### ISSUE TITLE
[Spec]  Rounded Corners

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#10]
# Rounded Corners

Rounded Corners are a common visual requirement.

![corners](https://cdn.dribbble.com/users/3860505/screenshots/11395419/media/504cd4b5d8be45643599db4e1b8961f7.png)

# API

We need to add an interface for defining what's required for a View to implement corner rounding (and provide CSS support):

```csharp
interface IRoundedCorner
{
	CornerRadius CornerRadius { get; }
	void CornerRadiusChanged(CornerRadius oldValue, CornerRadius newValue);
}
```

The CornerRadius BindableProperty can be implemented in one place:

```csharp
static class RoundedCorner
{
	public static readonly BindableProperty CornerRadiusProperty = 
	     BindableProperty.Create(nameof(CornerRadius), typeof(CornerRadius), typeof(IRoundedCorners));
}
```

The following Views are candidates for rounded corners:
* BoxView 
* Button
* Image
* ImageButton
* Layouts 
* ScrollView

# Scenarios

## C# Example

```csharp
var grid = new Grid();
grid.CornerRadius = new CornerRadius(12, 0, 12, 6);
```

## XAML Example

```xaml
<Grid
     CornerRadius="12, 0, 12, 6">
</Grid>
```

## Difficulty: Medium
Providing the interface is simple; individual implementations may vary in difficulty.

**Comment by aguywithcode** [comment]
Looks like Button has a [CornerRadiusProperty already](https://github.com/dotnet/maui/blob/build/System.Maui.Core/Button.cs#L51). Perhaps it should be extracted to a higher class in the tree perhaps View or VisualElement?

**Comment by ederbond** [comment]
Also make sure that if the element is set to have shadow, the shadow should be rounded too.
I've opened some issues for this in the past too. [https://github.com/xamarin/Xamarin.Forms/issues/3867](https://github.com/xamarin/Xamarin.Forms/issues/3867)
and here [https://github.com/xamarin/Xamarin.Forms/issues/3871](https://github.com/xamarin/Xamarin.Forms/issues/3871)

**Comment by MitchBomcanhao** [comment]
Would the rounded corners clip the content of the control?

**Comment by themronion** [comment]
What about single rounded corners on frame - like PancakeView? I think this is more desirable and wanted by xamarin devs. Thumbs up who agrees!
