### ISSUE TITLE
100th :)

### ISSUE THREAD

**Issue by mhrastegary77** [dotnet/maui#100]
## Summary
Can i stay here ? :)))))

**Comment by hartez** [comment]
I hate to be a buzzkill, but we gotta try to keep the open issue count down. :(

Also, c'mon - 100? This is software, you should have gone with a power of 2 :)

**Comment by Happypig375** [comment]
@hartez But 100 is a power of 2 though. 100 = 2^6.64385619...

**Comment by hartez** [comment]
![technicallycorrect](https://user-images.githubusercontent.com/538025/82737730-56c42280-9cf0-11ea-822d-57216e12e4c7.gif)
