### ISSUE TITLE
`Image` inside `Border` is rendered differently in XAML vs. Custom Control

### ISSUE THREAD

**Issue by nor0x** [dotnet/maui#10000]
### Description

I'm generating basically the same control in XAML and C# but it renders differently. I have a `Border `which wraps an `Image` here in XAML which was used within `MainPage.xaml`

```xml
<Border
    WidthRequest="400"
    HeightRequest="400">
    <Grid>
        <Image
            Source="grid.png"
            WidthRequest="800"
            HeightRequest="800" />
    </Grid>
</Border>
```

and here is it as a custom control:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Border
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="MauiFails.MyBorder"
    WidthRequest="400"
    HeightRequest="400">
    <Grid>
        <Image
            Source="grid.png"
            WidthRequest="800"
            HeightRequest="800" />
    </Grid>
</Border>
```
which i also add to the MainPage:

`<local:MyBorder  />`

the code is basically the same, so i was wondering why this renders differently?

as you can see in the screenshot the custom control (code in separate XAML file) is not clipped correctly (right side)
![image](https://user-images.githubusercontent.com/3210391/189174907-09f85c8d-ba13-47c9-8ea5-55852974d784.png)

also notice that on Android the image is not clipped by the border but the outer element (purple background)
![image](https://user-images.githubusercontent.com/3210391/189176142-ae1b21c8-0200-4f59-b4e8-eab70ba8a53b.png)

### Steps to Reproduce

1. See Repro or add the code from the description manually

### Link to public reproduction project repository

https://github.com/nor0x/MauiFails

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Android 11, Windows 22622.590, iOS 15

**Comment by jsuarezruiz** [comment]
I have been testing with:

1.
```
<Border 
    WidthRequest="400"
    HeightRequest="400"
    Background="Tomato">
    <Grid>
        <Image
            x:Name="firstImage"
            Source="grid.png"
            WidthRequest="400"
            HeightRequest="400" />
    </Grid>
</Border>
```
2.
```
<?xml version="1.0" encoding="utf-8"?>
<Border
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Maui.Controls.Sample.Pages.MyBorder"
    Background="Tomato">
    <Grid>
        <Image
            x:Name="firstImage"
            Source="grid.png"
            WidthRequest="400"
            HeightRequest="400" />
    </Grid>
</Border>
```
3.
```
var border = new Border()
{
    WidthRequest = 400,
    HeightRequest = 400,
    Background = Colors.Green,
    Content = new Grid()
    {
        Children =
        {
            new Image()
            {
                Source = "grid.png",
                WidthRequest = 400,
                HeightRequest = 400,
            }
        }
    }
};
```

![image](https://user-images.githubusercontent.com/6755973/189624092-970c53bd-4e07-4c70-80b1-09df62e07757.png)

Cannot see differences. Could you share more details?
