### ISSUE TITLE
Entry Control: When IsPassword is enabled, the placeholder text font is not the text font assigned to the Entry

### ISSUE THREAD

**Issue by jordan-hewitt** [dotnet/maui#10004]
### Description

This appears to be the same as the bug that was marked as resolved: https://github.com/dotnet/maui/issues/7966

Shown below, if you have an Entry with the property IsPassword set to True, the entry is not the correct font that was assigned:

Before, when IsPassword = True

<img width="319" alt="Screenshot 2022-09-08 134826" src="https://user-images.githubusercontent.com/16214224/189202161-ea843a06-f292-409b-a745-eafcb46b7876.png">

After, when IsPassword = False (toggled by the eye icon):

<img width="370" alt="Capture" src="https://user-images.githubusercontent.com/16214224/189202198-c96c3ead-d11f-4d51-b339-f1a6c8b99b75.PNG">

### Steps to Reproduce

1. Create a .NET MAUI app
2. Add an Entry to the app
3. Set a placeholder label
4. Set a font for the label (In my case, we used Poppins)
5. Set the property IsPassword to True
6. View that the placeholder text is not in Poppins
7. Set the property IsPassword to False
8. View that the placeholder text is in Poppins

### Link to public reproduction project repository

N/A

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

**Comment by jsuarezruiz** [comment]
This issue could be fixed by https://github.com/dotnet/maui/pull/8015
