### ISSUE TITLE
.NET Multi-platform App UI development is not an Option

### ISSUE THREAD

**Issue by John-Hatton** [dotnet/maui#10012]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: Windows 11

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

---

I was able to find "Mobile Development with .NET which seems to be similar.

**Comment by jfversluis** [comment]
Hey there @John-Hatton what version of Visual Studio are you using? You should be using Visual Studio 2022 17.3, you can see that at the top of the screen in the Visual Studio Installer.

![image](https://user-images.githubusercontent.com/939291/189329197-0fe2678c-eb57-4177-a3a1-0dbbcada946c.png)

**Comment by John-Hatton** [comment]
Yup, my VS installation was out of date. I updated to 17.3.3 and it's working now! Thanks!
