### ISSUE TITLE
Access denied error when deploy .net maui app by msix on windows

### ISSUE THREAD

**Issue by kamranattari4192** [dotnet/maui#10010]
### Description

I published .NET MAUI Windows MSIX to sideload that is signed with a valid certificate. When I click .msix file, nothing happened because msix extension was not known on windows 10 by default. It seems that I have to install App Installer from Microsoft Store to recognise msix extension. After installing App Installer, I clicked on .msix file it showed me installer window, when I clicked on Install button it showed me following error: App installation failed with error message: Access is denied. (0x80070005). Why am I getting this error? Then I open power shell without elevated admin rights and run Install.ps1 script it showed me Add-AppxPackage : Deployment failed with HRESULT: 0x80070005, Access is denied. error. After that I run power shell with elevated admin rights, and run Install.ps1, then it installed my package. So it is installing sideload package only from powershell with admin rights. How can we make it installable by double clicking misx file without admin rights?

### Steps to Reproduce

1. Create a MAUI app for windows
2. Publish it as sideload and sign with valid certificate
3. Click on .MSIX file, it shows installer window (if App Installer is installed).
4. Click install button, it shows error App installation failed with error message: Access is denied. (0x80070005).

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17763.0

**Comment by kamranattari4192** [comment]
Hi,
I created a simple Hello World .NET Maui project, its source code is here https://github.com/kamranattari4192/maui.git
I published it and signed the package with valid certificate, the published package can be downloaded from https://github.com/kamranattari4192/maui/releases/download/1.0.0.1/MauiApp1_1.0.2.0_Test.zip
When I double click on MauiApp1_1.0.2.0_x86.msix file, the installer screen is shown
When I click on Install, then it shows Access denied error.
My windows version is as followings:
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎30/‎10/‎2021
OS build	19042.1889
Serial number	PF36CD4R
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by hulltr1** [comment]
Any update on this subject?

**Comment by Elangovan4ever** [comment]
I'm also getting the same error. Any update on this issue?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 5.0. Not repro on windows platform.
![image](https://github.com/dotnet/maui/assets/77434865/d963fd63-6af7-4163-979f-6b0bb5581dc7)
