### ISSUE TITLE
[Android] Unable to change App.MainPage inside OnResume()

### ISSUE THREAD

**Issue by nicop85** [dotnet/maui#10024]
**Description**

I've found a strange behaviour after migrating my app from Xamarin to MAUI. An exception is thrown when I resume the app that was in a background state, and try to set the App.MainPage inside OnResume method. The exception is the following:

Java.Lang.IllegalStateException: 'Can not perform this action after onSaveInstanceState'

<img width="608" alt="image" src="https://user-images.githubusercontent.com/2288412/189409050-16136e0e-86ff-40a4-8de1-cf6ec9628fa8.png">

**Steps to reproduce**

1- User starts the app and a LoginPage shows up that inherits from ContentPage. (App.MainPage = new LoginPage())
2- User press the login button and (after validating the user) it redirects the user to the HomePage that inherits from Shell. (App.MainPage = new HomePage())
3- The user presses the home button of the device, taking the app to the background state. 
4- The user resumes the app and, as he is already logged in, it will send him directly to the HomePage. (App.MainPage = new HomePage())
5- The app crashed when trying to set the App.MainPage to the HomePage.

**Strange things I've noted while testing**

1- If I don't take the app to the background, I can change the App.MainPage all the times that I want without any problems.
2- If I use only a Shell (no login page, the user go straight to the HomePage), the OnResume works as expected and no exception is raised.

**Link to public project repository to reproduce the error**

https://github.com/nicop85/TestShell

**Version with bug**
6.0.486 (Current)

**Last version that worked well**
Unknown/Other

**Affected platforms**
Android

**Affected platform versions**
Tested on Android >= 9

**Did you find any workaround?**
No response

**Relevant log output**
No response

**Comment by PureWeen** [comment]
This might be fixed by https://github.com/dotnet/maui/pull/9955

If you add a delay before setting the `MainPage` does that resolve the issue?

**Comment by nicop85** [comment]
Hi @PureWeen, thanks for your answer. 

I tried what you said by adding the following

```
Task.Delay(5000).ContinueWith(
	t => GoToHomePage()
);
```

and I got a different exception:

`Java.Lang.IllegalArgumentException: 'No view found for id 0x8 (unknown) for fragment ShellItemRenderer{4b5a41d} (3eb92f41-245c-4ea9-a41d-88f6fee7fa0b id=0x8)'`

Just to be clear, the call to GoToHomePage() just make a `MainPage = new HomePage()`.

Does this makes sense with what you pointed out in the #9955 ?

**Comment by PureWeen** [comment]
@nicop85 #9955 should fix 

> Java.Lang.IllegalArgumentException: 'No view found for id 0x8 (unknown) for fragment ShellItemRenderer{4b5a41d} (3eb92f41-245c-4ea9-a41d-88f6fee7fa0b id=0x8)'

One thing I'd like to note is that you don't need to swap out the `MainPage` with shell you can set different items to visible or not visible if the user is logged in. 

I'm pretty sure you can even just have an empty shell and once you've determined if the user is logged in or not just add items based on that

**Comment by nicop85** [comment]
@PureWeen I've tried what you suggested about setting the MainPage once with a Shell, and then show/hide different views depending if the user is logged in or not. Everything seems to be working except for one thing.

In my app flow, I want to be able to display a biometrics unlock page every time the user resumes the app from background for security reasons. So, continuing with the previous changes, I've override the OnResume() method in the App.xaml.cs and make a call to my current Shell instance's OnResume(). Inside that last method, I made a `Navigation.PushModalAsync(new UnlockPage())` to display the biometrics unlock page on top of whatever page the user had left the app (preserving its state).

Doing so, I ended up with the same exception `Java.Lang.IllegalStateException: 'Can not perform this action after onSaveInstanceState'`.

To achieve what I want, I have to make a regular PushAsync of the UnlockPage and set it's Shell.NavBarIsVisible to False to avoid having the back button visible on the UnlockPage. This way I didn't get the exception.

Seems like there are some specific conditions, where modifying the pages stack raise that exception

**Comment by PureWeen** [comment]
@nicop85 can you create a branch or upload a new sample with the scenario you are outlining ?

**Comment by nicop85** [comment]
@PureWeen sure, no problem. I pushed another branch with those changes (branch ShellWithBiometricsUnlockPage).
Look at the ShowUnlockPage() method in the HomePage.xaml.cs

Let me know if you need something else.

**Comment by nicop85** [comment]
Hi! Just to let you know that you can go ahead and close this issue. I was reviewing it and it was fixed in some of the previous versions.
Thanks!
