### ISSUE TITLE
Multi-window memory leak

### ISSUE THREAD

**Issue by vfabulokwe** [dotnet/maui#10029]
### Description

Closing a window results in a memory leak. The windows are never GC’d and often all their content is still visible within memory. Comparing this behavior with WinUI3 I have found that it works correctly in WinUI3, windows are created and recycled, counts go up, and back down. On MAUI the same process results in a steady increase in Window counts. 

### Steps to Reproduce

1. Create new MAUI app
2. Add a button in the MainPage.xaml and implement the Clicked event handler in the code behind.
```c#
// button - to open a new window
private void BlankWinLeakBtn_Clicked(object sender, EventArgs e)
{
var page = new ContentPage()
{
Content = new Label()
{
Text = ""
}
};
var win = new Window()
{
Page = page
};

    App.Current.OpenWindow(win);
}
```
4.	Click on the button 
5.	Take snapshot 
6.	Close window 
7.	Click button again 
8.	Take snapshot 
9.	Close window 
10.	Repeat steps 1-6 multiple times 
11.	Compare snapshots 

**Expected Result:**
Ref count should go down when a window is closed.

**Actual Result:**
Ref count keeps going up, window is never GC'd.

### Link to public reproduction project repository

NA

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

**Comment by jsuarezruiz** [comment]
Related with https://github.com/microsoft/microsoft-ui-xaml/issues/7617

**Comment by mouralabank** [comment]
The same problem here, any workaround?

**Comment by danielancines** [comment]
I've been making some tests here, and the problem appears to be in a Window object that still forever allocated, in my tests, even I closed New Window and check if it removed from App.Current.Windows collection, the object never will be collect by GC and I cannot find who is locking up on the object tree. Unfortunately I didn't find any workaround for this issue, do you guys have any idea?
