### ISSUE TITLE
DisplayAlert popup on multiple open windows

### ISSUE THREAD

**Issue by vfabulokwe** [dotnet/maui#10026]
### Description

Calling DisplayAlert when multiple windows are open, causes the alert popup to display on all open windows.

### Steps to Reproduce

1. Create new MAUI app
2. Add 2 buttons in the MainPage.xaml and implement the Clicked events in the code behind.

```c#
// button 1 - to open a new window
private void BlankWinLeakBtn_Clicked(object sender, EventArgs e)
	{
        var page = new ContentPage()
        {
            Content = new Label()
            {
                Text = ""
            }
        };
        var win = new Window()
        {
            Page = page
        };

        App.Current.OpenWindow(win);
    }

// button 2 - to display alert
    private void AlertPopUpBtn_Clicked(object sender, EventArgs e)
    {
        DisplayAlert("Alert", "You have been alerted", "OK");
    }
```

3. Click on button 1 a few times to open multiple windows.
4. Click on button 2 to display alert and click OK to dismiss the alert.

**Expected Result:**
Alert is dismissed.

**Actual Result:**
Alert dismisses and pops up on all open windows, one at a time.

### Link to public reproduction project repository

NA

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

**Comment by RNavaneethKumar** [comment]
Is there any workaround for this at the moment?
