### ISSUE TITLE
Infinite ScrollView with BlazorWebView

### ISSUE THREAD

**Issue by Laftek** [dotnet/maui#10043]
### Description

When I use `<ScrollView>` and nest BlazorWebView it will create infinite scroll.  How can I get rid of it. The reason I am using it is because I wanted to get advantage of xaml implementation of Lottie.

I tried to find workaround (different type of stacklayout, using grid ...) but nothing helped. 

Thanks.

```xaml
    <ScrollView>
        <VerticalStackLayout>
            <skia:SKLottieView
                Source="jumping_pin.json"
                RepeatCount="-1"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="200"
                WidthRequest="200"
                HorizontalOptions="Center" />

            <BlazorWebView HostPage="wwwroot/index.html">
                <BlazorWebView.RootComponents>
                    <RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
                </BlazorWebView.RootComponents>
            </BlazorWebView>

        </VerticalStackLayout>
    </ScrollView>
```

### Steps to Reproduce

1. Create MAUI Blazor
2. Nest BlazorWebView inside of `<ScrollView>`

### Link to public reproduction project repository

dummy link

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 32

### Did you find any workaround?

No

**Comment by Laftek** [comment]
Its weird. I tried it now and its working. Bad thing is that I am not aware of any UI changes that should impact this. I will let it open for now in case you have idea what could be the issue.

**Comment by drasticactions** [comment]
I couldn't repro it, so I'm gonna close it and it can be reopened if it can be.

IMO my guess would be that the webview itself could have issues with being nested in this way? It feels like something that would be outside of the specific Blazor WebView.
