### ISSUE TITLE
Hide "Loading..." behind the splash screen or any other solution

### ISSUE THREAD

**Issue by Laftek** [dotnet/maui#10044]
### Description

I am not sure if I am doing something wrong but it does not make sense to me that Loading... screen is displaying after app launch. Its not webassembly so it cannot just be hidden in "splash screen" process? It not really pretty user experience to see this "flash". I know its a duplicate of #6438 but there is not solution to this at all.

Thank you.

@danroth27 

### Public API Changes

I dont know.

### Intended Use-Case

Much better user experience.

**Comment by Laftek** [comment]
I checked how it is done with podcast app but it's still not that elegant solution. I counted 3 screens before app loaded.

**Comment by janseris** [comment]
I am solving it by placing similar graphics as in splashscreen instead of the Loading.. HTML

**Comment by Laftek** [comment]
@janseris thanks for the answer. Are you experiencing any flashes or its just "one" splash screen?

**Comment by janseris** [comment]
@Laftek a quick check shows 1 small flash between Android splash screen and "Blazor splash/loading screen" and all subsequent attempts are transitioning without a flash. Note: tested on Sony Xperia 5 II, not sure about slower devices and not sure about emulator (haven't developed the app in a while now because the Android splash screen hasn't been working properly and/or the fixes from June haven't been released https://github.com/dotnet/maui/pull/8020#issuecomment-1243053644)

**Comment by Laftek** [comment]
@janseris Thanks! I will check it out. I hope they will fix android splash screen soon. But anyway I guess I will use full-time MUAI after .NET7 release.

**Comment by pekspro** [comment]
Is this even possible? What happens if you default page is an ordinary XAML page, and Blazor is used on the next page?

I agree the `Loading...` text is annoying. Here is an example how to center the text on the screen, and fade in the text - which will make it unlikely for the user to ever see it: https://github.com/dotnet/maui/issues/18548

**Comment by Eilon** [comment]
Hi, I posted a sample that shows how to make a nicer loading screen on the other issue: https://github.com/dotnet/maui/issues/18548#issuecomment-1900958614

**Comment by danielchalmers** [comment]
Hi @Eilon, am I mistaken or does that still result in a loading screen in addition to the splash screen? Will we be able to combine them in the near future?

**Comment by danielchalmers** [comment]
> Yeah the splash screen is still a separate thing that is shown immediately when an app is launched. The sample I linked doesn't do anything with splash screens. But if anyone knows a good way to transition from splash screen to a loading screen that could help folks too. It's not something I've read much on but I'm pretty sure there's info out there for each platform, though it might not be .NET MAUI-specific or Blazor Hybrid-specific.

Thanks for the info and thanks for the repo regardless, it's a cool trick I wasn't aware of! @Eilon

**Comment by danroth27** [comment]
There are ways to handle this in your app. See @Eilon's comment for details: https://github.com/dotnet/maui/issues/18548#issuecomment-1900958614.

**Comment by danielchalmers** [comment]
@danroth27 Maybe I'm not understanding it but I don't see how that's an appropriate solution when you still see the splash screen on Android for example:

https://github.com/dotnet/maui/assets/7112040/525d0c36-e937-4a06-a8ca-91a1fc600414

Isn't the linked solution just a different splash screen? Not combining them?

**Comment by Eilon** [comment]
@danielchalmers I think you're right, the Loading is separate from the Splash Screen. But I don't think there's any BlazorWebView-specific thing here, but a general .NET MAUI and/or Android/iOS pattern that would need to be implemented as part of the app.

These are the docs I'm aware of:

* General .NET MAUI splash screen info: https://learn.microsoft.com/dotnet/maui/user-interface/images/splashscreen
* Xamarin Android docs on splash screens: https://learn.microsoft.com/xamarin/android/user-interface/splash-screen (this probably still applies the same way in .NET MAUI)

And beyond that I think each platform has a pattern for transitioning from the splash screen to the app (if you don't want just the default behavior).

**Comment by danielchalmers** [comment]
Thanks @Eilon.

I guess the problem is that the splash screen is only up until `CreateMauiApp` is complete, but we need more control of when it transitions to the `MainPage`.

Should I should create a new, more general issue?

**Comment by Eilon** [comment]
> Thanks @Eilon.
> 
> I guess the problem is that the splash screen is only up until `CreateMauiApp` is complete, but we need more control of when it transitions to the `MainPage`.
> 
> Should I should create a new, more general issue?

I think that would make sense (unless there's already an existing issue for it).
