### ISSUE TITLE
Permission Denied returned when approximate location is selected

### ISSUE THREAD

**Issue by kojini** [dotnet/maui#10053]
### Description

I am developing a MAUI app for Android.  
From API 31, when you request location permission, you can choose either approximate location or precise location. When approximate location is selected, `await Permissions.RequestAsync<Permissions.LocationWhenInUse>();` returns `PermissionStatus.Denied`. I think it should return something else (maybe `Restricted`?), not `Denied`.  

I found an issue describing the same issue in Xamarin repo: https://github.com/xamarin/Essentials/issues/1912 and it seems to be fixed for Xamarin. I assume that it's not fixed in MAUI, but could anyone please confirm this is still an issue in MAUI?  
I don't know if this is an Android specific issue.  

Environment/Versions:  
Visual Studio 17.4.0 Preview 1.0  
Android 12 (API 31 and higher)

### Steps to Reproduce

- Call `await Permissions.RequestAsync<Permissions.LocationWhenInUse>();`, which shows a popup asking whether you allow approximate location or precise location or not allow location at all.
- Select approximate location (doesn't matter whether you choose only this time or when app is in use)
- See the return value is `PermissionStatus.Denied` 

### Link to public reproduction project repository

https://github.com/kojini/PermissionTest

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 API 31 and higher

### Did you find any workaround?

No

**Comment by ibpet11** [comment]
I feel this issue should be attended to timely. I have a new project and I keep getting "Location services are not enabled on device." even after the user select location permission for now when prompted. Please help out
