### ISSUE TITLE
[Windows] Cannot hide caption buttons from title bar

### ISSUE THREAD

**Issue by juanmalm** [dotnet/maui#10057]
### Description

On a native WinUI 3 project you can fully hide title bar and caption buttons using this code:
```
        public MainWindow()
        {
            this.InitializeComponent();
            var presenter = GetAppWindowAndPresenter();
            presenter.IsMaximizable = false;
            presenter.IsMinimizable = false;
            presenter.IsAlwaysOnTop = true;
            presenter.IsResizable = false;
            presenter.SetBorderAndTitleBar(false, false);
        }

        private OverlappedPresenter GetAppWindowAndPresenter()
        {
            var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
            WindowId myWndId = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);
            var _apw = AppWindow.GetFromWindowId(myWndId);
            return _apw.Presenter as OverlappedPresenter;
        }
```
Running the app, the title bar and caption buttons are gone:
![image](https://user-images.githubusercontent.com/22932620/189617763-bbbeb955-1d33-4003-b137-2e924d6a9765.png)

However, the same code snippet on a MAUI project targeting Windows does not totally hide title bar and caption buttons:
```
        Microsoft.Maui.Handlers.WindowHandler.Mapper.AppendToMapping(nameof(IWindow), (handler, view) =>
        {
#if WINDOWS
            var nativeWindow = handler.PlatformView;
            nativeWindow.Activate();

            var windowHandle = WindowNative.GetWindowHandle(nativeWindow);
            var windowId = Win32Interop.GetWindowIdFromWindow(windowHandle);
            var appWindow = AppWindow.GetFromWindowId(windowId);
            var presenter = appWindow.Presenter as OverlappedPresenter;
            presenter.IsMaximizable = false;
            presenter.IsMinimizable = false;
            presenter.IsAlwaysOnTop = true;
            presenter.IsResizable = false;
            presenter.SetBorderAndTitleBar(false, false);
#endif
        });
```
![image](https://user-images.githubusercontent.com/22932620/189618113-9ac13c92-11a5-429b-80c6-76ed0ca83b76.png)

### Steps to Reproduce

1. Clone reproduction project repository: https://github.com/juanmalm/maui_titlebar_issue
2. Build and run App1.sln
3. Title bar and caption buttons are gone
4. Build and run MauiApp1.sln
5. Title bar and caption buttons partially appear

### Link to public reproduction project repository

https://github.com/juanmalm/maui_titlebar_issue

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
I think this has mostly to do with the fact that the lifecycle is a little different with .NET MAUI. You totally can do this, but not exactly the same as with WinUI.

Coincidentally I have written about it here: https://blog.verslu.is/maui/full-screen-disable-minimize-maximize-for-net-maui-windows-apps/ with the code being here: https://github.com/jfversluis/MauiWindowsFullscreenMinimizeMaximizeSample

What you want to do is hook into the lifecycle events we have setup for windows (note: a window, not Windows). You can do that in the `MauiProgram` when the app is setup:

```csharp
public static MauiApp CreateMauiApp()
{
    var builder = MauiApp.CreateBuilder();
    builder
        .UseMauiApp<App>()
        .ConfigureFonts(fonts =>
        {
            fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
            fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
        });

#if WINDOWS
    builder.ConfigureLifecycleEvents(events =>
    {
        // Make sure to add "using Microsoft.Maui.LifecycleEvents;" in the top of the file 
        events.AddWindows(windowsLifecycleBuilder =>
        {
            windowsLifecycleBuilder.OnWindowCreated(window =>
            {
                window.ExtendsContentIntoTitleBar = false;
                var handle = WinRT.Interop.WindowNative.GetWindowHandle(window);
                var id = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(handle);
                var appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(id);
                switch (appWindow.Presenter)
                {
                    case Microsoft.UI.Windowing.OverlappedPresenter overlappedPresenter:
                        overlappedPresenter.SetBorderAndTitleBar(false, false);
                        overlappedPresenter.Maximize();
                        break;
                }
            });
        });
    });
#endif

#if DEBUG
    builder.Logging.AddDebug();
#endif

    return builder.Build();
}
```

The important part is in the `#if WINDOWS` block. First we set the `ExtendsContentIntoTitleBar` to false. I think that might be the cause of the small titlebar that you still see in your scenario. Maybe setting that for you is even enough. From there, I think we're doing pretty much the same thing to get the window handle, window, etc. and then set the right properties on the `Presenter`. Of course if you want to make this specific to one type of window or just one window you'll have to implement some logic to only do it for that window.

The above is for opening the window initially, you can also do it on some user interaction. That code with different scenarios can be found here: https://github.com/jfversluis/MauiWindowsFullscreenMinimizeMaximizeSample/blob/main/MauiWindowsFullscreenMinimizeMaximizeSample/MainPage.xaml.cs

If there is anything still missing from this feel free to reach out and/or open a new issue with that specific scenario.

Thanks!
