### ISSUE TITLE
MAUI 17.4pr1, Markup extension cause debugger fail to attach

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#10081]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-174pr1-Markup-extension-cause-deb/10132657)._

---
1, create a sample maui app.  
2, in MainPage.xaml.cs, add a new class

```  
public class MyVarExtension : IMarkupExtension
{
	public object ProvideValue(IServiceProvider serviceProvider)
	{
		return 20;
	}
}
  
```

3, in MainPage.xaml, modify ContentPage as

```  
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:mycode="clr-namespace:MauiApp1"
             x:Class="MauiApp1.MainPage"> 
```

modify Label.FontSize as

```  
FontSize="{mycode:MyVar}"
  
```

4, Click start debug.  
5, Got a unhandled win32 exception, debugger attach warning.  
I don’t know why the locale is English but the alarm window is still Chinese.
6, if I change "return 20;" to "return (double)20;” in step 2, the problem disappeared; however, I don't think a type cast problem(or some error I don't understand) should cause the debugger failed to attach....

---
#### Lee Kiilii on 8/27/2022, 08:00 AM: 

(private comment, text removed)
#### Feedback Bot on 8/28/2022, 07:35 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
@StephaneDelcroix  thoughts?

**Comment by samhouts** [comment]
I'm wondering if it's another manifestation of https://github.com/dotnet/maui/issues/6070.

**Comment by StephaneDelcroix** [comment]
@chabiss, @drasticactions does this ring a bell ?

**Comment by drasticactions** [comment]
It could be a XAML Language Service issue, @mgoertz-msft would you know?

**Comment by mgoertz-msft** [comment]
@drasticactions I don't see how the XAML Language Service could prevent the debugger from attaching. Those components aren't related at all.

**Comment by drasticactions** [comment]
Well, I doubt it's something in hot reload, so I'm grasping at straws, as it were, lol.

I guess we would need more information as to what could be happening here. What happens if you run that code without debugging? What happens if you launch and attach after the fact? What is the actual logs or stack trace?

**Comment by mgoertz-msft** [comment]
Or, if this repros, then you could ask someone on the debugger team to debug it.

**Comment by jfversluis** [comment]
I see a lot of guesses but nothing from the author. So closing this for now. If this is still an issue, please open a new one.
