### ISSUE TITLE
Can't run iOS simulator, in spite of being successfully connected to Mac.

### ISSUE THREAD

**Issue by tradegear** [dotnet/maui#10085]
### Description

I bought a new mac for this purpose. Nothing else installed besides Mono and Xcode. Existing documentation didn't inform me whether I had to install Mono, XCode, both/neither? I installed both after trial-and-error.
From VS2022 Maui Client project, I connected to my Mac via the toolbar. Everything seems fine.
I went into Tools --> Options --> Xamarin --> iOS. The Mac didn't appear connected there. There is an inconsistency between the status of the Mac connection when displayed from the toolbar, and when the connection status is displayed in the Tools Options Xamarin iOS panel. I disconnected and then connected via the Tools Options Xamarin iOS panel, and this time in this panel it appears my Mac is connected to the correct IP of the Mac.
"Simulator" - "Remote Simulator to Windows" is checked on enabled. I toggled that in addition to toggling things by restarting both machines and getting things reconnected.
Here is the main problem: I am unable to run an iOS simulator, even with a confirmed connected Mac. I really haven't made many changes to my VS2022 environment, and I've done nothing to this new Mac except install mono and XCode.
I have a Maui Client that runs fine in the Windows Machine environment.
The same Maui Client runs fine in an Android simulator (although there is an issue with Android connecting to local web api, which I have submitted feedback on that issue separately.)
The same Maui Client will not run an iOS simulator. There appear to be no iOS simulators in my list. I can't see how to get my iOS simulator list populated. I choose "iOS Simulator", and then the only option is "iOS Simulator". When I attempt to run the Maui Client app from "iOS simulator", I get this error:
Please select a valid device before running the application.
Well, there are no simulators to select from.
After about an hour googling around and looking for other fixes, this (a) appears to be a common problem (b) None of the proposed solutions resolve the issue.
New Mac.
Pretty much clean Windows 11 machine with VS2022 updated to latest as of 2022-09-10.
I'm at a loss for what to try next. I'll greatly appreciate any fix advice.

### Steps to Reproduce

Buy new mac.
Install Mono and XCode.
Connect to Mac in VS.
Try to run project in any iOS emulator.

### Link to public reproduction project repository

x

### Version with bug

6.0.408

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

any iOS

### Did you find any workaround?

No

**Comment by tradegear** [comment]
I did indeed install xCode 14 on Friday night.  Maybe I'll do a factory refresh on the Mac and go xCode 13.   That had crossed my mind, but I had the optimistic expectation that such an important function would have been covered over the months of xCode 14 RC's.

**Comment by HiTechMagic** [comment]
Had same problem. Following above suggestion, I uninstalled XCode 14 and installed XCode 13. Everything now working.

**Comment by HiTechMagic** [comment]
"Everything" may have been premature. iOS simulator starts up, but the standard Maui app does not appear anywhere.

**Comment by g4mb10r** [comment]
@samhouts This might be a P1?  Most Macs auto-update these days, which means XCode 14 will automatically install and break MAUI/Xamarin development.

**Comment by samhouts** [comment]
Thanks! Support is on the way! In the meantime, please visit https://github.com/xamarin/xamarin-macios/issues/15954 for more information.

**Comment by g4mb10r** [comment]
Thanks @samhouts !
