### ISSUE TITLE
await Shell.Current.GoToAsync(sPageName) results in An unhandled win32 exception occurred in [41992]

### ISSUE THREAD

**Issue by tradegear** [dotnet/maui#10084]
### Description

I've reviewed some youtube tutorials (Montemagno, Versluis) and countless stackoverflow and various google-located docs.
I have attempted to implement navigation using the "shell", for example buttons on one page that try to open another page; using the CommunityToolkit.MVVM and the RelayCommand on a button in the XAML which calls this in the ViewModel:

        [RelayCommand]
        public async Task EnsureValidSessionElsePromptAsync()
        {
            if (NotValidSession)
            {
                string sPageName = nameof(PageRegisterDevice);
                await Shell.Current.GoToAsync(sPageName);
            }
        }

That's just one example.
Or, if I add code to the main page code and try to get it to look at a setting in the ViewModel, and if something isn't initialized, I want it to go to a "PageRegisterdevice" page.  For example:

        if (sessionTokenViewModel.NotValidSession)
        {
            string sPageName = nameof(PageRegisterDevice);
            var task = new Task(async () => await Shell.Current.GoToAsync(sPageName));
        }

These pages ARE registered in the AppShell.xaml (but perhaps not correctly?):

<Shell
    x:Class="MTRMauiClient.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MTRMauiClient"
    Shell.FlyoutBehavior="Disabled">

    <ShellContent
        Title="Register Device"
        ContentTemplate="{DataTemplate local:Pages.PageRegisterDevice}"
        Route="Pages.PageRegisterDevice"/>

    <ShellContent
        Title="Main Page from xaml"
        ContentTemplate="{DataTemplate local:Pages.PageMainPage}"
        Route="Pages.PageMainPage"/>

</Shell>

Whichever shell content declaration that appears first above is the one that appears when I run the app.

No matter what I try, when the code that ultimately tries to do the 
Shell.Current.GoToAsync(sPageName));

results in a
Choose Just-In-Time Debugger
An unhandled win32 exception occurred in [41992] (my project name.exe)
Warning:
A debugger is attached to (my project name.exe) but not configured to debug this unhandled exception.  To debug this exception, detach the current debugger.

I don't really know where to start on this.  This just shouldn't be this hard.  The whole shell thing doesn't seem to work.  Sorry if that's a broad statement, but yeah, that's what I'm sticking to for now because I literally can't create any page navigation.

This is my third major breaking issue with this framework.  Is this ready for prime-time or is this going to go the way of Silverlight?
I don't even know if I'm posting these issues in the correct places.
Thanks :)

### Steps to Reproduce

I'd have to upload the whole project.
Initially if you could point me to (a) good documentation on the navigation - because what I've used so far has proven insufficient to get me going. (b) point me to any existing workarounds or solutions to this type of issue.
I have found in general that really ugly errors completely hose the debugging system.

### Link to public reproduction project repository

x

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Only tested on Windows Machine (no sense in trying others)

### Did you find any workaround?

No workaround.

### Relevant log output

```shell
I do not know where to locate log output.
```

**Comment by marcmognol** [comment]
Hi,

I think that your routes are not well declared, could you please replace in AppShell.xaml route attributes:

From:
Route="Pages.PageRegisterDevice"

To:
Route="PageRegisterDevice"

And

From:
Route="Pages.PageMainPage"

To:
Route="PageMainPage"


Marc
