### ISSUE TITLE
Toggle button OnColor for Off state not working in iOS, also VisualStateManager is also not working.   

### ISSUE THREAD

**Issue by divyesh008** [dotnet/maui#10099]
### Description

I want to change the OnColor and ThumbColor of the Switch control according to the On/Off state. 

In MAUI Switch control's OnColor property and ThumbColor properties are not working for iOS if handled from code behind. And it does not work properly in both Android & iOS in XAML using VisualStateManager. 

### 1. Using VisualStateManager (Does not work in Android or iOS) 
```html
<Switch IsToggled = "True" >
    <VisualStateManager.VisualStateGroups >
        < VisualStateGroup x:Name="CommonStates">
            <VisualState x:Name="On">
                <VisualState.Setters>
                    <Setter Property = "ThumbColor"
                            Value="MediumSpringGreen" />
                    <Setter Property = "OnColor"
                            Value="MediumSpringGreen" />
                </VisualState.Setters>
            </VisualState>
            <VisualState x:Name="Off">
                <VisualState.Setters>
                    <Setter Property = "ThumbColor"
                            Value="Red" />
                </VisualState.Setters>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>
</Switch>
```

<hr/>

### 2. Handled from code behind class, it does not work in iOS, in Android works fine. In iOS when changing the Switch state to Off it does not change the OnColor and ThumbColor like it does in Android. 
```html
void OnSiteToggle_Toggled(System.Object sender, Microsoft.Maui.Controls.ToggledEventArgs e)
{
    if (e.Value)
    {
        OnSiteToggle.OnColor = Color.FromArgb("#7C5FDF");
        OnSiteToggle.ThumbColor = Color.FromArgb("#512BD4");
    }
    else
    {
        OnSiteToggle.OnColor = Color.FromArgb("#969696");
        OnSiteToggle.ThumbColor = Color.FromArgb("#DFD8F7");
    }
}
```

### Steps to Reproduce

1. Create a new .Net Maui project 
2. Take a switch control on the page 
3. Try to change the OnColor and ThumbColor properties of Switch control based on the ON/OFF state. 

Follow the attached project to reproduce the reported bug. Maui

### Link to public reproduction project repository

https://github.com/divyesh008/MauiLabel_Bug.git

### Version with bug

6.0.400

### Last version that worked well

6.0.400

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android 10, 11 and up 

### Did you find any workaround?

No, not yet

**Comment by arkadym** [comment]
Just wondering - how to use MAUI for development ? There are hell of bugs, and MS announced that as stable release! But all bug reports are moving to backlog! I'm trying to use MAUI for one of my projects but almost gave up because months are passed with no any fixes, every platform has issues. The whole idea write single app which will work 4 platforms - is not working!
There is no any release schedule, couple months ago there are SR idea appeared and it gave a hope for some fixes to come, but i see it not working anymore.
Preparing another bug report and found msftbot moving all new issues to backlog (... It is very little patience left, before moving to flutter or electron... From comments here in issues see i'm not along who upset with MAUI. I started thinking it will be like Xamarin, cool idea but same will be buggy thing which can be used for very limited project types, just simple apps. Any more or less complex UI is not possible to implement here...

**Comment by divyesh008** [comment]
@arkadym I can understand your concern, I'm also facing a lot of challenges while working with MAUI as it does have a lot to cover yet. It's not stable yet so do not move your production-ready projects to MAUI as of now.

**Comment by PureWeen** [comment]
If you specify a

```XAML
<Setter Property = "OnColor"
                            Value="MediumSpringGreen" />
```

Inside `<VisualState x:Name="Off">` does it start working on iOS?

**Comment by divyesh008** [comment]
No it does not 

> If you specify a
> 
> ```
> <Setter Property = "OnColor"
>                             Value="MediumSpringGreen" />
> ```
> 
> Inside `<VisualState x:Name="Off">` does it start working on iOS?

No it does not.

**Comment by AndreasReitberger** [comment]
Following, facing the same issue on iOS.

**Comment by espenrl** [comment]
This fixes it for me. Based on #10758

``` CSharp
// add to MauiProgram
#if IOS
                SwitchHandler.Mapper.AppendToMapping(nameof(ISwitch.IsOn), MapSwitchIsOn);
#endif

#if IOS
    /// <summary>
    /// ISSUE: Toggle button OnColor for Off state not working in iOS
    /// https://github.com/dotnet/maui/issues/10099
    /// </summary>
    public static void MapSwitchIsOn(ISwitchHandler handler, ISwitch view)
    {
        if (view == null)
            return;

        var uiSwitch = handler.PlatformView;
        if (uiSwitch == null)
            return;

        var uIView = OperatingSystem.IsIOSVersionAtLeast(13) || OperatingSystem.IsTvOSVersionAtLeast(13)
            ? uiSwitch.Subviews?[0]?.Subviews?[0]
            : uiSwitch.Subviews?[0]?.Subviews?[0]?.Subviews?[0];

        if (uIView is null)
            return;

        if (!view.IsOn)
        {
            // iOS 13+ uses the UIColor.SecondarySystemFill to support Light and Dark mode
            // else, use the RGBA equivalent of UIColor.SecondarySystemFill in Light mode
            uIView.BackgroundColor = OperatingSystem.IsIOSVersionAtLeast(13)
                ? UIKit.UIColor.SecondarySystemFill
                : UIKit.UIColor.FromRGBA(120, 120, 128, 40);
        }
        else if (view.TrackColor is not null)
        {
            uiSwitch.OnTintColor = view.TrackColor.ToPlatform();
            uIView.BackgroundColor = uiSwitch.OnTintColor;
        }
    }
#endif
```

**Comment by fgiacomelli** [comment]
> This fixes it for me. Based on #10758

it works like a charm, thanks for sharing
