### ISSUE TITLE
Destroying event is not fired on Android

### ISSUE THREAD

**Issue by SymxnCreator** [dotnet/maui#10091]
### Description

Hello,

As you know, you can add the following code to App.xaml.cs:

```
    protected override Window CreateWindow(IActivationState activationState)
    {
        Window window = base.CreateWindow(activationState);  

        window.Created += (s, e) =>
        {
        };

        window.Destroying += (s, e) =>
        {
            // Not fired on Android
            Debug.WriteLine("App is destroying.");
        };

        return window;
    }
```

Unfortunately the Destroying event is not fired on Android. It works on Windows. I haven't been able to test it on iOS and MacOS yet.

### Steps to Reproduce

1. Create a .NET MAUI App
2. Paste the code above into the App.xaml.cs.
3. Launch the app in debug mode on Android.
4. Close the app.

Expected outcome: The text is written to the output.
Actual outcome: The text is not written to the output.

### Link to public reproduction project repository

-

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13 (probably all versions)

**Comment by PureWeen** [comment]
[Duplicate](https://github.com/dotnet/maui/issues/6993)
