### ISSUE TITLE
Make a weekly .NET MAUI Community Standup

### ISSUE THREAD

**Issue by ncarandini** [dotnet/maui#101]
It would be great if you could arrange a weekly appointment like the [ASP.NET Community Standup](https://www.youtube.com/playlist?list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL) dedicated to Maui, where each week we can follow development of the project, hosted by @davidortinau, @jamesmontemagno et all. (like Damian Edwards with Scott Hanselman et all. on the .NET Core show).

Actually we need to follow a number of different  sources (blog pages, twitch channels, GitHub Maui project issues, ...) to stay up to date. It would be really helpful to have a single source where every week we can go and have a resumé of what's going on, what has been done and what's coming next.

Moreover, someone could act like Jon Galloway with a list of other cool sources of info (some interesting blog, code spike, twitch recording, etc.).

Please, do this!

**Comment by charlesroddie** [comment]
Would make sense once there is a community, i.e. after release.

**Comment by giuseppenovielli** [comment]
I think also an official blog like Xamarin Blog https://devblogs.microsoft.com/xamarin/  
that contains small article and all contents, link, references about all .Net MAUI update and progress.

**Comment by ncarandini** [comment]
> Would make sense once there is a community, i.e. after release.

I don't agree, just look at the first ASP.NET vNext (even prior of naming it Core!) so you can better understand what I mean: [ASP.NET Community Standup - Sept 2nd, 2014 - Introduction to ASP.NET vNext, how and why?](https://www.youtube.com/watch?v=1rLbT6pBtak&list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL&index=188&t=0s)

> I think also an official blog like Xamarin Blog https://devblogs.microsoft.com/xamarin/
> that contains small article and all contents, link, references about all .Net MAUI update and progress.

It is not the same thing, the Xamarin blog is about Xamarin, I'd like to have a weekly appointment about .NET MAUI. Please see the linked video, the first episode explain much better than I've done the purpose of it.
