### ISSUE TITLE
Android: UI elements disappear when showing page, the 2nd time

### ISSUE THREAD

**Issue by jbe2277** [dotnet/maui#10108]
### Description

On Android the UI elements from the `TabbedPage` disappear when showing the page, the 2nd time:
![maui-android-issue](https://user-images.githubusercontent.com/10452896/190070841-11f01105-ba92-45e9-b63e-da36a6c6e5c6.gif)

On Windows it works correct:
![maui-windows-works](https://user-images.githubusercontent.com/10452896/190070862-53caccbc-b5f7-49da-8912-dcf4a1653b78.gif)

**Xamarin**: This App worked correct on Xamarin 5. The issue occurs just after migration to **Maui**.

### Steps to Reproduce

- Clone this repo: https://github.com/jbe2277/waf/tree/69803cef490970a344c370616021464f59ae201d
- Open src\NewsReader\NewsReader.sln

### Link to public reproduction project repository

https://github.com/jbe2277/waf/tree/69803cef490970a344c370616021464f59ae201d

### Version with bug

6.0.486 (current)

### Last version that worked well

Maui: Unknown/Other
Xamarin: 5

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
[Duplicate](https://github.com/dotnet/maui/issues/9743)
