### ISSUE TITLE
Android: Binding does not work when view is hidden

### ISSUE THREAD

**Issue by jbe2277** [dotnet/maui#10109]
### Description

On Android it seems that the Binding does not update the properties when the view is hidden. However, it works on Windows and it worked with Xamarin Forms 5 on Android as well.

Explanation: During navigation (async Task operation) the navigation item is shown as disabled (gray). After navigation has completed the [`NavigationItem.IsCommandEnabled`](https://github.com/jbe2277/waf/blob/69803cef490970a344c370616021464f59ae201d/src/NewsReader/NewsReader.Applications/DataModels/NavigationItem.cs#L57) is set back to true and via [`Binding`](https://github.com/jbe2277/waf/blob/69803cef490970a344c370616021464f59ae201d/src/NewsReader/NewsReader.Presentation/Views/ShellView.xaml#L35) the navigation items is shown as enabled again.

Issue on Android:
![maui-android-issue02](https://user-images.githubusercontent.com/10452896/190082780-ff45e1dc-a9fb-4b97-9369-806d3f1c9f02.gif)

On Windows this works correct:
![maui-windows-works02](https://user-images.githubusercontent.com/10452896/190082864-60914f10-1099-48d8-8f55-3e371725ed47.gif)

### Steps to Reproduce

- Clone this: https://github.com/jbe2277/waf/tree/69803cef490970a344c370616021464f59ae201d
- Open src\NewsReader\NewsReader.sln

### Link to public reproduction project repository

https://github.com/jbe2277/waf/tree/69803cef490970a344c370616021464f59ae201d

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
if you add a color for "Isenabled=true" does that work?

```XAML
  <Label Grid.RowSpan="2" Text="{Binding IconGlyph}" FontFamily="MaterialIcons" FontSize="22" VerticalOptions="Center" HorizontalOptions="Center">
                                <Label.Triggers>
                                    <DataTrigger TargetType="Label" Binding="{Binding IsCommandEnabled}" Value="False">
                                        <Setter Property="TextColor" Value="LightGray"/>
                                    </DataTrigger>
                                </Label.Triggers>
                            </Label>
```

**Comment by jbe2277** [comment]
@PureWeen : I have added an additional `DataTrigger` with color `Red` for `true`. This works. After navigation has completed it applies the color `Red`.

So it seems that it does not switch back to the default color when the `DataTrigger` condition changes to false. However, this issue is only on Android. Windows works correct.

```
<Label Grid.Column="1" Grid.Row="0" Text="{Binding Title}" Style="{StaticResource Subtitle}" VerticalOptions="Center">
    <Label.Triggers>
        <DataTrigger TargetType="Label" Binding="{Binding IsCommandEnabled}" Value="False">
            <Setter Property="TextColor" Value="LightGray"/>
        </DataTrigger>
        <DataTrigger TargetType="Label" Binding="{Binding IsCommandEnabled}" Value="True">
            <Setter Property="TextColor" Value="Red"/>
        </DataTrigger>
    </Label.Triggers>
</Label>
```

**Comment by jbe2277** [comment]
**Update:** This issue still exists after update to .NET 7/MAUI 7.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 4.0. Can repro on Android platform with sample project.
[waf.zip](https://github.com/dotnet/maui/files/12158144/waf.zip)
![Screenshot 2023-07-25 150911](https://github.com/dotnet/maui/assets/77434865/99418c53-93f1-467b-90c6-a78f713f54b7)

**Comment by WebGoose** [comment]
Any update on this? I am still running into the same issue where values aren't updating on a control if it's not visible.

**Comment by jbe2277** [comment]
✅ Seems that this issue got fixed. It does not occur anymore with MAUI 8.0.6.
