### ISSUE TITLE
Blazor Maui Apps Getting Stuck On Android Devices

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#10104]
### Description

If you run the default template, then if you go to the counter page and click very fast, after about 95 to 100 times, it gets stuck.
Once its stuck, you can't even go to another page (like index or the weather forecast page).
This only happens on android devices.  When you run on windows, no issues.
I can't test on IOS because I don't have IOS and can't afford to pay 100 dollars a year for a developer account and don't have a mac either.

### Steps to Reproduce

1.  Create New File (blazor maui app)
2.  Choose android (happens with local devices on android).
3. Run
4. Go to the Counter Page
5. Click really fast 90 to 100 times.
6. Will aways get stuck where the entire app freezes.

### Link to public reproduction project repository

https://github.com/musictopia2/MauiBlazorApp1

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All Android Platforms

**Comment by musictopia2** [comment]
Just wanted to let you know I tried maui app without blazor and that did not have those issues.

**Comment by arthastheking113** [comment]
Duplicated of #9882

Webview version 105.x issue.
