### ISSUE TITLE
XmlReader performance

### ISSUE THREAD

**Issue by jared-morley** [dotnet/maui#10103]
### Description

We are seeing significant performance issues attempting to read an xml document using xmlreader on iOS.  Attempting to read the same file in Maui is approx 10x slower then it was previously using Xamarin Forms.

### Steps to Reproduce

1. Open the maui project
3. Press the "Test" button to read it using XmlReader
4. Observe the time taken 
5. Open the xf project
7. Press the "Test" button to read it using XmlReader
8. Observe the time taken

### Link to public reproduction project repository

https://github.com/jared-morley/XmlReaderPerformance

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by drasticactions** [comment]
Did you try running the same benchmark in a .NET 6 iOS (`dotnet new ios`) application that doesn't use MAUI (The UI Framework?)

CC @dalexsoto

**Comment by jared-morley** [comment]
We have updated the repo to include a .net 6 iOS application.  A sample of the results we are seeing are as follows:

- Xamarin Forms: 88
- Maui: 1056
- IOS: 238

**Comment by jared-morley** [comment]
Is there is a more suitable place where we could submit this issue ie .net/runtime.  This issue will prevent us from being able to move to maui.  It does not make sense to us that the performance here should be so significantly poorer then what is seen using xamarinforms.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on MAUI iOS platform with above project. Xamarin Forms iOS works fine.
[XmlReaderPerformance-main.zip](https://github.com/dotnet/maui/files/11572442/XmlReaderPerformance-main.zip)
MAUI:
![10103](https://github.com/dotnet/maui/assets/77434865/ece01f40-4cef-4151-8fb2-dbe2e80079d0)
Xamarin Forms:
![10103 XF](https://github.com/dotnet/maui/assets/77434865/92d559ad-f0a5-4945-9c1f-f0e6b0d64367)

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-macios#20674
