### ISSUE TITLE
Shell.TitleView does not render on iOS 16

### ISSUE THREAD

**Issue by edgiardina** [dotnet/maui#10128]
### Description

.NET MAUI on iOS 16 does not render a titleview. Versions 15.4 and below do render a title view

First noticed this in forms but it appears to be happening in MAUI as well
https://github.com/xamarin/Xamarin.Forms/issues/15542

### Steps to Reproduce

1. File -> New Maui App
2. Create a TitleView in any page
3. It won't render on an iOS 16 device.

Screenshot from Android Emulator (WORKING):
![image](https://user-images.githubusercontent.com/3627193/190256870-7072a77c-67d3-4975-8b40-81b1e05af647.png)

Screenshot from iPhone 12 iOS 16 (NOT WORKING):
![84feca32-009a-4343-b131-a01fcd8fbb0d](https://user-images.githubusercontent.com/3627193/190256425-48234d60-84a6-4563-baec-6eb78314d3c9.jpg)

### Link to public reproduction project repository

https://github.com/edgiardina/Maui-iOS16-TitleViewBug

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Have not figured out a workaround.

**Comment by edgiardina** [comment]
iOS 15.5 simulator appearance
![image](https://user-images.githubusercontent.com/3627193/190258427-c5f76ca2-d6a4-40fe-b22b-2499d5dfe44b.png)

**Comment by jsuarezruiz** [comment]
Similar to https://github.com/xamarin/Xamarin.Forms/issues/15512

**Comment by jfversluis** [comment]
Looks like this should be fixed by #12363 keep an eye out for that in a release and let us know if something still seems off!

**Comment by jfversluis** [comment]
Maybe I was too quick on this one, let's validate to be sure.

**Comment by justcivah** [comment]
So we won't have a fix until .NET 8?
