### ISSUE TITLE
[Windows] Changing MainPage overlaps layout with title bar

### ISSUE THREAD

**Issue by juanmalm** [dotnet/maui#10123]
### Description

On changing App.MainPage on runtime, for instance from 
`MainPage = new MainPage();`
to
`MainPage = new NewPage1();`
is overlapping NewPage1's layout with window title bar:

![image](https://user-images.githubusercontent.com/22932620/190174118-428f1d5c-b354-4e02-b3fb-938596ddaea7.png)
https://user-images.githubusercontent.com/22932620/190175002-f6129e62-e14b-42e3-8646-bfad88f10625.mp4

However setting NewPage1 as the initial page it is shown as expected:

![image](https://user-images.githubusercontent.com/22932620/190173978-a50e581e-4938-431d-a4ee-fd7c61e81924.png)

### Steps to Reproduce

1. Clone reproduction project repository: https://github.com/juanmalm/maui_changing_mainpage 
2. Build and run MauiApp1.sln
3. Click on 'Navigate' button

Expected behavior:
- Label should appear below title bar

Current behavior:
- Label is overlapping title bar

### Link to public reproduction project repository

https://github.com/juanmalm/maui_changing_mainpage

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
I think is similar or related with https://github.com/dotnet/maui/issues/10087

**Comment by PureWeen** [comment]
Fixed by https://github.com/dotnet/maui/pull/9955
