### ISSUE TITLE
WebView can not show whole page

### ISSUE THREAD

**Issue by xclw2000** [dotnet/maui#10134]
I fix my page's size to 1920*1080, and I use a Android TV(1080p) enulator to debug my app. 
The webview only show part of the page, I had to scroll to view other part of the page.
Please see image below
![image](https://user-images.githubusercontent.com/32091566/190281928-e63f5b29-6b08-4187-8478-b46e0958eab3.png)

After the app starts up, I only can see the red square part, and I had to scroll(drag) to view other part. See below
![image](https://user-images.githubusercontent.com/32091566/190281424-3af6c1f2-9bb4-49bd-ae62-d3b409770fd2.png)

I used to use Xamarin, I can set android:layout_width and android:layout_height to achive my goal, like this:
![image](https://user-images.githubusercontent.com/32091566/190282425-8f045790-06bf-4aa5-af94-823d419ace6d.png)

But how can I do this when use Maui?

**Comment by drasticactions** [comment]
Is your app a net6-android app, or a MAUI app?

If it's net6-android, it's the same as Xamarin. You should be able to use the same layouts in both, nothing has changed there AFAIK.

**Comment by xclw2000** [comment]
> Hi @xclw2000. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

I have created a repository:

https://github.com/xclw2000/ElectronicClassBoard_Maui.git

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12 Preview 1 (8.0.80 & 8.0.72). Can repro on android platform. If you want to view the entire page, you must drag the scroll bar.

**Comment by jfversluis** [comment]
Can you maybe add more information on how you did this with Xamarin?
