### ISSUE TITLE
About the maui project error after updating VS17.3.4

### ISSUE THREAD

**Issue by SoaSoftNet** [dotnet/maui#10137]
### Description

After updating VS17.3.4, the maui project has an error as shown in the figure, please tell me how to deal with it, thank you
![fdc5c4072cd96f31badda6cd197bc6a](https://user-images.githubusercontent.com/30250585/190310034-6ebcc813-0c7a-4a8e-9884-bb5c85512bd3.jpg)

### Steps to Reproduce

直接新建一个maui 项目，然后生成，就出错

### Link to public reproduction project repository

none

### Version with bug

6.0.400

### Last version that worked well

6.0.400

### Affected platforms

Android, Windows

### Affected platform versions

Android,Windows11

**Comment by l3bel** [comment]
this is duplicate of #10102

**Comment by samhouts** [comment]
Duplicate of #10102
