### ISSUE TITLE
Android does not load System.ServiceModel.Primitives.dll

### ISSUE THREAD

**Issue by RemkoVermaeren** [dotnet/maui#10139]
### Description

Hello,

I'm trying to call a WCF service from .NET MAUI.
I encountered the same issue described in ticket [#9543](https://github.com/dotnet/maui/issues/9543) when trying to add the connect service in the .NET MAUI project.
So I tried to add the WCF service in a class library and reference the ServiceClient in the .NET MAUI project.
This works for Windows and iOS, but not for Android.

When running the app on Windows :
![image](https://user-images.githubusercontent.com/10937618/190345814-067110c3-35dd-408c-b732-627c8601d957.png)

When running the app on Android the following error occurs :
![image](https://user-images.githubusercontent.com/10937618/190346203-d89c86c2-e0c4-40fb-a2bc-97ca68f4a8ad.png)

As the image shows, the System.ServiceModel.Primitives.dll is unavailable on the android platform.
![image](https://user-images.githubusercontent.com/10937618/190192667-4af8a3ff-85bc-4fea-aa83-0e16bfa8d3b5.png)

### Steps to Reproduce

1. New .NET MAUI app
2. New .NET 6 Class Library 
3. Add connected service in the class library.
4. Reference class library in .NET MAUI app.
5. Call the ServiceClient from the .NET MAUI app on an Android device/emulator.

### Link to public reproduction project repository

https://github.com/RemkoVermaeren/MauiAndroidDll

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Minimum target 21

**Comment by MagicAndre1981** [comment]
What happens if you install version 4.10.0 directly to the project?

https://www.nuget.org/packages/System.ServiceModel.Primitives/4.10.0

**Comment by RemkoVermaeren** [comment]
> What happens if you install version 4.10.0 directly to the project?
> 
> https://www.nuget.org/packages/System.ServiceModel.Primitives/4.10.0

Upgrading all nuget packages generated by the WCF Helper and installing the v4.10.0 inside the class library did the trick.

**Comment by MagicAndre1981** [comment]
new PackageReferenceInclude is often buggy, so I always add the dependency packages on my own to fully control this. Nice to hear that this also fixed it for you.

**Comment by hartez** [comment]
Sounds like this is fixed, then.
