### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by d066zkie** [dotnet/maui#1014]
**Describe the bug**

Please understand that I used a translator.
Attempting to install PySide6 in a 32-bit environment fails.
It worked fine in a 64-bit environment.
This occurred when installing in a virtual environment that used anaconda and converted it to 32-bit.
I must use 32-bit, and I really hope this is resolved.

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

__Originally posted by @ccjs1234 in https://github.com/pypa/warehouse/issues/9507__

**Comment by jsuarezruiz** [comment]
Please, open the issue in the correct repository: https://github.com/pypa/warehouse/issues
