### ISSUE TITLE
Pair to Mac failed with the error "The Xcode license status couldn't be verified because Xcode has not been found on the default location of the connected Mac..."

### ISSUE THREAD

**Issue by cptbtptpg** [dotnet/maui#10140]
### Description

Pair to Mac failed with the error as below:
![image](https://user-images.githubusercontent.com/76163330/190354881-6611a536-ca21-46f1-a615-222b2ac0f4a9.png)

Disconnected
The Xcode license status couldn't be verified because Xcode has not been found on the default location of the connected Mac. Having Xcode installed and functional is necessary in order to build and run iOS apps, so please check that Xcode is correctly installed and that the path specified under iOS Settings is correct.

### Steps to Reproduce

1. Install the build from the VS PR:
   https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/419183
   If there are only expired builds, you could find the latest build for that PR here:
   https://dev.azure.com/devdiv/DevDiv/_build?definitionId=10310&_a=summary&branchFilter=509183%2C509183%2C509183
2. Add a few feeds to your NuGet.config:
   ```
   <add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json" />
   <add key="dotnet7-internal" value="https://pkgs.dev.azure.com/dnceng/internal/_packaging/dotnet7 internal/nuget/v3/index.json" />
   <add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
   <add key="dotnet6-internal" value="https://pkgs.dev.azure.com/dnceng/internal/_packaging/6.0.401-servicing.22421.13-shipping/nuget/v3/index.json" />
   ```
3. If you want to pair with the mac build agent, follow these iinstructions:
   https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/30321/Getting-workloads-manually-installed-on-macOS-from-private-feeds
4. On the Windows machine, create a new Blazor Hybrid project on the command line using the following:
  ```dotnet new maui-blazor -o iOSWindowsProject  ```
5. Open the iOSWindowsProject solution with Visual Studio.
6. Select the "Pair to Mac" option in the Visual Studio toolbar.
7. Select the mac OS device that is connected to the network and press "Connect".
8. In the next window, enter the username and password for the user account on the macOS machine.
9. Connect the machine.

**Actual**
Pair to mac failed.
![image](https://user-images.githubusercontent.com/76163330/190358024-f424a5bb-b782-48b8-95e5-c8ff902c216b.png)

**Note**
1. In Mac terminal run below code, it doesn't work
      ```sudo xcode-select --reset    ```
2. In Mac, try to agree XCode license, it also doesn't work

### Link to public reproduction project repository

No

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 7.0.100-rc.1.22431.12

### Did you find any workaround?

No

### Relevant log output

```shell
Disconnected
The Xcode license status couldn't be verified because Xcode has not been found on the default location of the connected Mac. Having Xcode installed and functional is necessary in order to build and run iOS apps, so please check that Xcode is correctly installed and that the path specified under iOS Settings is correct.
```

**Comment by drasticactions** [comment]
@cptbtptpg 

This has nothing to do with MAUI (The UI Framework), this is a tooling issue. Based on the fact that you've listed internal links, I'm guessing this is a tester? In that case, it should probably be filed directly in AZDO.

**Comment by cptbtptpg** [comment]
Thank you Tim! I filed the [Bug 1619477](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1619477): [XVS][MAUI] Pair Mac failed with error “The .NET iOS workload could not be found...” in AZDO.
