### ISSUE TITLE
CollectionView items layout is not changed when GridItemsLayout.Span is changed on iOS and Windows

### ISSUE THREAD

**Issue by vg12345** [dotnet/maui#10144]
### Description

CollectionView items layout is not changed when GridItemsLayout.Span is changed on iOS and Windows - columns number remains the same.
Works fine on Android.

Additional problem: trying to change the span without Dispatcher causes crash on iOS (!)

Reproduced on:
Visual Studio 17.3.4
Windows 11 desktop
iPhone device with iOS 15.6.1

Attached: 
MauiApp1 source code that demonstrates the bug
[MauiApp1.zip](https://github.com/dotnet/maui/files/9574398/MauiApp1.zip)

### Steps to Reproduce

Bug 1
1. Open MauiApp1 application
2. Click the button to change layout span
3. Items layout is not changed on iOS and Windows

Bug 2
1. Go to OnButtonClicked implementation, eliminate dispatching and try to change span directly.
2. Recompile
3. Open MauiApp1 on iOS
4.  Click the button to change layout span
5. Application is crashing

[MauiApp1.zip](https://github.com/dotnet/maui/files/9574435/MauiApp1.zip)

### Link to public reproduction project repository

https://github.com/dotnet/maui/files/9574398/MauiApp1.zip

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

iOS 15.6.1, Windows SDK 10.0.22000.194

**Comment by vg12345** [comment]
Please, add label for Windows too

**Comment by pekspro** [comment]
I can confirm this. It works as expected on Android, but not on Windows. My repro:

https://github.com/pekspro/MauiIssues/tree/10144_CollectionView_items_layout_is_not_changed

**Comment by mdbill** [comment]
Span (set in Xaml) was working on .net 6 Windows for me.  Broken with .net 7

**Comment by vg12345** [comment]
> Span (set in Xaml) was working on .net 6 Windows for me. Broken with .net 7

Span CHANGING is not working. With .net 6 too.

**Comment by mdbill** [comment]
> Span (set in Xaml) was working on .net 6 Windows for me. Broken with .net 7

I played around with CenterAndExpand on a few elements and replaced some FillAndExpand's and one of those changes actually made Span 2 work.  But I'll need span changes too - as @vg12345 noted: this, and many other layout issues with collectionview are not working.  Example: A little off topic, but the width doesn't stay fully expanded with window resizes.   This also used to work in .net 6.  Might be able to get a workaround now that .net7 can do this:

```
protected override Window CreateWindow(IActivationState activationState)
	{
		Window window = base.CreateWindow(activationState);
#if NET7_0_OR_GREATER
		window.MinimumWidth = 500;
		window.MinimumHeight = 500;

		window.Width = 800;
		window.Height = 1024;
		window.SizeChanged += (s, e) =>
		{
		};
#endif
		return window;
	}
```

**Comment by Strypper** [comment]
My project also got affected

**Comment by vg12345** [comment]
#13137 is a fix fo Windows.
Is this issue fixed for iOS?
