### ISSUE TITLE
[Bug] Generated PNG images not displaying

### ISSUE THREAD

**Issue by Phenek** [dotnet/maui#10149]
### Description

The MAUI documentation's [Add images to a .NET MAUI app project](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/images) page describes how SVG images are converted to PNG files for targeted platforms when the build action is set to MauiImage.

The generation seems to work, I can see my ".png" inside resizetizer folders under obj. 
(./obj/Debug/{Platfom}/resizetizer/r)
But when the application run, I can see only an empty space where the image should be diplayed..
This affect iOS, Android, Mac, and yes Windows.

### Steps to Reproduce

- Use Visual Studio to create a new .NET MAUI Class Library project and solution.
- Add a Resources folder to the project.
- Add an Images Folder to the Resources folder.
- Add an SVG file to the Images folder added in the previous step. As noted [here](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/images), the SVG file name must meet Android naming requirements.
- Set the SVG file's Build Action to MauiImage
- Display this image as ".png"
- Build the solution.

### Link to public reproduction project repository

https://github.com/Phenek/Maui-Issue.git

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

iOS 15, Android 11, Windows 10, Mac OS 12.5

### Relevant log output

```shell
No log is displayed about loading image.
```

**Comment by davidbuckleyni** [comment]
This seems to be back in lattest preview

**Comment by Phenek** [comment]
I will close this one again, because it's seems to work now :)
