### ISSUE TITLE
Build error when using some packages on Android

### ISSUE THREAD

**Issue by nCastle1** [dotnet/maui#10152]
### Description

When attempting to build an Android project there is the following error:

```
/Users//Projects/ARCoreBuildTest/ARCoreBuildTest/obj/Debug/net6.0-android/AndroidManifest.xml(18,18): Error AMM0000: 
	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from AndroidManifest.xml:22:18-91
	is also present at AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:12:3-29:17 to override.
 (AMM0000) (ARCoreBuildTest) java
```

SceneForm.UX package depends on Xamarin.Android.Support.Fragment. Referencing Xamarin.Android.Support.Fragment also fails to build but with a different error.

### Steps to Reproduce

1. Create a new MAUI app
2. Add a reference to `Xamarin.Android.SceneForm.UX` version `1.17.1`
3. Attempt to build the app for Android

### Link to public reproduction project repository

https://github.com/nCastle1/maui-bug-repro-repo

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No

### Relevant log output

```shell
Build FAILED.

MANIFESTMERGER : /Users//Projects/ARCoreBuildTest/ARCoreBuildTest/obj/Debug/net6.0-android/lp/121/jl/AndroidManifest.xml warning : 
MANIFESTMERGER : /Users//Projects/ARCoreBuildTest/ARCoreBuildTest/obj/Debug/net6.0-android/lp/18/jl/AndroidManifest.xml warning : 
/Users//Projects/ARCoreBuildTest/ARCoreBuildTest/obj/Debug/net6.0-android/AndroidManifest.xml(22,18): java error AMM0000: 
/Users//Projects/ARCoreBuildTest/ARCoreBuildTest/obj/Debug/net6.0-android/AndroidManifest.xml(22,18): java error AMM0000: 	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from AndroidManifest.xml:22:18-91
/Users//Projects/ARCoreBuildTest/ARCoreBuildTest/obj/Debug/net6.0-android/AndroidManifest.xml(22,18): java error AMM0000: 	is also present at AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
/Users//Projects/ARCoreBuildTest/ARCoreBuildTest/obj/Debug/net6.0-android/AndroidManifest.xml(22,18): java error AMM0000: 	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:12:3-29:17 to override.
/Users//Projects/ARCoreBuildTest/ARCoreBuildTest/obj/Debug/net6.0-android/AndroidManifest.xml(22,18): java error AMM0000: 
    2 Warning(s)
    1 Error(s)
```

**Comment by dotMorten** [comment]
This issue is a bit of a showstopper for us wrt supporting .NET MAUI. We can't add AR support to our libraries without this, and are stuck on Xamarin.Forms.

**Comment by moljac** [comment]
Those are old libraries/components/packages in XamarinComponents

https://github.com/xamarin/XamarinComponents/tree/main/Android/ARCore

https://github.com/xamarin/XamarinComponents/tree/main/Android/SceneForm

and they don't have net6 support

https://github.com/xamarin/XamarinComponents/blob/main/Android/SceneForm/source/Core/Core.csproj#L3

and do not depend on AndroidX, rather on triassic legacy Android.Support packages.

**Comment by dotMorten** [comment]
So how are we going to use ARCore in a MAUI app?

**Comment by moljac** [comment]
Best bet would be - update for ARCore and SceneForm and some testing. I will try to do it, but cannot promise when.

**Comment by dotMorten** [comment]
Any update to this and getting the bindings updated for .NET 6?

**Comment by SokoFromNZ** [comment]
When can we expect a fix for this so Toolkit will work on MAUI? I would only need Android support at the moment...

**Comment by mgierlasinski** [comment]
@nCastle1 You are referencing Support packages and AndroidX, usually sooner or later it will cause troubles. There is the same attribute defined in 2 packages: 

- `android.support.v4.app.CoreComponentFactory`
- `androidx.core.app.CoreComponentFactory)` 

Manifestest merger doesn't know which one is correct. Try adding to `AndroidManifest.xml` in your app:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" 
          xmlns:tools="http://schemas.android.com/tools">
        <application android:appComponentFactory="androidx.core.app.CoreComponentFactory" 
                     tools:replace="android:appComponentFactory"/>
</manifest>
```

This tells manifest merger that your app is overriding attribute `android:appComponentFactory` with value `androidx.core.app.CoreComponentFactory`.

You can look at AndroidManifest.xml from AndroidX for reference:
https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/core/core/src/main/AndroidManifest.xml

**Comment by dotMorten** [comment]
> You are referencing Support packages and AndroidX

It looks like the issue here then is that `Xamarin.Android.SceneForm.UX` is pulling in the support dependency. We really need an updated version of the SceneForm bindings that works with .NET 6.

/cc @moljac

**Comment by dotMorten** [comment]
Btw wrt the proposed app manifest workaround, that just gets me to a new exception:
```
2>Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Release\net6.0-android\lp\32\jl\bin\classes.jar:androidx/versionedparcelable/NonParcelField.class
2>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:98)
2>	at com.android.tools.r8.D8.main(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:4)
2>Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Release\net6.0-android\lp\32\jl\bin\classes.jar:androidx/versionedparcelable/NonParcelField.class
2>	at Version.fakeStackEntry(Version_3.3.28.java:0)
2>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:75)
2>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:28)
2>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:27)
2>	at com.android.tools.r8.internal.Bj.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
2>	at com.android.tools.r8.D8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:22)
2>	at com.android.tools.r8.D8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:17)
2>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:85)
2>	... 1 more
2>Caused by: com.android.tools.r8.internal.f: Type androidx.versionedparcelable.NonParcelField is defined multiple times: obj\Release\net6.0-android\lp\32\jl\bin\classes.jar:androidx/versionedparcelable/NonParcelField.class, obj\Release\net6.0-android\lp\72\jl\classes.jar:androidx/versionedparcelable/NonParcelField.class
2>	at com.android.tools.r8.internal.DT.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:14)
2>	at com.android.tools.r8.internal.DT.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:22)
2>	at com.android.tools.r8.internal.CN.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:33)
2>	at com.android.tools.r8.internal.CN.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:10)
2>	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
2>	at com.android.tools.r8.internal.CN.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
2>	at com.android.tools.r8.graph.B2$a.e(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:4)
2>	at com.android.tools.r8.dex.b.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:105)
2>	at com.android.tools.r8.dex.b.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:28)
2>	at com.android.tools.r8.D8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:25)
2>	at com.android.tools.r8.D8.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:606)
2>	at com.android.tools.r8.D8.c(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
2>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:24)
2>	... 5 more
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.D8.targets(79,5): error : java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Release\net6.0-android\lp\32\jl\bin\classes.jar : androidx/versionedparcelable/NonParcelField.class
2>Done building project "ARToolkit.SampleApp.Android.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by mbranscomb** [comment]
https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/issues/467

**Comment by jonathanpeppers** [comment]
I concur with @jpobst's assessment here.

To reiterate some things:

* `Android.Support.*` packages are not supported on .NET 6+,  AndroidX is required.
  *  Note that targeting the [minimum API level for Google Play](https://support.google.com/googleplay/android-developer/answer/11926878) already would require AndroidX. `Android.Support.*` packages last support API 28, if I remember correctly.
* Packages from XamarinComponents are [not supported or maintained](https://github.com/xamarin/XamarinComponents#status)
* Google [discontinued SceneForm](https://developers.google.com/sceneform/develop)

So, I don't think there is anything to be done here. But please file a new issue if you are hitting a similar problem with a different combination of NuGet packages that are supported. Thanks!

**Comment by dotMorten** [comment]
@jonathanpeppers @jpobst I think that's fair to skip SceneForm considering its outdated support. It does still beg the question around the base ARCore library. It's by now several versions behind, and while it doesn't exhibit the above build error, it is still only targeting the old xamarin.android runtime. Having all the XamarinComponents deprecated is still a bit of an issue - some of them are still very valuable.
