### ISSUE TITLE
Blazor - customization for video tag

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/maui#10151]
### Description

As we know iOS force to use native player. But sometimes we need to customize.
Maybe background video or so on.

`
<video class="video-background" autoplay loop muted playsinline> 
`

so, can we add in blazor support for it?

### Public API Changes

No

### Intended Use-Case

Custom video player.
Play videos on background.
Make video-call app with some  custom video view.

**Comment by KSemenenko** [comment]
In xamarin we use code like it

`[assembly: ExportRenderer(typeof(MyWebView), typeof(MyWebViewRenderer))]
namespace WebViewSample.iOS
{
    public class MyWebViewRenderer : ViewRenderer<MyWebView, WKWebView>
    {
        WKWebView wkWebView;

        protected override void OnElementChanged(ElementChangedEventArgs<MyWebView> e)
        {
            base.OnElementChanged(e);

            if (Control == null)
            {
                WKWebViewConfiguration configuration = new WKWebViewConfiguration();
                configuration.AllowsInlineMediaPlayback = true;
                wkWebView = new WKWebView(CGRect.Empty, configuration);

                if (Element.Url != null)
                {
                    wkWebView.LoadRequest(new NSUrlRequest(new NSUrl((Element).Url)));
                }
                SetNativeControl(wkWebView);
            }
        }

        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName.Equals(nameof(Element.Url)))
            {
                wkWebView.LoadRequest(new NSUrlRequest(new NSUrl((Element).Url)));
            }
        }

        public override void Draw(CGRect rect)
        {
            base.Draw(rect);

            Control.Frame = rect;
        }
    }
} `

**Comment by KSemenenko** [comment]
Related to https://github.com/dotnet/maui/issues/4807

**Comment by mkArtakMSFT** [comment]
Thanks for linking the right issue, @KSemenenko. Closing this as the one you linked already tracks the work needed.
