### ISSUE TITLE
Maui Shell always re-uses pages.  No option to re-create on navigation

### ISSUE THREAD

**Issue by kkohler2** [dotnet/maui#10164]
### Description

I'm using the .net Maui framework for Android development and realized that when you navigate to a page, it creates the page, then hangs on to the page instance.  If you navigate to the page again, it re-uses the same page instance.

In the past, with Xamarin.Forms, I have found that with some controls, re-using a page is problematic.  I do not know if this is the case using Maui, but want to avoid the situation to be sure.

I haven't found any settings that let me change the default behavior.

Is there a way to configure Maui to create each page every time you navigate to the page?

Issues with reusing pages:

1. stale data from previous instance might be displayed when page is navigated to again
2. some controls do NOT handle re-use well (this is the case with Carousel in Xamarin.Forms.  I haven't yet determined if it is the case in Maui.  If so, I will log a separate issue with example.)
3. some pages are used once or rarely, such as login or configuration pages.  Hanging on to instances of such pages for the life of an app is a poor use of memory/resources.

What I'm specifically looking for, and have not found, is a way to have either a setting for shell to not re-use pages or a page by page setting to not re-use the page.

### Steps to Reproduce

Create app with two pages.  Each page should have a label showing number of times page was displayed.
In OnAppearing increment counter for number of times page is displayed and format/set label showing the count.
Add button to each page with navigation to the other page.

Run app
Navigate to page 2, then navigate to page 1. 

Expected results: count for # of time page is visited should always be 1
Actual: count increases each time page is displayed (expected if you want to or are okay with re-using pages, not expected if you do NOT want to re-use the pages.)

### Link to public reproduction project repository

https://github.com/kkohler2/MauiShellReuseTest

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10

### Did you find any workaround?

Only possible work around is to NOT use shell for navigation and navigate such that pages are created each time they are displayed.

**Comment by janseris** [comment]
Try look into dependency injection setup. Now they are probably registered as singleton. You want transient. That might help

**Comment by PureWeen** [comment]
[duplicate](https://github.com/dotnet/maui/issues/9300)
