### ISSUE TITLE
Shadow Breaks TranslateTo Animation on Android

### ISSUE THREAD

**Issue by EthanHipps** [dotnet/maui#10169]
### Description

Adding a shadow to an Image Button that is animated causes the animation to flip (instead of the buttons translating up, they go down). I tested on Android Emulators (API 32 and 33), a Local iPhone (12 Pro Max - iOS 16), and Windows (Latest Version). I only experienced the issue on the Android Emulators. Adding a shadow on iPhone and Windows didn't break the animation.

Correct Behavior: 
![correct_behavior_NoShadow](https://user-images.githubusercontent.com/13156894/190691258-62fdb1ce-de4e-43e8-859f-3b5c79475cdd.gif)

After Adding Shadow (Incorrect Behavior):
![bug_ShadowInStyle](https://user-images.githubusercontent.com/13156894/190690630-074423eb-2d62-4516-812b-fe1add8a5076.gif)

Shadow on just one Button (Incorrect Behavior):
![bug_SingleShadow](https://user-images.githubusercontent.com/13156894/190690639-0dcbdf07-0cbe-4f60-a170-5ba2e9f0f308.gif)

### Steps to Reproduce

Here is an example Repo: https://github.com/EthanHipps/ShadowTranslateToBug

### Link to public reproduction project repository

https://github.com/EthanHipps/ShadowTranslateToBug

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.1 & 13

### Did you find any workaround?

No.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprisre 17.7.0 Preview1.0. Not repro on android，windows and iOS platform with above project.
[ShadowTranslateToBug-master.zip](https://github.com/dotnet/maui/files/11573558/ShadowTranslateToBug-master.zip)
Android:
![10169](https://github.com/dotnet/maui/assets/77434865/d8b8377b-fea1-4d76-b597-e86fb775c28f)
Windows:
![10169 Windows](https://github.com/dotnet/maui/assets/77434865/580b72d0-02bf-432b-8fd7-7169717d3bda)
iOS:
![10169 iOS](https://github.com/dotnet/maui/assets/77434865/d7047093-f9ae-4618-b359-50f2748af14f)
