### ISSUE TITLE
.NET MAUI Blazor UWP doesn't not allow camera access through javascript library or functions.

### ISSUE THREAD

**Issue by Guandaru6967** [dotnet/maui#10176]
### Description

When camera or microphone access is requested by the user through javascript library or function the prompt does not appear nor are the privilages granted to the MAUI APP allocated to the WebView. However it should be noted that prompts and alerts work on UWP but not permission prompts. If any it should be well documented cause i found out that webview and blazorwebview are not so different yet there is only permissions documentation on WebView only, despite BlazorWebView being an abstraction of WebView.

### Steps to Reproduce

Create MAUI App and request camera  and microphone through
```
navigator.mediaDevices.getUserMedia({video:true,audio:true})
```

Then call the zoom function on after render. The permissions to the MAUI APP on windows is not granted to the app and the permission prompt DOESNT APPEAR.

### Link to public reproduction project repository

N/A

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

ALL WINDOWS

### Did you find any workaround?

Not yet still looking.

### Relevant log output

```shell
No log out put
```

**Comment by janseris** [comment]
I read some time ago that you have to add some permissions to the windows platform manifest

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This repo contains sample project which shows how to set permissions as necessary: https://github.com/MackinnonBuck/MauiBlazorPermissionsExample

Hope this helps.
