### ISSUE TITLE
There is no link for mac installations

### ISSUE THREAD

**Issue by pereiraryan** [dotnet/maui#10179]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Eilon** [comment]
cc @davidbritch

**Comment by davidbritch** [comment]
@Eilon Afraid this isn't one for me. The MSLearn course comes under @jamesmontemagno and @codemillmatt 

The docs have this info though: https://learn.microsoft.com/dotnet/maui/get-started/installation?tabs=vsmac

**Comment by Eilon** [comment]
@jamesmontemagno is there a better place to track this issue? Should I move the issue to another repo?

**Comment by jamesmontemagno** [comment]
We already are tracking it internally in the website repo, so can be closed I think.

**Comment by Eilon** [comment]
Alright thanks @jamesmontemagno , and also thank you @pereiraryan for the report!

**Comment by lutzroeder** [comment]
@bzeren @mairaw
