### ISSUE TITLE
Can't add Map Pins

### ISSUE THREAD

**Issue by BillyMartin1964** [dotnet/maui#10180]
Current build displays and shows Location correctly, but has two major bugs:

When adding Map Pins, I get

### System.MissingMethodException: 'Method not found: bool Microsoft.Maui.Devices.Sensors.Location.op_Inequality(Microsoft.Maui.Devices.Sensors.Location,Microsoft.Maui.Devices.Sensors.Location)'

When tracking user with polyline, I get this

![image](https://user-images.githubusercontent.com/29313458/190867063-0e84ffa8-4a7e-4915-9fc8-e8ba9f4bb9e1.png)

**Comment by zakarlyya** [comment]
Did you ever resolve the map pins issue? I am getting the same message

**Comment by BillyMartin1964** [comment]
Yes. You have to update to .net7 and use VS preview, because vs2022 doesn't yet support .net 7.

Then you can use the maps update that is based on .net 7

**Comment by zakarlyya** [comment]
Thanks

**Comment by BillyMartin1964** [comment]
NP. From what I understand, if you upgrade to the latest VS preview, it will install .net 7 for you... but I'm not positive.

**Comment by jfversluis** [comment]
> System.MissingMethodException: 'Method not found: bool Microsoft.Maui.Devices.Sensors.Location.op_Inequality(Microsoft.Maui.Devices.Sensors.Location,Microsoft.Maui.Devices.Sensors.Location)'

This message indicates that this is not running on a .NET 7 MAUI app. The polyline issue is impossible to diagnose without seeing any code.

Please provide more detail on what you are using exactly, ideally with a GitHub repo with the code so we can have a look. Thanks.
