### ISSUE TITLE
Catalyst Gallery no longer resizes to fit the window

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#10183]
### Description

After https://github.com/dotnet/maui/pull/10073 the Catalyst Sample Gallery just stays a fixed width. No matter what you do when trying to resize the window the width of the gallery stays the same

**Comment by Eilon** [comment]
Happening on Windows too in Controls.Sample:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/202643/191373385-53fd06e4-b8ca-4ad3-b164-1f5773a77e3f.png">

**Comment by hartez** [comment]
The Windows version of this problem was fixed by #10243
