### ISSUE TITLE
Odd behaviour dragging window OR anything (sortable lists, etc)

### ISSUE THREAD

**Issue by TcNobo** [dotnet/maui#10185]
### Description

Dragging the window works normally, but as soon as I try use the Windows API with MAUI (`SendMessage`), it just doesn't work s expected.

I can't drag elements (or native UI elements) with this trigger. I need to click to start the drag or resize of the window and click again to "drop". I'm not sure if it's my code, so I have prepared an extremely minimal example using MAUI. The issue only appears to be here, and it works fine in WPF forms.

Minimal example: [HERE](https://github.com/TcNobo/MAUIDrag), with [only these changes made](https://github.com/TcNobo/MAUIDrag/commit/b9810e90a830cbc4877390181a2934ecc4f3fb9d). Also, [release build of sample](https://github.com/TcNobo/MAUIDrag/releases/tag/1).

Example (Green around mouse is Left Mouse):

https://user-images.githubusercontent.com/10319195/190872490-e4d675f5-aee0-4e45-839e-94c6fbacb52c.mp4

EDIT: This also applies to any draggable elements (I think these are using -webkit-drag - It's [SortableJS](https://github.com/SortableJS/Sortable)). This is not working anywhere near as expected. Drag actions only happen on click, instead of drag. Click (up-down) starts drag action, and Click (up-down) ends drag action. See the sortable list not sorting:

https://user-images.githubusercontent.com/10319195/190880249-211d2e99-5eeb-4881-9c4c-e8f8dac7787d.mp4

Expected behaviour (exact same codebase with Blazor Server)

https://user-images.githubusercontent.com/10319195/190880315-ffe1b1c4-d114-4def-b4dc-2a02157fda0b.mp4

### Steps to Reproduce

1. Create MAUI app.
2. Set for Windows (to allow WinRT)
3. Either create native UI element with `Pressed`, or add something in the `cshtml` with `onmousedown` to use the Windows API [SendMessage](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessage).
4. Watch as dragging doesn't work, but instead, clicking to "toggle" behaviour occurs.

### Link to public reproduction project repository

https://github.com/TcNobo/MAUIDrag

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All Windows

### Did you find any workaround?

No. This is very unexpected behaviour, but I wouldn't be surprised if it's something I'm doing wrong. It works in WPF apps so this has me at a loss.

### Relevant log output

```shell
N/A
```

**Comment by Eilon** [comment]
Hi @TcNobo , let's use https://github.com/MicrosoftEdge/WebView2Feedback/issues/2805 to track this because this is ultimately a WebView2-specific issue, and not an issue with BlazorWebView. I see you already commented on the other issue so let's see what the WebView2 team can say about it.
