### ISSUE TITLE
iOS keyboard "done" button does not call Editor.Completed and does not close the keyboard.

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#10190]
### Description

Under iOS, when the Editor control is focused, the soft keyboard opens.  However when pressing the "done" button on the keyboard nothing happens.  This should however close the soft keyboard and should also call Editor.Completed() which it does not.

The following sample shows this:

[Uploading layoutbug7.zip…]()

### Steps to Reproduce

1. Build the attached sample
2. Run under iOS emulator
3. tap the green Editor to open the keyboard
4. tap the keyboard "done" button
5. nothing happens but the keyboard should have closed.

### Link to public reproduction project repository

attached

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS15

### Did you find any workaround?

no

**Comment by AbstractionsAs** [comment]
I have this problem as well

**Comment by RonnyRos** [comment]
Same
