### ISSUE TITLE
XA1018 Specified AndroidManifest file does not exist after dotnet workload update  

### ISSUE THREAD

**Issue by xiangnanscu** [dotnet/maui#10191]
### Description

after `dotnet workload update ` I find no blazor maui template available when creating solution in vs 2022
**********************************************************************
** Visual Studio 2022 Developer PowerShell v17.3.4
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
PS C:\Users\xn\source\repos\MauiApp3> dotnet workload update

没有为此功能带安装工作负载。若要使用更早的 SDK 版本更新已安装的工作负载，请包括“the --from-previous-sdk”选项。
已更新广告清单 microsoft.net.workload.emscripten。
已更新广告清单 microsoft.net.workload.mono.toolchain。
已更新广告清单 microsoft.net.sdk.maui。
已更新广告清单 microsoft.net.sdk.android。
已更新广告清单 microsoft.net.sdk.ios。
已更新广告清单 microsoft.net.sdk.macos。
已更新广告清单 microsoft.net.sdk.tvos。
已更新广告清单 microsoft.net.sdk.maccatalyst。
计算机有挂起的重新启动。安装将继续，但可能需要重新启动。
Downloading microsoft.net.sdk.maui.manifest-6.0.400.msi.x64 (6.0.536)
正在安装 Microsoft.NET.Sdk.Maui.Manifest-6.0.400.6.0.536-x64.msi .... Done
Downloading microsoft.net.workload.mono.toolchain.manifest-6.0.400.msi.x64 (6.0.9)
正在安装 Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.400.6.0.9-x64.msi .... Done
Downloading microsoft.net.workload.emscripten.manifest-6.0.400.msi.x64 (6.0.9)
正在安装 Microsoft.NET.Workload.Emscripten.Manifest-6.0.400.6.0.9-x64.msi .... Done
没有为此功能带安装工作负载。若要使用更早的 SDK 版本更新已安装的工作负载，请包括“the --from-previous-sdk”选项。

已成功更新工作负载: 。

PS C:\Users\xn\source\repos\MauiApp3>

### Steps to Reproduce

just run `dotnet workload update` and then try to create a project

### Link to public reproduction project repository

https://github.com/xiangnanscu/MauiApp3

### Version with bug

6.0.400

### Last version that worked well

6.0.400

### Affected platforms

Windows

### Affected platform versions

Win 10

**Comment by xiangnanscu** [comment]
Also when I open a maui blazor project, error:
```
XA1018	Specified AndroidManifest file does not exist: C:\Users\xn\source\repos\MauiApp3\MauiApp3\AndroidManifest.xml.	MauiApp3	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets	517	

```

**Comment by mattleibow** [comment]
There may be an issue with `dotnet workload update`. Can you try using `dotnet workload install maui` instead and see if that fixes some things?

@Redth is missing files expected as part of the big? DO you have a link to the issue?
