### ISSUE TITLE
under iOS, "parent.InputTransparent = false" does not propagate to children as it should

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#10203]
### Description

When setting "parent.InputTransparent = true", this propagates to the child elements, but later setting "parent.InputTransparent = false" does not propagate, making the children permanently input transparent.  Under Android this works correctly.

This is a regression from Xamarin Forms.

This attached sample shows this:
[layoutbug2.zip](https://github.com/dotnet/maui/files/9598032/layoutbug2.zip)

### Steps to Reproduce

1. compile and run the attached sample under iOS
2. clicking the red square should print "TAP" but it does not.
3. instead "child.InputTransparent=true" is printed (which is my the tap does not work).
4. If we leave out the line "parent.InputTransparent = true" then the TAP works.

### Link to public reproduction project repository

attached

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS15

### Did you find any workaround?

no

**Comment by jfversluis** [comment]
I think some work has been done around this. Could you maybe check and see if this is still happening in the currently released version? Thank you!

**Comment by philipag** [comment]
@jfversluis I downloaded my sample, updated it to MAUI 8.0 preview 2, but the problem still persists.  So it seems this is not fixed.
