### ISSUE TITLE
CollectionView does not allow clicking of child elements

### ISSUE THREAD

**Issue by LennoxP90** [dotnet/maui#10209]
### Description

I have an application that utilized Listview for this behaviour in XF, I would like to switch to CollectionView in MAUI

I have a messaging application that has the ability to click on url links that are embedded into messages and open the appropriate browser

In MAUI with the CollectionView my Label Span is not clickable, the listview just selects the row but does not propagate the tap to the label

### Steps to Reproduce

1. create a Listview or CollectionView
2. add a label with a formattedText value of a clickable url
3. try to click the label on both CollectionView or ListView

Expected Outcome: should open the browser and navigate to the URL
Actual Outcome: nothing happens when you click collectionview but selects the row when you click listview

### Link to public reproduction project repository

https://github.com/LennoxP90/HyperLinksNotClickable

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 30 on Emulator

**Comment by AmSmart** [comment]
This feels like an input transparency issue. Are you sure the Label control gets clicked?

**Comment by LennoxP90** [comment]
interesting i didn't think of this
I added a gesture recognizer directly to the label control
```
<Label FormattedText="{Binding Text}">
  <Label.GestureRecognizers>
    <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"/>
  </Label.GestureRecognizers>
</Label>
```

now my span command is being executed but the TapGestureRecognizer_Tapped is not being called
updated repro with the behaviour

**Comment by egvijayanand** [comment]
Facing this issue on Android in both SR5 (.NET 6) and RC1 (.NET 7).

Even the `SelectionChangedCommand` of the CollectionView is not getting triggered.

As an alternate implementation, have tried defining the Tap gesture as part of the control within the item template of the CollectionView, but NO change in behavior.

Request to look into this issue on priority as CollectionView is the much needed control.

**Comment by egvijayanand** [comment]
> Facing this issue on Android in both SR5 (.NET 6) and RC1 (.NET 7).

Both **SelectionChangedCommand** and **Tap gesture** work fine on the Windows platform and I couldn't able to test on other platforms due to infra issues.

**Comment by LennoxP90** [comment]
some regressions have happened and my hack is no longer working in latest MAUI 7.0.59 with iOS Android seems to still work fine

**Comment by LennoxP90** [comment]
sounds good looking forward to this getting merged

**Comment by insolito86** [comment]
Do we have a workaround at this time?

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on Android platform with sample project. [HyperLinksNotClickable](https://github.com/LennoxP90/HyperLinksNotClickable)
