### ISSUE TITLE
[Bug] MAUI icon don't get resized to proper size on Android, renders extra accent overlay on Windows

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/maui#10219]
### Description

MAUI SVG icons don't show properly on Android (partially out of bound) and Windows (taskbar icon has an extra overlay with system accent color).

Having a hard time following the [MAUI Icon documentation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=android) to make icons automatically show properly on all platforms and all resolutions combinations. I hope this could be automatically done given any square SVG data, since it's scalable.

Thanks a lot.

### Steps to Reproduce

Please run the attached demo project on Android (check app icon) Windows (check taskbar icon).

### Link to public reproduction project repository

https://github.com/SunshineSpring666/MAUI_Icon.git

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 10+, Windows SDK 10.0.22000+

### Did you find any workaround?

No

**Comment by janseris** [comment]
@mattleibow

**Comment by mattleibow** [comment]
The new version of maui went out a few days ago, so please give it a test and see if we fixed all the issues.
