### ISSUE TITLE
Application OnSleep not Called in Windows

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#10214]
### Description

When switching to another Application and back in Android the correct sequence of calls are made, specifically

Page.OnDisappearing
App.OnSleep
App.OnResume
Page.OnAppearing

On Windows to App.OnSleep call is missing

### Steps to Reproduce

1. Create a default Maui App
2. Add this code to MainPage.Xaml.cs
```
	protected override void OnAppearing()
	{
		Debug.WriteLine("In MainPage.OnAppearing");
		base.OnAppearing();
	}

	protected override void OnDisappearing()
	{
        Debug.WriteLine("In MainPage.OnDisappearing");
        base.OnDisappearing();
	}
```
3. Add this code to App.xaml.cs:
```
	protected override void OnSleep()
	{
        Debug.WriteLine("In App.OnSleep");
        base.OnSleep();
	}
	protected override void OnResume()
	{
        Debug.WriteLine("In App.OnResume");
        base.OnResume();
	}
```

4. Build and run the project on Android then switch away from it and back, note the output.
5. Do the same in Windows, note that the OnSleep method is not called.

### Link to public reproduction project repository

See above

### Version with bug

6.0.400

### Last version that worked well

6.0.400

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@david-maw the event you're looking for is Activated/Deactivated

OnSleep is only called on windows when you minimize the app because it's connected to the "VisibilityChanged" event on windows where as "Activated/Deactivated" fires whenever the window is no longer the focus

**Comment by david-maw** [comment]
Thanks @PureWeen although it seems strange to call App.OnResume without a corresponding App.OnSleep having read through the "App LifeCycle" documentation for MAUI I can see that you're right, what I indeed want are ["cross platform lifecycle events"](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle#cross-platform-lifecycle-events). Probably worth a mention as a Xamarin migration issue.
