### ISSUE TITLE
.net maui crashes in the MauiAppCompatActivity/OnCreate method

### ISSUE THREAD

**Issue by proficad** [dotnet/maui#10218]
### Description

The app crashes in the MauiAppCompatActivity/OnCreate method.
It crashes even when I remove the method.

it crashes using  MAUI 6.0.4. it works fine with maui 6.0.312

### Steps to Reproduce

1) run the app in debugger on an android device
2) switch to google drive, double tap an a file with extension "sxe"
3) select "Viewer_Maui"
4) the app crashes on the line comment "it crashes here"

### Link to public reproduction project repository

https://github.com/proficad/Viewer_Maui

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

6.0.4

### Did you find any workaround?

no

**Comment by jsuarezruiz** [comment]
Could you try again with the latest version (net7 rc1)?
![fix-10218](https://user-images.githubusercontent.com/6755973/193575764-8001f8c4-87e5-40e5-856b-06656fb82d8f.gif)
Cannot reproduce the issue.

**Comment by proficad** [comment]
Hi,
how do I switch the app to net7 rc1?
Thanks
Vaclav
