### ISSUE TITLE
Update vs to  Version 17.4.0 Preview 2.0 causes Could not find android.jar for API level 31 error

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#10222]
### Description

Got this exception:
Severity	Code	Description	Project	File	Line	Suppression State
Error	XA5207	Could not find android.jar for API level 31. This means the Android SDK platform for API level 31 is not installed. Either install it in the Android SDK Manager (Tools > Android > Android SDK Manager...), or change the Xamarin.Android project to target an API version that is installed. (C:\Program Files (x86)\Android\android-sdk\platforms\android-31\android.jar missing.)	AutomationClient.MAUI	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets	533	

### Steps to Reproduce

1. Create maui app in Version 17.4.0 Preview 1.0
2. Upgrade maui app to Version 17.4.0 Preview 2.0
3. You got this exception:
Severity	Code	Description	Project	File	Line	Suppression State
Error	XA5207	Could not find android.jar for API level 31. This means the Android SDK platform for API level 31 is not installed. Either install it in the Android SDK Manager (Tools > Android > Android SDK Manager...), or change the Xamarin.Android project to target an API version that is installed. (C:\Program Files (x86)\Android\android-sdk\platforms\android-31\android.jar missing.)	AutomationClient.MAUI	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets	533	

### Link to public reproduction project repository

...

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

....

### Did you find any workaround?

No

### Relevant log output

```shell
this exception:
Severity	Code	Description	Project	File	Line	Suppression State
Error	XA5207	Could not find android.jar for API level 31. This means the Android SDK platform for API level 31 is not installed. Either install it in the Android SDK Manager (Tools > Android > Android SDK Manager...), or change the Xamarin.Android project to target an API version that is installed. (C:\Program Files (x86)\Android\android-sdk\platforms\android-31\android.jar missing.)	AutomationClient.MAUI	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets	533
```

**Comment by VladislavAntonyuk** [comment]
you just need to install sdk 31. then issue will disapper

**Comment by danies8** [comment]
Can you attaced screen cast how to install it through android manager.

**Comment by VladislavAntonyuk** [comment]
![image](https://user-images.githubusercontent.com/33021114/191324737-c38dc8b7-fd5b-45ac-af53-3ecbfbb6b85e.png)

**Comment by danies8** [comment]
In future when I will update Vs preview to new version
I will need to update Vs only or to uninstall Vs and install it from scratch beacue of this missing file that I added manually.

**Comment by supershopping** [comment]
My .net MAUI program is getting the same error after upgrading VS preview from Version 17.4.0 Preview 1.0 to Version 17.4.0 Preview 2.1. It's working at .NET 6.0.486 and Version 17.4.0 Preview 1.0.
I manually installed the SDK 31. All the dependency error are gone. Now I am getting below error **only in release mode**. (An item with the same key has already been added).
![error](https://user-images.githubusercontent.com/5925578/193025070-749354db-0335-4be9-a0c3-6f97e2d4339d.png)

I am searching the error message online. I found this post:
https://stackoverflow.com/questions/73183482/an-item-with-the-same-key-has-already-been-added-maui-c-sharp
What is the correct way to fix this? Is this a bug from VS preview?

**Comment by mattsegura** [comment]
Currently having the same issue, I'm running the latest version of visual studio 2022 preview and can't even load up the default .NETmaui sample app. 


**When compiling** on the windows machine
![image](https://user-images.githubusercontent.com/61678138/196769259-45a9f9f6-6960-4fa0-9849-4ccef9be86f2.png)

when going to (Tools > Android > Android SDK Manager) and updating I recieve this error
![image](https://user-images.githubusercontent.com/61678138/196769866-fa08d9c6-bf6d-4a8a-927f-6c59803b31db.png)

**Comment by workpebojot** [comment]
![image](https://user-images.githubusercontent.com/38276345/202876111-926c0c3f-998a-4e47-9396-ed96f8cc50e1.png)

**Comment by workpebojot** [comment]
I don't understand this. I'm lost. It is already installed
![image](https://user-images.githubusercontent.com/38276345/202876178-49a3f662-bf2e-4472-a9dd-3b92eb9aaeac.png)
