### ISSUE TITLE
[MacCatalyst] PointerOver visual state freezes up

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#10227]
### Description

PointerOver visual state works mostly well on MacCatalyst, but appears to freeze up when overengaged

### Steps to Reproduce

1. Run .NET MAUI control gallery
2. Navigate to VisualStates page
3. Quickly and repeatedly hover and unhover button that has PointerOver state
4. Notice that at some point, the background color appears to get "stuck"

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac 12.5.1

**Comment by davidortinau** [comment]
Confirmed still an issue. It breaks any other pointer related events on the same page as well. 



https://user-images.githubusercontent.com/41873/193849382-56695360-1eb7-4b76-83b1-d4f4139f7831.mp4
