### ISSUE TITLE
[Bug] Border StrokeShape Style Setter does not set

### ISSUE THREAD

**Issue by Phenek** [dotnet/maui#10229]
### Description

I am no able to set the StrokeShape property of a Border from a Xaml Style Setter.

### Steps to Reproduce

```
    <Style TargetType="Border" Class="BorderRounded">
        <Setter Property="StrokeShape" Value="RoundRectangle 15,15,15,15" />
    </Style>
```

```
<Border StyleClass="BorderRounded"
        Background="Blue"
        WidthRequest="100"
        HeightRequest="50" />
```

### Link to public reproduction project repository

I think you will be able to copy and past this one, but I can still do it if needed ;)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

iOS 16, Android 11, Windows 10

### Did you find any workaround?

Yeah you can still set the StrokeShape from direct Xaml or direct C#
````
<Border StrokeShape="RoundRectangle 15,15,15,15"
        Background="Blue"
               ... />
````

**Comment by jsuarezruiz** [comment]
This issue should be fixed by https://github.com/dotnet/maui/pull/8047/files

**Comment by PureWeen** [comment]
This should be fixed with .NET 7
