### ISSUE TITLE
Macos M1 Max Editor cannot scroll

### ISSUE THREAD

**Issue by khanakia** [dotnet/maui#10221]
### Description

I cannot Scroll the Editor Component. Check the attached video

https://user-images.githubusercontent.com/2174170/191232762-5ee463a2-af54-4457-9c1d-c6e91f4b6d3e.mp4

### Steps to Reproduce

1. Download the Sample Project from here https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/ControlGallery
2. Run the ControlGallery.sln
3. Click the Play Icon in Visual Studio Code
4. After app is running search for Editor Demo
5. Add some Long Text and then try to scroll you cannot scroll to the text.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/ControlGallery

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monetery 12.6 (21G115) M1 Max

### Did you find any workaround?

Not yet

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on macOS platform with sample project. [ControlGallery](https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/ControlGallery)

**Comment by mattleibow** [comment]
This might be fixed by https://github.com/dotnet/maui/pull/13234

**Comment by jingliancui** [comment]
Hi all, May I know is .net 8 GA will include the fix? thanks.

**Comment by jfversluis** [comment]
I think this is fixed, if not, please let us know.
