### ISSUE TITLE
Unable to record custom aot profile.

### ISSUE THREAD

**Issue by sake402** [dotnet/maui#10237]
### Description

With a maui application ``dotnet build -t:BuildAndStartAotProfiling`` returns an error

### Steps to Reproduce

```
dotnet add package Mono.AotProfiler.Android
dotnet build -t:BuildAndStartAotProfiling
```

Produces error

```
 error MSB4057: The target "BuildAndStartAotProfiling" does not exist in the project.
```

### Link to public reproduction project repository

None

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 21

**Comment by Eilon** [comment]
This issue was moved to xamarin/xamarin-android#7722
