### ISSUE TITLE
Updating Microsoft.WindowsAppSDK to 1.2 experimental breaks Titles on Shell

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#10244]
### Description

When testing the new 1.2 version of WindowsAppSDK we found some issues with the size of the Title and TitleView. 

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/1235097/191573255-72d00054-69ea-4d6f-890a-6482b3a3ddb7.png">

After update

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/1235097/191573328-725981ed-70c2-4639-9ee2-e7bb1551103b.png">

### Steps to Reproduce

1 -  Create  Filew new app 
2 - Run the app and check the Title
3 - Update  Microsoft.WindowsAppSDK to Version="1.2.220727.1-experimental1"
4 - Compare the Title
 

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows App SDK 1.2 expermienta

**Comment by PureWeen** [comment]
Fixed by https://github.com/dotnet/maui/pull/10273
