### ISSUE TITLE
Bug with WebView

### ISSUE THREAD

**Issue by MielsZ** [dotnet/maui#10246]
### Description

Hello, when i using WebView i take bug with with web page display the code is the same, what is in Maui and Xamarin.Forms (xaml)
The error looks like this
When i press the button of JS i dont see popups
https://learn.microsoft.com/en-us/answers/questions/999712/webview-doesnt-show-pop-up-window.html

### Steps to Reproduce

1) Create ContentPage.xaml
2) write down :
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="YourAppName.MainPage">
    <WebView Source="https://docs.microsoft.com/en-us/dotnet/maui"/>
</ContentPage>
```
### Link to public reproduction project repository

https://github.com/MielsZ/MauiWebViewBug

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

**Comment by jsuarezruiz** [comment]
![issue-10246](https://user-images.githubusercontent.com/6755973/196192211-093297fc-f010-4cb0-a368-1ffc111e2994.gif)

Could you try again with latest version (net7 rc1)?. Cannot reproduce the issue.

**Comment by MielsZ** [comment]
i am all updated in Visual Studio Installer and all work. Thank you very much.
