### ISSUE TITLE
[NetSDKE2E]With VS 17.4 preview 3 + NET7 RC2 installed, Duplicate template".NET MAUI ResourceDictionary (XAML)" display in dotnet new --list

### ISSUE THREAD

**Issue by vdanche** [dotnet/maui#10251]
### Description

With VS 17.4 preview 3 + NET7 RC2 installed, Duplicate template".NET MAUI ResourceDictionary (XAML)" display in dotnet new --list

### Steps to Reproduce

1.install it on locale OS Version 17.4.0 preview 3.0[32920.363.main] + .net7 rc2 SDK
2.Below workloads are installed in vs:

.NET desktop development

ASP.NET and web development

Universal Windows Platform development

Visual Studio extension development

.NET Multi-platform App Ul development--check Xamarin

3.Run “dotnet new --list” in CLI

We found Duplicate template".NET MAUI ResourceDictionary (XAML)" display in dotnet new --list

EN:
![image](https://user-images.githubusercontent.com/65637796/191641484-3bb33d78-e918-48f1-a9ee-94f033e9d2cf.png)

### Link to public reproduction project repository

No

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

VS17.4 preview 3

**Comment by PureWeen** [comment]
[duplicate](https://github.com/dotnet/maui/issues/10202)
