### ISSUE TITLE
Switching MainPage does not work if it is a NavigationPage (similar to #2517)

### ISSUE THREAD

**Issue by gerry123** [dotnet/maui#10271]
### Description

Switching between two different MainPages causes blank page, if the MainPages are NavigationPages.
Error occurs on Android, Windows is ok.

### Steps to Reproduce

1. Create a new app using the VS 2022 .NET MAUI template
2. Create a new BlankPage (ContentPage xaml) 
3. Add logic to switch both of them to MainPage (see App.SetMainPage() in reproduction project)
4. Execute the app

dotnet --version 6.0.401
Visual Studio Version 17.3.4

### Link to public reproduction project repository

git clone https://github.com/gerry123/MauiMainPageSwitchingError.git

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9 ->

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
This should be fixed on .NET 7 if you can/want to test the latest preview builds

https://github.com/dotnet/maui/pull/9955

**Comment by gerry123** [comment]
I get the same error with the latest preview of VS: 17.4.0 Preview 2.1, dotnet 7.0.100-rc.1.22431.12
Reproduction project is updated: git clone https://github.com/gerry123/MauiMainPageSwitchingError.git

**Comment by gerry123** [comment]
I get the same error with the latest preview of VS: 17.4.0 Preview 3, dotnet 7.0.100-rc.2.22477.23
Reproduction project is updated: git clone https://github.com/gerry123/MauiMainPageSwitchingError.git
