### ISSUE TITLE
MAUI Flyout doesnt work on Android when not using Shell

### ISSUE THREAD

**Issue by davidjackson148** [dotnet/maui#10274]
### Description

I'm porting an App over from Xamarin. I don't want to use shell. As I have a login page, then a summary page and them comes the flyoutpage. I can't see how you do this with shell as the flyout menu content is populated in code

Anyway I have (non shell) app with a flyout page that works great in Windows but the detail isn't populated if I run the same project on the android emulator

### Steps to Reproduce

1. Create a Maui App
2. Add A Flyoutpage (with content)
3. Add the code behind for navigation
4. deploy to windows emulator (ok)
5. deeply to android tablet. (doesn't work)

https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/flyoutpage

Use this example know it Xamarin but the code is identical

### Link to public reproduction project repository

[Repo Here](https://github.com/davidjackson148/FlyoutProject.App.git)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android

### Did you find any workaround?

no workaround, have recreated the project several times, same issue

**Comment by davidjackson148** [comment]
Repo is here https://github.com/davidjackson148/FlyoutProject.App.git. I can confirm the issue still exists.

**Comment by breenbob** [comment]
This is affecting me as well. In my testing it seems to work fine on Windows, iOS, and oddly enough, Android phone idiom, but not Android tablet idiom.

Not being able to push a page onto a Flyout detail nav stack seems like it should be higher priority than stuck on the backlog as there is literally no way around this issue, i.e. can't be fixed with a handler like many other issues.

**Comment by breenbob** [comment]
It also seems like not being able to push a page at all should be considered more severe than any issue that might manifest in the rendering of any control on a page, like misaligned shadow or some bits not being clipped...
