### ISSUE TITLE
Windows Capabilities in appxmanifest not properly used by building .msix

### ISSUE THREAD

**Issue by Tardigrade42** [dotnet/maui#10287]
### Description

When the `Capability` `runFullTrust` is replaced with something else (for instance `removableStorage`) and the `msix` file is build, the following is shown during the installation:
![image](https://user-images.githubusercontent.com/37712964/191975535-84ea508f-eccd-4280-a8c1-922eda2b8b39.png)
(The msix file can be found here [MauiIssue-WindowsCapabilities Action Artefact](https://github.com/Tardigrade42/MauiIssue-WindowsCapabilities/actions/runs/3112994129))
As you see, the `runFullTrust` was not removed from the `msix` which is strange.

### Steps to Reproduce

1. Create a Maui-App from the template
2. Go to "Platforms > Windows > Package.appxmanifest"
3. Change:
```XML
<Capabilities>
   <rescap:Capability Name="runFullTrust" />
</Capabilities>
```
to
```XML
<Capabilities>
   <uap:Capability Name="removableStorage" />
</Capabilities>
```
4. Build app with `dotnet publish`
5. Open the MSIX file on your computer

### Link to public reproduction project repository

https://github.com/Tardigrade42/MauiIssue-WindowsCapabilities

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 Pro 21H2

**Comment by Redth** [comment]
Transferring to: https://github.com/microsoft/microsoft-ui-xaml/issues/7766

Please track the issue in WinAppSDK for updates.
