### ISSUE TITLE
Picker ‘SelectedIndex’ is not effective

### ISSUE THREAD

**Issue by JusterZhu** [dotnet/maui#10305]
### Description

When Piker binds a collection or creates Picker.Items, setting SelectedIndex to 0 in xaml does not take effect, and UI has no effect.
![image](https://user-images.githubusercontent.com/11714536/192145994-cbf40e63-e433-4942-873d-5298ac93ce98.png)

### Steps to Reproduce

XAML：
`            <StackLayout Margin="0,0,100,0" Grid.Row="7" Orientation="Horizontal" HeightRequest="35" HorizontalOptions="Center">
                <Label VerticalOptions="Center"  Text="encoding :"></Label>
                <Picker WidthRequest="400" HeightRequest="30" Margin="9,0,3,0" SelectedIndex="0" ItemsSource="{Binding Encodings}" />
            </StackLayout>`

C#：
`        public List<string> Encodings 
        {
            get 
            {
                if (_currentEncoding == null) 
                {
                    _encodings = new List<string>();
                    _encodings.Add("Default");
                    _encodings.Add("UTF8");
                    _encodings.Add("UTF7");
                    _encodings.Add("Unicode");
                    _encodings.Add("UTF32");
                    _encodings.Add("BigEndianUnicode");
                    _encodings.Add("Latin1");
                    _encodings.Add("ASCII");
                }
                return _encodings;
            }
        }`

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.408

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041

**Comment by JusterZhu** [comment]
> You entered the .NET MAUI repository under the reproduction link, please add the right link so we can have a look, thanks!

I don't know how to fill in the correct path. It is not necessary to submit an issue before.

**Comment by affableashish** [comment]
Hi @JusterZhu , what @jfversluis meant is that you should provide a link to the code repository which .NET MAUI team can use to run and view your issue.
You can do this by 2 ways (just use one that's convenient for you):
1.Create a new code repository in GitHub, upload your code to it. Grab a link to it and share it in your issue.
2.Zip your code folder, upload here.

Before you share your code, make sure you remove things you can't share with the public.
If that is too tedious, create a new simple .NET MAUI app, include just the code that can be used to demonstrate your issue and share it here. 

For an example, just take a look at some other issues where users have shared their code. Like this one: 
https://github.com/dotnet/maui/issues/10325

**Comment by jsuarezruiz** [comment]
Same or similar to https://github.com/dotnet/maui/issues/7138

**Comment by JusterZhu** [comment]
> Hi @JusterZhu , what @jfversluis meant is that you should provide a link to the code repository which .NET MAUI team can use to run and view your issue. You can do this by 2 ways (just use one that's convenient for you): 1.Create a new code repository in GitHub, upload your code to it. Grab a link to it and share it in your issue. 2.Zip your code folder, upload here.
> 
> Before you share your code, make sure you remove things you can't share with the public. If that is too much effort, create a new simple .NET MAUI app, include just the code that can be used to demonstrate your issue and share it here.
> 
> For an example, just take a look at some other issues where users have shared their code.

https://github.com/JusterZhu/GeneralUpdate/blob/dev/src/c%23/GeneralUpdate.PacketTool/MainPage.xaml
