### ISSUE TITLE
ControlTemplate breaks RadioButton functionality 

### ISSUE THREAD

**Issue by NestorPV** [dotnet/maui#10301]
### Description

ControlTemplate breaks RadioButton functionality 

Also the template looks different on different platforms, 

### Steps to Reproduce

1. Set a `ControlTemplate` (Run reproduction project)

Expected:  RadioButton work normally and template looks the same
Actual: RadioButton do not work on Android and template looks different on other platforms

### Link to public reproduction project repository

https://github.com/NestorPV/Visual.States

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 11, Android 12

### Did you find any workaround?

No

**Comment by holecekp** [comment]
In general, RadioButtons with a ControlTemplate are currently broken in MAUI. They are rendered incorrectly on Windows. They renders well on Android but they cannot be checked by tapping on them (https://github.com/dotnet/maui/issues/8895) so they are unusable on Android, too.

**Comment by rmarinho** [comment]
This was fixed on #10768
