### ISSUE TITLE
HorizontalOptions DO NOT Work on HorizontalStackLayout

### ISSUE THREAD

**Issue by NestorPV** [dotnet/maui#10300]
### Description

HorizontalOptions DO NOT Work on HorizontalStackLayout

### Steps to Reproduce

Run the reproduction project 

Expected: Elements would use the available horizontal area
Actual: All elements are aligned to the left

### Link to public reproduction project repository

https://github.com/NestorPV/Visual.States

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, Mac, iOS

### Affected platform versions

Android 11, Android 12,  windows10,  iOS 15.5, macOS 12.6
### Did you find any workaround?

Using a stack layout with orientation horizontal.

**Comment by hartez** [comment]
This is as designed; `HorizontalStackLayout` stacks the child views right next to each other; layout options in the horizontal direction have no effect. 

Based on your markup and this issue, it looks like you want the first RadioButton to be left-aligned, the second one to be centered, and the third to be right-aligned. If that's the layout you're looking for, you can achieve that with a Grid:

```
<Grid RadioButtonGroup.GroupName="animals" ColumnDefinitions="*,*,*">
	<RadioButton Value="Start" HorizontalOptions="Start">
		...
	</RadioButton>
	<RadioButton Value="Center" HorizontalOptions="Center" Grid.Column="1">
		...
	</RadioButton>
	<RadioButton Value="End" HorizontalOptions="End" Grid.Column="2">
		...
	</RadioButton>
</HorizontalStackLayout>
```

This will fill the horizontal space available and divide it evenly into 3 sections, putting one RadioButton in each one (and aligning them horizontally within that column).
