### ISSUE TITLE
Pasting into MAUI text entry does not work on iOS

### ISSUE THREAD

**Issue by ss-proc** [dotnet/maui#10302]
### Description

Pasting into the MAUI text entry does not work. I have verified that I am able to paste the data into other iOS apps (like messages). See video here:

https://user-images.githubusercontent.com/104405893/192114697-94cf185c-1a30-4410-9dfc-ab7b35fff074.mp4

### Steps to Reproduce

Open the Maui samples task app https://github.com/dotnet/maui-samples/tree/main/6.0/Beginners-Series

Or create from scratch

1. Create new maui app
2. Add a simple text entry
```
<Entry x:Name="entry"
       Placeholder="Enter text"
       TextChanged="OnEntryTextChanged"
       Completed="OnEntryCompleted" />
```
3. Run the app on iOS
4. Type something into the text entry
5. Select and copy the text in the entry
6. Try to paste it into the text entry

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/Beginners-Series

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

N/A

### Relevant log output

```shell
N/A
```

**Comment by PureWeen** [comment]
@Eilon do you think Context Actions might have broken this?

**Comment by christopher-flexteam** [comment]
I am also experiencing this issue. Further, in iOS 16, selecting text crashes the application.

**Comment by PayProff-Don** [comment]
Is there no workaround?

**Comment by hjam40** [comment]
Really is not important that an application crashes when you paste a text in any field?? I have the same problem in iOS 16…

**Comment by PayProff-Don** [comment]
So we are now able to paste into the textbox with iOS16. I'm sitting at the in-laws now, so can't verify, but I believe the handler solved it, along with the tapping crash.

`#if ANDROID
using AndroidX.AppCompat.Widget;
#elif IOS || MACCATALYST
using UIKit;
#elif WINDOWS
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml;
#endif

namespace PayProff.NativeApp.Controls
{
    /// <summary>
    /// Entry created to ensure similar behavior across platforms
    /// </summary>
    public static class UnifiedEntry
    {
   
        public static void ApplyHandler()
        {
#if IOS
            //Should ensure that tapping the entry multiple times does not crash the app
            Microsoft.Maui.Handlers.EntryHandler.PlatformViewFactory = handler => new WorkaroundMauiTextField();
#endif
        }


    }

#if IOS
    public class WorkaroundMauiTextField : Microsoft.Maui.Platform.MauiTextField
    {
        public WorkaroundMauiTextField() : base()
        {
            //Ensures that the textbox has no border
            BorderStyle = UIKit.UITextBorderStyle.None; //UIKit.UITextBorderStyle.RoundedRect; <-- Part of the original fix
            ClipsToBounds = true;
        }

        [Foundation.Export("selectedTextRange")]
        public new UIKit.UITextRange SelectedTextRange
        {
            get => base.SelectedTextRange;
            set => base.SelectedTextRange = value;
        }
    }
#endif
}
`

**Comment by sunnamed434** [comment]
The same one, but on Windows 11 (Maui Blazor)

**Comment by SagarCIS** [comment]
How to  disable a  pasting option in Custom Entry Handler? or how to override a CanPerform method in handler?

**Comment by Priyabaghelgithub** [comment]
How to make custom entry to disable paste option for iOS because in ios16.1.1 pasting on entry causing crashing of app.???

How we can override a method in custom handler like handler.PlatformView.CanPerform()?

**Comment by jfversluis** [comment]
Can anyone confirm this is still an issue? Tried this just now and it seems to work fine for me.

**Comment by Priyabaghelgithub** [comment]
What is the command to update dotnet workload ?
Cmd= dotnet workload update maui??

**Comment by sunnamed434** [comment]
> dotnet workload update maui

`dotnet workload update` is enough I guess

**Comment by sunnamed434** [comment]
confirms that on Windows 11 (Maui Blazor) everything is now

**Comment by Priyabaghelgithub** [comment]
Solution : Entry pasting issue is fixed after updating to latest .net.

Open the project.
Open Developer command prompt.
Run the cmd : dotnet workload update
Also run cmd : dotnet workload restore
