### ISSUE TITLE
Border-Clipping Issue In Android

### ISSUE THREAD

**Issue by Ahamed-Ali** [dotnet/maui#10311]
### Description

Images are not Clipped correctly as expected in Android but in windows it looks like perfect

In Android 
<img width="188" alt="image" src="https://user-images.githubusercontent.com/102580874/181697605-6be5ebfb-fcec-4d06-9fe5-f0b3ff31da8a.png">
In Windows
<img width="701" alt="image" src="https://user-images.githubusercontent.com/102580874/181697761-d3b4d78a-4eab-4362-974c-472f0d1c850e.png">

### Steps to Reproduce

`  <Border VerticalOptions="Center" HorizontalOptions="Center" HeightRequest="100" WidthRequest="100" Stroke="red" StrokeThickness="15">
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="50"/>
            </Border.StrokeShape>
            <Border.Content>
                <Grid>
                    <Image Source="avatar1.png" Aspect="AspectFill"  />
                </Grid>
            </Border.Content>
        </Border>`

The Whole Project attached in the below repository

### Link to public reproduction project repository

https://github.com/Ahamed-Ali/AvatarView/tree/main

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

### Did you find any workaround?

NA

**Comment by jfversluis** [comment]
Could you try to set `IsClippedToBounds` to true on the `Image` and see if that helps anything?

**Comment by Ahamed-Ali** [comment]
Hi @jfversluis , I set IsClippedToBounds = True on the Grid which contains Image .... **Nothing works**....I also tried to give the IsClippedToBounds to Image but it is only applicable to layout... Could you please verify the issue

**Comment by jsuarezruiz** [comment]
Border does not inherit from Layout, it should clip by default. If you apply a background color to the image you can see that it is clipping but the size is not correct.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprisre 17.7.0 Preview1.0. Not repro on android platform with above project.
https://github.com/Ahamed-Ali/AvatarView/tree/main
![image](https://github.com/dotnet/maui/assets/82450723/0f6851ca-1885-4fd2-8076-9bac80fbaa05)
