### ISSUE TITLE
FilePicker issues when using WindowsPackageType=None

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#10313]
### Description

When using FilePicker on Windows and also set it to be unpackage app with   `WindowsPackageType=None` the application crashes.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1235097/192257170-4ba88ccb-2444-4961-9fd8-6d69ff9b56ea.png">

### Steps to Reproduce

1. Clone and Open repo
2. Set the app to start on windows
3. Change WindowsPackageType=None

### Link to public reproduction project repository

https://github.com/jonathanpeppers/inclusive-code-reviews-ml/tree/main/Maui/MLTrainer

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WindowsAppSDK 1.1

**Comment by mattleibow** [comment]
Does this also happen on a new template app? If so, then this is a bug in the windows api for unpackaged and needs to be opened on github.com/microsoft/WindowsAppSDK

**Comment by mattleibow** [comment]
This issue may be a bug: https://github.com/microsoft/WindowsAppSDK/issues/2995

Waiting on a reply there to see if we should work around this or if this is different behaviour.
