### ISSUE TITLE
debug and release show different NavBar colors

### ISSUE THREAD

**Issue by shameelfazul** [dotnet/maui#10315]
### Description

NavBar background color showing up differently in release

**Debug:**
![Screenshot_1664189876](https://user-images.githubusercontent.com/46882996/192262193-1e61a756-43a7-4cbd-ac55-354efd66746e.png)

**Release:**
![Screenshot_1664189818](https://user-images.githubusercontent.com/46882996/192262074-be198096-c365-449c-835e-a906fc1457fe.png)

### Steps to Reproduce

**AppShell.xaml** :

```
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="Adsemblie.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:views="clr-namespace:Adsemblie.Views"
    BackgroundColor="#0d0e12"
```

### Link to public reproduction project repository

https://github.com/shameelfazul/MAUI-Nav-Bar-Color/tree/main

### Version with bug

6.0.401

### Last version that worked well

Unknown/Other

### Affected platforms

Android - Visual Studio for Mac Preview (17.4 Build 1583)

### Affected platform versions

Android 12.1

**Comment by jfversluis** [comment]
Hey there, thanks for the report! Does it also happen on Windows are you able to test that?

And I see you mention .NET MAUI version 6.0.401, which is not the latest. Are you sure you are using that version? Could you use the latest version of MAUI and see if that helps?

**Comment by shameelfazul** [comment]
> Hey there, thanks for the report! Does it also happen on Windows are you able to test that? Do you also see this happening on Windows or iOS?
> 
> And I see you mention .NET MAUI version 6.0.401, which is not the latest. Are you sure you are using that version? Could you use the latest version of MAUI and see if that helps?

It appears to be fixed on the latest version.

**Comment by jfversluis** [comment]
Not sure why this was reopened, maybe by mistake? If someone is still experiencing this, please open a new issue. Thanks!
