### ISSUE TITLE
Editing text in a searchbar on Android .NET 7 RC1 does not have the expected behavior.

### ISSUE THREAD

**Issue by RonnyRos** [dotnet/maui#10323]
### Description

Editing text in a searchbar does not work as other text inputs, like Entrys.
The text blinker jumps to the end of the text in the Searchbar when you try to edit.

Start.
![image](https://user-images.githubusercontent.com/592363/192294790-decfde1b-7366-4219-9dd6-395242c0d119.png)

Select a text, type one letter or delete one.
![image](https://user-images.githubusercontent.com/592363/192294979-90bc71ee-2dc7-4090-ae4c-1abd3022c187.png)

### Steps to Reproduce

Add a simple searchbar into a new app.
Write some random text, select in the middle of the text and either delete or write a new character, the select indicator jumps to the end of the text.

### Link to public reproduction project repository

none

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.1

**Comment by rachelkang** [comment]
This issue has since been fixed, and you should be able to see the fix in the next release :)
