### ISSUE TITLE
Dotnet MAUI Blazor does not work with android System Web View version 105, beta version 106 works

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#10324]
### Description

Hi 
a country phone code control was added to a login in a Blazor MAUI app. The country code control shows country phone code and associated country flag.

The app worked OK on IOS (for a change) but Android froze on devices that had Android System WebView version 105 i.e the country code control was not rendered and the links on the login screen were not responsive. Once upgraded to version 106 Beta the app is working as expected.

This is a colossal issue for companies as app users may not even know about the existence of the Android System Web View let alone upgrade it.

### Steps to Reproduce

1 - Create a dot net Maui blazor app
2 - a page that has controls with animation such a country code component that displays phone code + flag
3 - install Android System WebView 105
4 - observe screen becomes Non responsive
5 - upgrade to beta 106 or downgrade to version 104
6 - observe all works OK

### Link to public reproduction project repository

na

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Windows server 2022

### Did you find any workaround?

yes upgrade

### Relevant log output

```shell
na
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue which has been discussed in detail in https://github.com/dotnet/maui/issues/9882
Google is working on a fix and that's what you see in the 106 beta version already.
