### ISSUE TITLE
MSBuild says Android API 31 missing when trying to build MAUI app, but it isn't missing.

### ISSUE THREAD

**Issue by SmartmanApps** [dotnet/maui#10337]
### Description

I have a MAUI app which calls library A, which calls library B. I'm working on library B, and would like to just build library A from command-line when needed. Building library A works fine in Visual Studio, but when running MSBuild LibraryA.sln in command-line it says 
"C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(533,2): err
or XA5207: Could not find android.jar for API level 31. This means the Android SDK platform for API level 31 is not ins
talled. Either install it in the Android SDK Manager (Tools > Android > Android SDK Manager...), or change the Xamarin.
Android project to target an API version that is installed. (C:\Program Files (x86)\Android\android-sdk\platforms\andro
id-31\android.jar missing.)", even though it IS installed, and build works fine in VS.
After reading a StackOverflow comment I uninstalled and re-installed API 31 (hopefully get any missing files), but still same error.

So I drilled down into that folder and found that Xamarin.Android.Common.targets doesn't exist, but Xamarin.Android.Common does, so MSBuild is failing to find that folder to begin with (cos it's not there). As I said, VS doesn't seem to care that it's not there, only MSBuild does.
   I don't know whether the issue here is MAUI, MSBuild, or the Android SDK, but in any case this prevents me from running MSBuild on a MAUI app in command-line, that otherwise works in VS (so I therefore currently have no choice but to have an instance of VS open JUST to build that library when needed).

### Steps to Reproduce

1. choose a MAUI library which currently builds fine in VS
2. open a VS developer command prompt and navigate to that solution.
3. run MSBuild yourlibrary.sln

expected outcome: library builds
actual outcome: C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(533,2): err
or XA5207: Could not find android.jar for API level 31. This means the Android SDK platform for API level 31 is not ins
talled. Either install it in the Android SDK Manager (Tools > Android > Android SDK Manager...), or change the Xamarin.
Android project to target an API version that is installed. (C:\Program Files (x86)\Android\android-sdk\platforms\andro
id-31\android.jar missing.)

### Link to public reproduction project repository

https://github.com/SmartmanApps/MauiLib1.git

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 31

### Did you find any workaround?

Not in command-line. Only way to build at all at the moment is in VS.

**Comment by PureWeen** [comment]
@jonathanpeppers

**Comment by jonathanpeppers** [comment]
@SmartmanApps can you share a `.binlog`? Add `-bl` to your command and it should create an `msbuild.binlog` in the current directory. See https://msbuildlog.com

Thanks!

**Comment by SmartmanApps** [comment]
Hi @jonathanpeppers,

    Here you go. :-)
[msbuild.zip](https://github.com/dotnet/maui/files/9660083/msbuild.zip)

**Comment by jonathanpeppers** [comment]
So if you go to `Tools > Android > Android SDK Manager` does it show this is installed?

![image](https://user-images.githubusercontent.com/840039/192671814-a51cb161-e2fa-4464-9045-82bd279baecd.png)

From the build log, it's saying it can't find this file:

    C:\Program Files (x86)\Android\android-sdk\platforms\android-31\android.jar

The only explanation of why some projects work and others don't:

1. The build that works is using a different Android SDK than `C:\Program Files (x86)\Android\android-sdk`. There is a set of fallback logic that tries values like `%ANDROID_HOME%`, VS settings, known locations, etc.
2. One project is an app, and the other is a library

**Comment by SmartmanApps** [comment]
Thanks @jonathanpeppers 

That's interesting, because that's a different file to the one in the error message. I could've more easily determined the issue if it had said that. Another red herring (sigh).

So yes, I do have that in a different location - my D: drive. The thing is that, as far as I'm aware, I only moved my emulator there (i.e. ANDROID_AVD_HOME is set to it), and when I was clicking around the the folders just now I saw the older API's were on C:, but 31 is on D:. ANDROID_HOME isn't set at all. So it looks like, for some reason, when I've (re)installed that API through VS, it went to D:, but MSBuild is looking on C: only.

I'll dig around a bit more with the VS settings and see if I can find where that setting is again (so hard to find settings in VS), and I'll report back on whether I manage to resolve it or not.

Thanks! At least now I'm looking for the right file! (the one in the message doesn't exist in either location)

**Comment by SmartmanApps** [comment]
Hey @jonathanpeppers 

   I found where I had set that in VS, and indeed I had moved the SDK as well, and yet even though that was set in VS MSBuild doesn't know where it is.

   So I manually created an ANDROID_HOME environment variable, rebooted (to be sure), reinstalled API 31 again (to be sure) and MSBuild STILL doesn't know where it is! Argh. How do I tell it where to look?

   I've attached a screenshot which shows...
1. Windows explorer showing that the API is installed at that location.
2. VS pointing to that location
3. ANDROID_HOME pointing to that location
4. error message I get from VS about not finding that location. Note though that I've been getting that message for a long time, but builds in VS work anyway (so I've just been ignoring it). What isn't working is MSBuild in command-line.

   Any more ideas on how to point MSBuild to the right location? Or why VS both does and doesn't know where it is?

P.S. maybe later we can get some follow-up on this with the relevant team(s) so that when one changes the location in VS, it does whatever is needed so that everyone else (in this case MSBuild) will also know where you've moved it to.

![AndroidSDK](https://user-images.githubusercontent.com/20635275/192708124-599a37be-e239-41c2-972b-662caed988c9.jpg)

**Comment by VladislavAntonyuk** [comment]
Try removing spaces from the path

**Comment by SmartmanApps** [comment]
@VladislavAntonyuk The only spaces in the path are in "Program Files (x86)", which is a Windows-created directory - not sure what would break if I changed that. Surely MSBuild should be written to cope with long filenames?

**Comment by VladislavAntonyuk** [comment]
I have a warning in rider that there shouldn't be any spaces in Android sdk path.

**Comment by SmartmanApps** [comment]
But the original path was identical, just on C not D. i.e. "C:\Program Files (X86)\Android\android-sdk" was the original location. When I moved it from one drive to the other I copied the rest of the path.

**Comment by SmartmanApps** [comment]
But I guess I could move it somewhere else anyway - somewhere without spaces. I'll try that out...

**Comment by SmartmanApps** [comment]
32Gb - no wonder I moved it. This will take a while. I'll let you know the outcome. I still maintain that MSBuild should be able to deal with it - VS manages to deal with it.

**Comment by jonathanpeppers** [comment]
@SmartmanApps command-line builds aren't going to be able to find a custom Android SDK location unless you do one of:

* Set `%ANDROID_HOME%`
* Pass `-p:AndroidSdkDirectory=D:\Android\android-sdk` at the command-line

The reason it works inside Visual Studio, is that each VS instance has its own registry key for persisting settings. VS passes the path to the key during the build. Command-line builds wouldn't know which registry key to look for.

This is the same logic we've had in Xamarin.Android for years, so this isn't really anything related to .NET MAUI.

Hope that helps! I think we can close this? Or file a new issue here if there is something we missed, thanks: https://github.com/xamarin/xamarin-android/issues

**Comment by SmartmanApps** [comment]
Yes! That works! Thank you so much @jonathanpeppers. And thanks for explaining how it's working in VS.

Note that once I had it working, I tried same method again using "D:\Program Files (X86)...", and that works also, so the spaces are definitely not an issue (maybe that's an issue with Jetbrains itself).

Also, as previously noted, setting ANDROID_HOME had no effect whatsoever, so it's not looking there.

It's still the case that there's a reference somewhere to the original location (C:\Program Files (x86)...), and it would be good to know where that is, as that would be the actual fix for the issue (updating that reference), but we have a work-around anyway, so that's good. :-)

I'm only using MAUI, so I didn't have a way to try a different language to rule that out.

Thanks! :-)
