### ISSUE TITLE
MAUI equivalent to Xamarin.Azure.NotificationHubs.iOS for iOS push notifications

### ISSUE THREAD

**Issue by rimex-bkimmett** [dotnet/maui#10330]
I am in the process of porting a Xamarin app to MAUI. The app is on iOS and Android, and uses Azure NotificationHubs to receive push notifications.

While everything is going mostly smoothly, there is one problem on the iOS side. The Xamarin.Azure.NotificationsHubs.iOS NuGet package is based on Xamarin.iOS and is not compatible with MAUI. What are my options for connecting to Azure NotificationHubs on iOS now?

**Comment by PureWeen** [comment]
@davidortinau

**Comment by aritchie** [comment]
Use Microsoft.Azure.NotificationHubs instead.  It is netstandard2.0.

**Comment by innomarcoItalia** [comment]
@aritchie ...  but Microsoft.Azure.NotificationHubs is for the back-end.
We need Xamarin.Azure.NotificationHubs.iOS to register the token to Azure NotificationHubs

**Comment by aritchie** [comment]
It works for client (listener connection string) or server (full connection string).  I do it already on https://GitHub.com/shinyorg/shiny

**Comment by Redth** [comment]
Thanks, it is indeed possible to use the netstandard library as a client as @aritchie stated.

@mpodwysocki is this the currently recommended path?

**Comment by mpodwysocki** [comment]
@

> Thanks, it is indeed possible to use the netstandard library as a client as @aritchie stated.
> 
> @mpodwysocki is this the currently recommended path?

Correct, as for now the only supported path is the Xamarin Component.  Adding @marstr who is on the Notification Hubs Team to provide more details, for any possible net6.0-ios/android support as I'm now on the Azure SDK team.

**Comment by jfversluis** [comment]
Looks like there is a path forward. In either case, this is not something we can do much about. If you need anything else in this area please report it here: https://github.com/Azure/azure-notificationhubs-dotnet

Thanks!
