### ISSUE TITLE
[iOS] Status Bar Background rectangle visible in Landscape mode

### ISSUE THREAD

**Issue by ewerspej** [dotnet/maui#10349]
### Description

On iOS (15.5), when using a Shell app, the background rectangle of the status bar is displayed when rotating the device into landscape mode. The rectangle stays visible on the upper left corner, covering parts of the navigation bar/title bar while it should actually disappear entirely, because iOS 15.5 does not show the status bar in landscape mode at all.

### Steps to Reproduce

1. Create a MAUI App with a Shell
2. Run the app on iOS
3. Rotate into landscape mode

Expected behavior: The status bar background disappears, because the status bar is hidden in landscape mode
Actual behavior: The rectangle of the status bar background is shown in the upper left corner of the device, covering parts of the navigation bar/title bar

### Link to public reproduction project repository

https://github.com/ewerspej/dotnet-maui-ct-bug-repro-status-bar-ios

### Version with bug

7.0.100-rc.1.22431.12

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
Can you include a screenshot please?

**Comment by ewerspej** [comment]
I will provide a sample as soon as possible

**Comment by ewerspej** [comment]
> Can you include a screenshot/repro please? 

Yes, I will create a repository soon and add a screenshot, too

**Comment by ewerspej** [comment]
@PureWeen This seems to be a _CommunityToolkit.Maui.Behaviors_ problem, but might just as well be related to MAUI directly. I'm going to add the repo here, and if necessary, I'll add the same issue in the [CommunityToolkit.Maui](https://github.com/CommunityToolkit/Maui/issues) repo.

**Comment by ewerspej** [comment]
@PureWeen Repo: https://github.com/ewerspej/dotnet-maui-ct-bug-repro-status-bar-ios

**Comment by jfversluis** [comment]
This is a but for the Community Toolkit, thanks! :)
