### ISSUE TITLE
MauiApp is a Poor Name for a Class - Should be Renamed

### ISSUE THREAD

**Issue by Torquecode-Ltd** [dotnet/maui#10343]
### Description

I wanted to try out the Maui framework for building mobile and desktop apps.  I created a new project.  Visual Studio automatically suggested the name "MauiApp1", but I didn't like the "1" so I removed it and set the project name to "MauiApp".  It is common to see projects with names like this.  (For example in the Calculator solution I have these projects: "MyCompany.Calculator.WpfApp" and "MyCompany.Calculator.WinFormsApp" and "MyCompany.Calculator.WebApp" etc. which all share the same calculator library code).

The project failed to build.  As a new developer to the framework this is a bad first impression.

I discovered this post:
https://github.com/dotnet/maui/issues/8474

But judging from the comments I don't think you guys are understanding the issue here.  The problem is **not** that you need to safeguard against "thousands of names that wouldn't work".  The problem is that thousands of new developers are going to choose "MauiApp" as their first project name (it's just the obvious name for a new project; it happened to me and it happened to the guy who posted in the link above and it's going to happen to lots of others).

The suggestion by Visual Studio of "MauiApp1" for the project name highlights that "MauiApp" is a typical name for the project and is likely to cause other developers to fall in to this trap (who likes to have a "1" at the end of their project names?!).

**Looking deeper there are more serious issues.**

We also have the class "MauiApplication" ?!  What's the difference between MauiApp and MauiApplication ?!

To add to the confusion, the builder for MauiApp has an extension method "UseMauiApp" but it takes a type of IApplication  (which is not a MauiApp type) - this is confusing.

So not only is the project failing to build, but the class names and method names are confusing.  As a new developer to the framework this is a bad first impression.

**Quick Fix:**  In the template generated code, fully qualify the usage of Microsoft.Maui.Hosting.MauiApp class so that it doesn't conflict with any namespace and makes it more obvious that this is in the hosting namespace and is different from Microsoft.Maui.MauiApplication class.  This will mean that at least the project builds even if the project is named "MauiApp".  It will also make it clear that the MauiApp class is related to the "Hosting" namespace which will help new developers understand it better and avoid confusion.

```csharp
using MauiHosting = Microsoft.Maui.Hosting;
var builder = MauiHosting.MauiApp.CreateBuilder();

// or just use
var builder = Microsoft.Maui.Hosting.MauiApp.CreateBuilder();
```

**Better Fix**  "MauiApp" is a terrible name for this class - rename this class, for example "MauiHostingApp" or just "HostingApp" (because it is in the "Hosting" namespace).  Make it clear what this class is doing and what makes it different from the Microsoft.Maui.MauiApplication class.

### Public API Changes

Example of changes to the way the project template generates the automatic code:

```csharp
using Microsoft.Maui.Hosting;

public static class MauiProgram
{
    public static HostingApp CreateHostingApp()
    {
        var builder = HostingApp.CreateBuilder();
        builder
            .UseMauiApp<App>()  // Note this is another big confusion, the "Maui App" here is not the MauiApp from Hosting, but calling the class "HostingApp" clears up this confusion.
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            });

        return builder.Build();
    }
}
```

### Intended Use-Case

This proposed change is to make it easier for developers to understand and work with the code.  It will avoid a "gotcha" for developers who are trying this framework out for the first time.

**Comment by Eilon** [comment]
Hi, thank you for the feedback. Changing this would be a breaking change and break every existing .NET MAUI application. We will consider this feedback in future naming needs.

**Comment by Torquecode-Ltd** [comment]
@Eilon
Also I made a suggestion above of using the fully qualify namespace - that would not be a breaking change.

**Comment by Eilon** [comment]
Hi @Torquecode-Ltd , that wouldn't be a breaking change, but it would likely make the code less readable or desirable to many users, to avoid a problem that only occurs when the project or another type has the name `MauiApp`, which we consider to be a rare case.
