### ISSUE TITLE
Maui failed to reference ios binding library

### ISSUE THREAD

**Issue by wzh425** [dotnet/maui#10344]
### Description

![截屏2022-09-27 20 54 53](https://user-images.githubusercontent.com/13762077/192532791-fbefffdb-11aa-4303-8462-461972300f45.png)

### Steps to Reproduce

1. Create ios binding library to bind WeChatSDK and compile successfully. 
2. The binding library is referenced in the maui project but cannot be generated

**IOS.WeChat.csproj**
![截屏2022-09-27 21 06 53](https://user-images.githubusercontent.com/13762077/192534779-420d878c-3d65-4806-bfa5-36af1b738b14.png)

### Link to public reproduction project repository

https://github.com/wzh425/MauiBlazorDemo

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios15.4

### Relevant log output

```shell
目标 _LinkNativeExecutable:
        Tool xcrun execution started with arguments: clang++ -F /Users/kakuhiroshi/Projects/MauiBlazorDemo/MauiBlazorDemo -framework CFNetwork -F /Users/kakuhiroshi/Projects/MauiBlazorDemo/MauiBlazorDemo -framework CoreTelephony -F /Users/kakuhiroshi/Projects/MauiBlazorDemo/MauiBlazorDemo -framework Security -F /Users/kakuhiroshi/Projects/MauiBlazorDemo/MauiBlazorDemo -framework SystemConfiguration -force_load /Users/kakuhiroshi/Projects/MauiBlazorDemo/IOS.WeChat/bin/Debug/net6.0-ios/IOS.WeChat.dll -ObjC -all_load -lstdc++ -lsqlite3.0 -lz -mios-version-min=14.2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk -arch arm64 /Users/kakuhiroshi/Projects/MauiBlazorDemo/MauiBlazorDemo/obj/Debug/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Private.CoreLib.dll.o /usr/local/share/dotnet/packs/Microsoft.iOS.Runtime.ios-arm64/15.4.442/runtimes/ios-arm64/native/libxamarin-dotnet-debug.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libSystem.IO.Compression.Native.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libSystem.Native.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libSystem.Net.Security.Native.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libSystem.Security.Cryptography.Native.Apple.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libicudata.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libicui18n.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libicuuc.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libmono-component-debugger-static.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libmono-component-diagnostics_tracing-static.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libmono-component-hot_reload-stub-static.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libmonosgen-2.0.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libmono-component-debugger-static.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libmono-component-diagnostics_tracing-static.a /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/6.0.5/runtimes/ios-arm64/native/libmono-component-hot_reload-stub-static.a -force_load /Users/kakuhiroshi/Projects/MauiBlazorDemo/IOS.WeChat/bin/Debug/net6.0-ios/IOS.WeChat.resources/libWeChatSDK.a -framework AuthenticationServices -framework CFNetwork -framework CloudKit -framework Contacts -framework ContactsUI -framework CoreFoundation -framework CoreGraphics -framework CoreLocation -framework CoreTelephony -framework CoreText -framework Foundation -framework Intents -framework MediaPlayer -framework QuartzCore -framework SafariServices -framework Security -framework SystemConfiguration -framework UIKit -framework WebKit -framework GSS -framework CFNetwork -framework CFNetwork -framework CoreTelephony -framework Security -framework SystemConfiguration -rpath @executable_path/Frameworks /Users/kakuhiroshi/Projects/MauiBlazorDemo/MauiBlazorDemo/obj/Debug/net6.0-ios/ios-arm64/nativelibraries/main.arm64.o /Users/kakuhiroshi/Projects/MauiBlazorDemo/MauiBlazorDemo/obj/Debug/net6.0-ios/ios-arm64/nativelibraries/registrar.o -o /Users/kakuhiroshi/Projects/MauiBlazorDemo/MauiBlazorDemo/obj/Debug/net6.0-ios/ios-arm64/nativelibraries/MauiBlazorDemo -ObjC -all_load -lstdc++ -lsqlite3.0 -lz -dead_strip -u_SystemNative_Log -u_SystemNative_GetEnv -u_SystemNative_SearchPath_TempDirectory -u_SystemNative_ConvertErrorPlatformToPal -u_SystemNative_ConvertErrorPalToPlatform -u_SystemNative_StrErrorR -u_SystemNative_Close -u_SystemNative_GetFileSystemType -u_SystemNative_FLock -u_SystemNative_FSync -u_SystemNative_FTruncate -u_SystemNative_GetCpuUtilization -u_SystemNative_GetCwd -u_SystemNative_GetEGid -u_SystemNative_GetNonCryptographicallySecureRandomBytes -u_SystemNative_GetCryptographicallySecureRandomBytes -u_SystemNative_GetSystemTimeAsTicks -u_SystemNative_GetTimestamp -u_SystemNative_LowLevelMonitor_Create -u_SystemNative_LowLevelMonitor_Destroy -u_SystemNative_LowLevelMonitor_Acquire -u_SystemNative_LowLevelMonitor_Release -u_SystemNative_LowLevelMonitor_Wait -u_SystemNative_LowLevelMonitor_TimedWait -u_SystemNative_LowLevelMonitor_Signal_Release -u_SystemNative_LSeek -u_SystemNative_Free -u_SystemNative_Malloc -u_SystemNative_MkDir -u_SystemNative_MksTemps -u_SystemNative_Open -u_SystemNative_PosixFAdvise -u_SystemNative_FAllocate -u_SystemNative_PRead -u_SystemNative_PReadV -u_SystemNative_PWrite -u_SystemNative_PWriteV -u_SystemNative_Read -u_SystemNative_OpenDir -u_SystemNative_GetReadDirRBufferSize -u_SystemNative_ReadDirR -u_SystemNative_CloseDir -u_SystemNative_ReadLink -u_SystemNative_FStat -u_SystemNative_Stat -u_SystemNative_LStat -u_SystemNative_SysLog -u_SystemNative_Unlink -u_SystemNative_Write -u_SystemNative_GetEUid -u_SystemNative_CreateAutoreleasePool -u_SystemNative_DrainAutoreleasePool -u_xamarin_release_managed_ref -u_xamarin_set_gchandle_with_flags_safe -u_UIApplicationMain -u_xamarin_find_protocol_wrapper_type -u_xamarin_log -u_xamarin_release_block_on_main_thread -u_xamarin_get_block_descriptor -u_xamarin_NativeHandle_objc_msgSend_NativeHandle_exception -u_xamarin_NativeHandle_objc_msgSendSuper_NativeHandle_exception -lz -liconv -lcompression
                
        Tool xcrun execution finished (exit code = 1).
                
        ld: warning: ignoring file /Users/kakuhiroshi/Projects/MauiBlazorDemo/IOS.WeChat/bin/Debug/net6.0-ios/IOS.WeChat.dll, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00 0x04 0x00 0x00 0x00 0xFF 0xFF 0x00 0x00 )
        Undefined symbols for architecture arm64:
          "_OBJC_CLASS_$_HBReq", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_HBResp", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_JumpToBizProfileReq", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_JumpToBizWebviewReq", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_OpenTempSessionReq", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_OpenTempSessionResp", referenced from:
              objc-class-ref in registrar.o
        ld: symbol(s) not found for architecture arm64
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        
        /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.442/targets/Xamarin.Shared.Sdk.targets(1219,3): error : clang++ exited with code 1
        /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.442/targets/Xamarin.Shared.Sdk.targets(1219,3): error :         
    已完成在项目“MauiBlazorDemo.csproj”中生成目标“_LinkNativeExecutable”的操作 - 失败。
```

**Comment by PureWeen** [comment]
@rolfbjarne thoughts?

**Comment by wzh425** [comment]
I try to configure it in two ways
I'm sorry, I don't speak English very well

1.IOS.WeChat.csproj 
 `<ItemGroup>
    <Compile Update="libWeChatSDK.linkwith.cs">
      <DependentUpon>libWeChatSDK.a</DependentUpon>
    </Compile>
  </ItemGroup>`
My binding library and project can be compiled and the assembly is generated, but I cannot find the class and namespace of the binding library in the main project
2.IOS.WeChat.csproj 
`<ItemGroup>
    <NativeReference Include="..\OpenSDK1.9.6\libWeChatSDK.a">
      <Kind>Static</Kind>
      <ForceLoad>True</ForceLoad>
      <Frameworks>CFNetwork CoreTelephony Security SystemConfiguration</Frameworks>
      <LinkerFlags>-ObjC -all_load -lstdc++ -lsqlite3.0 -lz</LinkerFlags>
    </NativeReference>
  </ItemGroup>`
MauiBlazorDemo.csproj
`<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>`
In this way, the error proposed by the issues will appear in the configuration

**Comment by wzh425** [comment]
Hope to get your response

**Comment by rolfbjarne** [comment]
The problem is that the `libWeChatSDK.a` file doesn't contain the classes you're trying to bind.

For exampe `HBReq`, it's in your binding:

```shell
git grep HBReq
IOS.WeChat/ApiDefinition.cs:    // @interface HBReq : BaseReq
IOS.WeChat/ApiDefinition.cs:    interface HBReq
```

but it's not in `libWeChatSDK.a`:

```shell
$ nm ./IOS.WeChat/libWeChatSDK.a | grep HBReq
<no output>
```

thus the build fails, because it tries to find the native `HBReq` class when it doesn't exist.

**Comment by wzh425** [comment]
@rolfbjarne  I have handled this error and successfully compiled, but new problems have arisen。

The project successfully generated the assembly of the binding library, but I couldn't call it, and I couldn't find the class and namespace
![截屏2022-09-28 13 30 29](https://user-images.githubusercontent.com/13762077/192696146-26a2b66f-0912-4793-826c-7123cd3a0b45.png)
![截屏2022-09-28 13 29 55](https://user-images.githubusercontent.com/13762077/192696180-8e3ca12a-0cd3-466e-bc9f-96dda047b89c.png)

**Comment by rolfbjarne** [comment]
That's a known problem for intellisense. It should work once you actually build the project.

A workaround is to reference the binding assembly, not the binding project, from the main project.

**Comment by wzh425** [comment]
@rolfbjarne  Thank you very much for your reply。
I'm sorry to have a new problem。
An error occurred when I connected to the local IOS mobile phone for debugging：An error occurred when I connected to the local IOS mobile phone for debugging
`/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.442/tools/bin/mlaunch -sdkroot "/Applications/Xcode.app/Contents/Developer" --installdev "/Users/kakuhiroshi/Projects/MauiBlazorDemo/MauiBlazorDemo/bin/Debug/net6.0-ios/ios-arm64/MauiBlazorDemo.app" --device ios "--devname=吴自浩的iPhone" --install-progress
error HE0004: Could not load the framework 'DVTITunesSoftwareServiceFoundation' (path: /Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/DVTITunesSoftwareServiceFoundation): 
dlopen(/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/DVTITunesSoftwareServiceFoundation, 0x0001): Library not loaded: '@rpath/ContentDelivery.framework/Versions/A/ContentDelivery'
  Referenced from: '/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/DVTITunesSoftwareServiceFoundation'
  Reason: tried: '/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.442/tools/lib/mlaunch/mlaunch.app/Contents/MacOS/../Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.442/tools/lib/mlaunch/mlaunch.app/Contents/MacOS/../Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Library/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/System/Library/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file)
        

应用程序无法上载到设备。
`

**Comment by mattleibow** [comment]
May be related to https://github.com/dotnet/maui/issues/10377

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-macios#16192
