### ISSUE TITLE
iOS Simulators list not populated

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#10346]
### Description

The list of iOS simulators is not populated in the last visual studio update 

> Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.4.0 Preview 2.1

![image](https://user-images.githubusercontent.com/17496741/192558164-66e600fe-ffc5-4e58-8769-4ee0fff2f1d7.png)

### Steps to Reproduce

- Open Visual Studio
- Create any iOS project
- Connect to a mac
- Open list of Simulators

### Link to public reproduction project repository

No demo

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

6.0.400

### Affected platforms

iOS

### Affected platform versions

Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.4.0 Preview 2.1

### Did you find any workaround?

No

### Relevant log output

```shell
dotnet --version

7.0.100-rc.1.22431.12
```

**Comment by arivoir** [comment]
Do I understand correctly I need to remove XCode 14 and install a previous version or I can change only the Command Line Tools of Xcode?

**Comment by SantosVictorero** [comment]
No, you don't need to remove Xcode 14, just install 13.4.1, if you don't have it installed, then select it in Xcode/Preferences/Locations

**Comment by arivoir** [comment]
I installed the tools 13.4 but they don't show up in the combo-box of XCode preferences locations, only 14.0.1 is there

**Comment by SantosVictorero** [comment]
Did you restarted the Mac?

**Comment by arivoir** [comment]
Yes I did it

**Comment by arivoir** [comment]
I'm trying to install the whole XCode 13.4.1 now

**Comment by arivoir** [comment]
Installing XCode 13.4.1 and then selecting the tools worked

![image](https://user-images.githubusercontent.com/17496741/192907246-7454cc1e-4b1d-4400-9235-1f529ddfe29c.png)

Thank you @SantosVictorero

**Comment by SantosVictorero** [comment]
You're welcome @arivoir!

**Comment by AlexeyStarkov** [comment]
Facing the same issue on Mac after updating to Xcode 14. Xamarin is already fixed, but it looks like MAUI still doesn't work with Xcode 14.
