### ISSUE TITLE
Deployed MAUI app as MSIX on server 2019 not unpackage 

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#10363]
### Description

Deployed MAUI app as MSIX on server 2019 not unpackage 

### Steps to Reproduce

1.Create MAUI app.
2.Deplayed as msix.
3.Not worked on server 2019.

### Link to public reproduction project repository

..

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

..

### Did you find any workaround?

..

### Relevant log output

```shell
..
```

**Comment by danies8** [comment]
This the command I used:
msbuild /t:restore AutomationClient.MAUI.csproj
msbuild /t:Publish AutomationClient.MAUI.csproj /p:TargetFramework=net6.0-windows10.0.19041.0 /p:configuration=release /p:GenerateAppxPackageOnBuild=false /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d" /p:PublishSingleFile=true /p:WindowsPackageType=None /p:WindowsAppSDKSelfContained=true /p:SelfContained=true

**Comment by danies8** [comment]
1.Put all files in the folder AutomationClient in C volume.

2.You will need to have the Desktop Experience installed as well as any dependencies for your app 
(.Net Framework, Windows App SDK, etc.) that aren't included by default in Server 2019.
 See https://docs.microsoft.com/en-us/windows/msix/msix-server-2019
3. NET runtime - See link  https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.7-windows-x64-installer
or file windowsdesktop-runtime-6.0.7-win-x64.exe located in C:\AutomationClient\DependenciesServer2019\windowsdesktop-runtime-6.0.7-win-x64.exe 
4. NET Framework - See link  https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer
or ndp48-web.exe located in C:\AutomationClient\DependenciesServer2019\ndp48-web.exe
5.Install latest see link Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle(https://github.com/microsoft/winget-cli/releases/download/v1.3.1872/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle)
or take it from C:\AutomationClient\DependenciesServer2019\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle via powershell
Add-AppxProvisionedPackage -Online -PackagePath C:\AutomationClient\DependenciesServer2019\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -LicensePath C:\AutomationClient\DependenciesServer2019\a941c144deac426082dc9f208f729138_License1.xml -Verbose
(XML can be found here in this link: https://github.com/microsoft/winget-cli/releases/download/v1.3.1872/a941c144deac426082dc9f208f729138_License1.xml 
or take it from C:\AutomationClient\DependenciesServer2019\a941c144deac426082dc9f208f729138_License1.xml)
6.VCLibs - the files located in this link https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages.
Install the x86 and x64 appx files with Add-AppxPackag(https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=windowsserver2019-ps#description=)
Or take it from C:\AutomationClient\DependenciesServer2019\Microsoft.VCLibs.x64.14.00.Desktop.appx && C:\AutomationClient\DependenciesServer2019\Microsoft.VCLibs.x86.14.00.Desktop.appx
The commands are:
Add-AppxPackage -Path "C:\AutomationClient\DependenciesServer2019\Microsoft.VCLibs.x64.14.00.Desktop.appx"
Add-AppxPackage -Path "C:\AutomationClient\DependenciesServer2019\Microsoft.VCLibs.x86.14.00.Desktop.appx"
The results blank window.

**Comment by PureWeen** [comment]
@danies8 does this look related?

https://github.com/microsoft/WindowsAppSDK/issues/2829

**Comment by danies8** [comment]
@PureWeen I read #2829 I list what I installed in server 2019. Do I need to install something more? 
If yes please specify link where I can install this ?

**Comment by danies8** [comment]
@PureWeen 
Do I need to install https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads
Version 1.1 3 files c#& c++ extension and x64 installer?

**Comment by mattleibow** [comment]
The story with MSIX is that all the requirements and dependencies should be installed with the app.

If you create a plain WinUI app, does it also have issues?

Also, the publish with ` /p:PublishSingleFile=true` might be an issue as this is not relevant.

And, `/p:GenerateAppxPackageOnBuild=true` should not be needed when publishing.

Is there a difference when you use `dotnet publish -f net6.0-windows10.0.19041.0 -c Release ...`

**Comment by danies8** [comment]
I used tis code:
dotnet publish -f net6.0-windows10.0.19041.0 -c Release /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d"
and it work on window 10 but not work on server 2019, i get blank window

**Comment by danies8** [comment]
@mattleibow  can you please say what to do?

**Comment by mattleibow** [comment]
This issue was moved to microsoft/WindowsAppSDK#3020
