### ISSUE TITLE
Windows cannot install package Microsoft.WindowsAppRuntime.1.1_1003.565.600.0_x64__8wekyb3d8bbwe

### ISSUE THREAD

**Issue by leobarbastefano** [dotnet/maui#10379]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Windows cannot install package Microsoft.WindowsAppRuntime.1.1_1003.565.600.0_x64__8wekyb3d8bbwe because this package is not compatible with the device. The package requires OS version 10.0.17763.0 or higher on the Windows.Universal device family. The device is currently running OS version 10.0.16299.1127

**Comment by PureWeen** [comment]
MAUI doesn't currently support `10.0.16299.1127`

**Comment by leobarbastefano** [comment]
I updated my windows and now it's working. thank you
