### ISSUE TITLE
Android Issue - MediaPicker

### ISSUE THREAD

**Issue by Javierflo95** [dotnet/maui#10385]
### Description

When I working with Net Maui MediaPicker

```c#
                 FileResult photoSelected = await MediaPicker.Default.PickPhotoAsync();

                if (photoSelected != null)
                {
                    var stream = await photoSelected.OpenReadAsync();
                    ImageProfileUser = ImageSource.FromStream(() => stream);
                }
```

Just this code works for iOS

![image](https://user-images.githubusercontent.com/11860518/192931268-466b2efd-89c4-40b1-95f5-11483f86d6d6.png)

### Steps to Reproduce

1. Create net Maui project
2. use MediaPicker Maui class
3. run app with Android
4. Select the image you want.
5. the application is closed automatically

### Link to public reproduction project repository

https://github.com/xamarin/Essentials/issues/1715

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Api 31

**Comment by innomarcoItalia** [comment]
see if it can help you: 
https://github.com/dotnet/maui/issues/9810

**Comment by moljac** [comment]
> see if it can help you: #9810

That issue and associated sample work with image capturing, while OP asked about `PickPhotoAsync`.

I was not able to reproduce the error.

Repro sample:

[Sample.Issue_10385.MediaPickerCrash.zip](https://github.com/dotnet/maui/files/11065554/Sample.Issue_10385.MediaPickerCrash.zip)

@Javierflo95 would you be so kind and add log/stacktrace or more details abbout the crash.
