### ISSUE TITLE
Editor within Frame causes application freeze for Windows

### ISSUE THREAD

**Issue by DelphinRP** [dotnet/maui#10387]
### Description

Placing an Editor inside a Frame causes the application to freeze.

**Note:** If I put `Text="Hello"` instead of `Text="HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello"` the application does not freeze. So the freeze *might* depend on the amount of text set to the editor?

![maui_editor_freeze](https://user-images.githubusercontent.com/85873523/193012899-3262ce0d-d111-414a-b218-29d1c449b0cb.gif)

### Steps to Reproduce

1. Create a new MAUI App
2. Open `MainPage.xaml`
3. Add the following XAML before the `</VerticalStackLayout>`:
```xaml
            <CheckBox
                x:Name="displayFrame" />
            <Frame>
                <Editor
                    IsVisible="{Binding IsChecked, Source={x:Reference displayFrame}}"
                    Text="HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello"
                    Margin="0,10,0,0"/>
            </Frame>
```
4. Run the application
5. Click the checkbox
6. Application freezes

### Link to public reproduction project repository

https://github.com/DelphinRP/maui-frame-editor-freeze

### Version with bug

6.0.401

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 19044.2006

### Did you find any workaround?

No

### Relevant log output

No log

**Comment by jsuarezruiz** [comment]
Can reproduce the issue with the attached sample. However, in latest net7.0 branch cannot reproduce the freeze (an infinite layout cycle?). but there is something wrong with the Layout:
![issue-10387](https://user-images.githubusercontent.com/6755973/193035760-b1ab12bd-c5cd-4ec0-8565-da7aaef11ddb.gif)

**Comment by dhindrik** [comment]
I have a similar problem. If I have an Editor inside a StackLayout or VerticalStackLayout it freezes the app. But only when running with .NET 7. Suppose I change the project back to .NET 6 it works. 

@jsuarezruiz do you think that my problem is related to this bug or should I create a new one?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 with below Project:
[10387.zip](https://github.com/dotnet/maui/files/11573883/10387.zip)

.NET 6: Application freeze.
.NET 7: Application does not freeze, but there are some layout issues.
![image](https://github.com/dotnet/maui/assets/97647558/ea896e87-cd1e-4424-8b39-61947b749c3a)

**Comment by last-Programmer** [comment]
It is happening with ios also when we try to set the text property of the editor that is inside frame control. i set the text property delayed and the issue is solved

**Comment by karthikraja-arumugam** [comment]
There is no freezing issue and layout issue with net8. Can you please check this with Net8?

https://github.com/user-attachments/assets/62d55ae6-5d62-498b-b800-1239627bcc0c
