### ISSUE TITLE
Uneven margin/padding along OnPlatform

### ISSUE THREAD

**Issue by IPdotSetAF** [dotnet/maui#10391]
### Description

there is no way to set padding or margin with different value for each side of the view and also separate them for platforms.

maui on android does not support ' ' separated values for setting padding or margin so we have to use ',' and when used inside an OnPlatform (which also separates platforms using ',') does not work correctly.

### Steps to Reproduce

        `Margin="{OnPlatform Android=10,5,10,10 ,WinUI=10,5}"`

### Link to public reproduction project repository

none

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 12, Windows

### Did you find any workaround?

I tried using this approach but still no result

```
<*.Margin>
<OnPlatform>
<On Platform="WinUI" value="10,5"/>
<On Platform="Android" value="10,5,10,10"/>
</OnPlatform>
</*.Margin>
```

**Comment by IPdotSetAF** [comment]
> @StephaneDelcroix What would the best approach here?

the second approach that i mentioned should work logically but for some reason it is not.

another approach would be supporting ' 'separated values for margin/padding on android as well

**Comment by jedusei** [comment]
@IPdotSetAF  Try this:
`Margin="{OnPlatform Android='10,5,10,10', WinUI='10,5'}"`

**Comment by IPdotSetAF** [comment]
> 

wow, that works. thanks a lot.
