### ISSUE TITLE
.NET 7: Maps control doesn't show zoom controls with constant IsZoomEnabled="true" 

### ISSUE THREAD

**Issue by GiovanniCmpaner** [dotnet/maui#10394]
### Description

Using .NET 7. 
When using a maps control with IsZoomEnabled="true", the zoom controls aren't displayed.
If you edit the XAML to false, then to true again, after hot reload the zoom controls show up.

![image](https://user-images.githubusercontent.com/22120203/193077361-3a31b98e-4d52-4d85-8ec6-e14fa5bca397.png)

### Steps to Reproduce

1. Create a .NET MAUI App
2. Edit project file and add the reference `<PackageReference Include="Microsoft.Maui.Controls.Maps" Version="7.0.0-rc.1.6683" />`
3. Add `.UseMauiMaps()` to builder in `MauiProgram.cs`
4. Create a page, add reference `xmlns:map="clr-namespace:Microsoft.Maui.Controls.Maps;assembly=Microsoft.Maui.Controls.Maps"`
5. Add a map control `<map:Map IsZoomEnabled="true" />`
6. Modify `AndroidManifest.xml`, add permissions and google maps API key.
7. Start android emulator, navigate to page
8. Observe that the zoom controls aren't displayed
9. Edit `IsZoomEnabled` to `false`, do a hot reload, then change back to `true`, do another hot reload, observe that now the zoom controls show up

### Link to public reproduction project repository

https://github.com/GiovanniCmpaner/MapSample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.0 and up

**Comment by rachelkang** [comment]
@rmarinho have you seen this one yet?
