### ISSUE TITLE
NavigationPageRenderer is broken in .net7 

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#10397]
System.InvalidCastException
  Message=Unable to convert instance of type 'Google.Android.Material.TextView.MaterialTextView' to type 'AndroidX.AppCompat.Widget.Toolbar'.

 	0x26 in Microsoft.Maui.Controls.Compatibility.Platform.Android.AppCompat.NavigationPageRenderer.SetupToolbar at D:\a\_work\1\s\src\Compatibility\Core\src\Android\AppCompat\NavigationPageRenderer.cs:771,5	C#

**Comment by Stedy59** [comment]
So, am I to understand that.....
 - You author an Android renderer, and don't have a test setup to validate?
 - The NavigationPageRenderer works fine in .net6

**Comment by jBijsterboschNL** [comment]
Are there any plans to dive into this issue? I'm trying to migrate a project for a client of mine and this way I'm unable to re-use the custom NavigationPageRenderer that is used throughout the app, which has some very specific needs that I'm not yet able to put in the new Handler parts just yet. And this seems like a clear issue? If needed I can make a test project to show the issue properly.

**Comment by jcslim89** [comment]
I am also experiencing the same issue. Is there any fix on this issue yet?

**Comment by Stedy59** [comment]
I am closing this issue... It is almost a year old and most likely will never be addressed.

I moved on from "Compatibility" implementations to "Handlers". I have this working via that path.
