### ISSUE TITLE
XamlC compiler null-refs when encountering a binding to an array access

### ISSUE THREAD

**Issue by 333fred** [dotnet/maui#10396]
### Description

When I have a ViewModel binding to an array backing property, I'm seeing the XamlC compiler null ref.

### Steps to Reproduce

1. Clone https://github.com/333fred/maui-layout-bugs.
2. Comment https://github.com/333fred/maui-layout-bugs/blob/main/Test/MainPage.xaml.cs#L21 and uncomment https://github.com/333fred/maui-layout-bugs/blob/main/Test/MainPage.xaml.cs#L23
3. Attempt to build the solution.

### Link to public reproduction project repository

https://github.com/333fred/maui-layout-bugs

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

.NET 7 RC 1

### Did you find any workaround?

Use a `List` instead, as on line 21.

**Comment by rachelkang** [comment]
@StephaneDelcroix what do you think?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 and Android with provided Project: [Test.zip](https://github.com/dotnet/maui/files/11573953/Test.zip)

![image](https://github.com/dotnet/maui/assets/97647558/61384194-ab58-48b9-81bd-7e62e003a249)

**Comment by StephaneDelcroix** [comment]
we look for the indexer instead of doing `ldelem` for System.Array
