### ISSUE TITLE
[CustomControl] HotReload works for nested items that derive from Element but not for items that derive from VisualElement

### ISSUE THREAD

**Issue by the8thC** [dotnet/maui#10390]
### Description

I have a 2 custom controls that have a **ContentProperty** attributes which _point to_ **ObservableCollections** of items -- in 1 control items derive from **Element**, in the other items derive from **VisualElement**. Controls are otherwise identical.
In the case of **Element**-items - HotReload works, in the case of **VisualElement**-items - it doesn't

I'm one of the [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/) developers, this issue has a **high** priority for us and we do not have a workaround (since we also can't change change inheritance due to implicit styles not working for our controls' nested items https://github.com/dotnet/maui/issues/10370) . Thank you for your help.

https://user-images.githubusercontent.com/21204523/193033969-21de3245-383e-42cb-b3a5-2c9680013ac1.mp4

P.S. Could this also be connected to https://github.com/dotnet/maui/issues/10066 or https://github.com/dotnet/maui/issues/9640? @drasticactions

### Steps to Reproduce

1. Clone reproduction repository
2. Try to add text to Element items and VisualElement items (as in the video)

Expected: HotReload works for both
Actual: HotReload only works for the item that derives from Element

### Link to public reproduction project repository

https://github.com/the8thC/ElementVisuaElementHotReload

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

iOS 15, Android API 32

**Comment by PureWeen** [comment]
@the8thC if you implement `IVisualTreeElement` and provide explicit implementations for retrieving the children and the parent does that resolve?

**Comment by the8thC** [comment]
@PureWeen it does resolve, thank you!
