### ISSUE TITLE
[Android12-API31] Entry: changing IsPassword false to true, does not show the numbers, when Keyboard attribute is "Numeric"

### ISSUE THREAD

**Issue by leoderja** [dotnet/maui#10407]
### Description

I have a functionallity in an App, that allows to change a PIN number. Next to every Entry (OldPIN, NewPIN & ConfirmPIN) there is a show/hide button that toggles IsPassword attribute (false/true) of the corresponding Entry. In the case of an Entry with the Keyboard attribute = Numeric, when the attribute IsPassword changes from true to false, the Entry control stays showing the passwords chars instead of the PIN's numbers.

### Steps to Reproduce

1. Create an Empty MAUI project.
2. Set the content of **MainPage.xaml** whith this xaml:

```
    <ScrollView>
        <VerticalStackLayout Spacing="10" Padding="10" HorizontalOptions="FillAndExpand">
            
            <HorizontalStackLayout Spacing="10">
                <!--Stays as password char after first toogle-->
                <Button Text="Entry1: numeric" Clicked="ToggleEntry1_Clicked"/>
                <Entry x:Name="Entry1" Text="1234" Keyboard="Numeric" />
            </HorizontalStackLayout>
            
            <HorizontalStackLayout Spacing="10">
                <!--OK-->
                <Button Text="Entry2: text" Clicked="ToggleEntry2_Clicked"/>
                <Entry x:Name="Entry2" Text="Abc - + 123" Keyboard="Text" />
            </HorizontalStackLayout>
            
        </VerticalStackLayout>
    </ScrollView>
```

3. Enter this event handlers on the **MainPage.xaml.cs**:

```
private void ToggleEntry1_Clicked(object sender, EventArgs e)
{
    Entry1.IsPassword = !Entry1.IsPassword;
}

private void ToggleEntry2_Clicked(object sender, EventArgs e)
{
    Entry2.IsPassword = !Entry2.IsPassword;
}
```

### Link to public reproduction project repository

https://github.com/leoderja/MauiApp1_EntryIsPassword

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android12 (not tested on MacOS/iOS)

### Did you find any workaround?

No workarounds

**Comment by mjphillips1981** [comment]
Same issue for me as well.
