### ISSUE TITLE
Line coordinates are not respected

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#10415]
### Description

A line that has coordinates differing from 0 is not displayed correctly in MAUI.

Code:
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="LineExample.MainPage">

    <Grid RowDefinitions="200" ColumnDefinitions="200" BackgroundColor="Beige" WidthRequest="200" HeightRequest="200">
        <Line X1="0" Y1="0" X2="100" Y2="100" Stroke="Blue"/>
        <Line X1="100" Y1="0" X2="100" Y2="100" Stroke="green"/>
        <Line X1="100" Y1="100" X2="200" Y2="200" Stroke="Red"/>
    </Grid>

</ContentPage>
`

Result:
![image](https://user-images.githubusercontent.com/114725843/193210076-804e2875-d0e9-446a-8599-fbe716de3426.png)

Expected Result (created in Xamarin.Forms):
![image](https://user-images.githubusercontent.com/114725843/193211072-4785a46d-89ec-4de0-ac0e-90dbdf6fe57a.png)

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Edit MainPage to look like the code example above
3. Start the App

### Link to public reproduction project repository

https://github.com/EulerKermi/LineExample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
Similar or the same as https://github.com/dotnet/maui/issues/9089

**Comment by labuisse** [comment]
I have been plagued by this primary functionality for weeks now and cannot understand how it passed testing.  Glad to see a fix is in the works, very sad it is in the backlog.

A program that worked well with the November preview is completely broken.  A workaround that is helping is to offset the Line or Polyline coordinates to get a 0,0 point then correct back using TranslationX and TranslationY.  (Don't know how to make that work in XAML with proportional coordinates.)

**Comment by rmarinho** [comment]
fixed by #10417
