### ISSUE TITLE
Not able to deploy MAUI app to physical iPhone using VS 17.3.5 w/ MAUI 6.0.536

### ISSUE THREAD

**Issue by Mephisztoe** [dotnet/maui#10422]
### Description

After having reset my developer machine and installed VS 17.3.5 completely from scratch, I am not able to deploy MAUI apps to my iPhone anymore. Visual Studio has successfully been paired with my MacOSX - including a warning about the XCode version not being the one expected (expected: 13.3, is: 14.0).

Compilation works.

On deploy, this is the error message that comes up:

error HE0004: Could not load the framework 'DVTITunesSoftwareServiceFoundation' (path: /Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/DVTITunesSoftwareServiceFoundation):		 	0	

### Steps to Reproduce

Create a new MAUI App using .NET 6 LTS
Pair VS with MacOS
Enable Automatic Provisioning and select a development team
Build and Deploy to iPhone

### Link to public reproduction project repository

n/a

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by hector2d2** [comment]
i have the same problem, incluse with xamarin forms, but in xamarin forms,  i solve this problem modify the file "IOS.csproj", with:
`<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhone' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\iPhone\Debug</OutputPath>
    <DefineConstants>DEBUG</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <MtouchArch>ARM64</MtouchArch>
    <CodesignKey>iPhone Developer</CodesignKey>
    <MtouchDebug>true</MtouchDebug>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <MtouchLink>None</MtouchLink>
    <MtouchInterpreter>-all</MtouchInterpreter>
  </PropertyGroup>`
i copy this propertygruop and paste in maui file with a little modifications in the condition, but not work. this problem is from credentials of mac maybe? i only can run my project maui in simulator iphone :c

**Comment by Mephisztoe** [comment]
Okay. It seems as if Xcode 14 is the root source of the issue here. There is some discussion going on at the Xamarin.Forms end that points towards a solution that included downgrading the command line tools of Xcode to version 13.4. This thread has some details: https://stackoverflow.com/questions/73705792/error-being-thrown-when-trying-to-debug-from-jetbrains-rider-error-he0004-coul

Because I am not a native MacOS user, I am having a hard time when it comes to understanding how installating, setting up copying and renaming applications on a Mac. Starting with missing file explorers. MacOS feels limited in its user experience in many ways for me. However, I guess I will be able to find out how this works and I am going to give the solution from above a try.

**Comment by Mephisztoe** [comment]
Alright. I got it to work again.

My assumption is that you experience the above issue after upgrading Xcode from 13.x to 14.

Here is how to get everything up and running again (credits go to [M31k](https://stackoverflow.com/users/19993143/m31k)):

1. On your Mac, go to https://developer.apple.com/download/all/?q=command%20line%20tools
2. Download Command Line Tools for Xcode 13.4
3. From the Download Page: Find and download Xcode 13.4.1
4. Open your Download Folder within the Finder
5. Doubleclick Xcode 13.4.1 xif-file to extract it within your Download Folder
6. Rename the resulting App-file from Xcode to something like Xcode 13
7. Drag and drop Xcode 13 to your Programs folder
8. Double click the Command Line Tools file downloaded earlier 
9. Follow installation instructions
10. Open your default Xcode (still version 14)
11. Go to Preferences > Location > Command Line Tools and select Version 13.4.1
12. Notice its path being something like "Application/Xcode 13"
13. Close Xcode and better restart your Mac... for safetly reasons, lol
14. If open: Restart Visual Studio on Windows and reconnect to your Mac

In my case, building and deploying on my physical iPhone now works again!

You may want to downgrade your Xcode to Version 13.3 even. 
My Visual Studio still claims that the installed Xcode Version (now 13.4) is not that compatible,... however, I didn't notice any further issues yet.

One more hint:
At some point Visual Studio and MAUI will support Xcode 14 as well and you might want to remember to switch your Mac back to using Xcode 14 then.
