### ISSUE TITLE
[Android] Images aren't reloading correctly in CollectionView

### ISSUE THREAD

**Issue by dg2k** [dotnet/maui#10435]
I suspect my issue is as described in #6783.
I am on Maui 6.0.540 (Visual Studio 17.4.0 Preview 2.1).

Does it mean that what was described in Issue #6783 and closed as resolved, should be **fixed** in 6.0.540?
I understand Issue #6783 is linked to milestone 6.0.300 which I assume this is the version in which it was fixed??

I want to be clear before I report as a recurring bug in 6.0.540, so appreciate if someone can comment on this.

**Comment by Symbai** [comment]
Describe what you mean with "arent loading correctly". The linked issue is about reloading when all models and properties including images are the SAME, i.e. when nothing in your collectionview has changed.

If that is not the case in your situation it could be a caching issue.

**Comment by dg2k** [comment]
I have a CollectionView binding to 10 ObservableCollection items in ViewModel.

Only one item has an icon image bound to an Image element (under DataTemplate) with Image's own Source property. The binding is to PNG image file name (string), and the image is located under Resources\Images. It means those without an icon have their filename as null. Everything works great, Except...

...in  the course of viewing the displayed items (scrolling, tapping selecting, changing name, etc), sometimes, the only one icon image is shown for another list item.

In contr, this never happens under WinUI and even tested thoroughly with touch gestures as for Android device.

It is as if the binding goes haywire and duplicates the icon image and pass on to another list item. There are other text based binding properties and they all work as expected. I think the issue is confined to image, and as you point out, things such as caching may impact but hard for me to visualize as I don't know the inner workings as well as performance constraints of CollectionView with regard to Android.
