### ISSUE TITLE
Incorrect instruction how to get version in bug report

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#10447]
### Description

In this bug report, there is this section:

![image](https://user-images.githubusercontent.com/3163293/193439616-70175620-e0f0-4d0e-8cff-44b0413ff377.png)

I do not think `dotnet --version` is the right command.

### Steps to Reproduce

1. Go to https://github.com/dotnet/maui/issues/new?assignees=&labels=t%2Fbug&template=bug-report.yml
2. Scroll down to **Last version that worked well**
3. Run `dotnet --version` on your computer.
4. I'm pretty sure you will not find releases like `6.0.486`. Compare with this: https://github.com/dotnet/sdk/releases

### Link to public reproduction project repository

https://github.com/dotnet/maui/issues/new?assignees=&labels=t%2Fbug&template=bug-report.yml

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All of them

### Did you find any workaround?

Is it the workload version that is being asked for? Then command should be `dotnet workload list`.

**Comment by mattleibow** [comment]
Thanks for sharing! I have fixed this in the template.
