### ISSUE TITLE
A DateTime.ToString with CultureInfo("nb-NO") gives the wrong datetime string output on iOS

### ISSUE THREAD

**Issue by sith-ikjetil** [dotnet/maui#10441]
### Description

If you compile a .NET MAUI project for iOS, you get the wrong datetime format string for Norwegian output.
If you compile a .NET MAUI project for Windows or Android, you get the correct datetime format string for Norwegian output.

I use dotnet --version 6.0.401

### Steps to Reproduce

1. Create a new .NET MAUI APP and compile for iOS.
2. Anywhere like in 'MauiProgram.cs' do something like:
3. var dt = DateTime.Now.ToString( new CultureInfo("nb-NO"));
4. dt will look like: 10/1/2022 4:00:28 PM
5. dt should look like: 01.10.2022 16:00:286

### Link to public reproduction project repository

https://github.com/sith-ikjetil/maui-cultureinfo-no-bug

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

**Comment by drasticactions** [comment]
I doubt this is an issue specific with MAUI (The UI Framework) and (probably) more to do with either the runtime or SDK.

@rolfbjarne @dalexsoto Does that sound correct?

**Comment by sith-ikjetil** [comment]
CurrentUICulture: Name: nb-US NativeName: 'nb (US)' DisplayName: 'nb (US)' EnglishName: 'nb (US)'
CurrentCulture: Name: nb-US NativeName: 'nb (US)' DisplayName: 'nb (US)' EnglishName: 'nb (US)'

@rolfbjarne This is what i got.

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-macios#16217
