### ISSUE TITLE
System.NullReferenceException in ShellToolbarTracker.cs:58

### ISSUE THREAD

**Issue by innomarcoItalia** [dotnet/maui#10442]
### Description

This issue #9090 is closed, it should be fixed in Build 6.0.525 with #9933.
In the latest version of maui 6.0536 
![Maui](https://user-images.githubusercontent.com/20582079/193417059-3c8a3c77-1a6b-4fff-9405-7a6817276af4.png)

we have the same problem because not all states of the app have been checked:

1) app closed tap on notification -> ok
2) app background tap on notification -> ok
3) app foreground  tap on notification -> System.NullReferenceException in ShellToolbarTracker.cs:58

The third state is the tap on the notification as shown in the photo:
![Immagine](https://user-images.githubusercontent.com/20582079/193416466-49e813e1-d740-47aa-8cc3-06cf7d3afccf.png)

It is also possible to see the issue in the video at 38:16
https://www.youtube.com/watch?v=gBbbctEvbOk

### Steps to Reproduce

1) clone repository
2) configure for your Firebase
3) run app
4) send push
5) tap notification

### Link to public reproduction project repository

https://github.com/mistrypragnesh40/PushNotificationDemoMAUI

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 - Android 12

**Comment by innomarcoItalia** [comment]
ShellToolbarTracker.cs:581

**Comment by jsuarezruiz** [comment]
Could you share the stackstrace?. Thanks.

**Comment by innomarcoItalia** [comment]
0xFFFFFFFFFFFFFFFF in Android.Runtime.JNIEnv.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12,5	C#
 	0x1E in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:122,26	C#
 	0x13 in Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnToolbarPropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarTracker.cs:581,4	C#
 	0x3F in Microsoft.Maui.Controls.Toolbar.SetProperty<System.Collections.Generic.IEnumerable<Microsoft.Maui.Controls.ToolbarItem>> at D:\a\_work\1\s\src\Controls\src\Core\Toolbar.cs:74,4	C#
 	0xD in Microsoft.Maui.Controls.Toolbar.set_ToolbarItems at D:\a\_work\1\s\src\Controls\src\Core\Toolbar.cs:34,79	C#
 	0xB7 in Microsoft.Maui.Controls.ShellToolbar.ApplyChanges at D:\a\_work\1\s\src\Controls\src\Core\ShellToolbar.cs:84,4	C#
 	0x1 in Microsoft.Maui.Controls.ShellToolbar.<.ctor>b__8_2 at D:\a\_work\1\s\src\Controls\src\Core\ShellToolbar.cs:44,39	C#
 	0x24 in Microsoft.Maui.Controls.Element.OnHandlerChangedCore at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:33,4	C#
 	0x1 in Microsoft.Maui.Controls.VisualElement.OnHandlerChangedCore at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:42,4	C#
 	0x6B in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:66,5	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:20,11	C#
 	0x18 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:301,5	C#
 	0xB0 in Microsoft.Maui.Platform.ElementExtensions.ToHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:96,4	C#
 	0x2 in Microsoft.Maui.Platform.ElementExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:127,4	C#
 	0x5F in Microsoft.Maui.Platform.ContainerView.SetView at D:\a\_work\1\s\src\Core\src\Platform\Android\ContainerView.cs:72,5	C#
 	0x3 in Microsoft.Maui.Platform.ContainerView.set_CurrentView at D:\a\_work\1\s\src\Core\src\Platform\Android\ContainerView.cs:51,11	C#
 	0x8 in Microsoft.Maui.Platform.ElementExtensions.ToContainerView at D:\a\_work\1\s\src\Core\src\Platform\Android\ElementExtensions.cs:11,4	C#
 	0x15 in Microsoft.Maui.Platform.NavigationRootManager.Connect at D:\a\_work\1\s\src\Core\src\Platform\Android\Navigation\NavigationRootManager.cs:51,4	C#
 	0x26 in Microsoft.Maui.Handlers.WindowHandler.CreateRootViewFromContent at D:\a\_work\1\s\src\Core\src\Handlers\Window\WindowHandler.Android.cs:38,4	C#
 	0x15 in Microsoft.Maui.Handlers.WindowHandler.MapContent at D:\a\_work\1\s\src\Core\src\Handlers\Window\WindowHandler.Android.cs:16,4	C#
 	0x21 in Microsoft.Maui.PropertyMapper<Microsoft.Maui.IWindow,Microsoft.Maui.Handlers.IWindowHandler>. at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:183,6	C#
 	0x18 in Microsoft.Maui.PropertyMapper.UpdatePropertyCore at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:47,4	C#
 	0x1D in Microsoft.Maui.PropertyMapper.UpdateProperties at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:82,5	C#
 	0xCB in Microsoft.Maui.Handlers.ElementHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:74,4	C#
 	0x65 in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:64,6	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:20,11	C#
 	0xA2 in Microsoft.Maui.Platform.ElementExtensions.SetHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:156,4	C#
 	0x3 in Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:166,4	C#
 	0x79 in Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow at D:\a\_work\1\s\src\Core\src\Platform\Android\ApplicationExtensions.cs:46,4	C#
 	0x54 in Microsoft.Maui.MauiAppCompatActivity.OnCreate at D:\a\_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.cs:32,4	C#
>	0x3 in SicurezzaInCasentino.MainActivity.OnCreate at C:\VS2022\TestMaui\Notifiche\App_Utente\SicurezzaInCasentino\Platforms\Android\MainActivity.cs:24,13	C#
 	0x11 in Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.App.Activity.cs:2781,4	C#
 	0x9 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:121,5	C#

**Comment by innomarcoItalia** [comment]
@PureWeen  
It is not the duplicate of # 9090.
the # 9090 solves cases 1 and 2
1) app closed tap on notification
2) app background tap on notification

WHILE THE CASE HAS NOT BEEN SOLVED:
3) App foreground tap on notification as shown in the photo in the post

**Comment by PureWeen** [comment]
> 0x13 in Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnToolbarPropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarTracker.cs:581,4	C#

Your crash is on the same line that was fixed
https://github.com/dotnet/maui/pull/9933/files#diff-b64fef5882e466ad5a3ec3508cc2a23f6c2057aeaee111692f08218ac2acea05R581

Once RC2 comes out if you're seeing the same crash let me know

**Comment by innomarcoItalia** [comment]
ok
thank you

**Comment by innomarcoItalia** [comment]
I confirm the rc2 version the problem has been solved System.NullReferenceException in ShellToolbarTracker.cs: 581 (#9090), but we have another crash next  #10776
