### ISSUE TITLE
'dotnet tool restore' for maui repo fails on macOS

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [dotnet/maui#10443]
### Description

Following the [MAUI Development Guide](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md), I get the folling output for the `dotnet tool restore` step:

> dotnet tool restore
> /var/folders/2_/b4md0kx56ss9ffwn_qf17c5w0000gn/T/q5juhwll.f0x/restore.csproj : error NU1101: Unable to find package microsoft.dotnet.xharness.cli. No packages exist with this id in source(s): /usr/local/share/dotnet/library-packs, nuget.org
> 
> Package "microsoft.dotnet.xharness.cli" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
>    at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
>    at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
>    at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
> 
> Tool 'cake.tool' (version '1.2.0') was restored. Available commands: dotnet-cake
> Tool 'powershell' (version '7.2.1') was restored. Available commands: pwsh
> Tool 'api-tools' (version '1.3.3') was restored. Available commands: api-tools
> 
> Restore partially failed.

### Steps to Reproduce

1. Install :NET 6 SDK, Powershell, XCode
2. `cd $(MAUI_REPO)`
3. `dotnet tool restore`

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS Monterey

### Did you find any workaround?

No

### Relevant log output

```shell
See description
```

**Comment by xleon** [comment]
I had a similar error today. 
Fixed by running `sudo dotnet workload restore`

**Comment by jfversluis** [comment]
@xleon thanks! I doubt that would work though... Are we talking about the same thing?

@ChristophSchmidpeter looking at the output it doesn't seem to pick up on the NuGet feed sources in the nuget.config file. Could you see why maybe that is? And/or add `--source {url}` (you can do this multiple times for multiple sources) for each of the sources in the nuget.config file manually and see if that helps?

**Comment by miadey** [comment]
Have a try with :
Go to System Preference, Security and Privacy, Full Disk Access and give access to terminal and Visual Studio.
Lot of my problems restoring  have been solved with this

**Comment by 64J0** [comment]
Having a similar problem. When trying to restore packages for the Saturn project it fails, only in MacOS:

* https://github.com/64J0/Saturn/actions/runs/3300248411/jobs/5444532815

**Comment by mattleibow** [comment]
I wonder if the `dotnet tool restore` command is not using the nuget.config? I don't see the various nuget feeds in the OP error message...

Can you double check your working directory has a nuget.config in it?
