### ISSUE TITLE
Development Guide not clear on required XCode Version

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [dotnet/maui#10444]
### Description

The [MAUI Development Guide](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md) states
> iOS and MacCatalyst will require Xcode 13.3 Stable
This, however, leaves unclear, whether the version 13.3 or higher, or the exact version 13.3 is required.
Which one is the case? To make the Guide clearer, the sentence should be adapted

### Steps to Reproduce

N/A

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS

### Did you find any workaround?

N/A

### Relevant log output

```shell
N/A
```

**Comment by drasticactions** [comment]
It's 13.3 and versions are included within 13.3. It does not support 13.4+. If it said "higher" it would have referenced it.
