### ISSUE TITLE
[Win][Mac] Secondary ButtonMask odd behaviour

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#10464]
### Description

The [Secondary ButtonMask](https://github.com/dotnet/maui/pull/9589) PR tells us that the feature works on Windows. But I'm not having much joy with it. Bear in mind that I know that secondary won't work with "NumberOfTapsRequired".

I setup 3 Labels triggered by a single tap. Label 1 is defined to be triggered by primary. Label 2 is defined to be triggered by secondary. Label 3 is defined to be triggered by either.

Then I added three more labels. Label 4 is defined to be triggered by primary single tap. Label 5 is defined to be triggered by secondary double tap. Label 6 is defined to be triggered by either triple tap. 

#### Win results

Label 1 is triggered by primary and secondary, Label 2 and 3 work as expected.

Label 4 is triggered by a single tap (albeit in primary or secondary). Label 5 isn't triggered by any double tap (known issue). Label 6 is never triggered at all.

### Mac Catalyst results

Label 1-5 work as expected. Label 6 (triple tap with either primary or secondary) - triple tap working for primary, but secondary only requires a single tap.

### Steps to Reproduce

Run the repro case.

### Link to public reproduction project repository

https://github.com/davidbritch/dotnet-maui-issues/tree/main/TapDemo

### Version with bug

.NET 7 RC1.

### Last version that worked well

Unknown/Other

### Affected platforms

Windows and Mac Catalyst

### Affected platform versions

N/A

### Did you find any workaround?

No.

### Relevant log output

N/A.

**Comment by davidortinau** [comment]
@davidbritch looking at your code everything currently says `Buttons="Primary"`fyi

**Comment by davidbritch** [comment]
Grrrrrrr. Fixed, and updating the bug description.

**Comment by PureWeen** [comment]
@davidbritch though some of this might be a little confusing it currently is intentional.  I would say the main bug here is that we should make scenarios like this currently not work on catalyst

```XAML
<TapGestureRecognizer Buttons="Secondary"
                                          NumberOfTapsRequired="2"
                                          Tapped="On2SecondaryTapped" />
```

If someone wants to enable primary and secondary taps for a label then they would need to add multiple gestures like so

```XAML
<Label.GestureRecognizers>
                    <TapGestureRecognizer Buttons="Primary"
                                          NumberOfTapsRequired="3"
                                          Tapped="On3EitherTapped" />
                    <TapGestureRecognizer Buttons="Secondary"
                                          Tapped="On3EitherTapped" />
                </Label.GestureRecognizers>
```

Triple tap also currently doesn't work on windows because there's not a platform way that surfaces out "triple tap". With windows we use the "Tapped" and "DoubleTapped" events specifically, so I think we'd have to fake anything more than that. 

I think this is a good bug to keep around to track other users that hit this.

**Comment by davidbritch** [comment]
@PureWeen So, given this code that sets a primary tap:

```xaml
            <Label Text="Tap with primary"
                   FontSize="18"
                   HorizontalOptions="Center">
                <Label.GestureRecognizers>
                    <TapGestureRecognizer Buttons="Primary"
                                          Tapped="OnPrimaryTapped" />
                </Label.GestureRecognizers>
            </Label>
```

It's not a bug that a tap can be triggered with primary or secondary on Windows?

Also, why would enabling primary and secondary taps on a label require two gesture recognisers? Given the code:

```xaml
            <Label Text="Tap with either"
                   FontSize="18"
                   HorizontalOptions="Center">
                <Label.GestureRecognizers>
                    <TapGestureRecognizer Buttons="Primary,Secondary"
                                          Tapped="OnEitherTapped" />
                </Label.GestureRecognizers>
            </Label>
```

The `Buttons` property is set correctly (as if done in C# with `Buttons = ButtonsMask.Primary | ButtonsMask.Secondary`):

![Capture](https://user-images.githubusercontent.com/8092460/194553418-f811935b-6532-4ce1-8b7f-0f377f039198.PNG)

**Comment by PureWeen** [comment]
> ```
>             <Label Text="Tap with primary"
>                    FontSize="18"
>                    HorizontalOptions="Center">
>                 <Label.GestureRecognizers>
>                     <TapGestureRecognizer Buttons="Primary"
>                                           Tapped="OnPrimaryTapped" />
>                 </Label.GestureRecognizers>
>             </Label>
> ```

It is a bug :-/ Fixing that now on that PR



> Also, why would enabling primary and secondary taps on a label require two gesture recognisers? Given the code:

It doesn't if you are ok with the same number of taps. My main point was that if you have

```XAML

<Label.GestureRecognizers>
                    <TapGestureRecognizer Buttons="Primary, Secondary"
                                          NumberOfTapsRequired="2"
                                          Tapped="On3EitherTapped" />
                </Label.GestureRecognizers>
                
````

You should only get `Primary` events. 

If you want a label that reacts to a double primary tap and a single secondary tap then you'll need two GestureRecognizers.
