### ISSUE TITLE
Flyout is not refreshing when item visibility is changed

### ISSUE THREAD

**Issue by gktval** [dotnet/maui#10468]
### Description

When changing the visibility of menu items in the Shell's Flyout, the flyout view is not updating. I have tried it in various ways, such as changing the FlyoutItemIsVisible property, the IsVisible property, and different views. 

### Steps to Reproduce

In the attached repository, there are two header items in the flyout:

1) The first header item sets the visibility of the sub item with resources. The sub item will disappear from the flyout on visibility set to false, but the item will not reappear in the flyout when visibility is set to true.

2) The second header should show the sub item when FlyoutItemIsVisible = true, but the results show that the flyout is not being updated, even with ForceLayout and InvalidateMeasure.

### Link to public reproduction project repository

https://github.com/gktval/MauiAppShellFlyout

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

### Relevant log output

```shell
none
```

**Comment by spadapet** [comment]
For me, now not only is the Flyout not refreshing, but my app crashes when a Flyout changes visibility. It's either a null exception or an index out of range exception when MAUI tries to update the visible Flyouts.

I just bind the visibility to some bool value to hit the bug:

![image](https://user-images.githubusercontent.com/2523431/224183677-7627b1e6-c19a-458e-ad51-861c4af8eab6.png)

Now I have to redesign my whole app to always have a static list of flyouts :(

**Comment by jinxinjuan** [comment]
We cannot access the repo https://github.com/gktval/MauiAppShellFlyout

Result: Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0 using another [maui-samples/7.0/Navigation/ShellFlyoutSample at main · dotnet/maui-samples · GitHub](https://github.com/dotnet/maui-samples/tree/main/7.0/Navigation/ShellFlyoutSample) repo. Can repro on android platform, seems not repro on macOS (MyMac). Not sure if it is correct result, if not, please help correct me.

**Comment by gktval** [comment]
Sorry about that. It is changed to public now.

**Comment by spadapet** [comment]
@BretJohnson, here are two test apps for hitting two different exceptions when flyouts change visibility:

* [TestAppThatHitsNullReference.zip](https://github.com/dotnet/maui/files/12381764/TestAppThatHitsNullReference.zip)
* [TestAppThatHitsArgumentOutOfRange.zip](https://github.com/dotnet/maui/files/12381766/TestAppThatHitsArgumentOutOfRange.zip)

The only difference in the two projects is the default value of `ViewModel.ShowStuff`

REPRO:
* Open either solution
* F5 to build and run on Windows
* Click the one button that appears in the running app UI

RESULT:
One of two exceptions, depending on which project was opened. You can change the reference to MAUI controls to a locally built package folder in order to debug

**Comment by BretJohnson** [comment]
@spadapet - I split out the WinUI crashes to a separate bug, here: https://github.com/dotnet/maui/issues/16929

**Comment by PureWeen** [comment]
Keeping this issue open for now

It looks like the visibility of the SubItem 2 is fixed but the visibility on the first "sub item" still doesn't return after being set back to visible. 

### Reproduction
- Run attached repro
- click "Header Item" => sub item disappears
- click "Header Item" => sub item should now re-appear

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/16991
