### ISSUE TITLE
Operation is not supported on this platform. when using HttpClient.send on ios and android

### ISSUE THREAD

**Issue by JPfahl** [dotnet/maui#10470]
### Description

Why I try to call a service from ios or android I get a System.PlatformNotSupportedException.  The code works perfectly in windows.  even if I try to hit something like http://goole.ca I get the same error.

### Steps to Reproduce

A added the following code to your default sample and get the error:

```C#
public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		MainPage = new AppShell();

		try
		{
            HttpClient client = new HttpClient();
            HttpResponseMessage response = client.Send(new HttpRequestMessage(HttpMethod.Get, "http://goole.ca"));
            System.Diagnostics.Debug.WriteLine(response.StatusCode.ToString());
        }
		catch (Exception ex) 
		{
			System.Diagnostics.Debug.WriteLine(ex.Message);
		}
    }
}
```

I am using VS 17.4 Preview 2.1 (6.0.540) does not appear in the list below.

### Link to public reproduction project repository

none

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15.5, android api33

**Comment by campersau** [comment]
Looks like the synchronus `Send` is not supported on mobile platforms.
Unfortunately the `UnsupportedOSPlatform` attributes are still commented out:

https://github.com/dotnet/runtime/blob/1281a4a3393e9293aa4b379d619a692d6dcb62a4/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.AnyMobile.cs#L702-L714

because of https://github.com/dotnet/arcade/issues/7585

**Comment by JPfahl** [comment]
This works fine in xamarin why stop supporting it?  with sendasync I still can't access my local network. I get the following error: The Internet connection appears to be offline.

**Comment by JPfahl** [comment]
A added the following code to your default sample and get the error in ios it works in windows and android:
note: add android:usesCleartextTraffic="true" to adroidmanifest.xml.

public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		MainPage = new AppShell();

            HttpClient client = new HttpClient();
            client.SendAsync(
				new HttpRequestMessage(HttpMethod.Get,
#if ANDROID
                "http://10.0.2.2/servicedev/people")).ContinueWith(task =>
#else
                "http://192.168.50.163/servicedev/people")).ContinueWith(task =>
#endif
                {
                    try
                    {
                        System.Diagnostics.Debug.WriteLine(task.Result.StatusCode.ToString());
                    }
                    catch (Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine(ex.Message);
                    }
                });
    }
}

**Comment by PureWeen** [comment]
@JPfahl can you include a full stack trace?

**Comment by JPfahl** [comment]
Call Stack:

[0:] [2022-10-05 13:01:27.15] Executing Load(MauiDev.ViewModels.MainPageViewModel)
[0:] [2022-10-05 13:01:27.17] NetworkAccess Internet
[0:] [2022-10-05 13:01:27.18] GET People?ModelName=Person 1 
Thread started:  #15
[0:] [2022-10-05 13:01:27.27] GET http://192.168.50.163/ServiceDev/People?ModelName=Person 1 Exception=System.Net.Http.HttpRequestException
AllowRetry=NoRetry
TargetSite=Void Throw()
Message=The Internet connection appears to be offline.
Source=System.Private.CoreLib
HResult=-2146233088
StackTrace=   at System.Net.Http.NSUrlSessionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Computronix.Mvvm.Services.NetworkService.SendRequestAsync(HttpRequestMessage request, String requestId, Int32 timeout) in C:\Dev\Git\Computronix.Mvvm\Computronix.Mvvm\Services\NetworkService.cs:line 1148
Inner Exception=Foundation.NSErrorException
Error=The Internet connection appears to be offline.
Domain=NSURLErrorDomain
Code=-1009
UserInfo={
    NSErrorFailingURLKey = "http://192.168.50.163/ServiceDev/People?ModelName=Person";
    NSErrorFailingURLStringKey = "http://192.168.50.163/ServiceDev/People?ModelName=Person";
    NSLocalizedDescription = "The Internet connection appears to be offline.";
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1009 \"(null)\" UserInfo={_NSURLErrorNWPathKey=unsatisfied (Local network prohibited), interface: en0, ipv4, _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}";
    "_NSURLErrorFailingURLSessionTaskErrorKey" = "LocalDataTask <36C71637-90D8-4409-80F8-58880A363820>.<1>";
    "_NSURLErrorRelatedURLSessionTaskErrorKey" =     (
        "LocalDataTask <36C71637-90D8-4409-80F8-58880A363820>.<1>"
    );
    "_kCFStreamErrorCodeKey" = 50;
    "_kCFStreamErrorDomainKey" = 1;
}
Message=Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x2828d4870 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorNWPathKey=unsatisfied (Local network prohibited), interface: en0, ipv4, _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <36C71637-90D8-4409-80F8-58880A363820>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <36C71637-90D8-4409-80F8-58880A363820>.<1>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=http://192.168.50.163/ServiceDev/People?ModelName=Person, NSErrorFailingURLKey=http://192.168.50.163/ServiceDev/People?ModelName=Person, _kCFStreamErrorDomainKey=1}
HResult=-2146233088

[0:] [2022-10-05 13:01:27.27] GET http://192.168.50.163/ServiceDev/People?ModelName=Person 1 BadRequest

**Comment by hartez** [comment]
@JPfahl  Does this work if you use "https://" instead of "http://"?

**Comment by JPfahl** [comment]
I don't have a certificate for my local iis

**Comment by jfversluis** [comment]
As mentioned earlier, this is simply not supported. If you want to learn more details about the why and how you'll have to contact the runtime team. This is not something that originates in .NET MAUI.

**Comment by JPfahl** [comment]
VS Preview 3 fixed the problem
