### ISSUE TITLE
[MacCatalyst] CollectionView is not rendering

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#10479]
### Description

CollectionView is not rendering on Catalyst.

Android
<img width="464" alt="Captura de Pantalla 2022-10-04 a las 10 52 45" src="https://user-images.githubusercontent.com/6755973/193780380-bf2adb9b-7523-46d1-a5f4-6592b2451615.png">

Catalyst
<img width="511" alt="Captura de Pantalla 2022-10-04 a las 11 02 12" src="https://user-images.githubusercontent.com/6755973/193780357-9f6618c0-b26f-4670-b765-e7d2745a799d.png">

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-surfing-app-challenge
2. Launch the App on macOS.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-surfing-app-challenge

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio for Mac 17.5.7 (build 1). Can repro with sample project.
[netmaui-surfing-app-challenge](https://github.com/jsuarezruiz/netmaui-surfing-app-challenge)
![image](https://github.com/dotnet/maui/assets/37974803/11b34b3b-954a-4739-873d-cdd2cf115557)

**Comment by jfversluis** [comment]
I believe this is fixed in more recent versions.
