### ISSUE TITLE
[MacCatalyst] Images are not loading

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#10475]
### Description

Local images are not loading on Catalyst.

![issue-scroll-catalyst](https://user-images.githubusercontent.com/6755973/193773026-d292f2f7-af07-412c-92c2-470aca65bf21.gif)

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-coupons-app-challenge
2. Launch the App.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-coupons-app-challenge

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey

**Comment by hector2d2** [comment]
hi, change the name of the image. in the object coupon to the exactly name of files. like Pizza.png to pizza.png
```
 new Coupon
                {
                    Id = 1,
                    Title = "McDonald's french",
                    Discount= -5.00,
                    CompanyLogo = "McDonalds.png",
                    Image = "Chips.png",
                    Color =  Color.FromArgb("#FF4AA596")
                },
to 
 new Coupon
                {
                    Id = 1,
                    Title = "McDonald's french",
                    Discount= -5.00,
                    CompanyLogo = "mcdonalds.png",
                    Image = "chips.png",
                    Color =  Color.FromArgb("#FF4AA596")
                },

```
<img width="657" alt="Captura de Pantalla 2022-10-04 a la(s) 14 59 12" src="https://user-images.githubusercontent.com/50940057/193914099-7470ed6e-38bd-416a-9e70-bdb5b873f336.png">

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio for Mac 17.5.7 (build 1). Can repro with sample project. [netmaui-coupons-app-challenge](https://github.com/jsuarezruiz/netmaui-coupons-app-challenge)
![image](https://github.com/dotnet/maui/assets/37974803/75320b28-c4fa-47f6-b46b-fecbcd9409cd)

**Comment by jfversluis** [comment]
I think this is a non-issue. Seems to be a mismatch in in filename casing.
