### ISSUE TITLE
[MacCatalyst] Scroll not working in ScrollView

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#10474]
### Description

The scroll is not working in ScrollView on Catalyst, cannot scroll.

![issue-scroll-catalyst](https://user-images.githubusercontent.com/6755973/193772576-c6cd4c6a-7c02-49f4-bbfa-efc9e68a8bfa.gif)

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-coupons-app-challenge
2. Try to scroll

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-coupons-app-challenge

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey

**Comment by hector2d2** [comment]
hi, In macos, i write in the first grid the row definitions two specific the heigth of the controllers like this:
`<Grid >
        <Grid.RowDefinitions>
                    <RowDefinition Height="*"/> 
                    <RowDefinition Height="40"/>
                </Grid.RowDefinitions>
        <ScrollView 
            BackgroundColor="{StaticResource BackgroundColor}">`
and in the tabview write:
`<controls:TabView Grid.Row="1"/>`
And then the scroll works

**Comment by hartez** [comment]
The scrolling works fine if I remove the TabView at the bottom.

**Comment by hartez** [comment]
The TabView is covering the entire page, preventing any input from getting to the ScrollView. This is a custom control implementation issue, not a ScrollView bug.
