### ISSUE TITLE
[MacCatalyst] Image not respecting parent size

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#10481]
### Description

An Image is rendered with the full image size and not respecting the parent width and height.

<img width="513" alt="Captura de Pantalla 2022-10-04 a las 11 18 05" src="https://user-images.githubusercontent.com/6755973/193783605-f4d264a5-5e3d-4d8f-9707-14a7278cfeef.png">

On Android:
![Uploading Captura de Pantalla 2022-10-04 a las 11.22.02.png…]()

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-chat-app-challenge
2. Launch the App on macOS.
3. Tap any chat conversation to navigate to the detail.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-chat-app-challenge

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS Monterey

**Comment by rachelkang** [comment]
https://github.com/dotnet/maui/issues/9734 potentially related

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio for Mac 17.5.7 (build 1). Can repro with sample project.
[netmaui-chat-app-challenge](https://github.com/jsuarezruiz/netmaui-chat-app-challenge)
![image](https://github.com/dotnet/maui/assets/37974803/77b33c67-9ec5-4959-9c07-a910660ee24c)

**Comment by faruknane** [comment]
This happened me twice today, how can we fix this?
