### ISSUE TITLE
[MacCatalyst] SearchBar background color is not working

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#10482]
### Description

SearchBar background color is not working on macOS.

<img width="511" alt="Captura de Pantalla 2022-10-04 a las 11 34 02" src="https://user-images.githubusercontent.com/6755973/193787371-48d8957c-74de-4e0f-9c6e-ecef2fd1a093.png">

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-travel-app-challenge
2. Launch the App on macOS.
3. The search is rendered like a black box.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-travel-app-challenge

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey

**Comment by rmarinho** [comment]
Fixed by #10615
