### ISSUE TITLE
MediaPicker.CapturePhotoAsync crash on the Kyocera C6930

### ISSUE THREAD

**Issue by scottteague** [dotnet/maui#10508]
### Description

Normally upon calling MediaPicker.CapturePhotoAsync the camera pops up and allows the user to take a photo. However, on a Kyocera C6930 with the default camera settings the app crashes about 7/10 times right after taking a picture. There usually seems to be a pause or stutter when the crash happens.  The linked solution works on all tested devices except for the Kyocera C6930. 

A strange behavior worth noting is that the frequency of crashing goes down if I set the resolution to be the lowest amount and the "Auto HDR"/"Auto Night Detection" settings to off.  I don't know if there is a different method I could use to try taking photos which might get us around this issue.

I am including a very simple app which just takes a picture and displays it. It should work fine on most things, but crashes almost every time a picture is taken on a Kyocera C6930.
The device log was too long to submit. I can include certain lines if you tell me what to look for. 

### Steps to Reproduce

1. Use a Kyocera C6930
2. Create a new .NET MAUI App (or use included reproduction app)
3. Make sure the camera settings are the default settings
4. Call MediaPicker.CapturePhotoAsync(new MediaPickerOptions { Title = "Take the shot" }) // passing in null behaves the same here

### Link to public reproduction project repository

https://github.com/scottteague/photo1

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

6.0.486/6.0.400 (All the way back to Xamarin)

### Did you find any workaround?

Not a complete workaround: When the photo resolution is set to medium and the "Auto HDR"/"Auto Night Detection" settings are turned off it crashes slightly less often.

I'd love to try a different workaround if you know of one.

### Relevant log output

```shell
*The device log is far too long to include here, I have put it into the example repository 
```

**Comment by scottteague** [comment]
I have made a commit which has the device logs since they are so large that they could not be added to the issue via the web page.

**Comment by scottteague** [comment]
If anyone is ever looking at this in the future I tried doing this in a way that seems "Lower Level" in my real project by Doing the following. It also failed (without any exception I could see) so maybe there could be something even lower level causing the issue?

I added:
```
		<provider android:name="androidx.core.content.FileProvider"
          android:authorities="${applicationId}.fileprovider"
          android:exported="false"
          android:grantUriPermissions="true">

			<meta-data android:name="android.support.FILE_PROVIDER_PATHS"
						   android:resource="@xml/file_paths"></meta-data>
		</provider
```
to my AndroidManifest.xml 
then added a file called file_paths.xml in my resources with the following code:
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
	<external-path name="local" path="." />
</paths>
```

Then I added the following code into my actual code:

```
public string TestTakePhotoADifferentWay(string filename)
        {
            var context = Android.App.Application.Context;
            var activity = Platform.CurrentActivity as MainActivity;
            using (var intent = new Intent(MediaStore.ActionImageCapture))
            {
                var file = new Java.IO.File(filename);
                var uri = FileProvider.GetUriForFile(context, context.ApplicationContext.PackageName + ".fileprovider", file);
                intent.PutExtra(MediaStore.ExtraOutput, uri);
                activity.StartActivityForResult(intent, 0);
                return file.Path;
            }
        }
```

I know that the StartActivityForResult() doesn't get waited on but even not trying to do anything with the photo the app still crashes.

**Comment by scottteague** [comment]
Another strange behavior is that this seems not to happen for a while after a reboot.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on Android platform with sample project.
https://github.com/scottteague/photo1
![image](https://github.com/dotnet/maui/assets/82450723/f9cc36e5-b24b-4184-9683-25ec600c4a75)
