### ISSUE TITLE
Opacity not applied to BoxView and Frame

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#10503]
### Description

The Frame and BoxView elements are not rendered with correct opacity:
![image](https://user-images.githubusercontent.com/114725843/194067367-bbb28f54-3d29-4905-9a1e-c0c1755eff59.png)

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Add a BoxView or Frame to the MainPage with a (arbitrary) background color and an opacity < 1
3. The elements are rendered with an opacity of 1

### Link to public reproduction project repository

https://github.com/owl-guy/OpacitySample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

Wrapping the elements in a Grid with opacity < 1 seems to work, they apparently adapt the grid's value.

**Comment by RonnyRos** [comment]
Initial value on Opacity does not work on Android 12.1

**Comment by matt-goldman** [comment]
I've noticed this same issue too. Although something weird happens - if you change the opacity while the app is running, hot reload will apply it. It just doesn't get set as an initial value.

**Comment by owl-guy** [comment]
@matt-goldman exactly

**Comment by naveedqamar650** [comment]
I am also facing the same issue as opacity value is applied while the app is running but it isn't getting value as the app starts again.
