### ISSUE TITLE
Hot Reload Doesn't work if another control references it

### ISSUE THREAD

**Issue by tylandercasper** [dotnet/maui#10506]
### Description

If a control references another control in XAML, the referenced control will not show changes in hot reload. 

If you change any properties on the referencer they will be reflected in the referenced control. 

Tested on 6.0.0.540. 

### Steps to Reproduce

Repeatable in two lines: 

```
<Label Text="This text won't change in hot reload"
     x:Name="referencedLabel"/>
<Label Text="This control is preventing the other label from changing. (And changes to this will override the other one)" 
     IsVisible="{Binding Source={x:Reference referencedLabel},Path=IsVisible}"/>
```

### Link to public reproduction project repository

https://github.com/tylandercasper/HotReloadBindingBug

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

tested on Windows 10 and Android 33 emulator

### Did you find any workaround?

Remove  the reference while styling the control. 

> VS bug [#1751833](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1751833)

**Comment by PureWeen** [comment]
@drasticactions @StephaneDelcroix  thoughts?

**Comment by hartez** [comment]
If this doesn't work in Hot Reload, I imagine it's also broken in a running app. We should check whether this works when changing the bound value in a running app.

**Comment by drasticactions** [comment]
I need to verify it but I think @hartez is on the right track. This feels like something that would be broken regardless of Hot Reload, it's just that it's easy to see because of Hot Reload.

Having said that, it could be a bit of A and bit of B here. We can check and see.

**Comment by jonathanpeppers** [comment]
@spadapet you might check this one with your work on `x:Name` to see if it solves anything.

**Comment by drasticactions** [comment]
Testing this out again:

- If you change either text field from C# they do change directly and don't stomp each other.
- As far as I can see, having not started to debug XET yet, it seems like the reference binding is causing some kind of additional actions to take place that are binding to the wrong control. 

CC @etvorun

**Comment by drasticactions** [comment]
Removed @spadapet from this, I don't believe the x:name issue is related to this.

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 and Android emulator (13.0-API 33) with below Project:
[MauiApp1.zip](https://github.com/dotnet/maui/files/11595073/MauiApp1.zip)
Please see the screenshot
![image](https://github.com/dotnet/maui/assets/131441429/4bf63f29-e74e-4d5d-9f87-a4601db0eaf7)

**Comment by drasticactions** [comment]
@tylandercasper Checking this against MAUI net8.0 GA, the source info is returning the correct values and XAML Hot Reload should be functioning correctly for this use case.

https://github.com/drasticactions/MauiRepros/tree/main/SourceInfoCheck

I still need to find which commit fixed this, but my assumptions are changes in XamlC may have caused the correct binding to happen to fix the source info? Can you try and validate this against this project and mine?

**Comment by drasticactions** [comment]
Verifying it between net7.0 and net8.0, I believe https://github.com/dotnet/maui/pull/17230 did fix this. It was for a different issue with styles, but it's the exact underlying cause with this one: The source info was wrong. That PR corrected it for styles and also for this.

If you still have issues with this, please file a new issue.
