### ISSUE TITLE
BackbuttonBehavior with custom command throws 'Object reference not set to an instance of an object' exception.

### ISSUE THREAD

**Issue by FM1973** [dotnet/maui#10514]
### Description

When I override the back button behavior using a RelayCommand in a ViewModel an exception is being thrown:
'Object reference not set to an instance of an object'.

I can set a breakpoint at `await Shell.Current.GoToAsync("..");` and after the command has been executed the exception occurs.

### Steps to Reproduce

1. Create a new Maui App
2. Add CommunityToolkit MVVM nuget package
3. Create a Viewmodel for a i.e. details page
4. Create a Contentpage and set the viewmodel as binding context
5. In the viewmodel create a relay command for the back operation (await Shell.Current.GoToAsync("..");)
6. In the contentpage override the backbuttonbehavior and bind the command to the viewmodels "BackCommand"
7. In Mainpage change the button clicked eventhandler to navigate to the details page (Shell.Current.GoToAsync(nameof(DetailsPage));)
8. Register the route for the detailspage
9. Register the details page and viewmodel in mauiprogram (builder.Services.Add...)

The main page will be registered as a singleton, the details page and viewmodel as transient.

Start the app, klick the button to go to the details page. Click the back button... then boom ;)

### Link to public reproduction project repository

https://github.com/FM1973/RepoBackButtonBehavior.git

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

No

### Relevant log output

```shell
Resolved pending breakpoint at 'DetailsViewModel.cs:16,1' to void RepoBackButtonBehavior.Viewmodels.DetailsViewModel.<Back>d__0.MoveNext () [0x0000f].
[Choreographer] Skipped 278 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=4646ms; Flags=0, IntendedVsync=70079283607535, Vsync=70083916940683, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=70083927350700, AnimationStart=70083927366900, PerformTraversalsStart=70083927477000, DrawStart=70083927641400, SyncQueued=70083927789300, SyncStart=70083928224200, IssueDrawCommandsStart=70083928271200, SwapBuffers=70083929047600, FrameCompleted=70083930328700, DequeueBufferDuration=514600, QueueBufferDuration=459500, GpuCompleted=0, 
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'
```

**Comment by affableashish** [comment]
> We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/maui/blob/main/docs/TriageProcess.md).

You can't be pushing every issue to the backlog. Hire more developers and fix them soon Microsoft! 
And don't tell us you don't have budget for that. If you can spend billions of dollars on buying Game Studios, you should be more than capable of providing some extra budget for MAUI bugfixes. You have an opportunity to make your UI platform better than everyone else's so you can use that leverage to get quality apps in your ecosystem and sell your services! 
See this huge potential in MAUI and invest accordingly!

**Comment by EmmaCCC** [comment]
> > We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/maui/blob/main/docs/TriageProcess.md).
> 
> You can't be pushing every issue to the backlog. Hire more developers and fix them soon Microsoft! And don't tell us you don't have budget for that. If you can spend billions of dollars on buying Game Studios, you should be more than capable of providing some extra budget for MAUI bugfixes. You have an opportunity to make your UI platform better than everyone else's so you can use that leverage to get quality apps in your ecosystem and sell your services! See this huge potential in MAUI and invest accordingly!

ha, there is so much bug in maui' issues  every day,so bad!

**Comment by knocte** [comment]
MAUI is an opensource project, it is given to you for free. If you benefit from it, you could also give some back in the form of contributions/bugfixes (pull requests).

**Comment by ClausRogisch** [comment]
In my opinion navigation is quite fundamental and this issue could get a higher priority?
Are there workarounds?
