### ISSUE TITLE
dotnet tool restore on Net7 repo Get error : blocked

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#10519]
### Description

After downloading the Maui Net 7 repo, I ran 'dotnet tool restore'. I got the following error 
👍 'File D:\Dev\GitHub\maui-net7.0\.config\dotnet-tools.json came from another computer and might be blocked to help protect this computer. For more information, including how to unblock, see https://aka.ms/motw'
Is this indicating I shouldnt be attempting to use this repo?

### Steps to Reproduce

1 Download net7 maui repo.
2 Run Cmd, cd to downloaded directory, type 'dotnet tool restore'

### Link to public reproduction project repository

https://github.com/dotnet/maui net7 branch

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

Copy the file from dotnet/maui/.config

**Comment by hartez** [comment]
@davefxy Did you clone the repo using git, or download the source in a zip?

**Comment by davefxy** [comment]
I downloaded the Maui Net 7 repo as a zip

**Comment by Redth** [comment]
Additionally, it sounds like you need to 'unblock' the .zip file before extracting it and trying to use it.

Right click the zip file, go to properties, and on the "general" tab, in the "Security" section, check the "Unblock" checkbox and click OK.

Now you can unzip and run the build script.
