### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Rustyhand3** [dotnet/maui#1051]
### Description

On a Mac installed Visual Studios, Downloaded  HelloMaui

### Steps to Reproduce

1. Created new solution "TestGoogle">> Under Multiplatform, Selected App >> Under Zamarin.Forms, Selected Shell Form App
2. Under Tools >> Android Device Manager  - Created Default Android Emulation:  Pixel_3a_API_30_x86 (1)
3. Next to the Run Button - Selected TestGoogle.Android >> Selected Release >> Selected my Pixel_3a_API_30_x86 (1) Emulator
4. Pressed Play

### Expected Behavior
Visual Studio to launch Android Emulator and deploy my Empty Shell form app. 

### Actual Behavior
Visual Studio launched Android Emulator and fails to deploy Empty shell form app.

## Deployment Errors

/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2143,5): warning MSB3277: Found conflicts between different versions of "Newtonsoft.Json" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2264,2): error MSB6003: The specified task executable "zipalign" could not be run. System.ComponentModel.Win32Exception (0x80004005): ApplicationName='/Users/kevin.hand/Library/Android/sdk/build-tools/30.0.2/zipalign', CommandLine=' -p 4 "/Users/kevin.hand/Projects/TestGoogle/TestGoogle.Android/obj/Release/android/bin/com.companyname.testgoogle.apk" "bin/Release//com.companyname.testgoogle-Signed.apk"', CurrentDirectory='', Native error= Access denied

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2264,2): error MSB6003:   at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/System/System.Diagnostics/Process.cs:778 

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2264,2): error MSB6003:   at System.Diagnostics.Process.Start () [0x0003a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2006 

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2264,2): error MSB6003:   at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2264,2): error MSB6003:   at Microsoft.Build.Utilities.ToolTask.ExecuteTool (System.String pathToTool, System.String responseFileCommands, System.String commandLineCommands) [0x000c9] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Utilities/ToolTask.cs:705 

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2264,2): error MSB6003:   at Microsoft.Build.Utilities.ToolTask.Execute () [0x00432] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Utilities/ToolTask.cs:1514 

### Basic Information

Visual Studio For Mac 8.9.9 (build 3)

Apple Developer Tools
Xcode 12.4 (17801)
Build 12D4e

Xamarin.Mac
Version: 7.10.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:41-0400

Xamarin.iOS
Version: 14.16.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:42-0400

Xamarin Designer
Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

Xamarin.Android
Version: 11.2.2.1 (Visual Studio Community)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/kevin.hand/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 30.0.3

**Comment by avaavg6629** [comment]
- [ ]

**Comment by avaavg6629** [comment]
#- [ ] ~~`**_[![image](https://user-images.githubusercontent.com/84434551/119207454-f0124a00-baa6-11eb-8bf8-e71d4e306103.png)]()_**`~~

**Comment by avaavg6629** [comment]
[[]()]()

**Comment by avaavg6629** [comment]
[]()

**Comment by banditoth** [comment]
> MSB6003: The specified task executable "zipalign" could not be run.

Hello @Rustyhand3 . 
It seems like this error message is because of the IDE, and irrelevant to .NET MAUI.
`Native error= Access denied`

**Comment by AmSmart** [comment]
@Rustyhand3, I believe you need a preview version of Visual Studio if you want to run .NET MAUI apps before it gets to stable.

**Comment by jfversluis** [comment]
There currently is no support for .NET MAUI in Visual Studio for Mac. If you want to run it on iOS have a look at VS Code and/or running from the CLI. James has a great video about how to set things up on Mac [here](https://www.youtube.com/watch?v=eF5YcpyzQIo&t=935s).
