### ISSUE TITLE
Couldn't run the emulator

### ISSUE THREAD

**Issue by mkeshmirian** [dotnet/maui#10527]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

OS: Windows 10
VS: 2022
Installed MAUI and created a MAUI C# project. Didn't change anything. Selected the "net6.0-android" framework and then tried tor run its "Pixel 2 - API 28..." emulator. I got the following error when I tried to run the project:
**Emulator pixel_2_-_api_28 cannot be started.**
No details was provided.

**Comment by hartez** [comment]
Can you launch the emulator directly from the Tools menu? Or does it fail from there as well?

**Comment by mkeshmirian** [comment]
This is what I get when I try to run the emulator directly:

 

Device error: WARNING: unexpected '-prop' value ('monodroid.avdname=pixel_2_-_api_28'), only 'qemu.' properties are supported

WARNING: unexpected '-prop' value ('emu.uuid=a5d95030-c68d-4843-9e4a-cfdf2214cb78'), only 'qemu.' properties are supported

Warning: Quick Boot / Snapshots not supported on this machine. A CPU with EPT + UG features is currently needed. We will address this in a future release.

 

I guess my CPU is old for the emulator :(

**Comment by jfversluis** [comment]
Unfortunately these type of problems can be hard to diagnose as there is a lot of factors that can influence this.

Please refer to the extensive documentation we have about the Android emulator, hopefully you can find something in there: https://learn.microsoft.com/dotnet/maui/android/emulator/troubleshooting

Else, please report your issue through Visual Studio in the help menu > Provide Feedback > Report a problem. That will land it with the right team and with the right logs etc.

Good luck!
