### ISSUE TITLE
InvalidCastException when using recommended ViewRenderer<TView, TNativeView>

### ISSUE THREAD

**Issue by roubachof** [dotnet/maui#10537]
### Description

I have the following exception:
```
"System.InvalidCastException: 'Specified cast is not valid.
```
If I use the recommended `ViewRenderer` (namespace `Microsoft.Maui.Controls.Handlers.Compatibility`).

If I use the obsolete `ViewRenderer` (namespace `Microsoft.Maui.Controls.Compatibility.Platform.Android`), it is working fine.

![image](https://user-images.githubusercontent.com/596903/194503504-1d6ad471-0321-4810-9ed2-4db8d585f5c6.png)

### Steps to Reproduce

1. clone https://github.com/roubachof/Sharpnado.CollectionView
2. switch to maui branch
3. open Maui/MauiSample/MauiSample.sln
4. go to Maui/Sharpnado.CollectionView.Maui/Platforms/Android/Renderers/CollectionViewRenderer
5. And replace the obsolete ViewRenderer with the recommended one.

### Link to public reproduction project repository

https://github.com/roubachof/Sharpnado.CollectionView

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Not version dependent

### Did you find any workaround?

Use the obsolete view renderer

**Comment by mattleibow** [comment]
I think this is because you are using `AddCompatibilityRenderer`... That is just for the obsolete things - and that is why it works. Just use `AddHandler` for the new "renderer" - confusing I know.

@PureWeen I think I am correct?

**Comment by PureWeen** [comment]
@mattleibow @roubachof here's a PR that should hopefully widen the pit of success a bit https://github.com/dotnet/maui/pull/10567. I've noticed a few users running into this scenario.
