### ISSUE TITLE
[Bug] ModalStack is broken (PushModalAsync, PopModalAsync [Android]) (Remove Page [All Platform])

### ISSUE THREAD

**Issue by Phenek** [dotnet/maui#10543]
### Description

I am testing the Modal Stack Navigation behavior.

- First point, when I am pushing 10 popups rapidly, 
The last page on the modal stack is not necessary the one display on front (on the device).

- Second point, when I poping with a button all pages one by one rapidly,
I can have at the end an empty modal stack, but still have one or more modal page displayed.

- Third point, we are not able to remove a specific modal page,
The method RemovePage(Page page) does not remove modal pages

### Steps to Reproduce

1. In MainPage.cs change the click too
```csharp
private void OnPushClicked(object sender, EventArgs e)
{
   Application.Current.MainPage.Navigation.PushModalAsync(new MainPage2());
}
```

2. On a second MainPage2.cs
```csharp
private void OnPopClicked(object sender, EventArgs e)
{
  Application.Current.MainPage.Navigation.PopModalAsync();
}
```
```csharp
private void OnRemoveClicked(object sender, EventArgs e)
{
  Application.Current.MainPage.Navigation.RemovePage(this);
}
```

3. Run and click verry fast on the centered button.
Yeah the behavior is very strange

### Link to public reproduction project repository
[https://github.com/Phenek/Maui-Issue/tree/issue/10543](https://github.com/Phenek/Maui-Issue/tree/issue/10543)

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

iOS 16, Android 13, Macatalist

### Did you find any workaround?

No we do not have access to the modal stack directly.

**Comment by Phenek** [comment]
I don't know, How can we up this one?

ModalStack is clearly the only way to have working popups on each platform on .Net MAUI.
We should be able to remove a specifiq page from this stack.
I mean, a page should be able to close it self, not another page.

PS: It was already broken on Xamarin.forms but we had some real alternative with [Rg.Plugins.Popup](https://github.com/rotorgames/Rg.Plugins.Popup).

**Comment by rachelkang** [comment]
Hi, @Phenek - thanks for reporting these issues. Could you please open separate issues for each of the ones you mention and provide the relevant repros for each? That way, we'll be able to investigate them separately and give the the necessary attention. Thanks :)

**Comment by janduldhardt** [comment]
Experience similar issues.

**Comment by Phenek** [comment]
I made a reproduction project on .Net7
[https://github.com/Phenek/Maui-Issue/tree/issue/10543](https://github.com/Phenek/Maui-Issue/tree/issue/10543)

It is really hard to reproduce with good hardware, so please use bad hardware.
WIth a LENOVO TAB M10, I can reproduce each time.

If you can not push 10 popup at once it's because you have a too good hardware.

Regards,

**Comment by Phenek** [comment]
Please follow => #11270

**Comment by samhouts** [comment]
Duplicate of #11270
