### ISSUE TITLE
Use BindableProperty on a self contained component

### ISSUE THREAD

**Issue by sinsedrix** [dotnet/maui#10542]
### Description

I'm trying to set some `BindableProperty`s on a self contained component, ie a component with it's own view model.

To have access to `BindableProperty`s, I declare the properties and their accessors:
```cs
  public ICommand ItemSelectedCommand
  {
    get => (ICommand)GetValue(ItemSelectedCommandProperty); 
    set { SetValue(ItemSelectedCommandProperty, value); Vm.ItemSelectedCommand = value; }
  }
  
  public ItemSize ItemSize
  {
    get => (ItemSize)GetValue(ItemSizeProperty);
    set { SetValue(ItemSizeProperty, value); Vm.ItemSize = value; }
  }

  public static readonly BindableProperty ItemSelectedCommandProperty = BindableProperty.Create(nameof(ItemSelectedCommand), typeof(ICommand), typeof(Component));
  public static readonly BindableProperty ItemSizeProperty = BindableProperty.Create(nameof(ItemSize), typeof(ItemSize), typeof(Component));
```

Then I set the view model as a property
```cs
  public ComponentVm Vm { get; }
```

So the component's constructor becomes:
```cs
  public Component()
  {
    InitializeComponent();
    Vm = new ComponentVm();
    BindingContext = this;
  }
```

Then I place the component in the MainPage, binding its properties:
```xaml
  <v:SelectorComponent
      ItemSelectedCommand="{Binding SelectItemCommand}"
      ItemSize="{Binding SelectedSize}"/>
```

If I set break points in porperties setters, I see they are never reached.
It seems to be a bug, but let me know if it's a mis-using of `BindingProperty`.

### Steps to Reproduce

Build test project:  [MauiTest/TransBinding](https://github.com/sinsedrix/MauiTests/tree/main/TransBinding)

Set break points in accessor setters.
Run app.
Notice that break points are never reached.

### Link to public reproduction project repository

https://github.com/sinsedrix/MauiTests

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 Pro

### Did you find any workaround?

No

**Comment by GF-Huang** [comment]
```cs
public Component()
  {
    InitializeComponent();
    Vm = new ComponentVm();
    BindingContext = this;
  }
```

So what's the use of `Vm`? You never use it.

It's really easy to get annoyed that the issues page is full of rookie questions like this.

**Comment by GalaxiaGuy** [comment]
When used from XAML, the getter and setter are not used. The `BindableProperty` instance is used directly (the getter and setter are essentially to make it easier to use the `BindableProperty` from code as if it was a normal property).

Instead of:

```csharp
public ICommand ItemSelectedCommand
{
    get => (ICommand)GetValue(ItemSelectedCommandProperty); 
    set { SetValue(ItemSelectedCommandProperty, value); Vm.ItemSelectedCommand = value; }
}
  
public static readonly BindableProperty ItemSelectedCommandProperty = 
    BindableProperty.Create(nameof(ItemSelectedCommand), typeof(ICommand), typeof(Component));
```

try
```csharp
public ICommand ItemSelectedCommand
{
    get => (ICommand)GetValue(ItemSelectedCommandProperty); 
    set => SetValue(ItemSelectedCommandProperty, value);
}
  
public static readonly BindableProperty ItemSelectedCommandProperty = 
    BindableProperty.Create(nameof(ItemSelectedCommand), typeof(ICommand), typeof(Component), propertyChanged: ItemSelectedCommandProperty);

public static void ItemSelectedCommandPropertyChanged(BindableObject bindable, object oldValue, object newValue)
{
    ((SelectorComponent)bindable).ItemSelectorCommand = (ICommand)newValue;
}
```
