### ISSUE TITLE
[Android] ConfigureLifecycleEvents OnBackPressed sample from documentation does not compile

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#10555]
### Description

The following code in documentation does not compile:
https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle#code-try-2

`.OnBackPressed((activity) => LogEvent("OnBackPressed"))` must be function returning `bool` for an unknown reason.

In `CreateMauiApp()` function in `MauiProgram.cs` add the following to the builder:
```

#if ANDROID
            builder.ConfigureLifecycleEvents(events =>
            {
                events.AddAndroid(android => android
                    .OnActivityResult((activity, requestCode, resultCode, data) => LogEvent("OnActivityResult", requestCode.ToString()))
                    .OnStart((activity) => LogEvent("OnStart"))
                    .OnCreate((activity, bundle) => LogEvent("OnCreate")) 
                    .OnBackPressed((activity) => LogEvent("OnBackPressed")) //cannot be void, must be function returning bool, e.g. (activity) => true
                    .OnStop((activity) => LogEvent("OnStop")) 
                    );
            });
#endif

static void LogEvent(string eventName, string type = null) =>
            Trace.WriteLine($"Lifecycle event: {eventName}{(type == null ? string.Empty : $" ({type})")}");
            
```

Also, the class `AndroidLifecycle` contains zero documentation which is not ideal.
![image](https://user-images.githubusercontent.com/64279914/194651063-742574d0-b8e5-4cc3-965a-7e5f4a122596.png)

### Steps to Reproduce

Add code from official documentation.
Project cannot be built.

### Link to public reproduction project repository

none

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

all

### Did you find any workaround?

no

**Comment by PureWeen** [comment]
@davidbritch

**Comment by janseris** [comment]
Seems like true /false is something like cancel event args here and it is bugged in terms of propagation in pages
