### ISSUE TITLE
 Permissions.CheckStatusAsync<LocationWhenInUse> calls OnAppearing when Denied and not invoking permission prompt

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#10566]
### Description

When permission is denied in application settings/information on Android and code calls  Permissions.CheckStatusAsync<LocationWhenInUse>();  which does not prompt anything, OnDisappearing and OnAppearing is called.

### Steps to Reproduce

Call Permissions.CheckStatusAsync<LocationWhenInUse>();  when permission is denied for the application (denied forever without the option to prompt again)

The situation that permission is denied forever and so this bug can then happen (prompt is not shown but OnDisappearing and OnAppearing is called for the page) is e.g. after:

- Android 8: user clicks Deny and ticks Never Ask Again on permission prompt
- Android 12: user clicks Deny for more than 1 times 

### Link to public reproduction project repository

none

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8, 12

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/pull/10530
