### ISSUE TITLE
InvalidateMeasure() not work at windows

### ISSUE THREAD

**Issue by yiszza** [dotnet/maui#10565]
### Description

in 7.0.0-rc.1.6683, InvalidateMeasure() it work at android, but not work at Windows.

### Steps to Reproduce

https://user-images.githubusercontent.com/42995476/194712811-508ea92a-7e33-4860-8ac4-6f3825f50ba7.mp4

[BugTest.zip](https://github.com/dotnet/maui/files/9739501/BugTest.zip)

### Link to public reproduction project repository

none

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

none

**Comment by PureWeen** [comment]
@yiszza can you expand on your use case here a little bit more?

**Comment by yiszza** [comment]
> @yiszza can you expand on your use case here a little bit more?
> 
> @ yiszza 你能在这里多展开一下你的用例吗？

I can't get the max allocation size of the control, This confuses me, How can I allocation reasonable size when my control changes?
I'm developing a controls library, https://github.com/yiszza/Material.Components.Maui

**Comment by yiszza** [comment]
@jsuarezruiz @PureWeen hello? How long will it take to fix? Or do you ignore the issue at all?
