### ISSUE TITLE
Icon for Android or iOS

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/maui#10569]
I made an icon in SVG; the problem is.
I don't know how to scale it down so it fits.
It would be nice if somebody could explain.

https://github.com/www-object-social/Storytime-OBJECTSOCIAL-Claims

**Comment by xtuzy** [comment]
icon for toolbar or tabbar? you can use widthrequest and heightrequest set image size, if your image not fit, such as seem too big,  you can set aspect, or add padding, or set it in a layout, down image size, total layout as a icon.

**Comment by PirasathLuxchumykanthan** [comment]
Icon for android and ios.
So you say I need to make a foreground?

**Comment by KSemenenko** [comment]
Related #10572

**Comment by PureWeen** [comment]
@PirasathLuxchumykanthan can you fill out a new issue and answer all the questions in the template please? Also include some screenshots so we have a better idea of the issue?
