### ISSUE TITLE
Documentation for Geolocation returning null missing

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#10562]
### Description

https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device/geolocation?tabs=android

`Geolocation.Default.GetLocationAsync()` sometimes returns `null`.
There is no comment on why and how to handle this.
It sometimes returns null when device is locked (Activity is Stopped).
It sometimes returns null from the start of the GPS check and never recovers (GPS permission is granted, GPS is turned on, GPS in the same location normally returns a value).
In other cases, when device is locked (Activity is Stopped), it returns some kind of cached GPS.

What does `null` returned by `GetLocationAsync()` mean?
Does it mean that GPS location could not be retrieved within the timeout set in `GeolocationRequest` `CancellationToken`?

Thank you for adding documentation

### Steps to Reproduce

call `Geolocation.Default.GetLocationAsync()` and receive `null`

### Link to public reproduction project repository

none

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8, Android 12

**Comment by Redth** [comment]
@davidbritch could you add a note to the conceptual docs about this? It's expected that the platform may return `null` in this call, we don't have much control over what we are given from the platform.
