### ISSUE TITLE
Windows Unpackaged support in .NET MAUI 

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#10564]
## Description

This is an epic issue tracking all the things needed for a 100% support rating.

### MAUI SDK

- [ ] Controls / XAML
- [ ] Core
- [ ] Essentials
   - [x] https://github.com/dotnet/maui/pull/10476
   - [x] https://github.com/dotnet/maui/pull/10356
   - [ ] https://github.com/dotnet/maui/issues/8552
- [ ] Graphics
- [ ] Other (targets, resizetizer, etc)
   - [x] https://github.com/dotnet/maui/issues/3166
   - [x] https://github.com/dotnet/maui/issues/9064
   - [x] https://github.com/dotnet/maui/pull/8432
   - [x] https://github.com/dotnet/maui/issues/6330
   - [ ] https://github.com/dotnet/maui/issues/5975
   - [x] https://github.com/dotnet/maui/issues/5881
   - [x] https://github.com/dotnet/maui/pull/4460

### Platform SDKs (Windows App SDK, Windows OS)

- [ ] https://github.com/microsoft/WindowsAppSDK/issues/2922
- [x] https://github.com/microsoft/WindowsAppSDK/issues/2870
- [ ] https://github.com/microsoft/WindowsAppSDK/issues/2684
- [ ] https://github.com/microsoft/microsoft-ui-xaml/issues/7331
- [x] WinUI custom titlebars not draggable in unpackaged apps
       https://dev.azure.com/microsoft/OS/_workitems/edit/38358053
       https://microsoft.visualstudio.com/OS/_workitems/edit/37749544
- [ ] Unpackaged apps can get Package Identity without any developer engagement.
       https://dev.azure.com/microsoft/OS/_workitems/edit/40211194
- [x] https://github.com/dotnet/maui/issues/9104
- [ ] https://github.com/microsoft/WindowsAppSDK/issues/3337
- [ ] https://github.com/microsoft/WindowsAppSDK/issues/4008
- [ ] https://github.com/microsoft/WindowsAppSDK/issues/2684

### Tooling

- [ ] Core IDE
    - [x] [MAUI] Enable WinAppSDK automatic packaged->unpackaged setting in Visual Studio  
           https://dev.azure.com/microsoft/OS/_workitems/edit/37055170
- [ ] UI Tools
- [ ] Platform Tools
   - [ ] ClickOnce support?
- [ ] Other
   - [ ] Make unpackaged the DEFAULT development experience
   - [ ] .NET MAUI WinUI publishing "unpackaged" apps  
          https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1556834
   - [ ] Unpackaged app created from default template just crashes 
          https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1565698
   - [ ] Customer needs a modern installation experience for desktop applications using an Open Source deployment solution  
          https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1256825
   - [ ] Developers can publish/deploy unpackaged  
          https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1054423
   - [ ] Add build support for unpackaged perf scenarios 
          https://dev.azure.com/microsoft/OS/_workitems/edit/39145956
   - [ ] Customize and optimize .NET MAUI apps for packaging and distribution
         https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1556844
   - [ ] [VS] WinUI Unpackaged support investigation and planning
         https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1555666

### Runtime / .NET SDK

- [ ]

> VS bug [#1791241](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1791241)

**Comment by kevmoens** [comment]
I would like to up vote ClickOnce
We ship software to on premise customers which then install and host our apps.  Thus we don't know the customer's URL where are app is hosted.

Currently we can update our app.config so our app knows where the hosted services are.  Then ClickOnce solves this as we package the ClickOnce app on their server using mage.exe with their own server's URL.

**Comment by Xo3-ToBapbl** [comment]
Could some please clarify: am I right that currently it is not possible to debug MAUI Win UI unpackaged application?

**Comment by mattleibow** [comment]
.NET MAUI supports building, debugging and publishing unpackaged apps. I am closing this issue as it was more of a container/uber issue to link everything. However, all the main features are done and the remaining are logged with the related teams. For example, issues with publishing certain things or running from the CLI are logged with WASDK.
