### ISSUE TITLE
[Android] If MainPage overrides OnBackButtonPressed,  OnBackButtonPressed and Android back button stop being called for other pages

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#10561]
### Description

If `MainPage : Shell` overrides OnBackButtonPressed, it is always called and works the following way:
`return true` => exit application
`return false` => do nothing

If then a different page `PopupPage : ContentPage` which is referenced in MainPage markup (simplified):

```xaml
<Shell>
    <TabBar>
        <Tab Title="Popup" Icon="popup">
            <ShellContent ContentTemplate="{DataTemplate local:PopupPage}" />
        </Tab>
    </TabBar>
</Shell>
```

Then if PopupPage overrides OnBackButtonPressed and MainPage overrides OnBackButtonPressed , PopupPage's OnBackButtonPressed  is never called even when currently at PopupPage (I print when navigating to PopupPage so I make sure I am on it).

This is a big problem because if I override OnBackButtonPressed like this on MainPage, then back button on every page triggers this function instead of triggering "Back" behavior on that page (when backing is possible):
```cs
 //this function cannot be async
        protected override bool OnBackButtonPressed()
        {
            //this is a dirty hack which shows Yes/No prompt and exits forcefully if users selects Yes
            //but leaving should be done by passing the true/false as a return value to this OnBackButtonPressed method.
            //how to read variable from async DisplayAlert UI call? it seems like Dispatcher.Dispatch must be waited for else this returns (e.g. false = close) and app crashes
            Dispatcher.Dispatch(async () =>
            {
                bool leave = await DisplayAlert("Leave MainPage?", "Leave MainPage?", "Yes", "No");
                if (leave)
                {
                    Application.Current.Quit();
                } else
                {
                    //do nothing
                }
            }
            );

            return true; //stay
        }
```

![image](https://user-images.githubusercontent.com/64279914/194675323-3559e2bc-c68a-40c7-b5db-e67fad8852e6.png)

When I remove the OnBackButtonPressed overriding in MainPage, navigation using Android Back button works again fine on this BrowsePage.

### Steps to Reproduce

steps above

### Link to public reproduction project repository

none

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

all

### Did you find any workaround?

no

**Comment by GF-Huang** [comment]
Why you don't call `base.OnBackButtonPressed(...);` in your override method?
