### ISSUE TITLE
Titlebar Translucent Issue When Switching the Root to Shell

### ISSUE THREAD

**Issue by AathifMahir** [dotnet/maui#10573]
### Description

This issue happens on most of scenerios like replacing navigation page with shell and shell with shell causes Titlebar to be translucent and pushes the page content to Title bar, as far as my testing it Happens on Windows 10 and 11, Not sure about Mac

As we see this issue has been fixed on .Net 7 Build as this closed issue #7274 describes, But we need the issue to be fixed Stable Version and Really an Annoyance when the app in production

### Steps to Reproduce

1. Create a New Maui Project
2. Head to App.xaml.cs
3. Change Mainpage = New AppShell() to Mainpage = New NavigationPage(New MainPage())
4. Create a button on Main Page and Use this code for Click event
Application.current.MainPage = New AppShell()

In the end when we click newly created button on Mainpage, we'd encounter this issue

### Link to public reproduction project repository

https://github.com/AathifMahir/ShellTitleBar_Issue

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 to Windows 11

### Did you find any workaround?

Currently, Didn't found any workarounds for this issue

**Comment by samhouts** [comment]
@AathifMahir 7.0 is now stable. Are you able to use that version? Thanks!

**Comment by AathifMahir** [comment]
> @AathifMahir 7.0 is now stable. Are you able to use that version? Thanks!
> 

Sure 👍
