### ISSUE TITLE
Xaml Compiler NullRef with Grid.Resources

### ISSUE THREAD

**Issue by 333fred** [dotnet/maui#10583]
### Description

When I include a resources dictionary on a `Grid`, the XamlC compiler null-refs.

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Create a generic IMarkupExtension
3. Attempt to define that markup extension in a static resource with a type argument.
4. Observe null ref from the XamlC compiler.

### Link to public reproduction project repository

https://github.com/333fred/maui-layout-bugs/tree/generic-imarkupextension-nullref

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

.NET 7.0 RC1

### Relevant log output

```shell
MainPage.xaml : XamlC error : Object reference not set to an instance of an object. [C:\temp\temp.csproj::TargetFramework=net7.0-maccata
lyst]
MainPage.xaml : XamlC error : Object reference not set to an instance of an object. [C:\temp\temp.csproj::TargetFramework=net7.0-ios]
MainPage.xaml : XamlC error : Object reference not set to an instance of an object. [C:\temp\temp.csproj::TargetFramework=net7.0-android
]
MainPage.xaml : XamlC error : Object reference not set to an instance of an object. [C:\temp\temp.csproj::TargetFramework=net7.0-windows
10.0.19041.0]
```

**Comment by 333fred** [comment]
Note: this appears to be much worse than I originally thought. I currently _cannot_ find a way to define and use a generic `IMarkupExtension<T>`. For example, if I instead make this an argument to an `ItemSource`, as in:
```xaml
<Picker>
    <Picker.ItemSource><test:EnumValuesProvider x:TypeArguments="test:E" /></Picker.ItemSource>
</Picker>
```
This example will also null-ref the Xaml compiler.

**Comment by StephaneDelcroix** [comment]
Markup Extensions are supposed to be used with the `{MarkupExtension}` syntax, and that doesn't support x:TypeArguments

**Comment by 333fred** [comment]
@StephaneDelcroix the [documentation](https://learn.microsoft.com/en-us/dotnet/maui/xaml/markup-extensions/create) on creating a custom markup extension does not mention that at all. It uses the syntax from my second example, which null refs the compiler.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Can repro on android platform with sample project.
https://github.com/333fred/maui-layout-bugs/tree/generic-imarkupextension-nullref
![image](https://github.com/dotnet/maui/assets/82450723/2f81ab23-8359-4d2b-8027-53c9afb512cf)

**Comment by StephaneDelcroix** [comment]
Using a MarkupExtension as a resource will never work. MarkupExtensions are transient objects and do not survive when the XAML is fully parsed.

I tried using a generic markup extension like it should `    <ListView x:Name="lv" ItemsSource="{local:Maui10583EnumValuesExtension x:TypeArguments=local:Maui10583Enum}" />
` and it works with runtime XAML, but the XAML Compiler produces invalid IL. We're going to fix that.
