### ISSUE TITLE
Shell Title View Set at Shell.Xaml.cs is visible in alternative flyout items

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#10587]
### Description

I set a titleview to a custom control in shell.xaml.cs. The app have several flyout items. The title view is only visible in alternate flyout items when flyouts are changed. 

### Steps to Reproduce

Run the repro and select different flyout items. The titlview will be visible in one and will be invisible in another. 

### Link to public reproduction project repository

https://github.com/HobDev/MauiBugs/tree/ShellTitleViewIssue

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. This issue does not reproduce on iOS 16.4 and Windows 11, repro on Android 13.0-API33 with below Project:
[MauiBugs.zip](https://github.com/dotnet/maui/files/11620493/MauiBugs.zip)

![Title](https://github.com/dotnet/maui/assets/97647558/22daf54e-610e-49da-ab10-2e4b695a6120)

**Comment by DM-98** [comment]
Issue still remains as of .NET 8 Preview 6, and it's a pretty big deal, and not sure what the workaround is at this moment. We're unable to ship a product due to this issue. 

In my case, the issue where the TitleView disappears occurs only when navigating with await Shell.Current.GoToAsync("//myPage");

**Comment by travis012** [comment]
I think this issue has to do with shared UI resources. in WPF you can define your resource in a resource dictionary and mark it with `x:shared="false"` but this is not supported in maui.

For a workaround you have to make sure all page instances get their own instance of your title view.

**1. Create your title view(s) in a resource dictionary wrapped inside of a DataTemplate:**
```xaml
<?xml version="1.0" encoding="UTF-8" ?>
<?xaml-comp compile="true" ?>
<ResourceDictionary 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">

    <DataTemplate x:Key="MyTitleViewHeaderDatatemplate" >
        <Label Text="My title view!"/>
    </DataTemplate>
</ResourceDictionary>
```
NOTE: To simply things, you can put it in `Resources\Styles\Styles.xaml`

**2. Add this markup extension to your project:**
```Csharp
    public class ViewLoaderFromTemplateExtension : IMarkupExtension<View>
    {
        public DataTemplate Template { get; set; }

        public View ProvideValue(IServiceProvider serviceProvider)
        {
            return Template.CreateContent() as View;
        }

        object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
        {
            return (this as IMarkupExtension<View>).ProvideValue(serviceProvider);
        }
    }
```

**3. Set the `Shell.TitleView` attached property in ALL of your `ShellContent` objects in your `AppShell.xaml` using the `ViewLoaderFromTemplate` markup extension:**
```xaml
<ShellContent Shell.TitleView="{local:ViewLoaderFromTemplate Template={StaticResource MyTitleViewHeaderDatatemplate}}" Route="MainPage"  ContentTemplate="{DataTemplate pages:MainPage}"/>
```

**4. If you need to push your page onto navigation from code behind you still must set it's TitleView attached property!**
```CSharp
        if (Application.Current.Resources.TryGetValue("MyTitleViewHeaderDatatemplate", out object oTemplate))
        {
            MainPage p = new MainPage();
            Shell.SetTitleView(p, (View)((DataTemplate)oTemplate).CreateContent());

            Navigation.PushAsync(p);

        }
        else
        {
            throw new Exception("Your data template must be included in your global application resources to use it this way. Add the resource dictionary containing your template to App.xaml")
        }
```

**Comment by sachinthau** [comment]
any update of this, because I am still facing for the issue

**Comment by bricefriha** [comment]
@travis012 Thanks, it's better than nothing, but there is one specific use case in which this workaround won't work: if we have binding data inside the titleview.

In my opinion, I think this is the kind of issue that should be addressed ASAP

**Comment by mattleibow** [comment]
I just tested with the sample app using MAUI `8.0.82` and it worked for me:

[android shell title.webm](https://github.com/user-attachments/assets/2263d5fc-c706-4aa3-b64a-9e97f8e62a92)
