### ISSUE TITLE
[BUG] Newly created view has IsVisible=ture

### ISSUE THREAD

**Issue by tomasfil** [dotnet/maui#10584]
### Description

Once new Content/View is instanciated, then is has default IsVisible true, which is incorrect (It is nowhere on the UI).

This is causing issues with ReactiveUI WhenActivated.

https://github.com/reactiveui/ReactiveUI/issues/3348

### Steps to Reproduce

Start the project and see the property default to true, when there is no UI displayed.

### Link to public reproduction project repository

https://github.com/tomasfil/IsVisibleMauiBug

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

All

**Comment by PureWeen** [comment]
@tomasfil  Is this different from how it worked on XF?

**Comment by tomasfil** [comment]
Hello @PureWeen, what is XF?

**Comment by tomasfil** [comment]
Indeed on Xamarin.Forms it is the same, but it is false information...

I suggest Loaded event should be used as workaround? But again, it is incorrect information, which currently reactiveUi ActivationForViewFetcher relays on:  https://github.com/reactiveui/ReactiveUI/blob/main/src/ReactiveUI.Maui/ActivationForViewFetcher.cs#L70

**Comment by tomasfil** [comment]
Yeah, you just answered to me, that Loaded and Unloaded events are the way to go..

**Comment by PureWeen** [comment]
> Yeah, you just answered to me, that Loaded and Unloaded events are the way to go..

Sounds good!

I'm going to close this issue. I realize the name can cause confusion, but we can't modify the behavior of `IsVisible`. 
Which is why we added other hooks :-)

**Comment by PureWeen** [comment]
@tomasfil also with regards to the code you linked. It might be useful for RxUI to look into a few other Page events for MAUI as well. 

NavigatedTo/NavigatedFrom/NavigatingFrom give the user a bit better context as to what's going on.
