### ISSUE TITLE
[Mac Catalyst] Application.Current.OpenWindow not working

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#10603]
### Description

`Application.Current.OpenWindow(new Window(new MainPage()));` works fine on Windows, in .NET 7 RC1, but does nothing on Mac Catalyst. Similarly, `Application.Current.CloseWindow(Window);` works fine on Windows, but does nothing on Mac Catalyst.

No exceptions. No errors. No new window.

### Steps to Reproduce

1. Run repo project on Mac Catalyst.
2. Click button to open a new window. Nothing happens.

### Link to public reproduction project repository

https://github.com/davidbritch/dotnet-maui-issues/tree/main/WindowSizeDemo

### Version with bug

.NET 7 RC1.

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

N/A

**Comment by davidbritch** [comment]
Confirmed that this is no longer an issue once I remembered to add the SceneDelegate/Info.plist config.

**Comment by mattleibow** [comment]
Might need to wait for this: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1641233/

**Comment by nor0x** [comment]
any updates on this? Multi-Window doesn't work at all on macOS

**Comment by davidbritch** [comment]
Hi @nor0x 

It works on my machine - check out https://github.com/davidbritch/dotnet-maui-issues/tree/main/WindowSizeDemo. You have to add SceneDelegate.cs and configure Info.plist to make it work on Mac Catalyst.

@mattleibow Personally I'd close this issue, or rename it at least.

**Comment by nor0x** [comment]
thanks for the reply @davidbritch - turns out it was a typo in my plist file. Everything good now 🥳
