### ISSUE TITLE
EnableDefaultApplicationDefintition typo in WinUI project template

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#1060]
Here:

https://github.com/dotnet/maui/blob/81994d1e684e753e119732005305ce2d0422a61b/src/Templates/src/maui-mobile/MauiApp1.WinUI3/MauiApp1.WinUI3.in.csproj#L12

This should presumably be `EnableDefaultApplicationDefinition`, but I'm not sure what will happen once the typo is fixed (clearly the current code does nothing).

cc @Redth

**Comment by Eilon** [comment]
I think the 2 options are:

1. Fix the typo and make sure the template still works
2. Remove the errant line entirely

**Comment by Redth** [comment]
Fixing in #1063
