### ISSUE TITLE
Random Android.Util.AndroidRuntimeException Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by tradegear** [dotnet/maui#10618]
### Description

It seems that if I run an async task within:
    public void ApplyQueryAttributes(IDictionary<string, object> query)

for example:

```cs
public void ApplyQueryAttributes(IDictionary<string, object> query)
    {
        Task.Run(() => 
        _jobsInProductionViewModel.GotoPageSessionTokenIfInvalidSessionToken()
        ).Wait();
        if (_jobsInProductionViewModel.vmSessionToken.validSession == 1) /* will be =1 */
            Task.Run(() => 
            _jobsInProductionViewModel.M1APIJobsInProductionGetCommand.Execute(null)
            ).Wait();
    }
```
I receive randomly generated errors:

Android.Util.AndroidRuntimeException
  Message=Only the original thread that created a view hierarchy can touch its views.

Is this because sometimes the async task is run on a separate thread, and other times it is not?

Note, I did try to implement an "async" in front of ApplyQueryAttributes method, but the interface does not seem to support async.
I need to perform token validation when this page is instantiated.  How does one do this and avoid the random confusion related to async and android UI thread limitations?

### Steps to Reproduce

You would have to have my whole machine.  There are SQL databases, and a webAPI.
Hopefully my question has a simple answer and I'm just inexperienced enough to not know it.

### Link to public reproduction project repository

n/a

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

I don't know how to look this up.

### Did you find any workaround?

no workaround.  I've spent hours trying various things.

**Comment by GF-Huang** [comment]
What diffs between

```cs
Task.Run(() =>
    _jobsInProductionViewModel.GotoPageSessionTokenIfInvalidSessionToken()
).Wait();
```
and

```cs
_jobsInProductionViewModel.GotoPageSessionTokenIfInvalidSessionToken()
```

NO, they are same, they both block your main thread. 

If you are not familiar with C# tasks/async/await, it is recommended to learn the basics first.

At last, format your code like this:

![image](https://user-images.githubusercontent.com/4510984/195202423-87ded93d-3987-4dea-9801-5d72b355fc9e.png)

**Comment by GF-Huang** [comment]
Why am I so angry? When I want to see how many bugs MAUI currently has, the issues page is full of newbie questions like you.

This is not MAUI issues at all. 

There are currently 1.1K issues with bug tags, and I even suspect more than 800 are newbie issues that have nothing to do with MAUI.

**Comment by rachelkang** [comment]
Hi, @tradegear - Please check out the docs at https://learn.microsoft.com/dotnet/maui/platform-integration/appmodel/main-thread - they should be helpful in understanding how to approach your scenario
