### ISSUE TITLE
Lottie animation not visible on Page from ServiceProvider

### ISSUE THREAD

**Issue by MarMarIV** [dotnet/maui#10628]
### Description

When Page with Lottie animation is created from ServiceProvider, then Lottie animation is not visible

### Steps to Reproduce

In file `App.xaml.cs` there are two examples. One i working fine. Second not

### Link to public reproduction project repository

https://github.com/MarMarIV/MauiLottieApp

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Any version

### Did you find any workaround?

Unfortunately, no

**Comment by PureWeen** [comment]
Moved To https://github.com/mono/SkiaSharp.Extended/issues/147

@pictos  FYI ^
