### ISSUE TITLE
[WinUI] Flashy backgrounds on start

### ISSUE THREAD

**Issue by mhrastegari** [dotnet/maui#10629]
### Summary
Is there a way to prevent or at least a workaround for changing the color of these flashy things?
I'm using the latest VisualStudio prerelease and I did everything like changing the BlazorWebView BackgroundColor in XAML or changing the root html color but no luck so far :(

### Screenshots
Step 1
![Screenshot 2022-10-12 114018](https://user-images.githubusercontent.com/42671084/195289228-2bf1ef29-2d68-4a35-afdb-97c2b70533ab.png)

Step 2
![Screenshot 2022-10-12 114044](https://user-images.githubusercontent.com/42671084/195289236-22e974fd-12a1-44da-b60f-43975ebfe148.png)

Step 3
![Screenshot 2022-10-12 114101](https://user-images.githubusercontent.com/42671084/195289246-84ee42f3-34de-4057-bf17-4ad9e6a1eb11.png)

**Comment by javiercn** [comment]
@mhrastegari thanks for contacting us.

I suspect you can configure this in the underlying webview as described [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.defaultbackgroundcolor?view=webview2-dotnet-1.0.1370.28) (at least for WinUI)

The BlazorWebview exposes a couple of event handlers to get access to the configuration of the underlying platforms webview during initialization. See [here](https://learn.microsoft.com/vi-vn/aspnet/core/blazor/hybrid/?view=aspnetcore-6.0#web-view-configuration) for details

**Comment by mhrastegari** [comment]
Thank you so much @javierc !
You saved my day :)
