### ISSUE TITLE
[Android] Multiple navigation bars appear for FlyoutPage (MAUI ver. 6.0.541)

### ISSUE THREAD

**Issue by vg12345** [dotnet/maui#10634]
### Description

Basic FlyoutPage implementation with menu and two pages.
Switching between pages adds additional navigation bars on Android (see picture below).

**Reproduced on ver. 6.0.541 (current) with Visual Studio 17.3.6**
Probably, regression from previous version, but not sure

Attached:
MauiApp3 source code that demonstrates the bug
[MauiApp3.zip](https://github.com/dotnet/maui/files/9764467/MauiApp3.zip)

![Bug](https://user-images.githubusercontent.com/77556137/195332618-34bbbe19-a76a-4e56-8e79-9f0a42b9434b.jpg)

### Steps to Reproduce

1. Open MauiApp3 application on Android -> "Page 1" appears on startup
2. Open menu and choose "Page 2"
3. Open menu and choose "Page 1" -> additional bar is added
4. Open menu and choose "Page 2" -> additional bar is added
5. Open menu and choose "Page 1" -> additional bar is added
6. Open menu and choose "Page 2" -> additional bar is added
7. Open menu and choose "Page 1" -> additional bar is added

[MauiApp3.zip](https://github.com/dotnet/maui/files/9764510/MauiApp3.zip)

### Link to public reproduction project repository

https://github.com/dotnet/maui/files/9764510/MauiApp3.zip

### Version with bug

6.0.541 (current)

### Last version that worked well

6.0.486 (not sure)

### Affected platforms

Android

### Affected platform versions

Android 8.0 (MIUI Global 11.0.2)

**Comment by vg12345** [comment]
No, I don't have 7.0 RC2 installed

**Comment by PureWeen** [comment]
There's still a bug with this on RC2 but I tested it with .NET 7.0 RTM and it looks like it's working there just fine. 

I'm going to close this for now and if you're still seeing this issue once .NET 7.0 GA's let me know.
