### ISSUE TITLE
[Windows] Image is not centered in AspectFill mode

### ISSUE THREAD

**Issue by vg12345** [dotnet/maui#10645]
### Description

Image is not centered in AspectFill mode on Windows. 
iOS and Android are OK.

**Reproduced on ver. 6.0.541 (current) with Visual Studio 17.3.6**

Attached:
MauiApp4 source code that demonstrates the bug:

[MauiApp4.zip](https://github.com/dotnet/maui/files/9766041/MauiApp4.zip)

![Bug](https://user-images.githubusercontent.com/77556137/195374368-46728a5d-29d8-48ac-a51d-d0e2ed385c34.png)

### Steps to Reproduce

Open attached MauiApp4 application that demonstrates the problem:
[MauiApp4.zip](https://github.com/dotnet/maui/files/9766050/MauiApp4.zip)

### Link to public reproduction project repository

https://github.com/dotnet/maui/files/9766050/MauiApp4.zip

### Version with bug

6.0.541 (current)

### Last version that worked well

Unknown

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

**Comment by Ruddy2007** [comment]
This seems pretty basic to fix, not sure why this is in the backlog and not being fixed. Windows is still being treated like a platform that isn't supported.

**Comment by edcache** [comment]
I can't get the grid workaround to work. Can you provide an example with MAUI xaml @japarson ?

**Comment by MitchBomcanhao** [comment]
how is this still not fixed?

**Comment by sbloom82** [comment]
I am also running into this issue.  I've been able to make some adjustments to the image's margin in the code behind to center then image, but it's a little laggy when resizing the window, not 100% correct, and not quite and ideal fix.

**Comment by RuddyOne** [comment]
So this has been fixed? 

Looks like its aiming for .NET 8 SR9? Do we have release dates for this? Im a little confused as to what version this will be in and when the fix will be available.
