### ISSUE TITLE
Validate Windows buttons have round corners

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#10644]
### Description

Last I saw something broke the default style so it reverted back to win 10 themes.

### Steps to Reproduce

Run windows

### Link to public reproduction project repository

maui

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

all

**Comment by mattleibow** [comment]
If you start testing this, it will be good to make sure that it is fixed/broken in the current VS insertion PRs so we know where to start and file known issues.

**Comment by tj-devel709** [comment]
Addressed in this PR: https://github.com/dotnet/maui/pull/10664
