### ISSUE TITLE
Frame.CornerRadius not working on iOS

### ISSUE THREAD

**Issue by AndyG74** [dotnet/maui#10643]
### Description

<img width="1287" alt="FrameCornerRadius" src="https://user-images.githubusercontent.com/61390650/195353369-a1a39975-32be-4366-aa0c-c5110712f01b.png">

### Steps to Reproduce

set the CornerRadius property on Frame object, then you can see on iOS there is no CornerRadius.

### Link to public reproduction project repository

https://1drv.ms/u/s!AvfMdSsMYykdkqJE-tsYDQaScSxFSA

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPhone 14 Simulator iOS 16.0

**Comment by rmarinho** [comment]
maybe related with #10480

**Comment by danielftz** [comment]
> border is not a equal control to frame, there is not corner radius. but, IsClippedToBounds="True" is the solution.
If you set the Stroke as RoundRectangle then Border can be used as a Frame

**Comment by jsuarezruiz** [comment]
> border is not a equal control to frame, there is not corner radius. but, IsClippedToBounds="True" is the solution.

Not related with the issue, which we must fix but you can use any Shape with the Border, included a RoundRectangle where you can set the radius from any corner.

**Comment by jsuarezruiz** [comment]
Could you try with the latest version? Tried with net7 rc2 and cannot reproduce the issue.

<img width="431" alt="Captura de Pantalla 2022-10-20 a las 14 29 16" src="https://user-images.githubusercontent.com/6755973/196948891-2fc45590-aa6a-4441-977a-ff0ca6239619.png">
