### ISSUE TITLE
Android PopModalAsync still fails when popping a NavigationPage after latest review update (.NET 7)

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#10656]
### Description

When pushing  a page onto a stack via a Navigation Page using:

```await Application.Current.MainPage.Navigation.PushModalAsync(new NavigationPage(toPage));```

It the crashes with an exception [System.InvalidOperationException: 'NavigationView cannot be null'] when popped

This still works under [.net6] but fails under [.NET7]. It appears to work fine under iOS.

Installed Workload Id      Manifest Version                  Installation Source
--------------------------------------------------------------------------------
maui-windows               7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.33006.217  
maui-maccatalyst           7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.33006.217  
maccatalyst                15.4.1031-rc.1/7.0.100-rc.1       VS 17.4.33006.217  
maui-ios                   7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.33006.217  
ios                        15.4.1031-rc.1/7.0.100-rc.1       VS 17.4.33006.217  
maui-android               7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.33006.217  
android                    33.0.0-rc.1.151/7.0.100-rc.1      VS 17.4.33006.217  
runtimes-windows           7.0.0-rc.2.22472.3/7.0.100        VS 17.4.33006.217  

This a serious issue. I'm sure many are using this push/pop approach for navigation (navigating Modal via a NavigationPage to lose the back button and to customise the header). There are alternatives to this but they have their own regression problems. This technique worked 100% under Xamarin Forms!!!!

### Steps to Reproduce

1. Load project from repro: https://github.com/hbraasch/BasicNavigationUsingNavPageTester.git
2. Run for Android, click [Navigate away], then [Navigate back]
3. Observe the error

### Link to public reproduction project repository

https://github.com/hbraasch/BasicNavigationUsingNavPageTester.git

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 - API 31 (Only one tested)

### Did you find any workaround?

No

**Comment by jenscski** [comment]
Same as this?
https://github.com/dotnet/maui/issues/10235

**Comment by smitha-cgi** [comment]
@hbraasch I'm guessing you updated to .NET 7 RC2 thinking it would fix #10235 (based on _runtimes-windows 7.0.0-rc.2_ reported in your workloads), but what was released a couple of days ago doesn't include any MAUI stuff. You'll need to wait for the MAUI RC2 release which is due out next week I think.

**Comment by PureWeen** [comment]
> @hbraasch I'm guessing you updated to .NET 7 RC2 thinking it would fix #10235 (based on _runtimes-windows 7.0.0-rc.2_ reported in your workloads), but what was released a couple of days ago doesn't include any MAUI stuff. You'll need to wait for the MAUI RC2 release which is due out next week I think.
