### ISSUE TITLE
Attached Property Errors

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#10652]
### Description

I wanted to migrate a StackPanel containing a CollectionView from Xamarin to MAUI, unfortunately the two are quite different and you have to use a Grid instead of a StackPanel in MAUI. I suggested it would be nice to have a cleaner alternative a (see #10224) and @hartez was kind enough to point me to some sample code that did what I needed, experimenting with this revealed that Attached properties in XAML don't seem to work. It's possible I've missed something, since I've never tried to define an attached property before, but  I'm pretty sure I followed the [instructions](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/attached-properties). 

### Steps to Reproduce

1. Clone https://github.com/david-maw/MauiAttached.git
2. Build the project and run it on Windows
3. Click on one of the txt lines ("Header", "Line 2" or "Footer", then resized the window to see the change in spacing (any hints on how to trigger that redraw automatically gratefully received).
4. You've now demonstrated it all works, close the program.

Open up MainPage.xaml in Visual Studio, the page content is:

```xaml
<local:ColumnLayout x:Name="columnLayout">
    <local:ColumnLayout.GestureRecognizers>
        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"/>
    </local:ColumnLayout.GestureRecognizers>
    <Label Text="Header"/>
    <!--<Label Text="Line 1" local:ColumnLayout.Fill="true"/>-->
    <Label x:Name="line2" Text="Line 2"/>
    <Label Text="Footer"/>
</local:ColumnLayout>    

```

Uncomment the "Line 1" label and intellisense will show an error:

![Intellisense](https://user-images.githubusercontent.com/12423046/195415017-19c62b6b-8162-4067-8c2e-41715d7b4ed5.jpg)

Compile the code and you will see the error:
```
MainPage.xaml(12,30): XamlC error XFC0020: The name of the BindableProperty Fill does not end with "Property".
```

On the face of it these would seem to be spurious errors, ColumnLayout.cs begins with:

```cs
public class ColumnLayout : VerticalStackLayout
{
    public static readonly BindableProperty FillProperty = BindableProperty.CreateAttached("Fill", typeof(bool),
        typeof(ColumnLayout), false);
```

### Link to public reproduction project repository

https://github.com/david-maw/MauiAttached.git

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11, Windows 10 

### Did you find any workaround?

Not for XAML, but the same thing can be done in code as the example demonstrates.

**Comment by PureWeen** [comment]
@david-maw I think you need to set your `GetFill` and `SetFill` to static

**Comment by david-maw** [comment]
Thanks @PureWeen that fixed it, sorry, I hadn't realized static Get/Set functions were necessary to create attached properties, thanks for the hint, I'll alert @hartez since it's his code I repurposed to create an attached property instead of a merely bindable one. If anyone's got a hint on how to trigger a control refresh when the property changes dynamically it'd be interesting for the general case but I don't need it for my usage.
