### ISSUE TITLE
When using a barcode scanner, the Entry.Completed event is fired with empty Text

### ISSUE THREAD

**Issue by ruimgoncalves** [dotnet/maui#10663]
### Description

When using a barcode scanner the Entry.Completed event is fired before the control is populated with the scanned barcode, and the Text value is Empty or null, and only after the event the Entry control is populated with the correct scanned value, but no Completed event is thrown again, since it already was triggered before.

The Entry.ReturnCommand is also affected with this behavior.

## Expected Behavior

Entry.Completed event fired after with the Text property filled with the scanned barcode value.

## Checks I already made

- The Entry.Completed event fires with correct Text if the Entry is populated by keyboard ✅ 
- Pasting the text and hitting enter in the Entry produced the Completed event with correct Text value ✅ 
- Barcode scanner is correctly configured to append the return key to the scanned value ✅ 
  - Notepad: scanning a barcode adds the correct text and a new line
  - other programs recognize the correct input barcode
- Running in release mode yields the same problem ✅ 

### Steps to Reproduce

1. dotnet new maui -n maui-scanned-entry
2. In MainPage.xaml 
``` xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="maui_barcode_entry_test.MainPage">

    <ScrollView>
        <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            VerticalOptions="Center">

            <Entry
                WidthRequest="500"
                HorizontalOptions="Center" 
                Keyboard="Plain"
                Completed="Entry_Completed"                
                />


        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```
3. In MainPage.xaml.cs
``` csharp
public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}

	private void Entry_Completed(object sender, EventArgs e)
	{
		Entry entry = sender as Entry;
		Trace.WriteLine("Scanned: " + entry.Text);
		entry.Text = "";

	}
}
```
4. Start project and put focus on Entry
5. Scan a barcode in Symbol scanner
6. Verify that the trace line is "Scanned:" but the Entry control has text
7. 
![image](https://user-images.githubusercontent.com/1674884/195595864-a4506716-1657-40b5-a546-f3c511e1d18d.png)

### Link to public reproduction project repository

https://github.com/ruimgoncalves/maui-barcode-entry-test

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

.NET v7.0.100-rc.2.22477.23

**Comment by PureWeen** [comment]
@ruimgoncalves if you change the field to an editor with multi-line can you tell if it's sending an enter key at the beginning of the entry as well?

**Comment by ruimgoncalves** [comment]
The enter key is only being sent at the end, and the Completed event is only triggered when the control loses focus, witch I guess is fine.

![image](https://user-images.githubusercontent.com/1674884/195828377-6f9078ad-ecc9-411c-8666-5b556275db73.png)

**Comment by pulmuone** [comment]
There are too many entry bugs in MAUI. Microsoft should have released MAUI as a GA in 2025.

**Comment by jstedfast** [comment]
How can I reproduce this? I don't know how to perform step 3:

> 3. Scan a barcode in Symbol scanner

**Comment by jstedfast** [comment]
I modified the sample to add a button that sets the Entry.Text value to a string ending with "\r\n".

The result is that the Entry.Text value will end up without the "\r\n" and the Completed event will not fire (probably because the Windows code only emits Completed if it intercepts an Enter key-up event, which, of course, does not happen).

I suspect the barcode scanner does the same as my button?

**Comment by immobilia** [comment]
Is it solved in .NET 8? We have same issue.

**Comment by jupagose** [comment]
Same here but in some machines, another ones works fine
