### ISSUE TITLE
MAUI App Windows App - Mouse movement reversed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#10675]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-App-Windows-App---Mouse-movement-re/10149378)._

---
[severity:I'm unable to use this version]
When running a MAUI app in Windows it seems to horizontally reverse the location of the mouse. For example, mousing to the top right corner to close the window does nothing. But moving to the top left corner does close the window.
I've made two recordings of this behavior and uploaded to YouTube at:
https://www.youtube.com/watch?v=ilEvyJcKaR4
https://www.youtube.com/watch?v=GEBHs-_D8KI
Which show this strange behavior

There is no issue when running in Android

I suspect it has to do with having Hebrew (an RTL language on my computer)

I've tried it on 3 seperate computers. Two running Windows 10 and one running Windows 11

---
#### Feedback Bot on 9/15/2022, 07:40 PM: 

(private comment, text removed)
#### Sigma Li (CSI Interfusion Inc) [MSFT] on 9/20/2022, 01:02 AM: 

(private comment, text removed)
#### Rayven IOT on 9/20/2022, 03:53 AM: 

(private comment, text removed)
#### Feedback Bot on 9/21/2022, 10:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by theadin** [comment]
Hello, I posted the original ticket Developer Community.

Just Want to add the Windows settings needed to reproduce the issue here:
![image](https://user-images.githubusercontent.com/46445608/195805244-86b24a8b-74b0-41f0-82dc-59d2db9fbd21.png)

Cheers
