### ISSUE TITLE
XAML Hot Reload fails with TypeConverter for RowDefinitionCollection error

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#10679]
### Description

I'm unable to use XAML Hot Reload on this page. I'm running RC2 and VS main.

![image](https://user-images.githubusercontent.com/41873/195717286-ede36199-49cd-43f3-a8fb-d83e18f03858.png)

### Steps to Reproduce

OrdersPage.xaml

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/Apps/PointOfSale/src/PointOfSale

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

latest

**Comment by SophisticatedConsulting** [comment]
I also have this problem and it is a big pain to debug as many pages have grids with column/row definitions.
17.4 Preview 2.1

**Comment by drasticactions** [comment]
@davidortinau Does RowDefinitionCollection support converting from a string? Does it work if you try that from C# Code Behind setting that value?

The error is correct if it doesn't support converting from a string. If you can't change those values from code behind, it also won't work.

This error is thrown in the [Markup Extension Parser](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/Xaml/Shared/Source/Markup/Markup/XamlParser/MarkupExtensionParser.cs&version=GBmain&line=634&lineEnd=634&lineStartColumn=25&lineEndColumn=131&lineStyle=plain&_a=contents). It's not hitting the XAML Hot Reload agents.

CC @mgoertz-msft @chabiss as you may know about the underlying code.

**Comment by etvorun** [comment]
https://github.com/dotnet/maui/pull/9447 is needed for MAUI v6. Currently it is available in 7.0.0-rc.1 only
