### ISSUE TITLE
Japanese Hiragana to Kanji converting not works in Searchbar Android

### ISSUE THREAD

**Issue by atsukur** [dotnet/maui#10683]
### Description

In Android, after entering Japanese hiragana into the SearchBar control, it cannot be converted to kanji.
Hiragana input is immediately confirmed.

### Steps to Reproduce

1. Clone [my repo](https://github.com/atsukur/MauiSearchTextJapaneseInputIssue
) or Create Maui App and add Searchbar control.
2. Add Japanese software keyboard in Gboard
3. Enter hiragana in the Searchbar (e.g., "あさ")

Please refer to the following video for Japanese input.

https://user-images.githubusercontent.com/69294861/195769783-bbaa6ecd-932a-454b-88b3-bcd547778389.mp4

### Link to public reproduction project repository

https://github.com/atsukur/MauiSearchTextJapaneseInputIssue

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 Emulator

**Comment by drasticactions** [comment]
https://user-images.githubusercontent.com/898335/195969714-e90b14a8-cd5d-4609-9b17-1e92983f9ff7.mov

I don't think it's specific to Hiragana -> Kanji. There may be other cases where the type ahead results for other languages that use the multiple level control that the Kanji uses would also cause it to cancel. I'm not sure if this is specific to GBoard, MAUIs implementation of the search bar, or the search bar in Android itself.

@rachelkang I think someone on the MAUI team can look at this, you don't need to understand Japanese to debug it nor does your device or emulator need to be in Japanese to replicate it. I would first look at the base control used for the search bar to see if it shows the same behavior outside of MAUI and in Android, and to try other keyboards to see how they work.
