### ISSUE TITLE
Crash on startup with XCode 14 / iOS 16

### ISSUE THREAD

**Issue by SirMangler** [dotnet/maui#10705]
### Description

Using _Visual Studio 2022 for Mac version 17.4 Preview_ with XCode 14.0.0 14A309 (also 14.0.1), running an app in the iOS simulator will result in an instant crash, directly after the splash screen is shown.

I first noticed this issue on 17.3 w/ XCode 13.4.1 when submitting my app to App Store Connect, where they reported [the app that was built for 15.5 crashed on launch on iOS 16.0.3](https://github.com/dotnet/maui/files/9792772/appstore-crash-log.txt). The app worked fine a week ago, and only minor changes to a specific page were made in this update. 

Updating to VS 17.4, and XCode 14.0.1 to try build and test for iOS 16 gave me the same result.  

This happened *regardless* of whether I used net6.0 or net7.0. My original project was based on net6.0, upgrading to net7.0 made no change, building the template with either made no difference.

Mac Console output of a blank project running in an iOS 16 simulator:
![image](https://user-images.githubusercontent.com/4237834/196001328-91e42833-f45e-49dd-a132-ee2a9623a227.png)

I really need to publish my app. Building on VS17.3 with XCode 13.4.1 for iOS **15.5** crashes on a iOS **16.0** simulator, but _not_ on an iOS **15.5** simulator. However, building with XCode 14 on VS17.4 _does_ crash on **15.5**

### Steps to Reproduce

1. Install XCode 14.0.0
2. Install Visual Studio 17.4 Preview
3. Create a new MAUI Project
4. Build for Generic iOS Device (simulators aren't available?)
5. Install App onto simulator and start app

### Link to public reproduction project repository

.NET MAUI App (Template in Visual Studio 17.4 Preview)

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5, iOS 16, net6.0, net7.0

### Did you find any workaround?

No. My project has been completely stalled by this.

### Relevant log output

```shell
Scene FBSceneManager/sceneID:com.companyname.mauitest-default update failed: <NSError: 0x600001230030; domain: FBSceneErrorDomain; code: 1 (operation-failed); reason: "Scene update failed."> {
    NSUnderlyingError = <NSError: 0x60000121b360; domain: FBWorkspaceScene; code: 1; reason: "Client process exited.">;
}
```

**Comment by drasticactions** [comment]
Did you try building and running a net6/net7 iOS app (`dotnet new ios`) that doesn't use MAUI? Does it still crash?

If you don't see simulators, then your VSMac build probably old. Both the SDKs, the IDE, and Xcode have to be in sync for it to not crash. Most likely you could have hit some unrelated crash, then upgraded Xcode without updating the underlying runtimes or IDE, causing everything to be out of sync.

**Comment by SirMangler** [comment]
> Did you try building and running a net6/net7 iOS app (dotnet new ios) that doesn't use MAUI? Does it still crash?

Yes, it still crashed.

> If you don't see simulators, then your VSMac build is probably old.

I installed the 17.4 preview and then XCode 14, the updater shows 'Up to date'. Perhaps I missed a step? Is there another thing I need to do to make sure my binaries are up to date? If it makes any difference, I'm also running on the latest Mac OS version (as of yesterday).

![image](https://user-images.githubusercontent.com/4237834/196033149-2ff5926a-1884-4217-b658-2d71016fbd03.png)

**Comment by vhugogarcia** [comment]
Thanks @SirMangler for reporting this issue. I am also facing the same issue, the ios app crash on startup and there are not logs anywhere that indicate the crash 💥.

**Comment by drasticactions** [comment]
> > Did you try building and running a net6/net7 iOS app (dotnet new ios) that doesn't use MAUI? Does it still crash?
> 
> Yes, it still crashed.

Then this is an SDK / IDE issue, not a MAUI (The UI Framework) one.

@rolfbjarne @dalexsoto Are there good ways to debug this? Is this a platform / IDE issue?

**Comment by rolfbjarne** [comment]
This is the problem:

> Build for Generic iOS Device (simulators aren't available?)
> Install App onto simulator and start app

A project built for device won't run in the simulator. Did you install the app using the IDE, or did you copy it manually?

**Comment by SirMangler** [comment]
> 

I copied it manually, I also found extracting the published build would also crash.

Do you have any ideas on what I could do to fix this? I have reinstalled both VS and Xcode twice. At this point I really only need to create a build that works on iOS 16.

**Comment by SirMangler** [comment]
> @SirMangler do you have a device you can use for development instead?

Not currently.

**Comment by rolfbjarne** [comment]
@SirMangler can you provide your full version information (by clicking on the Show Details button in your screenshot here: https://github.com/dotnet/maui/issues/10705#issuecomment-1279951913)?

**Comment by jovanmhn** [comment]
I can confirm the same behaviour with VS for Windows (17.3.6) with a paired Mac Xcode 14, on a iOS 16 simulator.
Splash screen followed by crash, tested with a default hello world app as well

**Comment by stcmz** [comment]
Same here with VS for Windows (17.3.6) with a paired Mac Xcode 14. Have reinstalled Xcode/VS/mono and cleaned up preferences/project-objects/caches for a dozen times and tried two Windows PC and two Macs in the last two days. Even the blank iOS app cannot be installed into the simulator. Wait until the simulator recovers from crash, then hit Run in VS will make the simulator crash again. No relevant logs can be found.

**Comment by rolfbjarne** [comment]
Can anybody who can reproduce this with VSMac provide the full version information as requested here: https://github.com/dotnet/maui/issues/10705#issuecomment-1281939359?

**Comment by vhugogarcia** [comment]
Hello @SirMangler,

The issue is fixed at least for me on the last Visual Studio for Mac 2022 update along with the dotnet maui released support for XCode 14. Please find below the settings I have:

> Visual Studio Community 2022 for Mac Preview 4.0
> Version 17.4 Preview (17.4 build 2326)

> .NET SDK (Arm64)
> SDK: /usr/local/share/dotnet/sdk/7.0.100-rc.2.22477.23/Sdks
> SDK Versions:
> 	7.0.100-rc.2.22477.23
> 	6.0.402

> .NET Runtime (Arm64)
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Versions:
> 	7.0.0-rc.2.22472.3
> 	6.0.10

> Xamarin.iOS
> Version: 16.0.0.72

> XCode 14.0.1
> macOS Monterey

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1047398/196956480-493e364c-9467-49a5-b279-3819885ebdc4.png">

The app does not crash anymore on my side. I hope the information above helps others to solve the issue.

Thanks all for the help! :)
