### ISSUE TITLE
FlexLayout completely broken...

### ISSUE THREAD

**Issue by StewBash** [dotnet/maui#10717]
Numerous issues:

BindableLayout.ItemTemplate -- does not render on Android or Windows.

BindableLayout.ItemTemplate -- Will not scroll content... adding <ScrollView> to stacklayout makes no difference.

In Xamarin Forms app I have a "grouped" display that uses Horizontal Scrolling CarouselView that binds to a Grouped Observable Object. In the MAUI conversion app the CarouselView Binds properly, and there is a child "FlexLayout" where I need a vertically scrollable list of Cards. The "FlexLayout" appears not to work properly as a child or a parent in any scenario.

**Comment by drasticactions** [comment]
You should make separate issues for each of these with reproduction steps.
