### ISSUE TITLE
Border Clipping Issue in [iOS & macOS]

### ISSUE THREAD

**Issue by Ahamed-Ali** [dotnet/maui#10724]
### Description

Images are not Clipped correctly as expected in iOS and macOS

**iOS**
![image](https://user-images.githubusercontent.com/102580874/196105896-56741c91-bbe0-425e-b277-59ce222c891b.png)

**macOS**
![image](https://user-images.githubusercontent.com/102580874/196105961-e91afb88-1462-4976-9c47-feed6bbad7a0.png)

### Steps to Reproduce
` <Border VerticalOptions="Center" HorizontalOptions="Center" HeightRequest="100" WidthRequest="100" Stroke="red" StrokeThickness="4">
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="50"/>
            </Border.StrokeShape>
            <Border.Content>
                <Grid>
                    <Image Source="avatar1.png" Aspect="AspectFill"  />
                </Grid>
            </Border.Content>
        </Border>`

The below repository contains the sample

### Link to public reproduction project repository

https://github.com/Ahamed-Ali/AvatarView/tree/main

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iPhone 13 Pro Max(iOS 15.5) & Mac Catalyst-15.4.454

### Did you find any workaround?

NA

### Relevant log output

```shell
NA
```

**Comment by ertandk** [comment]
I am having this problem too. Has it been edited? I couldn't see. Will it be fixed in the next update?
Thanks.
