### ISSUE TITLE
Issue was closed without proper reading or understanding the issue

### ISSUE THREAD

**Issue by juwens** [dotnet/maui#10720]
### Description

https://github.com/dotnet/maui/issues/10654

### Steps to Reproduce

https://github.com/dotnet/maui/issues/10654

### Link to public reproduction project repository

https://github.com/dotnet/maui/issues/10654

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

See issur

**Comment by drasticactions** [comment]
I agree, reopening that issue.

**Comment by samhouts** [comment]
Duplicate of #10654
