### ISSUE TITLE
Picker PlatformSpecific (UpdateMode) - Does not work

### ISSUE THREAD

**Issue by MarMarIV** [dotnet/maui#10722]
### Description

On iOS platform, `PlatformSpecific` for `Picker` does not work

### Steps to Reproduce

Set on Picker

`ios:Picker.UpdateMode="WhenFinished"`

Expected: When selecting date by wheel pickers, date should not be set, unitl i tap on 'Done' button

Actual: When selecting date by wheel pickers, date is immediately set

### Link to public reproduction project repository

https://github.com/MarMarIV/Maui_IosPickerUpdateMode

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.3.1

### Did you find any workaround?

No

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on iOS platform with sample project. 
[Maui_IosPickerUpdateMode-master.zip](https://github.com/dotnet/maui/files/11595338/Maui_IosPickerUpdateMode-master.zip)
![10722](https://github.com/dotnet/maui/assets/77434865/b54c5f87-1bbb-439c-8b11-3023838cbb38)

**Comment by jfversluis** [comment]
According to #5856 it should be implemented now
