### ISSUE TITLE
Android Emulator UTF8 Binding and Accent Support [Localization]

### ISSUE THREAD

**Issue by whann0205** [dotnet/maui#10723]
### Description

Want to enter Accents öäüß in a text input field and get that value 
correctly in a variable. 
Works perfectly with my android device (german samsung S10) but
not with the Android emulator although i have changed all
settings i know to german, but to no avail.
See what happens in the screenshots below.
I know it should be possible to make that work. 
In addition i fear when i deploy the app and someone lets say from 
england use the app will probably not wanting to change his phone to german/germany or
something like that.

![Counter1](https://user-images.githubusercontent.com/71807453/196103084-aae4d248-1bd7-4461-8892-af6014a03f48.png)
![Counter2](https://user-images.githubusercontent.com/71807453/196103087-0059eed2-6cca-46cd-b874-e173d49e6bf2.png)

### Steps to Reproduce

1. Create a new project - Choose net maui blazor as target
2. Edit the Counter.razor and insert a new control as described 
in https://learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-6.0
or simply create any inputtext .
3. Enter a string containing öäüß 
4. Press tab and you see the accents disappear

### Link to public reproduction project repository

NoRepository

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.1 API 32 Emulator

### Did you find any workaround?

No

**Comment by TanayParikh** [comment]
Hey @whann0205, thanks for reaching out. 

Can you please confirm if this issue reproduces on a base .NET MAUI WebView **without** Blazor?

**Comment by whann0205** [comment]
@TanayParikh 
I have never worked with .net maui without blazor, so its a new thing for me.
Maybe you can help me out and try that thing - you are probably much faster?

**Comment by whann0205** [comment]
![mytasks1](https://user-images.githubusercontent.com/71807453/196441905-02f94ce7-420c-4557-b9ad-7ae06bf1cf99.png)
I downloaded maui-samples Beginners-Series/MauiApp2 and entered some characters as with that
application on the same emulator. 
As everybody can see it works there, so it might be a blazor related problem?
Again i must point out that the problem does not exist on my local android phone or 
when i use the iphone simulator.
Is Nobody else experiencing that problem?

**Comment by TanayParikh** [comment]
I wonder if this is a font issue? Is this an issue specifically within the `input` content or regular HTML text also has this issue?

Details on using the .NET MAUI WebView are available here: https://learn.microsoft.com/dotnet/maui/user-interface/controls/webview

**Comment by whann0205** [comment]
What do you want me to try?
The font being used by net maui blazor is defined by the source or not?
Maybe the font installed on the emulator lacks displaying accents?

**Comment by TanayParikh** [comment]
> Is this an issue specifically within the `input` content or regular HTML text also has this issue?
> What do you want me to try?

Can you try updating the `Counter` title and `Current count` text to be `Counter öäüß` and `Current count öäüß`. Does that show up as expected.

Also, is the textbox value bind'ed to a variable? If so, is the value correct in the variable? If so, this definitely indicates a font issue.

 > The font being used by net maui blazor is defined by the source or not?

I think we may just use system defaults. This would explain why it's working on your physical device (which likely had a wide font library) and not necessarily in the emulator. 

> Maybe the font installed on the emulator lacks displaying accents?

Exactly! You can try using a custom WebFont and see if that renders the accents correctly.

**Comment by whann0205** [comment]
![TestAppText112022](https://user-images.githubusercontent.com/71807453/200486549-9ce79f55-ba3b-4b28-961a-a75c571a0248.png)

I have updated the Counter title and CurrentCount Text and it shows as excepted.

![TestAppText112022_2](https://user-images.githubusercontent.com/71807453/200486757-33ad8b17-ff32-4e3d-acdb-da2487ef7bb4.png)
The Textbox is binded to a variable and i typed in "Möbel". 
The variable gets the following value: "M\ufff6bel"

>Exactly! You can try using a custom WebFont and see if that renders the accents correctly.
Whats the best and easiest way to use a custom webfont on the control?

**Comment by TanayParikh** [comment]
Hmm I'm seeing the correct text in the stored value when I use Windows:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/14852843/200976239-117a853b-338f-4230-a38b-e4bfe16528cc.png">

as well as the correct value in the textbox:

<img width="994" alt="image" src="https://user-images.githubusercontent.com/14852843/200976291-aac4ebd3-d1fb-4ac2-b4e0-97fce9f4c00d.png">

I believe you're running into a bit of an edge case given you have this scenario specifically in the Android emulator. Unless this is impacting production apps, I'm inclined to keep this issue in the backlog. We'll asses additional user feedback as it comes in, to reprioritize the issue as necessary.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on android, windows and iOS platform with sample code.
Windows:
![Screenshot 2023-07-14 112536](https://github.com/dotnet/maui/assets/77434865/0d5420d4-e207-498c-bfd1-179500132516)
Android:
![Screenshot 2023-07-14 112654](https://github.com/dotnet/maui/assets/77434865/f12fb3c5-7b4b-42ec-bafe-b3b153a8c902)
iOS:
![Screenshot 2023-07-14 113603](https://github.com/dotnet/maui/assets/77434865/794c6f48-f575-4291-a258-78a782031281)
