### ISSUE TITLE
Text alignment not respected in migrated project

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#10728]
### Description

In a project that was migrated from Xamarin.Forms, the TextAlignments (HorizontalTextAlignment and VerticalTextAlignment) are not respected. 
![image](https://user-images.githubusercontent.com/114725843/196125024-a9013e34-7864-43d2-b812-16fb52b366cf.png)
![image](https://user-images.githubusercontent.com/114725843/196125157-d8abeba7-e065-40f6-ac5a-6e2b222e90ba.png)

This kind of bug has already been reported (https://github.com/dotnet/maui/issues/1509), and it does not happen in an empty MAUI Project, but it still seems to happen in migrated projects. I also encountered this bug in a project I migrated to MAUI by dragging the old files into a fresh MAUI project (I cannot share code, as it's enterprise code).

### Steps to Reproduce

1. Migrate a Xamarin.Forms project as described here: https://github.com/dotnet/maui/wiki/Migrating-from-Xamarin.Forms-(Preview)
2. Create a Label with HorizontalOptions = Fill and HorizontalTextAlignment = "Center" or "End"
3. The Label will still be leftaligned (as with HorizontalTextAlignment = "Start")

### Link to public reproduction project repository

https://github.com/owl-guy/LabelAlignmentExample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 30 and up

**Comment by rmarinho** [comment]
Can you check if it works if it's inside a Layout like `Grid` for example? 

Thanks

**Comment by jsuarezruiz** [comment]
Tested with latest version and current main branch where the alignment is working as expected.
![image](https://user-images.githubusercontent.com/6755973/197507494-55f2af9b-723a-45fb-bf36-d53e19d30471.png)

What version are you using?, could you test again with the latest version (net7 rc2)?

**Comment by owl-guy** [comment]
@jsuarezruiz 
![image](https://user-images.githubusercontent.com/114725843/197514151-b367495a-d49f-4ee8-8828-bd3eec866ec5.png)
This is my output for "dotnet workload list", so I guess I'm using .NET 6.0.400? Do I really have to upgrade to .NET 7? The corresponding VS version is still in preview, and our department does not work with preview versions. Can't there be a fix for .NET 6?

**Comment by owl-guy** [comment]
Still happens with the latest stable version of .NET 7 (7.0.100). when I start LabelAlignmentExampleMigrated.Android, the text is still leftaligned.

**Comment by samhouts** [comment]
Duplicate of #11251
