### ISSUE TITLE
Dynamic Resource TextColor of Label didn't update when the theme changes in Mac

### ISSUE THREAD

**Issue by EwaldJebaraj** [dotnet/maui#10738]
### Description

When I update 'PrimaryTextColor' at runtime due to a Theme change, the TextColor of the Label didn't get changed in Mac. Working fine for Windows

### Steps to Reproduce

1. Run the sample
2. Change the Theme of the system
3. The Label Text Color will not change

### Link to public reproduction project repository

https://github.com/EwaldJebaraj/LabelThemeIssue

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Above 10

**Comment by PureWeen** [comment]
@StephaneDelcroix

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.3 (build 421). Not repro on macOS platform with sample project.
[LabelThemeIssue-main.zip](https://github.com/dotnet/maui/files/12394634/LabelThemeIssue-main.zip)
![Screenshot 2023-08-21 173855](https://github.com/dotnet/maui/assets/77434865/ea72cae5-ede9-4b1c-85ee-53e16953dbaf)
![Screenshot 2023-08-21 173919](https://github.com/dotnet/maui/assets/77434865/8222fe88-b3aa-4517-98fa-83a95fe83a05)
