### ISSUE TITLE
[iOS] Crash when debugging with Hot Reload on local iPhone device after the splash screen disappear

### ISSUE THREAD

**Issue by vg12345** [dotnet/maui#10737]
### Description

App crash when I debug it on my local iPhone device. The splash screen is fine but then the App crash.
The App does NOT crash if runs in normal mode (not debugging).
I tried many times, and the crash happens constantly. 
I tried all three "Linker behavior" options - Don't link, SDKs only and All.

Windows 11 Desktop
Visual Studio 17.3.6
iPhone device with iOS 15.6.1

### Steps to Reproduce

Create a File > New .NET MAUI App
Make no changes
Connect up local iPhone device with Hot Reload
Click 'Debug' button
Deploy process is OK
App startup and the splash screen appears
Splash screen fade out and at this moment the App crashes

### Version with bug

6.0.541 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.6.1

### Relevant log output

Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/Microsoft.iOS.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Collections.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.InteropServices.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Threading.Thread.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Threading.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.Http.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Numerics.Vectors.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.Sockets.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Drawing.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Private.Uri.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/Xamarin.PreBuilt.iOS.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/Xamarin.iOS.HotRestart.Application.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/netstandard.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.IO.MemoryMappedFiles.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.IO.Pipes.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Memory.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Diagnostics.Tracing.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Collections.NonGeneric.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/Microsoft.Win32.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.NameResolution.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Threading.ThreadPool.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.CompilerServices.Unsafe.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Collections.Concurrent.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.InteropServices.RuntimeInformation.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Diagnostics.Process.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.ComponentModel.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.ComponentModel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.ObjectModel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Diagnostics.FileVersionInfo.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Reflection.Metadata.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Collections.Immutable.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Linq.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.IO.Compression.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Text.Encoding.Extensions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Collections.Specialized.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Security.Cryptography.X509Certificates.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Security.Cryptography.Algorithms.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Security.Cryptography.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Formats.Asn1.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.Numerics.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Security.Cryptography.Encoding.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.ComponentModel.TypeConverter.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.Loader.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.Security.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Security.Claims.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Text.RegularExpressions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Reflection.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.Serialization.Formatters.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Resources.Writer.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Xml.XDocument.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Private.Xml.Linq.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Private.Xml.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Diagnostics.TraceSource.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Diagnostics.DiagnosticSource.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.Quic.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.IO.Compression.Brotli.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Threading.Channels.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.NetworkInformation.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Reflection.Emit.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Linq.Expressions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.ComponentModel.EventBasedAsync.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Console.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Data.Common.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Xml.XmlSerializer.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Transactions.Local.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Diagnostics.Contracts.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Diagnostics.TextWriterTraceListener.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Diagnostics.StackTrace.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.IO.Compression.ZipFile.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.IO.FileSystem.DriveInfo.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.IO.FileSystem.Watcher.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.IO.IsolatedStorage.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Linq.Queryable.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Linq.Parallel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.Requests.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.WebHeaderCollection.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.ServicePoint.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.HttpListener.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.WebSockets.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Security.Principal.Windows.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.WebClient.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.WebProxy.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.Mail.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.Ping.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Net.WebSockets.Client.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Reflection.DispatchProxy.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.CompilerServices.VisualC.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.Serialization.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.Serialization.Xml.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Private.DataContractSerialization.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Runtime.Serialization.Json.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Security.Cryptography.Csp.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Threading.Overlapped.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Threading.Tasks.Parallel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Web.HttpUtility.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Xml.XPath.XDocument.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Xml.XPath.dll [External]
Thread started:  #2
Thread started: .NET Timers #3
2022-10-17 16:18:20.138 Xamarin.PreBuilt.iOS[33710:11619693] Content folder: /var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content

2022-10-17 16:18:20.142 Xamarin.PreBuilt.iOS[33710:11619693] App path /var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/MauiApp9.dll

Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/MauiApp9.dll
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Maui.Controls.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Maui.dll [External]
2022-10-17 16:18:20.157 Xamarin.PreBuilt.iOS[33710:11619693] AppDelegate name: AppDelegate

Thread started: <Thread Pool> #4
Thread started: .NET ThreadPool Gate #5
Thread started: <Thread Pool> #6
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Maui.Controls.Compatibility.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Extensions.Logging.Abstractions.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Extensions.Options.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Maui.Controls.Xaml.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Extensions.Primitives.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /private/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.Extensions.DependencyInjection.dll [External]
Resolved pending breakpoint for 'MauiApp9.Program.Main(System.String[])' to D:\Test\MauiApp9\Platforms\iOS\Program.cs:10 [0x00000].
Loaded assembly: data-0x10f720000 [External]
Loaded assembly: data-0x10f73c000 [External]
Loaded assembly: data-0x10d800000 [External]
Loaded assembly: data-0x10d850000 [External]
Loaded assembly: data-0x10d860000 [External]
2022-10-17 16:18:20.574 Xamarin.PreBuilt.iOS[33710:11619693] Could not resolve assembly Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.VisualStudio.DesignTools.TapContract.dll' or one of its dependencies.

2022-10-17 16:18:20.578 Xamarin.PreBuilt.iOS[33710:11619693] Could not resolve assembly Xamarin.HotReload.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Xamarin.HotReload.Contracts.dll' or one of its dependencies.

Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:419 [0x00000].
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Text.Json.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/AD411899-07F1-47CE-BD33-CE3AA1C418DE/MauiApp9.app/System.Text.Encodings.Web.dll [External]
2022-10-17 16:18:20.693 Xamarin.PreBuilt.iOS[33710:11619693] Could not resolve assembly Xamarin.HotReload.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Xamarin.HotReload.Contracts.dll' or one of its dependencies.

2022-10-17 16:18:20.695 Xamarin.PreBuilt.iOS[33710:11619693] Could not resolve assembly Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/37A574DB-BCC1-470C-9104-86F35CD5FC71/Documents/MauiApp9.content/Microsoft.VisualStudio.DesignTools.TapContract.dll' or one of its dependencies.

Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:414 [0x00000].
Thread started: <Thread Pool> #7
The app has been terminated.

**Comment by drasticactions** [comment]
FYI those log messages are, most likely, a red herring. They will show before the assemblies load from the app cache. More likely, this will be a Xamarin Hot Restart bug, since you're running this from Visual Studio on Windows.
