### ISSUE TITLE
[Bug] UWP Backward Navigation shows "B" page's TitleView content when ScrollView is in "A" page's TitleView

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/maui#1073]
**Description**
    The below Issue was reported since Xamarin 4. In many scenarios, we need to put a horizontal ScrollView in TitleView and navigation between pages back and forth, when navigating back, the TitleView doesn't get loaded normally (occasionally, weird). I'm wondering if this issue will ever be solved. 
I made a simple demo project as attachment to this bug report.
[ScrollViewInTitleViewNavigation.zip](https://github.com/dotnet/maui/files/6527575/ScrollViewInTitleViewNavigation.zip)

Below are details:
    If "A" page's TitleView contains a ScrollView, when navigating from page "A" to "B", the "B"'s TitleView content is shown. However, if we navigate back by pushing back button, the page "A" doesn't get its TitleView loaded. Instead, it shows page "A"'s content and page "B"'s TitleView.

**Steps to Reproduce**
Create page "A" and "B" in a Navigation-style App project.
For page "A"'s TitleView, add a ScrollView and some controls within it.
For page "B"'s TitleView, add some controls within it.
Add a button to navigate from "A" to "B".
Build and run, navigate from "A" to "B", then navigate back. See if the TitleView is normally loaded.

**Expected Behavior**
When navigating back from "B" to "A", "A"'s TitleView should be loaded.

**Actual Behavior**
"B"'s TitleView is still there.

**Basic Information**
Version with issue: All recent Xamarin.Forms/Maui version, including latest pre-release.
Last known good version: None.
IDE: Visual Studio 2019 16.10.0
Platform Target Frameworks:
UWP: All recent Windows SDK versions, including latest pre-release.
Nuget Packages: Xamarin.Forms 5.0.2012.
Affected Devices: Only UWP.
Workaround: Not known.

Thanks a lot.

Best Regards

**Comment by VincentBu** [comment]
repro on windows, if the TitleView doesn't get loaded normally after pushing back button, we need to click the back button again.

**Comment by PureWeen** [comment]
The `TitleView` code has been reworked for RC1

If this is still an issue when RC1 releases please create a new issue
