### ISSUE TITLE
Window.Height is -1 in Page_loaded() in Android Maui.

### ISSUE THREAD

**Issue by bymin** [dotnet/maui#10747]
### Description

Create a new ContentPage and hookup the Page_loaded event. You will see this.Width equals to -1 in Page_loaded() if running on an Android Emulator. The same code works fine (this.Width returns the actual width) on Windows.

It has the same issue for a ContentView as well.

### Steps to Reproduce

1. Create a new ".NET MAUI App" project in Visual Studio 2022 (17.3.4)
2. Hook up the Loaded event in Xaml
`<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="MauiApp1.MainPage" Loaded="MainPage_OnLoaded">`
and C#
`private void MainPage_OnLoaded(object sender, EventArgs e) { var width = this.Width; }`

3. Run the project. The with equals -1 if running on Android. It doesn't have an issue if running on Windows.

### Link to public reproduction project repository

https://github.com/bymin/RecreateMauiIssue.git

### Version with bug

7.0 Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Emulator -pixel_5 - api 30

### Did you find any workaround?

I can get the correct Width/Height in OnSizeChanged events. Also, I found OnSizeChanged event was raised before OnLoaded on Windows, but after OnLoaded on Android, that's probably why it is correct on Windows but incorrect on Android.

**Comment by PureWeen** [comment]
Loaded only indicates that an element has joined the main object tree. It's not a reliable place for size information. 

I've updated our API docs here
https://github.com/dotnet/maui/pull/10785/files#diff-f2b62907ed76d74de34a8cad8da91c66e34f43ac3a63a7eb871618cabd70d365R341-R381

To help guide future users
