### ISSUE TITLE
Publishing iOS MAUI App in Devops

### ISSUE THREAD

**Issue by Zack158** [dotnet/maui#10742]
### Description

On Azure Devops Pipelines we are trying to publish an iOS app built in MAUI which references a .NET6.0 class library. 

The issue is that we cannot figure out how to get the pipeline working with MAUI (We have it working with xamarin fine).

We get the error "A runtime identifier must be specified in order to publish this project" so when we enter this as a property group in the csproj file it says it can't find the codeSignKey etc in the keystore even though we have installed the Apple certificates as one of the first tasks.

We have created the distribution certificate and profile and put these in Azure secure storage.

Here is the project and the pipeline code that tries to build and publish the artefacts.
(AppleCertificateP12 and AppleProvisioningProfile are saved in the Pipelines Library secure files)

https://github.com/Zack158/MAUIiOSDevops

### Steps to Reproduce

1. Create empty iOS MAUI solution that references a class library
2. Create relevant apple signing certificates and distribution profiles
3. Add project to azure repos and create the pipleine to publish it
4. See the error

### Link to public reproduction project repository

https://github.com/Zack158/MAUIiOSDevops

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Relevant log output

```shell
Starting: Build iOS App
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash /Users/runner/work/_temp/c2593526-b420-405c-a502-db8466b7b025.sh
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/15.4.402/targets/Xamarin.Shared.Sdk.Publish.targets(16,3): error : A runtime identifier must be specified in order to publish this project. [/Users/runner/work/1/s/EmptyOne/src/MauiAppEmpty/MauiAppEmpty.csproj]

Workload updates are available. Run `dotnet workload list` for more information.
##[error]Bash exited with code '1'.
Finishing: Build iOS App
```

**Comment by KSemenenko** [comment]
Try to remove 
dotnet workload install maui
 **--sourcehttps://aka.ms/dotnet6/nuget/index.json**

you no need custom workload anymore.
Also increase dot net version to **6.0.402**
