### ISSUE TITLE
When the flow direction is changed in ScrollView as RTL, the scrolling direction remains unchanged in iOS and macOS

### ISSUE THREAD

**Issue by anandhan-rajagopal** [dotnet/maui#10755]
### Description

Change the flow direction as RTL in ScrollView, but the scrolling direction remains unchanged in iOS and macOS platforms. 

### Steps to Reproduce

1. Run the sample on the iOS and macOS platform
2. We have to scroll from the left to the right direction to see the children which are arranged based on RTL flow direction.

### Link to the public reproduction project repository

https://github.com/anandhan-rajagopal/ScrollView_Issue

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 10 Above, macOS 10.15 above

**Comment by PureWeen** [comment]
Can you try Public Preview? There were a lot of RTL changes put into .NET 7.0 Rc1

**Comment by KarthikRajaKalaimani** [comment]
Hi @PureWeen , 

Still the issue persist in Visual Studio 17.4 preview and .Net version  7.0.0-rc.2.22472.3. I have attached the video for your reference.
[Screen Recording 2022-10-28 at 10.35.46 AM.mov.zip](https://github.com/dotnet/maui/files/9885413/Screen.Recording.2022-10-28.at.10.35.46.AM.mov.zip)

**Comment by PaulAndersonS** [comment]
The issue persist in ios and MacCatalyst also with net7.0.

**Comment by anandhan-rajagopal** [comment]
This issue still persists in the latest public preview, therefore I have reopened this issue. https://github.com/dotnet/maui/issues/11026
