### ISSUE TITLE
[iOS] Issue with binaries builts compiled with VS 2022 and Xcode 14

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#10760]
### Description

I finally was able to publish my MAUI iOS app, however the built got rejected due this issue,
however my app isn't using any of those features.
Or is this new with Xcode 14?

> ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSContactsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources
> 
> ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources
> 
> ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSMicrophoneUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources
> 
> ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSAppleMusicUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources
> 
> ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSSiriUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources
> 
> Though you are not required to fix the following issues, we wanted to make you aware of them:
> 
> ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.
> 
> ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources
> 
> ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSBluetoothAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources

Here is my infp.plist file content

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>de</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>This app needs access to the photo gallery for picking photos for the printer.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app needs access to photos gallery for picking photos for the printer.</string>
	<key>NSCameraUsageDescription</key>
	<string>This app needs access to the camera to take photos of the printer or scan barcodes.</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>XSAppIconAssets</key>
	<string>Assets.xcassets/appicon.appiconset</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0.0</string>
	<key>CFBundleVersion</key>
	<string>1.0.0</string>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoadsInMedia</key>
		<true/>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
	<key>UIFileSharingEnabled</key>
	<true/>
	<key>LSSupportsOpeningDocumentsInPlace</key>
	<true/>
	<key>CFBundleDisplayName</key>
	<string>Stocks Monitor</string>
</dict>
</plist>
```
Entitlements.plist
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.networking.wifi-info</key>
	<true/>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>group.x.shared</string>
	</array>
	<key>com.apple.developer.icloud-container-identifiers</key>
	<array>
		<string>iCloud.com.x</string>
	</array>

	<key>com.apple.developer.ubiquity-kvstore-identifier</key>
	<string>$(AppIdentifierPrefix)$(CFBundleIdentifier)</string>
</dict>
</plist>
```

### Steps to Reproduce

1. Create an app and submit it to the App Store

### Link to public reproduction project repository

https://github.com/

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by mlancione** [comment]
It may not be related but one issue to watch out for when publishing for iPadOS is that Apple is currently rejecting iPad apps built with Xcode14 because iPadOS 16 is not officially released yet.

See: https://developer.apple.com/forums/thread/717275

**Comment by PureWeen** [comment]
@rolfbjarne @dalexsoto thoughts?

**Comment by rolfbjarne** [comment]
Can you attach a [binary build log](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs)?

**Comment by AndreasReitberger** [comment]
@rolfbjarne 
I tried to create the build log, however, somehow I'm not able to build my iOS project in release mode anymore.
It keeps saying that the path is to long, however the build was working fine two days ago (no change to code, only installed this extension.
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022

`
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.0.517\targets\Xamarin.Shared.Sdk.targets(753,3): error MSB3191: Das Verzeichnis "obj/Release/net6.0-ios/ios-arm64//stripped/Microsoft.Maui.Essentials.dllUsers\Andreas\Documents\GitHub\StocksWatchMauiApp\src\StocksWatchApp\obj\Release\net6.0-ios\ios-arm64\linked\" kann nicht erstellt werden. Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.
`
It tries to created a very long folder in the project path.

Github Project:  `C:\Users\Andreas\Documents\GitHub\StocksWatchMauiApp\src\StocksWatchApp` 
Path VS tries to create: `obj/Release/net6.0-ios/ios-arm64//stripped/Microsoft.Maui.Essentials.dll**Users\Andreas\Documents\GitHub\StocksWatchMauiApp\src\StocksWatchApp**\obj\Release\net6.0-ios\ios-arm64\linked\`

Somehow it adds the complete path again, which exceeds the limit of chars for a path...
I try to get the build working again. Any hints?

**Comment by AndreasReitberger** [comment]
Doesn't get it work with VS 2022 anymore, so I installed the preview version again.
With this, I was able to build in release mode again. Then I installed the addon for the build log.
Now it fails again due to a too long file path. So there is a issue with this addon.

Sorry, at the moment I cannot provide the binary log for you... at least not for a successfull build

[StocksWatchMauiApp_Release_AnyCPU_Build_2022-10-21T07_22_49.2979581+02_00.zip](https://github.com/dotnet/maui/files/9835952/StocksWatchMauiApp_Release_AnyCPU_Build_2022-10-21T07_22_49.2979581%2B02_00.zip)

**Comment by rolfbjarne** [comment]
@AndreasReitberger did you disable the linker (set `MtouchLink` to `None` in your project file)?

**Comment by AndreasReitberger** [comment]
@rolfbjarne 
Yes

`<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0-ios|AnyCPU'">
	  <MtouchLink>None</MtouchLink>
	  <DefineConstants>$(DefineConstants)TRACE;AppCenter</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0-ios|AnyCPU'">
	  <MtouchLink>None</MtouchLink>
	  <DefineConstants>$(DefineConstants)TRACE;AppCenter</DefineConstants>
	</PropertyGroup>`

**Comment by rolfbjarne** [comment]
@AndreasReitberger that's the reason: when linking is disabled, your app will include all the bindings we have for all of iOS' API, even those you don't use (because it's the linker that removes API bindings you don't use).

This means that the App Store will detect that you're using these APIs, because they exist in your app.

I see two potential solutions:

a) Add the missing purpose strings to your Info.plist.
b) Enable the linker (using `LinkSdk` instead of `None` should fix this). Was there any particular reason you disabled it?

**Comment by AndreasReitberger** [comment]
I'll try to set the linker back to SdlOnly.

b) 
Yes there was a time (after a VS update), where I wasn't able to built my iOS. The solution was to set the linker to `None`.

I'll try it and report back.
Maybe I'm then able to provide the binary log.

Thanks for the hint!

**Comment by AndreasReitberger** [comment]
Setting back to `LinkSDK` solved the issue.
Thank you for helping out! @rolfbjarne
