### ISSUE TITLE
Page.Width = -1 in Page_Loaded() in Mac Catalyst Maui

### ISSUE THREAD

**Issue by bymin** [dotnet/maui#10763]
### Description

Create a new ContentPage and hookup the Page_OnLoaded and Page_OnSizeChanged event. You will see this.Width equals to -1 in both Page_OnLoaded() and Page_OnSizeChanged events if running on a Mac Catalyst. The same code works fine (this.Width returns the actual width) on Windows, the same code works partially fine (it returns the correct width in OnSizeChanged event but not OnLoaded event, see #10747) on Android, I didn't have a chance to test it on iOS. 

It has the same issue for a ContentView as well.

### Steps to Reproduce

Run the linked repo and you will see 2 exceptions got thrown. One is thrown in OnLoaded event and the other is thrown in SizeChanged event. Neither of the exceptions are thrown if running on Windows, only 1 exception will be thrown on Android. 

### Link to public reproduction project repository

https://github.com/bymin/MauiLayoutIssueOnMac.git

### Version with bug

7.0 Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS 12.6, VS 2022 on Mac Preview 17.4. build 2285, Xcode 14.0.1

### Did you find any workaround?

If you remove the `<Grid></Grid>` from the xaml and put the `<button>` directly under Content page, it will then not throw exception in SizeChanged event, but still throws exception in OnLoaded event.

**Comment by CraigBelser** [comment]
We have this issues as well.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0(.NET8). Can repro on android platform with sample project.
[MauiLayoutIssueOnMac-main.zip](https://github.com/dotnet/maui/files/12394262/MauiLayoutIssueOnMac-main.zip)
![Screenshot 2023-08-21 165958](https://github.com/dotnet/maui/assets/77434865/36e8b53a-e361-41cc-ad9d-c3bba3ee0d48)

**Comment by PureWeen** [comment]
Things won't be guarunteed to be measured in PageLoaded
You need to use SizeChanged
