### ISSUE TITLE
[iOS] White flashy background after splash screen in MAUI Blazor

### ISSUE THREAD

**Issue by mhrastegari** [dotnet/maui#10767]
### Summary
Is there a way to change BlazorWebView's default white background color for iOS? like this one #10629 that I asked for Winui.

### More info
Visual Studio for mac 17.4 pre 4
.Net 6.0.8 SDK
XCode 14.0.1
iOS 16

**Comment by javiercn** [comment]
@mhrastegari thanks for contacting us.

You can use the same mechanism and do **something** like this. For future reference, we expose the underlying webview type via the events described in the referenced issue, so our recommendation is that you search how to do something in the IOS/Android/WinUI webview and try applying the same approach.

```csharp
webView.opaque = NO;
webView.backgroundColor = [UIColor clearColor];
```

**Comment by mhrastegari** [comment]
Thank you so much :)
