### ISSUE TITLE
New MAUI Blazor project should not target IOS by default

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#10766]
### Description

IOS and MacCatalyst get in the way of early development and should not be targeted by default.

For example, after adding a couple of lines I get:

1>CSC : error CS1705: Assembly 'Microsoft.Maui' with identity 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=15.4.300.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

### Steps to Reproduce

Create a new MAUI Blazor App. Note in the project properties that IOS and Android and Windows are targetted.

Add a partial class service to each of the three platforms. IOS will now report an error.

Manually go back to project properties and untarget IOS and proceed with development.

### Link to public reproduction project repository

none

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Windows, Android and IOS

### Did you find any workaround?

Manually untarget IOS

**Comment by javiercn** [comment]
@genifycom thanks for contacting us.

This is not something we plan to do in the near future unless Maui itself changes it. We might offer some options to choose during template creation, but we do not plan to remove support out of the box for any platform.

It is always easier to remove things than to add them back, so this creates an unnecessary cliff for people targeting iOS/Mac. You can always remove the target frameworks from the created project to remove support for the things you do not want.
