### ISSUE TITLE
Java.Lang.IllegalStateException: 'View with id -1: crc640ec207abc449b2ca.ShellPageContainer#onMeasure() did not set the measured dimension by calling setMeasuredDimension()'

### ISSUE THREAD

**Issue by innomarcoItalia** [dotnet/maui#10776]
### Description

Tap on the notification with the app in the foreground as shown in the photo:
![193416466-49e813e1-d740-47aa-8cc3-06cf7d3afccf](https://user-images.githubusercontent.com/20582079/196629287-4f06d4ce-4a15-4a03-a9bc-8367cfc8d19a.png)

NET 7 - RC2

### Steps to Reproduce

1) clone repository
2) configure for your Firebase
3) run app with VS 2022  17.4.0 Preview 4.0
4) send push
5) tap notification

### Link to public reproduction project repository

https://github.com/mistrypragnesh40/PushNotificationDemoMAUI

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 - Android 12

### Relevant log output

```shell
0xFFFFFFFFFFFFFFFF in Android.Runtime.JNIEnv.monodroid_debugger_unhandled_exception	
0x59 in Android.Runtime.JNIEnv.PropagateUncaughtException at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:308,5
```

**Comment by PureWeen** [comment]
@innomarcoItalia when you click the notification do you want it to open a new window? Or do you want it to navigate within the existing app instance?

**Comment by innomarcoItalia** [comment]
... the crash shouldn't occur either way.
It has currently been tested on the existing instance.

**Comment by PureWeen** [comment]
@innomarcoItalia I don't see the launchMode set so I think that will open a new instance.

If you set the `launchMode` to I think 'singleTop' do you still get the same crash?

**Comment by jsuarezruiz** [comment]
Could you share the stacktrace?

**Comment by PureWeen** [comment]
@innomarcoItalia your project is still targeting net6.0 

https://github.com/mistrypragnesh40/PushNotificationDemoMAUI/blob/master/PushNotificationDemoMAUI.csproj#L4

can you update all of those to `net7.0` and see if you get the same exception?

**Comment by innomarcoItalia** [comment]
@PureWeen In my local computer I have updated the project to Net.7 ... as per the attached zip file.
sorry for the repository, refer to the error above ... i am not the owner of the repository, i had to add in the post to upgrade to net.7
[App_Utente.zip](https://github.com/dotnet/maui/files/9823029/App_Utente.zip)

**Comment by innomarcoItalia** [comment]
@PureWeen 
I checked by setting launchMode to 'singleTop' and not crash.
I need to understand what it means to set LaunchMode to singleTop.... I need to open a specific page by tapping on the notification.

**Comment by PureWeen** [comment]
> @PureWeen I checked by setting launchMode to 'singleTop' and not crash. I need to understand what it means to set LaunchMode to singleTop.... I need to open a specific page by tapping on the notification.

singleTop means the already open activity will receive the intent from the popup notification. So then inside `OnResume` (I think that's where) you have to look at the intent to extract the message data.  Once you have that message data you can navigation inside shell to the location you want to navigate to.

**Comment by PureWeen** [comment]
> @PureWeen I checked by setting launchMode to 'singleTop' and not crash. I need to understand what it means to set LaunchMode to singleTop.... I need to open a specific page by tapping on the notification.

If you change your app.xaml.cs to look like this does it work the original way?

```C#
namespace SicurezzaInCasentino;

public partial class App : Application
{
    public App()
    {
        InitializeComponent();
    }

    protected override Window CreateWindow(IActivationState activationState)
    {
        return new Window(new AppShell();
    }
}
```

**Comment by PureWeen** [comment]
@jonathanpeppers thoughts?

@innomarcoItalia can you try grabbing a logcat file
https://learn.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows

**Comment by innomarcoItalia** [comment]
@PureWeen 
I created a new project already in NET 7 and added:

protected override Window CreateWindow (IActivationState activationState)
     {
         return new Window (new AppShell ());
     }

the app was starting in both Debug and Release, so I added push notifications.
Push notifications also work well with the app in the forground!


Write in App.xaml.cs:
public App ()
{
InitializeComponent ();

// MainPage = new AppShell ();
}

     protected override Window CreateWindow (IActivationState activationState)
     {
         return new Window (new AppShell ());
     }



is this the currently recommended path for Push Notification?
I ask this because I also have to develop push notifications for IOS. (I can always use conditional compilation)
thanks for your commitment

**Comment by jonathanpeppers** [comment]
> @innomarcoItalia can you try grabbing a logcat file https://learn.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows

I think we need the logcat file to know what's wrong here, it should show some exception message. Does it only crash when you tap the notification? Is it navigating to a page when you tap it?

**Comment by innomarcoItalia** [comment]
@jonathanpeppers 
I created a new project directly in Net. 7.
The app starts correctly both in debug and in release, as written in the previous post.
thank you

**Comment by rmarinho** [comment]
So the issue is fixed when using the net7 right @innomarcoItalia  ? 

Can you please close the issue if this is true. 

Thanks

**Comment by innomarcoItalia** [comment]
@rmarinho 
the issue is fixed with the addition in App.xaml.cs:
 protected override Window CreateWindow (IActivationState activationState)
 {
     return new Window (new AppShell ());
 }

**Comment by pekspro** [comment]
To anyone else that is struggling with this error message when user taps on an notification on Android. If you set `LaunchMode` to `SingleTop` on your `MainActivity`:

```C#
[Activity(  Theme = "@style/Maui.SplashTheme", 
            MainLauncher = true, 
            ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode | ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize,
            LaunchMode = LaunchMode.SingleTop)]
public sealed class MainActivity : MauiAppCompatActivity
{
```

Your app will no longer crash. Your app will be open on the latest used page. I have no idea how to do something different :-)
