### ISSUE TITLE
Cannot update WebView2 UserDataFolder in BlazorWebView for Windows Forms

### ISSUE THREAD

**Issue by thirstyape** [dotnet/maui#10772]
### Description

I received the following exception when running a WinForms with `BlazorWebView` project. After looking for a solution I found that the error could be solved by changing the UserDataFolder; however, this is impossible to do right now.

We couldn't create the data directory
Microsoft Edge can't read and write to its data directory: 
C:\Users\~\AppData\Local\~.WebView2\EBWebView

This only occurred after running the app as administrator. The interesting part is that the directory listed is the directory you would expect it to be for the administrative user. Once I started to look into the issue I found the following can be used to update the directory.

```
var myUserDataFolder = "C:\\Temp\\WebView2Temp";
Directory.CreateDirectory(myUserDataFolder);

var env = await CoreWebView2Environment.CreateAsync(null, myUserDataFolder);
await blazorWebView.WebView.EnsureCoreWebView2Async(env);
```

Unfortunately, this throws an `ArgumentException` stating: WebView2 was already initialized with a different CoreWebView2Environment. Check to see if the Source property was already set or EnsureCoreWebView2Async was previously called with different values.

Looking even further, I found that this is pretty much the end of the road as the [BlazorWebView](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/WindowsForms/BlazorWebView.cs) component is configured in such a way that users will never have the chance to call this before the underlying `Source` property is set.

### Steps to Reproduce

1. Create a new WinForms app follow the [MS Guide](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-6.0)
2. Try to update the WebView2 user data folder using the above snippet
3. Receive exception

### Link to public reproduction project repository

Project as per steps

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

This was going to be the workaround to a different issue :)

**Comment by javiercn** [comment]
@thirstyape thanks for contacting us.

Seems that you are not initializing blazor webview at the correct time. The BlazorWebview exposes a couple of event handlers to get access to the configuration of the underlying platforms webview during initialization. See [here](https://learn.microsoft.com/vi-vn/aspnet/core/blazor/hybrid/?view=aspnetcore-6.0#web-view-configuration) for details

**Comment by thirstyape** [comment]
Hi @javiercn,

Finally had time to give that a try. That worked, thank you.

For others reference:

```
public partial class AppWindow : Form
{
    public AppWindow()
    {
        InitializeComponent();

        blazorWebView.HostPage = "wwwroot/index.html";
        blazorWebView.RootComponents.Add<App>("#app");
        blazorWebView.RootComponents.Add<HeadOutlet>("head::after");

        blazorWebView.BlazorWebViewInitializing += WebViewInitializing;
    }

    private void WebViewInitializing(object? sender, BlazorWebViewInitializingEventArgs e)
    {
        var myUserDataFolder = "C:\\Temp\\MyApp.exe.WebView2";
        Directory.CreateDirectory(myUserDataFolder);

        e.UserDataFolder = myUserDataFolder;
    }
}
```

**Comment by kuba1** [comment]
Is the above supposed to also work for WPF? I created a MAUI Blazor app using VS 17.3.6 but the WebView writes to application folder (same as .exe) no matter what I try.

**Comment by thirstyape** [comment]
@kuba1 Yes, this will work for WPF as well. 

My example is specific to WinForms, but the `blazorWebView.BlazorWebViewInitializing += WebViewInitializing;` is the important part and should be the same.

**Comment by kuba1** [comment]
Thanks for help @thirstyape . For some reason this is not working for me but I cannot figure out what I'm missing...

Whatever I'm missing is most likely connected to the fact I'm using WPF. Still, I'm out of ideas.

I'm setting the UserDataFolder property in BlazorWebViewInitializing handler but in BlazorWebViewInitialized handler I can see that WebView.CoreWebView2.Environment.UserDataFolder is still set to application installation directory.

Setting BrowserExecutableFolder seems to be working.

I guess I'll think about it some more and open another issue.
