### ISSUE TITLE
Maui Error

### ISSUE THREAD

**Issue by Skyscalesystems** [dotnet/maui#1077]
Hi ,

I am install Visual studio 2019 preview and Install Maui with step by step guideline.
When i am create .NET MAUI project and Build this error will be coming. 
Please help me .

Thanks & Regards,
Ravikumar.

Error:  Severity	Code	Description	Project	File	Line	Suppression State
Error		Project "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\11.0.200-preview.3.196\Sdk\Sdk.targets" was not imported by "C:\Program Files\dotnet\sdk-manifests\6.0.100\Microsoft.NET.Workload.Android\WorkloadManifest.targets" at (2,3), due to the file not existing.	Maui	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\11.0.200-preview.3.196\Sdk\Sdk.targets	2

**Comment by AmSmart** [comment]
Use the maui-check tool to ensure you environment is setup. I believe your errors should go away afterwards. You should also consider updating to the latest VS2019 preview version.

**Comment by jfversluis** [comment]
This described a couple of previews ago and VS2019 so I'm going to rule this outdated :)

If you still have any issues with the latest bits, please create a new issue
