### ISSUE TITLE
[Android] WindowOvelay painting is not working with shell

### ISSUE THREAD

**Issue by PraveenGopalsamy** [dotnet/maui#10781]
### Description

In Android, when adding the WindowOverlay with shell, the rendering is not visible. I'm getting the paint rect.width as 0.

### Steps to Reproduce

* Create a new project in .Net Maui.
* Create a custom WindowOverlay extends from the IWindowOverlay.
* On a button click add this overlay to the Window using the addOverlay() method.
* Render a rectangle inside the OnDraw method. You can't get any output on the UI.

### Link to public reproduction project repository

https://github.com/PraveenGopalsamy/WindowOverlaySample

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android (all versions)

### Did you find any workaround?

No.

**Comment by PureWeen** [comment]
@PraveenGopalsamy if you update your project to net7.0 does it work?

**Comment by PraveenGopalsamy** [comment]
Hi @PureWeen ,

Yes. This issue was replicated in the .net7.0 too. Please check the sample project too. https://github.com/PraveenGopalsamy/WindowOverlaySample_7.0

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on android platform with sample project. Windows works fine.
[WindowOverlaySample-main.zip](https://github.com/dotnet/maui/files/11596547/WindowOverlaySample-main.zip)
Android:
![10781 A](https://github.com/dotnet/maui/assets/77434865/4efec170-3137-4743-ac47-a857496e6b1f)
Windows:
![10781 W](https://github.com/dotnet/maui/assets/77434865/a01b41b4-877b-47ba-89c5-2dd85b485d79)
