### ISSUE TITLE
Is there a way to change Shell.TitleView Background color?

### ISSUE THREAD

**Issue by mooshra** [dotnet/maui#10788]
### Description

I've tried many variants, but the header color seems to be unchangeable.

### Steps to Reproduce

1. Create a new project
2. Try to change Shell.TitleView background color

### Link to public reproduction project repository

-

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12-13 API 31-33

**Comment by PureWeen** [comment]
Can you include a screen shot indicating expectations?
