### ISSUE TITLE
[Bug] Scroll view inside the stack layout not scrolling.

### ISSUE THREAD

**Issue by BalachandarSelvam** [dotnet/maui#10787]
### Description

When I put scroll view inside the stack layout, the content was not scrolling. Whereas in Xamarin forms it was scrolling. I noticed this issue in all 4 platforms.

### Steps to Reproduce

1. Open and run the sample
2. Try to scroll the content

### Link to public reproduction project repository

https://github.com/BalachandarSelvam/Framework-bug/tree/main/ScrollView-Bug

### Version with bug

6.0.541

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 9, Windows 10.

### Did you find any workaround?

No

**Comment by jenscski** [comment]
This is not a bug, but a breaking change from Xamarin.Forms, see comment https://github.com/dotnet/maui/issues/7669#issuecomment-1144823422

**Comment by hartez** [comment]
This is a change to [make MAUI's layout system more consistent](https://gist.github.com/hartez/8eb5fe887935e4068be321ceed4ddefb).  Putting the ScrollView as the root of the Page will allow scrolling, or you can use another vertically-constrained layout, e.g. Grid:

```
<Grid>
    <ScrollView>...</ScrollView>
</Grid>
```
