### ISSUE TITLE
ScrollView inside StackLayout is not scrolling

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#10786]
### Description

When you put a ScrollView inside a StackLayout, you are not able to scroll up and down.
![image](https://user-images.githubusercontent.com/114725843/196724795-a24bca5e-7937-4bb6-a7d7-5ebe99e0c127.png)
![ScrollView_example](https://user-images.githubusercontent.com/114725843/196733199-cd397764-3946-410e-82d6-4ac42d696ba3.gif)

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Place a ScrollView with some elements inside a StackLayout
3. You cannot scroll up and down

### Link to public reproduction project repository

https://github.com/owl-guy/ScrollViewExample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

**Comment by jenscski** [comment]
This is not a bug, but a breaking change from Xamarin.Forms, see comment https://github.com/dotnet/maui/issues/7669#issuecomment-1144823422
