### ISSUE TITLE
WinUI Dynamic height in grid does not work when nothing else changes

### ISSUE THREAD

**Issue by duindain** [dotnet/maui#10799]
### Description

In WinUI setting a height for a control in a grid can work but if changed later the grid is not resized to match resulting in content getting cut off or controls out of reach in the UI

iOS also has a minor problem where the button i added first in the grid isn't visible when the boxview is expanded so I wired the event up to the demo app button as well, it does expand and contract though, Android works fine

Windows first opened (Boxview in black is 200 high)   |  Windows first dynamic resizing reducing size (Boxview is 30 high) | Windows second dynamic resizing increasing size nothing happens (Boxview is 200 high)
:-------------------------:|:-------------------------:|:-------------------------:
<img src="../../../duindain/expandingContent/blob/f6ead41a802b5529f3469f4da66b15068148a243/WinUI%20Initial%20screen.png?raw=true" width="300" height="200" alt="Windows first opened with dynamic content at 200"/> | <img src="../../../duindain/expandingContent/blob/f6ead41a802b5529f3469f4da66b15068148a243/WinUI%20First%20height%20change.png?raw=true" width="300" height="200" alt="Windows first resize down to 30 all good"/> | <img src="../../../duindain/expandingContent/blob/f6ead41a802b5529f3469f4da66b15068148a243/WinUI%20Second%20height%20change%20height%20should%20now%20be%20200.png?raw=true" width="300" height="200" alt="windows resize dynamic content to 200 nothing changes"/>

iOS first opened (First row containing button is not visible but it should be)  |  iOS after dynamic height change (First row is shown)
:-------------------------:|:-------------------------:
<img src="../../../duindain/expandingContent/blob/f6ead41a802b5529f3469f4da66b15068148a243/iOS%20First%20opened%20height%20at%20200%20button%20in%20grid%20missing.png?raw=true" width="300" height="200" alt="Button missing in iOS from grid when dynamic content size initially set"/> | <img src="../../../duindain/expandingContent/blob/f6ead41a802b5529f3469f4da66b15068148a243/iOS%20Resized%20to%2030%20button%20appears.png?raw=true" width="300" height="200" alt="dynamic content resized to 30 button appears in grid"/>

### Steps to Reproduce

1. Create new MAUI demo app
2. Add a Grid using * row definitions or Auto
3. Add a resizable control and a button to activate it
4. Add code to change the size onclick
5. Run the app, when resizing it is ok to go down in size but not up

### Link to public reproduction project repository

https://github.com/duindain/expandingContent

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

iOS 15, Win SDK 

### Did you find any workaround?

Seemingly adding a binding on the page that updates at the same time forces a redraw which makes the resizing work as intended
i.e. a new row in the grid with

`<Label Grid.Row="4" Grid.Column="0" Text="{Binding BoxHeight}"/>`

Will make the page work correctly in Windows

**Comment by duindain** [comment]
Change images to relative references

**Comment by PureWeen** [comment]
@duindain can you log this as a separate issue please?

> iOS also has a minor problem where the button i added first in the grid isn't visible when the boxview is expanded so I wired the event up to the demo app button as well, it does expand and contract though, Android works fine
