### ISSUE TITLE
[Enhancement] please consider console style UI

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/maui#108]
## Summary
IMHO it would be great if console ui could be supported similar to GUI.cs using ansi control codes to give a simple window experience across all platforms 

## Intended Use Case
A simple UI experience for applications running on Linux and or Windows Server Core/Nano Server contains where a full GUI is not installed or supported

**Comment by Happypig375** [comment]
What will be the implementation and maintenance cost of this feature?

**Comment by jayrulez** [comment]
https://github.com/migueldeicaza/gui.cs

**Comment by davidortinau** [comment]
@grahamehorner as with WPF and GTK# which are community contributor supported, we welcome a contributed console UI for those that wish to use it. Perhaps you can rally support here on this issue!

I don't see this being a high impact area for us to take on directly, but I'm open to learning.
