### ISSUE TITLE
Bindings are executed twice

### ISSUE THREAD

**Issue by bakerhillpins** [dotnet/maui#10806]
### Description

It appears that XAML bindings are being executed twice in certain circumstances. I've got several different situations in my MAUI application where this appears to be happening. At the moment I can only reproduce the following in a greatly simplified situation.

If I place a binding at the top of a Page definition, all the bindings on that page will we executed 2 times. 
It also appears that any IValueConverter attached to the binding is executed AFTER the lower bindings are applied the 1st time.

Thus if we have the following code:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:converters="clr-namespace:MauiBugz.Converters"
             xmlns:views="clr-namespace:MauiBugz.Views"
             BindingContext="{Binding Property, Mode=OneTime, Converter={x:Static converters:CountingConverter.Instance}, ConverterParameter='TopOfPage'}"
             x:Class="MauiBugz.Views.IssueView"
             Title="IssueView">

    <VerticalStackLayout>

        <ContentView
            BindingContext="{Binding Property, Mode=OneTime, Converter={x:Static converters:CountingConverter.Instance}, ConverterParameter='OneLevelDown'}"/>

        <ContentView
            BindingContext="{Binding Property, Mode=OneTime, Converter={x:Static converters:CountingConverter.Instance}, ConverterParameter='CustomContent'}"/>

    </VerticalStackLayout>
    
</ContentPage>
```
We will see the following progression:

```
[DOTNET] IssueViewModel Get Property
[DOTNET] OneLevelDown converter has been executed 1 times. Value: Data_A
[DOTNET] IssueViewModel Get Property
[DOTNET] CustomContent converter has been executed 1 times. Value: Data_A
[DOTNET] IssueViewModel Get Property
[DOTNET] TopOfPage converter has been executed 1 times. Value: Data_A          <<<<<<<<<<<<<< 
[DOTNET] ConvertedData_A Get Property
[DOTNET] OneLevelDown converter has been executed 2 times. Value: Data_B
[DOTNET] ConvertedData_A Get Property
[DOTNET] CustomContent converter has been executed 2 times. Value: Data_B
```
Note that `TopOfPage converter` is executed after all the lower bindings have been presented with the VM applied to the page.  They were never to see the VM, they were to receive `ConvertedData` objects that were derived from the `Data` object returned from the `VM.Property` getter. (As you see in the 2nd half of the console output.)

### Steps to Reproduce

1. Clone the Repro
2. Select the button for the Issue
3. View the Console output.

NOTE: This issue is a bit tedious to illustrate via output as Bindings are relatively verbose processes with several steps. I've implemented the following in an attempt to help track the issue via console output.

`CountingConverter` is an `IValueConverter` implementation with the following:
- Static `Instance` property that returns a unique/new converter for each access. (Each binding has it's own instance)
- `ConverterParameter` is expected to be a string "name" to uniquely identify each converter.
- Designed to count each time it's executed and prints it's name, the count, and the value and it's provided to the Console. 
- Takes a `Data` object in, and returns a `ConvertedData` object.

The initial ViewModel, `Data`, and `ConvertedData` all share the same `Property` property to simplify coding down the XAML tree. 
-  The getter creates a new `Data` object on first access.

`Data` and `ConvertedData` get a new designation character when they are created to make each unique.

### Link to public reproduction project repository

https://github.com/bakerhillpins/Issues/tree/NetMauiIssue10806

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

It appears that if you insert ContentView between your actual XAML and the Page (effectively wrapping your view) and move the TopOfPage binding down to that wrapper ContentView, the bindings are only executed once. 

The Caveat here is that I'm actually using this workaround in my larger application, however, I'm still seeing the issue and have not been able to determine why at the moment.

**Comment by bakerhillpins** [comment]
Key here appears to be the fact that the binding on the `ContentPage.BindingContext` fails to be resolved when the `BindingContext` is set in the constructor of the `ContentPage`.  That set of the BindingContext results in an attempt to apply the binding via the call at [Line 529 of BindableObject](https://github.com/dotnet/maui/blob/1c4c0dd17b0cd51cedc4883b3e5a683e453685e9/src/Controls/src/Core/BindableObject.cs#L529). Here we call into `BindingExpression.Apply(true)` but this fails [here](https://github.com/dotnet/maui/blob/1c4c0dd17b0cd51cedc4883b3e5a683e453685e9/src/Controls/src/Core/BindingExpression.cs#L55) because the `Binding.Source` is null.

As the binding is not resolved, this has the effect of pushing the VM down through the visual tree rather than the target property value that the binding on the Page was to extract. Thus all the bindings within the `VerticalStackLayout` will fail (They were not expecting the VM).  At this point the `BindingContextChanged` even is fired off which again attempts to Apply the binding but it appears to be rejected because it's a OneTime binding. It appears that when there's a binding on the BindingContext property there's a LOT of recursion.  At this point we exit the Page constructor with the incorrect BindingContext values.

The expected binding behavior doesn't occur here until Navigation actually pushes the page on to the Nav Stack by adding it as the child of the ShellSection. 

SO, the question is... Is this a valid binding? If that binding were set to `OneWay,` the act of setting the `Page.BindingContext` would actually remove the binding because it's a Manual Set of the `BindingContextProperty`.  But since it's OneTime it passes that check but gets goofed up downstream.

**Comment by bakerhillpins** [comment]
I've also located some paths through the code that result in executing BindableObject.ApplyBindings multiple times which will account for the multiple binding executions. An example is when a binding [adds a child to an Element](https://github.com/dotnet/maui/blob/1c4c0dd17b0cd51cedc4883b3e5a683e453685e9/src/Controls/src/Core/Element.cs#L346). Here Element.Parent is set and results in a call to `BindableObject.ApplyBindings` which is immediately followed by a 2nd call to `BindableObject.ApplyBindings`.

**Comment by CDboyOne** [comment]
I am faced with this issue too. @bakerhillpins Did you have problem that `IValueConverter.Convert()` get a `value` parameter that is `null`?

**Comment by bakerhillpins** [comment]
@CDboyOne Yes, that's part of the issue with the multiple executions, it actually passes the wrong Inherited binding context value down through the visual tree the first pass. 

I have fixes for these issues but I can't get any one at MS to respond to questions.. See post above concerning a OneTime binding being valid in this situation.

**Comment by bakerhillpins** [comment]
> SO, the question is... Is this a valid binding? If that binding were set to `OneWay,` the act of setting the `Page.BindingContext` would actually remove the binding because it's a Manual Set of the `BindingContextProperty`. But since it's OneTime it passes that check but gets goofed up downstream.

So I'm going to assume that a OneTime binding should behave the same as a OneWay binding because that's the way it works in WPF:

I've ported the example over to WPF to see how it behaves in that tech stack. WPF will detach the `OneTime` binding from the `DataContext` property when you directly set the `DataContext` value.  E.g. the `BindingExpressionBase` that's returned from the `BindingOperations.SetBinding()` reports `BindingStatus.Unattached` before the set and `BindingStatus.Detached` after the set.

Code snippet:

```csharp
        public MainWindow()
        {
            InitializeComponent();

            Binding x = new Binding( "Property" )
                        {
                            Mode = BindingMode.OneTime,
                            Converter = CountingConverter.Instance,
                            ConverterParameter = "Code"
                        };

            // setting here mimics markup in XAML via InitializeComponent()
            var exp = BindingOperations.SetBinding(this, Window.DataContextProperty, x); 

            Debug.WriteLine( $"{exp.Status}" );

            DataContext = new MainWindowViewModel();

            Debug.WriteLine( $"{exp.Status}" );
        }
```

The interactions between setting bindings (order they are applied in the visual tree via XAML/Code behind) and when the BindingContext is set results is many different outcomes. This is true in WPF as well.  E.g.

```csharp
public partial class View : ContentPage
{
	public View( ViewModel vm )
	{
                this.BindingContext = vm;  // Has different outcome 
		
		InitializeComponent();

		//this.BindingContext = vm;  // Then a set of the BindingContext here.
	}
}
```

So it would appear that if you'd like to save yourself a bunch of binding headaches in MAUI/WPF you should generally avoid setting any Binding on a BindingContext property which is manually set.
