### ISSUE TITLE
.net 7 android compiler error (Java)

### ISSUE THREAD

**Issue by Maverick1983** [dotnet/maui#10802]
### Description
```
1>obj\Debug\net7.0-android\android\src\com\companyname\play\for\asd\mymaui\R.java(8,30): javac.exe error JAVAC0000:  error: <identifier> expected
1>obj\Debug\net7.0-android\android\src\com\companyname\play\for\asd\mymaui\R.java(8,30): javac.exe error JAVAC0000: package com.companyname.play.for.asd.mymaui;
1>obj\Debug\net7.0-android\android\src\com\companyname\play\for\asd\mymaui\R.java(8,30): javac.exe error JAVAC0000: 1 error
1>obj\Debug\net7.0-android\android\src\com\companyname\play\for\asd\mymaui\R.java(8,30): javac.exe error JAVAC0000:
```
### Steps to Reproduce

1. Create new solution Net Maui with .Net 7
2. Build solution
3. Error

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

6.0.424

### Affected platforms

Android

### Affected platform versions

Android 8, Android 9, Android 7

### Did you find any workaround?

No

### Relevant log output

```shell
1>obj\Debug\net7.0-android\android\src\com\companyname\play\for\asd\mymaui\R.java(8,30): javac.exe error JAVAC0000:  error: <identifier> expected
1>obj\Debug\net7.0-android\android\src\com\companyname\play\for\asd\mymaui\R.java(8,30): javac.exe error JAVAC0000: package com.companyname.play.for.asd.mymaui;
1>obj\Debug\net7.0-android\android\src\com\companyname\play\for\asd\mymaui\R.java(8,30): javac.exe error JAVAC0000: 1 error
1>obj\Debug\net7.0-android\android\src\com\companyname\play\for\asd\mymaui\R.java(8,30): javac.exe error JAVAC0000:
```

**Comment by PureWeen** [comment]
@jonathanpeppers

**Comment by jonathanpeppers** [comment]
@Maverick1983 is the problem here because you have a package name with `for` in the name?

    com.companyname.play.for.asd.mymaui

`for` is a keyword in Java, perhaps it completely breaks this?

**Comment by Maverick1983** [comment]
> @Maverick1983 is the problem here because you have a package name with `for` in the name?
> 
> ```
> com.companyname.play.for.asd.mymaui
> ```
> 
> `for` is a keyword in Java, perhaps it completely breaks this?

Thanks. Working!
