### ISSUE TITLE
WevView not allowing target="_blank"  href redirects on Android

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/maui#10818]
### Description

I have an MAUI app that is essentially a WebView that hosts a wordpress website. My problem is that whenever I try to load an external link it will simply not load the "href" redirect... It works fine on Windows and iOS devices, but not in android.

Note: on windows devices, the links open in a new window, and on ios it opens in the current window.
I want it to behave like on iOS where the current window/webview hosts the page

Is there a specific permission I need in the manifest, nothing is happening when I click links?

### Steps to Reproduce

1. Create an MAUI app in android that consists of a `WebView`
2. The site in question must be a site with href redirects, so `google.com` is not valid

### Link to public reproduction project repository

*

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Androids 9 and 12 were tested

### Did you find any workaround?

None

**Comment by ctigrisht** [comment]
@jsuarezruiz 

Here is a content page with the webview inside it. Problem happens both in debug and release mode.
You only need to go to any site that has a `<a href="externalsite.com" target="_blank">` tag and click on it.


```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MltDimParisPhoneApp.BanglaPage" 
             NavigationPage.HasNavigationBar="False" NavigationPage.HasBackButton="False"
             Shell.NavBarIsVisible="False">
    <Grid BackgroundColor="DarkSlateGrey">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <StackLayout Grid.Row="0" Grid.Column="0" >
        </StackLayout>
        <WebView Grid.Row="1" Grid.Column="0" 
                     Source="https://example.com/"
                     x:Name="WebView"/>
    </Grid>
</ContentPage>
```

**Comment by ctigrisht** [comment]
So to handle redirects to `_blank` targets in a WebView by keeping them in the same window/view, I had to create a custom renderer.

1. Create a folder called `Controls` inside `Platforms/Android`, then create a class file, I called it `MltWebViewClientRenderer.cs`.
Paste this inside the file:
```cs
    public class MltWebViewRenderer : WebViewRenderer
    {
        public MltWebViewRenderer(Context context) : base(context)
        {
        }
        protected override void OnElementChanged(ElementChangedEventArgs<Microsoft.Maui.Controls.WebView> e)
        {
            base.OnElementChanged(e);
            Control.SetWebViewClient(new MltWebViewClient());
            global::Android.Webkit.WebView.SetWebContentsDebuggingEnabled(true);
        }
    }

    public class MltWebViewClient : global::Android.Webkit.WebViewClient
    {
        public MltWebViewClient()
        {
        }

        public override bool ShouldOverrideUrlLoading(global::Android.Webkit.WebView view, IWebResourceRequest request)
        {
            view.Settings.SetSupportMultipleWindows(false);
            view.Settings.JavaScriptCanOpenWindowsAutomatically = true;
            
            view.Settings.JavaScriptEnabled = true;

            view.SetWebChromeClient(new WebChromeClient());

            return base.ShouldOverrideUrlLoading(view, request);
        }
    }
```
The above code basically allows access to the `Settings` of the `WebView`.

2. In the `MauiProgram.cs`, you need to add some services to the builder, as such:

```cs
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                })
                .UseMauiCompatibility()
                .ConfigureMauiHandlers(x =>
                {
#if ANDROID
                    x.AddCompatibilityRenderer(typeof(WebView), typeof(Platforms.Android.Controls.MltWebViewRenderer));
#endif
                });
            return builder.Build();
```
The above only invokes our custom renderer if we are on Android.

Note: This solution only works for Android API versions 24 and above.

My problem with this problem is that WebView settings should be directly accessible within the pages code, having to write a custom renderer for such a basic thing is nonsensical.

**Comment by jfversluis** [comment]
Not a lot of traction over a couple of years, there is not reproduction so I can't easily verify if this is solved by now or not. There is a workaround provided. If there is still something we can do better here, please feel free to open a new issue with all the details. Thanks!
