### ISSUE TITLE
Android - Collectionview EmptyView not visible

### ISSUE THREAD

**Issue by FM1973** [dotnet/maui#10819]
### Description

Using a Collectionview with an EmptyView does not work.
The EmptyView is not being displayed. It does work on Windows, but not on Android.
If you set a HeightRequest on the CollectionView the EmptyView is being displayed.

### Steps to Reproduce

Just run the repo project and have a look.

### Link to public reproduction project repository

https://github.com/FM1973/EmptyViewProblem.git

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11+

### Did you find any workaround?

One can specify a HeightRequest and the EmptyView is beind displayed.
But this does prevent a dynamic height of the list.

**Comment by rmarinho** [comment]
Maybe duplicate of #8934

**Comment by espenrl** [comment]
I've been looking into the code and debugging the empty views in the sample gallery. These are my findings:

- The problem occurs with `LinearItemsLayout`, the samples mostly use `GridItemsLayout`.
- If the ItemsSource is null or have zero items the problem will occur. Most of the samples have several items.
- Given a CollectionView with LinearItemsLayout and zero items.
  - Setting EmptyView to a string works fine. Setting it to a View doesn't work.
  - EmptyViewTemplate never works.

It seems to be a initialization issue. For the sample `EmptyView (Swap EmptyView)` set ItemSource to null, remove the GridItemsLayout. Initially the EmptyView will not be shown. Then toggle the EmptyView and it will be shown.

**Comment by FM1973** [comment]
@espenrl Thanks a lot for your analysis. At least a workaround for this bug.

**Comment by FM1973** [comment]
@espenrl Ok, I had a try. Sadly the empty view isn´t initially being shown using your suggestions.

**Comment by Syed-RI** [comment]
cc @davidortinau @jfversluis @PureWeen . This is a basic requirement thats failing us now. Can you please assign resources in this issue please? I know you guys are working hard and really appreciate the work :) Thank you!

**Comment by nk54** [comment]
> Given a CollectionView with LinearItemsLayout and zero items.
> Setting EmptyView to a string works fine. Setting it to a View doesn't work.
> EmptyViewTemplate never works

Can confirm simple works, custom content doesn't on Android

**Comment by Larhei** [comment]
Same issue here.

**Comment by jsuarezruiz** [comment]
Reviewing the issue; we create the EmptyView with a wrong size because try to use the RecyclerView Height/Width and is not measured at this time.

**Comment by Syed-RI** [comment]
@jsuarezruiz any workaround?

**Comment by mattleibow** [comment]
Thanks to @espenrl for pointing out that templates are not working at all. I opened a new issue to track that: https://github.com/dotnet/maui/issues/18551
