### ISSUE TITLE
Error		ADB0010: Mono.AndroidTools.InstallFailedException: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]

### ISSUE THREAD

**Issue by Pasang012** [dotnet/maui#10829]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by achilleaskar** [comment]
This error usually occurs when you don't press accept on your android at the first install attempt. Also if you have checked the "remember" checkbox and then press the deny button it will always restrict the installation without asking. In this case you have to go to phone settings and search for install through usb option something like that, or change the app company name
