### ISSUE TITLE
Maui Application running throws FileNotFoundException (iOS)

### ISSUE THREAD

**Issue by MariyaGordeeva** [dotnet/maui#10821]
### Description

Maui Application running throws FileNotFoundException on iOS.

### Steps to Reproduce

1.   Create new Maui App from template in the Visual Studio
[TestApp.zip](https://github.com/dotnet/maui/files/9837369/TestApp.zip)
2.  In visual Studio Exception Settings enable Break on System.Exception
3.  Build and run project on iOS, it should break on the statement InitializeComponent() in App.xaml.cs.

### Link to public reproduction project repository

https://github.com/MariyaGordeeva/DefaultApp

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by Eilon** [comment]
Hi @MariyaGordeeva , if you continue the program execution once this exception happens, does everything continue to work? Or does the app fail completely?

**Comment by MariyaGordeeva** [comment]
Hi @Eilon, if I skip this exception than the application will continue running

**Comment by Eilon** [comment]
@MariyaGordeeva alright that's good to know. This is what's called a "first-chance exception," meaning that it was thrown, but then caught, so program execution continued normally. While these can certainly be annoying while debugging, they are often harmless (but not always).

This could be a sign of an actual bug in .NET MAUI, though since you say things otherwise work normally, perhaps it is not. But if it's truly harmless, then ideally there would be a way for this exception to be entirely avoided (at least to make things less annoying).

**Comment by borrmann** [comment]
Having the same problem (as well only on ios). Program runs fine. 
Is there a way avoiding this @Eilon?

**Comment by Eilon** [comment]
> Having the same problem (as well only on ios). Program runs fine. Is there a way avoiding this @Eilon?

@borrmann we'd need to know exactly which exception it is and the circumstances. As I said, sometimes it's normal and harmless (but perhaps annoying), and sometimes it's a sign of a bug in the app or in .NET MAUI. Also it can depend on whether the app is running in Debug mode, of if it's a published Release mode app.

**Comment by marktopley** [comment]
I was stuck with a similar issue, ran fine on Windows but Android and iOS both threw 1st chance exceptions FileNotFoundException from InitializeComponent() in App.xaml.cs. Even with FileNotFound exception not set in Debugger options. I found after much pain that deleting the .vs folder next to my solution fixed the issue.

**Comment by ac-lap** [comment]
> I was stuck with a similar issue, ran fine on Windows but Android and iOS both threw 1st chance exceptions FileNotFoundException from InitializeComponent() in App.xaml.cs. Even with FileNotFound exception not set in Debugger options. I found after much pain that deleting the .vs folder next to my solution fixed the issue.

Worked for me!

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 5.0. Not repro on Android and iOS platform on Mac with sample project. [/MariyaGordeeva/DefaultApp](https://github.com/MariyaGordeeva/DefaultApp)
