### ISSUE TITLE
loading app to phone in debug mode

### ISSUE THREAD

**Issue by samosim** [dotnet/maui#10837]
### Description

I updated VS to the latest preview version and created a new MAUI project. The Android application needs more than 2 minutes to deploy on my Android phone and after that debugging did not work at all. Here is the link: 
https://www.veed.io/view/5e3777aa-1bfd-49be-b681-9893fad54019?sharingWidget=true

If I open the project created in the previous preview version,  its application was not even open on my phone.
I was trying to find the previous preview version but without success.  If anyone knows how to get it I will appreciate it.

### Steps to Reproduce

No steps, the basics do not work at all!

### Link to public reproduction project repository

https://www.veed.io/view/5e3777aa-1bfd-49be-b681-9893fad54019?sharingWidget=true

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

**Comment by AlanGusLive** [comment]
@samosim you can Rollback to previous version by using the Visual Studio Installer : Visual Studio=>Tools=>Get Tools and Features...=>Button Close=>Button More=>[Rollback to previous version](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#17.4.0-pre.2.0)
![image](https://user-images.githubusercontent.com/15076413/197349562-2c44258d-5d1f-4f7c-9fa5-875d7a0c362c.png)
