### ISSUE TITLE
Settings `-p:MauiXamlCValidateOnly=False` not working on `Debug` configuration

### ISSUE THREAD

**Issue by yunusefendi52** [dotnet/maui#10844]
### Description

setting `MauiXamlCValidateOnly` to false not working on Debug configuration, log:
```
Set Property: _MauiXamlCValidateOnly=False
Set Property: _MauiXamlCValidateOnly=True

other logs

ValidateOnly=True. Skipping writing assembly.

```

Looking at the [source](https://github.com/dotnet/maui/blob/a2947dfcce1e2629fe1946b120070f3c38ce0bb0/.nuspec/Microsoft.Maui.Controls.targets#L145-L147), it's working when settings it to `-p:MauiXamlCValidateOnly=False -p:_MauiForceXamlCForDebug=True`
```
Set Property: _MauiXamlCValidateOnly=False
```

Confirmed by the output dll with IL compiled xaml

### Steps to Reproduce

1. Create maui project
2. dotnet build -f net6.0 -v diag -p:MauiXamlCValidateOnly=false

Expected: output dll should have IL compiled XAML
Actual: output dll doesn't have IL compiled XAML

### Link to public reproduction project repository

no

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All?

### Did you find any workaround?

Add `-p:_MauiForceXamlCForDebug=True` arg to force, but as far as I know property group prefixed with _ usually for internal use only

**Comment by jsuarezruiz** [comment]
cc @StephaneDelcroix

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Not repro this issue.
