### ISSUE TITLE
Support for App Store Monetization Like StoreKit2 and Google Play Badly Needed

### ISSUE THREAD

**Issue by speschka** [dotnet/maui#10853]
### Description

Right now there is a lack of any integration with the monetization features of Apple App Store (StoreKit2) or Google Play.  This relegates app development with .NET MAUI really to play apps only, or corporate apps.  The biggest market of course is the ISV market, but it needs a way to monetize apps.

I've developed an app using MAUI that, as it turns out, has a revenue model not covered by Apple's App Store guidelines, meaning they are not entitled to a piece of it nor can they force me to integrate an in app purchase.  As a result however, they have spent over a week now reviewing my app with constant harassment and bullying to try and find any reason they can to try and prevent it from being published.  All of this because I told them that there are no StoreKit2 libraries for .NET MAUI, and because Apple is, as usual, like a decade behind in technology, they have no REST APIs that you can use to integrate with the store.  Otherwise I would have done so just to move past this.  The bigger point though is that if my particular case did not fall outside of their guidelines where they can effectively tax my revenue on the app, then I would have been completely screwed.  MAUI developers should not be put in that position.

### Public API Changes

I'm not going to try and come up with a complete API list for in app purchase integration.

### Intended Use-Case

Any app that wants to include monetization needs some way to integrate on the .NET MAUI side with the in app purchase models of Apple and Google.

**Comment by rmarinho** [comment]
HI @speschka have you looked at https://github.com/jamesmontemagno/InAppBillingPlugin ?

**Comment by rmarinho** [comment]
No worries!

Thanks
