### ISSUE TITLE
IsFocused does not return to false when a DatePicker loses focus in iOS

### ISSUE THREAD

**Issue by JPfahl** [dotnet/maui#10875]
### Description

When a value is selected for a datepicker its IsFocused property changes to true and stays that way even when it loses focus.

### Steps to Reproduce

Add the following code to the mainpage.xaml a default .net maui app project:

            <DatePicker x:Name="dp1"/>
            <Label Text="{Binding IsFocused, Source={Reference dp1}}"/>
            <DatePicker x:Name="dp2"/>
            <Label Text="{Binding IsFocused, Source={Reference dp2}}"/>
            <Entry/>

Initially both are false.  select a date in the first datepicker and the first label displays true.
tap the second date picker and the first label does not change.
select a date in the second datepicker and the second label displays true.
tap on the entry so it has focus and both labels still display true.

Android does not set IsFocused at all.
Windows works as expected.

I am using Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.4.0 Preview 4.0

does not appear in the list below.

### Link to public reproduction project repository

none

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5, android api33

### Did you find any workaround?

no

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Not repro on iOS platform with mentioned code.
