### ISSUE TITLE
clang linker error after including Microsoft.Data.SqlClient nuget in project

### ISSUE THREAD

**Issue by jamesbgibson** [dotnet/maui#10870]
### Description

The problem is easily recreated.  Create a new project using the standard C# Maui template provided by Visual Studio.  Import the NuGet Microsoft.Data.SqlClient package release 5.0.0 or 5.0.1.  When you then perform a build with a target of one of the iOS emulators, you will see a clang linker error indicating that the framework "System" is not found.  If you revert to release 4.1.1, the error goes away.  I am using Microsoft Visual Studio Community version 17.3.6.

### Steps to Reproduce

See description above.

### Link to public reproduction project repository

not needed

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.0

### Did you find any workaround?

For the time, I've reverted to using 4.1.1.

**Comment by Eilon** [comment]
This issue was moved to dotnet/SqlClient#1816
