### ISSUE TITLE
Failed to verify code signature

### ISSUE THREAD

**Issue by ikeoriaku123** [dotnet/maui#10874]
### Description

After installing Visual Studio 2022 for Mac version 17.4 Preview 4.0, when running visual studio and visual studio is trying to deploy to device, I get this error;

The application has been built and uploaded, or is already up to date.
Visual Studio cannot start the application automatically because it was signed with a Distribution provisioning profile.  Please start it by tapping the application icon on the device. The trace trace log in the deploying to device tab gives an insight to the error but I do not know how to fix this as I have tried everything. Error: ApplicationVerificationFailed: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.K5w9UV/extracted/Maui.app : 0xe8008014 (The executable contains an invalid signature.)
error MT1006: Could not install the application.

My certificate and provisioning profile are correct and I am not sure why I am getting this error.

This never happened with Visual Studio 2022 for Mac version 17.4 Preview 3.0.

### Steps to Reproduce

1. Select your iphone under ios devices
2. Run visual studio for mac
3. Visual studio attempts to deploy to an iphone device
4. Error dialog: The application has been built and uploaded, or is already up to date.

Visual Studio cannot start the application automatically because it was signed with a Distribution provisioning profile.  Please start it by tapping the application icon on the device.

### Link to public reproduction project repository

NA

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 15.7

### Did you find any workaround?

No

### Relevant log output

```shell
CreatingStagingDirectory - PercentComplete: 5%
 ExtractingPackage - PercentComplete: 15%
 InspectingPackage - PercentComplete: 20%
 TakingInstallLock - PercentComplete: 20%
 PreflightingApplication - PercentComplete: 30%
 VerifyingApplication - PercentComplete: 40%
 ApplicationVerificationFailed: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.K5w9UV/extracted/Maui.app : 0xe8008014 (The executable contains an invalid signature.)
error MT1006: Could not install the application '/bin/Debug/net6.0-ios/ios-arm64/Maui.app' on the device 'iPhone': AMDeviceSecureInstallApplicationBundle returned: 0xe8008014.
```

**Comment by angelru** [comment]
@ikeoriaku123 
It seems that there are problems signing applications, this is how I have achieved it with a macOS application:

https://developercommunity.visualstudio.com/t/Signed-NET-MAUI-MACCATALYST-/10178897

**Comment by tj-devel709** [comment]
Hi @ikeoriaku123. This issue has been fixed and will be in an upcoming release. In the meantime, if you go into your .csproj file and manually remove any line (if any) that has
`<EnableCodeSigning>false</EnableCodeSigning>`

and add a line that says
`<EnableCodeSigning>true</EnableCodeSigning>`

I believe that will help you deploy. Let us know if this fixes your issue. 
Thanks.

**Comment by ikeoriaku123** [comment]
> Hi @ikeoriaku123. This issue has been fixed and will be in an upcoming release. In the meantime, if you go into your .csproj file and manually remove any line (if any) that has `<EnableCodeSigning>false</EnableCodeSigning>`
> 
> and add a line that says `<EnableCodeSigning>true</EnableCodeSigning>`
> 
> I believe that will help you deploy. Let us know if this fixes your issue. Thanks.

Thank @tj-devel709, this is the correct solution. It worked
