### ISSUE TITLE
[Bug] Build Handler registration ignores ordering 

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1088]
### Description

The order you call `Using` should be obeyed when registering handlers

Given the following code
```C#
.UseFormsCompatibility()
                .UseMauiControlsHandlers();
```

Whatever handlers are registered inside `UseFormsCompatibility` will win

**Comment by PureWeen** [comment]
This might not be a valid bug once this gets merged

https://github.com/dotnet/maui/pull/1157

**Comment by jsuarezruiz** [comment]
https://github.com/dotnet/maui/pull/1157 is already merged.
