### ISSUE TITLE
Install MAUI exe on server 2019 not seen the fonts

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#10899]
### Description

Install MAUI exe on sever 2019 not seen the fonts!!!

### Steps to Reproduce

1. Create MAUI app.
2. Install it as described in this ticket: https://github.com/dotnet/maui/issues/8830
3. The fonts are not seen.
4. How do I install the fonts ?
![image](https://user-images.githubusercontent.com/1079689/197806685-b08f400a-32f2-4561-9eb4-d6404ca714cf.png)

### Link to public reproduction project repository

....

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

...

### Did you find any workaround?

No,
How do I install the fonts ?

### Relevant log output

```shell
No
```

**Comment by danies8** [comment]
@PureWeen is there solution for this problem?

**Comment by Eilon** [comment]
This issue was moved to microsoft/microsoft-ui-xaml#7866
