### ISSUE TITLE
IOS Compiling Error

### ISSUE THREAD

**Issue by SantosVictorero** [dotnet/maui#10907]
### Description

Severity	Code	Description	Project	File	Line	Suppression State
Error		clang++ exited with code 1:
Undefined symbols for architecture x86_64:
  "_gprsharp_convert_clock_type", referenced from:
     -u command line option
  "_gprsharp_free", referenced from:
     -u command line option
  "_gprsharp_inf_future", referenced from:
     -u command line option
  "_gprsharp_inf_past", referenced from:
     -u command line option
  "_gprsharp_now", referenced from:
     -u command line option
  "_gprsharp_sizeof_timespec", referenced from:
     -u command line option
  "_grpcsharp_auth_context_peer_identity_property_name", referenced from:
     -u command line option
  "_grpcsharp_auth_context_property_iterator", referenced from:
     -u command line option
  "_grpcsharp_auth_context_release", referenced from:
     -u command line option
  "_grpcsharp_auth_property_iterator_next", referenced from:
     -u command line option
  "_grpcsharp_batch_context_create", referenced from:
     -u command line option
  "_grpcsharp_batch_context_destroy", referenced from:
     -u command line option
  "_grpcsharp_batch_context	XXX.xxx (Apps\XXX.xxx)	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.0.1271-rc.2-xcode14\targets\Xamarin.Shared.Sdk.targets	1230	

### Steps to Reproduce

1. Select IOS Simulator or Device
2. Rebuild

### Link to public reproduction project repository

N/A

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 14

### Did you find any workaround?

No

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error		clang++ exited with code 1:
Undefined symbols for architecture x86_64:
  "_gprsharp_convert_clock_type", referenced from:
     -u command line option
  "_gprsharp_free", referenced from:
     -u command line option
  "_gprsharp_inf_future", referenced from:
     -u command line option
  "_gprsharp_inf_past", referenced from:
     -u command line option
  "_gprsharp_now", referenced from:
     -u command line option
  "_gprsharp_sizeof_timespec", referenced from:
     -u command line option
  "_grpcsharp_auth_context_peer_identity_property_name", referenced from:
     -u command line option
  "_grpcsharp_auth_context_property_iterator", referenced from:
     -u command line option
  "_grpcsharp_auth_context_release", referenced from:
     -u command line option
  "_grpcsharp_auth_property_iterator_next", referenced from:
     -u command line option
  "_grpcsharp_batch_context_create", referenced from:
     -u command line option
  "_grpcsharp_batch_context_destroy", referenced from:
     -u command line option
  "_grpcsharp_batch_context	XXX.xxx (Apps\XXX.xxx)	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.0.1271-rc.2-xcode14\targets\Xamarin.Shared.Sdk.targets	1230
```

**Comment by SantosVictorero** [comment]
BTW, this app works fine with Android and Windows.

**Comment by lnaie** [comment]
I've just hit this wall with VS 2022 preview.

**Comment by SantosVictorero** [comment]
I have not been able to pair to my Mac either since I updated to Ventura:
See https://github.com/dotnet/maui/issues/10979

Also as you can see from my post this is a Grpc issue of .NET Maui and iOS.

I have been using Grpcweb with Blazor WebAssembly without any problems for a while.

Also as I said before, this app works fine with Android and Windows. Although I have not been able to use Windows with authentication do to another issue:
 https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?tabs=windows 

Hopefully all those issues are addressed ASAP.

**Comment by SantosVictorero** [comment]
Finally I was able to pair to my Mac and I created a repro of this bug at: https://github.com/SantosVictorero/Maui-Practice/tree/master

**Comment by eskaufel** [comment]
Is there any known workaround for this? I understand the implementation of the GRPC library causes this, but it is very problematic not to have any known way to support GRPC in MAUI on macos.

**Comment by AramMar** [comment]
hi @SantosVictorero, did you find any workaround for this issue?

**Comment by samhouts** [comment]
@rolfbjarne Any advice here?

**Comment by rolfbjarne** [comment]
Grpc is deprecated: https://grpc.io/blog/grpc-csharp-future/

Use [Grpc.Net.Client](https://www.nuget.org/packages/Grpc.Net.Client) instead: https://github.com/grpc/grpc-dotnet

See also https://learn.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-7.0

**Comment by SantosVictorero** [comment]
> hi @SantosVictorero, did you find any workaround for this issue?

Sorry @AramMar, I just saw your post. I never found a workaround, I had to postpone that project.

**Comment by AramMar** [comment]
thanks for your reply, i am using Grpc.Net.Client, unfortunately the same issue for that one also

**Comment by rolfbjarne** [comment]
> thanks for your reply, i am using Grpc.Net.Client, unfortunately the same issue for that one also

In that case, please file a new issue and provide a test project we can use to reproduce the problem.
