### ISSUE TITLE
Maui Blazor app truncated on Mac

### ISSUE THREAD

**Issue by johngsandiford** [dotnet/maui#10911]
### Description

When we run our app in Maui Blazor on Mac, the app is truncated.

Note that we do not have any issues running the same app on:

1. Maui Blazor on Windows
2. Blazor Server Side on Windows/Mac/Linux (various browsers)
3. Blazor WASM (various browsers)

The 3 images below, show the repro. code running on startup with statusbar missing.  Another shows the top part missing after scrolling down, and another when the app when maximized.  The maximized view is the expected view.

Hoping this is not expected behavior, but either way please advise.  Many thanks, John

<img width="544" alt="ResizeIssueTop" src="https://user-images.githubusercontent.com/8300961/197884772-5059c9d6-909e-4caa-8fbd-c13c5252742e.png">
<img width="553" alt="ResizeIssueBottom" src="https://user-images.githubusercontent.com/8300961/197884761-11a28a9c-21c0-43a5-87f9-509f8625ad07.png">
<img width="1280" alt="ResizeIssueMax" src="https://user-images.githubusercontent.com/8300961/197884769-09f8465c-c235-4d8f-ae3e-fa5b9f91d73d.png">

### Steps to Reproduce

1. Create Maui Blazor project.
2. Change code below.
3. Run on Mac  (we are using pkg to install, but that is probably irrelevant)

Index.razor 
------------------------------------------
```
@page "/"

<style>
    .flex-1-overflow {
        flex: 1;
        overflow: auto;
    }
</style>

<div class="m-0 p-0 d-flex flex-column vh-100">

        <div>Toolbar</div>

        <div class="flex-1-overflow m-0 p-0">
            <div>Main body</div>
        </div>

        <div>
            <div>Status bar</div>
        </div>

</div>
```

MainLayout.razor
------------------------
```
@inherits LayoutComponentBase

<main>
    @Body
</main>
```

### Link to public reproduction project repository

private but can provide pkg if required

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Latest mac

### Did you find any workaround?

No

**Comment by SteveSandersonMS** [comment]
@johngsandiford Thanks for letting us know.

At first glance it *looks* like this is just a CSS issue and perhaps an inconsistency in how Safari interprets `100vh` compared with other browsers. Safari has a concept of a "safe area" to account for the rounded corners of some devices, so you might need different styling rules.

I'd recommend you check other documentation about how to achieve 100% height reliably with Safari. If you track this down and become convinced it's a MAUI/Blazor bug, please let us know.

**Comment by johngsandiford** [comment]
Thanks for the reply, however we do not see the same issue in Safari on Mac, as shown in the first image below.  It is only in Maui Blazor on Mac that we see the issue.  

Furthermore, for our actual application, the entire toolbar is truncated rendering the app unusable, as shown in image 2.  When maximized, it shows fine, as in image 3.  Again, this only happens in Maui Blazor on Mac.  

Please advise, many thanks!

Repro code in Safari on Mac (no issue)
----------------------------
<img width="586" alt="SafariResize" src="https://user-images.githubusercontent.com/8300961/198869219-4e28b04a-108b-4cd1-a24f-6bb21e2f4909.png">

Actual App in Maui Blazor on Mac (issue as main toolbar truncated.  No issue on Windows)
--------------------------------------
<img width="931" alt="NoToolbar" src="https://user-images.githubusercontent.com/8300961/198869322-fd74b03a-fbe6-4dcf-8e02-492c72ecfaec.png">

Actual App in Maui Blazor on Mac Maximized (no issue as toolbar shows as expected)
--------------------------------------
<img width="1280" alt="WithToolbar" src="https://user-images.githubusercontent.com/8300961/198869334-e7520f27-1f8b-4c1b-94d2-ecc2ffb1e146.png">

**Comment by SteveSandersonMS** [comment]
Sorry for the confusion. When I said *how Safari interprets 100vh compared with other browsers* I really meant **WKWebView** rather than Safari. That's the actual webview you're using on Mac.

There are other notes on the internet from people observing issues with 100vh on WKWebView ([example](https://segmentfault.com/a/1190000040652799/en#item-2-5)). I'd recommend either:

 * Establishing whether the issue reproduces with the same CSS in a non-Blazor webview, either a plain MAUI webview or even a plain Mac Catalyst app webview
 * Or, researching [Apple's "safe area"](https://webkit.org/blog/7929/designing-websites-for-iphone-x/) approach further and finding a different CSS mechanism to achieve the layout you want

**Comment by johngsandiford** [comment]
Thanks @SteveSandersonMS .  The additional information was super helpful.  
The issue is with WKWebView as you suspected.  Detail is at https://bugs.webkit.org/show_bug.cgi?id=141832

For those who might have the same issue, the fix for us was to use the new viewport units (SVH, LVH, DVH, ...)

Thanks again.
