### ISSUE TITLE
Label WordWrap does not work inside HorizontalStackLayout or StackLayout with horizontal orientation

### ISSUE THREAD

**Issue by borrmann** [dotnet/maui#10917]
### Description

A Label with LineBreakMode="WordWrap" does not wrap the text when inside a HorizontalStackLayout or StackLayout with Orientation="Horizontal". It works with a VerticalStackLayout.

### Steps to Reproduce

1. Put a Label inside a HorizontalStackLayout
2. Set LineBreakMode to "WordWrap" and give it a long text
3. Label doesnt break its text

### Link to public reproduction project repository

https://github.com/borrmann/LabelBreak

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

iOS 16, Windows 10.0.171340.0

### Did you find any workaround?

no

**Comment by jsuarezruiz** [comment]
Similar or the same as https://github.com/dotnet/maui/issues/10046

**Comment by petrakritzinger** [comment]
Having the same issue, no workaround available. Breaking most of the layouts in our app. Please let us know when there is a workaround or a fix.

**Comment by JohnHDev** [comment]
@jsuarezruiz when might this get picked up? It is disheartening to see so many layout issues not being resolved in a timely manner.

**Comment by hartez** [comment]
This is expected behavior; horizontal stack layouts do not limit the horizontal space their child controls can consume, so there's no reason for a Label to ever wrap its text. 

If you need text to wrap, then you need to use a control which limits the horizontal space (like a Grid) or set a maximum width request on your horizontal layout.

**Comment by borrmann** [comment]
@hartez gotcha! 
However, shouldn't the Width of the HorizontalStackLayout be limited to the Width of its parent, e.g. if we have the HorizontalStackLayout inside a Grid like you suggested?

**Comment by hartez** [comment]
> @hartez gotcha! However, shouldn't the Width of the HorizontalStackLayout be limited to the Width of its parent, e.g. if we have the HorizontalStackLayout inside a Grid like you suggested?

No. Stacking layouts just keep stacking in their unconstrained direction until they run out of things to stack.

**Comment by BrianJSavage** [comment]
Not sure if this helps, but I had the same issue with word wrap not working. 
This was in a Grid cell, where the column definition width was set to "Auto". Changing to "*" it then wrapped **_without_** using LineBreakMode="WordWrap". Also I am using TextType="Html"
