### ISSUE TITLE
Clarification required: On screen keyboard #5272

### ISSUE THREAD

**Issue by get-flat** [dotnet/maui#10922]
### Description

Please provide code sample to achieve presented behavior: (tagging @jsuarezruiz)
https://github.com/dotnet/maui/issues/5272#issuecomment-1087632422

7.0.0-rc2 keyboard is not hidden on button click by default.

### Steps to Reproduce

Add an Entry view to default template-generated app.
Please clarify how to hide keyboard on button click.

### Link to public reproduction project repository

n/a

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13.0

**Comment by jsuarezruiz** [comment]
Could you share a sample where reproduce the problem?
