### ISSUE TITLE
GetChild value differs between horizontal and vertical orientation

### ISSUE THREAD

**Issue by RasikaPalanisamy** [dotnet/maui#10921]
### Description

We have a custom control in which we have custom scroll view and handler implementation.
In handler we have a class derived from the platform ScrollView , in that we have a method known as ComputeScroll() to provide implementation for scroll view, in that when we have tried to access the child element using this.GetChildAt(0), the value differs between vertical and horizontal orientation.
In vertical orientation the value of this.GetChildAt(0) is "ContentViewGroup". In horizontal orientation, the value is "MauiHorizontalScrollView".

Is this correct behavior? If not how to get the correct value using this.GetChildAt(0) in both scenario's Horizontal Orientation and Vertical Orientation?

### Steps to Reproduce

1. Derive a class for Plaform ScrollView,
2. Try to access the child element using GetChildAt(0) 
3. The value differs between horizontal and vertical orientation.

### Link to public reproduction project repository

NA

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9.0

**Comment by hartez** [comment]
This is the expected behavior - on Android, the ScrollView is composed of a vertical ScrollView and a nested ScrollView to provide horizontal scrolling. So if getChildAt(0) returns a MauiHorizontalScrollView, you'll need to call getChildAt(0) on the MauiHorizontalScrollView to get the actual content.
