### ISSUE TITLE
Publish Maui app as exe not work on window  10

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#10938]
### Description

Publish Maui app as exe not work

### Steps to Reproduce

1. Install window 10 on new virtual computer.
2.Creat a new Maui app.
3.Publish as exe using this command:
`dotnet publish -f net6.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -p:SelfContained=true -p:WindowsAppSDKSelfContained=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d"
`
4. the exe created but when I run it nothing happen.
5. Do I need to install any framework/SDKon this computer in order it will work ? Please give links

### Link to public reproduction project repository

....

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

.....

### Did you find any workaround?

No

### Relevant log output

```shell
No respond , and nothing in event viewer
```

**Comment by jsuarezruiz** [comment]
cc @jfversluis

**Comment by jfversluis** [comment]
Unpackaged apps are officially not supported right now. Also see #10564 

Additionally, whenever we do have it working, you will still need to make sure that all prerequisites, like having the Windows App SDK installed, are there. This is otherwise done through the MSIX installer.

Keep your eye on the linked issue for the progress on this, thanks!

**Comment by danies8** [comment]
@jfversluis 
I installed the first two files.
I installed the app according to https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps
![image](https://user-images.githubusercontent.com/1079689/198877036-6c059b87-ee45-4839-9fbc-dce5dc708103.png)
![image](https://user-images.githubusercontent.com/1079689/198876953-3afe0646-2e36-455b-8fb3-fee74772b507.png)
1. How do I installed the last tree files ?
2. I  added the  1.1.5 WindowsAppSDK throgh newget to the project and still the app is not running ?
3. Can you please help even if not official ?

**Comment by danies8** [comment]
@jfversluis Any answer?
