### ISSUE TITLE
[BUG][Android] Absolute Layout's layout flags and bounds not working in initial loading condition.

### ISSUE THREAD

**Issue by BalachandarSelvam** [dotnet/maui#10944]
### Description

My use case is that I need to change the height of the content in the Absolute layout by using the layout flags and the layout bounds when the app is loaded initially for the first time. For that I have used the overridden "OnSizeAllocated" method, as I need the height to do some calculation and then update the content height. But I wasn't able to control the height. I can able to change it dynamically, but in my scenario I need it at initial loading. I have reproduced this issue in sample level and attached it this report.

Note: All other platforms are working fine.

### Steps to Reproduce

1. Open and run the sample
2. you can able to see the label occupying full screen height but in "OnSizeAllocated" I have controlled the height.
3. Test in other platforms for better clarification
4. Click on toolbar item to change dynamically.

### Link to public reproduction project repository

https://github.com/BalachandarSelvam/Framework-bug/tree/main/LoadTimeChanges-Bug

### Version with bug

6.0.541
### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

### Did you find any workaround?

NO

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on Android API-33 with sample project. [LoadTimeChanges-Bug](https://github.com/BalachandarSelvam/Framework-bug/tree/main/LoadTimeChanges-Bug)
