### ISSUE TITLE
Multiple Collection Views don't display correctly with visual studio for Mac compiled for Mac Catalyst.

### ISSUE THREAD

**Issue by r3dgraphix** [dotnet/maui#10943]
### Description

I have one view page with two collection views and a button at the bottom. When running this in visual studio for windows compiled for Win all works fine. The exact same code compiled and run in visual studio for Mac compiled for Mac catalyst displays incorrectly. The first collection view displays fine, but everything below the first collection view including the second collection view and the button is not displayed. 

### Steps to Reproduce

1. create a maui project
2. Add two collection views to the view.
3. Add a button below the collection views.
4. populate the collection views from the code behind (ViewModel). I am using MVVM.
5. Run the app

### Link to public reproduction project repository

https://github.com/r3dgraphix/MauiBaseVS.git

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac OSX

### Did you find any workaround?

No work around

**Comment by jinxinjuan** [comment]
Verified this issue with VS for Mac 17.6 Preview(17.6.0.1569). Not repro on macOS platform with sample project. [MauiBaseVS.git](https://github.com/r3dgraphix/MauiBaseVS.git)
