### ISSUE TITLE
[Bug] VS2019 Template failed to generate correct MSIX project with template (wrong publisher, name, ...)

### ISSUE THREAD

**Issue by pellea** [dotnet/maui#1094]
### Description
New .NET MAUI project with the wrong MSIX template project is created.
The MSIX project is also not included in the solution.

![image](https://user-images.githubusercontent.com/395982/119720622-7ee9e280-be6a-11eb-81ac-542dea1b50ff.png)

![image](https://user-images.githubusercontent.com/395982/119720670-8dd09500-be6a-11eb-8bdf-19e9430737e3.png)

### Steps to Reproduce

1.  Create a new .NET MAUI project
2. Voila

### Expected Behavior
Correct name, assembly name, publisher display name, ...

### Actual Behavior
Displays "WeatherTwentyOne" and publisher "Microsoft" for a new project.

**Comment by hartez** [comment]
Looks like PR #1093 will fix the app name portion of this bug, at least.

**Comment by jfversluis** [comment]
The afore mentioned PR is merged, I think this is fixed with that. Let us know if that isn't the case.
