### ISSUE TITLE
.NET MAUI App Icon and Splash screen cannot be customized

### ISSUE THREAD

**Issue by 0nly1ken0bi** [dotnet/maui#10949]
Okay sooooo.. I ran into this same issue however, **I've managed to get it working** with my own custom app icon and well as my own custom splash screen.  Albeit it's not an animated splash screen, I was getting the exact same issues described above.

What I did was this.

1. Opened the Emulator and deleted the actual app from the device ( which I don't think was necessary)
2. Renamed the old SVG files to splash_old.svg and appiconfg_old.svg respectively ( which I don't think was necessary)
3. Added my custom splash.svg and appiconfg.svg files into their respective folders
4. Edited the csproj file namely removing this `Color="#512BD4" ` from this line `<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg"/>`
5. Run a Rebuild Solution
6. Run Build to Pixel 5 - API 33 (Android 13.0 - API 33)

Custom Icon:

![Custom_Icon](https://user-images.githubusercontent.com/54916539/198154875-60a22170-1eb5-499d-a7fc-806c3686f1f8.PNG)

Custom Splash Screen:

![Custom Splash](https://user-images.githubusercontent.com/54916539/198154953-28ce9d0c-bb99-46ed-8f04-68efbea25dd4.PNG)

Hope this helps.

https://github.com/dotnet/maui/issues/10079#issue-1370643762

**Comment by activa** [comment]
So what exactly is the issue? Your description doesn't say what you expect to happen or what is not working as you expected.

**Comment by 0nly1ken0bi** [comment]
I've linked the original issue [here](https://github.com/dotnet/maui/issues/10079#issue-1370643762)  as well as at the end of my post above.

I was having the exact same issue described in that post.

I was replying on that thread but for some reason I was asked to create a new issue and link it to the original thread which I did at the end of my post above.

I'll re-iterate here what the issue is and how to replicate it.

1. Create a new .Net Maui app
2. Build the Solution to Android Emulator
3. Note the icon and splash screen
4. Create a new custom splash.svg and appiconfg.svg files
5. Rebuild the solution
6. The original splash.svg and appiconfg.svg are still being shown

My original post above proposed a workaround to this issue as none was offered in the original thread.

Hope this clarifies what the issue is and how too circumvent it.

It would seem that during the Build process the csproj file is somewhat buggy as only when I edited the csproj file namely removing this` Color="#512BD4" `from this line `<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg"/>` did it actually work by displaying my custom splash.svg and appiconfg.svg files.


Please go and read the original [thread ](https://github.com/dotnet/maui/issues/10079#issue-1370643762) where this was reported on.

**Comment by mattleibow** [comment]
In step 5. Rebuild the solution, are you doing a rebuild with like a clean and build, or just running F5 again?

There may be an issue where the contents of the icon does not trigger a new image to be generated. But for a full rebuild, this should alway re-generate the images.

**Comment by mattleibow** [comment]
I think this PR will fix the splash screen since we now hash both the contents and the attibutes of splash screens: https://github.com/dotnet/maui/pull/10812

But, icons are just normal images with a special attribute so I may need to verify that there is somehting similar for images.

**Comment by 0nly1ken0bi** [comment]
> In step 5. Rebuild the solution, are you doing a rebuild with like a clean and build, or just running F5 again?
> 
> There may be an issue where the contents of the icon does not trigger a new image to be generated. But for a full rebuild, this should alway re-generate the images.

I used the Build/Rebuild Solution menu option which rebuilt the entire solution

**Comment by 0nly1ken0bi** [comment]
> I think this PR will fix the splash screen since we now hash both the contents and the attibutes of splash screens: #10812
> 
> But, icons are just normal images with a special attribute so I may need to verify that there is somehting similar for images.

Fingers crossed

**Comment by 0nly1ken0bi** [comment]
Using Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.4.0 Preview 6.0

Half the problem seems to be fixed whereby the splash screen is working when changing the `splash.svg` files to a custom file however, the App Icon remains unchanged.

Steps to duplicate issue:

1. Open Visual Studio Community 2022 (64-bit) - Preview 2022 | Version 17.4 Preview 6.0
2. Create new MAUI App and leave the defaults as is
3. Build the Solution to Android Emulator i.e. Pixel 5 - API 33 (Android 13.0 - API 33)
4. Note the App icon as being the default .Net purple and white icon
5. Close Emulator
6. Create a custom `appicon.svg`  int the `..Resource/AppIcon` folder and rebuild the the app to Android Emulator
7. Note that the default app icon hasn't changed on the device emulator which still shows the default .Net appicon.svg
8. Close Emulator
9. Edit the line in the  csproj  file `<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />` and delete the `Color="#512BD4"` portion
10. . Build the Solution to Android Emulator i.e. Pixel 5 - API 33 (Android 13.0 - API 33)
11. Note now that appicon on the emulator device now has your custom appicon.svg dispalyed

Only by editing the csproj does it allow you to display your custom app icon which eludes to the csprog file still being somewhat buggy.

Please follow the steps above to replicate the issue.

**Comment by 0nly1ken0bi** [comment]
Update

Using Version 17.4.0 after the Preview version of Microsoft Visual Studio Community 2022 (64-bit) seems to have fixed the issue. 

I'll close this issue now.
