### ISSUE TITLE
Grid row height not calculated correctly when set to auto and used with multiple columns of width *

### ISSUE THREAD

**Issue by damienpenman** [dotnet/maui#10956]
### Description
Grid row height not calculated correctly when set to auto and used with multiple columns of width *. The calculated height is not enough, resulting in the contents being clipped.

### Steps to Reproduce
Create a grid with a row definition of Auto and at least 2 columns with definitions of *.
Place a label into the first column with a long text attribute, and it's height will not be calculated correctly, resulting in the text being clipped.

(See code below).

```
<Grid RowDefinitions="Auto" ColumnDefinitions="*,*" >
           <Label Grid.Row="0" Grid.Column="0"  BackgroundColor="Blue" Text="This is some long text 1. This is some long text 2. This is some long text 3. This is some long text 4. This is some long text 5. This is some long text 6. This is some long text 7. This is some long text 8. This is some long text 9. This is some long text 10. This is some long text 11. This is some long text 12. This is some long text 13. This is some long text 14. END."></Label>
</Grid>
```

If the grid contains just a single column of width *, then the problem does not occur.

### Link to public reproduction project repository
n/a

### Version with bug
7.0.100-rc.2.22477.23

### Last version that worked well
Unknown

### Affected platforms
All

### Affected platform versions
All

### Did you find any workaround?
No

### Relevant log output
None

**Comment by mike3sullivan** [comment]
Also seeing big layout problems with RC2 associated with grid. Dumping RC2 work as well.

**Comment by PureWeen** [comment]
@damienpenman  this should be fixed once GA releases. 

If not let us know.

**Comment by IgorKravchenko10** [comment]
I have related issue after updating to Visual Studio Preview 4. All my layouts in cards were broken.
How it was before
![Screenshot_20221006-233806](https://user-images.githubusercontent.com/8657879/198530376-a21be749-1efd-4fe6-83ad-931de31f696c.jpg)

Now
![Screenshot_20221026-211907](https://user-images.githubusercontent.com/8657879/198530417-f5a2fd85-c2d7-4266-803a-9b56397f1829.jpg)
Note, my card is a custom control based on material android Card. All was good in VS Preview 3.

**Comment by AndreasReitberger** [comment]
Same here, I needed to set the `RowDefinition` to `Auto`, even for Grids with one row. Then it looked like before.
