### ISSUE TITLE
Navigation.TitleView/Title doesn't work

### ISSUE THREAD

**Issue by ClaudiuAndries** [dotnet/maui#10965]
### Description

I try to create a title image for .net maui android application, but the title is not visible. Even if I change with a label, same result:
https://imgur.com/a/AitiWWf

Visual studio version:17.3.6

### Steps to Reproduce

Create .net maui project
On main page add :
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage  xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Project.Views.MainPage"
			 >

	<NavigationPage.TitleView>
		<Label Text="Test" TextColor="Black"/>//or image
		
	</NavigationPage.TitleView>

</ContentPage>
```

### Link to public reproduction project repository

https://github.com/ClaudiuAndries/-Minimal-Reproducible-Example

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 12

**Comment by PureWeen** [comment]
@ClaudiuAndries it looks like you're not using a NavigationPage

if you set your root page to a `NavigationPage` does it fix it?

**Comment by ClaudiuAndries** [comment]
> @ClaudiuAndries it looks like you're not using a NavigationPage
> 
> if you set your root page to a `NavigationPage` does it fix it?

no, i have same problem with NavigationPage, but should work with ContentPage.

**Comment by ClaudiuAndries** [comment]
Problem fixed!
on App.xaml.cs i change my code:
`public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		MainPage = new NavigationPage(new MainPage());
	}
}
`
