### ISSUE TITLE
Visual Studio is not able to pair to Mac after Ventura upgrade

### ISSUE THREAD

**Issue by AlexeyBKuznetsov** [dotnet/maui#10979]
### Description

Visual Studio 17.4 Preview 5 is not able to pair to Mac after upgrade to Ventura. Showing the error below
![image](https://user-images.githubusercontent.com/47281114/198691329-b586127d-6458-4a1f-91ff-a0727425b84d.png)

### Steps to Reproduce

1. Start Visual Studio 17.4 Preview 5
2. Open MAUI project
3. Click Pair to Mac button from the visual Studio toolbar

### Link to public reproduction project repository

NA

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

NO workaround

**Comment by crazypmer** [comment]
Having the same issue

**Comment by AlleSchonWeg** [comment]
Perhaps this helps: https://stackoverflow.com/questions/74215881/vs-2022-wont-connect-with-mac-after-ventura-upgrade

**Comment by dajbych** [comment]
I can confirm it is fixed in Visual Studio 2022 17.4.
