### ISSUE TITLE
The name Resources is reserved and cannot be used

### ISSUE THREAD

**Issue by whann0205** [dotnet/maui#10975]
### Description

![grafik](https://user-images.githubusercontent.com/71807453/198523124-1b62db9d-b454-4b37-b0e6-d97c2ace84db.png)
Cannot build project for locally attached iphone, because of that error above.

### Steps to Reproduce

1. Select local IOS Device for example in my case "Iphone of wolfgang"
1. Create a folder database under the existing folder Resources
2. Add in the itemgroup section of csproj file
    
   <MauiAsset Include="Resources\Database\*" />
3. Build project
4. Encounter error 

### Link to public reproduction project repository

None

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS15,IOS16

### Did you find any workaround?

Yes working with the simulator, since the problem only appear when
directly deployed to a local attached iphone.

**Comment by rachelkang** [comment]
Hi, @whann0205 - thanks for submitting this issue. Could you please attach a binlog so that we can investigate further?

https://learn.microsoft.com/visualstudio/ide/how-to-view-save-and-configure-build-log-files?view=vs-2022

**Comment by whann0205** [comment]
[AssetQueryApp_Debug_AnyCPU_net6.0-ios_Build_2022-10-28T18_07_25.7673831+02_00.zip](https://github.com/dotnet/maui/files/9890069/AssetQueryApp_Debug_AnyCPU_net6.0-ios_Build_2022-10-28T18_07_25.7673831%2B02_00.zip)
Here you are....

**Comment by whann0205** [comment]
I found a workaround myself.
I put the .db File from the database directory into the predefined raw folder.
![grafik](https://user-images.githubusercontent.com/71807453/198870175-a700f317-3dab-4342-842a-0cb2826f3ebc.png)

**Comment by hartez** [comment]
@davidbritch Is this currently documented anywhere?

**Comment by mattleibow** [comment]
Not sure this is a bug as that code looks like the correct and designed way?

I think the issue may also have been that the MauiAsset also needs the LogicalName attribute. This is because if you just include the path, then it tries to match that path n the app package which is not supported on iOS. Using the LogicalName effectively redirects the csproj path into a different location in the app package.
