### ISSUE TITLE
[Android] Entry control: Closing onscreen keyboard manually resizes modal page height

### ISSUE THREAD

**Issue by SailDev** [dotnet/maui#10978]
### Description

On a modal page, i enter some text in an entry control. When i close the onscreen keyboard manually, the modal page height gets resized and reveals parts of the underneath page.

**This behaviour does only occur, if you actually enter some value in the entry control.** 

| A | B |
| :-: | :-: |
| ![Screenshot_1666960004](https://user-images.githubusercontent.com/94922306/198595193-5824144a-258b-4aba-93a0-e49974464e4c.jpg) | ![Screenshot_1666960018](https://user-images.githubusercontent.com/94922306/198595406-c506b543-845a-474f-a483-347be6baf4e6.jpg) |

### Steps to Reproduce

1. Create a new Maui app (net6.0).
2. Add a ContentPage (Page1).
3. Add 2 Entry controls to Page1.
4. Use the "OnCounterClicked" event handler, to open Page1 as modal page (await Navigation.PushModalAsync(new Page1());)
5. Run the app.
6. Open Page1.
7. Enter something in the Entry control.
8. Close the onscreen keyboard manually.

### Link to public reproduction project repository

https://github.com/SailDev/Net-Maui-bug-reproduction-example-001.git

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by AndreasReitberger** [comment]
Having the same issue. On iOS, the keyboard overlaps the content. On Android the content gets scrolled out fine, so that the current entry is not overlapped by the keyboard.
However there, after dismissing the content stays scrolled out, like described in the issues above.

**Comment by Kremed** [comment]
@AndreasReitberger 
Did you get any temporary solution to this problem? Or should I wait for the next releases?

**Comment by AndreasReitberger** [comment]
@Kremed 
Sadly no... ☹️

**Comment by Kremed** [comment]
Last version that worked well

- Android 10  ✅
- Samsung Note 9

**Comment by Kremed** [comment]
@jamesmontemagno  any suggestions?

**Comment by PureWeen** [comment]
Can you try the workaround from this issue? https://github.com/dotnet/maui/issues/11274

See if that resolves this for you?

I was able to reproduce this issue and then when I applied that workaround it no longer reproduced

**Comment by RonnyRos** [comment]
I can confirm this worked for me. Thanks !

**Comment by mrswdev** [comment]
Tested and it solves the problem. MANY THANKS!

**Comment by SailDev** [comment]
Tested and it solves the problem. Many THANKS!
