### ISSUE TITLE
CascadeInputTransparent="False" is not working on ContentView

### ISSUE THREAD

**Issue by pauldendulk** [dotnet/maui#10977]
### Description

If a ContentView has InputTransparent set to true and CascadeInputTransparent set to false the child controls do not receive input.

### Steps to Reproduce

1. Create a new Maui app in Visual Studio with the button click sample code.
2. Replace the content of MainPage.xml with:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="CascadeInputTransparent.MainPage">

    <ContentView
        InputTransparent="True"
        CascadeInputTransparent="False">    
        <Button
            x:Name="CounterBtn"
            Text="Click me"
            SemanticProperties.Hint="Counts the number of times you click"
            Clicked="OnCounterClicked"
            HorizontalOptions="Center" />
    </ContentView>
</ContentPage>
```
3. Click the button and nothing happens.

### Link to public reproduction project repository

https://github.com/pauldendulk/CascadeInputTransparentBug

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

Not one that solves my problem.

Note, this problem also exists in the ScrollView. It does not exist in the VerticalStackLayout. I did not test anything else.

**Comment by mattleibow** [comment]
This is an interesting one because CascadeInputTransparent is really only on Layouts, but now ContentView is also a Layout... @hartez not sure if this was a conscious decision to always make ContentView cascade (and the property is not supposed to be there) or is this a bug?

**Comment by homeyf** [comment]
![image](https://github.com/dotnet/maui/assets/82450723/84239d7c-9610-4306-a4e3-7b970c2c029c)

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Windows platform with sample project.
https://github.com/pauldendulk/CascadeInputTransparentBug
![image](https://github.com/dotnet/maui/assets/82450723/2bea987f-42ad-467e-877e-f4b8ac3d1994)

**Comment by ederbond** [comment]
Any news about this? @davidortinau @mattleibow @jfversluis @rmarinho @StephaneDelcroix @PureWeen ?
