### ISSUE TITLE
Attached methods of layouts should take IView parameter instead of BindableObject

### ISSUE THREAD

**Issue by MhAllan** [dotnet/maui#10988]
### Description

When `Grid.Children[i]` returns `IView` then we expect `Grid.GetColumn(obj)` to also take `IView` parameter, but it seems to be taking `BindableObject` which looks a bit weird and wrong for me. shouldn't we always work with interfaces? If a `Grid` child is an IView then you should be able to `GetColumn(IView)`

**Comment by hartez** [comment]
This is an artifact of backward compatibility with Forms (where everything is a BindableObject and which supports attached methods). 
`IView` comes from MAUI.Core, which doesn't use attached methods, so the equivalent methods (`GetColumn`, `GetRow`, etc.) are directly on the `IGridLayout` interface. If you cast the `Grid` to an `IGridLayout`, you can call those methods directly with an `IView` parameter. At the moment, we don't intend to add static methods to `Grid` which take `IView`.

@MhAllan Other than looking a little awkward, is this causing any specific issues for you?

**Comment by MhAllan** [comment]
no issue, I can always do the cast
