### ISSUE TITLE
\obj\project.assets.json' doesn't have a target for 'net6.0-windows10.0.19041.0'. Ensure that restore has run and that you have included 'net6.0-windows10.0.19041.0' in the TargetFrameworks for your project.

### ISSUE THREAD

**Issue by Qws** [dotnet/maui#10984]
### Description

I can't build/debug the project for Windows, Android (and probably any other platform).

- Restore nuget packages doesn't work (it doesn't even try.)
- Cleaning project doesn't work.
- Changing location of the project doesn't work.

I don't know what to do, so I decided to make a ticket.

But every action basically leads to this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'C:\MyProjectMaui\MyProjectMaui\obj\project.assets.json' doesn't have a target for 'net6.0-windows10.0.19041.0'. Ensure that restore has run and that you have included 'net6.0-windows10.0.19041.0' in the TargetFrameworks for your project.	MyProjectMaui	C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	
```

The platform dependencies have these warning marks:
![image](https://user-images.githubusercontent.com/3944421/198748338-ae6fef58-b71d-475f-9286-0c12683c78c1.png)

I can't do anything...

0 nuget packages are installed, it's completely empty, not even the default nuget packages are installed. Neither can I install nuget packages.

If I open my project file, and compare it to a newly fresh Maui project, it looks fine and identical. So I don't know what happened.

Everything worked fine untill I have succesfully published my first MAUI app to the Google Play Store and Microsoft Store.

### Steps to Reproduce

I have no clue what happened....

This problem only appeared after I have succesfully published my first MAUI app to the Google Play Store and Microsoft Store.

Perhaps something is wrong with one of these build script?

`msbuild .\MyProjectMaui\MyProjectMaui.csproj /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:configuration=release /p:GenerateAppxPackageOnBuild=true`

`dotnet publish -c Release -f:net6.0-android`

I have also downgraded from VS2022 Preview version to the VS2022 Stable version. I suspect that to be the main issue?

### Link to public reproduction project repository

I can't replicate this error on my other projects, I suspect this error is created by "downgrading" VS2022 Preview -> VS2022 Stable.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 10.0.19041.0 and Android 12 (Api 31)

### Did you find any workaround?

Sadly no, I can't continue with my Maui project at all. I can't build or debug the Maui project.

**Comment by VladislavAntonyuk** [comment]
you missed ".0" in target framework: `msbuild .\MyProjectMaui\MyProjectMaui.csproj /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041.0 /p:configuration=release /p:GenerateAppxPackageOnBuild=true`
