### ISSUE TITLE
Error HE0046: Failed to install the app ... simctl returned exit code 1

### ISSUE THREAD

**Issue by whann0205** [dotnet/maui#10998]
### Description

error HE0046: Failed to install the app 'com.companyname.mauiappblazor' on the device 'iOS 16.1 (20B72) - iPhone 11': simctl returned exit code 1

I try to use the native ios simulator (the one on the mac build host)

### Steps to Reproduce

1. Create a new Maui Project (does  not matter if Blazor or traditional) 
2. Select .net 6
3. Go to Tools/Xamarin und deselect the option Remote Simulator to Windows
4. Select IOS Simulators any Iphone 
5. Start Debug

### Link to public reproduction project repository

None

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16

### Did you find any workaround?

No. But i can use the Windows IOS Simulator by simply recheck the Remote Simulator
to Windows

**Comment by hartez** [comment]
@dalexsoto Thoughts?

**Comment by dalexsoto** [comment]
Any chance you can provide the install logs?

**Comment by whann0205** [comment]
Sure, just tell me where do i find the logs?

**Comment by whann0205** [comment]
I would be glad to help if someone could be so kind and answer my question what logs are needed and where do i find them.

**Comment by tj-devel709** [comment]
@rolfbjarne @davidbritch Do either of you know where docs on how to find installation logs on Visual Studio may be? Alex is referring to the logs similar to the ones produced on Visual Studio Mac inside the "Deploying to Device" section

**Comment by davidbritch** [comment]
@tj-devel709 Afraid there aren't any docs on device provisioning for MAUI.

**Comment by PureWeen** [comment]
Help => Xamarin => Open Logs

You can zip those up and attach/upload

**Comment by whann0205** [comment]
I uninstalled the old Visual Studio 2022 Version Preview since the trail would run out anyway.
I installed the new Visual Studio 2022 Version 17.5.0 Preview 1.0.
Make exactly the same thing with the same mac.
All is working no error. Strange not the first time strange errors suddenly went away by
installing a new version. Have not found anything regarding that issue in the change logs.
