### ISSUE TITLE
[Enhancement] Replace some APIs with existing .NET ones

### ISSUE THREAD

**Issue by ChaseFlorell** [dotnet/maui#110]
## Summary
Forms duplicated a lot of APIs due to limitations at the time. Now that more and more .NET is becoming available to all platforms, now is the time to drop those duplicate API's in favor of exising ones.

## API Changes

System.Maui.Color => System.Drawing.Color
System.Maui.Point => System.Drawing.Point
.. and others

// perhaps
System.Maui.Thickness => System.Windows.Thickness (or maybe they both move to a common one)

## Intended Use Case
Reduce code maintenance within the Maui namespace and not duplicate API's unnecessarily.

**Comment by dotMorten** [comment]
Also System.Maui.Size -> System.Drawing.Size
