### ISSUE TITLE
AngularJS is not rendering in WebView on Android

### ISSUE THREAD

**Issue by vovanb** [dotnet/maui#11007]
### Description

AngularJS does not work in MAUI WebView despite enabling HTML5 features as it was recommended by https://stackoverflow.com/questions/10599739/does-android-webview-browsers-support-html5-features.
Using handler.PlatformView I added below settings but problem still exist:
 ```
 Microsoft.Maui.Handlers.WebViewHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
        {
            if (view is MyCustomWebView)
            {
#if ANDROID
                Android.Webkit.WebView webView = handler.PlatformView;
                webView.Settings.JavaScriptEnabled = true;
                webView.Settings.MixedContentMode = Android.Webkit.MixedContentHandling.AlwaysAllow;
                webView.Settings.PluginsEnabled = true;
                //webView.Settings.UserAgentString = 
                
                webView.Settings.AllowContentAccess = true;
                webView.Settings.LightTouchEnabled = true;
                webView.Settings.AllowFileAccess = true;
                webView.Settings.SetSupportMultipleWindows(true);
                webView.Settings.DatabaseEnabled = true;
                webView.Settings.DatabasePath = "/data/data/session/databases/";
                webView.Settings.DomStorageEnabled = true;
                webView.Settings.SetAppCacheEnabled(true);
                webView.Settings.SetAppCacheMaxSize(1024 * 1024 * 8);
                webView.Settings.SetAppCachePath("/data/data/session/cache/");
                webView.ClearCache(true);


#endif
            }
        });
 ```

### Steps to Reproduce

1. add to default MAUI project WebView 
2. use [navigate to ](https://material.angularjs.org/latest/demo/menu) as URL for demo
3. create WebViewHandler to update webView.Settings

### Link to public reproduction project repository

https://github.com/Enghouse-CCSP-PS/MAUI_WebViewIssue

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13.0 API 33 Emulator

### Did you find any workaround?

no

### Relevant log output

```shell
no relevant errors
```

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on android platform with sample project.
[MAUI_WebViewIssue-master.zip](https://github.com/dotnet/maui/files/11717241/MAUI_WebViewIssue-master.zip)
![Screenshot 2023-06-12 112403](https://github.com/dotnet/maui/assets/77434865/2090614c-dbc4-4117-a844-51fc547531ad)
