### ISSUE TITLE
IOS ListView with HasUnevenRows = True crashes app - bug has been reintroduced

### ISSUE THREAD

**Issue by Vpatel541** [dotnet/maui#11019]
### Description

So I have been working on an app in android and have a ListView with the property of HasUnvenRows = True. This works in Android. However when testing the app in IOS in Visual Studios 2022 for Mac, the app crashes when this is set. 

### Steps to Reproduce

1. Create a new project in VS for Mac
2. Create a ListView
3. Set HasUnevenRows = true
4. Run the app
5. see the crash

### Link to public reproduction project repository

none

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

None

**Comment by Vpatel541** [comment]
https://github.com/Vpatel541/DotNetMauiListViewBug-

**Comment by Vpatel541** [comment]
So I realized that this bug comes from calling Dispatcher.Dispatch and populating the ListView twice in iOS. This will crash in iOS but not crash in Android.

**Comment by Vpatel541** [comment]
Also changing HasUnevenRows to a specified RowHeight fixes this for some reason but I want to use UnevenRows

**Comment by jsuarezruiz** [comment]
Can reproduce the issue with rc2 but cannot reproduce it with current 7.0 branch (upcoming 7.0 ga).
<img width="480" alt="Captura de pantalla 2022-11-04 a las 10 05 45" src="https://user-images.githubusercontent.com/6755973/199934964-93acf47a-a1c8-462f-85b0-4a232683e12a.png">

**Comment by Vpatel541** [comment]
> Can reproduce the issue with rc2 but cannot reproduce it with current 7.0 branch (upcoming 7.0 ga). <img alt="Captura de pantalla 2022-11-04 a las 10 05 45" width="480" src="https://user-images.githubusercontent.com/6755973/199934964-93acf47a-a1c8-462f-85b0-4a232683e12a.png">

Is the upcoming 7.0 the preview edition? or in Visual Studios 2022?

**Comment by Vpatel541** [comment]
This is an Issue with IOS not android

**Comment by jsuarezruiz** [comment]
Cannot reproduce the crash with the latest version (net 7 ga). Could you try with the latest version?
![image](https://user-images.githubusercontent.com/6755973/202189143-0d79cfa6-330c-4cbc-89bd-3cc973668316.png)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0 and VSM 17.6 (build 1575)(net7). Not repro on iOS platform with sample project.
https://github.com/Vpatel541/DotNetMauiListViewBug-
![Screenshot 2023-07-13 155058](https://github.com/dotnet/maui/assets/77434865/786b6235-a786-4fd0-813b-71b01f405d61)
