### ISSUE TITLE
FlyoutBackgroundColor not working when FlyoutBehavior is locked.

### ISSUE THREAD

**Issue by JiuLing-zhang** [dotnet/maui#11028]
### Description

It's can work when FlyoutBehavior is not locked.
It's can work when using hot reload.

I created the same [error 7321](https://github.com/dotnet/maui/issues/7321) last time, the bug was marked as resolved, but it didn't work.

### Steps to Reproduce

1. Create MAUI App.
2. Edit AppShell page.
3. Set 
    Shell.FlyoutBehavior="Locked"
    FlyoutBackgroundColor="Gray".
4. Run.

### Link to public reproduction project repository

https://github.com/JiuLing-zhang/MauiError001.git

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows Server 2019 Datacenter (version : 1809)

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on android and windows platform with above project.
https://github.com/JiuLing-zhang/MauiError001.git
![image](https://github.com/dotnet/maui/assets/82450723/3cc1dfde-60c8-47da-96e2-ed5c48ed8de5)

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on windows platform with above project.
https://github.com/JiuLing-zhang/MauiError001.git
![image](https://github.com/dotnet/maui/assets/82450723/1fae4c76-3494-4a86-bf06-d2ac53328aa9)
