### ISSUE TITLE
When the flow direction is changed in ScrollView as RTL, the scrolling direction remains unchanged in iOS and macOS

### ISSUE THREAD

**Issue by anandhan-rajagopal** [dotnet/maui#11026]
### Description

Change the flow direction as RTL in ScrollView, but the scrolling direction remains unchanged in iOS and macOS platforms.

### Steps to Reproduce

1. Run the sample on the iOS and macOS platform
2. We have to scroll from the left to the right direction to see the children which are arranged based on RTL flow direction.

### Link to public reproduction project repository

https://github.com/anandhan-rajagopal/ScrollView_Issue

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 11 or higher, macOS 11.15 or higher

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Not repro on iOS and macOS with sample project.
[ScrollView_Issue](https://github.com/anandhan-rajagopal/ScrollView_Issue).

**Comment by samhouts** [comment]
Duplicate of #10755
