### ISSUE TITLE
CollectionView: RemainingItemsThreshold not working properly

### ISSUE THREAD

**Issue by stelian-dev** [dotnet/maui#11037]
### Description

RemainingItemsThresholdReachedCommand it's called before RemainingItemsThreshold is reached.
See the attached git repository.

### Steps to Reproduce

-Create a CollectionView
-Set ItemsSource
-Set RemainingItemsThreshold 
-Set RemainingItemsThresholdReachedCommand

### Link to public reproduction project repository

https://github.com/stelian-dev/maui-collectionview-RemainingItemsThreshold

### Version with bug

7.0 Release Candidate 1

### Last version that worked well

7.0 Release Candidate 1

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

android 13

### Did you find any workaround?

no

**Comment by hartez** [comment]
See also #10078 and #9935

**Comment by angelru** [comment]
I posted a similar problem in Xamarin.Forms a long time ago
https://github.com/xamarin/Xamarin.Forms/issues/11060

**Comment by stelian-dev** [comment]
The issue seems to be caused by the fact that the <CollectionView> was placed inside a <ScrollView>. After removing the <ScrollView>, the <CollectionView> works fine.
