### ISSUE TITLE
Win32 exception on startup when using dependency injection with ContentPage

### ISSUE THREAD

**Issue by oracleguy** [dotnet/maui#11038]
### Description

Maui application crashes with Win32 exception on startup once a non-default constructor is added to a content page in a Maui shell application.
![image](https://user-images.githubusercontent.com/11576872/199281125-2c8a4a52-cb78-455d-b488-8976c933391f.png)

This crash seems to also happen if the dependency is added to the service collection or not.

This is on Windows 10 22H2. I could make the crash happen with Visual Studio 17.3 on net 6.0 and Visual Studio 17.4 Preview 5 on net 7.0.

![image](https://user-images.githubusercontent.com/11576872/199282550-5dfdbb15-d892-47df-8aa3-85d63a719339.png)

### Steps to Reproduce

1. Create a new Maui application in Visual Studio
2. Create a new public class in the application named "PageViewModel"
3. Add the class to the service collection in MauiProgram.cs: `builder.Services.AddTransient<PageViewModel>();`
4. Modify the MainPage code behind to have a constructor that takes the PageViewModel class.
5. Start the application under Windows.
6. Observe Win32 crash.

### Link to public reproduction project repository

https://github.com/oracleguy/mauicrash

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 22H2

**Comment by mattleibow** [comment]
Make sure to al add the PAGE to the services as DI looks for the page first, and then uses DI to locate the parameters. If you don't add the page, then it has no starting point.

**Comment by oracleguy** [comment]
Yes, the page being missing was the source of the problem. I appreciate the help.

If I add the page but not the VM, I also get a Win32 exception. Seems like if there is a problem resolving the dependency tree, that Win32 exception happens. Seems like there is still a bug in there since a more specific managed exception would easier for developers to track down.

**Comment by PureWeen** [comment]
I'm going to close this one for now. This exception originates from the MS.EXT.DI component when it fails to resolve. The vagueness of Windows exceptions comes from WinAppSDK not us as well. We are hopeful those messages will propagate with more info in the near future!
