### ISSUE TITLE
iOS Build Fails with "The application has not been built" on VS Mac

### ISSUE THREAD

**Issue by BenBtg** [dotnet/maui#11036]
### Description

Using VSMac to build and MAUI app created using VS2022.

Build succeeds with no errors. But follow popup appears claiming it has not been built.

<img width="302" alt="Screenshot 2022-10-31 at 16 18 25" src="https://user-images.githubusercontent.com/70525/199249287-5ff4188d-3737-4f55-b3ea-3d2ea6e982a6.png">

### Steps to Reproduce

Create MAUI app in VS2022 on Windows.

Open repo in VSMac.

Build and run iOS target.
Build completes with no errors. 
But following error appears
<img width="302" alt="Screenshot 2022-10-31 at 16 18 25" src="https://user-images.githubusercontent.com/70525/199249978-51b2f36a-c2ec-4c63-89b7-9849f73e7b77.png">

### Link to public reproduction project repository

Only private repo available

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Removing Android target in the shared project seems to work around the issue.

### Relevant log output

Building XApp (Debug)
Build started 10/31/2022 16:56:23.
Environment at start of build:
DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR = /usr/local/share/dotnet
VISUAL_STUDIO_BUNDLE_PATH      = /Applications/Visual Studio.app
COMMAND_MODE                   = unix2003
HOME                           = /Users/benbtg
VISUAL_STUDIO_UPDATER_DATA_FILE = /Users/benbtg/Library/Caches/VisualStudio/17.0/TempDownload/index.xml
COMPlus_EnableDumpOnSigTerm    = 1
DYLD_BIND_AT_LAUNCH            = 1
SHELL                          = /bin/zsh
COMPlus_DbgEnableFastHeapDumps = 1
__CFBundleIdentifier           = com.microsoft.visual-studio
VISUAL_STUDIO_PID              = 83877
VISUAL_STUDIO_UPDATER_LOG      = /Users/benbtg/Library/Logs/VisualStudio/17.0/Updater-83877.log
XPC_SERVICE_NAME               = application.com.microsoft.visual-studio.39062747.39063256
ServiceHubLogSessionKey        = E2E47E5E
COMPlus_EnableCrashReport      = 1
MSBUILD_EXE_PATH               = /usr/local/share/dotnet/sdk/6.0.402/MSBuild.dll
LOGNAME                        = benbtg
TMPDIR                         = /var/folders/r9/9tfbs4p53sz4hh9h11jkfvv80000gn/T/
MSBuildUserExtensionsPath      = /Applications/Visual Studio.app/Contents/MonoBundle/AddIns/MonoDevelop.Docker/MSbuild
MSBuildSDKsPath                = /usr/local/share/dotnet/sdk/6.0.402/Sdks
USER                           = benbtg
VISUAL_STUDIO_DOWNLOAD_DIR     = /Users/benbtg/Library/Caches/VisualStudio/17.0/TempDownload
MSBUILDPROJECTROOTELEMENTCACHESIZE = 200
MSBuildExtensionsPath          = /usr/local/share/dotnet/sdk/6.0.402/
DISPLAY                        = /private/tmp/com.apple.launchd.YKOyr3spYI/org.xquartz:0
COMPlus_DbgEnableMiniDump      = 0
XPC_FLAGS                      = 0x0
MONO_GC_PARAMS                 = nursery-size=64m
LANGUAGE                       = en
SSH_AUTH_SOCK                  = /private/tmp/com.apple.launchd.jUAbTObYe6/Listeners
VSMAC_MSBUILD_BUILDER_SETTINGS_FILE = /var/folders/r9/9tfbs4p53sz4hh9h11jkfvv80000gn/T/tmpx40Tqf.tmp
PATH                           = /Library/Frameworks/Mono.framework/Commands:/Applications/Visual Studio.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/benbtg/Library/Android/sdk/platform-tools:/opt/homebrew/bin:~/.dotnet/tools
DOTNET_HOST_PATH               = /usr/local/share/dotnet/dotnet
LC_CTYPE                       = en
__CF_USER_TEXT_ENCODING        = 0x1F5:0:2
GTKSHARP_SLIM_STARTUP          = yes
ServiceHubUniqueLogDir         = vsmac

__________________________________________________
Project "/Users/benbtg/Dev/Customers/Civica/ModernGov/XApp.Maui/XApp/XApp.csproj" (Build target(s)):

Target "_SetBuildInnerTarget" in file "/usr/local/share/dotnet/sdk/6.0.402/Microsoft.Common.CrossTargeting.targets":
Done building target "_SetBuildInnerTarget" in project "XApp.csproj".
Target "_ComputeTargetFrameworkItems" in file "/usr/local/share/dotnet/sdk/6.0.402/Microsoft.Common.CrossTargeting.targets":
Done building target "_ComputeTargetFrameworkItems" in project "XApp.csproj".
Target "DispatchToInnerBuilds" in file "/usr/local/share/dotnet/sdk/6.0.402/Microsoft.Common.CrossTargeting.targets":
  Using "MSBuild" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, 
  Task "MSBuild"
    Additional Properties for project "XApp.csproj":
      TargetFramework=net6.0-android
    Additional Properties for project "XApp.csproj":
      TargetFramework=net6.0-ios
    Resolving SDK 'Microsoft.NET.Sdk'...
    Importing project "/usr/local/share/dotnet/sdk/6.0.402/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props" into project "/Users/benbtg/Dev/Customers/Civica/ModernGov/XApp.Maui/XApp/XApp.csproj" at (0,0).
    Project "$(AlternateCommonProps)" was not imported by "/usr/local/share/dotnet/sdk/6.0.402/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props" at (39,3), due to false condition; ('$(AlternateCommonProps)' != '') was evaluated as ('' != '').
    Importing project "/usr/local/share/dotnet/sdk/6.0.402/Current/Microsoft.Common.props" into project "/usr/local/share/dotnet/sdk/6.0.402/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props" at (40,3).
    Project "$(DirectoryBuildPropsPath)" was not imported by "/usr/local/share/dotnet/sdk/6.0.402/Current/Microsoft.Common.props" at (32,3), due to false condition; ('$(ImportDirectoryBuildProps)' == 'true' and exists('$(DirectoryBuildPropsPath)')) was evaluated as ('true' == 'true' and exists('')).
  6.0.523/targets/Microsoft.iOS.Sdk.ImplicitNamespaceImports.props" into project "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.0.523/Sdk/AutoImport.props" at (3,2).
/Users/benbtg/Dev/Customers/Civica/ModernGov/XApp.Maui/XApp/Views/Login.xaml.cs(941,40,941,64): warning CA1416: This call site is reachable on: 'Android' 21.0 and later. 'CrossFingerprint.Current' is only supported on: 'Android' 31.0 and later.
/Users/benbtg/Dev/Customers/Civica/ModernGov/XApp.Maui/XApp/Views/Login.xaml.cs(932,34,932,82): warning CA1416: This call site is reachable on: 'Android' 21.0 and later. 'IFingerprint.IsAvailableAsync(bool)' is only supported on: 'Android' 31.0 and later.
/Users/benbtg/Dev/Customers/Civica/ModernGov/XApp.Maui/XApp/Views/Login.xaml.cs(961,34,961,47): warning CA1416: This call site is reachable on: 'Android' 21.0 and later. 'FingerprintAuthenticationResult.Status' is only supported on: 'Android' 31.0 and later.
/Users/benbtg/Dev/Customers/Civica/ModernGov/XApp.Maui/XApp/Views/Login.xaml.cs(938,63,938,121): warning CA1416: This call site is reachable on: 'Android' 21.0 and later. 'AuthenticationRequestConfiguration' is only supported on: 'Android' 31.0 and later.
/Users/benbtg/Dev/Customers/Civica/ModernGov/XApp.Maui/XApp/Views/Login.xaml.cs(953,29,953,49): warning CA1416: This call site is reachable on: 'Android' 21.0 and later. 'FingerprintAuthenticationResult.Authenticated' is only supported on: 'Android' 31.0 and later.
/Users/benbtg/Dev/Customers/Civica/ModernGov/XApp.Maui/XApp/Views/Login.xaml.cs(932,34,932,58): warning CA1416: This call site is reachable on: 'Android' 21.0 and later. 'CrossFingerprint.Current' is only supported on: 'Android' 31.0 and later.
    224 Warning(s)
    0 Error(s)

Time Elapsed 00:00:12.70

========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

Build: 0 errors, 224 warnings

**Comment by hartez** [comment]
See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1583057/
