### ISSUE TITLE
MAUI blazor example doesn't work on Windows

### ISSUE THREAD

**Issue by Lanayx** [dotnet/maui#1103]
### Description

Maui app from generated template won't start on Windows. It does start on Android device for me.

### Steps to Reproduce

1. Follow the steps from the guide https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/#net-maui-blazor-apps
2. Set MauiBlazorApp.WinUI3 (Package) as startup project and run

### Expected Behavior

The demo app shows up

### Actual Behavior

The application is installed, but only blue background is visible

![image](https://user-images.githubusercontent.com/3329606/119808708-109a3400-beed-11eb-9ca1-67254fbb380a.png)

When observing events I see the exception

![image](https://user-images.githubusercontent.com/3329606/119809232-8f8f6c80-beed-11eb-8bdf-d4204a092fe0.png)

### Basic Information

- .NET version: 6.0.0-preview.4.21253.7
- Windows version: 10.0.19043.0
- IDE: Visual Studio 2019 16.10.0
- _maui-check_ reports that everything is OK

**Comment by JohnyL** [comment]
I just wanted to create the same issue. I have the same thing!

**Comment by Fabi** [comment]
Works just fine for me

**Comment by JohnyL** [comment]
@Fabi Yes, it's VS 2019 16.11.

**Comment by Lanayx** [comment]
I've checked this as well - there is no difference after installing 16.11 preview. Tried launching this project https://github.com/danroth27/BlazorWeather - exactly the same blue screen (however no exceptions shown)

**Comment by Fabi** [comment]
The weather app only works partially for me. Like it loads the sidebar but content is not working at all.
The default hello world app works tho
![image](https://user-images.githubusercontent.com/246718/119970459-068d3980-bfb0-11eb-9c0f-d4ad34efb167.png)

**Comment by BrandonReynolds** [comment]
Same issue as others. Friend of mine was able to get a templated build running. However, running his source produces same results. Must be an environmental configuration problem somewhere.

**Comment by hypdeb** [comment]
I had it working on an Insider Build of windows. But now that I am working on a 'normal' build again (`10.0.19043 Build 19034`), I get this issue too.

**Comment by hpngo-dev** [comment]
I think you need to install WebView2 Runtime https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section.

**Comment by Lanayx** [comment]
@hpngo-dev It works indeed, thank you!

**Comment by BrandonReynolds** [comment]
Confirmed working here. Installation of WebView2 Runtime solves all issues.
