### ISSUE TITLE
DEP1000: Cannot copy file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#11044]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/DEP1000:-Cannot-copy-file/10168371)._

---
[severity:It bothers me. A fix would be nice]
every time i want to build the my MAUI app I get this issue:

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP1000: Cannot copy file "...\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\MyApp.dll" to layout "...\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\MyApp.dll". IOException - The process cannot access the file '...\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\MyApp.dll' because it is being used by another process. [0x80070020]	MyApp			
	
The ‘bin’ folder cannot be deleted because of file that is opened by another process.
I have to close vs and reopen my app to be able to do a build.

---
#### Feedback Bot on 10/10/2022, 06:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Can you please attach binlog? 

https://github.com/xamarin/xamarin-macios/wiki/Diagnosis
