### ISSUE TITLE
Strange entries in the .csproj

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#11043]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Strange-entries-in-the-csproj/10138404)._

---
_**Description**_
When I copy a .xaml file inside a Maui project, add a new .xaml file or if I migrate a Xamarin xaml to Maui, the following entries are set in the .csproj file:

```XML

   
      %(Filename)
   



   
      MSBuild:Compile
   

```

The entries sometimes cause VisualStudio to put the .xaml and .xaml.cs next to each other. This is a little annoying, especially if these entries are doing nothing and I look inside the .csproj file after some time, and it has multiple entries of this type.

I have the issue with VisualStudio 2022 Preview (Version 17.4.0 Preview 1.0). But this issue already occurred a few versions before.

_**Steps to Reproduce**_
Generate a new MAUI project from the template.
**Case 1:**
- Copy and paste the MainPage.xaml in the project
- Now you should have a MainPage.xaml (and the corresponding .xaml.cs file) and a MainPage - Copy.xaml in the project
- Open the .csproj file: You should see the entries provided in the description above

**Case 2:**

- Right-click on the project and hit "Add" > "New Item"
- Select any .xaml type (for instance Flyout Page) and hit "Add"
- Now you already see the following entries in the .csproj:

```

   
   
   



   
      MSBuild:UpdateDesignTimeXaml
   
   
      MSBuild:UpdateDesignTimeXaml
   
   
      MSBuild:UpdateDesignTimeXaml
   

```

- Now change the "properties" of for instance `FlyoutPage1.xaml`:
   - Buildaction Embedded resource > MauiXaml
   - Remove value in Custom Tool
- After this, the file is removed from the ItemGroups above and a new ItemGroup as followed will appear in the .csproj:

```XAML

   
      
   

```

- Additionally the FlyoutPage1.xaml.cs is not placed underneath the FlyoutPage1.xaml, but next to it.

---
#### Dean Ellis [MSFT] on 9/2/2022, 11:56 AM: 

(private comment, text removed)
#### Feedback Bot on 9/4/2022, 07:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Moved back to vsfeedback
