### ISSUE TITLE
Add interface for Microsoft.Maui.Essentials.MainThread

### ISSUE THREAD

**Issue by ChristopherStephan** [dotnet/maui#11054]
### Description

I would like to have an interface of `Microsoft.Maui.Essentials.MainThread` added. The majority of the Essentials implementations have an interface declaration in the shared file but it is missing for the MainThread. 

Using package `Xamarin.Essentials.Interfaces` could solve this but I would prefer to not add another dependencies to my project.

### Public API Changes

Providing an interface for the MainThread would require to make the class not static any longer. 🤔 

### Intended Use-Case

We have several unit tests that rely on mocking the MainThread.

`var mainThreadMock = new Mock<IMainThread>()`

**Comment by ewerspej** [comment]
Why do you need to mock the `MainThread` in a unit test? That's an odd scenario for a **unit** test. AFAIK, the `MainThread` class must be static. Can't you work around that problem by creating a provider interface and class and then just hook into that?

**Comment by drasticactions** [comment]
I'm with @ewerspej. That approach makes sense to me, as a unit test harness is not a MAUI (The UI Framework) application, so having an interface contained explicitly within it would be creating a tie to the overall framework that, IMO doesn't make sense.

Creating your own interface wrapper and handling actions from it is pretty straightforward (https://github.com/drasticactions/DotnetRss/blob/main/DotnetRss.Core/Services/IAppDispatcher.cs) and that would give you more flexibility than whatever API could be created within MAUI.

**Comment by jfversluis** [comment]
Because of the afore mentioned reasons I think we won't be adding this. Thanks for the suggestion!
