### ISSUE TITLE
Stepper IsEnabled can't be changed at runtime on Android

### ISSUE THREAD

**Issue by matt-goldman** [dotnet/maui#11050]
### Description

DataTrigger is not working with Stepper as expected. Adding a data trigger that sets the `IsEnabled` property of a Stepper to False based on a bound value does not seem to fire the ExitAction when the bound value changes.

As an example, I have a CollectionView with the SelectedItem bound to a property. I've got a data trigger that sets the Stepper's IsEnabled property to False when the bound property is null. However, when selecting an item, the Stepper remains disbaled.

I've tried two things to test it:
1. Added a data trigger with the same binding to a Button. The Button becomes enabled when an item is selected.
2. Set an initial value in the binding context's constructer for the property that SelectedItem (and the trigger) is bound to. In this case the Stepper is enabled when the view appears.

### Steps to Reproduce

1. Add a DataTrigger to a Stepper
2. Bind the DataTrigger to a property with a TargetNullValue
3. Set the Value of the DataTrigger to ""
4. Add a Setter to the trigger for the IsEnabled property and set the Value to False
5. Change the value of the bound property (ie, make it no longer null)

Expected behaviour:
Stepper becomes enabled

Actual behaviour:
Stepper remains disabled

### Link to public reproduction project repository

https://github.com/matt-goldman/DataTriggerNullBug

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 11 and up, Windows 11

**Comment by matt-goldman** [comment]
**Update**

1. I was wrong, issue does not occur on Windows. Only seems to occur on Android. I will test macOS and iOS too and report back.
2. Issue is not confined to data triggers. In the repro linked above, I added an additional test with a Switch just toggling a bool in the binding context. It seems that the `IsEnabled` binding for Stepper doesn't respond to changes at runtime as this didn't work either. As a final test, I added a Button with an event handler that sets the IsEnabled property of the Stepper to True directly. This also didn't work. So, in summary:   
    
**The actual issue seems to be that the `IsEnabled` property of Stepper can't be changed at runtime on Android.**

**Comment by matt-goldman** [comment]
Update 2: Confirmed issue does NOT occur on maccatalyst. Will confirm iOS as soon as I can.

**Comment by jsuarezruiz** [comment]
The https://github.com/matt-goldman/DataTriggerNullBug repo seems to not exists or be private, could you review it?

**Comment by matt-goldman** [comment]
Apologies it was private. I've made it public now.

**Comment by jsuarezruiz** [comment]
Reproduced.
