### ISSUE TITLE
Changes not re-rendering in Hot Reload

### ISSUE THREAD

**Issue by TrueTheos** [dotnet/maui#11066]
### Description

I had my MAUI app open in XAML Live Preview and in another window.

While it was running I added grid:

`<Grid ColumnDefinitions="*,auto,*" RowDefinitions="40,40,*" RowSpacing="15" >
                <Entry Grid.Row="0" Grid.Column="1"
                    x:Name="Email"
                    Placeholder="Type your email" 
                    WidthRequest="200"
                    HorizontalOptions="Fill" />

                <Entry Grid.Row="1" Grid.Column="1"
                    x:Name="Password"
                    Placeholder="Type your password"
                    IsPassword="True"
                    HorizontalOptions="Fill" />

                <Button Grid.Row="2" Grid.Column="1" Margin="0,20"
                    x:Name="Login"
                    Text="LOGIN"
                    Clicked="OnLoginClicked"
                    HorizontalOptions="Fill" />
            </Grid>`

Which didn't appear on the live preview even after clicking Hot Reload (ALT+F10)
Seems like values are being set correctly from Hot Reload, but they are not re-rendering correctly when applied unless the view is destroyed and recreated.

### Steps to Reproduce

I used a base project and I modified it so it looks like this:
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Meow.MainPage">

    <ScrollView>
        <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            VerticalOptions="Center">

            <Image
                Source="marin2.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="200"
                HorizontalOptions="Center" />

            <Label
                Text="Hello, World!"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />

        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
`
First run the app and then open XAML Live Preview and then add this snippet under the `Label`
`<Grid ColumnDefinitions="*,auto,*" RowDefinitions="40,40,*" RowSpacing="15" >
                <Entry Grid.Row="0" Grid.Column="1"
                    x:Name="Email"
                    Placeholder="Type your email" 
                    WidthRequest="200"
                    HorizontalOptions="Fill" />

                <Entry Grid.Row="1" Grid.Column="1"
                    x:Name="Password"
                    Placeholder="Type your password"
                    IsPassword="True"
                    HorizontalOptions="Fill" />

                <Button Grid.Row="2" Grid.Column="1" Margin="0,20"
                    x:Name="Login"
                    Text="LOGIN"
                    Clicked="OnLoginClicked"
                    HorizontalOptions="Fill" />
            </Grid>
`

### Link to public reproduction project repository

none

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

I just had to close my app and run it again.

**Comment by drasticactions** [comment]
A good way to verify if properties or controls are not being re-rendered correctly after a hot reload action has occured to is to try to replicate the behavior from C# code behind (As in, create or modify the same controls from a method in C# from within your app)

XAML Hot Reload is, effectivly, generating actions that poke MAUI properties on your behalf. If you apply a XAML Hot Reload change and check the object in MAUI and see the action you did take place, but not appear on screen, then it's most likely an issue that could also happen if you ran your own method from within your app trying to do the same thing.
