### ISSUE TITLE
Issue 7015 has not been fixed, please reopen this issue

### ISSUE THREAD

**Issue by faceoffers28** [dotnet/maui#11063]
### Description

https://github.com/dotnet/maui/issues/7015

This is still a problem. The issue persists in Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.3.6. Microsoft Visual Studio Enterprise 2022. I'm running version Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7). My target framework is net6.0-ios14.5.

### Steps to Reproduce

See issue 7015.

### Link to public reproduction project repository

 https://github.com/paulvarache/MauiIssueBorderShadowBackground

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

net6.0-ios14.5

### Did you find any workaround?

There is a workaround listed in the issue 7015, but I have no idea how to implement it in the AppDelegate.cs file.

**Comment by faceoffers28** [comment]
@rachelkang Since this bug seems to be a huge problem, can you comment on the workaround? How can we implement it? There is a workaround listed in the issue 7015, but I have no idea how to implement it in the AppDelegate.cs file. Thanks!

**Comment by rachelkang** [comment]
@faceoffers28 If you're referring to the StrokeThickness workaround that the original poster of that issue mentioned, that was set in their [MainPage.xaml.cs](https://github.com/paulvarache/MauiIssueBorderShadowBackground/blob/454134f4b137b1f6d1f411db38c30c1da8337685/MauiBorderBackgroundIOS/MainPage.xaml.cs#L14)

**Comment by faceoffers28** [comment]
@drasticactions I assume that you now realize that the original ticket was closed as completed. Why I have no idea. I could not raise awareness on the original issue. Furthermore, is anyone going to actually comment about the reported workaround? I'm trying to use .Net Maui for a production app I'm working on. This problem makes the UI unusable on an iPhone.

**Comment by drasticactions** [comment]
As you are right now, you could have by commenting on original issue even if it's closed. The comments are still open, and if an issue has regressed it can be reopened. 

The original issue was closed with https://github.com/dotnet/maui/pull/7695, either something could have regressed since it was fixed, or it was never fixed, or you have another problem. In which case, you can talk about it in the original issue. If it turns out to be something else, we can make a new issue to track it.

**Comment by faceoffers28** [comment]
@drasticactions I'm not going to argue with you, but comments were closed to new people. This is why I opened a new issue. It happens all the time with Microsoft and GitHub. This is the first time I created a new issue because I couldn't comment on an old one.

**Comment by faceoffers28** [comment]
Seeing as I still can't comment on the original issue (see attached image), does anyone have any idea how to implement the workaround as discussed here. https://github.com/dotnet/maui/issues/7015#issuecomment-1141315848

I tried adding it here.

```
public partial class App : Application
{
 //Insert before MainPage = new AppShell();
}

```
![image](https://user-images.githubusercontent.com/10619627/200029899-ff458f04-4510-45b8-a872-051d78ee93fe.png)

**Comment by faceoffers28** [comment]
The fix from https://github.com/dotnet/maui/issues/7015#issuecomment-1141315848 doesn't work for me. I tried the following in a .Net Maui iOS 15.4 app using Asp.net 6.0.400, Visual Studio 17.3.6 & Xamarin SDK 17.3.0.308.

```
//Fix for border and shadows issue on iOS
        BorderHandler.Mapper.AppendToMapping(nameof(Border.Background), (handler, view) =>
        {
            //Task.Delay(0).ContinueWith((_) =>
            //{
            //    MainThread.InvokeOnMainThreadAsync(() =>
            //    {
            //        SentrySdk.CaptureMessage("Background Mapping = " + "Yes");

            //        handler.PlatformView.UpdateBackground(view);
            //        handler.PlatformView.UpdateBorder(view);
            //    });
            //});

            handler.PlatformView.UpdateBackground(view);

        });
```

**Comment by samhouts** [comment]
Duplicate of #7015
