### ISSUE TITLE
Importing a JS module into a .NET MAUI Blazor app fails

### ISSUE THREAD

**Issue by danroth27** [dotnet/maui#11062]
Repro steps:

- Create a .NET MAUI Blazor app
- Add a Razor Class Library to the solution and reference it
- Add ExampleJsInterop as a singleton service

```csharp
builder.Services.AddSingleton<ExampleJsInterop>();
```

- Update Index.razor with the following:

```razor
@page "/"
@using RazorClassLibrary1
@inject ExampleJsInterop InteropTest

<button @onclick="ShowPrompt">Prompt</button>

@code {
    private async Task ShowPrompt()
    {
        var text = await InteropTest.Prompt("Favorite color?");
    }
}
```

- Run the app and click the prompt button

Expected result: Prompt shown

Actual result:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.AspNetCore.Components.WebView
  StackTrace:
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewJSRuntime.BeginInvokeJS(Int64 taskId, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1.MoveNext()
   at RazorClassLibrary1.ExampleJsInterop.<Prompt>d__2.MoveNext() in C:\Users\daroth\source\repos\MauiApp8\RazorClassLibrary1\ExampleJsInterop.cs:line 23

  This exception was originally thrown at this call stack:
    [External Code]
    RazorClassLibrary1.ExampleJsInterop.Prompt(string) in ExampleJsInterop.cs
```

This is with .NET 6 and VS2022 17.3.6

**Comment by TanayParikh** [comment]
> * Add ExampleJsInterop as a singleton service

Can you please provide a snippet for this too.

Does the import of the JS module specifically fail when done from a RCL? Do other JSInterop calls from the RCL work as expected?

**Comment by danroth27** [comment]
> Can you please provide a snippet for this too.

Done

> Does the import of the JS module specifically fail when done from a RCL? Do other JSInterop calls from the RCL work as expected?

I'm also unable to load the module from the app. I get an error: "Failed to fetch dynamically imported module". I wasn't able to figure out a path to the module that would work.

**Comment by TanayParikh** [comment]
>> Can you please provide a snippet for this too.

> Done

Sorry I meant the actual `ExampleJsInterop` implemention.

**Comment by danroth27** [comment]
> Sorry I meant the actual ExampleJsInterop implemention.

That comes from the Razor Class Library template

**Comment by MackinnonBuck** [comment]
In MAUI Blazor, `IJSRuntime` is a scoped service, so it cannot be injected into singleton services.

Closing as by-design.
