### ISSUE TITLE
Grid columns inside FlexLayout do not adjust their size correctly on Android

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#11079]
### Description

When you put a grid inside a FlexLayout, without giving it a WidthRequest and just setting the FlexLayout.Base to some value, its columns stretch across the whole screen, not respecting the grid's size:
![image](https://user-images.githubusercontent.com/114725843/199695919-14b0b1ad-e305-4a00-a406-24c5a637319e.png)
Works perfectly on iOS:
![image](https://user-images.githubusercontent.com/114725843/199696134-bcf7a158-dfcc-4945-a8f9-68d2eadc68db.png)

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Add a FlexLayout and a Grid as its child
3. Give the Grid a FlexLayout.Basis of e.g. 50% or 100 (it does not matter if it's a percentual value or not)
4. The Grid will have the correct size, but its children will stretch across the screen

### Link to public reproduction project repository

https://github.com/owl-guy/GridFlexExample

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

**Comment by owl-guy** [comment]
Still happens with the newest version 7.0.100-rc.2 in the latest Visual Studio preview

**Comment by ShadowOfPhantom** [comment]
If you don't mind, I add here a little more about FlexLayout here to not to create a new issue. If you set Wrap="Wrap" in FlexLayout then wrapped buttons miss clicks. [Here's a video](https://1drv.ms/v/s!AtDUa3oxb3BY6RMlHHJZ4K0m1WtZ?e=nE5duD) to demonstrate the issue. There I'm tapping 15x15 button and be notice, once I turned my iPhone to landscape then 15x15 button became not wrapped and clicks work

**Comment by owl-guy** [comment]
Seems to work now with the newest stable version of .NET 7, thus I will close this issue.
@ShadowOfPhantom If you still have this problem, please open a separate issue. Thx
