### ISSUE TITLE
When a custom NavigationDelegate is set in iOS, Navigated is not called

### ISSUE THREAD

**Issue by czuck** [dotnet/maui#11074]
### Description

This was initially discovered with Forms 5.0.0.2515 but recreated with Maui 6.0.541/6.0.400.
I am attempting to create a customWkNavigationDelegate so I can override the DecidePolicy.  If the navigationAction.TargetFrame == null (ie the link has target="_blank") I want to send the URL to a new instance of the browser.  When I did this the Navigated code stopped running.  I looked into it and it appears the default NavigationDelegate isn't WKNavigationDelegate as expected, but CustomWebViewNavigationDelegate (WKWebViewRenderer line 103).  This CustomWebViewNavigationDelegate is defined in WKWebViewRenederer, inherits from WKNavigationDelegate, but is not public so I can't inherit from it (In Maui it's private).  
Please fix this in both Forms and Maui, as porting our code will take some time.

### Steps to Reproduce

1. Run the attached project.  Note that the ActivityIndicator is hidden when the page finished loading.
2. In Platforms\iOS\CustomWebViewRenderer uncomment line 23: NavigationDelegate = new CustomWKNavigationDelegete();  Note this class is empty and inherits from WKNavigationDelegate
3. Run the project again.  Note that the ActivityIndicator continues to be visible and active. Also note that it is not centered vertically as it should be.

### Link to public reproduction project repository

https://github.com/czuck/WebViewTest

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS15

**Comment by PureWeen** [comment]
@czuck can you try to use the WebViewHandler instead of a Compatibility Renderer? 

You can add your own mapper key https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize and then in there set your new `NavigationDelegate` that inherits from `MauiWebViewNavigationDelegate`

**Comment by czuck** [comment]
@PureWeen is it possible to mix Handlers and Compatibility Renderers in the same object?  If not then no, because both the CustomWebView and CustomWebViewRenderer contain other customizations.

**Comment by PureWeen** [comment]
@czuck what customizations?

The WebViewHandler is largely just a repackaged `WebViewRenderer`

If you tap into

`WebViewHandler.PlatformViewFactory`

You can return your own custom `MauiWkWebView` and then most of your customizations should just work there.

**Comment by czuck** [comment]
@PureWeen I'm sorry, you've totally lost me.  I have been looking for instructions to migrate the test app I submitted from the Forms/Custom Renderer way of doing things to the Maui / Handler way and have not had success.  Perhaps you could do that?  
The customizations I have currently in my real app - not the stripped down test app I submitted with the issue - to CustomWebView and CustomWebViewHandler include things like javascript handling, cookie handling, conditional loading, UI changes, load completion handling .. I'm not sure what all that has to do with this issue.

**Comment by PureWeen** [comment]
@czuck The possibility that `CustomWebViewRenderer` will be updated to meet your needs is very low so ideally you can just move your customizations over to using a `WebViewHandler`

Can you post your full customization somewhere? or some subset of it and I can give you some sample code to help migrate?

**Comment by czuck** [comment]
@PureWeen I updated my sample project with my attempt at the Handler version, it doesn't compile.  Beyond that, how would I use the handler pattern to subscribe to Navigating and Navigated in the WebView, or is that still done by creating a CustomWebView inheriting from WebView?  On the platform side (Android and iOS), how would I add a handler for OnElementChanged?

**Comment by PureWeen** [comment]
@czuck I'm not too sure where in your code you are trying to do a Handler version. Can you link to the handler part of the code? 

In the meantime what'd I'd recommend trying is this 

Add the following code to your Platform/iOS folder

```C#
    internal class CustomWebView : MauiWKWebView
    {
        public CustomWebView(WebViewHandler handler) : base(handler)
        {
            NavigationDelegate = new CustomWKNavigationDelegete(handler);
        }
    }

    class CustomWKNavigationDelegete : MauiWebViewNavigationDelegate
    {
        public CustomWKNavigationDelegete(IWebViewHandler handler) : base(handler)
        {
        }
    }
```

And then on your builder just do this

```C#
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .ConfigureMauiHandlers(handlers =>
            {
#if IOS
                WebViewHandler.PlatformViewFactory = (h) => new Platforms.iOS.CustomWebView((WebViewHandler)h);

#endif

            })
```


Now that should give you a custom webview and a custom navigation delegate that you are able to use
