### ISSUE TITLE
Entry height rendering is broken

### ISSUE THREAD

**Issue by Vroomer** [dotnet/maui#11098]
### Description

This might be two separate issues, but they result in the same behaviour:

1. Entry inside CollectionView doesn't get rendered at full height. It remains cropped until the user hovers over the Entry or until the Entry gains focus. Setting HeightRequest for Entry or the layout of the DataTemplate has no effect.

2. In case HeightRequest is set for Entry, it doesn't get rendered at full height even outside of CollectionView. It also remains cropped until the user hovers over the Entry or until the Entry gains focus.

Setting Entry VerticalOptions to Fill has no effect.

The issue is present in Windows. Android is ok. iOS wasn't tested.

### Steps to Reproduce

1. Load the repository and run the app.
2. Observe cropped Entries. Try to hover over them.
3. Uncomment HeightRequest in ResourceDictionary of MainPage and try again.

### Link to public reproduction project repository

https://github.com/Vroomer/MAUI-Entry-height-rendering-cropped.git

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.22000

**Comment by IsaacSherman** [comment]
I've also experienced this issue.

**Comment by kemeril** [comment]
I was able to reproduct.

1. Net 7 final
2. Create initial MAUI APP, Net 7 version
3. Create two entries control on the main page under each other:
<Border><Border.StrokeShape><RoundRectangle CornerRadius="8" /></Border.StrokeShape><Entry Text="ABC" FontSize="14" HeightRequest="48" BackgroundColor="Red"/></Border
<Border><Border.StrokeShape><RoundRectangle CornerRadius="8" /></Border.StrokeShape><Entry Text="ABC" FontSize="14" HeightRequest="48" BackgroundColor="Red"/></Border
4. Start the app on Windows Machine
5. Hover the mouse over the entries
6. You can see the initial cropping and strange resizing

Remark: If the entries are placed into Borders the effects are stronger!

**Comment by Providenceee** [comment]
I encountered this issue aswell, except i placed Entries in a grid instead of a CollectionView. Definetely appeared with .NET 7 update, in .NET 6 everything renders perfectly.

**Comment by MaksimAdamenko** [comment]
The problem is everywhere except android

**Comment by hartez** [comment]
@Vroomer your repro link gives me a 404 error. Can you post another repro or make that one available?

**Comment by Vroomer** [comment]
@hartez Sorry I forgot to make it public. Should be available now.

**Comment by hartez** [comment]
@Vroomer This is what I'm seeing when running your repro project in the latest stable VS (17.4.4) (with the HeightRequest of 60 in the Style):

![image](https://user-images.githubusercontent.com/538025/213821957-c24df786-4ef1-4470-a5ca-7a486bda3f34.png)

Does it look like you expect? Am I missing something? (It's also possible we've fixed it since you originally reported this.)

**Comment by Vroomer** [comment]
@hartez I can't reproduce this bug in latest version either. It appears to be fixed. :)

**Comment by Vroomer** [comment]
@MartyIX This sounds like a different issue. The one I had was about entry being only partially rendered and then rerendered once you hovered mouse over it. I suggest you to make a new issue for yours.
