### ISSUE TITLE
InputFile not working on Blazor Desktp in winform

### ISSUE THREAD

**Issue by yeganehaym** [dotnet/maui#11093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i have made  an app with blazor server and launch dektop version with winform
but when i make release version of desktop application.
input file doesn't react to click of user
and i cant pickup any file
but on some systems opens but it looklike code doesn't continue
but it's ok on blazor server project and windows form when i run app in rider

### Expected Behavior

i can pick up file in file browser when i click on inputfile

### .NET Version

6

**Comment by TanayParikh** [comment]
Ah got it, from the looks of it, you're running a Blazor Hybrid application, and **not** a Blazor server application within a WinForms webview.

**Comment by TanayParikh** [comment]
Just tried reproducing your issue in Debug & Release configurations, as well as in a published app. I'm not seeing any issues with opening the input file dialogue. 

https://user-images.githubusercontent.com/14852843/199823942-9591c41e-cbe5-4b77-8031-ae0a0eb08d16.mov

If you still believe this is a framework issue, we'll need a minimal, public, GitHub repository which reproduces this issue.

**Comment by TanayParikh** [comment]
> i got a shared project of blazor server and this shared between winforms and blazor

So is the `*Blazor.Shared` project a Blazor Server project, or a Razor Class Library (RCL)?

**Comment by yeganehaym** [comment]
*.shared project is a class library that is set by
```
     <PropertyGroup>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		
    </PropertyGroup>
```

and *.blazorServer project and winform proj is referenced to share proj
and for windows i use this package

```
PackageReference Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" Version="6.0.101-preview.11.2349" />
```

**Comment by TanayParikh** [comment]
Ah I see, thanks for the details. `6.0.101-preview.11.2349` is from `12/13/2021`. Can you please try the latest .NET 7 build or `[6.0.547](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.WebView.WindowsForms/6.0.547)` and confirm if you're still having the issue? If so, we'll need a [minimal, public, GitHub repository which reproduces the issue](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) to investigate further.
