### ISSUE TITLE
Create code tour of handler architecture

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#1109]
As part of our mission to make our repros as approachable as possible to contributors, we'll be drafting up CodeTour walkthroughs of relevant portions of the codebase. In this repo, we'll be documenting the handler logic of a Button.

For: https://github.com/microsoft/contributor-community-experiments/issues/10

**Comment by jfversluis** [comment]
Let's revisit at some point, not going to happen for now.
