### ISSUE TITLE
MAUI Blazor App OnBackPressed not firing after launching Modal XAML Window from Blazor

### ISSUE THREAD

**Issue by WoodyJ007** [dotnet/maui#11105]
### Description

When creating a .NET MAUI Blazor App.  If you navigate to a Blazor page and on that page then lauch a XAML window.  Pressing the standard Back button on Android will not go back (close the window) and OnBackPressed will not fire.  It will only fire the event on the second press.  I believe the BlazorWebView is handling the back first in the background and the second press is then getting passed to the modal?

In very simple steps to reproduce you will see the issue.  If you override OnBackButtonPressed on NewPage1 and put a breakpoint on it you will see it will only be hit when the back button is pressed for the second time.

### Steps to Reproduce

1. Create a new .NET MAUI Blazor App
2. Add a new .NET MAUI ContentPage (XAML) to the project.  Name it NewPage1
3. Change Counter code on Counter Razor.  To below

```csharp
private void IncrementCount()
    {
        App.Current.MainPage.Navigation.PushModalAsync(new NewPage1());
    }
```

4. Run the app on an android device/emulator.
5. On app menu select Counter
6. Click on 'Click Me'
7. New Page 1 will be shown.
8. Press the Back button on the device
9. Nothing will happen.
10. Press the back button on the device again.
11. The modal will close and the default home screen will be shown.

### Link to public reproduction project repository

.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Framework 24+

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Android 13.0-API33 with below Project:
[11105.zip](https://github.com/dotnet/maui/files/11632395/11105.zip)

![ClickMe](https://github.com/dotnet/maui/assets/97647558/c17da4f9-8ff5-4200-ae70-3a15b6feac88)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
