### ISSUE TITLE
[Custom Control] HotReload doesn't work for newly added nested items

### ISSUE THREAD

**Issue by the8thC** [dotnet/maui#11106]
### Description

Continuation of https://github.com/dotnet/maui/issues/10390, but I've implemented `IVisualTreeElement`. Only now the HotReload works for items defined in XAML at launch, but doesn't work for items added via HotReload.
I've noticed the `IReadOnlyList<IVisualTreeElement> IVisualTreeElement.GetVisualChildren()` method is not called when adding new nested items, maybe I should handle collection changes somehow so it's called, @PureWeen?

https://user-images.githubusercontent.com/21204523/199957266-18de9468-d27d-4c95-beed-68c0b97377a5.mov

### Steps to Reproduce

Watch the video

### Link to public reproduction project repository

https://github.com/the8thC/ElementVisuaElementHotReload

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

iOS 16, Android API 32

### Did you find any workaround?

Remove and add the whole parent control and HotReload works for all items

**Comment by jfversluis** [comment]
@drasticactions any ideas here maybe?

**Comment by the8thC** [comment]
@drasticactions If I add the item in code-behind I can't edit it's XAML to check for HotReload, so I can't really test that. 
But the `IVisualTreeElement.GetVisualChildren()` isn't called when I add items via button clicked event

https://user-images.githubusercontent.com/21204523/201051556-2766fda6-995b-4b2b-ba8b-be9079f0e7ce.mov

**Comment by the8thC** [comment]
@drasticactions, it works this way, thanks! The issue can be closed

**Comment by PureWeen** [comment]
Ideally users creating custom controls wouldn't always have to know about `IVisualTreeElement` and we'd have a way to wire into `LogicalChildren` https://github.com/dotnet/maui/issues/11528

**Comment by Redth** [comment]
@davidbritch are you able to assist in adding some conceptual docs around LogicalChildren API's?

**Comment by davidbritch** [comment]
@Redth https://github.com/dotnet/docs-maui/issues/1216

**Comment by Redth** [comment]
Thanks!
