### ISSUE TITLE
Add a NuGet packed to a project. for Android

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/maui#11118]
### Description

I try to add this nuget packed Xamarin.AndroidX.Camera.Core.

But when i try i get this error..

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Xamarin.AndroidX.Lifecycle.LiveData from 2.5.1.1 to 2.5.1. Reference the package directly from the project to select a different version. 
 OBJECTSOCIAL.Software -> Xamarin.AndroidX.Camera.Core 1.1.0.2 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.5.1.1) 
 OBJECTSOCIAL.Software -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.5.1)	OBJECTSOCIAL.Software	D:\connecting-together\CONNECTING-TOGETHER\@Blazor software\OBJECTSOCIAL\OBJECTSOCIAL.Software.csproj	1

### Steps to Reproduce

I just need explaining..
Dont need to make a project for that..

### Link to public reproduction project repository

i must

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 

### Did you find any workaround?

Nop

**Comment by softlion** [comment]
That means the package you try to install is not compatible with other packages that are already installed.

You don't need to use this package. You can use the maui camera from the xamarin toolkit instead.

Also it's not a maui bug, so use stackoverflow to post those questions instead.

**Comment by PirasathLuxchumykanthan** [comment]
Shut up softlion.
Im a developer... not a person that likes to use toolkit that's a shit..
whit xamarin toolkit.. i can only take photo and pick files..
As i say im a developer i don't need your guide how to use toolkit..


im c# developer for more than 10 years

But MAUI has ruined it by saying toolkit..
go back to xamarin.

**Comment by PirasathLuxchumykanthan** [comment]
i hate this fucking Contributor  they thing i cant read... im 10 years 10 developer... and the fuckt it up whit silverlight and maui next person who write stupid in issuse and in just in c# project.. i will kill

**Comment by PirasathLuxchumykanthan** [comment]
[softlion](https://github.com/softlion) if you dont open this again trust me you will not have any fingeres.. .

i will count made count down for 2 hour..

**Comment by PirasathLuxchumykanthan** [comment]
<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-android'">
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.5.1.1" PrivateAssets="all" />
	</ItemGroup>

this is the fix
