### ISSUE TITLE
[Enhancement] Handle null/empty PropertyName in the INotifyPropertyChanged.PropertyChanged event

### ISSUE THREAD

**Issue by KPixel** [dotnet/maui#1111]
## Summary

MAUI uses the [PropertyChangedEventArgsExtensions](https://github.com/dotnet/maui/blob/efa9dabb31f347056dac46c9a6ac366eee444d1a/src/Controls/src/Core/PropertyChangedEventArgsExtensions.cs) class to check when a property has changed, however, its implementation is flawed:

[As documented here](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.propertychangedeventargs.propertyname?view=net-5.0) ([and here](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged.propertychanged?view=net-5.0#remarks)), the `PropertyName` property is allowed to be null/empty to indicate that all of the properties have changed. That is not currently supported by MAUI.

## API Changes

`PropertyChangedEventArgsExtensions` methods `Is()` and `IsOneOf()` should start with:

```C#
if (string.IsNullOrEmpty(args.PropertyName))
  return true;
```

The [platforms copies of this class](https://github.com/dotnet/maui/search?q=PropertyChangedEventArgsExtensions) should also be updated.

Any code using these classes must be aware of this scenario. So, they must avoid chaining the checks like this: "if (property1) ... else if (property2) ...". The `else` keyword must be removed.
Sadly, there is a lot of code that would need to be update to fix this: [else if (e.PropertyName ==](https://github.com/dotnet/maui/search?q=%22else+if+%28e.PropertyName+%3D%3D%22), [else if (e.Is](https://github.com/dotnet/maui/search?q=%22else+if+%28e.Is%22), [else if (e.IsOneOf](https://github.com/dotnet/maui/search?q=%22else+if+%28e.IsOneOf%22).

## Intended Use Case

This feature is officially documented, so .NET users would be surprised that it doesn't work in Maui.

As a practical example, this feature is useful when a ViewModel is reloaded from an external source, and we want to notify the UI to refresh itself without having to mention every property one by one. And the performance should be better when Maui receives a single change notification.

**Comment by KPixel** [comment]
At the very least, I hope that new code can be written to take this into account.

Then, the existing code can be updated progressively.

**Comment by mattleibow** [comment]
Adding this to the XAML area as it suppose for me it feels like this is more of the xaml bindings area rather than an actual control/feature bug.

We should support this to be consistent with other xaml platforms. But... Is this a breaking behavior change? I suppose not as most people will be checking name == "something" and if we call with a "", then that would just return false?

With handlers, this is a bit easier as we have a single point that gets the event and then pass it to the handler, so making that check for "" we can trigger all the properties or just do the one.

**Comment by mattleibow** [comment]
Moving to controls as this is a code bug I think :)
