### ISSUE TITLE
AppThemeBinding not working well on macOS

### ISSUE THREAD

**Issue by piotreksda** [dotnet/maui#11119]
### Description

AppThemeBinding is not dynamic on the mac. When I change the system theme while the app is running, the text colours do not change. AppThemeBinding only works when the application is launched then the colours are selected correctly.

https://user-images.githubusercontent.com/23263384/200120468-77f4031b-c77f-4f4e-b492-d86dd504024e.mp4

AppShell.xaml
![image](https://user-images.githubusercontent.com/23263384/200120541-d6d1e6e2-78cf-4837-9053-0bdf047b603e.png)

![image](https://user-images.githubusercontent.com/23263384/200121020-5e57f445-16d8-4298-b31c-d1f5636308e6.png)

### Steps to Reproduce

1. Create a new .Net MAUI App
2. Change the text colour of any lebel to `TextColor="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}}"`
3. When the application is running change the system themes and watch for the bug

### Link to public reproduction project repository

https://github.com/piotreksda/testMauiApp

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.6

**Comment by piotreksda** [comment]
`Application.Current.RequestedThemeChanged` also not working well



https://user-images.githubusercontent.com/23263384/200126060-42293633-1848-45d4-b35b-72a18d80f002.mp4

**Comment by softlion** [comment]
Maybe that is because the label is inside an itemtemplate ? what if it's inside a non item template container ?

**Comment by piotreksda** [comment]
Still not working
https://user-images.githubusercontent.com/23263384/200165236-cb26c867-e972-4f5d-a700-a7fa6f35c726.mp4
