### ISSUE TITLE
Device Idiom detects Windows as tablet

### ISSUE THREAD

**Issue by matt-goldman** [dotnet/maui#11126]
### Description

Using `DeviceInfo` or the `OnIdiom` markup extension detects Windows as tablet. I've seen these:
https://github.com/dotnet/maui/issues/4351
https://github.com/dotnet/maui/issues/2423
https://github.com/dotnet/maui/issues/5769

But the issue still occurs. See:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/19944129/200157976-2ab04596-0575-4b86-9a19-f361408c87b0.png" />

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Use `DeviceInfo.Current.Idiom` or the `OnIdiom` markup extension
3. Run on Windows
4. Observe that the detected idiom is tablet

### Link to public reproduction project repository

https://github.com/matt-goldman/OnIdiomBug.App

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

Workaround is to use Tablet for the views you want on Windows.

**Comment by matt-goldman** [comment]
**Update:**
I did this initially on my laptop, which has a touch screen. Ran it again on my desktop (which doesn't have a touch screen) and got the expected result:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/19944129/200158228-6f116cbf-bf38-4529-a5b0-7f21e79b4f49.png">

So I'm guessing you're using the presence of a touch screen to distinguish between desktop and tablet.

If this is intentional (i.e., if you consider a Windows computer with a touchscreen to be a 'tablet'), then I think the documentation should reflect this. But I also don't think this is the right approach; while it may be useful to distinguish between touch and non-touch devices, I don't think the device idiom is the correct place to do this.

**Comment by jfversluis** [comment]
The logic is a bit more than if there is a touch screen yes or no: https://github.com/dotnet/maui/blob/18ed02b41a35edad98aef79ec677c42ebff52890/src/Essentials/src/DeviceInfo/DeviceInfo.uwp.cs#L120

We (try to) detect if a tablet mode is supported and if that is currently enabled.

Are you running this on Windows 10 or 11? On Windows 10 you can manually enable and disable the tablet mode so could you double-check that? For Windows 11 it seems tablet mode has been removed, at least the ability to influence it manually and then it would seem that this is set to true by default?

**Comment by matt-goldman** [comment]
Thanks for the clarification @jfversluis. I suspected the logic was more sophisticated. I thought this might help to clarify why previous issues have not been reproducible.

I'm running Windows 11. Based on a quick search I can see that Windows 11 is supposed to automatically switch to tablet mode when the keyboard is detached, and leave tablet mode when it gets attached. I'm on a laptop with a non-detachable keyboard but it seems perpetually stuck in tablet mode. I have noticed that the Office ribbon changes when I touch the screen (the icons get bigger and more touch friendly), so I suspected that touching the screen might enable tablet mode, however a restart seems to have disproven this.

Based on similar problems reported across the web, I would initially suspect a bug in Windows incorrectly reporting tablet mode, however given the experience with Office, I'm more inclined to believe its an undocumented API change. But, tbh, I'm way out of my depth here and just wildly speculating.

So open appeal to anyone with a Windows 11 device with a detachable keyboard to test the sample at the repo linked above I guess? Is there anything else I can do to help troubleshoot this?

**Comment by matt-goldman** [comment]
**UPDATE** I just folded my screen back in 'lie flat mode' and it's now reporting desktop view. So this kind of works, but in reverse. In this position (lie flat) the screen rotates, whereas in normal laptop mode it does not. So I *think* Windows is working the right way (tablet mode when folded back flat, desktop mode when not), so it looks like maybe inverting `SM_CONVERTIBLESLATEMODE` might do the trick?

**Comment by jfversluis** [comment]
Amazing work @matt-goldman thanks for the help and investigation here!
