### ISSUE TITLE
Android version code incorrect when publishing release build apk

### ISSUE THREAD

**Issue by taublast** [dotnet/maui#11139]
### Description

There is no *appearent* way to set Version Code to other than 1 inside .cproj. whatever version number you put in code.
When you hit Publish release version you get an apk with Version Code 1.

Context:

Related to https://github.com/dotnet/maui/issues/3690.

Environment:

Microsoft Visual Studio Community 2022
Version 17.3.6
VisualStudio.17.Release/17.3.6+32929.385
Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Project:

```
        <TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0-android|AnyCPU'">
		<AndroidPackageFormat>apk</AndroidPackageFormat>
		<AndroidCreatePackagePerAbi>True</AndroidCreatePackagePerAbi>
	</PropertyGroup>
```

 

### Steps to Reproduce

Select local Android device as target, build configuration Release, hit Publish. but before:

1. We try to specify versions inside .cproj:
A:
```
		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<AndroidVersionCode>007</AndroidVersionCode>
		<ApplicationVersion>7</ApplicationVersion>
```

after Publish in VS for windows this results in:
![image](https://user-images.githubusercontent.com/25801194/200252132-5bcdc6fb-be6e-4d41-9a27-c74c4622f9b8.png)

Version Code 1

B:

```
		<ApplicationDisplayVersion>0.007</ApplicationDisplayVersion>
		<AndroidVersionCode>007</AndroidVersionCode>
		<ApplicationVersion>7</ApplicationVersion>
```

after Publish in VS for windows this results in:

![image](https://user-images.githubusercontent.com/25801194/200252212-8ca74ae3-7088-4ab2-a08f-85bf99d4ef09.png)

Version Code 1

As you can see there is no *appearent* way to set Version Code to other than 1 inside .cproj

2. We do not modify manifest file to specify version code to workaround the issue above, otherwise we meet another bug: if one specifies version code inside manifest then the build process takes sdk build target from manifest too (why), doesn't find it (we never did put it there), then uses sdk 19 by default and gives us a nice "build failed".

### Link to public reproduction project repository

https://github.com/taublast/MauiDroidVersionCodeBug/

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

et6.0-android

### Did you find any workaround?

No.

**Comment by AndreasReitberger** [comment]
I set the `Version` and `VersionCode` at the `AndroidManifest.xml` located in the `Platforms` folder.

```xaml
<?xml version="1.0" encoding="utf-8"?>
<manifest
	xmlns:android="http://schemas.android.com/apk/res/android"
	android:versionCode="40"
        android:versionName="1.3.0"
	>
	<application
		android:allowBackup="true"
		android:label="AppName"
		android:icon="@mipmap/appicon"
		android:roundIcon="@mipmap/appicon_round"
		android:supportsRtl="true"
		android:networkSecurityConfig="@xml/network_security_config"
		>
		<!-- Xam.Plugins.Messaging -->
		<!--android:name="android.support.v4.content.FileProvider"-->
		<provider android:name="androidx.core.content.FileProvider" android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" />
		</provider>
	</application>
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.FLASHLIGHT" />
</manifest>
```

**Comment by dellis1972** [comment]
This is a comment from the docs at https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/building-apps/build-properties.md#androidversioncode

```
This property is ignored if `$(AndroidCreatePackagePerAbi)` and `$(AndroidVersionCodePattern)` are used.
```

That said, having the value be derived from `ApplicationVersion` when using `AndroidCreatePackagePerAbi` should probably be something we could look at. 

In the meantime I have found that by setting the `android:versionCode="4"` in the `Platforms/Android/AndroidManifest.xml` does work, at least on .net 7.0.
