### ISSUE TITLE
[Bug] FilePicker throw an exception on WinUI3

### ISSUE THREAD

**Issue by realZhangChi** [dotnet/maui#1113]
### Description

FilePicker throw  exception **System.Runtime.InteropServices.COMException:“Invalid window handle. (0x80070578)”** on WinUI3

### Steps to Reproduce

1. Create a `maui-blazor` project
2. Call `FilePicker.PickAsync` by the following code
```
        private async void Button_Clicked(object sender, EventArgs e)
        {
            var result = await FilePicker.PickAsync();
        }
```
3.  Press **F5** to run *.WinUI3(Package) project
4.  Click the button to call method `Button_Clicked`

### Basic Information

- Version with issue: 6.0.100-preview.4.*
- Last known good version:
- IDE: 16.11.0 Preview1.0
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by AmSmart** [comment]
I believe this a well-known Project Reunion issue. Check out this [workaround](https://github.com/microsoft/ProjectReunion/issues/466#issuecomment-779628934) on the ProjectReunion repo

**Comment by realZhangChi** [comment]
> I believe this a well-known Project Reunion issue. Check out this [workaround](https://github.com/microsoft/ProjectReunion/issues/466#issuecomment-779628934) on the ProjectReunion repo

Thanks for your reply. I checked the workaround and it requires us to initialize the window manually when we use FileOpenPicker, but that doesn't help maui's project because maui wraps FileOpenPicker and I can't get an instance of it. maui needs to initialize the window when calling OpenFilePicker? I would be happy to contribute code if needed.

**Comment by AmSmart** [comment]
I don't think this is a bug that the MAUI team would want to fix since it'll likely be fixed from Project Reunion end before they reach 1.0. That being said, I don't think it'll be difficult to wrap the ``FileOpenPicker`` as a Dependency Service in your project.

**Comment by realZhangChi** [comment]
I understand, thanks

**Comment by aokocax** [comment]
For windows environment I was able to run it this way. It works flawlessly with both MAUI and MAUI-Blazor.

https://github.com/dotnet/maui/issues/2194#issuecomment-1003773033
