### ISSUE TITLE
iOS app fails when deployed to TestFlight using NotificationHubClient

### ISSUE THREAD

**Issue by ikeoriaku123** [dotnet/maui#11131]
### Description

Maui for iOS works on debug when running visual studio 2022 preview for Mac on macbook and deploying on iPhone device but fails when installed on Iphone using TestFlight. Using NotificationHubClient

nuget package: Microsoft.Azure.NotificationHubs 4.1.0

These are the code snippets;
```C#
public async Task<bool> IsDeviceRegisteredForNotificationsAsync()
        {
            var list = await _client.GetRegistrationsByChannelAsync(CleanDeviceToken(), 100);
            var deviceIsRegistered = list.Any();

            return deviceIsRegistered;
        }

        public async Task RegisterForNotifications(IEnumerable<string> tags)
        {
            var trimmedDeviceToken = await SecureStorage.GetAsync(Constants.DeviceTokenKey);

            if (trimmedDeviceToken == null || trimmedDeviceToken.Length == 0)
                return;

            var deviceRegisters = await _client.GetRegistrationsByChannelAsync(trimmedDeviceToken, 100);

            if (!deviceRegisters.Any())
            {
                await _client.CreateAppleNativeRegistrationAsync(trimmedDeviceToken, tags);
                await _client.CreateAppleTemplateRegistrationAsync(trimmedDeviceToken, Constants.APNTemplateBody, tags);
            }
        }
```
### Steps to Reproduce

1. Checked in working code to Azure Devops repository.
2. Merged code to master branch
3. CI pipelines kicks off
4. IPA file is generated
5. Run Release to deploy signed ipa file
6. App is deployed to TestFlight
7. Install the app to my iPhone.
8. Open the app
9. Successfully logged in
10. Throws an error when it get to NotificationHubClient lines. Please see logs

System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowRequiredMemberMissingException(XmlReaderDelegator xmlReader, Int32 memberIndex, Int32 requiredIndex, XmlDictionaryString[] memberNames)
System.Runtime.Serialization.SerializationException: ErrorInLine, 1, 1162 UnexpectedElementExpectingElements, Element, DeviceToken, http://schemas.microsoft.com/netservices/2010/10/servicebus/connect, PushVariables

### Link to public reproduction project repository

N/A

### Version with bug

6.0.424

### Last version that worked well

6.0.424

### Affected platforms

iOS

### Affected platform versions

ios 15.7, ios 16

### Did you find any workaround?

No

### Relevant log output

```shell
* System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowRequiredMemberMissingException(XmlReaderDelegator xmlReader, Int32 memberIndex, Int32 requiredIndex, XmlDictionaryString[] memberNames)  System.Runtime.Serialization.XmlObjectSerializerReadContext.GetMemberIndexWithRequiredMembers(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, XmlDictionaryString[] memberNamespaces, Int32 memberIndex, Int32 requiredIndex, ExtensionDataObject extensionData)  System.Runtime.Serialization.ReflectionXmlReader.ReflectionReadMembers(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] , ClassDataContract , Object& )  System.Runtime.Serialization.ReflectionReader.ReflectionReadClass(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] , ClassDataContract )  System.Runtime.Serialization.ReflectionXmlClassReader.ReflectionReadClass(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )  System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator , XmlObjectSerializerReadContext )  System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract , XmlReaderDelegator )  System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)  System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)  System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator , Boolean , DataContractResolver )  System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator , Boolean , DataContractResolver )  System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator , Boolean )  System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlReader )  Microsoft.Azure.NotificationHubs.Messaging.EntityDescriptionSerializer.Deserialize(XmlReader reader, String typeName)  Microsoft.Azure.NotificationHubs.NotificationHubClient.<ReadEntityAsync>d__205`1[[Microsoft.Azure.NotificationHubs.AppleRegistrationDescription, Microsoft.Azure.NotificationHubs, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()  Microsoft.Azure.NotificationHubs.NotificationHubClient.<>c__DisplayClass195_0`1.<<CreateOrUpdateRegistrationImplAsync>b__0>d[[Microsoft.Azure.NotificationHubs.AppleRegistrationDescription, Microsoft.Azure.NotificationHubs, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()  Microsoft.Azure.NotificationHubs.NotificationHubRetryPolicy.<RunOperation>d__4`1[[Microsoft.Azure.NotificationHubs.AppleRegistrationDescription, Microsoft.Azure.NotificationHubs, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()  Microsoft.Azure.NotificationHubs.NotificationHubRetryPolicy.<RunOperation>d__4`1[[Microsoft.Azure.NotificationHubs.AppleRegistrationDescription, Microsoft.Azure.NotificationHubs, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()  Microsoft.Azure.NotificationHubs.NotificationHubClient.<CreateOrUpdateRegistrationImplAsync>d__195`1[[Microsoft.Azure.NotificationHubs.AppleRegistrationDescription, Microsoft.Azure.NotificationHubs, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()  App.Client.Core.Infrastructure.Notifications.NotificationManager.RegisterForNotifications(IEnumerable`1 tags)  App.Client.Maui.ViewModels.LoginPageViewModel.RequestLogin()
```

**Comment by jfversluis** [comment]
Hey there, thanks for the report!

Would you be able to add this to your csproj file and see if that helps?

```xml
<PropertyGroup Condition="'$(TargetFramework)'=='net6.0-ios'">
    <MtouchExtraArgs>--linkskip=Microsoft.Azure.NotificationHubs</MtouchExtraArgs>
  </PropertyGroup>
```

I suspect that the linker strips out needed components and the Microsoft.Azure.NotificationHubs plugin not made compatible with that.

**Comment by ikeoriaku123** [comment]
> Hey there, thanks for the report!
> 
> Would you be able to add this to your csproj file and see if that helps?
> 
> ```
> <PropertyGroup Condition="'$(TargetFramework)'=='net6.0-ios'">
>     <MtouchExtraArgs>--linkskip=Microsoft.Azure.NotificationHubs</MtouchExtraArgs>
>   </PropertyGroup>
> ```
> 
> I suspect that the linker strips out needed components and the Microsoft.Azure.NotificationHubs plugin not made compatible with that.

Hi @jfversluis, I was able to resolve it by adding
<PropertyGroup>
		<UseInterpreter Condition="$(TargetFramework.EndsWith('-ios'))">true</UseInterpreter>
	</PropertyGroup>

But I will try yours and see if fixes it. The above fixed it. Please which is recommended? Thanks

**Comment by ikeoriaku123** [comment]
<PropertyGroup>
		<UseInterpreter Condition="$(TargetFramework.EndsWith('-ios'))">true</UseInterpreter>
	</PropertyGroup>

**Comment by jfversluis** [comment]
I'll have to defer to @rolfbjarne for that question :)

**Comment by rolfbjarne** [comment]
Feel free to use either approach. The --linkskip option may make your app a bit bigger (it's probably negligable, but if you care about app size you might want to test and see the difference in your case), while enabling the interpreter might make your app slightly slower (which is usually not a problem unless you're a game chasing FPS). I'd say that stick with what you've found to work.

**Comment by jfversluis** [comment]
OK, so I think this is handled for now, I'm also reaching out to the team behind this library to see if we can make this better without extra settings. Happy push notificationing!

**Comment by ikeoriaku123** [comment]
> OK, so I think this is handled for now, I'm also reaching out to the team behind this library to see if we can make this better without extra settings. Happy push notificationing!

Thanks @jfversluis
