### ISSUE TITLE
Can't specify the color of an SVG image

### ISSUE THREAD

**Issue by Jabbah76** [dotnet/maui#11141]
### Description

I'm trying to use an SVG image in my project but I can't specify the color. The Image color doesn't have a ForeColor property. How to change the color in xaml or codebehind? Note that I would like to use the same image but with different colors.

As an alternative I tried to set the color using the TintColor property in the project file, but that doesn't seem to work. The image always renders black.

This is the project file:

`    <ItemGroup>`
`      <None Remove="Resources\Images\delete.svg" TintColor="#FF0000" BaseSize="50,50" />`
`      <None Remove="Resources\Splash\splash.svg" />`
`    </ItemGroup>`

And this is the result:

![image](https://user-images.githubusercontent.com/58596571/200276020-13ed42aa-2230-4618-a681-ebf9dfda29c0.png)

I'm kind of puzzled that we should set the color in the project file, instead of a property on the Image itself.

### Steps to Reproduce

1. Create a new Maui project
2. Add an SVG image to the project and set the color as described above
3. Run the project, image stays black

### Link to public reproduction project repository

None

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

All Android

**Comment by Phenek** [comment]
Try this
````
<MauiImage Include="Resources\Images\delete.svg" TintColor="#FF0000" BaseSize="50,50" />
````
Rather than remove it like you do
````
<None Remove="Resources\Splash\splash.svg" />
````

**Comment by Jabbah76** [comment]
That was a mistake indeed, but I changed it, but the SVG still renders black, despite the TintColor.

**Comment by Phenek** [comment]
I have a handler workaround for you but only work on iOS ans Android.

ColorImage.cs
````csharp
namespace YourProject.Controls
{
    public interface IColorImage : IImage
    {
        public Color Color { get; }
    }

    public class ColorImage : Image, IColorImage
    {
        public static readonly BindableProperty ColorProperty = BindableProperty.Create(nameof(Color),
            typeof(Color), typeof(ColorImage), Colors.Black);

        public Color Color
        {
            get => (Color)GetValue(ColorProperty);
            set => SetValue(ColorProperty, value);
        }
    }
}

namespace YourProject.Handlers
{
    public partial class ColorImageHandler : ImageHandler
    {

        public static PropertyMapper<IColorImage, ColorImageHandler> ColorImageMapper = new PropertyMapper<IColorImage, ColorImageHandler>(ImageHandler.Mapper)
        {
            [nameof(IColorImage.Color)] = MapColor
        };

        public ColorImageHandler() : base(ColorImageMapper)
        {

        }

        public ColorImageHandler(PropertyMapper mapper = null) : base(mapper ?? ColorImageMapper)
        {

        }
    }
}
````

ColorImageHandler.Android.cs
````
namespace YourProject.Handlers
{
    public partial class ColorImageHandler : ImageHandler
    {
        public static void MapColor(ColorImageHandler handler, IColorImage image)
        {
            handler.PlatformView?.UpdateColor(image);
        }
    }

    public static class ImageViewExtension
    {
        public static void UpdateColor(this ImageView imageView, IColorImage image)
        {
            var color = image.Color ?? Colors.Black;
            var colorFilter = new PorterDuffColorFilter(color.ToAndroid(), PorterDuff.Mode.SrcIn);
            imageView.SetColorFilter(colorFilter);
        }
    }
}
````

ColorImageHandler.iOS.cs
````
namespace YourProject.Handlers
{
    public partial class ColorImageHandler : ImageHandler
    {
        public static void MapColor(ColorImageHandler handler, IColorImage image)
        {
            handler.PlatformView?.UpdateColor(image);
        }
    }

    public static class UIImageViewExtension
    {
        public static void UpdateColor(this UIImageView imageView, IColorImage image)
        {
            var color = image.Color ?? Colors.Black;
            imageView.Image = imageView.Image.ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);
            imageView.TintColor = color.ToPlatform();
        }
    }
}

````

**Comment by myrup** [comment]
Is this really closeable? It seems like something that should just be working out-of-the-box.

Perhaps a TintColor attribute on `Image`.
