### ISSUE TITLE
Unable to access raw json asset file.

### ISSUE THREAD

**Issue by cris-m** [dotnet/maui#11143]
### Description

accessing json raw asset throw `System.AggregateException` with `System.IO.FileNotFoundException` inner exception when using `OpenAppPackageFileAsync` function. I am able to access `AboutAssets.txt` using the same method. I have cleaned and rebuilt the project multiple time but the problem persist.

### Steps to Reproduce

1. Create a `json` file in `Resources\Raw` folder.
2. Change `Build Action` to `MauiAsset`
3. Try to access the file in any method using `OpenAppPackageFileAsync` method. eg: 
      ```csharp
      var stream = FileSystem.OpenAppPackageFileAsync("CountryAssets.json");
      ```
4. Execute the project

### Link to public reproduction project repository

https://github.com/cris-m/ExampleApp.git

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.1, Android 13.0,  macOS ventura 13.0

**Comment by jfversluis** [comment]
Could you try to remove these lines and see if that makes it work again?

https://github.com/cris-m/ExampleApp/blob/main/ExampleApp/ExampleApp.csproj#L55-L62

**Comment by cris-m** [comment]
> Could you try to remove these lines and see if that makes it work again?
> 
> https://github.com/cris-m/ExampleApp/blob/main/ExampleApp/ExampleApp.csproj#L55-L62

It works perfectly. Visual studio does not clean the `csproj` file after removing a file from a project.
