### ISSUE TITLE
 [Bug] Error compiling .NET MAUI project

### ISSUE THREAD

**Issue by Skyscalesystems** [dotnet/maui#1114]
### Steps to Reproduce

1. following  this blog : https://github.com/dotnet/net6-mobile-samples
2. MAUI Setup fine. when am creating MAUI project and Compile am facing this error:  error NU1101: Unable to find package Microsoft.Maui. No packages exit with this id in source(s): Microsoft Visual Studio offline Packages, nuget.org
3. 

### Basic Information

- Version with issue: Visual Studio Community 2019 Preview
- Last known good version:  Visual Studio Community 2019 Preview
- IDE:  Visual Studio Community 2019 Preview 16.11.0 Preview 1.0
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots :
![image](https://user-images.githubusercontent.com/27279515/119951130-3d1b8200-bfb9-11eb-9ccd-3e969b5df58a.png)

![image](https://user-images.githubusercontent.com/27279515/119951861-0a25be00-bfba-11eb-890b-3474b2f9b5f2.png)

**Comment by Serge-N** [comment]
What's you output for maui-check?

**Comment by Serge-N** [comment]
Also don't forget to add maui to your nuget config.

`dotnet new nugetconfig`
`dotnet nuget add source -n maui-preview https://aka.ms/maui-preview/index.json`

**Comment by ncarandini** [comment]
Instead of using CLI for adding the source of NuGet MAUI packages on each MAUI project you create, I suggest to add the source on Visual Studio:
1) Open Visual Studio
2) Go to "Tools | Options | NuGet Package Manager | Package Sources"
3) Create a new source (I've named it "MAUI Preview") with `https://aka.ms/maui-preview/index.json` as the source URL
![image](https://user-images.githubusercontent.com/139274/120100761-c0b4aa80-c142-11eb-978d-f400c5dab73b.png)

**Comment by Skyscalesystems** [comment]
Thanks,
Issue remain same 
![image](https://user-images.githubusercontent.com/27279515/120169005-1fe6ed80-c21d-11eb-9da6-3a70624c106f.png)

Please help me if any possible come to online to fix it.

**Comment by jsuarezruiz** [comment]
How did you create the project, using the App .NET MAUI project template?
Are you using https://github.com/dotnet/maui-samples/blob/main/NuGet.config?

**Comment by jonathanpeppers** [comment]
So you should not need a `NuGet.config` file anymore in .NET 6 Preview 5. Everything you need should be on NuGet.org by default.

Is everyone using this version?

```xml
<PackageReference Include="Microsoft.Maui" Version="6.0.100-preview.5.794" />
```

https://github.com/dotnet/maui-samples/blob/bb264d046139f6635ed066157c44b99010b8d1dd/HelloMaui/HelloMaui.csproj#L15

**Comment by jfversluis** [comment]
As this is about older previews I'm going to assume this is all fixed by now :) If not please open a new issue, thanks!
