### ISSUE TITLE
DVTItunesSoftwareServiceFoundation error deploying to iOS device

### ISSUE THREAD

**Issue by JRosanowski** [dotnet/maui#11158]
### Description

This error occurs when trying to deploy to the device with our app and with the .Net Maui sample Weather app. I'm using Visual Studio 17.4 Preview and XCode 14.0.1. I also have Visual Studio 17.3 installed if that makes any difference. Any help appreciated!

error HE0004: Could not load the framework 'DVTITunesSoftwareServiceFoundation' (path: /Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/DVTITunesSoftwareServiceFoundation): 
dlopen(/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/DVTITunesSoftwareServiceFoundation, 0x0001): Library not loaded: @rpath/ContentDelivery.framework/Versions/A/ContentDelivery
  Referenced from: <F96A284E-6B5C-36B8-8EA6-EA949DC02F1D> /Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/DVTITunesSoftwareServiceFoundation
  Reason: tried: '/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.454/tools/lib/mlaunch/mlaunch.app/Contents/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.454/tools/lib/mlaunch/mlaunch.app/Contents/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.454/tools/lib/mlaunch/mlaunch.app/Contents/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.454/tools/lib/mlaunch/mlaunch.app/Contents/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Library/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/System/Library/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file, not in dyld cache)
        

### Steps to Reproduce

1. Build and attempt to deploy the .Net Maui Sample app

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.0.3

**Comment by tj-devel709** [comment]
Hi! Specifically - Microsoft.iOS.Sdk version 15.4.454 does not support Xcode 14 so please make sure that is updated

**Comment by JRosanowski** [comment]
Seems to be fixed in the VS 17.4 release

**Comment by Waaheeda** [comment]
still facing this issue in VS 2022 17.4 

Visual Studio Community 2022 for Mac
Version 17.4 (build 2406)
Installation UUID: db33e1f1-4afe-479e-8111-5174d974674a

Runtime
.NET 6.0.9 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.4.0-3.22461.4+8ab250290a4010c11a21521f78dbc87dbb7aac81

NuGet
Version: 6.3.1.1

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.100/Sdks
SDK Versions:
	7.0.100
	6.0.403
	6.0.401
	5.0.408
	5.0.407
	5.0.404
	5.0.403
	3.1.425
	3.1.423
	3.1.420
	3.1.418
	3.1.416
	3.1.415
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.0
	6.0.11
	6.0.9
	5.0.17
	5.0.16
	5.0.13
	5.0.12
	3.1.31
	3.1.29
	3.1.26
	3.1.24
	3.1.22
	3.1.21

Xamarin.Profiler
Version: 1.8.0.22
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 12.2.8.3 (Visual Studio Community)
Commit: xamarin-android/d17-1/fafdba7
Android SDK: /Users/dmi.user/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:42:28 UTC

Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2022-11-02 23:42:28 UTC

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:42:23 UTC

Build Information
Release ID: 1704002406
Git revision: dfb45c1152306f0d5f77334f9d026b0aadb7ec90
Build date: 2022-11-02 23:40:15+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 13.0.1
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:14:54 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

**Comment by mibuswolf** [comment]
I have the same problem

**Comment by mariomurrent-softwaresolutions** [comment]
Same issue here - does not work with iOS simulators
