### ISSUE TITLE
Android MauiIcon resizetizering issue

### ISSUE THREAD

**Issue by Bohdandn** [dotnet/maui#11159]
### Description

MauiIcon on Android 8+ resizing wrongly scales foreground and "ForegroundScale" option that should fix it behaves unexpectedly.
Default project, default csproj, changes:
`<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" />`
- Color removed for android in order to have nice rounded icon on old androids.
- svg's replaced with similar to default ones 456x456 with ms icon and rounded bg - https://github.com/Bohdandn/simple-maui/tree/master/Resources/AppIcon

Main points:
- I think it would be much better to generate icon similar to old Android icons by default, MAUI stretches FG to like 120% by default so it never fit
- I found that ForegroundScale should fix it but it seems behave differently than supposed [here](https://learn.microsoft.com/en-us/answers/questions/990590/maui-appicon-strange-scaling-on-android.html) and [here](https://learn.microsoft.com/en-us/answers/questions/990590/maui-appicon-strange-scaling-on-android.html) 
- my maui-android version is - 6.0.541, there is no such in "Version with bug" selector

Here how it looks like:

Emulator: Nexus 6 API24
![image](https://user-images.githubusercontent.com/48527375/200417480-97b61662-dd89-435d-bda4-a13b091a6f65.png)

Emulator: Pixel 3 XL API33
![image](https://user-images.githubusercontent.com/48527375/200417708-d0f8124e-34ec-4f55-b704-cd0a1b0b6253.png)

ForegroundScale="0.65"
![image](https://user-images.githubusercontent.com/48527375/200417761-1cb4cbff-9862-49ba-ba72-23ee2957c77b.png)

ForegroundScale="0.2"
![image](https://user-images.githubusercontent.com/48527375/200418733-d4b50b96-2e8f-421d-831e-4ad5afdf5303.png)

ForegroundScale="0.1"
![image](https://user-images.githubusercontent.com/48527375/200418740-93f59009-ce71-4752-a073-f80c7e45bc46.png)

ForegroundScale="0.05" - looking to the trend I expected this one to finally fit...
![image](https://user-images.githubusercontent.com/48527375/200418755-0ad83b02-94a3-42f2-bd9d-699af8a39e10.png)

Setting BaseSize="128,128" doesn't seem to change anything

### Steps to Reproduce

1. dotnet new maui
2. replace icons (even with original one you will see that FG is too big)
3. Run on android 8+

### Link to public reproduction project repository

https://github.com/Bohdandn/simple-maui

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8+

### Did you find any workaround?

Use android native capabilities to set icon

**Comment by Bohdandn** [comment]
Checked after .net7 update (maui-* workloads - 7.0.49/7.0.100) - behavior still the same.
One more obvious note - scaled icon via ForegroundScale looks the same on iOS and old android

**Comment by tranb3r** [comment]
Any update? Thanks
cc @mattleibow

**Comment by Mephisztoe** [comment]
I experimented with this option today using my iPhone after we had some weird issues with ForegroundScale.

My expectation was that a value of 1.0 means that my AppIcon has its full size as designed (100%) and gets reduced with values smaller than that (with 0.5 being half its original size).

However, the Resizetizer takes this input value and multiplies some main scale value with it. 
This makes a value of 0.0 resulting in the icon vanishing.
However, a value of 0.5 actually doubles the size as it seems.

Also:
Whenever I enter a value with more than one decimal place (like 0.65 or 0.25), the AppIcon also vanishes. I had a look at the sources and there is nothing I could find that looks broken. The value is parsed into a Double first of all and later type casted into a Float. Nothing wrong there. However, I get only more or less predictable results when I enter values with only one decimal place and that's... weird.

Regarding iOS I'd say: Just don't use that option. Then the mechanism is ignored and the icon behaves as expected.

**Comment by tranb3r** [comment]
> Also: Whenever I enter a value with more than one decimal place (like 0.65 or 0.25), the AppIcon also vanishes. I had a look at the sources and there is nothing I could find that looks broken. The value is parsed into a Double first of all and later type casted into a Float. Nothing wrong there. However, I get only more or less predictable results when I enter values with only one decimal place and that's... weird.

There was an issue with the conversion of the double value, caused by incorrect culture being used.
So x0.65 could be interpreted as x65. While x0.6 would be x6.
I believe it has been fixed, but not released yet.

**Comment by Mashedpoturtles** [comment]
> > Also: Whenever I enter a value with more than one decimal place (like 0.65 or 0.25), the AppIcon also vanishes. I had a look at the sources and there is nothing I could find that looks broken. The value is parsed into a Double first of all and later type casted into a Float. Nothing wrong there. However, I get only more or less predictable results when I enter values with only one decimal place and that's... weird.
> 
> There was an issue with the conversion of the double value, caused by incorrect culture being used. So x0.65 could be interpreted as x65. While x0.6 would be x6. I believe it has been fixed, but not released yet.

how long usually can we expect a release for a fix for something like this?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on android emulator API33 platform with sample project.
[simple-maui.zip](https://github.com/dotnet/maui/files/12036335/simple-maui.zip)
API33-ForegroundScale="1"
![API33-1](https://github.com/dotnet/maui/assets/77434865/c2658d12-a8a9-4973-8950-f030b77df99f)
API33-ForegroundScale="0.65"
![API33-0 65](https://github.com/dotnet/maui/assets/77434865/27bb7bc7-3a1d-439f-9bbf-f913b61a2af8)
API33-ForegroundScale="0.2"
![API33-0 2](https://github.com/dotnet/maui/assets/77434865/8652daba-accf-47db-a2a0-e2db7b2cc2f5)
API33-ForegroundScale="0.1"
![API24-0 1](https://github.com/dotnet/maui/assets/77434865/267de72f-b679-4f5a-8b55-9e3e676a7faf)
API33-ForegroundScale="0.05"
![API33-0 05](https://github.com/dotnet/maui/assets/77434865/2cf3e5d6-fe79-46f5-b8e8-69b0afeb175f)

**Comment by tranb3r** [comment]
Why is the icon zoomed-in when foregroundscale=1?
It seems like you have to set foregroundscale=0.65 to get something that looks ok.
