### ISSUE TITLE
[iOS] Entry in Border - strange corner round.

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/maui#11152]
### Description

```xaml
 <VerticalStackLayout>
        <Label Text="Input" x:Name="InputLabel" Style="{StaticResource InputLabelStyle}"/>
        
        <Border Stroke="{StaticResource BackgroundOutline}" StrokeThickness="1" HeightRequest="52" >
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="16" />
            </Border.StrokeShape>
            <Entry x:Name="InputContext" BackgroundColor="{StaticResource BackgroundLight}" Placeholder="Placeholder text" 
                          Margin="8"/> 
        </Border>
       
        <Label Text="Error" x:Name="Error" Style="{StaticResource InputErrorLabelStyle}"/>
    </VerticalStackLayout>
```

<img width="486" alt="Screenshot 2022-11-07 at 18 19 01" src="https://user-images.githubusercontent.com/4385716/200374934-1e9b81e6-e456-45ca-9d00-d121ee14cf2e.png">

left top corner of Entry is rounded. but why?

### Steps to Reproduce

try to do
```xaml
 <VerticalStackLayout>
        <Label Text="Input" x:Name="InputLabel" Style="{StaticResource InputLabelStyle}"/>
        
        <Border Stroke="{StaticResource BackgroundOutline}" StrokeThickness="1" HeightRequest="52" >
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="16" />
            </Border.StrokeShape>
            <Entry x:Name="InputContext" BackgroundColor="{StaticResource BackgroundLight}" Placeholder="Placeholder text" 
                          Margin="8"/> 
        </Border>
       
        <Label Text="Error" x:Name="Error" Style="{StaticResource InputErrorLabelStyle}"/>
    </VerticalStackLayout>
```

### Link to public reproduction project repository

no

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by KSemenenko** [comment]
<img width="438" alt="Screenshot 2022-11-07 at 18 33 20" src="https://user-images.githubusercontent.com/4385716/200376671-c12165e6-a317-40aa-8421-02adfb951a06.png">
also looks like Border is not trim control

**Comment by MGohil** [comment]
Similar issue I came across. Works good in Android but iOS gives strange behaviour with upper left corner. Clipping my content.

![image](https://user-images.githubusercontent.com/16605284/209907913-bd20e08e-9197-41c6-9cb8-1cfa6fe12f18.png)

**Comment by KSemenenko** [comment]
Is there any idea how I can fix that behavior? Now it’s blocker for my next app release

**Comment by breenbob** [comment]
Also having this issue. In my specific circumstance adding more padding to inner element allowed it to "escape" the clipping that occurs. Would rather it was fixed!

**Comment by breenbob** [comment]
Also, I was seeing this behaviour on WinUI too.

**Comment by faheys** [comment]
A possible workaround is to wrap the child of the border element in another border element that is not rounded. 
E.g.
` 
<Border x:Name="RoundedCornerBorder">
            
            <Border StrokeShape="Rectangle"
                    StrokeThickness="0"
                    BackgroundColor="Transparent">
                  
            </Border>
</Border>
`

**Comment by jkhoel** [comment]
I was having the same issue and the solution was to ensure that the clipped element has a height. So if you added a HeightRequest to the HorizontalStackLayout in @MGohil 's screenshot, then that would probably fix it.

I think what is happening is that the shape we add to StrokeShape acts as a clipping mask. We would expect this mask to be perfectly aligned with the Border element, but it looks like moves if no children defines a height.



```

**Comment by FM1973** [comment]
Both workarounds do not work for me. Please fix it.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on iOS platform with project [MauiApp2.zip](https://github.com/dotnet/maui/files/11610805/MauiApp2.zip)

**Comment by jsuarezruiz** [comment]
> <img alt="Screenshot 2022-11-07 at 18 33 20" width="438" src="https://user-images.githubusercontent.com/4385716/200376671-c12165e6-a317-40aa-8421-02adfb951a06.png">
> 
> also looks like Border is not trim control

This should have been fixed by https://github.com/dotnet/maui/pull/10964
<img width="357" alt="Captura de pantalla 2023-06-15 a las 14 03 31" src="https://github.com/dotnet/maui/assets/6755973/1f976860-0915-4cf2-ba2c-b7c86a06ee43">
(sorry for the color selection, is to check easily the clipping)
