### ISSUE TITLE
Error MAUI0000 - System.Xml.XmlException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#11167]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-MAUI0000---SystemXmlXmlException/10177059)._

---
Hello....
Every time I start writing XAML code it starts working and then this comes up. I comment all the lines and the error continues to appear.
I create a new project and the same thing happens.

---
#### Feedback Bot on 10/19/2022, 08:03 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rachelkang** [comment]
Hi, Cristian - Could you pease elaborate on what you are experiencing? If you can share the exact error message, any screenshots, and ideally a repo, that would be immensely helpful for us to investigate further. Thank you!
