### ISSUE TITLE
MauiSplashScreen resizetizering issue

### ISSUE THREAD

**Issue by Bohdandn** [dotnet/maui#11160]
### Description

Splash screen image is too small and there is no way to change that as described here: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen.

Several notes:
- Setting `BaseSize="1024,1024" Resize="false"` doesn't change anything
- I tried different settings and "~\obj\Debug\net6.0-android\resizetizer\sp\maui_splash_image.xml" always has `android:width="108dp" android:height="108dp"` size in tag containing image, changing it solves the problem until next rebuild
- Logo looks fine here but usually there is logo with text there or something that is expected to be big on screen
- my maui-android version is - 6.0.541, there is no such in "Version with bug" selector
- my original splash has small icon and big text below, it is expected to cover ~70% of the portrait screen width and looks creepy now

Here how it looks like:

Emulator: Pixel 3 XL API33
![image](https://user-images.githubusercontent.com/48527375/200422998-679acb8c-2fc5-4509-a4ab-e1c2617c37b3.png)

Emulator: Nexus 6 API24 (On device with Android 11 it looks the same)
![image](https://user-images.githubusercontent.com/48527375/200423069-82b5a628-43b0-49e9-9847-852ae3cb6810.png)

iPhone 14 Pro Max iOS 16.0
![image](https://user-images.githubusercontent.com/48527375/200423093-55551c19-2513-4c79-9b96-d0f0f15ca38e.png)

### Steps to Reproduce

1. Create default project 
2. Change cproj: `<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="Green" />`
3. Replace splash.svg with https://github.com/Bohdandn/simple-maui/blob/master/Resources/Splash/splash.svg (bg color is different from icon to see that it is actually splash image there)
4. Check splash screen

### Link to public reproduction project repository

https://github.com/Bohdandn/simple-maui

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

### Did you find any workaround?

Manually create splash screens using native capabilities

**Comment by Bohdandn** [comment]
Checked after .net7 update (maui-* workloads - 7.0.49/7.0.100) - observed behavior changed, it started responding on properties so it is possible to get good looking splash:

- [x] - `iOS`  looks fine with `Resize="true"` (see screenshot), not sure about static size
- [ ] - `Android 5-8` - splash has always BaseSize size
- [ ] - `Android 8+` - splash has always 108dp size

iOS 16, Resize="true"
![image](https://user-images.githubusercontent.com/48527375/200685402-ec7492f8-5c41-4ec4-933b-f93552aa972b.png)

**Comment by ewerspej** [comment]
On Android, the splash screen image is limited in size and cannot be set to any arbitrary value: https://developer.android.com/develop/ui/views/launch/splash-screen

**Comment by Bohdandn** [comment]
@ewerspej Right, then current issue is fixed in 7.0.100.
