### ISSUE TITLE
more than one collectionview doesn't work in visual studio for mac

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#11164]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/more-than-one-collectionview-doesnt-wor/10184275)._

---
I have one view page with two collection views and a button at the bottom. When running this in visual studio for windows compiled for Win all works fine. The exact same code compiled and run in visual studio for Mac compiled for Mac catalyst displays incorrectly. The first collection view displays fine, but everything below the first collection view including the second collection view and the button is not displayed.
github public resposity showing the problem.
https://github.com/r3dgraphix/MauiBaseVS.git

---
#### Feedback Bot on 10/27/2022, 07:40 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rachelkang** [comment]
Hi, Rick - thanks for opening this issue. You. mentioned that it's compiling through VS on Windows but not through VSfM - could you clarify which platform/device/simulator you're running on when it is working as you expect vs when it is not?

**Comment by AdamBebko** [comment]
I'm having the same problem on VS 2022 on MacOS, 2nd collection view in a page is not showing. I can't test on windows. Running in iOS simulator.
