### ISSUE TITLE
Major change in Grids in latest .NET MAUI Preview

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#11162]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Major-change-in-Grids-in-latest-NET-MAU/10177131)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:VS 17.4.0 Preview 3]
I upgraded to Visual Studio 17.4.0 Preview 4, and my .NET MAUI app suddenly started to behave **VERY** differently! I'm creating a little Sudoku game using .NET MAUI. Sudoku requires a lot of nested tables of Cells.

Previously, controls that were children of Grids seemed to default to being in the Fill state.

After upgrading, all of the children seem to be defaulting to being in the upper-left corner of the Grid cell! This is a major, unexpected change! Even after I explicitly add **HorizontalOptions** = **Fill** and **VerticalOptions** = **Fill**, it doesn't seem to be taking effect.

I'm not sure if this is an intentional breaking change, but it was very unexpected!

---
#### Feedback Bot on 10/19/2022, 06:58 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
Fixed by #10768.
