### ISSUE TITLE
Microsoft.Maui.Platform.HandlerNotFoundException: 'Handler not found for view Microsoft.Maui.Controls.Maps.Map.'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#11169]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MicrosoftMauiPlatformHandlerNotFoundE/10166730)._

---
Add MapControl on xaml page in common project
Maui App project references common project
Under Windows, the above error occurs. Works in Android.

---
#### Feedback Bot on 10/8/2022, 06:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment]
Unfortunately, this is a case of a bad error message and then a sad case of this control not being available on windows yet.

With the case of the bad error, we currently don't have a way in certain scenarios to say "this platform is not supported" gracefully. This is something we are looking at and even the first step of a better exception will help.

In the second case, WinUI 3.x currently has not yet ported the map control over from UWP, so we don't really have a way: https://github.com/microsoft/microsoft-ui-xaml/issues/3024

There is the potential for leveraging the web version of the map control: https://github.com/CommunityToolkit/Maui/pull/604
However, this is still being worked on by the maui team and the community.

Not a happy answer, but this is the current state of things. One way to help would be to make sure you thumbs-up/comment on the WinUI issue:  https://github.com/microsoft/microsoft-ui-xaml/issues/3024

**Comment by jfversluis** [comment]
I don't think there is much for us to do here at the moment unfortunately. Since it's not really actionable I don't see much reason to keep it around. Closing for now. 

Keep your eye on the .NET MAUI Community Toolkit, a Windows alternative should be there relatively soon!
