### ISSUE TITLE
Button ImageSource

### ISSUE THREAD

**Issue by angelru** [dotnet/maui#11205]
### Description

With net7 the button icon is misaligned:

net7:
<img src="https://user-images.githubusercontent.com/11645585/200703431-6255c52d-4564-471d-8005-262316edfcc8.jpg" width="300" height="600" />

net6:
<img src="https://user-images.githubusercontent.com/11645585/200703452-56818189-333a-43e2-83a6-bb6725323ab5.jpg" width="300" height="600" />

### Steps to Reproduce

```
 <Button
                ImageSource="icon"
                Text="Bug" />
```

### Link to public reproduction project repository

http://

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

6.0.424

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

### Did you find any workaround?

use net6.

**Comment by PureWeen** [comment]
@angelru This was changed by design to make all 3 platforms layout the icons in the same fashion  #10309. 

Can you use the `ContentLayout` property on the button to push the alignment of the icon to the left edge?

**Comment by angelru** [comment]
@PureWeen Yes, I thought so, but it also moves the text. That's fine if the text is the same, but not in this case, it's all very misaligned that way.
