### ISSUE TITLE
Maui Email ComposeAsync Fails on Windows but works on Android

### ISSUE THREAD

**Issue by cdavidyoung** [dotnet/maui#11218]
### Description

In the app that I am currently developing I followed the guidelines to add email:

https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/email?view=net-maui-7.0&tabs=android

As reported in issue #5353 it does not work in Windows.  However, after adding the required lines to AndroidManifest.xml I tested it successfully on my Android tablet.

For what it is worth, the nearly same email code works on Xamarin for both Android and iOS.  I am hoping that this Maui Windows feature is just not ready for prime time and will be fixed in an upcoming release.

### Steps to Reproduce

The link to the repo that I provided can be used to reproduce the problem.  It is the same sample app that was provided in issue #5353 (thanks!) with the additional lines added to the AndroidManifest.xml to make it work in Android.

### Link to public reproduction project repository

https://github.com/cdavidyoung/MauiRCTest1.git

### Version with bug

7.0 Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

.NET 7.0 SDK Version: 7.0.100-rc.1.22431.12

### Did you find any workaround?

No

### Relevant log output

```shell
This is the exception on Windows:

Message = "The request is not supported. (0x80070032)"
Source = "WinRT.Runtime"
StackTrace = 
"   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)\r\n   at ABI.Windows.ApplicationModel.Email.IEmailManagerStaticsMethods.ShowComposeNewEmailAsync(IObjectReference _obj, EmailMessage message)\r\n   at Microsoft.Maui.ApplicationModel.Communication.EmailImplementation.<PlatformComposeAsync>d__4.MoveNext()\r\n   at MauiRCTest1.Services.EmailService.<SendEmail>d__1.MoveNext() in C:\\Users\\charl\\source\\repos\\GitHub\\MauiRCTest1\\MauiRCTest1\\Services\\EmailService.cs:line 33"
```

**Comment by mattleibow** [comment]
This was fixed in RC 2: https://github.com/dotnet/maui/pull/10063

But, .NET 7 was just released to GA, so try using that.

**Comment by cdavidyoung** [comment]
I am not sure what you mean by "But, .NET 7 was just released to GA, so try using that."

Is is possible for you to fix the sample project?  Thanks

**Comment by cdavidyoung** [comment]
I installed https://devblogs.microsoft.com/dotnet/dotnet-maui-in-dotnet-7-rc1/ 

I just tested it in Windows and it appears to be working now.  Thanks.
