### ISSUE TITLE
Errors after upgrading app from framework 6 to 7.

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#11217]
### Description

After update to Visual Studio 2022 version 17.4.0
and
after upgrading a NET.MAUI app from framework 6 to framework 7 by changing the target .NET Runtime from net6.0 to net 7.0 in the project file I get four times this error:

NU1105 Unable to read project information for 'Finance': Sequence contains more than one element.

After that I see that all the installed NuGet Packages are gone.
I tried to reinstall them but I get the error:
Invalid restore input.
Missing required property 'ProjectName'.  Input files: C:\Sources\MAUI\Finance\Finance\Finance.csproj.

Missing NuGet packages:
Microsoft.Extensions.Localization
Microsoft.Maui.Dependencies
Microsoft.Maui.Extensions
Microsoft.Windows.SDK.BuildTools
System.Runtime.InteropServices.NFloat.Internal

Any solution for this?
Thanks in advance.

### Steps to Reproduce

1. upgrading a NET.MAUI app from framework 6 to framework 7 by changing the target .NET Runtime from net6.0 to net 7.0 in the project file.

### Link to public reproduction project repository

https://github.com/geertgeerits/Finance

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Pixel 5 API 31 Android 12.0

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@geertgeerits if you delete your bin/obj/.vs colder and reopen the project does it work?

**Comment by Taiizor** [comment]
I had the same problem. The problem is in the line below.

`<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>`

Add the bottom line instead of the top line
`<TargetFrameworks>net7.0-android;net7.0-windows10.0.19041.0</TargetFrameworks>`

**Comment by PureWeen** [comment]
@geertgeerits can you paste what your `csproj` looks like now?

it looks like you've removed the WINUI target in your last comment? which is probably why windows isn't working anymore.

**Comment by jfversluis** [comment]
There is something weird going on in our `Entry`, this `ClearButtonVisibilityProperty` is pointing to `SelectionLength` as the regular property. This is incorrect. Opening a PR to fix it now.

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Entry.cs#L99

**Comment by geertgeerits** [comment]
> @geertgeerits can you paste what your `csproj` looks like now?
> 
> it looks like you've removed the WINUI target in your last comment? which is probably why windows isn't working anymore.

If I uncomment the second line (TargetFrameworks Condition=) then I get these 4 errors again:
NU1105 Unable to read project information for 'Finance': Sequence contains more than one element.

Project file:

`<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
		
		
		
		<OutputType>Exe</OutputType>
		<RootNamespace>Finance</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		
		<ApplicationTitle>Finance</ApplicationTitle>

		
		<ApplicationId>com.companyname.finance</ApplicationId>
		<ApplicationIdGuid>54742229-37CC-49C8-814D-220A22B0EF1F</ApplicationIdGuid>

		
		<ApplicationDisplayVersion>3.0.51</ApplicationDisplayVersion>
		<ApplicationVersion>3</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<Authors>Geert Geerits</Authors>
		<Company />
		<PackageIcon>finance_new_80p.png</PackageIcon>
		<Description>Financial applications</Description>
		<Copyright>Geert Geerits</Copyright>
		<PackageReadmeFile>ReadMe.md</PackageReadmeFile>
		<FileVersion>3.0.51</FileVersion>
		<AssemblyVersion>3.0.51</AssemblyVersion>
		<PackageCertificateThumbprint>3258A94BC8069F3911EA6D4619347375B5F4824A</PackageCertificateThumbprint>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
	</PropertyGroup>

	<ItemGroup>
		
		<MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.png" Color="#75F94D" BaseSize="128,128" />
		

		
		<MauiSplashScreen Include="Resources\appiconfg.png" Color="#75F94D" BaseSize="128,128" />

		
		<MauiImage Include="Resources\Images\*" />

		
		<MauiFont Include="Resources\Fonts\*" />

		
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="PageLicense.xaml.cs" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Remove="PageLicense.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Localization" Version="7.0.0-rc.2.22476.2" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="PageAmountGrossOfNet.xaml.cs">
	    <DependentUpon>PageAmountGrossOfNet.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="PageInterestAnnual.xaml.cs">
	    <DependentUpon>PageInterestAnnual.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="PageInterestMonthDay.xaml.cs">
	    <DependentUpon>PageInterestMonthDay.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="PageInvestmentReturn.xaml.cs">
	    <DependentUpon>PageInvestmentReturn.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="PageLoanDetail.xaml.cs">
	    <DependentUpon>PageLoanDetail.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="PageInterestPayDiscount.xaml.cs">
	    <DependentUpon>PageInterestPayDiscount.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Fin.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Fin.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\FinLang.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>FinLang.resx</DependentUpon>
	  </Compile>
	  <Compile Update="PageSettings.xaml.cs">
	    <DependentUpon>PageSettings.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="PageVATCalculation.xaml.cs">
	    <DependentUpon>PageVATCalculation.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Fin.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Fin.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\FinLang.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>FinLang.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="PageAbout.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageAmountGrossOfNet.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageDifferenceDates.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageDifferenceNumbers.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageInterestAnnual.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageInterestMonthDay.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageInterestPayDiscount.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageInvestmentReturn.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageLoanDetail.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageInterestEffective.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageInterestEffectiveBE.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageSettings.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="PageVATCalculation.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Resources\AppIcon\finance_new_80p.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Update="Resources\ReadMe.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
		<AndroidKeyStore>True</AndroidKeyStore>
		<AndroidSigningKeyStore>..\myapp.keystore</AndroidSigningKeyStore>
		<AndroidSigningKeyAlias>key</AndroidSigningKeyAlias>
		<AndroidSigningKeyPass></AndroidSigningKeyPass>
		<AndroidSigningStorePass></AndroidSigningStorePass>
		<ApplicationDisplayVersion>3.0.51</ApplicationDisplayVersion>
		<ApplicationVersion>51</ApplicationVersion>
		<ApplicationId>com.geertgeerits.finance</ApplicationId>
	</PropertyGroup>
</Project>
`

**Comment by arkadym** [comment]
Im stuck with below errors after upgrade, tried leave only windows target, currently left with android and windows. It is weird because this lib not using markup, community toolkit only referenced because of IMessenger.
```
1>...\CommunityToolkit.Maui.Markup.SourceGenerators\CommunityToolkit.Maui.Markup.SourceGenerators.TextAlignmentExtensionsGenerator\EditorTextAlignmentExtensions.g.cs(122,147,122,167): error CS0121: The call is ambiguous between the following methods or properties: 'CommunityToolkit.Maui.Markup.TextAlignmentExtensions_Editor.TextCenterHorizontal(Microsoft.Maui.Controls.Editor)' and 'CommunityToolkit.Maui.Markup.TextAlignmentExtensions_Editor.TextCenterHorizontal(Microsoft.Maui.Controls.Editor)'
1>...\CommunityToolkit.Maui.Markup.SourceGenerators\CommunityToolkit.Maui.Markup.SourceGenerators.TextAlignmentExtensionsGenerator\EntryTextAlignmentExtensions.g.cs(122,145,122,165): error CS0121: The call is ambiguous between the following methods or properties: 'CommunityToolkit.Maui.Markup.TextAlignmentExtensions_Entry.TextCenterHorizontal(Microsoft.Maui.Controls.Entry)' and 'CommunityToolkit.Maui.Markup.TextAlignmentExtensions_Entry.TextCenterHorizontal(Microsoft.Maui.Controls.Entry)'
1>...\CommunityToolkit.Maui.Markup.SourceGenerators\CommunityToolkit.Maui.Markup.SourceGenerators.TextAlignmentExtensionsGenerator\LabelTextAlignmentExtensions.g.cs(122,145,122,165): error CS0121: The call is ambiguous between the following methods or properties: 'CommunityToolkit.Maui.Markup.TextAlignmentExtensions_Label.TextCenterHorizontal(Microsoft.Maui.Controls.Label)' and 'CommunityToolkit.Maui.Markup.TextAlignmentExtensions_Label.TextCenterHorizontal(Microsoft.Maui.Controls.Label)'
1>...\CommunityToolkit.Maui.Markup.SourceGenerators\CommunityToolkit.Maui.Markup.SourceGenerators.TextAlignmentExtensionsGenerator\PickerTextAlignmentExtensions.g.cs(122,147,122,167): error CS0121: The call is ambiguous between the following methods or properties: 'CommunityToolkit.Maui.Markup.TextAlignmentExtensions_Picker.TextCenterHorizontal(Microsoft.Maui.Controls.Picker)' and 'CommunityToolkit.Maui.Markup.TextAlignmentExtensions_Picker.TextCenterHorizontal(Microsoft.Maui.Controls.Picker)'
```

**Comment by arkadym** [comment]
Ah, i see there is 3.0 release, somehow cannot see it yet in updates, how long it usualy takes to appear ?

**Comment by Mielesgames** [comment]
Same problem here, I have no idea on how to fix it

**Comment by mnwhle** [comment]
I have the same error (VS 17.4.0, .NET7 MAUI project):

_NU1105 Unable to read project information for Sequence contains more than one element_

It looks like that the project file is read incorrectly, it is just not read to the end. As a side affect, all NuGet Packages included to it are gone and can't be reinstalled.

The error appears in Windows 11 22H2 and Windows 10 22H2. The same project without any change is loaded and built correctly on Windows 10 21H2.

**Comment by mnwhle** [comment]
Hi,
Any idea when this error to be fixed?
I installed the release 17.4.1, the error is still there. I can't build my project anymore.

**Comment by Alky93** [comment]
...

**Comment by geertgeerits** [comment]
Workaround.
I solved this by creating a new project under the same name.
First rename the folder of the existing project.
Create a new project with the original name and select Framework .NET 7.0.
Import all files from the old project into the new project by right-clicking on the project name and Add... Existing item...
Add all files that way.
It is possible that manual adjustments have to be made to the project file (do not import the old project file!).
This solution is time consuming and not ideal, but I was able to transfer two projects from framework 6 to framework 7.

**Comment by Mielesgames** [comment]
> Workaround. I solved this by creating a new project under the same name. First rename the folder of the existing project. Create a new project with the original name and select Framework .NET 7.0. Import all files from the old project into the new project by right-clicking on the project name and Add... Existing item... Add all files that way. It is possible that manual adjustments have to be made to the project file (do not import the old project file!). This solution is time consuming and not ideal, but I was able to transfer two projects from framework 6 to framework 7.

You can also fix it by installing a bunch of android SDK's  (tools/android/androidSDKmanager)

**Comment by alexanderdp** [comment]
Im having the same issues with upgrading my .net Maui .net 6 to .net 7

_Error WMC9999 Cannot find type System.Windows.DependencyObject in module WindowsBase.dll_

By commenting out all the reference's to Windows in my project file, it now compiles just fine (for now).

**Items commented out:**

		```
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>


<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0-windows10.0.19041.0|AnyCPU'">
	  <LangVersion>10.0</LangVersion>
	</PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0-windows10.0.19041.0|AnyCPU'">
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>
```

My primary targets are Android & iOS, so I'm not too concerned for now, but I would like to have the windows version available as well in the near future.
