### ISSUE TITLE
[Android 13] - MediaPicker - Permissions issue

### ISSUE THREAD

**Issue by MarMarIV** [dotnet/maui#11211]
### Description

This bug is relevant for Android 13 only. Tested on Android 11 and Android 9 too, and it is ok

Mabey it should be problem with these changes: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

Permission is not accepted

Act: Method `CapturePhotoAsync()` throws `PermissionException` with access denied even with valid permissions

Req: Should show camera preview and take photo

### Steps to Reproduce

1. Tap 'Take photo' button
2. Confirm (accept) permission dialog

### Link to public reproduction project repository

https://github.com/MarMarIV/Android13Permissions

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by symbiogenesis** [comment]
Potential duplicate of https://github.com/dotnet/maui/issues/11275
