### ISSUE TITLE
Grid layout applies ColumnSpacing and RowSpacing to invisible children

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#11222]
### Description

It seems that the `Grid` layout does not respect the `IsVisible` property of its children then applying `ColumnSpacing` or `RowSpacing`. Setting the `IsVisible` property of a child to `false` collapses correctly the corresponding cell of the `Grid` layout, but the spacing is still applied, so we end up with double-spacing between the visible children. This makes it difficult to implement dynamic layouts, as hiding a child in the layout is not enough, we need to remove the corresponding `ColumnDefinition` or `RowDefinition` from the `Grid` as well.

### Steps to Reproduce

1. Run the sample project from the provided GitHub repository
2. Use the switches to toggle the visibility of the buttons below
3. Observe the remaining spacing between the visible controls

Here is a screenshot with all buttons visible:

![image](https://user-images.githubusercontent.com/98032058/200840723-2daf894c-9cef-4936-a808-3c53569e2ff1.png)

The following screenshot shows the layout after hiding the first button:

![image](https://user-images.githubusercontent.com/98032058/200840976-e6641415-9b65-4897-8e79-4b4351d71c76.png)

Observe how the spacing before the second button is still applied.

The next screenshot shows the layout after hiding both the first and the second button:

![image](https://user-images.githubusercontent.com/98032058/200841913-d44a221c-fdc7-4d8e-9eb9-93348cda7565.png)

We have a lot of unwanted spacing before the text entry.

### Link to public reproduction project repository

https://github.com/ivan-todorov-progress/maui-grid-spacing-invisible-bug

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

N/A

### Did you find any workaround?

The only workaround I have found in this particular case is to avoid the `ColumnSpacing` and `RowSpacing` properties of the `Grid`, and use the `Margin` property of the children instead. This is rather inconvenient, especially for complex layouts, as adjusting the spacing between the children would involve editing the `Margin` property of each child manually.

**Comment by hartez** [comment]
This is as designed (and consistent with other Grid systems).
