### ISSUE TITLE
	Line	Suppression State Error	XA1018	Specified AndroidManifest file does not exist in Visual Studio 2019 16.11 

### ISSUE THREAD

**Issue by jssuthahar** [dotnet/maui#1122]
### Description
I have created new project MAUI project using Visual Studio 2019 16.11 preview and while build the application getting the following error 
	**Line	Suppression State Error	XA1018	Specified AndroidManifest file does not exist** 
### Steps to Reproduce

1. Create New Project using  VS MAUI template 
2. Right-click Solutions and build 

### Expected Behavior
Build Should work using VS
### Actual Behavior
Getting error - 	Line	Suppression State Error	XA1018	Specified AndroidManifest file does not exist in Visual Studio 2019 16.11 
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![error MAUi](https://user-images.githubusercontent.com/5663351/120074503-bfd83600-c0ba-11eb-9472-409951c57a17.PNG)

**Comment by jfversluis** [comment]
Seems to be related to #1211 also I don't think VS2019 is going to be supporting .NET MAUI. Closing this one for now, thanks!
