### ISSUE TITLE
[iOS] An SSL error when sending request to server with self-signed certificate

### ISSUE THREAD

**Issue by IgorKravchenko10** [dotnet/maui#11225]
### Description

Hi!
I don't know is this issue of maui or xamarin-macios, so tell me.
I have exception when trying to send request from iOS application to our ASP.NET server with self-signed certificate.
In my Xamarin.Forms application I didn't have any exceptions. It just worked out of the box.
There was [related issue](https://github.com/dotnet/maui/issues/8518) in maui project (also reported in [xamarin-android](https://github.com/xamarin/xamarin-android/issues/7149) with android application. Now it is fixed for Android with .net7. But we need to create iOS application too, otherwise our customers will be unhappy =)

`"An SSL error has occurred and a secure connection to the server cannot be made."`

### Steps to Reproduce

1. Create new application using .net6 or .net7
2. Make a request to server with self-signed certificate using HttpClient.
3. Ensure you have "An SSL error has occurred and a secure connection to the server cannot be made".

### Link to public reproduction project repository

https://github.com/IgorKravchenko10/ServiceTest

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Relevant log output

```shell
StackTrace:


   at System.Net.Http.NSUrlSessionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at ServiceTest.BasicHttpConnection.<Post>d__21`1[[System.String[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in C:\Users\Igor\source\repos\Maui-web-service-bug-master\ServiceTest\BasicHttpConnection.cs:line 88
   at ServiceTest.MainPage.OnCounterClicked(Object sender, EventArgs e) in C:\Users\Igor\source\repos\Maui-web-service-bug-master\ServiceTest\MainPage.xaml.cs:line 16
```
```
Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x1090c9400) s: DESKTOP-LK5ITUQ i: DESKTOP-LK5ITUQ>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://tcu.base2base.com.ua:9005/api/Values, NSErrorFailingURLStringKey=https://tcu.base2base.com.ua:9005/api/Values, NSUnderlyingError=0x280669230 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x2839fc3c0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x1090c9400) s: DESKTOP-LK5ITUQ i: DESKTOP-LK5ITUQ>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <8AD7DEC5-5282-410F-8A7E-3112A978FEBF>.<1>"
), _kCFStreamErrorCodeKey=-9802, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <8AD7DEC5-5282-410F-8A7E-3112A978FEBF>.<1>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x2839fc3c0>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.}
```
```

**Comment by PureWeen** [comment]
@jonathanpeppers thoughts?

**Comment by IgorKravchenko10** [comment]
@PureWeen I'm sorry. Have you added android tag to ios issue? =)

**Comment by jfversluis** [comment]
I think we can unsummon Jonathan and instead ask for @rolfbjarne

**Comment by rolfbjarne** [comment]
@simonrozsival does xamarin-macios need the same fix xamarin-android did (https://github.com/xamarin/xamarin-android/pull/7246)?

**Comment by simonrozsival** [comment]
@rolfbjarne I don't think so (there's a [test case for hostname mismatch](https://github.com/xamarin/xamarin-macios/pull/15117/files#diff-8e3ae4fee3c71771bc624c7064b570e38dc50fc0a26836cc3d642ec1318e5c77R552)). I'll double check tomorrow.

**Comment by IgorKravchenko10** [comment]
> @IgorKravchenko10 I think there are two issues in the code you linked:
> 
> * I can't see that you would set a `ServerCertificateCustomValidationCallback` to bypass certificate validation anywhere in the code. I think you need to modify your `OnHttpClientCreating()` method to include:
> 
> ```cs
> var handler = new HttpClientHandler
> {
>     ServerCertificateCustomValidationCallback =
>         HttpClientHandler.DangerousAcceptAnyServerCertificateValidator,
> };
> var httpClient = new HttpClient(handler);
> ```
> 
> * on iOS you need to modify your Info.plist to make connections to servers with invalid certificates, for example by adding this snippet:
> 
> ```
> <key>NSAppTransportSecurity</key>
> <dict>
>     <key>NSAllowsArbitraryLoads</key>
>     <true/>
> </dict>
> ```
> 
> See https://developer.apple.com/documentation/security/preventing_insecure_network_connections for more information.
> 
> Does this solve your problem?

Thank you. This works.
In my main project I used DangerousAcceptAnyServerCertificateValidator but didn't know I need to add those attributes in info.plist.
Now I can to continue my work =)
