### ISSUE TITLE
Selected Visual States no longer work correctly

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#11238]
### Description

https://github.com/dotnet/maui/pull/10352

Added the `PointerOver` VSM. 

The "problem" with how CV/Shell propagate the `Selected` state is that it's not resilient. `Selected` is just set from within CV/Shell but `VisualElement` has no idea that it was set so if anything tells `VisualElement` to re-evaluate the VSM then that state is lost. 

You can reproduce this issue by running the `selected` VSM gallery items inside our samples gallery. You'll notice after you select an item and then move the mouse away that it loses the `selected` VSM state because `PointerOver` is triggering a re-evaluation of the VSM since it's Over the element. 

Some thoughts
- Do we need to add some additional states for scenarios where a control has a `Selected` state? "PointerOverSelected", `PointerOverUnselected`
- Not sure the best approach here to address the regression. We could possibly have `ChangeVisualState` evaluate if there's a `PointerOver` state added and only then will it re-evaluate the Visual State. This still doesn't fix a scenario where a user wants both `PointerOver` and `Selected` but it at least covers if the user only has `Selected` defined. 
- Make VSM resilient so that it can revert back to `Selected` if it gets transitioned to `PointerOver` and `Selected` is still valid.

**Comment by taimo42** [comment]
I also face this issue and found so far no workaround to change the background color of a selected item.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 1.1. Not repro this issue.
