### ISSUE TITLE
.NET MAUI Blazor CSS Missing on Hot Reload

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#11242]
https://user-images.githubusercontent.com/14852843/200969269-0893e51e-f9a5-480e-9306-a39297834f11.mov

**Comment by TanayParikh** [comment]
.NET MAUI ASP.NET Core: 7.0.49
VS: Int Preview (Version 17.5.0 Preview 2.0 [33102.382.main])

**Comment by TanayParikh** [comment]
Flaky issue? I only saw it once, and now it's working normally. Closing this out, but if anyone runs into this, please let us know!

**Comment by Taiizor** [comment]
![image](https://user-images.githubusercontent.com/41683699/200969943-2df910af-78d9-4ec8-b9e0-730421761e6f.png)
![image](https://user-images.githubusercontent.com/41683699/200969994-85295819-bc3b-4c2a-89a2-41b4e90daac1.png)

**Comment by TanayParikh** [comment]
Cool, thanks @Taiizor. Just got the repro too. It happens on hot reload.

**Comment by TanayParikh** [comment]
https://user-images.githubusercontent.com/14852843/200970740-405a5a47-e70c-4258-b060-f7b483f5e77e.mov

cc/ @BillHiebert 

Note, this doesn't happen with `app.css`:

https://user-images.githubusercontent.com/14852843/200971046-aaf9cbcd-1e25-4ec3-9297-a25e62fa678e.mov

But the change for app.css just doesn't take effect at all. cc/ @mcumming

**Comment by TanayParikh** [comment]
@Taiizor what version of VS are you running? I believe it's fine in 17.4. 17.5 appears to have the regression.

**Comment by Taiizor** [comment]
> @Taiizor what version of VS are you running? I believe it's fine in 17.4. 17.5 appears to have the regression.

17.4.0

**Comment by TanayParikh** [comment]
> But Hot Reload for app.css doesn't work.

Are you essentially seeing this?

https://user-images.githubusercontent.com/14852843/200971046-aaf9cbcd-1e25-4ec3-9297-a25e62fa678e.mov

**Comment by Taiizor** [comment]
> > But Hot Reload for app.css doesn't work.
> 
> Are you essentially seeing this?
> 
>  Screen.Recording.2022-11-09.at.4.29.42.PM.mov

https://user-images.githubusercontent.com/41683699/200973989-2aa1685c-0b16-4b26-94bc-c9be8123e417.mp4

**Comment by TanayParikh** [comment]
Okay thanks, yes I'm seeing the same.

**Comment by TanayParikh** [comment]
For `MainLayout.razor.css` (aka scoped CSS) we aren't getting any content in the [`MetadataUpdateHandler`](https://github.com/dotnet/maui/blob/98c6a47a68c47bf744f2b05e46edcccd9a20ee8d/src/BlazorWebView/src/SharedSource/StaticContentHotReloadManager.cs#L40) (cc/ @BillHiebert):

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/14852843/201447618-8472fc94-464a-4b18-9f6d-e5f2f4158a1b.png">


For app.css we aren't getting any content in the [`MetadataUpdateHandler`](https://github.com/dotnet/maui/blob/98c6a47a68c47bf744f2b05e46edcccd9a20ee8d/src/BlazorWebView/src/SharedSource/StaticContentHotReloadManager.cs#L40) (cc/ @mcumming):

<img width="1466" alt="Screen Shot 2022-11-11 at 4 30 34 PM" src="https://user-images.githubusercontent.com/14852843/201447505-5029349a-20ed-4e7f-aaa3-9400ff1699bc.png">

**Comment by EmilyFeng97** [comment]
@TanayParikh This issue does not repro on 6.0/7.0 MAUI projects on the latest build of Dev17.6 Preview 1[main-33314.27]. .NET MAUI version are 7.0.58 and 6.0.550.

**Comment by TanayParikh** [comment]
I believe @mcumming  had a fix for this recently. @mcumming  should we close out this issue now?

**Comment by mcumming** [comment]
Yes, closing.
