### ISSUE TITLE
Can't run my MAUI program on an android emulator

### ISSUE THREAD

**Issue by Gwen02** [dotnet/maui#11249]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Hello,

I've been trying to run my MAUI app within a Android Emulator with VS 2022 in the basic MAUI code, but an error says that "the specified file can't be found" in my folder.
![image](https://user-images.githubusercontent.com/62254832/201053343-349c05da-308e-4ce5-886c-73c65d1cb895.png)

I installed the Android SDK, ect. But I can't launch my program properly on android, even though the program works fine on my windows machine.

Moreover I noticed that when I installed .Net, the package _Microsoft.Android.Sdk.Windows_ wasn't installed, as shows the screen below 

![image](https://user-images.githubusercontent.com/62254832/201053963-386d3f94-6de8-46bb-afb7-347005be4875.png)

This is the ouput shown by Xamarin : 
![image](https://user-images.githubusercontent.com/62254832/201054108-911f9290-2dfc-4ac7-b2b1-baa8b6435bf1.png)

I tried reinstalling .Net with all the packages and VS 2022 but nothing work, has something similar ever happened to one of you?

Thanks for your help !

**Comment by AmSmart** [comment]
This might be an issue with your SDK path settings. Check for your Android SDK installation folder and be sure the correct folder is set in your Visual Studio settings.
