### ISSUE TITLE
[Bug] NavigationPage doesn't work (shows blank screen)

### ISSUE THREAD

**Issue by naweed** [dotnet/maui#1124]
### Description

NavigationPage does not work for me. It shows me blank/empty page with just the purple status bar (which is the app color).

//If I do this in my App class, it shows me empty page with white background
return new Microsoft.Maui.Controls.Window(new NavigationPage(new MainPage()));

//However, this works perfectly fine and shows me the page properly
return new Microsoft.Maui.Controls.Window(new MainPage());

### Steps to Reproduce

1. Create a new MAUI App project in VS 2019 16.11.0 Preview-1
2. In the App.xaml.cs, change the CreateWindow method to return new NavigationPage(new MainPage))

### Expected Behavior

The app should launch and show the MainPage content.

### Actual Behavior

The app launches but only shows blank page.

### Basic Information

- Version with issue: 6.0.100-preview.4.*
- Last known good version: N/A
- IDE: Visual Studio 16.11.1 Preview-1
- Platform Target Frameworks: 
  - iOS
  - Android
- Affected Devices: Samsung S20+ Physical device

### Reproduction Link

Source code (for reference):
[MAUI_Weather.zip](https://github.com/dotnet/maui/files/6565810/MAUI_Weather.zip)

### Other Info

I started a new MAUI app on VS 2019 16.11.0 Preview-1 (using Project->New). I already ran MAUI-Check to ensure that all pre-requisites are in place. I am running this on a Win 10 Pro VM, and tested it against physical Android Device (Samsung S20+)

**Comment by realZhangChi** [comment]
Same problem on WinUI

**Comment by Joren-Thijs** [comment]
Same problem here

**Comment by PureWeen** [comment]
There's a missing call to some additional handlers in the templates

`using Microsoft.Maui.Controls.Hosting;`

If you add `UseMauiControlHandlers` that will cause the Navigation Page to show up

**Comment by naweed** [comment]
Thanks @PureWeen. This has solved my issue.

**Comment by jfversluis** [comment]
Seems this was reopened by accident :)
