### ISSUE TITLE
[Enhancement] Roadmap for media and communication features

### ISSUE THREAD

**Issue by MhAllan** [dotnet/maui#1125]
Roadmap on these topics if you please:

- In app purchase
- Push notifications
- Live video streaming
- Video streaming with VAST
- Azure Communication Services Integration (Video Call, Ringing when app off, ... etc)

**Comment by Lanayx** [comment]
+1, especially for push notifications

**Comment by jfversluis** [comment]
While I definitely would like to see some of these integrated better somehow, this as an issue is hardly actionable. It described a couple of potentially very big and impactful features. If we want to consider any of these they need to be broken up into an issue per feature with a great number of detail on what the API might look like, what the use-case is, etc. all the detail you can think of.

I will close this for now, if there is things still on this list you'd like to see, please help us out by opening a feature request or maybe a discussion first to talk through some details.

Thanks!
