### ISSUE TITLE
Publish Maui app as exe not work on window 10 - continue

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#11254]
### Description

Description
Publish Maui app as exe is not working , while it works on server 2019 with some known issues(fonts...).

### Steps to Reproduce

1. Install window 10 on new virtual computer.
2. Creat a new Maui app.
3. Publish as exe using this command:
`dotnet publish -f net6.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -p:SelfContained=true -p:WindowsAppSDKSelfContained=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d"`
the exe created but when I run it nothing happen.
4. I installed the first two files.
I installed the app according to  https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps
![image](https://user-images.githubusercontent.com/1079689/201076210-8b4ac554-a300-4046-9cde-f3ce97dfc093.png)
How do I installed the last tree files ?
Can you please help even if not official ? I need  it for our customer not as msix

### Link to public reproduction project repository

....

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by LanceMcCarthy** [comment]
I recommend opening a discussion on the Windows  or WinUI Q&A. This is ultimately not related to .NET MAUI and is most certainly not a .NET MAUI bug.

It is a consequence of choosing to build an unpackaged WinUI3 app. You need to ensure the target environment has the necessary runtime. You can find the information in the article you've already shared https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps#chain-the-windows-app-sdk-installer-to-your-apps-setup

**Comment by LanceMcCarthy** [comment]
Also, I recommend trying the tutorial here => https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment?tabs=csharp

**Comment by mattleibow** [comment]
I am not sure the vsix are things you should install because they are VS extensions.

Can you try without the `-p:SelfContained=true` as I am not sure the Windows App SDK supports the single exe format. You still need the `-p:WindowsPackageType=None`

In addition to that, if you check the Event Viewer, can you see any errors appear when it tries to run? I wonder if there is something useful in there.

**Comment by danies8** [comment]
I tried to install the WindowsAppRuntimeInstall.exe I got this error:
![image](https://user-images.githubusercontent.com/1079689/201899567-f4a3c00b-007e-470a-8615-f5b36e99c94c.png)

**Comment by danies8** [comment]
I also removed -p:SelfContained=true  from the MAU installation and it works when you have VS 2022 installed.
Without VS 2022 is not works!!

**Comment by danies8** [comment]
> LanceMcCarthy

I read this tutorial and it seems that Installing the Windows App SDK NuGet package in my project where you have VS installed  
And in the target machine I do not have VS installed.
So how to installed Windows App SDK ?

**Comment by danies8** [comment]
I succedded running windowsdesktop-runtime-6.0.7-win-x64.exe
and it run the maui .exe
