### ISSUE TITLE
Android webview is only loading "about:blank" when using custom WebviewClient with .Net 7.0

### ISSUE THREAD

**Issue by Mackly** [dotnet/maui#11264]
### Description

Creating a custom WebviewClient and modifying the mapping for the webview to use it prevents the webview from loading any web page other than "about:blank".

Example :
![image](https://user-images.githubusercontent.com/9982915/200972687-04acbd7b-48c9-47bf-aeee-9ac53fbfb94b.png)

### Steps to Reproduce

1. Create a new MAUI app
2. Add a WebView
3. Set the Webview source
4. Create a custom WebviewClient
5. Modify the mapping to assign an instance of your WebviewClient to your webview
6. Start the app
7. See the blank page

### Link to public reproduction project repository

https://github.com/Mackly/MauiApp1.git

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9 and up

### Did you find any workaround?

Not yet, still searching, but I'm starting to run out of ideas. Hence, this bug report.

**Comment by PureWeen** [comment]
@Mackly yea we have some logic in the handler that should probably be moved into MauiWebViewClient :-/ 

If you copy the code [here](https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/WebView/WebViewHandler.Android.cs#L24-L36) does it fix the problem for you?

https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/WebView/WebViewHandler.Android.cs#L24-L36

**Comment by Mackly** [comment]
Hi @PureWeen. Thanks for the suggestion. Although I'm not sure where I should add [this piece of code](https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/WebView/WebViewHandler.Android.cs#L24-L36). 

Is it possible that the problem is related to [this part of the code](https://github.com/dotnet/maui/blob/496dab25ed729dc9acb5a25c7dd3392083d3f5ea/src/Core/src/Handlers/WebView/WebViewHandler.Android.cs#L74-L78) as it might not be called because I've modified the mapping. Thus no page can be loaded because of [the check here](https://github.com/dotnet/maui/blob/496dab25ed729dc9acb5a25c7dd3392083d3f5ea/src/Core/src/Handlers/WebView/WebViewHandler.Android.cs#L141-L142) and since_webViewClient is null ?

**Comment by Mackly** [comment]
I have found a workaround. It seems the problem does come from what I am mentioning in my last comment (unless I am missing something). The workaround is to simply add [that line](https://github.com/Mackly/MauiApp1/blob/32dd0e9eea22c09c2719d62e0a672c59d55355b2/MauiApp1/MainPage.xaml.cs#L21) before setting the custom web client. Thus initializing the handler with a webclient and making sure _webViewClient value is not null. It is not the best solution as it requires creating an unused "dummy" webclient but it works for now.

**Comment by DDHSchmidt** [comment]
Another workaround is to not inherit from Microsoft.Maui.Handlers.WebViewHandler, but to inherit from its base class: ViewHandler<IWebView, Android.Webkit.WebView>
That was our only workaround since the ModifyMapping() workaround didn't quite work out for us.

I also would like more insight into [the commit](https://github.com/dotnet/maui/commit/c6250a20d73e1992b4a02e6f3c26a1e6cbcbe988#diff-59bbbffb1e68bc56d1c81c749169372528af5d4166ba6c1c0c91e4c51a0d6220) that allegedly (?) introduced this bug.
Why was a null check to "_webViewClient" added if the private field is never set in the first place? How can it ever *not* be null?

I get that WebView interaction seems to be low priority for Microsoft, but this workaround has been a thorn in our sides for several months now :/

**Comment by jjxtra** [comment]
WebView Source property is non functional on Android. It times out after a few minutes regardless of the url. This worked a few months ago. Permissions are correct.

Is this a bug or by design?

**Comment by jjxtra** [comment]
> I have found a workaround. It seems the problem does come from what I am mentioning in my last comment (unless I am missing something). The workaround is to simply add [that line](https://github.com/Mackly/MauiApp1/blob/32dd0e9eea22c09c2719d62e0a672c59d55355b2/MauiApp1/MainPage.xaml.cs#L21) before setting the custom web client. Thus initializing the handler with a webclient and making sure _webViewClient value is not null. It is not the best solution as it requires creating an unused "dummy" webclient but it works for now.

Adding your code I get lots of namespace and references not found. Is there another step?

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on android platform with above project.
https://github.com/Mackly/MauiApp1.git
![image](https://github.com/dotnet/maui/assets/82450723/fc938e63-7ec0-410e-9284-5c1b062d6aa6)
