### ISSUE TITLE
Shell.Title and Window.Title currently doesn't propagate to the catalyst window title

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#11263]
### Description

The title on the window and shell component don't currently propagate to the `UIScene` title property.

Here's an example of a workaround 
https://github.com/PureWeen/dotnetConfDemo2022/blob/main/dotnetConfDemo/Windows/ScopedWindow.cs#L35

**Comment by mattleibow** [comment]
This is most likely related to https://github.com/dotnet/maui/issues/12646

**Comment by mattleibow** [comment]
Seems the Title is not bubbled up, but thisis also partially by design as some apps do not wish the APP title to match the current page.

If you do, you could maybe put something like this in your shell code-behind (AppShell.xaml.cs):

```cs
protected override void OnPropertyChanged([CallerMemberName] string propertyName = null)
{
    base.OnPropertyChanged(propertyName);

    if (propertyName == WindowProperty.PropertyName)
        Window?.SetBinding(Window.TitleProperty, new Binding("CurrentItem.Title", source: this) { StringFormat = ".NET MAUI {0}" });
}
```

If you want a fixed title for the app, then this is also possible if you put this in your app code-behind (App.xaml.cs):

```cs
protected override Window CreateWindow(IActivationState activationState)
{
    var window = base.CreateWindow(activationState);
    window.Title = ".NET MAUI";
    return window;
}
```

**Comment by mattleibow** [comment]
@PureWeen  is this still a thing? I feel like Window.Title now works and I am not sure if Shell.Title going to Window.Title is 100% desired as most apps don't flip title based on the current page... But maybe I am wrong. I have a workaround that may be a feature?

**Comment by PureWeen** [comment]
> @PureWeen is this still a thing? I feel like Window.Title now works and I am not sure if Shell.Title going to Window.Title is 100% desired as most apps don't flip title based on the current page... But maybe I am wrong. I have a workaround that may be a feature?

You only have one `Shell` for your window so the `Shell` and the window are synonymous.  The `Title` for the Page itself will be set on the `ShellContent` or the `Page` itself.

**Comment by PureWeen** [comment]
> Seems the Title is not bubbled up, but thisis also partially by design as some apps do not wish the APP title to match the current page.

Yes, it is?  Maybe I'm not following you here though but the `Title` is definitely bubbled up.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/5375137/212780026-ff179127-d5e6-4ead-82c1-73bebb6a81fa.png">

Here's the watching of the property change

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/HandlerImpl/Window/Window.Impl.cs#L635-L639


Here's how it's exposed via the interface
https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/HandlerImpl/Window/Window.Impl.cs#L107

**Comment by PureWeen** [comment]
> most apps don't flip title based on the current page...

They do for accessibility reasons. Ideally your window title will append/include the context of where you are in an app, that way if you have multiple windows, or you have multiple instances of an app, the reader will give your window context.
