### ISSUE TITLE
will MAUI support linux arm 64

### ISSUE THREAD

**Issue by selvam920** [dotnet/maui#1126]
will MAUI support linux arm 64 bit system?

**Comment by lytico** [comment]
try, if it works! i don't have an arm machine, so i can't
how to:
checkout https://github.com/jsuarezruiz/maui-linux/tree/main-linux
run Controls.Sample.Gtk

**Comment by tracker1** [comment]
@lytico Any word from MS if the GTK work will make it's way back into this repo?

**Comment by lytico** [comment]
i hope so. but as MS had Gtk-support in xamarins repo, i think it will be accepted if it works somehow, and isn't too much work to maintain.

**Comment by jsuarezruiz** [comment]
As @lytico mentioned, there will be no official support at the launch in Q2 2022. Which is not to say that it will not be included in the future. At the moment, there is a project at the community level for this https://github.com/jsuarezruiz/maui-linux/tree/main-linux

**Comment by osnipezzini** [comment]
> As @lytico mentioned, there will be no official support at the launch in Q2 2022. Which is not to say that it will not be included in the future. At the moment, there is a project at the community level for this https://github.com/jsuarezruiz/maui-linux/tree/main-linux

Your project is very interesting, but the problem is that it hasn't been updated for 3 months, and Microsoft doesn't position itself on official support. If I'm going to use a community repository I prefer to stick with AvaloniaUI or Uno which are already stable and fully cross-platform

**Comment by lytico** [comment]
> it hasn't been updated for 3 months

sorry for that. my engagement in the project is pure private, or, lets say, of research interest, and i don't get any funds or income out of it.

from time to time i have to take care of my income, and, unfortunately, my current "bread and butter" project targets asp.net  - blazor. so i won't have time to care about maui-gtk until june 2022.
