### ISSUE TITLE
CollectionView virtualization does not work when using a DataTemplateSelector

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#11272]
### Description

CollectionView virtualization does not work when using a DataTemplateSelector.
Both on android and ios.
Both on xamarin-forms and dotnet-maui.

I think this is a serious performance issue.
I've already reported this issue [here](https://github.com/xamarin/Xamarin.Forms/issues/13045#issuecomment-1254779257) with full details.
Could anybody help ?

### Steps to Reproduce

1. Run app from the repro project (either xamarin forms or maui, both for ios and android)
2. Click on the Add button
3. Scroll down/up a bit, and observe the increase of counters.
4. Compare the performance of different collection types on each tab.

### Link to public reproduction project repository

...

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

**Comment by tranb3r** [comment]
Could someone please investigate ?
cc @jonathanpeppers : this bug is quite a serious performance issue, I'm sure it's worth fixing it if you have the time to work on it.
Thanks.

**Comment by Vroomer** [comment]
@Redth Can you please let us know when we can expect the fix? You made PR 4 months ago and to this day it hasn't been merged without any further information. Selector is essential for any complex CollectionView and there is no workaround without massive performance hit. Combined with https://github.com/dotnet/maui/issues/12988 there is 7 unique likes so it seems to be among more important issues affecting a lot of developers. It's blocking us and it's been very frustrating to wait this long. Fix to this issue would be really appreciated.
