### ISSUE TITLE
ListView in MacCatalyst is slow and render incorrectly when scroll back / up

### ISSUE THREAD

**Issue by ooikengsiang** [dotnet/maui#11287]
### Description

ListView in MacCatalyst scrolling is laggy even it has fixed item height.
Even worse is, when scroll down then scroll up, some item no longer render or bind at all. They become blank. See the screenshot below.
Tested with latest .NET 7.0.100.
<img width="1041" alt="Screenshot 2022-11-12 at 12 02 01 AM" src="https://user-images.githubusercontent.com/19687809/201385304-9f46b438-1533-498a-a11a-914cd49e155f.png">

### Steps to Reproduce

1. Open the project in the given repository on MacOS.
2. You should see the ListView is populated with items.
3. Scroll down, down and down. Notice all item in ListView should render correctly although they might be slow / lag when scrolling.
4. Then scroll up, up and up. Notice some item start disappearing. Item height is still there but the content is empty.

### Link to public reproduction project repository

https://github.com/ooikengsiang/ListViewProblem

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacCatalyst, MacOS Venture 13.0.1

### Did you find any workaround?

No.

**Comment by jsuarezruiz** [comment]
Similar or related with https://github.com/dotnet/maui/issues/11598

**Comment by ooikengsiang** [comment]
2 months past, no workaround. Any update?

**Comment by alobimday** [comment]
Any update?

**Comment by ooikengsiang** [comment]
> Any update?

Nope. I try my best to get their MAUI team attention to this, so far no update.
I know that they have many bugs to fix (personally I file quite a number of them as well), but this feel like a show stopper which affect iOS and MacOS. Can't ship app with this bug :(

**Comment by DesmondMilez** [comment]
Hi guys, any workaround? I had problem with dissapearing rows on debug, but now I made a release package and the rows are all blank! I have two list views, in the first one, have TextCell and only the name is visible and in the second one is ViewCell and is blank.

Image:
 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/21020710/221221415-44a6092b-b752-4e24-a21b-c445bcaad632.png)

**Comment by muffadal53** [comment]
@jsuarezruiz and @jfversluis : Any update on when this issue will be fixed / any workaround for this as this is a blocker for iOS?

**Comment by ooikengsiang** [comment]
So far I didn't found any workaround yet. I have proposed a temporary fix, still waiting for the green light on the code review.

**Comment by muffadal53** [comment]
Thanks @ooikengsiang for the update. In my opinion this must be high priority fix as part of Microsoft MAUI framework team in order to help enterprise apps / developers which are migrating from Xamarin Forms to MAUI else it is difficult to release app on iOS with this kind of basic issue in ListViewcontrol. And this brings the point whether MAUI is mature enough to migrate from Xamarin forms.

Will await above temporary fix as part of .Net 7 service pack release.

Thanks.

**Comment by planerde** [comment]
I had a similar issue with ListView cells which were not re-rendered after some scrolling, but as a work-a-round I use `CachingStrategy="RecycleElement"` on the ListView. For me this fixes the issue (and should give a little performance boost, because my ListView cells are quite simple)

**Comment by muffadal53** [comment]
> CachingStrategy="RecycleElement" doesn't work on my repo. Still have the same problem, Actually I try all the CachingStrategy, none solve the problem.

@jsuarezruiz, @jfversluis, @ooikengsiang : Can you please tell me what is the workaround for this issue with .Net 7 if "CachingStrategy="RecycleElement"" doesn't work and the actual fix will be available in .Net 8 as seen in the milestone which still has time to release for GA around November 2023 from what I know?

Awaiting feedback.

Thanks.

**Comment by ooikengsiang** [comment]
> > CachingStrategy="RecycleElement" doesn't work on my repo. Still have the same problem, Actually I try all the CachingStrategy, none solve the problem.
> 
> @jsuarezruiz, @jfversluis, @ooikengsiang : Can you please tell me what is the workaround for this issue with .Net 7 if "CachingStrategy="RecycleElement"" doesn't work and the actual fix will be available in .Net 8 as seen in the milestone which still has time to release for GA around November 2023 from what I know?
> 
> Awaiting feedback.
> 
> Thanks.

There are no workaround actually, try use CollectionView instead for the mean while if possible.

**Comment by muffadal53** [comment]
> > > CachingStrategy="RecycleElement" doesn't work on my repo. Still have the same problem, Actually I try all the CachingStrategy, none solve the problem.
> > 
> > 
> > @jsuarezruiz, @jfversluis, @ooikengsiang : Can you please tell me what is the workaround for this issue with .Net 7 if "CachingStrategy="RecycleElement"" doesn't work and the actual fix will be available in .Net 8 as seen in the milestone which still has time to release for GA around November 2023 from what I know?
> > Awaiting feedback.
> > Thanks.
> 
> There are no workaround actually, try use CollectionView instead for the mean while if possible.

@ooikengsiang : Ok thanks for your suggestion will check if that option suits our needs. But if **CachingStrategy="RecycleElement"** workaround works then, we can go ahead with this till actual fix in framework is available. Is the understanding right?

**Comment by ooikengsiang** [comment]
The workaround other propose doesn't work for me, you can try and see.

**Comment by tibuprophen** [comment]
Won't this be fixed in .NET 7? ListView is a core component and .NET 7 support is not over yet. It's still 4 months until we see.
