### ISSUE TITLE
Setting SetSoftInputMode to AdjustResize on Android breaks modal layouts (and probably more)

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#11286]
### Description

This issue is an extension of the following [issue](https://github.com/dotnet/maui/issues/10978). This is happening because `MAUI` doesn't re-evaluate the layout size of the modal page when the keyboard is dismissed. In `Xamarin.Forms` the layout would re-evaluate via the `PageRenderer` when the modal was closed. 

You can recreate this issue by taking the sample attached to the above issue and then setting the `SoftInputMode` to `AdjustResize`

**Comment by cerkzil** [comment]
AdjustPan has the same issue just less noticeable at first glance since you have to have a view with entry at the bottom to see the effect. So currently there is no workarounds for this issue, is this still being looked into?

**Comment by PureWeen** [comment]
@cerkzil `AdjustPan` currently isn't being applied correctly https://github.com/dotnet/maui/pull/11356
