### ISSUE TITLE
Alt+Tab Causes Search bar via CTRL+F in top of the screen

### ISSUE THREAD

**Issue by sunnamed434** [dotnet/maui#11285]
### Description

![image](https://user-images.githubusercontent.com/65300126/201376127-4598733f-3d8e-4265-bf91-a95d362a6108.png)
![image](https://user-images.githubusercontent.com/65300126/201376219-d16915b4-2b3c-4770-b65e-771c520b7a68.png)

### Steps to Reproduce

1. CTRL+F in launched Maui app
2. Alt+Tab/CTRL+Alt+Tab
3. Now search bar is in top of the screen

### Link to public reproduction project repository

https://github.com/sunnamed434/BitMono

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by jinxinjuan** [comment]
@sunnamed434 This issue not reproduced on MAUI Blazor Template project with .NET8, could have a try with .NET8 to see if it works fine? Thanks.

**Comment by sunnamed434** [comment]
The problem is solved, closing it
