### ISSUE TITLE
Unable to create MAUI project

### ISSUE THREAD

**Issue by ROnderstal** [dotnet/maui#11284]
Unable to Select MAUI in project types as described on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
![image](https://user-images.githubusercontent.com/24256087/201372161-bb99d6bb-eeaf-454e-883b-209491c9c3d5.png)
however do have it installed as told to in the step https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
![image](https://user-images.githubusercontent.com/24256087/201372321-222f7877-c090-45d1-a2cf-ffb34d32b0ec.png)

using installer version 3.4.2244.14676 to install Visual Studio Community 2022 (17.4.0) newly downloaded from the website
Installing on Windows 11 Pro Insider Preview (Build 25236.rs_prerelease.221028-1618)

**Comment by sunnamed434** [comment]
Try to press `repair` button via visual studio installer or restart pc
![image](https://user-images.githubusercontent.com/65300126/201380492-01e8ad09-e91c-46ad-8c54-cc604791bf60.png)
