### ISSUE TITLE
[Bug]  AndroidManifest file does not exist

### ISSUE THREAD

**Issue by gviddy** [dotnet/maui#1129]
### Description
Cannot compile. Does not find AndroidManifest.xml

### Steps to Reproduce

1.  Install latest VS 2019 Preview (Version 16.11.0 Preview 1.0)
2.  Run maui-check (everything is fine)
3.  Create a new solution using VS 2019 Preview
4.  Compile

### Expected Behavior
No compile errors

### Actual Behavior
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\11.0.200-preview.4.245\tools\Xamarin.Android.Common.targets(503,3): error XA1018: Specified AndroidManifest file does not exist: D:\Projects\Maui\CryptoApp\CryptoApp\App\AndroidManifest.xml.

From the above error line it appears it needs to be App\Android as the that where the manifest file actually **does** exist.

How can I fix this? Come on guys, I know it is a preview but this is exactly the problem that Xamarin has always had. It just never works out of the box. Unlike Flutter.

**Comment by gviddy** [comment]
Apologies. You can close this. I completely forgot about the good ol 'restart visual studio'. I guess some things will never change. :)

**Comment by lbcsy** [comment]
It did not go away for me after ‘restart visual studio'. Additionally, it has error of not able to find all MAUI package from Nuget too:
Error	NU1101	Unable to find package Microsoft.Maui. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

**Comment by mohaaron** [comment]
I get a lot of different compile errors if I Rebuild the solution. I have only been able to make it work by setting the "WinUI3 (Package)" project as the start project. I can then run the application and it works. Compiling the solution has not worked for me.

**Comment by git-net** [comment]
i copy AndroidManifest.xml from android fold

**Comment by gviddy** [comment]
> It did not go away for me after ‘restart visual studio'. Additionally, it has error of not able to find all MAUI package from Nuget too:
> Error NU1101 Unable to find package Microsoft.Maui. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

Ah yes I did get all these errors too. Sorry but I do not have a solution for that as again they magically just went away. The build process seems to make no sense to me.

Fingers crossed that in the future we can select create solution and it 'just works'.

**Comment by lbcsy** [comment]
> Edit: If on Android, do make sure you run the following:
> dotnet new nugetconfig
> dotnet nuget add source -n maui-preview https://aka.ms/maui-preview/index.json

I actually did that when I tried with VS 16.10 and it worked, but did not know why, now it makes sense.
I still cannot get ios or Android to run, it complained something like don't know how to execute xxx profile (don't with my laptop at the moment)

**Comment by alexchukanov** [comment]
Shame on Microsoft, got the same errors!

**Comment by IbrahimHabibeh** [comment]
A restart of visual studio worked for me. Once I restarted it and ran it again it went ahead and downloaded everything that was missing. Just note that I think you have to connect an android device to your machine in order to have it run properly. Unfortunately, once the console comes up I am hit with another error so I'm gonna have to solve this first.

**Comment by Redth** [comment]
If you're using the latest preview, try a `dotnet new maui` to see the most recent template changes (the manifest is expected to be under `Platforms\Android\AndroidManifest.xml` now in a Single Project)
