### ISSUE TITLE
Entry crashing on iOS

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#11298]
### Description

Entry crashes on iOS in various instances

On a File > New .NET MAUI app, using the keyboard arrow keys from an Entry crashes the app 

On the latest net7.0 branch of the .NET MAUI repo, clicking into an Entry crashes the app 
(This is NOT happening with Editor)

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/21988533/201437982-1308e740-fae5-4603-913b-1c110b124e47.png">

<details>
   <summary>Exception stack trace</summary>
   
   
ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[<_UIObscurableTextContentStorage: 0x600002c83ed0> offsetFromLocation:toLocation:] received invalid locations 0 (null)
Native stack trace:
	0   CoreFoundation                      0x00007ff8004278cb __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80004dba3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8004277a9 -[NSException initWithCoder:] + 0
	3   UIFoundation                        0x00007ff80461af95 -[NSTextContentStorage offsetFromLocation:toLocation:] + 287
	4   UIKitCore                           0x0000000122bde8ec -[_UITextKit2LayoutController offsetFromPosition:toPosition:] + 234
	5   UIKitCore                           0x000000012361a070 -[UITextInputController offsetFromPosition:toPosition:] + 85
	6   UIKitCore                           0x00000001235e9180 -[UIFieldEditor offsetFromPosition:toPosition:] + 93
	7   UIKitCore                           0x0000000123604c14 -[UITextField offsetFromPosition:toPosition:] + 93
	8   libxamarin-dotnet-debug.dylib       0x000000010f58a49c xamarin_dyn_objc_msgSendSuper + 220
	9   ???                                 0x000000010f0b9ca7 0x0 + 4547386535
	10  libmonosgen-2.0.dylib               0x000000010fd5146a ves_pinvoke_method + 474
	11  libmonosgen-2.0.dylib               0x000000010fd442c9 interp_exec_method + 3737
	12  libmonosgen-2.0.dylib               0x000000010fd41a73 interp_runtime_invoke + 259
	13  libmonosgen-2.0.dylib               0x000000010fb66938 mono_runtime_invoke_checked + 136
	14  libmonosgen-2.0.dylib               0x000000010fb6a5ae mono_runtime_invoke + 142
	15  libxamarin-dotnet-debug.dylib       0x000000010f5816b0 xamarin_invoke_trampoline + 6320
	16  libxamarin-dotnet-debug.dylib       0x000000010f589019 xamarin_arch_trampoline + 105
	17  libxamarin-dotnet-debug.dylib       0x000000010f58a1fe xamarin_x86_64_common_trampoline + 118
	18  UIKitCore                           0x00000001235b2d7d -[UITextSelection commit] + 243
	19  UIKitCore                           0x00000001235b74d6 -[UITextSelectionView deactivateAndCollapseSelection:] + 142
	20  UIKitCore                           0x00000001235b86af -[UITextSelectionView textSelectionViewActivated:] + 350
	21  CoreFoundation                      0x00007ff80035869b __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
	22  CoreFoundation                      0x00007ff8003585d1 ___CFXRegistrationPost_block_invoke + 86
	23  CoreFoundation                      0x00007ff800357bb0 _CFXRegistrationPost + 541
	24  CoreFoundation                      0x00007ff8003574b9 _CFXNotificationPost + 822
	25  Foundation                          0x00007ff800c08501 -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
	26  UIKitCore                           0x00000001235b73c3 -[UITextSelectionView activate] + 224
	27  UIKitCore                           0x0000000123606813 -[UITextField _updateSelectionGestures] + 553
	28  UIKitCore                           0x00000001235f1ba4 -[UITextField _becomeFirstResponder] + 249
	29  UIKitCore                           0x0000000123266a21 -[UIResponder becomeFirstResponder] + 777
	30  UIKitCore                           0x00000001238451f7 -[UIView(Hierarchy) becomeFirstResponder] + 121
	31  UIKitCore                           0x00000001235f0713 -[UITextField becomeFirstResponder] + 180
	32  UIKitCore                           0x00000001235a1e3c -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) setFirstResponderIfNecessaryActivatingSelection:] + 203
	33  UIKitCore                           0x00000001235772b4 -[UITextSelectionInteraction _checkForRepeatedTap:gestureLocationOut:] + 278
	34  UIKitCore                           0x0000000123578252 -[UITextSelectionInteraction _handleMultiTapGesture:] + 1123
	35  UIKitCore                           0x0000000123233d05 -[UIApplication sendAction:to:from:forEvent:] + 95
	36  UIKitCore                           0x0000000122b64172 -[UITextMultiTapRecognizer onStateUpdate:] + 169
	37  UIKitCore                           0x0000000122c353ce -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 72
	38  UIKitCore                           0x0000000122c3f050 _UIGestureRecognizerSendTargetActions + 100
	39  UIKitCore                           0x0000000122c3bc68 _UIGestureRecognizerSendActions + 312
	40  UIKitCore                           0x0000000122c3b01b -[UIGestureRecognizer _updateGestureForActiveEvents] + 629
	41  UIKitCore                           0x0000000122c29bc8 _UIGestureEnvironmentUpdate + 3840
	42  UIKitCore                           0x0000000122c2886e -[UIGestureEnvironment _updateForEvent:window:] + 844
	43  UIKitCore                           0x000000012327aedb -[UIWindow sendEvent:] + 5282
	44  UIKitCore                           0x000000012324e7f2 -[UIApplication sendEvent:] + 898
	45  UIKitCore                           0x00000001232f5e61 __dispatchPreprocessedEventFromEventQueue + 9381
	46  UIKitCore                           0x00000001232f8569 __processEventQueue + 8334
	47  UIKitCore                           0x00000001232ee8a1 __eventFetcherSourceCallback + 272
	48  CoreFoundation                      0x00007ff800387035 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	49  CoreFoundation                      0x00007ff800386f74 __CFRunLoopDoSource0 + 157
	50  CoreFoundation                      0x00007ff800386771 __CFRunLoopDoSources0 + 212
	51  CoreFoundation                      0x00007ff800380e73 __CFRunLoopRun + 927
	52  CoreFoundation                      0x00007ff8003806f7 CFRunLoopRunSpecific + 560
	53  GraphicsServices                    0x00007ff809c5c28a GSEventRunModal + 139
	54  UIKitCore                           0x000000012322d62b -[UIApplication _run] + 994
	55  UIKitCore                           0x0000000123232547 UIApplicationMain + 123
	56  libxamarin-dotnet-debug.dylib       0x000000010f544a5a xamarin_UIApplicationMain + 58
	57  libmonosgen-2.0.dylib               0x000000010fd52639 do_icall + 345
	58  libmonosgen-2.0.dylib               0x000000010fd51143 do_icall_wrapper + 291
	59  libmonosgen-2.0.dylib               0x000000010fd441a0 interp_exec_method + 3440
	60  libmonosgen-2.0.dylib               0x000000010fd41a73 interp_runtime_invoke + 259
	61  libmonosgen-2.0.dylib               0x000000010fb66938 mono_runtime_invoke_checked + 136
	62  libmonosgen-2.0.dylib               0x000000010fb6e94c do_exec_main_checked + 92
	63  libmonosgen-2.0.dylib               0x000000010fc9daa2 mono_jit_exec + 354
	64  libxamarin-dotnet-debug.dylib       0x000000010f588e77 xamarin_main + 1927
	65  Maui.Controls.Sample                0x000000010eb47324 main + 68
	66  dyld                                0x000000010f2222bf start_sim + 10
	67  ???                                 0x000000011bff4310 0x0 + 4764680976

  at at UIKit.UITextField.GetOffsetFromPosition(UITextPosition fromPosition, UITextPosition toPosition)
  at Microsoft.Maui.Platform.TextInputExtensions.GetCursorPosition(IUITextInput platformView, Int32 cursorOffset) in /Users/rachelkang/maui/src/Core/src/Platform/iOS/TextInputExtensions.cs:13
  at Microsoft.Maui.Handlers.EntryHandler.OnSelectionChanged(Object sender, EventArgs e) in /Users/rachelkang/maui/src/Core/src/Handlers/Entry/EntryHandler.iOS.cs:164
  at Microsoft.Maui.Platform.MauiTextField.set_SelectedTextRange(UITextRange value) in /Users/rachelkang/maui/src/Core/src/Platform/iOS/MauiTextField.cs:58
  at at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
  at at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
  at Maui.Controls.Sample.Platform.Application.Main(String[] args) in /Users/rachelkang/maui/src/Controls/samples/Controls.Sample/Platforms/iOS/Main.cs:8

</details>

### Steps to Reproduce

1. Run .NET MAUI repo control gallery from the latest net7.0 branch
2. Navigate to Entry page
3. Click on entry as you would to type in it

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

**Comment by blimoon** [comment]
is this issue fixed? I'm waiting for this.

**Comment by blimoon** [comment]
is this issue fixed? I'm waiting for this.

**Comment by jeya-kasipandi** [comment]
Hi @jsuarezruiz 
Is this issue fixed and  when it will be included ?
