### ISSUE TITLE
Project naming issue

### ISSUE THREAD

**Issue by handicraftsman** [dotnet/maui#113]
I don't know if you already noticed this, but there is already a GUI toolkit called `maui` - it is based over Qt5 and KDE's Kirigami and can be found at https://mauikit.org/

**Comment by shanranm** [comment]
duplicate of #34, #35

**Comment by Happypig375** [comment]
Stop reposting the same content as #34

**Comment by Happypig375** [comment]
We already have
dotnet/maui#34
dotnet/maui#35
dotnet/maui#51
dotnet/maui#58
dotnet/maui#67
dotnet/maui#74
dotnet/maui#87

**Comment by jsuarezruiz** [comment]
Duplicate of #34.
