### ISSUE TITLE
.NET MAUI Windows content escapes window into toolbar

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#11300]
Not sure if this is a "bug" in the Sample project, or if this is something that should be prohibited at a framework level:

https://user-images.githubusercontent.com/14852843/201446787-bfb7f1f2-eaa9-43e6-9cf9-fd27e2897091.mov

**Comment by TanayParikh** [comment]
Version 17.5.0 Preview 2.0 [33109.374.main] ++ .NET MAUI main with `Maui.Controls.Sample`

**Comment by PureWeen** [comment]
Duplicate of #12063
