### ISSUE TITLE
TextArea is not working (Maui Blazor)

### ISSUE THREAD

**Issue by sunnamed434** [dotnet/maui#11308]
### Description

Sometimes when I`m opening page with textarea and trying to input something there its working fine and sometimes not, after executing this [method](https://github.com/sunnamed434/BitMono/blob/main/BitMono/BitMono.GUI/Pages/Obfuscation/Protect.razor.cs#L42)

Custom [Highlight.razor](https://github.com/sunnamed434/BitMono/blob/main/BitMono/BitMono.GUI/Shared/Inputs/Highlight.razor), usage of [Highlight.razor](https://github.com/sunnamed434/BitMono/blob/main/BitMono/BitMono.GUI/Pages/Obfuscation/Protect.razor#L28)

### Steps to Reproduce

1. Open page [Protect.razor](https://github.com/sunnamed434/BitMono/blob/main/BitMono/BitMono.GUI/Pages/Obfuscation/Protect.razor)
2. Click [obfuscate button](https://github.com/sunnamed434/BitMono/blob/main/BitMono/BitMono.GUI/Pages/Obfuscation/Protect.razor#L18)
3. By default listening logs by Serilog via some sinks and outputting this text into this textarea (in this case in Custom [Highlight.razor](https://github.com/sunnamed434/BitMono/blob/main/BitMono/BitMono.GUI/Shared/Inputs/Highlight.razor))
4. Error that says (Microsoft.JSInterop.JSException: 'Cannot read properties of null (reading 'scrollHeight')), or everything works fine, this is random I don`t even have an idea, after changing page to another then returning to [Protect.razor](https://github.com/sunnamed434/BitMono/blob/main/BitMono/BitMono.GUI/Pages/Obfuscation/Protect.razor) page and trying to output something you will get an the same error on empty output.
![image](https://user-images.githubusercontent.com/65300126/201473413-cefe9614-d515-4ee0-82ce-249bcec2243a.png)
![image](https://user-images.githubusercontent.com/65300126/201473446-26cbda32-ee8b-47f0-bf37-3cbba51470dd.png)
![image](https://user-images.githubusercontent.com/65300126/201473474-d124dcee-9de0-4212-a031-fc3fc9976d45.png)

Click button `Protect`
![image](https://user-images.githubusercontent.com/65300126/201473567-7db19301-3875-4dc6-b2b3-f0b7aef1d1cb.png)

![image](https://user-images.githubusercontent.com/65300126/201473494-4529c8f0-d632-48e9-8bc1-c9dcb7b39d7d.png)

### Link to public reproduction project repository

https://github.com/sunnamed434/BitMono/tree/main/BitMono/BitMono.GUI

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

6.0.400

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

I noticed that after executing InvokeAsync(StateHasChanged) causes this error, but this is not an workaround actually..

### Relevant log output

```shell
Microsoft.JSInterop.JSException: 'Cannot read properties of null (reading 'scrollHeight')
```

**Comment by Eilon** [comment]
I can still repro this. I cloned the repo and switched to this branch: https://github.com/sunnamed434/BitMono/tree/v0.4.0-alpha.9 (the code was since removed from the main branch). I then changed all the `net6.0` in the repo to `net8.0` and was able to run the project and follow the repro steps.

**Comment by Eilon** [comment]
I've spent quite a bit of time trying to get to the bottom of this, but unfortunately the repro is too complex to be able to make much progress. It's not clear to me where the bug would likely be (Blazor core? BlazorWebView? WebView2? A bug in the app's code?).

For now unfortunately I am choosing to close the bug until we can get a simpler reproduction of this, or at least more reports of the same/similar issue that would increase the priority.
