### ISSUE TITLE
No ios simulator in Visual Studio Mac

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/maui#11305]
My VS Mac looks like this, after opening a MAUI project:
![image](https://user-images.githubusercontent.com/17007651/201460498-4cb2b88f-940f-456b-83b7-dfd685ca2129.png)

Wondering where all the simulators are and how I can launch the application.

**Comment by Kremed** [comment]
need more information about the environment you're using and tools so the community can help you

Anyway, you have to make sure of several steps : 
1 - Check Xcode Version Compatibility
2 - Verify the MAUI IOS SDK 
3 - Update Your Visual Studio For mac

See This in Visual Studio Developer Community : https://developercommunity.visualstudio.com/t/ios-simulators-do-not-appear-for-running-project/1242725?viewtype=all

**Comment by nicholasyin** [comment]
> need more information about the environment you're using and tools so the community can help you
> 
> Anyway, you have to make sure of several steps : 1 - Check Xcode Version Compatibility 2 - Verify the MAUI IOS SDK 3 - Update Your Visual Studio For mac
> 
> See This in Visual Studio Developer Community : https://developercommunity.visualstudio.com/t/ios-simulators-do-not-appear-for-running-project/1242725?viewtype=all

Hardware: Mac Pro M1
Software: macOS Ventura 13.0.1, Xcode 14.1, MAUI iOS SDK 16.0.0, Visual Studio Mac 17.4

**Comment by nicholasyin** [comment]
First time learning that 'no answer' is equivalent to 'inactive' and 'completed'. psst...
