### ISSUE TITLE
[iOS] Shell.TitleView doesn't show accurate if not using just a string binding

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#11309]
### Description

When setting the `Shell.TitleView` in XAML, the content isn't shown up accurate on iOS 16.1.

```xaml
<Shell.TitleView>
        <Grid
            ColumnDefinitions="*,Auto"
            BackgroundColor="Red"
            >
            <Label
                Text="Headline"
                />
            <Button
                Grid.Column="1"
                Text="Button"
                />
        </Grid>
    </Shell.TitleView>
```
![image](https://user-images.githubusercontent.com/2952443/201476341-87c66aac-85a1-4de6-b394-1455f6a95488.png)

The `Label` isn't shown at all, the `Button` is only displayed half and setting a `BackgroundColor` has no effect (just for seeing the bounds of the `Grid`.
I just updated my repro for another issue with this issue.

Android works fine with the same project.

![image](https://user-images.githubusercontent.com/2952443/201476485-4fb8dde6-5a57-4335-b758-713eb814b200.png)

### Steps to Reproduce

1. Create a new MAUI app
2. Add the snippet above to the `MainPage`
3. Run it on iOS

### Link to public reproduction project repository

https://github.com/AndreasReitberger/ReproScrollingIssueModal

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

**Comment by AndreasReitberger** [comment]
@jsuarezruiz 
Is there any workaround for that? This also is keeping me from the app release. Or at least an ETA when this will be addressed?
Thank you!

**Comment by FM1973** [comment]
I got the same problem...

**Comment by DDHSchmidt** [comment]
> @jsuarezruiz Is there any workaround for that? This also is keeping me from the app release. Or at least an ETA when this will be addressed? Thank you!

You could try 
`<Grid Margin="{OnPlatform Default='0', iOS='0,0,0,-50'}>`
That should fix the offset of the TitleView.
Downside is: You can't limit this to iOS 16 only. If your user has iOS 15, this will probably look screwed.

**Comment by FM1973** [comment]
Happens on IOS 16, 15 and lower is fine.

**Comment by FM1973** [comment]
Hey there.
The following workaround works form me:
https://github.com/xamarin/Xamarin.Forms/issues/15512
In mauiprogram I then configure the handler like this:

`.ConfigureMauiHandlers((handlers) =>
            {
#if IOS16_0_OR_GREATER
                handlers.AddHandler(typeof(Shell), typeof(CustomShellRenderer));
#endif
            });`

**Comment by harrykontopoulos** [comment]
It happens on iOS 15.5 and 16 for me, unless I use the custom handler workaround suggestion above.
