### ISSUE TITLE
The default MAUI application created by Visual Studio on the Apple M1 platform cannot launch the Android emulator

### ISSUE THREAD

**Issue by bambuo** [dotnet/maui#11312]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/maui/first-app-tutorial/device-setup
Operating System: OSX Ventura 13.0

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I created a.NET MAUI application through Visual Studio without making any changes, and adjusted its startup environment to Debug using the Pixel 5-API 31 Android emulator, followed the prompts to install the corresponding dependencies, During startup, the system is generated successfully, but execution fails.

So I tried the following:

1. Change it to iPhone 14 ISO 16.0 to start and automatically open the display program interface of the emulator.
2. Modify MacCatalyst to start and display the program interface normally

In the end, I had to conclude that Visual Studio was flawed in Android development, and I couldn't find an entry to configure the Android emulator without starting the project, even if it wasn't possible to start the emulator.

I used Visual Studio for Mac 17.4 (build 2406)

I'm a newbie, and these are the problems I encountered when trying MAUI and using the Android emulator.

I read the document to https://dotnet.microsoft.com/zh-cn/learn/maui/first-app-tutorial/device-setup it is a pity that the graphics in the article only see Windows without Mac.

**Comment by jsuarezruiz** [comment]
Could you share the output, or some logs to get more information?

**Comment by bambuo** [comment]
[Re: [dotnet_maui] The default MAUI application created by Visual Studio on the Apple M1 platform cannot launch the Android emulator (Issue #11312).zip](https://github.com/dotnet/maui/files/10004722/Re.dotnet_maui.The.default.MAUI.application.created.by.Visual.Studio.on.the.Apple.M1.platform.cannot.launch.the.Android.emulator.Issue.11312.zip)

Attached is the reply email that failed to be sent, which contains some pictures and system environment, hoping to help find the problem
