### ISSUE TITLE
Label  TextType="Html" Crash in Windows  if html is "Broken"

### ISSUE THREAD

**Issue by lucianparvu** [dotnet/maui#11311]
### Description

Label  TextType="Html" Crash in Windows if html "Is Broken" .  

Same Html works in IOS and Android

How to check the Broken Html Before ?

` <Label  TextType="Html"
            Text="{Binding Item.Description}"
            VerticalOptions="Center" 
            HorizontalOptions="Center" />`

### Steps to Reproduce

-

### Link to public reproduction project repository

dont have

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Relevant log output

```shell
-
```

**Comment by jsuarezruiz** [comment]
Could you share the broken html used?

**Comment by lucianparvu** [comment]
I tried to display description of an product inserted in DB by a web app using some html editor .

Link : https://github.com/lucianparvu/Files/blob/67ab161399e8333f67f4c9ad7bce86def02da8b7/BrokenHtml

**Comment by ne0rrmatrix** [comment]
This fix works for html strings that have https with a ? mark in them. It simply removes everything after ? mark so it can render. This fixes a small issue for me that allows the page to render by ignoring invalid data in links.
```
public static string RemoveBADHtmlTags(string HTMLCode)
    {
        HTMLCode = Regex.Replace(HTMLCode, "/\\?.*?.\"", "\"", RegexOptions.IgnoreCase | RegexOptions.Singleline);
        return HTMLCode;
    }
```
