### ISSUE TITLE
Lowercase char in Entry with TextTransform=Uppercase moves cursor to the beginning

### ISSUE THREAD

**Issue by richardoplustil** [dotnet/maui#11313]
### Description

Typing lowercase character in Entry with TextTransform="Uppercase" makes carret jump to the start of the entry. This causes typing next character at the beginning of the text.
It happens only when typing lowercase character - and is being transformed to uppercase.
Typing uppercase characters or numeric values doesn't cause this.
Works fine on Windows platform.

### Steps to Reproduce

Create default .NET MAUI App > .NET 7.0
Add `<Entry **TextTransform="Uppercase"** />` to Main page (MainPage.xaml)
Run on Android 12.1 - API 32 emulator.
Press keys: 1 2 3 a b c d

Expected outcome: Entry is filled with value "123ABCD" and carret is at the end of the text.
Actual outcome: Entry is filled with value "DCB123A" and carret is at the beginning of the text.
![image](https://user-images.githubusercontent.com/72247560/201481353-8d3b898c-7fcf-4124-82ef-43cd2c69a0ed.png)

### Link to public reproduction project repository

https://github.com/richardoplustil/TextTransformUppercaseBug

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

Android

### Affected platform versions

Android 12.1

### Did you find any workaround?

Removed TextTransform="Uppercase" attribute. Transforming to .UpperCase() later in ViewModel. Remains as-typed in the View.

**Comment by petes05** [comment]
I'm having this same issue.

**Comment by faceoffers28** [comment]
Same problem. I would be interested to know how an upgrade to .Net 7.0 can cause such a huge problem. Was the code changed? I did a search in the repository, but I can't find the code where the actual work is being performed to transform the text.

**Comment by MahmoudAlEssawi** [comment]
I have had the same issue since I upgraded to .NET 7

**Comment by cmsdesigner** [comment]
Me too I have had the same issue since I upgraded to .NET 7 on .NET 6 All work well

**Comment by HobDev** [comment]
This is still an issue

**Comment by shadowfoxish** [comment]
Also confirmed. Android/.NET 7/Maui 7.0.52

This is a behavioral change, I previously had this implemented in the backing property like so and it seemed to work in Xamarin.Forms 5.

```
	private string _myProp;
	public string MyProp
	{
		get {
			return _myProp;
		}
		set {
			_myProp = value?.ToUpper();
			NotifyPropertyChanged(nameof(MyProp));
		}
	}
```

**Comment by nbiada** [comment]
Confirmed also with Scan Reader in keyboard emulation.

**Comment by a7son** [comment]
please tell me how to fix this? damn after update MAUI still have this problem..

**Comment by PureWeen** [comment]
Can someone validate if this is fixed in .NET 8 preview1? We'd like to just get some user validation before considering this for backporting.
