### ISSUE TITLE
.net maui android app crashes when deployed to google play closed testing

### ISSUE THREAD

**Issue by ikeoriaku123** [dotnet/maui#11316]
### Description

I recently got an update to .net maui .net 7 - stable version on the 08/11/2022. I tested all apps before release to testflight and play store closed testing. Everything worked on testflight but not on play console alpha testing. I have used App tester but the app crashes on opening the app. I have tried with firebase Test lab and it has produced some errors that I cannot understand. Please can anyone help as this project is very critical.

VS for mac version:
Visual Studio Enterprise 2022 for Mac
Version 17.4 (build 2406)
Installation UUID: 5e3cb452-01f4-4529-9007-a2b3ccc64eae

Runtime
.NET 6.0.9 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.4.0-3.22461.4+8ab250290a4010c11a21521f78dbc87dbb7aac81

NuGet
Version: 6.3.1.1

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.100/Sdks
SDK Versions:
	7.0.100
	7.0.100-rc.2.22477.23
	7.0.100-rc.1.22431.12
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	6.0.400-preview.22330.6
	6.0.302
	6.0.300
	6.0.203
	6.0.202
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.425
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.202
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.0
	7.0.0-rc.2.22472.3
	7.0.0-rc.1.22426.10
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5
	6.0.4
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.31
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.0.9

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Enterprise)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Enterprise)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:42:23 UTC

Xamarin.Android
Version: 13.1.0.1 (Visual Studio Enterprise)
Commit: xamarin-android/d17-4/13ba222
Android SDK: /Users/obioriaku/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.1 (API level 32)
		8.0  (API level 26)
		6.0  (API level 23)
		12.0 (API level 31)
		8.1  (API level 27)
		5.1  (API level 22)
		5.0  (API level 21)
		11.0 (API level 30)
		10.0 (API level 29)
		7.1  (API level 25)
		9.0  (API level 28)
		13.0 (API level 33)
		7.0  (API level 24)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: a96bde9
Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
SQLite: xamarin/sqlite/3.39.3@23e1ae7
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:42:28 UTC

Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2022-11-02 23:42:28 UTC

Build Information
Release ID: 1704002406
Git revision: dfb45c1152306f0d5f77334f9d026b0aadb7ec90
Build date: 2022-11-02 23:40:15+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:17:10 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

Enabled user installed extensions
Template Creator 0.7
NuGet Package Explorer 0.10
.NET Core Extensions 0.5
NuGet Package Management Extensions 0.32

### Steps to Reproduce

1. Updated Vistual studio for mac 2022 to stable versions
2. Built the project and confirmed running on both ios and android devices work very well, no issues.
3. Deployed to both TestFlight and play store closed testing.
4. Tested app on iphone device - working very well
5. Tested app on samsung device via App tester and Firebase Test Lab, not working. App crashes when opening the app.

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 5 - Android 11

### Did you find any workaround?

No

### Relevant log output

```shell
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/redfin/redfin:11/RQ3A.211001.001/7641976:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2022-11-12 13:48:23-0800
pid: 21398, tid: 21398, name: rom.appname  >>> com.adarcrom.appname <<<
uid: 10275
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'No assemblies found in '/data/user/0/com.adarcrom.appname/files/.__override__' or '<unavailable>'. Assuming this is part of Fast Deployment. Exiting...'
    x0  0000000000000000  x1  0000000000005396  x2  0000000000000006  x3  0000007ff1af1440
    x4  fefefefefefefeff  x5  fefefefefefefeff  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  0000007675b697c0  x10 ffffff80fffffbdf  x11 0000000000000001
    x12 0000007ff1aefcf0  x13 0000000000000079  x14 0000007ff1af0f68  x15 000000000000001b
    x16 0000007675c01c80  x17 0000007675be3320  x18 0000007678c52000  x19 0000000000005396
    x20 0000000000005396  x21 00000000ffffffff  x22 b400007542f0ba68  x23 000000737a35a3c8
    x24 0000007ff1af1b60  x25 00000076784cf000  x26 000000737a35a678  x27 0000007ff1af2320
    x28 0000007ff1af1df0  x29 0000007ff1af14c0
    lr  0000007675b97148  sp  0000007ff1af1420  pc  0000007675b97178  pst 0000000000001000
```

**Comment by jsuarezruiz** [comment]
Could you share more logs or info?

**Comment by ikeoriaku123** [comment]
> Could you share more logs or info?

Hello, thanks for responding. I resolved it by adding this attribute <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk> both in the csproj and azure pipeline publish task

**Comment by PureWeen** [comment]
@jonathanpeppers thoughts?

**Comment by jonathanpeppers** [comment]
This message would mean you possibly sent a `Debug` build to Google Play?
```
Abort message: 'No assemblies found in '/data/user/0/com.adarcrom.appname/files/.__override__' or '<unavailable>'. Assuming this is part of Fast Deployment. Exiting...'
```

The setting for this is:
* Debug mode = `EmbedAssembliesIntoApk=false`
* Release mode = `EmbedAssembliesIntoApk=true`.
