### ISSUE TITLE
ListView with ObservableCollection issue during scrolling (ObjectDisposedException)

### ISSUE THREAD

**Issue by gbbsoft** [dotnet/maui#11323]
### Description

If ListView has more lines than screen (Android) than during scrolling down using mouse wheel there is exception:
System.ObjectDisposedException
  Message=Cannot access a disposed object.
Object name: 'Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer'.

PS. The same was in .Net 6.0 Maui

### Steps to Reproduce

I create a simple example: https://github.com/gbbsoft/Maui_ListViewIssue

### Link to public reproduction project repository

https://github.com/gbbsoft/Maui_ListViewIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Emulator and Galaxy S20 FE (Android 12)

### Did you find any workaround?

No

**Comment by MdLejTeCole** [comment]
Hi, I had the same problem. I put the Frame into the Grid and the problem does not occur.

`    <Grid>`
`             <Frame>`                              
`             </Frame>`
`    </Grid>`

**Comment by MdLejTeCole** [comment]
When I checking your repo you have one more frame off-grid. Before <Grid > from your screenshot.

**Comment by gbbsoft** [comment]
When I remove off-grid frame there is no issue :) :(

**Comment by Hakim83** [comment]
As you mentioned, the bug appear with 'frame', one workaround that works for me is to encolse it with another layout, no issue then :)

```
<StackLayout>
   <Frame BorderColor="Gray"
                 CornerRadius="10"
                 Padding="5,10,5,10"
                 Margin="10,0,10,0"
                 >
                    <Grid >
                              ...
                    </Grid>
     </Frame>
</StackLayout>
```

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on android platform with sample project.
[Maui_ListViewIssue-master.zip](https://github.com/dotnet/maui/files/11610036/Maui_ListViewIssue-master.zip)
![Screenshot 2023-05-31 153713](https://github.com/dotnet/maui/assets/77434865/2df3a9cf-d0e7-44a1-951d-bec9925ba1d6)

**Comment by sanchessls** [comment]
> orm with sa

That works, for all my projects.
Just NOT having a frame as Main component of a ViewCell!

**Comment by jfversluis** [comment]
Seeing that Frame is officially deprecated as of .NET 9, I don't think we will be working on this anymore. Also its a bit older by now, so maybe its even resolved in current versions 🤞
