### ISSUE TITLE
Incorrect layout with RefreshView, CollectionView that has an GridItemsLayout on iPhone

### ISSUE THREAD

**Issue by vpshonyak** [dotnet/maui#11327]
### Description

I'm having an RefreshView with CollectionView that has an GridItemsLayout that should draw two columns of boxes. On Android, it is perfect: 
![image](https://user-images.githubusercontent.com/47300892/201550343-d0342fd9-8fc7-4166-a92b-67569fcc84b5.png)

But not on iPhone. It shows only odd boxes instead:
![image](https://user-images.githubusercontent.com/47300892/201550390-2437abef-4969-496a-a213-e32d3fd30929.png)

### Steps to Reproduce

1.Create a new MAUI application.
2. Update MainPage.xaml:

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.MainPage">

    <RefreshView>
        <CollectionView 
            BackgroundColor="DarkBlue"
            ItemsSource="{Binding Numbers}"
            >
            <CollectionView.ItemsLayout>
                <GridItemsLayout 
                    Orientation="Vertical"
                    Span="2"
                    VerticalItemSpacing="5"
                    HorizontalItemSpacing="5" />
            </CollectionView.ItemsLayout>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <StackLayout HeightRequest="50" BackgroundColor="Purple">
                        <Label Text="{Binding }" TextColor="White" HorizontalOptions="Center" VerticalOptions="Center" />
                    </StackLayout>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </RefreshView>
</ContentPage>`

3. Update MainPage.xaml.cs:

`
namespace MauiApp2;

public partial class MainPage : ContentPage
{

    public List<int> Numbers { get; } = Enumerable.Range(1, 100).ToList();
    public MainPage()
	{
		InitializeComponent();
        BindingContext = this;
    }

}
`

### Link to public reproduction project repository

https://github.com/vpshonyak/MauiApp2.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

**Comment by Redth** [comment]
Is there a particular reason you're putting the RefreshView inside of a Grid here?  Also the RefreshView does not have a row assigned from the grid, and having it default to the "Auto" row height is probably causing some strange behaviour because the CollectionView will naturally want to take up all available area on the screen.

**Comment by vpshonyak** [comment]
@Redth I'm just trying to have two columns inside a RefreshView. Not sure how to archive it without a Grid. Changing "Auto" to "*" helps only temporarily while app is Hot Reloaded. Unfortunately, after recompiling and restarting the layout is bad again.

Given code works perfectly in Xamarin/Android/iPhone and MAUI/Android. Only in MAUI/iPhone layout extends to 200% of screen width.

**Comment by minglu** [comment]
+1
