### ISSUE TITLE
Label not changing text 

### ISSUE THREAD

**Issue by Robert9330** [dotnet/maui#11325]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/modify
Operating System: windows

Trying to edit the text in first label in toturial, but it's not updating. Moved on to changing counts per click and that works fine. But text still not chaniging.

**Comment by jfversluis** [comment]
Hey @Robert9330 sorry that isn't working! Do you see any message about Hot Reload whenever you start the application?

If you stop and start the debugging session and start editing some things do the changes show up then?

Lastly, if you go to Tools > Options, what do the settings look like?

![image](https://user-images.githubusercontent.com/939291/201697522-b83384ac-6550-48e9-8fcc-9d381cab07a8.png)

In any case, XAML Hot Reload is a great productivity booster, but if it's not working that shouldn't block you from making any progress here. Still, we'd love to figure out what might be causing this for you and fix it!

**Comment by Robert9330** [comment]
Hi, my settings looks like the picture above. Had trouble also getting the android emulator running, so tried to start a new project and now the changes I'm making is shown fine in the emulator, so I guess it's working?

**Comment by jfversluis** [comment]
Cool! If this fails again and it fails consistently, please report it through Visual Studio. Under the Help menu find Provide Feedback and Report a Problem. That will collect all relevant logs and send it to the right team, happy developing!
