### ISSUE TITLE
Infrared sensor 

### ISSUE THREAD

**Issue by Mahdikh75** [dotnet/maui#11322]
### Description

Hello team, please enable the ability to send infrared frequencies (infrared hardware support). Thanks 

### Public API Changes

.

### Intended Use-Case

The application of this feature is to make remote control programs

**Comment by jfversluis** [comment]
This is very specific and my gut says this will have a fairly small audience that will want to use this. I don't think we'll be adding this (in the near future) as such, closing it for now.

**Comment by sharpordie** [comment]
Damn, I'm doomed to stay with good old Xamarin. :(
