### ISSUE TITLE
Android-.NET6-Style issue when changing the button status (disabled->enabled)

### ISSUE THREAD

**Issue by jonmikeli** [dotnet/maui#11336]
#### Control
button

#### Issue description
The background color is not updated when changing the status of a button from disabled to enabled.
The button is clickable though.
Border and foreground (text) styles are updated properly.
If the view is reloaded, the background color is updated with the right style.

The status is updated through the "CanExecute" methods/properties of the RelayCommands bound to the control (MVVM Community Toolkit, 8.0.0).

#### Environment
.NET 6
Visual Studio 2022 (17.4)

#### Other
Additionally, other issues with style loading have been noticed with checkboxes. If you think the source of the issue might be different, I can create another issue.

### Steps to Reproduce

1. Create a MAUI project.
2. Add a button (disabled by default).
3. Customize the style (colors) for the enabled/disabled status.
4. Add a View Model (MVVM Community Toolkit).
5. Add a RelayCommand with a CanExecute method/property.
6. Bind the command of the button to the previous RelayCommand.
7. Update the status.

### Link to public reproduction project repository

Not applicable

### Version with bug

6.0.486

### Last version that worked well

6.0.312

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android API 31+

### Did you find any workaround?

No workaround but refreshing the view updates the style.

**Comment by jonmikeli** [comment]
Hi  @affableashish,

Yes, I get it. Just thought that sharing the true solution was probably the best way to be efficient (for everybody involved in this) and figure out what is wrong.

Taking problems with some level of complexity out of their context might require considerable effort to do it properly and without changing the potential source of the issue. I would not like to waste the time of the people who looks into this with inaccurate sample projects.

**Comment by PureWeen** [comment]
@jonmikeli you can create a vsfeedback issue and attach a project there. 

Did you also try on NET7?
