### ISSUE TITLE
iOS The type initializer for 'Microsoft.Maui.Controls.Shapes.Shape' threw an exception. on latest .NET 7

### ISSUE THREAD

**Issue by paulhavey** [dotnet/maui#11333]
### Description

On our project on iOS this code throws an exception using latest 
.NET 7
Xcode 14.1, 
Xamarin.iOS 16.0.0.72,
VS Version 17.5.0 Preview 1.0

Android and UWP are fine... Maui Sample project also works fine on iOS

```
builder.UseMauiApp<App>().ConfigureFonts(fonts =>
        {
            fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
            fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
        })
        .UseMauiCommunityToolkit()
        .ConfigureEssentials(essentials =>
        {
            essentials.UseVersionTracking();
        });

```
### Steps to Reproduce

Not sure

### Link to public reproduction project repository

NA

### Version with bug

7.0 (current)

### Last version that worked well

7.0 Release Candidate 2

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

No

### Relevant log output

```shell
{System.TypeInitializationException: The type initializer for 'Microsoft.Maui.Controls.Shapes.Shape' threw an exception.
 ---> System.MissingFieldException: Field not found: Microsoft.Maui.IPropertyMapper`2<Microsoft.Maui.IShapeView, Microsoft.Maui.Handlers.IShapeViewHandler> Microsoft.Maui.Handlers.ShapeViewHandler.Mapper Due to: Could not find field in class
   --- End of inner exception stack trace ---
   at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.RemapForControls(MauiAppBuilder builder)
   at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.SetupDefaults(MauiAppBuilder builder)
   at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.UseMauiApp[App](MauiAppBuilder builder)
   at AssessorApp.MauiProgram.CreateMauiApp() in C:\Users\User\workspace\project\MauiProgram.cs:line 13
   at AssessorApp.AppDelegate.CreateMauiApp() in C:\Users\User\workspace\project\project\Platforms\iOS\AppDelegate.cs:line 16
   at Microsoft.Maui.MauiUIApplicationDelegate.WillFinishLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at AssessorApp.Program.Main(String[] args) in C:\Users\User\workspace\project\project\Platforms\iOS\Program.cs:line 15}
    base: {System.SystemException}
    TypeName: "Microsoft.Maui.Controls.Shapes.Shape"
```

**Comment by mancda** [comment]
I ran into the same problem today as well.

**Comment by PureWeen** [comment]
It looks like the issue here is if you specify `net7.0-ios15.4` as a TFM 

I'm not sure if that's supported. @rolfbjarne  thoughts?

**Comment by mancda** [comment]
Sorry this took so long.  

![about](https://user-images.githubusercontent.com/10619392/202306970-22b5317f-5718-49eb-bcd7-2d2723bf9bc6.png)

![packages](https://user-images.githubusercontent.com/10619392/202307040-ca7130fc-1503-4bc4-8a7e-c73389e2c8d6.png)

**Comment by mancda** [comment]
I am targeting a Mac running Ventura OS and targeting the IPhone 14 Plus IOS 16 Simulator.

**Comment by PureWeen** [comment]
@mancda can you past your csproj file here? and/or attach a binlog? https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

**Comment by mancda** [comment]
See attached.
[binlogandcsproj.zip](https://github.com/dotnet/maui/files/10032374/binlogandcsproj.zip)

**Comment by PureWeen** [comment]
@mancda you need to change this

![image](https://user-images.githubusercontent.com/5375137/202506738-2711d363-1ac4-466c-90b7-7ec3806f803b.png)

remove the 15.4 from net7.0-ios

**Comment by mancda** [comment]
That fixed it for me.  Thank you very much.

**Comment by PureWeen** [comment]
Closing this issue in favor of https://github.com/xamarin/xamarin-macios/issues/16802

I've also engaged with the IDE teams on this one to provide a better experience with the TFM dropdown options.
