### ISSUE TITLE
android application with testOnly option set to true can't be deployed

### ISSUE THREAD

**Issue by prostopsih** [dotnet/maui#11345]
### Description

This is error that I get:
ADB0010: Mono.AndroidTools.InstallFailedException: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]...

https://stackoverflow.com/questions/62162640/xamarin-android-install-flags 
There is same problem with xamarin.forms

### Steps to Reproduce

1. Create new dotnet maui application
2. Set android:testOnly="true" property on application tag in android manifest
3. Try to debug application

### Link to public reproduction project repository

https://github.com/prostopsih/Android-TestOnly-Bug-Repro

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9, 12, 13

### Did you find any workaround?

deploy manually using following command:
adb install -t {apkFilePath}

The problem is that I can't debug my application after installing it in such way.

In android studio testOnly is set to true by default and also there is a possibility to add extra parameters on install command.

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by jonathanpeppers** [comment]
@prostopsih can you describe a bit why you want to use `android:testOnly="true"`? To understand the use-case.

What does it do for you?

**Comment by prostopsih** [comment]
I develop a kiosk application and granting device owner access to my application via this command:
`adb shell dpm set-device-owner {packageName}/{adminReceiverClassName}`
But to remove it with this command:
`adb shell dpm remove-active-admin {packageName}/{adminReceiverClassName}`
I need application to be installed as testOnly
Otherwise I need to reinstall firmware of my device

**Comment by jonathanpeppers** [comment]
@dellis1972 do you know if there is some MSBuild property that would allow passing `-t` to `adb install` commands?

**Comment by dellis1972** [comment]
@jonathanpeppers not of the top of my head. I guess we'd need to add an argument to androidtools to allow us to do that. 
It should probably also autodetect the `testOnly` attribute in the manifest and turn that on if its `true`.
