### ISSUE TITLE
Picker on windows not load in MVVM

### ISSUE THREAD

**Issue by mibuswolf** [dotnet/maui#11343]
### Description

I use CommunityToolkit.Mvvm to load items in picker , on andriod and ios load good but on windows never show data.

    private readonly IApiService _apiService;

        [ObservableProperty]
        public ObservableCollection<Companies> _companies;

        [ObservableProperty]
        private bool _isrunning;

        //public ObservableCollection<Companies> Companies1
        //{
        //    get => _companies;
        //    set => SetProperty(ref _companies, value);
        //}

        public  LoginPageViewModel(ApiService apiService)
        {
            _apiService = apiService;
      

           this.LoadCompanies();
        }

        private async void LoadCompanies()
        {
            Isrunning = true;
            /*
            if (Connectivity.NetworkAccess != NetworkAccess.Internet)
            {
                //await _alertDialogService.ShowDialogAsync(Resource.Error, "ic_cancel", Resource.ConnectionError, Resource.Accept);
                return;
            }*/

            string url = "xxxx"; 

            HttpClient _client;
            _client = new HttpClient();
            HttpResponseMessage response = await _client.GetAsync(url+ "/api/account/companylist");

            string result = await response.Content.ReadAsStringAsync();

            Response response1 = await _apiService.GetListAsync<Companies>(url, "/api", "/account/companylist");

            List<Companies> list = (List<Companies>)response1.Result;
            Companies = new ObservableCollection<Companies>(list.OrderBy(c => c.CompanyName));
            Isrunning = false;
            /*
            if (!response.IsSuccess)
            {
                await _alertDialogService.ShowDialogAsync(Resource.Error, "ic_cancel", Resource.AXConectionError, Resource.Accept);
                return;
            }*/

            //  List<Companies> list = (List<Companies>)response.Result;
            /// companies = new ObservableCollection<Companies>(list.OrderBy(c => c.CompanyName));
        }
    }

 <Picker Title="Select a monkey"
                    ItemsSource="{Binding Companies}"
                
                    ItemDisplayBinding="{Binding CompanyName}" />

![image](https://user-images.githubusercontent.com/39713441/201679843-6cbe82d4-f642-414d-a6bb-b93fd759c2c7.png)

### Steps to Reproduce

.

### Link to public reproduction project repository

.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

19041

**Comment by AndreasReitberger** [comment]
Have you tried to rename the property?

```cs
[ObservableProperty]
public ObservableCollection<Companies> companies; //_companies;
```
The `ObservableProperty` takes the name and creates the observable property with a capital letter. I'm
not sure what happens if it starts with `_`.

Also you can try to remove the line ` ItemDisplayBinding="{Binding CompanyName}"`. just to see if the list has items.
A wrong binding here, can also lead to an invisble list.

Another try is, to change `private async void LoadCompanies()` to `private async Task LoadCompanies()` and add a `trycatch`,
maybe you do not reach the line setting the `Companies` at all.

```cs
Companies = new ObservableCollection<Companies>(list.OrderBy(c => c.CompanyName));
```

I'm using the `Picker` in serveral MAUI projects, had no issues with it yet.

**Comment by mibuswolf** [comment]
> Have you tried to rename the property?
> 
> ```cs
> [ObservableProperty]
> public ObservableCollection<Companies> companies; //_companies;
> ```
> 
> The `ObservableProperty` takes the name and creates the observable property with a capital letter. I'm not sure what happens if it starts with `_`.
> 
> Also you can try to remove the line ` ItemDisplayBinding="{Binding CompanyName}"`. just to see if the list has items. A wrong binding here, can also lead to an invisble list.
> 
> Another try is, to change `private async void LoadCompanies()` to `private async Task LoadCompanies()` and add a `trycatch`, maybe you do not reach the line setting the `Companies` at all.
> 
> ```cs
> Companies = new ObservableCollection<Companies>(list.OrderBy(c => c.CompanyName));
> ```
> 
> I'm using the `Picker` in serveral MAUI projects, had no issues with it yet.

Hello the problem is the version of the visual studio , i install the new version and the problem end.
