### ISSUE TITLE
Xcode 14.1 not compatible whit VS 2022

### ISSUE THREAD

**Issue by Kremed** [dotnet/maui#11348]
### Description

I am trying to run the MAUI application on a MacBook connected to the network, during the connection process a message appears:
`The Xcode version installed on the Mac (14.1) is not compatible with this version of Visual Studio. This may cause unexpected warnings or errors when building and deploying iOS projects. Please install Xcode '0.0'. To download a specific version of Xcode, visit https://developer.apple.com/downloads.`

![Screenshot 2022-11-14 182116](https://user-images.githubusercontent.com/43956454/201711722-63545cfa-8d76-4f45-a9c1-29ac6322b459.png)

after that, it connected but no simulator showed,
![Screenshot 2022-11-14 182232](https://user-images.githubusercontent.com/43956454/201713612-0a7afad7-7890-4a1c-9801-7d1f99327deb.png)

now I will downgrade Xcode to 14.0 and give that try 

### Steps to Reproduce

-

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

-

**Comment by beeradmoore** [comment]
Support will be coming (I assume shortly?). In the mean time you should downgrade Xcode to 14.0.1. 

There is a neat tool called [Xcodes](https://www.xcodes.app) that can help manage multiple Xcode installs so you will be able to continue working even if the latest Xcode is not fully supported yet.

**Comment by jfversluis** [comment]
As indeed pointed out, not supported right now. Thanks @beeradmoore for the great suggestion here.

The only thing that looks a bit weird is the version number it's reporting @maddymontaquila 

For the rest, not much to do here, support will come asap. Thanks!

**Comment by svaldetero** [comment]
@jfversluis Do we have a github issue that we can use to track MAUI support for Xcode 14.1 or does it support it now? I've been holding off on updating because I have MAUI apps.

**Comment by jfversluis** [comment]
@svaldetero as per the update from yesterday it should be supported!

**Comment by Kremed** [comment]
Its work just fine now 🎈👌
