### ISSUE TITLE
Wrong height for multi-line Label under certain conditions

### ISSUE THREAD

**Issue by tschramme86** [dotnet/maui#11358]
### Description

When the text of a multi-line Label reaches a certain length (depending on available horizontal space, word lengths, font size, etc.), apparently the height calculation of the label assumes the Label will have a height of `n` lines, while the actual text then is rendered in `n + 1` lines. This causes the last line of the label to be truncated in the rendering.

This is a huge issue for apps with variable horizontal space + unpredictable text content. Even if it might look good on the developer machine, the layout could be broken + text truncated on the users machine when the horizontal size is different or text content is different.

See attached screenshots for Windows + Android. Both section headings have more text than it would fit in one line. But the height calculation for the first label thinks it would still fit in one line, so the last word "Label" is truncated.
For the second section heading I just added one more character so that the last word becomes "Labelx". Now also the height calculation thinks that two lines are necessary and the label text is rendered correctly.

![image](https://user-images.githubusercontent.com/54247971/201785082-bc8db17f-36e5-4823-84cc-742d85ff0761.png)

![image](https://user-images.githubusercontent.com/54247971/201785690-0ee2307f-8a6d-4f13-88dc-63488552a795.png)

### Steps to Reproduce

1. Create the labels shown in the above screenshots like this:

		<Grid ColumnDefinitions="*,300,*">
			<ScrollView Grid.Column="1">
				<VerticalStackLayout>
					<Grid Padding="10" ColumnDefinitions="Auto,*,Auto" RowDefinitions="Auto,Auto">
						<BoxView WidthRequest="24" Grid.Column="0" Color="Blue" VerticalOptions="Fill" />
						<Label Text="Section Multi Line Heading Label" 
								Grid.Row="0" Grid.Column="1" FontSize="16" FontFamily="OpenSansSemibold" />
						<Label Text="Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua." 
								Grid.Row="1" Grid.Column="1" FontSize="14" FontFamily="OpenSansRegular" />
						<BoxView WidthRequest="24" Grid.Column="2" Grid.Row="1" Color="Yellow" VerticalOptions="Fill" />
					</Grid>
					<Grid Padding="10" ColumnDefinitions="Auto,*,Auto" RowDefinitions="Auto,Auto">
						<BoxView WidthRequest="24" Grid.Column="0" Color="Blue" VerticalOptions="Fill" />

						<Label Text="Section Multi Line Heading Labelx" 
								Grid.Row="0" Grid.Column="1" FontSize="16" FontFamily="OpenSansSemibold" />
						<Label Text="Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua." 
								Grid.Row="1" Grid.Column="1" FontSize="14" FontFamily="OpenSansRegular" />
						<BoxView WidthRequest="24" Grid.Column="2" Grid.Row="1" Color="Yellow" VerticalOptions="Fill" />
					</Grid>
				</VerticalStackLayout>
			</ScrollView>
		</Grid>

2. See that the first label has an incorrect height.

To reproduce, this example is also provided in this test app: https://github.com/tschramme86/MauiBugs
Open and navigate to bug 002 "Wrong Label Height when MultiLine" from the main page (Page file is "/Bugs/Bug002-MultiLineLayout/Bug002MultiLineLayout.xaml").

### Link to public reproduction project repository

https://github.com/tschramme86/MauiBugs

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

net7.0-Windows SDK 10.0.19041 (tested on Win 11), net7.0-android33.0 (tested on Android 11 + Android 13)

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified on Visual Studio Enterprise 17.7.0 Preview 1.0. This issue does not repro on Windows 11 and Android 13.0-API33 with below Project:
[11358.zip](https://github.com/dotnet/maui/files/11649566/11358.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/eeaba9dc-e980-4ab0-8759-79e13e8bc72d)
Android:
![image](https://github.com/dotnet/maui/assets/97647558/cc9dfa32-8116-4ca7-8dcd-e3009ca89bff)
