### ISSUE TITLE
Build of MAUI app fails if NuGet package contains references

### ISSUE THREAD

**Issue by AntonKosenkoDX** [dotnet/maui#11364]
### Description

We want to hide our private libraries from IntelliSense for our customers. We followed the instructions from the following guide: [Multiple assemblies in one package](https://learn.microsoft.com/en-us/nuget/create-packages/select-assemblies-referenced-by-projects#not-recommended-multiple-assemblies-in-one-package). This solution works in pure net7.0 apps, but leads to build errors on MAUI apps.

### Steps to Reproduce

I prepared a sample repo to demonstrate this issue: https://github.com/AntonKosenkoDX/nuget-refs.

To build this project, please run the `build` script or execute the following commands:

```
dotnet build MyUtilities/MyUtilities.csproj
dotnet build MyLib/MyLib.csproj
nuget pack MyNuget/MyNuget.nuspec -OutputDirectory MyNuget/

dotnet build MyApp/MyApp.csproj
dotnet build MyConsoleApp/MyConsoleApp.csproj
```

You will see that the pure NET7 project is built without errors and it's IntelliSense shows only members from MyLib. Members from MyUtilities are not shown. This behavior is expected.

However, an attempt to build MyApp (MAUI application) results with the following error:
```
 error XAGJS7028: System.IO.FileNotFoundException: Could not load assembly 'MyUtilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile? 
```

### Link to public reproduction project repository

https://github.com/AntonKosenkoDX/nuget-refs

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All

### Did you find any workaround?

No

### Relevant log output

```shell
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028: System.IO.FileNotFoundException: Could not load assembly 'MyUtilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile? [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028: File name: 'MyUtilities.dll' [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 245 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 191 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Mono.Cecil.MetadataResolver.Resolve(TypeReference type) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/MetadataResolver.cs:line 110 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/ModuleDefinition.cs:line 762 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Mono.Cecil.TypeReference.Resolve() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/TypeReference.cs:line 278 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Java.Interop.Tools.Cecil.TypeDefinitionCache.Resolve(TypeReference typeReference) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionCache.cs:line 20 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Java.Interop.Tools.Cecil.TypeDefinitionRocks.GetBaseType(TypeDefinition type, IMetadataResolver resolver) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:line 23 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Java.Interop.Tools.Cecil.TypeDefinitionRocks.GetTypeAndBaseTypes(TypeDefinition type, IMetadataResolver resolver)+MoveNext() in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:line 40 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Java.Interop.Tools.Cecil.TypeDefinitionRocks.IsSubclassOf(TypeDefinition type, String typeName, IMetadataResolver resolver) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:line 94 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Java.Interop.Tools.JavaCallableWrappers.JavaTypeScanner.AddJavaTypes(List`1 javaTypes, TypeDefinition type) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs:line 58 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Java.Interop.Tools.JavaCallableWrappers.JavaTypeScanner.GetJavaTypes(IEnumerable`1 assemblies, IAssemblyResolver resolver) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs:line 48 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res) [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask() [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.4/tools/Xamarin.Android.Common.targets(1476,3): error XAGJS7028:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17 [/Users/antonkosenko/work/nuget-refs/MyApp/MyApp.csproj::TargetFramework=net7.0-android]
```

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by jonathanpeppers** [comment]
Can you share the `.nupkg` files you created in the example above? (Or at least just list the file contents)

Also an [MSBuild diagnostic log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) would help us look into the error message. Thanks!

**Comment by AntonKosenkoDX** [comment]
Hello @jonathanpeppers! Thanks for fast response. 
I've added `.nupkg` file here:
https://github.com/AntonKosenkoDX/nuget-refs/tree/main/MyNuget 
And diagnostic log here:
https://github.com/AntonKosenkoDX/nuget-refs/blob/main/MyApp/msbuild-diagnostic.log 

Hope it helps.

**Comment by jonathanpeppers** [comment]
Hmm, how did you end up with:

![image](https://user-images.githubusercontent.com/840039/202034033-2a8065bc-106e-4cd2-900e-bbb0714c59b7.png)

Does the problem go away with `net7.0-android33`??? That should actually be the default value, but it has 31 in your package.

**Comment by AntonKosenkoDX** [comment]
I've just tried to up target version to android33 and the error still appears(

**Comment by AntonKosenkoDX** [comment]
@jonathanpeppers ?

**Comment by jonathanpeppers** [comment]
@AntonKosenkoDX your `.nuspec` file has:
```xml
<group targetFramework="net7.0-android31.0"/>
```
There are also manual file paths like:
```xml
<file src=".\..\MyLib\bin\Debug\net7.0-android\MyLib.dll" target="ref\net7.0-android31.0"/>
<file src=".\..\MyLib\bin\Debug\net7.0-android\MyLib.dll" target="lib\net7.0-android31.0"/>
<file src=".\..\MyUtilities\bin\Debug\net7.0-android\MyUtilities.dll" target="lib\net7.0-android31.0"/>
<file src=".\..\MyLib\bin\Debug\net7.0-android\MyLib.aar" target="lib\net7.0-android31.0"/>
<file src=".\..\MyUtilities\bin\Debug\net7.0-android\MyUtilities.aar" target="lib\net7.0-android31.0"/>
```

If you change these all to 33, does it solve the issue?

**Comment by AntonKosenkoDX** [comment]
@jonathanpeppers As I said before I updated android version to 33 in my `.nuspec` but it didn't fix the problem. I've also double checked this just now and have updated the reproducing sample.  
https://github.com/AntonKosenkoDX/nuget-refs/blob/main/MyNuget/MyNuget.nuspec

**Comment by jonathanpeppers** [comment]
I can try it again on Monday, it looks like you updated the repo above.

https://github.com/AntonKosenkoDX/nuget-refs/commit/0ec315d5686cf8e5e6edea6cfe2fd6ac8be91542

**Comment by AntonKosenkoDX** [comment]
Ok, thanks!

**Comment by jonathanpeppers** [comment]
So it's been a little while since I've used a `.nuspec`, but I just fixed everything a bit and it works for me.

See: https://github.com/AntonKosenkoDX/nuget-refs/pull/1

Notes:
* Use `dotnet pack` instead of `.nuspec` -- it might be easier? I would just pack the top level assembly and add extra files as needed.
* If you use a `ref` folder actually put reference assemblies in there. (see [docs](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#producereferenceassemblyinoutdir))
* When I did a build, there was no reference added to `MyUtility.dll`, and it was in fact not in the MSBuild `.binlog` at all -- I added to the `.nuspec` to add it
* If you have a reference assembly, you need to put the `.aar` file next to it, for that to work.

I suspect some of these details would have gone away with `dotnet pack`. Hope that helps!

**Comment by AntonKosenkoDX** [comment]
@jonathanpeppers thanks for your PR. 
But I feel that you're still misunderstanding me. I know that if I add references to `.nuspec` file, it will work. 
As I mentioned in first post, I want to hide API from `MyUtilities.dll` in end-user apps. I use way described in this guide [Multiple assemblies in one package](https://learn.microsoft.com/en-us/nuget/create-packages/select-assemblies-referenced-by-projects#not-recommended-multiple-assemblies-in-one-package) - and it works perfectly for pure `net7.0` apps (and even for `net7.0-ios`) but leads to compilation errors in `net7.0-android`.

Here is a desired behavior:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/2052851/203114882-68b7bc17-8b64-445e-8714-f1ea3ca0055d.png">

Here is actual (with your PR):
<img width="402" alt="image" src="https://user-images.githubusercontent.com/2052851/203114009-21b879d9-9268-4cfd-bb45-6926751a66cb.png">

**Comment by jonathanpeppers** [comment]
Can you mark the types `internal`? And use `InternalsVisibleTo`?

I don't think it works for the console app either... If you `dotnet publish --self-contained -r win-x64`, for example, you don't end up with `MyUtilities.dll` in `MyConsoleApp\bin\Debug\net7.0\win-x64\publish`.

We're basically seeing the same behavior on Android, except an MSBuild task fails. With the console app it would crash at runtime in a self-contained app.

**Comment by jonathanpeppers** [comment]
There might be an underlying issue here, such as:

https://github.com/xamarin/xamarin-android/pull/7642

@AntonKosenkoDX if you put this in your main app `.csproj`, does it workaround the issue?

```xml
<PropertyGroup>
  <_ResolveReferenceDependencies>true</_ResolveReferenceDependencies>
</PropertyGroup>
```
