### ISSUE TITLE
Building IOS Release generate error "the selected execution mode is not supported for .NET projects"

### ISSUE THREAD

**Issue by sofyaol** [dotnet/maui#11368]
### Description

When I try to build my Release project on IOS it generate error with message: "Can not execute {projectpath}/bin/Release/net6.0-ios/ios-arm64/{projectname}.exe. The selected execution mode is not supported for .NET projects."
But I don't have some troubles by Debug Mode or building publish .ipa with Terminal line "dotnet publish -f:net6.0-ios -c:Release"

### Steps to Reproduce

1. Create a new MAUI project 
2. Modificate Info.plist and .csproj for Release
3. Run Release on IOS Simulator 

### Link to public reproduction project repository

https://github.com/sofyaol/MAUIReleaseError

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16

**Comment by jfversluis** [comment]
Could you maybe add a little bit more about what you are trying to do here?

You are trying to publish an iOS app? But you're talking about an exe file? Because a exe file is very specific to Windows. Also, I see a lot of very Windows specific libraries in there. 

What are you trying to build? And how did you end up with this situation, what steps did you take? 

Thanks!

**Comment by sofyaol** [comment]
On the toolbar of VS for Mac I choose Release from the Solution Configurations list and run with arrow button. On Output, I see that the build was successful, but it doesn't run on the simulator and gives an error about which I wrote earlier.
And I also don't undestand why it says about exe file.

**Comment by samirgcofficial** [comment]
+1 There's lot's of problem in release publish iOS on MAC OS VS 2022. We want a perfect way to release the iOS app This doc is taking me to nowhere. https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/overview?view=net-maui-7.0

**Comment by mphill** [comment]
**Repo steps:**

1. Create a new MAUI app on VS Mac.  
2. Attempt to run the app in the **simulator** with **release** selected

App will not run, and the error "the selected execution mode is not supported for .NET projects" is displayed

**Comment by Eilon** [comment]
@Redth - move to xamarin-macios?

**Comment by F-Goncalves** [comment]
I get the same problem "the selected execution mode is not supported for .NET projects" when trying to deploy in Release on Android Emulator. Is this a VS Mac issue?

**Comment by mphill** [comment]
This bug was reported here https://github.com/dotnet/maui/issues/8894 over 7 months ago and closed although it was **never** fixed.

**Comment by Kapusch** [comment]
Hi, apparently this is a known bug, and the workaround for this is simple.
In a Release configuration, you can run the app by clicking on "Start Without Debugging" under the "Debug" menu tab:
<img width="238" alt="image" src="https://github.com/dotnet/maui/assets/9576733/d1383937-2cde-4aaf-a7b2-8b4dcade6665">

The reason why it doesn't work when using the play button is because it runs in debug mode.
However, debugging is NOT supported in Release configuration!

I have open a ticket for Visual Studio [here](https://developercommunity.visualstudio.com/t/The-selected-execution-mode-is-not-suppo/10358767).

**Comment by kocevilija** [comment]
I am trying to create different configurations for my dotnet maui project "Debug-DEV" and "Debug-PROD. 

I am copying the existing "Debug" configuration and renaming it in order not to mess up something in the solution. After I have created everything I have tried to build Android using one of the new configurations and it works, where the same on iOS is not working and I am getting the error ```"Can not execute {projectpath}/bin/{Configuration}/net7.0-ios/iossimulator-x64/{projectname}.exe. The selected execution mode is not supported for .NET projects."``` but the build is succeeded with `0 failed`.

Can anyone help me how to fix this problem without selecting "Debug -> Start without debugging"(this works but I cannot debug the application)?

**Comment by Kapusch** [comment]
@kocevilija , did you add `<MtouchDebug>true</MtouchDebug>` under each of your debug configuration ?

**Comment by kocevilija** [comment]
I have just added it and it works! Thank you @Kapusch

**Comment by jinxinjuan** [comment]
Verified this issue with VS for Mac 17.6.1 (build 452). Can repro on iOS platform with sample project. 
[MAUIReleaseError](https://github.com/sofyaol/MAUIReleaseError)

Note: In a Release configuration, you can run the app by clicking on "Start Without Debugging" under the "Debug" menu tab:

**Comment by jfversluis** [comment]
Looks like there is a workaround and this is a bug in Visual Studio rather than the .NET MAUI SDK.

Bug tracking this is here: https://developercommunity.visualstudio.com/t/The-selected-execution-mode-is-not-suppo/10358767
