### ISSUE TITLE
Circular progress animation of RefreshView keeps spinning even after all data has been successfully loaded

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/maui#11388]
### Description

Circular progress animation of `RefreshView` keeps spinning even after all data has been loaded successfully and asynchronously from `https://www.montemagno.com/monkeys.json`. 

### Steps to Reproduce

Visit [my repo](https://github.com/pstricks-fans/RefreshViewBug).
The `readme.md` describes the details.

### Link to public reproduction project repository

https://github.com/pstricks-fans/RefreshViewBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

### Did you find any workaround?

No idea.

### Relevant log output

```shell
No relevant log available.
```

**Comment by AndreasReitberger** [comment]
I checked your repro. In the `MonkeyViewModel`, at line 45 you are setting `isRefreshing = false`, however you need to set `IsRefreshing = false`

Can you try if it works with that modification?

**Comment by pstricks-fans** [comment]
> I checked your repro. In the `MonkeyViewModel`, at line 45 you are setting `isRefreshing = false`, however you need to set `IsRefreshing = false`
> 
> Can you try if it works with that modification?

Oh my ghost. It now works as expected. Thank  you. I close this stupid mistake. :-)
