### ISSUE TITLE
.NET MAUI : Error CS0012- The type 'object' is defined in an assembly that is not referenced. You must add a reference to assembly 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

### ISSUE THREAD

**Issue by deepanshujn112** [dotnet/maui#11399]
**Description** 

I am adding a binding native library (library.dll ) to the .NET MAUI App. And when I am invoking the functions of this library, I am facing these errors.
Error CS0012: The type 'object' is defined in an assembly that is not referenced. You must add a reference to assembly 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

I have tried adding this Xamarin.iOS package from NuGet packages, but I did not find this package.

**Software I am using**
Visual Studio : 17.3.8 (version)
Xcode : 14.0.1 (version)
MacOS : 12.5.1 (version)

**Platform** 
 iOS

**Comment by mattleibow** [comment]
This native binding library... was this a classic Xamarin iOS binding? Not sure that it is compatible with net6.0-ios because of several large API breaks.

Are you able to create a net6.0-ios binding library and use that?

**Comment by deepanshujn112** [comment]
I converted Objective-C library with Objective Sharpie tool by parsing the header files with Xamarin iOS binding project. That binding project generates a native library (. dll file).  And then integrated that binded library in .NET MAUI Application (with net6.0-ios). When I run that project I am facing above issue.

 Is Xamarin iOS binding library compatible with .NET MAUI Apps(with net6.0-ios) ?

**Comment by mattleibow** [comment]
> Is Xamarin iOS binding library compatible with .NET MAUI Apps(with net6.0-ios) ?

Unfortunately not as there were several api breaks to take advantage of brand new os and language features as well as to fix long standing bugs.

@rolfbjarne @dalexsoto do we have docs on what to do to turn a normal ios lib into a binding lib?

**Comment by deepanshujn112** [comment]
> @rolfbjarne @dalexsoto do we have docs on what to do to turn a normal ios lib into a binding lib?

Thanks for the reply @mattleibow, we have documentation on Xamarin.iOS binding and we have converted normal iOS library to binding library(.dll). I can see same [process](https://learn.microsoft.com/en-us/events/dotnetconf-focus-on-maui/binding-native-libraries-for-dotnet-maui) for .NET MAUI but I'm not so sure After integrating that binding library we are facing above issue. Do we have different process for .NET MAUI. If yes then please let us know.

Thanks once again.

**Comment by rolfbjarne** [comment]
> @rolfbjarne @dalexsoto do we have docs on what to do to turn a normal ios lib into a binding lib?

The easiest is probably to execute `dotnet new iosbinding` to create a new binding project from a template, and then copy over stuff from the old binding project.

In any case, the main difference between a normal ios lib and a binding lib is that IsBindingProject is true:

https://github.com/xamarin/xamarin-macios/blob/ce895603a52ee27c2f2a6c424d1c3f0c6901d5a0/dotnet/Templates/Microsoft.iOS.Templates/iosbinding/iOSBinding1.csproj#L7

**Comment by deepanshujn112** [comment]
> > @rolfbjarne @dalexsoto do we have docs on what to do to turn a normal ios lib into a binding lib?
> 
> The easiest is probably to execute `dotnet new iosbinding` to create a new binding project from a template, and then copy over stuff from the old binding project.
> 
> In any case, the main difference between a normal ios lib and a binding lib is that IsBindingProject is true:
> 
> https://github.com/xamarin/xamarin-macios/blob/ce895603a52ee27c2f2a6c424d1c3f0c6901d5a0/dotnet/Templates/Microsoft.iOS.Templates/iosbinding/iOSBinding1.csproj#L7

I am binding iOS Library with Objective Sharpie and it generates ApiDefination.cs and Structs.cs files. I can use these files in creating Xamarin.ios binding library but I cannot use and copy the stuffs of these into the .NET MAUI binding library because there is no such files and also file structure is completely different.

**Comment by mattleibow** [comment]
I think you may have created a maui class library, you may need to create an "ios binding library":

![image](https://user-images.githubusercontent.com/1096616/204631279-9f370df2-fcc7-422f-a458-dcdd0a7a0cd3.png)


> Note the weird icon

The result is this:

![image](https://user-images.githubusercontent.com/1096616/204631406-c497b8d2-852e-4327-ad04-3af598dae145.png)

**Comment by deepanshujn112** [comment]
> I think you may have created a maui class library, you may need to create an "ios binding library":
> 
> ![image](https://user-images.githubusercontent.com/1096616/204631279-9f370df2-fcc7-422f-a458-dcdd0a7a0cd3.png)
> 
> > Note the weird icon
> 
> The result is this:
> 
> ![image](https://user-images.githubusercontent.com/1096616/204631406-c497b8d2-852e-4327-ad04-3af598dae145.png)

I have converted normal iOS native library into iOS binding library and using it in Xamarin.iOS apps, with the help of Objective Sharpie.

But now I want to use my iOS native library into .NET MAUI apps. Is there any way to convert iOS native library into MAUI Class library, so that I can use in .NET MAUI apps?

**Comment by mattleibow** [comment]
@deepanshujn112 it depends on what you are trying to do, but let me throw an option out.

If you just want to use your iOS binding library in the iOS part of maui, then you can just do a normal project reference with a condition. So when you add the project reference in the IDE, save the projects and then edit the csproj to add this condition:

```xml
<ProjectReference Include="../path/to/binding.csproj" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'" />
```

You can then use the binding library in parts of the app that are ios-specific or in the `#if IOS` sections.
