### ISSUE TITLE
Created an APK for Android - My phone says "This type of file is not supported"

### ISSUE THREAD

**Issue by joaquim66** [dotnet/maui#11391]
### Description

Hello all.

I'm new to Maui and i have an issue installing APK directly on mobile:

Created an working .net maui on my computer.
Can run it in the emulator, but now, because i'm new to maui, i have to test it on my Samsung A52S phone.

So, i created a APK, aimed it (just to be sure) for Android 12.0 (the SO of my mobile), but with a minimal Android Version 5.0.
Created the APK with command "dotnet build -f net6.0-android".
It created some files on Bin folder, one of them was: com.nameOfMyApplication.app.apk.

When i tried to instal it on my mobile it asked me:
"Do you want to install this App"
I press "Install" and i receive the message: "The app wasn't intalled because the package seems invalid".

Any ideas.
Thank you,
Joaquim

### Steps to Reproduce

-

### Link to public reproduction project repository

-

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No

**Comment by Taiizor** [comment]
Because the package is not signed.

**Comment by laconical77** [comment]
You need to sign and [publish](https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/overview) the app before it can be installed on a phone. File->Publish command in VS. Once a build has been published you can distribute it from the same area (still as an apk file)
