### ISSUE TITLE
Android precompile failed for visualstudio.rpccontracts.dll

### ISSUE THREAD

**Issue by mikiplaygames** [dotnet/maui#11397]
### Description

![image](https://user-images.githubusercontent.com/95536396/202036103-f53ba9dc-b1c7-4ac3-ab7f-515e33449d36.png)

Hi, im having weird problem when trying to rebuild my maui app for publish in release mode. As you can see im getting ^ this error. I can't even publish app for windows

![image](https://user-images.githubusercontent.com/95536396/202198007-1a165087-3315-4599-ad5a-64ebf5edd986.png)
![image](https://user-images.githubusercontent.com/95536396/202198023-1d5cdf4c-69ec-4102-a8e7-115664340b1e.png)

It crashes on MonoAOTCompiler

Pls help

### Steps to Reproduce

Don't know, just created normal maui project and started working (all default settings)

### Link to public reproduction project repository

https://github.com/mikiplaygames/ProjektTales

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-android

**Comment by PureWeen** [comment]
Do you need to include this nuget?

https://github.com/mikiplaygames/ProjektTales/blob/main/ProjektTales.csproj#L76

**Comment by mikiplaygames** [comment]
Thanks it worked 😎 🤝 😎 
unfortunately now most of text in my app is invisible + when i try to use entry it crashes
ill try to deal with it rn

**Comment by mikiplaygames** [comment]
kay there is something with binding
what im getting in debug mode: (expected outcome)
![image](https://user-images.githubusercontent.com/95536396/202307141-cbb747fa-2602-4865-94f0-a4363795f553.png)
what im getting in release mode: (broken outcome)
![image](https://user-images.githubusercontent.com/95536396/202307507-91623feb-d918-45a5-b4f1-4f93ec1b47ec.png)

**Comment by rachelkang** [comment]
Hi, @mikiplaygames - glad the nuget worked for you! If you're still experiencing the issue you described in your most recent comments, please open a new, separate issue for it so can track it appropriately. Thank you!
