### ISSUE TITLE
I found a similar Xamarin based on Flutter

### ISSUE THREAD

**Issue by qcjxberin** [dotnet/maui#114]
https://github.com/adospace/reactorui-xamarin

**Comment by Happypig375** [comment]
Still missing the platform-independent looks though.

**Comment by davidortinau** [comment]
Thx @qcjxberin, I've exchanged messages previously with Adolfo, the author of the library. 

Have you used ReactorUI? 

What do you like and dislike about it?

**Comment by qcjxberin** [comment]
@davidortinau  I have used it, and I like his way of doing it, because I have used flutter to develop apps, but not Xamarin, so it may be more acceptable for ReactorUI usage. But at present, I have encountered a problem in the use process that the hot update cannot be used normally, and the other is that there are too few functions and some components.

**Comment by viktorszekeress** [comment]
Worked with WPF, WP8, UWP, Xamarin and now Flutter.
The idea about State in Flutter is not the most elegant way of doing it. Considering the Flutter's approach of rendering the frame, State was the only option they had.

We don't NEED to bring these ugly things to Xamarin, Xamarin doesn't rebuild entire Visual tree for each frame.
