### ISSUE TITLE
[iOS]No Keyboard popup on Entry and Editor focus 

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#11406]
### Description

Whenever the Entry or Editor gets focus the Keyboard does not popup. Hence it's impossible to enter Text. 

### Steps to Reproduce

Run the repro project and try to enter text in the entry and editor controls. 

### Link to public reproduction project repository

https://github.com/HobDev/MauiBugs/tree/EditorBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

NO

**Comment by HobDev** [comment]
As if [this](https://github.com/dotnet/maui/issues/4792) was not enough to frustrate the developers.

**Comment by KieranMaclagan** [comment]
Haven't been able to test this on a physical device, but can confirm I'm seeing the same behaviour on the iOS simulator.

**Comment by samirgcofficial** [comment]
+1 Same goes in the real device too can confirm it.

**Comment by PureWeen** [comment]
@KieranMaclagan @HobDev I think this is just a quirk of the iOS Simulator

I tested your sample on a physical device and the keyboard opens. A lot of times when using the simulator (even through xcode) I have to go to I/O -> KEyboard => Toggle Software Keyboard.

After doing that it starts to work as expected. 

@samirgcofficial can you open a new issue or attach a repro?

**Comment by KieranMaclagan** [comment]
@PureWeen Good to know. Thanks for the follow-up and extra info!

**Comment by HobDev** [comment]
@PureWeen  thanks for the quick response. Yes the issue was with the settings in the Simulator. Glad to see that now I can close the keyboard with return or done key which was not possible in the previous release (.NET 6 )
