### ISSUE TITLE
Radio button loses initial 'IsChecked=True' value when another radio button also has 'IsChecked=True'

### ISSUE THREAD

**Issue by andycambo** [dotnet/maui#11418]
### Description

There is an issue when trying to use multiple radio buttons on a page.

If there are two radio buttons set to 'IsChecked=True' then only the last button in the view will remain true - despite them being given different GroupNames and in separate parent containers.
![image](https://user-images.githubusercontent.com/25864071/202220945-8611a651-5d55-43bd-8f6f-dbb5e8bd9148.png)

Initial thoughts are that it *appears* that all the radio buttons on the view are treated as one group (tried to give the control different GroupNames as shown in example) and therefore, as the view is rendered in order, only the last radio button with IsChecked=True will keep its initial value, earlier radio buttons will be set to be unchecked.
![image](https://user-images.githubusercontent.com/25864071/202224294-7da9daf0-08b3-437a-8666-60fb6258b298.png)

In Android, the expected result is shown. I have been unable to test the remaining platforms.
![image](https://user-images.githubusercontent.com/25864071/202222376-d03752fd-4045-4847-874c-2b2daf66a99d.png)

### Steps to Reproduce

Create a new solution.
Add to view multiple radio buttons with IsChecked=True

```
<VerticalStackLayout Spacing="25">

            <VerticalStackLayout>
                <RadioButton GroupName="First" Content="First" IsChecked="True"/>
            </VerticalStackLayout>

            <VerticalStackLayout>
                <RadioButton GroupName="Middle" Content="Middle" IsChecked="True"/>
            </VerticalStackLayout>

            <VerticalStackLayout>
                <RadioButton GroupName="Last" Content="Last" IsChecked="True"/>
            </VerticalStackLayout>

</VerticalStackLayout>
```

### Link to public reproduction project repository

https://github.com/andycambo/MauiRadioButtonBugExample

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

**Comment by danielancines** [comment]
I got the shame problem here, when you create two separated layouts under the same BindingContext, the property RadioButtonGroup.SelectedValue works fine, but, even if you use different RadioButtonGroup.GroupName, occurs the same problem as @andycambo mentioned above, only the second pair of RadioButtons respect the initial binding, the first loaded unchecked.

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Maui.RadioButtonBindingIssue.App.MainPage">

    <ScrollView>
        <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            VerticalOptions="Center">
            <HorizontalStackLayout RadioButtonGroup.GroupName="Z"
                                   RadioButtonGroup.SelectedValue="{Binding ImportExcelSelectedOption}">
                <RadioButton Content="Option 1" Value="grupo_cliente"/>
                <RadioButton Content="Option 2" Value="grupo_primeiro_depois_mft" Margin="10,0,0,0"/>
            </HorizontalStackLayout>

            <HorizontalStackLayout RadioButtonGroup.GroupName="Z1"
                                   RadioButtonGroup.SelectedValue="{Binding ExportExcelSelectedOption}">
                <RadioButton Grid.Column="2"
                             Content="Option 1" Value="grupo_cliente"/>
                <RadioButton Grid.Column="3" Margin="10,0,0,0"
                             Content="Option 2" Value="grupo_primeiro_depois_mft"/>
            </HorizontalStackLayout>
            <Button Clicked="Button_Clicked" Text="tes"/>
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
`

**Comment by mouralabank** [comment]
Same problem here.

**Comment by hartez** [comment]
Apparently this is a known bug in WinUI: https://github.com/microsoft/microsoft-ui-xaml/issues/2081

And I can reproduce that issue in UWP as well, so it's been a problem for a while. Not sure if we've ever run into this in Forms; if not, I wonder what we did that prevented it.

**Comment by hartez** [comment]
Okay, I think we can hack around this in .NET MAUI until https://github.com/microsoft/microsoft-ui-xaml/issues/2081 gets fixed. It's a little gross, but I think it'll work:

1. When creating the platform RadioButton in RadioButtonHandler.Windows, we'll need to set the native GroupName property to something unique (maybe a GUID). That will prevent the native IsChecked conflicts.
2. At some point after the native controls have resolved their containers, we can clear the native GroupName property. It seems to stop being a problem after the initial layout, so I'm betting if we cleared the property after the first PlatformArrange call in RadioButtonHandler.Windows we'd be good.

**Comment by jstedfast** [comment]
Just confirmed with VS 2022 17.5.0
