### ISSUE TITLE
Entry - Different font for placeholder when password mode is enabled

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/maui#11428]
### Description

I found that when I set IsPassword, the Placeholder font is changed.

I have attached pictures, I can not understand whether it is a different font, or the spacing between the letters or size of font has changed, but if you quickly change the IsPassword, you can see how the placeholder changes.

![password](https://user-images.githubusercontent.com/4385716/202395957-927d3216-91d7-4139-8e03-0dcd2dd21bae.jpg)

https://user-images.githubusercontent.com/4385716/202398682-7af1f2a6-567a-46f2-848e-72d79d2f6c13.MOV

### Steps to Reproduce

1. Create Entry
2. Set custom Font
3. Set custom front size
4. Set Placeholder Color
5. Set Placeholder text
6. Set IsPassword to true
7. Check font

### Link to public reproduction project repository

no

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

**Comment by hartez** [comment]
@KSemenenko also, your video doesn't seem to play - can you try uploading it again?

**Comment by KSemenenko** [comment]
Let me create new one

**Comment by KSemenenko** [comment]
this is test project. [MauiApp1.zip](https://github.com/dotnet/maui/files/10047701/MauiApp1.zip)

and this is screenshots,
so IsPassword change font at all


<img width="394" alt="Screenshot 2022-11-19 at 19 14 15" src="https://user-images.githubusercontent.com/4385716/202865585-bd8c330c-596e-4008-8485-74930cd3043c.png">
<img width="394" alt="Screenshot 2022-11-19 at 19 14 11" src="https://user-images.githubusercontent.com/4385716/202865586-7ea6d188-3638-44eb-a28d-c0e783e5a870.png">

**Comment by KSemenenko** [comment]
@hartez I realised that video will be avaialalbe after 6-8 minutes. seesm it take some time for loading.
anyway, I made screenshots and test project. 

I found most different font, by buttoin I just invert IsPassword for fields.
``` xaml
<Entry FontFamily="RubikDistressedRegular"  Placeholder="Password" FontSize="16" x:Name="EntryBox1"/>
<Entry FontFamily="RubikDistressedRegular"  Placeholder="Password" Text="My Complicated Password" FontSize="16" IsPassword="True" x:Name="EntryBox2"/>
```

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue in current main branch:
<img width="457" alt="Captura de pantalla 2022-11-25 a las 13 53 19" src="https://user-images.githubusercontent.com/6755973/203990203-097e38d9-19e6-4f3d-9dc0-5f1c03169e48.png">

**Comment by KSemenenko** [comment]
when you click on the button (to change the IsPassword) are the fonts the same in the two comments?

**Comment by KSemenenko** [comment]
For me, when IsPassword is enabled, it uses the default font and not the one I set back in the Entry settings.

**Comment by KSemenenko** [comment]
do you have new versions of maui?

**Comment by rachelkang** [comment]
confirming that I'm able to reproduce this issue on the current main branch. Will continue investigating!
