### ISSUE TITLE
Button with shadow style does not appear if it is "IsVisible = false" initially

### ISSUE THREAD

**Issue by Nibby** [dotnet/maui#11427]
### Description

If a `Button` is:
- Configured to `IsVisible="False"` initially
- And it has a `Shadow` style applied to them in `Styles.xaml`

Toggling the button's visibility to `True` will not make the button show up properly. But if the button with the shadow is visible initially, toggling its visibility works correctly. 

I have tested this on Android and macOS (Catalyst). Only Android appears to be exhibiting this issue. I have not tested this on iOS or Windows, or any other platforms.

My MAUI Workload versions are:
```
Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
wasm-tools                 7.0.0/7.0.100         SDK 7.0.100        
maui-maccatalyst           7.0.49/7.0.100        SDK 7.0.100        
maui-ios                   7.0.49/7.0.100        SDK 7.0.100        
maui-android               7.0.49/7.0.100        SDK 7.0.100        
maui                       7.0.49/7.0.100        SDK 7.0.100   
```

### Steps to Reproduce

In the linked reproduction project:
1. Launch it on Android
2. Press "Make Me Visible"

**Expected**
The button `I'm Visible By Default` should disappear, and in its place `I'm NOT Visible By Default` appears.

**Actual**
The button `I'm Visible By Default` disappears, spacing is reserved for a button, but `I'm NOT Visible By Default` does not appear.

**Notes**
If you disable the shadow style for this button, the behaviour will be correct.

### Link to public reproduction project repository

https://github.com/Nibby/MAUI-Bug-1

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 and up

### Did you find any workaround?

Best workaround for the time being is to disable the shadow styling on any buttons that must be invisible on the page initially.

Another dirty-but-proven workaround is to make sure all buttons are visible on the page when it is presented, before making them invisible again.

**Comment by espenrl** [comment]
I can confirm the issue exists on WinUI too. MAUI in .NET 7 / Windows 10.

**Comment by BioTurboNick** [comment]
I believe isVisible == false is causing a host of problems; I presume it's saving time by not processing things that aren't seen, but they aren't redone when it becomes visible.

**Comment by mdbill** [comment]
Similarly...
I have buttons with shadows defined in xaml   When I change IsVisible to false, it disappears, but the button shadow is left behind.  
WinUI, .net6 and 7

Workaround: wrap the buttons in verticalstacklayouts and make the layout not IsVisible.

**Comment by LukasKuchta** [comment]
Hi, same behaviour for mee. As @mdbill  said, the workaround is wrap element with shadow into another layout and set visibilit for this parent.
