### ISSUE TITLE
Some lifecycle events under macOS are not working

### ISSUE THREAD

**Issue by paratype-fonts** [dotnet/maui#11423]
### Description

When minimizing/hiding a maui app, Window.Stopped event:
1. Is not fired in Release mode
2. Is not fired in Debug mode when using mouse click on the yellow button
3. Is fired in Debug mode when using Cmd + H shortcut

### Steps to Reproduce

See the description...

### Link to public reproduction project repository

https://github.com/paratype/MauiLifecycleEvents

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.6

### Did you find any workaround?

No

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6 (build 1575). Not repro on macOS platform with sample project.
[MauiLifecycleEvents-main.zip](https://github.com/dotnet/maui/files/12024130/MauiLifecycleEvents-main.zip)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6 (build 1575). Not repro on macOS platform with sample project.
[MauiLifecycleEvents-main.zip](https://github.com/dotnet/maui/files/12024130/MauiLifecycleEvents-main.zip)

**Comment by Zhanglirong-Winnie** [comment]
Sorry, this was closed by mistake.
