### ISSUE TITLE
CollectionView inside RefreshView causes layout problems on iOS

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#11440]
### Description

![maui_ios_layout_bug](https://user-images.githubusercontent.com/114725843/202462421-d71155d5-862f-4b2a-a3d4-26d5423abcae.gif)

If you put a CollectionView inside a RefreshView and switch from portrait to landscape and back on iOS, the layout gets messed up.

### Steps to Reproduce

""

### Link to public reproduction project repository

https://github.com/dotnet/maui/issues/11363

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS16 and up

**Comment by owl-guy** [comment]
It gets even worse if you put a grid around it...

**Comment by Redth** [comment]
This seems to be an issue with controls inside the CV, not the collectionview itself.  I switched the usage of Frame to Border and the issue resolved.

**Comment by owl-guy** [comment]
> This seems to be an issue with controls inside the CV, not the collectionview itself. I switched the usage of Frame to Border and the issue resolved.

Wait what? That doesn't make it better! It's still a problem. You can't simply close this ticket because "Hey, it works with Border"

**Comment by RobTF** [comment]
@owl-guy you have it all wrong, it's just a documentation issue;

We clearly just need a matrix of which controls can appear on the screen with which other controls, and specifically how they are allowed to do so. Maybe it's a per-platform thing too (certainly the RefreshView stuff is).

;)

**Comment by krookdfinger** [comment]
Wrap the collection view in contentview and it will work

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="CollectionViewDemo.MVVM.Views.DataView"
             xmlns:DataTemplates="clr-namespace:CollectionViewDemo.Selectors"
             Title="DataView">

    <ContentPage.Resources>
        <DataTemplates:ProductDataTemplateSelector x:Key="ProductTemplates" />
    </ContentPage.Resources>

    <RefreshView Command="{Binding RefreshCommand}"
                 IsRefreshing="{Binding IsRefreshing}">
        **<ContentView>**
            <CollectionView ItemsSource="{Binding Products}"
                            ItemTemplate="{StaticResource ProductTemplates}">
    
            **</CollectionView>**
        </ContentView>
    </RefreshView>

</ContentPage>
`
