### ISSUE TITLE
Changing ApplicationDisplayVersion in .NET MAUI project causes problems

### ISSUE THREAD

**Issue by mnwhle** [dotnet/maui#11464]
### Description

Hi,
I know this is a duplicate, see e.g. #3690. There are possibly a few more duplicates. While they all are closed, this annoying bug is still not fixed.

### Steps to Reproduce

1. Create new .NET MAUI App from template.
2. Go to project settings and change the Application Display Version to 1.1 (I guess you can use any other value except 1.0).
3. Save changes.
4. Close the solution.
5. Open the solution folder in explorer and delete **.vs, bin, obj** folders and **MauiApp1.csproj.user** file in the solution folder and all sub folders. (These folders and file are normally ignored by git, so deleting them should not cause any problem.)
7. Open the solution in Visual Studio again.
8. You will get Error NU1105 Unable to read project information for 'MauiApp1': Sequence contains more than one element.

![image](https://user-images.githubusercontent.com/104074902/202598427-4ba0aa21-2677-4293-9917-e83b61bcd7ba.png)

Tested in Visual Studio Community 17.4.0, 17.4.1.
The issue appears in Windows 10, 11 22H2.
In Windows 10 21H2 the issue does not appear.

### Link to public reproduction project repository

https://github.com/mnwhle/MauiApp1

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All default platforms in new MAUI project

### Did you find any workaround?

Change Application Display Version back to 1.0
-or-
drop Windows target platform by commenting out
`<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>` in *.csproj file
then rebuild the solution.

**Comment by mattleibow** [comment]
I think this is a bug in VS where setting properties causes some terrible things to happen in the csproj and then it cries as a result: https://github.com/mnwhle/MauiApp1/blob/master/MauiApp1/MauiApp1.csproj#L33-L63

Try deleting this and editing the one in the first section.

Also can you open this bug using the VS Feedback tool so the IDE team can fix this?

**Comment by mnwhle** [comment]
Thank you for answering. The issue is posted as [a possible bug in VS](https://developercommunity.visualstudio.com/t/Changing-ApplicationDisplayVersion-in-N/10206931).
