### ISSUE TITLE
Private EventHandlers throw an exception on XAML-defined custom control, inherited by other control

### ISSUE THREAD

**Issue by maiia-kuzmishyna** [dotnet/maui#11467]
### Description

When I define a custom control in XAML that subscribes to some event handlers and those event handlers are private (ParentControl), and then I have a different control inheriting ParentControl (ChildControl) - 
Application crashes with exception: 
"No method ParentButton_OnClicked with correct signature found on type ProtectedEventHandlers.ChildButton".
If I just use ParentButton instead of ChildButton, or make event handler protected - works without errors.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/113444284/202634483-db93aee0-239b-455a-9935-bde37caf265a.png">

### Steps to Reproduce

1. Create a blank MAUI App project
2. Define a control in XAML that inherits f.e. Button: ParentButton
3. Subscribe to Clicked event in XAML of ParentButton
4. Define a control (XAML  or C#) ChildButton that inherits from ParentButton
5. Use ChildButton f.e. in MainPage
6. Deploy the app

### Link to public reproduction project repository

https://github.com/maiia-kuzmishyna/MAUI-ProtectedEventHandlers

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 15,16; Windows 11; Android 31

### Did you find any workaround?

Make Event Handler protected instead of private.

**Comment by rachelkang** [comment]
cc @mattleibow

**Comment by mattleibow** [comment]
This seems interesting @StephaneDelcroix... It appears the derived type is looking to attach the event from the derived type to the base, but the event handler is in the base...

Not sure if that makes sense, but the repro shows an exception for me in the latest net7.0 code too.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11.

**Windows:** Application crashes with exception
![image](https://github.com/dotnet/maui/assets/97647558/492163c2-d4cf-4ba0-b756-b3d3cf11e473)

**Android 13.0-API33:** Application works well.
![image](https://github.com/dotnet/maui/assets/97647558/721a2d13-1c2b-48c9-b855-c765ae53921b)

**iOS 16.4**: Application deploy successfully, but there is no response when click "Parent Button" button.
![image](https://github.com/dotnet/maui/assets/97647558/0ae1eb4e-53bf-4aaa-9ca7-50ced217082b)

**Comment by StephaneDelcroix** [comment]
> This seems interesting @StephaneDelcroix... It appears the derived type is looking to attach the event from the derived type to the base, but the event handler is in the base...
> 
> Not sure if that makes sense, but the repro shows an exception for me in the latest net7.0 code too.

If I understand this correctly, you would get the same result from c#. if you want to access methods from derived types, `private` isn't the keyword you're after.
