### ISSUE TITLE
[MacOS]  File picker returns null on new MacOS 13

### ISSUE THREAD

**Issue by HapkidoNinja** [dotnet/maui#11462]
[MAUI-Sample_FilePicker.zip](https://github.com/dotnet/maui/files/10036907/MAUI-Sample_FilePicker.zip)

This sample app works smoothly on MacOS 12, but fails to return the selected file on the newly released MacOS 13. Would welcome any indication of whether this is a known issue. 

In the interim, I will likely have to use a platform specific code extension, which I would rather avoid.
Thanks.

**Comment by rachelkang** [comment]
Duplicate of #11088
