### ISSUE TITLE
iOS build: the "-gcc_flags -dead_strip" Mtouch argument doesn't work

### ISSUE THREAD

**Issue by vasile135** [dotnet/maui#11477]
### Description

Have a working Xamarin Forms application that relies on some iOS native static libraries.
Trying to migrate the solution to .NET MAUI.
When adding the same static libraries with the same configurations and the same gcc flag, the MAUI application build fails with:
`Error: clang++ exited with code 1:
duplicate symbol '_crypto_onetimeauth_verify' in:
    /Users/hetzner/Desktop/TestIndyLibraries/iOSBindingLibrary/bin/Debug/net7.0-ios/iOSBindingLibrary.resources/libsodium.a(libsodium_la-crypto_onetimeauth.o)
    /Users/hetzner/Desktop/TestIndyLibraries/iOSBindingLibrary/bin/Debug/net7.0-ios/iOSBindingLibrary.resources/libzmq.a(src_libzmq_la-tweetnacl.o)`
In Xamarin, I believe that the error is addressed by the following Mtouch extra argument:
<MtouchExtraArgs>-gcc_flags -dead_strip -v</MtouchExtraArgs>

### Steps to Reproduce

1. In order to add native references, added an iOS Binding project to the MAUI solution. 

2. Added native references (one of it is C++):
![image](https://user-images.githubusercontent.com/58006892/202736561-386fe476-fcff-4c91-83ec-a9ea845a0606.png)

3. Added an additional Mtouch argument to the application project:
<MtouchExtraArgs>-gcc_flags -dead_strip -v</MtouchExtraArgs>

4. Installed the nuget package that uses these native libraries (Hyperledger.Aries).

5. When trying to build, the following error occurs:
`Error: clang++ exited with code 1:
duplicate symbol '_crypto_onetimeauth_verify' in:`

From here I conclude that the gcc flag was not applied.

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
cc @rolfbjarne

**Comment by rolfbjarne** [comment]
@vasile135 could you get a [binary build log](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) and attach it here?

**Comment by vasile135** [comment]
> @vasile135 could you get a [binary build log](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) and attach it here?

Sure.
[msbuild.zip](https://github.com/dotnet/maui/files/10065512/msbuild.zip)

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#16861
