### ISSUE TITLE
Add permission request for POST_NOTIFICATION to essentials for Android 13 and up

### ISSUE THREAD

**Issue by norton287** [dotnet/maui#11476]
### Description

Android 13 now requires a new permission, POST_NOTIFICATION, to allow notifications in the notifications tray.  I did an extension to add it but having it built in would be nice and easier as it is not going away.

Here is the info on it 

https://developer.android.com/develop/ui/views/notifications/notification-permission

### Public API Changes

Essentials would just need to add the permission checks and request. 

### Intended Use-Case

This would probably apply to any app that uses the notifications tray.

**Comment by trampster** [comment]
Every app that uses notifications needs this, Android 13 was released 4 months ago. We had to implement this ourselves using the android sdk.

**Comment by trampster** [comment]
This is a permission that every app that uses notifications needs with android 13 which was released 4 months ago.

**Comment by Redth** [comment]
It's worth noting that you can extend the Essentials' API for your own use for any permission as well.  Take for example [ContactsRead](https://github.com/dotnet/maui/blob/main/src/Essentials/src/Permissions/Permissions.android.cs#L216-L220).

If you follow this pattern you could create something like:

```
public partial class PostNotifications : BasePlatformPermission
{
	public override (string androidPermission, bool isRuntime)[] RequiredPermissions =>
				new (string, bool)[] { (Manifest.Permission.PostNotifications, true) };
}
```

Then use it something like:

```
var result = await Permissions.RequestAsync<PostNotifications>();
```

**Comment by vallgrenerik** [comment]
> It's worth noting that you can extend the Essentials' API for your own use for any permission as well. Take for example [ContactsRead](https://github.com/dotnet/maui/blob/main/src/Essentials/src/Permissions/Permissions.android.cs#L216-L220).
> 
> If you follow this pattern you could create something like:
> 
> ```
> public class PostNotifications : BasePlatformPermission
> {
> 	public override (string androidPermission, bool isRuntime)[] RequiredPermissions =>
> 				new (string, bool)[] { (Manifest.Permission.PostNotifications, true) };
> }
> ```
> 
> Then use it something like:
> 
> ```
> var result = await Permissions.RequestAsync<PostNotifications>();
> ```

@Redth when I try your solution, I get this error:
`The current Activity can not be detected. Ensure that you have called Init in your Activity or Application class.`

Any ideas? :)

**Comment by vallgrenerik** [comment]
> > It's worth noting that you can extend the Essentials' API for your own use for any permission as well. Take for example [ContactsRead](https://github.com/dotnet/maui/blob/main/src/Essentials/src/Permissions/Permissions.android.cs#L216-L220).
> > If you follow this pattern you could create something like:
> > ```
> > public class PostNotifications : BasePlatformPermission
> > {
> > 	public override (string androidPermission, bool isRuntime)[] RequiredPermissions =>
> > 				new (string, bool)[] { (Manifest.Permission.PostNotifications, true) };
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then use it something like:
> > ```
> > var result = await Permissions.RequestAsync<PostNotifications>();
> > ```
> 
> @Redth when I try your solution, I get this error: `The current Activity can not be detected. Ensure that you have called Init in your Activity or Application class.`
> 
> Any ideas? :)

Hmm it worked using Xamarin.Essentials.Permissions instead of Microsoft.Maui.ApplicationModel

**Comment by TonyLugg** [comment]
As a work around, add this to MainActivity:

`        // Ask for permission to send notifications (required by API 33+)
        if (ContextCompat.CheckSelfPermission(this, Manifest.Permission.PostNotifications) != Permission.Granted)
        {
            ActivityCompat.RequestPermissions(this, new[] { Manifest.Permission.PostNotifications }, 0);
        }`

**Comment by DeepWorksStudios** [comment]
I hope it will be added to .net 8

**Comment by AmSmart** [comment]
@Redth Will the team be willing to accept a PR for this one?
