### ISSUE TITLE
Pasted text is shown in cleartext (not hidden) in Entry with IsPassword=true

### ISSUE THREAD

**Issue by RogerJans** [dotnet/maui#11478]
### Description

When pasting text in an Entry which has the IsPassword property set to true the text is occasionally shown in clear text (no 'bullets').
Also, in an Entry element for username - which has IsPassword=false - immediately above the password field, it is possible to
get pasted text shown as bullets.

![IsPassword property not honored_1](https://user-images.githubusercontent.com/118542451/202725975-1cd0edcb-cb6b-4f9a-a1e8-fe56bf67d4f3.png)
![IsPassword property not honored_2](https://user-images.githubusercontent.com/118542451/202725978-c4d06dfe-0a44-49db-9590-887d222a1743.png)

### Steps to Reproduce

1. Add two Entry elements, for example

    <Entry Text="{Binding Username}" Placeholder="Username" ReturnCommand="{Binding LoginCommand}" />
    <Entry IsPassword="true" Placeholder="Password" Text="{Binding Password}" ReturnCommand="{Binding LoginCommand}" />
    
2. Write and copy/paste text into the two Entry fields in a random fashion.
    Without too much effort I managed to get bullets in the non-password field and cleartext in the password-type field.
    See attached images.

### Link to public reproduction project repository

https://github.com/RogerJans/MauiIsPasswordError.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. This issue does not repro on Windows 11(22621) with provided Project:
[MauiTestApp.zip](https://github.com/dotnet/maui/files/11661462/MauiTestApp.zip)

Try to copy/paste text into the two Entry fields more times, all works as expect.
![paste](https://github.com/dotnet/maui/assets/97647558/aec1ce56-7337-420f-b0b6-d76f3cebc301)
