### ISSUE TITLE
Community Toolkit Popup closing on window minimize or maximize in .NET MAUI

### ISSUE THREAD

**Issue by deviprasad987** [dotnet/maui#11473]
### Description

I am working with the Community toolkit, after opening the Popup when I minimize or maximize the window the popup gets closed.

### Steps to Reproduce

To reproduce the issue please follow the below steps.

> Run the attached project.
> Click on the button to open the popup.
> Minimize and Maximize the window.
> See the popup is getting closed.

### Link to public reproduction project repository

https://github.com/deviprasad987/Bugs.git

### Version with bug

7.0(Current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No

**Comment by rachelkang** [comment]
This issue was moved to CommunityToolkit/Maui#774
