### ISSUE TITLE
Localization not work under iOS and Mac arm64

### ISSUE THREAD

**Issue by changguangyu** [dotnet/maui#11474]
### Description

Localization not work under iOS and Mac arm64. 
It seems that `<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>` under these platform is broken.
The satellite assemblies are not included in output app package.

Right click 'Show package contents' on output Mac app, the  satellite assemblies folder(e.g. zh-Hans)  inside MonoBundle directory are empty. There should be ProjectName.resources.dll.

### Steps to Reproduce

1. Clone this project https://github.com/VladislavAntonyuk/MauiSamples/tree/main/MauiLocalization
2. Compile with Visual Studio 17.4 with .Net 7.0 

For Windows and Android, switch language is working fine, but on iOS and Mac arm64 it's not work.

The satellite assemblies are not included in output app package.

It seems that `<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore> `is broken.

### Link to public reproduction project repository

https://github.com/VladislavAntonyuk/MauiSamples/tree/main/MauiLocalization

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

Mac x64 is working fine, arm not work

**Comment by rachelkang** [comment]
@rolfbjarne thoughts?

**Comment by rolfbjarne** [comment]
@changguangyu 

> Right click 'Show package contents' on output Mac app, the satellite assemblies folder(e.g. zh-Hans) inside MonoBundle directory are empty. There should be ProjectName.resources.dll.

Your test project doesn't seem to contain any `zh-Hans` resources, but it contains a `uk` resource, which shows up in the `uk` subdirectory in the app bundle (for iOS apps) when I build on macOS using the command line:

> MauiLocalization.app/uk/MauiLocalization.resources.dll

does it work for you if you build from the command line? If not, can you get a [binary buildlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) so that we can investigate where things go wrong for you?

**Comment by changguangyu** [comment]
This is my build command:  `dotnet build -f:net7.0-maccatalyst -c:Release /bl:msbuild.binlog`

The uk subdirectory  at  `bin/Release/net7.0-maccatalyst/maccatalyst-x64/MauiLocalization.app/Contents/MonoBundle/uk` is fine. But `bin/Release/net7.0-maccatalyst/MauiLocalization.app/Contents/MonoBundle/uk` is empty.

Here is my build log. 
[msbuild.binlog.zip](https://github.com/dotnet/maui/files/10045682/msbuild.binlog.zip)

**Comment by changguangyu** [comment]
The issue also exists in iOS App Store distribution package(but does not appear when test the app in both debug and release mode, physical device and stimulator). I think MAUI is not a proper choice for production at this time. Not because bugs of MAUI, but the difference between the final distribution package and release mode package, which makes MAUI totally not reliable.

**Comment by changguangyu** [comment]
Edit: Tested again. On iOS App Store distribution package it is another issue.  `uk` folder is not empty, but switch language not work.

**Comment by changguangyu** [comment]
Still cannot solve this issue.

**Comment by changguangyu** [comment]
Temporary Fix for Mac: Add `<RuntimeIdentifiers>maccatalyst-x64</RuntimeIdentifiers>` to force build a x64 only Mac package( Prevent build universal package for x64 and arm64).

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#16847
