### ISSUE TITLE
Fix issues on net8 branch

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#11481]
### Description

We need to enable a couple of features that were disable on net8 branch,

- Enable tizen (we need the net8 bits from the Samsung team)
- Enable  AndroidEnableMarshalMethods https://github.com/dotnet/maui/pull/11387/commits/0368b19448b6e916cf6860b7c888ddb91c46ab9d

### Steps to Reproduce

Clone .net maui repo
Checkout net8. branch

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

Android,Tizen

**Comment by jonathanpeppers** [comment]
The android side of this is fixed in https://github.com/dotnet/maui/pull/12520, 99898bc.

I believe the `net8.0` branch is building tizen, but please feel free to reopen if this isn't the case:

https://github.com/dotnet/maui/blob/b612ef9cde7cdba3948e576a2bdfbd353a0443f1/Directory.Build.props#L65
