### ISSUE TITLE
Opacity set in xaml becomes the maximum value during animation

### ISSUE THREAD

**Issue by terraslate** [dotnet/maui#11499]
### Description

In a maui control i have written which contains child images when my animation changes the opacity of a child control to 1 the value displayed is not 1 as in 100% but rather 100% of what the initial value was as specified in the xaml. So if the initial value was 0.2 then setting 1 in animation means it appears to render opacity at 0.2, setting 0.5 means it renders as 0.1.  This is counter intuitive, an opacity of 1 should mean 1. 

This came about because my initial value was 0 and no amount of changing the opacity in the animation would make it visible.

### Steps to Reproduce

            <Image x:Name="enemy1Image"
               IsVisible="true"
               Opacity="0"                                                            
               Grid.Row="0"                             
               BackgroundColor="Transparent" 
               Aspect="AspectFit" 
               WidthRequest="{Binding Source={x:Reference radarView}, Path=ImageHelperInstance.DIUWidth}"                        
               HorizontalOptions="CenterAndExpand" 
               VerticalOptions="CenterAndExpand"  
               Source="enemy1.png"
               Margin="0" />

in code behind in an animation change the opacity

enemy1Image.Opacity = 1;

It will not display.

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 API 31

### Did you find any workaround?

I am working on a workaround. Perhaps set to opacity 1 but IsVisible false.

**Comment by Domik234** [comment]
Hello, 
I've found that this happens when you set InputTransparent = true. Then the currect value of Opacity works as maximal for FadeTo.

Here is the repro - VS 17.4.1 - Tested on Android 10 (Honor 20 - YAL-L21):
[OAFRepro.zip](https://github.com/dotnet/maui/files/10085097/OAFRepro.zip)

Thanks,
Dominik Švarc

**Comment by terraslate** [comment]
> Hello, I've found that this happens when you set InputTransparent = true. Then the currect value of Opacity works as maximal for FadeTo.
> 
> Here is the repro - VS 17.4.1 - Tested on Android 10 (Honor 20 - YAL-L21): ~[OAFRepro.zip](https://github.com/dotnet/maui/files/10085097/OAFRepro.zip)~
> 
> EDIT: InputTransparent breaks even the Opacity property. Here is updated bundle... I rushed it, sorry. 😄 [OAFRepro2.zip](https://github.com/dotnet/maui/files/10085174/OAFRepro2.zip)
> 
> Thanks, Dominik Švarc

Cheers. In my case i didn't explicitly set InputTransparent

**Comment by LukasKuchta** [comment]
Same issue here, when i set opacity in xaml to 0 and animate to 1 nothing is visibile. But when it is vice versa from 1 to 0 it is working fine but .... 

Any workaround for this ? Component has white background no trasparent.

**Comment by LukasKuchta** [comment]
Ok in my case it was Grid with shaddow definition in xaml. When i removed shadow before animation it is working fine. Seems to be bug. I will send demo project.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on Android platform with sample project.
[OAFRepro2.zip](https://github.com/dotnet/maui/files/10085174/OAFRepro2.zip)

**Comment by PureWeen** [comment]
Duplicate of #15826
