### ISSUE TITLE
MAUI Blazor `html, body, #app { height: 100%; }` works properly on Windows but doesn't work properly on macOS

### ISSUE THREAD

**Issue by Jinjinov** [dotnet/maui#11508]
### Description

MAUI Blazor `html, body, #app { height: 100%; }` works properly on Windows but doesn't work properly on macOS

There is no scrollbar on Windows:

![MauiWindows](https://user-images.githubusercontent.com/20396198/202898452-023c488b-adab-4e98-b3e2-ec80eb07f7aa.png)

But there is a scrollbar on macOS:

![MauiMac](https://user-images.githubusercontent.com/20396198/202898330-ae75f1e8-d73f-48da-9a3e-c779770f9385.png)

### Steps to Reproduce

1. Create new Maui Blazor project
2. Add `html, body, #app { height: 100%; }` to `app.css`
3. Run on Windows - there is no scrollbar - as expected
4. Run on macOS - there is a scrollbar - not as expected - bug

### Link to public reproduction project repository

https://github.com/Jinjinov/MauiBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Ventura 13.0.1

**Comment by Taiizor** [comment]
If you make the application full screen (no titlebar), the problem disappears. This is because of the macOS TitleBar.

**Comment by Jinjinov** [comment]
@mkArtakMSFT would it be possible to get an estimate for when this will be fixed? this year? next year Q1?

I don't know how to fix this problem using CSS, since the problem disappears in full screen mode. Any additional margin / padding that would account for the title bar would cause a new problem in full screen mode.

**Comment by mhrastegari** [comment]
Same here

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio for Mac 17.6 (build 1575). Can repro on macOS with sample project. https://github.com/Jinjinov/MauiBug

**Comment by mkArtakMSFT** [comment]
We believe this is a platform-specific issue and we don't think we're doing anything wrong here.
If you know of such a thing, please late us know.

**Comment by BethMassi** [comment]
I can't repro this one anymore. Blazor Hybrid default template looks fine on Mac 
<img width="677" alt="Screenshot 2024-04-05 at 2 08 18 PM" src="https://github.com/dotnet/maui/assets/5115571/31551fd6-dfc4-488b-9135-ebbd51084783">

**Comment by Jinjinov** [comment]
@BethMassi did you add `html, body, #app { height: 100%; }` to `app.css` ?
