### ISSUE TITLE
Embedding .NET MAUI in a native WinUI 3 App doesn't work as expected - Not even launching

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#11516]
### Description

Embedding .NET MAUI in a native WinUI 3 App doesn't work as expected. Not even launching.

Followed the steps mentioned in the documentation here: https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/native-embedding?view=net-maui-7.0

Though the App successfully builds, upon launching ends up with this message `Exception has been thrown by the target of an invocation.` the moment the `Build()` method on the MauiAppBuilder object is invoked.

Refer to the relevant log output for more details.

### Steps to Reproduce

1. Clone the sample code in the repo mentioned
2. Build the application and run it
3. Ends up the error mentioned

### Link to public reproduction project repository

https://github.com/egvijayanand/maui-issue-11516

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

Nope

### Relevant log output

```shell
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at Microsoft.Maui.Platform.ResourceDictionaryExtensions.AddLibraryResources[T](ResourceDictionary resources)
   at Microsoft.Maui.Hosting.MauiAppBuilder.MauiCoreInitializer.<Initialize>g__SetupResources|0_1()
   at Microsoft.Maui.Hosting.MauiAppBuilder.Build()
   at EmbeddedWindows.MainWindow..ctor() in E:\Tasks\EmbeddedWindows\MainWindow.cs:line 23
   at EmbeddedWindows.App.OnLaunched(LaunchActivatedEventArgs args) in E:\Tasks\EmbeddedWindows\App.cs:line 29
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
COMException: Unspecified error
```

**Comment by egvijayanand** [comment]
While validating the suggestion provided for this issue #14247  to place the WinUI-related files in the Windows folder.

Since Windows-targeted MAUI is nothing but a superset of WinUI project. Invoking the `UseMauiEmbedding<App>()` method call on the builder object to use it as native WinUI project results in the below error message.

**Either set MainPage or override CreateWindow.**

While using the `UseMauiEmbedding()` call suppress this error as it'll be handled in the native project and MAUI is just a container with all those DI registered services which is required for `ToPlatform()` translations to use MAUI view/layout/page inside native code.

**Comment by egvijayanand** [comment]
Have shared a Xaml version of the sample project to understand the earlier comment detailing the error message.

The earlier C# based sample is moved to the **src\\Code\\** folder.

Kindly go through these two source files.

* src\Xaml\EmbeddedWindows\MauiProgram.cs
* src\Xaml\EmbeddedWindows\Platforms\Windows\App.xaml.cs
  - Have left a comment on how it works now and how it is expected to work

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 3.0(net8). Not repro on Windows platform with sample.
https://github.com/egvijayanand/maui-issue-11516
![image](https://github.com/dotnet/maui/assets/82450723/dadcd5f4-aff9-4439-98e4-d7779014713b)
