### ISSUE TITLE
Label height too small when padding is greater than 1.

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#11511]
### Description

Last line of text is lost when padding is greater than one when using the phone in portrait position.
HeightRequest is not set.
I suppose the height should adjust to the amount of text.

### Steps to Reproduce

Open the repository in the link below.
Run the app in the Android simulator 13 API 33.

### Link to public reproduction project repository

https://github.com/geertgeerits/MauiAppTestLabelHeight

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13.0 API 33

### Did you find any workaround?

Not setting the padding greater than one and/or adding a line feed at the end of the text ( + "\n").

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. This issue does not repro on Android 13.0-API33 with below Project:
[MauiAppTestLabelHeight.zip](https://github.com/dotnet/maui/files/11673589/MauiAppTestLabelHeight.zip)

![image](https://github.com/dotnet/maui/assets/97647558/f77e6e8e-c58e-496b-bb42-3c6b87b050d4)

**Comment by geertgeerits** [comment]
It has been solved in the latest version. Thank you.
