### ISSUE TITLE
CarouselView inside CollectionView throws Java.Lang.RuntimeException: 'Canvas: trying to use a recycled bitmap'

### ISSUE THREAD

**Issue by terraslate** [dotnet/maui#11519]
Well this one is a real showstopper.  Haven't had this happen in the emulator, maybe it is a bit slower, in some ways but it happens on a physical device, Samsung Note 10+.  The carousel has two panels, one has 2 images in it, the other has 23. They download from the internet though they are cached, so display is quickish after a second run.

Java.Lang.RuntimeException
  Message=Canvas: trying to use a recycled bitmap android.graphics.Bitmap@9383040

I don't think it is related to the visual tree hierarchy I note in the title however I put that in for reference as it may or may not be related. But on further consideration given the nature of the message I decided to check if the page has any duplicate urls, which it is allowed to have btw, and in particular this one does. I suspect the image is destroying and then through the implementation underneath by noting it is the same url it tries to use the same image again, but it is in the process of destroying, hence it crashes. 

In my estimation the implementation should wait for it to destroy first before attempting to reuse it, perhaps reference count the uniqueness of it so that it can easily see that the same image coming into view increases to 2 views using it, drops to 1 view using it, and only when it reaches 0 can it then destroy it.

Update: still happens without duplicate images in the list.

**Comment by terraslate** [comment]
Did some digging: also saw reference in maui code that it is moving to use Glide, probably a good idea.

Seems this issue has been around decades in java. Here's probably the ultimate link on the problem and how to solve it:

https://developer.android.com/topic/performance/graphics/manage-memory

This article indeed shows that you need to use reference counting. It appears older version of android used native memory, then not, and then newer versions do again. So the reference counting seems critical.

Also, later versions from 19 on can reuse bitmaps of a different size, and my collectionview does use different sized bitmaps. It may be possible that the issue is around the difference in size of the content., perhaps a larger bitmap into a smaller bitmap or something.

**Comment by terraslate** [comment]
> We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/maui/blob/main/docs/TriageProcess.md).

Well i do hope you keep the comments here or moved them across because what i read in the other link you posted are some really horrendous ideas by the team about not releasing images at all and letting the garbage collector do it instead (err it is native memory!!! - noooooooooo!)

Also this occurs in release mode, whereas in the other it is claimed it only happens in debug. It is obviously a race condition and incorrect code guards, and the link i included tells you how to fix it, it's been referenced from 9 years ago.

**Comment by mohachouch** [comment]
I spent a few hours to analyze this problem.

This bug was created following this pull request: https://github.com/dotnet/maui/pull/7348

While waiting for Microsoft to permanently fix this bug, the workaround consists of redoing the clear before each source image change.

Below is an example of code to add the clear in the source image mapping.

```
using Microsoft.Maui.Handlers;
using Microsoft.Maui.Platform;

namespace MauiCanvas;

public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

#if __ANDROID__
        ImageHandler.Mapper.PrependToMapping(nameof(Microsoft.Maui.IImage.Source), (handler, view) => PrependToMappingImageSource(handler, view));
#endif

        return builder.Build();
	}

#if __ANDROID__
    public static void PrependToMappingImageSource(IImageHandler handler, Microsoft.Maui.IImage image)
    {
        handler.PlatformView?.Clear();
    }
#endif

}
```

**Comment by mohachouch** [comment]
I spent a few hours to analyze this problem.

This bug was created following this pull request: https://github.com/dotnet/maui/pull/7348

While waiting for **Microsoft to permanently fix this bug**, the workaround consists of redoing the clear before each source image change.

Below is an example of code to add the clear in the source image mapping.

This workaround is applicable to the following bug 
https://github.com/dotnet/maui/issues/11519 https://github.com/dotnet/maui/issues/11130 https://github.com/dotnet/maui/issues/10032 https://github.com/dotnet/maui/issues/9712 https://github.com/dotnet/maui/issues/8809 https://github.com/dotnet/maui/issues/9011
https://github.com/dotnet/maui/issues/8178 https://github.com/dotnet/maui/issues/8809
```
using Microsoft.Maui.Handlers;
using Microsoft.Maui.Platform;

namespace MauiCanvas;

public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

#if __ANDROID__
        ImageHandler.Mapper.PrependToMapping(nameof(Microsoft.Maui.IImage.Source), (handler, view) => PrependToMappingImageSource(handler, view));
#endif

        return builder.Build();
	}

#if __ANDROID__
    public static void PrependToMappingImageSource(IImageHandler handler, Microsoft.Maui.IImage image)
    {
        handler.PlatformView?.Clear();
    }
#endif

}
```
