### ISSUE TITLE
MAUI iOS .NET 7 + EFCore 7.0.0 doesn't work

### ISSUE THREAD

**Issue by RobertoGFilho** [dotnet/maui#11513]
### Description

EF Core 7 doens't work with MAUI iOS .NET 7, please reproduce this issue on working Visual Studio 2022 for Windows 11.

### Steps to Reproduce

1 Use Windows 11;
2 Visual Studio 2022 last version;
3 buind app on real device "using hotrestar"  sample iPhone 7 Plus;
4 download project: https://github.com/RobertoGFilho/Samples/tree/master/EFCore

### Link to public reproduction project repository

https://github.com/RobertoGFilho/Samples/tree/master/EFCore

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

```
<!--DOESN'T WORKS on iOS-->
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.0" />

<!--WORKS-->
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.11" />
<PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
<PackageReference Include="SQLitePCLRaw.core" Version="2.1.2" />
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.2" />
<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.2" />
<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.2" />
```

```
using Foundation;
using SQLitePCL;

namespace EFCore
{
    [Register("AppDelegate")]
    public class AppDelegate : MauiUIApplicationDelegate
    {
        protected override MauiApp CreateMauiApp()
        {
            //raw.SetProvider(new SQLite3Provider_sqlite3());
            return MauiProgram.CreateMauiApp();
        }
    }
}
```

references: https://vladislavantonyuk.azurewebsites.net/articles/Adding-SQLite-to-the-.NET-MAUI-application

**Comment by yunusefendi52** [comment]
for the workaround have you try to remove "sqlite-net-pcl" because it doesn't have the dependency to ef core
```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.11" />
<PackageReference Include="SQLitePCLRaw.core" Version="2.1.2" />
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.2" />
<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.2" />
<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.2" />
```

**Comment by Eilon** [comment]
Closing because this does not appear to be a bug in .NET MAUI.
