### ISSUE TITLE
Unpackaged app compilation fail due to space in profile name

### ISSUE THREAD

**Issue by brignolff** [dotnet/maui#11518]
### Description

When building an unpackaged MAUI app, the build fails due to a white space in the "C:\\users\*profile name*" folder.

### Steps to Reproduce

1. Create a profile with a space in the name
2. create a MAUI app using the VS template
3. add the <WindowsPackageType>None</WindowsPackageType> node to a PropertyGroup in the .csproj
4. change the "CommandName" to "project" in the "launchSetting.json"
5. try to build in release or debug.

### Link to public reproduction project repository

none because linked to user profile and not project

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

windows 10 21H2

### Did you find any workaround?

Had to make a new user profile without the space in the name

**Comment by jsuarezruiz** [comment]
Could you share more information like your bin logs?

**Comment by brignolff** [comment]
Hi, 

As mentioned in the post I fixed the bug by creating à second user profile without the space in the name. 

After reinstalling everything and transfering my data I deleted the old profile and I'm now unable to provide log or reproduce the bug.

**Comment by mattleibow** [comment]
This issue was moved to microsoft/WindowsAppSDK#3173
