### ISSUE TITLE
Allow custom/localized text for TabBar "More"-button

### ISSUE THREAD

**Issue by durandt** [dotnet/maui#11521]
### Description

**Context**
On Android, when using a TabBar with many Tabs the renderer hides extra tabs under a "More"-tab/button. 
The more button with text and icon is created in BottomNavigationViewUtils.cs
https://github.com/dotnet/maui/blob/bcaea570dd469404fce699c9bf38cf8a18a65897/src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs#L77

**Feature request**
Make it possible to customize/localize the text and icon of the more-tab/button. 

**Question**
The _More_ text is defined in as _overflow_tab_title_ in `src/Controls/src/Core/Platform/Android/Resources/values/strings.xml`
Please tell me if there is a way to localize MAUI's strings.xml that I have missed. 

### Public API Changes

```csharp
var tabBar= new TabBar();
tabBar.MoreTabText = "MyCustomText"; // new API
tabBar.MoreTabIcon = "my_custom_icon.png"; // new API
```

### Intended Use-Case

This feature could be used to localize the text that appears when the number of tabs overflow. Many mobile-apps users wish to have their apps in their native language or don't even speak English. It is therefore important that all text showing in the app may be customizable and localizable by the app developer.

**Comment by jfversluis** [comment]
If you add a `Resources/values/strings.xml` file in your own project with that key it should pick that up. Have you tried that? Didn't that work.

We already implemented that for Xamarin.Forms, you can see how to use it here: https://github.com/xamarin/Xamarin.Forms/pull/10604/files

From there, you can add localized `strings.xml` files for a localized value.

**Comment by jfversluis** [comment]
Tried it out for you, see here: https://github.com/jfversluis/MauiAndroidCustomMoreTabTitleSample

Key is the `strings.xml` file I mentioned, so look for that under the `Android` folder.

If you put it under the `values` folder it will be the default/fallback. So I changed it and then looks like this
![image](https://user-images.githubusercontent.com/939291/203095863-76f2dd8c-82bd-4a1a-8a48-103315d5ba11.png)

If you want to localize, this will just use the [Android way to do this](https://developer.android.com/guide/topics/resources/localization). For instance, I added a `values-nl` folder for Dutch, and added a different value for it, and when you set the device language to Dutch, it now changes to this

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/939291/203096096-bf0b21d6-f060-488e-a982-bb2dbc782608.png)

I don't think there is anything to do here for us so closing this for now.

**Comment by durandt** [comment]
Hi @jfversluis ,

Thank you for your quick answer and walkthrough of current solution. 
I still think that there are valid use-cases for dynamically set the More-tab-label in the future, but the strings.xml solution will do for me for the time being. 

Best regards,
