### ISSUE TITLE
Flyout items can vanish when arrowing down through a flyout.

### ISSUE THREAD

**Issue by Karan4495** [dotnet/maui#11522]
GitHubTags:
#.NET MAUI; #A11ySev1; #A11yMAS; #A11yTCS; #Benchmark; #DesktopApp; #Win11; #WCAG2.1.1; #GH_.NETMAUI_Win32_Apr2022; #AILimited; #Win32; #Keyboard;

### Description

When arrowing down through a Maui Flyout, items below the 2nd item in the flyout can visually vanish, leaving only space where they once were.

### Steps to Reproduce

1. Build and run this test app for Windows, https://github.com/gbarkerz/MyVeryFirstMauiApp.
2. Tab to move keyboard focus to the Open Navigation button at the top left corner of the app.
3. Press Space to invoke the flyout.
4. Press DownArrow to move keyboard focus to the first item in the flyout.
5. Press DownArrow again to move keyboard focus to the second item in the flyout.
6. Verify Flyout items can vanish when arrowing down through a flyout or Not.

Before. Alt: A test .NET Maui app running on Windows. Its flyout is open, showing items of "First", "Second", "Third", "Fourth", and "Fifth". Keyboard focus feedback is shown at the first item in the flyout.
![image](https://user-images.githubusercontent.com/100186395/203028875-99ffea32-391e-49f8-ad51-668e3e1aa18c.png)

After. Alt: A test .NET Maui app running on Windows. Its flyout is open, showing items of "First" and "Second", with keyboard focus feedback showing on the second item. No other items are shown, yet the flyout is large enough to contain multiple other items.
![image](https://user-images.githubusercontent.com/100186395/203028923-ef0c9e76-2429-44cf-b3cc-93880f9236a1.png)

### Link to public reproduction project repository

Not Applicable

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 Enterprise Version 22H2 OS build 22621.819

### Relevant log output

```shell
Flyout items should not vanish when arrowing down through a flyout.
```

**Comment by merriemcgaw** [comment]
@PureWeen / @rachelkang - do we have a timeline for the ingestion of the next Windows SDK? It looks like 1.2.2 is stable and released.

**Comment by PureWeen** [comment]
> @PureWeen / @rachelkang - do we have a timeline for the ingestion of the next Windows SDK? It looks like 1.2.2 is stable and released.

It's already ingested and released with the latest stable .NET 7.0 and Visual Studio 2022

**Comment by merriemcgaw** [comment]
@Karan4495 can you please have the team verify the fix by using the latest .NET 7 servicing build by installing the latest servicing update of Visual Studio 2022?  I believe that it would be Dev17.4.3 builds, but @PureWeen can confirm. Just use the sample app, but make sure that it targets .NET 7.0 and it should work fine.

**Comment by Karan4495** [comment]
Verified the bug and issue is fixed so closing the bug.
https://user-images.githubusercontent.com/100186395/212810910-c52714ea-c0d6-44de-81c9-bbb87da8ecad.mp4
