### ISSUE TITLE
FileSavePicker throws "Invalid window handle" error

### ISSUE THREAD

**Issue by datvm** [dotnet/maui#11527]
### Description

The following code throws an exception:

```cs
        var diag = new Windows.Storage.Pickers.FileSavePicker();
        diag.FileTypeChoices.Add("PDF", new List<string>() { ".pdf" });

        try
        {
            await diag.PickSaveFileAsync(); // Exception here
        }
        catch (Exception ex)
        {
            this.exceptionText = ex.ToString();
        }
```

> System.Runtime.InteropServices.COMException (0x80070578): Invalid window handle. (0x80070578)
> Consider WindowNative, InitializeWithWindow
> See https://aka.ms/cswinrt/interop#windows-sdk
>    at MauiApp1.Pages.Index.SaveFileAsync()

![image](https://user-images.githubusercontent.com/6388546/203099336-687eab80-be13-4b4d-9e72-64230fb08bcb.png)

### Steps to Reproduce

1. Create a MAUI app. Add the above code or use the repo below.
2. Click "Save File" button.
3. Exception is thrown.

### Link to public reproduction project repository

https://github.com/datvm/MAUIWinPickerError

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

~~This supposes to fix it but right now I cannot find anyway to get a Window hWnd anymore. Also that issue is closed supposedly it's fixed but I am still encountering it right now: https://github.com/dotnet/maui/issues/2194#issuecomment-1003773033~~. See https://github.com/dotnet/maui/issues/11527#issuecomment-1322287764

**Comment by datvm** [comment]
Found workaround for now (finally know how to get the window's hWnd):

```cs
            var currWin = Application.Current?.Windows.FirstOrDefault();
            var hwnd = (currWin?.Handler.PlatformView as MauiWinUIWindow)?.WindowHandle;
            if (hwnd is null) { return; }
            
            WinRT.Interop.InitializeWithWindow.Initialize(diag, hwnd.Value);
```

**Comment by mattleibow** [comment]
This is the issue: https://github.com/microsoft/WindowsAppSDK/issues/1063
