### ISSUE TITLE
Page title won't update when switching tabs with top bars inside a TabBar inside a shell on Android. Re-introduced

### ISSUE THREAD

**Issue by alfamizar** [dotnet/maui#11549]
### Description

Bug is the same, that was already closed [here ](https://github.com/dotnet/maui/issues/3743)

Works as expected on Windows (can not check on Mac and iOS)

If you use top Tabs by using multiple ShellContent elements inside a Tab, the page title will not update when switching tabs.

<Shell
    x:Class="MauiPageTitleNotUpdated.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiPageTitleNotUpdated"
    Shell.FlyoutBehavior="Disabled">

    <FlyoutItem FlyoutDisplayOptions="AsMultipleItems">
        <Tab Title="Domestic">
            <ShellContent Title="Cats"
                          ContentTemplate="{DataTemplate local:CatsPage}" />
            <ShellContent Title="Dogs"
                          ContentTemplate="{DataTemplate local:DogsPage}" />
        </Tab>
        
        <ShellContent Title="Monkeys"
                      ContentTemplate="{DataTemplate local:MonkeysPage}" />
        <ShellContent Title="Elephants"
                      ContentTemplate="{DataTemplate local:ElephantsPage}" />
        <ShellContent Title="Bears"
                      ContentTemplate="{DataTemplate local:BearsPage}" />
    </FlyoutItem>

</Shell>

https://user-images.githubusercontent.com/52598586/203285729-ffb818a3-0b7d-4924-95e0-5f9785b2fa36.mp4

![Screenshot_1669111316](https://user-images.githubusercontent.com/52598586/203285742-1a1045a1-fc11-426e-9810-31a3e3a325f2.png)
![Screenshot_1669111318](https://user-images.githubusercontent.com/52598586/203285747-f40587ef-cf56-4fbc-a7fc-7b3580074112.png)

### Steps to Reproduce

1. Create a Shell with a TapBar inside.
2. Inside the TapBar use a Tab item with multiple ShellContent.
3. You'll see the Page Title won't update when you switch tabs.

### Link to public reproduction project repository

https://github.com/alfamizar/MauiPageTitleNotUpdated

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

I have tested on API 28 and 32

### Did you find any workaround?

No

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on android platform with above project.
[MauiPageTitleNotUpdated-master.zip](https://github.com/dotnet/maui/files/11622007/MauiPageTitleNotUpdated-master.zip)
![11549](https://github.com/dotnet/maui/assets/77434865/a5b6866b-f373-40d7-8f04-5a2d69508d17)

**Comment by alfamizar** [comment]
Tested in VS 17.6.2 Community edition, .Net 7. Seems like bug is already fixed.
