### ISSUE TITLE
Running on windows 11 doesn't live up to expectations, but Android is right

### ISSUE THREAD

**Issue by caoyiliang** [dotnet/maui#11547]
### Description

[Calc.zip](https://github.com/dotnet/maui/files/10065643/Calc.zip)
Running on windows 11 doesn't live up to expectations, but Android is right

### Steps to Reproduce

[Calc.zip](https://github.com/dotnet/maui/files/10065653/Calc.zip)
Running on windows 11 doesn't live up to expectations, but Android is right

### Link to public reproduction project repository

https://github.com/dotnet/maui/files/10065653/Calc.zip

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows

**Comment by caoyiliang** [comment]
Thank you for your letter, I will reply as soon as possible

**Comment by PureWeen** [comment]
Can you include some screen shots with expectations?

**Comment by caoyiliang** [comment]
windows: The first input deletion is normal; After the second delete, the delete button is still gray, but it can be used.
Normal on android

**Comment by caoyiliang** [comment]
https://user-images.githubusercontent.com/67636300/203451234-be823bff-f9ba-4321-b645-941da6c0cbb2.mp4

**Comment by caoyiliang** [comment]
Left:windows: The first input deletion is normal; After the second delete, the delete button is still gray, but it can be used.
Normal on android

**Comment by Providenceee** [comment]
> https://user-images.githubusercontent.com/67636300/203451234-be823bff-f9ba-4321-b645-941da6c0cbb2.mp4 Left:windows: The first input deletion is normal; After the second delete, the delete button is still gray, but it can be used. Normal on android

Encountered this visual bug too.

**Comment by mattleibow** [comment]
Duplicate of #7377

**Comment by mattleibow** [comment]
I also see CanExecute in the code, so a duplicate of #9753

**Comment by mattleibow** [comment]
Duplicate of #9753
