### ISSUE TITLE
[Bug] Semantic Hint not working as expected Maui Main Branch Andriod

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/maui#1155]
I am creating a Selected Date property for the date picker control in my code it is the following.But when I set a Date the hint does not display so I must trap for the text in Set Text but if I do it the way below the hint will not disapear and never shows the date.

It looks like the default code is not calling SetHint=""; When closing of the date picker dialog?

    internal static void SetText(this MauiDatePicker nativeDatePicker, IDatePicker datePicker)
    {
         if (datePicker.SelectedDate != null )
	     datePicker.Date = (DateTime)datePicker.SelectedDate;
         if (datePicker.Semantics !=null)
             nativeDatePicker.Hint = datePicker.Semantics.Hint;
         else
	      nativeDatePicker.Text = datePicker.Date.ToString(datePicker.Format);			
    }
    
Date Picker Cs i have the following

      public static readonly BindableProperty DateProperty = BindableProperty.Create(nameof(Date), typeof(DateTime), typeof(DatePicker), default(DateTime), BindingMode.TwoWay,
			coerceValue: CoerceDate,
			propertyChanged: DatePropertyChanged,
			defaultValueCreator: (bindable) => DateTime.Today);

		public static readonly BindableProperty SelectedDateProperty= BindableProperty.Create(nameof(Date), typeof(DateTime?), typeof(DatePicker), default(DateTime?), BindingMode.TwoWay,
		coerceValue: CoerceDate,
		propertyChanged: SelectedDatePropertyChanged,
		defaultValueCreator: (bindable) => null);

		public DateTime? SelectedDate
		{
			get { return (DateTime?)GetValue(SelectedDateProperty); }
			set { SetValue(SelectedDateProperty, value); }
		}

		public DateTime Date
		{
			get { return (DateTime)GetValue(DateProperty); }
			set { SetValue(DateProperty, value); }
		}

 However the issue I am having Is that the hint text is not clearing itself on the Android Ok Button click its still showing the orignal hint if I don't set the hint physically using the above method in UpdateText It will not show the Hint I think hints are not working correctly in the main maui branch here is an example of what i mean.

I am setting the hint in the sample project of MainPage.CS

      var testDate= new DatePicker { Date=DateTime.Today};			
	    SemanticProperties.SetHint(testDate, "Please select");
	   verticalStack.Add(testDate);

This is an item on the issue bored to allow SelectedDate to be null that a app developer does not have to add a check box just to be able to not to have the user to select a date

The issue that is the main is that Date will default to todays date which does not make since for a user so maybe a more simpler fix could be required, I am working on the issue but any assistance as to why the hint may not be working.

IF a video is required to show the implementation and problem please advice.

**Comment by davidbuckleyni** [comment]
Im running API 30 on Pixel 2

![image](https://user-images.githubusercontent.com/5619229/120559701-65601200-c3f9-11eb-9d54-2f9ea8abf8ef.png)

**Comment by rachelkang** [comment]
Hi @davidbuckleyni, thanks so much for submitting this issue! In your explanation, you mentioned that the hint is not "showing" and "displaying". Before investigating further, I just want to clarify - are you expecting to see the hint appear on the screen visually? If so, SemanticHint is not what you should be using. SemanticHint is not meant to appear visually on the UI; it is used for screen reader accessibility, to set the text that gets read aloud by screen readers. If I'm understanding correctly, your best solution might be to implement a label above the date picker. (Although with a normal picker, you can use the Title property)

Hope this helps, but if not, let me know if I'm misunderstanding!

**Comment by davidbuckleyni** [comment]
I was talking about hints like as in Place Holders ? A that is a miss understanding then close the issue do u no what i use instead @PureWeen

**Comment by rachelkang** [comment]
Hi @davidbuckleyni - as I mentioned, you can use the `Title` property for normal pickers, but unfortunately we don't currently have an equivalent for DatePickers and TimePickers. So for your use case, the best workaround at the moment might be to implement a label above the date picker.
