### ISSUE TITLE
[iOS] Scrollviewer not scrolling

### ISSUE THREAD

**Issue by Larhei** [dotnet/maui#11558]
### Description

When changing the ContentSize of the Scrollable content in Scrollviewer after OnLoad, the Scrollview does not Scroll.

Lets say I need a scrollable ItemsControl.
I would use a ScrollViewer containing a BindableLayout.
When for what ever reason it takes longer to generate the Collection bound to the Itemssource and the generated Items are greater than the ViewPort of the ScrollView, after rendering the items, the Scrollviewer does not scroll. 

### Steps to Reproduce

1. Just run the demo on iOS

### Link to public reproduction project repository

https://github.com/Larhei/Maui-Issues/tree/main/ScrollViewer/ScrollViewer

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS all

### Did you find any workaround?

Subscribing the SizeChanged of the BindableLayout and setting the MinimHeightRequest helps.
Forcing an additional Measure to get it right is not my Job.

    private void HandleSizeChanged(object sender, System.EventArgs e)
    {
        var layout = sender as Layout;
        if (layout == null)
        {
            return;
        }
        layout.MinimumHeightRequest = 0;
        var size = layout.Measure(double.PositiveInfinity, double.PositiveInfinity, MeasureFlags.None);
        if (double.IsNaN(size.Request.Height) || double.IsInfinity(size.Request.Height))
        {
            return;
        }

        layout.MinimumHeightRequest = Math.Max(size.Request.Height, size.Minimum.Height);
    }

**Comment by hartez** [comment]
Likely fixed by #11175.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on iOS platform with sample project.
[Maui-Issues-main.zip](https://github.com/dotnet/maui/files/11622293/Maui-Issues-main.zip)
![11558](https://github.com/dotnet/maui/assets/77434865/cb9fc0ad-b5a9-4e4b-8420-7a00bada4a4b)

**Comment by jfversluis** [comment]
Just tried the sample against .NET 8 and it works! So assuming this is fixed. If something still isn't right, please open a new issue, thanks!
