### ISSUE TITLE
Metatada file "MyApp.dll" could not be found, on all default solutions on Visual Studio Mac

### ISSUE THREAD

**Issue by kedare** [dotnet/maui#11567]
### Description

After a fresh install of Visual Studio for Mac 17.4 (build 2406),

I tried to create both a Tabbed and Flyout project.

The projects do build fine, when the solutions don't (and impossible to run the app on ios or android emulator then)

### Steps to Reproduce

- Install a fresh visual studio 17.4 on MacOs Ventura on M1
- Create any multiplatform app solution
- Try to build the solution or launch the project
- The error should appear on the errors pane and the build fail

### Link to public reproduction project repository

https://github.com/kedare/maui-bug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Not related to a specific platform

### Did you find any workaround?

No

### Relevant log output

```shell
/Users/mpoussin/Projects/MauiTabbed/MauiTabbed/MauiTabbed.Android/CSC: Error CS0006: Metadata file '/Users/mpoussin/Projects/MauiTabbed/MauiTabbed/MauiTabbed/bin/Debug/netstandard2.0/ref/MauiTabbed.dll' could not be found (CS0006) (MauiTabbed.Android)
/Users/mpoussin/Projects/MauiTabbed/MauiTabbed/MauiTabbed.iOS/CSC: Error CS0006: Metadata file '/Users/mpoussin/Projects/MauiTabbed/MauiTabbed/MauiTabbed/bin/Debug/netstandard2.0/ref/MauiTabbed.dll' could not be found (CS0006) (MauiTabbed.iOS)
```

**Comment by jsuarezruiz** [comment]
Are you trying to create a .NET MAUI App?. Taking a look to your sample, you are creating a Xamarin.Forms App using net standard 2.0. https://github.com/kedare/maui-bug/blob/master/MauiFlyout/MauiFlyout/MauiFlyout.csproj#L9

**Comment by kedare** [comment]
Indeed looks like I selected the wrong type in visual studio.
Thank you for your fast response, I will close the ticket
