### ISSUE TITLE
Create handler extension methods that will scan dlls for compat renderers

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1156]
We need to add some handler registration calls you can use to scan dlls (API names below have not been well thought out so don't stick with these names)

- AddCompatibilityRenderersFromAssemblies(list of assemblies)
- AddCompatiblityRenderersFromAllAssemblies()

**Comment by jsuarezruiz** [comment]
Hey Shane, what is the status, there are something related right?

**Comment by mattleibow** [comment]
This was added some time back and there is now a `AddCompatibilityRenderers(params Assembly[] assemblies)` that can be used like this:

```cs
handlers.AddCompatibilityRenderers(AppDomain.CurrentDomain.GetAssemblies())
```
