### ISSUE TITLE
dotnet test fails when test project targets net6.0-windows10.0.19041

### ISSUE THREAD

**Issue by filipleifer** [dotnet/maui#11575]
### Description

We have MAUI apllication which targets "net6.0-android/net6.0-ios" and it cannot target simply "net6.0" framework because of 3rd party nuget dependencies. So we are targeting also net6.0-windows10.0.19041 in MAUI project to use MAUI project in unit tests. But unit test project targeting net6.0-windows10.0.19041 cannot be run. It fails with error event if Microsoft.Maui.Core version 6.0.547 can be found in location c:\Program Files\dotnet\packs\Microsoft.Maui.Core.Ref.win\6.0.547\

 You must install or update .NET to run this application.
App: d:\test\testhost.exe
Architecture: x64
Framework: 'Microsoft.Maui.Core', version '6.0.547' (x64)
.NET location: C:\Program Files\dotnet
No frameworks were found.
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.Maui.Core&framework_version=6.0.547&arch=x64&rid=win10-x64

------------------------------------------------------------------------------------------------

dotnet workload list:

--------------------------------------------------------------------
maui                        7.0.49/7.0.100         SDK 7.0.100
maui-ios                    7.0.49/7.0.100         VS 17.4.33110.190
ios                         16.0.1478/7.0.100      VS 17.4.33110.190
maui-android                7.0.49/7.0.100         VS 17.4.33110.190
android                     33.0.4/7.0.100         VS 17.4.33110.190
maui-windows                7.0.49/7.0.100         VS 17.4.33110.190
maui-maccatalyst            7.0.49/7.0.100         VS 17.4.33110.190
maccatalyst                 15.4.2372/7.0.100      VS 17.4.33110.190

### Steps to Reproduce

1. Create MAUI project referencing also net6.0-windows10.0.19041
2. Create Test Project referencing MAUII Project targeting only net6.0-windows10.0.19041 with option UseMaui = true
3. run dotnet test "PATH TO TEST PROJECT"

Current result: Test run fails

App: d:\Repos\MyMauiApp\MyTestProject\bin\Debug\net7.0-windows10.0.19041.0\testhost.exe
Architecture: x64
Framework: 'Microsoft.Maui.Core', version '**FromWorkload**' (x64)
.NET location: C:\Program Files\dotnet
No frameworks were found.
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.Maui.Core&framework_version=**FromWorkload**&arch=x64&rid=win10-x64

Expected result: Tests are run successfully

Bahavior is same for NET6.0 / NET 7.0

### Link to public reproduction project repository

https://github.com/filipleifer/samples

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 with below Project:
[MyMauiApp.zip](https://github.com/dotnet/maui/files/11674116/MyMauiApp.zip)

![image](https://github.com/dotnet/maui/assets/97647558/c8db5eda-4bd6-4713-88ed-3db6866ad864)

**Comment by Hottemax** [comment]
we have the same issue. Not sure why #3552 was closed, and what the closing `[comment/screenshot](https://github.com/dotnet/maui/issues/3552#issuecomment-1468808644)` is supposed to demonstrate.

Is it with the 

```
<!-- xUnit: The condition here only excludes this for the unit test project -->
<TargetFrameworks>net7.0;net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
<OutputType Condition="'$(TargetFramework)' != 'net7.0'">Exe</OutputType>

"trick"? (This trick is even still used by their [eShopOnContainers showcase project](https://github.com/dotnet-architecture/eshop-mobile-client/blob/main/eShopOnContainers/eShopOnContainers.csproj), which has unit tests).

If so, this

a) is not really a stable solution
b) **cannot be used when nuget packages without net7.0 are among your used packages** (some just specify the platform-specific target frameworks...

So, all in all, we still don't have a consistent solution, unfortunately.

**Comment by mattleibow** [comment]
With .NET 8 we are now using NuGet packages and this should no longer be happening. There is now real way to fix this for net6/net7 since dotnet workloads do not support dotnet test.
