### ISSUE TITLE
Application targetting .NET 6 and Windows 10.0.22621.0 cannot be run

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#11585]
### Description

MAUI app targetting Windows 10.0.22621.0 cannot be started.
Project builds successfully.
Error:

`1>C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1005: Assets file 'C:\Users\janse\Desktop\prace\Tempus.Mobile.Android.Updater\MauiApp1\MauiApp1\obj\project.assets.json' doesn't have a target for 'net6.0-windows10.0.19041.0'. Ensure that restore has run and that you have included 'net6.0-windows10.0.19041.0' in the TargetFrameworks for your project.`

When changing the version to Windows 10.0.19041.0 in the settings and targetting .NET 6, the application can be started.

![image](https://user-images.githubusercontent.com/64279914/203602532-1d9152c3-f108-4db7-acbf-9ab3aeac9eba.png)

### Steps to Reproduce

Create a new MAUI app in VS 17.4.0 targetting .NET 6 (select the option when creating the project).
Note: VS 17.4.0 is the first GA version to include .NET 7.
Disable all targets except Windows (and Mac, it cannot be unselected)
Select version Windows 10.0.22621.0 for Windows target in project settings (may be selected by default).
The project is built successfully.
The application cannot be started on Windows.

### Link to public reproduction project repository

not needed

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.22621.0

### Did you find any workaround?

no

**Comment by rachelkang** [comment]
Hi, @janseris - please attach [bin logs](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis) so that we can investigate further. Thank you!

**Comment by janseris** [comment]
> Hi, @janseris - please attach [bin logs](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis) so that we can investigate further. Thank you!

Hi, you cannot reproduce the issue?
