### ISSUE TITLE
Mac Catalyst target cannot be removed

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#11584]
### Description

All platforms can be removed except Mac Catalyst
![image](https://user-images.githubusercontent.com/64279914/203599301-0b358b98-fcce-4711-abd3-8bb5c99d9fae.png)

Expected behavior:
- Mac Catalyst platform can be removed as well

Use case:
- create an Android-only MAUI app

### Steps to Reproduce

Create a new MAUI project targetting .NET 6
Click project properties and find the section shown in the image.
There is no option to enable/disable Mac Catalyst target or to change its properties.

### Link to public reproduction project repository

not needed

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

all

### Did you find any workaround?

no

**Comment by janseris** [comment]
@rachelkang Hi, could you move the issue there, please?

**Comment by jfversluis** [comment]
@janseris we can't that is why we have this label and message in place. If we were to move this it would just have the information that you have provided here. If you report it yourself as per the instructions provided, it will also provide relevant log data etc. that will be of help for the Visual Studio team. Sorry for the inconvenience!

**Comment by NPatch** [comment]
Just FYI, since the op mentions no workaround. You can easily edit the project file and remove the mac catalyst target from the <TargetFrameworks ../> tag up top. Once you have the target is no longer available on the UI when selecting active target.
