### ISSUE TITLE
Very slow Intellisense & Code Completion in MAUI projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#11592]
EDIT: Adding context to this issue:

It looks like the source generator in MAUI Community Toolkit is causing slowdowns with Roslyn.

[TextColorToGenerator](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs)

The suggestion is to move to using `ForAttributeWithMetadataName` to create the analyzer which would mean creating an attribute and decorating any types you want the generator to run on with it.

This may reduce the usefulness of the generator towards the original goal, but I think short of making this change, perhaps we need to consider removing the generator, or otherwise making it opt-in somehow via msbuild property or something else.

--------

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Very-slow-Intellisense--Code-Completion/10198504)._

---
[severity:It's more difficult to complete my work]
Working in MAUI projects within Visual Studio is extremely slow.
It already occurred in 17.3.* but even after upgrading to 17.4 I can wait ~ 10 seconds before code completoin or INtelliSense kick in.
Adding missing using-statements take up minutes now!

This does not happen in Console appplications, Xamarin projects, etc., *only* in MAUI solutions.

---
#### Feedback Bot on 11/14/2022, 00:42 AM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 11/15/2022, 01:14 AM: 

(private comment, text removed)
#### Schmidt, Helmut on 11/16/2022, 11:14 AM: 

(private comment, text removed)
#### Feedback Bot on 11/17/2022, 04:46 AM: 

(private comment, text removed)
#### Cyrus Najmabadi [MSFT] on 11/23/2022, 01:36 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Transfer to the CommunityToolkit

**Comment by mattleibow** [comment]
This issue was moved to CommunityToolkit/Maui#785
