### ISSUE TITLE
[Bug] AppThemeBinding issues

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1160]
### Description

On iOS nothing changes on my `ContentPage` as I expect it to.

On Android, the initial theme state is wrong, the page background changes, but the `Label` doesn't respond to changes as expected.

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             Title="AppThemeBinding"
             BackgroundColor="{AppThemeBinding Dark=Black, Light=White}"
             x:Class="ScenarioValidation.Pages.AppThemeBindingPage">
    <ContentPage.Content>
        <StackLayout VerticalOptions="CenterAndExpand" 
                   HorizontalOptions="CenterAndExpand">
            <Label Text="This text should always be visible"
                   TextColor="{AppThemeBinding Dark=White, Light=Black}"
                    />
            <Label Text="Background is Black when Dark"
                   TextColor="White" />
            <Label Text="Background is White when Light"
                   TextColor="Black" />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

https://user-images.githubusercontent.com/41873/120566101-25d2ff00-c3d4-11eb-9f58-cca6cfb150b8.mp4

https://user-images.githubusercontent.com/41873/120566289-89f5c300-c3d4-11eb-8c0b-2b5bd8443500.mp4

https://user-images.githubusercontent.com/41873/120566807-aba37a00-c3d5-11eb-9209-396d9324a10a.mp4

### Basic Information

- Version with issue: Pre4

**Comment by davidortinau** [comment]
Doing some more investigation with this in pre5 and seeing that ContentPage.Background doesn't work if I use StaticResources of type Color, however it does with hex values and SolidColorBrush. This is done directly on my page. 

No:

```
Background="{AppThemeBinding 
                        Dark={StaticResource Black}, 
                        Light={StaticResource White}}"
```

Yes:

```
Background="{AppThemeBinding 
                        Dark=#000000, 
                        Light=#999999}"
```

Also, this looks like it could work:

```
<SolidColorBrush x:Key="BackgroundBrush" 
                Color="{AppThemeBinding 
                        Dark={StaticResource BlackBrush}, 
                        Light={StaticResource WhiteBrush}}"/>
```

```
<ContentPage Background="{DynamicResource BackgroundBrush}"...
```

However it doesn't. a/ it would be nice if it did, b/ if it cannot, then we ought to throw some compiler error.

**Comment by mattleibow** [comment]
Another related issue for https://github.com/dotnet/maui/issues/3188 I think.

Just linking them all up now and will do a app big theme test run.

**Comment by v-xiaofchen** [comment]
Verified repro with Android 11 and the above project.

**Comment by v-xiaofchen** [comment]
Verified repro with Android 11 and the above project.
![Picture29](https://user-images.githubusercontent.com/99376012/156136519-35500903-67f6-4c06-8303-e932d8dfb2b5.png)

**Comment by Redth** [comment]
https://user-images.githubusercontent.com/271950/165129834-a9a515b3-e0e3-4573-996c-e2d238bd8cf4.mp4

Looks good here now in main.
