### ISSUE TITLE
Add Test for RefreshView / Scrolling

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#11637]
From: https://github.com/dotnet/maui/pull/11357

We should add a UI Test to cover scrolling + refresh view

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 3.0. Not repro on android platform with sample project.
[3248.zip](https://github.com/dotnet/maui/files/8129962/3248.zip)
![image](https://github.com/dotnet/maui/assets/82450723/cc7ae1a9-9298-4e43-92cc-0977973b2f03)
