### ISSUE TITLE
Application Display Version With Build Number

### ISSUE THREAD

**Issue by Kiryuumaru** [dotnet/maui#11642]
### Description

I was trying to add the build number on ApplicationDisplayVersion `<ApplicationDisplayVersion>0.1.0+build.253</ApplicationDisplayVersion>` but compiler throws an error : ApplicationDisplayVersion '0.1.0+build.253' was not a valid 3 part semver version number and/or ApplicationVersion '253' was not a valid integer.

### Steps to Reproduce

1. Create maui project from template
2. Change ApplicationDisplayVersion with build number `<ApplicationDisplayVersion>0.1.0+build.253</ApplicationDisplayVersion>`
3. Build

### Link to public reproduction project repository

https://github.com/Kiryuumaru/MauiApp1

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All that supports 'ApplicationDisplayVersion'

### Did you find any workaround?

No

**Comment by AndreasReitberger** [comment]
As far as I know the `ApplicationDisplayVersion` has a `Version` type behind it, so it must be formated like this `x.x.x`.
https://learn.microsoft.com/en-us/dotnet/api/system.version?view=net-7.0#constructors

So I guess this is not actually a bug.

**Comment by Kiryuumaru** [comment]
The error throws: `ApplicationDisplayVersion '0.1.0+build.253' was not a valid 3 part semver version number and/or ApplicationVersion '253' was not a valid integer.` says that It was an invalid sevmver version. And `0.1.0+build.253` is a valid semver version standards following this spec (https://semver.org/#spec-item-10)
So I guest `ApplicationDisplayVersion` does not follow the semver version standards

**Comment by AndreasReitberger** [comment]
OK I see.
What happens if you use `0.1.0+alpha.253`?

According to the docs, it say you can add a build number, but I'm not sure if the keyword `build` is needed.

> After the patch version, there are some optional labels we can add to our versions, such as a pre-release label or a build number.

https://www.baeldung.com/cs/semantic-versioning#4-pre-release-and-build

**Comment by NonameMissingNo** [comment]
Hey there, I'm building on .Net 7, and it works just fine.

**Comment by NonameMissingNo** [comment]
Okay, so what's weird, is that a Visual Studio build just swallows it, but a CLI build throws the error.

**Comment by Kiryuumaru** [comment]
> OK I see. What happens if you use `0.1.0+alpha.253`?
> 
> According to the docs, it say you can add a build number, but I'm not sure if the keyword `build` is needed.
> 
> > After the patch version, there are some optional labels we can add to our versions, such as a pre-release label or a build number.
> 
> https://www.baeldung.com/cs/semantic-versioning#4-pre-release-and-build

Yes tried that too.

**Comment by Kiryuumaru** [comment]
> Okay, so what's weird, is that a Visual Studio build just swallows it, but a CLI build throws the error.

I tried it on both .csproj and CLI (using dotnet publish -p:ApplicationDisplayVersion="0.1.0+build.253")

**Comment by espenrl** [comment]
Remember that versioning rules are different for the platforms. See https://github.com/dotnet/Nerdbank.GitVersioning/issues/828

**Comment by mattleibow** [comment]
Thanks folks for all the comments, @espenrl has it right on the head: the mobile platforms are not as flexible as plain .NET. Pretty much the restrictions are:

 - ApplicationDisplayVersion: `#.#.#`
 - ApplicationVersion: `#`
