### ISSUE TITLE
WebAuthenticator doesn't support Azure App Service callback response.

### ISSUE THREAD

**Issue by adrianhall** [dotnet/maui#11641]
### Description

I would like to use WebAuthenticator when also using Azure App Service Authentication.  Unfortunately, EasyAuth does not return the token and expiry in a format that WebAuthenticator understands.  To fix this, I propose that we add a "ResponseDecoder" option to WebAuthenticator.

### Public API Changes

I'd suggest having a new interface `IWebAuthenticatorResponseDecoder`:

```csharp
public interface IWebAuthenticatorResponseDecoder
{
  IDictionary<string, string> DecodeResponseUri(Uri uri);
}
```

Then, in WebAuthenticator, have a new public property:

```csharp
public IWebAuthenticatorResponseDecoder? ResponseDecoder { get; set; }
```

This gets passed as an optional parameter to the constructor of `WebAuthenticatorResult` (the one that gets passed the Uri).  When the response decoder is not null, it is called to convert the Uri into a dictionary (and then everything progresses as normal).  When the response decoder is null, the current method (WebUtils.ParseQueryString()) is used to decode the response.

### Intended Use-Case

Authenticating to Azure App Service when using Azure App Service Authentication & Authorization.

The generalized method proposed allows customers to parse the callback URL for any platform, and allows App Service to release their own package that has the decoder in it if they desire.

**Comment by adrianhall** [comment]
... and I'm happy to contribute a PR for the changes (including tests) if folks think this is the right solution to the problem.

**Comment by mattleibow** [comment]
Do you have an example of the invalid/strange/unique format?

I am wondering if we should also just make the full Uri available as a property. This decoder aspect is very nice, so we should investigate that still. 

> The reason I call this out is that I am not 100% confident that the runtime is still in memory in some cases. I am thinking on Android when the Auth pops the dialog, the app _may_ be stopped. Not sure if that is the _app_ or just the _activity_. Need to test that. But, we do have an await here so even if the entire app is shut down, the code will never run again as the runtime would have unloaded all the code after the await... So maybe I am wrong? Need to talk to my Android experts.

But either way, having a way to intercept the parsing - or escape from it - is a very good idea.

**Comment by JayWilk** [comment]
Yep can totally replicate this.

I set up a server side authenticator following the tutorial on Microsoft Learn: https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?view=net-maui-7.0&tabs=android

When my WebAuthenticator calls my endpoint, via WebAuthenticator.Default.AuthenticateAsync, the API endpoint processes the Auth request then when returning back to the MAUI app - nothing... the MAUI app just freezes and a response is never captured when debugging..
