### ISSUE TITLE
Android: Open App from background -> no shell navigation

### ISSUE THREAD

**Issue by anweihe** [dotnet/maui#11656]
### Description

When sending an Android App to the background and opening it from there, the shell navigation is not working anymore.
Seems only to occur when the debugger is attached.

### Steps to Reproduce

- start app with debugger attached
- click button to navigate (works)
- navigate back
- send app to background
- open app to foreground
- click button
- no navigation

### Link to public reproduction project repository

https://github.com/anweihe/maui_background_bug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Pixel 4 API 32

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. This issue does not repro on Android 13.0-API33 with below Project:
[MauiBackgroundBug.zip](https://github.com/dotnet/maui/files/11684655/MauiBackgroundBug.zip)
![background](https://github.com/dotnet/maui/assets/97647558/2f423a1f-c1fc-4a4e-9ab3-c12ef009d7cc)
