### ISSUE TITLE
When two control views overlap, setting the opacity  and TranslationY properties is invalid

### ISSUE THREAD

**Issue by xyeie** [dotnet/maui#11658]
### Description

It is normal when it is hot reload, but the expected effect will not be achieved when it is restarted.

### Steps to Reproduce

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">

    <ScrollView>
        <VerticalStackLayout Margin="15,0,15,0">

            <Grid RowDefinitions="*"
                  VerticalOptions="Center"
                  HeightRequest="150">
                <Frame Grid.Row="0" 
                       BackgroundColor="Black">
                    
                </Frame>
                <Frame Grid.Row="0"
                       BackgroundColor="Beige"
                       Opacity="0.9"
                       TranslationY="40">
                    
                </Frame>
            </Grid>

        </VerticalStackLayout>
    </ScrollView>

</ContentPage>

Modify xaml at runtime, and the result is normal. However, if you re run the program, you will not get the expected results.

### Link to public reproduction project repository

no

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android11 and up

### Did you find any workaround?

 no

### Relevant log output

```shell
no
```

**Comment by xyeie** [comment]
![实际](https://user-images.githubusercontent.com/105901371/204004136-27a74f9d-30f0-4dcd-ad83-d27ba43eae91.png)
The actual effect is shown in the figure
![预期](https://user-images.githubusercontent.com/105901371/204004417-4d54b1e1-b653-4f91-b65b-83bbaf4f75f2.png)
The expected effect is as shown in the figure

**Comment by xyeie** [comment]
尊敬的客户您好，您的信息已收到，请务必加入咱们的微信学习群，进群学习哦

**Comment by jsuarezruiz** [comment]
Testing it with the latest version:
![image](https://user-images.githubusercontent.com/6755973/228828715-8adec3cf-9e84-4350-85ea-a095049af9ed.png)

The second Frame is translated and have the opacity, seems correct. Is your result?

**Comment by xyeie** [comment]
尊敬的客户您好，您的信息已收到，请务必加入咱们的微信学习群，进群学习哦

**Comment by xyeie** [comment]
Thank you very much. This issue has been resolved
