### ISSUE TITLE
MAUI App is there any tool from Microsoft which supports MAUI GUI Automation?

### ISSUE THREAD

**Issue by Giri1102** [dotnet/maui#11650]
### Description

We have developed Windows Desktop application(Win3) using MAUI.
Now we have query like planning to do GUI automation using python language.

For UWP App we’ve used Windows Application Driver with Appium for GUI Automation

Similarly for MAUI App is there any tool from Microsoft which supports MAUI GUI Automation?

### Public API Changes

NA

### Intended Use-Case

NA

**Comment by jfversluis** [comment]
We don't have anything currently. The platform native tools should work as a .NET MAUI app delivers all platform controls at the end of the day. There are some initiatives here and there but nothing we can share at this moment.

**Comment by samhouts** [comment]
Duplicate of #11236
