### ISSUE TITLE
[Bug] MAUI Essentials GetLocationAsync doesn't work - throws error

### ISSUE THREAD

**Issue by naweed** [dotnet/maui#1166]
### Description

I am not able to use GetLocationAsync in MAUI Essentials. It throws an error that "The current Activity can not be detected. Ensure that you have called Init in your Activity or Application class."

### Steps to Reproduce

Run the following code:

            //Try to get My Current Location                    
            try
            {
                location = await Geolocation.GetLocationAsync();
            }
            catch (Exception ex)
            {
                // Unable to get location
                // Default to Bahrain location
                location = new Location(26.20397160522508, 50.56526549999999);
            }

### Expected Behavior

The app should launch and ask for location permissions.

### Actual Behavior

It goes into the exception block with the following error:
"System.NullReferenceException: The current Activity can not be detected. Ensure that you have called Init in your Activity or Application class.
   at Microsoft.Maui.Essentials.Platform.GetCurrentActivity(Boolean throwOnNull)"

### Basic Information

- Version with issue: 6.0.100-preview.4.*
- Last known good version: N/A
- IDE: Visual Studio 16.11.1 Preview-1
- Platform Target Frameworks: 
  - iOS
  - Android
- Affected Devices: Samsung S20+ Physical device

### Other Info

Testing against a physical device (Samsung S20+)

**Comment by iConfesss** [comment]
I ran into the same issue. I resolved it by following the docs on https://docs.microsoft.com/en-us/xamarin/essentials/geolocation but using Maui Essentials instead of Xamarin.

After modifying the MainActivity.cs within the Android platform folder it asks me for location permission.

**Comment by VincentBu** [comment]
repro on Android & IOS. it might be related to permission. I'm not sure how to set permission for IOS, but for android simulator, you can add following content in `AndroidManifest.xml`:
```
<uses-feature android:name="android.hardware.location.gps" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

**Comment by jfversluis** [comment]
@VincentBu or others, could you please provide a reproduction project? Because I can't seem to get this issue to show up

**Comment by VincentBu** [comment]
> could you please provide a reproduction project? Because I can't seem to get this issue to show up

Here is the repro project: [MauiApp1.zip](https://github.com/dotnet/maui/files/8182440/MauiApp1.zip)
Click on 'Get Location' button, you will get error message like this:
![image](https://user-images.githubusercontent.com/44959937/156684430-256f36cc-8eee-45dc-84ce-2031ecf9d816.png)

then, add
```
<uses-feature android:name="android.hardware.location.gps" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```
to `AndroidManifest.xml` and run again, you would get the expect result:
![image](https://user-images.githubusercontent.com/44959937/156684568-5365a2cd-3cca-4215-bde2-5238295cd380.png)

**Comment by naweed** [comment]
This was a very old issue. May be there was a bug in that build. Plz close.
