### ISSUE TITLE
Is `AppDomain.CurrentDomain.ProcessExit` supposed to work on macOS (maccatalyst)?

### ISSUE THREAD

**Issue by MartyIX** [dotnet/maui#11676]
### Discussed in https://github.com/dotnet/maui/discussions/11670

<div type='discussions-op-text'>

<sup>Originally posted by **MartyIX** November 25, 2022</sup>
Hi, 

I have tried to register the `ProcessExit`  event in my MAUI app running on macOS (maccatalyst) but it is *not* called:

```cs
using System;

public partial class App : Application
{
    public App()
    {
        InitializeComponent();

        MainPage = new AppShell();

        AppDomain.CurrentDomain.ProcessExit += this.OnProcessExit;
    }

    // This method is not called on macOS but it is called on Windows.
    private void OnProcessExit(object sender, EventArgs e)
    {
        throw new Exception("REACHED?");
    }
}
```

Does anybody know why it is *not* being called on macOS? 

Interestingly, I can see that `AppDomain.CurrentDomain.ProcessExit` event is fired in .NET MAUI on Windows.</div>

edit: I filed also https://github.com/dotnet/runtime/issues/78911 to know whether it is more a MAUI issue or a runtime issue. I can't tell.

**Comment by PureWeen** [comment]
Closing in favor of runtime issue
