### ISSUE TITLE
[iOS] Spacing between `Header` and `FlyoutItems` on iOS only

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#11679]
### Description

When I'm running my app on iOS, I get a space between the `HeaderTemplate` and the first `FlyoutItem`.
Running the same project on Android is working fine.

```cs
<Shell.FlyoutHeader>
        <Grid
            HeightRequest="92"
            BackgroundColor="{AppThemeBinding Light={StaticResource Gray800}, Dark={StaticResource Gray200}}"
            >
            <Label
                Text="Just a simple header"
                TextColor="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource White}}"
                />
        </Grid>
    </Shell.FlyoutHeader>

    <FlyoutItem
        Title="MainpPage" 
        >
        <ShellContent
            ContentTemplate="{DataTemplate local:MainPage}"
            Route="DashboardPage"
            />
    </FlyoutItem>
```

iOS 

![2022-11-27_07-34-39-](https://user-images.githubusercontent.com/2952443/204122716-583f6dd3-a269-4e96-87dd-a8520eb1d76a.png)

Android

![Screenshot_1669531325](https://user-images.githubusercontent.com/2952443/204122831-8045aa9d-7d33-4f8f-b944-48048de933d4.png)

### Steps to Reproduce

1. User the repro provided
2. Run on Android and iOS
3. Compare both flyout menus

### Link to public reproduction project repository

https://github.com/AndreasReitberger/ReproScrollingIssueModal

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16, haven't tried any older version

**Comment by nebula2** [comment]
why the heightrequest on the grid? how does it behave when you remove that?

**Comment by AndreasReitberger** [comment]
> why the heightrequest on the grid? how does it behave when you remove that?

Removing the `HeightRequest` results in the same output.

![2022-11-29_08-16-25-](https://user-images.githubusercontent.com/2952443/204463770-18506e7e-9705-4ae4-bb4d-9d74db75fbc0.png)

**Comment by GnanaPriyaNamasivayam** [comment]
When can we expect this fix to live, Any idea?

**Comment by Greg-Bates-Trimble** [comment]
Just following up on this. Is there any update on when this fix will go live? Thanks

**Comment by GnanaPriyaNamasivayam** [comment]
Any update on when is the new ongoing release is expected to live.
