### ISSUE TITLE
Stacklayout leaves layout space for items whose IsVisible=false

### ISSUE THREAD

**Issue by edgiardina** [dotnet/maui#11678]
### Description

Given the following Stacklayout with three buttons, I'd expect that if one of the buttons was marked isvisible=false, that the layout would not reserve layout space in the stacklayout for the invisible button. (that's the case in Xamarin Forms). However, MAUI appears to generate a layout for a button that's not visible.

```  
<StackLayout Orientation="Horizontal">
                <Button Margin="10,0" Text="Button 1" HorizontalOptions="FillAndExpand" />
                <Button Margin="10,0" Text="Button 2" HorizontalOptions="FillAndExpand" />
                <Button Margin="10,0" Text="Button 3" HorizontalOptions="FillAndExpand" IsVisible="False" />
            </StackLayout>
 ```
            
            
![image](https://user-images.githubusercontent.com/3627193/204112186-23532718-6e8c-4ce3-934d-18dc881f7e37.png)

            

### Steps to Reproduce

1. Create a File -> New MAUI project
2. Create a horizontal stacklayout with three buttons
3. mark one button's isvisible as false
4. Expected result would be the two remaining visible buttons that stretch the width of the Stacklayout
5. Actual result is that the invisible button still is laid out and has reserved space. 

### Link to public reproduction project repository

https://github.com/edgiardina/StackLayout_IsVisible_Bug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

all platforms

### Did you find any workaround?

No workaround I can see

**Comment by nebula2** [comment]
have you tried using a grid as a workaround?

StackLayout is cursed as well as FillAndExpand

**Comment by edgiardina** [comment]
@nebula2 I'm unsure how I'd get the desired behavior in a grid. If I use a three column grid with 'Auto' sizes, I still get buttons that don't stretch the entire width

```
 <Grid ColumnDefinitions="Auto,Auto,Auto">
                        <Button Grid.Column="0" Margin="10,0" Text="Results" Clicked="TournamentResults_Button_Clicked" />
                        <Button Grid.Column="1" Margin="10,0" Text=" PVP " Clicked="Pvp_Button_Clicked" />
                        <Button Grid.Column="2" Margin="10,0" Text="Champ. Series" Clicked="CS_Button_Clicked" IsEnabled="{Binding HasChampionshipSeriesData}" IsVisible="{Binding HasChampionshipSeriesData}" />
                    </Grid>
```

yields the following results. Really what I want is the buttons to appear the entire width of the phone side by side. Stacklayout accomplished this in Xamarin Forms. It's not an uncommon pattern; I have no idea how wide the device(s) that this will run on, but I do want a uniform appearance. 
(Screenshot here with the Grid as commenter suggested)

![image](https://user-images.githubusercontent.com/3627193/204141568-c6c0f1e2-d40a-4611-8039-6e4ce542d1bc.png)

**Comment by nebula2** [comment]
> @nebula2 I'm unsure how I'd get the desired behavior in a grid. If I use a three column grid with 'Auto' sizes, I still get buttons that don't stretch the entire width

Jeah, that will not work.

Would need to build the grid programmatically with * width instead of auto.

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/grid?view=net-maui-7.0

Not sexy, but that should at least get you going

**Comment by edgiardina** [comment]
@nebula2  Sure, I could, in the Page codebehind, do the math manually. That makes it more of a pain to restyle later. But the main point is that this worked for the most part in Xamarin Forms. Why is there a departure here in MAUI? Why are layout options considered "cursed" yet available to use? 

It's been a frustrating road unfortunately in my attempt to migrate a small hobby project from Xamarin Forms to MAUI (definitely over 50 hours now for the migration, if not more). The layout engine seems to have under the covers been subtly changed such that stacklayouts are not really usable. Stacklayouts were IMHO a great solution to the fragmentation of mobile display sizes. declaring discrete widths/heights and calculating my own layouts instead of using XAML goes against the spirit of the x-plat project. It wouldn't be so bad to change all the stacklayouts to grids if we didn't already have the Xamarin Forms standard to see how it *should* work, vs how MAUI works. 

There have been a lot of confusing design decisions for MAUI that have made switching painful and I don't understand the underlying philosophy behind them. Why is MAUI tied to the .net workflow version and not a nuget package like forms? The mobile frameworks shift quickly as vendors change them, and waiting until .NET releases in november isn't an option IMHO. Why did stacklayouts get nerfed in MAUI?

**Comment by nebula2** [comment]
@edgiardina I don't know :/ I struggled very hard to create a stable app using MAUI (with lots of experience using Xamarin) and I have collected quite an amount of workarounds..

**Comment by hartez** [comment]
> Really what I want is the buttons to appear the entire width of the phone side by side.

Try this:

```
<Grid ColumnDefinitions="*,*,*">
  <Button Grid.Column="0" Margin="5,5" Text="Results"  />
  <Button Grid.Column="1" Margin="5,5" Text=" PVP "  />
  <Button Grid.Column="2" Margin="5,5" Text="Champ. Series" IsVisible="{Binding HasChampionshipSeriesData}" />
</Grid>
```

**Comment by edgiardina** [comment]
@hartez I tried this and it still leaves space for the third column / button., I'd actually not expect three columns with * to work, doesn't * indicate a percentage type width? I would think three columns with * definitions would yield three equal sized columns. The reason I also attempted three 'Autos' is that it should take into account the size of the elements (and an element with isvisible false should have zero size).

**Comment by affableashish** [comment]
> @nebula2 Sure, I could, in the Page codebehind, do the math manually. That makes it more of a pain to restyle later. But the main point is that this worked for the most part in Xamarin Forms. Why is there a departure here in MAUI? Why are layout options considered "cursed" yet available to use?
> 
> It's been a frustrating road unfortunately in my attempt to migrate a small hobby project from Xamarin Forms to MAUI (definitely over 50 hours now for the migration, if not more). The layout engine seems to have under the covers been subtly changed such that stacklayouts are not really usable. Stacklayouts were IMHO a great solution to the fragmentation of mobile display sizes. declaring discrete widths/heights and calculating my own layouts instead of using XAML goes against the spirit of the x-plat project. It wouldn't be so bad to change all the stacklayouts to grids if we didn't already have the Xamarin Forms standard to see how it _should_ work, vs how MAUI works.
> 
> There have been a lot of confusing design decisions for MAUI that have made switching painful and I don't understand the underlying philosophy behind them. Why is MAUI tied to the .net workflow version and not a nuget package like forms? The mobile frameworks shift quickly as vendors change them, and waiting until .NET releases in november isn't an option IMHO. Why did stacklayouts get nerfed in MAUI?

Interested to get an answer to these questions by someone from the team. @davidortinau

**Comment by edgiardina** [comment]
Interesting, when I try @hartez 's structure, the buttons still aren't lining up as I expect, but then also they don't respond to clicks /fire their event handlers anymore on iOS. Putting them back in the stacklayout fixes it

**Comment by hartez** [comment]
> @hartez I tried this and it still leaves space for the third column / button., I'd actually not expect three columns with * to work, doesn't * indicate a percentage type width? I would think three columns with * definitions would yield three equal sized columns. The reason I also attempted three 'Autos' is that it should take into account the size of the elements (and an element with isvisible false should have zero size).

Sorry, I misunderstood the initial description of the problem.

**Comment by hartez** [comment]
Okay, looks like we have a bug in the AndExpandLayoutManager; it shouldn't be creating columns/rows for invisible views. Should be a fairly simple fix.

In the meantime, you can achieve the same effect with a Grid using a Binding for ColumnDefinitions, either directly to a property on your model or to your `HasChampionshipSeriesData` property via an IValueConverter.

**Comment by hartez** [comment]
Alternatively, you could handle this with a [data trigger](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/triggers?view=net-maui-7.0#data-triggers), something like this:

```
<Grid >
    <Grid.Triggers>
        <DataTrigger TargetType="Grid"
                    Binding="{Binding Source={x:Reference ChampButton}, Path=IsVisible}" Value="True">
            <Setter Property="ColumnDefinitions" Value="*,*,*" />
        </DataTrigger>
        <DataTrigger TargetType="Grid"
                    Binding="{Binding Source={x:Reference ChampButton}, Path=IsVisible}" Value="False">
            <Setter Property="ColumnDefinitions" Value="*,*" />
        </DataTrigger>
    </Grid.Triggers>

    <Button Grid.Column="0" Margin="5,5" Text="Results" />
    <Button Grid.Column="1" Margin="5,5" Text=" PVP " />
    <Button Grid.Column="2" Margin="5,5" Text="Champ. Series" x:Name="ChampButton" IsVisible="{Binding IsVisible}" />
</Grid>
```

**Comment by hartez** [comment]
> Why is there a departure here in MAUI? Why are layout options considered "cursed" yet available to use?

The "AndExpand" options have always been awkward:

- From the name, it's not obvious what they actually _do_. 
- Their inclusion in the LayoutOptions enumeration meant they were available on any View in any container, despite the fact that they only affect StackLayout. 
- Forms is the only platform which includes this alternate behavior to force a stacking layout to subdivide an area in the stacking direction, which makes things extra confusing for users coming from other platforms.
- They make the actual implementation of StackLayout complex and difficult to maintain

So for simplicity, easier maintenance, and performance reasons, "AndExpand" is not part of MAUI.Core's layout system. Other SDKs (AlohaKit, Comet, etc.) don't have to use "AndExpand" or account for it. 

"AndExpand" remains available (and functional) in the StackLayout in MAUI.Controls for the convenience of users migrating from Forms. Aside from a couple of bugs we've hit in porting it to MAUI.Controls, the functionality is identical. 

> The layout engine seems to have under the covers been subtly changed such that stacklayouts are not really usable.

> Why did stacklayouts get nerfed in MAUI?

As I said upthread, this particular issue is a bug in the AndExpand implementation in MAUI.Controls. A fix is in the works. StackLayouts should function as expected if you're migrating from Forms. Anywhere else that they aren't, please open an issue and we'll take a look.

> Stacklayouts were IMHO a great solution to the fragmentation of mobile display sizes. declaring discrete widths/heights and calculating my own layouts instead of using XAML goes against the spirit of the x-plat project.

I encourage you to take a look at our other options for handling multiple display sizes and triggering layout changes from XAML (e.g., [Triggers](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/triggers?view=net-maui-7.0)).

**Comment by edgiardina** [comment]
Thank you for the prompt attention this bug received. The Grid workaround was a clever solution I had not thought of as well. We've used Triggers for a number of properties but for some reason row definitions had not occurred to me as triggerable.
