### ISSUE TITLE
Blazor Maui : "<audio />" tag doesn't show screen lock notification on Android

### ISSUE THREAD

**Issue by abdu292** [dotnet/maui#11675]
### Description

It appears that the lock screen notification is not displayed on Android when audio is played. However, playing an audio on a web browser using audio tag will give you the notification on Android. Should this be default to Maui Blazor app as the framework uses a web browser to play the audio?

### Steps to Reproduce

Repro:

[ReproPlaybackNot.zip](https://github.com/dotnet/maui/files/10096587/ReproPlaybackNot.zip)

On windows it shows a media playback notification bar, but not on Android.

### Link to public reproduction project repository

https://github.com/dotnet/maui/files/10096587/ReproPlaybackNot.zip

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 12 Emulator

### Did you find any workaround?

Not really.

### Relevant log output

```shell
N/A
```

**Comment by javiercn** [comment]
@abdu292 thanks for contacting us.

Does the same behavior happen when you try to do this on a regular webview control? (No Blazor involved).

**Comment by abdu292** [comment]
@javiercn Thanks for the response. Yes the behavior is the same even on the regular WebView control on a standard Maui project.

If I navigate to the below link on a chrome browser, it shows the notification (expected behavior) as the audio plays. However on a standard Maui project with a regular WebViewControl it doesn't work and says "Media Session API is not yet available". Does this mean maui uses an older version of browser? Is there any way I can use the latest chrome on Maui/Blazor project? 
Thanks a bunch!

https://googlechrome.github.io/samples/media-session/audio.html

![image](https://user-images.githubusercontent.com/13116312/204268115-526a2f82-ca4a-4be8-ab57-c17cbc6cc976.png)

**Comment by drasticactions** [comment]
@abdu292 Can you repro this on a Android app that doesn't use MAUI? (ex `dotnet new android`). AFAIK, the MAUI WebView for Android is the Android System WebView (https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US&gl=US), which is the standard webview for Android. My guess is that if you build a straight Android app using the webview you would end up with the same state.

**Comment by abdu292** [comment]
Thanks @drasticactions for the response I tried on a dotnet android native project and the behavior appears to be the same.
Here is the repro.

[WebViewAndroid.zip](https://github.com/dotnet/maui/files/10139686/WebViewAndroid.zip)

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-android#7895
