### ISSUE TITLE
Impossible to add the background gradients feature on ContentPage iOS

### ISSUE THREAD

**Issue by samirgcofficial** [dotnet/maui#11714]
### Steps to Reproduce

Add this code to any of the content page

` <ContentPage.Background>
        <LinearGradientBrush EndPoint="0,1">
            <GradientStop Color="Yellow"
                          Offset="0.1" />
            <GradientStop Color="Green"
                          Offset="1.0" />
        </LinearGradientBrush>
    </ContentPage.Background>
    <ContentPage.Content>
        <Label Text="I love MAUI"
               VerticalOptions="CenterAndExpand"
               HorizontalOptions="CenterAndExpand"/>
    </ContentPage.Content>`

### Link to public reproduction project repository

https://github.com/samirgcofficial/GradientBugMAUI

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 14

### Did you find any workaround?

https://gist.github.com/vhugogarcia/b49af71df1e339626f758479d836b45a

**Comment by matt-goldman** [comment]
I've noticed this too. On iOS a gradient background doesn't apply at startup, but Hot Reload will apply it if you change it at runtime.

I have a repro I can share privately if needed.

Possibly related: #10445
