### ISSUE TITLE
Binding does not work for Platform dependent Behaviors

### ISSUE THREAD

**Issue by YMichurin** [dotnet/maui#11729]
### Description

Binding to observable property does not work in platform behaviors. Try any platform behavior community mvvm toolkit provides:

https://github.com/CommunityToolkit/Maui/tree/main/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors

or create your own, you would get the same result. 

Here is an original stackoverflow thread https://stackoverflow.com/questions/74607699/binding-does-not-work-for-platform-dependent-behaviors

### Steps to Reproduce

Take for example `StatusBarBehavior`, write something like

```
    <ContentPage.Behaviors>
        <toolkit:StatusBarBehavior StatusBarColor="{Binding StatusBarColorProp}" StatusBarStyle="LightContent" />
    </ContentPage.Behaviors>
```

create the property in your view model
```
    [ObservableProperty]
    private Color _statusBarColorProp;
```
Update the property value in code-behind or model like `StatusBarColorProp=Color.FromRgb(255,0,0)`. You'll see status bar color does not change with StatusBarBehavior property change in runtime. Same for all the rest of behaviors. It works fine for non-bindings setters like StatusBarColor="Red". 

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

at least Android API 32 that I tested on, but does not seem to be platform dependent

### Did you find any workaround?

interestingly while binding does not work for viewmodel, it does if you bind it to other control.

For example if you take BlurBehaviour from the repository https://github.com/VladislavAntonyuk/MauiSamples/tree/main/MauiImageEffects.

This code works fine:
```
<Image.Behaviors>
   <bh:BlurBehavior Radius="{Binding Value, Source={x:Reference imageBlurSlider}}"/>
</Image.Behaviors>
```

But this one does not
```
<Image.Behaviors>
   <bh:BlurBehavior Radius="{Binding MyMvvmBlurProperty}"/>
</Image.Behaviors>
```

**Comment by rachelkang** [comment]
This issue was moved to CommunityToolkit/Maui#795
