### ISSUE TITLE
Label binding not works in collectionview in release mode

### ISSUE THREAD

**Issue by emanuelevaini** [dotnet/maui#11726]
### Description

Hello,
I created an app to scan bluetooth devices around, so I created a collectionView to show the list of those nearby devices. I use the MVVM pattern for my app.
The data template of the collectionView has both static and bindable text.
In debug mode all seems work perfectly, but in release mode it seems that bindable elements are not shown (even if the relative device is added to the collectionView).

### Steps to Reproduce

1. Create a new NET Maui app.
2. In XAML of the MainPage add a CollectionView and set its ItemSource to an ObservableCollection with different properties (in my case, "NAME" and "ID")
3. Define ItemTemplate->DataTemplate with a grid with several labels, binding its text to device property and define the DataType
4. Populate the collection view and test the app both in debug and in release mode

```xaml
<CollectionView  ItemsSource="{Binding DEVICES_OBSERVABLE_COLLECTION}">
                <CollectionView.ItemTemplate>
                    <DataTemplate >
                        <Grid 
                            ColumnDefinitions="Auto, *, Auto" 
                            RowDefinitions="Auto, Auto" >
                            <Label
                                Grid.Column="0"  
                                Margin="0,0,4,0"  
                               x:DataType="models:RemoteDevice"
                                FontSize="24" 
                                Text="staticText"                       
                                VerticalOptions="Start" />
                            <StackLayout Grid.Column="1" Orientation="Vertical" x:DataType="MODELS:REMOTEDEVICES">
                                <Label  Text="{Binding DEVICE_NAME}"      />
                                <Label  Text="{Binding DEVICE_ID}"  />
                            </StackLayout>                         
                            <!--<Grid.Behaviors>
                                <behaviors:TapToCommandBehavior Command="{Binding DeviceSelectedCommand}" CommandParameter="{Binding .}" />
                            </Grid.Behaviors>-->
                        </Grid>
                    </DataTemplate>

                </CollectionView.ItemTemplate >
            </CollectionView>

```
5. Verify that DEVICE_NAME and DEVICE_ID are visible in debug mode but not in release mode

### Link to public reproduction project repository

http:\\

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

All Android platforms

### Did you find any workaround?

Unfortunately not yet.

### Relevant log output

```shell
None
```

**Comment by rmotta01** [comment]
Are you understaffed?

https://github.com/rmotta01/MauiBugBtnImgSource01
