### ISSUE TITLE
How to customize the default installation path of packaged programs

### ISSUE THREAD

**Issue by Aspire0423** [dotnet/maui#11728]
### Description

I use maui to develop Windows desktop applications, but when I run it after I package it as msix, it does not let me choose the installation directory, which is all the default installation directory

### Public API Changes

new PublishPath()

### Intended Use-Case

like publish is other or default directory

**Comment by mattleibow** [comment]
For an MSIX, I am not sure this is possible: https://techcommunity.microsoft.com/t5/msix/msix-set-installation-path/m-p/3044888/highlight/true#M1389

> The installation path of an MSIX package cannot be changed. All the files you have included in your package are installed inside an app-specific folder under "C:\Program Files\WindowsApps<your app>\".
This is a design decision from Microsoft. Only for MSI/EXE installers you can change the install path.

If you want to control the install location, you need to make an unpackaged app and use your own installer (msi). Maybe have a look at this: https://blog.verslu.is/maui/dotnet-maui-windows-unpackaged-apps
