### ISSUE TITLE
[Bug] XAML Hot Reload not working on Windows VS 2022

### ISSUE THREAD

**Issue by matheus-blank-BTG** [dotnet/maui#11743]
### Description

XAML Hot Reload and Live Preview not working on Windows. Tested on latest VS Professional 2022 17.4.2 and MAUI workload installed by the Visual Studio Installer

I tried uninstalling, reinstalling and cleaning up everything .NET and VS related, didn't help.

### Steps to Reproduce

Create new MAUI sample app
Run
Try changing something, like the text in my screenshots
Expected Behavior
XAML Hot reload working, like in every MAUI promotional video made in past several months...

### Link to public reproduction project repository

https://github.com/dotnet/maui/blob/main/.github/repro.md

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

No

**Comment by mouralabank** [comment]
I am getting this same issue as well

**Comment by danielancines** [comment]
The same problem here after update from Preview.

**Comment by nmushovic** [comment]
The same problem here. Hot Reload not working after upgrading from 17.4.0 to 17.4.2.

**Comment by drasticactions** [comment]
- XAML Live Preview depends on XAML Hot Reload being connected and working. If that fails, XAML Live Preview will fail.
- Which platforms have you tried to use? WinUI? Android? iOS?

**Comment by mouralabank** [comment]
@drasticactions WinUI. Yes WinUI Hot Reload fail too.

**Comment by drasticactions** [comment]
> @drasticactions WinUI. Yes WinUI Hot Reload fail too.

Awesome! MAUI Hot Reload on WinUI depends on WinUI Hot Reload also working, so if that fails... then that would explain that. Does Android and/or iOS work?

**Comment by drasticactions** [comment]
For WinUI, your issue may be related to this: https://developercommunity.visualstudio.com/t/In-app-toolbar-not-appearing/10202670

There is a workaround posted there:

> Open a Powershell Admin window on your machine
Run ‘get-appxpackage -name *WindowsAppRuntime*’
Locate Microsoft.WindowsAppRuntime.1.1 and Microsoft.WindowsAppRuntime.1.2, installation location (ex: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1005.616.1651.0_x64__8wekyb3d8bbwe)
run the command below in an Admin command prompt
takeown /f “C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1003.565.600.0_x64__8wekyb3d8bbwe” /r /d y
icacls.exe “C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1003.565.600.0_x64__8wekyb3d8bbwe” /grant Users:(RD,R,REA,RX) /t

> Make sure the path specified match the InstallLocation reported by ‘get-appxpackage -name *WindowsAppRuntime’

**Comment by mouralabank** [comment]
@drasticactions Thanks, I followed the walkthrough, but it's still not working. I'll look for more on this, if you find anything, please let me know

**Comment by mouralabank** [comment]
@drasticactions after reboot I tried again and now it worked! Thanks!
![image](https://user-images.githubusercontent.com/116117838/204680300-ac808faa-a2b6-4b59-a776-2b740e7b38e7.png)

**Comment by danielancines** [comment]
@drasticactions Thank you for your help, it worked for me too.

**Comment by YiannisBourkelis** [comment]
Same issue here. Hot reload is working on VS Mac while debugging iOS/Android/Mac app, but is not working on Visual Studio on Windows when debugging a UWP app. 

In general hot reload is not working as expected. Sometimes I have to re-compile the app to make it work. Many issues also when a page has a <ScrollView>. Changing something makes scrolling stop working. I am fighting every day with it.

**Comment by drasticactions** [comment]
> In general hot reload is not working as expected. Sometimes I have to re-compile the app to make it work. Many issues also when a page has a `<ScrollView>`. Changing something makes scrolling stop working. I am fighting every day with it.

File bugs for them and we'll figure out where they go. If you wanna be proactive about if it's a MAUI or Hot Reload bug, try replicating your Hot Reload actions with code behind functions. For example, if you're adding elements to a scroll view with XAML Hot Reload, and scrolling stopps working when you do, try dynamically adding elements to the scroll view through C# (Like, make a button on the page that adds a new element to the scroll view through its click handler)

If you can repro it outside of XAML / C# Hot Reload, it will be a MAUI bug that will be fixed in this repo. If it only happens within the context of XAML Hot Reload, it will go to VS Feedback and fixed internally.

**Comment by JohnHunterACS** [comment]
Does anyone know how to downgrade from 17.4.2 to 17.4.1 ?  I really need Hot Reload for a demo to the Product Board in a few weeks time.

**Comment by valimaties** [comment]
Check in Visual Studio installer. Start VS installer and press on "more" option

**Comment by JohnHunterACS** [comment]
@valimaties Cheers.  I had completely forgotten that feature had been added.  Anyway, back on 17.4.1 but it hasn't fixed the issue.   I'm guessing there's something that was registered during the 17.4.2 upgrade that has been left hanging around.  I've tried @drasticactions workaround but no luck with that either.
