### ISSUE TITLE
Image does not load a specific URI only on Android and UWP platform.

### ISSUE THREAD

**Issue by SVRagul** [dotnet/maui#11749]
### Description

- Image control does not loads the image from URI ->https://tile.openstreetmap.org/1/0/0.png
- But, it is working fine in the iOS and Mac Platform.
- Please refer the below code example.

```
Image image = new Image
{
    Source = ImageSource.FromUri(new Uri("https://tile.openstreetmap.org/1/0/0.png"))
};
```

### Steps to Reproduce

1. Create a project.
2. Create a image control like below.
```
Image image = new Image
{
    Source = ImageSource.FromUri(new Uri("https://tile.openstreetmap.org/1/0/0.png"))
};
```
3. Run the sample.
4. Image will not be loaded on Android and UWP platform.

Actual Result: Image not loaded.
Expected: Image to be loaded.

### Link to public reproduction project repository

https://github.com/SVRagul/ImageControlDemo

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 12

### Did you find any workaround?

No

**Comment by hartez** [comment]
Debugging this on Windows, and the request is coming back with a 403 (Forbidden). Works fine in a browser, which makes me wonder if it's a user agent filtering issue.

**Comment by hartez** [comment]
Confirmed - if I go into UriImageSource and add custom request headers to the HttpClient, the image downloads just fine:

```
using var client = new HttpClient();
client.DefaultRequestHeaders.UserAgent.ParseAdd("My App Headers");
```

There's currently no API for customizing the HttpClient settings in UriImageSource, so if you want to download OSM tiles you'll need to manually create your own HttpClient instance to do the image downloading manually, write a custom image source, or maybe try a 3rd-party library.
