### ISSUE TITLE
Have easy way to set initial BlazorWebView URL

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#11746]
## Background

When BlazorWebView initializes Blazor itself, the first thing it does is navigate to `/` (examples: [MAUI Windows](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Windows/BlazorWebViewHandler.Windows.cs#L86), [MAUI Android](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs#L123), [WinForms](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/WindowsForms/BlazorWebView.cs#L196)).

If you want the initial URL to be something different, you have to do it entirely manually, which in my view is not so obvious.

It's useful to have a custom start page when your app is built around one main Razor component that represents the app, but you want to take the user straight to a specific page within the Blazor navigation space. This could be due to deep-linking from an external location, multi-window apps (e.g. pop open a new window to show a specific order's details, etc.).

## Workaround

Here's how to do it manually in MAUI (very similar on WinForms/WPF as well):

1. Change the default `Main.razor` file to accept an optional `StartPath` property, and call `NavigationManager.NavigateTo` if it is set:
    ```c#
    @inject NavigationManager NavigationManager

    <!-- normal router stuff here -->
    <Router ...>
    </Router>

    @code
    {
        [Parameter] public string StartPath { get; set; }

        protected override void OnParametersSet()
        {
            if (!string.IsNullOrEmpty(StartPath))
            {
                NavigationManager.NavigateTo(StartPath);
            }

            base.OnParametersSet();
        }
    }
    ```
2. In `MainPage.xaml.cs` set the root component's parameters to indicate which, if any, custom start path to use:
    ```c#
    public MainPage()
    {
        InitializeComponent();

        blazorWebView.RootComponents[0].Parameters = new Dictionary<string, object>
        {
            { "StartPath", "/counter" }, // hard-code this, or get its value dynamically from somewhere
        };
    }
    ```

## Proposal

This could possibly be done more easily if each `BlazorWebView` control had a new `StartPath` property that would be used for the initial navigation (instead of always navigating to `/`):

```c#
public class BlazorWebView : ...
{
    public string? StartPath { get; set; }
}
```

**Comment by ismasanchez** [comment]
There's a "hidden bug" with this proposal in relation to https://github.com/dotnet/maui/issues/12171 .
Once NavigateTo is fired, if you navigate to another page and press the back button twice on android, router will try to find the root page and will find nothing, so you will get the route note found component:
```
	<NotFound>
		<LayoutView Layout="@typeof(MainLayoutUtils)">
			<p role="alert">Sorry, there's nothing at this address.</p>
		</LayoutView>
	</NotFound>
```
This is one of the reasons why https://github.com/dotnet/maui/issues/12171 is important among others potential use cases.
