### ISSUE TITLE
Problem Geocoding Address

### ISSUE THREAD

**Issue by mancda** [dotnet/maui#11756]
### Description

Using VS 2022 ver 17.4.2 and deploying my Maui app to my physical device (Microsoft Duo 1), I am getting System.NullReferenceException
Message=Object reference not set to an instance of an object

using the following code

string address = "Microsoft Building 25 Redmond WA USA";
var m = await Geocoding.Default.GetLocationsAsync(address);

Thanks for your help

### Steps to Reproduce

See above

### Link to public reproduction project repository

This should be readily reproducible without 

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android platform 12

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
[MauiProgram.zip](https://github.com/dotnet/maui/files/10129730/MauiProgram.zip)

I tried to repro it on the newest MAUI stable and I couldn't. Does my project run for you @mancda?

**Comment by janseris** [comment]
On Windows it's missing MapServiceToken, on Android 12 emulator it's grpc call failed.
VS 17.4.0

**Comment by mancda** [comment]
The program [MauiProgram.zip](https://github.com/dotnet/maui/files/10129730/MauiProgram.zip) worked fine on my device.  I moved the code to a different location in my project and it worked.  I have not been able to pin down why it was not working in the first code location.

**Comment by mattleibow** [comment]
Thanks, I'll close this for now, feel free to open a new issue (or this one again) if it reappears.

Maybe we fixed a bug in a version of maui and then the VS updated to a new version with the fix?
