### ISSUE TITLE
No iPhone simulators show in vs for mac stable version

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#11753]
### Description

<img width="522" alt="Screenshot 2022-11-30 at 17 12 02" src="https://user-images.githubusercontent.com/16309962/204754965-7a1add1b-0d0e-4be0-a680-4d95716ff4ad.png">

mac info:
mac book pro m1

vs info:
```
Visual Studio Community 2022 for Mac
Version 17.4 (build 2406)
Installation UUID: 72492a3b-74b2-4ad0-a6a7-b78ee273f990

Runtime
.NET 6.0.9 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-3.22461.4+8ab250290a4010c11a21521f78dbc87dbb7aac81

NuGet
Version: 6.3.1.1

.NET SDK (Arm64)
SDK: Not installed

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.10
	6.0.9
	6.0.4
	6.0.1
	5.0.16 (x64 – Unsupported)
	5.0.13 (x64 – Unsupported)
	3.1.28 (x64 – Unsupported)
	3.1.25 (x64 – Unsupported)
	3.1.24 (x64 – Unsupported)
	3.1.22 (x64 – Unsupported)

Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found

Updater
Version: 11

Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:47:17 UTC

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:47:26 UTC

Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2022-11-02 23:47:26 UTC

Build Information
Release ID: 1704002406
Git revision: dfb45c1152306f0d5f77334f9d026b0aadb7ec90
Build date: 2022-11-02 23:44:22+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 13.0.1
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:14:30 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64


```

### Steps to Reproduce

not need

### Link to public reproduction project repository

just new a maui project using vs for mac

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS16

### Did you find any workaround?

no 

### Relevant log output

```shell
not need? maybe.
```

**Comment by coen22** [comment]
You should open Xcode to check if everything is installed. After you've opened it, the simulators should propagate again. Also, check that the Xcode path is set correctly. Otherwise, you should file a bug report in VS mac.

Hope it helps!

**Comment by EdwardMcFlurry** [comment]
Sometimes those Simulators show but most of the times they disappear and restarting VS for Mac doesn't work!

**Comment by drasticactions** [comment]
> Sometimes those Simulators show but most of the times they disappear and restarting VS for Mac doesn't work!

You need to be on the correct version of Xcode, or else it won't list them.

Let's say the version of Xamarin.iOS you have installed is intended for Xcode 14.0. You upgrade to Xcode 14.1. If the version of Xamarin.iOS you have doesn't support it, it (should) show a message in the IDE telling you that the version you have is not correct and you either need to downgrade to a supported Xcode, or update Xamarin.iOS (Most likely through the Visual studio for Mac updater, or Xamarin Mac Agent if you're on Windows)

That's most likely the problem here.
