### ISSUE TITLE
iOS Thickness should be multiple to 2

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/maui#11769]
### Description

I discovered that, for example, to change the SafeArea in iOS, the values must be multiplied by 2. This is probably because of the retina.

But in large iPads there is a factor of 3x. 

Maybe we should add some property that will depend on the system and we can multiply by it without worrying about compatibility?

https://developer.apple.com/documentation/uikit/uiscreen/1617836-scale

swift:
```swift
UIScreen.main.scale
```

cs:
``` cs
UIKit.UIScreen.MainScreen.Scale
```

### Steps to Reproduce

``` cs
var scene = UIKit.UIApplication.SharedApplication.ConnectedScenes.ToArray<UIKit.UIWindowScene>().FirstOrDefault();
if (scene != null)
{
    var windowScene = (UIKit.UIWindowScene)scene;
    var safeArea = windowScene.Windows.FirstOrDefault()?.SafeAreaInsets;
    Padding =  new Thickness(
        -(safeArea.Value.Left * 2), //left
        Padding.Top, //safeArea.Value.Top, //-(safeArea.Value.Top * 2),// top, 
        -(safeArea.Value.Right * 2), //right
        -(safeArea.Value.Bottom * 2)); //bottom
}
```

### Link to public reproduction project repository

no

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by hartez** [comment]
@KSemenenko Are you seeing an incorrect or unexpected behavior that this is meant to correct?

**Comment by KSemenenko** [comment]
so maybe we can have some property like
```cs
Paddin.Top = safeArea.Value.Top * On<iOS>().ScaleFactor;
```

or
```cs
Paddin.Top =  On<iOS>().ScaleValue(safeArea.Value.Top);
```

what do you think @hartez?

**Comment by KSemenenko** [comment]
so, I have to use this code

``` cs
        var scene = UIKit.UIApplication.SharedApplication.ConnectedScenes.ToArray<UIKit.UIWindowScene>().FirstOrDefault();
        if (scene != null)
        {
            var windowScene = (UIKit.UIWindowScene)scene;
            var safeArea = windowScene.Windows.FirstOrDefault()?.SafeAreaInsets;
            Padding =  new Thickness(
                -(safeArea.Value.Left * UIKit.UIScreen.MainScreen.Scale), //left
                Padding.Top, //safeArea.Value.Top, //-(safeArea.Value.Top * 2),// top, 
                -(safeArea.Value.Right * UIKit.UIScreen.MainScreen.Scale), //right
                -(safeArea.Value.Bottom * UIKit.UIScreen.MainScreen.Scale)); //bottom
        }
```

**Comment by hartez** [comment]
> even in the maui code base there is such a thing.

Where?

**Comment by KSemenenko** [comment]
@hartez  my bad. sorry it was strokeThickness
``` cs
(float)frame.Width - (strokeThickness * 2)
```

also I found **DeviceDisplay.Current.MainDisplayInfo.Density** wich is scale.
but for me it's 3 with some reason.

**Comment by hartez** [comment]
> also I found **DeviceDisplay.Current.MainDisplayInfo.Density** wich is scale. but for me it's 3 with some reason.

Yes, if you are using a higher density display, the density will be higher: 
https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.devices.displayinfo.density?view=net-maui-7.0#remarks

But you really only need to know this if you are doing platform-specific work. For anything cross-platform, the density scaling is accounted for automatically.  If you set the Padding for a Grid to 10, that value will be multiplied by the screen density _for you_ by the layout engine; you don't need to worry about it. 

If you're doing some sort of layout work in platform-specific code (e.g., in UISceneDelegate), and you need to account for the density yourself, then use DisplayInfo.Density.
