### ISSUE TITLE
DisplayAlert not working on MacCatalyst and UWP

### ISSUE THREAD

**Issue by YiannisBourkelis** [dotnet/maui#11766]
### Description

DisplayAlert is working on iOS and Android but I am experiencing some issues on MacCatalyst an Windows.

On Windows, it does not work at all when compiling as UWP app. It raises an unhandled exception.

On MacCatalyst, if the message string is like the one on the attached case, it displays a line at the center of the screen and nothing else.

### Steps to Reproduce

Run the reproduction project on MacCatalyst and on Windows (UWP). The Alert will not display.

### Link to public reproduction project repository

https://github.com/YiannisBourkelis/maui_issues/tree/main/src/DiplayAlertIssue/DisplayAlertIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS

### Affected platform versions

Latest MacCatalyst (Ventura 13.0.1) and Windows 10 Pro 22H2

### Did you find any workaround?

No

**Comment by YiannisBourkelis** [comment]
@PureWeen yes, I had to start the app without debugging and attach the debugger when the exception is raised. This is what i have:

`Unhandled exception at 0x00007FF9E215FDF2 (KernelBase.dll) in DisplayAlertIssue.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x00000294655FF1D0, 0x0000000000000001).`

**Comment by drasticactions** [comment]
I think the root of the problem is how you're using DisplayAlert.

https://github.com/YiannisBourkelis/maui_issues/blob/main/src/DiplayAlertIssue/DisplayAlertIssue/App.xaml.cs#L12-L28

You're calling for it in OnStart. The Application has started, the window nor page has fully loaded yet. The alert can't be displayed because there's nowhere for it to go.

If you call it when the window is loaded, it seems to appear fine on both platforms. I'm not sure what the expected behavior should be here.

**Comment by YiannisBourkelis** [comment]
@drasticactions I tried other events too. Window.Creared and Window.Activated. The issue remains on both Windows and MacCatalyst.

I placed the DisplayAlert code on the button click now to ensure that the page is loaded. The issue remains on MacCatalyst. It displays a line instead of the alert.

**Comment by Mat3oo** [comment]
Hi,

I've also experienced `DisplayAlert` not rendering correctly on MacCatalyst (_as a note `DisplayPromptAsync` hasn't this issue_), while other tested platforms (Windows, Android, iOS, iPad) worked fine.
What I was able to find out is that, when displaying message which lines exceed 17, then alert modal is rendered as thin line on the screen.
Here is example code (I'm not sure if on all screen it will give 17 new lines, so if not it for loop could be adjusted):

```csharp
StringBuilder messageBuilder = new StringBuilder(string.Empty);
for (int i = 0; i < 341; i++)
{
	messageBuilder.Append('W');
}
string message = messageBuilder.ToString();
await Application.Current.MainPage.DisplayAlert("Title", message, "Ok");
```
 341 counts of 'W' equals to 18 lines, which will result in failed display. Under 340 'W's result in proper displaying.

**Comment by pvoelker** [comment]
Ideally it would be great to eliminate the limit.  However I wonder if this is a limitation on the MacOS side.  If so, a meaningful exception would be good making the character limit clear...

**Comment by pvoelker** [comment]
> Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0(.NET8). Not repro on macOS and windows platform with sample project. https://github.com/YiannisBourkelis/maui_issues/tree/main/src/DiplayAlertIssue/DisplayAlertIssue

So one of the issue identified with DisplayAlert is the length of the string.  Strings that are over 340 on MacCatalyst (macOS) causes the crash.  It looks like the 340 limit is not being exercised (https://github.com/YiannisBourkelis/maui_issues/blob/5e63991b78fdc8ed4bcbec9fcff65f65a7cd0c19/src/DiplayAlertIssue/DisplayAlertIssue/MainPage.xaml.cs#L31).

My hunch is this is a limit on the macOS side.  If this is the case, a dedicated exception to help the user understand this is a hard limitation on DisplayAlert would be very helpful.  Versus a 'general' exception...
