### ISSUE TITLE
EvaluateJavaScriptAsync null reference if undefined returned on Android

### ISSUE THREAD

**Issue by anton-nikitsiuk** [dotnet/maui#11770]
### Description

An easy call for an undefined object or undefined itself triggers a NullReference error, and only on Android platform (at least Pixel 5 API 33 Emulator )
`await WebView.EvaluateJavaScriptAsync("undefined")`
or
`await WebView.EvaluateJavaScriptAsync("localStorage.realUndefinedObject")`

### Steps to Reproduce

1. Create a Page with a WebView, 
2. Make a call in any event, in my case it's on navigated
    ```c#
    WebView.Navigated += async (sender, e) =>
		{
			await WebView.EvaluateJavaScriptAsync("undefined")
		};
    ```
Actual result: NullReference exception is throw
Expected result: null object is returned

### Link to public reproduction project repository

I have no public repo for this issue

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13/ Pixel 5 in Emulator

### Did you find any workaround?

There is a workaround like 
`await WebView.EvaluateJavaScriptAsync("localStorage.realUndefiedObject ?? ''")`

### Relevant log output

```shell
Pretty cool log
Thread started: <Thread Pool> #2
Thread started: .NET ThreadPool Gate #3
Thread started: <Thread Pool> #4
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'
```

**Comment by drasticactions** [comment]
I just ran this in the current MAUI Main (net7.0) and it returned null for me

<img width="516" alt="image" src="https://user-images.githubusercontent.com/898335/204970341-0c4cde19-2cc9-456a-b420-6b62f0cbdfe4.png">

**Comment by drasticactions** [comment]
Same with Navigating

<img width="645" alt="image" src="https://user-images.githubusercontent.com/898335/204970823-c01bdd37-e36c-4a4c-aa8a-6130b6062096.png">

**Comment by anton-nikitsiuk** [comment]
Thank you, I will switch to .net 7, it looks more stable though
