### ISSUE TITLE
Failed to check update for Microsoft.Maui.Templates::6.0.100-preview.4.634: the package is not available in configured NuGet feeds.

### ISSUE THREAD

**Issue by Durelam** [dotnet/maui#1180]
I made a Maui check. preview 4 net6 costs. Installed components successfully. The latest version is worth a preview of the visual studio. As soon as I create the maui project, the error immediately gives:
"
C:\Users\dx_11>dotnet new maui
The template ".NET MAUI App" was created successfully.
Warning: Microsoft.Maui.Templates is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
Failed to check update for Microsoft.Maui.Templates::6.0.100-preview.4.634: the package is not available in configured NuGet feeds.
"

What was I doing wrong?

**Comment by TFreudi1** [comment]
What was it ? I got the same thing. I can create a project with VS2019 Preview, but also can't get this to work.
