### ISSUE TITLE
repro for Slider issues on Windows and macOS #9812

### ISSUE THREAD

**Issue by linkaiyu** [dotnet/maui#11802]
### Description

this issue is for the previous issue (Slider issues on Windows and macOS #9812) that was closed due to lack of repro from customer. Working with customer, I have created the repro. Please refer to the problem description to the original issue:
https://github.com/dotnet/maui/issues/9812

### Steps to Reproduce

please refer to the original issue for steps to reproduce
https://github.com/dotnet/maui/issues/9812

### Link to public reproduction project repository

https://github.com/linkaiyu/MauiSliderNotWorkingCorrectlyOnMac

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

maccatalyst 14

### Did you find any workaround?

no

**Comment by linkaiyu** [comment]
@WisJamison; @faustmet , can you verify if the above update fix the issue?

**Comment by WisJamison** [comment]
Hi @linkaiyu & @faustmet , after tested in my local,  the issues have been fixed with latest sdk/workload. Thanks a lot.
