### ISSUE TITLE
[Scenario Days 02 Dec] Local images not loading

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#11827]
### Description

Local images not loading. 
![image](https://user-images.githubusercontent.com/6755973/205296732-98ffb572-287f-4a7b-8777-2b75b38b90fa.png)

(Works on other platforms like Android)

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/scenariodays-120222/tree/main/src/ScenarioDays.Sample3
2. Launch the App on macOS.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/scenariodays-120222/tree/main/src/ScenarioDays.Sample3

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Ventura

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with 17.6 Preview (17.6 build 1539). Not repro on macOS with sample project. But the pictures show incomplete.
[scenariodays.zip](https://github.com/dotnet/maui/files/11632915/scenariodays.zip)
![11827](https://github.com/dotnet/maui/assets/77434865/03b8a421-e184-453c-aa6f-b2b7c3bd6e93)
