### ISSUE TITLE
Domain Architecture  causing build to fail  Windows is fine Andriod fails

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/maui#11825]
### Description

In the following situation where I have my models stored in Domain that has the following tooling installed which is shared betweeen my api and the blazor maui app.

    <Project Sdk="Microsoft.NET.Sdk">
    
      <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      </PropertyGroup>
    
      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="7.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational.Design" Version="2.0.0-preview1-final" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.0">
        <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
       </ItemGroup>   
    </Project>

If I add this project which is called  sentinelapi.Domain to the maui app it causing my builds to fail with the below error messages?

![image](https://user-images.githubusercontent.com/5619229/205287049-d21251b7-8add-4cc9-a5ae-58b544c03951.png)

I am also using mud blazor 

    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                });
            
            builder.Services.AddHttpClient();
            builder.Services.AddMudServices();
            builder.Services.AddScoped<HttpClient>();
            builder.Services.AddMauiBlazorWebView();

#if DEBUG
		builder.Services.AddBlazorWebViewDeveloperTools();
		builder.Logging.AddDebug();
#endif

            builder.Services.AddSingleton<WeatherForecastService>();

            return builder.Build();
        }
    }

### Steps to Reproduce

1 Create new app 
2 Add Shared Class Libary
2 Create some models
3 Create identity based models
5 Installed the required nugets for identity data annotations
4 Add Reference to the above libary
5 Windows Deploys fine
6 Andriod has issues and displays the error mentioed

### Link to public reproduction project repository

https://github.com/dotnetappdevni/sentinel.Web

### Version with bug

7.0 (current)

### Last version that worked well

7.0 Release Candidate 2

### Affected platforms

Android

### Affected platform versions

Andriod 12

### Did you find any workaround?

NO

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'android-x64'.	sentinel.APP	C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	448	

Even though this is installed as a file new app works?
```

**Comment by davidbuckleyni** [comment]
@PureWeen  any ideas here? Packs are installed

**Comment by davidbuckleyni** [comment]
@jsuarezruiz  any ideas here?

**Comment by jsuarezruiz** [comment]
Could you try removing https://github.com/dotnetappdevni/sentinel.Web/blob/1-0-1-beta/sentinel.APP/sentinel.APP.csproj#L32?

**Comment by Eilon** [comment]
Hi, the ASP.NET runtime is not supported on iOS, MacCatalyst, or Android. It is supported on Windows.

I suggest refactoring the application to have an architecture where common code that is not platform-specific is in one project, and then that project is referenced from an ASP.NET Core project and a .NET MAUI project. That means that the ASP.NET Core Identity UI project _cannot_ be referenced from the common code, but can be referenced from the ASP.NET Core project.
