### ISSUE TITLE
BlazorWebView error when doing XAML Hot Reload

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#11835]
### Description

XAML Hot Reload works on other pages, but not this one. App runs and behaves fine.

<img width="970" alt="Screenshot 2022-12-02 at 1 38 04 PM" src="https://user-images.githubusercontent.com/41873/205373366-75ab27f3-6e6f-4d02-acb3-7f8562959ff5.png">

```
/Users/dmo/work/maui-samples/7.0/Apps/PointOfSale/src/PointOfSale/Pages/Handheld/SignaturePage.xaml(48,48): Error: The name "Main" does not exist in the namespace "clr-namespace:PointOfSale".
```

I have a few other XLS errors now as well. Those also work fine despite the errors.

<img width="857" alt="Screenshot 2022-12-02 at 1 44 50 PM" src="https://user-images.githubusercontent.com/41873/205373891-3df099c3-1451-43cd-8f13-befdbf894c0c.png">

### Steps to Reproduce

Try to hot reload on the page linked to in maui-samples

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/blob/main/6.0/Apps/PointOfSale/src/PointOfSale/Pages/Handheld/SignaturePage.xaml#L25

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

16.1

**Comment by Eilon** [comment]
Marking tooling because it's unlikely Blazor plays any role here, given that the error seems to be related to the contents of the XAML, as opposed to any logic of the BlazorWebView control.
