### ISSUE TITLE
Android "No compatible code running on the thread" and crash after hit continue

### ISSUE THREAD

**Issue by eddylawsurgere** [dotnet/maui#11837]
Hi All,

I have a .Net MAUI project and installed a NuGet package called OctaneSDK. If I called any function of the package for Android and it throw exception, debugger went to Break Mode "No compatible code running on the thread". It crashed after I clicked Continue. The try-catch didn't catch the exception.
![Maui Adroid Break Mode](https://user-images.githubusercontent.com/75318786/205388202-18877a38-758b-4d85-b65f-a20432e387dc.png)
I attached the screenshot. But there is no issue to run in Windows platform.

Platform: Android
NuGet Package: OctaneSDK (4.1.0)
Code:
![Code](https://user-images.githubusercontent.com/75318786/205388911-f73d5268-b7c2-4933-8735-0a48fa43e42a.png)

  using Impinj.OctaneSdk;

        try
        {
            ImpinjReader reader = new ImpinjReader();
            reader.Connect("nohost");  // nohost not exist IP to cause the Connect() throw timeout exception
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());  // the reader.Connect timeout exception not caught here. Crash if press Continue in break mode.
        }

Thank you.

**Comment by jsuarezruiz** [comment]
If you try the same code with a console app (for example) get something similar?, is the Connect method async?

**Comment by eddylawsurgere** [comment]
Hi Javier,

I did the same code in a console app for windows platform. The try-catch got the connection timeout exception. The Connect method is not async.

Eddy Law
Sr Software Developer
***@***.***<http://www.surgere.com/>
833.221.1165  |  surgere.com<http://www.surgere.com/>  |  ***@***.*** <https://www.linkedin.com/company/surgere>  ***@***.*** <https://twitter.com/SurgereIoT>  ***@***.*** <https://www.facebook.com/SurgereIoT/>  ***@***.*** <https://www.instagram.com/surgereiot/>

**Comment by PureWeen** [comment]
@eddylawsurgere can you open an issue on the OctaneSDK repo?

**Comment by eddylawsurgere** [comment]
I reported the issue to Impinj support for OctaneSDK.

Eddy Law
Sr Software Developer
***@***.***<http://www.surgere.com/>
833.221.1165  |  surgere.com<http://www.surgere.com/>  |  ***@***.*** <https://www.linkedin.com/company/surgere>  ***@***.*** <https://twitter.com/SurgereIoT>  ***@***.*** <https://www.facebook.com/SurgereIoT/>  ***@***.*** <https://www.instagram.com/surgereiot/>

**Comment by jenscski** [comment]
Hello. We are also using this SDK, for now in Xamarin, but will transition over to MAUI, so I wanted to test this, and I got the crash, not the exact same error you did, but a unhandled exception.

I'm testing using Sentry, so I got a stack trace for the unhandled exception there.

```
OS Version: Android 11 (RP1A.200720.012.A405FNXXS4CVH1)
Report Version: 104

Exception Type: Unknown (SIGABRT)

Application Specific Information:
Abort

Thread 0 Crashed:
0   libc.so                         0x733658bcd0        abort
1   libmonodroid.so                 0x729fd4d338        <unknown> + 492307796792
2   libmonosgen-2.0.so              0x7299123534        <unknown> + 492194379060
3   libmonosgen-2.0.so              0x7299123660        <unknown> + 492194379360
4   libmonosgen-2.0.so              0x7298f631e0        <unknown> + 492192543200
5   libmonosgen-2.0.so              0x72990ab77c        <unknown> + 492193888124
6   libmonosgen-2.0.so              0x72990aa410        <unknown> + 492193883152
7   libmonosgen-2.0.so              0x72990f636c        <unknown> + 492194194284
8   libmonosgen-2.0.so              0x72990f44f4        <unknown> + 492194186484
9   libmonosgen-2.0.so              0x72990eb5dc        <unknown> + 492194149852
10  libmonosgen-2.0.so              0x7299024c30        <unknown> + 492193336368
11  libmonosgen-2.0.so              0x7298f5cbf8        mono_runtime_invoke_checked
12  libmonosgen-2.0.so              0x7298f75304        <unknown> + 492192617220
13  libmonosgen-2.0.so              0x7298f750f8        <unknown> + 492192616696
14  libc.so                         0x73365ed7a4        __pthread_start
15  libc.so                         0x733658dc88        __start_thread
```

In the debug output I also noticed

``[nyname.mauiapp] * Assertion at /__w/1/s/src/mono/mono/metadata/object.c:4176, condition `is_ok (error)' not met, function:mono_unhandled_exception_internal, (null) assembly:/data/data/com.companyname.mauiapp1/files/.__override__/System.Private.CoreLib.dll type:ThreadInterruptedException member:(null)``

And
``[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4783 (Thread-18), pid 3048 (nyname.mauiapp1)``

**Comment by jenscski** [comment]
I started a further investigation (decompiling OctaneSDK), and found out that Monitor.Wait, on Android (mono?) does not comply to the description in https://learn.microsoft.com/en-us/dotnet/api/system.threading.monitor.wait

If the thread is interrupted, then Wait should throw ThreadInterruptedException, which is handled in the OctaneSDK, instead it returns false, throwing an unhandled exception in a thread, by the SDK, resulting in a exception that is impossible to catch, and resulting in an application crash.

I'm guessing the Monitor.Wait is compliant in a console application, and no errors is thrown.

So this should probably be reported in a mono repository or something?

@PureWeen | @jsuarezruiz

**Comment by eddylawsurgere** [comment]
Thanks Jens.
I tried to use Xamarin to run the same code with OctaneSDK for Android. It worked and the try-catch got the Timeout exception.
Eddy Law
Sr Software Developer
***@***.***<http://www.surgere.com/>
833.221.1165  |  surgere.com<http://www.surgere.com/>  |  ***@***.*** <https://www.linkedin.com/company/surgere>  ***@***.*** <https://twitter.com/SurgereIoT>  ***@***.*** <https://www.facebook.com/SurgereIoT/>  ***@***.*** <https://www.instagram.com/surgereiot/>

**Comment by eddylawsurgere** [comment]
> I started a further investigation (decompiling OctaneSDK), and found out that Monitor.Wait, on Android (mono?) does not comply to the description in https://learn.microsoft.com/en-us/dotnet/api/system.threading.monitor.wait
> 
> If the thread is interrupted, then Wait should throw ThreadInterruptedException, which is handled in the OctaneSDK, instead it returns false, throwing an unhandled exception in a thread, by the SDK, resulting in a exception that is impossible to catch, and resulting in an application crash.
> 
> I'm guessing the Monitor.Wait is compliant in a console application, and no errors is thrown.
> 
> So this should probably be reported in a mono repository or something?
> 
> @PureWeen | @jsuarezruiz

**Comment by eddylawsurgere** [comment]
> Hello. We are also using this SDK, for now in Xamarin, but will transition over to MAUI, so I wanted to test this, and I got the crash, not the exact same error you did, but a unhandled exception.
> 
> I'm testing using Sentry, so I got a stack trace for the unhandled exception there.
> 
> ```
> OS Version: Android 11 (RP1A.200720.012.A405FNXXS4CVH1)
> Report Version: 104
> 
> Exception Type: Unknown (SIGABRT)
> 
> Application Specific Information:
> Abort
> 
> Thread 0 Crashed:
> 0   libc.so                         0x733658bcd0        abort
> 1   libmonodroid.so                 0x729fd4d338        <unknown> + 492307796792
> 2   libmonosgen-2.0.so              0x7299123534        <unknown> + 492194379060
> 3   libmonosgen-2.0.so              0x7299123660        <unknown> + 492194379360
> 4   libmonosgen-2.0.so              0x7298f631e0        <unknown> + 492192543200
> 5   libmonosgen-2.0.so              0x72990ab77c        <unknown> + 492193888124
> 6   libmonosgen-2.0.so              0x72990aa410        <unknown> + 492193883152
> 7   libmonosgen-2.0.so              0x72990f636c        <unknown> + 492194194284
> 8   libmonosgen-2.0.so              0x72990f44f4        <unknown> + 492194186484
> 9   libmonosgen-2.0.so              0x72990eb5dc        <unknown> + 492194149852
> 10  libmonosgen-2.0.so              0x7299024c30        <unknown> + 492193336368
> 11  libmonosgen-2.0.so              0x7298f5cbf8        mono_runtime_invoke_checked
> 12  libmonosgen-2.0.so              0x7298f75304        <unknown> + 492192617220
> 13  libmonosgen-2.0.so              0x7298f750f8        <unknown> + 492192616696
> 14  libc.so                         0x73365ed7a4        __pthread_start
> 15  libc.so                         0x733658dc88        __start_thread
> ```
> 
> In the debug output I also noticed
> 
> `` [nyname.mauiapp] * Assertion at /__w/1/s/src/mono/mono/metadata/object.c:4176, condition `is_ok (error)' not met, function:mono_unhandled_exception_internal, (null) assembly:/data/data/com.companyname.mauiapp1/files/.__override__/System.Private.CoreLib.dll type:ThreadInterruptedException member:(null) ``
> 
> And `[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4783 (Thread-18), pid 3048 (nyname.mauiapp1)`

@jenscski I switched to use Xamarin. The OctaneSDK Connect method worked for Android but I got connect Timeout exception for Window (UWP). Did you try OctaneSDK for Window (UWP)?
Thanks

**Comment by jenscski** [comment]
No, not tested for UWP, but I do use it for other windows targets, mainly background services, without problem

**Comment by jenscski** [comment]
@eddylawsurgere have you sent the error report I created in the dotnet runtime repository to Impinj?
To let them know about the limitation in .NET on Android?

Maybe they can create a workaround for it ...
