### ISSUE TITLE
Can't access Maui's xaml schema

### ISSUE THREAD

**Issue by zooeywm** [dotnet/maui#11841]
When I'm accessing <https://schemas.microsoft.com/dotnet/2021/maui>, I got a response that shows "the resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

**Comment by Eilon** [comment]
I believe those schemas are URIs, but not URLs. A URI is anything that has the pattern `[scheme] :// [host] / [path]` and is used to _identify_ a resource (hence the "I" in URI, Uniform Resource Identifier). On the other hand, a URL is a URI that points to how to actually locate a resource to get it (hance the "L" in URL, Uniform Resource Locator).

So, I wouldn't expect that URI to be a valid URL (sometimes they are, but with schemas I've found that's rarely the case).

If the question is where _could_ you find the schema for .NET MAUI XAML, then hopefully another person here can help with that.

**Comment by zooeywm** [comment]
> I believe those schemas are URIs, but not URLs. A URI is anything that has the pattern `[scheme] :// [host] / [path]` and is used to _identify_ a resource (hence the "I" in URI, Uniform Resource Identifier). On the other hand, a URL is a URI that points to how to actually locate a resource to get it (hence the "L" in URL, Uniform Resource Locator).
> 
> So, I wouldn't expect that URI to be a valid URL (sometimes they are, but with schemas I've found that's rarely the case).
> 
> If the question is where _could_ you find the schema for .NET MAUI XAML, then hopefully another person here can help with that.

Thanks for your reply! I made a mistake in distinguishing URI and URL. Indeed, I want to get the schema for .NET MAUI XAML, I wonder is there a way to use a thing like "XML Schema" to xml/xaml file like JSONSchema to json file? Because I want to develop MAUI in vscode but I found that vscode can't make MAUI XAML's intellisense.

**Comment by Eilon** [comment]
I couldn't find any location for XAML schema but maybe someone else here knows. It's possible that there is no XSD available for it.

**Comment by mattleibow** [comment]
@StephaneDelcroix do we have this schema anywhere?

**Comment by StephaneDelcroix** [comment]
no, we don't. such a thing do not exists. One could generate a XSD based on the assemblies, if you plan to run some XML tools on the XAML files
