### ISSUE TITLE
ScrollView doesn't resize when child scaled

### ISSUE THREAD

**Issue by ShadowOfPhantom** [dotnet/maui#11850]
### Description

I have a StackLayout inside ScrollView. When I scale this StackLayout, ScrollView doesn't expand accordingly.

I attached a video sample and appropriate part of xaml

https://user-images.githubusercontent.com/41395390/205459056-1f9e9511-5d83-4877-9822-7621377a9bbe.MP4

```
<ScrollView
            Orientation="Both">
                <StackLayout
                    Scale="{Binding Scale}"
                    VerticalOptions="CenterAndExpand"
                    HorizontalOptions="CenterAndExpand"
                    x:Name="RootLayout"
                    Spacing="1.5">
                <Border
                VerticalOptions="Start"
                HorizontalOptions="FillAndExpand"
                StrokeShape="RoundRectangle 20,20,7,7"
                Style="{StaticResource TransparentFrame}">
                        <Border.Stroke>
                            <Color>
                                Transparent
                            </Color>
                        </Border.Stroke>
                        <StackLayout
                                 Padding="10"
                                 Spacing="0"
                                 VerticalOptions="FillAndExpand"
                                 HorizontalOptions="FillAndExpand">
                            <Label Text=""/>
                            <Label Text="{Binding GameInfo.FirstPlayerLabel}"/>
                            <Label Text="{Binding GameInfo.SecondPlayerLabel}"/>
                        </StackLayout>
                    </Border>
                </StackLayout>
        </ScrollView>
```

### Steps to Reproduce

1) Place a StackLayout inside ScrollView
2) Change scale of StackLayout

### Link to public reproduction project repository

-

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

iOS, macOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16, macOS Ventura 13.0.1 (22A400)

### Did you find any workaround?

I broke my brain but didn't find a workaround :(

**Comment by rmarinho** [comment]
@hartez  do you have any ideas about this? Should the bounds change when we scale? i don't think so.
