### ISSUE TITLE
Resources defined in the App.xaml was not referred for Background Property while deploying in the release mode.

### ISSUE THREAD

**Issue by VijayakumarViswanathan** [dotnet/maui#11857]
### Description

SolidColorBrush resource was defined in the App.XAML page and used in the project for the Background property (Brush type) of framework controls like  Label, Button, StackLayout, etc. When deploying in the **release mode** SolidColorBrush resource was not referred to and not displaying the defined resources. but on debug mode, it was referred to and works properly.

| Debug Mode | Release Mode |
| :-: | :-: |
| ![Debug mode](https://user-images.githubusercontent.com/97146530/205590525-73dac689-9fb4-46fa-9257-92dde16fb70d.png) | ![Release mode](https://user-images.githubusercontent.com/97146530/205590764-f5ed272a-db6b-402e-b12f-e28d7373af89.png) |

### Steps to Reproduce

1. Run the attached sample in debug mode. Background property works properly.
2.  Then, Run the attached sample in release mode. The background property does not work properly. (Issue)

### Link to public reproduction project repository

https://github.com/VijayakumarViswanathan/ReleaseModeAppResourcesNotReferred

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 9, windows10.0.19041.0

### Did you find any workaround?

No

**Comment by mattleibow** [comment]
I think I found the issue... SolidColorBrush is not actually initialized using the color:

![image](https://user-images.githubusercontent.com/1096616/206016395-9e6e403c-4e5e-4023-8a96-31b2ea6ad456.png)

**Comment by mattleibow** [comment]
Removing the android labels as this happens in Windows and is related to the output of XamlC - potentially the converters since the XamlC code is "valid" not "correct".

**Comment by mattleibow** [comment]
I tried turning off XamlC for the App.xaml using the directive, but it does nothing:

```xml
<?xaml-comp compile="false" ?>
```

**Comment by kocevilija** [comment]
> Investigating this and I found some "things".
> 
> I can reproduce the issue in Debug when I set XamlC to always run:
> 
> ```
> <_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>
> ```
> 
> I then also tried plain debug again, but copied the contents from the generated xaml into App.cs and I got the same. The C# was valid and looks right, but it can't read the resources when created in C#. Not sure XamlC is the issue but rather the code-based dictionary.
> 
> In all cases, the items from the separate files are fine, just the in-line ones are broken - the button is purple from the Styles.xaml.

@mattleibow Where did you se this tag?

**Comment by DamianSuess** [comment]
@kocevilija, I set it in my Maui `.csproj` file. However, this ended up breaking Hot Reload, and had to stop using it.

**Comment by vhugogarcia** [comment]
> I think I found the issue... SolidColorBrush is not actually initialized using the color:
> 
> ![image](https://user-images.githubusercontent.com/1096616/206016395-9e6e403c-4e5e-4023-8a96-31b2ea6ad456.png)

I'm facing the same issue where the styles such as font family, font size, borders with round corners, etc are not being applied to my elements such as Entry and Labels. I'm using .NET MAUI 7.0.59/7.0.100, I cannot release the app to the stores because when setting LinkFrameworksSDKs only, the styles are missing.

Do you know if there is a workaround to solve this issue? 

Maybe you @DamianSuess, have you able to fix the issue?

Thanks in advance

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on android and windows platform with above project.
[ReleaseModeApp.zip](https://github.com/dotnet/maui/files/11658967/ReleaseModeApp.zip)
Android:
![Screenshot 2023-06-05 143340](https://github.com/dotnet/maui/assets/77434865/12a96603-e266-4511-885a-1115b8fa2dc4)
Windows:
![11857 Release W](https://github.com/dotnet/maui/assets/77434865/1377725a-ca8f-4ce8-9d3a-6e942aeed0c2)

**Comment by StephaneDelcroix** [comment]
working on this. A workaround would be

```xaml
        <SolidColorBrush x:Key="notpink">
            <SolidColorBrush.Color>HotPink</SolidColorBrush.Color>
        </SolidColorBrush>
```
