### ISSUE TITLE
Adding mappings to ViewHandler.Mapper only works if you run it before calling MauiApp.CreateBuilder()

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#11853]
### Description

The change [here](https://github.com/dotnet/maui/pull/4995/files#diff-a13ce6b34969e6decdc4f6547e8bc4e457593651756af3a320be9efa69cc086eR294) sets the ViewHandler.Mapper to a property mapper with generics `<ILayout, LayoutHandler>`. This makes it so the only way you can add a mapper for all view types is to set the mapper before calling `MauiApp.CreateBuilder`.   If you try to add a mapper property at the `ViewHandler.Mapper` level inside the `App` ctor or `ConfigureHandlers` it will only execute if the view implements `ILayout` and the handlers implements `LayoutHandler`

### Reproduction

You can see this issue pretty easily with the following code

```C#
public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		MainPage = new AppShell();

		ViewHandler.ViewMapper.Add("SomeMapping", (handler, View) =>
		{
			if (View is IButton)
			{
				// This never runs
			}
		});
	}
}
```

The only way to add a mapper function that will run for every view is to add a mapper before calling `MauiApp.CreateBuilder`

### Proposal

1) The ControlsLayoutMapper should just be `<IView, IViewHandler>` and the mapper methods should just cast to layout themselves. If the incoming type is the expected types then it executes the necessary logic.
2) Maybe there's a way to make property mapper more permissive? It could check the types on the action or it could just try to call the action and if it gets an InvalidCastException move on
   - This is probably not a good idea. Just wanted to offer an alternative :-)

**Comment by Eilon** [comment]
Is `ViewHandler.ViewMapper.Add()` a thread-safe call? If not, then it's quite limited where you can safely call this method to begin with. If the app is already running and it isn't thread safe, the app can exhibit undefined behavior.

**Comment by PureWeen** [comment]
@Eilon agreed, but you should be able to call it from the `App.xaml.cs` ctor or `ConfigureHandlers` which both happen before the app is really considered `Running` 

If we want to lock down where these can be modified, then we should make the mappers read-only after a certain life cycle point the way `Services` are. 

Typically, any mapper modifications will all just happen one place inside the startup cycle before the app is really running.

**Comment by Eilon** [comment]
I just didn't want someone to see this and then start calling it on button clicks or something 😄 

I don't think we necessarily have to block things off, at least not without strong feedback people are doing it wrong. Certainly there has to be some internal cut-off after which we don't _expect_ it to work, even if it's not blocked. I just wasn't sure how late is too late.
