### ISSUE TITLE
MAUI App UI Elements disappear on iOS when Instabug is initialized

### ISSUE THREAD

**Issue by DavidMina96** [dotnet/maui#11854]
### Description

Hi team, 

This is David, a Cross-Platform Mobile Engineer at Instabug. 

We're considering adding .NET MAUI support to our SDK but are encountering an issue that's a blocker. Whenever Instabug SDK is initialized, all UI elements (e.g. icon, button) of the app disappear except for the top navigation bar. This was observed only on iOS and works well on Android. Screen recordings from both platforms are attached below:

https://user-images.githubusercontent.com/36373152/205485677-5f3babd6-6c85-4755-9736-979e7bae9d38.mp4

https://user-images.githubusercontent.com/36373152/205485684-28437540-6a69-4e45-b8d2-456064bfa282.MOV

A few points that may help narrow down the root cause:
1. This behaviour happens regardless of the invocation event(s) used to initialize Instabug (e.g. `FloatingButton`, `Shake` or even `None`). 
2. It's not related to where the SDK gets initialized in the app lifecycle; if it's done after `InitializeComponent` is called in `App.xaml.cs` or inside AppDelegate's `FinishedLaunching` method, the app starts without the UI elements right from the beginning. If the initialization code is moved to be executed on a button click, the UI elements first appear normally, and once the button is clicked, they disappear (like the screen recording shared earlier). 

Kindly check the following screenshots as well that illustrate the app view hierarchy before and after Instabug gets initialized:

<img width="1407" alt="before initialization" src="https://user-images.githubusercontent.com/36373152/205485817-18142316-91ca-475d-8cc7-16e8bf32d82f.png">
<img width="1411" alt="after initialization" src="https://user-images.githubusercontent.com/36373152/205485811-6c195d04-e8a6-4cb8-afbb-876998a13a65.png">

Another issue is that we're not able to run the app on the simulator; it crashes with the following error:
`error HE0042: Could not launch the app 'com.companyname.InstabugMAUIExample' on the device 'iOS 15.5 (19F70) - iPhone 13 Pro': Application launch for 'com.companyname.InstabugMAUIExample' did not return a valid pid nor a launch error.` 

It runs, however, on a physical device (with the UI issue of course). 

Your assistance is appreciated! 

### Steps to Reproduce

1. Clone the project from the public repo below
2. Build `Instabug.iOS.Binding` and `Instabug.MAUI` projects
3. Run `Instabug.MAUI.Example` project on iOS
4. Click "Click me" button

Expected outcome: Instabug floating button appears and the app UI elements stay. 
Actual outcome: Instabug floating button appears and the app UI elements disappear. 

### Link to public reproduction project repository

https://github.com/DavidMina96/IBG-Maui

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Tried on iOS 15 (could be the same on other versions too)

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@DavidMina96 if you update to net7.0 instead of net6.0 do you get the same thing?

**Comment by rmarinho** [comment]
Can you please open a new bug related with the simulator issue on [VS Feedback](https://developercommunity.visualstudio.com/VisualStudio/report)

Thanks

**Comment by DavidMina96** [comment]
@PureWeen Yes, the same issue persists even after updating to net7.0 unfortunately. SDK version as per `dotnet workload list` is 7.0.100. Any thoughts how we can move forward with investigating the issue?

**Comment by DavidMina96** [comment]
Any updates on this issue please? I'm not sure why it's closed even though it's occurring on net7.0 as well. Please let us know if we shall reach out to a different support channel - or even join a debug call - to expedite things.

**Comment by yousefhamza** [comment]
@PureWeen @rmarinho any updates here? it's blocking us
