### ISSUE TITLE
Label does not get wrapped when in Grid with ColumnSpan

### ISSUE THREAD

**Issue by SokoFromNZ** [dotnet/maui#11863]
### Description

When I put a Label in a Grid with a ColumnSpan the Label does not get wrapped as it usually does (the green text should be the same as the blue and the yellow):

![image](https://user-images.githubusercontent.com/33326277/205618103-3d75bfd7-83cb-4fce-acb3-348134909bd2.png)

### Steps to Reproduce

ContentPage with the following grid or use my repository example

```xaml

    <Grid ColumnDefinitions="*" RowDefinitions="Auto,Auto,Auto">
        <Label
            Grid.Row="0"
            Grid.Column="0"
            BackgroundColor="Blue"
            Text="This is a very long text which should be wrapped to the next line when the end of the Android screen is reached" />
        <Grid
            Grid.Row="1"
            Grid.Column="1"
            BackgroundColor="Green"
            ColumnDefinitions="*, Auto, *"
            RowDefinitions="Auto, Auto">
            <Label
                Grid.Row="0"
                Grid.Column="0"
                Grid.ColumnSpan="3"
                Text="This is a very long text which should be wrapped to the next line when the end of the Android screen is reached" />
            <Label
                Grid.Row="1"
                Grid.Column="0"
                HorizontalOptions="End"
                Text="No"
                VerticalOptions="Center" />
            <Switch Grid.Row="1" Grid.Column="1" />
            <Label
                Grid.Row="1"
                Grid.Column="2"
                HorizontalOptions="Start"
                Text="Yes"
                VerticalOptions="Center" />
        </Grid>
        <Label
            Grid.Row="2"
            Grid.Column="0"
            BackgroundColor="Yellow"
            Text="This is a very long text which should be wrapped to the next line when the end of the Android screen is reached" />
    </Grid>
```

### Link to public reproduction project repository

https://github.com/SokoFromNZ/MauiNoLabelWrappingInGrid

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11, 12, 13

### Did you find any workaround?

I have to put all Labels in a separate Grid

**Comment by BioTurboNick** [comment]
Another workaround: Wrap the label in a ContentView with a Margin set to force the extra layout pass.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on Android platform with sample project.
[MauiNoLabel.zip](https://github.com/dotnet/maui/files/11659200/MauiNoLabel.zip)
![Screenshot 2023-06-06 095906](https://github.com/dotnet/maui/assets/77434865/6ce3005e-4ca9-458d-9ff5-669720b37af5)

**Comment by SokoFromNZ** [comment]
Thanks @Zhanglirong-Winnie for your check with the latest preview. As I'm not allowed to install VS Previews on my machine I'll have to wait until 17.7.0 is official to confirm.
If I still have this issue then I will reopen it.
