### ISSUE TITLE
CollectionView cause Intent memory Leak

### ISSUE THREAD

**Issue by matteo-convert** [dotnet/maui#11866]
### Description

In MVVM when a page contains the CollectionView element the page and ViewModel destructors will never be called and therefore will create a memory stack, the application will then become slower and slower until it crashes.

This does not happen with the ListView but the listview does not allow to make a list containing SwipeView (another bug I guess)

### Steps to Reproduce

1. create two view one with collectionView and one with ListView
2. Navigate to page with CollectionView and MainPage many times (u can see with the destructor the page never destruct)
3. do same with ListView and the page destruct

### Link to public reproduction project repository
https://github.com/matteo-convert/CollectionViewMemoryLeak.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

all i think

### Did you find any workaround?

No, apart from using listViews but as I said it i can't use SwipeView inside it.

**Comment by 8m0** [comment]
Does memory leak when switching pages still exists as well?

**Comment by matteo-convert** [comment]
> Does memory leak when switching pages still exist as well?

I don't quite understand, what do you mean?

**Comment by 8m0** [comment]
> > Does memory leak when switching pages still exist as well?
> 
> I don't quite understand, what do you mean?

There is a bug which hasn't been fixed since Xamarin forms. Memory leak occurs when you switch pages, this happens to me in UWP app(Xamarin). I found bug report complaining about the same thing as well in MAUI. The problem was ignored since Xamarin up until MAUI, and i think it will take a loot of time they pay attention to it.

I would suggest to everyone not to use MAUI so far, don't know why they decided to release it. It seems like you need constantly look for backbones. You can click few random reports and see how they offer "workarounds" instead of normal solution.

I have been watching issues list (https://github.com/dotnet/maui/issues) growing since May. Bugs list increases fast but they release fixes to slow.

**Comment by angelru** [comment]
> > > Does memory leak when switching pages still exist as well?
> > 
> > 
> > I don't quite understand, what do you mean?
> 
> There is a bug which hasn't been fixed since Xamarin forms. Memory leak occurs when you switch pages, this happens to me in UWP app(Xamarin). I found bug report complaining about the same thing as well in MAUI. The problem was ignored since Xamarin up until MAUI, and i think it will take a loot of time they pay serious attention to it.
> 
> I would suggest to everyone not to use MAUI so far, don't know why they decided to release it. It seems like you need constantly look for backbones. You can click few random reports and see how they offer "workarounds" instead of normal solution. Let's imagine you have at least mid size project, after sometime it will be a giant mess with "workarounds" for each problem, which hard to remember as they are not simple(straightforward) sometimes => not possible to debug in case of new problems.
> 
> I have been watching issues list (https://github.com/dotnet/maui/issues) growing since May. Bugs list increases fast but they release fixes too slow.
> 
> Xamarin forms looks not ideal as well, there are a lot of problems as well and they abandoned fixing them, prioritizing MAUI development. But it seems more stable at least. So if your project is serious, i would recommend you to switch to Xamarin as i did. I had constant problems with MAUI, relied on Montemagno opinion as he was advertising as great and working technology. Yes it is pity that you need to switch to older version of .NET, but believe me, you will save a lot of your time.

The truth is that I am unhappy with MAUI. There are several very important controls like SwipeView and CollectionView, which present bugs and poor performance in the CollectionView Scroll.

Also Shell has some important bugs in the navigation animation when there is a page with a "complex layout". And we still don't have Badge on the tabs...

**Comment by 8m0** [comment]
> 

When MAUI was at preview state, there was a big list of problems already. If i remember correctly more than 1k. And when i saw they released it, i was stunned. Couldn't believe they fixed it fast. Then i just opened issues tab and saw the same bugs as it was, basically left without attention.

**Comment by trivalik** [comment]
Could it help releasing DataContext (DataBinding) like here https://github.com/xamarin/Xamarin.Forms/pull/14780/files ?

**Comment by matteo0158** [comment]
> Could it help releasing DataContext (DataBinding) like here https://github.com/xamarin/Xamarin.Forms/pull/14780/files ?

Nop

**Comment by nikolaykusch** [comment]
Same problem. I have only one question. How to work with MAUI with such bugs?

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 6.0. Not repro on Android platform with sample project.
https://github.com/matteo-convert/CollectionViewMemoryLeak.git
![image](https://github.com/dotnet/maui/assets/82450723/581fc6b7-7995-4107-9e4a-6b24650ea8b9)
