### ISSUE TITLE
ImageButton with CornerRadius is not calculated as expected on Android when Padding exists

### ISSUE THREAD

**Issue by YiannisBourkelis** [dotnet/maui#11874]
### Description

Trying to create a circular ImageButton, I am setting the CornerRadius half the width of the control, but on Android it does not appear as expected. If I remove the Padding it works, but it should also work with padding. 

On iOS, MacCatalyst and Windows it works fine, however the text inside the ImageButton is not aligned exactly at the center of the ImageButton and appears a little blurry.

<img width="911" alt="corner_radius_issue" src="https://user-images.githubusercontent.com/2575796/206004926-137f5b24-031d-448b-af5e-f14d47ea9c21.png">

This is the code that creates the ImageButton
```
            <ImageButton
                x:Name="AddItemImageButton"
                HorizontalOptions="End"
                VerticalOptions="End"
                CornerRadius="25"
                WidthRequest="50"
                HeightRequest="50"
                BackgroundColor="DodgerBlue"
                Padding="8,8,8,8" >                
                <ImageButton.Source>
                    <FontImageSource FontFamily="OpenSansRegular" Color="White"  Glyph="+" />
                </ImageButton.Source>                           
            </ImageButton>
```

Check the reproduction project.

### Steps to Reproduce

Just run the reproduction project targeting Android. The ImageButton will not appear as a circle.

### Link to public reproduction project repository

https://github.com/YiannisBourkelis/maui_issues/tree/main/src/CornerRadiusIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android Emulator - Pixel 5 - Api 33

### Did you find any workaround?

No.

**Comment by PureWeen** [comment]
@YiannisBourkelis can you attach a screen shot please?

**Comment by YiannisBourkelis** [comment]
@PureWeen Yes. It is the reproducible project running on android on the left and iOS on the right.

<img width="911" alt="corner_radius_issue" src="https://user-images.githubusercontent.com/2575796/206004682-77d66b97-7635-4ee7-9796-4cc477171ca2.png">

**Comment by MhAllan** [comment]
any updates on this basic thing? It was right on XF!!

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0 with provided project:
[CornerRadiusIssue.zip](https://github.com/dotnet/maui/files/11704929/CornerRadiusIssue.zip)

**iOS 16.4:** Can repro the text inside the ImageButton is not aligned exactly at the center of the ImageButton issue.
![image](https://github.com/dotnet/maui/assets/97647558/230eeb51-aa9b-40f7-8e36-f1d3dcb63767)

**Android 13.0-API33:** Can repro the CornerRadius issue.
![image](https://github.com/dotnet/maui/assets/97647558/fdd63eb8-dd0f-4521-a95d-d7570f124af2)

**Windows 11:** Seems work as expected.
![image](https://github.com/dotnet/maui/assets/97647558/61ccc84a-7416-46bb-aa83-d77e5324970b)

**Comment by thomaskaelin** [comment]
@jsuarezruiz I ran [the example](https://github.com/dotnet/maui/issues/11874#issuecomment-1584290586) posted by @XamlTest with my installation of **Visual Studio Professional 2022 (Version 17.6.2)** on an Android Device (Android 11 - API 30). I was able to reproduce the CornerRadius-issue without with the provided code.

<img width="487" alt="CornerRadius Issue" src="https://github.com/dotnet/maui/assets/20944426/4a2edbe4-28f4-4610-99d5-cf3f714553c9">

**Comment by davidortinau** [comment]
Looks correct in .NET 8 Preview 6. Not sure when this was fixed. Tested on API 33 and 32.

On older versions, you can work around this with math. On Android adjust the w/h by 16 to offset the padding of 8.

```
<ImageButton
    x:Name="AddItemImageButton"
    HorizontalOptions="End"
    VerticalOptions="End"
    CornerRadius="25"
    WidthRequest="{OnPlatform 50, Android=66}"
    HeightRequest="{OnPlatform 50, Android=66}"
    BackgroundColor="DodgerBlue"
    Padding="8,8,8,8" >                
    <ImageButton.Source>
        <FontImageSource FontFamily="OpenSansRegular" Color="White"  Glyph="+" />
    </ImageButton.Source>                           
</ImageButton>
```
