### ISSUE TITLE
HorizontalOptions="FillAndExpand" is ignored in Android when a stack layout is inside a RefreshView

### ISSUE THREAD

**Issue by YiannisBourkelis** [dotnet/maui#11879]
### Description

I am trying to display a full width stack layout inside a refresh view but it is impossible in Android.
It works on iOS, MacCatalyst and Windows.
If I remove the RefreshView, the stack layout appears as expected. Please check the attached project.

This issue breaks all our existing layouts when migrating a Xamarin.Forms project to MAUI.

Screenshot of the reproduction project running on Android and iOS. Android has the issue.
 
<img width="880" alt="refreshview_full_width_issue" src="https://user-images.githubusercontent.com/2575796/206069622-83e044dd-4adc-41db-aea2-d6f09c122cbd.png">

### Steps to Reproduce

Run the attached reproduction project targeting Android. The stack layout does not occupy the full width of the device screen.

### Link to public reproduction project repository

https://github.com/YiannisBourkelis/maui_issues/tree/main/src/HorizontalOptionsFullWidthIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Pixel 5 Api 33

### Did you find any workaround?

No.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with 17.6 Preview (17.6 build 1539). Not repro on android with sample project.
[maui_issues-main.zip](https://github.com/dotnet/maui/files/11671784/maui_issues-main.zip)
![Screenshot 2023-06-07 102821](https://github.com/dotnet/maui/assets/77434865/2cf505d7-89ae-4e80-bc6c-f292400cf5e6)
