### ISSUE TITLE
[Bug] Cannot build sln from template if was created with `-` in the name

### ISSUE THREAD

**Issue by SirIndubitable** [dotnet/maui#1187]
### Description
If `-` is in the name of a project that is created from a maui template, the projects are not created correctly 
The projects are all created with `-` in the name, except the project references have the `-` changed to a `_`

### Steps to Reproduce

1. Call `dotnet new maui-blazor -n maui-test`
2. Enter maui-test directory
3. Call `dotnet build`

Notice you get this error message:
>The project file "...\maui-test\maui_test\maui_test.csproj" was not found

While this file exists:
`maui-test\maui-test\maui-test.csproj`

### Expected Behavior
Creating a project form a template should create a valid project

### Actual Behavior
The project references are incorrect in the generated solution

### Basic Information

- Version with issue: 6.0.100-preview.4.21255.9
- Last known good version: Unknown
- IDE: None
- Nuget Packages: N/a
- Affected Devices: N/a

### Workaround

Manually changing the project references to have `-` instead of `_`

**Comment by Eilon** [comment]
Ah, yes, I keep forgetting to file this bug! I think this bug affects all the .NET MAUI templates.

**Comment by Eilon** [comment]
I'm closing this because we have another issue logged that also discusses how to fix it, so I'll keep this one: https://github.com/dotnet/maui/issues/2176

Thank you for the report, I'm working on a fix right now!
