### ISSUE TITLE
Xamarin.AndroidX.Work.Runtime support for .net7

### ISSUE THREAD

**Issue by sung-insightly** [dotnet/maui#11887]
### Description

We're in the process of converting our applications to net7 from xamarin.ios and xamarin.android Forms apps. We were originally aiming to target net6 but due to bugs in certain controls (e.g RefreshView with a ScrollView doesn't work) decided we should just bite the bullet and aim for net7.

We have a dependency on Xamarin.AndroidX.Work.Runtime in our Android version of our app. Are there plans to either include Xamarin.AndroidX.Work.Runtime in net7 or will there be an updated nuget package sometime in the future?

### Public API Changes

```cs
using AndroidX.Work;

public class MyWorker : Worker
{
  public override Result DoWork()
  {
    return Result.InvokeSuccess();
  }
}
```

### Intended Use-Case

```cs
using AndroidX.Work;

public class MyWorker : Worker
{
  public override Result DoWork()
  {
    return Result.InvokeSuccess();
  }
}
```

**Comment by mattleibow** [comment]
I think the nuget is updated? I see net6 support in there: https://www.nuget.org/packages/Xamarin.AndroidX.Work.Runtime
