### ISSUE TITLE
iOS Rotate animation is very choppy due to LOTS of unneceesary measure cycles and makes application unusably slow

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#11891]
### Description

In the sample attached below you can see that the robot image rotation is very choppy.  This is particularly evident on an iOS simulator where things run a bit slower than a high end phone.  On my test machine I am getting perhaps 5-10fps.

On Windows and Android this animation runs smoothly and Measure() and MeasureOverride() are not called on the animated control or other controls.

On iOS, Measure() and MeasureOverride() are called all the time.  They are even called on neighboring controls (making the animation even slower).  In the sample you can see they are called for the label even though the animation has nothing to do with the label.

This is a major regression from XF and prevents us from shipping an application ported to MAUI.  In XF, animations did not cause all the unnecessary measure cycles and the animation also ran smoothly on iOS.

[MauiApp4_rotatebug.zip](https://github.com/dotnet/maui/files/10164462/MauiApp4_rotatebug.zip)

### Steps to Reproduce

1. run the sample using iOS simulator
2. debug output shows all the Measure() calls to the rotated and other controls.
3. the animation is slow and consumes a lot of CPU
4. Under Windows+Android this does not happen and the animation is smooth and consumes little CPU.

### Link to public reproduction project repository

see atttached sample

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15,16

### Did you find any workaround?

no

**Comment by philipag** [comment]
Just to be clear about the magnitude of this bug: this bug can essentially cause the entire visual tree to be re-measured for each step of the animation!

**Comment by hartez** [comment]
Fixed by #12627. The fix is available in .NET 8 Preview 1; it has been backported to .NET 7 (#12933), and will be in the next service release.
