### ISSUE TITLE
CollectionView Header/Footer/EmptyView issues when adding/removing items

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#11896]
### Description

An Android, in a CollectionView which defines Header/Footer/EmptyView, I'm facing a lot of issues when adding/removing items.
- the footer is not always shown, it appears only for one in two added items
- when the last item is removed from the source, the header becomes blank and the footer moves to the bottom of the page
- after that, when adding/removing items, the footer does not appears anymore, unless the itemslist becomes empty again

There are also issues on iOS, not exactly the same though...

### Steps to Reproduce

1. Create a maui app with a collectionview
2. Define header/footer/emptyview (and itemtemplate)
3. Add/Remove items from the source and observe what happens, especially for header and footer

### Link to public reproduction project repository

[repro](https://github.com/tranb3r/Issues/tree/main/MauiAppCollectionViewHeaderOrEmpty)
Launch app ; click on button to add a few items ; click on button to remove items until list is empty.

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Latest

### Did you find any workaround?

No workaround

**Comment by tranb3r** [comment]
Similar to #8761

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 3.0(net8). Can repro on Android platform with sample project. [Issues/MauiAppCollectionViewHeaderOrEmpty at main · tranb3r/Issues (github.com)](https://github.com/tranb3r/Issues/tree/main/MauiAppCollectionViewHeaderOrEmpty)

**Comment by tranb3r** [comment]
Is this going to be fixed?
