### ISSUE TITLE
Mac Catalyst Binding Library not callable

### ISSUE THREAD

**Issue by 4or5trees** [dotnet/maui#11890]
### Description

It appears anything in the `ApiDefinition.cs` and `StructsAndEnums.cs` of a Mac Catalyst Binding Library is not callable from MAUI (or other) code. 

With a barebones Mac Catalyst Binding Library containing only the following interface declaration:
```csharp
    [BaseType(typeof(NSObject))]
    interface Widget
    {
    }
```

Strangely, in Visual Studio for Mac 2022 Preview 17.5 there is no syntax highlighting for `BaseType` and `NSObject`:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/31886148/205859609-768d7257-279f-4a9a-8c6a-cfc481951345.png">

I cannot reference this class or any other code defined in these files from either a MAUI app or any other class library: It cannot resolve the references. ("the type or namespace could not be found")

If I create a _separate_ class file within the Mac Catalyst Binding Library, then I am able to reference that class from MAUI with no issues. However, even within this separate class file I cannot reference code from the `ApiDefinition.cs` or `StructsAndEnums ` (see file `EmptyClass.cs` in reproduction project repo)

In Xamarin.Mac it was possible to reference a Bindings Library in the way it currently fails for MAUI.

**Note**: In this example I am not actually adding a Native Framework to the Bindings Library, but I can confirm that in the 'real' project where I encountered this issue that I have the exact same issue when there is a proper Native Framework reference in the Bindings Library.

### Steps to Reproduce

1. Create new MAUI project 
     - Disabling all-but Mac Catalyst functionality
3. Create new Mac Catalyst Binding Library
     - Adding small interface definition to `ApiDefinition.cs` to test if it can be referenced
4. Add reference to Mac Catalyst Binding Library from MAUI project
5. Try to reference code from `ApiDefinition.cs` in the MAUI project, it will not resolve and the build will fail.

### Link to public reproduction project repository

https://github.com/4or5trees/maui-macos-binding-problem

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOs 12.6, VS for Mac 2022 Preview 17.5

**Comment by drasticactions** [comment]
@4or5trees The syntax highlighting would, I think, be an IDE problem. It might not be seeing the project settings for the binding files so it treats them as plain text.

Referencing Binding Libraries is also not a MAUI (The UI Framework) issue. You would have the same issue if you referenced the binding library directly to a Mac Catalyst/iOS/Mac app as well, even if it did not use this UI Framework. If you want to reference it via the csproj, you should be able to reference the underlying build artifacts (As in, reference the DLL that is produced, rather than the project itself.) and that should work.

@rolfbjarne Would you know why you can not reference a binding project directly to an app? Is that a supported use case?

**Comment by drasticactions** [comment]
@rolfbjarne I think they mean that they have a MAUI App, and are trying to reference a Binding project directly as a CSProj, and that doesn't work. The Binding Project builds fine, and if you reference the outputted DLLs inside of another project, it works fine, but if you directly reference that Binding CSProj inside of another project, that won't work.

**Comment by 4or5trees** [comment]
@drasticactions Thank you very much! 
Referencing the built DLL of my bindings project fixes my issue.
