### ISSUE TITLE
[Spec] C# Markup for MVU and MVVM

### ISSUE THREAD

**Issue by VincentH-Net** [dotnet/maui#119]
# C# Markup for MVU _and_ MVVM
Let Maui developers switch and mix MVVM and MVU patterns with minimal markup changes, combining - and improving on - the best of [Comet](https://github.com/Clancey/Comet) markup and [Forms C# Markup](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup).

# Example
This is the C# Markup for the Maui MVU example that @davidortinau [demonstrated at Build 2020](https://aka.ms/Build2020AppDev-DotNet), in versions for MVU and MVVM, both in current markup and in the proposed improved markup:
![MauiCSharpMarkupAlignMvuMvvm](https://user-images.githubusercontent.com/1872271/83105449-fc91db80-a0ba-11ea-8c56-e9d7acb15048.png)

The obvious remaining difference is in bindings, which makes sense because that is what MVVM / MVU is about.

Complete source with markup helpers and logic: [MVU](https://github.com/VincentH-Net/Comet/tree/MAUI/sample/System.Maui.Samples/Markup), [MVVM](https://github.com/VincentH-Net/maui/tree/build/PagesGallery/PagesGallery/Markup).
> **Note** that this source contains an example implementation of helpers for every type of markup improvement described below. The implementation is part of this spec.

# Common Markup Improvements
These changes improve markup readability and conciseness for the current markup in both MVU and MVVM:
- Eliminate `new`
  `new VStack { new Label (), new Button () }`
  =>
  `VStack ( Label (), Button () )`
  
- Eliminate **type name** repetition
  - For helper parameter type ctor overloads:
    `.Color (new Color("#ABCDEF"))`
    =>
    `.Color ("#ABCDEF")`
  - For enums:
    `.TextAlignment (TextAlignment.Left)`
    =>
    `.TextLeft ()`
  - For static values:
    `.Color (Color.White)`
    =>
    `.Color (White)`
  - or using a [fluent subchain](https://github.com/VincentH-Net/Comet/blob/18fa4887adc8315a8003e718bc36fabb45b725fb/sample/System.Maui.Samples/Markup/Helpers.cs#L51):
    `.Color().White ()`
    `.Text().Left ()`

- Format markup
  - Indent view helpers to align with view parameters
  - Spaces before `.` and `(` - similar to the formatting of property names and values in XAML 
  - Group + sort helpers on lines based on category: content, border, layout (see the [Layout Line](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup#layout-line-convention))
```C#
        Button ("Increment")
               .Color (White) .Font (32) // content
               .RoundedBorder (radius: 20, color: Transparent) .Shadow () // border
               .Margin (30) .FillHorizontal () .Frame (height: 76) // layout
```

# MVU Markup Improvements
These changes improve markup readability and conciseness for current C# Markup for MVU, and align the markup to C# Markup for MVVM:
- Shorten overly verbose property names
  `.TextAlignment (TextAlignment.Left)`
  `.LineBreakMode (LineBreakMode.NoWrap)`
  =>
  `.TextLeft ()`
  `.LinesNoWrap ()`

- Single helper for properties that are often set in combination
  `.Color (Color.White) .Background ("#7258F6")`
  =>
  `.Color (White, "#7258F6")`

- Move UI logic to `.logic.cs` partial class file
`LiveStreamSample3Format.logic.cs`:
```C#
    public partial class LiveStreamSample3Format : View
    {
        readonly State<int> count = 0;

        string Message() => $"I will run {count.Value} miles this month.";
        void Increment() => count.Value++;
        void Decrement() => count.Value--;
    }
```

# MVVM Markup Improvements
These changes improve markup readability and conciseness for current C# Markup for MVVM, and align the markup to Comet-style MVU markup:

- Eliminate property name for assigning (not binding) to the default assignment properties of a view
  `new Label { Text = "Hi" }`
  =>
  `Label ("Hi")`

- Eliminate `Children =` and `Content =`
```C#
    new Grid { Children = { 
        new Label { }, 
        new Button { } 
    } }`
```
   =>

```C#
    Grid ( 
        Label (), 
        Button () 
    )
```

- Factory methods for layouts views in Comet
  `new StackLayout { Orientation = StackOrientation.Vertical, Children = { ... } }`
  =>
  `VStack (...)`

# API
The above example demonstrates different types of markup improvements and alignments, and how they could be implemented. The full API results from applying this for all views and properties. This spec is a work in progress, intended to grow into the full API.

# Codegen
As a consequence of eliminating the `new` keyword, a fluent helper is needed for each property of each view. The original implementation of C# Markup avoided this, mainly to prevent that PR to become too big (impact and size) to merge.

As I explained in the original C# Markup PR (see the header [CodeGen API would have little value](https://github.com/xamarin/Xamarin.Forms/pull/8342#issuecomment-554350423)):
> _"While automatically generating a full fluent API would prevent the above (light) maintenance, it would not improve much for the developer. C# markup is improved by intelligently choosing shorter names for the most often used (combinations of) overly verbose property setters."_ 

MAUI may well include fluent helpers for all views and properties (like Comet); if not, it will be simple to generate them for C# Markup.

Most kinds of helpers demonstrated above could be generated (factories, ctor unwrappers, enum and static values).

Both factory methods and property helpers should be generated from the underlying properties, but with intelligent direction to the code gen so we can:
- Register manually coded helpers to set (a combination of) specific properties, to prevent generating unwanted helpers for those properties
- Register manually coded factory methods for a view type with optional parameters to set specific properties, to prevent generating unwanted helpers for those properties. This allows to use renamed and combined parameters for properties, like with the helpers
- Specify whether to use a [fluent subchain](https://github.com/VincentH-Net/Comet/blob/18fa4887adc8315a8003e718bc36fabb45b725fb/sample/System.Maui.Samples/Markup/Helpers.cs#L51) (`.Color () .Black ()`) or joining a property name with a value name ( `.TextLeft ()`) for a property type

# Future
The improvements in this spec are designed to mimic some of [these language improvements](https://gist.github.com/VincentH-Net/c7568727517c4ef4f622815a580316d9). This avenue will also be pursued, but this is more long term.

# Tooling
Two tools would further improve the developer experience of C# Markup:
- Autoformat C# Markup
  Whitespace, group & sort helpers into lines based on category, extract UI logic to partial class. Note that formatting conventions for markup differ from those for logic. This is due to the inherent deeply nested, high cohesive nature of declaratice markup (as opposed to procedural logic). 
- Convert XAML to C# Markup
  So the many existing examples in the internet can be used directly by devs that choose to use C# Markup.

# Backward Compatibility

The C# Markup API only adds to underlying API's; it does not introduce any breaking changes to existing code.

There may be some breaking changes in the C# Markup helpers for Xamarin Forms, but since that feature is currently experimental this is acceptable. Best would be to only move C# Markup in Forms out of Experimental after this spec has been completed and a backport into Forms has been done, to make markup C# compatible when migrating from Forms to MAUI.

All platforms are supported. The API and it's implementation are platform agnostic.

# Difficulty : [medium]
Examples of all types of helpers are already implemented. The main effort would be implementing the codegen with overrides and direction, implementing the tools, and adding full unit tests.

**Comment by nerocui** [comment]
Yes I would want this very much. The current C# markup seems too verbose.

**Comment by jcbeppler** [comment]
> For helper parameter type ctor overloads:
> .Color (new Color("#ABCDEF"))
> =>
> .Color ("#ABCDEF")
> For enums:
> .TextAlignment (TextAlignment.Left)
> =>
> .TextLeft ()

Hi @VincentH-Net, interesting idea but if I understood correctly it may be an issue with different overloads, no?
.Color ("#ABCDEF") => If someone creates a different overload for color, which also could be used as a string as input, how would it be? The person will have to create a different Color class name? Nowadays I see it as more unlimited as the person can do "new Color(#ABCDEF")" or may create a new one like "new ColorBasedOnTheDay("01/01/2001")"

.TextLeft () => How are the guys going to checking if the same property is being repeated? They will have to check in this case if TextRight, TextMiddle.... I imagine that today they check if the same already exist. Also, then when you press the dot, you will have 2000 options in your intelli-sense, no?

>Tool to Convert XAML to C# Markup
One issue I see here is that every Windows Forms developer who don't want to learn XAML will use the tool into existing XAML developed applications.

Sorry if I misunderstood the suggestions.

**Comment by VincentH-Net** [comment]
Hi @jcbeppler, thanks for chiming in. No worries, none of the things you mention are an issue. I'll explain inline below.
 
> Hi @VincentH-Net, interesting idea but if I understood correctly it may be an issue with different overloads, no?
> 
> > .Color (new Color("#ABCDEF"))
> > =>
> > .Color ("#ABCDEF")
> 
> .Color ("#ABCDEF") => If someone creates a different overload for color, which also needs a string as input, how would it be? Will the person have to create a different Color class name? Nowadays it is unlimited as the person can do "new Color(#ABCDEF")" or may create a new one like "new ColorBasedOnTheDay("01/01/2001")"

Replicating ctor overloads as helper overloads - in this example `Color` ctor and `.Color` helper - does not introduce any limitation. Both are the same set of overload signatures. You can add anything you want with either a new helper method name like `.ColorFromDay` or a fluent subchain like `.ColorFrom().Day()`, `.ColorFrom().Month()` etc.

> 
> > .TextAlignment (TextAlignment.Left)
> > =>
> > .TextLeft ()
> 
> .TextLeft () => How are the guys going to check if the same property is being repeated? They will have to check in this case if TextRight and TextMiddle already exist in the syntax.... I imagine that today they only have to check if TextAlignment is being called twice.

We won't. We could, but it is not needed. Even if a dev would overlook that Label() .TextLeft() .TextRight() does not make sense, the last setting will be used. If the result is not what they want they will recognize the issue; otherwise there will only be one method call that is not needed. Btw in the years of CSharpForMarkup use this has never been an issue.

> Also, when you press the dot, you will have 2000 options in your IntelliSense, no?

No; you will have about the same number of extension method intellisense options as for existing properties. You can even select to only show the extension methods. And intellicode shows the most likely first.

> 
> > Tool to Convert XAML to C# Markup
> 
> One issue I see here is that every Windows Forms developer who don't want to learn XAML will use the tool into existing XAML developed applications to convert what they don't understand.

Understanding is not the issue; if you know one, you understand the other since it is the same object model, just with different syntax. The tool is just there to automate the mindless syntax conversion for you.

> 
> Sorry if I misunderstood the suggestions.

NP; I'm happy to clarify where I can

**Comment by jcbeppler** [comment]
Hi @VincentH-Net , thanks for the clarification. That is definitely a change of paradigm. 

I just think it appears a little bit strange the comparison in the code you created (on the right) because it is basically the same as the original (from the left). In your code you just grouped many things on the same line which if you do the same on the left it will have the same size. 

Of course you removed the "new" keyword which is basic from C#, not that it couldn't be done but it will look strange if in some places you need to use it and in others not.

Also for me (maybe because I am long time user) it looks strange that I will have something called VStack and HStack considering that both are StackPanel just with different orientation.

I didn't like so much the changes but I will think more about the subject. :smile:

**Comment by JeroMiya** [comment]
I played around a little with constructor wrapper generators, but I've always been a little unhappy with the look of mixing object initializers, static constructor wrappers, and fluent extension methods. With some of my hand written static constructor wrappers, I ended up adding optional function arguments for each of the properties of the control, so that I could set them in a single function call expression rather than use the fluent API:

```CSharp
// CSharpForMarkup
Content = new Label("Text") { }.
  Margin(5)
  .FillHorizontal()

// Static ctor wrapper with only ctor arguments
Content = Label("Text")
  .Margin(5)
  .FillHorizontal()

// Combined static wrapper
Content = Label(
  text: "Text",
  margin: Uniform(5),
  horizontal: Fill
);

```

The drawback is that it's slightly more verbose than the static ctor wrapper with fluent extensions, and not extensible without additional fluent extensions. But it seems more readable to me maybe?

In an ideal world, I would love to combine two language changes: removing the `new` keyword requirement on ctor calls, and extension properties. Then I could do this:

```CSharp
// Extension properties, elide `new` keyword
Content = Label {
  Margin = Uniform(5),
  HorizontalOptions = FillAndExpand, // static using directive, or maybe new target type enum language feature
  ThirdPartyProperty = someValue, // an extension property defined by a third party
};
```

Obviously these small examples don't really demonstrate the readability issue as much as I'd like but if you've had experience with these layouts hopefully you recognize the issue. Otherwise I can try to come up with a more involved example.

**Comment by Happypig375** [comment]
>
```cs
​//​ Combined static wrapper​
​Content​ ​=​ ​Label​(
  ​text​: ​"​Text​"​,
  ​margin​: ​Uniform​(​5​),
  ​horizontal​: ​Fill​
);
```

That's how Fabulous currently works, https://github.com/fsprojects/Fabulous/issues/738 discusses how to improve.

**Comment by JeroMiya** [comment]
It would also be nice if we could use object initializer syntax with function return values somehow, though that would encourage mutability:

```CSharp
Content = MyStyledLabel("Text") then { Margin = Uniform(5) };
```

With an immutable UI tree, we'd just use the new `with` expression, though for complex controls it might be costly in terms of performance:

```CSharp
Content = MyStyledLabel() with { Margin = Uniform(5) };
```

Here the new `then` keyword would work like `with` except that it wouldn't create a new copy but rather mutate the original.

**Comment by VincentH-Net** [comment]
@JeroMiya both the Combined static wrapper and the object initializer syntax have the limitation that they cannot use the view or the property that you are setting to scope the names of assignable values.

E.g. both `Uniform` and `Fill` (and all other values of that enum and of all other enums for all other property types in the entire framework) need to be present in the scope after `: ` / ` = `
```csharp
​Content​ ​=​ ​Label​(​text​: ​"​Text​"​, ​margin​: ​Uniform​(​5​), ​horizontal​: ​Fill​); // Combined statica  wrapper​
Content = Label("Text") then { Margin = Uniform(5), horizontal​: ​Fill​}; // Object initializer syntax
```

So _each_ possible value that you can potentially assign to _any_ property in the entire UI framework needs to be available in source file (page) context. Including all values of all enums and all static values (e.g. all `Color.White` etc).

You could to this with multiple `using static` classes, but this leads to name ambiguities and intellisense would drown and become useless.

Resolving name ambiguities by prefixing values with a class (enum) name negates the whole point of removing redundant enum / class names.

Avoiding name ambiguities leads to choosing long value names, or to adding a redundant scope in the value by making them an enum (so you get `TextAlignment = TextAlignment.Left` etc), again negating that we want to remove redundant enum / class names.

The power of Fluent is in the `.` - it scopes the possible names based in the view or property type that you are setting.
```csharp
Label("Text") .TextLeft () // Fluent helper joins property name and enum value
Label("Text") .Color () .White () // Fluent subchain scopes White () etc names to after Color() only

Label("Text", textAlignment: TextAlignment.Left) // Forced to use scope name repetition to avoid name collision
Label("Text") then { TextAlignment = TextAlignment.Left } // Forced to use scope name repetition to avoid name collision
```

So the fluent approach scales better to the full framework, if you want to use concise names and don't want to repeat yourself.

**Comment by VincentH-Net** [comment]
@JeroMiya wrote:
> I've always been a little unhappy with the look of mixing object initializers, static constructor wrappers, and fluent extension methods

I had the same feeling; the best scaling approach I could think of to improve that (without changing C#) was:
- Eliminate the use of the object initializer syntax and go full fluent for all properties / values, together with static ctor wrapper
- Format the markup differently. This should be configurable autoformat for markup only

This is the approach I described in this spec, e.g.:
```csharp
Label ("Text")
      .TextLeft ()
      .Color () .Black ()
```

**Comment by VincentH-Net** [comment]
Changing C# is not really in scope for this spec, because we need to release this within a year. Extension properties, optional new in initializers and implicit parameter value type will solve many of the issues that we solve with fluent and static ctor wrapper in this spec.

Perhaps better to collect / discuss thoughts [in this gist](https://gist.github.com/VincentH-Net/c7568727517c4ef4f622815a580316d9) and then create a proper language proposal from that?

One thing though. After we have solved & released with the fluent API, C# changes will mainly help to make UI frameworks lighter, but it will have less additional benefit for the devs who write the markup. So maybe it will not be worth it unless C# is changed to support markup within 6 months...

**Comment by VincentH-Net** [comment]
@Happypig375 wrote
> That's how Fabulous currently works, [fsprojects/Fabulous#738](https://github.com/fsprojects/Fabulous/issues/738) discusses how to improve.

Thanks for that link to the Fabulous discussion. I picked up some insights there that resonate for C# Markup:

The fluent DSL approach has several advantages.
- Better learning & writing through Intellisense showing primarily what is relevant for the current view / property only
- Avoids repeating property names in property values (see [above](https://github.com/dotnet/maui/issues/119#issuecomment-649983736))
- Supports Obsolete handling: you can mark a single extension method as oblolete (but if you would use static wrapper with optional parameters, can't mark a single optional parameter as obsolete)

[Comparing several markup DSLs, SwiftUI comes out on top](https://github.com/fsprojects/Fabulous/issues/738#issuecomment-626395314):
```swift
HStack(alignment = .leading) {
    Label("Hello world")
         .font (.title)
         .color (.grey)

    Image("path/to/image")
}
```
>  So to use a control, you have 4 distinct parts.
> 
> - Its name HStack
> - Its most meaningful properties inside the parentheses (either mandatory or optional - default value is fine but there's a high chance I will change the columns of a Grid for example).
> - Optional child/children
> - Optional additional properties I might change like the color, the padding, etc.
> The meaningful properties are not available as additional property methods.
> 
> The signal-to-noise ratio is pretty good.
> 
> You're also immediately aware of what's important and what's not with the most meaningful properties inside the parentheses.

This spec already comes close to this. To get even close we could adopt:
> The meaningful properties are not available as additional property methods

**Comment by JeroMiya** [comment]
@VincentH-Net Yep, understood. I think your proposal works in terms of consistency and readability, though I think it might benefit the spec if at least some of the more common properties are added as additional optional arguments to the static ctor wrappers, similar to Fabulous. I like that style because it encourages writing code in an immutable way (even if the types themselves are not actually immutable).

I've written a static ctor wrapper generator before, but it was quite limited - particularly with respect to generic types and arguments. And it didn't include additional properties like Fabulous. I'd be interested to see if anyone else has made more progress than I on a more complete solution.

Also, just to clarify on enums - I was assuming some kind of target type inference would be involved to allow unambiguous shortening of the enum values to just the enum value name without the type name repetition, in situations where the enum target type is known (i.e. function arguments or property initializers). That would eliminate the ambiguity storm caused when you try to use too many `static using` statements.

**Comment by VincentH-Net** [comment]
@JeroMiya wrote:
> I think it might benefit the spec if at least some of the more common properties are added as additional optional arguments to the static ctor wrappers, similar to Fabulous.

Yes; that is what I propose - based on things that work well for devs in SwiftUI ([see above](#issuecomment-650044919)):
- The "meaningful properties" become optional parameters in the static ctor wrappers, e.g. `Text` for `Label` but there can be multiple.
- All other properties have fluent helpers

All these are generated from the underlying properties, but with intelligent direction to the code gen so we can:
- Register manually coded, improved helpers to set (a combination of) specific properties, to prevent generating unwanted helpers for those properties
- Register manually coded, static ctor wrapper for a view type with optional parameters to set specific properties, to prevent generating unwanted helpers for those properties. This allows to use renamed and combined parameters for properties, like with the helpers.
- Specify whether to use a fluent subchain (`.Color () .Black ()`) or flattening ( `.TextLeft ()`) for a property type

> Also, just to clarify on enums - I was assuming some kind of target type inference would be involved to allow unambiguous shortening of the enum values to just the enum value name without the type name repetition, in situations where the enum target type is known (i.e. function arguments or property initializers). That would eliminate the ambiguity storm caused when you try to use too many `static using` statements.

Yes, I thought along those lines too; it would require a C# change, hence my [comment on that above](#issuecomment-650026072)

**Comment by VincentH-Net** [comment]
I updated the **CodeGen** section in the spec to include factory methods (aka "static ctor wrappers" @JeroMiya) with optional parameters

**Comment by JajaHarris** [comment]
I really like the recommendation below. Not sure if you are recommending this as an optional approach or as a replacement. I would say go with replacement.

I don't think it would be a good experience where sometimes a StackLayout is used and other times HStack is used. The framework needs to provide consistency. At least for MVU - its a fresh start so break ties with past controls now.

> Factory methods for layouts views in Comet
> new StackLayout { Orientation = StackOrientation.Vertical, Children = { ... } }
> =>
> VStack (...)
