### ISSUE TITLE
[Bug] Microsoft.Maui.Templates is not found in Nuget 

### ISSUE THREAD

**Issue by BalasubramaniSundaram** [dotnet/maui#1191]
### Description
I have followed each instruction and step but i am getting this issue while creating maui new sample 

*https://github.com/dotnet/maui/wiki/Getting-Started

![Screenshot 2021-06-05 175125](https://user-images.githubusercontent.com/45868997/120891695-7aba8380-c627-11eb-901d-527415f33b3d.png)

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by BicycleMark** [comment]
Samw Experience on Mac running OSCX11.2 Big Sur. Wow no time to test anything :)

**Comment by saint4eva** [comment]
Same experience too

**Comment by matt-goldman** [comment]
I had this problem too. Manually adding the preview nuget feed (as described in step 3 of the [getting started doc](https://github.com/dotnet/maui/wiki/Getting-Started) in the wiki solved it for me.

**Comment by Eilon** [comment]
I think this issue is quite out of date now. The templates aren't installed directly from any feed. You can follow the official installation instructions here: https://docs.microsoft.com/dotnet/maui/get-started/installation
