### ISSUE TITLE
[Bug] Cannot build for iOS on mac when Windows targets included in solution

### ISSUE THREAD

**Issue by matt-goldman** [dotnet/maui#1193]
### Description
When attempting to run a MAUI app on macOS, targeting iOS, if there is a WinUI3 target included in the solution (i.e., a vanilla `dotnet new maui` app), the following error is thrown:

```
/usr/local/share/dotnet/sdk/6.0.100-preview.4.21255.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(64,5): error NETSDK1100: Windows is required to build Windows desktop applications. [/Users/matt/Projects/MyMauiApp/src/MAUI/MyMauiApp.Maui/MyMauiApp.Maui.WinUI3/MyMauiApp.Maui.WinUI3.csproj]
```

The described workaround below allows me to get past this step, but this is not ideal as I have to then modify this file depending on which platform I'm working on, or maintain different versions of it.

### Steps to Reproduce

1. Create a new maui app using `dotnet new maui`
2. Attempt to run it using `dotnet build -t:Run -f net6.0-ios;`

### Expected Behavior
The targeted platform should build and run

### Actual Behavior
An error is thrown when running on macOS

### Basic Information

- Version with issue: 6.0.100-preview.4.21255.9
- Last known good version: NA
- IDE: NA
- Platform Target Frameworks: 
  - iOS:  14.5
  
### Workaround
Removing the WinUI3 projects from the solution allows the command to run.
```
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MyMauiApp.Maui", "MyMauiApp.Maui\MyMauiApp.Maui.csproj", "{FEE9FCBC-DA95-4E69-8157-D78278E7A0EE}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MyMauiApp.Maui.WinUI3", "MyMauiApp.Maui.WinUI3\MyMauiApp.Maui.WinUI3.csproj", "{6AB0E142-9C6B-4616-BCA3-EEA64235B93D}"  <---- Delete this
EndProject  <---- Delete this
Project("{C7167F0D-BC9F-4E6E-AFE1-012C56B48DB5}") = "MyMauiApp.Maui.WinUI3 (Package)", "MyMauiApp.Maui.WinUI3 (Package)\MyMauiApp.Maui.WinUI3 (Package).wapproj", "{17A350EA-899A-49B8-8034-E3963C47B89B}".  <---- Delete this
EndProject  <---- Delete this
```

**Comment by jfversluis** [comment]
Hey Matt, thanks for reporting this! I think a lot has changed about the project structure by now so I don't think this is an issue anymore. If you still run into problems, feel free to ping us here or open a new issue. 

Thanks!
