### ISSUE TITLE
Button "normal" visual state not being correctly applied upon release of button

### ISSUE THREAD

**Issue by davepruitt** [dotnet/maui#11947]
### Description

I have created a new .Net MAUI project (the default one that just says "Hello, World!" and then provides a button which you can click, and it counts how may times you clicked the button).

The only thing I have changed in the code is that I have added a "Pressed" visual state to the button style in my `Styles.xaml` file. I want buttons to feel responsive, and the default style doesn't feel responsive at all.

In my "Pressed" visual state, all I do is invert the colors, so the text color is now the primary color, and the button background is now white:
```
<VisualState x:Name="Pressed">
    <VisualState.Setters>
        <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}}" />
        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource Primary}}" />
    </VisualState.Setters>
</VisualState>      
```

I would expect the button to return to its normal state when released, but this is not happening. Here is an image that depicts the current and expected behaviors:

![image_for_bug_post](https://user-images.githubusercontent.com/15479248/206300704-2941dcf2-cbf4-4ab5-8ca8-d141249c0a8e.png)

### Steps to Reproduce

1. Create new default .Net MAUI App
2. Add the following XAML to the Button style in Styles.xaml:
```
<VisualState x:Name="Pressed">
    <VisualState.Setters>
        <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}}" />
        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource Primary}}" />
    </VisualState.Setters>
</VisualState>
```
3. Run the app (deploy to "Windows Machine")
4. Try clicking the button

### Link to public reproduction project repository

https://github.com/davepruitt/bug_reproduction_repository_01_maui_button

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10 Pro, Version 20H2, OS build 19042.1586, .NET 7.0 installed

### Did you find any workaround?

No workaround found so far

**Comment by jfversluis** [comment]
@hartez I think this is fixed with the stuff that you have been doing probably?

**Comment by hartez** [comment]
@davepruitt In addition to your `Pressed` state, add empty states for `PointerOver` and `Focused`:

```XAML
<VisualState x:Name="PointerOver" />
<VisualState x:Name="Focused" />
```

When you release the button and still have your pointer over it, the Button is trying to apply a `PointerOver` state; since that state doesn't exist, it can't move to that state and unapply the `Pressed` state. Adding the empty `PointerOver` state gives it a target state, and allows it to unapply `Pressed`. 

There's a similar issue with `Focused`, which will go away once #11840 is released. But in the meantime, you'll also need an empty `Focused` state.

**Comment by davepruitt** [comment]
@hartez yes adding those two empty visual states fixes the issue. So that is an acceptable workaround for now.
