### ISSUE TITLE
App shell does not fill screen on iOS when no splash screen is added to project.

### ISSUE THREAD

**Issue by DuckScapePhilip** [dotnet/maui#11951]
### Description

If for whatever reason you remove your splash screen from the `.csproj` file, then you get some weird behavior where the application no longer fills the screen.

At the very least, if this is required, it should produce some sort of error or warning when compiling.

This is what I removed:
```
<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
```

The app then looks like:
![IMG_4258](https://user-images.githubusercontent.com/59456945/206342954-e5aec0ae-5b0b-45da-8588-ae3d755f9949.PNG)
![IMG_4257](https://user-images.githubusercontent.com/59456945/206342962-ca909770-236e-42a2-8024-89e7aa48fe9e.PNG)

### Steps to Reproduce

1. Create new iOS project
2. Remove the splash screen from the `.csproj` file
3. Launch the application

### Link to public reproduction project repository

https://github.com/DuckScapePhilip/Bugs/tree/main/MauiAppShellNotFillingScreen

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Make sure you have a splash screen added.

**Comment by Poppyto** [comment]
I can confirm the bug

**Comment by mattleibow** [comment]
This will be much easier to fix once we merge https://github.com/dotnet/maui/pull/12481
