### ISSUE TITLE
Android app crash with NavigationPage in Release build

### ISSUE THREAD

**Issue by reinhardlackner** [dotnet/maui#11978]
### Description

If you use a NavigationPage in Android as Main Page, the app crashes immediately after app start.
But this issue occurs only in Release Build, in Debug Build the app can be started correctly.
In dotnet 6 it was working correctly, in dotnet 7 the app crashes.

### Steps to Reproduce

1) Create a new MAUI app
![image](https://user-images.githubusercontent.com/15954854/206539584-e8a08fe9-d1a2-4b74-96a7-9695272c271d.png)
![image](https://user-images.githubusercontent.com/15954854/206539689-e931b336-f6ef-4c04-bfe4-af4e2f5146d6.png)

2) Replace MainPage = new AppShell() with MainPage = new NavigationPage(new MainPage()) in App.xaml.cs
and start the app in "Release":
![image](https://user-images.githubusercontent.com/15954854/206539902-f0abb16e-5689-4489-9e18-c6cf9bc257c1.png)

3) The app in the Android Emulator in Release Build crashes immediately after Splash screen was shown shortly.
![image](https://user-images.githubusercontent.com/15954854/206540122-31cf0eea-6cdf-4360-8c60-2eaba318ba77.png)

Also tested with a real device and building with dotnet publish... does not work.

When you start the app in debug build, it is working correctly:
![image](https://user-images.githubusercontent.com/15954854/206545523-4c021f71-93b7-4180-92c9-e13f79661896.png)

### Link to public reproduction project repository

https://github.com/reinhardlackner/SampleAndroidNavigationPageIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android in general

**Comment by g0dpain** [comment]
Any updates or workaround with this?
I don't know if this is the same problem but in my project logcat prints errors while inflating com.google.android.material.appbar.appbarlayout and therefore terminating the app

**Comment by mjaravinda** [comment]
Any solution on this

**Comment by twtechstudio** [comment]
Any update on this? Have a fix please.

**Comment by michael-koester** [comment]
Did you tried this: https://github.com/dotnet/maui/issues/12165

**Comment by reinhardlackner** [comment]
@michael-koester 

This bug is not related with [#12165](https://github.com/dotnet/maui/issues/12165) - workaround is not possible.
I tried following steps:
a) changed the type from Debug to Release in Visual Studio... 
b) closed Visual Studio
c) removed the bin and obj folder completely... 
d) open Visual Studio solution again ("Release" is suggested)
d) after that I started in Release build, folders bin + obj were recreated... and the app crashed :-(

**It would be great if this bug would be fixed as soon as possible. For me, this is a major issue and I am not able to convert my Xamarin Forms project to MAUI .net 7 with my navigation page structure.**

**Comment by mattleibow** [comment]
@reinhardlackner I am not able to repro with your sample in release. What version of Android are you running on? Is this a device or the emulator?

What is the output of:

```
> dotnet workload list
```

I am using maui 7.0.59

**Comment by reinhardlackner** [comment]
@mattleibow : I tested that... with the newest version (7.0.59) this issue does not occur any more => it is fixed now.
![image](https://user-images.githubusercontent.com/15954854/223664663-69d3f016-ce89-4822-942b-643ee73a568f.png)
