### ISSUE TITLE
[Bug]Xamarin.Android.Common.Debugging.targets(604,5): error XA0010: No available device.

### ISSUE THREAD

**Issue by PontiacGTX** [dotnet/maui#1197]
### Description

When you launch the sample application from workspace in visual studio code, using NET 6 preview 4 under debug it throws an error when launching as debug 
### Steps to Reproduce
After you Install the required SDK for IOS and Android, aswell Install NET 6 preview4 SDK and then proceed to launch directly from workspace 

### Expected Behavior

Start the mono debugger.

### Actual Behavior
It fails to debug the project and throws the following error
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\11.0.200-preview.4.245\tools\Xamarin.Android.Common.Debugging.targets(604,5): error XA0010: No available device. [C:\Users\PontiacGTX\Documents\maui-samples-main\HelloAndroid\HelloAndroid.csproj]

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: NET 6 preview 4 
  - iOS:  none
  - Android: none
  - UWP:  none
- Android Support Library Version: SDK v29
- Nuget Packages: 
- Affected Devices:

### Screenshots

![imagen](https://user-images.githubusercontent.com/18119088/121078940-87fe7c00-c7a7-11eb-8e91-f1052e1e52c4.png)

### Reproduction Link

-

### Workaround
-

**Comment by giacatno68** [comment]
****

**Comment by PontiacGTX** [comment]
What did the post say?

**Comment by Cfun1** [comment]
Have you tried manually starting the emulator and keep it open/ready, and after that start maui debugging?

**Comment by PontiacGTX** [comment]
when I tried listing the avds there werent any installed oddily

**Comment by PontiacGTX** [comment]
> 
> 
> Have you tried manually starting the emulator and keep it open/ready, and after that start maui debugging?
when I tried listing the avds there werent any installed oddily

**Comment by jfversluis** [comment]
Hey there, thanks for reporting! It has been a while since this preview and new releases have passed since then. I'm going to assume that this has been fixed in the meantime. If not, please feel free to ping us here or open a new issue.

Thanks!
