### ISSUE TITLE
Switching Current Application After Initialization

### ISSUE THREAD

**Issue by bradencohen** [dotnet/maui#11977]
### Description

In Xamarin.Forms, it was relatively easy to "switch" applications. 

For instance, you could initialize an app in one spot:
```
var app = new SecondApp();
app.DoWhatever();
```
And then later, you could do:
`LoadApplication(app);`  to effectively switch.

I couldn't find any equivalent of this in MAUI.
I developed a workaround (although it is admittedly awful):
1. Update 'CreateMauiApp' to use a generic type:
```
public static MauiApp CreateMauiApp<TApp>()
        where TApp : class, IApplication
	{
        var builder = MauiApp.CreateBuilder(false);
        builder
            .UseMauiApp<TApp>()
            ....
       }
```
2. A method that uses reflection to call the areas that seem to be updating the application and related contexts:
```
public void MauiLoadApplication( MauiApp mauiApp )
{
    RegisterActivityLifecycleCallbacks( new ActivityLifecycleCallbacks() );

    var rootContext = new MauiContext( mauiApp.Services, this );

    var extensionsTypes = typeof( MauiApplication ).Assembly.GetTypes();
    var extensionType = extensionsTypes.FirstOrDefault( t => t.Name == "MauiContextExtensions" );
    var miMakeApplicationScope = extensionType.GetMethod( "MakeApplicationScope", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static );

    IMauiContext applicationContext = null;
    try
    {
        applicationContext = ( IMauiContext ) miMakeApplicationScope.Invoke( null, new object[] { rootContext, this } );
    }
    catch (Exception e)
    {
        // Intentionally ignored for now
    }
            
    Services = applicationContext?.Services;

    Current.Services?.InvokeLifecycleEvents<AndroidLifecycle.OnApplicationCreating>( del => del( this ) );

    Application = Services.GetRequiredService<IApplication>();

    this.SetApplicationHandler( Application, applicationContext );

    Current.Services?.InvokeLifecycleEvents<AndroidLifecycle.OnApplicationCreate>( del => del( this ) );
}
```

3. When you need to update the app, create a new one using the builder and use the method we just created:
```
var app = MauiProgram.CreateMauiApp<SecondApp>();
( MauiApplication.Current as MainApplication ).MauiLoadApplication( app );
```

I'm still learning, and if this does exist and I'm doing it completely wrong, please feel free to correct me. 

### Public API Changes

Create a meaningful way to update the application, preferably without having to create an entire new builder.

E.g. 
`LoadApplication( new SecondApp() );`

### Intended Use-Case

In our app (written in Xamarin), we get a lot of XAML and related configuration from a server, with the ability to update what server we're pointed at while in-app. We have another Application that we switch to that allows for that.

Repo demonstrating Xamarin.Forms implementation:
https://github.com/bradencohen/XF-AppSwitchingDemo

**Comment by PureWeen** [comment]
@bradencohen can you include a Xamarin.Forms sample app demonstrating your use case?

**Comment by bradencohen** [comment]
@PureWeen added the repro project to the original proposal

**Comment by bradencohen** [comment]
Closing this because the same functionality can be achieved by swapping out the MainPage of the application.
