### ISSUE TITLE
Published version of app with Popups crashes

### ISSUE THREAD

**Issue by druchti1** [dotnet/maui#11976]
### Description

I wrote a MAUI card playing app that uses Popups (using CommunityToolkit.Maui.Views;).  The app works perfect in development mode.  However, when I create a publish(release) version, it crashes when trying to open popup windows.  There are two types of popup windows, one that return an object and the other does not.  The popups that do not return a value work.  The popups that return an object causes the app to crash.  I have AppCenter configured in the app.  None of the crashes register in AppCenter.  Also, there are two content pages that crash when trying to open.  I posted this error to the MS Questions and Answers website.  The MS moderator told me I should post it here. Both the Android and Windows app crash.  I do not have and IOS or Mac app.

### Steps to Reproduce

Here is the definition of one of the popups.

```XAML
<?xml version="1.0" encoding="utf-8" ?>
<mct:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
           xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
           xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
           CanBeDismissedByTappingOutsideOfPopup="false"
           Size="225,225"
           x:Class="xxxxxxTheGame.Popups.SuggestPickPopup">

    <Grid BackgroundColor="White" HorizontalOptions="Center" VerticalOptions="Center"  HeightRequest="224" WidthRequest="224" >

        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="1*"/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height=".20*" />
            <RowDefinition Height=".40*" />
            <RowDefinition Height=".40*" />
        </Grid.RowDefinitions>

        <Button  x:Name="btnPick" Text="Pick"  Clicked="AcceptSuggestion" Grid.Column="0" Grid.Row="1" 
                 HorizontalOptions="CenterAndExpand" Style="{StaticResource BaseButtonStyleLight}"/>
        
        <Button  x:Name="btnReject" Text="Reject"  Clicked="RejectSuggestion" Grid.Column="0" Grid.Row="2"
                 HorizontalOptions="CenterAndExpand"  Style="{StaticResource BaseButtonStyleLight}"/>

        <Label  x:Name="lblHeading" Text="Click or Tap"  Grid.Column="0" Grid.Row="0" 
                    HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand" TextColor="Black"/>

    </Grid>
</mct:Popup>
```

```C#
using CommunityToolkit.Maui.Views;
using GameLogic;

namespace xxxxxxxTheGame.Popups
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class SuggestPickPopup : Popup
    { 
        private ResponseMessage mResponseMessage;

        public SuggestPickPopup(ResponseMessage pResponseMessage)
        {
            InitializeComponent();
            mResponseMessage = pResponseMessage;
            if (mResponseMessage.Request)
            {
                btnPick.Text = "Pick";
            }
            else
            {
                btnPick.Text = "Pass";
            }
        }

        private void AcceptSuggestion(object sender, EventArgs e)
        {
            mResponseMessage.Response = true;
            ReturnResponse();
        }

        private void RejectSuggestion(object sender, EventArgs e)
        {
            mResponseMessage.Response = false;
            ReturnResponse();
        }

        private void ReturnResponse()
        {
            Close(mResponseMessage);
        }
    }
```

Calling the popup
```C#
            await DisplayAlert("Launch", "2", "OK");
            GameLogic.ResponseMessage oResponse = (ResponseMessage)await this.ShowPopupAsync(new 
                      SuggestPickPopup(new GameLogic.ResponseMessage(e.Response)));
            await DisplayAlert("Launch", "3", "OK");
```

Never gets to the second display alert.

### Link to public reproduction project repository

no repository

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 13, Windows 10.2.22621.819

### Did you find any workaround?

I have not found a work around.

### Relevant log output

```shell
no logs
```

**Comment by PureWeen** [comment]
@pictos thoughts?

**Comment by pictos** [comment]
Interesting, I thought that XAML was compiled in release mode, so it should fail on the build 🤔

**Comment by AswinPG** [comment]
> In the process of creating the sample app I discovered the problem. This xaml code was attached to a button
> 
> Style="{StaticResource BaseButtonStyleLight}"
> 
> BaseButtonStyleLight does exist in the project. It looks like Development mode doesn't care that the static resource doesn't exist where as Release mode thows a hard error.
> 
> Dave

I was also experiencing this issue. Although it was not related to popup. Missing keys are ignored during debugging and causes the app to crash in release build

**Comment by pictos** [comment]
cc: @PureWeen looks like it's a Resource issue
