### ISSUE TITLE
BindableLayout - Invalid height rendered

### ISSUE THREAD

**Issue by MarMarIV** [dotnet/maui#11987]
### Description

When BindableLayout is used in Grid, element with BindableLayout have invalid height

Android:
![droid](https://user-images.githubusercontent.com/10964247/206645309-13158f9d-8430-4da1-8c2c-f56e3a84d905.png)

iOS:
![Snímek obrazovky 2022-12-09 v 8 07 54](https://user-images.githubusercontent.com/10964247/206645316-16b92a35-ca1a-4589-bdfc-500e6d346cc3.png)

### Steps to Reproduce

1. Start example app in repo
2. Scroll down to last item

Expected behavior: There should be 200 items visible
Actual behavior: There is only few items (about 100)

### Link to public reproduction project repository

https://github.com/MarMarIV/BindableLayoutTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Any version

### Did you find any workaround?

No

**Comment by MarMarIV** [comment]
@jsuarezruiz Is there any progress on this BUG?

**Comment by homeyf** [comment]
Verified this issue with 17.7.0 Preview 1.0. Not repro on android and iOS platform with sample project.
https://github.com/MarMarIV/BindableLayoutTest
![image](https://github.com/dotnet/maui/assets/82450723/fd072961-7d54-4c3b-a8c9-b2de890c2e52)
