### ISSUE TITLE
custom font on android only partly loaded: 

### ISSUE THREAD

**Issue by innomotionmedia** [dotnet/maui#11995]
### Description

I am consuming a few fonts on my app and they load in fine on ios, but android only displays font 2 and 3, font 1 is rendered as a standard font. 

### Steps to Reproduce

I am consuming a few fonts on my app:

```cs
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("bebas_neue.ttf", "BebasNeue");
				fonts.AddFont("myriad_pro_reg.ttf", "MyriadReg");
                fonts.AddFont("myriad_pro_semibold.ttf", "MyriadBold");
            });

        builder.UseMauiApp<App>().UseMauiCommunityToolkit();

        return builder.Build();
	}
```

they load in fine on ios, but android only displays font 2 and 3, font 1 is rendered as a standart font. 

### Link to public reproduction project repository

not neccissay

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Android

### Affected platform versions

all

**Comment by mattleibow** [comment]
It may be the font on android for some reason. Are you able to attach a repro with the fonts?

If this is confidential or some copyright things, you can use VS feedback and open a private issue and link to it from here. Then we can check.
