### ISSUE TITLE
some images are rendered at the bottom of the page on ios

### ISSUE THREAD

**Issue by innomotionmedia** [dotnet/maui#11996]
### Description

![grafik](https://user-images.githubusercontent.com/83273576/206724578-acd2309f-eaf7-4cb8-b438-d84dad6bd6a8.png)

### Steps to Reproduce

I have the simplest code available:

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
               xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
               xmlns:res="clr-namespace:Skillbased.Resources"
               x:Class="Skillbased.Pages.LogIn.CreateAccount.Page_Tutorial"
               Title="Page_Tutorial">
       <VerticalStackLayout>
           <Grid Margin="0,30,0,0">        
               <Image Source="img_headerbar"/>
                <Label VerticalOptions="Center"
                      FontFamily="BebasNeue"
                      FontSize="30"
                      HorizontalOptions="Center"
                      Text="{x:Static res:Strings.WarumSkillbased}"/>
           </Grid>
           <Image Source="img_headerbar.png"/>
       </VerticalStackLayout>
  </ContentPage>
```

This renderes as the image above. the first picture is rendered fine, the second one is rendered at the bottom, irregardless of if i use a vertical stack layout or grid or whatnot.

And no, the image does NOT have a big white border at the top or something. 
It is working fine on android 

### Link to public reproduction project repository

na

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

all

### Did you find any workaround?

no

**Comment by jamesmontemagno** [comment]
Can you update your code block? Or create a sample to take a look.
