### ISSUE TITLE
Frame does not render border correctly while corner radius specified on windows platform

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#11990]
### Description

We are using the frame control for showing control with corner radius and border, but the border was not render correctly while corner radius specified on windows platform.

```
 <Grid HeightRequest="400" WidthRequest="350" >
            <Frame Background="White" BorderColor="#E6E6E6" Padding="0" Margin="0">
                <Grid Background="Green"/>
            </Frame>
</Grid>
```

<img width="445" alt="Issue" src="https://user-images.githubusercontent.com/44917578/206673322-4d6d38ca-d346-4164-a66e-8d980ad91a80.png">

**Issue:** 
![Issue](https://user-images.githubusercontent.com/44917578/206673521-26a358fc-aa59-4325-b7c1-6d6ba14334b1.png)

**Note:** We used border control to replace the frame control but border control blur its child(text drawn on drawable view) on windows.

### Steps to Reproduce

1. Create the application with above specified code
2. Run the application 
3. Output UI shown some glitch on left top, right top, left bottom and right bottom of frame

### Link to public reproduction project repository

Not Applicable

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.17134

### Did you find any workaround?

No

### Relevant log output

```shell
Not applicable
```

**Comment by PureWeen** [comment]
This should be fixed here

https://github.com/dotnet/maui/pull/11779

I tested your XAML and it looks good now
![image](https://user-images.githubusercontent.com/5375137/208758389-9d3cc616-3b44-46af-b038-ed12e9a6a394.png)
