### ISSUE TITLE
[Enhancement] ViewModel add OnApearing like methods for async/await invoke

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#120]
## Summary
In traditional way , something async operations can be invoke at OnApearing method in Page.cs , but 
something async operations I want use on viewmodel after the constructor method. Maybe refer the PrismFramework but maybe MAUI can do this without Inherited some class from App.cs

## API Changes
Provide some interface method to implement or abstract method to override in viewmodel.

## Intended Use Case
Viewmodel can do something async/await operations after its constructor finished.

**Comment by ChaseFlorell** [comment]
Prism already has this with [`IPageLifecycleAware`](https://github.com/PrismLibrary/Prism/blob/master/src/Forms/Prism.Forms/AppModel/IPageLifecycleAware.cs)

Essentially, if Maui were to implement something similar, they could just extend the `SendAppearing()` and `SendDisappearing()` methods to check the BindingContext

```csharp
if(element.BindingContext is IPageLifecycleAware lifecycleAware)
{
    lifecycleAware.OnAppearing(); 
}
```

**Comment by dansiegel** [comment]
FWIW, I wouldn't complain about not having to support that in Prism for MAUI

**Comment by MathewLC** [comment]
I don't know if this belogns here but, it would be nice too if passing parameters direct to ViewModel, when navigating between pages, was implemented from the begining. Like queryProperties that shell([link here](https://devblogs.microsoft.com/xamarin/xamarin-forms-shell-query-parameters/))  already has in xamarin.
That is also something that prism support since a long time.

**Comment by VladislavAntonyuk** [comment]
You can write small navigation service:
```
Public interface INavigationService 
{
 Task NavigateTo<ViewModel>();

Task NavigateTo<ViewModel, TObject>(TObject parameter);

}

Public class NavigationService:INavigationService
{
...
var page= GetPageFromVM(ViewModel);
Navigation.NavigationStack.PushAsync(page);
ViewModel.Init(parameter);
...
}
```

**Comment by MathewLC** [comment]
@VladislavAntonyuk  that it's what I actually do.

**Comment by VladislavAntonyuk** [comment]
I totally disagree with the idea of adding page methods to view model. We have code behind for that. VM shouldn’t know anything about the page and can be applied to any page

**Comment by timmi-on-rails** [comment]
I agree with @VladislavAntonyuk 
Though these lifecycle events sound appealing, it will have an effect on the desired loose coupling of View and ViewModel in the MVVM pattern.

Nothing stops me from using the very same ViewModel instance in two different views at the same time. How would the proposed lifecycle interface help in this case?
Maybe passing in the view instance as a parameter?
But this might lead to a tighter coupling of the ViewModel to the concrete type of view.
IMHO this needs more thinking....
