### ISSUE TITLE
Dock > Fill dropdown values missing for a BlazorWebView control

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12006]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Dock--Fill-dropdown-values-missing-for-/10206976)._

---
The Dock > Fill property dropdown for the BlazorWebView control is missing values. Selecting the first empty value does select the correct value, "Fill" for the property's value.

BTW -- IIRC, this problem goes back to the release of 17.3 on my system.

---
#### Luke Latham (GuardRex) on 11/19/2022, 02:47 AM: 

(private comment, text removed)
#### Luke Latham (GuardRex) on 11/19/2022, 02:50 AM: 

(private comment, text removed)
#### Feedback Bot on 11/20/2022, 07:48 PM: 

(private comment, text removed)
#### Artak Mkrtchyan on 12/7/2022, 09:28 PM: 

(private comment, text removed)
#### Feedback Bot on 12/8/2022, 00:35 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Closing, as this was moved here incorrectly. Reopening the VS Feedback ticket instead.
