### ISSUE TITLE
maui blazor ios iframe

### ISSUE THREAD

**Issue by harima34** [dotnet/maui#12012]
### Description

When added a iframe into a razor page, it's oppening the iframe as a new tab on chrome iOS instead of open the iframe into the app.
The problem occure only in blazor webview. On regular webview, is working as expected.

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Add a iframe into a razor page
3. Launch the app on a Iphone and when the razor page will be loaded, the app will reduce and then open the iframe into a new tab of chrome/safari.

Expected outcome : the iframe display into the razor page
Actual outcome : the iframe is opening into chrome in a new tab.

### Link to public reproduction project repository

//

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS15

### Did you find any workaround?

No

**Comment by harima34** [comment]
It's seems is the same issue as this one #5784 (iFrame Automatically Opens Source in New Window at Initialization (iOS Blazor WebView). Did there is no trick or something that can solve the issue ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. What is the content of the iframe? Is it a page from within the same app, or for an external URL ?
