### ISSUE TITLE
[Android]Scrollbars Visibility property "Never" is not working properly in the ScrollView control 

### ISSUE THREAD

**Issue by SuthiYuvaraj** [dotnet/maui#12028]
### Description

I am using MaUI scrollView control and I want to show the scrollbars "never" in the android platform if the content size is less than the view size. I am using the scrollview properties "HorizontalScrollBarVisibility" and "VerticalScrollBarVisibility" as "Never". However the scrollbar is always visible.
[Listview.zip](https://github.com/dotnet/maui/files/10208421/Listview.zip)

### Steps to Reproduce

1.Create a sample with ScrollView
2.Define the content as scrollable and ScrollBarVisibility as "Never"

Expected outcome: ScrollBar should not be visible but the content should be scrollable 
Actual outcome: ScrollBar is always visible

### Link to public reproduction project repository

https://github.com/dotnet/maui/files/10208421/Listview.zip

### Version with bug

Recent preview(net 6.0)

### Last version that worked well
Unknown/other

### Affected platforms

Android

### Affected platform versions

Android 9

**Comment by jfversluis** [comment]
Might be related to #7766

You mention version .NET 6 RC2 in this issue, is that correct? Would you be able to test the latest version and see if it still happens?

Also please add the reproduction as a public GitHub repository instead of a zip file. Thanks!

**Comment by SuthiYuvaraj** [comment]
I am using Visual Studio preview version(Preview Version 17.4.0 Preview 5.0) , Issue is still there.
