### ISSUE TITLE
Updating Image.Source at runtime is not working for iOS

### ISSUE THREAD

**Issue by LennoxP90** [dotnet/maui#12020]
### Description

I am trying to load a byte[] to an image control using 
Source = ImageSource.FromStream( () => new MemoryStream( CurrentImage ) );

this method works fine in android but does not work in iOS unless I trigger a hot reload event in my xaml

https://github.com/LennoxP90/StreamImageSourceIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2.1

**Comment by LennoxP90** [comment]
ended up writing this workaround
```
using CommunityToolkit.Maui.Converters;

 Microsoft.Maui.Handlers.ImageHandler.Mapper.AppendToMapping( "iOSImageFix", ( handler, view ) =>
    {
      if( view.Source is StreamImageSource streamImageSource )
      {
        try
        {
          byte[]? array = 
            new ByteArrayToImageSourceConverter().ConvertBackTo( streamImageSource );
          if( array != null )
          {
            NSData? data = NSData.FromArray( array );
            if( data != null )
            {
              handler.PlatformView.Image = UIImage.LoadFromData( data );
            }
          }
        }
        catch
        {
        }
      }
    } );
```

**Comment by jfversluis** [comment]
Can I please ask you to add a little repro to make sure that we're looking at the right thing?

Thanks!

**Comment by LennoxP90** [comment]
https://github.com/LennoxP90/StreamImageSourceIssue

i tried to recreate it as best i can, It is not exact same way i am doing it in my main app

but the steps are the same 
hide a download this image 
then show the neely downloaded image after it downloaded it from my server that is stored in a byte[] then set the other image to the source of that byte[]

this should all happen with 1 click of the imagebutton

**Comment by mattleibow** [comment]
Just looking at this now and I see that this is not really tied to the steam but rather the image control. If you rotate the device, this triggers a layout and the image appears. Also, when stepping through the code, the image control does not trigger a re-layout when the image changes.

This also happens with URI image sources.

**Comment by mattleibow** [comment]
I think I may have a better repro:

```xaml

<VerticalStackLayout>

    <Image
        x:Name="testImage" />

    <Button
        x:Name="downloadImage"
        Text="Switch"
        Clicked="downloadImage_Clicked" />

</VerticalStackLayout>
```

```cs
private void downloadImage_Clicked(object sender, EventArgs e)
{
    testImage.Source = new UriImageSource
    {
        Uri = new Uri("https://raw.githubusercontent.com/dotnet/maui/3c37d850317e80c19df3c5e754dbce12fb818c6c/Assets/icon.png"),
        CachingEnabled = false
    };
}
```

**Comment by mattleibow** [comment]
This is probably more related to the fact that the URI/stream image sources are async.

**Comment by victorsigga** [comment]
Any workarround on this issue ?

**Comment by MateuszLas421** [comment]
any news ?

**Comment by jsuarezruiz** [comment]
The issue will be fixed by https://github.com/dotnet/maui/tree/fix-12020
