### ISSUE TITLE
[mac][iOS] content clip issue.

### ISSUE THREAD

**Issue by BalachandarSelvam** [dotnet/maui#12022]
### Description

I have used content view in a content page and clipped the  content view on top left and top right corner alone. But in sample that I have attached the scroll view content was not fully visible in iOS and mac but in android and windows complete element was visible. I have attached the sample for your reference.

Expected output:

https://user-images.githubusercontent.com/102292597/206984203-ab3fbbf5-4dd4-4d79-aa28-0a5cd9a29e84.mp4

Actual output on mac and iOS.
 
https://user-images.githubusercontent.com/102292597/206984547-2ea82f38-18d7-43c1-8468-d776faf172d7.mov

### Steps to Reproduce

1. open and run the sample
2. scroll the content you can able to see the first and last element button
3. click the fist element button
4. now scroll the content.

### Link to public reproduction project repository

https://github.com/BalachandarSelvam/Framework-bug/tree/main/ContentClip-Bug

### Version with bug

6.0.547

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

ios - 16, mac os - 13

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Maybe related #9825

Would you be able to check if this also happens on .NET 7?
