### ISSUE TITLE
XAML Binding errors not being reported on Output OR XAML Binding Failure

### ISSUE THREAD

**Issue by hjharvey-MSFT** [dotnet/maui#12035]
### Description

If we create a binding in Xamarin for a property that doesn't exist, then we get an error message in the Output window and under Xaml Binding Failure window.
As seen in this image.
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/57494070/207117610-fcc88dec-f3d4-44f7-9fe0-d604db8a0ced.png">

But in MAUI we do not get such errors.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/57494070/207117901-a07e2296-8577-4e29-826c-c4ce0dedc1ca.png">

### Steps to Reproduce

Please see attached Projects. Very simple repros

Create a new MAUI project. Add a binding that doesnt exist, see that you do not get an error.

### Link to public reproduction project repository

N/A

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Android, Windows

### Affected platform versions

Latest

### Did you find any workaround?

No workaround found.

**Comment by hjharvey-MSFT** [comment]
Microsoft Visual Studio Enterprise 2022
Version 17.5.0 Preview 1.0
VisualStudio.17.Preview/17.5.0-pre.1.0+33103.201
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA658
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.5.90.43013
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.90.43013
Azure App Service Tools v3.0.0

C# Tools   4.5.0-1.22528.5+77904ac785bbddb853161aed9eac6ca03aba0ddf
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Extensibility Message Bus   1.4.1 (main@2ee106a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.0 (52dce31)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2255201+5530de5c8323cd1ecacb497bbab5637907d0fc02
Provides languages services for ASP.NET Core Razor.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.11026.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-1.22528.5+77904ac785bbddb853161aed9eac6ca03aba0ddf
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   17.0.33103.201
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools   17.5.0-beta.22525.1+90f5b1ed0befe8337b923860d29dcd62d4735aef
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Unity   17.4.3.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.5.0.66 (main@fb92eb2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.1.13 (remotes/origin/d17-5@14bdde937f)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.5.3 (3c53880)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.1.0.1 (d17-4/13ba222)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a96bde9
    Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
    SQLite: xamarin/sqlite/3.39.3@23e1ae7
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a


Xamarin.iOS and Xamarin.Mac SDK   16.0.0.92 (3dd3dc52c)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by Larhei** [comment]
Fair. Would be nice to see it at least in the log.

But did you know you could avoid the whole topic by setting x:DataType on your page and get compiled binding?
So if Binding is Wrong... You can not compile
[More Info](https://learn.microsoft.com/dotnet/maui/fundamentals/data-binding/compiled-bindings?view=net-maui-7.0)

**Comment by hjharvey-MSFT** [comment]
what do you set the x:DataType too? 
And what dynamic runtime binding context switches? This compile time error message would help with that. For instance, if you have listview or similar type control you would need a runtime error about the binding. Xamarin does this currently.

**Comment by Larhei** [comment]
`<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:DataBindingDemos"
             x:Class="DataBindingDemos.CompiledColorSelectorPage"
             x:DataType="local:MyViewModel"
             Title="Compiled Color Selector">`

or
`
<DataTemplate x:DataType="local:MyModel">
            <Label Text="{Binding MyProperty}"/>
</DataTemplate>
`
