### ISSUE TITLE
Pair to Mac failed with the error "Failed to install manifest microsoft.net.workload.mono.toolchain.net6 version 7.0.1..."

### ISSUE THREAD

**Issue by EmilyFeng97** [dotnet/maui#12046]
### Description

Pair to mac failed with the error as below:
![image](https://user-images.githubusercontent.com/66412474/207268459-78216183-a0e2-47f4-93c9-fb9e3c1498bc.png)

`Could not install workload 'ios'. Details: Workload installation failed: Failed to install manifest microsoft.net.workload.mono.toolchain.net6 version 7.0.1: microsoft.net.workload.mono.toolchain.net6.manifest-7.0.100::7.0.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://api.nuget.org/v3/index.json"..
`

### Steps to Reproduce

1. Install the Dev17.5 Preview 3 from main branch.
1. Add the following feeds to NuGet.config file.
    ```
    <configuration>
    <packageSources>
    <add key="nuget" value="https://api.nuget.org/v3/index.json"/>
    <add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json"/>
    <add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json"/>
    <add key="dotnet-eng" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json"/>
    </packageSources>
    </configuration>
    ```
1. On the Windows machine, create a new Blazor Hybrid project on the command line using the following:
  `dotnet new maui-blazor -o iOSWindowsProject`
1. Open the iOSWindowsProject solution with Visual Studio.
1. Select the "Pair to Mac" option in the Visual Studio toolbar.
1. Select the mac OS device that is connected to the network and press "Connect".
1. In the next window, enter the username and password for the user account on the macOS machine.
1. Connect the machine.

**Note:**
1. This issue does not reproduce on Dev17.5 preview 2. The version of the manifest "microsoft.net.workload.mono.toolchain.net6" included in Dev17.5P2 is 7.0.0. But the version included in Dev17.5p3 is 7.0.1.
For 17.5P2：
![image](https://user-images.githubusercontent.com/66412474/207274065-90c0656c-bbab-4acb-a713-52c421543002.png)
For 17.5p3:
![image](https://user-images.githubusercontent.com/66412474/207275323-3067f37e-f25f-457d-b3e6-8f91212f5e55.png)

### Link to public reproduction project repository

No

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 

### Did you find any workaround?

No

**Comment by mattleibow** [comment]
We just pushed out a new VS and a new set of workloads. Try updating VS and see if you get all the new things.

That error may be a result of you running workload installs using all the feeds listed - and this gets you some versions of things that are not available when you use the pairing.

**Comment by EmilyFeng97** [comment]
> We just pushed out a new VS and a new set of workloads. Try updating VS and see if you get all the new things.

Thanks for your reply. This issue does not repro on the latest build of Dev17.5.0 Preview 3.0 [33213.368.main].

**Comment by EmilyFeng97** [comment]
These two issue are not repro on the latest build of Dev17.5.0 Preview 3.0 [33215.297.main]. Close it now.
