### ISSUE TITLE
Possible Memory leaks?

### ISSUE THREAD

**Issue by Larhei** [dotnet/maui#12048]
### Description

We are seeing crashes of our app on iOS because of what looks to us like a memory shortage. So we took some time to break down the things we are seeing. 
The provided Repro is doing the following.
After starting the app we call GC.Collect(); and GC.WaitForPendingFinalizers(); every 2 Seconds;
When navigating away from the inital page, we stop calling GC.Collect and WaitForPendingFinalizers.
When navigating back to the start page we start calling GC.Collect(); and GC.WaitForPendingFinalizers(); every 2 Seconds; again.

So in theory because the page is not in the backstack any more, and because it is not single instance on the ioc side, it should get collected.

Of my knowledge it is not guaranteed to Finalize. when calling Collect() and WaitForPendingFinalizers();
This is all fine, but after some time it should kick in. Right?

That is why we added a Page that get´s Finalized after same time. 
After making the changes described in the different views we can see the views get finalized also.
So we would say these are Memoryleaks that can be worked around?

The biggest things we are seeing is that on iOS non of our pages get finalized. Even in the provided Repro an empty Contentpage is not finalizing. This could be because this is expected from your side.. But not for me.
If it is expected. Please give some context why.
If this is not expected, what can we do? Is there a workaround?

### Steps to Reproduce

1. Checkout
2. Run the Sample
3. Navigate to a Sample Page
3. Navagate Back
4. Wait and watch the VS Output to see if Finalizer of the previously navigated page get´s called.

### Link to public reproduction project repository

https://github.com/Larhei/Maui-Issues/tree/main/GarbageCollection

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS, Android, Windows

### Did you find any workaround?

For some things yes. Read the xaml ;-)

**Comment by Vroomer** [comment]
I suppose that this is the same problem I raised as an issue in https://github.com/dotnet/maui/issues/10578# and https://github.com/dotnet/maui/issues/12039.

I think that actual pages do get disposed as I tried to use weak reference for the pushed page in one of the sample and the reference is eventually broken, which probably means that the page was disposed. I'm also unable to see instances of page or view model in VS memory profiler. What I see is a lot of UI bits left behind - controls, bindings, handlers... to me it appears that those are never properly disposed. The problem also seems to be getting progressively worse with more controls on pushed page.

Unfortunately so far the MAUI team doesn't seem to care about this issue, even thought it probably affects all apps in serious manner.

**Comment by jfversluis** [comment]
Sorry you feel that we don't care because we definitely do. It seems you are very experienced and knowledgeable in this area. We're more than happy to also take in any and all contributions you might have in this area to expedite things.

Thank you for your detailed reports which is very helpful!

**Comment by Larhei** [comment]
Hi @jfversluis,

I agree with @Vroomer that a lot of UI bits are left behind. The question from my side would be when can we see a memory profiler on mac to better profile our apps and narrow down the problems? PerfView is not on Mac and what described at https://github.com/xamarin/xamarin-macios/wiki/Profiling is good for speed analysis but not for memory analysis. Xcode Profiler does not help me with that, because it does not seem to work with maui projects (on my machine).
Is it just me? If it´s just me, could someone please point me to some valid documentation how to do memory analysis on mac on maui apps?
