### ISSUE TITLE
[Android] Button Corner Radius is broken with high BorderWidth values

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#12056]
### Description

Button Corner Radius is broken with high BorderWidth values
![issue-button-cornerradius](https://user-images.githubusercontent.com/6755973/207365030-12fe9e0f-8263-4139-8b73-74526db66171.gif)

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/dotnet-maui-testing-playground
2. Launch the App and navigate to the Button test cases.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/dotnet-maui-testing-playground

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by rmarinho** [comment]
I spent some time yesterday looking at this, and I can't figure out why this happens, binging it also didn't show too much about the subject. also looked at the MaterialButton java code and didn't understand yet why this happens. @jsuarezruiz  do you have any ideas here? I also tried using the apperanceModel with CornerSize but no luck

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on android platform with sample project.
[dotnet-maui-testing-playground](https://github.com/jsuarezruiz/dotnet-maui-testing-playground)

**Comment by davidortinau** [comment]
net8 preview 6 doesn't show the corner radius glitch on API 33. Can we close this @jsuarezruiz ?

<img width="783" alt="Screenshot 2023-07-06 at 3 12 31 PM" src="https://github.com/dotnet/maui/assets/41873/d6c31a1d-0a36-4b7d-bc7a-092543747eb7">
