### ISSUE TITLE
File picker not work when publish MAUI as exe on Windows server 2019 +windows 10

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#12052]
### Description

File picker not work when publish MAUI as exe on Windows

### Steps to Reproduce

1.Create Maui app
2.Add file picker implementation from
https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-picker?view=net-maui-7.0&tabs=windows
3.Publisf from command line using:
dotnet publish -f net6.0-windows10.0.19041.0 -c Release /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d"
4.Choose file with file picker and is not working
5.When debugging the app is working.

### Link to public reproduction project repository

...

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

No

### Relevant log output

```shell
....
```

**Comment by mattleibow** [comment]
Just to clarify, what does "not working" mean? Is this that there is no picker that appears or it does appear and a file is not picked? Or it crashes?

**Comment by danies8** [comment]
@mattleibow file is not picked.

**Comment by jsuarezruiz** [comment]
> 6.0 Release Candidate 2 or older

Could you try the same with a WinUI 3 App?, could you share a repro sample?
