### ISSUE TITLE
RemainingItemsThreshold not working on Windows

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12066]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/RemainingItemsThreshold-no-working-on-Wi/10224430)._

---
RemainingItemsThreshold is not working in Windows app.  It works correctly when running on the Android Emulator; i.e., when scrolling to the bottom, it fires the event and calls the listed command.  In the Windows, the command is never triggered.

`

---
#### Feedback Bot on 12/7/2022, 06:19 PM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 12/8/2022, 00:50 AM: 

(private comment, text removed)
#### Rod Barnes on 12/8/2022, 10:57 AM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 12/9/2022, 01:32 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by RodBarnes** [comment]
It manifests in this repository: https://github.com/RodBarnes/NationalParks
