### ISSUE TITLE
[WinUI] Add logic to set `DefaultLabelPosition` on the WinUI CommandBar

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#12063]
### Description

The ToolBar on Windows has a very odd open a close behavior as you can see from the following issues

- https://github.com/dotnet/maui/issues/11300
- https://github.com/dotnet/maui/issues/7034

The container for the Windows Toolbar uses a `CommandBar` which defaults to `DefaultLabelPosition.Bottom` which is what causes this odd open and close behavior

https://user-images.githubusercontent.com/14852843/201446787-bfb7f1f2-eaa9-43e6-9cf9-fd27e2897091.mov

Which pretty much never looks good. 

My current thinking is that we choose between `DefaultLabelPosition.Right` and `DefaultLabelPosition.Collapsed` based on the text that a user has specified

- If the ToolBar Items only contain text:  `DefaultLabelPosition.Right`
- If the ToolBar Items only contain images: `DefaultLabelPosition.Collapsed` 
- If they contain both text and Images we use  `DefaultLabelPosition.Right`
- Add a platform specific (or just an xplat API) that lets users configure this themselves
- Make sure the `ToolTipProperties.Text` property gets mapped to `ToolTipService.ToolTip`

### Steps to Reproduce

```XAML

    <ContentPage.MenuBarItems>
        <MenuBarItem Text="Item"></MenuBarItem>
    </ContentPage.MenuBarItems>

    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Toolbar Item" ToolTipProperties.Text=""></ToolbarItem>
    </ContentPage.ToolbarItems>
```

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WinUI

### Did you find any workaround?

You can set the position yourself by adding a mapper property

```C#
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
#if WINDOWS
        ToolbarHandler.Mapper.Add("FixPlacement", (handler, view) =>
        {
            handler.PlatformView.DefaultLabelPosition = Microsoft.UI.Xaml.Controls.CommandBarDefaultLabelPosition.Right;
        });
#endif
```

**Comment by duindain** [comment]
Can we get this fix backported to .Net 7 please
