### ISSUE TITLE
.NET MAUI Problem with ListView/CollectionView on iOS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12071]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Problem-with-ListViewCollecti/10220493)._

---
[severity:I'm unable to use this version]
I have a program on the MAUI platform with the MVVM pattern. The problem occurs when running on an Iphone (any) of my program with ListView/CollectionView. When I click on the button or try to just fill in the ListView/Collection view, the program just freezes and nothing happens! I can't write a program for iOS! (There is no difference between Release and Debug)

Example:

C#
```
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows.Input;

namespace MauiApp1;

public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
        BindingContext = new MainPageModel();
    }
}

public class MainPageModel : INotifyPropertyChanged
{

    public event PropertyChangedEventHandler? PropertyChanged;

    public ICommand ButtonCommand => new Command(UpdateList);

    private void UpdateList()
    {
        List list = new();
        for (int i = 0; i < 20; i++)
        {
            list.Add(new MainPageModel()
            {
                Example = "Text",
                Test = "Test"

            });
        }
        MyItems = new ObservableCollection(list);

    }

    public ObservableCollection MyItems
    {
        get => _MyItems;
        set
        {
            _MyItems = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(MyItems)));
        }
    }
    private ObservableCollection _MyItems = new ObservableCollection();

    public string Example
    {
        get => _example;
        set
        {
            _example = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Example)));
        }
    }
    private string _example;

    public string Test
    {
        get => _test;
        set
        {
            _test = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Test)));
        }
    }
    private string _test;
}

```
XAML

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage"
             xmlns:local="clr-namespace:MauiApp1"
             x:DataType="local:MainPageModel">
    <ScrollView Padding="6">
        <VerticalStackLayout>
            <Button Text="Add 20 items" Command="{Binding ButtonCommand}" />
            <ListView ItemsSource="{Binding MyItems}" HasUnevenRows="True">
                <ListView.ItemTemplate>
                    <DataTemplate x:DataType="local:MainPageModel">
                        <ViewCell>
                            <Grid>
                                <VerticalStackLayout>
                                    <VerticalStackLayout Margin="0,12,0,0">
                                        <Label Text="{Binding Example}"  />
                                        <Label Text="{Binding Example}"  />
                                        <Label Text="{Binding Example}"  />
                                        <Label Text="{Binding Example}"  />
                                    </VerticalStackLayout>
                                    <VerticalStackLayout Margin="0,12,0,0">
                                        <Label Text="{Binding Test}"  />
                                        <Label Text="{Binding Test}"  />
                                        <Label Text="{Binding Test}"  />
                                        <Label Text="{Binding Test}"  />
                                    </VerticalStackLayout>
                                </VerticalStackLayout>
                            </Grid>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>

```

PS: I work on Windows 11 - Visual Studio and connect to a MacBook Pro  - using the simulator to launch an Iphone

---
#### Feedback Bot on 12/4/2022, 04:37 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Odaronil** [comment]
you copied my XAML code incorrectly from the Developer Community. Please correct it.

**Comment by jsuarezruiz** [comment]
> you copied my XAML code incorrectly from the Developer Community. Please correct it.

Fixed, thanks for let us know.

**Comment by softlion** [comment]
You can't embed a ListView/CollectionView/ScrollView inside a VerticalStackLayout, as a VerticalStackLayout has the height of its content, and a ListView/CollectionView/ScrollView has no height except if you set one through HeightRequest.

So nothing will appear in your example, as the height of your ListView is 0.

Not that the height of a ListView/CollectionView/ScrollView is NOT the height of it's content !

**Comment by Odaronil** [comment]
> You can't embed a ListView/CollectionView/ScrollView inside a VerticalStackLayout, as a VerticalStackLayout has the height of its content, and a ListView/CollectionView/ScrollView has no height except if you set one through HeightRequest.
> 
> So nothing will appear in your example, as the height of your ListView is 0.
> 
> Not that the height of a ListView/CollectionView/ScrollView is NOT the height of it's content !

[softlion](https://github.com/softlion),
If set manually, it works, but it should also work automatically (as in Android). But that's not the only problem. There is a problem with both performance and content display, etc. I think if you made the app with CollectrionView, then you know what I mean. Here Microsoft clearly needs to work on the levels of collectionView for both Android and iOS. Since it is very difficult to make any application without ListView/CollectionView...

**Comment by softlion** [comment]
I don't have any performance issue after embedding CollectionView inside ContentView. It can scroll 10k items very fast.

But I agree that it requires a couple of trick that should be out of the box for everyone.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0(.NET8). Not repro on iOS platforms with sample project (ListViewDemos). [maui-samples/7.0/UserInterface/Views/ListViewDemos at main · dotnet/maui-samples (github.com)](https://github.com/dotnet/maui-samples/tree/main/7.0/UserInterface/Views/ListViewDemos)
