### ISSUE TITLE
.Net MAUI clicked Button stays gray after enabling

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12073]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-MAUI-clicked-Button-stays-gray-afte/10226958)._

---
[severity:I'm unable to use this version]
.NET MAUI Button does not get back to "enabled" appearance after setting IsEnabled = true if it was clicked

Steps to reproduce:

1. Create new .NET MAUI C# project called "EnableButtons"

2. Replace MainPage.xaml and MainPage.xaml.cs with the attached

3. Run in Debug for Windows Machine

4. Click each button and note how it stays gray after the "Loading..." while not clicked buttons are fine

[MainPage.xaml](https://aka.ms/dc/file?name=B64201f68c4f745c895d2e682c2cf7c30638062695119774686_MainPage.xaml&tid=64201f68c4f745c895d2e682c2cf7c30638062695119774686)

[MainPage.xaml.cs](https://aka.ms/dc/file?name=B490cff4eed21471aa3f35f6f7fee9eab638062695223793185_MainPage.xaml.cs&tid=490cff4eed21471aa3f35f6f7fee9eab638062695223793185)

---
#### Feedback Bot on 12/11/2022, 06:31 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by johannes-steurer** [comment]
Same issue here

**Comment by hartez** [comment]
This is fixed by #11840, which should be included in the next service release.
