### ISSUE TITLE
[Proposal] Bring up nightly release builds like on Xamarin.Forms

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#12079]
### Description

At the moment, the interval between releases is roughly about a month. Maybe, it would be more helpful to devs to create nightly builds, like it is in Xamarin.Forms.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="xamarin-ci" value="https://aka.ms/xf-nightly/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

### Public API Changes

None

### Intended Use-Case

So PR's and fixes are faster available for the developers. Also MS gets faster feedback if the PR actually fixed an issue.

**Comment by Symbai** [comment]
https://github.com/dotnet/maui/issues/7653
