### ISSUE TITLE
AppIcon does not deliver what it suggests

### ISSUE THREAD

**Issue by a-einstein** [dotnet/maui#12087]
### Description

The Resources/AppIcon folder strongly suggests its contained icon will be used on all platforms for all applicable purposes. Which would be great.
But it doesn't.

My observations.
- Windows 
  - Taskbar: yes.
  - Apps list: yes.
- Android
  - Window: no.
  - Apps list: no.

With XamarinForms I had this working, but with a lot more hassle of files in multiple platform folders and with multiple dimensions.
My hope was to avoid all that.

So what is it?
- Do I still have to jump through the same hoops and forget  Resources/AppIcon?
- Is it yet to be implemented?
- Or is this a bug?

Same sort of questions for icons in general, and Titles. I may get back to those.

### Steps to Reproduce

See description.

### Link to public reproduction project repository

N.A.

### Version with bug

7.0 (current)

### Last version that worked well

N.A.

### Affected platforms

Android

### Affected platform versions

Android 30.

### Did you find any workaround?

No.

### Relevant log output

```shell
N.A.
```

**Comment by mattleibow** [comment]
I am not sure what you mean about Android. When using the app icon and then having the `<MauiIcon>` in your csproj, the icon should be used for the app in the launcher.

Maybe you can attach a sample so we can see if your csproj/icon is correct.

Also, can you add some pictures here so we can see what you are seeing. Maybe I am misunderstanding what you are meaning.
