### ISSUE TITLE
.NET Maui IOS Release build does not contain iTunesArtwork?

### ISSUE THREAD

**Issue by hattmann** [dotnet/maui#12085]
### Description

Using the `dotnet publish` command does not include an xxxITunesArtwork.png file in the ipa.
Tested with Visual Studio 17.4.2 und Windows and also with Visual Studio for Mac 17.4.1.
If i deploy the ipa to ITunesConnect there is only a white box for the graphic.
![image](https://user-images.githubusercontent.com/4472613/207546317-2eee609c-35a4-4716-b44a-0e0e6e44f3a5.png)

If i look into the ios emulator directory i see several icons ready defined:
![image](https://user-images.githubusercontent.com/4472613/207546529-e3c05a00-3bee-4838-897d-89b3488f8a24.png)

Am i missing a deploy parameter in the project file or is this a bug?

### Steps to Reproduce

Create a new .maui application with all needed certificates, create an ipa and deploy that to itunesconnect with the transporter app

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16.1

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Please post the contents of your `Contents.json` file that you see in the screenshot. It would be helpful if you could add the reproduction as wel request for issues. That will greatly speed up diagnoses and potential fixes. Thanks!

**Comment by hattmann** [comment]
Here is the content of the file `Contents.json`, taken from the directory `iossimulator-x64/resizetizer/rAssets.xcassets/appicon.appiconset` 

{
  "images": [
    {
      "idiom": "iphone",
      "size": "20x20",
      "scale": "2x",
      "filename": "appicon20x20@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "20x20",
      "scale": "2x",
      "filename": "appicon20x20@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "20x20",
      "scale": "3x",
      "filename": "appicon20x20@3x.png"
    },
    {
      "idiom": "iphone",
      "size": "29x29",
      "scale": "2x",
      "filename": "appicon29x29@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "29x29",
      "scale": "2x",
      "filename": "appicon29x29@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "29x29",
      "scale": "3x",
      "filename": "appicon29x29@3x.png"
    },
    {
      "idiom": "iphone",
      "size": "40x40",
      "scale": "2x",
      "filename": "appicon40x40@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "40x40",
      "scale": "2x",
      "filename": "appicon40x40@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "40x40",
      "scale": "3x",
      "filename": "appicon40x40@3x.png"
    },
    {
      "idiom": "iphone",
      "size": "60x60",
      "scale": "2x",
      "filename": "appicon60x60@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "60x60",
      "scale": "3x",
      "filename": "appicon60x60@3x.png"
    },
    {
      "idiom": "ipad",
      "size": "76x76",
      "scale": "2x",
      "filename": "appicon76x76@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "83.5x83.5",
      "scale": "2x",
      "filename": "appicon83.5x83.5@2x.png"
    },
    {
      "idiom": "ios-marketing",
      "size": "1024x1024",
      "scale": "1x",
      "filename": "appiconItunesArtwork.png"
    }
  ],
  "properties": {},
  "info": {
    "version": 1,
    "author": "xcode"
  }
}

**Comment by hattmann** [comment]
I am using die blank .net maui template, only changing the bundle id and the name. If i try to deploy it the .IPA doesn't include any iTunesArtwork, the simulator build does.

**Comment by hattmann** [comment]
I will Do so 👍

msftbot[bot] ***@***.***> schrieb am Do., 15. Dez. 2022,
13:41:

**Comment by mattleibow** [comment]
OK... @Redth could this be that issue we saw with some customers that a build and publish are missing the assets or something...

@hattmann can you expand the ipa and see if the image are being included? Also, maybe attach a binlog of the publish of the ipa. I wonder if everythis is working except the assets are just missi g the very last step of being included...

I know ios did change the order of the build tasks at the last minute. @rolfbjarne could the be a bug in the change?

**Comment by rolfbjarne** [comment]
We have a known bug where if you do `dotnet build` first, and then `dotnet publish` to a different output directory, we won't do the right thing. But `dotnet publish` without `dotnet build` first should work just fine.

A binlog will likely help.

**Comment by jfversluis** [comment]
Instructions on how to create a binlog are here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

**Comment by hattmann** [comment]
Here is the binlog file! (in .zip format!)
[binlog-for-diagnostic.zip](https://github.com/dotnet/maui/files/10260877/binlog-for-diagnostic.zip)

**Comment by rolfbjarne** [comment]
That doesn't look like a full build, the build log is almost empty (it looks like a design-time build for the IDE to make intellisense work)

**Comment by hattmann** [comment]
Oh, sorry, i will try to make another build log today!


Am Di., 20. Dez. 2022 um 08:29 Uhr schrieb Rolf Bjarne Kvinge <
***@***.***>:

**Comment by craigbosward** [comment]
I just tried to upload a Maui IOS to app store.  from XCode it would not validate and it bleated about missing iPad artwork for 167x167 and 157x157.  if i need to add these manually how do you do it?
if I upload via transported it said 3 issues.  2 the ones mentioned above and the 1024 iTunes artwork. 
Here is contents. Json from release object.  It shows iTunes artwork in file.  Any work around?  VS2022 V17.5 preview 2
{
  "images": [
    {
      "idiom": "iphone",
      "size": "20x20",
      "scale": "2x",
      "filename": "appicon20x20@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "20x20",
      "scale": "2x",
      "filename": "appicon20x20@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "20x20",
      "scale": "3x",
      "filename": "appicon20x20@3x.png"
    },
    {
      "idiom": "iphone",
      "size": "29x29",
      "scale": "2x",
      "filename": "appicon29x29@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "29x29",
      "scale": "2x",
      "filename": "appicon29x29@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "29x29",
      "scale": "3x",
      "filename": "appicon29x29@3x.png"
    },
    {
      "idiom": "iphone",
      "size": "40x40",
      "scale": "2x",
      "filename": "appicon40x40@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "40x40",
      "scale": "2x",
      "filename": "appicon40x40@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "40x40",
      "scale": "3x",
      "filename": "appicon40x40@3x.png"
    },
    {
      "idiom": "iphone",
      "size": "60x60",
      "scale": "2x",
      "filename": "appicon60x60@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "60x60",
      "scale": "3x",
      "filename": "appicon60x60@3x.png"
    },
    {
      "idiom": "ipad",
      "size": "76x76",
      "scale": "2x",
      "filename": "appicon76x76@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "83.5x83.5",
      "scale": "2x",
      "filename": "appicon83.5x83.5@2x.png"
    },
    {
      "idiom": "ios-marketing",
      "size": "1024x1024",
      "scale": "1x",
      "filename": "appiconItunesArtwork.png"
    }
  ],
  "properties": {},
  "info": {
    "version": 1,
    "author": "xcode"
  }
}

**Comment by hattmann** [comment]
Hello! After doing intensive research on the problem i found out that, in Visual Studio for Mac there is a Compile Setting to IncludeArtwork.
I am now using this as a commandline switch on Windows:

`dotnet publish myproject.sln -f:net7.0-ios -c:Release /p:ServerAddress=172.16.1.1 /p:ServerUser="fooTest" /p:ServerPassword=1234 /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory="/Users/fooTest/Library/Caches/Xamarin/XMA/SDKs/dotnet/" /p:BuildIpa=true /p:IpaIncludeArtwork=true`

After that my transporter app on the mac reports an error with the appicon:
`2023-02-15 12:32:12.976 ERROR: Asset validation failed (90717) Invalid App Store Icon. The App Store Icon in the asset catalog in 'myproject.app' can't be transparent nor contain an alpha channel. (ID: 0683bbfe-5653-47e5-90f4-4ab07964d9ef)`

To fix this i am now using a 440x440 pixel sized PNG as the appicon.
Settings in my project file:
```
<!-- App Icon -->
<MauiIcon Include="Resources\AppIcon\appicon.png" />
```

The transporter app then accepts the new IPA build with the `IpaIncludeArtwork` Switch on

After iTunesConnect confirmed my upload and manual approving the build als the current build for the app the appstore Image changes to my uploaded image.

Problem solved, hope this helps anyone!

**Comment by hattmann** [comment]
Problem solved, hope this helps anyone!

**Comment by hattmann** [comment]
Problem solved, hope this helps anyone!
