### ISSUE TITLE
java.lang.IllegalStateException: Handshake has already been started TcpClient & SslStream

### ISSUE THREAD

**Issue by ajphall** [dotnet/maui#12084]
### Description

Hi,

I am trying to use a TcpClient and SslStream on an Android device and get the following exception thrown:

`{System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__146`1[[System.Net.Security.SyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at MauiApp2.MainPage.OnCounterClicked(Object sender, EventArgs e) in C:\Users\Andrew-Desktop\source\repos\MauiApp2\MauiApp2\MainPage.xaml.cs:line 31
   at Microsoft.Maui.Controls.Button.Microsoft.Maui.Controls.Internals.IButtonElement.PropagateUpClicked() in D:\a\_work\1\s\src\Controls\src\Core\Button.cs:line 278
   at Microsoft.Maui.Controls.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementManager) in D:\a\_work\1\s\src\Controls\src\Core\ButtonElement.cs:line 85
   at Microsoft.Maui.Controls.Button.SendClicked() in D:\a\_work\1\s\src\Controls\src\Core\Button.cs:line 253
   at Microsoft.Maui.Controls.Button.Microsoft.Maui.IButton.Clicked() in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Button\Button.Impl.cs:line 22
   at Microsoft.Maui.Handlers.ButtonHandler.OnClick(IButton button, View v) in D:\a\_work\1\s\src\Core\src\Handlers\Button\ButtonHandler.Android.cs:line 197
   at Microsoft.Maui.Handlers.ButtonHandler.ButtonClickListener.OnClick(View v) in D:\a\_work\1\s\src\Core\src\Handlers\Button\ButtonHandler.Android.cs:line 212
   at Android.Views.View.IOnClickListenerInvoker.n_OnClick_Landroid_view_View_(IntPtr jnienv, IntPtr native__this, IntPtr native_v) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:line 2285
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121}`

By running `adb logcat -s System.err` I can see another stacktrace of 

`12-14 16:26:19.186 11175 11175 W System.err: java.lang.IllegalStateException: Handshake has already been started
12-14 16:26:19.187 11175 11175 W System.err:    at com.android.org.conscrypt.ConscryptEngine.beginHandshakeInternal(ConscryptEngine.java:376)
12-14 16:26:19.187 11175 11175 W System.err:    at com.android.org.conscrypt.ConscryptEngine.beginHandshake(ConscryptEngine.java:366)
12-14 16:26:19.187 11175 11175 W System.err:    at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
12-14 16:26:19.187 11175 11175 W System.err:    at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:31)
12-14 16:26:19.188 11175 11175 W System.err:    at android.view.View.performClick(View.java:6294)
12-14 16:26:19.188 11175 11175 W System.err:    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
12-14 16:26:19.188 11175 11175 W System.err:    at android.view.View$PerformClick.run(View.java:24774)
12-14 16:26:19.188 11175 11175 W System.err:    at android.os.Handler.handleCallback(Handler.java:790)
12-14 16:26:19.188 11175 11175 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
12-14 16:26:19.188 11175 11175 W System.err:    at android.os.Looper.loop(Looper.java:164)
12-14 16:26:19.188 11175 11175 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6606)
12-14 16:26:19.188 11175 11175 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
12-14 16:26:19.188 11175 11175 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-14 16:26:19.189 11175 11175 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

A simple application to reproduce it is (based on the default template):

`
public partial class MainPage : ContentPage
{
	int count = 0;

	public MainPage()
	{
		InitializeComponent();
	}

	private void OnCounterClicked(object sender, EventArgs e)
	{
		count++;

		if (count == 1)
			CounterBtn.Text = $"Clicked {count} time";
		else
			CounterBtn.Text = $"Clicked {count} times";

		SemanticScreenReader.Announce(CounterBtn.Text);

		var tcpClient = new TcpClient("google.com", 443);
                var sslStream = new SslStream(tcpClient.GetStream());
                sslStream.AuthenticateAsClient("google.com");         
    }
}
`

This is happening on an Android device running 8.1.0.  The only other Android device I have to test is running Android 11 and does not exhibit this behaviour (the connection works fine).

### Steps to Reproduce

Create default MAUI application
Paste the following code into OnCounterClicked
`
var tcpClient = new TcpClient("google.com", 443);
var sslStream = new SslStream(tcpClient.GetStream());
sslStream.AuthenticateAsClient("google.com");
`

### Link to public reproduction project repository

.

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8.1.0

### Did you find any workaround?

No

### Relevant log output

```shell
12-14 16:26:19.186 11175 11175 W System.err: java.lang.IllegalStateException: Handshake has already been started
12-14 16:26:19.187 11175 11175 W System.err:    at com.android.org.conscrypt.ConscryptEngine.beginHandshakeInternal(ConscryptEngine.java:376)
12-14 16:26:19.187 11175 11175 W System.err:    at com.android.org.conscrypt.ConscryptEngine.beginHandshake(ConscryptEngine.java:366)
12-14 16:26:19.187 11175 11175 W System.err:    at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
12-14 16:26:19.187 11175 11175 W System.err:    at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:31)
12-14 16:26:19.188 11175 11175 W System.err:    at android.view.View.performClick(View.java:6294)
12-14 16:26:19.188 11175 11175 W System.err:    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
12-14 16:26:19.188 11175 11175 W System.err:    at android.view.View$PerformClick.run(View.java:24774)
12-14 16:26:19.188 11175 11175 W System.err:    at android.os.Handler.handleCallback(Handler.java:790)
12-14 16:26:19.188 11175 11175 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
12-14 16:26:19.188 11175 11175 W System.err:    at android.os.Looper.loop(Looper.java:164)
12-14 16:26:19.188 11175 11175 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6606)
12-14 16:26:19.188 11175 11175 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
12-14 16:26:19.188 11175 11175 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-14 16:26:19.189 11175 11175 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by drasticactions** [comment]
@ajphall Can you try this in a straight Android app (`dotnet new android`) that doesn't use the MAUI UI Framework? This doesn't seem like something specific to the UI Framework here.

**Comment by ajphall** [comment]
Hi @drasticactions yes I can confirm that a plain Android project has the same issue with the code directly in the MainActivity:

`using System.Net.Security;
using System.Net.Sockets;

namespace test_android;

[Activity(Label = "@string/app_name", MainLauncher = true)]
public class MainActivity : Activity
{
    protected override void OnCreate(Bundle? savedInstanceState)
    {
        base.OnCreate(savedInstanceState);

        // Set our view from the "main" layout resource
        SetContentView(Resource.Layout.activity_main);

        var tcpClient = new TcpClient("google.com", 443);
        var sslStream = new SslStream(tcpClient.GetStream());
        sslStream.AuthenticateAsClient("google.com");
    }
}`

In that case where should an issue like that be reported? https://github.com/xamarin/xamarin-android

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-android#7849
