### ISSUE TITLE
Flickering WebView

### ISSUE THREAD

**Issue by Mielesgames** [dotnet/maui#12089]
### Description

I have been using the webview for a while, it was working perfectly fine, but after a while it started flickering.
I expected to disappear since it appeared out of nowhere and the site I was trying to load was under construction, but that doesn't seem to be the case.

### Steps to Reproduce

1. Add a webview
2. Add a website that doesn't end with ".nl" (that worked perfectly fine for me, but mabye that's the case for servers that are in your country)
3. after a while it starts acting weird (for me it took one or two months before it started flickering, so it isn't really easy to reproduce)

### Version with bug

7.0 (current)

### Last version that worked well

The last version that got released in September

### Affected platforms

Android

### Affected platform versions

idk

### Did you find any workaround?

I haven't found a workaround, I noticed that this bug isn't happening to all sites though

### Relevant log output

```shell
there is no output, just a flickering webview
```

**Comment by Mielesgames** [comment]
https://user-images.githubusercontent.com/83580270/207635977-7cdf517b-1aad-4f3f-90ec-39e1b16cebd8.mp4

This is what is happening on screen (screensharing trough phone link because my laptop can't run an emulator)

**Comment by jsuarezruiz** [comment]
Could you share a small sample where reproduce the issue or a specific url to do some tests?. Thanks.

**Comment by Mielesgames** [comment]
Here's a small repo
https://github.com/Mielesgames/TestApp/tree/ef71617da2559bfad7e5633f7598696c4aac238f

**Comment by vhugogarcia** [comment]
Thanks @Mielesgames for sharing the small sample reproducing the issue.

After some local testing I found out that the flickering occurs when there is not set HeightRequest and  WidthRequest. The following code shows some local tests I did to reproduce the issue:

```xml
<!-- Fixed Height & Width :: WORKS OK (No Flickering) -->
        <WebView x:Name="WebsiteViewFixedSize"
                 HeightRequest="300"
                 WidthRequest="350"/>

       <!-- Fixed Width Only :: FAILED -->
        <WebView x:Name="WebsiteViewPartialSize"
                 VerticalOptions="FillAndExpand"
                 WidthRequest="350"/>

         <!-- Dynamic Size :: FAILED -->
        <WebView x:Name="WebsiteViewFullSize"
                 VerticalOptions="FillAndExpand"
                 HorizontalOptions="FillAndExpand"/>
```

What makes this bug interesting if that only fails with the following URL: `https://www.r-go-tools.com` , others URLs load just fine I even tried to load random websites and they do not show the flickering issue.

I'm not sure if this is a bug in MAUI or the website from that particular domain. If this is a bug maybe @jsuarezruiz can provide more insights about it.

@Mielesgames as a temporary workaround I recommend you to set a fixed height and width to the WebView. You can use the MAUI Essentials in the constructor of the page to get the Display dimensions for height and width and then set those values to the webview control.

**Comment by Mielesgames** [comment]
> Thanks @Mielesgames for sharing the small sample reproducing the issue.
> 
> After some local testing I found out that the flickering occurs when there is not set HeightRequest and WidthRequest. The following code shows some local tests I did to reproduce the issue:
> 
> ```
> 
>         <WebView x:Name="WebsiteViewFixedSize"
>                  HeightRequest="300"
>                  WidthRequest="350"/>
> 
>        
>         <WebView x:Name="WebsiteViewPartialSize"
>                  VerticalOptions="FillAndExpand"
>                  WidthRequest="350"/>
> 
>          
>         <WebView x:Name="WebsiteViewFullSize"
>                  VerticalOptions="FillAndExpand"
>                  HorizontalOptions="FillAndExpand"/>
> ```
> 
> What makes this bug interesting if that only fails with the following URL: `https://www.r-go-tools.com` , others URLs load just fine I even tried to load random websites and they do not show the flickering issue.
> 
> I'm not sure if this is a bug in MAUI or the website from that particular domain. If this is a bug maybe @jsuarezruiz can provide more insights about it.
> 
> @Mielesgames as a temporary workaround I recommend you to set a fixed height and width to the WebView. You can use the MAUI Essentials in the constructor of the page to get the Display dimensions for height and width and then set those values to the webview control.

Thanks for the fix!
it works perfectly fine now

**Comment by Mielesgames** [comment]
> Thanks @Mielesgames for sharing the small sample reproducing the issue.
> 
> After some local testing I found out that the flickering occurs when there is not set HeightRequest and WidthRequest. The following code shows some local tests I did to reproduce the issue:
> 
> ```
> 
>         <WebView x:Name="WebsiteViewFixedSize"
>                  HeightRequest="300"
>                  WidthRequest="350"/>
> 
>        
>         <WebView x:Name="WebsiteViewPartialSize"
>                  VerticalOptions="FillAndExpand"
>                  WidthRequest="350"/>
> 
>          
>         <WebView x:Name="WebsiteViewFullSize"
>                  VerticalOptions="FillAndExpand"
>                  HorizontalOptions="FillAndExpand"/>
> ```
> 
> What makes this bug interesting if that only fails with the following URL: `https://www.r-go-tools.com` , others URLs load just fine I even tried to load random websites and they do not show the flickering issue.
> 
> I'm not sure if this is a bug in MAUI or the website from that particular domain. If this is a bug maybe @jsuarezruiz can provide more insights about it.
> 
> @Mielesgames as a temporary workaround I recommend you to set a fixed height and width to the WebView. You can use the MAUI Essentials in the constructor of the page to get the Display dimensions for height and width and then set those values to the webview control.

This works perfect as a fix, thank you
