### ISSUE TITLE
[Bug] Image source from url doesn´t load (it works for WinUI3 project)

### ISSUE THREAD

**Issue by icebeam7** [dotnet/maui#1210]
### Description
Adding an Image view specifying a URL as its source crashes the app when tested in Android. It works in the WinUI3 project, though, which makes me think that something should be configured in either AndroidEnvironment.txt or somewhere else.

I tried setting `XA_HTTP_CLIENT_HANDLER_TYPE=System.Net.Http.HttpClientHandler` and `XA_TLS_PROVIDER=btls` in `AndroidEnvironment.txt` file but it didn't affect the outcome. 

### Steps to Reproduce

1. Add `<Image Source="https://aka.ms/campus.jpg"/>` inside a ContentPage
2. Deploy it to Android (tested in simulator only). It crashes.
3. Debug and test on WinUI3. It works.

### Expected Behavior
The image should load.

### Actual Behavior
The app crashes in Android.

### Basic Information

- Version with issue: Preview 4
- Last known good version:
- IDE: Visual Studio 2019 Preview 16.11
- Platform Target Frameworks: 
  - iOS:  
  - Android: 30.0.4 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/6038239/121189696-9eb9d700-c86a-11eb-8e3a-033e2f50ef14.png)

**Comment by icebeam7** [comment]
Workaround:

As mentioned by my colleague @humbertojaimes, overriding **MainActivity**'s **OnCreate** method and adding this line, makes it possible to load external images (tested with a list of urls containing flags -https-)

`Java.Lang.JavaSystem.LoadLibrary("System.Security.Cryptography.Native.OpenSsl");`

![image](https://user-images.githubusercontent.com/6038239/123092969-59c99f00-d42b-11eb-95cb-e14512ee53a1.png)

**Comment by Redth** [comment]
Fixed in later previews.

**Comment by hflexgrig** [comment]
Not working for me @Redth  images are loaded on windows, but not on Android.
