### ISSUE TITLE
Shell Tabbar doesn't behave correctly when changing tab icon image (through binding or style triggers)

### ISSUE THREAD

**Issue by MK1985** [dotnet/maui#12105]
### Description

Changing the App Shell tab icon using style triggers or through property binding causes the tab bar icon to behave incorrectly:

1) Icon image changing mechanism starts to work after few initial clicks on tab bar icon.
2) There is a strange icon shuffling/rearranging animation on tab icon change. See: https://github.com/dotnet/maui/issues/11520
3) Tabbarselected color isn't maintained correctly when tab bar icon is being changed. It requires additional click to switch to correct state.

### Steps to Reproduce

1. Change Tab Icon Image through Style triggers or property binding

f.i:

<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiIssueRepro.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiIssueRepro"
    Shell.FlyoutBehavior="Disabled">

    <Shell.Resources>
        <Style x:Key="BrowseTab1" TargetType="Tab">
            <Style.Triggers>
                <Trigger TargetType="Tab" Property="IsChecked" Value="False">
                    <Setter Property="Icon" Value="radio_off.png" />
                </Trigger>
                <Trigger TargetType="Tab" Property="IsChecked" Value="True">
                    <Setter Property="Icon" Value="radio_on.png" />
                </Trigger>
            </Style.Triggers>
        </Style>
        <Style x:Key="BrowseTab2" TargetType="Tab">
            <Style.Triggers>
                <Trigger TargetType="Tab" Property="IsChecked" Value="False">
                    <Setter Property="Icon" Value="radio_off.png" />
                </Trigger>
                <Trigger TargetType="Tab" Property="IsChecked" Value="True">
                    <Setter Property="Icon" Value="radio_on.png" />
                </Trigger>
            </Style.Triggers>
        </Style>
        <Style x:Key="BrowseTab3" TargetType="Tab">
            <Style.Triggers>
                <Trigger TargetType="Tab" Property="IsChecked" Value="False">
                    <Setter Property="Icon" Value="radio_off.png" />
                </Trigger>
                <Trigger TargetType="Tab" Property="IsChecked" Value="True">
                    <Setter Property="Icon" Value="radio_on.png" />
                </Trigger>
            </Style.Triggers>
        </Style>
    </Shell.Resources>

    <TabBar>
        <Tab
            Title="Quotations"
            Icon="radio_off.png"
            Style="{StaticResource BrowseTab1}">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" Route="MainPage1" />
        </Tab>
        <Tab
            Title="Logout"
            Icon="radio_off.png"
            Style="{StaticResource BrowseTab2}">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" Route="MainPage2" />
        </Tab>
        <Tab
            Title="Timer"
            Icon="radio_off.png"
            Style="{StaticResource BrowseTab3}">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" Route="MainPage3" />
        </Tab>
    </TabBar>

</Shell>

### Link to public reproduction project repository

https://github.com/MK1985/MauiShellTabBarIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android SDK 30-33

### Did you find any workaround?

Didn't find any

**Comment by PureWeen** [comment]
You can apply the workarounds from this project to fix this behavior. 

https://github.com/PureWeen/ShanedlerSamples/tree/main/ShanedlerSamples/Library/Workarounds

**Comment by Znow** [comment]
> IsChecked

Does not seem to work...
