### ISSUE TITLE
Error NU1101	Unable to find package Microsoft.Maui. and Error	XA1018	Specified AndroidManifest file does not exist: 

### ISSUE THREAD

**Issue by vikingcodes** [dotnet/maui#1211]
Getting following error when running MAUI project.

Error NU1101	Unable to find package Microsoft.Maui. 
Error	XA1018	Specified AndroidManifest file does not exist: 

![image](https://user-images.githubusercontent.com/976073/121216384-76e46680-c89e-11eb-9547-df7908a75f36.png)

**Comment by ElliottBrand** [comment]
Have you ran the following commands in the root of your project (MauiApp3)?

```
dotnet new nugetconfig
dotnet nuget add source -n maui-preview https://aka.ms/maui-preview/index.json
```

https://github.com/dotnet/maui/wiki/Getting-Started

**Comment by deepaktech94** [comment]
@ElliottBrand Yes

**Comment by ElliottBrand** [comment]
If you ran in command line, be sure to run ```dotnet restore``` too (as mentioned in the Wiki), but you can also add the nuget package source via Visual Studio as seen in this video https://youtu.be/MHISYUrjxQA?t=485

**Comment by deepaktech94** [comment]
@ElliottBrand dotnet restore worked . Thanks

**Comment by jfversluis** [comment]
This is from a while ago. I'm going to assume this is fixed in newer previews. If you still experience this, feel free to let us know or open a new issue, thanks!

**Comment by solvingj** [comment]
@jfversluis Novice here, but I just encountered on clean install of latest Vs2022 17.1.0 preview 1.1 .
