### ISSUE TITLE
The MAUI Blazor doesn't work on iOS 16.2 arm64 simulator

### ISSUE THREAD

**Issue by gdar91** [dotnet/maui#12124]
### Description

After upgrading to iOS 16.2, MAUI Blazor projects started crashing. This applies to devices and simulators.

### Steps to Reproduce

1. Create a new MAUI Blazor project.
2. Create a simulator device with the new iOS 16.2 OS.
3. Run the project on the device.
4. It will display a blank page.

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

### Did you find any workaround?

See these comments:
* https://github.com/dotnet/maui/issues/12124#issuecomment-1480790540
* https://github.com/dotnet/maui/issues/12124#issuecomment-1483707988

**Comment by mkArtakMSFT** [comment]
@gdar91 can you please try this scenario with a MAUI app (not Blazor) and see if that works? Thanks!

**Comment by drasticactions** [comment]
I think the only way you could test iOS 16.2 is if you're using Xcode 14.2, which was just released and is not supported by the currently shipping iOS SDKs. What version of Xcode are you running?

**Comment by Shineway02** [comment]
My Xcode Version 14.2 (14C18)

**Comment by Murkrow02** [comment]
I have the same issue, working on every iOS version but not on 16.2, only a blank page is shown :/

**Comment by MackinnonBuck** [comment]
Thanks for your feedback, @Shineway02 and @Murkrow02.

Could you please check if the issue reproduces on a MAUI project (__*NOT*__ Blazor) with a normal webview?

**Comment by Murkrow02** [comment]
> Thanks for your feedback, @Shineway02 and @Murkrow02.
> 
> Could you please check if the issue reproduces on a MAUI project (**_NOT_** Blazor) with a normal webview?

I tried creating a blank MAUI (not blazor) project and added a simple web view.
The app is working as expected on iOS 16.2

<img width="379" alt="Screenshot 2022-12-19 alle 18 59 45" src="https://user-images.githubusercontent.com/38087157/208490477-4e836358-b71b-45a6-ab26-b5cbc64a478a.png">

**Comment by Murkrow02** [comment]
This instead is what happens on 16.2 and 16.0 (running the same application, simple blank starting project for Blazor MAUI)
<img width="756" alt="Screenshot 2022-12-19 alle 19 03 51" src="https://user-images.githubusercontent.com/38087157/208490998-4d6dcd3d-8b31-4b6a-8251-7841ba8a425d.png">

This is the full log on iOS 16.2

**Comment by Jinjinov** [comment]
I have the same issue. It started when I upgraded macOS to 13.1, Visual Studio for Mac to 17.4.2 and XCode 14.2

My MAUI Blazor project runs ok on MacCatalyst, but on every iOS 16.2 simulator I only see a blank white screen.

**Comment by drasticactions** [comment]
@Jinjinov The current net7.0-ios SDK does not support Xcode 14.2. It would be best if you downgraded back to Xcode 14.1 until it receives support.

This issue could be related to underlying issues within the SDK that needs to be addressed.

**Comment by mkArtakMSFT** [comment]
@drasticactions do you know of another tracking issue for the SDK issue that you're suspicious of?

**Comment by ktravelet** [comment]
confirmed that downgrading to 16.1 is working

**Comment by datvm** [comment]
Also it only affects me on Simulator somehow. Testing on real iPhone works though it sucks because I can no longer use Simulator to take screenshots for the App Store. Will check if downloading lower Simulator image version (without XCode) works.

**Comment by sjbthfc2** [comment]
Is there an estimation ot ETA of when .NET 7 sdk will work with xCode 14.2?

**Comment by datvm** [comment]
I am pretty sure the latest VS for Mac works *only* with XCode 14.2 (I don't know about the Windows connection thing, I could never get it to work for me so I just use VS for Mac).

So here's how it was after I updated to the latest VS for Mac:

- I cannot compile anything because I had XCode 14.0 or 14.1. It says something like I need to have XCode 14.2.
- After upgrading, I could compile and run the app well.
- However as others said, the Blazor app simply shows a blank screen on iOS Simulator (only Blazor app, MAUI app works well, so I assume it's some problem with the Simulator WebView). Note that it's running fine for real devices.
- Worse, before I could try using older Simulator version. On last update, VS no longer see simulators under 16.x (? not sure, the latest version of iOS). I can only see Simulators with the latest version.

So what it means:

- I can only debug on real phone.
- Apps can still be installed manually on older simulator version by drag-n-dropping the file in `bin\Debug` folder into the Simulator window. However that means no debug is possible. This is only useful if you need screenshot for the Store.

Hope these problems can be fixed soon.

**Comment by hakonn** [comment]
This also makes it impossible to upload apps for review, since the Blazor apps also crashes in the simulator during review. "We were unable to review your app as it crashed on launch." 

A fix would be greatly appreciated :-)

**Comment by datvm** [comment]
Can confirm with @hakonn , now 16.2 simulator simply shows blank screen, while trying to manually install the app through drag-and-drop to older simulators (16.0) would just crash on startup. We have no problem with review though since it runs fine on real devices. It's still an issue that needs to be fixed I believe.

**Comment by gdar91** [comment]
They seriously need to review their Xamarin MAUI compilation pipeline and maybe allocate more brainpower for it. Even if they say the GA is there, you can’t depend on it, because when you actually try to use it in production, lots of issues and blockers pop up.

**Comment by Lazzerman42** [comment]
why is microsoft so quiet about this? It is a serious bug and we get no information on the progress. Meanwhile they're bashing the drum for hybrid razor on all plattforms.  I'm really frustrated - feels like the bad old Xamarin days.

**Comment by rolfbjarne** [comment]
Can anyone reproduce this on an intel machine, or does it only happen on M1/M2 macs?

**Comment by datvm** [comment]
Pretty sure that changed by the recent [Visual Studio 2022 for Mac v17.4.5](https://learn.microsoft.com/en-us/visualstudio/releases/2022/mac-release-notes#17.4.5) (VS2022 on Windows has a similar update):

> Added support for Xcode 14.2 for Xamarin.iOS and Xamarin.Mac.

I haven't tried the update on my Mac yet (someone mentioned Intel vs M1/M2 Macs, I only have a M2 Mac) but last time I tried, my previous comment was still correct.

**Comment by Murkrow02** [comment]
I can confirm it’s a M1/M2 bug, working fine on intel machine

Il giorno ven 17 feb 2023 alle 16:47 Rolf Bjarne Kvinge <
***@***.***> ha scritto:

**Comment by Murkrow02** [comment]
> Can anyone reproduce this on an intel machine, or does it only happen on M1/M2 macs?

I can confirm it's only a M1/M2 bug, working fine on my Intel machine. Still an issue if Apple reviewers use Apple silicon (very likely)

**Comment by rolfbjarne** [comment]
> Still an issue if Apple reviewers use Apple silicon (very likely)

AFAIK reviewers use actual devices, and this issue only happens in the simulator.

Does the problem still occur when using `iossimulator-arm64` as the RuntimeIdentifier? i.e. add something like this to the csproj:

```xml
<PropertyGroup>
    <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
</PropertyGroup>
```

**Comment by datvm** [comment]
Can confirm, we have many iOS apps successfully published and passed reviews without any issue (no `RuntimeIdentifier` needed). I simply set the Profile in Bundle Signing (in project property dialog).

**Comment by DC8394** [comment]
@rolfbjarne 
> Does the problem still occur when using `iossimulator-arm64` as the RuntimeIdentifier? i.e. add something like this to the csproj:
> 
> ```
> <PropertyGroup>
>     <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
> </PropertyGroup>
> ```

Yes, the problem also occurs if the RuntimeIdentifier is set.

I really hope this issue gets resolved soon. Apple already released Xcode 14.3 beta and MAUI doesn't even support 14.2 correctly, which was released over two months ago.

**Comment by rolfbjarne** [comment]
> @rolfbjarne
> 
> > Does the problem still occur when using `iossimulator-arm64` as the RuntimeIdentifier? i.e. add something like this to the csproj:
> > ```
> > <PropertyGroup>
> >     <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
> > </PropertyGroup>
> > ```
> 
> If the `RuntimeIdentifier` is set to `iossimulator-arm64`, I get the following error:
> 
> ```
> Xamarin.Shared.Sdk.targets(1225, 3): clang++ exited with code 1:
> ld: in /Users/username/Projects/MauiProject/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/e_sqlite3.a(sqlite3.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/username/Projects/MauiProject/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/e_sqlite3.a'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

It seems you're using a third-party native library that doesn't support arm64 in the simulator.

> I really hope this issue gets resolved soon. Apple already released Xcode 14.3 beta and MAUI doesn't even support 14.2 correctly, which was released over two months ago.

This is a bit complicated to investigate, because Apple's web view rendering is remoted into a different process, and the problem is that this other process crashes. I wouldn't be surprised if this turns out to be a bug in the iOS simulator, because realistically nothing we do should be able to crash this other rendering process.

**Comment by rolfbjarne** [comment]
> > Still an issue if Apple reviewers use Apple silicon (very likely)
> 
> AFAIK reviewers use actual devices, and this issue only happens in the simulator.
> 
> Does the problem still occur when using `iossimulator-arm64` as the RuntimeIdentifier? i.e. add something like this to the csproj:
> 
> ```
> <PropertyGroup>
>     <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
> </PropertyGroup>
> ```

We've tested this a bit, and it seems that this is the solution.

At some point we'll change the default to build for iossimulator-arm64 when using an ARM64 Mac, but this won't be until .NET 8 at least (it's a rather major change, and it also means a lot of third-party libraries need to add support for iossimulator-arm64 as well - as evidenced by this [previous comment](https://github.com/dotnet/maui/issues/12124#issuecomment-1441314180)).

In the meantime it's possible to add this yourself to the project file.

**Comment by baddinosaur-kyle** [comment]
I can confirm this fixed it for us.

**Comment by rolfbjarne** [comment]
Here is a solution that handles a few more scenarios (from https://github.com/xamarin/xamarin-macios/issues/17841#issuecomment-1480439593).

Add this to the csproj:

```xml
<PropertyGroup>
  <_OSArchitecture>$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)</_OSArchitecture>
  <_TargetPlatformIdentifier>$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)'))</_TargetPlatformIdentifier>
  <RuntimeIdentifier Condition="'$(_TargetPlatformIdentifier)' == 'ios' And '$(_OSArchitecture)' == 'Arm64' And ('$(_iOSRuntimeIdentifier)' == 'iossimulator-x64' Or ('$(_iOSRuntimeIdentifier)' == '' And '$(RuntimeIdentifier)' == ''))">iossimulator-arm64</RuntimeIdentifier>
</PropertyGroup>
```

* It will only set the RuntimeIdentifier to `iossimulator-arm64` when building on an ARM64 machine.
* It will not overwrite RuntimeIdentifier when building for device from within the IDE.
* It will default to `iossimulator-arm64` when building from the command line on an ARM64 machine.

**Comment by DC8394** [comment]
Unfortunately, this still didn't fix it for us.

It fails with the following error:
```
Xamarin.Shared.Sdk.targets(1225, 3): clang++ exited with code 1:
ld: in /Users/username/Projects/MauiProject/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/e_sqlite3.a(sqlite3.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/username/Projects/MauiProject/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/e_sqlite3.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any idea why this happens?

**Comment by MaxwellDAssistek** [comment]
Neither of the workarounds above work for me. I have a slightly unconventional scenario where the blazor webview is in a separate MAUI class library. I tried adding both `<RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>`  and the other workaround to both the class library and the main project file with no luck.

Here is the log of the simulator: https://pastebin.com/raw/07wuQiBE

**Comment by TranNguyen17893** [comment]
> This is very annoying to deal with because I am forced to downgrade to .net 7.0.100 and ios workload 16.1 to be able to still use Xcode 16.1
Did you try to use the old iOS 16.1 simulator on Xcode 14.2 (iOS 16.2)?

**Comment by rolfbjarne** [comment]
> Unfortunately, this still didn't fix it for us.
> 
> It fails with the following error:
> 
> ```
> Xamarin.Shared.Sdk.targets(1225, 3): clang++ exited with code 1:
> ld: in /Users/username/Projects/MauiProject/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/e_sqlite3.a(sqlite3.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/username/Projects/MauiProject/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/e_sqlite3.a'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Any idea why this happens?

My guess is that the native sqlite library you're using doesn't contain an arm64 version for the simulator (it's trying to link in an arm64 version for device, which won't work).

You'll need an updated version of the sqlite library.

**Comment by mathewgrabau** [comment]
The RuntimeIdentifier workaround worked for me. I am glad that the workaround provided a path forward, but it still leaves me feeling that MAUI is in chaos right now.

**Comment by foximoxi** [comment]
The problem with this issue is that Apple is using arm64 simulators and does not want to validate working application.
Maintenance of any multiplatform application on MAUI is really difficult. 
I can update MAUI for Android and cannot for iOS because of this.

**Comment by steinbachio** [comment]
@foximoxi I got it through the verification process by stating in the test notes that they should test it on intel simulators or real hardware and referencing this issue.
