### ISSUE TITLE
Azure DevOps builds failing with latest version of MAUI

### ISSUE THREAD

**Issue by jdunaway** [dotnet/maui#12122]
### Description

Please see this issue https://github.com/actions/runner-images/issues/6771  I'm getting the same error in Azure Dev Ops Pipeline builds that were working earlier this week.

### Steps to Reproduce

1. Try to build azure devops pipelines for maui iOS with  vmImage: 'macos-12'
2. The build was working earlier this week but is now failing with this error: ILLINK : error MT0180: This version of Microsoft.iOS requires the iOS 16.1 SDK (shipped with Xcode 14.1). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/TransportACE_Maui/TransportACE_Maui.csproj::TargetFramework=net7.0-ios]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: This version of Microsoft.iOS requires the iOS 16.1 SDK (shipped with Xcode 14.1). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/TransportACE_Maui/TransportACE_Maui.csproj::TargetFramework=net7.0-ios]

### Link to public reproduction project repository

None

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

(https://github.com/actions/runner-images/issues/6771#issuecomment-1353590992)

### Relevant log output

```shell
ILLINK : error MT0180: This version of Microsoft.iOS requires the iOS 16.1 SDK (shipped with Xcode 14.1). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/TransportACE_Maui/TransportACE_Maui.csproj::TargetFramework=net7.0-ios]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: This version of Microsoft.iOS requires the iOS 16.1 SDK (shipped with Xcode 14.1). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/TransportACE_Maui/TransportACE_Maui.csproj::TargetFramework=net7.0-ios]
```

**Comment by jdunaway** [comment]
Please see this comment for a workaround for this issue:  https://github.com/actions/runner-images/issues/6771#issuecomment-1353590992

**Comment by drasticactions** [comment]
The underlying SDKs are updated to support Xcode 14.1, and don't work with other versions of Xcode. So yes, the runners needs to be updated to point to the right version of Xcode, same as it would on your local machine.

**Comment by jfversluis** [comment]
Not much we can do about this on our end unfortunately. As mentioned, a workaround is here: https://github.com/actions/runner-images/issues/6771#issuecomment-1353590992

That is also the place where to track progress on getting Xcode 14.1 installed on these machines.

**Comment by trevortirrell** [comment]
> also the place where to

What do you mean? This is happening to us also in Azure DevOps. UseDotNet@2 isn't compatible with the dotnet workload install maui command. 

We couldn't even get our iOS app to deploy from VS on Windows after the .Net 7 update 3 days ago. Had to update XCode to 14.1 to get it to work. But the only documentation from devblogs shows it doesn't support XCode 14.1.

Took us 3 days to get this working again.  Wound be helpful if this stuff was tested and documented better.
