### ISSUE TITLE
IImage.AsBytes() takes float quality 0..1 but complains about quality not being 0..100 when 50 is entered

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#12158]
### Description

_Probably just the exception message is wrong._

When calling image.AsBytes for a jpg image with quality `50`, the following code is executed:

![image](https://user-images.githubusercontent.com/64279914/167227855-deab4758-ad96-4404-900b-7df91d83207e.png)

but it outputs: 

`**Java.Lang.IllegalArgumentException:** 'quality must be 0..100'`

I don't know if Windows is affected because Windows cannot load IImage at all currently.

### Steps to Reproduce

export IImage on Android

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 (API 30)

### Did you find any workaround?

use quality / 100f -> 0..1

**Comment by drasticactions** [comment]
@janseris The code has since moved into the MAUI repo, so none of those issues are probably being triaged. I moved it for you.

**Comment by janseris** [comment]
@drasticactions Thank you. Could you please also move my 2 other issues from the Maui.Graphics repo to MAUI?
It's these two:
https://github.com/dotnet/Microsoft.Maui.Graphics/issues/423
https://github.com/dotnet/Microsoft.Maui.Graphics/issues/422

**Comment by Christerad** [comment]
> @drasticactions Thank you. Could you please also move my 2 other issues from the Maui.Graphics repo to MAUI? It's these two: [dotnet/Microsoft.Maui.Graphics#423](https://github.com/dotnet/Microsoft.Maui.Graphics/issues/423) [dotnet/Microsoft.Maui.Graphics#422](https://github.com/dotnet/Microsoft.Maui.Graphics/issues/422) And also this issue which is very much related to my issue 423: [dotnet/Microsoft.Maui.Graphics#450](https://github.com/dotnet/Microsoft.Maui.Graphics/issues/450)

https://github.com/dotnet/Microsoft.Maui.Graphics/issues/423
https://github.com/dotnet/Microsoft.Maui.Graphics/issues/422
These problem isnt being solved ? any updates ?
