### ISSUE TITLE
Android Release Mode app crash during startup

### ISSUE THREAD

**Issue by XamerDev** [dotnet/maui#12165]
### Description

Hello after upgrade to the newest version of Visual Studio my app in ReleaseMode crash during startup without any errors. 
Previous version worked properly.
Debug mode works properly. I heven't seen any errors during compilation too. 
Can you please check my binlog?
***

### Steps to Reproduce

1. App immediately stops after splash screen in release mode on android

### Link to public reproduction project repository

----

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android all

### Did you find any workaround?

nope

**Comment by FM1973** [comment]
I have / had the same problem.
If you let the release mode run on a local device and open the device log you can see, that there is a mismatch between the expected maui version (dll.so) and the included maui verion in the package.
I then deleted the bin and obj folder of my release build and did a recompile.
After doing so the release version started normally.
So I think that doing a rebuild the maui.dll doesn´t get replaced. As I said, cleaning bin and obj should help. At least in my case.
I keep my fingers crossed this works for you as well.

**Comment by XamerDev** [comment]
@FM1973 thanks it works now

**Comment by jfversluis** [comment]
Thanks for the help here @FM1973 ! Awesome work!

**Comment by christallire** [comment]
this needs to be pinned
