### ISSUE TITLE
AVFoundation Migration to .NET 7 Maui 

### ISSUE THREAD

**Issue by alaskanrogue** [dotnet/maui#12176]
### Description

AVFoundation doesn't support .NET 7 and is still associated with Xamarin. The assembly needs to be migrated.

### Public API Changes

No public API changes are known to be needed.

### Intended Use-Case

In my migration to Maui .NET 7, the AVFoundation not installable, stating incompatibility with the framework version. I also noticed that Xamarin appears to be directly associated to the Nuget.

**Comment by mphill** [comment]
Which assembly are you talking about? The AVFounation namespace is in the MAUI runtmie.  Do you have a small code sample?

**Comment by alaskanrogue** [comment]
I don't find the assembly as part of Maui.

![Screenshot 2022-12-18 213008](https://user-images.githubusercontent.com/14001196/208336221-77eed984-1206-4744-8b8c-2a627b863ca7.png)

If I try to load the Nuget, I get:

![Screenshot 2022-12-18 212554](https://user-images.githubusercontent.com/14001196/208336297-6512a5ba-e231-4c10-b3ad-30bfcd509bdc.png)

**Comment by jfversluis** [comment]
You shouldn't need to install any plugin.

The fact that you don't see `AVFoundation` in your screenshot probably has to do with the fact that that file is not compiled as part of the iOS target. I can't say for sure as the information needed for that is just outside the screenshot 😄  this has to do with multi-targeting, read more on that here: https://learn.microsoft.com/dotnet/maui/fundamentals/single-project?view=net-maui-7.0#platform-specific-code

As you can see in this project, AVFoundation is available right from .NET MAUI: https://github.com/jfversluis/Plugin.Maui.Audio/blob/main/src/Plugin.Maui.Audio/AudioPlayer.macios.cs

I don't think there is an issue here for us that is actionable so I will close this one for now.

**Comment by alaskanrogue** [comment]
I wasn't referring to "Plugin,Maui.Audio" Nuget directly. I have it working with AzureCognitiveServices. 

What I am trying to do is implement a backup speech service using MauiCognitiveServices in case AzureCognitiveServices goes down. After upgrading to .NET 7, MauiCognitiveServices began failing when deployed to iOS trying to use an API that wasn't present referring to the assembly.
