### ISSUE TITLE
Images in CollectionView displayed incorrectly

### ISSUE THREAD

**Issue by Matmork** [dotnet/maui#12182]
### Description

When using images in CollectionView they display incorrectly when scrolling. Often the wrong image for the item is displayed, or it shows an image on an item that should not have one.

See attached video. Rows with label "False" should not have an image.

https://user-images.githubusercontent.com/11912795/208201035-bea0cb93-cb91-4001-8062-974f7b059665.mp4

https://user-images.githubusercontent.com/11912795/208252468-816238f5-37e7-421b-b5cb-479a069cb7ec.mov

### Steps to Reproduce

1. Clone and run repro project
2. Scroll CollectionView
3. Start to see incorrect images/images where it should be none

### Link to public reproduction project repository

https://github.com/Matmork/MauiCollectionViewImage

### Version with bug

7.0.52 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, iOS

### Affected platform versions

API 32, iOS 16.2

### Did you find any workaround?

No

**Comment by Matmork** [comment]
Also happens with `IsGrouped="False"`

https://user-images.githubusercontent.com/11912795/208238753-c5435ec0-957a-4586-9327-19def18b5bad.mp4



Also tried to set `CachingEnabled="False"` on image
```
<Image.Source>
    <UriImageSource Uri="{Binding ImageUrl}"
                    CachingEnabled="False"
                    CacheValidity="30:00:00:00" />
</Image.Source>
```

**Comment by angelru** [comment]
This is an error that happens from Xamarin Forms, I don't know if it is from Image or CollectionView.

**Comment by minglu** [comment]
Same here
