### ISSUE TITLE
Flexlayout into CollectionView crashes

### ISSUE THREAD

**Issue by RobertoGFilho** [dotnet/maui#12189]
### Description

Houston, we have a problem!

Flexlayout into CollectionView crashes if we have a label into flexlayout, see:

        <CollectionView ItemsSource="{Binding Items, Mode=OneWay}">
            <CollectionView.ItemTemplate>
                <DataTemplate>                    
                    <FlexLayout>
                        
                        <Label Text="{Binding ., Mode=OneWay}" />
                </FlexLayout>
            </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

But, if we set a heigth on label this problem dissapear see:

        <CollectionView ItemsSource="{Binding Items, Mode=OneWay}">
            <CollectionView.ItemTemplate>
                <DataTemplate>                    
                    <FlexLayout>
                        
                        
                </FlexLayout>
            </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

### Steps to Reproduce

1. Create a new MAUI project;
2. Add CollectionView if some items;
3. Add Flexlayout into ItemTemplate;
4. Add label into flexlayout

### Link to public reproduction project repository

https://github.com/RobertoGFilho/MauiSamples

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Android All version, Windows 11, IOS last version

### Did you find any workaround?

if we set a heigth on label this problem dissapear

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on windows, iOS and android platform with sample project. [MauiSamples](https://github.com/RobertoGFilho/MauiSamples)
