### ISSUE TITLE
Images are not rendering in both iOS and Android

### ISSUE THREAD

**Issue by sam33r786** [dotnet/maui#12184]
### Description

I am attempting to use a CarouselView to show an Array of images using URLs stored alongside an entity but the doesn't show anything than an empty white square in both Android and iOS.

I have also added a standalone Image element with a hard-coded source to check if the issue was with my code or the framework but the issue remains.

>  
                <CarouselView ItemsSource="{Binding CurrentRecord.ImageUrls}" IndicatorView="indicatorView" HeightRequest="300">
                    <CarouselView.ItemTemplate>
                        <DataTemplate>
                            <Frame HasShadow="True"
                               BorderColor="DarkGray"
                               CornerRadius="5"
                               Margin="20"
                               HeightRequest="300"
                               HorizontalOptions="Center"
                               VerticalOptions="Center">
                                <Image Source="{Binding .}" 
                                   Aspect="AspectFill"
                                   HeightRequest="150"
                                   WidthRequest="150"
                                   VerticalOptions="Center"
                                   HorizontalOptions="Center" />

                            </Frame>

                        </DataTemplate>

                    </CarouselView.ItemTemplate>

                </CarouselView>
                <IndicatorView x:Name="indicatorView"
                       IndicatorsShape="Square"
                       IndicatorColor="LightGray"
                       SelectedIndicatorColor="DarkGray"
                       HorizontalOptions="Center"
                       Margin="0,0,0,40" />

                
                <Image Source="https://en.wikipedia.org/wiki/Visual_Studio#/media/File:Visual_Studio_2013_EN.png" HeightRequest="200" WidthRequest="200" MinimumHeightRequest="200" MinimumWidthRequest="200" />

### Steps to Reproduce

1. Create an Image element in XAML and either hard-code its source or attempt to bind source to view model.

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 16.2, Android 12

**Comment by 7702244** [comment]
I have the same problem, only on the emulator everything works, but when you run it on the device - a blank square.

**Comment by 7702244** [comment]
After several days of searching for solutions and experiments, I managed to find a solution to the problem. Add a datatype for the `<DataTemplate>` tag:
```
<CarouselView.ItemTemplate>
    <DataTemplate x:DataType="sys:String">
        <Image Source="{Binding .}"  />
     </DataTemplate>
</CarouselView.ItemTemplate>
```
and namespace: `xmlns:sys="clr-namespace:System;assembly=mscorlib"`.

Maybe an analyzer should be added, so that the Visual Studio warnings about this situation?

**Comment by sam33r786** [comment]
> After several days of searching for solutions and experiments, I managed to find a solution to the problem. Add a datatype for the `<DataTemplate>` tag:
> 
> ```
> 
> <CarouselView.ItemTemplate>
> 
>     <DataTemplate x:DataType="sys:String">
> 
>         <Image Source="{Binding .}"  />
> 
>      </DataTemplate>
> 
> </CarouselView.ItemTemplate>
> 
> ```
> 
> and namespace: `xmlns:sys="clr-namespace:System;assembly=mscorlib"`.
> 
> 
> 
> Maybe an analyzer should be added, so that the Visual Studio warnings about this situation?

Thanks for the workaround. I'll try and give that a go.

**Comment by sam33r786** [comment]
@7702244 I've tried your workaround and it doesn't seem to working for me for some reason.
