### ISSUE TITLE
Refreshing Observable Collection Generates InvalidOperationException

### ISSUE THREAD

**Issue by canperk** [dotnet/maui#12181]
### Description

Following code sample throws _VirtualView cannot be null here_
```

 public ObservableCollection<FinanceListDto> Items { get; set; }

public async Task InitAsync()
{
    Items.Clear();
    IsRefreshing = true;
    var result = await service.GetFinancialStream();
    foreach (var item in result)
    {
        Items.Add(item); // exception is thrown here
    }
    IsRefreshing = false;
}
```

### Steps to Reproduce

1. Create a XAML Project with MAUI
2. Add a page with a Collection view which was wrapped by a RefreshView
3. Use Components like below
```
 <RefreshView IsRefreshing="{Binding IsRefreshing}" Command="{Binding RefreshCommand}">
        <Grid>
            <CollectionView ItemsSource="{Binding Items}">
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                             <Label Text="{Binding Name}" />
                    </DataTemplate>                
               </CollectionView.ItemTemplate>
           </CollectionView>
       </Grid>
  </RefreshView>
```

4. Refreshing operation occurs exception

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

IOS 15+, Android 28+

**Comment by jsuarezruiz** [comment]
Could be related with https://github.com/dotnet/maui/issues/12219
