### ISSUE TITLE
RuntimeInformation.RuntimeIdentifier returns wrong version of Maccatalyst in Maui app.

### ISSUE THREAD

**Issue by julianadormon** [dotnet/maui#12198]
### Description

RuntimeInformation.RuntimeIdentifier returns "maccatalyst-x64" when run on an M1 processor.
It should return "maccatalyst-arm64", I would think?

### Steps to Reproduce

1. Create a Maui app that runs a MacCatalyst app.
2. Run the app in debug on a Mac with an M1 chip.
3. Call RuntimeInformation.RuntimeIdentifier.

![image](https://user-images.githubusercontent.com/89358714/208302269-04fa2f40-4f7f-4c91-ad42-466ef50a417d.png)

I added the code into a repository I used to report another bug, so don't be confused by the name please.

### Link to public reproduction project repository

https://github.com/julianadormon/FilePickerManyFilesBug.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacCatalyst 13

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
I think what @MartyIX says makes sense. Could you double-check in your Activity Monitor what the architecture is when running this .NET MAUI app? I suspect it's running emulated with Rosetta and that is why it reports like that. You'll have to create a native ARM build for it to show up right.

**Comment by julianadormon** [comment]
Thanks guys, I will try that and report back.
