### ISSUE TITLE
Entry control ClearButtonVisibility="WhileEditing" tap location moves

### ISSUE THREAD

**Issue by ideasdeployed** [dotnet/maui#12192]
### Description

If you have a Entry control inside another container (Frame or Grid, ect...) if you change the WidthRequest in either the Entry or any of the outer container, the Tap location for the ClearButtonVisibilyt moves to left, but the "X" stays in place. It actually moves approximately the same width to the left set by the WidthRequest in either of the containers.

```xaml
<Grid RowDefinitions="*" ColumnDefinitions="*"              
	Padding="12,2,12,2" WidthRequest="300">
	<Frame Grid.Column="0" Padding="0">
		<VerticalStackLayout Padding="14,0">
			<Entry Placeholder="Address"                   
				ClearButtonVisibility="WhileEditing"/>
		</VerticalStackLayout>
	</Frame>
</Grid>
```

### Steps to Reproduce

If you have a Entry control inside another container (Frame or Grid, ect...) if you change the WidthRequest in either the Entry or any of the outer container, the Tap location for the ClearButtonVisibilyt moves to left, but the "X" stays in place. It actually moves approximately the same width to the left set by the WidthRequest in either of the containers.

### Link to public reproduction project repository

https://github.com/ideasdeployed/BugReport

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up.

### Did you find any workaround?

Not yet.

**Comment by hartez** [comment]
This is fixed by #12753.
