### ISSUE TITLE
Some generated code falls foul of code analyzers.

### ISSUE THREAD

**Issue by RobTF** [dotnet/maui#12196]
### Description

Due to the fact that some generated code does not adhere to the standard naming convention of `.generated.cs`, tooling is picking it up as an issue. I've tried exceptioning it in my `.editorconfig` but to no avail.

![image](https://user-images.githubusercontent.com/4292237/208288852-e0fe0195-aead-4462-a576-06a8b69a3085.png)
 

### Steps to Reproduce

1. Create a new MAUI app.
2. Add NetAnalyzers and StyleCopAnalyzers packages.
3. Turn on rule CS1591
4. Build project.

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS (all), Android (all)

### Did you find any workaround?

I think there might be a way to work around this by using tricks in `.editorconfig` but so far nothing I've tried has worked.

### Relevant log output

```shell
5>C:\Repos\Vismo\playground\MauiPlay\MauiPlay\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Resources_Styles_Colors.xaml.sg.cs(17,23,17,45): error CS1591: Missing XML comment for publicly visible type or member '__TypeD0CFC899972F7471'
5>C:\Repos\Vismo\playground\MauiPlay\MauiPlay\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Resources_Styles_Colors.xaml.sg.cs(20,10,20,32): error CS1591: Missing XML comment for publicly visible type or member '__TypeD0CFC899972F7471.__TypeD0CFC899972F7471()'
5>C:\Repos\Vismo\playground\MauiPlay\MauiPlay\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Resources_Styles_Styles.xaml.sg.cs(17,23,17,45): error CS1591: Missing XML comment for publicly visible type or member '__TypeE776626181B1C0EF'
5>C:\Repos\Vismo\playground\MauiPlay\MauiPlay\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Resources_Styles_Styles.xaml.sg.cs(20,10,20,32): error CS1591: Missing XML comment for publicly visible type or member '__TypeE776626181B1C0EF.__TypeE776626181B1C0EF()'
```

**Comment by Youssef1313** [comment]
I don't think this is related to the naming of the file. The generated code should either suppress the warning with `#pragma warning disable` or add documentation comment to the public members.

I'm not sure though why suppression don't work in `.editorconfig`

**Comment by RobTF** [comment]
@Youssef1313 I agree the name is just one way of applying the *"ignore me, I'm generated"* marker. However I've seen this before, where other markers such as `///<autogenerated />` etc. are ignored. There was a similar problem with the Godot game engine and they were ultimately forced to use the `.generated.cs` suffix.

I think it's perhaps a bug with whatever chain generates the warnings, Roslyn, NetAnalyzers, StyleCop etc. when source generators are involved. It almost _feels_ like code files produced through generators somehow bypass some of the checks performed by these tools to weed out the files to be ignored.

**Comment by Youssef1313** [comment]
The compiler isn't supposed to ignore `/// <auto-generated>`.

**Comment by RobTF** [comment]
That was just a guess, I'm probably wrong as I haven't spent a lot of time looking into it.

The issue with just slapping on `#pragma warning disable` at the top of the file is one of semantics. Whilst it technically might work in suppressing the issue these code analysis tools are designed to be able to reason about what generated code is so they handle it appropriately. Therefore the problem isn't that the warnings pop up (that's a symptom), I think it's that the analysers simply don't understand that the affected files are auto-generated in the first place.

To be honest, your response doesn't surprise me as I think this whole area around code analysis is a little confusing (not a MAUI issue of course!) as taking that tag as an example, [others seem to think it should work](https://stackoverflow.com/questions/5027889/exclude-file-from-stylecop-analysis-auto-generated-tag-is-ignored), and [some tools downstream](https://shishkin.wordpress.com/2008/07/08/stylecop-how-to-ignore-generated-code/) from the compiler [do respect it](https://stackoverflow.com/questions/2701706/suppress-warning-for-generated-c-sharp-code).

Then you have competing configuration "standards" such as `.editorconfig` vs. `stylecop.json` vs. `SomeFile.ruleset` and the nuances of how they interact and which rules can be articulated in each, which tools respect what etc. etc.

**Comment by Youssef1313** [comment]
> I think it's that the analysers simply don't understand that the affected files are auto-generated in the first place.

This is not an analyzer. That is a compiler diagnostic.

**Comment by RobTF** [comment]
Consider me told ;) hopefully the overall point still makes sense.

**Comment by mattleibow** [comment]
@StephaneDelcroix Is there a thing we add into the generated files to tell the analyzers to ignore?

**Comment by mattleibow** [comment]
Note for future us:

> Step 2 should be "enable doc comments and enable warnings as errors". The analyzers are irrelevant.

**Comment by Youssef1313** [comment]
> @StephaneDelcroix Is there a thing we add into the generated files to tell the analyzers to ignore?

You can add a `#pragma warning disable CS1591` to the generated code. But better to actually produce a warning-free code and add doc comments IMO.

**Comment by pictos** [comment]
@mattleibow @StephaneDelcroix I believe you could add the `global::System.CodeDom.Compiler.GeneratedCode` attribute on generated members, that should help. The MVVM toolkit uses it, as you can see [here](
https://github.com/CommunityToolkit/dotnet/blob/main/src/CommunityToolkit.Mvvm.SourceGenerators/Input/RelayCommandGenerator.Execute.cs#L166)

**Comment by StephaneDelcroix** [comment]
> @StephaneDelcroix Is there a thing we add into the generated files to tell the analyzers to ignore?

We add a [GeneratedCode] attribute to the generated code ctor, and all the generated fields

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 5.0. Not repro on Android platform and can build successfully.

**Comment by DamianSuess** [comment]
Verified that this is still happening as well
* Visual Studio Enterprise 17.8.0
* .NET 7
