### ISSUE TITLE
Failure to install maui-ios and maui-android workload

### ISSUE THREAD

**Issue by BeepBeepBopBop** [dotnet/maui#12204]
Hi there, I am new to MAUI and I have recently upgraded to .NET 7.

Since that, a basic Maui App won't compile anymore; I get the following error message:

> Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-android, net7.0-ios, net7.0-maccatalyst

So I tried to install the workloads by running "workload install maui-ios maui-android" as suggested here https://github.com/dotnet/sdk/issues/28217

But the install systematically, fails. I had various error messages until now, and tried troubleshooting by searching several open issues here on github. I ended up uninstalling all the workloads and so when I type "workload list" I have none listed. 

The one error that I have now is:

> Workload installation failed: One or more errors occurred. (samsung.tizen.sdk.msi.x64::7.0.103 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-PullRequests/nuget/v3/index.json".)

dotnet --info output is the following:

> dotnet --info
> .NET SDK:
>  Version:   7.0.100
>  Commit:    e12b7af219
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22000
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\7.0.100\
> 
> Host:
>   Version:      7.0.0
>   Architecture: x64
>   Commit:       d099f075e4
> 
> .NET SDKs installed:
>   6.0.401 [C:\Program Files\dotnet\sdk]
>   7.0.100 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Other architectures found:
>   x86   [C:\Program Files (x86)\dotnet]
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found
> 
> Learn more:
>   https://aka.ms/dotnet/info
> 
> Download .NET:
>   https://aka.ms/dotnet/download

I have been struggling with this for several hours now and nothing seems to work, any insight would be much appreciated, thanks a lot...

**Comment by UkeHa** [comment]
Can you check with this tool https://github.com/Redth/dotnet-maui-check if everything necessary is installed?
