### ISSUE TITLE
[Windows] TapGestureRecognizer not working on Entry

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#12213]
### Description

TapGestureRecognizer not working on Entry on Windows.

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/dotnet-maui-testing-playground
2. Launch the App on Windows.
3. Navigate to the Entry tests.
4. Check the En41 test case.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/dotnet-maui-testing-playground

### Version with bug

7.0 (current)

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by jasonmsmith** [comment]
Just ran into this issue. Any estimate on when/whether it will be fixed?

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on windows platform with sample project.  

[/dotnet-maui-testing-playground](https://github.com/jsuarezruiz/dotnet-maui-testing-playground)

**Comment by alexKuchyk-godel** [comment]
Is there already a solution or workaround for this bug?
