### ISSUE TITLE
SetPadding for Entry does not work in .NET 7/MAUI 7 in Android

### ISSUE THREAD

**Issue by rentoulis** [dotnet/maui#12224]
### Description

If you create a new handler for an Entry in Android to set padding to zero, the padding of Entry does not change. That is true for .NET 7/Android 10. Works fine in .NET 6/Android 10.

### Steps to Reproduce

1. Create a new MAUI app.
2. Add an Entry.
3. Create handler to set padding to zero.

### Link to public reproduction project repository

https://github.com/rentoulis/MauiNet7Test.App.git

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

Android

### Affected platform versions

Android 10

**Comment by hartez** [comment]
As far as I can tell, the only customization you've made is this mapping change:

```
Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
{
#if ANDROID
	handler.PlatformView.SetPadding(0, 0, 0, 0);
#endif
});
```

You've told the property mapper to run this code after mapping the "MyCustomization" property. But the Entry mapper does not have a "MyCustomization" property, so that never happens. You'll need to add a mapping for that property to the EntryMapper, or append your customization to an existing property. Something like this:


```
Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("Placeholder", (handler, view) =>
{
#if ANDROID
	handler.PlatformView.SetPadding(0, 0, 0, 0);
#endif
});
```

**Comment by hartez** [comment]
@pedromcrocha I just realized that I was wrong about AppendToMapping - if the property does not exist, it will still create the mapping for it. So there's nothing wrong with your original code.

**Comment by hartez** [comment]
Okay, it's definitely not working on the latest stable, but it seems to be working with the latest on the main branch. So hopefully we can identify which commit broke it and which one fixed it.

**Comment by rmarinho** [comment]
@rentoulis is the repo project updated ?

**Comment by rentoulis** [comment]
@rmarinho No. It is not. For what reason?
