### ISSUE TITLE
Building in Release mode for Android results in a "The selected execution mode is not supported for .NET projects." error

### ISSUE THREAD

**Issue by Glorfindel83** [dotnet/maui#12226]
### Description

In Visual Studio for Mac, when building the .NET MAUI App template project in Release mode for an Android emulator, the build output and deploy window say the build is successful but the status bar shows an error

> Can not execute "..../bin/Release/net7.0-android/MyMAUIApp.dll". The selected execution mode is not supported for .NET projects.

and the application is not deployed.

<img width="717" alt="Screenshot 2022-12-20 at 12 33 24" src="https://user-images.githubusercontent.com/24611142/208658604-fa6face7-a6cf-4920-8a03-7b8411ff7d35.png">

Here are the [Visual Studio details](https://github.com/dotnet/maui/files/10267257/visual-studio-details.txt), the 
[build output](https://github.com/dotnet/maui/files/10268045/build-output.txt) and the 
[output of the Deploy to Device window](https://github.com/dotnet/maui/files/10268046/deploy-output.txt).

### Steps to Reproduce

1. Create a new project using the .NET MAUI App template. Target framework (.NET 7.0 or .NET 6.0) does not seem to make a a difference.
2. Select Release and choose an Android emulator
3. Click the Run button

This should build the app and deploy it to the emulator, but instead I get an error message.

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No.

**Comment by Glorfindel83** [comment]
This might be related to my other bug report from today: https://github.com/dotnet/maui/issues/12225

**Comment by rachelkang** [comment]
@jonathanpeppers any thoughts on this one?

**Comment by jonathanpeppers** [comment]
This looks like a VS Mac issue like Tim says: https://github.com/dotnet/maui/issues/12225#issuecomment-1359328002

To verify, you can run the app command line with:
```
dotnet build YourMauiApp.csproj -f net7.0-android -t:Run
```

If that works fine, then it's just VS Mac.

**Comment by Glorfindel83** [comment]
Thanks @jonathanpeppers, that works (though I do need to add `-c Release`, right?) I hope Microsoft will fix it along with the other report, which they've indicated will be in a future version.

**Comment by jonathanpeppers** [comment]
Yes if you want to select `Release`:
```
dotnet build --help
...
  -c, --configuration <CONFIGURATION>  The configuration to use for building the project. The default for most projects is 'Debug'.
  ```
