### ISSUE TITLE
ScrollView Content cannot scroll inside Grid 

### ISSUE THREAD

**Issue by omegazero2310** [dotnet/maui#12236]
### Description

When I put ScrollView inside Grid with 2 rows or more, Content inside ScrollView is fixed and cannot be scrolled (VerticalScrollBar is not visible indicating there is no more content to start scrolling, but there is more view to show)

### Steps to Reproduce

1. Create New MAUI Project
2. Inside MainPage.xaml , add a new Grid with properties: HorizontalOptions="FillAndExpand", RowDefinitions="80, Auto", VerticalOptions="FillAndExpand"
3. Add the first View with Grid.Row="0"
4. Add ScrollView with Grid.Row="1" and properties: HorizontalOptions="FillAndExpand", VerticalOptions="FillAndExpand"
5. Inside ScrollView add VerticalStackLayout 
6. Inside VerticalStackLayout add multiple Views to increase the content size to trigger scrolling 

### Link to public reproduction project repository

https://github.com/omegazero2310/MauiScrollViewBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

No

**Comment by hartez** [comment]
> RowDefinitions="80, Auto"

Change this to `RowDefinitions="80, *"`.
