### ISSUE TITLE
Key Property is not working at Visual Studio 2019. Preview 16.11

### ISSUE THREAD

**Issue by Markus1961** [dotnet/maui#1223]
I have compiled the Hello Maui app for Windows and the Key Property in Resourcedictionary at Color is not working

**Comment by Daniellled** [comment]
I think I am having the same issue. Can you provide more details as to what you are seeing and what you mean by "not working"?

**Comment by Markus1961** [comment]
I have solved the problem, i have not included the Http link for maui and not given the xmlns for Microsoft u as  i have done this and the example from github have reinstalled the problem was solvedi

**Comment by jfversluis** [comment]
The issue is not really clear to me here and it seems it also resolved itself. If there is still something not right, please open an issue with more details. Thanks!
