### ISSUE TITLE
Label control with TextType set to Html not able to change FontFamily

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#12230]
### Description

Related #11817 

Seeing on Mac that the font family has no impact on a Label with HTML. Android looks ok, though perhaps that's accidental b/c the font is close to what I expect (OpenSansRegular).

Note the block of text in the blog section. "Check out what's new" etc.

![Screenshot_1671551758](https://user-images.githubusercontent.com/41873/208710581-ab20b9e5-e3bc-455b-8c17-94ace4d2af66.png)

<img width="1281" alt="Screenshot 2022-12-20 at 9 57 02 AM" src="https://user-images.githubusercontent.com/41873/208710575-6eed310c-3591-4512-8a04-d9d2d261ae1a.png">

### Steps to Reproduce

```
<Label Text="{Binding Description}"
  Grid.Row="1"
  Padding="12,8"
  TextType="Html"/> 
```

Send html to that label and see how it renders when the label implicit style uses OpenSansRegular or similar. 

### Link to public reproduction project repository

https://github.com/davidortinau/ControlGallery/blob/main/src/ControlGallery/Pages/HomePage.xaml#L42

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

latest

**Comment by Mashedpoturtles** [comment]
Check fonts more closely because for me custom in general don't work at ALL on any mobile platform NOR windows...
