### ISSUE TITLE
Maui Drawer

### ISSUE THREAD

**Issue by raf10** [dotnet/maui#12240]
### Description

Please help me. with Maui Shell Menu
I Need a menu drawer like this
https://prnt.sc/8teVzIbDtLx6
https://prnt.sc/k7AnBUSZsG20

### Public API Changes

FlyoutSideDrawer.Transition = Transitions.Push
FLyout.Mode has two varitions expanded and partial expanded

### Intended Use-Case

In my app I need  to have this feature for comfortabel it users when they without opening full drawer , can navigate between pages

**Comment by angelru** [comment]
@raf10 
Try using blazor's menu drawer collapse.

**Comment by raf10** [comment]
how can I add it in MAUI

**Comment by angelru** [comment]
> how can I add it in MAUI?

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview?view=net-maui-7.0

https://mudblazor.com/components/drawer#mini-drawer-customization

**Comment by raf10** [comment]
I Need  to Add it in Mobile developing by MAUI but not with blazor.  are there another variant?

**Comment by pictos** [comment]
@raf10 you can control the Width and Height of Shell's Flyout, that way you can collapse and expand it as you need

**Comment by raf10** [comment]
> @raf10 you can control the Width and Height of Shell's Flyout, that way you can collapse and expand it as you need

Thank you , I've done now like that but in that case i can't use it for pushing the content while extending,, 
and the hamburger icon isn't shown when expanding menu

**Comment by pictos** [comment]
@raf10 can you share a video of those behaviors?
