### ISSUE TITLE
RadioButton does not fill its width in WinUI with ControlTemplate

### ISSUE THREAD

**Issue by shivagurunatha** [dotnet/maui#12241]
### Description

RadionButton ControlTemplate does not FillAndExpand[HorizontalOption] in WinUI. It works fine in Android and iOS.

### Steps to Reproduce

1. Run the attached sample in WinUI
2. You can see that RadioButton does not Expands horizontally

Android
![image](https://user-images.githubusercontent.com/80253119/208852188-f0141ac7-a3b9-41ec-a1b9-fae6a6de2603.png)

Windows
![image](https://user-images.githubusercontent.com/80253119/208852993-92a651a3-d3fe-4712-94b3-b0b82c8ad50a.png)

### Link to public reproduction project repository

https://github.com/shivagurunatha/Maui-WindowsRadioButtonIssue

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Windows

### Affected platform versions

10.0.19041.0

### Did you find any workaround?

No

**Comment by homeyf** [comment]
Verified this issue with 17.7.0 Preview 1.0. Not repro on windows platform with sample project.
https://github.com/shivagurunatha/Maui-WindowsRadioButtonIssue
![image](https://github.com/dotnet/maui/assets/82450723/fbdfdb6f-cef6-43d4-a6d5-e05a51543420)
