### ISSUE TITLE
"ResolvePackageDependenciesDesignTime" does not exist in the project

### ISSUE THREAD

**Issue by PavlovTM** [dotnet/maui#1224]
## HelloMauiWinUI3
I get the following error:

```
Error MSB4057 The target "ResolvePackageDependenciesDesignTime" does not exist in the project.
```

## Specs
Microsoft Visual Studio Community 2019
Version 16.10.1

.NET MAUI Check without problems

**Comment by jsuarezruiz** [comment]
Could again you try again updating to the latest .NET MAUI workloads and using latest Visual Studio 2022 Preview?. Some previews have been released with changes related to workloads, etc. I'm going to close the issue but if you still have problems let me know and we reopen this issue or feel free to open a new one.
