### ISSUE TITLE
I cannot access the Command Line arguments in Windows - MAUI

### ISSUE THREAD

**Issue by NirabhraDas013** [dotnet/maui#12246]
### Discussed in https://github.com/dotnet/maui/discussions/12193

<div type='discussions-op-text'>

<sup>Originally posted by **NirabhraDas013** December 18, 2022</sup>
Hi, I am new to MAUI and .NET programming in general and I am having a weird problem.

I am refactoring an existing Avalonia project to MAUI. The application depends on a Command Line Argument to decide which API to call which was working in Avalonia.

But in testing with MAUI, I am only getting the application dll name in the `Environment.GetCommandLineArgs()` call. 

Here is my debug profile:
![image](https://user-images.githubusercontent.com/54432376/208282051-3dc9962a-9b8d-4f42-8c65-717b6ebd95f6.png)

The code to get the Command Line Arguments:
![image](https://user-images.githubusercontent.com/54432376/208282059-4fa18ab9-36c3-49c2-8acb-9fd6b95d91eb.png)

The response to that code:
![image](https://user-images.githubusercontent.com/54432376/208282063-998ef767-2879-416f-b3f2-0223ce4b152f.png)

Also, to make sure there is no confusion, this is what I'm trying to run:
![image](https://user-images.githubusercontent.com/54432376/208282077-6c1ff768-0de4-40c0-bb1c-ba11958862be.png)

Could someone help me please? Let me know what I am doing wrong</div>

**Comment by jfversluis** [comment]
I think this is something that is more a WinUI issue than a .NET MAUI issue. A found this one here: https://github.com/microsoft/WindowsAppSDK/issues/1619 that points to here: https://github.com/microsoft/microsoft-ui-xaml/issues/3368

There are some suggestions given on how to make it still work.

As this is not really a (potential) issue in the .NET MAUI codebase, closing this one for now.
