### ISSUE TITLE
Navigation bar overlaps title bar when replacing MainPage for a MAUI 6.0 Windows App

### ISSUE THREAD

**Issue by JohnHunterACS** [dotnet/maui#12255]
### Description

This is in relation to https://github.com/dotnet/maui/issues/10710 being closed as fixed.  However, the bug is still present in MAUI 6.0, i.e. the LTS product.

Just to confirm that @PureWeen's fix for 7.0 is good, this only affects 6.0.

.Net 6 with splash page
![image](https://user-images.githubusercontent.com/93978222/208967982-4f813819-053d-4346-bd99-180586d66d3d.png)

.Net 7 with splash page
![image](https://user-images.githubusercontent.com/93978222/208968553-0296b2af-5c79-4d95-840d-330004bfc7b6.png)

### Steps to Reproduce

1. Create a new Default MAUI App using .Net 6.0
2. Add a new content page call SplashPage.xaml
3. In App.xaml.cs change the MainPage initialisation to `MainPage = new SplashPage();`
4. Add a Loaded event handler in SplashPage.xaml.cs
5. In the event handler reset the MainPage to be the default AppShell - `App.Current.MainPage = new AppShell();`

### Link to public reproduction project repository

https://dev.azure.com/JohnHunter0895/MauiBugs/_git/MauiBugs/branches?_a=all

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.22000.194

### Did you find any workaround?

Tried the same workaround used in https://github.com/dotnet/maui/issues/10710 but this results in spurious padding at the top of the flyout items

`Microsoft.Maui.Handlers.WindowHandler.Mapper.AppendToMapping(nameof(IWindow), (h, v) =>`
`        {`
`            (v.Handler.PlatformView as MauiWinUIWindow).ExtendsContentIntoTitleBar = false;`
`        });`

![Padding](https://user-images.githubusercontent.com/93978222/208968023-0cb084fe-9426-4d35-aeae-c9c1569dec10.jpg)

**Comment by PureWeen** [comment]
Interesting! Thank you for trying this out and letting us know. We'll definitely work on this for .NET8. Once we get that code finished, we'll see if we can backport or at least provide a workaround.

**Comment by JohnHunterACS** [comment]
@PureWeen I thought that .NET 6.0 being an LTS version, and the default version when creating a new MAUI project in VS2022, then it would also receive the fix?

**Comment by PureWeen** [comment]
@JohnHunterACS the default in VS2022 is .NET 7. Maybe it's remembering your previous choice? 

![image](https://user-images.githubusercontent.com/5375137/209875354-ae01f6d6-6771-4f85-84c1-74d8bea0451e.png)

LTS fixes are mainly going to be around security level issues. Bugs like this that are fixed by updating to .NET 7.0 most likely won't be back ported to .NET 6.0

**Comment by JohnHunterACS** [comment]
@PureWeen I've bumped all the projects in the solution up to .Net 7 but the Windows project wasn't happy about that and I ended up having to recreate the project from scratch and manually copy over all the changes from a backup.  At least I'm unblocked now.  Thanks.
