### ISSUE TITLE
Splash screen does not show when running in debugger

### ISSUE THREAD

**Issue by cdavidyoung** [dotnet/maui#12254]
### Description

I was struggling to get my splashscreen to show even though I followed the documentation and it seemed like it should be very easy.  Basically you just replace the splash.svg in the Resources\Splash folder and it should work.

What I finally discovered is that the splashscreen does show if you run the app by tapping on the icon.  For me, anyway, it never shows when I run the app in the debugger.

### Steps to Reproduce

You can do it with any app.  I just happened to be using

https://github.com/dotnet/maui-samples/tree/main/7.0/UserInterface/Views/Map/MapDemo

If you run this in the debugger the splashscreen is just a blank blue screen.  After installing it on a platform you can tap the icon and the .Net splashscreen appears.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/7.0/UserInterface/Views/Map/MapDemo

### Version with bug

7.0 (current)

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

iOS, Android

### Affected platform versions

I have tried iOS 15 and Android 12

### Did you find any workaround?

Not in the debugger.

**Comment by vhugogarcia** [comment]
Splash Screens have cache in the app. If you replaced the SVG image and set the proper settings in the .csproj file the image should be shown correctly. 

However, any change into the splash screen image or .csproj properties require for you to delete the app from simulators or device then delete bin & obj folders, close Visual Studio, open the project again and run the project again. The new splash screen should be there without issues.

**Comment by cdavidyoung** [comment]
This is good to know.  Thanks.  Rather than going to that much trouble I am now doing a Clean Solution and Rebuild Solution when I change the icon or splashscreen.  That seems to make the changes show up when I run by tapping the icon.  Now that I know that, I am not concerned that the splashscreen is not show up when running in the debugger.

**Comment by vhugogarcia** [comment]
> This is good to know.  Thanks.  Rather than going to that much trouble I am now doing a Clean Solution and Rebuild Solution when I change the icon or splashscreen.  That seems to make the changes show up when I run by tapping the icon.  Now that I know that, I am not concerned that the splashscreen is not show up when running in the debugger.

Glad it helped!! Feel free please to close the ticket if the issue has been solved 😄
