### ISSUE TITLE
Visual Studio Installer does not offer .NET Multi-platform App UI development workload

### ISSUE THREAD

**Issue by cpah** [dotnet/maui#12251]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am running Windows 11 (ARM) on a Mac Mini M1 (macOS 13.1) with Parallels Desktop for Mac 18. I have downloaded Visual Studio Community 2022 - 17.4.3. I want to install the  .NET Multi-platform App UI development workload but Visual Studio Installer does not offer this option.

**Comment by AathifMahir** [comment]
> Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
> Operating System: windows
> 
> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
> 
> I am running Windows 11 (ARM) on a Mac Mini M1 (macOS 13.1) with Parallels Desktop for Mac 18. I have downloaded Visual Studio Community 2022 - 17.4.3. I want to install the  .NET Multi-platform App UI development workload but Visual Studio Installer does not offer this option.

Hi @cpah 

DotNet Maui Workload for Windows on Arm (WOA) not supported yet on Visual Studio 2022 for ARM. I guess the Maui Team is Already working with the Visual Studio Team for Supporting the Workload, I hope it will be available very soon

**Comment by cpah** [comment]
Thanks for the very prompt reply. I guess I should use Visual Studio for Mac and just use my Windows VM for testing. Sent from my iPhoneOn 21 Dec 2022, at 15:36, AathifMahir ***@***.***> wrote:﻿

Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I am running Windows 11 (ARM) on a Mac Mini M1 (macOS 13.1) with Parallels Desktop for Mac 18. I have downloaded Visual Studio Community 2022 - 17.4.3. I want to install the  .NET Multi-platform App UI development workload but Visual Studio Installer does not offer this option.

Hi @cpah
DotNet Maui Workload for Windows on Arm (WOA) not supported yet on Visual Studio 2022 for ARM. I guess the Maui Team is Already working with the Visual Studio Team for Supporting the Workload, I hope it will be available very soon

**Comment by jfversluis** [comment]
Thanks for the help here @AathifMahir!

The ARM workloads are being worked on so hopefully they will be there soon!
