### ISSUE TITLE
(Un)SelectedTabColor do not work for TabbedPage icons (FontImageSource) on iOS

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#12250]
### Description

When using a font (FontImageSource) for tab icon, TabbedPage does not apply (Un)SelectedTabColor properties, on iOS.
However, the colors are properly applied to tab titles. 
Also, no issue when using an image (png) for the icon.
No issue on Android.

On this example, Tab1 uses an image, Tab2 uses a font:
![Screenshot_1671633286](https://user-images.githubusercontent.com/12516566/208932635-0e23d0f2-4d9a-4641-b89a-ec0f9e875363.png)

Similar issues:
https://github.com/dotnet/maui/issues/6043
https://github.com/dotnet/maui/issues/6718
https://github.com/xamarin/Xamarin.Forms/issues/8556

### Steps to Reproduce

1. Create a maui app, both for android and ios
2. Add a TabbedPage, and use either image or font for tab icons.
3. Set (Un)SelectedTabColor properties on TabbedPage
4. Observe colors, both on android and ios, both for image and font icons.

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppTabbedPageIconColor

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

Use an image instead of a font.

**Comment by JoacimWall** [comment]
Hi
My workaround for this adding this to the AppShell.Xml.cs

```
 protected override void OnNavigated(ShellNavigatedEventArgs args)
    {
        if (args.Source == ShellNavigationSource.ShellSectionChanged)
        {
            if (DeviceInfo.Platform != DevicePlatform.iOS)
                return;

            for (int i = 0; i < MyTabbar.Items.Count; i++)
            {
                var img = (FontImageSource)MyTabbar.Items[i].Icon;
                bool isCurrentPage = MyTabbar.CurrentItem.Title == MyTabbar.Items[i].Title ? true : false;
                MyTabbar.Items[i].Icon = new FontImageSource { Glyph = img.Glyph, FontFamily = img.FontFamily, Size = 20, Color = isCurrentPage ? AppColors.SignalBlueColor : AppColors.WhiteColor };

            }
        }
       
         base.OnNavigated(args);
    }
```

//Regards Joacim

**Comment by tranb3r** [comment]
That's not a shell issue. It's happening with TabbedPage.

**Comment by alanhoman** [comment]
I am having the exact same issue.  This is working properly in Xamarin but broken in Maui for iOS.

**Comment by BenderRodr1guez** [comment]
Quite the same issue.
Setup: tabbed page as the main app's page, each tab is a navigation page.
Next style doesn't work 
	<Style TargetType="TabbedPage">
		<Setter Property="BarBackgroundColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource Gray900}}" />
		<Setter Property="BarTextColor" Value="{AppThemeBinding Light={StaticResource Gray900}, Dark={StaticResource Gray200}}" />
		<Setter Property="UnselectedTabColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray900}}" />
		<Setter Property="SelectedTabColor" Value="{AppThemeBinding Light={StaticResource Gray900}, Dark={StaticResource Gray200}}" />
	</Style>

but, I see that all those properties have default values (just override property changed method, for ex.).
So, I assigned colors directly in the xaml of the tabbed page and oh my goodness, it's works.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on iOS platform with sample project.
[Issues-main.zip](https://github.com/dotnet/maui/files/11998761/Issues-main.zip)
![Screenshot 2023-07-10 145920](https://github.com/dotnet/maui/assets/77434865/5153f9ff-049f-4786-93d1-8003e86cb920)

**Comment by Yves-Be** [comment]
I came up with this elegant solution for the TabbedPage.

```C#
public class CustomTabbedPage : TabbedPage
{
    protected override void OnPagesChanged(NotifyCollectionChangedEventArgs e)
    {
        base.OnPagesChanged(e);

        if (e.Action == NotifyCollectionChangedAction.Add)
        {
            foreach (var page in e.NewItems.OfType<Page>())
            {
                FixSelectedIconColoriOS(page);
            }
        }
    }

    protected void FixSelectedIconColoriOS(Page page)
    {
        if (DeviceInfo.Platform == DevicePlatform.iOS && page.IconImageSource is FontImageSource fontImageSource)
        {
            page.IconImageSource = new FontImageSource()
            {
                Glyph = fontImageSource.Glyph,
                FontFamily = fontImageSource.FontFamily,
                Size = fontImageSource.Size,
                Color = UnselectedTabColor
            };
            var selectedPageStyle = new Style(typeof(Page)) { ApplyToDerivedTypes = true };
            selectedPageStyle.Triggers.Add(new DataTrigger(typeof(Page))
            {
                Binding = new Binding(nameof(CurrentPage), source: this),
                Value = page,
                Setters = {{
                Page.IconImageSourceProperty,
                    new FontImageSource()
                    {
                        Glyph = fontImageSource.Glyph,
                        FontFamily = fontImageSource.FontFamily,
                        Size = fontImageSource.Size,
                        Color = SelectedTabColor
                    }
                }}
            });
            page.Style = selectedPageStyle;
        }
    }
}
```

**Comment by juniorsaraviao** [comment]
Still an issue using Net-MAUI 8.0.100 on iOS

<img src="https://github.com/dotnet/maui/assets/43689290/bfe86594-ad0d-4fbb-8c4e-d4c8ba0d7c32" width="500" height="150">

**Comment by codercampos** [comment]
> I came up with this elegant solution for the TabbedPage.
> 
> ```cs
> public class CustomTabbedPage : TabbedPage
> {
>     protected override void OnPagesChanged(NotifyCollectionChangedEventArgs e)
>     {
>         base.OnPagesChanged(e);
> 
>         if (e.Action == NotifyCollectionChangedAction.Add)
>         {
>             foreach (var page in e.NewItems.OfType<Page>())
>             {
>                 FixSelectedIconColoriOS(page);
>             }
>         }
>     }
> 
>     protected void FixSelectedIconColoriOS(Page page)
>     {
>         if (DeviceInfo.Platform == DevicePlatform.iOS && page.IconImageSource is FontImageSource fontImageSource)
>         {
>             page.IconImageSource = new FontImageSource()
>             {
>                 Glyph = fontImageSource.Glyph,
>                 FontFamily = fontImageSource.FontFamily,
>                 Size = fontImageSource.Size,
>                 Color = UnselectedTabColor
>             };
>             var selectedPageStyle = new Style(typeof(Page)) { ApplyToDerivedTypes = true };
>             selectedPageStyle.Triggers.Add(new DataTrigger(typeof(Page))
>             {
>                 Binding = new Binding(nameof(CurrentPage), source: this),
>                 Value = page,
>                 Setters = {{
>                 Page.IconImageSourceProperty,
>                     new FontImageSource()
>                     {
>                         Glyph = fontImageSource.Glyph,
>                         FontFamily = fontImageSource.FontFamily,
>                         Size = fontImageSource.Size,
>                         Color = SelectedTabColor
>                     }
>                 }}
>             });
>             page.Style = selectedPageStyle;
>         }
>     }
> }
> ```

Unfortunately, this only fixes the Selected/Unselected color for the icon, but the text keeps being the system's default.

![image](https://github.com/dotnet/maui/assets/8483978/9c9115ba-f255-4766-849f-fd0ac0dcdf90)

**Comment by JohnTraDolta** [comment]
As a workaround you can implement a CustomHandler and paint the imagesource  yourself as such:
``` csharp
public class ShellTabBar : ShellTabBarAppearanceTracker
{
    public override void SetAppearance(UITabBarController controller, ShellAppearance appearance)
    {
        var unselectedColor = appearance.TabBarUnselectedColor.ToPlatform();
        var selectedColor = appearance.TabBarTitleColor.ToPlatform();
        
        for (var i = 0; i < controller.TabBar.Items?.Length; i++)
        {
            var uiImage = controller.TabBar.Items[i].Image;
            

            var unselectedImage = uiImage.ApplyTintColor(unselectedColor , UIImageRenderingMode.AlwaysTemplate);
            var selectedImage = uiImage.ApplyTintColor(selectedColor, UIImageRenderingMode.AlwaysOriginal);
            controller.TabBar.Items[i].SetFinishedImages(selectedImage, unselectedImage);

        }

        base.SetAppearance(controller, appearance);
        
    }
}
class CustomShellHandler : ShellRenderer
{
    protected override IShellTabBarAppearanceTracker CreateTabBarAppearanceTracker()
    {
        return new ShellTabBar();
    }
}
```
