### ISSUE TITLE
Is there a way how we could create apps for Windows Phone with maui (The Lumia ones)?

### ISSUE THREAD

**Issue by snehccurry** [dotnet/maui#12270]
### Description

Is there a way how we could create apps for Windows Phone with maui (The Lumia ones)?

### Public API Changes

Is there a way how we could create apps for Windows Phone with maui (The Lumia ones)?

### Intended Use-Case

Is there a way how we could create apps for Windows Phone with maui (The Lumia ones)?

**Comment by drasticactions** [comment]
No
