### ISSUE TITLE
[Android,Windows]When the parent's IsEnabled Property is set to false, the touch of the child is getting triggered.

### ISSUE THREAD

**Issue by RiyashameedM** [dotnet/maui#12278]
### Description

I created a stacklayout and changed the value of the isEnabled property to false. As a child of the stacklayout, I've added a button inside the stacklayout.After clicking the button the button clicked event is getting triggered.touch interaction should not occur for the child if the parent's element is set to isEnabled to false.

### Steps to Reproduce

1.Run sample. 
2.Click the button. 
Observed behavior-> after clicking the button,button clicked event will be trigerred.

### Link to public reproduction project repository

[SimpleSample.zip](https://github.com/dotnet/maui/files/10292329/SimpleSample.zip)

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Android, Windows

### Affected platform versions

all platforms

### Did you find any workaround?

I have set inputTransparent property to true to resolve the issue.

**Comment by pwisk** [comment]
I noticed the same behaviour for Grid. This issue is present from a long time now.

**Comment by acaliaro** [comment]
Is this a bug or is it intentional? What is the use of the IsEnabled property in a layout?

**Comment by rachelkang** [comment]
Hi, @RiyashameedM - this should be fixed in the upcoming .NET 8 release, as per https://github.com/dotnet/maui/pull/12488! Feel free to reopen if you continue to have issues
