### ISSUE TITLE
Request to add function to Microsoft.Maui.Handlers.EntryHandler.

### ISSUE THREAD

**Issue by pulmuone** [dotnet/maui#12276]
### Description

I need to use CommandMapper in Microsoft.Maui.Handlers.EntryHandler, there is only IPropertyMapper. CommandMapper is necessary because IPropertyMapper will not be called unless the value changes.

### Public API Changes

Microsoft.Maui.Handlers.EntryHandler.

as-is
public EntryHandler(IPropertyMapper? mapper = null);

to-be
public EntryHandler(IPropertyMapper? mapper = null, CommandMapper? commandMapper = null);

### Intended Use-Case

I am trying to make a CustomEntry by inheriting Entry and create a function that shows/hides the SoftKeyboard when the user clicks a command button, but the value of the Handler's PropertyMapper is not changed and is not called.
I would like to be able to use all PropertyMapper/CommandMapper like ViewHandler.

**Comment by jstedfast** [comment]
This seems to have been added unless I'm not understanding something correctly(?).

Looks like @mattleibow added this .ctor 235 days ago:

```csharp
public EntryHandler(IPropertyMapper? mapper, CommandMapper? commandMapper)
```
