### ISSUE TITLE
CarouselView IsSwipeEnabled="False" still scrolls with tab navigation

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#12272]
### Description

On Android, even using `IsSwipeEnabled="False"` on a CarouselView, it is still possible to 'tab' through to the next item, causing the next item to scroll into view.

It looks like the RecyclerView layout manager we use will need to toggle enabling scroll on/off, or perhaps we need to look at the focusable properties of items and disable focus so they cannot be navigated to that way.

https://user-images.githubusercontent.com/271950/209175194-9204a7d0-f25d-498a-aecd-3bf2a35facff.mp4

### Steps to Reproduce

See attached repro, run it on android, tab through the items and observe the unintended scrolling between items via focus changes.

### Link to public reproduction project repository

https://github.com/Redth/MauiIssueRepros/tree/main/CarouselView/CarouselViewDisableSwipe12272

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 31, did not test others

**Comment by gabsamples6** [comment]
@Redth  I wanted to use the carousel view for a wizard but given this bug its pretty unusable!!
This is such a core control ! Any workarounds would be appreciated. Will this bug ever be fixed?

thanks in advance for any reply

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on android platform with above project.
[CarouselViewDisableSwipe12272](https://github.com/Redth/MauiIssueRepros/tree/main/CarouselView/CarouselViewDisableSwipe12272)

**Comment by Redth** [comment]
Works fine in net9 :)
