### ISSUE TITLE
HotReload doesn't work on .Net7 when targeting Windows (it seems to work on Android)

### ISSUE THREAD

**Issue by marcojak** [dotnet/maui#12274]
### Description

I'm trying to use Hot Reload with a .net 7 project but it doesn't work on Windows (it works on Android. not sure about iOS)
In the Hot Reload log windows, it says "Starting session" but nothing else after it.

Everything works fine with a .net 6 project.

### Steps to Reproduce

Create a new .Net 6 MAUI app.
Try Hot Reload. It works.
Replace .Net 6 with .Net 7.
Clean and rebuild the project (This is important, otherwise it still works somehow)
Now hot reload doesn't work anymore.

### Link to public reproduction project repository

https://github.com/marcojak/TestHotReload

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

Use .Net6, but for me it's not possible as some plugins are not compatible.

**Comment by SonOfKorriban** [comment]
It does not even work with .Net6. 
Debugging on Android is possible with working Hot Reload, but not on Windows.
