### ISSUE TITLE
iOS: content page is showing flyout menu icon when back button is set to false in flyout pages app

### ISSUE THREAD

**Issue by kirankumar4vr** [dotnet/maui#12289]
### Description

In a flyout pages app, when the back button is set to false for a navigation page using the below line
`NavigationPage.SetHasBackButton(this, false); `
page is showing the flyout menu icon on iOS. if the above line is not set, page top bar simply shows a back button as expected.
However, on Android, it is working as expected.
Android screenshot
https://raw.githubusercontent.com/kirankumar4vr/FlyoutPages/main/Images/Android.png

iOS screenshot
https://raw.githubusercontent.com/kirankumar4vr/FlyoutPages/main/Images/iOS.png

### Steps to Reproduce

1. clone the git repo
2. run the app on both android and iOS
3. push the content page by clicking the 'Click Me!' button

### Link to public reproduction project repository

https://github.com/kirankumar4vr/FlyoutPages

### Version with bug

7.0 Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 14+

### Did you find any workaround?

NA

**Comment by lizharems** [comment]
On iOS Right now based on your example it looks like this is working as intended. If you hide the back button on Navigation Page with a flyout we have logic to handle if it should show the flyout button or the back button. In your example it is showing a flyout button and the custom button you added to the navigation title.

If you are interested in implementing custom logic for displaying the default toolbar buttons I suggest overriding ShouldShowToolbarButton() as part of the FlyoutPage and implement your logic from there.
