### ISSUE TITLE
WebView do not ask permissions for Video and Mic

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/maui#12283]
### Description

WebView decline permissions for video and microphone access in .net7

this is not working for .NET7
https://github.com/MackinnonBuck/MauiBlazorPermissionsExample

### Steps to Reproduce

Try to start video call, and you neverver recive request for permission

### Link to public reproduction project repository

https://github.com/MackinnonBuck/MauiBlazorPermissionsExample

### Version with bug

7.0 (current)

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

iOS, Android

### Affected platform versions

IOS, Android

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck can you please see if your sample should be updated for .NET 7?

**Comment by KSemenenko** [comment]
Also I found that on iOS webviee can request permission for video and mic.
But It not for android.

To test it, try to open zoom or Google meets link in webview

**Comment by MackinnonBuck** [comment]
I tried running the sample on .NET 7 and it works for me on Windows and Android (I can test on Mac again next time I get the chance).

@KSemenenko, I saw your screenshot posted in https://github.com/MackinnonBuck/MauiBlazorPermissionsExample/issues/4. The dialog might not be showing up because the permission was previously denied. You can go to the settings app and change the location permissions for the app to "Ask every time", and the dialog should show up:
![image](https://user-images.githubusercontent.com/10456961/210663982-020ea766-90a0-4304-89d7-b00497419b13.png)

**Comment by MackinnonBuck** [comment]
I just noticed you called out the video and microphone permissions specifically. I tried those too and they both worked on .NET 7 for me. The suggestion in my previous comment applies for those permissions as well.

**Comment by KSemenenko** [comment]
I have update here, so https://github.com/MackinnonBuck/MauiBlazorPermissionsExample/ works fine.

But just WebView from Maui is not ask permissions on Android for mic and video.

What I did, I create custom Handler and use this code
https://github.com/MackinnonBuck/MauiBlazorPermissionsExample/blob/1cc5e26fb8753f0a73bb113edfd04ebcb5112e13/MauiBlazorPermissionsExample/MainPage.xaml.Android.cs

PermissionManagingBlazorWebChromeClient:
https://github.com/MackinnonBuck/MauiBlazorPermissionsExample/blob/1cc5e26fb8753f0a73bb113edfd04ebcb5112e13/MauiBlazorPermissionsExample/Platforms/Android/PermissionManagingBlazorWebChromeClient.cs

``` cs
public sealed partial class CustomWebViewHandler
{
    protected override WebView CreatePlatformView()
    {
        var webview = base.CreatePlatformView();
        
        if (webview.Context?.GetActivity() is not ComponentActivity activity)
        {
            throw new InvalidOperationException($"The permission-managing WebChromeClient requires that the current activity be a '{nameof(ComponentActivity)}'.");
        }
        
        webview.Settings.JavaScriptEnabled = true;
        webview.Settings.AllowFileAccess = true;
        webview.Settings.MediaPlaybackRequiresUserGesture = false;
        //webview.ClearCache(true);
        webview.Settings.SetGeolocationEnabled(true);
        webview.Settings.SetGeolocationDatabasePath(webview.Context?.FilesDir?.Path);
        webview.SetWebChromeClient(new PermissionManagingBlazorWebChromeClient(webview.WebChromeClient!, activity));
        
        return webview;

    }
}
```
and method  ```cs  private void RequestPermission(string permission, Action<bool> callback) ``` never called, so looks like android webview do not even try to ask permission, it's looks like it disabled from begining.

**Comment by adegeo** [comment]
Hi @KSemenenko I was messing around with this and I think what is happening is some handler or something is running **after** your handler which then calls **SetWebChromeClient** and sets it with the default. So I think you're right, there is something bad going on in the backend.

At the time of permission request, I was able to still set it directly and avoid it. However, it would be better to be able to set it via the handler mapping..!

```csharp
private async void ContentPage_Loaded(object sender, EventArgs e)
{
	PermissionStatus status = await Permissions.CheckStatusAsync<Permissions.Camera>();

	if (status != PermissionStatus.Granted)
	{
		if (Permissions.ShouldShowRationale<Permissions.Camera>()) { }

		await Permissions.RequestAsync<Permissions.Camera>();

#if ANDROID
        ((IWebViewHandler)webviewcontrol.Handler).PlatformView.SetWebChromeClient(new MyWebChromeClient());
#endif
    }
}
```

**Comment by adegeo** [comment]
@KSemenenko OK I did a lot more playing around, including looking at the .NET MAUI source code to figure out how they're doing chrome object and I discovered they have a property mapper set explicitly for that property. You simply need to overwrite it with the same name as the property that, in the end, gets set (which is **WebChromeClient**).

```csharp
private void CustomizeWebViewHandler()
{
    Microsoft.Maui.Handlers.WebViewHandler.Mapper.Add("WebChromeClient", (handler, view) =>
    {
#if ANDROID
        handler.PlatformView.SetWebChromeClient(new MyWebChromeClient());
#elif WINDOWS
#elif IOS
#endif
    });
}
```
Call this method when your page constructor is running or at the start of the program itself.

The `MyWebChromeClient` class in the Android folder:
```csharp
using Android.Webkit;

namespace MauiAppWebViewHandlers.Platforms.Android
{
    internal class MyWebChromeClient: WebChromeClient
    {
        public override void OnPermissionRequest(PermissionRequest request)
        {

            foreach (var resource in request.GetResources())
            {
                if (resource.Equals(PermissionRequest.ResourceVideoCapture, StringComparison.OrdinalIgnoreCase))
                {
                    request.Grant(request.GetResources());
                    return;
                }
            }

            base.OnPermissionRequest(request);
        }
    }
}
```

**Comment by KSemenenko** [comment]
@adegeo thanks for your investigation. This was relay hard for me. Thanks a lot!
And I think this is good idea to add it in maui to have identical behavior between platforms

**Comment by adegeo** [comment]
@KSemenenko You're welcome. Also, technically, you don't have to use a handler. You can set your custom chrome client with reference to the control itself. For example, this sets the `webviewcontrol` named control when the page is loaded:

```csharp
private async void ContentPage_Loaded(object sender, EventArgs e)
{
    PermissionStatus status = await Permissions.CheckStatusAsync<Permissions.Camera>();

    if (status != PermissionStatus.Granted)
    {
        if (Permissions.ShouldShowRationale<Permissions.Camera>()) { }

        await Permissions.RequestAsync<Permissions.Camera>();
    }

#if ANDROID
    ((IWebViewHandler)webviewcontrol.Handler).PlatformView.SetWebChromeClient(new MyWebChromeClient());
#endif
}
```

**Comment by KSemenenko** [comment]
@adegeo  wow, this is so cool! thans a lot!

**Comment by MackinnonBuck** [comment]
It sounds like this has been answered - closing this out now.
