### ISSUE TITLE
Width/Text rendering on Android Button with ImageSource when ContentLayout set to Top

### ISSUE THREAD

**Issue by simpsoc** [dotnet/maui#12288]
### Description

Android buttons with an ImageSource set and ContentType of Top do not render properly(width and text alignment).

![androidtop](https://user-images.githubusercontent.com/115647689/209358112-044156f8-5698-4431-a1ad-d28170c46f4d.png)

If you make any changes to any setting the button re-renders correctly, but as soon as you close and reopen the issue comes back.  In my example I changed text to CLICK m, but the same happens if you change padding, margin, horizontaloptions, verticaloptions and others.

![androidremovem](https://user-images.githubusercontent.com/115647689/209359403-2d317e63-a111-4a87-b3a7-37625dd8a36f.png)

Clicking the button increases the count with re-renders the button correctly.

![afterclick](https://user-images.githubusercontent.com/115647689/209360063-6c030b41-cdd1-4153-b6aa-cd12afd8d1ec.png)

If you change ContentType to Bottom and run in debug the button renders correctly.

![androidbottom](https://user-images.githubusercontent.com/115647689/209358120-1dfe6480-afb7-4b15-b79d-54792ccae870.png)

If you run in iOS the button renders properly with either the top or bottom setting.

![iOStop](https://user-images.githubusercontent.com/115647689/209358950-8458a6cb-934b-46c9-8147-5c5f18e73634.png)
![iOSbottom](https://user-images.githubusercontent.com/115647689/209358952-8f830192-7d7b-49b0-88b2-e67aa61c4bd9.png)

### Steps to Reproduce

1. Create a new maui app from the template.
2. Add a 72x72 png image(android_icon.png) was the first i found with a google search.
3. Add the following 3 lines of code to CounterBtn:

HeightRequest="150"
ImageSource="android_icon.png"
ContentLayout="Top"

4. Run on android.

### Link to public reproduction project repository

https://github.com/simpsoc/buttonlayouttest.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android api 33

### Did you find any workaround?

For now I have set the buttons to render the way I want on iOS and the way that works on Android:

ContentLayout="{OnPlatform Default='Top', Android='Bottom'}"

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Android platform with above project.
https://github.com/simpsoc/buttonlayouttest.git
![image](https://github.com/dotnet/maui/assets/82450723/d1649ebd-ade5-411d-a70d-c9490efb4427)

**Comment by davidortinau** [comment]
net8 preview 6 this all seems to render correctly (at least as far as alignment) on initial run and after clicking, with both Top and Bottom options. Tested on android API 33 and iOS 16.4.

![Simulator Screenshot - iPhone 14 Pro - 2023-07-06 at 15 33 58](https://github.com/dotnet/maui/assets/41873/7e512b18-b64f-4f53-9d8a-cd5be66a0399)
![Simulator Screenshot - iPhone 14 Pro - 2023-07-06 at 15 33 18](https://github.com/dotnet/maui/assets/41873/a6e41d14-a1ab-418f-acfb-5a41feac4a07)
![Screenshot_1688675487](https://github.com/dotnet/maui/assets/41873/3e35f3af-de2e-4b11-b314-8b423fcdc00c)
![Screenshot_1688675446](https://github.com/dotnet/maui/assets/41873/1077a66d-68fe-495d-ad25-2fbb0a91a884)
