### ISSUE TITLE
Permission for Notifications

### ISSUE THREAD

**Issue by TonyLugg** [dotnet/maui#12291]
### Description

Android 13 has a new permission POST_NOTIFICATIONS.  Notifications are turned off by default after installing the app in Android 13.  There is no automatic prompt to allow notifications.  We must manually request permission to send notifications.

Please add this to the Permissions in MAUI.

### Public API Changes

Permissions.Notifications

### Intended Use-Case

It is required to allow an app to send notifications in Android 13+

**Comment by norton287** [comment]
@TonyLugg See my proposal here #11476

**Comment by vhugogarcia** [comment]
You can add the permission directly in the Android's manifest file at the following path: /Platforms/Android/

```xml
<manifest ...>
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
    <application ...>
        ...
    </application>
</manifest>
```

Just make sure your project compiles against Android SDK 33 (v13)

**Comment by TonyLugg** [comment]
@vhugogarcia Yes, I've done that.  But my point was that Android 13 no longer puts up a prompt to the user to enable the permission.  You have to do it manually.  I resolved it with this code in MainActivity:

```        // Ask for permission to send notifications (required by API 33+)
        if (ContextCompat.CheckSelfPermission(this, Manifest.Permission.PostNotifications) != Permission.Granted)
        {
            ActivityCompat.RequestPermissions(this, new[] { Manifest.Permission.PostNotifications }, 0);
        }```

**Comment by TonyLugg** [comment]
Yes, I posted my work around on your issue.

Tony Lugg
C-TAP Corp.
Tel: 780-481-9017 ext: 101
Cel: 780-991-3526
www.ctapcorp.com<https://www.ctapcorp.com/>
www.vdis.com<https://www.vdis.com/>

Microsoft Certified Partner

**Comment by jfversluis** [comment]
Yep great proposal, thank you! We also have #12264 about Bluetooth and actually a part of the implementation for this was done for Xamarin.Essentials: https://github.com/xamarin/Essentials/pull/2063

We need to make a little inventory of the new things we need to add here and get it done. In the meantime, the Permissions APIs are very extensible so if you need something right now, you might want to look into that: https://learn.microsoft.com/dotnet/maui/platform-integration/appmodel/permissions?view=net-maui-7.0&tabs=android#extending-permissions

**Comment by KSemenenko** [comment]
this is good one

**Comment by moljac** [comment]
Repro sample + Notes 

[Sample.Issue_12291.PostNotifications.zip](https://github.com/dotnet/maui/files/11193801/Sample.Issue_12291.PostNotifications.zip)



*   https://github.com/dotnet/maui/issues/12291

    *   related:

        *   https://github.com/dotnet/maui/issues/11476

PR https://github.com/dotnet/maui/pull/14456

To enable notifications and to build added:

```xml
	<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
	<uses-sdk
			android:minSdkVersion="21"
			android:targetSdkVersion="33"
            />
```

Works on API 31 and API32 

API 33 log message (no error/exception):

```
[com.companyname.sample.issue_12291.postnotifications] Show: Notifications are disabled
```

TODO:

* Refine sample

**Comment by adrynalyne** [comment]
I find it disturbing this was put on a backlog when Google made clear their August 31, 2023 deadline for Android application to target Api 33. Yet, this was not considered to be added to .NET7?

**Comment by tranb3r** [comment]
@samhouts @moljac
Any update?

**Comment by r-work** [comment]
Another basic thing that has been reported for about a year, someone already made a [PR](https://github.com/dotnet/maui/pull/14456), and still nothing.
Ridiculous!
