### ISSUE TITLE
[iOS] Debug / Deploy is broken when specifying custom build configuration

### ISSUE THREAD

**Issue by DoubleDBE** [dotnet/maui#12299]
### Description

When you create a new build configuration in VS, debugging (and deploying?) is broken on iOS.

The app somehow gets deployed to the simulator, but you'll notice no output is being written to the output window.

Breakpoints are also not hit.

I have tested this with Xamarin.Forms and there it works, so I presume it's a MAUI thing.

Also, when you press the stop button in VS, the IDE hangs untill you close the simulator.

### Steps to Reproduce

1. Create a new .NET MAUI app.
2. Create a new Build Configuration (either solution wide or only on the project, doesn't make a difference).

![image](https://user-images.githubusercontent.com/45478482/209519970-4a443c05-8509-4346-8ccd-a24473f2e4ac.png)

4. Start debugging to a simulator

### Link to public reproduction project repository

https://github.com/DoubleDBE/MauiBuildConfigurationBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1, probably earlier versions too

### Did you find any workaround?

Please let me know if anyone knows a workaround!

**Comment by rachelkang** [comment]
This issue was moved to xamarin/xamarin-macios#17567
