### ISSUE TITLE
build fails if xaml is in Platform/Windows folder

### ISSUE THREAD

**Issue by adiamante** [dotnet/maui#12306]
### Description

When a xaml file exists in the Platforms/Windows folder, the build fails.

### Steps to Reproduce

1. Create an empty MAUI App
2. Create a .NET MAUI ContentPage xaml file under Platforms/Windows folder
3. Build fails with the following message for the xaml file
`Error CS0103 The name 'InitializeComponent' does not exist in the current context	TestMaui (net7.0-windows10.0.19041.0)`

### Link to public reproduction project repository

https://github.com/adiamante/Testmaui

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

Placing xaml files in folders other than Platforms/Windows.

\* Edit

Moving xaml files was not enough. To provide some context, my end goal was to have platform specific xaml. I would get windows working then break android and vice versa. I ended up with a xaml.cs page outside Platforms folder, xaml file in Platforms/Android and xaml field in Platforms/WindowsViews (Platform/Windows would result in error). In addition, I had to the following configuration in .csproj to build in both windows and android

```
  <ItemGroup Condition="$(TargetFramework.StartsWith('net7.0-android')) != true">
    <MauiXaml Remove="**\Android\**\*.xaml" />
    <Compile Remove="**\Android\**\*.xaml.cs" />
    <None Include="**\Android\**\*.xaml.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.Contains('-windows')) != true">
    <MauiXaml Remove="**\WindowsViews\**\*.xaml" />
    <Compile Remove="**\WindowsViews\**\*.xaml.cs" />
    <None Include="**\WindowsViews\**\*.xaml.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
  </ItemGroup>
```

Using this workaround, the WindowsViews folder disappers from Solution Explorer.  Visual Studio doesn't seem to be detecting the TargetFramework well in the Solution Explorer

### Relevant log output

```shell
Error	XLS0414	The type 'TestMaui.Platforms.Windows.NewPage1' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.
The name 'InitializeComponent' does not exist in the current context
```

**Comment by rachelkang** [comment]
Hi, @adiamante - any code you include in the Platform/Windows folder should be specific to the Windows platform, and not the cross-platform .NET MAUI APIs. Is there a reason you wanted to have the MAUI code at that location?

**Comment by adiamante** [comment]
@rachelkang I am not attempting to have cross platform code in the Platform folder. In the workaround I was trying to share the xaml.cs and have platform specific xaml. I understand that the the Platform specific code is supposed to be specific to the platform. However, when I try to have any xaml code under Platform/Windows for a Windows specific view, it fails to build.
