### ISSUE TITLE
[regression/7.0.0] Building a NuGet package from .NET MAUI Class Library with Source Link results in the error described.

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#12309]
### Description

Building a NuGet package from .NET MAUI Class Library with Source Link enabled results in the below error while validating the package.

* Some PDB's checksums do not match their PE files and are shown as missing.

And when the symbol package is pushed to the NuGet repository, the publish fails with the error message:

* The checksum does not match for the DLL(s) and corresponding PDB(s).

Seems some issue with the source-generated files.

### Steps to Reproduce

1. Create a new .NET MAUI class library project
2. Add a reference to the source link NuGet package `Microsoft.SourceLink.GitHub`
3. Add some content, a valid Page/View, to the project
4. Build the project, make use of the command provided below
5. Validate the generated NuGet package with the Package Validator tool (which can be installed with the command provided)

```shell
dotnet new mauilib -o TestLib
```
```shell
dotnet add package Microsoft.SourceLink.GitHub
```
```
dotnet build -c Release -p:GeneratePackageOnBuild=true -p:PublishReadyToRun=false -p:EmbedUntrackedSources=true -p:ContinuousIntegrationBuild=true -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
```
Install the package validator tool
```shell
dotnet tool install --global dotnet-validate --version 0.0.1-preview.304
```
Validate the package - Ensure the context is in the `bin\Release` folder for this to work
```shell
dotnet-validate package local TestLib.1.0.0.nupkg
```

### Link to public reproduction project repository

https://github.com/egvijayanand/maui-issue-12309

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All platforms

### Did you find any workaround?

Nope. Still trying.

### Relevant log output

```shell
Some PDB's checksums do not match their PE files and are shown as missing.
```

**Comment by egvijayanand** [comment]
This was working fine previously and it started to crib after upgrading to .NET MAUI on .NET 7 SR1.1 (v7.0.52).

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 1.1. Not repro this issue.
