### ISSUE TITLE
Unable to write to Registry from MAUI Windows application

### ISSUE THREAD

**Issue by Daniellled** [dotnet/maui#1230]
### Description
I am unable to Save a value to HKCU from a MAUI/WinUI3 application.
### Steps to Reproduce

1. Run *dotnet new maui*
2. Open new project in *Microsoft Visual Studio Enterprise 2019 Preview Version 16.11.0 Preview 1.0*
3. To the WinUI3 project add the nuget package *Microsoft.Win32.Registry Version=5.0.0*
4. Edit the App.xaml.cs to look like the following
```C#
		protected override IWindow CreateWindow(IActivationState activationState)
		{
			Microsoft.Maui.Controls.Compatibility.Forms.Init(activationState);

			this.On<Microsoft.Maui.Controls.PlatformConfiguration.Windows>()
				.SetImageDirectory("Assets");
#if WINDOWS
			// The name of the key must include a valid root.
			const string userRoot = "HKEY_CURRENT_USER";
			const string lmRoot = "HKEY_LOCAL_MACHINE";
			const string subkey = "RegistrySetValueExample";
			const string keyName = userRoot + "\\" + subkey;

			// An int value can be stored without specifying the
			// registry data type, but long values will be stored
			// as strings unless you specify the type. Note that
			// the int is stored in the default name/value
			// pair.
			Registry.SetValue(keyName, "", 5280);
			Registry.SetValue(keyName, "TestLong3", 12345678901234,
				RegistryValueKind.QWord);
#endif

			return new Microsoft.Maui.Controls.Window(new MainPage());
		}
```
5. Fix usings by adding
`using Microsoft.Win32;`
6. Run the application by debugging the WinUI3 (Package)
7. Open Regedit.exe and try to navigate to *Computer\HKEY_CURRENT_USER\RegistrySetValueExample* and nothing exist.

However if you create a new console application with the same code, nuget packages, and Target Frameworks it works.

1. run *dotnet new console*
2. run *dotnet new sln*
3. Open new project in *Microsoft Visual Studio Enterprise 2019 Preview Version 16.11.0 Preview 1.0*
4. Change the target framework of the project to *net6.0-windows10.0.19041*
5. To the project add the nuget package *Microsoft.Win32.Registry Version=5.0.0*
6. Modify Program.cs main
```C#
        static void Main(string[] args)
        {
			Console.WriteLine("Hello World!");

			// The name of the key must include a valid root.
			const string userRoot = "HKEY_CURRENT_USER";
			const string lmRoot = "HKEY_LOCAL_MACHINE";
			const string subkey = "RegistrySetValueExample";
			const string keyName = userRoot + "\\" + subkey;

			// An int value can be stored without specifying the
			// registry data type, but long values will be stored
			// as strings unless you specify the type. Note that
			// the int is stored in the default name/value
			// pair.
			Registry.SetValue(keyName, "", 5280);
			Registry.SetValue(keyName, "TestLong4", 12345678901234,
				RegistryValueKind.QWord);

			Console.ReadLine();
		}
```
7. Fix usings by adding
`using Microsoft.Win32;`
8. Run the application
9. Open Regedit.exe and try to navigate to *Computer\HKEY_CURRENT_USER\RegistrySetValueExample* and TestLong4 exist.

### Expected Behavior

The key *Computer\HKEY_CURRENT_USER\RegistrySetValueExample* would be created in the registry and a value named *TestLong3* would exist in the registry with its data set to *12345678901234*.

### Actual Behavior

The registry key is not created and no data is added to the registry.

### Basic Information

- Version with issue:
- Last known good version: Unknown
- IDE: Microsoft Visual Studio Enterprise 2019 Preview Version 16.11.0 Preview 1.0
- Platform Target Frameworks: net6.0-windows10.0.19041, net6.0-ios;net6.0-android;net6.0-maccatalyst
  - iOS: None
  - Android: None 
  - UWP:  10.0.17763.0 (I think???)
- Android Support Library Version: None
- Nuget Packages: Microsoft.Maui 6.0.100-preview.4.634, Microsoft.Maui.Controls.Compatibility 6.0.100-preview.4.634,  Microsoft.Maui.Resizetizer 6.0.100-preview.4.634, Microsoft.ProjectReunion 0.5.6, Microsoft.Win32.Registry 5.0.0
- Affected Devices: Microsoft Windows [Version 10.0.19042.1052]

**Comment by charlesroddie** [comment]
Wrong repo surely

**Comment by mattleibow** [comment]
The app may be running in the sandbox or package system. I don't think those apps can access the registry in the global sense. It is like a virtual registry combo thing.

This is best asked on the winui repo: https://github.com/microsoft/microsoft-ui-xaml/

**Comment by Daniellled** [comment]
> The app may be running in the sandbox or package system. I don't think those apps can access the registry in the global sense. It is like a virtual registry combo thing.
> 
> This is best asked on the winui repo: https://github.com/microsoft/microsoft-ui-xaml/

Yeah I started here due to the repro steps. Not sure if it is WinUI, or a project reunion issue or what.

**Comment by Fabi** [comment]
> > The app may be running in the sandbox or package system. I don't think those apps can access the registry in the global sense. It is like a virtual registry combo thing.
> > This is best asked on the winui repo: https://github.com/microsoft/microsoft-ui-xaml/
> 
> Yeah I started here due to the repro steps. Not sure if it is WinUI, or a project reunion issue or what.

the behavior is the same as in UWP apps. It's isolated. Another answer as workaround: https://docs.microsoft.com/en-us/answers/questions/285798/how-can-i-edit-the-registry-with-c-uwp.html

**Comment by jfversluis** [comment]
As pointed out, more a WinUI/UWP issue than a .NET MAUI issue. Hope you got it working by now!
