### ISSUE TITLE
Maui MacCatalyst app can't be successfully submitted to Apple macOS store

### ISSUE THREAD

**Issue by Jinjinov** [dotnet/maui#12311]
### Description

App is rejected when trying to upload with Transporter: `App sandbox not enabled. The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list` 

This issue can be fixed with `<CodesignEntitlement>Platforms/MacCatalyst/Entitlements.plist</CodesignEntitlement>` inside `csproj`  and a `Platforms/MacCatalyst/Entitlements.plist` file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
  </dict>
</plist>
```

**But adding this causes that the app in Release mode only displays the splash screen background color and nothing else.**

**This is a showstopper bug.**

### Steps to Reproduce

1. Create a new Maui project
2. Try to publish a Maui MacCatalyst app on Apple macOS store

### Link to public reproduction project repository

https://github.com/Jinjinov/Ididit

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Ventura 13.1

**Comment by jsuarezruiz** [comment]
@rolfbjarne Thoughts?

**Comment by Jinjinov** [comment]
@Eilon @jfversluis @jsuarezruiz @mkArtakMSFT

How can I help? I can try to contribute to MAUI and fix this, if someone gives me some starting points?

**Comment by rolfbjarne** [comment]
* Are there any crash reports in `~/Library/Logs/DiagnosticReports/`?
* Is anything printed to the terminal if the executable is launched directly from the command line (the executable would be something like `./bin/Debug/net7.0-macatalyst/maccatalyst-x64/Ididit.app/Contents/MacOS/Ididit`)

**Comment by Jinjinov** [comment]
There are no crash reports at `~/Library/Logs/DiagnosticReports/`

If the executable is launched directly from the command line, it prints:

    2023-01-29 12:24:50.854 ididit![6712:62057] Could not find `Blazorise.Generator.Features` referenced by assembly `Blazorise, Version=1.1.4.1, Culture=neutral, PublicKeyToken=null`.

But that happens only in my project which uses Blazorise.

If you make a new project from the MAUI Blazor template, the bug is the same (screen in the color of the splash screen)
