### ISSUE TITLE
Unable to reflect assembly of MAUI application on macOS

### ISSUE THREAD

**Issue by realLiangshiwei** [dotnet/maui#12317]
### Description

I try to reflect the assembly of the MAUI application using console program, building the MAUI project from windows works but not on macOS:

```
System.IO.FileLoadException: Could not load file or assembly 'myapp2, 
    Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
```

I noticed that on macOS it trims the assembly.
unfortunately, I can't disable Publish Trimmed. it throws an error on project build: `MacCatalyst projects must build with PublishTrimmed=true. Current value: false`

### Steps to Reproduce

1. Create a new MAUI Blazor app (on Mac OS)
2. Run `dotnet build` for the project.
3. Create a console app and reflect the assembly file of the MAUI application.

Code:

`Assembly.LoadFrom(.....//maui app's assembly file path);`

### Link to public reproduction project repository

https://github.com/realLiangshiwei/ReflectMAUIAssembly

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 13.0.1

**Comment by mattleibow** [comment]
@rolfbjarne is this because the assembly is bundked into the app package?

@realLiangshiwei I think your repro is private as I get a 404 :(

**Comment by realLiangshiwei** [comment]
Hi, @mattleibow 

Sorry, I make it public now.

**Comment by rolfbjarne** [comment]
> I noticed that on macOS it trims the assembly.
> unfortunately, I can't disable Publish Trimmed. it throws an error on project build: `MacCatalyst projects must build with PublishTrimmed=true. Current value: false`

You can tell it to trim nothing by adding this property to the project file:

```xml
<MtouchLink>None</MtouchLink>
```

However, the assembly you're reflecting on must still be referenced from the executable project (and in code, not just in the project file). This is because:

* We will only copy assemblies that are actually used to the app bundle (otherwise the apps will become quite enormous).
* The C# compiler will only add a reference to an assembly if the compiled code needs that assembly.

If you don't want to reference the assembly in question in code, then it might be possible to copy it to the app bundle as a resource:

```xml
<ItemGroup>
    <BundleResource Include="Path/To/MyAssembly.dll" />
</ItemGroup>
```

**Comment by realLiangshiwei** [comment]
> You can tell it to trim nothing by adding this property to the project file:
> <MtouchLink>None</MtouchLink>

Thanks for the suggestion, but it is working.
I think it should have consistent behavior across multiple platforms(win, macos).

> If you don't want to reference the assembly in question in code, then it might be possible to copy it to the app bundle as a resource:

We make a dotnet tool, that can manage the static assets of the application through reflection assembly,  so unable to reference the assembly into the dotnet tool,  it should be loaded dynamically

**Comment by mattleibow** [comment]
OK, so I think I know what is happening here - you are loading the dll from the app inside a console app. @rolfbjarne does the linker potentially do things that makes Assembly.LoadFrom not work?

However, I am not sure the Assembly.LoadFrom will work for mobile apps as they are trimmed (as you know) and potentially optimized - but even if you could load it, all the dependencies will be missing.

Maybe you can try Mono.Cecil as that reads assemblies without actually trying to load the types.

**Comment by realLiangshiwei** [comment]
Hi,

Thanks, but we actually need to load types. we are trying to do something like this:

```csharp
public interface IBundleContributor
{
    List<BundleDefinition> Bundle();
}
```

The `IBundleContributor` interface will be implemented in the app and its dependencies

```csharp
public class AppBundleContributor: IBundleContributor
{
    public List<BundleDefinition> Bundle()
   {
      //....
   }
}
```
In the console app, it read the app's DLL file try to find all types that implement `IBundleContributor` and execute them.

```csharp
var bundleContributors = Assembly.LoadFrom(assembly file path)
   .GetTypes()
   .Where(!t.IsInterface && t.IsAssignableTo<IBundleContributor>()).ToList();
//... and also look for dependencies

foreach(bundleContributorType in bundleContributors)
{
   var bundleContributor = (IBundleContributor)Activator.CreateInstance(bundleContributorType);
   bundleContributor.Bundle();
}
```

**Comment by mattleibow** [comment]
Is there a reason you cannot use a class library to implement `AppBundleContributor`? Is there specific macos code in there that has to be compiled as a mac app?

**Comment by realLiangshiwei** [comment]
Yes, it's possible to use a class library. the reason is the static assets are part of the UI layer(by design), so I didn't do it.

**Comment by rolfbjarne** [comment]
> but we actually need to load types.

In that case your main executable project must reference the assembly in question somehow (in code).
