### ISSUE TITLE
[Android] Listview Header content disappears while scrolling

### ISSUE THREAD

**Issue by liveinvarun** [dotnet/maui#12312]
### Description

Normal Listview with multiple items the header content disappears when scrolled.
NET 6 Latest -> Android 

### Steps to Reproduce

[testsample.zip](https://github.com/dotnet/maui/files/10311386/testsample.zip)

### Link to public reproduction project repository

test sample attached

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

VS2022 preview

### Did you find any workaround?

No workaround.

Not sure how basic functionality like header is broken in MAUI. :(

**Comment by bilelmnasser** [comment]
HI everyone,
Same problem, the header always disappears when scrolling the list view

**Comment by artyomszasa** [comment]
Same issue here, using .NET 7 (7.0.2).
Have you found any solution?
