### ISSUE TITLE
.NET MAUI iOS can't debug or publish arm-64 without iossimulator-x64

### ISSUE THREAD

**Issue by rstolpe** [dotnet/maui#12323]
### Description

you can't debug or publish iOS-arm-64 without the folder iossimulator-x64.

![image](https://user-images.githubusercontent.com/76907327/209873341-a3f9d49f-55f8-4a2a-ba70-ec04591a004d.png)

### Steps to Reproduce

1. delete all the folders inside the Debug folder both the one that are located in obj and bin.
2. In the .csproj file add the following as debug and release, make sure that you delete the other enteries.
````
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'debug'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<CodesignEntitlement>Entitlements.plist</CodesignEntitlement>
		<ArchiveOnBuild>true</ArchiveOnBuild>
		<BuildIpa>true</BuildIpa>
		<IpaPackageName>Mvi</IpaPackageName>
	</PropertyGroup>
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<CodesignEntitlement>Entitlements.plist</CodesignEntitlement>
		<ArchiveOnBuild>true</ArchiveOnBuild>
		<BuildIpa>true</BuildIpa>
		<IpaPackageName>Mvi</IpaPackageName>
	</PropertyGroup>
````
3. Now try to debug or build you will get an error that it's not possible.

### Link to public reproduction project repository

don't have

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Yes,
1. Run the debug or build without the `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` line.
2. Now add `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` back and then run the build or debug again and now it will work.

> VS bug [#1748626](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1748626)

**Comment by KSemenenko** [comment]
Yah this is annoying one

**Comment by rstolpe** [comment]
It's the same for Mac Catalyst

**Comment by mattleibow** [comment]
@rolfbjarne thoughts?

**Comment by rstolpe** [comment]
Why? You have everything above. No need for any code Mr. boot :)

**Comment by rstolpe** [comment]
> Hi @rstolpe. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

You have everything you need above

**Comment by rolfbjarne** [comment]
> 1. Run

How? Are you using VS for Mac? VS for Windows? Command line? VSCode?

**Comment by rstolpe** [comment]
> > 1. Run
> 
> How? Are you using VS for Mac? VS for Windows? Command line? VSCode?

In this I was using vscode on MacOS

**Comment by rolfbjarne** [comment]
This is an issue in VSCode then (or an extension) - @mattleibow do you know where this should go?

**Comment by mattleibow** [comment]
Before we move the issue to VSCode, @rstolpe can you run this app using the command line?

@rolfbjarne  what would be the commands to use in order to determine if the launch is failing because the build did not happen properly for some reason?

**Comment by rstolpe** [comment]
@mattleibow  I can try that tomorrow.

**Comment by rolfbjarne** [comment]
> @rolfbjarne what would be the commands to use in order to determine if the launch is failing because the build did not happen properly for some reason?

I'm not sure I understand, if the app wasn't built properly, there should have been a build error. The only real way to ensure a build happened properly (if there were no build errors), is to run the actual app to see if it works.

**Comment by rstolpe** [comment]
> Before we move the issue to VSCode, @rstolpe can you run this app using the command line?
> 
> 
> 
> @rolfbjarne  what would be the commands to use in order to determine if the launch is failing because the build did not happen properly for some reason?

Everything work from terminal.
Vs2022 for Mac are throwing many false positiv errors. Can I report them somewhere?

**Comment by rolfbjarne** [comment]
> Vs2022 for Mac are throwing many false positiv errors. Can I report them somewhere?

Yes: menu "Help" -> "Report a Problem"

**Comment by rolfbjarne** [comment]
This seems like an issue in VSCode, so I'm moving the issue [there](https://github.com/microsoft/vscode).

**Comment by rolfbjarne** [comment]
This issue was moved to microsoft/vscode#175317
