### ISSUE TITLE
Need the option to modify the visibility of the XAML code-behind class so as to hide it from library consumers

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#12322]
### Description

XAML is easy to generate UI definition. But the visibility of the code-behind type (class) cannot be updated to any value other than `Public`.

While distributing UI definitions in a .NET MAUI class library, some/all UIs need to be made hidden so that it's not directly accessible to library consumers.

Have tried setting the `x:ClassModifier="Internal"` attribute at the root element, but has no effect on the generated code.

This is something like the `x:FieldModifier` attribute that controls the visibility of the views defined within a page/layout/view.

### Public API Changes

```xml
<ContentPage
    x:Class="MauiApp1.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:ClassModifier="Internal">
<!-- Page Content -->
</ContentPage>
```
```cs
namespace MauiApp1;

internal partial class MainPage : ContentPage
{
}
```

### Intended Use-Case

To hide some/all of the UI types so as to prevent direct access by the library consumers.

**Comment by mattleibow** [comment]
@StephaneDelcroix is this just a matter of making the source generators do this, or is there some limitation with xaml and internal?

**Comment by egvijayanand** [comment]
@mattleibow @davidortinau It's possible to define UI types with C# as internal, then it has to be a simple code gen change. Moreover x:ClassModifier attribute is part of the 2009 xaml namespace definition.

https://learn.microsoft.com/en-us/dotnet/desktop/xaml-services/xclassmodifier-directive

Hence, there's nothing new as part of XAML definition as well. Only the logic needs to be slightly tweaked in the source gen.

Moving every other issue to backlog won't help in shaping the product better.

**Comment by pavel-zhukov** [comment]
I absolutely agree with @egvijayanand. Just remove accessibility modifier from auto-generated part of class to allow it to be specified in the editable part. This will suffice until you implement the `x:ClassModifier` functionality.

**Comment by egvijayanand** [comment]
Have gone through the source of the code generator and the accessibility modifier is hardcoded as `public` in the source file.

https://github.com/dotnet/maui/blob/4b54c9f1ccbbb0ad80755bc302f5cf3fd97db3cc/src/Controls/src/SourceGen/CodeBehindGenerator.cs#L166

In the same file, the accessibility modifier for the fields is referred to from the `FieldModifier` attribute defined at the node level.

https://github.com/dotnet/maui/blob/4b54c9f1ccbbb0ad80755bc302f5cf3fd97db3cc/src/Controls/src/SourceGen/CodeBehindGenerator.cs#L321

So based on my understanding, this would be a slight tweak to bring in the `ClassModifier` attribute and update the value of the accessibility modifier at the type level based on the value of the attribute.

**Comment by philipag** [comment]
Any chance this can be added to a coming milestone?  Seems easy enough to do and would be VERY useful for obfuscation.

**Comment by egvijayanand** [comment]
Seems only two possible values are supported for the `ClassModifier` attribute, namely `Public` and `NotPublic`.

In C#:

* Public maps for the `public` accessibility modifier (the default one)
* NonPublic maps for the `internal` accessibility modifier

So I don't think this will have a downstream impact on other areas. So request to kindly take this up in the upcoming service release.
