### ISSUE TITLE
AppCenter still does dot build MAUI apps .... 

### ISSUE THREAD

**Issue by stephenhauck** [dotnet/maui#12336]
### Description

AppCenter still will not build MAUI apps for store submission.

Can you provide detailed instructions for NON AZURE people to use Azure Build Pipelines since they seem to work according to rumor?

### Steps to Reproduce

Simple .. try to setup a build for a MAUI app in AppCenter

### Link to public reproduction project repository

this is not necessary .. ANY MAUI project cannot be built

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All current 

### Did you find any workaround?

Too many "rumors" on how to perform CI/CD for MAUI apps ..

We need FACTS and step by step documentation please

**Comment by JohnHDev** [comment]
You can install .NET MAUI via the CLI (I presume AppCenter allows this too):
```
      - task: CmdLine@2
        displayName: 'Install .NET Maui'
        inputs:
          script: |
            echo Installing .NET Maui workload
            sudo dotnet workload install maui
```

You can then build for iOS, Mac, Android (on a macOS host) and Windows on a Windows host. For iOS I use:
```
            dotnet publish -f net7.0-ios -c RELEASE /p:ApplicationDisplayVersion='$(major).$(minor).$(patch)' /p:ApplicationVersion=${REV} /p:BuildIpa=True /p:RuntimeIdentifier=ios-arm64 "/p:CodesignKey=$(APPLE_CERTIFICATE_SIGNING_IDENTITY)" "/p:CodesignProvision=$(APPLE_PROV_PROFILE_UUID)"
```

This presumes that you have already installed your certs and profiles in an earlier step.

**Comment by wubalubadubdub55** [comment]
@JohnHDev Do you have a link to a blog post or MSFT documentation page to do all this. I'd love to see step by step instructions on this. 🙂

**Comment by stephenhauck** [comment]
@JohnHDev exactly ... a complete end to end "this is how to bypass MAUI AppCenter CI/CD issues" guide with VERIFIED steps ...

**Comment by JohnHDev** [comment]
@stephenhauck its very reproducible, the information on how to install via cmd line is available on the Maui GitHub repo, the botnet publish command line is also published, installing certs and profiles is a prerequisite that I presume you already know how to do.

Does AppCenter build pipelines not use yaml? Maybe that is where the confusion lies.

This isn't difficult to do, it took me a few hours to get it all working in ADO. Certainly not cobbled together, yaml has steps and tasks that you create, some of those just happen to be CLI.

**Comment by stephenhauck** [comment]
@wisdeom , @jamesmontemagno , @maddymontaquila , @davidortinau, @jfversluis

@rachelkang why would you add "needs more info tab" when it's plain and clear that AppCenter STILL does not build MAUI apps ?

Switching to Azure pipelines has NOTHING to do with AppCenter not building MAUI apps .. it may be a workaround but I'm done.

You people at MS just don't care or get it ...

https://github.com/dotnet/maui/discussions/3333

You can close this since no one wants to take responsibility and get it fixed ... I guess it's time to move to Flutter like everyone else is doing

**Comment by stephenhauck** [comment]
@wisdeom , @jamesmontemagno , @maddymontaquila , @davidortinau, @jfversluis, @rachelkang 

I used to pay for Xamarin since back in 2012 .... guess it's dead and over ...  thanks for the memories

**Comment by stephenhauck** [comment]
found this in case anyone stumbles onto this thread ...
https://docs.flutter.dev/get-started/flutter-for/xamarin-forms-devs

**Comment by affableashish** [comment]
@stephenhauck C'mon Stephen,
Don't give up like that.

I haven't really used App center for builds, so I can't really comment on that, but how about this setup:
1.You use Github or Azure DevOps for builds. Example: [here](https://www.cliffordagius.co.uk/post/mauiwithazuredevops/).
2.You use AppCenter for analytics/crash tracking/app distribution. Example: [here](https://www.andreasnesheim.no/using-app-center-diagnostics-analytics-with-net-maui/).

**Comment by davidortinau** [comment]
@stephenhauck this is not the best place for the questions you're asking. I understand your questions are product related, but the team here just isn't responsible for the pieces you're asking about.

For MAUI docs: https://github.com/dotnet/docs-maui/issues
For App Center docs: https://github.com/MicrosoftDocs/appcenter-docs/issues
For Azure DevOps docs: https://github.com/MicrosoftDocs/azure-devops-docs/issues

We have a blog in progress for MAUI and devops which may also become a doc. It's based on this same information: 
https://www.youtube.com/watch?v=yqiGfggSLPY

**Comment by stephenhauck** [comment]
@davidortinau it seems that no matter where we post about AppCenter it is simply ignored even if we email AppCenter support 

I'm not alone in my quest for working software ... 

https://github.com/dotnet/maui/discussions/3333
