### ISSUE TITLE
There is a problem

### ISSUE THREAD

**Issue by XueGang206** [dotnet/maui#12334]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MAUIG1001	An error occured while parsing Xaml: 有多个根元素。 第 15 行，位置 2。.	MyFirstMauiApp (net7.0-android)	E:\C#-lean\MyFirstMauiApp\MyFirstMauiApp.csproj	1	活动

**Comment by wubalubadubdub55** [comment]
@XueGang206 Can you please post a sample code that shows your problem?
There's not enough information on your post to be able to help you.
