### ISSUE TITLE
HeadContent not working with maui with blazor

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#12338]
I created a test page where I use the HeadContent to change the head.   That works fine with blazor server side and blazor web assembly.  However, if I do in any maui app including wpf with blazor, its not setting the headcontent.
That needs to be fixed because there can be cases where the headcontent would simply be linking to external css that is needed.

**Comment by Eilon** [comment]
@musictopia2 can you please upload a sample app to a public GitHub repro that demonstrates this issue, along with any relevant errors and screenshots?

**Comment by musictopia2** [comment]
I have a link to the repository here now.
https://github.com/musictopia2/HeadContentBugSolution 
You will see that blazor server side, the headcontent works perfectly.
However, blazor from wpf does not work at all.
The sample links a css file.  The purpose of doing via headcontent is so a razor class library can link a css file.

**Comment by Eilon** [comment]
@musictopia2 I think the root cause here is that the main page in the Blazor Server app is a Razor Pages CSHTML file: https://github.com/musictopia2/HeadContentBugSolution/blob/master/ServerHeadContentCorrect/Pages/_Host.cshtml#L12

But those don't work in Blazor Hybrid (and I think they don't work in Blazor WebAssembly either?).

Tagging @javiercn and @MackinnonBuck who I think have seen duplicate issues of this before.

**Comment by musictopia2** [comment]
I tried on webassembly and it worked on web assembly.
I updated my repository to show this.

**Comment by musictopia2** [comment]
On wasm, it works because of these 2 lines of code
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

this means something like that needs to be done for maui but don't know where though.

**Comment by Eilon** [comment]
In Blazor Hybrid you can add as many root components as you want, including dynamic root components. You specify them in the RootComponents property of the BlazorWebView control.

I haven't tried it, but maybe that works like with Blazor WebAssembly?

**Comment by musictopia2** [comment]
Where do you add it at?  Because for web assembly, the sample shows something like this.
var serviceCollection = new ServiceCollection();
        serviceCollection.AddWpfBlazorWebView(); //has to change existing ones to use this version for extension.
        serviceCollection.AddBlazorWebViewDeveloperTools();
        Resources.Add("services", serviceCollection.BuildServiceProvider());

I don't even see an option to add root components via code since there is no builder object.

**Comment by Eilon** [comment]
@musictopia2 you can do it in the XAML file for the app. Your app probably already has at least 1 root component for the main component of the app. You should be able to add another root component with different options.

**Comment by musictopia2** [comment]
I see this part
<blazor:RootComponent Selector="#app" ComponentType="{x:Type local:StartBlazor}" />
which is like
builder.RootComponents.Add("#app");

however, not sure how this part would work.
builder.RootComponents.Add("head::after");

First, tried
<blazor:RootComponent Selector="head::after"  />
but then it said it needed the component type.
Then I tried
<blazor:RootComponent Selector="head::after" ComponentType="{x:Type local:StartBlazor}" />
but that somehow did not work either.
Most likely there are some hidden things that are needed so using headcontent can work with maui.  You can see it works for web assembly and server side.  Should be reasonable that it can work with maui as well.

**Comment by Eilon** [comment]
Hi @musictopia2 , using the same pattern as WebAssembly seems to work fine. Here's what I changed in your app's MainWindow.xaml:

1. In the [list of namespace declarations](https://github.com/musictopia2/HeadContentBugSolution/blob/master/WPFBlazorHeadContentFail/MainWindow.xaml#L2-L7) I added:
    ```xaml
        xmlns:blazorweb="clr-namespace:Microsoft.AspNetCore.Components.Web;assembly=Microsoft.AspNetCore.Components.Web"
    ```
1. And then in the BlazorWebView's [list of RootComponents](https://github.com/musictopia2/HeadContentBugSolution/blob/master/WPFBlazorHeadContentFail/MainWindow.xaml#L12-L14) I added the `HeadOutlet`:
    ```xaml
                <blazor:RootComponent Selector="head::after" ComponentType="{x:Type blazorweb:HeadOutlet}" />
    ```

And it rendered the red CSS:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/202643/210859179-48430f18-3dc9-4655-8119-c3fd8603a85d.png">
