### ISSUE TITLE
MAUI .net 7.0 , App store submission failed bitcode issue December 2022

### ISSUE THREAD

**Issue by ganeshachary** [dotnet/maui#12331]
### Description

The Apple App store rejected the Maui .net 7.0 App submission due to code containing bitcode 

Earlier faced the same issue on November 22, 2022. Updating the nugets package worked and also 
https://github.com/dotnet/maui/issues/10989#issuecomment-1304317816 this workaround helped earlier.
was able to upload the App.

On December 27 2022  after some feature changes with no new updates to Maui.net packages, submission failed with the same bitcode issues listed below : 

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/AppAuth.framework/AppAuth' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FBAEMKit.framework/FBAEMKit' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FBLPromises.framework/FBLPromises' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FBSDKGamingServicesKit.framework/FBSDKGamingServicesKit' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FBSDKLoginKit.framework/FBSDKLoginKit' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FBSDKShareKit.framework/FBSDKShareKit' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FacebookGamingServices.framework/FacebookGamingServices' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseABTesting.framework/FirebaseABTesting' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseAuth.framework/FirebaseAuth' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseCore.framework/FirebaseCore' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseDynamicLinks.framework/FirebaseDynamicLinks' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseFirestore.framework/FirebaseFirestore' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseFunctions.framework/FirebaseFunctions' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseInstallations.framework/FirebaseInstallations' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseMessaging.framework/FirebaseMessaging' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseRemoteConfig.framework/FirebaseRemoteConfig' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/FirebaseStorage.framework/FirebaseStorage' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/GTMAppAuth.framework/GTMAppAuth' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/GoogleAPIClientForREST.framework/GoogleAPIClientForREST' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/GoogleDataTransport.framework/GoogleDataTransport' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/GoogleUtilities.framework/GoogleUtilities' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/Protobuf.framework/Protobuf' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/absl.framework/absl' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/grpc.framework/grpc' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/grpcpp.framework/grpcpp' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/leveldb.framework/leveldb' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/nanopb.framework/nanopb' contains bitcode.

ITMS-90482: Invalid Executable - The executable '"{AppName}.app/Frameworks/openssl_grpc.framework/openssl_grpc' contains bitcode.

### Steps to Reproduce

NA

### Link to public reproduction project repository

NA

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

iOS

### Affected platform versions

ios 16 , Xcode 14.1

### Did you find any workaround?

No

**Comment by rachelkang** [comment]
@SotoiGhost any thoughts for this one?

**Comment by rachelkang** [comment]
This issue was moved to xamarin/xamarin-macios#17152
