### ISSUE TITLE
iOS Local Network permission not requested, can't be checked

### ISSUE THREAD

**Issue by skima74** [dotnet/maui#12351]
### Description

When deploying a new Maui app to an iOS device, and accessing local network addresses, the app does appear to request local network permissions, and cannot access local network hosts. The same app deployed on Windows works fine, no issue. Adding 
<key>NSLocalNetworkUsageDescription</key>	<string>Allow LAN access</string> to the Info.plist does not make any difference.  Have tried this with both Debug and Release builds/deploys, neither work.

Docs for Permissions in Maui (https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/permissions?view=net-maui-7.0&tabs=windows) make no mention of Local Network permissions, so looks like checking this is not supported.

### Steps to Reproduce

I've attached a link to the public repo below.
Its a standard maui app with added buttons and entry to specify an url.
The local network traffic is directed to the ingestion port of a Seq sink for the Serilog logger.

### Link to public reproduction project repository

[skima74/MauiExperiments/MauiSerilogTestApp](https://github.com/skima74/MauiExperiments/tree/master/MauiSerilogTestApp)

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

Nope.

**Comment by skima74** [comment]
Seems to be a bug in iOS 16.x
See https://developer.apple.com/forums/thread/711320

**Comment by rachelkang** [comment]
@skima74 Can you confirm this is a bug with Apple and not .NET MAUI so we can close this issue here?
