### ISSUE TITLE
Unwanted behavior in ToolBarItems on iOS and macOS.

### ISSUE THREAD

**Issue by pitasoft** [dotnet/maui#12359]
### Description

It is observed that in the iOS and macOS platforms, in the pages that you want to use ToolBarItems in these platforms, the icons are not displayed with the desired colors, so I have used black and white icons to solve this problem, because there are icons that only the outline is visible. But in addition to this, the icons cannot be displayed correctly on the pages, as can be seen in the following images.

Windows
<img width="543" alt="Captura de pantalla 2022-12-30 a las 20 12 16" src="https://user-images.githubusercontent.com/52622876/210104677-4862c4a3-500f-48d6-84b3-fe93b1b20401.png">
In this image you can see the desired behavior.

Android
<img width="349" alt="Captura de pantalla 2022-12-30 a las 20 13 32" src="https://user-images.githubusercontent.com/52622876/210104760-2414b573-4632-4d86-a620-952c231a206d.png">
Also, it can be observed that the behavior is correct.

But on Apple platforms, the icons don't look good even though OnPlatform is used to change the icon and use a black and white image. In addition, it is also observed that the buttons do not fit the screen.

macOS
<img width="733" alt="Captura de pantalla 2022-12-30 a las 20 16 09" src="https://user-images.githubusercontent.com/52622876/210104966-4c281aea-cfa3-44cc-b44b-f528164d214c.png">
Not all the marked buttons appear, because the buttons are very wide.

iOS
<img width="396" alt="Captura de pantalla 2022-12-30 a las 20 19 30" src="https://user-images.githubusercontent.com/52622876/210105216-8302bffa-5eb4-4f33-b127-5812cd5564a7.png">

### Steps to Reproduce

Attached part of the code that is used.

```
   <pages:TaskPage.ToolbarItems>
        <ToolbarItem Text="Refresh" IconImageSource="{OnPlatform Default='refresh.png',iOS='refresh_bk.png',MacCatalyst='refresh_bk.png'}" Order="Primary" Command="{Binding RefreshDataCommand}">
        </ToolbarItem>
        <ToolbarItem Text="New" IconImageSource="newitem.png" Command="{Binding NewFarmCommand}">
            <ToolbarItem.Order>
                <OnPlatform x:TypeArguments="ToolbarItemOrder">
                    <On Platform="iOS" Value="Secondary"/>
                    <On Platform="Default" Value="Primary"/>
                </OnPlatform>
            </ToolbarItem.Order>
        </ToolbarItem>
        <ToolbarItem Text="Update" IconImageSource="updateitem.png" Command="{Binding UpdateFarmCommand}">
            <ToolbarItem.Order>
                <OnPlatform x:TypeArguments="ToolbarItemOrder">
                    <On Platform="Android" Value="Secondary"/>
                    <On Platform="iOS" Value="Secondary"/>
                    <On Platform="Default" Value="Primary"/>
                </OnPlatform>
            </ToolbarItem.Order>
        </ToolbarItem>
        <ToolbarItem Text="Delete" IconImageSource="deleteitem.png" Command="{Binding DeleteFarmCommand}">
            <ToolbarItem.Order>
                <OnPlatform x:TypeArguments="ToolbarItemOrder">
                    <On Platform="Android" Value="Secondary"/>
                    <On Platform="iOS" Value="Secondary"/>
                    <On Platform="Default" Value="Primary"/>
                </OnPlatform>
            </ToolbarItem.Order>
        </ToolbarItem>
        <ToolbarItem Text="Evolution" IconImageSource="{OnPlatform Default='chart.png',iOS='chart_bk.png',MacCatalyst='chart_bk.png'}" Order="Primary" Command="{Binding ChartFarmCommand}"/>
    </pages:TaskPage.ToolbarItems>
```

### Link to public reproduction project repository

There is no public repository.

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.2 y macOS 13.1

**Comment by pitasoft** [comment]
In the icons that I use for Apple platforms, I have modified the icons in the project file to set the size of the images, but it still fails. I show an example of the modification that I have made in the images.

```
    <MauiImage Include="Resources\Images\add_bk.svg" BaseSize="24,24" />
    <MauiImage Include="Resources\Images\cancel_bk.svg" BaseSize="24,24"/>
    <MauiImage Include="Resources\Images\chart_bk.svg" BaseSize="24,24" />
    <MauiImage Include="Resources\Images\download_bk.svg" BaseSize="24,24"/>
    <MauiImage Include="Resources\Images\edit_bk.svg" BaseSize="24,24" />
    <MauiImage Include="Resources\Images\refresh_bk.svg" BaseSize="24,24" />
    <MauiImage Include="Resources\Images\save_bk.svg" BaseSize="24,24" />
```

As the behavior has not been adequate, I have modified the images with Adobe Ilustratro, modifying the size of the SVG files, which had a size of 512px * 512px to 24px * 24px. At this point I have managed to have a proper behavior, as you can see in the following images.

<img width="685" alt="Captura de pantalla 2022-12-31 a las 10 04 20" src="https://user-images.githubusercontent.com/52622876/210131278-4bb2ea22-1edc-4d87-b21e-1b23b2fe8412.png">

<img width="396" alt="Captura de pantalla 2022-12-31 a las 10 05 36" src="https://user-images.githubusercontent.com/52622876/210131304-509393d6-cd9f-459c-951c-3c973bd8050d.png">

**Comment by rachelkang** [comment]
Hi, @pitasoft - thanks for opening this issue. Unfortunately, due to platform limitations, having colored icons in the toolbar for maac and iOS is not feasible. As for the sizing issue, if you are continuing to experience it, please attach a repro so that we can investigate further. Also related is #8609

**Comment by pitasoft** [comment]
Hello, I understand the limitation of the platform, but the problem is that the images of the icons (which I have put in two colors, black and white), I have managed to make them look correctly. The problem is that the icons take the actual size of the image, even though a BaseSize is specified. To solve the problem I had to change the size of the SVG files to 24 px x 24 px.

I try to create a public repository so that the problem can be seen. The simple thing would be for the icons to be used in the toolbar to use the appropriate size.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 3.0(net8) and Visual Studio for Mac 17.6 (build 1575). Can repro on macOS and iOS platform with sample project. [ToolbarIcon-Bug.](https://github.com/BalachandarSelvam/Framework-bug/tree/main/ToolbarIcon-Bug)

**Comment by jknaudt21** [comment]
> Hello, I understand the limitation of the platform, but the problem is that the images of the icons (which I have put in two colors, black and white), I have managed to make them look correctly. The problem is that the icons take the actual size of the image, even though a BaseSize is specified. To solve the problem I had to change the size of the SVG files to 24 px x 24 px.
> 
> I try to create a public repository so that the problem can be seen. The simple thing would be for the icons to be used in the toolbar to use the appropriate size.

Based on this, I'd say it is safe to say that this issue is linked to #17120
