### ISSUE TITLE
WebView2 stops receiving click events if you type and switch focus fast enough.

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/maui#12361]
### Description

If you have two text inputs and type fast while clicking between the inputs, the WebView2 control or the MAUI desktop window stops receiving mouse click events. You can still use keyboard events, i.e tab and enter to navigate, but you can no longer click anything.

### Steps to Reproduce

1) Create a new MAUI blazor project.
2) Create two text input fields:
```html
@page "/"

<h1>Hello, world!</h1>

<div class="container">
    <div class="row">
        <div class="col">
            <input class="form-control" type="text" />
        </div>
    </div>
    <div class="row">
        <div class="col">
            <input class="form-control" type="text" />
        </div>
    </div>
</div>
```
3) Run the app
4) Focus on one of the text inputs, type fast and then use the mouse simultaneously to switch focus between the two text inputs.
5) after a few focus switches, the window will no longer accept mouse click events.

Video example:
https://www.youtube.com/watch?v=f5nYtta00y0

### Link to public reproduction project repository

https://github.com/KieranDevvs/WebView2BugTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

None.

### Relevant log output

```shell
N/a
```

**Comment by nathanjeynes** [comment]
This sounds similar to #12262 and the issue I'm having.

**Comment by Eilon** [comment]
@nathanjeynes alright that's good to know, thank you!

**Comment by Eilon** [comment]
@nathanjeynes I confirmed it repros with even a plain WinUI3 app w/ WebView2:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/202643/210862274-70a16b8a-832a-46c3-b68e-239d3a33662c.png">

It appears to be a known issue logged here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003

Please up-vote that to help it gain visibility.

**Comment by KieranDevvs** [comment]
@Eilon Is anyone from MS going to chase this up internally on behalf of the community? Seeing as WebView2 isn't open source and the team members don't respond to anything posted, everyone who decided to use MAUI Blazor in production is in dire s**t street right now.

**Comment by nathanjeynes** [comment]
@Eilon also if anyone from the blazor team can put pressure on them to fix this as it will stop anyone using .net maui blazor releasing into production? Not sure who best to tag here.

**Comment by Eilon** [comment]
@KieranDevvs , @nathanjeynes - we do talk to the WebView2 folks and I'll make sure we bring up these issues to them in our next discussion. Upvoting the issues in the WebView2 repo is a huge help because it helps demonstrate how important the issues are.
