### ISSUE TITLE
Shapes gallery currently crashes because of Polygon and Polyline confusions

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#12364]
### Description

It looks like because we have `Polyline` and `Polygon` defined in both maps and shapes we get a crash. In this case, it looks like the Maps version is winning which is causing a crash.

### Reproduction

- Run the samples gallery
- Controls => Shapes => crash

**Comment by jsuarezruiz** [comment]
On what platform?

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz Pretty sure all of them since it's an issue with processing the `XAML`

Tried on Windows and was not able to reproduce the issue. But, then noticed is because there is no map support on Windows. I have managed to reproduce the issue and submit a fix. Thanks for the feedback.
