### ISSUE TITLE
Windows deadlock when copying text in Entry

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#12369]
### Description

This issue occurs in Xamarin.Forms & MAUI. I've profiled this application using the Visual Studio profiler.

The highlighted section is where the "deadlock" occurs. It fixes itself after an unknown amount of time, which seems to scale based on the time dragging around the control.

![image](https://user-images.githubusercontent.com/105223895/210154407-2be88419-c6a1-459a-b5bc-069e51225e48.png)

### Steps to Reproduce

1. Create new MAUI application based on default template in VS 2022
2. Add the following text to `MainPage`

```
            <Entry Text="Test text" />
```
3. Run application, click into textbox and click and drag rapidly **outside** the boundaries of the text box.
4. Observe deadlock

Attached is a video demonstrating the freeze. You can see the time "clicking & dragging" around the control. After the deadlock occurs, I attempt to click on the "Click" button and it does not update until the freeze has ended.

https://user-images.githubusercontent.com/105223895/210154476-98d93c4e-9a63-4f08-8b2e-a313fb91a6a2.mp4

### Link to public reproduction project repository

https://github.com/daltzctr/MauiDeadlock

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 22621.963

### Did you find any workaround?

No. Seems to be a bug in WinRT.

> VS bug [#1782015](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1782015)

**Comment by drasticactions** [comment]
You wrote that this happens in a non-MAUI app, correct? If this is a bug with WinUI and/or UWP itself, the issue should be filed there. I don't think there's much here that could be done about it.

**Comment by daltzctr** [comment]
This does happen in the Windows 11 settings app, but it's a bit less extreme. If you could point me to the relevant repo, I'd be happy to duplicate this issue there!

**Comment by PureWeen** [comment]
@daltzctr Would it be possible to see if you can recreate this inside a WinUI platform app?

**Comment by daltzctr** [comment]
@PureWeen this is reproduced in a blank WinUI platform app. A reproduction sample is available [here](https://github.com/daltzctr/WinUITest)

**Comment by mattleibow** [comment]
This issue was moved to microsoft/WindowsAppSDK#3299
