### ISSUE TITLE
Unable to load Win2D Maui Graphics images on the background thread

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#12370]
### Description

The current code sets up a W2DGraphicsService.Creator from the graphics view. And if there is no view, then image loading fails.

Exception message: "No resource creator has been registered globally or for this thread."

### Steps to Reproduce

1. :)

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

**Comment by u1-kino** [comment]
https://github.com/dotnet/Microsoft.Maui.Graphics/issues/422
This bug and related content and workarounds are proposed in Issue number 442 in the Maui.Graphics repository.

**Comment by janseris** [comment]
It shouldn't be dependent on any GraphicsView because image processing is usually a backend service (e.g. resize a photo).
