### ISSUE TITLE
Maui for Windows freezes when resizing Entry control for email address

### ISSUE THREAD

**Issue by donald-fraser** [dotnet/maui#12377]
### Description

A WinUI Maui project, with CommunityToolkit.Mvvm, and one page.
Assigning a string, containing an email, to a binderable control, using a view-model, during page loading freezes the main thread.
Pausing the app show the main thread is locked here:
Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride

![Maui-WinUI-bug](https://user-images.githubusercontent.com/13952324/210188990-859c7d4d-8b97-4981-8183-073e8be99b4d.JPG)

### Steps to Reproduce

I have created a project that contain minimal code (see below):

The offending line of code is in the file:
Maui-NoteApp\ViewModels\Startup\LoginPageViewModel.cs
line: 11
` 

        public LoginPageViewModel() 
        {           
            // For some bizare reason if the string is a valid email style address, windows locks up when resizing
            _email = "testy.mctest@test.face";
        }
`

### Link to public reproduction project repository

https://github.com/donald-fraser/MauiWinUIBug.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows-10.0.19041, SDK Version: 7.0.101, maui-windows 7.0.52/7.0.100 VS 17.4.33205.214

### Did you find any workaround?

Assign the observable string variable via dispatch thread...
`
        AppShell.Current.Dispatcher.Dispatch(() =>
        {
            Email = "testy.mctest@test.face";
        });
`

**Comment by PureWeen** [comment]
@donald-fraser if you use `Border` instead of `Frame` does that fix your issue?

I'm guessing your issue will be fixed by the following PR to `Frame` 
https://github.com/dotnet/maui/pull/11779

**Comment by donald-fraser** [comment]
> @donald-fraser if you use `Border` instead of `Frame` does that fix your issue?
> 
> I'm guessing your issue will be fixed by the following PR to `Frame` #11779

Yes you are correct. Thanks
