### ISSUE TITLE
Support OSM by MAUI MapControl

### ISSUE THREAD

**Issue by AllNickNamesAreBusySoITakenThis** [dotnet/maui#12378]
Your MapControl looks great! Many thanks for it! But do you plan to integrate Open Street Map (OSM) support?

**Comment by Ghostbird** [comment]
What do you mean by OSM support? There is not one OSM tile server URI you can use, as you can do for Google Maps (and presumably Bing/Apple and maps).  I would like to see generic XYZ tiles layer support, but it might require quite a bit of work, depending on the current state of the control.

A first version might just allow a replacement of the current map layer with a generic XYZ tiles layer based on a URI template. But then the projection of those tiles probably must be EPSG:3857

**Comment by vhugogarcia** [comment]
@AllNickNamesAreBusySoITakenThis please refer to this discussion about MAUI community toolkit wanting to implement a map handler on webview. Please join that conversatio, any feedback is always welcome.

**Comment by Ghostbird** [comment]
Ah, good idea. This sounds like a better fit for the community toolkit.

**Comment by vhugogarcia** [comment]
I agree. @Ghostbird https://github.com/CommunityToolkit/Maui/issues/605 please share the feedback above on the community toolkit thread, so others can see it. 👍🏻

**Comment by mattleibow** [comment]
This issue was moved to CommunityToolkit/Maui#865
