### ISSUE TITLE
MAUI blazor cannot inject `NavigationManager` into a service 

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/maui#12387]
### Description

When trying to inject a `NavigationManager` into a singleton service and try to access it like so `Manager.NavigateTo(url);`, it shows me the following error:

![image](https://user-images.githubusercontent.com/43137837/210334897-a952a2c4-03b7-4cf2-a8af-4197075c7bee.png)

### Steps to Reproduce

1. Create an MAUI blazor app
2. Create a singleton service that requires a `NavigationManager` instance
3. Create and call a method that calls `NavigateTo` on the `NavigationManager`
4. Error 

### Link to public reproduction project repository

none

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows 11

### Did you find any workaround?

I can use events to navigate through the blazor app instead of calling the manager directly, but it is very tedious to do so

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This seems to be something we may have fixed in 7.0.
Can you please try that out and see if that's the case or not?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Singleton services shouldn't depend on non-singleton services. You should fix the scope of the service which depends on the NavigationManager to be `scoped` too and that should fix it. Also, there has been DI / NavigationManager related fix in .NET 7. So give that a try to (after fixing the scope, of course).
