### ISSUE TITLE
How to make animation rate smooth

### ISSUE THREAD

**Issue by Glacial** [dotnet/maui#12385]
### Discussed in https://github.com/dotnet/maui/discussions/12280

<div type='discussions-op-text'>

<sup>Originally posted by **Glacial** December 23, 2022</sup>
Hi all,
I'm working on a cross-platform app that requires buttery smooth scrolling of large items and I'm encountering a whole bunch of stuttering and hitching with MAUI.
	
There's a little test app here that should help my description a bit:
https://github.com/Glacial/MauiAnimationSmoothnessTest
	
The test app moves some items around the screen and measures the time between PropertyChanged events being fired as an animation affects a property. An average is based off the last 100 reading as is shown along with a "low" and "high" time within that 100.
The large bars are animated by moving a fixed number of pixels each update instead of using a delta time. This highlights the variance in frame times more. The progress bar is using a MAUI animation so should be using a delta time solution, but can still appear choppy. The statements below are based on Release mode builds.
	
On Windows, the animation loop is very choppy, unable to maintain a steady 60fps. The stats output by the test app show an average around 16.33ms (good) but wobbles where the gap between animation updates is as low as 0.6ms or as high as 33.4ms. This variance creates notably unstable looking movement. This is without interacting with the app.
	
iOS fares much better, maintaining an average 16.66ms per frame with little variance, that is until you interact. When you interact note that the "High" time can suddenly double and frame skips can be noted. Try dragging around the slider to create a little choppiness. My tests were performed on an iPad Air (5th Gen).
	
Is there anything I can do to improve the animation rates so they look more steady and professional (such as paint to screen myself)? Is there still work for the MAUI team to do to improve this (if so should this be re-posted as an issue)?
	
I've experimented with using a separate PlatformTicker to drive my timings with no improvements (probably because I still can't influence the screen paint time) so I assume the problems are with the underlying platform specific hooks.
	
Thanks
</div>

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0(.NET8). Can repro on windows platform with sample project.
[MauiAnimationSmoothnessTest-main.zip](https://github.com/dotnet/maui/files/12342461/MauiAnimationSmoothnessTest-main.zip)
![1](https://github.com/dotnet/maui/assets/77434865/e13202e1-9a05-432d-8dd6-e0eeded9311a)

**Comment by davidortinau** [comment]
Is your goal to actually achieve **this** animation smoothly? It is important to focus the sample to the actual scenario you need for your app. For example, `Border` does not perform in this case as well as something more primitive like `BoxView`. `Border` is a layout/container that has the potential to trigger additional layout/measure calls that would slow down an animation.

The smoothest way to do this animation would be with GraphicsView and drawing APIs, or even SkiaSharp.

So please focus the report on a real world scenario and we can consider how it might be addressed, and prioritize it among other issues here.

**Comment by davidortinau** [comment]
I see this is an older report, so I'm going to close this issue. Please open a new issue with the guidance I provided.
