### ISSUE TITLE
`dotnet publish` fails for Windows [MSB4184]

### ISSUE THREAD

**Issue by nor0x** [dotnet/maui#12389]
### Description

i'm trying to publish the Windows version of my application. Running the `dotnet publish -f net7.0-windows10.0.17763.0` command fails with the following error message:

```
C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(188,18): error MSB4184: The expression "[MSBuild]::VersionGreaterThan( [C:\Users\Johnny\Dev\dots\Dots\MAUI\Dots.csproj::TargetFramework=net7.0-windows10.0.17763.0]
C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(188,18): error MSB4184: 10.0.17763.0, 10.0.17763.0)" cannot be evaluated. Version string was not in a correct format. [C:\Users\Johnny\Dev\dots\Dots\MAUI\Dots.csproj::TargetFramework=net7.0-windows10.0.17763.0]
```

![image](https://user-images.githubusercontent.com/3210391/210337616-2b309f6f-07a1-4277-9a0d-f70d61a9b573.png)

### Steps to Reproduce

1. Create new MAUI app
2. run `dotnet publish -f net7.0-windows10.0.17763.0` 

### Link to public reproduction project repository

https://github.com/nor0x/MauiFails

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by mattleibow** [comment]
@nor0x I am wondering if it is potentially the whitespace in these: https://github.com/nor0x/MauiFails/blob/main/MauiFails/MauiFails.csproj#L27-L38

Try putting it on a single line and see if that fixes it.

**Comment by nor0x** [comment]
> @nor0x I am wondering if it is potentially the whitespace in these: https://github.com/nor0x/MauiFails/blob/main/MauiFails/MauiFails.csproj#L27-L38
> 
> Try putting it on a single line and see if that fixes it.

thanks a lot! my auto-formatter in vscode added these 🤦

it's working now!
