### ISSUE TITLE
[Bug] Could not run application by using dotnet-run command

### ISSUE THREAD

**Issue by yamachu** [dotnet/maui#1238]
### Description

On Maui project, the path resolved by `dotnet run` does not reflect the OS delimiter.

### Steps to Reproduce

1. Following https://github.com/dotnet/maui/wiki/Getting-Started Step 1 to 3
2. dotnet build -c Debug -f net6.0-maccatalyst HelloMauiPreview
3. dotnet run -c Debug -f net6.0-maccatalyst -p HelloMauiPreview --no-build

### Expected Behavior

Run applications with following path ( /Users/yamachu/Projects/github.com/yamachu/Repro/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/Repro.app )

### Actual Behavior

shell shows `The file /Users/yamachu/Projects/github.com/yamachu/Repro/bin\Debug/net6.0-maccatalyst/maccatalyst-x64/Repro.app does not exist.`

### Basic Information

- Version with issue: -
- Last known good version: -
- IDE: -
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Microsoft.Maui.Core/6.0.100-preview.4.634
- Affected Devices: macOS BigSur 11.4

- dotnet version: 6.0.100-preview.4.21255.9

### Screenshots

<img width="1680" alt="スクリーンショット 2021-06-10 20 41 53" src="https://user-images.githubusercontent.com/1955233/121519514-c0fb5280-ca2c-11eb-9a38-7dc5e816f728.png">

### Workaround

Following https://github.com/dotnet/maui/wiki/Getting-Started Step 4
`dotnet build -t:Run -c Debug -f net6.0-maccatalyst HelloMauiPreview`

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#11999
