### ISSUE TITLE
Border content clipping issue on iOS

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#12398]
### Description

When using a Border with a RoundRectangle stroke shape, the content of the border is clipped even if there is enough margin.
The bug is only for the top-left corner (the 3 other corners are fine), which is weird.
This happens only on iOS. No issue on Android.

<img src="https://user-images.githubusercontent.com/12516566/210432033-3d55bd30-6440-4734-a8cb-a8cadd947d07.png" height=700 /> <img src="https://user-images.githubusercontent.com/12516566/210432025-81ace8f1-25a1-49d2-bd1a-23f5d87b7d4a.png" height=700 /> 

### Steps to Reproduce

1. Create Maui app (for iOS and Android)
2. Add page with Border (RoundRectangle shape) and content
3. Compare Android and iOS displays

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppBorderPaddingClip

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

no workaround

**Comment by activa** [comment]
Could be related to #7521

**Comment by danielftz** [comment]
The workaround Ive found is that instead of setting Padding for the Border, set the Margin for its Content instead.

**Comment by tranb3r** [comment]
> The workaround Ive found is that instead of setting Padding for the Border, set the Margin for its Content instead.

I've thought about that. Unfortunately, it does not work on my sample.

<img src="https://user-images.githubusercontent.com/12516566/210507551-91e41371-87a9-453d-a6d7-4f76cd2a0fe7.png" width=500 />

**Comment by tranb3r** [comment]
@rachelkang 
Are you sure this a duplicate ? How do you explain that only the top-left corner has an issue here ?

**Comment by danielftz** [comment]
> Duplicate of #10724

> @rachelkang Are you sure this a duplicate ? How do you explain that only the top-left corner has an issue here ?

Yea they don't seem to be clipping the same way.
