### ISSUE TITLE
[Edited] Is MVU-Style Coded-UI really necessary?

### ISSUE THREAD

**Issue by sim756** [dotnet/maui#124]
I think MAUI should stick with only one way of designing UI, that's: **XAML**

**Blazor Syntex** is okay, but MVU seems totally unnecessary mess to me. If it is to attract Flutter Devs, please, let them stay with Flutter; DO NOT destroy the beauty of XAML;

_[Update]_
![image](https://user-images.githubusercontent.com/5331667/83265397-45dd4a80-a1e3-11ea-9acf-a63c74ff4ab5.png)

**Comment by Happypig375** [comment]
Flutter has an entire [page](https://flutter.dev/docs/get-started/flutter-for/xamarin-forms-devs) dedicated to attracting people from Xamarin.Forms. You are saying we should ignore competition. Really?

**Comment by rohanbojja** [comment]
Blazor bindings are beautiful! I'm just starting out with them and they offer the simplicity that Flutter does.

**Comment by forki** [comment]
@davidortinau as I said in the other thread. The MAUI blog post created massive confussion. People now seem to think MVU = view as code/DSL. 
But this is completely independent from what MVU is. MVU is perfectly possible with XAML. It has nothing to do with how you write the view. 
It's only about creating an immutable model + update function which takes a model and msg and builds a new model and also a view function which does not mutate the model directly but sends new commands (messages) into the update loop.

**Comment by saint4eva** [comment]
> I think MAUI should stick with only one way of designing UI, that's: **XAML**
> 
> **Blazor Syntex** is okay, but MVU seems totally unnecessary mess to me. If it is to attract Flutter Devs, please, let them stay with Flutter; DO NOT destroy the beauty of XAML;

It is meant for C# and .NET dev.

**Comment by aspnetde** [comment]
@sim756 

> I think MAUI should stick with only one way of designing UI, that's: XAML

It has never been one way only. Code-based UIs have been supported through Xamarin.Forms from the beginning. Making that more approachable makes sense. And by the way: MVU can be used [easily with XAML](https://fsprojects.github.io/Fabulous/Fabulous.StaticView/).

**Comment by sim756** [comment]
@Happypig375 
> Flutter has an entire [page](https://flutter.dev/docs/get-started/flutter-for/xamarin-forms-devs) dedicated to attracting people from Xamarin.Forms. You are saying we should ignore competition. Really?

Well, we better have "**Xamarin for Flutter devs**" page!


@rohanbojja 
> Blazor bindings are beautiful! I'm just starting out with them and they offer the simplicity that Flutter does.

Everything is okay except this, and **_this_** is why I hate **Flutter** : 
![image](https://user-images.githubusercontent.com/5331667/83265072-d36c6a80-a1e2-11ea-9611-a941cd338744.png)
**Image 0**

@forki 
> @davidortinau as I said in the other thread. The MAUI blog post created massive confussion. People now seem to think MVU = view as code/DSL.
> But this is completely independent from what MVU is. MVU is perfectly possible with XAML. It has nothing to do with how you write the view.
> It's only about creating an immutable model + update function which takes a model and msg and builds a new model and also a view function which does not mutate the model directly but sends new commands (messages) into the update loop.

I am really confused!! Thank you, you just made it clear, the post is catastrophically confusing: 
![image](https://user-images.githubusercontent.com/5331667/83265397-45dd4a80-a1e3-11ea-9acf-a63c74ff4ab5.png)
**Image 1**


@saint4eva 
> > I think MAUI should stick with only one way of designing UI, that's: **XAML**
> > **Blazor Syntex** is okay, but MVU seems totally unnecessary mess to me. If it is to attract Flutter Devs, please, let them stay with Flutter; DO NOT destroy the beauty of XAML;
> 
> It is meant for C# and .NET dev.

"**It is meant for C# and .NET dev.**", exactly, it should not get influenced by Flutter (I am afraid it is..).


@aspnetde 
> @sim756
> 
> > I think MAUI should stick with only one way of designing UI, that's: XAML
> 
> It has never been one way only. Code-based UIs have been supported through Xamarin.Forms from the beginning. Making that more approachable makes sense. And by the way: MVU can be used easily with XAML ([Xamarin.Forms](https://fsprojects.github.io/Fabulous/Fabulous.StaticView/), [WPF](https://github.com/elmish/Elmish.WPF)).

I know. Sometimes we do write `new Button() { .... }`, but this [post](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/) (**Image 1**) confused me, and many other, I believe.

**Comment by Happypig375** [comment]
> @Happypig375
> 
> > Flutter has an entire [page](https://flutter.dev/docs/get-started/flutter-for/xamarin-forms-devs) dedicated to attracting people from Xamarin.Forms. You are saying we should ignore competition. Really?
> 
> Well, we better have "**Xamarin for Flutter devs**" page!

LOL. Imagine a page dedicated to "Windows Forms for WPF devs".

**Comment by GiampaoloGabba** [comment]
XAML is just a "tool" on top of the object model...  You can use xaml, c#. You can architect your app using MVVM (with or without XAML) or with MVU (to be fair the examples provided were not "real" MVU but this is another topic).

If you dont like coded ui or the MVU approach just ignore it :) There is no need to push it back.

I dont think this is just to attract flutter developer. The MVU pattern is on the rise, and is very well suited for mobile development.

**Comment by GiampaoloGabba** [comment]
Also coded UI is on the rise... react, flutter, swiftUI, ecc... theyy are gaining a LOT of popularity

**Comment by sim756** [comment]
# What I wanted to say:

What will we choose between **Flutter/Swift/Coded-UI** thing and **WPF/XAML** with a **GUI Editor** like **Blend for Visual Studio**?

**Comment by aspnetde** [comment]
@sim756 

> I know. Sometimes we do write new Button() { .... }

Sometimes people write entire XF apps without touching XAML – and they are happy about it ;-).

**Comment by sim756** [comment]
> @sim756 
> 
> > I know. Sometimes we do write new Button() { .... }
> 
> Sometimes people write entire XF apps without touching XAML – and they are happy about it ;-).

@aspnetde

I'm surprised..!! 😢

However, not for them, but for people like me, who wants **Blend** for Xamarin/MAUI, is unhappy:

Android Studio **Motion Editor**

https://developer.android.com/studio/write/motion-editor

https://developer.android.com/studio/images/write/motion_animation_preview.gif

**Comment by forki** [comment]
@sim756 I wonder if you still want to have blend support once you worked in a system with properly working hot reload. Usually people prefer that a lot

**Comment by isaacabraham** [comment]
Coming from a XAML / Blend background, my initial thoughts around UI in code was to recoil but once I tried it, there were many benefits that I saw that I had simply not considered. The removal of the need for - what now seems like massively overly-complex but at the time felt totally reasonable - features such as converters, resources and similar have made me a real believe in code-first UIs.

**Comment by Yakimych** [comment]
> Well, we have .designer.cs, but we did not have to edit code there, even I guess many of the Windows Forms developers didn't even see the contents of the .designer.cs files ever.

@sim756 - while a capable designer sounds like a great productivity tool, if you've been around for a while, you might have worked on "legacy" codebases, where the designer has been broken and stopped working a few Visual Studio versions back, and you'd have to understand and edit thousands of lines in .designer.cs by hand. As making even the tiniest of changes (like aligning a button) in such codebases might take a day or two - all those productivity benefits get reconsidered. (Had those experiences with both WinForms and WebForms previously).

@dsyme talks about reliance on heavy tooling in [this talk about Fabulous](https://youtu.be/ZCRYBivH9BM?t=922) with a section dedicated to "The Problem with XAML". Even though Fabulous has lots of problems, it's hard to disagree with many of the points being raised.

**Comment by ehsangfl** [comment]
blazor binding has multiple tipps and issue
1- difference syntax between 1 way binding and two-way binding ( Value = @Value For one Way and Value-Changed = @Value for two-Way )
2- Binding does not support IValueConverter and we must convert values inline. and this is not good for reusing code.
3- we can control UI updates by INotifyPropertyChanged from viewmodel or model. but in blazor, this is done automatically and this  is an performance issue
please keep xaml alive with its designation
