### ISSUE TITLE
[Win UI] Slider throws an exception when trying to move the thumb

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#12405]
### Description

The bug occurs in the corner case when the `Maximum` and `Minimum` properties are set to the same value:

```xml
<Slider Maximum="100" Minimum="100" Value="100" />
```

When trying to move the thumb with the mouse, the following exception is thrown:

```
System.ArgumentException:
The value cannot be infinite or Not a Number (NaN).
```

There is no stack trace or additional info available.

Interestingly, when trying the same scenario in a pure Win UI application, no exception occurs. Perhaps, .NET MAUI uses a different implementation for the slider, that causes the bug to occur.

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Place a Slider in the main page:
```xml
<Slider Maximum="100" Minimum="100" Value="100" />
```
3. Build and run the application on Windows
4. Try to move the thumb with the mouse

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

N/A

**Comment by jfversluis** [comment]
+1 I've seen this one as well. I thought it was a WinUI bug, but seems not then!
