### ISSUE TITLE
App crashes in release with a specific Android code

### ISSUE THREAD

**Issue by PaulChek** [dotnet/maui#12407]
### Description

**VS** 17.5.33209.295
**MAUI**  7.0.100
**After update VS app crushes in release mode on Android with this code:**

```
public class MainActivity : MauiAppCompatActivity {
        protected override void OnCreate(Bundle savedInstanceState) {
            base.OnCreate(savedInstanceState);
#if !RELEASE
    Window.SetFlags(Android.Views.WindowManagerFlags.LayoutNoLimits,Android.Views.WindowManagerFlags.LayoutNoLimits);
            Window.ClearFlags(Android.Views.WindowManagerFlags.TranslucentStatus);
            Window.AddFlags(Android.Views.WindowManagerFlags.DrawsSystemBarBackgrounds);
#endif
        }
    }
```
Before update it works fine in both release and debug mode.

### Steps to Reproduce

1. Create MAUI Project
2. Add Code above

### Link to public reproduction project repository

[reproduction link](https://github.com/PaulChek/MauiBugFullscreen)

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android all

### Did you find any workaround?

Nope

### Relevant log output

```shell
**Some logs form adb:**
01-04 19:15:19.231  1297 18431 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 hwFlg=0x10 cmp=com.companyname.h2kmobileclient/crc64a4102369fd6cb8f0.MainActivity bnds=[360,874][528,1077] (has extras)} from uid 10058
01-04 19:15:19.233  1297 18431 I ActivityManager: ActivityRecord info: ActivityInfo{c435b54 crc64a4102369fd6cb8f0.MainActivity}
01-04 19:15:19.233  1297 18431 I ActivityManager: isNeedToStartExSplash requestCode: -1
01-04 19:15:19.233  1297 18431 I ActivityManager: isNeedToStartExSplash  callingPackage: com.huawei.android.launcher packageName: com.companyname.h2kmobileclient
01-04 19:15:19.291  1297  1440 I ActivityManager: Start proc 11340:com.companyname.h2kmobileclient/u0a228 for activity com.companyname.h2kmobileclient/crc64a4102369fd6cb8f0.MainActivity
--------- beginning of crash
01-04 19:15:19.499 11340 11340 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 11340 (h2kmobileclient), pid 11340 (h2kmobileclient)
01-04 19:15:19.610 11367 11367 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-04 19:15:19.610 11367 11367 F DEBUG   : Build fingerprint: 'HONOR/JAT-L21RU/HWJAT-M:9/HONORJAT-LX1/9.1.0.351C10:user/release-keys'
01-04 19:15:19.610 11367 11367 F DEBUG   : Revision: '0'
01-04 19:15:19.610 11367 11367 F DEBUG   : ABI: 'arm'
01-04 19:15:19.610 11367 11367 F DEBUG   : pid: 11340, tid: 11340, name: h2kmobileclient  >>> com.companyname.h2kmobileclient <<<
01-04 19:15:19.610 11367 11367 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-04 19:15:19.610 11367 11367 F DEBUG   :     r0  00000000  r1  00002c4c  r2  00000006  r3  00000008
01-04 19:15:19.610 11367 11367 F DEBUG   :     r4  00002c4c  r5  00002c4c  r6  ffd5b3c4  r7  0000010c
01-04 19:15:19.610 11367 11367 F DEBUG   :     r8  00000004  r9  c8afc5b4  r10 c8affa98  r11 c8affa84
01-04 19:15:19.610 11367 11367 F DEBUG   :     ip  ffd5b360  sp  ffd5b3b0  lr  ea86ac31  pc  ea862a7e
```

**Comment by mattleibow** [comment]
Can you try moving the code before the base.OnCreate() as that may be the issue.

**Comment by PaulChek** [comment]
> Can you try moving the code before the base.OnCreate() as that may be the issue.

Actually it was partial class but I simplify it for this

**Comment by PaulChek** [comment]
Is there some work around to achieve full screen mode on android?

**Comment by mattleibow** [comment]
Going to have a look and see if I can reproduce now...

**Comment by mattleibow** [comment]
I ran the attached sample in both release and debug and in both cases the app launches fine... Is this repo crashing for you? Maybe it is the specific device or emulator?

**Comment by PaulChek** [comment]
> I ran the attached sample in both release and debug and in both cases the app launches fine... Is this repo crashing for you? Maybe it is the specific device or emulator?

It crashes on two physical devices and on windows subsystem for Android(release) . Now I think may be it's conflict of different versions vs or maui installed on my pc

**Comment by PaulChek** [comment]
> I ran the attached sample in both release and debug and in both cases the app launches fine... Is this repo crashing for you? Maybe it is the specific device or emulator?

It works **fine** on   **VS 17.4.33205.214 and maui  7.0.52** for me, but **crushes** on **VS 17.5.33209.295 and 7.0.100** (info from **dotnet workload list** command)

**Comment by PaulChek** [comment]
@mattleibow Thank you for your help! I finally find out. 
1. Deploy my repo
2.  Change code in  MainActivity -> OnCreate method ( I added this string to existing code
Window.SetNavigationBarColor(Android.Graphics.Color.AliceBlue); )
4. Deploy once more in release. after this steps my app crashes
Clean solution each time  works for me.

**Comment by rachelkang** [comment]
@jonathanpeppers do you have any thoughts on this one?

**Comment by rachelkang** [comment]
@PaulChek Could you please update the sample repro with your latest code? Thanks :)

**Comment by jonathanpeppers** [comment]
I believe VS 17.4 and 17.5 have the exact same Android workload right now.

Is the problem that something goes wrong with an incremental build, and you need to `Clean` to fix it?
