### ISSUE TITLE
Compatibility HorizontalStackLayout does not constrain correctly 

### ISSUE THREAD

**Issue by bradencohen** [dotnet/maui#12415]
### Description

In Xamarin.Forms, if you used a horizontal stack layout, content would be constrained to the width of the screen. That is no longer the case in .NET MAUI. 

For example: 
 
```
<StackLayout Orientation="Horizontal">
    <Image
    Source="dotnet_bot.png"
    SemanticProperties.Description="Cute dot net bot waving hi to you!"
    HeightRequest="100" />

    <Label
    Text="This label would go to the next line in Xamarin.Forms. Now it cuts off."
    SemanticProperties.HeadingLevel="Level2"
    SemanticProperties.Description=""
    FontSize="18" />
</StackLayout>
```

Renders this:
![image](https://user-images.githubusercontent.com/11482832/210658045-ad4ab9a7-19e1-45ae-89b5-0a1d36948665.png)

While the exact same structure in Xamarin.Forms renders this:
```
<StackLayout Orientation="Horizontal">
    <Image Source="xamarin_logo.png" WidthRequest="100" />
    <Label
    Text="Since this horizontal stack layout is in Xamarin.Forms, it is constrained to the size of the screen."
    FontSize="18" />
</StackLayout>
```
![image](https://user-images.githubusercontent.com/11482832/210659073-d96736f6-af09-46af-83ef-acb312fd0cc8.png)

It seems that the width constraint of the stack layout is set to infinity, which seems wrong to me:
https://github.com/dotnet/maui/blob/main/src/Core/src/Layouts/HorizontalStackLayoutManager.cs#L30, but I'm not positive whether this is the exact source of the issue or not. 

This is a showstopper for us, since we use dynamically rendered XAML.

### Steps to Reproduce

1. Create a new MAUI project (or clone the repro project)
2. Insert the following snippet into the MainPage:
```
<StackLayout Orientation="Horizontal">
    <Image
    Source="dotnet_bot.png"
    SemanticProperties.Description="Cute dot net bot waving hi to you!"
    HeightRequest="100" />

    <Label
    Text="This label would go to the next line in Xamarin.Forms. Now it cuts off."
    SemanticProperties.HeadingLevel="Level2"
    SemanticProperties.Description=""
    FontSize="18" />
</StackLayout>
```
3. You can see that the label's content gets clipped off of the screen, although that behavior is completely different in Xamarin.Forms.

### Link to public reproduction project repository

https://github.com/bradencohen/HorizontalConstraintsMAUIBugDemo

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android API 31

### Did you find any workaround?

Currently, nothing that is production level. You can set the MaxWidthRequest of the StackLayout to be the exact width of the screen, but that is definitely a band-aid fix.

**Comment by bradencohen** [comment]
Similar issue: https://github.com/dotnet/maui/issues/8873

**Comment by Dreamescaper** [comment]
Apparently this is an expected behavior now.
The suggested approach is to use Grid instead with ColumnDefinitions="100, *".

**Comment by bradencohen** [comment]
What are we supposed to do to make this compatible then? I feel like it at least should be re-evaluated whether that is correct or not.

**Comment by bradencohen** [comment]
Some more comments on this: 
I verified the behavior on iOS, and I think it most likely represents the behavior on every platform.

I figured that using the [compatibility ](https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-7/#new-layouts) version of the control (Microsoft.Maui.Controls.Compatibility.StackLayout) would fix the issue, and it least get it to act like the Xamarin.Forms version, but the issue persists. Does the compatibility StackLayout still utilize the HorizontalStackLayoutManager in some capacity? 

This massively breaks horizontal StackLayouts, arguably one of the most used layouts when coming from Xamarin.Forms. Is it by design?

If that is the case and it is by design, I think it would be fair that the compatibility version behave as the Xamarin.Forms StackLayout does.

**Comment by bradencohen** [comment]
@hartez thanks so much! I think this:

> Create a [custom layout manager](https://github.com/hartez/CustomLayoutExamples#custom-layoutmanagers-for-existing-layouts) for StackLayout/HorizontalStackLayout. (Or a [pre-made custom layout](https://github.com/hartez/CustomLayoutExamples#custom-single-column-pre-made-layouts), if this is a common pattern you use in your applications.

is sufficient as an interim patch. As far as the compatibility StackLayout goes, that working as expected would still be the most desired fix. Thanks again!

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on android platform with above project. 
[HorizontalConstraints.zip](https://github.com/dotnet/maui/files/11673834/HorizontalConstraints.zip)
![Screenshot 2023-06-07 153340](https://github.com/dotnet/maui/assets/77434865/18cc7ac5-afe4-4768-8f0c-bd7c8c3b4263)

**Comment by varyamereon** [comment]
I can confirm that using `HorizontalOptions="StartAndExpand"` does work as mentioned above. These little quirks are very annoying and can't really understand how this could be conceived as the expected behaviour. If I set a label to wrap, it should wrap.

**Comment by bradencohen** [comment]
Closing because the original issue got skewed & this is expected behavior now. I pretty much use Grid everywhere.
