### ISSUE TITLE
SafeArea gets applied to any child controls even if you've disabled the safe area for the page

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#12417]
### Description

If you disable the SafeArea on a page it will correctly move the page up into the SafeArea. The problem is that any controls that should also occupy that same SafeArea get adjusted out of the SafeArea. 

```XAML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="WrapperViewSafeArea.MainPage"
             Title="MainPage"
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="False"
             >
    <Grid VerticalOptions="Start"  Background="Purple" RowDefinitions="*,Auto" MinimumHeightRequest="100"  HeightRequest="200" >
        <Button Text="Top" Background="Green"></Button>
        <Button Grid.Row="1" Text="Bottom" Background="Blue"></Button>
    </Grid>
</ContentPage>
```

### Steps to Reproduce

[WrapperViewSafeArea.zip](https://github.com/dotnet/maui/files/10347850/WrapperViewSafeArea.zip)

#### MAUI
![image](https://user-images.githubusercontent.com/5375137/210661006-d93851b9-2645-4489-8c2e-e7ba85088e4e.png)

#### FORMS
![image](https://user-images.githubusercontent.com/5375137/210661059-2f2b33d4-54ae-4f34-9def-a416e06ac729.png)

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by Gabrielnet9** [comment]
<Grid IgnoreSafeArea="True">

**Comment by FM1973** [comment]
Same problem

**Comment by ThomasBernard03** [comment]
> Same problem
Try [Gabrielnet9](https://github.com/Gabrielnet9) soltuion, it work for me

**Comment by RobTF** [comment]
Same issue, currently blocked.

**Comment by hartez** [comment]
In MAUI, layouts are safe-area aware, just like pages. (This is partly to give greater layout flexibility, and partly to support Comet, which doesn't have Page).

By default Layouts will confine themselves to the safe area; if you want them to have access to the danger zone, you can set the `IgnoreSafeArea` property:

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="WrapperViewSafeArea.MainPage"
             Title="MainPage"
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="False"
             >
    <Grid IgnoreSafeArea="True" VerticalOptions="Start"  Background="Purple" RowDefinitions="*,Auto" MinimumHeightRequest="100"  HeightRequest="200" >
        <Button Text="Top" Background="Green"></Button>
        <Button Grid.Row="1" Text="Bottom" Background="Blue"></Button>
    </Grid>
</ContentPage>
```

**Comment by yunusefendi52** [comment]
> In MAUI, layouts are safe-area aware, just like pages.

Is there a toggle switch to ignore this behavior? I am porting xf app and would safe area behavior the same as xf

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on iOS 16.4 with below Project:
[WrapperViewSafeArea.zip](https://github.com/dotnet/maui/files/11743273/WrapperViewSafeArea.zip)

**Comment by borrmann** [comment]
@hartez what is the reason for having UseSafeArea and IgnoreSafeArea? Or at least, why is IgnoreSafeAre="False" the default? 
When the page doesn't use the Danger Zone, all Layouts are outside the Danger Zone anyways, right?
If I define on my page that I want to use the Danger Zone, then it should mean the Layouts shouldn't ignore the Danger Zone by Default as @MichalJan008 showed.

The problem I have is, IgnoreSafeAre can't be set in a Style (or I couldn't figure out how) and for instance also doesn't work on ScrollViews. 
This means, if I don't manually set IgnoreSafeArea="False", I have inconsistent UI across the App. when I use Layouts with and without this property and also have all pages set to UseSafeArea="True". 

On another note, for simpler use, IMHO the property should also be named differently like UseDangerZone or again, UseSafeArea to avoid double negations.

**Comment by Felicity-R** [comment]
> Is there a toggle switch to ignore this behavior? I am porting xf app and would safe area behavior the same as xf

I haven't tested it yet, but perhaps one option would be to set IgnoreSafeArea=true in the LayoutHandler so it will apply to all layouts. Like so:

```
LayoutHandler.Mapper.AppendToMapping("Custom", (h, v) =>
            {
                if (v is Layout layout)
                {
                    layout.IgnoreSafeArea = true;
                }
            });
```
