### ISSUE TITLE
Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools'

### ISSUE THREAD

**Issue by tsrancsik** [dotnet/maui#12410]
### Description

I ran into [this issue](https://github.com/dotnet/maui/issues/11339) which is supposed to be solved. `Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools'.`

### Steps to Reproduce

1. Install Visual Studio 2022 for Mac (17.4.2 (build 17)) with Maui, iOS, and Android.
2. Install xcode-cli `xcode-select --install`.
3. Create a new Maui project with dotnet 7.0 and build it.

### Link to public reproduction project repository

...

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Ventura 13.1

### Did you find any workaround?

No. The formerly suggested reset does not work.

**Comment by VladislavAntonyuk** [comment]
Change the path to XCode in VS settings.
