### ISSUE TITLE
Android enterprise - work profile - app crash, no possibility  to run and debug

### ISSUE THREAD

**Issue by LukasKuchta** [dotnet/maui#12427]
### Description

Hi, we have app for Android runs under Android enterprise. It is diffrent device user that normal profile. 

normal user has id 0 and enterprise user obviously 10

csproj has **<LaunchFlags>--user 10</LaunchFlags>** element

When we traying to debug app from VS app crashes without error. Only 
`"'No assemblies found in '/data/user/10/com.companyname.app/files/.__override__' or '<unavailable>'. Assuming this is part of Fast Deployment. Exiting...'"`

It is possible to run and debug MAUI app under work profile? It seems any dlls missing in workprofile. Copy is probably exists in normal profile but it is not possible to access tham from work profile.

### Steps to Reproduce

Run android app under work profile / android enterprise

### Link to public reproduction project repository

https://github.com/LukasKuchta/MauiContextMenu

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android independent

### Did you find any workaround?

no

**Comment by rachelkang** [comment]
@jonathanpeppers any ideas for this one?

**Comment by jonathanpeppers** [comment]
This might have some details: https://github.com/xamarin/xamarin-android/commit/7b51fd1b45f7f315df402ba333e141a49c8a3ca7

Docs: https://learn.microsoft.com/xamarin/android/deploy-test/building-apps/build-properties#androiddeviceuserid

If you set `<AndroidDeviceUserId>10</AndroidDeviceUserId>` in your `.csproj`, does that work?

/cc @dellis1972 if you still have an issue after trying that.

**Comment by LukasKuchta** [comment]
@jonathanpeppers  thanks this flag helps. But 

- Visual Studio for Mac 17.4.2 (build 17). - no debug session is attached, application is installed for correct profile and run by user tapped on icon
- Version 17.5.0 Preview 2.0 Windows - works fine

It seems that is problem in VS and MAC version. Next build for mac can fixed this issue

**Comment by jonathanpeppers** [comment]
@mattleibow what do we do to route this to Xamarin extension for VS Mac? Seems like this works on Windows and not Mac, and works command-line.
