### ISSUE TITLE
Azure Pipelines Ios Maui: code object is not signed at all

### ISSUE THREAD

**Issue by Zack158** [dotnet/maui#12430]
### Description

I am trying to run an Azure Pipeline to publish a .Net Maui project on ios, but keep getting the following error

  **/Users/runner/work/1/s/src/appName/bin/Release/net7.0-ios/ios-arm64/appname.app: code object is not signed at all
  In subcomponent: /Users/runner/work/1/s//src/appName/bin/Release/net7.0-ios/ios-arm64/appName.app/System.Security.Cryptography.aotdata.arm64**

However, the pipeline installs the apple certificates and provisioning profiles etc fine with no errors so I’m not sure why it thinks the code object is not signed?

Here is the pipeline:
  

stages:
- stage: Build_Dev_Only
  jobs:
  - job: 'BuildDevApp'
    displayName: 'Build Maui iOS Dev'
    timeoutInMinutes: 120
    pool:
      vmImage: 'macOS-12'

    steps:
    
     # Install Certificate        
    - task: InstallAppleCertificate@2
      displayName: 'Install an Apple certificate $(AppleCertificateP12) '
      inputs:
        certSecureFile: $(AppleCertificateP12)
        certPwd: ''
        keychain: 'temp'

    # Install provisioning profile
    - task: InstallAppleProvisioningProfile@1
      displayName: 'Install an Apple provisioning profile $(AppleDEVAdhocProvisioningProfile)'
      inputs:
        provProfileSecureFile: $(AppleDEVAdhocProvisioningProfile)

    - task: UseDotNet@2
      displayName: .NET Version
      inputs:
        packageType: 'sdk'
        version: '$(DotNetVersion)' 
        includePreviewVersions: true
    
    - task: Bash@3
      displayName: Install MAUI
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear 
          dotnet workload install maui 
          dotnet workload install ios 
    
    # Print all the variables
    - task: Bash@3
      displayName: Print out all the parameters
      inputs:
          targetType: 'inline'
          script: |
            echo 'vmImage - 'macOS-12'
            echo 'nugetVersion - $(NugetVersion)
            echo 'solutionPath - $(iOSSolutionPath)
            echo 'packageName - $(PackageNameDev)
            echo 'appLabel - $(AppLabelDev)
            echo 'versionCodeOffset - $(iOSVersionCodeOffset)
            echo 'appleCertificateP12 -$(AppleCertificateP12)'
            echo 'appleProvisioningProfile - $(AppleDEVAdhocProvisioningProfile)'
            echo 'infoListPath - $(iOSinfoListPath)'
            echo 'majorMinorVersionName - $(iOSMajorMinorVersionName)'
            echo 'iOSBuildVersionFolder in bootstrapsettings Ver_iOS_$(iOSMajorMinorVersionName).$(Build.BuildId)'
            echo 'system working directory - $(system.defaultworkingdirectory)'

    - task: Bash@3
      displayName: Restore nuget
      inputs:
        targetType: 'inline'
        script: |
          cd src/
          dotnet restore appName.sln
 
    - task: DotNetCoreCLI@2
      displayName: 'Build iOS app'
      inputs:
          command: 'publish'
          publishWebProjects: false
          zipAfterPublish: false
          projects: src/app/appName.csproj'
          arguments: '-c Release -f net7.0-ios -o $ (build.artifactstagingdirectory) /p:RuntimeIdentifier=ios-arm64 /p:BuildIpa=true /p:Codesignkey="$(APPLE_CERTIFICATE_SIGNING_IDENTITY)" /p:CodesignProvision="$(APPLE_PROV_PROFILE_UUID)"'

### Steps to Reproduce

Create a maui ios app and try to publish it using azure pipelines with the pipeline code above.

### Link to public reproduction project repository

https://github.com/Zack158/MAUIiOSDevops

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 16

### Relevant log output

```shell
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.1.1481/tools/msbuild/iOS/Xamarin.Shared.targets(2128,3): error : /usr/bin/codesign exited with code 1: [/Users/runner/work/1/s/src/appName/appName.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.1.1481/tools/msbuild/iOS/Xamarin.Shared.targets(2128,3): error : /Users/runner/work/1/s/src/appName/bin/Release/net7.0-ios/ios-arm64/appName.app: code object is not signed at all [/Users/runner/work/1/s/src/appName/appName.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.1.1481/tools/msbuild/iOS/Xamarin.Shared.targets(2128,3): error : In subcomponent: /Users/runner/work/1/s/src/appName/bin/Release/net7.0-ios/ios-arm64/appName.app/System.Security.Cryptography.aotdata.arm64 [/Users/runner/work/1/s/src/appName/appName.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.1.1481/tools/msbuild/iOS/Xamarin.Shared.targets(2128,3): error : Failed to codesign '/Users/runner/work/1/s/src/appName/bin/Release/net7.0-ios/ios-arm64/appName.app': /Users/runner/work/1/s/src/appName/bin/Release/net7.0-ios/ios-arm64/appName.app: code object is not signed at all [/Users/runner/work/1/s/src/appName/appName.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.1.1481/tools/msbuild/iOS/Xamarin.Shared.targets(2128,3): error : In subcomponent: /Users/runner/work/1/s/src/appName/bin/Release/net7.0-ios/ios-arm64/appName.app/System.Security.Cryptography.aotdata.arm64 [/Users/runner/work/1/s/src/appName/appName.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.1.1481/tools/msbuild/iOS/Xamarin.Shared.targets(2128,3): error :  [/Users/runner/work/1/s/src/appName/appName.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.1.1481/tools/msbuild/iOS/Xamarin.Shared.targets(2128,3): error :          [/Users/runner/work/1/s/src/appName/appName.csproj::TargetFramework=net7.0-ios]
```

**Comment by rachelkang** [comment]
This issue was moved to xamarin/xamarin-macios#17153
