### ISSUE TITLE
WPF Blazor Rendering Runtime Error Plus Hidden Bug

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#1244]
I have a custom toast component that I created.  Works perfectly in web assembly but when using from blazor desktop wpf, it has one hidden bug and one runtime error.

The hidden bug is the popup does not go away when it was supposed to.   Even webassembly, that worked perfectly.

However, the runtime error is when I try to close out of the popup from wpf, it gives a render runtime error.   Happens everytime.
However, when running the same thing from web assembly, no problems.  This means there is one case where something works even on web assembly that does not work properly on desktop.  I hope this problem can be fixed.  Here is my repository to show this.
https://github.com/musictopia2/RenderingProblemSolution 

It would be really disappointing if there ends up being cases where something works from webassembly but not from blazor desktop or even future mobile.

**Comment by musictopia2** [comment]
I can tell you for sure that this bug went away as of .net 6 preview 7.  When I reported it, I ended up working around by using WPF specific stuff to create a toast like.  However, when I saw a future preview fixed the problem, then I did not need that workaround anymore.

**Comment by VincentBu** [comment]
Ok, I will close it. If you run into the same bug again, feel free to open a new issue.
