### ISSUE TITLE
Version conflict detected for `Microsoft.Extensions.DependencyInjection.Abstractions` [NU1107]

### ISSUE THREAD

**Issue by nor0x** [dotnet/maui#12463]
### Description

I have created a new .NET MAUI project in Visual Studio 17.5.0 Preview 2.0 and didn't modify any code. When i try to build the application i get the following error:

```
1>C:\Users\jo\MauiTests\MauiApp3\MauiApp3.csproj : warning NU1603: Microsoft.Extensions.DependencyInjection 7.0.0 depends on Microsoft.Extensions.DependencyInjection.Abstractions (>= 7.0.0) but Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0 was not found. An approximate best match of Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0-rc.1.22426.10 was resolved.
1>C:\Users\jo\MauiTests\MauiApp3\MauiApp3.csproj : warning NU1603: Microsoft.Extensions.Logging 7.0.0 depends on Microsoft.Extensions.DependencyInjection.Abstractions (>= 7.0.0) but Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0 was not found. An approximate best match of Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0-rc.1.22426.10 was resolved.
1>C:\Users\jo\MauiTests\MauiApp3\MauiApp3.csproj : warning NU1603: Microsoft.Extensions.Logging.Debug 7.0.0 depends on Microsoft.Extensions.DependencyInjection.Abstractions (>= 7.0.0) but Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0 was not found. An approximate best match of Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0-rc.1.22426.10 was resolved.
1>C:\Users\jo\MauiTests\MauiApp3\MauiApp3.csproj : error NU1107: Version conflict detected for Microsoft.Extensions.DependencyInjection.Abstractions. Install/reference Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0-rc.1.22426.10 directly to project MauiApp3 to resolve this issue. 
1>C:\Users\jo\MauiTests\MauiApp3\MauiApp3.csproj : error NU1107:  MauiApp3 -> Microsoft.Extensions.Logging.Debug 7.0.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 7.0.0) 
1>C:\Users\jo\MauiTests\MauiApp3\MauiApp3.csproj : error NU1107:  MauiApp3 -> Microsoft.Extensions.DependencyInjection 7.0.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 7.0.0).
1>    3 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:00.11
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 10:48 AM and took 01,140 seconds ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Deploy started at 10:48 AM and took 01,140 seconds ==========
```

![image](https://user-images.githubusercontent.com/3210391/210976316-7b184da1-505e-4802-91f4-e1ed4bf22c22.png)

This only happens on one of my Windows machines, so i guess something is messed up on my side. I suspect an outdated workload or so, since error states the RC version (7.0.0-rc.1.22426.10) of Microsoft.Extensions.DependencyInjection.Abstractions.

This is annoying but it's not a blocker for me and can be fixed by manually installing Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0
`<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />`

here is my `dotnet workload list`

```shell
Installed Workload Id      Manifest Version       Installation Source
--------------------------------------------------------------------------------
wasm-tools                 7.0.1/7.0.100          SDK 7.0.100, VS 17.5.33209.295
maui-windows               7.0.52/7.0.100         VS 17.5.33209.295
maui-maccatalyst           7.0.52/7.0.100         VS 17.5.33209.295
maccatalyst                16.1.1481/7.0.100      VS 17.5.33209.295
maui-ios                   7.0.52/7.0.100         VS 17.5.33209.295
maui-android               7.0.52/7.0.100         VS 17.5.33209.295
android                    33.0.4/7.0.100         VS 17.5.33209.295
ios                        16.1.1481/7.0.100      VS 17.5.33209.295

Use `dotnet workload search` to find additional workloads to install.
```

### Steps to Reproduce

1. Create New .NET MAUI project
2. Build it

### Link to public reproduction project repository

.

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

adding
`<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />`

to the csproj fixes the issue for me

**Comment by mattleibow** [comment]
Something is happening with your nuget cache. Can you try clearing it?

This error message:

> warning NU1603: ...  Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0 was not found. 

seems to indicate that the cache is corrupted.

**Comment by nor0x** [comment]
> Something is happening with your nuget cache. Can you try clearing it?
> 
> This error message:
> 
> > warning NU1603: ...  Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0 was not found.
> 
> seems to indicate that the cache is corrupted.

thank you! clearing the NuGet cache helped
