### ISSUE TITLE
ShellContent.IsEnabled = false

### ISSUE THREAD

**Issue by sretz** [dotnet/maui#12478]
### Description

Even though I have set the flyout menu item IsEnabled to false, it is clickable and tries to display the content which is null. In addition the program is mostly generated by the default template, runs on android but not windows (which I have no idea why).

### Steps to Reproduce

1. Download https://github.com/sretz/Reproduce.ShellContentIsEnabled
2. run on android
3. on menu click Disabled

### Link to public reproduction project repository

https://github.com/sretz/Reproduce.ShellContentIsEnabled

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Andriod Pixel 5 - API 30 (Andriod 11), Windows10.0.19041.0

### Did you find any workaround?

no

**Comment by XamlTest** [comment]
@sretz The project you provided is not found now, could you attach a sample project again?
