### ISSUE TITLE
Blazor Maui Listening on public port, access is denied

### ISSUE THREAD

**Issue by Grizor1911** [dotnet/maui#12475]
HttpListener works with http://127.0.0.1:8083 prefix but not with http://+:8083. An error "access is denied" appears in the console.

The same code in Console Application is working. Tried admin permission and other ports.

Is Blazor Maui limited in this sense like Blazor wasm ? If yes, is there a list of limited features ?

Sample code:

```c#
		string[] prefixes = { "http://+:8083/" };
		if (prefixes == null || prefixes.Length == 0)
			throw new ArgumentException("prefixes");

		// Create a listener.
		HttpListener listener = new HttpListener();
		// Add the prefixes.
		foreach (string s in prefixes)
		{
			listener.Prefixes.Add(s);
		}
		listener.Start();
		Console.WriteLine("Listening...");
		// Note: The GetContext method blocks while waiting for a request.
		HttpListenerContext context = listener.GetContext();
		HttpListenerRequest request = context.Request;
		// Obtain a response object.
		HttpListenerResponse response = context.Response;
		// Construct a response.
		string responseString = "<HTML><BODY> Hello world!</BODY></HTML>";
		byte[] buffer = System.Text.Encoding.UTF8.GetBytes(responseString);
		// Get a response stream and write the response to it.
		response.ContentLength64 = buffer.Length;
		System.IO.Stream output = response.OutputStream;
		output.Write(buffer, 0, buffer.Length);
		// You must close the output stream.
		output.Close();
		listener.Stop();
```

**Comment by Eilon** [comment]
@Grizor1911 can you share more info about where you put this code and what happened? What platform was this running on? How is there a console if this is a .NET MAUI app (which are always GUI apps)?

In general HttpListener should work the same as it does in any other app type _on the same platform_. It's possible that HttpListener isn't supported on some platforms (let's say for example Android), in which case it wouldn't work in .NET MAUI on Android. But on Windows where I know HttpListener works, it should work exactly the same way.

**Comment by Grizor1911** [comment]
Thanks for answering. I meant that the same code in a .NET 7 Console application works correctly, on the same computer. Platform is Windows 11, 64 bits.

This is the error in the developer console:
blazor.webview.js:1 
        
   Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at BlazorMauiExample.Pages.Index.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()




Full code in Blazor Maui, could you reproduce it, please:

@page "/"

@using System.Net;

<h1>Hello, world!</h1>

@code {

    protected override async Task OnInitializedAsync()
    {
        HttpListener listener = new HttpListener();
        listener.Prefixes.Add("http://*:8083/");
        listener.Start();
        Console.WriteLine("Listening...");

        while (true)
        {
            // Wait for a client to connect asynchronously
            HttpListenerContext context = await listener.GetContextAsync();
            HttpListenerRequest request = context.Request;
            // Obtain a response object
            HttpListenerResponse response = context.Response;
            string responseString = "Hello World!";
            // Construct a response
            byte[] buffer = System.Text.Encoding.UTF8.GetBytes(responseString);
            // Get a response stream and write the response to it
            response.ContentLength64 = buffer.Length;
            System.IO.Stream output = response.OutputStream;
            await output.WriteAsync(buffer, 0, buffer.Length);
            // You must close the output stream
            output.Close();
        }
   }

**Comment by Eilon** [comment]
@Grizor1911 thank you for the info we'll take a look!

**Comment by Eilon** [comment]
Hi, this is caused by an aspect of HttpListener requiring admin elevation to accept requests on all hostnames. Learn more here: https://stackoverflow.com/questions/4019466/httplistener-access-denied

After using one of the suggestions on that post, I set the listener address to be `http://localhost:8083/` (without using `*`), and then it worked fine:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/202643/224445116-49bdedf4-b3d7-4ec3-8eba-a7448631eb6a.png">

**Comment by Grizor1911** [comment]
Tried with Windows admin user and executing visual studio as admintrator. The same error appears. I would like to listen for all prefixes, not only localhost as I can do it in a console application with HTTPListener. 

I readed the post you commented but I don't want to grand permisions with netsh. It would be nice if HTTPListener would work like in a console application.

**Comment by Eilon** [comment]
I get the exact same behavior in a console app. If I use `*` then I get Access is denied:

![image](https://user-images.githubusercontent.com/202643/224449191-3e756c4f-621a-4101-af8b-f60864c318ad.png)

And if I use `localhost` then it works:

![image](https://user-images.githubusercontent.com/202643/224449393-e95ff71b-a799-47d4-90fb-3a0405443c70.png)

I think this is behavior of the Windows operating system where those types of addresses can't be used without Admin elevation.

**Comment by Grizor1911** [comment]
I just know that the same code in console app works but in Blazor it doesn't and I didn't need to elevate permissions with my admin user. Maybe it's some weird configuration. In any case, thanks for responding!

**Comment by Eilon** [comment]
I did try in a regular console app and the behavior was exactly the same as a .NET MAUI app running on Windows. Are you certain that the console app is _not_ elevated?
