### ISSUE TITLE
Editors not scrollable on iOS/Catalyst

### ISSUE THREAD

**Issue by tj-devel709** [dotnet/maui#12485]
### Description

When using an editor control on iOS (simulator and device) or MacCatalyst, the editor content is not scrollable.
The scroll bar appears on the right side of the editor, but it does not allow you to scroll. 

On iOS, the editor is derived from the UITextView class and it appears that the UITextView's base class UIScrollView has the `ScrollEnabled == true` so something else must be going on.

The issue also occurs on .NET 6 Maui project for iOS and Catalyst.

The editor worked correctly on Android. It also worked as expected on iOS when adding the UITextView through Xcode and on iOS through Xamarin Forms. 

### Steps to Reproduce

1. Create a new Maui App
2. Add an editor control
3. Deploy to an iOS device/sim
4. Add multiple lines of text to the editor
5. Try to scroll up and down

### Link to public reproduction project repository

https://github.com/tj-devel709/MauiEditorBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

No workarounds found

**Comment by ShadowOfPhantom** [comment]
Same here

**Comment by tj-devel709** [comment]
Edit: scrolling works on iOS through Xamarin.Forms! Reflected in the original issue description.
