### ISSUE TITLE
[Bug] dotnet-build sometimes does not emit executable file to .app/Contents/MacOS

### ISSUE THREAD

**Issue by yamachu** [dotnet/maui#1248]
### Description

Even if you build a maui-blazor app for net6.0-maccatalyst, it may not output an executable file.
If you build the same code several times, a file that cannot be executed suddenly will be output, and even if you do dotnet-clean etc. and build again, the file that can be executed will not be output.
This also happened in the project created in a way `dotnet new maui-blazor`.

### Steps to Reproduce

1. Following https://github.com/dotnet/maui/wiki/Getting-Started steps.
2. Build and run...
3. Some code change and revert...

### Expected Behavior

Output executable files

### Actual Behavior

In case of build https://github.com/yamachu/MAUICameraSetting 

> open bin/Debug/net6.0-maccatalyst/maccatalyst-x64/MAUICameraSetting.app
>         The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3762, _LSFunction=_LSOpenStuffCallLocal}

### Basic Information

- Version with issue: preview-4 and preview.5.764
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: macOS BigSur 11.4

- Xcode: Version 12.5 (12E262)
- dotnet: 6.0.100-preview.4.21255.9

### Screenshots

<img width="677" alt="スクリーンショット 2021-06-11 4 32 10" src="https://user-images.githubusercontent.com/1955233/121585859-068c3f80-ca6e-11eb-8c5f-65dcb8edd616.png">

### Reproduction Link

https://github.com/yamachu/MAUICameraSetting

### Workaround

I haven't found it.
NG: copy project directory to another directory, then build and run
NG: clone this repo, then build and run
NG: use other bundle ID, then build and run
NG: rebuild LaunchServices database with command: `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user` (This doesn't seem to matter :(

I've tried Build several times, but once this happened, the project has never been successfully built again...

maybeRef: https://github.com/dotnet/maui/issues/1175

**Comment by rolfbjarne** [comment]
Please get the binlog of a build that doesn't produce an executable and attach it here.

You can get a binlog by executing `dotnet build /bl` - this will produce `msbuild.binlog`, which is the file we need to diagnose this.

**Comment by yamachu** [comment]
Thank you for investigating.
Now I built bellow link application with command `dotnet build -bl -f net6.0-maccatalyst MAUICameraSetting` and got binlog file.
https://github.com/yamachu/MAUICameraSetting/commit/a50c80784af77f9918f7792cc6d85ca5e877f713

Here is zipped binlog file
[msbuild.binlog.zip](https://github.com/dotnet/maui/files/6650249/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
Thanks!

This issue has already been fixed, and the fix will be included in the next preview (preview 5).

**Comment by yamachu** [comment]
I tried Microsoft.Maui/6.0.100-preview.5.798 
Just upgrading to it didn't work, but I deleted `<PublishTrimmed Condition="'$(CONFIGURATION)' == 'Debug'">False</PublishTrimmed>` I was adding for accelerating build speed,  it worked perfectly!

Thanks
