### ISSUE TITLE
Blazor Web integration with MAUI / RCL / MAUI Class Library

### ISSUE THREAD

**Issue by Pinox** [dotnet/maui#12489]
### Description

I would luv to see the following to be included with .NET 8 planning.

A truly unified UI project that includes all the device form factors including Web in one project.

![image](https://user-images.githubusercontent.com/5297255/211152014-948fc877-da75-43ba-96fa-9ef5e52ea655.png)

The above project structure would be truly awesome as we can then use Blazor Server for fast iteration , Blazor WASM for web deployment and MAUI to extend web assets to native platforms.

Another pain point at the moment using Blazor is the fact that you can't centralize your UI assets in a Razor Class Library including the wwwroot folder.  When trying to centralize the wwwroot folder in the RCL for all projects I got various errors and there is also a couple of issues logged regarding this online.  So even with the current project structure of MAUI / Blazor Server and Blazor WASM the following should have been possible but it's not.

![image](https://user-images.githubusercontent.com/5297255/211150385-84ae78fd-4768-4380-b439-167d8d44d472.png)

Extending the above idea into the MAUI class library with a wwwroot folder would be really great., therefor this becomes a MAUI Razor Class Library hybrid.

![image](https://user-images.githubusercontent.com/5297255/211157785-a69f9746-31cb-4157-9a94-2bc6a1a56627.png)

Note the inclusion of the wwwroot folder in the MAUI Class Library.

This feature compliments the existing request already filed at:
https://github.com/dotnet/maui/issues/1069

### Public API Changes

n/a

### Intended Use-Case

Unified Blazor project structure.

**Comment by affableashish** [comment]
I absolutely love this proposal!
Hope it comes in .NET 8.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is something we are investigating as part of https://github.com/dotnet/maui/issues/1069.
Please upvote the linked issue.
