### ISSUE TITLE
Shell Tabbar visibility bug on Windows

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#12499]
### Description

If you set Shell.TabBarIsVisible to false this is not respected on Windows but at a later time on a different page the tabbar is hidden where it should not be hidden

### Steps to Reproduce

- Start the app on Windows
- Click Events in tabbar
- Click Go to details page button
- You are on the detail page -> the tabbar is still visible but should not
- Click Dumm1 on tabbar
- Click Events in tabbar -> you are on the event details page now but the tabbar is gone. You can click back so you are on the event page but still the tabbar is not visible and you have to close app since you cannot navigate any more

### Link to public reproduction project repository

https://github.com/rogerbriggen/Maui_sHell/tree/TabbarVisibilityBugWindows

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 22H2

### Did you find any workaround?

https://github.com/dotnet/maui/issues/12499#issuecomment-1650654570

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11 with below Project:
[sHellDemo.zip](https://github.com/dotnet/maui/files/11744297/sHellDemo.zip)
![tabbar](https://github.com/dotnet/maui/assets/97647558/70b69f3f-1b89-4d71-9145-c595ff1e608e)

**Comment by MegaEgorik** [comment]
I managed to fix this problem with this code:
`public static void SetTabBarVisibility(in Page page, in bool value)
 {
        if (Shell.Current.CurrentItem.Items.Count > 1)
        {
            Shell.SetTabBarIsVisible(page, value);
            ShellSection currentSection = Shell.Current.CurrentItem.CurrentItem;
            Shell.Current.CurrentItem.CurrentItem = null;
            Shell.Current.CurrentItem.CurrentItem = currentSection;
        }
}`
Call `SetTabBarVisibility(somePage, false)` to hide the TabBar, and call `SetTabBarVisibility(somePage, true)` to return the TabBar

**Comment by unombun** [comment]
> I managed to fix this problem with this code:
> 
> ```cs
> public static void SetTabBarVisibility(Page page, bool value)
> { 
>     if (Shell.Current.CurrentItem.Items.Count > 1)
>     {
>         Shell.SetTabBarIsVisible(page, value);
>         ShellSection currentSection = Shell.Current.CurrentItem.CurrentItem;
>         Shell.Current.CurrentItem.CurrentItem = null;
>         Shell.Current.CurrentItem.CurrentItem = currentSection;
>     }
> }
> ```
> 
> Call `SetTabBarVisibility(somePage, false)` to hide the TabBar, and call `SetTabBarVisibility(somePage, true)` to return the TabBar

Where exactly do you call this SetTabBarVisibility method?
I called in Constructor of the page -> it does not work. 
I called in OnAppearing  -> the app crashes.

**Comment by MegaEgorik** [comment]
> 

I call these methods in constructor of page. These methods work great for me. You may be using TabbedPage and it's causing your app to crash because this code only works if you use

**Comment by MegaEgorik** [comment]
> 
> Where exactly do you call this SetTabBarVisibility method? I called in Constructor of the page -> it does not work. I called in OnAppearing -> the app crashes.

Perhaps your application crashes due to the fact that you are not using FlyoutItem. Just put all your tabs in FlyoutItem and maybe the app won't crash.

**Comment by MegaEgorik** [comment]
This example showing how my workaround works:
![image](https://github.com/dotnet/maui/assets/97403611/91d594d4-6a35-45d4-86ca-c0d1f87c4c5d)
![image](https://github.com/dotnet/maui/assets/97403611/3609d889-1ada-4442-8cb0-14053182f2fd)
![image](https://github.com/dotnet/maui/assets/97403611/c66c1c6d-1ec1-47b9-bf5e-a73e4c7f7e1c)

https://github.com/dotnet/maui/assets/97403611/0b73d1a6-1c83-4ad5-9cfb-ccee9fc52acc

**Comment by unombun** [comment]
> This example showing how my workaround works: ![image](https://user-images.githubusercontent.com/97403611/259453181-91d594d4-6a35-45d4-86ca-c0d1f87c4c5d.png) ![image](https://user-images.githubusercontent.com/97403611/259453274-3609d889-1ada-4442-8cb0-14053182f2fd.png) ![image](https://user-images.githubusercontent.com/97403611/259453412-c66c1c6d-1ec1-47b9-bf5e-a73e4c7f7e1c.png)
> 2023-08-09.18-03-11.mp4

I re-tried your workaround with the updated steps. Yes, it works, but this can be applied only with basic navigation. When you have more complex navigation with multiple back steps and/or replacement of pages from the navigation stack, it becomes like impossible to use

**Comment by MegaEgorik** [comment]
> I re-tried your workaround with the updated steps. Yes, it works, but this can be applied only with basic navigation. When you have more complex navigation with multiple back steps and/or replacement of pages from the navigation stack, it becomes like impossible to use

So what exactly is your problem? 
My workaround forces the TabBar to update, so you can easily call this code at any time to update the TabBar:
```C#
ShellSection currentSection = Shell.Current.CurrentItem.CurrentItem;
Shell.Current.CurrentItem.CurrentItem = null;
Shell.Current.CurrentItem.CurrentItem = currentSection;
```
You can subscribe to OnAppearing or OnBackButtonPressed events and then every time you return to the previous page the TabBar will be updated

**Comment by unombun** [comment]
> > I re-tried your workaround with the updated steps. Yes, it works, but this can be applied only with basic navigation. When you have more complex navigation with multiple back steps and/or replacement of pages from the navigation stack, it becomes like impossible to use
> 
> So what exactly is your problem? My workaround forces the TabBar to update, so you can easily call this code at any time to update the TabBar:
> 
> ```cs
> ShellSection currentSection = Shell.Current.CurrentItem.CurrentItem;
> Shell.Current.CurrentItem.CurrentItem = null;
> Shell.Current.CurrentItem.CurrentItem = currentSection;
> ```
> 
> You can subscribe to OnAppearing or OnBackButtonPressed events and then every time you return to the previous page the TabBar will be updated

I re-tested the workaround and by modifying it a little bit it worked in our navigation system
