### ISSUE TITLE
[iOS] App exceptions on physical device, but works on the simulator

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#12503]
### Description

I was facing a strange behaviour of my app. It was working fine while running on the simulator.
However once I moved to a physical device (iPhone in my case), the app throws exceptions and crashes.

After a while I figured out, that a missing `StaticResource`, better a missing style, was the issue.

> System.Reflection.TargetInvocationException: Position 165:45. StaticResource not found for key DefaultBorderlessEntry

```xaml
Style="{StaticResource DefaultBorderlessEntry}"
```

It would have saved me a lot of headache if the Simulator would also throw an exception if a `StaticResource` is not found.
Is there a way to adjust this?

### Steps to Reproduce

1. Already fixed

### Link to public reproduction project repository

none

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

16

**Comment by jfversluis** [comment]
@StephaneDelcroix seems like something you might know more about?

**Comment by AndreasReitberger** [comment]
It would be even more awesome if the build task already sees that the `StaticResource` is not found. Like it works with `CompiledBindings`.
https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 1.0 and 17.6.7 (build 417). Not repro on iOS platform.
