### ISSUE TITLE
Poor performance in debug mode under iOS and Android

### ISSUE THREAD

**Issue by UweFuchsPit** [dotnet/maui#12508]
### Description

We tested our attached spike under Windows, iOS and Android. In Debug-Mode the performance running on Windows is quite ok, despite a similar App created with Xamarin is much faster. But debugging under iOS and Android is unbelievable slow. Maybe the reason is the interpreter, disabling Hot-Reload in the settings has no effect, even put UseInterpreter=false in the project file didn't improve the performance. If the problem is really the interpreter we can't understand the difference to windows, where the interpreter works obviously much better. Is there a possibility to disable hot reload?
An other problem is that the app get's slower if we add more views via an BindableLayout.ItemsSource bound ObservableCollection into for instance a grid. The more views we add the longer it takes the new view appears.
After adding and removing some views we still found viewmodels and views left in the diagnostic tools (even calling the garbage-collector has no effect), maybe there are also some memory leak issues.

### Steps to Reproduce

1. Run attached spike app
2. in the topbar you find some buttons to add views to an bound collection, the back-button removes the last view from the collection
3. the more views you add the more time it takes to appear, also pressing back is slower if more views are bound via the ObservableCollection to a BindableLayout.ItemsSource

In this spike the difference between  iOS and Windows is not that significant like in our real app where much more bound views are included, where opening a next 'step' sometimes takes nearly a minute to finish.

If you open a grid with clicking the 'Entity Grid' Button and then rotate the device relayouting is very slow too

### Link to public reproduction project repository

https://github.com/pitMobile/maui-perfomance-issue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 16.1, Android 10, Windows 11

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by jonathanpeppers** [comment]
@jsuarezruiz can someone on the MAUI team record a `.speedscope` file? (or @UweFuchsPit :smile:)? I think the complaint here is the speed of MAUI layout?

https://aka.ms/profile-maui

**Comment by pitMobile** [comment]
@jonathanpeppers attached you will find the corresponding speedscopes for Android. Both for the configuration debug and release. We hope it contains the information you need.

[maui-perfomance-issue-android-debug.zip](https://github.com/dotnet/maui/files/10394804/maui-perfomance-issue-android-debug.zip)
[maui-perfomance-issue-android-release.zip](https://github.com/dotnet/maui/files/10394805/maui-perfomance-issue-android-release.zip)

**Comment by jonathanpeppers** [comment]
I looked at the release one, and about 18% of the time is spent in:

 ```
microsoft.maui!Microsoft.Maui.Handlers.ScrollViewHandler.GetDesiredSize(double,double)
 ```
 
It kind of feels like some kind of "layout loop" that happens when you rotate the device. Have you tried disabling the `ScrollView` (so it doesn't scroll) prior to rotation? And re-enable when rotation is complete? You could also try removing/re-adding child views.

Maybe @jsuarezruiz can offer a code example? We could think about doing this in MAUI itself automatically.

**Comment by pitMobile** [comment]
The hint with the rotation and the recalculation of the size is very interesting, at least for the future. However, the device was not rotated for the creation of the speedscope. Only alternating views were created and stacked on top of each other. In Xamarin, the whole thing runs without any problems. In MAUI, loading the views is extremely slow, especially in debug mode. Then as the number of existing views increases, it gets even slower. 

Whether it's faster in release mode or from the store doesn't matter in the end either, since development takes place in debug mode.

**Comment by jonathanpeppers** [comment]
@pitMobile have you tried removing `<ScrollView/>` from your layout? To see if that is where the issue is?

**Comment by hartez** [comment]
If you are using any Shape views in your layout (including Border), you might be running into an infinite layout loop issue that we fixed a couple of weeks ago: #11704

Not saying that this will fix every performance issue you see on Android, but it definitely doesn't help. 

iOS has some known issues with unnecessary extra measure calls that I'm working on today; that may be contributing to the issues you're seeing there.

**Comment by AndreasReitberger** [comment]
@hartez 
Is this issue fixes with the `Border` control already? I'm facing poor Performance on mostly alle Pages, even if on data loading is happening. The most laggy pages are using a ListView with ItemPlates having borders. 

If this is fixed, I Need to do further researching.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 3.0. Can repro on Android platform with sample project. 
[maui-perfomance-issue](https://github.com/pitMobile/maui-perfomance-issue)

**Comment by CRoederTND** [comment]
the update changed nothing, still laggy
