### ISSUE TITLE
VisualStudio Maui templates not working in release

### ISSUE THREAD

**Issue by ZeProgFactory** [dotnet/maui#12515]
### Description

When trying to deploy Maui app in release mode:
```
error NETSDK1094: Unable to optimize assemblies for performance: a valid runtime package was not found. Either set the PublishReadyToRun property to false, or use a supported runtime identifier when publishing. When targeting .NET 6 or higher, make sure to restore packages with the PublishReadyToRun property set to true.
```
Debug - Android 12.1 - OK
Release - Android 12.1 - error
Debug - Windows - OK
Release - Windows - error
   
**Would expect templates to build in release without debugging.**

### Steps to Reproduce

Using Microsoft Visual Studio Enterprise 2022 (64-bit) – Preview - Version 17.5.0 Preview 2.0:

 * Create Maui App (7.0)
 * Add Maui Lib 
 * Add ‘Maui Lib’ Project Reference to Maui App

All settings to default values, no changes to the templates.

### Link to public reproduction project repository

https://github.com/ZeProgFactory/NETSDK1094

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12.1

### Did you find any workaround?

Cleanning and adding
```
<PublishReadyToRun>False</PublishReadyToRun>
```
in first ```PropertyGroup``` of  app and lib project file solves the issue.

**Comment by jsuarezruiz** [comment]
@jonathanpeppers Thoughts?

**Comment by jfversluis** [comment]
@ZeProgFactory can you try the workaround as specified here: https://github.com/dotnet/maui/pull/12114#issue-1497179167

I think this is fixed but has not been released yet.

**Comment by jfversluis** [comment]
Ah sorry, overlooked that one. Then use that for now until the next update!
