### ISSUE TITLE
Transparent background support in (blazor)webview component

### ISSUE THREAD

**Issue by vannomad** [dotnet/maui#12534]
I am currently using a BlazorWebview component as an overlay on a xaml view by Setting the BlazorWebViews's Background to Transparent, and also applying a transparent background to the html, body etc.

I want to make sure that this is not a bug and that I can depend on this implementation as it makes working with xaml controls + blazor hybrid much easier.

**Comment by mkArtakMSFT** [comment]
Can you please clarify which behavior you think may be a bug?
Customizing BlazorWebView should work.

**Comment by vannomad** [comment]
Specifically about content behind the BlazorWebView being able to be seen along with the html content.

To me this is desirable behavior but i want to make sure this isn't going to change/is intended behaviour.

**Comment by mkArtakMSFT** [comment]
Looks like things are working for you and as long as they do, we don't plan to change them 👍
