### ISSUE TITLE
Invalidate() does not invoke Draw() when GraphicsView is inside a Grid.

### ISSUE THREAD

**Issue by Greg-Bates-Trimble** [dotnet/maui#12560]
### Description

Cannot redraw a graphics view when the view is inside either a grid or stacklayout. E.g. calling Invalidate will not go and call Draw().

### Steps to Reproduce

1. Run the application in the public repo.
2. On MainPage.xaml is the element to display it not working.
3. Removing the grid and the Graphics view will begin to update.

### Link to public reproduction project repository

https://github.com/Greg-Bates-Trimble/GraphicsView_Not_Redrawing/tree/main

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

Android 12 and up

### Did you find any workaround?

Have not found a workaround as this is required for a page with lots of elements.

Have not tried on iOS

**Comment by jsuarezruiz** [comment]
Debugging the code seems to be an issue related with a layout sizing issue.

![fix-graphicsview-issue](https://user-images.githubusercontent.com/6755973/211766184-8480cc27-78b8-4b95-b67e-95dca0127afb.gif)

The Invalidate method use internally-calculated area based on the View height and width. The height is zero and for that reason the invalidated area is wrong. Works using the deprecated method invalidate(Rect) with a specific height (for example, 1000).

**Comment by Greg-Bates-Trimble** [comment]
Hi @jsuarezruiz thanks for that information. With those details have been able to construct a work around, which is to specify a HeightRequest and WidthRequest on the Graphics View.

**Comment by DoubleDBE** [comment]
@Greg-Bates-Trimble 

Your work around doesn't seem to work for me.

Did you specify your WidthRequest and HeightRequest in XAML or where did you apply it?

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 3.0(net8). Not repro on Android platform with sample project. [GraphicsView_Not_Redrawing/tree/main](https://github.com/Greg-Bates-Trimble/GraphicsView_Not_Redrawing/tree/main)
