### ISSUE TITLE
Carousel View does not behave properly in Windows

### ISSUE THREAD

**Issue by EwaldJebaraj** [dotnet/maui#12567]
### Description

In Android, Carousel view item takes full-screen width, But in Windows, it takes content width

**Android**
<img width="104" alt="image" src="https://user-images.githubusercontent.com/97146356/211792111-5fa1754f-dc87-4fe7-a990-a3f70910f9d5.png">

**Windows**
<img width="441" alt="image" src="https://user-images.githubusercontent.com/97146356/211792200-74e022d0-416c-4774-b4ba-e8e4878ab745.png">

Note : Not checked in iOS and MacCatalyst

### Steps to Reproduce

1. Run the attached sample
2. Run in Android 
3. Run in Windows
4. See the Difference in the View

### Link to public reproduction project repository

https://github.com/EwaldJebaraj/CarouselViewIssue

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by 1357310795** [comment]
Encountered the same problem. The CarouselView on Windows should bahave the same as Android, that's to say, display only an item at a time.

**Comment by syachrodi** [comment]
Why is the MAUI team classified as very slow and don't care about bugs? I, who was originally interested in using this framework, became lazy because there were too many bugs, and for years there were no bug fixes.

**Comment by mlancione** [comment]
Any update on this issue? The CarouselView is a basic control that simply doesn't work in Windows.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on windows platform with above project.
https://github.com/EwaldJebaraj/CarouselViewIssue
![image](https://github.com/dotnet/maui/assets/82450723/9579ef4b-3272-4f94-90ea-f4485bc57492)

**Comment by mlancione** [comment]
Verified this issue still exists in .NET 8 Preview 4.

**Comment by Stedy59** [comment]
Question... Do you desire to have the CarouselView Items' content size to the window size, or do you want to keep the CarouselView size consistent?

**Comment by PaulAndersonS** [comment]
We are looking for horizontal scrolling. Also we expect the carousel to get resized based on the window size. We also noted that when looping is enabled when we reach the last item and then to the first item the carousel gets resized based on the window size.

**Comment by malsabi** [comment]
Please any solution available for desktop mode ? I'm having the same issue with .NET 7
