### ISSUE TITLE
Unable to add an event handler via XAML if the event is internal

### ISSUE THREAD

**Issue by pavel-zhukov** [dotnet/maui#12566]
### Description

If you want to add an event handler to an object using XAML, you must ensure the event has the `public` accessibility modifier. If the modifier is `internal`, `LoadFromXaml` will throw a `XamlParseException` (in Windows):
> Cannot assign property "_property_": Property does not exist, or is not assignable, or mismatching type between value and property

...or the exception will not be thrown, but the handler will not be added (in Android).

### Steps to Reproduce

1. Create a File > New .NET MAUI App.
2. Create the class:
```c#
class MyView : ContentView
{
    internal event EventHandler MyEvent;
}
```
3. Add an object of the class to the `MainPage` content and create an event handler for its `MyEvent`:
```xml
<ContentPage ...>
    ...
    <local:MyView MyEvent="MyView_MyEvent" />
</ContentPage>
```
4. Run the app.

The `MyView_MyEvent` handler will not be added to the internal event via XAML, although the same can still be done successfully via C#.

### Link to public reproduction project repository

https://github.com/pavel-zhukov/MauiInternalEvent

### Version with bug

7.0 (current)

### Affected platforms

Android, Windows

### Affected platform versions

Android 9, Android 13, Win SDK 10.0.17763.0

**Comment by rachelkang** [comment]
@StephaneDelcroix any thoughts on this one?

**Comment by drasticactions** [comment]
@etvorun Do you have thoughts on this? AFAIK you can't do this in any of the other XAML frameworks we support (WPF, UWP, WinUI, etc)

**Comment by drasticactions** [comment]
CC @mgoertz-msft too.

**Comment by mgoertz-msft** [comment]
@drasticactions Internal is supported in WPF. The type with the internal event just needs to be in the same assembly as the XAML that uses it.

**Comment by mgoertz-msft** [comment]
Not sure about LoadXaml but at least it builds.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11 and Android 13.0-API33 with below Project:
[MauiInternalEvent.zip](https://github.com/dotnet/maui/files/11755240/MauiInternalEvent.zip)

**Comment by StephaneDelcroix** [comment]
WPF uses InternalTypeHelper https://learn.microsoft.com/en-us/dotnet/api/system.windows.markup.internaltypehelper?view=windowsdesktop-8.0
