### ISSUE TITLE
[Bug] WinUI has issues laying out compat layouts

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#1257]
### Description
If I have a page that has a compat layout, nothing appears:

```xaml

    <StackLayout>
        <Label Text="Hello, World!" FontSize="32"
               HorizontalOptions="CenterAndExpand" />
    </StackLayout>

```

### Steps to Reproduce

1. Replace the contents of the Xaml page with that
2. Run the sample in Xaml page mode
3. Observe a blank screen
4. Change to `<VerticalStackLayout>`
5. Observe contents

### Expected Behavior
Content.

### Actual Behavior
No content.

**Comment by mattleibow** [comment]
Stepping through the code, it goes to Platform.GetNativeSize for the children, which works with renderers so it seems like something is using the old code path.

**Comment by PureWeen** [comment]
@hartez it looks like before this PR 

https://github.com/dotnet/maui/pull/1157

WinUI was still using DefaultRenderer for StackLayout/Grid/etc...
Android/iOS use LayoutHandler
