### ISSUE TITLE
 Contacts.PickContactAsync(); Throws exception even if rights are granted. (windows)

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#12595]
### Description

Contacts.PickContactAsync();

THROWS AN EXCEPTION EVEN IF THE RIGHTS ARE GRANTED

>>> System.InvalidCastException

```cs
try
        {
            PermissionStatus status = await Permissions.RequestAsync<Permissions.ContactsRead>();

            var contact = await Contacts.PickContactAsync();

            if (contact == null)
                return;

            string id = contact.Id;
            string namePrefix = contact.NamePrefix;
            string givenName = contact.GivenName;
            string middleName = contact.MiddleName;
            string familyName = contact.FamilyName;
            string nameSuffix = contact.NameSuffix;
            string displayName = contact.DisplayName;
            List<ContactPhone> phones = contact.Phones; // List of phone numbers
            List<ContactEmail> emails = contact.Emails; // List of email addresses
        }
        catch (Exception ex)
        {
            // Most likely permission denied
        }
```

### Steps to Reproduce

Follow the code above
Rights are granted

Then the picker does not appear, exception is triggered.

On Android the code behaves properly.

Expected behavior: Same as Android.

### Link to public reproduction project repository

https://github.com/pierre01/UCSD-MAUI-Samples/blob/development/MAUICommunications/Views/ContactsPage.xaml.cs

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 Pro 22H2

### Did you find any workaround?

No

**Comment by mattleibow** [comment]
This is due to an issue in the Windows App SDK: https://github.com/microsoft/WindowsAppSDK/issues/1157

@davidbritch maybe we will have to add a note in the docs as I am not sure if the WASDK team will get to it any time soon.

**Comment by mattleibow** [comment]
Closing this issue as there is nothing we can really do. Windows does not have a contacts picker anymore. It used to work but since Windows 11 and WinUI 3, contacts are not a thing anymore as far as I can tell.

The only way to get this is to make a comment on the windows issue and let them know that you need this feature. We will try update our docs and things to make this exception not so painful to deal with.

**Comment by mattleibow** [comment]
Added a new issue here to track the docs part of this: https://github.com/dotnet/docs-maui/issues/1191

Please let your needs be known on the windows issue as they use that to prioritize development.
