### ISSUE TITLE
Consider implementing the PointerOver state for .NET 6

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#12597]
### Description

The PointerOver visual state was long anticipated and is now added to .NET MAUI for .NET 7. There is no support for .NET 6 however. Since .NET 6 is a long-term version, while .NET 7 is a short-term one, it makes sense to have essential features like this for the long-term version as well. Please, keep in mind, that not all developers are eager to upgrade their applications to a short-term .NET version, for various reasons. Since .NET MAUI is a separate workload, I see no reason to introduce such features for .NET 7 only.

### Public API Changes

No API changes are necessary.

### Intended Use-Case

The developers should have access to this feature in .NET 6.

**Comment by danies8** [comment]
Very important.

**Comment by jfversluis** [comment]
Just wanted to point out that the support policy of .NET MAUI differs from the more general .NET LTS and STS policies: https://dotnet.microsoft.com/platform/support/policy/maui

**Comment by PureWeen** [comment]
.NET 6 is now out of support
