### ISSUE TITLE
Cant Download

### ISSUE THREAD

**Issue by glennquagmir** [dotnet/maui#12591]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: Windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. My computer doesn't have the latest version of Windows, so it doesn't let me download Studio. Can you guys help me out?

**Comment by jfversluis** [comment]
Hey there @glennquagmir thanks for reaching out!

If you don't have the system requirements to run the necessary tools then unfortunately there is not much we can do. These requirements are set to provide you with the best experience. The only thing you can do is to upgrade your system to something that does work with the necessary Windows and Visual Studio versions.

The Visual Studio 2022 system requirements can be found in more detail here: https://learn.microsoft.com/visualstudio/releases/2022/system-requirements
