### ISSUE TITLE
Consider implementing tooltip support for .NET 6

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#12598]
### Description

Tooltip support was long anticipated and is now added to .NET MAUI for .NET 7. There is no support for .NET 6 however. Since .NET 6 is a long-term version, while .NET 7 is a short-term one, it makes sense to have essential features like this for the long-term version as well. Please, keep in mind, that not all developers are eager to upgrade their applications to a short-term .NET version, for various reasons. Since .NET MAUI is a separate workload, I see no reason to introduce such features for .NET 7 only.

### Public API Changes

No API changes are necessary.

### Intended Use-Case

The developers should have access to this feature in .NET 6.

**Comment by danies8** [comment]
Very important

**Comment by davidortinau** [comment]
.NET MAUI as Gerald points out is never LTS due to the nature of the platforms we support and tooling dependencies. 

Tooltip and other features will not be backported to previous versions.
