### ISSUE TITLE
iOS app poorly responsive when many elements, nested deeply, are on the screen

### ISSUE THREAD

**Issue by BioTurboNick** [dotnet/maui#12592]
### Description

The same page was very responsive in Xamarin.Forms 5, and in MAUI 7 on Android.

But on MAUI 7 iOS, the touch interaction responses tend to be delayed and executed in bursts.

The problem doesn't happen if I only have one custom control on the screen, but does happen when I have 12 of them.

It also only happens with several nested levels of controls.

### Steps to Reproduce

Several nested levels of Grid objects, the innermost one containing complex controls composed of many layout containers.

### Link to public reproduction project repository

https://github.com/BioTurboNick/iOSSlowdownExample

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by BioTurboNick** [comment]
@rachelkang Reproduction project added.

**Comment by BioTurboNick** [comment]
Possibly related: rotating the device with this page leads to a visibly slow layout cycle.

**Comment by hartez** [comment]
#12627 will likely help with this.

**Comment by BioTurboNick** [comment]
That would be great!

**Comment by BioTurboNick** [comment]
I believe this has been fixed by 7.0.59. I updated the workloads and the delays are vastly reduced, if not gone. There's still a visibly slow rotation-related layout cycle. But maybe that's another issue?

**Comment by hartez** [comment]
> I believe this has been fixed by 7.0.59. I updated the workloads and the delays are vastly reduced, if not gone. There's still a visibly slow rotation-related layout cycle. But maybe that's another issue?

Oh, rotation is probably a whole other ball of wax. If you've got a repro project that shows really rough performance on rotation, please open an issue for that!

**Comment by hartez** [comment]
Closing this, since the OP believes it's been fixed. @BioTurboNick if you're still running into issues with rotation, please open an issue and we'll take a look.
