### ISSUE TITLE
net6.0-android generated sources StyleCop error

### ISSUE THREAD

**Issue by dude3133** [dotnet/maui#12638]
### Description

Using StyleCop with rules `Action="Error"` produce unexpected compile errors from autogenerated code and used libraries
For example:
Using StyleCop.Analyzers.ruleset with:
`<Rule Id="SA1505"  Action="Error" />`
Produces errors:
```
/Droid/obj/Debug/net6.0-android/generated/src/Java.Interop.__TypeRegistrations.cs(24,24): Error SA1505: An opening brace should not be followed by a blank line (SA1505)
/Droid/obj/Debug/net6.0-android/generated/src/Com.Android.Installreferrer.Commons.InstallReferrerCommons.cs(47,47): Error SA1505: An opening brace should not be followed by a blank line (SA1505)
```

StyleCop provide option with ignoring all errors and warnings using `// <auto-generated/>` comment. And I found one ticket that refers their logic to avoid generated code: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1430
Could we somehow add  `// <auto-generated/>` comment for all generated code under obj/ folder?

### Steps to Reproduce

1. Create any net6-android project
2. Add SonarCop with more rules (like SA1505, SA1507) as Error
3. Try to build

### Link to public reproduction project repository

-

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

Android Any

### Did you find any workaround?

Remove SonarCop? Live without clean code? Nope

**Comment by mattleibow** [comment]
This issue was moved to xamarin/xamarin-android#7698
