### ISSUE TITLE
[Android 12+]Splash screen doesn't appear on maui app

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [dotnet/maui#12636]
### Description

Splash does work fine up to Android v 11.0 and not in 12.0.

Noticed some open issues in Git Hub with a workaround PFB. Unfortunately, it doesn't work.

Sample:
https://github.com/dotnet/maui-samples/tree/main/7.0/Fundamentals/ContextMenu

1. Just run above sample on API 31, you will see blank splash UI.
2. Add the mentioned workaround in this repository, still facing same issue, it does not resolve. https://github.com/dotnet/maui/issues/9794 

PFA issue replicable image for reference,
![image](https://user-images.githubusercontent.com/44390143/212339684-ead59cfe-65c3-4562-928d-81d596fcbb8c.png)

### Steps to Reproduce

1. Just run above sample on API 31, you will see blank splash UI.
2. Add the mentioned workaround in this repository, agin run the sample with workaround.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/7.0/Fundamentals/ContextMenu

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

11.0

**Comment by GnanaPriyaNamasivayam** [comment]
Hi @mattleibow,
The workaround you mentioned as a fix in the below thread, does not resolve the issue.
https://github.com/dotnet/maui/issues/7289
https://github.com/dotnet/maui/issues/9794

You have also mentioned its fixed in PR https://github.com/dotnet/maui/pull/8394 , Any update on its release?
Any alternate workaround or suggestion from your end would help, and its a critical issue for us.

Thanks.

**Comment by GnanaPriyaNamasivayam** [comment]
@mattleibow In the Nuget store the latest version has been released 6.0.550 on Jan 19, Seems the issue still exists.
Could you provide us with any update on this issue? It will help us to process further.

**Comment by Hottemax** [comment]
Confirmed, this is NOT fixed.

Repro for example is simply the sample app from https://github.com/enisn/UraniumUI
- emulator Pixel 5 API 30 (Android 11) - looks ok (including icon from svg)
- emulator Pixel 5 API 31 (Android 12) - only shows background color, no icon

**Comment by mattleibow** [comment]
That is the thing. Android 12 has a "feature" of only displaying the splash screen if you are launching from the home screen - so running via the IDE is not going to show the splash. Same happens if you restore the app via a notification.

https://issuetracker.google.com/issues/205021357?pli=1#comment14

> On Android 12:
> That's intended. By default it only show from the launcher. 
> The splash screen icon won't be shown otherwise, that includes notifications, deeplinks, start from other applications.

**Comment by suchithm** [comment]
Same issue. What is the additional information required

**Comment by mattleibow** [comment]
I suppose the bot is a bit wrong, but there is no real new info needed.

Android 12 does not support splash screens correctly and will only show it if launched via the default OS launcher. It will not show when resuming, from notifications, from the IDE or using custom launchers.

They fixed this in Android 13.

**Comment by suchithm** [comment]
`will only show it if launched via the default OS launcher`

Even when launched from default launcher not showing full screen image. only small circle  in center it shows.

**Comment by mattleibow** [comment]
That is the new, "correct" behavior. Unfortunately. The android OS only allows that for now.
