### ISSUE TITLE
How to disable bitcode strip for Google Sign In ?

### ISSUE THREAD

**Issue by Priyabaghelgithub** [dotnet/maui#12631]
### Description

I am facing below issue for Google Sign In : 

D:\MauiFirebaseDemo-master\MauiFirebaseDemo\MauiFirebaseDemo.csproj(148,3): error MSB3073: The command ""$(xcrun -find
bitcode_strip)" C:/Users/abcd/AppData/Local/XamarinBuildDownloadCache/GSgnI-5.0.2/Frameworks/GoogleSignIn.fram
ework/GoogleSignIn -r -o C:/Users/abcd/AppData/Local/XamarinBuildDownloadCache/GSgnI-5.0.2/Frameworks/GoogleSi
gnIn.framework/GoogleSignIn" exited with code 1. [TargetFramework=net7.0-ios]

### Steps to Reproduce

Have disabled the bitcode for Core, GoogleAppMeasurement. It is working but facing bitcode issue for Google Sign In.

### Link to public reproduction project repository

https://github.com/dotnet/maui/issues/10989

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS14

### Did you find any workaround?

https://github.com/xamarin/GoogleApisForiOSComponents/pull/580/commits/6b54ab26a20970ac7b273a0222521909c46f675e#diff-8477ebd83c197a9396792fa47096265b0436ce0a88a66384adccf71179b80715

**Comment by mattleibow** [comment]
@SotoiGhost Does this look like something you can help with?

**Comment by mattleibow** [comment]
This issue was moved to xamarin/GoogleApisForiOSComponents#596
