### ISSUE TITLE
Element.OnChildRemoved() - Incorrect variable used in function.

### ISSUE THREAD

**Issue by Martyf101** [dotnet/maui#12633]
Wrong variable in function call prevents retrieving required information:

`ChildRemoved?.Invoke(child, new ElementEventArgs(child));`

The first parameter should be "this" not "child", as its already in the second parameters EventArgs and not the sender.

Here is the ChildAdded line for comparison, with the correct parameters:

`ChildAdded?.Invoke(this, new ElementEventArgs(child));`

Element.cs lines 344-370 :

`

		protected virtual void OnChildAdded(Element child)
		{
			child.Parent = this;

			child.ApplyBindings(skipBindingContext: false, fromBindingContextChanged: true);

			ChildAdded?.Invoke(this, new ElementEventArgs(child));

			VisualDiagnostics.OnChildAdded(this, child);

			OnDescendantAdded(child);
			foreach (Element element in child.Descendants())
				OnDescendantAdded(element);
		}

		protected virtual void OnChildRemoved(Element child, int oldLogicalIndex)
		{
			child.Parent = null;

			ChildRemoved?.Invoke(child, new ElementEventArgs(child));

			VisualDiagnostics.OnChildRemoved(this, child, oldLogicalIndex);

			OnDescendantRemoved(child);
			foreach (Element element in child.Descendants())
				OnDescendantRemoved(element);
		}`

The following call throws "Specified cast is not valid." error as the sender is incorrectly set.

`childPage.ChildRemoved += (s, e) => System.Diagnostics.Debug.WriteLine(((NavigationPage)s).Height);`

Element.cs Line 363 should be written as:

`ChildRemoved?.Invoke(this, new ElementEventArgs(child));`

**Comment by hartez** [comment]
This was fixed in November: https://github.com/dotnet/maui/commit/f9c7e4d36e769a8ad7813c5e6b781cf8953329d6

What branch are you seeing this on?

**Comment by Martyf101** [comment]
Okay I can see this is fixed now on main branch. I would have got there though the search/reference popup on GitHub.

However it is still sending 'child' in the version I'm running, and I appear to be fully updated : 6.0.548

`childPage.ChildRemoved += (s, e) =>
                        {
                            if (s == e.Element)
                                System.Diagnostics.Debug.WriteLine("SENDER EQUALS ELEMENT");
}`

Shouldn't this code already be in the released version?

**Comment by hartez** [comment]
It's been backported to 7.0 and will be in the next 7.0 service release (which should be coming soon). It has not been backported to 6.0 and there are currently no plans to do so.
