### ISSUE TITLE
Support background image on splashscreen iOS 

### ISSUE THREAD

**Issue by JoacimWall** [dotnet/maui#12639]
### Description

I have bin able to solve this on Android using the old style like we do in Xamarin but I can’t find a way on iOS to provide a storyboard in Maui. Assets catalog is always generated on build. 

I can se that mauisplash screen create a storyboard that has an image that are centered on the screen. If you add a parameter to the Maui splash screen property in the project file and add this file as background on the mauisplash storyboard with aspect fill it would work perfect. 

Thanks Joacim 

### Public API Changes

The icon has similar function
<ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" />
</ItemGroup>

Suggestion add backgroundfile
<MauiSplashScreen Include="Resources\Splash\splashscreen.svg"
 BackgroundFile="Resources\AppIcon\background.svg"/>

### Intended Use-Case

My customer that has a Xamarin app that we upgrade to Maui expect this to work.

**Comment by jfversluis** [comment]
Hey @JoacimWall this shouldn't block you from upgrading. You can still use custom splash screens if you want, you could even copy it from your Xamarin project and use it directly in .NET MAUI.

The splash screen functionality we added is just to make it easier for you to get started.

I will keep this issue around as a feature request to consider where we can expand on our existing single-project splash screen functionality.

**Comment by Tsukasa42** [comment]
How is such a simple feature overlooked like this? I don't know anyone who creates a splash screen with only a small image. These are usually full screen images. I tried copying my iOS storyboard for LaunchScreen over with and without setting the property the document states not to set with no luck. As excited as I was to see the simplicity of the new structure, this is a show stopper if I can't customize the iOS splash page.

`.../Platforms/iOS/LaunchScreen.storyboard: Error: The file 'Platforms/iOS/LaunchScreen.storyboard' conflicts with 'Platforms/iOS/LaunchScreen.storyboard'.`

**Comment by michalpobuta** [comment]
@jfversluis Same storyboard from Xamarin added to MAUI not working. After adding custom storyboard, splashscreen is black and app layout is destroyed.

**Comment by jfversluis** [comment]
@michalpobuta did you run it on a real device? Or make sure your build is signed on the Simulator? 

Since some (somewhat recent) Xcode version iOS will only show the launch screen when the build is signed.

**Comment by michalpobuta** [comment]
@jfversluis I am sure. On emulator everything is okey. The problem is only on real device
