### ISSUE TITLE
Microsoft .Net Maui Toolkit Cannot resolve type EventToCommandBehavior

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12642]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Microsoft-Net-Maui-Toolkit-Cannot-resol/10233613)._

---
Added Community Toolkits Maui.Core, Maui, and MVVM to .net 7 Maui App.

On MainPage.xaml with ListView added the Behavior:
...
    xmlns:mauiToolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
...
...
            
                
            

F6 to Build:
Error  XFC0000 - Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:mauiToolkit:EventToCommandBehavior".	Common	xxxx\Common\MainPage.xaml	67	

---
#### Feedback Bot on 12/18/2022, 10:02 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by znelson32** [comment]
Same problem with InvertedBoolConverter today

**Comment by jfversluis** [comment]
Indeed make sure that initialization line is there! If it then still doesn't work please report it on the Toolkit repository: https://github.com/CommunityToolkit/Maui
