### ISSUE TITLE
.NET MAUI CollectionView scrolling doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12643]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-CollectionView-scrolling-doesn/10199158)._

---
The GitHub maui-samples repository includes a set of CollectionView demos.

https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Views/CollectionViewDemos/CollectionViewDemos

These generally include some demos of collections that extend beyond the page length, and specifically demos of programmatically scrolling.

Environment
* Windows 11 Pro
* Visual Studio 2022
* .NET 7
* .NET 6

As far as I can tell, scrolling of CollectionView doesn't work at all. To test, I have:

* Used Visual Studio 2022 Preview 17.5.0 Preview 1
* Used Visual Studio 2022 17.4.0
* Run the Windows application
* Run in Android emulation
* Deployed to my Android phone
* Run the sample using Visual Studio 2022 on a different computer (running Windows 10)

The (lack of) behaviors I'm seeing are:

* In the Windows app, no scroll bar, click-drag doesn't scroll
* In the Android app, swipe doesn't scroll
* In the samples where a button is supposed to bring an item into view, it doesn't.

Samples tried:

* Vertical list - data template
* Vertical grid - data template
* Scroll by object - ScrollTo

As these are Microsoft samples, I'd expect them to work unless there's a configuration step I'm missing (and if there is, it isn't obvious).

---
#### Feedback Bot on 11/13/2022, 09:42 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by marcojak** [comment]
Same problem here. Collection view doesn't work. This is not a minor bug. It's a massive one. A collectionview is a basic control and I cannot imagine a proper app without one. I hope this will be fixed soon otherwise, at least on Windows, it's not possible to develop almost any app!

**Comment by acaliaro** [comment]
I think depends by the container layout.

**Comment by Ruddy2007** [comment]
This is insane. How did we do from Xamarin were things where starting to work... Back to basic controls not working at all. How are we expected to migrate to MAUI with these basic bugs?

**Comment by DeerSteak** [comment]
I can't believe this fundamental control that every mobile app on the planet uses is still hosed and we're supposed to be off Xamarin.Forms by the end of the year. 

@Ruddy2007 thanks so much for the hint about the Grid. If I set the RowHeight for the row the CollectionView is in to * it scrolls and it fits. If I use a VerticalStackLayout it's broken.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0(.NET8). Not repro on windows and android platforms with sample project (CollectionViewDemos).
https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Views/CollectionViewDemos/CollectionViewDemos

**Comment by MV10** [comment]
> Hi @vsfeedback. We have added the "s/try-latest-version" label to this issue
> This issue will be closed automatically in 7 days if we do not hear back from you by then

Gee, what are the chances "vsfeedback" will respond? These issue bots are a plague... I've been chasing this problem through one bot-closed issue after another. And it looks like this one will auto-close four days from now. Lovely.

**Comment by samhouts** [comment]
Hey, @MV10 ! Looks like we fixed this one in NET 8 previews. Are you able to confirm? Thanks!

**Comment by MV10** [comment]
@samhouts Unfortunately I'm chasing MAUI in a locked-down corporate environment that doesn't permit pre-release.
