### ISSUE TITLE
VS 2022 MAUI : App does not show mainpage on windows machine

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12651]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-MAUI-:-App-does-not-show-mainpag/10135601)._

---
I just create a simple MAUI get started project, it build and deploy succeeded on windows machine, but a mainpage window does not show.
I found it running in the task manager processes.
But it is work on android emulator.

---
#### Feedback Bot on 8/31/2022, 07:41 PM: 

(private comment, text removed)
#### Melody Huang (CSI Interfusion Inc) [MSFT] on 9/1/2022, 02:56 AM: 

(private comment, text removed)
#### pichet on 9/2/2022, 00:50 AM: 

(private comment, text removed)
#### Melody Huang (CSI Interfusion Inc) [MSFT] on 9/5/2022, 01:58 AM: 

(private comment, text removed)
#### pichet on 9/5/2022, 02:39 AM: 

(private comment, text removed)
#### Feedback Bot on 9/6/2022, 03:16 AM: 

(private comment, text removed)
#### Somchai LIMSIRORATANA on 9/26/2022, 06:51 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment]
Potentially related to #12080
