### ISSUE TITLE
Xaml compiler removes xaml-only Resources from Release builds

### ISSUE THREAD

**Issue by razaraz** [dotnet/maui#12659]
### Description

When pecifying a Resource file as only XAML with no code-behind, the release configuration will remove the .xaml file from the Assembly's resources. This will happen even if the type is used to initialize a `ResourceDictionary` through the `LoadFromXaml()` extension method.

If the Resource file is referenced directly in another .xaml file, the xaml compiler will not remove the resource. If the resource file is only instantiated by code however, the compiler will not detect that, and remove the file as an optimization.

### Steps to Reproduce

1. Create a Maui App from the Maui App template
2. In `App.xaml` remove the entry for the Colors resource dictionary
3. In `Colors.xaml`, add an `x:Class` attribute with the value `x:Class="MauiApp1.ColorResources"`
4. In `Styles.xaml`, remove everything except the `Label` style, and the `TextColor` setter
5. In `Styles.xaml` replace the value for `TextColor` to `{DynamicResource White}`
6. In `App.xaml.cs` add the following line after `InitializeComponent()`: `Resources.Add(new ResourceDictionary().LoadFromXaml(typeof(ColorResources)));`
7. Launch the project in `Debug`: Project runs fine
8. Launch the project in `Release`: Project crashes.

### Link to public reproduction project repository

https://github.com/razaraz/MauiXamlCBugRepro

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.17763; Android 21.0

### Did you find any workaround?

I've found a workaround by adding the line:
` <MauiKeepXamlResources>True</MauiKeepXamlResources>`
in the `.csproj`

**Comment by jsuarezruiz** [comment]
@StephaneDelcroix Thoughts?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11 and Android 13.0-API33 with below Project:
[MauiXamlCBugRepro.zip](https://github.com/dotnet/maui/files/11767070/MauiXamlCBugRepro.zip)

**Comment by StephaneDelcroix** [comment]
well, that's kind of the intended behaviour

replace 
```
Resources.Add(new ResourceDictionary().LoadFromXaml(typeof(ColorResources)));
```

by 

```
Resources.Add(new ColorResources()));
```

**Comment by StephaneDelcroix** [comment]
we could add an xml processing instruction, like `<?xaml-comp keepxaml="true" ?>`
