### ISSUE TITLE
SVG file is not converting to PNG properly.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12658]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SVG-file-is-not-converting-to-PNG-proper/10248731)._

---
I've added an svg icon and its not rendered properly in maui.
this are some of the svg which doesn't render properly
https://www.svgrepo.com/svg/474519/orange
https://www.svgrepo.com/svg/474536/cantaloupe
just plug it in an image box it doesn't render properly.

---
#### Feedback Bot on 1/9/2023, 06:33 PM: 

(private comment, text removed)
#### Sigma Li (CSI Interfusion Inc) [MSFT] on 1/10/2023, 02:02 AM: 

(private comment, text removed)
#### anuj guha on 1/10/2023, 09:06 PM: 

(private comment, text removed)
#### Feedback Bot on 1/11/2023, 01:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by moljac** [comment]
Confirmed:

Repro sample:

[AppMAUI.ReproSample12658.SVG2PNG.zip](https://github.com/dotnet/maui/files/12332616/AppMAUI.ReproSample12658.SVG2PNG.zip)

For given SVGs:

![orange_svgrepo_com](https://github.com/dotnet/maui/assets/1768576/cff2cbc7-355d-4424-ac3e-846f2241a824)
![cantaloupe_svgrepo_com](https://github.com/dotnet/maui/assets/1768576/843a306c-22d0-4ae9-9f67-2536c680d80b)

Output PNGs:

![orange_svgrepo_com](https://github.com/dotnet/maui/assets/1768576/d33be5c1-f38e-47e1-877b-585d8de69e87)
![cantaloupe_svgrepo_com](https://github.com/dotnet/maui/assets/1768576/bdc08071-c649-4bb4-96fc-a690c736bb75)

**Comment by moljac** [comment]
Created issue in Svg.Net

https://github.com/svg-net/SVG/issues/1069

Closing this one.
