### ISSUE TITLE
Windows Machine MAUI Drop Event from an external source causes Exception

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12657]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Windows-Machine-MAUI-Drop-Event-from-an-/10239539)._

---
There are actually 2 problems.
1. When Dragging a from an external source (such as File Explorer) DragOver arguments (DragEventArgs) contain no data.
2. When Dropping from an external source (such as File Explorer) causes "Unhandled Exception" in App.g.i.cs

```cs
    public void InitializeComponent()
        {
            if (_contentLoaded)
                return;

            _contentLoaded = true;

            global::System.Uri resourceLocator = new global::System.Uri("ms-appx:///Platforms/Windows/App.xaml");
            global::Microsoft.UI.Xaml.Application.LoadComponent(this, resourceLocator);

#if DEBUG && !DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
            DebugSettings.BindingFailed += (sender, args) =>
            {
                global::System.Diagnostics.Debug.WriteLine(args.Message);
            };
#endif
```

**Here:
```cs
#if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
            UnhandledException += (sender, e) =>
            {
                if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();
            };
#endif
        }**
```
---
#### Feedback Bot on 12/27/2022, 06:15 PM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 12/29/2022, 03:16 AM: 

(private comment, text removed)
#### Feedback Bot on 1/10/2023, 08:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by v-yanfw** [comment]
As user didn’t provide details repro information, and I reply to user confirm the repro steps, but we haven't received a reply from the user.
I just guess the scenario that as user’s described.
User’s feedback repro on 17.4.3

Repro Steps:
1. Create new MAUI project base on .NET 7.0.

2. Add the code into MainPage.xaml
<Editor>
<Editor.GestureRecognizers>
<DropGestureRecognizer AllowDrop=“True” Drop=“DropGestureRecognizer_Drop_1”></DropGestureRecognizer>
</Editor.GestureRecognizers>
</Editor>

3. Meanwhile the following code is added into MainPage.xaml.cs file.
private void DropGestureRecognizer_Drop_1(object sender, DropEventArgs e)
{
 
}

4. Target use the default option “Windows Machine” Build and debug the app.

5. After the app is deployed to Windows Machine, drag some text to the editor part of the window, exception occurred.
Please refers to the screenshot:
maui1.png

**Comment by rachelkang** [comment]
@v-yanfw thanks for the additional information. Would you be able to share the repro?

**Comment by v-yanfw** [comment]
> @v-yanfw thanks for the additional information. Would you be able to share the repro?

This is feedback from VS user.
There is no need to provide a repo. Follow the repro steps I wrote just to reproduce the user's feedback.

**Comment by drasticactions** [comment]
Could this be the same as https://github.com/dotnet/maui/issues/6080?

**Comment by upswing1** [comment]
I have the same problem as everyone else on this thread.  The possibility to drag and drop a file needs to be fixed and not put in the backlog if you want the community to use MAUI for desktop development..

**Comment by ToolmakerSteve** [comment]
@drasticactions - looks closely related. Fundamental issue with drag & drop from other app.

**Comment by mootah01** [comment]
I agree with other posters, the desktop app support is shocking, basic functionality is being put onto the backlog. I have an app live on windows that I can’t release on Mac because MAUI just doesn’t work.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 3.0(net8). Not repro on Windows platform with mentioned repro steps.
