### ISSUE TITLE
Can't access Color type in net7.0-windows10.0.19041.0

### ISSUE THREAD

**Issue by sretz** [dotnet/maui#12655]
### Description

A change in net7.0-windows10.0.19041.0 from net6.0-windows10.0.19041.0 is making the Color type no longer accessible.

### Steps to Reproduce

1. Download https://github.com/sretz/Reproduce.RadioGridVisible
2. Run in Windows
3. Change TargetFrameworks to net7.0
4. Will not compile

### Link to public reproduction project repository

https://github.com/sretz/Reproduce.RadioGridVisible

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

No

**Comment by mattleibow** [comment]
I am not able to reproduce this. Maybe you needed a clean after the TFM change as that is quite a massive change.

**Comment by sretz** [comment]
I dont know why you cant reproduce because when I create new projects I still have the problem. How do I the clean you are suggesting?

**Comment by mattleibow** [comment]
You should be able to select "Clean Solution" from the "Build" menu.

Also, maybe you can share the build error/log you are getting?

And also a full binlog will be very helpful: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

**Comment by sretz** [comment]
@mattleibow Clean Solution from the Build menu fixed the problem thank you.

**Comment by mattleibow** [comment]
Awesome!

Usually switching TFM (net6 to net7) is actually counted as a brand new thing. So you at least have to reload or clean the project. So is adding or removing a TFM.
