### ISSUE TITLE
MAUI Community Toolkit Popup Displayed Out Window Bounds On MacCatalyst

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12652]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Community-Toolkit-Popup-Displayed-O/10191700)._

---
If your app windows is not full screen on Mac when your run your app the popup page won’t show up, now maximize you window and then show the popup and the popup will be shown but it will go ourside the parent window boundaries although I sat the popup page width to the same value as the parent window width (same goes for height of course).

I am attaching two screenshots the first one shows the output when my window is not full screen (vertically in this particular case) which shows only the white translucent background color but the popup is not shown.

Second screenshot shows the popup after I maximized my window vertically to full screen and you can see here that the popup page went out of its parent window from the right side.

---
#### Feedback Bot on 11/6/2022, 11:03 PM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 11/11/2022, 00:22 AM: 

(private comment, text removed)
#### Tamer Irdais on 11/11/2022, 08:34 AM: 

(private comment, text removed)
#### Feedback Bot on 11/13/2022, 11:54 PM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 11/13/2022, 11:58 PM: 

(private comment, text removed)

---
#### Feedback Bot solved on 11/8/2022, 01:07 AM, 0 votes: 

<p>Thanks for taking the time to report this issue! It seems to us that it’s describing the same thing as <a target='_blank' href="https://developercommunity.visualstudio.com/t/MAUI-Community-Toolkit-Popup-Background-/10191178">another one</a>. We’ve closed this one as a duplicate and transferred all votes from this ticket to the other one. Please follow along on the linked ticket to communicate with the team, see updates on status, and help provide any needed diagnostic info. For more information, see our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines">issue reporting guidelines</a>.</p>
<p>Happy coding!</p>

#### Tamer Irdais on 11/9/2022, 07:44 AM: 

(private comment, text removed)

**Comment by mattleibow** [comment]
This issue was moved to CommunityToolkit/Maui#898
