### ISSUE TITLE
Where is toolbox?

### ISSUE THREAD

**Issue by AP2020C** [dotnet/maui#12667]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/modify
Operating System: windows

The VS2022 presentation clearly indicated the presence of the toolbox to visually edit xaml in all products. How do I activate it?

**Comment by drasticactions** [comment]
https://learn.microsoft.com/en-us/visualstudio/ide/reference/toolbox?view=vs-2022

It's under View > Toolbox. I don't believe it's the default to open in a new project but it should work.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/898335/212622783-c95fdb9f-22ec-44e2-8313-44c9291ad988.png">

**Comment by AP2020C** [comment]
OK, although I don't understand why it is hidden. However, I keep seeing XAML code instead of the graphical layout, as I do in WPF.
Like this https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2019/12/WPFCore3_VisualStudio.png

**Comment by jfversluis** [comment]
There is only a toolbox. We do not have a graphical designer for .NET MAUI at this time nor is it on the roadmap. Sorry!

**Comment by AP2020C** [comment]
It would help.
Thanks for the clarification.

**Comment by AP2020C** [comment]
Is there a third-party tool with this function?
