### ISSUE TITLE
But what if I want to use Maui to create a normal exe?

### ISSUE THREAD

**Issue by AP2020C** [dotnet/maui#12668]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

But what if I want to use Maui to create a normal exe?
I would like to use Maui to compile exe in Windows and apk/aab for andoird! And then also for Linux and Mac in their respective formats.

**Comment by MagicAndre1981** [comment]
[Windows Unpackaged support is still work in progress](https://github.com/dotnet/maui/issues/10564)
