### ISSUE TITLE
Difficult installation

### ISSUE THREAD

**Issue by AP2020C** [dotnet/maui#12664]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Problem 1: the page is only in English, trying to set another language it remains in English
Problem 2: I had already installed VS2017, the procedure to install VS2022 did not give an error but only VS2017 keeps showing up!

**Comment by AndreasReitberger** [comment]
If you have more than one VS instances installed, you need to right click the solution first ans select 'open with'. Then select VS 2022 and set the tick for remember that setting.
Additionally, you can remove VS 2017.

**Comment by AP2020C** [comment]
I actually think it was an installation problem: the first time it seemed to have installed but actually had not. On the second try instead it seems to work with the version choice menu and the presence of both in Start.
