### ISSUE TITLE
Simplification of interface declaration in code

### ISSUE THREAD

**Issue by idexus** [dotnet/maui#12678]
# Description

I would love to simplify interface declaration in code for classes with `[ContentProperty]` attribute

### Single item content

I would like to add the ability to declare content inside curly braces

```cs
new Border
{
    new Grid
    {
        ...
    }
}
```

### Multi item content

I would also like to add the ability to declare content inside curly braces

```cs
new Shell
{
    new FlyoutItem
    {
        new Tab
        {
            new ShellContent(),
            new ShellContent(),
            new ShellContent()
        },
        new Tab
        {
            new ShellContent(),
            new ShellContent()
        }
    }
}
```

# Public API Changes

I can prepare PR.

### To do

You will need to implement the `IEnumerable` interface for classes that do not already have the `IList` interface implemented and have the `[ContentProperty]` attribute.

### Single item content

```cs
[ContentProperty("Content")]
public class Border : ..., IEnumerable
{ 
    ...

    public IEnumerator GetEnumerator()
    {
        yield return Content;
    }

    public void Add(View content)
        => Content = content;

    ...
}
```

in classes:

```cs
Microsoft.Maui.Controls.Border
Microsoft.Maui.Controls.ContentPage
Microsoft.Maui.Controls.ContentView
Microsoft.Maui.Controls.FlyoutPage
Microsoft.Maui.Controls.ImageBrush
Microsoft.Maui.Controls.IndicatorView
Microsoft.Maui.Controls.Label
Microsoft.Maui.Controls.On
Microsoft.Maui.Controls.RadioButton
Microsoft.Maui.Controls.ScrollView
Microsoft.Maui.Controls.Setter
Microsoft.Maui.Controls.Shapes.Path
Microsoft.Maui.Controls.ShellContent
Microsoft.Maui.Controls.Span
Microsoft.Maui.Controls.ViewCell
Microsoft.Maui.Controls.Window
```

### Multi item content

```cs
[ContentProperty ("Items")]
public class ShellSection : ..., IEnumerable

{
    ...

    public IEnumerator GetEnumerator()
        => Items.GetEnumerator();

    public void Add(ShellContent items)
        => Items.Add(items);

    ...
}
```

in classes:

_Note: For these classes, you can declare an `IList<T>` interface instead of `IEnumerable`, but this is not necessary for the purpose._

```cs
Microsoft.Maui.Controls.DataTrigger
Microsoft.Maui.Controls.EventTrigger
Microsoft.Maui.Controls.FormattedString
Microsoft.Maui.Controls.GradientBrush
Microsoft.Maui.Controls.MultiBinding
Microsoft.Maui.Controls.MultiPage<T>
Microsoft.Maui.Controls.MultiTrigger
Microsoft.Maui.Controls.OnPlatform<T>
Microsoft.Maui.Controls.Shapes.GeometryGroup
Microsoft.Maui.Controls.Shapes.PathFigure
Microsoft.Maui.Controls.Shapes.PathGeometry
Microsoft.Maui.Controls.Shapes.Polygon
Microsoft.Maui.Controls.Shapes.Polyline
Microsoft.Maui.Controls.Shapes.TransformGroup
Microsoft.Maui.Controls.Shell
Microsoft.Maui.Controls.ShellItem
Microsoft.Maui.Controls.ShellSection
Microsoft.Maui.Controls.Style
Microsoft.Maui.Controls.TableView
Microsoft.Maui.Controls.Trigger
Microsoft.Maui.Controls.VisualState
Microsoft.Maui.Controls.VisualStateGroup
```

### `[ContentProperty]` attributes

It would be nice to add missing content property attributes to improve consistency, but it's not necessary for this purpose.

```cs
[ContentProperty("Points")]
public class Polyline { ... }

[ContentProperty("Data")]
public class Path { ... }

[ContentProperty("Points")]
public class Polygon { ... }

[ContentProperty("Content")]
public class RadioButton { ... }

[ContentProperty("Setters")]
public class VisualState { ... }
```

# Intended Use-Case

Interface declaration in code

**Comment by mattleibow** [comment]
One issue with this is that C# does not support mixing the content and properties:

```cs
new Border
{
    BackgroundColor = Colors.Red,
    new Grid {} // error
}
```

**Comment by idexus** [comment]
Yes, but you can do the rest with extension methods, e.g. using Community Markup. What this proposal is about are things that cannot be done outside of the library.

For example, I had to wrap your classes and create new library to get this effect, instead of using Community Markup
[https://youtu.be/YitedYYS1Zo](https://youtu.be/YitedYYS1Zo)

```cs
Content = new Border
{            
    new Grid
    {
        new VStack
        {
            new Label()
                .Text(e => e.Path(nameof(CardTitle)))
                .FontSize(25)
                .TextColor(Colors.White),

            new Label()
                .Text(e => e.Path(nameof(CardDescription)))
                .Style(e => e.Path(nameof(DescriptionStyle))),
        },

        new ContentView()
            .Row(1)
            .Content(e => e.Path(nameof(ContentView)))
            .HorizontalOptions(LayoutOptions.Center)
            .VerticalOptions(LayoutOptions.Center)
            .SizeRequest(120,120),

        new Button()
            .Row(2)                    
            .Text(e => e.Path(nameof(ButtonTitle)))
            .BackgroundColor(AppColors.Gray600)
            .TextColor(AppColors.Gray100)
            .OnClicked((sender, e) => Clicked(sender,e))
    }
    .RowDefinitions(e => e.Star(1).Star(2).Star(0.7))
    .RowSpacing(10)
}
.StrokeShape(new RoundRectangle().CornerRadius(10))
.Stroke(e => e.Path(nameof(BorderColor)))
.BackgroundColor(e => e.Path(nameof(CardColor)))
.SizeRequest(200, 300)
.Margin(50)
.Padding(20);
```

**Comment by mattleibow** [comment]
What would you expect to happen if for example there is the `Border` control that takes only 1 child. Because the API in use will be the `Add` method, would you expect the add to replace the content or throw an exception?

**Comment by idexus** [comment]
I expect to replace the content.

```cs
public void Add(View content)
        => Content = content;
```

**Comment by idexus** [comment]
Of course, overloading can be done also with extension methods, which gives great opportunities for developers

**Comment by mattleibow** [comment]
Just was trying something here, and the Add method can be extension methods - even generic extension methods:

```cs
public static View Add(this View that, View view)
{
	return that;
}
```

```cs
public static T Add<T>(this T that, View view)
	where T : View
{
	return that;
}
```

So maybe all we need to do is add `IEnumerable` and explicitly implement that? Things like border can even have a simple enumerator:

```cs
IEnumerator IEnumerable.GetEnumerator()
{
	yield return Content;
}
```

**Comment by idexus** [comment]
> Just was trying something here, and the Add method can be extension methods - even generic extension methods:

yes, the interface is enough, I thought to add at least a basic implementation for the `Add` method

**Comment by idexus** [comment]
> So maybe all we need to do is add IEnumerable and explicitly implement that? Things like border can even have a simple enumerator:

that would be enough, it would then be up to the developer what he would do - replace the content or throw an exception

**Comment by idexus** [comment]
Such a simple thing, but it gives you a lot of possibilities

**Comment by mattleibow** [comment]
Maybe this is a PR that you could start? The at least we can see if there are any test failures and the team can comment on various views. I don't foresee any major issues, but one thing I noticed was that my iOS tests failed when we switched to net6 because the Xunit `Assert.Equal()` actually did a different thing whether or not the object was IEnumerable or not. If it was IEnumerable then the test would iterate over the items instead of comparing. I had to switch to `Assert.Same()`.

This may be very unexpected for our tests as well as customers. But I suppose the counter to that is that layouts are lists...

**Comment by idexus** [comment]
Great! I will start a PR. One question, should I create `Add()` methods for the content which is a list, or should I create only the `GetEnumerator()` method for all classes?

**Comment by mattleibow** [comment]
Let's start with the enumerator version for now as that is minimal changes and we could maybe sneak it into net7. But maybe not so might have to wait for net8.

The add will have to wait for net8.

To test you can also set up a demo page with local Add extension methods in the sample code file.

**Comment by idexus** [comment]
Ok, I will do it :)
