### ISSUE TITLE
Android.Util.AndroidRuntimeException: 'Only the original thread that created a view hierarchy can touch its views.'

### ISSUE THREAD

**Issue by OnlyIslam** [dotnet/maui#12670]
### Description

![image](https://user-images.githubusercontent.com/3030547/212485284-d8e8aefc-c132-46d4-abee-5c67983b7b5e.png)

### Steps to Reproduce

Android.Util.AndroidRuntimeException: 'Only the original thread that created a view hierarchy can touch its views.'

### Link to public reproduction project repository

Android.Util.AndroidRuntimeException: 'Only the original thread that created a view hierarchy can touch its views.'

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Android

### Affected platform versions

android 13

**Comment by BioTurboNick** [comment]
You're probably accidentally trying to manipulate the view from code running in another thread. Use `MainThread` to ensure it runs in the main thread, which should avoid this.
