### ISSUE TITLE
ResourceDictionary Source-Property not settable

### ISSUE THREAD

**Issue by SonOfKorriban** [dotnet/maui#12709]
### Description

i wrote an WPF Application earlier, where i changed the Soruce of a Dictionary within the MergedDictionaries of the App. 
The reason was, i wanted to implement localisation / multi-language support. So if i changed the Source of the Dictionary from the US one to the German one, the strings were changed.

So i decided to use this in my new MAUI-App too. But unfortunately, i cannot set the Source of a Resource Dictionary by Code!
Why did you remove that feature? I spended a lot of hours trying arount other solutions (creating a new Dictionary and use the "SetAndLoadSource"-Method), but nothing works.

So, can you please provide setters for the Source of a Resource Dictionary, as you did in WPF?

### Steps to Reproduce

1. Get a ResourceDictionary by calling `Application.Current.Resources.MergedDictionaries[0];   ` 
2. Set the Source of a ResourceDictionary by calling `dict.Source = new Uri("..\\Resources\\StringResources.de-DE.xaml", UriKind.Relative);`

Expected Behaviour: The loaded Dictionary is overwritten by the new one
Current Behaviour: Exception, because the "Source"-Property cannot be set on C#-Code

![grafik](https://user-images.githubusercontent.com/39160000/212853853-94c27e0b-fcff-42e1-b70f-06c04dc607d6.png)

### Link to public reproduction project repository

https://github.com/SonOfKorriban/MauiIssueDictionaries

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows SDK 8.1.23107

### Did you find any workaround?

No

**Comment by rachelkang** [comment]
@StephaneDelcroix any thoughts on this one?

**Comment by StephaneDelcroix** [comment]
the RD.Source property is only meant to be set by xaml. it's by design

**Comment by SonOfKorriban** [comment]
What does mean "it's by design" mean?
Why was it possible to set the RD.Source in C# Code in WPF?
