### ISSUE TITLE
[SOLVED] Windows x86 Exception

### ISSUE THREAD

**Issue by TheMattWalker** [dotnet/maui#12717]
### Description

[SOLVED]
Update:
Using the following syntax in the project file resolved the issue and allows the application to be built and run as x86.
 
	<PropertyGroup>
		<Platforms>AnyCPU;x86</Platforms>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-windows')) and $(PlatformTarget)=='x64'">
		<Platforms>x64</Platforms>
		<RuntimeIdentifier>win10-x64</RuntimeIdentifier>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-windows')) and $(PlatformTarget)=='x86'">
		<Platforms>x86</Platforms>
		<RuntimeIdentifier>win10-x86</RuntimeIdentifier>
	</PropertyGroup>
	
![image](https://user-images.githubusercontent.com/12226257/212970217-0086e70e-0a81-4cde-b46c-2b28ce204ef3.png)

MAUI/WinUI throwing an exception when built for x86. 
When building and running x64 the exception is not thrown and everything works.

It appears the exception occurs right when the UI is attempting to load.

This is a massive issue as I must have an x86 client for my customer.

![image](https://user-images.githubusercontent.com/12226257/212939415-3cbf7410-dcd6-4909-96e4-9e4f29b93b03.png)
![image](https://user-images.githubusercontent.com/12226257/212937581-1d2e3d28-5d4d-441e-bf22-3245f1ac1c8e.png)

### Steps to Reproduce

1) Create .NET MAUI App from template.
2) Set Platform to "x86", set RuntimeIdentifier to "win-x86".
3) Build.
4) Attempt to run/debug.
5) Observe exception caught at App.g.i.cs.
6) Exception details listed in below log output.

### Link to public reproduction project repository

Simply use .NET MAUI App template

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

```shell
Meesage:
The type initializer for 'WinRT.ActivationFactory`1' threw an exception.

Source:
Microsoft.Graphics.Canvas.Interop

StackTrace:
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl..ctor()
   at Microsoft.Maui.Graphics.Win2D.W2DGraphicsView.UserControl_Loaded(Object sender, RoutedEventArgs e)
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
   
   
   Inner Exception:
   
   Message:
   Element not found.
   
   Source:
   Microsoft.Graphics.Canvas.Interop
   
   StackTrace:
      at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
      at WinRT.ActivationFactory`1..ctor()
      at WinRT.ActivationFactory`1..cctor()
```

**Comment by jfversluis** [comment]
Hey @TheMattWalker thanks for the report and even more thanks for coming up with a solution as well! 😄 

If you feel something still needs to be optimized here, please report it through the instructions above. That will make it go to the right team.
