### ISSUE TITLE
[WinUI] CarouselView "Scrolled" event never fires

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#12725]
If you take a look at line 32 in the CarouselViewHandler.Windows.cs (ConnectHandler override), it is removing the event handler instead of adding...

https://github.com/dotnet/maui/blob/af9c887431ac9a4b4faae20ff5763a50143ccc5a/src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs#L32

This should be an easy fix...  Please do not move this to the backlog!

**Comment by rachelkang** [comment]
Hi, @Stedy59 - we'll take a look at this further when we are able to. In the meantime, you are more than welcome to open a PR making the changes you see fit!

**Comment by Stedy59** [comment]
> Hi, @Stedy59 - we'll take a look at this further when we are able to. In the meantime, you are more than welcome to open a PR making the changes you see fit!

I was able to work around the initial issue with this code... but there are other issues that plague this platform implementation. 

I would love to open a PR on MANY issues that I have, but am not able to get the code base working. A little assistance would allow me to assist.


`		public static void AppendToMapping() =>
			CarouselViewHandler.Mapper.AppendToMapping(nameof(MauiCarouselView), (handler, view) => {
				if (view is MauiCarouselView carouselView) {
					handler.PlatformView.Loaded += (s, e) => {
						ScrollViewer scrollViewer = handler.PlatformView.GetFirstDescendant<ScrollViewer>();
						if (scrollViewer != null) {
							switch (handler.VirtualView.VerticalScrollBarVisibility) {
								case MScrollBarVisibility.Always:
									ScrollViewer.SetVerticalScrollBarVisibility(handler.PlatformView, WScrollBarVisibility.Visible);
									break;
								case MScrollBarVisibility.Never:
									ScrollViewer.SetVerticalScrollBarVisibility(handler.PlatformView, WScrollBarVisibility.Hidden);
									break;
							}
							switch (handler.VirtualView.HorizontalScrollBarVisibility) {
								case MScrollBarVisibility.Always:
									ScrollViewer.SetHorizontalScrollBarVisibility(handler.PlatformView, WScrollBarVisibility.Visible);
									break;
								case MScrollBarVisibility.Never:
									ScrollViewer.SetHorizontalScrollBarVisibility(handler.PlatformView, WScrollBarVisibility.Hidden);
									break;
							}
							scrollViewer.ViewChanged += (s, e) => {
								ItemsViewScrolledEventArgs args =
									new() {
										HorizontalOffset = scrollViewer.HorizontalOffset,
										HorizontalDelta = scrollViewer.HorizontalOffset - MauiCarouselViewHandler._previousHorizontalOffset,
										VerticalOffset = scrollViewer.VerticalOffset,
										VerticalDelta = scrollViewer.VerticalOffset - MauiCarouselViewHandler._previousVerticalOffset,
									};
								MauiCarouselViewHandler._previousHorizontalOffset = scrollViewer.HorizontalOffset;
								MauiCarouselViewHandler._previousVerticalOffset = scrollViewer.VerticalOffset;
								args.FirstVisibleItemIndex = handler.PlatformView.ItemsPanelRoot.As<ItemsStackPanel>().FirstVisibleIndex;
								args.LastVisibleItemIndex = handler.PlatformView.ItemsPanelRoot.As<ItemsStackPanel>().LastVisibleIndex;
								double center = (args.LastVisibleItemIndex + args.FirstVisibleItemIndex) / 2.0;
								args.CenterItemIndex =
									args.HorizontalDelta > 0
										? (int)Math.Ceiling(center)
										: (int)Math.Floor(center);
								handler.VirtualView.SendScrolled(args);
							};
						}
					};
				}
			});
`
