### ISSUE TITLE
WebView clears all other control elements rendered before it into blank

### ISSUE THREAD

**Issue by Silver-Fang** [dotnet/maui#12734]
### Description

WebView clears all other control elements rendered before it into blank

### Steps to Reproduce

Create a new MAUI App project.
MainPage.xaml:
```XAML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
	<Grid RowDefinitions="*,*,*">
		<Button Grid.Row="0"/>
		<WebView Grid.Row="1"/>
		<Button Grid.Row="2"/>
	</Grid>
</ContentPage>
```
MainPage.xaml.cs
```CSharp
namespace MauiApp1;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}
}
```
Debug on USB-connected Android phone. The Button above WebView is invisible, while the one below WebView is visible.

### Link to public reproduction project repository

https://github.com/Silver-Fang/MauiApp1

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

HarmonyOS 2.0

### Did you find any workaround?

Put the WebView element above any other control elements in the XAML code. Controls below WebView won't be affected.

**Comment by Silver-Fang** [comment]
![Screenshot_20230118_153359_com companyname mauiapp1](https://user-images.githubusercontent.com/33191697/213111023-3277fedb-0e7c-4872-9589-87e82547422b.jpg)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on android emulator and device platform with sample project.
[MauiApp1-master.zip](https://github.com/dotnet/maui/files/11932529/MauiApp1-master.zip)
![Screenshot 2023-07-03 105219](https://github.com/dotnet/maui/assets/77434865/70f5cef8-7de5-4353-8e33-1c908a391cf3)
