### ISSUE TITLE
FontImageSource Glyph using font name

### ISSUE THREAD

**Issue by acaliaro** [dotnet/maui#12732]
### Description

Hello. In a project I have two font files, one with the ttf extension, the other with the otf extension. Using the .otf file it seems that it can call the font using its name directly:

```
   <Image >
                <Image.Source>
                    <FontImageSource
                        FontFamily="FontAwesome"
                        Glyph="phone"
                        Size="40"
                        Color="{x:StaticResource Primary}" />
                </Image.Source>
            </Image>
```

Using the ttf one, it seems I'm forced to use the hexadecimal code.

```
            <Image >
                <Image.Source>
                    <FontImageSource
                        FontFamily="FASolid900"
                        Glyph="&#xf095;"
                        Size="40"
                        Color="{x:StaticResource Primary}" />
                </Image.Source>
            </Image>
```

Why can't I use the font name also with the ttf file? Is this a maui issue or is it related to the file type?

### Steps to Reproduce

See the project

### Link to public reproduction project repository

https://github.com/acaliaro/MauiAppFontImageProblem

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

No

**Comment by Redth** [comment]
This isn't something on our roadmap to try and add support for, and right now we rely on the underlying platform support.

So you're right that specifying "phone" for the otf does seem to work on the underlying platforms, however this isn't really something we control in the MAUI SDK.  Not all fonts contain the metadata for doing this either.

You'll have to specify the actual glyph unicode values when you are using .ttf files it seems.

**Comment by jamesmontemagno** [comment]
I would use something like https://andreinitescu.github.io/IconFont2Code/ to get friendly names for your fonts or https://github.com/matthewrdev/fa2cs
