### ISSUE TITLE
[Bug] Fullscreen and snapped window doesn't size content and layouts edge to edge

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1273]
### Description

Taking the template fullscreen I get:

![image](https://user-images.githubusercontent.com/41873/121738588-0157e080-cac0-11eb-840d-b96ef3e253aa.png)

Snapped to the right I get:

![image](https://user-images.githubusercontent.com/41873/121738704-2f3d2500-cac0-11eb-85b8-07e5f295cf3d.png)

### Expected Behavior

The content of my window/page takes up the fill bounds of the window when snapped to fullscreen or to a side or whatever new window size/position.

### Basic Information

- Version with issue: preview.5.4185

### Reproduction Link

`dotnet new maui`

**Comment by hartez** [comment]
This has been fixed.
