### ISSUE TITLE
RelativeLayout crashes android app.

### ISSUE THREAD

**Issue by comarkiewicz** [dotnet/maui#12748]
### Description

Using a RelativeLayout will result in a .NET MAUI app to crash while on Android.  Other platforms haven't been tested.  No errors or exceptions are produced in the debugger or the device log.

### Steps to Reproduce

1. Create a new .NET MAUI app.
2. Replace the contents of the MainPage.xaml with the following:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:cmp="clr-namespace:Microsoft.Maui.Controls.Compatibility;assembly=Microsoft.Maui.Controls"
             x:Class="Test_Maui_App.MainPage">

    <ScrollView>
        <cmp:RelativeLayout>

        </cmp:RelativeLayout>
    </ScrollView>

</ContentPage>
```
3. Replace the contents of the MainPage.xaml.cs with the following:
```
namespace Test_Maui_App;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}
}
```
4. Attempt to run the app on an android device and observe the crash that occurs.

### Link to public reproduction project repository

https://github.com/comarkiewicz/RelativeLayout-Crash

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 and up

**Comment by jfversluis** [comment]
Also seems to (still) happen on Windows: https://github.com/dotnet/maui/issues/6063#issuecomment-1476088769

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[12748.zip](https://github.com/dotnet/maui/files/11768210/12748.zip)
![image](https://github.com/dotnet/maui/assets/97647558/3224d5ab-529d-4501-abba-0eccd1f7f8e1)

**Comment by samhouts** [comment]
This is not a bug. The RelativeLayout is a compatibility feature. You must opt into these features by configuring your MauiProgram to Use Compatibility. You do this by editing your MauiProgram.cs to the following:

```
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			})
            .UseMauiCompatibility(); // <---- add this line!!

#if DEBUG
		builder.Logging.AddDebug();
#endif

		return builder.Build();
	}
```
The error message tells you to do this.

I verified that this works with the repro project.

Thanks!

**Comment by jaysidri** [comment]
The MauiApp builder does not have a method named UseMauiCompatibility() -- do I need to install a nuget to enable this?
