### ISSUE TITLE
New Maui projects should only open the Overview Page in VS

### ISSUE THREAD

**Issue by jknaudt21** [dotnet/maui#12755]
### Description

When creating a new Maui project in VS, the ideal behavior is to only open MAUI overview page and not the MainPage.xaml and other files. 

### Steps to Reproduce

1. Open VS
2. Create a new Maui project
3. Observe how the overview page and other files are opened . 

### Link to public reproduction project repository

https://github.com/jknaudt21/maui

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by BretJohnson** [comment]
It currently shows this (note that the overview page isn't activated by default):
![image](https://user-images.githubusercontent.com/245892/213329464-487eca3b-ed92-44da-95cf-92962b154215.png)

Where the intended experience is to show this:
![image](https://user-images.githubusercontent.com/245892/213329594-a4f9bea6-3e59-4a77-b013-01bc3b52098b.png)
