### ISSUE TITLE
OnRequest permission invoke on mainactivity shows warning as it supports only v23.0 and later

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [dotnet/maui#12764]
### Description

How I supposed to receive warnings in lower versions?

Is there any way to get rid of this warning?

![image](https://user-images.githubusercontent.com/44390143/213394300-3c96e275-681e-4b12-bc87-e66bb4351fea.png)

Any suggestion would be appreciable. Thanks.

### Steps to Reproduce

NA

### Link to public reproduction project repository

NA

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

8.0 and lower

### Did you find any workaround?

NO

**Comment by mattleibow** [comment]
This override is not available on the older OS, so you can avoid the warning by adding this atteibute:

```cs
[System.Runtime.Versioning.SupportedOSPlatform("android23.0")]
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
{
...
}
```

**Comment by mattleibow** [comment]
Closing this issue as it appears to have been resolved.
