### ISSUE TITLE
Hiding Entry underline inside compile directive does not work

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [dotnet/maui#12771]
### Description

I'm trying to hide Entry underline in MAUI android but it fails when added inside 
```
#region Android
                    h.PlatformView.BackgroundTintList = Android.Content.Res.ColorStateList.ValueOf(Android.Graphics.Color.Transparent);
#endif
```
This same set of entry handler code works when added inside DeviceInfo.Platform ==DevicePlatform.Android

Why does it happen? Kindly update as early as possible.

### Steps to Reproduce

1. Take a simple Maui sample with the entry.
2. Add Handler for it MauiProgram.cs within Android compile directive

Note: It does not reflect in view
If you remove directive if works.

### Link to public reproduction project repository

NA

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

11.0

**Comment by jfversluis** [comment]
The sample code that is provided has `#region Android` which is not a compile directive. That should be `#if ANDROID`.

Please provide a reproduction sample if you still need help with this to help us understand the exact problem.
