### ISSUE TITLE
Rollback JSON file links are not accessible

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#12772]
As part of our CI build process, we publish rollback .json files for the versions of the workloads we built a given commit for and the version of the maui workloads we produced.  

These rollback files can be used from the `dotnet workload install maui --from-rollback-json https://aka.ms/dotnet/maui/main.json` command.

The azure blob storage container has recently stopped allowing public access to those files and so these commands will currently fail.

We are investigating the issue and will look to have a resolution soon.

In the meantime, you can work around this issue by manually creating a `7.0.58.json` file with the contents:

```json
{
  "microsoft.net.sdk.android": "33.0.26/7.0.100",
  "microsoft.net.sdk.ios": "16.1.1481/7.0.100",
  "microsoft.net.sdk.maccatalyst": "16.1.1481/7.0.100",
  "microsoft.net.sdk.macos": "13.0.2036/7.0.100",
  "microsoft.net.sdk.maui": "7.0.58/7.0.100",
  "microsoft.net.sdk.tvos": "16.1.1481/7.0.100",
  "microsoft.net.workload.mono.toolchain.net6": "7.0.2/7.0.100",
  "microsoft.net.workload.mono.toolchain.net7": "7.0.2/7.0.100",
  "microsoft.net.workload.emscripten.net6": "7.0.2/7.0.100",
  "microsoft.net.workload.emscripten.net7": "7.0.2/7.0.100"
}
```

You can use that file locally with a workload install command:

`dotnet workload install maui --from-rollback-json 7.0.58.json`

**Comment by Redth** [comment]
While we're looking at options to mitigate this issue fully, I've gone ahead and updated the aka.ms links to point at static raw gist content which contain the files previously on blob storage.  The follow URL's should be functional again:

- https://aka.ms/dotnet/maui/7.0.58.json
- https://aka.ms/dotnet/maui/main.json
- https://aka.ms/dotnet/maui/net6.0.json
- https://aka.ms/dotnet/maui/net7.0.json
- https://aka.ms/dotnet/maui/net8.0.json
- https://aka.ms/dotnet/sdk/maui/net7.0.json
- https://aka.ms/dotnet/sdk/maui/net8.0.json

**Comment by rmarinho** [comment]
We are not providing the rollback anymore on that public url, going forward using workload set should be the recommended way. 

To workaround for users still using rollbacks we can add them to the each release so you can reference them like this

```
https://github.com/dotnet/maui/releases/download/8.0.82/8.0.82.json
```
