### ISSUE TITLE
MAUI cannot get the length of the stream from FileSystem.OpenAppPackageFileAsync on Android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12776]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-cannot-get-the-length-of-the-stream/10255594)._

---
[severity:It's more difficult to complete my work]
Create a new MAUI App project. Add a TextFile1.txt in the Resources\Raw directory.
MainPage.xaml:
```XAML
namespace MauiApp1;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
		long L = FileSystem.OpenAppPackageFileAsync("TextFile1.txt").Result.Length;
	}
}
```
Debug on my USB-connected Android phone. MainPage constructor fails to get the Length of the Stream opened by OpenAppPackageFileAsync. This works normally on Windows Machine. I found no documentations telling that Android does not support this.

---
#### Feedback Bot on 2023-01-18, 02:20 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment]
Hi, unfortunately this is just not supported on Android. On Android the only way to get the size of an asset is to read the whole stream and count how many bytes there were.

**Comment by janseris** [comment]
More details here:
https://github.com/dotnet/maui/issues/7471

**Comment by Silver-Fang** [comment]
> Hi, unfortunately this is just not supported on Android. On Android the only way to get the size of an asset is to read the whole stream and count how many bytes there were.

Then [this comment](https://github.com/dotnet/maui/issues/7471#issuecomment-1137525551) should be added to the relevant documentation, or there will always be followers thinking it is a bug.

**Comment by jsuarezruiz** [comment]
@davidbritch Could we update the documentation?

**Comment by davidbritch** [comment]
@jsuarezruiz I've added a docs issue about this: https://github.com/dotnet/docs-maui/issues/1215

**Comment by jfversluis** [comment]
Going to be added to the docs, nothing more for us to do here. Thanks!
