### ISSUE TITLE
Bound property does not update UI

### ISSUE THREAD

**Issue by Phil4121** [dotnet/maui#12790]
### Description

Hi!

I'm using .Net MAUI in combination with .Net 7 and CommunityToolkit.MVVM. I have got an ActivityIndicator and bound "IsRunning" to a property of my ViewModel ("IsLoading".

XAML:

    <Grid>
        <VerticalStackLayout
            Padding="30,0"
            Spacing="25"
            VerticalOptions="Center">

            <ActivityIndicator
                AbsoluteLayout.LayoutBounds="0.5,0.5,0.1,0.1"
                AbsoluteLayout.LayoutFlags="All"
                IsRunning="{Binding IsLoading}"
                IsVisible="True" />

            <Button
                x:Name="CounterBtn"
                Command="{Binding ButtonClickedCommand}"
                HorizontalOptions="Center"
                SemanticProperties.Hint="Counts the number of times you click"
                Text="Click me" />
        </VerticalStackLayout>
    </Grid>

CS:

	public MainPage(MainPageViewModel mpvm)
	{
		InitializeComponent();
        BindingContext = mpvm;
	}

I'm injecting my ViewModel.

ViewModel:

    public partial class MainPageViewModel : ObservableObject
    {
        [ObservableProperty]
        private bool isLoading = false;

        [RelayCommand]
        private async Task ButtonClicked()
        {
            IsLoading = true;

            await WriteLines();

            IsLoading = false;
        }

        private async Task WriteLines()        {
            for (int i = 0; i < 10000; i++)
            {
                Console.WriteLine(i);
            }
        }
    }

If I run this sample my ActivityIndicator isn't running and invisible. I was using this solution in .Net 6 and had no problem...
If I change ButtonClicked like this:

        [RelayCommand]
        private async Task ButtonClicked()
        {
            IsLoading = !IsLoading;
        }

ActivityIndicator is running and displayed. So, Binding seems to be correct and no typos.

### Steps to Reproduce

You can download my Repo to try it.

### Link to public reproduction project repository

https://github.com/Phil4121/Playground_ActivityIndicator

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

Android

### Affected platform versions

Android 8 and 11

**Comment by acaliaro** [comment]
Maybe write 10000 rows is too fast? try a Task.Delay with some seconds

**Comment by Phil4121** [comment]
Hi acaliaro! Thanks for your quick replay!

You are right! If I use Task.Delay(5000) the ActivityIndicator is displayed well. But if I extend from 100000 to 1000000 the Indicator isn't displayed...

Okay, but I see it's not a bug.

**Comment by GalaxiaGuy** [comment]
Despite using async/await it, this will run synchronously on the same thread (unless you do something to force it) so there is no chance for the UI to update. 

`Task.Delay(1)` forces allows the UI to update, although `Task.Yield()` should also do it and be more efficient.

Another option which is probably closer to what you want to do is wrap the contents of `WriteLines` in `Task.Run` so it actually runs on a background thread (make sure you return that `Task` or `await` it).

**Comment by Phil4121** [comment]
Hello GalaxiaGuy!
Thanks for your hint! I change my code to `await Task.Run(() => { WriteLines(); });` and it works perfectly without Task.Delay(1)!
Will have a closer look to async/await ;)

Thx
