### ISSUE TITLE
Missing Buttons-Property in TapGestureRecognizer-Control

### ISSUE THREAD

**Issue by SonOfKorriban** [dotnet/maui#12815]
### Description

As you mentioned in your MAUI Documentation [HERE](https://learn.microsoft.com/de-de/dotnet/maui/fundamentals/gestures/tap?view=net-maui-7.0) , you can theoretically catch a click of the mouse's secundary button, if you use the `Buttons` Property of the `TapGestureRecognizer `.

Here is the Code how i want to use it, as it's described in the documentation:

```
<Image Source="dotnet_bot.png">
        <Image.GestureRecognizers>
            <TapGestureRecognizer Tapped="OnTapGestureRecognizerTapped" Buttons="Secondary" />
        </Image.GestureRecognizers>
    </Image>
```

If i am doing that, VS tells me, that the Property `Buttons` is not Found in the Class `TapGestureRecognizer`, as you can see below:

![grafik](https://user-images.githubusercontent.com/39160000/213747911-a733b1a2-d067-401c-aca2-3715352aff13.png)

So, is the [documentation ](https://learn.microsoft.com/de-de/dotnet/maui/fundamentals/gestures/tap?view=net-maui-7.0) depricated? if so, how can i react to a richt-mouse-button click event? Thank you!

### Steps to Reproduce

1. Add a TapGestureRecognizer to an Image-Control
2. Try to use the `Buttons `Property of it, as mentioned in the official [documentation](https://learn.microsoft.com/de-de/dotnet/maui/fundamentals/gestures/tap?view=net-maui-7.0)
3. Fail, because it does not exist

### Link to public reproduction project repository

https://github.com/SonOfKorriban/MauiIssueReproductionRepo

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows SDK 8.1.23107

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. This issue does not repro on the latest .NET 7 on Windows 11 and Android 13.0-API33 with below Project:
[MauiIssueReproductionRepo.zip](https://github.com/dotnet/maui/files/11768475/MauiIssueReproductionRepo.zip)

**.NET 6.0:** repro this issue.
![image](https://github.com/dotnet/maui/assets/97647558/ecb07d90-d822-4f28-87bc-ad7ff5f2177d)

**.NET 7.0:** Does not repro this issue.
![image](https://github.com/dotnet/maui/assets/97647558/8391f19a-8643-424d-9094-ae55207b2583)

![image](https://github.com/dotnet/maui/assets/97647558/db6068cf-786e-44cc-ac92-fbf7d51b42d6)
