### ISSUE TITLE
 code 2147942405

### ISSUE THREAD

**Issue by Tenekamdaasisjopin** [dotnet/maui#12812]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Le programme '[8620] MyFirstMauiApp1.exe' s'est arrêté avec le code 2147942405 (0x80070005).

**Comment by Tenekamdaasisjopin** [comment]
slt a vous je ne sais plus trop quoi faire 
svp

**Comment by jsuarezruiz** [comment]
Seems to be the same as https://github.com/dotnet/maui/issues/12080

Try this workaround https://github.com/dotnet/maui/issues/12080#issuecomment-1377243186
