### ISSUE TITLE
MAUI rollbacks no longer publicly available causing build to fail

### ISSUE THREAD

**Issue by jdunaway** [dotnet/maui#12814]
### Description

Was using https://maui.blob.core.windows.net/metadata/rollbacks/7.0.1xx.json in my azure devops pipeline as a workaround for https://github.com/actions/runner-images/issues/6771 but when I checked in changes last night noticed this morning the build failed due to the following error.  You will also see this error if you navigate to https://maui.blob.core.windows.net/metadata/rollbacks/7.0.1xx.json  Has the url changed where we should be getting the rollback versions of maui from?

<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:5e6d3e1d-b01e-003e-47e5-2c7781000000 Time:2023-01-20T15:41:00.8232920Z</Message>
</Error>

### Steps to Reproduce

1. Navigate to https://maui.blob.core.windows.net/metadata/rollbacks/7.0.1xx.json
2. See the error message that it is no longer publicly available.

### Link to public reproduction project repository

not needed

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS

### Affected platform versions

iOS build

### Did you find any workaround?

No

**Comment by baaaaif** [comment]
see [https://github.com/dotnet/maui/issues/12772](https://github.com/dotnet/maui/issues/12772)

**Comment by drasticactions** [comment]
Fixed with https://github.com/dotnet/maui/issues/12772, those links should be public again.
