### ISSUE TITLE
[Bug] Investigate how the BackgroundLayers are all directly tied to the NativeArrange calls inside ViewHandler

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1282]
https://github.com/dotnet/maui/pull/1279

https://github.com/dotnet/maui/blob/7de6dca82eb968b6b680556d18872aec1ddc2801/src/Core/src/Handlers/View/ViewHandlerOfT.iOS.cs#L34

**Comment by hartez** [comment]
I tried to find an alternative, but short of subclassing all the of the native iOS controls and overriding layoutSubviews() (or using a custom CALayer), I can't find a way to make this work on iOS. I think for the time being we're stuck with UpdateBackgroundLayerFrame().
