### ISSUE TITLE
Implement or remove PreventGestureBubbling behavior inside Windows Gesture Manager

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#12828]
### Description

https://github.com/dotnet/maui/pull/12259#discussion_r1080739045

The intention of this [PR](https://github.com/xamarin/Xamarin.Forms/pull/842) in `Xamarin.Forms` was to make UWP gestures all work the same on WinUI as other platforms. The spirit of that PR most likely got lost in translation with MAUI since in MAUI we no longer have a `Panel` that everything is contained inside.

This isn't a bug indicating that we should fix this. We should first evaluate if we still want that code.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 1.0. Not repro this issue.
