### ISSUE TITLE
CarouselView on Windows totally broken

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#12850]
### Description

If loop=False in CarouselView if you change the CollectionView this is not reflected at all on Windows (but works on Android).
If you set loop=True in CarouselView even if you have 1 item in your CollectionView Windows renders it like 20 times. Again, this works on Android.

### Steps to Reproduce

- Get the repo and get the [CarouselViewOnWindowsBroken](https://github.com/rogerbriggen/mauiCarouselViewProblems/tree/CarouselViewOnWindowsBroken) branch
- Start the app
- Click any of the buttons -> On Windows, the UI does not update, on Android it works
- Stop the app

Change loop=True in MainPage.xaml
- Start the app
- See the horrable rending on Windows, on Android it works
- Push the button to add 2 new items
- Now, at least the text is updated even on Windows but still rendered unusable
- Stop the app
![Windows_LoopIsTrue_Started](https://user-images.githubusercontent.com/46163208/214046795-f7653e83-c842-49b0-828e-dd14b6564572.png)

### Link to public reproduction project repository

https://github.com/rogerbriggen/mauiCarouselViewProblems.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 22H2

### Did you find any workaround?

The only thing mostly working is set loop=false and then create a new ObservableCollection everytime something changes and also raise INotifyPropertyChanged for the ObservableCollection.

**Comment by Stedy59** [comment]
"Part" of the issue stems from the issue I reported last week... #12725 

I created a "AppendMapper" handler to address the scrollview issue, but have other issues "only in Windows"... such as the first element never showing...

Please try my "MauiCarouselView"... Attached.
[MauiCarouselView.zip](https://github.com/dotnet/maui/files/10481434/MauiCarouselView.zip)

**Comment by rstolpe** [comment]
> We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/maui/blob/main/docs/TriageProcess.md).

Well if you keep moving important things to backlog you will not get any new devs looking at MAUI and the devs that are trying it will jump ship.

MAUI need to keep up it up. Just face it, your not the only one out there.

Lack of docs etc make people dislike MAUI don't matter if people are publishing nice UI pics at Twitter etc.
We need something that can handle production.

**Comment by DeepWorksStudios** [comment]
@rstolpe I can fully agree that I am facing the same problems and am really worried about the fact that so many critical bugs have been pushed to the backlog. The reason why it worries me so much is the fact that I am working on a client project that should be ready for production in a few months, but if the situation doesn't improve, I might have to change the platform completely. I have already reported the bugs I have discovered that have not yet been reported.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Android platform with sample project.
https://github.com/rogerbriggen/mauiCarouselViewProblems.git
![image](https://github.com/dotnet/maui/assets/82450723/802ef10e-45c4-4c6a-9e78-bc143f5ad927)
