### ISSUE TITLE
MAUI Webview Process Lifecycle/Crash events

### ISSUE THREAD

**Issue by prerakpatel2** [dotnet/maui#12860]
### Description

Expose the lifecycle events of browsers through the API. As the Webviews run in separate processes, it is possible that they can crash or be forced to close by the user/OS. We should be able to react to those events so the app can recover the view if the webview processes crash. The lifecycle events would also allow us to hide the loading of the view until the process is ready for rendering. 

### Public API Changes

```csharp
Webview view = new();
view.OnViewProcessTerminated += (event) => {
// Logic to stop processing data for the view and reinitialize the view, log error, or notify of successful shutdown
}
view.OnViewProcessReady += (event) => { logic to hide loading screen }
view.OnViewProcessCloseInitiated += (event) => { logic to cleanup view  }
}

```

### Intended Use-Case

Recovering from crashed processes. We should be able to seamlessly recover from the crash, reload the view, and continue from where we left off.  This would also enable to preload the webview and know its ready for rendering when opening a webview based tool.

**Comment by Redth** [comment]
We should ensure that the various delegates for WKWebView can be easily passed in as custom instances.

We do this for UIDelegate currently in a mapper.  Navigation Delegate would need the same treatment.  

Related to #7551

**Comment by mgungorchamp** [comment]
I am trying this via Microsoft.AspNetCore.Cors - will try 

      builder.Services.AddCors(options =>
        {
            options.AddPolicy("AllowAll", builder =>
            {
                builder.AllowAnyOrigin()
                       .AllowAnyMethod()
                       .AllowAnyHeader();
            });
        });

**Comment by Eilon** [comment]
BTW here was a sample of how the process terminated event can be used specifically for BlazorWebView scenarios (not regular WebView): https://github.com/dotnet/maui/issues/6481#issuecomment-1117823532

**Comment by rmarinho** [comment]
Fixed by https://github.com/dotnet/maui/pull/20059
