### ISSUE TITLE
MAUI need Canvas layout like WPF or UWP

### ISSUE THREAD

**Issue by chaibi-mustapha** [dotnet/maui#12862]
### Description

I am developing an application with canvas and this canvas groups canvas childs. the child canvases will be the layers that group elements (image, drawings, ..) as to manipulate them (drag, drop, resize, rotate,....) then the main canvas can save its content as PNG , JPEG , SVG images it's like the principle of photoshop Canvas layout of WPF or UWP can do that and MAUI really lacks it please plan to create this control.

### Public API Changes

Canvas Layout

### Intended Use-Case

Canvas with  UIElement childs

**Comment by PureWeen** [comment]
@chaibi-mustapha Have you tried [GraphicsView](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/graphicsview?view=net-maui-7.0)?

**Comment by chaibi-mustapha** [comment]
Hi [PureWeen](https://github.com/PureWeen) ,
Canvas with graphicsview from MAUI does not work same as Canvas in WPF or UWP.
Canvas with MAUI's Graphicview function as a drawing board
but the WPF or UWP Canvas that I want is a layout that can contain UIElements (Images , Drawings ) and even nest other Canvas.

**Comment by jsuarezruiz** [comment]
> Hi [PureWeen](https://github.com/PureWeen) , Canvas with graphicsview from MAUI does not work same as Canvas in WPF or UWP. Canvas with MAUI's Graphicview function as a drawing board but the WPF or UWP Canvas that I want is a layout that can contain UIElements (Images , Drawings ) and even nest other Canvas.

What about use the AbsoluteLayout Layout?

**Comment by chaibi-mustapha** [comment]
[jsuarezruiz](https://github.com/jsuarezruiz)
it works like the canvas of WPF or WUP
that's what I'm looking for
thank you very much Javier Suarez.

**Comment by chaibi-mustapha** [comment]
> > Hi [PureWeen](https://github.com/PureWeen) , Canvas with graphicsview from MAUI does not work same as Canvas in WPF or UWP. Canvas with MAUI's Graphicview function as a drawing board but the WPF or UWP Canvas that I want is a layout that can contain UIElements (Images , Drawings ) and even nest other Canvas.
> 
> What about use the AbsoluteLayout Layout?

[jsuarezruiz](https://github.com/jsuarezruiz)
it works like the canvas of WPF or UWP
that's what I'm looking for
thank you very much Javier Suarez.
