### ISSUE TITLE
[Bug] Font icon not working on Mac Catalyst

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1286]
### Description

I'm using FontAwesome which works on other platforms but not on Mac Catalyst.

```xaml
<StackLayout Orientation="Horizontal">
                    <Button FontFamily="FontAwesome"
                            Text="{x:Static app:IconFont.Archway}"/>
                    <Button FontFamily="FontAwesome"
                            Text="{x:Static app:IconFont.Archway}"
                            IsEnabled="False"/>
                </StackLayout>
```

<img width="877" alt="Screen Shot 2021-06-12 at 12 01 52 AM" src="https://user-images.githubusercontent.com/41873/121765583-90d9af80-cb11-11eb-86e5-e528e5ab141a.png">

### Basic Information

- Version with issue: preview 5

### Reproduction Link

https://github.com/davidortinau/ControlGallery/blob/maui/src/ControlGallery/Pages/ButtonPage.xaml#L24

**Comment by VincentBu** [comment]
I run ControlGallery on monterey and the Font icon shows:
![ScreenShot](https://user-images.githubusercontent.com/44959937/156992518-7db78848-fbf3-4f51-88bd-da4eb1faef85.png)
:

**Comment by mattleibow** [comment]
This should be fixed in Preview 14. Please open another issue if there are still problems.
