### ISSUE TITLE
[Bug] New Project is not buliding

### ISSUE THREAD

**Issue by uzairali001** [dotnet/maui#1287]
### Description
Newly created project of maui-blazor is not building showing this error
```2>F:\Maui\PresentationApp\PresentationApp\PresentationApp.csproj : warning NU1603: Microsoft.AspNetCore.Components.WebView.Maui 6.0.100-preview.5.751 depends on Microsoft.Maui.Controls (>= 6.0.100-preview.5.751) but Microsoft.Maui.Controls 6.0.100-preview.5.751 was not found. An approximate best match of Microsoft.Maui.Controls 6.0.100-preview.5.753 was resolved.
2>F:\Maui\PresentationApp\PresentationApp\PresentationApp.csproj : warning NU1603: Microsoft.AspNetCore.Components.WebView.Maui 6.0.100-preview.5.751 depends on Microsoft.Maui.Core (>= 6.0.100-preview.5.751) but Microsoft.Maui.Core 6.0.100-preview.5.751 was not found. An approximate best match of Microsoft.Maui.Core 6.0.100-preview.5.753 was resolved.
2>F:\Maui\PresentationApp\PresentationApp\PresentationApp.csproj : error NU1102: Unable to find package Microsoft.Maui.Graphics with version (>= 6.0.100-preview.5.213)
2>F:\Maui\PresentationApp\PresentationApp\PresentationApp.csproj : error NU1102:   - Found 2 version(s) in nuget.org [ Nearest version: 6.0.100-preview.4.158 ]
2>F:\Maui\PresentationApp\PresentationApp\PresentationApp.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
2>Done building project "PresentationApp.csproj" -- FAILED.
```
### Steps to Reproduce

1.  Create new project => dotnet new maui-blazor --output TestApp
2. Build it (it will fail)
3. 

### Expected Behavior
Show build and run

### Actual Behavior
Not Building

### Basic Information

- Version with issue: 6.0.100-preview.4.*
- Last known good version: Don't know
- IDE:
- Platform Target Frameworks: net6.0-ios;net6.0-android;net6.0-maccatalyst
  - iOS:  Not tried
  - Android: Not tried
  - UWP:  Not tried
- Android Support Library Version: 
- Nuget Packages: Default comes with template
- Affected Devices:

**Comment by vanka78bg** [comment]
You need to add a NuGet.config file with the following or similar content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <!-- ensure only the sources defined below are used -->
    <add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
    <add key="dotnet-eng" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json" protocolVersion="3" />
    <add key="xamarin" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" />
    <add key="public" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <config>
    <add key="globalPackagesFolder" value="packages" />
  </config>
</configuration>
```

The above NuGet.config is taken from the [https://github.com/dotnet/maui-samples](Maui Samples). Perhaps the project template should include this file as a temporary solution to the problem.

**Comment by Eilon** [comment]
I think a custom nuget.config was needed with preview 4. But starting with preview 5, no nuget.config is needed because all the packages are either pre-installed, or they are on NuGet.org: https://www.nuget.org/packages/Microsoft.AspNetCore.Components.WebView.Maui/6.0.100-preview.5.794

**Comment by Eilon** [comment]
(_Checks date_ ...)

OK I think the issue is that this package wasn't on NuGet.org until _22_ days ago, whereas the bug was opened _25_ days ago.

**Comment by Eilon** [comment]
Oh wait I see what's happened. The original poster was _trying_ to use preview 4, but presumably without a custom nuget.config, so some other version was found on some feeds.

* If you're using .NET MAUI Preview 4, follow the instructions on this blog post with the custom nuget feeds: https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-4/
* If you're using .NET MAUI Preview 5 (currently the latest), follow the instructions on this blog post: https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-5/

**Comment by Depechie** [comment]
I have the same issue...
```
Unable to find package Microsoft.Maui.Graphics with version (>= 6.0.100-preview.7.358)
  - Found 3 version(s) in nuget.org [ Nearest version: 6.0.100-preview.5.229 ]
  - Found 0 version(s) in /usr/local/share/dotnet/library-packs
```
Running dotnet 6.0.100-preview.7.21379.14 on Mac

**Comment by Eilon** [comment]
@Depechie I'm seeing that exact version of the package on nuget.org here: https://www.nuget.org/packages/Microsoft.Maui.Graphics/6.0.100-preview.7.358

**Comment by Eilon** [comment]
And it's been there for nearly 2 weeks... so I'm not sure why it wouldn't be found. If this is perhaps a NuGet client caching issue, you can clear all NuGet caches by running `dotnet nuget locals all --clear` from the command line.

**Comment by Depechie** [comment]
@Eilon I know `dotnet nuget locals all -c` did indeed fix it!
Forgot to report back... not sure why it would hassle for older versions though a newer one should be downloaded if cache has older versions I guess.
But in the end it is fixed.

**Comment by Eilon** [comment]
@Depechie yeah if clearing the NuGet cache fixed it, then it's possible that there's a bug with NuGet somehow. I'm glad you got it working!
