### ISSUE TITLE
[Bug] Theme Mode Maui

### ISSUE THREAD

**Issue by mohammadaminyza** [dotnet/maui#1288]
Hi I'm Using Visual Studio Preview16.11.
When I Used Application.Current.UserAppTheme In Android 11 Api 30 , value was Unspecified.
But I'm Using Same Code In Xamarin Forms And It's Working.

**Comment by jfversluis** [comment]
Hi there @mohammadaminyza thanks for the report!

I hope this is fixed by now, if not, would you mind opening a new issue using the bug report template? That will give us a lot of valuable information and will help us get to fix this quicker. Thanks!
