### ISSUE TITLE
DatePicker Focused, UnFocused not working as expected

### ISSUE THREAD

**Issue by edgarfgp** [dotnet/maui#12899]
### Description

Preciously on XF DatePicker `Focused` and `UnFocused` events were triggered when opening and closing the date picker dialog

Now in Maui is not longer the case

### Steps to Reproduce

1. Open MauiApp2
2. Set breakpoints on DatePicker Focus and Unfocused events 
3. Run the app
5. Interact with DatePicker 

Note: See the video attached for more info 

Expected: 
- Focused should trigger when the DatePicker dialog is opening
- UnFocused should trigger when the DatePicker dialog is closing

Current: 
- Focused is not trigger when the DatePicker dialog is opening
- UnFocused is not trigger when the DatePicker dialog is closing

https://user-images.githubusercontent.com/31915729/214537202-0d8d9cc0-f851-4a4a-9e5d-30641af9711f.mov

### Link to public reproduction project repository

https://github.com/edgarfgp/DatePickerBugRepro

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android 11

### Did you find any workaround?

Write a Custom DatePicker Handler to set the `VirtualView.IsFocused`

**Comment by TimLariviere** [comment]
Please note that this affects both iOS and Android.

**Comment by PureWeen** [comment]
@TimLariviere @edgarfgp are you primarily using the focused/unfocused events to figure out if the picker dialog is open/closed?

**Comment by edgarfgp** [comment]
@PureWeen Yes, we use it basically for that to be able to change / animate the state of our custom controls

**Comment by SagarPanwala** [comment]
@PureWeen @jsuarezruiz As this issue has been resolved now, when it's going to be released 😬?
