### ISSUE TITLE
iOS label within horizontalstacklayout overflowing container

### ISSUE THREAD

**Issue by duindain** [dotnet/maui#12895]
### Description

Adding a label inside a horizontal stack layout allows the label content to overflow outside its parent container
The width of the parents container is visible using the green background

![Image showing label content overflowing outside of its parents constraints](https://github.com/duindain/mauiBrokenLabeliOS/blob/main/Simulator%20Screen%20Shot%20-%20iPad%20Pro%20(12.9-inch)%20(6th%20generation)%20-%202023-01-25%20at%2012.57.24.png?raw=true)

There was a similiar bug in .Net 6 reported here https://github.com/dotnet/maui/issues/9639

I've tried setting VerticalOptions and Horizontal ones the only setting that had an effect was setting IsClippedToBounds to true
This did limit the label to the bounds of the horizontalstacklayout but only one line of text is shown

### Steps to Reproduce

Add a Grid with * column width
Add a Stacklayout as the only child
Add a background color to the stacklayout for visibility on the issue
Add a label with more content that can fit on one line

The label will overflow outside of the stacklayouts contraints

### Link to public reproduction project repository

https://github.com/duindain/mauiBrokenLabeliOS

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

### Did you find any workaround?

IsClippedToBounds stops the label growing outside its container but doesnt allow the label to grow vertically

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11 and  iOS 16.4 with below Project:

[mauiBrokenLabeliOS-main.zip](https://github.com/dotnet/maui/files/11783670/mauiBrokenLabeliOS-main.zip)
Result in Windows 11: The label will overflow outside of the stacklayouts contraints
![image](https://github.com/dotnet/maui/assets/131441429/fbd8418f-71eb-4bba-b460-1bb1fdebc5bc)
Result in iOS 16.4: only one line of text is shown,but doesnt allow the label to grow vertically
![image](https://github.com/dotnet/maui/assets/131441429/78a5bfa9-eea0-4801-bf32-b5f0091fad46)

**Comment by softeip** [comment]
I was able to make it work by setting HorizontalOptions="FillAndExpand" on the Label and wrapping it into a Grid like this

```
<Grid
        HorizontalOptions="FillAndExpand"
        ColumnDefinitions="*">
        <Label
            HorizontalOptions="FillAndExpand"
            LineBreakMode="TailTruncation"
            Text="Long text here"
            />
</Grid>
```

**Comment by hartez** [comment]
This is the expected behavior for a Label in a HorizontalStackLayout. The HSL allows the Label to be as wide as it wants to be; there's no width constraint which would cause it to wrap.

If you want the Label text to wrap, you have to constrain its width. You can do this by setting the `WidthRequest` property, or in your example you can simply remove the HorizontalStackLayout:

```xaml
<Grid WidthRequest="700">
	<Label
		BackgroundColor="Green"
		Text="..."
		LineBreakMode="WordWrap"/>           
</Grid>
```
