### ISSUE TITLE
Reassigning Picker.ItemsSource does not trigger refresh of page

### ISSUE THREAD

**Issue by DrHardReset** [dotnet/maui#12891]
### Description

The Picker visible on the page does not refresh when assigning a new list to the Picker's ItemsSource.
The Picker still shows the values of the initially assigned list, although it's ItemsSource points to the new list while debugging.

### Steps to Reproduce

1. Create a Picker and assign a List<string> list1 to it's ItemsSource.
2. During runtime assign a List<string> list2 to Picker's ItemsSource.
3. On the visible page the Picker still shows values of list1 instead of list2.

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">

    <ScrollView>
        <VerticalStackLayout
            VerticalOptions="Center">

            <Picker
                x:Name="Picker1"
                WidthRequest="200"/>
            
            <Button
                x:Name="Button1"
                Text="Change List"
                WidthRequest="200"
                Clicked="OnButtonClicked"/>

        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```

```
namespace MauiApp1;

public partial class MainPage : ContentPage
{
    List<string> list1 = new List<string>() { "1" };
    List<string> list2 = new List<string>() { "2" };

    public MainPage()
    {
        InitializeComponent();
        Picker1.ItemsSource = list1;
        Picker1.SelectedIndex = 0;
    }

    private void OnButtonClicked(object sender, EventArgs e)
    {
        Picker1.ItemsSource = list2;
        Picker1.SelectedIndex = 0;
    }
}
```

Hint 1:
The problem does not occur when doing the same thing with a ComboBox in a WPF app. 

Hint 2:
When changing the ItemsSource multiple times in the MainPage constructor, the last assigned list's values are correctly shown on page:

```
namespace MauiApp1;

public partial class MainPage : ContentPage
{
    List<string> list1 = new List<string>() { "1" };
    List<string> list2 = new List<string>() { "2" };

    public MainPage()
    {
        InitializeComponent();
        Picker1.ItemsSource = list1;
        Picker1.ItemsSource = list2;
        Picker1.SelectedIndex = 0;
    }
}
```

### Link to public reproduction project repository

https://github.com/DrHardReset/MAUI_NET7_PickerItemsSource_Issue

### Version with bug

6.0

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

windows10.0.19041.0

**Comment by PureWeen** [comment]
It looks like you're repro is still on net6 https://github.com/DrHardReset/MAUI_NET7_PickerItemsSource_Issue/blob/main/MauiApp1/MauiApp1.csproj#L5



can you try net7?

**Comment by DrHardReset** [comment]
@PureWeen I already tried net7 but I didn't get any net7 MAUI app to start. Today I found the workaround in [issue 12080](https://github.com/dotnet/maui/issues/12080)
Now I can confirm that the issue does not appear with net7.
But I thought net6 would have LTS? Why is this not fixed in net6?

**Comment by DrHardReset** [comment]
Why is this closed? Net6 LTS still contains this bug.
