### ISSUE TITLE
[Enhancement] 3D graphics bindings

### ISSUE THREAD

**Issue by deviloper** [dotnet/maui#129]
## Summary

I make .net tools for 3D data processing and rendering and I found .Net lacks of a low level engine to make custom 3D applications for architecture and engineering.

I tried to embed Urho3D and some WPF toolkits but they are too high-level and OS specific.

Unity 3D is another possible choice but it is not embeddable, its workspaces merge 3D models and code in a unmaintainable way and it hasn't a 2D UI library.

So what about to include in MAUI something like a webgl engine just to enable 3D graphics to run in. NET on all platforms?

## API Changes

The 3D environment could be implemented in a specific control within its namespace (System.MAUI.GL)

## Intended Use Case

Move applications for architecture, design and engineering to .NET 6.

**Comment by Happypig375** [comment]
UrhoSharp is not platform-specific. Like SkiaSharp, it targets .NET Standard 2.0 and is cross-platform.

**Comment by deviloper** [comment]
> UrhoSharp is not platform-specific. Like SkiaSharp, it targets .NET Standard 2.0 and is cross-platform.

Yes, urhosharp is a cross-platform engine, but I didn't find an access to low level graphics and render models with custom shaders.

Game engines also use y-up coordinate systems and sometimes clockwise rotations and this is not common in engineering.

**Comment by charlesroddie** [comment]
This is a request for low level cross-platform dot net 3d graphics.

MAUI is not the right place for this as you would want this to work across all .Net UI projects not just MAUI.

Also WebGL is not suitable as that is for web.

I don't use 3D graphics but from a quick search the project that would come closest to meeting your needs is [OpenTK](https://github.com/opentk/opentk). Is there a reason you don't mention this?

**Comment by deviloper** [comment]
@charlesroddie thank you for the response.

I tried many engines and libraries, but I didn't find a good solution in .NET (C++ and JS have the best solutions at the moment).

I mentioned webgl as an example because it's a good abstraction on both hardware and graphics libraries (for cross platform applications, even if run in a webview), and at the same time it gives the developer the possibility to work on shaders and define custom materials with parameters.

I know OpenTK and it has been a good project for. NET Framework. 

About cross-platform I don't think it's a good solution because it lays on OpenGL and it could be dropped on some devices in future (see Metal on Mac). Furthermore OpenTK is a bit "slow" in following .NET releases (I'm still waiting for a stable version which is compatible with .NET Core) and it's not supported by Microsoft.

Maybe the best way to add 3D Graphics in. NET could be to add an internal low level engine with bindings for each UI framework. 

This would make. NET suitable for many cross platform applications and increase its adoption through new markets.

**Comment by charlesroddie** [comment]
@deviloper So you are looking for an .net abstraction layer that can deploy to multiple low level frameworks. I agree that this would be very good for cross-platform development, and while it wouldn't be in Maui in a strict sense, it would be a similar/allied project.

Have you tried https://github.com/mellinoe/veldrid ?

> Veldrid is a cross-platform, graphics API-agnostic rendering and compute library for .NET. It provides a powerful, unified interface to a system's GPU and includes more advanced features than any other .NET library. Unlike other platform- or vendor-specific technologies, Veldrid can be used to create high-performance 3D applications that are truly portable.
>
> Supported backends: Direct3D 11, Vulkan, Metal, OpenGL 3, OpenGL ES 3

**Comment by deviloper** [comment]
@charlesroddie It seems to be an interesting project, I will try it in next days, thank you!
