### ISSUE TITLE
[Bug] New Project Does Not Build

### ISSUE THREAD

**Issue by DevCisse** [dotnet/maui#1291]
### Description
New Project created with VS 2019 Preview does not build
### Steps to Reproduce

1. Create New Project with VS 2019 preview 
2. Build
3. 

### Expected Behavior
Build and run
### Actual Behavior
Fails

### Basic Information

- Version with issue: VS 2019 16.11.0 preview 1.0
- Last known good version: No Idea
- IDE: VS 2019 Preview
- Platform Target Frameworks: 
  - iOS:  Nil
  - Android: 11.0
  - UWP:  Nil
- Android Support Library Version: 

### Screenshots

![image](https://user-images.githubusercontent.com/45653783/121782139-0b511080-cba0-11eb-80b9-7990530b656a.png)

**Comment by vanka78bg** [comment]
See my answer here: https://github.com/dotnet/maui/issues/1287#issuecomment-860555191
