### ISSUE TITLE
[Bug] initially invisible views don't work as expected

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#1293]
### Description

Testing on Android. Noticed here: https://github.com/davidortinau/WeatherTwentyOne/blob/67b35fbf42d5796b0cef944904f46162b4e0a9d2/src/WeatherTwentyOne/Pages/SettingsPage.xaml#L89

 - I noticed that in a compat layout, if a [handler] view is initially hidden (say via a binding) it never actually appears - even if it has an explicit size and a column space.  
 - I tried using a VerticalStackLayout, but they just ignored the visibility.
 - Switching to an ImageButton (renderer) it just never appears when the property changes.

**Comment by hartez** [comment]
This is fixed in the latest on main.
