### ISSUE TITLE
MAUI Blazor Publish is taking a very long time

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#12948]
### Description

MAUI Blazor publish is taking 30 minutes and increasing.

This is hampering development and testing.

### Steps to Reproduce

Create an Android 10 MAUI Blazor app and publish.

### Link to public reproduction project repository

none

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

No

### Relevant log output

```shell
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.52/7.0.100         VS 17.4.33213.308
maui-maccatalyst           7.0.52/7.0.100         VS 17.4.33213.308
maccatalyst                16.1.1481/7.0.100      VS 17.4.33213.308
maui-ios                   7.0.52/7.0.100         VS 17.4.33213.308
ios                        16.1.1481/7.0.100      VS 17.4.33213.308
android                    33.0.4/7.0.100         VS 17.4.33213.308
maui-android               7.0.52/7.0.100         VS 17.4.33213.308
wasm-tools-net6            7.0.2/7.0.100          VS 17.4.33213.308
wasm-tools                 7.0.2/7.0.100          VS 17.4.33213.308
```

**Comment by jfversluis** [comment]
What is the command you are using to publish? What are the NuGet packages you have installed?

Could you please provide relevant logs and preferably a binlog?
