### ISSUE TITLE
ApplyQueryAttributes when go back to one tab and two views is invoked in the wrong view

### ISSUE THREAD

**Issue by Victorbp09** [dotnet/maui#12957]
### Description

With Shell navigation and MVVM and NET6.0, if two pages exist in the same tab like:

```
<Tab Title="Search"
     Icon="search">
    <ShellContent Title="Page1"
                  ContentTemplate="{DataTemplate views:Page1View}" />
    <ShellContent Title="Page2"
                  ContentTemplate="{DataTemplate views:Page2View}" />
</Tab>
```

Both viewmodels (Page1ViewModel and Page2ViewModel) implement IQueryAttributable

And both views can access to another view (i.e. `SecondLevelPageView`), and from this page we invoke:
`await Shell.Current.GoToAsync($"..?test=hello");`

If I access to SecondLevelPageView from Page2View and go back with the previous code, it goes back to Page2View, this is correct. However, it's always the `ApplyQueryAttributes` method from `Page1ViewModel` which is invoked, and if I go back to `Page2View` it should be the `ApplyQueryAttributes` method from `Page2ViewModel` which should be invoked.

### Steps to Reproduce

1. Start the app TestErrorApplyQueryAttributes on Android
2. Go to tab "Page2"
3. Click button "Go to second level"
4. Click button "Go back"

### Link to public reproduction project repository

https://github.com/Victorbp09/TestErrorApplyQueryAttributes

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12 - API 31

### Did you find any workaround?

No. Use await Shell.Current.GoToAsync(nameof(Page2View), true) will invoke the constructor again, and this doesn't match with my requirements

**Comment by PureWeen** [comment]
I'm thinking this will be fixed [by](https://github.com/dotnet/maui/pull/12884)

You can try this workaround?
https://github.com/dotnet/maui/issues/8102#issuecomment-1401093844

**Comment by victorbeltranpinol** [comment]
@PureWeen Yes, your workaround works!
Thanks! 

I'm going to update MAUI version as well and I will try if it works with the new version and without your workaround

**Comment by Victorbp09** [comment]
Not working updating to the last MAUI version. Right now, it only works with the @PureWeen workaround
