### ISSUE TITLE
he program '[17988] myFirstMauiApp.exe' has exited with code 2147942405 (0x80070005)

### ISSUE THREAD

**Issue by dovoosh** [dotnet/maui#12965]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by affableashish** [comment]
Seems similar or the same as https://github.com/dotnet/maui/issues/12080

Workaround: https://github.com/dotnet/maui/issues/12080#issuecomment-1377243186
