### ISSUE TITLE
[Regression] [Android] ImageButton with Clip and bound IsVisible property does not display

### ISSUE THREAD

**Issue by mfeingol** [dotnet/maui#12972]
### Description

This ImageButton will not display on Android when the IsButtonVisible property defaults to false and then is set to true:

```xml
            <ImageButton WidthRequest="100" HeightRequest="100" Aspect="AspectFit" HorizontalOptions="Center" VerticalOptions="Center" Source="dotnet_bot.png" IsVisible="{Binding IsButtonVisible}" Clicked="OnCounterClicked">
                <ImageButton.Clip>
                    <EllipseGeometry Center="50,50" RadiusX="50" RadiusY="50"/>
                </ImageButton.Clip>
            </ImageButton>
```

If you remove the Clip property, or default IsButtonVisible to true, then the Imagebutton will display just fine. It is as if the binding change is not picked up by the ImageButton, but it only happens when there's a Clip property set as above.

### Steps to Reproduce

Run the attached repro. Observe that the first ImageButton fails to display, while the other two do.

### Link to public reproduction project repository

https://github.com/mfeingol/repros/tree/master/ImageButtonClipRepro

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

Using CornerRadius instead of the Clip works. Wrapping the ImageButton in a Grid also works. But this is a bug.

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Android emulator (13.0-API 33) but not on Windows 11 with below Project
[MauiApp6.zip](https://github.com/dotnet/maui/files/11785605/MauiApp6.zip)

Screenshot
![image](https://github.com/dotnet/maui/assets/131441429/61babb1c-2877-4d44-9e94-caa415eae1e4)

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue with the latest version:
![issue-12972](https://github.com/dotnet/maui/assets/6755973/7d574ae8-407d-4e78-a29f-fa7f279dfd1f)
