### ISSUE TITLE
Toast throws exception on Windows

### ISSUE THREAD

**Issue by cdavidyoung** [dotnet/maui#12976]
### Description

With the most recent updates Toast is now throwing an exception on Windows but works fine on the Mac.  This is a simple mod to the standard Maui app that illustrates the problem.  If you run this and set a breakpoint on the exception it stops when you press the button.

```cs
using CommunityToolkit.Maui.Alerts;
namespace TooltipsSample;

public partial class MainPage : ContentPage
{
	int count = 0;

	public MainPage()
	{
		InitializeComponent();
	}

	private void OnCounterClicked(object sender, EventArgs e)
	{
		count++;
        CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
        var toast = Toast.Make("Toast");
        try
        {
#pragma warning disable CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
            toast.Show(cancellationTokenSource.Token);
#pragma warning restore CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
        }
        catch (Exception ex)
        {
            // This gives an exception on Windows
        }
 
        if (count == 1)
			CounterBtn.Text = $"Clicked {count} time";
		else
			CounterBtn.Text = $"Clicked {count} times";

		SemanticScreenReader.Announce(CounterBtn.Text);
	}
}
```

### Steps to Reproduce

See the description for sample code.

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

windows10.0.19041

### Did you find any workaround?

use try/catch to not crash but Toast not working

### Relevant log output

```shell
{"Could not load file or assembly 'Microsoft.Windows.AppNotifications.Builder.Projection, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.":"Microsoft.Windows.AppNotifications.Builder.Projection, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null"}
```

**Comment by VladislavAntonyuk** [comment]
Make sure you have Windows SDK version at least version 1.2
You can install it manually in your csproj as a workaround

**Comment by cdavidyoung** [comment]
Well, it looks like windows10.0.19041 to me.  I am not sure where you are getting 1.2.  Could you clarify?  Do I need to update Windows, VS 2022, a Nuget package?

**Comment by VladislavAntonyuk** [comment]
@cdavidyoung install this NuGet package: https://www.nuget.org/packages/Microsoft.WindowsAppSDK

**Comment by mattleibow** [comment]
What version of the OS are you running?

**Comment by jfversluis** [comment]
This issue was moved to CommunityToolkit/Maui#946
