### ISSUE TITLE
.Net MAUI 7 Android, Image Gif Animation Not Playing in Release Mode, Normal in Debug Mode 

### ISSUE THREAD

**Issue by syachrodi** [dotnet/maui#12974]
### Description

I tried to release the .net maui apps that I made, when in debug mode everything works fine, but the problem occurs when I release my application to Android, the gif image that I use for loading doesn't work properly, no animation is playing, it only displays the native image. 

Then I tried to make a simple application to confirm this problem, and yes, the problem remains the same, here I attach the simple code that I made, where this coding runs normally in debug mode, but in release mode the gif animation doesn't play

### Steps to Reproduce

The simple code

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MiCetApp.View.StartPage"
             Title="StartPage"
             BackgroundColor="#6789ba"
             Shell.NavBarIsVisible="False">
    <Grid
        RowDefinitions="*, Auto, Auto">
        <Image
            HeightRequest="150"
            Source="{Binding StringFormat=Resources/Images/loading_animation}"
            IsAnimationPlaying="False"
            x:Name="gifAnimation"/>

        <Button
            Grid.Row="1"
            Text="Play Animation"
            Clicked="PlayAnimation"/>

        <Button
            Grid.Row="2"
            Text="Pause Animation"
            Clicked="PauseAnimation"/>
    </Grid>
</ContentPage>
```

```cs
private void PlayAnimation(object sender, EventArgs e)
{
    gifAnimation.IsAnimationPlaying = true;
}

private void PauseAnimation(object sender, EventArgs e)
{
    gifAnimation.IsAnimationPlaying = false;
}
```

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11.0 API 31.0

**Comment by syachrodi** [comment]
<Grid
        RowDefinitions="*, Auto, Auto">
        <Image
            HeightRequest="150"
            Source="{Binding StringFormat=Resources/Images/loading_animation}"
            IsAnimationPlaying="False"
            x:Name="gifAnimation"/>

        <Button
            Grid.Row="1"
            Text="Play Animation"
            Clicked="PlayAnimation"/>

        <Button
            Grid.Row="2"
            Text="Pause Animation"
            Clicked="PauseAnimation"/>
    </Grid>

private void PlayAnimation(object sender, EventArgs e)
    {
        gifAnimation.IsAnimationPlaying = true;
    }

    private void PauseAnimation(object sender, EventArgs e)
    {
        gifAnimation.IsAnimationPlaying = false;
    }

**Comment by NonameMissingNo** [comment]
Hey there, can you put up a repo?

**Comment by syachrodi** [comment]
> Hey there, can you put up a repo?

https://github.com/syachrodi/MiCetApp

**Comment by hg15671855182** [comment]
I also encountered the same problem, which urgently needs to be solved!

**Comment by rfangzh** [comment]
Is there any workaround to this issue, please?

**Comment by fariz-huseynov** [comment]
Works neither on IONS nor Android

**Comment by ea543** [comment]
not work on iOS and Android +1

**Comment by sheharyarshahid** [comment]
I was able to resolve by simply doing this

`protected override async void OnAppearing()`
    `{`
             `base.OnAppearing();`
        `await Task.Delay(100);`
        `BreatheImageLoader.IsAnimationPlaying = false;`
        `await Task.Delay(100);`
        `BreatheImageLoader.IsAnimationPlaying = true;`
    `}`

**Comment by syachrodi** [comment]
> I was able to resolve by simply doing this
> 
> `protected override async void OnAppearing()` `{` `base.OnAppearing();` `await Task.Delay(100);` `BreatheImageLoader.IsAnimationPlaying = false;` `await Task.Delay(100);` `BreatheImageLoader.IsAnimationPlaying = true;` `}`

Has been try in release mode?

**Comment by jmc5018** [comment]
protected async override void OnAppearing()
        {
            base.OnAppearing();
            await Task.Delay(100);
            imgLoader.IsAnimationPlaying = false;
            await Task.Delay(100);
            imgLoader.IsAnimationPlaying = true;
        }

I did the same thing and it works fine in Debug but does not work in Release.

**Comment by xufeitt** [comment]
anyone solve this problem ?

**Comment by ea543** [comment]
no2023年5月23日 14:25，xufeitt ***@***.***>寫道：
anyone solve this problem ?

**Comment by ea543** [comment]
> 

no@@

**Comment by Buryyy** [comment]
> protected async override void OnAppearing() { base.OnAppearing(); await Task.Delay(100); imgLoader.IsAnimationPlaying = false; await Task.Delay(100); imgLoader.IsAnimationPlaying = true; }
> 
> I did the same thing and it works fine in Debug but does not work in Release.

Doesn't work in Release. Any solutions?

**Comment by Buryyy** [comment]
Any fix?

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Android emulator (13.0-API 33) and  iOS 16.4 with below Project:
[MauiApp14.zip](https://github.com/dotnet/maui/files/11786284/MauiApp14.zip)
Screenshot:
![image](https://github.com/dotnet/maui/assets/131441429/2223c43a-4ffd-4ebd-af17-7487f72cf1ac)

**Comment by ecosimini** [comment]
Been watching this one since March hoping it would get fixed before my app release but doesn't look like it's been started yet. I know you guys have your hands full with others issues but this does seem like basic functionality that should get fixed. Any update on when a fix for this might go out? Thank you MAUI team.

**Comment by ea543** [comment]
> 

thanks,It`s workaround for me.

**Comment by ecosimini** [comment]
@umeshkamble I got excited when I saw this but tried it out and it doesn't work for Android release builds :(  GetDataAsync is only supported for ios and maccatalyst. Is there any similar method that would work for Android?

**Comment by Vito258** [comment]
I think playing GIFs is a basic feature, but I struggled to figure it out in maui, which is ridiculous! To this day, there is still no good way to solve this problem

**Comment by msrockswell** [comment]
The playback of GIFs is a basic function. The ticket is almost 1 year old already. When will the problem be fixed?

**Comment by echolumaque** [comment]
2024 is just around the corner and this issue is still not fixed. 👎🏻

**Comment by billreiss** [comment]
I've experimented with using WebView to play a GIF in MAUI, it works on Android and iOS, on Windows I use the native support because it seems to work fine and I didn't want to troubleshoot what was going wrong with the WebView on Windows. I'm working on building out a sample, but if anyone needs something sooner let me know. What I don't have working yet is to honor HeightRequest or WidthRequest.

**Comment by msrockswell** [comment]
[umeshkamble](https://github.com/umeshkamble) [Gif Animation Sample](https://github.com/umeshkamble/GifAnimation) The gif is played much too slowly.

With FFImageLoading works under iOS. Android doesn't work. 

Does anyone know a Nuget alternative to ffimageloading?

**Comment by billreiss** [comment]
Using WebView to animate GIF on iOS and Android https://github.com/billreiss/MauiGifWebView

**Comment by dora-emo** [comment]
Any fix? When will the problem be fixed?

**Comment by msrockswell** [comment]
@billreiss : Nice Workaround for NET8. 

I need a Workaround for NET7. Does anyone know a example?

**Comment by Dryzler** [comment]
I am waiting for a fix :(

**Comment by mrnams** [comment]
Not working in .net8.0

**Comment by ssbssb-cmd** [comment]
has anyone found any workaround? how to play animated gif in MAUI?

**Comment by bhuwancb99** [comment]
I've been waiting for over a year, and it's still not fixed. I'm so frustrated with MAUI that I've now switched to Flutter for mobile application development. They don't seem to be addressing basic issues like the release animation problem and the Android scroll bar not being visible. In comparison, Flutter is far superior.

**Comment by msrockswell** [comment]
Now it works on .NET 7. NuGet Update 1.1.3 & csproj None Remove gif.

**Comment by Redth** [comment]
As a workaround you can load the .gif into a webview.

1. Copy the .gif to `Resources/Raw/my.gif` folder of your project
2. Add a .html file (see below) to `Resources/Raw/my.html`
3. Add a web view: `<WebView HeightRequest="200" WidthRequest="200" x:Name="webView" />`
4. In your code behind, set the source:

```csharp
webView.Source = new UrlWebViewSource {
  Url = "file:///android_asset/my.html"
};
```

HTML File eg:

```html
<html>
<body style="background-color: #ffffff; padding: 0; margin: 0;">
    <img src="my.gif" width="200" height="200">
</body>
</html>
```

This works in release mode in my testing.  It's not ideal, but it's a workaround until we can figure out and eventually fix why release mode is not animating.

**Comment by ea543** [comment]
As a new workaround on https://github.com/microspaze/FFImageLoading.Maui for me~ Perfect~

**Comment by Matthias5555** [comment]
Hello I got a Workaround for Android.  A Gif is basically just a SpriteSheet , a list of Pictures which are played after another. So I have an Image Object in Xaml and a Class which does basically that. 
I Only testet it on Android Release and Debug build, both works. (IOS should probably also work)( I am in .Net 8 newest Version of Maui

Xaml:
                    <Image 
                           x:Name="Loadspinner" >
                    </Image>

GifLoader Class:

    public class GifLoader
    {

        private List<string> SpriteImagesList {  get; set; } = new List<string>();

        private Image? ImageObject {  get; set; }

        public int MillisecondsDelay { get; set; } = 100;

        public bool IsAnimationPlaying { get; set; } = false;

        public GifLoader(List<string> SpriteImages, Image image)
        {
            if(SpriteImages != null && SpriteImages.Count > 0)
            {
                SpriteImagesList = SpriteImages;
            }
            if(image != null)
            {
                ImageObject = image;
            }

        }

        public void StopAnimation()
        {
            IsAnimationPlaying = false;
        }

        public async void StartAnimation()
        {
            if (ImageObject == null){return;}
            
            IsAnimationPlaying = true;

            while (IsAnimationPlaying == true)
            {
                foreach (string spriteSource in SpriteImagesList)
                {
                    ImageObject.Source = spriteSource;

                    await Task.Delay(MillisecondsDelay);
                }
            }
        }

        public async void StartAnimation(int MillisecondsDelay)
        {
            if (ImageObject == null) { return; }

            IsAnimationPlaying = true;

            while (IsAnimationPlaying == true)
            {
                foreach (string spriteSource in SpriteImagesList)
                {
                    ImageObject.Source = spriteSource;

                    await Task.Delay(MillisecondsDelay);
                }
            }
        }
        
        
        Code On the xaml.cs
        
                List<String> gifSources = new List<String>()
        {
            "loadspinner1.png",
            "loadspinner2.png",
            "loadspinner3.png",
            "loadspinner4.png",
            "loadspinner5.png",
            "loadspinner6.png",
            "loadspinner7.png",
            "loadspinner8.png",
        };
        GifLoader loadspinnerGif = new GifLoader(gifSources, Loadspinner);
        loadspinnerGif.StartAnimation();
        
        
        So first you'll need to split up the gif in its pictures there are severel websites which do these, you can also make that by  youre self. 
        You Import the Images into Resources/Images in youre Maui Project.
        After that you can add the GifLoader Class in a new .cs file
        Now you just need to create an GifLoader Object with the Source paths of youre pictures.
        (Its important thats in the right order)
        you can Start and Stop the Animation with the Method given in the GifLoader. 
        
        This worked for me, i hope it also does for you ,comment if theres a better workaround or already fixed. Thanks

**Comment by mattleibow** [comment]
I think I found out _why_ the animations are not playing, now I just need to find a solution.

When setting the drawable, the type is a `android.graphics.drawable.AnimatedImageDrawable` which _should_ be an `Android.Graphics.Drawables.IAnimatable`. However, in Release builds it appears to lose that interface...

**Comment by mattleibow** [comment]
I think I have found a way to make it work, however I discovered that Glide only loads GIF files in Android 28+ for some reason. I see they register Stream -> Drawable for animations in 28+:

https://github.com/bumptech/glide/blob/a7351b0ecf6656ad937fbc52fe9e90d3b289c265/library/src/main/java/com/bumptech/glide/RegistryFactory.java#L175-L179

However, they just decide to only register Stream -> GifDrawable in older:

https://github.com/bumptech/glide/blob/a7351b0ecf6656ad937fbc52fe9e90d3b289c265/library/src/main/java/com/bumptech/glide/RegistryFactory.java#L246-L250

This means unless you explicitly know you are loading a gif and you remember that you need to use `AsGif` in the builder, you don't get anyhting.

**Comment by mattleibow** [comment]
A workaround for this right now would be to make sure that there is a reference to the `AnimatedImageDrawable` type somewhere in your code.

```cs
class MauiProgram {
#pragma warning disable 0219, 0649
    static bool falseflag = false;
    static MauiProgram ()
    {
        if (falseflag) {
            var ignore = new AnimatedImageDrawable ();
        }
    }
#pragma warning restore 0219, 0649

    // ...
}
```

There is also an option to use a linker configuration to keep the type around: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options

However, since this was just fixed in the upcoming SR6 https://github.com/dotnet/maui/pull/22874 it may be easier to just use the false flag for now and delete once the SR is released.
