### ISSUE TITLE
`CodeBehindGenerator` has improper pipeline

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/maui#12978]
https://github.com/dotnet/maui/blob/83c3ac902ea496e409026c830ccd930c4021f8ab/src/Controls/src/SourceGen/CodeBehindGenerator.cs#L64-L67

This won't work well. Combining `CompilationProvider` and having `Compilation` as part of the pipeline will cause the generator to re-run on every change. So, it's not incremental at all. Note that `sourceProvider` is the last step.

~~This also roots `Compilation` objects in memory. See https://github.com/dotnet/roslyn-analyzers/issues/6352~~ (Edit: I don't think there is a memory leak concern in this case)

**Comment by Youssef1313** [comment]
Note: I think this needs a second look from Roslyn team.

**Comment by StephaneDelcroix** [comment]
@jonathanpeppers thoughts ?

**Comment by jonathanpeppers** [comment]
I asked in Teams ([private link](https://teams.microsoft.com/l/message/19:d16b7953d6a7442abdc84e59de75825e@thread.skype/1690295353703?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4ba7372f-2799-4677-89f0-7a1aaea3706c&parentMessageId=1690295353703&teamName=.NET%20Developer%20Experience&channelName=General&createdTime=1690295353703)), where some of the Roslyn folks are.

**Comment by jonathanpeppers** [comment]
The points in teams are:

1. The MAUI source generator is currently not incremental at all. It reruns on every keystroke.
2. This is likely not an easy thing to solve at all.

You can define any type in XAML and then give it a `x:Name`. But it really needs to rerun if types or their namespaces change?
So, if you added a method, maybe we wouldn't need to run the source generator in that case.

One comment from the Roslyn team:

> One possible approach here is to extract type/namespace names from source and metadata, and refresh that index when it changes.
> It's unfortunate that somewhat requires reiventing our decltrees.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 1.0. Can repro on android platform.

**Comment by mgoertz-msft** [comment]
Completed with PR #20524. Not sure why it didn't auto-complete this item.

**Comment by akoeplinger** [comment]
> Not sure why it didn't auto-complete this item.

Because the PR had `Fixes Issue #12978` but it needs to be `Fixes #12978` for GitHub to recognize it.
