### ISSUE TITLE
DataTemplateSelector on CollectionView is completely broken - templates don't match BindingContext

### ISSUE THREAD

**Issue by Vroomer** [dotnet/maui#12988]
### Description

Items in CollectionView utilizing DataTemplateSelector get often assigned to wrong DataTemplate. It appears to be a problem related to recycling views. While first items are usually displayed with correct DataTemplate, once the recycling kicks in the DataTemplates are mismatched. It's a serious issue as it makes the DataTemplateSelector unusable without any workaround. The problem was observed on Windows. Other platforms were not tested.

It might be the same problem as https://github.com/dotnet/maui/issues/11272. There is also a related PR to this issue right now https://github.com/dotnet/maui/pull/12011, but both the issue and PR mention only Android and iOS and the description of the problem is different. In my case the views get recycled, but incorrectly.

I made a sample showing list of colors to visualize the problem. Each row consists of two colors - one color assigned by DataTemplate and the other assigned by BindingContext.

![Screenshot 2023-01-30 000442](https://user-images.githubusercontent.com/26696962/215360754-d94b2cc6-8157-41a8-99bc-4824fb91509f.png)

### Steps to Reproduce

1. Load the repository and run the app.
2. Scroll the CollectionView to trigger virtualization.
3. Notice mismatched colors. Left half is the color assigned by DataTemplate, right half is color from BindingContext. Differences in numbers can help identify recycled views.

### Link to public reproduction project repository

https://github.com/Vroomer/MAUI-CollectionView-DataTemplateSelector-Bug.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.22621

**Comment by jsuarezruiz** [comment]
Related or the same as https://github.com/dotnet/maui/issues/11272

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on Windows platform with sample project.
[MAUI-CollectionView-DataTemplateSelector-Bug.git](https://github.com/Vroomer/MAUI-CollectionView-DataTemplateSelector-Bug.git)

**Comment by Vroomer** [comment]
![image](https://github.com/dotnet/maui/assets/26696962/3db53b34-0eb9-4630-8de3-f4bf0c3ad9ab)
![image](https://github.com/dotnet/maui/assets/26696962/fc5cf2e4-9b03-4d5b-9edd-19147aaa51f1)
@homeyf which version? I can still reproduce it in main branch 7.0.0-ci.net7.18626

**Comment by Eitsop** [comment]
I also have found this an issue (8.2.1) - I have ~130 entries to enumerate, though the `DataTemplateSelector` only gets called 25 times, then it appears the remaining entries are still mapped to the first 25 and no more calls are made.

**Comment by last-Programmer** [comment]
I am also facing this issue. Collectionview control is not usable with this bug if we have to vertically scroll. I am trying to convert the existing xamaring app to maui and stuck with this. cant migrate it without this bug is fixed. I am not sure when the maui team will fix this. Maui is not yet ready for production yet.
