### ISSUE TITLE
Maui App crashes on an android device when navigating to another page

### ISSUE THREAD

**Issue by ikeoriaku123** [dotnet/maui#12980]
### Description

My App keeps crashing on an android device. When navigating to another page using this
await Current.MainPage.Navigation.PushModalAsync(new NavigationPage(new PopupPage(viewModel))); or
await Current.MainPage.Navigation.PushModalAsync(new OfferListPopupPage(viewModel));
It is find when you delete the app and redeploy to an android device again. This is fine on iphone device but not android device. Any help will be appreciated.

### Steps to Reproduce

1. Run app via debug mode
2. Click on view profile to open a popup page via await Current.MainPage.Navigation.PushModalAsync
3. App crashes

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 5 - Android 11

### Did you find any workaround?

The workaround is to delete the app and redeploy. Then it is fine. But after several debugging, it introduces it again

### Relevant log output

```shell
--- End of managed Java.Lang.ClassCastException stack trace ---
java.lang.ClassCastException: android.widget.ImageView cannot be cast to android.view.ViewGroup
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:504)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by PrestigiousF** [comment]
I can try to assist in this... I'm fairly new to MAUI, but I do something similar in my app and I don't have issues pushing a new page on Android...

I can say, just try 

`var page = new OfferListPopupPage();
await Shell.Current.Navigation.PushAsync(page);` 

and bind your view model in the page via.  xaml/cs instead?

`<ContentPage.BindingContext>
<whatever:viewmodelclasshere>
</ContentPage.BindingContext>`

Also are you using any form of dependency injection?

**Comment by PrestigiousF** [comment]
Is you ImageView by any chance
 `<ImageView x =blahblah></ImageView>`?
if so.. change it to `<ImageView x =blahblah/>`

ImageView isn't capable of hosting view, so if you have it wrapped around your ViewGroup, this error will be shown.

**Comment by ikeoriaku123** [comment]
> Is your ImageView by any chance `<ImageView x="blahblah"> Some other view here </ImageView>`? if so.. change it to `<ImageView x="blahblah"/>`
> 
> ImageView isn't capable of hosting view, so if you have it wrapped around your ViewGroup, this error will be shown.

I do not have any ImageView. It's when calling the pushmodalasync that it errors

**Comment by ikeoriaku123** [comment]
I am unable to replicate when I create a new project. What I have observed is in the current project I am working on is whenever doing a fresh install, the app doesn't crash when this await Current.MainPage.Navigation.PushModalAsync(new NavigationPage(new PopupPage(viewModel))) is called. When you re-run to update the app, it fails on pushmodalasync. It's only fine when you delete the app and reinstall. This happens on both debug and release. Please can someone help as I have no clue why my app is behaving this way.

**Comment by ikeoriaku123** [comment]
This issue can be closed as I have decided to use Mopups and I am not getting any error. Thanks
