### ISSUE TITLE
How to disable bitcode strip in Plugin.Firebase in .net 7. It causing issue in iOS in .net MAUI, unable to make release build.

### ISSUE THREAD

**Issue by deepikacis** [dotnet/maui#12993]
### Description

I am facing below issue for GoogleAppMeasurement in iOS when making release build  :
C:\Users\abc\.nuget\packages\xamarin.firebase.ios.core\8.10.0.3\buildTransitive\Xamarin.Firebase.iOS.Core.tar
gets(216,5): error MSB3073: The command ""$(xcrun -find bitcode_strip)" C:/Users/abc/AppData/Local/XamarinBui
ldDownloadCache/GAppM-8.9.1/GoogleAppMeasurement-8.9.1/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/Goog
leAppMeasurement.framework/GoogleAppMeasurement -r -o C:/Users/abc/AppData/Local/XamarinBuildDownloadCache/GA
ppM-8.9.1/GoogleAppMeasurement-8.9.1/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/GoogleAppMeasurement.f
ramework/GoogleAppMeasurement" exited with code 1. [D:\iOSNotification\iOSNotification\iOSNotification.csproj::TargetFr
amework=net7.0-ios]

I have tried the workaround https://github.com/dotnet/maui/issues/10989 but still facing  below issue for Google Sign In :
D:\MauiFirebaseDemo-master\MauiFirebaseDemo\MauiFirebaseDemo.csproj(148,3): error MSB3073: The command ""$(xcrun -find
bitcode_strip)" C:/Users/abcd/AppData/Local/XamarinBuildDownloadCache/GSgnI-5.0.2/Frameworks/GoogleSignIn.fram
ework/GoogleSignIn -r -o C:/Users/abcd/AppData/Local/XamarinBuildDownloadCache/GSgnI-5.0.2/Frameworks/GoogleSi
gnIn.framework/GoogleSignIn" exited with code 1. [TargetFramework=net7.0-ios]

### Steps to Reproduce

Have implemented fcm push notification in  MAUI having .net version 7 from the below link : https://cedricgabrang.medium.com/firebase-push-notifications-in-net-maui-ios-2f4388bf1ac
 
For testing , creating release build to test on physical device but unable to create build because facing bitcode issue.

### Link to public reproduction project repository

#10989

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

iOS

### Affected platform versions

iOS16

**Comment by deepikacis** [comment]
@jfversluis @jamesmontemagno

**Comment by HobDev** [comment]
Facing same issue

**Comment by mattleibow** [comment]
This issue was moved to xamarin/xamarin-macios#17402
