### ISSUE TITLE
Build `Android` fail

### ISSUE THREAD

**Issue by Coloryr** [dotnet/maui#12990]
### Description

```
No Android SDK instance matching the 'E:\Android' path
--- Items to install
NDK : ndk-bundle
```

Install fail

![VF2)%~OQ`RPSGA2POM5(6@1](https://user-images.githubusercontent.com/26276037/215399126-dfae9c7f-be83-4a2d-93a3-7184abd8ca2e.png)
![ERI S4V%Y (F`(IOOYW_QVH](https://user-images.githubusercontent.com/26276037/215399433-30af46e7-5396-4534-bea6-96995a11e185.png)
![@W}C5FA%NA~CA6GUE2AN992](https://user-images.githubusercontent.com/26276037/215399459-b6788bf0-d65d-4b66-b27a-26f5d3460954.png)
![@(W$UAUY_{QK{8~97R769`E](https://user-images.githubusercontent.com/26276037/215399541-f4e3df06-e900-4d45-8a5a-af9fcc58b5c1.png)

### Steps to Reproduce

just build the project

### Link to public reproduction project repository

Maui app template

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Android

### Affected platform versions

win11

**Comment by Coloryr** [comment]
Install `NDK 22.1.7171670` no work

**Comment by jfversluis** [comment]
Hi there! Unfortunately based on just this information it's a bit hard to diagnose what is going wrong. 

It seems like you're using JetBrains products? Did you have a look with them if there are any issues? If I look at the issue reported it seems to say that there is no Android SDK found at the location you have specified which is E:\Android. What are the contents of that folder? Are you sure there is a valid Android installation in there?

Do you have any more extensive build logs maybe?

Thanks!

**Comment by Coloryr** [comment]
> 

It can't auto install need files

**Comment by Coloryr** [comment]
![CH42U{G_F%4H{11U)T@J8O](https://user-images.githubusercontent.com/26276037/215657563-7ee3960e-2ba1-4838-a719-aa1058fef5ad.png)
![NPQX_VQ3P_6S5ZE_U~D`74S](https://user-images.githubusercontent.com/26276037/215657636-508b94e2-a61a-45d8-86a6-d712a3855041.png)

**Comment by Coloryr** [comment]
![OZ(}SSYZ62A3%VJ0 XL SY9](https://user-images.githubusercontent.com/26276037/215657838-c0b8a46a-b510-409c-ae81-83e16d498a6e.png)

**Comment by Coloryr** [comment]
when i create a new project, it can build well in first time, but change the project name, it will request install `android sdk`

**Comment by PureWeen** [comment]
@Coloryr can you try a couple things to gather a little bit more info?

1) https://github.com/xamarin/xamarin-macios/wiki/Diagnosis
2) 
![image](https://user-images.githubusercontent.com/5375137/218838536-704f011e-5122-450b-b0b3-2dc06691e4bb.png)

**Comment by Coloryr** [comment]
![Q_97292NA70K8FGSB} 8NLT](https://user-images.githubusercontent.com/26276037/218942240-8bcd1a23-086c-4bb3-8930-1444a467beca.png)
![{FJZ 4CS@S22WNS20AQ@F2](https://user-images.githubusercontent.com/26276037/218942331-334b0df6-cd79-4fa9-8dc5-d0ad297894f1.png)
now change name
![HUID{3MX4~9{@84AS}FR1A6](https://user-images.githubusercontent.com/26276037/218942371-e092ff99-dbb7-42e2-b438-94b51a19b430.png)

**Comment by Coloryr** [comment]
![LO)0%01`UWLX{Q@_`SVU813](https://user-images.githubusercontent.com/26276037/218942496-7762ee65-23c4-43da-9af6-530b76c527d3.png)

**Comment by Coloryr** [comment]
[log.zip](https://github.com/dotnet/maui/files/10739694/log.zip)

**Comment by Coloryr** [comment]
It look like work now.
