### ISSUE TITLE
[Bug] Blazor maccatalyst

### ISSUE THREAD

**Issue by dhindrik** [dotnet/maui#1299]
### Description
Build error when trying to start MAUI Blazor for Mac Catalyst. It works for iOS. Maui project without Blazor is also working.

### Steps to Reproduce

1.  dotnet new maui-blazor
2.  dotnet build -t:Run -f net6.0-maccatalyst

### Expected Behavior
App to build and start

### Actual Behavior
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/14.5.100-preview.4.635/tools/msbuild/iOS/Xamarin.iOS.Common.targets(878,3): error : /usr/bin/codesign exited with code 1 [/Users/danielhindrikes/Source/open-source/VisualServiceBus/VisualServiceBus/VisualServiceBus.csproj]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/14.5.100-preview.4.635/tools/msbuild/iOS/Xamarin.iOS.Common.targets(878,3): error :          [/Users/danielhindrikes/Source/open-source/VisualServiceBus/VisualServiceBus/VisualServiceBus.csproj]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/14.5.100-preview.4.635/tools/msbuild/iOS/Xamarin.iOS.Common.targets(878,3): error : Failed to codesign 'bin/Debug/net6.0-maccatalyst/maccatalyst-x64/VisualServiceBus.app': /Users/danielhindrikes/Source/open-source/VisualServiceBus/VisualServiceBus/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/VisualServiceBus.app: replacing existing signature [/Users/danielhindrikes/Source/open-source/VisualServiceBus/VisualServiceBus/VisualServiceBus.csproj]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/14.5.100-preview.4.635/tools/msbuild/iOS/Xamarin.iOS.Common.targets(878,3): error : /Users/danielhindrikes/Source/open-source/VisualServiceBus/VisualServiceBus/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/VisualServiceBus.app: unsealed contents present in the bundle root [/Users/danielhindrikes/Source/open-source/VisualServiceBus/VisualServiceBus/VisualServiceBus.csproj]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/14.5.100-preview.4.635/tools/msbuild/iOS/Xamarin.iOS.Common.targets(878,3): error :  [/Users/danielhindrikes/Source/open-source/VisualServiceBus/VisualServiceBus/VisualServiceBus.csproj]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/14.5.100-preview.4.635/tools/msbuild/iOS/Xamarin.iOS.Common.targets(878,3): error :          [/Users/danielhindrikes/Source/open-source/VisualServiceBus/VisualServiceBus/VisualServiceBus.csproj]

### Basic Information
- Version with issue:
.NET 4 preview 4 installed via maui-check tool

**Comment by dhindrik** [comment]
This also remains with Preview 5.

**Comment by dhindrik** [comment]
It seems to work now when I created a new project from the new templates.

**Comment by Eilon** [comment]
I guess it's working for you now, but when you were having this problem, did you have the same problem with a regular .NET MAUI app (no Blazor)? I think all the errors you have are not specific to Blazor.
