### ISSUE TITLE
No MAUI workload

### ISSUE THREAD

**Issue by jerelmcdonald** [dotnet/maui#13001]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jerelmcdonald** [comment]
Visual Studio Professional 2022 17.1.6 - install does not have the MAUI workload as an option

**Comment by jfversluis** [comment]
Hey @jerelmcdonald thanks for trying out .NET MAUI!

As already pointed out, .NET MAUI is available from Visual Studio 17.4 and up. Upgrade your Visual Studio or install one side-by-side and you should be able to see the option.

Good luck and have fun!
