### ISSUE TITLE
Maui App LifeCycle broken on Android

### ISSUE THREAD

**Issue by acaliaro** [dotnet/maui#13000]
### Description

Hello. By reading this documentation

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle?view=net-maui-7.0

and implementing the CreateWindow override

 ```
 protected override Window CreateWindow(IActivationState activationState)
     {
         System.Diagnostics.Debug.WriteLine("CreateWindow", "CreateWindow");

         Window window = base.CreateWindow(activationState);

         window.Created += (s, e) =>
         {
             System.Diagnostics.Debug.WriteLine("Created", "CreateWindow");
         };

         window.Activated += (s, e) =>
         {
             System.Diagnostics.Debug.WriteLine("Activated", "CreateWindow");
         };

         window.Deactivated += (s, e) =>
         {
             System.Diagnostics.Debug.WriteLine("Deactivated", "CreateWindow");
         };

         return window;
     }
```

this works fine if in android I press the key
![image](https://user-images.githubusercontent.com/5759350/215518490-720e8bbb-9283-4430-9dc0-85a22977f72f.png)

and then I select the app from the button
![image](https://user-images.githubusercontent.com/5759350/215518578-5810af79-6bc3-4a09-981f-e41ea4a37ca9.png)

But if I send the app to the background with the key
![image](https://user-images.githubusercontent.com/5759350/215518959-434155ef-d651-4249-8ec5-cd0607caa5f9.png)

and then I reselect the app with the button
![image](https://user-images.githubusercontent.com/5759350/215518578-5810af79-6bc3-4a09-981f-e41ea4a37ca9.png)

the Create Windows method is called every time the app appears, and the events are repeated

[0:] CreateWindow: CreateWindow
[0:] CreateWindow: Created
[0:] CreateWindow: Created
[0:] CreateWindow: Created
[0:] CreateWindow: Created
[0:] CreateWindow: Created
[0:] CreateWindow: Activated
[0:] CreateWindow: Activated
[0:] CreateWindow: Activated
[0:] CreateWindow: Activated
[0:] CreateWindow: Activated

### Steps to Reproduce

1. Create a Maui App.
2. in the app class, add this:

```
 protected override Window CreateWindow(IActivationState activationState)
    {
        System.Diagnostics.Debug.WriteLine("CreateWindow", "CreateWindow");

        Window window = base.CreateWindow(activationState);

        window.Created += (s, e) =>
        {
            System.Diagnostics.Debug.WriteLine("Created", "CreateWindow");
        };

        window.Activated += (s, e) =>
        {
            System.Diagnostics.Debug.WriteLine("Activated", "CreateWindow");
        };

        window.Deactivated += (s, e) =>
        {
            System.Diagnostics.Debug.WriteLine("Deactivated", "CreateWindow");
        };

        return window;
    }
```

### Link to public reproduction project repository

https://github.com/acaliaro/MauiAppActivatedProblem

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

no

### Relevant log output

```shell
[0:] CreateWindow: CreateWindow
[0:] CreateWindow: Created
[0:] CreateWindow: Created
[0:] CreateWindow: Created
[0:] CreateWindow: Created
[0:] CreateWindow: Activated
[0:] CreateWindow: Activated
[0:] CreateWindow: Activated
[0:] CreateWindow: Activated
[0:] CreateWindow: Deactivated
[0:] CreateWindow: Deactivated
[0:] CreateWindow: Deactivated
[0:] CreateWindow: Deactivated
```

**Comment by PureWeen** [comment]
@acaliaro This one is a bit tricky. 

The difference between the BackButton and the backgrounding button is that the back button destroys the `Activity` on android. 
So technically the window is being destroyed/created. 

I think if you return the same window instance for `CreateWindow` then your life cycle events should streamline.

**Comment by acaliaro** [comment]
> @acaliaro This one is a bit tricky.
> 
> The difference between the BackButton and the backgrounding button is that the back button destroys the `Activity` on android. So technically the window is being destroyed/created.
> 
> I think if you return the same window instance for `CreateWindow` then your life cycle events should streamline.

could you post a sample? Thanks!

**Comment by Redth** [comment]
Your code is always calling base.CreateWindow() which will get a new instance.  Instead you can store the reference as a property in your application class and only create it if it's null.
