### ISSUE TITLE
MAUI 7.0: ListView with Recycling strategy causes issues with images, on both iOS and Android

### ISSUE THREAD

**Issue by curia-damiano** [dotnet/maui#13008]
Using MAUI for .NET 6, the sample [ListViewDemos ](https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Views/ListViewDemos) works perfectly.

The same sample, compiled using MAUI for .NET 7, causes a bug:
- only on .NET 7 (no on .NET 6)
- only when using the Recycling strategy (without Recycling, it is ok)
- on both iOS and Android (tested on physical devices).

What happens is that labels seem to be ok, but images get scrambled all around.
[MonkeysViewModel.zip](https://github.com/dotnet/maui-samples/files/10509732/MonkeysViewModel.zip)

The issue is more evident using more rows in the view-model, and in particular not assigning an images to some cells.
Note: to have the bug is it not required to have cells without images - it just makes it more evident.
I attach to the issue a sample view-model.

[ListViewDemos.zip](https://github.com/dotnet/maui-samples/files/10539809/ListViewDemos.zip)

**Comment by PureWeen** [comment]
related https://github.com/dotnet/maui/issues/13076

**Comment by samhouts** [comment]
possibly a duplicate of #8787.

**Comment by curia-damiano** [comment]
Hi @samhouts , this issue is a duplicate of #8787 , that has been closed.
So we can close this as well (published with .NET 7.0.81)

**Comment by samhouts** [comment]
Duplicate of #8787
