### ISSUE TITLE
App does not register on default build

### ISSUE THREAD

**Issue by tryhardsnipehrd** [dotnet/maui#13007]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Trying to run the default code that is generated upon creating a project in Visual Studio 2022, latest build. OS version: Windows 10 - 21H2 - OS Build 19044.2486

I select `Windows Machine` in the editor, and have enabled debug mode on windows. The error I receive is `DEP0700: Registration of the app failed. [0x80073CFD] Windows cannot deploy to path AppX of file system type exFAT.`

I have tried running the compiler again, but nothing works.

Any and all help would be greatly appreciated!

**Comment by jfversluis** [comment]
Hey there, thank you for trying out .NET MAUI! Sorry you ran into a snag here.

I think this doesn't have much to do with .NET MAUI itself though, rather the underlaying layer. Based of what I see [here](https://learn.microsoft.com/en-us/answers/questions/642938/dep0700-registration-of-the-app-failed-(0x80073cfd), it seems that UWP (and now WinUI) apps can only be deployed to NTFS filesystems? 

Not sure what the reason behind that is, but it seems that you'll need to reformat the hard-drive of this machine to a different filesystem format for this to work 😅 If you'd still like to discuss possible options, I think this repository would be a better place for it: https://github.com/microsoft/microsoft-ui-xaml

Thanks!
