### ISSUE TITLE
[Mac]Fail to install 7.0 MAUI from main branch with error "Failed to install manifest microsoft.net.sdk.ios version 16.2.36... is not found in NuGet feeds"

### ISSUE THREAD

**Issue by v-Lily** [dotnet/maui#13012]
### Description

1. After installing the .NET 7.0 SDK, fails to install MAUI from main branch with the following error:
```
Workload installation failed. Rolling back installed packs...Workload installation failed: Failed to install manifest microsoft.net.sdk.ios version 16.2.36: microsoft.net.sdk.ios.manifest-7.0.100::16.2.36 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://api.nuget.org/v3/index.json"..
````
2. According to this [instruction](https://microsoft.sharepoint.com/:fl:/s/8203df86-d3c2-4c98-ad2e-c5112f35d0a6/EW58PqJer9NOlQUBjZb_YR8BBBsyU49ZuB-lE4Ej6Nq_2g?e=iXbvbl&nav=cz0lMkZzaXRlcyUyRjgyMDNkZjg2LWQzYzItNGM5OC1hZDJlLWM1MTEyZjM1ZDBhNiZkPWIhM2ZhcnJWVTN2RW1GR2xiQ1pMYTgtdWZVRFFZSWdiZEpyelQxQS1uZmFCRmtWT0taNVJBNVJKMW9zTDRpUmN1TiZmPTAxVlVOUzZTM09QUTdLRVhWUDJOSEpLQklCUldMUDZZSTcmYz0lMkYmZmx1aWQ9MSZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUV6Wm1GeWNsWlZNM1pGYlVaSGJHSkRXa3hoT0MxMVpsVkVVVmxKWjJKa1NuSjZWREZCTFc1bVlVSkdhMVpQUzFvMVVrRTFVa294YjNOTU5HbFNZM1ZPZkRBeFZsVk9VelpUTmtWYVZsTk9VMXBEVGs5YVFreE9TVmd6V1RReU0xRlNVMEUlM0QlMjIlMkMlMjJpJTIyJTNBJTIyZGZmMGZhNzktMDU1Zi00ZWVkLTgxZGItMDMwZGM2MzI4MmMxJTIyJTdE) install vs for mac 17.5 Preview 5 update the latest maui version met the same issue.

### Steps to Reproduce

1. Install the .NET 7.0 SDK.
1. Download the rollback.json file from [here](https://maui.blob.core.windows.net/dogfooding/7.0.1xx-sr3/rollback.json).
1. Download the NuGet.Config file from [here](https://maui.blob.core.windows.net/dogfooding/7.0.1xx-sr3/NuGet.Config).
1. Place the NuGet.Config and rollback.json files in the same directory (make sure there's no global.json file in the directory or directory tree above).
1. Open a terminal and cd into the directory with the NuGet.Config and rollback.json files.
1. Run the workload install command:
 `sudo dotnet workload install maui ios maccatalyst android macos tvos --from-rollback-file ./rollback.json`
1. The error is as shown below：   
    ![image](https://user-images.githubusercontent.com/83056958/215640550-0fde1caf-ac69-42b3-9d7d-1ebf7465e304.png)

### Link to public reproduction project repository

No

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS SDK 7.0.300-preview.23068.14

### Did you find any workaround?

No

### Relevant log output

```shell
Skipping NuGet package signature verification.Installing workload manifest microsoft.net.sdk.android version 33.0.26…Installing workload manifest microsoft.net.sdk.ios version 16.2.36…Workload installation failed. Rolling back installed packs...Workload installation failed: Failed to install manifest microsoft.net.sdk.ios version 16.2.36: microsoft.net.sdk.ios.manifest-7.0.100::16.2.36 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://api.nuget.org/v3/index.json"..
```
```

**Comment by v-Lily** [comment]
Add the following internal feed in the downloaded NuGet.Config file. This issue does not reproduce.
  https://pkgs.dev.azure.com/dnceng/internal/_packaging/6.0.406-servicing.23074.33-shipping/nuget/v3/index.json
  https://pkgs.dev.azure.com/dnceng/internal/_packaging/7.0.200-rtm.23080.6-shipping/nuget/v3/index.json

**Comment by mattleibow** [comment]
I think the rollback file was fixed so now uses a different version of the ios workload: `16.2.1007`

But also, since you managed to get this working, I will close. Feel free to reopen if the updated rollback file is not working.
