### ISSUE TITLE
Provide a cross platform API for customizing the TitleBar of desktop apps

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#13023]
### Description

Currently the `TitleBar` on WinUI isn't easily changeable from the xplat code.  Users can modify the WinUI `AppTitleBar` through resources https://github.com/dotnet/maui/pull/5811 but ideally you could configure it through xplat code. 

On Catalyst we currently have no way to do this other than users just adding the behavior themselves through the handler and hacking the layouts to work. 

### Related Issues

- [ ] https://github.com/dotnet/maui/issues/5710
- [ ] https://github.com/dotnet/maui/issues/9837
- [ ] https://github.com/dotnet/maui/issues/10297
- [ ] https://github.com/dotnet/maui/issues/7160
- [x] https://github.com/dotnet/maui/issues/7123
- [x] https://github.com/dotnet/maui/issues/7751

### (Public) API Changes

# TitleBar Control

This control is mostly based on the control in the WinAppSDK 1.6 Preview:
![image](https://github.com/dotnet/maui/assets/890772/adb64f45-a802-4d1f-8671-3353894a7f45)

## Properties

| API | Type | Description |
| --- | ----- | ------------- |
| Icon | ImageSource | The ImageSource for the TitleBar icon |
| LeadingContent | IView | Leading content, appears before the `Content`, allows full hit test |
| Content | IView | Centered content, allows full hit test |
| TrailingContent | IView | Trailing content, appears after the `Content`, allows full hit test |
| Title | string | The title text of the window |
| Subtitle | string | The subtitle text, follows the title text |
| BackgroundColor |  Color | The background color |
| ForegroundColor | Color | The foreground color of the `Title` and `Subtitle` text |
| InactiveBackgroundColor | Color | The background color of the TitleBar when the window is not in focus |
| InactiveForegroundColor | Color | The foreground color of the `Title` and `Subtitle` text when the window is not focused  |
| IsVisible | bool | Setting this to `False` will hide the TitleBar |

# Window

## Methods

| API | Description |
| --- | ----------- |
| SetTitleBar(TitleBar) | Sets the TitleBar |

#### XAML

```XAML
<ContentPage>
     <TitleBar
         x:Name="MyTitleBar"
         Title="{Binding Title}" />
         <TitleBar.Content>
             <Entry
                 Text="{Binding SearchInput}"/>
         </TitleBar.Content>
...
```

#### Backing .cs

```csharp
protected override void OnAppearing()
{
    base.OnAppearing();
    Window.SetTitleBar(MyTitleBar);
}
```

### Backward Compatibility

N/A

### Difficulty

High

> VS bug [#1864265](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1864265)

**Comment by lfmouradasilva** [comment]
Any updates on this issue?

**Comment by mhrastegari** [comment]
Any updates on this? :(
