### ISSUE TITLE
[Spec]  Implement ContentView inside Core

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#1302]
# [The feature] 

The `ContentView` class is a type of Layout that contains a single child element and is typically used to create custom, reusable controls. 

The ContentView class defines a single property, `Content` is a View object.

To allow porting libraries and apps to .NET MAUI it is important to have ContentView implementation in Core.

# Difficulty : [low]

**Comment by PaulAnderson02** [comment]
When will this support will be released?
