### ISSUE TITLE
A DllNotFoundException is thrown when calling into an iOS binding library when using MAUI on iOS

### ISSUE THREAD

**Issue by whodges** [dotnet/maui#13039]
### Description

I followed the instructions here (https://learn.microsoft.com/en-us/xamarin/cross-platform/cpp/) to access C++ native libraries from C# across multiple platforms.  While I was able to get this working in MAUI on Windows and Android, I can't get it to work on iOS.  Accessing the library throws a DllNotFoundException in MAUI under iOS (which is odd because DllImport is being passed "__Internal"; it's as if it's actually trying to load a library named as such).  For the C# iOS native lib wrapper, I've used the "iOS Binding Library" project template.  Note that this is not the Xamarin iOS binding library, it's the .NET one.

I created a full example of the problem I'm running into here:  https://github.com/whodges/bindingsample/tree/main.  This is the default template MAUI app, but it uses a native C++ counter from C# to keep track of how many times the button has been clicked, rather than just a '_count' member variable.   Windows and Android work fine; they're native libraries get used perfectly.  Using Visual Studio 17.5.0 Preview 5.0 on Windows, it fails on iOS as follows:

![screenshot](https://user-images.githubusercontent.com/5587254/215929166-cd985c15-f5a5-45f9-b9ad-c69e40bdc7f8.png)

### Steps to Reproduce

1. Clone the repo here:  https://github.com/whodges/bindingsample/tree/main
2. Build the solution and deploy to am ARM64 iOS device (I was using a physical iPhone 14 Pro).  Note building CounteriOS requires you be paired with a Mac running VCRemote (Tools->Options->Cross Platform->C++->iOS->Pairing).  If a Mac isn't available, you can actually just remote CounteriOS (NOT Counter.iOS) from the solution as Counter.iOS already has a pre-built copy of libCounteriOS.a to reference.
3. Debug the solution.  A DllNotFoundException will be thrown whenever a method in CounterWrapper gets called.

### Link to public reproduction project repository

https://github.com/whodges/bindingsample/tree/main

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

### Did you find any workaround?

Nope.

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-macios#17418
