### ISSUE TITLE
Newtonsoft.Json deserialization fails in Release build, works fine in Debug build

### ISSUE THREAD

**Issue by minglu** [dotnet/maui#13033]
### Description

Deserialization by using `Newtonsoft.json` fails in both Android and iOS builds, it works as expected in Debug builds. I am not sure if it's a trimming issue or AOT issue. I tried `<UseInterpreter>true</UseInterpreter>`, `<EnableAssemblyILStripping>false</EnableAssemblyILStripping>`, and also added XML to preserve all the types but doesn't work

@LeVladIonescu @rolfbjarne

### Steps to Reproduce

1. Checkout https://github.com/minglu/ReleaseTest
2. Debug Build, Run, and Click the [Click me] button, it will alert deserialized object Account.Name value without issue
3. Release Build, Run, and Click the [Click me] button, it will alert the error message

`Cannot create and populate list type System.Collections.Immutable.IImmutableList'caught

### Link to public reproduction project repository

https://github.com/minglu/ReleaseTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

Android 13, iOS 16.3

### Did you find any workaround?

For Android release:

```xml 
<RunAOTCompilation>False</RunAOTCompilation>
<PublishTrimmed>False</PublishTrimmed>
```
For iOS release, but we can't publish it to TestFlight with [Don't Link]:
```xml
<MtouchLink>None</MtouchLink>
```

### Relevant log output

```shell
Warning IL2104: Assembly 'Newtonsoft.Json' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries (IL2104)
```

**Comment by rolfbjarne** [comment]
This can be reproduced in both Debug and Release by doing this:

```xml
<MtouchLink>SdkOnly</MtouchLink>
```

The underlying reason is that Newtonsoft.Json.dll isn't trimmer-safe, and the trimmer ends up removing too much.

The required API is in System.Collections.Immutable.dll, as hinted to by the exception message:

And it's possible to tell the trimmer to not trim anything from that assembly by doing something like this in the csproj:

```xml
	<Target Name="DisableTrimmerForCertainAssemblies" BeforeTargets="PrepareForPublish">
		<ItemGroup>
			<ResolvedFileToPublish Update="@(ResolvedFileToPublish)" Condition="'%(Filename)%(Extension)' == 'System.Collections.Immutable.dll'">
				<IsTrimmable>false</IsTrimmable>
			</ResolvedFileToPublish>
		</ItemGroup>
	</Target>
```

can you try that and see if it works for you?

**Comment by minglu** [comment]
@rolfbjarne Thanks for the explanation, but somehow `ResolvedFileToPublish` (i also tried to use`ManagedAssemblyToLink`, or preserve all in `TrimmerRootDescriptor`) doesn't work for me. It does work with 

```xml
<ItemGroup>
    <TrimmerRootAssembly Include="System.Collections.Immutable" />
</ItemGroup>
```
