### ISSUE TITLE
Consider making IsPointerOver property public

### ISSUE THREAD

**Issue by polqnaP** [dotnet/maui#13046]
### Description

The PointerOver visual state is a useful visual state, however the default implementation does not allow for developers to know when an element is in PointerOver state. Like IsFocused and IsEnabled property the IsPointerOver property is essensial for customizing when a custom element should go to a specific state. 
For example, go to PointerOver state only if an entry is not focused. Currently this cannot be achieved due to IsPointerOver being internal.

### Public API Changes

```
public partial class VisualElement : NavigableElement, IAnimatable, IVisualElementController, IResourcesProvider, IStyleElement, IFlowDirectionController, IPropertyPropagationController, IVisualController, IWindowController
{
	// ...
	public bool IsPointerOver
	{
		get { return _isPointerOver; }
	}
	// ...
}

public class MyEntry : Entry
{
    protected override void ChangeVisualState()
    {
		if (!this.IsEnabled)
		{
			VisualStateManager.GoToState(this, VisualStateManager.CommonStates.Disabled);
		}
		else if(this.IsPointerOver && !this.IsFocused )
		{
			VisualStateManager.GoToState(this, VisualStateManager.CommonStates.PointerOver);
		}
		else if(this.IsFocused)
		{
			VisualStateManager.GoToState(this, VisualStateManager.CommonStates.Focused);
		}
		else
		{
			VisualStateManager.GoToState(this, VisualStateManager.CommonStates.Normal);
		}
	}
}
```

### Intended Use-Case

I would like to know when an element is hovered, so that I can choose which VisaulState to choose, for example I would like to go to PointerOver state when my control hovered, but is not Focused and not IsReadonly (custom property for custom element)).

**Comment by jfversluis** [comment]
I think this should now be possible with the [PointerGestures](https://learn.microsoft.com/dotnet/maui/fundamentals/gestures/pointer). If that is not enough, please feel free to open something new detailing what you'd like to see more.
