### ISSUE TITLE
BindableProperty OneWay Event not working.

### ISSUE THREAD

**Issue by BoungSeokKim** [dotnet/maui#13042]
### Description

```propertyChanged``` Value is propertyChanged not call. demo progject attach.

```C#
public class CircleProgress : SKCanvasView
{
///
	public float Value
	{
		get => (float)GetValue(ValueProperty);
		set => SetValue(ValueProperty, value);
	}

	public static readonly BindableProperty ValueProperty = BindableProperty.Create(nameof(Value), typeof(float), typeof(CircleProgress), 0.0f, propertyChanged: (BindableObject bindable, object oldValue, object newValue) =>
	{
		var progress = (CircleProgress)bindable;
		if(oldValue != newValue)
		{
			progress.ValueChanged?.Invoke(progress, new ValueChangedEventArgs((float)oldValue, (float)newValue));
			progress.InvalidateSurface();
		}
	}, coerceValue: (bindable, value) =>
	{
		var progress = (CircleProgress)bindable;
		return Math.Clamp((float)value, progress.Minimum, progress.Maximum);
	});
}
```

[ProgressDemo.zip](https://github.com/dotnet/maui/files/10554349/ProgressDemo.zip)

### Steps to Reproduce

1. project open 
2. run
3. "Clicked me" button clicked
4. CircleProgress only not updated.
5.

### Link to public reproduction project repository

https://github.com/BoungSeokKim/ProgressDemo

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

windwos 10 21H2, macOS Monterey 12.6.3, 

### Did you find any workaround?

```
maui                  7.0.58/7.0.100         SDK 7.0.100
maui-windows          7.0.58/7.0.100         VS 17.4.33213.308
maui-maccatalyst      7.0.58/7.0.100         VS 17.4.33213.308
maccatalyst           16.2.1007/7.0.100      VS 17.4.33213.308
maui-ios              7.0.58/7.0.100         VS 17.4.33213.308
ios                   16.2.1007/7.0.100      VS 17.4.33213.308
android               33.0.26/7.0.100        VS 17.4.33213.308
maui-android          7.0.58/7.0.100         VS 17.4.33213.308
```

**Comment by jfversluis** [comment]
Maybe related: #12285

Changing [this code](https://github.com/BoungSeokKim/ProgressDemo/blob/main/MainPage.xaml#L13-L18):

```xml
<local:CircleProgress 
    Value="{Binding Count}" 
    Maximum="100"
    Thickness="20"
    HeightRequest="200"
/>
```

to 

```xml
<local:CircleProgress 
    Maximum="100"
    Value="{Binding Count}" 
    Thickness="20"
    HeightRequest="200"
/>
```

Makes it work. Somewhere in your code you seem to reset the binding of `Value` when you set `Maximum`. Since this is not really an issue with us, closing this for now.
