### ISSUE TITLE
Hot Reload does not work or stops working in some specific cases

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#13052]
### Description

I have noticed that updating VisualStates from a style https://github.com/jsuarezruiz/netmaui-movies-app-challenge/blob/main/src/MoviesApp/Views/MoviesView.xaml#L19, especially complex elements such as CarouselView or Border, stops XAML Hot Reload from working.

![issue-hr](https://user-images.githubusercontent.com/6755973/216081204-d6f52734-1706-4830-813f-b1fb9bc8f7a3.gif)

Updating VisualStates (without styles) does not update the changes. https://github.com/jsuarezruiz/netmaui-movies-app-challenge/blob/main/src/MoviesApp/Views/MoviesView.xaml#L146

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/netmaui-movies-app-challenge
2. Launch the App on an Android emulator.
3. Try to update the shared lines from VisualStates.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-movies-app-challenge

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 13

> VS bug [#1748371](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1748371)

**Comment by chabiss** [comment]
This is probably related to the huge overhaul of the property setter specificity work as part of https://github.com/dotnet/maui/issues/11082

**Comment by chabiss** [comment]
This issue should not be closed. tag [partner/hot-reload-xaml](https://github.com/dotnet/maui/labels/partner%2Fhot-reload-xaml) is accurate as an item to be track in the MAUI debot

**Comment by drasticactions** [comment]
https://user-images.githubusercontent.com/898335/219333152-d4598005-af31-46a3-881c-0eda7d2f84e9.mp4

I am testing on the current net7.0 maui with the current VSMac.

**Comment by drasticactions** [comment]
Changes within the VisualStateGroup itself are not reflected, nor are they updated by XAML Actions from code behind. Nothing is sent from what I can see.

<img width="875" alt="スクリーンショット 2023-02-16 19 19 19" src="https://user-images.githubusercontent.com/898335/219337777-592567be-664f-45a2-93bc-0ac413411bce.png">

If you change the individual value of the setter (Like the text color) nothing is sent to the application. If you change the entire list (As in, replace the entire VisualState or the VisualStateGroup) then it sends actions to replace the whole thing and _then_ it reloads.

Having the style attached at all to a control shouldn't matter.

**Comment by drasticactions** [comment]
Assigning myself to this for the moment so it's tracked, most likely this will be a XET issue but having this around is fine for visibility.

**Comment by jsuarezruiz** [comment]
Not sure how to reproduce exactly, but modifying content from a ContentView used as CollectionView ItemTemplate
![xaml-hot-relaod-issue](https://user-images.githubusercontent.com/6755973/223440321-75b22efb-210f-45f5-92e3-021113b5e9d9.PNG)

https://github.com/jsuarezruiz/netmaui-skateboard-ecommerce-app-challenge

**Comment by drasticactions** [comment]
@jsuarezruiz I can't reproduce that on Android nor WinUI. I was able to make changes on the underlying ContentView and it showed fine. Was that on iOS? Do you have Logs?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on windows and android platform with sample project.
[netmaui-movies.zip](https://github.com/dotnet/maui/files/11880330/netmaui-movies.zip)
![13052](https://github.com/dotnet/maui/assets/77434865/c6e7e868-d08e-45d0-a037-f7810c387af3)
