### ISSUE TITLE
[Windows] CarouselView Layout is broken

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#13057]
### Description

CarouselView Layout is broken. The item size is wrong.

Windows
![image](https://user-images.githubusercontent.com/6755973/216082466-a7dd7bab-e35b-433c-a050-2c41415cfea9.png)

Android
![fhl-result](https://user-images.githubusercontent.com/6755973/216082845-82a225f5-f2d2-4679-846e-1fb2e876978f.gif)

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/netmaui-movies-app-challenge
2. Launch the App on Windows

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-movies-app-challenge

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 22H2

**Comment by jbfranklin** [comment]
The CarouselView is KEY functionality for MAUI to even be a viable product at least MVP. Please fix ASAP.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on windows platform with above project.
[netmaui-movies.zip](https://github.com/dotnet/maui/files/11685342/netmaui-movies.zip)
![Screenshot 2023-06-08 153907](https://github.com/dotnet/maui/assets/77434865/6961ee42-f2ef-4a31-9c61-333cab57a35d)

**Comment by dotMorten** [comment]
I'm hitting this too and can't get it to size right on Windows - its children are generally zero-height during arrange, yet it renders it contents under the next element (I have it in a vertical stacklayout, and I see the Carousel's contents render under the next element in the stack)
