### ISSUE TITLE
创建新项目时，找不到“MAUI”选项

### ISSUE THREAD

**Issue by qsl888** [dotnet/maui#13075]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/maui/first-app-tutorial/install
Operating System: windows
安装好VS2022和.NET MAUI后，创建新项目时，找不到“MAUI”选项。
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Hey there, sorry for responding in English, but I can't speak or write Chinese 😄  Happy to see your interest in .NET MAUI!

You mention that you did install Visual Studio and .NET MAUI? I assume that means during the install you have clicked the .NET MAUI option? 

![image](https://user-images.githubusercontent.com/939291/216288559-dca6f689-0fef-4759-a77b-efaf39ba2acb.png)

If you go back to the Visual Studio Installer and click Modify, does the .NET MAUI option show as checked? If you go to a command-line window and type `dotnet new list`, does is show .NET MAUI in there?
