### ISSUE TITLE
Implementation error in settings manager with .NET MAUI

### ISSUE THREAD

**Issue by Larii04** [dotnet/maui#13085]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/maui/first-app-tutorial/run
Operating System: windows

I following microsoft's tutorial and when I run the program for the first time to configure with "Windows Machine" an error appears. Bellow is the error:
"Erro	DEP0700: Falha no registro do aplicativo. [0x80073D1F] Erro não especificado."
----------------------------------------------------------------------------------------------------
"The project needs to be deployed so we can debug. Enable deploy in Configuration Manager."

**Comment by Larii04** [comment]
Thank you. I'll do that tomorrow!

**Comment by jfversluis** [comment]
The author has acknowledged and not sure if the issue will now close automatically, so I will do it for this instance. Thanks @Larii04!
