### ISSUE TITLE
[Android] Crash binding the CarouselView CurrentItem

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#13084]
### Description

Crash binding the CarouselView CurrentItem using also Loop property:

![image](https://user-images.githubusercontent.com/6755973/216337867-94ae2b28-f2af-4035-a6df-88e062e3db8a.png)

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/netmaui-movies-app-challenge
2. Set the Movies CarouselView CurrentItem  property.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-movies-app-challenge

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. This issue does not repro on Android 13.0-API33 with below Project:
[MoviesApp.zip](https://github.com/dotnet/maui/files/11785717/MoviesApp.zip)

Run successfully on Android without exception.
![image](https://github.com/dotnet/maui/assets/97647558/67de5b67-9ddb-4b9c-9690-9ea234b995b1)
