### ISSUE TITLE
I can not see MAUI project type in VS 2022

### ISSUE THREAD

**Issue by tkachuk2222** [dotnet/maui#13099]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

I've installed MAUI component from VS Installer but can't see it after clicking "Create project"
![image](https://user-images.githubusercontent.com/20381930/216476918-90933905-ea04-4896-b43a-83fd98e3c48c.png)

> VS bug [#1745722](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1745722)

**Comment by LennoxP90** [comment]
I had a similar issue with my existing app after the 7.0.59 release of maui VS 2022 17.4 no longer works, I was forced to update to the preview branch 17.5

**Comment by AswinPG** [comment]
try running `dotnet workload install maui` on a terminal. I had the same issue after i updated the workloads from the command line and running this command solved it for me

**Comment by lepete11** [comment]
running `dotnet workload install maui` worked for me, even though I had the MAUI Workload installed in 17.4.4.   MS needs to fix this issue for which a workload is already installed, but the project type does not appear when creating new projects.
