### ISSUE TITLE
HttpClientHandler.ClientCertificates.Add() do nothing on macOS

### ISSUE THREAD

**Issue by nomadedge** [dotnet/maui#13102]
### Description

If you create HttpClientHandler and add client certificate the collection remains empty, no certificate added.

`var handler = new HttpClientHandler();`
`handler.ClientCertificateOptions = ClientCertificateOption.Manual;`
`handler.SslProtocols = SslProtocols.Tls12;`
`var index = handler.ClientCertificates.Add(new X509Certificate2());`

Same code on Windows works as expected, same code in macOS Console app works as expected.
Manually creating X509CertificateCollectoin and adding certificate in it works fine as well.
AddRange method has the same issue.

### Steps to Reproduce

1. Create HttpClientHandler
2. Call Add method on ClientCertificates property
3. See that collection is still empty, no exception thrown, 0 index is returned

### Link to public reproduction project repository

https://github.com/nomadedge/NetMaui.BugReport.ClientCertIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Ventura 13.1

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-macios#17443
