### ISSUE TITLE
C # long/Int64 type conversion error！

### ISSUE THREAD

**Issue by XiangShuUncle** [dotnet/maui#13116]
### Description

![image](https://user-images.githubusercontent.com/37469567/216742138-5732db86-7c43-464e-9d5a-8ef471d52b52.png)

As shown in the figure, I use the default MAUI Blazor template to output c # long/Int64 type to JavaScript. By default, JavaScript Number is not compatible, so is there any way to convert it to string type?

### Steps to Reproduce

1. Use the default template.
2. Change the MauiProgram.cs file 
```cs
          public static class MauiProgram
          {
	          public static MauiApp CreateMauiApp()
	          {
		          var builder = MauiApp.CreateBuilder();
		          builder
			          .UseMauiApp<App>()
			          .ConfigureFonts(fonts =>
			          {
				          fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
			          });
          
		          builder.Services.AddMauiBlazorWebView();
		          #if DEBUG
		          builder.Services.AddBlazorWebViewDeveloperTools();
          #endif
		          
		          builder.Services.AddSingleton<WeatherForecastService>();
          
		          return builder.Build();
	          }
          
	          [JSInvokable]
	          public static Task<long> GetLongType()
	          {
		          return Task.FromResult(long.MaxValue);
	          }
	          [JSInvokable]
	          public static Task<LongObj> GetLongObject()
	          {
		          return Task.FromResult(new LongObj(){Id = long.MaxValue } );
	          }
          }
          
          public class LongObj
          {
	          public long Id { get; set; }
          }
```
3.  Change the  wwwroot\index.html.cs file 
```html
    <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
	        <title>MauiApp1</title>
	        <base href="/" />
	        <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
	        <link href="css/app.css" rel="stylesheet" />
	        <link href="MauiApp1.styles.css" rel="stylesheet" />
        </head>
        
        <body>
        
	        <div class="status-bar-safe-area"></div>
        
	        <div id="app">Loading...</div>
        
	        <div id="blazor-error-ui">
		        An unhandled error has occurred.
		        <a href="" class="reload">Reload</a>
		        <a class="dismiss">🗙</a>
	        </div>
        
	        <script src="_framework/blazor.webview.js" autostart="false"></script>
            <script>
                window.GetLongType = function () {
                    DotNet.invokeMethodAsync('MauiApp1', 'GetLongType')
                        .then(data => {
                            console.log("InData",data);
                            console.log("long.MaxValue( 9223372036854775807 ) IsEquals InData:", data.toString() =="9223372036854775807");
                        });
                }
                window.GetLongObject = function () {
                    DotNet.invokeMethodAsync('MauiApp1', 'GetLongObject')
                        .then(data => {
                            console.log("InData", data);
                            console.log("long.MaxValue( 9223372036854775807 ) IsEquals InData.id:", data.id.toString() == "9223372036854775807");
                        });
                }
            </script>
        </body>
        
        </html>
```
5. Change the  Pages\Index.razor file 

```razor
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />
<button onclick="GetLongType()">GetLongType</button>
<button onclick="GetLongObject()">GetLongObject</button>
```

6.Run App, observation console.

### Link to public reproduction project repository

https://github.com/XiangShuUncle/MauiTemp

### Version with bug

7.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

或许可以使用 System.Text.Json.Serialization.JsonConverter 自定义输出格式，But that doesn't work.
![image](https://user-images.githubusercontent.com/37469567/216743407-02e1e92d-a71c-4397-9f32-d4a49b02696b.png)

**Comment by ramonB1996** [comment]
@XiangShuUncle Could you tell us what your exact goal is to achieve?

**Comment by XiangShuUncle** [comment]
> @XiangShuUncle你能告诉我们你的确切目标是什么吗？我知道Javascript现在有一个，这会解决你的问题吗？`bigint`
I need javascript to directly call the backend. net [JSInvokable] method to return long type data without losing precision, regardless of whether the result is string or bigint. The current situation is that calling the [JSInvoke] method directly will convert C # long to JS Number type and lose precision.

**Comment by XiangShuUncle** [comment]
@ramonB1996 I need javascript to directly call the backend. net [JSInvokable] method to return long type data without losing precision, regardless of whether the result is string or bigint. The current situation is that calling the [JSInvoke] method directly will convert C # long to JS Number type and lose precision.

**Comment by ramonB1996** [comment]
@XiangShuUncle I think I found the issue here. In your Javascript code, `typeof data` is a `number` by default. You can cast it to a `bigint` this way: 

`const preciseData = BigInt(data)` on line 30 of `wwwroot/index.html`

Hopefully this would be good enough for your use-case. I am not sure how to make it use `bigint` as the default, but that might be a setting somewhere.

If you can not find a way to get it more accurate (and you really need to), then you could pass an argument to the JSInterop call. For example pass the number `1000` to the function and use that to divide by 1000 in your `GetLongType()` method. Then multiply the number by `1000` again when converting the results in `Javascript`. You just have to be careful with the rounding, but I am sure you can figure that out :)

Good luck! Please let me know if this issue can be closed after ;)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. As @ramonB1996 did mention, this is due to using incompatible type for your data storage. Closing, as there is no further action pending here from the team.
