### ISSUE TITLE
Published Android App crashes due to XAML incompatibility 

### ISSUE THREAD

**Issue by JeroenMBooij** [dotnet/maui#13124]
### Description

Running the `dotnet build app.csproj -c Release -f net6.0-android` command and installing the resulting apk on a mobile device causes the app to crash when it opens the app and it gave me the following errors in the device log even though the app works in an emulator.

```
Time	Device Name	Type	PID	Tag	Message
02-05 23:32:16.304	Samsung SM-G715FN	Info	1351	MonoDroid	android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `App.MainPage:InitializeComponent ()'
```

### Steps to Reproduce

1. Create a new .NET Maui App

2. add the following XAML to MainPage.xaml

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:App"
             x:Class="App.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height = "*" />
        </Grid.RowDefinitions>

        <StackLayout x:Name="AdPlaceholder" ZIndex="10">
        </StackLayout>

        <BlazorWebView HostPage="wwwroot/index.html" Grid.Row = "1">
            <BlazorWebView.RootComponents>
                <RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
            </BlazorWebView.RootComponents>
        </BlazorWebView>
        
    </Grid>

</ContentPage>`

3. run `dotnet build app.csproj -c Release -f net6.0-android` in the project root

4. Use the APK file to install the app on your android device

5. App will crash

### Link to public reproduction project repository

see steps to reproduce

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10 and up

### Did you find any workaround?

Remove ZIndex from XAML and add it using c# codebehind file

**Comment by jsuarezruiz** [comment]
This have been already fixed in .NET 7 https://github.com/dotnet/maui/pull/8184
Could you upgrade your app?
