### ISSUE TITLE
DisplayPromptAsync auto-capitalizes some letters

### ISSUE THREAD

**Issue by heron1** [dotnet/maui#13129]
### Description

I'm using Application.Current?.MainPage?.DisplayPromptAsync to display a box to the end user which they must fill out. As they're typing, some words are autocapitalized which they shouldn't be. I want to capture the user input exactly.

Using .ToLowerCase or .ToCupperCase won't work since I want to retain the capitalization in the input. I simply want to capture the user input exactly without this popup box autocapitalizing anything.

### Steps to Reproduce

For an example, type in "microsoft" into the box and it will automatically become "Microsoft". or ".net" and it will automatically become ".NET", etc.

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by drasticactions** [comment]
I believe that's the default when using that method. It enables spellcheck for the keyboard, so it autocorrects what you're typing.

If you read the documentation for that method (https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pop-ups?view=net-maui-7.0), there is a parameter to set the keyboard (https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.keyboard?view=net-maui-7.0). I believe changing it to `Text` will fully disable spellcheck.

**Comment by heron1** [comment]
Thanks, unfortunately the issue still seems to be persisting regardless of what I input for the Keyboard parameter.
