### ISSUE TITLE
BoolToObjectConverter doesn't work with IconTintColorBehavior In Android

### ISSUE THREAD

**Issue by KDewangan** [dotnet/maui#13122]
### Description

When we use BoolToObjectConverter with IconTintColorBehavior in the Image it doesn't show the Image, Just shows blank for Android. 
<img width="1067" alt="Screenshot 2023-02-05 at 8 47 06 PM" src="https://user-images.githubusercontent.com/20160755/216828175-3da72aee-ce96-46e4-9606-082ec01095e8.png">

### Steps to Reproduce

1. Create New MAUI App.
2. On MainPage.xaml add static resource 
**<ResourceDictionary>
              <xct:BoolToObjectConverter x:Key="TintedImageColorConverter" TrueObject="#B9D9EB" FalseObject="#e7e7e7" />
   </ResourceDictionary>**

3. Add an Image with 
 **<Image.Behaviors>
                    <xct:IconTintColorBehavior TintColor="{Binding IsEnabled, Converter={StaticResource TintedImageColorConverter}}"/>
 </Image.Behaviors>**

4. Add a class for MainPage BindingContext : 
**public class MainPageContext
{
    public string imgSource { get; set; } = "dotnet_bot.svg";
    public bool IsEnabledProp { get; set; } = true;
}**
5. Run the App on Android 

Expected outcome: The image should show with provided tint color 
Actual outcome: shows blank, doesn't show any Image. 

### Link to public reproduction project repository

https://github.com/KDewangan/MAUIPractice

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No

**Comment by KDewangan** [comment]
It's reproducible with .net 7

**Comment by ramonB1996** [comment]
This issue should be in the MAUI Community Toolkit repository I think

**Comment by jfversluis** [comment]
This issue was moved to CommunityToolkit/Maui#965
