### ISSUE TITLE
Navigating using flyout menu causes all items after first item in TabBar to dissapear.

### ISSUE THREAD

**Issue by ne0rrmatrix** [dotnet/maui#13134]
### Description

Upon using flyout menu navigation to navigate to a page the second and following items in TabBar are no longer visible.

### Steps to Reproduce

1. Create New Maui solution.
2. Add flyout navigation menu.
3. Add TabBar menu.
4. Navigate using flyout menu.

### Link to public reproduction project repository

https://github.com/ne0rrmatrix/ShellMenu

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13, Windows10.0.17763.0 and up

### Did you find any workaround?

In AppShell.xaml set FlyoutBehavior="Disabled" will mitigate the navigation issue by removing the navigation.

**Comment by XamlTest** [comment]
@ne0rrmatrix The provided project is not found. Could you check that and upload again?
