### ISSUE TITLE
.NET MAUI Blazor App - UI Freeze when overwhelmed with key and mouse input messages

### ISSUE THREAD

**Issue by Kanawanagasaki** [dotnet/maui#13145]
### Description

In .NET MAUI with Blazor Hybrid model if you press and hold any key on keyboard and if you start moving your mouse at the same time after some time UI will freeze.
![bug](https://user-images.githubusercontent.com/62866497/217078716-36ea3eac-0acc-4b8a-b99a-6632ab854ee5.gif)

### Steps to Reproduce

1. Create a .NET MAUI Blazor App Project
2. Run the application using "Windows Machine"
3. Make sure the app is focused
4. Press and hold the Ctrl key
5. Continuously move your mouse over the window

After a while, the interface will freeze

### Link to public reproduction project repository

https://github.com/Kanawanagasaki/Maui.UIFreezeBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

windows10.0.19041.0

**Comment by Eilon** [comment]
Hi, this is tracked as a WebView2 issue here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003.
