### ISSUE TITLE
On Windows, ImageButton is set to isEnable=false. When isEnable=true is set, the button status is gray

### ISSUE THREAD

**Issue by gudder** [dotnet/maui#13157]
### Description

On Windows, ImageButton is set to IsEnable=false. When IsEnable=true is set, the button status is gray

![20230207142201](https://user-images.githubusercontent.com/3445189/217165293-e2274137-064a-43ef-a39b-e7a0ed750b6f.gif)

### Steps to Reproduce

[App1.zip](https://github.com/dotnet/maui/files/10672146/App1.zip)

### Link to public reproduction project repository

Attached zip files 

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

**Comment by mattleibow** [comment]
Does this also happen with .NET 7?

Is it possible to upload the sample as a GitHub repository so that it makes things easier for the team to check?

**Comment by gudder** [comment]
> Does this also happen with .NET 7?
> 
> Is it possible to upload the sample as a GitHub repository so that it makes things easier for the team to check?

GitHub repository ： https://github.com/gudder/MauiApp1.git

**Comment by gudder** [comment]
> Does this also happen with .NET 7?
> 
> Is it possible to upload the sample as a GitHub repository so that it makes things easier for the team to check?

My environment has some problems in dotnet7, only tested dotnet6
GitHub repository ： https://github.com/gudder/MauiApp1.git， When scale_slider's value between max and min，button will be set IsEnable = true.

`        if (scale_slider.Value >= scale_slider.Maximum)
        {
            btn_zoom_in.IsEnabled = false;
        }
        else if (scale_slider.Value <= scale_slider.Minimum)
        {
            btn_zoom_out.IsEnabled = false;
        }
        else
        {
            btn_zoom_in.IsEnabled = true;
            btn_zoom_out.IsEnabled = true;
        }
`

**Comment by gudder** [comment]
> Does this also happen with .NET 7?
> 
> Is it possible to upload the sample as a GitHub repository so that it makes things easier for the team to check?

I get the latest version but the problem persists

1. It is to set the qslider value by clicking the button, gray the button in the qslider value change event.
2. Change the value of the slider value through another button, and set IsEnable for the gray button in the slider vavlue change event.
3. The button is still in the gray state, but it can be clicked.

I change the setting button IsEnable=false and IsEnable=true by sliding the slider , and the refresh of the button is work.

![4](https://user-images.githubusercontent.com/3445189/217487694-c5d8b09d-01f2-45c9-bf34-f06f22b6cb9a.gif)
