### ISSUE TITLE
IllegalStateException: ShellPageContainer#onMeasure() did not set the measured dimension by calling setMeasuredDimenstion()

### ISSUE THREAD

**Issue by BioTurboNick** [dotnet/maui#13152]
### Description

I've seen this report sporadically in the wild (via AppCenter) but I haven't yet been able to reproduce.

May be related to #10776 ?

Is it possible for there to be a case where `Child.NativeView` is not an `Android.Views.View` (or becomes null?) during a layout cycle? Perhaps `SetMeasuredDimension` should always be called regardless of `Child.PlatformView`?

https://github.com/dotnet/maui/blob/50e28913c29c780fb1d012e1d23bc9a9ece2ec64/src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellPageContainer.cs#L50-L58

### Steps to Reproduce

pending

### Link to public reproduction project repository

pending

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8.1, 9, 10

### Relevant log output

```shell
android.view.View.measure View.java:22298
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild CoordinatorLayout.java:795
com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild HeaderScrollingViewBehavior.java:100
com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild AppBarLayout.java:2253
androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure CoordinatorLayout.java:866
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
android.view.View.measure View.java:22286
android.widget.LinearLayout.measureVertical LinearLayout.java:975
android.widget.LinearLayout.onMeasure LinearLayout.java:702
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
android.view.View.measure View.java:22286
androidx.drawerlayout.widget.DrawerLayout.onMeasure DrawerLayout.java:1156
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.LinearLayout.measureChildBeforeLayout LinearLayout.java:1539
android.widget.LinearLayout.measureHorizontal LinearLayout.java:1184
android.widget.LinearLayout.onMeasure LinearLayout.java:704
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
androidx.appcompat.widget.ContentFrameLayout.onMeasure ContentFrameLayout.java:145
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.LinearLayout.measureChildBeforeLayout LinearLayout.java:1539
android.widget.LinearLayout.measureVertical LinearLayout.java:823
android.widget.LinearLayout.onMeasure LinearLayout.java:702
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
com.android.internal.policy.DecorView.onMeasure DecorView.java:837
android.view.View.measure View.java:22286
android.view.ViewRootImpl.performMeasure ViewRootImpl.java:2646
android.view.ViewRootImpl.measureHierarchy ViewRootImpl.java:1674
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:1933
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1558
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:7463
android.view.Choreographer$CallbackRecord.run Choreographer.java:1041
android.view.Choreographer.doCallbacks Choreographer.java:847
android.view.Choreographer.doFrame Choreographer.java:774
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:1027
android.os.Handler.handleCallback Handler.java:809
android.os.Handler.dispatchMessage Handler.java:102
android.os.Looper.loop Looper.java:166
android.app.ActivityThread.main ActivityThread.java:7555
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:469
com.android.internal.os.ZygoteInit.main ZygoteInit.java:963
```
```

**Comment by BioTurboNick** [comment]
Android documentation says:

```
CONTRACT: When overriding this method, you must call [setMeasuredDimension(int, int)](https://developer.android.com/reference/android/view/View#setMeasuredDimension(int,%20int)) to store the measured width and height of this view. Failure to do so will trigger an IllegalStateException, thrown by [measure(int, int)](https://developer.android.com/reference/android/view/View#measure(int,%20int)). Calling the superclass' [onMeasure(int, int)](https://developer.android.com/reference/android/view/View#onMeasure(int,%20int)) is a valid use.
```
https://developer.android.com/reference/android/view/View#setMeasuredDimension(int,%20int)

So either this method needs to call `SetMeasuredDimension` no matter what, or it can call the base `OnMeasure()`.

I'll just do a PR quick.

**Comment by BioTurboNick** [comment]
Wait... crap. I hate GitHub search. Apparently what I found isn't in the main branch?

**Comment by BioTurboNick** [comment]
The hidden comment is still applicable (and reproduced below). I found the real ShellPageContainer (thanks to cloning it and using Windows and VS Code). It looks like it uses a pattern that was dropped in the current `PageContainer`.

Android documentation says:

```
CONTRACT: When overriding this method, you must call [setMeasuredDimension(int, int)](https://developer.android.com/reference/android/view/View#setMeasuredDimension(int,%20int)) to store the measured width and height of this view. Failure to do so will trigger an IllegalStateException, thrown by [measure(int, int)](https://developer.android.com/reference/android/view/View#measure(int,%20int)). Calling the superclass' [onMeasure(int, int)](https://developer.android.com/reference/android/view/View#onMeasure(int,%20int)) is a valid use.
```
https://developer.android.com/reference/android/view/View#setMeasuredDimension(int,%20int)

So either this method needs to call `SetMeasuredDimension` no matter what, or it can call the base `OnMeasure()`.

I'll just do a PR quick.

**Comment by EdwardMcFlurry** [comment]
Well for this is strange as the user launched the App and the the App crashed…

![500FBA54-A5B8-4FD2-AA64-94EFC3691CCD](https://user-images.githubusercontent.com/46613832/219323564-eb94d672-4653-4092-8687-aa073f3eb4ab.jpeg)

and this where I don’t understand what went wrong…

android.view.View.measure View.java:25483
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6957
android.widget.FrameLayout.onMeasure FrameLayout.java:194
android.view.View.measure View.java:25470
androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins RecyclerView.java:9681
androidx.recyclerview.widget.LinearLayoutManager.layoutChunk LinearLayoutManager.java:1657
androidx.recyclerview.widget.LinearLayoutManager.fill LinearLayoutManager.java:1591
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren LinearLayoutManager.java:668
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 RecyclerView.java:4309
androidx.recyclerview.widget.RecyclerView.dispatchLayout RecyclerView.java:4012
androidx.recyclerview.widget.RecyclerView.onLayout RecyclerView.java:4578
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
androidx.viewpager2.widget.ViewPager2.onLayout ViewPager2.java:527
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild HeaderScrollingViewBehavior.java:149
com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild ViewOffsetBehavior.java:43
com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild AppBarLayout.java:2253
androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout CoordinatorLayout.java:953
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
android.widget.FrameLayout.layoutChildren FrameLayout.java:332
android.widget.FrameLayout.onLayout FrameLayout.java:270
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
android.widget.LinearLayout.setChildFrame LinearLayout.java:1829
android.widget.LinearLayout.layoutVertical LinearLayout.java:1673
android.widget.LinearLayout.onLayout LinearLayout.java:1582
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
android.widget.FrameLayout.layoutChildren FrameLayout.java:332
android.widget.FrameLayout.onLayout FrameLayout.java:270
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
androidx.drawerlayout.widget.DrawerLayout.onLayout DrawerLayout.java:1263
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
android.widget.LinearLayout.setChildFrame LinearLayout.java:1829
android.widget.LinearLayout.layoutHorizontal LinearLayout.java:1818
android.widget.LinearLayout.onLayout LinearLayout.java:1584
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
android.widget.FrameLayout.layoutChildren FrameLayout.java:332
android.widget.FrameLayout.onLayout FrameLayout.java:270
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
android.widget.FrameLayout.layoutChildren FrameLayout.java:332
android.widget.FrameLayout.onLayout FrameLayout.java:270
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
android.widget.FrameLayout.layoutChildren FrameLayout.java:332
android.widget.FrameLayout.onLayout FrameLayout.java:270
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
android.widget.LinearLayout.setChildFrame LinearLayout.java:1829
android.widget.LinearLayout.layoutVertical LinearLayout.java:1673
android.widget.LinearLayout.onLayout LinearLayout.java:1582
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
android.widget.FrameLayout.layoutChildren FrameLayout.java:332
android.widget.FrameLayout.onLayout FrameLayout.java:270
com.android.internal.policy.DecorView.onLayout DecorView.java:784
android.view.View.layout View.java:22848
android.view.ViewGroup.layout ViewGroup.java:6389
android.view.ViewRootImpl.performLayout ViewRootImpl.java:3475
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:2943
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1948
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:8177
android.view.Choreographer$CallbackRecord.run Choreographer.java:972
android.view.Choreographer.doCallbacks Choreographer.java:796
android.view.Choreographer.doFrame Choreographer.java:731
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:957
android.os.Handler.handleCallback Handler.java:938
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:223
android.app.ActivityThread.main ActivityThread.java:7680
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:592
com.android.internal.os.ZygoteInit.main ZygoteInit.java:947
