### ISSUE TITLE
Images in common MAUI resources, are not accessible by resource id in Android platform code

### ISSUE THREAD

**Issue by inderpalaulakh** [dotnet/maui#13151]
Issue: Images in common MAUI resources, are not accessible by resource id in Android platform code. `context.Resources.GetIdentifier("cat.png", "drawable", context.PackageName)` returns `0`.

Description:
1. I added a image in `Resources`` folder and is displayed successfully by Android and iOS by by Maui. 
![image](https://user-images.githubusercontent.com/11532702/217121609-dcf4855b-2beb-46f4-a0da-1244942883d0.png)
2. In Android platform code (C#), below code returns `0` resource id. 
```cs
int resID = context.Resources.GetIdentifier("cat.png", "drawable", context.PackageName);
Bitmap avatarBitMap = BitmapFactory.DecodeResource(context.Resources, resID);
```
3. Unzipped .aar and can confirm that image exists
![image](https://user-images.githubusercontent.com/11532702/217122162-dda0070e-cdf3-4836-93d3-ffc691c71279.png)

Note: for iOS platform code works fine.
```cs
UIImage avatar = UIImage.FromBundle("cat.png");
```

**Comment by mattleibow** [comment]
I think the issue on Android is that the extension is a lie. Android does not use extensions at runtime so if you remove the `.png` it should work.

An alternative I saw was to use the `FileImageSourceService`... some pseudo code:

```cs
var service = new FileImageSourceService();
var image = await service.LoadImageAsync("cat.png", ...);
```

See also this potentially similar code: https://github.com/dotnet/maui/issues/12556#issuecomment-1383231470

**Comment by iaulakh** [comment]
remove the .png helped. Thank you!
