### ISSUE TITLE
How to switch AndroidManifest.xml for multiple Android builds.

### ISSUE THREAD

**Issue by masatoru** [dotnet/maui#13155]
### Description

I want to switch `AndroidManifest.xml` for multiple Android builds.

Currently, `AndroidManifest.xml` file name is fixed and must be in the project folder or `Platforms/Android` folder.

FYI, I get the following error if I put AndroidManifest.xml in another folder.

```
Xamarin.Android.Common.targets(517,3): error XA1018: Specified AndroidManifest file does not exist: C:\dev\MauiSample\MauiSample\MauiSample\AndroidManifest.xml.
```

### Public API Changes

none

### Intended Use-Case

Since MAUI does not have `AndroidManifest` value in the build action property, it would be nice if `AndroidManifest` value is added or it can be switched as shown below when building.

```
<ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
  <None Include="Platforms\Android\Debug\AndroidManifest.xml" LogicalName="AndroidManifest.xml" />
</ItemGroup>
```

Thanks.

**Comment by mattleibow** [comment]
@jonathanpeppers do we have support for partial manifests or manifest merging these days.

**Comment by jonathanpeppers** [comment]
If you just want to move the file location, you can set `$(AndroidManifest)` in your `.csproj`:

https://github.com/xamarin/xamarin-android/blob/47a1df7b6911dc30b52164766984d3ed3c4f004e/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L76

So, you *should* be able to do:

```xml
<PropertyGroup>
  <AndroidManifest>Platforms\Android\$(Configuration)\AndroidManifest.xml</AndroidManifest>
</PropertyGroup>
```

Looking at MAUI, it seems like if this file doesn't exist the above would work?

https://github.com/dotnet/maui/blob/9ab7067150f78bc0917ac2fdfab994c921ac207c/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.SingleProject.targets#L40

@masatoru you'll need to experiment and let us know if what works. Thanks!

**Comment by masatoru** [comment]
Hi @jonathanpeppers.
It worked your way. Thank you very much!!

```
<PropertyGroup>
  <AndroidManifest>Platforms\Android\$(Configuration)\AndroidManifest.xml</AndroidManifest>
</PropertyGroup>
```

VisuaStudio's build action does not allow me to select the `AndroidManifest` value.
So I had mistakenly thought it was not available.
