### ISSUE TITLE
Created default .NET MAUI project with .NET 7 yest there are over 94 build errors

### ISSUE THREAD

**Issue by Jammooly1** [dotnet/maui#13160]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I Followed exact instructions on the website and I didn't do anything else. I tried dotnet restore, and other commands but they fail to install the workloads/nuget packages as well.

for example, here are two of the errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package Xamarin.Google.Crypto.Tink.Android. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	Notes1 (net7.0-android), Notes1 (net7.0-ios), Notes1 (net7.0-maccatalyst), Notes1 (net7.0-windows10.0.19041.0)	
```

**Comment by mattleibow** [comment]
I don't see the nuget.org source in the list of packages so I think that is why it can't find the related nugets.

Did you disable/remove that nuget source? Can you add this source in the package manager sources:

```
https://api.nuget.org/v3/index.json
```
