### ISSUE TITLE
MAUI Preview 4 Sadly does not work

### ISSUE THREAD

**Issue by vonwenm** [dotnet/maui#1316]
I had been delighted the amazing maui was released for experimentation. ….and when it will be ready for even the most basic alpha testing in a later preview I will be delighted again.

Have been trying to get MAUI Preview 4 to work but there seems to be no way. Granted maui-check is easy to deploy and works reliably. Howere then – when maui-check is all good and green the whole thing comes apart and gets worse and worse with no way to fix.

If you try to create Maui projects from the visual studio templates they break out of the box. any attempt to fix these breaks makes things worse. Preview 4 IS UNUSABLE. Please avoid the pain until this is fixed in a later PREVIEW.

Unless you like hundreds of error like the one below and no way of fixing them.

Error CS0234 The type or namespace name ‘AspNetCore’ does not exist in the namespace ‘Microsoft’ (are you missing an assembly reference?) MAUI_03.WinUI3 D:\MAUI\DEMO_03\MAUI_03\MAUI_03\MAUI_03.WinUI3\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator_Pages_FetchData_razor.cs 193 Active

**Comment by gviddy** [comment]
Preview 5 also does not work.

**Comment by jfversluis** [comment]
I don't mean to minimize your frustration here, but this seems about older previews so I will close these as (hopefully) they're outdated. Hope your experience with newer previews have been better! If you still experience issues, please feel free to open something new with the required details.

Thanks!
