### ISSUE TITLE
Set underlying sdk version to a lower version

### ISSUE THREAD

**Issue by yunusefendi52** [dotnet/maui#13183]
### Description

When I upgraded from Maui 7.0.49 -> 7.0.59 there is a minimum sdk version that maui needs, but I will ios for an example because it causes me to update xcode 14.0 to 14.2, and xcode is really huge to download
7.0.49 -> Microsoft.iOS.Sdk/16.0.1478
7.0.59 -> Microsoft.iOS.Sdk/16.2.1004

As you can see there is bumped version. if I compile maui 7.0.59 using Microsoft.iOS.Sdk/16.0.1478 it wouldn't work because Maui minimum requirement is using 16.2.1004 when it doesn't have to

Solution? I think pin the underlying sdk to the lowest version, for ios instead of `net7.0-ios` use `net7.0-ios16.0`

### Steps to Reproduce

1. compile maui app 7.0.59 using Microsoft.iOS.Sdk/16.0.1478

Expected: Compile just fine
Outcome: Error build

### Link to public reproduction project repository

do you need to? it's a dependency issue

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, Android

### Affected platform versions

iOS, Android

### Did you find any workaround?

Upgrade, but it's not a workaround, it's an obligation from Maui sigh

**Comment by yunusefendi52** [comment]
Related issue https://github.com/dotnet/sdk/issues/30103

**Comment by mattleibow** [comment]
I had a chat with the team working on Apple things and it appears that we use the latest versions of things because Apple requires that. Maybe not the instant we get the update, but often very soon after:

> Apple will reject submissions if they are not done with the current stable Xcode 
> Also Xcodes stop working, for example Xcode 13 no longer runs on Ventura at all
> and lastly Xcode forces users to upgrade macOS too, we are close to the next Xcode to require Ventura in order to work

**Comment by mattleibow** [comment]
I am going to close this as we are really driven by the schedule of the Apples.

**Comment by yunusefendi52** [comment]
Sorry @mattleibow 1 question. Isn't possible for library (maui in this case) to set minimum version to 16.0 for example? It will pickup whatever the user has. So library author doesn't have to force you (unless there is a difference api breaking change)

I am comparing current state with xamarin.forms. Xf has minimum version of Xamarin.iOS10 but it can be still compile using the targeted version (currently can be 16.0 or 16.2)

**Comment by yunusefendi52** [comment]
Here is for comparison inside nuget package, this is also the case for other platforms not just ios
![IMG_20230209_054009.jpg](https://user-images.githubusercontent.com/19399214/217667714-1cff0208-1655-495e-9c2e-3d8916707a64.jpg)

**Comment by mattleibow** [comment]
@dalexsoto ?

**Comment by rolfbjarne** [comment]
> Isn't possible for library (maui in this case) to set minimum version to 16.0 for example?

Kind of, but it gets complicated because MAUI is a workload, and not just a library. That means that you'd have to update the MAUI workload(s), but not the iOS workload, and then you're combining workloads from different versions, and that's not something we're testing (the test matrix would become huge after a while).

Also, due to https://github.com/dotnet/sdk/issues/30103, it's not currently possible (but that will hopefully be fixed).

**Comment by yunusefendi52** [comment]
Maui is kinda workload-_ish_ now, maui will use nuget package from (changes from @mattleibow https://github.com/dotnet/maui/pull/11206) is that changing anything?

So because maui will use nuget package instead of full workload, maui can use lower version?

just a reminder: this is also the case for other platforms, not just ios

**Comment by yunusefendi52** [comment]
Hi @mattleibow should this issue be open again? The reason is because Apple **will reject app** that uses old xcode version **but not the library it self**. So i think maui isn't going to be causing the problem if lower the minimum version (see xamarin.forms, uno.ui, basically other libraries)

**Comment by yunusefendi52** [comment]
Here is how it would look like (see net7.0-android30.0, net6.0-android30.0)

![Screen Shot 2023-02-11 at 5 27 30 AM](https://user-images.githubusercontent.com/19399214/218211520-17e684eb-62ee-4340-bfa1-bfa94ec560c8.png)

**Comment by yunusefendi52** [comment]
Ok, just spent GBs of bandwidth just to update maui. I am really wondering how can it be? 🤡 it shouldn't have to

**Comment by yunusefendi52** [comment]
Found another issue related to this I think https://github.com/dotnet/maui/issues/12122
