### ISSUE TITLE
[Maps] [Android] Registering for CameraMove events in a custom MapHandler disables Map.VisibleRegion.Center

### ISSUE THREAD

**Issue by mfeingol** [dotnet/maui#13186]
### Description

This is an odd one.

If you create a custom map type and a handler for it, and inside that handler you register for CameraMove events from the underlying GoogleMap (either via SetOnCameraMoveListener or the CameraMove event), the Maui Map's VisibleRegion property no longer updates when you move the map. In particular, the Center property always returns the map's initial location.

Comment out the `+=` to the CameraMove event, or the call to SetOnCameraMoveListener, and VisibleRegion.Center will update again.

### Steps to Reproduce

```c#
class CustomMapHandler : MapHandler
{
    protected override void ConnectHandler(Android.Gms.Maps.MapView platformView)
    {
        base.ConnectHandler(platformView);
        platformView.GetMapAsync(new CustomMapCallbackHandler(this));
    }

    internal void OnMapReady(Android.Gms.Maps.GoogleMap googleMap)
    {
        googleMap.CameraMove += this.OnCameraMoved;
    }

    void OnCameraMoved(object sender, EventArgs e)
    {
    }
}

class CustomMapCallbackHandler : Java.Lang.Object, Android.Gms.Maps.IOnMapReadyCallback
{
    readonly CustomMapHandler handler;

    public CustomMapCallbackHandler(CustomMapHandler handler)
    {
        this.handler = handler;
    }

    public void OnMapReady(Android.Gms.Maps.GoogleMap map)
    {
        this.handler.OnMapReady(map);
    }
}
```

### Link to public reproduction project repository

https://github.com/mfeingol/repros/tree/master/MapVisibleRegionRepro

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Android

### Affected platform versions

11 at least

### Did you find any workaround?

No.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on Android platform with sample project.
https://github.com/mfeingol/repros/tree/master/MapVisibleRegionRepro
![image](https://github.com/dotnet/maui/assets/82450723/dc72e6c5-0fa0-45da-9aa3-eee316c40f7b)

**Comment by mfeingol** [comment]
This appears to be fixed in .NET 8
