### ISSUE TITLE
[Android][Mac Catalyst]  ScrollView with Orientation Both cannot scroll both directions (missing scrollbar)

### ISSUE THREAD

**Issue by nengxingxu** [dotnet/maui#13187]
### Description

For Android,  You can only slide left and right to display the page, you cannot slide up and down.
For Mac Catalyst， You can only slide slide up and down to display the page, you cannot left and right .
Windows and iOS Work fine.

Windows
![1](https://user-images.githubusercontent.com/3445189/217418327-e7e80197-fe3e-4c55-a0d5-368e01e4565c.gif)
Andorid
![2](https://user-images.githubusercontent.com/3445189/217418531-cb7f9322-56e0-4976-b917-5930cc8e4045.gif)
Mac Catalyst
![3](https://user-images.githubusercontent.com/3445189/217419240-59423ec4-f550-4391-890e-1a2117aed85c.gif)
iOS
![4](https://user-images.githubusercontent.com/3445189/217419645-3d1e8b0e-7a06-4620-bf81-ba8dff8de5ad.gif)

### Steps to Reproduce

Example of a GitHub repository https://github.com/gudder/MauiApp2
Put GraphicsView inside ScrollView.

### Link to public reproduction project repository

https://github.com/gudder/MauiApp2

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android, macOS

### Affected platform versions

Andorid 12  maccatalyst 14

**Comment by rmarinho** [comment]
This was fixed by #13657
