### ISSUE TITLE
ObservableProperty causes build error

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#13191]
### Description

When you create an observable property, and then try to access it in the code, you get a build error.

### Steps to Reproduce

1. In Visual Studio, Create observable property
2. Access it in the code
3. Build - see error.

Example code:
```C#
    [ObservableProperty]
    public string _contact1Name;
....
        Contact1Name = "Hello";
```

Error	CS0103	The name 'Contact1Mobile' does not exist in the current context xxxx (net7.0-android), xxxx (net7.0-ios)	C:\xxx\SupportContactsPageVm.cs	63	Active

![image](https://user-images.githubusercontent.com/32165641/217504787-bf7c6bd6-74d4-4b26-bd98-75136741b4f6.png)

### Link to public reproduction project repository

?

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

net7.0

### Did you find any workaround?

No

**Comment by mattleibow** [comment]
This issue was moved to CommunityToolkit/dotnet#598
