### ISSUE TITLE
Question: Purpose of extra solution files

### ISSUE THREAD

**Issue by wjk** [dotnet/maui#132]
What is the purpose of the following files in the solution root?

* `.System.Maui.Android.nuget.sln`
* `.System.Maui.UAP.nuget.sln`
* `.System.Maui.iOS.nuget.sln`
* `.System.Maui.nuget.sln`

While trying to build Maui the other day, I ran into numerous issues regarding project files that weren't supported (e.g. UWP libraries) that were not detected and disabled automatically by VS. I was wondering if these files would help with this problem. Furthermore, I would appreciate being able to only load (for example) the core and iOS assemblies, but not the Android or UWP ones. Can these files help with that as well? Thanks!

**Comment by pictos** [comment]
@wjk I think that Maui already has this, look for the `slnf` files in the root folder. This [one](https://github.com/dotnet/maui/blob/build/.System.Maui.Android.slnf), for example, will load just the Android stuffs.

**Comment by wjk** [comment]
@pictos Yep, that's it! Thanks so much!
