### ISSUE TITLE
FilePicker: A device attached to the system is not functioning. (0x8007001F)

### ISSUE THREAD

**Issue by true-perfect-code** [dotnet/maui#13207]
### Description

I wanted to easily select a file in my project and used FilePicker and the example from the MAUI documentation. 

The file selection dialogue opens and I can select a file, but when I click on Open, the following error is triggered:

**A device attached to the system is not functioning. (0x8007001F)**

![image](https://user-images.githubusercontent.com/45635963/217616645-70dd4989-3baa-48a0-8533-9afd15bd47b8.png)

I first looked for this error here, but couldn't find anything. Then I searched for MAUI and this error, but I couldn't find anything either. But if you search only for error message, posts come up, but they are related to Windows.  One suggested restarting the PC, but that didn't help me either. My devices look fine and I had no problems with the PC:

![image](https://user-images.githubusercontent.com/45635963/217617036-a7ae87c9-b4a5-4c1b-997a-8f8a3a6c798b.png)

I have placed the demo app on GitHub.

Can anyone also reproduce this error and does anyone know maybe how I solve it?

Iam using:
- VS 2022 Version 17.4.4
- running on Windows 10 pro
- MAUI Blazor
- NET 7

Thanks

### Steps to Reproduce

1. Download my project from GitHub 
2. run it. and select file from dialog box
3. In the Try Catch the error should be triggered after selecting a file from the file dialog.

### Link to public reproduction project repository

https://github.com/true-perfect-code/FilePickerError.git

### Version with bug

7

### Last version that worked well

7

### Affected platforms

Windows

### Affected platform versions

Windows 10 pro

**Comment by drasticactions** [comment]
I couldn't repro this locally so checking your example I saw it was a Blazor app. Trying it there though, I can't get it to fail. 

<img width="745" alt="スクリーンショット 2023-02-09 11 52 36" src="https://user-images.githubusercontent.com/898335/217705949-44f9be0a-d1c6-4bf0-a9c9-64b822519dd3.png">

That error is very weird. It does seem hyper specific to your computer, but I've never seen it before. Could you post a full stack trace? My guess is that it's from WinUI, and even then it's probably deeper within Win32 or something. Most likely if you were to call the direct FilePicker APIs that essentials calls from a straight WinUI app, you would hit the same issue, regardless of MAUI.

**Comment by true-perfect-code** [comment]
When I couldn't find anything about this error, I also assumed that this error was computer specific. 

However, let's find out the cause of the error in this post.

Here is more information:

![image](https://user-images.githubusercontent.com/45635963/217746888-880f9418-425c-4b04-afe6-f378134030d7.png)

**StackTrace:**
```
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.Storage.AccessCache.IStorageItemAccessListMethods.Add(IObjectReference _obj, IStorageItem file)
   at Windows.Storage.AccessCache.StorageItemAccessList.Add(IStorageItem file)
   at Microsoft.Maui.Storage.FilePickerImplementation.PlatformPickAsync(PickOptions options, Boolean allowMultiple)
   at Microsoft.Maui.Storage.FilePickerImplementation.PickAsync(PickOptions options)
   at FilePickerError.Pages.Index.OnInitializedAsync()
```
![image](https://user-images.githubusercontent.com/45635963/217748354-c04293fa-e8d1-44ad-9efa-3a6d7437d303.png)

I tried to use

`var dialog = new Microsoft.Win32.OpenFileDialog(); `

unfortunately this does not work in MAUI.


Thanks

**Comment by true-perfect-code** [comment]
Maybe my SSD is causing the "problem" in MAUI. It is an **M.2 SSD**!

It would be very interesting if someone also had the **M.2** (SSD) configuration to see if the problem really comes from that?

In any case, I can't see anything wrong in Windows:

![image](https://user-images.githubusercontent.com/45635963/217792339-dc8a62a2-8070-408a-990a-0e4df8ac1d4f.png)

![image](https://user-images.githubusercontent.com/45635963/217792602-551958ed-b19c-4303-9a78-d6df320a5bdc.png)

**Comment by true-perfect-code** [comment]
I found out where the problem comes from (at least I think I did). It comes, as I suggested in the last post, from **M.2 SSD**.

I took an SSD from another computer and connected it to SATA. Windows 10 pro is also installed on SSD, also Visual Studio and MAUI. So I could use exactly the same demo project.

I was then able to select a text file via FilePicker and no error occurred (see pictures).

![image](https://user-images.githubusercontent.com/45635963/217805030-aee48585-4d72-43f7-ad98-63b26e8f6927.png)

![image](https://user-images.githubusercontent.com/45635963/217805098-80a22f0a-0f81-4af1-8496-cfc055af98a4.png)

![image](https://user-images.githubusercontent.com/45635963/217805593-a8af9272-d740-41c7-a07e-01ed96264b1a.png)

I can imagine two reasons for the error:
1. my M.2 SSD has a physical error/problem that causes this MAUI error =>  is not probable because otherwise Windows would have reported earlier if something was wrong with the M.2 SSD.
2. MAUI generally has a problem with reading files that are on a storage medium (e.g. SSD) that is communicated via M.2.

Now that we know how to reproduce the error, I think it will really not be a problem for MAUI team to fix this problem in a future version.

Thanks

**Comment by true-perfect-code** [comment]
**Additional information**

I have bought and installed a SATA SSD. I then copied the MAUI project to SATA SSD and ran it. but the error comes!

So my conclusions is that this error comes in relation to Windows. Because the first test with SATA SSD was that there was a Windows installed on the SSD. But this test is without Windows (because SSD was bought new).

I will now install Windows 10 and expect that the error will then no longer occur when I start the app from SATA SSD, which also has Windows on it.

I will report on this later...

**Comment by true-perfect-code** [comment]
...so after a few hours I installed Windows and Visual Studio 2022 (MAUI, ASP.NET and WPF) on the new SSD.

**Here is the summary:**

- If SATA SSD is set as primary in BIOS, then it doesn't matter where the project/app is located in which you use FilePicker in MAUI (i.e. whether it's on SATA or M.2 drive).

- If M.2 SSD is set as primary, then the above error message "A device attached to the system is not functioning. (0x8007001F)" is generated when using the MAUI FilePicker function. 

I will stop experimenting at this point, because work is waiting for me. However, it remains to be clarified whether this behavior always applies to M.2 SSDs. Because it could also be that something is physically wrong with my M.2 SSD and Windows therefore passes this error message to MAUI.

I am interested to see how this problem will be solved.

Thank you MAUI teams for the excellent work you have done with MAUI Framework (especially in the direction of Blazor).

**Comment by drasticactions** [comment]
@mattleibow This feels like, maybe, a WinUI issue, or something with the Windows.Storage libraries that MAUI essential uses? Would this be a better fit if moved over there? I don't think there's anything that can be solved in this repo.

**Comment by true-perfect-code** [comment]
Where exactly should I post this problem? Please provide the link. Thanks.

**Comment by mattleibow** [comment]
I think you can start off by opening an issue at https://github.com/microsoft/WindowsAppSDK/issues

You can link to this one as well. I will try ping the windows people and see. Can you check if the other pickers have issues - like the media picker? I am wondering if the underlying apis have issues.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Not repro on windows platform with sample project.
[FilePickerError-master.zip](https://github.com/dotnet/maui/files/12331163/FilePickerError-master.zip)

**Comment by true-perfect-code** [comment]
I really hope that this is a problem with my M.2 SSD. Otherwise I'm sure we would have heard more about it here. Thanks for the effort. I close this issue.
