### ISSUE TITLE
O programa "[20588] MauiApp1.exe" foi fechado com o código 2147942405 (0x80070005).

### ISSUE THREAD

**Issue by KadyMix** [dotnet/maui#13211]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jsuarezruiz** [comment]
Update to the latest [Windows 10 OS January 19](https://support.microsoft.com/en-us/topic/january-19-2023-kb5019275-os-builds-19042-2546-19044-2546-and-19045-2546-preview-8ae1b678-d38c-4249-848d-06b722e7c0ad) update
Manually install the runtime with the [Windows App SDK Runtime Installer](https://aka.ms/windowsappsdk/1.2/latest/windowsappruntimeinstall-x64.exe)
Set the project property in your MAUI app project: false
Update to MAUI 7.0.59 (when it is released)

**Comment by KadyMix** [comment]
Hi guys. Thank you very much, @jsuarezruiz . It has worked perfectly...Now everything is cool. Thank you.
