### ISSUE TITLE
The project doesn't know how to run the profile Android Local device

### ISSUE THREAD

**Issue by ericbrunner** [dotnet/maui#1321]
### Description

After hitting **F5** I get the app properly deployed to the Android Phone ### HUAWEI VNS-L31 but the debugger doesn't start.

![image](https://user-images.githubusercontent.com/6480047/122016015-ef788500-cdc0-11eb-9b39-9b537c8271cf.png)

![image](https://user-images.githubusercontent.com/6480047/122014875-e3d88e80-cdbf-11eb-8120-c033c3c88413.png)

### Basic Information

![image](https://user-images.githubusercontent.com/6480047/122015109-184c4a80-cdc0-11eb-9300-374d57dfdce7.png)

![image](https://user-images.githubusercontent.com/6480047/122015349-50ec2400-cdc0-11eb-8c82-4d4f9b041ecf.png)

**Comment by matt-goldman** [comment]
I get the same error with Android Emulator

**Comment by expcat** [comment]
Looks like this bug.
https://developercommunity.visualstudio.com/t/Unable-to-deploy-to-emulator-or-device-u/1431718

**Comment by ericbrunner** [comment]
Thanks, but I have the most recent VS2019 Preview Release installed on 15.06.2021 and bug still there.

**Comment by MagicAndre1981** [comment]
update to 16.11 Preview 2.0

**Comment by matt-goldman** [comment]
Updating to 16.11 Preview 2.0 has fixed it for me
