### ISSUE TITLE
VMware

### ISSUE THREAD

**Issue by mrklausj** [dotnet/maui#13219]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows 10
VMware Workstation 16 Player
Visual Studio 2022 17.4.4
The program '[9416] MyFirstMauiApp.exe' has exited with code 2147942405 (0x80070005).

**Comment by holecekp** [comment]
This could be the same as https://github.com/dotnet/maui/issues/12080. You can try one of the workarouds in that issue.
