### ISSUE TITLE
iOS: Publish failed with "_GenerateDSym" failure if specify "-o:{path to custom directory}"

### ISSUE THREAD

**Issue by eshvatskyi** [dotnet/maui#13231]
### Description

publish process failed with error: "_GenerateDSym target" failed, dsymutil exited with code 1

### Steps to Reproduce

add -o:$publishDir to your "dotnet publish" command

### Link to public reproduction project repository

no need

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

Do not use "-o:$publishDir "

**Comment by jsuarezruiz** [comment]
Could you share more info?, more detailed output logs?

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-macios#17496
