### ISSUE TITLE
Installing android emulator

### ISSUE THREAD

**Issue by srilakshmigaya3** [dotnet/maui#13235]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I am new to .NET applications and also for android emulator. Whenever i tried to run the android emulator option in the menu, i got an error and the tutorial mentioned that double clicking will help the visual studio to install the required sdk. But the message says 
"Android SDK components installation failed
The debug was canceled. Please create an android emulator to debug the application. "
![image](https://user-images.githubusercontent.com/59032597/217946114-be0b669b-8753-41ec-b2c2-b5a702f9d673.png)

**Comment by jfversluis** [comment]
Hello @srilakshmigaya3 thank you so much for wanting to try .NET MAUI. I am sorry that you ran into an issue here.

It seems that something is going wrong with the Android components. Could you check under Tools > Android > Android SDK Manager what it says there? Did anything get installed?

You could then go to Tools > Android > Android Device Manager to setup an emulator. Try it from there and see if it gives you more information.

Are you running on an ARM machine by any chance?

If you're still running into issues when doing this, please go to the Help menu and then choose Provide Feedback > Report a Problem. That will make sure to include all the right logs and send it to the right team.

Hope we can get this sorted soon to get you started on your .NET MAUI journey!
