### ISSUE TITLE
The template generates invalid code? MAUI targeting  .net 7 in Visual Studio IDE 2022.

### ISSUE THREAD

**Issue by zetaFairlight** [dotnet/maui#13248]
I used to be able to use MAUI without issue, but now I'm encountering a lot of errors when I create a MAUI solution targeting dotnet 7. Despite reinstalling, resetting Visual Studio, and running a cleanup app from Microsoft, I still have many issues. For example

- Error	CS1061	'IServiceCollection' does not contain a definition for 'AddMauiBlazorWebView' and no accessible extension method 'AddMauiBlazorWebView' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	

- MauiApp2 (net7.0-android), MauiApp2 (net7.0-ios), MauiApp2 (net7.0-maccatalyst), MauiApp2 (net7.0-windows10.0.19041.0)

- Warning (active)	RZ10012	Found markup element with unexpected name 'SurveyPrompt'. If this is intended to be a component, add a @using directive for its namespace.		_*******_MauiApp2\Pages\Index.razor

I have both Unity and Visual Studio Code installed and updated on my Windows 10 machine.

**Comment by Eilon** [comment]
Hi @zetaFairlight , that certainly seems quite unexpected. Can you check in Solution Explorer to see whether the `Microsoft.AspNetCore.Components.WebView.Maui` package is listed as a dependency of any of ios/android/maccatalyst/windows:

![image](https://user-images.githubusercontent.com/202643/218165545-01c0e4d2-775d-438e-aa35-96b50309f5ff.png)

**Comment by Eilon** [comment]
Yeah that should be fine. That package looks like it's working, and that's where the `AddMauiBlazorWebView` comes from, so I'm not sure why it can't find it.

Does this happen even when you create a brand new .NET MAUI Blazor project? Or is this from a pre-existing project that stopped working?

**Comment by Eilon** [comment]
So even a .NET MAUI project without Blazor isn't working? Which error(s) do you get for that?

Having .NET 6 and .NET 7 at the same time should be totally fine.

**Comment by Eilon** [comment]
@zetaFairlight thank you for posting the info. I'm guessing there's some issue with the installation of .NET MAUI and/or Visual Studio on your computer, though you said you've run the clean-up process before. Would it be worth trying to repair the Visual Studio installation one more time?
