### ISSUE TITLE
ScrollView not updating size on iOS

### ISSUE THREAD

**Issue by andreeabuzuriu11** [dotnet/maui#13246]
### Description

ScrollView is not updating its size on iOS which results in scroll not working on iOS.
I noticed this problem by adding multiple labels under ScrollView which ultimately makes them not fit on the screen anymore. 
The new elements are added to the list but the new ones (which don't fit the initial screen) cannot be scrolled to.
On Android the scroll is working fine.

A comparison between iOS and Android can be seen below:

https://user-images.githubusercontent.com/62621512/218099482-86d578fa-107d-47cd-85e3-8803c355d6b6.mov

### Steps to Reproduce

    <ScrollView>
        <VerticalStackLayout BackgroundColor="Red">
            <Button Text="Add"
                    Command="{Binding AddItemCommand}"
                    WidthRequest="100"
                    Margin="10" />
            <VerticalStackLayout
                BackgroundColor="Yellow"
                Spacing="25"
                Padding="30,0"
                BindableLayout.ItemsSource="{Binding Items, Mode=TwoWay}">
                <BindableLayout.ItemTemplate>
                    <DataTemplate x:DataType="sampleExpander:Item">
                        <Label Text="{Binding Label}"
                               FontSize="16" />
                    </DataTemplate>
                </BindableLayout.ItemTemplate>
            </VerticalStackLayout>
        </VerticalStackLayout>
    </ScrollView>

Checkout this repository: https://github.com/andreeabuzuriu11/MauiSampleExpander
Open the solution
Run it on iOS
Add some more labels using the "Add" button on top of the screen
Try to scroll

### Link to public reproduction project repository

https://github.com/andreeabuzuriu11/MauiSampleExpander

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by KieranMaclagan** [comment]
I'm seeing something similar. On iOS I can scroll, but anything outside the initial view can't be tapped on.

**Comment by hartez** [comment]
If I clone the linked repository, open the solution, and change the Target .NET Runtime to 7, it works (I can scroll to the added items).
