### ISSUE TITLE
[Windows][Picker] Background and BackgroundColour properties are not updating

### ISSUE THREAD

**Issue by joaowatchful** [dotnet/maui#13269]
### Description

Picker Background and BackgroundColor properties don't seem to change when value is assigned **directly** or through the **VisualStateManager**.

**Invalid State:**
![image](https://user-images.githubusercontent.com/99800206/218234344-67ed1dd2-6db3-4776-a427-77b62e996196.png)

**Valid State:**
![image](https://user-images.githubusercontent.com/99800206/218234347-18476c5b-2209-4e30-8483-cb39d2c72e7e.png)

**What should be the Valid State:**
![image](https://user-images.githubusercontent.com/99800206/218235376-db849c89-7369-4280-a096-7ebaf6fe7427.png)

I've tested with using TextColor instead of Background/BackgroundColor and it's definitely working as expected.

### Steps to Reproduce

Assign value **directly**:
```
picker.Background = IsValid ? Brush.Green : Brush.Red;  //or
picker.BackgroundColor = IsValid ? Colors.Green : Colors.Red; 
```
Assign the visual state through the **VisualStateManager**:
```
<Style x:Key="smValidatablePickerStyle" BasedOn="{StaticResource smPickerStyle}" TargetType="Picker" >
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState Name="Valid">
                        <VisualState.Setters>
                            <Setter Property="Background" Value="{AppThemeBinding Light={StaticResource SuccessBrush}, Dark={StaticResource SuccessBrush}}" />
                            //or <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource Success}, Dark={StaticResource Success}}" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState Name="Invalid">
                        <VisualState.Setters>
                            <Setter Property="Background" Value="{AppThemeBinding Light={StaticResource DangerBrush}, Dark={StaticResource DangerBrush}}" />
                            //or <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource Danger}, Dark={StaticResource Danger}}" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>
```

```
var str = IsValid ? "Valid" : "Invalid";
VisualStateManager.GoToState(picker, str);
```

### Link to public reproduction project repository

Easy to reproduce, let me know if you need a repository

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

N/A

**Comment by jsuarezruiz** [comment]
Could you attach a sample where reproduce the issue?.

Cannot reproduce the issue doing a quick test with Normal and Focused VisualStates.
![picker-colors-win](https://user-images.githubusercontent.com/6755973/218419150-43e76d05-fca9-41b8-b9ca-f3db1b9c648e.gif)

**Comment by joaowatchful** [comment]
@jsuarezruiz I will try to attach a sample repository as a soon as I'm able to, thank you
