### ISSUE TITLE
Directory.CreateDirectory does not work

### ISSUE THREAD

**Issue by devhl-labs** [dotnet/maui#13281]
### Description

I also see the issue that was reported here https://github.com/dotnet/maui/issues/8089 There is no error and the returned object indicates the directory exists, yet it does not.

```
// works
var a = Directory.CreateDirectory(@"C:\Users\devhl\Desktop\test"); 

// does not work
var b = Directory.CreateDirectory(@"C:\Users\devhl\AppData\Roaming\test");
```

![image](https://user-images.githubusercontent.com/29644329/218290719-4e441d95-92fc-4159-86b5-812af83281ea.png)

![image](https://user-images.githubusercontent.com/29644329/218290736-d67369e7-faba-48ef-aae4-6c205843521a.png)

### Steps to Reproduce

    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var a = Directory.CreateDirectory(@"C:\Users\devhl\Desktop\test");
            var b = Directory.CreateDirectory(@"C:\Users\devhl\AppData\Roaming\test");

            var builder = MauiApp.CreateBuilder()
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                });

            return builder.Build();
        }
}

### Link to public reproduction project repository

see steps above

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows .net7.0

**Comment by drasticactions** [comment]
That's not a MAUI bug; that's a limitation of WinUI Packaged apps.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/898335/218298757-99958c67-a384-4e21-aa94-9cbd5ae1f21f.png">

This is a WinUI3 template app. It doesn't work there, either. As MAUI Uses packaged WinUI 3 for its apps, it affects it too, but that's something that needs to be addressed in WinUI.

I would redirect this bug over to https://github.com/microsoft/microsoft-ui-xaml

For how to fix your issue, you should probably use `Microsoft.Maui.Storage.FileSystem.AppDataDirectory`. That's a cross-platform implementation of the Roaming settings you may want.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/898335/218299047-93bd8495-795a-4bcb-8aaf-143aa4fa8157.png">

`LocalState` is a synced instance that is created for your WinUI/MAUI App, and that's writable by default.
