### ISSUE TITLE
.NET MAUI Maps for iOS doesn't allow to zoom in and out

### ISSUE THREAD

**Issue by thebravedave** [dotnet/maui#13288]
### Description

Hello, I am following your Microsoft.Maui.Controls.Maps tutorial:
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/map?view=net-maui-7.0
[ https://www.nuget.org/packages/Microsoft.Maui.Controls.Maps/ ]

When I load it in MacCatalyst I get a map that i can use my scroll wheel to zoom in and out.
When I load any of my iOS emulators (iOS16.2) the map loads but I can't scroll in or out using the scroll wheel.
If I double click the map it zooms in but I can never zoom out.
I don't have a physical device I can test this on.

Computer: Macbook Air M1 Ventura.
Xcode: 14.2
Visual Studio 2022 Mac

Here is my GitHub repository with all of the code:
https://github.com/thebravedave/HelloWorldMap

I really love how MAUI is integrating maps and I want to use it for a bunch of projects but so far it doesn't seem to work.
Is there a bug in the library or am I doing something wrong?  
I followed the tutorial that was put out.
NOTE: I have not set up Android Google Cloud Maps SDK key for this repository as I don't want to share my key.

### Steps to Reproduce

1) Create a new .NET 7 MAUI app.
2) Add Microsfot.Maui.Controls.Maps NuGet Package.
3) Initialize Map library in MauiProgram.
4) Add map control to MainPage
5) Build and run on iOS simulator.
6) Notice that you can't zoom in or out.

### Link to public reproduction project repository

https://github.com/thebravedave/HelloWorldMap

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

16.2

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Hey @thebravedave thanks for bringing this to our attention!

I do think that the zoom works fine though. From what I can see this is key: 

> but I can't scroll in or out using the scroll wheel.

Indeed you can't do that. The Simulator does not recognize the scroll wheel. You will want to press the Option key while the Simulator has focus. This will show you two dots. Now with Option pressed you can click with your mouse cursor and move the dots closer or further apart to simulate a pinch or pan gesture just like you would do on a physical device.

Then you'll see zoom works as intended. Or of course, run it on a physical device.
