### ISSUE TITLE
mct:IconTintColorBehavior doesn't work on winUI <image> or <imagebutton>

### ISSUE THREAD

**Issue by TheLankyScottishNerd** [dotnet/maui#13285]
### Description

Using tint color to change the icon / image colours doesn't apply when deployed to windows.

an example project has been linked which shows two images, one of which is an imagebutton, with the behaviour attached and no visible changes.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/8051530/218322617-fe052dc0-9015-4fee-b6c1-b30a1833ac59.png">

Works ok when deployed to iOS or android.
<img width="202" alt="image" src="https://user-images.githubusercontent.com/8051530/218322582-f2870af6-a1eb-4280-8fd9-6d022ba1a162.png">

### Steps to Reproduce

1.  Create new MAUI App.
2.  Add community toolkit and namespaces to project.
3.  Add icon tint behaviour to the dotnet bot image.
4.  run on 3 platforms and observe bug.

### Link to public reproduction project repository

https://github.com/TheLankyScottishNerd/IconTintWinUI

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by pictos** [comment]
Isn't a bug. There's no support for winui. You should see a warning telling you that... Maybe the warning can't be visible in xaml? 🤔
