### ISSUE TITLE
Null reference for jsRuntime in .net MAUI app with BlazorWebView

### ISSUE THREAD

**Issue by LeviSTA** [dotnet/maui#13293]
### Description

Hi there, I'm currently trying to add communication between a .net MAUI app and a BlazorWebView.

But I keep running into a null reference for jsRuntime.

### Steps to Reproduce

1. Start the app, click the button, and then the null reference will appear.

### Link to public reproduction project repository

https://github.com/LeviSTA/MAUIBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Api 33

**Comment by Xyncgas** [comment]
https://github.com/LeviSTA/MAUIBug/blob/main/MauBlazoriApp/MauiApp1/JsInteropCommunication.cs
Line 7
do this
![image](https://user-images.githubusercontent.com/35312807/218726965-aefbc4f7-b175-400a-a0aa-f23c656167ea.png)
not some lazy Task

**Comment by LeviSTA** [comment]
That's not the issue at hand. Still doesn't get the reference to the IJSRuntime.

**Comment by Eilon** [comment]
Hi, it looks like the repro project is no longer available. If you're still experiencing this problem, can you make sure the repro project is available? (Or share a relevant code snippet?)

**Comment by Xyncgas** [comment]
I'm using blazor for MAUI, trust me bro the injection works
![image](https://github.com/dotnet/maui/assets/35312807/f5d1c8bf-b8a3-4d1f-910b-6e7f131db273)
