### ISSUE TITLE
Error: System.Exception

### ISSUE THREAD

**Issue by ThomasBlervaque** [dotnet/maui#13298]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I try to create a new project with .NET MAUI App (C#) microsoft visual studio return me this :

![image](https://user-images.githubusercontent.com/64147824/218484206-ad786f48-ec84-4dde-b606-bce520e82443.png)

**Comment by jfversluis** [comment]
Hi @ThomasBlervaque thanks for wanting to try .NET MAUI! I'm sorry you're having some issues.

What version of Visual Studio is this? Did you freshly install this? And what version of Windows are you running this on? Does a .NET MAUI Blazor template work? Does any other project template work?

Ideally you'll want to report this through Visual Studio, this seems to be an issue with them, but I'm happy to see if I can be of any assistance here. Let me know if there is any more information you can share.

**Comment by ThomasBlervaque** [comment]
Hi @jfversluis, Its Visual Studio Community 2022 v17.4.4, I installed today, I use Windows 10 the latest version.
No I dont see the same error but 0 project is create.

Thanks for your answer !
