### ISSUE TITLE
Maui Community pop up doesn't work in OnAppearing()

### ISSUE THREAD

**Issue by BrianJSavage** [dotnet/maui#13305]
### Description

I used the Maui Community PopUp example to test this issue, after I couldn't get it to work in my new app.

I needed to display a message when a page is first opened, so put the PopUp call in OnAppearing().

It fails there with System.InvalidOperationException: 'Could not locate MauiContext.'

### Steps to Reproduce

1. Create the Popup app as described here: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup
2. Add a call for the pop as below in OnAppearing() 
3. It works with the OnAppearing call commented out, but not if used.

using CommunityToolkit.Maui.Views;
namespace PopUpTest;
public partial class MainPage : ContentPage{
	int count = 0;
	public MainPage()
	{
		InitializeComponent();
	}
	protected override void OnAppearing()
	{
		//DisplayPopup();
	}
		private void OnCounterClicked(object sender, EventArgs e)
	{
		DisplayPopup();
		count++;
		if (count == 1)
			CounterBtn.Text = $"Clicked {count} time";
		else
			CounterBtn.Text = $"Clicked {count} times";

		SemanticScreenReader.Announce(CounterBtn.Text);
	}
	public void DisplayPopup()
	{
		var popup = new SimplePopup();
		this.ShowPopup(popup);
	}
}

### Link to public reproduction project repository

https://github.com/BrianJSavage/PopUpTest.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Latest versions available

### Did you find any workaround?

No

### Relevant log output

```shell
none
```

**Comment by drasticactions** [comment]
This would probably be a better fit to file this in https://github.com/CommunityToolkit/Maui

**Comment by BrianJSavage** [comment]
Done.

 

Should I leave open in the dotnet/maui?

 

Or will someone close it?

 

brian

**Comment by drasticactions** [comment]
I'll close it. If they see it's an issue with MAUI itself, you can reopen this issue. Thanks for filing!
