### ISSUE TITLE
UriImageSource and dependencies

### ISSUE THREAD

**Issue by ehsangfl** [dotnet/maui#13309]
### Description

UriImgaeSource creates a HttpClient instance and load image through it. this is not correct behavior and httpClient should be resolved through DI.
currently, we cannot load image from source that needs an authentication/authorization token

### Steps to Reproduce

load image from URI that needs authentication/Authorization token

### Link to public reproduction project repository

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/UriImageSource.cs

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

Resolve HttpClient through DI

**Comment by drasticactions** [comment]
That should be taken care of with https://github.com/dotnet/maui/pull/10995

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Not repro this issue.

![image](https://github.com/dotnet/maui/assets/82450723/c09ed5d0-9c4e-4cbd-b20d-0d4c2aa5c72c)
