### ISSUE TITLE
Button in Maui Transparent

### ISSUE THREAD

**Issue by micswe** [dotnet/maui#13317]
### Description

Hi, 
i have problem with Background Color in Buttons.

### Steps to Reproduce

1. Create a new Maui Projekt VS 17.4.4 in Windows 10
2. Run the Projekt F5

![image](https://user-images.githubusercontent.com/58488062/218758368-72f0b90b-3af8-489c-8e57-2995b0cd6479.png)

The Button is Transparency, but i have now idea why.

            <Button
                x:Name="CounterBtn"
                Text="Click me"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center"
                BackgroundColor="Black"/>

### Link to public reproduction project repository

h

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Windows 

### Did you find any workaround?

No Workaround at the moment.

> VS bug [#1749171](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1749171)

**Comment by micswe** [comment]
Hi i Upload a Sample Projekt to GitHub.

https://github.com/micswe/MauiTest

**Comment by micswe** [comment]
I tried the Projekt on MAC OS, and it Works. I have the Problem only under Windows. With VS.

**Comment by jsuarezruiz** [comment]
Are you using 6.0.312?. Cannot reproduce the issue with .NET 7.
![image](https://user-images.githubusercontent.com/6755973/218972068-fe6d6de5-76b8-4bec-a64d-8ea09e33de26.png)

**Comment by micswe** [comment]
I test both version first with .net 6 the last Projekt ist with .net 7, I think the issue is in VS not in the Projekt. In your Screen shot you see a Status Bar with Black Symbols.

![image](https://user-images.githubusercontent.com/58488062/219103021-492fe0b7-9ff3-4700-bbbf-f51a1b1e37a9.png)

In my Projekt the Symbols ar "Transparent".
Why ?

**Comment by chabiss** [comment]
@micswe did you create a VS feedback tickets as mentioned above?
