### ISSUE TITLE
Grid rows overlap when a cell content is wrapped

### ISSUE THREAD

**Issue by jns300** [dotnet/maui#13315]
### Description

Rows in Grid layout overlap when an upper cell content is wrapped and the Grid has two columns (the first Star and the second Auto).

From MainPage.xaml:

        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"></RowDefinition>
                <RowDefinition Height="Auto"></RowDefinition>
                <RowDefinition Height="Auto"></RowDefinition>
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"></ColumnDefinition>
                <ColumnDefinition Width="Auto"></ColumnDefinition>
            </Grid.ColumnDefinitions>
            <VerticalStackLayout
                Spacing="25"
                Padding="30,0"
                VerticalOptions="Center">
                <Label
                    Text="0000 1111 0000 1111 0000 1111 0000 1111 0000 1111 0000 1111 0000 1111 0000 1111 0000 1111 0000 1111"
                    FontSize="32"
                    HorizontalOptions="Center" />
            </VerticalStackLayout>
            <Image Grid.Column="1"
                Source="dotnet_bot.png"
                HeightRequest="200"
                HorizontalOptions="Center" />
            <Label Grid.Row="1"
                Text="Bottom Label"
                FontSize="18"
                HorizontalOptions="Center" />
            <Image Grid.Row="2"
                Source="dotnet_bot.png"
                HeightRequest="100"
                HorizontalOptions="Center" />
        </Grid>

The picture below shows that the first row overlaps the second row when the text from the top cell is wrapped:
![WithSecondColumnNet6](https://user-images.githubusercontent.com/18332092/218711177-3b5f63fb-2f74-49f2-8cdc-1bd461fbcff2.png)

When there is no second column then Grid cells are presented correctly:
![NoSecondColumnNet6](https://user-images.githubusercontent.com/18332092/218711308-f70085f3-e328-4dd8-a26a-c76a60a22498.png)

The issue appears in .NET version 6.0.405 and 7.0.102.

### Steps to Reproduce

The Grid has to have two columns and at least two rows.  
Content of the cell from the first row and the first column has to be wrapped.

### Link to public reproduction project repository

https://github.com/jns300/Bugs/tree/main/GridLayoutBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 11, Android 9 API 28

**Comment by Xyncgas** [comment]
This is exact what motivates me to stop using XAML and DIY UI library instead of relying on other people to write them for you because you want to put Microsoft at making a product that works so when other things don't work you can fix it yourself

**Comment by jns300** [comment]
The issue is resolved in .NET version 7.0.5.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on Windows and Android platform with sample project.
https://github.com/jns300/Bugs/tree/main/GridLayoutBug
![image](https://github.com/dotnet/maui/assets/37974803/5ff27fbe-e4a9-4f1a-87b0-e4ec8ea1c586)
