### ISSUE TITLE
(Even empty app, not with other regular desktop browsers) MAUI.Blazor, with rapid (keyboard + mouse) input between multiple div element with contenteditable set to true, becomes unresponsive to mouse / touch

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/maui#13314]
### Description

My struggle : 

After abandoning the input MAUI.Blazor gave me I created my custom input using html ```contenteditable``` attribute. I enjoyed using it I had apps built with it using both Blazor and MAUI Blazor in the past.

Recently after a certain update that I don't know which, the UI freezes when I typed rapidly while clicking between multiple input rapidly. It hangs in a way that you can still type but you can no longer click between these elements with ```contenteditable``` set to True / true rapidly in fact anywhere you move the mouse cursor looks like you are inputting something while you are unable to interact with the UI using your mouse

If I switch to Blazor webassembly it doesn't happen, if I do it with application built with older version of MAUI.Blazor it wont happen.

### Steps to Reproduce

Minimum repo : 
Launch empty MAUI.Blazor, delete everything in the body tag and just put 3 ```div``` element with ```contenteditable``` set to true, then type rapidly while trying to click between them

https://user-images.githubusercontent.com/35312807/218724725-4ae3a8ce-ff7f-4001-9c2d-334599ddf203.mp4

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by hartez** [comment]
You might be experiencing this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003

**Comment by Xyncgas** [comment]
yea likely
