### ISSUE TITLE
Publish to Windows Storage

### ISSUE THREAD

**Issue by JORGEGO** [dotnet/maui#13324]
### Description

I am using Visual Studio to publish to Windows Storage

But everytime same error
1>Improper project configuration: WindowsPackageType is set to None, but PublishAppxPackage is set to true.
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
========== Elapsed 00:36.362 ==========
========== Package: 0 succeeded, 1 failed ===========

### Steps to Reproduce

I have create my project solution is composed by a class library and .net maui app
All works perfect in debug environment, can install, test and all works perfect
So I change to release configuration
And use 
https://learn.microsoft.com/es-es/dotnet/maui/windows/deployment/publish-visual-studio-folder?view=net-maui-7.0
But I could not generate the MSIX package

### Link to public reproduction project repository

q

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by JORGEGO** [comment]
When I try to compile the class library error is:
C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(299,5): error NETSDK1094: Unable to optimize assemblies for performance: a valid runtime package was not found. Either set the PublishReadyToRun property to false, or use a supported runtime identifier when publishing. When targeting .NET 6 or higher, make sure to restore packages with the PublishReadyToRun property set to true.
1>Done building project "greenyng.mobile.business.common.csproj" -- FAILED.

**Comment by JORGEGO** [comment]
It seems I have found a solution base on https://github.com/dotnet/maui/issues/12548 I have unchecked all and started to compile and after that I could generated the msix... so I believe could found an workaround

**Comment by JORGEGO** [comment]
So for the moment I close the issue

**Comment by lutzroeder** [comment]
@sbanni @beckybuckler

**Comment by sbanni** [comment]
We have this [WinAppSDK issue](https://github.com/microsoft/microsoft-ui-xaml/issues/7846) that is tracking this.
