### ISSUE TITLE
Long running GeoLocation

### ISSUE THREAD

**Issue by gktval** [dotnet/maui#13335]
### Description

I am using GeoLocation to do gps tracking. So getting the location is called in a loop once a second 

```
_gpsRequest = new GeolocationRequest(GeolocationAccuracy.Best, TimeSpan.FromMilliseconds(1000));
Location location = await Geolocation.Default.GetLocationAsync(_gpsRequest, _cancelTokenSource.Token);
```

Evertime GetLocationAsync is called, the gps icon in the task bar flickers on and off. This seems a bit erratic. Perhaps it can be possible to create a long-running GPS event that keeps the icon from flickering on and off.

### Steps to Reproduce

To reproduce, call  Geolocation.Default.GetLocationAsync multiple times in a loop once a second.

### Link to public reproduction project repository

na

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

Android 13 API 33

**Comment by Xyncgas** [comment]
C# is a managed memory language, therefore without the dangerous null pointer but with the phantom of objects that still lives without you seeing it haunting you sometimes.

The two lines you showed.. if they are in a loop they shouldn't be because you don't want to keep creating new objects in a loop. They wont go away for a while until garbage collection comes to pick them up

**Comment by gktval** [comment]
> The two lines you showed.. if they are in a loop they shouldn't be because you don't want to keep creating new objects in a loop. They wont go away for a while until garbage collection comes to pick them up

_gpsResult is obviously not in a loop for the reason you say.  Geolocation.Default is static and is not created each loop.

**Comment by gktval** [comment]
I am going to close this as I will port the GeolocationPlugin from Xamarin to Maui
https://github.com/jamesmontemagno/GeolocatorPlugin
