### ISSUE TITLE
App crash on iOS when using SQLite-net-pcl

### ISSUE THREAD

**Issue by Laim** [dotnet/maui#13334]
### Description

When trying to run an iOS App on a Physical device using SQLite-net-pcl (1.8.116) and .NET 6, when loading any data or trying to add data the application crashes or hangs/freezes.

I have only been able to reproduce this on iOS, using an iPhone 13 Pro Max and an iPhone 11 Pro - iOS 16 and iOS 16.3.1.  Unable to test on the iOS Simulator as it just refuses to boot at all. 

Application works as expected on Android (Sim and Physical) as well as Windows.

### Steps to Reproduce

1. Open Reproduction Project
2. Build to **iOS Remote Device**
3. The application should hang if connected to Visual Studio, if ran without a connection it will instantly crash.
4. Remove `Refresh()` from `HomeViewModel.cs` and it will open, but when you try to add a task item it will hang or crash when trying to pull the data.
5. Click `Settings` in-app, click `Delete All` and it will crash the app.

I have been able to re-create this on another application I'm working on, using the same code and versions.

### Link to public reproduction project repository

https://github.com/Laim/TodoIst

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16 - 16.3.1 (Tested)

### Did you find any workaround?

No

### Relevant log output

```shell
No log generated, although I may have looked in the wrong place.
```

**Comment by Laim** [comment]
Regrarding 'Version with Bug' - I'm definitely using .NET 6, but `dotnet workload list` returns 7.0.49/7.0.100 for iOS

**Comment by gktval** [comment]
I found out I did not have the bundle_green updated to the correct version. Not sure if this may be related to your issue or not.
https://stackoverflow.com/a/74007173/5792527

**Comment by Laim** [comment]
> Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")

Will try this now and report back, thank you!

**Comment by Laim** [comment]
> I found out I did not have the bundle_green updated to the correct version. Not sure if this may be related to your issue or not. https://stackoverflow.com/a/74007173/5792527

This appears to have worked (Option 1)!  My case based on your answer on SO was slightly different in that I didn't have `SQLitePCLRaw.bundle_green` at all for some reason?  

It looks like the dependency check for `sqlite-pcl-net` v1.8.116 may be incorrect as I retested in a completely blank project and it also didn't install bundle_green.  

Thank you so, so much.

**Comment by drasticactions** [comment]
To note: This would be an issue with running SQlite on iOS/Mac at all, verses something specific to the MAUI UI stuff. Some libraries (Like some EFCore's SQLite versions) don't include a native SQLite library by default so you have to provide one.

Closing this as it's not MAUI Related, glad you got a fix!.
