### ISSUE TITLE
Make IBorderElement properties settable

### ISSUE THREAD

**Issue by Jendx** [dotnet/maui#13349]
### Description

I'm not able to set properties of objects of this interface when using generic parameter.  
I have created 

Possible workaround is reflexion 

### Public API Changes

```csharp
 [EditorBrowsable(EditorBrowsableState.Never)]
    public interface IBorderElement
    {
        Color BorderColor { get; set; }
        int CornerRadius { get; set; }
        Color BackgroundColor { get; set; }
        etc...
    }
```

### Intended Use-Case

![Snímek obrazovky 2023-02-15 135436](https://user-images.githubusercontent.com/62170918/219032926-c0674969-d2cb-4ced-a515-e1559e5e99be.png)

**Comment by PureWeen** [comment]
These aren't meant to be settable via the interface.
Whoever implements this interface manages how they are set and then notifies the platform that they have changed.
