### ISSUE TITLE
[RelayCommand] not generating a command viewable in XAML

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13378]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/RelayCommand-not-generating-a-command-/10261412)._

---
With the latest release of community tool kit my relaycommands do not appear to be generating and are not selectable in a Binding statement.

In the code below the DragItemCompleteCommand is only found if I use the old method for defining a command vs. [RelayCommand]
    Command="{Binding DragItemCompleteCommand}"

```
?xml version="1.0" encoding="utf-8" ?>



        
    
    
     
<label>
        
            
                

```

```
namespace MyNextBook.ViewModels;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

using MyNextBook.Models;
using System.Collections.ObjectModel;
using System.Windows.Input;

[QueryProperty("Name", "name")]
public partial class EditSeriesViewModel : ObservableObject
{
 
public EditSeriesViewModel()
	{
        System.Diagnostics.Debug.WriteLine("EditSeriesViewModel");
	}

public ObservableCollection Items { get; set; }

Series selectedSeries;
    public string seriesName;
    public string displaySeriesName { get; set; }
    public int ItemCount { get; set; }
    public int FinishedItemCount { get; set; }
    public string HeaderString { get; set; }

public ICommand DragItemCompleteCommand => new Command(DragItemComplete);

private void DragItemComplete ()
    {
        int i = 1;
        foreach (Book b in Items)
        {
            b.SeriesBookSortOrder = i;
            i++;
        }
        OnPropertyChanged("Items");
    }
 
```

If I use the following code then DragItemCompleteCommand does not show up in the XAML and is not recognized.

```
[RelayCommand]
  
private void DragItemComplete ()
    {
        int i = 1;
        foreach (Book b in Items)
        {
            b.SeriesBookSortOrder = i;
            i++;
        }
        OnPropertyChanged("Items");
    }
 
```

---
#### Feedback Bot on 1/27/2023, 05:47 PM: 

(private comment, text removed)
#### brady on 1/28/2023, 08:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I think this is an issue for https://github.com/CommunityToolkit/dotnet

**Comment by Hakoyu** [comment]
This is actually a problem for [Visual Studio Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-does-not-recognize-source-g/10242238?q=mvvm&sort=newest)
[CommunityToolkit](https://github.com/CommunityToolkit/dotnet/issues/598) also think so
