### ISSUE TITLE
System.MissingFieldException after update MAUI Community Toolkit nuget to 4.0.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13375]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemMissingFieldException-after-updat/10274465)._

---
[severity:I'm unable to use this version]
Hello,
After update MAUI Community Toolkit nuget to 4.0.0 I get this error: "System.MissingFieldException: 'Field not found: int .Animation.linear_indeterminate_line1_head_interpolator Due to: Could not find field in class'"

Stepping through the app ends after last line in App constructor (MainPage = new AppShell();) then it construct Android MainActivity, after that this exception; MAUI MainPage constructor is not even called. Downgrading back to Community Toolkit 3.1.0 solve it.

---
#### Feedback Bot on 2/8/2023, 05:44 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
This sounds like something that needs some cache cleaning. Add the 4.0.0 version of the Toolkit again, remove your bin & obj folders from the file system and do some clean and rebuild actions in Visual Studio.

If that still doesn't help, please open an issue at https://github.com/CommunityToolkit/Maui

**Comment by bofden** [comment]
Works fine after deleting bin & obj, thanks!
