### ISSUE TITLE
MAUI multi-targeting is completely broken

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13377]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-multi-targeting-is-completely-broke/10277206)._

---
I have created a new empty project using the default Visual Studio template. I wanted to learn about creating custom handlers. 

The first problem is with the documentation. It is unclear which symbols should be used when targeting a platform: ANDROID, __ANDROID__, or MONODROID? Various parts of documentations and MAUI source code use all of them. For example:
- #elif **ANDROID** is used in the documentation at https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/create?view=net-maui-7.0
- #if **(underscore)(underscore)ANDROID(underscore)(underscore)** is used at https://github.com/dotnet/maui/wiki/Porting-Custom-Renderers-to-Handlers
- #elif **MONOANDROID** is used in the source codes at https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/Entry/EntryHandler.cs

The second problem is that all of them are broken. The following code highlights Windows part of #elif all the times, even when Android is selected as the target platform.
```csharp
#if ANDROID
using PlatformView = AndroidX.AppCompat.Widget.AppCompatEditText;
#elif WINDOWS
using PlatformView = Microsoft.UI.Xaml.Controls.TextBox;
#endif
```

I have tried the other symbols and there is the same bug. I am using the latest available VS and MAUI version. It seems that there is a closed issue in the MAUI repository which is very similar but the problem is still there even when the issue is marked as fixed (https://github.com/dotnet/maui/issues/6815). Also the workarounds from that issue do not work so maybe it is a different problem.

---
#### Feedback Bot on 2/12/2023, 06:25 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
> The following code highlights Windows part of #elif all the times, even when Android is selected as the target platform.

Does it only highlight it or does it also (not) compile? If it's just a visual thing then this is more of an issue with Visual Studio.

I'd love to see a reproduction project for this, even if it seems trivial to you. This would help us understand what the exact thing is that you are looking at without making assumptions. As you've already seen, we have a lot of these in our own source code, so it works. I'm wondering what it is that you are seeing that makes it not work.

Thanks!

**Comment by drasticactions** [comment]
This person is, most likely, not selecting the correct TFM from the Visual Studio dropdown from the editor. Changing the deployment TFM target, AFAIK, doesn't change the default from the editor dropdown too. 

<img width="568" alt="スクリーンショット 2023-02-16 18 25 41" src="https://user-images.githubusercontent.com/898335/219323804-a9720924-a139-49ca-863c-d1d8605afdfb.png">

(This is VSMac but it should be similar on VS, it defaults to the first item in the TFM list for the editor. In this case, Android)

The default TFM names for multitargetting are also not a MAUI UI Framework-specific thing. Those are set by the runtime (https://learn.microsoft.com/en-us/dotnet/standard/frameworks). There are legacy ones in use in the MAUI codebase since it was ported from older code. We could clean up the docs to make it consistent, though, and for anyone wanting to use multitargetting, I would follow the definitions in the standards doc I linked.

**Comment by holecekp** [comment]
The previous version of MAUI had big troubles with multi-targetting for Windows and I could not compile the project at all. The last update of MAUI/VS improved it a lot but it is still very hard to use. See the following screenshots (both with the latest VS 17.4.5). Android is selected as the target platform but #if ANDROID is grayed out and #elif WINDOWS is highlighted instead.
![maui multitargetting bug](https://user-images.githubusercontent.com/24872113/219972349-8a5758d4-0980-44a8-b9aa-2948ecbb0dcb.png)

When I opened the same project a few days latter, VS did not higlight any of the branches:
![maui multitargetting bug 2](https://user-images.githubusercontent.com/24872113/219972820-a7e4beec-14ee-4300-890c-349353f72cd0.png)

I am able to run the project both on Windows and Android. It seems to be more problem of VS highlighting. Another problem that makes it harder to use is that errors for all platforms are displayed. If I want the app to support Android and Windows only, a lot of errors for iOS and Mac are displayed. There is no filter. If there is a real error it is hard to find it among the others for the unsupported platforms.

**Comment by acaliaro** [comment]
It does not depend by the project you run but the platform you see in the upper left corner of the developer view (in this case there is windows as selected platform)

**Comment by holecekp** [comment]
Thank you. Now I understand. I have been selecting the platform from the drop-down menu next to the Play button and I have completely missed that there is another platform selector above the editor window (with a different value selected).

Still, there is a problem that when I change the platform form the drop-down in the upper left corner the correct code is highlighted first and after one second it is grayed out.

**Comment by PureWeen** [comment]
> Thank you. Now I understand. I have been selecting the platform from the drop-down menu next to the Play button and I have completely missed another platform selector in the upper-left corner of the editor window (with a different value selected). I am sorry for the misunderstanding.
> 
> Still, there is a problem that when I change the platform form the drop-down in the upper-left corner, the correct code is highlighted first and after one second it is grayed out. But this is probably related to VS and not MAUI.

@holecekp can you open a new issue on vsfeedback with these details please?

**Comment by holecekp** [comment]
I have reported it on vsfeedback. I think that this issue can be closed because it turned out that it is not a problem in MAUI.
