### ISSUE TITLE
[Bug] - Cannot run WinUI Apps after updating to 6.0.100-preview.5.21302.13

### ISSUE THREAD

**Issue by mogand** [dotnet/maui#1339]
### Description

After upgrading to maui preview 5 using  .NET MAUI Check v0.5.6.0, I can not run the WinUI, get the error "The project doesn't know how to run the profile MauiApp1.WinUI."

### Steps to Reproduce

1.  Create a new .NET MAUI App project
2.  Build
3. Run/Debug 

### Expected Behavior

Expected the WinUI app to build and run.

### Actual Behavior

Just pops up a dialogue with he message The project doesn't know how to run the profile MauiApp1.WinUI."

### Basic Information

- Version with issue: NET SDK - Packs (6.0.100-preview.5.21302.13
- Last known good version:  maui preview 4 
- IDE:  Microsoft Visual Studio Community 2019 Preview Version 16.11.0 Preview 2.0
 
- Platform Target Frameworks: 
- NET SDK - Workloads (6.0.100-preview.5.21302.13) Checkup...
  - microsoft-android-sdk-full (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 30.0.100-preview.5.28) installed.
  - microsoft-ios-sdk-full (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 14.5.100-preview.5.894) installed.
  - microsoft-maccatalyst-sdk-full (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 14.5.100-preview.5.894) installed.
  - microsoft-tvos-sdk-full (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 14.5.100-preview.5.894) installed.
  - microsoft-macos-sdk-full (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 11.3.100-preview.5.894) installed.

> .NET SDK - Packs (6.0.100-preview.5.21302.13) Checkup...
  - Microsoft.Maui.Templates (6.0.100-preview.5.794) installed.
  - Microsoft.Android.Sdk (30.0.100-preview.5.28) installed.
  - Microsoft.Android.Sdk.BundleTool (30.0.100-preview.5.28) installed.
  - Microsoft.Android.Ref (30.0.100-preview.5.28) installed.
  - Microsoft.Android.Templates (30.0.100-preview.5.28) installed.
  - Microsoft.iOS.Sdk (14.5.100-preview.5.894) installed.
  - Microsoft.iOS.Windows.Sdk (14.5.100-preview.5.894) installed.
  - Microsoft.iOS.Ref (14.5.100-preview.5.894) installed.
  - Microsoft.iOS.Templates (14.5.100-preview.5.894) installed.
  - Microsoft.MacCatalyst.Sdk (14.5.100-preview.5.894) installed.
  - Microsoft.MacCatalyst.Ref (14.5.100-preview.5.894) installed.
  - Microsoft.MacCatalyst.Templates (14.5.100-preview.5.894) installed.
  - Microsoft.tvOS.Sdk (14.5.100-preview.5.894) installed.
  - Microsoft.tvOS.Ref (14.5.100-preview.5.894) installed.
  - Microsoft.tvOS.Templates (14.5.100-preview.5.894) installed.
  - Microsoft.macOS.Sdk (11.3.100-preview.5.894) installed.
  - Microsoft.macOS.Ref (11.3.100-preview.5.894) installed.
  - Microsoft.macOS.Templates (11.3.100-preview.5.894) installed.

### Screenshots

![image](https://user-images.githubusercontent.com/16896432/122375175-54410480-cfa6-11eb-805a-4c76a38cbd84.png)

### Reproduction Link

None

### Workaround

Have not found a workaround

**Comment by AlexLablaiksSAP** [comment]
I had the same issue. There are two new extensions that need to be installed according to the [preview 5 blog post](https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-5/):
Project Reunion (Preview) Extension
Single-project MSIX Packaging Tools (Preview)

**Comment by mogand** [comment]
@AlexLablaiksSAP - Thanks fixed the issue

**Comment by coldino** [comment]
I have added both of these extensions and still get the same error. Any ideas what else I might be missing? maui-check output seems to match the details in the original issue here.

**Comment by mogand** [comment]
@coldino - I installed the missing extensions as mentioned by @AlexLablaiksSAP, then I created a new maui app, and debugged, the WinUI project, the project build and ran, but only the background colour where visible, I think the reason is that ScrollView and Grid has not been implemented  for desktop, if you remove the ScrollView,  Grid,  all references to Grid.Row and the Image then form will display.

Startup.cs no longer loads UseFormsCompatibility()

**Comment by coldino** [comment]
Finally, the solution for me was to right-click the WinUI project and 'Deploy'. So simple really, but didn't see that mentioned anywhere.
