### ISSUE TITLE
RemainingItemsThresholdReachedCommand is not called on iOS for IsGrouped CollectionViews

### ISSUE THREAD

**Issue by SophisticatedConsulting** [dotnet/maui#13391]
### Description

The code behind or command events for infinite scrolling in a CollectionView are not triggered for iOS, i.e. no additional data is populated.

This is already reported for Windows but not for iOS (which is critical for Xamarin migration (where it does work!).

For Windows, see also:
https://github.com/dotnet/maui/issues/8338
https://github.com/dotnet/maui/issues/9935

### Steps to Reproduce
Use sample attached
[CollectionView.zip](https://github.com/dotnet/maui/files/10769058/CollectionView.zip)

This works for Android but does not work for iOS or Windows, i.e. scrolling has no effect and a breakpoint set in the Command associated with RemainingItemsThresholdReachedCommand is never reached

### Link to public reproduction project repository

[CollectionView.zip](https://github.com/dotnet/maui/files/10769058/CollectionView.zip)

### Version with bug

7.0.200-preview.22628.1

### Last version that worked well

None

### Affected platforms

iOS, Windows

### Affected platform versions

ios 16.3

### Did you find any workaround?

No workaround (tried with different thresholds to no effect). This is a show-stopper for MAUI migration.

This has never worked with any maui SDK version (I have been trying to migrate Xamarin apps for over 1 year)!

I am not sure if anyone ever tested the sample app!

Please fix this.

**Comment by SophisticatedConsulting** [comment]
As indicated above, the issue is with an all versions of the Maui SDK including the latest release, 7.02 and the current pre-release installed with the latest VS preview build. 
The issue can be reproduced with the MS sample app referenced above.

**Comment by samirgcofficial** [comment]
I can confirm this is not the issue on latest iOS version and Latest maui version.  Here's the source code. But the threshold repeats for 5 time ? Any solution for this ? 
http://xamaringuyshow.com/wp-content/uploads/2023/02/CollectionViewRemainItemCommand.zip

**Comment by SophisticatedConsulting** [comment]
Please reopen this. It is not completed.

**Comment by ImproveSoftware2022** [comment]
Any news on this thread? Trying with latest official version but still happening on iOS and Windows, while working perfectly on Android.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on windows and iOS platform with sample project.
[CollectionView.zip](https://github.com/dotnet/maui/files/11865870/CollectionView.zip)

**Comment by ZackYangyang** [comment]
This issue also repro on Android platform.

**Comment by naaeef** [comment]
Based on the workaround of @kramer-e I wrote a workaround that uses handler instead of a custom renderer.

```
public class CustomCollectionViewHandler : CollectionViewHandler
{
    protected override ItemsViewController<ReorderableItemsView> CreateController(
        ReorderableItemsView itemsView,
        ItemsViewLayout layout)
    {
        return new CustomGroupableItemsViewController<ReorderableItemsView>(itemsView, layout);
    }
}

public class CustomGroupableItemsViewController<TItemsView>(TItemsView groupableItemsView, ItemsViewLayout layout)
    : GroupableItemsViewController<TItemsView>(groupableItemsView, layout)
    where TItemsView : GroupableItemsView
{
    protected override UICollectionViewDelegateFlowLayout CreateDelegator()
    {
        return new CustomGroupableItemsViewDelegator<TItemsView, CustomGroupableItemsViewController<TItemsView>>(
            ItemsViewLayout,
            this);
    }
}

public class CustomGroupableItemsViewDelegator<TItemsView, TViewController>(
        ItemsViewLayout itemsViewLayout,
        TViewController itemsViewController)
    : GroupableItemsViewDelegator<TItemsView, TViewController>(itemsViewLayout, itemsViewController)
    where TItemsView : GroupableItemsView
    where TViewController : GroupableItemsViewController<TItemsView>
{
    protected override (bool VisibleItems, int First, int Center, int Last) GetVisibleItemsIndex()
    {
        var (VisibleItems, First, Center, Last) = GetVisibleItemsIndexPath();
        int firstVisibleItemIndex = -1, centerItemIndex = -1, lastVisibleItemIndex = -1;

        if (VisibleItems) {
            firstVisibleItemIndex = AppendGrouping(First);
            centerItemIndex = AppendGrouping(Center);
            lastVisibleItemIndex = AppendGrouping(Last);
        }
        return (VisibleItems, firstVisibleItemIndex, centerItemIndex, lastVisibleItemIndex);
    }

    private int AppendGrouping(NSIndexPath indexPath)
    {
        int index = (int)indexPath.Item;

        if (indexPath.Section > 0) {
            for (int i = 0; i < indexPath.Section; i++) {
                index += ViewController.ItemsSource.ItemCountInGroup(i);
            }
        }

        return index;
    }
}
```
