### ISSUE TITLE
Default ShellContent on Mac Flyout

### ISSUE THREAD

**Issue by scottkuhl** [dotnet/maui#13409]
### Description

The default layout of the text and icon on the Flyout menu does not match Windows or any Mac standard.  The icon should be to the left of the text.  Padding and margins should also be cleaned up.

Windows:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/4465616/219567456-8b47efb3-6d3d-490b-8c56-a5213eb10fa3.png">

Mac:

<img width="211" alt="image" src="https://user-images.githubusercontent.com/4465616/219567607-24185b9b-8f50-42dd-af6a-981f82262980.png">

### Steps to Reproduce

Here is some example XAML in AppShell:

```
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="Notes.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:Notes"
    Shell.FlyoutBehavior="Locked">

        <ShellContent
            Title="Notes"
            ContentTemplate="{DataTemplate local:MainPage}"
            Icon="{OnPlatform 'icon_notes.png', iOS='icon_notes_ios.png', MacCatalyst='icon_notes_ios.png'}" />

        <ShellContent
            Title="About"
            ContentTemplate="{DataTemplate local:AboutPage}"
            Icon="{OnPlatform 'icon_about.png', iOS='icon_about_ios.png', MacCatalyst='icon_about_ios.png'}" />

</Shell>
```

### Link to public reproduction project repository

See XAML above

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

13.2

### Did you find any workaround?

You can restyle the shell content.

**Comment by pitasoft** [comment]
I mentioned this problem here, I think the problem is that if you use SVG images, you have to resize the images to 24x24 px. The icons remain adjusted.

Depending on the platform I use one icon or another.

<ToolbarItem Text="Refresh" 
                     IconImageSource="{OnPlatform Default='refresh.png',iOS='refresh_bk.png',MacCatalyst='refresh_bk.png'}" 
                     Order="Primary" 
                     Command="{Binding RefreshDataCommand}"/>

Although in the images you do this it will not work, you have to do it manually.

<MauiImage Include="Resources\Images\refresh_bk.svg" BaseSize="24,24" />

DOES NOT WORK, you have to modify the size of the files.

**Comment by scottkuhl** [comment]
> I mentioned this problem here, I think the problem is that if you use SVG images, you have to resize the images to 24x24 px. The icons remain adjusted.

I tried changing the file size to 24x24 and that does not fix this issue.  The icons do appear at a different size but the layout and styling issues remain.

**Comment by davidortinau** [comment]
https://github.com/dotnet/maui/issues/8477

Workaround is to use a template. https://github.com/davidortinau/ControlGallery/blob/main/src/ControlGallery/App.xaml#L44-L60

**Comment by PureWeen** [comment]
@scottkuhl I tested #8477 with the latest MAUI nuget and this looks fixed. When the next release of MAUI lands (7.0.59) can you test again and let me know if it works alright?

**Comment by samhouts** [comment]
Duplicate of #8477
