### ISSUE TITLE
Entry tint color not works in iOS and MAC

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#13416]
### Description

Changed tint color in entry as like below code snippet by using handler in iOS and mac to change the text selection highlight color.But it does not work in mac and iOS platform.

private void Button_Clicked(object sender, EventArgs e)
    {
#if MACCATALYST || IOS
        if (entry.Handler.PlatformView is Microsoft.Maui.Platform.MauiTextField macEntry)
        {
            macEntry.TintColor = UIKit.UIColor.Green;
        }
#endif

### Steps to Reproduce

1.Run the sample from below link
https://github.com/jeya-kasipandi/Entry-selection-issue
2.Click button to change the entry selection color
3.Type the text and select the text
4.Selection color not changed to green color it show the default  color  in mac and iOS

### Link to public reproduction project repository

https://github.com/jeya-kasipandi/Entry-selection-issue

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.2,MAC

**Comment by jeya-kasipandi** [comment]
Can you share any workaround or solution to resolve this issue?

**Comment by jfversluis** [comment]
It seems that `entry.Handler` is null at this point.

Change your code to be like this, and it works: 

```csharp
#if MACCATALYST || IOS
		Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("TintColor", (handler, entry) =>
		{
			handler.PlatformView.TintColor = UIKit.UIColor.Green;
		});
#endif
```

Additionally, if you don't want to make the `TintColor` green for _all_ entries, you can create an inheritance of `Entry` and check for that in here as well. More information can be found in our documentation: https://learn.microsoft.com/dotnet/maui/user-interface/handlers/customize?view=net-maui-7.0

**Comment by jeya-kasipandi** [comment]
Hi @jfversluis 

As per your suggestion, I have set like below code snippet it works in iOS but it does not work in mac
C#:
void entry_HandlerChanged(System.Object sender, System.EventArgs e)   
 {        
 Entry entry = sender as Entry;
 #if MACCATALYST || IOS       
  (entry.Handler.PlatformView as UITextField).TintColor=UIColor.Green;
 #endif   
   }
   
   XAML
   <entry:CustomEntry HandlerChanged="entry_HandlerChanged" Text="Enter Text"      WidthRequest="250"/>
   
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/92785406/219685480-965f7948-80b8-4264-9689-87974d521f68.png)

<img width="963" alt="MicrosoftTeams-image (7)" src="https://user-images.githubusercontent.com/92785406/219685528-19db4250-ecb9-4526-bc72-53367da3053f.png">

**Comment by jfversluis** [comment]
Seems like Apple just [didn't implement this](https://stackoverflow.com/questions/60537039/change-prompt-color-for-uitextfield-or-uitextview-on-mac-catalyst) functionality for Mac Catalyst. You can do this:

```csharp
#if MACCATALYST || IOS
		Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("TintColor", (handler, entry) =>
		{
#if IOS
			handler.PlatformView.TintColor = UIKit.UIColor.Green;
#elif MACCATALYST
			var textInputTraits = handler.PlatformView.ValueForKey((NSString)"textInputTraits");
			textInputTraits.SetValueForKey(UIColor.Red, (NSString)"insertionPointColor");
#endif

		});
#endif
```
But that will only color the cursor. I haven't found a way to also color the selection color, maybe it's just not possible. This is not a bug with .NET MAUI, this is just something that is not working/unclear how to do it in the Apple APIs.
