### ISSUE TITLE
Entry ClearButton not taking color of text/hard to see

### ISSUE THREAD

**Issue by shadowfoxish** [dotnet/maui#13432]
### Description

![image](https://user-images.githubusercontent.com/12143535/219802464-0771db75-0db2-4841-8042-7d20a539990e.png)

The clear button isn't taking a color cue from the text color. 

I found some notes about this in the Xamarin.Forms github, but I'm not sure if that's actively used for anything or just an archive.

https://github.com/xamarin/Xamarin.Forms/pull/12391
https://github.com/xamarin/Xamarin.Forms/pull/14766

### Steps to Reproduce

Make an entry with a black or near-black background color and light text color, the 'x' for the clear button is not readily visible.

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 9.0, API 28

**Comment by jsuarezruiz** [comment]
Regression from Xamarin.Forms.
