### ISSUE TITLE
Cannot start the application without starting it in debugging.

### ISSUE THREAD

**Issue by ToaRuGakusei** [dotnet/maui#13445]
### Description

The app does not work properly unless I launch it from debug from VisualStudio.
If I start it on my phone or PC after building it from release or from debug, it shows the logo and crashes a second later.
This problem happened suddenly.
The logs are not displayed, so the details of the error are not clear.

https://github.com/ToaRuGakusei/TGReaderGX
This is my public repository.
You can actually download and run it.

### Steps to Reproduce

1. Build in release mode.
2. Open the installed application.
3. The logo will appear and the app will crash after 1 second.
For some reason, when I start it from a PC in debug mode, it works fine, but when I exit debug and open it directly from my phone, it will not start.

### Link to public reproduction project repository

https://github.com/ToaRuGakusei/TGReaderGX

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS16.2,Windows11,Android9,11,13

**Comment by Martinedo** [comment]
how did you resolve it?
