### ISSUE TITLE
Visual Studio for Mac does not support setting TargetFramework settings for iOS/Mac Binding Libraries

### ISSUE THREAD

**Issue by Tazzi3** [dotnet/maui#13450]
### Description

When using MAC Visual Studio and creating a new iOS Binding Library, it does not provide a choice for the .Net core to use.
It automatically targets .net7 when looking at the project settings. Attempting to select .net6 from the project settings and saving does not work either, when opening the project settings again, it shows .net7 as targetted.

I am needing to use .net6 since the MAUI app that the binding library will be used on is in .net6 which also uses other libraries only built in .net6.

### Steps to Reproduce

1. Create a new iOS Binding Library
2. Opening project settings, change to .NET6, save project
3. Open project settings again (it will still be on .Net7

### Link to public reproduction project repository

https://github.com/Tazzi3/Maui-iosbinding

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

any iOS Binding Library project

### Did you find any workaround?

No workaround found.

> VS bug [#1750601](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1750601)

**Comment by drasticactions** [comment]
You can use net6.0 bindings on net7.0+. It's only targeted bindings going in reverse (net7.0 to net6.0) that won't work. So if you upgrade your MAUI App to net7.0, those net6.0 bindings should still work and if they don't then there's an issue.

As for your issue, I can reproduce this, but I believe this is a bug in VSMac, it has nothing to do with MAUI nor the dotnet SDK. If you edit the `TargetFramework` in your csproj to `net6.0-ios` it will build fine. Those IDE GUI settings don't seem to do anything, which is an issue. But you can edit the csproj directly and it should work. You can verify that too by building via CLI. 

I would file this to [vsfeedback](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by Tazzi3** [comment]
@drasticactions Manually changing it and then reloading the project did solve the issue, thankyou for that.
I will open this using the feedback tool also.
