### ISSUE TITLE
[Debug]: The framework should break to warn user more efficient 

### ISSUE THREAD

**Issue by Strypper** [dotnet/maui#13460]
### Description

I was trying to display a popup using page that enable Shell.PresentationMode="Modal"
[Debug]: Everything display and work fine
[Release]: The page refuse to display when I try to navigate to it, at first I thought there's something wrong with my navigation of other factor like the toolkit statecontainer, but when remove the contentview out of page everything display like normal. 

Updated!!: 
I found out what was happening this is the code that cause the problem 
```xml
<ImageButton
    BackgroundColor="Transparent"
    BorderColor="{x:StaticResource Primary}"
    Source="{x:StaticResource CameraIcon}" />
```

Detail: `Source="{x:StaticResource CameraIcon}" ` the source unable to find the icon in the app but debug allow the app to run normal (The image is not showing up) but this put my guard down didn't realize that something cause my app to break in release mode. And I couldn't find anything on the log output windows

### Steps to Reproduce

1. Create an image link to an imagesource through `x:StaticResource`
2. Test app in both Debug and Release mode

### Link to public reproduction project repository

https://github.com/Strypper/mauisland

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Android, Windows

### Affected platform versions

Windows 11 Android 11

### Did you find any workaround?

No

### Relevant log output

```shell
None
```

**Comment by PureWeen** [comment]
@Strypper Just some clarification on your issue here. 

Are you indicating that 
```XAML
<ImageButton
    BackgroundColor="Transparent"
    BorderColor="{x:StaticResource Primary}"
    Source="{x:StaticResource CameraIcon}" />
```

The ImageButton here works fine and renders when run in debug mode but does not in release mode? 
Or does it throw but not crash in debug mode?

**Comment by Strypper** [comment]
> @Strypper Just some clarification on your issue here. 
> 
> 
> 
> Are you indicating that 
> 
> ```XAML
> 
> <ImageButton
> 
>     BackgroundColor="Transparent"
> 
>     BorderColor="{x:StaticResource Primary}"
> 
>     Source="{x:StaticResource CameraIcon}" />
> 
> ```
> 
> 
> 
> The ImageButton here works fine and renders when run in debug mode but does not in release mode? 
> 
> Or does it throw but not crash in debug mode?

On debug mode I don't see the button but the application keep running without crash, when in release mode it will crash without logging out anything.

**Comment by rachelkang** [comment]
Hi, @Strypper - could you try adding this to your project?
`<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>`

**Comment by Strypper** [comment]
> Hi, @Strypper - could you try adding this to your project and let us know if that helps?
> 
> `<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>`

I will try that as soon as possible

**Comment by Strypper** [comment]
> Hi, @Strypper - could you try adding this to your project and let us know if that helps? `<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>`

WOW!!! Thanks Rachel it does break when in debug, this is what I need for my team to be aware of 
Many cases things work in debug but they don't realize that will break in release so your solution is PERFECT
