### ISSUE TITLE
Add GoogleServicesJson Build Action 

### ISSUE THREAD

**Issue by MahmudX** [dotnet/maui#1346]
## Summary
If we add google-services.json under the android project we should be able to mark it as the GoogleServicesJson file or have any other alternative way.

## API Changes

- Xamarin.GooglePlayServices (AFAIK)

## Intended Use Case
To publish Android apps, `google-services.json` file must be added.

**Comment by gianox** [comment]
Relates to [Bug] Java.Interop version issue in Android #3389 ?

**Comment by Redth** [comment]
Is this suggesting that you can't apply the build action with the file in a Multitargeted/Single Project?  The build action comes from https://github.com/xamarin/GooglePlayServicesComponents/blob/d72add8573e5b63dda71ac6b31d3dbdea8b36d67/source/com.google.android.gms/play-services-basement/merge.targets#L18

//CC @moljac @jpobst @jonpryor

**Comment by AswinPG** [comment]
Is there any workaround to this ?

**Comment by mattleibow** [comment]
This issue was moved to xamarin/XamarinComponents#1421
