### ISSUE TITLE
iOS Binding library crash DYLD 4 Symbol missing

### ISSUE THREAD

**Issue by hetcmnten** [dotnet/maui#13464]
I'm migrating an app from Xamarin.Form to .NET MAUI. When create a new DLL with .framework file from .NET binding project. I'm able to reference and use it in my code normally. But after deploy to an iPhone, it got crash at launch with some log like below.
I searched for several similar issue but none fix my problem
I'm binding Gigya Swift SDK - which using FBAEMKit as dependency

`Termination Reason: DYLD 4 Symbol missing
Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
Referenced from: <DC3CEA75-38E5-305E-B5B4-423E31031846> /Volumes/VOLUME/*/MyBindingApp.app/Frameworks/MyBindingApp.framework/MyBindingApp
Expected in:     <1667FCCD-D108-3A09-941F-1C7D1A499700> /Volumes/VOLUME/*/MyApp.app/Frameworks/FBAEMKit.framework/FBAEMKit
(terminated at launch; ignore backtrace)`

**Comment by rachelkang** [comment]
@SotoiGhost do you have any ideas? Looks like they're using a Facebook dependency
