### ISSUE TITLE
ObjCRuntime.RuntimeException has been thrown

### ISSUE THREAD

**Issue by rohanmpalan** [dotnet/maui#13476]
Failed to marshal the Objective-C object 0x60000297c000 (type: NSBundle). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Foundation.You_Should_Not_Call_base_In_This_Method' does not have a constructor that takes one NativeHandle argument).

**Comment by ramonB1996** [comment]
Duplicate of #13748

**Comment by jsuarezruiz** [comment]
Let's focus on https://github.com/dotnet/maui/issues/13478 Close this duplicate.
