### ISSUE TITLE
[Enhancement] Serious Android and iOS Binding Generator

### ISSUE THREAD

**Issue by MhAllan** [dotnet/maui#1347]
We use Xamarin and will use MAUI because we like C# and .Net . But most mobile vendors don't create libraries for Xamarin/MAUI (Including your colleagues at Azure) 

<img src="https://user-images.githubusercontent.com/13087546/122431133-8880e900-cfd7-11eb-8942-0afed45fd1dc.png" width="400" height="150">

And so, to use Xamarin/MAUI we need to always generate binding libraries which is very difficult process even for those know Java and Swift. You need to list all dependencies and bind them all, and even you live enough to do so there will be tons of missing classes, methods, members ... etc.

We need serious binding tool if we want MAUI to be adopted seriously

**Comment by yurkinh** [comment]
There were some attempts to automate this:

https://marketplace.visualstudio.com/items?itemName=EgorBogatov.XamarinGradleBindings
https://github.com/EgorBo/Xamarin.GradleBindings

But this project is not maintained anymore.

**Comment by MhAllan** [comment]
Thanks a lot @yurkinh , I will try that, but we still hope VS can do without extensions because as you said such tools don't keep updating.

**Comment by shaggygi** [comment]
I read at one point that Java interop was coming to .NET 6, but was pushed back.  I think Objective-C interop is coming in .NET 6 now, but have not heard specifics if Java will be in .NET 7.  I hope so as I'm really needing this support, as well.

**Comment by MhAllan** [comment]
any updates on this? estimated time?

**Comment by realZhangChi** [comment]
👀

**Comment by jfversluis** [comment]
I'm going to close this issue for now as it's very broad, it describes "mobile vendors" that are for the most part out of our control. Of course we would want everyone to start creating .NET MAUI libraries and controls, but that is up to them. And to be fair, I think they're waiting up until about this point in time where the APIs are all determined and chances on big changes are low. We are working with big and small library maintainers to transition them to .NET MAUI and hopefully many (new) will follow. Additionally, there isn't a clear point at which this issue will be resolved. This is on our radar for sure.

Thanks!

**Comment by jfversluis** [comment]
For this specific library you are referencing, there is a Azure Feedback ticket open here: https://feedback.azure.com/d365community/idea/4c3c83f6-8948-ec11-a819-0022484bf651

Make sure you upvote it so that team can prioritize accordingly.

**Comment by shaggygi** [comment]
@jfversluis I might be interpreting the issue wrong, but I was thinking it was more about allowing more Java-type libraries to be used within .NET projects.  For example, there is this old doc https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-a-jar.

In addition, I recall there being an announcement about Java interop coming.  I believe it was in a .NET blog by @richlander.

Any updates are appreciated.

**Comment by jfversluis** [comment]
I don't think that process should change that much tbh since it's very much on the platform side. If such things are coming that would be coming from the .NET for iOS and .NET for Android teams.

**Comment by MhAllan** [comment]
@jfversluis  Please re-open this issue as you completely missed what I am asking form. The issue is about generating binding libraries. The current tools are useless, we need to improve these tools so we can generate useful bindings. have you tried to generate binding for any java or ios library to use it in Xamarin? if not, try and see what I mean. https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/

**Comment by jfversluis** [comment]
I'm sorry if you feel I wasn't understanding you, I think I do, but as mentioned: the binding tools for libraries are owned by the [.NET for iOS](https://github.com/xamarin/xamarin-macios) and [.NET for Android](https://github.com/xamarin/xamarin-android) teams. They are the ones binding libraries and .NET MAUI (as did Xamarin.Forms) is building on top of that, we don't create the tools to do that.

**Comment by MhAllan** [comment]
@jfversluis thanks a lot
