### ISSUE TITLE
When I Capture a photo the second time the camera does not open

### ISSUE THREAD

**Issue by mreugenevanrooyen** [dotnet/maui#13477]
### Description

When I open my app and try to take a photo on my iPhone, the app prompts me to allow it to access the camera, which I grant. I'm able to take one photo successfully, but when I try to take a second photo, the camera app briefly opens and then immediately closes again. This problem is not happening on my Android device.

https://user-images.githubusercontent.com/26383481/220267066-427161b1-bb30-4e74-bea2-78f664435199.mp4

### Steps to Reproduce

            if (MediaPicker.Default.IsCaptureSupported)
            {
                FileResult photo = await MediaPicker.Default.CapturePhotoAsync(new MediaPickerOptions
                {
                    Title = "Please enter a name"
                });

                if (photo != null)
                {
                    IsBusy = true;
                    Stream sourceStream = await photo.OpenReadAsync();
                    image = new byte[sourceStream.Length];
                    await sourceStream.ReadAsync(image, 0, image.Length);
                    return image;
                }
                else
                {
                    return null;
                }
            }

When I try to capture a photo or video using my app, I'm able to receive the FileResult object from the first capture. However, on the second capture attempt, the FileResult object is returning null, even though the capture seems to work normally.

### Link to public reproduction project repository

nothing yet

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

IOS 10 - IOS14

### Did you find any workaround?

I have not

**Comment by mr5z** [comment]
Shouldn't you dispose the stream object here before the function returns

**Comment by mreugenevanrooyen** [comment]
> Shouldn't you dispose the stream object here before the function returns

I have added  using Stream sourceStream = await photo.OpenReadAsync();

same result

**Comment by mreugenevanrooyen** [comment]
I have created a new repro - https://github.com/mreugenevanrooyen/CapturePhotoTest1

**Comment by mreugenevanrooyen** [comment]
Good day, I have tested this with the latest --
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.6.0 Preview 1.0

https://user-images.githubusercontent.com/26383481/221207572-ae90c92c-0c0c-44af-8d09-f2e2546874ca.mp4

**Comment by grimmi** [comment]
Can confirm, we see the same problem on one of our devices (but not the other one) running iOS 15.3.

**Comment by mreugenevanrooyen** [comment]
Can you please explain why this issue has been closed?
