### ISSUE TITLE
ObjCRuntime.RuntimeException has been thrown

### ISSUE THREAD

**Issue by rohanmpalan** [dotnet/maui#13478]
### Description

Failed to marshal the Objective-C object 0x60000297c000 (type: NSBundle). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Foundation.You_Should_Not_Call_base_In_This_Method' does not have a constructor that takes one NativeHandle argument).

### Steps to Reproduce

update the Visual audio for Mac with Version 17.4.5 (build 8). Existing apps with .Net MAUI 7 have this issue with iOS

### Link to public reproduction project repository

NA

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by rohanmpalan** [comment]
<img width="1116" alt="Screenshot 2023-02-21 at 6 02 45 PM" src="https://user-images.githubusercontent.com/13179137/220348344-d5f06ee4-9420-4e53-ba9b-7a40ff80cb2c.png">

**Comment by mr5z** [comment]
Were you calling some `base()` in any of your derived classes from iOS framework?

**Comment by rohanmpalan** [comment]
No, It is just the scaffolded code. It was working fine previously. The problem started coming when I updated VS for Mac

**Comment by rohanmpalan** [comment]
I was able to resolve this issue by clearing Bin And Obj folders
