### ISSUE TITLE
SearchHandler doesn’t show results on iOS

### ISSUE THREAD

**Issue by sasharp** [dotnet/maui#13470]
### Description

SearchHandler shows always white space with binding and crashes after setting ItemsSource manually. 

### Steps to Reproduce

1. Set binding for ItemsSource
2. Update binding property

or

Set a list to ItemsSource

### Link to public reproduction project repository

—-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPadOS 16.2

### Relevant log output

```shell
"Object reference not set to an instance of an object."

" at Microsoft.Maui.Controls.ViewExtensions.GetParentsPath(Element self)+MoveNext()\n at Microsoft.Maui.Controls.ViewExtensions.FindMauiContext(Element element, Boolean fallbackToAppMauiContext)\n at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view, Shell shell, Object context)\n at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view)\n at Microsoft.Maui.Controls.Platform.Compatibility.ShellSearchResultsRenderer.GetCell(UITableView tableView, NSIndexPath indexPath)\n at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)\n at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)\n at {Project}.Program.Main(String[] args) in {project path}\\Platforms\\iOS\\Program.cs:line 13"
```

**Comment by sasharp** [comment]
[SearchHandlerIOSBug.zip](https://github.com/dotnet/maui/files/10805813/SearchHandlerIOSBug.zip)
Here is sample. Simply type „a“ in the search field.

**Comment by kcoop** [comment]
This looks like the same issue as [[https://github.com/dotnet/maui/issues/11823](url)](https://github.com/dotnet/maui/issues/11823), which is resolved for version 8.

I can't find any workarounds. Any chance of a back port to 7?

**Comment by jsuarezruiz** [comment]
This issue have been fixed by https://github.com/dotnet/maui/pull/11926
