### ISSUE TITLE
Android Button (maybe other controls) problem

### ISSUE THREAD

**Issue by tengulak** [dotnet/maui#13483]
### Description

Both problems with Android
1. When set button backgroud from LinearGradietBrush to SolidColorBrush, button rendered as a square without other setting, lile Border, Border radius,etc.
2. When button have ImageSource and ContenLayout set to Top,0  first rendered screen move text mostly to left side. Other postions Left,Right,Bottom seems OK.

### Steps to Reproduce

Sample project added.

### Link to public reproduction project repository

https://github.com/tengulak/bugs.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11,12

### Did you find any workaround?

For 1.  LinearGradietBrush can be changed only LinearGradietBrush
For 2. No workaround

**Comment by tengulak** [comment]
Hi @msfboot, i added a public project for that bugs.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Android platform with sample project.
https://github.com/tengulak/bugs.git
![demo2](https://github.com/dotnet/maui/assets/82450723/f9370aca-6730-4848-898d-9db7d73c7cf5)
