### ISSUE TITLE
Wrong height for Label placed inside a Scrollview

### ISSUE THREAD

**Issue by cat0363** [dotnet/maui#13498]
### Discussed in https://github.com/dotnet/maui/discussions/13494

<div type='discussions-op-text'>

<sup>Originally posted by **cat0363** February 22, 2023</sup>
Xamarin.Forms and .NET MAUI have different heights when placing a Label inside a ScrollView.
Below is the XAML for confirmation. (This is the result of running on Android.)

    <Grid RowDefinitions="44,*" RowSpacing="0">
      <ScrollView Grid.Row="0" Orientation="Horizontal" BackgroundColor="Red">
        <Label Text="This is test." FontSize="18" HorizontalOptions="Start" VerticalOptions="Center" BackgroundColor="Yellow" />
      </ScrollView>
      <Grid Grid.Row="1" BackgroundColor="Blue" />
    </Grid>

The execution result of Xamarin.Forms is as follows.
![image](https://user-images.githubusercontent.com/125236133/220499364-1890ae45-6207-4126-9683-fddc87dd70c3.png)

The execution result of .NET MAUI is as follows.
![image](https://user-images.githubusercontent.com/125236133/220499416-1c998220-6d04-4d24-93a4-f2fcc9e34b42.png)

How can I get the same execution result as Xamarin.Forms?</div>

**Comment by rachelkang** [comment]
Hi, @cat0363 - thanks for submitting this issue. Could you let us know what version of .NET you're on (have you tried the latest version yet? if not, could you give it a go?), and what platforms/versions you're seeing this issue on?

**Comment by cat0363** [comment]
@rachelkang, thank you for your reply.

I used .NET 7.0.2 The version of .NET MAUI is 6.0.552.
The platform is Android and the version is 11.0 (API 30).
I will try it later with .NET 7.0.3.

**Comment by vhugogarcia** [comment]
Hello @cat0363 ,

I solved this issue by just adding a fixed height to the label: `HeightRequest="30"`. I don't think this is a .NET MAUI bug, per what I learned last week from the Xamarin.Forms migration to .NET MAUI Layouts, in .NET MAUI you need to specify values for layouts, in the past Xamarin.Forms was trying to calculate everything in real-time which was one of the things that make it not good in performance. 

Please review this recent documentation the MS team shared with us 7 days ago. I found it really helpful and I personally learned from it. [https://learn.microsoft.com/en-us/dotnet/maui/migration/layouts?view=net-maui-7.0](https://learn.microsoft.com/en-us/dotnet/maui/migration/layouts?view=net-maui-7.0)

**Note**: I tested it on .NET MAUI 7.0.59
cc: @rachelkang 

![Screenshot_1677193603](https://user-images.githubusercontent.com/1047398/221051470-dba42306-9f1b-4762-b628-3e4cd309e98b.png)

**Comment by cat0363** [comment]
Hi, @rachelkang 
I installed the latest Visual Studio 2021 Preview (17.6) and .NET 7 (7.0.3) to check if this issue is resolved.
Installing the latest Visual Studio 2021 Preview and .NET 7 did not resolve this issue. The results were the same.
If you need any additional information or anything else I should try, please let me know.

Hi, @vhugogarcia
Thank you for suggesting a solution to this issue. 
When I first discovered this issue, I temporarily worked around it by specifying the Label's HeightRequest 
as you suggested. For me, it was a workaround, not a solution, as the label's height changes depending 
on the font you specify for it. I understand that explicitly specifying the size of the control is less computational 
and better for performance. I would like it to work in .NET MAUI the same way it does in Xamarin.Forms, 
as it's not ideal to explicitly specify a HeightRequest for each font you specify for a control.
Thank you for your help.

**Comment by cat0363** [comment]
Hi, @rachelkang 
Earlier, when I was replying, I accidentally closed it.
I am sorry. Open again.

**Comment by cat0363** [comment]
A msftbot changed the status of this issue to Closed. Is this change mechanical?
Or is it due to the solution by [#13554](https://github.com/dotnet/maui/pull/13554)?
I would like to know the reason why it became Closed.

**Comment by cat0363** [comment]
Hi, @hartez 
Thank you for reopening and replying.
I hope that the solution([#13554](https://github.com/dotnet/maui/pull/13554)) you provided will solve this Issue.

**Comment by cat0363** [comment]
Hi, @hartez 
This issue has been changed to closed status again by msftbot. Since this issue 
has not been resolved, could you please open it again? Could you please let me 
know if there is anything I should do to resolve this issue?

**Comment by hartez** [comment]
@cat0363 Sorry, I have no idea why the bot closed it this time. No action needed on your part, I'll re-open it.

**Comment by cat0363** [comment]
Thank you for your work leading up to the closure of this issue. \\(^_^)/
