### ISSUE TITLE
Reopen issue number 7751

### ISSUE THREAD

**Issue by asafgo** [dotnet/maui#13491]
### Description

I am asking to reopen this issue https://github.com/dotnet/maui/issues/7751 as it is not solved yet on windows with RTL regions.

My workloads
![maui](https://user-images.githubusercontent.com/12719112/220437743-776498fc-dc0a-4ace-a4f0-3f6c9d667c36.png)

my windows 11 region
![region](https://user-images.githubusercontent.com/12719112/220437772-c94009aa-c283-46ec-9ac2-0a893ab43f40.png)

### Steps to Reproduce

Just create a File -> new -> project... .NET MAUI App and run it as Windows Machine

### Link to public reproduction project repository

https://github.com/asafgo/MauiWindows

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 22H2

### Did you find any workaround?

No

**Comment by Eilon** [comment]
I reopened it.
