### ISSUE TITLE
Can't get started

### ISSUE THREAD

**Issue by aloneguid** [dotnet/maui#13500]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

MAUI is not shown when trying to create a new project:
![image](https://user-images.githubusercontent.com/3155189/220595067-081e0cb1-4f2c-486b-bcca-f64d3c64dea8.png)

Workload is installed:

![image](https://user-images.githubusercontent.com/3155189/220595214-f2f4dc7a-71f7-46a7-b8b8-9caba4486312.png)

> VS bug [#1756008](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1756008)

**Comment by jfversluis** [comment]
Hey @aloneguid! Thanks for trying out .NET MAUI, sorry that you ran into this.

Typically the templates should be installed as part of that checkbox in Visual Studio. Was this a new installation? Or did you modify your Visual Studio to add .NET MAUI to it?

It isn't really clear from your screenshot if you actually used the searchbox as well to really be sure? In the dropdown I see Mobile as an option, .NET MAUI should be under there.

If it really isn't anywhere to be found you can open a command prompt and type `dotnet new -i Microsoft.Maui.Templates` that should install the templates and also make them show up in Visual Studio.

Does that help at all?
