### ISSUE TITLE
Possibility to send basic authentication headers with Browser.Default.OpenAsync()

### ISSUE THREAD

**Issue by RsZoli** [dotnet/maui#13515]
### Description

I would very much like to have the possibility to send basic authentication headers with the Browser.Default.OpenAsync function!

### Public API Changes

```csharp
var headers = new List<Dictionary<string, string>>();
headers.Add(new Dictionary<string, string>
{
 "Authentication", "Basic xxxxxxxxxxxxxxxxxxxxxx"
};
await Browser.Default.OpenAsync(uri, headers);
```

### Intended Use-Case

I'm developing an internally distributed corporate app that is already authenticated to reach internal resources! It would be nice if i could pass the neccessary information to the browser, so ti would not prompt the user to log in again!

**Comment by jfversluis** [comment]
I don't think this is possible on (all) underlaying platforms.
