### ISSUE TITLE
[Android] SwipeItemView size issues

### ISSUE THREAD

**Issue by nicop85** [dotnet/maui#13547]
### Description

In version 7.0.58 you have pushed some changes to fix SwipeItemView size problems (https://github.com/dotnet/maui/pull/10522).

But there is still one problem with this and it is when you programmatically triggers to open the SwipeView.

Opened with swipe gesture:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/2288412/221271281-c2006af5-79d1-4ae9-9ff6-e301dc121c25.png">

Opened programmatically:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/2288412/221271333-a4781844-4db4-45b3-b098-9253cfb84200.png">

It leaves some blank space between the content and the Swipe items.

### Steps to Reproduce

1. Create a new project
2. Add a SwipeView to the content of the page
3. Add a Button to trigger the swipe programmatically
4. You will see the difference between both behaviours

Expected outcome: both with a gesture or programmatically, the swipe should behave the same way and no blank space should be displayed
Actual outcome: When opening it programmatically, there is a blank space between SwipeView content and SwipeView items

### Link to public reproduction project repository

https://github.com/nicop85/SwipeViewSizeProblems

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

No

**Comment by rachelkang** [comment]
Potentially related https://github.com/dotnet/maui/issues/4121
