### ISSUE TITLE
MAUI Blazor Windows: InputText not leaveable after mouse click

### ISSUE THREAD

**Issue by reinhardlackner** [dotnet/maui#13541]
### Description

When you edit the first InputText and click in the second InputText (you are writing in the first field and clicking in the second field at the same time), the app freezes and you can not leave the first InputText.
![image](https://user-images.githubusercontent.com/15954854/221130730-45da374b-063a-4f52-8408-ce073bf68d77.png)

### Steps to Reproduce

- Create new MAUI Blazor app (.net 7)
- Edit Index.razor and add 2 bound InputText-fields:
![image](https://user-images.githubusercontent.com/15954854/221132153-41d6cec8-e935-41db-af1a-5962fca6e6db.png)

- Write something in InputText 1 (First name) and while writing click (or double click) in InputText 2 Last name:
![image](https://user-images.githubusercontent.com/15954854/221132588-02601a5b-213e-4d12-9a99-0f304068b745.png)
If you are able to click in InputText 2, write something and during writing click back in InputText 1. If you repeat these steps, you are able to reproduce it. Use different characters for writing in the InputText.

- After that, it is not possible to leave the current InputText with a mouse click.
It is possible to switch to InputText 2 with "TAB" - but you can not leave InputText 1 it with a mouse click. You can see that at the end of the attached video. But after InputText 2 was entered with "TAB", you can not leave it any more.
You are not able to click on any other main menue item (e.g. Counter) -> It is no longer possible to use the app and you must restart it.

https://user-images.githubusercontent.com/15954854/221135322-cc299443-de4d-4954-8d9c-0f2f27ba0e11.mp4

### Link to public reproduction project repository

https://github.com/reinhardlackner/SampleMauiInputTextIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 and Windows 11 (Target SDK 10.0.19041.0)

**Comment by Eilon** [comment]
Hi, this is a known issue with WebView2 that is tracked here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003

Please add your up-vote to that issue to help increase visibility. Thanks!
