### ISSUE TITLE
Support for [JSImport] in MAUI Blazor App

### ISSUE THREAD

**Issue by orosbogdan** [dotnet/maui#13551]
### Description

I would like to use [JSImport] in MAUI Blazor App to improve performance on JS interop calls.

### Public API Changes

```System.Runtime.InteropServices.JavaScript.JSImport```

The attribute above should be supported in .NET MAUI Blazor Apps since it uses Blazor WASM behind the door.

```JSHost.ImportAsync```
Currently I am getting the following error when trying to achieve this "(System.Runtime.InteropServices.JavaScript is not supported on this platform.)"

### Intended Use-Case

In my app I want to be able to transfer array with large number of elements efficiently between the C# layer and the JS layer. My app uses MAUI Blazor App.

**Comment by javiercn** [comment]
@orosbogdan thanks for contacting us.

That attribute and support is specific to the .NET webassembly runtime and not something that Blazor supports (or wil be able to support).

Blazor Maui apps do not use webassembly, the .NET code runs directly on the device.
