### ISSUE TITLE
CollectionView Windows Memory Leak, Android Laggy scrolling

### ISSUE THREAD

**Issue by alfamizar** [dotnet/maui#13557]
### Description

I noticed huge memory leak in my app, but seems this is widely spread issue, as it is easy to reproduce even in Monkey Finder
https://github.com/dotnet-presentations/dotnet-maui-workshop.git 

![image](https://user-images.githubusercontent.com/52598586/221351861-111e6bb7-3b53-4c8f-a371-546f1fb55923.png)

Also, scrolling performance is bad on Samsung Galaxy S20 Ultra (12GB RAM) if Data Tepmplate contains Frame, without wrapping with a Grid. (I mean fixing Memory leak on Windows, ruins scrolling performance (by potentional memory) on Android)

### Steps to Reproduce

1. Run Monkey finder on Windows, in release build, [link](https://github.com/dotnet-presentations/dotnet-maui-workshop.git)
2. Click Get Monkeys and see, how memory usage increases up to infinity

### Link to public reproduction project repository

https://github.com/dotnet-presentations/dotnet-maui-workshop.git

### Version with bug

7.0 (current)

### Last version that worked well

-----

### Affected platforms

Android, Windows

### Affected platform versions

Android 9, 12; Windows 11

### Did you find any workaround?

Workaround for Windows memory leak is simple. Remove Grid, that wraps Frame
![image](https://user-images.githubusercontent.com/52598586/221352073-d83455ac-68bf-47e1-a0b4-95fe1aa093bd.png)

Using this fix for Windows works fine
![image](https://user-images.githubusercontent.com/52598586/221352165-41ac8677-6f3d-40ab-9803-c8cf4e0213d8.png)
But reduces scrolling performance on Android, and may be causing memory leak (I can not check it for sure)

**Comment by rachelkang** [comment]
@jonathanpeppers

**Comment by jonathanpeppers** [comment]
I debugged this app quite a bit today, I believe there are two core problems here:

1. Something XAML Hot Reload causes. Things worked better if I do:

![image](https://user-images.githubusercontent.com/840039/222325505-e6f61659-3ee8-4502-8a54-2fdc40ae5503.png)

I will investigate this further and let the right team know.

2. `VisualElement.Background` subscribes to events, which is a problem if the `Background` comes from `App.Resources`:

https://github.com/dotnet/maui/blob/7f3b34f53f629035fedb338d6f474a1cd019a858/src/Controls/src/Core/VisualElement.cs#L252-L265

Can be reproduced in a test:
```csharp
[Theory]
[InlineData(typeof(ImmutableBrush), false)]
[InlineData(typeof(SolidColorBrush), false)]
[InlineData(typeof(LinearGradientBrush), true)]
[InlineData(typeof(RadialGradientBrush), true)]
public async Task BackgroundDoesNotLeak(Type type, bool defaultCtor)
{
	var brush = defaultCtor ?
		(Brush)Activator.CreateInstance(type) :
		(Brush)Activator.CreateInstance(type, Colors.CornflowerBlue);

	var reference = new WeakReference(new VisualElement { Background = brush });

	await Task.Yield();
	GC.Collect();
	GC.WaitForPendingFinalizers();

	Assert.False(reference.IsAlive, "VisualElement should not be alive!");
}
```

Only `ImmutableBrush` passes, as it is special cased and returns early.

I'll keep working on this. 👍

**Comment by alfamizar** [comment]
@jonathanpeppers hi. Thanks for digging into it.

Regaridng first problem, I am surprised, as I didn't expect that hot reload could cause issues in Release mode.

**Comment by jonathanpeppers** [comment]
I was testing in Debug mode, so I could do things like our breakpoints in MAUI.

**Comment by alfamizar** [comment]
@jonathanpeppers if you find a workaround, that could fix an issue, before fix will be merged into .NET 7 MAUI, please, let me know.

**Comment by jonathanpeppers** [comment]
@alfamizar in the example above, you could avoid using `{StaticResource}` including a `Style` in a `DataTemplate`? Basically just hardcode values instead.
