### ISSUE TITLE
UI freezing when performing frequent mouse action in different  HTML input element in MAUI app

### ISSUE THREAD

**Issue by Deepak-Ramakrisnan** [dotnet/maui#13573]
### Description

The App freezes when a component dynamically changes focus using a mouse action while utilizing the HTML input tag. This occurs when performing frequent mouse actions on the input elements, causing the app to freeze and prevents further mouse actions from being performed. However, keyboard actions work as expected.

### Steps to Reproduce

1.Run the attached MAUI app
2.Focus the first input tag and type something 
3.now focus the second input element and type something 
4.Now continue with the 2nd and 3rd steps 

**Expected Result**:

The focus of the HTML input tag should change without freezing the UI.

**Actual Result**:

However, the app freezes, and further mouse actions cannot be performed.

### Link to public reproduction project repository

https://github.com/Deepak-Ramakrisnan/MAUIAPP

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

WindowsAPPSdk-1.2.221209

**Comment by drasticactions** [comment]
Possibly related to https://github.com/microsoft/microsoft-ui-xaml/issues/8088. I would be hard pressed to find this to be MAUI specific

**Comment by ndegheselle** [comment]
> Possibly related to [microsoft/microsoft-ui-xaml#8088](https://github.com/microsoft/microsoft-ui-xaml/issues/8088). I would be hard pressed to find this to be MAUI specific

He is using Blazor, I don't think it is related to XAML ? I don't have the issue with the sample though.

**Comment by Ocrosoft** [comment]
I have the same problem..

**Comment by Eilon** [comment]
This is tracked by https://github.com/microsoft/WindowsAppSDK/issues/3266. It looks like they are testing a fix for this, so hopefully that will be released soon. Please use that issue for any questions/comments.
