### ISSUE TITLE
Tabbed pages with mapsui map do not work on Android but do on windows

### ISSUE THREAD

**Issue by raymondjstone** [dotnet/maui#13575]
### Description

Maui/Blazor app, tabbed pages (2), page 1 has the map (mapsui) on it (and also a maui control), page 2 has a maui control only.

Tab1 shows initially and is correct and shows the map along with the various layers I add to it. when switching to tab2 that page then shows correctly.

Switching back to tab1 however the page shows but only the maui controls, the map itself is missing and calling refreshGraphics in the NavigateTo method does not help

running in windows this works fine, running on android device it does not (both emulator and physical machine).

map control is in an absolute layout object within the page

### Steps to Reproduce

Switching between tabbed pages on Android does not return the original content on a tab with a mapsui map added to it but does work on windows.

### Link to public reproduction project repository

not available at the moment

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No

I tried to use the navigatedTo handler to refresh the map and to replace the enitire contents of the page but that does not work

### Relevant log output

```shell
no errors shown, just a blank screen where the map should be (but other maui controls overlayed over it do show)
```

**Comment by Eilon** [comment]
Hi @raymondjstone can you also show screenshots of what you're seeing and point out what it is that you expect?
