### ISSUE TITLE
[Entry] [Android] Cursor makes undesired jumps with masked behaviour

### ISSUE THREAD

**Issue by Asfiroth** [dotnet/maui#13571]
### Description

Using the .NET MAUI Entry control works fine in both android and iOS, but applying behaviours such as MaskedBehvior from .NET MAUI Community Toolkit (or others) ends up un randomic cursor movements on Android, iOS doesn't present this strange behaviour.

### Steps to Reproduce

1. Create a MAUI App.
2. Download package `CommunityToolkit.Maui` and follow instructions to make it work.
3. On Main page put a entry with behaviour:
````
<Entry>
                <Entry.Behaviors>
                    <mtc:MaskedBehavior Mask="XXXX XXXX XXXX XXXX" />
                </Entry.Behaviors>
            </Entry>
````
4. Start writing and see randomic cursor dance.

### Link to public reproduction project repository

https://github.com/Asfiroth/MauiEntryBehaviourIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 and up

### Did you find any workaround?

Yes, modifying the Entry handler for android adding this:

On ConnectHandler:

`PlatformView.TextChanged += PlatformViewOnTextChanged;`

On DisconnectHandler:

`PlatformView.TextChanged -= PlatformViewOnTextChanged;`

This is the event handler for text changed event

```
private void PlatformViewOnTextChanged(object sender, TextChangedEventArgs e)
    {
        if (sender is not AppCompatEditText editText) return;
        
        if (string.IsNullOrWhiteSpace(editText.Text)) return;
        
        var looper = Looper.MyLooper();
        if (looper != null)
        {
            var handler = new Handler(looper);
            handler.Post(() =>
            {
                editText.SetSelection(editText.Text.Length);
            });
        }else
        {
            editText.SetSelection(editText.Text.Length);
        }
    }

```
It's not perfect but does the job, any help to make this better is appreciated.

**Comment by Asfiroth** [comment]
> #12750

Hi @rmarinho would that fix make it to net7-latest version?

**Comment by rmarinho** [comment]
The bar for net7 fixes is high now, but i will suggest as backport and we will discuss on our team meeting.
