### ISSUE TITLE
Setter using DynamicResource is not reapplied when related trigger condition is updated

### ISSUE THREAD

**Issue by dilyantraykov** [dotnet/maui#13585]
### Description

Assume the following style which is applied to a Button element:

```
        <Color x:Key="MyPrimaryColor">Green</Color>
        <Color x:Key="MyReadOnlyColor">Purple</Color>

        <Style TargetType="Button" x:Key="MyDynamicResourceButtonStyle">
            <Setter Property="BackgroundColor" Value="{DynamicResource MyPrimaryColor}" />
            <Style.Triggers>
                <Trigger TargetType="Button" Property="IsEnabled" Value="False" >
                    <Setter Property="BackgroundColor" Value="{DynamicResource MyReadOnlyColor}" />
                </Trigger>
            </Style.Triggers>
        </Style>
 ```
When the button's IsEnabled property is changed to True after initially being False (for example upon a button click), the BackgroundColor property is not updated as expected. The issue is not present when using StaticResource instead.

### Steps to Reproduce

1. Open the project from the referenced reproduction repository. 
2. Click on any of the Start buttons.

Expected: Both Stop buttons have a Green background color.
Actual: Only the top Stop button (using StaticResource) has a Green background. The Button using the DynamicResource keeps its Purple color.

### Link to public reproduction project repository

https://github.com/dilyantraykov/DynamicResourceIssueIsolation

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 33, Windows SDK 10.0.19041.0, iOS, MacCatalyst

### Did you find any workaround?

One workaround is to use a StaticResource instead of a DynamicResource.
Another way around this is to explicitly define separate triggers for all the possible values for the styled property which may not be sustainable in most cases.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on windows, android and iOS platform with sample project. [DynamicResourceIssueIsolation](https://github.com/dilyantraykov/DynamicResourceIssueIsolation)

**Comment by StephaneDelcroix** [comment]
We did some major rewrites of Styles and Setters in main and net8. I no longer can reproduce your problem on top of the new code. I've added a unitest fo this particular issue. 

Please reopen this issue, or modify the unit test if your issue isn't resolved
