### ISSUE TITLE
Maui Blazor input dropdown list not accepting selected value

### ISSUE THREAD

**Issue by bartbrock** [dotnet/maui#13586]
I am using a searchable dropdown list to input values into a .net maui blazor android app. The dropdown works but when the selection is made it is not entered into the input field. The issue seems to be sporadic sometimes working when the page is first loaded. The code works great with the Windows Machine target. I am not using an editform model with this page. Built with Visual Studio 22 Version 17.4.4 and.net 6.0. Running on Android 10 & 11.
If only a single input field is used on the page it works fine but when the second one is added it stops working.  I added separate datalist objects thinking this may be the issue but results are the same.

I've created a simplified demo of the issue and posted to GitHub, https://github.com/bartbrock/MauiDropdownTest.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 6.0. Can repro on android platform with sample project.
[MauiDropdownTest-master.zip](https://github.com/dotnet/maui/files/12311005/MauiDropdownTest-master.zip)
![1](https://github.com/dotnet/maui/assets/77434865/dd9d3493-33f3-46bd-8e77-ce74d721cc66)

**Comment by Eilon** [comment]
This appears to be an issue with the Android WebView because it affects a plain WebView and not just BlazorWebView.

I tried this MainPage.xaml:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiDropdownTest"
             x:Class="MauiDropdownTest.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">

    <WebView>
        <WebView.Source>
            <HtmlWebViewSource>
                <HtmlWebViewSource.Html>
                    <![CDATA[
                <html>
                <body>
 
                      <div>Choose your browser from the list:</div>
                      <input list="browsers">
                      <datalist id="browsers">
                        <option value="Edge">
                        <option value="Firefox">
                        <option value="Chrome">
                        <option value="Opera">
                        <option value="Safari">
                      </datalist>
  
                     <div>Choose your color from the list:</div>
                      <input list="colors">
                      <datalist id="colors">
                        <option value="Orange">
                        <option value="Purple">
                        <option value="Red">
                        <option value="Blue">
                        <option value="Indigo">
                      </datalist>
                      <input type="submit">

                    </body>
                </html>
                ]]>
                </HtmlWebViewSource.Html>
            </HtmlWebViewSource>
        </WebView.Source>
    </WebView>
</ContentPage>
```

And whichever dropdown you use first will work fine. And then the second one behaves as though there is no dropdown.

Oddly, Chrome Web Browser works just fine with the exact same HTML.

**Comment by Eilon** [comment]
I even updated the Android System WebView from 113.0.5672.136 to 120.0.6099.43 and it's still not working.

Might need to make a Java repro and report to Chromium.

**Comment by Eilon** [comment]
Java repro here: https://github.com/Eilon/AndroidWebViewDoubleDataList

**Comment by Eilon** [comment]
Bug reported here: https://issuetracker.google.com/issues/316393728

So until that bug is addressed/fixed, I think people will need to use another type of dropdown instead. There are several 3rd party components, or you could use a different type of UI (such as a textbox + select).

I'm closing this bug here because the bug is within Android/Chrome/WebView.
