### ISSUE TITLE
Blazor app webview becomes randomly unresponsive on windows after upgrading to net7 from net6

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/maui#13584]
### Description

I have made a MAUI blazor app in net6 that I upgraded to net7, since then the html buttons become randomly unclickable and I cannot scroll anymore, the debug bar on the top is also unclickable.

EDIT: It's only a problem when I hold down a keyboard key for long inside of an input/textarea, otherwise it works fine

### Steps to Reproduce

I don't know how to repro this, and it is a complex app

### Link to public reproduction project repository

none

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Relevant log output

```shell
no logs in debug
```

**Comment by rmarinho** [comment]
@Eilon any ideas here? Is related with the WebView2 issue?

**Comment by ctigrisht** [comment]
> @Eilon any ideas here? Is related with the WebView2 issue?

Hey, if it has been moved to backlog we would not be able to keep working on this project with current stack... Is there an ETA?

**Comment by Eilon** [comment]
Yes, this is the same issue that @hartez pointed to. This is not specific to .NET 6 / 7, but is an issue with WebView2 on WinUI. Please add your up-votes to those issues.

**Comment by ctigrisht** [comment]
> Yes, this is the same issue that @hartez pointed to. This is not specific to .NET 6 / 7, but is an issue with WebView2 on WinUI. Please add your up-votes to those issues.

well I downgraded to .net 6 to test and the issue is not there, it's specific to .net 7
