### ISSUE TITLE
[Bug] Does not support XAML hot reload on Android?

### ISSUE THREAD

**Issue by expcat** [dotnet/maui#1358]
### Description

When XAML hot reload is enabled, it can‘t run on the Android Emulator. (visual studio 16.11 preview 2.0)

### Steps to Reproduce

1. Create a new .NET MAUI App project
2. Choese Android Emulator
3. Enable XAML hot reload
4. Run debug

### Actual Behavior

The program running in the Android emulator crashes.
Debug output:
```
[HostConnection] HostConnection::get() New Host Connection established 0xe9064dd0, tid 21657
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
[OpenGLRenderer] Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
[EGL_emulation] eglCreateContext: 0xe90653f0: maj 2 min 0 rcv 2
[EGL_emulation] eglMakeCurrent: 0xe90653f0: ver 2 0 (tinfo 0xb1fcb710) (first time)
[Gralloc4] mapper 4.x is not supported
[HostConnection] createUnique: call
[HostConnection] HostConnection::get() New Host Connection established 0xe9065c40, tid 21657
[goldfish-address-space] allocate: Ask for block of size 0x100
[goldfish-address-space] allocate: ioctl allocate returned offset 0x3fde96000 size 0x2000
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
[monodroid] MonodroidRuntime::monodroid_dlopen ("/data/data/com.companyname.MauiApp1/files/.__override__/System.Runtime.Serialization.Formatters.dll.so", 0x1, 0xb2cfa760, 0x0)
[monodroid] MonodroidRuntime::monodroid_dlopen ("/__w/1/s/artifacts/obj/mono/Android.x86.Release/out/lib/mono/aot-cache/x86/System.Runtime.Serialization.Formatters.dll.so", 0x1, 0xb2cfa760, 0x0)
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Runtime.Serialization.Formatters.dll [External]
[nyname.MauiApp] * Assertion at /__w/1/s/src/mono/mono/mini/debugger-engine.c:1088, condition `found_sp' not met
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 21664 (.NET ThreadPool), pid 21620 (nyname.MauiApp1)
```

### Basic Information

? OpenJDK 11.0 Checkup...
  – 11.0.10 (C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot\bin\..)
  – 1.8.0-25 (C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25)

? Visual Studio 16.10.0 Checkup...
  – 16.10.2 - C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
  – 17.0.0-pre.1.0 - C:\Program Files\Microsoft Visual Studio\2022\Preview
  – 16.11.0-pre.2.0 - C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview

? Android SDK Checkup...
  – emulator (30.6.5)
  – build-tools;30.0.2 (30.0.2)
  – platforms;android-30 (3)
  – system-images;android-30;google_apis;x86 (9)
  – platform-tools (31.0.2)

? Android Emulator Checkup...
  – Emulator: pixel_2_r_11_0_-_api_30 found.

? .NET SDK Checkup...
  – 5.0.204 - C:\Program Files\dotnet\sdk\5.0.204
  – 5.0.301 - C:\Program Files\dotnet\sdk\5.0.301
  – 5.0.400-preview.21277.10 - C:\Program Files\dotnet\sdk\5.0.400-preview.21277.10
  – 6.0.100-preview.5.21302.13 - C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13

? .NET SDK - Workload Deduplication Checkup...

? .NET SDK - EnableWorkloadResolver.sentinel Checkup...
  – C:\Program Files (x86)\Microsoft Visual
Studio\2019\Enterprise\MSBuild\Current\Bin\SdkResolvers\Microsoft.DotNet.MSBuildSdkResolver\EnableWorkloadResolver.senti
nel exists.
  – C:\Program Files\Microsoft Visual
Studio\2022\Preview\MSBuild\Current\Bin\SdkResolvers\Microsoft.DotNet.MSBuildSdkResolver\EnableWorkloadResolver.sentinel
exists.
  – C:\Program Files (x86)\Microsoft Visual
Studio\2019\Preview\MSBuild\Current\Bin\SdkResolvers\Microsoft.DotNet.MSBuildSdkResolver\EnableWorkloadResolver.sentinel
exists.

? .NET SDK - Workloads (6.0.100-preview.5.21302.13) Checkup...
  – microsoft-android-sdk-full (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 30.0.100-preview.5.28) installed.
  – microsoft-ios-sdk-full (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 14.5.100-preview.5.894) installed.
  – microsoft-maccatalyst-sdk-full (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 14.5.100-preview.5.894) installed.
  – microsoft-tvos-sdk-full (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 14.5.100-preview.5.894) installed.
  – microsoft-macos-sdk-full (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 11.3.100-preview.5.894) installed.

? .NET SDK - Packs (6.0.100-preview.5.21302.13) Checkup...
  – Microsoft.Maui.Templates (6.0.100-preview.5.794) installed.
  – Microsoft.Android.Sdk (30.0.100-preview.5.28) installed.
  – Microsoft.Android.Sdk.BundleTool (30.0.100-preview.5.28) installed.
  – Microsoft.Android.Ref (30.0.100-preview.5.28) installed.
  – Microsoft.Android.Templates (30.0.100-preview.5.28) installed.
  – Microsoft.iOS.Sdk (14.5.100-preview.5.894) installed.
  – Microsoft.iOS.Windows.Sdk (14.5.100-preview.5.894) installed.
  – Microsoft.iOS.Ref (14.5.100-preview.5.894) installed.
  – Microsoft.iOS.Templates (14.5.100-preview.5.894) installed.
  – Microsoft.MacCatalyst.Sdk (14.5.100-preview.5.894) installed.
  – Microsoft.MacCatalyst.Ref (14.5.100-preview.5.894) installed.
  – Microsoft.MacCatalyst.Templates (14.5.100-preview.5.894) installed.
  – Microsoft.tvOS.Sdk (14.5.100-preview.5.894) installed.
  – Microsoft.tvOS.Ref (14.5.100-preview.5.894) installed.
  – Microsoft.tvOS.Templates (14.5.100-preview.5.894) installed.
  – Microsoft.macOS.Sdk (11.3.100-preview.5.894) installed.
  – Microsoft.macOS.Ref (11.3.100-preview.5.894) installed.
  – Microsoft.macOS.Templates (11.3.100-preview.5.894) installed.

### Screenshots
![hotreload](https://user-images.githubusercontent.com/4289694/122496395-47f88e00-d01e-11eb-85a4-2be53a266602.png)
![hotreload1](https://user-images.githubusercontent.com/4289694/122496488-71b1b500-d01e-11eb-93b6-79898785f12a.png)
![hotreload2](https://user-images.githubusercontent.com/4289694/122496494-74140f00-d01e-11eb-8c67-ea7564f81044.png)

**Comment by gviddy** [comment]
Yeah I have never had this work for me either. But on the Build demo he was showing it working.

**Comment by expcat** [comment]
https://github.com/dotnet/maui/issues/1467#issuecomment-871024582
