### ISSUE TITLE
[Bug] Might be MAUI related. After upgrading to preview 5 workload manifests are not found.

### ISSUE THREAD

**Issue by En3Tho** [dotnet/maui#1360]
I've filed an issue to https://github.com/dotnet/installer/issues/10916 but this might be maui related in general.
After upgrading to preview 5 updating maui-check fails with the same exception.
I found that maui is now a workload? Is there some undocumented magic I need to do after upgrading to preview 5? I don't really wish to waste more time reinstalling stuff, adding-removing projects, copying jsons and getting cryptic exceptions... :/

**Comment by UweReisewitz** [comment]
Did you update maui-check to the latest version (0.5.6)? After that it succeeded on my machine and I was able to create a new MAUI-solution

**Comment by En3Tho** [comment]
-> After upgrading to preview 5 updating maui-check fails with the same exception.

**Comment by UweReisewitz** [comment]
Ok, then my other change may help. I had to copy the WorkloadManifest.json files to the new folders.:
They are now in "C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.<platform>"
Previously the were in "C:\Program Files\dotnet\sdk-manifests\6.0.100\Microsoft.NET.Workload.<Platform>"
After I copied them from the new folder to the old folder maui-check worked and downloaded the new files (and removed the old ones)

**Comment by En3Tho** [comment]
Thank you for help. I thought about this too. I guess it's just the frustration kicked in. That I have to install old preview, copy files, install new one etc instead of "just working".

**Comment by UweReisewitz** [comment]
I had the old files still on my machine, so this was no big deal. But you're  right. Maybe they should try a clean machine once in a while:-)
