### ISSUE TITLE
WinUI does not draw any content [Bug] 

### ISSUE THREAD

**Issue by gviddy** [dotnet/maui#1362]
### Description
Running the default project created in Visual Studio 2019 Preview 2 with Maui Preview 5 shows an empty purple window. If you resize the window then the content is drawn. ie the label, click button, and robot image.

### Steps to Reproduce

1.  Create a brand new MAUI solution in Visual Studio 2019 Preview 2
2.  Build All
3.  Select the WinUI project and run
4. Observe a purple screen
5. Resize the window and then notice the actual window content is now showing. ie hello world text,  button and image

### Expected Behavior
I should not need to resize the window to see the content.

### Actual Behavior
I see a purple window with no content.

This did not happen in VS Preview 1 with Maui Preview 4. 
maui-check says everything is ok.

**Comment by AlexLablaiksSAP** [comment]
I also have the same issue. However, I see an exception thrown during startup:
Unable to load DLL 'Microsoft.Graphics.Canvas.Text.dll' or one of its dependencies: The specified module could not be found.

**Comment by bhavesh4asi** [comment]
Please try to install www.microsoftedgeinsider.com and maybe your issue may resolve.

**Comment by bhavesh4asi** [comment]
> ### Description
> Running the default project created in Visual Studio 2019 Preview 2 with Maui Preview 5 shows an empty purple window. If you resize the window then the content is drawn. ie the label, click button, and robot image.
> 
> ### Steps to Reproduce
> 1. Create a brand new MAUI solution in Visual Studio 2019 Preview 2
> 2. Build All
> 3. Select the WinUI project and run
> 4. Observe a purple screen
> 5. Resize the window and then notice the actual window content is now showing. ie hello world text,  button and image
> 
> ### Expected Behavior
> I should not need to resize the window to see the content.
> 
> ### Actual Behavior
> I see a purple window with no content.
> 
> This did not happen in VS Preview 1 with Maui Preview 4.
> maui-check says everything is ok.

Please try to install www.microsoftedgeinsider.com and maybe your issue may resolve.

**Comment by hartez** [comment]
This is likely fixed by #1374.

**Comment by solvingj** [comment]
When i resized the window the content appeared.

**Comment by derekpapworth** [comment]
I'm getting the same issue with latest builds (as of yesterday 5th July) of VS, maui-check, etc., with getting blank window until resize.

Also noticed that first resize shows all content then when you click the button the "Current count: x" disappears then another resize shows it then click and disappears and only sticks around until after 2 or 3 resizes

**Comment by AliAUZ** [comment]
Install [Microsoft Edge WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) and then rerun the project and it will fix the issue

**Comment by F-Unction** [comment]
> Install [Microsoft Edge WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) and then rerun the project and it will fix the issue

It doesn't work.

**Comment by AliAUZ** [comment]
I had the same issue with EF 6 and when I installed both x86 and x64 on my pc and,created a new app, then the issue gone

**Comment by hartez** [comment]
This is fixed with the latest on main.
