### ISSUE TITLE
Weird code generation error.

### ISSUE THREAD

**Issue by ota-ash** [dotnet/maui#13626]
I just converted a Xamarin Forms Project to Maui. 
The project structure is like this:
All Code, styles, color etc is in a Maui Library and then that library is referenced in multiple app projects. 
The initial conversion went great. Now I'm trying to compile the code and I'm running into this weird error:

```
  Argument 1: cannot convert from '__XamlGeneratedCode__.__Type88B98DF5C996752D' to 'Microsoft.Maui.Controls.Element'
  Argument 1: cannot convert from '__XamlGeneratedCode__.__Type88B98DF5C996752D' to 'Microsoft.Maui.Controls.Element'
  Argument 1: cannot convert from '__XamlGeneratedCode__.__Type88B98DF5C996752D' to 'Microsoft.Maui.Controls.Element'
  Argument 1: cannot convert from '__XamlGeneratedCode__.__Type88B98DF5C996752D' to 'Microsoft.Maui.Controls.Element'
  Argument 1: cannot convert from '__XamlGeneratedCode__.__Type88B98DF5C996752D' to 'Microsoft.Maui.Controls.Element'
  Argument 1: cannot convert from '__XamlGeneratedCode__.__Type88B98DF5C996752D' to 'Microsoft.Maui.Controls.Element'
```

My first thought was something wrong in the Styles.Xaml or Colors.Xaml, but nothing wrong there. 
Also, I'm not sure why the code is compiled 3 times. The target for the libary is set to .net7, iOS and Android. Is it because of that? even though the current configuration is iOS or Android?

Anyways here is little more details:

```
Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/Resources_Styles_Styles.xaml.sg.cs(39,128): error CS1503: Argument 1: cannot convert from '__XamlGeneratedCode__.__Type88B98DF5C996752D' to 'Microsoft.Maui.Controls.Element'
         Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/Resources_Styles_Styles.xaml.sg.cs(40,132): error CS1503: Argument 1: cannot convert from '__XamlGeneratedCode__.__Type88B98DF5C996752D' to 'Microsoft.Maui.Controls.Element'
```

### Reproduction

https://github.com/ryzzyxx/playground

**Comment by Eilon** [comment]
@ota-ash are you able to share more details on how to reproduce this issue? If you can upload your project as a publicly accessible GitHub repo that demonstrates the problem we could get a better idea of what's happening here.

**Comment by ryzzyxx** [comment]
Here it is:
https://github.com/ryzzyxx/playground
There is only one project in the repo. Clone it, restore nuget and build it. 
I'm pretty sure the issue is somewhere in the styles Xaml. But without little bit more information, which line, or which TargetType, I am not sure where to look. 
Anyways, thanks for your help.

**Comment by PureWeen** [comment]
@StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
the 2 first DataTemplates have a `x:Name` attribute. Remove that, and you'll be able to move on
