### ISSUE TITLE
ClearButtonVisibility not working

### ISSUE THREAD

**Issue by RodBarnes** [dotnet/maui#13659]
### Description

I found [9954](https://github.com/dotnet/maui/issues/9954) and [6360](https://github.com/dotnet/maui/issues/6360) but these are both closed.  I'm experiencing this same issue.

When setting `ClearButtonVisibility` for a XAML `<Entry />` element, the 'X' appears but tapping on it does nothing when running on Android.  It works fine running on Windows.

**Android** (when the cursor appears is when I'm clicking on the button but it just takes it as putting the cursor in the field.)
https://user-images.githubusercontent.com/3944607/222578644-ca1dabd0-40ac-42f3-a17b-806d19073ec0.mp4

**Windows**
https://user-images.githubusercontent.com/3944607/222578775-02d7ba25-1f1b-47cc-8e1f-8403b5241339.mp4

XAML where `ClearButtonVisibility` is set for the XAML element.
```
<Frame Style="{StaticResource ViewFrame}" Grid.Row="0" Grid.ColumnSpan="2" Margin="10,10,10,0">
    <HorizontalStackLayout>
        <Label Text="Terms" 
               Style="{StaticResource LabelMedium}" 
               VerticalOptions="Center" 
               Margin="0,0,5,0" />
        <Entry Text="{Binding QueryFilter}" 
               WidthRequest="300" 
               HeightRequest="40"
               ClearButtonVisibility="WhileEditing" />
    </HorizontalStackLayout>
</Frame>
```

Framework Target is .NET 7
`<TargetFrameworks>net7.0-maccatalyst;net7.0-android33.0</TargetFrameworks>`

Workload list:

```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
wasm-tools                 7.0.3/7.0.100          VS 17.5.33424.131
ios                        16.2.1024/7.0.100      VS 17.5.33424.131
maccatalyst                16.2.1024/7.0.100      VS 17.5.33424.131
maui-windows               7.0.59/7.0.100         VS 17.5.33424.131
maui-maccatalyst           7.0.59/7.0.100         VS 17.5.33424.131
maui-ios                   7.0.59/7.0.100         VS 17.5.33424.131
android                    33.0.26/7.0.100        VS 17.5.33424.131
maui-android               7.0.59/7.0.100         VS 17.5.33424.131
wasm-tools-net6            7.0.3/7.0.100          VS 17.5.33424.131

```

Android SDK Manager is up-to-date; i.e., all updates have been applied.

### Steps to Reproduce

1. Clone the repository, build and run the app on Android emulator.
2. Tap menu, tap Parks.
3. Tap Filter button.
4. Tap Terms entry field.
5. Enter text in the field.
6. Tap the X to clear the field.

The X button appears but tapping on it does nothing.

### Link to public reproduction project repository

https://github.com/RodBarnes/NationalParks

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 31; API33

### Did you find any workaround?

No

**Comment by mouralabank** [comment]
I'm experiencing this same issue
