### ISSUE TITLE
IsVisible extension in IView

### ISSUE THREAD

**Issue by Ramttid** [dotnet/maui#13678]
### Description

There is no option to use the extension 'IVisible'

Code example:

(Children[0] as Grid).Children[1].IsVisible;

### Public API Changes

hmmm

### Intended Use-Case

Full code: 
public bool IsChecked
        {
            get => (Children[0] as Grid).Children[1].IsVisible;
            set
            {
                (Children[0] as Grid).Children[1].IsVisible = value;
                SetValue(IsCheckedProperty, value);
            }
        }

**Comment by rachelkang** [comment]
Hi, @Ramttid - we have a [Visibility](https://learn.microsoft.com/dotnet/api/microsoft.maui.controls.visualelement.microsoft-maui-iview-visibility?view=net-maui-6.0) property that you should be able to use. Could you provide more info on the scenario / specific control you're having issues with?

**Comment by Ramttid** [comment]
```
public bool IsChecked
{
     get => (Children[0] as Grid).Children[1].IsVisible;
     set
     {
        (Children[0] as Grid).Children[1].IsVisible = value;
        SetValue(IsCheckedProperty, value);
     }
}
```
In this example I cannot set the .IsVisible property to value. => ((Children[0] as Grid).Children[1].IsVisible = value;)

I have now fixed it by doing this:
```

public bool IsChecked
        {
            get => (Children[0] as Grid).Children[1].Visibility == Visibility.Visible;
            set
            {
                VisualElement child = (Children[0] as Grid).Children[1] as VisualElement;
                child.IsVisible = value;
                SetValue(IsCheckedProperty, value);
            }
        }
```

**Comment by hartez** [comment]
> I have now fixed it 

Glad you were able to find a solution!

**Comment by Ramttid** [comment]
Don't think this is the correct solution tho, in xamarin forms this works, maui it doesn't

**Comment by hartez** [comment]
What error does it give you in MAUI?

**Comment by Ramttid** [comment]
The property is inaccessible when using it like this: (.IsVisible cannot be found)
`(Children[0] as Grid).Children[1].IsVisible = value;`

but can find it like this:
`child.IsVisible = value;
`
