### ISSUE TITLE
Maui does not work at all[Bug] 

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#1367]
After I installed the latest .net preview 5, I tried to create a new maui app.   It fails to compile even with none of my code.
First, I tried the blazor template.  When that failed, I tried one without blazor and same issue.
So far, it appears that Maui will not work at all.
I would be really disappointed if it will become impossible to even create maui apps.
I don't have any mac or iphone though.  Hopefully they don't require a person to even have an iphone to use maui.
Tried to use the windows (winui) and it keeps saying "The project doesn't know how to run the profile MauiApp2.WinUI.
That was my second attempt.

**Comment by ShawnTheBeachy** [comment]
Got around this by going into the WinUI project properties. Debug tab > set the "Launch" dropdown to "Project".

**Comment by Fabi** [comment]
You need https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingTools to launch WinUI stuff.

**Comment by ncarandini** [comment]
You need to follow the [.NET MAUI installation](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation).
See https://github.com/dotnet/maui/issues/1379#issuecomment-864383473
