### ISSUE TITLE
RadioButton - Color of dot/glyph/indicator not changing

### ISSUE THREAD

**Issue by zZHorizonZz** [dotnet/maui#13670]
### Description

I want to change the color of the RadioButton component, but it seems it currently doesn't work. I asked on the answer forum how to change the color and I have been told it was through BorderColor which I already tried so I came to the conclusion that there is something wrong. I tested this only on android and windows. On Android, there is no change at all when using BorderColor, on windows it changes the color of the border of the component which I don't know if it's working as intended.

Screenshots:
![Screenshot 2023-03-03 085725](https://user-images.githubusercontent.com/60035933/222663973-25af3ea2-ea2c-4be0-a3bd-6675f9b2632e.png)
![Screenshot 2023-03-03 085611](https://user-images.githubusercontent.com/60035933/222663982-51122a57-b813-46fb-8b7e-36dd9f354569.png)

### Steps to Reproduce

1. Create the new MAUI app
2. Add the RadioButton with property BorderColor set to color of your liking. Something like this.
```xml
<RadioButton BorderColor="Aquamarine" Content="Border Color"></RadioButton>
```

### Link to public reproduction project repository

https://github.com/zZHorizonZz/MAUI-RadioButton-Bug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows 10 Enterprise (OS build 19044.2604)

### Did you find any workaround?

I think the workaround currently would be to use platform-specific code. For example on android changing the color tint of the button should work.

**Comment by dustin-wojciechowski** [comment]
Thanks for your issue. There has been some fixes to RadioButton recently that should fix some issues with the control. But what I think you might want to do is not solved by modifying the border color (which creates a border around the entire container including the ellipses and the text content), but by assigning values to the RadioButtonThemeColor and RadioButtonCheckMarkThemeColor in a ResourceDictionary in your project, or assigning individual light/dark values to the outer ellipse, and stroke and fill of the inner check glyph. Also on Windows and Android, don't forget to specify RadioButton.DefaultTemplate if you wish to use these theme colors.

 Please see this PR for more information on how to accomplish this: https://github.com/dotnet/maui/pull/14117 Thanks :)
