### ISSUE TITLE
Resources type or namespace does not exist

### ISSUE THREAD

**Issue by slprog1** [dotnet/maui#13677]
### Description

Hello,

I've recently tried to play around with .NET MAUI project, and one of the things I wanted to implement was the localization.
So I've added new folder, called Translations, into the Resources, and after that added Localizations.resx file.

I'm working on Mac, so I was kind of surprised to see plain xml file instead of graphical resource file editor like it is on VS for Windows, but nevertheless that is not a big deal. What matters is that I can't "implement" localization manager (or service) class because I can't access Culture property from Localizations' auto-generated cs file.

<img width="632" alt="Screenshot 2023-03-03 at 14 01 47" src="https://user-images.githubusercontent.com/5887079/222715664-55ebb402-3d19-4f34-b2dd-7036f9c6e9a6.png">

I've checked that on my another project which is written on Xamarin 5 - everything works fine there. 

Tools & frameworks specs:
- VS for mac - 17.5 (build 1802)
- .NET 7.0.1 (64-bit) 
Architecture: Arm64
- Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

- Updater
Version: 11

- Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

- Xamarin.Mac
Version: 9.1.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:14-0500

- Xamarin.iOS
Version: 16.2.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:15-0500

- Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 2023-02-14 00:26:00 UTC

- Xamarin.Android
Version: 13.2.0.0 (Visual Studio Community)

### Steps to Reproduce

1. create .NET MAUI project
2. add new folder into Resources
3. add new resx file
4. add using statement

### Link to public reproduction project repository

https://github.com/slprog1/MauiPlayground

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

iOS 16

> VS bug [#1759887](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1759887)

**Comment by mattleibow** [comment]
I think the csproj has gotten corrupte. Try removing these few lines: https://github.com/slprog1/MauiPlayground/blob/40fc3036aba80d7d7390853ba1d6abc44ee822d6/MauiPlayground.csproj#L70-L77

This is because the IDE is not doing something correctly, so might be best if you open on the feedback tool?

**Comment by mrward** [comment]
Files inside the Resources folder seem to be treated as BundleResources by default for iOS and MacCatalyst. I would look at adding string translations in another folder to avoid this problem.

Not sure why VS Mac here is applying the BundleResource files globs from MAUI (iOS and maccatalyst) in this particular case though since it should be using the first target framework in the project here when evaluating items, which would be Android.

**Comment by slprog1** [comment]
Moved to VS issues

**Comment by mattleibow** [comment]
Where is this new issue? In a MAUI app we redirect all the things into a Platform/iOS/Resources so the IDE should not be making files in the root Resources directory BundleResource.

**Comment by mrward** [comment]
Whilst this is an IDE bug for .resx files here. The various workload sdks define BundleResources for all files in those directories by default, and this is not something the IDE controls.

**Comment by mattleibow** [comment]
We have redefined those defaults! 

The new place:
https://github.com/dotnet/maui/blob/main/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.Globs.props#L66-L69

The `$(iOSProjectFolder)` is now Platforms\iOS\
https://github.com/dotnet/maui/blob/b653d40b00886197b9d4535168b4739f371561d2/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.SingleProject.targets#L15

So building an app will no longer assume the root Resources folder is BundleResource but rather the sub folder Platform\iOS\Resources.

The IDE should be looking at the value of ` <IPhoneResourcePrefix>$(iOSProjectFolder)Resources</IPhoneResourcePrefix>`
https://github.com/dotnet/maui/blob/b653d40b00886197b9d4535168b4739f371561d2/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.SingleProject.targets#L46

**Comment by mrward** [comment]
Thanks. My MAUI workload install is a bit out of date, which likely explains why I was seeing those BundleResource items.
