### ISSUE TITLE
[Enhancement] Add Loaded event for page

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#137]
## Summary
ContentPage now just has OnApearing override method and the Appearing event , but doesn't has Loaded event . 
Then now meet an "issue" , maybe , do navigation to the secondpage in the mainpage OnApearing method , result is I can not return to mainpage after I press the back button on the secondpage . 
Then search on the internet and I found this https://forums.xamarin.com/discussion/22561/page-loaded-event . 
Use the SizeChanged event as the "Loaded" event .
But I don't know if it is can use as "Loaded" event .

## API Changes

Page class add Loaded and UnLoaded Event .

## Intended Use Case

Page class add Loaded and UnLoaded Event .

**Comment by PureWeen** [comment]
duplicate https://github.com/dotnet/maui/issues/30
