### ISSUE TITLE
Using Microsoft.AspNetCore.Components.WebView.WindowsForms in Visual Studio says it does not have a strong name

### ISSUE THREAD

**Issue by kasajian** [dotnet/maui#13711]
### Description

Using Microsoft.AspNetCore.Components.WebView.WindowsForms 6.0.552 in a WinForms application targeting .NET 6.

Reference looks like this:

    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" Version="6.0.552" />

The desktop project has a strong name snk file.  

CSC : warning CS8002: Referenced assembly 'Microsoft.AspNetCore.Components.WebView.WindowsForms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
1><prj>-> <prj>\bin\Debug\net6.0-windows\<prj>.dll

If SNKs are no longer supported, why are the other .NET 6 related assemblies also referenced not producing this error.   But if they are supported, maybe this one was a miss and should be corrected.

### Steps to Reproduce

Use WinForms Blazor sample.  add strong name snk key

### Link to public reproduction project repository

n/a

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

n/a

### Did you find any workaround?

no workaround

### Relevant log output

```shell
CSC : warning CS8002: Referenced assembly 'Microsoft.AspNetCore.Components.WebView.WindowsForms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
1><prj>-> <prj>\bin\Debug\net6.0-windows\<prj>.dll
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is probably the case indeed but adding it would (at this point) be a breaking change. We will probably not do that given that we haven't heard this being a problem for this long.
Do you have a real scenario where you need this to work? If so, can you please share it? Thanks!
