### ISSUE TITLE
Using Clipboard solves the error CO_E_NOTINITIALIZED !

### ISSUE THREAD

**Issue by true-perfect-code** [dotnet/maui#13719]
### Description

I am trying to copy a text to the clipboard under Windows. To do this, I use the example from https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/data/clipboard?view=net-maui-7.0

Unfortunately, this triggers the following error for me:

**Coinitialize has not been called. (0x800401F0 (CO_E_NOTINITIALIZED))**

As I see it, this is not directly related to Clipboard, so it is difficult for me to figure out what is causing this error!

Can anyone confirm this error? Or is it my code?

![image](https://user-images.githubusercontent.com/45635963/223172274-d16d12c4-f6e9-46d1-8b0a-8a3e8733d712.png)

As you can see in the picture, I have tried pretty much all the variations, but each one triggers this error.

**EDIT**
**StackTrace**
   bei WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   bei ABI.Windows.ApplicationModel.DataTransfer.IClipboardStaticsMethods.SetContent(IObjectReference _obj, DataPackage content)
   bei Windows.ApplicationModel.DataTransfer.Clipboard.SetContent(DataPackage content)
   bei Microsoft.Maui.ApplicationModel.DataTransfer.ClipboardImplementation.SetTextAsync(String text)
   bei Microsoft.Maui.ApplicationModel.DataTransfer.Clipboard.SetTextAsync(String text)
   bei native.Pages.base.testBase.<CopyToClipboard>d__0.MoveNext() in E:\Users\User\source\repos\native\native\Pages\base\test.razor.cs: Zeile36

### Steps to Reproduce

Use NET MAUI 7 Clipboard function (see MS example on https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/data/clipboard?view=net-maui-7.0 )

### Link to public reproduction project repository

No

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Windows

### Affected platform versions

Windows SDK

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by jfversluis** [comment]
I've just tried this and it works perfectly for me, so please add a reproduction sample that we can look at so we can diagnose properly. Danke!

**Comment by true-perfect-code** [comment]
I will create a project tomorrow and upload it to GitHub.
I almost suspected it was hardware specific bug. Otherwise the guys would have contacted Microsoft much earlier.

By the way, I already reported a bug to FilePicker about a month ago, which only occurs for me when I have M.2 SSD as primary drive. This one might be along the same lines.

@jfversluis
Thank you for the message
