### ISSUE TITLE
Ticket: #11274 is closed before 2nd part of issue was resolved. Code snippet in ticket resolves most issues, but still leaves a sliver of previous page's view.

### ISSUE THREAD

**Issue by destynn** [dotnet/maui#13718]
Updating the Android code per ticket: #11274 only MOSTLY fixes the issue. Sometimes it still leaves a sliver of the previous page.

User @cerkzil was correct in mentioning this, but the ticket was closed after he brought it up, was there a continuation to this resolution?

**Comment by destynn** [comment]
https://user-images.githubusercontent.com/39460996/205447193-c38530e0-6554-4301-8329-4655c1816607.png

**Comment by PureWeen** [comment]
@destynn this should be fixed in a future release by https://github.com/dotnet/maui/pull/12661

I have a workaround in a nuget here
https://github.com/PureWeen/ShanedlerSamples

If you want to try that workaround and see if it fixes it for you

**Comment by destynn** [comment]
I think I tried your nuget but my project doesn't use .net7.0 since I'm porting it over from xamarin.

(Will support for 6.0 exist for your nuget in the future?)
