### ISSUE TITLE
Make DynamicResource bindings be supported as normal bindings

### ISSUE THREAD

**Issue by Cybrosys** [dotnet/maui#13724]
Hard to find a good title for this, but...

From what I could get as information while trying to use `DynamicResource` bindings against a `Behavior`, is that it seems that they only work when something is inheriting from `VisualElement`.

I would argue that you should be able to use `DynamicResource` bindings even when not inheriting from `VisualElement`. The reason being that you can put any type of value into a `ResourceDictionary`, so in essence it is just a normal binding where the source is the parent or app's `ResourceDictionary`.

### Discussed in https://github.com/dotnet/maui/discussions/13691

<div type='discussions-op-text'>

<sup>Originally posted by **Cybrosys** March  4, 2023</sup>
Hi,

I raised this Q&A and also a bug in the MCT repo:
https://github.com/CommunityToolkit/Maui/discussions/1054

It is a question related to doing a `DynamicResource ` binding against a bindable property on the `StatusBarBehaior`, if it is supported or a bug. If it is a bug I think it belongs here in the main MAUI repo.

Here is a link to the bug in the MCT Repo:
https://github.com/CommunityToolkit/Maui/issues/1056

So, is this a bug in the MAUI repo or a limitation? For me as a developer and consumer, since the XAML does not show any error I would expect and assume that I would be able to use a `DynamicResource` binding for the `StatusBarBehavior`'s `StatusBarColor` bindable property.

I also expressed in one of my comments that if I wanted to start investigating this, where would I start? I do not know who would own the `DynamicResource` binding. When doing a normal `Bind` I would expect it to be owned by the UI element itself, targeting a defined `BindingContext`. However, `DynamicResource` bindings seem a bit more "magical" in that they work without a `BindingContext` being defined/assigned.

There are several issues currently related to `DynamicResource` bindings not working in .NET 7 but in .NET 6. So I do not know if this problem is related to `Behavor`s specifically or a core issue with `DynamicResource`.

**Update**

I got information here https://github.com/CommunityToolkit/Maui/issues/1056 that it can't use `DynamicResource` because it does not inherit from [VisualElement](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/VisualElement.cs#L770) or implement [IResourcesProvider](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/IResourcesProvider.cs).

I would argue that you should be able to use `DynamicResource` even when not inheriting from `VisualElement`. The reason being that you can put any type of value into a `ResourceDictionary`, so in essence it is just a normal binding where the source is the parent or app's `ResourceDictionary`.</div>

**Comment by PureWeen** [comment]
@StephaneDelcroix thoughts?

**Comment by StephaneDelcroix** [comment]
A prerequisite for `{DynamicResource}` to work is an ability to be part of a object tree (ability for the DR to look up the tree for a resource with that name, AND the ability for a modified or added resource to notify down the tree that it has changed), and that's where it differs from `{Binding}`: a Binding hold a reference to a source (VM), a DR does not.

`VisualElement` provides that capability and that's why DR mostly works with VE. You could enable other objects of your own to support DR, there's an interface for that

**Comment by Cybrosys** [comment]
@StephaneDelcroix which interface would that be? The one I got information about is the private [IResourceProvider](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/IResourcesProvider.cs)
