### ISSUE TITLE
Hide Cancel button for SearchBar on iOS while edit/text enter operation using MAUI handlers and Mappers not working

### ISSUE THREAD

**Issue by muffadal53** [dotnet/maui#13720]
### Description

In .Net MAUI how can we hide the Cancel button for SearchBar control while entering text in the control. The way we used to do in Xamarin forms is by adding custom rendered for iOS with below code:

Xamarin forms code:

```C#
protected override void OnElementPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
 {
            base.OnElementPropertyChanged(sender, e);

            if (e.PropertyName == "Text")
            {
                Control.ShowsCancelButton = false;
            }
 }
```

So, in .Net MAUI how to achieve this using Handlers and Mappers approach? I tried with below code but that doesn't work for SearchBar controls used at multiple pages in the application

```C#
public static MauiApp CreateMauiApp()
{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

#if DEBUG
		builder.Logging.AddDebug();
#endif

        Microsoft.Maui.Handlers.SearchBarHandler.Mapper.AppendToMapping("MySearchBarCustomization", (handler, view) =>
        {
#if IOS
            handler.PlatformView.SetShowsCancelButton(false,false);
#endif
        });

        return builder.Build();
}
```

Please let us know as I am not able to find much documentation around this Handlers and Mappers with concrete examples on MAUI documentation.

### Steps to Reproduce

1. Download the solution here:

      https://github.com/muffadal53/MAUISearchBariOS

2. Run the Application on iOS and notice search bar on main page of the application.

3. Try to enter text in SearchBar and notice the Cancel button appears next to "x" button/icon on iOS - This is not OK as per below code added in which we set the Cancel button to false for iOS so it should hide the Cancel button:

```C#
Microsoft.Maui.Handlers.SearchBarHandler.Mapper.AppendToMapping("MySearchBarCustomization", (handler, view) =>
{
#if IOS
            handler.PlatformView.SetShowsCancelButton(false,false);
#endif
});
```

### Link to public reproduction project repository

https://github.com/muffadal53/MAUISearchBariOS

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15, iOS 16

### Did you find any workaround?

No.

### Relevant log output

```shell
N/A
```

**Comment by PureWeen** [comment]
@muffadal53 if you change your `Mapper` to 

```C#
Microsoft.Maui.Handlers.SearchBarHandler.Mapper.AppendToMapping("Text"
```

Does that work? That'll make your code more equivalent to `Forms`

**Comment by muffadal53** [comment]
Hi @PureWeen. The suggestion you provided above doesn't work and as per the MAUI documentation the first parameter to "AppendToMapping" method is a "key" which is:

**A string-based key. When modifying one of the mappings provided by .NET MAUI, the key used by .NET MAUI must be specified. The key values used by .NET MAUI control mappings are based on interface and property names, for example nameof(IEntry.IsPassword). The interfaces, and their properties, that abstract each cross-platform control can be found [here](https://github.com/dotnet/maui/tree/main/src/Core/src/Core). Otherwise, this key can be an arbitrary value that doesn't have to correspond to the name of a property exposed by a type. For example, MyCustomization can be specified as a key, with any native view modification being performed as the customization.**

So, I had used the arbitrary name because I didn't find any relevant mappings for ISearchBar in "https://github.com/dotnet/maui/tree/main/src/Core/src/Core" for hiding Cancel button while editing SearchBar in MAUI.

Hence, in conclusion the solution you suggested doesn't work. Please let me know how to implement is a way it works for iOS.

**Comment by mattleibow** [comment]
I think Text is partly correct, however it is not the only one that shows/hides the cancel button. I see we have another property that fires every time the cancel button will update: `CancelButtonColor`

```cs
#if IOS
SearchBarHandler.Mapper.AppendToMapping("CancelButtonColor", (handler, view) =>
{
    handler.PlatformView.SetShowsCancelButton(false, false);
});
#endif
```

We probably should have a separate property for this, so if this is something you think is worthwhile, please open a new feature request with the topic of adding a property to control the visibility of the cancel button.

NOTE to me: not sure if any other platforms have this concept of a cancel and a clear - so maybe this should just be a platform specific?

**Comment by muffadal53** [comment]
Hi @mattleibow thanks for your input. I tried by only adding the above handler as below and not the "Text" proposed by @PureWeen and its seems to work on iOS and I no longer see the "Cancel" button on iOS :

#if IOS
SearchBarHandler.Mapper.AppendToMapping("CancelButtonColor", (handler, view) =>
{
    handler.PlatformView.SetShowsCancelButton(false, false);
});
#endif

And as proposed by you I have opened a feature request in MAUI and following is the same "https://github.com/dotnet/maui/issues/13780".

Regards.

**Comment by acaliaro** [comment]
Maybe something like https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/entry?view=net-maui-7.0#display-a-clear-button ?

**Comment by jfversluis** [comment]
Looks like this issue is resolved then, let's stick with the feature proposal to discuss potentially adding that.
