### ISSUE TITLE
.NET MAUI cant show up on the list of project

### ISSUE THREAD

**Issue by pitamcclav** [dotnet/maui#13748]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

After installing the .Net Maui i cant find it under the listed projects

> VS bug [#1760889](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1760889)

**Comment by drasticactions** [comment]
@pitamcclav If you go to your console and type

```
dotnet new --list
```

what projects do you see? Do you see any MAUI projects?

**Comment by pitamcclav** [comment]
No I don't

**Comment by pitamcclav** [comment]
Actually it showed that now sdks were installed
i installed the sdk seperately
and still the same

**Comment by pitamcclav** [comment]
i got a solution
first make sure that you have an SDK installed and its recognized by the command line 
you can try that but running "dotnet --version"
if no sdk is present try deleting the dotnet folder in C:/program files (x86)
Once the dotnet sdk is present 
you can then run "dotnet new install Microsoft.Maui.Templates" in the terminal to independently install the MAUI templates
once its done open VS and search MAUI and the templates will be present.
