### ISSUE TITLE
Weird behavior with Compiled Bindings 

### ISSUE THREAD

**Issue by danardelean** [dotnet/maui#13764]
### Description

The compiled bindings don't works as expected

### Steps to Reproduce

1.Create two models that have one property in common
2.Set the x:DataType (compiled binding) on the page with one of the two models
3.Set the BindingContext an instance of the second model

I would expect:

1. If compiled binding should crash as it would use the cast of the object not reflection
2. Not do the binding on the common property

See the attached sample 

### Link to public reproduction project repository

https://github.com/danardelean/MAUICompiledBindings

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

**Comment by mattleibow** [comment]
May be related to https://github.com/dotnet/maui/issues/11956

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/11956
