### ISSUE TITLE
CommunityToolkit.Mvvm.SourceGenerators has errors

### ISSUE THREAD

**Issue by ITBeesPL** [dotnet/maui#13773]
### Description

Hello,
am i the only one seeing these errors after installing communityToolkit.mvvm version >= 8.0 ?
I tested with net 6.0 and net 7.0 same symptoms 

CommunityToolkit.Mvvm.SourceGenerators
![image](https://user-images.githubusercontent.com/91939133/223822696-b87842be-7a9f-46ef-a184-f0bc1d7cecc9.png)

Tested on a new project with one class and one property observable

### Steps to Reproduce

Create new Maui App project, add one partial class, install comunityToolkit.mvvm 8.0 or higher.

### Link to public reproduction project repository

https://github.com/ITBeesPL/MauiApp3

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

windows

### Did you find any workaround?

works correctly with versions  < 8.0

**Comment by mattleibow** [comment]
This may be best opened on the community toolkit repo: https://github.com/CommunityToolkit/Maui

I also think those are not actual errors but a list of all the analyzers? Maybe I am wrong.
