### ISSUE TITLE
MAUI for CPU ARM 64

### ISSUE THREAD

**Issue by mohammaderfanarbaby** [dotnet/maui#13789]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mohammaderfanarbaby** [comment]
How to make apps for ARM 64 processors in Android with MAUI?

**Comment by mohammaderfanarbaby** [comment]
.

**Comment by mattleibow** [comment]
@jonathanpeppers I think this is just a matter of setting some RIDs? Or should it generate an app for everything and there is a bug somewhere in the build?

**Comment by jonathanpeppers** [comment]
@mohammaderfanarbaby what problem are you having exactly?

Android apps build for 4 architectures by default: `arm64`, `arm`, `x86`, and `x64`.

**Comment by mohammaderfanarbaby** [comment]
Hello, I just started MAUI programming in Visual Studio and in order to
output as Android, I have to go to Android SDK Manager in Visual Studio and
download the desired SDK. I got the ARM 64 SDK for Android 9 and to view
For the output in Vigil Studio, I have to download the Android emulator
that is in it. To download, I have to go to the Android Device Manager and
give the specifications of the mobile phone on which I want to run the
program. I am building an Android 9 mobile phone with an ARM 64 processor
and When I try to run it, it gives an error and says that only x86 and x64
processors are supported
Please help what should I do?

‫‪msftbot[bot]‬‏ ***@***.***‬‏> در تاریخ پنجشنبه ۹ مارس ۲۰۲۳
ساعت ۱۱:۱۷ نوشت:‬

**Comment by jonathanpeppers** [comment]
Emulators are best run matching the same processor as your desktop computer. An arm64 emulator would run very slowly on an x64 PC, for example.

Details about emulators here: https://learn.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/

If you want to test on arm64, I would recommend attaching an Android device to your computer with a USB cable.

This is not strictly an issue with .NET MAUI, so if you still have trouble, you can file an issue appropriately at:

* Android SDK setup in Visual Studio: https://developercommunity.visualstudio.com
* Android emulators, in general: https://source.android.com/docs/setup/contribute/report-bugs

Hope that helps!

**Comment by mohammaderfanarbaby** [comment]
Hello, I want the program that is being developed to run on ARM processors,
but when I install the APK file on the mobile phone, it gives an error and
says that it is not compatible with the device.

‫‪Jonathan Peppers‬‏ ***@***.***‬‏> در تاریخ پنجشنبه ۹ مارس
۲۰۲۳ ساعت ۲۰:۳۱ نوشت:‬

**Comment by jonathanpeppers** [comment]
Can you give screenshots? error messages? etc.? There isn't enough information for me to help, sorry.

You should be able to just hit the green Play button in Visual Studio with the name of your device selected.

**Comment by mohammaderfanarbaby** [comment]
Sure, here it is.
[image: 1.jpg]

‫‪Jonathan Peppers‬‏ ***@***.***‬‏> در تاریخ جمعه ۱۰ مارس
۲۰۲۳ ساعت ۱۳:۵۳ نوشت:‬

**Comment by mohammaderfanarbaby** [comment]
[image: 2.jpg]

‫‪mohammaderfan arbaby‬‏ ***@***.***‬‏> در تاریخ جمعه
۱۰ مارس ۲۰۲۳ ساعت ۱۳:۴۰ نوشت:‬

**Comment by mohammaderfanarbaby** [comment]
[image: 3.jpg]

‫‪mohammaderfan arbaby‬‏ ***@***.***‬‏> در تاریخ جمعه
۱۰ مارس ۲۰۲۳ ساعت ۱۳:۴۰ نوشت:‬

**Comment by mohammaderfanarbaby** [comment]
[image: 4.jpg]

‫‪mohammaderfan arbaby‬‏ ***@***.***‬‏> در تاریخ جمعه
۱۰ مارس ۲۰۲۳ ساعت ۱۳:۴۱ نوشت:‬

**Comment by mohammaderfanarbaby** [comment]
[image: 5.jpg]

‫‪mohammaderfan arbaby‬‏ ***@***.***‬‏> در تاریخ جمعه
۱۰ مارس ۲۰۲۳ ساعت ۱۳:۴۱ نوشت:‬

**Comment by mohammaderfanarbaby** [comment]
[image: 6.jpg]

‫‪mohammaderfan arbaby‬‏ ***@***.***‬‏> در تاریخ جمعه
۱۰ مارس ۲۰۲۳ ساعت ۱۳:۴۲ نوشت:‬
