### ISSUE TITLE
When building on Android and creating an .apk file, the file size is too large.

### ISSUE THREAD

**Issue by Babyqoo** [dotnet/maui#13785]
Since I used a translator, please forgive me if my question is strange.

=====================

After creating a default project with .NET MAUI app, I deleted all the content in the default project.
Then, I deleted all the content in the default project and added only one webview control, and built the project to create an .apk file.

Is it normal for the .apk size to be around 30MB, or are there ways to reduce the size?

**Comment by mattleibow** [comment]
Are you building Debug or Release?

**Comment by Babyqoo** [comment]
> 
No, I didn't use R8 shrinker. I will search and try to apply it on the website. Thank you for the response!

**Comment by Babyqoo** [comment]
> 

@mattleibow When built with 'debug' mode, the .apk file size was 136MB, but when built with 'release' mode, the .apk file size was 30MB.

**Comment by mattleibow** [comment]
Is there a reason you closed this?

@jonathanpeppers what is the size of a fully linked default maui template? I thought it was smaller...

**Comment by jonathanpeppers** [comment]
Yes, we need numbers to look into this. 1 architecture was about 14 MB for GA:

https://github.com/jonathanpeppers/maui-profiling/blob/main/apks/maui.rtm/release-aot/com.companyname.hellomaui-Signed.apk

Keep in mind, I built this for 1 architecture to simulate what happens on Google Play. It will build all 4 by default, so you'll see a number that 4x the real number.

The real number would only be displayed by Google Play when you submit your app.

**Comment by Babyqoo** [comment]
> 닫은 이유가 있나요?
> 
> @jonathanpeppers완전히 연결된 기본 maui 템플릿의 크기는 얼마입니까? 작을 줄 알았는데...

I don't know how to use Git, so I think the issue was closed by mistake.
