### ISSUE TITLE
Shell Search leaves screen darkened after navigation

### ISSUE THREAD

**Issue by RonPeters** [dotnet/maui#13813]
### Description

When I navigate to a detail page from a collection view, it looks fine. When I navigate to the same page via shell search handler, the page is darkened, like there is an opacity or overlay. The darkening goes away after you tap the screen

### Steps to Reproduce

1. Download Xaminals sample solution
2. Build and run
3. Use the search bar
4. Select an item from search
5. The target page is mysteriously dark
6. Tap and the darkness goes away

Starting Search
![Screenshot_1678433182](https://user-images.githubusercontent.com/76271129/224251805-d183e1a8-af20-42f0-8c7b-4a7fd5482457.png)

Navigated to page from search
![Screenshot_1678433186](https://user-images.githubusercontent.com/76271129/224251894-99f84509-e58c-40b8-9b49-151af35c5b1d.png)

After tapping the page
![Screenshot_1678433190](https://user-images.githubusercontent.com/76271129/224251918-2170fe32-c4ea-46e2-9702-37f0dc15b1fa.png)

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/Fundamentals/Shell

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Emulator, Pixel 5 API 33

### Did you find any workaround?

Have not determined a workaround. Noticed the problem in the latest .NET 7 in my own project, but verified replication on Xaminals which is 6.0.552. Have not tried on a physical device

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on android platform with sample project.
https://github.com/dotnet/maui-samples/tree/main/6.0/Fundamentals/Shell
![13813](https://github.com/dotnet/maui/assets/77434865/616ab4fd-afd9-430c-9107-cd09eec55e20)
