### ISSUE TITLE
[Android] - Opacity property not working properly at initial loading time for Frame and ListView control

### ISSUE THREAD

**Issue by BalachandarSelvam** [dotnet/maui#13811]
### Description

For a specific scenario I need to set opacity to 0 for ListView and Frame control at initial loading time, but in Android platform the opacity is not working properly. If I change the opacity dynamically it was working as expected.  In all other platforms it was working fine at initial loading time.

### Steps to Reproduce

1. Run the attached sample
2. Navigate to either frame or list view page
3. Check the label for opacity value 
4. Click the toolbar item to change the opacity dynamically.

![bug](https://user-images.githubusercontent.com/102292597/224236461-8c9db1f8-4bc8-4fe8-b855-3f3e2e02792a.gif)

### Link to public reproduction project repository

https://github.com/BalachandarSelvam/Framework-bug/tree/main/Opacity-Bug

### Version with bug

6.0.552

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
Are you using .NET 6?, could you update the version?. This is already fixed in .NET 7:
![image](https://user-images.githubusercontent.com/6755973/226917476-56eb26d5-7932-468f-9eb2-a56cc341030d.png)

**Comment by BalachandarSelvam** [comment]
Hi @jsuarezruiz , 
Yes, we are working on .Net 6. Though in .Net 7, this fix was not working on ListView.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Android platform with sample project.
https://github.com/BalachandarSelvam/Framework-bug/tree/main/Opacity-Bug
![image](https://github.com/dotnet/maui/assets/82450723/49e769e2-cb78-4ef1-9b1f-03d3390f4d27)

**Comment by aleks42** [comment]
I have a similar problem with opacity. When opening the page, it is ignored (I'm trying to make boxview with opacity = .7). Managed to make it work if using binding and property in viewmodel.
