### ISSUE TITLE
No image rendered on the MAUI App created by template (Preview 5) [Bug] 

### ISSUE THREAD

**Issue by ncarandini** [dotnet/maui#1382]
### Description

When running the MAUI app in the emulated Android device, I can 't see the Dotnet bot image:

![image](https://user-images.githubusercontent.com/139274/122640670-173d5500-d101-11eb-9e81-eea823bb0ffb.png)

### Steps to Reproduce

1.  Install VS 2022 (Version 17.0.0 Preview 1.0) or in the VS 2019 (Version 16.11.0 Preview 2.0)
2. Update maui-check and run it
3. Create a new MAUI app from the VS template

### Expected Behavior
In the main page, below the "Click me" button, see the dotnet bot image

### Actual Behavior
The image is not shown.

**Comment by andyfmking** [comment]
Setting the HeightRequest on the image in MainPage.Xaml fixes it.
Also the label with the counter in MainPage.Xaml doesn't show the second digit when count is greater than 9, seems that the HorizontalOptions for the Label still doesn't work (currently tested on Android only)

**Comment by jsuarezruiz** [comment]
Testing with Preview 11, the image appear and the text is invalidating the Layout
![image](https://user-images.githubusercontent.com/6755973/140495592-d3c75a10-cb3c-4375-97af-a89d9e902c22.png)

I am going to close the PR, but feel free to reopen it or open a new one if find anything!.
