### ISSUE TITLE
Masking(PatternMask) with MudBlazor not working in Blazor hybrid

### ISSUE THREAD

**Issue by MOAnfaDaniel922** [dotnet/maui#13834]
### Description

I am trying to use the MudBlazor library to mask a phone number,card number input in a **Blazor hybrid** app, but it is not working as expected. Here is the code that I am using:
`<MudTextField Mask="@(new PatternMask("00 00 00 00 00"))" Label="phone Number"
                      @bind-Value="phoneNumber" Variant="@Variant.Text" Clearable />`

This code works well in a Blazor webassembly project, but when i try to use it in a **Blazor hybrid** app, the masking feature does not work. Has anyone else encountered this issue with .net maui blazor or blazor hybrid? Any help would be greatly appreciated.
Note:I tried the example provided in the link below, but it doesn't seem to be working for blazor hybrid: 
[https://mudblazor.com/features/masking#multimask](url)

### Steps to Reproduce

1.Create a Blazor hybrid app
 2.Add the MudBlazor library
 3.Use the MudTextField component with a phone number mask

### Link to public reproduction project repository

https://github.com/dotnet/maui/blob/main/.github/repro.md

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

android

**Comment by drasticactions** [comment]
Shouldn't this go to the MudBlazor library first to ensure it's not an issue with their implementation?

**Comment by MOAnfaDaniel922** [comment]
@drasticactions  I have tested all of the masking examples provided by MudBlazor, and they have worked well in a WebAssembly project but it doesn't  working for blazor hybrid ,you can test it from:
[https://mudblazor.com/features/masking#multimask](url)
Thank you.

**Comment by drasticactions** [comment]
@MOAnfaDaniel922 I understand, but if you ask that project first to take a look they could see if this is intrinsic to something within MAUI Blazor, something within their own code, or something else.

MAUI Blazor is based on webviews running on the given platforms (Webview2 for Windows, etc). If you built a straight .NET Android app (`dotnet new android`), put in a webview, and ran the same code there's a good chance it'll fail the same way.
