### ISSUE TITLE
[Windows] Triggered VisualState only gets applied for a short time, then is undone

### ISSUE THREAD

**Issue by spadapet** [dotnet/maui#13837]
### Description

This only repros on Windows, on Android the VisualState change works fine.

I'm using either a StateTrigger or CompareStateTrigger to apply a VisualState. The VisualState applies, and then is either immediately undone, or clicking a button in the view causes it to undo.

### Steps to Reproduce

**REPRO:**

1. Open linked sample project MyDash.sln in VS (link is to branch bug/VisualStateTempApply)
2. Ensure "Windows Machine" is the debug target
3. F5 to build and debug
4. Watch the loading animation for 3 seconds, then the UI is supposed to change state. It will either change state and go right back to loading animation, or it will go back after clicking the "Retry" button

**RESULT:**

First you see the initial loading animation:
![image](https://user-images.githubusercontent.com/2523431/224449124-79b8c58a-12db-4a03-bd9c-2c9f57e3d8b0.png)

After three seconds you see the pretend error:
![image](https://user-images.githubusercontent.com/2523431/224449158-3e0d066a-ffac-4f15-81b4-78a48a95d676.png)

Then after a second, it'll go back to loading. If that doesn't happen, click the "Retry" button. It's supposed to do nothing, but the VisualState changes will be undone.

The "HasError" trigger only ever changes from false to true once, it never goes back, so the VisualState should stay applied:
![image](https://user-images.githubusercontent.com/2523431/224449411-3c26c855-494d-4c4c-a6d9-81e87f4e59f2.png)

### Link to public reproduction project repository

https://github.com/spadapet/mydash/tree/bug/VisualStateTempApply

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

No known workaround

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on Windows platform with sample project.
https://github.com/spadapet/mydash/tree/bug/VisualStateTempApply
![image](https://github.com/dotnet/maui/assets/82450723/cadf8302-0c28-4ddb-9014-9ec132b55d50)

**Comment by spadapet** [comment]
Yes @homeyf it looks like the bug doesn't repro anymore. Thanks to whoever fixed this!
