### ISSUE TITLE
App crashes within a few seconds

### ISSUE THREAD

**Issue by MahmudX** [dotnet/maui#1383]
### Description

If I run the app on the android emulator, the app opens up and crases within few seconds. But I was able to click on the click me button and saw the increment but. 
I've tried with vs 2019 16.11 and newly released vs 2022 preview 1. The result is the same. I've tried reinstalling .NET6 SDK, Android Emulator, cleaning the project,
creating another project, downloading the sample weather app from GitHub but the problem remained. 

If I run the installed version of the app from the emulater, it gets stucks. The **Weather ’21** demo app also crashes.

### Steps to Reproduce

1. `dotnet new maui `
2. `dotnet restore`  
3. `dotnet build`  
4. `dotnet build -t:Run -f net6.0-android`  

### Expected Behavior

The app should run smoothly.

### Actual Behavior

Crashing without any build error.

### Basic Information

- Version with issue: 6.0.1000-preview.5.794
- Last known good version: None
- IDE: Visual Studio 2019 16.11 (Preview) & Visual Studio 2022 17.0.0 (Preview 1.0)
- Platform Target Frameworks: 
  - Android: 9.0, 11.0
- Nuget Packages: Microsoft.Maui (6.0.1000-preview.5.794)
- Affected Devices: Android

### System Information

- Windows 10 Pro
- 16 GIG 
- AMD Ryzen 5 3600
- Nvidea GeForce GT220 1GB

### Screenshots

![maui_notworking_ss](https://user-images.githubusercontent.com/16564582/122646708-5dff6f00-d142-11eb-886f-cd9f83d0b911.gif)

### `maui-check` Output

[maui-check.txt](https://github.com/dotnet/maui/files/6680906/maui-check.txt)

### Build Output

[buid output.txt](https://github.com/dotnet/maui/files/6680904/buid.output.txt)

### Debug output

[debug output.txt](https://github.com/dotnet/maui/files/6680902/debug.output.txt)

**Comment by matt-goldman** [comment]
See #1361

**Comment by MahmudX** [comment]
After disabling the hot reload, the app doesn't crash but freezes instead. Also if it were the hot reload issue, it would have run perfectly if I fire it up from the command line. 

After running multiple times (After disabling the Hot reload), the result didn't change.

So I cleaned the solution, uninstalled the existing app from the emulator, and tried to run again. Now the app is not even starting. Here is the result if I try to run from the command line -

![image](https://user-images.githubusercontent.com/16564582/122657274-fd912180-d183-11eb-97dc-4049699cb209.png)

Here the build gets failed, but if I run from the visual studio -

![image](https://user-images.githubusercontent.com/16564582/122657251-befb6700-d183-11eb-8130-3e20d01d0b5c.png)

Also, you can see in the picture that the app wasn't got installed at all.

![Screenshot_1624143537](https://user-images.githubusercontent.com/16564582/122657301-3f21cc80-d184-11eb-9ceb-19066b01600a.png)

But here is the recent view -

![Screenshot_1624143766](https://user-images.githubusercontent.com/16564582/122657388-dedf5a80-d184-11eb-8320-5542c3262117.png)

This time I used vs 2022 preview 1. I tried all the basic troubleshooting such as restarting the IDE and cleaning the project.

**Comment by jfversluis** [comment]
Hey @MahmudX are you still having issues with this? Did you get it to work with newer versions?

**Comment by jsuarezruiz** [comment]
I tried with latest Preview (Pre 11, cannot reproduce the issue and Hot Reload is working. However, we maintain the issue open to receive feedback from @MahmudX.

**Comment by MahmudX** [comment]
You guys are responding so fast. Such fast that I was bored and tired of waiting, therefore uninstalled all the MAUI workload to be in peace.

**Comment by jfversluis** [comment]
Glad your life is better now! Let us know if we can help you in any other way.
