### ISSUE TITLE
System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible

### ISSUE THREAD

**Issue by anherukun** [dotnet/maui#13830]
### Description

I'm deploying a Release version for android app, and i get this message error `` System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible` ``

Also i'm trying with debugger but this error doesn't appears, every works fine 

### Steps to Reproduce

1. Create MAUI app project with .net 6 framework
2. In XAML editor add the property ZIndex with any value
3. Choose Release deployment
4. Compile and run (Emulator or Physical device indistinct)

Optional: Use device logger to identify the exception

### Link to public reproduction project repository

https://github.com/anherukun/zindexerrorexample

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 (Tested)

### Did you find any workaround?

Not using Zindex, but rather positioning the objects in reverse order in the XAML Editor

**Comment by hartez** [comment]
@anherukun Does the error occur if you update to .NET 7?

**Comment by anherukun** [comment]
![image](https://user-images.githubusercontent.com/16740339/225131735-02b1f253-0555-4975-8782-8e07b8010e46.png)

I'm using MAUI 7.0.59

**Comment by hartez** [comment]
> ### Steps to Reproduce
> 1. Create MAUI app project with .net 6 framework

Does the problem occur if you create your project with the .NET 7 framework?

**Comment by anherukun** [comment]
My mistake. I'm tested with .net 7 and it works fine
