### ISSUE TITLE
Removing Obsolete References

### ISSUE THREAD

**Issue by taz4270** [dotnet/maui#1384]
https://github.com/dotnet/maui/blob/7c2bd8361105aac5682ed17c742760ff2bcaa7fc/src/Controls/src/Core/VisualElement.cs#L735

Hello, can i comment all obsolete references that are no longer use like this one?

**Comment by jfversluis** [comment]
While I appreciate the offer for help I don't think it is very useful right now. It might be that code is not ported that will start referencing this code and/or we will probably do some pass to cleanup the code as we near a release.

Thanks!
