### ISSUE TITLE
Unable to create android class library with maui preview 5

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#1385]
If I create even the most simple class library that needs to reference android apis, then when i deploy, there is an error that says "Xamarin.Android does not support deploying the previous version.  Please ensure your solution builds before deploying it."
The solution did build successfully though.
Even tried deploying to emulator on android and still same error.  For the class library, the project file was something like this.

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0-android</TargetFrameworks>
  </PropertyGroup>
  
</Project>

If I take out the -android, then it works.  However, it means that I cannot access any android stuff.  I do know this library will only work on android and I intend only on android.  An example of how it can be used is for an android music player.

**Comment by PureWeen** [comment]
Can you attach a repro @musictopia2  ?

**Comment by musictopia2** [comment]
Here is the repository now.
https://github.com/musictopia2/AndroidClassLibraryFailProject

**Comment by mattleibow** [comment]
Closing this as this should be fixed in the latest previews. We also have added class library templates.
