### ISSUE TITLE
Can't Disable MAUI Blazor - Android WebView Streached  Overscroll / Bounse effect which feels non native

### ISSUE THREAD

**Issue by sangeethnandakumar** [dotnet/maui#13852]
### Description

The default render of web view in Android for Blazor MAUI has a bounce / stretch / over-stretch feature which feels very much non-native and any user can spot it as a webview.

Is there any way I can disable it?
Is there any way I can disable this webview feature app-wide or at least on Android?

### Steps to Reproduce

1. Create a Blazor MAUI app
2. Render a big list of cards
3. Drag left or right or top to bottom
4. The default web-view engine of Android will try to stretch the layout which is called over-scroll or bounce effect in mobile browsers. It's very common on almost all mobile browsers

But when we see this inside a native app, That feels very non-native and any user can immediately spot it as some sort of web-view.

I tried adding this to CSS
```css
<style>
    section {
        overscroll-behavior: none !important
    }
</style>
```

But no effect..!
Is there any way I can disable this webview feature app-wide or at least on Android

### Link to public reproduction project repository

https://github.com/sangeethnandakumar/MAUI-Blazor-Template/tree/checkpoints/RenderIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13 (Samsung Galaxy S22)

### Did you find any workaround?

No

**Comment by Eilon** [comment]
Hi, there's a setting on the Android WebView to control this called "Overscroll Mode". From BlazorWebView you can get access to the Android WebView and change this setting.

In a default .NET MAUI Blazor app you can edit `MainPage.xaml.cs` and register an event handler for the BlazorWebView in the `MainPage` constructor:

```c#
        blazorWebView.BlazorWebViewInitialized += BlazorWebView_BlazorWebViewInitialized;
```

And the event handler would look like this:

```c#
    private void BlazorWebView_BlazorWebViewInitialized(object sender, Microsoft.AspNetCore.Components.WebView.BlazorWebViewInitializedEventArgs e)
    {
#if ANDROID
        // Disable overscroll on Android
        e.WebView.OverScrollMode = Android.Views.OverScrollMode.Never;
#endif
    }
```
