### ISSUE TITLE
[Bug] Missing SetMenu implementation on ContentPage

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1386]
### Description

In Xamarin.Forms this will create a menu for macOS app. 

```csharp
var mainMenu = new Menu();

var fileMenu = new Menu { Text = "File" };
var exitItem = new MenuItem
{
Text = "Exit",
Command = new Command((obj) =>
{
	Application.Current.Quit();
})
};
MenuItem.SetAccelerator(exitItem, Accelerator.FromString("cmd+q"));
fileMenu.Items.Add(exitItem);

var locationMenu = new Menu { Text = "Location" };
var changeItem = new MenuItem
{
Text = "Change",
Command = new Command((obj) =>
{
	Navigation.PushAsync(new ButtonPage());
})
};
locationMenu.Items.Add(changeItem);

var refreshItem = new MenuItem
{
Text = "Refresh"
};
MenuItem.SetAccelerator(refreshItem, Accelerator.FromString("cmd+r"));
locationMenu.Items.Add(refreshItem);

mainMenu.Add(fileMenu);
mainMenu.Add(locationMenu);
SetMenu(Application.Current, mainMenu); 
```

### Steps to Reproduce

1. Add the above code or similar to any ContentPage
2. Run the app and observer

### Expected Behavior

I should see my custom menu items in the top macOS menu bar, and the WinUI window however it handles menus (at least allowing accelerators to work).

### Actual Behavior

No errors. No menus.

### Basic Information

- Version with issue: pre5

Test on macOS Big Sur.

https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/DesktopSupportTestPage.cs

**Comment by v-longmin** [comment]
@davidortinau Could you provide your repro projects, thanks?

**Comment by davidortinau** [comment]
#4640 solves this
