### ISSUE TITLE
Android and iOS: BackgroundColor and TextColor properties are not getting applied for Button if they are set based on Converters

### ISSUE THREAD

**Issue by muffadal53** [dotnet/maui#13865]
### Description

If we set the "BackgroundColor" and "TextColor" properties of **Button** control based on Converters then these properties are not getting applied to Button control. However if we hardcode these properties to the Button control then the "BackgroundColor" and "TextColor" gets applied correctly.

### Steps to Reproduce

Download solution here

https://github.com/muffadal53/MAUIButtonBackgroudColorBug.git

Run solution

On MainPage, 

Check the "BackgroundColor" and "TextColor" based on converter is not getting applied - **This is NOT OK**

click on checkbox "AlterButtonEnabledAndColor"

Notice that the Button "UsingConverters_Colors_NotAppliedButton" gets enabled however the "BackgroundColor" and "TextColor" properties doesn't get updated - **This is NOT OK**

Again uncheck the checkbox "AlterButtonEnabledAndColor" and notice that the button gets disabled however the "BackgroundColor" and "TextColor" properties doesn't get updated - **This is NOT OK**

However notice that the hardcoded values provided to button "StaticColors_GettingAppliedButton" gets applied correctly - **This is OK and working fine**

### Link to public reproduction project repository

https://github.com/muffadal53/MAUIButtonBackgroudColorBug.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11, iOS 16

### Did you find any workaround?

No

### Relevant log output

```shell
N/A
```

**Comment by jsuarezruiz** [comment]
This issue should have been fixed by this recent PR https://github.com/dotnet/maui/pull/9814

**Comment by muffadal53** [comment]
@jsuarezruiz Many thanks for the update. 

Can you please update in which version of .Net will this fix be available and tentatively when would it be available?

**Comment by muffadal53** [comment]
@mattleibow This happens with latest version of .Net MAUI framework and the sample/reproduction project is already mentioned above and here is the link of the same "https://github.com/muffadal53/MAUIButtonBackgroudColorBug.git". 
You can try the same and let me know if I am missing anything on my side to make it work in MAUI.

Thanks.

**Comment by muffadal53** [comment]
> @mattleibow This happens with latest version of .Net MAUI framework and the sample/reproduction project is already mentioned above and here is the link of the same "https://github.com/muffadal53/MAUIButtonBackgroudColorBug.git".
> 
> @mattleibow, @jsuarezruiz The fix mention in issue "[9814](https://github.com/dotnet/maui/pull/9814)" is different then what I have mention above because as per mentioned in PR "[9814](https://github.com/dotnet/maui/pull/9814)" if I do similar thing of Binding for Button "BackgroundColor" OR "TextColor" using ViewModel then it works for me too and I have updated my sample to show that too. You can have a look at "BindingColorAppliedBtn" in MainPage.xaml in my example "https://github.com/muffadal53/MAUIButtonBackgroudColorBug.git". However if we set color based on Converters then it doesn't seem to work is the issue we are facing.
> 
> You can try the same and let me know if I am missing anything on my side to make it work using Converters in MAUI.
> 
> Thanks.

@mattleibow This happens with latest version of .Net MAUI framework and the sample/reproduction project is already mentioned above and here is the link of the same "https://github.com/muffadal53/MAUIButtonBackgroudColorBug.git".

@mattleibow, @jsuarezruiz The fix mention in issue "https://github.com/dotnet/maui/pull/9814" is different then what I have mention above because as per mentioned in PR "https://github.com/dotnet/maui/pull/9814" if I do similar thing of Binding for Button "BackgroundColor" OR "TextColor" using ViewModel then it works for me too and I have updated my sample to show that too. You can have a look at "BindingColorAppliedBtn" in MainPage.xaml in my example "https://github.com/muffadal53/MAUIButtonBackgroudColorBug.git". However if we set color based on Converters then it doesn't seem to work is the issue we are facing.

You can try the same and let me know if I am missing anything on my side to make it work using Converters in MAUI.

Thanks.
