### ISSUE TITLE
[Bug] Unable to use Application.Current.Quit

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1387]
### Description

This should quit the running desktop application, but doesn't.

```csharp
Application.Current.Quit();
```

### Steps to Reproduce

1. Add this code to a button handler
2. Click it

### Expected Behavior

The application should quit

### Actual Behavior

Nothing happens. No errors are thrown.

### Basic Information

- Version with issue: pre5
- macOS Big Sur

https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/DesktopSupportTestPage.cs#L223

**Comment by cjldev** [comment]
This bug appears to apply to the Windows platform too. More specifically, the Quit method does not work on Windows with MAUI Preview 6.

**Comment by jfversluis** [comment]
Seems this is fixed then? Seems like we'll have an extra look with #2814 anyway
