### ISSUE TITLE
error: Failed to load AOT module 'Microsoft.Maui.Graphics' while running in aot-only mode

### ISSUE THREAD

**Issue by cdavidyoung** [dotnet/maui#13882]
### Description

I am trying to deploy an app to the App Store using release mode and it crashes even though in debug mode it works fine. This is discussed in https://github.com/dotnet/maui/issues/12537 but I can't tell how to resolve this. Supposedly Add <UseIntepreter>True</UseInterpreter> to the .csproj file is the fix but it is not obvious where and all the places I have tried result in the project not even building.

Could someone please elaborate on the fix and whether this is a permanent solution?

Specifically, could @[ghevi](https://github.com/Ghevi) please comment?

Strangely enough I was able to deploy the first version of my app successfully (https://apps.apple.com/us/app/cacheall/id1667541054) but during the review process they discovered that the next version crashes as described here.

Thanks

### Steps to Reproduce

This is reproduced in https://github.com/dotnet/maui/issues/12537

### Link to public reproduction project repository

https://github.com/dotnet/maui/issues/12537

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

all so far

### Did you find any workaround?

Supposedly Add <UseIntepreter>True</UseInterpreter> to the .csproj file I have not been able to verify this since it is not explained where to add this line.

**Comment by cdavidyoung** [comment]
I fixed my problem by just doing a Clean All before doing the Release build.  It was not necessary to modify the .csproj file as suggested.  The app has been succesfully installed and tested via TestFlight so I resubmitted it for review.

**Comment by onurhazar** [comment]
Same issue here with my .NET iOS project. Weird thing is sometimes it gives the same error with another package name/project name which doesn't make any sense. Cleaning works as a workaround but it takes too much time to rebuild :(

**Comment by tussock** [comment]
Yeah... I get this one every 3 or 4th run, and then I need to do a rebuild which takes time.
HotReload is disabled too. 
It's a damned nuisance. but given VSMac is now dying... I'm guessing there's no fix coming.

**Comment by Zhanglirong-Winnie** [comment]
Visual Studio Enterprise 17.6.5(build 417). Can repro on iOS platform.

**Comment by Michal-MK** [comment]
I was suspecting Rider but if it is happening with VS as well: `error: Failed to load AOT module 'Microsoft.Maui.Controls' while running in aot-only mode: doesn't match assembly.` +1 here
