### ISSUE TITLE
Mac catalyst target cannot be removed from project Properties page

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#13884]
### Description

All other target platforms have the setting.
Mac Catalyst does not and cannot be removed.
![image](https://user-images.githubusercontent.com/64279914/224806180-59bc211b-3a2c-4df7-85e5-98ad0a2f7773.png)

### Steps to Reproduce

Create a new MAUI app
Rightclick project -> Properties -> see.

### Link to public reproduction project repository

not needed

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

all

> VS bug [#1772200](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1772200)

**Comment by Eilon** [comment]
Interesting, I see the same thing in VS 17.6 Preview 1.

**Comment by janseris** [comment]
I can see that you linked a link to internal VS bug tracking. Does this mean that this problem is already being solved?

**Comment by Eilon** [comment]
> I can see that you added a link to internal Microsoft Visual Studio bug tracking. Does this mean that this problem is already being solved?

It's an internal clone of this issue that contains no additional information. But if you do use VS's Report a Problem we can associate the logs created by that with the internal issue, which can be helpful if we need more info about the issue. That internal issue will be more easily tracked by teams that work on VS components because they don't have any easy way to track various GitHub issues in various repos (such as this one). And when that issue is updated it is possible to send some of those updates back to this issue here (you'll see some weird bot-looking-account commenting).

**Comment by japarson** [comment]
@janseris Thank you for filing this bug. The workaround here would be to manually remove the maccatalyst target framework from the csproj like so:
![image](https://user-images.githubusercontent.com/59936622/226447576-8984533a-d47b-4243-b2e1-32bca68959a9.png)

We will add support for this functionality to the property page UI in the future.

It would be very helpful if you could report this problem to VS using these instructions: https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

Thank you!

**Comment by janseris** [comment]
@japarson Elion already linked the VS bug [#1772200](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1772200) issue, I think it's reported.
I think that no log from VIsual Studio or anything is needed because this happens for every MAUI project.

**Comment by mariaghiondea** [comment]
@janseris that is an internal work item. Reporting it through the feedback tool or developer community, will allow other users to vote on it, helping us prioritize, as well as for everyone to track the work.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on android platform with sample project.
![image](https://github.com/dotnet/maui/assets/82450723/9e1c4043-d1fb-4196-a8eb-ac8dd19c8deb)
