### ISSUE TITLE
i dont have MAUI when i want to select workload 

### ISSUE THREAD

**Issue by a52cents** [dotnet/maui#13887]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

> VS bug [#1772212](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1772212)

**Comment by MSLukeWest** [comment]
@a52cents In the Visual Studio installer, can you select "Modify" and then make sure you have the workload ".NET Multi-platform App UI development" selected?  Once this workload is added you should see the .NET MAUI templates in the new project dialog.
