### ISSUE TITLE
Error compiling 8.0 preview 1

### ISSUE THREAD

**Issue by SF-Simon** [dotnet/maui#13897]
### Description

I try to complete the locally compiled test version according to the instructions of the development guide.
I downloaded the main version from GitHub without changing anything.
I used the following command and got wrong feedback.

### Steps to Reproduce

Git clone https://github.com/dotnet/maui/

and

$ dotnet tool restore
$ dotnet build src\DotNet\DotNet.csproj       /        $ dotnet cake --target=VS

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

8.0 previews

### Last version that worked well

7.0 (current)

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041 and Windows SDK 10.0.22621

### Relevant log output

```shell
PS D:\maui-main> dotnet tool restore
工具“cake.tool”(版本“1.2.0”)已还原。可用的命令: dotnet-cake
工具“powershell”(版本“7.2.1”)已还原。可用的命令: pwsh
工具“microsoft.dotnet.xharness.cli”(版本“1.0.0-prerelease.23152.1”)已还原。可用的命令: xharness
工具“api-tools”(版本“1.3.5”)已还原。可用的命令: api-tools

还原成功。
PS D:\maui-main> dotnet build src\DotNet\DotNet.csproj
MSBuild version 17.6.0-preview-23108-10+51df47643 for .NET
  正在确定要还原的项目…
  所有项目均是最新的，无法还原。
D:\Net_Program\Net_NuGet\Packages\microsoft.codeanalysis.netanalyzers\7.0.0\build\Microsoft.CodeAnalysis.NetAnalyzers.t
argets(593,5): warning : The .NET SDK has newer analyzers with version '8.0.0' than what version '7.0.0' of 'Microsoft.
CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference. [D:\maui-main\src\DotNet
\DotNet.csproj]
    正在确定要还原的项目…
C:\Program Files\dotnet\sdk\8.0.100-preview.1.23115.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.Sha
red.targets(152,5): error MSB4062: 未能从程序集 C:\Program Files\dotnet\sdk\8.0.100-preview.1.23115.2\Sdks\Microsoft.NET.Sdk\
targets\..\tools\net8.0\Microsoft.NET.Build.Tasks.dll 加载任务“CheckForImplicitPackageReferenceOverrides”。Could not load fi
le or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 系统找不到指定的文件。 请确认 <Us
ingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。 [D:\maui-main\src\DotNet\Dependen
cies\Workloads.csproj] [D:\maui-main\src\DotNet\DotNet.csproj]
D:\maui-main\src\DotNet\DotNet.csproj(171,5): error MSB3073: 命令“"D:\maui-main\bin/dotnet/dotnet" rest
ore "D:\maui-main\src\DotNet\Dependencies/Workloads.csproj" -bl:D:\maui-main\artifacts/DotNetWorkload
s.binlog”已退出，代码为 1。

生成失败。

D:\Net_Program\Net_NuGet\Packages\microsoft.codeanalysis.netanalyzers\7.0.0\build\Microsoft.CodeAnalysis.NetAnalyzers.t
argets(593,5): warning : The .NET SDK has newer analyzers with version '8.0.0' than what version '7.0.0' of 'Microsoft.
CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference. [D:\maui-main\src\DotNet
\DotNet.csproj]
C:\Program Files\dotnet\sdk\8.0.100-preview.1.23115.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.Sha
red.targets(152,5): error MSB4062: 未能从程序集 C:\Program Files\dotnet\sdk\8.0.100-preview.1.23115.2\Sdks\Microsoft.NET.Sdk\
targets\..\tools\net8.0\Microsoft.NET.Build.Tasks.dll 加载任务“CheckForImplicitPackageReferenceOverrides”。Could not load fi
le or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 系统找不到指定的文件。 请确认 <Us
ingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。 [D:\maui-main\src\DotNet\Dependen
cies\Workloads.csproj] [D:\maui-main\src\DotNet\DotNet.csproj]
D:\maui-main\src\DotNet\DotNet.csproj(171,5): error MSB3073: 命令“"D:\maui-main\bin/dotnet/dotnet" rest
ore "D:\maui-main\src\DotNet\Dependencies/Workloads.csproj" -bl:D:\maui-main\artifacts/DotNetWorkload
s.binlog”已退出，代码为 1。
    1 个警告
    2 个错误

已用时间 00:00:01.15
```

**Comment by Eilon** [comment]
Hi @SF-Simon , do you have the .NET 7 SDK installed? The 'main' branch of this repo uses .NET 7, but there is a [`net8`](https://github.com/dotnet/maui/tree/net8.0) branch that is mostly the same, but targeting .NET 8.

**Comment by SF-Simon** [comment]
> Hi @SF-Simon , do you have the .NET 7 SDK installed? The 'main' branch of this repo uses .NET 7, but there is a [`net8`](https://github.com/dotnet/maui/tree/net8.0) branch that is mostly the same, but targeting .NET 8.

Hello, @Eilon, I have the SDK with "7.0.201" and "8.0.100-preview. 1.23115.2" installed.
I don't know much about the version requirements of .Net SDK. Should I maintain the latest SDK for each major version, or should each version of the SDK have one to ensure the dependent requirements?

For example, now. Net 8 has released the "Preview. 2" version. Should I delete the "Preview. 1" version? Or must we keep it?

thank.

**Comment by Eilon** [comment]
Hmm then I'm not sure the issue. I'll have to let an expert on this chime in.

**Comment by SF-Simon** [comment]
> 

I don't know why, but it did succeed. I updated VS2022 to version 17.5.2, and then successfully completed the compilation.
I noticed that it automatically uninstalled my original. Net SDK "7.0.201" version.
After the update, no error will be reported after restarting the computer.

But now there is another problem.

```
$ dotnet cake --pack --sln="d:\TestProject.sln" --target=VS  --workloads=global

> Setting environment variable: RestorePackagesPath = 'C:/Users/f1/AppData/Local/Temp/Microsoft.Maui.Cache/NuGet/packages'
> Setting environment variable: NUGET_PACKAGES = 'C:/Users/f1/AppData/Local/Temp/Microsoft.Maui.Cache/NuGet/packages'
```
After I compiled successfully, I opened vs2022. When restoring dependencies in the project, an error occurred, indicating that the library could not be found. 
```
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	NU1102	找不到版本为 (>= 8.0.0-preview.2.7903) 的包严重性	代码	说明	项目	文件	行	禁止显示状态
错误	NU1102	找不到版本为 (>= 8.0.0-preview.2.7903) 的包 Microsoft.Maui.Graphics.Win2D.WinUI.Desktop
  - 在 nuget.org 中找到 27 个版本[ 最接近版本: 8.0.0-preview.2.7871 ]
  - 在 C:\Program Files\dotnet\library-packs 中找到 1 个版本[ 最接近版本: 7.0.59 ]
  - 
 Microsoft.Maui.Controls.Compatibility
  - 在 nuget.org 中找到 5 个版本[ 最接近版本: 8.0.0-preview.2.7871 ]
  - 在 Microsoft Visual Studio Offline Packages 中找到 0 个版本
  - 在 C:\Program Files\dotnet\library-packs 中找到 0 个版本
```

C:\Users\f1\AppData\Local\Temp\Microsoft.Maui.Cache\NuGet\packages

When I open this temporary directory and enter _"C:\Users\f1\AppData\Local\Temp\Microsoft.Maui.Cache\NuGet\packages\microsoft.maui.controls.compatibility"_, I find that it is empty and does not rely on database information. But other libraries get directories, which all have corresponding files.

I appeared under the "net8.0" branch.
