### ISSUE TITLE
Maui Essentials works only on emulator but not real devices

### ISSUE THREAD

**Issue by AhmedHemdan21** [dotnet/maui#1391]
### Steps to Reproduce

1. Create a new Blazor MAUI project
2. Add a page to load contacts
3. Add permission request to AndroidManifest.xml file
3. Deploy to a real device with Android 11
4. Give permission to the applications to read contacts

### Expected Behavior
Load contacts list on real devices and emulators as well

### Actual Behavior
It works perfectly fine on an emulator but, on actual device, the app works but without the native features

### Basic Information

- Version with issue: .NET 6 preview 5
- Last known good version: none
- IDE: VS 2019 16.11.0 Preview 2.0
- Platform Target Frameworks: 
Android 11, Galaxy S21 Ultra

**Comment by Eilon** [comment]
@AhmedHemdan21 can you confirm whether this happens in a regular .NET MAUI project without Blazor? I'm trying to see if there's anything Blazor-specific about this issue (I don't think there is).

**Comment by AhmedHemdan21** [comment]
@Eilon You're totally right, I've created a new regular .NET MAUI project and it worked perfectly fine on both emulator and a real device, so I followed the same exact steps on a newly created MAUI Blazor project and it worked exactly the same. I don't know what has changed but I'm pretty satisfied with the result. Thank you and sorry for wasting your time.

**Comment by Eilon** [comment]
Thank you for the response @AhmedHemdan21 it's no waste of time, we're always happy to hear from people using our products! 😄
