### ISSUE TITLE
[regression/7.0.0] Entry Return command not firing up - .NET MAUI MVVM on Android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#13921]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Entry-Return-command-not-firing-up---NE/10289718)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.4.4]
Hello,
I have another issue - .NET MAUI (using NET 7.0) Entry stops firing up Return command on Android 11 device when HW return key is pressed - device have HW keyboard. Works with Android SW keyboard, but using HW keyboard on device or return key on Vysor remote control doesn't work. 

Sample project files attached.

---
#### Feedback Bot on 2/23/2023, 05:49 PM: 

(private comment, text removed)
#### bohdan on 3/1/2023, 05:05 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### Reproduction
Repro is attached to internal VS ticket

**Comment by bofden** [comment]
Hello,
here is my VS version:


```
Microsoft Visual Studio Professional 2022
Version 17.5.3
VisualStudio.17.Release/17.5.3+33516.290
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

Visual C++ 2022
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.5.318.41597
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.318.41597
Azure App Service Tools v3.0.0

C# Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.5.2.2316603+9f1b6856460af1e592d387ebef416eadddac453f
Provides languages services for ASP.NET Core Razor.

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio File Histories   VSHistory
Maintains the history of all files saved in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.5.41 (ba80d05)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77


Xamarin.iOS and Xamarin.Mac SDK   16.2.0.5 (7738c90c9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```

and this is list of all nuget packages from project cache file:
```
communitytoolkit.mvvm\\8.2.0-preview2\\communitytoolkit.mvvm.8.2.0-preview2.nupkg.sha512",
googlegson\\2.9.1.1\\googlegson.2.9.1.1.nupkg.sha512",
microsoft.extensions.configuration\\7.0.0\\microsoft.extensions.configuration.7.0.0.nupkg.sha512",
microsoft.extensions.configuration.abstractions\\7.0.0\\microsoft.extensions.configuration.abstractions.7.0.0.nupkg.sha512",
microsoft.extensions.dependencyinjection\\7.0.0\\microsoft.extensions.dependencyinjection.7.0.0.nupkg.sha512",
microsoft.extensions.dependencyinjection.abstractions\\7.0.0\\microsoft.extensions.dependencyinjection.abstractions.7.0.0.nupkg.sha512",
microsoft.extensions.logging\\7.0.0\\microsoft.extensions.logging.7.0.0.nupkg.sha512",
microsoft.extensions.logging.abstractions\\7.0.0\\microsoft.extensions.logging.abstractions.7.0.0.nupkg.sha512",
microsoft.extensions.logging.debug\\7.0.0\\microsoft.extensions.logging.debug.7.0.0.nupkg.sha512",
microsoft.extensions.options\\7.0.0\\microsoft.extensions.options.7.0.0.nupkg.sha512",
microsoft.extensions.primitives\\7.0.0\\microsoft.extensions.primitives.7.0.0.nupkg.sha512",
microsoft.graphics.win2d\\1.0.4\\microsoft.graphics.win2d.1.0.4.nupkg.sha512",
microsoft.maui.graphics\\7.0.59\\microsoft.maui.graphics.7.0.59.nupkg.sha512",
microsoft.maui.graphics.win2d.winui.desktop\\7.0.59\\microsoft.maui.graphics.win2d.winui.desktop.7.0.59.nupkg.sha512",
microsoft.windows.sdk.buildtools\\10.0.22621.755\\microsoft.windows.sdk.buildtools.10.0.22621.755.nupkg.sha512",
microsoft.windowsappsdk\\1.2.221209.1\\microsoft.windowsappsdk.1.2.221209.1.nupkg.sha512",
xamarin.android.glide\\4.13.2.2\\xamarin.android.glide.4.13.2.2.nupkg.sha512",
xamarin.android.glide.annotations\\4.13.2.2\\xamarin.android.glide.annotations.4.13.2.2.nupkg.sha512",
xamarin.android.glide.disklrucache\\4.13.2.2\\xamarin.android.glide.disklrucache.4.13.2.2.nupkg.sha512",
xamarin.android.glide.gifdecoder\\4.13.2.2\\xamarin.android.glide.gifdecoder.4.13.2.2.nupkg.sha512",
xamarin.androidx.activity\\1.6.0.1\\xamarin.androidx.activity.1.6.0.1.nupkg.sha512",
xamarin.androidx.activity.ktx\\1.6.0.1\\xamarin.androidx.activity.ktx.1.6.0.1.nupkg.sha512",
xamarin.androidx.annotation\\1.5.0.1\\xamarin.androidx.annotation.1.5.0.1.nupkg.sha512",
xamarin.androidx.annotation.experimental\\1.3.0.1\\xamarin.androidx.annotation.experimental.1.3.0.1.nupkg.sha512",
xamarin.androidx.appcompat\\1.5.1\\xamarin.androidx.appcompat.1.5.1.nupkg.sha512",
xamarin.androidx.appcompat.appcompatresources\\1.5.1\\xamarin.androidx.appcompat.appcompatresources.1.5.1.nupkg.sha512",
xamarin.androidx.arch.core.common\\2.1.0.16\\xamarin.androidx.arch.core.common.2.1.0.16.nupkg.sha512",
xamarin.androidx.arch.core.runtime\\2.1.0.16\\xamarin.androidx.arch.core.runtime.2.1.0.16.nupkg.sha512",
xamarin.androidx.asynclayoutinflater\\1.0.0.15\\xamarin.androidx.asynclayoutinflater.1.0.0.15.nupkg.sha512",
xamarin.androidx.browser\\1.4.0.3\\xamarin.androidx.browser.1.4.0.3.nupkg.sha512",
xamarin.androidx.cardview\\1.0.0.16\\xamarin.androidx.cardview.1.0.0.16.nupkg.sha512",
xamarin.androidx.collection\\1.2.0.5\\xamarin.androidx.collection.1.2.0.5.nupkg.sha512",
xamarin.androidx.collection.ktx\\1.2.0.5\\xamarin.androidx.collection.ktx.1.2.0.5.nupkg.sha512",
xamarin.androidx.concurrent.futures\\1.1.0.10\\xamarin.androidx.concurrent.futures.1.1.0.10.nupkg.sha512",
xamarin.androidx.constraintlayout\\2.1.4.1\\xamarin.androidx.constraintlayout.2.1.4.1.nupkg.sha512",
xamarin.androidx.constraintlayout.core\\1.0.4.1\\xamarin.androidx.constraintlayout.core.1.0.4.1.nupkg.sha512",
xamarin.androidx.coordinatorlayout\\1.2.0.3\\xamarin.androidx.coordinatorlayout.1.2.0.3.nupkg.sha512",
xamarin.androidx.core\\1.9.0.1\\xamarin.androidx.core.1.9.0.1.nupkg.sha512",
xamarin.androidx.core.core.ktx\\1.9.0.1\\xamarin.androidx.core.core.ktx.1.9.0.1.nupkg.sha512",
xamarin.androidx.cursoradapter\\1.0.0.15\\xamarin.androidx.cursoradapter.1.0.0.15.nupkg.sha512",
xamarin.androidx.customview\\1.1.0.14\\xamarin.androidx.customview.1.1.0.14.nupkg.sha512",
xamarin.androidx.documentfile\\1.0.1.15\\xamarin.androidx.documentfile.1.0.1.15.nupkg.sha512",
xamarin.androidx.drawerlayout\\1.1.1.10\\xamarin.androidx.drawerlayout.1.1.1.10.nupkg.sha512",
xamarin.androidx.dynamicanimation\\1.0.0.14\\xamarin.androidx.dynamicanimation.1.0.0.14.nupkg.sha512",
xamarin.androidx.emoji2\\1.2.0\\xamarin.androidx.emoji2.1.2.0.nupkg.sha512",
xamarin.androidx.emoji2.viewshelper\\1.2.0\\xamarin.androidx.emoji2.viewshelper.1.2.0.nupkg.sha512",
xamarin.androidx.exifinterface\\1.3.3.5\\xamarin.androidx.exifinterface.1.3.3.5.nupkg.sha512",
xamarin.androidx.fragment\\1.5.3.1\\xamarin.androidx.fragment.1.5.3.1.nupkg.sha512",
xamarin.androidx.fragment.ktx\\1.5.3.1\\xamarin.androidx.fragment.ktx.1.5.3.1.nupkg.sha512",
xamarin.androidx.interpolator\\1.0.0.15\\xamarin.androidx.interpolator.1.0.0.15.nupkg.sha512",
xamarin.androidx.legacy.support.core.ui\\1.0.0.16\\xamarin.androidx.legacy.support.core.ui.1.0.0.16.nupkg.sha512",
xamarin.androidx.legacy.support.core.utils\\1.0.0.15\\xamarin.androidx.legacy.support.core.utils.1.0.0.15.nupkg.sha512",
xamarin.androidx.legacy.support.v4\\1.0.0.15\\xamarin.androidx.legacy.support.v4.1.0.0.15.nupkg.sha512",
xamarin.androidx.lifecycle.common\\2.5.1.1\\xamarin.androidx.lifecycle.common.2.5.1.1.nupkg.sha512",
xamarin.androidx.lifecycle.livedata\\2.5.1.1\\xamarin.androidx.lifecycle.livedata.2.5.1.1.nupkg.sha512",
xamarin.androidx.lifecycle.livedata.core\\2.5.1.1\\xamarin.androidx.lifecycle.livedata.core.2.5.1.1.nupkg.sha512",
xamarin.androidx.lifecycle.livedata.core.ktx\\2.5.1.1\\xamarin.androidx.lifecycle.livedata.core.ktx.2.5.1.1.nupkg.sha512",
xamarin.androidx.lifecycle.process\\2.5.1\\xamarin.androidx.lifecycle.process.2.5.1.nupkg.sha512",
xamarin.androidx.lifecycle.runtime\\2.5.1.1\\xamarin.androidx.lifecycle.runtime.2.5.1.1.nupkg.sha512",
xamarin.androidx.lifecycle.runtime.ktx\\2.5.1.1\\xamarin.androidx.lifecycle.runtime.ktx.2.5.1.1.nupkg.sha512",
xamarin.androidx.lifecycle.viewmodel\\2.5.1.1\\xamarin.androidx.lifecycle.viewmodel.2.5.1.1.nupkg.sha512",
xamarin.androidx.lifecycle.viewmodel.ktx\\2.5.1.1\\xamarin.androidx.lifecycle.viewmodel.ktx.2.5.1.1.nupkg.sha512",
xamarin.androidx.lifecycle.viewmodelsavedstate\\2.5.1.1\\xamarin.androidx.lifecycle.viewmodelsavedstate.2.5.1.1.nupkg.sha512",
xamarin.androidx.loader\\1.1.0.15\\xamarin.androidx.loader.1.1.0.15.nupkg.sha512",
xamarin.androidx.localbroadcastmanager\\1.1.0.3\\xamarin.androidx.localbroadcastmanager.1.1.0.3.nupkg.sha512",
xamarin.androidx.media\\1.6.0.2\\xamarin.androidx.media.1.6.0.2.nupkg.sha512",
xamarin.androidx.navigation.common\\2.5.2.1\\xamarin.androidx.navigation.common.2.5.2.1.nupkg.sha512",
xamarin.androidx.navigation.fragment\\2.5.2.1\\xamarin.androidx.navigation.fragment.2.5.2.1.nupkg.sha512",
xamarin.androidx.navigation.runtime\\2.5.2.1\\xamarin.androidx.navigation.runtime.2.5.2.1.nupkg.sha512",
xamarin.androidx.navigation.ui\\2.5.2.1\\xamarin.androidx.navigation.ui.2.5.2.1.nupkg.sha512",
xamarin.androidx.print\\1.0.0.15\\xamarin.androidx.print.1.0.0.15.nupkg.sha512",
xamarin.androidx.recyclerview\\1.2.1.7\\xamarin.androidx.recyclerview.1.2.1.7.nupkg.sha512",
xamarin.androidx.resourceinspection.annotation\\1.0.1.2\\xamarin.androidx.resourceinspection.annotation.1.0.1.2.nupkg.sha512",
xamarin.androidx.savedstate\\1.2.0.1\\xamarin.androidx.savedstate.1.2.0.1.nupkg.sha512",
xamarin.androidx.savedstate.savedstate.ktx\\1.2.0.1\\xamarin.androidx.savedstate.savedstate.ktx.1.2.0.1.nupkg.sha512",
xamarin.androidx.security.securitycrypto\\1.1.0-alpha03\\xamarin.androidx.security.securitycrypto.1.1.0-alpha03.nupkg.sha512",
xamarin.androidx.slidingpanelayout\\1.2.0.3\\xamarin.androidx.slidingpanelayout.1.2.0.3.nupkg.sha512",
xamarin.androidx.startup.startupruntime\\1.1.1.2\\xamarin.androidx.startup.startupruntime.1.1.1.2.nupkg.sha512",
xamarin.androidx.swiperefreshlayout\\1.1.0.10\\xamarin.androidx.swiperefreshlayout.1.1.0.10.nupkg.sha512",
xamarin.androidx.tracing.tracing\\1.1.0.2\\xamarin.androidx.tracing.tracing.1.1.0.2.nupkg.sha512",
xamarin.androidx.transition\\1.4.1.8\\xamarin.androidx.transition.1.4.1.8.nupkg.sha512",
xamarin.androidx.vectordrawable\\1.1.0.14\\xamarin.androidx.vectordrawable.1.1.0.14.nupkg.sha512",
xamarin.androidx.vectordrawable.animated\\1.1.0.14\\xamarin.androidx.vectordrawable.animated.1.1.0.14.nupkg.sha512",
xamarin.androidx.versionedparcelable\\1.1.1.15\\xamarin.androidx.versionedparcelable.1.1.1.15.nupkg.sha512",
xamarin.androidx.viewpager\\1.0.0.15\\xamarin.androidx.viewpager.1.0.0.15.nupkg.sha512",
xamarin.androidx.viewpager2\\1.0.0.16\\xamarin.androidx.viewpager2.1.0.0.16.nupkg.sha512",
xamarin.androidx.window\\1.0.0.10\\xamarin.androidx.window.1.0.0.10.nupkg.sha512",
xamarin.google.android.material\\1.7.0\\xamarin.google.android.material.1.7.0.nupkg.sha512",
xamarin.google.crypto.tink.android\\1.7.0.1\\xamarin.google.crypto.tink.android.1.7.0.1.nupkg.sha512",
xamarin.google.guava.listenablefuture\\1.0.0.10\\xamarin.google.guava.listenablefuture.1.0.0.10.nupkg.sha512",
xamarin.jetbrains.annotations\\23.0.0.5\\xamarin.jetbrains.annotations.23.0.0.5.nupkg.sha512",
xamarin.kotlin.stdlib\\1.7.20.1\\xamarin.kotlin.stdlib.1.7.20.1.nupkg.sha512",
xamarin.kotlin.stdlib.common\\1.7.20.1\\xamarin.kotlin.stdlib.common.1.7.20.1.nupkg.sha512",
xamarin.kotlin.stdlib.jdk7\\1.7.20.1\\xamarin.kotlin.stdlib.jdk7.1.7.20.1.nupkg.sha512",
xamarin.kotlin.stdlib.jdk8\\1.7.20.1\\xamarin.kotlin.stdlib.jdk8.1.7.20.1.nupkg.sha512",
xamarin.kotlinx.coroutines.android\\1.6.4.1\\xamarin.kotlinx.coroutines.android.1.6.4.1.nupkg.sha512",
xamarin.kotlinx.coroutines.core.jvm\\1.6.4.1\\xamarin.kotlinx.coroutines.core.jvm.1.6.4.1.nupkg.sha512",
microsoft.windows.sdk.net.ref\\10.0.19041.28\\microsoft.windows.sdk.net.ref.10.0.19041.28.nupkg.sha512",
microsoft.aspnetcore.app.runtime.win-x64\\7.0.4\\microsoft.aspnetcore.app.runtime.win-x64.7.0.4.nupkg.sha512",
microsoft.windowsdesktop.app.runtime.win-x64\\7.0.4\\microsoft.windowsdesktop.app.runtime.win-x64.7.0.4.nupkg.sha512",
microsoft.netcore.app.runtime.win-x64\\7.0.4\\microsoft.netcore.app.runtime.win-x64.7.0.4.nupkg.sha512"

```

**Comment by mconca-kube** [comment]
I am experiencing the exact same problem.
Please note that hardware keyboard used to work correctly in MAUI .Net 6.
I have an app running on .Net 6 that triggers the hw enter key correctly.
When I upgrade the app to .Net 7 (latest stable MAUI version with VS 17.5.4), the hardware keyboard misbehaves (does not trigger Return event and changes active item focus instead).

This is blocking me from upgrading to .Net 7 because I'm developing for an industrial environment that uses handheld devices (like Zebra MC3300 or Honeywell CK65)

**Comment by mconca-kube** [comment]
[TestApp.zip](https://github.com/dotnet/maui/files/11253098/TestApp.zip)

https://user-images.githubusercontent.com/61966672/232552786-343c1925-f886-4ff1-b4e2-ddbe0af3734c.mp4

I uploaded a sample project and a video showing what happens to me

**Comment by marshallellis** [comment]
I am also experiencing this issue with the Honeywell CK65 and the Zebra MC9300 running Android 11. This also creates a difficulty with scanning barcodes with these devices in any warehouse application since these rugged devices with internal barcode scanners typically send an ENTER key after the scan thus moving to the next control. Currently the user must press ENTER manually on the soft keypad after a barcode scan! I am hoping this issue can be bumped up in priority since we cannot deploy with this issue and it is critical that the HW keypad ENTER key function as the soft keypad does! Any help I can provide please let me know...

**Comment by acaliaro** [comment]
> I am also experiencing this issue with the Honeywell CK65 and the Zebra MC9300 running Android 11. This also creates a difficulty with scanning barcodes with these devices in any warehouse application since these rugged devices with internal barcode scanners typically send an ENTER key after the scan thus moving to the next control. Currently the user must press ENTER manually on the soft keypad after a barcode scan! I am hoping this issue can be bumped up in priority since we cannot deploy with this issue and it is critical that the HW keypad ENTER key function as the soft keypad does! Any help I can provide please let me know...

with these devices you should use intents in your app instead of keyboard wedge mode

**Comment by marshallellis** [comment]
That might be a potential work around but that adds complexities of having to deal with intent messages that are formatted and requested differently from each manufacturer. VERY hard to keep up with that! The path of least resistance would be the keyboard wedge since a key event is the same across ALL manufacturers. I believe the hardware keypad should function as the soft keypad. An ENTER key should fire the same events on both!

**Comment by acaliaro** [comment]
yes, but you always need to focus on a text field or view that accepts the keystroke. With intent, you no longer have to care which UI object has focus

**Comment by marshallellis** [comment]
I agree that there are benefits to this low-level control and perhaps in some narrow support situations where being device agnostic is not an issue then go for it! Our situation (As with many others) is that we need to support EVERYBODY! If your app is designed efficiently then focus should not be an issue! Conditional coding for ALL mfgs and ALL devices would be a support nightmare!

Apologies but are you trying to say that the keypads should not operate the same? I cannot debate the merits of your intent usage BUT I am simply wanting both keypads (Soft and Hard) to fire the same events (As they apparently did in 6).

**Comment by bofden** [comment]
I'm using this workaround for now - just call the method in App() constructor and it changes behavior of all "Entry" controls:

```c#
    void ModifyEntry()
    {
        Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
        {
#if ANDROID
            handler.PlatformView.KeyPress += (sender, e) => 
            {
                try
                {
                    if (e.KeyCode.IsInSetOfValues(Android.Views.Keycode.Tab, Android.Views.Keycode.Enter))
                    {
                        e.Handled = true;
                        if ((e.KeyCode == Android.Views.Keycode.Enter) && (e.Event.Action == Android.Views.KeyEventActions.Up))
                        {
                            ((Entry)handler.VirtualView).ReturnCommand?.Execute(((Entry)handler.VirtualView).ReturnCommandParameter);
                        }
                    }
                    else
                        e.Handled = false;
                }
                catch (Exception E) 
                {
                    //log exception...
                }
            };
#endif
        });
    }
```

**Comment by marshallellis** [comment]
bofden:

Thanks a ton for that code! Testing it now and it seems to be a good work around! Good Stuff!
I need to dig more into these types of capabilities. Still learning...

Thank you

Marshall

**Comment by Simoneye1011** [comment]
@bofden where you write ModifyEntry()?do we need dependency service --like render?

**Comment by bofden** [comment]
> @bofden where you write ModifyEntry()?do we need dependency service --like render?

You shoudn't need anything - this method is just adding/changing behavior of already defined mappings between MAUI Entry and Android TextEdit.

**Comment by Simoneye1011** [comment]
Error	CS1061	'Keycode' does not contain a definition for 'IsInSetOfValues' and no accessible extension method 'IsInSetOfValues' accepting a first argument of type 'Keycode' could be found (are you missing a using directive or an assembly reference?)

**Comment by Simoneye1011** [comment]
> 



> > @bofden where you write ModifyEntry()?do we need dependency service --like render?
> 
> You can put it in App.xaml.cs, you shoudn't need anything - this method is just adding/changing behavior of already defined mappings between MAUI Entry and Android TextEdit.

whether you are running in xamarin,but i copy your code ,there is error here

**Comment by bofden** [comment]
> but unfortunally，there cant access keypress,but there are keydown,i want do some work like this Entry myEntry = sender as Entry; myEntry.CursorPosition = 0; myEntry.SelectionLength = myEntry.Text != null ? myEntry.Text.Length : 0; ((MainPageViewModel) BindingContext).ScanCommand.Execute(null); do you have ideal?

For this case it's probably the best idea to create your own "MyEntry" control derived from Entry with new "KeyPress" event you can call in your code.

> Error CS1061 'Keycode' does not contain a definition for 'IsInSetOfValues' and no accessible extension method 'IsInSetOfValues' accepting a first argument of type 'Keycode' could be found (are you missing a using directive or an assembly reference?)

IsInSetOfValues is my extension, of course - you can use something like this: (e.KeyCode == Android.Views.Keycode.Tab || e.KeyCode == Android.Views.Keycode.Enter))


That workaround is obviously for Android only as you can see by the compiler directive... I have no issue running this code in .NET 7 MAUI; it will probably work in .NET 6 MAUI as well, but it seems you don't need it there anyway and most likely it wouldn't work on older Xamarin Forms.

**Comment by Simoneye1011** [comment]
@bofden THANKS,DO YOU KNOW SOME WHERE WE COULD TALK ABOUT TECHNOLOGY,NOT UES COMMENT,ITS SLOW FOR RESPON

**Comment by energywave** [comment]
> I'm using this workaround for now - just call the method in App() constructor and it changes behavior of all "Entry" controls:

Thank you @bofden you saved my life! I'm using an Athesi AP5705S device and the scan wedge app is sending the enter key after the barcode (that wasn't catched by MAUI) so your code saved the ugly workaround that I did before (using a code suffix and detecting it in a derived Entry class)!

I just wanted to improve it with this code with two changes:
- static method
- call the Entry hidden method SendCompleted() instead of calling ReturnCommand as that method will do that plus fire the Completed event (that I'm using). Hope that can be useful to someone.

```cs
    static void ModifyEntry()
    {
        Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
        {
#if ANDROID
            handler.PlatformView.KeyPress += (sender, e) => 
            {
                try
                {
                    if (e.KeyCode == Android.Views.Keycode.Tab || e.KeyCode == Android.Views.Keycode.Enter)
                        {
                        e.Handled = true;
                        if ((e.KeyCode == Android.Views.Keycode.Enter) && (e.Event.Action == Android.Views.KeyEventActions.Up))
                        {
                            //((Entry)handler.VirtualView).ReturnCommand?.Execute(((Entry)handler.VirtualView).ReturnCommandParameter);
                            ((Entry)handler.VirtualView).SendCompleted();
                        }
                    }
                    else
                        e.Handled = false;
                }
                catch (Exception ex) 
                {
                    GlobalModule.ElabEx("Errore gestione tasti ENTER/TAB", ex);
                }
            };
#endif
        });
    }

```

**Comment by harveytriana** [comment]
Hopefully that MAUI .NET 7 BUG will be fixed. Another bug behavior is that when the keyboard appears, it scrolls the screen up abnormally, and it repositions correctly when hiding the virtual keyboard. In MAUI .NET 6 we don't have that ugly behavior.

If I didn't make myself understood, you can expand the description with an example.

**Comment by vguerin533** [comment]
Got this issue as well on a HW ck65 only on physical keyboard

**Comment by MarcoTrombetta** [comment]
> > I'm using this workaround for now - just call the method in App() constructor and it changes behavior of all "Entry" controls:
> 
> Thank you @bofden you saved my life! I'm using an Athesi AP5705S device and the scan wedge app is sending the enter key after the barcode (that wasn't catched by MAUI) so your code saved the ugly workaround that I did before (using a code suffix and detecting it in a derived Entry class)!
> 
> I just wanted to improve it with this code with two changes:
> 
>     * static method
> 
>     * call the Entry hidden method SendCompleted() instead of calling ReturnCommand as that method will do that plus fire the Completed event (that I'm using). Hope that can be useful to someone.
> 
> 
> ```cs
>     static void ModifyEntry()
>     {
>         Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
>         {
> #if ANDROID
>             handler.PlatformView.KeyPress += (sender, e) => 
>             {
>                 try
>                 {
>                     if (e.KeyCode == Android.Views.Keycode.Tab || e.KeyCode == Android.Views.Keycode.Enter)
>                         {
>                         e.Handled = true;
>                         if ((e.KeyCode == Android.Views.Keycode.Enter) && (e.Event.Action == Android.Views.KeyEventActions.Up))
>                         {
>                             //((Entry)handler.VirtualView).ReturnCommand?.Execute(((Entry)handler.VirtualView).ReturnCommandParameter);
>                             ((Entry)handler.VirtualView).SendCompleted();
>                         }
>                     }
>                     else
>                         e.Handled = false;
>                 }
>                 catch (Exception ex) 
>                 {
>                     GlobalModule.ElabEx("Errore gestione tasti ENTER/TAB", ex);
>                 }
>             };
> #endif
>         });
>     }
> ```

Thanks a lot, i was losing my mind with this, since it's still not fixed in MAUI .NET 8.0

**Comment by mconca-kube** [comment]
Do we have any updates from Microsoft on this. Wasn't this going to be fixed in .Net 8 GA?
I need to start new projects and I would like to use Maui, but this is really painful to see bugs like this after 2 major releases and several months of waiting. I really don't understand if Microsoft is working on making this product good to use. Please give us some updates on this
