### ISSUE TITLE
[Bug] Bindable Layout Doesn't Update when ItemsSource Changes

### ISSUE THREAD

**Issue by matt-goldman** [dotnet/maui#1393]
### Description
When using BindableLayout, the screen should update when the ItemsSource that the layout is bound to changes. For example, when using an ObservableCollection, adding or removing items from the collection should result in the content of the bindable layout changing. And equally, when adding or removing items from a list, the content of the bindable layout should change when PropertyChanged is invoked on that list.

However, in both cases the content does not update. Setting the source to new (e.g. `MyList = new List<MyModel>()` and same with ObservableCollection) and then adding items doesn't give the expected result either.

The binding works initially - if the list or collection is given an initial set of values, these are displayed. But updating them does not cause the screen to update.

### Steps to Reproduce

1. Add a bindable layout
2. Set the ItemsSource of the bindable layout to a list or collection in your view model
3. Update the list or collection
4. Raise PropertyChanged if necessary

### Expected Behavior
The content of the bindable layout should change to reflect changes in the item source.

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: 6.0.100-preview.5.794
- Last known good version: NA (Xamarin.Forms)
- IDE: Visual Studio 2019 16.11.2 Preview 2.0
- Platform Target Frameworks: 
  - iOS:  
  - Android: 30
  - UWP:   
- Affected Devices: Pixel 2 (emulated)

### Reproduction Link

https://github.com/matt-goldman/maui-bindable-test

### Workaround

None found.

**Comment by matt-goldman** [comment]
Just to be extra sure, I forked @davidortinau 's Weather TwentyOne, and on the Favorites page, I took the Fetch method out of the constructor and called it with a command from a button instead. Same issue - looks like you can't update a BindableLayout source after init. This is a shame given that the CollectionView/ListView is not ready yet. Repo is here: https://github.com/matt-goldman/WeatherTwentyOne

As a workaround, I tried embedding BindableLayout in a view and then newing the source, re-adding values and then raising property changed. See updated example on my bindable test repo (linked in original comment) on the test-embedded-view branch for an example. This also didn't work.

Not sure if this is something that hasn't been implemented yet or an actual bug. If it's an actual bug, seems pretty severe.

**Comment by aidanwallace7** [comment]
Can confirm I have experienced the same issue. Had to write my own ItemsSource for a grid to do any dynamic updates. Hope this one gets picked up soon

**Comment by shimingsg** [comment]
verified with VS 17.2.0 Preview 2.0 [32228.609.main],
ObservableCollection works but List doesn't:
![1393](https://user-images.githubusercontent.com/20982341/156329481-f4b28c6f-1b10-4805-a1da-fd9f5b80ea59.gif)

demo: 
[1393.zip](https://github.com/dotnet/maui/files/8168158/1393.zip)

**Comment by Redth** [comment]
This is fixed in the upcoming RC1 release.

![image](https://user-images.githubusercontent.com/271950/161123554-b93df3c8-fc0c-41fd-a4dd-e46065632d08.png)
