### ISSUE TITLE
Button, switch

### ISSUE THREAD

**Issue by MForce01** [dotnet/maui#13949]
### Description

When we use Button's ContentLayout with parameters (Top, (any number)), every time we connect to the program, it does not understand the given parameter, it is enough to touch the parameter while it is connected, it will confirm it.

The same problem applies to OnColor, ThumbColor of switch.

Thank you.

### Steps to Reproduce

When we use Button's ContentLayout with parameters (Top, (any number)), every time we connect to the program, it does not understand the given parameter, it is enough to touch the parameter while it is connected, it will confirm it.

The same problem applies to OnColor, ThumbColor of switch.

Thank you.

### Link to public reproduction project repository

no have

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 12 with Pixel 5

**Comment by Eilon** [comment]
@MForce01 I'm not sure I understand what you mean by "touch" or "connect". Can you show any relevant code, errors, screenshots, or even a video recording of the problem?
