### ISSUE TITLE
HorizontalOptions squish a button

### ISSUE THREAD

**Issue by chabiss** [dotnet/maui#13941]
### Description

HorizontalOptions break button rendering

### Steps to Reproduce

Just put the markup below                  
```
<Button
                    Text="Button"
                    HorizontalOptions="Center"/>
```

The button will be squished
![image](https://user-images.githubusercontent.com/14151258/225157149-e195d4b7-3857-4efe-a8b6-4c5b365faac1.png)

This is a regression in main

### Link to public reproduction project repository

http://open_the_default_template

### Version with bug

8.0 previews

### Last version that worked well

7.0 (current)

### Affected platforms

Windows

### Affected platform versions

10.0.22000.194

### Did you find any workaround?

No

### Relevant log output

```shell
No need
```

**Comment by hartez** [comment]
It's an unfortunate side effect of #10759. We'll need to revert that commit and have another look at the problem.
