### ISSUE TITLE
switch and underline

### ISSUE THREAD

**Issue by MForce01** [dotnet/maui#13950]
### Description

It is illogical that the switch does not have the ability to Command to work with MVVM.

The line between Entry and Editor is illogical. Which is stubbornly impossible to remove. Either create a feature or I'll move to DevExpress. Where all the provided tools are absolutely free.

### Public API Changes

It is illogical that the switch does not have the ability to Command to work with MVVM.

The line between Entry and Editor is illogical. Which is stubbornly impossible to remove. Either create a feature or I'll move to DevExpress. Where all the provided tools are absolutely free.

### Intended Use-Case

It is illogical that the switch does not have the ability to Command to work with MVVM.

The line between Entry and Editor is illogical. Which is stubbornly impossible to remove. Either create a feature or I'll move to DevExpress. Where all the provided tools are absolutely free.

**Comment by Eilon** [comment]
@MForce01 - can you show an example of what code you'd like to be able to write, and what it would do? A new property on a control?
