### ISSUE TITLE
Border Left and Right Margins Dont work on iOS, works well on Android

### ISSUE THREAD

**Issue by planyazilim** [dotnet/maui#13965]
### Description

In CollectionView
Border Left and Right Margins Dont work on iOS, works well on Android

### Steps to Reproduce

                    <DataTemplate>
                        <Border  Margin="20,20,20,20" Padding="15,6,15,6" Background="White" Stroke="#237073" 
                            StrokeShape="RoundRectangle 10,10,10,10" StrokeThickness="3">
                                <Label  Text="{Binding Kat_ismi}" TextColor="#237073" VerticalTextAlignment="Center" />
                        </Border>
                    </DataTemplate>

### Link to public reproduction project repository

In CollectionView Border Left and Right Margins Dont work on iOS, works well on Android

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

Yes, if I add a VerticalStackLayout and give Margin, and put Border inside this stacklayout it works.

                    <DataTemplate>
                        <VerticalStackLayout Margin="0,0,0,0">
                        <Border  Padding="15,6,15,6" Background="White" Stroke="#237073" 
                            StrokeShape="RoundRectangle 10,10,10,10" StrokeThickness="3">
                                <Border.Margin>
                                    <OnPlatform x:TypeArguments="Thickness">
                                        <On Platform="iOS" Value="10,4,10,2" />
                                        <On Platform="Android" Value="10,0,10,0" />
                                    </OnPlatform>
                                </Border.Margin>
                                <Label 
                                Style="{DynamicResource LargeL}"
                                Text="{Binding Kat_ismi}"
                                TextColor="#237073"
                                VerticalTextAlignment="Center" />
                        </Border>
                        </VerticalStackLayout>
                    </DataTemplate>

### Relevant log output

```shell
Yes, if I add a VerticalStackLayout and give Margin, and put Border inside this stacklayout it works
```

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on iOS platform with above code.
![Screenshot 2023-06-20 164823](https://github.com/dotnet/maui/assets/77434865/8c000a30-caca-4fd3-a502-b3fc81165932)
![Screenshot 2023-06-20 165519](https://github.com/dotnet/maui/assets/77434865/88566aa5-d1a2-4e93-9f86-007b70a634ca)
