### ISSUE TITLE
RadioButton TextColor Doesnt work on iOS it is always black, works well on Android

### ISSUE THREAD

**Issue by planyazilim** [dotnet/maui#13964]
### Description

RadioButton TextColor Doesnt work on iOS it is always black, works well on Android

### Steps to Reproduce

<RadioButton  Grid.Row="0"  Grid.Column="0" TextColor="#237073"  FontSize="Medium"                         CheckedChanged="MesajTurChanged"  Content="Gelen"   GroupName="MesajTur"   IsChecked="true"   />

### Link to public reproduction project repository

<RadioButton  Grid.Row="0"  Grid.Column="0" TextColor="#237073"  FontSize="Medium"                         CheckedChanged="MesajTurChanged"                         Content="Gelen"                          GroupName="MesajTur"                         IsChecked="true"                          />

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

no

### Relevant log output

```shell
<RadioButton x:Name="Gelen"
                        Grid.Row="0"
                        Grid.Column="0" FontSize="Medium"
                        CheckedChanged="MesajTurChanged"
                        Content="Gelen" 
                        GroupName="MesajTur"
                        IsChecked="true"
                        TextColor="#237073" />
```

**Comment by dustin-wojciechowski** [comment]
Thank you for filing this issue. This was addressed recently in PR #13215 :)
