### ISSUE TITLE
This is definitely an issue

### ISSUE THREAD

**Issue by noteilon** [dotnet/maui#13967]
And I am definitely not Eilon.

**Comment by Eilon** [comment]
Hi definitely-not-Eilon, please try the latest version, ok?

**Comment by noteilon** [comment]
Oh hi again it's me, who is definitely not you, and I would like to let you know the latest version is fabulous.

**Comment by Eilon** [comment]
Cool, so I'm closing this issue. Thanks definitely-not-me for reporting this issue.
