### ISSUE TITLE
Color.Equals() returns true for Colors with small difference 

### ISSUE THREAD

**Issue by XceedBoucherS** [dotnet/maui#13968]
### Description

Color.Equals() return true when 2 colors have a small difference. If we take the Red property of the Color as an example : 
R = 0.521 and R = 0.525, 
This will return equals Red because the difference is less than 0.01 and less than 0.01 are considered equal in the Color.Equals() override method !
Why ?

### Steps to Reproduce

var color1 = new Color( 0.521f, 0, 0 );
var color2 = new Color( 0.525f, 0, 0 );
var result = color1.Equals( color2 );

result is True. 
result should be false.

### Link to public reproduction project repository

none

### Version with bug

8.0 previews

### Last version that worked well

unknown

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by Eilon** [comment]
It's clearly deliberate, but I have no idea why. Here's the code: https://github.com/dotnet/maui/blob/main/src/Graphics/src/Graphics/Color.cs#L113

And nothing else ever seems to pass in a different value for epsilon, so it always compares to within 0.01f.

**Comment by drasticactions** [comment]
It was introduced in https://github.com/dotnet/Microsoft.Maui.Graphics/pull/76/files#diff-22908ddaf46e102ad48fd7492ff2113cc224e324878f7c86802e8c01a3fe79b3, and ported into MAUI when that code moved here.

The PR doesn't mention the reasons, and I'm not sure its other code calls for "Color.Equals" to invoke it. @Redth do you remember why?

**Comment by pictos** [comment]
@XceedBoucherS right now you can create your own `ColorComparer` and use it to compare colors. Here's [an sample](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYAMBYAUBgRj1UwAJUCAWAbmLIoDoARASwEMBzKAewGdgWAY14MAwtzgBTAIJQ2AGwCevFr1q5iBAJwAKAESAeDcAg+3oCU6vHgBubMKUHd53MAVIBeUlEkB3UuKdgOqSYDACs6AQAZjDBMWTm1rb2js7o7p4+fimBwWHoodGxwaQJuDZ2YJK8EPLA6Q4BBAwAogCOEAq8QQ2pJRYaZUkOALYADraSdh5evv7O4mMTgaWJFfXci5VgLe2dOj0uMQfopRS6YKVTyZuTOx3yXQcER9kEp9o6F/3EaXNgC+MtqQQKQAJJte4sYCKAFLAA8fwAfHgAN54UgY8gAZlIACNuI5SBC9n8APykAAeMTJpEUpnRmLRuExLNILEipB0FLZvE8NXkpGQyFpPL58nkpnIAHZSJFOpJ1CyGazpZyKQxpPJRgALNgxdUAIXkEEk+oYACVJHAzQBxSqSKCStweHSKDVa3UxN1Gk1ei1Wv12yQO0osgC+lmZmNQOJYUDqNskwAAEmxeNrxFIdABtVi8BRObwAOX5AF0sgFSNxcQArelRjFMlUY1AynTVmvunV6qu1/3W3udn2mwcMIMhsdJ1PpzOSHShzER3BLyMYCvOVHK7GypxsOqWuCkFEcJPUXinpcsmM77h70jjqBHk/AM8XrfXyK7urDp+n88vy9oxxT9bzqTVu1/F9/2oQCMXfHE/nnLcm2bLdYNIeD10CEC70qAccLqDh7VgG871xY0RwI0gFAgjxMEiesWRQlUD3SPDFWbB90iI4MoA4lUfw8ciTX41lwN1dIaN1USVwGK8cW4KxJjAFgpDxAkBWJB521rSRBGAckO0YxktxZdlOQ7UU/irYBtUmesAEgnIc1tSCLSRbCULSdAPGJuFs24D0c5yHIAMlCtyPLALzdnkHQHz8gLtgfYLnPCyLPMUbzh0SuztmHVKnPS9zMu88Se38vKu11FZcGc1zcTTSQ7j2IyZMjeSqyUsAVLUuMEynNMMwkOdjMbUzoxlRrz0nFMhtned2rk6MCAANnUwkSuirLYp0KjImeUi6kidAYioyRRhUJxHzohhMCiVK3ERUgAFk921DVcS6A7SAAWllE5SDhUgLqu7g+MjMMgA===)

**Comment by XceedBoucherS** [comment]
Thank you for the workaround @pictos
