### ISSUE TITLE
[Enhancement] IQKeyboardManager

### ISSUE THREAD

**Issue by angelru** [dotnet/maui#1396]
## Summary
It would be nice if MAUI on iOS had a configuration option like the one on Android so the keyboard doesn't overlap entry

## API Changes

https://github.com/hackiftekhar/IQKeyboardManager (Swift)
https://github.com/asklyking/KeyboardOverlapRenderer (Xamarin)

**Comment by mattleibow** [comment]
I believe this is now fixed in .NET 8. @tj-devel709 did the work for .NET 8 and @PureWeen has a few fixes in his NuGet? Or is it in the community toolkit?

**Comment by angelru** [comment]
no veo nada relacionado en https://learn.microsoft.com/es-es/dotnet/communitytoolkit/maui/extensions/keyboard-extensions
