### ISSUE TITLE
Set Focus on custom control

### ISSUE THREAD

**Issue by XceedBoucherS** [dotnet/maui#13969]
### Description

Call CustomControl.Focus() returns false. How set focus on a custom control, which derives from TemplatedView ?
 Calling Control.Focus() on
  -Entry (returns true)
  -Label (returns false)
  -Maui Button (returns true) 
  -My custom Control (returns false)

### Steps to Reproduce

Create a custom control, which derives from TemplatedView.

In XAML, add:
<local:MyCustomControl x:Name="_myCustomControl"/>
<Entry />
<Button Text="TEST" Click="OnClick"/>

In the OnClick() callback, do:
var result = _myCustomControl.Focus;

When running, 
-click on Entry control (focus is in Entry)
-click on the Button

Result: the "result" variable should be true. But it's always false.

How can we set focus on a custom control ?

### Link to public reproduction project repository

none

### Version with bug

8.0 previews

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by PureWeen** [comment]
@XceedBoucherS this is going to differ a bit platform to platform. For example, with you can't set a label or a layout to be focused because these are focusable elements. In order to make them focusable you have to set properties at the platform level to make them focusable.
