### ISSUE TITLE
[Question] What is the intended way that namespaces in platform-specific folder work?

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#13972]
### Description

Create a new .NET MAUI app.

See classes in Platform/Android. They have root project namespace (e.g. MauiApp1)
Create new class in Platform/Android. It has folder-structure-based namespace (e.g. MauiApp1.Platforms.Android).
It looks like the default behavior for generating namespaces has changed for MAUI projects in Visual Studio.

With the second behavior, classes like these will no longer compile when placed in Platforms/Android where they belong:

```
public class BluetoothLEPermissions : Permissions.BasePlatformPermission
    {
        public override (string androidPermission, bool isRuntime)[] RequiredPermissions
        {
            get
            {
                return new List<(string androidPermission, bool isRuntime)>
            {

                (Android.Manifest.Permission.Bluetooth, true),
                (Android.Manifest.Permission.BluetoothAdmin, true),
                (Android.Manifest.Permission.BluetoothScan, true),
                (Android.Manifest.Permission.BluetoothConnect, true),
                (Android.Manifest.Permission.AccessFineLocation, true),
                (Android.Manifest.Permission.AccessCoarseLocation, true),
                //(Android.Manifest.Permission.AccessBackgroundLocation, true),

            }.ToArray();
            }
        }
    }
```

Source: https://github.com/TimoKinnunen/MauiXAMLBluetoothLE

![image](https://user-images.githubusercontent.com/64279914/225460943-f3d65ce2-a825-4fa6-80b8-90222587632b.png)

The namespaces to folder-based structure will be adjusted as well when you click Sync Namespaces in VS.

### Steps to Reproduce

mentioned in the desscription

### Link to public reproduction project repository

https://github.com/TimoKinnunen/MauiXAMLBluetoothLE

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

all

> VS bug [#1774548](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1774548)

**Comment by Eilon** [comment]
I end up just keeping `Platforms` in the name because it's easier to go with whatever VS suggests. I haven't tried the new Sync Namespaces feature, but when I looked up info on it, I couldn't find any options to configure it or alter its behavior in certain folders.

**Comment by janseris** [comment]
> I end up just keeping `Platforms` in the name because it's easier to go with whatever VS suggests. I haven't tried the new Sync Namespaces feature, but when I looked up info on it, I couldn't find any options to configure it or alter its behavior in certain folders.

OK when you do this then there is the conflict I mentioned and the default project template is configured the other way which I think is good.
Sync namespaces will be also used when you want to change project name (real use case).

**Comment by Eilon** [comment]
Oh I see the problem now: because there's already another namespace `Android.*`, you get the error? If you (or anyone) is blocked by it, you could reference the types via `global::Android.Whatever` to force a top-level namespace lookup. But that certainly isn't pretty.
