### ISSUE TITLE
XAML Hot Reload is broken within Shell.TitleView

### ISSUE THREAD

**Issue by spadapet** [dotnet/maui#13992]
### Description

XAML hot reload just doesn't work within Shell.TitleView.

### Steps to Reproduce

**REPRO:**

1. In VS, create new blank MAUI app
    ![image](https://user-images.githubusercontent.com/2523431/225689310-2f6f6337-85ce-4f7b-991d-b63cb06b5beb.png)
2. Open AppShell.xaml and set the TitleView property with something:
    ```
    <Shell.TitleView>
        <Label Text="Hello Title!" />
    </Shell.TitleView>
    ```
3. F5 to build and debug your app. notice the new title:
    ![image](https://user-images.githubusercontent.com/2523431/225689810-b92230d2-451e-44c6-93da-ab806a4c59e2.png)
4. Change anything in the TitleView, like the Label's text:
    ```
    <Shell.TitleView>
        <Label Text="Hot Reload Title!" />
    </Shell.TitleView>
    ```

**RESULT:**
XAML changes are _not_ hot reloaded into the running app (of course make sure XAML hot reload is enabled)

**EXPECT:**
XAML changes in Shell.TitleView should be hot reloaded and affect the running app

### Link to public reproduction project repository

N/A use blank template

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

net7.0-windows10.0.19041.0, net7.0-android21.0

### Did you find any workaround?

No, have to restart the app :(

**Comment by drasticactions** [comment]
Notes: If you remove and reapply the TitleView element whole, it will update.

This also isn't specific to Shell, it happens on NavigationView.TitleView as well. Maybe the nested-ness of how it's laid out causes XAML Actions to not be generated?

**Comment by drasticactions** [comment]
Ahhh, I think I know why:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/898335/225825678-6575a031-cdb0-42b5-8d3e-fb98068210d6.png">

TitleView is not represented in as part of the child of the page. We're therefore not able to track it in LVT, so we can't generate actions for it. We'll need to get that represented in MAUI for those changes to be seen.
