### ISSUE TITLE
Elements in ColumnDefinition with star width are not displayed when the Grid is in a StackLayout

### ISSUE THREAD

**Issue by dilyantraykov** [dotnet/maui#13993]
### Description

Consider the following layout:

```
<StackLayout>
    <Grid ColumnDefinitions="Auto, *">
        <Rectangle />
        <Label Grid.Column="1" Text="Label" />
    </Grid>
</StackLayout>
```

The Label is not displayed when using the unofficial version from the [release/7.0.2xx](https://github.com/dotnet/maui/tree/release/7.0.2xx) branch.

For comparison, the Label is displayed as expected with version `7.0.59`.

Most probably the issue occurs due to the following change: [#13395](https://github.com/dotnet/maui/pull/13395)

### Steps to Reproduce

1. Run the project from the referenced reproduction repository.

**Expected Behavior**: The Label defined in XAML is displayed as expected.
**Actual Behavior**: The Label is not displayed.

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/IncorrectGridMeasurement

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Windows SDK 10.0.19041.0, Android 33

**Comment by PureWeen** [comment]
@hartez thoughts?
