### ISSUE TITLE
MAUI Template not showing up in VS 17.5.2

### ISSUE THREAD

**Issue by JerryWatsonJr** [dotnet/maui#14001]
After updating to 17.5.2 my maui projects will not open. When try to create a new solution the maui template does not show. I am using Windows 10.
![Untitled-1](https://user-images.githubusercontent.com/112991575/225789689-bb049482-60f7-4fda-9ced-c7ae111cc04d.jpg)
![Untitled-2](https://user-images.githubusercontent.com/112991575/225789716-a7de1670-0f75-4e3e-9d6c-0b247219af55.jpg)

**Comment by drasticactions** [comment]
If you go to your CLI and type `dotnet new --list` do you see the MAUI templates? If not, can you run `dotnet workload install maui`?

**Comment by JerryWatsonJr** [comment]
I get the following error:

![Untitled-3](https://user-images.githubusercontent.com/112991575/225884550-c2dff3ce-eba1-4f54-8921-37e71cebcd36.jpg)

**Comment by JerryWatsonJr** [comment]
![Untitled-3](https://user-images.githubusercontent.com/112991575/225884985-fc9d602d-309d-4a07-9450-7068b9f7a268.jpg)

**Comment by Vikas8881** [comment]
did you try to update the window?

**Comment by jfversluis** [comment]
The error is very strange with the workload install, but it seems the workload is installed. Could you try to just to `dotnet new install Microsoft.Maui.Templates`? That should only install the templates and also make them show up in Visual Studio.

**Comment by JerryWatsonJr** [comment]
> 

I have wasted enough time. I just changed to 17.4.2 and everything works. Thanks

**Comment by AndreasReitberger** [comment]
@JerryWatsonJr 
I also had this issue. I figured out that there where two dotnet version listed in my environment variables somehow after the update.
There I deleted the entry leading to the `Program Files (x86)`. After that, VS took the right SDK and it was working again.
Maybe it helps you as well ;)

**Comment by JerryWatsonJr** [comment]
> @JerryWatsonJr I also had this issue. I figured out that there where two dotnet SDK path version listed in my environment variables somehow after the update. There I deleted the entry leading to the `Program Files (x86)`. After that, VS took the right SDK and it was working again. Maybe it helps you as well ;)

I do not have two, only Program Files (not x86). Thanks anyway.

**Comment by JerryWatsonJr** [comment]
> 


PS C:\WINDOWS\system32> dotnet new install Microsoft.Maui.Templates
The following template packages will be installed:
   Microsoft.Maui.Templates

Error: Failed to retrieve template packages from provider 'Optional workloads'.
Details: Invalid numeric identifier: '300_bak'.
Error: Failed to retrieve template packages from provider 'Optional workloads'.
Details: Invalid numeric identifier: '300_bak'.
Success: Microsoft.Maui.Templates::6.0.312 installed the following templates:
Template Name                     Short Name        Language  Tags
--------------------------------  ----------------  --------  ---------------------------------------------------------
.NET MAUI App                     maui              [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Tizen
.NET MAUI Blazor App              maui-blazor       [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Tizen/Blazor
.NET MAUI Class Library           mauilib           [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Tizen
.NET MAUI ContentPage (C#)        maui-page-csharp  [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code
.NET MAUI ContentPage (XAML)      maui-page-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code
.NET MAUI ContentView (C#)        maui-view-csharp  [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code
.NET MAUI ContentView (XAML)      maui-view-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code
.NET MAUI ResourceDictionary ...  maui-dict-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code

Error: Failed to retrieve template packages from provider 'Optional workloads'.
Details: Invalid numeric identifier: '300_bak'.

**Comment by JerryWatsonJr** [comment]
> PS C:\WINDOWS\system32> dotnet new install Microsoft.Maui.Templates The following template packages will be installed: Microsoft.Maui.Templates
> 
> Error: Failed to retrieve template packages from provider 'Optional workloads'. Details: Invalid numeric identifier: '300_bak'. Error: Failed to retrieve template packages from provider 'Optional workloads'. Details: Invalid numeric identifier: '300_bak'. Success: Microsoft.Maui.Templates::6.0.312 installed the following templates: Template Name Short Name Language Tags
> 
> .NET MAUI App maui [C#] MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Tizen .NET MAUI Blazor App maui-blazor [C#] MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Tizen/Blazor .NET MAUI Class Library mauilib [C#] MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Tizen .NET MAUI ContentPage (C#) maui-page-csharp [C#] MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code .NET MAUI ContentPage (XAML) maui-page-xaml [C#] MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code .NET MAUI ContentView (C#) maui-view-csharp [C#] MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code .NET MAUI ContentView (XAML) maui-view-xaml [C#] MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code .NET MAUI ResourceDictionary ... maui-dict-xaml [C#] MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
> 
> Error: Failed to retrieve template packages from provider 'Optional workloads'. Details: Invalid numeric identifier: '300_bak'.

**Comment by jfversluis** [comment]
As also communicated per email:

Seems like you’re made a backup just to be sure in that folder. Which is a very wise thing to do! But in this case that breaks it. Notice how it says it tries to make a numeric identifier from 300_bak which is obviously not an integer 😊

Either rename that back, delete the folder, or use the safest option and move the folder outside of that folder.
