### ISSUE TITLE
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

### ISSUE THREAD

**Issue by Darkatek7** [dotnet/maui#1400]
### Steps to Reproduce

1.  Create a new Dot Net Blazor Project
2.  Run the winui package

### Expected Behavior
run the project

### Actual Behavior
The Project doesn't start because of the following error:
![image](https://user-images.githubusercontent.com/50767771/122820899-6f7c7e80-d2dc-11eb-85a1-9643e9d1258d.png)

### Basic Information

- Version with issue: Visual Studio preview 16.11 preview 2
- Last known good version: Visual Studio preview 16.11 preview 1
- IDE: Visual Studio 
- Platform Target Frameworks: 
- Windows

**Comment by Darkatek7** [comment]
thats all I get
![image](https://user-images.githubusercontent.com/50767771/122881052-011ad900-d33b-11eb-9dc6-1deda3e23e25.png)

**Comment by Eilon** [comment]
@Darkatek7 can you check if you have the [Microsoft Edge WebView2 installer](https://developer.microsoft.com/microsoft-edge/webview2/) installed?

Also, if you right-click on the `[External Code]` item in the call stack you can configure VS to _show_ the external code, and then you can see a lot more info. If you see this again, that info would be helpful.

**Comment by Dreamescaper** [comment]
I had exactly the same issue with the same stacktrace when I tried to run the app without launchSettings.json and "Windows Machine" profile.

**Comment by jfversluis** [comment]
Hey everyone, thanks for the report! It seems this issue is from a while ago and I assume (hope?) that this is fixed in the meantime with the newer previews. Closing this for now. If this is still a problem please ping us here or feel free to open a new issue. Thanks!
