### ISSUE TITLE
MAUI template does not available on visual studio 2022 for mac

### ISSUE THREAD

**Issue by nrakurniawan** [dotnet/maui#14017]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: macos Ventura 13.2.1

<img width="916" alt="Screenshot 2023-03-18 at 1 05 07" src="https://user-images.githubusercontent.com/55402943/225959869-9c18786c-c8e3-4b6c-9568-1c78269e975c.png">

When creating a multiplatform app, I can not choose MAUI template from Visual Studio 2022 for Mac (version 17.5.2).

**Comment by jfversluis** [comment]
Hey @nrakurniawan thanks for trying out .NET MAUI! Sorry that's happening.

I assume you did check the .NET MAUI workload when installing?

You can still get the templates by opening a terminal and using this command: `dotnet new install Microsoft.Maui.Templates`. That should also make them show up in Visual Studio, you will need to restart Visual Studio for that.

If you have further issues with this not showing up in Visual Studio, please report it through there. You can do that by going to the Help menu, then choose Provide Feedback > Report a Problem.

Good luck on your .NET MAUI journey!

**Comment by nrakurniawan** [comment]
Thank you, 
now the MAUI template is available.

**Comment by robomac** [comment]
This did not work for me.  
The templates are still missing.  
<img width="894" alt="image" src="https://user-images.githubusercontent.com/15898894/229323380-19bf6bbb-bac4-4e1d-8558-de972bb7cc06.png">
<img width="899" alt="image" src="https://user-images.githubusercontent.com/15898894/229323406-28045d7d-f0d1-4d9d-bf4f-fac9823abb6e.png">
I even uninstalled and reinstalled Visual Studio!  
VS Mac 17.5.3 (build 15)

**Comment by milleniumfrog** [comment]
> This did not work for me.
> The templates are still missing.
> <img alt="image" width="894" src="https://user-images.githubusercontent.com/15898894/229323380-19bf6bbb-bac4-4e1d-8558-de972bb7cc06.png">
> <img alt="image" width="899" src="https://user-images.githubusercontent.com/15898894/229323406-28045d7d-f0d1-4d9d-bf4f-fac9823abb6e.png">
> I even uninstalled and reinstalled Visual Studio!
> VS Mac 17.5.3 (build 15)

I had the same Problem. Running `sudo dotnet workload update` fixed it.

**Comment by Badhansen** [comment]
`dotnet new install Microsoft.Maui.Templates` work on my end. Thanks @jfversluis
