### ISSUE TITLE
User Story: As a developer I can build applications with Android API 34

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#14026]
In .NET 7 and .NET 8 we will introduce Android 14 (API 34) for .NET and .NET MAUI.

Bindings work appears here: https://github.com/xamarin/xamarin-android

- [x] [Feb/Mar: Developer Previews](https://github.com/xamarin/xamarin-android/pull/7796)
- [x] April/May: Unstable Betas
- [x] June/July: Stable Betas
- [x] ???: Final

**Comment by jonpryor** [comment]
API-34 support is in xamarin-android/main and should be part of .NET 8 P6: https://github.com/xamarin/xamarin-android/commit/dab495ff1e139e2761bd690cb001f3df78a8e0db

API-34 support for .NET 7 is in draft, and we're uncertain if it will land: https://github.com/xamarin/xamarin-android/pull/8150
