### ISSUE TITLE
Remove solution files from maui templates

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/maui#14033]
### Description

When creating a new .NET MAUI project from the command line with `dotnet new maui` (or `dotnet new maui-blazor`), the output includes a new solution file (ex., `MyMauiApp.sln`).

It should only create the project file.  Solution files should not be created by project templates.

### Public API Changes

No API changes.  Just don't have a solution file in the project templates.

### Intended Use-Case

I might already have a solution that consists of class libraries, test projects, and other applications.  Adding a MAUI project to it should not generate a new solution file.

Consider that none of the other common .NET project templates include a solution file, such as `console`, `web`, `wpf`, `winforms`, `ios`, `android`, etc.  The MAUI templates should be consistent.

Thanks.

**Comment by jfversluis** [comment]
Maybe related to #13782?
