### ISSUE TITLE
[iOS] Page Contents shift down when using Prompt with input field.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#14041]
### Description

https://user-images.githubusercontent.com/898335/226103670-98c0861b-b891-428d-adc4-7c05964f26b9.mov

I believe this is caused by [this PR](https://github.com/dotnet/maui/commit/16fcd7e481c1b883aca9fe3533aebd445e212ead). The inner contents of the page are shifting down to match the keyboard height, but I am using a standard iOS prompt, so there's no reason for it to shift.

### Steps to Reproduce

1. Create an alert with a input field.
2. Watch as the inner contents shift.

### Link to public reproduction project repository

https://github.com/dotnet/maui/tree/main/src/Controls/samples/Controls.Sample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All iOS Versions

**Comment by jsuarezruiz** [comment]
cc @tj-devel709

**Comment by tj-devel709** [comment]
Thanks for spotting this @drasticactions, I'll take a look at this one!
