### ISSUE TITLE
[iOS] After lower positioned text entry item selected and scrolled, you can't scroll back to it.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#14043]
### Description

This is an after-effect of [this PR](https://github.com/dotnet/maui/commit/16fcd7e481c1b883aca9fe3533aebd445e212ead).

https://user-images.githubusercontent.com/898335/226108233-81b10d16-fbd0-4d20-be93-709e800897da.mp4

If you select the lowest positioned item, the view compensates and shows that item with the keyboard under it. However, if you scroll up, the view resets, and the item is now positioned under the keyboard, with no way to scroll back down. The only way to access it is to disable and reenable the keyboard.

### Steps to Reproduce

1. Open the Control Sample
2. Go to the entry page.
3. Select the lowest entry item
4. Scroll up.

### Link to public reproduction project repository

https://github.com/dotnet/maui/tree/main/src/Controls/samples/Controls.Sample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All Versions

**Comment by jsuarezruiz** [comment]
cc @tj-devel709

**Comment by tj-devel709** [comment]
Hi @drasticactions, I'll take a look at this one!

**Comment by tj-devel709** [comment]
I was able to recreate this issue! Looks like it also happens when the keyboard comes up and we rotate the screen orientation while the keyboard is still up

**Comment by tj-devel709** [comment]
While testing, it appears that this is not actually a regression, but something that was already happening on iOS

https://user-images.githubusercontent.com/50846373/229620113-efc38839-2e7c-44a9-b33a-6a18e691260b.mov

**Comment by tj-devel709** [comment]
@drasticactions and @jsuarezruiz, if I am incorrect about this not being a regression, please feel free to add the tag back on!

**Comment by tj-devel709** [comment]
I created the PR above to address this issue and will deal with the rotation parts with this issue here: https://github.com/dotnet/maui/issues/14372 since there is a good amount of change for the rotation
