### ISSUE TITLE
MAUI Blazor. Publish iOS. Can not create an IOS archive. Code object is not signed at all. In subcomponent. SQLLitePCLRaw.lib.e_sqllite.ios.aotdata.arm64

### ISSUE THREAD

**Issue by rburnashev85** [dotnet/maui#14044]
### Description

The app is working fine on windows, android and with ios hotreload with local connected iPhone.

The app uses sqllite.

I followed [this guide ](https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-app-store?view=net-maui-7.0&tabs=vs#publish-the-app). Now I have connected Mac in cloud and all the apple ids, certificates etc.

When I try to publish a new MAUI Blazor app everything works as expected.

But when I try to publish my app I have this error in Archive Manager window after about 5 minutes of execution:

`Can not create an IOS archive..... Process can not be executed on XMA server...... codesign exited with code 1: code object is not signed at all..... In subcomponent..... SQLLitePCLRaw.lib.e_sqllite.ios.aotdata.arm64`

Then I tried to unload projects which use sqllite and to remove references to them in MAUI project. The error changed to 

`Can not create an IOS archive..... Process can not be executed on XMA server...... codesign exited with code 1: code object is not signed at all..... In subcomponent..... System.Security.Cryptography.aotdata.arm64`

It seems that it is similar issue which was reported [here ](https://github.com/xamarin/xamarin-macios/issues/17153) with pipelines

Other issues I have with iOS. Maybe it would help to understand the core of the main issue:
1) When I try to just rebuild project in Release, iOS -> RemoteDevice I get this [error ](https://stackoverflow.com/questions/75749782/the-compileappmanifest-task-was-not-given-a-value-for-the-required-parameter)
2) Before the last VS update I was able to run iOS 14.2 Emulator. However it showed only white screen.  Both for my project and for the new MAUI Blazor project.
But now in output I just see that the project was sucessfully rebuild and published and that it took a couple of minutes. Then the debugging just stops and Emulator window doesn't appear. 

### Steps to Reproduce

1. Open the project
2. Follow the official guide how to publish it to App Store.  

### Link to public reproduction project repository

https://drive.google.com/file/d/1xhVdTjSpxnjMbiQF64QHjeA_sBiFFP2W/view?usp=sharing

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

xcode 14.2

**Comment by jfversluis** [comment]
A reproduction is not sharing your customers code, it's about sharing the minimal bits that you put together to show the issue. It will be super helpful if you could provide that so we don't have to try and back trace what you have been doing.

**Comment by rburnashev85** [comment]
Hi Gerald. First of all thank you for your videos! They are really heplful.

I updated the first post. I added the link to the zip file with the project. And also I added information about 2 other issues I have with iOS. Maybe they are related.

**Comment by jfversluis** [comment]
You mention

> Follow the official guide how to publish it to App Store

Could you share the commands you use? Even if they are the same as the official guides, just so we know there is no ambiguity there that we are overlooking? Thanks!

**Comment by rolfbjarne** [comment]
Does it happen if you try directly from the Mac using Visual Studio for Mac?

Also please share a binlog from a failing build (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) - even better if you can also share a binlog from a working build (since it might be somewhat random according to your last comment).

**Comment by rburnashev85** [comment]
@rolfbjarne 
Mac in cloud works superslow via RDP. And also it can not open my projects due to some permission issues:
![image](https://user-images.githubusercontent.com/54798402/226817446-e316f447-945f-4c0c-9ef6-ba76850d9806.png)

BinLogs (I used VS extension to collect it):
1) When I rebuild the project in Release, IOS Remote Device. I get "CompileAppManifest" task was not given a value for the required parameter "DefaultSdkVersion" error. [BinLog](https://drive.google.com/file/d/18sxJ0fGFvImEnY6QBUtdJ3hZUoNQUV6N/view?usp=sharing)
2) When I publish the project in Release, IOS Remote Device. I get Can not create an IOS archive..... Process can not be executed on XMA server...... codesign exited with code 1: code object is not signed at all..... In subcomponent..... SQLLitePCLRaw.lib.e_sqllite.ios.aotdata.arm64
[BinLog](https://drive.google.com/file/d/1LtTPCW9_OxSAf8t_5Wm2owo_Prhs-Mbt/view?usp=sharing)
3) When I rebuild a new MAUI Blazor Project in Release, IOS Remote Device with the same Sqllite dependencies - no errors.  [BinLog](https://drive.google.com/file/d/1t88nEvtKnQO7toVrfykklAxJtwMAKkaU/view?usp=sharing)
4) When I publish the new MAUI Blazor in Release, IOS Remote Device Project with the same Sqllite dependencies - no errors. 
 [BinLog] (https://drive.google.com/file/d/1isttxP8YLPeCqlLk8wm-GW0kjw1yH-VC/view?usp=sharing)

**Comment by rolfbjarne** [comment]
> And also it can not open my projects due to some permission issues:

This might be some special macOS protection since it's a file downloaded from the internet (it's in your ~/Downloads folder). I would suggest moving the zip file out of the ~/Downloads folder, then remove any quarantine attributes from the zip file (https://superuser.com/a/526949/61379), and only then extract the zip file.

**Comment by rburnashev85** [comment]
I moved the arhive to documents folder, removed quarantine attr. Now I get this errors:
![image](https://user-images.githubusercontent.com/54798402/226918822-8c209de7-a2fc-4cff-912d-e261c952e665.png)
![image](https://user-images.githubusercontent.com/54798402/226918992-f1d78a7d-66e6-4f94-a3cc-439074031d41.png)

**Comment by rolfbjarne** [comment]
> 1. When I rebuild the project in Release, IOS Remote Device. I get error: `"CompileAppManifest" task was not given a value for the required parameter "DefaultSdkVersion" . `

This happens because VS is not connected to the Mac:

> C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.2.1024\tools\msbuild\iOS\Xamarin.Messaging.Apple.targets(31,3): There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed [C:\Repos\Emily.Client\Emily.Client.MAUI\Emily.Client.MAUI.csproj]

> 2\. When I publish the project in Release, IOS Remote Device. I get error `Can not create an IOS archive..... Process can not be executed on XMA server...... codesign exited with code 1: code object is not signed at all..... In subcomponent..... SQLLitePCLRaw.lib.e_sqllite.ios.aotdata.arm64`

Does this only happen for Release builds, or does it happen for Debug builds as well (with with Hot Reload disabled)?

**Comment by rburnashev85** [comment]
1) But it is connected to Mac. New MAUI Blazor app using the same Mac and the same connection is rebuilded fine. Similar [issue](https://stackoverflow.com/questions/75749782/the-compileappmanifest-task-was-not-given-a-value-for-the-required-parameter).
2) Same errors for Debug (Hot Reload disable). However I've noticed that sometimes the error can change from `Can not create an IOS archive..... Process can not be executed on XMA server...... codesign exited with code 1: code object is not signed at all..... In subcomponent..... SQLLitePCLRaw.lib.e_sqllite.ios.aotdata.arm64` to `Can not create an IOS archive..... Process can not be executed on XMA server...... codesign exited with code 1: code object is not signed at all..... In subcomponent..... Microsoft.CSharp.dll`

**Comment by rolfbjarne** [comment]
The problem is that the app bundle contains a Resources directory. Removing this directory makes the app sign correctly.

This is the file in the directory:

> Resources/Raw/client.db

which seems to come from this in the csproj:

```xml
<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
```

Note the attempt to put the remove the "Resources\Raw" part of these paths - which was unsuccessful since files ended up in the Resources\Raw subdirectory.

I had a look at the binlog, and the problem seems to be in the ProcessMauiAssets target, because the GetMauiAssetsPath doesn't take the `LogicalName` metadata into account:

```
Target Name=ProcessMauiAssets Project=Emily.Client.MAUI.csproj
    GetMauiAssetPath
        Assembly = /usr/local/share/dotnet/packs/Microsoft.Maui.Resizetizer.Sdk/7.0.59/targets/Microsoft.Maui.Resizetizer.dll
        Parameters
            Input
                Resources/Raw/client.db
                    CopyToOutputDirectory = Always
                    LogicalName = client.db
            ProjectDirectory = /Users/rolf/Downloads/Emily.Client/Emily.Client.MAUI
        OutputItems
            Content
                Resources/Raw/client.db
                    CopyToOutputDirectory = Always
                    LogicalName = client.db
                    Link = Resources/Raw/client.db
```

Note how the `Link` metadata contains "Resources/Raw" in the output item.

As a workaround, it seems that setting the `Link` metadata instead of the `LogicalName` metadata works:

```xml
<MauiAsset Include="Resources\Raw\**" Link="%(RecursiveDir)%(Filename)%(Extension)" />
```

@jfversluis this looks like it's a bug in MAUI.

Note: I can reproduce this on a Mac.

**Comment by rburnashev85** [comment]
Confirm that both rebuild and publish issues are gone 😃 

Thank you guys!

Regarding Mac VS permission issues. It works if to move the project to Projects folder. In Downloads and Documents folder it doesn't work.
