### ISSUE TITLE
Border Margin on IOS Increases Padding

### ISSUE THREAD

**Issue by pschubert777** [dotnet/maui#14051]
### Description

When increasing the margin for a <Border> </Border> element in IOS, it seems to instead increase the padding. 

For example, when increasing the top and bottom margin from 10 to 40, the space within the border increases, but not the space between other elements in the CollectionView.

**IOS- Margin 10**

<img width="318" alt="Screen Shot 2023-03-18 at 9 34 15 PM" src="https://user-images.githubusercontent.com/44069136/226148946-9aa9e5f7-3228-4027-bb49-9d5310c41573.png">

**IOS - Margin 40**

<img width="323" alt="Screen Shot 2023-03-18 at 9 35 06 PM" src="https://user-images.githubusercontent.com/44069136/226148972-7806d686-20b6-4bf1-a9a1-d890b322df26.png">

**However, it works with Android**

<img width="331" alt="Screen Shot 2023-03-18 at 7 47 34 PM" src="https://user-images.githubusercontent.com/44069136/226148920-ea015a90-e628-4cc9-aabc-9c3de48513e7.png">

### Steps to Reproduce

1. Create a File > New Maui App
2. Create an Observable collection in the MainPage.xaml.cs
3. Create a CollectionView and set the ItemSource to the Observable collection in the MainPage.xaml
4. In the DataTemplate, wrap each list item with a border, set the top and bottom margin equal to 10
5. Run the IOS emulator
6. Switch the top and bottom margin to 40

### Link to public reproduction project repository

https://github.com/pschubert777/NewMauiTodo

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16.2/15.4

### Did you find any workaround?

No

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6 Preview(17.6.0.1539). Not repro on macOS platform with sample project. [NewMauiTodo](https://github.com/pschubert777/NewMauiTodo)
