### ISSUE TITLE
[Bug] VerticalStackLayout doesn't size

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1405]
### Description

I have a `VerticalStackLayout` inside a `HorizontalStackLayout` inside `ContentPage > ScrollView > StackLayout`. I set the width to 400, but the VSL still expands forever.

```xcml
<HorizontalStackLayout>
                     <VerticalStackLayout WidthRequest="400">
                            <Label Text="Overview" StyleClass="Title1"/>
                            <Label Text=".NET Multi-platform App UI (. NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. Using . NET MAUI, you can develop apps that can run on Android, iOS, macOS, and Windows from a single shared code-base." 
                                   LineBreakMode="WordWrap"
                            />
                     </VerticalStackLayout>
                     <VerticalStackLayout HorizontalOptions="Fill">
                            <Label Text="Getting Started" StyleClass="Headline"/>
                            <Label Text="To create .NET Multi-platform App UI (MAUI) apps, you currently require .NET 6 Preview 5 with .NET MAUI and the platform SDKs for Android, iOS, macOS, tvOS, and Mac Catalyst." 
                                   LineBreakMode="WordWrap"
                            />
                     </VerticalStackLayout>
                </HorizontalStackLayout>
```

<img width="1029" alt="Screen Shot 2021-06-21 at 10 47 30 PM" src="https://user-images.githubusercontent.com/41873/122860336-25e36200-d2e3-11eb-91f1-ae9048cdc0bc.png">

### Basic Information

- Version with issue: pre5

**Comment by davidortinau** [comment]
I would have expected to see something like this:

<img width="915" alt="Screen Shot 2021-06-21 at 11 00 23 PM" src="https://user-images.githubusercontent.com/41873/122861159-9474ef80-d2e4-11eb-8d92-64e7d2b2dbeb.png">

Which I achieved by using a 2 col Grid and StackLayouts:

```xaml
<Grid ColumnDefinitions="*,*">
                     <StackLayout Grid.Column="0">
                            <Label Text="Overview" StyleClass="Title1"/>
                            <Label Text=".NET Multi-platform App UI (. NET MAUI) is a cross-platform framework for creating native mobile and desktop apps with C# and XAML. Using . NET MAUI, you can develop apps that can run on Android, iOS, macOS, and Windows from a single shared code-base." 
                                   LineBreakMode="WordWrap"
                            />
                     </StackLayout>
                     <StackLayout Grid.Column="1">
                            <Label Text="Getting Started" StyleClass="Title1"/>
                            <Label Text="To create .NET Multi-platform App UI (MAUI) apps, you currently require .NET 6 Preview 5 with .NET MAUI and the platform SDKs for Android, iOS, macOS, tvOS, and Mac Catalyst." 
                                   LineBreakMode="WordWrap"
                            />
                     </StackLayout>
                </Grid>
```

**Comment by hartez** [comment]
@davidortinau Is this on Catalyst? Are you seeing it anywhere else?

**Comment by Redth** [comment]
Still an issue here:
![image](https://user-images.githubusercontent.com/271950/140555003-75bde729-ee78-441b-837e-aabedf712f4e.png)

**Comment by shimingsg** [comment]
Not reproducible with windows.

**Comment by kristinx0211** [comment]
can be reproduced on windows, repro sample:
[1405.zip](https://github.com/dotnet/maui/files/8129336/1405.zip)

**Comment by Redth** [comment]
Still repro's on windows here too.

**Comment by hartez** [comment]
@Redth and @davidortinau - I don't understand what you expect it to do. You have a HorizontalStackLayout with two children. The first child has an explicit width of 400, so it's 400 units wide. The second child has no explicit width set, so it gets as much width as it wants. There's no horizontal constraint. So it lays out the text in one long line.

**Comment by AmrAlSayed0** [comment]
@hartez The label in the stack on the right goes off screen and doesn't wrap.
