### ISSUE TITLE
LayoutOptions.Fill does not work with VisualElement.MaximumWidthRequest in FlexLayout

### ISSUE THREAD

**Issue by SF-Simon** [dotnet/maui#14050]
### Description

![image](https://user-images.githubusercontent.com/11264289/226148718-660a63e6-37f2-4e82-99ac-8792e0448799.png)

My understanding is that when it has sufficient width, it should maintain a width of 540.
But it didn't go as expected. That is, LayoutOptions.Fill cannot make this element always maximized, and is limited to VisualElement.MaximumWidthRequest.

### Steps to Reproduce

```
    <FlexLayout
        AlignContent="Center"
        AlignItems="Center"
        JustifyContent="Center"
        Wrap="Reverse">
        <VerticalStackLayout
            BackgroundColor="Green"
            HorizontalOptions="Fill"
            MaximumWidthRequest="540"
            Spacing="25">
            <Label
                BackgroundColor="Gray"
                FontSize="32"
                HorizontalOptions="Fill"
                Text="Hello, World!" />

            <Label FontSize="18" Text="Welcome to .NET Multi-platform App UI" />

            <HorizontalStackLayout Spacing="48">
                <Button
                    x:Name="CounterBtn"
                    Clicked="OnCounterClicked"
                    Text="Click me" />
                <Button Clicked="OnCounterClicked" Text="Click me" />
            </HorizontalStackLayout>
        </VerticalStackLayout>
        <Image Source="dotnet_bot.png" WidthRequest="200" />
    </FlexLayout>
```

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041 and Windows SDK 10.0.22621

**Comment by hartez** [comment]
This is the expected behavior. If there is a conflict between `HorizontalOptions` and `WidthRequest`/`MaximumWidthRequest`, the `WidthRequest`/`MaximumWidthRequest` will always win.
