### ISSUE TITLE
Maui Blazor with external library build in mac error

### ISSUE THREAD

**Issue by densen2014** [dotnet/maui#14056]
### Description

main maui blazor project ([MauiApp1](https://github.com/densen2014/MauiBlazorWithExternalLibrary/tree/master/MauiApp1))  and a external library with file with razor ([TestLibrary](https://github.com/densen2014/MauiBlazorWithExternalLibrary/tree/master/TestLibrary))

[TestLibrary.csproj](https://github.com/densen2014/MauiBlazorWithExternalLibrary/blob/master/TestLibrary/TestLibrary.csproj)

```
<Project Sdk="Microsoft.NET.Sdk.Razor">


    <PropertyGroup>
        <TargetFrameworks>net7.0;net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <SingleProject>true</SingleProject>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
        <Configurations>Debug;Release</Configurations>
		<!--<UseMaui>true</UseMaui>-->
	</PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="7.0.4" />
    </ItemGroup>

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
    </PropertyGroup> 
    
</Project>
```

### **Debug and build in windows have not error, but in vs for mac, show this error**  

![image](https://user-images.githubusercontent.com/8428709/226189046-dab643a6-19ac-4a4f-81ca-77ac56ebeefc.png)

### demo
https://github.com/densen2014/MauiBlazorWithExternalLibrary

Installed Workload ID     Manifest Version    Installation Source File   
-----------------------------------------------------
maui-maccatalyst      7.0.59/7.0.100      SDK 7.0.200
maui-ios              7.0.59/7.0.100      SDK 7.0.200
maui-android          7.0.59/7.0.100      SDK 7.0.200

### Steps to Reproduce

1. create a main maui blazor project 
2. create a external library with file with razor `<Project Sdk="Microsoft.NET.Sdk.Razor">`
3. add a razor file to external library
4. add a external library reference to main maui blazor project 
5. debug

### Link to public reproduction project repository

https://github.com/densen2014/MauiBlazorWithExternalLibrary

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

vs for mac 17.5.2

### Relevant log output

Full log [error.log](https://github.com/densen2014/MauiBlazorWithExternalLibrary/blob/master/error.log)

ListToList.razor : warning XA0101: @(Content) build action is not supported
_Imports.razor : warning XA0101: @(Content) build action is not supported
ListToList.razor : error : The path '../../../../../../../../../Users/alex/MauiBlazorWithExternalLibrary/TestLibrary/ListToList.razor' would result in a file outside of the app bundle and cannot be used.
ListToList.razor : error :         
_Imports.razor : error : The path '../../../../../../../../../Users/alex/MauiBlazorWithExternalLibrary/TestLibrary/_Imports.razor' would result in a file outside of the app bundle and cannot be used.
_Imports.razor : error :         
ListToList.razor : error : The path '../../../../../../../../../Users/alex/MauiBlazorWithExternalLibrary/TestLibrary/ListToList.razor' would result in a file outside of the app bundle and cannot be used.
ListToList.razor : error :         
_Imports.razor : error : The path '../../../../../../../../../Users/alex/MauiBlazorWithExternalLibrary/TestLibrary/_Imports.razor' would result in a file outside of the app bundle and cannot be used.
_Imports.razor : error :         
    2 个警告
    4 个错误

已用时间 00:00:15.06

========== 生成: 0 成功，1 失败，0 更新，0 跳过 ==========

生成: 4 个错误, 2 个警告

**Comment by MackinnonBuck** [comment]
cc @Eilon

**Comment by Eilon** [comment]
Hi, this scenario is not currently supported, but we are considering adding support for it in the future. As a workaround, you can split out the Razor files into a separate Razor Class Library project, and then reference that from a MAUI library project. You just can't mix Razor and MAUI in the same library right now.

You can read more in this issue: https://github.com/dotnet/maui/issues/3288#issuecomment-1021612636

**Comment by densen2014** [comment]
> 嗨，目前不支持这种情况，但我们正在考虑在未来增加对它的支持。作为解决方法，您可以将 Razor 文件拆分到一个单独的 Razor 类库项目中，然后从 MAUI 库项目中引用它。你现在不能在同一个库中混合使用 Razor 和 MAUI。
> 
> 更多内容可以阅读本期：[#3288（评论）](https://github.com/dotnet/maui/issues/3288#issuecomment-1021612636)

i am so sorry to hear that, but it can debug in vs2022 for windows. i am using with shard libary publish to a nuget pack .. is a long way.

**Comment by densen2014** [comment]
> Hi, this scenario is not currently supported, but we are considering adding support for it in the future. As a workaround, you can split out the Razor files into a separate Razor Class Library project, and then reference that from a MAUI library project. You just can't mix Razor and MAUI in the same library right now.
> 
> You can read more in this issue: [#3288 (comment)](https://github.com/dotnet/maui/issues/3288#issuecomment-1021612636)

i am so sorry to hear that, but it can debug in vs2022 for windows. i am using with shard libary publish to a nuget pack .. is a long way.

**Comment by Eilon** [comment]
@densen2014 indeed, it might work on certain platforms, but not others. The workaround should work on all platforms.
