### ISSUE TITLE
The main branch is minimized before restoring the window, and the program crashes.

### ISSUE THREAD

**Issue by SF-Simon** [dotnet/maui#14053]
### Description

![image](https://user-images.githubusercontent.com/11264289/226155377-87b06500-9e7a-4a40-af8d-12e78d95f745.png)

### Steps to Reproduce

I downloaded the branch from GitHub, Debug the specified project after compilation. 
`$ dotnet cake --pack --sln="D:\Test.sln" --target=VS`

The newly created Windows platform project has no changes. （_Maui.Controls.Sample_ This error can also occur.）

When debugging is running, simply minimize the window and restore it to the foreground, resulting in a direct crash.

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041 and Windows SDK 10.0.22621

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 1.0. Not repro on windows platform with sample project.
I debugged Maui.Controls.Sample, minimized the window and restored it, and it didn't crash.
https://github.com/dotnet/maui/
