### ISSUE TITLE
RefreshView TapGestureRecognizer Event does not respond on iOs for items which are only visible after scrolling

### ISSUE THREAD

**Issue by Yannikk1996** [dotnet/maui#14060]
### Description

In a RefreshView the TapGestureRecognizer Event does not respond on iOs for items which are only visible after scrolling. The TapGestureRecognizer Event works for the first items which can be displayed on the screen but for the items which can only be reached by scrolling down the TapGestureRecognizer Event will not be triggered. This happens when items created in xaml and also when added in c# code. 

This also happens when using Scrollview. For Scrollview this only happens when adding items after its creation. Therefore recreating the complete scrollview control is a possible workaround.

This issue occurs on  iOS. Windows and Android work as expected.

### Steps to Reproduce

<RefreshView x:Name="Refresh">
        <ScrollView>
            <StackLayout x:Name="stack">
            <Border x:Name="con1"  HeightRequest="100">
                <Label Text="1"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
            </Border>
            <Border x:Name="con2" HeightRequest="100">
                <Label Text="2"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con3" HeightRequest="100">
                <Label Text="3"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con4" HeightRequest="100">
                <Label Text="4"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con5" HeightRequest="100">
                <Label Text="5"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con6" HeightRequest="100">
                <Label Text="6"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con7" HeightRequest="100">
                <Label Text="7"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con8" HeightRequest="100">
                <Label Text="8"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con9" HeightRequest="100">
                <Label Text="9"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con10" HeightRequest="100">
                <Label Text="10"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con11" HeightRequest="100">
                <Label Text="11"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con12" HeightRequest="100">
                <Label Text="12"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
            <Border x:Name="con13" HeightRequest="100">
                <Label Text="13"></Label>
            </Border>
            <Border x:Name="con14" HeightRequest="100">
                <Label Text="14"></Label>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                    </Border.GestureRecognizers>
                </Border>
        </StackLayout>
        </ScrollView>
    </RefreshView>

### Link to public reproduction project repository

[[-](https://github.com/Yannikk1996/RefreshViewNotWorking)](https://github.com/Yannikk1996/RefreshViewNotWorking)

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.3.1

### Did you find any workaround?

No

**Comment by JonnySKK** [comment]
We are also encountering the exact same issue - on iOS only, and only for items which are only visible after scrolling - the click events do not work. Currently it's holding up being able to use the RefreshView at all on an important screen

**Comment by Yannikk1996** [comment]
#14795

**Comment by Yannikk1996** [comment]
#14795 maybe similiar issue

**Comment by Yannikk1996** [comment]
Ipad is not affected.

**Comment by xXComanderXx** [comment]
Hey,
I have the exact same issue and didn't find a workaround. This makes it almost useless to use the RefreshView.

**Comment by Yannikk1996** [comment]
Hi , I found the workaround from #14624 can work by using an additional Grid between Refresh and scrollview.

**Comment by cat0363** [comment]
It worked with the code below.
The name of the control is the one in the source code you uploaded.

    stack.SizeChanged += (object sender, EventArgs e) =>
    {
        Refresh.ForceLayout();
    };

**Comment by Yannikk1996** [comment]
@cat0363  thanks!

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on iOS platform with sample project.
https://github.com/Yannikk1996/RefreshViewNotWorking

**Comment by muak** [comment]
@cat0363 
This workaround works fine. Thanks!

**Comment by hartez** [comment]
Possible this is fixed by #16385.

**Comment by jsuarezruiz** [comment]
Fixed by https://github.com/dotnet/maui/pull/16385
