### ISSUE TITLE
Frame clipping incorrectly on Windows

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#14078]
### Description

Run the sample from 
https://github.com/dotnet/maui/issues/13469

**Expected**

![image](https://user-images.githubusercontent.com/5375137/226377962-71f9414e-cc59-4e3b-b019-9a1c84efca36.png)

**Actual**

![image](https://user-images.githubusercontent.com/5375137/226377795-54527904-8f98-4d35-9fb5-d7a4c0a20961.png)

This doesn't appear to be a regression from our recent changes with `Frame`. I ran the sample against 7.0.49 and that also seems to offset the image in a way that doesn't match ios/android.

### Steps to Reproduce

Run the attached sample on WinUI

### Link to public reproduction project repository

https://github.com/ManfredRohleder/FrameIssueAndroid

### Version with bug

8.0 previews

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on windows platform with sample project.
[FrameIssueAndroid-master.zip](https://github.com/dotnet/maui/files/11785200/FrameIssueAndroid-master.zip)
![Screenshot 2023-06-19 150429](https://github.com/dotnet/maui/assets/77434865/541cee73-2542-46d2-9141-00df1f667c1d)

**Comment by jfversluis** [comment]
Seeing that Frame is officially deprecated as of .NET 9, I don't think we will be working on this anymore. Also its a bit older by now, so maybe its even resolved in current versions 🤞
