### ISSUE TITLE
Could not load file or assembly XmlSerializers.dll on Mac

### ISSUE THREAD

**Issue by dingxiaolong** [dotnet/maui#14086]
### Description

When try to instance a XmlSerializer, face an issue :"Could not load file or assembly XmlSerializers.dll".

### Steps to Reproduce

1. Create a new MAUI app 
2. Instance a XmlSerializer like this :        var xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(Test));
3. Add a New Exception breakpoint 
4. Run on ios simulator ,app will face an error  "Could not load file or assembly XmlSerializers.dll"
![image](https://user-images.githubusercontent.com/21192107/226554082-3053aaee-d59b-464a-b4cf-aa631192f440.png)

### Link to public reproduction project repository

https://github.com/dingxiaolong/XmlSerializer-test

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

all version

**Comment by drasticactions** [comment]
This is not an MAUI bug; you can reproduce that exception with a .NET iOS app that doesn't use the MAUI UI Framework, for example, https://github.com/drasticactions/MauiRepros/tree/main/XmlApple/XmlApple.iOS

<img width="1163" alt="スクリーンショット 2023-03-22 0 34 46" src="https://user-images.githubusercontent.com/898335/226657935-b8be3d5a-7d3f-472d-a2cc-3633f0b5b0fe.png">

```
"System.Private.CoreLib"
System.IO.FileNotFoundException: 
  at at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
  at at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
  at at System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly(Type type, String defaultNamespace, XmlSerializerImplementation& contract)

```

<img width="1323" alt="スクリーンショット 2023-03-22 0 40 35" src="https://user-images.githubusercontent.com/898335/226659739-36fd2cbb-3fe8-48af-9c4d-1f345c310511.png">

This feels like it would be a runtime issue. It doesn't seem specific to iOS/Mac; I could get it thrown on Android too. @rolfbjarne @akoeplinger Any ideas?

**Comment by rolfbjarne** [comment]
> This is not an MAUI bug; you can reproduce that exception with a .NET iOS app that doesn't use the MAUI UI Framework, for example, [drasticactions/MauiRepros@`main`/XmlApple/XmlApple.iOS](https://github.com/drasticactions/MauiRepros/tree/main/XmlApple/XmlApple.iOS?rgh-link-date=2023-03-21T15%3A43%3A20Z)

This sample works fine for me, both from the command line and when running from the IDE.

Can you try executing `dotnet run /v:diag` to see if you get the same behavior from the command line?

**Comment by dingxiaolong** [comment]
Dear guys:
I also face this issue on the iOS project you provide [drasticactions/MauiRepros@main/XmlApple/XmlApple.iOS](https://github.com/drasticactions/MauiRepros/tree/main/XmlApple/XmlApple.iOS?rgh-link-date=2023-03-21T15%3A43%3A20Z),   **when I add a exception breakpoint** 

The topic is I need use this instance  , if try to use this instance ,app will crash directly .
Just like the demo here :https://github.com/dingxiaolong/TestIOSXml

[drasticactions/MauiRepros@main/XmlApple/XmlApple.iOS](https://github.com/drasticactions/MauiRepros/tree/main/XmlApple/XmlApple.iOS?rgh-link-date=2023-03-21T15%3A43%3A20Z)

Could you help double check it please .
Many thanks.

**Comment by drasticactions** [comment]
It doesn't

<img width="739" alt="スクリーンショット 2023-03-22 12 26 44" src="https://user-images.githubusercontent.com/898335/226794591-6e543507-d4fd-4655-9643-bc4965d4e308.png">

The exception is thrown by XmlSerializers, but you're seeing it because you're telling the debugger to show all exceptions. It's handled internally by the library so it passes and returns the object.

I believe your example repro is crashing because you're setting up an app process, but not calling UIApplication.Main, so it quits since it's not actually starting.

**Comment by rolfbjarne** [comment]
> it's an internal exception within XmlSerializers that's being thrown, apparently, on Mono based devices? I could get the same exception thrown on Android, this seems like a runtime bug.

IMHO it's not a bug, it's an internal implementation detail, as long as the exception is handled by the library before you get back control - although admittedly it can be argued that finding an implementation that doesn't throw an exception would be better, and in that case this issue should be refiled/moved to the dotnet/runtime repository.

**Comment by dingxiaolong** [comment]
Many thanks for your help.
I am sorry, It is clear for me . I think it is my misunderstanding .
At first I face a serialize issue when I try to migrate my project from Xamarin to Donet 6, so I suppose the issue related to the lib ... 
Anyway it is a good news for me , I will try to find another reason .
Thanks again .
Br .
