### ISSUE TITLE
Single-project MSIX Packaging Tools is NOT included with Project Reunion (Preview)

### ISSUE THREAD

**Issue by markrendle** [dotnet/maui#1408]
### Description

The Overview for the Single-project MSIX Packaging Tools on Marketplace says the "extension is included with Project Reunion (Preview) and does not need to be downloaded and installed separately."

This is not, in fact, true. I had the Project Reunion (Preview) package installed but still couldn't run a .NET 6 Preview 5 MAUI WinUI project until I manually installed the Single-project MSIX Packaging Tools.

### Basic Information

- VS2019 16.11 Preview 2.0
- Project Reunion (Preview) version 0.8.0.44306308
- Single-project MSIX Packaging Tools version 0.9.0.2105281

### Screenshots

![image](https://user-images.githubusercontent.com/178242/122907867-768ea580-d34b-11eb-9566-b4415b9668eb.png)

### Reproduction Link

https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingTools

**Comment by solvingj** [comment]
This requirement is explained the readme of the maui-samples repo, but obviously, there's no guarantee anyone would look there.  There are so many repos and samples and templates and demos right now, it's hard for everyone trying to use it to find all the important information. 

https://github.com/dotnet/maui-samples#winui3

**Comment by marb2000** [comment]
@markrendle the single project is a work in progress in Windows App SDK 0.8, there are still several scenarios no supported. We don't expect to have it fully integrated until v1.

**Comment by Eilon** [comment]
BTW please note that at this point Visual Studio 2022 is required, so you need to make sure to install the VS2022 version of the Single-project MSIX tools from here: https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17

**Comment by jsuarezruiz** [comment]
Actually you require Visual Studio 2022 Preview and **Single-project MSIX Packaging Tools for VS 2022**  https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17
