### ISSUE TITLE
HorizontalOptions Fill does not have any effect on the HorizontalStackLayout

### ISSUE THREAD

**Issue by omghb** [dotnet/maui#14087]
### Description

This issue just tries to re-open: 
- https://github.com/dotnet/maui/issues/6768

**Reason**
- See comment from @hartez: https://github.com/dotnet/maui/issues/6768#issuecomment-1116177114
- The `AndExpand` layout options are deprecated. But `HorizontalOptions="Fill"` doesn't work either.
- We are using `HorizontalStackLayout` with `BindableLayout.ItemsSource`. This cannot be replaced by a `Grid` or `FlexLayout`.

### Steps to Reproduce

See https://github.com/dotnet/maui/issues/6768

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

All

### Did you find any workaround?

Just by using old `StackLayout` and using the `deprecated` `AndExpand` layout feature.

### Relevant log output

```shell
-
```

**Comment by hartez** [comment]
When you say that "HorizontalOptions="Fill" doesn't work" with a HorizontalStackLayout, what are you referring to? Are you doing something like this?

```
<HorizontalStackLayout HorizontalOptions="Fill"></HorizontalStackLayout>
```

or something like this?

```
<HorizontalStackLayout>
	<Button Text="Hello" HorizontalOptions="Fill"/>
</HorizontalStackLayout>
```

**Comment by omghb** [comment]
Steps to reproduce:
1. Create MAUI 7 project
2.  Replace code in `MainPage.xaml` with:
```XML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiApp2"
             x:Class="MauiApp2.MainPage" x:DataType="local:MainViewModel">
    <ContentPage.Resources>
        <DataTemplate x:Key="TestTemplate">
            <Label Text="{Binding}" Background="Green" HorizontalOptions="FillAndExpand"/>
        </DataTemplate>
    </ContentPage.Resources>
    
    <VerticalStackLayout>
        <Label Text="HorizontalStackLayout:"/>
        <HorizontalStackLayout BindableLayout.ItemsSource="{Binding List}" BindableLayout.ItemTemplate="{StaticResource TestTemplate}" Background="Red"/>

        <Label Text="StackLayout:" Margin="0,20,0,0"/>
        <StackLayout Orientation="Horizontal" BindableLayout.ItemsSource="{Binding List}" BindableLayout.ItemTemplate="{StaticResource TestTemplate}" Background="Red"/>
    </VerticalStackLayout>
</ContentPage>
```
4. Replace code in `MainPage.xaml.cs` with
```
namespace MauiApp2;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
		BindingContext = new MainViewModel();
	}
}

public class MainViewModel
{
    private readonly string[] list = new[] { "Bill", "Steve", "John" };

    public IReadOnlyList<string> List => list;
}
```
5. Verify that the namespace is correct. My code snippets use `MauiApp2`.
6. Run (e.g. on Android) to see the following result:

![image](https://user-images.githubusercontent.com/47421673/226901526-06591056-4cef-4fe0-8121-a842c73c2454.png)

I want to have the result of the second variant with the `StackLayout` together with the `FillAndExpand` option. But I'm not able to get this result with any other layout container.

**Comment by hartez** [comment]
You can achieve your target layout using FlexLayout:

```xaml
<ContentPage.Resources>
    <DataTemplate x:Key="TestTemplate">
        <Label Text="{Binding}"
                FlexLayout.Grow="1"
                Background="Green"
                HeightRequest="40" />
    </DataTemplate>
</ContentPage.Resources>

<VerticalStackLayout>
    <Label Text="FlexLayout:"
            Margin="0,20,0,0" />
    <FlexLayout JustifyContent="SpaceBetween"
                AlignContent="Stretch"
                BindableLayout.ItemsSource="{Binding List}"
                BindableLayout.ItemTemplate="{StaticResource TestTemplate}"
                Background="Orange" />
</VerticalStackLayout>
```

However, the current stable version of .NET 7 has a bug with FlexLayout where items without explicit sizes don't get properly laid out by FlexLayout. (That's why there's a `HeightRequest="40"` in the `DataTemplate` - to work around the bug.)

The fix for the issue has been backported (https://github.com/dotnet/maui/pull/13399), and should be in the next service release. Then you'll be able to remove the `HeightRequest` from the template.

**Comment by omghb** [comment]
Thanks for your help. Using the `FlexLayout` looks promising. I will give it a try.
