### ISSUE TITLE
ScrollView inside Border does not render offscreen content after scroll. iOS only.

### ISSUE THREAD

**Issue by Keflon** [dotnet/maui#14091]
### Description

A ScrollView inside a Border does not render content that is scrolled into view. 
The content takes up space, so is measured, it just doesn't render.
iOS screenshot.
![image](https://user-images.githubusercontent.com/16598898/226574554-7ad5661b-a1cf-472c-8b30-15a1d40b4541.png)

### Steps to Reproduce

1. Create a File->New MAUI app.
2. In MainPage.xaml
   1. Wrap the ScrollView in a Border
   2. Add enough content (e.g. Labels) to the end of the VerticalStackLayout
3. Build and run the app for iOS.

## Expected behaviour
Scrolling content into view ought to render the content.

## Actual behaviour
Content that is scrolled into view is not rendered on the iOS platform.

### Link to public reproduction project repository

https://github.com/Keflon/MauiScrollViewBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Simulator 16.2; iPhone X 16.3.1.  Probably others.

### Did you find any workaround?

Do not wrap a ScrollView in a Border if targeting iOS.

**Comment by ooikengsiang** [comment]
Tested again main branch, this problem is fixed. I think by this changelist #14096.

**Comment by rmarinho** [comment]
Fixed by #14096.
