### ISSUE TITLE
Keyboard Events Not Triggering in Input Element and InputText Component on macOS

### ISSUE THREAD

**Issue by Deepak-Ramakrisnan** [dotnet/maui#14099]
### Description

The keyboard events, such as @onkeydown, @onkeyup, and @onkeypress, are not triggering for the input element or InputText component in a MAUI Blazor app running on macOS. While these events work fine on Windows machines.

### Steps to Reproduce

- Run the attached MAUI app.
- Focus on the input element.
- Type any alphanumeric key inside it.

**Expected Result**:
The keyboard events should trigger for every valid key press.

**Actual Result**:
None of the keyboard events are triggered for the key inputs.

### Link to public reproduction project repository

https://github.com/Deepak-Ramakrisnan/MAUI-KeyBoard

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MACOS Ventura version 13.2.1

**Comment by Eilon** [comment]
Confirmed it is a dupe.

**Comment by Eilon** [comment]
To anyone seeing this issue: On whichever Mac you are seeing this issue, can you tell us what type of Apple hardware you have?

To find this info:
* On your Mac, click on the Apple logo at the upper-left corner of the screen, then select **About This Mac**
* It will say "Processor" or "Chip" and next to that it will say either Intel (such as Intel Core i7) or Apple (such as Apple M1)
