### ISSUE TITLE
DisplayActionSheet still not working on Windows 

### ISSUE THREAD

**Issue by R-J-Turner** [dotnet/maui#14098]
### Description

When attempting to show an action sheet, it works fine on Android, but the code is skipped over completely on Windows.

This is the same issue as logged in https://github.com/dotnet/maui/pull/7025, which is marked as fixed, but the issue is still occurring on my version (7.0.59).

### Steps to Reproduce

1. Create a new MAUI App.
2. Add the following code to the main page:
`         Shell.Current.DisplayActionSheet("Return Reason", "Cancel", null, "OK");
`

3. Build the app and run it in Windows, the actionsheet will not be displayed.
4. Repeat for Android, the action sheet will display as intended.
N.B. Other alerts (such as DisplayAlert) work fine on both platforms. 

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by R-J-Turner** [comment]
I'm calling it from an event handler on a page. All the other "alerts" (i.e. DisplayAlert) work fine in the same position. The issue only occurs on Windows, it works fine in Android.

**Comment by R-J-Turner** [comment]
I've tried to replicate this in a few scenarios outside of my original code, and can't seem to be able to. I then restructured my code and was able to get this working correctly.

**Comment by samhouts** [comment]
Duplicate of #14829
