### ISSUE TITLE
[regression/7.0.0] Label Multilinetruncation (MaxLines / LineBreakMode)

### ISSUE THREAD

**Issue by vcechak** [dotnet/maui#14125]
### Description

Hi, I have run into issue where using MaxLines and  LineBreakMode didn't work. 

code of the label:
` new Label()
        {
            MaxLines = 2,
            LineBreakMode = LineBreakMode.TailTruncation,
        }
          .Font(family: MediumFont)
          .FontSize(16.AsSize());
 `

When used, label truncated on the first line.

Per this Git https://github.com/dotnet/maui/pull/5093 the issue have been fixed. We are using version 7.0.52 where it should already work as it has been fixed somewhere in Maui 6.

This workaround worked:
https://github.com/dotnet/maui/discussions/5492#discussioncomment-4681884

### Steps to Reproduce

Create label with MaxLines=2, LineBreakMode=LineBreakMode.TailTruncation

Fill label with string longer than 2 lines.

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

both latest os of Iphone and Android

### Did you find any workaround?

https://github.com/dotnet/maui/discussions/5492#discussioncomment-4681884

**Comment by Redth** [comment]
This did not work in net7.0 or net8.0.
