### ISSUE TITLE
On iOS Property InputTransparent=true does not work for LABEL

### ISSUE THREAD

**Issue by scriptBoris** [dotnet/maui#14124]
### Description

```
<Grid>
        <Button Text="button" Clicked="Button_Clicked"/>
        <Label Text="label"
                    InputTransparent="True"/>
</Grid>
```

The button will never receive input!

### Steps to Reproduce

```
<Grid>
        <Button Text="button" Clicked="Button_Clicked"/>
        <Label Text="label"
                    InputTransparent="True"/>
</Grid>
```

### Link to public reproduction project repository

https://github.com/scriptBoris/MauiAppBugLabel_14124

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16.2

### Did you find any workaround?

NOT

**Comment by scriptBoris** [comment]
Everything works fine on android.

**Comment by ooikengsiang** [comment]
@scriptBoris make sure there are no style that target label type with background color set to transparent or any value.
iOS have behavior that if the background color is set (even it is set to transparent), it will block the user interaction.

**Comment by scriptBoris** [comment]
> @scriptBoris make sure there are no style that target label type with background color set to transparent or any value. iOS have behavior that if the background color is set (even it is set to transparent), it will block the user interaction.

I created a public repository where the bug is reproduced based on the default template
https://github.com/scriptBoris/MauiAppBugLabel_14124

**Comment by ooikengsiang** [comment]
> > @scriptBoris make sure there are no style that target label type with background color set to transparent or any value. iOS have behavior that if the background color is set (even it is set to transparent), it will block the user interaction.
> 
> 
> 
> I created a public repository where the bug is reproduced based on the default template
> 
> https://github.com/scriptBoris/MauiAppBugLabel_14124
> 
> 

Ya, the default template have a style to target label type and set the background to transparent.

**Comment by scriptBoris** [comment]
OMG

**Comment by ooikengsiang** [comment]
I can understand the reason why they put background color transparent in style for the template project. This is because make label clickable is a very common scenario and many developers will miss out that they need to set the background color.
Although you can argue that it is a bug that the MAUI should automatically adjust the background color between null and transparent for iOS.

**Comment by cat0363** [comment]
What is the reason for closing this issue?
What is the workaround or solution?
I am facing a similar issue and specifying a background color does not fix this issue.
It was working on Xamarin.Forms, but no longer works on iOS with .NET MAUI.
