### ISSUE TITLE
CollectionView scrollts content behind TitleBar (can't scroll down enough) on some devices

### ISSUE THREAD

**Issue by Sebastian1989101** [dotnet/maui#14149]
### Description

As title says, on some devices (here iPhone SE with iOS 14.5), the CollectionView is behind the TitleBar and can't be scrolled down enough. On a iPhone 14 Pro Max the list looks fine so I expect this issue to only affect devices without SafeArea. 

<img width="458" alt="Bildschirm­foto 2023-03-22 um 23 22 48" src="https://user-images.githubusercontent.com/25636075/227052166-ab9a606a-8740-4ccd-928d-141d5b45c51c.png">

### Steps to Reproduce

1. Create new MAUI App with Flyout Menu 
2. Add CollectionView to it 
3. Set `ios:Page.UseSafeArea="False"` on the page (because the default MAUI behavior breaks native control behavior - maybe that should be a bug as well?? MAUI just uses a margin at the bottom instead of a content padding for the scrolling)
4. Use a Emulator without SafeArea (for example iPhone SE with iOS 14.5)

### Link to public reproduction project repository

n/a

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

n/a

### Did you find any workaround?

No

**Comment by jinxinjuan** [comment]
@Sebastian1989101 Could you provide a sample project in order to repro the issue? Thanks.
