### ISSUE TITLE
The Image.Source data binding does not react to BindingContext changes

### ISSUE THREAD

**Issue by DmitryRomenskiy** [dotnet/maui#14157]
### Description

Hello,

When BindingContext is changed for an Image that has Binding assigned to its source, the new image source is not always rendered

### Steps to Reproduce

See the attached project

### Link to public reproduction project repository

https://github.com/DmitryRomenskiy/ImageBindingContext

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

The use of an additional bound property, like Image.IsVisible tends to help

**Comment by kirakosyan** [comment]
DevEx claims that the bug in their control is related to this. Information in the discussion can be useful
https://supportcenter.devexpress.com/ticket/details/t1155623/dxcollectionview-does-not-show-images-in-its-items-when-its-parent-tab-is-switched

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on android and iOS platform with sample project.
[ImageBinding.zip](https://github.com/dotnet/maui/files/11783681/ImageBinding.zip)
![14157](https://github.com/dotnet/maui/assets/77434865/da7689ff-ec1a-4bb4-aa1e-b67603c06b3b)
![14157 iOS](https://github.com/dotnet/maui/assets/77434865/a095a265-96a6-4b7b-974f-30cec479d35a)

**Comment by kirakosyan** [comment]
> Hi @DmitryRomenskiy. We have added the "s/try-latest-version" label to this issue, which indicates that we'd like you to try and reproduce this issue on the latest available public version. This can happen because we think that this issue was fixed in a version that has just been released, or the information provided by you indicates that you might be working with an older version.
> 
> You can install the latest version by installing the latest Visual Studio (Preview) with the .NET MAUI workload installed. If the issue still persists, please let us know with any additional details and ideally a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md) provided through a GitHub repository.
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

Hi

Latest version of what? 
Some people use Rider and Mac and some cannot upgrade Visual Studio to preview.
What should be exactly updated and to which version?

**Comment by DmitryRomenskiy** [comment]
Yo,

I assume that the latest .NET version is in discussion (7.0.7 as I see - https://dotnet.microsoft.com/en-us/download/dotnet/7.0). I did not have a chance to try it myself yet.

**Comment by DmitryRomenskiy** [comment]
.NET 8 preview is also available - https://dotnet.microsoft.com/en-us/download/dotnet/8.0

**Comment by kirakosyan** [comment]
may be @Zhanglirong-Winnie can provide some details what does that mean /try-latest-version
Will be nice to know in which version it was fixed.

**Comment by mattleibow** [comment]
`try-latest-version` usually means we released something so it may be in one of those. Usually only 1 release has happened, but sometimes a servicing goes out. In many cases, you can see in the issue that there is a linked PR that would be merged into a branch for the release. We have also been adding a `released-in-xxx` labels too for finding fixes.

But in this case, we have no fix since we are not sure which change fixed it. Typically we work on VS releases since that is our main way of releasing things.

In this case, it probably was .NET 8, but I tested this now and it seems to work in .NET 7. So basically, try any latest version that we released since the issue was opened.
