### ISSUE TITLE
[Bug] IsVisible Can't Be Changed at Runtime

### ISSUE THREAD

**Issue by matt-goldman** [dotnet/maui#1416]
### Description
The IsVisible property of a view or control doesn't respond to changes at runtime. When binding this to a boolean property of a viewmodel, changing the value of that property, then raising property changed, the visibility of that control should change. Also, when setting the IsVisible property directly in code behind, the visual state should change, but does not.

For example, if I have a label and bind the text to a string in my view model, start with an empty string, populate the string and raise property changed, the text then appears on screen. If instead I create a label with static text but bind the IsVisibile property and change that instead, the label does not appear.

### Steps to Reproduce

1. Bind the IsVisible property of a view to a boolean property of a view model
2. Change the value of the boolean
3. Raise property changed

or

1. In the code behind, set the IsVisible property of a view to false in a page constructor
2. At runtime, change the IsVisible property of that view to true in a method or event handler

### Expected Behavior
The visibility of the view should change

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: Microsoft.Maui 6.0.100-preview.5.794
- Last known good version:
- IDE: Visual Studio 16.11.0 Preview 2.0
- Platform Target Frameworks: 
  - iOS:  
  - Android: 30
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

This repo demonstrates the issue: https://github.com/matt-goldman/maui-isvisible-bug-demo

In the main branch the IsVisible property of a label is set programmatically in the code behind. This works, although I have other more complex test projects where it doesn't work.

There is also a branch called `with-viewmodel` - in this branch the IsVisible property of the label is set in the ViewModel, and changing this property and then raising a property changed notification does not change the visibility in the view.

### Workaround
Depending on the view, the workaround can be to update the content (e.g. for a label) rather than the visibility. 

Alternatively, initialising the property to true seems to help. For example, in the repo above (view model branch), if I declare my binding property as `private bool showLabel = true;`, I can set it to false, and back to true, etc and the view responds. If I intitialise it to false (or don't prescribe an initial value) the view remains invisible no matter what I do.

**Comment by matt-goldman** [comment]
Additional information - with a non-trivial view, the workarounds don't work as well. For example even having something visible at init doesn't necessarily guarantee the workaround will work. In summary, the behaviour is inconsistent and unpredictable.

This is interesting though - if you do a bunch of view updates in your view model, raise a property changed event for them all, and nothing happens - then you click into an entry or editor, and all the view updates apply.

**Comment by psandgren** [comment]
Is this being looked at? I'm having the same problem in Preview 7.

**Comment by Allemannen** [comment]
I'm having this problem as well and my perception is, in addition to what matt-goldman wrote, is that it also behaves erradic when in an async context. Note that I'm not talking about problems with execute GUI-code on non-MainThread. After awaiting an async Task I've not managed to change IsVisible-property and have the effect occur, neither by INotifyPropertyChanged binding or by directly changing the setting the property on the Element.

**Comment by hartez** [comment]
This is fixed with the latest in main.

**Comment by matt-goldman** [comment]
I'm still getting this issue on the latest preview.

**Comment by DaveNatalieTripArc** [comment]
This is not fixed as of Preview 13.

**Comment by MaxxDelusional** [comment]
I am seeing this in Preview 13.

**Comment by davidbuckleyni** [comment]
Why has this been closed this is hapening to much if late fix the bugs.
