### ISSUE TITLE
.Net Maui Hybrid + Paypal, Smart payment button works very well on Android, but not on Iphone

### ISSUE THREAD

**Issue by MarcoErlwein** [dotnet/maui#14162]
### Description

I have an App developed in .Net Maui Hybrid, it uses the Paypal buttons to make a Checkout Payment, it works very well on Android, but not on Iphone, the traditional PayPal modal window is not shown, but a Safari session is started with the button, but it is blocked.

I am using version 7.0 of .NET

These are the screens captured on Iphone, the first image generates the PayPal button, but it is blocked and the second image is directly raised in Safari. The third image is the correct behavior in Android.

first image
![Wallet01](https://user-images.githubusercontent.com/33732800/227222239-88227880-0285-4787-abc1-f2bdc0c239d6.png)

second image
![Wallet02](https://user-images.githubusercontent.com/33732800/227222427-0efbde39-6ed0-4c31-8dc6-e045400f40fa.png)

 third image
![image](https://user-images.githubusercontent.com/33732800/227222756-a9eded3b-97ca-473c-810f-1ae896550d17.png)
![image](https://user-images.githubusercontent.com/33732800/227222866-a203832c-f037-4049-b9b1-ba0ca955491b.png)

### Steps to Reproduce

**This is the code generated by PayPal for the Smart Button Checkout Payment**

```
<div id="smart-button-container">
      <div style="text-align: center;">
        <div id="paypal-button-container"></div>
      </div>
    </div>
  <script src="https://www.paypal.com/sdk/js?client-id=sb&enable-funding=venmo&currency=USD" data-sdk-integration-source="button-factory"></script>
  <script>
    function initPayPalButton() {
      paypal.Buttons({
        style: {
          shape: 'rect',
          color: 'gold',
          layout: 'vertical',
          label: 'paypal',
          
        },

        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{"amount":{"currency_code":"USD","value":1}}]
          });
        },

        onApprove: function(data, actions) {
          return actions.order.capture().then(function(orderData) {
            
            // Full available details
            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));

            // Show a success message within this page, e.g.
            const element = document.getElementById('paypal-button-container');
            element.innerHTML = '';
            element.innerHTML = '<h3>Thank you for your payment!</h3>';

            // Or go to another URL:  actions.redirect('thank_you.html');
            
          });
        },

        onError: function(err) {
          console.log(err);
        }
      }).render('#paypal-button-container');
    }
    initPayPalButton();
  </script>
```

### Link to public reproduction project repository

https://github.com/MarcoErlwein/MyWallet

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS

### Affected platform versions

IOS 15

**Comment by Eilon** [comment]
Hi @MarcoErlwein , it looks like the repo https://github.com/MarcoErlwein/MyWallet is not available or not public. Can you check that?

Also, can you point us to info on the PayPal SDK/docs that you're using? It's possible that it isn't supported in hybrid apps.

**Comment by MarcoErlwein** [comment]
> Hi @MarcoErlwein , it looks like the repo https://github.com/MarcoErlwein/MyWallet is not available or not public. Can you check that?
> 
> Also, can you point us to info on the PayPal SDK/docs that you're using? It's possible that it isn't supported in hybrid apps.

I already changed the repository to public.
This is the link to the PayPal documentation: https://www.paypal.com/buttons/smart

**Comment by Eilon** [comment]
@MarcoErlwein thanks, I can access the repo now.

It would be more helpful for us to investigate if the repro is complete and minimal. The provided sample is only a few files without any required project or references, so we would not be able to run it easily. Could you please provide a complete and minimal repro for it?
