### ISSUE TITLE
Assets file doesn't have a target for net7.0

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#14175]
### Description

This is an ongoing, intermittent, but persistent issue that the entire team are having to deal with every day. 

![image](https://user-images.githubusercontent.com/32165641/227378617-8323b221-36c8-424b-9ac4-fa556bcc1918.png)

I have the exact same file in a different branch and it is building:

![image](https://user-images.githubusercontent.com/32165641/227378720-2191c75c-ca8a-4149-b0eb-31791db6bfcf.png)

The issue is worse in VS for Mac - it's almost impossible to not get it to happen.

### Steps to Reproduce

No idea. It just happens. Go away for a while then come back and it suddenly builds without any changes taking place.

### Link to public reproduction project repository

?

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11 - 13, iOS 16

### Did you find any workaround?

No

> VS bug [#1779588](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1779588)

**Comment by MagicAndre1981** [comment]
clean obj folder to let VS restore nuget packages.

**Comment by williambuchanan2** [comment]
> clean obj folder to let VS restore nuget packages.

Tried that at least 5 times but no change. We call that the 'cleaning ritual' because that's what you have to do to get it to build.

**Comment by MagicAndre1981** [comment]
also report it via Feedback tool from Visual Studio, this is a VS tooling issue

**Comment by mariaghiondea** [comment]
Can you please log this through Visual Studio?

**Comment by williambuchanan2** [comment]
I did: https://developercommunity.visualstudio.com/t/Assets-file-issue-on-build/10312467 

Nothing came of that either :(

**Comment by jfversluis** [comment]
The VS feedback ticket is the right place and is still open. Closing this here.
