### ISSUE TITLE
Unable to scroll to keyboard

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#14173]
### Description

This issue has been closed off as a duplicate before - but it isn't. There are a few different keyboard problems which look similar but aren't.

With this one, I have a form with a lot of entry fields on it:
![image](https://user-images.githubusercontent.com/32165641/227361445-a1f81f73-8e0a-444a-aa2a-b649505283a1.png)

The last field (which I can scroll to before the keyboard shows) has 'reach me' in it:

![image](https://user-images.githubusercontent.com/32165641/227361579-bd6b34e8-6aa5-49c0-852d-c375e7c3a155.png)

When the keyboard shows (the result of tapping in one of the top fields) I can no longer scroll to the bottom of the page. So I can no longer get to the bottom fields. This is because the keyboard has rendered on top of those fields, and the page (despite being in a scroll view) no longer scrolls into view.

![image](https://user-images.githubusercontent.com/32165641/227361777-2710e701-1b9a-40ad-9b8e-9fb60fc49099.png)

See example app from repository below.

### Steps to Reproduce

Open example solution from repo below.
Tap 'Keyboard Problem' button.
Tap on a field on the top of the page - ensure the keyboard shows.
Now try to scroll to the bottom - you can't

### Link to public reproduction project repository

https://github.com/williambuchanan2/MauiNavigation

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11 - 13, iOS 16

### Did you find any workaround?

Only workaround so far is to add a fixed height (same height as keyboard) empty border to the bottom of every page.

**Comment by radderz** [comment]
@williambuchanan2 how are you determining the height of the keyboard as part of your work around?

I am using Maui.Blazor and have the same issue where the web elements get covered by the keyboard and I haven't found a simple way to capture when the keyboard becomes visible and what the height of the keyboard is on android/iOS.

#14197

**Comment by radderz** [comment]
By doing this,

I find that iOS and Android both react the same way, where they resize the Content Page to the remainder of the screen, if this is sufficient for your issue you can do the below. iOS does this by default and Android by default seems to do nothing or maybe does the pan option (which doesn't work if the item is at the bottom of the scroll view.

```

using Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;
using Application = Microsoft.Maui.Controls.Application;

namespace SoftKeyboardBug;

public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		MainPage = new MainPage();

        Current.On<Microsoft.Maui.Controls.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize);
    }
}

```

**Comment by williambuchanan2** [comment]
> By doing this,
I had already tried it but it doesn't fix the problem for me. I am seeing the problem on both Android and iOS.

**Comment by williambuchanan2** [comment]
> @williambuchanan2 how are you determining the height of the keyboard as part of your work around? 

To be honest my workaround is a quick band aid because I don't have time to fix it. I just set it to a fixed height.

**Comment by williambuchanan2** [comment]
I decided to try it again. Sure enough it works for Android (not sure why it didn't the last time I tried it), but iOS is still not working. Here is what I see. I can't scroll past the 'Mobile' field:

![image](https://user-images.githubusercontent.com/32165641/228187354-e979e43d-b26c-4413-bc7f-ec29d062695e.png)

**Comment by radderz** [comment]
> I decided to try it again. Sure enough it works for Android (not sure why it didn't the last time I tried it), but iOS is still not working. Here is what I see. I can't scroll past the 'Mobile' field:
> 
> ![image](https://user-images.githubusercontent.com/32165641/228187354-e979e43d-b26c-4413-bc7f-ec29d062695e.png)
> 

You'll possibly need the view to be in a scroll view if it isn't already so that the view which is now shrunk can fit in the content page without overflowing past the bottom. 

In my case I was using maui blazor which is a web view and scrollable. The bottom of my control was the top of the keyboard.

**Comment by williambuchanan2** [comment]
It already is. Here is the Xaml for the top of the page:

````
    <ContentPage.Content>
            <ScrollView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Margin="0" Padding="0">
                <VerticalStackLayout VerticalOptions="Center">


````

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on android platform with sample project.
[MauiNavigation-main.zip](https://github.com/dotnet/maui/files/11765748/MauiNavigation-main.zip)
![14173](https://github.com/dotnet/maui/assets/77434865/35487e18-53c1-454e-acfe-f721051feee9)
