### ISSUE TITLE
HorizontalOptions/VerticalOptions property to Frame not working , Android  .NET 7.0

### ISSUE THREAD

**Issue by sswi** [dotnet/maui#14188]
### Description

HorizontalOptions/VerticalOptions property to Frame not working 
 platform： Android   (.NET 7.0)

![Snipaste_2023-03-24_23-50-16](https://user-images.githubusercontent.com/39110708/227576988-029a5665-f7c8-4b17-9a74-6ddd642a1017.png)
![Snipaste_2023-03-24_23-51-16](https://user-images.githubusercontent.com/39110708/227577008-d4951ed4-ad47-45ee-b3ec-fe50f837c8f3.png)

![Snipaste_2023-03-24_23-52-31](https://user-images.githubusercontent.com/39110708/227577263-4aee5375-7e83-43db-bd75-a5b17656abce.png)

### Steps to Reproduce

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp5.MainPage">

    <Frame 
        BackgroundColor="Aqua"
        WidthRequest="100"
        HeightRequest="100" 
        HorizontalOptions="Center" 
        VerticalOptions="Center"
        />

</ContentPage>

### Link to public reproduction project repository

https://github.com/sswi/Frame-Not-Working

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

Android11

**Comment by sswi** [comment]
sorry
Version with bug =.Net 7.0

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on .NET 7 android platform with above code.
![Screenshot 2023-06-16 101317](https://github.com/dotnet/maui/assets/77434865/7f8e3380-5d0c-4eaf-95e6-04cfe1183177)
