### ISSUE TITLE
BlazorWebView/WebView2 Transparent background not transparent on Windows

### ISSUE THREAD

**Issue by StonedHackerman** [dotnet/maui#14185]
### Description

# What I did
I created a project from the default template ".NET MAUI Blazor App". In the MainPage I created a Label and a BlazorWebView which I shifted up a bit, so that it partly convers the Label. Then, I did these steps to make sure the page displayed in the BlazorWebView has transparent background:

- Set the page's body background-color to transparent with CSS
```
html, body {
    background-color: transparent;
}
```

- Set the BlazorWebView's backgroud color to transparent
```
<BlazorWebView x:Name="BlazorWebView" HostPage="wwwroot/index.html" BackgroundColor="Transparent" Margin="0,-10,0,0" MinimumHeightRequest="20">
```

- Explicitly set the internal WebView2's DefaultBackgroundColor to transparent in an OnLoaded event handler
```
private void MainPage_OnLoaded(object sender, EventArgs e)
    {
        #if WINDOWS
        
        var webView = (BlazorWebView.Handler.PlatformView as Microsoft.UI.Xaml.Controls.WebView2);

        webView.DefaultBackgroundColor = Windows.UI.Color.FromArgb(0, 0, 0, 0);

        #endif
    }
```

- Displayed a Razor page directly, containing only a single P element, to make sure no other HTML elements are blocking the transparency

MainPage.xaml
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:TransparencyTest.Pages"
             x:Class="TransparencyTest.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}"
             Loaded="MainPage_OnLoaded">

    <StackLayout>
        <Label>This is a MAUI label</Label>

        <BlazorWebView x:Name="BlazorWebView" HostPage="wwwroot/index.html" BackgroundColor="Transparent" 
                       Margin="0,-10,0,0" MinimumHeightRequest="20">
            <BlazorWebView.RootComponents>
                <RootComponent Selector="#app" ComponentType="{x:Type pages:Index}" />
            </BlazorWebView.RootComponents>
        </BlazorWebView>
    </StackLayout>

</ContentPage>
```

Index.razor
```
@page "/"

<p style="margin: 0">This is a P from Blazor</p>

```

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
    <title>TransparencyTest</title>
    <base href="/" />

    <link href="css/app.css" rel="stylesheet" />
    <link href="TransparencyTest.styles.css" rel="stylesheet" />
</head>

<body>

    <div class="status-bar-safe-area"></div>

    <div id="app">Loading...</div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.webview.js" autostart="false"></script>

</body>

</html>
```

# Result on Android (correct expected behavior)
On Android, I can correctly see the text in the P element on the Razor page inside a BlazorWebView overlayed on top of the MAUI Label

<img width="410" alt="Screenshot 2023-03-24 14 54 27" src="https://user-images.githubusercontent.com/16528222/227549506-679b98e8-24a8-47f2-bdd6-4994a341d318.png">

# Result on Windows (incorrect behavior)
On Windows, the background is not transparent

<img width="469" alt="Screenshot 2023-03-24 14 52 56" src="https://user-images.githubusercontent.com/16528222/227551044-1151b7df-8e9e-48ed-babe-e29038677b0e.png">

The color displayed must be somehow related to the current Windows theme, because when I change my Windows theme from Dark to Light, the BlazorWebView's background color changes too

<img width="459" alt="Screenshot 2023-03-24 15 22 49" src="https://user-images.githubusercontent.com/16528222/227551434-46e570a6-6af0-4636-af62-c58796828d3a.png">

According to this link to Microsoft's official documentation, setting a WebView2's DefaultBackgroundColor to transparent is supported:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.defaultbackgroundcolor?view=webview2-dotnet-1.0.864.35#microsoft-web-webview2-core-corewebview2controller-defaultbackgroundcolor

Which leads a logical conclusion that this is a bug, and the background should be transparent, like on Android.

# Platforms/versions
I'm using VS Community 2022 v17.5.3 and the latest MAUI workload

The project contains these `TargetFrameworks`: (just the defaults from the template)
```
<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
        
```

This is the output from `dotnet workload list`
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.59/7.0.100         VS 17.5.33516.290
maui-maccatalyst           7.0.59/7.0.100         VS 17.5.33516.290
maccatalyst                16.2.1024/7.0.100      VS 17.5.33516.290
maui-ios                   7.0.59/7.0.100         VS 17.5.33516.290
android                    33.0.26/7.0.100        VS 17.5.33516.290
ios                        16.2.1024/7.0.100      VS 17.5.33516.290
wasm-tools                 7.0.4/7.0.100          VS 17.5.33516.290
maui-android               7.0.59/7.0.100         VS 17.5.33516.290
```

### Steps to Reproduce

1. Download the code from the [example repo](https://github.com/StonedHackerman/MauiBlazorWebViewTransparencyTest/tree/main/TransparencyTest)
2. Run on Windows
3. See bug

### Link to public reproduction project repository

https://github.com/StonedHackerman/MauiBlazorWebViewTransparencyTest/tree/main/TransparencyTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

No, nothing I tried worked and no amount of Googling helped

**Comment by Eilon** [comment]
This might be a limitation of the WebView2 control on WinUI, which is what .NET MAUI uses on Windows. We'll have to check.

**Comment by StonedHackerman** [comment]
It also seems to work under WPF (which also uses the same WebView2 no?), e.g. as this StackOverflow post shows:
https://stackoverflow.com/questions/67838739/how-to-use-transparency-in-webview2

**Comment by Eilon** [comment]
Indeed, I recall the WPF issue, so I wonder if the same type of issue exists on WinUI as well. I found this issue, which seems to indicate that others have the same issue:: https://github.com/microsoft/microsoft-ui-xaml/issues/6527

**Comment by Eilon** [comment]
The other issue suggests that there could be a fairly easy workaround: https://github.com/microsoft/microsoft-ui-xaml/issues/6527#issuecomment-1274932222

So you could easily try that in an `#if WINDOWS` section in your app's `MauiProgram.cs`.

**Comment by StonedHackerman** [comment]
I inserted these lines in `MauiProgram.cs` at the beginning of the CreateMauiApp() method
```
#if WINDOWS

Environment.SetEnvironmentVariable("WEBVIEW2_DEFAULT_BACKGROUND_COLOR", "0");

#endif
```
But the result is still the same. I also tried inserting this in the constructor of `MainPage` and the constructor of `App` in `Platforms/Widows/App.xaml.cs` but nothing ever changed

**Comment by Eilon** [comment]
Hmm then possibly the workaround just doesn't work? Because that's otherwise the same as what the others were saying in the WebView2 thread.

**Comment by Eilon** [comment]
Hmm yeah I don't see it working either in my test.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on windows platform with sample project. https://github.com/StonedHackerman/MauiBlazorWebViewTransparencyTest/tree/main/TransparencyTest.

**Comment by mhrastegari** [comment]
So how's the new Outlook doing it? it's web based too.

![Screenshot (20)](https://github.com/dotnet/maui/assets/42671084/fd995e60-b68b-4f4c-aa6a-eef51ef940da)

**Comment by SimenCTan** [comment]
Have there been any updates regarding this issue

**Comment by SimenCTan** [comment]
> to resolve the issue on macOS
```
  public static void ModifyBlazorWebView() 
  {
      ViewHandler.ViewMapper.AppendToMapping(nameof(IView.Background), (handler, view) =>
      {
#if MACCATALYST || IOS
          if (handler.PlatformView is WKWebView wv)
          {
              wv.Opaque = false;
              wv.BackgroundColor = UIColor.Clear;
          }
#endif
      });
  }
```

**Comment by everharder** [comment]
Any news on this?

**Comment by shyqrirama** [comment]
This Solution seems to work,  create a new control that inherits the base class BlazorWebView, and then based on platform(when on windows) add init event. Add the below code and the issue seems to go away.

private async void BlazorWebView_BlazorWebViewInitialized(object? sender, Microsoft.AspNetCore.Components.WebView.BlazorWebViewInitializedEventArgs e)
{
    e.WebView.DefaultBackgroundColor = Windows.UI.Color.FromArgb(0, 255, 255, 255);
    await e.WebView.EnsureCoreWebView2Async();
}

**Comment by everharder** [comment]
@shyqrirama Unfortanetly the solution doesn't work for me.
In the screenshot, the expected background color for the embedded website is blue (because that's the background color of the MainPage).

![issue](https://github.com/dotnet/maui/assets/7161230/4e10fbf6-f333-40c6-857d-1161354d3d69)

Can you maybe provide a minimal working example of your solution?

**Comment by mkArtakMSFT** [comment]
Closing as this is not something we control: https://github.com/microsoft/microsoft-ui-xaml/issues/6527
