### ISSUE TITLE
Android local pdf file path as source of webview is not displaying

### ISSUE THREAD

**Issue by amose-123** [dotnet/maui#14184]
HI ,

I am working on displaying the pdf file in a webview, pdf file is saved in app local folder. i am giving webview.source = /storage/emulated/0/Android/data/.................    but it is not displaying the pdf. Also i tried webview.source = file:///storage/emulated/0/Android/data/................. it is not working. Please me on this. Thanks in advance

**Comment by Eilon** [comment]
Hi @amose-123 can you please share a complete app that demonstrates the issue and upload it to a public GitHub repo? There might not be enough info to investigate this.

**Comment by amose-123** [comment]
Pdf file is saved in this path /storage/emulated/0/Android/data/................. 

if we give this path as source of webview, the file is not displaying in webview. How can i  give the source for the webview to display the pdf file in the webview?

some security purpose i unable to share a project. I try to share a sample project, in the mean time if you get any answer for this issue please let me know.

My problem is how can set app local path as source for the webview ?

**Comment by amose-123** [comment]
Any update on the above?

**Comment by flipper09112** [comment]
Some workarround that not use .js?
