### ISSUE TITLE
Xamarin.Forms UWP CollectionView Memory leak

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#14194]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/XamarinForms-UWP-CollectionView-Memory-/10319497)._

---
[severity:I'm unable to use this version]
I am experiencing a memory leak when I use the Collectionview on UWP.
In my app I Bind the ItemsSource and ItemsLayout properties and update them on resize of the main window.
I have a reproducable scenario in this repo: https://github.com/sjorsmiltenburg/XF.UWP.Collectionview.MemoryLeak

to reproduce:
- run the app (UWP)
- make the window small, so only a few images are shown per row (not minimized)
- alternate the window size between fullscreen and small, and see the memory footprint of the app rise and not come down

Because my actual application refreshes the collectionview in more occasions then only during resize, this problem makes my application slow / unusable on production.

---
#### Feedback Bot on 3/23/2023, 07:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
This seems to be about Xamarin.Forms, and also reported here: https://github.com/xamarin/Xamarin.Forms/issues/15717

A fix for .NET MAUI seems to be already been implemented here: https://github.com/dotnet/maui/pull/14075
