### ISSUE TITLE
error NETSDK1139: The target platform identifier tizen was not recognized. 

### ISSUE THREAD

**Issue by jessejiang0214** [dotnet/maui#14206]
### Description

Hi team, 

My UnitTest project use MAUI as project reference. 
I build everything is ok on my end. But it failed in Github Action. 

It cannot restore NuGet. 
```
/Users/runner/.dotnet/sdk/7.0.202/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(112,5): error NETSDK1139: The target platform identifier tizen was not recognized. [/Users/runner/work/Comet/Comet/External/Maui/src/Graphics/src/Graphics.Skia/Graphics.Skia.csproj::TargetFramework=net7.0-tizen]
```

I tried to `dotnet workload restore`,  build MAUI on that agent, but seems not working.

The MAUI source code I used this tag https://github.com/dotnet/maui/releases/tag/7.0.59 

Any idea about this?

### Steps to Reproduce

Not sure if you can see this Action, the details are all in log 
https://github.com/flyperstudio/Comet/actions/workflows/test.yml 

### Link to public reproduction project repository

https://github.com/flyperstudio/Comet

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MAUI 7.0.59

**Comment by jfversluis** [comment]
I see here are different instructions on how to install the Tizen workload: https://github.com/Samsung/Tizen.NET/wiki/Installing-Tizen-.NET-Workload#install-tizen-net-workload-2 that seems also what we are using for the .NET MAUI Community Toolkit.

If you try to add that, does that work?

**Comment by jessejiang0214** [comment]
Hi @jfversluis , 

Thanks for your reply, another question is, if possible to build the project only target to .Net7, not include the platforms like iOS, Android etc.

Thanks
Jesse

**Comment by jfversluis** [comment]
Sure! You can specify the `-f` switch with the TFM you want to build specifically. For instance: `dotnet build -f net7.0-ios`. If you have a `net7.0` in there, you should be able to just to `dotnet build -f net7.0`.

Going to assume this is all fixed now for you, good luck!
