### ISSUE TITLE
Update Templates to Make Developing a Maui Blazor MacCatalyst app a Better Experience

### ISSUE THREAD

**Issue by dustin-wojciechowski** [dotnet/maui#14219]
### Description

This issue is an adaption of one for Xamarin-macios for maui: https://github.com/xamarin/xamarin-macios/issues/17591
It can be difficult to get everything correctly aligned for publishing, so we might want to add comments to templates to show developers what they need to do depending on what they want to do.

A list of problems for Mac Catalyst are described here: https://github.com/dotnet/maui/issues/12293

1. App rejected because: The product archive package's signature is invalid. Ensure that it is signed with your "3rd Party Mac Developer Installer" certificate. A commented section in csproj explaining what they need to do might help here.
2. App rejected because: The product archive is invalid. The Info.plist must contain a LSApplicationCategoryType key, whose value is the UTI for a valid category. For more details, see "Submitting your Mac apps to the App Store". A commented section in the Info.plist might be helpful.
3. App rejected because: Invalid bundle. The bundle supports arm64 but not Intel-based Mac computers. Your build must include the x86_64 architecture to support Intel-based Mac computers. A commented section in csproj explaining that if only x64 or arm64+x64 (but not just arm64) is valid for publishing would help.
4. App rejected because: `Invalid Bundle. The key UIDeviceFamily in the app's Info.plist file contains one or more unsupported values '1'. We should probably validate this at build time.
5. App rejected because: App sandbox not enabled. The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list [...]. A commented section in the Entitlements.plist might be helpful. Alternatively we could default to include this entitlement by default for release builds (but verify that we don't end up with builds that won't execute locally).
6. "I had to add ITSAppUsesNonExemptEncryption to Info.plist." A commented section in the Info.plist might be helpful.

## Action Items
1. Add commented section to csproj for selecting correct runtime.
2. Add commented section to csproj about code/package signing.
3. Add `com.apple.security.get-task-allow` to Enlistments.Debug to allow use of Web Dev Tools during debugging.
4. Add `com.apple.security.app-sandbox` and `com.apple.security.network.client` to Enlistments.Release to allow for publishing to App Store.
5. Add `ITSAppUsesNonExemptEncryption` and `LSApplicationCategoryType` to Info.Plist.

### Steps to Reproduce

1. Create a new Maui Blazor app.
6. Set configuration to Release
7. Try to publish to the App Store.

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

8.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Ventura 13.0, macOS Ventura 13.1

**Comment by drasticactions** [comment]
Are these issues specific to publishing MAUI UI Catalyst apps, or could they be hit if you're publishing Catalyst apps in general?

**Comment by dustin-wojciechowski** [comment]
@drasticactions Most are in general. We have a lot of these additions added in on the Xamarin-macios side: https://github.com/dotnet/maui/pull/14117
