### ISSUE TITLE
CollectionView+FormattedString Poor Performance

### ISSUE THREAD

**Issue by shadowfoxish** [dotnet/maui#14222]
### Description

When using a Collection View with a formatted string inside a grid, the scroll performance or framerate is severely reduced. 

Similar issue was found Open in the Xamarin Forms repo: https://github.com/xamarin/Xamarin.Forms/issues/5087

Here is a video of it scrolling smoothly (using a model property)

https://user-images.githubusercontent.com/12143535/228093105-21e2cc76-2d28-4252-afa2-814ccfaef1dd.mp4

And a video of it very choppy (using FormattedString)

https://user-images.githubusercontent.com/12143535/228093142-8d3c00fa-0ef0-4d7b-a322-83c9da1de010.mp4

Its subtle, but noticeable enough to be a problem for users.

### Steps to Reproduce

1. Add a CollectionView with an Item Template. 
2. Inside the item template add a grid and display some Labels. 
3. Include a label with a few Spans in formatted string. 
4. Observe performance impact versus a code-centric model binding.

### Link to public reproduction project repository

https://github.com/shadowfoxish/Temp-CollectionViewFormattedStringSlowness

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Tested on Android 9.0, API 28

### Did you find any workaround?

Using a get-only model property eliminates the need for FormattedString, but breaks the Model-View-ViewModel paradigm as it pushes UI logic into the Model or ViewModel.

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by jonathanpeppers** [comment]
@shadowfoxish it looks like your views are in Debug mode with XAML Hot Reload connected on an emulator. I wouldn't measure performance using Debug mode.

How do things fare on a physical Android device in Release mode? That is where we should be testing this.

**Comment by shadowfoxish** [comment]
Hi @jonathanpeppers,
I used OBS studio to put those videos together, I was using a physical device (not emulated) and recording the video from miracast/connect. But, they were definitely both in debug mode.

I set the project up for a release-mode build and deployed that, and the performance is definitely better in RELEASE mode, but I can still definitely "feel" some choppiness on the view when its rendered with FormattedString. When its using the model property, it scrolls like butter.

(If you tried it with release, it probably failed for you, there was a missing style in the styles.xaml that was causing a crash in release mode that wasnt present in debug. I updated the repo with this change.)

**Comment by jonathanpeppers** [comment]
Looks like ~6.8% of the time is spent in:

![image](https://user-images.githubusercontent.com/840039/228677172-68a8a2aa-05eb-4626-bf9c-58912fffd0c6.png)

[formattedstring.zip](https://github.com/dotnet/maui/files/11105836/formattedstring.zip)

Very similar to what I did here: https://github.com/dotnet/maui/pull/14275

I think we can move these types to Java and do less Java to C# interop:

https://github.com/dotnet/maui/blob/cbce20c8ab7289fe8f2bfef427e359364ff5f7b7/src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs#L235-L244

**Comment by shadowfoxish** [comment]
If I may ask, what are you using to profile this code?

**Comment by jonathanpeppers** [comment]
I'm using `dotnet-trace` and opening these files in speedscope, docs for each platform are at: https://aka.ms/profile-maui

**Comment by sencagri** [comment]
Is there any workaround except binding to formatted property? 

And it would be awesome that both MAUI Label and CollectionView documents have warnings about these issues.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 6.0. Can repro on android and ios platform with sample project.
[CollectionView.zip](https://github.com/dotnet/maui/files/12299332/CollectionView.zip)

**Comment by abelgarciasaiz** [comment]
Hi, i have the same problem and i'm forced to redesign many of the lists i have. Is there any update?
i'm using latest net 8
thanks

**Comment by jonathanpeppers** [comment]
@abelgarciasaiz are you able to take my suggestion instead: https://github.com/dotnet/maui/issues/14222#issuecomment-1598809599

If you format strings in your ViewModel layer, no C#-Java interop will occur.

**Comment by abelgarciasaiz** [comment]
Yes, a bit better but laggy. Even so, doing that forces me to move styling stuff outside the view to the dto model and mix concepts. The reason to use formatted text is to use different font style in each part.

**Comment by williambuchanan2** [comment]
We are getting similar jitter as per this bug report:
https://github.com/dotnet/maui/issues/19383

Seems to be a common theme with collection view.

**Comment by jonathanpeppers** [comment]
@williambuchanan2 this issue is specifically about `<FormattedString/>`. It does a *lot* of C# / Java interop currently. It only slows down a `CollectView`, because it would spend additional CPU time on each row.

Is it an option to do something like this instead?

```csharp
public string QuantityText => $"{Quantity}: [{UnitOfMeasure} / {UnitSize}]";
```

Then you'd bind to this property instead of creating a `<FormattedString/>` with 3 bindings. That would be considerably faster *even if* we did some work to improve `<FormattedString/>`.
