### ISSUE TITLE
CharacterSpacing Causes Button Layout to be Incorrect

### ISSUE THREAD

**Issue by matthericks** [dotnet/maui#14243]
### Description

character spacing appears to not be accounted for when calculating the size and spacings on a button.

<img width="922" alt="Screenshot 2023-03-28 at 12 04 43 PM" src="https://user-images.githubusercontent.com/19779550/228319699-7aac4149-6429-420b-9ee3-845058131bed.png">

### Steps to Reproduce

Create project
Add button with text and an image
duplicate that button, but set the character spacing to 2

Notice that the second button is sized improperly and various paddings and contentlayout are incorrect.

### Link to public reproduction project repository

https://github.com/matthericks/button-content-layout

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16.2

### Did you find any workaround?

Could probably make my own content view with a a tapped gesture recognizer and manually measure the string length for resizing and spacing purposes, but that feels a bit silly for a button.

**Comment by softlion** [comment]
If I remember the release notes for version 8 (which is the current alpha), it's already fixed.

**Comment by hartez** [comment]
This may have been fixed by #10293; we need to validate that.

**Comment by jknaudt21** [comment]
Hey @hartez,
I validated this issue and it seems to be fixed. There were couple of button-related issues I uncovered that seem loosely related to this one, however. Should I still close this one?

#15004, #15003, and #15002.

**Comment by hartez** [comment]
@jknaudt21 Thanks for validating! Since we've got open issues tracking those other problems, we'll close this one.
