### ISSUE TITLE
Support DisplayAlert from PresentedViewController

### ISSUE THREAD

**Issue by marekm294** [dotnet/maui#14258]
### Description

Currently it's not possible to use DisplayAlert from Maui CommunityToolkit Popup on iOS - mentioned in https://github.com/CommunityToolkit/Maui/issues/1106. It works with code below (just an example) but I think it should be implemented in MAUI.

```
    internal static async Task<bool> ShowAlertAsync(string title, string message, string confirm, string close)
    {
        var window = UIApplication.SharedApplication.Delegate.GetWindow(); 
        if (window.RootViewController.PresentedViewController is null)
        {
            return await ShowAlertFromPageAsync(title, message, confirm, close);
        }
        
        var result = new TaskCompletionSource<bool>();
        var confirmAlertController = UIAlertController.Create(title, message, UIAlertControllerStyle.Alert);

        confirmAlertController.AddAction(UIAlertAction.Create(confirm, UIAlertActionStyle.Default, alert => result.SetResult(true)));
        confirmAlertController.AddAction(UIAlertAction.Create(close, UIAlertActionStyle.Cancel, alert => result.SetResult(false)));

        window.RootViewController.PresentedViewController.PresentViewController(confirmAlertController, true, null);

        return await result.Task;
    }
```

### Public API Changes

No changes would be required. There should be still used DisplayAlert(title, message, confirm, close)/DisplayAlert(title, message, close) etc. 

### Intended Use-Case

Using Display Alert etc from Maui ComunnityToolkit Popup

**Comment by PureWeen** [comment]
This will most likely be resolved by https://github.com/dotnet/maui/pull/12910

**Comment by marekm294** [comment]
@jfversluis - you closed related issue in community toolkit. Should be this issue closed too?

**Comment by jfversluis** [comment]
Yeah as mentioned this is likely to be resolved with the PR above and not sure if this is something we should fix on our side at this time. Thanks!
