### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by MrsLeigh** [dotnet/maui#14267]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Just doing the initial build of the application after I turned on the Developer Mode I got this set of error messages as shown below

**Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80073D1F]	MyFirstMauiApp	
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4044	The "GenerateResourceDesigner" task was not given a value for the required parameter "JavaPlatformJarPath".	MyFirstMauiApp	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.26\tools\Xamarin.Android.Common.targets	1025**

**Comment by Eilon** [comment]
Paging Mr. @jonathanpeppers .

**Comment by jonathanpeppers** [comment]
Can you share a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) of this error?

If you hit this in a brand new, empty project, it seems like something went wrong with your installation? The error means the MSBuild `.targets` file doesn't match the `.dll` file that contains the `GenerateResourceDesigner` class.

**Comment by MrsLeigh** [comment]
When I try to run the build after adding the debugging steps as described this is the output that I get.  Incidently the build isn't successful though.

Thank you.

IsEmulatorSupported: START
	Is64BitOperatingSystem = True
DetectSlat: START
	isHyperVRunning = False
	isHardwareVirtualizationSupported = True
	isHardwareVirtualizationEnabledInBIOS = True
DetectSlat: END (Success, 0:00:01.173)
	SlatState = SlatAndHWVEnabled
	IsEmulatorSupported = True
IsEmulatorSupported: END (Success, 0:00:01.199)

**Comment by mattleibow** [comment]
This looks like 2 errors for 2 separate platforms?

* Error DEP0700: Registration of the app failed. [0x80073D1F] MyFirstMauiApp

* Error MSB4044 The "GenerateResourceDesigner" task was not given a value for the required parameter "JavaPlatformJarPath". MyFirstMauiApp C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.26\tools\Xamarin.Android.Common.targets 1025

**Comment by MrsLeigh** [comment]
I just set up the application like the demo documentation said to set it up?  So I'm not sure if the documentation is missing in the setup. But this is my first attempt to run anything in Maui,  so I do not know what I am looking for to know where to even start.

**Comment by mattleibow** [comment]
Can you attach a binlog following these steps? https://github.com/xamarin/xamarin-macios/wiki/Diagnosis
