### ISSUE TITLE
Style (BackgroundColor) is not reflect correctly when in release mode

### ISSUE THREAD

**Issue by eyeveye** [dotnet/maui#14266]
### Description

Code behind applying the style for label. During debug mode is working but not in release mode. 

Example of the code:

`    <Style x:Key="selectedTabLabel" TargetType="Label">
        <Setter Property="HorizontalOptions" Value="FillAndExpand" />
        <Setter Property="VerticalOptions" Value="FillAndExpand" />
        <Setter Property="HorizontalTextAlignment" Value="Center" />
        <Setter Property="VerticalTextAlignment" Value="Center" />
        <Setter Property="TextColor" Value="{DynamicResource White}" />
        <Setter Property="BackgroundColor" Value="{DynamicResource Primary}" />
    </Style>`

` <Grid
                ColumnDefinitions="*,auto,*,auto,*"
                IsClippedToBounds="True"
                VerticalOptions="FillAndExpand">
                <Label
                    x:Name="lblFd" FontAutoScalingEnabled="False"
                    Style="{DynamicResource tabLabel}"
                    Text="A"/>
                <BoxView
                    Grid.Column="1"
                    BackgroundColor="White"
                    Style="{StaticResource tabBoxview}" />
                <Label
                    x:Name="lblToto"
                    Grid.Column="2" FontAutoScalingEnabled="False"
                    Style="{DynamicResource tabLabel}"
                    Text="B"/>
                <BoxView Grid.Column="3" Style="{StaticResource tabBoxview}" />
                <Label
                    x:Name="lblSweep" FontAutoScalingEnabled="False"
                    Grid.Column="4"
                    Style="{DynamicResource tabLabel}"
                    Text="C"/
            </Grid>`

`if(Application.Current.Resources.TryGetValue("selectedTabLabel" +
                "", out object selectedTabLabel_style)
lblFd.Style = selectedTabLabel_style as Style;`

### Steps to Reproduce

1) Create a style in style.xaml
2) Apply a style in code behind

### Link to public reproduction project repository

NIL

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android33

**Comment by gabsamples6** [comment]
@mattleibow hi this is making all our app unworkable, any chance of this being merged in .net 7 next visual studio release? It has such impact if you rely on this for every page in the app

thanks for your time in advance
