### ISSUE TITLE
.net maui & ios

### ISSUE THREAD

**Issue by ourweb4** [dotnet/maui#14273]
### Description

I am using xcode 14 on the lastest version mac os . I dont see any ios stimulator or my iphone or mt ipad . Can you tell me when or if this problem resolved please? Thank you Bill

### Steps to Reproduce

Im writing a program app

### Link to public reproduction project repository

na

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

ios 16

> VS bug [#1781902](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1781902)

**Comment by ourweb4** [comment]
Any news?

**Comment by mariaghiondea** [comment]
As mentioned above, please log this using the Visual Studio Report a Problem too. That will give us more information and logs.

**Comment by SagarPanwala** [comment]
@ourweb4 
These seems similar to yours. After installing ios package it started working  for me.

https://github.com/xamarin/xamarin-macios/issues/17561

https://stackoverflow.com/questions/75942259/visual-studio-for-mac-not-seeing-simulators

**Comment by jinxinjuan** [comment]
This issue not repro on Visual Studio Enterprise 17.7.0 Preview 2.0.
