### ISSUE TITLE
[iOS] Trimming / AOT issue after publish in .NET MAUI Blazor app

### ISSUE THREAD

**Issue by ScarletKuro** [dotnet/maui#14271]
### Description

I'm not sure if this issue should go here or under the dotnet/runtime, but the problem is following.
MudBlazor users report problem when they publish app on iOS. Meanwhile, it runs normally in Debug / Release mode on the device.
The problem is shown in the stack trace. I suspect that the setter property is getting removed and then `SetParametersAsync` -> `ComponentProperties.SetProperties` throws exception, because it's using reflection to set the value.
At first I thought it's some MudBlazor trimming issue, but it's not. The razor components are protected via Blazor framework, the `RenderTreeBuilder`, `RootComponentMappingCollection` etc are annotated with `[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]` and it should preserve everything in the component.
Worth to mention that MudBlazor supports trimming in general, and it's used by many people and there was never such problem encountered.
The same code will work perfectly fine when used in Browser and published with trimming enabled!

If I'm not wrong, iOS has AOT compilation requirements, and maybe it's way too aggressive. I should note that Blazor supports only partial TrimMode, but I'm not sure if MAUI uses `ILLink` as Blazor WASM does. 

Additional information: Android is unaffected. Internal MudBlazor issue: https://github.com/MudBlazor/MudBlazor/issues/6310

### Steps to Reproduce

1. Clone reproduction link
2. Publish iOS and sign Ad Hoc / App Store
3. Install app
4. Launch

### Link to public reproduction project repository

https://github.com/QwertyMC/MauiBlazorTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 14 and higher

### Did you find any workaround?

No. Seems ILLink.Descriptors.xml / BlazorLinkerDescriptor doesn't have any effect.

### Relevant log output

```shell
Unable to set property 'Required' on object of type 'MudBlazor.MudTextField`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'. 
The error was: Attempting to JIT compile method '(wrapper delegate-invoke) void <Module>:invoke_callvirt_void_MudTextField`1<string>_bool (MudBlazor.MudTextField`1<string>,bool)' while running in aot-only mode. 
See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
:    at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at MudBlazor.MudBaseInput`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<>n__1(ParameterView parameters)
   at MudBlazor.MudBaseInput`1.<SetParametersAsync>d__177[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
```

**Comment by Eilon** [comment]
Blazor folks - I think we've seen similar issues when using MudBlazor before. Does this look familiar and/or related to past issues?

**Comment by ScarletKuro** [comment]
> I think we've seen similar issues when using MudBlazor before. Does this look familiar and/or related to past issues?

Doesn't look familiar. All previous issues were easy to trace and fix. It was mainly related to JS Interop.
In this case `Required` is just an bool property. There is no reflection from our side, only the ones that are happening [inside](https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Components/Components/src/Reflection/ComponentProperties.cs#L23) Blazor. There shouldn't be done anything special from MudBlazor in order for this property to be preserved since all the job is already done by the Blazor: [here](https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Components/WebAssembly/WebAssembly/src/Hosting/RootComponentMappingCollection.cs#L24) and [here](https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Components/Components/src/Rendering/RenderTreeBuilder.cs#L490), the `Index.razor`that contains the MudBlazor component is rendering it through `RenderTreeBuilder` that guarantees that everything inside the component is preserved.

**Comment by ScarletKuro** [comment]
Sorry to tag directly, but can you assist @vitek-karas

**Comment by ScarletKuro** [comment]
> What are the versions in use - the SDK version and TFM of the app?

As I understand TFM is net7.0-ios, sdk 7.0.104-7.0.202
Is this correct @assemblysoft?
Just in case, they have the same issue and they are ready to provide any assist:
> We are able to run the application on a physical iPhone (iOS) by distributing directly from Visual Studio (without the need for a MAC in between) and it works fine. As soon as we publish to the App Store or Testflight, although Apple is happy with the distribution, it fails as above. We have added remote logging, so we can capture the stack trace and happy to assist you with any additional info you might need. We are available anytime, if required to jump on a call or can share access to our app distribution in Testflight, if that helps.

**Comment by ScarletKuro** [comment]
Maybe worth to mention that
`MudTextField` is a generic a `MudTextField<T>` that inherits from `MudDebouncedInput<T>` -> `MudBaseInput<T>` -> `MudFormComponent<T, string>` -> `MudComponentBase` -> `ComponentBase`.

The `Required` property is located in `MudFormComponent<T, string>`.

Could it hit the Limited Generics Support in iOS AOT?

**Comment by assemblysoft** [comment]
> 
@ScarletKuro 
net7.0-ios (14.0) 7.0.59/7.0.100 ( VS 17.5.33516.290)

**Comment by assemblysoft** [comment]
> 
@ScarletKuro @rolfbjarne can confirm that after applying the above,  this has resolved the issue and we have successfully deployed and tested via App Store Connect (TestfFight).
Many Thanks both!

**Comment by ivanpovazan** [comment]
This seems to be a duplicate of: https://github.com/dotnet/maui/issues/13279 and further: https://github.com/dotnet/runtime/issues/78889

There is a global tracking issue: https://github.com/dotnet/runtime/issues/83329 which would hopefully resolve all related issues.

**Comment by ScarletKuro** [comment]
Thanks everyone for such fast help.
Ok, I will close the issue since apparently there are multiple issues created, but what I would like to happen is:

- The documentation gets improved and added to learn.microsoft. The `UseInterpreter` is hard discoverable option. I found it in EF core issue, and I wasn't sure what it's doing from the name and if it's AOT related. It's also hard to find the drawbacks of using this option.
- A better exception messages if applicable for this case.
-  Enabling interpreter by default when publishing on iOS since too many customers running into the problems rn.
- Improve AOT in the future, so that it could AOT-compile such cases.
