### ISSUE TITLE
Buttons at end of layout (and Gesture Recognizers) do not trigger! ... Unless you HOT RELOAD the page

### ISSUE THREAD

**Issue by innomotionmedia** [dotnet/maui#14292]
### Description

This issue is sooo annyoing.
There is no way of getting a button to work at the bottom of a page UNLESS every single element before that gets a fixed height. No matter wehter it is inside a stack layout, vertical one, grid, - all elements have to have a set size so that the buttons at the bottom work.

They work at the top - they work with some elements above them - but once they are inside a scrollview and at the bottom they stop working...

UNLESS you edit the layout live and let xaml hot reload reload the page. Then the button works but this one time.
STart the app anew and the button is broken again.

It is rendered fine.
Just not clickable. 

### Steps to Reproduce

new project, create views add button

### Link to public reproduction project repository

none

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

all

**Comment by innomotionmedia** [comment]
I have more info on that; the issue comes from the scrollview when data is populated into it later. It doesnt resize its layout. A workaround is to add an eventhandler to all the child layouts inside the scrollview that potentually could resize due to layout changes (item gets removed or added) and then for a resize on the scrollview:

    private void VerticalStackLayout_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        (scrollView as IView)?.InvalidateMeasure(); // if not done, everything else will fail 
    }

in XAML:

<VerticalStackLayout PropertyChanged="VerticalStackLayout_PropertyChanged" (add this to every layout that is inside the scrollview and could change its content at rumtime)

this in the end works.

So my guess is that the hitbox around the button does not get shifted down while the UI element itself does.

**Comment by drasticactions** [comment]
I apologize; I'm not sure I understand what you're saying. Could you create a reproduction project showing your expectations and what you're trying to do?

**Comment by drasticactions** [comment]
Maybe it's related to https://github.com/dotnet/maui/issues/14257?

**Comment by MichaelNovikov** [comment]
Workaround with an InvalidateMeasure doesn't work anymore!
