### ISSUE TITLE
.NET MAUI targeting Windows does not show/display

### ISSUE THREAD

**Issue by Richard-Dufour** [dotnet/maui#14309]
### Description

I started playing with .NET MAUI, one of the target platform I use is Windows. At first it loaded/ran and I was able to see it on screen. Now, all of the sudden, without any code change on my end, I can hit F5, the app builds, and "starts", but you can't see anything on screen, it is not shown. 

Running task manager will show the app.exe is running in a background process but you can't see the app, which is kind of useless for a windows app. 

Tried just about everything, clean, rebuild, delete bin/obj folders, AppX folder, etc. it just won't display anymore. 

### Steps to Reproduce

1. Create a .NET MAUI app targeting Windows
2. Run it via F5 of Visual Studio a few times 
3. Stop the execution via stop button in Visual Studio
4. Run again... the window no longer shows up.

May take a few times to get it to behave this way. 

### Link to public reproduction project repository

na

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.171340.0

### Did you find any workaround?

No

### Relevant log output

```shell
na
```

**Comment by Richard-Dufour** [comment]
Why was this thread closed (https://github.com/dotnet/maui/issues/12080)? Somebody had to test it first right? 
Clearly, this is **not** fixed.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on windows platform with template MAUI project.
