### ISSUE TITLE
embed:// uri not working from c# code

### ISSUE THREAD

**Issue by jakopo87** [dotnet/maui#14319]
### Description

The [MediaElement](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement) docs says that it's possible to use the `embed://` scheme to set the `Source` property of a `MediaElement` to load a media embedded in the app, however this works only from XAML code and not from C# .

### Steps to Reproduce

1. Create a .NET MAUI app.
2. Add `CommunityToolkit.Maui.MediaElement` package.
3. Put a supported media file in the `Resource\Raw` folder.
4. Add a `MediaElement` in the XAML code.
5. Set the `Source` property from C# code (using a button).
6. Call the `Play()` method of the `MediaElement`.
7. The `MediaElement` will show the message `Error: Unsupported video type or invalid path`

### Link to public reproduction project repository

https://github.com/jakopo87/TestMediaElementEmbed

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 13, Windows 10.19045.2728

### Did you find any workaround?

Using the file `Resource\Raw\test.wav` as example, it's possible to load correctly the media with `MediaSource.FromResource("test.wav")`.

**Comment by jakopo87** [comment]
I tried to test on .NET 8, but the solution would not compile anymore with VS 2022.

**Comment by drasticactions** [comment]
This is a [CommunityToolkit Control](https://github.com/CommunityToolkit/Maui/tree/main/src/CommunityToolkit.Maui.MediaElement).  You will need to file it in their repo.
