### ISSUE TITLE
[Bug] WinUI Template : Improper project configuration: no AppxManifest is specified...

### ISSUE THREAD

**Issue by solvingj** [dotnet/maui#1431]
### Description

This is a weird bug because the `.csproj` sets the `WindowsPackageType` variable to `MSIX` correctly, but the error states that it does not.  Also of note, I do not believe this issue occurred with the previous version of the template. 

### Steps to Reproduce

1. On windows...
2. mkdir maui_appx_bug && cd maui_appx_bug
3. dotnet new maui
4. dotnet restore
5. open solution in visual studio
6. try to build/run WinUI3 project

### Expected Behavior

The brand new from-template project should open and build and run without errors by default.

### Actual Behavior

Visual studio reports an error out of the box.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Improper project configuration: no AppxManifest is specified, but WindowsPackageType is not set to MSIX.	maui_three.WinUI	C:\Users\jerry\.nuget\packages\microsoft.projectreunion.winui\0.8.0-preview\buildTransitive\Microsoft.Build.Msix.Packaging.targets	134	

```

### Basic Information

- Version with issue:  Microsoft.Maui.Templates::6.0.100-preview.6.874
- Last known good version:  Microsoft.Maui.Templates::6.0.100-preview.5.794 
- IDE: Visual Studio 2019 preview 2
- Platform Target Frameworks: 
  - Project reunion:  0.8.0-preview
- Nuget Packages:
- Affected Devices: WinUI3

### Screenshots

![image](https://user-images.githubusercontent.com/8557737/123130384-bc666f00-d41a-11eb-9768-f34ac74fc081.png)

### Workaround

I edited Microsoft.Build.Msix.Packaging.targets and just commented out the error check.

**Comment by jcapellman** [comment]
Got this as well with VS2022 Preview 4, latest MSIX extension:
![image](https://user-images.githubusercontent.com/11558993/133888641-1295f996-dda3-4a97-8587-3cd3d7681d30.png)

Fortunately, I wanted to build a regular PE32 file instead of a MSIX anyway so I changed the PackageType

**Comment by jsuarezruiz** [comment]
Could you try again with the latest VS 2022 Preview and .NET MAUI Preview 10?. Let me know if find any issue with it and we can reopen the issue.
