### ISSUE TITLE
Make WebView available in ScrollView.

### ISSUE THREAD

**Issue by SF-Simon** [dotnet/maui#14349]
### Description

We have some complex layout styles that use HTML pages to display to users.

In other frameworks, we used to use a browser and have the browser constantly adjust its height based on its own content, that is, keep the size of the WebView the same as the size of the content document. Then we'll put this WebView in the scrolling view.

I tried to implement it in the same way in MAUI, but I didn't get the expected effect.

```
    this.webView.Navigated += OnWebViewNavigated;

    private async void OnWebViewNavigated(object? sender, WebNavigatedEventArgs e)
    {
        string clientHeight = await this.webView.EvaluateJavaScriptAsync($"document.body.scrollHeight");
        string clientWidth = await this.webView.EvaluateJavaScriptAsync($"document.body.scrollWidth");
        this.WidthRequest = clientWidth.ToInt32();
        this.HeightRequest = clientHeight.ToInt32();
    }
```

Although both the height and width have changed, it is not possible to scroll normally because two scroll bars appear. I tried to remove the scroll bar from the web, but it still doesn't work properly.

### Public API Changes

I don't have a particular idea, but I just want to have a setting that can accomplish this task, so that the size of the WebView is always consistent with the content view. Turn WebView into an HTML renderer.

### Intended Use-Case

The advantage of doing this is that it can make the interface more flexible, and you can use the Web to complete some complex tasks at any time. I think efficiency should also be higher.

**Comment by eli191** [comment]
For me works in Android, not in iOS.

**Comment by cyliu12** [comment]
The Following code worked in MAUI

    private void OnWebViewNavigated(object sender, WebNavigatedEventArgs e)
    {
        WebView webView = sender as WebView;
        webView.WidthRequest = webView.DesiredSize.Width > 0 ? webView.DesiredSize.Width: -1;
        webView.HeightRequest = webView.DesiredSize.Height > 0 ? webView.DesiredSize.Height: -1;
    }
