### ISSUE TITLE
Visual Studio Mac 17.5.3 (build 15) doesn't list Maui Templates

### ISSUE THREAD

**Issue by robomac** [dotnet/maui#14352]
### Description

Followed the template installation instructions.
<img width="894" alt="image" src="https://user-images.githubusercontent.com/15898894/229323462-c89cfbf8-f55f-41dc-9910-af89e7c28c35.png">
Restarted Visual Studio Mac (17.5.3 (build 15)); they still aren't there.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/15898894/229323473-c0870d13-ddde-4021-9093-bf88e4916d6a.png">
Even uninstalled and reinstalled.  The _installer_ said Maui was installed; they just don't show in the U.I.

Possibly related: https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/cli?view=net-maui-7.0 is also wrong currently,  as files are missing.
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/15898894/229323683-67b473c0-f5a9-4c2a-b343-a3f560f752bf.png">

This happens for most Maui components.

### Steps to Reproduce

They're above... 
Install Maui Templates via dotnet new install Microsoft.Maui.Templates
You'll get the same results whether it's already there or not.
Start up Visual Studio Mac 17.5.3 (build 15).
No Maui workloads.

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

https://github.com/dotnet/maui

### Did you find any workaround?

None.

> VS bug [#1784395](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1784395)

**Comment by MateuszLas421** [comment]
I had the same thing, A full reinstallation helps. 
1. uninstall Visual Studio for mac
2. uninstall maui from mac console
3. Install Visual studio for mac

**Comment by jfversluis** [comment]
While reporting this through the instructions above 👆 definitely is the right thing to do. The thing I notice about your screenshots is that one says .NET 6 and the other says .NET 7. It might be that the templates are installed for one and not the other.

From your command-line check the output for `dotnet --info`. Do you have some global.json file somewhere in there? You could also try the command line for updating the templates and try what Mateusz mentioned. 

Anyway! Please report above which is the right place for this 😄

**Comment by jfversluis** [comment]
No response here, going to assume this has been resolved.
