### ISSUE TITLE
Binding fails when stacklayout is introduced

### ISSUE THREAD

**Issue by ragiovan** [dotnet/maui#14350]
### Description

When binding Source to x:name in xaml, binding works when content is placed in `ContentPage`. Once content is placed inside a `StackLayout` binding no longer occurs:

Works:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:CellularSignal1"
             xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.Maui;assembly=LiveChartsCore.SkiaSharpView.Maui"
             x:DataType="local:CellularFrequencies"
             x:Class="CellularSignal1.CellularFrequencies"
             x:Name="this">

    <lvc:CartesianChart
            Series="{Binding Series, Source={x:Reference this}}">
    </lvc:CartesianChart>
</ContentPage>

```
Doesn't work:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:CellularSignal1"
             xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.Maui;assembly=LiveChartsCore.SkiaSharpView.Maui"
             x:DataType="local:CellularFrequencies"
             x:Class="CellularSignal1.CellularFrequencies"
             x:Name="this">

    <StackLayout>
        <lvc:CartesianChart
                Series="{Binding Series, Source={x:Reference this}}">
        </lvc:CartesianChart>
    </StackLayout>

</ContentPage>

```

### Steps to Reproduce

Remove Stacklayout. Graph appears in page. Add Stacklayout, binding no longer occurs.

Things tried:

Add Binding context to `StackLayout` such as: 

    <StackLayout BindingContext="{x:Reference this}">
        <lvc:CartesianChart
                Series="{Binding Series">
        </lvc:CartesianChart>
    </StackLayout>

But no dice...

### Link to public reproduction project repository

https://github.com/ragiovan/maui-binding-issue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No.

**Comment by cat0363** [comment]
Hi, @ragiovan 
How about changing it as below?
Try adding VerticalOptions, HorizontalOptions and specifying FillAndExpand, or specify the height with HeightRequest.

    <StackLayout BindingContext="{x:Reference this}">
        <lvc:CartesianChart Series="{Binding Series}" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" />
    </StackLayout>

The Binding itself is working, but the height of the Chart is 0.

**Comment by drasticactions** [comment]
StackLayout doesn't have an intrinsic height in MAUI, as documented here: https://learn.microsoft.com/en-us/dotnet/maui/migration/layouts?view=net-maui-7.0

If your control does not offer a height and you use a StackLayout, it will be zero, which is happening here. Try using a Grid or setting a specific height and it should work.

**Comment by ragiovan** [comment]
Thanks guys, it just wasn't appearing due to height being 0 as mentioned.
