### ISSUE TITLE
[MacCatalyst] [iOS] Label goes out of the bounds of its parent when it has a bigger desired width than the parent constraints

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#14368]
### Description

I have a Label placed inside ContentView with LineBreakMode set to TailTruncation. The ContentView has WidthRequest set to 150. As the Label has a desired width bigger than the parent's constraints the expected behavior is to have a wrapped Label with TailTruncation. However, the Label goes out of the bound of the ContentView.

Check the following images to see how the same Label look in Android (working) and Catalyst:
![Screenshot_1680539245](https://user-images.githubusercontent.com/9336157/229570781-8da55210-10e3-4fa5-a2e1-b8c072506d91.png)
<img width="624" alt="Screenshot 2023-04-03 at 7 31 04 PM" src="https://user-images.githubusercontent.com/9336157/229571487-77c71fae-26c8-47f9-a351-60703b6bffcc.png">

### Steps to Reproduce

1. Create a new maui application.
2. Add the following label inside the MainPage:
`<ContentView WidthRequest="150"
                HeightRequest="150"
                BackgroundColor="Lime">
    <ContentView.Content>
            <Label HorizontalOptions="Start"
                LineBreakMode="TailTruncation"
                Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit." />
    </ContentView.Content>
</ContentView>`

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/Nasko/label-issue/Maui/LabelLayout

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

macOS Ventura, iOS 16

**Comment by PureWeen** [comment]
Related https://github.com/dotnet/maui/issues/9084

**Comment by LanceMcCarthy** [comment]
Quick update for the link to the repo project => https://github.com/telerik/ms-samples/tree/main/Maui/LabelLayout
