### ISSUE TITLE
[WinUI] ScrollView does not layout contents if they don't change in size. 

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#14377]
### Description

![71f334a0-f845-40b5-bb67-7603e9e0a1fc](https://user-images.githubusercontent.com/898335/229717770-917f53ba-c805-4686-be84-d5aee5a48f56.png)
![c8d6eda3-ca19-482b-a186-d44524b9200c](https://user-images.githubusercontent.com/898335/229717776-1067a8cc-53c8-4f6e-8457-af4a1d78eaa4.png)

When trying to change the inner contents of a ScrollView, such as a Label or Image, if the contents themselves don't change (I.E, changing the HorizontalOptions from Start to End) then the layout will remain the same until something causes the scrollview to lay itself out again (such as the window resizing, or the label text updating)

I can't reproduce this on Android, iOS, or Catalyst. 

### Steps to Reproduce

Run https://github.com/drasticactions/MauiRepros/tree/main/LabelTest and click the layout button.

### Link to public reproduction project repository

https://github.com/drasticactions/MauiRepros/tree/main/LabelTest

### Version with bug

7.0 (current), .NET 8 Preview7

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Whatever the version of WinUI that's shipped with that version of MAUI.

### Did you find any workaround?

Wrap the inner contents of ScrollView with something like StackLayout or Grid.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11 with below Project:
[LabelTest.zip](https://github.com/dotnet/maui/files/11866182/LabelTest.zip)

**Comment by spadapet** [comment]
See if this PR change helps:
* https://github.com/dotnet/maui/pull/15248

**Comment by spadapet** [comment]
That PR didn't help. Layouy.OnChildMeasureInvalidated is getting called, but the children aren't actually getting updated.
