### ISSUE TITLE
WebView Navigating and Navigated Events not fired

### ISSUE THREAD

**Issue by SvenCarstensen** [dotnet/maui#14379]
### Description

I have set the events Navigated and Navigating in the XAML.
XAML:

```xaml
<WebView
  x:Name="ContentWebView"
  VerticalOptions="Fill"
  HorizontalOptions="Fill"
  BackgroundColor="Azure"
  Navigated="ContentWebView_OnNavigated"
  Navigating="ContentWebView_OnNavigating"
  Loaded="WebView_OnLoaded"/>
```
Code-behind:
```cs
private void ContentWebView_OnNavigating(object sender, WebNavigatingEventArgs webNavigatingEventArgs)
{
    Console.WriteLine("ContentWebView_OnNavigating called");
}

private void ContentWebView_OnNavigated(object sender, WebNavigatedEventArgs webNavigatedEventArgs)
{
    Console.WriteLine("ContentWebView_OnNavigated called");
}
```
If I now set the source of the WebView with an HTML text, no event is fired.
The event Loaded, however, works.

### Steps to Reproduce

See above

### Link to public reproduction project repository

N/A

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
I see you mention .NET 6 as the version. Have you tried .NET 7? Could you please provide a reproduction sample?

**Comment by SvenCarstensen** [comment]
Hi Gerald,

> I see you mention .NET 6 as the version. Have you tried .NET 7? Could you please provide a reproduction sample?

I just tried it with .NET 7. Unfortunately without success.
I'll create a sample project over Easter and get back here.

See you then

Sven Carstensen

PS: I like to watch your videos on YouTube :-)

**Comment by jinxinjuan** [comment]
@SvenCarstensen I see you mention "I'll create a sample project over Easter and get back here.". Could you please provide a reproduction sample? Thanks. And by the way, could you have a try with .NET 8 on latest release build?

**Comment by jfversluis** [comment]
With the current version of .NET MAUI I can't reproduce anymore. Seems to be working just fine. If you're still hitting this, please open a new issue with all the details, thanks!
