### ISSUE TITLE
Azure B2C within MAUI Mobile Apps

### ISSUE THREAD

**Issue by Strawberrychewy** [dotnet/maui#14380]
### Description

(Not tested for iOS. Only Android so far.)
I have been following a couple of YouTube videos on Azure B2C to authenticate users using Microsoft, Twitter and Google.
My current MAUI app uses Shell Navigation, so I thought with the right setup on the cloud I can get this working correctly.
Microsoft login works correctly with Shell Navigation, but when adding Twitter and Google user flows, the app seems to ignore redirecting back to the application after successfully logging in. 
This does not happen when I substituted the Shell Navigation for the login section to 'directly setting the main page of the app'
For the sake of logging out and setting the main page as a workaround, it will not redirect properly into the app again, so the major cause of this may be if the app is navigating using shell rather than shell itself. You would need to NOT use any form of Shell Navigation before attempting to log in using Azure B2C.

### Steps to Reproduce

1. Follow this tutorial or clone the github repo. (The repo should work provided that you set up the Azure B2C on the cloud successfully)
Tutorial: https://www.youtube.com/watch?v=AIO2qOKC7Vc
Github Repo: https://github.com/carlfranklin/MsalSocialAuthInMaui

2. Change the application so that it utilises Shell Navigation instead. The app should allow you to attempt to log in to the app but does not redirect to the app once the login is successful.

### Link to public reproduction project repository

https://github.com/carlfranklin/MsalSocialAuthInMaui

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

Android 11 and up?

### Did you find any workaround?

Don't use Shell Navigation.

**Comment by PureWeen** [comment]
@Strawberrychewy including a small video might also help here.

**Comment by Strawberrychewy** [comment]
I have uploaded a basic project here to use. Readme also included but it does require some wiring to get it set up with Azure.
https://github.com/Strawberrychewy/AzureB2CMAUIApp

**Comment by Strawberrychewy** [comment]
Finally got to the issue now.
When using Azure B2C and MSAL Authentication, you need to use the redirect URI that is automatically made up (the link that has "(MSAL only)" next to it) when you take a look at the authentication tab in your azure application, which isn't noted in the tutorial videos for it, as they used normal navigation instead of Shell Navigation.

![image](https://user-images.githubusercontent.com/54252095/234172822-f062f908-aecb-4ff7-871e-a068025c503b.png)

**Comment by mattleibow** [comment]
Closing this as it was an issue with the incorrect redirect url used.

Thanks for letting us know!
