### ISSUE TITLE
Visual State for button background not working

### ISSUE THREAD

**Issue by gktval** [dotnet/maui#14385]
### Description

I have two buttons on a page. When the start button is pushed, the behavior should change the background color through the VisualState to red and a Pause button should be yellow. However, both button's background colors remain green.

The VisualState for a button's background color was working about a month ago. A recent update broke this feature.

### Steps to Reproduce

1. Create a VisualState in the styles.xaml. The one I create has a key of "surveyButton"
2. Create a behavior (ElementStateBehavior.cs) that binds the VisualState
3. Command when the button is clicked that changes the State of the button.

### Link to public reproduction project repository

https://github.com/gktval/Maui-VisualStateBug

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

No

### Relevant log output

```shell
none
```

**Comment by jsuarezruiz** [comment]
Testing changing the VisualStates tapping buttons (for example) works. In this case the Behavior StateChanged event never fires.

**Comment by gktval** [comment]
Thanks, you are indeed correct that the VisualStates are working. The binding of the behavior to the "SurveyState" property is not working:
```
<Button.Behaviors>
         <behave:ElementStateBehavior Target="{Binding Source={x:Reference startButton}}"
                       State="{Binding SurveyState"/>
</Button.Behaviors>
```

Changing to this works:
```
<Button.Behaviors>
         <behave:ElementStateBehavior Target="{Binding Source={x:Reference startButton}}"
                       State="{Binding SurveyState, Source={x:Reference mainPage}}"/>
</Button.Behaviors>
```

I assume this is the way it is supposed to work (all properties in behaviors must have their source directly set since the Binding Context is not set)? https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/behaviors?view=net-maui-7.0#create-a-net-maui-behavior
If so I will close this ticket. Thanks

**Comment by gktval** [comment]
Although upon further investigation, I am not sure if my above solutions works with a view model. For example, if in my .cs I have a property called 'SurveyModel': ```public  MyModel SurveyModel { get; }``` that gets set on initialization.  Then changing the behavior of the button to this:
``` 
<Button.Behaviors>
        <behave:ElementStateBehavior BindingContext="{x:Reference mainPage}"
                      Target="{Binding Source={x:Reference startButton}}"
                      State="{Binding SurveyModel.SurveyState}"/>
</Button.Behaviors>
```
The resulting code also does not bind the State property in the behavior to the SurveyState in the view model.
Thoughts?
If this is a bug I can redo the repository code to reflect my concerns.

**Comment by gktval** [comment]
Closing this since the bug is more with binding properties in behaviors than with the state value. That and I haven't heard any response to my questions and I have already found workarounds.
