### ISSUE TITLE
.net maui ios ipa cant be created

### ISSUE THREAD

**Issue by planyazilim** [dotnet/maui#14393]
### Description

I create default .Net 7 Maui App Project with Windows Visual Studio 2022 17.6.0 Preview 2.0

I created certificates, Identifiers,Profiles times and time during a whole week.

**Run Tis command On Windows Machine Terminal**

dotnet publish -f:net7.0-ios -c:Release /p:ArchiveOnBuild=true /p:RuntimeIdentifier=ios-arm64 /p:CodesignKey="Apple Distribution: Are Arat Cakavo (US2T586KMM)" /p:CodesignProvision="myprofile" /p:ServerAddress=192.168.1.121 /p:ServerUser=Rac /p:ServerPassword=2222 /p:TcpPort=58181 /p:_DotNetRootRemoteDirectory=/Users/Mac/Library/Caches/Xamarin/XMA/SDKs/dotnet/

**It compiles I wait almost 5 min , then I get error**

 /usr/bin/mdimport bin/Release/net7.0-ios/ios-arm64/
  Tool /usr/bin/codesign execution finished (exit code = 1).

  Warning: unable to build chain to self-signed root for signer "Apple Distribution: Are Arat Cakavo (US2T586KMM)"
  /Users/mac/Library/Caches/Xamarin/mtbs/builds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/Mau
  iApp1.app: errSecInternalComponent

C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : /usr/bin/codesign exited with code 1: [C:\
Users\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : Warning: unable to build chain to self-sig
ned root for signer "Apple Distribution: Are Arat Cakavo (US2T586KMM)" [C:\Users\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7
.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : /Users/mac/Library/Caches/Xamarin/mtbs/bui
lds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/MauiApp1.app: errSecInternalComponent [C:\Users
\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : Failed to codesign '/Users/mac/Library/Cac
hes/Xamarin/mtbs/builds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/MauiApp1.app': Warning: una
ble to build chain to self-signed root for signer "Apple Distribution: Are Arat Cakavo (US2T586KMM)" [C:\Users\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp
1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : /Users/mac/Library/Caches/Xamarin/mtbs/bui
lds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/MauiApp1.app: errSecInternalComponent [C:\Users
\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error :  [C:\Users\ttoxi\source\repos\MauiApp1\Mau
iApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error :          [C:\Users\ttoxi\source\repos\Maui
App1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]

### Steps to Reproduce

1. Create a .Net 7 Maui app
2. Create Certificates, Identifiers and Profiles on Mac
3. Change info.plist bundle identifier as it is in our Profile
4. Choose Release Mode and Remote Device on Visua Studio 2022
5. On Windows Visual Studio Terminal Run
dotnet publish -f:net7.0-ios -c:Release /p:ArchiveOnBuild=true /p:RuntimeIdentifier=ios-arm64 /p:CodesignKey="Apple Distribution: Are Arat Cakavo (US2T586KMM)" /p:CodesignProvision="ikinciprofile" /p:ServerAddress=192.168.1.121 /p:ServerUser=Rac /p:ServerPassword=2222 /p:TcpPort=58181 /p:_DotNetRootRemoteDirectory=/Users/Mac/Library/Caches/Xamarin/XMA/SDKs/dotnet/
6. And error is
 /usr/bin/mdimport bin/Release/net7.0-ios/ios-arm64/
  Tool /usr/bin/codesign execution finished (exit code = 1).

  Warning: unable to build chain to self-signed root for signer "Apple Distribution: Are Arat Cakavo (US2T586KMM)"
  /Users/mac/Library/Caches/Xamarin/mtbs/builds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/Mau
  iApp1.app: errSecInternalComponent

C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : /usr/bin/codesign exited with code 1: [C:\
Users\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : Warning: unable to build chain to self-sig
ned root for signer "Apple Distribution: Are Arat Cakavo (US2T586KMM)" [C:\Users\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7
.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : /Users/mac/Library/Caches/Xamarin/mtbs/bui
lds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/MauiApp1.app: errSecInternalComponent [C:\Users
\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : Failed to codesign '/Users/mac/Library/Cac
hes/Xamarin/mtbs/builds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/MauiApp1.app': Warning: una
ble to build chain to self-signed root for signer "Apple Distribution: Are Arat Cakavo (US2T586KMM)" [C:\Users\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp
1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : /Users/mac/Library/Caches/Xamarin/mtbs/bui
lds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/MauiApp1.app: errSecInternalComponent [C:\Users
\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error :  [C:\Users\ttoxi\source\repos\MauiApp1\Mau
iApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error :          [C:\Users\ttoxi\source\repos\Maui
App1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]

### Link to public reproduction project repository

Simliest Maui App

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

### Relevant log output

```shell
/usr/bin/mdimport bin/Release/net7.0-ios/ios-arm64/
  Tool /usr/bin/codesign execution finished (exit code = 1).

  Warning: unable to build chain to self-signed root for signer "Apple Distribution: Are Arat Cakavo (US2T586KMM)"
  /Users/mac/Library/Caches/Xamarin/mtbs/builds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/Mau
  iApp1.app: errSecInternalComponent

C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : /usr/bin/codesign exited with code 1: [C:\
Users\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : Warning: unable to build chain to self-sig
ned root for signer "Apple Distribution: Are Arat Cakavo (US2T586KMM)" [C:\Users\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7
.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : /Users/mac/Library/Caches/Xamarin/mtbs/bui
lds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/MauiApp1.app: errSecInternalComponent [C:\Users
\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : Failed to codesign '/Users/mac/Library/Cac
hes/Xamarin/mtbs/builds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/MauiApp1.app': Warning: una
ble to build chain to self-signed root for signer "Apple Distribution: Are Arat Cakavo (US2T586KMM)" [C:\Users\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp
1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error : /Users/mac/Library/Caches/Xamarin/mtbs/bui
lds/MauiApp1/f60baf3136827dbafd4e9d4f728f6d252393424ab94c7b1868ecd58c3d2bdd89/bin/Release/net7.0-ios/ios-arm64/MauiApp1.app: errSecInternalComponent [C:\Users
\ttoxi\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error :  [C:\Users\ttoxi\source\repos\MauiApp1\Mau
iApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1040\tools\msbuild\iOS\Xamarin.Shared.targets(2128,3): error :          [C:\Users\ttoxi\source\repos\Maui
App1\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
```

**Comment by jfversluis** [comment]
I think this might help here: https://blog.verslu.is/app-publishing/unable-to-build-chain-for-self-signed-root/
