### ISSUE TITLE
MAUI BlazorWebView does not support transparent page background in iOS

### ISSUE THREAD

**Issue by drmaven** [dotnet/maui#14407]
### Description

I am using a BlazorWebview component inside a xaml page and have set the following:
```

MainPage.xaml
<BlazorWebView HostPage="wwwroot/index.html" Grid.Row="2"
                           BackgroundColor="Transparent"
                           >
                <BlazorWebView.RootComponents>
                    <RootComponent Selector="#app" ComponentType="{x:Type blazor:Main}" />
                </BlazorWebView.RootComponents>
</BlazorWebView>

wwwroot/index.html
<html lang="en" style="background-color: transparent;">

```
The result is that the webview control has a white background on the iOS simulator. If I set the background-color in index.html to any other color, then that color displays correctly. I have also tried setting the background color via css directly in the razor component, but again transparency isn't working.

### Steps to Reproduce

//MainPage.xaml

```
<BlazorWebView HostPage="wwwroot/index.html" Grid.Row="2"
                           BackgroundColor="Transparent"
                           >
                <BlazorWebView.RootComponents>
                    <RootComponent Selector="#app" ComponentType="{x:Type blazor:Main}" />
                </BlazorWebView.RootComponents>
</BlazorWebView>
```

// wwwroot/index.html

```
<html lang="en" style="background-color: transparent;">
```

### Link to public reproduction project repository

N/A

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by drmaven** [comment]
This is the workaround I implemented, on top of setting the index.html styles as shown above

```
using System;
using Microsoft.AspNetCore.Components.WebView.Maui;
#if IOS || MACCATALYST
using WebKit;
using UIKit;
using CoreGraphics;
using Microsoft.Maui.Platform;
using Microsoft.Maui.Handlers;
using RectangleF = CoreGraphics.CGRect;
#endif


namespace MyApp.Presentation.Controls.Extended
{
	public class CustomBlazorWebView : BlazorWebView
    {
		public CustomBlazorWebView()
		{
            this.BlazorWebViewInitialized += CustomWebView_BlazorWebViewInitialized;
		}

        private void CustomWebView_BlazorWebViewInitialized(object sender, Microsoft.AspNetCore.Components.WebView.BlazorWebViewInitializedEventArgs e)
        {
            #if IOS
			var webView = (WKWebView)e.WebView;
            webView.Opaque=false;
            webView.BackgroundColor=UIColor.Clear;
            #endif
        }
    }
}
```

**Comment by mkArtakMSFT** [comment]
@Eilon do you know if the original code works on other (non iOS) platforms? Like Android?

**Comment by mkArtakMSFT** [comment]
@drmaven your workaround looks great for time being.

**Comment by Zhanglirong-Winnie** [comment]
Visual Studio Enterprise 17.8.0 Preview 2.0. Can repro on ios platform.

**Comment by mkArtakMSFT** [comment]
Closing as we think the solution provided by https://github.com/dotnet/maui/issues/14407#issuecomment-1497413616 is what we would recommend to anyone doing this.
