### ISSUE TITLE
Button properties are inconsistent when applying android themes

### ISSUE THREAD

**Issue by g4gekkouga** [dotnet/maui#14404]
### Description

Button control behaves differently with different android themes. 
Can observe a thick gray border around the control when background color set to transparent. And distorted click action.
Also, a thin line border around the control when color set to white or others

Button Controls Used:

Button 1:

Text="Click me"
TextColor="Black"
HorizontalOptions="Center"
HeightRequest="100"
WidthRequest="100"
BackgroundColor="Transparent"
BorderColor="Transparent"
CornerRadius="10"
BorderWidth="0"

Button 2:

Text="Click me"
TextColor="Black"
HorizontalOptions="Center"
HeightRequest="100"
WidthRequest="100"
BackgroundColor="White"
BorderColor="Black"
BorderWidth="1"
CornerRadius="50"

### MaterialComponents Theme Button:

<img src="https://user-images.githubusercontent.com/40440064/230038645-b79c64d5-b26c-46b9-95c0-71f00bd904b6.jpg" width="200" height="200" />

_Can observe the above-mentioned issue._

### AppCompat Theme Button:

<img src="https://user-images.githubusercontent.com/40440064/230038633-67460754-efd5-41e3-9565-4b18df410604.jpg" width="200" height="200" />

_No weird border now. But button properties like Corner radius, Border width etc properties are not applying._

### Material3 Theme Button:

<img src="https://user-images.githubusercontent.com/40440064/230038639-79af43e5-bcee-4faa-8e1d-b19bb72700a6.jpg" width="200" height="200" />

_No weird border here also. But still properties are not consistent. Observed Image Size etc. are not being applied for Image Button control._

### Steps to Reproduce

1. Clone the repo and run the app.
2. Can observe the button behavior on the home screen.
3. View MainPage.xaml to look at the button properties
4. Uncomment the button style item in Android/Resources/Values/styles.xml to change the button theme
5. Re-compile the app to apply theme changes and observe the behavior..

### Link to public reproduction project repository

https://github.com/g4gekkouga/MauiAppSample

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All API versions

### Did you find any workaround?

None.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on Android platform.
[MauiAppSample-main.zip](https://github.com/dotnet/maui/files/11721055/MauiAppSample-main.zip)
![Screenshot 2023-06-12 174928](https://github.com/dotnet/maui/assets/77434865/a94592fd-cbc9-42fd-b700-c55a32e891e7)
