### ISSUE TITLE
Unable to configure theranchi.com theme in Blazor

### ISSUE THREAD

**Issue by abhaykk0009** [dotnet/maui#1440]
Hi Team,

This is Abhay here.

I have a project running in MVC at www.theranchi.com , further i wanted to upgrade this to Blazor server side. I am facing the challenge in configuring this HTMl UI. 
I kept the CSS , Jquery and Images inside wwwroot folder. Next to it , I places CSS inside _host.cshtml <head> tag and Jquery at the bottom inside body tag and then header menu html inside nav.razor component,Footer in footer.razor component and then used these two components inside mainlayout . 
Now placed sliders and other contents inside index.razor . My slider is not working even images are not being pulled in the index.razor .

Reason- Reason for this can be that the Jquery for sliders and putting background images are in _host.cshtml and some how its not being served to index.razor.
please let me know if i can use <script> tag inside index.razor or how we can call it.

Thanks

**Comment by Eilon** [comment]
Hi, can you confirm where you are hosting Blazor? This repo is for issues related to the BlazorWebView control in .NET MAUI, WPF, and WinForms. If this issue is about using Blazor for web apps / web sites, I can migrate this issue to https://github.com/dotnet/aspnetcore.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
