### ISSUE TITLE
MAUI XAML build error when using Data Template and binding

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#14425]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-XAML-build-error-when-using-Data-Te/10318101)._

---
\[severity:I’m unable to use this version\]  
I’m getting following build error when trying to use ItemTemplate anywhere (CollectionView, ListView, etc.)

**Error XFC0045 Binding: Property “Name” not found on “MainPageViewModel”.**

How ever when I change code bellow  
from `<label>` to `<label>` I can compile the code  
and when I change it back to `<label>` during debugging, binding works correctly. So it’s just a compiler issue.

```  
public class Monkey
{
	public string Name { get; set; }
	public string Color { get; set; }	
}

public partial class MainPageViewModel : ObservableObject
{
	[ObservableProperty]
	public List monkeys;
}
  
``````  

	
		
			
				
					<label>
				
			
		
	

  
```

---
### Original Comments

#### Vlastimil Knotek on 3/22/2023, 06:28 AM: 

(private comment, text removed)
#### Feedback Bot on 3/22/2023, 07:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
This fix the issue.
`<DataTemplate x:DataType="Monkey">`

But should not be necessary, right @StephaneDelcroix?

**Comment by jfversluis** [comment]
This is necessary. If you have the `x:DataType` on the root of your page that will assume that everything with a binding is now available in the type that is in that datatype. However, for a template the scope of your binding context changes and you need to add the `x:DataType` in that template as well with the type that is used there.

I've pinged the docs team to double-check if we have errors with this in our docs and/or maybe add something for it. Thanks!
