### ISSUE TITLE
The .NET MAUI base template project doesn't compile because resizetizer is not loading in the images from the csproj

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#14422]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-NET-MAUI-base-template-project-does/10324935)._

## Description

[severity:It bothers me. A fix would be nice]
It is due to an old bug that apparetly hasn't been fixed yet, the template references a default splashscreen image for the Windows platform but that splashscreen doesn't exist in the project resources, to fix it one must go to Platforms\Windows\Package.appxmanifest and delete the reference to the splashscreen, but it is really not user/beginner friendly at all.

Please fix the template project available on Visual Studio Community 2022 so the project compiles right off the bat, thanks :)

**Comment by Deus-nsf** [comment]
Hello, I'm the guy who initially created the issue, after some troubleshooting, it seems that the issue is only present if you initially create an empty solution and then an MAUI project inside.
If instead you decide to create an MAUI project directly, even by not ticking "place solution and project in the same directory", then the issue doesn't occur.

Not the end of the world, but it can be confusing for people who likes to create empty solutions first (even though it's not as interesting as before since the directory option).

**Comment by samhouts** [comment]
I ran into this one today myself doing exactly the same thing that @Deus-nsf commented: created a MAUI app in an existing solution and ran in Windows.

It's not just the splash screen. The dotnet bot wasn't there either.

To workaround it, I commented out the MauiImages and MauiSplashScreen in the csproj, built, and then uncommented again. This triggered resizetizer to handle those images.

**Comment by mattleibow** [comment]
@Deus-nsf @samhouts 

I can't repro on a clean machine and that app manifest is an old old one, so I am not sure what is going on. In net8 pre3 we switched back to project templates: https://github.com/dotnet/maui/commit/bc831215169e789314a883ced474279179360792 However we switched to solution templates in 6.0.100-rc1: https://github.com/dotnet/maui/commit/1831c946cf9f7f370cdb3832fdc0472f340df391

This means that as of today, using the new project dialog may be pulling in some pre rc1 net6 templates??? If you can reproduce this, can you zip up the project that it creates so I can have a look and see if I can spot old things to confirm.

The OG issue seemed to be the IDE could not run apps if there was no solution: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1377951

I think I can confirm the old templates if I can see it, I will also start the backport of the project templates so net6/net7 can have project template support.

**Comment by mattleibow** [comment]
The PRs
 - net8: https://github.com/dotnet/maui/pull/14215
 - net7: https://github.com/dotnet/maui/pull/14841
 - net6: https://github.com/dotnet/maui/pull/14842

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 2.0. Not repro on windows platform.
