### ISSUE TITLE
Getting error on code that is not generated in MAUI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#14430]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Getting-error-on-code-that-is-not-genera/10308008)._

---
[severity:It bothers me. A fix would be nice]
I have a custom renderer in MAUI which uses platform specific code bounded by #if and #endif.
Code inside a #if where the symbol is *not* defined is producing an error in the Error List.

The code in question is:

```
            Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping( nameof( BorderlessEntry ), ( handler, view ) =>
            {
                if ( view is BorderlessEntry )
                {
#if __ANDROID__
                handler.PlatformView.SetBackgroundColor(Colors.Transparent.ToPlatform());
#elif __IOS__
                    handler.PlatformView.BorderStyle = UIKit.UITextBorderStyle.None;
#elif WINDOWS
                    Microsoft.UI.Xaml.Thickness thick = new Microsoft.UI.Xaml.Thickness();

                    thick.Left = 0;
                    thick.Top = 0;
                    thick.Right = 0;
                    thick.Bottom = 0;

                    handler.PlatformView.BorderThickness = thick;
```
The error is:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'Color' does not contain a definition for 'ToPlatform' and no accessible extension method 'ToPlatform' accepting a first argument of type 'Color' could be found (are you missing a using directive or an assembly reference?)	ARKitect (net7.0-android)	C:\Git\PortableAltair\PortableAltair\ARKitect\App.xaml.cs	22	Active
```

Even though this code is shown in a dark colour indicating the code is not being compiled.
Note that my code is being built to run on Windows and still runs despite the error message.

---
#### Feedback Bot on 3/13/2023, 07:36 PM: 

(private comment, text removed)
#### Dean Ellis [MSFT] on 3/22/2023, 05:47 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by danielancines** [comment]
The ColorExtensions is only available on Windows platform, in my tests, if you compile for Android you'll get an error because this method is not available on Android. If you compile with Windows target, no error was show.

**Comment by ojukwu24** [comment]
I added this using to the App.xaml.cs class
`using Microsoft.Maui.Platform;`

This resolved it for me.

**Comment by jsuarezruiz** [comment]
> 

Have you tried to updated yout App.xaml.cs with the missing namespace?
