### ISSUE TITLE
Disable web security in BlazorWebView

### ISSUE THREAD

**Issue by pmpbpl** [dotnet/maui#14433]
### Description

I have wpf blazor app and on one page I would like to display in iframe another localhost app and modify its html by js.
I need update cors policy or disable web security.

### Steps to Reproduce

I have tried:
`Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--disable-web-security");`
but `$('iframe').contentDocument` is `null` (blocked by different origin)

### Link to public reproduction project repository

---

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by Eilon** [comment]
Hi, it's possible that the setting isn't being applied at the right time. The BlazorWebView has a `BlazorWebViewInitializing` event that in Windows exposes a `public CoreWebView2EnvironmentOptions EnvironmentOptions { get; set; }` property that you can use to set the option directly like this:

```c#
myBlazorWebView.BlazorWebViewInitializing += MyBlazorWebViewInitializingHandler;

...

public void MyBlazorWebViewInitializingHandler(object sender, BlazorWebViewInitializingEventArgs args)
{
#if WINDOWS
    args.EnvironmentOptions.AdditionalBrowserArguments = ".... options here ...";
#endif
}
```

If that doesn't work, it could be that other settings are required either in the BlazorWebView settings, or in the HTML/JS code that's being used. Check out the discussion on [this StackOverflow post](https://stackoverflow.com/questions/67882953/disabling-of-web-security-when-using-webview2-in-c-sharp-coding-environment/67892890#67892890) to see if any of those options help out.

If that still does not work, please post a complete repro app that demonstrates the problem so we can investigate further.
