### ISSUE TITLE
Android and iOS PlatformImage export/save all ImageFormats other than Jpeg as Png

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#14449]
### Description

https://github.com/dotnet/maui/blob/main/src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs
https://github.com/dotnet/maui/blob/main/src/Graphics/src/Graphics/Platforms/iOS/PlatformImage.cs

Regardless of what ImageFormat Gif, Tiff, Bmp, the images will be saved as Png without any warning or public API documentation.

Example: methods `SaveAsync` (and `Save`) from Android `PlatformImage`:
```
switch (format)
{
    case ImageFormat.Jpeg:
        await _bitmap.CompressAsync(Bitmap.CompressFormat.Jpeg, (int)(quality * 100), stream);
        break;
    default:
        await _bitmap.CompressAsync(Bitmap.CompressFormat.Png, 100, stream);
        break;
}
```

### Steps to Reproduce

none

### Link to public reproduction project repository

none

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

all?

**Comment by xtuzy** [comment]
The save action is correct, because android and ios not support others format, see https://learn.microsoft.com/en-us/dotnet/api/uikit.uiimage.asjpeg?view=xamarin-ios-sdk-12, https://developer.android.com/reference/android/graphics/Bitmap.CompressFormat.

I create a issue in doc https://github.com/dotnet/docs-maui/issues/1404

**Comment by jsuarezruiz** [comment]
> The save action is correct, because android and ios not support others format, see https://learn.microsoft.com/en-us/dotnet/api/uikit.uiimage.asjpeg?view=xamarin-ios-sdk-12, https://developer.android.com/reference/android/graphics/Bitmap.CompressFormat.
> 
> I create a issue in doc [dotnet/docs-maui#1404](https://github.com/dotnet/docs-maui/issues/1404)

cc @davidbritch

**Comment by davidbritch** [comment]
https://github.com/dotnet/docs-maui/issues/1404
