### ISSUE TITLE
[Bug] Any use of RealParent to locate the Application will currently fail

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1445]
### Description
https://github.com/dotnet/maui/blob/18e0f4ebbcca7c904ccdb67e6439cb72382e2a40/src/Controls/src/Core/Binding.cs#L182

RealParent now returns Window instead of Application

**Comment by shimingsg** [comment]
Not reproducible with windows.

**Comment by shimingsg** [comment]
Verified repro with windows  and the above file.
