### ISSUE TITLE
Maui TableView binding with custom view doesn't accept input

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#14464]
### Description

0

I migrated DotMorten AutoSuggestBox control to a Android Maui test app. It runs fine except when I use it in a TableView ViewCell. The AutoSuggestBox appears, you can move the cusor to the box but it wont accept keyboard input. So I dont see the dropdown list as a result. This works with Xamarin Forms. I am including the app source at https://github.com/davefxy/AutoSuggestionBoxTest.
The test app uses the AutoSuggestBox in 3 instances in a StackLayout. The 3rd instance is in a TableView. The 1st 2 work as expected. The AutoSuggestBox in the TableView accepts focus (cursor) but doesn't permit data entry.

### Steps to Reproduce

Use the supplied test app.
Build Android version.
Run the app and attempt to enter data in each of the 3 fields
The 3rd instance wont allow you to input data.

### Link to public reproduction project repository

https://github.com/davefxy/AutoSuggestionBoxTest.

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 33.0.26/7.0.100

### Did you find any workaround?

No

**Comment by davefxy** [comment]
I believe that I was attempting to use the custom control AutoSuggestBox where perhaps it wasnt supported. So I replaced the TableView with a Grid layout. Doing this was extremely easy with the help of CoPilot. And no changes were required to the code behind. Microsoft made it so easy to perform this migration from TableView to a Grid layout.

**Comment by Zhanglirong-Winnie** [comment]
Code issue, the customer has resolved this issue.
