### ISSUE TITLE
[Windows] IsVisible on shell menu items through ViewModel randomly duplicates shell menu items

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#14467]
### Description

Windows (not OK):
![image](https://user-images.githubusercontent.com/64279914/230717539-f13327d3-9b9b-4340-9237-dee450038e1e.png)

Android (OK):

![image](https://user-images.githubusercontent.com/64279914/230717616-ccc41304-0878-4fd9-b9c1-fbcae10eb6f2.png)

### Steps to Reproduce

1. Run application
2. Enter `All` into the login screen input text field _(this "logs in" user with rights to all menu buttons)_
3. Click Login button
4. Click shell menu
5. See menu items

### Link to public reproduction project repository

https://github.com/janseris/MAUIDynamicMenuItemsBugReports

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. This issue repro on Windows 11, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[DynamicMenu.zip](https://github.com/dotnet/maui/files/11867510/DynamicMenu.zip)
