### ISSUE TITLE
Cannot navigate to page when Shell menu item has IsVisible=False

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#14470]
### Description

Cannot navigate to page when Shell menu item has `IsVisible=False`
When trying to navigate to such page, the following `Exception` is thrown:

`System.Exception: 'Global routes currently cannot be the only page on the stack, so absolute routing to global routes is not supported. For now, just navigate to: ArcheologiePage'`

### Steps to Reproduce

1. Change Line 26 in AppShell.xaml to `IsVisible="False"`
2. Run application
3. Enter `All` into the login screen input text field _(this "logs in" user with rights to all menu buttons)_
4. Click Login button
5. Experience crash

### Link to public reproduction project repository

https://github.com/janseris/MAUIDynamicMenuItemsBugReports

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by PureWeen** [comment]
@janseris if you want to hide something from the Flyout use https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout?view=net-maui-7.0#flyoutitem-visibility. That will hide it from the Flyout Menu but make it still navigable.

**Comment by janseris** [comment]
> @janseris if you want to hide something from the Flyout use https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout?view=net-maui-7.0#flyoutitem-visibility. That will hide it from the Flyout Menu but make it still navigable.

Thank you, it's possible to use but that property IsFlyoutItemVisible does not comply with MVVM. It is not bindable.

**Comment by janseris** [comment]
> @janseris it is a bindable property:
> 
> https://github.com/dotnet/maui/blob/22bd97f28cf1e11b5aec3db919906f7de6136dab/src/Controls/src/Core/Shell/Shell.cs#L72
> 
> so that should work just fine. What makes you think that it doesn't?

![image](https://user-images.githubusercontent.com/64279914/233338167-40122fbc-bc38-4bcc-bb8f-89dda54d3e04.png)

**Comment by janseris** [comment]
> @janseris if you want to hide something from the Flyout use https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout?view=net-maui-7.0#flyoutitem-visibility. That will hide it from the Flyout Menu but make it still navigable.

How does a shell flyout menu item influence that the page can or cannot be navigated to using await Shell.Current.NavigateTo()? Should it influence that? This is set up in routing setup, isn't it?

**Comment by janseris** [comment]
Btw. 
The naming is confusing, what is supposed to be the difference between `IsVisible` vs `FloyoutItemIsVisible`?

There is no documentation for these two properties.
![image](https://user-images.githubusercontent.com/64279914/233341387-53e6e155-f6dc-4f58-b451-314ed57eca2e.png)
