### ISSUE TITLE
[MacCatalyst]RadioButton does not display button

### ISSUE THREAD

**Issue by robomac** [dotnet/maui#14485]
### Description

Defining a RadioButton inside a Grid or Stack (haven't tried others) on MacCatalyst, the Content (text) shows but the button does not.

### Steps to Reproduce

1. Create new Maui app using  Visual Studio Mac  and the template.
2. Add a single line to the demo code...  Line 11 of MainPage.xaml:
`           <RadioButton Content="Test Button"/>`
3. Observe disastrous result:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/15898894/230792763-875e1911-61d2-4184-bdf8-a456fc876014.png">

### Link to public reproduction project repository

https://github.com/robomac/MauiMacRadioButtonRepro

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Ventura 13.3.1

### Did you find any workaround?

I have not found a work-around.

**Comment by XamlTest** [comment]
Verified this issue on MacCatalyst 13.6.1, repro on 7.0.101, but not repro on latest 8.0.3 version. 

<img width="1020" alt="Screenshot 2023-11-17 at 10 59 56 AM" src="https://github.com/dotnet/maui/assets/97647558/6ecdae50-8f7f-4c40-93e3-2211f71d2edf">
