### ISSUE TITLE
[WinUI] Replacing CollectionView ItemSource does not clear underlying children from VisualTree

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#14507]
### Description

<img width="812" alt="スクリーンショット 2023-04-11 17 21 50" src="https://user-images.githubusercontent.com/898335/231100603-b7484700-0c14-4dbe-905e-7345df3776f3.png">

If you replace the itemsource of a given collectionview, the collectionview updates to show the new contents, but the original ItemSource items are still present in the CollectionViews visual tree and are not removed nor disposed of.

As far as I can tell, this only happens on WinUI. Android does remove and replace its items correctly. iOS/Catalyst does clear some but not all of the items, see https://github.com/dotnet/maui/issues/14506.

### Steps to Reproduce

1. Run my reproduction project https://github.com/drasticactions/MauiRepros/tree/main/MauiCollectionView

### Link to public reproduction project repository

https://github.com/drasticactions/MauiRepros/tree/main/MauiCollectionView

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All versions.

**Comment by rachelkang** [comment]
@PureWeen any chance this is related to your LVT-related PR?

**Comment by drasticactions** [comment]
Trying to reproduce this in Main, I can't. I can still repro https://github.com/dotnet/maui/issues/14506, though, and I'm not sure what changed.

I am closing this for now unless I can reproduce this later.
