### ISSUE TITLE
.net MAUI FlexLAyout do not display correctly in .NET 7 framework with Android

### ISSUE THREAD

**Issue by samhouts** [dotnet/maui#14500]
---
**Issue moved from xamarin/Xamarin.Forms#15725**
- Please respond to @vsfeedback.

---

_From @vsfeedback on Wednesday, April 5, 2023 11:44:52 PM_

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/net-MAUI-FlexLAyout-do-not-display-corr/10323882)._

---
[severity:I'm unable to use this version]
I have a project in .NET Maui with the .NET 6 Framework has a ContentPage with a FlexLayout. That ContentPage works perfectly with this configuratin. The problem is when I wanted to change the project to target .NET 7 framework. The following issues have occurred:
1: I have not been able to recompile the project even after a Clean. I decided to delete the obj and bin folders, but they were locked by Visual Studio, even after I closed it.  I had to sign out from windows and relog to be able to delete the folders. I've already had that problem in other projects. From there I was able to rebuild the solution.
2: Once the solution was rebuilt, although it still worked well with Windows, with Android , the Flexlayout only had one column that occupied the entire width of the screen.
I attach some screenshots and a small project with which the problem can be reproduced. 
![FlexLayout with .NET 7.png](https://aka.ms/dc/image?name=Bc02b787d44d049b7910dfdaeeb6dfefc638155289288045811_FlexLayout_with_.NET_7.png&tid=c02b787d44d049b7910dfdaeeb6dfefc638155289288045811)
![FlexLayout with .NET 6.png](https://aka.ms/dc/image?name=B16ecc5232d864a64bec875987e2a601c638155289504889678_FlexLayout_with_.NET_6.png&tid=16ecc5232d864a64bec875987e2a601c638155289504889678)
[FlexLayout.zip](https://aka.ms/dc/file?name=Bc8d94d11655f487ab3b6bd3b17defca3638155290006944005_FlexLayout.zip&tid=c8d94d11655f487ab3b6bd3b17defca3638155290006944005)

---
#### Feedback Bot on 3/27/2023, 06:53 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Redth** [comment]
I could not reproduce the issue on .NET 7.0.81:

![image](https://user-images.githubusercontent.com/271950/232630236-20a1da68-7093-4210-b475-f8f5fbdd57da.png)
