### ISSUE TITLE
Cannot debug iOS 16.4

### ISSUE THREAD

**Issue by PrestigiousF** [dotnet/maui#14503]
### Description

Hi, I'm honestly not sure if this is a MAUI issue or if I lack in an update somewhere...

I go to Project Settings to edit the target version to 16.4, but the max Is 16.2 - The emulator uses 16.4 as well since I have 14.3.

Xcode Version: 14.3
Dotnet Version: 7
Visual Studio 2022

### Steps to Reproduce

See above.

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by drasticactions** [comment]
https://github.com/xamarin/xamarin-macios/issues/17561

Xcode 14.3 support is not available yet. Follow the above issue for more details.
