### ISSUE TITLE
Could not resolve type with token 010001db from typeref  (.NET MAUI)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#14515]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Could-not-resolve-type-with-token-010001/10334837)._

---
Hello, 

I created a .NET MAUI app, which is running in .net 6.0 framework. When I build the output solution using an Android Emulator, the app will deploy but at some point the MauiProgram.cs file appears with the following error message: -

```
System.TypeLoadException
  Message=Could not resolve type with token 010001db from typeref (expected class 'Microsoft.Maui.Graphics.Platform.GraphicsExtensions' in assembly 'Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')

```
Can you kindly provide assistance in resolving this issue. 

Thanks

---
#### Feedback Bot on 4/10/2023, 07:36 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment]
@jonathanpeppers / @mattleibow - any idea where this should go? Issue related to MAUI, Xamarin Android, or Graphics?

**Comment by wirejp** [comment]
[Stack Trace of the Exception](https://imgur.com/040GqNS)

**Comment by jonathanpeppers** [comment]
Can you share a sample project that shows the problem?

**Comment by wirejp** [comment]
I cannot create a sample project to share. I did upgrade to .net 7 and the error is no longer occurring. Thank you for your help.

**Comment by jonathanpeppers** [comment]
Let us know if you hit this in .NET 7, thanks!

**Comment by wirejp** [comment]
I did not hit the same error in .NET 7. Instead, I receive an error message in the AppShell.xaml.cs file at the InitializeComponent(); line: -

`
public partial class AppShell : Shell
{
   
    public AppShell()
	{
		InitializeComponent();
        Routing.RegisterRoute(nameof(AddStackPage), typeof(AddStackPage));
       Routing.RegisterRoute(nameof(AddCellPage), typeof(AddCellPage));

     Routing.RegisterRoute(nameof(RegistrationModal), typeof(RegistrationModal));
    }
}
`

The error message is: -
`System.Reflection.TargetInvocationException
1.	Message=Exception has been thrown by the target of an invocation.
`
Note that in upgrading to the .NET 7, I received the following warning message in the AppViewModel.cs file (login file):-

`Warning CS0618 'MessagingCenter' is obsolete: 'We recommend migrating to `CommunityToolkit.MVVM.WeakReferenceMessenger`: https://www.nuget.org/packages/CommunityToolkit.Mvvm`

**Comment by wirejp** [comment]
Here is the code in the output window: -

`> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.Monitormauiapp/crc6404617909d487a25b.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.Monitormauiapp/crc6404617909d487a25b.MainActivity }
[trackersmauiapp] Late-enabling -Xcheck:jni
[trackersmauiapp] Unexpected CPU variant for x86: x86_64.
[trackersmauiapp] Known variants: atom, sandybridge, silvermont, kabylake, default
[CompatibilityChangeReporter] Compat change id reported: 171979766; UID 10159; state: ENABLED
[nativeloader] Configuring classloader-namespace for other apk /system_ext/framework/androidx.window.extensions.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/lib/x86_64:/data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.companyname.Monitormauiapp
[nativeloader] Configuring classloader-namespace for other apk /system_ext/framework/androidx.window.sidecar.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/lib/x86_64:/data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.companyname.Monitormauiapp
[ziparchive] Unable to open '/data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/base.dm': No such file or directory
[ziparchive] Unable to open '/data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/base.dm': No such file or directory
[nativeloader] Configuring classloader-namespace for other apk /data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/lib/x86_64:/data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.companyname.Monitormauiapp
[GraphicsEnvironment] ANGLE Developer option for 'com.companyname.Monitormauiapp' set to: 'default'
[GraphicsEnvironment] ANGLE GameManagerService for com.companyname.Monitormauiapp: false
[GraphicsEnvironment] Neither updatable production driver nor prerelease driver is supported.
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[debug-app-helper] Checking if libmonodroid was unpacked to /data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/lib/x86_64/libmonodroid.so
[debug-app-helper] Native libs extracted to /data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/lib/x86_64, assuming application/android:extractNativeLibs == true
[debug-app-helper] Setting up for DSO lookup in app data directories
[debug-app-helper] Added filesystem DSO lookup location: /data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/lib/x86_64
[debug-app-helper] Using runtime path: /data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/lib/x86_64
[debug-app-helper] checking directory: `/data/user/0/com.companyname.Monitormauiapp/files/.__override__/lib`
[debug-app-helper] directory does not exist: `/data/user/0/com.companyname.Monitormauiapp/files/.__override__/lib`
[debug-app-helper] Checking whether Mono runtime exists at: /data/user/0/com.companyname.Monitormauiapp/files/.__override__/libmonosgen-2.0.so
[debug-app-helper] Checking whether Mono runtime exists at: /data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/lib/x86_64/libmonosgen-2.0.so
[debug-app-helper] Mono runtime found at: /data/app/~~fogg-bM3-wDyF9rZW2h55A==/com.companyname.Monitormauiapp-iAWXvKvUzLk5-Tm98EGP9A==/lib/x86_64/libmonosgen-2.0.so
[trackersmauiapp] Attempt to remove non-JNI local reference, dumping thread
[DOTNET] JNI_OnLoad: JNI_OnLoad in pal_jni.c
[DOTNET] GetOptionalClassGRef: optional class com/android/org/conscrypt/OpenSSLEngineImpl was not found
[monodroid] Creating public update directory: `/data/user/0/com.companyname.Monitormauiapp/files/.__override__`
[trackersmauiapp] Attempt to remove non-JNI local reference, dumping thread
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=10.0.2.2:57559,embedding=1
[monodroid-assembly] open_from_bundles: failed to load assembly MonitorMauiApp.dll
[monodroid-gc] GREF GC Threshold: 46080
[monodroid-assembly] open_from_bundles: failed to load assembly Mono.Android.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Java.Interop.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.InteropServices.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/MonitorMauiApp.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Mono.Android.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Runtime.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Java.Interop.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Runtime.InteropServices.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Collections.dll [External]
Resolved pending breakpoint for 'Android.Runtime.JNIEnv.RegisterJniNatives(System.IntPtr, System.Int32, System.IntPtr, System.IntPtr, System.Int32)' to /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:127 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Threading.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.Thread.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.StackTrace.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Threading.Thread.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Diagnostics.StackTrace.dll [External]
[trackersmauiapp] Attempt to remove non-JNI local reference, dumping thread
The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Mono.Debugging.Client.StackFrame.<GetFullStackFrameTextAsync>d__55.MoveNext() in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging\Mono.Debugging.Client\StackFrame.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mono.Debugging.Client.StackFrame.GetFullStackFrameText(EvaluationOptions options) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging\Mono.Debugging.Client\StackFrame.cs:line 157
   at Xamarin.HotReload.HotReloadSharedBridge.SharedBreakpoints(HotReloadBridge bridge, FunctionBreakpoint bpFunction, TargetEventArgs e) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadSharedBridge.cs:line 239
   at Xamarin.HotReload.HotReloadBridge.Debugger_TargetHitBreakpoint(Object sender, TargetEventArgs e) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 434
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Mono.Debugging.Client.DebuggerSession.OnTargetEvent(TargetEventArgs args) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging\Mono.Debugging.Client\DebuggerSession.cs:line 1254
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleBreakEventSet(Event[] es, Boolean dequeuing) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2204
   at Mono.Debugging.Soft.SoftDebuggerSession.EventHandler() in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1764
Loaded assembly: data-0x7496cfe17050 [External]
Loaded assembly: data-0x7496cfe37070 [External]
Loaded assembly: data-0x74977e9b5a70 [External]
[monodroid-assembly] open_from_bundles: failed to load assembly netstandard.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/netstandard.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Linq.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.Concurrent.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Collections.Concurrent.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:423 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Json.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Text.Json.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encodings.Web.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Text.Encodings.Web.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.ComponentModel.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Maui.Controls.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.ObjectModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.ObjectModel.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Maui.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Graphics.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Essentials.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Abstractions.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Extensions.Logging.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.TypeConverter.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.ComponentModel.TypeConverter.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Uri.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Private.Uri.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Loader.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Runtime.Loader.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:418 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Memory.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Memory.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.Lightweight.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.ILGeneration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Primitives.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Reflection.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Core.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.Core.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.Abstractions.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Console.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Console.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Xaml.dll
[monodroid-assembly] open_from_bundles: failed to load assembly CommunityToolkit.Maui.dll
[monodroid-assembly] open_from_bundles: failed to load assembly CommunityToolkit.Maui.Core.dll
[monodroid-assembly] open_from_bundles: failed to load assembly ZXing.Net.MAUI.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Maui.Controls.Xaml.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/CommunityToolkit.Maui.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/CommunityToolkit.Maui.Core.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/ZXing.Net.MAUI.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Extensions.Logging.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.AppCompat.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.Google.Android.Material.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SwipeRefreshLayout.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.AppCompat.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.Google.Android.Material.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.SwipeRefreshLayout.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Fragment.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Activity.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.ViewModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.Common.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SavedState.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.Fragment.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.Activity.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.Lifecycle.ViewModel.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.Lifecycle.Common.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.SavedState.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.DrawerLayout.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CustomView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.Runtime.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.DrawerLayout.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.CustomView.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Xamarin.AndroidX.Navigation.Runtime.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Net.Primitives.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Net.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly zxing.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/zxing.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/Microsoft.Extensions.DependencyInjection.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.Tracing.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Diagnostics.Tracing.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly MauiCalendarPlugin.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/MauiCalendarPlugin.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Xml.ReaderWriter.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Xml.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Private.Xml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encoding.Extensions.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Text.Encoding.Extensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Numerics.Vectors.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Numerics.Vectors.dll [External]
[trackersmauiapp] Explicit concurrent copying GC freed 624(170KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2080KB/4160KB, paused 522us,75us total 5.437ms
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.RegularExpressions.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Text.RegularExpressions.dll [External]
Thread started:  #2
Thread started:  #3
Thread started:  #4
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Json.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.DataContractSerialization.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Xml.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Primitives.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Runtime.Serialization.Json.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Private.DataContractSerialization.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Runtime.Serialization.Xml.dll [External]
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Runtime.Serialization.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly CommunityToolkit.Mvvm.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/CommunityToolkit.Mvvm.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.CompilerServices.Unsafe.dll
Loaded assembly: /data/data/com.companyname.Monitormauiapp/files/.__override__/System.Runtime.CompilerServices.Unsafe.dll [External]
**System.Reflection.TargetInvocationException:** 'Exception has been thrown by the target of an invocation.'
`

**Comment by jonathanpeppers** [comment]
@wirejp your new issue is related to either the Mono debugger or hot reload.

Can you file an issue with VS feedback (`Help > Send Feedback > Report a Problem`)? That will get your problem to the right folks -- it does not look like a .NET MAUI issue to me.

**Comment by wirejp** [comment]
@jonathanpeppers sure, I will do so. Thank you for your help.
