### ISSUE TITLE
[regression/8.0.0-preview.2.7871] Landscape Mode Splash Screen issue in .NET 8 Preview 2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#14514]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Landscape-Mode-Splash-Screen-issue-in-N/10331745)._

---
[severity:I'm unable to use this version]
Hello,

I’m testing an iOS app MAUI app targeting .NET 8.0 framework Preview 2 by using iOS Simulator feature in VS 2022 Preview 2 (version 17.6 Preview 2) but my splash screen in landscape mode (light appearance mode only) is appearing like it's in a portrait mode with right half of the screen being black and bottom half of the splash screen completely cut off and not visible. 

It works as expected in dark mode, as well as on iPad simulator (both dark and light mode), it's fine on Android Phones too and in portrait mode on all devices. Only when I start the app in iPhones Simulator landscape mode while light (standard) appearance on is when I have this issue. 

The problem is persistent even for the default “MauiApp1” app without writing a single line of code leading me to believe this might be either an issue in .NET 8 or Simulator. I cannot test it on a physical device since Hot Restart is not working for apps targeting .NET 8.0 per [https://developercommunity.visualstudio.com/t/iOS-Hot-Restart-not-working-in-NET-80/10316853]()

I'm attaching few screenshots so you can better visualize the issue at hand of both default MauiApp1 and my app..

Any and all help is greatly appreciated.

Regards,
Alen

![maui_app_1_light_mode.jpg](https://aka.ms/dc/image?name=Badcf90ea83e743aca803fe0a8ff1871d638163242207396126_maui_app_1_light_mode.jpg&tid=adcf90ea83e743aca803fe0a8ff1871d638163242207396126)

![maui_app_1_dark_mode.jpg](https://aka.ms/dc/image?name=B6c7038b8951340bf88865642c9c68f1e638163239560738881_maui_app_1_dark_mode.jpg&tid=6c7038b8951340bf88865642c9c68f1e638163239560738881)

![my_app_light_mode.jpg](https://aka.ms/dc/image?name=Bc9e245b9cfb642b1b13c3b097dca81ea638163241531322948_my_app_light_mode.jpg&tid=c9e245b9cfb642b1b13c3b097dca81ea638163241531322948)

![my_app_dark_mode.jpg](https://aka.ms/dc/image?name=B37520e2a78c74acb971f56f80dbe8b18638163241651396995_my_app_dark_mode.jpg&tid=37520e2a78c74acb971f56f80dbe8b18638163241651396995)

---
#### Feedback Bot on 4/5/2023, 10:13 PM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 4/7/2023, 01:41 AM: 

(private comment, text removed)
#### Alen Paravinja on 4/8/2023, 06:56 AM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 4/10/2023, 05:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
@aparavinja I'm afraid I haven't been able to reproduce your issue on any version of .NET 7 or .NET 8. You mentioned that it happens with the default app, but it seems to load fine on landscape mode for me. I know it' sbeen quite some time, but does this issue still happen for you? If so, are you able to attach the project you used with the exact versions of .NET MAUI and iOS Simulator?

Thanks!

**Comment by samhouts** [comment]
Got it! I'll go ahead and close this for now, but please ping me when you come back to it! Thanks!!
