### ISSUE TITLE
Fresh MAUI app 

### ISSUE THREAD

**Issue by SteveRosam** [dotnet/maui#14512]
Using net6 because net7 gave a load of other errors
Straight out of the box this throws errors about not having `ContentPage` available.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ContentPage' could not be found (are you missing a using directive or an assembly reference?)	MauiApp2 (net6.0-android), MauiApp2 (net6.0-ios), MauiApp2 (net6.0-maccatalyst), MauiApp2 (net6.0-windows10.0.19041.0)	C:\Users\xxx\source\repos\MauiApp2\MauiApp2\MainPage.xaml.cs	3	Active

**Comment by Eilon** [comment]
Hi @SteveRosam , we recommend using .NET MAUI in .NET 7 because it is the most recent supported release.

Can you share some more details about what's installed? Please share the output of running `dotnet --info` and `dotnet workload  list`.

**Comment by SteveRosam** [comment]
I was trying to get this to work all day.

In the end I got it working but had to remove all the MAUI features from VS22 then add them all back again.

I think the thing that fixed it was running this:

`dotnet workload install maccatalyst`

**Comment by jsuarezruiz** [comment]
> dotnet workload install maccatalyst

We are happy to read it; I am going to close the issue but feel free to open a new one if find anything.
