### ISSUE TITLE
Window title bar is not accessible when the Windows platform targeted .NET MAUI App is run as an Unpackaged type

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#14518]
### Description

The window title bar is not accessible when the Windows platform targeted .NET MAUI App is run as an Unpackaged type.

None of the Controls on the Title Bar such as Minimize, Maximize, or Close is responding to user action.

This worked fine with .NET 8 Preview 2 and the Issue is observed in .NET 8 Preview 3 released today.

Note: The Title context menu (Alt + Space) is working.

### Steps to Reproduce

1. Create a new .NET MAUI App from VS IDE/CLI
2. Build the application with the target set as the Windows platform
3. Use the commands provided below to build and run the application

To build the application:

```shell
dotnet build -f net8.0-windows10.0.19041.0 -p:WindowsPackageType=None
```

To run the application:

```shell
dotnet build -f net8.0-windows10.0.19041.0 -t:Run -p:WindowsPackageType=None
```

### Link to public reproduction project repository

Default template itself is suffice, no authored code

### Version with bug

8.0 previews

### Last version that worked well

8.0 previews

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

Nope. Have to use Alt + Space to bring in the Title context menu or use Taskbar/Task Manager to close the application.

### Relevant log output

```shell
NA
```

**Comment by PureWeen** [comment]
I tested this on the latest .NET8 preview7 and it looks like it's working now.

**Comment by egvijayanand** [comment]
It works with the latest preview version `.NET 8 Preview 7`. Can be marked as resolved.
