### ISSUE TITLE
[Bug] Label won't resize after setting its text on Android, other platforms not sure

### ISSUE THREAD

**Issue by imgen** [dotnet/maui#1452]
### Steps to Reproduce

1. Create a maui app using latest VS 2019 preview
2. Run the app in emulator or device
3. Click the button more than 9 times
4. Observe the size, after the count hits 10, the text becomes just one

### Expected Behavior
The label will resize if the text expands out its size

### Actual Behavior
It doesn't resize

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
Fixed by #1700.
