### ISSUE TITLE
UI components not filling parent container

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#14526]
### Description

Place a label inside a grid which is inside a border. I would expect the text to wrap. Instead it just flows off the page.

Even if I remove the border the same thing happens.

Android:

![image](https://user-images.githubusercontent.com/32165641/231323962-bf23223d-9b61-4cf5-81aa-f5b5259e4207.png)

iPhone:

![image](https://user-images.githubusercontent.com/32165641/231339886-539675f0-bd76-42ea-b247-e11e6822958e.png)

### Steps to Reproduce

Open demo app in the repo below.
Tap 'Border Problem'
Observe...

### Link to public reproduction project repository

https://github.com/williambuchanan2/MauiNavigation

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11 - 13, iOS 16

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
You may have wanted to post your full code, since IMO the issue is a bit more subtle.

<img width="1162" alt="スクリーンショット 2023-04-12 12 45 47" src="https://user-images.githubusercontent.com/898335/231344845-d6f3746a-35a9-4f6c-9f43-f95b7e587298.png">

I think the issue here is with ColumnSpan. 

<img width="974" alt="スクリーンショット 2023-04-12 12 59 05" src="https://user-images.githubusercontent.com/898335/231345837-652f3bb7-c32c-4a4b-921b-8fd8faaa399e.png">
<img width="969" alt="スクリーンショット 2023-04-12 12 58 44" src="https://user-images.githubusercontent.com/898335/231345843-21a761d6-8cbb-4bf4-9860-54cfa2e66008.png">

If you set the given Column0 to a specific width, then the span works and the label properly wraps. When set to Auto, it fails.

@hartez Does this sound right?

**Comment by williambuchanan2** [comment]
This is essentially the full code - it is a fully working example. The page it came from is pretty simple.

Just out of interest, would I really want to set the width? I have no idea how big the screen is. I thought that was the whole point of auto sizing. As soon as you put a size to anything then you have lost the ability for it to fit to the screen it happens to be showing on...

**Comment by drasticactions** [comment]
Your title is "UI components not filling parent container", and your description talks about a grid and a label not wrapping. Looking at your code, I think it has to do with Column Span in this context, so it's a more specific issue than what your description would lead someone to believe.

This does look like a bug with Column Span, though. Hence why I asked @hartez.  On iOS and Catalyst it does, mostly, wrap with your original settings, although the height is still off and not all of the text shows. Setting the first column to have a width does produce the right values.

<img width="505" alt="スクリーンショット 2023-04-12 13 41 52" src="https://user-images.githubusercontent.com/898335/231351928-96b47e1f-6cfa-42f0-ae9a-c9d30323c0de.png">
<img width="911" alt="スクリーンショット 2023-04-12 13 42 05" src="https://user-images.githubusercontent.com/898335/231351953-446a678a-3ca8-4980-9f56-7a7161bfe988.png">

**Comment by williambuchanan2** [comment]
Ok I see your point.

In fact I have just noticed that I have this problem in a lot of places. Lots of labels which at some point in the past used to fill their parent but now they don't. Some of them aren't directly inside a grid - for example I have one which is inside a grid/scrollview/verticalstacklayout/collectionview/stacklayout/border and it is doing the same thing. So to me this looks like a bigger problem, and also it seems to have got worse with the current version which I downloaded yesterday.

Again, this is another thing which will make it difficult to deploy an app live before it is fixed....

**Comment by shadowfoxish** [comment]
Label has a property called [LineBreakMode ](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/label?view=net-maui-7.0#control-text-truncation-and-wrapping) you could try. 
LineBreakMode="WordWrap"

**Comment by williambuchanan2** [comment]
> Label has a property called [LineBreakMode ](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/label?view=net-maui-7.0#control-text-truncation-and-wrapping) you could try. LineBreakMode="WordWrap"

Yep - tried that but doesn't have any effect.

**Comment by Xyncgas** [comment]
regarding your point, 'how do you get every device's screen size and adapt to it', I am leaning toward it doesn't matter is what the opinion of the design was.

Pixel originally has a definition of real world dimension, xamarin used relative pixel I believe, so if it works on iphone it is going to look about the same on 4k or 8k tv or ipad

Lable should understand its width in a grid, this provides less friction for composability of components in MAUI which is what it desperately needs, in web technology you can just put ten things in one thing it's that easy the frameworks are so mature and we should expect that experience from MAUI which is modern and has microsoft's name on it starting with these design decisions, so it may be a bug that it doesn't know its dimension when it's in a grid, that being said we can always set the proper dimension like mentioned by @drasticactions to say its parent, now you can use this component without knowing what dimension to give it as long you worry about this on its parent container which at that point it's alright to set it to some value say 150 and see how it looks and expect it to stay relatively the same accross devices

**Comment by williambuchanan2** [comment]
>  at that point it's alright to set it to some value say 150 and see how it looks and expect it to stay relatively the same accross devices

Not sure I understand how setting a width on anything is a good idea. Are you saying that I just make it small enough so that it will even fit on the smallest screen? 

As it turns out with this one it seems to be a problem related to the column span. If you remove that it seems to work ok.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Not repro on android platforms with sample project.
[MauiNavigation-main.zip](https://github.com/dotnet/maui/files/13817139/MauiNavigation-main.zip)
![image](https://github.com/dotnet/maui/assets/77434865/2a37000f-a421-4784-9c9c-cb87bff3a504)
