### ISSUE TITLE
[regression/7.0.81] 7.0.81 Service Release 4 breaks CascadeInputTransparency

### ISSUE THREAD

**Issue by rbrettj** [dotnet/maui#14522]
### Description

After the most recent update (7.0.81), I noticed that the CascadeInputTransparency flag was no longer working on Android. This was not a problem on version 7.0.59. I am aware of [this issue](https://github.com/dotnet/maui/issues/9069) that deals with InputTransparency being broken on Android, but this is a separate issue. I suspect that [this PR](https://github.com/dotnet/maui/pull/11907/files) has something to do with it, specifically the change on line 304 of file `src/Controls/src/Core/Layout/Layout.cs` as it doesn't match the other patterns, but I don't know for sure.

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Add the following:
```
<Grid InputTransparent="True" CascadeInputTransparent="False">
    <Button />
</Grid>
```
3. Try and click the button

### Version with bug

7.0.81

### Last version that worked well

7.0.59

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android

**Comment by jkhoel** [comment]
I am seeing some similar behaviour, where my pop-ups suddenly stopped working on Android devices. I am not able to pinpoint the issue exactly, so contributing in a very meaningful fashion is hard, but it seems to be related to either gesture recognizers og (most likely) some sort of input transparency behaviour.

Reverting from 7.0.81 to 7.0.59 solved the issue.

**Comment by jonakirke94** [comment]
Is there a known workaround for this? Currently this regression is preventing us from bumping our version

**Comment by PureWeen** [comment]
You can try copying the method I have here as a workaround
https://github.com/PureWeen/ShanedlerSamples/blob/main/ShanedlerSamples/Library/Common/HostExtensions.cs#L13-L69

If that doesn't work, please post something about your code so I can see why.

@jonakirke94 @jkhoel if you have reproductions or vague examples of code that's broken for you, can you post them here? Just want to make sure we test as many scenarios as possible here.

**Comment by jonakirke94** [comment]
@PureWeen 

Yes

Okay, that might be a bug on our end.

It appears that the backdrop only behaves correctly when there is a TapGestureRecognizer added so I wonder if the InputTransparent even has an effect here.

See this updated example where the panel also has a TapGestureRecognizer:

[InputTransparentRepro_v2.zip](https://github.com/dotnet/maui/files/11286911/InputTransparentRepro_v2.zip)

Shouldn't setting `CascadeInputTransparent="True"` on the ContentView also resolve the above issues?

**Comment by PureWeen** [comment]
> @PureWeen
> 
> Yes
> 
> Okay, that might be a bug on our end.
> 
> It appears that the backdrop only behaves correctly when there is a TapGestureRecognizer added so I wonder if the InputTransparent even has an effect here.
> 
> See this updated example where the panel also has a TapGestureRecognizer:
> 
> [InputTransparentRepro_v2.zip](https://github.com/dotnet/maui/files/11286911/InputTransparentRepro_v2.zip)
> 
> Shouldn't setting `CascadeInputTransparent="True"` on the ContentView also resolve the above issues?

Yea, it should. We have a PR [here ](https://github.com/dotnet/maui/pull/13725) that should resolve that scenario. But, that wasn't working in 7.0.52 so just making sure there wasn't a regression. 

Another thing you can do is set the `ScrollView` on the contentpage to InputTRansparent and cascade that down. That worked for me.
