### ISSUE TITLE
Splash Screen has a black frame around the logo - even when forced to white

### ISSUE THREAD

**Issue by Systellence** [dotnet/maui#14527]
### Description

I had an issue with API Level 31 where the splash screen had a black frame around the logo with the Light Theme/Light Mode, even when forced to other colors. I then understood that this was a bug and upgraded my mobile device to API level 33 which should resolve the issue. This solved the issue for certain devices BUT I then experienced that the issue persisted on the Xioami Redmi Note 10 Pro. This is now all for Android. I haven't tested it on Mac/iPhone yet.

### Steps to Reproduce

No specific steps.

### Link to public reproduction project repository

N/A

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

Android 13 (API level 33)

### Did you find any workaround?

No workaround

### Relevant log output

```shell
N/A
```

**Comment by mattleibow** [comment]
Can you attach a screenshot with what you are seeing?

Also, can you try Android 10 or 11 and see if anything isdifferent. I do know Android 12+ do not support normal spash screens and do their own formatting to convert into a non-transparent icon.

**Comment by Systellence** [comment]
![Screenshot_2023-04-12-20-31-51-871_com.systellence.votingcrowd.jpg](https://user-images.githubusercontent.com/25317643/231552115-ee3d0d59-6517-4fb9-ad4f-9eccee23957c.jpg)

This is what I see. Suppose to be white around which is the case with a similar mobile device with the same API Level

**Comment by Systellence** [comment]
I see I made a mistake in the initial explanation. I am forcing the splash screen to white, even if the device is in Dark Mode. This works on other devices except on the Xiaomi Redmi Note 10 Pro. I understood the problem was on API Level 31 but now Xiaomi is on level 33. Others are all on 33. Is there another way of doing a splash screen than the standard implementation? I don't have a device on Android 10/11

**Comment by mattleibow** [comment]
You can entirely skip the maui splash screen pattern and use your own drawables.

But, you can also set the background color of the splash to be white.

```xml
<MauiSplashScreen Include="path/to/splash.svg" Color="#FFFFFF" />
```

**Comment by Systellence** [comment]
Hi

Thank you. I forced the background color to white as you indicated.

But how can I bypass the Maui splash screen pattern?

Kind regards

Jaco

**Comment by Systellence** [comment]
Just want to add that after forcing the background it still doesn't work on my Xiaomi. Just on the Samsung

**Comment by Systellence** [comment]
Update. Forcing to #FFFFFF does not work but to any other color works. Really strange.

**Comment by MouratidisA** [comment]
> Update. Forcing to #FFFFFF does not work but to any other color works. Really strange.

@Systellence you're right!!
I am having the same issue...any workaround??

**Comment by Systellence** [comment]
Unfortunately not. I just used another background which is still acceptable. Hopefully this will be sorted with a future update.

**Comment by mattleibow** [comment]
Closing this issue as the feature is working as expected:
* Android 12+ no longer has full screen splash
* Color is the correct attribute to use to change color
* iOS has a known caching issue and we fixed that in .NET 8
