### ISSUE TITLE
"Pair to Mac" in Visual Studio 2022 not working when Mac is behind proxy with authentication

### ISSUE THREAD

**Issue by marco-skizza** [dotnet/maui#14534]
### Description

Hi there

I hope I'm at the right place here...

The Mac is behind a corporate proxy that requires authentication.

On the Mac, I therefore added environment variables for the proxy:
```
export http_proxy=http://my.proxy.com
export https_proxy=http://my.proxy.com
```

"Pair to Mac" in Visual Studio 2022 currently doesn't seem to take this into account.

I was able to reproduce this problem on the Mac by calling `sudo dotnet workload install ios`.
When calling it with `sudo -E`, the proxy was taken into account and the command worked.

So as a fix, you maybe can call `sudo -E dotnet workload install ios` or the like in Visual Studio 2022.

Kind Regards
Marco

### Steps to Reproduce

1. Add the mentioned environment variables on the Mac
2. Call "Pair to Mac" in Visual Studio 2022

Expected Outcome: The proxy settings should be taken into account
Actual Outcome: The proxy settings are ignored

### Link to public reproduction project repository

You can use the .NET MAUI starter project

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Ventura 13.3.1

### Did you find any workaround?

No

**Comment by MPCoreDeveloper** [comment]
The Visual studio feedback server is broken for som time this is really frustrating , as I have invested a lot of time in creating nice detailed reports , but Visual Studio 17.5.4   does not see my Mac when I press the Distribute button for the rest it works fine ( it does use the mac for builds and with the emulators )  

![DevCommunityBroken](https://user-images.githubusercontent.com/37024522/232063140-aec05fd8-d4ef-4f72-a5dc-4242d1036977.png)

**Comment by marco-skizza** [comment]
A bug for Visual Studio has been placed here:
https://developercommunity.visualstudio.com/t/Pair-to-Mac-in-Visual-Studio-2022-not/10337622
