### ISSUE TITLE
text on button disappears UI problem

### ISSUE THREAD

**Issue by Anmol-Zahra** [dotnet/maui#14533]
### Description

my .net maui app works fine in debug mode but when i release it as apk file the text on buttons disappear during working of app,like if im using app first everything goes fine but after some time text on buttons will disappear like shown in image

### Steps to Reproduce

1-create new .net maui app
2- create 3 to 4 buttons using grid and also create there actions 
3-in debug mode it will work fine just create its apk 
4-test apk file you'll experience disappearing text on buttons more offen when you'll use app more frequently

Expected Outcome: app will run fine but  in more load  button text shouldn't disappear
Actual Outcome: frequently usage of app results in text disappearing from buttons

### Link to public reproduction project repository

https://github.com/anmol776/Button-Text-Disappearing.git

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 11

### Did you find any workaround?

no i didn't find any work around

**Comment by Anmol-Zahra** [comment]
do you have any update about the issue I've reported

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Not repro on android platforms with sample project.
[Button-Text.zip](https://github.com/dotnet/maui/files/13827783/Button-Text.zip)
