### ISSUE TITLE
can not achive immersive mode in android?

### ISSUE THREAD

**Issue by ljzj2** [dotnet/maui#14530]
### Description

I want to make immersive mode(status bar transparent) but navigationbar not .

I can set layoutNoLimits
`this.Window.SetFlags(WindowManagerFlags.LayoutNoLimits,WindowManagerFlags.LayoutNoLimits);`
in MainActivity.cs OnCreate.

or Set `FullScreen`

But I do not want it the navigationbar can not be touched.

why cannot I set `WindowManagerFlags.TranslucentStatus`?
![image](https://user-images.githubusercontent.com/110752116/231370268-8ee4a936-54da-457a-ab01-9093784722e2.png)

the status bar is not transparent
you can set the color to transparent but still not.

I want it be immersive or bottom bar do not hide in LayoutNoLimits.

in immersive the status bar not transparent is also a but not fixed in xamarin.

### Steps to Reproduce

1.Create a maui project
2.open platform->android->MainActivity
3.type code `
`this.Window.SetFlags(WindowManagerFlags.TranslucentStatus,WindowManagerFlags.TranslucentStatus);`

run the android.

### Link to public reproduction project repository

you can create it

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 11

### Did you find any workaround?

No

**Comment by ljzj2** [comment]
@drasticactions  you just create maui project and open platform/android/MainActivity.cs and add the code:
`
protected override void OnCreate(Bundle savedInstanceState)
    {
        base.OnCreate(savedInstanceState);

        Window.AddFlags(Android.Views.WindowManagerFlags.TranslucentStatus);
    }
`

do not need repo I think.

**Comment by drasticactions** [comment]
@ljzj2 

Your example is

`3.type code  this.Window.SetFlags(WindowManagerFlags.Immersive,WindowManagerFlags.TranslucentStatus);``

That enum, as far as I can tell, doesn't exist. You are the first person on GitHub to reference it.

<img width="1097" alt="スクリーンショット 2023-04-12 16 54 39" src="https://user-images.githubusercontent.com/898335/231390592-1134646f-3efd-4ab5-9f68-4765c2228a8a.png">

**Comment by drasticactions** [comment]
`Window.AddFlags(Android.Views.WindowManagerFlags.TranslucentStatus);` does the same behavior in a .NET Android app as well, without MAUI.

<img width="887" alt="スクリーンショット 2023-04-12 17 08 27" src="https://user-images.githubusercontent.com/898335/231394065-a9feec7c-c944-487d-ba29-db4e957e41f2.png">

That said, I could find code that I _think_ does what you want where you can make the status bar transparent or a color with an alpha value, 

https://github.com/drasticactions/MauiRepros/blob/main/AndroidImmersive/MainActivity.cs#L24-L30

<img width="1191" alt="スクリーンショット 2023-04-12 17 09 39" src="https://user-images.githubusercontent.com/898335/231394986-09ee9415-0fbd-480d-9795-a2377e416063.png">

But unless someone like @jonathanpeppers says otherwise, I'm unsure if this is a MAUI issue.

**Comment by ljzj2** [comment]
@drasticactions  yes you are right.
maybe is not a MAUI issue. maybe a `mono` issue right?
If do not use Shell in MAUI I think I can make status bar transparent.(just create maui project and do not use shell)
it is same in xamarin.forms(use xamarins shell it is not tranparent and do not use shell it is transparent)

and I asked jpost in android team in .net android and he think it is not a mono android issue.

**Comment by ljzj2** [comment]
@drasticactions  can you use Android Layout Inspector to check it?
something may in front of the status bar.

**Comment by drasticactions** [comment]
If you can make an example of what you're trying to do with Shell, then that would help us know what you're trying to do and if there is a bug or not. 

I believe there is no bug for the issue you raised in the original post. You can change the translucent color of the status bar though Android's APIs. Now, how that works in conjunction with what you're trying to do with shell, or if Shell should be able to do something out of the box without you needing to access those APIs, that's a different question. 

I am closing this issue. If you can create a new issue with a reproduction project with what you expect to be able to do, that would be great.

**Comment by ljzj2** [comment]
@drasticactions

thankyou I searched and get what 

it is not work in `Shell`  and it is not a bug. just do not work in `Shell`
maybe the program manager do not think it is useful.

**Comment by ljzj2** [comment]
@drasticactions

thankyou I searched and get what 

it is not work in `Shell`  and it is not a bug. just do not work in `Shell`
maybe the program manager do not think it is useful.
