### ISSUE TITLE
Maui Android: If keyboard is on the page scroll not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#14548]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-Android:-If-keyboard-is-on-the-page/10336626)._

---
[severity:It's more difficult to complete my work]
After I complete typing in the text box and want to type in the text box bellow the text box, I taped outside the textbox but the keypad is not closed automatically on focus changed also at that time I can't scroll the page to access the other controls so I have to close the textbox each time manually to access the other textboxes or button. 

I am using the latest Visual Studio 2022 version: 
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current- Version 17.5.4

I have attached a sample project here: TestKeyPadIssue.zip

---
#### Feedback Bot on 4/12/2023, 01:26 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
@tj-devel709 Could have been fixed by your recent PRs?

**Comment by PureWeen** [comment]
Duplicate of #12002
