### ISSUE TITLE
Can't build to local iOS device after updating MAUI workload with Hot Restart

### ISSUE THREAD

**Issue by faheys** [dotnet/maui#14578]
### Description

After updating the MAUI workload from version **7.0.59** to **7.0.81** I am no longer able to build to any local iOS devices using Hot Restart on Windows VS 2022.
The build errors immediately with the following error: "The specified network password is not correct". This occurs in both Debug and Release configurations. 
Automatic provisioning is enabled and I have no issues building to the iOS Simulators through Pair to Mac.

Relevant Infomation:
![image](https://user-images.githubusercontent.com/28056243/231924982-e16211cf-23a3-42ea-8f3a-9075e25c12ac.png)

### Steps to Reproduce

1. Update MAUI workload to 7.0.81
2. Attempt to build MAUI project to a local iOS device using Hot Restart

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

7.0.81 (current)

### Last version that worked well

7.0.59

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16.2

### Did you find any workaround?

No workaround found.

### Relevant log output

```shell
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.2.2054\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error : The specified network password is not correct.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.2.2054\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error :
```

**Comment by drasticactions** [comment]
I updated your comment from "Hot Reload" to "Hot Restart"

"Hot Restart" is the feature where you can deploy a Xamarin.Forms or MAUI Application locally on Windows without a Mac.

**Comment by alaskanrogue** [comment]
I have the same issue since my MAUI workload update yesterday. It doesn't make sense that this is a Visual Studio issue as the problem wasn't occurring before the update. This is a workload issue.

**Comment by faheys** [comment]
I too am inclined to think this is a workload issue as it occurs on different versions of Visual Studio.

**Comment by wd-mutasim** [comment]
I have the same issue, 12 hours trying to fix it with no luck, even after reinstalling Visual Studio .
I have removed all certificates and profiles from %LOCALAPPDATA%\Xamarin\iOS\Provisioning
Creating new certificates throgh API from Visual Studio

When you trying to load manually the certificate which is created from Visual Studio API located in %LOCALAPPDATA%\Xamarin\iOS\Provisioning\Certificates when it asking for the password [%LOCALAPPDATA%\Xamarin\iOS\Provisioning\Certificates\xxxxxxxxx.pass] you will get the same massage "The specified network password is not correct". 
It seems like Visual creating wrong password , 

I'm planning to generate new certificate from mac and uploaded to Visual Studio if it works I will update you

**Comment by drasticactions** [comment]
> I have the same issue since my MAUI workload update yesterday. It doesn't make sense that this is a Visual Studio issue as the problem wasn't occurring before the update. This is a workload issue.

Workloads are updated as part of Visual Studio, unless you've manually updated them from CLI. Hot Restart (Building iOS Apps locally to your iPhone) is a Visual Studio feature, depending on the underlying workloads and whatever changes they bring.

**Comment by faheys** [comment]
> > I have the same issue since my MAUI workload update yesterday. It doesn't make sense that this is a Visual Studio issue as the problem wasn't occurring before the update. This is a workload issue.
> 
> Workloads are updated as part of Visual Studio, unless you've manually updated them from CLI. Hot Restart (Building iOS Apps locally to your iPhone) is a Visual Studio feature, depending on the underlying workloads and whatever changes they bring.

I updated via the CLI with no change in VS version and faced the issue.

**Comment by alaskanrogue** [comment]
The issue does not exist for the Android or Windows platforms.

**Comment by drasticactions** [comment]
> I updated via the CLI with no change in VS version and faced the issue.

Because the issue is, most likely, with Hot Restart, and it's present in both versions of Visual Studio with that version of the MAUI/iOS Workload.



> Workloads are installed on top of the .NET SDK to provide support for various application types, such as .NET MAUI and Blazor Web Assembly AOT. They are not extensions to Visual Studio.

Workload updates are installed as part of Visual Studio updates.

**Comment by alaskanrogue** [comment]
Going back to the issue itself, 

    1) What is the purpose of use of the network in the Hot Restart?
    2) Where do we look for the network password in use? 
    3) From where it is obtained? 
    4) How is it specified?
    5) Who specifies it?

**Comment by jenksbryan** [comment]
I did notice for the first time recently that VS makes some API call to Apple every time it builds. I only noticed this because VS prompted me for the 2FA OTP code that Apple sent over SMS at the same time.
So VS is using something from an Apple API at least sometimes when you run an iOS debug build.

**Comment by faheys** [comment]
Just for clarification, I’m able to build to a local iOS device using VS for Mac and workload version 7.0.81 just fine, presumably because Hot Restart is not being used on the Mac..

**Comment by Moro890** [comment]
Has someone opened a VS Feedback issue?

**Comment by MLB-BIOMETRIC** [comment]
We are also experiencing this issue after updating!

**Comment by alaskanrogue** [comment]
I just did: https://developercommunity.visualstudio.com/t/Cant-build-to-local-iOS-device-after-up/10344787?port=1025&fsid=c72fb983-a265-4c56-ba30-9ad2d9b52165

**Comment by jenksbryan** [comment]
> Has anyone opened a VS Feedback issue?

Submitted one a couple days ago as well:
https://developercommunity.visualstudio.com/t/net-MAUI-Unable-to-build-iOS-app:-Error/10341302

**Comment by MLB-BIOMETRIC** [comment]
Any way to downgrade to v. 7.0.59?

**Comment by samhouts** [comment]
Thanks, everyone! We received the feedback ticket, and we're on it!

**Comment by jenksbryan** [comment]
For reference, I tried clearing out all Apple accounts from VS and creating a whole new Apple ID (on the same enterprise account) with a new certificate. Same issue.

**Comment by Alfort-G** [comment]
Same issue here for Microsoft Visual Studio Enterprise 2022 (ARM 64-bit) - Version 17.6.0 Preview 5.0

**Comment by FM1973** [comment]
Please let us know how to get back to version 7.0.59!!!
Or at least how to remove the version 7.0.81 and do a reinstall of 7.0.59.
I tried to uninstall visual studio  and reinstall version 17.5.3
Doing a dotnet workload list after reinstall shows 7.0.81 again.
Does anyone know how to get back to the previous verion?
7.0.81 has some major bugs (grid) and is unusable!!!

**Comment by MLB-BIOMETRIC** [comment]
Good news! Maria from Microsoft just commented this on the[ developercommunity.microsoft.com](https://developercommunity.visualstudio.com/t/net-MAUI-Unable-to-build-iOS-app:-Error/10341302) thread:

``
A fix for this issue has been internally implemented and is being prepared for release. We'll update you once it becomes available for download.
``

**Comment by bakhodirk** [comment]
Coooool, when can we expect a new release?

**Comment by FrKaram** [comment]
Same issue here
I really try to like this MAUI thing but honnestly each new release introduces as many issues as it solves

**Comment by Alfort-G** [comment]
I have the same feeling of constant frustration. Myself I face too many issues and I waste a lot of time looking at how to fix things, use workarounds or close/open things multiple times. You install an upgrade and you hope for the best, you deploy to a device in release mode and you hope for the best...

**Comment by FM1973** [comment]
@bryansjenks 
So please let us know how to build an IOS version of a MAUI app on Windows  without any dependency on a Mac. There is none I know of...

**Comment by bryansjenks** [comment]
I's the feature we're here on this thread waiting for a fix on: "iOS Hot Restart"
https://learn.microsoft.com/en-us/dotnet/maui/ios/hot-restart?view=net-maui-7.0
From that article:

> .NET Multi-platform App UI (.NET MAUI) hot restart enables you to quickly deploy a .NET MAUI app to a 64-bit local iOS device, from Visual Studio 2022, _without requiring a Mac build host_.

Setting it up has some trickiness (and this current bug being discussed), but in general you pick local iOS device from the build menu.
![image](https://user-images.githubusercontent.com/63628719/236863497-1210318e-7e14-4d84-b4e2-ab76815d354a.png)

**Comment by FM1973** [comment]
@bryansjenks 
Cool, I didn´t know this feature exists. Thanks for the info!

**Comment by alaskanrogue** [comment]
I was just able to build and deploy successfully with Preview Version 17.6.0 Preview 7.0.

**Comment by faheys** [comment]
I can confirm that Visual Studio Build 17.6.0 Preview 7.0 has fixed the issue for me. The new build also comes with a MAUI workload update from 7.0.81 -> 7.0.86. Will go ahead and mark the issue as closed!

**Comment by bryansjenks** [comment]
Working for me as well. Thanks for all your help MS team!
