### ISSUE TITLE
Android系统下RuntimeInformation.IsOSPlatform无法正常使用.与Xamarin不一致

### ISSUE THREAD

**Issue by BaY1251** [dotnet/maui#14579]
### Description

var isAndroid = RuntimeInformation.IsOSPlatform(OSPlatform.Linux)
返回false, 并且没有任何一个平台对应Android.

### Steps to Reproduce

在任意工程源程序中 插入 var isAndroid = RuntimeInformation.IsOSPlatform(OSPlatform.Linux)
加断点确认,返回值.

### Link to public reproduction project repository

无

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API25

### Did you find any workaround?

使用Xamarin无此问题.

**Comment by hez2010** [comment]
Android is not Linux, we recommend you to use `OperatingSystem.IsAndroid()`;

**Comment by BaY1251** [comment]
谢谢 烦请尽量将IsOSPlatform标记为deprecated. 避免迁移时因不兼容导致的应用错误
