### ISSUE TITLE
Border control display bug in a Grid (Windows)

### ISSUE THREAD

**Issue by andrewstellman** [dotnet/maui#14573]
### Description

When I create a Grid layout with a Border in it, the Border is rendered weirdly, flowing off the bottom of the window. This seems to affect only .NET MAUI apps on Windows, it works fine on macOS.

### Steps to Reproduce

Load BorderTest.sln from https://github.com/andrewstellman/BorderTest/ and run the .NET MAUI app. On Windows ARM it looks like this -- the Border in the bottom cell expands past the bottom of the page:

![image](https://user-images.githubusercontent.com/7516297/231874820-5260cb2e-2bfc-4868-8ba6-45353ac61682.png)

Make the window shorter by clicking on the bottom of the window frame and dragging up and the other controls resize with the Grid, but the Border does not:

![image](https://user-images.githubusercontent.com/7516297/231874876-e922461d-ae0a-4136-a136-e7419c15e26c.png)

Make the window smaller by clicking the lower right corner and dragging up and left just a few pixels, and the Border control corrects itself and looks like it should:

![image](https://user-images.githubusercontent.com/7516297/231874942-f40b7bde-d2de-49c5-ad17-f971b692fe71.png)

Note that the Button also resizes itself correctly, so this may be a problem with the Grid and not the Border. But when I replace the Border with a Button it works, so evidence seems to point to an issue with Border:

![image](https://user-images.githubusercontent.com/7516297/231875008-3ac05b81-0561-43e5-a727-1e8ec7872138.png)

## Workload list

```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
runtimes-windows           7.0.3/7.0.100          VS 17.6.33417.168
maui-windows               7.0.59/7.0.100         VS 17.6.33417.168
maui-maccatalyst           7.0.59/7.0.100         VS 17.6.33417.168
maccatalyst                16.2.1024/7.0.100      VS 17.6.33417.168
maui-ios                   7.0.59/7.0.100         VS 17.6.33417.168
ios                        16.2.1024/7.0.100      VS 17.6.33417.168
maui-android               7.0.59/7.0.100         VS 17.6.33417.168
android                    33.0.26/7.0.100        VS 17.6.33417.168
```

## Reproduced on Windows Intel

The above screenshots were taken on Windows ARM. The following screenshot shows the problem also affects Widows Intel:

![image](https://user-images.githubusercontent.com/7516297/231875300-bdd53f8d-2a5d-4d8c-9de1-c7d39982051c.png)

```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.81/7.0.100         VS 17.5.33530.505
maui-maccatalyst           7.0.81/7.0.100         VS 17.5.33530.505
maccatalyst                16.2.2035/7.0.100      VS 17.5.33530.505
maui-ios                   7.0.81/7.0.100         VS 17.5.33530.505
ios                        16.2.2035/7.0.100      VS 17.5.33530.505
maui-android               7.0.81/7.0.100         VS 17.5.33530.505
android                    33.0.46/7.0.100        VS 17.5.33530.505
```

## Cannot reproduce on MAUI macOS

When I run on MAUI macOS the page renders as expected:

![image](https://user-images.githubusercontent.com/7516297/231875361-f6c5a7d6-1e34-4542-ad0f-57da01787b8b.png)

```
Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui-maccatalyst           7.0.81/7.0.100        SDK 7.0.200        
maui-ios                   7.0.81/7.0.100        SDK 7.0.200        
maui-android               7.0.81/7.0.100        SDK 7.0.200        
```

### Link to public reproduction project repository

https://github.com/andrewstellman/BorderTest/

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 ARM and Intel

### Did you find any workaround?

Unfortunately, I couldn't find a workaround 😢

**Comment by Foda** [comment]
Here's a video that shows the issue:

https://github.com/dotnet/maui/assets/890772/72777595-f604-4a02-8c9b-7940ac31d5ca

Looks like it's not a issue with Border specifically, but when a Grid is inside a ScrollView without a fixed height set.

**Comment by andrewstellman** [comment]
Ah, that's great—glad to see this!! 

That XAML is from a project in Chapter 6 of the next edition of Head First C# -- we're converting all the WPF projects in the book to use MAUI. I am **_absolutely loving MAUI ❤️❤️❤️_** and so, so, SO excited to teach MAUI to our readers. I've run into two bugs (this one and #13604) in projects in the book so far. I'm really hoping they'll both be fixed by the time we go to press!

Here's a PDF with a draft of that project – it's still going through tech review and hasn't been copyedited, so there may be typos/errors: [hfc#5e_ch06 - Beehive Management System (early draft).pdf](https://github.com/dotnet/maui/files/11511093/hfc.5e_ch06.-.Beehive.Management.System.early.draft.pdf)


(We'll introduce data binding in the next chapter, and they'll update the code to use data binding.)
