### ISSUE TITLE
Can't find Apple SDK Location despite correct SDK path

### ISSUE THREAD

**Issue by mash808** [dotnet/maui#14582]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: macos

Hi there,

I'm using .NET MAUI for the first time on my Macbook Pro running Ventura 13.3. Currently trying to run the default hello world app with Visual Studio, just to see if it builds properly. However, it can't find the macOS SDK. I have double checked that I have the correct path to the SDK in Visual Studio preferences > SDK Locations > Apple (confirmed via `xcrun --show-sdk-path` output in terminal). I have also restarted Visual Studio multiple times and selected `Xcode 14.2 (14C18)` under Xcode > Settings > Locations > Command Line Tools.

Here is the error received when attempting build the application:
```
Error: Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'. Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK).
```

Any help here would be much appreciated!

Thanks for your time.

**Comment by jfversluis** [comment]
Hey there, glad to see you're trying .NET MAUI! Sorry you're running into a snag here.

Did you try and start Xcode? It might prompt you to install additional command-line tools. Does it do that, and if you install those, does this error go away?

**Comment by mash808** [comment]
> Hey there, glad to see you're trying .NET MAUI! Sorry you're running into a snag here.
> 
> Did you try and start Xcode? It might prompt you to install additional command-line tools. Does it do that, and if you install those, does this error go away?

Hi. Thanks for the reply! I have the command-line tools installed up to the latest and greatest version but the error is still occurring unfortunately. 

![out](https://user-images.githubusercontent.com/39176556/232313641-bc166e02-02d3-42a0-886e-572dbf5e58c5.png)

**Comment by Ghostbird** [comment]
I've probably got the same issue:
```log
…msbuild/iOS/Xamarin.Shared.targets(1738,3): error : Could not find a valid Xcode app bundle at '/Applications/Xcode_14.2.app'. Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK)
```

The message says to use some Visual Studio setting to fix it, but this is a build machine with .NET CLI and the `maui-ios` workload installed. Why does it refer to Visual Studio?

On a system level, xcode path is set-up correctly: `/Applications/Xcode.app/Contents/Developer`. At some point last week, the drive clean-up tool of MacOS was used to clean-up old XCode installs. Then the latest one was installed in `/Applications/Xcode.app`. MAUI builds worked fine after that. But today (maybe after a reboot) `msbuild` looks for it in the cleaned-up location: `/Applications/Xcode_14.2.app`
