### ISSUE TITLE
Partial classes and methods not working for .net maui library

### ISSUE THREAD

**Issue by DiagProf** [dotnet/maui#14601]
### Description

I want to store code that I want to use frequently (across different apps) in a .net maui library. But somehow it doesn't work in libraries to store the platform specific code in partial classes.
It does not compile.

Error	CS8795	Partial method 'DelayLibService.DelayLibWithDummyReturnAsync(int)' must have an implementation part because it has accessibility modifiers.	MauiLibraryWithAsync (net7.0)	….\MauiLibTest\MauiLibraryWithAsync\Services\PartialMethods\DelayLibService.cs	7	Active

Error	CS8795	Partial method 'DelayLibService.DelayLibWithDummyReturn(int)' must have an implementation part because it has accessibility modifiers.	MauiLibraryWithAsync (net7.0)	…\MauiLibTest\MauiLibraryWithAsync\Services\PartialMethods\DelayLibService.cs	9	Active

If I do exactly the same in the main project, it works. 

	    //over Lib
		var dsLib = new DelayLibService();
		await dsLib.DelayLibWithDummyReturnAsync(100);
		dsLib.DelayLibWithDummyReturn(100);

        //direct in the main project 
		var ds = new DelayService();
        await ds.DelayWithDummyReturnAsync(500);
        ds.DelayWithDummyReturn(500);

### Steps to Reproduce

Try to compile the example projcet

### Link to public reproduction project repository

https://github.com/DiagProf/MauiLibTest_ErrorExample

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

all

### Did you find any workaround?

I tried (because I read it) to delete the TargetFrameworks "net7.0" from the Lib project. 
But I'm not sure if this is a workaround.

**Comment by drasticactions** [comment]
The error shown is correct: You don't have an implementation of that code for `net7.0`. That's what it's complaining about. You either need to have an implementation of that code for net7.0 that you override with the platform code, or remove the `net7.0` tfm and only target the platforms directly.

**Comment by DiagProf** [comment]
Hello, I don't quite understand that. I didn't add the TargetFramework "net7.0" to the lib. It all comes from the ".NET MAUI Class Library" project template.

**Comment by RPGUK** [comment]
@DiagProf, the comment from drasticactions did help. I didn't check the project from the Error List. After reading the comment I saw that I was only getting the error in net7.0-macatalyst. I hadn't implemented the code on that particular platform. Android, iOS, Windows was implemented. I copied the partial class, with the partial methods from iOS to macCatalyst (hopefully behaves the same as iOS). Tizen, doesnt seem to need an implementation. Hope this helps you out.

**Comment by DiagProf** [comment]
What I don't understand is when I create a Maui library with VS 2022 Review, why is .net7.0 created as a target?
<TargetFrameworks>net7.0;net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>

And the second question is. What I have to do if I wanted to implement the function under the .net7.0 target. For example, what would the folder under Platforms be called?
