### ISSUE TITLE
Still cannot build in Release mode on Android with AOT and trimming disabled

### ISSUE THREAD

**Issue by rbrettj** [dotnet/maui#14605]
### Description

This is still an issue! There was an [issue](https://github.com/dotnet/maui/issues/7284) that was closed, but I am running into this with a File -> New MAUI project. Just because someone stops responding doesn't mean this is suddenly fixed.

### Steps to Reproduce

1. Create a file new MAUI app
2. Update csproj file to disable AoT and trimming
3. Change to release mode
4. Try and build the app

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by drasticactions** [comment]
Reopened, https://github.com/dotnet/maui/issues/7284

**Comment by jonathanpeppers** [comment]
> Version with bug
6.0.312

@drasticactions I think they are saying this happened in .NET 6, but #7284 seemed to be fixed in .NET 7 when I tested it.

**Comment by jonathanpeppers** [comment]
What *is* the error? Details here on getting a log: https://github.com/dotnet/maui/issues/7284#issuecomment-1511383946

**Comment by rbrettj** [comment]
I don't have time to do that right now. Did you try the repro steps yourself? I imagine that would get you whatever it is you're needing much faster than me.
