### ISSUE TITLE
The background color of Entry cannot be switched in the Normal and Focus states. 

### ISSUE THREAD

**Issue by jessiezh0320** [dotnet/maui#14600]
### Description

If we set the `BackgroundColor` of Entry both on normal and focus status, the BackgroundColor of Entry on `normal` status will replace the color on focus status while the Entry get the focus.

And if we remove the `BackgroundColor` of Entry on normal and set the `BackgroundColor` of Entry on focus status, the  `BackgroundColor` of Entry on focus status will display normally , but after the entry lose focus, the `BackgroundColor` of Entry  is still the color in focus. 

### Steps to Reproduce

1.create a new maui app
2.add the following code to `MainPage.xaml`:

    <StackLayout> 
        <StackLayout.Resources>
            <Style TargetType="Entry">
                <Setter Property="Margin"
                        Value="20, 0" />
                <Setter Property="FontSize"
                        Value="18" />
                <Setter Property="VisualStateManager.VisualStateGroups">
                    <VisualStateGroupList>
                        <VisualStateGroup x:Name="CommonStates">
                            <VisualState x:Name="Normal">
                                
                            </VisualState>
                            <VisualState x:Name="Focused">
                                <VisualState.Setters>
                                    <Setter Property="FontSize"
                                            Value="36" />
                                    <Setter Property="BackgroundColor"
                                            Value="Red" />
                                </VisualState.Setters>
                            </VisualState>
                            <VisualState x:Name="Disabled">
                                <VisualState.Setters>
                                    <Setter Property="BackgroundColor"
                                            Value="Pink" />
                                </VisualState.Setters>
                            </VisualState>
                        </VisualStateGroup>
                    </VisualStateGroupList>
                </Setter>
            </Style>

        </StackLayout.Resources>

        <Label Text="Normal Entry" />
        <Entry />

        <Button Text="test" WidthRequest="200" HorizontalOptions="CenterAndExpand" Margin="20"/>
       
    </StackLayout>

### Link to public reproduction project repository

https://github.com/dotnet/maui/issues/new?assignees=&labels=t%2Fbug&template=bug-report.yml

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

android 10

**Comment by marshallellis** [comment]
Ran into this as well! Fantastic guys! Thanks for the help!

**Comment by marshallellis** [comment]
So is this fixed in MAUI 8.0.0 and or .NET 4.8333? Trying to see how I get this fix???

Thank you

Marshall

**Comment by samhouts** [comment]
You should be able to find it in the latest previews of MAUI 8.0, which you can install with Visual Studio 17.8 P1! Please let us know if there are any problems. Thanks!!
