### ISSUE TITLE
[Enhancement] In-App purchase and subscription API

### ISSUE THREAD

**Issue by scarrier92** [dotnet/maui#1461]
## Summary
I'd like if it was possible to natively being able to monitise my app. It would be nice to be able to support iOS and Android  InApp purchase and subscription.

## API Changes

New API 

## Intended Use Case
Prompt user to purchase something. Proceed with native  payment interface and then also have a Methode to check if subscription is active or wether it was cancelled or not renew ...

Let user upgrade their subscription to annual instead of monthly for example

All of this with out having to deal with transaction ids and...

Thank you

**Comment by GalaxiaGuy** [comment]
One thing that complicates this is that Android does not really have s native payment interface.

There is Google Play,  which is what I assume you mean, but that depends on Google Play services which MAUI probably won't take a dependency on.

Beyond that there is also Amazon, HarmonyOS and in the near future maybe Microsoft Store on Windows 11.

**Comment by GalaxiaGuy** [comment]
This was the discussion on the Essentials repo:
https://github.com/xamarin/Essentials/issues/472

And there is this:
https://github.com/jamesmontemagno/InAppBillingPlugin

**Comment by Redth** [comment]
The already mentioned InAppBillingPlugin fits this purpose very well.  We'll continue to collaborate with @jamesmontemagno when we can on keeping that solution updated :)
