### ISSUE TITLE
PointerGestureRecognizer  CommandParameter using ICommand as declaring Type instead of object

### ISSUE THREAD

**Issue by cgp1976** [dotnet/maui#14629]
### Description

Am I missing something, I noticed that the PointerGestureRecognizer is using ICommand type as property instead of object. 
basically, I am trying to pass parameter to the command via the comandParameter

### Steps to Reproduce

var pointerGesture = new PointerGestureRecognizer();
pointerGesture.PointerEnteredCommandParameter;  <<<<<< over here, I right click go to definition

        public ICommand PointerEnteredCommand { get; set; }
        public ICommand PointerEnteredCommandParameter { get; set; }  <<< ICommand
        public ICommand PointerExitedCommand { get; set; }
        public ICommand PointerExitedCommandParameter { get; set; }   <<< ICommand
        public ICommand PointerMovedCommand { get; set; }
        public ICommand PointerMovedCommandParameter { get; set; }  <<< ICommand

#region Assembly Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// C:\Program Files\dotnet\packs\Microsoft.Maui.Controls.Ref.win\7.0.81\ref\net7.0-windows10.0.19041\Microsoft.Maui.Controls.dll
#endregion

#nullable enable

using System;
using System.Windows.Input;

namespace Microsoft.Maui.Controls
{
    //
    // Summary:
    //     Provides pointer gesture recognition and events.
    public sealed class PointerGestureRecognizer : GestureRecognizer
    {
        //
        // Summary:
        //     The command to invoke when the pointer has entered the view. This is a bindable
        //     property.
        public static readonly BindableProperty PointerEnteredCommandProperty;
        //
        // Summary:
        //     An object to be passed to PointerEnteredCommand. This is a bindable property.
        public static readonly BindableProperty PointerEnteredCommandParameterProperty;
        //
        // Summary:
        //     The command to invoke when the pointer has exited the view. This is a bindable
        //     property.
        public static readonly BindableProperty PointerExitedCommandProperty;
        //
        // Summary:
        //     An object to be passed to PointerExitedCommand. This is a bindable property.
        public static readonly BindableProperty PointerExitedCommandParameterProperty;
        //
        // Summary:
        //     The command to invoke when the pointer has moved within the view. This is a bindable
        //     property.
        public static readonly BindableProperty PointerMovedCommandProperty;
        //
        // Summary:
        //     An object to be passed to the PointerMovedCommand. This is a bindable property.
        public static readonly BindableProperty PointerMovedCommandParameterProperty;

        //
        // Summary:
        //     Initializes a new instance of PointerGestureRecognizer.
        public PointerGestureRecognizer();

        //
        // Summary:
        //     Identifies the PointerEnteredCommand bindable property.
        public ICommand PointerEnteredCommand { get; set; }
        //
        // Summary:
        //     Identifies the PointerEnteredCommandParameter bindable property.
        public ICommand PointerEnteredCommandParameter { get; set; }
        //
        // Summary:
        //     Identifies the PointerExitedCommand bindable property.
        public ICommand PointerExitedCommand { get; set; }
        //
        // Summary:
        //     Identifies the PointerExitedCommandParameter bindable property.
        public ICommand PointerExitedCommandParameter { get; set; }
        //
        // Summary:
        //     Identifies the PointerMovedCommand bindable property.
        public ICommand PointerMovedCommand { get; set; }
        //
        // Summary:
        //     Identifies the PointerMovedCommandParameter bindable property.
        public ICommand PointerMovedCommandParameter { get; set; }

        //
        // Summary:
        //     Raised when the pointer enters the view.
        public event EventHandler<PointerEventArgs>? PointerEntered;
        //
        // Summary:
        //     Raised when the pointer exits the view.
        public event EventHandler<PointerEventArgs>? PointerExited;
        //
        // Summary:
        //     Raised when the pointer moves within the view.
        public event EventHandler<PointerEventArgs>? PointerMoved;
    }
}

### Link to public reproduction project repository

nil

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Window 11 Arm

### Did you find any workaround?

nil

### Relevant log output

```shell
mil
```

**Comment by Symbai** [comment]
It is type of `object` https://github.com/dotnet/maui/blob/3269fd0c9f718029505d530cf0643b22d33f9d1e/src/Controls/src/Core/PointerGestureRecognizer.cs#L21

**Comment by cgp1976** [comment]
do you have these issues when you right click go to definition.  bascially I can't compile the project. code snipplet below

var pointerGesture = new PointerGestureRecognizer();
pointerGesture.PointerEnteredCommandParameter; <<<<<< over here, I right click go to definition

**Comment by Symbai** [comment]
Do not rely on where VS brings you. Look at the source code here. I posted the line, its declared as `object`.
