### ISSUE TITLE
[Bug] XamlParseException: "Expected Style but found Microsoft.Maui.Controls.Trigger"

### ISSUE THREAD

**Issue by Zachael** [dotnet/maui#1463]
### Description
XamlParseException: "Expected Style but found Microsoft.Maui.Controls.Trigger" for the Setter under VisualState.Setters tag. The parser doesn't seem to recognize that the setter is in a Style because it finds the Trigger first.

```
<Style TargetType="MyButton">
	<Style.Triggers>
		<Trigger TargetType="MyButton" Property="ButtonType" Value="Primary" >
			<Setter Property="VisualStateManager.VisualStateGroups">
				<VisualStateGroupList>
					<VisualStateGroup x:Name="CommonStates">
						<VisualState x:Name="Normal">
							<VisualState.Setters>
								<Setter Property="TextColor" 
									Value="{DynamicResource MyButton_Primary_TextColorNormal}" />
								<Setter Property="BackgroundColor" 
									Value="{DynamicResource MyButton_Primary_BackgroundColorNormal}" />
							</VisualState.Setters>
						</VisualState>
						<VisualState x:Name="Disabled">
							<VisualState.Setters>
								<Setter Property="TextColor" 
									Value="{DynamicResource MyButton_Primary_TextColorDisabled}" />
								<Setter Property="BackgroundColor" 
									Value="{DynamicResource MyButton_Primary_BackgroundColorDisabled}" />
							</VisualState.Setters>
						</VisualState>
					</VisualStateGroup>
				</VisualStateGroupList>
			</Setter>
		</Trigger>
	</Style.Triggers>
</Style>
```

### Expected Behavior
Expected no exception

### Actual Behavior
XamlParseException: Expected Style but found Microsoft.Maui.Controls.Trigger

### Basic Information

- Version with issue: Maui 6.0.100-preview.5.794
- Last known good version: Xamarin Forms 5.0.0.2012
- IDE: VS Enterprise 2019 Preview Version 16.11.0 Preview 2.0
- Platform Target Frameworks: WinUI3 (ProjectReunion 0.8.0-preview)

### Workaround

No know workaround

**Comment by Zachael** [comment]
This problem did not occur with Maui preview 4.

**Comment by Zachael** [comment]
This problem did not occur with Maui preview 4.

**Comment by jsuarezruiz** [comment]
Tried and no longer occur with Preview 11.

**Comment by jsuarezruiz** [comment]
Feel free to reopen or open a new issue if find anything.
