### ISSUE TITLE
[Android] Navigating event not fired from WebView for data:video links with download attribute presented

### ISSUE THREAD

**Issue by IvanMi773** [dotnet/maui#14636]
### Description

Navigating event not fired from Android WebView for `data:video/`... html links with `download` attribute presented. 

### Steps to Reproduce

1.  Create index.html with the following html tag:
`<a href="data:video/mpeg;base64,MQ==" download="New Text Document.txt">Download file</a>`

2. Add a WebView to some component. Set source
```
<WebView
	Source="wwwroot/index.html"
        x:Name="wvWebApp"
        Navigating="wvWebApp_Navigating"/>
```

3. Create  `wvWebApp_Navigating` function
```
private void wvWebApp_Navigating(System.Object sender, Microsoft.Maui.Controls.WebNavigatingEventArgs e)
{
	Debug.WriteLine(e.Url.ToString());
}
```

4. Run application and click on link. 

### Expected Behavior:
Navigating event should be triggered

### Actual Behavior:
Navigating event is not triggered on Android if link contains download attribute. On IOS works fine. Not tested on other platforms

### Link to public reproduction project repository

https://gitlab.com/IvanMi773/webview-bug-reproduction/-/tree/main

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 13

### Did you find any workaround?

l found two ways how this bug can be avoided:
1. Use the following url in href attribute: `https://test.com/data:video/mpeg;base64,MQ==`
2. Remove `download` attribute

**Comment by drasticactions** [comment]
@IvanMi773 I think this may be a limitation of the Android WebView

https://user-images.githubusercontent.com/898335/232975245-1ee5e22e-2d3e-4d70-af41-d154cab92612.mov

As far as I know, Android WebView's handle navigation events through `ShouldOverrideUrlLoading` on the WebViewClient, which is what MAUI does. When using your reproduction sample, this method never gets called, but does for normal links. Do you have an example that should work?

@jonathanpeppers Do you know if there are other ways to detect navigation links?

**Comment by IvanMi773** [comment]
@drasticactions if you will remove `download` attribute from `a` tag, then it should work.

**Comment by drasticactions** [comment]
But I thought your issue was that it wouldn't send the "navigated" event with that tag present. Is that right?

What I am showing is that, with your original code and that tag present, it doesn't fire "ShouldOverrideUrlLoading" on the underlying Android WebView, meaning Maui's "Navigated" event will never fire because that's necessary for it to work. So this seems like an underlying issue with Android's WebView.

**Comment by IvanMi773** [comment]
Ok, so l think we can close this issue

**Comment by jonathanpeppers** [comment]
> @jonathanpeppers Do you know if there are other ways to detect navigation links?

The best I would know to do here is read Android's docs.

But it does appear that `<a download="..." />` doesn't go through the callback. I'm not sure there is anything we can do in MAUI for this, but you could also test the Android APIs directly in a `dotnet new android` app. If you can get it to work there, that would point to an issue in MAUI to fix.

It sounds like we can close for now? Thanks.
