### ISSUE TITLE
[Android] Optimize the package by removing the unnecessary runtimes when publishing

### ISSUE THREAD

**Issue by danardelean** [dotnet/maui#14646]
### Description

I have tested this behaviour on both Visual Studio for Mac and Visual Studio for Windows. I have only tested it on Android but it might also happen on iOS

When you Archive for publishing an .Net MAUI application in the final aab (apk) you will have the runtimes for x86 and x86-64 which are not needed . The only architecture to be included by default on Archive for publishing should be android-arm64

By dropping all the unnecessary runtimes the package will be smaller

### Public API Changes

Only build for android-arm64 runtime when publishing

### Intended Use-Case

Smaller packages to upload to the store

**Comment by janseris** [comment]
Seems like some of the last devices with x86 and Android were released by Asus in 2014 and by Lenovo in 2016, the former running Android 6 which is capable of running MAUI.
It would be a very useful option to choose to not include these runtimes, that's true.

**Comment by jonpryor** [comment]
@danardelean: to which store are you uploading your app?  If you're uploading to the Google Play Store, then [you should be uploading `.aab` files, *not* `.apk` files](https://developer.android.com/guide/app-bundle):

> From August 2021, new apps are required to publish with the [Android App Bundle](https://developer.android.com/guide/app-bundle) on Google Play.

The benefit to App Bundles (`.aab` files) is that when a customer downloads their app from the Google Play Store, the `.apk` that is downloaded will contain *only* runtime files that their device will run.  If your `.aab` contains both arm64 and x64 runtimes, a customer running an arm64 device will download a `.apk` containing *only* the arm64 runtime, *not* the x64 runtime.

You can explicitly control which runtimes are included in the `.aab` by setting the [`$(RuntimeIdentifiers)` MSBuild property](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#runtimeidentifiers):

```dotnetcli
dotnet build -c Release -f net8.0-android -p:RuntimeIdentifiers=android-arm64
```

will produce a `.aab` file which contains only arm64-v8a runtime files, not x86/x64/etc.

That said, `lib/*/libmonosgen-2.0.so` is not the only "runtime file" of consequence; there are also files such as `assemblies.arm64_v8a.blob` that are included for *all* ABIs, e.g. from #19469:

![unzip output](https://private-user-images.githubusercontent.com/128687574/329943185-c3ab909f-98f3-4bd7-87c5-9b66c664a073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTc2ODIsIm5iZiI6MTcxNjIxNzM4MiwicGF0aCI6Ii8xMjg2ODc1NzQvMzI5OTQzMTg1LWMzYWI5MDlmLTk4ZjMtNGJkNy04N2M1LTliNjZjNjY0YTA3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxNTAzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzBlNjRiOTc5YTAwZTdkNGI0Zjk1MGJlMTQ2MDI4NTc3YmYwMmMxOWQ3N2FiM2M4MzM1ZWQ3NTcwMDE0NDgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._QXhzO1T1jckugvv0a5--OL8jxwmlnPNbRa4GmkR3R0)

.NET for Android in .NET 9 will be further altering how assemblies are packaged, removing the `assemblies*.blob` files.  This will in turn allow *App Store `.apk` downloads* to be smaller, though `.aab` *uploads* will be *larger*.  See also:

  * https://github.com/xamarin/xamarin-android/issues/8168
  * https://github.com/xamarin/xamarin-android/commit/86260ed36dfe1a90c8ed6a2bb1cd0607d637f403
