### ISSUE TITLE
How to implement the bidirectional list/scroll view in Maui

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#14652]
### Discussed in https://github.com/dotnet/maui/discussions/4012

<div type='discussions-op-text'>

<sup>Originally posted by **Sasikumar3595** January 10, 2022</sup>
We are creating the application to show the list of notes, each of the note's view (UI element) is a different size (height) based on its content. We want to start the list from today's date, and we loaded the previous/next notes on async basis.

We needed the scroll view that loads items at top and bottom of scroll view dynamically. 
My requirement is bidirectional (top and bottom) scroll view like flutter: https://pub.dev/packages/bidirectional_listview

**Reference Image:**  
![example](https://user-images.githubusercontent.com/44917578/148728030-65ab6a16-4346-482e-a1b5-3e75c745396f.gif)

Anyone please suggests me to implement the behavior on Maui platform.</div>

**Comment by drasticactions** [comment]
You already have a GitHub discussion about this, which is the appropriate place for this issue.

**Comment by Sasikumar3595** [comment]
@drasticactions 

But I did not get any suggestions or attention there.
