### ISSUE TITLE
Basic Binding Label is not working

### ISSUE THREAD

**Issue by MathewLC** [dotnet/maui#14657]
### Description

Apparently basic binding to a label is not working.

### Steps to Reproduce

Access the sample and run it.
The text will not be changed.

### Link to public reproduction project repository

https://github.com/MathewLC/MAUITest

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android, Windows

### Affected platform versions

Android, Windows

**Comment by MathewLC** [comment]
Actually this scenario it's working. Try to provide a more reproducible example.

**Comment by drasticactions** [comment]
If you can reproduce it, can you try on the newest net7.0 stable release of MAUI?

**Comment by MathewLC** [comment]
Hi, I actually saw that was another unrelated thing because of the binding mode So I'm closing this issue. Sorry for the mistake.
