### ISSUE TITLE
[Enhancement] Add support for FFmpeg

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#1466]
## Summary
I think adding support for FFmpeg (or another framework with similar characteristics) should be an issue to consider for this new .NET MAUI, we are in 2021 and file decoding or encoding is something that many clients demand for their projects, but it is difficult They offer a solution based on Xamarin.Forms mainly because generating linking libraries can be an odyssey when it comes to large libraries and the few open source libraries available are not available for all platforms that Xamarin.Forms supports given the complexity involved in the support of such libraries. on so many platforms. So my suggestion would be that .NET MAUI add support for FFmpeg (or another framework with similar features) on Android, iOS, UWP and macOS officially (official support could be added initially so that in the future the community can maintain it on their own) .
https://www.ffmpeg.org/

**Comment by Redth** [comment]
Sounds interesting, and maybe something better suited for the Community Toolkit.  This is currently not in scope for .NET 6 and not on our roadmap.  We may re-evaluate in future versions of .NET, but closing for now.
