### ISSUE TITLE
Entitlements.plist is not used correctly in Debug configuration

### ISSUE THREAD

**Issue by reinierkops** [dotnet/maui#14662]
### Description

When a custom Entitlements.plist is set in csproj file, this file will not be used, and only a default (templated) Entitlements.plist will be used and generated in the obj folder as Entitlements.xcent.

All the properties set in the custom Entitlements.plist are ignored, and things like NFC access is not working.
The signed .app file has the default (templated) Entitlements file included.

### Steps to Reproduce

1. define a custom Entitlements.plist
2. Run application on physical device
3. see Entitlements.xcent which has not the complete content.
4. Inspect .app file, even no correct entitlements data

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

>= iOS 13

**Comment by ramonB1996** [comment]
This also seems to be the case with 'MacCatalyst'

**Comment by reinierkops** [comment]
Issue was project specific, and fixed by setting the correct TargetFrameworks in depending projects
