### ISSUE TITLE
[Android] ContentView measures content even if its IsVisible is set to False

### ISSUE THREAD

**Issue by dilyantraykov** [dotnet/maui#14683]
### Description

Consider this setup:

```
    <VerticalStackLayout>
        <ContentView BackgroundColor="Blue">
            <ContentView.Content>
                <Button IsVisible="False" />
            </ContentView.Content>
        </ContentView>
    </VerticalStackLayout>
```

On WinUI, iOS, and MacCatalyst, the ContentView does not occupy any space.
On Android, however, the blue background is drawn indicating that space is reserved for the Button.

![image](https://user-images.githubusercontent.com/5472516/233317659-e33acd88-d6e4-4d09-a0fd-87df7174aef8.png)

### Steps to Reproduce

1. Create a new .NET MAUI project.
2. Add the following code to the MainPage:
```
    <VerticalStackLayout>
        <ContentView BackgroundColor="Blue">
            <ContentView.Content>
                <Button IsVisible="False" />
            </ContentView.Content>
        </ContentView>
    </VerticalStackLayout>
```
3. Run the application on Android and notice the blue background reserved for the Button.

### Link to public reproduction project repository

setup is rather simple

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

A possible workaround would be to wrap the Content of the ContentView in a (Vertical)StackLayout.

**Comment by durandt** [comment]
I have been plaged by a similar issue where a ContentView containing a Fixed-height View that becomes invisible (IsVisible = false) will keep its height although it is now "empty". 

```
<Grid RowSpacing="0">
     <Grid.RowDefinitions>
        <RowDefinition Height="*" />
        <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>
    <ContentView Grid.Row="0">
    [...]
    </ContentView>
    <ContentView Grid.Row="1" BackgroundColor="Blue">
        <ContentView HeightRequest="80" x:Name="_InnerContentView">
        </ContentView>
    </ContentView>
</Grid>
[...]
_InnerContentView.IsVisible = false;
```

Grid Row 0 won't expand after `_InnerContentView.IsVisible` is set to `false` and blue background will still be visible

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Android 13.0-API33 and iOS 16.4, not repro on Windows 11 with below Project:
[14683.zip](https://github.com/dotnet/maui/files/12695994/14683.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/6fca9fc2-90e2-4348-a6a6-87c133fc257b)
Android:
![image](https://github.com/dotnet/maui/assets/97647558/c4d06aca-470a-4cbb-abd4-82d90200a250)
iOS:
![image](https://github.com/dotnet/maui/assets/97647558/a35af9dd-0083-4cef-b65b-ee97ba4f40b0)
