### ISSUE TITLE
To can check if location is enabled

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/maui#14682]
### Description

I would like to know if location is enabled or not in an Android device.

My case is that if the user gives permissions to use the location, with the method GetLastKnownLocationAsync() I can get null if it is not possible to get the last location.

One reason could be that there is no GPS signal when the location is enabled.

And another reason could be because the location is disabled in the settings of the device.

I would like to know both cases, because in my case I would like to implment different logic in each case.

Is it possible to know if the location is disabled?

Thanks.

### Public API Changes

Perhaps it could be possible a method like Location.IsEnabled() that returns a bool.

### Intended Use-Case

```
bool isLocationEnabled = Location.IsEnabled();

if(isLocationEnabled == false)
{
    //Ask user to enabled it

    //if user tells no: do Action1();
   //else do nothing, wait user enables location and try again.
}
else
{
    //do Action2();
}
```

**Comment by janseris** [comment]
```
try
{
 GeolocationRequest request = new GeolocationRequest(GeolocationAccuracy.Best, TimeSpan.FromSeconds(LocationRequestTimeoutSeconds));
            _GPSCheckCancelTokenSource = new CancellationTokenSource();

            Location location = await Geolocation.Default.GetLocationAsync(request, _GPSCheckCancelTokenSource.Token);
}

        catch (FeatureNotEnabledException)
        {
            result.Status = GPSResultStatus.GPS_NOT_ENABLED;
            var message = "GPS is not enabled. Please turn on GPS.";
            ShowDismissablePopUp(message);
            Print(message);
            DebugPrint?.Invoke(this, message);
        }
     
```

**Comment by jfversluis** [comment]
The Permissions API should also take into account if something is possible/available or not: https://learn.microsoft.com/dotnet/maui/platform-integration/appmodel/permissions

So I'd say this is already possible to determine.

**Comment by janseris** [comment]
> The Permissions API should also take into account if something is possible/available or not: https://learn.microsoft.com/dotnet/maui/platform-integration/appmodel/permissions
> 
> So I'd say this is already possible to determine.

GPS permission is different than enabled/disabled GPS
