### ISSUE TITLE
Synchronous prompt on CustomScriptDialogOpening WebView2

### ISSUE THREAD

**Issue by OMendozaG** [dotnet/maui#14691]
### Description

I'm developing a MAUI application in C# that implements a WebView2 and I need to change the style of the alert, prompt, and confirm dialogs. In WinUI applications everything is very modern, avoiding synchrony, but apparently only when it suits Microsoft, let me explain: If I do:

```
webView.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
webView.CoreWebView2.ScriptDialogOpening += CustomScriptDialogOpening;
```

I can intercept the default JavaScript dialogs, but even if the CustomScriptDialogOpening function is async, the WebView doesn't await it.

So,

How the heck can I make a prompt if I can't await it, And there's no way to launch the user prompt window synchronously, and if I launch it asynchronously, WebView2 doesn't await it?

I don't know if this has a solution... Thank you!

### Steps to Reproduce

Create MAUI project with windows support.
Add webview.
Set AreDefaultScriptDialogsEnabled = false
add Event on ScriptDialogOpening 

### Link to public reproduction project repository

https://github.com/MicrosoftEdge/WebView2Feedback

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by Eilon** [comment]
Hi @OMendozaG , can you share more code about how you're trying to handle the event? The more info we have, the better we can understand the exact issue you're having. Ideally, a complete app that reproduces the issue posted to a public GitHub repo.

**Comment by OMendozaG** [comment]
Hi Elion,

An example may not make much sense as it is a very simple problem, but I will try to explain it better:

In JavaScript, when you launch a prompt, it runs synchronously, stopping the JavaScript execution thread and returning the user's entered response. This is also applicable to confirm and alert.
Well, in Maui, the PlatformView of the Maui WebView in WindowsUI is WebView2.

If we access this PlatformView and use its "wb.CoreWebView2.ScriptDialogOpening" property, we can add an event listener that returns these prompt, confirm, and alert calls to C# code.

NOTE: To make it work and have the calls returned, you need to disable the default dialog execution with the "wb.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;" property.

Then, if you add a method to handle the events, you will see that we can do (I will give the example of prompt()):

```
wb.CoreWebView2.ScriptDialogOpening += async (CoreWebView2 sender, CoreWebView2ScriptDialogOpeningEventArgs e) => {
	if (e.Kind == CoreWebView2ScriptDialogKind.Prompt) {
		e.ResultText = await DisplayPromptAsync("title", "Question", "Cancel", "OK", "");
		e.Accept();
	}
}};
```

But the method, despite being async, is not awaited by the function that launches it.
If I don't make it async, I can't launch a Prompt to the user because the main thread is busy waiting for the prompt response in the WebView, so it is never processed.

This makes it practically impossible to display a custom Prompt to the user.
If you need more information, I can provide it.

**Comment by Eilon** [comment]
Ah, I'd like to introduce you to my dear friend `GetDeferral()`! For WebView2 (and maybe other things in WinUI?) if you want to do async stuff in an event handler, you have to do the following:

1. Call and save the result of `e.GetDeferral()`
2. Do your async work (e.g. using C# async/await)
3. When done, call `Complete()` on the deferral object you saved

See an example here in the BlazorWebView code that runs on WinUI: https://github.com/dotnet/maui/blob/2b823f8503748f115028e671b4fff9048628c462/src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs#L80-L166

(It's handling a different WebView2 event, but the pattern is exactly the same.)

**Comment by OMendozaG** [comment]
> ¡Ah, me gustaría presentarles a mi querido amigo `GetDeferral()`! Para WebView2 (¿y tal vez otras cosas en WinUI?) Si desea hacer cosas asíncronas en un controlador de eventos, debe hacer lo siguiente:
> 
> 1. Llame y guarde el resultado de`e.GetDeferral()`
> 2. Haga su trabajo asíncrono (por ejemplo, usando C# async/await)
> 3. Cuando haya terminado, invoque `Complete()`el objeto de aplazamiento que guardó
> 
> Vea un ejemplo aquí en el código BlazorWebView que se ejecuta en WinUI:
> 
> https://github.com/dotnet/maui/blob/2b823f8503748f115028e671b4fff9048628c462/src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs#L80-L166
> 
> (Está manejando un evento WebView2 diferente, pero el patrón es exactamente el mismo).

True... 

My mistake due to ignorance.

I didn't know this. It was so easy, and I didn't know how to find the answer. Thank you Eilon. And thank you for the work you do with HybridWebview. 

We had something similar in Xamarin, and your project encouraged us to switch to MAUI. :) 

Thanks again.

**Comment by Eilon** [comment]
You're quite welcome. When I started using WebView2 it was the first time I saw this pattern as well, and was quite surprised by it!
