### ISSUE TITLE
WKUIDelegate.RunJavaScriptTextInputPanel bad implementation

### ISSUE THREAD

**Issue by OMendozaG** [dotnet/maui#14695]
### Description

In the RunJavaScriptTextInputPanel function of the WKUIDelegate, which is used to intercept PROMPTs in a WKWebView, the completionHandler parameter is a System.Action<string>.

This parameter should be nullable, System.Action<string?>, since, in case the prompt is cancelled, the result passed back to Javascript is NULL and not an empty string.

This means that, if you implement your own prompt for WKWebView, you cannot give the option to cancel, since if you return Null:

```
public override void RunJavaScriptTextInputPanel(WebKit.WKWebView webview, string prompt, string defaultValue, WebKit.WKFrameInfo frame, System.Action<string> completionHandler) {
            completionHandler(null);
}
```

It will create an Exception:

```
Loaded assembly: /private/var/containers/Bundle/Application/XXX/System.Runtime.Intrinsics.dll [External]
2023-04-20 22:34:31.443 Xamarin.PreBuilt.iOS[26770:1883143] *** Terminating app due to uncaught exception 'System.ArgumentNullException', reason: 'Value cannot be null. (Parameter 'obj') (System.ArgumentNullException)
```

But yes. The value can be null.

The result of a PROMPT should be able to be null, since the prompt can be either text or null for Javascript. This is how WKWebkit does it by default, as well as all browsers.

### Steps to Reproduce

1. Create a MAUI app with iOS support.
2. Add WKWebview.
3. Implement a custom WKUIDelegate
4. Override RunJavaScriptTextInputPanel
5. Try to reproduce default behavior of prompt on it 
`
public override void RunJavaScriptTextInputPanel(WebKit.WKWebView webview, string prompt, string defaultValue, WebKit.WKFrameInfo frame, System.Action<string> completionHandler) {
			UIAlertController alert = UIAlertController.Create("", prompt, UIAlertControllerStyle.Alert);
			alert.AddTextField(textfield => { textfield.Placeholder = defaultValue; });
			alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, action => completionHandler(alert.TextFields[0].Text)));
			alert.AddAction(UIAlertAction.Create("CANCEL", UIAlertActionStyle.Cancel, action => completionHandler(null)));
}
`

Call a prompt from javascript. Try to cancel prompt: Et voila. Exception. Non nullable actiont but promp has to be nullable because it have cancel button.

Thanks.

### Link to public reproduction project repository

only with this explanation is enougth

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All, I found this problem on xamarin

### Did you find any workaround?

Bad one: Put a custom string like <!NULL!> on your prompt and intercept default javascript prompts to replace it with null if <!NULL!> string is the result.

### Relevant log output

```shell
Loaded assembly: /private/var/containers/Bundle/Application/XXX/System.Runtime.Intrinsics.dll [External]
2023-04-20 22:34:31.443 Xamarin.PreBuilt.iOS[26770:1883143] *** Terminating app due to uncaught exception 'System.ArgumentNullException', reason: 'Value cannot be null. (Parameter 'obj') (System.ArgumentNullException)
at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName)
at ObjCRuntime.Trampolines.NIDActionArity1V64.Invoke(String obj)
at WKUIDelegate.<>c__DisplayClass4_0.<RunJavaScriptTextInputPanel>b__2(UIAlertAction action) in X.cs:line 113
at ObjCRuntime.Trampolines.SDActionArity1V241.Invoke(IntPtr block, NativeHandle obj)
at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
at Program.Main
```

**Comment by filipnavara** [comment]
It has been previously reported [here](https://github.com/xamarin/xamarin-macios/issues/15728) which is the repository where the code is.

**Comment by OMendozaG** [comment]
> It has been previously reported [here](https://github.com/xamarin/xamarin-macios/issues/15728) which is the repository where the code is.

True. Thanks and sorry for repeat 👍
