### ISSUE TITLE
Cursor position is at the beginning of entry/editor

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#14707]
### Description

On Windows and Android (not tested on iOS), when tab navigating through a page with entrys and editors with text bindings, the cursor position initializes at the beginning, and so typing into the fields without moving the cursor would mean text would get added to the beginnings rather than the ends of the fields.

### Steps to Reproduce

1. Pull down https://github.com/rachelkang/recipeSearch
2. Deploy to Windows, Android (not tested on iOS)
3. Navigate to "My Recipes" tab
4. Click on any of the recipes (like the first item, "Korean egg roll")
5. Click on the "Edit" button in the toolbar
6. Use keyboard tab to navigate through the entrys/editors on the screen
7. Notice cursor position

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11, Android 12

**Comment by mattleibow** [comment]
Should it be at the end or should it select the text?
