### ISSUE TITLE
MeasureInvalided of the Parent is not being invoked when a Child invalidates itself

### ISSUE THREAD

**Issue by deyanTerz** [dotnet/maui#14706]
### Description

I am trying to figure out how to get notified when a child in a layout invalidates itself and thus causes the layout to invalidates itself as well. From what I have read, the MeasureInvalidated event does just that, it notifies us when it the view has invalidated itself. In my testing however that is not the case. When a child for instance increases its HeightRequest, the parent does not invoke the MeasureInvalidated event even though the parent does become bigger/smaller along with the child. 

In other words, the child's MeasureInvalidated is invoked but the parent's is not.

### Steps to Reproduce

1. Run the provided app in the linked public repo or through the attachments
2. After the MainPage has loaded, add breakpoints to the methods defined in MyVerticalStackLayout.cs
3. Click the 'Expand' Button in the MainPage

Expected: We hit the breakpoint in NotifyMeasureInvalidated since the MeasureInvalidated event is invoked
Actual: We don't hit any breakpoints 

[MeasureIssueApp.zip](https://github.com/dotnet/maui/files/11296078/MeasureIssueApp.zip)

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/MeasureIssueApp

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 11, Windows SDK 10

### Did you find any workaround?

Attaching an event handler to the child's MeasureInvalidated event seems to fix the issue: ((VisualElement)child).MeasureInvalidated += this.MeasureInvalidatedEventHandler;

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[MeasureIssueApp.zip](https://github.com/dotnet/maui/files/11914006/MeasureIssueApp.zip)

**Comment by PureWeen** [comment]
This should be fixed now on 8.0.92
