### ISSUE TITLE
Windows WebView2 ScriptDialogOpening CoreWebView2ScriptDialogOpeningEventArgsIt not functional

### ISSUE THREAD

**Issue by OMendozaG** [dotnet/maui#14717]
### Description

With CoreWebView2ScriptDialogOpeningEventArgs, you cannot tell it that it has not been intercepted and to finally launch the original, okay, this is not a bug, it is a feature proposal.

What is a bug, though, is that CoreWebView2ScriptDialogOpeningEventArgs has an Accept but no cancel. Therefore, in the case of a Confirm,

```
if (e.Kind == CoreWebView2ScriptDialogKind.Confirm) {
	if (Confirm(e.Message)) {
		e.Accept();
	}
}
```

There is no way for the confirm CoreWebView2ScriptDialogOpeningEventArgs to return FALSE. Because if you not fire Accept, return of confirm( on javascript will be null.

This does not give me the tools to substitute the original behavior of Confirm since it can result in true or false.

Yes, I could do a workaround and intercept the result by JavaScript and if it is === null, transform it to false. But that is not a solution. CoreWebView2ScriptDialogOpeningEventArgs should allow me to substitute the original behavior of the events.

Also, as I said before, I do not understand why it does not have a return property that allows me to launch the default event despite having intercepted it.

### Steps to Reproduce

Create a WebView2
Intercept ScriptDialogOpening
Try to return false on the javascript confirm call.

### Link to public reproduction project repository

not necessary

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

All

**Comment by Eilon** [comment]
This question looks like it is specific to the WebView2 control, and I found the same issue was opened here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3418

So let's use that other issue to track it because it's specific to WebView2 and not .NET MAUI.
