### ISSUE TITLE
[Android] CollectionView scrolling is not smooth and bounces

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#14711]
### Description

CollectionView scrolling is not always consistently smooth. Sometimes, it intermittently bounces back to the place I started dragging from. This seems to happen more often when in horizontal screen orientation, but whether there is an actual correlation is still unclear.

In the video below, I repeatedly swipe on the screen from left to right in an attempt to scroll to previous items in the CollectionVew. At no point do I manually swipe the other way. However, the CollectionView can be seen quickly bouncing back to the position where I'd started dragging from to the end of the CollectionView.

https://user-images.githubusercontent.com/21988533/233676439-2fa28487-a05b-43bd-8b7e-1eaa63330ae8.mp4

### Steps to Reproduce

1. Pull down https://github.com/rachelkang/recipeSearch
2. Deploy to Android physical device
3. Navigate to "My Recipes" tab
4. Scroll to the back of the CollectionView
5. Swipe on the CollectionView from the left to right ends of the screen in an attempt to scroll 
6. Notice a relatively smoothly experience.
7. Rotate phone to horizontal screen orientation.
8. Repeat steps 4-5.
9. Notice an inconsistent scrolling experience.

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by jonathanpeppers** [comment]
@jsuarezruiz what should I be looking for here?

@rachelkang is the problem here performance or something with UI behavior? It seems like some scrolling values are wrong after you rotate the device?

**Comment by etienneCGI** [comment]
I have the same issue but with vertical scrolling
work fine on iOS though.

**Comment by dpjha84** [comment]
I face the exact same issue. Any updates on this?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Not repro on Android platforms with sample project.
https://github.com/rachelkang/recipeSearch
