### ISSUE TITLE
The linker ignores --linkskip attributes.

### ISSUE THREAD

**Issue by gdar91** [dotnet/maui#14719]
### Description

When I try to publish my MAUI iOS App, it has problems with the System.Collections.Immutable assembly (which might be an issue itself). (I use it with SignalR and it crashes with an InvalidOperationException "Unexpected message type: Microsoft.AspNetCore.SignalR.Protocol.StreamBindingFailureMessage").

When I set linker mode to - Don't Link - then it works. But it ignores them if I want to skip just that assembly (System.Collections.Immutable) via the additional mtouch arguments option (--linkskip=System.Collections.Immutable). Finally, I managed to make it work by adding an XML linker configuration file, but the documentation says that the --linkskip argument should be enough.

### Steps to Reproduce

1. In a MAUI project using .NET 7, use any type from the System.Collections.Immutable library (e.g. ImmutableList<>).
2. In iOS build settings use this option for "Additional arguments": --linkskip=System.Collections.Immutable
3. Build the app in release mode.
4. In the build output it will say the action for the assembly System.Collections.Immutable is Link (and not Copy).

### Link to public reproduction project repository

...

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

You can work around it by adding an XML linker configuration file.

**Comment by drasticactions** [comment]
What happens if you try this with a dotnet iOS app ('dotnet new ios') that doesn't use MAUI?

**Comment by drasticactions** [comment]
CC @rolfbjarne, would you know what's happening here?

**Comment by rolfbjarne** [comment]
> but the documentation says that the --linkskip argument should be enough.

Where did you read this?

It seems that's incorrect, --linkskip doesn't work anymore.
