### ISSUE TITLE
MAUI iOS - None of the input catalogs contained a matching stickers icon set or app icon set named "appicon"

### ISSUE THREAD

**Issue by aboulinguez** [dotnet/maui#14721]
### Description

During the build of my MAUI app project (before running it on iOS) I got this error :

None of the input catalogs contained a matching stickers icon set or app icon set named  "appicon".
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.1024\tools\msbuild\iOS\Xamarin.Shared.targets

In my .csproj :

```
<ItemGroup>
	<None Remove="Resources\AppIcon\icon.svg" />
</ItemGroup>

<ItemGroup>
	<MauiIcon Include="Resources\AppIcon\icon.svg" />
</ItemGroup>
```

The fact is before that, I was not able to change my app icon and splashcreen by replacing the default files given in the MAUI app project template. I got this error when I try to use a new icon file instead of the default one that I have deleted from the project.

### Steps to Reproduce

> Create a new MAUI app project

> Delete both "appicon.svg" and "appiconfg.svg" files from the project.

> Add a new svg file to be the new icon.

> Set this new file build action to MauiIcon

> Try to run the project on a physical iOS device

### Link to public reproduction project repository

https://bitbucket.org/aboulinguez/issuemaui_2023-04-22

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

VS 17.5.33516.290 ; maui-ios 7.0.59/7.0.100 ; ios 16.2.1024/7.0.100

### Did you find any workaround?

No workaround found

**Comment by n3oea** [comment]
I too have this issue.  I can run/debug on Android devices and the emulator, but nothing works when targeting iOS.

**Comment by Howellpeebles** [comment]
Same here.  I'm ready to publish, but can't until this is resolved.

**Comment by Jake-Derrick** [comment]
In the info.plist you have
```
<key>XSAppIconAssets</key>
<string>Assets.xcassets/appicon.appiconset</string>
```
The AppIcon file name is **icon**.svg

What worked for me was making sure those name matched, ex rename the svg to appicon.svg or in info.plist to icon.appiconset

**Comment by ChrisAllisonMalta** [comment]
I had the same problem what fixed it for me was renaming my icon file from "orpheus_icon.png" to "orpheus.png" and changing this line in the info.plist to <string>Assets.xcassets/orpheus.appiconset</string>

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Not repro on iOS platforms.
As **Jake-Derrick** said, you need to right-click info.plist to open it in XML (Text) Editor mode, and edit the appicon.appiconset name to be consistent with the name of the svg image you added.
![Screenshot 2024-01-09 174146](https://github.com/dotnet/maui/assets/77434865/19644ead-3ba4-4722-866c-8a481622eb49)
