### ISSUE TITLE
Can't customize Entry Controls with XAML

### ISSUE THREAD

**Issue by myebstudios** [dotnet/maui#14723]
Is there any way to customize Entry Controls?
If not, is it coming soon?

**Comment by jfversluis** [comment]
Hi @myebstudios for more how-to questions please refer to a medium like [StackOverflow](https://stackoverflow.com/questions/tagged/maui) or the Discussions tab.

In our docs we have a section about customizing controls, maybe that helps answer your question: https://learn.microsoft.com/dotnet/maui/user-interface/handlers/customize
