### ISSUE TITLE
FontImageSource blurry on IOS in button and imagebutton

### ISSUE THREAD

**Issue by FM1973** [dotnet/maui#14728]
### Description

When I use a FontImageSource for a button or an imagebutton the icon is blurry on ios.
Using the same FontImageSource in an image is rendered correctly.

### Steps to Reproduce

1. Start the app
2. Click on button "Icons"

### Link to public reproduction project repository

https://github.com/FM1973/RefreshGridRepo.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ISO 14+

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on iOS 16.4 with below Project:
[RefreshGridRepo.zip](https://github.com/dotnet/maui/files/11935495/RefreshGridRepo.zip)

![image](https://github.com/dotnet/maui/assets/97647558/b5a6e359-271e-4cc7-a674-53381e1908b0)

**Comment by borrmann** [comment]
#6043 there is also this issue which is triaged, hopefully the solution will fix both the shell and buttons?
