### ISSUE TITLE
Safari browser development tools does not work for Blazor Hybrid 16.4 IOS/Mac Catalyst App

### ISSUE THREAD

**Issue by v-Lily** [dotnet/maui#14736]
### Description

1. .NET 7.0.300
2. Xcode 14.3 
3. IOS Simulator 16.4
4. M1 Mac mini, Inter Mac mini
5. MacOS Ventura 13.3.1

### Steps to Reproduce

1.  Install the .NET 7.0 SDK.
1.  Download the rollback.json file from [here](https://maui.blob.core.windows.net/dogfooding/7.0.1xx-sr3/rollback.json).
1. Download the NuGet.Config file from [here](https://maui.blob.core.windows.net/dogfooding/7.0.1xx-sr3/NuGet.Config).
1. The download NuGet.Config file need to add the below internal feed.
```
https://pkgs.dev.azure.com/dnceng/internal/_packaging/7.0.300-rtm.23215.13-shipping/nuget/v3/index.json
https://pkgs.dev.azure.com/dnceng/internal/_packaging/6.0.409-servicing.23215.9-shipping/nuget/v3/index.json
```
6. Place the NuGet.Config and rollback.json files in the same directory (make sure there's no global.json file in the directory or directory tree above).
7. Open a terminal and cd into the directory with the NuGet.Config and rollback.json files.
8. Run the workload install command:
`sudo dotnet workload install maui ios maccatalyst android macos tvos --from-rollback-file ./rollback.json`
9. Run the workload to Update the Maui version:
` dotnet workload update`
10. Create Maui project:
```
mkdir maui_from_mac && cd maui_from_mac
dotnet new maui-blazor -o maui-blazor-cti
cd maui-blazor-cti
```
11. Run the project & ensure you see the application.
`dotnet build -t:Run -f net7.0-ios`

1. The error is as shown below：
![image](https://user-images.githubusercontent.com/83056958/233952569-7d3a8c55-08ac-4cac-8a08-984673dbd4c2.png)

### Link to public reproduction project repository

No

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

iOS, macOS

### Affected platform versions

MacOS SDK 7.0.300

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by Eilon** [comment]
This should work starting in .NET 8. See duplicate issue #14590
