### ISSUE TITLE
StackLayout HorizontalOptions & VerticalOptions do nothing.

### ISSUE THREAD

**Issue by LWGShane** [dotnet/maui#14749]
It wasn't until I read the post below when I found out why my StackView wasn't centering the views on screen when I applied [HorizontalOptions="Center"]. I fully agree with @srqdevg that they need to be removed or at least have a compiler warning stating that they'll do nothing. 

------

I would disagree with closing this because there is a difference between the behavior of HorizontalOptions and VerticalOptions when the orientation is changed. Just because Xamarin did it one way, does not mean it is correct as evidenced by the removal of the AndExpand options. The stacking direction of a layout should only affect the inner contents not the position of the control.  If I replace the inner stacklayout with a listview and center the listview, it displays the items vertically stacked in the center of the screen, so effectively a stacklayout of vertically orientated items centered on screen.  I know I will lose this discussion so can we at least put some kind of compiler warning / error stating that because of oritentation, then option y (either horizontaloption or verticaloption) will be ignored. To help anyone new to XAML to understand why specifying an option has no effect.

_Originally posted by @srqdevg in https://github.com/dotnet/maui/issues/9927#issuecomment-1240906460_

**Comment by hartez** [comment]
This behavior is as-designed and is [documented](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/stacklayout?view=net-maui-7.0#position-and-size-of-child-views).
