### ISSUE TITLE
Setting CollectionView.ItemSizingStrategy to MeasureFirstItem causes StackLayout to not respond to content having IsVisible set to false

### ISSUE THREAD

**Issue by sjordanGSS** [dotnet/maui#14746]
### Description

With the following XAML:
```
    <ContentPage.Resources>
        <x:Boolean x:Key="show-label">True</x:Boolean>
    </ContentPage.Resources>

    <CollectionView x:Name="collection"
                    ItemSizingStrategy="MeasureFirstItem">
        <CollectionView.ItemsLayout>
            <GridItemsLayout Orientation="Horizontal" />
        </CollectionView.ItemsLayout>

        <CollectionView.ItemTemplate>
            <DataTemplate x:DataType="x:Object">
                <VerticalStackLayout>
                    <Label Text="This Label should turn invisible"
                        IsVisible="{DynamicResource show-label}"/>
                    <Label Text="This label should move up to fill the space" />
                </VerticalStackLayout>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
```
Setting the resource "show-label" to false causes the label contained within the item template of the collectionview to disappear as is expected. However, the label below it does not move up as expected on instances after the first when ItemSizingStrategy is set to MeasureFirstItem. Note that setting ItemSizingStrategy to MeasureAllItems causes the second label to move up as expected.

The effect is different on items that created after the value of "show-label" has been changed: in this case, the second label appears at the top, and toggling "show-label" to false causes nothing to happen: the first label remains hidden, the second label doesn't move.

### Steps to Reproduce

1: Run the linked repro project
2: Tap the button marked "Tap to make the label invisible"

### Link to public reproduction project repository

https://github.com/sjordanGSS/ColViewStackIsVisible

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Only tested on Android 11

### Did you find any workaround?

Overriding ItemContentView.OnMeasure to measure the content with the passed width and height seems to fix the issue. However, I think this may just be nullifying the point of MeasureFirstItem as every item will get remeasured now. 
Edited to add: I've done some profiling with a custom control based on StructuredItemsView that is very similar to a CollectionView with MeasureFirstItem set, and adding a call to Content.VirtualView.Measure does seem to undo a lot of the performance gain from using this mode.

**Comment by taublast** [comment]
This is discussable if this can be considered a bug, just would say it's by design. 
When measuring first item the invisible child was obviously skipped. When other cells use same measurement they obviously have this child size as 0 even if it should be visible with another context, otherwise that would not be "measure first item" but "measure all items", theses two strategies have totally different execution time.
Maybe use another strategy more suitable for this case.

**Comment by taublast** [comment]
The issue states clearly Android and we got а "no repro on Windows"?
