### ISSUE TITLE
[Bug] .AAR/.JAR Binding works on Compile but doesn't work on Runtime

### ISSUE THREAD

**Issue by vfongmala** [dotnet/maui#1475]
### Steps to Reproduce

1. Add .jar/.aar reference in project
```
<ItemGroup Condition="$(TargetFramework.Contains('-android'))">
	<EmbeddedJar Include="..\Lib\Android\myjavalib.jar" />
</ItemGroup>
```
2. Build project. Now it can reference in src/Android/MainActivity.cs
3. Run project on device or emulator

### Expected Behavior
Should be able to reference to class as in compile time

### Actual Behavior
Couldn't run an application
```
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.demo/crc6466b141205c78a362.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.company.mylibrary.NativeLibrary" on path: DexPathList[[zip file "/data/app/~~2DGjK-ivAqIgR-5CJwLUlQ==/com.company.demo-dgKJQbH-orf7bno40PgR9w==/base.apk"],nativeLibraryDirectories=[/data/app/~~2DGjK-ivAqIgR-5CJwLUlQ==/com.company.demo-dgKJQbH-orf7bno40PgR9w==/lib/arm64, /data/app/~~2DGjK-ivAqIgR-5CJwLUlQ==/com.compant.demo-dgKJQbH-orf7bno40PgR9w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
```
Classes in .jar/.aar also not included in class.dex in .apk file

### Basic Information

- Version with issue: 6.0.100-preview.5.21302.13
- Last known good version: -
- IDE: Visual Studio Code on Mac
- Platform Target Frameworks: 
  - Android: android-25
- Affected Devices: Android device

**Comment by Redth** [comment]
@jonathanpeppers can't transfer this between orgs, but does this look familiar?

**Comment by jonathanpeppers** [comment]
@vfongmala can you try using the new `AndroidLibrary` item group? Documented here:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetEmbeddedResources.md#msbuild-item-groups

I don't think `EmbeddedJar` would do what you're looking for in an app project. We wanted to make `AndroidLibrary`, so no one has to learn the 17 item group names anymore.

If it still doesn't work, can you try `dotnet build -bl` on your project and share the `msbuild.binlog` file here?

**Comment by vfongmala** [comment]
@jonathanpeppers Hi, thanks for helping me out on this.
Here's the progress.

When I tried to use `AndroidLibrary` with my `.aar` file.
It can be built (without using) and library's classes is included in `classes.dex`
BUT when I `using <package>` then it cannot refer to the class while building.

I have to have both `AndroidLibrary` and `LibraryProjectZip` for the same `.aar` file to make it possible to build and run.

**Comment by jonathanpeppers** [comment]
You shouldn't need to do this, it seems like it's missing the C# binding unless you add `LibraryProjectZip`.

If you add `Bind="true"`, to your `AndroidLibrary` does that also solve the issue?

**Comment by jonathanpeppers** [comment]
This should hopefully be fixed by: https://github.com/xamarin/xamarin-android/pull/6056

**Comment by vfongmala** [comment]
@jonathanpeppers So this will be included in next MAUI preview version right?

**Comment by jonathanpeppers** [comment]
This fix will be in .NET 6 Preview 6. It's not really part of MAUI, but the Android workload it depends on.
