### ISSUE TITLE
Crashing on Startup in Release on Physical Devices

### ISSUE THREAD

**Issue by TheMattWalker** [dotnet/maui#14750]
I am still getting the crash similar to #8928.

I have had to turn AOT off for Android using the following:

```
<PropertyGroup Condition="$(TargetFramework.Contains('-android')) and $(Configuration)=='Release'">
		<AndroidLinkResources>true</AndroidLinkResources>
		<AndroidLinkMode>None</AndroidLinkMode>
		<RunAOTCompilation>false</RunAOTCompilation>
		<AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
</PropertyGroup>
```

I am able to workaround the issue on iOS by using:

```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and $(Configuration)=='Release'">
		<MtouchLink>None</MtouchLink>
</PropertyGroup>
```

It seems to be related to AOT compilation. I also have noticed that there are many .so files missing from my .apk when compared to obj\Release\net7.0-android\android-x\aot\
**Update**: I have explicitly added dummy code to reference the missing dlls in MauiProgram.cs and the .so files are now showing up in the .apk so there seems to also be an issue with Android picking up all the dependencies. However, I'm still getting the crash and have posted the pertinent log information below.

I am using multiple .NET MAUI Class Libraries as PackageReferences from a private feed. Could there be an issue with AOT and .NET MAUI Class Library references?

This is absolutely ridiculous MAUI released with such a massive issue. I don't even know how #8928 was even closed with this being an issue still and how is no one else running into this?

Also turning AOT off should not be an acceptable workaround. I need AOT working on both Android and iOS.

Using .NET 7.0 with Visual Studio 17.5.4

**Comment by Eilon** [comment]
@jonathanpeppers - should I transfer to the xamarin-android repo?

**Comment by jonathanpeppers** [comment]
@TheMattWalker can you share a log of the crash as mentioned here (https://github.com/dotnet/maui/issues/8928#issuecomment-1438648330), or can you share a sample project that has the same issue?

We will probably need to move this to dotnet/runtime, so the Mono team can look into this.

**Comment by TheMattWalker** [comment]
Looks like this person is getting the same issue but there was no response as he posted after the issue was closed.
https://github.com/dotnet/maui/issues/8337#issuecomment-1349871117

**Comment by jonathanpeppers** [comment]
@TheMattWalker the error message above means the AOT images don't match the .dll files in your app.

Given that you run into the same problem with both iOS and Android, are you doing anything custom in the build? Using something that rewrites assemblies? Something like [Fody](https://github.com/Fody/Fody)?

Do you have the same issue in a `dotnet new maui` project?

**Comment by TheMattWalker** [comment]
> @TheMattWalker the error message above means the AOT images don't match the .dll files in your app.
> 
> Given that you run into the same problem with both iOS and Android, are you doing anything custom in the build? Using something that rewrites assemblies? Something like [Fody](https://github.com/Fody/Fody)?
> 
> Do you have the same issue in a `dotnet new maui` project?

Not doing anything custom in the build just using Visual Studio to build it. I have also tried "dotnet publish -c Release -f net7.0-android" to build it and it has same results.

**Comment by jonathanpeppers** [comment]
Do you have the same issue in a `dotnet new maui` project?

**Comment by TheMattWalker** [comment]
No.
However, all I have to do is add this to MauiProgram.cs:

`builder.UseMauiCompatibility();`

and the crash will occur  in a `dotnet new maui` project

![image](https://user-images.githubusercontent.com/12226257/234689017-be83b4af-d20e-459e-9810-6e9cba8362e3.png)


> Do you have the same issue in a `dotnet new maui` project?

No.
However, all I have to do is add this to MauiProgram.cs:

`builder.UseMauiCompatibility();`

and the crash will occur  in a `dotnet new maui` project

![image](https://user-images.githubusercontent.com/12226257/234689017-be83b4af-d20e-459e-9810-6e9cba8362e3.png)

**Comment by jonathanpeppers** [comment]
Thanks, I'll try this myself this afternoon. What if you exclude this assembly from trimming?

```xml
<ItemGroup>
  <TrimmerRootAssembly Include="Microsoft.Maui.Controls.Compatibility" />
</ItemGroup>
```

https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#root-assemblies

**Comment by TheMattWalker** [comment]
> Thanks, I'll try this myself this afternoon. What if you exclude this assembly from trimming?
> 
> ```
> <ItemGroup>
>   <TrimmerRootAssembly Include="Microsoft.Maui.Controls.Compatibility" />
> </ItemGroup>
> ```
> 
> https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#root-assemblies

That did seem to fix it for the `dotnet new maui` project. 

However still a bit confused as to what is going on. I have another project that was not getting it and compared the csproj files and noticed the one that was getting this issue had 
```
</PropertyGroup>
        <DefaultLanguage>en</DefaultLanguage>
        <Platforms>AnyCPU;x86</Platforms>
</PropertyGroup>
```

So I removed it and no longer getting this Microsoft.Maui.Controls.Compatibility issue. 
However, the `dotnet new maui` project I created as a test didn't have that and I was able to simply add the `builder.UseMauiCompatibility();` to reproduce it. So now 2 of my real projects have `builder.UseMauiCompatibility();` and no longer getting the Microsoft.Maui.Controls.Compatibility issue in either one. 

So not really sure now how to reproduce this Microsoft.Maui.Controls.Compatibility issue. 


New Issue: (Should I create a new Issue for this?)

I am running into a crash at startup only on Release still on one of my projects but seems to be another issue. 
I have 2 MAUI projects both referencing a .NET MAUI Class Library, one is referencing the class library as a PackageReference the other is referencing it as a ProjectReference.

In my class library I'm using a ResourceDictionary with this in 2 area:
`<Setter.Value>
                <OnPlatform x:TypeArguments="x:Boolean">
                    <On Platform="iOS,Android" Value="True"/>
                </OnPlatform>
</Setter.Value>`

The MAUI project referencing the MAUI Class Library as PackageReference is getting the following exception only in Release. If I remove the 2 setters using "x:Boolean" I no longer get the following exception and can finally get a working Release build in Android for my project. I also do not get the exception in the project that references the class library as ProjectReference in Release.

04-26 17:12:38.194 23686 23686 I MonoDroid: android.runtime.JavaProxyThrowable: Microsoft.Maui.Controls.Xaml.XamlParseException: Position 935:18. Type Boolean not found in xmlns http://schemas.microsoft.com/winfx/2009/xaml
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.CreateValuesVisitor.Visit(ElementNode node, INode parentNode)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[StyleResources](StyleResources view, Type callingType)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at MyClassLibrary.GlobalResources.StyleResources.InitializeComponent()
04-26 17:12:38.194 23686 23686 I MonoDroid:    at MyClassLibrary.GlobalResources.StyleResources..ctor(ResourceDictionary colorResources)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at MyClassLibrary.Themes.Default.DefaultThemeResources..ctor()
04-26 17:12:38.194 23686 23686 I MonoDroid:    at MyClassLibrary.ApplyTheme(Theme theme)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at MyClassLibrary.set_CurrentTheme(Theme value)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at MyClassLibrary.Init(Theme startingTheme)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at MyMauiApp..ctor()
04-26 17:12:38.194 23686 23686 I MonoDroid:    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite , RuntimeResolverContext )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type , Func`2 )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Microsoft.Maui.MauiApplication.OnCreate()
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Android.App.Application.n_OnCreate(IntPtr , IntPtr )
04-26 17:12:38.194 23686 23686 I MonoDroid:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7632)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at android.os.Looper.loopOnce(Looper.java:226)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at android.os.Looper.loop(Looper.java:313)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at android.app.ActivityThread.main(ActivityThread.java:8775)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at java.lang.reflect.Method.invoke(Native Method)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
04-26 17:12:38.194 23686 23686 I MonoDroid: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by jonathanpeppers** [comment]
I’d file a new issue for the second problem, a sample project would help. It may be related to: https://github.com/dotnet/maui/pull/14546

**Comment by TheMattWalker** [comment]
> I’d file a new issue for the second problem, a sample project would help. It may be related to: #14546

Thanks for the help!

I have created a new issue here https://github.com/dotnet/maui/issues/14790

**Comment by TheMattWalker** [comment]
Closing this issue as I'm not sure exactly how to reproduce and no longer getting it.
