### ISSUE TITLE
Linear Gradients constantly have a grey hue in .net Maui on iOS

### ISSUE THREAD

**Issue by BECInc** [dotnet/maui#14766]
### Description

Setting a gradient brush causes a persistent grey hue to be present in the view where the brush is set to the background (see image).
![Simulator Screen Shot - iPad (9th generation) - 2023-04-25 at 11 53 53](https://user-images.githubusercontent.com/6816815/234255903-af938dd8-e5ce-4575-b0c3-c44fe931f91b.png)

### Steps to Reproduce

I started a basic sample project with this as the following code as the MainPage (no other changes to the project).  I've also tried commenting out all the default styles and colors, but that doesn't seem to change anything either.   This occurs on iPads running in release mode and debug mode, and in the simulator.

```cs
public class MainPage : ContentPage
{
	public MainPage()
	{
        var contentGrid = new Grid
        {
            HorizontalOptions = LayoutOptions.Center,
            VerticalOptions = LayoutOptions.Center,
            BackgroundColor = Colors.WhiteSmoke,
            WidthRequest = 500,
            HeightRequest = 500,
            RowDefinitions =
            {
                new RowDefinition { Height = GridLength.Star },
                new RowDefinition { Height = 100 }
            }
        };

        var boxView = new BoxView
        {
            HorizontalOptions = LayoutOptions.Fill,
            VerticalOptions = LayoutOptions.Fill,
            Color = Colors.Transparent,
            Background = new LinearGradientBrush
            {
                StartPoint = new Point(0, 0),
                EndPoint = new Point(0, 1),
                GradientStops = new GradientStopCollection
                {
                    new(Colors.Transparent, 0.1f),
                    new(Colors.White, 1f)
                }
            }
        };

        contentGrid.Add(boxView, 0, 1);

        Content = new Grid
        {
            HorizontalOptions = LayoutOptions.Fill,
            VerticalOptions = LayoutOptions.Fill,

            Children =
            {
                contentGrid
            }
        };
	}
}
```

### Link to public reproduction project repository

https://github.com/BECInc/LinearGradientSample

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

**Comment by mattleibow** [comment]
OK, I see this on Windows too. And it is maybe important to note that the gradient is from White to transparent, so there should be nothing visible actually. Seems to be some issue with the alpha calculations.

**Comment by jsuarezruiz** [comment]
@mattleibow Have done a quick tests and, seems correct on Windows:
![image](https://user-images.githubusercontent.com/6755973/234817146-1ba06120-8bae-4ff3-bcdc-ff52bb51c334.png)

Did you tried with a specific View (I used the BoxView)?

**Comment by mattleibow** [comment]
Did you try the code above? I am sure I saw it on main... Maybe I was mistaken and was using something else... Maybe the net7 branch. So scary now.

**Comment by mattleibow** [comment]
Ah, this happens on iOS.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on iOS 16.4 with below Project:
[transparentgradient.zip](https://github.com/dotnet/maui/files/11945740/transparentgradient.zip)
