### ISSUE TITLE
iOS Binding Does Nothing

### ISSUE THREAD

**Issue by Tazzi3** [dotnet/maui#14775]
### Description

I can successfully get an iOS Objective-C library (.a file) to bind following the Xamarin binding tutorial found here: https://learn.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-c-libraries.
I also used the library that the tutorial recommended to follow which is located here:  https://github.com/xamarin/ios-samples/tree/master/BindingSample

Now I am trying to do the same for MAUI. When selecting a MAUI iOS binding library, adding the ios static library, and copying in the same code, it says it compiled but it has not actually done anything. The dll produced has no functions present when decompiling and checking it. Its almost like VS does not recognize that it is a binding library setup and basically does nothing.

Things I have tried for a fix:
1) Creating a new MAUI ios binding template using the dotnet commands in powershell
2) Downloading a MAUI ios binding example and trying to compile that directly such as: https://github.com/drasticactions/WebP.Touch/tree/net6-port/WebP.Touch
3) Changing from a .netcore 7 to .netcore6 project which fails too.

Am I missing something critical for MAUI template to work in comparison to how XAMARIN does it?

### Steps to Reproduce

1. Create new MAUI iOS Binding Library in Visual Studio 22
2. Load in a native iOS library (.a) and add any exports to the code
3. Compile and then decompile DLL to see now functions available

### Link to public reproduction project repository

https://github.com/Tazzi3/MAUI-ObjC-Binding

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

all iOS

### Did you find any workaround?

No work around.

**Comment by drasticactions** [comment]
A few things:

1. I think this issue may be better suited for https://github.com/xamarin/xamarin-macios, as it has to do with the Mac/iOS SDK and not MAUI (The UI Framework), which is what this repo is for.
2. Pulling down your code, the errors being returned are correct:

- It's complaining that it can't find things like NSString and Export, because you need to include the namespaces for them.

```
using System;

using UIKit;
using Foundation;
using ObjCRuntime;
```

- After adding that, it's complaining you don't have `XMGreeting`, which is not included in your binding. You would need to include that.
- There's also an error with the `[Model(AutoGeneratedName = true)]` for XMCustomViewDelegate, remove AutoGeneratedName and it should work.,

```
// @protocol XMCustomViewDelegate<NSObject>
    [Protocol]
    [Model]
    [BaseType(typeof(NSObject))]
    interface XMCustomViewDelegate
```

I pulled down my repo that you listed, built it with no errors and it worked fine when I referenced the output in another project.

The only other thing I can think of is that you can't directly reference binding projects with other projects. If you're trying to, for example, reference a binding project with your MAUI app, that won't work. You would need to reference the output DLLs of the binding (or create a Nuget package and reference that) and then it should work.

@rolfbjarne Am I correct? Does this sound right?

**Comment by rolfbjarne** [comment]
> The only other thing I can think of is that you can't directly reference binding projects with other projects. If you're trying to, for example, reference a binding project with your MAUI app, that won't work. You would need to reference the output DLLs of the binding (or create a Nuget package and reference that) and then it should work.

You can reference a binding project from another project, it'll kind of work. The IDE will tell you that there's a problem (red squiggly lines when trying to use anything from the binding project), but if you try to build, it'll build just fine (this is a known issue). That said, just referencing the output dll makes the IDE happy as well, so most people do that.

Otherwise everything else is correct.

**Comment by Tazzi3** [comment]
Thanks for the responses guys!

@drasticactions  I do not get any errors at all when I compile. I added those namespaces and still get no errors, infact, I can absolutely trash the entire ApiDefinition file with random errors and changes and it still claims to compile fine. What version of VS are you using and the dot net version installed? (I have listed mine at the bottom of this comment).

Also thankyou for pointing out the XMGreeting enum, that is suppose to be in the StructsAndEnums class. But that is also a perfect example of the project compiling without any problems when clearly it should be failing to compile.

Do note that if I create a Xamarin Binding project, it will compile and I can then reference the xamarin DLL in a xamarin project.
But this does not work for MAUI binding project, I get the previously mentioned issues.

To verify this is not a problem on just my computer. I have just done a fresh install of Visual Studio 2022 community on a laptop, and I get the exact same behaviour.

The installed version I am running on both computers is:
 ```
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.5.4

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.81/7.0.100         VS 17.5.33530.505
maui-maccatalyst           7.0.81/7.0.100         VS 17.5.33530.505
maccatalyst                16.2.2035/7.0.100      VS 17.5.33530.505
maui-ios                   7.0.81/7.0.100         VS 17.5.33530.505
ios                        16.2.2035/7.0.100      VS 17.5.33530.505
maui-android               7.0.81/7.0.100         VS 17.5.33530.505
android                    33.0.46/7.0.100        VS 17.5.33530.505
```

**Comment by drasticactions** [comment]
I'm doing this on my Mac, I haven't tried to build and reference a Binding project on Windows. 

In any case, this issue wouldn't be one for the this Repo: It's unrelated to the MAUI UI Framework. This sounds like a tooling issue on Windows, so I would file an issue there and see.

**Comment by rolfbjarne** [comment]
Ah, I didn't notice that this happens on Windows.

At the moment, building a binding project on Windows requires having a connection to a remote Mac (see also https://github.com/xamarin/xamarin-macios/issues/16244).

**Comment by Tazzi3** [comment]
I will try again on the MAC and report back!

**Comment by Tazzi3** [comment]
@drasticactions  @rolfbjarne  We have had success with compiling in MAC Visual Studio. I can then confirm that the desired functions are displaying in the DLL when decompiling it.

When I copy the DLL over to Windows Visual Studio and attempt to use it in a MAUI application, I get the following error:
`Error CS0012	The type 'NSObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.iOS, Version=16.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

When looking at the Microsoft.iOS version in my MAC visual studio, it shows it is using Microsoft.iOS v16.2.46
Whereas the version in my Windows visual studio shows it is using v16.2.34

Is it possible to manually update the version? Or can I copy the DLL from the windows version onto the MAC to make them the same?
`

**Comment by rolfbjarne** [comment]
> When I copy the DLL over to Windows Visual Studio and attempt to use it in a MAUI application, I get the following error:
> `Error CS0012 The type 'NSObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.iOS, Version=16.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

Can you get a binary build log (binlog) as described here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs?

**Comment by Tazzi3** [comment]
> Can you get a binary build log (binlog) as described here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs?

Yes I can get that today. But I am getting the same issue as this person: https://github.com/xamarin/xamarin-macios/issues/17418

The Microsoft.iOS SDK used between MAC and Windows Visual Studio is different. I have tried completely uninstalling and reinstalling Visual Studio 22 on both machines at the same time and they still use two different versions.

I can see there are newer versions of the SDK which can be seen on the nuget link: https://www.nuget.org/packages/Microsoft.iOS.Windows.Sdk/

But trying to install these results in the same error that the previous person got which was: 
The package Microsoft.iOS.Sdk 16.2.46 has a package type DotnetPlatform that is incompatible with this project.

I did try a variety of different versions as well, but the v16.2.46 is the version that matches the MAC VS install.

**Comment by rolfbjarne** [comment]
Marking as need info: https://github.com/dotnet/maui/issues/14775#issuecomment-1532764952

**Comment by dynatom** [comment]
Same issue, iOS binding api definition not working.

Android binding just copy jar frome Xamarin Android binding will be success, AndroidBinding project compile success, and add it to maui project's <ProjectReference>, it can use api in jar file.

In iOS binding, copy all .a files and ApiDefinition.cs/StructsAndEnums.cs files, the iOSBinding project can compile success, but add it to maui project's <ProjectReference>, it can't find any api which was defined in ApiDefinition.cs.


Add .a/.framework to iOSBinding project is like the following：
```
  <ItemGroup>
    <NativeReference Include="libTestiOS.a">
      <Kind>Static</Kind>
      <ForceLoad>True</ForceLoad>
    </NativeReference>
    <NativeReference Include="TestiOS2.framework">
      <Kind>Framework</Kind>
      <Frameworks></Frameworks>
      <LinkerFlags></LinkerFlags>
      <WeakFrameworks></WeakFrameworks>
      <ForceLoad>True</ForceLoad>
      <NeedsGccExceptionHandling>False</NeedsGccExceptionHandling>
      <IsCxx>False</IsCxx>
      <SmartLink>False</SmartLink>
    </NativeReference>
  </ItemGroup>
```

**Comment by rolfbjarne** [comment]
> In iOS binding, copy all .a files and ApiDefinition.cs/StructsAndEnums.cs files, the iOSBinding project can compile success, but add it to iOS maui project (`<ProjectReference Include="..\iOS_BindingLibrary\iOS_BindingLibrary.csproj" />`), it can't find any api which was defined in ApiDefinition.cs.

There's a known issue where intellisense in the IDE won't work, but the build will actually succeed. Can you try building the project and see if that works? One workaround is to reference the binding assembly directly instead of the binding project, in which case intellisense will work as expected.

**Comment by dynatom** [comment]
> > In iOS binding, copy all .a files and ApiDefinition.cs/StructsAndEnums.cs files, the iOSBinding project can compile success, but add it to iOS maui project (`<ProjectReference Include="..\iOS_BindingLibrary\iOS_BindingLibrary.csproj" />`), it can't find any api which was defined in ApiDefinition.cs.
> 
> There's a known issue where intellisense in the IDE won't work, but the build will actually succeed. Can you try building the project and see if that works? One workaround is to reference the binding assembly directly instead of the binding project, in which case intellisense will work as expected.

Thanks, it build success and work correctly with wrong intellisense.
[Binding project: ApiDefinition.cs](https://i.imgur.com/3bpT3mA.png)
[MAUI project: Platforms\iOS\Program.cs](https://i.imgur.com/hqv2u9d.png)



The test lib files and define are these:
TestiOS.h
```Objective-C
#ifndef TestiOS_h
#define TestiOS_h

#import <Foundation/Foundation.h>

@interface TestiOS : NSObject
- (int) add:(int)a b:(int)b;
@end
#endif /* TestiOS_h */
```
TestiOS.m
```Objective-C
#import "TestiOS.h"

@implementation TestiOS

- (int) add:(int)a b:(int)b {
    return a+b;
}

@end
```
ApiDefinition.cs <-- Create from sharpie
```C#
using Foundation;

namespace BindingiOS
{
    // @interface TestiOS : NSObject
    [BaseType(typeof(NSObject))]
    interface TestiOS
    {
        // -(int)add:(int)a b:(int)b;
        [Export("add:b:")]
        int Add(int a, int b);
    }
}
```
Test code in Program.cs
```C#
	BindingiOS.TestiOS testobj = new BindingiOS.TestiOS();
	int a = 15;
	int b = 57;
	int c = testobj.Add(a, b);
```

**Comment by rolfbjarne** [comment]
> But 【reference the dll directly】 still has wrong intellisense.

Can you show your csproj file?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 3 and VSMac 17.6.8.400. Builds without errors using user-provided projects. And when I try to reference a binding project from another project, it still works fine.
