### ISSUE TITLE
[iOS] CollectionView will not scroll to the end of a horizontal list when ItemSpacing > 0

### ISSUE THREAD

**Issue by dustypigtv** [dotnet/maui#14788]
### Description

When using a LinearLayout (Horizontal) in a CollectionView with ItemSpacing > 0, the view will not scroll to the end of the list on iOS.

### Steps to Reproduce

1. Download the github repository
2. Run on iOS, the bottom CollectionView with spacing will not scroll to the end
3. Works correctly on Android

### Link to public reproduction project repository

https://github.com/dustypigtv/CollectionViewItemsSpacing

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16

### Did you find any workaround?

Wrap the item template inside another view (stacklayout or grid), then set the margin on the inner view. BUT this will add margin around all items, not just between, so the margin will now show up before the first and after the last item.  Also may be some performance considerations if the view hierarchy is deep

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on iOS 16.4 with below Project:

![image](https://github.com/dotnet/maui/assets/97647558/f44ce311-39b5-4935-b34e-287b46353d7a)

**Comment by Marioo1357** [comment]
Still reproduce on 8.0.7 and newest 8.0.40

**Comment by OudomMunint** [comment]
This is still an issue

**Comment by rmarinho** [comment]
This is fixed on main with CV1 and CV2
