### ISSUE TITLE
Padding not applied to AbsoluteLayout within ScrollView when navigating through app shell.

### ISSUE THREAD

**Issue by RajaRamalingam3772** [dotnet/maui#14797]
### Description

I am facing an issue with setting padding on an AbsoluteLayout within a ScrollView when navigating through app shell. I have two content pages, and in the app shell flyout item tabs, I have set navigation for these two pages. The issue is only reproducible for the second page, and not the first page.

I am setting the padding to the absolute layout ('childLayout') in the OnAppearing method of the second page. However, when I navigate to this second page, the padding is not applied to the layout. I have also tried setting the padding to the layout through a button click in hot reload, but that also does not apply the padding.

However, when I remove the ScrollView from the tree, the padding is applied to the layout using a button click. But its not applying with 'OnAppearing' method.

As an another workaround, I tried setting the layout bounds for the absolute layout instead of setting padding. But that is also not working exactly similar to the above case.

### Steps to Reproduce

1. Create a new MAUI app with two content pages and list them in the app shell like below.

```
<FlyoutItem  Shell.TabBarIsVisible="True"
            FlyoutDisplayOptions="AsSingleItem" >

    <Tab x:Name="report" Title="Report" Icon="report.png" >
        <ShellContent Title="Home"
                        ContentTemplate="{DataTemplate local:BlankPage}"
                        Route="NewPage1" /> 

        <ShellContent x:Name="shell"
                        Title="Home"
                        ContentTemplate="{DataTemplate local:MainPage}"
                        Route="MainPage" />           
    </Tab>

</FlyoutItem>
```

2. Add the below code for the second page.

```
<ScrollView>
    <VerticalStackLayout>
        <Button Text="Click apply padding" Clicked="Button_Clicked"/>
        <AbsoluteLayout  HeightRequest="200" BackgroundColor="LightGray">
            <AbsoluteLayout x:Name="childLayout" AbsoluteLayout.LayoutBounds="0,0,1,1" AbsoluteLayout.LayoutFlags="All"
                BackgroundColor="Red">
                <BoxView AbsoluteLayout.LayoutBounds="0,0,1,1" AbsoluteLayout.LayoutFlags="All" BackgroundColor="Green" />
            </AbsoluteLayout>
        </AbsoluteLayout>
    </VerticalStackLayout>
</ScrollView>
```

3. Set the padding for the AbsoluteLayout (x:Name="childLayout") in the OnAppearing override method of the page.

```
protected override void OnAppearing()
{
    base.OnAppearing();

    childLayout.Padding = new Thickness(40);
}
```

5. Navigate to the second page and observe that the padding is not applied to the layout.
6. Also try with button click for setting padding, it will not work.
```
private void Button_Clicked(object sender, EventArgs e)
{
    childLayout.Padding = new Thickness(60);
}
```

This way you can reproduce the issue well.

Also, while setting the absolute layout bounds as like below, we can reproduce the same issue.

```
protected override void OnAppearing()
{
    base.OnAppearing();

    AbsoluteLayout.SetLayoutFlags(childLayout, AbsoluteLayoutFlags.None);
    AbsoluteLayout.SetLayoutBounds(childLayout, new Rect(0, 0, 100, 100)); 
}
```

### Link to public reproduction project repository

https://github.com/RajaRamalingam3772/PaddingSample

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

We reproduced in all versions

### Did you find any workaround?

NO

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 5.0(8.0.0-rc.2.9373). Seems this issue does not repro on Android 13.0-API33 with below Project:
[PaddingSample.zip](https://github.com/dotnet/maui/files/13173911/PaddingSample.zip)

![Padding](https://github.com/dotnet/maui/assets/97647558/1e245a46-429b-41e7-9505-4cf8303491fb)
