### ISSUE TITLE
Control enabling/disabling style color not working (new in net7.0)

### ISSUE THREAD

**Issue by adamjhilton** [dotnet/maui#14813]
### Description

I'm having issues with controls not respecting their background colors from their styles. Most of this worked in net6.0, but is broken in net7.0. So far, I've noticed this in the following controls:
* Entry
* Picker
* DatePicker
* CheckBox (also broken in net6.0)

Here's what I see in net6.0:
Enabled: background colors are purple.
![image](https://user-images.githubusercontent.com/31253633/234976337-14b72ee9-2658-4619-92d8-50fe01a97f55.png)

Disabled: background colors are gray.
![image](https://user-images.githubusercontent.com/31253633/234976422-f482c09a-6877-46ea-b7ba-448ecf1d209d.png)

And in net7.0:
Enabled: background colors are purple.
![image](https://user-images.githubusercontent.com/31253633/234976539-c5fdc1a2-a775-46c5-8930-4e55571a8306.png)

Disabled: background colors are STILL purple.
![image](https://user-images.githubusercontent.com/31253633/234976552-8f584c03-34c7-4f5e-9ade-6acc151d5cc7.png)

But this is just when the controls are originally drawn as enabled. If their original state was disabled and you enable them, they stay gray. However, they can be interacted with normally, and their text color changes correctly.

Checkboxes are a different story. As you can see in the images above -- and in the attached project -- whatever state they were checked in is the color they stay whether they are enabled or disabled. And the color of unchecked checkboxes are opposite of what they're supposed to be: purple when disabled and gray when enabled. Although, unchecked checkboxes initially start the correct color. As soon as you start disabling and enabling, they go backwards.

### Steps to Reproduce

1. Clone the attached repository. (net6.0)
2. Play around with the Enable and Disable buttons.
3. The Entry, Picker, and DatePicker controls work correctly.
4. The CheckBox control is broken.
5. Change the target framework to net7.0.
6. The Entry, Picker, and DatePicker controls are broken.
7. The CheckBox control is still broken.

### Link to public reproduction project repository

https://github.com/adamjhilton/MauiBugs

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No.

**Comment by PureWeen** [comment]
Is this in release mode that they break?

**Comment by adamjhilton** [comment]
@PureWeen, both debug and release.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. This issue does not repro on Android 13.0-API33, Android 11.0-API30, iOS 16.4 with below Project:
.NET 7: [MauiTestApp.zip](https://github.com/dotnet/maui/files/11954779/MauiTestApp.zip)
![Disable11](https://github.com/dotnet/maui/assets/97647558/c99fbc80-9dee-4ce0-a900-4f01e9d2ac00)
