### ISSUE TITLE
Visual Element gets duplicated after TableView is refreshed

### ISSUE THREAD

**Issue by gktval** [dotnet/maui#14819]
### Description

Rather an odd bug where a control gets duplicated within the table. You cannot interact with the duplicate control, it just seems to be a visual bug. The first image is what the app looks like, after interacting with the table, clearing the root, and resetting the table sections, it randomly adds the last section row to other elements.

This only happens in MacCatalyst and iOS. It does not occur in windows or android.

![image](https://user-images.githubusercontent.com/7605046/235007483-b99d775c-82da-4b28-8c98-8acf90248e83.png)

![image](https://user-images.githubusercontent.com/7605046/235007570-5c319ca9-a43a-417e-840f-ce7e1eda908c.png)

### Steps to Reproduce

Open the project in the repository. Click a section row, it will reset the sections in the Table and the call a PropertyChanged event. When this happens, a random "Click me" button will appear in the table. 

### Link to public reproduction project repository

https://github.com/gktval/MauiTableViewBug.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 14+

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
Very small chance related to https://github.com/dotnet/maui/pull/13669

**Comment by XamlTest** [comment]
Verified this on **7.0.101**, repro on MacCatalyst 13.6.1 and iOS 17.0.
Also verified on **8.0.3**, this issue does not repro on MacCatalyst 13.6.1, iOS 17.0, Windows 11 and Android 14.0-API34.

Repro project: [MauiTableViewBug.zip](https://github.com/dotnet/maui/files/13407378/MauiTableViewBug.zip)

**Comment by gktval** [comment]
This could be fixed, but I cannot test it because row cannot be clicked: https://github.com/dotnet/maui/issues/18047

**Comment by XamlTest** [comment]
> This could be fixed, but I cannot test it because row cannot be clicked: #18047

After https://github.com/dotnet/maui/issues/18047 is fixed, then I will verify and confirm again.
