### ISSUE TITLE
Improve Screenshot API on Windows to allow for WebView screenshots

### ISSUE THREAD

**Issue by hsn-github** [dotnet/maui#14825]
On Windows it is not possible to take a screenshot of the `WebView` with the code we have currently in the `Screenshot` API. We might want to consider adding some specialized code for it so that the consuming developer does not see any difference in public API, but the result will be the same.

For a workaround/code that needs to be implemented see [this comment below](https://github.com/dotnet/maui/issues/14825#issuecomment-1529489594).

---
Original issue:

```c#
    bool iscom=  webView.CaptureAsync().IsCompleted;
    var stream = await webView.CaptureAsync();
    using (var fileStream = new FileStream("image.png", FileMode.Create))
    {
        await stream.CopyToAsync(fileStream, ScreenshotFormat.Png, 100);
    }
```

This code is working fine on Android Phone but on Win Desktop it is returning Blank image and 
bool iscom return true in case of Android and on Win Desktop it always return false.

**Comment by Eilon** [comment]
@hsn-github what is the type of `webView`? Is it the .NET MAUI WebView, or the platform-specific WebView2 on Windows?

**Comment by Eilon** [comment]
On Windows you might need to call the WebView2 `CapturePreviewAsync` method to get a "screenshot" of what's in the webview: https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.capturepreviewasync?view=webview2-dotnet-1.0.1722.45

**Comment by hsn-github** [comment]
its .net MAUI Webview 
e.g. in contentpage or XAML
`Webview webView = new Webview();`

**Comment by jfversluis** [comment]
Seems like we might want to consider adding some specialized code for when someone is taking a screenshot of a `WebView` on Windows. What Eilon was trying to explain is that you need some platform specific code for this. Which would look like this: 

```csharp
string saveImagePath = "image.png";

#if WINDOWS
Stream stream = new FileStream(saveImagePath, FileMode.Create);

await ((MauiWebView)webView.Handler.PlatformView).CoreWebView2
    .CapturePreviewAsync(Microsoft.Web.WebView2.Core.CoreWebView2CapturePreviewImageFormat.Png,
    stream.AsRandomAccessStream());
#else
var stream = await webView.CaptureAsync();

using (var fileStream = new FileStream(saveImagePath, FileMode.Create))
{
    await stream.CopyToAsync(fileStream, ScreenshotFormat.Png, 100);
}
#endif
```

You can of course do it a bit different if you want, but this should work. A fully working example can be found here: https://github.com/jfversluis/MauiWindowsWebViewScreenshotSample

I will keep this issue around, and edit it a little, to make it into a request for change for the `Screenshot` API on Windows
