### ISSUE TITLE
MAUI-Blazor Exception

### ISSUE THREAD

**Issue by MRakesh** [dotnet/maui#1482]
Hi Daniel Roth,
The below code is working in blazor hosted wasm

```csharp
public class ParentComponentBase : ComponentBase
  {	
	[Inject] protected NavigationManager _navigation { get; set; }
	[Inject] protected IJSRuntime _jsRuntime { get; set; }
}

 public partial class Index : ParentComponentBase
 {
 }
```

and in Index.razor file

```
@inherits ParentComponentBase
```

but the same above code is not working in MAUI-Blazor,  getting unhandled error in android emulator.

**Comment by danroth27** [comment]
@MRakesh Thanks for reporting this issue. What is the specific error that you get on Android?

**Comment by MRakesh** [comment]
I am not sure how to see the error in emulator and the debugger is not working for Maui-Blazor app in my VS but at the bottom that says unhandled exception Reload

**Comment by MRakesh** [comment]
I am not sure how to see the error in emulator and the debugger is not working for Maui-Blazor app in my VS but at the bottom that says unhandled exception Reload

**Comment by rabberbock** [comment]
I am also running into a similar issue as well. Wasm works well, but on Maui I get the following chromium error in the android device logs:

```
Time	Device Name	Type	PID	Tag	Message
07-02 11:27:14.759	pixel_2_pie_9_0_-_api_28	Info	26807	chromium	[INFO:CONSOLE(1)] "Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterView parameters)", source: https://0.0.0.0/_framework/blazor.webview.js (1)
```

**Comment by Eilon** [comment]
I am seeing this exception now but in a very different scenario.

**Comment by Eilon** [comment]
Ah, it looks like in my case there's an ambiguous route:

```
System.InvalidOperationException: 'The following routes are ambiguous:
'/' in 'Maui.Controls.Sample.Pages.Others.Index'
'/' in 'Maui.Controls.Sample.Pages.Index'
'
```

And it's bubbling up as a super weird exception.

**Comment by Eilon** [comment]
Once I fixed the ambiguous route, the error completely went away.

And as far as that error showing up to begin with, I think that's this Blazor bug: https://github.com/dotnet/aspnetcore/issues/32411

So I'm not aware of any specific issue in Blazor Desktop.
