### ISSUE TITLE
Error reading response from wcf service in basicHttpBinding

### ISSUE THREAD

**Issue by ptk369** [dotnet/maui#14836]
### Description

I am porting a xamarin.forms application to .net.maui with .net 7 and cannot get WCF server responses using basicHttpBinding.

The service has not changed and xamarin.forms and windows clients still work.
I also tried a windows console app with .net 7, the same code works as expected.
(I reported the same issue on dotnet/wcf #5127 because I don't know if its more related to .net.maui or wcf)

Under .net.maui I get one of these errors, depending on the returned data:
System.ServiceModel.CommunicationException: 'Error in deserializing body of reply message for operation 'ConnectDwProject'. Unexpected end of file. Following elements are not closed: Envelope. Line 1, position 284.'
System.ServiceModel.ProtocolException: 'The number of bytes available is inconsistent with the HTTP Content-Length header. There may have been a network error or the client may be sending invalid requests.'
And other errors, all showing that the received data cannot be interpreted.

This happens with basicHttpBinding only, when we use wsHttpBinding it works as expected.
Using http or https does not change the behaviour.

### Steps to Reproduce

use wcfService and Maui / Console clients
replace IP with the IP on your machine
Link to service: https://github.com/ptk369/WCFService1

### Link to public reproduction project repository

https://github.com/ptk369/WCFClientMaui

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tried with API 28-33, all the same

### Did you find any workaround?

wsHttpBinding works, but our customers servers all use basicHttp binding, are still using the Xamarin.Forms app, and have to be modified.

**Comment by PureWeen** [comment]
https://github.com/dotnet/runtime/issues/80935
