### ISSUE TITLE
Navigation.push Speed in Android 

### ISSUE THREAD

**Issue by mohammadyz** [dotnet/maui#1484]
Hi
Navigation.pushasync is to slow since Xamarin.Forms in Android please improve that.

**Comment by GalaxiaGuy** [comment]
Have you tried MAUI on Android yet? The navigation code on Android is already very different: https://github.com/dotnet/maui/pull/837

**Comment by mohammadyz** [comment]
Yes I tried but it's same and I think it's slower
I tried weatherapp on my phone

**Comment by PureWeen** [comment]
Once stable if it's still slow for you please attach a Maui Repro
