### ISSUE TITLE
iOS support for NSUserDefaults.DidChangeNotification not working.

### ISSUE THREAD

**Issue by s3743761** [dotnet/maui#14857]
### Description

 iOS api NSUserDefaults.DidChangeNotification doesn't get invoked when UserDefaults get changed.
This is required for MDM implementation in iOS using AppConfig

### Steps to Reproduce

1. Create a MAUI App.
2. In your platform specific iOS code add the following in constructor

```c#
          var observer2 = NSNotificationCenter.DefaultCenter.AddObserver(NSUserDefaults.DidChangeNotification,
          n => { Console.WriteLine("Notified"); });
```
         
and create a method as in same class
```c#
        public const string MangedConfigurationKey = "com.apple.configuration.managed";

        public partial string GetStringValue(string key)
        {
            var dic = NSUserDefaults.StandardUserDefaults.DictionaryForKey(MangedConfigurationKey);
            if (dic != null)
            {
                NSObject value = null;
                if (dic.TryGetValue(new NSString(key), out value) && value != null)
                    Console.WriteLine(value);
                    return value.ToString();
            }

            return null;
        }
```
4. Run the code and see nothing getting printed.
5. Run a simulator and enter key, value using following command `xcrun simctl spawn booted defaults write {apple_bundle_id} com.apple.configuration.managed -dict 'key1' 'VALUE1'`.
6. You will see no the notification is not triggered even though there is a change in NSUserDefaults.
7. Now Create a button and attach the OnClick to GetStringValue("key1");
8. Now you will see the value on button click but not with Notification Center
9. try deleting  and re-running the command from step 5 again, same result` xcrun simctl spawn booted defaults delete {apple_bundle_id}`

Ideally, the Console.WriteLine("Notified"); should be triggered with the command from step 5.

### Link to public reproduction project repository

given in description

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16 and before

**Comment by drasticactions** [comment]
I recommend trying what you're doing in a dotnet iOS app (`dotnet new ios`) to see if it works there.

**Comment by s3743761** [comment]
@drasticactions no It still doesn't work. This is my code

```c#
[Register ("AppDelegate")]
public class AppDelegate : UIApplicationDelegate {
	public override UIWindow? Window {
		get;
		set;
	}

	public override bool FinishedLaunching (UIApplication application, NSDictionary launchOptions)
	{
		// create a new window instance based on the screen size
		Window = new UIWindow (UIScreen.MainScreen.Bounds);

		// create a UIViewController with a single UILabel
		var vc = new UIViewController ();
		vc.View!.AddSubview (new UILabel (Window!.Frame) {
			BackgroundColor = UIColor.SystemBackground,
			TextAlignment = UITextAlignment.Center,
			Text = "Hello, iOS!",
			AutoresizingMask = UIViewAutoresizing.All,
		});
		Window.RootViewController = vc;

		// make the window visible
		Window.MakeKeyAndVisible ();

   

    
     
        NSNotificationCenter.DefaultCenter.AddObserver(
               NSUserDefaults.DidChangeNotification,
               DefaultsChanged,
               null);
        GetStringValue("key1");

        return true;
	}

    private void DefaultsChanged(NSNotification notification)
    {
		// Get the user defaults
		Console.WriteLine("DefaultsChanged");

    }

    public const string MangedConfigurationKey = "com.apple.configuration.managed";

    public string GetStringValue(string key)
    {
        var dic = NSUserDefaults.StandardUserDefaults.DictionaryForKey(MangedConfigurationKey);
        if (dic != null)
        {
            NSObject value = null;
            if (dic.TryGetValue(new NSString(key), out value) && value != null)
                Console.WriteLine(value.ToString());
        }

        return null;
    }


}


```

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-macios#18193
