### ISSUE TITLE
[Shell] GoToAsync("..") from modal page does nothing

### ISSUE THREAD

**Issue by nor0x** [dotnet/maui#14858]
### Description

I'm navigating to a Page which has `Shell.PresentationMode="ModalAnimated"` by calling 
`await Shell.Current.GoToAsync("///NewPage");` 

navigating back via `await Shell.Current.GoToAsync("..");` does nothing

### Steps to Reproduce

1. Clone https://github.com/nor0x/MauiRepro_14858
2. Launch
3. Wait modal navigation
4. Click "Go Back"

### Link to public reproduction project repository

https://github.com/nor0x/MauiRepro_14858

### Version with bug

7.0.81

### Last version that worked well

7.0.81
### Affected platforms

iOS, Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android, Windows, iOS

### Did you find any workaround?

navigation via
`await Shell.Current.Navigation.PushModalAsync(new NewPage1(), true);
`and back with
`await Shell.Current.Navigation.PopModalAsync(true);
`

works - but without routes obviously

**Comment by greg84** [comment]
Registering the page in AppShell causes it to only exist at the root level, so relative routing to that page doesn't work.

The documentation on shell navigation is not super clear. I downloaded your sample and was able to get it to work by doing this:

1. Remove the <ShellContent> tag for NewPage from AppShell.xaml

2. Add this line to the constructor of AppShell()...

`Routing.RegisterRoute("NewPage", typeof(NewPage1));`

3. Change the line in MainPage to this...

`await Shell.Current.GoToAsync("NewPage");`

**Comment by nor0x** [comment]
thank you @greg84 - this works for me.

i agree - there is room for improvement in the docs - especially Shell
