### ISSUE TITLE
The project doesn't know how to run the profile with name 'Windows Machine' and command 'MsixPackage'.

### ISSUE THREAD

**Issue by techierathore** [dotnet/maui#14862]
### Description

Description
I've created a new MAUI Blazor project and tried to execute it and got following error 

" The project doesn't know how to run the profile with name 'Windows Machine' and command 'MsixPackage'."

I have installed all of the latest stable version of Visual Studio Community 2022:

Universal Windows Platform development,
MAUI Workload,
ASP.Net and web development,
.NET desktop development,

Even installed MSIX Packaging tool as suggested in following bug 
https://github.com/dotnet/maui/issues/4797

The Windows Version is 22H2 (build 19045.2846)
Visual Studio version is Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.5.4

### Steps to Reproduce

Create a new MAUI Blazor project and execute it.  

### Link to public reproduction project repository

NA

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Windows 

### Did you find any workaround?

NA

**Comment by davidortinau** [comment]
I followed these steps on a Sandbox and was unable to reproduce this error. The Blazor MAUI hybrid template runs, and a default .NET MAUI app also run.

.NET MAUI 7.0.71
VS 17.5.4 Community
Windows 11, 22H2 25346.1001

**Comment by PureWeen** [comment]
Can you please log an issue with VSFeedback? You can include a recording which will help to diagnose.
