### ISSUE TITLE
Maui apps fail to compile[Bug] 

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#1487]
![problem](https://user-images.githubusercontent.com/39104606/123730386-1f0ca000-d84b-11eb-9924-020a70449e6b.png)

Whenever I create a new project and try to build, i get the errors as mentioned in the screenshot.
I even tried to run maui-check and it said everything was fine.
It used to work but somehow suddenly does not work anymore.
Would be disappointed if some computers can't even create maui apps.

**Comment by jfversluis** [comment]
> Would be disappointed if some computers can't even create maui apps.

I would be too! But that is definitely not going to happen :) 

It seems this is from some time ago and running on VS2019. I hope you installed all the latest bits by now and your experience has been better. If not, please open a new issue with all the necessary details, thanks!
