### ISSUE TITLE
Using font files does not work

### ISSUE THREAD

**Issue by oujunke** [dotnet/maui#14871]
### Description

> 
If the file type font is not obtained, the default font will be returned instead of throwing an error

```cs
	public static class FontExtensions
	{
		public static SKTypeface ToSKTypeface(this IFont font)
		{
			if (string.IsNullOrEmpty(font?.Name))
				return SKTypeface.Default;
			try
			{
				return SKTypeface.FromFamilyName(font.Name, font.Weight, (int)SKFontStyleWidth.Normal,
					font.StyleType switch
					{
						FontStyleType.Normal => SKFontStyleSlant.Upright,
						FontStyleType.Italic => SKFontStyleSlant.Italic,
						FontStyleType.Oblique => SKFontStyleSlant.Oblique,
						_ => SKFontStyleSlant.Upright,
					});
			}
			catch
			{
				return SKTypeface.FromFile(font.Name);
			}
		}
	}
```

### Steps to Reproduce

1. New SkiaCanvas
2. Set Font

### Link to public reproduction project repository

https://github.com/oujunke/TestMauiFont.git

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Win10

**Comment by oujunke** [comment]
I created a project:https://github.com/oujunke/TestMauiFont.git

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Not repro on windows platforms with sample project.
https://github.com/oujunke/TestMauiFont.git
