### ISSUE TITLE
DisplayAlert not working on CommunityToolkit.Maui Popup

### ISSUE THREAD

**Issue by acaliaro** [dotnet/maui#14870]
### Description

Trying to display a DisplayAlert by pressing a Button in a CommunityToolkit.Maui Popup. The DisplayAlert is not displayed

### Steps to Reproduce

1- Run the project
2- press "Open popup"
3- press "Show display alert"

### Link to public reproduction project repository

https://github.com/acaliaro/MauiPicker

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.7

### Did you find any workaround?

No workaround

**Comment by PureWeen** [comment]
@pictos @brminnick thoughts?

**Comment by acaliaro** [comment]
> Hi @acaliaro. We have added the "s/needs-info" label to this issue, which indicates that we have an open question for you before we can take further action. This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

Sorry, but which is the "open question"?

**Comment by PureWeen** [comment]
@acaliaro the open question is if this is a MAUI issue or an MCT issue so I'm waiting on guidance from MCT.

**Comment by acaliaro** [comment]
> @acaliaro the open question is if this is a MAUI issue or an MCT issue so I'm waiting on guidance from MCT.  If this is purely an MCT issue, then we will close it here.

Ok @PureWeen , so we are waiting MCT boys?

**Comment by pictos** [comment]
@PureWeen I'll look asap and report back

**Comment by marekm294** [comment]
There is already opened proposal https://github.com/dotnet/maui/issues/14258.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Can repro on iOS platforms with sample project.
https://github.com/acaliaro/MauiPicker.git

**Comment by jfversluis** [comment]
I can't reproduce anymore with .NET MAUI 8.0.14 and Toolkit 8.0.0 on iOS and macOS. If you still experience this with those version please let us know, thanks!
