### ISSUE TITLE
[Bug] Unable to compile after creating a new project, The name 'InitializeComponent' does not exist in the current context

### ISSUE THREAD

**Issue by VinceKellyBM** [dotnet/maui#1488]
I have installed DotNet 6 preview 5, and run the latest maui-check, I have installed both of the project reunion tools as well, everything reports as being fine.
In Visual Studio 2019 Preview and from the CLI if I create a new Maui project, then try to compile it to run it I get the above error on all InitializeComponent(); calls.

Steps to Reproduce

1.  Create a new project in Visual Studio 2019 preview

Screenshots

![MauiProblem001](https://user-images.githubusercontent.com/42607860/123761131-6fbae200-d8b9-11eb-9e4f-812c442fdaa9.jpg)

![MauiProblem002](https://user-images.githubusercontent.com/42607860/123761170-78131d00-d8b9-11eb-869c-63ed12f05ddd.jpg)

![MauiProblem003](https://user-images.githubusercontent.com/42607860/123761065-5d40a880-d8b9-11eb-8f23-f761efd38a7e.jpg)

![MauiProblem004](https://user-images.githubusercontent.com/42607860/123761212-8103ee80-d8b9-11eb-8fa2-4215186c43e0.jpg)

Any help would be greatly appreciated thanks.

**Comment by rvlietstra** [comment]
I have the same issue. It seems it is currently not possible to create a maui project.

I tried repairing visual studio. 
I tried uninstalling/reinstalling the .net 6 sdk.

Is it an issue with the templates ? Could it be that whatever the MauiXaml build action does isn't getting executed ?

Thanks

**Comment by gohopo** [comment]
try move the project to the folder without any special character #1596

**Comment by VinceKellyBM** [comment]
Hi gohopo, many thanks this has resolved my issue. I will close this issue as #1596 explains exactly the problem. Thanks again.
