### ISSUE TITLE
".NET MAUI" is not Listed as Project Template on Visual Studio 2022 Community

### ISSUE THREAD

**Issue by geasi** [dotnet/maui#14890]
### Description

Hello,

I can't find ".NET MAUI" as an option when I click "Create new Project" on Visual Studio 2022 Community.

I have:

- Windows 11 Pro 22H2
- Visual Studio 2022 Community (installed with the ".NET Multi-platform App UI development")

### Steps to Reproduce

(from a fresh installation of Windows 2022 Pro 22H2)

1. Install Visual Studio 2022 Community with the following Workload selected: ".NET Multi-platform App UI development"
2. Open VS and click "New Project"
3. Search for "MAUI"
4. No results

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

22H2

### Did you find any workaround?

So far I had:

1. Enabled "Developer" mode on my new computer
2. Reordered the Path Env variable to have "C:\Program Files\dotnet\" before "C:\Program Files (x86)\dotnet\"
3. Installed two more workloads: ".NET desktop development" and "ASP.NET and web development"
4. Ran the command "dotnet workload install maui"
5. Repaired the Visual Studio installation

And, **of course**, restarted my computer many times.
I don't even remember the order I did but after ALL THESE STEPS I can see it now.

**Microsoft**, is that how you expect to have more developers using your technology??

TERRIBLE EXPERIENCE SO FAR

**Comment by mattleibow** [comment]
This is probably "by design" because a few versions of VS ago the IDE could not handle the case of a project without a solution. However this has been fixed and this PR will make the projects work: https://github.com/dotnet/maui/pull/14841

**Comment by mattleibow** [comment]
I updated the templates to be project templates now.
