### ISSUE TITLE
Binding Context on Content View

### ISSUE THREAD

**Issue by AathifMahir** [dotnet/maui#14919]
### Description

Setting Binding Context on Content View Doesn't Work with Data Template with Compiled Bindings Unless We Set the Relative Source Explicitly, But the Same Content View Without Binding Context Works as Intended with Compiled Bindings without any Relative Source

More Information Regarding This Can be Found in the below Github Repo Sample

Is this the intended behavior or Bug?

### Steps to Reproduce

1. Create New Maui Project
2. Create a Content View with Couple of Bindable Property
3. Set the Binding Context to Same Content View
4. Use that ContentView on MainPage.xaml with Compiled Binding Enabled

### Link to public reproduction project repository

https://github.com/AathifMahir/BindingContextOnDataTemplate

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11 22H2

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Can repro on Windows platforms with sample project.
https://github.com/AathifMahir/BindingContextOnDataTemplate
![image](https://github.com/dotnet/maui/assets/82450723/872b314a-381f-445e-bff9-247736834e11)
