### ISSUE TITLE
iOS: Content in `Border` with `StrokeShape` of `Ellipse` not rendered correctly.

### ISSUE THREAD

**Issue by RobTF** [dotnet/maui#14927]
### Description

I attempted to add font icon content into a circular "button-like" component I was building;

The component is a border with an ellipse stroke shape, with a label containing the font icon in it.

On Android this renders correctly;
![android](https://user-images.githubusercontent.com/4292237/236263191-a99df513-876b-4cef-90d7-bee328609e8d.png)

On iOS it is quite broken;
![ios](https://user-images.githubusercontent.com/4292237/236263243-e33219cd-51fe-4a0a-b907-443b72b7cde4.PNG)

It is as if the ellipse stroke clip is being applied to the children of `Border` as well as the border itself.

### Steps to Reproduce

1. Open my repro project.
2. Run in iOS
3. Observe issue.

### Link to public reproduction project repository

https://github.com/RobTF/mauiplay/tree/master/BorderStrokeShapeIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Avoid the issue by making nothing a child of `Border` if at all possible, e.g.

```xaml
            <Border
                Style="{StaticResource ButtonStyle}">
                <Label
                    Style="{StaticResource ButtonIcon}"
                    Text="circle"
                    TextColor="#ff3333"
                    FontFamily="FontAwesomeSolid" />
            </Border>
```
becomes...
```xaml
            <Grid>
                <Border Style="{StaticResource ButtonStyle}" />
                <Label
                    Style="{StaticResource ButtonIcon}"
                    Text="circle"
                    TextColor="#ff3333"
                    FontFamily="FontAwesomeSolid" />                
            </Grid>
```

### Relevant log output

```shell
None.
```

**Comment by mattleibow** [comment]
You can try make the root of the Border a Grid, and put your content in there.

```xaml
<Border>
  <Grid>
    <Label>
```

**Comment by mattleibow** [comment]
@jsuarezruiz You may have a PR on this? Is this a duplicate?

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz You may have a PR on this? Is this a duplicate?

Is not a duplicate.

**Comment by Axemasta** [comment]
I am seeing this issue on .NET 7. The proposed workaround doesn't really work in my case, this makes the `Frame` -> `Border` migration incredibly frustrating if coming from Forms... 🙁

**Comment by jsuarezruiz** [comment]
Work in progress, will be fixed by https://github.com/dotnet/maui/tree/fix-14927-II
