### ISSUE TITLE
ImageButton cannot be smaller than ~30

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#14932]
### Description

`ImageButton` does not obey small sizes on Windows. I have not tested other operating systems.

### Steps to Reproduce

```xaml
        <Grid Grid.Row="0" RowDefinitions="30">
            <ImageButton
                Padding="0"
                WidthRequest="20"
                BackgroundColor="Black"
                CornerRadius="5"
                HorizontalOptions="End"
                Source="refresh.png"
                VerticalOptions="Start" />
 ```
 
 Does not set the image to 20 wide. Replacing `ImageButton` with `Image` works correctly.

### Link to public reproduction project repository

https://github.com/daltzctr/SmallImageButtonRepo

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041.0

### Did you find any workaround?

No.

**Comment by daltzctr** [comment]
Adding onto this, there seems to be a lot of controls like this.

To name a few

- Entry
- Picker

**Comment by drasticactions** [comment]
How small could you make a similar WinUI control with similar elements without MAUI? It could be a limitation of the given control set in WinUI.

**Comment by AmrAlSayed0** [comment]
I think this is [intentional](https://github.com/dotnet/maui/blob/a721d8babaab5caf108a1490f8c8fcb3fa2c2033/src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml#L146) for accessibility reasons. Having a press-able element be too small isn't very good for accessibility.

**Comment by daltzctr** [comment]
Workaround: Manually specifying MinimumWidth and MinimumHeight. Ideally, these would be set to 0 or much smaller on Windows.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11 and iOS 16.4(8.0.0-preview.7.8842), not repro on Android 13.0-API33 with below Project:
[SmallImageButtonRepro.zip](https://github.com/dotnet/maui/files/12606559/SmallImageButtonRepro.zip)
![ImageButton](https://github.com/dotnet/maui/assets/97647558/1d1e431c-ad20-4b64-9a63-333dc584ed4f)

**Comment by mattleibow** [comment]
The default Styles.xaml have a min width/height of 44 or something? Was that removed?

**Comment by daltzctr** [comment]
@mattleibow I would expect the minimum width and height to not be set at all, or set to 0.

**Comment by mattleibow** [comment]
It is set for accessibility and UX guidelines for touch devices. You can just remove it as it is just a template value.
