### ISSUE TITLE
[regression/8.0-preview 4] Border with RoundRectangle Corner Radius values are smaller than they were

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#14936]
### Description

In .NET 8 P4, on Android specifically, the RoundRectangle stroke shape with a corner radius of '10' is too small.  One thought is that maybe the pixel / dpi scaling calculation has been lost on android?

Android (now, on .NET 8 P4):
![image](https://user-images.githubusercontent.com/271950/236346349-7ce8e21b-02a1-40ae-8080-64451c175037.png)

Windows looks fine still (and android used to look like this too):
![image](https://user-images.githubusercontent.com/271950/236345983-4b0d282e-c960-4bf5-98e8-750e0b33f424.png)

### Steps to Reproduce

`<Border StrokeShape='{RoundRectangle CornerRadius=10}' Background="Blue" WidthRequest="200" HeightRequest="200" />`

### Link to public reproduction project repository

N/A

### Version with bug

8.0 previews

### Last version that worked well

7.0 (current)

### Affected platforms

Android

### Affected platform versions

All

**Comment by rmarinho** [comment]
Fixed by #17087
