### ISSUE TITLE
Always have to close and restart VS between each new change

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#14943]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Always-have-to-close-and-restart-VS-betw/10335105)._

---
This is driving me nuts, why do I have to randomly close and restart VS between each code change made? Seems like every time I stop the application to make a change, then re-run the app, it fails and the only thing I can do to get out of that locked state is to stop/close VS and restart. 

There are so many issue with MAUI, definitely not stable enough for us to use in Production just yet. 

---
#### Feedback Bot on 4/10/2023, 07:37 PM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 4/11/2023, 02:59 AM: 

(private comment, text removed)
#### Richard Dufour on 4/11/2023, 08:20 AM: 

(private comment, text removed)
#### Richard Dufour on 4/11/2023, 02:03 PM: 

(private comment, text removed)
#### Richard Dufour on 4/11/2023, 03:00 PM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 4/12/2023, 03:10 AM: 

(private comment, text removed)
#### Richard Dufour on 4/12/2023, 08:07 AM: 

(private comment, text removed)
#### Richard Dufour on 4/12/2023, 08:13 AM: 

(private comment, text removed)
#### Richard Dufour on 4/12/2023, 10:16 AM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 4/12/2023, 10:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drasticactions** [comment]
For reference, this was the last comment on the issue

```
I think I might have found out what is causing the issue. This used to work in Xamarin:

<controls:Frame BorderColor="Black" Margin="0" Padding="0" HorizontalOptions="CenterAndExpand" HasShadow="False">
                        <Entry x:Name="UsernameBox"
                               
Text=“{Binding Username}”
Placeholder=“Username”
FontSize=“Small”
WidthRequest=“320”
IsPassword=“False”


VerticalOptions="Center"
                               HorizontalOptions="Center"
                               IsSpellCheckEnabled="False"
                               IsTextPredictionEnabled="False"
                               Keyboard="Plain"
                               />
 </controls:Frame>
But cause the hanging issue on MAUI, I removed the Frame and, so far, the app has not hung/froze… yet.

                        <Entry x:Name="UsernameBox"
                               Text="{Binding Username}"
                               Placeholder="Username"
                               FontSize="Small"
                               WidthRequest="320"
                               IsPassword="False"
                               VerticalOptions="Center"
                               HorizontalOptions="Center"
                               IsSpellCheckEnabled="False"
                               IsTextPredictionEnabled="False"
                               Keyboard="Plain"
                               />

Finger’s crossed. A lot of voodoo magic with MAUI for sure. A lot of guessing.
```
