### ISSUE TITLE
[Bug] StackLayout does not appear to update when pushed new child elements.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#1494]
Tested with: 6.0.100-preview.5.794

### Description
In Xamarin.Forms, when pushing new children elements into an existing `StackLayout`, the new elements appear at the bottom of the stack. In MAUI, if you try the same thing, the elements don't seem to appear or render.

### Steps to Reproduce

1.  Check out [This Project](https://github.com/drasticactions/MauiFormsApp/tree/4d5cd77afa85b8baccbb42c61c986474cdee05b2)
2. Build and launch `MauiApp`
3. Click on `Add New Label`

### Expected Behavior
The new label gets inserted and appears at the bottom of the stack layout.

### Actual Behavior
Nothing appears to happen.

### Basic Information
This example also affects Hot Reload. When you add a new element to the stack layout nothing seems to change in the initial stack, while the Live Visual Tree does appear to update. It appears, on the surface at least, to be the same issue happening here with code behind.

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
Works in Preview 7.

**Comment by drasticactions** [comment]
https://user-images.githubusercontent.com/898335/128916919-26518dca-be60-41d1-b8aa-04585f6a8838.mp4

Update to this bug: It seems to be fixed in Android, where we can add and remove children and they properly reappear. It still appears broken in iOS. This is based on the newest main rc builds.

**Comment by hartez** [comment]
@drasticactions Should be fixed with the latest in main.
