### ISSUE TITLE
can't find option to create maui project

### ISSUE THREAD

**Issue by diamondbarcode** [dotnet/maui#14959]
The problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: Windows

I follow the steps to install what I need when I try to create the first project I could not find any Maui or Xamarin anywhere I am using visual studio 2022 community edition version 4.8.09032 ..

I used to have it until I do a fresh install on my pc and for some reason, it just disappear. I am not sure where I do wrong here ..

**Comment by EagleDelux** [comment]
During installation, the .NET Multi-platform App UI development workload should be selected. 
![image](https://user-images.githubusercontent.com/127604980/236659851-8cd6753f-6274-4453-9cac-40f566ca5d54.png)
Please make sure you have installed .NET MAUI:
Select the Windows key, type Visual Studio Installer, and press Enter.
Find your Visual Studio 2022 installation and select Modify.
Check that ".NET Multi-platform App UI develpment" is selected. 
![image](https://user-images.githubusercontent.com/127604980/236660032-aa902715-44f2-434f-a872-a9cb267dc204.png)

**Comment by jfversluis** [comment]
Seems like vsfeedback didn't take here. Closing this one.
