### ISSUE TITLE
Shell.SetTabBarIsVisible is not working WinUI

### ISSUE THREAD

**Issue by ne0rrmatrix** [dotnet/maui#14969]
### Description

Setting Tab bar visibility is not working in WinUI after you have loaded Page. Only works if you set it in xaml.
```csharp
Shell.SetTabBarIsVisible(Shell.Current.CurrentPage, false);
```
It works fine in Android and IOS.
### Steps to Reproduce

1. Create a new DotNet Maui Application.
2. In Code behind ``` Shell.SetTabBarIsVisible(Shell.Current.CurrentPage, false); ``` put it function and execute function.
3. create button and put this in button.

```csharp
 private void ContentPage_Loaded(object sender, EventArgs e)
    {
        Shell.SetTabBarIsVisible(Shell.Current.CurrentPage, false);
    }
```

### Link to public reproduction project repository

https://github.com/ne0rrmatrix/TabBarBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17763.0 and up

### Did you find any workaround?

Disable tab bar at top of xaml and do not use tab bar.

### Related to

- [ ] #7246

**Comment by jsuarezruiz** [comment]
The sample https://github.com/ne0rrmatrix/TabBarBug is not working, maybe are you missing to make it public?

**Comment by ne0rrmatrix** [comment]
> The sample https://github.com/ne0rrmatrix/TabBarBug is not working, maybe are you missing to make it public?

Fixed. Repo is public now

**Comment by ne0rrmatrix** [comment]
What is needs attention? Do you need me to do anything?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11, not reproduce on Android 13.0-API33 and iOS 16.4 with below Project:
[TabBarBug.zip](https://github.com/dotnet/maui/files/11974498/TabBarBug.zip)

![image](https://github.com/dotnet/maui/assets/97647558/c6aea808-92ea-4ab3-aac3-d9a6bbdb0734)
