### ISSUE TITLE
`"Uncaught ReferenceError: Blazor is not defined", source: https://0.0.0.0/ `on physical Android device

### ISSUE THREAD

**Issue by hypdeb** [dotnet/maui#14961]
### Description

App is stuck on "Loading..." screen (i.e. before actual app is loaded) on physical devices.

The specifications of my physical device are (I'm not sure exactly what is relevant):

- Brand: Huawei
- Model: VOG-L29 (P30 Pro)
- EMUI version: 12.0.0
- Google Play System Update: 2023-04-01 Q
- Kernel Version: 4.14.116

### Steps to Reproduce

- Create new MAUI Blazor app: `dotnet new maui-blazor -n MyBlazorMAUIApp`
- Publish it by following instructions here: https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-cli
- Copy the `apk` file to physical phone
- Open `apk` file on physical phone to install app
- Start app

The app doesn't load. Using `adb shell logcat`, the only potentially pertinent log entry I could find was "Uncaught ReferenceError: Blazor is not defined"

### Link to public reproduction project repository

Default app template

### Version with bug

8.0 previews

### Last version that worked well

7.0

### Affected platforms

Android

### Affected platform versions

Android 11 and up

**Comment by hypdeb** [comment]
Ah, one piece of information I forgot to mention: the app works perfectly fine when debugging on the device through USB. The phone itself is capable of running it.

**Comment by drasticactions** [comment]
<img width="750" alt="スクリーンショット 2023-05-07 22 46 19" src="https://user-images.githubusercontent.com/898335/236681333-76a1e4e5-345f-4458-8766-f92b2a821c85.png">

![IMG_1243](https://user-images.githubusercontent.com/898335/236681705-e098499a-c1ae-41f8-8e99-e1adb4676c8a.jpeg)

- Created a new MAUI Blazor Project
- Debugged it to Device, worked.
- Uninstalled it.
- Ran the publishing steps
  - Set up a Provisioning Key Store With keytool
  - Added the required parameters to the csproj
  - ran dotnet publish
  - Dragged and dropped the file on the emulator first to test that. Ran it, worked.
  - Ran adb install and installed the release APK on my Pixel. Worked.

**Comment by drasticactions** [comment]
Can you upload the APK you're trying to run? It could be your device, or maybe how you built the package (I was building with Release mode)

https://1drv.ms/u/s!AkVh4q06uIhojY1Jtxe859DRfZPtkg?e=qaWTpX

I've uploaded my release mode APK I built, using the template. Can you try that and see if it works on your device?

**Comment by hypdeb** [comment]
Hello @drasticactions,

Thanks for the answer.

Your application works.

Here is my build: https://drive.google.com/file/d/1MLQFOB6eW_UKF6Wl0fSoWJ7Q2ILW4mqO/view?usp=share_link

Here is the folder from which I run the build. Sorry for the weird structure there, it's a sandbox for all my repros and I don't really tidy up :D

The command I run:
```
dotnet publish maui/WhyDoesItNotWork/WhyDoesItNotWork.csproj -f net8.0-android -c Release -p:AndroidSigningStorePass=123456 -p:AndroidSigningKeyPass=123456
```

**Comment by drasticactions** [comment]
Ahh, I did notice you're running with .NET 8. 

CC @jonathanpeppers

**Comment by hypdeb** [comment]
Gosh it's the first thing I should have tried... I had forgotten I was working with a preview version :D It works with net7.0. Still, I guess it's something that should be looked into for net8.0 release. Is @jonathanpeppers the person to go to for that ?

**Comment by hypdeb** [comment]
I don't know if it's related but there's also a lot of warnings which I think don't make sense like this one:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA1416	This call site is reachable on: 'Android
            ' 24.0 and later. 'FontCollectionExtensions.AddFont(IFontCollection, string, string?)' is only supported on: 'Android' 21.0 and later.	****** (net8.0-android)	D:\******\MauiProgram.cs	16	Active
```
If it is supported on `21.0` or later, it seems it should be fine that it's reachable on `24.0`, because `24.0` is later than `21.0`.

**Comment by jonathanpeppers** [comment]
I think the error message `Uncaught ReferenceError` might be something blazor-related, and not Android-related:

https://stackoverflow.com/a/67145218

This is a MAUI API, that isn't decorated with any `[SupportedOSPlatform]` attributes that I can tell, I'm not sure how this warning would appear:

```
Warning	CA1416	This call site is reachable on: 'Android
' 24.0 and later. 'FontCollectionExtensions.AddFont(IFontCollection, string, string?)' is only supported on: 'Android' 21.0 and later.
```

**Comment by hypdeb** [comment]
@Eilon do you have an approximate idea of how difficult this is to fix? Two reasons for me to ask: if it's a good first issue, I'd be willing to give it a try, otherwise, I would like to know if I should be downgrading to 7.0, or if it can be working again 'soonish'.

**Comment by e012345678** [comment]
Any update on this? I just tried with net8.0 Preview 4 and Android app stuck on Blazor loading... exact same app was working fine on net7.0

**Comment by mhrastegari** [comment]
yeah me too :(

**Comment by damianjr4634** [comment]
Hi something new?
With Dotnet 8 previews 7 the problem continues.
A new Maui Hybrid project is created, compiled to release, and installed on the mobile phone. The app runs and stays with the message "Loading..."

**Comment by Eilon** [comment]
@damianjr4634 - for .NET 8 Preview 7 specifically, there's a bug that has a workaround listed here: https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849. Please try that out and let us know if it resolves it.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Cannot repro on Android platforms with repro steps, the apk file can be installed and opened on Android device.

**Comment by Eilon** [comment]
> Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Cannot repro on Android platforms with repro steps, the apk file can be installed and opened on Android device.

Just to confirm, you're saying you cannot reproduce the bug anymore?
