### ISSUE TITLE
Impossible to add UseWindowsForms in a MAUI project

### ISSUE THREAD

**Issue by guyvaio** [dotnet/maui#14970]
I've created a new MAUI project 7.0. In this project I need to reference an assembly compiled against .net 7.0 but with `<UseWindowsForms>true</UseWindowsForms>`. So I need to add `<UseWindowsForms>true</UseWindowsForms>` in the project.

When adding this line, the project does not compile anymore and claims for: "Project file must include the .NET Framework assembly 'PresentationCore, PresentationFramework' in the reference list. ... Microsoft.WinFX.targets".

I understand I have to add this line in the MAUI project (not needed in my case): `<UseWPF>true</UseWPF>`.

Consequently I get this error: 'App' does not contain a definition for 'InitializeComponent'

Tried to force build action to MauiXaml for all XAML files.

if I replace all XAM file by their equivalent cs files, I can add `UseWindowsForms` without `UseWpf` and everything works fine.

Seems that when `UseWindowsForms` is added and XAML files exist, WPF is required, even though there is no XAML files for WPF.

Visual Studio 17.5.5 has been restarted several times. Bin and Obj directories have been manually deleted several times.

**Comment by drasticactions** [comment]
Most likely, your issue is already addressed in MAUI Main,

https://github.com/dotnet/maui/pull/14595#issuecomment-1511565265

https://github.com/dotnet/maui/pull/14331

**Comment by guyvaio** [comment]
Repro 

- create new project with ".NET MAUI App" template
- Add <UseWindowsForms>true</UseWindowsForms> in project
- In App.xaml.cs, replace App : Application by App : Microsoft.Maui.Controls.Application to prevent ambiguous reference
- compile
- got first error I mentionned

**Comment by drasticactions** [comment]
You need to create a repro project. This helps by removing chances of ambiguity and a way for both of us to verify that the changes work. I know it seems obvious to do, but it really helps.

**Comment by guyvaio** [comment]
Repro project attached
[TestMauiAppWin.zip](https://github.com/dotnet/maui/files/11420827/TestMauiAppWin.zip)

**Comment by drasticactions** [comment]
I apologize; I should have specified this: Can you make this a public repo on GitHub or another source repository?

**Comment by mattleibow** [comment]
I am not sure we support this on .NET 7. What happens if you target .NET 8?

**Comment by guyvaio** [comment]
As mentioned in my first post : .net 7.0

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Can repro on Windows platforms with repro steps.
![image](https://github.com/dotnet/maui/assets/77434865/b4e68abc-aeb6-4b16-97df-32ddc818373d)

**Comment by guyvaio** [comment]
Not solved in Visual Studio 17.9.6

**Comment by mattleibow** [comment]
This happens with a plain WinUI app and I think this is all because we have conflicting compilers for XAML. We have MAUI, WinUI 3 and WPF all trying to build. Adding UseWindowsForms should be OK, but then it detects XAML and goes off on a error spree.

I don't think these are all meant to work together, and if they are, they were never tested as such. With MAUI and WPF/WinUI maybe we could get by as we have a MauiXaml build action, but _both_ WPF and WinUI use Page, so this means it will never work without great effort.

Please open a bug for WinUI and WPF to address.
