### ISSUE TITLE
MAUI project templates use latest C# language idioms

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/maui#1497]
In .NET 6, the included C# project templates will use the latest language idioms.

See the [parent Epic](https://github.com/dotnet/templating/issues/3359) for details.

@mhutch

**Comment by mhutch** [comment]
Note that this depends on adding global usings (https://github.com/dotnet/sdk/pull/18459).

**Comment by mhutch** [comment]
Depends on:

- [ ] https://github.com/dotnet/sdk/pull/18459
- [ ] https://github.com/dotnet/maui/issues/1564
- [ ] https://github.com/xamarin/xamarin-android/issues/6075
- [ ] https://github.com/xamarin/xamarin-macios/issues/12084
