### ISSUE TITLE
XamlCompilation attribute does not work (Windows 10 for sure, possibly Windows 11 too) for xaml files in Platform -> Windows. "IN RELEASE MODE"

### ISSUE THREAD

**Issue by KCarterSr** [dotnet/maui#14981]
### Description

XamlCompilation attribute does not work (Windows 10, possibly Windows 11) for xaml files in Platform -> Windows. "IN RELEASE MODE"

### Steps to Reproduce

1. Create a new Maui App in Visual Studio 2022 (Windows 10) using .Net MAUI App template.
2.  Annotate with [assembly: XamlCompilation(XamlCompilationOptions.Compile)] in MauiProgram.cs
3.  Using any decompiler (dotpeek, justdecompile, etc..), I'm using dnspy, and look at,  bin\Release\net7.0-windows10.0.............\win10-x64\MauiApp.dll
4. Look at the decompiled code for initializeComponent()
5. For the xaml files outside of the Windows platform folder the decompiled code is available as it should be. For xaml files (App.xaml.cs, etc..) in the Platforms/Window, the decompiled code only shows,
```
.........
.........
........
	Uri resourceLocator = new Uri("ms-appx:///Platforms/Windows/App.xaml");
	Application.LoadComponent(this, resourceLocator);
........
.......
........
```

Here is my workload.
```
Installed Workload Id      Manifest Version       Installation Source
--------------------------------------------------------------------------------
ios                        16.2.2054/7.0.100      SDK 7.0.200, VS 17.5.33530.505
maccatalyst                16.2.2054/7.0.100      SDK 7.0.200, VS 17.5.33530.505
maui-android               7.0.81/7.0.100         VS 17.5.33530.505
android                    33.0.46/7.0.100        VS 17.5.33530.505
wasm-tools                 7.0.5/7.0.100          VS 17.5.33530.505
maui-windows               7.0.81/7.0.100         VS 17.5.33530.505
maui-maccatalyst           7.0.81/7.0.100         VS 17.5.33530.505
maui-ios                   7.0.81/7.0.100         VS 17.5.33530.505
```
### Link to public reproduction project repository

Not available

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

NONE

**Comment by mattleibow** [comment]
`[XamlCompilation]` does not apply to WinUI XAML, only MAUI XAML.
