### ISSUE TITLE
MAUI - File picker - option to only to choose file and no more

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#14992]
### Description

Please see :
https://learn.microsoft.com/en-us/answers/questions/1275421/maui-file-picker-option-to-only-to-choose-file-and
There is no option to choose file and no more

[Yonglun Liu (Shanghai Wicresoft Co,.Ltd.) ](https://learn.microsoft.com/en-us/users/na/?userid=994fd0f3-fc7a-4621-a8a9-6e3cce0b5bdc)• 
Follow
15,726 Reputation points• Microsoft Vendor
May 9, 2023, 9:20 AM
I've tested it by following the steps in the[ Create a custom control using handlers](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/create?view=net-maui-7.0) documentation, but FilePicker doesn't provide an API or interface in the base classes for each platform that restricts users from picking files.

For your issue, it is more recommended to post your issue on [maui - issues](https://github.com/dotnet/maui/issues) to make our product group aware of this feature request.

### Steps to Reproduce

...

### Link to public reproduction project repository

...

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

...

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by danies8** [comment]
Any solution ?

**Comment by mattleibow** [comment]
As Rob mentions in the linked forum, there is no way to customize the picker as this is an OS feature. However, if you want to really restrict the picker, you may have to make your own using a new page and reading the files on the file system.

None of the platforms really allow for much customization of the system dialogs, but in your case you may actually just be looking for an in-app file picker that can be created using the `File` and `Directory` features. This is more work and requires extra things, but may also be better if you are really wanting to make a read-only picker.
