### ISSUE TITLE
[Bug] Setting a MAUI Window with a new page doesn't change to the new page.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#1500]
### Description

A MAUI Window has a settable `Page` parameter. If you try to set it from within an existing page (Either by calling the top parent as I do here, or potential through dependency injection), nothing seems to happen. If you notice, the Live Visual Tree does update with the new page, and we do receive VisualTree Change events showing that _something_ happened, but it's not reflected in the running application.

My expectation would either be that you _can't_ replace the existing Window's page, or that if you do, it updates to the new page. 

### Steps to Reproduce

1. Check out [this project](https://github.com/drasticactions/MauiFormsApp/tree/ee22515a187229c5523e78b6203281d3680f0b54)
2. Build, deploy, and click "Replace Window with Second page"

### Expected Behavior

The Window's contents change to reflect the new page.

### Actual Behavior

Nothing happens.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

https://user-images.githubusercontent.com/898335/123885535-a4f81c00-d91b-11eb-8868-36795780da63.mp4

**Comment by Redth** [comment]
@mattleibow thoughts on this? especially wrt your Window PR #1468

**Comment by mattleibow** [comment]
Oh... My PR might just solve that. I'll test.

**Comment by mattleibow** [comment]
Yep, I see my PR did not do that correctly because I did it wrong. But I just fixed it :) So... "Yeah of course. We _just_ added that feature to the new preview." 🤣

**Comment by drasticactions** [comment]
Trying this with `6.0.100-rc.1.1310` in main, it appears to be fixed. After pushing the page on the window, we get the proper events and the live visual tree propagates, and the page actually changes in the app.
