### ISSUE TITLE
Button not honoring MaximumWidthRequest on iOS, Mac, and Android

### ISSUE THREAD

**Issue by jknaudt21** [dotnet/maui#15002]
### Description

Creating a button with a `MaximumWidthRequest` does not cap the button's width. Only setting a fixed `WidthRequest` seems to affect the width.

Below are the screenshots of this code 
```xaml
    <StackLayout>
            <Button Text="Some random text that I've typed to occupy space"
                    BackgroundColor="AliceBlue"
                    TextColor="Black"
                    MaximumWidthRequest="100"
                    />
    </StackLayout>
```

Mac
<img width="988" alt="image" src="https://github.com/dotnet/maui/assets/32918747/0977a4f2-2bac-4ad4-a76e-17469db09c21">

iOS 
<img width="428" alt="image" src="https://github.com/dotnet/maui/assets/32918747/27f9e232-96a2-44e8-99ad-2fc598b3925d">

Android 
<img width="414" alt="image" src="https://github.com/dotnet/maui/assets/32918747/b05b81d0-ecd1-4ded-a3c5-3f9d9d1fd023">

### Expected
The button should be a lot smaller and not occupy the entire screen. Changing `MaximumWidthRequest` to simply `WidthRequest`  creates small buttons like so:
<img width="409" alt="image" src="https://github.com/dotnet/maui/assets/32918747/4b0835a9-d210-49f5-ac50-970e14e2b403">

### Steps to Reproduce

1. Build MAUI using main
2. Add this button to the sandbox:
```xaml
    <StackLayout>
            <Button Text="Some random text that I've typed to occupy space"
                    BackgroundColor="AliceBlue"
                    TextColor="Black"
                    MaximumWidthRequest="100"
                    />
    </StackLayout>
```
3. Deploy and observe results 

### Link to public reproduction project repository

(see description)

### Version with bug

8.0 previews

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

iOS, MacCatalyst, Android

### Did you find any workaround?

Use `WidthRequest` instead of `MaximumWidthRequest`.

**Comment by mattleibow** [comment]
Does this issue also appear with a Grid or if you use a Entry?

**Comment by jknaudt21** [comment]
@mattleibow yes, the issue still repros with grid or entry. I'm working on the fix at the moment, so a PR should (hopefully) be coming soon! :)

PS: The issue was in LayoutExtensions
