### ISSUE TITLE
BindableLayout placed inside Border does not render elements correctly on iOS.

### ISSUE THREAD

**Issue by cat0363** [dotnet/maui#15025]
### Description

Layout as below to reproduce the problem.

    <Border Grid.Row="1" Grid.Column="0" Stroke="Gray" StrokeShape="RoundRectangle 10,10,10,10" StrokeThickness="1" Margin="10">
        <ScrollView x:Name="svTestItems1" Orientation="Vertical">
            <StackLayout x:Name="slTestItems1" Orientation="Vertical">
                <BindableLayout.ItemTemplate>
                    <DataTemplate>
                        <Grid HeightRequest="44">
                            <Label Text="{Binding ItemName}" TextColor="Black" FontSize="18" VerticalOptions="Center" HorizontalOptions="Start" />
                        </Grid>
                    </DataTemplate>
                </BindableLayout.ItemTemplate>
            </StackLayout>
        </ScrollView>
    </Border>

For comparison, I also tried the following layout without a border.

    <ScrollView Grid.Row="1" Grid.Column="1" x:Name="svTestItems2" Orientation="Vertical">
        <StackLayout x:Name="slTestItems2" Orientation="Vertical">
            <BindableLayout.ItemTemplate>
                <DataTemplate>
                    <Grid HeightRequest="44">
                        <Label Text="{Binding ItemName}" TextColor="Black" FontSize="18" VerticalOptions="Center" HorizontalOptions="Start" />
                    </Grid>
                </DataTemplate>
            </BindableLayout.ItemTemplate>
        </StackLayout>
    </ScrollView>

Bind data with 10 elements to ItemSource of BindableLayout.

[Result of layout wrapped with Border]
Although the number of elements is 10, only 5 elements that fit in the display range are displayed by scrolling.
The left side of the video shown below is the execution result.

[Result of layout not wrapped in border]
Elements that do not fit in the display range are drawn correctly by scrolling.
The right side of the video shown below is the execution result.

[Execution result video on iOS]

https://github.com/dotnet/maui/assets/125236133/0efa3745-a96a-4779-922c-994b352bd703

[Execution result video on Android]

https://github.com/dotnet/maui/assets/125236133/b5d9f506-ac67-4a3e-a337-f14ff208c5ad

I expected all elements to be rendered by the scroll operation, whether or not they are wrapped in a border.
On Android it's rendering as intended.

Additional Information:
There is a problem that the height of StackLayout placed in ScrollView is not reflected correctly, 
and the following method reported in another Issue has been applied.

    slTestItems1.SizeChanged += (object sender, EventArgs e) =>
    {
        (svTestItems1 as IView).InvalidateMeasure();
    };

### Steps to Reproduce

The steps to reproduce are as follows.

1. Launch the app uploaded to github on your iOS
2. Vertically scrolls the ScrollView in the left Border layout

In step 2, up to the 5th element is displayed, but the 6th and subsequent elements are not displayed.

### Link to public reproduction project repository

https://github.com/cat0363/Maui-IssueBorder.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

### Did you find any workaround?

StrokeThickness cannot be specified, but it can be avoided by using Frame instead of Border.
However, on iOS the Frame's IsClippedToBounds value must be set to True. Because Android 
clips with the default value, but iOS does not clip with the default value.

**Comment by cat0363** [comment]
Added missing parts uploaded to github.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on iOS 16.4, not repro on Windows 11 and Android 13.0-API33 with below Project:
[Maui-IssueBorder.zip](https://github.com/dotnet/maui/files/11998410/Maui-IssueBorder.zip)

![image](https://github.com/dotnet/maui/assets/97647558/f8324fb6-213b-42d7-8993-74d49b750895)

**Comment by cat0363** [comment]
I can confirm that the problem does not reproduce with the latest source code.
Below are the verification results.

https://github.com/dotnet/maui/assets/125236133/5b576c6d-c9f8-403d-96fc-60087d16bd32

Thank you for addressing this issue.
