### ISSUE TITLE
Frame's IsClippedToBounds default value behavior is incorrect on Android.

### ISSUE THREAD

**Issue by cat0363** [dotnet/maui#15029]
### Description

Even though I didn't explicitly specify the IsClippedToBounds value for Frame, 
it behaves as True on Android.

I tested with the following layout.

    <Grid RowDefinitions="*,150,*" ColumnDefinitions="*,150,*">
        <Frame x:Name="frm" Grid.Row="1" Grid.Column="1" CornerRadius="20" HasShadow="False" Padding="0">
            <Grid BackgroundColor="SkyBlue" />
        </Frame>
    </Grid>

[Android]

![Screenshot_1683783027](https://github.com/dotnet/maui/assets/125236133/056aae33-6be4-485e-9649-06f722ed2bdf)

[iOS]

![2023-05-11_02-36-41-午後](https://github.com/dotnet/maui/assets/125236133/6a866929-d5bd-43cf-abbb-eb6604761c91)

I checked the default value after calling the InitializeComponent method and it is False for both Android and iOS.
Android behavior seems to be incorrect. I was expecting non-clipped behavior because Frame's IsClippedToBounds 
default value is False.

### Steps to Reproduce

The steps to reproduce are as follows.

1. Launch the app uploaded to github on your Android

In step 1, the Grid clipped by Frame is drawn on the screen.

### Link to public reproduction project repository

https://github.com/cat0363/Maui-IssueFrameClip.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11.0

### Did you find any workaround?

Explicitly specify a value for IsClippedToBounds.

**Comment by cat0363** [comment]
This issue was resolved by making the following changes.

[src\Controls\src\Core\Compatibility\Handlers\Android\FrameRenderer.cs]

    void UpdateClippedToBounds()
    {
        if (Element == null)
            return;

        var shouldClip = Element.IsClippedToBoundsSet(Element.IsClippedToBounds);

        this.SetClipToOutline(shouldClip);
    }

The shouldClip value setting was as follows before the change.

    var shouldClip = Element.IsClippedToBoundsSet(Element.CornerRadius > 0f);

Intentionally not setting the value of the Frame's IsClippedToBounds property in XAML is 
equivalent to setting the IsClippedToBounds property to True if the Frame's CornerRadius 
is greater than 0.

For this reason, when the IsClippedToBounds property of Frame was intentionally not set 
in XAML, there was a difference in display between iOS and Android.

Could you please check it? Thank you.

**Comment by cat0363** [comment]
However, in the current iOS source code, if the IsClippedToBounds property value of Frame is not explicitly specified, 
it behaves the same as if the IsClippedToBounds property value is True. By the way, the initial value of IsClippedToBounds is 
False if you don't explicitly specify a value for the Frame's IsClippedToBounds property. So clipping is not the intended 
behavior.

If you modify it in the same way as the Android side, the iOS side will be as follows.
Some of the code below is omitted.

[src\Controls\src\Core\Compatibility\Handlers\iOS\FrameRenderer.cs]

    public virtual void SetupLayer()
    {
        omit ...

        _actualView.Layer.RasterizationScale = UIScreen.MainScreen.Scale;
        _actualView.Layer.ShouldRasterize = true;
        _actualView.Layer.MasksToBounds = Element.IsClippedToBounds;         <= Modify
    }

Before the change, the code looked like this:

    _actualView.Layer.MasksToBounds = Element.IsClippedToBoundsSet(true)

From the above, the execution results for Android and iOS are as follows.

[Android IsClippedToBounds unspecified]

![Screenshot_1687765914](https://github.com/dotnet/maui/assets/125236133/b96cd6b2-8b32-43a2-8ab2-c09540825bda)

[Android IsClippedToBounds = "True"]

![Screenshot_1687765925](https://github.com/dotnet/maui/assets/125236133/e9a8000c-24d8-4757-b7b7-c7d84173b40c)

[Android IsClippedToBounds = "False"]

![Screenshot_1687765934](https://github.com/dotnet/maui/assets/125236133/a777cbe4-6249-420e-9bca-b8be43b1c7e3)

[iOS IsClippedToBounds unspecified]

![2023-06-26_04-37-52-午後](https://github.com/dotnet/maui/assets/125236133/88c79087-c47e-4d6f-aba8-9fb92a502153)

[iOS IsClippedToBounds = "True"]

![2023-06-26_04-37-41-午後](https://github.com/dotnet/maui/assets/125236133/fb586a17-8f14-4d61-b049-946bf6cccc4d)

[iOS IsClippedToBounds = "False"]

![2023-06-26_04-37-23-午後](https://github.com/dotnet/maui/assets/125236133/569eaca3-f2ca-4f02-b080-fdedb5566fa2)

**Comment by cat0363** [comment]
In PR #11352, the default value is true when the IsClippedToBounds property value on the iOS side is not set, but the default value when the IsClippedToBounds property value is not set on the Android side is Element.CornerRadius > 0f.

Why is the concept of default values ​​different for iOS and Android?

Assuming that the default value of IsClippedToBounds property is true, the default value of IsClippedToBoundsProperty of Layout class should be as follows.

[src\Controls\src\Core\Layout.cs]

    public static readonly BindableProperty IsClippedToBoundsProperty =
        BindableProperty.Create(nameof(IsClippedToBounds), typeof(bool), typeof(Layout), true,
            propertyChanged: IsClippedToBoundsPropertyChanged);

However, the status quo is false. Both iOS and Android are different from the default value of IsClippedToBoundsProperty.

If you consider the value of Layout.IsClippedToBounds as the default value, then the following is correct.

[src\Controls\src\Core\Compatibility\Handlers\Android\FrameRenderer.cs]

    void UpdateClippedToBounds()
    {
        if (Element == null)
            return;

        var shouldClip = Element.IsClippedToBoundsSet(Element.IsClippedToBounds);

        this.SetClipToOutline(shouldClip);
    }

[src\Controls\src\Core\Compatibility\Handlers\iOS\FrameRenderer.cs]

    public virtual void SetupLayer()
    {
        omit ...

        _actualView.Layer.RasterizationScale = UIScreen.MainScreen.Scale;
        _actualView.Layer.ShouldRasterize = true;
        _actualView.Layer.MasksToBounds = Element.IsClippedToBoundsSet(Element.IsClippedToBounds);
    }

At least the current behavior does not correctly reflect the default value of IsClippedToBoundsProperty.

**Comment by samhouts** [comment]
Following the conversation on the associated PR, it seems like this needs to be a documentation update, is that right? Thanks!

**Comment by cat0363** [comment]
@samhouts , Document modifications are required as described below.
I've requested a correction to the document, but I don't know the status after that.

https://github.com/dotnet/maui/pull/15894#issuecomment-1623889725

**Comment by jfversluis** [comment]
Seeing that Frame is officially deprecated as of .NET 9, I don't think we will be working on this anymore. Also its a bit older by now, so maybe its even resolved in current versions 🤞
