### ISSUE TITLE
ContentProperty leads to XamlC error XFC0009 while compiling

### ISSUE THREAD

**Issue by JPZV** [dotnet/maui#15061]
### Description

I'm trying to make a new control using ContentView, but every time I try to set the ContentProperty, it fails with the error `XamlC error XFC0009`.

I even deleted everything leaving just a Grid and the BindingProperty, but I cannot make it work either.

This is the code:

`SectionView.xaml`

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MyApp.Controls.SectionView">

    <Grid> <!-- Line 6 -->
    </Grid>
</ContentView>
```

`SectionView.xaml.cs`

```cs
namespace MyApp.Controls;

[ContentProperty(nameof(Fire))]
public partial class SectionView : ContentView
{
    public static readonly BindableProperty FireProperty = BindableProperty.Create(nameof(Fire), typeof(string), typeof(SectionView));

    public string Fire
    {
        get => GetValue(FireProperty) as string;
        set => SetValue(FireProperty, value);
    }
    
    public SectionView()
    {
        InitializeComponent();
    }
}
```

The only workaround is to delete `[ContentProperty(nameof(Fire))]` and assign the value explicitly

### Steps to Reproduce

1. Clone the reproduction project repository and open it on Visual Studio
2. Click on Build -> Build Solution

**Expected behavior**: It should build successfully

**Actual behavior**: It fails with `Controls\SectionView.xaml(6,6): XamlC error XFC0009: No property, BindableProperty, or event found for "Fire", or mismatching type between value and property.`

### Link to public reproduction project repository

https://github.com/JPZV/ContentPropertyIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Not relevant

### Did you find any workaround?

The only workaround is to delete `[ContentProperty(nameof(Fire))]` and assign the value explicitly while implementing the Control. E.g.

```xaml
<controls:SectionView Fire="Test">
</controls:SectionView>
```

Instead of

```xaml
<controls:SectionView>
    Test
</controls:SectionView>
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[ContentPropertyIssue.zip](https://github.com/dotnet/maui/files/12011283/ContentPropertyIssue.zip)
