### ISSUE TITLE
Impossible to use MAUI win app outside of Visual Studio

### ISSUE THREAD

**Issue by guyvaio** [dotnet/maui#15067]
### Description

App runs well in Visual Studio debug mode but is not usable in real production environment.

### Steps to Reproduce

Steps to reproduce:
1) create new .NET MAUI (regular or Blazor) App from VS 17.5.5
2) In the project set <TargetFrameworks>net7.0-windows10.0.19041.0</TargetFrameworks> only
3) Compile -> OK
4) Go to bin\Debug\net7.0-windows10.0.19041.0\win10-x64 folder and start MauiApp3.exe -> app crashes "DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: Le module spécifié est introuvable. (0x8007007E)
"
Tried 2nd solution : publishing
1) On project, choose Publish
2) Choose "Slideloading"
3) Skip signing (but same result if signed)
4) Select "neutral" "Release Any CPU"
Error : The target "_GenerateAppxPackage" does not exist in the project.

### Link to public reproduction project repository

https://github.com/jefh531/repos/tree/main/MauiApp3

### Version with bug

6.0.312

### Last version that worked well

7.0 (current)

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

No.
A lot of time passed on Google (many unsolved issues seen) for a manipulation that should be simple.

**Comment by drasticactions** [comment]
MAUI uses WinUI Packaged Mode for its application deployment. So trying to run the debug build outside of Visual Studio won't work, you need to package it.

There is documentation for how to publish a MAUI WinUI app for sideloading: https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/overview, did you run through these steps?

**Comment by guyvaio** [comment]
Yes I did try a publish.
At step "Select the Publishing profile drop-down and select <New...>", I do not see any combo "Publish profile" with "New". I see "Select the package to create and the solution configuration mappings". I select "neutral" and "release any cpu". When I click on "Create", I receive 
The target "_GenerateAppxPackage" does not exist in the project.

**Comment by Eilon** [comment]
@guyvaio - can you also confirm whether the same thing happens in a regular .NET MAUI project (without Blazor)? That will help us narrow down where the issue is.

**Comment by guyvaio** [comment]
Same error on a fresh new .NET MAUI project (without Blazor). Publish -> The target "_GenerateAppxPackage" does not exist in the project.

**Comment by guyvaio** [comment]
Publish eventually successful with command line:
dotnet publish -f "net7.0-windows10.0.19041.0"  -c Release /p:Platform="x64"

**Comment by Eilon** [comment]
> Same error on a fresh new .NET MAUI project (without Blazor). Publish -> The target "_GenerateAppxPackage" does not exist in the project.

Thanks, I updated the title and repro steps to indicate it happens with both regular and Blazor projects.

**Comment by ErikSJan** [comment]
I reached the same point as @guyvaio if I try to modify the project file by hand.
But even if you do all the operations through the GUI then there is still and error.
The steps to reproduce are:
- create a new .NET MAUI App with .NET 7.0 framework
- publish the application without any modification, the publish wizard will ask for a new MSIX publish profile:
![Create a new MSIX Publish Profile](https://github.com/dotnet/maui/assets/14327592/6aed7851-6522-44a2-82fe-08ea3167a543)
Everything works fine and you have a valid MSIX file in the directory you choosed.

At this step, you can remove android target using the project properties in the GUI and it will still publish.

- remove iOS target from the project property.
   Note that this will at once display a warning saying that the modification of the project cannot be taken into account directly and you must reload the project.
![Without iOS target](https://github.com/dotnet/maui/assets/14327592/417aee7d-511f-4547-927b-2f2c2c17410e)
- save the project and click on reload
- try to publish the project and now you will have a different panel for the profile:
![Select and configure packages after iOS removal](https://github.com/dotnet/maui/assets/14327592/a1a0f4a3-97e1-4697-ae60-978e5078f0ec)
Note that you must create by hand the output location.
Proceed with the rest of the process and then you have the following error:
> Build started...
> 1>------ Build started: Project: MauiApp3, Configuration: Debug Any CPU ------
> 1>MauiApp3 -> C:\Users\User\source\repos\MauiApp3\bin\Debug\net7.0-maccatalyst\maccatalyst-x64\MauiApp3.dll
> 1>MauiApp3 -> C:\Users\User\source\repos\MauiApp3\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\MauiApp3.dll
> 1>The package MauiApp3.1.0.0 is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package readmes are important.
> 1>Successfully created package 'C:\Users\User\source\repos\MauiApp3\bin\Debug\MauiApp3.1.0.0.nupkg'.
> ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
> ========== Build started at 1:49 PM and took 07,298 seconds ==========
> A package has been successfully built for Debug (Any CPU).
> ========== Package: 1 succeeded, 0 failed ===========
> Start copying from output to installer location.
> Error: Failed to copy. Object reference not set to an instance of an object.

I hope this will help to solve this issue.

The workaround proposed by @guyvaio doesn't work if there are COM libraries referenced by the project as the dotnet publish doesn't accept this.

**Comment by ErikSJan** [comment]
Note that as a result of this problem if you can't have iOS target activated because you use COM libraries or other functionnalities that are not available in iOS then you can't publish the MAUI app on Windows.

**Comment by summitabrown** [comment]
So is this issue not going to get fixed? I can't publish a windows app for sideloading using MAUI

**Comment by jfversluis** [comment]
Publishing unpackaged apps is supported and how to do it can be found here: https://learn.microsoft.com/dotnet/maui/windows/deployment/publish-unpackaged-cli?view=net-maui-8.0

If something doesn't seem to work correctly with that from the Visual Studio UI, please report it through the above proces. Thank you!

**Comment by flaubertagu** [comment]
Hi,
I had the same issue on .net Maui (not Blazor). Here is the original post => https://developercommunity.visualstudio.com/t/Impossible-to-publish-net-MAUI-windows-/10577729?viewtype=all
I found a way to publish in sideload. May be it could be of help.

1. Create a self-sign certificate
You can use the method is the following link https://learn.microsoft.com/fr-fr/dotnet/maui/windows/deployment/publish-cli?view=net-maui-8.0

2. Add the following code in your .csproj file
`
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows' and '$(Configuration)' == 'Release'">
		<AppxPackageSigningEnabled>true</AppxPackageSigningEnabled>
		<PackageCertificateThumbprint>YOURTHUMBPRINTHERE</PackageCertificateThumbprint>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows' and '$(RuntimeIdentifierOverride)' != ''">
		<RuntimeIdentifier>$(RuntimeIdentifierOverride)</RuntimeIdentifier>
	</PropertyGroup>
...
</Project>`

3. Do not change the classic TargetFrameworks in your .csproj file
`<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>`

4. Save the .csproj file and rebuild the project in release mode.
5. If you are using visual studio, click on tool andopen cmd. Then cd to the project solution
6. Enter the command => dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64
It will rebuild your project and the project references associated to .net MAUI
Hope this will help to solve the issue.
