### ISSUE TITLE
[Bug] Loaded images have no size

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1506]
### Description

In XF when I load an image from a URL or locally, it sizes and displays the image.

```xaml
<FlexLayout Direction="Column"
                AlignItems="Center"
                JustifyContent="SpaceEvenly">
        
        <Label Text="FlexLayout in Action"
               FontSize="Large" />

        <Image Source="https://raw.githubusercontent.com/xamarin/docs-archive/master/Images/stock/small/IMG_2371.JPG"/>

        <Button Text="Do-Nothing Button" />

        <Label Text="Another Label" />
    </FlexLayout>
```

![Screenshot_1625060547](https://user-images.githubusercontent.com/41873/123970966-3cdb2180-d97f-11eb-9302-8068c423f62b.png)

In maui it does not. I see no image unless I set some explicit width/height.

```xaml
<layouts:FlexLayout Direction="Column"
                AlignItems="Center"
                JustifyContent="SpaceEvenly">
        
        <Label Text="FlexLayout in Action"
               FontSize="Large" />

        <Image Source="https://raw.githubusercontent.com/xamarin/docs-archive/master/Images/stock/small/IMG_2371.JPG"
               WidthRequest="200"
               HeightRequest="200"
               />

        <Button Text="Do-Nothing Button" />

        <Label Text="Another Label" />
    </layouts:FlexLayout>
```

![Screenshot_1625060703](https://user-images.githubusercontent.com/41873/123971262-80ce2680-d97f-11eb-8558-016b28876d01.png)

### Expected Behavior

I get the same behavior as XF with some minimum sizing information on source loaded.

### Actual Behavior

The image is not visible until I set an explicit size.

### Basic Information

- Version with issue: preview 6

### Reproduction Link

https://github.com/davidortinau/ControlGallery/blob/flexlayout/src/ControlGallery/Pages/Flex/

**Comment by PureWeen** [comment]
Tested this on the latest MAUI and it looks like this is fixed

![image](https://user-images.githubusercontent.com/5375137/140566135-f98f3c6a-78ab-46ec-8342-ca9785bc183e.png)
