### ISSUE TITLE
Unable to debug iOS MAUI app

### ISSUE THREAD

**Issue by Ratnapriya** [dotnet/maui#15065]
### Description

iOS app debugging is not working on iPhone

### Tried deploying using 
1. windows VS + Mac combination.
2. Mac VS

Observation:
When the breakpoints are disabled or deleted the app attaches to the debugger but eventually crashes. Running the app without debugger does not crash.

### Relevant tickets found on maui github

https://github.com/dotnet/maui/issues/9056

https://github.com/dotnet/maui/issues/11324

https://learn.microsoft.com/en-us/answers/questions/1055443/net-maui-sample-project-does-not-up-before-ios-wat

Version: Visual Studio for Mac 17.5.4, also observed on Preview version 17.6

### Steps to Reproduce

Steps

Deploying using Windows VS + Mac combination.

1.Pair to MAC from Visual Studio
2. Add a breakpoint
3. Choose the remote device (iPhone 13 Pro iOS version 15.4.1)
4. Run the app in debugger
5. App terminates after loading assemblies.

When the app is run in the debugger, the app terminates right after loading the assemblies. The app can be launched and run on the device. Attaching to the debugger fails when breakpoints are enabled. Watchdog exceptions can be found in the device logs. Watchdog is terminating the app even before the debugger attaches.

Deploying directly from Mac, 

Version: Visual Studio for Mac 17.5.4, also observed on Preview version 17.6

Steps to reproduce:

1. Open app in Visual Studio for Mac
2. Clean/Build the app, observe successful cleans/build from the output
3. Start debugging app from Visual Studio for Mac onto physical device

Expected behavior:

1. The app gets installed on the phone while Visual Studio for Mac displays "Deploying to Device" then "Installing application bundle on device_name"
2. After installation, Visual Studio will connect to the debugger and the app will open on the phone
3. Normal debugging will begin in Visual Studio, with ability to step at breakpoints/step through code

Actual behavior:

1. The app gets installed on the phone while Visual Studio for Mac displays "Deploying to Device" then "Installing application bundle on device_name"
2. If the app is already installed, Visual Studio displays "Application already installed" on the bottom banner and does not open app or reinstall
3. After installation, Visual Studio simply displays "Upload Successful" on bottom banner, app does not open and debugger is not connected to Visual Studio
App runs fine if opened manually on phone, but debugging is not possible

### Link to public reproduction project repository

NA

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

XCode 14.3, Visual Studio 17.5.3

### Did you find any workaround?

No. Only option is to run without debugger.

**Comment by mariaghiondea** [comment]
We just released VS 17.6 GA. Could you try upgrading and letting us know if you are still having issues?

**Comment by Distinctlyminty** [comment]
I'm seeing this issue today using the latest stable release of visual studio Mac. Also can't debug in Jetbrains Rider so I think this probably is a Maui problem.

**Comment by mauroa** [comment]
Do you have the same problem with any MAUI app (even a blank new one) or only with your specific app? If the problem is specific to your app, is there any chance you can share it? You can open a Feedback ticket and attach the project privately. Please follow these steps to open the ticket: https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

Thanks

**Comment by Rabosa616** [comment]
I'm experiencing the same problem even with new app created with the VS default templates.
![image](https://github.com/dotnet/maui/assets/12774781/f6def6de-3c1f-430c-ba9a-038e60f78a41)

**Comment by ivanpovazan** [comment]
@Ratnapriya, I am trying to reproduce your issue and determine what is causing the crash you are experiencing, but with no luck.

Would it be possible for you (or other reporters of the same problem) to share the application which is causing the crash with the debugger?

Additionally, could you to repeat your steps and launch the debug session of your application, **but** without having the `Locals` window in focus (as shown in the attached screenshot where `Breakpoints` window is in focus, not `Locals`) ? 

<img width="1430" alt="Screenshot 2023-07-24 at 20 52 37" src="https://github.com/dotnet/maui/assets/55002338/aa91649d-bbfa-4519-8459-74bcb248071e">

**Comment by dimplevador** [comment]
@ivanpovazan I am facing the same issue. I cannot share the code but I can share the screenshot with breakpoints tab in focus that you asked for. The app crashes right after it hits the debug point.

![iOS-debugger-problem](https://github.com/dotnet/maui/assets/329829/61d02f30-4ac3-4f7b-8627-ac42c232ac94)

**Comment by samhouts** [comment]
Were you able to open a Visual Studio feedback ticket? Thanks!
