### ISSUE TITLE
[regression/7.0.86] On iOS grid rows that are set to star display as auto when view is added later that spans all rows and columns

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#15079]
### Description

After updating to 7.0.86 we are seeing an issue when adding a menu overlay to page grids.

The page overlay is effectively a menu system we are converting from Xamarin Forms where we detect the view the user has long tapped on and display an opaque view on top with a menu of options the user can perform.

The page grid is a simple enough layout, an auto row 0 (a toolbar), a star row 1 (for data), and auto row 2 (quick navigation options). Within row 1 we display another grid with 5 or 6 star rows, and each of those contains a scrollview. This allows the user to scroll data within each row if there is more information to display.

When adding the page overlay to the page grid we span all its columns and rows. Worked perfectly previously, but now all the rows within the page expand and display all the data within the scrollview as if they were auto.

### Steps to Reproduce

This will be a pain to create a repo, but Im happy to share video, screenshots, or even a TestFlight build to demo the issue.
I *could* at a push invite someone to the app repo in Azure DevOps but I will want to speak to someone first.

### Link to public reproduction project repository

Nope

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS all

### Did you find any workaround?

Previous Maui versions worked, so the latest grid fixes appear to have broken something else.
EDIT:
Adding `<MauiVersion>7.0.59</MauiVersion>` to the project and the grid behaves correctly.
7.0.86 fixes a lot of other layout issues btw.

**Comment by rmarinho** [comment]
@JohnHDev  anyway you can try isolate the issue, this seems a very specific scenario. Adding screenshots and videos of the behaviour or maybe just post some of the code you are using will help us a lot identifying the issue.

@hartez  anything that pops here about the weird behaviour ?

**Comment by samhouts** [comment]
same as or similar to #15018?

**Comment by samhouts** [comment]
There's a repro in #15085

**Comment by JohnHDev** [comment]
@samhouts could very well be related to #15085, good spot!

Im happy to try an updated handler if it helps debug the issue when its available.

**Comment by hartez** [comment]
This was fixed by https://github.com/dotnet/maui/pull/14176

**Comment by Hooterr** [comment]
So what that it's fixed in preview? It'll be available in November. PLEASE reopen this issue as it's critical and must be fixed ASAP.
