### ISSUE TITLE
Emoji Issue on Windows

### ISSUE THREAD

**Issue by codeaphex** [dotnet/maui#15077]
### Description

Emojis not correctly displayed in a Label on Windows.
There seem to be problems in other tools too, but its weird that just one arrow is correctly displayed in the windows label control and editor tab, while being correctly displayed on android and the editor content.

Windows:
![image](https://github.com/dotnet/maui/assets/39407721/1b74e9cf-79b8-452c-b5a3-e81e3feca32c)

Windows Default Editor (Notice the Title of the Editor Tab):
![image](https://github.com/dotnet/maui/assets/39407721/aecba8d0-54f4-4308-a820-7e274909b498)

Android:
![image](https://github.com/dotnet/maui/assets/39407721/9ae4af06-44b9-4188-a3af-554ec63f0874)

### Steps to Reproduce

1. Create a new MAUI project
2. Add Emoji-Arrows ⬆️↗️➡️↘️⬇️↙️⬅️↖️↕️
3. Start on Windows vs Android

### Link to public reproduction project repository

https://github.com/codeaphex/repro_maui_windows_emoji

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

11+

### Did you find any workaround?

No.

### Relevant log output

```shell
None.
```

> VS bug [#1819619](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1819619)

**Comment by drasticactions** [comment]
I believe this is WinUI, not MAUI Specific

<img width="576" alt="image" src="https://github.com/dotnet/maui/assets/898335/2f3358d9-f179-452e-9b6b-e4bb27656609">

https://github.com/drasticactions/MauiRepros/tree/main/EmojiLabelWinUI

You can replicate that with a straight WinUI Project and a TextBlock, which MAUI uses for its label.

I would ask in [microsoft-ui-xaml](https://github.com/microsoft/microsoft-ui-xaml) about this.

**Comment by Eilon** [comment]
Closing because this doesn't appear to be a .NET MAUI issue. This could be the same issue as discussed in https://github.com/microsoft/microsoft-ui-xaml/issues/6713. If not, please open a new issue in that repo.

**Comment by drasticactions** [comment]
Closing again, it should be related to https://github.com/microsoft/microsoft-ui-xaml/issues/6713.
