### ISSUE TITLE
Android: text color in buttons in alert dialog and picker dialog for default theme has very low contrast in dark mode

### ISSUE THREAD

**Issue by webwarrior-ws** [dotnet/maui#15088]
### Description

The text color in buttons in alert dialog for an Android app (maui app with default theme styles removed) is dark, which makes it very low contrast in dark mode and makes it unreadable.

### Steps to Reproduce

1. Create new MAUI app, HelloWorld app, from template.
2. Delete all styles from the template.
3. Create simple form in a simple page with a button that opens Alert dialog on click.
Run it in dark mode and open dialog, result:
![alertDialog-before-simple-dark](https://github.com/dotnet/maui/assets/6537039/4e2c5138-76c7-4728-bf2b-e34504103d16)

Expected results: text in "Cancel"  button should create high contrast with background in both light and dark mode an be easily readable.

The same app in light mode (button text is clearly visible):

![alertDialog-before-simple-light](https://github.com/dotnet/maui/assets/6537039/cc933a2c-a8b6-4aa8-b9aa-a59d3e853f38)

### Link to public reproduction project repository

https://github.com/webwarrior-ws/TemplateMauiApp

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

any?

### Did you find any workaround?

Not removing the default theme from the template.

**Comment by duindain** [comment]
Can this be backported to .Net 7 please?
