### ISSUE TITLE
NavigationPage.ToolbarItems not shown on Android after Back key pressed

### ISSUE THREAD

**Issue by luwed** [dotnet/maui#15096]
### Description

I noticed that ToolbarItems are not shown if Back key pressed and then the app is moved to foreground. Please note that there is another similar issue which has been already fixed: https://github.com/dotnet/maui/issues/5031

### Steps to Reproduce

1. Create Maui app
2. Define MainPage in App.xaml.cs as:
```
    var rootPage = new MainPage();
    MainPage = new NavigationPage(rootPage);
```
3. Add ToolbarItem to MainPage.xaml:
```
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Test" />
    </ContentPage.ToolbarItems>
```
4. Run app on Android 11
5. Move app to background using Back key
6. Return to the app

Actual result:
ToolbarItem is not shown

Expected result:
ToolbarItem is shown

### Link to public reproduction project repository

https://github.com/luwed/maui-stuff/tree/toolbarItems-not-shown-Android-after-back-and-return-to-app

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Reconstruct ToolbarItems in OnAppearing.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Android 11.0-API30 with below Project:
[MauiProject.zip](https://github.com/dotnet/maui/files/12026431/MauiProject.zip)
