### ISSUE TITLE
Star columns not computed correctly when ScrollView spans across all of them

### ISSUE THREAD

**Issue by pikausp** [dotnet/maui#15105]
### Description

When I create a `Grid` with multiple star columns and put a `ScrollView` inside of it which spans across all of those columns, the columns don't have the appropriate width no matter the desired ratio.

```
<Grid RowDefinitions="Auto, *"
      ColumnDefinitions="*, 2*,3*">
    <Frame BackgroundColor="Red"/>
    <Frame BackgroundColor="Blue"
            Grid.Column="1"/>
    <ScrollView Grid.Row="1" Grid.ColumnSpan="3">
        <Frame BackgroundColor="Green"/>
    </ScrollView>
</Grid>
```
Produces the following
![image](https://github.com/dotnet/maui/assets/6717146/004c8bcc-df06-468c-a077-1f78f6237663)

Whereas leaving out one column (reducing the `ColumnSpan` to `2`) displays a layout I would expect
![image](https://github.com/dotnet/maui/assets/6717146/e46502b4-bb12-4372-ac7a-2d3219134dba)

### Steps to Reproduce

See the description/repo

### Link to public reproduction project repository

https://github.com/pikausp/GridStarColumnRepro

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by mattleibow** [comment]
This is fixed now in .NET 7 and .NET 8

<img width="416" alt="image" src="https://github.com/dotnet/maui/assets/1096616/99b3829c-a1c1-451c-a392-38956f90aab7">
