### ISSUE TITLE
Failed to AOT compile while building iOS IPA and using Microsoft.Maui.Essentials NuGet package in a class library

### ISSUE THREAD

**Issue by Jean-RochSDX** [dotnet/maui#15104]
### Description

While creating a Release IPA for iOS devices using the Microsoft.Maui.Essentials 8.0.0-preview.3.8149 NuGet package in a class library I get a "Failed to AOT compile" error.

Building the Debug version is on the other side working.

### Steps to Reproduce

1. Download repository
2. Update the "Bundle Identifier" name in Info.plist
3. Provide your signing identity and provisioning profile
4. Build IPA using the ReleaseError configuration

### Link to public reproduction project repository

https://github.com/Jean-RochSDX/MauiAotError

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Using the build property "UseMauiEssentials" as indicated in this [article ](https://learn.microsoft.com/en-us/dotnet/maui/migration/native-essentials?tabs=ios) solved the problem but I would have expected a more helpful error message or warning during the build process and to have a similar behavior while building both configurations ("Release" and "Debug").

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with VSM 17.6.7 (build 400). Can repro this issue with sample project.
![image](https://github.com/dotnet/maui/assets/77434865/4b37a871-b515-4fb6-8e6e-f8c90e9f6efc)
