### ISSUE TITLE
Filepicker doesn't work in sandbox mode (MacCatalyst)

### ISSUE THREAD

**Issue by petervaradi** [dotnet/maui#15129]
### Description

You can't release an app to Mac App Store if it's not in sandbox mode:
![8CDC2BDF-D973-4C77-ACF1-700EA1F41169](https://github.com/dotnet/maui/assets/2270218/2e4ad484-1fdb-4005-8270-49e2fceaf36a)
https://developer.apple.com/documentation/security/app_sandbox
"To distribute a macOS app through the Mac App Store, you must enable the App Sandbox capability."

If I enable the sandbox mode with Entitlements.plist

```
    <key>com.apple.security.app-sandbox</key>
    <true/>
```
then the FilePicker won't even open. 

### Steps to Reproduce

1. Create a new .Net MAUI App on Mac in Visual Studio.
2. Create an Entitlements.plist and add this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
  </dict>
</plist>
```
3. In the MainPage.xaml.cs add the following (to the sample button handler OnCounterClicked:
```
var result = await FilePicker.Default.PickAsync();
if (result != null)
{
    int u = 0;  
}
```
Click on the button on the sample app. Nothing happens. The app freezes. 

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

macOS

### Affected platform versions

macOS Ventura 13.3.1 x64

**Comment by petervaradi** [comment]
I will answer my own question. 
According Apple:
https://developer.apple.com/documentation/xcode/configuring-the-macos-app-sandbox/
You can add these folder access elements to the entitlements.plist

```
	<key>com.apple.security.assets.movies.read-only</key>
	<true/>
	<key>com.apple.security.assets.music.read-only</key>
	<true/>
	<key>com.apple.security.assets.pictures.read-only</key>
	<true/>
	<key>com.apple.security.files.downloads.read-only</key>
	<true/>
	<key>com.apple.security.files.user-selected.read-only</key>
	<true/>
	<key>com.apple.security.personal-information.photos-library</key>
	<true/>
```

Then the FilePicker will work again in sandbox mode too, and let you pick a file. 

It might be worth mentioning this in the FilePicker docs for Maui. 

I found another issue with FilePicker:
https://github.com/dotnet/maui/issues/15126

**Comment by PureWeen** [comment]
> I will answer my own question. According Apple: https://developer.apple.com/documentation/xcode/configuring-the-macos-app-sandbox/ You can add these folder access elements to the entitlements.plist
> 
> ```
> 	<key>com.apple.security.assets.movies.read-only</key>
> 	<true/>
> 	<key>com.apple.security.assets.music.read-only</key>
> 	<true/>
> 	<key>com.apple.security.assets.pictures.read-only</key>
> 	<true/>
> 	<key>com.apple.security.files.downloads.read-only</key>
> 	<true/>
> 	<key>com.apple.security.files.user-selected.read-only</key>
> 	<true/>
> 	<key>com.apple.security.personal-information.photos-library</key>
> 	<true/>
> ```
> 
> Then the FilePicker will work again in sandbox mode too, and let you pick a file.
> 
> It might be worth mentioning this in the FilePicker docs for Maui.
> 
> I found another issue with FilePicker: #15126

@davidbritch

**Comment by davidbritch** [comment]
@PureWeen You can close here now. It's done via https://github.com/dotnet/docs-maui/pull/1494
