### ISSUE TITLE
Button isenabled not working

### ISSUE THREAD

**Issue by NicolaZuc** [dotnet/maui#15127]
### Description

I was trying to use the disabled feature on buttons with mvvm commands when i noticed it wasn't working.
I've then found that it doesn't work even when using the isenabled property attacched to the button.
Neither text or background changes when button is disabled.
The button itself is disabled but graphically it doesn't change

### Steps to Reproduce

Xaml:
```
<ContentPage
    x:Class="repro.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    <Button
        Background="Green"
        IsEnabled="False"
        Text="Press me"
        TextColor="Black" />
</ContentPage>
```

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 10

**Comment by NicolaZuc** [comment]
> @NicolaZuc I'm guessing you need to apply a VisualStateManager in order to change the color when `disabled`
> 
> if you check the MAUI templates, we include a large set of default styles you can use.

Visual state manager is not working for me, as i've already reported  in #15055

**Comment by SagarPanwala** [comment]
I do have same bug with buttons.

**Comment by jared-ca** [comment]
Could be a completely different thing but I had a similar issue and it only occurred when I had a Command bound to the button. With a command bound MAUI would ignore the IsEnabled property.

I suspect the reason is that the ICommand interface has a CanExecute method which is overriding the IsEnabled prop, by implementing CanExecute properly the button was correctly disabled.

**Comment by mattleibow** [comment]
@jared-ca  that issue was finally fixed in https://github.com/dotnet/maui/pull/12488
