### ISSUE TITLE
Windows emptyView text has different default placement

### ISSUE THREAD

**Issue by marekm294** [dotnet/maui#15131]
### Description

All 3 platforms place emptyView text to center of collectionView by default. Windows places it on top.
![iOS](https://github.com/dotnet/maui/assets/108216731/cb634ced-45c7-4eab-b5ec-1e9792619062)
![Mac](https://github.com/dotnet/maui/assets/108216731/0c2661ad-358a-47ce-abf9-ef4c701b531d)
<img width="958" alt="Windows" src="https://github.com/dotnet/maui/assets/108216731/c1b84983-877b-4ca3-ac39-53ab90e8a05b">
![Android](https://github.com/dotnet/maui/assets/108216731/130f5349-2dbe-4f4b-b33b-7143c593d0ad)

### Steps to Reproduce

    <Grid>
        <CollectionView EmptyView="Empty collection" BackgroundColor="Beige"/>
    </Grid>

### Link to public reproduction project repository

*

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 3.0. This issue repro on Windows 11 on .NET 7, not repro on Windows 11 on .NET 8 with below Project:

**.NET 7:**
![image](https://github.com/dotnet/maui/assets/97647558/2c05760d-1087-41bf-99ed-901f3feac8d6)
**.NET 8:**
![image](https://github.com/dotnet/maui/assets/97647558/a547b38f-1c29-4b3b-af5b-ccf2af4e29dc)
