### ISSUE TITLE
Windows does not show datalist dropdown

### ISSUE THREAD

**Issue by farmergreg** [dotnet/maui#15136]
### Description

This has become a show stopper for my team.
When using a datalist on Windows, the datalist option values do not display at all. When the user clicks in the control and starts typing nothing happens.

The datalist has has worked for us since last fall when we started this project at work.  Unfortunately I do not know what version(s) worked. It broke for us only recently after installing updates. I verified that  datalist works correctly on Android in an emulator. Therefore this appears to be a Windows specific problem. 

On windows in the past, We've seen the drop down datalist values displayed at the wrong coordinates on screen. This happens when the main window is moved by the user. The datalist was drawn where the window originally opened instead of where the window is "now".  So I suspect this bug may be related - it may be possible that the datalist is being drawn somewhere that is not visible...

### Steps to Reproduce

Attach a datalist to an input control on any .net Maui blazor page.

Here is a working example:
https://github.com/farmergreg/maui-datalist-example/blob/master/MauiApp1/Pages/Index.razor

<input type="text" list="MyHtmlId-Auto-Complete-List" />
<datalist id="MyHtmlId-Auto-Complete-List">
    <option value="0123"></option>
    <option value="4321"></option>
</datalist>

Clicking in the above input control and typing "2" should show a drop down list with both options. On Windows 10 & 11, this no longer works. You should be able to see it work on Android, or by placing the html code into a simple index.htm file on your computer.

### Link to public reproduction project repository

https://github.com/farmergreg/maui-datalist-example/blob/master/MauiApp1/Pages/Index.razor

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10, Windows 11

**Comment by Eilon** [comment]
Possible related/dupe: https://github.com/dotnet/maui/issues/15005

**Comment by carsten-riedel** [comment]
@farmergreg @Eilon @mkArtakMSFT 
You can find some hints about a workaround found in. https://github.com/MicrosoftEdge/WebView2Feedback/issues/3496 
Basically, you can adapt the UWP Fixed Webview Runtime solution, and need to make a recursive copy task to copy it to the output,build,publish directorys.

**Comment by Eilon** [comment]
Thanks, this is indeed covered by the following WebView2 issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3496

The issue repros only on WebView2 in WinUI, which is what .NET MAUI uses when running on Windows, so it affects the .NET MAUI BlazorWebView and WebView controls on Windows.

The issue does not seem to happen on non-Windows platforms, and on Windows it seems fine on WPF/WinForms, so BlazorWebView should work fine there.

Please up-vote the WebView2 issue to increase visibility.
