### ISSUE TITLE
Cannot launch ios app on simulator or device "does not contain valid CFBundleVersion"

### ISSUE THREAD

**Issue by ShaunNealFluent** [dotnet/maui#15144]
### Description

Upon trying to debug in the simulator, the following error is received:

> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
> Simulator device returned an error for the requested operation.
> The application's Info.plist does not contain a valid CFBundleVersion.
> Ensure your bundle contains a valid CFBundleVersion.
> Underlying error (domain=NSPOSIXErrorDomain, code=22):
> 	Failed to install the requested application
> 	The application's Info.plist does not contain a valid CFBundleVersion.

I have verified the bundle name and short name are the same as the application versions in the csproj.

I was able to deploy the application yesterday.  After re-cloning our devops repo source it now will not build.

### Steps to Reproduce

Unknown exactly, but appears to be a version mismatch in the info.plist which is generated, or perhaps info.plist changes are not being picked up upon rebuild after editing in the gui.

### Link to public reproduction project repository

code is commercial/proprietary banking app

### Version with bug

7.0.86

### Last version that worked well

7.0.86

### Affected platforms

iOS

### Affected platform versions

xcode 14.3.  visual studio for mac 17.5.4

### Did you find any workaround?

I can build a fresh ios app and deploy to the simulator without issue.  Copying the info.plist values from the fresh app to my app results in the same error.

### Relevant log output

```shell
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Simulator device returned an error for the requested operation.
The application's Info.plist does not contain a valid CFBundleVersion.
Ensure your bundle contains a valid CFBundleVersion.
Underlying error (domain=NSPOSIXErrorDomain, code=22):
	Failed to install the requested application
	The application's Info.plist does not contain a valid CFBundleVersion.
```

**Comment by RhevanP** [comment]
Hey there, just following up the issue.

I've been facing it too. A bit more context:
I built the project on Windows with an previous version of Visual Studio (Don't have the version number, updated it in-between) and then bought a mac mini, installed the latest visual studio version & pull the code directly on it.

On my windows device, the whole thing runs smoothly with Android, I even published the app no problem.

On mac, I have exactly the same problem. However when building brand new projects it doesn't seem to happen.

**Solutions I tried but ended up with the same error**

1. Added manually the "Bundle versions string (short)" and "Bundle Version" to 1.0.0
2. Delete the entire repo & pulled again
3. Modified by hand using notes the info.plist to add CFBundleVersion
4. Tried to force type in manually the CFBundleVersion in the file but it reverts to Bundle Version.
5. Erased all contents and settings from the simulator & tried again
6. Adding a new iphone simulator, testing on all the simulators
7. Added manually the Bundle Name and Bundle Identifier with a string
8. 1-3-4-5-6-7 after cleaning the build at every run
9. Tried to add another .0 after 1.0.0 (was mostly to see if I could have another error - I didn't)
10. I've changed the `ApplicationDisplayVersion` to 1.0.0 as well
11. I've compared side by side all the info.plist & project/solution files from my project and a brand new project that can launch the emulator, changing ANYTHING that didn't match.

I'll try a few more things today and keep you posted if I find anything new.

**Comment by alangrima** [comment]
Any luck with this issue? I'm experiencing exactly the same thing!

**Comment by RhevanP** [comment]
Sadly not. 
I bought an ipad and it seems that now I have a different error when trying to build related to codesign.
I don't think I managed to replicate the bug since I got the product & I redid all the signing for my app.

**Comment by RhevanP** [comment]
Update:
It seems that I don't see that error anymore, but I see an exit code 22 when trying to install my app on ANY device (Simulator or physical) which seems to be related to the above [according to this link](https://stackoverflow.com/questions/73989470/deploying-net-maui-to-ios-simulator-error-simctl-returned-exit-code-22). So I think the problem still persists.

**Comment by RhevanP** [comment]
Thanks to you, I managed to have some "progress" (As in, I have a different error message now)

**_Devices:_**
1. Windows laptop connected to mac mini
2. Mac Mini M2
3. ipad USB linked to mac mini

**_Build Process:_**
Remote build from Windows to ipas using the Mac Mini connection I have with Visual Studio.

**_What I did:_**
- I deleted the entire line importing what you described above
- I deleted the .txt file inside the raw folder (now the folder is totally empty)
- Using indications from [this subject on github](https://github.com/dotnet/maui/issues/14044) replace the `Logical Name` in the `<MauiAsset>` by `Link`
- Did change LogicalName by Link while having the entire Raw import line commented out

Now instead of having a code 22 OR an issue with the CFBundle, I have a Code 1
`YourAppName.app is not signed at all`

I configured correctly the automatic signing with my enterprise key & imported a keychain for development, I can even see in the logs that it's detecting the signing automatically.

Looking at the logs, I can also see that `Microsoft.CSharp.dll` is not signed either.

**Comment by alangrima** [comment]
I was also getting a similar message. What I did not do is change Logical Name to Link .. just left it as it was, but removed the additional references to the files I had added.

**Comment by RhevanP** [comment]
What I did:
- Removing all double reference of asset file within the project (Including a `<ItemGroup>` that contained `<Content>` which referenced things from other than RAW project file).
- Clean the build
- Closed & opened VS again just in case 

Now my error message changed to 
`Unable to build chain to self-signed root for signer "Apple Development : MyName (NumbersAndLetters)`

So now it's a different error message & different issue. Thanks for the help 😄

**Comment by jameslavery** [comment]
Looking through the comments above - has anyone got a workaround for this? I'm getting this error with files in Resources/Raw

It's stopping me being able to deploy to any iOS device.

**Comment by nihaoyahaha** [comment]
I have also encountered this problem, and my solution is not to set the file generation operation as an embedded resource

**Comment by NabodevMats** [comment]
+1 on the codesign exited with code 1:  code object is not signed at all. after following in the footsteps of @RhevanP . Using a M1 Mac Studio and VS 17.6.6 and net7. Provisioning profiles are listed correctly in the project options.

Trying to get my app deployed to ios sim. Have the android working and have had the ios working some months ago and now after picking it up again I'm at the same place as you.

**Comment by Hackmodford** [comment]
I just ran into this issue when trying to add an asset to the raw folder. No idea how to fix this.

**Comment by M4rtinSc** [comment]
After hours of research with code 22 error, the hint with Remove Files in Projectfile solved the problem:

After Removing that lines:

`<ItemGroup>
      <None Remove="Resources\Splash\splash.png" />
</ItemGroup>`

Its working.

It seems that not only the Raw directory is affected.

**Comment by jaosnz-rep** [comment]
Verified this issue with Visual Studio for Mac 17.6.8. Not repro with MAUI and Xamarin iOS project.
macOS: Ventura 13.6.3
Xcode: 15.1, iOS 17.2 simulator

**Comment by mirceamuresanse** [comment]
I also get the same issue and it is not related to Visual Studio.
I tried on my M2 Mac, using both Visual Studio for Mac (version 17.6.8 build 400) and Rider (latest version) and getting exactly the same error:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Simulator device returned an error for the requested operation.
The application's Info.plist does not contain a valid CFBundleVersion.
Ensure your bundle contains a valid CFBundleVersion.
Underlying error (domain=NSPOSIXErrorDomain, code=22):
	Failed to install the requested application
	The application's Info.plist does not contain a valid CFBundleVersion.
That tells me it is not related to tooling, but it is a deployment to a simulator related issue.
I tried all of the suggested work arounds and none of them worked.

**Comment by konradzuse** [comment]
I have the same error using Rider, so it's probably unrelated to Visual studio

**Comment by konradzuse** [comment]
the issue appears to be the use of a referenced project containing embedded resources

**Comment by mmuresan** [comment]
I tried on a project that has embedded resources and I don't get this issue. This is related to something else, not VS, Rider or VS Code related, as I am using all 3. This is strictly related to Maui build process.
