### ISSUE TITLE
MauiHybrid <datalist> element no longer working

### ISSUE THREAD

**Issue by DrNoLife** [dotnet/maui#15149]
### Description

The ```datalist ``` element, no longer works as it should do, when using MauiHybrid (Maui with Blazor).

The element works exactly as it should in Blazor WASM.

When trying to use the element in MauiHybrid, the suggestions-box is not appearing. Neither when clicking on the input field, nor when typing.

The datalist is there when I check the source code of the Maui program using dev tools. However, it never visually appears for the user. 

Here's a video of the issue, which should make it a bit more clear:

https://github.com/dotnet/maui/assets/17468135/489b6c86-4b94-4ba2-8b02-e0277181f8ba

## Further information

Last time this worked correctly, was "roughly a week or two ago". I do realize this is not a good descriptor, but alas it's all I can say. The program wherein I'm using the datalist worked fine before. Then without changing any code, a week later it just didn't work. I've tested it on: my desktop; my laptop; on a coworker's PC.

### Steps to Reproduce

1. Create a new Maui Blazor project.
2. In one of the pages, add an input that references a datalist.
3. Populate said datalist.
4. Run the program, and try to use the input.

Expected outcome: The datalist would appear when the input has focus. The datalist would only show results that match with what the user was writing.
Actual outcome: The datalist does not appear.

### Link to public reproduction project repository

https://github.com/DrNoLife/maui-bug-datalist-not-working

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

net6.0-windows10.0.19041.0

**Comment by Eilon** [comment]
Probably dupe: https://github.com/dotnet/maui/issues/15005

**Comment by carsten-riedel** [comment]
@mkArtakMSFT @Eilon @DrNoLife 
You can find some hint about a workaround found in. https://github.com/MicrosoftEdge/WebView2Feedback/issues/3496 
Both teams should align for creating a more solid solution in my opinion.

**Comment by DrNoLife** [comment]
I believe I've found a fix for it.  The testing I've done is basically create 2 brand new projects and use the fix, both times it has worked. It also worked when I published the project via .msix, and then ran the program afterwards.

Step by step:

1. Create a MAUI Blazor Project using .NET6
2. Download the working version of WebView2 at https://developer.microsoft.com/en-us/microsoft-edge/webview2/ [112.0.1722.68]
3. Transfer the downloaded .cab file into your project folder (I added it into a folder named Runtimes).
4. Run the following command: ```expand {path to the package} -F:* {path to the destination folder}``` e.g. ```expand .\Microsoft.WebView2.FixedVersionRuntime.112.0.1722.68.x64.cab -F:* .```
5. Rename the new folder, I just changed it to WW2 (short for WebView2). We need to rename it, because we might end up hitting a character limit at some point by using the long default name.
6. Inside your .csproj file, add the following: <br/>
```
<ItemGroup>
	<Folder Include="Runtimes\" />
</ItemGroup>

<ItemGroup>
	<None Update="Runtimes\WW2\**">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
</ItemGroup>
```
7. Inside your MauiProgram.cs, add the following to the top of the CreateMauiApp method: <br/>

```csharp
string relativePath = @"Runtimes\WW2";
string basePath = AppContext.BaseDirectory;
string runtimePath2 = Path.Combine(basePath, relativePath);
Environment.SetEnvironmentVariable("WEBVIEW2_BROWSER_EXECUTABLE_FOLDER", runtimePath2);
```

# Explanation

It seems like the WebView2 element read the ```WEBVIEW2_BROWSER_EXECUTABLE_FOLDER``` environment variable, to see if it needs to use a specific webview version. This should point towards a local directory containing the webview2 files.

We're doing the ItemGroup stuff to make sure that our folders ```Runtimes\WW2``` (and all of the content inside) are being included into the program itself. After this, we can then find the base directory of our program and combine that with the relative path pointing towards the WebView2 files.

## Notes

This does increase the file size a lot. Reason being, the webview2 files are around 250MB.
It also seems like it increases the load times of the application (I guess this is due to the fact that the webview takes a bit of time getting initialized).

**Comment by Eilon** [comment]
Indeed, the core issue is tracked here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3496

More details from another issue: https://github.com/dotnet/maui/issues/15136#issuecomment-1560167151
