### ISSUE TITLE
iOS - Can't scroll to the last item in Flyout

### ISSUE THREAD

**Issue by marekm294** [dotnet/maui#15153]
### Description

https://github.com/dotnet/maui/assets/108216731/30e64523-76df-4af3-9272-8ea957cc812d

There's also weird behavior when you scroll title with multiple lines to to the bottom of the screen.

### Steps to Reproduce

Use multiple ShellContents in Flyout so you have more lines than your screen can display.

### Link to public reproduction project repository

*

### Version with bug

7.0.86

### Last version that worked well

7.0.86

### Affected platforms

iOS

### Affected platform versions

iOS 16.4.1

### Did you find any workaround?

no

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 3.0. This issue does not repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[15153.zip](https://github.com/dotnet/maui/files/12047922/15153.zip)
![Scroll](https://github.com/dotnet/maui/assets/97647558/f8235da6-c29e-45a4-b16d-9cda136928e8)
