### ISSUE TITLE
Windows EmptyView different vertical/horizontal options when Template/View used

### ISSUE THREAD

**Issue by marekm294** [dotnet/maui#15152]
### Description

Android:
![Android](https://github.com/dotnet/maui/assets/108216731/3e4be677-9e3d-4aa5-aadf-1fa1f92debd1)

iOS:
![iOS](https://github.com/dotnet/maui/assets/108216731/46935be7-4b13-4c85-93eb-da06267c9c5f)

Windows:
<img width="957" alt="Windows" src="https://github.com/dotnet/maui/assets/108216731/a958b22e-fd21-49e2-92bc-2e5dccf7f64d">

As you can see empty view does behave differently. I'm not sure which is correct.

Cannot test it on mac 

### Steps to Reproduce

    <Grid>
        <CollectionView BackgroundColor="Beige">
            <CollectionView.Behaviors>
                <behaviors:CollectionViewReloadingEmptyViewBehavior />
            </CollectionView.Behaviors>
            <CollectionView.EmptyViewTemplate>
                <DataTemplate>
                    <HorizontalStackLayout BackgroundColor="#80000000">
                        <Label Text="No record here"
                           Margin="10,25,10,10"
                           FontAttributes="Bold"
                           FontSize="18"
                           HorizontalOptions="Fill"
                           HorizontalTextAlignment="Center" />
                        <Button Text="AddItem" Clicked="Button_Clicked"/>
                    </HorizontalStackLayout>
                </DataTemplate>
            </CollectionView.EmptyViewTemplate>
        </CollectionView>
    </Grid>

### Link to public reproduction project repository

*

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11, iOS 16.4.1, Android 11

### Did you find any workaround?

no

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 3.0. This issue repro on .NET 7.0, but not repro on .NET 8.0 with below Project:
[15152.zip](https://github.com/dotnet/maui/files/12047663/15152.zip)

Windows 11:
![image](https://github.com/dotnet/maui/assets/97647558/d4b42cd8-ed4c-4a3a-98f0-8fc77e7a636f)
Android Android 13.0-API33:
![image](https://github.com/dotnet/maui/assets/97647558/118aa9ee-a388-41df-92c0-50a15b50cb20)
iOS 16.4:
![image](https://github.com/dotnet/maui/assets/97647558/a0a93605-84f6-4479-8689-c2679c244f4f)
