### ISSUE TITLE
Windows Cannot click on EmptyView

### ISSUE THREAD

**Issue by marekm294** [dotnet/maui#15157]
### Description

Android:
https://github.com/dotnet/maui/assets/108216731/e17ca6ed-6dcf-46b2-a1f4-c5d377691d37

iOS:
https://github.com/dotnet/maui/assets/108216731/af4500b3-bafc-46d1-ad57-f51bd436fea6

Windows:
https://github.com/dotnet/maui/assets/108216731/9944028d-f0f6-47bb-9712-5831f17ed265

You can click on EmptyView on Android/iOS but not on Windows. Could not test on mac

### Steps to Reproduce

    <Grid>
        <CollectionView BackgroundColor="Beige">
            <CollectionView.Behaviors>
                <behaviors:CollectionViewReloadingEmptyViewBehavior />
            </CollectionView.Behaviors>
            <CollectionView.EmptyViewTemplate>
                <DataTemplate>
                    <HorizontalStackLayout BackgroundColor="#80000000">
                        <Label Text="No record here"
                           Margin="10,25,10,10"
                           FontAttributes="Bold"
                           FontSize="18"
                           HorizontalOptions="Fill"
                           HorizontalTextAlignment="Center" />
                        <Button Text="AddItem" Clicked="Button_Clicked"/>
                    </HorizontalStackLayout>
                </DataTemplate>
            </CollectionView.EmptyViewTemplate>
        </CollectionView>
    </Grid>

CodeBehind:

```
    private void Button_Clicked(object sender, EventArgs e)
    {
        Toast.Make("Button").Show();
    }
```

Behavior:

```
internal sealed class CollectionViewReloadingEmptyViewBehavior : Behavior<CollectionView>
{
    protected override void OnAttachedTo(CollectionView collectionView)
    {
        base.OnAttachedTo(collectionView);
        collectionView.PropertyChanged += Bindable_PropertyChanged;
    }

    protected override void OnDetachingFrom(BindableObject bindable)
    {
        base.OnDetachingFrom(bindable);
        bindable.PropertyChanged -= Bindable_PropertyChanged;
    }

    private void Bindable_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        var collectionView = (CollectionView)sender;

        if (e.PropertyName == CollectionView.WidthProperty.PropertyName)
        {
            if (collectionView.Width > 0 && Helper.IsEnumerableNullOrEmpty(collectionView.ItemsSource))
            {
                var emptyViewTemplate = collectionView.EmptyViewTemplate;
                collectionView.EmptyViewTemplate = null;
                if (emptyViewTemplate is not null)
                {
                    collectionView.EmptyView = emptyViewTemplate.CreateContent();
                }
            }
        }
    }
}
```

### Link to public reproduction project repository

*

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by marekm294** [comment]
@drasticactions https://github.com/marekm294/EmptyViewRepo - you should be able to test it here.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 3.0. This issue repro on Windows 11 on **.NET 7**, not repro on Windows 11(**.NET 8.0**), Android 13.0-API33 and iOS 16.4 with below Project:
[EmptyViewRepo.zip](https://github.com/dotnet/maui/files/12047561/EmptyViewRepo.zip)

Windows on .NET 8.0:
![Button](https://github.com/dotnet/maui/assets/97647558/e0150bc9-b319-4de9-9f36-a43accf9d2bd)
