### ISSUE TITLE
iOS - Basic collection view elements don't render properly.

### ISSUE THREAD

**Issue by RobTF** [dotnet/maui#15164]
### Description

I have a simple collection view with an item template which shows an image with a description to the right.

The XAML for the template is;
```xaml
<Border Margin="10,0,10,0">
    <Grid ColumnDefinitions="Auto,*" ColumnSpacing="10" Margin="5">
        <Image Source="template.png" WidthRequest="36" />
        <Label Grid.Column="1" Text="{Binding Name}" VerticalOptions="Center" />
    </Grid>
</Border>
```

On Android it works fine as per below;
![image](https://github.com/dotnet/maui/assets/4292237/a04d4f7f-f506-4c9d-9494-63aa9bf225d2)

However, on iOS it seems to have problems with vertical sizing.
![image](https://github.com/dotnet/maui/assets/4292237/ec0f2fc9-42cd-4058-a5e8-26e179310155)

### Steps to Reproduce

1. Build attached repro case.
2. Run on iOS
3. Tap "Go to test page"
4. Observe issue.

### Link to public reproduction project repository

https://github.com/RobTF/mauiplay/tree/master/CollectionViewIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

### Did you find any workaround?

If the item height is known ahead of time, a `HeightRequest` can be added as a hack, but this is problematic as in a lot of cases the item should just be the size of the content, so varying font sizes, or data which is dynamically bound make this very difficult or impossible.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 3.0. Repro on iOS 16.4 .NET 8, and Android 13.0-API33 also has render issue with below Project:
[CollectionViewIssue.zip](https://github.com/dotnet/maui/files/12068053/CollectionViewIssue.zip)

iOS:
![image](https://github.com/dotnet/maui/assets/97647558/8112e5f4-6d68-4ad2-b0ca-d69a0870bb44)
Android:
![image](https://github.com/dotnet/maui/assets/97647558/51e47f0c-c33b-4f6d-89dc-58cf142fcf10)

**Comment by davidortinau** [comment]
Set `HeightRequest` on the `Image`:

![Simulator Screenshot - iPhone 14 Pro - 2023-08-17 at 10 10 12](https://github.com/dotnet/maui/assets/41873/a906c9a3-d054-46f1-9102-27f45f7265e1)

Android `Border` default background color seems to be the black. Setting the default style to transparent resolves this:

Resources/Styles.xaml

```xml
<Style TargetType="Border">
        <Setter Property="Stroke" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray500}}" />
        <Setter Property="StrokeShape" Value="Rectangle"/>
        <Setter Property="StrokeThickness" Value="1"/>
        <Setter Property="Background" Value="Transparent"/>
    </Style>
    ```
    
   @PureWeen @rachelkang should we update the default styles RD, or is there a backing default that is incorrect on Android?
