### ISSUE TITLE
The foreground stop running when application is not in foreground

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/maui#15161]
### Description

I have an application.

This is the application: 
[MauiForegroundServiceWithGps.zip](https://github.com/dotnet/maui/files/11508800/MauiForegroundServiceWithGps.zip)

In the application  I have an AlarmForegroundService that I use to keep running the service although the application is not in foreground or it is also closed. At least, this in theory, because it is stopped when the application is not in the foreground.

This AlarmForegroundService use AlarmService, that implements the logic, it has a PeriodicTimer that get the location and compare it with a reference location. If it is less, it notify to AlarmForegroundService with a Message and then the AlarmForegroundService publish a notification.

However, I have notify that if I set a breakpoint in the AlarmService, in the method that is run periodically requesting the location, and I quit the application from the foreground, then the breakpoint is not arise. But If i back to put the application in the foreground, it is arise again.

So my question is, why the foreground service doesn't run when the application is not in the foreground? If I am right, the main use of foreground it is to ensure to keep running although the application is not in the foreground.

Thanks.

### Steps to Reproduce

1. Run the attached application.

### Link to public reproduction project repository

Not needed, I have attached the source code

### Version with bug

7.0.49

### Last version that worked well

7.0.86

### Affected platforms

Android

### Affected platform versions

Android API 31

### Did you find any workaround?

I couldn't find the way to make it works as expected.

**Comment by RobTF** [comment]
Hi,

I've taken a look at your code and what you're doing won't work - unfortunately you can't just start a timer in .NET and expect it to run indefinitely whilst the app is backgrounded. You need to consider the wider app lifecycle on mobile platforms.

This sort of background processing is heavily locked down on mobile platforms (for battery, privacy etc.), and each platform allows for this sort of capability differently. Android for example, has specific methods by which apps can register to do periodic work. I would suggest you take a look at these topics.

[Schedule Alarms](https://developer.android.com/training/scheduling/alarms)
[Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager)

Our app is using `WorkManager` to wake up in the background periodically on Android with no problems. I don't think there is an issue with MAUI here.

**Comment by ComptonAlvaro** [comment]
Hello, thanks for the comments.

I have tried WorkManager, and it works and have adavanteges that if the device reboots, it will continue working by itself, it is not needed to create a receiver.

The problem with the worker is that if for example I set an interval of 10 seconds, the worker can take 15 mintues to run again, so it is a lot of time. And I have read that Android decides itself when to run the worker, so I can't ensure when it will be run. I would like to ensure that the code is run in the interval that I would like to configure.

My application what I want to do it is publish a notification if the device is near some locations than the user can set. It can be considerated an alarm when the user is in a location.

I will check the option of scheduling an alarm, perhaps it is a another option.



Thanks so much.

**Comment by RobTF** [comment]
Hi,

No problem. Yes you're correct the devices won't let you set recurring jobs for very short times such as 10 seconds; this is just a limitation of the platform.

If your app needs to respond to the user entering a location, I suggest you take a look at the geo-fence API as this allows your app to be invoked based on user location without having to poll the location yourself.

[Create and monitor geofences](https://developer.android.com/training/location/geofencing)

iOS has a similar concept.

**Comment by ComptonAlvaro** [comment]
But if is a limitation, I am wondering how GPS navigation applications can work, because this kind of applications need real time location. In my case with 5 or 10 minutes it is enough, I don't need more, but what if I could need real time location like gps navigation applications?

**Comment by RobTF** [comment]
A GPS navigation app quite often will be in the foreground in some way (so the user can see the map) and none of the limitations you're hitting apply anymore.

Regarding the locations, they don't poll the device explicitly but rather will use a location listener to get a continuous stream of location updates from the device.

[LocationListener](https://developer.android.com/reference/android/location/LocationListener)

However, depending on your use case this can be a bad idea as it will drain battery fairly quickly, which is fine if your app is being used in a car as a sat nav, cabled into a charger but not so good for something longer running.

Depending on the intended application, certainly an option though.

**Comment by ComptonAlvaro** [comment]
I was thinking about what did you tell: "unfortunately you can't just start a timer in .NET and expect it to run indefinitely whilst the app is backgrounded".

So I tried to modify my code in this way. In the AlarmService, I modify the method DoWork and I use this:

```
private int _notificationNumber = 0;
private async Task DoWorkAsync()
{
    try
    {
        while (await _timer.WaitForNextTickAsync(_cts.Token))
        {
            _notificationNumber++;
            _messenger.Send<TextMessage>(new TextMessage($"notification number: {_notificationNumber}"));
        }
    }
    catch (System.OperationCanceledException ex)
    {
    }
}
```

In this case, the code is not stopped, it runs and I have tried to put the application in background and also I close the it, but the timmer is still running.

However, when the timmer request the location, it seems that the OS, if it detects that the code request the location, it will stop it if the application is not in the foreground.

So after this I am thinking that perhaps the problem is not the timmer and I can expect it will run indefinitely meanwhile the code doesn't requst the location.

**Comment by RobTF** [comment]
Hi,

You might need to do a little more research on the platform, as having simply a loop in your code that runs indefinitely and hoping it will stay alive might work in short tests but is a very naïve implementation that will not work in the general case.

For example, if you take a look at the Android process lifecycle documentation [here](https://developer.android.com/guide/components/activities/process-lifecycle). The documentation warns about spawning threads which do work in the background with warnings such as _"...the system can kill the process at any time to reclaim memory, and in doing so, it terminates the spawned thread running in the process."_

Most mobile platforms work this way - your app can be terminated at any time for any reason, or put into a [deep sleep](https://developer.android.com/training/monitoring-device-state/doze-standby) state whereby your app simply stops.

When your app is stopped, what will restart your thread? With iOS it's worse as your app can be flagged as "misbehaving" and can be terminated if it refuses to stop processing in the background when asked.

It is also not uncommon for the devices to limit APIs for background applications (such as location, microphone etc.) so the fact the location APIs stop working in the same way when backgrounded is unsurprising.

It's a big topic, and one we've dealt with for a number of years now with the nature of our own apps. I'm happy to continue the discussion in a direct chat or the discussions section, but this is certainly not a MAUI bug.
