### ISSUE TITLE
[Bug] Partial class for Razor Component does not work.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/maui#1516]
In Blazor Web Assembly and Blazor Server, we use partial class for Razor component to separate the C# Code from Razor Code. In .NET MAUI Blazor, the partial class for Razor Component is not working. It shows the following error:

>	'LoginComponent.OnInitialized()': no suitable method found to override

![Maui](https://user-images.githubusercontent.com/14342773/124151532-76617900-dab4-11eb-94af-93859ff3b8ff.PNG)

**Comment by Eilon** [comment]
Very interesting, I think I'm seeing the same thing on my machine. We'll have to take a look at this, because it should be working.

**Comment by Eilon** [comment]
As a _workaround_, of course you can place all the code in the `.razor` file in an `@code { ... }` block for now.

**Comment by TanvirArjel** [comment]
@Eilon Please also take a look at this: https://github.com/dotnet/maui/issues/1623 . This is another crucial blocking bug.

**Comment by Eilon** [comment]
Good news, we figured out a fix! https://github.com/dotnet/maui/pull/1651

**Comment by TanvirArjel** [comment]
@Eilon The pull requested says, the fixes have been merged with .NET 6.0 preview 6. I have tested with .NET 6.0 preview6 with Visual Studio 2022 preview2 and Visual Studio 2019 16.11 Preview3 and found that fixes are not available. Could you please confirm with which version of .NET 6.0 and Visual Studio the fixes will be available?
