### ISSUE TITLE
Border StrokeThickness="0" not working when parent is Grid

### ISSUE THREAD

**Issue by pinyo-rungoral** [dotnet/maui#15162]
### Description

Border that StrokeThickness=0 still render 1 pixel with transparent color when it is child of Grid

below image show you can see red color of BoxView (BoxView render correct but Border still have 1 border pixcel)

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui-maccatalyst           7.0.86/7.0.100        SDK 7.0.200        
maui-ios                   7.0.86/7.0.100        SDK 7.0.200        

<img width="1278" alt="image" src="https://github.com/dotnet/maui/assets/43538243/82efc359-5bac-43a9-b2ad-af0ebb051a31">
<img width="364" alt="image" src="https://github.com/dotnet/maui/assets/43538243/21b203c0-713a-45e7-ae3b-224ae017d417">

### Steps to Reproduce

clone reproduction project repository and run

expected: Border should fill to cell like ViewBox do
act: border still show Transparent 1 pixel

### Link to public reproduction project repository

https://github.com/pinyo-rungoral/maui-border-bug/tree/main

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

maui-ios                   7.0.86/7.0.100        SDK 7.0.200

**Comment by mavispuford** [comment]
This also happens to us.  Workload info:

```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-ios                   7.0.86/7.0.100         VS 17.6.33815.320
maui-android               7.0.86/7.0.100         VS 17.6.33815.320
maccatalyst                16.4.7067/7.0.100      VS 17.6.33815.320
maui-windows               7.0.86/7.0.100         VS 17.6.33815.320
maui-maccatalyst           7.0.86/7.0.100         VS 17.6.33815.320
ios                        16.4.7067/7.0.100      VS 17.6.33815.320
android                    33.0.46/7.0.100        VS 17.6.33815.320
```

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 3.0. This issue repro on .NET 7.0, but not repro on .NET 8.0 with below Project:
[MauiApp18.zip](https://github.com/dotnet/maui/files/12066875/MauiApp18.zip)
iOS 16.4:
![image](https://github.com/dotnet/maui/assets/131441429/12ac7403-65ca-4297-b396-c35e300b67ae)
Android Android 13.0-API33:
![image](https://github.com/dotnet/maui/assets/131441429/e6e433c1-d341-4d75-86f8-7a770feaa17f)
