### ISSUE TITLE
Splash screen icon shrink when using State Manager on iPad

### ISSUE THREAD

**Issue by Moro890** [dotnet/maui#15175]
### Description

I'm using an iPad Pro (11-inch) (3rd generation), but it happens on the 2nd generation too. When you open the app and the state manager is enabled, the splash screen shrink
![IMG_0063](https://github.com/dotnet/maui/assets/100759335/22f8066b-588d-4747-a884-04a2992df880)

### Steps to Reproduce

1. Enable State Manager
2. Open the app

### Link to public reproduction project repository

.

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPadOS 16.4.1

**Comment by mattleibow** [comment]
I am not sure what you mean by "State Manager"? Is this only on iPad or also iPhone?
