### ISSUE TITLE
MAUI ios will no longer build on windows when using Xamarin.Firebase.iOS.CloudMessaging

### ISSUE THREAD

**Issue by jadenrogers** [dotnet/maui#15170]
### Description

Unable to build for ios targets from Windows Visual Studio 17.6

when using the following packages 

```
		<PackageReference Include="Xamarin.Firebase.iOS.CloudMessaging" Version="8.10.0.3" />
		<PackageReference Include="Xamarin.Firebase.iOS.Installations" Version="8.10.0.3" />
```

Remove them and it will work fine.

1>Target _CopyLocalBindingResources:
1>  C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7060\targets\Xamarin.Shared.Sdk.targets(2019,3): error : MessagingRemoteException: An error occurred on client Build1647060 while executing a reply for topic xvs/build/16.4.7060/execute-task/FirebaseErrorSample/0a1e8f7002fGetFileSystemEntries

### Steps to Reproduce

Run sample from windows using visual studio 2022 17.6 connected to a Mac Agent.

Solution will error. 

Remove the following packages

```
		<PackageReference Include="Xamarin.Firebase.iOS.CloudMessaging" Version="8.10.0.3" />
		<PackageReference Include="Xamarin.Firebase.iOS.Installations" Version="8.10.0.3" />
```

Solution will run.

No issue running the same project directly on mac.

### Link to public reproduction project repository

https://github.com/jadenrogers/FirebaseErrorSample

### Version with bug

7.0.86

### Last version that worked well

7.0.49

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Current work around is to use VS For Mac.

### Relevant log output

```shell
Target _CopyLocalBindingResources:
1>  C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7060\targets\Xamarin.Shared.Sdk.targets(2019,3): error : MessagingRemoteException: An error occurred on client Build1647060 while executing a reply for topic xvs/build/16.4.7060/execute-task/FirebaseErrorSample/0a1e8f7002fGetFileSystemEntries
1>  C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7060\targets\Xamarin.Shared.Sdk.targets(2019,3): error : DirectoryNotFoundException: Could not find a part of the path '/Users/drkevl/Library/Caches/Xamarin/mtbs/builds/FirebaseErrorSample/0a1e8f7fdf7c6b6897adab9e13565febdb579b8d471685aa8bc47b9367615275/C:/Users/drkevl/.nuget/packages/xamarin.firebase.ios.cloudmessaging/8.10.0.3/lib/net6.0-ios15.4/Firebase.CloudMessaging.resources'.
1>  C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7060\targets\Xamarin.Shared.Sdk.targets(2019,3): error :
1>Done building target "_CopyLocalBindingResources" in project "FirebaseErrorSample.csproj" -- FAILED.



On mac files exist up to 

'/Users/drkevl/Library/Caches/Xamarin/mtbs/builds/FirebaseErrorSample/0a1e8f7fdf7c6b6897adab9e13565febdb579b8d471685aa8bc47b9367615275/C:/Users/drkevl/'

Looking for

'/Users/drkevl/Library/Caches/Xamarin/mtbs/builds/FirebaseErrorSample/0a1e8f7fdf7c6b6897adab9e13565febdb579b8d471685aa8bc47b9367615275/C:/Users/drkevl/.nuget/packages/xamarin.firebase.ios.cloudmessaging/8.10.0.3/lib/net6.0-ios15.4/Firebase.CloudMessaging.resources'
```

**Comment by scriptBoris** [comment]
I can confirm this issue. In using library @JimmyPun610 barcode scanner based on Google Machine Learning

**Comment by scriptBoris** [comment]
https://github.com/dotnet/maui/issues/15042 linked issue

**Comment by jadenrogers** [comment]
Logged with VS. Closing. https://developercommunity.visualstudio.com/t/An-error-occurred-on-client-Build1647054/10370055

**Comment by brunck** [comment]
See https://github.com/xamarin/xamarin-macios/issues/18308
