### ISSUE TITLE
iOS: CollectionView items don't change their size when item content size is changed

### ISSUE THREAD

**Issue by pitMobile** [dotnet/maui#15177]
### Description

I'm facing the same issue like handled in issue #3643 which is now closed but the problem still exists. The attached sample in  3643 does not work, the collection view cell don't increases his height.

### Steps to Reproduce

use the attached sample in issue #3643

### Link to public reproduction project repository

#3643

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16.4

**Comment by pitMobile** [comment]
I changed the Rowdefinitions of the Root Grid to "Auto", but the Grid doesn't change its size, the inner Label gets correct the  SizeChanged event. This looks like the same problem handled in #7297.
But even if I get the root grid change its size (in our program we use for instance an autosizing editor or a flex layout with dynamical content as Childs of the root grid in the Collectionview DataTemplate) the CollectionView doesn't update its cell.

**Comment by eengstroem** [comment]
I am facing the same issue. I tested a collectionview, where the IsVisible-attribute of some elements can be changed on a button press. Inside the collectionview is a grid, where some labels become visible/not visible. The labels push other content down on Android, as I intended. However, on iOS, it doesn't. There is no MaximumHeightRequest set, or something like that.

**Comment by pitMobile** [comment]
The project Maui.Controls.Sample in the Maui source solution contains a CollectionView sample named Expanding Text (Vertical List) with the same problem.

**Comment by FlavioGoncalves-Cayas** [comment]
It's been over half a year since this bug was initially reported. 
This should be basic functionality that worked even in Xamarin Forms...

This can also easily reproduced when using an expander in the ItemTemplate.

**Comment by unamed000** [comment]
I'm having the same issue ...

Some people saying this is the native behaviors, but again, Xamarin Forms was working normally fine and MAUI break this, how can we suppose to migrate from Xamarin Forms to MAUI when we have a tons of CollectionView that we need to migrate and this isn't working normally ?!

**Comment by ilsur-dev111** [comment]
The problem still exists for almost a year now. such things should be implemented out of the box, I already regret that I didn’t start using flutter for commercial development, it’s a complete disappointment.
