### ISSUE TITLE
Latest update to Visual Studio for Mac breaks CollectionView

### ISSUE THREAD

**Issue by cdavidyoung** [dotnet/maui#15189]
### Description

Yesterday (5/18/23) I had finished testing my CacheAll app on my Mac and was ready to upload it to the AppStore and run it from TestFlight.  However, VS told me there was an update so I said OK to let it update.  I then rebuilt the app and tried it out in the debugger.  To my surprise the CollectionView on the main page starts out looking fine but as soon as I scroll it it gets messed up. Below are screenshots from both Mac and iOS.

I used Time Machine to go back to 5/17/23 to back out of the update and all is well again.  The version I am using now is VS Mac 17.5.5 build 12.  The strange thing is that when I ask it to check for updates it says that I am up-to-date.  Yesterday I am positive there was an update that messed things up.  Has that update been backed out?

![Screenshot 2023-05-19 at 7 45 13 AM](https://github.com/dotnet/maui/assets/937899/c0af6ad9-df65-4618-8791-49a966079ca0)
![Screenshot 2023-05-19 at 7 45 59 AM](https://github.com/dotnet/maui/assets/937899/99006630-397b-48fb-8dfb-2bb0a62791f4)
![Screenshot 2023-05-19 at 7 41 08 AM](https://github.com/dotnet/maui/assets/937899/7c454001-aabd-4b45-bee0-452f755fcde8)

![Screenshot 2023-05-19 at 7 41 43 AM](https://github.com/dotnet/maui/assets/937899/3061ec0d-25bf-4c7a-ac22-5bac2e82d9f8)

### Steps to Reproduce

Let VS Mac update to version available on 5/18/23.  That seems to be gone now.

### Link to public reproduction project repository

?

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

iOS, macOS

### Affected platform versions

iOS and MacCatalyst

### Did you find any workaround?

Use Time Machine to revert to previous VS Mac before updates.

### Relevant log output

```shell
none
```

**Comment by anurkalem** [comment]
I have another type of this issue. My collection view is become incorrect height according to parent size view after update. I am waiting new update...

![ScreenShot](https://github.com/dotnet/maui/assets/13329201/9dd5ca56-9ba5-4fe0-b197-e16da728800d)

**Comment by cdavidyoung** [comment]
Is this iOS?  If so, I would recommend using a Time Machine backup to roll back to the day before the update.  This is easily done with Migration Assistant.

**Comment by janseris** [comment]
Seems like they dropped out the testers between MAUI Preview 24 and 25.
Or did they not have them since Preview 13?

**Comment by anurkalem** [comment]
> Is this iOS? If so, I would recommend using a Time Machine backup to roll back to the day before the update. This is easily done with Migration Assistant.

Yes it is iOS but I will never downgrade anything in my career. I will wait next upgrade :)

**Comment by taublast** [comment]
Unfortunately it's not only CollectionView. They heavily broken something related to expanding layouts on iOS/MacCatalyst.

**Comment by taublast** [comment]
> I have another type of this issue. My collection view is become incorrect height according to parent size view after update. I am waiting new update...
> 
> ![ScreenShot](https://user-images.githubusercontent.com/13329201/239684055-9dd5ca56-9ba5-4fe0-b197-e16da728800d.png)

Are you inside a grid, can you post your layout?

**Comment by cdavidyoung** [comment]
Yes.  My collection view is in row 1.

`  <Grid>
      <Grid.RowDefinitions>
        <RowDefinition Height="Auto"></RowDefinition>
        <RowDefinition Height="*"></RowDefinition>
        <RowDefinition Height="Auto"></RowDefinition>
      </Grid.RowDefinitions>

      <Grid Grid.Row="1">
        <CollectionView x:Name="collectionView"
                        ItemsSource="{Binding Records}"
                        BackgroundColor="LightGrey">

`

**Comment by MichalPeterek** [comment]
Add this:

`    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="100"/>
            <RowDefinition Height="2*"/>
            <RowDefinition Height="100"/>
        </Grid.RowDefinitions>
        <Rectangle BackgroundColor="Red" Grid.Row="0"/>
        <Rectangle BackgroundColor="Green" Grid.Row="1"/>
        <Rectangle BackgroundColor="Blue" Grid.Row="2"/>
    </Grid>`

Add this on top of ContentPage and run as Mac Catalyst when app started, all sems to be working good, but when window is resized down middle rectangle not changing. When window is resizing up, then all working good.

**Comment by headintheclouds21** [comment]
I'm having the same issue with maccatalyst layouts. My application is currently unusable because of this.

**Comment by cdavidyoung** [comment]
There is really no reason for your app to be unusable.  Just use Time Machine to roll back to before the update. This is easily done with Migration Assistant.  I have since continued development and even released a new version of my app.

BTW, after rolling back VS Mac says there is an update to 17.5.6.3.  Is that the update that broke things?  I seem to remember that there were 4 updates to several components but I don't remember what they were.

**Comment by MichalPeterek** [comment]
> There is really no reason for your app to be unusable. Just use Time Machine to roll back to before the update. This is easily done with Migration Assistant. I have since continued development and even released a new version of my app.
> 
> BTW, after rolling back VS Mac says there is an update to 17.5.6.3. Is that the update that broke things? I seem to remember that there were 4 updates to several components but I don't remember what they were.

Not all people using timemachine :)

**Comment by kocevilija** [comment]
I have put `<MauiVersion>7.0.52</MauiVersion>` in the `.csproj` file inside first `PropertyGroup`, right below the `SupportedOSPlatformVersion`s tag and it works.

However, this is a workaround and problem should be fixed in the new MAUI version.

**Comment by gy-mate** [comment]
@janseris Yeah, you're right. Anyways, I'll just use a PC at uni, I got enough of debugging MAUI instead of my actual assignment :)
