### ISSUE TITLE
Navigation between top level pages fail in Unpackaged WinUI application

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#15180]
### Description

Using the 7.0 Navigation sample available [here](https://github.com/dotnet/maui-samples/tree/main/7.0/Navigation/ShellFlyoutSample) and building unpackaged for WinUI. Open the application and attempt to navigate between pages in the flyout. You'll observe that the pages change in the flyout, but the content itself does not change. 

This does not occur in a WinUI application

### Steps to Reproduce

1. Clone https://github.com/dotnet/maui-samples/tree/main/7.0/Navigation/ShellFlyoutSample
2. Publish WinUI Unpackaged with `/p:WindowsAppSDKSelfContained=true`
3. Open and navigate between pages

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/7.0/Navigation/ShellFlyoutSample

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 22621.963

### Did you find any workaround?

Negative. Workarounds would be appreciated.

### Relevant log output

```shell
No log, no crash, extremely difficult to debug.
```

**Comment by drasticactions** [comment]
Unpackaged WinUI apps are currently unsupported: https://github.com/dotnet/maui/issues/10564

**Comment by mattleibow** [comment]
`WindowsAppSDKSelfContained` is not for unpackaged, but rather for including the WindowsAppSDK runtime in the app - which is now the default.

I am not sure this is related to unpackaged, but more an issue in shell.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 3. Not repro on
Unpackaged WinUI application with sample project. 
Reference: [Use the CLI to publish unpackaged apps for Windows - .NET MAUI | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-unpackaged-cli?view=net-maui-8.0)
