### ISSUE TITLE
Blazor: oncontextmenu doesn't work on iOS devices

### ISSUE THREAD

**Issue by Kebechet** [dotnet/maui#15199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The contextmenu event is not fired on Safari for iOS as it seems to be not compatible.
https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event#browser_compatibility

This introduces problems for webpages working in browser or for hybrid apps (.NET MAUI Blazor) - our case

Even though this event is not supported by the browser itself, you on the Blazor side could wire it with their ontouchdown, ontouchup like mentioned here: https://github.com/facebook/react/issues/17596#issuecomment-565524946

### Steps To Reproduce

Put `<button @oncontextmenu="HandleLongPress" >Long Press Meeeeeeee</button>` into your Blazor page and
```
@code{
    private void HandleLongPress(MouseEventArgs eventArgs) {
        Console.WriteLine($"Long press detected on element: {eventArgs.ScreenX};{eventArgs.ScreenY}");
    }
}
```

On longpress (on android) or rightClick (on windows) it works and triggers the `HandleLongPress` but not on the iOS Blazor webview

### .NET Version

7.0.203

**Comment by Kebechet** [comment]
@javiercn thanks for comment. Just yesterday I did so:
https://github.com/Kebechet/Blazor.EventHandlers.LongPress
and I will use it as a temporary workaround.

But still `oncontextmenu` is built-in thing and the bahavior that it doesnt work as expected just on iOS Safary is negatively surprising and would be convinient to have it fixed even though it is not problem on your side.

+ on MAUI Blazor this thing is blocked by: https://github.com/dotnet/maui/issues/15201

**Comment by javiercn** [comment]
It can be done without using an initializer. You can call Blazor.start manually, await the promise and you should be able to register it there too.

**Comment by Kebechet** [comment]
@javiercn but in MAUI hybrid the BlazorWebView calls the Blazor.Start in the background, doesnt it ?

**Comment by jupdike** [comment]
I successfully implement the solution here: https://github.com/Kebechet/Blazor.EventHandlers.LongPress and it works with a simple @onlongpress attribute now.

**Comment by Kebechet** [comment]
@mkArtakMSFT so just to be clear, the final solution is "we wont change original behavior of native events like `oncontextmenu` you should handle it yourself" ?
So I know in the future what to or not to report.
