### ISSUE TITLE
Failures in the MAUI Hello World app (part of the onboarding webpages)

### ISSUE THREAD

**Issue by errveen** [dotnet/maui#15197]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Here are all the errors I received after trying to install all the Maui / Xamarin / Xcode stuff:

.../MyFirstMauiApp/Platforms/Android/Resources/values/colors.xml(5,5): Error: Assets file '.../MyFirstMauiApp/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. (MyFirstMauiApp)
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/16.4.7060/tools/msbuild/iOS/Xamarin.Shared.targets(3,3): Error: /usr/bin/xcrun exited with code 134:
2023-05-20 22:33:58.803 ibtoold[82850:3133777] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot7/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21779/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:79
Details:  DVTExtendedPlatformInfo: Synthesized watchos Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <_NSMainThread: 0x600003ed8000>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-05-20 22:33:58.804 ibtoold[82850:3133777] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot7/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21779/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:79
Details:  DVTExtendedP (MyFirstMauiApp)
.../MyFirstMauiApp/obj/Debug/net7.0-maccatalyst/maccatalyst-x64/actool/cloned-assets/Assets.xcassets: Error: 2023-05-20 22:33:58.803 ibtoold[82850:3133777] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot7/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21779/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:79
Details:  DVTExtendedPlatformInfo: Synthesized watchos Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <_NSMainThread: 0x600003ed8000>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-05-20 22:33:58.804 ibtoold[82850:3133777] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot7/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21779/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:79
Details:  DVTExtendedPlatformInfo: Synthesized driverkit Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <_NSMainThread: 0x600003ed8000>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-05-20 22:33:58.804 ibtoold[82850:3133777] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot7/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21779/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:79
Details:  DVTExtendedPlatformInfo: Synthesized iphonesimulator Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <_NSMainThread: 0x600003ed8000>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-05-20 22:33:58.804 ibtoold[82850:3133777] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot7/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21779/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:79
Details:  DVTExtendedPlatformInfo: Synthesized appletvsimulator Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <_NSMainThread: 0x600003ed8000>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-05-20 22:33:58.804 ibtoold[82850:3133777] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot7/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21779/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:79
Details:  DVTExtendedPlatformInfo: Synthesized watchsimulator Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <_NSMainThread: 0x600003ed8000>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-05-20 22:33:58.804 ibtoold[82850:3133777] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot7/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21779/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:79
Details:  DVTExtendedPlatformInfo: Synthesized appletvos Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <_NSMainThread: 0x600003ed8000>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-05-20 22:33:58.804 ibtoold[82850:3133777] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot7/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21779/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:79
Details:  DVTExtendedPlatformInfo: Synthesized iphoneos Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
Object:   <DVTExtendedPlatformInfo>
Method:   +extendedPlatformInfoForPlatformIdentifier:error:
Thread:   <_NSMainThread: 0x600003ed8000>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2023-05-20 22:33:58.823 ibtoold[82850:3133777] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.AssetCatalogAppleTVKit (/Applications/Xcode.app/Contents/Frameworks/AssetCatalogAppleTVKit.framework), error = Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Applications/Xcode.app/Contents/Frameworks/AssetCatalogAppleTVKit.framework/AssetCatalogAppleTVKit, 0x0109): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: <3BBE2003-EF36-3115-AE6A-186F08B021A7> /Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/Versions/A/IDEInterfaceBuilderCocoaTouchIntegration
  Reason: tried: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/Library/Frameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/System/Library/Frameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file, not in dyld cache)" UserInfo={NSLocalizedFailureReason=The bundle couldn’t be loaded., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/Frameworks/AssetCatalogAppleTVKit.framework/AssetCatalogAppleTVKit, NSDebugDescription=dlopen(/Applications/Xcode.app/Contents/Frameworks/AssetCatalogAppleTVKit.framework/AssetCatalogAppleTVKit, 0x0109): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: <3BBE2003-EF36-3115-AE6A-186F08B021A7> /Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/Versions/A/IDEInterfaceBuilderCocoaTouchIntegration
  Reason: tried: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/Library/Frameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/System/Library/Frameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file, not in dyld cache), NSBundlePath=/Applications/Xcode.app/Contents/Frameworks/AssetCatalogAppleTVKit.framework, NSLocalizedDescription=The bundle “AssetCatalogAppleTVKit” couldn’t be loaded.}, dyldError = dlopen(/Applications/Xcode.app/Contents/Frameworks/AssetCatalogAppleTVKit.framework/AssetCatalogAppleTVKit, 0x0000): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: <3BBE2003-EF36-3115-AE6A-186F08B021A7> /Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/Versions/A/IDEInterfaceBuilderCocoaTouchIntegration
  Reason: tried: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/Library/Frameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/System/Library/Frameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file, not in dyld cache)

A required plugin failed to load. Please ensure system content is up-to-date — try running 'xcodebuild -runFirstLaunch'.
 (MyFirstMauiApp)
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/16.4.7060/tools/msbuild/iOS/Xamarin.Shared.targets(3,3): Error: actool exited with code 134
         (MyFirstMauiApp)
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/16.4.7060/tools/msbuild/iOS/Xamarin.Shared.targets(3,3): Error: Failed to load actool log file `obj/Debug/net7.0-maccatalyst/maccatalyst-x64/actool/asset-manifest.plist`: Failed to parse PList data type: 
         (MyFirstMauiApp)

**Comment by errveen** [comment]
Had to re-run the XCode install and install additional components, then compile the sample app 3 times. After that, ti ran.

**Comment by Xyncgas** [comment]
> Had to re-run the XCode install and install additional components, then compile the sample app 3 times. After that, ti ran.

Of course, MAUI is not a typical project it's mobile development
