### ISSUE TITLE
[Enhancement] Add ability to embed the wwwroot web files when using Blazor Wpf and WinForms controls

### ISSUE THREAD

**Issue by budcribar** [dotnet/maui#1520]
## Summary
Add ability to embed the wwwroot web files when using Blazor Wpf and WinForms controls.

## API Changes
Currently, neither of the Blazor controls support embedding the wwwroot files into the executable and publish as a single file. This could be a major security issue especially if the application runs as an administrator. The restriction is also  an installation inconvenience. In order to support this feature, the publishing step would first have to generate the wwwroot files before they could be embeded. Also, the Blazor controls would have to support reading the wwwroot files with the ManifestEmbeddedFileProvider which they currently do not.

## Intended Use Case

To be able to deliver a Wpf or WinForms app that would not let users inadvertently or maliciously change the behavior of the program by replacing files under wwwroot.

**Comment by Eilon** [comment]
Hi @budcribar this is something we can look into, but I want to make sure there isn't a security issue here I'm missing. Once an app is installed, no "regular" user can modify its files, including static HTML files. Users can only change files that they own. An admin can always change any file anywhere on the computer. This is no different than someone replacing a "good" DLL file with a "malicious" DLL file.

Having said that, I agree that it could be nice to have a single-file EXE for some scenarios, so that's worth considering.

**Comment by budcribar** [comment]
Hi @Eilon The security concern is that I could copy the winform or wpf .exe to a directory that I have access to as a non-admin. Once, I have the .exe, all I need to do is replace the wwwroot folder with my malicious version which would dump a secret file that requires admin permission to read and  voilà I know your secrets. This scenario is arguably easier to implement than using a similar procedure to replace a .dll, but it is one in which a major client of mine has forbidden due to security concerns. The bottom line for me is that I would not be able to pass a security review unless the wwwroot files are embedded. I have added this feature into RemoteBlazorWebView.Wpf and RemoteBlazorWebView.WinForms, but it is a real hack because you need to publish once to get the wwwroot built (if you are using other Blazor components) and then again to embed the wwwroot files. That said, I'm good for now :)

**Comment by Eilon** [comment]
We'll look into supported single-file projects, but this is not something that is considered a security issue of any degree. If the application is in a location that is writeable, someone could just as easily replace the entire EXE with a malicious app. There's no need to just edit an HTML or JS file in some subtle or malicious way.
