### ISSUE TITLE
Assets file '.../MauiTutorialProject/obj/project.assets.json' not found. Run NuGet package restore to generate this file.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#15215]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Assets-file-MauiTutorialProjectobj/10370034)._

---
I am running Visual Studio 17.5.5 (build 12) on Mac Venturea 13.3.1 (a). I am trying to go through the .NET MAUI tutorials so I am following the online pages, I am not creating a new project on my own yet. I am currently on this page: https://learn.microsoft.com/en-us/training/modules/build-mobile-and-desktop-apps/4-exercise-create-your-first-maui-app. When I compile the sample application that was generated by Visual Studio (no code changes made my me). I get the following error:

Assets file '.../MauiTutorialProject/obj/project.assets.json' not found. Run NuGet package restore to generate this file.

(The … is the path to where I have the solution on disk)

The error says it’s occuring on line 266 of file colors.xml. Here is the colors.xml file that it’s referring to:

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="colorPrimary">#512BD4</color>
    <color name="colorPrimaryDark">#2B0B98</color>
    <color name="colorAccent">#2B0B98</color>
</resources>

CLEARLY NOT 266 lines long. Anyway, I have been combing the Internet to try to solve this problem and I’m not finding a solution yet. Here’s what I’ve done so far:

1. Right-click the Solution and then clicked Restore NuGet Packages. Didn’t fix it.

2.In Terminal, navigated to the root project folder and entered the command “dotnet restore”. Output was:

     Determining projects to restore…
     All projects are up-to-date for restore.

Rebuilt the solution, still get the error.

3. In Terminal, navigated to the root project folder and entered the command “dotnet restore —force”. Output was:

     Determining projects to restore…
     Restored /…/MauiTutorialProject/MauiTutorialProject.csproj (in 490ms).

Rebuilt the solution and got the same error.

4. In Visual Studio, clicked on Tools -> Manage NuGet Packages… Attempted to locate project.assets.json anywhere in this UI and did not find it. Searched across all four tabs that appear here.

5. In Terminal, navigated to the project OBJ folder and I see the file is there (project.assets.json). I tried “dotnet restore” here, but it didn’t work - not the location for the project or solution file (I thought I’d try this here as a last resort).

Judging by the fact that there seems to be many complaints across about 6 years of posts, this isn’t a one-off problem. My problem is that all the posts that I read and tried didn’t solve this issue. 

So, my question is, how can I solve this on my current configuration?

---
#### Feedback Bot on 5/21/2023, 07:11 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rachelkang** [comment]
Hi, Kevin - thanks for opening this issue. Please share a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis) with us so that we can investigate this issue further. Thanks!
