### ISSUE TITLE
TextColor throws exception on Windows Machine

### ISSUE THREAD

**Issue by roysurles** [dotnet/maui#15210]
### Description

Setting TextColor property in xaml, throws following exception on Windows Machine.  Works on Android emulator.
"Cannot assign property "TextColor": Property does not exist, or is not assignable, or mismatching type between value and property"

TextColor="{StaticResource PrimaryBrush}"

### Steps to Reproduce

1. Create a File --> New .Net MAUI Application
2. Edit MainPage.xaml & add TextColor="{StaticResource PrimaryBrush}" to one of the Labels.
3. Run on Windows Machine

Throws exception:  "Cannot assign property "TextColor": Property does not exist, or is not assignable, or mismatching type between value and property"

Works on Android Emulator.

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by rachelkang** [comment]
(Note for team: @mattleibow suspects this may be an intellisense issue)

**Comment by roysurles** [comment]
Hi, using Visual Studio 2022 v17.6.1, Create a File --> New .Net MAUI Application
![image](https://github.com/dotnet/maui/assets/37274814/5ba31940-08ee-4ae4-ac2e-17a9cbcc460e)

Edit MainPage.xaml & add TextColor="{StaticResource PrimaryBrush}" to one of the Labels.
![image](https://github.com/dotnet/maui/assets/37274814/a8a3be3c-5353-41d5-9ff2-e22d9e979301)

Run on Windows Machine
![image](https://github.com/dotnet/maui/assets/37274814/559bc377-6751-44d8-b850-838765519be9)

Throws exception: "Cannot assign property "TextColor": Property does not exist, or is not assignable, or mismatching type between value and property"
![image](https://github.com/dotnet/maui/assets/37274814/5fef871c-27da-4961-aeec-472dbf544dd5)

**Comment by jsuarezruiz** [comment]
> Hi, using Visual Studio 2022 v17.6.1, Create a File --> New .Net MAUI Application ![image](https://user-images.githubusercontent.com/37274814/240708854-5ba31940-08ee-4ae4-ac2e-17a9cbcc460e.png)
> 
> Edit MainPage.xaml & add TextColor="{StaticResource PrimaryBrush}" to one of the Labels. ![image](https://user-images.githubusercontent.com/37274814/240709139-a8a3be3c-5353-41d5-9ff2-e22d9e979301.png)
> 
> Run on Windows Machine ![image](https://user-images.githubusercontent.com/37274814/240709309-559bc377-6751-44d8-b850-838765519be9.png)
> 
> Throws exception: "Cannot assign property "TextColor": Property does not exist, or is not assignable, or mismatching type between value and property" ![image](https://user-images.githubusercontent.com/37274814/240709490-5fef871c-27da-4961-aeec-472dbf544dd5.png)

The TextColor property expect a Color and you are assigning a Brush. There is a mismatch between property and value.
