### ISSUE TITLE
On iOS Launcher.OpenAsync presents Open-In/ShareSheet Menu but closes immediately (.net MAUI)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#15216]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/On-iOS-LauncherOpenAsync-presents-Open-/10362740)._

---
\[severity:I’m unable to use this version\]  
I’m using .net MAUI.  
On iOS Launcher.OpenAsync presents Open-In/ShareSheet Menu but closes immediately  
On Android it’s fine.  
This is the code I’m using  
await Launcher.OpenAsync(new OpenFileRequest(“my\_title”, new ReadOnlyFile(my\_file\_name)));

---
#### Feedback Bot on 5/15/2023, 01:29 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drasticactions** [comment]
<img width="465" alt="スクリーンショット 2023-06-09 12 17 09" src="https://github.com/dotnet/maui/assets/898335/e72c125f-8617-4e33-b43d-46fb3907f942">

```
macos                   13.3.7060/7.0.100      SDK 7.0.300
maui-android            7.0.86/7.0.100         SDK 7.0.300
ios                     16.4.7060/7.0.100      SDK 7.0.300
maccatalyst             16.4.7060/7.0.100      SDK 7.0.300
maui                    7.0.86/7.0.100         SDK 7.0.300
tvos                    16.4.7060/7.0.100      SDK 7.0.300
android                 33.0.46/7.0.100        SDK 7.0.300
```

With the following workloads, I tried running this on iOS and Catalyst, and it worked. The share menu stayed on screen and did not go away until I clicked away.

What workloads are you running? Is this on device?

**Comment by athtse** [comment]
I have test it on 3 different iPhones.
I did not test it on simulator.
I'm new at MAUI and I don't know anything about workloads.
I just created a new MAUI project and the problem is there.

**Comment by drasticactions** [comment]
@athtse Can you run `dotnet workload list` in a command prompt and tell me the output?

**Comment by athtse** [comment]
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maccatalyst                16.4.7060/7.0.100      VS 17.7.33711.374
runtimes-windows             7.0.5/7.0.100      VS 17.7.33711.374
ios                              16.4.7060/7.0.100      VS 17.7.33711.374
maui-windows                 7.0.86/7.0.100      VS 17.7.33711.374
maui-maccatalyst            7.0.86/7.0.100       VS 17.7.33711.374
maui-ios                          7.0.86/7.0.100       VS 17.7.33711.374
maui-android                  7.0.86/7.0.100       VS 17.7.33711.374
android                         33.0.46/7.0.100        VS 17.7.33711.374

**Comment by drasticactions** [comment]
So trying this on my Mac, on an iPhone and two iPads, it worked fine and did the same thing as the simulators. But since your sources say "VS" I'm guessing you're running Windows, and since you've only tested Devices and not Simulators, I'm guessing you're using "Hot Restart" with no connected Mac. Is that correct?

**Comment by athtse** [comment]
I'm using Visual Studio on Windows.
I have paired a MAC and connected the iPhone to the MAC.
The point is that my app on apple store has the same problem.
The problem stays the same both on Release and Debug Mode.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 3. Not repro on iOS simulator & devices with sample project. 
https://github.com/athtse/MauiApp1.git
