### ISSUE TITLE
xmlns can't access its classes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#15217]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/xmlns-cant-access-its-classes/10355207)._

---
I made xaml namespaces many times before, and they were working well, but suddenly  they stop recognizing their classes, and the intelliSense stopped suggesting the public classes and 10 errors occurred.
that happened in all projects.
the xaml code is:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
xmlns:local="using: HossamTest1.behaviorsfolder"
             x:Class="HossamTest1.BehaviorPage"
             Title="BehaviorPage"
     
>
    <StackLayout >
        <Entry Placeholder="behavior" local: NumericBehaviorValidation.NumricValidation="true" >
        </Entry>
        
</StackLayout>
</ContentPage>
```
the code behind is

```
namespace HossamTest1;

public partial class BehaviorPage : ContentPage
{
	public BehaviorPage()
	{
		InitializeComponent();
	}

}
```
and the NumericBehaviorValidation class is

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HossamTest1.behaviorsfolder
{
    public static class NumericBehaviorValidation
    {
        public static readonly BindableProperty NumricValidationProperty =
                    BindableProperty.CreateAttached("NumricValidation",typeof(bool),typeof(NumericBehaviorValidation),false,propertyChanged:OnValidation );
        public static bool getNumricValidationProperty(BindableObject view)
        {
            return (bool)view. GetValue(NumricValidationProperty);
        }
        public static void setNumricValidationProperty(BindableObject view,bool value)
        {
            view. SetValue(NumricValidationProperty,value);
        }
        public static void OnValidation(BindableObject view, object  oldvalue,object newvalue)
        {
            Entry entry=view as Entry;
            if (entry == null)
            {
                return;
            }
            bool valid = (bool)newvalue;
            if (valid) 
            {entry. TextChanged+= OnValidationHandler;
            }
            else
            {
                entry. TextChanged -= OnValidationHandler;
            }
        }
        static void OnValidationHandler(object sender, TextChangedEventArgs e)
        {
            Entry entry=sender as Entry;
            double result;
            bool isvalid=double. TryParse(e.NewTextValue, out result);
            entry. TextColor=isvalid? Colors.Green:Colors.Red;
        }
    }
}

```
the error list is
Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0413	The property '<Unknown>' was not found in type 'Entry'.	HossamTest1	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml	10	
Error	XLS0112	Expected '='.	HossamTest1	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml	10	
Error	XLS0304	Expected an attribute value. Attribute values are delimited by a single quotation mark (') or a double quotation mark (").	HossamTest1	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml	10	
Error	XLS0415	The attachable property 'NumricValidation' was not found in type 'NumericBehaviorValidation'.	HossamTest1	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml	10	
Error	MAUIG1001	An error occured while parsing Xaml: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 10, position 45..	HossamTest1 (net7.0-android)	D:\hossam\backup2\HossamTest1\HossamTest1\HossamTest1.csproj	1	Active
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	HossamTest1 (net7.0-android), HossamTest1 (net7.0-ios), HossamTest1 (net7.0-maccatalyst), HossamTest1 (net7.0-windows10.0.19041.0)	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml.cs	7	Active
Error	MAUIG1001	An error occured while parsing Xaml: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 10, position 45..	HossamTest1 (net7.0-ios)	D:\hossam\backup2\HossamTest1\HossamTest1\HossamTest1.csproj	1	Active
Error	MAUIG1001	An error occured while parsing Xaml: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 10, position 45..	HossamTest1 (net7.0-maccatalyst)	D:\hossam\backup2\HossamTest1\HossamTest1\HossamTest1.csproj	1	Active
Error	MAUIG1001	An error occured while parsing Xaml: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 10, position 45..	HossamTest1 (net7.0-windows10.0.19041.0)	D:\hossam\backup2\HossamTest1\HossamTest1\HossamTest1.csproj	1	Active

---
#### Feedback Bot on 5/4/2023, 07:20 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
It looks like you have an extra space between the namespace prefix and the class name - maybe that's causing problems?

```xaml
<Entry Placeholder="behavior" local: NumericBehaviorValidation.NumricValidation="true" >
```
