### ISSUE TITLE
[NET 8, Windows] wrong initial BindingConext in CollectionView DataTemplate

### ISSUE THREAD

**Issue by Vroomer** [dotnet/maui#15212]
### Description

The BindingContext for DataTemplates in CollectionView seems to be broken in .NET 8 (all previews). Upon loading the CollectionView Items, the template object initially receives BindingContex reference to the BindingContext of the CollectionView parent. Immediately after it receives another BindingContext reference - this time the right reference to the Model of Items. This behavior has big performance impact because it sets Bindings twice and causes BindingFailures during the first cycle.

Tested on Windows and Windows subsystem for Android - only Windows version seems affected.

### Steps to Reproduce

1. Load the repository and run the app in debug mode.
2. Add new Items to the CollectionView using the button.
3. Observe raising count of BindingFailures with reference to wrong BindingContext. Data are displayed correctly, because it eventually receives the right BindingContext. The behavior is tracked in the Debug output window:

- Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Name' property not found on 'MauiApp4.MainPageViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
- Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Description' property not found on 'MauiApp4.MainPageViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
- current BindingContext: MainPageViewModel
- current BindingContext: Model

### Link to public reproduction project repository

https://github.com/Vroomer/MAUI-wrong-initial-BindingContext-in-CollectionView-DataTemplate.git

### Version with bug

8.0.0-preview.4.8333

### Last version that worked well

7.0.86

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

All the .NET 7 builds seem working properly, including nightly releases.

**Comment by Vroomer** [comment]
Seems working in preview 5.

**Comment by petrochuk** [comment]
Same here

**Comment by Redth** [comment]
Thanks for reporting back!
