### ISSUE TITLE
Obsolete ImageSource.FromResource

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#15225]
### Description

There's a discussion in https://github.com/dotnet/maui/issues/8666 about loading images from embedded resources no longer being a recommended practice (see https://github.com/dotnet/maui/issues/8666#issuecomment-1550534641).

Bearing that in mind, perhaps now's a good time to obsolete `ImageSource.FromResource`?

**Comment by janseris** [comment]
What is the replacement?

**Comment by Zhanglirong-Winnie** [comment]
Feature changes, Now the MauiImage could be import.
