### ISSUE TITLE
Backport fixing WebView Cookie to .NET 7

### ISSUE THREAD

**Issue by mhrastegari** [dotnet/maui#15239]
### Summary
We've got a .NET MAUI Blazor application that uses WebView for a case and it's only works well in .NET 8 pre 3!
But it's not a wise choice for us to upgrade a production app to a preview SDK.

**Comment by mattleibow** [comment]
Added the backport label so we can review and see what needs to be done for:
 - https://github.com/dotnet/maui/pull/13736
 - https://github.com/dotnet/maui/pull/13518

**Comment by mhrastegari** [comment]
Thanks!
