### ISSUE TITLE
[Blazor] Maui windows apps can't find _framework/blazor.modules.json

### ISSUE THREAD

**Issue by javiercn** [dotnet/maui#15234]
For some reason the apps fail to find the file and as a result initializers don't load. It works fine in other platforms like Android

**Comment by vnbaaij** [comment]
@mkArtakMSFT, @javiercn We are running into this when using the Blazor Fluent UI library in A Blazor Hybrid project (see https://github.com/microsoft/fluentui-blazor/issues/404#issuecomment-1570174528). Any indication on if/when/how this is solved? And are there known workarounds (besides building your own Microsoft.AspNetCore.Components.WebView :))?

**Comment by vnbaaij** [comment]
@mkArtakMSFT, @javiercn, one of our contributors has created a nice workaround for this. See https://github.com/microsoft/fluentui-blazor#tempory-workaround-for-maui-issues for the details.

**Comment by LuohuaRain** [comment]
is this PR relevant?
https://github.com/dotnet/aspnetcore/pull/48594

**Comment by Jarek300** [comment]
Is this problem fixed in .NET 8? 

Do Blazor JS module initializers work in NET 8 in Blazor Hybrid? Is loading file wwwroot/{AppName}.lib.module.js in Blazor hybrid / BlazorWebView fixed?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Can repro this issue.

**Comment by javiercn** [comment]
This should be fixed in https://github.com/dotnet/maui/pull/18953

**Comment by datvm** [comment]
@javiercn  Hi when is this fix released? And when it is released, do the old projects that use the workaround need to remove it? We have tons of MAUI projects that is currently using the `initializersLoader.webview.js`

**Comment by BretJohnson** [comment]
This indeed does look to be fixed in .NET9. With .NET9, you should _not_ use the workaround https://github.com/microsoft/fluentui-blazor?tab=readme-ov-file#temporary-workaround-for-mauiwpfwindows-forms-issues, for Blazor Fluent UI, and in fact things won't work if you do since now the modules file is named `_framework/blazor.modules.json` and the workaround has it look for `<app-name>.modules.json`, which is no longer generated.
