### ISSUE TITLE
Windows HorizontalList CollectionView has some weird space if cells are smaller than 88 dp

### ISSUE THREAD

**Issue by unombun** [dotnet/maui#15241]
### Description

On Windows just create a horizontal collection view. If the cell has a width smaller then ~88dp a space will appear until the next cell

![image](https://github.com/dotnet/maui/assets/11754566/c1564c16-9bb2-4819-97ee-2aab65c15dc8)

### Steps to Reproduce

1. Create a MAUI App for Windows
2. Add a horizontal list CollectionView with items that are smaller than 88 dp.
3. The content of the cell will become smaller, but then a space until the next cell will appear. Somehow like there is a minimum cell width.

### Link to public reproduction project repository

https://github.com/flesarradu/WindowsHorizontalCollectionViewSpacingIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

-

### Did you find any workaround?

No

**Comment by bwoebi** [comment]
This affects CollectionViews in both directions equally - on my end it seems like Windows forces a Height of at least 40 for each entry in the CollectionView.

**Comment by mrderon** [comment]
@samhouts Can you please confirm that this fix is working? I'm using 8.0.0-preview.7.8842 with the sample app given in #12495  and it still doesn't seem to work (result still has the red spacing as initially reported).
