### ISSUE TITLE
Flyout Page: iOS version doesn't have a native hamburger icon for the flout menu

### ISSUE THREAD

**Issue by kubaflo** [dotnet/maui#15258]
### Description

Expected Behavior:
The application should display a hamburger icon as the button to open the flyout menu.

Current Behavior:
The application does not generate a hamburger icon. Instead, the Title property of a component, possibly a button or a text element, is being used as the button to open the flyout menu.

### Steps to Reproduce

1. Launch the iOS application.
2. Navigate to the screen or view where the flyout menu should be accessible.
3. Look for a hamburger icon in the navigation bar or any other expected location.
4. Observe that no hamburger icon is displayed.
5. Instead, identify if there is a Title property associated with a component.
6. Interact with the Title property and observe if it opens the flyout menu.

<img src="https://github.com/dotnet/maui/assets/42434498/be1b6762-1d63-4d62-b715-f654e04815e3" width="400px"/>

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/7.0/Navigation/FlyoutPageSample

### Version with bug

8.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Set a custom icon for IconImageSource property of the FlyoutPage

**Comment by drasticactions** [comment]
I don't believe this is a bug. This is the default behavior for Flyout view, as it was in Xamarin.Forms.

There is no "default" hamburger menu icon for iOS. It's not a native iOS component. There is a "hamburger menu" that appears within Shell, but that is an [included image](https://github.com/dotnet/maui/blob/97b77448c72179c8843d9b684cdc798f0b8d7529/src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs#L436) within Forms/MAUI. (Although this is shown under Compatability, I'm unsure if a newer implementation is pointing to something else). So, the default behavior for iOS/Catalyst with this control would be to show the title text of the button. This is the same behavior as it was on Xamarin.Forms, so everything is intact from it.

You can override that with your own icon image, as you've seen and is [documented](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout#flyout-icon).

@PureWeen What do you think? Is there anything that we could do here? Am I missing any context?

**Comment by BioTurboNick** [comment]
Actually, did something change in a recent iOS version or phone layout? Because when I run my app on my iPhone SE, it has a hamburger icon. But my app is now being rejected by the Apple Store because it's missing (with screenshots), so users have no way to know there's functionality in the menu.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Can repro on iOS platform with sample project. 
https://github.com/dotnet/maui-samples/tree/main/7.0/Navigation/FlyoutPageSample

**Comment by kubaflo** [comment]
@drasticactions what do you think about adding a new property to FlyoutPage eg. `HasHabmurgerIcon` that would draw the same hamburger icon as shell page when this property is set to true and FlyoutPage has no icon set?

**Comment by Thaldoras** [comment]
When I add a custom hamburger icon for iOS using IconImageSource.
The image gets stretched and does not take up the same space as the back button on iOS.
On Android it works perfectly. The burger icon gets changed to the back icon as you navigate and they are the same size.

Also suffers from the color of the icon being changed. e.g. you use a png icon with green colour and then it turns to gray or whatever default color is set somewhere.
