### ISSUE TITLE
Brakes ... Maui Windows so it will not startup suspected Xaml Grid Pattern with * (stars) 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#15276]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Brakes--Maui-Windows-so-it-will-not-s/10372310)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.5.5]
Brakes ... Maui Windows so it will not startup suspected Xaml Grid Pattern with * (stars)  (or too many "*"'s)

"Element not found. (0x80070490)"

similar to 

https://github.com/dotnet/maui/issues/9905

---
#### Feedback Bot on 5/23/2023, 09:35 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
Can you post your XAML Grid layout?
