### ISSUE TITLE
[Bug] XAML HOT Reload stops at initialize with Android Emulator

### ISSUE THREAD

**Issue by madlotus** [dotnet/maui#1528]
XAML HOT Reload stops at initialize with Android Emulator

### Steps to Reproduce

1. dotnet new maui -n HelloMaui
2. ./HelloMaui.sln
3. inside VS 2k22 edit MainPage.xaml first Label text
4. F5

### Expected Behavior

XAML HOT Reload working

### Actual Behavior

XAML HOT Reload initializing but stops at one second.

### Basic Information

- IDE: Visual Studio 2022 Preview
- NET: 6.0.100-preview.5.21302.13
- Platform Target Frameworks:
  - Android: Android 11.0 API 30
- Affected Devices: Pixel 3 XL R 11.0

### Screenshots

![Screen](https://i.imgur.com/vOeO3mS.png)

**Comment by drasticactions** [comment]
This is a .NET 6 Runtime bug, not a MAUI nor XAML Hot Reload issue. It was fixed as part of https://github.com/dotnet/runtime/pull/54757 and has a PR to be inserted into Preview 6  (https://github.com/dotnet/runtime/pull/54763) but it hasn't shipped yet.

**Comment by madlotus** [comment]
solved with

- Visual Studio 2022 Version 17.0.0 Preview 2.0
- dotnet 6.0.100-preview.6.21355.2
