### ISSUE TITLE
Windows Titlebar where Close-Max-Min buttons rendered are different from where they are clickable

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [dotnet/maui#15297]
### Description

the close maximize and minimize buttons render on the right side of the window titlebar but they are only clickable and have the hover effect from the opposite direction (the left side) 

https://github.com/dotnet/maui/assets/7858946/af32d2ad-ee20-4fd6-bfac-b71511e2a618

the system localization settings (think it's what causing the problem)
![Screenshot 2023-05-26 185132](https://github.com/dotnet/maui/assets/7858946/8fc08d5b-720e-421d-a010-d8199b49f8a1)
![Screenshot 2023-05-26 185209](https://github.com/dotnet/maui/assets/7858946/9b1767f7-4774-4619-8971-e458b722d7f0)

### Steps to Reproduce

1. create a new maui project
2. run the windows app
3. try to close it from the Titlebar Close button

### Link to public reproduction project repository

*

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows 11

**Comment by Eilon** [comment]
Looks same as https://github.com/dotnet/maui/issues/7751, but that one was closed, yet 2 days ago another person mentioned it still repros.

**Comment by Eilon** [comment]
Looks like the other issue mentioned a workaround, in case you need to un-block your progress: https://github.com/dotnet/maui/issues/7751#issuecomment-1439715657

**Comment by ahmed-abdelrazek** [comment]
yes it's the same problem (was searching for an issue with titlebar or close button that's why i didn't find it)
will try the work around 
but i'm not surprised it's not the first time winui 3 had a problem with rtl languages that is why i mentioned localization settings

**Comment by ahmed-abdelrazek** [comment]
the work around doesn't work @Eilon 
it seems that maui can't find WinRT and want me to install a package from uno

**Comment by Eilon** [comment]
@ahmed-abdelrazek it's a little hard for me to tell, but is the situation that the hamburger menu is correctly on the left side, but it's hidden by the "Market" text? And the "Market" text should be on the _right_ side?

**Comment by ahmed-abdelrazek** [comment]
@Eilon the "Market" text should be next to the hamburger menu not under it 
and i can't find an option to control its margin or padding

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1. This issue repro on Windows 11(**7.0.101**), but not repro on Windows 11(**8.0.3**):
Repro project: [15297.zip](https://github.com/dotnet/maui/files/13435273/15297.zip)
![TitleBar](https://github.com/dotnet/maui/assets/97647558/bbd3ebed-1738-4b10-bb9b-c0dd4cb146e9)
