### ISSUE TITLE
In the maui blazorWebView development, in order to display images provided by external websites, Content-Security-Policy is used, and data: http: https: has been specified, as follows:

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#15299]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/In-the-maui-blazorWebView-development-i/10374007)._

---
Add to index.html in wwwroot:
<meta http-equiv="Content-Security-Policy" content="img-src data: https: http:" /> 
The window program can display all pictures normally.

However, only http: external network images can be displayed on android devices, and the https: protocol cannot display images.

![image](https://github.com/dotnet/maui/assets/202643/ad15bfa0-8508-4022-ace5-d9986808bb76)

It has been confirmed that the relevant picture can be opened, but the HTTPS cannot be displayed in the APP, and I am puzzled.

---
#### Feedback Bot on 5/24/2023, 07:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Seems to be related to https://github.com/dotnet/maui/issues/10141.

@Eilon do you think this is the same issue or different?

**Comment by Eilon** [comment]
> Seems to be related to #10141.
> 
> @Eilon do you think this is the same issue or different?

Not sure, it could be related.

**Comment by Jockeyvb** [comment]
This is the issue I submitted on the window is working.

**Comment by Jockeyvb** [comment]
look,debug on android device  :![image](https://github.com/dotnet/maui/assets/16102290/52f98e7d-47ae-435f-a80c-a23d4d8c1e45)

Chrome open this pic is ok . but andorid device ,Strangely enough, using HTTP can display it normally, bugs?

**Comment by Jockeyvb** [comment]
device:User-Agent: Mozilla/5.0 (Linux; Android 8.1.0; DUB-AL20 Build/HUAWEIDUB-AL20; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36

**Comment by janseris** [comment]
Try Android 9 or 10, is it the same? Android 8.1 in .NET had issues with SSL/TLS connections (websocket, TDS, ...)

**Comment by janseris** [comment]
@mkArtakMSFT adding needs info on vs feedback will not notify any real person

**Comment by Jockeyvb** [comment]
@janseris try android 9.0 https :
![image](https://github.com/dotnet/maui/assets/16102290/ccb4b2a5-83d9-48bb-bc38-f8604d7d59ab)

**Comment by Jockeyvb** [comment]
![image](https://github.com/dotnet/maui/assets/16102290/ce682a10-e7d1-484a-9469-96ac830320e5)
run at Android emulator Accessing HTTPS with a certificate displays normally, but displaying certificates with errors is not normal

android 8.1 had error not show image .

**Comment by mkArtakMSFT** [comment]
Do you have a repro we can try out?

**Comment by mkArtakMSFT** [comment]
We think this is due to a non-trusted / invalid certificate that your app is using. Unfortunately, there is no more data for us to come up with other explanations.

**Comment by Jockeyvb** [comment]
@mkArtakMSFT 
thx
> We think this is due to a non-trusted / invalid certificate that your app is using. Unfortunately, there is no more data for us to come up with other explanations.

i think you right

**Comment by SteveSandersonMS** [comment]
Thanks for all the info! At this point we think it's best to close the issue as it seems to be understood now.
