### ISSUE TITLE
Java.Lang.IllegalArgumentException when I try to start a ForegroundService

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/maui#15292]
### Description

I would like to start a Foreground Service using the overload method of StartForeground in which I can pass as parameter the permission that I need for the service.

This is the documentation: [](https://developer.android.com/about/versions/14/changes/fgs-types-required#permission-for-fgs-type)

My code is this:

In the manifest, I include this:

```
      <service
          android:name=".AlarmasForegroundService"
          android:foregroundServiceType="location"
          android:exported="false">
      </service>
```

And this is how I start the ForegroundService:

```
var notificationManager = (GetSystemService(Context.NotificationService) as NotificationManager)!;

createNotificationChannel(_notificationManager);


Notification notification = new Notification.Builder(this, NOTIFICATION_CHANNEL_ID)

    .SetContentTitle("GTS Registros Horarios")
    .SetContentText($"{DateTime.Now}: Se han iniciado las alarmas.")
    .SetSmallIcon(Resource.Drawable.logo32x32)
    .SetAutoCancel(false)
    .SetOngoing(false)
    .Build();

//Java.Lang.IllegalArgumentException
StartForeground(NOTIFICATION_ID, notification, Android.Content.PM.ForegroundService.TypeLocation);
```

But when I try to call the StartForeground service, I get this error:

`Java.Lang.IllegalArgumentException: 'foregroundServiceType 0x00000008 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file'`

How could I request the permission when i call the StartForeground() method? Because according to the documentation, it is needed from Android 14 because if not, I would get a security exception.

Thanks.

### Steps to Reproduce

1. Create a Foreground service.
2. try to start the foreground service passing the permission as parameter.

### Link to public reproduction project repository

not needed

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 33

### Did you find any workaround?

I don't have any workaround.

**Comment by philipag** [comment]
I'm afraid you don't really include enough information to diagnose the problem and this is probably not a MAUI bug. For instance is your app getting ACCESS_FINE_LOCATION or coarse location permission? Without that it won't work.

You should read through https://developer.android.com/about/versions/14/changes/fgs-types-required

**Comment by ComptonAlvaro** [comment]
I have  all permissions needed.  The application works if I don't use the overload method of StartForegreound that takes 2 arguments, the ID and notification.

**Comment by philipag** [comment]
In our app we only use the 2 parameter StartForeground().  If you don't include the third parameter (service type) then it will just use the service declared service type which in your case is already "location" so you can just use the method with 2 parameters instead.  That is what we do and it works properly.

If you do that, do things work properly?

**Comment by ComptonAlvaro** [comment]
Yes, if I use the method with two parameters it works with no problems.

My doubt is about the documentation: [](https://developer.android.com/about/versions/14/changes/fgs-types-required?hl=es-419#include-fgs-type-runtime)

It seems that is recommended to use the method with the three parameters, in which in the the third parameter, I can pass all the needed permissions.

Perhaps I misunderstood and the documentation doesn't recomend to use this method with three parameters and it is enough to use the method with two parameters.

**Comment by TalipV** [comment]
Yes. Android 14 requires that third parameter and for some reason the service declaration in the AndroidManifest is treated as if not existent.

**Comment by Zhanglirong-Winnie** [comment]
According to the user’s latest reply, the user’s problem no longer recurs, so we add a non-recurrence tag.
