### ISSUE TITLE
ResourceDictionary get item operator weird behaviour

### ISSUE THREAD

**Issue by andrey-onischenko** [dotnet/maui#15312]
### Description

Here are screenshots from debugger and code. You can see that there's item when you use MergedResources enumerator, but when you use IDictionary enumerator or accessing through index, it can't found any value.
![image](https://github.com/dotnet/maui/assets/117270710/b1815ab7-25c9-47cf-babd-6b890584293f)
![image](https://github.com/dotnet/maui/assets/117270710/e7a52fdd-e623-40e0-9afa-f6cc9aba2aee)
![image](https://github.com/dotnet/maui/assets/117270710/a51eab56-d2f3-4de0-9300-d3a4bdb5688f)
![image](https://github.com/dotnet/maui/assets/117270710/38c16a84-2c70-4073-8e69-c0a02602574b)

### Steps to Reproduce

Create simple maui project and try accessing anything in Styles.xaml by using Application.Current.Resources[index]. It will work from xaml, but not from c#. You can call it from constructor or from OnAppearing, doesn't matter.

### Link to public reproduction project repository

_

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android version doesn't matter

**Comment by andrey-onischenko** [comment]
It's critical, you can't somehow use static resources from c#

**Comment by janseris** [comment]
Try using it in an event handler when app is already fully living. Does it work then?
I have had an issue using resources when using dependency injection.
https://github.com/dotnet/maui/issues/11485

**Comment by Dreamescaper** [comment]
Probably it this issue: https://github.com/dotnet/maui/issues/8799
Try using TryGetValue.

That said, I don't understand why that issue is closed. Even if it is not possible to fix it now, this issue is still present, and the item shouldn't be closed.

**Comment by andrey-onischenko** [comment]
Yeah, it's the same problem. I think it can be fixed by iterating through MergedResources and check if key is the same. But it might be quite inefficient for applications with a lot of resources. I might commit to repo with this fix, but I'm not sure if it will comply with all rules.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 4, can repro this issue with repro steps.
![image](https://github.com/dotnet/maui/assets/77434865/f1ef7dd0-e202-4348-a86f-59859046b524)

**Comment by janseris** [comment]
Could the official MAUI tester test it so that it doesn't sink into closed issues if the author does not follow it?
