### ISSUE TITLE
adding net7.0 tfm to project with handlers crashes

### ISSUE THREAD

**Issue by veldfolds** [dotnet/maui#15314]
### Description

![VideoDemos - Microsoft Visual Studio 5_28_2023 5_54_35 PM](https://github.com/dotnet/maui/assets/52108581/7e4bb902-1f6e-467a-83d7-22de247d33de)
![VideoDemos - Microsoft Visual Studio 5_28_2023 5_53_40 PM](https://github.com/dotnet/maui/assets/52108581/d44f95fe-623b-4bc8-9b82-cd8e1f69b5a8)
![VideoDemos - Microsoft Visual Studio 5_28_2023 5_54_12 PM](https://github.com/dotnet/maui/assets/52108581/6d4b5fba-0f81-4c5f-9f7a-c7a9c0dce714)

### Steps to Reproduce

New project
Add handlers
Add net7.0 in tfm list in csproj

### Link to public reproduction project repository

https://github.com/veldfolds/VideoDemos.git

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12 & 13, Windows 10 19044.2075 & up

**Comment by drasticactions** [comment]
The errors are telling you what to do. You added a net7.0 TFM, which is a standard non-platform-specific target framework. You don't have code implemented for it, so it's telling you to implement it.

If you remove that TFM, or implement the code it's telling you to implement, it will work.

**Comment by veldfolds** [comment]
I can't remove the tfm because i'll be adding a reference to a .net7.0 class library and a .net7.0 maui class library which break without the .net7.0 tfm. so what code should i implement because i do not understand

**Comment by mattleibow** [comment]
A .NET MAUI app can reference a net7.0 class library. For example, net7.0-android app can reference a net7.0 library. Not the other way around.

A .NET MAUI app should be able to reference a .NET MAUI class library.

What error do you get when you reference the class libraries (force adding the net7.0 TFM)?
