### ISSUE TITLE
[Bug] iOS layout keeps adding margin which is locking up the layout and the app

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1531]
### Description

then the bounds/center are adjusted => triggers SetNeedsLayout => this calls LAyoutSubviews => layoutSubviews measures again but now adds the margin again => go back to beginning of this list

### Steps to Reproduce

1. Run ios controls samples
2.  go to Controls => Editor
3. app freezes

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Redth** [comment]
#1471 seems to do some things with not repeating adding margin, perhaps that helps here too?
