### ISSUE TITLE
DeviceInfo not working in iOS

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#15315]
### Description

Try to use DeviceInfo while debugging a physical device connected by USB - just returns garbage. Wrong Name, OS, device type - in fact everything is wrong.

TBH, by this point I would have been more surprised if it actually worked.

### Steps to Reproduce

Plug iPhone into USB connected to a Mac.
Debug
Call DeviceInfo - e.g. DeviceInfo.Name

### Link to public reproduction project repository

?

### Version with bug

8.0.0-preview.3.8149

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Can you demonstrate it failing on your device? Could you create a sample app to output that info and show it on screen? Does it work on simulators? Does it work in net6/net7?

**Comment by JohnHDev** [comment]
Running on .NET 7 on an iOS simulator I see the correct name: iPhone 14 Pro Max.

**Comment by williambuchanan2** [comment]
> Running on .NET 7 on an iOS simulator I see the correct name: iPhone 14 Pro Max.

Yes it seems to work on simulators

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 3 & Visual Studio for Mac 17.6.8. Not repro with MAUI and Xamarin iOS project.
![image](https://github.com/dotnet/maui/assets/77434865/82b00821-7ff8-4200-affe-86d0182d6acf)
