### ISSUE TITLE
[iOS] Grid with BoxView inside calculates incorrect width when ColumnsSpacing is non zero.

### ISSUE THREAD

**Issue by Hooterr** [dotnet/maui#15328]
### Description

When you put a BoxView inside a Grid layout with column spacing that is not zero, the layout calculates the wrong width.

When you replace BoxView with ContentView it magically works again.

<img src="https://github.com/dotnet/maui/assets/28758721/7f0abaa4-d284-4e76-b463-b164289b9d25" width="400"/>

```xaml
 <Grid HeightRequest="56"
       ColumnSpacing="20"
       ColumnDefinitions="*,20,auto,20,*">

      <BoxView
          Grid.ColumnSpan="5"
          Color="Red"/>

       <Label
          VerticalTextAlignment="Center"
          Text="BoxView with Grid.Spacing=20"
          Grid.Column="2"/>
  </Grid>
```

### Steps to Reproduce

1. Make a grid with columns
2. Add columns spacing
3. Put a BoxView inside that spans all the columns

### Link to public reproduction project repository

https://github.com/Hooterr/MauiGridBoxViewBug

### Version with bug

7.0.86

### Last version that worked well

7.0.58

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

### Did you find any workaround?

Use `ContentView` instead of `BoxView`

**Comment by LukeFranky** [comment]
I'm seeing this bug too.

For anyone reading, if you have a choice, for the love of all things programming, don't use MAUI.

**Comment by rachelkang** [comment]
Hi, @Hooterr  - we believe this issue may be fixed in the latest .NET 8 Preview. Please let us know if you continue to see issues on that version!

**Comment by omghb** [comment]
I believe this is about the same or a similar issue: 
- https://github.com/dotnet/maui/issues/15195

Unfortunately, we cannot try out a unstable preview version (VS preview, .NET preview) in our environment. If it would be just a NuGet package then we will be happy to try it out.

**Comment by Hooterr** [comment]
@rachelkang I'll test it in .net 8 but there's no excuse to not to include this in .net 7.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0. This issue does not repro on 7.0.92 and 8.0.0-rc.1.9171.
Repro project:
[MauiGridBug(8.0).zip](https://github.com/dotnet/maui/files/12698132/MauiGridBug.8.0.zip)
[MauiGridBug(7.0).zip](https://github.com/dotnet/maui/files/12698150/MauiGridBug.7.0.zip)

iOS:
![image](https://github.com/dotnet/maui/assets/97647558/5c73a237-f514-4c43-b65d-15f9aa5e1c3b)
