### ISSUE TITLE
Progress bar - add feature  intermediate = true like in WPF

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#15324]
### Description

////

### Public API Changes

....

### Intended Use-Case

////

**Comment by danies8** [comment]
In WPF the progress bar  has feature IsIntermmidiate Boolean  flag that when is true the progress is in activity all times
when false its stops.

**Comment by jfversluis** [comment]
Please put a little more effort in your feature proposals for them to be considered. Think of things like: proposed API to use, does this mean a breaking change for existing users, screenshots, mockups, or just add text and not just a title.

The above together with not much traction on this issue in about a year means I will close this one for now.
