### ISSUE TITLE
[Android] Sign APK in release mode

### ISSUE THREAD

**Issue by latinosamuel** [dotnet/maui#15323]
### Description

When I run the project in release mode with the apk signature option activated, I get the following error:

Target _Sign:

    /Users/samuellatino/Library/Android/sdk/build-tools/32.0.0/zipalign -p 4 "obj/Release/net7.0-android/android/bin/com.companyname.maui.apk" "bin/Release/net7.0-android//com.companyname.maui-Signed.apk" 
    /Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home/bin/java -jar /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.46/tools/apksigner.jar sign --ks Platforms/Android/Keystore/keystore.keystore --ks-pass pass:Teste-MAUI --ks-key-alias Teste-KeyStore --key-pass pass:Teste-MAUI --min-sdk-version 21 --max-sdk-version 33 Teste-MAUI  bin/Release/net7.0-android/com.companyname.maui-Signed.apk 
    /Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home/bin/java -jar /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.46/tools/apksigner.jar sign --ks Platforms/Android/Keystore/keystore.keystore --ks-pass pass:Teste-MAUI --ks-key-alias Teste-KeyStore --key-pass pass:Teste-MAUI --min-sdk-version 21 --max-sdk-version 33 Teste-MAUI  bin/Release/net7.0-android/com.companyname.maui-Signed.apk 
    Unexpected parameter(s) after input APK (bin/Release/net7.0-android/com.companyname.maui-Signed.apk)
    /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.46/tools/Xamarin.Android.Common.targets(2361,2): error MSB6006: "java" exited with code 1.
Done building target "_Sign" in project "MAUI.csproj" -- FAILED.

Done building project "MAUI.csproj" -- FAILED.

### Steps to Reproduce

1º Download project:  https://github.com/latinosamuel/MAUI-KeyStore
2º Run the project in release mode.
3º The previous error will appear.

### Link to public reproduction project repository

https://github.com/latinosamuel/MAUI-KeyStore

### Version with bug

7.0.86

### Last version that worked well

7.0.81

### Affected platforms

Android

### Affected platform versions

Android 33

### Did you find any workaround?

No

**Comment by rachelkang** [comment]
Hi, @latinosamuel - Could you please provide a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis) so that we can investigate further? Thanks

cc @jonathanpeppers

**Comment by jonathanpeppers** [comment]
This `$(AndroidApkSignerAdditionalArguments)` setting doesn't look right:

https://github.com/latinosamuel/MAUI-KeyStore/blob/03455ad502b3d2c38c6451914a990e477f0408da/MAUI/MAUI.csproj#L42

Can you remove it? It doesn't look like a valid switch to `apksigner`.

A `.binlog` would tell us more and should contain the error message from `apksigner`.

**Comment by latinosamuel** [comment]
Hi @jonathanpeppers,
Removing the line of code, the problem no longer happens.
Thanks.
