### ISSUE TITLE
Support for Dragging and Dropping Files from System Explorer into a .NET MAUI Application

### ISSUE THREAD

**Issue by McoreD** [dotnet/maui#15331]
Hello,

I am currently developing an application using .NET MAUI and I am interested in implementing a feature where users can drag files from their system's file explorer (like Windows Explorer or Finder on macOS) and drop them into my MAUI application.

In the past, I have implemented this type of functionality in Windows Forms and WPF applications using the `DragDrop` and `DragEnter` events. However, I am having trouble finding a way to implement this in a MAUI application.

While I understand that .NET MAUI provides support for dragging and dropping elements within an application through the `DragGestureRecognizer` and `DropGestureRecognizer` classes, I am specifically looking for a way to drag files from the system file explorer and drop them into my application.

As far as I can tell, this feature is not currently available in .NET MAUI. I think this would be a valuable addition to the framework, as it would allow developers to create more interactive and intuitive user interfaces, especially for desktop applications.

If this feature is already available and I have missed it, I would appreciate if you could point me towards the relevant documentation or examples. If it's not, could you please consider this as a feature request?

Thank you for your time and consideration.

**Comment by Dokug** [comment]
I am not sure if this is your exact question, but maybe this will help you?
https://vladislavantonyuk.github.io/articles/Drag-and-Drop-any-content-to-a-.NET-MAUI-application
