### ISSUE TITLE
Grid Overflow when content is too large

### ISSUE THREAD

**Issue by lk-code** [dotnet/maui#15342]
### Description

The first line consists of 3 buttons with icon. Between them is a button with text. If the text is too big, the text should be cut off. Instead the content goes out of the display (see screenshot)

<img width="441" alt="Bildschirmfoto 2023-05-30 um 22 40 50" src="https://github.com/dotnet/maui/assets/1656571/4344f33e-8caa-4c2f-a264-3071b70430b7">

that is the xaml:

`....`
`<ContentPage.Content>`
`<Grid RowDefinitions="Auto,Auto,Auto,*"`
`ColumnDefinitions="Auto,*,Auto,Auto"`
`ColumnSpacing="8"`
`RowSpacing="8"`
`Margin="10"`
`HorizontalOptions="Fill"`
`VerticalOptions="Fill">`
`....`

### Steps to Reproduce

see description xaml

### Link to public reproduction project repository

there is no public repo

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16.4 Simulator and Device

**Comment by TheJarX** [comment]
I've got the same issue. I did tested on Android and it seems fine, the problem seems to be with iOS and MacOS. Hoping someone can help us out; just started on this yesterday.

**Comment by mattleibow** [comment]
Fixed in .NET 7 and .NET 8

<img width="418" alt="image" src="https://github.com/dotnet/maui/assets/1096616/167463ce-6fb7-486a-840c-f39e3f3b1014">
