### ISSUE TITLE
IsVisible binding not showing items again if Shadow is set

### ISSUE THREAD

**Issue by dan-matthews** [dotnet/maui#15357]
### Description

A very, very strange bug! It always works correctly on Windows, but on Android there is a bug. In my app, the IsVisible for a button is set using binding (MVVM). Setting IsVisible false will always hide the button, but setting IsVisible true is NOT showing the button.  However, I found that a styling for the Button was causing the issue. Specifically, the setter (in a Styles.xaml file) was as follows:

        <Setter Property="Shadow">
            <Shadow Brush="Black"
                Offset="4,4"
                Opacity="0.9" />
        </Setter>

When the setter is swapped for individual setters, the IsVisible works:

        <Setter Property="Shadow.Offset" Value="4,4"/>
        <Setter Property="Shadow.Opacity" Value="0.9"/>
        <Setter Property="Shadow.Brush" Value="Black"/>

For some reason, the 'nested' style setter for Shadow seems to be affecting the visibility toggle of the element, but only on Android.

### Steps to Reproduce

1. Create a starter Maui app (XAML)
2. Add the following to the Button style in Styles.xaml

`
        <Setter Property="Shadow">
            <Shadow Brush="Black"
                Offset="4,4"
                Opacity="0.9" />
        </Setter>`

4. Add a button to the MainPage with IsVisible to a bound property initialized false
5. Toggle the bound property to true (e.g. via another button)

Expected: Button becomes visible
Actual: Button stays hidden

### Link to public reproduction project repository

(https://github.com/dan-matthews/VisibleTest)

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11+

### Did you find any workaround?

Use individual style setters for Shadow.

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue on current main branch:
![issue-15357](https://github.com/dotnet/maui/assets/6755973/cb955528-c69f-4b40-9e8b-3f058bfbbf63)

**Comment by PureWeen** [comment]
Duplicate of #15826
