### ISSUE TITLE
Border size changes appear to be animated on iOS/MacCatalyst

### ISSUE THREAD

**Issue by DancesWithDingo** [dotnet/maui#15363]
### Description

When I use the Border control in a page, when first drawn (and in subsequent redraws/resizes) the border/contents appear to animate the changes. This results in weird visual artifacts that don't occur when using layout controls with background color set.

### Steps to Reproduce

Create a .NET MAUI project with a button and a border within a vertical stack layout. Wire up the button click handler so it toggles the width of the border. Notice that the border size change seems to be animated as compared to the vertical stack layout without the border. This only happens on iOS and MacCatalyst.

```
<VerticalStackLayout Spacing="20" Padding="20">
    <Button Text="Toggle Width" HorizontalOptions="Center" Clicked="Button_Clicked"/>
    <VerticalStackLayout x:Name="Container" Spacing="20" MinimumWidthRequest="100">
        <Border Stroke="Firebrick" StrokeThickness="10" BackgroundColor="Yellow" HeightRequest="200">
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="20"/>
            </Border.StrokeShape>
        </Border>

        <VerticalStackLayout HeightRequest="200" BackgroundColor="Orange"/>
    </VerticalStackLayout>
</VerticalStackLayout>
```

``` cs
void Button_Clicked(System.Object sender, System.EventArgs e) {
    Container.HorizontalOptions = Container.HorizontalOptions.Alignment == LayoutOptions.Fill.Alignment ? LayoutOptions.Start : LayoutOptions.Fill;
}
```

https://github.com/dotnet/maui/assets/11809753/59120b16-0958-4492-a9cd-c6b21fbca142

### Link to public reproduction project repository

https://github.com/DancesWithDingo/MAUI_BorderFillChange.git

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.4

### Did you find any workaround?

No. And the visual impact can be horrendous when many borders appear on a page.

**Comment by CurtisTodd** [comment]
Has anyone found a work around for this? I am also suffering grief from this animation. I have had to switch some of my Borders to Frames until this issue is resolved or a workaround is found.

For reference, in an attempt to debug the problem I tried overriding most methods in BorderHandler and doing this:

UIView.PerformWithoutAnimation(() =>
{
    CATransaction.Begin();
    CATransaction.DisableActions = true;

    //Original base method call

    CATransaction.Commit();
});

But this did NOT work.

**Comment by Hooterr** [comment]
It's a default iOS behavior but it would be great to be able to control it. It's super unnatural in collection views when you scroll through items and everything just animates like crazy.

**Comment by Hooterr** [comment]
```csharp
Microsoft.Maui.Handlers.BorderHandler.Mapper.PrependToMapping("DON'T ANIMATE YOU FILTHY ANIMAL", (handler, view) =>
{
    foreach (var layer in handler.PlatformView.Layer.Sublayers)
    {
        layer.RemoveAllAnimations();
    }
    handler.PlatformView.Layer.RemoveAllAnimations();

});
```

This sort of worked for me. It doesn't remove all the animations but in a collection view it stops doing background animations.

**Comment by DancesWithDingo** [comment]
It’s good to learn that this is coming from CALayer. Thanks for your research.On Jun 22, 2023, at 02:35, Maksymilian Lach ***@***.***> wrote:﻿
It's a default iOS behavior but it would be great to be able to control it. It's super unnatural in collection views when you scroll through items and everything just animates like crazy.

**Comment by DancesWithDingo** [comment]
I've created a temporary workaround for the Border control by using a behavior that sets PlatformView's Layer properties. I updated the sample repository to show an example of usage. In this case, the behavior works on any layout control, but I'm using it by temporarily replacing Border with ContentView.

https://github.com/dotnet/maui/assets/11809753/271769ae-2d28-413d-9e12-80f03f5b1808

It's a bit inelegant, but as I only use Border within my own BorderView control, it was a quick fix that can be removed when Border is repaired. My borders all use a round rectangle, but other shapes can be implemented.

The second rectangle (light green) is a VSL with the BorderBehavior added.

Note the green bar: that's to proved that the borders are actually the correct thickness. Apparently there's a bug on iOS that renders borders at half the thickness specified...I've only just noticed it, but it doesn't happen on Android so it's likely a bug. I'll have to report that a little later.

**Comment by matheusouz** [comment]
I had the same problem, that was fixed in this PR https://github.com/dotnet/maui/pull/15856/files, its easy to apply the fix while is not release to .NET 7

**Comment by durandt** [comment]
@matheusouz Would you care to share your workaround/fix? The PR fixes 3-4 issues and has changes to the iOS ContentView that I don't find so easy to apply. How did you go about, and what pieces did you take from the PR? (I'm mainly interested in stopping the size change animation)
