### ISSUE TITLE
MAUI Blazor Hybrid does not respect device language on iOS for datetime

### ISSUE THREAD

**Issue by vallgrenerik** [dotnet/maui#15364]
### Description

Hello!

I've created a simple MAUI Blazor Hybrid application and using 
```
<input type="date" title="Date"/>
<input type="time" title="Time" >
```
mixes both English and Swedish (my preferred language) 
![image](https://github.com/dotnet/maui/assets/26163937/9d7cbe1a-279c-45a5-8a99-7a48d86cb064)
![image](https://github.com/dotnet/maui/assets/26163937/627c4ba7-bbca-414f-9562-d0cdc7518613)

### Steps to Reproduce

1. Create new MAUI Blazor Hybrid App
2.  Add 
```
<input type="date" title="Date"/>
<input type="time" title="Time" >
```
3. Connect to MAC
4. Set your simulator to another language and format
5. Run the application

### Link to public reproduction project repository

https://github.com/vallgrenerik/MauiApp2_Input_Time_Date.App

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Does it behave correctly on other platforms? 

Would you maybe be able to try following this: https://blog.verslu.is/xamarin-forms-xamarin/localization-default-ios-controls/

And see if that helps things?

**Comment by vallgrenerik** [comment]
> Does it behave correctly on other platforms?
> 
> Would you maybe be able to try following this: https://blog.verslu.is/xamarin-forms-xamarin/localization-default-ios-controls/
> 
> And see if that helps things?

Yeah it works fine on android. I will check the info.plist thing tomorrow! Thanks @jfversluis 😊

**Comment by vallgrenerik** [comment]
> > Does it behave correctly on other platforms?
> > Would you maybe be able to try following this: https://blog.verslu.is/xamarin-forms-xamarin/localization-default-ios-controls/
> > And see if that helps things?
> 
> Yeah it works fine on android. I will check the info.plist thing tomorrow! Thanks @jfversluis 😊

@jfversluis I can confirm that setting the ```CFBundleLocalizations``` works! 
Awesome, thanks for the quick answer!

**Comment by jfversluis** [comment]
Perfect, thanks for letting us know!
