### ISSUE TITLE
Using INotify interface in single modal for Blazor and Maui

### ISSUE THREAD

**Issue by premshahdev** [dotnet/maui#1536]
### Discussed in https://github.com/dotnet/maui/discussions/1381

<div type='discussions-op-text'>

<sup>Originally posted by **PremSha20** June 19, 2021</sup>
I want to write a single modal which is going to use in Blazor App and Maui App. 
I am little bit confused regarding Implement INotify Interface Because Blazor do not need INotify Interface to be Implemented in its modal but Maui need.
so here is my question

1. Does is it good practise to use Single modal in Maui and Blazor App ? 
2. By using INotify interface for blazor is going to side effect or bad performace ?  
3. What is good Practise to use single modal in both Blazor and DotNet Maui ?

Note : I am already aware of DotNet Maui For Blazor but it is not realated to my question.</div>

**Comment by Eilon** [comment]
Hi @premshahdev , this is ultimately an app design question depending on how you want to build your app and how you want it to behave. You can use INotifyXyz in both MAUI and Blazor, but you might have to write some adapters to make it work in both.

If you use something like INotifyXyz, then in Blazor you could connect that to an event that would call `StateHasChanged()` and in .NET MAUI it would fit more naturally with a typical MVVM design.
