### ISSUE TITLE
BlazorWebView.HostPage does not support URI pack notation

### ISSUE THREAD

**Issue by AndersenBell** [dotnet/maui#15373]
### Description

I am trying to create a WPF library using blazor components.

When I try to use the WPF UserControl that I created in my library that contains a BlazorWebView, it will never render, and always display "There is no content at".

It looks like the index.html needs to be embedded in the executing application, which I cannot do since it's a third-party application that I am building a component for. 

If it would be possible to use the pack notation to specify the WPF Library assembly and make the index.html a resource, then it would make everything work.

### Steps to Reproduce

1. Create a new WPF app.
2. Create a new WPF Library and set it up like the example at https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-7.0 but make sure its a library
3. Create a UserControl instead of the Window in the example
4. Add the UserControl to the WPF App's MainWindow

### Link to public reproduction project repository

https://github.com/AndersenBell/BlazorWebView.HostPage-bug.git

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10+

### Did you find any workaround?

No, it does not seem like there is a workaround.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
