### ISSUE TITLE
ICanvas DrawString does not work on MacCatalyst platform

### ISSUE THREAD

**Issue by grempel** [dotnet/maui#15370]
DrawString tosses an exception every Time. "Value cannot be null. (Parameter 'handle').

Any plans to fix this? This is a complete lack of functionality. For my app its a show stopper.

Thanks,
Gerry

The code is too simple to require a sample.

**Comment by drasticactions** [comment]
![Test Image](https://github.com/dotnet/maui/assets/898335/c0e71e08-517d-4afc-a02c-a9fd72fce83b)

https://github.com/drasticactions/MauiRepros/tree/main/MauiDrawString

Workload List
```
wasm-tools              7.0.5/7.0.100          SDK 7.0.200
macos                   13.3.7060/7.0.100      SDK 7.0.200
ios                     16.4.7060/7.0.100      SDK 7.0.200
maccatalyst             16.4.7060/7.0.100      SDK 7.0.200
maui                    7.0.86/7.0.100         SDK 7.0.200
tvos                    16.4.7060/7.0.100      SDK 7.0.200
android                 33.0.46/7.0.100        SDK 7.0.200
```

I can use DrawString without issues on Mac Catalyst, using the newest MAUI stable release. Can you try my reproduction sample to see if it works for you? It could be that you're using an older version, or you could have done other things within your code that is causing DrawString to throw (Maybe setting a font?), which could be a bug we can look at. This is generally why we request repro projects, so we can make sure that all sides can recognize the bug and validate it.

**Comment by grempel** [comment]
Net Maui has two DrawString methods on ICanvas. The one that takes a bounding box works. The one that takes only the starting X and Y location of the string does not work and tosses an exception every time when run on MacCatalyst. 

Tim's example above uses the bounding box DrawString and works properly. I've changed my code to use this as well. The bug remains - only 50% of your DrawString methods work on the MacCatalyst platform.

Thanks,
Gerry

**Comment by drasticactions** [comment]
![Samplel(https://github.com/dotnet/maui/assets/898335/231241cd-0470-4c1e-8d7c-89d54c4c4424)

I updated my sample and while it didn't draw the string (which makes sense I think, as it's not bound to any width or height) nothing was thrown. 

I don't doubt you're seeing an exception, but this is why we need reproducible samples so we can see if this is something local to your setup or if everyone else can hit the same thing you are.

**Comment by drasticactions** [comment]
@mattleibow Would you have any tips for this?

**Comment by mattleibow** [comment]
I can have a look at why nothing is drawn in the overload, but for the exception we will need a repro as you said.
