### ISSUE TITLE
No Android SDK instance matching the 'C:\Program Files (x86)\Android\android-sdk' path

### ISSUE THREAD

**Issue by zoid66** [dotnet/maui#15381]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by gizaha** [comment]
I realised that I had this problem and it cost me 2 days to solve it.

I went to 

C:\Users\user\AppData\Local\Xamarin\AndroidDevices.exe_Url_vad3ja0bqgjyvgyibkftpvyz0n12l5ed\17.6.0.76

and deleted the user.config file (it was empty), then i opened android device manager, it opened ok and it created a new user.config file.

What happened in the first place:

I try to start android device manager, bsod and then android device manager didn't start, instead it returned in console output:

"Xamarin - 17.6.0.251-d17-6+318364c

No Android SDK instance matching the 'C:\Program Files (x86)\Android\android-sdk' path"

Countless tries of repair/reinstalling xamarin etc etc didn't work

**Comment by tklempay** [comment]
> I realised that I had this problem and it cost me 2 days to solve it.
> 
> I went to
> 
> C:\Users\user\AppData\Local\Xamarin\AndroidDevices.exe_Url_vad3ja0bqgjyvgyibkftpvyz0n12l5ed\17.6.0.76
> 
> and deleted the user.config file (it was empty), then i opened android device manager, it opened ok and it created a new user.config file.
> 
> What happened in the first place:
> 
> I try to start android device manager, bsod and then android device manager didn't start, instead it returned in console output:
> 
> "Xamarin - 17.6.0.251-d17-6+318364c
> 
> No Android SDK instance matching the 'C:\Program Files (x86)\Android\android-sdk' path"
> 
> Countless tries of repair/reinstalling xamarin etc etc didn't work

In the process of porting a Xamarin native app (android and ios) to .NET MAUI.  Updated my Visual Studio to 17.6.2 to get the latest maui bits and support for xcode 14.3.  After the VS update, I too received the **No Android SDK instance matching the 'C:\Program Files (x86)\Android\android-sdk' path"** message and Visual Studio won't startup any of my android emulators.  I can't shake it.  Unfortunately, your workaround did not work for me.  

I'm on Day 3 of trying to get my android emulators back :-(

**Comment by Amine-Smahi** [comment]
I have the problem too :(

**Comment by garda-bonifaccio** [comment]
Same issue

**Comment by CarmineLyria** [comment]
Bumping this; same issue. Visual Studio suggested updating my GPU drivers; that didn't seem to help.

**Comment by gizaha** [comment]
Workaround is simple: We don't program for android. I'm not gonna test
solutions that maybe result in bsod each time. I don't program for android.
Android loses, not me, i gain money from other sources.

**Comment by Lioncky** [comment]
Too many problems about android, I've wait microsoft for one year but still too much probs, maybe microsoft need to change the member who just piss away the time

**Comment by samhouts** [comment]
Was anyone here able to open a Visual Studio feedback ticket for this issue? Thanks!

**Comment by AmirImam** [comment]
Is there any solution to this problem right now? I have the same issue
