### ISSUE TITLE
[Enhancement] Make Wpf and WinForms BlazorWebView public classes.

### ISSUE THREAD

**Issue by budcribar** [dotnet/maui#1538]
## Summary
The Wpf and WinForms BlazorWebView are sealed classes. This restriction is not on other WinForms or Wpf controls. Leveraging these classes forces either the copying of all of the code or keeping an internal instance of the Microsoft control and forwarding everything to it. Neither is a good solution.

## API Changes
Change "public sealed class BlazorWebView" to "public class BlazorWebView" for both Wpf and Winforms versions of BlazorWebView.cs

## Intended Use Case
Provide developers to add functionality to the base WebView classes without the need to copy all of the associated source code or keep an internal instance and forward functionality.

**Comment by Eilon** [comment]
Very nice find, I think this was unintentional! Here's a PR to fix it: https://github.com/dotnet/maui/pull/1573
