### ISSUE TITLE
[Enhancement] FontNames for OnIdiom

### ISSUE THREAD

**Issue by Codelisk** [dotnet/maui#1539]
## Summary
Provide FontNames support for Setter

## API Changes

e.g.

In Order to use OnIdiom Setter for Fonts efficient I would try to do something like that:

```
 <Setter Property="FontSize">
            <Setter.Value>
                <OnIdiom Default="Medium"
                         Tablet="Large" />
            </Setter.Value>
        </Setter>
```

Unfortunately at the moment I can only insert numbers into OnIdiom here:
 ```
 <Setter Property="FontSize">
            <Setter.Value>
                <OnIdiom Default="24"
                         Tablet="40" />
            </Setter.Value>
        </Setter>
```

## Intended Use Case
Easier use for Setter OnIdiom

**Comment by hartez** [comment]
This should now be working (as of Preview 10).
