### ISSUE TITLE
Release 7.0.86 refers non-existing packages

### ISSUE THREAD

**Issue by BjornEGlomsrud** [dotnet/maui#15392]
### Description

Maui Release 7.0.86 refers versions of dependencies that do not exist.

Refer to:
https://maui.blob.core.windows.net/metadata/rollbacks/7.0.86.json
contains these packages with versions that do not exist - at least in the normal nuget repos.
However, version 16.4.7054/7.0.100 exists. Typo?

- microsoft.net.sdk.ios: "16.4.7045/7.0.100"
- microsoft.net.sdk.maccatalyst: "16.4.7045/7.0.100"
- microsoft.net.sdk.macos: "13.3.7045/7.0.100"
- microsoft.net.sdk.tvos: "16.4.7045/7.0.100"

This prevents us from using the rollbackfile to install maui in our Azure pipeline

### Steps to Reproduce

1. Open a command prompt
2. Run this command to install version 7.0.86 of maui workload:
dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/7.0.86.json --source https://api.nuget.org/v3/index.json
3. Error:
**Workload installation failed: One or more errors occurred. (microsoft.net.sdk.ios.manifest-7.0.100.msi.x64::16.4.7045 is not found in NuGet feeds https://api.nuget.org/v3/index.json".)**

### Link to public reproduction project repository

https://github.com/

### Version with bug

7.0.86

### Last version that worked well

7.0.81

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

No

**Comment by NickDarvey** [comment]
I think you're right, it must be a typo.

> This prevents us from using the rollbackfile to install maui in our Azure pipeline

As a workaround (or to defend against this in future), you can refer to a local rollback file:

```
dotnet workload install maui --from-rollback-file my-local-rollback-file.json
```

**Comment by BjornEGlomsrud** [comment]
No longer an issue, as the rollback file [https://maui.blob.core.windows.net/metadata/rollbacks/7.0.86.json](https://maui.blob.core.windows.net/metadata/rollbacks/7.0.86.json) now contains references to versions that do exist in the nuget feeds.
