### ISSUE TITLE
[Bug] iOS Crash GroupFooterTemplate on CollectionView with Grouping

### ISSUE THREAD

**Issue by sesitosvdx** [dotnet/maui#15393]
### Description

Having a CollectionView with IsGrouped=True and add the GroupFooterTemplate with any Templatel that has a visibility binding or a dynamic changing makes it crash with the folllowing error:

An error occurred: 'Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: UICollectionView (<UICollectionView 0x114fe0000>) is stuck in its update/layout loop. This can happen for various reasons, including self-sizing views whose preferred attributes are not returning a consistent size. To debug this issue, check the Console app for logs in the "UICollectionViewRecursion" category. In particular, look for messages about layout invalidations, or changes to properties like contentOffset (bounds.origin), bounds.size, frame, etc. Native stack trace:

I was only able to reproduce it on certain iOS devices (not iPhone 6 SE, but yes on iPhone 12 Pro Max and iPhone 14 Pro Max). Couldn't reproduce it on any simulator.

Setting a HeightRequest does not fix it.

### Steps to Reproduce
1. You can use the maui-samples repo and edit any CollectionView example that uses GroupFooterTemplate with some Template that has a visibility binding with some logic that, e.g. changes if it's the first item
2. It crashed on appearing.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

No

**Comment by MitchBomcanhao** [comment]
We're still on xamarin forms but we've got an increasing number of crash groups that relate to NSInternalInconsistencyException and grouped listviews - Likely to be related to the same problem in the underlying platform. if this is investigated in maui, it probably needs backporting to xamarin forms too.

**Comment by moneosi** [comment]
Hello guys today I had this issue when work with grouped dates in collectionview. There any resolution? Or  any future release with fix.

- Thanks

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio for Mac 17.6.8. Not repro with [maui-samples/8.0/UserInterface/Views/CollectionViewDemos at main · dotnet/maui-samples (github.com)](https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CollectionViewDemos) project.
