### ISSUE TITLE
[Enhancement] Performance Profiler

### ISSUE THREAD

**Issue by jrc14** [dotnet/maui#154]
## Summary
Make the performance profiling tools available in the Community toolkit - or at least available in something cheaper than an Enterprise subscription to VS.

## Intended Use Case
Developing solid production apps in Android is really difficult without tools for profiling (performance and memory allocation) , but an enterprise subscription is just too expensive.

**Comment by awulkan** [comment]
For comparison, Flutter offers great performance profiling tools for free. If MAUI wants to be competitive I think this is a must.
