### ISSUE TITLE
FontFamily = "OpenSans-Semibold.ttf"; to custom button not working in  net 6

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#15429]
### Description

When I add FontFamily = "OpenSans-Semibold.ttf"; to the custom button below the custom button stop working.

### Steps to Reproduce

```
public class MyButton:Button
{
    public static readonly BindableProperty HasSelectProperty =BindableProperty.CreateAttached("HasSelect", typeof(bool), typeof(MyButton), false,BindingMode.OneWay,propertyChanged: HasSelectChanged);

   public bool HasSelect
    {
        get { return (bool)GetValue(HasSelectProperty); }
        set { SetValue(HasSelectProperty, value); }
    }

   public MyButton()
    {
        Background = Brush.Transparent;
        TextColor = Colors.Black;
FontFamily = "OpenSans-Semibold.ttf";
    
    }
    
    private static void HasSelectChanged(BindableObject bindable, object oldValue, object newValue)
    {
        if (bindable != null&& newValue!=null)
        {
            bool IsSelect = (bool)newValue;
            
            MyButton myButton = bindable as MyButton;
            if (IsSelect)
            {
                myButton.FontAttributes = FontAttributes.Bold;
            
                myButton.ScaleTo(1.2f, 10);
            }
            else
            {
                myButton.FontAttributes = FontAttributes.None;
                myButton.ScaleTo(1f, 10);
            }
        }
    }

 
}

<local:MyButton x:Name="mybutt" Clicked="Button_Clicked" Text="QA"/>


private void Button_Clicked(object sender, EventArgs e)
    {
       
        mybutt.HasSelect =!mybutt.HasSelect ;   
    }

```
### Link to public reproduction project repository

.....

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

....

### Relevant log output

```shell
.....
```

**Comment by danies8** [comment]
I added full code up full sniped code.
1.Open vs and create maui project in net 6.
2.Create custom button:
public class MyButton:Button
{
public static readonly BindableProperty HasSelectProperty =BindableProperty.CreateAttached("HasSelect", typeof(bool), typeof(MyButton), false,BindingMode.OneWay,propertyChanged: HasSelectChanged);

public bool HasSelect
{
get { return (bool)GetValue(HasSelectProperty); }
set { SetValue(HasSelectProperty, value); }
}

public MyButton()
{
Background = Brush.Transparent;
TextColor = Colors.Black;
FontFamily = "OpenSans-Semibold.ttf"; **// this line is problematic**
}
private static void HasSelectChanged(BindableObject bindable, object oldValue, object newValue)
{
    if (bindable != null&& newValue!=null)
    {
        bool IsSelect = (bool)newValue;
        
        MyButton myButton = bindable as MyButton;
        if (IsSelect)
        {
            myButton.FontAttributes = FontAttributes.Bold;
        
            myButton.ScaleTo(1.2f, 10);
        }
        else
        {
            myButton.FontAttributes = FontAttributes.None;
            myButton.ScaleTo(1f, 10);
        }
    }
}
3. Consume  this custom button.
<local:MyButton x:Name="mybutt" Clicked="Button_Clicked" Text="QA"/>
private void Button_Clicked(object sender, EventArgs e)
{

    mybutt.HasSelect =!mybutt.HasSelect ;   
}
4. FontFamily = "OpenSans-Semibold.ttf"; **// this line is problematic** in ctor of custom button.
5.the results the button not working with this row.

**Comment by jsuarezruiz** [comment]
Would be interesting to have a repro project mostly to see where you have the font file, and if the single project tooling is exporting to the correct path, could you share it?. If not, can just try to reproduce with your code.

**Comment by danies8** [comment]
The font in the right place.
Tomorrow I will prepare repro project :)
