### ISSUE TITLE
[Bug] An unhandled error  has occurred Reload

### ISSUE THREAD

**Issue by infofromca** [dotnet/maui#1542]
### Description
when An unhandled error  has occurred Reload, it will make the whole app dead
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
the framework should deal with this exception, and make the app  to go smoothly
### Actual Behavior
app is dead, cannot click any link or ...
### Basic Information

- Version with issue:
preview 5
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:android

**Comment by jfversluis** [comment]
Thanks for reporting! I hope with the latest updates everything is better. However, this issue has too few details to be able to diagnose it. If this issue still persists, please open a new issue and make sure to fill out as many of the fields as possible. 

THanks!
