### ISSUE TITLE
Spurious 'Must declare Runtime Identifier triggered' when linking to platform dependent libraries

### ISSUE THREAD

**Issue by hallambaker** [dotnet/maui#15436]
### Description

I have a main program that is platform neutral linking to platform specific cryptography libraries on each platform. The code compiles fine when the main program does not link to the platform specific library but halts whenever linking to the platform specific library with the following error:

"Packaged .NET applications with an app host exe cannot be ProcessorArchitecture neutral. Please specify a RuntimeIdentifier or a Platform other than AnyCPU"

Needless to say, I have tried every conceivable permutation of RuntimeIdentifier/RuntimeIdentifiers

		<TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
		<RuntimeIdentifier>win10-x64</RuntimeIdentifier>

I have tried defining them in the program declaring the .exe, in the linked library, in both, etc. etc. Every permutation fails with the rids specified as win-x64.

I have just got the code to run with the following

Exe specifies the RID win10-64, library specifies NO RID AT ALL.

### Steps to Reproduce

See above, it is a bug report with a work arround

### Link to public reproduction project repository

https://github.com/hallambaker/Mathematical-Mesh

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

As specified above, it works if and only if the win10-x64 is specified in the exe build alone

Trying to specify multiple runtime identifiers invariably leads to a fail.

This may be a Visual Studio bug that is being triggered by Maui or due to the Maui builds being incorrect in some peculiar fashion. It appears to be a recurring .net bug as there are repeated fix claims.

I suspect that building from the command line might work as a workaround but that has its issues as well.

**Comment by QianaJiao** [comment]
This issue was not repro on Visual Studio 17.11.0 Preview 2.1 (8.0.60 & 8.0.40).
![image](https://github.com/dotnet/maui/assets/91244512/0a3e2eb2-147a-4515-ab10-d0247152e042)
