### ISSUE TITLE
[Enhancement] Cannot deploy MAUI app to an iOS device

### ISSUE THREAD

**Issue by gazeing** [dotnet/maui#1543]
### Description

Cannot deploy MAUI app to a real iOS device instead of the simulator.

### Steps to Reproduce

1. Install Maui sample app
2. Connect an iOS device to the laptop, on the bottom of VScode, press "select a device", then pick the iOS device connected
3. Run the sample app

### Expected Behavior
The App is deployed to the device and run
### Actual Behavior
An error is popup as "iOS simulator is not valid"
### Basic Information

- Version with issue: 6.0.100-preview.5.21302.13
- Last known good version: N/A
- IDE: VScode Version: 1.57.1

**Comment by jfversluis** [comment]
Thanks for reporting this @gazeing ! Unfortunately, VS Code is not officially supported right now. For the best experience please use Visual Studio 2022.
