### ISSUE TITLE
The SVG image cannot be fully displayed

### ISSUE THREAD

**Issue by xyeie** [dotnet/maui#15442]
### Description

Some SVG images cannot be fully displayed
The expected image to be displayed is as follow：
![image](https://github.com/dotnet/maui/assets/105901371/291d0360-b8a1-41a6-93b8-9f3835862d4d)
But the actual image displayed is：
![image](https://github.com/dotnet/maui/assets/105901371/9d9d979e-c252-44a3-bc2c-3b5d07a39843)
I don't know what caused the image to not display properly and completely

### Steps to Reproduce

<Image Source="find_icon.png"
                 Aspect="AspectFit"
                 HeightRequest="60"
                 WidthRequest="60">
![find_icon](https://github.com/dotnet/maui/assets/105901371/e126bbae-d0d3-420f-b2b9-cb6433f204f2)

### Link to public reproduction project repository

maui

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android13

**Comment by jsuarezruiz** [comment]
Could you share a repro project and the SVG used?

**Comment by xyeie** [comment]
尊敬的客户您好，您的信息已收到，请务必加入咱们的微信学习群，进群学习哦

**Comment by xyeie** [comment]
the svg content:

<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1685868247753" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="7805" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200"><path d="M509.4912 516.7104m-366.5408 0a366.5408 366.5408 0 1 0 733.0816 0 366.5408 366.5408 0 1 0-733.0816 0Z" fill="#A5ADF6" p-id="7806"></path><path d="M398.5408 651.3152c-49.664 16.0768-103.168-11.2128-119.296-60.8768s11.2128-103.168 60.8768-119.296 103.168 11.2128 119.296 60.8768-11.2128 103.2192-60.8768 119.296z m-37.12-114.5344c-13.5168 4.352-20.8896 18.8928-16.5376 32.4096 4.352 13.5168 18.8928 20.8896 32.4096 16.5376 13.5168-4.352 20.8896-18.8928 16.5376-32.4096-4.4032-13.5168-18.944-20.9408-32.4096-16.5376z" fill="#FFFFFF" p-id="7807"></path><path d="M475.4432 326.2464m-51.5072 0a51.5072 51.5072 0 1 0 103.0144 0 51.5072 51.5072 0 1 0-103.0144 0Z" fill="#FFFFFF" p-id="7808"></path><path d="M906.2912 789.9136m-59.8016 0a59.8016 59.8016 0 1 0 119.6032 0 59.8016 59.8016 0 1 0-119.6032 0Z" fill="#A5ADF6" p-id="7809"></path><path d="M641.024 470.1184m-40.6528 0a40.6528 40.6528 0 1 0 81.3056 0 40.6528 40.6528 0 1 0-81.3056 0Z" fill="#FFFFFF" p-id="7810"></path><path d="M636.16 923.1872m-29.2864 0a29.2864 29.2864 0 1 0 58.5728 0 29.2864 29.2864 0 1 0-58.5728 0Z" fill="#A5ADF6" p-id="7811"></path><path d="M108.4416 325.376m-29.2864 0a29.2864 29.2864 0 1 0 58.5728 0 29.2864 29.2864 0 1 0-58.5728 0Z" fill="#A5ADF6" p-id="7812"></path><path d="M667.0336 125.2352m-29.2864 0a29.2864 29.2864 0 1 0 58.5728 0 29.2864 29.2864 0 1 0-58.5728 0Z" fill="#A5ADF6" p-id="7813"></path><path d="M402.176 840.7552c-26.7264 8.6528-52.8384 15.4624-78.08 20.2752-113.408 21.5552-198.5024 0.256-239.5648-60.1088-24.5248-35.9936-30.5664-82.8416-17.4592-135.3728 5.7344-22.9888 29.0304-36.9664 51.968-31.232a42.8544 42.8544 0 0 1 31.232 51.968c-7.1168 28.5696-5.376 50.8928 5.1712 66.3552 20.0704 29.44 77.1072 38.4512 152.6784 24.1152 89.9584-17.1008 194.3552-63.8976 293.9392-131.6864S783.36 497.2544 832.256 419.84c41.0624-65.024 53.5552-121.3952 33.536-150.8864-14.6944-21.6064-46.2336-28.3136-70.0416-30.1568-23.6032-1.792-41.2672-22.4256-39.4752-46.0288 1.792-23.6032 22.4256-41.3184 46.0288-39.4752 77.1584 5.9392 115.6608 39.936 134.3488 67.4304 41.0624 60.3136 29.7472 147.3024-31.8976 244.8896-55.04 87.1424-145.408 176.0256-254.5152 250.3168-81.8688 55.7568-167.5776 98.7136-248.064 124.8256z" fill="#A5ADF6" p-id="7814"></path><path d="M875.9296 507.0848a366.94016 366.94016 0 0 0-24.1664-121.6512 389.92384 389.92384 0 0 1-19.5072 34.4576C783.36 497.3056 701.5936 577.28 602.0096 645.12s-203.9296 114.5856-293.9392 131.6864c-17.9712 3.4304-34.8672 5.4784-50.5344 6.2976a366.42816 366.42816 0 0 0 104.8064 69.3248c13.1072-3.3792 26.4192-7.2704 39.8336-11.6224 80.4864-26.112 166.1952-69.0176 248.064-124.7744 91.8528-62.6176 170.2912-135.4752 225.6896-208.9472z" fill="#635DF7" p-id="7815"></path></svg>

**Comment by xyeie** [comment]
`<Image Source="find_icon.png">`

![find_icon](https://github.com/dotnet/maui/assets/105901371/9935966d-9f0a-4959-8b1b-17ace8f98ebb)
@jsuarezruiz

**Comment by xyeie** [comment]
the svg content:
`<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1685868247753" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="7805" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200"><path d="M509.4912 516.7104m-366.5408 0a366.5408 366.5408 0 1 0 733.0816 0 366.5408 366.5408 0 1 0-733.0816 0Z" fill="#A5ADF6" p-id="7806"></path><path d="M398.5408 651.3152c-49.664 16.0768-103.168-11.2128-119.296-60.8768s11.2128-103.168 60.8768-119.296 103.168 11.2128 119.296 60.8768-11.2128 103.2192-60.8768 119.296z m-37.12-114.5344c-13.5168 4.352-20.8896 18.8928-16.5376 32.4096 4.352 13.5168 18.8928 20.8896 32.4096 16.5376 13.5168-4.352 20.8896-18.8928 16.5376-32.4096-4.4032-13.5168-18.944-20.9408-32.4096-16.5376z" fill="#FFFFFF" p-id="7807"></path><path d="M475.4432 326.2464m-51.5072 0a51.5072 51.5072 0 1 0 103.0144 0 51.5072 51.5072 0 1 0-103.0144 0Z" fill="#FFFFFF" p-id="7808"></path><path d="M906.2912 789.9136m-59.8016 0a59.8016 59.8016 0 1 0 119.6032 0 59.8016 59.8016 0 1 0-119.6032 0Z" fill="#A5ADF6" p-id="7809"></path><path d="M641.024 470.1184m-40.6528 0a40.6528 40.6528 0 1 0 81.3056 0 40.6528 40.6528 0 1 0-81.3056 0Z" fill="#FFFFFF" p-id="7810"></path><path d="M636.16 923.1872m-29.2864 0a29.2864 29.2864 0 1 0 58.5728 0 29.2864 29.2864 0 1 0-58.5728 0Z" fill="#A5ADF6" p-id="7811"></path><path d="M108.4416 325.376m-29.2864 0a29.2864 29.2864 0 1 0 58.5728 0 29.2864 29.2864 0 1 0-58.5728 0Z" fill="#A5ADF6" p-id="7812"></path><path d="M667.0336 125.2352m-29.2864 0a29.2864 29.2864 0 1 0 58.5728 0 29.2864 29.2864 0 1 0-58.5728 0Z" fill="#A5ADF6" p-id="7813"></path><path d="M402.176 840.7552c-26.7264 8.6528-52.8384 15.4624-78.08 20.2752-113.408 21.5552-198.5024 0.256-239.5648-60.1088-24.5248-35.9936-30.5664-82.8416-17.4592-135.3728 5.7344-22.9888 29.0304-36.9664 51.968-31.232a42.8544 42.8544 0 0 1 31.232 51.968c-7.1168 28.5696-5.376 50.8928 5.1712 66.3552 20.0704 29.44 77.1072 38.4512 152.6784 24.1152 89.9584-17.1008 194.3552-63.8976 293.9392-131.6864S783.36 497.2544 832.256 419.84c41.0624-65.024 53.5552-121.3952 33.536-150.8864-14.6944-21.6064-46.2336-28.3136-70.0416-30.1568-23.6032-1.792-41.2672-22.4256-39.4752-46.0288 1.792-23.6032 22.4256-41.3184 46.0288-39.4752 77.1584 5.9392 115.6608 39.936 134.3488 67.4304 41.0624 60.3136 29.7472 147.3024-31.8976 244.8896-55.04 87.1424-145.408 176.0256-254.5152 250.3168-81.8688 55.7568-167.5776 98.7136-248.064 124.8256z" fill="#A5ADF6" p-id="7814"></path><path d="M875.9296 507.0848a366.94016 366.94016 0 0 0-24.1664-121.6512 389.92384 389.92384 0 0 1-19.5072 34.4576C783.36 497.3056 701.5936 577.28 602.0096 645.12s-203.9296 114.5856-293.9392 131.6864c-17.9712 3.4304-34.8672 5.4784-50.5344 6.2976a366.42816 366.42816 0 0 0 104.8064 69.3248c13.1072-3.3792 26.4192-7.2704 39.8336-11.6224 80.4864-26.112 166.1952-69.0176 248.064-124.7744 91.8528-62.6176 170.2912-135.4752 225.6896-208.9472z" fill="#635DF7" p-id="7815"></path></svg>`

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 3.0(.NET 8). Repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[15442.zip](https://github.com/dotnet/maui/files/12093243/15442.zip)

![image](https://github.com/dotnet/maui/assets/97647558/ba10e3c5-5739-416b-93cf-625affc0006f)
