### ISSUE TITLE
SwipeItem.IsEnable clobbering source value when BindingContext changed

### ISSUE THREAD

**Issue by BenCamps** [dotnet/maui#15444]
### Description

Setting BindingContext on SwipeView causes SwipeItem.IsEnabled binding to apply control's IsEnabled value back to source

I found this bug also exists in Xamarin Forms

### Steps to Reproduce

Clone referenced repository and run application

Expected outcome: after setting BindingContext in MainPage constructor viewModel.IsEnabled should be `false`
Actual outcome: viewModel.IsEnabled value changed to `true`

### Link to public reproduction project repository

https://github.com/BenCamps/SwipeItemIsEnabledBindingIssue

### Version with bug

8.0.0-preview.4.8333

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

all

**Comment by jsuarezruiz** [comment]
Have done a quick test in main branch and cannot reproduce the issue there:
![image](https://github.com/dotnet/maui/assets/6755973/6a3f2235-33fa-498c-8032-a74996d55e05)

Will review with more details.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 4.0. This issue repro on Windows 11 .NET 7, not repro on Windows .NET 8 and Android 13.0-API33, iOS 16.4 with below Project:
[SwipeItemIsEnabledBindingIssue.zip](https://github.com/dotnet/maui/files/12093757/SwipeItemIsEnabledBindingIssue.zip)

**Windows**:
![image](https://github.com/dotnet/maui/assets/97647558/b6419263-db3f-4734-8940-e2c37afa7974)
