### ISSUE TITLE
Converters/DataTrigger/MultiTrigger not updating the destination property

### ISSUE THREAD

**Issue by danardelean** [dotnet/maui#15455]
### Description

When changing a property on a ViewModel that uses PropertyChanged to notify the binding using a Converter (or DataTrigger or MultiTrigger) is not updated

Tried it on both 7.0.86 and also 8.0 preview 4.

The same code works on Xamarin.Forms so I think that it is a bug

### Steps to Reproduce

1. Clone the repository
2. Launch the application and press the button
3. The code changes a property that should make the TextColor on the 4th line red but it doesn't
4. Look at the MainPage.xaml and replace the TExtColor set using Binding and converter with DataTrigger or MultiTrigger (commented code) and observe the same wrong behaviour (the label does not change color)
5. I have also tried with BindableLayout and VerticalStackLayout (thinking that maybe it is a problem of the CollectionView but I have the same behaviour)

### Link to public reproduction project repository

https://github.com/danardelean/MauiIssueTriggerConverters

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

iOS 16.4, android 13, Ventura 13.4

### Did you find any workaround?

No

**Comment by danardelean** [comment]
Any feedback on this one?

**Comment by danardelean** [comment]
News on this bug?

**Comment by ysbakker** [comment]
I'm also experiencing this issue. Any news?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(**8.0.3**). This issue does not repro on Windows 11, Android 14.0-API34, iOS 17.0 and MacCatalyst with below Project:
[MauiIssueTriggerConverters.zip](https://github.com/dotnet/maui/files/13447797/MauiIssueTriggerConverters.zip)

![image](https://github.com/dotnet/maui/assets/97647558/e602197c-0fcb-466f-aafb-af13a464e493)
