### ISSUE TITLE
Get geolocation using maui web view

### ISSUE THREAD

**Issue by persiabudi28** [dotnet/maui#15451]
How to get geolocation using web view like this source https://github.com/hamza3344/longitude/blob/main/longitude.rar
And https://youtu.be/CL4QJSV6iX8

**Comment by Eilon** [comment]
Hi @persiabudi28 , we cannot open attachments. Can you provide more info about what you tried and what isn't working? And which platform? If you search this repo's issues you might find other similar questions about geolocation in webviews.

**Comment by bradencohen** [comment]
If this is on Android, you have to do a couple additional things to callback for geolocation permissions; https://stackoverflow.com/questions/42304287/xamarin-forms-webview-geolocation-issue/76175631#76175631

**Comment by persiabudi28** [comment]
Not to retrieve the device's current latitude and longitude, but instead to get longitude and latitude from Google map in c# using maui webview
