### ISSUE TITLE
Black screen upon starting debug.

### ISSUE THREAD

**Issue by nicktheone** [dotnet/maui#15467]
### Description

I'm having this issue where upon starting a debug session on Windows Platform sometimes the app window remains a black screen and it never actually starts, despite Visual Studio acting like it did.

### Steps to Reproduce

It's happening with both my linked repo and also a fresh new project.

### Link to public reproduction project repository

https://github.com/nicktheone/CalypsoApp

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

**Comment by Eilon** [comment]
Dup of #15533
