### ISSUE TITLE
Can't build Maui from main branch

### ISSUE THREAD

**Issue by webwarrior-ws** [dotnet/maui#15470]
### Description

Can't build maui from `main` branch. Get build errors.

### Steps to Reproduce

Checkout maui repository, `main` branch.
Try to build it using local dotnet install.
Command: `dotnet cake --pack --sln="<path to a .sln file>" --target=VS`

Expected:
build completes successfully and VS launches.

Actual:
build fails with the following error: https://gist.github.com/webwarrior-ws/3283bfd25e35449033b3db30e91e5b2d

The last commit that I got to build is https://github.com/dotnet/maui/commit/cad62a0b95a457d3a1643ce5c4a09321637e2fbb
Next commit (https://github.com/dotnet/maui/commit/6e8df7f81bd39636848a8dcb08b0c892160e5be6) breaks the build.

### Link to public reproduction project repository

not applicable

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

any?

**Comment by Eilon** [comment]
@mattleibow - looks like they're hitting some build error with graphics. Any idea?

```
D:\Projects\work\maui2\src\Graphics\src\Graphics\Platforms\Windows\PlatformImage.cs(130,38): error CS1503: Argument 1:cannot convert from 'Microsoft.Graphics.Canvas.ICanvasResourceCreator' to 'byte[]' [D:\Projects\work\maui2\src\Graphics\src\Graphics.Win2D\Graphics.Win2D.csproj::TargetFramework=net7.0-windows10.0.20348]
D:\Projects\work\maui2\src\Graphics\src\Graphics\Platforms\Windows\PlatformImage.cs(130,48): error CS1503: Argument 2:cannot convert from 'Microsoft.Graphics.Canvas.CanvasBitmap' to 'Microsoft.Maui.Graphics.ImageFormat' [D:\Projects\work\maui2\src\Graphics\src\Graphics.Win2D\Graphics.Win2D.csproj::TargetFramework=net7.0-windows10.0.20348]
D:\Projects\work\maui2\src\Graphics\src\Graphics\Platforms\Windows\PlatformCanvas.cs(539,41): error CS1061: 'PlatformImage' does not contain a definition for 'PlatformRepresentation' and no accessible extension method 'PlatformRepresentation' accepting a first argument of type 'PlatformImage' could be found (are you missing a using directive or an assembly reference?) [D:\Projects\work\maui2\src\Graphics\src\Graphics.Win2D\Graphics.Win2D.csproj::TargetFramework=net7.0-windows10.0.20348]
D:\Projects\work\maui2\src\Graphics\src\Graphics\Platforms\Windows\PlatformImage.cs(130,38): error CS1503: Argument 1:cannot convert from 'Microsoft.Graphics.Canvas.ICanvasResourceCreator' to 'byte[]' [D:\Projects\work\maui2\src\Graphics\src\Graphics.Win2D\Graphics.Win2D.csproj::TargetFramework=net7.0-windows10.0.19041]
D:\Projects\work\maui2\src\Graphics\src\Graphics\Platforms\Windows\PlatformImage.cs(130,48): error CS1503: Argument 2:cannot convert from 'Microsoft.Graphics.Canvas.CanvasBitmap' to 'Microsoft.Maui.Graphics.ImageFormat' [D:\Projects\work\maui2\src\Graphics\src\Graphics.Win2D\Graphics.Win2D.csproj::TargetFramework=net7.0-windows10.0.19041]
D:\Projects\work\maui2\src\Graphics\src\Graphics\Platforms\Windows\PlatformCanvas.cs(539,41): error CS1061: 'PlatformImage' does not contain a definition for 'PlatformRepresentation' and no accessible extension method 'PlatformRepresentation' accepting a first argument of type 'PlatformImage' could be found (are you missing a using directive or an assembly reference?) [D:\Projects\work\maui2\src\Graphics\src\Graphics.Win2D\Graphics.Win2D.csproj::TargetFramework=net7.0-windows10.0.19041]
```

**Comment by webwarrior-ws** [comment]
I tried to build latest `main` (4aaa10e) and got the same errors as before.

**Comment by knocte** [comment]
@mattleibow hello Matthew, sorry for pinging you here, but you were the author of this commit:

> Next commit (https://github.com/dotnet/maui/commit/6e8df7f81bd39636848a8dcb08b0c892160e5be6) breaks the build.

Can you look at the build error and give some advice here? Thanks

**Comment by mattleibow** [comment]
main should be buildable again. Make sure you are on the latest VS/SDK
