### ISSUE TITLE
Cannot change the border color of an ImageButton

### ISSUE THREAD

**Issue by gktval** [dotnet/maui#15479]
### Description

Changes to an ImageButton's border color are not displayed. Have not tested with iOS or Android.

### Steps to Reproduce

Create an ImageButton. On Click, change the color of the border for the ImageButton. Notice it does not change.

### Link to public reproduction project repository

https://github.com/gktval/MauiImageButtonBug

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

no

**Comment by gktval** [comment]
Also happening in Android/iOS.

**Comment by jknaudt21** [comment]
Seems this bug will be fixed in .NET 8. I tested using the latest on main using Windows, Mac, and Android. All platforms were working as expected.
