### ISSUE TITLE
CollectionView items have extra space on Windows

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#15492]
### Description

The CollectionView Items take extra space than it's content when I set  `ItemsLayout = new LinearItemsLayout(ItemsLayoutOrientation.Horizontal) { ItemSpacing = 0 },`. 

### Steps to Reproduce

Run the reproduction project on Windows and select any item. The selected Items highlighted color will show the extra space the item is taking. Also the space between the items is huge even when the spacing is set to 0. 

### Link to public reproduction project repository

https://github.com/HobDev/MauiBugs/tree/CollectionViewAlignmentIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

The items does not take that much space in GridItemsLayout. It's also not take that much space in  LinearItemsLayout if Orientation is Vertical. But still there is extra space being hold by each item

**Comment by Vroomer** [comment]
Old bug that should have been fixed by https://github.com/dotnet/maui/pull/12811, but I have the same problem in main branch as well.
