### ISSUE TITLE
[.NET8][Regression] Recipe main page cannot be swipe down

### ISSUE THREAD

**Issue by QianaJiao** [dotnet/maui#15494]
### Description

Recipe main page cannot be swipe down on Android emulator/device and Windows. 

### Steps to Reproduce

**Steps to reproduce:**
Deploy https://github.com/rachelkang/recipeSearch to device  
Swipe down on the main page

Actual results:
Unable to swipe down, the options under search by diet cannot be fully displayed
![image](https://github.com/dotnet/maui/assets/91244512/a5eb72b8-2970-4c50-8692-15e9e9283cd4)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

8.0.0-preview.5.8506

### Last version that worked well

8.0.0-preview.4.8333

### Affected platforms

Android, Windows

### Affected platform versions

net8.0-windows10.0.19041.0

**Comment by rachelkang** [comment]
re-commenting from the AzDo issue:

I'm not having any issues with the scrolling (emulator can admittedly be finnicky sometimes, which is what Jason may have run into; but ultimately, no issues with scrolling the horizontal ScrollViews)

I'm actually more concerned with the layout portrayed... that looks like it might be the regression

| Preview 4 | Preview 5 |
|--|--|
|![image](https://github.com/dotnet/maui/assets/21988533/332837db-cc1c-4add-b471-3f8154c95909)|![image](https://github.com/dotnet/maui/assets/21988533/433ee109-2f6f-4ac4-9a32-f4fa2319663e)|

I've investigated, and it's tied to the GridLayoutManager.cs changes in https://github.com/dotnet/maui/pull/14902
