### ISSUE TITLE
Showing TitleBar and ToolbarItems on Android in a modal ContentPage in a MVVM Shell app

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/maui#15498]
## Setup

I have a `Shell` app using `Tab`s as root pages. I am using the MVVM Community Toolkit.
I am creating a list/detail page with edit functionality.
I am trying to present the edit page as a modal view. I want to present the cancel / save buttons of the edit page at the top of the page as `ToolbarItem`s. 

## Examples of what I am trying to achieve:
- [Full screen dialog](https://m2.material.io/components/dialogs#full-screen-dialog) on Android
- [Large sheet](https://developer.apple.com/design/human-interface-guidelines/sheets) on iOS
  - This [Apple tutorial page](https://developer.apple.com/tutorials/app-dev-training/creating-the-edit-view) has a [video](https://docs-assets.developer.apple.com/published/829da7e9f1e3bf608b8c4f705c8cfd49/SUI050_040-080~dark@2x.mp4) on the bottom of the page of what I am trying to achieve.

## Approach I tried to achieve this
- Create a new `ContentPage` for the editing and register a route for it.
- Set its `Shell.PresentationMode="ModalAnimated"` and add a title with `Title="{Binding Item.Title}"`
- Add
  ```xaml
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Cancel"
                     Command="{Binding ResetCommand}" />
        <ToolbarItem Text="Save"
                     Command="{Binding SaveCommand}" />
    </ContentPage.ToolbarItems>
  ```
- Navigate to the `edit` page from the `detail` page using
  ```csharp
  await Shell.Current.GoToAsync("edit", true, new Dictionary<string, object>
  {
       { "Item", Item }
  });
  ```

## The issue
The issue is that the `Title` and `ToolbarItems` do not show up. The whole navigationbar is not visible, even when trying to force it using `Shell.NavBarIsVisible="True"`.

## Workarounds I tried
- Adding `Shell.NavBarIsVisible="True"` does not work
- Using `await Shell.Current.Navigation.PushModalAsync(new NavigationPage(new EditPage(this) { Title="This does not show" }));` instead of `Shell.Current.GoToAsync` does not work

## Related items
A similar bug was reported in https://github.com/xamarin/Xamarin.Forms/issues/13477 but the suggested workaround from there does not work.

### Steps to Reproduce

1. Create a new Maui app using [Maui App Accelerator](https://github.com/mrlacey/MauiAppAccelerator). Settings:
  - .NET 7
  - MVVM Toolkit
  - Tabs navigation
  - Add a List/Detail page (leave its title to follow the class names in the retro)
2. Copy the `ListDetailDetailPage` xaml and xaml.cs files, and paste them renamed as `EditPage`. Also update its contents so that the new page xaml and xaml.cs contain the correct class name. Still have the xamlpoint to the `ListDetailDetailViewModel`
3. Setup routes for the pages
4. - Create a new `ContentPage` for the editing and register a route for it.
- Set its `Shell.PresentationMode="ModalAnimated"` and add a title with `Title="{Binding Item.Title}"`
- Add
  ```xaml
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Cancel"
                     Command="{Binding ResetCommand}" />
        <ToolbarItem Text="Save"
                     Command="{Binding SaveCommand}" />
    </ContentPage.ToolbarItems>
  ```
- Navigate to the `edit` page from the `detail` page using
  ```csharp
  await Shell.Current.GoToAsync("edit", true, new Dictionary<string, object>
  {
       { "Item", Item }
  });
  ```

### Link to public reproduction project repository

https://github.com/hansmbakker/maui-modal-bug-repro

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

At least Android

### Did you find any workaround?

No

**Comment by hansmbakker** [comment]
If there are suggestions how to build this interaction better (maybe the Shell + modal "`ContentPage` is the wrong approach for this?) I'm curious to hear so. In any case I could not find good documentation on how to implement this common detail --> edit page interaction.

I can imagine using [`Popup`](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup)s" for this is an option, but at first sight it looks like it is not very polished yet [especially when wanting to follow the MVVM pattern](https://stackoverflow.com/questions/75722266/how-to-show-a-popup-from-viewmodel-maui).

**Comment by hansmbakker** [comment]
I created a branch that is upgraded to .NET 8. See https://github.com/hansmbakker/maui-modal-bug-repro/tree/net8.0.

The behavior is the same unfortunately:
- `ContentPage` with `Shell.PresentationMode="ModalAnimated"` and `Shell.NavBarIsVisible="True"` does neither show `Title` nor `ToolbarItems`
- using `await Shell.Current.Navigation.PushModalAsync(new NavigationPage(new EditPage(this) { Title="This does not show" }));` as a suggested workaround does not show the `Title` nor `ToolbarItems`.
  Note: I did set `NavigationPage.HasNavigationBar="True"` on the `ContentPage` just to be sure.

If I made a mistake in my code, I would also be happy to get that feedback!

**Comment by hansmbakker** [comment]
It seems so. Adding to that, I found **another bug**:
1. start on a normal ContentPage in a Shell app (default PresentationMode)
1. navigate to a modal ContentPage  (PresentationMode is ModalAnimated) --> no title bar is shown - **bug 1**
1. from that modal ContentPage, navigate to a new normal ContentPage (default PresentationMode) --> it is opened with a modal animation (from the bottom) instead of a normal page navigation animation (slide from the right) AND still there is no title bar so you cannot navigate back to the first modal page using a back button - **bug 2**

Bug 1 - no title bar is shown for modal pages
Bug 2 - normal pages navigated to from a modal page keep being presented and animated as modal pages

**Comment by haavamoa** [comment]
To overcome your second bug @hansmbakker : We’ve made sure to wrap that first modal page navigation in a NavigationPage and to push the next ContentPage we navigate using the NavigationPage to push.

But, the entire NavBar missing is quite bad. This forces us to put Shell on the shelf, and leave it there.

**Comment by PureWeen** [comment]
> @PureWeen can you please explain what's a next step?

Repentance?
https://github.com/dotnet/maui/pull/15799

**Comment by hansmbakker** [comment]
Hi @PureWeen! Thank you very much for starting a PR on this!

I'm not sure what you meant with "repentance", I just meant to ask what else I could do myself for this item or what could be done to prioritize this item.

But really good to see that this is added to the .NET 8 milestone!

**Comment by PureWeen** [comment]
@hansmbakker hehe, yea, just apologizing for letting this one sit :-) 

Should hopefully get this one merged for the next net8 preview. 🤞
Thank you for following up!!

**Comment by hansmbakker** [comment]
> Bug 1 - no title bar is shown for modal pages
> Bug 2 - normal pages navigated to from a modal page keep being presented and animated as modal pages

@PureWeen does your PR address both points already or should a separate issue be reported for the second one?

**Comment by PureWeen** [comment]
@hansmbakker do you have a repro for this one?

> Bug 2 - normal pages navigated to from a modal page keep being presented and animated as modal pages

I can test real quick against my PR

**Comment by hansmbakker** [comment]
> @hansmbakker do you have a repro for this one?
> 
> > Bug 2 - normal pages navigated to from a modal page keep being presented and animated as modal pages
> 
I created a repro for this:
- dotnet 7.0: https://github.com/hansmbakker/modal-bug-repro
- dotnet 8.0 preview 5: https://github.com/hansmbakker/modal-bug-repro/tree/net8.0-preview5

**Comment by hansmbakker** [comment]
Hi @PureWeen,
I saw your PR was merged, great! 👍🏻
Have you had a chance to check your improvements against my second repro repository?

**Comment by PureWeen** [comment]
> Hi @PureWeen, I saw your PR was merged, great! 👍🏻 Have you had a chance to check your improvements against my second repro repository?

If I'm following your code correctly you need to wrap `ModalPage` with a `NavigationPage` for that to work.

If you don't have things wrapped in a `NavigationPAge` then it just pushes each page modally because it's not inside a `Navigation` container.

**Comment by hansmbakker** [comment]
@PureWeen is that a workaround or is that intended behaviour? I couldn't find that documented anywhere.

Can you explain how a modal `ContentPage` can be wrapped in a `NavigationPage` using XAML so that I can keep my presentation settings in XAML?

I don't want to do that in the `Shell.Current.GoToAsync(...)` call (which is in the ViewModel) because that breaks the MVVM pattern (something similar was suggested in https://github.com/xamarin/Xamarin.Forms/issues/13477#issuecomment-947506530 and at the time I tried that, it did not work - see https://github.com/dotnet/maui/issues/15498#issuecomment-1582410235).

And, for me it is counterintuitive in XAML that modal pages are not inside a `Navigation` container.
I just have `ContentPage`s with different `Shell.PresentationMode`s and haven't consciously put something in or out of a container.
