### ISSUE TITLE
Abstract interpretation

### ISSUE THREAD

**Issue by sultanaalyami** [dotnet/maui#155]
A JIT compiler does a lot

If we look at the uwp applications and use some tricks to modify the package_ manifest and the start page made the .html file dependencies from Webpack it will be easily formatted MSXML and you will find compatibility with the application capabilities definitions, in return he will find it difficult to call the .NET method, and this is evident clearly with Blazor WebAssembly scenarios which With a high level role, it lacks 'js' flexibility and html efficiency , .NET CLR has the strength to lead over all high level software by focusing on the middle end and convergence with OpenMP.
in order not to get away from the address, I am a developer of mvc applications c# for 7 years  I love to display my applications on html pages with all their capabilities, and my dealing with .cshtml is very ideal I have never found Xamarin to attract me even a step to mobile applications, although I have been following it since its beginnings To take her as the next turn and I hope that the new interface is interested UI developers, and replace poor .xaml

e.g.
Instead of imposing a fixed scenario for a particular project that is being collected
Into parallel applications as with Xamarin.Forms | .NET The developer is given a choice of his development style without imposed restrictions and limitations in the vs environment in pop-up comments when they are exceeded

## By analogy with uwp applications
`///This style does not apply to blazor WebAssembly`
If you have created an uwp application and want to use the html interface as the starting page, I will attach the ClientApp folder within the project it contains
index.html
main-es2015.js
main-es5.js
polyfills-es2015.js
polyfills-es5.js
runtime-es2015.js
runtime-es5.js
styles.css

I will create an index.html file in the main root as follows

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>teckget</title>
    <base href="/" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <link rel="stylesheet" href="ClientApp/styles.css">
</head>
<body>
    <app-root>Loading...</app-root>
    <script src="ClientApp/runtime-es2015.js" type="module"></script>
    <script src="ClientApp/runtime-es5.js" nomodule defer></script>
    <script src="ClientApp/polyfills-es5.js" nomodule defer></script>
    <script src="ClientApp/polyfills-es2015.js" type="module"></script>
    <script src="ClientApp/main-es2015.js" type="module"></script>
    <script src="ClientApp/main-es5.js" nomodule defer></script>
</body>
</html>
```
The application will work and communicate with the machine with xml links as if it was built as well
Just need to modify Package.appxmanifest

```
  <Application Id="App"
    StartPage="index.html" >
```

This is ideal for me, as a web application developer, to approach an uwp approach that may conflict with software engineering but is a style that really must be followed in order to Abstract interpretation, Thunks should be used mainly.

**Comment by Happypig375** [comment]
You want to write JavaScript with Xamarin.Forms/MAUI?

**Comment by sultanaalyami** [comment]
> You want to write JavaScript with Xamarin.Forms/MAUI?


Not so much, but if there is the advantage of grouping similar projects in Maui and merging them with what they claim
