### ISSUE TITLE
Share  ViewModel with Maui and BlazorWebView

### ISSUE THREAD

**Issue by johngsandiford** [dotnet/maui#1550]
### Discussed in https://github.com/dotnet/maui/discussions/1530

<div type='discussions-op-text'>

<sup>Originally posted by **johngsandiford** July  2, 2021</sup>
Hi. I have a MAUI app that mixes MAUI controls and BlazorWebViews.  I want to be able to share a view-model (i.e. the same instance) between both the MAUI part and the Blazor part,  but I can't figure out how to share it.

_Some view-models are one per SPA, but others are created dynamically._

Any help much appreciated.  Thanks, John</div>

**Comment by Eilon** [comment]
Hi @johngsandiford because view models are regular C# types, you can register them in the dependency injection container as singletons and then use a single instance anywhere in the app. These registrations are typically done in the Startup.cs file in your app. In Razor files you can use the `@inject` directive to get an instance of them, and there are other APIs/patterns to consume them elsewhere in the app.

**Comment by johngsandiford** [comment]
Hi Eilon,
Many thanks for the reply!

I did try the @inject approach but:

1. I couldn't figure out how to inject the same instance into the MAUI code (e.g. I couldn't get InjectAttribute to work).  What is the recommended approach on the MAUI side?

2. Some of my view-models are one per SPA, so injecting would work, however if I am dynamically creating view-models I am not sure how I would pass them through to a BlazorWebView.  In some cases I guess you could use properties of an injected object that could be changed, but that seems limiting.

Many thanks, John

**Comment by Eilon** [comment]
@johngsandiford to retrieve services from a MAUI page you need to do it the MAUI way. I think you can do constructor injection, such as:

```c#
public partial class MyPage
{
    public class MyPage(ISomeService service)
    {
        // use the service here
    }
}
```

Or I think you can get the whole service provider and query your services explicitly:


```c#
public partial class MyPage
{
    public class MyPage(IServiceProvider services)
    {
        var myService = services.GetRequiredService<ISomeService>();
    }
}
```

**Comment by johngsandiford** [comment]
I have already tried the first way, and the second doesn't work for me.  Please can you confirm that it works for you.

Thanks, John

**Comment by johngsandiford** [comment]
Hi, thanks for the update.  Once I changed my service from scoped to singleton it works with the IServiceProvider method, so many thanks!
