### ISSUE TITLE
Using x:static in App.xaml located in Platform -> Windows folder causes build to fail with, XamlCompiler error WMC0001: Unknown type 'Static' in XML namespace 'http://schemas.microsoft.com/winfx/2006/xaml'

### ISSUE THREAD

**Issue by KCarterSr** [dotnet/maui#15509]
### Description

x:static causes a build to fail with, XamlCompiler error WMC0001: Unknown type 'Static' in XML namespace 'http://schemas.microsoft.com/winfx/2006/xaml' when used in any legitimate way, anywhere in the App.xaml file that is located in the Platforms-> Windows folder. The use of x:static in any way, shape, or form, will cause this error. I've tried this even on a fresh install of Visual Studio and and a new bare MAUI project. Still it fails.

When x:static is used in any other xaml file it works fine.

See steps to reproduce.

### Steps to Reproduce

1. Create a File -> new C# Maui App using .NET MAUI Template.
2. Use x:static in any legitimate way, anywhere in the App.xaml file that is located in the Platforms-> Windows folder.

That's all you have to do. The build will fail!

Here is my workload.

Installed Workload Id Manifest Version Installation Source
ios 16.2.2054/7.0.100 SDK 7.0.200, VS 17.5.33530.505
maccatalyst 16.2.2054/7.0.100 SDK 7.0.200, VS 17.5.33530.505
maui-android 7.0.81/7.0.100 VS 17.5.33530.505
android 33.0.46/7.0.100 VS 17.5.33530.505
wasm-tools 7.0.5/7.0.100 VS 17.5.33530.505
maui-windows 7.0.81/7.0.100 VS 17.5.33530.505
maui-maccatalyst 7.0.81/7.0.100 VS 17.5.33530.505
maui-ios 7.0.81/7.0.100 VS 17.5.33530.505

### Link to public reproduction project repository

[https://github.com/KCarterSr/XStatic-Error](https://github.com/KCarterSr/XStatic-Error)

### Version with bug

7.0.81

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

None

**Comment by KCarterSr** [comment]
Ok, here is a repro I created with a project for this bug.

[https://github.com/KCarterSr/XStatic-Error](https://github.com/KCarterSr/XStatic-Error)

IMHO - I hope this doesn't get put on the Backlog. Seems pretty significant to me.

Thanks

**Comment by drasticactions** [comment]
@KCarterSr I don't believe x:Static is available in WinUI 3, which is what MAUI uses for its Windows support. https://github.com/microsoft/microsoft-ui-xaml/issues/2232. You may be confusing WinUI with WPF.

So the error is correct, it doesn't exist.

**Comment by drasticactions** [comment]
I'm closing this. "x:static" is a WPF feature, and not supported in WinUI. This is not a MAUI bug. If you can show that it does work in WinUI and doesn't work in MAUI, you're welcome to reopen it.

**Comment by KCarterSr** [comment]
No problem. I only though it was open because https://github.com/microsoft/microsoft-ui-xaml/issues/2232 is open.

Thanks
