### ISSUE TITLE
[MAUI] Card will be truncated after resizing the window to be smaller and larger on Windows and MacCatalyst target 

### ISSUE THREAD

**Issue by QianaJiao** [dotnet/maui#15519]
### Description

Card will be truncated after resizing the window to be smaller and larger on Windows and MacCatalyst target

### Steps to Reproduce

**Steps to reproduce:**

1. Download the project https://github.com/rachelkang/recipeSearch and open it in Visual Studio.
2. Click on the 'My Recipes' tab to navigate to the 'My Recipes' page.
3. Resize the window to be larger, smaller, and every size in-between. Experiment with different sizes and note any obvious bugs or issues with the layout.

**Actual results:**
Card will be truncated after resizing the window to be smaller and larger.
![d2585728-0985-4b55-9a48-c8cb82d06ce0](https://github.com/dotnet/maui/assets/91244512/b7dc4e4f-3ba0-4385-abac-911982b81f68)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

8.0.0-preview.4.8333

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS

### Affected platform versions

net8.0-windows10.0.19041.0

**Comment by rachelkang** [comment]
@hartez are you familiar with this issue? it's using a CollectionView. And when I swap it out for a CarouselView, this isn't an issue whatsoever

**Comment by jaosnz-rep** [comment]
The original error mentioned that the picture is truncated is not reproduced at present, but when the window is resized on Windows and MacCatalyst, there will be a problem that the Image size doesn't match page size.

**Comment by samhouts** [comment]
Related? https://github.com/dotnet/maui/issues/10325
