### ISSUE TITLE
Shell navigation creates a void space after navigating to the target page

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#1551]
### Description
Shell navigation creates a void space after navigating to the target page (in Android)

### Steps to Reproduce

1. Create a new dotnet Maui project, define an AppShell, and set it as a Startup page in the CreateWindow() method
2. Define a Tab (with a ContentPage) within AppShell
3. Create another ContentPage and register its route using Routing.RegisterRoute() method
4. Define Shell navigation from Tab page to another page registered with route
5. Navigation occurs, but creates a void space in the target page, refer attached screenshot
6. Same is the case with a physical device and an emulator. Facing this issue in Android.

### Expected Behavior
Post navigation, there should not be any such void space occurring in the target.

### Actual Behavior
Shell navigation creates a void space after navigating to the target page

### Basic Information

- Version with issue: **.NET 6 Preview 5**
- Last known good version: **NA**
- IDE: **VS2019 16.11 Preview 2.0**
- Platform Target Frameworks: 
  - iOS:  
  - Android:  **API 30 (Android 11)**
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

Refer the void space below the AppBar
![Screenshot_1625564551](https://user-images.githubusercontent.com/81947404/124582011-3fea7c00-de6f-11eb-987d-d2f573eeb1ef.png)

**Comment by egvijayanand** [comment]
Issue still persists in .NET 6 Preview 6

**Comment by VincentBu** [comment]
@egvijayanand would you like to provide a sample project for us to repro?

**Comment by egvijayanand** [comment]
Hi @VincentBu, This issue was observed way back in .NET MAUI Preview 5, and now even am not able to simulate it.

This can be marked as closed. Attached is the scenario attempted.

[Issue1551.zip](https://github.com/dotnet/maui/files/8194861/Issue1551.zip)
