### ISSUE TITLE
Memory Leak issue in MAUI

### ISSUE THREAD

**Issue by MohamedHasan3644** [dotnet/maui#15523]
### Description

We have created a custom layout that holds labels and layout, but the layout does not dispose properly while the layout page is closed on the navigation page. Custom layout and its children hold on to memory after collecting the memory using a garbage collector.

Below code snippet is used to reproduce the issue.

```c#
public class DemoGrid : Grid
{
	public DemoGrid()
	{
		for (int i = 0; i < 2; i++)
		{
			this.Children.Add(new DemoStackLayout());
		}
	}
}

public class DemoStackLayout : StackLayout
{
	public DemoStackLayout()
	{
		for (int i = 0; i < 10; i++)
		{
			this.Children.Add(new Demolabel());
		}
	}
}

public class Demolabel : Label
{
	public Demolabel()
	{
		BackgroundColor = Colors.Red;
		Text = "Demo";
		HeightRequest = 100;
	}
}
```

### Steps to Reproduce

1. Create a file in .Net MAUI.
2. In MainPage Create two buttons, one for navigating to the page 2, other for calling Garbage collector.
3. Place the above code in the page 2 and add DemoGrid as the content of the page 2
4. In Diagnostics tool take snap shot for each process like,
   - Before page 2 navigation
   - After page 2 navigation
   - Before and after Calling Garbage collector
5. Issue can be seen on the snap shot taken after the Garbage collection.

![Screenshot (295)](https://github.com/dotnet/maui/assets/102596726/47a7affd-a374-470c-864a-3733c93eba0f)

### Link to public reproduction project repository

[MemoryLeak.zip](https://github.com/dotnet/maui/files/11687331/MemoryLeak.zip)

### Version with bug

7.0.81

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 pro 10.0.19044

**Comment by drasticactions** [comment]
![image](https://github.com/dotnet/maui/assets/898335/1d33424c-5694-472a-b818-c9eef8fe9dbd)

There's an `observablecollection` for the GestureManager and that might be holding on to those objects.

**Comment by Ahamed-Ali** [comment]
Any update on this ?

**Comment by jonathanpeppers** [comment]
The screenshot above has this warning:

![image](https://github.com/dotnet/maui/assets/840039/5c08b99c-070d-4359-baee-6e01fa2c92b6)

You can't reliably test memory leaks with XAML hot reload.

Using a local build of dotnet/maui/main, I don't see a leak in this app:

![image](https://github.com/dotnet/maui/assets/840039/4a435f34-af1c-4261-b796-4cb34d0596e0)

I did this 5 times:

* `Go to page 2`: button
* Back
* `GC` button
* Take memory snapshot

It could also be one of the fixes here that solved it:

* [Memory-related PRs](https://github.com/dotnet/maui/labels/memory-leak%20%F0%9F%92%A6)

I'm basically testing .NET 8, and the app here is .NET 7.

I think this issue will be solved if you can move to .NET 8.

Also turn off XAML hot reload if you want to test again. Thanks!
