### ISSUE TITLE
SwipeView crashes on Windows when in a CollectionView during scrolling

### ISSUE THREAD

**Issue by KeithBoynton** [dotnet/maui#15546]
### Description

When adding a simple SwipeView to a DataTemplate of a CollectionView and then scrolling through the collection view's items it crashes on Windows with an unhandled exception.

![image](https://github.com/dotnet/maui/assets/39023169/f6d376b8-dfa6-407c-83e3-8741113062de)

It works fine on iOS and macOS. It doesn't work on Android but at least doesn't crash.

### Steps to Reproduce

1. Create a new MAUI app
2. Add a CollectionView to the main page
3. Add a simple View Model with an observable collection for the item source
4. Wrap a label in a simple SwipeView in the DataTemplate for the CollectionView
5. Populate the observable collection with enough items to need scrolling
6. Run on Windows and scroll the collection

If using the supplied reproduction project. Then just run the project and scroll the collection.

### Link to public reproduction project repository

https://github.com/KeithBoynton/SwipeView

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

None found.

**Comment by n9** [comment]
@KeithBoynton Is this same as https://github.com/dotnet/maui/issues/7757?

**Comment by KeithBoynton** [comment]
It does look similar

**Comment by KeithBoynton** [comment]
This issue still remains in 8.0.100-rc.2.23502.2

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). This issue does not repro on Windows 11, Android 14.0-API34, iOS 17.0 and MacCatalyst with below Project:
[SwipeView.zip](https://github.com/dotnet/maui/files/13455609/SwipeView.zip)
