### ISSUE TITLE
All texts are upside down if using .NET MAUI Blazor App with Windows 11 Arabic

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#15556]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/All-texts-are-upside-down-if-using-NET-/10383876)._

---
The type of application used is .NET MAUI Blazor App
This problem disappears if the Windows 11 language is changed to English
By the way, it does not happen with other types of applications
![image](https://github.com/dotnet/maui/assets/202643/b39048dc-a09e-4602-b1c0-5198faa43adf)

---
#### Feedback Bot on 6/5/2023, 05:48 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by wtgodbe** [comment]
Could be that something is applying the right-to-left part of the localization transformation, but not actually the language change. Could confirm by checking other right-to-left languages like Hebrew.

**Comment by Eilon** [comment]
Original poster: Can you upload your code to a GitHub repo so we can take a look?

@wtgodbe I've never seen a case where the _font_ was rendered backwards. That's incredibly bizarre! At most I've seen the letters come out in the wrong order, that is, `hello` --> `olleh`, but not rendering each letter backwards.
