### ISSUE TITLE
Error handling/logging with MAUI

### ISSUE THREAD

**Issue by ThomasArdal** [dotnet/maui#1555]
### Discussed in https://github.com/dotnet/maui/discussions/1030

<div type='discussions-op-text'>

<sup>Originally posted by **ThomasArdal** May 15, 2021</sup>
I couldn't find any documentation on global error handling/logging with MAUI. With Xamarin and Xamarin.Forms you would do something like this (Android as an example):

```csharp
AndroidEnvironment.UnhandledExceptionRaiser += (sender, e) =>
{
    // do something with e
    e.Handled = true;
};
TaskScheduler.UnobservedTaskException += (sender, e) =>
{
    // do something with e
    e.SetObserved();
};
```

It seems to work in MAUI too. But I'm wondering if there are better ways to create these hooks now. Maybe as part of the `appBuilder` in `Startup.cs`?</div>

**Comment by jfversluis** [comment]
@ThomasArdal any reason you would repost this as an issue? The Discussions is the right place for this. Thanks!
