### ISSUE TITLE
FlyoutPage on iOS net8.0 opens Flyout extremely slowly

### ISSUE THREAD

**Issue by markmccaigue** [dotnet/maui#15552]
### Description

Please see video below, which captures first few seconds of waiting for the flyout to open.

https://github.com/dotnet/maui/assets/736783/5f625bc2-f1a7-49cb-8fbc-e0cd64655f33

### Steps to Reproduce

1. Check out MAUI Samples repository
2. Run the FlyoutPage sample on iOS
3. Observe the flyout animates open over the course of less than as second, as expected
4. Update the sample from net7.0 to to net8.0 and run it
5. Observe the flyout takes many seconds to animate open

### Link to public reproduction project repository

https://github.com/markmccaigue/maui-samples

### Version with bug

8.0.0-preview.4.8333

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

15.4 sim, 16.4 sim, 16.5 device

**Comment by PureWeen** [comment]
I just tested this with the latest .NET 8 preview 5 and it's fixed there.
