### ISSUE TITLE
Android Device Manager briefly appears then disappears

### ISSUE THREAD

**Issue by JLG123xx0** [dotnet/maui#15554]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I try to open the Android Device Manager, it first brings up the "Do you want to allow this app to make changes to your device?" screen (which I answer with a Yes), then... the screen returns to Visual Studio 2022 and another window briefly appears (which I suspect is the device manager) and quickly goes away.  It looks like it's trying to start the device manager, but fails.  I suspect that some type of permission is missing in my Windows 10, or that I have not installed something in Visual Studio 2022.  Can you suggest what it might be unhappy about, how to fix it, or what I might look for to analyze the source of the problem?
thanks, John

**Comment by Eilon** [comment]
@BethMassi

**Comment by BethMassi** [comment]
@JLG123xx0 Can you try to open the Device Manager directly? It should be in \Program Files\Microsoft Visual Studio\2022\Common7\IDE\Extensions\Xamarin\AndroidDeviceManager\AndroidDevices.exe

**Comment by jfversluis** [comment]
Seems like VS feedback didn't close this one and no further follow up. Closing this for now.
