### ISSUE TITLE
.net 8 preview 4 HotRestart prevents launching iOS app

### ISSUE THREAD

**Issue by gabsamples6** [dotnet/maui#15564]
### Description

Given the state of .net 7 in maui and that fixes are not backported to it unless considered critical by the MAUI team I have decided to give .net 8 preview a go and I have installed side by side - I just hope it doesnt blow up in my face..

1. Launch visual studio preview 4
2. Create a maui app from template
3. Connect to an iOS phone 
4. Launch the app and you see
![image](https://github.com/dotnet/maui/assets/109357537/4b763955-0f69-47ae-830e-0ed2ef077c2b)

### Steps to Reproduce

1. Launch visual studio preview 4
2. Create a maui app from template
3. Connect to an iOS phone 
4. Launch the app and you see
![image](https://github.com/dotnet/maui/assets/109357537/4b763955-0f69-47ae-830e-0ed2ef077c2b)

### Link to public reproduction project repository

n/a

### Version with bug

8.0.0-preview.4.8333

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Version 17.7.0 Preview 1.0

### Did you find any workaround?

no workaround

### Relevant log output

```shell
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.4.8377-net8-p4\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(252,3): error : Object reference not set to an instance of an object.
1>Done building project "MauiApp3.csproj" -- FAILED.
```
@BretJohnson   - do you have any ideas ? I am really keen to use preview because I am in the hope that all those bugs that made my life hell in .net 7 are gone :)

**Comment by PureWeen** [comment]
@emaf is this related to the issue I pinged you about?

**Comment by gabsamples6** [comment]
@PureWeen  well just installed preview 5 

- created a maui from template 
-  launch using physical device (iOS) 
- Automatic provisioning profile was a success 
-  I got below error, 
- 
![image](https://github.com/dotnet/maui/assets/109357537/32716f1c-9cb8-41fc-af49-84f59ce8d408)


What am I missing ??

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "DetectHotRestartSigningIdentity" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'Xamarin.iOS.Windows.HotRestartClient' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.Tracer, Version=2.1.0.0, Culture=neutral, PublicKeyToken=173d89ffae9ce988' or one of its dependencies. The system cannot find the file specified.
   at Xamarin.iOS.Windows.HotRestartClient..cctor()
   --- End of inner exception stack trace ---
   at Xamarin.iOS.Windows.HotRestartClient..ctor()
   at Xamarin.iOS.HotRestart.Tasks.DetectHotRestartSigningIdentity.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/Tasks/DetectHotRestartSigningIdentity.cs:line 70
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MauiApp2	C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.4.8525-net8-p5\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets	36

**Comment by gabsamples6** [comment]
@PureWeen  hi  not sure who works on hotrestart stuff on  your side but I would like to know if its something I am doing wrong or if its bug? using .net 7 I can attach an iphone and launch an app but I cant with .net 8 Preview 5. Can someone tell me one way or the other?

many thanks

**Comment by emaf** [comment]
@gabsamples6 Sorry for the delay. Yes, this is a bug on the .NET 8 Preview 5 iOS SDK version. We are working on a fix and we'll ship it in the next preview.

**Comment by eduard-dumitru** [comment]
I'm getting the same issue and I'm using:
- .NET SDK **8.0.100-preview.4.23260.5**
- workloads
  - maui-ios: **8.0.0-preview.4.8333/8.0.100-preview.4** 
  - ios: **16.4.8377-net8-p4/8.0.100-preview.4**

I'll try to switch to SDK version preview3 and wait for preview6.

**Comment by gabsamples6** [comment]
@samhouts  hi - tried the last version as well - and using windows 11 as host connecting to an iphone - hot restart prevents me from building any app even a simple brand new app.

`error : Error loading partial Info.plist template file 'obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist': Could not find a part of the path 'C:\MauiIssues\MauiApp1\MauiApp1\obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist'`

Have you tried using windows to use hot restart on maui 8 preview 6?  Does it work for you?

**Comment by samhouts** [comment]
Hey friends, sorry about that! This fix appears to have gone out with preview 7 (in 17.8 Preview 1), which just landed this week! We've validated this on our side, but please let me know right away if this is not working for you!

**Comment by UkeHa** [comment]
@samhouts, i'm getting the same error as @gabsamples6  with the latest preview

![grafik](https://github.com/dotnet/maui/assets/2254304/98930cc4-956b-460d-a727-d570387b06bd)

**Comment by emaf** [comment]
@UkeHa could you share a build binary log with that error? You can record one with the [Project System Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022) extension, by following [these](https://github.com/dotnet/project-system-tools#features) steps.

**Comment by UkeHa** [comment]
@emaf, sorry, i've reverted my machine to the latest stable version as the .net8 release had too many regressions

**Comment by emaf** [comment]
@gabsamples6 We have not been able to reproduce this error, would you be able to provide a binlog after reproducing it? 

> `error : Error loading partial Info.plist template file 'obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist': Could not find a part of the path 'C:\MauiIssues\MauiApp1\MauiApp1\obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist'`

**Comment by gabsamples6** [comment]
@emaf  I cannot replicate this bug anymore with the latest version  of  visual studio preview 7
A simple app builds and displays on a phisycal device... however unrelated I get warning on the package 
![image](https://github.com/dotnet/maui/assets/109357537/f5e0637c-7fec-4604-beb4-d11eae511e45)
