### ISSUE TITLE
Unable to add a second contentpage in maui

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#1556]
If I try to click on new contentpage, its still showing xamarin forms.  However, if I copy from one content page to another, it still gives compile errors.
Even this part
BackgroundColor="{DynamicResource PageBackgroundColor}"
is not working either.

Would be really disappointing if multiple content pages is not supported in maui.

**Comment by jfversluis** [comment]
> Would be really disappointing if multiple content pages is not supported in maui.

That is definitely a scenario that will be supported. I think this might be before we had the .NET MAUI templates in place? I expect this to work better by now. If you still experience issues with this please open a new issue with some more details and a reproduction project.

Thanks!
