### ISSUE TITLE
My Net To Makes Land

### ISSUE THREAD

**Issue by UpToDate2010** [dotnet/maui#15567]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mattleibow** [comment]
This issue seems to just have the default description. Can you open a new issue with more information if this was not an accidental open?
