### ISSUE TITLE
CollectionView scrolling is not working inside of other controls without HeightRequest.

### ISSUE THREAD

**Issue by higun295** [dotnet/maui#15572]
### Description

I'm making customized DataGrid template for my MAUI app.
Inside of ScrollView, I want to make whole DataGrid(include header) move horizontally and only data part move vertically, if both sizes are bigger than each mobile screen.

But, CollectionView is not scrolling without HeightRequest as I'd written on title.

### Steps to Reproduce

```xaml
<ScrollView Margin="20"
            HeightRequest="200"
            HorizontalOptions="FillAndExpand"
            Orientation="Horizontal">
    <Grid WidthRequest="500">
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="2*" />
        </Grid.RowDefinitions>
        <Label Grid.Row="0"
                BackgroundColor="Green"
                HeightRequest="50"
                Text="This is header." />
        <CollectionView x:Name="dataGrid"
                        Grid.Row="1" />
    </Grid>
</ScrollView>
```

### Link to public reproduction project repository

https://github.com/higun295/MAUI_Toys.git

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 5.0 and up, .net 7.0

**Comment by mattleibow** [comment]
@hartez when a scrollview is horizontal, should it also expand vertically but not scroll?

**Comment by higun295** [comment]
❤️

**Comment by EricKwon94** [comment]
버그 진챠 개많아요. 일좀 해라 이것들아~~,,

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 3. Not repro on Android platform with sample project. 
[higun295/MAUI_Toys (github.com)](https://github.com/higun295/MAUI_Toys)
