### ISSUE TITLE
CollectionView and ScrollView on iOS don't decelerate with fling gesture.

### ISSUE THREAD

**Issue by Hooterr** [dotnet/maui#15580]
### Description

On the first load when you scroll down a bit and lift your finger the collectionview scrolls all the way to the bottom and afterwards it only scrolls when your finger is touching the screen. 

Expected behavior: it should decelerate smoothly.

Apple calls it deceleration rate
https://developer.apple.com/documentation/uikit/uiscrollview/1619438-decelerationrate

Super basic repro

```
<CollectionView x:Name="collection"/>
collection.ItemsSource = Enumerable.Range(0, 200).ToList();
```

https://github.com/dotnet/maui/assets/28758721/f1be3f8b-7b4c-406f-be3d-4eb2ef85135b

Can't remember the version but it used to work...

### Steps to Reproduce

1. Just create a collectionview with a couple of items (data template doesn't matter)
2. Try to scroll it

### Link to public reproduction project repository

https://github.com/Hooterr/CollectionViewScrollBug

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4, iOS 15.5

### Did you find any workaround?

No

**Comment by Hooterr** [comment]
Here is the repro

```
<CollectionView x:Name="collection"/>
collection.ItemsSource = Enumerable.Range(0, 200).ToList();
```

**Comment by drasticactions** [comment]
I understand that the code for this is "simple", but having the exact code in a ready to run project makes it easier for anyone looking at this to test and debug it, and it can help when creating a test use case when it's fixed. Also, you can have the exact project ready for testing the fix when it's ready.

**Comment by Hooterr** [comment]
ScrollView is broken in the exact same way. Added repro to the repository.

**Comment by Hooterr** [comment]
More info:
I stumbled across a similar issue with the Flutter framework and it turned out to be some sort of an issue when targeting simualtorx86-64 on an M1 mac. To verify this I made a simple project in xcode with a collection view and put arm64 in excluded architectures. Almost the exact same issue occurs then too (it doesn't jump to the bottom but it won't decelerate smoothly in any direction).

**Comment by Hooterr** [comment]
Putting this in your project file solves the issue: https://github.com/dotnet/maui/issues/12124#issuecomment-1480790540
