### ISSUE TITLE
[MAUI] After rotating the Emulator/Simulator to horizontal orientation, the text in the picture disappears and the button is truncated.

### ISSUE THREAD

**Issue by QianaJiao** [dotnet/maui#15589]
### Description

After rotating the Emulator/Simulator to horizontal orientation, the text in the picture disappears and the button is truncated.

### Steps to Reproduce

**Steps to reproduce:**

1. Download the project https://github.com/rachelkang/recipeSearch and open it
2. Click on the Breakfast -> Breakfast Sausage Puffs
3. Rotate the Emulator/Simulator to horizontal orientation.

**Actual results:**
The text "Breakfast Sausage Puffs" in the picture disappears and "Add to my Recipes" button will be truncated.
![image](https://github.com/dotnet/maui/assets/91244512/f3740c19-eba3-4db0-aa27-131b1ef35544)

**Vertical orientation:**
![image](https://github.com/dotnet/maui/assets/91244512/e2d179fc-9c49-4255-918e-31f4c7bf5574)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

8.0.0-preview.4.8333

### Affected platforms

Android

**Comment by rachelkang** [comment]
Sample has since been updated to fix these issues
