### ISSUE TITLE
Switch to bootstrap icons in maui blazor template

### ISSUE THREAD

**Issue by surayya-MS** [dotnet/maui#15582]
https://github.com/dotnet/aspnetcore/issues/48341

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 3. The bootstrap icons as follows:
![image](https://github.com/dotnet/maui/assets/77434865/463d9fb7-efc6-46b2-a399-dd27d749f6ac)
