### ISSUE TITLE
[Bug] DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION when adding a CollectionView

### ISSUE THREAD

**Issue by carlubian** [dotnet/maui#1561]
### Description

Adding a CollectionView control to a page causes the app to no longer launch, and instead throws an unhandled exception that is caught on App.g.i.cs

This happens both with an empty CollectionView:

```xaml
<CollectionView Grid.Row="5" />
```

As well as with a "complete" element with a binding:

```xaml
<CollectionView Grid.Row="5" ItemsSource="{Binding People}"
                            HorizontalOptions="Center">
  <CollectionView.ItemTemplate>
    <DataTemplate>
      <Grid RowDefinitions="Auto,Auto">
        <Label Grid.Row="0" Text="{Binding FirstName}"/>
        <Label Grid.Row="1" Text="{Binding LastName}"/>
      </Grid>
    </DataTemplate>
  </CollectionView.ItemTemplate>
</CollectionView>
```

However, a Picker element is correctly shown, and displays the bound element (although without a data template, only showing the class name):

```xaml
<Picker Grid.Row="4" ItemsSource="{Binding People}"
             HorizontalOptions="Center">
                    
</Picker>
```

### Steps to Reproduce

1. Follow the installation guide and create a template project
2. Check that the app launches correctly
3. Open MainPage.xaml and add a CollectionView
4. Try to launch the app again

### Expected Behavior

The app should launch and display either an empty or a filled CollectionView.

### Actual Behavior

The app crashes after launching.

### Basic Information

- Version with issue: Preview 5
- Last known good version: None
- IDE: Visual Studio 16.11.0 Preview 2.0
- Platform Target Frameworks: 
  - Android: 11  
  - UWP: 19041   

### Screenshots

![issue-01](https://user-images.githubusercontent.com/15659739/124650629-375b6b00-de9a-11eb-97f3-d32c2b65db93.png)
Picker working correctly and showing elements.

![issue-02](https://user-images.githubusercontent.com/15659739/124650685-48a47780-de9a-11eb-8a23-13b3831721b1.png)
CollectionView throwing an exception.

### Reproduction Link

[GitHub repo](https://github.com/carlubian/MauiCollectionException)

### Workaround

Unknown

**Comment by jfversluis** [comment]
@carlubian the reproduction project is no longer available on GitHub or is set to private. Are you still having this issue with the current preview versions?

**Comment by carlubian** [comment]
I can confirm that the problem is gone in VIsual Studio 17.1 Preview 4.
Now the CollectionView is added correctly, and doesn't throw any exxceptions.

**Comment by jfversluis** [comment]
Perfect, thanks for letting us know!
