### ISSUE TITLE
Best Practices for SVG and Images

### ISSUE THREAD

**Issue by ChiefInnovator** [dotnet/maui#15611]
### Discussed in https://github.com/dotnet/maui/discussions/15610

<div type='discussions-op-text'>

<sup>Originally posted by **ChiefInnovator** June 13, 2023</sup>
We are constantly wanting to pull in SVGs and using them in our applications.  Unfortunately, we find that our builds start to slow down and/or come to a halt.  We believe this has to do with image creation from SVG to PNG done at build time.  When we remove the SVGs, our builds get fast again.  If we convert the images to PNGs ourselves, it fixes the problem.

We would like to use SVGs but are finding that the feature is not ready for production use.  We would like to use this feature but lack the necessary best practices.  Any guidance and answers to the following questions would be helpful.

1) How can we regenerate the images based on SVG so that we don't have to incur the expense at "build time"?
2) How can we make the generation of images based on SVGs faster?
3) Why would this process be so slow that it hangs our builds?
4) What additional best practices should we be looking at?

Thanks,
Rich</div>

**Comment by PureWeen** [comment]
@ChiefInnovator can you attach a binlog? 
https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

And possibly a repro with some svgs we can test?
