### ISSUE TITLE
A11y_.NETCore_RecipesAppMyRecipesNew_NewRecipe_NonTextContrast: Disabled "Save" button is not looking like disabled.

### ISSUE THREAD

**Issue by PoojaNamde** [dotnet/maui#15626]
### Description

[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver"**

### GitHub Tags:
#A11yMAS; #A11ySev2; #A11yTCS; #DesktopApp; #BM_.NETCore_Android_May23; #.NET Core; #Android; #WCAG1.4.11; #A11yWCAG2.1; #NonTextContrast; #AndroidPhone;

### Environment Details:​
Application Name: Rachel's Recipe
Operating System: Android 13
Screen Reader: Talkback

### Repro Steps:

1. Install and open ".NET MAUI" app.
2. Swipe till "My Recipes" and double tap.
3. Swipe till "New" button and double tap.
4. "New Recipe" Screen will open.
5. TAB to "Save" button and observe that Disabled "Save" button is not looking like disabled.

### Actual Results:
 Disabled "Save" button is not looking like disabled.

### Expected Results:
 Disabled "Save" button should look like disabled.

### User Impact:
Low vision users will get confused as here they will not understand whether button is in disabled state or enabled state.

### PWD Input:
All the users will not be able to differentiate the state of button as it is in enabled state or disabled state.

### Attachment:
![15626_Android](https://github.com/dotnet/maui/assets/90901519/da37609f-ea06-4dc2-b4cd-a3a3ed701c37)

### Steps to Reproduce

NA

### Link to public reproduction project repository

Test

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by 12-shweta** [comment]
Github Tags: #A11ySev4;A11yUsable;

**Comment by samhouts** [comment]
See also #15127

**Comment by PoojaNamde** [comment]
Verified the bug in latest environment
Bug is fixed and does not repro. Hence closing the bug.
Please find the closing attachment.

#Closed; #Regressed:07-25-23;
