### ISSUE TITLE
A11y_.NETCore_RecipesAppMyRecipesNew_NewRecipe_NonTextContrast: Disabled "Save" button is not looking like disabled.

### ISSUE THREAD

**Issue by PoojaNamde** [dotnet/maui#15628]
### Description

[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-nikpap%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847543876&sdata=6wiDneF0tmnVt4CroW43rkfVbB%2BL%2BAAdn0nD7xR5hQM%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver"**

### GitHub Tags:
#A11yMAS; #A11ySev2; #A11yTCS; #DesktopApp; #BM_.NETCore_iOS_May23; #.NET Core; #iOS; #iPhone; #WCAG1.4.11; #A11yWCAG2.1; #NonTextContrast;

### Environment Details:​
Application Name: Rachel's Recipe
Operating System: iOS (iPhone 6s)
Screen Reader: Voiceover

### Repro Steps:

1. Install and open ".NET MAUI" app.
2. Swipe till "My Recipes" and double tap.
3. Swipe till "New" button and double tap.
4. "New Recipe" Screen will open.
5. TAB to "Save" button and observe that Disabled "Save" button is not looking like disabled.

### Actual Results:
Disabled "Save" button is not looking like disabled.

### Expected Results:
Disabled "Save" button should look like disabled.

### User Impact:
Low vision users will get confused as here they will not understand whether button is in disabled state or enabled state.

### PWD Input:
All the users will not be able to differentiate the state of button as it is in enabled state or disabled state.

### Attachment:
![15628_IOS](https://github.com/dotnet/maui/assets/90901519/01f45dd4-bddc-4c98-8d7d-ba6d7776c69f)

### Link to public reproduction project repository

Test

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS version 15.7.6

**Comment by 12-shweta** [comment]
Github Tags: #A11ySev4;A11yUsable;

**Comment by PoojaNamde** [comment]
#Regressed:08-17-23; #Closed;

Verified the bug in latest environment.
Bug is fixed and does not repro. Hence closing the bug.
Please find the closing attachment
