### ISSUE TITLE
Oppo's system overrides the app's font and in place uses the system set font.

### ISSUE THREAD

**Issue by Hkarata** [dotnet/maui#15654]
### Description

I have tried to deploy a sample application in two different Oppo smartphones, I have found that any font you set on the app won't work on Oppo devices. The code is not erroneous and has been reviewed time over time.

The Oppo devices I tested on were: Oppo A7x (android 9) and Oppo F9 (android 10)

### Steps to Reproduce

1. create an application using MAUI
2. create any label use any desired font as long as that font is not the same as the system set font in Oppo device
3. test the application on **Oppo device**

**This is Oppo Specific Issue**

### Link to public reproduction project repository

https://github.com/Hkarata/Dall.git

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 9, android 10

**Comment by drasticactions** [comment]
Have you tried building a .NET Android application without the MAUI UI framework to see what that does?

You can do that by installing the Android workload

`dotnet workload install android`

and creating a template app

`dotnet new android`

My guess is that it will do the same behavior.

**Comment by Mnyema** [comment]
Fonts were applied when i made a .net Android app

**Comment by Hkarata** [comment]
Fonts were applied when i made a .net Android app

**Comment by Mnyema** [comment]
Thank you for the information

Mnyema's signature
