### ISSUE TITLE
[Android] Image with FontImageSource shows nothing after switching between the applications

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#15669]
### Description

There is a problem with `Image` and `FontImageSource` on lower versions of Android. Initially the image is displayed correctly. Switching to the home screen using the _back_ button, as shown in the screenshot below, and then restoring the application back causes the image to disappear. The only way to make it reappear is to quit the application and restart it again. The bug is reproducible on Android 10, API level 29 and below. I cannot reproduce the same on higher versions of Android. The usage of the `Image` with `FontImageSource` is pretty straightforward:

```xml
<Image Aspect="Center">
    <Image.Source>
        <FontImageSource FontFamily="FontAwesomeSolid"
                         Glyph="&#xf118;"
                         Size="200"
                         Color="Orange" />
    </Image.Source>
</Image>
```

Interestingly, it has something to do with the `NavigationPage` as well. The bug is reproducible, if I initialize the `MainPage` of the `Application` like this:

```csharp
public partial class App : Application
{
    public App()
    {
        InitializeComponent();

        MainPage = new NavigationPage(new MainPage());
    }
}
```

The bug is not reproducible when I am not using a `NavigationPage`, however:

```csharp
public partial class App : Application
{
    public App()
    {
        InitializeComponent();

        MainPage = new MainPage();
    }
}
```

After some debugging, I have found that pressing the _back_ button causes the `Unloaded` event of the `Page` to be fired. After restoring back the application, the `Loaded` event of the `Page` is fired. My speculation is that unloading and then reloading the same page is what is causing the bug with the image for some reason.

### Steps to Reproduce

1. Run the sample application on Android 10 or below.
2. Tap on the _back_ button as shown in the screenshot below.
3. Restore the application back.

Notice how the image is initially visible, but minimizing and then restoring the application causes it to disappear.

![Screenshot 2023-06-14 at 19 55 52](https://github.com/dotnet/maui/assets/98032058/06df4776-bc9e-4c56-8ee9-664e5d20cf77)

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/FontImageSourceSwitchApp

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10, API level 29 and below

### Did you find any workaround?

It is 2023 already and you still have an old Android 10 device?! It is about a time to upgrade, duh! :smile:

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 4.0. This issue repro on Android 10.0-API29 .NET 7, not repro on Android 10.0-API29 .NET 8, Windows 11 and iOS 16.4  with below Project:
[TestApp.zip](https://github.com/dotnet/maui/files/12121930/TestApp.zip)

**.NET 7:**
![ImageNET7](https://github.com/dotnet/maui/assets/97647558/f7059c09-c9d2-4019-a00b-458159c7a15e)

**.NET8:**
![Image](https://github.com/dotnet/maui/assets/97647558/20cf5b1a-01d3-4f01-9408-cf1000641a4e)
