### ISSUE TITLE
WebAuthenticator does not extract parameters contained in a fragment (regression)

### ISSUE THREAD

**Issue by rdavisau** [dotnet/maui#15661]
### Description

This test doesn't pass any more (case when parameters are contained in a fragment);

https://github.com/dotnet/maui/blob/9b091fd530cf54bb8c756474fc7585ec125a9b66/src/Essentials/test/DeviceTests/Tests/WebAuthenticator_Tests.cs#L60

Introduced by #15245, which changes parameter extraction to happen off of Uri.Query (seems fragment parameters are found in Uri.Fragment) 
https://github.com/dotnet/maui/commit/edeae340ab9ee9d8a8a5f5fc3dfb4a0f17729ff3#diff-686959c852a62a0b284d6cf92e5b61a6871108fbfc177d8ef9be7ccc94fbc2dfR18

This prevents successful authentication when callback parameters are returned in a fragment.

### Steps to Reproduce

Run the WebAuthenticator `ParseQueryString` tests

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

8.0.0-preview.4.8333

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

all

### Did you find any workaround?

User can extract any required parameters from `WebAuthenticatorResult.CallbackUri` manually

**Comment by jstedfast** [comment]
The URI in the test should probably be fixed:

```csharp
[InlineData("xamarinessentials://?refresh_token=blah2&expires=1#access_token=blah", "blah", "blah2", "1")]
```

Or does our code generate these types of URIs where the fragment is assumed to be allowed to contain query parameters?
