### ISSUE TITLE
Remove NewsstandKit Dependency to build targeting iOS17

### ISSUE THREAD

**Issue by wtvamp** [dotnet/maui#15660]
### Description

When building with iOS17 as a target, builds fail with: 

Termination Reason: DYLD 1 Library missing
Library not loaded: /System/Library/Frameworks/NewsstandKit.framework/NewsstandKit

Per the iOS 17 release notes, it looks like NewsstandKit has been removed from the latest release: https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-17-release-notes

### Public API Changes

I'm not sure as I could not find any references to NewsstandKit in the github repo even though the build definitely fails.

### Intended Use-Case

Anyone attempting to target ios 17 as a build target will fail with the above error.

**Comment by drasticactions** [comment]
The [xamarin-macios SDK](https://github.com/xamarin/xamarin-macios) still needs to be updated for iOS 17 support, so you can't build on iOS 17, and is unrelated to the MAUI UI project. I would raise your concerns over it to that repo.
