### ISSUE TITLE
SelectionChangedCommand does not invoke in CollectionView twice when SelectionMode is Single on Windows

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#15677]
### Description

On Windows when SelectionMode is Single the Selected item can't be unselected by assigning null value to the Selected Item in the ViewModel. 

### Steps to Reproduce

Run the reproduction project on windows. Select an item from the list of items in CollectionView. The Selected Item is set to null in the ViewModel. But still the SelectionChangedCommand does not invoke on re-selecting it.

### Link to public reproduction project repository

https://github.com/HobDev/MauiBugs/tree/CollectionViewSelectionIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

May be using SelectionMode=Multiple serve the purpose in some scenarios.

**Comment by jaosnz-rep** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 4. Can repro on Windows platforms with sample project.
https://github.com/HobDev/MauiBugs/tree/CollectionViewSelectionIssue
