### ISSUE TITLE
Navigation to ContentPage make weird animation on IOS

### ISSUE THREAD

**Issue by LeoThinnes** [dotnet/maui#15684]
### Description

When you go to a new page by clicking on a button with a pushAsync, there is a strange animation, like a delay.

https://github.com/dotnet/maui/assets/63150113/ff21ee05-0732-4470-ba68-216bd3b52af5

### Steps to Reproduce

1. Create maui app
2. Add new ContentPage 
3. Add button on mainPage to navigate with pushAsync
4. click on the button

### Link to public reproduction project repository

https://gitlab.com/LeoThinnes/repropushasync.git

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4, 16.5

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 4.0. This issue does not repro on iOS 16.4 .NET 8, Windows 11 and Android 13.0-API33 with below Project:
[15684.zip](https://github.com/dotnet/maui/files/12144764/15684.zip)

![NewPage](https://github.com/dotnet/maui/assets/97647558/715fe1b6-b6f5-46bf-84cd-0168512fe64f)

**Comment by LeoThinnes** [comment]
Verified on Visual Studio Community 2022 for Mac, Version 17.6 Preview (17.6 build 1569), and everything works.

**Comment by mattleibow** [comment]
Awesome! Closing this now. Please open a new issue if anything breaks again.
