### ISSUE TITLE
Back button not displayed in WinUI title bar while using NavigationPage

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#1568]
### Description
Back button not displayed in WinUI title bar while using NavigationPage

### Steps to Reproduce

1. Create a new dotnet Maui project, and use NavigationPage as Startup page in the CreateWindow() method
2. Create another ContentPage
4. Define navigation from the initial page to another page with PushAsync() method
5. Navigation occurs, but the back button is missing in the target page title bar so as to come back to original page
6. Facing this issue in WinUI project. Refer screenshot. 

### Expected Behavior
The title bar should have a back button along with the Page title

### Actual Behavior
Back button missing in the title bar

### Basic Information

- Version with issue: **.NET 6 Preview 5**
- Last known good version: **NA**
- IDE: **VS2019 16.11 Preview 2.0**

- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
  - WinUI: **Target SDK version 10.0.19041 (running on Windows 10 21H1)**
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

<img width="960" alt="WinUI-BackButton" src="https://user-images.githubusercontent.com/81947404/124732036-6f14f200-df30-11eb-844a-63b05343b8c9.png">

**Comment by egvijayanand** [comment]
Issue still persists in .NET 6 Preview 6

**Comment by PureWeen** [comment]
Xamarin.Forms was based on UWP which utilized the backbutton in the status bar. MAUI is based on WinUI which has no statusbar so we had to create a new one.

This should be fixed with Preview 9 https://github.com/dotnet/maui/pull/2551
