### ISSUE TITLE
Android crash on navigate back from tab 2 without Shell

### ISSUE THREAD

**Issue by sebdesalvador** [dotnet/maui#15687]
### Description

I have created a very simple app with only a `MainPage` and a `TabbedPage` with its tabs at the bottom. Navigation is done without a `Shell`, so the `App`'s main page is actually a `NavigationPage`. Pushing the `TabbedPage` onto the navigation stack automatically creates the navigation bar with a back button at the top (as expected, and _to my current knowledge_, absolutely impossible to do with a `Shell`). When navigating from the 2nd tab of the `TabbedPage` back to the `MainPage` via the back button, the app crashes with a `NullReferenceException`.

Strangely enough, if the `TabbedPage` only contains 2 tabs, or if the tabs are at the top, the app doesn't crash, and when it contains more than 2 bottom tabs, the crash only happens from the 2nd tab.

It happens on _Android_ simulator as well as on an _Android_ device and I only tested .NET 7 and latest .NET 8 preview. Doesn't happen on _iOS_ (simulator or device).

I'd like to know if it's only on my machine (mac), or if it's a general issue.

Thanks

### Steps to Reproduce

1. Create a basic MAUI app (no blazor)
2. Remove the `AppShell` (xaml and xaml.cs)
3. Modify the `App.xaml.cs` constructor to initialise the `NavigationPage`
```csharp
public App()
{
    InitializeComponent();
    MainPage = new NavigationPage( new MainPage() );
}
```
4. Create a `TabbedPage` at the root of the project with 3 `ContentPage`s, call it `MyTabbedPage` (notice the _Android_ specific argument on the `TabbedPage` node to make the tabs appear at the bottom)
```xml
<?xml version="1.0" encoding="utf-8"?>

<TabbedPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:android="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;assembly=Microsoft.Maui.Controls"
            x:Class="ThreeTabsCrash.MyTabbedPage"
            Title="TabbedPage"
            android:TabbedPage.ToolbarPlacement="Bottom">

    <ContentPage Title="Tab 1">

        <ScrollView>

            <VerticalStackLayout
                Spacing="25"
                Padding="30,0"
                VerticalOptions="Center">

                <Label
                    Text="Tab 1"
                    SemanticProperties.HeadingLevel="Level1"
                    FontSize="32"
                    HorizontalOptions="Center" />

            </VerticalStackLayout>
        </ScrollView>

    </ContentPage>

    <ContentPage Title="Tab 2">

        <ScrollView>

            <VerticalStackLayout
                Spacing="25"
                Padding="30,0"
                VerticalOptions="Center">

                <Label
                    Text="Tab 2"
                    SemanticProperties.HeadingLevel="Level1"
                    FontSize="32"
                    HorizontalOptions="Center" />

            </VerticalStackLayout>
        </ScrollView>

    </ContentPage>

    <ContentPage Title="Tab 3">

        <ScrollView>

            <VerticalStackLayout
                Spacing="25"
                Padding="30,0"
                VerticalOptions="Center">

                <Label
                    Text="Tab 3"
                    SemanticProperties.HeadingLevel="Level1"
                    FontSize="32"
                    HorizontalOptions="Center" />

            </VerticalStackLayout>
        </ScrollView>

    </ContentPage>

</TabbedPage>

```
5. Create a button on the `MainPage` to navigate to the `TabbedPage`
```xml
<Button
    Text="Go To Tabs"
    Clicked="OnTabsClicked"
    HorizontalOptions="Center" />
```
```csharp
private void OnTabsClicked( object sender, EventArgs e )
{
    App.Current.MainPage.Navigation.PushAsync( new MyTabbedPage() );
}
```
6. Start the app (Debug or Release mode)
7. Navigate to the `TabbedPage` via the button on the `MainPage`
8. Navigate to the 2nd tab
9. Hit the back button (from the navigation bar or the actual device's back button)
10. Suffer the crash

### Link to public reproduction project repository

https://github.com/sebdesalvador/ThreeTabsCrash

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Pixel 5 - API 33

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 4.0. Repro on Android 13.0-API33 .NET 8, not repro on Windows 11 and iOS 16.4 with below Project:
[ThreeTabsCrash.zip](https://github.com/dotnet/maui/files/12156780/ThreeTabsCrash.zip)

![image](https://github.com/dotnet/maui/assets/97647558/5be45891-b965-4b6e-9dd9-7e639c1abbb4)
