### ISSUE TITLE
Errors: WinUI is causing errors.The Android version is not experiencing any issues.The permanent keyboard hiding feature is not working

### ISSUE THREAD

**Issue by persiabudi28** [dotnet/maui#15708]
After updating to Microsoft visual studio v 17.6.3, the code for WinUI is causing errors.The Android version is not experiencing any issues.The permanent keyboard hiding feature is not working.

**Comment by Eilon** [comment]
@persiabudi28 also, can you please show screenshots or copy/paste the error messages? There is not enough information for us to understand what the problem is.
