### ISSUE TITLE
Maui Map touch control not working or stops working soon

### ISSUE THREAD

**Issue by dustin2711** [dotnet/maui#15714]
### Description

Everytime I want to drag (or zoom) on the Microsoft.Maui.Controls.Maps map, it **doesnt work at all or it works for like 0.3 seconds and then it gets unresponsive**.
When I elevate my finger and start dragging again: same behaviour. An interaction with the map is impossible.

### Steps to Reproduce

Create a new .NET MAUI APP using .NET 7.0.

Add **Microsoft.Maui.Controls.Maps** package using Nuget.

In **MauiProgram.cs** class I add following line to the MauiAppBuilder:
`.UseMauiMaps()`

In **AppShell.xaml**, include Microsoft.Maui.Control.Maps.Map assembly and add a Map control.
`xmlns:maps="clr-namespace:Microsoft.Maui.Controls.Maps;assembly=Microsoft.Maui.Controls.Maps"`
`<maps:Map
                x:Name="map"
                HeightRequest="500"
                WidthRequest="1000"
                HorizontalOptions="Center"`

Add google API key in **manifest.xml**.

Run application on a Pixel 7 Pro with Android 13. Try to control the map.

### Link to public reproduction project repository

https://github.com/dustin2711/MauiMapControlError

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

Not yet

**Comment by drasticactions** [comment]
Your linked repro project doesn't exist, can you please add it?

**Comment by dustin2711** [comment]
The repository is now available. Please have a look into it.
