### ISSUE TITLE
OnPlatform x:TypeArguments does not support Default case

### ISSUE THREAD

**Issue by HavenDV** [dotnet/maui#15715]
### Description

xaml OnPlatform syntax does not support Default case.

I want to point out that this has been accurately tested, but under the assumption that the resources are stored in an external NuGet package, where the ResourceDictionary has x:Class and code behind the class with a call to InitializeComponent();

### Steps to Reproduce

```xml
<OnPlatform x:Key="Primary" x:TypeArguments="Color">
        <On Platform="iOS,MacCatalyst" Value="Red" />
        <On Platform="Default" Value="Blue" />
</OnPlatform>
```
This is expected to be Blue for Android, but it will be undefined

### Link to public reproduction project repository

-

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

macOS 13.4

### Did you find any workaround?

Specify all platforms manually separated by commas

**Comment by drasticactions** [comment]
As far as I'm aware (@StephaneDelcroix, maybe you'll know more?), that was never supported. In the documentation (https://learn.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/essential-syntax#platform-differences) it does not reference Default, and it wasn't supported in Xamarin.Forms either.

There is a markup extension for `OnPlatform` that is documented (https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/customize-ui-appearance#customize-ui-appearance-based-on-the-platform) and does work with Default.

![image](https://github.com/dotnet/maui/assets/898335/d69e2d42-1364-4e6a-abb0-5436354feace)

**Comment by jfversluis** [comment]
You have to set the default on the `OnPlatform` node

```xml
<OnPlatform x:Key="Primary" x:TypeArguments="Color" Default="Blue">
        <On Platform="iOS,MacCatalyst" Value="Red" />
</OnPlatform>
```

**Comment by HavenDV** [comment]
Thanks, I think it's worth noting this somewhere in the documentation. I think I searched in detail

**Comment by jfversluis** [comment]
@HavenDV done: https://learn.microsoft.com/dotnet/maui/xaml/fundamentals/essential-syntax#platform-differences
