### ISSUE TITLE
Android Platform App Theme does not automatically update when switching themes

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#15723]
### Description

When switching themes at a platform level with Android, the application does not automatically switch to the other theme. While it can update without closing the application, you need to reinvoke launching it at least twice, if not more, for the change to work.

### Steps to Reproduce

1. Run the attached application.
2. After starting the application, note the default settings for your given device/emulator.
3. Go to your system settings, switch the system theme to the opposite.
4. Navigate back to your application through the multitasking menu or app menu.
5. It should not switch themes at this point. Navigate back to the app menu, then navigate back to the application (using the app icon or multitasking)
6. It should now update to the other theme.

### Link to public reproduction project repository

https://github.com/drasticactions/MauiRepros/tree/main/ThemeChangeError

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

At least Android 11 and up.

### Did you find any workaround?

Invoke the UserAppTheme, which changes automatically. However, this then "breaks" the RequestedAppTheme Event, since you now need to set the app theme yourself for it to work.

**Comment by jaosnz-rep** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 4. Can not repro on Android platforms with sample project.
https://github.com/drasticactions/MauiRepros/tree/main/ThemeChangeError
