### ISSUE TITLE
Project report issue 

### ISSUE THREAD

**Issue by bnhassin** [dotnet/maui#15736]
### Description

**[Template team feedback issue #35867](https://github.com/dotnet/docs/issues/35867)**

Create 35867.md 
https://github.com/bnhassin/maui.community/commit/2ca53b06d94d5fb903de4b824bc4df20bbb13024

![Screenshot_20230620-005046](https://github.com/dotnet/maui/assets/1473765/425029fb-16b2-4d6d-9560-4928df18b06d)

[issues](https://github.com/bnhassin/maui.community/tree/main/.github/ISSUE_TEMPLATE/docs/issues)

![IMG_20230620_015800](https://github.com/dotnet/maui/assets/1473765/db06e490-6841-4059-a75b-1e7133a8a217)

[workflow runs](https://github.com/bnhassin/maui.community/actions/workflows/dotnet-desktop.yml)

![Screenshot_20230620-010601](https://github.com/dotnet/maui/assets/1473765/feff1e68-6ed6-40a3-9271-7479451bdd18)

vscode.json

https://github.com/dotnet/maui/commit/79e0cf49811fbdbfd49931390c2db6cc00094e98

[docs/patch-1/README.md](https://github.com/dotnet/maui/blob/6ef6f39a0749d3892a2939b90fce026aff4e1855/docs/patch-1/README.md)

dotnet workload list

### Steps to Reproduce

)

### Link to public reproduction project repository

https://github.com/users/bnhassin/projects/1/

### Version with bug

Unknown/Other

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by Eilon** [comment]
Hi @bnhassin can you explain the actual issue? This seems like some AI-generated text that isn't specific to this repo?
