### ISSUE TITLE
Remote images not working in Image tag in latest version on Android

### ISSUE THREAD

**Issue by LewisEKay** [dotnet/maui#15735]
### Description

Image URLS dot load in image tag when specified like so: `Source="https://ichef.bbci.co.uk/food/ic/food_16x9_320/recipes/rainbow_cake_20402_16x9.jpg"`

I've seen some past issues about this back in 2022 and they said it was fixed but clearly something has happened.

### Steps to Reproduce

1. Create a new MAUI App targeting .NET 7.
2. Go to MainPage and replace Image source of the cute dot net bot to a url.
3. Load app, image not visible.

### Link to public reproduction project repository

https://github.com/LewisEKay/MauiImageError

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by drasticactions** [comment]
![image](https://github.com/dotnet/maui/assets/898335/93cd3d98-936b-45d5-9d0e-701c8a7962d3)

It seems to be fine? Am I missing something here?
