### ISSUE TITLE
A11y_.NET Core_Recipes App My Recipes New_New Recipe_NonTextContrast: Disabled "Save" button is not looking like disabled.

### ISSUE THREAD

**Issue by Swati1700** [dotnet/maui#15740]
### Description

[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver"

### GitHubTags:
#A11yMAS;#A11yTCS;#BM_.NET Core[MAUI]-Win32-May2023;#.NET Core;#A11ySev2;#DesktopApp; #Win11;#Benchmark;#WCAG1.4.11;#A11yWCAG2.1;#NonTextContrast;#Closed

### Steps to Reproduce:
Install and open ".NET MAUI" app.
TAB till "My Recipes" and double tap.
TAB till "New" button and double tap.
"New Recipe" Screen will open.
TAB to "Save" button and observe that Disabled "Save" button is not looking like disabled.
Actual Results:
Disabled "Save" button is not looking like disabled.

### Expected Results:
Disabled "Save" button should look like disabled.

### User Impact:
Low vision users will get confused as here they will not understand whether button is in disabled state or enabled state.

### PWD Input:
All the users will not be able to differentiate the state of button as it is in enabled state or disabled state.

### Link to public reproduction project repository

Test

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Windows

### Affected platform versions

Windows 11 23H2

**Comment by samhouts** [comment]
See also #15127

**Comment by Swati1700** [comment]
verified the bug and now the issue does not repro. Issue is fixed hence closing the bug. Please find the closing attachment below
![nontext](https://github.com/dotnet/maui/assets/86710888/9f8e9d31-7211-4df3-94fd-47c54545474d)
