### ISSUE TITLE
ColumnDefinition with * inconsistent

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#15757]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ColumnDefinition-with--inconsistent/10390848)._

---
[regression] [worked-in:17.6.2]
see attached image - submitting feedback crashing on every attempt, the connection from VS to Edge failing constantly. 

Materials Column not remaining proportional - it is dynamic to the contents being displayed.  Driving other fields off the screen

---
#### Feedback Bot on 6/13/2023, 10:48 PM: 

(private comment, text removed)
#### JASON Zhao [MSFT] on 6/15/2023, 02:54 AM: 

(private comment, text removed)
#### Rick Lunt on 6/15/2023, 09:03 AM: 

(private comment, text removed)
#### JASON Zhao [MSFT] on 6/16/2023, 01:28 AM: 

(private comment, text removed)
#### Rick Lunt on 6/16/2023, 05:01 AM: 

(private comment, text removed)
#### JASON Zhao [MSFT] on 6/19/2023, 03:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment]
@hartez is this maybe fixed with the grid changes?
