### ISSUE TITLE
Scroll Slow .Net Maui Android 7 CollectionView + slow tab switch Shell

### ISSUE THREAD

**Issue by lucianparvu** [dotnet/maui#15755]
### Description

I experience a slow scroll in .NET Maui Android (IOS works perfect) and sometimes the scroIl has a delay, some time slow tab switch (Shell) and need some guidance.

Full xaml  examples : 

https://github.com/lucianparvu/Files/blob/main/HomePage.xaml - Slow Scroll with some delays 

https://github.com/lucianparvu/Files/blob/main/ProductCategoryDetailPage.xaml - Slow Scroll with some delays + Slow Tab (Shell) switch when come back .

The Structure Example
  ```
<RefreshView Command="{Binding RefreshCommand}" IsRefreshing="{Binding IsRefreshing}" >
        <Grid >
            <CollectionView ItemsSource="{Binding ProductCategoryList}"   SelectionMode="None" ItemsUpdatingScrollMode="KeepScrollOffset">
                <CollectionView.Header>
                    <VerticalStackLayout IsVisible="{Binding HasBanners}">
                        <Border  BackgroundColor="Transparent" >
                            <Border.StrokeShape>
                                <RoundRectangle CornerRadius="10"/>
                            </Border.StrokeShape>
                            <CarouselView ItemsSource="{Binding BannerFileList}" HeightRequest="{OnIdiom Phone=160, Tablet=230, Default=250}"  
                                          x:Name="BannersCarouselView" Position="{Binding PositionBanner}"
                                          BackgroundColor="Transparent"  IndicatorView="IndicatorViewBanners" Loop="False" >
                               ...
                            </CarouselView>
                        </Border>
                        
                        <IndicatorView x:Name="IndicatorViewBanners"    
                                IndicatorsShape="Circle"
                                IndicatorColor="#c4c4c4"
                                SelectedIndicatorColor="{StaticResource AccentColor}"
                                HorizontalOptions="Center"
                                VerticalOptions="End"
                                Margin="0,8,0,10" HeightRequest="20" Position="{Binding PositionBanner}"  >  
                           ..........
                        </IndicatorView>
                      
                    </VerticalStackLayout>                  
                </CollectionView.Header>
                <CollectionView.ItemsLayout>
                    <GridItemsLayout Span="{OnIdiom Phone=2, Tablet=3, Desktop=4}"
                                         Orientation="Vertical"
                                         HorizontalItemSpacing="15"
                                         VerticalItemSpacing="15"/>

                </CollectionView.ItemsLayout>
                <CollectionView.ItemTemplate   SelectionMode="None"  >
                    <DataTemplate x:DataType="model:ProductCategory"  >
                    
                        <Border Padding="5" Style="{StaticResource RoundedGrayBorder}"  Margin="0,0" >
                            <Border.StrokeShape>
                                <RoundRectangle CornerRadius="10"/>
                            </Border.StrokeShape>
                            
                            <Grid Padding="5" HorizontalOptions="Center">
                                ........
                            </Grid>
                        </Border>
                     
                    </DataTemplate>
                </CollectionView.ItemTemplate>                
             
            <CollectionView.Footer>
                    <VerticalStackLayout Padding="0"   Spacing="15"  Margin="0,15,0,0"   IsVisible="{Binding HasFooter}">
                        <VerticalStackLayout IsVisible="{Binding HasNewProductsOnHomePage}">
                            <Label  Text="{x:Static localization:AppResource.NewProductsOnHomePage}"  FontAttributes="Bold" FontSize="14"></Label>
                            <CollectionView  ItemsSource="{Binding NewProductList}"
                                 SelectionMode="None"  Margin="0, 10"  HeightRequest="220"   >                                
                                <CollectionView.ItemsLayout>
                                    <LinearItemsLayout Orientation="Horizontal" ItemSpacing="10" />
                                </CollectionView.ItemsLayout>
                                <CollectionView.ItemTemplate>
                                    <DataTemplate x:DataType="model:Product">
                                        <Border Padding="5,0"  Style="{StaticResource RoundedGrayBorder}"  >
                                           .....
                                        </Border>
                                    </DataTemplate>
                                </CollectionView.ItemTemplate>
                            </CollectionView>
                        </VerticalStackLayout>
                        <VerticalStackLayout IsVisible="{Binding HasRecommendedProductsOnHomePage}">
                            <Label   Text="{x:Static localization:AppResource.RecommendedProductsOnHomePage}"  FontAttributes="Bold" FontSize="14"></Label>
                            <CollectionView   ItemsSource="{Binding HomeProductList}" 
                               SelectionMode="None"    Margin="0, 10"  HeightRequest="220"  >
                                
                                <CollectionView.ItemsLayout>
                                    <LinearItemsLayout Orientation="Horizontal"   ItemSpacing="10"/>
                                </CollectionView.ItemsLayout>
                                <CollectionView.ItemTemplate>
                                    <DataTemplate  x:DataType="model:Product">
                                       ............
                                            </Border>
                                    </DataTemplate>
                                </CollectionView.ItemTemplate>
                            </CollectionView>    
                        </VerticalStackLayout>
                        <VerticalStackLayout IsVisible="{Binding HasRecentlyVisitedProducts}">
                            <Label   Text="{x:Static localization:AppResource.RecentlyViewed}"  FontAttributes="Bold" FontSize="14"></Label>
                            <CollectionView   ItemsSource="{Binding RecentlyVisitedProductList}" 
                               SelectionMode="None"    Margin="0,5"  HeightRequest="220"  >

                                <CollectionView.ItemsLayout>
                                    <LinearItemsLayout Orientation="Horizontal"   ItemSpacing="10"/>
                                </CollectionView.ItemsLayout>
                                <CollectionView.ItemTemplate>
                                    <DataTemplate  x:DataType="model:RecentlyVisitedProduct">
                                       ...........  
                                    
                                    </DataTemplate>
                                </CollectionView.ItemTemplate>
                            </CollectionView>
                        </VerticalStackLayout>
                    </VerticalStackLayout>
            </CollectionView.Footer>
        </CollectionView>
        </Grid>
    </RefreshView> 
```

### Steps to Reproduce

-

### Link to public reproduction project repository

https://github.com/lucianparvu/Files/blob/main/HomePage.xaml

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

all

**Comment by angelru** [comment]
@lucianparvu 

It looks like it uses nested CollectionViews, I think this causes bad performance, I made a similar post, try using BindableLayouts and only 1 CollectionView.

I think for .NET 8 many performance issues have been fixed, you can see here:

https://github.com/dotnet/maui/issues/12130

**Comment by lucianparvu** [comment]
> @lucianparvu
> 
> It looks like it uses nested CollectionViews, I think this causes bad performance, I made a similar post, try using BindableLayouts and only 1 CollectionView.
> 
> I think for .NET 8 many performance issues have been fixed, you can see here:
> 
> #12130

Thank's for your answer

Meanwhile the issue with infinite scroll was solved in Android by incresing : MONO_GC_PARAMS=nursery-size=128m

I wil try to use bindable layout and come back

**Comment by angelru** [comment]
> > @lucianparvu
> > It looks like it uses nested CollectionViews, I think this causes bad performance, I made a similar post, try using BindableLayouts and only 1 CollectionView.
> > I think for .NET 8 many performance issues have been fixed, you can see here:
> > #12130
> 
> Thank's for your answer
> 
> Meanwhile the issue with infinite scroll was solved in Android by incresing : MONO_GC_PARAMS=nursery-size=128m
> 
> I wil try to use bindable layout and come back

In my application I also have that:
https://github.com/angelru/ValdemoroEn1/blob/main/src/ValdemoroEn1/Platforms/Android/GarbageCollector.config

**Comment by lucianparvu** [comment]
I have tried to use bindable layout in footer collections  and there is no improvment in Android at scroll and tab switch too . And it seems is not recommended if u need scroll .

I suspect that the main collection with vertical scroll is the problem because it has footer, maybe it doesnt know the real height.  If i change to horizontal orientation, everything works smooth . The problem is in this case that the main collection is populated from database and dont know how many items will be . Maybe another approach ?

<CollectionView ItemsSource="{Binding ProductCategoryList}"   SelectionMode="None" ItemsUpdatingScrollMode="KeepScrollOffset">
              <CollectionView.Header>
                  <VerticalStackLayout IsVisible="{Binding HasBanners}">
                      <Border  BackgroundColor="Transparent" >
                          <Border.StrokeShape>
                              <RoundRectangle CornerRadius="10"/>
                          </Border.StrokeShape>
                          <CarouselView ItemsSource="{Binding BannerFileList}" HeightRequest="{OnIdiom Phone=160, Tablet=230,  
                             ...
                          </CarouselView>
                      </Border>
                      
                  </VerticalStackLayout>                  
              </CollectionView.Header>
              <CollectionView.ItemsLayout>
                  <GridItemsLayout Span="{OnIdiom Phone=2, Tablet=3, Desktop=4}"
                                       Orientation="Vertical"
                                       HorizontalItemSpacing="15"
                                       VerticalItemSpacing="15"/>

              </CollectionView.ItemsLayout>
              <CollectionView.ItemTemplate   SelectionMode="None"  >
                 .......
              </CollectionView.ItemTemplate>                
           
          <CollectionView.Footer>
                  <VerticalStackLayout Padding="0"   Spacing="15"  Margin="0,15,0,0"   IsVisible="{Binding HasFooter}">
                      <VerticalStackLayout IsVisible="{Binding HasNewProductsOnHomePage}">
                          <Label  Text="{x:Static localization:AppResource.NewProductsOnHomePage}"  FontAttributes="Bold" FontSize="14"></Label>
                          <CollectionView  ItemsSource="{Binding NewProductList}"
                               SelectionMode="None"  Margin="0, 10"  HeightRequest="220"   >                                
                               ..............
                          </CollectionView>
                      </VerticalStackLayout>
                      <VerticalStackLayout IsVisible="{Binding HasRecommendedProductsOnHomePage}">
                          <Label   Text="{x:Static localization:AppResource.RecommendedProductsOnHomePage}"  FontAttributes="Bold" FontSize="14"></Label>
                          <CollectionView   ItemsSource="{Binding HomeProductList}" 
                             SelectionMode="None"    Margin="0, 10"  HeightRequest="220"  >
                              
                             .........
                          </CollectionView>    
                      </VerticalStackLayout>
                      <VerticalStackLayout IsVisible="{Binding HasRecentlyVisitedProducts}">
                          <Label   Text="{x:Static localization:AppResource.RecentlyViewed}"  FontAttributes="Bold" FontSize="14"></Label>
                          <CollectionView   ItemsSource="{Binding RecentlyVisitedProductList}" 
                             SelectionMode="None"    Margin="0,5"  HeightRequest="220"  >

                          ...........
                          </CollectionView>
                      </VerticalStackLayout>
                  </VerticalStackLayout>
          </CollectionView.Footer>
      </CollectionView>

**Comment by Zhanglirong-Winnie** [comment]
This is a .NET 7 maui performance issue, we verified it on .NET 8 maui with Visual Studio Enterprise 17.9.0 Preview 4. Can not repro on Android platforms with sample project. 
https://github.com/lucianparvu/MauiApp16.App.git
