### ISSUE TITLE
Placeholder font size not applied in editor on macOS and iOS

### ISSUE THREAD

**Issue by Shalini-Ashokan** [dotnet/maui#15750]
### Description

The placeholder text in the Maui editor is not being displayed with the correct font size on macOS and iOS platforms. This inconsistency affects the overall user experience and can lead to confusion when entering content in the editor

### Steps to Reproduce

1. Create a new Maui application.
2. Add an editor control to the content of the page.
3. Set the font size of the editor control to 50.
4. Specify a placeholder color for the editor control.
5. Run the application on an iOS or macOS platform.

### Link to public reproduction project repository

https://github.com/KarthikRajaAKR/Samples/tree/main/PlaceHolder

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

IOS 16.2, macOS 12.6.3

**Comment by jsuarezruiz** [comment]
Working on a fix here: https://github.com/dotnet/maui/tree/fix-15792

Fix Editor placeholder issues on iOS/Catalyst:
- Correct size.
- Apply character spacing etc correctly.

<img width="521" alt="Captura de pantalla 2023-06-27 a las 10 58 05" src="https://github.com/dotnet/maui/assets/6755973/5ab18d7f-2c5e-41a8-b58b-c734e507a7d1">

Added device tests and changes in the Editor sample page from the .NET MAUI Gallery (added samples using CharacterSpacing, Fonts etc).

<img width="371" alt="Captura de pantalla 2023-06-27 a las 10 47 09" src="https://github.com/dotnet/maui/assets/6755973/1d80ae9e-1a12-4cc2-a410-d6607136b8bf">
