### ISSUE TITLE
[regression/8.0.0-preview.5.8529] Cannot interact with RadioButton on iOS in a Popup

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#15760]
### Description

When putting `RadioButton`s in a toolkit Popup, I cannot interact with them on net8.0-ios. net8.0-android works fine. Other UI elements work fine, so this appears to be just `RadioButton` on net8.0-ios 

### Steps to Reproduce

Run this app with net8.0 on iOS, touch the button to launch the popup, and try to interact with the UI elements.

https://github.com/dotnet/maui/assets/41873/86531bab-fff0-4d21-90fe-7a84e741d237

### Link to public reproduction project repository

https://github.com/davidortinau/bug-radiobutton

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

7.0.49

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

**Comment by affableashish** [comment]
Are you guys thinking of doing better automated UI testing, so you avoid any regression bugs?

**Comment by davidortinau** [comment]
I've not been able to repro this outside of the community toolkit popup.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 4.0. Repro on iOS 16.4 .NET 8, not repro on Windows 11 and Android 13.0-API33 with below Project:
[bug-radiobutton.zip](https://github.com/dotnet/maui/files/12158114/bug-radiobutton.zip)

**Comment by inforithmics** [comment]
There is a similar Bug concerning the BindingContext in iOS and Popup.
https://github.com/CommunityToolkit/Maui/pull/1309
@PureWeen What do you mean by adding it as a logical Child.

**Comment by PureWeen** [comment]
> There is a similar Bug concerning the BindingContext in iOS and Popup. [CommunityToolkit/Maui#1309](https://github.com/CommunityToolkit/Maui/pull/1309) @PureWeen What do you mean by adding it as a logical Child.

A lot of the plumbing isn't connected up because it's been impossible to add `LogicalChildren` to the `Page` element. 

With the next .NET8 preview if `Popup` gets added to the `LogicalChildren` via https://github.com/dotnet/maui/pull/16046 that will fix the plumbing. 

I need to fix up gestures so they can work without that plumbing.

**Comment by jfversluis** [comment]
FYI we've released a fix in 5.3.0 of the .NET MAUI Community Toolkit for now, not sure if anything still needs to be done here for .NET MAUI.

**Comment by inforithmics** [comment]
https://github.com/inforithmics/TabGestureRecognizerBugOnPopupOniOS

```
 var popup = new ButtonPopup();
 this.AddLogicalChild(popup);
 this.ShowPopup(popup);
```

Still no Tapgesture on Popup, maybe I'm missing something

**Comment by inforithmics** [comment]
After some Debugging i found out that the Window is not set on the Radiobutton or Label And therefore the Gestures are not initialized.
After some more debugging, I found the problematic function in CommunityToolkit Maui.

Not Working CreatePage Handler

```
static PageHandler CreatePageHandler(IPopup virtualView)
{
	var mauiContext = virtualView.Handler?.MauiContext ?? throw new NullReferenceException(nameof(IMauiContext));
	var view = (View?)virtualView.Content ?? throw new InvalidOperationException($"{nameof(IPopup.Content)} can't be null here.");
	view.SetBinding(BindingContextProperty, new Binding { Source = virtualView, Path = BindingContextProperty.PropertyName });
	var contentPage = new ContentPage
	{
		Content = view,
	};
	
	return (PageHandler)contentPage.ToHandler(mauiContext);
}
```

Working CreatePageHandler

```
static PageHandler CreatePageHandler(IPopup virtualView)
{
	var mauiContext = virtualView.Handler?.MauiContext ?? throw new NullReferenceException(nameof(IMauiContext));
	var view = (View?)virtualView.Content ?? throw new InvalidOperationException($"{nameof(IPopup.Content)} can't be null here.");
	view.SetBinding(BindingContextProperty, new Binding { Source = virtualView, Path = BindingContextProperty.PropertyName });
	var contentPage = new ContentPage
	{
		Content = view,
	};

	if (virtualView.Parent is Element element)
	{
		contentPage.Parent = element;
	}
	
	return (PageHandler)contentPage.ToHandler(mauiContext);
}
```

**Comment by PureWeen** [comment]
if you change this
```C#
if (virtualView.Parent is Element element)
	{
		contentPage.Parent = element;
	}
```

to

```C#
if (virtualView.Parent is Element element)
	{
		element.AddLogicalChild(contentPage);
	}
```

Does that work too?

It should let you also delete this
```C#
view.SetBinding(BindingContextProperty, new Binding { Source = virtualView, Path = BindingContextProperty.PropertyName });
```

**Comment by inforithmics** [comment]
@PureWeen 

The Gestures are initialized with AddLogicalChild 

```
static PageHandler CreatePageHandler(IPopup virtualView)
		{
			var mauiContext = virtualView.Handler?.MauiContext ?? throw new NullReferenceException(nameof(IMauiContext));
			var view = (View?)virtualView.Content ?? throw new InvalidOperationException($"{nameof(IPopup.Content)} can't be null here.");
#if !NET8_0_OR_GREATER
			view.SetBinding(BindingContextProperty, new Binding { Source = virtualView, Path = BindingContextProperty.PropertyName });
#endif
			var contentPage = new ContentPage
			{
				Content = view,
			};

			if (virtualView.Parent is Element element)
			{
#if NET8_0_OR_GREATER
				element.AddLogicalChild(contentPage);
#else
				contentPage.Parent = element;
#endif
			}

			return (PageHandler)contentPage.ToHandler(mauiContext);
		}
```

How can I test if this is still needed.

`view.SetBinding(BindingContextProperty, new Binding { Source = virtualView, Path = BindingContextProperty.PropertyName });`

**Comment by inforithmics** [comment]
I tested it and the BindingContext is the same with `element.AddLogicalChild(contentPage); `as with 
`view.SetBinding(BindingContextProperty, new Binding { Source = virtualView, Path = BindingContextProperty.PropertyName });`

**Comment by PureWeen** [comment]
> I tested it and the BindingContext is the same with `element.AddLogicalChild(contentPage); `as with `view.SetBinding(BindingContextProperty, new Binding { Source = virtualView, Path = BindingContextProperty.PropertyName });`

Amazing!! Thank you for testing.

@pictos @jfversluis  FYI

**Comment by pictos** [comment]
@PureWeen, what version of .net maui is this available? I know that we pin our .net Maui version to the minimum possible, so probably the version that we're pinned doesn't have the `AddLogicalChild`

**Comment by PureWeen** [comment]
> @PureWeen, what version of .net maui is this available? I know that we pin our .net Maui version to the minimum possible, so probably the version that we're pinned doesn't have the `AddLogicalChild`

This is available in Preview7 of .NET8 so it'll be part of the first stable release of .NET8.

**Comment by inforithmics** [comment]
> > I tested it and the BindingContext is the same with `element.AddLogicalChild(contentPage); `as with `view.SetBinding(BindingContextProperty, new Binding { Source = virtualView, Path = BindingContextProperty.PropertyName });`
> 
> Amazing!! Thank you for testing.
> 
> @pictos @jfversluis FYI

I retested it, and 
`view.SetBinding(BindingContextProperty, new Binding { Source = virtualView, Path = BindingContextProperty.PropertyName });`
is still needed because AddlogicalChild only inherits the Parent BindingContext. When the BindingContext is set on the Popup
`view.SetBinding(BindingContextProperty, new Binding { Source = virtualView, Path = BindingContextProperty.PropertyName });`
is needed for binding it properly.
