### ISSUE TITLE
Compiling a simple, basic, barebones Maui Xaml file (App.xaml.cs located in Platform -> Windows folder) that uses a minimal custom IMarkupExtension Fails to Compile, giving the Error, XamlCompiler error WMC0015: Cannot assign 'StringResourceXamlMarkupExtension' into property 'Text', type must be assignable to 'String'

### ISSUE THREAD

**Issue by KCarterSr** [dotnet/maui#15775]
### Description

I'm getting the error, WMC0015: Cannot assign 'StringResourceXamlMarkupExtension' into property 'Text', type must be assignable to 'String', in a Maui project I'm working on. I have a Textblock in my App.xaml (Windows platform App.xaml) file with the Text property getting a String value from my markup extension. This same code works in other areas but not here.

So, I created a barebones test project with no other code in it to confirm (see github link to project). The same error occurs. 

Here is this simple code. Note: This is just a test project to trigger the error. The error will still happen in a project with more realistic and useful code.

APP.XAML

```xaml
<maui:MauiWinUIApplication
    x:Class="MarkupError.WinUI.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:maui="using:Microsoft.Maui"
    xmlns:local="using:MarkupError.WinUI">

<maui:MauiWinUIApplication.Resources>

<TextBlock x:Key="test" Text="{local:StringResourceXamlMarkupExtension Test=Hello}"/>

</maui:MauiWinUIApplication.Resources>
</maui:MauiWinUIApplication>
```

STRINGRESOURCEXAMLMARKUPEXTENSION.CS

```cs
namespace MarkupError.WinUI
{
 using System;

 public class StringResourceXamlMarkupExtension : IMarkupExtension<string>
 {
  private string test;

  public string Test
  {
      get => test;
      set => test = value;
  }

 object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
 {
  return (this as IMarkupExtension<string>).ProvideValue(serviceProvider);
 }

  public string ProvideValue(IServiceProvider serviceProvider)
  {
   return "test";
  }
 }
}
```

### Steps to Reproduce

1. Create a File -> new C# Maui App using .NET MAUI Template.

2. Create a markup extension that returns a string.

3. In the Windows App.xaml file create a resource item (DataTemplate, etc.)  that consumes the markup extension using something similar to `Text="{local:StringResourceXamlMarkupExtension Test=Hello}" `

That's all you have to do. The build will fail!

Here is my workload.

Installed Workload Id Manifest Version Installation Source
ios 16.2.2054/7.0.100 SDK 7.0.200, VS 17.5.33530.505
maccatalyst 16.2.2054/7.0.100 SDK 7.0.200, VS 17.5.33530.505
maui-android 7.0.81/7.0.100 VS 17.5.33530.505
android 33.0.46/7.0.100 VS 17.5.33530.505
wasm-tools 7.0.5/7.0.100 VS 17.5.33530.505
maui-windows 7.0.81/7.0.100 VS 17.5.33530.505
maui-maccatalyst 7.0.81/7.0.100 VS 17.5.33530.505
maui-ios 7.0.81/7.0.100 VS 17.5.33530.505

### Link to public reproduction project repository

https://github.com/KCarterSr/MarkupError

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

None

**Comment by drasticactions** [comment]
The error is correct, you're using the wrong interface in the wrong place.

https://github.com/KCarterSr/MarkupError/blob/76f0444d14d1e7ac952cc91fd5f91268603ea0f5/MarkupError/Platforms/Windows/StringResourceXamlMarkupExtension.cs#L5

`IMarkupExtension<string>` (or `IMarkupExtension<out T>`) and `IMarkupDocument` is [a MAUI interface](https://learn.microsoft.com/en-us/dotnet/maui/xaml/markup-extensions/create), not a WinUI one. You're trying to use this inside of WinUI, which won't work. 

https://github.com/drasticactions/MauiRepros/tree/main/MarkupError

I wrote an example of this working correctly. If you use it within MAUI, it's fine.

**Comment by mattleibow** [comment]
I think @drasticactions is saying you are using the wrong type. Did you check his changes? It also has WinUI things.

**Comment by KCarterSr** [comment]
@mattleibow 

Oh, I'll check it out.
Thanks

**Comment by KCarterSr** [comment]
@mattleibow

Thanks for the clarification. I totally missed that. I changed inheritance from IMarkupExtension to MarkupExtension. Good now.
