### ISSUE TITLE
Android binding project error on build step class-parse: Unable to read file

### ISSUE THREAD

**Issue by pierre-galaup** [dotnet/maui#15771]
### Description

Hello,

I am in the process of migrating my app from XAMARIN FORMS to MAUI.

I'm using the PORTSIP library to make VOIP and I'm transforming my XAMARIN binding project into a MAUI binding.

However, I have a problem: on some MACs (or on the DEVOPS CI), I get an error on the ANDROID binding.

`class-parse: Unable to read file '{0}': Unknown file format.`

`(_ExportJarToXml target) -> /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Bindings.ClassParse.targets(35,5): error MSB6006: "dotnet" exited with code 1. `

I'm attaching a log I made on a MAC that works and one that doesn't.
The log was made with the command: `dotnet build -c Release --verbosity diagnostic >> working.txt`

Log of a working MAC: [working.txt](https://github.com/dotnet/maui/files/11815617/working.txt)
Log of a MAC that doesn't work: [notworking.txt](https://github.com/dotnet/maui/files/11815615/notworking.txt)

My csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net7.0-android33.0</TargetFramework>
        <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsBindingProject>true</IsBindingProject>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>PortSip.Droid</RootNamespace>
        <AssemblyName>PortSip.Android</AssemblyName>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <OutputPath>bin\Debug\</OutputPath>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
        <AndroidLinkMode>None</AndroidLinkMode>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <DebugType>portable</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\Release\</OutputPath>
        <DefineConstants>TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
        <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
        <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedNativeLibrary Include="lib\armeabi-v7a\libportsip_core.so" />
        <EmbeddedNativeLibrary Include="lib\armeabi-v7a\libportsip_media.so" />
        <EmbeddedNativeLibrary Include="lib\x86\libportsip_core.so" />
        <EmbeddedNativeLibrary Include="lib\x86\libportsip_media.so" />
        <EmbeddedNativeLibrary Include="lib\arm64-v8a\libportsip_core.so" />
        <EmbeddedNativeLibrary Include="lib\arm64-v8a\libportsip_media.so" />
        <EmbeddedNativeLibrary Include="lib\x86_64\libportsip_core.so" />
        <EmbeddedNativeLibrary Include="lib\x86_64\libportsip_media.so" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PortSip\PortSip.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AndroidLibrary Include="portsipvoipsdk.jar" />
    </ItemGroup>
</Project>
```

### Steps to Reproduce

I can't give my code because the licenses are directly in the JAR I'm trying to bind.

But I have an Android binding project, and I'm adding the libraries .so and the .jar (see the csproj file above).
I compile (on my MAC or on the Devops CI) and I get the error.
But on some MACs, I don't get the error and everything works fine.

### Link to public reproduction project repository

https://www.portsip.com/download-portsip-voip-sdk/

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android binding library

### Did you find any workaround?

No workaround

### Relevant log output

```shell
Task Parameter:ToolExe=class-parse.dll (TaskId:213)
                     Using: /usr/local/share/dotnet/dotnet /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/class-parse.dll (TaskId:213)
                     [class-parse] response file: obj/Release/net7.0-android33.0/class-parse.rsp (TaskId:213)
                     --o="obj/Release/net7.0-android33.0/api.xml.class-parse" (TaskId:213)
                     "portsipvoipsdk.jar" (TaskId:213)
                     /usr/local/share/dotnet/dotnet /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/class-parse.dll "@obj/Release/net7.0-android33.0/class-parse.rsp"  (TaskId:213)
                     class-parse: Unable to read file '{0}': Unknown file format. (TaskId:213)
```

**Comment by Eilon** [comment]
Paging @jonathanpeppers

**Comment by jpobst** [comment]
It would appear that the `portsipvoipsdk.jar` isn't a valid zip file.

Here is the check that is looking at that:
https://github.com/xamarin/java.interop/blob/release/7.0.2xx/tools/class-parse/Program.cs#L99-L115

**Comment by pierre-galaup** [comment]
Hello,

I checked the JAR files and they were indeed different.

However, I can't explain how on a MAC and DEVOPS they are different from another MAC when all 3 are based on exactly the same GIT and the same branch.

I pushed the right JAR from the MAC that had an error and since then everything works.

Thank you very much.
