### ISSUE TITLE
iOS: Splash Screen Logo Scaling Issue in MAUI Apps

### ISSUE THREAD

**Issue by kubaflo** [dotnet/maui#15782]
### Description

When using the properties Resize="True" and setting the size in BaseSize, the logo on the splash screen is not scaling correctly even in new projects. The issue persists even after ensuring that the latest MAUI SDK is installed and attempting various troubleshooting steps. It, however, works when using sample apps inside https://github.com/dotnet/maui

Expected Behavior:
The splash screen logo should scale properly according to the specified  BaseSize.

### Steps to Reproduce

1. Create a new MAUI app project or open an existing MAUI app.
2. Configure the splash screen logo by setting Rebase="True" and for example BaseSize="10,10" properties.
3. Build and launch the app.

### Link to public reproduction project repository

https://github.com/kubaflo/MauiSplashResize

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Relevant log output

```shell
I have tested the issue in multiple MAUI apps and encountered the same problem consistently.
I have verified that the latest MAUI SDK is installed and up to date.
The bug does not occur when using projects from the latest MAUI repository, suggesting that it may have already been fixed.
```

**Comment by mattleibow** [comment]
Is this a png or svg? Do you mean Resize or Rebase? Can you attach a repo so I can have a look?

**Comment by kubaflo** [comment]
Hi, @mattleibow it happens for both png and svg. I added a repo so that you can check on your own. I meant Resize, not Rebase (I fixed my typo in the description). Thanks!

**Comment by kubaflo** [comment]
@mattleibow here's the repo: https://github.com/kubaflo/MauiSplashResize

Feel free to contact me if you need more details :)

**Comment by satyam16998** [comment]
I am also facing the same issue for both ios and Android. The image is not resizing after changing the base size.

**Comment by MAUIoxo** [comment]
With such small SVG images it really looks ridiculous - why not allow full screen images and why ignore different base sizes?

**Comment by CameronVetter** [comment]
Any progress on this?  I've got the same issue and it appeared after a workload update.  I'm currently on 7.0.92/7.0.100

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 4. Can repro on iOS platforms with sample project.
https://github.com/kubaflo/MauiSplashResize

**Comment by jfversluis** [comment]
@kubaflo can you confirm this is still an issue with recent .NET MAUI versions?

**Comment by kubaflo** [comment]
I forgot about this bug haha. It works for me in NET 8
