### ISSUE TITLE
navHost cannot be null after app2app

### ISSUE THREAD

**Issue by tkern46** [dotnet/maui#15788]
### Description

I noticed an **InvalidOperationException (NavHost cannot be null)** after app-to-app-communication via intents.
To reproduce this bug I have created 2 App (LoginApp and CallingApp). The **LoginApp** called via intent out of **CallingApp**. To simulate the login-process, the LoginApp waits for 2 seconds and finishes the intent. When the intent is finished and you go back into the LoginApp, the LoginApp crashes because the navHost is null.
It did not crash using Xamarin with dotnet 2.1.

### Steps to Reproduce

1. Start LoginApp
2. Start CallingApp
3. Wait until LoginView disappears and "Hello from CallingApp!" is displayed
4. Open still running LoginApp => InvaldiOperationException pops up

### Link to public reproduction project repository

https://github.com/tkern46/navhost-connot-be-null-after-app2app.git

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 29

### Relevant log output

```shell
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: NavHost cannot be null
[mono-rt] at Microsoft.Maui.Platform.StackNavigationManager.get_NavHost() in D:\a_work\1\s\src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs:line 32
[mono-rt] at Microsoft.Maui.Platform.NavigationViewFragment.OnResume() in D:\a_work\1\s\src\Core\src\Platform\Android\Navigation\NavigationViewFragment.cs:line 75
[mono-rt] at AndroidX.Fragment.App.Fragment.n_OnResume(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/generated/androidx.fragment.fragment/obj/Release/net6.0-android/generated/src/AndroidX.Fragment.App.Fragment.cs:line 2614
[mono-rt] at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
[mono-rt] at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12320
[mono-rt] at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
[mono-rt] at Android.App.Activity.OnPostResume() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.App.Activity.cs:line 4296
[mono-rt] at Microsoft.Maui.MauiAppCompatActivity.OnPostResume() in D:\a_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.Lifecycle.cs:line 66
[mono-rt] at Android.App.Activity.n_OnPostResume(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.App.Activity.cs:line 4286
[mono-rt] at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

**Comment by mattleibow** [comment]
@PureWeen thoughts?

**Comment by tkern46** [comment]
Hi, the exception still occures with the latest releases. We've tried it with Visual Studio Preview 17.7.0 Preview 2.0 and the .net8 preview.

**Comment by markusroessler** [comment]
note this exception doesn't occur, if you create a custom Window in App.xaml.cs.CreateWindow() and set the MainPage in this Window instead of the App.
However this leads to a memory leak instead: https://github.com/dotnet/maui/issues/15972

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Can repro on android platform with sample project.
[navhost.zip](https://github.com/dotnet/maui/files/13807319/navhost.zip)
![image](https://github.com/dotnet/maui/assets/77434865/98d6de91-b3ac-4835-8183-cff8de49d61f)

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds
