### ISSUE TITLE
Label wordwrap does not honor container MaxWidth

### ISSUE THREAD

**Issue by zwikk** [dotnet/maui#15785]
### Description

PR #15022 fixes MaxRequestWidth and MaxRequestHeight and works mostly great! However, it seems a Label with WordWrap inside a container such as a Grid with MaximumWidthRequest, does not play along.

### Steps to Reproduce

Consider the following XAML:

```xaml
<Grid BackgroundColor="LightBlue" MaximumWidthRequest="600" Padding="10">
  <Label FontSize="20" 
         Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sodales eros nec massa facilisis venenatis. Sed fermentum porta diam eu pulvinar. Cras ornare ligula id finibus tincidunt. Sed sagittis aliquam neque sit amet commodo. Sed eget velit tortor. Nam ac fringilla leo, sit amet egestas quam. Praesent finibus sem ac nisi elementum sollicitudin. "
         LineBreakMode="WordWrap" />
</Grid>
```

On iOS (and MacOS) in portrait this looks fine (enforced by device width):

![Simulator Screenshot - iPhone 14 - 2023-06-21 at 15 26 30](https://github.com/dotnet/maui/assets/123168199/5115c0cc-412a-45c4-9a34-36207b653136)

In landscape things fall apart:

![Simulator Screenshot - iPhone 14 - 2023-06-21 at 15 26 33](https://github.com/dotnet/maui/assets/123168199/f89b7a1f-4bf8-4b82-9576-91d455f0a613)

On Android the behavior is exactly the opposite. Portrait mode doesn't look great:

![Screenshot_1687420702](https://github.com/dotnet/maui/assets/123168199/dbec8671-ea67-44a5-b270-8e6f5a32d83c)

Landscape mode is fine:

![Screenshot_1687420709](https://github.com/dotnet/maui/assets/123168199/61bac42b-ea59-48ea-8d87-4ea60f8a7ab3)

### Link to public reproduction project repository

https://github.com/zwikk/maui-playground/tree/main/Source/MauiNet8Test

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16, Android, MacOS

**Comment by mattleibow** [comment]
@hartez  thoughts?

**Comment by jfversluis** [comment]
Since @jknaudt21 did the PR that is referenced maybe?
