### ISSUE TITLE
Editor Placeholder displays incorrectly on iOS

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#15792]
### Description

Comparing Android and iOS, the placeholder is being cutoff on iOS.

<img width="789" alt="Screenshot 2023-06-21 at 3 18 10 PM" src="https://github.com/dotnet/maui/assets/41873/0eb4de6e-8edc-40f5-a166-ae7bcc136c90">

### Steps to Reproduce

Add editor and placeholder text and run it on iOS. Compare to Android.

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

16.4

**Comment by jsuarezruiz** [comment]
Working on a fix here: https://github.com/dotnet/maui/tree/fix-15792

Fix Editor placeholder issues on iOS/Catalyst:
- Correct size.
- Apply character spacing etc correctly.

<img width="521" alt="Captura de pantalla 2023-06-27 a las 10 58 05" src="https://github.com/dotnet/maui/assets/6755973/5ab18d7f-2c5e-41a8-b58b-c734e507a7d1">

Added device tests and changes in the Editor sample page from the .NET MAUI Gallery (added samples using CharacterSpacing, Fonts etc).

<img width="371" alt="Captura de pantalla 2023-06-27 a las 10 47 09" src="https://github.com/dotnet/maui/assets/6755973/1d80ae9e-1a12-4cc2-a410-d6607136b8bf">
