### ISSUE TITLE
RadioButton border doesn't work on Android

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#15795]
### Description

Low priority, but I noticed border color doesn't work on Android the same as iOS.

<img width="778" alt="Screenshot 2023-06-22 at 10 25 49 AM" src="https://github.com/dotnet/maui/assets/41873/cb8e190e-87e1-44ff-a1b7-32fc479ebe7c">

Project:
[Archive.zip](https://github.com/dotnet/maui/files/11835699/Archive.zip)

### Steps to Reproduce

Run it

### Link to public reproduction project repository

see project attached

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

8.0.0-preview.5.8529

### Affected platforms

Android

### Affected platform versions

33

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. Repro on Android 13.0-API33 .NET 8, not repro on Windows 11 and iOS 16.4 with below Project:
[Archive.zip](https://github.com/dotnet/maui/files/12169976/Archive.zip)

**Comment by vishnumenon2684** [comment]
Hey @davidortinau ,

By Using the BorderWidth property we can resolve this issue.

**Comment by vishnumenon2684** [comment]
Hi @davidortinau ,

We have found that the default value of the border width is set as -1 for the radio button.
It has been overridden in the windows.
It seems like the behaviour of android seems to be the correct one.
Without the border width we shouldn't draw the border right?

**Comment by ParzLaboratory** [comment]
Hi , did anyone find solution for this ?

**Comment by ParzLaboratory** [comment]
@davidortinau / @vishnumenon2684  Did any of you guys find the solution ?

**Comment by EwaldJebaraj7** [comment]
Workaround - This will changed the Radiobutton border color

`Microsoft.Maui.Handlers.RadioButtonHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
            {
#if ANDROID
                if (handler.PlatformView is Android.Widget.RadioButton radioButton)
                {
                    var states = new int[][]
                    {
                        new int[] { Android.Resource.Attribute.StateChecked }, 
                        new int[] { -Android.Resource.Attribute.StateChecked }  
                    };

                    // Define the colors corresponding to the states (border color)
                    var colors = new int[]
                    {
                        Android.Graphics.Color.Orange,    
                        Android.Graphics.Color.Orange    
                    };

                    // Create a ColorStateList with the states and colors
                    var colorStateList = new Android.Content.Res.ColorStateList(states, colors);

                    // Apply the color tint to the button's border
                    radioButton.ButtonTintList = colorStateList;
                }
#endif
            });`

**Comment by jfversluis** [comment]
Seeing that Frame is officially deprecated as of .NET 9, I don't think we will be working on this anymore. Also its a bit older by now, so maybe its even resolved in current versions 🤞
