### ISSUE TITLE
[Bug] Not having WebView2 Runtime installed create unhelpful error

### ISSUE THREAD

**Issue by john681611** [dotnet/maui#1579]
### Description
Attempting to run a released Blazor Winforms app on a machine that does not have WebView2 Runtime installed produces an unhelpful error.
### Steps to Reproduce

1.  Create Forms app using Microsoft.AspNetCore.Components.WebView.WindowsForms and Blazor UI
2.  Publish Version of app
3.  Try running release version on machine without WebView2 Runtime installed 

### Expected Behavior
Pop Up asking to install runtime or even better runtime installed as part of  `SelfContained` build attribute
### Actual Behavior
Receive Popup with an error message
```
************** Exception Text **************
System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)

************** Loaded Assemblies **************
System.Private.CoreLib
Assembly Version: 6.0.0.0
Win32 Version: n/a
CodeBase:
...
```

### Basic Information

- Version with issue: 6.0.0-preview.4.21253.5
- Last known good version: N/A
- IDE: VS code
- Platform Target Frameworks: win-x64
- Nuget Packages: Microsoft.AspNetCore.Components.WebView.WindowsForms 6.0.0-preview.4.21253.5
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/10814889/124914217-fffad480-dfe7-11eb-9319-42305a868bed.png)

### Workaround

Ask people to install runtime...

**Comment by VincentBu** [comment]
@john681611 is there any sample for repro? I didn't see any link under **Reproduction Link**.

**Comment by john681611** [comment]
I don't have a specific repo but this is usable if you run up ASMDesktop
https://github.com/john681611/ArmaServerManager

**Comment by VincentBu** [comment]
> I don't have a specific repo but this is usable if you run up ASMDesktop https://github.com/john681611/ArmaServerManager

Well, sorry, I just realize all my machines are newer than Windows 10 21H2 and WebView 2 is installed by default as a programming component, which can't be uninstalled.

**Comment by john681611** [comment]
Fair enough my projects are often run on peoples servers running older OS's so I guess I saw it when others didn't
