### ISSUE TITLE
DatePicker Focused color not applied after date selection

### ISSUE THREAD

**Issue by Kerubananthan3761** [dotnet/maui#15805]
### Description

In Maui DatePicker while customizing date picker style using Visual State, the focused color of date picker is not applied  for the Focused Visual State.
[DatePickerSample.zip](https://github.com/dotnet/maui/files/11843832/DatePickerSample.zip)

### Steps to Reproduce

1. Create a file > .Net Maui App
2. Add ContentPage.Resources in MainPage.Xaml
3. Add Style to ContentPage.Resources
4. Add Setter Property="VisualStateManager.VisualStateGroups" to style
5. Add Visual state Group list to VisualStateManager with Normal and Focused state
6. Add DatePicker to ContentPage
7. Set StaticResource to DatePicker style property and bind with ContentPage.Resources  specifed Key
8. Run the sample 
9. The DatePicker Background and text color is applied as in Normal Visual state
10. Pick any date in picker, the color not applied as in Focused state

### Link to public reproduction project repository

[DatePickerSample.zip](https://github.com/dotnet/maui/files/11843832/DatePickerSample.zip)

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

**Comment by PureWeen** [comment]
@Kerubananthan3761 can you push your repro to a github repository please?
