### ISSUE TITLE
Picker selected item text color changes on mouse hover

### ISSUE THREAD

**Issue by Kerubananthan3761** [dotnet/maui#15804]
### Description

In Maui Picker while customizing picker style using Visual State, the text color of selected item in picker changes on initial selection and it changes once mouse pointer is hovered above picker for Normal visual state. When the visual state is focused the picker customization is not applied.

[PickerSample.zip](https://github.com/dotnet/maui/files/11843787/PickerSample.zip)

### Steps to Reproduce

1. Create a file > .Net Maui App
2. Add ContentPage.Resources in MainPage.Xaml
3. Add Style to  ContentPage.Resources
4. Add Setter Property="VisualStateManager.VisualStateGroups" to style
5. Add Visual state Group list to VisualStateManager with Normal and Focused state
6. Add Picker to ContentPage
7. Set StaticResource Picker style property and bind with ContentPage.Resources specifed Key
8. Run the sample and Select any item in picker
9. Hover the mouse above picker

### Link to public reproduction project repository

[PickerSample.zip](https://github.com/dotnet/maui/files/11843787/PickerSample.zip)

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

**Comment by PureWeen** [comment]
Can you please push your repro to a github repository?
