### ISSUE TITLE
Strange file picker behavior when using BlazorWebView

### ISSUE THREAD

**Issue by Take-A-Byte** [dotnet/maui#15812]
### Description

When I try to open a web file picker from a XAML button, it opens up without any issues the first time, but when I try to click it again, I get a warning that the file picker should only be invoked by a user.

## Introduction to the sample repository
I have created an input control in HTML and want to invoke a file picker from the web to refrain from sending data from native to the web as it makes the reading of files slower.

I have hidden this input control and created a custom button in Razor page as well as Xaml named "Open from Blazor" and "Open from XAML" respectively.

### Steps to Reproduce

1. Run the MAUI project
2. Click on the "Open from XAML" button
   - This will open a file picker and once you pick a file, you will see an alert.
3. Click on "Open from XAML" button again
   - This time, nothing happens. But, if you open the dev tools, you would see a warning that file picker can only be shown with a user activation

4. Click on the "Open from Blazor" button any number of time, it opens the file picker and gives an alert after file is picked.

### Link to public reproduction project repository

https://github.com/Take-A-Byte/StrangeFilePickerBehviorInMauiBlazorApp/blob/master

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

No

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Can repro on windows platform with sample project.
[StrangeFilePicker.zip](https://github.com/dotnet/maui/files/13807200/StrangeFilePicker.zip)

**Comment by Eilon** [comment]
Hi, I think this behavior is standard WebView behavior that exists for security reasons. It's to prevent script code from maliciously activating UI without user interaction.

I'm not sure why it's only happening _sometimes_, though, but that's up to the native WebView control to decide. For Windows we use the [Edge WebView2](https://github.com/MicrosoftEdge/WebView2Feedback/issues) control, so if you feel there's an issue with that control, please consider filing an issue there.
