### ISSUE TITLE
CollectionView with non integer height request has atrocious scroll performance

### ISSUE THREAD

**Issue by Hooterr** [dotnet/maui#15814]
### Description

When you put a height request on collection view (which you have to do due to current bugs), if it contains a decimal part the scrolling performance will be atrocious. This performance scales linearly with the number of items, not their complexity. Above 2000 it's unusable (if usable means above 10fps).

Also on the video the columns are bugged as well, but I've seen this bug so many times in this repo that I'm not even commenting on that.

https://github.com/dotnet/maui/assets/28758721/d223f5da-5a6d-4819-acb9-4b9ddd156e01

### Steps to Reproduce

1. Set height request on a collection view to something that has a decimal part e.g. 600.5;

### Link to public reproduction project repository

https://github.com/Hooterr/CollectionViewHeightRequestBug

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4, but probably all of them

### Did you find any workaround?

Cast height request to int always.

**Comment by PureWeen** [comment]
Do you get the same atrocious performance in released mode?

**Comment by Hooterr** [comment]
Yup, there as well too. 
Sorry for the tone, but I've spent over 10 hours trying to figure out what was wrong just to discover such a ridiculous bug.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. Repro on iOS 16.4 .NET 8, not repro on Windows 11 and Android 13.0-API33 with below Project:
[CollectionViewHeightRequestBug.zip](https://github.com/dotnet/maui/files/12181096/CollectionViewHeightRequestBug.zip)

**Comment by jsuarezruiz** [comment]
@Hooterr Could you try again with SR3?

**Comment by MitchBomcanhao** [comment]
there were already similar (unaddressed) bugs raised against xamarin forms, https://github.com/xamarin/Xamarin.Forms/issues/15426, so I'm guessing that any such issues will still be happening on maui across the board.

**Comment by rmarinho** [comment]
I test this and wasn't able to reproduce. Please reopen if this is a still issue with an updated repo. 

Thanks
