### ISSUE TITLE
iOS: CollectionView - Horizontal CollectionView does not show the last element under some conditions

### ISSUE THREAD

**Issue by unombun** [dotnet/maui#15815]
### Description

If in a horizontal CollectionView (iOS) we have first items ( quite few of them so not to fill the screen -> need to scroll) with the same Width (let's call it XWidth) and  the last 2 items have Width = 2* XWidth, then the last Item is not rendered at all (it is not shown as it would not be in the collection view).

If the Width of the last 2 items are different from 2*XWidth, the items are rendered properly.
Also if in the first items there is a item with a different Width, the 2 last items are again shown properly.

| | |
|:-:|:-:|
|![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-23 at 14 24 59](https://github.com/dotnet/maui/assets/11754566/44e92d23-f997-4052-b6d6-efba0159fd99)|![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-23 at 14 25 07](https://github.com/dotnet/maui/assets/11754566/dc87333d-7476-4058-982a-4eb8dd01c128)|

### Steps to Reproduce

1. Create MAUI App - iOS
2. Add a horizontal CollectionView
3. The ItemsSource of CollectionView should have items that have the same width (enough items so the user needs to scroll)
4. The last 2 items of ItemsSource should have the width equal to double of the regular items.
5. From the last 2 items only the first one is rendered. The last one from the ItemsSource is not displayed at all.

### Link to public reproduction project repository

https://github.com/flesarradu/iOSHorizontalCollectionViewItemsIssueMaui

### Version with bug

7.0.81

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by drasticactions** [comment]
This could be worth trying in net8.0 to see if https://github.com/dotnet/maui/pull/14951 addresses it?

**Comment by BenBtg** [comment]
I have been able to repro this issue on iOS with .NET 7 and .NET8 preview.5.8529.
Last item is missing if they are an exact multiple of the first item. 
I have found that changing the width of either item by 1 pixel seems to workaround the issue but don't think this is an acceptable workaround.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. Repro on iOS 16.4 .NET 8, not repo on Windows 11 and Android 13.0-API33 with below Project:
[NewMauiApp.zip](https://github.com/dotnet/maui/files/12181271/NewMauiApp.zip)

**Comment by jknaudt21** [comment]
This still repros in main and seems to be particularly gnarly. If the window is resized on macCatalyst, some of the items won't appear in the CollectionView where everything should be visible, yet scrolling back and forth "fixes" it. The "broken" CV, however, always remains broken. 


https://github.com/dotnet/maui/assets/32918747/2cc0ef45-1f50-48d5-8d7f-e822f1413c27

**Comment by Redth** [comment]
Still repros here in .NET 8 nightlies (8.0.4-nightly.9725)

**Comment by PureWeen** [comment]
Possibly related

https://github.com/dotnet/maui/issues/19240

**Comment by roughiain** [comment]
Ran into this in vertical Collection view today

**Comment by rmarinho** [comment]
@roughiain  do you have a repo for vertical ?
