### ISSUE TITLE
Screen is partially scrolled and hidden when showing the virtual keyboard

### ISSUE THREAD

**Issue by harveytriana** [dotnet/maui#15838]
### Description

When you give focus to an Entry control the virtual keyboard is displayed, but the top of the screen is apparently displaced and doesn't look complete. I report it as an ISSUE because the same does not happen in MAUI .NET 6. To give a better explanation, I have put a Solution in Git with the two projects in 6 and 7: https://github.com/harveytriana/MauiKeyboardIssues

The Xaml and C# are exactly the same. Except that the correction was added for 7 about the Completed event of the Entry control which is not fired by the ENTER key (another 7 issue).

### Steps to Reproduce

Unexpected behavior in .NET MAUI 7

### Link to public reproduction project repository

https://github.com/harveytriana/MauiKeyboardIssues

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android X

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. Repro on Android 13.0-API33 and iOS 16.4 .NET 8 with below Project:
[15838.zip](https://github.com/dotnet/maui/files/12191946/15838.zip)
Android:
![MessageAndroid](https://github.com/dotnet/maui/assets/97647558/c8268d3e-bcc8-4f42-b496-b7ea27e26979)
iOS: 
![MessageiOS](https://github.com/dotnet/maui/assets/97647558/606acfe3-33cd-40b4-a561-ceab7718e1bb)

**Comment by PureWeen** [comment]
@harveytriana This feature wasn't wired up correctly in NET6

You can try toggling it to see if it adjusts back to what you're wanting/expecting
https://learn.microsoft.com/en-us/dotnet/maui/android/platform-specifics/soft-keyboard-input-mode
