### ISSUE TITLE
[MAUI with .NET 8] Can't run on Android/iOS

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/maui#15849]
### Description

In latest VS (17.7.0 Preview 2) and .NET 8 (Preview 5), a MAUI project

(1) can’t Compile on Android/iOS. Error:
Error APT2260 resource mipmap/appicon (aka com.xy.fa:mipmap/appicon) not found.
Error APT2260 resource mipmap/appicon_round (aka com.xy.fa:mipmap/appicon_round) not found.
Error APT2067 failed processing manifest.

(2) the .csproj file can’t be opened in VS GUI to modify the content. Error:
System.ArgumentException: Expected 6 values for property IOSRule::MtouchSdkVersion, but got 2.

These problems exist since .NET 8. Please investigate the issues. Thanks.

### Steps to Reproduce

1. Create a MAUI app with .NET 8 in Visual Studio.
2. Try to open the .csproj file, error shows.
3. Try to compile app on Android/iOS, error shows.

### Link to public reproduction project repository

https://github.com/SunshineSpring666/MaApp.git

### Version with bug

8.0.0-preview.1.7762

### Last version that worked well

7.0.86

### Affected platforms

iOS, Android

### Affected platform versions

.NET 8, Android 12+

### Did you find any workaround?

No workaround. 
Currently, there are bugs preventing MAUI app to run with .NET 8 on Android/iOS.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. This issue does not repro on Android 13.0-API33 and iOS 16.4(8.0.100-preview.6.23330.14) with below Project:
[MaApp.zip](https://github.com/dotnet/maui/files/12192355/MaApp.zip)

Compile successfully on iOS and Android:
![image](https://github.com/dotnet/maui/assets/97647558/f2cd8217-8997-4b4a-b674-e16815f2d5f7)
![image](https://github.com/dotnet/maui/assets/97647558/70b62bba-37d2-4224-9476-aa9d6834ce74)

**Comment by ewerspej** [comment]
I experience this issue with the latest version (8.0.100-preview.7.23376.3) while trying to check if issue #16816 has been fixed already in the latest preview.
