### ISSUE TITLE
FlyoutPage: Scrolling is not working in the Detail page on iOS Tablets when setting the flyout behavior to Split. 

### ISSUE THREAD

**Issue by Jean-RochSDX** [dotnet/maui#15876]
### Description

ScrollView in the Detail Page of a FlyoutPage is not working on iOS Tablets when setting the flyout behavior to Split.

Scrolling is working on Windows and Android.

On Xamarin scrolling in the detail page with the flyout behavior set to Split was working for the three platforms (Windows, Android, iOS) 

### Steps to Reproduce

Open the solution FlyoutPageSample.sln in the MAUI folder
Run App on a iOS Tablet
Select the TodoList menu item.
Try to scroll text => scrolling is not working.

Scrolling is working when reproducing the previous steps with Android tablets and Windows.
Scrolling is working when reproducing the previous steps with Android tablets, Windows AND iOS tablets when using the solution FlyoutPageNavigation.sln located in the Xamarin folder.

### Link to public reproduction project repository

https://github.com/Jean-RochSDX/FlyoutScrollBugMaui

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

No

**Comment by Jean-RochSDX** [comment]
Hi, as recommended I tested with the preview version and the bug is still there. Here the build environment configuration:

Visual studio:
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.7.0 Preview 2.0

dotnet --version
7.0.400-preview.23274.1

dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
----------------------------------------------------------------------------------------------
ios                        16.4.7067/7.0.100      SDK 7.0.400-preview.23274, VS 17.7.33808.371
maui-ios                   7.0.86/7.0.100         SDK 7.0.400-preview.23274, VS 17.7.33808.371
runtimes-windows           7.0.8/7.0.100          VS 17.7.33808.371
maui-windows               7.0.86/7.0.100         VS 17.7.33808.371
maui-maccatalyst           7.0.86/7.0.100         VS 17.7.33808.371
maccatalyst                16.4.7067/7.0.100      VS 17.7.33808.371
maui-android               7.0.86/7.0.100         VS 17.7.33808.371
android                    33.0.68/7.0.100        VS 17.7.33808.371

**Comment by PureWeen** [comment]
@Jean-RochSDX can you test with .NET 8?

**Comment by Jean-RochSDX** [comment]
It works on .NET 8. Thank you for your time.
