### ISSUE TITLE
[regression/8.0-preview5] Entry not working when keyboard is numeric and os language is not english

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#15884]
### Description

On Android, using net8-pre5, Entry control is not working when Keyboard is Numeric and OS language is not english.
Both in Debug and Release mode.
This was working in net7.

### Steps to Reproduce

1. Create a Maui app for Android using net8-pre5
2. In XAML, add an Entry and set Keyboard to Numeric
3. Change OS language to any non-english language (for example, French)
4. Run app, tap on the entry, it's impossible to enter a value.

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppKeyboardNumeric

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

7.0.86

### Affected platforms

Android

### Affected platform versions

Android 33

### Did you find any workaround?

No workaround

**Comment by MarMarIV** [comment]
It will be in next preview? With this bug, app for invoicing is unussable, without 'numeric entry'
