### ISSUE TITLE
XamlC error XFC0000 : Cannot resolve type "Application".

### ISSUE THREAD

**Issue by psudodev** [dotnet/maui#15904]
### Description

Adding Rg.Plugins.Popup to Maui Project fails to build solution

### Steps to Reproduce

Create a Blank Maui Project

Add Rg.Plugins.Popup inside your project

Clean and Build

The Project fails to build

Severity	Code	Description	Project	File	Line	Suppression State
Error		 : XamlC error XFC0000 : Cannot resolve type "Application".	MauiSample	

### Link to public reproduction project repository

https://github.com/psudodev/MauiRgPopupPluginSample

### Version with bug

7.0.86

### Last version that worked well

6.0

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

30

### Did you find any workaround?

NA

### Relevant log output

```shell
Build started...
1>------ Build started: Project: MauiSample, Configuration: Debug Any CPU ------
1>App.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "Application".
1>AppShell.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "Shell".
1>MainPage.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "ContentPage".
1>Resources\Styles\Colors.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "ResourceDictionary".
1>Resources\Styles\Styles.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "ResourceDictionary".
1>Done building project "MauiSample.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 6:05 AM and took 03.325 seconds ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Deploy started at 6:05 AM and took 03.325 seconds ==========
```

**Comment by greg84** [comment]
This is not a defect in MAUI. The Rg.Plugins.Popup plugin is not MAUI compatible (see [this issue](https://github.com/rotorgames/Rg.Plugins.Popup/issues/684) for details).

The Mopups plugin is the replacement for Rg.Popups with MAUI compatibility: https://github.com/LuckyDucko/Mopups

**Comment by psudodev** [comment]
Thanks I could use Mopups as a Replacement for Rg,Plugin.Popups
