### ISSUE TITLE
`CarouselView` on `Windows` doesn't update `SelectedItem`

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#15900]
### Description

Running my maui project on Windows, I'm not able to select `Items` from my `CarouselView`.
Android and iOS are working fine with the same project code.

![image](https://github.com/dotnet/maui/assets/2952443/2ee1f689-e8d6-4be4-aa39-c1b2b984441d)

I can see and scroll the items, however when I try to click one to select it, nothing happens.
Same on `net8 P5`

### Steps to Reproduce

1. Download and run the project from the repro uri
2. Go to `ViewModels\PageViewModel.cs`
3. Set a breaking point at `partial void OnSelectedColorChanged(ThemeColorInfo value)`
4. Run the project on windows and try to select a color.
5. The `Button.BackgroundColor` should be set to the selected color and the breaking point should be hit

### Link to public reproduction project repository

https://github.com/AndreasReitberger/MauiCarouselViewIssueWinUI

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

Not yet

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). This issue does not repro on Windows 11, Android 14.0-API34, iOS 17.0 and MacCatalyst with below Project:
[MauiApp_CarouselViewIssue.zip](https://github.com/dotnet/maui/files/13498215/MauiApp_CarouselViewIssue.zip)
![Scroll](https://github.com/dotnet/maui/assets/97647558/367a0176-9136-451b-8444-9248c8b676d1)

**Comment by AndreasReitberger** [comment]
Fixed in `8.0.3`, thank you!
