### ISSUE TITLE
Grid Columns Affecting Row Resize Behaviour (WinUI/MacCatalyst)

### ISSUE THREAD

**Issue by TiberiusDRAIG** [dotnet/maui#15909]
### Description

Another weird Grid issue; the row resize behaviour seems to change depending on the column definitions, and I can't see any rhyme or reason to it.

The following is the expected behaviour that we see with a single '*' column; note that the label doesn't get cut-off before the scrollview starts scrolling:

[gridNotCutoff1Col.webm](https://github.com/dotnet/maui/assets/59740414/c2436c61-7d5b-4268-80df-b52c587bc0c3)

In the following example, the only change I have made is to make the Grid's column definitions '*,Auto', with everything still in the first column - note that the label now gets cut-off before the scrollview kicks in:

[gridCutoff2Cols.webm](https://github.com/dotnet/maui/assets/59740414/3b15c7df-6b5b-474f-bbb0-7bfa0e1debff)

Weirder still, the problem goes away if I move all of the content into the second column (the 'Auto' sized one):

[gridNotCutoff2ndCol.webm](https://github.com/dotnet/maui/assets/59740414/d16b53b5-d10e-4b73-93ad-2387d95c09f0)

### Steps to Reproduce

1. Create default MAUI template app
2. Update MainPage.xaml to:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
    <Grid RowDefinitions="*,Auto"
          ColumnDefinitions="*,Auto">
        <ScrollView Grid.Column="0">
            <VerticalStackLayout
                Spacing="25"
                Padding="30,0"
                VerticalOptions="Center">

                <Image
                    Source="dotnet_bot.png"
                    SemanticProperties.Description="Cute dot net bot waving hi to you!"
                    HeightRequest="200"
                    HorizontalOptions="Center" />

                <Label
                    Text="Hello, World!"
                    SemanticProperties.HeadingLevel="Level1"
                    FontSize="32"
                    HorizontalOptions="Center" />

                <Label
                    Text="Welcome to .NET Multi-platform App UI"
                    SemanticProperties.HeadingLevel="Level2"
                    SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                    FontSize="18"
                    HorizontalOptions="Center" />

                <Button
                    x:Name="CounterBtn"
                    Text="Click me"
                    SemanticProperties.Hint="Counts the number of times you click"
                    Clicked="OnCounterClicked"
                    HorizontalOptions="Center" />

            </VerticalStackLayout>
        </ScrollView>
        <Label Grid.Row="1"
               Grid.Column="0"
               HorizontalOptions="Center">I get cut off when there's two columns</Label>
    </Grid>
</ContentPage>
```

3. Resize window vertically and note that label in bottom row is cut-off before scrollview starts scrolling. 

### Link to public reproduction project repository

https://github.com/TiberiusDRAIG/MAuiGridRowCutOffBug

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

No. ~~Honestly, I'm starting to think the workaround for these things is to just give up and not use MAUI...~~ _Sorry, I'm just frustrated with these fundamental issues._

**Comment by TiberiusDRAIG** [comment]
Reproduced on Catalyst:

https://github.com/dotnet/maui/assets/59740414/fce87785-0dc3-4148-8fc5-231e1a846249

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Can repro on windows platform with sample project.
[MAuiGridRowCutOffBug-main.zip](https://github.com/dotnet/maui/files/13806705/MAuiGridRowCutOffBug-main.zip)
![image](https://github.com/dotnet/maui/assets/77434865/49b935f0-79cd-42a3-9b9f-068f3878b0bb)
