### ISSUE TITLE
When both relative layout width and height constraint is set, child layout is not getting focused.

### ISSUE THREAD

**Issue by SahanaSShetty** [dotnet/maui#15910]
### Description

Reference of this https://github.com/dotnet/maui/issues/13600 -  issue got closed So Opening a new issue.

 Tried the solution mentioned in the comment - https://github.com/dotnet/maui/issues/13600#issuecomment-1544790794 but still had the same issue.

### Steps to Reproduce

Steps to Reproduce
1. Add relative layout height and width constraints in the stack layout
2. Add an Entry view and Button inside the stack layout.
3. Focus on the Entry view, it should pop the keyboard on focus.
4. The keyboard is not popping up.

### Link to public reproduction project repository

https://github.com/SahanaSShetty/MauiExample

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. Repro on Windows 11 on .NET 8, Android 13.0-API33 and iOS 16.4 with below Project:
[MauiAppFocusIssue.zip](https://github.com/dotnet/maui/files/12211719/MauiAppFocusIssue.zip)
