### ISSUE TITLE
.NET MAUI not supported on Ubuntu

### ISSUE THREAD

**Issue by mcumming** [dotnet/maui#15929]
### Description

When trying to install .NET MAUI workload on Ubuntu , received this error:
```
~$ dotnet workload install maui
Workload ID maui isn't supported on this platform.
```

### Steps to Reproduce

1. Open terminal
2. run the command `dotnet workload install maui`

Expected Outcome: 
`maui` workload is successfully installed

Actual outcome:
`Workload ID maui isn't supported on this platform.`

### Link to public reproduction project repository

N/A

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

Ubuntu 22.04

### Did you find any workaround?

Installing `maui-android` will give you at least android targets, but cannot compile for Windows, iOS or MacCatalyst

**Comment by arviedelgado** [comment]
@mcumming maybe because MAUI does not support Ubuntu (Linux).
https://learn.microsoft.com/en-us/dotnet/maui/supported-platforms

> NET Multi-platform App UI (.NET MAUI) apps can be written for the following platforms:
> 
> Android 5.0 (API 21) or higher.
> iOS 11 or higher, using the latest release of Xcode.
> macOS 10.15 or higher, using Mac Catalyst.
> Windows 11 and Windows 10 version 1809 or higher, using Windows UI Library (WinUI) 3

**Comment by drasticactions** [comment]
@arviedelgado You can build Android apps with .NET on Linux. That's what he's referring to.

**Comment by Ghostbird** [comment]
MAUI is supported on Ubuntu. It's just that it only supports building Android applications, which will probably remain the case for a while. Building MacCatalyst and iOS apps is probably never going to be  supported on anything than MacOS because Apple won't permit it.

**Comment by mattleibow** [comment]
I believe this is an issue with macios not supporting Linux. Closing this issue as there are internal issues to track the progress of getting an ios workload at least installing on Linux and maybe building a plain dll for a better UX.
