### ISSUE TITLE
Incorrect/Cut off shadows

### ISSUE THREAD

**Issue by r-work** [dotnet/maui#15924]
### Description

When setting shadows on a button, it gets cut off.
It seems to be somewhat correct on Android `10`, `11` and `12`, but not on `9` and `13`

Check the button shadow in the following screenshots:

| Android 9 | Android 10 |
|:-:|:-:|
|![shadow_incorrect_android_9](https://github.com/dotnet/maui/assets/68378520/c1f746ef-f142-40f1-9d37-63625bc9e304) | ![shadow_correct_android_10](https://github.com/dotnet/maui/assets/68378520/5755aa7e-1096-481a-be7e-ab368222afd2)|
| Android 11 | Android 12 |
| ![shadow_correct_android_11](https://github.com/dotnet/maui/assets/68378520/7c37cdf7-4276-4772-a522-8bdcc39ad62d)|![shadow_correct_android_12](https://github.com/dotnet/maui/assets/68378520/c454752b-262e-4a54-8e21-9de2c523d607)|
|Android 13|Android 14|
|![shadow_incorrect_android_13](https://github.com/dotnet/maui/assets/68378520/d4b8161e-3e59-46fd-b352-50385c9f356f)| |

### Steps to Reproduce

1. Create a new MAUI project.
2. Paste the following in the MainPage.xml

```XAML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiShadowIssue.MainPage">

    <Grid>
        <Button
            Text="+"
            HorizontalOptions="End" 
            VerticalOptions="End" 
            HeightRequest="56" 
            WidthRequest="56" 
            CornerRadius="28"
            Margin="16">
            <Button.Shadow>
                <Shadow Radius="20" />
            </Button.Shadow>
        </Button>
    </Grid>

</ContentPage>
```

### Link to public reproduction project repository

https://github.com/r-work/MauiShadowIssue

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9 and 13

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. This issue **does not repro** on Android 13.0-API33 and Android 9.0-API28 (8.0.100-preview.6.23330.14), Windows 11 and iOS 16.4 with below Project:
[MauiShadowIssue.zip](https://github.com/dotnet/maui/files/12213612/MauiShadowIssue.zip)

![image](https://github.com/dotnet/maui/assets/97647558/7f3d0d06-6690-4ab8-9c32-23dbcc82fd32)
![image](https://github.com/dotnet/maui/assets/97647558/608e36cd-79cd-4f7d-9f9a-c753d4ffd1dc)

**Comment by mattleibow** [comment]
I tested again on 9.0 and 13.0 with .NET 7 and .NET 8. Appears to be working as expected now.
