### ISSUE TITLE
NullReferenceException in Font.Equals

### ISSUE THREAD

**Issue by nickwhaley** [dotnet/maui#15925]
### Description

Font.Equals does not account for the Name property being potentially null, like it is in Font.Default and Font.DefaultBold.

I came across this by setting the SkiaCanvas.Font property to Font.DefaultBold twice on the same canvas, which calls Equals between the existing font and the new one to set, throwing the exception.

### Steps to Reproduce

1. Run this code:

```
using Microsoft.Maui.Graphics;
Font.DefaultBold.Equals(Font.DefaultBold);
```

Expect: No exception.
Actual: A NullReferenceException is thrown.

### Link to public reproduction project repository

https://github.com/nickwhaley/Issue1

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

10.0.19045

### Did you find any workaround?

I have worked around that by just setting the font null before setting to Font.DefaultBold on any SkiaCanvas.Font to ensure no the exception regardless of the canvas state.

**Comment by jsuarezruiz** [comment]
The issue will be fixed by https://github.com/dotnet/maui/tree/fix-15925
