### ISSUE TITLE
Partial Repost: MainWindow freeze after workaround for "Maui partial UI freeze, typing to fast or method takes time to process."

### ISSUE THREAD

**Issue by carsten-riedel** [dotnet/maui#15939]
### Description

There is a known bug in the Windows App Sdk used by MAUI projects. (And other project types, Universal app etc.)
See references.

https://github.com/dotnet/maui/issues/13573

Tracked here:
https://github.com/microsoft/WindowsAppSDK/issues/3266

There is an advice how to fix this bug from [Eilon](https://github.com/Eilon) commented [on Apr 6](https://github.com/microsoft/WindowsAppSDK/issues/3266#issuecomment-1499402062)
See this comment for how to get the fix in a .NET MAUI Blazor project: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003#issuecomment-1499349079

It is basically upgrading to `<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.230313.1" />`

On the first run after applying this it seems to work. After deleting bin and obj folder (before run) or building the app in CI/CD this won't work and causes the **MAINWINDOW to partial freeze**. (See video trying to move, close etc. the MainWindow)

So basically, there is no solution with net7 MAUI Projects for the "UI freeze, typing to fast". 

This is a somewhat major showstopper for our current project. Cause how to progress with UI and Window freeze in net7, should we decide to stick to net6 and wait for net8 release, cause of the project timeline this could lead to some problems.

Would be nice if you could adjust priority on this topic and introduce a fix for net7 projects running `<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.230313.1" />`, causes a "Window Freeze" at the moment.

### Steps to Reproduce

Run link to public repository and try to move the window.

### Link to public reproduction project repository

https://github.com/carsten-riedel/Bug.Report.Maui1

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No workaround yet.

### Relevant log output

![2023-06-30_07h15_08](https://github.com/dotnet/maui/assets/97656046/df9c96f6-03cb-49b2-8d2c-fcdb0fa1a138)

**Comment by drasticactions** [comment]
@carsten-riedel Based on what you wrote, this seems like it's still an issue with Webview2/WinUI and is independent of the MAUI UI Framework. If you updated your WinUI build to one that contains their fix, and it still has issues, it's most likely still with WinUI. IMO, it would probably make more sense to move it back to WindowsAppSDK, unless we can prove it's something specific within MAUI itself.

@Eilon What do you think?

**Comment by Eilon** [comment]
> @carsten-riedel Based on what you wrote, this seems like it's still an issue with Webview2/WinUI and is independent of the MAUI UI Framework. If you updated your WinUI build to one that contains their fix, and it still has issues, it's most likely still with WinUI. IMO, it would probably make more sense to move it back to WindowsAppSDK, unless we can prove it's something specific within MAUI itself.
> 
> @Eilon What do you think?

Yeah I agree it should probably go to WindowsAppSDK first.

**Comment by carsten-riedel** [comment]
Reference to **WindowsAppSDK** [https://github.com/microsoft/WindowsAppSDK/issues/3702](url)
