### ISSUE TITLE
.NET MAUI Shell app page navigation memory leaks

### ISSUE THREAD

**Issue by duffh** [dotnet/maui#15930]
### Description

In a .NET MAUI Shell app running on Windows it looks like pages are held in memory after navigating to and then away from the page. This results in an increase in memory over time as pages are opened and closed.

We noticed this issue as we have some particularly memory intensive pages that result in steep memory jumps as they are opened and closed. 

### Steps to Reproduce

Setup 
1. Create new Maui app. File -> New Solution -> Maui App
2. Create two new MAUI ContentPages `SecondaryPage` and `TertiaryPage`
3. Add `SecondaryPage` to the Shell Flyout Items
4. Add a Button to the `SecondaryPage` with a clicked event `await Navigation.PushAsync(new TertiaryPage());`

Testing
1. Run the app targeting Windows
2. Navigate to the `SecondaryPage` via the Flyout
3. Navigate to the `TertiaryPage` via the Button on `SecondaryPage`
4. Click the back button 
5. Take a snapshot of the memory usage
6. Navigate to the `TertiaryPage` via the Button on `SecondaryPage`
7. Click the back button
8. Take a snapshot of the memory usage
6. Repeat as many times as desired

Result: Looking at the memory usage snapshots the number of instances of `TertiaryPage` in memory increases with the number of times the page has been opened. 

![image](https://github.com/dotnet/maui/assets/99325835/ebdf2796-133c-4f44-83c8-15e4848c57fa)

![image](https://github.com/dotnet/maui/assets/99325835/8ca3e191-aa72-495a-8fd1-cffadf087631)

Expected: The page should no longer exist in memory after navigating away, the number of instances in memory should not increase as the page is repeatedly opened. 

### Link to public reproduction project repository

https://github.com/duffh/MauiMemoryLeakTestApp

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by jonathanpeppers** [comment]
Did you push the change where you added `GC.Collect()`?

https://github.com/duffh/MauiMemoryLeakTestApp/commits/7e81ca10cd0b7a2c7d143a17bb7a0f8516c53b09

**Comment by duffh** [comment]
I have now pushed the changes, sorry for the delay.

**Comment by jonathanpeppers** [comment]
I think I'm seeing the memory leak here as well. I tested the existing memory leak tests we have with pages on Windows -- and they seem OK & pass. So, this seems like a new/unfixed problem.

My first guess, is it's related to setting up Shell:
```csharp
private void Initialize()
{
	FlyoutItem flyoutItem = new FlyoutItem();
	flyoutItem.Title = "SecondaryPage";

	ShellContent shellContent = new ShellContent();
	shellContent.Content = new SecondaryPage();
	shellContent.Route = $"{nameof(SecondaryPage)}_test";

	flyoutItem.Items.Add(shellContent);

	this.Items.Add(flyoutItem);
}
````

Then somehow there is a leak if once you do `await Navigation.PushAsync(new TertiaryPage());` from the `SecondaryPage`.

I don't see what is holding the `TertiaryPage` indefinitely (yet):

![image](https://github.com/dotnet/maui/assets/840039/4aae31f2-8812-4f4d-8fc9-7985cba9ffb8)

(some of these are ok, once you see it say "Cycle Detected" in this tree view)

I will keep investigating, thanks for filing this!

**Comment by duffh** [comment]
Great, thanks @jonathanpeppers !

**Comment by SarthakB26** [comment]
@duffh I think you should use Shell navigation i.e Shell.Current.GoToAsync("pagename");
Rather then Navigation.PushAsync(new TertiaryPage()); when using shell right or I am missing anything ?

**Comment by jonathanpeppers** [comment]
I've taken the approach that it doesn't really matter if the sample isn't best practice -- MAUI shouldn't leak.

`Navigation.PushAsync(new TertiaryPage())` is reasonable to expect it wouldn't leak.

**Comment by jonathanpeppers** [comment]
I tried reproducing the issue in a test -- but it passes:
```csharp
[Fact(DisplayName = "Routes Do Not Leak")]
public async Task RoutesDoNotLeak()
{
	SetupBuilder();
	var shell = await CreateShellAsync(shell =>
	{
		var flyoutItem = new FlyoutItem
		{
			Title = "SecondaryPage"
		};
		var shellContent = new ShellContent
		{
			Content = new ContentPage { Title = "Page 2" },
			Route = "page2",
		};
		flyoutItem.Items.Add(shellContent);

		shell.Items.Add(flyoutItem);
		shell.CurrentItem = new ContentPage { Title = "Page 1" };
	});

	WeakReference pageReference = null;

	await CreateHandlerAndAddToWindow<ShellHandler>(shell, async (handler) =>
	{
		await OnLoadedAsync(shell.CurrentPage);

		var page = new ContentPage
		{
			Title = "Page 3",
			Content = new VerticalStackLayout
			{
				new Label { Text = "Test", HorizontalOptions = LayoutOptions.Center, VerticalOptions = LayoutOptions.Center }
			},
		};
		pageReference = new WeakReference(page);

		await shell.GoToAsync("//page2");
		await shell.Navigation.PushAsync(page);
		await shell.Navigation.PopAsync();
	});

	// Windows requires an actual delay
	// Android/iOS require multiple GCs
	await AssertionExtensions.Wait(() =>
	{
		GC.Collect();
		GC.WaitForPendingFinalizers();
		return !pageReference.IsAlive;
	}, timeout: 5000);

	Assert.NotNull(pageReference);
	Assert.False(pageReference.IsAlive, "Page 3 should not be alive!");
}
```

So, I think I'll have to test the actual sample some more.

**Comment by jonathanpeppers** [comment]
Ok, I'm not seeing a leak anymore with dotnet/maui/main either:

![image](https://github.com/dotnet/maui/assets/840039/d8a143ae-7da9-40a0-9ad0-eed6ec031cf8)

![image](https://github.com/dotnet/maui/assets/840039/db4288a2-17ce-4026-97a7-481574832e5d)

But if I go back and try stable .NET 7 it leaks (as expected, as the fixes aren't there):

![image](https://github.com/dotnet/maui/assets/840039/32b1d7c5-5fb6-416a-95f8-39048334cd07)

So, then I tried MAUI 8.0.0-preview.5.8529 again, and it seems ok:

![image](https://github.com/dotnet/maui/assets/840039/72d64506-7a32-475c-bc40-4b770d978e4b)

I think when I was seeing the issue before -- I made some mistake with my local build of .NET MAUI.

I also cleaned the project between each version of MAUI I tested this time with this setting off:

![image](https://github.com/dotnet/maui/assets/840039/6bc20c66-658e-411e-b264-f95861185f52)

I believe this issue should be fixed in .NET 8 releases going forward.

@duffh if you try again, does the problem seem to go away? The only change I made to the project is:

https://github.com/jonathanpeppers/MauiMemoryLeakTestApp/commit/5ae66bfed900b6a55458a6b48f143b97c2cce660

I wonder if just doing a Clean or restarting VS (if turning off XAML HR) was needed before.

These are the builds that worked for me:
```
> dotnet workload list

Installed Workload Id      Manifest Version                            Installation Source
------------------------------------------------------------------------------------------
maui-windows               8.0.0-preview.5.8529/8.0.100-preview.5      VS 17.7.33808.371
maui-maccatalyst           8.0.0-preview.5.8529/8.0.100-preview.5      VS 17.7.33808.371
maccatalyst                16.4.8525-net8-p5/8.0.100-preview.5         VS 17.7.33808.371
maui-ios                   8.0.0-preview.5.8529/8.0.100-preview.5      VS 17.7.33808.371
ios                        16.4.8525-net8-p5/8.0.100-preview.5         VS 17.7.33808.371
maui-android               8.0.0-preview.5.8529/8.0.100-preview.5      VS 17.7.33808.371
android                    34.0.0-preview.5.312/8.0.100-preview.5      VS 17.7.33808.371
```
