### ISSUE TITLE
The width of the picker cannot be filled on Windows

### ISSUE THREAD

**Issue by Tenglingfeng** [dotnet/maui#15941]
### Description

          <Grid Grid.Row="7" ColumnDefinitions="2*,8*" Margin="10">
                <Button Grid.Column="0" x:Name="SearchTenantButton" Text="查询租户"
                        FontSize="18" FontAttributes="Bold"
                        HorizontalOptions="Center" VerticalOptions="Center"
                        Command="{Binding SearchTenantCommand}" />
                <Picker
                    Grid.Column="1"
                    VerticalOptions="Center"
                    FontSize="20"
                    SelectedItem="{Binding SelectedTenant}"
                    ItemsSource="{Binding Tenants}" Title="请选择租户" ItemDisplayBinding="{Binding Name}">
                </Picker>
            </Grid>

 

android:
![image](https://github.com/dotnet/maui/assets/55183506/0ccb6ebf-265c-45e3-8886-06cffcf6d836)

windows:
![image](https://github.com/dotnet/maui/assets/55183506/1d41802d-ef8a-4ca3-8d89-245a2a91e067)

ItemDisplayBinding="{Binding Name}"   Name is item  Property . Why did VS2022 prompt that no member was found?
![image](https://github.com/dotnet/maui/assets/55183506/684d7c96-76ec-4cf3-92d5-a8c71d407ea5)

### Steps to Reproduce

          <Grid Grid.Row="7" ColumnDefinitions="2*,8*" Margin="10">
                <Button Grid.Column="0" x:Name="SearchTenantButton" Text="查询租户"
                        FontSize="18" FontAttributes="Bold"
                        HorizontalOptions="Center" VerticalOptions="Center"
                        Command="{Binding SearchTenantCommand}" />
                <Picker
                    Grid.Column="1"
                    VerticalOptions="Center"
                    FontSize="20"
                    SelectedItem="{Binding SelectedTenant}"
                    ItemsSource="{Binding Tenants}" Title="请选择租户" ItemDisplayBinding="{Binding Name}">
                </Picker>
            </Grid>

### Link to public reproduction project repository

n/a

### Version with bug

7.0.49

### Last version that worked well

7.0.49

### Affected platforms

Android, Windows

### Affected platform versions

Android6.0  windows11

### Did you find any workaround?

no

### Relevant log output

```shell
-----
```

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0 in Windows 11. This issue didn't repro on .NET 8.0 with below Project:
[MauiApp9.zip](https://github.com/dotnet/maui/files/12225191/MauiApp9.zip)
Screenshot in Windows 11
![image](https://github.com/dotnet/maui/assets/131441429/c5d58d89-6455-415d-b530-712d3b37879a)
