### ISSUE TITLE
Visual Studio 17.7.0 Pre2 / Dotnet 8 8.0.100-preview.5.23303.2 / MAUI 8.0.0-preview.5.8529 build error XAGJS7023 for Android

### ISSUE THREAD

**Issue by rogerbriggen-securiton** [dotnet/maui#15947]
### Description

I try to compile my project with dotnet 8 and I get the same error as mentioned here: https://github.com/dotnet/maui/issues/12945

In my .csproj we have Windows, iOS and Android as platform and : 
<BuildIpa>true</BuildIpa>

"C:\Program Files\dotnet\dotnet.exe" build C:\BuildAgent\work\ef497e914ee5fdcb\MyProject.sln --configuration Release

17:27:48     C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\obj\Release\net8.0-android\android-arm\linked\Mono.Android.dll'. [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     [ERR] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\obj\Release\net8.0-android\android-arm\linked\Mono.Android.dll'. [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite) [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     [ERR] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite) [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.MarshalMethodsAssemblyRewriter.<Rewrite>g__CopyFile|6_0(String source, String target) [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     [ERR] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.MarshalMethodsAssemblyRewriter.<Rewrite>g__CopyFile|6_0(String source, String target) [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.MarshalMethodsAssemblyRewriter.Rewrite(DirectoryAssemblyResolver resolver, List`1 targetAssemblyPaths, Boolean brokenExceptionTransitions) [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     [ERR] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.MarshalMethodsAssemblyRewriter.Rewrite(DirectoryAssemblyResolver resolver, List`1 targetAssemblyPaths, Boolean brokenExceptionTransitions) [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res, Boolean useMarshalMethods) [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     [ERR] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res, Boolean useMarshalMethods) [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask() [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     [ERR] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask() [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25 [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     [ERR] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25 [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:49  

### Steps to Reproduce

1. Install latest dotnet 8 preview with MAUI
2. Create a maui project
3. Enable ipa and apk during build
4. build release mode

### Link to public reproduction project repository

-

### Version with bug

Unknown/Other

### Last version that worked well

7.0.86

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No

### Relevant log output

```shell
17:27:48     C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res, Boolean useMarshalMethods) [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     [ERR] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res, Boolean useMarshalMethods) [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask() [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     [ERR] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask() [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25 [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:48     [ERR] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.5.312\tools\Xamarin.Android.Common.targets(1513,3): error XAGJS7023:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25 [C:\BuildAgent\work\ef497e914ee5fdcb\MyProject\MyProject.csproj::TargetFramework=net8.0-android]
17:27:49
```

**Comment by dellis1972** [comment]
I cannot repo this on .net 8 preview 7  (8.0.100-preview.7.23376.3)
We think it is because we disabled Marshal methods. We shall log this issue for future work.

In the mean time try adding the following to your build command see if that helps.

```
-p:AndroidEnableMarshalMethods=false
```
