### ISSUE TITLE
Android app doesn't build if project location path has a dot

### ISSUE THREAD

**Issue by vpshonyak** [dotnet/maui#15963]
### Description

Once I change project location and path has dot in it, I cannot build an Android app. The following error occurs:

Error	APT2260	resource mipmap/appicon (aka com.companyname.mauiapp1:mipmap/appicon) not found.
This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.	
 

### Steps to Reproduce

Change project location path and add the dot to it,
 
### Link to public reproduction project repository

https://github.com/vpshonyak/MauiApp1.git

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

### Did you find any workaround?

Change project location. Make sure there is no dot in it.

**Comment by jfversluis** [comment]
@vpshonyak could you give an example of what that path would look like? Did you try this on Windows, Mac, both? Does this only happen for Android or also iOS?

**Comment by vpshonyak** [comment]
@jfversluis  tried on Windows only. Path was C:\Projects\App.MAUI. It happens only on Android. iOS is fine.

**Comment by jsuarezruiz** [comment]
> ### Description
> Once I change project location and path has dot in it, I cannot build an Android app. The following error occurs:
> 
> Error APT2260 resource mipmap/appicon (aka com.companyname.mauiapp1:mipmap/appicon) not found. This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.
> 
> ### Steps to Reproduce
> Change project location path and add the dot to it,
> 
> ### Link to public reproduction project repository
> https://github.com/vpshonyak/MauiApp1.git
> 
> ### Version with bug
> 8.0.0-preview.5.8529
> 
> ### Last version that worked well
> Unknown/Other
> 
> ### Affected platforms
> Android
> 
> ### Affected platform versions
> Android 9
> 
> ### Did you find any workaround?
> Change project location. Make sure there is no dot in it.
> 
> ### Relevant log output
> _No response_

The link for the reproduction sample is not working, could you review it?. Thanks in advance.

**Comment by moljac** [comment]
> Path was C:\Projects\App.MAUI. It happens only on Android. iOS is fine.

Please do NOT use `App.` (note `.`) as part of the name od the MAUI project. `App` is a name (filename and class) used in/by MAUI:

```
App.xaml
App.xaml.cs
```

You can change it, but I would not recommend that. Autogenerated code might cause issues.

If you want to (must) use `App.` (like I do) then call it `AppMAUI.*` or `AppAndroid.*` or `AppDroid.*`.

BTW: `aapt[2]` is very sensitive to filenames. To name few:

1. no multiple dots AKA multiple extensions
2. names must be lowercase 

I cannot repro. Added 4 cases:

1. original
2. changed top folder
3. changed top folder and project/solution names, but not csproj content
4. changed top folder and project/solution names AND csproj content

[ReproAttempts.zip](https://github.com/dotnet/maui/files/12000958/ReproAttempts.zip)
