### ISSUE TITLE
Grid * Row is broken on iOS

### ISSUE THREAD

**Issue by Larhei** [dotnet/maui#15968]
### Description

On iOS Grid Rowdefinitions with * size take up the whole screen. 

When doing
`<Grid RowDefinitions="*,auto" />`

everything placed in the auto row is below the end of the screen.

For more, see attached repo. This was working in previous versions. But not sure which on.

### Steps to Reproduce

1. Checkout repo and run it.

### Link to public reproduction project repository

https://github.com/Larhei/Maui-Issues/tree/main/ParentLayoutIssues

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

14.3

### Did you find any workaround?

Calculating MaxHeight for Elements in * Size rows by myself.

**Comment by arahmancsd** [comment]
This happens when there is a scroll in the first row in iOS. the workaround for me was to use the Flex Layout instead of Grid. Flex Layout has issues with Android which don't work as expected when there is a CollectionView on the page.

**Comment by Larhei** [comment]
It´s not just related to Scrollview.
In case of
`<Grid RowDefinitions="*,auto,*" />`
With some control in the auto row, it is the same. The control is below the screen size.

**Comment by pkalwig** [comment]
@Larhei wrap your View under GridLenght.Star into AbsoluteLayout.
`<AbsoluteLayout Grid.Row="0">
    <AnyView
        AbsoluteLayout.LayoutFlags="SizeProportional"
        AbsoluteLayout.LayoutBounds="0,0,1,1" />
</AbsoluteLayout>`

**Comment by patbosc** [comment]
@jsuarezruiz the same applies to android as well btw.

**Comment by Blinchik91** [comment]
> 

@arahmancsd 
it does not work for me, I get a NullReferenceException

`     ...
 <CollectionView.ItemTemplate>
                <DataTemplate x:DataType="models:SpaceshipItem">
                    <OnPlatform x:TypeArguments="View">
                        <On Platform="iOS">
...`

**Comment by jsuarezruiz** [comment]
cc @hartez

**Comment by jsuarezruiz** [comment]
Could be related or be the same https://github.com/dotnet/maui/issues/15966?

**Comment by arahmancsd** [comment]
> > 
> 
> @arahmancsd it does not work for me, I get a NullReferenceException
> 
> ` ... <CollectionView.ItemTemplate> <DataTemplate x:DataType="models:SpaceshipItem"> <OnPlatform x:TypeArguments="View"> <On Platform="iOS"> ...`


Until the fix, if you are following my workaround, please do the opposite.

```
<OnPlatform x:TypeArguments="View">
        <On Platform="iOS">
            <FlexLayout Direction="Column">
                 <Lable Text="header" />

                <FlexLayout FlexLayout.Grow="1">
                      <CollectionView FlexLayout.Grow="1">
                      </CollectionView>
                </FlexLayout>

              <Label Text="footer" />
            </FlexLayout>
       </On>

       <On Platform="Android">
           <Grid RowDefinitions="*,Auto">
              ...
           </Grid>
      </On>
</OnPlatform>
```

**Comment by hartez** [comment]
This is fixed for service release 7 (which should be landing next week).
