### ISSUE TITLE
Item Selected from ViewModel for CollectionView De-selected automatically

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#15967]
### Description

Item Selected from ViewModel for CollectionView De-selected automatically. If the item is selected from view the item does not de-selects.

### Steps to Reproduce

Run the reproduction sample. The SelectedItem is assigned in the constructor of the view model. Once the Selection Changed command will be executed for the selected item.  Immediately the items gets de-selected and the selection changed command executes again. 

### Link to public reproduction project repository

https://github.com/HobDev/MauiBugs/tree/SelectedItemDeselectedIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows 10.0.19041.0

### Did you find any workaround?

No

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0 in Windows 11. This issue repro on .NET 8.0 with below Project:
[MauiApp13.zip](https://github.com/dotnet/maui/files/12226130/MauiApp13.zip)
