### ISSUE TITLE
Dragging random stuffs inside webview shows weird looking icon

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/maui#15969]
### Description

![image](https://github.com/dotnet/maui/assets/35312807/efe0faaa-ae0a-419c-b81f-89b2e070f858)
Sometimes dragging random element with mouse makes an icon appear, it makes my app look low quality and crashes

### Steps to Reproduce

Randomly dragging something inside UI, usually a div having nothing inside other than size and background color defined in style
I guess it's only a maui thing not asp.net thing

### Link to public reproduction project repository

Just add an div with nothing in it, to the default MAUI.blazor template

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by Xyncgas** [comment]
You have to try clicking and dragging at nothing for a couple of times
In my example I made div that takes the entire screen, and did that really fast and it appears always
in order to move that icon, I had to drag my mouse but now starting from the task title bar

**Comment by mhrastegari** [comment]
you should set 
```
*:not(input) {
                -webkit-user-select: none;
            }
```
in your `index.html`.

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0 in Windows 11. This issue repro on .NET 8.0 with below Project:
[MauiApp3.zip](https://github.com/dotnet/maui/files/12235383/MauiApp3.zip)

**Comment by Xyncgas** [comment]
> you should set
> 
> ```
> * {
>      -webkit-user-drag: none;
>   }
> ```
> 
> in your `index.html`.

![image](https://github.com/dotnet/maui/assets/35312807/6f613734-5a5b-477f-80b7-6f660dfbf996)

**Comment by Xyncgas** [comment]
Tried both methods together, still
![image](https://github.com/dotnet/maui/assets/35312807/f542ccdf-dbd1-4a66-a0a7-3bd4f0fb98bc)

**Comment by Xyncgas** [comment]
maybe to repro this you need to drag very fast

**Comment by Xyncgas** [comment]
![image](https://github.com/dotnet/maui/assets/35312807/57e88ca7-2f29-4076-b1af-e2cbe8490fe4)

Selecting text and dragging always produce the icon, it doesn't look like this in edge or firefox it gotta stop because for people who are using lenovo's 'nipple' to move their mouse it feels bad to try to click somewhere but nothing works in turns shows these icons instead

**Comment by mhrastegari** [comment]
Have you tried to add `draggable="false"` in your index.html body tag?

**Comment by Xyncgas** [comment]
> Have you tried to add `draggable="false"` in your index.html body tag?

![image](https://github.com/dotnet/maui/assets/35312807/a26e41cb-f973-4439-86f5-efb8aafe13a4)

**Comment by mkArtakMSFT** [comment]
Closing as we don't control over this. This is related to WebView2.

**Comment by Xyncgas** [comment]
Thanks
