### ISSUE TITLE
Archiving apk using .net 7.0+ for android includes wrong platforms

### ISSUE THREAD

**Issue by mosammo** [dotnet/maui#15971]
### Description

[severity:I’m unable to use this version]
Archiving apk using .net 7.0 for android with “Target platform” “ARM64” produces large apk that includes assemblies of other platforms “X86” and “x64” which increases apk size considerably.

Expected behavior is to only include assemblies of the selected target platform. For example if we select “ARM32” it should not include other platforms like “ARM64”, “X86” and “x64”.

Latest visual studio 2022 17.6.2

### Steps to Reproduce

simple steps:
1. Create a maui project.
2. Right click the project to select the properties change Target platform to “ARM64” under Build->General
3. Build the project then archive apk.

To check it simply rename the apk as .zip file then open it and check folders “assemblies” and “bin” inside the apk. (please check attached screenshots)

### Link to public reproduction project repository

https://github.com/mosammo/DotNetIssues

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

.net 7 for android

### Did you find any workaround?

no

**Comment by mosammo** [comment]
Example apk for platform "ARM64" including unselected platforms assemblies
![large apk size due to including wrong platforms](https://github.com/dotnet/maui/assets/137315518/6a850db4-4abf-4082-802e-dc1752d1f7be)

**Comment by jfversluis** [comment]
The reproduction is not using .NET MAUI at all, while this probably would apply to .NET MAUI too, the core is in .NET for Android. Moving it to the right repo.

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-android#8165
