### ISSUE TITLE
App won't run n Windows Machine

### ISSUE THREAD

**Issue by lane8800** [dotnet/maui#15978]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Windows 11: Attempt to run the application on Windows Machine with Framework "net7.0-windows10.0.19041.0"

Error: "The project needs to be deployed before we can debug. Please enable Deploy in the configuration Manager" with .  I set "Deploy" in the Configuration Manager. I also removed and re-installed the SDKs as indicated on another possible fix. Still, nothing works. 
Also, I get an error in the Error List window in Visual Studio 2022 that says "DEP0700: Registration of the app failed. [0x80073CFD] Windows cannot deploy to path AppX of file system type exFAT". I tried uninstalling the workloads and reinstalling them using the Visual Studio installer to no avial.

Help!

**Comment by milklike** [comment]
Your file system need change to ntfs

**Comment by jfversluis** [comment]
I think that covers it. Unfortunately this can be a potentially drastic change to your machine. Maybe it would be an idea to do it on a virtual machine? Hope this will give you enough info to start looking further into your .NET MAUI adventures.

Unfortunately there is nothing actionable that we can do here, so I'm closing this one. Good luck!
