### ISSUE TITLE
Unable to publish and generate ipa file in .net 8.0 preview 5

### ISSUE THREAD

**Issue by RNavaneethKumar** [dotnet/maui#15973]
### Description

I'm trying to publish and generate an IPA file using the following command.

dotnet publish -f:net8.0-ios -c:Release /p:ArchiveOnBuild=true /p:RuntimeIdentifier=ios-arm64 /p:CodesignKey="*******************" /p:CodesignProvision="********" /p:ServerAddress=********* /p:ServerUser=macmini /p:ServerPassword=******* /p:TcpPort=58181 /p:_DotNetRootRemoteDirectory=/Users/macmini/Library/Caches/Xamarin/XMA/SDKs/dotnet/

The publish was working fine until I updated to .net 8 preview 5. However, after updating to .net 8 preview 5, the publish proceeds and fails towards the end. Below is a screenshot of the error.

![Error](https://github.com/dotnet/maui/assets/22679526/fce5727b-c1dc-4ce7-bdb5-04c65f485773)

Has anyone faced this issue or know why this issue might be caused. This was 

### Steps to Reproduce

Create the project and publish using the following command
dotnet publish -f:net8.0-ios -c:Release /p:ArchiveOnBuild=true /p:RuntimeIdentifier=ios-arm64 /p:CodesignKey="*******************" /p:CodesignProvision="********" /p:ServerAddress=********* /p:ServerUser=macmini /p:ServerPassword=******* /p:TcpPort=58181 /p:_DotNetRootRemoteDirectory=/Users/macmini/Library/Caches/Xamarin/XMA/SDKs/dotnet/

### Link to public reproduction project repository

No public repo

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

7.0.86

### Affected platforms

iOS

### Affected platform versions

ios

### Did you find any workaround?

None

**Comment by jsuarezruiz** [comment]
@rolfbjarne Thoughts?

**Comment by RNavaneethKumar** [comment]
@rolfbjarne Would be very helpful if there is a solution or workaround.

**Comment by samhouts** [comment]
@emaf Are the locked files a tooling issue perhaps?

**Comment by RNavaneethKumar** [comment]
When I changed the project files to target .net 7.0 and ran the command
with .net 7.0, it created the ipa file without any problem. The problem is
only with 8.0.

**Comment by emaf** [comment]
> @emaf Are the locked files a tooling issue perhaps?

I don't think so. This looks like a bug that Rolf fixed recently (https://github.com/xamarin/xamarin-macios/pull/18410), and that fix was included on .NET 8 Preview 6.

@RNavaneethKumar Could you try updating to Preview 6? 
Also, if you just intend to generate an IPA file (and not also an archive), you can drop `/p:ArchiveOnBuild=true`.

**Comment by dustin-wojciechowski** [comment]
@RNavaneethKumar @emaf I went ahead and tried publishing in the same fashion that you were able to and was successful using Preview 6. This is the exact version I used:
`8.0.100-preview.6.23330.14`

I recommend downloading preview 6 and giving it a shot. I hope that helps!

**Comment by RNavaneethKumar** [comment]
Hi everyone. I confirm this has been fixed in .net 8.0 preview 6. I am able
to create the ipa file successfully

**Comment by RNavaneethKumar** [comment]
Hi everyone. I confirm this has been fixed in .net 8.0 preview 6. I am able
to create the ipa file successfully. Thanks a ton :)
