### ISSUE TITLE
Maui - SwipeView not working with Editor control in iOS

### ISSUE THREAD

**Issue by RawoofSharief** [dotnet/maui#15975]
### Description

SwipeView item not swiping when the item has editor control inside the template. Please refer the below screenshot.

![Simulator Screen Shot - iPhone 14 - 2023-07-03 at 18 26 21](https://github.com/dotnet/maui/assets/39043330/30377aa5-8994-4738-ac09-69903aa2a333)

If I use label or entry controls, Swiping is working properly. Please refer the below screenshot.

![Simulator Screen Shot - iPhone 14 - 2023-07-03 at 18 29 26](https://github.com/dotnet/maui/assets/39043330/e9e372ed-0984-4498-9e2f-e0e6eafd60ad)

### Steps to Reproduce

    <Grid x:Name="SwipeViewGrid" 
              RowDefinitions="*">
        <CollectionView x:Name="collectionView"
            HorizontalOptions="FillAndExpand"
            SelectionMode="None"
            ItemSizingStrategy="MeasureAllItems"
            VerticalScrollBarVisibility="Never">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                        <SwipeView Threshold="0" IsClippedToBounds="True">
                        <SwipeView.RightItems>
                            <SwipeItems SwipeBehaviorOnInvoked="Close" >
                                <SwipeItemView >
                                    <Frame Margin="10,20,25,20" WidthRequest="80"
                                            Padding="8"
                                            HasShadow="False"
                                            BackgroundColor="Red"
                                            CornerRadius="7"
                                            IsClippedToBounds="True">
                                        <Label Text="Delete" Margin="0" Padding="0"
                                                TextColor="Black"
                                                TextTransform="Uppercase"
                                                VerticalOptions="Center"
                                                HorizontalOptions="Center" HorizontalTextAlignment="Center"
                                                LineBreakMode="WordWrap"
                                                FontSize="12"/>
                                    </Frame>
                                </SwipeItemView>
                            </SwipeItems>
                        </SwipeView.RightItems>
                        <Grid Padding="10">
                            <Frame BackgroundColor="Transparent" Margin="10"
                                HasShadow="False"
                                Padding="10"
                                BorderColor="Grey"
                                CornerRadius="7"
                                IsClippedToBounds="True">
                                <Grid ColumnDefinitions="Auto,*"
                                    ColumnSpacing="10">

                                    <Frame Grid.Column="0"
                                        HasShadow="False"
                                        CornerRadius="5"
                                        IsClippedToBounds="True"
                                        Padding="0"
                                        Margin="0">
                                        <Image Source="dotnet_bot.png"
                                            HeightRequest="55" WidthRequest="54"
                                            Aspect="Fill"
                                            VerticalOptions="Center"
                                            BackgroundColor="Transparent">
                                        </Image>
                                    </Frame>
                                    <Grid Grid.Column="1">
                                        <Editor 
                                            BackgroundColor="Transparent"
                                            MinimumHeightRequest="50" MaximumHeightRequest="50"
                                            Placeholder="Enter Text Here"
                                            />
                                    
                                    </Grid>
                                </Grid>
                            </Frame>
                        </Grid>
                    </SwipeView>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </Grid>

### Link to public reproduction project repository

https://github.com/RawoofSharief/SwipeIssue.git

### Version with bug

7.0.59

### Last version that worked well

6.0

### Affected platforms

iOS

### Affected platform versions

16.2

**Comment by drasticactions** [comment]
If you could create a reproduction project, rather than a XAML segment, that would make it easier to properly reproduce, debug, and verify the issue and make sure it's fixed.

**Comment by RawoofSharief** [comment]
Please find the reproduction sample project in the below link. Also,I have added in the issue description.

Sample Link :  https://github.com/RawoofSharief/SwipeIssue.git

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 6.0 in iOS 16.4. This issue didn't repro on .NET 8.0 with below Project:
Screenshot in iSO16.4:
[MauiApp4.zip](https://github.com/dotnet/maui/files/12235578/MauiApp4.zip)
![image](https://github.com/dotnet/maui/assets/131441429/c080f2c3-0b83-45d2-8c44-2572cd77450d)
