### ISSUE TITLE
Can't get BindableProperty to work

### ISSUE THREAD

**Issue by Laursen1992** [dotnet/maui#15976]
### Description

BindeableProperty doesn't get hit.

Previously i've gotten, what seem to be the exact same thing, to work. But somehow i can't get it to work any longer.

### Steps to Reproduce

1.Create a Content view

2. Setup BindableProperty in the content view's code-behind

![image](https://github.com/dotnet/maui/assets/47735401/eaf3f473-f364-4e93-a199-ed29bf978fb0)

3. On another page, try to use the content view, and bind an entry's text to the bindable property in that content view

![image](https://github.com/dotnet/maui/assets/47735401/604872fe-bcd4-41e1-abe2-27714fc79360)

4. Write something in the entry, and see that the bindable property doesn't get hit.

### Link to public reproduction project repository

https://github.com/Laursen1992/MauiApp3

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 13

**Comment by Laursen1992** [comment]
@jfversluis Thanks for the answer!
 
I see. Now i know it doesn't necessarily go through the setter. Although my original problem still persists. I try to make a bindable boolean, which never gets updated, as far as I can see. I have implemented OnPropertyChanged in the parents ShowClipBoard property:

![image](https://github.com/dotnet/maui/assets/47735401/75e5924e-b4bd-4b53-9e4e-4896eb43bb4b)

In the child components setter for the bindable property, i try to update a number of things, which never happens

**Comment by jfversluis** [comment]
I think this part is key here:

> If you really do need to make sure you catch all the changes, be sure to implement the OnPropertyChanged or OnPropertyChanging parameters.

You might want to refer to this great blog about it: https://mfractor.com/blogs/news/using-bindable-properties-in-xamarin-forms

It's about Xamarin.Forms, but this exact code should work for .NET MAUI as well.

**Comment by Laursen1992** [comment]
@jfversluis That did it! Thank you.

Still have no idea why this was necessary though in this case, when I got it to work without calling the onpropertyChanged in the BindableProperty, in other parts of the code. But at least I have a way to solve the prior problem, so thank you :)
