### ISSUE TITLE
iOS - CollectionView incorrect behaviors

### ISSUE THREAD

**Issue by Blinchik91** [dotnet/maui#15977]
### Description

immediately after starting the app in iOS Simunlator the grid dimension is faulty.
If you pull it a bit, the dimension corrects itself, but items disappear

Everything works fine and correctly on Android! 

![image](https://github.com/dotnet/maui/assets/70434936/c5b50f92-1623-46ee-b4c6-e5126b11a787)

![image](https://github.com/dotnet/maui/assets/70434936/cde53902-6a0a-4b50-97a2-5e8374284581)

Additional Information:
SDK: .NET 7.0.304

### Steps to Reproduce

1. Start the application in iOS Simulator and the first Bug immediately appears
2.  Pull the CollectionView a bit and the second Bug immediately appears

Repo: https://github.com/Blinchik91/CollectionView/tree/main

**Comment by Blinchik91** [comment]
> Hi @Blinchik91. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

Repo added https://github.com/Blinchik91/CollectionView/tree/main

**Comment by xtuzy** [comment]
refreshview's bug

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. This issue repro on iOS 16.4 .NET 7, not repro on iOS 16.4 .NET 8, Windows 11 and Android 13.0-API33 with below Project:
[Maui_Spaceships.zip](https://github.com/dotnet/maui/files/12236816/Maui_Spaceships.zip)
**iOS on .NET 8**:
![Refresh](https://github.com/dotnet/maui/assets/97647558/aefa9b89-73be-42dc-81f4-4e84c1e71cdf)
