### ISSUE TITLE
Content Page Can Not Extend Edge To Fullscreen When Using Translucent NavigationBar 

### ISSUE THREAD

**Issue by microspaze** [dotnet/maui#15989]
### Description

When set NavigationBar's ios:NavigationPage.IsNavigationBarTranslucent="true", according the source code in NavigationRender's sub class ParentingViewController:
```
public override void ViewWillAppear(bool animated)
{
    SetupDefaultNavigationBarAppearance();
    UpdateNavigationBarVisibility(animated);
    
    NavigationRenderer n;
    var isTranslucent = false;
    if (_navigation.TryGetTarget(out n))
	    isTranslucent = n.NavigationBar.Translucent;
    EdgesForExtendedLayout = isTranslucent ? UIRectEdge.All : UIRectEdge.None;
    
    base.ViewWillAppear(animated);
}
```
The EdgesForExtendedLayout will be set to UIRectEdge.All, then the content page should extend to the fullscreen. 

It works in Xamarin.Forms. However in MAUI, everytime the ParentingViewController ViewDidLayoutSubviews, it will call a UpdateFrames method:

```
public override void ViewDidLayoutSubviews()
{
	base.ViewDidLayoutSubviews();
	UpdateFrames();
}

public void UpdateFrames()
{
	NavigationRenderer n;

	// We only want to update the frame after the navigation has settled
	// The frame bounces a bit during navigation and it messes up 
	// the animation changing the frame during navigation
	if (_navigation.TryGetTarget(out n) &&
		ChildViewControllers.Length > 0 &&
		!n._navigating)
	{
		nfloat offset = 0;

		if (n._hasNavigationBar)
			offset = n.NavigationBar.Frame.Bottom;

		if (!n._secondaryToolbar.Hidden)
		{
			offset += n._secondaryToolbar.Bounds.Height;
		}

		if (View.Frame.Y != offset)
		{
			var newY = offset - View.Frame.Y;
			var newHeight = View.Frame.Height - newY;

			View.Frame =
				new RectangleF(0, offset, View.Bounds.Width, newHeight);
		}
	}
}
```

The UpdateFrames method will SET the Y of current page's frame. And NO WAY to override it, because it writes in the end of the ViewDidLayoutSubviews method.

Then the content page will leave the header part empty just like:

![d57dff3ef4aaa3a046635089b919490](https://github.com/dotnet/maui/assets/17372096/22a6da88-11a4-4a5f-9ef2-1e9cca132a9a)

### Steps to Reproduce

1. Add a NavigationPage
2. Add xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls" to NavigationPage
3. Add ios:NavigationPage.IsNavigationBarTranslucent="true" to NavigtionPage
4. Set BarBackgroundColor="Transparent"
5. Jump to a content page
6. Check the content page's head part.

### Link to public reproduction project repository

https://github.com/dotnet/maui/blob/700944b2ac65c4807c657336b49c72c30e4da1da/src/Compatibility/Core/src/iOS/Renderers/NavigationRenderer.cs

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

### Did you find any workaround?

NO WORKAROUND

**Comment by VinShen** [comment]
Facing same issue with iOS 16.7.2 with Microsoft.Maui.Controls Version 8.0.3. Any Solution or workaround?

**Comment by microspaze** [comment]
> Facing same issue with iOS 16.7.2 with Microsoft.Maui.Controls Version 8.0.3. Any Solution or workaround?

Here is my ugly workaround, it has been tested on .NET 7. You may need modify some code for .NET 8.

```
public class MyNavigationRenderer : NavigationRenderer
{
    private NavigationPage _navigationPage => base.Element as NavigationPage;

    //You can create your own BindableProperty to identify whether the NavigationBar is Transparent
    private bool IsTransparent => true;

    private bool HasNavigationBar => _navigationPage is { CurrentPage: not null } && NavigationPage.GetHasNavigationBar(_navigationPage.CurrentPage);

	public override void ViewDidLayoutSubviews()
	{
		base.ViewDidLayoutSubviews();
		
		if (HasNavigationBar && IsTransparent && View != null)
		{
			var viewFrame = View.Frame;
			var viewHeight = viewFrame.Height;
			var navHeight = GetNavHeight();
			var parentingController = ChildViewControllerForPointerLock;
			var parentingView = parentingController?.View;
			var parentingFrameY = parentingView?.Frame.Y;
			var subview = parentingView?.Subviews.FirstOrDefault();
			if (parentingView != null
				&& subview != null 
				&& (parentingView.Frame.Height < viewHeight || parentingFrameY == 0)
				&& (subview.Frame.Y >= 0 || (parentingFrameY == 0 && subview.Frame.Y < 0)))
			{
				//Must set the parentingView's Height = 844
				if (parentingFrameY == 0)
				{
					viewFrame.Height = viewHeight + navHeight;
					viewFrame.Y = navHeight;
				}
				parentingView.Frame = viewFrame;
				
				//Refetch the subview after parentingView's frame update
				subview = parentingView?.Subviews.FirstOrDefault();
				if (subview != null && subview.Frame.Y >= 0)
				{
					//Must set the subview's Height == 844+91
					var subviewFrame = subview.Frame;
					subviewFrame.Height = parentingFrameY == 0 ? viewHeight + 2 * navHeight : viewHeight + navHeight;
					subviewFrame.Y = -navHeight;
					subview.Frame = subviewFrame;
				}
			}
		}
	}
	
	private nfloat GetNavHeight()
	{
		nfloat height = UIApplication.SharedApplication.StatusBarFrame.Height;
		nfloat height2 = NavigationBar.Frame.Height;
		if (_doesSafeAreaConceptExist)
		{
			UIEdgeInsets safeAreaInsets = UIApplication.SharedApplication.Windows[0].SafeAreaInsets;
			if (safeAreaInsets.Top > 0)
			{
				return safeAreaInsets.Top + height2;
			}
		}
		return height + height2;
	}
}
```

**Comment by VinShen** [comment]
Thanks and appreciate your quick reply. I will try this with .Net 8

Can anyone clarify please,
Is this a bug or ios:NavigationPage.IsNavigationBarTranslucent="true" is not supported by Microsoft.Maui.Controls now?
With latest .Net 8 and iOS 17 (XCode 15) the same issue is still there
Is there no real bug fix or am I missing something?

**Comment by VinShen** [comment]
Is there any way to get transparent Navigation Bar in Android App with Maui .Net 8.
I have done it in Xamarin Forms using AppNavigationRenderer overriding OnLayout method.
