### ISSUE TITLE
[MAUI] New recipe page is missing "New recipe" title after rotating emulator/device.

### ISSUE THREAD

**Issue by jaosnz-rep** [dotnet/maui#15982]
### Description

New recipe page is missing "New recipe" title after rotating emulator/phone.

### Steps to Reproduce

1.Deploy https://github.com/rachelkang/recipeSearch to Android/iOS emulator or device.
2.Tap on the 'My Recipes' tab to navigate to the 'My Recipes' page.
3.Tap on the 'New' button in the upper right-hand corner of the page to navigate to the 'New Recipe' page.
4.Rotate the emulator or device to the horizontal orientation.

Actual results:
The "New recipe" title is missing.
![image](https://github.com/dotnet/maui/assets/82628041/75749f41-60d2-489f-831d-89bb50690e6b)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

7.0.92

### Affected platforms

iOS, Android

### Affected platform versions

net ios 16.4.7067, net android 33.0.46

**Comment by rachelkang** [comment]
Validated that this is indeed an issue. Workaround: Removing the margin from the "Recipe name" label will make it appear.

This is an issue in preview1, preview2, preview5 of net8, as well as on current main. It is also an issue on 7.0.86.

On preview3 and preview4 however, the "New Recipe" label _does_ show. However, it presents with a different issue with unexpectedly large spacing and scrolling issues, as captured in https://github.com/dotnet/maui/issues/15521

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. This issue does not Repro on Android 13.0-API33 and iOS 16.4 (**.NET 8.0.100-preview.6.23330.14**) with below Project:
[WhatToEat.zip](https://github.com/dotnet/maui/files/12225620/WhatToEat.zip)

**Android:**
![image](https://github.com/dotnet/maui/assets/97647558/f20f4d5a-132a-4596-8edb-1512c531589b)
**iOS:**
![image](https://github.com/dotnet/maui/assets/97647558/b36c635a-4c2c-4351-a85d-9b1c57f289e7)
