### ISSUE TITLE
Pages retained in memory when using DynamicResource Grid style

### ISSUE THREAD

**Issue by duffh** [dotnet/maui#15986]
### Description

In a .NET MAUI Shell app running on Windows it looks like pages referencing DynamicResource Grid styles are held in memory after navigating to and then away from the page. This results in an increase in memory over time as pages are opened and closed.

### Steps to Reproduce

Setup 
1. Create new Maui app. File -> New Solution -> Maui App
2. Add the following style to `Styles.xaml`:
```
<Style x:Key="GridContainer" TargetType="Grid">
    <Setter Property="Grid.RowDefinitions" Value="Auto,*" />
    <Setter Property="Grid.ColumnDefinitions" Value="*,Auto" />
</Style>
```
3. Create two new MAUI ContentPages `StyledPage` and `UnstyledPage`
4. Add a `Grid` element to both of the newly created pages
   4a. To the `StyledPage` add:
   ```
   <Grid Style="{DynamicResource GridContainer}">
    <Label 
        Grid.Row="0" Grid.ColumnSpan="2"
        Text="This is the first row"
        VerticalOptions="Center" 
        HorizontalOptions="Center" />
    <Label 
        Grid.Row="1" Grid.ColumnSpan="2"
        Text="This is the second row"
        VerticalOptions="Center" 
        HorizontalOptions="Center" />
   </Grid>
   ```
   4b. To the `UnstyledPage` add:
   ```
   <Grid RowDefinitions="Auto, *" ColumnDefinitions="*, Auto">
    <Label 
        Grid.Row="0" Grid.ColumnSpan="2"
        Text="This is the first row"
        VerticalOptions="Center" 
        HorizontalOptions="Center" />
    <Label
        Grid.Row="1" Grid.ColumnSpan="2"
        Text="This is the second row"
        VerticalOptions="Center" 
        HorizontalOptions="Center" />
   </Grid>
   ```
3. Add a Button to the `MainPage` with a clicked event `await Navigation.PushAsync(new StyledPage());`
4. Add a Button to the `MainPage` with a clicked event `await Navigation.PushAsync(new UnstyledPage());`
5. Add a Button to the `MainPage` with a clicked event `GC.Collect();`

Testing
1. Run the app targeting Windows
2. Navigate to the `StyledPage`
3. Click the back button
4. Click the `GC Collect` button
5. Take a snapshot of the memory usage
6. Navigate to the `UnstyledPage`
7. Click the back button
8. Click the `GC Collect` button
9. Take a snapshot of the memory usage
10. Repeat as many times as necessary

Result: Looking at the memory usage snapshots the number of instances of `StyledPage` in memory increases with the number of times the page has been opened. 

![image](https://github.com/dotnet/maui/assets/99325835/df22eb34-c716-4beb-83b2-130d9c6ed137)

![image](https://github.com/dotnet/maui/assets/99325835/4e9b1bed-2c1f-433f-aef1-ec492a7fdcdb)

Expected: The page should no longer exist in memory after navigating away, the number of instances in memory should not increase as the page is repeatedly opened. This works correctly for the `UnstyledPage`.

### Link to public reproduction project repository

https://github.com/duffh/MauiStylesMemoryLeakTestApp

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by duffh** [comment]
Looks like the same issue to me, thanks for taking a look!

**Comment by jonathanpeppers** [comment]
I wasn't aware of this issue filed -- and I just happened to find the problem in another sample, thanks!
