### ISSUE TITLE
[MAUI]Text appears overlapping on RefreshView page.

### ISSUE THREAD

**Issue by Chloelong123** [dotnet/maui#15993]
### Description

Text appears overlapping on RefreshView page.

### Steps to Reproduce

1.Deploy to [ManualMauiTests - Repos (visualstudio.com)](https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests) iOS emulator/MacCatalyst.
2. Click "C RefreshView", then click "C3 Refreshview with ListView child".
3.View simulator

Actual results:
Text appears overlapping
![image](https://github.com/dotnet/maui/assets/109071485/b0abe0b3-c192-4a16-8004-9b7a73616ab3)

### Link to public reproduction project repository

[ManualMauiTests - Repos (visualstudio.com) 
](https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests)
### Version with bug

7.0.86

### Affected platforms

MacOS: iOS, MyMac (MacCatalyst).

### Affected platform versions

net ios 16.4.7067,net macos 13.3.7067

**Comment by jaosnz-rep** [comment]
C3 behaves differently on Android. The image is cut off and the location is not displayed. We think this is the same problem.
![image](https://github.com/dotnet/maui/assets/82628041/7d7baada-0f70-4c87-aa79-5176d9d4f76c)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.8 (build 400). Can repro on MacCatalyst platform with sample project. 
[ManualMauiTests - Repos (visualstudio.com)](https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests)

**Comment by jfversluis** [comment]
I acknowledge that this issue is older, but the linked issue has a bit more information on the different parameters that influence the behavior here and thus has more useful and actionable information.
