### ISSUE TITLE
FlexLayout Padding not working

### ISSUE THREAD

**Issue by muak** [dotnet/maui#15991]
### Description

Padding does not work in FlexLayout.
It works in Xamarin.Forms and was displayed correctly before migration to MAUI.
After MAUI migration, the layout is broken.

```xml
<VerticalStackLayout BackgroundColor="AliceBlue">
    <FlexLayout Direction="Column" Padding="16" BackgroundColor="LightGreen">
        <BoxView WidthRequest="40" HeightRequest="20" Color="Red"  />
        <BoxView WidthRequest="40" HeightRequest="20" Color="Blue" />
        <BoxView WidthRequest="40" HeightRequest="20" Color="Green"  />
        <BoxView WidthRequest="40" HeightRequest="20" Color="Yellow"/>
        <BoxView WidthRequest="40" HeightRequest="20" Color="Magenta"  />
        <BoxView WidthRequest="40" HeightRequest="20" Color="Black"  />
        <BoxView WidthRequest="40" HeightRequest="20" Color="Orange"  />
        <BoxView WidthRequest="40" HeightRequest="20" Color="GreenYellow"  />
    </FlexLayout>
</VerticalStackLayout>
```

<img src="https://github.com/dotnet/maui/assets/16084475/31a59dde-4964-4c5d-9fab-7c2224b448fb" width="320" /> <img src="https://github.com/dotnet/maui/assets/16084475/b6b8c112-d52e-4488-a524-39d5e36e13eb" width="320" />

### Steps to Reproduce

1. Put a FlexLayout with Padding.

### Link to public reproduction project repository

https://github.com/muak/FlexIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS15.4 / Android API33

### Did you find any workaround?

Set parent layout padding.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. Repro on Android 13.0-API33 and iOS 16.4 .NET 8 with below Project:
[FlexIssue.zip](https://github.com/dotnet/maui/files/12225951/FlexIssue.zip)

**Comment by bradencohen** [comment]
+1

**Comment by mikeysouthwell** [comment]
Also having the same issue. Having to use Margins instead of Padding as s workaround which isn't ideal.

Please fix this!

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               8.0.3/8.0.100          VS 17.8.34525.116
maccatalyst                17.2.8004/8.0.100      VS 17.8.34525.116
android                    34.0.43/8.0.100        VS 17.8.34525.116
ios                        17.2.8004/8.0.100      VS 17.8.34525.116

**Comment by PrathyushTaneti** [comment]
Please fix this bug.

**Comment by PabloRuiz-TT** [comment]
Este error sigue existiendo con net 8 y vs 2022 17.9.5

**Comment by mikeysouthwell** [comment]
Any update on this? Having something as simple as padding not work is a pretty big deal and is making our migration from Xamarin to MAUI very painful 😢

**Comment by hiroian** [comment]
Also waiting on a fix for this!

**Comment by rhodesie123** [comment]
I have the same issue!! When will this be fixed?!?!

**Comment by GirbyDev** [comment]
I have the same problem, I am migrating from xamarin to .NET Maoi and I am having problems with the padding in the FlexLayouts, even the margin does not work well either.
