### ISSUE TITLE
NU1202	Package Microsoft.Maui.Graphics 7.0.86 is not compatible with net7.0-android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#16009]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/10400856)._

---
Literally just created a new Maui program in 17.6.4 (and previous version), and I get a host of errors like this one:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.Maui.Graphics 7.0.86 is not compatible with net7.0-android33.0 (.NETCoreApp,Version=v7.0). Package Microsoft.Maui.Graphics 7.0.86 does not support any target frameworks.	MauiApp3	

---
#### Feedback Bot on 6/26/2023, 06:30 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
We are going to re-open the original issue that's already on vs-feedback

**Comment by samhouts** [comment]
Closing this, as the original feedback ticket is the tracking item now.
