### ISSUE TITLE
[ VS & .NET 8 ] MAUI Android/iOS causes error and can't be built, .csproj file can't be shown

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#16008]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/-VS--NET-8--MAUI-AndroidiOS-causes-/10400056)._

---
In latest VS (17.7.0 Preview 2) and .NET 8 (Preview 5), a MAUI project

(1) can't Compile on Android/iOS. Error:
     Error APT2260 resource mipmap/appicon (aka com.xy.fa:mipmap/appicon) not found.
     Error APT2260 resource mipmap/appicon_round (aka com.xy.fa:mipmap/appicon_round) not found.
     Error APT2067 failed processing manifest.

(2) the .csproj file can't be opened in VS GUI to modify the content. Error:
     System.ArgumentException: Expected 6 values for property IOSRule::MtouchSdkVersion, but got 2.

These problems exist since .NET 8. Please investigate the issues. Thanks.

---
#### Feedback Bot on 6/26/2023, 00:01 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Re-opened, issues on VS Feedback
