### ISSUE TITLE
[Bug] StackLayout.Spacing should be a bindable property

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#1600]
I've been examining the new `HorizontalStackLayout` and `VerticalStackLayout` classes. Both derive from a new `StackLayout` class which defines a `Spacing` property. After talking to EZ, it seems that the property should be a `BindableProperty`.

The original `StackLayout` class defaults its `Spacing` BP to 6.

**Comment by hartez** [comment]
> The original `StackLayout` class defaults its `Spacing` BP to 6.

And the new ones will _not_ be doing that :) 

They'll be using a default of zero, instead of an arbitrary value.
