### ISSUE TITLE
"playsinline" attribute not working in HTML5 video tag for iOS

### ISSUE THREAD

**Issue by ElliottBrand** [dotnet/maui#16013]
### Description

The MAUI WebView doesn't seem to be honoring the "playsinline" attribute for iOS apps. The iPhone's video player takes over and makes it full screen.

```html
<video playsinline webkit-playsinline muted autoplay src="some-video-link.mp4" controlslist="nodownload">
    Your browser does not support this video player.
</video>
```
Also, it works fine when viewing in a safari browser on the same phone outside of MAUI (Blazor WASM).

I'm using Visual Studio 16.7.4 and it looks like 7.0.304 sdk.

### Steps to Reproduce

1. Create a new MAUI Blazor app.
2. Add the HTML5 video tag I mentioned above to the index.razor file and reference a video in the src.
3. Launch it on an iPhone simulator or device with iOS 15. I'm testing with an iPhone 8 Plus model.

### Link to public reproduction project repository

[https://github.com/ElliottBrand/HTML5_MAUI_Issue_16013](https://github.com/ElliottBrand/HTML5_MAUI_Issue_16013)

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No.

**Comment by ElliottBrand** [comment]
The repo has been added to the original post.

**Comment by ElliottBrand** [comment]
I also tried adding the following to the MauiProgram.cs file (based on https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview?pivots=devices-ios#configure-the-native-webview-on-ios-and-mac-catalyst), with no luck:

```csharp
#if IOS || MACCATALYST
        var config = MauiWKWebView.CreateConfiguration();
        config.AllowsInlineMediaPlayback = true;
        WebViewHandler.PlatformViewFactory =
            handler => new MauiWKWebView(CGRect.Empty, (WebViewHandler)handler, config);
#endif
```

**Comment by ElliottBrand** [comment]
I figured out a way to get this working!  I ended up adding `BlazorWebViewInitializing="HandleWebViewInitializing"` to BlazorWebView in MainPage.xaml and the following method to MainPage.xaml.cs

```csharp
    private void HandleWebViewInitializing(object sender, BlazorWebViewInitializingEventArgs args)
    {
        // WebView needs the configuration updated during initialization in order for "playsinline" attributes 
        // to work in the HTML5 video player for iOS devices.
#if IOS || MACCATALYST
        args.Configuration.AllowsInlineMediaPlayback = true;
        args.Configuration.MediaPlaybackRequiresUserAction = false;
        args.Configuration.RequiresUserActionForMediaPlayback = false;
#endif
    }
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 6.0. Repro on iOS 16.4 .NET 7, but **not repro on iOS 16.4 .NET 8**, Windows 11 and Android 13.0-API33 with below Project:
[HTML5_MAUI_Issue_16013.zip](https://github.com/dotnet/maui/files/12237710/HTML5_MAUI_Issue_16013.zip)

![image](https://github.com/dotnet/maui/assets/97647558/27bd80f8-7fba-4087-82ff-abb517d1164b)
