### ISSUE TITLE
PlatformNotSupported exception on iOS Release build from DevOps pipeline

### ISSUE THREAD

**Issue by bsloehr** [dotnet/maui#16025]
### Description

When I build my app for iOS through an Azure DevOps pipeline and deploy it to an iPad the app with throw a PlatformNotSupported exception for certain third party nuget packages. At first it was with the Mopups package. I have opened an issue there on this [Mopups issue](https://github.com/LuckyDucko/Mopups/issues/70). But now the same behavior is happening with another third party party package. I am suspecting that there is something wrong or missing in my build script or something in the iOS linker is too aggressive or the compiler is not recognizing the platform directives? I have configured the project to use the interpreter, but no change in behavior.

Some interesting notes about the behavior observed:

1. The app can be built in the Debug configuration and functions properly. The build is done in Visual Studio 2022 17.6.4 and deployed to the iPad (iPadOS 16.5.1) through a paired MacBook Pro.
2. The app can be built in Release configuration using an AdHoc provisioning profile and it will function properly. Deployment is the same as above.
3. When the app is built through the pipeline and installed through TestFlight it fails. Deployment is through FastLane.
4. When the Mopups code is downloaded and referenced as a project in the app then is functions properly. Build and deployment is through the pipeline/Fastlane/TestFlight.
5. When the downloaded Mopups code is compiled locally into a nuget package and referenced in the project it functions properly.  Build and deployment is through the pipeline/Fastlane/TestFlight.

The azure-pipelines.yml file in the reproduction link details the commands used for the build.
 

### Steps to Reproduce

1. Download the project from the GitHub repro link
2. Build in Debug and deploy to iPad (or optionally in Release using an AdHoc provisioning profile)
3. Click the Pick List button, observe the popup
![MicrosoftTeams-image (20)](https://github.com/dotnet/maui/assets/4925076/9845a63f-7221-4e83-8cf7-11d5d8d7f57b)

4. Build project using the azure pipelines script and deploy to iPad
5. Click the Pick List button, observe the caught exception showing Arg_PlatformNotSupported message
![MicrosoftTeams-image (19)](https://github.com/dotnet/maui/assets/4925076/8710a0f3-6e13-41af-98dc-46a030b0e3b9)

### Link to public reproduction project repository

https://github.com/bsloehr/TestMopups

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16 and up

### Did you find any workaround?

Locally compiling Mopups got me past my first blocking issue but the second nuget package I am working with is a BLE package that is more complex and I'd rather not compile it locally if I don't have to.

**Comment by samhouts** [comment]
@rolfbjarne  any ideas?

**Comment by rolfbjarne** [comment]
A stack trace of the exception would likely be really useful, could you get that?

**Comment by bsloehr** [comment]
Sorry for the delay. I had to revive that build. It is no longer reproducible when compiled using 7.0.101.
