### ISSUE TITLE
[Bug] HorizontalStackLayout displays nothing

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#1602]
### Description

I've tried the `HorizontalStackLayout`:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp4.MainPage">
    <HorizontalStackLayout Margin="20">
        <Label Text="Red" />
        <BoxView Color="Red" />
    </HorizontalStackLayout>
</ContentPage>
```

Nothing is displayed on iOS/Android/Windows. Not even the BoxViews. Not the Labels. I tried registering the BoxView renderers myself, using `AddCompatibilityRenderer`, but it didn't help.

### Steps to Reproduce

1. Run the attached sample.

### Expected Behavior

Labels and BoxViews are displayed in a horizontal stack.

### Actual Behavior

Blank page.

### Basic Information

- Version with issue: 6.0.100-preview.5.794
- IDE: VS2019 16.11
- Platform Target Frameworks:
  - Android: 30
  - Win: net6.0-windows10.0.19041

### Reproduction Link

[MauiApp4.zip](https://github.com/dotnet/maui/files/6785749/MauiApp4.zip)

**Comment by hartez** [comment]
HSL issues are fixed in with the latest on P7. BoxView-specific issues are handled in #1923.
