### ISSUE TITLE
Issue with .NET MAUI in VS 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#16027]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Issue-with-NET-MAUI-in-VS-2022/10402110)._

---
[severity:It bothers me. A fix would be nice]
I have installed the .NET MAUI workload in Visual Studio Community 2022. However, I am not able to see this platform "MAUI" as an option when I want to create an app.

---
#### Feedback Bot on 6/27/2023, 08:26 PM: 

(private comment, text removed)
#### Lim Simon on 6/29/2023, 06:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by lambdageek** [comment]
I can't reproduce this.  I just tried a brand new install of VS 2022 17.6.4 Community edition on an x64 devbox, selected "Maui" in the installer (and did not select "Xamarin") then launched VS and searched for "MAUI" in the new project template dialog - it was there.

**Comment by drasticactions** [comment]
My guess would be that the MAUI Workload wasn't installed by the VS Installer, so it's missing on their system?

**Comment by mattleibow** [comment]
I think this was an issue with installing templates and multiple versions of workloads and IDE. Hopefully this is no longer happening. If it is, then we need a new IDE ticket.
