### ISSUE TITLE
DatePicker runtime error during DateSelected event

### ISSUE THREAD

**Issue by chsakell** [dotnet/maui#16022]
### Description

`DateSelected` event breaks the app when a date is selected and press OK. The event of course not firing properly.

![Screenshot 2023-07-06 135158](https://github.com/dotnet/maui/assets/7770797/ddca870f-588e-494a-b2f3-f29974ff9b68)

### Steps to Reproduce

1. Create a DatePicker control in a Xaml page ` <DatePicker DateSelected="DatePicker_DateSelected" />`
2. Optionally set dates, it doesn't matter. 
3. Select a date and press OK. 

The result is to get a `Break Mode` tab saying **No compatible code running on the thread**

### Link to public reproduction project repository

https://github.com/chsakell/DatePickerApp

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 6.0. This issue does not repro on Android 13.0-API33 .NET 8, Windows 11 and iOS 16.4 with below Project:
[DatePickerApp.zip](https://github.com/dotnet/maui/files/12238599/DatePickerApp.zip)
![DataPicker](https://github.com/dotnet/maui/assets/97647558/a5e39674-6d7e-439c-973b-8da267e4f736)
