### ISSUE TITLE
Binding CollectionView/CarouselView to lists of primitive types doesn't work on Release Builds

### ISSUE THREAD

**Issue by stefanpirkl** [dotnet/maui#16021]
### Description

A CollectionView/CarouselView bound to an IList with primitive types doesn't render items on release builds.

Tested on Windows and Android, both don't work.

Debug:
![image](https://github.com/dotnet/maui/assets/81682730/ff0e2f8a-3cad-4ae8-915b-36483a3a9cae)

Release:
![image](https://github.com/dotnet/maui/assets/81682730/43597991-21dd-491a-b2ee-d7499f267977)

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Add a view model with a list property of type List<string> and some elements:
`    internal class MainPageViewModel : BindableObject
    {
        private IList<string> _items = new List<string> { "first value", "second value", "third value" };

        public IList<string> Items
        {
            get { return _items; }
            set { _items = value; OnPropertyChanged(nameof(Items)); }
        }
    }`
3. Bind the view model to MainPage.xaml.cs:
` public partial class MainPage : ContentPage
    {
        MainPageViewModel viewModel = new MainPageViewModel();

        public MainPage()
        {
            InitializeComponent();

            BindingContext = viewModel;
        }
    }`
4. Add a CollectionView to MainPage.xaml, bound to the list in MainPageViewModel:
`			<CollectionView ItemsSource="{Binding Items}">
				<CollectionView.ItemTemplate>
					<DataTemplate>
						<Label Text="{Binding}" />
					</DataTemplate>
				</CollectionView.ItemTemplate>
			</CollectionView>
`
5. Do a release build, observe that nothing is rendered.

### Link to public reproduction project repository

https://github.com/stefanpirkl/bugreport-maui-collectionview-primitive-list-on-release

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10, Android 9 and up

### Did you find any workaround?

Changing the List<string> to a custom model class with a single string property in it.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 6.0. Repro on Windows 11 and Android 13.0-API33 .NET 8 with below Project:
[CollectionViewBinding.zip](https://github.com/dotnet/maui/files/12238371/CollectionViewBinding.zip)

**Comment by IsmailHassani** [comment]
I've encountered the same issue with Release build.  
It has to do with the issue #17515 that states you have to specify the x:DataType to fix the binding. 
For strings i use: 
```<DataTemplate x:DataType="x:String">```

**Comment by stefanpirkl** [comment]
> I've encountered the same issue with Release build. It has to do with the issue #20002 that states you have to specify the x:DataType to fix the binding. For strings i use: `<DataTemplate x:DataType="x:String">`

Wow, thank you! This did really fix it.
