### ISSUE TITLE
KeyboardEventArgs attributes Code is "" and Key is "Undefined" on mobile Android.

### ISSUE THREAD

**Issue by CarterBoyd** [dotnet/maui#16030]
### Description

When working with a text area with Maui Blazor the keyboardEventArgs does not register any keys on an android. under windows and iOS the Code and Key will show what letter is pressed but not with Android.

### Steps to Reproduce

1. Create .NET MAUI Blazor App
2. Keep Framework .NET 7.0
3. Create a textarea in a .razor file
4. In the textarea create a @onkeydown="function" this will be the bug function
5. Create the function and set the parameter as KeyboardEventArgs e
6. Run a debug through Android, breakpoint inside the function or make a WriteLine to print e.Key & e.Code
7. hover over the variable and it will show "" for Code and "Undefined" for Key or look at console output

### Link to public reproduction project repository

https://github.com/CarterBoyd/KeyboardEventArgs-Android-Issue

### Version with bug

7.0.81

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android version 13

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 6.0. Repro on Android 13.0-API33 .NET 8, not repro on Windows 11 and iOS 16.4 with below Project:
[16030.zip](https://github.com/dotnet/maui/files/12246164/16030.zip)

Android:
![image](https://github.com/dotnet/maui/assets/97647558/44fbb86a-e2cd-4da2-9432-3aaaa51d9c29)

**Comment by Eilon** [comment]
I just tried this now with the provided repro project and using an Android 13 (API 33) emulator and it worked:

![image](https://github.com/dotnet/maui/assets/202643/c4e32016-2949-475c-94da-a7fbb6cfdf05)

I also tried with .NET MAUI 8 on Android 13 (API 33) and Android 14 (API 34) and also couldn't repro it.

So it could be that there was some bug in earlier .NET MAUI 7 previews but it's now gone. As such, I am closing this issue. If anyone can repro in .NET 8 please let us know.
