### ISSUE TITLE
Enable Remoteable Blazor UI 

### ISSUE THREAD

**Issue by budcribar** [dotnet/maui#1603]
Hi @Eilon,

I have built a demo based on the work that @jspuij  did in creating BlazorWebView which allows the user interface to be accessed through a web server. For example, a customer who is running a diagnostic program behind a firewall could allow service personnel to control the program remotely  without giving up full access to the customer's computer. There are some other IOT scenarios that could be easily enabled with this technology which would make it useful.

My code is in the following repositories

https://github.com/budcribar/RemoteBlazorWebViewTutorial
and
https://github.com/budcribar/RemoteBlazorWebView

There were minimal changes required in the BlazorWebView to support this capability and would like to propose making similar changes to the MobileBlazorBindings project. Please check out the repositories and let me know what you think. We could also schedule an online meeting and I could give you a demo.
thanks,
@budcribar

**Comment by Eilon** [comment]
I moved this issue to the .NET MAUI repo, where most of the Blazor WebView code is located.

@budcribar I think I understand the basic idea of this and the changes you suggest above seem reasonable even outside of this remoting scenario. Would you like to send a PR to this repo to make some changes to the WPF/WinForms/MAUI controls? (The MAUI stuff might be more difficult, so feel free to ignore that for now and I will do it later.)
