### ISSUE TITLE
Building AdHoc iOS in Release does not ask for permissions on device

### ISSUE THREAD

**Issue by gktval** [dotnet/maui#16034]
### Description

I'm not sure if I am doing something wrong or this is a bug since I have never built for iOS before. When debugging, the app asks for permissions to use storage and to use location. However, when I build the app in Release mode, published it to the Apple Store, then downloaded it via TestFlight, the app does not ask for permissions. When I go into settings, I do not see any permissions available for the app.

I wonder if the info.plist is not getting built in the app.ipa file (but I am unsure how to check). Perhaps someone knows off the top what I might be doing wrong or if this is a bug somehow.

### Steps to Reproduce

Build the iOS app that requires storage permissions in Release mode.
Archive it and publish it AdHoc to the play store.
Download it via TestFlight.

### Link to public reproduction project repository

na

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 14+

**Comment by AndreasReitberger** [comment]
This could be due to the `Linker`. It removes all unnecessary stuff from your application once you built it in `Release` mode and if enabled.
Or do you have a specific use case for the `Location` or `Storage` permission?

**Comment by gktval** [comment]
Closing this because it was more crashing on json serializer (and never made it to permissions) and needed UseInterpreter which is already an issue elsewhere.
