### ISSUE TITLE
MAUI sdk should default the JsonSerializerIsReflectionEnabledByDefault property to true

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/maui#16038]
We are about to merge https://github.com/dotnet/runtime/pull/88480 which once active will turn off System.Text.Json reflection-based serialization for projects with `PublishTrimmed=true`. Projects that use both trimming and reflection serialization will need to explicitly set the  `JsonSerializerIsReflectionEnabledByDefault` property to `true`.  For reference, [here's the PR](https://github.com/dotnet/sdk/pull/31909) enabling this for blazor wasm targets.

**Comment by akoeplinger** [comment]
I wonder if this should be set at the iOS/Android SDK level rather than MAUI since it'll affect those projects as well.

/cc @Redth

**Comment by akoeplinger** [comment]
Just noticed that we probably don't want this for the NativeAOT iOS scenario since it should disable reflection there.

**Comment by jonathanpeppers** [comment]
@rolfbjarne can you do the xamarin-macios side of this?

We should also add a runtime/on-device test that does something like `System.Text.Json.JsonSerializer.Serialize(42)` or a basic `.json` blob.

**Comment by rolfbjarne** [comment]
> @rolfbjarne can you do the xamarin-macios side of this?
> 
> We should also add a runtime/on-device test that does something like `System.Text.Json.JsonSerializer.Serialize(42)` or a basic `.json` blob.

Sure, tracked here: https://github.com/xamarin/xamarin-macios/issues/18057
