### ISSUE TITLE
Basic stuff must work in maui preview 6 

### ISSUE THREAD

**Issue by gabsamples6** [dotnet/maui#16036]
### Description

Hi,
@davidortinau @Redth 
Unfortunately working with Maui is very rough ride!! 
Because you are no longer fixing .net 7 we want to move to preview where you claim some basic stuff has finally been fixed (i.e keyboard issues - line breaks and gestures not firing)

We would very much appreciate if you could make sure that below works before shipping, without this is a pure nightmare.

- **Cannot Debug iOS physical device** .Using windows host - iOS physical device can you debug and hot restart? Broken since preview 4
   https://github.com/dotnet/maui/issues/15564#issuecomment-1620807237
- **Can you successfully deploy and successfully build a Maui app** both iOS and android in Azure pipeline- Currently is broken.
  I dont have a link but our pipeline got all sorts of errors.Also its been reported that they are issues with publishing
  https://github.com/dotnet/maui/issues/15973 - I have seen other links on this one
- **Can you fix Maui Release binding** - true nightmare this one in .net 7 - Looks good in debug than release the app and crashes or page looks strange and all because  release binding does not bind viewmodel - Workaround - to each xaml.cs page add Attribute -compilation.Skip  see url https://www.banditoth.net/2023/06/08/net-maui-ios-bug-release-mode-bindings-not-working/   and this I believe is related https://github.com/dotnet/maui/issues/16021
- Grid - the most important control - Layout, we have some odd issues with grid layout - I will put a repo together was not working with "*,Auto" at times.. 
- Borders cutting of images - Please this one is driving us nuts in .net 7. Is this fixed? every page in the app looks bad because of border cutting off in iOS.  https://github.com/dotnet/maui/issues/15794

**1 wish item**

Can we have Lottie working? Does not work in windows host - pop ups - or when using a service provider - seen few people raising the issue on twitter Why important? it helps selling the app. @mattleibow 
When doing demos to clients and we have a bit of lottie here and there it goes a long way to have a "wow" factor... silly hey  but makes a massive different in a sale.

I guess the team is stretched out and not sure what the answer is but above is just the Minimum to have to release a maui  app in the real world

### Steps to Reproduce

See description above with links

### Link to public reproduction project repository

n/a

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

iOS, Android

### Affected platform versions

VS 2022 any version

### Did you find any workaround?

For some we have dodgy workaround

**Comment by jfversluis** [comment]
@gabsamples6 I appreciate the concerns here, but opening an issue that links to issues that are already open is not going speed things up. Now we have to spend time looking at this issue too, which is time we can't spend on the other issues at hand 😉  I appreciate that these are the ones that are important to you, we're doing everything we can to make .NET 8 the best experience for you and everyone.

For the existing issues, please add all relevant (new) information in each respective bug and if you find something new, please open 1 issue per potential bug, as has happened with the issues you link here. This will make sure that they all stay actionable, we can easily track and prioritize and we don't clutter our list of issues that have a high risk of lingering around.

Thanks for understanding!

**Comment by gabsamples6** [comment]
@jfversluis  I appreciate and agree with what you are  saying but we are in desperate mode now.. nothing simple works!  I dont want to go on a rant mode but there is no feedback or blog or whatever of what is being actually fixed. 

you stopped fixing .net 7 - telling us to move to .net 8 preview  and then we cannot - debug - deploy -release 
What are we suppose to do ?

I can close this ticket if you want me to- silence does not help ..

**Comment by jfversluis** [comment]
We have not stopped fixing .NET 7, we're bringing over the minimum to reduce the risk on regressions so we can focus even more attention on .NET 8.

If you want to know what is fixed, you can following along the [PRs](https://github.com/dotnet/maui/pulls) and [commits](https://github.com/dotnet/maui/commits/main) as they are being merged in this repo. Furthermore, for each release that we do, there is a corresponding release on the [Releases page](https://github.com/dotnet/maui/releases) that lists exactly what has been merged.

**Comment by gabsamples6** [comment]
ok , I know where PRs and commits are and the release page is .. but please see it from the other side , its very very difficult to have a real app work in maui as basic stuff just does not work without searching all possible workarounds. 

and regarding fixing .net 7 - I understand what you are doing it but  we are still very much in a bad place for a production app.
and David saying rightly we are concentrating on .net 8 and we go there and we cannot debug or release etc..

anyway - thanks for your time - not the answer I was hoping
