### ISSUE TITLE
[Documentation] Frame IsClippedToBounds Property Default Value

### ISSUE THREAD

**Issue by tj-devel709** [dotnet/maui#16044]
Hi, I'm creating this issue based on this issue here: https://github.com/dotnet/maui/pull/15894.

The default behavior of IsClippedToBounds on Frame has an implicit "true" value when not set and it can be not clear for some users. 

On Android, the default property is `IsClippedToBounds = CornerRadius > 0f` 
and on iOS, the default property is `IsClippedToBounds = true`

While these are different, they will essentially both clip if there is some corner radius set and when there is no corner radius set, we do not really care if we are clipping or not as it won't make a visual difference.

Small example of the behaviors on iOS and Android currently where there is a corner radius applied to each shape:

<img height="500" alt="Screenshot 2023-07-05 at 6 08 55 PM" src="https://github.com/dotnet/maui/assets/50846373/1325af1a-7c92-426e-be7c-9114715d6eac">
<img height="500" alt="Screenshot 2023-07-05 at 6 10 17 PM" src="https://github.com/dotnet/maui/assets/50846373/79e87ffe-b6dc-4188-837a-7245f6c6fab0">

**Comment by jsuarezruiz** [comment]
Could we align the behavior between platforms?
