### ISSUE TITLE
Including specific android libraries via nuget causes AOT failures on RELEASE build

### ISSUE THREAD

**Issue by Ball** [dotnet/maui#16074]
### Description

Including Android Material 1.8.0 to match vendor native android library causes release builds to fail to AOT Microsoft.MAUI.Controls.dll.

### Steps to Reproduce

Import Xamarin.Google.Android.Material 1.8.0

Build MAUI project to Release.

### Link to public reproduction project repository

https://github.com/Ball/MAUIBugReprot-AndroidIncludesAOTBug

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

net7.0-android

### Relevant log output

```shell
[Microsoft.Maui.Controls.dll] Exec (with response file contents expanded) in /Users/ball/Projects/temp-crap/AndroidIncludesAOTBug/AndroidIncludesAOTBug: MONO_PATH=/Users/ball/Projects/temp-crap/AndroidIncludesAOTBug/AndroidIncludesAOTBug/obj/Release/net7.0-android/android-x64/linked: MONO_ENV_OPTIONS= /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.android-x64/7.0.8/Sdk/../tools/mono-aot-cross --debug --nollvm "--aot=asmwriter,temp-path=obj/Release/net7.0-android/android-x64/aot/x86_64/Microsoft.Maui.Controls,profile-only,profile=/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/7.0.86/Sdk/maui.aotprofile,profile=/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/7.0.86/Sdk/maui-blazor.aotprofile,mtriple=x86_64-linux-android,tool-prefix=/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Darwin/binutils/bin/x86_64-linux-android-,outfile=obj/Release/net7.0-android/android-x64/aot/Microsoft.Maui.Controls.dll.so,ld-name=ld,ld-flags=--no-relax -s" "obj/Release/net7.0-android/android-x64/linked/Microsoft.Maui.Controls.dll"
            
            /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/targets/Microsoft.Android.Sdk.Aot.targets(91,5): error : Precompiling failed for /Users/ball/Projects/temp-crap/AndroidIncludesAOTBug/AndroidIncludesAOTBug/obj/Release/net7.0-android/android-x64/linked/Microsoft.Maui.Controls.dll with exit code 1.
            /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/targets/Microsoft.Android.Sdk.Aot.targets(91,5): error : Failed to load method 0x6002df6 from '/Users/ball/Projects/temp-crap/AndroidIncludesAOTBug/AndroidIncludesAOTBug/obj/Release/net7.0-android/android-x64/linked/Microsoft.Maui.Controls.dll' due to Could not resolve type with token 01000245 from typeref (expected class 'AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper' in assembly 'Xamarin.AndroidX.AppCompat.AppCompatResources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Xamarin.AndroidX.AppCompat.AppCompatResources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper member:(null).
            /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/targets/Microsoft.Android.Sdk.Aot.targets(91,5): error : Run with MONO_LOG_LEVEL=debug for more information.
            /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/targets/Microsoft.Android.Sdk.Aot.targets(91,5): error : AOT of image obj/Release/net7.0-android/android-x64/linked/Microsoft.Maui.Controls.dll failed.
            /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/targets/Microsoft.Android.Sdk.Aot.targets(91,5): error : Mono Ahead of Time compiler - compiling assembly /Users/ball/Projects/temp-crap/AndroidIncludesAOTBug/AndroidIncludesAOTBug/obj/Release/net7.0-android/android-x64/linked/Microsoft.Maui.Controls.dll
            /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/targets/Microsoft.Android.Sdk.Aot.targets(91,5): error : AOTID CC96FD86-66AF-C4AE-30D7-A2112B3DA00A
            /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/targets/Microsoft.Android.Sdk.Aot.targets(91,5): error : Using profile data file '/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/7.0.86/Sdk/maui.aotprofile'
            /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/targets/Microsoft.Android.Sdk.Aot.targets(91,5): error : Using profile data file '/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/7.0.86/Sdk/maui-blazor.aotprofile'
```

**Comment by mattleibow** [comment]
Can you attach a binlog? 

See this for how: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

**Comment by mattleibow** [comment]
@jonathanpeppers  thoughts?

**Comment by Ball** [comment]
[output.binlog.zip](https://github.com/dotnet/maui/files/12018599/output.binlog.zip)

**Comment by jonathanpeppers** [comment]
@jpobst @moljac could the latest `Xamarin.Google.Android.Material` package be missing a dependency to `Xamarin.AndroidX.AppCompat.AppCompatResources`?

And then somehow everything works in Debug mode, but the AOT compiler fails in Release?

**Comment by jpobst** [comment]
Google renamed the `DrawableWrapper` type to `DrawableWrapperCompat` in one of their updates:
https://github.com/xamarin/AndroidX/issues/690#issuecomment-1414325720

If MAUI uses that type directly, it may be the same issue that XF had:
https://github.com/xamarin/Xamarin.Forms/issues/15668

That is, MAUI would be expecting `DrawableWrapper` while the user-upgraded NuGet package is providing `DrawableWrapperCompat`.

If this is the case, MAUI will need to update its AndroidX before users will be able to.

**Comment by jonathanpeppers** [comment]
.NET 8 MAUI has the new one:
* https://github.com/dotnet/maui/blob/net8.0/eng/AndroidX.targets

.NET 7 actually looks like it has Xamarin.Google.Android.Material 1.7.0:
* https://github.com/dotnet/maui/blob/net7.0/eng/AndroidX.targets

@Ball so another option is to try .NET 8?

**Comment by moljac** [comment]
> @jpobst @moljac could the latest `Xamarin.Google.Android.Material` package be missing a dependency to `Xamarin.AndroidX.AppCompat.AppCompatResources`?

https://www.nuget.org/packages/Xamarin.Google.Android.Material/1.9.0.1#dependencies-body-tab
https://www.nuget.org/packages/Xamarin.AndroidX.AppCompat/1.6.1.2#dependencies-body-tab
https://www.nuget.org/packages/Xamarin.AndroidX.AppCompat.AppCompatResources/1.6.1.2

> And then somehow everything works in Debug mode, but the AOT compiler fails in Release?

I see Pobst did answer in detail typename change.

**Comment by moljac** [comment]
> .NET 8 MAUI has the new one:
> 
> * https://github.com/dotnet/maui/blob/net8.0/eng/AndroidX.targets

Yes I added the newest few weeks ago. Seems like I need to add it to net7.0 (main) ASAP

**Comment by moljac** [comment]
2 PRs created 2 ("alignment" PRs)

- AX
   https://github.com/xamarin/AndroidX/pull/759
- GPS-FB-MLKit
   https://github.com/xamarin/GooglePlayServicesComponents/pull/794
   
I am going to create 2 PRs with nuget updates for MAUI `net7.0`/`main` and `net8.0` branches.

**Comment by pulmuone** [comment]
https://github.com/sasa-bobic/Xamarin.AndroidX.AppCompat.AppCompatResources
I solved it with this content.
