### ISSUE TITLE
Azure Pipelines Fails in the Restore Nuget Step on the solution when the solution has a Test project associated with it.

### ISSUE THREAD

**Issue by ataparia** [dotnet/maui#16075]
### Description

Hi Team,
I am trying to implement CI/CD pipeline for our MAUI project. The MAUI solution has a unit test project associated with it.
During the Nuget restore step of the pipeline which looks like this:
- task: CmdLine@2
          displayName: Restore nuget
          inputs:            
            script: |
              dotnet restore '$(SOLUTION_PATH)'

the pipeline fails with the following output message:
1. error NETSDK1147: To build this project, the following workloads must be installed: maui-tizen
2. error NETSDK1147: To install these workloads, run the following command: dotnet workload restore

The strange thing is that I have already downloaded the maui-tizen workload as a prerequisite to the Restore Nuget Step which looks like this:
# Step 1 : Install .NET MAUI            
        - task: Bash@3
          displayName: Install .NET MAUI
          inputs:
            targetType: inline
            script: |
                dotnet nuget locals all --clear 
                dotnet workload install maui #--source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
                dotnet workload install maui-android maui-ios maui-tizen #android ios maccatalyst macos maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

Also, none of my projects support Tizen framework. So why is this that I have to install tizen framework for the nuget restore step to pass on my test project. 

### Steps to Reproduce

1. Create a azure devops pipeline 
2. Triggered the pipeline

Expected Behavior - Pipeline should pass
Actual Behavior - Pipeline fails on the Nuget Restore step with the following message

1. error NETSDK1147: To build this project, the following workloads must be installed: maui-tizen
2. error NETSDK1147: To install these workloads, run the following command: dotnet workload restore

### Link to public reproduction project repository

https://github.com/ataparia/MAUIAzurePipelineCI.git

Private Repo

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

NA as the issue is happening on the Restore Nuget step

**Comment by drasticactions** [comment]
Without knowing the full context of what you have set up, it's hard to know what could be at fault: It could be something specific to how the MAUI workload is set up, or the SDK tooling, or AzDo, or whatever Unit Test framework you're using. If you could set up a repro project with what you have set up, that could help diagnose it.

(You don't have to deploy it to Devops, but a simple repo of the YAML you have set up could help too)

**Comment by JohnHSE** [comment]
I believe Ive seen this issue, I resolved it by upgrading the nuget version on the pipeline iirc.

**Comment by ataparia** [comment]
Hi @JohnHSE, Thank you for the response. Are you talking about upgrading nuget package manager or the actual nuget packages referenced by my project?

**Comment by ataparia** [comment]
> Without knowing the full context of what you have set up, it's hard to know what could be at fault: It could be something specific to how the MAUI workload is set up, or the SDK tooling, or AzDo, or whatever Unit Test framework you're using. If you could set up a repro project with what you have set up, that could help diagnose it.
> 
> (You don't have to deploy it to Devops, but a simple repo of the YAML you have set up could help too)

Hi @drasticactions, I have put in the code to a github repository which should be accessible to you guys.
https://github.com/ataparia/MAUIAzurePipelineCI.git

**Comment by JohnHDev** [comment]
> Hi @JohnHSE, Thank you for the response. Are you talking about upgrading nuget package manager or the actual nuget packages referenced by my project?

I was referring to the nuget package manager, Ive checked my pipeline and I was wrong, I no longer update, apologies.

Are you using a macos-12 build image?
Im installing Maui with this:
    sudo dotnet workload install maui

**Comment by ataparia** [comment]
> > Hi @JohnHSE, Thank you for the response. Are you talking about upgrading nuget package manager or the actual nuget packages referenced by my project?
> 
> I was referring to the nuget package manager, Ive checked my pipeline and I was wrong, I no longer update, apologies.
> 
> Are you using a macos-12 build image? Im installing Maui with this: sudo dotnet workload install maui

Hi @JohnHDev , I am not using macos-12 build image. I am using 'windows-latest' which has .net maui installed as per this article. https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

**Comment by ataparia** [comment]
> > > > Hi @JohnHSE, Thank you for the response. Are you talking about upgrading nuget package manager or the actual nuget packages referenced by my project?
> > > 
> > > 
> > > I was referring to the nuget package manager, Ive checked my pipeline and I was wrong, I no longer update, apologies.
> > > Are you using a macos-12 build image? Im installing Maui with this: sudo dotnet workload install maui
> > 
> > 
> > Hi @JohnHDev , I am not using macos-12 build image. I am using 'windows-latest' which has .net maui installed as per this article. https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
> 
> You can't build iOS on that, you need a Mac host.
Hi @JohnHDev,
Yes, totally understand that I cannot build iOS on Windows-latest server. I have given up on iOS build for now as the latest maui -ios build requires xcode 14.3/14.4 and even macos-latest doesnt have that version of xcode.
Right now, my focus is to get my windows and android build up and running and seems like I can't even build them let alone sign and package.

**Comment by mattleibow** [comment]
I just tested with a plain dotnet restore and then a dotnet build and it works for me: https://dev.azure.com/mattleibow/OpenSource/_build/results?buildId=670&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=036ed663-514a-59f3-0c88-23d2cf182147

I am seeing a bunch of variables in your pipeline - especially this one: `$(DOT_NET_VERSION)`

What version are you installing? When you install a version of the .NET SDK that was not previously installed, the workloads do not automatically carry over. For example, if you install maui for .net 7 (typical CI image) and then install net 8 - the net 8 maui workloads must also be installed.

The error about the missing `maui-tizen` is more of a red herring but still a sign. That workload is just the first one that the build detects is missing. It is a bit confusing and the SDK team is working to make this message better, but it basically means you installed a new sdk and the workloads were not there.

After installing the new sdk, i would then also run a `dotnet workload install maui` as the next step.

**Comment by ataparia** [comment]
> I just tested with a plain dotnet restore and then a dotnet build and it works for me: https://dev.azure.com/mattleibow/OpenSource/_build/results?buildId=670&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=036ed663-514a-59f3-0c88-23d2cf182147
> 
> I am seeing a bunch of variables in your pipeline - especially this one: `$(DOT_NET_VERSION)`
> 
> What version are you installing? When you install a version of the .NET SDK that was not previously installed, the workloads do not automatically carry over. For example, if you install maui for .net 7 (typical CI image) and then install net 8 - the net 8 maui workloads must also be installed.
> 
> The error about the missing `maui-tizen` is more of a red herring but still a sign. That workload is just the first one that the build detects is missing. It is a bit confusing and the SDK team is working to make this message better, but it basically means you installed a new sdk and the workloads were not there.
> 
> After installing the new sdk, i would then also run a `dotnet workload install maui` as the next step.

Hi @mattleibow , the value for the DOT_NET_VERSION is 7.0.x
Also does running dotnet workload install maui install everything i.e. maui-ios, maui-android or do I have to run the following command as suggested in https://github.com/dotnet/maui-samples/blob/main/7.0/Apps/WeatherTwentyOne/devops/AzureDevOps/azdo_windows.yml which is

- task: Bash@3
      displayName: Install MAUI
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear 
          dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json

**Comment by ataparia** [comment]
> > I just tested with a plain dotnet restore and then a dotnet build and it works for me: https://dev.azure.com/mattleibow/OpenSource/_build/results?buildId=670&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=036ed663-514a-59f3-0c88-23d2cf182147
> > I am seeing a bunch of variables in your pipeline - especially this one: `$(DOT_NET_VERSION)`
> > What version are you installing? When you install a version of the .NET SDK that was not previously installed, the workloads do not automatically carry over. For example, if you install maui for .net 7 (typical CI image) and then install net 8 - the net 8 maui workloads must also be installed.
> > The error about the missing `maui-tizen` is more of a red herring but still a sign. That workload is just the first one that the build detects is missing. It is a bit confusing and the SDK team is working to make this message better, but it basically means you installed a new sdk and the workloads were not there.
> > After installing the new sdk, i would then also run a `dotnet workload install maui` as the next step.
> 
> Hi @mattleibow , the value for the DOT_NET_VERSION is 7.0.x Also does running dotnet workload install maui install everything i.e. maui-ios, maui-android or do I have to run the following command as suggested in https://github.com/dotnet/maui-samples/blob/main/7.0/Apps/WeatherTwentyOne/devops/AzureDevOps/azdo_windows.yml which is
> 
> * task: Bash@3
>   displayName: Install MAUI
>   inputs:
>   targetType: 'inline'
>   script: |
>   dotnet nuget locals all --clear
>   dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
>   dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
> 
> Another thing that I noticed in the output of the job window where it errors our running the Build process for Windows is the following: C:\Program Files\dotnet\sdk\6.0.411\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maui-windows [D:\a\1\s\Infor.PublicSector.Mobile.Core\Infor.PublicSector.Mobile.Core.csproj]
> 
> Notice how the patch is going to dotnet\sdk\6.0.411 although I have installed 7.0.x version before running the build step.
> 
> Having said that, I do see that the .NET SDK version installed as part of my pipeline is 7.0.306
> 
> Also, can you share your .yml file. I need to see what changes you have made to my .yml file for it to run. I cannot access it on the azuredevops repo

Happy to report that I got the pipeline working on my end as well.
The actual issue was that I was trying to save time by only running the Install MAUI Workload task once for both Windows and Android by defining the "pool" on the Stage and then defining Jobs under that "Stage" but seems like the jobs needs their own "pool" and vmImage setting for this to work.

Closing this issue for now as I am up and running.

**Comment by ataparia** [comment]
Got it working. See previous comment on why it was not working.
