### ISSUE TITLE
[Bug] Maui-ified Android Gallery doesn't layout correctly

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1607]
### Description

Android Legacy Control Gallery home page is currently blank

![image](https://user-images.githubusercontent.com/5375137/165134442-25a6c1ba-3ef3-4d09-b0ed-2014ee05e935.png)

**Comment by jinxinjuan** [comment]
We verified this issue using this sample project <https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/ControlGallery> with Visual Studio Enterprise 17.6.0 Preview 2.0. Not repro it, however not sure if it is expected?

**Comment by jfversluis** [comment]
I think this is outdated and we're getting rid of this project anyway.
