### ISSUE TITLE
Add support for WiX Toolset Harvest Tool (Heat) HarvestProject element

### ISSUE THREAD

**Issue by jeremy-visionaid** [dotnet/maui#16096]
### Description

I would like to be able to havest the necessary project files for building a Microsoft Software Installer (MSI) using the WiX Toolset `HarvestProject` element

### Public API Changes

The msbuild project should expose the `BuiltProjectOutputGroup` target

### Intended Use-Case

To create an MSI without needing to individually specify all the required files, or harvest a directory which might contain unnecessary/unwanted files.

**Comment by jeremy-visionaid** [comment]
Also related/relevant to #10564

**Comment by rachelkang** [comment]
Hi, @jeremy-visionaid - did you try unpackaged? Also, can you attach a repro so we can better understand your use case?

**Comment by jeremy-visionaid** [comment]
@rachelkang This only applies to unpackaged anyway since the output is an MSI. My understanding is that `BuiltProjectOutputGroup` should be a common MSBuild target (i.e. from Microsoft.Common.CurrentVersion.targets), but WiX is current;y unable to find it when referencing a MAUI project:

```error MSB4057: The target "BuiltProjectOutputGroup" does not exist in the project```

This could actually just be a WiX bug, since HarvestProject looks a bit broken in v4.0.1 at the moment (other project types have different errors). Nonetheless, I feel like this kind of stuff should just work. In the meantime I'll go with `HarvestDirectory` and fix it up with XSLT. I'll add a repro if I get the chance.

**Comment by mattleibow** [comment]
This does sound more like a WIX issue than a MAUI issue. But this may also be because a maui app has multiple TFMs, so you may need to condition things to a specific TFM and not the top-level project.
