### ISSUE TITLE
.NET 8.0 Preview 6 - Cant build/start Android project from VS for Mac 15.6.1 or CLI

### ISSUE THREAD

**Issue by Pastajello** [dotnet/maui#16099]
### Description

Hello,

In .net 6/7 I was able to start the application from VS or CLI. With .net 8 Im able to only do it in iOS.

### Steps to Reproduce

Just create a new maui project from VS for mac 15.6.1 or CLI with 'dotnet new maui'.

### Link to public reproduction project repository

its a inbuilt template so no repo

### Version with bug

8.0.0-preview.6.8686

### Last version that worked well

7.0.86

### Affected platforms

Android

### Affected platform versions

Android 

### Did you find any workaround?

no

### Relevant log output

```shell
/Users/mer/Projects/maui8/maui8/obj/Debug/net8.0-android/android/src/crc6477f0d89a9cfd64b1/FormsAppCompatActivity.java(8,8): Error JAVAC0000:  error: cannot access LifecycleOwner
public class FormsAppCompatActivity
  class file for androidx.lifecycle.LifecycleOwner not found
 (JAVAC0000) (maui8) javac

/Users/mer/Projects/maui8/maui8/obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(102,102): Error JAVAC0000:  error: cannot find symbol
	public MultiPageFragmentStateAdapter_1 (androidx.fragment.app.FragmentManager p0, androidx.lifecycle.Lifecycle p1)
  symbol:   class Lifecycle
  location: package androidx.lifecycle
 (JAVAC0000) (maui8) javac
 
 Additionally:

% dotnet --list-sdks
6.0.412 [/usr/local/share/dotnet/sdk]
7.0.304 [/usr/local/share/dotnet/sdk]
7.0.306 [/usr/local/share/dotnet/sdk]
8.0.100-preview.6.23330.14 [/usr/local/share/dotnet/sdk]

dotnet workload list
Installed Workload Id Manifest Version Installation Source

wasi-experimental 8.0.0-preview.6.23329.7/8.0.100-preview.6 SDK 8.0.100-preview.6
ios 16.4.8646-net8-p6/8.0.100-preview.6 SDK 8.0.100-preview.6
maui 8.0.0-preview.6.8686/8.0.100-preview.6 SDK 8.0.100-preview.6
```

**Comment by jfversluis** [comment]
What is the command that you are using to start it? Are you on Mac or Windows? Could you try preview6 that came out yesterday?

**Comment by Pastajello** [comment]
Hello,

Ah yes, sorry. There was no label for preview6, so couldnt select it and forgot to write about this. Its on preview6.

The error is also quite the same on Vs For Mac with just a simple F5 build&run. 

For the command Im going to paste all my logs:

`% dotnet build -t:Run -f net8.0-android maui8.sln
MSBuild version 17.7.0+5785ed5c2 for .NET
  Determining projects to restore...
  Restored /Users/mer/Projects/maui8/maui8/maui8.csproj (in 891 ms).
/usr/local/share/dotnet/sdk/8.0.100-preview.6.23330.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
  maui8 -> /Users/mer/Projects/maui8/maui8/bin/Debug/net8.0-android/maui8.dll
obj/Debug/net8.0-android/android/src/crc6477f0d89a9cfd64b1/FormsAppCompatActivity.java(4,8): javac error JAVAC0000:  error: cannot access LifecycleOwner [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc6477f0d89a9cfd64b1/FormsAppCompatActivity.java(4,8): javac error JAVAC0000: public class FormsAppCompatActivity [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc6477f0d89a9cfd64b1/FormsAppCompatActivity.java(4,8): javac error JAVAC0000:   class file for androidx.lifecycle.LifecycleOwner not found [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc6477f0d89a9cfd64b1/FormsAppCompatActivity.java(4,8): javac error JAVAC0000:  [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(40,102): javac error JAVAC0000:  error: cannot find symbol [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(40,102): javac error JAVAC0000:         public MultiPageFragmentStateAdapter_1 (androidx.fragment.app.FragmentManager p0, androidx.lifecycle.Lifecycle p1) [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(40,102): javac error JAVAC0000:   symbol:   class Lifecycle [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(40,102): javac error JAVAC0000:   location: package androidx.lifecycle [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(40,102): javac error JAVAC0000:  [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]

Build FAILED.

obj/Debug/net8.0-android/android/src/crc6477f0d89a9cfd64b1/FormsAppCompatActivity.java(4,8): javac error JAVAC0000:  error: cannot access LifecycleOwner [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc6477f0d89a9cfd64b1/FormsAppCompatActivity.java(4,8): javac error JAVAC0000: public class FormsAppCompatActivity [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc6477f0d89a9cfd64b1/FormsAppCompatActivity.java(4,8): javac error JAVAC0000:   class file for androidx.lifecycle.LifecycleOwner not found [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc6477f0d89a9cfd64b1/FormsAppCompatActivity.java(4,8): javac error JAVAC0000:  [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(40,102): javac error JAVAC0000:  error: cannot find symbol [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(40,102): javac error JAVAC0000:         public MultiPageFragmentStateAdapter_1 (androidx.fragment.app.FragmentManager p0, androidx.lifecycle.Lifecycle p1) [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(40,102): javac error JAVAC0000:   symbol:   class Lifecycle [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(40,102): javac error JAVAC0000:   location: package androidx.lifecycle [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
obj/Debug/net8.0-android/android/src/crc64338477404e88479c/MultiPageFragmentStateAdapter_1.java(40,102): javac error JAVAC0000:  [/Users/mer/Projects/maui8/maui8/maui8.csproj::TargetFramework=net8.0-android]
    0 Warning(s)
    2 Error(s)`

**Comment by Pastajello** [comment]
Additionally:

 % dotnet --list-sdks
6.0.412 [/usr/local/share/dotnet/sdk]
7.0.304 [/usr/local/share/dotnet/sdk]
7.0.306 [/usr/local/share/dotnet/sdk]
8.0.100-preview.6.23330.14 [/usr/local/share/dotnet/sdk]

 dotnet workload list                           

Installed Workload Id      Manifest Version                               Installation Source  
-----------------------------------------------------------------------------------------------
wasi-experimental          8.0.0-preview.6.23329.7/8.0.100-preview.6      SDK 8.0.100-preview.6
ios                        16.4.8646-net8-p6/8.0.100-preview.6            SDK 8.0.100-preview.6
maui                       8.0.0-preview.6.8686/8.0.100-preview.6         SDK 8.0.100-preview.6

Use `dotnet workload search` to find additional workloads to install.

**Comment by rachelkang** [comment]
Hi, @Pastajello - could you share a repro and a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis) please? Even if it's just the file new maui template, we'd like to see if there are any discrepancies
