### ISSUE TITLE
[regression/8.0.0-preview.5.8529] - WinUI shadows are broken

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#16094]
### Description

Add shadows to standard controls...
![image](https://github.com/dotnet/maui/assets/46286656/3f598af2-b67b-442c-8947-6f50744b69ba)

			`<Button
				x:Name="RoundBtn"
				HorizontalOptions="Center"
				Text="Shadow"
				CornerRadius="60"
				HeightRequest="120"
				WidthRequest="120">
				<Button.Shadow>
					<Shadow
						Brush="Black"
						Opacity="1"
						Radius="10"
						Offset="0,0" />
				</Button.Shadow>
			</Button>`

			`<Editor Text="All shadow - No text!!!">
				<Editor.Shadow>
					<Shadow
						Brush="Black"
						Opacity="1"
						Radius="10"
						Offset="0,0" />
				</Editor.Shadow>
			</Editor>`

### Steps to Reproduce

1. Create a new .net Maui app
2. Add Shadow properties to standard elements

### Link to public reproduction project repository

n/a - just add shadows to elements

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

7.0.86

### Affected platforms

Windows

### Affected platform versions

Windows SDK - all

### Did you find any workaround?

no

**Comment by jsuarezruiz** [comment]
Quick test in main branch using .NET 7:

![test-shadow-win-net7](https://github.com/dotnet/maui/assets/6755973/2e45d83a-e34c-4aed-b35a-abeaba103489)

Works correctly, next will test the same with .NET 8.

**Comment by Stedy59** [comment]
@jfversluis , @jsuarezruiz 

I don't know how better to show what I am building, and the issues I am running so...
Here is a link to a video that shows Windows / Android side by side...

[https://youtu.be/-BrKbE_Ve8Y](https://youtu.be/-BrKbE_Ve8Y)

Inspired by both of your works... All custom using Handlers/Mappers 

NavigationPage, NavigationBar with CRUD, TabView, SlidingPanel, DialogView, MessageBox, ComboBox, MediaSelection, etc.

Complete control and access to colors/fonts/shadows/animations from Maui layer to and including platform layer for the developer!

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 6.0. Repro on Windows 11 .NET 8, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[16094.zip](https://github.com/dotnet/maui/files/12258363/16094.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/501420b9-f891-48a4-b748-024864379302)
Android:
![image](https://github.com/dotnet/maui/assets/97647558/87544e85-eb65-4430-82ec-04a878bf83ed)
iOS:
![image](https://github.com/dotnet/maui/assets/97647558/1977adaf-cb30-4d54-b78d-cfb63f5156c9)
