### ISSUE TITLE
Maui 8 preview 6 Blank app iOS using windows host attached to physyical device cannot find part of MauiInfo.plist

### ISSUE THREAD

**Issue by developer9969** [dotnet/maui#16117]
### Description

Installed latest VS 2022 preview with Maui preview 6 
Create a blank app 
Attach an iPHone 
build the app 

and I get 
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error loading partial Info.plist template file 'obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist': Could not find a part of the path 'D:\TEMP\MauiApp3\MauiApp3\obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist'.
        	MauiApp3	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8646-net8-p6\tools\msbuild\iOS\Xamarin.Shared.targets	535	

Am I missing something obvious here. It should just run - install profile via hot restart wizard and build  no?

### Steps to Reproduce

1. Create a blank app 
2. Attach an iPhone  using windows 11 
3. build the app 

and first you will see an error with provisioning profile  
I went to the pinfo.list and added
	<key>CFBundleIdentifier</key>
	<string>com.companyname.mauiapp3</string>

then you get 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Error loading partial Info.plist template file 'obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist': Could not find a part of the path 'D:\TEMP\MauiApp3\MauiApp3\obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist'.
        	MauiApp3	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8646-net8-p6\tools\msbuild\iOS\Xamarin.Shared.targets	535	

### Link to public reproduction project repository

just create a  blank app

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

VS 17.7.0 Preview 3.0

### Did you find any workaround?

no

### Relevant log output

```shell
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8646-net8-p6\tools\msbuild\iOS\Xamarin.Shared.targets(535,3): error : Error loading partial Info.plist template file 'obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist': Could not find a part of the path 'D:\TEMP\MauiApp3\MauiApp3\obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist'.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8646-net8-p6\tools\msbuild\iOS\Xamarin.Shared.targets(535,3): error :
1>Done building project "MauiApp3.csproj" -- FAILED.
1>MauiApp3 -> D:\TEMP\MauiApp3\MauiApp3\bin\Debug\net8.0-android\MauiApp3.dll
```
[MauiApp3.zip](https://github.com/dotnet/maui/files/12030286/MauiApp3.zip)

**Comment by developer9969** [comment]
@drasticactions  thank you for your reply. I am kind of baffled about creating an issue in visual studio. I totally get it that is a bug at their end , but surely this is an internal issue between Maui-Team and Visual studio Team and more importantly in my eyes this a Critical bug P1 as you cannot do anything..  Surely some sort sanity checks occurs before launching any preview?

The preview 5 hot restart preventing us to launch an iOS app in device now this 

thanks again for your reply
Very frustating..

**Comment by samhouts** [comment]
@developer9969 I wanted to follow up to see if you were able to create the issue in Visual Studio and if you got any resolution on it. As we mentioned in our comment suggesting that you create a VS feedback item, it's much easier to collect data on the tooling through that mechanism, and since we are not experiencing the issue you describe, there may be somthing unique to your environment. Thanks!
