### ISSUE TITLE
[Bug] On maximize, content of the WinUI window doesn't resize automatically. Manual resizing does it well.

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#1612]
### Description
On maximize, the content of the WinUI window doesn't resize automatically. Manual window resizing does it well.

### Steps to Reproduce

1. Create a new dotnet Maui project and set WinUI as the startup project
2. Build and run the project
3. Try to maximize the window, the content of the window doesn't resize automatically. Refer screenshot.
4. Whereas manually resizing the window, does resize the content to fit the window

### Expected Behavior
Content of the window should resize and fit into the window like how the manual resizing works

### Actual Behavior
Window content doesn't fit into the window

### Basic Information

- Version with issue: **.NET 6 Preview 5**
- Last known good version: **NA**
- IDE: **VS2019 16.11 Preview 2.0**
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  
  - WinUI: **Target SDK 10.0.19041 (running on Windows 10 21H1)**
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

<img width="960" alt="WinUI-Maximize" src="https://user-images.githubusercontent.com/81947404/125035685-bd9cca80-e0af-11eb-9d18-d0a2a5c23fd2.png">

**Comment by egvijayanand** [comment]
Not fully resolved (in .NET 6 Preview 6), when resized, the inner page content responds to resize action only after crossing a threshold limit for both width and height.

To simulate the issue, add a button with both its Horizontal and Vertical options set to CenterAndExpand, build and run the project, then try resizing the window. The expected output would be that button has to be in the center irrespective of its size.

But here the button would respond, by aligning itself to the center of the screen, only after crossing a certain threshold. And on the other side, when the window size goes below that limit, the button would disappear from the viewing area.

**Comment by hartez** [comment]
#1676 _might_ fix this.

**Comment by egvijayanand** [comment]
Thanks for the update @hartez, will verify once it is released.

**Comment by hartez** [comment]
Confirmed fixed with the latest on the main branch.
