### ISSUE TITLE
Downsizing Image with AspectFit leaves space around Image on iOS

### ISSUE THREAD

**Issue by marco-skizza** [dotnet/maui#16120]
### Description

I have a big Image (3700 x 2500 px) in my Resources that I display on my page. On iOS the width of the Image gets correctly downsized to the available space, but the height seems to remain untouched. Leaving a lot of space above and below the Image. On WinUI for example this works ok.

iOS not ok:
<img width="581" alt="iOS NOK" src="https://github.com/dotnet/maui/assets/130545138/238360b1-dcb9-459e-b1b5-246e14c6c39e">

WinUI ok:
![Screenshot 2023-07-12 183618](https://github.com/dotnet/maui/assets/130545138/ad12c6ab-bfa5-4e37-9ccc-f1a078637fc5)

### Steps to Reproduce

1) Create a starter MAUI app
2) Place a big image (around 3700 x 2500 px) under `/Resources/Images/tree_big.jpg`
3) Use the following markup on the page
```
    <ScrollView>
        <VerticalStackLayout>

            <Image
                Source="tree_big.jpg" />

        </VerticalStackLayout>
    </ScrollView>
```

### Link to public reproduction project repository

Please tell me if you need one

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Tested on iOS Simulator 16.4 (iPad mini 6th Gen)

### Did you find any workaround?

No

**Comment by muak** [comment]
I am facing the same issue.
In Xamarin.Forms it displays fine with no margins.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 6.0. Repro on iOS 16.4 .NET 8, not repro on Windows 11 and Android 13.0-API33 with below Project:
[16120.zip](https://github.com/dotnet/maui/files/12271664/16120.zip)
