### ISSUE TITLE
iOS/Catalyst memory leak with CollectionView when CollectionChanged is used

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/maui#16125]
### Description

This is the latest problem on the issue here: https://github.com/dotnet/maui/issues/14654

It can be illustrated with the test: https://github.com/jonathanpeppers/maui/commit/bbea0597cd0d90e4f0a84445f4ae35445f553bb4

When you replace an `ItemsSource` on iOS, in this way:

```csharp
var newCollection = new ObservableCollection<string>();
collectionView.ItemsSource = newCollection;
foreach (var item in data)
{
    newCollection.Add(item);
}
```

It appears that the old items are not removed, the test fails with:

    Expected: 3
    Actual: 6

But passes on Windows & Android. The test also passes if you change this:

```diff
var newCollection = new ObservableCollection<string>();
--collectionView.ItemsSource = newCollection;
foreach (var item in data)
{
    newCollection.Add(item);
}
++collectionView.ItemsSource = newCollection;
```

However, the sample app still leaks with the above change:

https://github.com/nacompllo/MemoryLeakEverywhere

I've not been successful in solving this one, but it seems good to write down what I found so far.

### Steps to Reproduce

Run the test in: https://github.com/jonathanpeppers/maui/commit/bbea0597cd0d90e4f0a84445f4ae35445f553bb4
Or try the sample: https://github.com/nacompllo/MemoryLeakEverywhere

### Link to public reproduction project repository

https://github.com/nacompllo/MemoryLeakEverywhere

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

All

**Comment by kevinxufei** [comment]
According to the project provided by the user, it was verified that there is no memory leak on 17.6.8 (build 400).
