### ISSUE TITLE
AppThemeBindingExtension not working in code

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#16126]
### Description

Apologies if Im not doing this correctly, but Im trying out dark mode in .NET Maui but with a coded UI, not XAML.
Given the below code sample in a new ContentPage:
When using SetAppThemeColor with both a light and dark colour it works and supports dark mode nicely. But this isn't using resources, and I would much prefer to.
When using SetDynamicResource for the background colour property to a resource with just a colour, it works (but no dark mode).
However, when using SetDynamicResource for the background colour to a resource defined by AppThemeBindingExtension, it doesn't set the initial colour and it doesn't respond to dark mode toggles.

The below code shows what doesn't work, its quite possible Im using AppThemBindingExtension incorrectly though.

            //Resources["myColor1"] = Colors.Red;
            Resources["myColor2"] = new AppThemeBindingExtension() { Light = Colors.LightGray, Dark = Colors.DarkGray };

            this.SetDynamicResource(ContentPage.BackgroundColorProperty, "myColor2");
            //this.SetAppThemeColor(ContentPage.BackgroundColorProperty, Colors.LightGray, Colors.DarkGray);

### Steps to Reproduce

New .NET Maui app, update MainPage to be defined in code rather than XAML.

Paste the following code into the constructor:

            //Resources["myColor1"] = Colors.Red;
            Resources["myColor2"] = new AppThemeBindingExtension() { Light = Colors.LightGray, Dark = Colors.DarkGray };

            this.SetDynamicResource(ContentPage.BackgroundColorProperty, "myColor2");
            //this.SetAppThemeColor(ContentPage.BackgroundColorProperty, Colors.LightGray, Colors.DarkGray);

Run and toggle dark mode in the iOS simulator. Background colour isn't set to either colour.

### Link to public reproduction project repository

Nope

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16, haven't tried anything else

### Did you find any workaround?

No.

**Comment by jfversluis** [comment]
The extension is a `MarkupExtension` which is specifically for use with XAML.

If you want to do this in code, you'll want to use the extension methods that are available: https://learn.microsoft.com/dotnet/maui/user-interface/system-theme-changes#extension-methods

**Comment by JohnHDev** [comment]
@jfversluis thanks, but the link you provided doesn't show how to set and use a dynamic resource in code.

I have however realised my error, I need to setup a Style and use that. That doesn't work with AppThemeBindingExtension so I ended up using  typeof(Page).Assembly.GetType("Microsoft.Maui.Controls.AppThemeBinding") and Activator.CreateInstance and set the properties directly. Works like a charm. Dark mode in .NET MAUI is looking very, very nice.

I see there was a discussion on making AppThemBinding public but sealed in Xamarin Forms. Would be worth considering for .NET Maui too I think.

Thanks Gerald! Keep up the good work on the videos, really helpful.
