### ISSUE TITLE
How to access the font file that location in the Resources folder in the .NET MAUI app.

### ISSUE THREAD

**Issue by tjiakwokyung28** [dotnet/maui#16129]
Local font in the resource font folder cannot use to write pdf by code

**Comment by xtuzy** [comment]
font be install to platform font folder, on ios, it same as system font. you can't get file directly, if you use platform graphic framework to write pdf, you can read font from font name, if not, maybe you can see https://stackoverflow.com/questions/3692812/on-ios-can-i-access-the-system-provided-fonts-ttf-file
