### ISSUE TITLE
iOS signing

### ISSUE THREAD

**Issue by vfongmala** [dotnet/maui#1614]
At the moment, we can build an MAUI iOS app with the bash command dotnet build net6-samples.sln -c Release.
And we can get an output .app file from the folder /bin/Release/net6.0-ios
Is there any way to sign the output .app file, so it can be shared and installed on other devices?

**Comment by igalfsg** [comment]
I haven't tried it for MAUI, but it did take me a while to figure out to do it for .NET console app. Here is what I had to do for .NET Console App, hope it helps for MAUI https://codingflamingo.com/blog/how-to-code-sign-and-notarize-net-console-app-for-mac

**Comment by vfongmala** [comment]
@igalfsg Will definitely take a look. Thank you Igal.

**Comment by jfversluis** [comment]
Hope this is resolved! This is more a iOS generic question than something specific to .NET MAUI I think anyway :)
