### ISSUE TITLE
invalid android:versionCode - Android app doesn't build in default .NET MAUI Blazor Hybrid app

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/maui#16155]
### Description

Trying to run a default app in that template on Android will result in build errors. Unsure if there's something wrong with my templates.

### Steps to Reproduce

1. Create new .NET MAUI Blazor Hybrid app
2. Run in debug or release
3. :

```
1>Done building project "MauiApp1demo.csproj".
1>MauiApp1demo\Platforms\Android\AndroidManifest.xml : error APT2140: invalid android:versionCode ''.
1>MauiApp1demo\Platforms\Android\AndroidManifest.xml : error APT2140: 
1>MauiApp1demo\Platforms\Android\AndroidManifest.xml : error APT2140: This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.
1>MauiApp1demo\Platforms\Android\AndroidManifest.xml : error APT2140: invalid android:versionCode ''.
1>\MauiApp1demo\Platforms\Android\AndroidManifest.xml : error APT2140: 
1>MauiApp1demo\Platforms\Android\AndroidManifest.xml : error APT2140: This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.
```

### Link to public reproduction project repository

https://github.com/danielchalmers/MauiApp1demo

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

24.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Do you see the same issue when you create and run a new MAUI app (targeting Android again), where there is no Blazor involved?

**Comment by danielchalmers** [comment]
Not able to get this reproduced again either way. Apologies, must have been my computer at the time.
