### ISSUE TITLE
Include Map xml namespace by default on .NET 8 too, on NET 7 it works without any explicit definition

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#16154]
### Description

Include Map xml namespace by default on .NET 8 too, on NET 7 it works without any explicit definition.

### Steps to Reproduce

1. On an MAUI app targeting .NET 8, add Map control on any page/view
2. Requires this xml namespace (http://schemas.microsoft.com/dotnet/2021/maui/maps) to be explicitly defined for it to get compiled
3. Whereas on .NET 7, Map control would compile without any need for this explicit definition

```xml
<Map />
```

### Link to public reproduction project repository

Plain control definition, default template is sufficient

### Version with bug

.NET 8 Previews

### Last version that worked well

.NET 7

### Affected platforms

All platforms (Generic)

### Affected platform versions

All platforms

### Did you find any workaround?

Requires explicit xml namespace definition, which is definitely an overhead as it works without such a thing on .NET 7.

**Comment by jfversluis** [comment]
I would doubt something here has changed actually... Does it really not build and run? Or does it only give a warning/error in Visual Studio but does it actually work? Do you have some screenshots or actual error messages?

**Comment by egvijayanand** [comment]
Whereas the same works fine on .NET 7 i.e., without any explicit XML namespace defn.

**Comment by egvijayanand** [comment]
Post namespace inclusion screenshot, no errors, build succeeded.

![image](https://github.com/dotnet/maui/assets/81947404/df2147bd-092c-4c53-81a3-5ee20fc73797)

**Comment by egvijayanand** [comment]
Have found the root cause of this issue:

Seems there's an update in the namespace URI for the maps feature in .NET 8. And it's not the same as the root namespace used for .NET MAUI. There's a **maps** suffix added to it. So an explicit namespace definition is required apart from adding a reference to the Maps NuGet package.

```xml
<StatusPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:m="http://schemas.microsoft.com/dotnet/2021/maui/maps">
    <m:Map />
</StatusPage>
```

This issue can be marked as resolved.
