### ISSUE TITLE
Android splashscreen SVG not shown

### ISSUE THREAD

**Issue by duindain** [dotnet/maui#16159]
### Description

In our app we have a svg with text and an image, I can see when loading it shows the background color we have set in the MauiSplashScreen setting but the svg is not displayed

Spinning up a repro app with no changes I can see it should show .NET from the svg file but it does not though the background color is shown, this is the same behavior I've observed in our app

https://github.com/dotnet/maui/assets/4401594/9f3b9a34-3b8f-442f-aa36-cc299f6f9f7a

### Steps to Reproduce

New .Net Maui app
Run on Android

Splashscreen should display .NET from the splash.svg file but it doesnt just the background color is shown Color="#512BD4"

`<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />`

### Link to public reproduction project repository

https://github.com/duindain/MauiAndroidSplash

### Version with bug

7.0.92

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
@mattleibow Thoughts?

**Comment by moljac** [comment]
Seems like `h` and `w` are 0

```
07-18 10:22:18.895   707   830 D SplashScreenView: Build android.window.SplashScreenView{e821255 V.E...... ......ID 0,0-0,0}
07-18 10:22:18.895   707   830 D SplashScreenView: Icon: view: null drawable: null size: 0
07-18 10:22:18.895   707   830 D SplashScreenView: Branding: view: android.view.View{1b5e46a G.ED..... ......I. 0,0-0,0 #10204a6 android:id/splashscreen_branding_view} drawable: null size w: 0 h: 0
```

Adding logcat and bugreport

[bugreport-sdk_gphone64_x86_64-SE1A.220826.006.A1-2023-07-18-10-23-11.zip](https://github.com/dotnet/maui/files/12078104/bugreport-sdk_gphone64_x86_64-SE1A.220826.006.A1-2023-07-18-10-23-11.zip)

[log_2023-07-18T10-22-59.txt](https://github.com/dotnet/maui/files/12078105/log_2023-07-18T10-22-59.txt)

**Comment by moljac** [comment]
`MauiAndroidSplash-master/MauiApp1/obj/Debug/net7.0-android/mauisplash.inputs`

```
File=Resources/Splash/splash.svg;Link=;BaseSize=128,128;Resize=;TintColor=;Color=#512BD4;ForegroundScale=
```

**Comment by SarthakB26** [comment]
It happened with me sometime but only when I run app in debug mode or debugger is attached.
If I open deployed app by clicking on icon from mobile or simulator it shows just fine.

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 5. Can not repro on Android platform with https://github.com/duindain/MauiAndroidSplash.
