### ISSUE TITLE
[Bug] .NET MAUI Blazor App [WinUI] is blank (on 21H1?)

### ISSUE THREAD

**Issue by Viomaliha** [dotnet/maui#1617]
### Description
We installed VS 2019 Preview and required stuff. Created fresh .NET MAUI Blazor. It runs fine on two PCs with `Windows 20H2 (19042)` but is *blank* on another PC with `Windows 21H1`.

It there anything we can do to fix it? issue is on our setup? or the framework?

### Steps to Reproduce

1. Install Visual Studio 2019 Preview 2.0 (16.11.0) and select ".NET desktop development", "desktop development with C++", "UWP development", "Mobile development with .net"
2. Install Project Reunion (version 0.8.0.46122163 which is _not preview_) extension (fwiw: preview version results the same)
3. Install Single-project MSIX Packaging Tools extension
4. `dotnet nuget add source --name nuget.org https://api.nuget.org/v3/index.json`
5. `dotnet tool install -g redth.net.maui.check`
6. `maui-check` (and ensure everything is green)
7. Enable "Developer Mode" from windows settings
8. Start VS 2019 Preview and Create a new project
9. Select *.NET MAUI Blazor App*
10. Select `<projectname>.WinUI` from run target from top
11. Hit Play button

### Expected Behavior
- App runs and Home/Counter/Fetch data etc tabs are visible
- NOTE: This is what happens with TWO machines with Windows 19042

### Actual Behavior
- App is empty with blue/purple screen.
- Resizing the app window does NOT show the UI
- NOTE: This is what happens with another machine with Windows 19043

### Basic Information

- Version with issue: Windows 19043
- Last known good version: Windows 19042
- IDE: Visual Studio 2019 Preview 2.0 (16.11.0) 
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

- Output of 19043 (not working):
![image](https://user-images.githubusercontent.com/62325199/125110708-bead1680-e106-11eb-9ba4-d0aa16d2d4b9.png)

- Output of 19042 (working):
![image](https://user-images.githubusercontent.com/62325199/125110799-e2705c80-e106-11eb-89af-b2009b001c92.png)

### Workaround

- Use Windows 19042?

**Comment by Eilon** [comment]
Hi @Viomaliha , this issue should be fixed in the MAUI update that came out earlier this week. You can learn more about what's new and how to install the update in this post: https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/
