### ISSUE TITLE
Mouse scroll on 'X' closes application

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/maui#16179]
### Description

On windows MAUI app closes when you scroll on the close button, it doesn't happen when you scroll on Visual studio's 'X' icon on the upper right corner

### Steps to Reproduce

A new app demonstrates the problem

### Link to public reproduction project repository

default MAUI.Blazor template

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by drasticactions** [comment]
This is a WinUI 3 bug with `ExtendsContentIntoTitleBar`: https://github.com/drasticactions/MauiRepros/blob/51c4868af6d230252bf682f328a79ed708e84783/WinUIWindowExtendsIntoTitlebarBug/App1/App1/MainWindow.xaml.cs#L28-L29

If you enable that on a window, then all the mouse buttons (including the scroll wheel) seem to impact those controls. It's independent of MAUI. We should move this to https://github.com/microsoft/windowsappsdk

**Comment by Xyncgas** [comment]
Hey, it's fixed
