### ISSUE TITLE
Maui Handlers using partial classes do always replace existing handlers? How to customize and existing control with Handlers?

### ISSUE THREAD

**Issue by EmilAlipiev** [dotnet/maui#16178]
### Description

I have asked this question on SO before and i was suggested to create a bug or feature request here. 
So here is the original [question](https://stackoverflow.com/questions/76547022/maui-handlers-using-partial-classes-do-always-replace-existing-handlers-how-to) 

I don't really understand Maui handlers using Partial class method. When using other method you have options like AppendToMapping that you can extend the current mapping but when I use partial classes, I get a new instance of the control always. I am not able to append the existing control. That means if i define a control that inherits from Maui control with some default values and registering this control with platforms specific handlers, my control loses predefined cross platform values. This is not the way Renderers are working xamarin.forms? So what is this case and how to fix this?

Please dont suggest me to use Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping because this does not exist in maui class library if i want to work with nuget packages.

Even Microsoft's [documentation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize) doesn't mention about partial classes to customize a control but mentions [here](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/create) Create a control. (yes there is something at the end with Partial class but this is totally irrelevant, not sure what is this about and MS documented something like that) Why? If that is not possible, thats a huge downgrade in Maui from Xamarin.forms.
 
 

### Steps to Reproduce

I have created a test repo with demo maui project and maui class library.

https://github.com/EmilAlipiev/TestMauiHandlers

under the class library you find the Old renderers under each platform and new upgraded Handlers under handlers folders.

1- So first run the Demo project in IOS without handlers. you can see the default value for text "this is default text" on the ui.
2- enable ConfigureMauiHandler in MauiProgram.cs in HandlersDemoApp
3- You see that default text is empty

Reason for that is Handlers are creating a complete new Entry instead of extending the Entry defined in the shared part i believe.

If i use renderers they will be just extended with the default cross platform definitions.

### Link to public reproduction project repository

https://github.com/EmilAlipiev/TestMauiHandlers

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All versions

**Comment by xtuzy** [comment]
Try use `EntryHandler.Mapper` instead of `EntryHandler.ViewMapper` in
```
    public static PropertyMapper<CustomEntry, CustomEntryHandler> PropertyMapper = new PropertyMapper<CustomEntry, CustomEntryHandler>(EntryHandler.ViewMapper)
    {
#if __ANDROID__
      
        [nameof(CustomEntry.LeftPadding)] = UpdatePadding,
        [nameof(CustomEntry.RightPadding)] = UpdatePadding,
        [nameof(CustomEntry.HorizontalTextAlignment)] = UpdateTextAlignment,
#elif IOS || MACCATALYST
        [nameof(CustomEntry.BorderWidth)] = UpdateBorderWidth,
        [nameof(CustomEntry.BorderColor)] = UpdateBorderColor,
        [nameof(CustomEntry.BorderRadius)] = UpdateBorderRadius,
        [nameof(CustomEntry.LeftPadding)] = UpdateLeftPadding,
        [nameof(CustomEntry.RightPadding)] = UpdateRightPadding,
#endif
    };
```

**Comment by jfversluis** [comment]
Looks like this is more of a how-to question which is probably better for a discussion or Microsoft Q&A. If you want to see any changes in the docs, please open an issue on [that repo](https://github.com/dotnet/docs-maui/issues/new).

I do think the docs in this area might be improved by now as well, so it might be worth checking that out.

Thanks!
