### ISSUE TITLE
Rare error occuring in the wild

### ISSUE THREAD

**Issue by zoanthal** [dotnet/maui#16184]
### Description

Google Play store reporting the error below. Cannot find any information on previous occurrences. The page does have timers with a cancellation token, could this crash be related to that if not disposed of properly? (iI have cancellations in OnDisappearing). Cannot reproduce on my devices, and appears to be occurring very rarely in the wild.

```
Exception android.runtime.JavaProxyThrowable:
  at crc6488302ad6e9e4df1a.MauiApplication_ActivityLifecycleCallbacks.n_onActivityStopped
  at crc6488302ad6e9e4df1a.MauiApplication_ActivityLifecycleCallbacks.onActivityStopped
  at android.app.Application.dispatchActivityStopped (Application.java:510)
  at android.app.Activity.dispatchActivityStopped (Activity.java:1548)
  at android.app.Activity.onStop (Activity.java:2679)
  at androidx.fragment.app.FragmentActivity.onStop (SourceFile:1)
  at androidx.appcompat.app.AppCompatActivity.onStop (SourceFile:1)
  at android.app.Instrumentation.callActivityOnStop (Instrumentation.java:1551)
  at android.app.Activity.performStop (Activity.java:8829)
  at android.app.ActivityThread.callActivityOnStop (ActivityThread.java:5835)
  at android.app.ActivityThread.performStopActivityInner (ActivityThread.java:5809)
  at android.app.ActivityThread.handleStopActivity (ActivityThread.java:5880)
  at android.app.servertransaction.StopActivityItem.execute (StopActivityItem.java:43)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2574)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8757)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
```

### Steps to Reproduce

Unknown

### Link to public reproduction project repository

None

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11, 12, 13

**Comment by jsuarezruiz** [comment]
Do you have more logs or information?

**Comment by zoanthal** [comment]
Unfortunately I don't. The app is used by 40k+ people and I am seeing ~10 crashes per day with this error in my Play Console. No user has contacted me about the error. I myself cannot reproduce it, though perhaps I could if I knew what these users were doing. These errors only started after adding buttons making use of these elements:  



    public class CountdownButton : Button
    {
        private CancellationTokenSource _cancellationTokenSource;
        private DateTime _startTime;
        private TimeSpan _countdownDuration;
        private TimeSpan _remainingDuration;
        public string InitialText;
        private string _finishedText;
        public string _pausedText;
        public bool Paused = false;

        public bool IsRunning { get; private set; } = false;
        public TimeSpan RemainingTime => _countdownDuration - (DateTime.Now - _startTime);
        public DateTime StartTime => _startTime;

        public int _beforefinsecs;
        public string _beforefinmsg;
        private bool Added = false;

        public CountdownButton(string initialText, int countdownSeconds, string finishedText, int beforefinishsecs = -1, string beforefinishmsg = "", string pausedText = null)
        {
            
            InitialText = initialText;
            _countdownDuration = TimeSpan.FromSeconds(countdownSeconds);
            _finishedText = finishedText;
            _beforefinsecs = beforefinishsecs;
            _beforefinmsg = beforefinishmsg;
            _pausedText = pausedText;

            this.Text = InitialText;
            this.Clicked += OnButtonClicked;


        }

        private void OnButtonClicked(object sender, EventArgs e)
        {
            if (IsRunning)
            {
                this.Paused = true;
                PauseCountdown();

            }
            else
            {
                StartCountdown();
            }
        }

        public void StartCountdown()
        {
            if (!Added) { 
                App.ActiveCountdownButtons.Add(this);
                Added = true;
                };
            IsRunning = true;

            // If the timer is resumed, adjust the _startTime
            if (Paused)
            {
                this.Paused = false;
                _startTime = DateTime.Now - (_countdownDuration - _remainingDuration);
            }
            else
            {
                _startTime = DateTime.Now;
            }

            if (_pausedText != null)
            {
                this.Text = _remainingDuration.ToString(@"mm\:ss");
            }
            else
            {
                this.IsEnabled = false;
                this.Text = RemainingTime.ToString(@"mm\:ss");
            }
            
            _cancellationTokenSource = new CancellationTokenSource();

            UpdateCountdown();
        }

        private async void UpdateCountdown()
        {

            try
            {
                while (RemainingTime.TotalSeconds > 0)
                {
                    await Task.Delay(50, _cancellationTokenSource.Token);
                    this.Text = RemainingTime.ToString(@"mm\:ss");
                    _remainingDuration = RemainingTime; // Add this line
                    if (Math.Floor(RemainingTime.TotalSeconds) == _beforefinsecs)
                    {
                        if (App.audioSwitch.IsToggled)
                            await TextToSpeech.SpeakAsync(_beforefinmsg);
                    }
                }

                // Time's up: play an alert and reset the button
                this.Text = InitialText;
                if (App.audioSwitch.IsToggled)
                    await TextToSpeech.SpeakAsync(_finishedText);
            }
            catch (TaskCanceledException)
            {
                // The countdown was cancelled
            }
            finally
            {
                IsRunning = false;
                this.IsEnabled = true;
                _cancellationTokenSource.Dispose();
            }
        }

        public void ResetCountdown(int countdownSeconds)
        {
            _countdownDuration = TimeSpan.FromSeconds(countdownSeconds);
            _remainingDuration = _countdownDuration;
            _startTime = DateTime.Now;
            IsRunning = true;
            this.IsEnabled = false;
            UpdateCountdown();
        }

        public void PauseCountdown()
        {
            IsRunning = false;
            _cancellationTokenSource?.Cancel();
            _remainingDuration = RemainingTime; // Save remaining time during pause
            this.Text = _pausedText;
        }

        public void StopCountdown()
        {
            App.ActiveCountdownButtons.Remove(this);
            IsRunning = false;
            Paused = false;
            _cancellationTokenSource?.Cancel();
            this.Text = InitialText;
            this.IsEnabled = true;
            // Optionally reset _remainingDuration to the original _countdownDuration
            _remainingDuration = _countdownDuration;
        }

    }

    public class CountupButton : Button
    {
        private CancellationTokenSource _cancellationTokenSource;
        private DateTime _startTime;
        private bool Added;
        private TimeSpan _totalElapsedTime = TimeSpan.Zero;
        public string InitialText;
        public bool ClickedAlready = false;

        private string _beforeTimer;
        private string _afterTimer;

        private bool _isPaused = false;
        public List<(TimeSpan time, string announcement)> _announcements;

        public bool IsRunning { get; private set; } = false;
        public TimeSpan ElapsedTime => _isPaused ? _totalElapsedTime : _totalElapsedTime + (DateTime.Now - _startTime);
        public DateTime StartTime => _startTime;

        public CountupButton(string initialText,
            List<(TimeSpan time, string announcement)> announcements,
            string beforeTimer = "", string afterTimer = "")
        {
            InitialText = initialText;
            _announcements = announcements;
            _announcements.Sort(); // Ensure the announcements are sorted by time
            _beforeTimer = beforeTimer;
            _afterTimer = afterTimer;

            this.Text = InitialText;
            this.Clicked += OnButtonClicked;

        }

        private void OnButtonClicked(object sender, EventArgs e)
        {
            if (IsRunning)
            {
                if (_isPaused)
                {
                    ResumeCountup();
                }
                else
                {
                    PauseCountup();
                }
            }
            else
            {
                StartCountup();
            }
        }

        public void StartCountup()
        {
            if (!Added)
            {
                App.ActiveCountupButtons.Add(this);
                Added = true;
            };
            IsRunning = true;
            _isPaused = false;
            _startTime = DateTime.Now;

            this.Text = _beforeTimer + " " + ElapsedTime.ToString(@"mm\:ss") + " " + _afterTimer;

            UpdateCountup();
        }

        private async void UpdateCountup()
        {
            _cancellationTokenSource = new CancellationTokenSource();

            try
            {
                int nextAnnouncementIndex = 0;

                while (IsRunning)
                {
                    if (_isPaused)
                    {
                        await Task.Delay(50);
                        this.Text = "Paused @ " + ElapsedTime.ToString(@"mm\:ss") + " - Click to resume timer";
                    }
                    else
                    {
                        await Task.Delay(50, _cancellationTokenSource.Token);
                        this.Text = _beforeTimer + " " + ElapsedTime.ToString(@"mm\:ss") + " " + _afterTimer;

                        // Make an announcement when the elapsed time reaches the time of the next announcement
                        if (nextAnnouncementIndex < _announcements.Count &&
                            ElapsedTime >= _announcements[nextAnnouncementIndex].time)
                        {
                            if (App.audioSwitch.IsToggled)
                                await TextToSpeech.SpeakAsync(_announcements[nextAnnouncementIndex].announcement);
                            nextAnnouncementIndex++;
                        }
                    }
                }
            }
            catch (TaskCanceledException)
            {
                // The countup was cancelled
            }
            finally
            {
                this.IsEnabled = true;
                _cancellationTokenSource.Dispose();
            }
        }

        public void PauseCountup()
        {
            _isPaused = true;
            _totalElapsedTime += DateTime.Now - _startTime; // Capture the total elapsed time up until now

        }

        public void ResumeCountup()
        {
            _isPaused = false;
            _startTime = DateTime.Now;
            this.Text = _beforeTimer + " " + ElapsedTime.ToString(@"mm\:ss") + " " + _afterTimer;
        }

        public void StopCountup()
        {
            App.ActiveCountupButtons.Remove(this);
            IsRunning = false;
            _isPaused = false;
            _totalElapsedTime = TimeSpan.Zero; // Reset the total elapsed time
            _cancellationTokenSource?.Cancel();
            this.Text = InitialText;
        }
    }
}

**Comment by PureWeen** [comment]
We have a lot of fixes in this area with .NET8

I'm hopeful you'll be fixed once you update to .NET8.
