### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by RainyArcher** [dotnet/maui#16183]
### Description

It would be great to build apps for all the platforms available. .NET MAUI could become a good competitor to Avalonia and Uno frameworks by adding a support for the platform that is being widely used by developers all around the world. Linux support is a feature that was requested many times by the dotnet community, so here's my contribution. 

### Public API Changes

dotnet package on linux 

dotnet maui component

### Intended Use-Case

Linux support is really important for those who use this OS and want to build and use apps with a beautiful UI.

.NET MAUI can become a truly cross-platform framework

**Comment by Xyncgas** [comment]
Linux support enables visual studio on linux

**Comment by RainyArcher** [comment]
> Linux support enables visual studio on linux

Developing and debugging .NET MAUI applications is possible on Linux through the VS Code MAUI extension

But currently, you can only debug Android apps on Linux, so it would be great to see another debug target option

**Comment by jfversluis** [comment]
This has been asked many times before. Please find an open one, I think there is a rather popular Discussion, and upvote that instead of opening duplicate ones. Thanks!
