### ISSUE TITLE
[Windows, Blazor] Review currently failing Windows tests

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#16187]
### Description

As part of https://github.com/dotnet/maui/pull/15629 I've skipped the tests listed below. All of these tests were failing on the original PR. We don't necessarily need to fix these issues for .NET8 but we should establish if we *should* fix these for .NET8 or just fix the tests themselves. 

**BlazorWebView**
- [ ] BlazorWebViewUsesStartPath
- [ ] BlazorWebViewLogsRequests

**Comment by mkArtakMSFT** [comment]
@Eilon parking this in rc2 milestone.
