### ISSUE TITLE
MAUI BlazorWebView does not support backgroundcolor in iOS

### ISSUE THREAD

**Issue by frarcedev** [dotnet/maui#16186]
### Description

I am using the BlazorWebView component and currently shows a white backgroundcolor when initializing the iOS application, using the BackgroundColor property you can remove this effect in Android but in iOS the error persists being a visual nuisance when initializing the app. Because if I use a dark splashscreen a white jump will be seen on the screen.

Also using a transparent backgroundcolor the problem persists on iOS.
MainPage.xaml
`
<BlazorWebView x:Name="blazorWebView" HostPage="wwwroot/index.html" BackgroundColor="Black">
        <BlazorWebView.RootComponents>
            <RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
        </BlazorWebView.RootComponents>
    </BlazorWebView>
`

### Tested in
Physical device iPhone 14 Pro
Simulator iPhone 14 Pro Max

### Steps to Reproduce

1.Create new .NET MAUI Blazor App.
2.Set a splashscreen dark and set a style to background color in index.html dark.
3.Run application in any iOS device.

### Link to public reproduction project repository

https://github.com/frarcedev/blazorwebviewerrorios/tree/main/splashapp

### Version with bug

7.0.86

### Last version that worked well

7.0.86

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by mhrastegari** [comment]
That's the default background color of WKWebView, you need to use custom handlers and put [these codes](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/App/MainPage.xaml.cs#L46) in it.

**Comment by frarcedev** [comment]
> That's the default background color of WKWebView, you need to use custom handlers and put [these codes](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/App/MainPage.xaml.cs#L46) in it.

Thank you very much @mhrastegari , that worked correctly for me.
