### ISSUE TITLE
Label not respecting Font Family setup if using FormattedText

### ISSUE THREAD

**Issue by albilaga** [dotnet/maui#16193]
### Description

When setup `FontFamily` in `Label` who have `FormattedText`, `Label` will not respect `FontFamily` setup in `Label`. But if we setup the `FontFamily` in `Span` then it is worked. This is occuring on MAUI 7.0.92. Not sure if previous version worked or not but in Xamarin.Forms this is worked.

### Steps to Reproduce

1. Open this https://github.com/albilaga/MAUIPlayground/tree/test-font-family
2. Run the app.
3. The second label will have regular font even though I already setup the `FontFamily` to be the same like other label
4. Code all is in this page https://github.com/albilaga/MAUIPlayground/blob/test-font-family/MAUIPlayground/MainPage.xaml

### Link to public reproduction project repository

https://github.com/albilaga/MAUIPlayground/tree/test-font-family

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS and Android

### Did you find any workaround?

Workaround right now is setup the `FontFamily` in the `Span` instead in `Label`

**Comment by AndreasReitberger** [comment]
Duplicate of #13977

**Comment by drasticactions** [comment]
> Duplicate of #13977

I agree, looking at the root issues, they seem the same. 

Duplicate of https://github.com/dotnet/maui/issues/13977

**Comment by samhouts** [comment]
Duplicate of https://github.com/dotnet/maui/issues/13977
