### ISSUE TITLE
[Spec] MAUI emoji

### ISSUE THREAD

**Issue by Suplanus** [dotnet/maui#162]
We all ❤️ emojis and use it for the platforms like:
- 🤖 Android
- ⌚️ watchOS
- 📺 tvOS
- 🖥 Windows
- 📱 iOS
- 💻 macOS

Which emoji would be the best for MAUI it self? 🏝?

# Difficulty : [low]

**Comment by Happypig375** [comment]
Why do we limit ourselves to emoji? Why don't we use images?

**Comment by Suplanus** [comment]
I think MAUI would have an image / logo like the Xamagon in Xamarin.
Would like to have an option if I want to use an emoji 🦄

**Comment by laptou** [comment]
Wouldn't the emoji that are used depend on that platform that the app is running on and the font that is being used to render them? Why does MAUI need to have its own specific emoji set?

**Comment by Suplanus** [comment]
You are right. Want only to discuss if there is a need.
I think especially in the changeover phase there will be issues that only affect MAUI.

I close this issue. Thanks for your replies 💕
