### ISSUE TITLE
Title bar messes up on resize

### ISSUE THREAD

**Issue by PerfectlyFineCode** [dotnet/maui#16209]
### Description

When I start the app and resize the window, title bar will lag behind as well as go out of view.

https://github.com/dotnet/maui/assets/70201838/04430091-5e6a-4709-a3ae-75ae5d851464

### Steps to Reproduce

1. Create a new project.
2. Start the project
3. Resize the app as soon as it loads up.

Expected Outcome: Title bar should resize with no issues or lag-behind.
Actual Outcome: Title bar lags behind as well as the window control buttons moves out of view.

### Link to public reproduction project repository

https://github.com/PerfectlyFineCode/MyRecipes

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11 22H2 22621.1992

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue does not repro on Windows 11(8.0.100-preview.6.23330.14) with below Project:
[My Recipes.zip](https://github.com/dotnet/maui/files/12299325/My.Recipes.zip)
![Resize](https://github.com/dotnet/maui/assets/97647558/47d300fc-781e-47da-9f46-7fe647d5de64)
