### ISSUE TITLE
[iOS, Blazor] `AllowInlineMediaPlayback` should be true by default

### ISSUE THREAD

**Issue by mhrastegari** [dotnet/maui#16207]
### Summary
Shouldn't the `WKWebView`'s `Configuration.AllowsInlineMediaPlayback` in `BlazorWebView` handler be `true` by default?
In our case it was about `input` tag with type of `file`, which shows black screen when you wanna take picture or record video.

**Comment by mkArtakMSFT** [comment]
This should already be the default in .NET 8.
