### ISSUE TITLE
[regression/8.0.0-preview.1.7762] CollectionView with bound text of varying lengths does not properly measure all items

### ISSUE THREAD

**Issue by samhouts** [dotnet/maui#16234]
### Description

I have a CollectionView with a Label in the ItemTemplate. The text of the Label is bound to a value in the ItemSource that can either be 1 line or multiple lines. As of 8.0, it appears that it only measures the first item in this instance and not all items, so if the first item is short, the rest of the items will be cut off.

Works as expected in 7.0.92.

### Steps to Reproduce

1. File > New
2. Add ViewModel with ObservableCollection of objects where one property has text that can vary between short and long string values. Make sure the first item is the shortest.
3. Add CollectionVIew with Label bound to the string. (Possibly an image of varying size could do the same thing...?)
4. Run.

Expected: CollectionView has rows of varying height and the entire content is visible.
Actual: CollectionView has rows of all the same height and some of the content is truncated.

### Link to public reproduction project repository

https://github.com/samhouts/dotnetmauirepros/tree/cvmeasureallitems

### Version with bug

8.0.0-preview.1.7762

### Last version that worked well

7.0.92

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

?

**Comment by manstheram** [comment]
I believe I'm getting the same issue but also on version 7.0.92. It started happening after I updated a bunch of packages which probably included MAUI stuff.

**Comment by samhouts** [comment]
@manstheram I did not see this issue on 7.0.92 with my reproduction project. Can you link yours, possibly? Thanks!

**Comment by DDHSchmidt** [comment]
May I inquire why this was closed as completed?
This is still an issue in 8.0.0-rc.2.9511
Please compare the following screenshots of the sample project from two different Maui versions on Windows:
![image](https://github.com/dotnet/maui/assets/67259411/eb66d940-9889-48b9-8cdc-cb0650e25aec)
![image](https://github.com/dotnet/maui/assets/67259411/aa54f6e6-6206-41a5-b113-727e5855fabf)

This is currently *not* addressed at all!
If the last commit is a fix, then I'm unable to see which release is going to contain it, please be more open about this.
I have a whole department grilling me about this issue :/
