### ISSUE TITLE
[Bug] IntelliSense does not work in `.razor` file in .NET MAUI Blazor App.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/maui#1623]
IntelliSense ( C# and Razor ) is not working in the `.razor` file in .NET MAUI Blazor App. Also `.razor` related code highlighting not working. Please look at the following screenshot. Here `<SurveyPrompt/>` is not green bold.

![MAUI Blazor](https://user-images.githubusercontent.com/14342773/125151893-4d537f00-e16b-11eb-8a61-f5bfc105673b.PNG)

**Visual Studio Version: 2019 16.11 preview 2.**

**Comment by Eilon** [comment]
Good news, we figured out a fix! https://github.com/dotnet/maui/pull/1651

**Comment by TanvirArjel** [comment]
@Eilon Thank you so much for a prompt fix. I am really enjoying .NET MAUI Blazor.

**Comment by TanvirArjel** [comment]
@Eilon The pull requested says, the fixes have been merged with .NET 6.0 preview 6. I have tested with .NET 6.0 preview6 with Visual Studio 2022 preview2 and Visual Studio 2019 16.11 Preview3 and found that fixes are not available. Could you please confirm with which version of .NET 6.0 and Visual Studio the fixes will be available?
