### ISSUE TITLE
MAUI App is not supporting iOS 17 Beta version

### ISSUE THREAD

**Issue by venkatkancheti** [dotnet/maui#16236]
### Description

As iOS will release the new iOS 17 version in September for all the users, as we have tried upgrading my phone to iOS 17 beta version and tried to launch the MAUI app its crashing. Can you please help us in fixing this? or do we have any ETA on this?

### Steps to Reproduce

1. Created a new project for MAUI
2. Tried to launch the app from simulator or device that target ios 17 version.

### Link to public reproduction project repository

https://github.com/venkatkancheti/TestProjectMAUI

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

iOS

### Affected platform versions

iOS 17

**Comment by xtuzy** [comment]
dotnet's support for the new version of ios is slow, I suggest you run a default dotnet ios app first. If it doesn't work, you can go https://github.com/xamarin/xamarin-macios to get help first. If it work, it's probably maui's fault, You can debug from the source code.

**Comment by drasticactions** [comment]
The current .net7.0 and .net8.0 previews of MAUI support the current stable Xcode (As of this writing, 14.3.1) and will, most likely, fail on anything higher. That means deploying to beta versions of Xcode (And, by extension, Beta versions of iOS) will most likely fail until there is support for it within the SDK.

You can follow supported Xcode / iOS releases on https://github.com/xamarin/xamarin-macios.
