### ISSUE TITLE
What about multitouch gestures functionality with platformeffects?

### ISSUE THREAD

**Issue by hflexgrig** [dotnet/maui#1624]
Hello, on Xamarin forms I have implementation of toucheffect , which I use for multitouch pinch gestures in my Xamarin app. I'd like to know if there's backward capability of this like for renderers or something new planned for that ?

**Comment by jfversluis** [comment]
Thanks for your question! Do you have your own implementation? You can make your current renderers work without too much effort. I don't think we have any Docs on that yet, but you can see my video on that here: https://www.youtube.com/watch?v=_EKznvARe8o

Ideally, you would want to port that to the new handler architecture. Additionally, if it's something you would like to see in .NET MAUI in the box, make sure to open a feature request with the necessary details.
