### ISSUE TITLE
Home Indicator Auto Hidden Not Working In MAUI

### ISSUE THREAD

**Issue by Sohel3798** [dotnet/maui#16247]
### Description

Home Indicator Auto Hidden Not Working In .Net MAUi

### Steps to Reproduce

Open the Attached Zip And Check the Button's Method so you can see like HomeIndicator Auto Hidden Not Working In .Net MAUi

### Link to public reproduction project repository

https://github.com/Sohel3798/HomeIndicatorAutoHidden.git

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

**Comment by Sohel3798** [comment]
![Uploading IMG_8455.png…]()

**Comment by Sohel3798** [comment]
![Simulator Screenshot - iPhone 14 Pro Max - 2023-07-20 at 14 20 42](https://github.com/dotnet/maui/assets/93022175/8b55a216-51c2-40ec-b0fc-88202bee33b1)

**Comment by Sohel3798** [comment]
Hello MAUI Team Any Update On This Issue?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on iOS 16.4(8.0.100-preview.6.23330.14) with below Project:
[HomeIndicatorAutoHidden.zip](https://github.com/dotnet/maui/files/12299978/HomeIndicatorAutoHidden.zip)

**Comment by marcoablanco** [comment]
Still not working on Net8.

**Comment by Higeneko9** [comment]
After spending several hours looking at the MAUI source code, I've figured out how i can hide the home indicator with the following steps:

1. Create a custom PageViewController that overrides the PrefersHomeIndicatorAutoHidden property, which always returns true.
2. Create a custom PageHandler which creates a custom view controller.
3. Replace the PageHandler with new custom PageHandler in service.

Custom PageViewController class code:

```
  public class MyPageViewController(IView page, IMauiContext mauiContext)
      : PageViewController(page, mauiContext)
  {
      public override bool PrefersHomeIndicatorAutoHidden => true;
  }
```

Custom PageHandler class code:
```
  using ContentView = Microsoft.Maui.Platform.ContentView;
  
  public class MyPageHandler : PageHandler
  {
    protected override ContentView CreatePlatformView()
    {
      ViewController ??= new MyPageViewController(VirtualView, MauiContext!);
      return base.CreatePlatformView();
    }
  }
```

Replace the PageHandler with new PageHandler in service:
```
  public static partial void InitApp(IServiceProvider services)
  {
      var handlerFactory = services.GetService(typeof(IMauiHandlersFactory)) as IMauiHandlersFactory;
      var handlers = handlerFactory!.GetCollection();
      handlers.TryGetService(typeof(Page), out var descriptor);
      
      // Add a new PageHandler that returns a view controller with the home indicator disabled.
      handlers.Remove(descriptor!);
      handlers.AddHandler<Page, MyPageHandler>();
  }
```

You need to call that InitApp method from MauiProgram.cs:
```
  public static MauiApp CreateMauiApp()
  {
    // Builder code...
    var mauiApp = builder.Build();
    CrossPlatform.InitApp(mauiApp.Services);
    return mauiApp;
  }
```

Note that all codes are iOS specific code except CreateMauiApp part.

This code works both simulator and actual device for me.
