### ISSUE TITLE
Tab key doesn't move between Entry fields on Mac Catalyst

### ISSUE THREAD

**Issue by agingo** [dotnet/maui#16255]
@davidortinau The issue with moving between entry fields on Mac Catalyst still exists in the most recent Visual Studio release.  

Here's the original ticket that was closed https://github.com/dotnet/maui/issues/8473
        

---------------------------------
              Hi @davidortinau. We have added the "s/try-latest-version" label to this issue, which indicates that we'd like you to try and reproduce this issue on the latest available public version. This can happen because we think that this issue was fixed in a version that has just been released, or the information provided by you indicates that you might be working with an older version.

You can install the latest version by installing the latest Visual Studio (Preview) with the .NET MAUI workload installed. If the issue still persists, please let us know with any additional details and ideally a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md) provided through a GitHub repository.

_Originally posted by @msftbot[bot] in https://github.com/dotnet/maui/issues/8473#issuecomment-1400457370_

**Comment by mhrastegari** [comment]
Same issue :"(

**Comment by mattleibow** [comment]
This is now fixed in .NET 7 and .NET 8
