### ISSUE TITLE
Maui 8 preview 6 Visual studio 2022 preview 4 - Cannot build android or iOS blank app (windows host)

### ISSUE THREAD

**Issue by developer9969** [dotnet/maui#16259]
### Description

Cannot build android blank app

### Steps to Reproduce

1.  I have downloaded and installed the latest Android 34 sdk in tools
2. Create a new .net 8 maui app using the latest preview and visual studio.
3. build the app  and you get

![image](https://github.com/dotnet/maui/assets/16970109/2bd8223d-9e7d-4db2-9ac0-4723fe1388b9)

What Am I Missing ?  Should it just build? 

**iOS**
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error loading partial Info.plist template file 'obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist': Could not find a part of the path 'D:\TEMP\Maui8Prev6VSPrev4\Maui8Prev6VSPrev4\obj\Debug\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist'.
        	Maui8Prev6VSPrev4	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8646-net8-p6\tools\msbuild\iOS\Xamarin.Shared.targets	535	

### Link to public reproduction project repository

just create a  blank app

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Version 17.7.0 Preview 4

### Did you find any workaround?

No

### Relevant log output

```shell
n
```

**Comment by RisingDragoon** [comment]
Hi,
I had the same problem. 
You could try this solution:
https://learn.microsoft.com/en-us/answers/questions/1178661/how-to-fix-error-dep0700-maui-net7-0

**Comment by mattleibow** [comment]
This should now be working in the latest preview versions of VS.
