### ISSUE TITLE
Error JAVAC0000 error: no suitable constructor found for BaseCellView(Context,AttributeSet,int,int)

### ISSUE THREAD

**Issue by jeanhibbert** [dotnet/maui#16278]
### Description

I can deploy and test the debug version of my android app on my Android phone but the release version displays error: 

Severity Code Description Project File Line Suppression State
Error JAVAC0000 error: no suitable constructor found for BaseCellView(Context,AttributeSet,int,int)
super (p0, p1, p2, p3);
constructor BaseCellView.BaseCellView(Context) is not applicable
(actual and formal argument lists differ in length)
constructor BaseCellView.BaseCellView(Context,AttributeSet) is not applicable
(actual and formal argument lists differ in length)
constructor BaseCellView.BaseCellView(Context,AttributeSet,int) is not applicable
(actual and formal argument lists differ in length)
XYZ ...\obj\Release\net7.0-android\android\src\crc6477f0d89a9cfd64b1\TextCellRenderer_TextCellView.java 47

### Steps to Reproduce

1. create new complex maui android app
2. Attempt to deploy release version to android phone

### Link to public reproduction project repository

private repository

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

I have not found a workaround

### Relevant log output

```shell
Severity Code Description Project File Line Suppression State
Error JAVAC0000 error: no suitable constructor found for BaseCellView(Context,AttributeSet,int,int)
super (p0, p1, p2, p3);
constructor BaseCellView.BaseCellView(Context) is not applicable
(actual and formal argument lists differ in length)
constructor BaseCellView.BaseCellView(Context,AttributeSet) is not applicable
(actual and formal argument lists differ in length)
constructor BaseCellView.BaseCellView(Context,AttributeSet,int) is not applicable
(actual and formal argument lists differ in length)
XYZ ...\obj\Release\net7.0-android\android\src\crc6477f0d89a9cfd64b1\TextCellRenderer_TextCellView.java 47
```

**Comment by PureWeen** [comment]
@jonathanpeppers

**Comment by PureWeen** [comment]
@jeanhibbert your build errors say "ReleasE" but your description says "Debug" 

does this work in "Debug" ?

**Comment by jonathanpeppers** [comment]
Can you share a sample app with this issue?

The class doesn't have this constructor:

https://github.com/dotnet/maui/blob/ecad65954f1feba75c8184c53103a3f133ef55a4/src/Compatibility/Core.LegacyRenderers/Android/Cells/BaseCellView.cs#L31

But I thought this constructor would only be used at runtime, if you tried to use Android XML. And you got a build error?

**Comment by eengstroem** [comment]
@jeanhibbert Did you ever manage to fix this? Facing the same problem, currently.
