### ISSUE TITLE
A double click (only clicked event defined) on a MenuFlyoutItem adds multiple pages

### ISSUE THREAD

**Issue by DominikErnst** [dotnet/maui#16276]
### Description

When I double click on a MenuFlyOutItem, the page is added to the navigation stack multiple times. This should not happen because I only added an event for click and not for double click.

### Steps to Reproduce

1.  Create a MAUI App
2. Add a Menu to main-page
3. Add a FlyoutItem with a Click Event
4. Add Navigation code to a page in the click Event
5. Click once and one page is added to the Navigation Stack -> OK
6. Double-Click and multiple Pages are added to the navigation Stack -> NOK

```XAML 
   <ContentPage.MenuBarItems>
        <MenuBarItem Text="Extra">
            <MenuFlyoutItem Text="Settings" Clicked="MenuFlyoutItem_Clicked" />
        </MenuBarItem>
        </MenuBarItem>
    </ContentPage.MenuBarItems>`
```

```XAML
    private void MenuFlyoutItem_Clicked(object sender, EventArgs e)
    {
        Navigation.PushAsync(new DataTemplateSelectorPage());
    }
```

### Link to public reproduction project repository

no repo

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

not yet

### Relevant log output

```shell
no log
```

**Comment by zijianhuang** [comment]
Though technically you may use a local variable to flag whether the codes of launching the page should be executed upon the 2nd click, a common practice during the era of Xamarin  is like 
```cs
private async void Settings_Clicked(object sender, EventArgs e)
{
	if (Navigation.ModalStack.Where(x => x is SettingsPage).Any())
	{
		return;
	}

	await Navigation.PushModalAsync(new SettingsPage(viewModel.NotifySettingsChanged)).ConfigureAwait(true);
}
```
