### ISSUE TITLE
DatePicker FontAttributes="Bold" and FontAttributes="Italic" Not Working on IOS or MacCatalyst

### ISSUE THREAD

**Issue by dlent1** [dotnet/maui#16272]
### Description

Setting FontAttributes to bold or italic on the datepicker does not make the text bold or italic.

### Steps to Reproduce

1. Create 2 DatePickers (one with FontAttributes="Bold" and the other with FontAttributes="Italic" 
2. Debug targeting MacCatalyst or IOS
3. Notice that the first datepicker is not bold and the second one is not italic

### Link to public reproduction project repository

https://github.com/dlent1/DatePickerBoldItalicNotWorking/tree/main

### Version with bug

7.0.86

### Last version that worked well

6.0

### Affected platforms

iOS, macOS

### Affected platform versions

IOS 16.5.1 and MacOs Ventura 13.2.1

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on iOS 16.4(8.0.100-preview.6.23330.14), not repro on Windows 11 and Android 13.0-API33 with below Project:
[DatePickerBoldItalicNotWorking.zip](https://github.com/dotnet/maui/files/12300158/DatePickerBoldItalicNotWorking.zip)

![image](https://github.com/dotnet/maui/assets/97647558/6448a8b4-d507-4b99-bc2f-5c22a57beb40)

**Comment by Divyesh-Bhatt** [comment]
Not just for the DatePicker it's same for the Label control as well.
