### ISSUE TITLE
Panning MAUI.Blazor on touch screen cause random crashes

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/maui#16303]
### Description

1. On my computer, panning on MAUI.Blazor works by changing the zooming in a different way than say (ctrl + '+') / (ctrl + '-')
2. Panning would crash randomly, exiting the app, or throw exception say if debugging.
3. Happened to all the apps I've made using MAUI, in .NET 6 & .NET 7

### Steps to Reproduce

Use any MAUI.Blazor app, use it for a while, pan on touch screen hope the app would crash

### Link to public reproduction project repository

N/A

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by javiercn** [comment]
@Xyncgas thanks for contacting us.

Does this happen on a regular webview without Blazor involved?

**Comment by Xyncgas** [comment]
My apps are built on .NET 6 from last year and .NET 7 currently, they are both text editor and I myself find panning the screen crashing the app. I am sorry, I wish I can provide more information, but I don't have application developed using webview outside of MAUI.Blazor and I am not going to test it but it's ok if this is not fixed

**Comment by mkArtakMSFT** [comment]
> My apps are built on .NET 6 from last year and .NET 7 currently, they are both text editor and I myself find panning the screen crashing the app. I am sorry, I wish I can provide more information, but I don't have application developed using webview outside of MAUI.Blazor and I am not going to test it but it's ok if this is not fixed

Can you please share the stacktrace?
