### ISSUE TITLE
android

### ISSUE THREAD

**Issue by christiansiepermann1** [dotnet/maui#16306]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
I'm very sorry but this report does not seem to contain any details as to what issue you're experiencing. If you still would like some help, please open a new issue but add as much detail as possible. Thanks!

**Comment by christiansiepermann1** [comment]
sittin , up

new reading down

xt
