### ISSUE TITLE
.NET Maui 7 app crashes on iOS 17

### ISSUE THREAD

**Issue by JRosanowski** [dotnet/maui#16316]
### Description

Link to discussion.
https://github.com/dotnet/maui/discussions/15540

.Net Maui apps crash on the iOS 17 beta. iOS 17 is being released in September but some people are installing the beta now. Can we have some indication of when this will be fixed? Will there be a .NET Maui 7 release to address it or will it only be addressed in November with the .NET Maui 8 release? 
I assume there's also a dependency on XCode 15?

### Steps to Reproduce

Run a .NET Maui 7 app on iOS 17 beta

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17 Beta

### Did you find any workaround?

No

**Comment by JRosanowski** [comment]
There's a workaround mentioned in the Discussion
https://github.com/dotnet/maui/discussions/15540

**Comment by rolfbjarne** [comment]
> > We'll fix this in [xamarin/xamarin-macios#18621](https://github.com/xamarin/xamarin-macios/pull/18621), and backport the fix to .NET 7 so that the next service release will contain it.
> 
> @rolfbjarne I guess this didn't make it into 7.0.307? Have just updated and rebuilt my project but it is still crashing at launch on iOS 17.

Correct, it was fixed too late for this week's release, it'll be in the next release.

**Comment by Hooterr** [comment]
@rolfbjarne Any word on when that'll be?
iOS 17 release is scheduled between September 13, and September 21, 2023. We can't have our apps just stop working out of the blue.

**Comment by rolfbjarne** [comment]
> @rolfbjarne Any word on when that'll be? iOS 17 release is scheduled between September 13, and September 21, 2023. We can't have our apps just stop working out of the blue.

If all goes well in the next service release.

>  Is there a way to somehow fix this without having to wait for the official release?

Yes. The solution in this discussion explains it: https://github.com/dotnet/maui/discussions/15540#discussioncomment-6554443
