### ISSUE TITLE
Having problems with maui.

### ISSUE THREAD

**Issue by sneppington** [dotnet/maui#16312]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Even though I had MAUI downloaded and I had followed all previous steps I was not capable of finding any option for a MAUI project.

**Comment by jfversluis** [comment]
Hey @sneppington sorry to hear you're having trouble getting started with .NET MAUI!

Can you confirm that you installed Visual Studio and checked the .NET MAUI workload? Are you on Windows? But you don't see the new .NET MAUI project templates, is that correct?

Does it help if you open a command-line window and execute `dotnet new install Microsoft.Maui.Templates`, what output does that give? And if it seems successful, does it show the templates in Visual Studio now?
