### ISSUE TITLE
My shadows are not rendering correctly on Samsung S21 [API 33]

### ISSUE THREAD

**Issue by GlacierFox** [dotnet/maui#16311]
### Description

Shadows are not rendering correctly on my physical Samsung Galaxy S21, however they look fine on my emulator. 
I have updated the phone to the latest available version **(Build Number - TP1A.220624.014.G991BXXS9EWF3)**. This looks like the problem mentioned in the closed issue  #10401 .  Can't seem to find a workaround for this fairly popular device.
Here's a screenshot. 

| | |
|:-:|:-:|
| ![255354537-c1daea7c-fb54-44cd-b526-f359f9f26326](https://github.com/dotnet/maui/assets/9074086/7504085f-2820-4411-b3b7-38fb5406d0f6) | ![Screenshot_20230723_120436_Settings](https://github.com/dotnet/maui/assets/9074086/e88085c4-3c52-44b2-95eb-00575cd4329e) |

I've noticed that if I put negative numbers in the XAML shadow code it sort of smooths it out on the top and left edges but as you can see below, there's still a strange hard edge on the end of them.

 ```
<Label.Shadow>
    <Shadow Brush="Black"
                    Radius="40"
                    Offset="-20,-30"
                    Opacity="0.8"/>
</Label.Shadow>
```

| | As you can see below, it works fine on my emulator.|
|:-:|:-:|
| <img src="https://github.com/dotnet/maui/assets/9074086/c7c4a7b8-f769-4a9e-8896-3a57bd45a961" width="400" /> | <img src="https://github.com/dotnet/maui/assets/9074086/333b9197-e0fb-47d4-aeaf-27cd84f7a690" width="470" />|

### Steps to Reproduce

1. Create a new Dotnet Maui App
2. Create a simple label or any other visual element with shadow capability.
3. Debug on android device.
4. Result

### Link to public reproduction project repository

https://github.com/GlacierFox/MauiShadowError 

### Version with bug

7.0.86

### Last version that worked well

No previous version seems to work.

### Affected platforms

Android

### Affected platform versions

API 13 (Build Number - TP1A.220624.014.G991BXXS9EWF3)

### Did you find any workaround?

No workaround.

### Relevant log output

No meaningful errors found.

**Comment by GlacierFox** [comment]
Here's a simple repro project I created to showcase the shadow problem:
[](https://github.com/GlacierFox/MauiShadowError)

@jsuarezruiz 

I've just ran it on my physical Samsung Galaxy S21 and also my Samsung Galaxy Tab A7 Lite and I'm getting the same shadow errors. They both look to be on the same build number as mentioned above. This is what it looks like:
![Screenshot_20230724_164229](https://github.com/dotnet/maui/assets/9074086/ecbb35d9-7b41-4798-9680-7acbfe900482)


I then ran the exact same project in my API 33 - Android 13 Emulator and it looks fine as you can see below. I've also included an image of the current emulator device details:

![Screenshot 2023-07-24 164018](https://github.com/dotnet/maui/assets/9074086/4cfcb9b1-780b-4202-994b-a8f60dc71b34)

![Screenshot 2023-07-24 160928](https://github.com/dotnet/maui/assets/9074086/d1924cf6-ad78-4c1f-800a-64b965bfb0e3)


I haven't been able to find a work-around for this problem and the shadows look terrible on my physical devices.

**Comment by drasticactions** [comment]
Reopened the other issue, closing this as a dupe, https://github.com/dotnet/maui/issues/16311
