### ISSUE TITLE
DisplayAlert Displaying Beneath PopupPage (Mopups) on iOS

### ISSUE THREAD

**Issue by ESO-ST** [dotnet/maui#16321]
### Description

On iOS, using DisplayAlert from a Mopups PopupPage causes the alert to be displayed under the PopupPage.
[Here's a link](https://github.com/LuckyDucko/Mopups/issues/66) to the Mopups ticket.

### Steps to Reproduce

1. Show a popup page (Mopups)
2. Display an alert

**Expected**
Alert to be shown in front of the popup page.
**Actual**
Alert is shown behind the popup page.

### Link to public reproduction project repository

https://github.com/LuckyDucko/Mopups/issues/66

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by ESO-ST** [comment]
I tried this in 8.0.0-RC1 but the issue is still there, alerts are still showing up behind Mopups popup on iOS.

**Comment by PureWeen** [comment]
> I tried this in 8.0.0-RC1 but the issue is still there, alerts are still showing up behind Mopups popup on iOS.

Do you have a repro? Make sure you are calling the popup code on the mopup page itself not the pages under the mopup. 

I tested with the latest RC1 against the mopups sample project and it works for me

![image](https://github.com/dotnet/maui/assets/5375137/a09a5bba-e7df-40d2-b127-a6f51122e589)

**Comment by ESO-ST** [comment]
Okay I was able to verify that when calling DisplayAlert from the popup page itself, then it works properly, otherwise it will display behind it.
I also verified that in Xamarin this limitation was not there, if we had a parent page and an rg.plugins.popup page on top, calling DisplayAlert from the parent page will also display the alert on top of the popup page.

Is this new limitation a bug or working as intended? I'd imagine Alerts always displaying at the very front on top of everything else.

**Comment by PureWeen** [comment]
> Okay I was able to verify that when calling DisplayAlert from the popup page itself, then it works properly, otherwise it will display behind it. I also verified that in Xamarin this limitation was not there, if we had a parent page and an rg.plugins.popup page on top, calling DisplayAlert from the parent page will also display the alert on top of the popup page.
> 
> Is this new limitation a bug or working as intended? I'd imagine Alerts always displaying at the very front on top of everything else.

It's intended 

In Xamarin.Forms the popups were all new UIWindows, but we changed those in MAUI to just be modals. 
Mopups displays all its page as a UIWindow. 

All of this combined with the fact that MAUI supports multi-window, we can't really just guess what UIWindow you want a popup to display on top of. Just detecting whatever window is visible is risky, so we leave it to the developer to indicate what page the popup should be associated with.
