### ISSUE TITLE
Prompts are missing when creating a new page

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#16325]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Prompts-are-missing-when-creating-a-new-/10421137)._

---
0. Right click somewhere in a project
1. Choose Add New Class …
2. Select .NET MAUI
3. Click on any page
4. Notice that on the righthand side the description of the page is missing - it just shows the page name (see screenshot)

For those just getting started in .NET MAUI, this is unhelpful - surely it would not take too long to fix this

---
#### Feedback Bot on 7/23/2023, 07:03 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
The MAUI file templates have no description:

https://github.com/dotnet/maui/blob/fdb244d7d4013f9e2c916c285de50834b65c404e/src/Templates/src/templates/maui-contentpage-csharp/.template.config/template.json#L6

VS Mac will use the description if it is there.

**Comment by mprogers** [comment]
So, it looks like you're going to fix .NET 8, but we're using .NET 7 and unable to upgrade (until IT says so).

**Comment by samhouts** [comment]
We'll review the PR for suitability to backport to NET 7. Thanks!
