### ISSUE TITLE
[Android] Mysterious back button shows up on root page when navigating back from second page

### ISSUE THREAD

**Issue by mavispuford** [dotnet/maui#16328]
### Description

I've observed this in both .NET 7 and .NET 8 (though I can't reproduce it in .NET 7 with my public repo app - Only with an internal one).  It should be easily reproducible in .NET 8 Preview 6.

Often when going back from a page that was pushed onto the stack, a back button will show up on the root page that does nothing.  If you tap it and hold, it will say "Open navigation drawer".  

In our internal .NET 7 app, it doesn't matter how quickly you tap the back button.  You can tap it 10 seconds after the page has completed loading and it will still happen.  For .NET 8, it seems like you have to navigate and tap back quickly to reproduce it reliably.

In my experience, the issue tends to be worse if either page has a `TitleView`.

![GIF here](https://github.com/mavispuford/ShellBackButtonIssue/blob/main/Media/BackButtonIssue.gif?raw=true)

### Steps to Reproduce

1. Create a new app
2. Add a button to the main page that navigates to a new page
3. Run the app
4. Click on the button to navigate to the new page, then quickly navigate back using the back button above

### Link to public reproduction project repository

https://github.com/mavispuford/ShellBackButtonIssue

### Version with bug

7.0.92
8.0.0-preview.6.8686

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13+

### Did you find any workaround?

No

### Relevant log output

```shell
dotnet workload list

Installed Workload Id      Manifest Version                            Installation Source
-----------------------------------------------------------------------------------------------------------
maui-ios                   8.0.0-preview.6.8686/8.0.100-preview.6      VS 17.6.33829.357, VS 17.7.33913.275
maui-android               8.0.0-preview.6.8686/8.0.100-preview.6      VS 17.6.33829.357, VS 17.7.33913.275
maccatalyst                16.4.8646-net8-p6/8.0.100-preview.6         VS 17.6.33829.357, VS 17.7.33913.275
maui-windows               8.0.0-preview.6.8686/8.0.100-preview.6      VS 17.6.33829.357, VS 17.7.33913.275
maui-maccatalyst           8.0.0-preview.6.8686/8.0.100-preview.6      VS 17.6.33829.357, VS 17.7.33913.275
ios                        16.4.8646-net8-p6/8.0.100-preview.6         VS 17.6.33829.357, VS 17.7.33913.275
android                    34.0.0-preview.6.359/8.0.100-preview.6      VS 17.6.33829.357, VS 17.7.33913.275
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue does not repro on Windows 11(8.0.100-preview.6.23330.14), Android 13.0-API33 and iOS 16.4 with below Project:
[ShellBackButtonIssue.zip](https://github.com/dotnet/maui/files/12318326/ShellBackButtonIssue.zip)

![BackButton](https://github.com/dotnet/maui/assets/97647558/3fc5abcd-7013-4a80-919c-91ef3a379325)
