### ISSUE TITLE
[regression/8.0.0-preview.5.8529] Grid with a star and an empty auto column leads to an incorrect layout

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#16334]
### Description

When using a `Grid` layout with `*` and `Auto` columns and there is no content in the `Auto` column, the result layout is incorrect.

For example, consider the following `Grid` layout:

```xml
<Grid ColumnDefinitions="*, Auto" RowDefinitions="Auto, *">
    <Label Grid.Row="0" Text="First Name" />
    <Entry Grid.Row="1" />
</Grid>
```

The above `Grid` contains children in the `*` column only, while the `Auto` is empty. The following screenshot demonstrates how the layout appears initially:

![image](https://github.com/dotnet/maui/assets/98032058/addbff87-47a7-45aa-bff0-c6581b333c00)

After resizing the window, the layout appears correctly:

![image](https://github.com/dotnet/maui/assets/98032058/7c0cf09d-bcc5-4baf-8cf8-0e973addb6af)

The above screenshot is on Windows, but similar problems can be observed on the other platforms as well.

### Steps to Reproduce

1. Run the sample project from the provided link.
2. Observe the incorrect initial layout.
3. Resize the window or rotate the phone/tablet.
4. Observe the correct layout after resizing.

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/GridStarAutoEmptyIncorrectLayout

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

7.0.86

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

N/A

**Comment by Stedy59** [comment]
You specified two columns, but the grids children have no grid column value. The documentation for Maui Grid states... You must specify row and/or column if more than one. Xamarin would "kind of" figure that out for you, but moving forward, Maui doesn't. Hope that helps.

**Comment by ivan-todorov-progress** [comment]
@Stedy59 If `Grid.Column` is not explicitly specified, it defaults to 0. Please, keep in mind that this is a repro project, stripped down for simplicity. The actual use case is more sophisticated than that, but I have omitted some unrelated details.

For example, I have the following requirement:

- On desktop, put the Label to the left of the Entry;
- On mobile, put the Label above the Entry;

One way to accomplish this is to duplicate all views for desktop and mobile, but that would be tedious and difficult to maintain. Another option is to use the a `Grid` with sufficient rows and columns in combination with the `OnIdiom` markup extension:

```xml
<Label Grid.Column="{OnIdiom Default=0, Phone=1}" Grid.Row={OnIdiom Default=1, Phone=0}" />
```

That is just one example. Another case is to have a child in an `Auto` column, which is shown or hidden based on a condition. I can give such examples, but I believe you get the idea.

The problem is that when we have an `Auto` column, which does not have a visible content, the `Grid` ignores the sizes of the rest of its children and simply evaluates the row height to 0. And that is done only initially. Resizing the window or rotating the device recomputes the layout this time correctly.

**Comment by Stedy59** [comment]
Try this...

`<VerticalStackLayout`
`	Spacing="10">`
`	<StackLayout`
`		Spacing="10"`
`		Orientation="{OnIdiom Default='Horizontal', Phone='Vertical'}">`
`		<Label`
`			Text="First Name:"/>`
`		<Entry`
`			MinimumWidthRequest="200"/>`
`	</StackLayout>`
`	<StackLayout`
`		Spacing="10"`
`		Orientation="{OnIdiom Default='Horizontal', Phone='Vertical'}">`
`		<Label`
`			Text="Last Name:"/>`
`		<Entry`
`			MinimumWidthRequest="200"/>`
`	</StackLayout>`
`</VerticalStackLayout>`

Make the inner StackLayout a global style, and use everywhere.

**Comment by ivan-todorov-progress** [comment]
@Stedy59 Thanks for the suggestion. I have a workaround for my particular scenario, but it is more involved. I am reporting a regression in the `Grid` layout that wored with the latest official version, but was broken in the latest preview, in hope Microsoft would have enough time to fix it before .NET 8 goes official.

**Comment by Redth** [comment]
Just to add a bit more context, the sample project repros but the sample in the issue description does not.

It seems like the condition here is when there's an auto/unbound measure involved only.  If you just put the one Grid (First Name with entry) in a page, it doesn't repro, but as soon as I nest it inside a VerticalStackLayout (or even inside a <Grid RowDefinitions="Auto">) it repros.

So, without going into the repro project, you can simply use this XAML:

```
<VerticalStackLayout Margin="20">
    <Grid ColumnDefinitions="*, Auto" RowDefinitions="Auto, *" ColumnSpacing="10" RowSpacing="10">
        <Label Grid.Row="0" Text="First Name" />
        <Entry Grid.Row="1" />
    </Grid>
</VerticalStackLayout>
```

**Comment by hartez** [comment]
So this and #16368 are the same bug.
