### ISSUE TITLE
Add hooks to disconnect/connect a PlatformView from a Handler in order to avoid memory leaks

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#16332]
### Description

It's becoming too difficult on iOS to construct controls in such a way that they will just GC all on their own. It's also becoming obvious that we need to give developers better guidance on where they can connect/disconnect. 

This proposes some additional life cycle hooks that don't completely remove the platform view from the handler. 

At the `Controls` level we'll tie these calls to when something has been added/removed from the VisualTree. UI Frameworks can decide when they want to call these. I like this approach over adding `AddedToVisualTree`/`RemovedFromVisualTree`, mainly because those are a bit tricky to do in a completely accurate way that meets expectations of what it means to be "ready" on the visual tree. For example, on WinUI do we fire this before or after the `ApplyTemplate` runs? 

### Use Case
- We need a place inside the `ViewHandler` where users can put code to wire/unwire from platform events. Users can use this as a place to wire into the `VirtualView` as well, but this is primarily a place where users can subscribe/unsubscribe from platform events that might cause memory leaks.   A more accurate name might be `DisconnectAnythingThatMightLeak`

### (Public) API Changes

```C#
public interface IElementHandler
{
     void Disconnect(bool isDestroying) { }
     // This should possibly include "oldVirtualView", "newVirtualView"  if this fires from SetVirtualView
     void Connect() { } 
}
```

### Usage Scenarios

```C#
public partial class ButtonHandler : ViewHandler<IButton, MaterialButton>
{
		protected override void Connect() 
		{
			ClickListener.Handler = this;
			platformView.SetOnClickListener(ClickListener);

			platformView.FocusChange += OnNativeViewFocusChange;
			platformView.LayoutChange += OnPlatformViewLayoutChange;
		}

		protected override void Disconnect(bool isDestroying) 
		{
			ClickListener.Handler = null;
			platformView.SetOnClickListener(null);

			platformView.FocusChange -= OnNativeViewFocusChange;
			platformView.LayoutChange -= OnPlatformViewLayoutChange;
			
			if (isDestroying)
			{
			     
			}
		}
}
```

### Backward Compatibility

N/A

### Difficulty

Medium

**Comment by RobTF** [comment]
Yes please!!! +1 to this. The Dispose/Cleanup story in MAUI is a mess. I've tried doing stuff like waiting for handlers to become `null` and half the time it never happens, and when it does it is inconsistent per-platform making it unreliable and dangerous to use.

Also, we need something analogous to this for `AppendToMapping`.

For example, if I use `AppendToMapping` and wire up events such as theme changes etc. where do I disconnect them???

```
MapHandler.Mapper.AppendToMapping("MyAppendedLogic", async (handler, map) =>
{
     // where do I clean up???
});
```

**Comment by haavamoa** [comment]
Is there any progress on this? I noticed the focus from MAUI on memory leaks in .NET 8. But we are yet to have a very stable and essy way to dispose our objects in MAUI as I see it. I am a library author and rigjHT now I have no idea how to create a simple view that is 100% memory leak safe without the consumers having to explicity make sure to dispose every view/effect/behavior I create. This has to be a major issue for projectes like CommunityToolkit as well?

Correct me if I am wrong, but didnt the Handlers,Effects and Behavior disconnecting methods run in previous versions of MAUI? I’m sure I’ve debugged and made sure theese run when people navigate out of pages before…

**Comment by haavamoa** [comment]
In lack of progress on this, I've done some research on `UnLoaded` and `Loaded` events. From this I've created this best practices for the developers in my company. If possible, a comment on if this approach will work would be nice.

https://github.com/DIPSAS/DIPS.Mobile.UI/wiki/Memory-Leaks

**Comment by AdamEssenmacher** [comment]
@PureWeen you are 1000% right that we need an architectural answer to this systemic problem. Lacking an official solution, I've cobbled one together that achieves this as an attached property and has been working well for me the last couple weeks: https://github.com/AdamEssenmacher/MemoryToolkit.Maui

**Comment by PureWeen** [comment]
> In lack of progress on this, I've done some research on `UnLoaded` and `Loaded` events. From this I've created this best practices for the developers in my company. If possible, a comment on if this approach will work would be nice.
> 
> https://github.com/DIPSAS/DIPS.Mobile.UI/wiki/Performance#clean-up

This is great!

This would be my recommendation at the handler level as well really.

Android => Watch the PlatformAttached event
Windows => Watch the loaded/unloaded
iOS => Subclass the view and override MovedToWindow

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/pull/23738
