### ISSUE TITLE
[regression/8.0.0-preview.6] SwipeView breaks binding

### ISSUE THREAD

**Issue by Starchm** [dotnet/maui#16345]
### Description

When adding a swipeview inside the datatemplate, it breaks the binding, when i remove it, the values will be shown.

It was working in 8.0 public preview 5:
Android:
![resizedpreview5](https://github.com/dotnet/maui/assets/29771467/bf1b688c-1472-42ab-baca-4ad073b6fe61)

Windows:
![Screenshot 2023-07-24 201524](https://github.com/dotnet/maui/assets/29771467/c4a7f258-f2c7-4489-82d4-6bf813d447d9)

Its broken in the latest 8.0 public preview 6:
Android:
![resizedpreview6](https://github.com/dotnet/maui/assets/29771467/51c8b134-d6fc-4426-b003-ba3ff3ca4f98)

Windows:
![Screenshot 2023-07-24 202729](https://github.com/dotnet/maui/assets/29771467/cfea821f-470c-4a96-9244-76879d6c6ad7)

Collectionview inside the xaml
```
<CollectionView x:Name="cv">
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <SwipeView>
                            <StackLayout>
                                <Label BackgroundColor="Red" Text="{Binding .}">
                                </Label>
                            </StackLayout>
                        </SwipeView>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>
```

### Steps to Reproduce

1.Create a new project in the .NET MAUI application.
2. Add a collectionview in XAML.
3. Create a string list as itemsource for the collectionview from code-behind.
4. Put a swipeview inside the datatemplate.
5. Put a label inside the swipeview and bind its text to the current elements value.

Expected:
The list will show the values.

Actual:
List text values will be missing.

### Link to public reproduction project repository

https://github.com/Starchm/bindingbug

### Version with bug

8.0.0-preview.6

### Last version that worked well

8.0.0-preview.5.8529

### Affected platforms

Android, Windows

### Affected platform versions

Android 13, windows10.0.19041.0

**Comment by jerry2007** [comment]
Same problem, please fix it...

**Comment by ValonK** [comment]
Experiencing the same issue on **8.0.0-preview.6**

**Comment by tranb3r** [comment]
Also happening with **8.0.0-preview.7**

**Comment by OleksiyVerkhorobin** [comment]
![2023-08-14_02-28-53-PM](https://github.com/dotnet/maui/assets/142259064/34f5c240-d4f8-4d8e-bfd1-16061f8438b1)
![2023-08-14_02-27-51-PM](https://github.com/dotnet/maui/assets/142259064/41e41df4-3a98-49a1-81a4-732a66079535)

**Comment by OleksiyVerkhorobin** [comment]
Same happens within iOS: the first screen represents untouched project (no binding) and the second one - works as expected, if you change SwipeView to ContentView just to confirm that SwipeView causes reported issue.
