### ISSUE TITLE
Multi line editor height issue in .NET MAUI Editor control

### ISSUE THREAD

**Issue by Kerubananthan3761** [dotnet/maui#16341]
### Description

The height of the multi-line editor control in Microsoft .NET MAUI remains the same when the "Enter" key is pressed to move to the second line. The height of the control only changes when a value is actually entered in the editor.
Requirement: The height of the control has to change while the "Enter" key is pressed to move to the second line.

### Steps to Reproduce

1. Create a new project in the .NET MAUI application.
2. Add Editor control in the XAML file.
3. Wire Text changed event for the editor.
4. Set the initial height of the editor control.
5. Check for the editor height value in the event by using ComputeDesiredSize() method.
6. Enter any value in the editor and check the height. 
![image](https://github.com/dotnet/maui/assets/104969840/f7a77b80-bc01-4d97-b0e3-204e76b442a9)

7. Press the "Enter" key to move to the second line in the editor without entering any text.
![image](https://github.com/dotnet/maui/assets/104969840/9d4302d0-208c-46f0-a647-7766a700601c)

8. Enter any value in the editor's second line and check the height.
![image](https://github.com/dotnet/maui/assets/104969840/aed2454f-fba5-4efa-bed9-1bca52275d1e)

### Link to public reproduction project repository

[MauiApp1.zip](https://github.com/dotnet/maui/files/12162464/MauiApp1.zip)

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11(8.0.100-preview.7.23376.3), not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[16341.zip](https://github.com/dotnet/maui/files/12319068/16341.zip)

**Comment by Foda** [comment]
Hello! When using the `Editor` control you need to use the [AutoSize](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/editor#auto-size-an-editor) property set to `TextChanges` to allow it to resize vertically on new lines.

The following code should work:
```xaml
<Border Background="Yellow">
    <Editor WidthRequest="100" VerticalOptions="Center" AutoSize="TextChanges"/>
</Border>
```
