### ISSUE TITLE
[regression/7.0.92] [Android] Grid contents and layout are messed up by Picker changes

### ISSUE THREAD

**Issue by mavispuford** [dotnet/maui#16354]
### Description

_I've observed this in both .NET 7 and .NET 8 Preview 6_

I have a `Grid` with `Labels` on the left and other elements on the right.  If I select different values from a `Picker`, the `Grid`'s layout gets messed up.  Also the child elements don't redraw in some cases, so they appear to be empty until you interact with them.

![Demonstration](https://raw.githubusercontent.com/mavispuford/MauiGridLayoutIssue/main/Media/GridWithPicker.gif)

### Steps to Reproduce

1. Create a new app
2. Make the main layout on the main page a `Grid` with a few rows (auto is fine) and two columns (auto,*)
3. Add `Labels` on the left column and other elements on the right, one of them being a `Picker` with choices of varying lengths
4. Run the app
5. Pick different values from the `Picker` and notice that the `Grid` layout changes (it gets compacted) and some of its elements (`Entry` for example) don't seem to redraw

### Link to public reproduction project repository

https://github.com/mavispuford/MauiGridLayoutIssue

**Branches**:
**.NET 7** - use [`Net7Version`](https://github.com/mavispuford/MauiGridLayoutIssue/tree/Net7Version)
**.NET 8** - use [`main`](https://github.com/mavispuford/MauiGridLayoutIssue/tree/main)

### Version with bug

7.0.92
8.0.0-preview.6.8686

### Last version that worked well

7.0.86

### Affected platforms

Android

### Affected platform versions

Android 13+

### Did you find any workaround?

It looks like setting a `WidthRequest` on the `Picker` prevents it from happening.  

### Relevant log output

```shell
dotnet workload list

Installed Workload Id      Manifest Version                            Installation Source
-----------------------------------------------------------------------------------------------------------
maui-ios                   8.0.0-preview.6.8686/8.0.100-preview.6      VS 17.6.33829.357, VS 17.7.33913.275
maui-android               8.0.0-preview.6.8686/8.0.100-preview.6      VS 17.6.33829.357, VS 17.7.33913.275
maccatalyst                16.4.8646-net8-p6/8.0.100-preview.6         VS 17.6.33829.357, VS 17.7.33913.275
maui-windows               8.0.0-preview.6.8686/8.0.100-preview.6      VS 17.6.33829.357, VS 17.7.33913.275
maui-maccatalyst           8.0.0-preview.6.8686/8.0.100-preview.6      VS 17.6.33829.357, VS 17.7.33913.275
ios                        16.4.8646-net8-p6/8.0.100-preview.6         VS 17.6.33829.357, VS 17.7.33913.275
android                    34.0.0-preview.6.359/8.0.100-preview.6      VS 17.6.33829.357, VS 17.7.33913.275
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33(8.0.100-preview.7.23376.3), not repro on Windows 11 and iOS 16.4 with below Project:
[GridLayoutIssue.zip](https://github.com/dotnet/maui/files/12319229/GridLayoutIssue.zip)

**Comment by PureWeen** [comment]
Tested this sample against latest GA and can't reproduce
