### ISSUE TITLE
[Bug] No visual ripple on Button tap

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1635]
### Description

When tapping buttons in the Maui.Controls.Gallery sample I don't see any visible effect like the material ripple on the Buttons. 

### Expected Behavior

I should see the default material design effect on Android.

### Actual Behavior

The buttons don't do anything visually. No down/pressed, up states, etc.

### Basic Information

- Version with issue: pre6

**Comment by jsuarezruiz** [comment]
Testing with Preview 11, this issue is already fixed.
