### ISSUE TITLE
After Visual Studio for MAC Update My App Crash On Launch on IOS

### ISSUE THREAD

**Issue by skotzageorgiouRDC** [dotnet/maui#16362]
### Description

After update visual studio for mac to version 17.6.1 (build 452)
All ios new builds apps when i open it crash.

the crash log for the appstore is bellow.

Incident Identifier: 5F82976C-365F-4E3E-96F4-25BA61D04D11
Hardware Model:      iPhone12,3
Process:             Medimall [9719]
Path:                /private/var/containers/Bundle/Application/F9E17567-0E52-41EF-BD10-B0BB58F567C9/Medimall.app/Medimall
Identifier:          com.rdc.ios.medimall
Version:             230724.1 (230724.1)
AppStoreTools:       14E221
AppVariant:          1:iPhone12,3:16
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.rdc.ios.medimall [2519]

Date/Time:           2023-07-24 12:24:02.8034 +0300
Launch Time:         2023-07-24 12:23:58.6785 +0300
OS Version:          iPhone OS 16.5.1 (20F770750d)
Release Type:        User
Baseband Version:    4.02.01
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_PROTECTION_FAILURE at 0x000000016ae8bff8
Exception Codes: 0x0000000000000002, 0x000000016ae8bff8
VM Region Info: 0x16ae8bff8 is in 0x16ae88000-0x16ae8c000;  bytes after start: 16376  bytes before end: 7
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_TINY              128000000-128100000 [ 1024K] rw-/rwx SM=PRV  
      GAP OF 0x42d88000 BYTES
--->  STACK GUARD              16ae88000-16ae8c000 [   16K] ---/rwx SM=NUL  ... for thread 0
      Stack                    16ae8c000-16af88000 [ 1008K] rw-/rwx SM=PRV  thread 0
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [9719]

### Steps to Reproduce

I followed the prescribed procedure

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

7.0.49

### Last version that worked well

7.0.86

### Affected platforms

iOS

### Affected platform versions

IOS

**Comment by borrmann** [comment]
Oftentimes deleteing the Xamarin/Cache folder helps (located in <usernemae>\library\Caches\Xamarin
