### ISSUE TITLE
[regression/8.0.0-preview.6] Image not loading

### ISSUE THREAD

**Issue by jitendrajadav** [dotnet/maui#16364]
### Description

Seems like .NET 8 Preview 6 Images and SVG not loading having issue
please check this repo:
![Screenshot_1690362501](https://github.com/dotnet/maui/assets/1029026/312c1623-adf6-4290-83a0-5ff7e43e3e4f)
https://github.com/jitendrajadav/MauiApp1

Here is the my IDE :

Microsoft Visual Studio Enterprise 2022
Version 17.7.0 Preview 5.0
VisualStudio.17.Preview/17.7.0-pre.5.0+33920.267
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.50628.1 Commit Hash:f9e713b25f69afd3ced63d934e0722003b73c121
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.23189.3
Profiling support for Python projects.

Python with Pylance   17.0.23189.3
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.7.0
Microsoft SQL Server Data Tools

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Windows Subsystem for Android Barista   1.1.0
Adds a command to the tools menu to start and connect to the Windows Subsystem for Android so you can develop and debug with it from within Visual Studio.

Xamarin   17.7.0.210 (d17-7@f5c03d7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.7.21 (150ec9f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.13 (d17-5/3f21639)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 73df89a
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.5 (191fe02ea)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Steps to Reproduce

1. Create a new sample project.
2. Run this project in android 
3. check images is not working in landing page .net boat image

### Link to public reproduction project repository

https://github.com/jitendrajadav/MauiApp1

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 33

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue does not repro on Android 13.0-API33(8.0.100-preview.7.23376.3), Windows 11 and iOS 16.4 with below Project:
[16364.zip](https://github.com/dotnet/maui/files/12319475/16364.zip)

![image](https://github.com/dotnet/maui/assets/97647558/1617a508-3af9-4ab6-9528-0aae046915da)
