### ISSUE TITLE
[regression/8.0.0-preview.5.8529] Incorrect layout when using a Grid with Star and Auto Columns with a child with HeightRequest placed in the Auto column

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#16368]
### Description

Duplicate of: #14494 A Grid that has two elements inside is not getting laid our properly. The two elements are: an Entry in a Star column, and a Button in an Auto column. The Button has a HeightRequest smaller than the intrinsic size of the Entry. The end result is that the Entry is getting clipped at the bottom.

```
<VerticalStackLayout>
    <Grid ColumnDefinitions="*, Auto">
        <Entry Text="qwerty" />
        <Button Grid.Column="1" HeightRequest="26" />
    </Grid>
</VerticalStackLayout>
```
The order of the ColumnDefinitions is not of great importance because the issue is reproduced even if the first column is Auto:

```
<VerticalStackLayout>
    <Grid ColumnDefinitions="Auto, *">
        <Button HeightRequest="26" />
        <Entry Grid.Column="1" Text="qwerty" />
    </Grid>
</VerticalStackLayout>
```

**The issue is reproduced both with 7.0.92 and 8.0.0-preview.6.8686.** 

### Steps to Reproduce

1. Go to the repo from the link
2. Make sure you have navigated to the folder Maui\GridStarAutoIncorrectLayout
3. Run the project

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/GridStarAutoIncorrectLayout

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

current versions

### Did you find any workaround?

I was not able to find any workarounds.

**Comment by jsuarezruiz** [comment]
Seems similar to https://github.com/dotnet/maui/issues/14494

**Comment by hartez** [comment]
I can reproduce this on Windows. It does not reproduce on iOS or Android.

**Comment by hartez** [comment]
This does not appear to be a Grid layout issue. This is a Windows-specific issue with Button when the Button has an empty `Text` property. 

Until we get this fixed, if you need to have Buttons with no text, you can work around this issue by setting the text to a non-printing character. I'd suggest a zero-width space:

```xaml
<VerticalStackLayout>
    <Grid ColumnDefinitions="*, Auto" >
        <Entry Text="qwerty" />
        <Button Text="&#8203;" Grid.Column="1" />
    </Grid>
</VerticalStackLayout>
```

**Comment by hartez** [comment]
Ah, it _is_ a Grid issue, but the way iOS and Android handle Entry means that it doesn't manifest on those platforms.

**Comment by SmartmanApps** [comment]
> Ah, it _is_ a Grid issue, but the way iOS and Android handle Entry means that it doesn't manifest on those platforms.

Hey @hartez , I'm just wondering if this issue - whatever it's root cause is - might also be the root cause of https://github.com/CommunityToolkit/Maui/issues/1136? That is also an issue on Windows only with GridLength.Auto, so seems like it might be related?

**Comment by hartez** [comment]
> > Ah, it _is_ a Grid issue, but the way iOS and Android handle Entry means that it doesn't manifest on those platforms.
> 
> Hey @hartez , I'm just wondering if this issue - whatever it's root cause is - might also be the root cause of [CommunityToolkit/Maui#1136](https://github.com/CommunityToolkit/Maui/issues/1136)? That is also an issue on Windows only with GridLength.Auto, so seems like it might be related?

It's certainly _possible_, but I can't say for certain without digging into it.

**Comment by SmartmanApps** [comment]
> > Hey @hartez , I'm just wondering if this issue - whatever it's root cause is - might also be the root cause of [CommunityToolkit/Maui#1136](https://github.com/CommunityToolkit/Maui/issues/1136)? That is also an issue on Windows only with GridLength.Auto, so seems like it might be related?
> 
> It's certainly _possible_, but I can't say for certain without digging into it.

Ok, I've seen you've started backporting to .NET 7, so I'll see what happens when that update comes through. Any idea on a timeline for that?
