### ISSUE TITLE
[Android] The measure and arrange methods are not being called in custom layout inside the Shell TabBar.

### ISSUE THREAD

**Issue by Tamilarasan-Paranthaman** [dotnet/maui#16361]
### Description

- I have two app shell tabs, and within each tab, there is a **ScrollView** containing a label. The issue arises when I scroll the application vertically or horizontally in the second tab of the Shell **`TabBar`**.

- I have called the **`InvalidateMeasure`** method during scrolling, but the **`LayoutMeasure`** and **`LayoutArrangeChildren`** methods are not being triggered as expected. This behavior is causing the layout to remain unchanged, and I'm unable to achieve the desired updates during scrolling in the second tab. 

**Note: It's working properly on Windows Platform.**

### Steps to Reproduce

1. Run the attached sample. 
2. Navigate to the second tab and scroll the app vertically

https://github.com/dotnet/maui/assets/93904422/621dd0d2-83c5-44a9-b9f8-6ac3aa48f0da

### Link to public reproduction project repository

https://github.com/Tamilarasan-Paranthaman/MauiAppShellTabBarSample

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue does not repro on Windows 11(8.0.100-preview.7.23376.3), Android 13.0-API33 and iOS 16.4with below Project:
[16361.zip](https://github.com/dotnet/maui/files/12319414/16361.zip)
![Called](https://github.com/dotnet/maui/assets/97647558/7ebc5252-e110-4167-a814-db4dd91a68e0)
