### ISSUE TITLE
OnNavigatedTo is fired when leaving a Modal page

### ISSUE THREAD

**Issue by borrmann** [dotnet/maui#16395]
### Description

When a Modal page is left with Shell.Current.GoToAsync(), both OnNavigatedTo and OnNavigatedFrom are fired once.
When going to a Modal page, OnNavigatedTo is fired twice,

### Steps to Reproduce

1. Create a Modal Page (I used Shell.PresentationMode="ModalAnimated")
2. Set a breakpoint in OnNavigatedTo and in OnNavigatedFrom
4. Go ToPage (I used Shell.Current.GoToAsync)
5. OnNavigateTo hits twice
6. Leave the Modal page with Shell.Current.GoToAsync()
7. Breakpoint in OnNavigatedFrom hits and OnNavigatedTo hits as well

### Link to public reproduction project repository

*fe

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No

**Comment by borrmann** [comment]
Moreover, when leaving the page, OnNavigatedTo of the modal page hits AFTER OnNavigatedTo of the page that I was navigating to. When stuff like StatusBarColor/ etc. are handled in this method, this causes problems.

**Comment by borrmann** [comment]
Well, it is fixed in .NET 8.0 preview 6, but not in the latest version of .NET 7.

**Comment by rajmondburgaj** [comment]
Is there any workaround to this until there is a new stable version?

**Comment by borrmann** [comment]
@rajmondburgaj I guess you could track states yourself and ensure your method only executes once when you enter the page and fire your own event when you leave the page.. that will be annoying to maintain though and will cause issues once you work with fixed events.
