### ISSUE TITLE
[MAUI]The Horizontal Scrolling does not work on MacCatalyst target.

### ISSUE THREAD

**Issue by homeyf** [dotnet/maui#16416]
### Description

The Horizontal Scrolling does not work on MacCatalyst target.

### Steps to Reproduce

**Steps to reproduce:**
1. Download the project https://github.com/rachelkang/recipeSearch and Locate it.
2. Shrink the window small enough 
3. Scroll the icons in "Search by meal type" and "Search by diet" horizontally

**Note:**  This issue also can repro on .NET 8 Preview 7.

**Actual results:**
The Horizontal Scrolling does not work on MacCatalyst target.
![demo3](https://github.com/dotnet/maui/assets/82450723/eb2d27ae-55f5-457d-b16b-4a1cc8bced17)

**Expected Result:**
The Horizontal Scrolling works correctly on MacCatalyst target.
![demo4](https://github.com/dotnet/maui/assets/82450723/146a90b2-09d9-4f05-83bd-5b74a98c5315)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

7.0.92

### Affected platforms

macOS

### Affected platform versions

macOS 16.4

**Comment by jfversluis** [comment]
Still reproduces on .NET 8 GA

**Comment by v-yanfw** [comment]
Verify the issue on MacBook Pro and Mac mini:

- macOS:14.1
- maui: 8.0.3
- maccatalyst: 17.0.8482
- Microsoft.Maui.Controls 8.0.4-nightly.9672+sha.7e636f29c8-azdo.8740130

Result:
MacBook Pro: **Not Repro**
Mac mini: **Repro**

**Comment by QianaJiao** [comment]
Hi, @samhouts , we have some new findings about this bug.
Our previous tests used VNC to remotely connect to the Mac Mini, so there was no horizontal scroll bar.
And this doesn't happen if I use my monitor to connect directly to my Mac, and the scroll bar displays correctly:
![image](https://github.com/dotnet/maui/assets/91244512/fa04a9d2-e9e1-47e7-97c1-fb96ffc30e56)

I guess this is not an issue with the App or SDK, could we close it?

**Comment by kevinxufei** [comment]
Verified this issue on 17.6.8 (build 400) with 8.0.7-nightly.9952+sha.74fbfcbabd-azdo. 8998181，connect the mac directly with the display, and a horizontal scroll bar appears and can be swiped.
![maui1](https://github.com/dotnet/maui/assets/86938401/5681884f-6722-4f32-a5ea-282d650969d1)
