### ISSUE TITLE
Cannot find `ShellHandler` under `Microsoft.Maui.Handlers`

### ISSUE THREAD

**Issue by FreakyAli** [dotnet/maui#16424]
### Description

I want to make some customizations to my Maui Shell but when I try to find its handler for some reason I cannot whereas the Maui documentation seems to just skip it in the list of handlers: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/

![ShellHandler](https://github.com/dotnet/maui/assets/31090457/76ca3192-7a89-460d-8df3-70335b78374a)

Is this something planned for the Future are there any workarounds other than using a Compatibility Renderer??

### Steps to Reproduce

- Create a file.
- Try to find the handler as mentioned above.

### Link to public reproduction project repository

NA

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, I was *not* able test on other platforms

### Affected platform versions

NA

### Did you find any workaround?

NO

**Comment by pictos** [comment]
@FreakyAli there's no Handler for Shell it, you should look for the ShellRenderers

**Comment by FreakyAli** [comment]
@pictos Is there a reason for this?

**Comment by MNADEEMCH** [comment]
Why still we don't have the ShellRenderer in maui?

**Comment by FreakyAli** [comment]
Any updates on this guys?

**Comment by apy534** [comment]
Any update?

**Comment by mattleibow** [comment]
I think the namespace is `Microsoft.Maui.Controls.Handlers`

https://github.com/dotnet/maui/blob/33f5d20be7f847e5dbae37453965fe6e276fc4c0/src/Controls/src/Core/Handlers/Shell/ShellHandler.cs#L10

**Comment by pictos** [comment]
@mattleibow the thing is that just windows and tizen has Handlers for Shell, as you can see [here](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Handlers/Shell/ShellHandler.cs), for other platforms it still uses the renderer

**Comment by FreakyAli** [comment]
@mattleibow I have tried both, @pictos already added a link btw that gives more context.

**Comment by PureWeen** [comment]
it's ShellRenderer on iOS and Android 
ShellHandler on Windows

i.e. https://github.com/dotnet/maui/blob/91ebe27859f3032b9822cb759251a6e83e304b4f/src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellRenderer.cs#L13

https://github.com/dotnet/docs-maui/issues/1958

**Comment by FreakyAli** [comment]
@PureWeen Why was this closed? When will the Handlers get added for iOS and Android? This does not solve my issue!!!

**Comment by PureWeen** [comment]
> I want to make some customizations to my Maui Shell but when I try to find its handler for some reason I cannot whereas the Maui documentation seems to just skip it in the list of handlers

Yea, you can achieve this same customization by inheriting from the ShellRenderer on ios/android.

**Comment by FreakyAli** [comment]
Yeah but aren't Renderers from Xamarin Forms and not Maui and I should be using handlers?

**Comment by FreakyAli** [comment]
@PureWeen Please add some context here!!

**Comment by FreakyAli** [comment]
????????????

**Comment by PureWeen** [comment]
> @mattleibow the thing is that just windows and tizen has Handlers for Shell, as you can see [here](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Handlers/Shell/ShellHandler.cs), for other platforms it still uses the renderer

echoing what @pictos said here. 

Some of the larger components (Shell/NavigationPage) aren't fully reorganized into Handlers.

We recently updated the documentation to show you what platform class to use for each control
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/?view=net-maui-8.0

**Comment by FreakyAli** [comment]
So these will always stay this way is it?
