### ISSUE TITLE
SetAppThemeColor for Label or Entry background colours only works on initial state on release builds

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#16430]
### Description

On release builds only:
When using SetAppThemeColor on label or entry background colours, when a page loads it takes the current app theme correctly. However toggling to light or dark doesn't update it.
This works correctly in debug builds

### Steps to Reproduce

Create a page with a label, set the label background binding like so:
label.SetAppThemeColor(VisualElement.BackgroundColorProperty, Colors.Red, Colors.Blue);

Run the app in release, see the label has the correct background colour.
Toggle the device theme (light to dark for example)
Label and entry backgrounds don't update, but other controls do.

### Link to public reproduction project repository

nope

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

No.
The version with bug options is out of date, it is 7.0.92, the current *production* version of .NET MAUI.

**Comment by Dokug** [comment]
I guess this is the same error as in #16250 and #11662 and should be fixed by #13836 while the workaround currently is to use the BackgroundProperty instead of the BackgroundColorProperty.

At least that was what worked for me and some others as well, I think

**Comment by JohnHDev** [comment]
@Dokug you are correct as the workaround mentioned in those tickets works for both Label and Entry backgrounds, so will close this ticket. Thanks!
