### ISSUE TITLE
Label TextColor does not update on theme change when using FormattedText

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#16431]
### Description

As Span doesn't support StyleClass we are trying to refactor our FormattedText to have no colours so they can be driven from the label text colour.
This works until the theme changes, the label will load the correct colour on first use, but switching from light to dark leaves the label in the light colour, rendering the UI unreadable.

### Steps to Reproduce

Add a label to a page, set the formatted text to a  number of spans but don't specify a text colour for those.
Set the label style you have defined in your Resources, something like:

                new Style(typeof(Label))
                {
                    ApplyToDerivedTypes = true,
                    Class = "TestTitle",
                    Setters =
                    {
                        new Setter { Property = Label.TextColorProperty, Value = AppThemeBindingHelper.Create(Colors.Red, Colors.Blue) }
                    }
                }

Run the app, see the text in the correct colour.
Toggle the theme, the label won't update.

NOTE: Labels with just a Text value do update correctly.

### Link to public reproduction project repository

None

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16, haven't tried android

### Did you find any workaround?

No.
Using 7.0.92.

**Comment by ouma** [comment]
Facing the same issue on Android
