### ISSUE TITLE
Shadow Radius on API 33 not fixxed

### ISSUE THREAD

**Issue by South2AK** [dotnet/maui#16440]
### Description

The new preview version of Visiual Studio should have fixxed the error with the non working SHadows as mentioned in https://github.com/dotnet/maui/issues/10401.

Unfortunetely this still doesnt´t work:
![image](https://github.com/dotnet/maui/assets/48831239/a7793859-5f33-4c60-bd2c-c130b8cd1d7c)

### Steps to Reproduce

1. Create a new MAUI Project
2. Add the following code:
```
<Image
     Source="dotnet_bot.png"
     SemanticProperties.Description="Cute dot net bot waving hi to you!"
     HeightRequest="200"
     HorizontalOptions="Center" >



     <Image.Shadow>
         <Shadow Brush="black" Radius="20" Offset="20,20"/>
     </Image.Shadow>
 </Image>

```

### Link to public reproduction project repository

https://github.com/South2AK/Gutachten

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

API 33

**Comment by drasticactions** [comment]
Reopened the other issue, closing this as a dupe, https://github.com/dotnet/maui/issues/16440
