### ISSUE TITLE
ScrollView sizing issue in Grids in iOS

### ISSUE THREAD

**Issue by bluetreee** [dotnet/maui#16456]
### Description

On iOS, when a ScrollView is sandwiched between two StackLayouts in a three row Grid, the ScrollView can not be scrolled all the way down and the StackLayout in third row is missing.

### Steps to Reproduce

1.  Create a Grid with "*, Auto, *" RowDefinitions.
2.  Place StackLayouts in rows 0 and 2, and a ScrollView in row 1.

Result: On iOS, the ScrollView does not scroll all the way to the bottom (there are three entries on this page and you can only scroll part way down to the second entry) and the StackLayout in row 2 is not visible.

Expected Result: You are able to scroll to the bottom of the ScrollView and the StackLayout in row 2 is visible and fixed to the bottom of the page.  This is the behavior in Android.

### Link to public reproduction project repository

https://github.com/bluetreee/ScrollViewSample

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

**Comment by MarianHristov92** [comment]
I have the same the same issue

`<ScrollView VerticalScrollBarVisibility="Never"
                        BackgroundColor="{AppThemeBinding Light={StaticResource LightGrayLightestColor}, Dark={StaticResource DarkGrayLightestColor}}"
                        HorizontalOptions="FillAndExpand"
                        VerticalOptions="FillAndExpand">
                <Grid Margin="16,16,16,20"
                      HorizontalOptions="FillAndExpand"
                      VerticalOptions="FillAndExpand">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="*" />
                        <RowDefinition Height="*" />
                        <RowDefinition Height="*" />
                        <RowDefinition Height="*" />
                        <RowDefinition Height="*" />
                        <RowDefinition Height="*" />
                    </Grid.RowDefinitions>
                    <Image x:Name="LogoImage"
                           Grid.Row="0"
                           HorizontalOptions="Start"
                           HeightRequest="55"
                           WidthRequest="55"
                           Source="store.png">
                        <Image.Behaviors>
                            <toolkit:IconTintColorBehavior TintColor="{AppThemeBinding Light={StaticResource LightStoreDetailPrimaryColor}, Dark={StaticResource DarkStoreDetailPrimaryColor}}" />
                        </Image.Behaviors>
                        <Image.Margin>
                            <OnPlatform x:TypeArguments="Thickness">
                                <On Platform="iOS" Value="0, 0, 0, 20" />
                                <On Platform="Android" Value="0, 0, 0, 20" />
                            </OnPlatform>
                        </Image.Margin>
                    </Image>
                    <Grid Grid.Row="1">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="2*"/>
                            <ColumnDefinition Width="*"/>
                        </Grid.ColumnDefinitions>
                        <StackLayout Grid.Column="0"
                            Spacing="0">
                            <Label Text="{Binding MyStore.NameLabel}"
                                   FontFamily="ProBold"
                                   TextColor="{AppThemeBinding Light={StaticResource LightGrayDarkestColor}, Dark={StaticResource DarkGrayDarkestColor}}"
                                   FontSize="{Binding Fontsize}"
                                   MaxLines="1"
                                   HorizontalTextAlignment="Start"/>
                            <Label Text="{Binding MyStore.Street}"
                                   FontFamily="ProRegular"
                                   TextColor="{AppThemeBinding Light={StaticResource LightGrayDarkestColor}, Dark={StaticResource DarkGrayDarkestColor}}"
                                   FontSize="{Binding Fontsize}"
                                   MaxLines="1"
                                   HorizontalTextAlignment="Start"/>
                            <Label Text="{Binding MyStore.LocationLabel}"
                                   FontFamily="ProRegular"
                                   TextColor="{AppThemeBinding Light={StaticResource LightGrayDarkestColor}, Dark={StaticResource DarkGrayDarkestColor}}"
                                   FontSize="{Binding Fontsize}"
                                   MaxLines="1"
                                   HorizontalTextAlignment="Start"/>
                            <Label Text="{Binding MyStore.CurrentDayOpeningHours}"
                                   FontFamily="ProBold"
                                   FontSize="{Binding Fontsize}"
                                   MaxLines="1"
                                   Padding="0,0,0,20"
                                   HorizontalTextAlignment="Start"
                                   TextColor="{AppThemeBinding Light={StaticResource LightStoreDetailPrimaryColor}, Dark={StaticResource DarkStoreDetailPrimaryColor}}">
                            </Label>
                        </StackLayout>
                        <Grid Grid.Column="1"
                              ColumnSpacing="10"
                              RowSpacing="10"
                              HorizontalOptions="End">
                            <Grid.RowDefinitions>
                                <RowDefinition Height="45"/>
                                <RowDefinition Height="45"/>
                            </Grid.RowDefinitions>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="45"/>
                                <ColumnDefinition Width="45"/>
                            </Grid.ColumnDefinitions>
                            <Frame Grid.Row="0"
                                   Grid.Column="0"
                                   HasShadow="False"
                                   CornerRadius="5"
                                   Padding="0"
                                   BackgroundColor="{StaticResource PrimaryColor}">
                                <Image Source="map_marker.png"
                                       HeightRequest="25"
                                       HorizontalOptions="Center"
                                       VerticalOptions="Center"/>
                                <Frame.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding NavigateToStoreCommand}"/>
                                </Frame.GestureRecognizers>
                            </Frame>
                            <Frame Grid.Row="0"
                                   Grid.Column="1"
                                   HasShadow="False"
                                   CornerRadius="5"
                                   Padding="0"
                                   BackgroundColor="{StaticResource PrimaryColor}">
                                <Image Source="phone.png"
                                       HeightRequest="25"
                                       HorizontalOptions="Center"
                                       VerticalOptions="Center">
                                    <Image.Behaviors>
                                        <toolkit:IconTintColorBehavior TintColor="{StaticResource WhiteColor}" />
                                    </Image.Behaviors>
                                </Image>
                                <Frame.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding CallStoreCommand}"/>
                                </Frame.GestureRecognizers>
                            </Frame>
                            <Frame Grid.Row="1"
                                   Grid.Column="0"
                                   HasShadow="False"
                                   CornerRadius="5"
                                   Padding="0"
                                   BackgroundColor="{StaticResource PrimaryColor}">
                                <Image Source="clock3.png"
                                       HeightRequest="25"
                                       HorizontalOptions="Center"
                                       VerticalOptions="Center">
                                    <Image.Behaviors>
                                        <toolkit:IconTintColorBehavior TintColor="{StaticResource WhiteColor}" />
                                    </Image.Behaviors>
                                </Image>
                                <Frame.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding OpeningHoursCommand}"/>
                                </Frame.GestureRecognizers>
                            </Frame>
                            <Frame Grid.Row="1"
                                   Grid.Column="1"
                                   HasShadow="False"
                                   IsVisible="{Binding IsPetrolstationAvailable}"
                                   CornerRadius="5"
                                   Padding="0"
                                   BackgroundColor="{StaticResource PrimaryColor}">
                                <Image Source="gas.png"
                                       HeightRequest="25"
                                       HorizontalOptions="Center"
                                       VerticalOptions="Center">
                                    <Image.Behaviors>
                                        <toolkit:IconTintColorBehavior TintColor="{StaticResource WhiteColor}" />
                                    </Image.Behaviors>
                                </Image>
                                <Frame.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding GasPricesCommand}"/>
                                </Frame.GestureRecognizers>
                            </Frame>
                        </Grid>
                    </Grid>
                    <Label Text="{DynamicResource ViewsStoreDetailPageServicesHeaderLabelText}"
                           Grid.Row="2"
                           FontFamily="ProBold"
                           FontSize="{Binding Fontsize}"
                           TextColor="{AppThemeBinding Light={StaticResource LightGrayDarkestColor}, Dark={StaticResource DarkGrayDarkestColor}}"
                           Margin="0,20,0,20"/>
                    <Grid ColumnSpacing="20"
                          Grid.Row="3"
                          PropertyChanged="OnServicesGridPropertyChanged"
                          Margin="0,0,0,20"
                          HorizontalOptions="Center">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="120"/>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="120"/>
                            <ColumnDefinition Width="120"/>
                        </Grid.ColumnDefinitions>
                        <Frame Grid.Row="0"
                               Grid.Column="0"
                               HasShadow="False"
                               CornerRadius="5"
                               Padding="0"
                               BackgroundColor="{StaticResource PrimaryColor}">
                            <Frame.Triggers>
                                <DataTrigger TargetType="Frame"
                                             Binding="{Binding FoodServicesAvailable}"
                                             Value="False">
                                    <Setter Property="IsVisible" Value="False"/>
                                </DataTrigger>
                                <DataTrigger TargetType="Frame"
                                             Binding="{Binding FoodServicesAvailable}"
                                             Value="True">
                                    <Setter Property="IsVisible" Value="True"/>
                                </DataTrigger>
                            </Frame.Triggers>
                            <Image HeightRequest="70"
                                   WidthRequest="70"
                                   HorizontalOptions="Center"
                                   VerticalOptions="Center"
                                   Source="platter.png">
                                <Image.Behaviors>
                                    <toolkit:IconTintColorBehavior TintColor="{StaticResource WhiteColor}" />
                                </Image.Behaviors>
                            </Image>
                            <Frame.GestureRecognizers>
                                <TapGestureRecognizer Command="{Binding FoodServicesTappedCommand}" />
                            </Frame.GestureRecognizers>
                        </Frame>
                        <Frame Grid.Row="0"
                               Grid.Column="1"
                               HasShadow="False"
                               CornerRadius="5"
                               Padding="0"
                               BackgroundColor="{StaticResource PrimaryColor}">
                            <Frame.Triggers>
                                <DataTrigger TargetType="Frame"
                                              Binding="{Binding FoodPartnersAvailable}"
                                              Value="False">
                                    <Setter Property="IsVisible" Value="False"/>
                                </DataTrigger>
                                <DataTrigger TargetType="Frame"
                                              Binding="{Binding FoodPartnersAvailable}"
                                              Value="True">
                                    <Setter Property="IsVisible" Value="True"/>
                                </DataTrigger>
                            </Frame.Triggers>
                            <Image HeightRequest="60"
                                   WidthRequest="70"
                                   HorizontalOptions="Center"
                                   VerticalOptions="Center"
                                   Source="dinner.png">
                                <Image.Behaviors>
                                    <toolkit:IconTintColorBehavior TintColor="{StaticResource WhiteColor}" />
                                </Image.Behaviors>
                            </Image>
                            <Frame.GestureRecognizers>
                                <TapGestureRecognizer Command="{Binding FoodPartnersTappedCommand}"/>
                            </Frame.GestureRecognizers>
                        </Frame>
                    </Grid>
                    <Grid ColumnSpacing="20"
                          Grid.Row="4"
                          PropertyChanged="OnOtherServicesGridPropertyChanged"
                          Margin="0,0,0,20"
                          HorizontalOptions="Center">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="120"/>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="120"/>
                            <ColumnDefinition Width="120"/>
                        </Grid.ColumnDefinitions>
                        <Frame Grid.Row="0"
                               Grid.Column="0"
                               HasShadow="False"
                               CornerRadius="5"
                               Padding="0"
                               BackgroundColor="{StaticResource PrimaryColor}">
                            <Frame.Triggers>
                                <DataTrigger TargetType="Frame"
                                             Binding="{Binding OtherServicesAvailable}"
                                             Value="False">
                                    <Setter Property="IsVisible" Value="False"/>
                                    <Setter Property="IsEnabled" Value="False"/>
                                </DataTrigger>
                                <DataTrigger TargetType="Frame"
                                             Binding="{Binding OtherServicesAvailable}"
                                             Value="True">
                                    <Setter Property="IsVisible" Value="True"/>
                                </DataTrigger>
                            </Frame.Triggers>
                            <Image HeightRequest="60"
                                   WidthRequest="70"
                                   HorizontalOptions="Center"
                                   VerticalOptions="Center"
                                   Source="bag2.png">
                                <Image.Behaviors>
                                    <toolkit:IconTintColorBehavior TintColor="{StaticResource WhiteColor}" />
                                </Image.Behaviors>
                            </Image>
                            <Frame.GestureRecognizers>
                                <TapGestureRecognizer Command="{Binding OtherPartnersTappedCommand}"/>
                            </Frame.GestureRecognizers>
                        </Frame>
                        <Frame Grid.Row="0"
                               Grid.Column="1"
                               HasShadow="False"
                               CornerRadius="5"
                               BackgroundColor="{StaticResource PrimaryColor}"
                               Padding="0">
                            <Frame.Triggers>
                                <DataTrigger TargetType="Frame"
                                              Binding="{Binding OtherPartnersAvailable}"
                                              Value="False">
                                    <Setter Property="IsVisible" Value="False"/>
                                    <Setter Property="IsEnabled" Value="False"/>
                                </DataTrigger>
                                <DataTrigger TargetType="Frame"
                                             Binding="{Binding OtherPartnersAvailable}"
                                             Value="True">
                                    <Setter Property="BackgroundColor" Value="{StaticResource PrimaryColor}"/>
                                    <Setter Property="IsVisible" Value="True"/>
                                </DataTrigger>
                            </Frame.Triggers>
                            <Image Source="store.png"
                                   HeightRequest="60"
                                   WidthRequest="70"
                                   HorizontalOptions="Center"
                                   VerticalOptions="Center">
                                <Image.Behaviors>
                                    <toolkit:IconTintColorBehavior TintColor="{StaticResource WhiteColor}" />
                                </Image.Behaviors>
                            </Image>
                            <Frame.GestureRecognizers>
                                <TapGestureRecognizer Command="{Binding OtherServicesTappedCommand}"/>
                            </Frame.GestureRecognizers>
                        </Frame>
                        <Grid.Triggers>
                            <MultiTrigger TargetType="Grid">
                                <MultiTrigger.Conditions>
                                    <BindingCondition Binding="{Binding OtherServicesAvailable}"
                                                          Value="False"/>
                                    <BindingCondition Binding="{Binding OtherPartnersAvailable}"
                                                          Value="False"/>
                                </MultiTrigger.Conditions>
                                <Setter Property="Margin" Value="0"/>
                            </MultiTrigger>
                            <DataTrigger TargetType="Grid"
                                         Binding="{Binding MarkthalleForFamiliesAvailable}"
                                         Value="False">
                                <Setter Property="Margin" Value="0"/>
                            </DataTrigger>
                        </Grid.Triggers>
                    </Grid>
                    <Button Text="{DynamicResource ViewsStoreDetailPageChangeStoreButtonText}"
                            Grid.Row="5"
                            Command="{Binding ChangeStoreCommand}"
                            FontFamily="ProBold"
                            Margin="60,0,60,10"
                            Style="{StaticResource PrimaryButton}"
                            HorizontalOptions="Center"
                            VerticalOptions="End">
                    </Button>
                </Grid>
            </ScrollView>`

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0 in iOS16.4, This issue repro on .NET 8.0 with below Project, it not repro in Android 13.0-API33.
[MauiApp1.zip](https://github.com/dotnet/maui/files/12341868/MauiApp1.zip)
 iOS16.4:
![image](https://github.com/dotnet/maui/assets/131441429/2669f929-321c-465e-b199-4db6fd10b7cb)
Android 13.0-API33:
![image](https://github.com/dotnet/maui/assets/131441429/407d8fa5-c859-4abc-bff9-c39cc580af65)
