### ISSUE TITLE
MaximumHeightRequest property of ScrollView is incorrect on Android.

### ISSUE THREAD

**Issue by muak** [dotnet/maui#16464]
### Description

ScrollView's MaximumHeightRequest property does not function properly in Android.

It works correctly on iOS.
It appears that the MaximumHeightRequest value is behaving like MinimumHeightRequest on Android.

```xml
<ScrollView MaximumHeightRequest="300" BackgroundColor="LightBlue">
    <Label Text="TEXT" />
</ScrollView>
```

<img height="400" alt="scrollViewIssue_iOS" src="https://github.com/dotnet/maui/assets/16084475/75f00e3b-136e-43af-aed5-71d502ebf811">
<img height="400" src="https://github.com/dotnet/maui/assets/16084475/5611419e-59df-4330-a2e9-ce10f991efb5" />

### Steps to Reproduce

1. Set MaximumHeightRequest value of ScrollView

### Link to public reproduction project repository

https://github.com/muak/ScrollViewIssue

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android11

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 .NET 8, not repro on Windows 11 and iOS 16.4 with below Project:
[ScrollViewIssue.zip](https://github.com/dotnet/maui/files/12341846/ScrollViewIssue.zip)

**Comment by PureWeen** [comment]
@muak it looks like if you set the `VerticalOptions` to start that will workaround the issue for now

```XAML
<ScrollView VerticalOptions="Start" MaximumHeightRequest="300" BackgroundColor="LightBlue">
    <Label Text="TEXT" />
</ScrollView>
```

**Comment by muak** [comment]
@PureWeen 
Thank you for the workaround!

**Comment by jknaudt21** [comment]
I think this has also been fixed. Oddly enough, the behavior on iOS is actually the platform that's behaving incorrectly in this case. 

`ScrollView` is supposed to take as much space as it can with the default `VerticalOptions`, so regardless of what's inside of it, the view will try to take as much space as it can. 

That being said the changes in #16215 likely affected this issue, and now the behavior is consistent across platforms. (The `ScrollView` expands to fill all the space it can) . 

| Windows | Android | iOS |
| -- | -- | -- |
| ![image](https://github.com/dotnet/maui/assets/32918747/6abca7ba-9f9d-432e-a8e4-5f628462ae3d) |  ![image](https://github.com/dotnet/maui/assets/32918747/edb99f9e-e70f-45eb-bb1d-2a4ab4597270) | wip |

**Comment by jknaudt21** [comment]
@hartez Thoughts on this? I think this can be closed

**Comment by hartez** [comment]
@jknaudt21 Those are the correct behaviors for a page with _only_ the ScrollView on them, but the original report is talking about a ScrollView inside a VerticalStackLayout.

Inside the VSL, the ScrollView should be sizing itself to be just large enough to contain its content (the Label). Testing on `main`, it looks like iOS and Windows are working correctly (the ScrollView is the height of the Label). 

Android, however, is expanding beyond the height of the Label up to the `MaximumHeightRequest` value. So there's still a bug here.
