### ISSUE TITLE
Appended ToolbarHandler mapper action not called on iOS

### ISSUE THREAD

**Issue by JordiCasas** [dotnet/maui#16467]
### Description

I want to customize the toolbar in Android and iOS. For this purpose I tossed my old renderers and appended a mapper for the `ToolbarHandler`:

In Android the code is reached and executed:

```
ToolbarHandler.Mapper.AppendToMapping("CustomToolbarMapper", (handler, toolbar) =>
{
    var materialToolbar = handler.PlatformView;
    materialToolbar.ContentInsetStartWithNavigation = 0;
    materialToolbar.TitleCentered = true;
    materialToolbar.SetTitleTextAppearance(Context, Resource.Style.ToolbarTitleStyle);
});
```

On iOS the appended mapper action doesn't get triggered at all:

```
ToolbarHandler.Mapper.AppendToMapping("CustomToolbarMapper2", (handler, toolbar) =>
{
    // Not reached!!
    System.Diagnostics.Debug.WriteLine("IN TOOLBAR HANDLER");
});
```

### Steps to Reproduce

1. Append a custom mapping to the existing `ToolbarHandler.Mapper` property.
2. Run the project on iOS.

Expected result:
The code in the appended mapper action is called.

Current result:
The code in the appended mapper action is not called.

### Link to public reproduction project repository

https://github.com/JordiCasas/ToolbarHandlerIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

Use custom renderer from Xamarin.Forms project.

**Comment by JordiCasas** [comment]
As the bot asked, I installed latest VS preview version:

![image](https://github.com/dotnet/maui/assets/86722749/bfa43781-8821-412b-98a6-1cbe7fe81e72)

But the issue still persists. I didn't change the code of the reproduction repository I already shared in my original post:

https://github.com/JordiCasas/ToolbarHandlerIssue

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on iOS 16.4 .NET 8, not repro on Android 13.0-API33 with below Project:
[16467.zip](https://github.com/dotnet/maui/files/12342050/16467.zip)

**Comment by TomSoPolaris** [comment]
Also an issue on the latest stable VS for Mac version 17.6.7 and official .NET 8 release
