### ISSUE TITLE
When I use MVVN binding a property , and use a thread to update this property value. This property value has been changed in the code,but in UI not changed!

### ISSUE THREAD

**Issue by lxq-iang** [dotnet/maui#16465]
### Description

When I use MVVN binding a property , and use a thread to update this property value. This property value has been changed in the code,but in UI not changed!

### Property value in code
![f30746e7d3f15ee6239b6e3052dcd43](https://github.com/dotnet/maui/assets/49385488/3beecb4c-c073-43a5-b75e-3d5074db99cb)
### XAML
![8545644381d3b20d4b27538bc15aab3](https://github.com/dotnet/maui/assets/49385488/de562a56-a7fc-4f00-935b-a10e732bcdf4)
### Property value in UI
![98ab2a5975a606d9c5a457ff0a07368](https://github.com/dotnet/maui/assets/49385488/81561e08-dd5f-4e4d-b250-bb9a59794993)

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and higher version

**Comment by AndreasReitberger** [comment]
You must invoke the code on the `UIThread`. You either can use the `MainThread` or the `IDispatcher` (recommended).

```cs
MainThread.InvokeOnMainThreadAsync(() =>
{
    try
    {
     // Your code, simplified
     IsConnected = true;
    }
    catch (Exception exc)
    {
        EventManager.Instance.LogError(exc);
    }
});
```

or 

```cs
// A method to invoke an action on the `UIThread` using a `Dispatcher`
 public static void Dispatch(IDispatcher dispatcher, Action action, bool forceUiThread = false)
{
    if (dispatcher.IsDispatchRequired || forceUiThread)
    {
        dispatcher.Dispatch(() =>
        {
            try
            {
                action?.Invoke();
            }
            catch (Exception exc)
            {
                EventManager.Instance.LogError(exc);
            }
        });
    }
    else
    {
        action?.Invoke();
    }
}
```
You can use `DependencyInjection` in order to inject the `Dispatcher` from the current `Page` to your `ViewModel`
https://learn.microsoft.com/en-us/dotnet/architecture/maui/dependency-injection

**Comment by lxq-iang** [comment]
@AndreasReitberger I try to invoked the code in UIThread, but it didn't work.
```
public void ChangeConnectionStatus()
{
          MainThread.BeginInvokeOnMainThread(() =>
          {
              IsConnected = _AppConfig.GetConfig.IsConnected;
          });
 }
```

**Comment by AndreasReitberger** [comment]
Did you set your `ViewModel` as `BindingContext` in your views `Ctor`?

```
public partial class MyPage : ContentPage
{
    public MyPage (MyViewModel viewModel)
    {
        InitializeComponent();
        BindingContext = viewModel;
    }
// or

public MyPage()
    {
        InitializeComponent();
        BindingContext = new MyViewModel();
    }
}
```

Updating on the `UIThread`, as shown above, is to avoid exceptions if you access UI relevant bindings on a background task.

**Comment by lxq-iang** [comment]
Yes, I set my view as shown below
```
public partial class AppShell : Shell
{
    public AppShell(AppShellViewModel viewModel)
    {
        InitializeComponent();
        //other code ... ...
        BindingContext = viewModel; 
        
    }
}
```

**Comment by AndreasReitberger** [comment]
Can you create or upload your small repro? I guess otherwise it would be hard to identify the issue.

**Comment by lxq-iang** [comment]
@AndreasReitberger I made a small repro, and put it in the [https://github.com/lxq-iang/TestRepro.git](url).  Can you help me see what problem is?  Thank you very much!

**Comment by affableashish** [comment]
@lxq-iang Your repro link is not working.

**Comment by AndreasReitberger** [comment]
Just remove the ".git" from it
[https://github.com/lxq-iang/TestRepro](https://github.com/dotnet/maui/issues/url)

**Comment by richardrigutins** [comment]
@lxq-iang from your repro it looks like you're using multiple separate instances of AppShellViewModel:

``` csharp
	public App()
	{
		InitializeComponent();

		MainPage = new AppShell(new ViewModel.AppShellViewModel());
	}
```

``` csharp
        public PollSignalrConnectionStatusWorker()
        {
            timer.Elapsed += TestSignalRConnection;
            timer.AutoReset = true;
            timer.Enabled = true;
            timer.Start();
            SignalREvent += new AppShellViewModel().ChangeConnectionStatus;
        }
```

The AppShellViewModel you're setting the IsConnected property on and the one used by the AppShell are different objects, that's why you don't see changes in the UI.

You could try to use dependency injection to inject the AppShellViewModel instead of creating separate instances with the `new()` keyword.

**Comment by lxq-iang** [comment]
@richardrigutins Thanks for your guidance, I know how to solve this problem.

**Comment by drasticactions** [comment]
Closing this as it seems you've solved your code issue and it doesn't seem to be a MAUI bug. Thanks everyone for your input!
