### ISSUE TITLE
Animation CallBack action not invoked when enabled the battery-saver in Android device.

### ISSUE THREAD

**Issue by anandhan-rajagopal** [dotnet/maui#16478]
### Description

I encountered an issue with the custom animation control developed to replace the framework's ActivityIndicator. The problem arises when the device's battery-saver mode is enabled. Under this condition, the Animation CallBack Action, which is a crucial part of the animation functionality, fails to get invoked.

We're seeking a solution that guarantees the consistent triggering of the Animation CallBack Action, irrespective of the device's battery saver mode being on or off. This would ensure seamless and continuous animations even in battery-saving scenarios, thereby improving the overall user experience.battery-saver

https://github.com/dotnet/maui/assets/97146406/4769f439-b48a-4b76-a13d-1a8f8037dd03

### Steps to Reproduce

1. Launch the .NET MAUI application on an Android device running Android OS version X or higher.
2. Ensure the application includes a label and a button.
3. Enable the device's battery saver mode either through the Settings menu or by using the battery status notification.
4. Tap the button to trigger the custom animation, which should scale the label.

### Link to public reproduction project repository

https://github.com/anandhan-rajagopal/CustomAnimation

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 5.0 and above

### Did you find any workaround?

https://github.com/dotnet/maui/blob/main/src/Core/src/Animations/AnimationManager.cs#L38,
https://github.com/dotnet/maui/blob/main/src/Core/src/Animations/PlatformTicker.Android.cs#L61

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33(8.0.100-preview.7.23376.3) with below Project:
[AnimationSample.zip](https://github.com/dotnet/maui/files/12356288/AnimationSample.zip)
