### ISSUE TITLE
Fix the slow startup

### ISSUE THREAD

**Issue by YoussofKhawaja** [dotnet/maui#1648]
Fix this slow startup for andriod or you just didn't change anything between xamarin.forms and maui

**Comment by lutzroeder** [comment]
Duplicate of #1595

**Comment by SagarPanwala** [comment]
@lutzroeder 1595 is deleted hence this is still a valid open bug.

**Comment by jfversluis** [comment]
There are several issues already describing this problem that we are very much invested in. You can see in the [latest blog post](https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-9/#quick-android-startup) that we have made great progress here.

Another issue for this is here #822

Closing this one for now, rest assured: this is on our radar and a big priority for us. Thanks!
