### ISSUE TITLE
ImeOptions only working after hot reload - Android

### ISSUE THREAD

**Issue by CodeTigerCloud** [dotnet/maui#16497]
### Description

Hello,

I'm using maui (with xaml) on an Pixel 6a (Android 13.0) and .net 7.

I have a form with multiple entries and want the user to be able to select the next by clicking the bottom right button on his screen keyboard by adding:
    android:Entry.ImeOptions="Next"
if I add this attribute and hot-reload, it works as expected. But if I restart the debugging session or just plainly start the app on the phone, it shows a check-mark in that corner that closes the screen-keyboard.

### Steps to Reproduce

Create a new .NET MAUI APP in VS2022 - you now should have the template with the waving dotnet bot.

Add following attribute to the ContentPage node in the MainPage.xaml:
xmlns:android="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;assembly=Microsoft.Maui.Controls"

Add those nodes after the Button "CounterBtn":
            <Entry x:Name="entry1" Text="1" android:Entry.ImeOptions="Next" />
            <Entry x:Name="entry2" Text="2" android:Entry.ImeOptions="Done" />

Select the Phone as StartUp Option and start Debug.

Click on the "1" on the PhoneScreen - there is a Check-Mark instead of a Next on the Screen-Keyboard.

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

Not using MAUI

**Comment by rachelkang** [comment]
Hi, @CodeTigerCloud - have you tried using the cross-platform API? `ReturnType="Next"` https://github.com/dotnet/maui/issues/16503

Is there a reason you are seeking to use the platform-specific instead?

**Comment by CodeTigerCloud** [comment]
> Hi, @CodeTigerCloud - have you tried using the cross-platform API? `ReturnType="Next"` #16503
> 
> Is there a reason you are seeking to use the platform-specific instead?

Hi Rachel,

I guess I took a wrong turn googling for a solution. ReturnType works fine for me.

Still wondering about the weird behaviour regarding the hot-reload with the platform-specific option. Maybe you want to keep it as a low priority bug - but for me, the issue is solved.

Thank you a lot

**Comment by drasticactions** [comment]
I removed the Hot Reload tags. As far as I can tell this has nothing to do with how Hot Reload/XAML Hot Reload operates.

When you change a setting with Hot Reload, you are (generally) updating the existing object with new values. So when you updated the existing object with "Next", it happened to get the value you were expecting based on the previous values contained within the control. When it loads the first time, that value does not work because the previous context, AFAIK, would not show that option.

So AFAIK, everything is operating as it should.
