### ISSUE TITLE
AutomationProperties not working in release mode

### ISSUE THREAD

**Issue by hepple9** [dotnet/maui#16491]
### Description

When assigning AutomationProperties to an element in xaml or code behind, they are not being set when the app is built in release mode.

### Steps to Reproduce

Create a new sample app
Add a label to the mainPage and set AutomationProperties.IsInAccessibleTree="False"
Build in release mode

The label can still be focused on and read out by a screen reader

### Link to public reproduction project repository

https://github.com/hepple9/mauiIssue16491Repro.git

### Version with bug

7.0.92

### Last version that worked well

6.0

### Affected platforms

iOS, Android

### Did you find any workaround?

N/A

**Comment by hepple9** [comment]
Please note that this issue is not occurring in debug builds but only in release builds. I have also been able to repro on the latest version (7.0.92) and attached a repro project.

**Comment by PureWeen** [comment]
@hepple9 Can you test this on the latest .NET8 release?
