### ISSUE TITLE
Incorrect use of nullable enable in iOS HealthKit

### ISSUE THREAD

**Issue by reinierkops** [dotnet/maui#16503]
### Description

The delegate HKSampleQueryResultsHandler has nullable enabled, but the properties HKSample[] and NSError could be null, but are not marked as null.

### Version with bug

7.0.92

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

Check the properties, and ignore the compiler warning :-)

**Comment by mattleibow** [comment]
This issue was moved to xamarin/xamarin-macios#18622
