### ISSUE TITLE
Port Forms Animation/Power Save test 

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#16511]
We need to port the Android Power Save/Animation manual test to MAUI and verify that Android animations still behave correctly when Power Save mode engages while the animation is in progress.

The original test from Forms:
https://github.com/xamarin/Xamarin.Forms/pull/3148/files#diff-2e8601dda44950742e2c73bcd18dd088ceda621961b1c68e45a2ba358ef97327

**Comment by japarson** [comment]
The tests have been ported with [Pull Request 490263](https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml/pullrequest/490263): Add Android tests for stopping animation when battery saver/remove animations enabled

@hartez will work on getting the tests enabled again.
