### ISSUE TITLE
about support linux

### ISSUE THREAD

**Issue by samchenws** [dotnet/maui#16529]
### Description

Without Linux support, this project is useless, and Microsoft has always missed the best opportunity. It's us who love .net developers (sorry, to tell the truth)

### Public API Changes

Without Linux support, this project is useless, and Microsoft has always missed the best opportunity. It's us who love .net developers (sorry, to tell the truth)

### Intended Use-Case

Without Linux support, this project is useless, and Microsoft has always missed the best opportunity. It's us who love .net developers (sorry, to tell the truth)

**Comment by Eilon** [comment]
Hi, there are various other requests and discussions in this repo that cover this topic, such as https://github.com/dotnet/maui/discussions/339, https://github.com/dotnet/maui/issues/8802, and others.
