### ISSUE TITLE
How to interact with non lifecycle events in MainActivity

### ISSUE THREAD

**Issue by bsloehr** [dotnet/maui#16524]
### Description

Hopefully this is an easy question. In Xamarin Forms we could interact with non lifecycle events from the MainActivity class. 

```cs
public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
{
        protected App App { get; set; }

        protected override void OnCreate(Bundle bundle)
        {
            SetTheme(Resource.Style.AIAppTheme_Base);
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;
            base.OnCreate(bundle);

            Xamarin.Essentials.Platform.Init(this, bundle);
            CrossCurrentActivity.Current.Init(this, bundle);

            Forms.Init(this, bundle);
            App = new App();
            
            LoadApplication(App);

            App.NavigateToMainPage();                    
        }

        public override bool DispatchKeyShortcutEvent(KeyEvent e)
        {
            if (e.Action == KeyEventActions.Down)
            {
                var keyEvent = new KeyShortcutEvent
                {
                    Keycode = (Keycode)Enum.Parse(typeof(Keycode), e.KeyCode.ToString()),
                    IsShiftPressed = e.IsShiftPressed,
                    IsCtrlPressed = e.IsCtrlPressed,
                    IsAltPressed = e.IsAltPressed
                };

                App.DispatchKeyShortcutEvent(keyEvent);
            }

            return base.DispatchKeyShortcutEvent(e);
        }
}
```

Since the App is instantiated in the OnCreate override we can gain reference to it and use it to interact when the DispatchKeyShortcutEvent was fired by Android.

I can't seem to determine how to do something like this in MAUI. The MainActivity is still there and the DispatchKeyShortcutEvent method fires appropriately, but where is App?

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by mattleibow** [comment]
You can override the main activity in the app project. IN the template, you still can see the file under the Platforms/Android folder:

https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/Platforms/Android/MainActivity.cs

**Comment by bsloehr** [comment]
Thanks for the response @mattleibow . I do understand that MainActivity can still be modified as it was in Xamarin Forms. The sticky part comes in access the App object. In XF the App object is instantiated directly.

`App = new App();`

This allows us to add methods in the App.xml.cs file and access them from MainActivity since we have reference to the App object.

But in MAUI the App object is not instantiated within MainActivity. So how do we gain access to it? The only answer I've stumbled upon is to downcast MauiApplication.Current.Application, as such:

`App = MauiApplication.Current.Application as App;`

Now we can access methods we have added to App.xml.cs. This allows us to respond to DispatchKeyEvent on Android and pass those key events back into the app.

**Comment by mattleibow** [comment]
Does `Application.Current` not work?

That should still be there. Make sure to use the MAUI application object and not the Android object.

**Comment by bsloehr** [comment]
If you're talking about MauiApplication.Current.Application, then yes but only if I downcast it to App.

App.xaml.cs will be in the namespace of my project, e.g. MyApp. So I downcast MauiApplication.Current.Application to MyApp.App. This gives me access back into App.xaml.cs where I've added a method that can be called from MainActivity. This allows me to intercept key events in Android and handle them within my app.

The missing piece was figuring out what object represented App.xaml.cs.

**Comment by mattleibow** [comment]
I am talking about Microsoft.Maui.Controls.Application.Current.

You can also add a static property on you app to get current directly.

Like MyApp.Current

**Comment by bsloehr** [comment]
Thank you @mattleibow, referencing the static App.Current property is what I was looking for. Please consider this closed
