### ISSUE TITLE
ContentPage.Background (with LinearGradientBrush) not working for iOS

### ISSUE THREAD

**Issue by albilaga** [dotnet/maui#16537]
### Description

When setting Page.Background with `LinearGradientBrush`, it won't set Page.Background in iOS. On Android it is working fine. Setting `Background=Red` also working fine both in Android and iOS.

### Steps to Reproduce

1. Create new .NET MAUI App
2. Change Page.Background to be something like this
```
  <ContentPage.Background>
        <LinearGradientBrush>
            <GradientStop Color="Green" Offset="0"/>
            <GradientStop Color="Red" Offset="1"/>
        </LinearGradientBrush>
    </ContentPage.Background>
```
3. Run the app. The background still white
4. Or you can also test this https://github.com/albilaga/MAUIPlayground/tree/test-page-background
5. `MainPage` working fine because I wrap it inside `ContentView` but when setting Background directly in `SecondPage` it is not working as expected

### Link to public reproduction project repository

https://github.com/albilaga/MAUIPlayground/tree/test-page-background

### Version with bug

7.0.92

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Create root `ContentView` and set `Background` there

**Comment by mattleibow** [comment]
This was fixed in https://github.com/dotnet/maui/pull/15832

This _just_ messed the preview 7 release, but will be in the RC 1.

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/15128
