### ISSUE TITLE
Border background is wrong by default on Android and text cannot be seen (it's correct on Windows)

### ISSUE THREAD

**Issue by spadapet** [dotnet/maui#16547]
### Description

When I wrap a Border around my content, the default background color is black on Android and I can't see Label text. Is the Border really supposed to be filled black on Android? I thought it should be transparent by default.

### Android:

* ![image](https://github.com/dotnet/maui/assets/2523431/82388e2f-8bdd-4886-a4a6-37541fe03b4d)

### Windows:

* ![image](https://github.com/dotnet/maui/assets/2523431/c1ede374-11d4-4555-add0-96c84a647927)

### Steps to Reproduce

I was using **.NET 8 preview 7**.

1. In Visual Studio, File|New|Blank MAUI app
2. Add a Border around the default ScrollView in MainPage.xaml:
    * ![image](https://github.com/dotnet/maui/assets/2523431/6fc892f8-a1ed-4fce-b7e3-a78607025c65)
3. Change debug target to Android emulator
    * ![image](https://github.com/dotnet/maui/assets/2523431/195171af-3645-48a2-87f6-ead3f4c76f94)
4. F5 to build and debug

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

net8.0-android21.0

### Did you find any workaround?

My workaround is to manually set the background to transparent:

* ![image](https://github.com/dotnet/maui/assets/2523431/ef98d585-dd21-4e28-8fea-e90528ec0bbe)

**Comment by spadapet** [comment]
@rmarinho, I did include repro steps in this bug. And no test project is needed, it's just a blank template with one tag added. If you can't repro, that's great, then this bug can be closed.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 .NET 8, not repro on Windows 11 and iOS 16.4 with below Project:
[16547.zip](https://github.com/dotnet/maui/files/12367577/16547.zip)

![image](https://github.com/dotnet/maui/assets/97647558/ff635124-9e8b-4b86-ad99-1556c402b9c6)
