### ISSUE TITLE
[Bug] Shell navigation bar color not rendering on iOS 15

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1654]
### Description

On iOS 15 I'm not seeing the nav bar bg color when running XF, however not sure if it's an issue here. Logging to make sure we look at it.

The bg color does appear if I trigger a layout update via something like the soft keyboard. 

<img width="564" alt="Screen Shot 2021-07-12 at 8 24 31 PM" src="https://user-images.githubusercontent.com/41873/125376242-39b53d80-e350-11eb-83d2-e8db7221c9a6.png">
<img width="564" alt="Screen Shot 2021-07-12 at 8 22 43 PM" src="https://user-images.githubusercontent.com/41873/125376246-3b7f0100-e350-11eb-9780-ee7c81dbaff9.png">

**Comment by varyamereon** [comment]
Could be something like [this](https://developer.apple.com/forums/thread/682420)?

**Comment by jsuarezruiz** [comment]
Is the same as https://github.com/xamarin/Xamarin.Forms/pull/14649
Will port the code to fix this issue!

**Comment by jfversluis** [comment]
Fixed by #3332
