### ISSUE TITLE
CollectionView bounces/wobbles when values are updated on Android

### ISSUE THREAD

**Issue by jstedfast** [dotnet/maui#16546]
### Description

As you can see in the video below (at about the 19s mark), when my app updates the labels in the StockSymbolView (a custom ViewCell class that is used by the MAUI TableView control), the CollectionView bounces - it seems all of the cells expand vertically as if I just did a "pull the refresh" type of thing.

https://github.com/dotnet/maui/assets/338984/21f981c7-529b-4c85-9110-441f22f7f598

Tested on:
* WinUI (no bounceyness/wobble)
* Android (CollectionView bounces/wobbles)

### Steps to Reproduce

1. git clone [git@github.com](mailto:git@github.com):jstedfast/Stocks
2. cd Stocks
3. git checkout -b collection-view-wobble origin/collection-view-wobble
4. git reset --hard 546edf8b84b0636e02ab6478fabbce139eb84e1b
5. Open the Stocks.sln in Visual Studio
6. Select an Android emulator (or device?) to run the Stocks app on
7. Build & Run
8. Within ~20 seconds of the Stocks app launching on Android, the stock quote data should be fetched from the web and at this point, it will update the stock quote info in each cell and you will see all of the cells in the CollectionView wobble/bounce. And then every 15 seconds or so after that, the wobble/bounce will repeat as the data is updated at about a 15s interval.

### Link to public reproduction project repository

https://github.com/jstedfast/Stocks

### Version with bug

8.0.0-preview.6.8686

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 33

### Did you find any workaround?

This is actually my work-around for https://github.com/dotnet/maui/issues/16533

### Relevant log output

```shell
No relevant log output that I'm aware of.
```

**Comment by mattleibow** [comment]
Is this issue still happening with CollectionView? You linked to https://github.com/dotnet/maui/issues/16533 so is this a duplicate?

| A | B |
|:-:|:-:|
| ![](https://github.com/dotnet/maui/assets/1096616/08718147-1fd7-42a0-83a5-168d4814eed3) | ![](https://github.com/dotnet/maui/assets/1096616/5912bf00-34e8-4cc0-841d-a4f2548e923b) |

**Comment by jstedfast** [comment]
I removed the outer ScrollView and that seems to have fixed the wobble
