### ISSUE TITLE
Release 7.0.92 rollback json refers to non exiting packages

### ISSUE THREAD

**Issue by nll** [dotnet/maui#16557]
### Description

Workload rollback file for version 7.0.92 refers to component's versions that do not exist.

||Refered version| Version that exists|
|---|---:|---:|
|  microsoft.net.sdk.android |  `33.0.69`  | `33.0.68`
|  microsoft.net.sdk.ios |  `16.4.7073`  | `16.4.7089`
|  microsoft.net.sdk.maccatalyst |  `16.4.7073`  | `16.4.7089`
|  microsoft.net.sdk.macos |  `16.4.7073`  | `16.4.7089`
|  microsoft.net.sdk.tvos |  `16.4.7073`  | `16.4.7089`
|  microsoft.net.workload.mono.toolchain.net6 |  `7.0.6`  |  `7.0.7`
| microsoft.net.workload.mono.toolchain.net7  |  `7.0.6`  |  `7.0.7`
| microsoft.net.workload.emscripten.net6 | `7.0.6` | `7.0.7`
| microsoft.net.workload.emscripten.net7 |  `7.0.6` | `7.0.7`

### Steps to Reproduce

1. Open terminal
2. Install workload from rollback file:
    - `dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/7.0.92.json`
3. Error:
    - `Workload installation failed: Failed to install manifest microsoft.net.sdk.android version 33.0.69: Unable to load the service index for source https://pkgs.dev.azure.com/coins/Umbrella-Mob-App/_packaging/COINSLive/nuget/v3/index.json..` 

### Version with bug

7.0.92

### Last version that worked well

7.0.86

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

Creating a new json with the fixed versions, like 
```json
{
  "microsoft.net.sdk.android": "33.0.68/7.0.100",
  "microsoft.net.sdk.ios": "16.4.7089/7.0.100",
  "microsoft.net.sdk.maccatalyst": "16.4.7089/7.0.100",
  "microsoft.net.sdk.macos": "13.3.7089/7.0.100",
  "microsoft.net.sdk.maui": "7.0.92/7.0.100",
  "microsoft.net.sdk.tvos": "16.4.7089/7.0.100",
  "microsoft.net.workload.mono.toolchain.net6": "7.0.7/7.0.100",
  "microsoft.net.workload.mono.toolchain.net7": "7.0.7/7.0.100",
  "microsoft.net.workload.emscripten.net6": "7.0.7/7.0.100",
  "microsoft.net.workload.emscripten.net7": "7.0.7/7.0.100"
}
```
and using that for workload install

**Comment by mattleibow** [comment]
Thanks for reporting this. I have updated the rollback. 

One thing I would strongly reccommend is using the `<MauiVersion>` msbuild property instead as this allows VS to managed the SDKS, and you can override the actual version used.
