### ISSUE TITLE
There should be a subscribable event for changes to the Map visible region

### ISSUE THREAD

**Issue by japarson** [dotnet/maui#16556]
### Description

It would be great if the [Map control](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/map) had an event that could be subscribed to that was fired whenever the visible region of the Map changed.

### Public API Changes

```C#
public MainPage()
{
    InitializeComponent();
    MyMap.VisibleRegionChanged += MyMap_VisibleRegionChanged;
}

private void MyMap_VisibleRegionChanged(object sender, EventArgs e)
{
    throw new NotImplementedException();
}
```

### Intended Use-Case

In my app, I have a situation where I want to load/unload pins depending on the region being rendered. This is mainly for performance reasons as I don't want the control to have to manage thousands to millions of pins at once. Perhaps this could be mitigated with pin clustering, but I imagine there might still be performance implications.

I'm sure there's other use cases for this event as well. For example, maybe you want to perform some action when the zoom level changes.

**Comment by rmarinho** [comment]
Hi @japarson VisibleRegion is not a BindableProperty but we still raise Property changes when it get's changed. 
```
MyMap.PropertyChanged += (s,e) => {
   if(e.PropertyName == nameof(Map.VIsibleRegion))
   {
       //Load pins
   }
};

```
