### ISSUE TITLE
Custom color for selected bottom tabbar in Shell not working.

### ISSUE THREAD

**Issue by kubalobacz** [dotnet/maui#16551]
### Description

Hey. I am setting within my Shell xaml object TabBarTitleColor to red.
It renders ok on Android, but fails on ios (refer to screenshot). Anyone encounter this? 
![image](https://github.com/dotnet/maui/assets/16230985/d8e39371-9599-4fcf-94e0-7dc8e2adb930)

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by kubalobacz** [comment]
From what i managed to discover that if you set TabBarForegroundColor on iOS then selected tab text/icon is set to custom color.

Not sure if its a workaround or intended behavior.

![image](https://github.com/dotnet/maui/assets/16230985/57b9dbb7-1cf1-4ff4-9006-8cc9990a71ec)

**Comment by jsuarezruiz** [comment]
This issue should be fixed in .NET 8 by https://github.com/dotnet/maui/pull/15748

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue repro on iOS 16.4(8.0.0-preview.7.8842), not repro on Windows 11 and Android 13.0-API33 with below Project:
[16551.zip](https://github.com/dotnet/maui/files/12377126/16551.zip)

![image](https://github.com/dotnet/maui/assets/97647558/54eb371b-ec45-41b1-a657-f5fa3c2eb5dd)

![image](https://github.com/dotnet/maui/assets/97647558/33ec1ca3-779f-4382-a292-eb1cf1f2f46a)
