### ISSUE TITLE
CarouselView - The specified child already has a parent. You must call removeView() on the child's parent first

### ISSUE THREAD

**Issue by ericbrunner** [dotnet/maui#16577]
### Description

I am trying to setup a CarouselView in my ContentPage whereby the content items are defined as ContentView items (which have there layout and content completely defined in their own XAML file).
Like so:

```
<CarouselView Grid.Row="1"
                      x:Name="CarouselView"
                      ItemsSource="{Binding Source={x:Reference This}, Path=TabItems}">
            <CarouselView.ItemTemplate>
                <DataTemplate>
                    <Grid x:DataType="models:ITabItem">
                        <ContentView Grid.Row="0" Content="{Binding View}" />
                    </Grid>
                </DataTemplate>
            </CarouselView.ItemTemplate>
</CarouselView>
```

The TabItems is an observable collection like:
        
```
            public ObservableCollection<ITabItem> TabItems   
    {
        get => (ObservableCollection<ITabItem>)GetValue(TabItemsProperty);
        set => SetValue(TabItemsProperty, value);
    }
```
        
        
Installed workloads:
![image](https://github.com/dotnet/maui/assets/6480047/9e9cc875-ae11-4aae-96b7-8cf7b3dd85d9)

### Steps to Reproduce

1. Clone provided repo https://github.com/ericbrunner/TaskyApp.Maui.SingleProject.git. 
2. Click on 
![image](https://github.com/dotnet/maui/assets/6480047/24f51700-4ab6-41fe-9b41-a2b988f1ed14)
3. App crashes like
![image](https://github.com/dotnet/maui/assets/6480047/d52b50c7-3342-482f-9cc2-45cff85a73b0)

**Java.Lang.IllegalStateException
  Message=The specified child already has a parent. You must call removeView() on the child's parent first.**

Is there a way in .NET MAUI to show custom controls based on ContentView class to a CarouselView? 

### Link to public reproduction project repository

https://github.com/ericbrunner/TaskyApp.Maui.SingleProject/commit/832289f9f126f5189552d0e9ab50b1c7d57138fd

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No. A further attempt would be to create a `DataTemplate `for each individual custom Control (ContentView) and use a `DataTemplateSelector`

### Relevant log output

```shell
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[mono-rt]    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12324
[mono-rt]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
[mono-rt]    at Android.Views.ViewGroup.AddView(View child) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:line 1999
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler) in D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:line 44
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page) in D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:line 49
[mono-rt]    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 172
```

**Comment by VladislavAntonyuk** [comment]
the issue still exists in .NET 8 RC1

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Not repro on android platform with sample project.
https://github.com/ericbrunner/TaskyApp.Maui.SingleProject/commit/832289f9f126f5189552d0e9ab50b1c7d57138fd
![image](https://github.com/dotnet/maui/assets/82450723/49e19664-f287-4f3a-b6df-6eb1f0381014)
