### ISSUE TITLE
"System.ArgumentException: NaN is not a valid value for height" from `Rect.Size` getter

### ISSUE THREAD

**Issue by BioTurboNick** [dotnet/maui#16571]
### Description

Very many reports in the wild of this issue from AppCenter. the stack doesn't include any of my code, though it didn't happen until I started implementing LayoutManager overrides (though, oddly, I never overrode anything for AbsoluteLayout).

Nearest I can figure is that somewhere a NaN is slipping in, and then later Rect.Size() is tripping over it, which builds a new Size object from the width and height on demand.

So either Rect needs to be made impossible to have a NaN Width/Height so that this condition can be caught and prevented at the source, or the Size getter needs to return some other valid value when the Width or Height is NaN. Getters should not throw exceptions.

```
Microsoft.Maui.Graphics.Size..ctor(Double width, Double height)
Microsoft.Maui.Graphics.Rect.get_Size()
Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds)
Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
Microsoft.Maui.Layouts.AbsoluteLayoutManager.ArrangeChildren(Rect bounds)
Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds)
Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b)
Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr , IntPtr , Boolean , Int32 , Int32 , Int32 , Int32 )
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V , IntPtr , IntPtr , Boolean , Int32 , Int32 , Int32 , Int32 )
```

### Steps to Reproduce

I do not know how to reproduce it.

### Link to public reproduction project repository

n/a

### Version with bug

7.0.81

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 11, 12, 13

**Comment by jsuarezruiz** [comment]
Do you have more logs or data?, cual you share feedback about what is doing the AbsoluteLayout (like adding items at runtime etc)?

**Comment by BioTurboNick** [comment]
The nearest I can figure is that in a few places I had bound in XAML a `MinimumHeightRequest` and `MaximumHeightRequest` of one object to another's `Height`. An attempt to workaround some layout issues in MAUI.

I just implemented a `ValueConverter` that converts NaN to 0.0 for those bindings and released that, so I'll update this if I notice that crash has disappeared.

**Comment by BioTurboNick** [comment]
I'm pretty sure this was the issue - 3 days of the update out in the wild and no issue.

I'll try to make a repro.

**Comment by BioTurboNick** [comment]
Okay, so I don't have the root issue, but I have isolated the immediate problem:

A `Rect` can be created with `Width` or `Height` set to `double.NaN`, but the `Size` property does not support `double.NaN` values. This suggests that the constructor is allowing an invalid `Rect` to be created.

Reproduction:
[NanHeightRepro.zip](https://github.com/dotnet/maui/files/12328705/NanHeightRepro.zip)

If this issue were fixed, the error would move up to the point of construction of the `Rect` rather than the point of consumption of the `Rect.Size` property, because the point of construction shouldn't be producing a `double.NaN`. And that would allow us to determine where the bad `Rect`s are coming from.

If this would be considered a breaking change, .Net 8 would be a good time to make that change.

On the other hand, if for whatever reason it is desired that a `Rect` needs to be able to accept `double.NaN` input still despite making the `Size` property throw an exception, then the code base needs to be carefully reviewed to prevent NaNs from going into `Rect` objects in the layout system.

**Comment by BioTurboNick** [comment]
This is still present in 8.0.3.

**Comment by BioTurboNick** [comment]
I think the immediate cause might have been that a `NaN` was appearing in a value I was using to construct the `Rect` argument for `AbsoluteLayout.SetLayoutBounds()`. I suppose a simpler fix would be to have `SetLayoutBounds` validate the `Rect`, but the same kind of error could crop up again. Better IMO to preclude the possibility altogether.

**Comment by dpozimski** [comment]
It can be related:
https://github.com/dotnet/maui/issues/19120

**Comment by mattleibow** [comment]
I see #18971 took the approach to make Width/Height of Rect throw if NaN was set, however Graphics is a bit inconsistent.

* `Point` and `PointF` allow `NaN`
* `Size` and `SizeF` do NOT allow `NaN`
* `Rect` and `RectF` allow `NaN`

Why is a `NaN` size so terrible but a point or rect just fine? System.Drawing and WPF seem to handle `NaN` just fine, so I think we should fix size and make it match the rest of the world.
