### ISSUE TITLE
Unable to Locate .NET MAUI in VS

### ISSUE THREAD

**Issue by Hive356** [dotnet/maui#16590]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows 
- Version: 22H2
- OS Build: 22621.1992

When trying to follow the tutorial on installing the .NET MAUI, I have run into the problem where once installing the necessary section and launching VS Community 2022 (current version is: 17.6.5) there is no option to search for MAUI in the right most box at the top
![image_2023-08-07_214541520](https://github.com/dotnet/maui/assets/141680629/a4165d54-75f1-43a5-bc7c-52ebb6902fbf)

I am unsure of what the problem may be. Currently, my VS is installed in the default location which is: 
![image_2023-08-07_214800820](https://github.com/dotnet/maui/assets/141680629/db0f8618-f3a4-4df2-8c8a-e27e10f4a051)

Additionally, here is an image of what I have currently installed
![image_2023-08-07_214437278](https://github.com/dotnet/maui/assets/141680629/dc8bc119-059a-4a77-8c2c-6e9f9305d2f5)

**Comment by Eilon** [comment]
Hi @Hive356 , from a command line window can you run `dotnet workload list` and share the output of that? And also the output of `dotnet new list maui`?

**Comment by UkeHa** [comment]
@Hive356 this tool was also helpful: https://github.com/Redth/dotnet-maui-check

**Comment by Hive356** [comment]
> Hi @Hive356 , from a command line window can you run `dotnet workload list` and share the output of that? And also the output of `dotnet new list maui`?

@Eilon Hello, so I figured I'd try to make a simple C# console app to use to run the command line window however I appear to have faced yet another problem. When making a new console app, the app generated seems to be empty missing the items as shown on the image below on right hand sign and instead of running in debug mode, its prompting me to attach to process which I am unsure of how that works. 
![image_2023-08-08_102424726](https://github.com/dotnet/maui/assets/141680629/1ba058e7-c713-4524-884e-dff0c82320a2)

Ill be honest and say that I might as well be new to VS as I've only ever used it at school where it was all sorted out and there are still quite a numerous amount of features I haven't touched on or even know about. I do apologise if this seems like a simple task but I just for some reason are facing a lot of issues I haven't come cross at school in trying.
