### ISSUE TITLE
[regression/7.0.81] Strange padding problem using grid

### ISSUE THREAD

**Issue by FM1973** [dotnet/maui#16598]
### Description

I got a special case where the padding of an outer grid gets doubled on the right side when data changes.
I got a grid. Inside the grid is a verticalstack and inside the stack is another grid with 3 columns. The most left and most right columns have a fixed width of 50. The middle column has a width of STAR.

In the middle column there is an entry. If you change the content of the entry an it reaches the max width of the middle column, the outer grid doubles the padding on the rigtht. It´s hard to explain. Please try the repo.

By the way: it doesn´t matter if I use an entry. You can even put a label in the middle column.
I pinned the maui version to 7.0.92!!!

### Steps to Reproduce

1. Download repo
2. Start repo
3. Click on button 'Grid column problem' on the bottom
4. Change the content of the entry. I.E. 100 for padding 50 or 1000000 for padding 20
5. The padding of the outer table get´s doubled for the right side

### Link to public reproduction project repository

https://github.com/FM1973/RefreshGridRepo.git

### Version with bug

7.0.92

### Last version that worked well

7.0.52

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

Not really.

**Comment by FM1973** [comment]
Doesn´t make a difference. It behaves the same. And it should work with or without a HorizontalStackLayout, should´t it?
Anyway, the same code works pretty well in 7.0.52. There have been a lot of changes on how a grid get´s calculated and in my oppinion version 7.0.52 did work. Starting with 7.0.81 the grid problems started.

**Comment by DouglasGiovanella** [comment]
Same case here, just the right side doubles the size when using padding. Margin works fine

**Comment by PureWeen** [comment]
If I'm following the repro correctly

I'm not seeing this reproduce in net8

**Comment by FM1973** [comment]
@PureWeen I can confirm the problem has been solved in 8.0.3

**Comment by MichaelShapiro** [comment]
I can confirm too - this issue doesn't exist in mau .bet 8.0.3.
