### ISSUE TITLE
[regression/8.0.100-preview.7.23376.3] .NET Maui Blazor App throws "No interop methods are registered for renderer" javascript exception

### ISSUE THREAD

**Issue by campersau** [dotnet/maui#16609]
### Description

When creating a new .NET Maui Blazor App in `8.0.100-preview.7.23376.3` and running it results in the following javascript exception when navigating or clicking on the counter button.

Open the dev tools to see the exception:

```
blazor.webview.js:1  Uncaught Error: No interop methods are registered for renderer 0
    at k (blazor.webview.js:1:13290)
    at blazor.webview.js:1:13196
    at T (blazor.webview.js:1:13379)
    at N (blazor.webview.js:1:13170)
    at x.dispatchGlobalEventToAllElements (blazor.webview.js:1:15755)
    at x.onGlobalEvent (blazor.webview.js:1:14948)
```

### Steps to Reproduce

1. Create a new .NET Maui Blazor App and target .NET 8 preview (`8.0.100-preview.7.23376.3`)
2. Run the app on e.g. `Windows Machine`
3. Open the dev tools
4. Navigate through the menu and you notice the exception
5. But its easiest to see on the `Counter` page and clicking the `Click Me` button

### Version with bug

8.0.100-preview.7.23376.3

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Windows, and others

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

```
blazor.webview.js:1  Uncaught Error: No interop methods are registered for renderer 0
    at k (blazor.webview.js:1:13290)
    at blazor.webview.js:1:13196
    at T (blazor.webview.js:1:13379)
    at N (blazor.webview.js:1:13170)
    at x.dispatchGlobalEventToAllElements (blazor.webview.js:1:15755)
    at x.onGlobalEvent (blazor.webview.js:1:14948)
```

**Comment by Eilon** [comment]
Alright we think we know what caused this and have a solution we're testing. We'll also test out a workaround so that anyone running into this in .NET 8 Preview 7 can get their Blazor Hybrid apps working.

cc @MackinnonBuck

**Comment by Eilon** [comment]
# Workaround for .NET 8 Preview 7

For anyone encountering this issue in .NET 8 Preview 7 (released August 8th, 2023), here's how you can work around it in your apps:

1. Download the file [blazor.webview.net8-p7fix.zip](https://github.com/dotnet/maui/files/12307000/blazor.webview.net8-p7fix.zip), decompress the ZIP, and add the `blazor.webview.net8-p7fix.js` in it to your app's `wwwroot` folder
2. Edit your app's `wwwroot/index.html` file change the `_framework/blazor.webview.js` reference to instead point to the new file you added:
    ```html
    <script src="blazor.webview.net8-p7fix.js" autostart="false"></script>
    ```
    (Note that the exact filename/sub-folder don't matter, so you can rename the file, as long as it doesn't conflict with any other existing file in your app.)
3. You should now be able to build/run/publish your app on all .NET MAUI platforms

This is already fixed for .NET 8 Preview 8. When you update to .NET 8 Preview 8, you will need to delete the file that you added and also change back the `<script ...>` reference in `index.html`.

If anyone here tries out this workaround and is successful (or not), please let us know. Thanks!

**Comment by Fydar** [comment]
The workaround was successful for me! Thanks for that! 🎉

**Comment by v-Lily** [comment]
@Eilon I tried the workaround in [#16609 (comment)](https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849), but it didn't solve my issue([#2270](https://github.com/aspnet/AspNetCore-ManualTests/issues/2270)). Detailed reproduction steps refer to issue [#2270](https://github.com/aspnet/AspNetCore-ManualTests/issues/2270#:~:text=Repro%20Steps,click%20me%20button).

![image](https://github.com/dotnet/maui/assets/83056958/ead03752-9f28-4a84-b724-b2975692dec1)

**Comment by Eilon** [comment]
@MackinnonBuck - any idea about this one? In the macOS screenshot it's showing `renderer 3,` which I think is correct (it used to say `renderer 0`). And the filename shows that it's using the fixed JS file.

**Comment by MackinnonBuck** [comment]
I'll need a full repro to know what's going on there. @v-Lily, does your project use preview7 nugets? Could you please upload a repro project as a public GitHub repository?

**Comment by Xyncgas** [comment]
Thank u

**Comment by v-Lily** [comment]
> I'll need a full repro to know what's going on there. @v-Lily, does your project use preview7 nugets? Could you please upload a repro project as a public GitHub repository?

@MackinnonBuck 
Yes, my project uses preview 7 nugets and this issue also reproduces on Windows. I have uploaded the Windows repro project as a public GitHub [repository](https://github.com/v-Lily/MauiApp2.git).

**Comment by Eilon** [comment]
I'll take a look.

**Comment by Eilon** [comment]
Here's the SDK version I'm using:

```
C:\Users\elipton>dotnet --info
.NET SDK:
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          win-x64

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.4.23260.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

@v-Lily - can you run `dotnet --info` and report what you see?

**Comment by Eilon** [comment]
And in the repro app from @v-Lily if I switch back to the regular `blazor.webview.js` that has the bug, I get the expected renderer failure.

In `index.html` I changed it to:

```
    <script src="/_framework/blazor.webview.js" autostart="false"></script>
    <!-- <script src="blazor.webview.net8-p7fix.js" autostart="false"></script> -->
```

And here's the 'expected' error on Windows:
<img width="724" alt="image" src="https://github.com/dotnet/maui/assets/202643/24b866b3-9012-4525-ba94-c87d37c69fb4">

And Android:
<img width="937" alt="image" src="https://github.com/dotnet/maui/assets/202643/cde2ac4e-1019-487c-8a1c-3e4811ddc7ae">

**Comment by Eilon** [comment]
@v-Lily - I wonder if maybe the app wasn't fully re-built? Can you try doing a "Clean" and then build/run again?

**Comment by v-Lily** [comment]
> Here's the SDK version I'm using:
> 
> ```
> C:\Users\elipton>dotnet --info
> .NET SDK:
>  Version:   8.0.100-preview.7.23376.3
>  Commit:    daebeea8ea
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22621
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\
> 
> .NET workloads installed:
> There are no installed workloads to display.
> 
> Host:
>   Version:      8.0.0-preview.7.23375.6
>   Architecture: x64
>   Commit:       65b696cf5e
>   RID:          win-x64
> 
> .NET SDKs installed:
>   3.1.426 [C:\Program Files\dotnet\sdk]
>   7.0.400 [C:\Program Files\dotnet\sdk]
>   8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 8.0.0-preview.4.23260.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Other architectures found:
>   x86   [C:\Program Files (x86)\dotnet]
>     registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found
> ```
> 
> @v-Lily - can you run `dotnet --info` and report what you see?

Here's the SDK version I'm using:
```
C:\Users\v-lilyli1>dotnet --info
.NET SDK:
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          win-x64

.NET SDKs installed:
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by PeymanDinani** [comment]
This issue only happens on Visual Studio 17.8.0 Preview 1.0.
I rolled back to Visual Studio 17.7.0 Preview 6.0 and opened the same project and it works just fine.

Any Idea?

**Comment by Eilon** [comment]
> This issue only happens on Visual Studio 17.8.0 Preview 1.0. I rolled back to Visual Studio 17.7.0 Preview 6.0 and opened the same project and it works just fine.
> 
> Any Idea?

@PeymanDinani - this issues affects .NET 8 Preview 7, which I believe came with Visual Studio 17.8 Preview 1. You can either use [the workaround listed above](https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849), or go back to using an earlier preview of .NET 8 (such as Preview 6). The full fix will be available in the next pre-release of .NET 8.

**Comment by PeymanDinani** [comment]
> > This issue only happens on Visual Studio 17.8.0 Preview 1.0. I rolled back to Visual Studio 17.7.0 Preview 6.0 and opened the same project and it works just fine.
> 
> > 
> 
> > Any Idea?
> 
> 
> 
> @PeymanDinani - this issues affects .NET 8 Preview 7, which I believe came with Visual Studio 17.8 Preview 1. You can either use [the workaround listed above](https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849), or go back to using an earlier preview of .NET 8 (such as Preview 6). The full fix will be available in the next pre-release of .NET 8.

Oh ok. I guess I am experiencing a different issue with the same side side effect. They closed my post on Microsoft visual studio forums and pointed me here.

My issue for reference:

https://developercommunity.visualstudio.com/t/Net-Maui-Blazor-hybrid-app-Events-are-n/10445068

**Comment by Eilon** [comment]
Hi @PeymanDinani , I was the one who closed that issue because it appears to be the same thing (clicks not responding in Blazor Hybrid apps with .NET 8 Preview 7). If you want to use .NET 8 Preview 7, please refer to the workaround listed above (it should only take 2 minutes to do the workaround).

**Comment by Xyncgas** [comment]
So if .NET preview becomes stable how do I upgrade my application to it, do I have to create a new project in the newest .NET stable or I can simply update my visual studio + remove the 'temporary changes' we applied using your zip

**Comment by Eilon** [comment]
> So if .NET preview becomes stable how do I upgrade my application to it, do I have to create a new project in the newest .NET stable or I can simply update my visual studio + remove the 'temporary changes' we applied using your zip

@Xyncgas - for anyone using specifically .NET 8 Preview 7, you can use the workaround posted above. All other versions are fine (.NET 6, .NET 7, .NET 8 Preview 1-6, and any .NET 8 pre-release _after_ Preview 7).

**Comment by Eilon** [comment]
Hi everyone, you should be able to download .NET 8 RC1 that was released this week and has the official fix. If you previously used the workaround posted above, you'll need to undo that change (delete the JS file and change the `<script>` reference back).
