### ISSUE TITLE
new MAUI App project, Nuget dependencies are not being restored

### ISSUE THREAD

**Issue by carloswis** [dotnet/maui#16615]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Hi Team, when creating a new MAUI App project, Nuget dependencies are not being restored and also show these errors:

![image](https://github.com/dotnet/maui/assets/89159940/8cf6d18b-3ea0-4775-972e-d6df02f7439d)

![image](https://github.com/dotnet/maui/assets/89159940/68925112-bacc-4b58-8f90-d948cabc4847)

I have followed all steps from the tutorial and all Maui workloads installed.

**Comment by drasticactions** [comment]
Do you have a `global.json` somewhere in the directory tree where you're building your app? If you open the directory where your app csproj is and run

`dotnet --info` what do you see?

**Comment by carloswis** [comment]
> dotnet --info

Hi, I dont see any global.json in the app directory:

Here is the output of dotnet --info:
[Dotnet.txt](https://github.com/dotnet/maui/files/12307963/Dotnet.txt)

**Comment by carloswis** [comment]
> Do you have a `global.json` somewhere in the directory tree where you're building your app? If you open the directory where your app csproj is and run
> 
> `dotnet --info` what do you see?

Hi, Found the global.json in the top parent folder, here it is:

[global.txt](https://github.com/dotnet/maui/files/12308011/global.txt)

**Comment by carloswis** [comment]
Hi Team, fixed changing sdk to 7.0.0 inside global.json

Thanks.
