### ISSUE TITLE
App is crashing on using "Share" word in MenuFlyoutSubItem 

### ISSUE THREAD

**Issue by theRealGupta** [dotnet/maui#16618]
### Description

Hi Dev, 

On creation on a menu using keyword "Share" app is crashing

```
<FlyoutBase.ContextFlyout>

                                        <MenuFlyout x:Name="RightClickMenu">
                                           
                                            <!--Share-->

                                            <MenuFlyoutSubItem Text="Share" Command="{Binding ShareCommand}">
                                                         <MenuFlyoutItem Text="Facebook"
                                                           Command="{Binding ShareFacebookCommand}"/>
                                            </MenuFlyoutSubItem>
                                            <!--Create-->

                                            <MenuFlyoutSubItem Text="Create" Command="{Binding CreateAlbumCommand}">

                                            </MenuFlyoutSubItem>

                                            <!--Delete-->
                                            <MenuFlyoutItem Text="Delete" Command="{Binding DeleteCommand}"/>

                                        </MenuFlyout>
                                    </FlyoutBase.ContextFlyout>
```

As you can see I am using "Share" Key word in MenuFlyoutSubItem Text Field using this key word crashing the app on right Click

CRASH REPORT 

> Unhandled Exception:
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Maui.Platform.MenuExtensions.ToPlatformMenu(IList`1 menuElements, String title, IImageSource imageSource, IMauiContext mauiContext, IUIMenuBuilder uIMenuBuilder)
>    at Microsoft.Maui.Handlers.MenuFlyoutSubItemHandler.CreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler`2[[Microsoft.Maui.IMenuFlyoutSubItem, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIMenu, Microsoft.MacCatalyst, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].OnCreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
>    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
>    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
>    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
>    at Microsoft.Maui.Platform.MenuExtensions.ToPlatformMenu(IList`1 menuElements, IMauiContext mauiContext)
>    at Microsoft.Maui.Handlers.MenuFlyoutHandler.CreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler`2[[Microsoft.Maui.IMenuFlyout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIMenu, Microsoft.MacCatalyst, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].OnCreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
>    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
>    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
>    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
>    at Microsoft.Maui.Platform.MauiUIContextMenuInteraction.GetConfigurationForMenu()
>    at Microsoft.Maui.Platform.MauiUIContextMenuInteraction.FlyoutUIContextMenuInteractionDelegate.GetConfigurationForMenu(UIContextMenuInteraction interaction, CGPoint location)
>    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
>    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
>    at PhotoScannerApp.Program.Main(String[] args) in /Users/anupg/workSpace/MindFire/AmbirTechnology/PhotoScanner/PhotoScannerApp/PhotoScannerApp/Platforms/MacCatalyst/Program.cs:line 13
> 2023-08-09 10:14:42.749 PhotoScannerApp[35055:4844862] Unhandled managed exception: Object reference not set to an instance of an object. (System.NullReferenceException)
>    at Microsoft.Maui.Platform.MenuExtensions.ToPlatformMenu(IList`1 menuElements, String title, IImageSource imageSource, IMauiContext mauiContext, IUIMenuBuilder uIMenuBuilder)
>    at Microsoft.Maui.Handlers.MenuFlyoutSubItemHandler.CreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler`2[[Microsoft.Maui.IMenuFlyoutSubItem, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIMenu, Microsoft.MacCatalyst, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].OnCreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
>    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
>    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
>    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
>    at Microsoft.Maui.Platform.MenuExtensions.ToPlatformMenu(IList`1 menuElements, IMauiContext mauiContext)
>    at Microsoft.Maui.Handlers.MenuFlyoutHandler.CreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler`2[[Microsoft.Maui.IMenuFlyout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIMenu, Microsoft.MacCatalyst, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].OnCreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
>    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
>    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
>    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
>    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
>    at Microsoft.Maui.Platform.MauiUIContextMenuInteraction.GetConfigurationForMenu()
>    at Microsoft.Maui.Platform.MauiUIContextMenuInteraction.FlyoutUIContextMenuInteractionDelegate.GetConfigurationForMenu(UIContextMenuInteraction interaction, CGPoint location)
>    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
>    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
>    at PhotoScannerApp.Program.Main(String[] args) in /Users/anupg/workSpace/MindFire/AmbirTechnology/PhotoScanner/PhotoScannerApp/PhotoScannerApp/Platforms/MacCatalyst/Program.cs:line 13
> 
> =================================================================
> 	Native Crash Reporting
> =================================================================
> Got a SIGABRT while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries 
> used by your application.
> =================================================================
> 
> =================================================================
> 	Native stacktrace:
> ======

===========================================================

### Repro

https://github.com/theRealGupta/MAUI-Bug-FlyoutMenu

**Comment by theRealGupta** [comment]
this is code for MainPage.xaml 

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="FlyoutMenu.MainPage">

    <Label Text="Right click here">


        <FlyoutBase.ContextFlyout>

            <MenuFlyout x:Name="RightClickMenu" FlyoutItem.IsVisible="False">
                <!--Add to Album-->

                <MenuFlyoutSubItem Text ="Add to Album" FlyoutItem.IsVisible ="False">
                    <MenuFlyoutItem Text="Create New"/>
                </MenuFlyoutSubItem>
                <!--Save-->

                <MenuFlyoutItem Text="Save" />

                <!--Share-->

                <MenuFlyoutSubItem Text="Share">
                    <MenuFlyoutItem Text="Facebook"/>
                    <MenuFlyoutItem Text="Twitter"/>
                </MenuFlyoutSubItem>
                

                <!--Delete-->
                <MenuFlyoutItem Text="Delete" />

            </MenuFlyout>

        </FlyoutBase.ContextFlyout>

    </Label>

</ContentPage>
```


and no other code is required to test this 
You can noticed here I used "**Share**" keyword in `MenuFlyoutSubItem` if i change this app will not crash otherwise it will crash

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0 in Windows 11, it not repro on .NET 8.0 and .NET7.0 using below Project.
[FlyoutMenu.zip](https://github.com/dotnet/maui/files/12394330/FlyoutMenu.zip)
![FlyoutMenu](https://github.com/dotnet/maui/assets/131441429/d8891be9-bbbd-48ec-bdee-1f4c33eddcc3)
