### ISSUE TITLE
Blazor button events not firing on MAUI Hybrid project after .NET 8 Preview 7 package update

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#16616]
### Description

Blazor button events not firing on the MAUI Hybrid project after .NET 8 Preview 7 package update.

This is the case with WinForms and WPF hybrid apps too.

The same is working with the earlier preview version - Preview 6 package on Preview 7 runtime. Seems some issue in the latest preview version of the Package.

### Steps to Reproduce

1. Create a new .NET MAUI Blazor Hybrid app from the template
2. Build for any supported target
3. Run the app and navigate to the Counter page using the Navigation menu
4. Try to increment the Counter

### Link to public reproduction project repository

The default template itself is sufficient, no authored code

### Version with bug

8.0.0-preview.7.8842

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, Windows, I was *not* able to test on other platforms

### Affected platform versions

All platforms

### Did you find any workaround?

Nope.

**Comment by egvijayanand** [comment]
@Eilon FYI

**Comment by campersau** [comment]
Seems similar to https://github.com/dotnet/maui/issues/16609
Do you get the same JavaScript exception?
(You can open the dev tools via F12 when running on Windows.)

**Comment by Eilon** [comment]
Please refer to https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849 for a workaround for this issue.

**Comment by egvijayanand** [comment]
> Please refer to [#16609 (comment)](https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849) for a workaround for this issue.

The fix is working for all Blazor hybrid scenarios, .NET MAUI, WinForms, and WPF. Thanks @Eilon.
