### ISSUE TITLE
Net 7 and net 8 preview 1 side by side  I get Platform version is not present for one or more target frameworks,

### ISSUE THREAD

**Issue by gabsamples6** [dotnet/maui#16626]
### Description

I have upgraded both visual studio and I get
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-ios

Any suggestions

### Steps to Reproduce

Upgraded to latest visual studio 2022 and also preview at the same time
and I get
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-ios

### Link to public reproduction project repository

n/a

### Version with bug

7.0.92

### Last version that worked well

7.0.86

### Affected platforms

iOS, Android

### Did you find any workaround?

I am looking for a workaround.
I have even rolledback to previous version of visual studio but still same error.

Shall I remove preview?

**Comment by drasticactions** [comment]
When you installed the Visual Studio Preview and the .NET 8 preview, did you select to install the MAUI workload? If you go to your command line and type

`dotnet workload list`

What do you see?

Most likely your issue has nothing to do with the Visual Studio preview. If you installed the .NET 8 Preview, unless you have a `global.json` to set a specific SDK/Runtime, it will always try to use the newest version to compile. If you didn't install the MAUI workloads for the .NET 8 preview, it will most likely complain that they are missing.

**Comment by gabsamples6** [comment]
@drasticactions thanks for your reply I am not longer at my desk I will try later 

I had preview 6 installed and I just updated from visual studio to latest preview.

Should I have removed it previous six first?
Why did affect vs stable versions (updated to latest using visual studio check update too)

I have rolled back latest stable but still issue?
Should I delete all nugets from cache? 

I will run that come line when back at my desk

many thanks for any suggestions

**Comment by tranb3r** [comment]
I've had a similar issue when upgrading visual studio preview.
There was no checkbox to install the maui workload in the vs installer.
So I've had to manually install the workload after updating visual studio preview.

**Comment by espenrl** [comment]
MAUI was simply removed from my system when I upgraded VS to the latest version. Thanks @tranb3r

**Comment by gabsamples6** [comment]
@espenrl so what did you do to make it work ?
Did you have to install the workloads for stable vs and preview separately? Did you upgrade using visual studio installer?

many thanks

**Comment by gabsamples6** [comment]
@tranb3r  so did u install the workload separately too? Many thanks

**Comment by tranb3r** [comment]
> @tranb3r so did u install the workload separately too? Many thanks

Yes, I installed the workload manually, since for some unexplained reason, upgrading VS-Preview made it disappear.
I'm always testing VS upgrade in a VM, and I'm not mixing Stable and Preview.

**Comment by gabsamples6** [comment]
Thanks to @tranb3r  and @espenrl  for their input - reinstalling workloads fixed the issue.. I will close this but clearly Visual studio removes the workload when it should not! 

CC @PureWeen
