### ISSUE TITLE
GitInfo -> Devlooped.SponsorLink dependency violates privacy and collects developer PII without consent

### ISSUE THREAD

**Issue by Eonasdan** [dotnet/maui#16638]
`Devlooped.SponsorLink` is current a hot topic. It collects the git user email address and posts it to an Azure blob storage. And as this user points out in the Moq discussion, it adds a `thread.sleep`.

![image](https://github.com/dotnet/maui/assets/1006516/5029b843-7f37-4ff7-86d1-70aa85772c43)

**Comment by drasticactions** [comment]
MAUI doesn't use moq internally for its tests or anywhere else AFAIK.

There are many places to have this conversation, this isn't one of them. Sorry.

**Comment by jfversluis** [comment]
Also see #16647
