### ISSUE TITLE
[regression/8.0.0-preview.7.8842] Bug: Multiple platforms Editor & Entry Two Way binding to text

### ISSUE THREAD

**Issue by SamuelJames101** [dotnet/maui#16636]
1) Create an editor
2) Bind its text property to attached BindingContext ViewModel
3) Enter some text into the editor
4) Change the text value in the viewModel

Expected Results:
Views editors text updates

Actual Results:
Views editor keeps old text. However, I can see that the getter is hit indicating the view does come up for it. Backing field for text binding is also correctly set.

The issue is reproducible on MacCatalyst, iOS And Android. @drasticactions has also confirmed on WinUI

Previously working in .Net 7

Repo: https://github.com/SamuelJames101/EditorAndEntryBugNet8

**Comment by drasticactions** [comment]
@SamuelJames101 
> Additional issue (iOS/Mac & Editor only) : If you look at the screen shot you'll see the placeholder text is cut off, miss aligned and has different font size to normal text. I see there is a fix for incorrect size (#15750) but not sure about the other bits.

Anything "Additional" should be its own issue, rather than making this an uber issue. It makes it easier to fix and to roll them out independently when they are ready, if there are bugs.

**Comment by SamuelJames101** [comment]
@drasticactions I will separate the bugs now : https://github.com/dotnet/maui/issues/16656

**Comment by drasticactions** [comment]
> @drasticactions The additional bug now has its own report : #16656

Thanks! I also tested this on WinUI and it repros there. Seems like it's probably intrinsic rather than platform specific.

**Comment by SamuelJames101** [comment]
@drasticactions Thanks mate! What bug did you test on WinUI? This issue or the new one I have raised? As I can edit the platforms it affects.

**Comment by drasticactions** [comment]
This binding issue. It works in net7.0 but fails on net8.0, and like you I can repro it on the other platforms too.

**Comment by StephaneDelcroix** [comment]
should be fixed by #16410
