### ISSUE TITLE
https://github.com/gorkhadk/maui_crash_reproduction

### ISSUE THREAD

**Issue by gorkhadk** [dotnet/maui#16630]
https://github.com/gorkhadk/maui_crash_reproduction

_Originally posted by @gorkhadk in https://github.com/dotnet/maui/issues/16001#issuecomment-1671124485_

**Comment by gorkhadk** [comment]
Reproduction added on original issue

**Comment by Eilon** [comment]
Hi @gorkhadk , what issue is this referring to? Can you edit the original issue to add this link?

**Comment by samhouts** [comment]
Duplicate of #16001
