### ISSUE TITLE
Bug report yaml is broken

### ISSUE THREAD

**Issue by vividos** [dotnet/maui#16645]
Yesterday there was a "Bug report" item when opening a new GitHub issue, but today there's none. When opening the .yml file, it shows an error:
https://github.com/dotnet/maui/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml

> There is a problem with this template
> 
> body[5]: checkbox is not a valid input type. [Learn more about this error.](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-x-is-not-a-valid-input-type)

**Comment by vividos** [comment]
Most probably caused by PR #16613.

**Comment by vividos** [comment]
And fixed by PR #16643. Sorry for the noise :-D

**Comment by samhouts** [comment]
Thanks! Silly me didn't check that the yaml was right 😂
