### ISSUE TITLE
Can't use WebView with local files stored as MauiAssets on Windows

### ISSUE THREAD

**Issue by vividos** [dotnet/maui#16646]
### Description

I'm using a `WebView` in a MAUI content page and want to reference local files. From #7672 I gather that on Windows I can use the `https://appdir/` URL and the Windows `WebView` handler sets up a virtual folder mapping so that I can reference local files that are marked with `MauiAsset`. I have two similar problems here:

1. When using an `HtmlWebViewSource`, the BaseUrl is set to the URL but the image can't be referenced:

>     Source = new HtmlWebViewSource
>     {
>         Html = "<html><body><h1>Hello World!</h1>" +
>                 "<img src='dotnet_bot.png' />" +
>                 "</body></html>",
>         BaseUrl = "https://appdir/",
>     };

The image file is placed correctly in the app's layout folder at build.

2. When using a `UrlWebViewSource`, the Windows WebView first shows an error "Hmmm… can't reach this page", then after a few seconds, reloads the page and everything works:

>     Source = new UrlWebViewSource
>     {
>         Url = "https://appdir/info.html",
>     };

Both bugs makes it hard to show WebView content that references local asset files.

I didn't test the other platforms, as they need a different `BaseUrl` or `Url`, and the handler doesn't need to set up a virtual host name to folder mapping.

I have the feeling that calling `WebView2`'s `SetVirtualHostNameToFolderMapping()` is missing at some spot. I have written a UWP Xamarin.Forms renderer that also provides platform `WebView2` for `Xamarin.Forms.WebView` and there it works without a problem.

### Steps to Reproduce

I prepared a sample app, and it's the easiest to use this:
1. Clone the https://github.com/vividos/SampleProjects/ repository and open the app contained in the subfolder `WebViewLocalFilesMauiApp`
2. Open the `MainPage.xaml.cs` and find that the second problem case is uncommented.
3. Run the Windows app and see the problem number 2
4. Change `MainPage.xaml.cs` to use the `HtmlWebViewSource` instead of `UrlWebViewSource` to reproduce the first problem
5. Switch back to use `UrlWebViewSource` and remove the `return;` statement in `WebView_HandlerChanged`
6. See that the workaround with manual setting up the virtual host name to folder mapping works

### Link to public reproduction project repository

https://github.com/vividos/SampleProjects/

### Version with bug

7.0.86

### Is this a regression from previous behavior? In other words, did this work before an update and now does not?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

See steps 5 and 6 above, but it's a workaround only for the specific URL.

**Comment by vividos** [comment]
@PureWeen I'd like to look at this issue and figure out a fix. Is there a manual or a list of directions to follow in order to set up development using the dotnet maui git repository? Thank you!

**Comment by mattleibow** [comment]
There is a doc: https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md

Typically my dev path is:
1. Clone repo
2. Restore any tools:  
   ```
   dotnet tool restore
   ```
4. Build the tasks used by the IDE:  
   ```
   dotnet build ./Microsoft.Maui.BuildTasks.slnf
   ```
5. Open the `Microsoft.Maui-dev.sln` solution

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11 .NET 8 with below Project:

**First issue(Windows)**: The image can't be referenced.
![image](https://github.com/dotnet/maui/assets/97647558/2fb8daa0-2cf1-47f8-8f16-9eda3698c222)
**Second issue(Windows)**: WebView first shows an error "Hmmm… can't reach this page", then after a few seconds, reloads the page and everything works.
![image](https://github.com/dotnet/maui/assets/97647558/cf3d2ea8-99ff-4489-8ec1-8a5b49a70730)
**iOS:** Nothing is displayed.
![image](https://github.com/dotnet/maui/assets/97647558/ed74b1a9-c810-4a96-9c93-d4a178229a18)
**Android**: Nothing is displayed.
![image](https://github.com/dotnet/maui/assets/97647558/93b3eb3b-496e-4f08-919a-72a6ff65b932)

**Comment by vividos** [comment]
Just a note, the sample project does not work in Android and iOS, since it would require different base urls, but these two platforms are out of scope for this issue anyway.

**Comment by lukasrut** [comment]
Hello, I have the same issue with displaying images in html on android (image can't be referenced). Is here some progress? Thanks!
