### ISSUE TITLE
CS1061 error in VS for Mac when referencing XAML views in code-behind

### ISSUE THREAD

**Issue by liamself** [dotnet/maui#16659]
### Description

When attempting to reference views defined in a XAML file in the .xaml.cs code-behind file, using Visual Studio for Mac v17.6.2, a CS1061 error is highlighted:

<img width="1041" alt="Screenshot 2023-08-10 at 11 49 09" src="https://github.com/dotnet/maui/assets/16032427/e4b4d117-75ed-44af-9daf-8e42cffe4315">

<img width="561" alt="Screenshot 2023-08-10 at 11 48 43" src="https://github.com/dotnet/maui/assets/16032427/4d16b5c3-c562-46e3-98de-982ea2b2da2f">

The build succeeds without errors and this issue has no effect on the function of the program (the view can still be modified from the .xaml.cs file).

### Steps to Reproduce

1. Open a MAUI solution on Visual Studio for Mac
2. Create a MAUI Page and add a view in the .xaml file, with the x:Name property set
3. In the associated .xaml.cs file, assign the view to a variable
4. Observe the error

Expected behaviour: No warning appears, as the view is defined in the XAML file
Actual behaviour: A CS1061 warning is displayed

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

VS for Mac v17.6.2

### Did you find any workaround?

N/A

### Relevant log output

N/A

**Comment by jfversluis** [comment]
Did you restart VS? Maybe do a clean and rebuild? Does it work on Windows or using VS Code? Does it work if you try this on another control or page?
