### ISSUE TITLE
[regression/8.0.0-preview.7.8842] Maui MenuFlyOut Crashes

### ISSUE THREAD

**Issue by Meapaydin** [dotnet/maui#16663]
### Description

After updating my .net maui project to preview 7, I’ve got this error “Unable to cast object of type ‘Microsoft.Maui.Controls.MenuFlyout’ to type ‘Microsoft.Maui.Controls.VisualElement”. Is there a solution?

### Steps to Reproduce

1. Add MenuFlyOut to a control. 
2. Compile
3.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

Windows

**Comment by Meapaydin** [comment]
StackLayout alintiList = new StackLayout() { Background = Colors.Ivory, VerticalOptions = LayoutOptions.Fill };

/////
MenuFlyout mfly = new MenuFlyout();
MenuFlyoutItem menitYuklemEkle = new MenuFlyoutItem() { Text = “Eylem İfadesi Ekle” };//Colors.DarkTurquoise
menitYuklemEkle.Clicked += MenitYuklemEkle_Clicked;
mfly.Add(menitYuklemEkle);

FlyoutBase.SetContextFlyout(alintiList, mfly);

**Comment by Meapaydin** [comment]
There was no problem before Preview 7...

**Comment by drasticactions** [comment]
@Meapaydin You need to create a full reproduction project. That helps us quickly set up and debug the issue and have a shared reference between you and us for what the bug is. It also makes it easier to create test cases to make sure it doesn't regress in the future.

Posting code blocks isn't enough.

**Comment by Meapaydin** [comment]
To reproduce the issue
1. Create a new project
2. Create a user control MyControl:Grid
3. Add that control to the MainPage content..
 Here is the sample code


namespace MauiApp1
{
    public partial class MainPage : ContentPage
    {
        int count = 0;
        MyKontrol mc = new MyKontrol();
        public MainPage()
        {
            InitializeComponent();
            Content = mc;
        }

        private void OnCounterClicked(object sender, EventArgs e)
        {
            count++;

            if (count == 1)
                CounterBtn.Text = $"Clicked {count} time";
            else
                CounterBtn.Text = $"Clicked {count} times";

            SemanticScreenReader.Announce(CounterBtn.Text);
        }
    }

    public class MyKontrol : Grid
    {
       public MyKontrol()
        {
           MenuFlyout mfly = new MenuFlyout();
            MenuFlyoutItem mitemEserAra = new() { Text = "Eser Ara Ctrl+F" };
            mfly.Add(mitemEserAra);
            MenuItem.SetAccelerator(mitemEserAra, Accelerator.FromString("Ctrl+F"));
            FlyoutBase.SetContextFlyout(this, mfly);
        }

    }

}
