### ISSUE TITLE
[regession/8.0.0-preview.7.8842] MAUI Blazor Hybrid rerenders whole layout after each navigation

### ISSUE THREAD

**Issue by orosbogdan** [dotnet/maui#16661]
### Description

Since .NET 8 preview 7, the whole layout would refresh when a navigating to another page, prompting the "Loading..." each time.
 

### Steps to Reproduce

1. Create new MAUI Blazor Hybrid project in .net 8 preview 7.
2. Navigate back and forth between counter and home page.
3. Observe "Loading..." appearing /flashing after each nagivation.

In previous version, the container / MainLayout.razor would not re-render, just the children components that change.

This gets more severe/noticeable the longer a component takes to load, because the MainLayout is disappearing/re-appearing.

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

```shell
-
```

**Comment by Eilon** [comment]
This is a symptom of this issue: https://github.com/dotnet/maui/issues/16609

Can you try the workaround at https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849 and let us know if that fixes it?
