### ISSUE TITLE
[regression/8.0.0-preview.7.8842] Border clips on the bottom and right

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#16667]
### Description

The following XAML
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="ButtonTest.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    BackgroundColor="White">

    <ScrollView>
        <VerticalStackLayout WidthRequest="500">
            <Border StrokeThickness="5">
                <Button Text="Hi hi" />
            </Border>
        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```

produces the below. 

![image](https://github.com/dotnet/maui/assets/105223895/84a78c1c-6d3e-44e4-8e74-c2d466f5ab43)

This did not occur in .NET Preview 7

### Steps to Reproduce

1. Create a border
2. Notice clipping
3. Nice.

### Link to public reproduction project repository

https://github.com/daltzctr/button-clipping

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by tranb3r** [comment]
Could you please take a look at this issue at the same time? [https://github.com/dotnet/maui/issues/11994](https://github.com/dotnet/maui/issues/7764)

**Comment by dotMorten** [comment]
Seeing this too:
```cs
            double borderThickness = 10;
            Border border = new Border() { WidthRequest = 200, HeightRequest = 100 };
            border.BackgroundColor = Colors.Red;
            border.Stroke = Colors.Blue;
            border.StrokeThickness = borderThickness;
            testArea.Children.Add(border);
```

.NET7: 
![image](https://github.com/dotnet/maui/assets/1378165/84992f52-11bf-4c19-9727-103407e6235a)
.NET8 preview 8:
![image](https://github.com/dotnet/maui/assets/1378165/2e579980-6d56-4a6b-8614-e3b0f8955f28)

**Comment by jstedfast** [comment]
```xml
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Maui.Controls.Sample.MainPage"
    xmlns:local="clr-namespace:Maui.Controls.Sample"
    BackgroundColor="White">

    <Grid ColumnDefinitions="*,*" RowDefinitions="*,*" WidthRequest="500" HeightRequest="500">
        <Border Grid.Row="0" Grid.Column="0" BackgroundColor="Red" Stroke="Blue" StrokeThickness="10" StrokeShape="{RoundRectangle CornerRadius=20}">
        </Border>
    </Grid>

</ContentPage>
```

Windows:
![windows](https://github.com/dotnet/maui/assets/338984/6ef9ff0e-f4d3-4a31-928b-1ab6adc4df9a)

Android:
![android](https://github.com/dotnet/maui/assets/338984/166d7d92-0df1-4f68-88ce-93093767c668)

**Comment by dotMorten** [comment]
If I scale up the above android image to 500x500, I get a 20px border, not 10:
![image](https://github.com/dotnet/maui/assets/1378165/1cf9e98c-38fc-4cff-8b80-58d82dd5c0a1)

**Comment by jstedfast** [comment]
I think I changed it from 10 to 20, I should have redone Windows screenshot but didn't

I also changed Width/HeightRequests from 500 to 300 to better fit in Android's screen.

**Comment by jstedfast** [comment]
Correction: I changed the Width/HeightRequests to 300, but did not change the StrokeThickness. But I did add Padding="10" for Android.

I'll redo all of the screenshots once I get an iOS screenshot going.

**Comment by jstedfast** [comment]
Okay, so if I use the following XAML:

```xml
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Maui.Controls.Sample.MainPage"
    xmlns:local="clr-namespace:Maui.Controls.Sample"
    BackgroundColor="White">

    <Grid ColumnDefinitions="*,*" RowDefinitions="*,*" WidthRequest="300" HeightRequest="300" Padding="10" BackgroundColor="LightGray">
        <Border Grid.Row="0" Grid.Column="0" BackgroundColor="Red" Stroke="Black" StrokeThickness="10" StrokeShape="{RoundRectangle CornerRadius=20}" />
        <Border Grid.Row="0" Grid.Column="1" BackgroundColor="Green" Stroke="Black" StrokeThickness="10" StrokeShape="{RoundRectangle CornerRadius=20}" />
        <Border Grid.Row="1" Grid.Column="0" BackgroundColor="Blue" Stroke="Black" StrokeThickness="10" StrokeShape="{RoundRectangle CornerRadius=20}" />
        <Border Grid.Row="1" Grid.Column="1" BackgroundColor="Yellow" Stroke="Black" StrokeThickness="10" StrokeShape="{RoundRectangle CornerRadius=20}" />
    </Grid>

</ContentPage>
```

...and I modify the UpdatePath() method found in `maui\src\Core\src\Platform\Windows\BorderExtensions.cs` to:

```csharp
		internal static void UpdatePath(this Path borderPath, IShape? borderShape, double width, double height)
		{
			if (borderShape == null)
				return;

			var strokeThickness = borderPath?.StrokeThickness ?? 0;

			if (width <= 0 || height <= 0)
				return;

			var pathSize = new Graphics.Rect(strokeThickness / 2, strokeThickness / 2, width - strokeThickness, height - strokeThickness);
			var shapePath = borderShape.PathForBounds(pathSize);
			var geometry = shapePath.AsPathGeometry();

			if (borderPath != null)
			{
				borderPath.Data = geometry;
				//borderPath.RenderTransform = new TranslateTransform() { X = -(strokeThickness / 2), Y = -(strokeThickness / 2) };
			}
		}
```

Then I get the followinging rendering:
![windows-fixed](https://github.com/dotnet/maui/assets/338984/50ba6911-d7c7-4c4d-9275-415cb263d76a)

Which I think is correct, other than maybe the 1px spacing between the items?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11 .NET 8, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[button-clipping.zip](https://github.com/dotnet/maui/files/12405933/button-clipping.zip)

**Comment by orange-pig** [comment]
version: 8.0.0-preview.7.8842

The Border sample out of bounds, left and top appear to be 2 pixels out of bounds, right and bottom appear to be >4 pixels out of bounds. 

![image](https://github.com/dotnet/maui/assets/5195198/16f1c840-054f-46d9-b8f6-1359707f0a12)

**Comment by tranb3r** [comment]
@samhouts
About the 1px spacing between the items: is it going to be fixed? 
Thanks
