### ISSUE TITLE
Error NETSDK1032: The RuntimeIdentifier platform 'osx-arm64' and the PlatformTarget 'x64' must be compatible.

### ISSUE THREAD

**Issue by alataffective** [dotnet/maui#16673]
### Description

When building a new macOS Application in Release x64 build configuration, I get the build error: /usr/local/share/dotnet/sdk/7.0.307/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(5,5): Error NETSDK1032: The RuntimeIdentifier platform 'osx-arm64' and the PlatformTarget 'x64' must be compatible. (NETSDK1032) (NewProject)

### Steps to Reproduce

In Visual Studio for Mac:

1. Choose a new project
2. Select macOS Application: Mac > App > .NET, and click Continue
3. Choose a project name, e.g. NewProject, and click Create
4. In the solution, right click the project and select Properties
5. Choose a Configuration of Release, a Platform Target of x64, and click OK
7. Select the Release build configuration
8. Build the project

Workload details:

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
macos                      13.3.7090/7.0.100      SDK 7.0.300
maui-maccatalyst           7.0.92/7.0.100         SDK 7.0.300
maui-ios                   7.0.92/7.0.100         SDK 7.0.300
maui-android               7.0.92/7.0.100         SDK 7.0.30

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 13.5

### Did you find any workaround?

No.

### Relevant log output

```shell
Building NewProject (Release)
Build started 8/10/2023 4:56:14 PM.
__________________________________________________
Project "/Users/user/Projects/NewProject/NewProject/NewProject.csproj" (Build target(s)):

[...]
    __________________________________________________
    Project "/Users/user/Projects/NewProject/NewProject/NewProject.csproj" is building "/Users/user/Projects/NewProject/NewProject/NewProject.csproj" (_BuildRidSpecificAppBundle target(s)):

    Target _CheckForMismatchingPlatform:
        /usr/local/share/dotnet/sdk/7.0.307/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(264,5): error NETSDK1032: The RuntimeIdentifier platform 'osx-arm64' and the PlatformTarget 'x64' must be compatible.
    Done building target "_CheckForMismatchingPlatform" in project "NewProject.csproj" -- FAILED.

    Done building project "NewProject.csproj" -- FAILED.

Build FAILED.

/usr/local/share/dotnet/sdk/7.0.307/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(264,5): error NETSDK1032: The RuntimeIdentifier platform 'osx-arm64' and the PlatformTarget 'x64' must be compatible.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:26.54

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 0 warnings
```

**Comment by mattleibow** [comment]
I think this is because you are trying to publish an x64 app, but publishing apps produce both architectures in the package.

I think you are not looking for `Platform`, but rather a RuntimeIdentifier. Since this does not involve maui or even maui platforms (macOS) i would suggest opening an issue at: https://github.com/xamarin/xamarin-macios/
