### ISSUE TITLE
[Bug] Layout2.Layout has internal Children list, breaks LogicalChildren

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#1667]
### Description

https://user-images.githubusercontent.com/898335/125541073-47644a0f-682a-4ef6-aacd-b108a1915cde.mp4

Layout2.Layout (https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Layout/Layout.cs#L18) contains an internal `public IReadOnlyList<IView>` Children implementation. By not using `LogicalChildren` in the base implementation, XAML Hot Reload does not have a reliable way to get the list of its internal children views, making it impossible to reload any of its contents. 

In order for these new layout types to work, we should make them consistent and use `LogicalChildren`.

### Steps to Reproduce

Use this reproduction project [MauiSizeTest.zip](https://github.com/dotnet/maui/files/6812649/MauiSizeTest.zip)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Redth** [comment]
This is somewhat related to #584

**Comment by Redth** [comment]
Fixed in #1722
