### ISSUE TITLE
After update, Visual Studio 2022 Preview from 17.7. Preview 6 to 17.8.0 Preview 1 OnClick stopped working - MAUI Blazor

### ISSUE THREAD

**Issue by chali-atos** [dotnet/maui#16684]
### Description

The issue is in regard to .NET MAUI Blazor Hybrid App template.
I also test it on Blazor WebAssembly and it worked.

I am attaching a video where it shows this.

https://github.com/dotnet/maui/assets/89792313/12f34b93-2135-43b4-a87b-0a6c6dc2c5e5

### Steps to Reproduce

Steps in the attached video.

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

**Comment by Eilon** [comment]
Hi, sorry about this issue. There is a workaround for this fix listed here: https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849

And it will be fixed in the next update as well.

Can you let us know if the workaround fixes your issue? Thanks!

**Comment by chali-atos** [comment]
Hi, after implementation of this workaround, it started to work. Thanks!
