### ISSUE TITLE
Referencing a Maui Library in a Maui App causes Apt2144 on Android build. on 7.0.400 SDK

### ISSUE THREAD

**Issue by inforithmics** [dotnet/maui#16680]
### Description

Referencing a Maui Library in a Maui App causes Apt2144 on Android build. on 7.0.400 SDK and Visual Studio 2022 17.7

### Steps to Reproduce

1. Create Maui App
2. Create Maui Library
3. Reference MauiLibrary in Maui App
Compilation causes Apt2144 

### Link to public reproduction project repository

https://github.com/inforithmics/MauiLibraryBug

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android

### Affected platform versions

.Net7-Android (7.0.400)

### Did you find any workaround?

1. Removing Net7-Android Target (but this is not really a solution).

2. Another solution would be to make a nuget package of the Maui lib and reference this nuget package.

3. Intrestingly It Compiles with Visual Studio 2022 17.8 (Preview with Framework .NET 8 Perview 7)

4. Retarget the MauiLibrary from Net7.0 to Net6.0 (including os targets) net7.0-android => net6.0-android Then it works too

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2144	invalid file path 'C:\Users\thoma\source\repos\MauiApp2\MauiApp2\obj\Debug\net7.0-android\lp\99.stamp'.	MauiApp2	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.80\tools\Xamarin.Android.Aapt2.targets	123
```

**Comment by mattleibow** [comment]
@jonathanpeppers this ring any bells?

**Comment by inforithmics** [comment]
I looked at the binlog and it seems to be a timing problem because the missing files are created 
![grafik](https://github.com/dotnet/maui/assets/2290863/36bfb801-4218-4367-9202-ece48fea3fac)

![grafik](https://github.com/dotnet/maui/assets/2290863/bfa449cc-9548-4586-bc3c-9fb58e011b79)

**Comment by jonathanpeppers** [comment]
The project above builds for me.

Can you share an MSBuild `.binlog` of this failing? https://aka.ms/binlog

**Comment by inforithmics** [comment]
Here is the binlog
[msbuild.zip](https://github.com/dotnet/maui/files/12317461/msbuild.zip)

On my new Development PC (AMD 7940HS) it doesn't work see binlog
On my slower Windows Dev Kit PC(ARM) it works, so it seems to be a timing issue

**Comment by inforithmics** [comment]
I don't know how deterministic the [number].stamp files are but in every rebzukd other files file.

**Comment by inforithmics** [comment]
When I change the MauiLibrary to net6.0-android it worked, changing back to net7.0-android -it failed again.

**Comment by mattleibow** [comment]
@jonathanpeppers should this be in the android SDK?

**Comment by jonathanpeppers** [comment]
@inforithmics how did you get this nightly build?
```
Assembly = C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.80\tools\Xamarin.Android.Build.Tasks.dll
```

The released version is:
https://www.nuget.org/packages/Microsoft.Android.Sdk.Windows/33.0.68

I believe you are encountering a problem we reverted:

https://github.com/xamarin/xamarin-android/commits/release/7.0.3xx

`33.0.81` would have the bad commit reverted.

**Comment by inforithmics** [comment]
@jonathanpeppers I looked at the folder and the installation date is from 8.8.2023 so I got it when I either install Visual Studio 2022 or Installed Visual Studio 2022 Preview (for .NET 8 MAUI)

Will uninstall both Visual Studio and Preview and install Visual Studio to see  what it installs.

**Comment by inforithmics** [comment]
So I investigated:
Installing Visual Studio 2022 and Visual Studio 2022 Preview didn't download 33.0.80.

But executing dotnet workload update in a directory with following global.json
```
{
  "sdk": {
    "allowPrerelease": false,
    "version": "7.0.302",
    "rollForward": "latestMajor"
  },
  "tools": {
    "allowPrerelease": false,
    "dotnet": "7.0.302",
    "rollForward": "latestMajor"
  }  
}

```

`dotnet workload install update` or `dotnet workload install maui android`

**Comment by jonathanpeppers** [comment]
33.0.80 is only available on the nightly NuGet feed: 
```xml
<add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
```
Is there a `nuget.config` file in the current directory where you ran these commands?

You can also do `dotnet nuget list source` to see all the feeds in a given context.

**Comment by inforithmics** [comment]
Thanks for the Tip, I investigated a Bug in MAUI and therefore forked MAUI and there is 
 <add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json" />
and probably I updated the workloads.

**Comment by inforithmics** [comment]
Because it is a nightly version that seems not to work I updated the workloads again in the repository.
With `dotnet workload update` and got Version 33.0.83 which seems to work so far.
