### ISSUE TITLE
iOS and MacOS - ContentView (CustomControl) inside Grid Row, makes only the last item in the row clickable

### ISSUE THREAD

**Issue by drossoft** [dotnet/maui#16705]
### Description

When a custom control created with a ContentView is placed inside a Grid Row that has other elements, only the last element in the stack is clickable.
I used Maui's test project to demonstrate the behavior.

```xaml
<Grid RowDefinitions="Auto,*,Auto">
		<Label Grid.Row="0"
				Margin="8"
				Text="Header"/>
		<ScrollView Grid.Row="1">
			<VerticalStackLayout
				Spacing="25"
				Padding="30,0"
				VerticalOptions="Center">

				<Image
					Source="dotnet_bot.png"
					SemanticProperties.Description="Cute dot net bot waving hi to you!"
					HeightRequest="200"
					HorizontalOptions="Center" />

				<Label
					Text="Hello, World!"
					SemanticProperties.HeadingLevel="Level1"
					FontSize="32"
					HorizontalOptions="Center" />

				<Label
					Text="Welcome to .NET Multi-platform App UI"
					SemanticProperties.HeadingLevel="Level2"
					SemanticProperties.Description="Welcome to dot net Multi platform App U I"
					FontSize="18"
					HorizontalOptions="Center" />

				<Button
					Text="{Binding Message}"
					SemanticProperties.Hint="Counts the number of times you click"
					Command="{Binding CounterClickedCommand}"
					HorizontalOptions="Center" />

			</VerticalStackLayout>
		</ScrollView>
		<!--<Button Grid.Row="1"
				Text="Button 1"
				Command="{Binding CounterClickedCommand}"
				HorizontalOptions="Start"
				VerticalOptions="End"/>
		<Button Grid.Row="1"
				Text="Button 2"
				Command="{Binding CounterClickedCommand}"
				HorizontalOptions="End"
				VerticalOptions="End"/>-->

			<cc:Button1 Grid.Row="1"/>
			<cc:Button2 Grid.Row="1"/>

		<Label Grid.Row="2"
				Margin="8"
				Text="Footer"/>
	</Grid>
```

The page contains a grid with 3 rows. In the middle row, there is the ScrollView containing the example controls, and I have added two custom controls in the same row Grid.Row="1". 

In total there are 3 buttons, all with the same command. Custom control Buttons are defined like this:

```xaml
<Button 	Text="Button 1"
		Command="{Binding CounterClickedCommand}"
		HorizontalOptions="Start"
		BackgroundColor="Blue"
		TextColor="White"
		VerticalOptions="End"
		Margin="4"/>
```

When running the application, the only button that executes the command is Button2, which is the one in the last position in the row.
If you move Button1 to the end, you will see that Button1 now works and Button2 no longer works.

If buttons are placed directly (Commented lines) it works properly.

This only happens on iOS and MacCatalyst. It works correctly on Android and WinUI.

### Steps to Reproduce

Run the project from the provided repo.

Check that only the button that is placed at the end of the grid row works when a ContentView exists on that row.

### Link to public reproduction project repository

https://github.com/drossoft/grid_issue_demo

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 14.2, McCatalyst 14

### Did you find any workaround?

No

**Comment by hartez** [comment]
The ContentViews you're using for your custom buttons are occupying the entire Grid cell, covering each other and the ScrollView. To see what I mean, try modifying Button1.xaml to this:

```xaml
<ContentView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 xmlns:vm="clr-namespace:grid_issue_demo.ViewModels"
			 x:DataType="vm:SampleViewModel"
			 x:Class="grid_issue_demo.CustomControls.Button1"
			 BackgroundColor="Yellow" Opacity="0.5">
    <Button 
				Text="Button 1"
				Command="{Binding CounterClickedCommand}"
				HorizontalOptions="Start"
				BackgroundColor="Blue"
				TextColor="White"
				VerticalOptions="End"
				Margin="4"/>
</ContentView>
```

With the background color added to the ContentView, you can see that it fills up the entire Grid cell.

The easiest way to fix this would be to move the positioning properties to the main layout:

```xaml
<cc:Button1 Grid.Row="1" HorizontalOptions="Start" VerticalOptions="End"/>
```

**Comment by drossoft** [comment]
Thank you very much for the clarification, I will do so, but shouldn't it behave the same on all platforms? It is very confusing.

**Comment by hartez** [comment]
> Thank you very much for the clarification, I will do so, but shouldn't it behave the same on all platforms? It is very confusing.

It should, but we have some open bugs on Android and Windows where it _doesn't_ always block input when it _should_. That's why it accidentally sort of worked on those platforms.

**Comment by drossoft** [comment]
Thank you! I followed your advice and now it works correctly on all platforms.
