### ISSUE TITLE
[regression/8.0.0-preview.1.7762] Border + RefreshView will let ScrollView no SizeChanged

### ISSUE THREAD

**Issue by xtuzy** [dotnet/maui#16711]
### Description

When a Border in ScrollView and ScrollView in RefreshView, ScrollView no SizeChanged  event.
![sharex-20230812075006](https://github.com/dotnet/maui/assets/17793881/8e30704c-6780-48ba-a4be-e840a3e483a8)

When i delete Border or Delete RefreshView, ScrollView have SizeChanged event.
![sharex-20230812075049](https://github.com/dotnet/maui/assets/17793881/bff4b693-8f8c-4a09-a8d1-d0e7b0ce4ac7)

![sharex-20230812075107](https://github.com/dotnet/maui/assets/17793881/316b54b7-02ab-4c16-b97f-93f105bcb0e7)

I find this bug when i test my project [MauiUICollectionView](https://github.com/xtuzy/MauiUICollectionView) on net8 preview7, when change window size, content don't fit window size.

### Steps to Reproduce

1. clone https://github.com/xtuzy/net8preview7_refeshviewborderbug
2. change windows size, see output information

### Link to public reproduction project repository

https://github.com/xtuzy/net8preview7_refeshviewborderbug

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

windows10.0.19041.0

**Comment by Redth** [comment]
I have another repro that I believe to be the same bug: https://github.com/Redth/MauiRepro_RefreshScrollRepro

**Comment by samhouts** [comment]
Confirmed that this regressed between https://github.com/dotnet/maui/compare/8.0.0-preview.1.7762..7.0.92. https://github.com/dotnet/maui/pull/11357 seems sus.

**Comment by jsuarezruiz** [comment]
![image](https://github.com/dotnet/maui/assets/6755973/c9f44f4a-ba5f-444a-99e9-dd735680a82f)
Where is the Border in the visual tree? Inside the ScrollView? I have added several Borders and with the latest version the SizeChanged event of the ScrollView is triggered.
