### ISSUE TITLE
Context menu not displaying on Mac Catalyst with BlazorWebView

### ISSUE THREAD

**Issue by SimenCTan** [dotnet/maui#16726]
### Description

> When I bind `FlyoutBase.ContextFlyout` to the BlazorWebView control, the context menu appears as expected when right-clicking on Windows, but on Mac Catalyst, it displays the default Mac menu.

### Steps to Reproduce

1. Create a new .net maui project
2. [Add a BlazorWebView to an existing app](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview#add-a-blazorwebview-to-an-existing-app)
3. Mainpage.xaml create a BlazorWebView and bind it like this
```XML
 <BlazorWebView
      x:Name="blazorWebView"
      Grid.Row="1"
      BackgroundColor="AliceBlue"
      HostPage="wwwroot/index.html">
      <FlyoutBase.ContextFlyout>
          <MenuFlyout>
              <MenuFlyoutItem Text="New"/>
              <MenuFlyoutItem Text="Clone"/>
          </MenuFlyout>
      </FlyoutBase.ContextFlyout>
      <BlazorWebView.RootComponents>
          <RootComponent ComponentType="{x:Type views:TextAreaView}" Selector="#app" />
      </BlazorWebView.RootComponents>
 </BlazorWebView>
```

Build and deploy

Expected result :
When right-clicking on both Windows and Mac Catalyst, the custom context menu appears as intended.

Actual result:
Mac Catalyst, it displays the default Mac menu.

Images：
> Windows
![image](https://github.com/dotnet/maui/assets/19427810/16f4849d-5e24-4970-87b0-8b75c415f6b8)
> macOS
![image](https://github.com/dotnet/maui/assets/19427810/29bc20fe-45bc-482f-81a2-20bb9044d793)

### Link to public reproduction project repository

https://github.com/SimenCTan/MauiSamples/tree/main/TelerikBlazorMaui

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

7.0.92

### Affected platforms

macOS

### Affected platform versions

macOS Ventura 13.2.1

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
