### ISSUE TITLE
[Android] Animation on Opacity Issue

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#16729]
### Description

If you perform an animation on a controls Opacity property, the maximum value will be the value when the control was created.

For instance, I have a control the starts out at Opacity=0.5, the animation sets the Opacity value to 1.0, but the Opacity range is now set to 0=>.5, so setting it to 1.0 means an actual Opacity of .5.

In the example below. five controls are created with opacity values of 1.0, .75, .50, .25, and 0.0.

The first button animates each to an opacity of 0.0, the second to an opacity of 1.0. You can see the Opacity value on the right go from 0 to 1, but the actual opacity is capped at its initial value.

This works fine on Windows... and I haven't tested to see if other properties are effected.

![Maui Animation Issues 1](https://github.com/dotnet/maui/assets/46286656/ea84f667-f8ee-418f-af9e-5b29dc9f4c51)

### Steps to Reproduce

Problem: If I have two layered controls on a form and set a click event to fade one in and out, the control that starts off with opacity=0 will never show....

Expected outcome: Opacity works correctly. 

### Link to public reproduction project repository

https://github.com/Stedy59/StedySoft.AnimationIssues.1

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 34

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 .NET 8, not repro on Windows 11 with below Project:
[StedySoft.AnimationIssues.1.zip](https://github.com/dotnet/maui/files/12416033/StedySoft.AnimationIssues.1.zip)

**Comment by PureWeen** [comment]
Duplicate of #15826
