### ISSUE TITLE
[regression/8.0.0-preview.7.8842] Binding Issue: Multiple platform CheckBox control 'IsChecked'

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#16721]
### Description

CheckBox control IsCheckedProperty will not update using a bound property.

### Steps to Reproduce

Create a Checkbox
Bind its IsChecked property to a BindableProperty
Checkbox IsChecked remains at initial value

### Link to public reproduction project repository

https://github.com/Stedy59/StedySoft.BindingIssues.4

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK - all, Android API 34

### Did you find any workaround?

No

**Comment by daltzctr** [comment]
I can confirm this.

**Comment by Stedy59** [comment]
> I can confirm this.

I wonder where the Maui team is... Two-way binding regression issue on most controls, and no one even viewing the reports????

**Comment by StephaneDelcroix** [comment]
should be fixed by #16410
