### ISSUE TITLE
Date format error for September 

### ISSUE THREAD

**Issue by SupaStid** [dotnet/maui#16728]
### Description

Date time format error dd-MMM-yyyy

produces 01-Sept-2023 only for September 

this does not occur for other months which obey the 3 letter short name

I have only witnessed it in WinUi and iOS

Android and iOS simulator work fine

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows, I was *not* able test on other platforms

### Affected platform versions

IOS 16 and Windows 11 as far as I know

### Did you find any workaround?

I do a string replace on a short date from Sept to Sep

**Comment by drasticactions** [comment]
We would need to see how you've implemented your code but my guess right now is that it's either

- A runtime issue, since this should not be specific to the underlying Maui UI Codebase
- A Culture issue with how you're using DateTime and how your application is set up.

**Comment by SupaStid** [comment]
I have written a simple Maui App that demonstrates the issue

https://github.com/SupaStid/dotnet-maui-Date-format-error-for-September-Issue-16728-

Thank you

**Comment by jfversluis** [comment]
Looks like this has been reported for runtime and is by design: https://github.com/dotnet/runtime/issues/87307

If something still isn't right according to you, please report there. This is not something that .NET MAUI influences. Thanks!

**Comment by SupaStid** [comment]
Thank you - I only ever experienced it since Maui programming - to be by design is ridiculous - when did a three letter standard become 4 ??  - Especially when passing that date to SQL Server

Again thank you
