### ISSUE TITLE
WebView does not support setPointerCapture when mouse leaves the control

### ISSUE THREAD

**Issue by Fydar** [dotnet/maui#16727]
### Description

When using a MAUI Blazor Hybrid application, using [HTMLElement.setPointerCapture](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) does not capture the pointer movements when the cursor leaves the WebView.

Reproduced on Windows 10. [Demo project](https://github.com/Fydar/MauiCapturePointerIssue) based on the example from [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) is attached.

## Video Demonstration

https://fydar.github.io/MauiCapturePointerIssue/rundown-video.mp4

## Expected Behaviour

<p align="center">
  <img src="https://raw.githubusercontent.com/Fydar/MauiCapturePointerIssue/main/docs/expected-behaviour-in-edge.gif" alt="Expected behaviour GIF"/></br>
  <sub><b>Figure 1</b>: <i>Expected behaviour demonstrated using Microsoft Edge.</i></sub>
</p>

## Actual Behaviour

<p align="center">
  <img src="https://raw.githubusercontent.com/Fydar/MauiCapturePointerIssue/main/docs/actual-behaviour-in-maui.gif" alt="Actual behaviour GIF"/></br>
  <sub><b>Figure 2</b>: <i>Actual behaviour demonstrated in a MAUI Blazor Hybrid application.</i></sub>
</p>

### Steps to Reproduce

1. Create a File > New .NET MAUI Blazor Hybrid App
2. Add to the `index.html` file in `wwwroot` and add the `setPointerCapture` example from the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture)
3. Observe the actual behaviour when dragging the Slider element outside of the window.

### Link to public reproduction project repository

https://github.com/Fydar/MauiCapturePointerIssue

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by Fydar** [comment]
To be clear, I am getting `"mouseup"` events even when my mouse is not over the window, but I am not getting `"mousemove"` events.

**Comment by Fydar** [comment]
I've tested with both `<WebView>` and `<BlazorWebView>` and they both have this issue.

I created a [blank WPF project](https://github.com/Fydar/MauiCapturePointerIssue/tree/main/src/MauiCapturePointerIssue.WPFWorking) and added a `<wv2:WebView2>` component and **it is working properly** (as shown below).

<p align="center">
  <img src="https://raw.githubusercontent.com/Fydar/MauiCapturePointerIssue/main/docs/expected-behaviour-in-wpf.gif" alt="Expected behaviour as demonstrated in a WPF application."/></br>
  <sub><b>Figure 3</b>: <i>Expected behaviour demonstrated using <a href="https://github.com/Fydar/MauiCapturePointerIssue/tree/main/src/MauiCapturePointerIssue.WPFWorking">a WPF application</a>.</i></sub>
</p>

**Comment by drasticactions** [comment]
Did you try using Webview2 in a WinUI project? That's the closest analog to the MauiBlazor Webview, since it's based on Webview2 on WinUI.

**Comment by Fydar** [comment]
I just created a WinUI3 project and I was able to confirm that it is an issue with WinUI and not MAUI.

**Comment by drasticactions** [comment]
Most likely. The MAUI Blazor Webview and WebView on WinUI use Webview2, so if it doesn't work in a stock WinUI3 app with Webview2, it can't work in MAUI since it's, more or less, the same thing under the covers.

@mattleibow Could this be transferred to the WinUI Repo? I don't think I have the permissions to do that.

**Comment by Eilon** [comment]
This issue was moved to microsoft/microsoft-ui-xaml#8753

**Comment by Eilon** [comment]
(We can't do an _actual_ issue transfer because it's in a different org. Transfer only works between repos in the same org.)
