### ISSUE TITLE
[regression/8.0.0-preview.7.8842] Binding Issue: Multiple platform - Binding a property after an animation fails

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#16723]
### Description

**Clock Example** - After applying the control template, I modify the clock hands by rotating them to the current time. Then bind the RotationProperty.
`
_ = this.Dispatcher.Dispatch(() => {
    DateTime dt = DateTime.Now;
    new Animation {
        { 0, 1, new Animation(v => this._imgClockHour.Rotation = v, 0, 30 * (dt.Hour % 12) + 0.5 * dt.Minute) },
        { 0, 1, new Animation(v => this._imgClockMinute.Rotation = v, 0, 6 * dt.Minute + 0.1 * dt.Second) },
        { 0, 1, new Animation(v => this._imgClockSecond.Rotation = v, 0, 6 * dt.Second + 0.006 * dt.Millisecond) }
    }.Commit(
	this,
	"CurrentTimeAnimation",
	length: (uint)TimeSpan.FromSeconds(1.5).TotalMilliseconds,
	easing: Easing.SinOut,
	finished: async (v, c) => {
			_ = this._imgClockHour.Bind(Image.RotationProperty, path: "HourAngle", source: ClockManager.Current);
			_ = this._imgClockMinute.Bind(Image.RotationProperty, path: "MinuteAngle", source: ClockManager.Current);
			_ = this._imgClockSecond.Bind(Image.RotationProperty, path: "SecondAngle", source: ClockManager.Current);
		await ClockManager.Current.StartAsync();
	});
});

`

### Steps to Reproduce

Expected outcome is that the RotationProperty would bind to the backing bindable.

### Link to public reproduction project repository

https://github.com/Stedy59/StedySoft.BindingIssues.2

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK - all, Android API 34

### Did you find any workaround?

For this example yes... but many others in my Framework would require linking the PropertyChanged event for every property effected. That is not feasible nor appropriate.

**Comment by StephaneDelcroix** [comment]
should be fixed by #16410
