### ISSUE TITLE
ClickGestureRecognizer is not functional

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#16739]
### Description

Using a "ClickGestureRecognizer" on any UI component does not trigger any attacked "Clicked" event. 

### Steps to Reproduce

Adapt the basic MAUI template to the following

```xml
            <Label
                x:Name="CounterBtn"
                HorizontalOptions="Center"
                SemanticProperties.Hint="Counts the number of times you click"
                Text="Click me">
                <Label.GestureRecognizers>
                    <ClickGestureRecognizer Clicked="ClickGestureRecognizer_Clicked" />
                </Label.GestureRecognizers>
            </Label>
```

```csharp
        private void ClickGestureRecognizer_Clicked(System.Object sender, System.EventArgs e)
        {
            count++;

            if (count == 1)
                CounterBtn.Text = $"Clicked {count} time";
            else
                CounterBtn.Text = $"Clicked {count} times";

            SemanticScreenReader.Announce(CounterBtn.Text);
        }
```

### Link to public reproduction project repository

https://github.com/daltzctr/ClickGestureBug

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

You can use `TapGestureRecognizer`, but the *expected* behavior is slightly different. A tap consists of the following sequence on desktop.

1. User "clicks" (but does not release) the LMB. This does NOT trigger the "tapped" event.
2. User then "let's go", raising the "Tapped" event.

I expect that ClickGestureRecognizer (will or does) the following

1. User "clicks", raising the "clicked" event.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11, Android 13.0-API33 and iOS 16.4 .NET 8 with below Project:
[ClickGestureBug.zip](https://github.com/dotnet/maui/files/12424880/ClickGestureBug.zip)

**Comment by Foda** [comment]
Hello! `ClickGestureRecognizer` is obsolete. If you need click events you can utilize the following:
* [TapGestureRecognizer](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/tap), for a sequence of pressed and then released
* [PointerGestureHandler](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/pointer), which has `PointerPressed` and `PointerReleased`

**Comment by daltzctr** [comment]
`PointerGestureHandler` doesn't seem to have a `PointerPressed` and `PointerReleased` as you described.

**Comment by Foda** [comment]
> `PointerGestureHandler` doesn't seem to have a `PointerPressed` and `PointerReleased` as you described.

Ah, this API was added for the upcoming .NET 8 release ([see this ticket here](https://github.com/dotnet/maui/issues/13346)).
