### ISSUE TITLE
MAUI appicon and splash not updating on physical device IPhone 13 - iOS version 16.5.1

### ISSUE THREAD

**Issue by Hugo64** [dotnet/maui#16731]
### Description

I changed the default appicon and splash images in my MAUI solution. The changes were effected on Android device but on iOS device, the default .NET appicon and splash images show. Even just changing the Color property in the .csproj file has no effect on iOS device. I s using Visual Studio Version 17.7.0 (Aug 8th 2023).

### Steps to Reproduce

1.  Create a new MAUI app ;
2.  Change the appicon and/or splash images. (or just change the Color property of the SplashScreen property in .csproj file ;
3.  Run or deploy the app to Android Device - the appicon and/or splash images are updated as expected ;
4.  Run or deploy the app to iOS device - the changes are not effected. The default .NET appiocn and splash images still shows ;
5.  Try to change the name of the appicon and splashscreen svg file, delete app on iOS device, reboot device, clean solution and deplot to iOS device - still appicon and splash images not updated.

![image](https://github.com/dotnet/maui/assets/14372882/dcdb8fab-0831-4af2-8065-823e53ccb8d1)

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

16.5.1

### Did you find any workaround?

None has worked.

**Comment by drasticactions** [comment]
Are you connecting to a physical Mac or are you using Hot Restart to deploy the application?

**Comment by Hugo64** [comment]
> Are you connecting to a physical Mac or are you using Hot Restart to deploy the application?

**Comment by Hugo64** [comment]
> Are you connecting to a physical Mac or are you using Hot Restart to deploy the application?


@drasticactions 
I'm using my own device. An iPhone 13

**Comment by drasticactions** [comment]
@Hugo64 I apologize, but my question was if you're using Hot Restart (Directly connecting your phone to your Windows computer) or connecting your phone to a remote Mac. That difference matters since two sets of tools build and deploy your application to your device.

**Comment by Hugo64** [comment]
> @Hugo64 I apologize, but my question was if you're using Hot Restart (Directly connecting your phone to your Windows computer) or connecting your phone to a remote Mac. That difference matters since two sets of tools build and deploy your application to your device.

Yes, I'm using Hot Restart to connect to my Iphone.

**Comment by mattleibow** [comment]
There are 2 issues here:

 - iOS hot restart does not support custom app icons and splash screens, please log an issue with the VS feedback tool
 - iOS also caches the app icon on devices and there is no way to change it without changing the file name: https://github.com/dotnet/maui/issues/8685

**Comment by Hugo64** [comment]
> Existem 2 questões aqui:
> 
> * A reinicialização a quente do iOS não oferece suporte a ícones de aplicativos personalizados e telas iniciais, registre um problema com a ferramenta de feedback do VS
> * O iOS também armazena em cache o ícone do aplicativo nos dispositivos e não há como alterá-lo sem alterar o nome do arquivo: [a tela inicial não atualiza o iOS ](https://github.com/dotnet/maui/issues/8685)[ #8685](https://github.com/dotnet/maui/issues/8685)[](https://github.com/dotnet/maui/issues/8685)

Would this be a Visual Studio or iOS bug? I downloaded Visual Studio 2022 Preview 17.8 and even so the problem persists until today, it seems to be an old problem.

**Comment by mattleibow** [comment]
Visual Studio as that is where the Hot Restart app people work from.

**Comment by Hugo64** [comment]
A bug has been opened for Microsoft

https://developercommunity.visualstudio.com/t/Bug-in-Hot-Restart-debugger-deployment-f/10444768

**Comment by Hugo64** [comment]
Microsoft support responded to the open call, and it appears to be a Hot Restart limitation. Unfortunately, even if we have the resources, the best choice is to use a MAC.

Response: https://developercommunity.visualstudio.com/t/Bug-in-Hot-Restart-debugger-deployment-f/10444768

**Comment by Hugo64** [comment]
https://developercommunity.visualstudio.com/t/Bug-in-Hot-Restart-debugger-deployment-f/10444768
