### ISSUE TITLE
[regression/8.0.0-preview.6] [Android] SwipeView's data binding doesn't work while using it inside a CollectionView

### ISSUE THREAD

**Issue by nicop85** [dotnet/maui#16742]
### Description

I was testing the last updates available for the Net 8 preview 6 (using Visual Studio 17.7), to see if everything continues to works as expected.

What I have found is that if you have a CollectionView that uses a SwipeView inside it's DataTemplate, the text data bindings of the SwipeView stays empty.

I have created a sample project that I will link below. Inside the MainPage, you will find two CollectionViews with the same structure. The first one has a SwipeView that uses data binding to display some text. The second one also has a SwipeView but with a fixed text.

**Actual result:**
The first CollectionView display empty rows that you can swipe to display the buttons.
The second CollectionView displays the fixed texts and you can also swipe to display the buttons.

**Expected result:**
The first CollectionView should display the text of the data binding.

MAUI version: 8.0.0-preview.6.8686
Net 8 version: 8.0.100-preview.6.23330.14

### Steps to Reproduce

1. Download the sample project
2. Run the code

### Link to public reproduction project repository

https://github.com/nicop85/SwipeViewBindingProblems.git

### Version with bug

8.0.0-preview.6.8686

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.3.8149

### Affected platforms

Android

### Affected platform versions

Android 30 at least

### Did you find any workaround?

Not yet

**Comment by PureWeen** [comment]
This might be resolved by
https://github.com/dotnet/maui/pull/16753
