### ISSUE TITLE
Provide Static MauiContextAccessor

### ISSUE THREAD

**Issue by dansiegel** [dotnet/maui#16759]
### Description

The root application types used by Maui are prescriptive in accessing a Current instance to get the Application Scope IServiceProvider and a reference to IApplication. While this works for Maui Applications it causes problems in Embedding scenarios where the Android MauiApplication or the Windows MauiWinUIApplication for instance will not exist.

### (Public) API Changes

# static MauiContextAccessor

## Properties

| API | Description |
| ------------- | ------------- |
| Services | Gets or sets the IServiceProvider. |
| Application | Gets or sets the IApplication. |

### Usage Scenarios

This provides a single class that can be accessed from:

- Markup Extensions
- Embedding Scenarios
- Existing native Maui Application classes

### Backward Compatibility

This can be added so that under the covers the existing native Maui Application classes such as the Android MauiApplication or the MauiWinUIApplication can use this when getting/setting the Services/Application properties.

```cs
public abstract class MauiWinUIApplication : UI.Xaml.Application, IPlatformApplication
{
    public IServiceProvider Services
    {
        get => MauiContextAccessor.Services;
        protected set => MauiContextAccessor.Services = value;
    }

    public IApplication Application
    {
        get => MauiContextAccessor.Application;
        protected set => MauiContextAccessor.Application = value;
    }
}
```

### Difficulty

Low

**Comment by dansiegel** [comment]
@Eilon the issue is the these properties are public in the native app classes which means that you have developers doing this `MauiWinUIApplication.Current.Services` which blows up instantly in an Embedded scenario because `MauiWinUIApplication.Current` isn't a `MauiWinUIApplication` and would be null if it were cast differently. This affects a number of 3rd party libraries including Syncfusion and Telerik currently which break on WinUI for this exact scenario. 

The goal is to give them a cross platform way of doing what they need to do that can still work in embedded apps.

**Comment by dansiegel** [comment]
For context on this issue. The original proposal is actually a duplicate of the IPlatformApplication API which already exists in MAUI today. The biggest problem it would seem is less about needing a static context to access these properties as you can already do this with `IPlatformApplication.Current`. The problem is that Maui implementations are explicitly referenced. These references need to be updated to use `IPlatformApplication.Current` this will ultimately better support a number of scenarios including Runtime Tests and Embedding.

**Comment by Eilon** [comment]
@dansiegel yeah thanks I did see that other PR. I'm not sure I'm a big fan of that either because of the problems it can create, but I guess it was already there...
