### ISSUE TITLE
Linking of native static library fails and the resulting package is including the native reference

### ISSUE THREAD

**Issue by tentom** [dotnet/maui#16764]
### Description

When binding a native library the library is not statically linked to the executable.  When the this package is consumed by the MAUI project the library is still not linked in to the iOS app  so when packaged into a .ipa file the library is still not linked in and Apple rejects the app because of a the library being dynamic linked and its not a framework. 

When building and packing the reproduction project (libmds.a is in Git LFS) the file libmds.a is added to the StaticLinkingNotWorking.1.0.0.nupkg under lib -> net7.0-ios16.1 -> StaticLinkingNotWorking.resources -> libmds.a 

What I expected was for it to be linked into the lib ->  net7.0-ios16.1 -> StaticLinkingNotWorking.dll file as it was when using the Xamarin binding project. 

But whatever I do to try to statically link libmds.a it seems like the project insists on making it dynamically linked and add libmds.a as it was before.  

I hope this repository is the correct place to report this issue, if not please point me to the correct place. 

I can consume the package and get a running application locally on a iOS device but this issue causes uploads to AppStore to fail. The exact fail is this one: 

`Asset validation failed (90171) Invalid bundle structure. The “testApp.app/libmds.a” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle `

(I changed the name of the app to testApp)

### Steps to Reproduce

1. Create a iOS binding project
2. Add native static library (.a) file
3. Build the project
4. pack the project

Expected: 
libmds.a statically linked into the StaticLinkingNotWorking.dll file 

Actual
libmds.a added to the StaticLinkingNotWorking.resources folder and not linked in to the dll file.

### Link to public reproduction project repository

https://github.com/tentom/staticLinkingNotWorking

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No known workarounds found.

**Comment by drasticactions** [comment]
This should be transferred to http://github.com/xamarin/xamarin-macios, this isn't related to the MAUI UI project.

**Comment by rolfbjarne** [comment]
> When building and packing the reproduction project (libmds.a is in Git LFS) the file libmds.a is added to the StaticLinkingNotWorking.1.0.0.nupkg under lib -> net7.0-ios16.1 -> StaticLinkingNotWorking.resources -> libmds.a
>
> What I expected was for it to be linked into the lib -> net7.0-ios16.1 -> StaticLinkingNotWorking.dll file as it was when using the Xamarin binding project.

This is the expected behavior, we're not putting native libraries inside the managed dll anymore.

Note that native libraries were never _linked into_ into the managed dll, they were embedded as a resource. This had numerous problems (among other things it got quite slow as native libraries got bigger), so we implemented a way to keep them as separate files in a directory next to the managed dll. They should be automatically picked up correctly - if that's not happening, please include a complete test solution that includes the executable (app) project as well, consuming the binding project/nupkg + [a binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs).

**Comment by tentom** [comment]
@rolfbjarne  
Hi, Im not consuming this package directly in a app project, but it goes into a another package that has one android binding (as a NuGet Package) and a iOS binding (as a NuGet Package) as dependencies. This project is in turn made into a NuGet Package and consumed in an MAUI app project. I assume that the .a file should continue to exist in this use case and be removed when consumed in the final executable (app) project in the release configuration,  is this correct? 

I'm not quite sure I understand what you mean by `They should be automatically picked up correctly`.  When I consume the library in my cross platform project and then consume the cross platform package in a MAUI application I can call the native code and everything works as expected and the libmds.a file is still in the generated IPA package. The issue first arises when uploading to the Apple AppStore. So it seems like it is picked up correctly but the final stage there is something missing before the upload to Apple.

1. Should it work like visioned in the first paragraph?
2. Do I have the right understanding of what `They should be automatically picked up correctly` mean? 
3. I will  update the test project with api definitions and consume it in a maui app project and see if the generated IPA file still contains the libmds.a file.

**Comment by rmarinho** [comment]
This issue was moved to xamarin/xamarin-macios#18751
