### ISSUE TITLE
Auto read OTP in Android using the Google SMS Verification API

### ISSUE THREAD

**Issue by shery-sharaf** [dotnet/maui#16773]
### Discussed in https://github.com/dotnet/maui/discussions/16772

<div type='discussions-op-text'>

<sup>Originally posted by **shery-sharaf** August 16, 2023</sup>
Since READ_SMS and RECEIVE_SMS permissions are not so much easier to get published on the play store, how can i implement auto read OTP in android using the Google SMS verification API in .net MAUI. I came over this [Request SMS Verification in an Android App](https://developers.google.com/identity/sms-retriever/request). For implementing this how can i add the required dependencies of 'com.google.android.gms:play-services-auth:20.6.0' and 'com.google.android.gms:play-services-auth-api-phone:18.0.1' in .net MAUI ?</div>

**Comment by drasticactions** [comment]
You already have a discussion topic on this, which IMO is more appropriate for your question. This isn't an issue with the MAUI UI platform.
