### ISSUE TITLE
[regression/8.0.0-preview.1.7762] [WinUI] CollectionView runtime binding errors when loading the ItemSource asynchronously

### ISSUE THREAD

**Issue by nicop85** [dotnet/maui#16787]
### Description

I was testing the last updates available for the Net 8 preview 6 (using Visual Studio 17.7), to see if everything continues to works as expected.

What I have found is that if you have a CollectionView that uses data binding inside it's DataTemplate, WinUI will report some binding problems if you load the ItemSource asynchronously like when you go to some API to get the data and then fill the ItemSource list with that data.

If you load the ItemsSource without waiting for an asynchronous response, everything work as expected.

**App after showing the list:**
![image](https://github.com/dotnet/maui/assets/2288412/45091ee9-373f-4af4-8d52-52ed32eaec07)

**Binding errors:**
![image](https://github.com/dotnet/maui/assets/2288412/c6fd2c1a-099e-42e3-820a-2d907767503b)

### Steps to Reproduce

1. Download the project linked below
2. Run it targeting Windows

### Link to public reproduction project repository

https://github.com/nicop85/CollectionViewBindingProblems.git

### Version with bug

[8.0.0-preview.1.7762](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.1.7762)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.17763.0

### Did you find any workaround?

No

**Comment by samhouts** [comment]
Could be the same as https://github.com/dotnet/maui/issues/11956 or https://github.com/dotnet/maui/issues/8433

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11 .NET 8 with below Project:
[CollectionViewBindingProblems.zip](https://github.com/dotnet/maui/files/12426816/CollectionViewBindingProblems.zip)

![image](https://github.com/dotnet/maui/assets/97647558/3df452f2-11f0-499d-bd5a-a13f86b1b5da)

**Comment by TiberiusDRAIG** [comment]
Just adding my name to this as it completely blocks our upgrade to .NET 8 - we are effectively stuck on our landing page because none of the controls generated by CollectionView have any context, ergo are completely non-functional. This basically blocks any real testing of .NET 8 since we cannot progress past this point without rewriting code. 

This is a major issue for us with the timescales involved - the more time we lose to things like this, the less time we have to properly test our end-of-year release.

**Comment by samhouts** [comment]
Confirmed that this regressed between [7.0.92...8.0.0-preview.1.7762](https://github.com/dotnet/maui/compare/7.0.92...8.0.0-preview.1.7762). Still reproducible on nightly. Some of the errors seem inconsequential and the binding is resolved, while others appear to not work at all.

https://github.com/dotnet/maui/pull/10999 seems sus.

**Comment by jeremy-visionaid** [comment]
@samhouts Good catch, thanks! I can at least confirm that reverting #10999 resolves #17192

**Comment by jeremy-visionaid** [comment]
I hope we're going to see a pretty quick turn around on a new RC given how serious this one is - pretty much a blocker for using MAUI on Windows. At least I can continue with a local build, but I assume someone else might want to come up with a better fix than just reverting #10999? @espenrl @PureWeen @hartez
