### ISSUE TITLE
Cannot Build MAUI Blazor Android App when Referencing a Blazor WebAssembly Project

### ISSUE THREAD

**Issue by Jerry239** [dotnet/maui#16782]
### Description

Can't build an Android app from a ".NET MAUI Blazor App" template that is referencing a "Blazor WebAssembly App". the MAUI app is using the "Client" from the WebAssembly app. This approach works fine with Windows and iOS builds but fails for Android. I reproduced this behavior with .NET 7 und .NET 8-Preview

In the output I can see a missing file:
Manifest file at 'obj\Debug\net7.0\browser-wasm\staticwebassets.build.json' not found.

### Steps to Reproduce

- Create a "Blazor WebAssembly App" projekt. run it and it will start up a webserver and open a webbrowser and load the WASM App.
- Create a ".NET MAUI Blazor App" in the same solution. Remove the wwwroot folder, Pages, Shared, and Data folders.
- Add a project reference to the "Client" and "Shared" projects of the "Blazor WebAssembly App"
- Fix up some dependency version issues and add a HttpClient scoped service to the MAUI app. Remove the existing WeatherService.
- In "Main.razor", add the assembly from the "Blazor WebAssembly App" to the AdditionalAssemblies list
- Compile/Run for Android (tested with Android 13.0 Simulator - API 33)

-> Compilation will fail with missing obj\Debug\net7.0\browser-wasm\staticwebassets.build.json file

### Link to public reproduction project repository

https://github.com/Jerry239/MauiBlazorWASM-Bug

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No workaround found

### Relevant log output

```shell
Build started...
Starting emulator tablet_420-dpi_8in_-_api_33_1 ...
C:\Program Files (x86)\Android\android-sdk\emulator\emulator.EXE -netfast -avd tablet_420-dpi_8in_-_api_33_1 -prop monodroid.avdname=tablet_420-dpi_8in_-_api_33_1
1>------ Build started: Project: MauiBlazor, Configuration: Debug Any CPU ------
1>Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
1>Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
1>Compressing Blazor WebAssembly publish artifacts. This may take a while...
1>C:\Program Files\dotnet\sdk-manifests\7.0.100\microsoft.net.workload.mono.toolchain.net7\WorkloadManifest.targets(95,9): warning MSB4011: "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.MonoTargets.Sdk\7.0.10\Sdk\Sdk.props" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk-manifests\7.0.100\microsoft.net.workload.mono.toolchain.net7\WorkloadManifest.targets (48,9)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\Temp\BlazorWASM\BlazorWASM\Client\BlazorWASM.Client.csproj]
1>C:\Program Files\dotnet\sdk-manifests\7.0.100\microsoft.net.workload.mono.toolchain.net7\WorkloadManifest.targets(99,9): warning MSB4011: "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.MonoTargets.Sdk\7.0.10\Sdk\Sdk.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk-manifests\7.0.100\microsoft.net.workload.mono.toolchain.net7\WorkloadManifest.targets (49,9)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\Temp\BlazorWASM\BlazorWASM\Client\BlazorWASM.Client.csproj]
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>MauiBlazor -> D:\Temp\BlazorWASM\MauiBlazor\bin\Debug\net7.0-android\MauiBlazor.dll
1>C:\Program Files\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,7): error : Manifest file at 'obj\Debug\net7.0\browser-wasm\staticwebassets.build.json' not found.
1>Done building project "BlazorWASM.Client.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(467,5): error : IOException: The process cannot access the file 'D:\Temp\BlazorWASM\MauiBlazor\obj\Debug\net7.0-android\staticwebassets.publish.json' because it is being used by another process.
1>C:\Program Files\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(467,5): error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Program Files\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(467,5): error :    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Program Files\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(467,5): error :    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Program Files\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(467,5): error :    at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
1>C:\Program Files\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(467,5): error :    at Microsoft.AspNetCore.Razor.Tasks.GenerateStaticWebAssetsManifest.PersistManifest(StaticWebAssetsManifest manifest)
1>C:\Program Files\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(467,5): error :    at Microsoft.AspNetCore.Razor.Tasks.GenerateStaticWebAssetsManifest.Execute()
1>C:\Program Files\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(467,5): error :
1>Done building project "MauiBlazor.csproj" -- FAILED.
1>Done building project "MauiBlazor.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
========== Build started at 19:51 and took 15,759 seconds ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Deploy started at 19:51 and took 15,760 seconds ==========
Emulator tablet_420-dpi_8in_-_api_33_1 is running.
Waiting for emulator to be ready...
```

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0 using below Project (.NET 8.0), Compilation will fail with missing obj\Debug\net7.0\staticwebassets.build.json  file
[MauiBlazorWASM-Bug-main.zip](https://github.com/dotnet/maui/files/12426279/MauiBlazorWASM-Bug-main.zip)
![image](https://github.com/dotnet/maui/assets/131441429/2394c204-0816-45a4-aa75-99754f72c0a7)

**Comment by Eilon** [comment]
Hi @Jerry239 , the recommended approach for sharing Razor/Blazor content between multiple apps is to place the shared content into a Razor Class Library (RCL) project. You can then reference that shared RCL from each Blazor-based application (Blazor WASM, Blazor Server, .NET MAUI Blazor Hybrid, etc.).

Having one app project (MAUI Blazor Hybrid) reference another app project (Blazor WASM) can cause many problems, including accidentally sharing content that isn't meant to be shared (such as the index.html from the WASM project), or creating other conflicts between the two incompatible app types.

You can find more guidance on this documentation page: https://learn.microsoft.com/aspnet/core/blazor/hybrid/class-libraries
