### ISSUE TITLE
MAUI templates are missing in VS 2022, Preview 2.0 as well.

### ISSUE THREAD

**Issue by DuaRobin** [dotnet/maui#1679]
MAUI templates are missing in "VS 2022, Version 17.0.0 Preview 2.0" as well.

**Comment by Mrsevic** [comment]
As well as in the new Preview 3.0.

**Comment by azthrunzalao0o** [comment]
Templates are available in VS2022 on one computer but not the other. 
Both PCs have VS 2022 preview 3.1; Both have the latest maui-check; and Both have all green when running maui-check.
The only difference I would say is that one with templates available is running on the latest version of Win10, while the other one which does not have templates available is on Win11.

**Comment by DuaRobin** [comment]
> Templates are available in VS2022 on one computer but not the other.
> Both PCs have VS 2022 preview 3.1; Both have the latest maui-check; and Both have all green when running maui-check.
> The only difference I would say is that one with templates available is running on the latest version of Win10, while the other one which does not have templates available is on Win11.

What do you see for this on your machine? 

C:\>dotnet workload list

Workload Id
-----------
android
android-aot
ios
maccatalyst
macos
maui
tvos
wasm-tools

If you don't see below workloads, could you then delete everything in 'C:\Program Files\dotnet\metadata\workloads', and run maui-check again, re-validate workloads? if something is still missing, install it manually. let say 'dotnet workload install android'. After this try VS 2022, version 3.1. Let everyone know if this solves it.

**Comment by azthrunzalao0o** [comment]
> > Templates are available in VS2022 on one computer but not the other.
> > Both PCs have VS 2022 preview 3.1; Both have the latest maui-check; and Both have all green when running maui-check.
> > The only difference I would say is that one with templates available is running on the latest version of Win10, while the other one which does not have templates available is on Win11.
> 
> What do you see for this on your machine?
> 
> C:>dotnet workload list
> 
> ## Workload Id
> android
> android-aot
> ios
> maccatalyst
> macos
> maui
> tvos
> wasm-tools
> 
> If you don't see above workloads, could you then delete everything in 'C:\Program Files\dotnet\metadata\workloads', and run maui-check again, re-validate workloads? if something is still missing, install it manually. let say 'dotnet workload install android'. After this try VS 2022, version 3.1. Let everyone know if this solves it.

I have tried these steps so that my workload list looks exactly the same as yours, but VS2022 still doesn't show the templates.
Also I want to mention that in my Win10 PC which has no issue with templates in VS, the only workload listed is "maui", nothing else.

**Comment by jfversluis** [comment]
This should be fixed in newer previews. If not, you can manually install/update the templates by running `dotnet new -i Microsoft.Maui.Templates` from a command-line
