### ISSUE TITLE
Update Blazor Hybrid template to match new Blazor Web App conventions

### ISSUE THREAD

**Issue by danroth27** [dotnet/maui#16797]
We've made a number of [changes to the content in the new Blazor Web App template](https://github.com/dotnet/aspnetcore/pull/49801) to clean things up:

- New Components folder
- Cleaned up names and content for the Home, Counter, and Weather pages
- New Include sample pages option

 We should update the .NET MAUI Blazor Hybrid template to match these changes.

@SteveSandersonMS @eilon @BethMassi

**Comment by Eilon** [comment]
Fixed by #17946
