### ISSUE TITLE
App Crash on starting - iOS Binding library - DYLD: Symbol not found

### ISSUE THREAD

**Issue by kapilntt** [dotnet/maui#16811]
### Description

I'm migrating an app from Xamarin.Form to .NET MAUI.  The Xamarin Forms app successfully uses a native iOS library (xcframework) with the help of bindings project.

With .net 7,
* The binding project compiles successfully
* The Maui iOS App compiles successfully

However upon launching the app on iPhone or in simulator, the app throws following error and Visual Studio shows the crash screen.
`xcrun simctl launch --stdout=/dev/ttys001 --stderr=/dev/ttys002 --terminate-running-process 6FB7B74B-4AE5-43C4-A1F4-67BA87255B9B com.companyname.appname.iOS2 -monodevelop-port 10000
com.companyname.appname.iOS2: 7307
dyld[7307]: Symbol not found: _$s21MobileAccess0B10CredentialP10sessionUrl10Foundation3URLVvgTj
Referenced from: <E9568E49-115C-3F9A-99A4-23446C80E534> /Library/Developer/CoreSimulator/Devices/6FB7B74B-4AE5-43C4-A1F4-67BA87255B9B/data/Containers/Bundle/Application/9BFB0F68-20E4-4176-BC7B-60DA6752F4FB/appname.iOS2.app/Frameworks/SdkProxy.framework/SdkProxy`

A similar issue was reported in the following ticket but it has been put into backlog with no timeframe for fixing.
 https://github.com/dotnet/maui/issues/13464 

### Steps to Reproduce

1. Create iOS binding library in Visual Studio for Mac 17.6.3 (build 421)
2. Add native references to xcframework files. Make sure Smark Link is ticked.
3. Add ApiDefinition and StructsAndEnums from old Xamarin project. 
4. Observe successful compilation
5. Go to the iOS app project and refer the binding DLL
6. Observe successful compilation
7. Run the app
8. Observe the crash

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

no

**Comment by rmarinho** [comment]
This issue was moved to xamarin/xamarin-macios#18761
