### ISSUE TITLE
[regression/8.0.0-preview.6.8686] Grid with padding column misalignment

### ISSUE THREAD

**Issue by JordiCasas** [dotnet/maui#16815]
### Description

When a grid has left/right padding set and column definition is set to *,Auto, if the content of the * column is close to the end of the column, the column set to 'Auto' is misaligned to the left. If the grid is set with no left/right paddings, alignments stay correct. See the attached video which shows the issue.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp3.MainPage">

    <ScrollView>
        <VerticalStackLayout >
            <!-- Notice the left and right paddings are set -->
            <Grid Padding="20,0,20,0">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="Auto"/>
                </Grid.ColumnDefinitions>
                <!-- If the text lenght is not long enough, alignment is correct -->
                <Label
                    Grid.Column="0"
                    Text="This text is OK"
                    HorizontalTextAlignment="Start"
                    HorizontalOptions="Start"
                    VerticalTextAlignment="Center"
                    VerticalOptions="Center"
                    FontSize="15"/>
                <Image
                    WidthRequest="40"
                    HeightRequest="40"
                    Source="dotnet_bot.png"
                    BackgroundColor="Olive"
                    Grid.Column="1"
                    HorizontalOptions="End"/>
            </Grid>
            <!-- Notice the left and right paddings are set -->
            <Grid Padding="20,0,20,0"
                BackgroundColor="AliceBlue">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="Auto"/>
                </Grid.ColumnDefinitions>
                <!-- Modify the text length until the point where the alignment of the 'Auto' column is broken. Will depend on the device screen width -->
                <Label
                    BackgroundColor="Violet"
                    Grid.Column="0"
                    Text="Modify the text length until the point "
                    HorizontalTextAlignment="Start"
                    HorizontalOptions="Start"
                    VerticalTextAlignment="Center"
                    VerticalOptions="Center"
                    FontSize="15"/>
                <Image
                    WidthRequest="40"
                    HeightRequest="40"
                    Source="dotnet_bot.png"
                    BackgroundColor="Olive"
                    Grid.Column="1"
                    HorizontalOptions="End"/>
            </Grid>
            <!--The padding of the grid is 0, the issue is not reproducible here-->
            <Grid Padding="0,20,0,20"
                BackgroundColor="AliceBlue">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="Auto"/>
                </Grid.ColumnDefinitions>
                <!-- Modify the text length to see that the alignment of the 'Auto' column stays correct. -->
                <Label
                    BackgroundColor="Violet"
                    Grid.Column="0"
                    Text="Modify the text length to see that the align"
                    HorizontalTextAlignment="Start"
                    HorizontalOptions="Start"
                    VerticalTextAlignment="Center"
                    VerticalOptions="Center"
                    FontSize="15"/>
                <Image
                    WidthRequest="40"
                    HeightRequest="40"
                    Source="dotnet_bot.png"
                    BackgroundColor="Olive"
                    Grid.Column="1"
                    HorizontalOptions="End"/>
            </Grid>
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
```

https://github.com/dotnet/maui/assets/86722749/d892a57b-7182-4d31-a4a9-9c32b60a68c8

### Steps to Reproduce

1. Create a grid with left/right padding and two columns, "*, Auto". Add a label in the '*' column. Fix the size of the element in the 'Auto' column. 
2. Depending on the size of the screen, modify the text so it 'barely' fits in a single row (see attached video).

Expected result: the content in the 'Auto' column is aligned to the 'end'.
Current result: the content in the 'Auto' column is misaligned and slightly moved to the left.

### Link to public reproduction project repository

https://github.com/JordiCasas/GridPaddingIssue

### Version with bug

[8.0.0-preview.6.8686](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.6.8686)

### Is this a regression from previous behavior?

Yes, this used to work in MAUI

### Last version that worked well

[8.0.0-preview.5.8529](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.5.8529)

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by JordiCasas** [comment]
@rmarinho I added steps to reproduce and also improved a bit the original issue description. 

There's already a public repro link: https://github.com/JordiCasas/GridPaddingIssue, why did you add the needs-repro tag? Do you have problems accessing it?

**Comment by rmarinho** [comment]
Yap @JordiCasas  404 on that link

**Comment by JordiCasas** [comment]
@rmarinho Sorry, my bad, thought I made it public, but it was private. Try now please.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11, Android 13.0-API33 and iOS 16.4 .NET 8 with below Project:
[16815.zip](https://github.com/dotnet/maui/files/12436379/16815.zip)

**Comment by danielkraut** [comment]
I think this is the same problem as I have. It is happening on .NET 7 on both Android and iOS. It wasn't happening on Android with VS 17.6.x but when I upgraded few days ago it started happeninig. On iOS  I cannot say what specific version I was using but it happened to me a month ago. Both are on .NET 7.0.

**Comment by samhouts** [comment]
Confirmed that this regressed between [8.0.0-preview.5.8529](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.5.8529) and [8.0.0-preview.6.8686](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.6.8686).

https://github.com/dotnet/maui/compare/8.0.0-preview.5.8606...8.0.0-preview.6.8686

https://github.com/dotnet/maui/pull/15532 seems sus. If so, this change was backported to [7.0.92 Service Release 7](https://github.com/dotnet/maui/releases/tag/7.0.92), so it would have been a regression from [7.0.86 Service Release 6](https://github.com/dotnet/maui/releases/tag/7.0.86), too.

**Comment by mattleibow** [comment]
Simpler repro:


```xml
<Grid Padding="20,0,20,0" ColumnDefinitions="*,Auto">

    <BoxView
        Color="Violet"
        WidthRequest="250"
        HeightRequest="20" />

    <BoxView
        Grid.Column="1"
        WidthRequest="40"
        HeightRequest="40"
        Color="Olive" />

</Grid>
```

**Comment by mattleibow** [comment]
I managed to create a test case for this:

```cs
[Theory, Category(GridStarSizing)]
[InlineData(172, 92, 112)] // pass
[InlineData(171, 91, 111)] // pass
[InlineData(170, 90, 110)] // fail
[InlineData(169, 89, 109)] // fail
public void StarColumnCalculatesCorrectlyWithPadding(double gridWidth, double v0W, double v1X)
{
	var grid = CreateGridLayout(rows: "*", columns: "*, Auto");
	grid.Padding.Returns(new Thickness(20, 0, 20, 0));

	var view0 = CreateTestView(new Size(50, 40));
	var view1 = CreateTestView(new Size(40, 40));

	SubstituteChildren(grid, view0, view1);
	SetLocation(grid, view0, col: 0);
	SetLocation(grid, view1, col: 1);

	_ = MeasureAndArrangeFixed(grid, widthConstraint: gridWidth, heightConstraint: 40);

	AssertArranged(view0, new Rect(20, 0, v0W, 40));
	AssertArranged(view1, new Rect(v1X, 0, 40, 40));
}
```
