### ISSUE TITLE
void VisualElement.Arrange(Rect bounds) doesn't arrange.

### ISSUE THREAD

**Issue by DanTravison** [dotnet/maui#16823]
### Description

I have two Layout/LayoutManager classes (Panel and Toolbar). I wrote Panel a few months ago and works and Toolbar that I just implemented.  With Toolbar, I don't see any of the child controls presented in the UI.

I spent yesterday debugging Toolbar, hand calculating Measure and Arrange metrics with different variations and orientations, examining the actual child properties in an effort to determine what I was missing.  Last night I decided to debug into Maui for Panel to see what was occurring the repeating the same steps with Toolbar and found the difference, Toolbar was using a dictionary to save layout information and the associated VisualElement while Panel was caching layout information and the associated IView.

VisualElement has two implementations of Arrange:  void Arrange(Rect) and Size IView.Arrange(Rect).   Panel was calling the IView.Arrange while Toolbar was calling VisualElement.Arrange.

Calling the first has the following call chain...
VisualElement.Arrange -> Layout(bounds) -> Bounds=bounds -> Frame = value -> UpdateComponents

It sets Frame,X,Y.Width/Height and raises the SizeAllocated event but nothing else. Examining the VisualElemnt in the debugger shows the expected property changes, shows the control in the Visual but no platform code is invoked and is present in the Live Visual Tree but it is not present in the rendered UI.

Calling Arrange(Rect) through the interface does what is expected...

IView.Arrange -> VisualElement.ArrangeOverride
    Frame = this.ComputeFrame(bounds);
    Handler?.PlatformArrange(Frame);
    return Frame.Size;

Why does VisualElement.Arrange even exist?  It doesn't invoke the expected platform code and IView.Arrange doesn't invoke it indirectly.  At best, this is confusing and error prone. At worse, this is a bug.

I have not begun to test Toolbar other platforms since it's not working on Windows so I don't know if the behavior varies by platform.

### Steps to Reproduce

Update an existing LayoutManager implementation and call void VisualElement.Arrange instead of IView.Arrange

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

Ensure IView.Arrange is called explictly.

**Comment by PureWeen** [comment]
This might help as well
https://github.com/dotnet/maui/blob/main/docs/design/layout.md

**Comment by DanTravison** [comment]
Thanks for the link @PureWeen.

Here's a repro showing the exact issue.  I would expect VisualElement.Arrange and ((IView)VisualElement).Arrange to have the same side-effects but they don't and it's not clear why.

https://github.com/DanTravison/MauiArrangeIssue

**Comment by hartez** [comment]
`IView.Arrange()` is the correct method to use/implement for any custom layouts you're writing specifically for MAUI. 

The other version of `Arrange()` in VisualElement exists for backward compatibility reasons with Xamarin.Forms. When the renderer->handler wrappers are used to make controls written for Forms work on MAUI, that method gets called. 

The naming is confusing and unfortunate (along with `IView.Measure()` vs `Measure()` and a couple other things in the API), and if we had it to do over again we would've made different decisions. 20/20 hindsight, and all.

**Comment by DanTravison** [comment]
Thanks.
