### ISSUE TITLE
[Spec]  Font.AutoScalingEnabled and make scaling reactive

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1683]
# Provide the ability to disable auto scaling font.

This will add a boolean property to the Font struct so that when calculating the size of the font and setting it on native elements the user can disable/enable accessibility scaling. By default accessibility scaling will be enabled.

Currently on Android/iOS if you auto scale while the app is running the font sizes don't change. Ideally the size of the fonts would increase/decrease as you are changing them in the accessibility properties.

# API

### Properties

| API | Description |
| ------------- | ------------- |
| AutoScalingEnabled | By default this value will be true. If the user sets this to false then for each platform we'll figure out how to translate the specified font size to an exact measurement effectively disabling whatever the user has specified for font scaling on the device  |

## XAML Example
```xaml
<Image Background="Green">
    <Image.Source>
        <FontImageSource
        FontAutoScalingEnabled="True"
        FontFamily = "Ionicons" 
        Glyph = "&#xf30c;">
        </FontImageSource>
    </Image.Source>
</Image>

<Label Text="EnableScaling disabled" FontAutoScalingEnabled="False"></Label>
```

# Backward Compatibility

This is a breaking change on iOS because now all of the numbered fonts on iOS will scale. If users want to disable this behavior they can implement their own `IFontManager` that inherits from ours and then then explicitly implement GetFont to influence the font that's returned. 

# Difficulty : medium

**Comment by Redth** [comment]
My thoughts around this implementing it outside of a supported api were to use the Accessibility system notifications on each platform and basically apply a % multiplier against the actual specified font size based on the accessibility setting.  Android basically does this already for free, but iOS does not, and not sure about other platforms.

**Comment by Redth** [comment]
A good read on the subject: https://stablekernel.com/article/supporting-accessibility-larger-text-in-ios/

Android currently does this already for us.

iOS you need to use named sizes, or handle it yourself.  What we should do is listen for the Trait Collection changed event on the UIViewController and check the UIApplication.SharedApplication.PreferredContentSizeCategory which gives the slider size setting from the system accessibility / font size settings and then we can apply the change from there.  We'll need to come up with a good magic number for each content size to use for scaling the fonts.

We have a decent spot in the font manager to actually apply the font size manipulation at:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/271950/125989142-6b3faa63-56ed-434c-9e44-9156a5677c8f.png)

Need to validate how Windows handles this as well.

**Comment by mattleibow** [comment]
_can_ we disable auto sizing on all the platforms?

**Comment by mattleibow** [comment]
We probably want to use a negative with a default of false for the property name because Font is a struct, and we want `default(Font)` to be a scalable thing. This is because we can totally do a `default(Font).WithFontFamily("font")` and we want that to be the best Font that it could ever be.

With regards to scaling on Android, we can use the native `dp` for density scaled, but not accessibility scaled. The `sp` can be used to scale with density AND accessibility.

iOS uses the interesting `UIFontMetrics` and a few special properties on views.

Windows has a `IsTextScaleFactorEnabled` property on most views.
