### ISSUE TITLE
How to remove the radius at the edges in Shell Flyout in MAUI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#16832]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/How-to-remove-the-radius-at-the-edges-in/10439002)._

---
When creating Flyout, some value is set to CornerRadius by default, but there is no way to change it through Shell property. From here I have a few questions:
1. How can I set СornerRadius=0?
2. Can I set the restriction of CornerRadius=0 only for Windows 10?

---
#### Feedback Bot on 8/13/2023, 06:53 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
This might also help
https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout
