### ISSUE TITLE
SwipeView open/close methods don't work as expected

### ISSUE THREAD

**Issue by pitMobile** [dotnet/maui#16858]
### Description

We want to use the SwipeView in both ways: the swipe gesture and triggered programmatically with the open/close methods. The gesture works but the methods don't. We checked out the Maui source repo (7.0.100) and tested your sample in the Maui.Controls.Sample project. Under SwipeView exists an Open/Close SwipeView Gallery sample which does not work (tested in iOS and Windows, in Windows the SwipeItemView shows nothing even with the gesture).
In Windows seams to be an other problem with SwipeViews in CollectionViews, here the template renders not correctly (we see nothing), you can try this out in your samples to (i.e. CollectionView using VisualStates Gallery).

### Link to public reproduction project repository

https://github.com/dotnet/maui.git

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows, I was *not* able test on other platforms

### Affected platform versions

iOS 16.4

**Comment by rmarinho** [comment]
@jsuarezruiz  this should be fixed right?
