### ISSUE TITLE
Grid rows not sizing properly on Windows

### ISSUE THREAD

**Issue by john-hollander** [dotnet/maui#16857]
### Description

The vertical sizing of rows in a Grid is not sizing properly, this occurs especially when the Grid is within another Grid (though it has been observed in limited sizes with just one Grid, it's much easier to reproduce when nested). At certain sizes, the auto-sized rows have the correct, and at others they have the incorrect size.

For example, the following has the correct sizing:
![correct](https://github.com/dotnet/maui/assets/11653688/7d9a43ae-08a1-4924-875d-585bc7c2748f)

And the following size gives incorrect sizing:
![incorrect](https://github.com/dotnet/maui/assets/11653688/b5152cfb-be9e-4b07-b2f7-6f854e754a72)

### Steps to Reproduce

1. Create a new .NET MAUI Project
2. Delete code from MainPage.xaml.cs (remove OnCounterClicked method).
3. Paste the following into the MainPage.xaml (replacing the ScrollView code entirely):

 ```
   <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="1*"/>
            <RowDefinition Height="100*"/>
        </Grid.RowDefinitions>

        <Grid Grid.Row="1">
            <Grid.RowDefinitions>
                <RowDefinition Height="5*"/>
                <RowDefinition Height="1*"/>
                <RowDefinition Height="14*"/>
                <RowDefinition Height="1*"/>
                <RowDefinition Height="5*"/>
            </Grid.RowDefinitions>

            <Rectangle Grid.Row="0" Grid.RowSpan="1" Background="Red" />
            <Rectangle Grid.Row="1" Grid.RowSpan="1" Background="Blue" />
            <Rectangle Grid.Row="3" Grid.RowSpan="1" Background="Blue" />
        </Grid>
    </Grid>
```

4. Run the project, and resize the vertical size to see the improper sizes.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 12.0, Windows 11

### Did you find any workaround?

No, though it works better without nesting.

**Comment by john-hollander** [comment]
As a note, this is reproducible with just the following:

 ```
   <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="5*"/>
            <RowDefinition Height="1*"/>
            <RowDefinition Height="13*"/>
            <RowDefinition Height="1*"/>
            <RowDefinition Height="5*"/>
        </Grid.RowDefinitions>

        <Rectangle Grid.Row="0" Background="Red" />
        <Rectangle Grid.Row="1" Background="Blue" />
        <Rectangle Grid.Row="3" Background="Blue" />
    </Grid>
```

But it occurs a bit less often this way.

Also reproducible on Windows 10.

**Comment by john-hollander** [comment]
After testing the code of the GridLayoutManager, it is apparent that the issue occurs when in the ExpandStars(double, double, Definition[], double, double) method the `if (maxCurrentStarSize <= targetStarSize)` line isn't fulfilled, so it goes through to the "We don't have enough room for all the star rows/columns to expand to their full size." section, even though we actually do. Usually this is due to a rounding issue, it seems.

**Comment by john-hollander** [comment]
See pull request. The issue can be resolved by adjusting the distribution algo in the "We don't have enough room" section.

**Comment by mattleibow** [comment]
I can repro this 100% on windows with this:

```xaml
<Grid>

    <Grid RowDefinitions="5*,1*,13*,1*,5*"  HeightRequest="172.5">
        <Rectangle Grid.Row="0" Background="Red" />
        <Rectangle Grid.Row="1" Background="Green" />
        <Rectangle Grid.Row="3" Background="Blue" />
    </Grid>

</Grid>
```

However, I am not able to get the test to hit it:

```cs
[Fact]
[Category(GridStarSizing)]
public void GridRowsDistributeCorrectly()
{
	var height = 172.39999389648438; // this is the value that reaches the layout
	var totalStars = 5 + 1 + 13 + 1 + 5;
	var oneHeight = height / totalStars;

	var grid = CreateGridLayout(rows: "5*,1*,13*,1*,5*");
	grid.DesiredSize.Returns(new Size(100, height));
	grid.Width.Returns(100);
	grid.Height.Returns(height);

	var view0 = CreateTestView(new Size(10, 10));
	var view1 = CreateTestView(new Size(10, 10));
	var view2 = CreateTestView(new Size(10, 10));

	SetLocation(grid, view0, row: 0);
	SetLocation(grid, view1, row: 1);
	SetLocation(grid, view2, row: 3);
	SubstituteChildren(grid, view0, view1, view2);

	_ = MeasureAndArrange(grid);

	AssertArranged(view0, new Rect(0, 0, 100, 5 * oneHeight));
	AssertArranged(view1, new Rect(0, 0, 100, 1 * oneHeight));
	AssertArranged(view2, new Rect(0, 0, 100, 1 * oneHeight));
}
```

**Comment by mattleibow** [comment]
I am using Windows 11 with a scale of 250% and a resolution 3840x2160.

I am probably sure that it has to do with my display and how it all gets rounded down... I wonder if your remove the height on the grid and wiggle screen around. I observed it when the window got very small.

SO it would be interesting to see your display characteristics and the sizes that trigger it.

**Comment by john-hollander** [comment]
Ok, I'll test that when I get a chance (in around 3 hours). Thanks for the details.

**Comment by mattleibow** [comment]
Actually, maybe I was not clear... This issue is fixed. I was not able to write a test for the PR. Not sure if you were able to get numbers to write a test that failed before your fix? Let me re-close this and open a new issue to avoid confusion.

**Comment by john-hollander** [comment]
Ok. I'll take a look at getting the test to work (i.e. fail with the old code) as soon as I get a chance.
