### ISSUE TITLE
Blazor Desktop WPF/Windows: Lower the minimum net6.0-windows TFM to the minimum required version

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#1685]
The TFM for the WPF/Windows packages seems to be too high - higher than the real minimum.

The TFM should be set to the MAX of:
- The WebView2's min TFM
- WinForms/WPF's min TFM

Blazor itself is "pure" net6.0 so that shouldn't be a problem.

**Comment by realivanjx** [comment]
When will the nuget package of webview wpf be updated with this fix? Thanks.

**Comment by Eilon** [comment]
This will be available in .NET 6 Preview 7, which is coming out very soon. I don't have an exact date.
