### ISSUE TITLE
[regression/8.0.0-preview.7.8842] Bug: Android & iOS - Binding inside of DataTemplate not working if swipeView is present

### ISSUE THREAD

**Issue by SamuelJames101** [dotnet/maui#16855]
### Description

BindingContext is not passed from grand parent to grand children if swipe view is in between.

Example:

Grand Parent (Grid) (Has BindingContext set)
      Parent (SwipeView)
           Grand Child (Grid) (No access to BindingContext)

### Steps to Reproduce

**When testing my repo remove line 19 from myTemplate to see the issue**
**This issue may also exist beyond this CollectionView example**

1. I have created a CollectionView and have setup a binding for it's itemSource to an ObservableCollection<myModel>, located in its ViewModel.
2. The data template is then set to a separate Grid Xaml class.

` <Grid ColumnDefinitions="*" RowDefinitions="*">
        <CollectionView
            Grid.Row="0"
            Grid.Column="0"
            ItemsSource="{Binding ItemSource}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <local:myTemplate/>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </Grid>`

3. Inside of 'myTemplate' create a swipe view.
4. Add items inside of the swipe view such as labels or grids etc.

`<VerticalStackLayout BackgroundColor="White">
        <SwipeView>
            <SwipeView.LeftItems>
                <SwipeItems>
                    <SwipeItem
                        Text="hello"
                        BackgroundColor="LightPink" />
                </SwipeItems>
            </SwipeView.LeftItems>
            <Grid 
                BackgroundColor="White"
                RowDefinitions="*,*"
                ColumnDefinitions="Auto,*,Auto"
                Padding="5"
                ColumnSpacing="10"
                RowSpacing="10">`

Expected Result:
You are able to see a list of rows with the correct styling and data for each row.

Actual Result:
You are able to see a list of rows with the correct styling but the data is missing (If using binding)

### Link to public reproduction project repository

https://github.com/SamuelJames101/CollectionViewDataTemplateIssue

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

Manually set the binding context to the children inside of the swipeView pointing to the grand parents bindingcontext.

`
BindingContext="{Binding BindingContext, Source={x:Reference templateMy} }" 
`

**Comment by jsuarezruiz** [comment]
Could be related with https://github.com/dotnet/maui/pull/16632

**Comment by PureWeen** [comment]
This should be resolved by https://github.com/dotnet/maui/pull/16753

If this isn't resolved with the next .NET8 release we can reopen this issue.
