### ISSUE TITLE
After rotating the emulator from horizontal to vertical orientation, the card of page My Recipes is truncated.

### ISSUE THREAD

**Issue by QianaJiao** [dotnet/maui#16850]
### Description

After rotating the emulator from horizontal to vertical orientation, the card of page My Recipes is truncated.

**Note**: This bug is not a regression, it can be reproduced in the latest stable release: 8.0.0-preview.7.8842+sha.1869d0fe2-azdo.8167964 

### Steps to Reproduce

1.Download the project https://github.com/rachelkang/recipeSearch and open it in Visual Studio.
2.Click on the 'My Recipes' tab to navigate to the 'My Recipes' page.
3.Rotate the emulator clockwise (to the right) to the horizontal orientation.
4.Rotate the emulator counterclockwise (to the left) so that it is in the original vertical orientation.

**Result**: 
After rotating the emulator from horizontal to vertical orientation, the card of page My Recipes is truncated.
![rotates page](https://github.com/dotnet/maui/assets/91244512/668485f0-f292-4a62-a7f3-328dda17e493)

### Link to public reproduction project repository
https://github.com/rachelkang/recipeSearch

_No response_

Maui: 8.0.100-preview.7.23376.3
Microsoft.Maui.Controls: 8.0.0-nightly.8982+sha.e0d8ba7da-azdo.8272925

### Version with bug
8.0.0-nightly.8982

### Is this a regression from previous behavior?
This bug is not a regression, it can be reproduced in the latest stable release: 8.0.0-preview.7.8842+sha.1869d0fe2-azdo.8167964 

### Last version that worked well
8.0.0-preview.6

### Affected platforms
Android

### Affected platform versions
Android API34

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 .NET 8 with below Project:
[WhatToEat.zip](https://github.com/dotnet/maui/files/12449919/WhatToEat.zip)

**Comment by PureWeen** [comment]
I tested this against NET7 and I'm seeing the same thing.

![image](https://github.com/dotnet/maui/assets/5375137/58835594-9644-456b-9ca3-fa9c1921159f)

**Comment by rachelkang** [comment]
still an issue on net8 rc2

**Comment by Ying-6** [comment]
Breakfast Sausage puffs page also cutoff.
![1](https://github.com/dotnet/maui/assets/126375062/0c7e816c-1e03-43fb-b5e3-80e8f6106931)

**Comment by kevinxufei** [comment]
Verify in the latest main build 17.10.0 Preview 2.0 [34620.193.main] and Microsoft.Maui.Controls: 8.0.10-nightly.10061+sha.37be10aad8-azdo.9091888, the card truncation issue does not repro.

**Comment by QianaJiao** [comment]
Verify in the latest stable release Microsoft.Maui.Controls: 8.0.7, the card truncation issue does not repro.
