### ISSUE TITLE
Unable to create a maui (v7) app on windows and target iOS

### ISSUE THREAD

**Issue by Andy-Hollis** [dotnet/maui#16915]
### Description

Connect to Mac always fails  - VS for windows attempts to install dotnet framework 7.0.407 on the mac even though it is already installed and fails
I install that SDK version by direct download from dotnet.microsoft.com as VS for mac only installs sdk 7.0.307

On Windows, I can create and run a maui app for android and on the mac i can create a maui app for ios so it just fails when creating an app on windows targeting iOS

Is the path wrong as SDKs are installed into /user/local/share/dotnet/sdk yet VS attempts to install into a user specific cache folder? Just wondering if the Mac path is wrong so it cannot find the existing SDKs hence the attempt to reinstall.

### Steps to Reproduce

Install VS windows 7.7.0
Install latest VS for mac: 17.6.3
Create new Maui project and pick v7 
Press Connect to Mac

Also tried running the install directly on the mac using:
./dotnet-install.sh --install-dir /users/andyhollis1/Library/Caches/Xamarin/XDA/SDKs/dotnet --version 7.0.400-rtm.23369.16

Failed to connect to dotnetcli.azureedge.net port 443 after 4ms: coudln't connect to server

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

iOS

### Affected platform versions

all iOS

### Relevant log output

```shell
Using dotnet install script '/Users/andyhollis1/Library/Caches/Xamarin/XMA/SDKs/dotnet/scripts/dotnet-install.sh'...
--install-dir /Users/andyhollis1/Library/Caches/Xamarin/XMA/SDKs/dotnet --version 7.0.400-rtm.23369.16 --architecture Arm64 --no-path
dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.400-rtm.23369.16/dotnet-sdk-7.0.400-rtm.23369.16-osx-arm64.tar.gz
curl: (7) Failed to connect to dotnetcli.azureedge.net port 443 after 4 ms: Couldn't connect to server
/Users/andyhollis1/Library/Caches/Xamarin/XMA/SDKs/dotnet/scripts/dotnet-install.sh: line 1024: http_code: unbound variable

Could not install dotnet SDK '7.0.400-rtm.23369.16'. Details: 


dotnet info on the mac shows 407 is installed:
dotnet --info
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: arm64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by samhouts** [comment]
@emaf ?

**Comment by Andy-Hollis** [comment]
Thanks for confirming. I have reported the issue through the VS for windows report a problem link and will report back
