### ISSUE TITLE
ImageButton  is not properly anti-aliased when scaled down

### ISSUE THREAD

**Issue by alphac05** [dotnet/maui#16918]
### Description

On **Windows**, `ImageButtons` with a source image that is scaled down are not properly anti-aliased.

![Screenshot](https://github.com/dotnet/maui/assets/104758282/8badfb15-bbab-46cd-9ec2-ceb07fdd29c4)

### Steps to Reproduce

1. Run the attached sample project, derived from the _Hello World_ VS MAUI project, under Windows.

Expected outcome: the `Image` and `ImageButton` (1&2, 3&4) that use the same source image should look the same.
Actual outcome: the `ImageButton` (fourth one) looks like no anti-aliasing is performed, while the `Image` (third one) looks much smoother.

Note: the two images sources are SVG files that have a different document size.

[ImageButtonIssue.zip](https://github.com/dotnet/maui/files/12407844/ImageButtonIssue.zip)

### Version with bug

7.0.86

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 11.22621.2134

**Comment by Transis-Felipe** [comment]
Could you please attach an print with this image in Android ?

**Comment by alphac05** [comment]
Thank you. I have trouble with my android development environment, but as soon as I have it running,; I will post the screenshot here.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11 .NET 8, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[ImageButtonIssue.zip](https://github.com/dotnet/maui/files/12461302/ImageButtonIssue.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/9e741172-babd-45d5-b550-f2e46f6587a7)
Android:
![image](https://github.com/dotnet/maui/assets/97647558/b0c045ed-09ae-4b02-8ec3-3712be28ec20)
iOS:
![image](https://github.com/dotnet/maui/assets/97647558/50ac5796-62f2-44ee-8e21-6561695c1f0a)
