### ISSUE TITLE
[iOS]Image downscaling makes image layout inconsistent on IOS when compared to Android and non downscaled images

### ISSUE THREAD

**Issue by skha83** [dotnet/maui#16921]
### Description

When downscaling png images using the HeightRequest property and trying to arrange the image with the HorizontalOptions property the result is inconsistent between iOS and Android. It is also inconsistent compared to how the layout works when images are not downscaled but at their native size. 
The exact same problems is seen if only WidthRequest is specified and VerticalOptions is used to layout the image.

The difference between iOS and Android can be seen on the following images. To emphasize the problem a red background color has been added to both image elements. The 4 different scenarios for HorizontalOptions Start, Center, End and Fill is displayed for each platform in that order. The small button image below show how a non scaled image behave. 

iOS:
![complete_ios_space_small](https://github.com/dotnet/maui/assets/137503619/e526d841-2d3f-4ced-bbca-d051ab164532)

Android:
![complete_android_space_small](https://github.com/dotnet/maui/assets/137503619/480d55f0-f03e-4235-82a4-b858714d7b57)

### Steps to Reproduce

1. Deploy the linked repo to both an iOS and Android phone.
2. Press the four buttons on both phones which will change the HorizontalOptions for both the down-scaled image (Windows logo) and the button imagine in native size with no downscaling applied. 

Expected result:
The image will get resized and positioned in the correct position like it is done on Android and for the non downscaled image on both iOS and Android devices. At least the layout should be consistent between the two platforms.

Actual result:
The base image content gets scaled correctly according to aspect ratio, but there is added a lot of padding to the image element so it becomes very wide while the height is still kept at the requested size. The image's width get set to NaN which cause the image to go out of the screen when the HorizontalOptions is set to either Start or End. 

### Link to public reproduction project repository

https://github.com/skha83/ImageScaling

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.6

### Did you find any workaround?

Only workaround is to always specify both height and width of the image

### Relevant log output

```shell
No response
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on iOS 16.4 .NET 8, not repro on Windows 11 and Android 13.0-API33 with below Project:
[ImageScaling.zip](https://github.com/dotnet/maui/files/12471158/ImageScaling.zip)

**Comment by jknaudt21** [comment]
Same root cause as #16120
