### ISSUE TITLE
Grid RowDefinition height taking precedence over actual Height constraints

### ISSUE THREAD

**Issue by jknaudt21** [dotnet/maui#16935]
### Description

A grid's `Height` or `MaximumHeightRequest` will not work take precedence over the RowDefinitions height.

This can lead to the unintended behavior of creating RowDefinitions that overflow the container and are not clipped out. I suspect this also affects Width requests with Column definitions too.

### Steps to Reproduce

Copy and paste the following code into MainPage.xaml: 
```xaml
    <Grid MaximumHeightRequest="500" MaximumWidthRequest="250" RowDefinitions="500, 500">
        <Button BackgroundColor="AliceBlue" Text="Foo" Grid.Row="0"/>
        <Button BackgroundColor="LightGray" Text="Bar" Grid.Row="1"/>
    </Grid>
```
Observe that the grid overflows its container. I was expecting the second button to be clipped out. This can be particularly nasty when putting a CollectionView inside a row that has "Auto" as its height since the CollectionView will just overflow and grow to the size it wants.
![image](https://github.com/dotnet/maui/assets/32918747/8f955863-3f93-49b4-87ff-4b8fe1efbee1)

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Did you find any workaround?

Use `*` for row and column definitions instead of actual units.

**Comment by mattleibow** [comment]
I see that the default value for `IsClippedToBounds` is false, so I wonder if setting that to true fixes this?

@hartez should/can we change the default on net8 to true?

**Comment by mattleibow** [comment]
I can confirm that setting `IsClippedToBounds ="true"' fixes the issue. 

![image](https://github.com/dotnet/maui/assets/1096616/4d7ab8bf-8997-49a2-949b-f8b2a24502a6)

**Comment by mattleibow** [comment]
I also wrote a test that confirms that the actual grid bounds are correct, just the content is not clipped:

```cs
[Category(GridAbsoluteSizing)]
[Theory]
[InlineData(50, 50)]
[InlineData(100, 100)]
[InlineData(200, 200)]
[InlineData(300, 200)]
public void MaxHeightOverridesRowHeight(double maxHeight, double expectedHeight)
{
	var grid = CreateGridLayout(rows: "100,100");
	var view1 = CreateTestView(new Size(100, 100));
	var view2 = CreateTestView(new Size(100, 100));
	SubstituteChildren(grid, view1, view2);
	SetLocation(grid, view1, row: 0, col: 0);
	SetLocation(grid, view1, row: 1, col: 0);

	grid.MaximumHeight.Returns(maxHeight);

	var layoutManager = new GridLayoutManager(grid);
	var measure = layoutManager.Measure(double.PositiveInfinity, double.PositiveInfinity);

	Assert.Equal(expectedHeight, measure.Height);

	var target = new Rect(Point.Zero, new Size(measure.Width, measure.Height));
	var actual = layoutManager.ArrangeChildren(target);

	Assert.Equal(expectedHeight, actual.Height);
}
```

**Comment by hartez** [comment]
This is expected behavior. If you want the content to be clipped, you need to set `IsClippedToBounds` to true.
