### ISSUE TITLE
Android CollectionView leaks if given a header or footer

### ISSUE THREAD

**Issue by jknaudt21** [dotnet/maui#16961]
### Description

This bug was discovered when modifying the tests for this PR: #16870

Turns out that when you create a CollectionView and give it a header or footer, it begins to leak. 

I was expecting to see 5 logical children, but instead saw that there were 9.

### Steps to Reproduce

1. Add a header and footer to the collection view on the [ItemsSourceDoesNotLeak test](https://github.com/dotnet/maui/blob/312948086267cf6c529dfeb2ec0eeae7e7aa57ae/src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs#L48-L51). If #16870  has already been merged, then delete the preprocessor directives that were added
```
			var collectionView = new CollectionView
			{
				Header = new Label { Text = "Header" },
				Footer = new Label { Text = "Footer" },
				ItemTemplate = new DataTemplate(() => new Label())
			};
```
2. Run the test and observe the failure: the collection view is leaking memory and adding too many logical children

### Link to public reproduction project repository

Maui main

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by rachelkang** [comment]
fyi @jonathanpeppers
