### ISSUE TITLE
Nested CollectionViews aren't rendered correctly in iOS and MacCatalyst

### ISSUE THREAD

**Issue by dmanning23** [dotnet/maui#16966]
### Description

When CollectionViews are nested to build complex controls, the resulting lists are not rendered correctly on iOS and Mac Catalyst. (see screenshots) 
The height of each item appears to expand to fill the maximum height allowed.

The results are as expected on Android.  (see screenshot)

**Expected results:**

### Android:
![Screenshot_1692826959](https://github.com/dotnet/maui/assets/1888089/276a96a0-15bc-42a5-b5e9-87d89d22aabe)

**Actual Results:**

### iOS:
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-23 at 16 43 03](https://github.com/dotnet/maui/assets/1888089/97f53ff1-617d-4169-a10a-b95ce73dc347)

### MacCatalyst:
![Screenshot 2023-08-23 at 4 43 30 PM](https://github.com/dotnet/maui/assets/1888089/ec6f14b3-affe-4169-85d3-f4290a3e3e51)

### Steps to Reproduce

This is a somewhat complicated bug to reproduce, so I've repurposed the CollectionViewDemos from the maui-samples repository to show the bug.

1. Create a model with a list of data
2. Create a viewmodel with a list of the models
3. Create a CollectionView that is databound to the viewmodel's list
4. Add a nested CollectionView that is databound to the model's data

### Link to public reproduction project repository

https://github.com/dmanning23/CollectionViewBugExample

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.4, MacCatalyst

### Did you find any workaround?

I have not found a workaround for this issue.

**Comment by Unflab** [comment]
Could possibly be same issue as #9135.

**Comment by drasticactions** [comment]
> Could possibly be same issue as #9135.

There's a backport for that issue https://github.com/dotnet/maui/pull/15652. It's merged, but not in a shipping product yet. It should be in the newest net8.0 preview right now though. You can try it there and see if it's working there. If it is, then it _should_ work in net7.0 whenever the service release ships.

**Comment by rmarinho** [comment]
Can you try on net8 to see if it works?

**Comment by dmanning23** [comment]
> Can you try on net8 to see if it works?

I've installed Visual Studio Preview and the latest .Net 8 Preview, yet when I try to run the project under .Net8 I run into a bunch of error messages and general Visual Studio weirdness. It should be as simple as going to the project properties -> Target Platforms, and changing the Target .Net Runtime to .Net 8.0?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on iOS 16.4 **.NET 7**, but not repro on iOS **.NET 8**, and not repro on Windows 11 and Android 13.0-API33 with below Project:
[CollectionViewDemos.zip](https://github.com/dotnet/maui/files/12483224/CollectionViewDemos.zip)

![image](https://github.com/dotnet/maui/assets/97647558/cca3320e-0b1c-41bf-a192-219d1438b443)
