### ISSUE TITLE
.NET MAUI does not support Arabic language (RTL) on iOS devices

### ISSUE THREAD

**Issue by WAEL20221** [dotnet/maui#16964]
### Description

.NET MAUI does not support Arabic language (RTL) on iOS devices ,

Images do not appear when the language is Arabic (RTL) when using ScrollView, Frame and border .

target framework .NET 7.0

Visual Studio for Mac 17.6.3(build 421)

Xcode (14.3.1)

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
         
             x:Class="TestRTL.MainPage">

    <ScrollView FlowDirection="RightToLeft" Orientation="Horizontal">
        <HorizontalStackLayout >
            <Frame HorizontalOptions="Start" HeightRequest="100" WidthRequest="100" BackgroundColor="Transparent" Padding="0" HasShadow="False" >
                <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="80"
                WidthRequest="80"
                HorizontalOptions="Start" />

            </Frame>
            
             <Frame HorizontalOptions="Start" HeightRequest="100" WidthRequest="100" BackgroundColor="Transparent" Padding="0" HasShadow="False" >
                <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="80"
                WidthRequest="80"
                HorizontalOptions="Start" />

            </Frame>
             <Frame HorizontalOptions="Start" HeightRequest="100" WidthRequest="100" BackgroundColor="Transparent" Padding="0" HasShadow="False" >
                <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="80"
                WidthRequest="80"
                HorizontalOptions="Start" />

            </Frame>
             <Frame HorizontalOptions="Start" HeightRequest="100" WidthRequest="100" BackgroundColor="Transparent" Padding="0" HasShadow="False" >
                <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="80"
                WidthRequest="80"
                HorizontalOptions="Start" />

            </Frame>
             <Frame HorizontalOptions="Start" HeightRequest="100" WidthRequest="100" BackgroundColor="Transparent" Padding="0" HasShadow="False" >
                <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="80"
                WidthRequest="80"
                HorizontalOptions="Start" />

            </Frame>

        </HorizontalStackLayout>
    </ScrollView>

</ContentPage>
```

![262109553-3c796ea9-5f9c-4f4c-8ede-5813d63b79f9](https://github.com/dotnet/maui/assets/98676107/10978f99-057e-45a1-99e1-9becd1650230)

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Can you please turn your code sample into a full repro project? This will help us quickly debug the issue and make sure we have a shared codebase where we can both see the same issue within the same codebase. Copy and pasting code can lead to cases where it works for everyone else but not you, due to other changes you may have missed.

**Comment by WAEL20221** [comment]
> أهلاً@WAEL20221. لقد أضفنا التصنيف "s/needs-repro" إلى هذه المشكلة، مما يشير إلى أننا نحتاج إلى خطوات ونموذج للتعليمات البرمجية لإعادة إنتاج المشكلة قبل أن نتمكن من اتخاذ المزيد من الإجراءات. يرجى محاولة إنشاء نموذج بسيط للمشروع/الحل أو نماذج التعليمات البرمجية التي تعيد إنتاج المشكلة، ومن الأفضل أن تكون بمثابة مستودع GitHub يمكننا استنساخه. اطلع على مزيد من التفاصيل حول إنشاء النسخ هنا: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> سيتم إغلاق هذه المشكلة تلقائيًا خلال 7 أيام إذا لم نتلق ردًا منك بحلول ذلك الوقت - فلا تتردد في إعادة فتحها إذا عدت إلى هذه المشكلة بعد ذلك الوقت.



This is the project
https://github.com/WAEL20221/RTLiosArab

**Comment by WAEL20221** [comment]
> هل يمكنك تحويل نموذج التعليمات البرمجية الخاصة بك إلى مشروع النسخة الكاملة؟ برنامجنا هذا على تصحيح المشكلة بسرعة والتأكد من أن لدينا قاعدة تعليمات برمجية داخل شركة برمجية حيث يمكننا رؤية نفس المشكلة نفس قاعدة التعليمات البرمجية. يمكن أن تؤدي إلى نسخ التعليمات البرمجية ولصقها إلى الحالات حيث أنها تتواصل مع أي شخص آخر ولكن ليس أنت، وذلك بسبب التغييرات الأخرى التي ربما فاتتك.

This is the project
https://github.com/WAEL20221/RTLiosArab

**Comment by davidortinau** [comment]
I'm not able to repro this on latest .NET 7 or .NET 8 Preview 7. @WAEL20221 would you please try .NET 8?

![Simulator Screenshot - iPhone 14 Pro - 2023-08-30 at 09 53 23](https://github.com/dotnet/maui/assets/41873/aad593b1-6aa6-4abc-82e5-9c295b5a0666)

**Comment by WAEL20221** [comment]
> لا أستطيع إعادة إنشاء هذا على أحدث إصدار من .NET 7 أو .NET 8 Preview 7.@WAEL20221هل من الممكن أن تجرب .NET 8؟
> 
> ![لقطة شاشة للمحاكاة - iPhone 14 Pro - 2023-08-30 الساعة 09 53 23](https://user-images.githubusercontent.com/41873/264383674-aad593b1-6aa6-4abc-82e5-9c295b5a0666.png)

The problem still exists in all versions of .NET MAUI

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.6.9 (build 415). Not repro on iOS platform with sample project. (.net7 &.net8)
https://github.com/WAEL20221/RTLiosArab
![image](https://github.com/dotnet/maui/assets/77434865/5a56df7e-9296-463d-88bb-01da3c080cd0)
