### ISSUE TITLE
Existing TextDecorations applied to a Label are not removed when a new TextDecoration value is set after the Label's Text has been modified

### ISSUE THREAD

**Issue by Unflab** [dotnet/maui#16967]
### Description

Title is a bit of a mouthful, but the steps to reproduce clearly lay it out.

I'm trying to implement logic that strikes through the Text of a Label when a Checkbox is checked. Unchecking the checkbox should remove the strikethrough (by setting TextDecorations.None).

This works fine on Android, and works fine on iOS until _the Label's text changes while a Strikethrough is active_. Unchecking the checkbox after that does not remove the strikethrough.

### Steps to Reproduce

Run linked repo on iOS
1. Tap button to change Label text
2. Check checkbox to apply strikethrough effect
3. Uncheck checkbox to see strikethrough effect disappear and underline effect appear <- this is expected behaviour

Re-run the project
1. Tap button to change Label text
2. Check checkbox to apply strikethrough effect
3. Tap button again to change Label text
4. Uncheck checkbox to see strikethrough effect does NOT disappear and underline effect appear <- expect to see strikethrough disappear at this point.

### Link to public reproduction project repository

https://github.com/Unflab/StrikethroughIssue.git

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

_Edited 22 September: repo has been updated with functioning workaround_

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on iOS 16.4 .NET 8, not repro on Android 13.0-API33 with below Project:
[StrikethroughIssue.zip](https://github.com/dotnet/maui/files/12483312/StrikethroughIssue.zip)

![image](https://github.com/dotnet/maui/assets/97647558/d2103472-6ae2-420d-8047-e4c02539eac3)

**Comment by SyntaxDomain** [comment]
I also just ran into this issue. Has anyone figured out a workaround for it yet?

**Comment by cl3m** [comment]
Thank you @SyntaxDomain for the mapper. Some properties are not handled though so I had some problem with it. Here is a  more robust fix :


```
public partial class StrikethroughLabelHandler : LabelHandler
{
    private static IPropertyMapper<ILabel, ILabelHandler> Mapper()
    {
        var mapper = new PropertyMapper<ILabel, ILabelHandler>(LabelHandler.Mapper);
        mapper.ModifyMapping(nameof(ILabel.Text), (h, v, a) => MapText(h, v));
        return mapper;
    }

    public StrikethroughLabelHandler() : base(Mapper()) { }

    public static void MapText(ILabelHandler handler, ILabel label)
    {
        if (handler.PlatformView != null && label.Text != null)
            handler.PlatformView.AttributedText = new NSMutableAttributedString(label.Text);

        MapFormatting(handler, label);
    }
}
```

**Comment by Unflab** [comment]
Thanks @cl3m. I've applied your workaround to the repo linked in my initial bug report, and it's now behaving as expected.
