### ISSUE TITLE
(App Name).build.appxrecipe" does not exist. You may need to build your project

### ISSUE THREAD

**Issue by AnithaRaniT** [dotnet/maui#16975]
### Description

Unable to run the MAUI winUI app. 

Always giving the error as "DEP1700: The recipe file "C:\Projects\MauiApp2\MauiApp2\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\MauiApp2.build.appxrecipe" does not exist. You may need to build your project.	MauiApp2			
"
**And my launch settings looks like this:**

```
{
	"profiles": {
		"Windows Machine": {
			"commandName": "MsixPackage",
			"nativeDebugging": false
		},
		"Profile 1": {
			"commandName": "Executable",
			"nativeDebugging": true
		}
	}
}
```

**And the .csproj file looks like this :**

```
<PropertyGroup>
		<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net7.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>MauiApp2</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>MauiApp2</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.mauiapp2</ApplicationId>
		<ApplicationIdGuid>3aac4806-6dd2-4fd2-aa7f-8cdc9d9ed172</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>
```

**app.manifest looks like this:**

```
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity version="1.0.0.0" name="MauiApp2.WinUI.app"/>

  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <!-- The combination of below two tags have the following effect:
           1) Per-Monitor for >= Windows 10 Anniversary Update
           2) System < Windows 10 Anniversary Update
      -->
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, PerMonitor</dpiAwareness>
    </windowsSettings>
  </application>
</assembly>
```

**Steps Followed:**
- Clean
- Rebuild
- Removed bin and obj
- Changes "commandName": "MsixPackage", to "commandName": "Package", which gives the different error

I have not done any changes in the MAUI project. Just created new MAUI project and try to run with code changes. 
Still not working. 

### Steps to Reproduce

Create a new MAUI app and run targeting the Windows platform

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

Unable to find some workaround

### Relevant log output

```shell
DEP1700: The recipe file "C:\Projects\MauiApp2\MauiApp2\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\MauiApp2.build.appxrecipe" does not exist. You may need to build your project.
1>Deployment of the application to the target device failed.
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
========== Elapsed 00:00.424 ==========
```

**Comment by AnithaRaniT** [comment]
@Eilon  Here is the code sample. 

Reproducing steps:
-Download the code
-Extract the file
-Select the target platform for windows
-Run the Windows Machine

Output:
DEP1700: The recipe file "C:\Projects\MauiApp2\MauiApp2\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\MauiApp2.build.appxrecipe" does not exist. You may need to build your project.	MauiApp2	
![image](https://github.com/dotnet/maui/assets/45478510/8d7ab822-907f-4612-849f-683721cb6d89)
		


[MauiApp2.zip](https://github.com/dotnet/maui/files/12435790/MauiApp2.zip)

**Comment by AnithaRaniT** [comment]
Could you please provide some work around for this? My work got blocked.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue does not repro on Windows 11 .NET 7 and .NET 8 with provided Project:
[MauiApp2.zip](https://github.com/dotnet/maui/files/12484018/MauiApp2.zip)

![image](https://github.com/dotnet/maui/assets/97647558/3daa7780-e0c3-4ca2-8ab2-e7c85b6d0ad4)

**Comment by AnithaRaniT** [comment]
![image](https://github.com/dotnet/maui/assets/45478510/2cd59535-3ed6-4097-bab8-92872e4aa028)


![image](https://github.com/dotnet/maui/assets/45478510/428c5e78-e3f0-463d-9bc7-1c0b7a47d3ad)


![image](https://github.com/dotnet/maui/assets/45478510/6062bd96-152c-4e8d-a82e-284a263db77e)

@XamlTest Please find the Screenshots. I already tried in the latest preview version of Visual Studio. Still I see the issue.

**Comment by AnithaRaniT** [comment]
Hello @XamlTest  I tried that as well. I still see the same issue. I installed the Enterprise edition of Visual Studio. And there also the same.

**Comment by XamlTest** [comment]
@AnithaRaniT I have encountered the issue, but it seems not stable.

Related to the https://github.com/dotnet/maui/issues/13085

**Comment by AnithaRaniT** [comment]
Seems the issue is closed with no further update. And it's reported 6 months ago. How to track that in that case? Or is there any way can re-open that?

**Comment by dgerding** [comment]
I am getting the same error using .net 8 RC1 and  VS2022 17,8 Preview 2.

**Comment by Fred-Hudson-CST** [comment]
does anyone have a work around

**Comment by AnithaRaniT** [comment]
@dgerding and @Fred-Hudson-CST This might be the certificate issue in the windows platform. Target your solution to the windows platform and create your own certificate for windows with the publisher name and password. And then try to run in the windows machine. It works.

**Comment by Fred-Hudson-CST** [comment]
@AnithaRaniT thanks for the response, what ended up working for me was creating a new solution in place and then moving my project into the new solution ... i could identify no changes to any of the configuration files or code but just copy pasting to a new solution worked for some reason

**Comment by achobanov** [comment]
Same issue here. I'm running on Windows 10, VS 17.7.5. Targeting Yesterday my app was working, today I tried to integrate MudBlazor components and got that error. Initially I thought I messed up the config somehow, but the issue persists after `git stash`.

@Fred-Hudson-CST copying the existing projects in a new solution didn't work, same error
@AnithaRaniT can you share a bit more please? How do I create my own certificate and why do I need certificate to debug the project?

**Comment by achobanov** [comment]
After almost 4 hours of reading, attempting new solutions, new projects, several manual VS cache clears ( almost deleted the whole vs folder by accident ) I finally solved it, by simply pushing my changes and making a fresh repo clone.

**Comment by Fred-Hudson-CST** [comment]
@achobanov its such a strange failure mode, it seems that the 3 of us all found unrelated solutions that did not work in the other cases. makes it very difficult to know what to do when the error presents ... will try re cloning the repo next time i encounter this because that is much easier than what i did to fix it.

**Comment by achobanov** [comment]
Indeed. Not looking forward to encountering that again, lol. Feels bad when not yet mature tooling steps in the way.. but then MAUI allows us to do amazing stuff, so it's worth in the end.

**Comment by Hassan-Abdulbaqi** [comment]
Seriously? there is no solution so i just redo the project? that sucks man

**Comment by achobanov** [comment]
@Hassan-Abdulbaqi it seems to be some sort of bug/immaturity of the platform. These things happen, MAUI is very ambicious

**Comment by Strypper** [comment]
qUalIty 🤡

**Comment by mattleibow** [comment]
This sounds like something was blocking VS for creating/reading the recipe. Are folks still hitting this?

**Comment by mukul-gupta** [comment]
> This sounds like something was blocking VS for creating/reading the recipe. Are folks still hitting this?

Yes ! New to C#, .Net and MAUI; Visual Studio 17.8, .NET 8.0    .  Upgraded from VS 17.6 to 17.8 and started getting it again (dont recall how it 'vanished' last time but I got it a few days back too)

**Comment by Dayjay** [comment]
Hey, I just ran into the same problem after upgrading to the latest Visual Studio 17.8.0 release. Project is a Maui Blazor-Hybrid-App.

I could "fix" it by cloning the repo again. Now everything works as usual.

**Comment by NEmbgen** [comment]
@mattleibow We are also running into this with VS 17.8, .NET 8. No fixes mentioned here have worked.

**Comment by maxibyte** [comment]
I've added `<OutputType>Exe</OutputType>` to the csproj and now it works again.

**Comment by STIGsolution** [comment]
Same issue for me after upgrading to 17.8 on my .NET 7 MAUI project. Changing <OutputType>Launch</OutputType> to Exe in csproj corrected the issue.

**Comment by deveshyngle** [comment]
Upgraded my MAUI project from .NET 6.0 to 8.0 today along with 17.8 Visual studio, same issue persists. Changing Launch to Exe in csproj did not work.

**Comment by wallym** [comment]
I'm getting this issue as well with .NET 8.0.  Have tried all of the fixes for the existing project and no success.

**Comment by jobrien9** [comment]
This happened to me, as well. I'd attempted an upgrade from .NET 6 to .NET8 for my Hybrid Maui Blazor app. After a few hours of trying random stuff, I figured out I was attempting to launch the wrong framework (see screenshot):
![image](https://github.com/dotnet/maui/assets/19732549/530a19ae-bc1c-41bb-866c-461d374883dd)
While my app currently only targets Windows, I also have a plain net8.0 framework in the csproj file. I believe it's used by my unit test project. After switching the Framework to the net8.0-windows10.0.19041.0 in the dropdown in the screenshot, it launched successfully again.

My guess is that the framework got switched after the .NET upgrade

**Comment by dperish** [comment]
> This happened to me, as well. I'd attempted an upgrade from .NET 6 to .NET8 for my Hybrid Maui Blazor app. After a few hours of trying random stuff, I figured out I was attempting to launch the wrong framework (see screenshot): ![image](https://user-images.githubusercontent.com/19732549/284651027-530a19ae-bc1c-41bb-866c-461d374883dd.png) While my app currently only targets Windows, I also have a plain net8.0 framework in the csproj file. I believe it's used by my unit test project. After switching the Framework to the net8.0-windows10.0.19041.0 in the dropdown in the screenshot, it launched successfully again.
> 
> My guess is that the framework got switched after the .NET upgrade

I also have a plain net8.0 targetframework to support an xunit project.  Changing the selected framework as you suggested, along with whacking bin/obj folders, clean & build, and then F5 worked like a charm.  

It'd be nice to have a error that instructed me to check my target framework as well.

**Comment by mattleibow** [comment]
This is very strange and the "created a new project made it work" is also very weird. Typical things that cause issues are some .vs folder or .user files or the obj/bin folders. I wonder if a `git clean -xdf` after pushing changes makes a difference.

If that all fails, I wonder if you `git clean -xdf` and then just rename the whole fodler temporarily. Maybe there is some special VS cache or something that is tracking something.

Or it could be the fact that VS is selecting plain net8.0 and has no way to represent that in the Play button UI.

Are there folks still hitting this that do not have a plain net8.0 TFM and have also tried a fresh clone of their project?
