### ISSUE TITLE
Label that HorizontalOptions is "EndAndExpand" in HorizontalStackLayout  are not working

### ISSUE THREAD

**Issue by maonaoda** [dotnet/maui#16972]
### Description

Label that HorizontalOptions is "EndAndExpand" in HorizontalStackLayout  are not working.
But it works in StackLayout.

![image](https://github.com/dotnet/maui/assets/32831595/e8fd80de-25e4-426b-af53-353d35388dc1)

### Steps to Reproduce

```
            <HorizontalStackLayout BackgroundColor="Green" HorizontalOptions="Fill">
                <Label Text="Label2" FontSize="26" TextColor="pink"
                       HorizontalOptions="EndAndExpand"
                       VerticalOptions="Center"/>
            </HorizontalStackLayout>

            <StackLayout Orientation="Horizontal" BackgroundColor="Green" HorizontalOptions="Fill">
                <Label Text="Label2" FontSize="26" TextColor="pink"
                       HorizontalOptions="EndAndExpand"
                       VerticalOptions="Center"/>
            </StackLayout>
```

### Link to public reproduction project repository

https://github.com/maonaoda/MyTestMauiApp

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

no

### Relevant log output

```shell
no
```

**Comment by hartez** [comment]
This is by design. HorizontalStackLayout and VerticalStackLayout do no support the deprectated "AndExpand" options. Support for them is included in StackLayout for ease of migration from Xamarin.Forms.

I would suggest using an [alternate layout](https://github.com/dotnet/maui/discussions/7346#discussioncomment-2794122).

**Comment by maonaoda** [comment]
Sorry I misunderstood the deprectated "AndExpand" options thing,it seems that child in HorizontalStackLayout and VerticalStackLayout with "AndExpand" is also unsupported.

Thanks for replying.


> This is by design. HorizontalStackLayout and VerticalStackLayout do no support the deprectated "AndExpand" options. Support for them is included in StackLayout for ease of migration from Xamarin.Forms.
> 
> I would suggest using an [alternate layout](https://github.com/dotnet/maui/discussions/7346#discussioncomment-2794122).
