### ISSUE TITLE
[Bug] DesignTools assemblies are missing from workload

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#1699]
When we converted to a workload we dropped shipping the designtools assemblies. 

These should probably be in the ref packs?

**Comment by jonathanpeppers** [comment]
If I look at the pack from Preview 5:

![image](https://user-images.githubusercontent.com/840039/125961830-570a5716-fe5a-4541-af18-0d8a0e9d941b.png)

This is apparently a .NET framework v4.7.2 assembly in the `net6.0-android/Design` folder?

![image](https://user-images.githubusercontent.com/840039/125962042-3556aa72-0dad-41e5-a963-67d82fa9cde2.png)

What is this, and why is it in a `Design` subfolder? I don't see how this would be used at build time at all?

**Comment by Redth** [comment]
https://github.com/dotnet/maui/issues/688

It's not really needed for build time, the designer has a convention where it looks for the special dll by name/location relative to the referenced assemblies...

**Comment by Redth** [comment]
https://github.com/microsoft/xaml-designer-extensibility has more details on how it works...

**Comment by jonathanpeppers** [comment]
So we have to put this file in every `Microsoft.Maui.Controls.Ref.[platform]` pack? So each platform has a copy of the same assembly?
