### ISSUE TITLE
Grid - HeightRequest and WidthRequest is not setting properly in SizeChanged event

### ISSUE THREAD

**Issue by amose-123** [dotnet/maui#16995]
### Description

I have a grid, i am just setting the grid width and height in sizechanged event for landscape and portrait of the device. while rotation the device the widthrequest and heightrequest is not set properly for the orientation. Landscape width and height is set for Portrait. Portrait width and height is set for Landscape. Below are the sample code. your help must be appreciated. Thanks

```csharp
private void Views_SizeChanged(object sender, EventArgs e)
{
   var info = DeviceDisplay.MainDisplayInfo;
   var width = info.Width / info.Density;
   var height = info.Height / info.Density;
   var control = (Grid)sender;
   if (width > height)
   {
      control.HeightRequest = 300;
      control.WidthRequest = 600;
   }
   else
   {
      control.HeightRequest = 200;
     control.WidthRequest = 100;
   }
}
```

### Steps to Reproduce

1. Create a MAUI app
2. Add a grid in page and apply the back ground color for the grid
3. Add size changed event for a grid. This event will trigger when device rotation
4. While rotation a device the grid height and width request is not refreshing
5. In portrait mode HeightRequest is 200 and WIdthRequest is 100, when rotating to landscape mode i am setting HeightRequest is 300 and WidthRequest is 600, but the both values are not refreshing in landscape mode still it is displaying grid with HeightRequest is 200 and WIdthRequest is 100

### Version with bug

7.0.59

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 and Up

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 .NET 8, not repro on iOS 16.4 with below Project:
[16995.zip](https://github.com/dotnet/maui/files/12495549/16995.zip)
![image](https://github.com/dotnet/maui/assets/97647558/655f2ed6-e7d6-4121-af99-1676d9646b6f)
