### ISSUE TITLE
Incorrect Arrangement of Children in Grid Layout

### ISSUE THREAD

**Issue by NirmalKumarYuvaraj** [dotnet/maui#16999]
### Description

When placing a Label, ListView, and a Button inside a Grid Layout with a height defined as Auto, Star, Auto, the arrangement becomes improper, causing the Button to be partially visible within the window. I have verified that Xamarin's implementation of this behavior is correct.  I have attached the screenshot of the issue.

![image](https://github.com/dotnet/maui/assets/97871636/3cf0cec9-f18e-4f6f-a74d-5df5a5d38620)

**Code Snippet**
```XAML
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto"/>
        <RowDefinition Height="*"/>
        <RowDefinition Height="Auto"/>
    </Grid.RowDefinitions>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*"/>
        <ColumnDefinition Width="Auto"/>
    </Grid.ColumnDefinitions>
    <Label Text="This is Label" Grid.Row="0" Grid.ColumnSpan="2"/>
    <ListView ItemsSource="{Binding Monkeys}" 
              Grid.Row="1" 
              Grid.ColumnSpan="2">
        <ListView.ItemTemplate>
            <DataTemplate>
                <ViewCell>
                    <StackLayout>
                        <Label Text="{Binding Name}" TextColor="Black" FontAttributes="Bold" FontSize="22"/>
                        <Label Text="{Binding Location}"/>
                    </StackLayout>
                </ViewCell>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
    <Button Grid.Row="2" Grid.Column="0" Text="Test1"/>
    <Button Grid.Row="2" Grid.Column="1" Text="Test2"/>
</Grid>
```

### Steps to Reproduce

1.  Run the attached sample in Windows.
2.  Notice the Button is Partially visible in output Window.

### Link to public reproduction project repository

https://github.com/NirmalKumarYuvaraj/GridLayoutDisplaceIssue

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

**Comment by rmarinho** [comment]
Duplicated of #17000
