### ISSUE TITLE
Unnecessary Compiler rebuilds 

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#17005]
### Description

If you are working in DotNet MAUI release mode on a physical Android device, the build process has to rebuild 188+ libraries every time to ".so" whenever you make a change. This makes testing the release build unnecessarily lengthy.

Since the 188 core .Net files do not change during this testing cycle, it seems unreasonable to have to wait for a conversion to ".so" for each of these files every time.

Thanks 

### Steps to Reproduce

Create an Android release and run on a physical Android 33 device.

Deploy, then make a source code change and redeploy.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

None

### Relevant log output

```shell
None
```

**Comment by rmarinho** [comment]
This issue was moved to xamarin/xamarin-android#8306
