### ISSUE TITLE
Visual Studio 16 Preview 3.0 / .NET 6.0 Preview 6 can't run Maui Blazor Project Template

### ISSUE THREAD

**Issue by PaulSorauer-IPG** [dotnet/maui#1701]
Hi there

I'm using Microsoft Visual Studio Professional 2019 Preview Version 16.11.0 Preview 3.0 and have updated to the Preview 6 version of the .NET 6.0 SDK and have also run the latest version of the 'maui-check' tool, so everything supporting the latest .NET 6.0 Preview 6 should be installed.

I created a new project and selected the existing '.NET MAUI Blazor App' project template:

![image](https://user-images.githubusercontent.com/61489185/125876910-8dec8328-354b-4378-a0c2-3e7ff6946010.png)

As soon as all dependencies have been downloaded from NuGet I tried to run the solution targeting the WinUI version and VS complains that "The project doesn't know how to run the profile":

![image](https://user-images.githubusercontent.com/61489185/125877228-0cfcc2a3-76f9-45ac-857a-359e3af5bce6.png)

This was working fine in Preview 5.

**Comment by Redth** [comment]
You will need to use VS2022 for WinUI in dotnet 6 preview 6 or newer.  The blog post has more information: https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-6/

**Comment by PaulSorauer-IPG** [comment]
@Redth - this isn't  WinUi app - it's a MAUI Blazor App that runs fine in BOTH VS 2019 and 2022 but in Preview 5 - upgrading to VS Preview 3 / .NET 6.0 Preview 6 causes the above error.

Since I first posted I also tried VS 2022 which similarly errors. And I've also tried creating a new project using "dotnet new maui-blazor" and again, VS 2022 Preview 2 throws the same error.
