### ISSUE TITLE
Shell.Current.CurrentPage is always null

### ISSUE THREAD

**Issue by MV10** [dotnet/maui#17019]
### Description

Not much else to say -- as far as I can tell, `Shell.Current.CurrentPage` is always null.
Repro (below) is trivial but it persists in more complex shell-navigation-based apps.

I won't provide a repro repository for a one-liner issue, so please don't waste my time with the repro-attack-bot and auto-close. 😁 

### Steps to Reproduce

Create a new .NET 7 MAUI template app and add this line to the `MainPage.xaml.cs` constructor:

```csharp
Debug.WriteLine($"CurrentPage: {(Shell.Current.CurrentPage)?.GetType().ToString() ?? "null"}");
```

It will always output:

```
CurrentPage: null
```

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Did you find any workaround?

I can reference the route name in the property from this somewhat ridiculous hierarchy:

```csharp
Shell.Current.CurrentItem.CurrentItem.CurrentItem.Route
```

**Comment by drasticactions** [comment]
I believe that is correct for the given situation.

You're asking for the `CurrentPage` while it's being created in the constructor. It's not set yet, so there is none. If you check after it has been set (In the template, you can put this in OnCounterClicked) it will show it as the current page.

@PureWeen is this a bug, or should this be closed?

**Comment by MV10** [comment]
That makes sense, but my real application was checking `CurrentPage` in response to user activity on the page. However, when I move the repro debug output to the default template's button-click event, the correct page is shown, so I'll try to figure out what's going on and if it looks like a bug, in that case I will open a repro, as I imagine it'll be a little more involved.

Closing until then, thanks.
