### ISSUE TITLE
Move AndExpand to Attached Properties

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#1702]
AndExpand is a confusing paradigm that no one fully understands. It only applies to StackLayout, but it appears in the general LayoutOptions. It needs to be moved out and stuck to StackLayout so it’s clear when it’ll take effect.

**Comment by hartez** [comment]
Alternatively, #1872

**Comment by hartez** [comment]
See also #29

**Comment by jsuarezruiz** [comment]
Take a look to the discussion here: https://github.com/dotnet/maui/discussions/3324

**Comment by jsuarezruiz** [comment]
We have a discussion and the same issue (not exactly the same, but covering the same topic) duplicated. Closing this one to concentrate all the comments in #29.
