### ISSUE TITLE
Rename Min/Max Width/Height Request to Width/Height

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#1703]
The new layout functionality no longer treats these as 'requests'.

**Comment by Redth** [comment]
The functionality isn't changing but we decided ultimately that the semantics of the current name are still reasonable and valid and to avoid such a breaking xaml change

**Comment by AmrAlSayed0** [comment]
I don't think Width & Height are a replacement for (Min/Max)Width & (Min/Max)Height. In a matter of fact, they're opposites. You wouldn't set both Width and MaxWidth for example.

The Min/Max properties define the size of the element when the element _can change_. The other forces the element to _not change_.
