### ISSUE TITLE
Hot reload file save issue in .NET MAUI

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [dotnet/maui#17038]
Not repro on VS 17.2.0 Preview 2.0 [32208.484.main]

_Originally posted by @Amir-Care in https://github.com/dotnet/maui/issues/3369#issuecomment-1054945594_
            .NET MAUI hot reloading with file (XAML) save is not working properly.

**Comment by drasticactions** [comment]
Can you detail what you're referring to? Is there something specific that doesn't work? Is there an error? This is too vague to be actionable.

**Comment by SoumyadipYT-OSS** [comment]
Can you tell me the official stable version of MAUI ? Because some features of dotnet maui is still not working and hot reload also not working in visual studio 2022
________________________________
