### ISSUE TITLE
Nightly Builds fail to compile

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#17040]
### Description

Created a new project, compiles fine. Update to nightly build 8.0.0-rc.1.9068, compiles fine.

Update to any nightly build beyond 8.0.0-rc.1.9068, fails to build with the following results:

Rebuild started...
1>------ Rebuild All started: Project: MauiApp1, Configuration: Debug Any CPU ------
Restored E:\Projects\Maui.Issues\MauiApp1\MauiApp1.csproj (in 245 ms).
1>C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>C:\Users\eboel\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(148,5): error : Improper project configuration: no AppxManifest is specified, but WindowsPackageType is not set to MSIX.
1>Done building project "MauiApp1.csproj" -- FAILED.
1>E:\Projects\Maui.Issues\MauiApp1\App.xaml.cs(4,4,4,23): error CS0103: The name 'InitializeComponent' does not exist in the current context
1>E:\Projects\Maui.Issues\MauiApp1\AppShell.xaml.cs(4,4,4,23): error CS0103: The name 'InitializeComponent' does not exist in the current context
1>E:\Projects\Maui.Issues\MauiApp1\MainPage.xaml.cs(6,4,6,23): error CS0103: The name 'InitializeComponent' does not exist in the current context
1>E:\Projects\Maui.Issues\MauiApp1\MainPage.xaml.cs(13,5,13,15): error CS0103: The name 'CounterBtn' does not exist in the current context
1>E:\Projects\Maui.Issues\MauiApp1\MainPage.xaml.cs(15,5,15,15): error CS0103: The name 'CounterBtn' does not exist in the current context
1>E:\Projects\Maui.Issues\MauiApp1\MainPage.xaml.cs(17,34,17,44): error CS0103: The name 'CounterBtn' does not exist in the current context
1>Done building project "MauiApp1.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
========== Rebuild started at 3:00 PM and took 05.133 seconds ==========

### Steps to Reproduce

Create a new project.
Update to any nightly build after 8.0.0-rc.1.9068... to 8.0.0-rc.1.9071 or 8.0.0-rc.1.9080.
Build fails.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows SDK - all, Android API 34

### Did you find any workaround?

No

**Comment by Stedy59** [comment]
Note: If I remove the Windows Target and compile for Android only, the "AppxManifest" error goes away, but the others persist.

**Comment by mattleibow** [comment]
Are you able to share a binlog? https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

Also, what version of the .NET SDK are you using and how are you getting RC 1 builds?

**Comment by mattleibow** [comment]
I tested now with .NET 8 Preview 7 and used the MauiVersion to update MAUI to RC 1 as well as a daily build of .NET RC 1. But, it all seems to build and deploy a Windows app the first time.

**Comment by Stedy59** [comment]
> I tested now with .NET 8 Preview 7 and used the MauiVersion to update MAUI to RC 1 as well as a daily build of .NET RC 1. But, it all seems to build and deploy a Windows app the first time.

@mattleibow @samhouts 

Current SDK Version:
![image](https://github.com/dotnet/maui/assets/46286656/36282931-6166-4598-87f5-2fe032c6bc9f)

Current Workload:
![image](https://github.com/dotnet/maui/assets/46286656/3bcc8018-729e-4034-9973-84d43005373a)

I am getting the nightly Maui builds from:
`https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json`

![image](https://github.com/dotnet/maui/assets/46286656/b74b0eaa-80cc-496b-8ad9-5c23c6be4ba1)

**Comment by Stedy59** [comment]
Most likely, Microsoft.Maui.Controls needs an updated .NET SDK version. Is RC1 available? Or is VS Version 17.8.0 Preview 2.0 with the RC1 bits on the near horizon?

**Comment by mattleibow** [comment]
I think I finally found out why the builds are failing. I am not sure why it did not fail for me on my first tests, but I eventually got a failing project... That was exactly the same. But, I think I have a fix that I will merge ASAP.
