### ISSUE TITLE
FlyoutBackgroundImage not shown when compiled with 'WindowsMachine'

### ISSUE THREAD

**Issue by edikaufmann** [dotnet/maui#17052]
### Description

when using the (original/cloned!) Shell/Xaminals sample:

- compiled with my Android 13: the 'FlyoutBackgroundImage=photo.jpg' (AppShell.xaml) shows correctly.
- compiled with 'Windows Machine': the FlyoutBackgroundImage does NOT show up.
(I cloned a fresh version of( xaminals) into my VS) .
![xami](https://github.com/dotnet/maui/assets/51043011/1d9ac50f-59e5-439a-ad0a-09b87a3d0b1d)

repro: clone in VS 'xaminals' compile for Android
I'm using : VS: 17.6.4,  Android: 13.0 API-33

What might be wrong with my VS (Window Machine) compilation? wrong settings, parameters ...

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

C:\Users\edika\.nuget\packages\microsoft.windows.sdk.buildtools\10.0.22621.755\      Android 13.0 API 33  VS 17.6.4

### Did you find any workaround?

live without the background

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.10.0 Preview 1. Can repro on Windows platform with sample project. 
https://github.com/xamarin/xamarin-forms-samples/tree/main/UserInterface/Xaminals
![image](https://github.com/dotnet/maui/assets/77434865/bda5c9c2-ebba-468b-aeb5-984d9c159854)

**Comment by edikaufmann** [comment]
sorry, forgot to close. all ok
