### ISSUE TITLE
CollectionView sets the wrong height for items containing long word-wrapped text inside a * column

### ISSUE THREAD

**Issue by mfeingol** [dotnet/maui#17050]
### Description

See description and repro steps

### Steps to Reproduce

Inside a CollectionView, define the item DataTemplate using a Grid with several columns with Width=Auto and one column with Width=* containing a Button with long text and LineBreakMode set to WordWrap. You will see the incorrect rendering:

![image](https://github.com/dotnet/maui/assets/218865/d33c774a-3456-4b32-975d-ec0d668004f4)

Using hot reload, add a character to the Button's text and save. You will see the correct rendering:

![image](https://github.com/dotnet/maui/assets/218865/ea3b10e9-4c1b-47db-9ab7-734c529b43e1)

### Link to public reproduction project repository

https://github.com/mfeingol/repros/tree/master/CollectionViewHeightBug

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

Setting a min height works, but is very annoying.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Android 13.0-API33 .NET 8 with below Project:
[CollectionViewHeightBug.zip](https://github.com/dotnet/maui/files/12512275/CollectionViewHeightBug.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/8a8af044-2e8e-4de7-a776-134dcfe699e6)

Android:
![image](https://github.com/dotnet/maui/assets/97647558/4eaa1f93-f36d-4f02-9b46-0191553b1cf8)

iOS:
![image](https://github.com/dotnet/maui/assets/97647558/e8af908b-9095-4eec-a222-1368e22bee55)

**Comment by mfeingol** [comment]
This appears to be fixed in MAUI 8.0.6.
