### ISSUE TITLE
Net 8 Preview VS Installer - No such option 

### ISSUE THREAD

**Issue by mgungorchamp** [dotnet/maui#17051]
There is no "NET MAUI (.NET 8 Preview)” option available as mentioned there

https://github.com/dotnet/maui/releases

Here is the screen shot.
![image](https://github.com/dotnet/maui/assets/83103466/a6e494c9-4d92-4db5-adda-4050fbdbc822)

**Comment by drasticactions** [comment]
I believe the .NET 8 Preview are installed by default as part of Visual Studio 17.8.0 Preview 1, which includes the MAUI Preview workloads. You don't need to select them, they are apart of the install.

**Comment by mgungorchamp** [comment]
You were right!
