### ISSUE TITLE
How do we use Microsoft.Maui.Controls.WebView in the mobile application that wants to launch multiple browser tabs?

### ISSUE THREAD

**Issue by udayvalluri** [dotnet/maui#17063]
### Description

Our mobile app uses Microsoft.Maui.Controls.WebView to launch a web page. The content/buttons on the page need to launch another window but this functionality is not working. The buttons that are supposed to launch a new window are unresponsive on the webview. The action that we are using to launch a new tab has been attached. Please take a look at the attachment. How do we make sure that the buttons launch a new window? Do we need to change the action of how we are launching or anything can be done from the mobile side?

![MicrosoftTeams-image](https://github.com/dotnet/maui/assets/53011890/a15967c8-f569-4342-a2e3-59ea9235483b)

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by drasticactions** [comment]
If possible, could you please create a small reproduction project with what you're attempting to do and what you're expecting? I'm not sure based on the context of the code posted what your expectations are for what should open, having a repro project would help make that clearer.

**Comment by udayvalluri** [comment]
@davidortinau @drasticactions @Eilon 
Hi, I have included a sample solution under the below repository. I could not take care of adding gitignore due to time limitations. In the example, I have a simple Maui webview that is loading index.html. Index.html has one button that tries to open index2.html using this statement - "**window.open("index2.html");**". This is not working on mobile. I have tried using - ** window.open("index2.html", "_self");** and this works fine to open within the same webview. But as per our need, we do not want to launch index2.html on the same window we have launched index.html because we will have some user inputs on index.html so we do not want to lose those by launching another page. 

https://github.com/udayvalluri/WebviewNewTab

**Comment by Eilon** [comment]
I'm guessing this needs to be explicitly enabled by the WebView itself to enable opening URLs in 'external' browser windows. For example, in BlazorWebView on iOS it's an optional thing and ultimately it handles external browsers here: https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs#L250. And for BlazorWebView on Android there's similar logic here: https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs#L60

I'm not sure how to do this in the regular WebView.

**Comment by udayvalluri** [comment]
@Eilon - Recently we have learned to communicate back and forth between MAUI and Webview. If a button on the webview page wants to open a new window, we can transfer that event to MAUI using script bridge and can open Safari browser. Using C# we can still open Safari so UIApplication.SharedApplication.OpenUrl is not a limitation in our scenario. But our need is to keep the user inside the app instead of opening another app(Safari). Also, we do want to carry the user auth to the new window instead of asking the user to sign in for every new window.

**Comment by udayvalluri** [comment]
Right now, we are able to achieve this using a script bridge between Webview and MAUI. Whenever a web page wants to launch a new page, we pass that event from web view to native, and native launches another web view instance with a new page URL. For now this works fine for us so closing the issue.
