### ISSUE TITLE
Cannot connect to mac after updating to VS 17.7.3

### ISSUE THREAD

**Issue by jbtdevgit** [dotnet/maui#17089]
### Description

I just installed the new Visual Studio 2022 Update 17.7.3 on my Windows PC. Since then, I cannot pair with my Mac anymore to deploy my .NET MAUI App. I am getting the following Error Message:

`Could not install workload 'ios'. Details: Workload installation failed: Failed to install manifest microsoft.net.sdk.ios version 16.4.7098: microsoft.net.sdk.ios.manifest-7.0.100::16.4.7098 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging`

### Steps to Reproduce

- Update to VS 2022 17.7.3
- Update VS Mac Preview to latest
- Pair to Mac in VS 2022

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.92

### Affected platforms

iOS, macOS

### Affected platform versions

iOS, MacOS

### Did you find any workaround?

n/a

### Relevant log output

```shell
n/a
```

**Comment by schlaman** [comment]
I have the exact same problem now with pairing to Mac after updating to VS 17.7.3

"Could not install workload 'ios'. Details: Workload installation failed: Failed to install manifest microsoft.net.sdk.ios version 16.4.7098: microsoft.net.sdk.ios.manifest-7.0.100::16.4.7098 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://api.nuget.org/v3/index.json"

**Comment by tgudelj** [comment]
Could this be fixed by publishing the required version of the package?

**Comment by DosangGu** [comment]
<https://developercommunity.visualstudio.com/t/Pair-to-Mac:-Could-not-install-workload/10453595?q=mac+pair&sort=newest>

**Comment by DosangGu** [comment]
I fixed this issue following these steps.

1. Rolling back to visual studio 17.7.2
2. Open `C:\Program Files\dotnet\sdk-manifests\7.0.100\microsoft.net.sdk.ios\WorkloadManifest.json` as an administrator
3. Edit all version field with "16.4.7098" to "16.4.7090"
4. Do `dotnet restore` command on my solution(project)

I lost all my extensions settings due to rolling back the visual studio. And I assume that editing the WorkloadManifest.json file without roll back can fix the issue. Can somebody try to edit the WorkloadManifest.json file with visual studio 17.7.3 and share the result?

**Comment by jbtdevgit** [comment]
> I have the exact same problem now with pairing to Mac after updating to VS 17.7.3
> 
> "Could not install workload 'ios'. Details: Workload installation failed: Failed to install manifest microsoft.net.sdk.ios version 16.4.7098: microsoft.net.sdk.ios.manifest-7.0.100::16.4.7098 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://api.nuget.org/v3/index.json"
> 
> UPDATE: **Good news** - I rolled back to 17.7.2 and connected just fine to my Macbook.
> 
> **I sure would hope that EVERY single release would be tested to make sure it plays nicely with the Mac** Otherwise it leaves us .NET MAUI developers out in the cold!!
> 
> If you don't know how to rollback. Just use the "Visual Studio Installer" and select the 'More' dropdown in the block with the 17.7.3 and choose the rollback option. It took only a couple of minutes.

Nope, this destroyed my workloads. Updating `dotnet workload update` does not work as well as it is still looking for the nuget.

**Comment by jbtdevgit** [comment]
> I fixed this issue following these steps.
> 
> 1. Rolling back to visual studio 17.7.2
> 2. Open `C:\Program Files\dotnet\sdk-manifests\7.0.100\microsoft.net.sdk.ios\WorkloadManifest.json` as an administrator
> 3. Edit all version field with "16.4.7098" to "16.4.7090"
> 4. Do `dotnet restore` command on my solution(project)
> 
> I lost all my extensions settings due to rolling back the visual studio. And I assume that editing the WorkloadManifest.json file without roll back can fix the issue. Can somebody try to edit the WorkloadManifest.json file with visual studio 17.7.3 and share the result?

Okay, so I reinstalled back 17.7.3 as rolling back causes an issue with the workloads.
You can update the `WorkloadManifest.json` to `7090` and this will fix the pairing

**Comment by TamerIrdais** [comment]
As @jbtdevgit said I fixed this on my machine by reinstalling 17.7.3 and then update WorkloadManifest.json to 7090
