### ISSUE TITLE
NavigationPage bar gets stuck and stops updating its title

### ISSUE THREAD

**Issue by mfeingol** [dotnet/maui#17083]
### Description

In short, the NavigationPage's NavigationBar stops updating after a few rounds of navigation:

![image](https://github.com/dotnet/maui/assets/218865/18c02022-3572-48b5-84b3-11a6714e2c23)

### Steps to Reproduce

I created a simple repro using a FlyoutPage, a couple of main pages, and a couple of detail pages.

1. Press the button to navigate to DetailPage1
2. Go back
3. Use the flyout to navigate to MainPage2
4. Press the button to navigate to DetailPage2
5. Observe the NavigationBar's title doesn't update. It should be set to each page's title on entry

### Link to public reproduction project repository

https://github.com/mfeingol/repros/tree/master/NavigationPageRepro_2023

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No workaround.

**Comment by mfeingol** [comment]
This will break any app using NavigationPage, which is likely many if not most Xamarin Forms apps. Will someone be taking a look at this?

**Comment by vecalion** [comment]
> This will break any app using NavigationPage, which is likely many if not most Xamarin Forms apps. Will someone be taking a look at this?

And this is exactly what is happening with our app. @mfeingol Any known workarounds?

**Comment by mfeingol** [comment]
@vecalion: sadly, no. I've been looking into what it would take to port over to Shell, but it's major surgery.

**Comment by mfeingol** [comment]
@samhouts: any hope for this getting fixed? It's pretty critical to migration.

**Comment by mfeingol** [comment]
I spent some more time on this today and found a workaround: instead of setting the `Detail` property on the `FlyoutPage`, replace the FlyoutPage page entirely:

```c#
        NavigationPage nav = new((Page)Activator.CreateInstance(type));

        // This doesn't work, and it's a regression from Xamarin Forms
        //this.Detail = nav;

        // This is the workaround I've found
        App.Current.MainPage = new AppFlyoutPage { Detail = nav };
```

cc @vecalion

I also updated the repro project I linked above for .NET 8 GA.

**Comment by mfeingol** [comment]
@mattleibow: I tried out `8.0.4-nightly.9714` and it does appear to be fixed. Thanks for the note.
