### ISSUE TITLE
Issue in Grid column sizing

### ISSUE THREAD

**Issue by RanjithkumarSyncfusion** [dotnet/maui#17097]
### Description

Sample description

- Grid with 2 rows (Auto,Star)  and 2 columns(Auto,Star)
- 
> <table>
>     <tbody>
>         <tr >
>             <td colspan=2>
>                Grid with 3 columns(*,*,*) ColumnSpan 2
>                <table>
>                     <tbody>
>                         <tr >
>                             <td>Label</td>
>                             <td>Button1</td>
>                             <td>Label(horizontalOptions End)</td>
>                        </tr>
>                    </tbody>
>              </table>
>              </td>
>         </tr>
>         <tr>
>             <td>Button2(visibility false)</td>
>              <td>Scrollview</td>
>         </tr>
>     </tbody>
> </table>
> 

- When clicking button 1 button2 becomes visible.

When button 2 becomes visible the **End Label moves out of the view**. 

**Noted:**
Screen width - 950
Button 2 width- 50

When button 2 is visible, the scrollview is getting measured with full width 950 which causes the increase in 2nd column width(results in end label to move out of the view ) and the Grid total width becomes (950 +50) . The remaining 50 portion will not be in the view.

**Expected :** 
Since Scroll view column definition is Star, it should be measured with remaining width(screen width - button 2 width) 900 but since the grid gives 950 to scrollview causes the above issue.

### Steps to Reproduce

Open the attached sample and press the Center button.
[DemoProj.zip](https://github.com/dotnet/maui/files/12473249/DemoProj.zip)

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

latest

**Comment by mattleibow** [comment]
I could repro thiswith a simpler xaml:

```xaml

    <Grid RowDefinitions="Auto,*"
          ColumnDefinitions="Auto,*">

        <Grid ColumnDefinitions="*,*,*"
              Grid.Row="0" Grid.Column="0"
              Grid.ColumnSpan="2"
              HorizontalOptions="Fill" VerticalOptions="Fill">

            <Label Text="Start Start Start Start" BackgroundColor="Orange" />
            <Label Text="Center" BackgroundColor="Pink" Grid.Column="1" />
            <Label Text="End End End End" BackgroundColor="Green" Grid.Column="2" HorizontalTextAlignment="End" />
        </Grid>

        <Button Grid.Row="1" Grid.Column="0"
                Text="Hide ME"
                BackgroundColor="Aqua"/>

        <ScrollView Grid.Row="1" Grid.Column="1"
                    BackgroundColor="Red">
            <Label Text="What do you mean by current? What is Current? | Fluke Current is the rate at which electrons flow past a point in a complete electrical circuit. At its most basic, current = flow. An ampere (AM-pir), or amp, is the international unit used for measuring current"/>
        </ScrollView>

    </Grid>
```

**Comment by mattleibow** [comment]
Even simpler, Just remove the `RowDefinitions="Auto,*"` from the xaml to fix it (add it back to break it):

```xaml

<Grid RowDefinitions="Auto,*"
        ColumnDefinitions="Auto,*">

    <Button Grid.Row="1" Grid.Column="0"
            Text="Hide ME"
            BackgroundColor="Aqua"/>

    <Grid Grid.Row="1" Grid.Column="1"
                BackgroundColor="Red">
        <Label Text="What do you mean by current? What is Current? | Fluke Current is the rate at which electrons flow past a point in a complete electrical circuit. At its most basic, current = flow. An ampere (AM-pir), or amp, is the international unit used for measuring current"/>
    </Grid>

</Grid>
```

![image](https://github.com/dotnet/maui/assets/1096616/e7f3e74d-fda4-43f9-a338-4d8b2b3f6f53)

**Comment by QianaJiao** [comment]
Verified this issue with Visual Studio Enterprise 17.10.0 Preview 1. Can repro with sample project. [DemoProj.zip](https://github.com/dotnet/maui/files/12473249/DemoProj.zip)
