### ISSUE TITLE
Switch's Text

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#1709]
Hi,

Please add a Text to Switch with TextAlignment. This will make it easier to add switch and developer will have the choice to use the Switch's Text or a separate Label control, for example:

`<Switch Text="Push Notification" TextPosition="Before" TextAlignment="Left" TextColor="Red" fontSize="15" IsToggled="True"/>`

**Comment by vhugogarcia** [comment]
I personally was thinking the same way a few years ago. However, I later learned that by doing that the layout/themes are going to be complex behind the scenes. So, I prefer to skip this suggestion. There is nothing that a horizontal stack layout with a switch control and a label can do now on MAUI. 😋

**Comment by jfversluis** [comment]
I think the way we have this implemented right now allows for maximum flexibility over the layout. If this is something you want it should be easy to create an inherited/compound control that will do this for you in your project.

If you're convinced we should have this, I would love to see your substantiation using the feature request template.
