### ISSUE TITLE
An error was encountered while registering a service worker js script in the MAUI Blazor Hybrid application

### ISSUE THREAD

**Issue by Qiulin-Git** [dotnet/maui#17095]
### Description

Can we use service workers in the maui blazor hybrid? I got an error registering a service worker js script in my blazor hybrid app.

Below is the display of the error I encountered in Dev Tools Console：

```
Service Worker: Error: TypeError: Failed to register a ServiceWorker for scope ('https://0.0.0.0/') with script ('https://0.0.0.0/sw.js'): An unknown error occurred when fetching the script.
```

Here is the script referenced in <script> tag:
```
if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
        navigator.serviceWorker
            .register('./sw.js')
            .then(reg => console.log('Service Worker: Registered (Pages)'))
            .catch(err => console.log(Service Worker: Error: ${err}));
    });
}
```

The same script works fine in the Blazor WebAssembly, and I don't know what the problem is.
Can we use service workers in the maui blazor hybrid?  If possible, how to set it up .

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Running a service working in a webview is not supported.
