### ISSUE TITLE
MAUI Blazor release version fine, published version fails

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#17116]
### Description

I have successfully published this app once, but now Release mode works fine but the published version immediately fails.

How can I determine what is causing this since it does not get far enough to write debug messages.

### Steps to Reproduce

Create a MAUI Blazor App with DotNet 7.

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

None

**Comment by Eilon** [comment]
Hi @genifycom , we'll need some more info in order to figure out what's happening. Are you able to reproduce this in a new app? The bug report specifically mentions .NET 8.0.0-preview.7.8842, which has a known bug (with [a workaround](https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849)), but in the text it also says to reproduce the issue use DotNet 7. Can you clarify which version has the issue? Also, what exactly fails? Does the app crash? Or load, but not work correctly?

**Comment by genifycom** [comment]
Question. In the csproj, I am using DotNet 7

        <TargetFrameworks>net7.0-maccatalyst;net7.0-android33.0</TargetFrameworks>

but the runtime I have 

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23260.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Since the project says to use DotNet 7, then can I assume that the DotNet runtime is being used for deployment?

The app shows the splash screen and immediately stops.

**Comment by Eilon** [comment]
```
    <TargetFrameworks>net7.0-maccatalyst;net7.0-android33.0</TargetFrameworks>
```

That indicates you're using .NET 7. The other list shows you have various other .NET runtime versions also installed.

Does this issue reproduce if you create a brand new .NET 7 MAUI Blazor Hybrid project and run it in release? And how about a .NET 7 MAUI (non-Blazor) app?
