### ISSUE TITLE
TableSection and TableRoot Title properties are displayed as lower case on Windows.

### ISSUE THREAD

**Issue by apk24** [dotnet/maui#17123]
### Description

TableView elements' Title properties don't carry any capitalization. 

The following TableView has both upper case and lower case titles, but is rendered with only lower case. 
```
    <TableView Intent="Menu"
               HorizontalOptions="Center">
        <TableRoot Title="TableRoot Title Text">
            <TableSection Title="TableSection Title Text">
                <TextCell Text="TextCell Text"
                          Detail="TextCell Detail" />
                <EntryCell Label="EntryCell Label"
                           Placeholder="EntryCell Placeholder" />
            </TableSection>
        </TableRoot>
    </TableView>
```

![image](https://github.com/dotnet/maui/assets/6509460/f217fb3b-a738-404a-9f5a-5dd1df177064)

See Also: [StackOverflow Question](https://stackoverflow.com/questions/74771568/maui-tableview-title-capitalisation)

### Steps to Reproduce

Create a new .NET MAUI app. 
Replace all content from MainPage with the above TableView.
Compile and Run on Windows. 

### Link to public reproduction project repository

https://github.com/apk24/dotnet-maui-tableview-titles-bug

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17763.0

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11 and iOS 16.4 .NET 8, not repro on Android 13.0-API33 with below Project:
[MauiApp1.zip](https://github.com/dotnet/maui/files/12522067/MauiApp1.zip)

Windows: TableView rendered lower case. 
![image](https://github.com/dotnet/maui/assets/97647558/59c6a00d-9cf0-4ac2-8ba0-3e784470fed5)

iOS: TableView rendered upper case. 
![image](https://github.com/dotnet/maui/assets/97647558/6bb475d1-6012-4985-aad1-d3c4f84c5d03)

**Comment by danies8** [comment]
Verify that this issue happened in net 7 vs 17.4.
Does it will be fixed in net 8 on November relese ?

**Comment by ajsuydam** [comment]
Has anyone found a workaround for this?

**Comment by DanielGramsJTL** [comment]
As workaround for TableSection, i inserted the following to `Platforms\Windows\App.xaml`:

```
<maui:MauiWinUIApplication.Resources>
    <ResourceDictionary>
        <DataTemplate x:Key="TableSection">
            <TextBlock Margin="0,20,0,0" Text="{Binding Title}" Style="{ThemeResource SubtitleTextBlockStyle}" Visibility="{Binding Text,RelativeSource={RelativeSource Mode=Self},Converter={StaticResource CollapseWhenEmpty}}" Foreground="{Binding TextColor,Converter={StaticResource ColorConverter},ConverterParameter=DefaultTextForegroundThemeBrush}" />
        </DataTemplate>
    </ResourceDictionary>
</maui:MauiWinUIApplication.Resources>
```

Original Template from https://github.com/dotnet/maui/blob/68524c8056491da6a40b06dd0c979de1bb40538f/src/Controls/src/Core/Compatibility/Handlers/TableView/Windows/TableViewStyles.xaml#L19C5-L21C20
