### ISSUE TITLE
Migration from Xamarin to MAUI - Title bar is not coming in children pages and tabs pages  

### ISSUE THREAD

**Issue by siddhisadh** [dotnet/maui#17126]
### Description

I am not able to see title bar on children pages , for eg

**Ticket History** is main page where I am able to see title bar but  if routing from this page to there child details page, only **tabs** are coming but title bar is disappear , and same with happen with all children pages.

This all are TabbedPages not ShellTabs

![05-readonly list](https://github.com/dotnet/maui/assets/93911238/e5df90ce-1711-42db-8959-80679cbcda6b)

![06-Details](https://github.com/dotnet/maui/assets/93911238/9dd3f5ab-10d2-433a-9444-00b0a190e615)

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by siddhisadh** [comment]
Any update on this?

**Comment by jfversluis** [comment]
Hey @siddhisadh is this still an issue for you? Could you maybe try with .NET 8? If it still shows the same behavior, please provide a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md) that shows this behavior so we can look at it more quickly.
