### ISSUE TITLE
[Android] - Cursor Resets to the Beginning When Typing Letters with TextTransform

### ISSUE THREAD

**Issue by AlexRojasB** [dotnet/maui#17122]
### Description

Cursor Resets to the Beginning When Typing Letters with TextTransform 'Uppercase' on Editor Control in Android

When using the TextTransform="Uppercase" or TextTransform="Lowercase" attribute on an editor control within a MAUI application running on the Android platform, a critical issue arises. This problem is also observed when toggling between uppercase and lowercase characters using the virtual keyboard's shift functionality. The unexpected behavior manifests as the cursor resetting to the beginning of the text input, disrupting the natural typing flow.

https://github.com/dotnet/maui/assets/39141911/605d0c2b-a4e8-4216-9083-c27aea6c71d8

### Steps to Reproduce

1. Create a MAUI application containing an editor control for text input.
2. Apply either the TextTransform="Uppercase" or TextTransform="Lowercase" attribute to the editor control.
3. Deploy the application on an Android device.
4. Begin typing text using the virtual keyboard and observe the cursor behavior.
5. Toggle between uppercase and lowercase using the keyboard's shift functionality and note the cursor's behavior.

Expected Behavior:
The text entered should be transformed to uppercase as intended, and the cursor should remain at its current position within the text input field.

Actual Behavior:
As letters are typed using the virtual keyboard, the cursor unexpectedly jumps to the start of the text input, disrupting the natural typing flow and causing confusion for users. This behavior is not observed on the iOS platform, where the cursor remains in the correct position.

Additional Information:

The issue occurs consistently on various Android devices running different versions of the operating system.
The problem does not manifest on the iOS platform, where the cursor behaves as expected while using TextTransform="Uppercase" on the editor control.

This bug severely impacts the user experience and the usability of text input fields, particularly when uppercase formatting is required

### Link to public reproduction project repository

https://github.com/AlexRojasB/MauiTextTransformationIssue

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13, Android 11

**Comment by RobTF** [comment]
+1

**Comment by AlexRojasB** [comment]
A possible workaround that was shared with me by Jose Orosco seems to work well on both platforms, so I'm sharing the code with you.

   ```
 <Entry
    VerticalOptions="Start"
    Placeholder="Brand"
    ReturnType="Next">
    <Entry.Keyboard>
        <Keyboard x:FactoryMethod="Create">
            <x:Arguments>
                <KeyboardFlags>CapitalizeCharacter</KeyboardFlags>
            </x:Arguments>
        </Keyboard>
    </Entry.Keyboard>
</Entry>
```

**Comment by RobTF** [comment]
> A possible workaround that was shared with me by Jose Orosco seems to work well on both platforms, so I'm sharing the code with you.
> 

Seems so work great, thankyou. This is the sort of thing .NET 8 needs sorting although I'm not enthused by the number of regressions in the issues list :(

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 4(8.0.3). This issue does not repro on Android 13.0-API33 and Android 11.0-API30 with below Project:
[TestAndroidEntry.zip](https://github.com/dotnet/maui/files/14061879/TestAndroidEntry.zip)

https://github.com/dotnet/maui/assets/97647558/0765099b-5d4e-4238-96dc-0572655e4da5
