### ISSUE TITLE
Button text does not clear on iOS using button.Text = "" or button.Text = null

### ISSUE THREAD

**Issue by barnasoba** [dotnet/maui#17128]
### Description

When trying to clear the text of a Button on iOS using .NET MAUI version 7.0.92, setting button.Text to an empty string "" or null does not clear the button's text. The same code works as expected on Android. As a workaround, I have to set button.Text = " ", adding a space, for it to work on both platforms.

### Steps to Reproduce

1. Create a Button with some text in a .NET MAUI app.
2. Attempt to clear the button's text using button.Text = "" or button.Text = null.
3. Observe that the text does not clear on iOS.

Expected Behavior:
Setting the Button text to an empty string or null should clear the text on both Android and iOS.

Actual Behavior:
The text does not clear on iOS.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue does not repro on iOS 16.4 **.NET 8**, Windows 11 and Android 13.0-API33 with below Project:
[17128.zip](https://github.com/dotnet/maui/files/12522261/17128.zip)

![ClearText](https://github.com/dotnet/maui/assets/97647558/ce36bd96-a525-404d-b49b-1da9005aa6b1)
