### ISSUE TITLE
[regression/8.0.0-preview.7.8842] Maui Hybrid App stuck on "Loading..." in release mode on Android

### ISSUE THREAD

**Issue by ShiftyTR** [dotnet/maui#17130]
### Description

Just start a project and release it without doing anything, it gets stuck in loading. If you open a normal Maui project and install a signalr client, it constantly connects and disconnects. It seems like there is a bug related to signalr.

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android

**Comment by samhouts** [comment]
@mkArtakMSFT I think this one is for your team?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This should be fixed in .NET 8 RC1 release.
Can you please download the latest SDK and try it out?

**Comment by ShiftyTR** [comment]
Yes, it looks solved. Thank you.
