### ISSUE TITLE
NullReferenceException in Platform.DidAppear on iOS when migrating from Xamarin Forms.

### ISSUE THREAD

**Issue by GalaxiaGuy** [dotnet/maui#17133]
### Description

I have a complicated Xamarin Forms app that I'm migrating to MAUI. It uses embedding and currently uses compatibility.

Shortly after launch, I'm getting a `NullReferenceException` in `Platform.DidAppear` (via `PlatformRenderer.DidAppear`).

Looking at the contents of `DidAppear`:
```csharp
internal void DidAppear()
{
    _animateModals = false;
    Application.Current.NavigationProxy.Inner = this;
    _animateModals = true;
}
```
it looks like `Application.Current.NavigationProxy` is `null`. Looking through the code I could not find anywhere where this gets set to a non-null value.

If I use reflection to set it (it is private), the exception goes away:

```csharp
private void SetNavigationProxy()
{
    var propertyInfo = typeof(Microsoft.Maui.Controls.Application).GetProperty("NavigationProxy");
    propertyInfo.SetValue(this, new NavigationProxy());
}
```

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jfversluis** [comment]
@GalaxiaGuy I see this has been a while, which also means that there are now newer .NET MAUI version available. Would you be able to confirm that this is still a problem for the current versions?

**Comment by GalaxiaGuy** [comment]
This no longer seems to happen for us in `8.0.10-nightly.10028`, however we have also since worked to remove a lot of compatibility reference so we may just be avoiding it.

**Comment by samhouts** [comment]
Okay, we'll close for now, but let us know if it comes back! Thanks!!
