### ISSUE TITLE
MediaElement Record Audio

### ISSUE THREAD

**Issue by r2d2Proton** [dotnet/maui#17144]
### Description

Allow MediaElement to record audio on the different platforms. If I understand correctly, the control can play and record video (mp4), and playback mp3. I do not see how to record mp3, or audio in general.

### Public API Changes

I do not know enough to answer.

### Intended Use-Case

It would be used in my app. At the moment on Windows I am using MCI commands; on Android I am using protected MediaRecorder mediaRecorder; and have not implemented iOS yet. . but headed there shortly.

**Comment by mattleibow** [comment]
I think this feature exists in the Maui Community Toolkit: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement
