### ISSUE TITLE
A new class created in Platform/Android folder of .NET MAUI project will have wrong namespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#17148]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/A-new-class-created-in-PlatformAndroid-/10311508)._

---
[severity:I'm unable to use this version]
When you create a .NET MAUI project, the namespace of the platform-specific classes will be just the root project namespace (e.g. MauiApp1).
Example: class MainActivity in Platform/Android will have namespace MauiApp1 if the project name is MauiApp1

When you create a new class in the folder, it will have incorrect namespace: MauiApp1.Platforms.Android because of the folder structure.

When this happens, you cannot add any classes from Mono.Android namespace in the code because the namespaces will conflict.

![image.png](https://aka.ms/dc/image?name=Be64d5d1c78624ba19cb8a1b75376dc10638145173214548139_20230315-234840-image.png&tid=e64d5d1c78624ba19cb8a1b75376dc10638145173214548139)

This is probably new behavior because I took the sample from the project https://github.com/TimoKinnunen/MauiXAMLBluetoothLE where the platform-specific class uses project root namespace and new .NET MAUI App project template does as well.

---
#### Feedback Bot on 3/15/2023, 10:59 PM: 

(private comment, text removed)
#### Feedback Bot on 7/2/2023, 07:53 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Unfortunately there isn't much we can do about it from our side. This is a feature of Visual Studio, I think you can disable it if you want, or just change the namespace when you create something new there. I'm not sure if we want to change the template for just this.

Sorry we couldn't be more helpful here.
