### ISSUE TITLE
Method not found: void Microsoft.Maui.Controls.TapGestureRecognizer.add_Tapped(System.EventHandler) in .Net MAUI targeting .Net 7

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#17147]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Method-not-found:-void-MicrosoftMauiCo/10448217)._

---
I am creating a .Net MAUI project in Visual Studio 2022 using .Net 7 and have implemented a TapGestureRecognizer.
I am getting the error "Method not found: void Microsoft.Maui.Controls.TapGestureRecognizer.add_Tapped(System.EventHandler)"

The line is :
AddHandler tgrSpellFormat.Tapped, AddressOf imgSpellFormat_Tapped

After researching this error. Someone else also had the same error and was instructed to roll back to .Net 6.
After doing so I no longer get this error. Does .Net 7 use a different way of adding a handler for Tapped?

Here is the link to the workaround until it becomes fixed in .Net 7:
https://github.com/enisn/UraniumUI/issues/74

---
#### darkmatter2001 on 8/23/2023, 07:53 AM: 

(private comment, text removed)
#### Feedback Bot on 8/23/2023, 06:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment]
This seems like it's an issue with mixing versions of packages that reference different versions of .NET MAUI. Probably some packages using .NET MAUI 6, 7, or even 8, which is not supported. All references must use the same version of .NET MAUI. We'll need a repro app to investigate any further.
