### ISSUE TITLE
Cannot directly type culture (e.g. 'en-US') for a CultureInfo property in .NET MAUI XAML

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#17146]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-directly-type-culture-eg-en-U/10238313)._

---
[severity:I'm unable to use this version]
Xaml extension is like
```csharp
// MAUI
public class StringsExtension : IMarkupExtension
{
	public string Key { get; set; }

	public CultureInfo Culture { get; set; } = CultureInfo.CurrentUICulture;

	public string ProvideValue(IServiceProvider serviceProvider) { /*code*/ }

	object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider) => ProvideValue(serviceProvider);
}
// WPF
public class StringsExtension : MarkupExtension
{
	public string Key { get; set; }

	public CultureInfo Culture { get; set; } = CultureInfo.CurrentUICulture;

	public override object ProvideValue(IServiceProvider serviceProvider) { /*code*/ }
}
```
and xaml:
```csharp

```
Xaml code `Culture='en-US'` works in WPF application. But in MAUI application, compiler reports
```
*.xaml(-1,-1): XamlC error XFC0009: No property, BindableProperty, or event found for "Culture", or mismatching type between value and property.
```

---
#### brandonstudio on 12/23/2022, 11:26 PM: 

(private comment, text removed)
#### Feedback Bot on 12/25/2022, 06:20 PM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 12/26/2022, 09:55 PM: 

(private comment, text removed)
#### brandonstudio on 12/27/2022, 03:59 PM: 

(private comment, text removed)
#### brandonstudio on 12/27/2022, 04:02 PM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 12/29/2022, 03:46 AM: 

(private comment, text removed)
#### Feedback Bot on 12/29/2022, 04:36 AM: 

(private comment, text removed)
#### Feedback Bot on 4/3/2023, 07:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
could you please update your bug report, the XAML snippet is missing so I don't get what you want. If I had to guess, you probably have to declare a converter for CultureInfo, and attribute the Culture property...
