### ISSUE TITLE
Validate MenuItem API is complete for Desktop MacCatalyst/WinUI

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#1715]
- [ ] https://github.com/dotnet/maui/issues/1716
 - [ ] https://github.com/dotnet/maui/issues/1717

**Comment by profix898** [comment]
I apologize for potentially hijacking this issue. I've been waiting for desktop menu item support to start migrating a XamarinForms app (with custom menu implementation) to MAUI. I hope that I can point out a few things which are inconsistent or missing in the current design from my perspective.

1. No support for hierarchical menus
You can not mix-and-match sub-menus and normal menu items inside of a `Menu` (see below).

2. No support for other types of menu items (toggle, radio, separator)
For proper desktop support, MAUI needs to (at least) support toggle menu items (true/false) and separators, both are supported with WinUI and macOS.

---

The following describes the implementation in MAUI (former XF) as it is today:
`Menu` contains two ObservableCollections `_menus` and `_items`. `Menu` itself implements `IList<Menu>` (backed by `_menu`), which essentially means that we can have a parent menu and any number of submenus. On the other hand, `_item` is wired for OnPropertyChanged and exposed via a public `Items` property, which allow each menu (level) to have a collection of menu items. However, it is clear from its design, that `Menu` is meant to be used either as a container for menu items (mostly on mobile) or container for submenus (but not both).
You can't control the actual layout of a fully hierarchical menu. Lets say you want to build a menu, which for example contains: first two entries = simple menu items, then a submenu, then another menu item, etc.

In my custom XF implementation, I used the following types to describe a menu:
- `class AppMenu : View, IList<Menu>` (-> container for app/window-level menu, can have any number of (sub-)menus, i.e. 'File', 'Edit', etc.)
- `class Menu : MenuItemBase, IList<MenuItemBase>` (-> a submenu, that can hold other MenuItemBase-derived menu items, incl. menu itself)
- `class MenuItem : MenuItemBase` (-> standard menu item)
- `class ToggleMenuItem : MenuItem` (-> same as MenuItem, but supports toggling (true/false))
- `class RadioMenuItem : MenuItem` (-> same as MenuItem, but implements item in a radio group)
- `class SeparatorMenuItem : MenuItemBase` (-> separator menu item)

### Windows Implementation: #1717
In WinUI the corresponding types are:
`MenuBar` (= AppMenu), `MenuBarItem` (= Menu), `MenuFlyoutSubItem` (= MenuItem), `ToggleMenuFlyoutItem` (= ToggleMenuItem), `RadioMenuFlyoutItem` (= RadioMenuItem), `MenuFlyoutSeparator` (= SeparatorMenuItem)

As you can see, there is a 1:1 relationship (between the native platform control and the XF view).
The biggest issue with the new handler design is that this (or any similar) inheritance structure should exists for the Controls as well as for the implementing handlers.

### MacOS Implementation: #1716
https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/
https://developer.apple.com/documentation/appkit/nsmenu
https://developer.apple.com/documentation/appkit/nsmenuitem
In AppKit the corresponding types are:
`NSMenu` (= AppMenu), `NSMenu` (= Menu), `NSMenuItem` (= MenuItem),
other menu item types a represented via properties on NSMenuItem, e.g. `isSeparatorItem=true` (Separator) or `state=on/off` (Toggle)

Not sure about Mac Catalyst equivalents (https://developer.apple.com/documentation/uikit/uicommand/adding_menus_and_shortcuts_to_the_menu_bar_and_user_interface).

---

It should be noted, that next to menu support, a desktop app most likely also needs an app/window-level toolbar.
In WinUI that is `CommandBar` (with `AppBarButton`, `AppBarToggleButton`, `AppBarSeparator`). These types are very similar to the menu items above. For that reason, in my XF implementation, I reused the MenuItemBase-derived types to construct the toolbar as well. So a toolbar could simply be implemented as `class Toolbar : View, IList<MenuItemBase>` (but without multiple sub-levels, i.e. items of type `Menu` are not allowed). I just want to point out here that app toolbar design most probably wants to take a unified approach for handling menu and toolbar (especially for implementing toggle or radio items).

---

_Note: I would be happy to help or test/review any implementation for MAUI preview 8. Let me know._

**Comment by Redth** [comment]
This is really awesome added context from your experience. Thank you for this!  Yes the issue title should really be changed to reflect that we aren't just validating the existing api but designing a spec for the api needed to properly support desktop scenarios.

**Comment by profix898** [comment]
Just wondering: Do you plan on including **Desktop Menu Items** in the first stable release? Otherwise, its likely to cause a breaking change later on ...

**Comment by davidbuckleyni** [comment]
To be fair @Redth u guys should no what we need as developers in desktop and mac apps in terms of menus the additional context the others developers have rasied our vittle for business apps moving forward not every app is mobile and comptable with the shell ethos. 

We will also need 
Menu Bar
ribbon bar for office style menus 

Status bars yes their still used allot. 

Tooltips as well 
mutiple document support. 

I dont see how all this be ready for q2

**Comment by davidbuckleyni** [comment]
I feel ur pain @profix898 their ignoring the mass desktop market in favour of shell which at present is not good enough for our needs.

**Comment by PureWeen** [comment]
@profix898 I started working on this a bit here
https://github.com/dotnet/maui/issues/4640

I have a semi working implementation here on WinUI
https://github.com/dotnet/maui/tree/menubar

It looks like we came to similar conclusions with the API's

```
MenuBar (= AppMenu), MenuBarItem (= Menu), MenuFlyoutSubItem (= MenuItem), ToggleMenuFlyoutItem (= ToggleMenuItem), RadioMenuFlyoutItem (= RadioMenuItem), MenuFlyoutSeparator (= SeparatorMenuItem)
```

I mapped things a little bit different than you've described here mainly because
- MenuFlyoutSubItem - I don't think you can map this to `MenuItem` because `MenuFlyoutSubItem` doesn't have a command property (AFAICT). It's only used to create a submenu
- [MenuFlyoutItem ](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.menuflyoutitem?view=winui-3.0) - Maps a bit more naturally to `MenuItem`

**Comment by profix898** [comment]
@pureween: Thanks for letting me know! If you agree, I can try to take this the next step. Add more features, add a demo page/window to the samples project etc. I'm currently quite busy with my daytime job, but I'd be happy to work on this a little in the evenings. Let me know. In any case, I will come back to you with more detailed feedback in the next few days.

BTW: I noticed that several 'Core' samples (from the Samples gallery) still do not work on WinUI, including ActionSheets, Brushes, FlyoutPage, NewWindow (= exception). Not sure that is due to me compiling MAUI locally or because it's generally broken.

**Comment by PureWeen** [comment]
@profix898 I wouldn't yet. The spec/work there is still in progress. Once we have a more final idea for the APIs though :-)

A lot of the WinUI parts will work better with P13. New Window on WinUI is a bit of a weird one because it's not fully enable on the WinUI side with stable release of WinUI so they currently just throw an exception if you use it.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/4640

**Comment by davidbuckleyni** [comment]
> @profix898 I started working on this a bit here #4640
> 
> I have a semi working implementation here on WinUI https://github.com/dotnet/maui/tree/menubar
> 
> It looks like we came to similar conclusions with the API's
> 
> ```
> MenuBar (= AppMenu), MenuBarItem (= Menu), MenuFlyoutSubItem (= MenuItem), ToggleMenuFlyoutItem (= ToggleMenuItem), RadioMenuFlyoutItem (= RadioMenuItem), MenuFlyoutSeparator (= SeparatorMenuItem)
> ```
> 
> I mapped things a little bit different than you've described here mainly because
> 
> * MenuFlyoutSubItem - I don't think you can map this to `MenuItem` because `MenuFlyoutSubItem` doesn't have a command property (AFAICT). It's only used to create a submenu
> * [MenuFlyoutItem ](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.menuflyoutitem?view=winui-3.0) - Maps a bit more naturally to `MenuItem`

U are a legend
