### ISSUE TITLE
[regression/8.0.0-rc.1.9171] Entire page glitches when using Shell

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#17157]
### Description

When horizontally resizing the window, the page disappears sometimes when the screen gets narrow-ish.

https://github.com/dotnet/maui/assets/1096616/50fd4eb1-b4ad-43bd-922a-f9d34edd82dc

This does not appear to happen with `NavigationPage` but sometimes it glitches for a split millisecond and may be the WASDK something.

### Steps to Reproduce

1. File | New | Maui App
2. Replace the contents with anything (or use what is on screen) - I used a plain button
3. Resize to about 200px wide
4. during the resize, the page should flicker wildly

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp129.MainPage">
    <Button />
</ContentPage>
```

### Link to public reproduction project repository

N/A

### Version with bug

8.0.0-rc.1.9121

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

Windows

**Comment by mattleibow** [comment]
If I lock the flyout, it appears to start glitching when the window width is 2x the flyout or the page is the same width as the flyout:

![image](https://github.com/dotnet/maui/assets/1096616/47c0be4d-a75f-47b4-92eb-445ce7cd3bce)

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 3.0. Repro on Windows 11 .NET 8(8.0.0-rc.1.23420.5) with below Project:
[17157.zip](https://github.com/dotnet/maui/files/12545321/17157.zip)

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/17724
