### ISSUE TITLE
Not Able to find .Net Multi-Platform Apps UI 

### ISSUE THREAD

**Issue by dhiliphen** [dotnet/maui#17179]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

I am not able to find .Net Multi-Platform Apps UI 
![SS_MAUI_notfound](https://github.com/dotnet/maui/assets/311456/d9988b55-9f44-4c9a-bc14-aff901b45bed)

**Comment by moljac** [comment]
@dhiliphen 

Can you provide more info, please? Visual Studio version, dotnet version etc.

**Comment by dhiliphen** [comment]
Sorry, Microsoft Visual Studio Community 2022 (64-bit) - Current Version => 17.1.5
.Net Version => 4.8.09032

**Comment by jfversluis** [comment]
This is stale by now, hoping your figured it out by now and are happily creating .NET MAUI apps!

If not, please open a new issue letting us know.
