### ISSUE TITLE
HTTP files do not appear to work in MAUI

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#17183]
### Description

Created an HTTP file in my MAUI Dotnet 7 project and tried to send the request. Nothing happened.

I tested the same file in another project type and it works.

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by affableashish** [comment]
Please post a reproducible example project.

**Comment by moljac** [comment]
@genifycom 

Thanks for the feedback.

`*.http` files are used to test and document for ASP.net Core projects, which are different from MAUI project.

https://learn.microsoft.com/en-us/aspnet/core/test/http-files

My suggestion - close this issue (not bug or not planned)

**Comment by jfversluis** [comment]
Like @moljac points out, I think these only work in ASP.NET projects at this time. If you also want them to work for other types of projects it's best to open a feature request through Visual Studio.

Thanks!

**Comment by genifycom** [comment]
I would point out that MAUI projects are even more dependent on API requests that many other ASP.NET core project types.

**Comment by moljac** [comment]
> I would point out that MAUI projects are even more dependent on API requests that many other ASP.NET core project types.

Good point, but from the docs:

> .http file editor provides a convenient way to test ASP.NET Core projects, especially API apps.

some authors add "test and document" API apps. I use them to test and document REST request in my MAUI side projects, but from VSCode:

https://marketplace.visualstudio.com/items?itemName=humao.rest-client

Testing and documenting REST APIs is not MAUI responsibility.
