### ISSUE TITLE
MAUI Blazor android wont go after splash page at release version (.NET 8 preview 7)

### ISSUE THREAD

**Issue by sarsey-walker** [dotnet/maui#17184]
### Description

I created a new .NET MAUI Blazor app, added a minimal customization android. Debug version works fine, but release version stop after splash screen.

I changed to .net 7 and worked just fine.

### Steps to Reproduce

1. Create a new project MAUI blazor hybrid app
2. Run as debug at android emulator. Everything works fine 'til here
3. Change to release an try to run.
4. First will there this erros
![image](https://github.com/dotnet/maui/assets/54552722/224b7234-dfa8-4242-b43c-5f33ae0d6241)
5. Delete `android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round"` at `Androidmanifest.xml` and run again
6. it will be stuck here
7. 
![image](https://github.com/dotnet/maui/assets/54552722/d1191271-fb75-4952-9b1c-12909ed25c12)

### Link to public reproduction project repository

https://github.com/sarsey-walker/TodoApp

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.92

### Affected platforms

Android

**Comment by sarsey-walker** [comment]
Fix typo

**Comment by sarsey-walker** [comment]
Making some tests here, I noticed that it only happens when "Enable trimming" is enabled `<PublishTrimmed>True</PublishTrimmed>` 

When testing at debug mode the linker crashes. Searching around I found https://github.com/mono/SkiaSharp/issues/2327 . Using `<AndroidLinkResources>false</AndroidLinkResources>` does solve my problem. Must be another regression.

**Comment by Eilon** [comment]
@sarsey-walker - you could be running into an issue in .NET 8 Preview 7 with Blazor Hybrid, which has a workaround described here: https://github.com/dotnet/maui/issues/16609#issuecomment-1672166849

Could you try that out and let us know if it resolves the issue?

**Comment by Eilon** [comment]
@sarsey-walker ah OK then it does seem like the trimming is perhaps trimming out part of the app that is required to run. I think for now the best thing is to disable trimming by setting `<PublishTrimmed>True</PublishTrimmed>` in the CSPROJ file as you have already tried. There could be some fixes in the upcoming preview that make this work better by default.

**Comment by sarsey-walker** [comment]
Ok, lets wait. 
Can u say something about the error with `android:icon="@mipmap/appicon"` ?

**Comment by mattleibow** [comment]
Now that we have RC 2.1 out, is this issue still happening? If you disable trimming, did it work?
