### ISSUE TITLE
Android AAB file > 150 M limitation on Google Play Console

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#17191]
### Description

Is there any workaround for .net MAUI apps where the Android AAB file ends up larger than 150 MB (the Google Play Console limit)? I can easily split my app into a < 150M AAB and a zip file with data only, but cannot find any method equivalent to the old [APK Expansion File] approach to follow. 
There is something like [Integrated asset delivery], but I cannot find anything on how to implement this under Visual Studio .Net Maui.
I've searched the web for suggestions but cannot find any. Thats why I'm posting this as an issue.
Some help shall be much appreciated. I'm sure I am not the only one with this problem. If someone can point me to some solution I'm sure many will benefit by that.
Thanks

### Steps to Reproduce

It's a possible shortcoming. No need to reproduce

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 - API 31, Android 11 = API 30

### Did you find any workaround?

No

**Comment by jonathanpeppers** [comment]
@dellis1972 is there a way to do this today? For things like image assets or raw files?

* https://github.com/xamarin/xamarin-android/pull/5890

I remember you had an example project somewhere?

**Comment by dellis1972** [comment]
yes its at https://github.com/infinitespace-studios/XamarinLegacyDynamicAssetsExample.
Its not been updated fo .net 7 but it should mostly work exactly the same way.

**Comment by dellis1972** [comment]
I can probably put together a pure Maui sample if that is someting you might need @PureWeen ? Might be useful for documentation.

**Comment by dellis1972** [comment]
@hbraasch 

So I put together this sample for you https://github.com/infinitespace-studios/MauiAndroidAssetPackExample. 
It works with the `Install Time` asset packs on android.  If you want to use Dynamic asset packs (which are downloaded on demand) you will need to do some platform specific api calls. 

The sample should also work for other platforms. On those it is setup to include all the "assets" from the "AssetFeature" project as typical `MauiAsset` items. So you should be able to put all your large assets in that AssetFeature project.

**Comment by hbraasch** [comment]
@dellis1972 
Thanks. I'll have a look and see if I understand it. Regards

**Comment by hbraasch** [comment]
@dellis1972 
Thanks a lot. It works GREAT!! And thanks for the sample MAUI project. I definitely would not have grasped it if it wasn't for the project.
Much appreciated.

**Comment by dellis1972** [comment]
@hbraasch no problem, I'll close this issue as there is a sample available. Please re-open if you need more info on this.
