### ISSUE TITLE
ListView Visibility Problem in .Net 8.0

### ISSUE THREAD

**Issue by OmidTavana** [dotnet/maui#17195]
### Description

I have a Listview and its visibility by default is set to "False".
I want to show it when I'm focusing on an Entry.
It works fine when Listview visibility is set to "True" by default.
But when its visibility is false and I'm trying to set it to true in code-behind items are still hidden or just not rendered.

More information: I'm using Shell and I have this issue in both debug and release mode

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android

### Affected platform versions

Android API 34

**Comment by PureWeen** [comment]
Fixed by https://github.com/dotnet/maui/pull/16941
