### ISSUE TITLE
[Question] Is this project / repo updated?

### ISSUE THREAD

**Issue by mf-RDP** [dotnet/maui#172]
## Summary

Hi,

it appears this Repo ist currently not under maintainance?
Can you please explain whether MAUI project plans still are in place, the repo has moved or something?

Many Thanks
;)

**Comment by Happypig375** [comment]
MAUI is equivalent to Xamarin.Forms 6 for .NET 6. Xamarin.Forms 5 is not even out yet, so why would you expect activity here?

**Comment by mf-RDP** [comment]
There was quite some activity in May when MAUI was announced. See commits. 
So, just hopefully waiting for a short stmt from MS ;)

**Comment by Happypig375** [comment]
Those commits mainly change the ReadMe, Code of Conduct, License and Contributing files, i.e. mainly repo management. Nothing related to the actual framework.

**Comment by jfversluis** [comment]
I think this will answer your question: https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap#july-15-2020-pull-request-policy-changes

You will see a lot of action in this repo pretty soon :)

**Comment by mf-RDP** [comment]
thanks
