### ISSUE TITLE
Setting the `Style` property using triggers within a Style resource freezes the UI

### ISSUE THREAD

**Issue by SotoiGhost** [dotnet/maui#17202]
### Description

Having a Style resource, using triggers to set the `Style` property freezes the UI.

### Steps to Reproduce

1. Copy/paste the following Styles anywhere of your app:

    ```xml
        <Style x:Key="AP_ButtonStyle" TargetType="Button">
            <Setter Property="TextColor" Value="White" />
            <Setter Property="FontSize" Value="16" />
            <Setter Property="CornerRadius" Value="4" />
            <Setter Property="TextTransform" Value="Uppercase" />
        </Style>

        <Style x:Key="SecondaryButtonStyle" TargetType="Button" BasedOn="{StaticResource AP_ButtonStyle}">
            <Setter Property="Background" Value="Green" />
        </Style>

        <Style x:Key="SecondaryButtonDisableStyle" TargetType="Button" BasedOn="{StaticResource AP_ButtonStyle}">
            <Setter Property="Background" Value="Black" />
            <Setter Property="TextColor" Value="Gray" />
        </Style>

        <Style x:Key="SecondaryButtonTriggersStyle" TargetType="Button">
            <Style.Triggers>
                <Trigger TargetType="Button"
                        Property="IsEnabled"
                        Value="True">
                    <Setter Property="Style" Value="{x:StaticResource SecondaryButtonStyle}" />
                </Trigger>
                <Trigger TargetType="Button"
                        Property="IsEnabled"
                        Value="False">
                    <Setter Property="Style" Value="{x:StaticResource SecondaryButtonDisableStyle}" />
                </Trigger>
            </Style.Triggers>
        </Style>
    ```

2. Add the style to a button:

    ```xml
    <Button
        ...
        Style="{StaticResource SecondaryButtonTriggersStyle}" />
    ```

3. Run the app and observe the bug

### Link to public reproduction project repository

https://github.com/SotoiGhost/MauiSandbox/tree/Style-triggers-issues

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 16, Android 13

### Did you find any workaround?

Noup…

**Comment by PureWeen** [comment]
Hi @SotoiGhost !!!

Does this also break on .NET 8 ?

**Comment by SotoiGhost** [comment]
Hi @PureWeen! I tested this issue using `8.0.100-preview.7.23376.3` and the UI does not get frozen. The enabled style is being applied but not the disabled one. Want me to open a new issue or can I rename the current one?

**Comment by jaosnz-rep** [comment]
Verified this issue with Visual Studio Enterprise 17.10.0 Preview 1.0, not repro on iOS and Android platforms with sample project. 
https://github.com/SotoiGhost/MauiSandbox/tree/Style-triggers-issues
