### ISSUE TITLE
TypeConverterAttribute bug with custom type converter

### ISSUE THREAD

**Issue by AidarNurmukhametov** [dotnet/maui#17203]
### Description

I guess TypeConverterAttribute is not working at all with user-defined converters. See attached repo. I can't find any code in [BindableProperty.cs](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/BindableProperty.cs) that reads data from this attribute, so it is always ignored. As a result, only predefined converters (not sure) and implicit operators are used.

I really not sure this worked ever before, so I don't consider this as regression, but you can change this if I'm mistaken. 

### Steps to Reproduce

Run project, notice that [assertion](https://github.com/AidarNurmukhametov/TypeConverterBug/blob/12fded83f3d5cf7c218873e3f47b53f45b7dc4e8/MainPage.xaml.cs#L9) failed. 

### Link to public reproduction project repository

https://github.com/AidarNurmukhametov/TypeConverterBug

### Version with bug

8.0.0-preview.7.8842
7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Did you find any workaround?

Creating custom types that have implicit operators from assignable types to target property type

**Comment by PureWeen** [comment]
@StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
we have tests showing custom converter working. I have to look at the sample provided

**Comment by StephaneDelcroix** [comment]
you're doing
```csharp
		ThatView.SetValue(CustomView.ColorProperty, 0);
```

which doesn't invoke the converter, and isn't supposed to.

TypeConverters are there for Xaml scenarios, when you do
```xaml
            <CustomView Color="stringvalue" />
```

and in some cases for binding too
