### ISSUE TITLE
XPlat Page Lifecycle

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#1721]
Adding Lifecycle methods
- [x] Appearing
- [x] Disappearing
- [ ] ~NavigatingTo~
- [x] NavigatingFrom
- [x] NavigatedTo
- [x] NavigatedFrom

`// TODO: Validate implementation`

**Comment by rachelkang** [comment]
Note to future self: Review platform-specific APIs, .NET MAUI implementation, and test

**Comment by rachelkang** [comment]
Also consider https://github.com/dotnet/maui/issues/999
