### ISSUE TITLE
Mac Catalyst Binding Project does not work with MAUI without manual edit of project file

### ISSUE THREAD

**Issue by scottkdavis** [dotnet/maui#17217]
### Description

After creating a new (blank) MAUI application and adding a new (blank) Mac Catalyst binding project I receive this error.

Project [csproj file] targets 'net7.0-maccatalyst'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v7.0'.

However, this is the target of my MAUI app (default from VS, not changed)

`		<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		
		
`

By default, binding projects should be excluded from the platforms to which they do not apply, or the error message should be improved to indicate which platforms are a problem.

### Steps to Reproduce

1. Create new MAUI app. Select .Net 7.0 framework
2. Add new project, Mac Catalyst Binding Library
3. Reference binding library from MAUI app
4. Build

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac OS Ventura 13.5

### Did you find any workaround?

You must manually edit the project file to include the condition to only include the binding library if TargetFramework is maccatalyst, or remove android and ios targets from the top of the file.

`	<ItemGroup>
	  <ProjectReference Condition="'$(TargetFramework)'=='net7.0-maccatalyst'" Include="..\TestMauiMacCatBinding\TestMauiMacCatBinding.csproj" />
	</ItemGroup>
`

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-macios#18948
