### ISSUE TITLE
blazor hybrid blazorwebview mixed mode http content and untrusted ssl certificate problem

### ISSUE THREAD

**Issue by serkansmg** [dotnet/maui#17219]
hi my problem is different. 
i have a video tag and android app works in local intranet. 
my server is ubuntu and using for hls streaming.
when trying with hls.js stream http://192.168.195.176:8080/hls/stream.m3u8
because of http , blazorwebview does not allow it to load.

then i installed letsencrypt certificate with dns challenge and got certificates for ex: xxx.xyz domain

now when i hls stream in blazorwebview with:
https://192.168.195.176/hls/stream.m3u8
certificates are untrusted.. so i again cant stream it.. 

i tried network_security_config.xml and applied it to android manifest as:
android:usesCleartextTraffic="true" android:networkSecurityConfig="@xml/network_security_config"

and the xml:
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
	<domain-config cleartextTrafficPermitted="true">
		<domain includeSubdomains="true">192.168.195.176</domain>
	</domain-config>
	<base-config>
		<trust-anchors>
			<!-- Trust preinstalled CAs -->
			<certificates src="system" />
			<!-- Additionaly trusted user added CAs -->
			<certificates src="user"/>
		</trust-anchors>
	</base-config>
</network-security-config>

```
not worked.. 
then i tried 

```
        private void blazorWebView_BlazorWebViewInitialized(object sender, Microsoft.AspNetCore.Components.WebView.BlazorWebViewInitializedEventArgs e)
        {
#if ANDROID
            
            if(e.WebView.Settings.MixedContentMode != Android.Webkit.MixedContentHandling.AlwaysAllow)
            {
                e.WebView.Settings.MixedContentMode = Android.Webkit.MixedContentHandling.AlwaysAllow;
                
          }
#endif
        }

```
again not worked for both http and https.
so there are 400 android clients in local network which does not have access to internet. 
i have to serve hls streaming.. 
help needed

**Comment by jfversluis** [comment]
> hi my problem is different.

Different from what exactly? And why do you think it's different?

Do you have some kind of reproduction?

**Comment by serkansmg** [comment]
> > hi my problem is different.
> 
> Different from what exactly? And why do you think it's different?
> 
> Do you have some kind of reproduction?



> 

I mentioned from another thread, it is different than that problem. That guy having problem with images with http. 
He can view image with several different methods but  mine is about video tag.
Yes you can reproduce it.. Just add a video tag, add any http video or video stream in local intranet. You will see it.. 
Or, serve it with kestrel and serve with https and ıp.

**Comment by affableashish** [comment]
@serkansmg Please post a reproducible example project.

**Comment by mkArtakMSFT** [comment]
@serkansmg this doesn't seem to be Blazor specific. Can you try to reproduce this with a pure MAUI WebView app and see if it works or fails again?

What seems to be the issue here is that the certificate was generated for a specific host and you're trying to access it using IP Address and obviously getting host mismatch error. So mapping the IP address to the hostname for which the certificate was provided in the hosts file (or whatever similar one there in Ubuntu) should fix this problem.
