### ISSUE TITLE
Memory leak with GraphicsView in windows

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#17214]
### Description

In our custom control, we use multiple Graphics Views, and when users swipe on these views, we initiate a redraw operation by invalidating them. However, we've observed a noticeable increase in committed memory size in the Task Manager after performing these redraws, despite no apparent memory changes in Visual Studio Diagnostics.

In the provided sample, we perform redraw operations on six views. Upon reviewing the attached video, you'll notice a memory increase of 200 MB for each invalidate call.
This memory increase is directly correlated with the canvas size we use. The larger the canvas we utilize, the more memory is consumed.

This memory does not occur when examined in the performance profiler.

### Steps to Reproduce

1. Run the attached sample.
2. Open Task Manager.
3. Click the invalidate button and notice the increase in Task Manager committed memory

https://github.com/dotnet/maui/assets/92788387/b4642cbb-7127-445a-a1e3-31ed49abaceb

### Link to public reproduction project repository

https://github.com/KarthikRajaAKR/Samples/tree/main/MemoryLeak

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

No

**Comment by MuniappanSubramanian** [comment]
Any update on this?

**Comment by robivin** [comment]
Any update?

**Comment by danielancines** [comment]
Any updates?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 5. Can repro on Windows platform with sample project.
https://github.com/KarthikRajaAKR/Samples/tree/main/MemoryLeak
