### ISSUE TITLE
[regression/8.0] Unable to access Implicit Styles

### ISSUE THREAD

**Issue by Tamilarasan-Paranthaman** [dotnet/maui#17212]
### Description

I have a custom control and would like to retrieve the style that is set implicitly for use within my control. I have achieved this as follows. 

This was working as expected in '.Net7'.

<img width="659" alt="image" src="https://github.com/dotnet/maui/assets/93904422/7772b8c5-c838-48b8-9ab7-668b860648ff">

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiApp1"
             x:Class="MauiApp1.MainPage">

    <ContentPage.Resources>
        <Style TargetType="local:CustomButton">
            <Setter Property="HorizontalOptions" Value="Center" />
            <Setter Property="VerticalOptions" Value="Center" />
            <Setter Property="BackgroundColor" Value="Bisque" />
            <Setter Property="FontSize" Value="18" />
        </Style>
    </ContentPage.Resources>

    <local:CustomButton
                Text="Hello World!!"
                FontSize="18"
                HorizontalOptions="Center" />

</ContentPage>
```

```C#
using Microsoft.Maui.Controls;
using System.Reflection;

namespace MauiApp1
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }
       
    }

    public class CustomButton : Button
    {
        public CustomButton()
        {
            this.Clicked += CustomButton_Clicked;
        }

        private void CustomButton_Clicked(object sender, EventArgs e)
        {
            var dynamicResources = (Dictionary<BindableProperty, string>)typeof(Element)?.GetRuntimeProperties()?.FirstOrDefault(x => x.Name == "DynamicResources")?.GetValue(this);
            var key = dynamicResources?.Keys.FirstOrDefault();
            var style = (Style)this.GetValue(key);
        }
    }
}
```

**However, in .NET 8, it's not functioning as expected. Facing the following issue related to SetterSpecificity.**

<img width="685" alt="image" src="https://github.com/dotnet/maui/assets/93904422/35cf5e15-7bb7-40f7-b383-28078de73fd4">

<img width="685" alt="image" src="https://github.com/dotnet/maui/assets/93904422/44f2d884-d764-4be0-b7ff-8867ba6711b6">

### Steps to Reproduce

1. Run the attached file.
2. Click the Hello World!! button.

**Sample: [Sample](https://github.com/dotnet/maui/files/12522499/Sample.zip)**

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows

**Comment by samhouts** [comment]
@StephaneDelcroix ?

**Comment by StephaneDelcroix** [comment]
well, it looks like your code that uses reflection to use internal API fails. doesn't look like a bug to me

**Comment by Tamilarasan-Paranthaman** [comment]
@StephaneDelcroix - In .NET 7, we utilized this method to identify the implicit style for the control. However, it is no longer functional in .NET 8. Is there an alternative approach for determining whether the control possesses an implicit style? How can we achieve this in .NET 8?

**Comment by StephaneDelcroix** [comment]
I'd get the element Style as a MergedStyle, and see if ImplicitStyle is set. should be possible using reflection
