### ISSUE TITLE
[Bug]  "HelloMaui" Errors in VS22 'Out of Box' 

### ISSUE THREAD

**Issue by dgerding** [dotnet/maui#1723]
### Description
Following the "[Build your first .NET MAUI app](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=windows)" 

### Steps to Reproduce

1. Run "dotnet workload install maui" in elevated powershell
2. Run "dotnet new maui -n HelloMaui" in powershell
3. Open Visual Studio 17 Preview 2

### Expected Behavior
Solution available to build and run.

### Actual Behavior
* Get several UI indications of failed project loading / parsing (see screens)
* Error log (attached) 

Solution says it is building without errors.
Will not run.

### Basic Information
[VsProjectFault_f273f627-1dcf-43c4-8ea9-41c4c14c16a2.failure.txt](https://github.com/dotnet/maui/files/6833081/VsProjectFault_f273f627-1dcf-43c4-8ea9-41c4c14c16a2.failure.txt)

- Version with issue:
- Last known good version:
- IDE: Visual Studio 17 Preview 2
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![ide-2021-07-16_14-40-41](https://user-images.githubusercontent.com/523279/126002165-a5909a39-71d5-4675-bc80-100c208d3821.png)

**Comment by pjmagee** [comment]
You still need the MSIX extension installed and then you need to install the dotnet workflow maui.

**Comment by dgerding** [comment]
Re-running maui-check allowed me to build and run. However, VS22 still reported project problems and error log file on initial open.
