### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Georgeochana17** [dotnet/maui#17249]

**Comment by drasticactions** [comment]
There's not enough info here to know

- What platform you're running on (Windows, macOS)
- Which target framework and runtime your running (net6.0, net7.0, net8.0)

We need more information or a reproduction project for what you're doing (if anything beyond deploying the template) that could be at fault.

CC @rolfbjarne, if you've seen this stack trace before?

**Comment by rolfbjarne** [comment]
This looks truncated, please provide a complete [binlog](https://aka.ms/binlog).
