### ISSUE TITLE
Webview on Android devices don't send __RequestVerificationToken to MVC endpoint with [ValidateAntiForgeryToken] annotation

### ISSUE THREAD

**Issue by b-j-fellowmind** [dotnet/maui#17269]
### Description

We have a MVC website that is shown in a webview. 
The MVC post endpoints are annotated with [System.Web.Mvc.ValidateAntiForgeryToken]

When testing on IOS physical device or Android emulator the endpoints work. 
IIS logs show that __RequestVerificationToken is part of the request.

When testing on physical Android device the endpoint gives an error.
IIS logs show that __RequestVerificationToken is **not** part of the request.

### Steps to Reproduce

1) Create a MVC website with a POST endpoint annotated with [System.Web.Mvc.ValidateAntiForgeryToken]
2) Create a MAUI app with a webview that show the MVC site
3) Call the Post endpoint on a **physical IOS device** and it works
4) Check IIS log for MVC website to verify that __RequestVerificationToken is in the request
5) Call the Post endpoint on a **physical Android device** and you get an error
6) Check IIS log for MVC website to verify that __RequestVerificationToken is missing from request

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 Physical device

**Comment by drasticactions** [comment]
If you try creating a .NET Android app that doesn't use the MAUI UI Framework (`dotnet new android`), add a webview, and load the site, does the same thing happen?

**Comment by b-j-fellowmind** [comment]
It seems the problem is related to CookieContainer.

MVC controller: 

```
public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostToMe(MyModel model)
        {
            return View(model);
        }
    }
```

MVC view:
```
using (Html.BeginForm("PostToMe", "Home", FormMethod.Post))
    {
        Html.AntiForgeryToken()
        Html.TextBoxFor(m => m.MyValue)
    }
```

MAUI view:
`<WebView Source="{Binding Url}" Cookies="{Binding CookieContainer}" />`

MAUI viewmodel:
```
[ObservableProperty]
public string _url;

[ObservableProperty]
public CookieContainer _cookieContainer;
...
...
CookieContainer = new CookieContainer();
Url = "**MVCSITE**";
```

If Cookies="{Binding CookieContainer}" is removed from the MAUI webview, __RequestVerificationToken is posted to the endpoint. 
If Cookies is in the webview __RequestVerificationToken **is not** posted to the endpoint. 

In out case we need the CookieContainer as we have authentication cookies in it. 

It works on a .NET Android app that doesn't use the MAUI UI Framework but it is tested without CookieContainer.
