### ISSUE TITLE
MAUI Autogenerate icons for Mac Catalyst & iOS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#17279]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Autogenerate-icons-for-Mac-Catalyst/10457675)._

---
It is great that you have simplified the process of generating the icons for cross platform. I have added my gficon.svg to Resources\AppIcon\ and in my .csproj file I have adjusted the MauiIcon reference as follows:
```<MauiIcon Include="Resources\AppIcon\gficon.svg"/>``` 
I have also tried:
```<MauiIcon Include="Resources\AppIcon\gficon.svg" ForegroundFile="Resources\AppIcon\gficon.svg" Color="#FFFFFF"/>```

I want just the icon with a transparent bg to appear in the taskbar in Windows 11.  But in Mac & iOS Apple does not like the transparent bg so it needs the white BG.

So when I build my application I see the iconset gets autogenerated and placed in the Assets.xcassets folder which I see referenced in Platforms\MacCatalyst\info.plist.  I adjusted that reference to be:
```
<key>XSAppIconAssets</key>
<string>Assets.xcassets/gficon.appiconset</string>
```

But I cannot figure out how to get the transparent icon in windows and the non transparent in mac?

---
#### Feedback Bot on 9/4/2023, 08:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment]
For this, you just need to use conditions: https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2022

So your csproj would be something like:

```xml
<MauiIcon Include="Resources\AppIcon\gficon.svg" ForegroundFile="Resources\AppIcon\gficon.svg" Color="#FFFFFF"  Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'"/>
<MauiIcon Include="Resources\AppIcon\gficon.svg" ForegroundFile="Resources\AppIcon\gficon.svg" Color="#FFFFFF"  Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'windows'"/>
```
