### ISSUE TITLE
Windows: Connectivity check sometimes return NetworkAccess.Unknown

### ISSUE THREAD

**Issue by unombun** [dotnet/maui#17270]
### Description

On Windows checking connectivity returns incorrect value of NetworkAccess.Unknown.

There is this already closed issue: https://github.com/dotnet/maui/issues/9972

But this for sure is not fixed because I can still reproduce it.

### Steps to Reproduce

Here is the tricky part. I cannot provide any particular repro steps. In my app this can reproduce in some particular screens, in other happens only sometimes. 

I tried create a demo sample app but I could not reproduce there.
Of course I tried calling on the main thread the check as a suggestions made in the https://github.com/dotnet/maui/issues/9972. But sometimes it works, sometimes not.

It happens also with .Net 8 - preview 7.8842

### Link to public reproduction project repository

No sample

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No

### Relevant log output

```shell
Exception thrown at 0x00007FFB8C31CF19 (KernelBase.dll) : The application called an interface that was marshalled for a different thread.
```

**Comment by samhouts** [comment]
Thank you, we'll take a look at this. We'll see if we can come up with a reproduction on our side for now.

**Comment by BenBtg** [comment]
Repro sample confirmed in this repo https://github.com/breenbob/MauiWindowsConnectivityIssue

**Comment by jsuarezruiz** [comment]
Related with https://github.com/microsoft/WindowsAppSDK/issues/2965

**Comment by HelenMamalaki** [comment]
Copy of same comment posted #2965 
I am having the same issue:
**Target framework:** net7.0-windows10.0.19041.0

      "Microsoft.Maui.Dependencies/6.0.312": {
        "type": "package",
        "dependencies": {
          "Microsoft.Graphics.Win2D": "1.0.3.1",
          "Microsoft.Maui.Graphics": "6.0.300",
          "Microsoft.Maui.Graphics.Win2D.WinUI.Desktop": "6.0.300",
          "Microsoft.WindowsAppSDK": "1.0.3"
        }
[project.assets.json](https://github.com/microsoft/WindowsAppSDK/files/13168204/project.assets.json)

**Laptop running:** Windows 10 Enterprise 19045.3570

I can't keep calling my fetch data API service on the Main thread as it blocks the UI thread - this seems like a major issue.
![image](https://github.com/microsoft/WindowsAppSDK/assets/4314194/35ccd083-4779-407e-8287-014cdec67034)

**Comment by Foda** [comment]
> Copy of same comment posted #2965 I am having the same issue: **Target framework:** net7.0-windows10.0.19041.0
> 
> ```
>   "Microsoft.Maui.Dependencies/6.0.312": {
>     "type": "package",
>     "dependencies": {
>       "Microsoft.Graphics.Win2D": "1.0.3.1",
>       "Microsoft.Maui.Graphics": "6.0.300",
>       "Microsoft.Maui.Graphics.Win2D.WinUI.Desktop": "6.0.300",
>       "Microsoft.WindowsAppSDK": "1.0.3"
>     }
> ```
> 
> [project.assets.json](https://github.com/microsoft/WindowsAppSDK/files/13168204/project.assets.json)
> 
> **Laptop running:** Windows 10 Enterprise 19045.3570
> 
> I can't keep calling my fetch data API service on the Main thread as it blocks the UI thread - this seems like a major issue. ![image](https://private-user-images.githubusercontent.com/4314194/278311529-35ccd083-4779-407e-8287-014cdec67034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyOTkyMTUsIm5iZiI6MTcwMTI5ODkxNSwicGF0aCI6Ii80MzE0MTk0LzI3ODMxMTUyOS0zNWNjZDA4My00Nzc5LTQwN2UtODI4Ny0wMTRjZGVjNjcwMzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMjMwMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWRkMmQ5MDlhMzJmYzJhYmNjNmY5NzdlOGJiNzc0YTc4YTc0Y2E2NmI2NzVjMzQzOTI2NWY4MDkwZjM2YWNhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WvD_1seyJvSjp3hl7DbeigG3NLap3aQTcyxYsWgf0FE)

Can you give me a small reproduceable sample? I'm having a difficult time with this.

**Comment by damienaicheh** [comment]
Hi @Foda the repro sample provided above is not enough ? https://github.com/dotnet/maui/issues/17270#issuecomment-1717572125 and this one https://github.com/breenbob/MauiWindowsConnectivityIssue

**Comment by Foda** [comment]
Update: finally able to repro on latest w/ Win10 :)

**Comment by samhouts** [comment]
bad bot!
