### ISSUE TITLE
[Bug] maui-check -->There is no output

### ISSUE THREAD

**Issue by WuMianRen** [dotnet/maui#1728]
win11 22000.71
vs2022 preview2
net6 preview6

**Comment by pjmagee** [comment]
Ive had this issue when not running from a terminal with Admin. Happened to me several times. I had to exit. Reinstall the tool and then open up a fresh Windows terminal with Admin.

**Comment by Quietscheente** [comment]
Had the same issue.
Found this log entry in the windows event log:
"...
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
..."

This was not automatically installed with VS2022 preview.

**Comment by pjmagee** [comment]
> Had the same issue.
> Found this log entry in the windows event log:
> "...
> Application: maui-check.exe
> ...
> The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
> ..."
> 
> This was not automatically installed with VS2022 preview.

I think maui-check needs to confirm it needs .NET 5, Since VS 2022 installs Preview6 and only need Preview6 for Maui. So it seems a bit counter-intuitive that maui-check needs .NET 5 installed.

**Comment by jfversluis** [comment]
Looks like maui-check should be [able to run on .NET Core 3.1 as well as .NET 5](https://github.com/Redth/dotnet-maui-check/blob/main/MauiCheck/MauiCheck.csproj#L5)

If you still have issues with this, please open an issue on the [maui-check repository](https://github.com/Redth/dotnet-maui-check/).
