### ISSUE TITLE
Unable to compile MAUI Blazor App

### ISSUE THREAD

**Issue by fillet29** [dotnet/maui#17288]
Original Title: 「ど素人の質問で申し訳ありませんが、、、」

English Translation:

When I click on the Windows machine and try to run it, I get an error and cannot proceed.
The error message is as follows
Severity Level Code Description Project File Line Suppression Status
Error NU1202 Package Xamarin.AndroidX.Navigation.Fragment 2.5.2.1 is incompatible with net7.0-android33.0 (.NETCoreApp,Version=v7.0). Package Xamarin.AndroidX.Navigation.Fragment 2.5.2.1 does not support any target framework. BlazorApp2 C:\Users\halap\source\repos\BlazorApp2\BlazorApp2\BlazorApp2.csproj 1
Severity Level Code Description Project File Line Suppression Status
Error NU1202 Package Xamarin.Google.Android.Material 1.7.0 is incompatible with net7.0-android33.0 (.NETCoreApp,Version=v7.0). Package Xamarin.Google.Android.Material 1.7.0 does not support any target framework. BlazorApp2 C:\Users\halap\source\repos\BlazorApp2\BlazorApp2\BlazorApp2.csproj 1

Severity Level Code Description Project File Line Suppression Status
Error NU1202 Package Xamarin.Google.Crypto.Tink.Android 1.7.0.1 is incompatible with net7.0-android33.0 (.NETCoreApp,Version=v7.0). Package Xamarin.Google.Crypto.Tink.Android 1.7.0.1 does not support any target framework. BlazorApp2 C:\Users\halap\source\repos\BlazorApp2\BlazorApp2.csproj 1

If you look closely at the screen, you will see a cross in the lower right corner of the dependency folder.
Is this the cause?
Please let me know how to solve this problem.

Problem encountered on https://dotnet.microsoft.com/ja-jp/learn/maui/first-app-tutorial/run
Operating System: windows　11

Windowsマシンをクリックして実行しようとしたらエラーがでてしまい、進みません。
エラーメッセージは次の通りです。
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	NU1202	パッケージ Xamarin.AndroidX.Navigation.Fragment 2.5.2.1 は net7.0-android33.0 (.NETCoreApp,Version=v7.0) と互換性がありません。 パッケージ Xamarin.AndroidX.Navigation.Fragment 2.5.2.1 はどのターゲット フレームワークもサポートしません。	BlazorApp2	C:\Users\halap\source\repos\BlazorApp2\BlazorApp2\BlazorApp2.csproj	1	
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	NU1202	パッケージ Xamarin.Google.Android.Material 1.7.0 は net7.0-android33.0 (.NETCoreApp,Version=v7.0) と互換性がありません。 パッケージ Xamarin.Google.Android.Material 1.7.0 はどのターゲット フレームワークもサポートしません。	BlazorApp2	C:\Users\halap\source\repos\BlazorApp2\BlazorApp2\BlazorApp2.csproj	1	

重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	NU1202	パッケージ Xamarin.Google.Crypto.Tink.Android 1.7.0.1 は net7.0-android33.0 (.NETCoreApp,Version=v7.0) と互換性がありません。 パッケージ Xamarin.Google.Crypto.Tink.Android 1.7.0.1 はどのターゲット フレームワークもサポートしません。	BlazorApp2	C:\Users\halap\source\repos\BlazorApp2\BlazorApp2\BlazorApp2.csproj	1	

画面をよく見ると、依存関係のフォルダに右下にバツ印がついています。
これが原因でしょうか。
解決方法をご教授願いたいです。

![スクリーンショット 2023-09-09 110759](https://github.com/dotnet/maui/assets/143938425/4162d7b9-1d81-4f82-a3a9-4fee8d120b06)

**Comment by jfversluis** [comment]
Hi there! Great to see you're trying out .NET MAUI and Blazor Hybrid!

Could you please describe the steps you took to end up in this situation? From what I can tell from your description it would seem like you installed some NuGet packages is that correct?

It looks like it's trying to compile AndroidX plugins for Windows which is not going to work. Would you be able to post the contents of your csproj file maybe?
