### ISSUE TITLE
The target "GetPriOutputs" does not exist in the project

### ISSUE THREAD

**Issue by wa1gon** [dotnet/maui#17295]
### Description

**The target "GetPriOutputs" does not exist in the project** in the "Error List".

This happens on both VS 2022 and 2022 preview.  

This started to happen when I tried to extract some projects into a new library solution.

Now I can't create a MAUI solution that runs.

PS C:\Users\wa1go> dotnet workload list

Installed Workload Id      Manifest Version                            Installation Source
------------------------------------------------------------------------------------------
maccatalyst                16.4.8694-net8-p7/8.0.100-preview.7         VS 17.7.34024.191
maui-windows               8.0.0-preview.7.8842/8.0.100-preview.7      VS 17.7.34024.191
maui-maccatalyst           8.0.0-preview.7.8842/8.0.100-preview.7      VS 17.7.34024.191
ios                        16.4.8694-net8-p7/8.0.100-preview.7         VS 17.7.34024.191
maui-android               8.0.0-preview.7.8842/8.0.100-preview.7      VS 17.7.34024.191
android                    34.0.0-preview.7.382/8.0.100-preview.7      VS 17.7.34024.191
maui-ios                   8.0.0-preview.7.8842/8.0.100-preview.7      VS 17.7.34024.191

### Steps to Reproduce

1.  Create a MAUI project from the template
2.  Run it as Windows machine
3. See error in Error list.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

### Did you find any workaround?

No, but would love to have one.  I am dead in my tracks.

### Relevant log output

```shell
1>------ Build started: Project: LogGate, Configuration: Release Any CPU ------
1>C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(254,5): warning NETSDK1201: For projects targeting .NET 8.0 and higher, specifying a RuntimeIdentifier will no longer produce a self contained app by default. To continue building self-contained apps, set the SelfContained property to true or use the --self-contained argument.
1>C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>C:\Users\wa1go\.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1155,68): error MSB4057: The target "GetPriOutputs" does not exist in the project.
```

**Comment by samhouts** [comment]
It looks like your WinAppSDK installation is out of sync. 8.0.0 should be using 1.3, not 1.2. You might need to reinstall.

**Comment by RoiChen001** [comment]
I can't repro this issue on latest 17.10.0 Preview 1.
