### ISSUE TITLE
Exception occurs when modifying an ObservableCollection that has a binding to a BindableLayout on a thread from the ThreadPool

### ISSUE THREAD

**Issue by bykovd1984** [dotnet/maui#17302]
### Description

There occurs exception "The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))" when I modify ObservableCollection that has a binding to a BindableLayout on a thread that isn't MainThread. When I do the same with ObservableCollection that has a binding to a CollectionView there is no exception.

### Steps to Reproduce

1. Start project on "Windows Machine"
2. Click button "Add element to BindableLayout"
3. See "Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.WinUI.dll
BindableLayoutButton_Clicked: The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))" in Output/Debug
4. Click button "Add element to CollectionView"
5. See added elements under the button

### Link to public reproduction project repository

https://github.com/bykovd1984/maui-issues-bindablelayout-and-observablecollection

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Relevant log output

```shell
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.WinUI.dll
BindableLayoutButton_Clicked: The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11 .NET 8 with below Project:
[BindableLayoutAndObservableCollection.zip](https://github.com/dotnet/maui/files/12583371/BindableLayoutAndObservableCollection.zip)

**Comment by razaraz** [comment]
Workaround: Call collection operations through the Dispatcher.

**Comment by PureWeen** [comment]
This isn't behavior we are going to enable. You'll need to make UI changes on the UI Thread yourself.
