### ISSUE TITLE
I'm guessing your device is too old to work based on [this link](https://learn.microsoft.com/en-us/dotnet/maui/deployment/hot-restart?view=net-maui-7.0#troubleshoot). I've had similar problems with an old iPhone 5.

### ISSUE THREAD

**Issue by Jockeyvb** [dotnet/maui#17313]
I'm guessing your device is too old to work based on [this link](https://learn.microsoft.com/en-us/dotnet/maui/deployment/hot-restart?view=net-maui-7.0#troubleshoot). I've had similar problems with an old iPhone 5.

_Originally posted by @smitha-cgi in https://github.com/dotnet/maui/issues/11324#issuecomment-1313148424_

**Comment by Jockeyvb** [comment]
I have the same issue with iPhone 6 plus and iPhone 12 devices

**Comment by drasticactions** [comment]
As suggested in the original bug you linked to: https://github.com/dotnet/maui/issues/11324#issuecomment-1315065191

This would be an issue with Hot Restart, a Visual Studio feature. This should be filed [under there](https://developercommunity.visualstudio.com/spaces/8/index.html) as a bug report.
