### ISSUE TITLE
[regression/8.0.0-rc.1.9171] XAMLC is currently throwing exceptions in RC1 that don't appear to have been throwing in PReview7

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#17333]
### Description

XAMLC is currently throwing exceptions in RC1 that don't appear to have been throwing in PReview7

/Users/shneuvil/Downloads/AXamlCStyleError/AXamlCStyleError/Resources/Styles/DefaultStyles.xaml: Error: Collection was modified; enumeration operation may not execute. (AXamlCStyleError) XamlC

### Steps to Reproduce

Download this sample  based off of https://github.com/davidortinau/ControlGallery
[AXamlCStyleError.zip](https://github.com/dotnet/maui/files/12590722/AXamlCStyleError.zip)

Try to compile it

### Link to public reproduction project repository

https://github.com/davidortinau/ControlGallery

### Version with bug

[8.0.0-rc.1.9171](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.1.9171)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

iOS, Android, Windows, macOS

### Did you find any workaround?

Remove XAMLC attribute from failing files

**Comment by JoacimWall** [comment]
Hi 
We have the same issue. 
If you change to [XamlCompilation(XamlCompilationOptions.Skip)] on the style.xaml file the compile works.

//Joacim
