### ISSUE TITLE
.NET 8 iOS Release build very slow

### ISSUE THREAD

**Issue by Inrego** [dotnet/maui#17339]
### Description

Due to bugs regarding LINQ in Release builds in .NET 7, I opted to upgrade my app to .NET 8
The build time increased drastically. I'm using azure DevOps cloud agent to build.

Build time on .NET 7:  ~14 min
Build time on .NET 8: 34 min 36 sec

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS

**Comment by jfversluis** [comment]
Do you have any more information on what does the build definition look like? What command are you using for building? What build agent? Relevant log output?
