### ISSUE TITLE
Button stops responding on clicks after switching Command by DataTrigger

### ISSUE THREAD

**Issue by bykovd1984** [dotnet/maui#17344]
### Description

I change the button Command depending on the value of the IsSelected property. After the second click, the button stops calling Command.
```
    <Button>
      <Button.Triggers>
        <DataTrigger TargetType="Button" Binding="{Binding IsSelected}" Value="True">
          <Setter Property="Text" Value="Selected"/>
          <Setter Property="Command" Value="{Binding UnselectCommand}" />
        </DataTrigger>
        <DataTrigger TargetType="Button" Binding="{Binding IsSelected}" Value="False">
          <Setter Property="Text" Value="Unselected"/>
          <Setter Property="Command" Value="{Binding SelectCommand}" />
        </DataTrigger>
      </Button.Triggers>
    </Button>
```

### Steps to Reproduce

1. Start project
2. See text button "Selected"
3. Click button
4. See text changed on "Unselected"
5. Click button
6. See text changed on "Selected"
7. Click button
8. See nothing happens

### Link to public reproduction project repository

https://github.com/bykovd1984/maui-issues-switch-command-by-datatrigger

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue repro on Windows 11 **.NET 7**, but not repro on Windows 11(8.0.0-preview.7.8842), Android 13.0-API33 and iOS 16.4 with below Project:
[17344.zip](https://github.com/dotnet/maui/files/12605325/17344.zip)
![Click](https://github.com/dotnet/maui/assets/97647558/fdb1bc96-76af-4420-92b1-f8e5620cec92)
