### ISSUE TITLE
[Support] Select TFMs for Maui projects

### ISSUE THREAD

**Issue by profix898** [dotnet/maui#1734]
With Xamarin.Forms we could build _'components'_ in a netStandard project. In my case, I used to create navigation infrastructure (INavigation, etc.) and base Forms (IView, etc.) in a variety of project assemblies.

Now I started to migrate the projects over to MAUI. However, it looks like I have to choose exact/specific TFMs (net6.0-ios, net6.0-android, even net6.0-windows-10.0.19041, etc.) throughout the entire dependency tree of the app. Its not possible to reference and use any MAUI interfaces and components in a _'universal'_ net6.0 project (even if UseMaui is specified).

This works (in .csproj):
```
<TargetFrameworks>net6.0-ios;net6.0-android;net6.0-maccatalyst;net6.0-windows10.0.19041</TargetFrameworks>
<UseMaui>true</UseMaui>
```

This does not:
```
<TargetFramework>net6.0</TargetFramework>
<UseMaui>true</UseMaui>
```

I'm just wondering if that is deliberately by design or a regression in comparison to Xamarin.Forms? Looks like this is related to the recent move from packages to workloads?

(I'm using VS 2022 preview 2 and the latest net6.0 preview 6. Checked with maui-check tool.)

**Comment by Redth** [comment]
Fixed
