### ISSUE TITLE
[regression/8.0.0-preview.7.8842] VisualState does not return to `Normal` state when using an `AppThemeBinding`

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#17354]
### Description

Utilizing a `VisualState` that defines an `AppThemeBinding` in `PointerOver` never returns to `Normal` state. 

### Steps to Reproduce

Given 
```xml
            <Grid WidthRequest="500" ColumnDefinitions="*">
                <VisualStateManager.VisualStateGroups>
                    <VisualStateGroupList>
                        <VisualStateGroup x:Name="CommonStates">
                            <VisualState x:Name="PointerOver">
                                <VisualState.Setters>
                                    <Setter Property="BackgroundColor" Value="{AppThemeBinding Dark=Red, Light=White}"/>
                                </VisualState.Setters>
                            </VisualState>
                            <VisualState x:Name="Normal">
                                <VisualState.Setters>
                                    <Setter Property="BackgroundColor" Value="Transparent" />
                                </VisualState.Setters>
                            </VisualState>
                        </VisualStateGroup>
                    </VisualStateGroupList>
                </VisualStateManager.VisualStateGroups>
                <Label Text="I'm a grid. Hover over me to change background color"/>
            </Grid>
 ```
 
 Observe the following.
 
 1. Hover over the grid. Observe the color change to RED.
 2. No longer hover over the grid. The color still stays RED.
 
 This does **not** occur if you remove the `AppThemeBinding` binding and just use `RED`.

### Link to public reproduction project repository

https://github.com/daltzctr/maui-hoverstate-repro

### Version with bug

[8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.6.8686](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.6.8686)

### Affected platforms

Windows

### Did you find any workaround?

Don't use `AppThemeBinding`. Unfortunately, for applications that support more than one theme (dark and white), this is not an acceptable solution.

**Comment by samhouts** [comment]
very similar to https://github.com/dotnet/maui/issues/16960, but that first appeared in preview2

**Comment by samhouts** [comment]
Confirmed that this regressed between [8.0.0-preview.6.8686](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.6.8686) and [8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842). https://github.com/dotnet/maui/pull/13818 seems sus.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11(8.0.0-preview.7.8842) with below Project:
[maui-hoverstate-repro.zip](https://github.com/dotnet/maui/files/12605896/maui-hoverstate-repro.zip)

![image](https://github.com/dotnet/maui/assets/97647558/707db35b-8793-4f5f-9706-1d9c61686887)

**Comment by StephaneDelcroix** [comment]
similar, but different, to #16538. Fixed by the same changes
