### ISSUE TITLE
[regression/8.0.0] LinearGradient from transparent to white is getting gray at the bottom

### ISSUE THREAD

**Issue by MAUIoxo** [dotnet/maui#17366]
### Description

I use a ContentView with a Background Image and stacked on top a LinearGradientBrush like this:

```xaml
<Grid RowDefinitions="Auto">

    <!-- BackgroundImage and LinearGradient -->
    <Image x:Name="BackgroundImage" Grid.Row="0"  Source="radiant_gradient.png" Aspect="AspectFill" />
    <Grid BackgroundColor="Transparent"  Grid.Row="0">
        <Grid.Background>
            <LinearGradientBrush EndPoint="0,1">
                <GradientStop Color="Transparent" Offset="0.1" />
                <GradientStop Color="White" Offset="1.0" />
            </LinearGradientBrush>
        </Grid.Background>
    </Grid>
    
</Grid>
```

![grafik](https://github.com/dotnet/maui/assets/140683727/ad4631b1-d4a5-416a-9cbe-f4baea57cbad)

<br/>
<br/>

**BackgroundImage without LinearGradientBrush**:

![grafik](https://github.com/dotnet/maui/assets/140683727/450f23d8-15f3-44c4-b1ad-bd55cc966c7d)

<br/>
<br/>

**BrackgroundImage displayed with correct LinearGradientBrush on Android**:

![grafik](https://github.com/dotnet/maui/assets/140683727/cf4119db-9136-4c0d-baa5-008f1ebc9cd0)

<br/>
<br/>
<br/>

**Problem:** 

In **Visual Studio 2022 17.8 - Preview 1** with **.NET 8.0** the LinearGradientBrush is getting **gray at the Bottom** instead of being white as expected (see SCreenshots above and attached sample application)

This used to work in .NET 7.0 

### Steps to Reproduce

- Visual Studio 2022 17.8 - Preview 1
- .NET 8.0
- Launch sample application with iPhone 14 iOS 16.2 Simulator (or any other iOS-Simulator)
- If you can see the wrong LinearGradientBrush effect when application was started fine, otherwise switch to View2 and back to View1 and you will see it as in the screenshots above

### Link to public reproduction project repository

https://github.com/MAUIoxo/LinearGradientBrushApp_17366

### Version with bug

8.0.100-rc.1.23455.8
8.0.100-preview.7.23376.3  (coming with VS 2022 17.8)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS

### Did you find any workaround?

No workaround available
Tried with StackLayout instead of Grid in BackgroundImageView.xaml, but without effect

**Comment by billreiss** [comment]
I'm seeing this too, given the following XAML:

<Frame VerticalOptions="Fill" CornerRadius="0" BorderColor="Transparent" HeightRequest="300" >
    <Frame.Background>
        <LinearGradientBrush StartPoint="0,0" EndPoint="0,1">
            <GradientStop Color="#40000000" Offset="0.0"/>
            <GradientStop Color="#20000000" Offset="0.7"/>
            <GradientStop Color="Transparent" Offset=".995"/>
            <GradientStop Color="Red" Offset=".995"/>
            <GradientStop Color="Red" Offset="1.0"/>
        </LinearGradientBrush>
    </Frame.Background>
</Frame>

I would expect the top area to go from translucent black to transparent, and then a red bar at the bottom. However, the top area has red where there shouldn't be any.

<img width="292" alt="image" src="https://github.com/dotnet/maui/assets/1813417/7e4a401b-7699-4589-9f37-204587ddca68">

**Comment by billreiss** [comment]
Workaround: try setting your last gradient stop to .999 instead of 1.

**Comment by MAUIoxo** [comment]
@billreiss - Unfortunately, it did not help in my case. When I first saw this behavior which lead to this issue, I thought the Linear Gradient is upside down which might be a bit as you described. But how would it be gray then, when I do it from tranparent to white? Funny thing is that I reported a similar effect on Android in [https://github.com/dotnet/maui/issues/16392](https://github.com/dotnet/maui/issues/16392), also see [https://stackoverflow.com/questions/76762039/lineargradientbrush-not-working-on-android-in-landscape-view](https://stackoverflow.com/questions/76762039/lineargradientbrush-not-working-on-android-in-landscape-view). On Android it it should be fixed in .NET 8, but now we have the same effect on iOS...

**Comment by arnaudaug** [comment]
Hello,

Today I wanted to add a "LinearGradientBrush" to my code and I have the same problem with Maui 7.0.92 (my main SDK) and 8.0.0-rc.1.9171 ; not tested with earlier versions. So I came across this topic.

Tested with iOS Simulator and MacCatalyst, same result on an iPhone with iOS 16.6.1 : Bug with gray.
Android Simulator : OK

My code :
```
<Grid HeightRequest="200"
      VerticalOptions="End">
    <Grid.Background>
        <LinearGradientBrush StartPoint="0,0" EndPoint="0,1">
            <GradientStop Color="Transparent" Offset="0" />
            <GradientStop Color="White" Offset="0.999" />
        </LinearGradientBrush>
    </Grid.Background>
</Grid>
```

Regards

**Comment by khagesh-medtronic** [comment]
Hello,

I am also impacted with this issue with the sable .net 8 release version. The suggested workaround of stopping at 0.999 doesn't work. Is there any update on this.

**Comment by billreiss** [comment]
> Hello,
> 
> Today I wanted to add a "LinearGradientBrush" to my code and I have the same problem with Maui 7.0.92 (my main SDK) and 8.0.0-rc.1.9171 ; not tested with earlier versions. So I came across this topic.
> 
> Tested with iOS Simulator and MacCatalyst, same result on an iPhone with iOS 16.6.1 : Bug with gray. Android Simulator : OK
> 
> My code :
> 
> ```
> <Grid HeightRequest="200"
>       VerticalOptions="End">
>     <Grid.Background>
>         <LinearGradientBrush StartPoint="0,0" EndPoint="0,1">
>             <GradientStop Color="Transparent" Offset="0" />
>             <GradientStop Color="White" Offset="0.999" />
>         </LinearGradientBrush>
>     </Grid.Background>
> </Grid>
> ```
> 
> Regards

So Transparent is actually #00000000, when it's generating intermediate colors, there is a mis of white and black. Try #00FFFFFF for your first GradientStop and see if it helps.

**Comment by Redth** [comment]
I'm not able to reproduce this on 8.0.3 (MAUI GA) in terms of what the first screenshot in the original post shows, where it's' not even getting opaque at the end of the gradient. 

As @billreiss mentioned, Transparent is not quite what you are expecting, and using #00FFFFFF does indeed explicitly make the gradient appear less gray.
