### ISSUE TITLE
Windows: CollectionView is flickering when an item is moved

### ISSUE THREAD

**Issue by unombun** [dotnet/maui#17369]
### Description

On Windows I have a collectionView bound with some items. In the ObservableCollection if I do a move of an item, the whole collection view is flickering.

The same behavior is in the latest .Net 8 Maui RC1

### Steps to Reproduce

1. On Windows create a collection view bound with data from an ObservableCollection.
2. Call ObservableCollection.Move method to change position of an item.
3. The whole collection view is flickering. 
4. It should not flick, just update the UI.

### Link to public reproduction project repository

https://github.com/flesarradu/WindowsMoveItemCollection

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1). Repro on Windows 11, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[WindowsMoveItemCollection.zip](https://github.com/dotnet/maui/files/12646574/WindowsMoveItemCollection.zip)

![Flicker](https://github.com/dotnet/maui/assets/97647558/1b1d3cd2-71ae-42d6-a542-38d14610f68f)

**Comment by PureWeen** [comment]
> Hi @unombun. We have added the "s/try-latest-version" label to this issue, which indicates that we'd like you to try and reproduce this issue on the latest available public version. This can happen because we think that this issue was fixed in a version that has just been released, or the information provided by you indicates that you might be working with an older version.
> 
> You can install the latest version by installing the latest Visual Studio (Preview) with the .NET MAUI workload installed. If the issue still persists, please let us know with any additional details and ideally a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md) provided through a GitHub repository.
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

I tested this on the next Preview build of VS and can't reproduce. If you are still seeing this with the next Preview 6 build of VS please let me know.

**Comment by BenBtg** [comment]
I have just tested the above repro sample 17.8.0 Preview 6.0 using NET7 and NET8 RC2.9511 (latest public preview available today) and still get the flickering issue.

**Comment by PureWeen** [comment]
> I have just tested the above repro sample 17.8.0 Preview 6.0 using NET7 and NET8 RC2.9511 (latest public preview available today) and still get the flickering issue.

Can you test the test nightly?

https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by BenBtg** [comment]
Have just tested against 8.0.0-nightly.9556
Still get the flickering issue. i.e. full list refresh.

**Comment by BenBtg** [comment]
Have retested using latest daily build 8.0.4-nightly.9659 and still getting the above full list refresh flickering issue on Windows.
Items moved smoothly as expected on other platforms.

**Comment by Foda** [comment]
Hello! Unfortunately, this is an issue with WinUI (see: https://github.com/microsoft/microsoft-ui-xaml/issues/1503).

However, you can work-around it by doing something like:
```csharp
int item = _items[5];
_items.RemoveAt(5);
_items.Insert(7, item);
```

**Comment by Redth** [comment]
Moving to SR2 while we are blocked on the WinUI issue already linked.  We will continue investigating as a possibility for SR2.

**Comment by Redth** [comment]
As mentioned, we are currently blocked in our existing implementation of this by the issue residing in WinUI.  

There is a workaround suggested here in the meantime.

Moving this to the backlog until we can revisit this either by reworking the underlying implementation (which carries significantly more cost and risk, especially in a .NET 8 cycle) or the upstream issue unblocks it.

**Comment by workmail20** [comment]
Have similar problem

WinUI

https://github.com/dotnet/maui/assets/74146677/4d292739-7cab-4cf7-9d18-0f129172b1f3



Android

https://github.com/dotnet/maui/assets/74146677/a2e7d462-6704-4246-b726-8880b787f831

**Comment by leelandclay** [comment]
I ran into this same problem and discovered what was causing it for me. When I added the `ItemsUpdatingScrollMode="KeepLastItemInView"` property to the `CollectionView`, it started flickering. The fix for me was to remove that property and assign a name to the CollectionView (I used LogCollectionView). Then I added a SetCollectionView method to my ViewModel like this

```
private CollectionView _collectionView;
public void SetCollectionView(CollectionView collectionView)
{
    _collectionView = collectionView;
}
```
I then modified the code behind of the page to pass the CollectionView over to the ViewModel like this:

```
public MainPage(MainPageViewModel viewModel)
{
    InitializeComponent();
    viewModel.SetCollectionView(LogCollectionView);
    BindingContext = viewModel;
}
```

Finally, I updated my AddLogEntry to call the ScrollTo method on the CollectionView whenever items were added like this:


```
private void AddLogEntry(string entry)
{
    LogEntries.Add(entry);
    if (_collectionView != null && LogEntries.Count > 0)
    {
        _collectionView.ScrollTo(LogEntries.Count - 1);
    }
}
```

**Comment by donbing** [comment]
adding `ItemsUpdatingScrollMode="KeepScrollOffset"` seems to have fixed this for me.

**Comment by jeqermigselv-cloud** [comment]
I can confirm this exact behavior - and workarounds - also work in .NET MAUI in .NET 10 Release Candidate 1

**Comment by ThaDaVos** [comment]
Curious if there have been any updates as to a fix to this?

**Comment by kubaflo** [comment]
Closing as externally owned. The relevant upstream owner or tracking destination is https://github.com/microsoft/microsoft-ui-xaml/issues/1503. The complete MAUI report and discussion remain available here for reference.

> Disclosure: this comment was generated by AI.

**Comment by kubaflo** [comment]
Reopening — this issue should not have been closed.

It carries `s/verified` (a maintainer or partner reproduced it), `s/triaged` (it already went through triage), `partner/winui`, `partner/cat 😻` (a partner team is tracking it). Those labels mean the report was already confirmed as a real product defect, so it is not eligible for backlog cleanup closure. Closure here requires specific fix evidence (a merged PR that closes it, or a `fixed-in-*` label), and there was none.

Sorry for the noise, and thanks to everyone who flagged it.

> Disclosure: this comment was generated by AI.
