### ISSUE TITLE
BlazorWebView scale is not right for displays with scales greater than 100%

### ISSUE THREAD

**Issue by msschl** [dotnet/maui#17372]
### Description

If the display scale of text apps and other elements is set to > 100% the blazor web view won't scale accordingly.

![image](https://github.com/dotnet/maui/assets/5054780/7cab63e3-cb20-42dd-81e7-a8acbb6e64cc)

### Steps to Reproduce

1. Create a .net maui blazor hybrid app
2. Start it
3. Set the display scale to > 100%

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

No

**Comment by Eilon** [comment]
Hi @msschl , is the issue specifically that changing the DPI _after_ the app is already running has no effect? Does restarting the app after the DPI is set work?

**Comment by msschl** [comment]
No sry. I forgot to mention that. You can set the DPI to 150% and then start the app. Also changing the dpi while the app is running has also jo effect.

**Comment by msschl** [comment]
I think I found the reason why it is not working:

We used a hack to fix the issue with dropdowns in the web view being in the wrong screen position when the window was moved and the dropdown was expanded. See MainPage.xaml.cs

```cs
using Microsoft.Maui.Platform;

namespace Company.Namespace.XYZ;

public partial class MainPage : ContentPage
{
    public MainPage()
    {
        this.InitializeComponent();
    }

// #if WINDOWS
//     private bool foundWindow;

//     protected override void OnHandlerChanged()
//     {
//         base.OnHandlerChanged();

//         if (this.foundWindow is false)
//         {
//             var window = this.GetParentWindow();

//             if ((window?.Handler?.PlatformView as MauiWinUIWindow)?.GetAppWindow() is var appWindow && appWindow is not null)
//             {
//                 appWindow.Changed += this.OnAppWindowChanged;
//                 this.foundWindow = true;
//             }
//         }
//     }

//     private void OnAppWindowChanged(Microsoft.UI.Windowing.AppWindow sender, Microsoft.UI.Windowing.AppWindowChangedEventArgs args)
//     {
//         if (args.DidPositionChange)
//         {
//             this.WidthRequest = this.Width + 1;
//             this.HeightRequest = this.Height + 1;
//             this.WidthRequest = sender.Size.Width;
//             this.HeightRequest = sender.Size.Height;
//         }

//         if (args.DidSizeChange)
//         {
//             this.WidthRequest = sender.Size.Width;
//             this.HeightRequest = sender.Size.Height;
//         }
//     }
// #endif

}
```

After commenting this out the scaling works however the issue with the dropdown elements remains.

**Comment by Eilon** [comment]
@msschl thank you for the extra info. It does seem like the workaround for the dropdowns could mess up the DPI scale because it's modifying the control's size dynamically. This ultimately appears to be an issue with the underlying WebView2 control, which has its issue tracker here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/. There's an issue at https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290 that describes the dropdown issue and has some discussions about various workarounds that work better than others. Ultimately I don't think there's anything we can do for this within .NET MAUI because it's up to the underlying control to set the dropdown location and respect DPI settings.
