### ISSUE TITLE
[regression/8.0.0-rc.1.9171] SwipeView Execute mode does not work when using Binding Command

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#17371]
### Description

In net8-rc1, on android, Execute mode of a SwipeView is not working when using Binding Command.
This was working in net7 and also in net8-pre2.

### Steps to Reproduce

1. Open repro project
2. Swipe left
3. The GO action should be invoked
4. The binded command should do a Console.WriteLine, check your output.
5. Unfortunately, on net8-rc1, the command is not executed.

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppTestSwipeView

### Version with bug

[8.0.0-rc.1.9171](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.1.9171)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842) 

### Affected platforms

Android

### Affected platform versions

Android 34

### Did you find any workaround?

When using SwipeItem.Invoked instead of the Binding Command, it seems to work.
But it's not really a workaround.

**Comment by tranb3r** [comment]
Could be related to https://github.com/dotnet/maui/issues/16345

**Comment by samhouts** [comment]
Yep, regressed between [8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842) and [8.0.0-rc.1.9171](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.1.9171), so I think https://github.com/dotnet/maui/issues/16345 is the culprit. Thanks!
