### ISSUE TITLE
VisualStateManager with TargetName error XFC0001: Cannot resolve property

### ISSUE THREAD

**Issue by MatrixRonny** [dotnet/maui#17380]
### Description

I am trying to compile a MAUI application. I receive the following error:
`XamlC error XFC0001: Cannot resolve property "IsToggled" on type "Grid (property missing or missing accessors)".`

I am trying to style the selection of the CollectionView using ItemTemplate and VisualStateManager. As far as I understand, the VisualStateManager for the first child of DataTemplate inherits the VisualStates of the CollectionViewItem (analogy from ListView). I cannot use properties other that the DataTemplate's child in Setters, even when TargetName is used due to compilation error.

### Steps to Reproduce

Add the following code anywhere inside a ContentPage:
``` XML
<Grid>
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroup Name="CommonStates">
            <VisualState Name="Normal">
                <VisualState.Setters>
                    <Setter Property="IsToggled" Value="True" TargetName="something"/>
                </VisualState.Setters>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>

    <Switch x:Name="something"/>
</Grid>
```

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (API 30)

### Did you find any workaround?

As far as I understand, the problem is that the compiler expects all setter properties from VisualStateManager to be the same type as the control where the VisualStateManager is defined, even if TargetName is specified. However, the Setters work on properties with same name from other controls.

One workaround is to use a layout control for each state and set its visibility to true/false. The workaround consists of duplicating all the target controls with styles corresponding to each state.

Another workaround is to handle corresponding events, set their value in a ViewModel using observable properties and then handle the states through Bindings.

### Relevant log output

This is a compile time issue, logging does not apply.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1). Build failed with below project on Windows 11:
[17380.zip](https://github.com/dotnet/maui/files/12646583/17380.zip)
![image](https://github.com/dotnet/maui/assets/97647558/825ef09d-cf8f-4ef4-8db7-9565287733e9)

**Comment by Xo3-ToBapbl** [comment]
Please, read documentation here:
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/visual-states#set-state-on-multiple-elements

You should access target element property by: "Switch.IsToggled"
