### ISSUE TITLE
Binding doesn't update control property after manual update

### ISSUE THREAD

**Issue by Mexraub** [dotnet/maui#17382]
### Description

I have created an app with an Entry control and a Button. I have a binding on the Text property with the OneWay mode. When I click on the Button, it updates a counter in the page's viewmodel which updates the Entry's text (The binding of the Text property is on the counter)

This updates correctly the entry's text. However, if I manually update the Entry's text, then try to click on the Button, the Entry's text won't update anymore.

It feels like the link to the Binding is broken after the manual update. I have tried to create the same app on Xamarin Forms, and it worked correctly there.

### Steps to Reproduce

1. Create a MAUI app
2. In the page, add an Entry like so : `<Entry Text="{Binding Test, Mode=OneWay}"/>`
3. In the same page, add a Button like so : `<Button Grid.Row="1" Text="Test" Clicked="Button_Clicked"/>`
4. Create the file MainPageViewModel.cs (The page's BindingContext)
5. Add the property Test (integer) and add the necessary code to update a Binding (INotifyPropertyChanged interface)
6. Add the function UpdateTest, which increases the Test counter
7. In MainPage.xaml.cs, create the function Button_Clicked (Button's Clicked event), and use it to call the UpdateTest function
8. Compile the app
9. Click on the Button, it should update the Entry's text
10. Manually change the Entry's text
11. Click on the Button

Expected outcome : The Entry's text is updated
Actual outcom : The Entry's text stays the same

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by jsuarezruiz** [comment]
Could be fixed by https://github.com/dotnet/maui/pull/17215
cc @StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
I think this was fixed, I need to check

**Comment by StephaneDelcroix** [comment]
@jsuarezruiz not by that, but the change we did for calling SetValueFromRenderer in entry, instead of SetValue. do you have the PR # ?

**Comment by StephaneDelcroix** [comment]
fixed by #17036
