### ISSUE TITLE
No Longer Able to Create MapSpan in XAML

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#17383]
### Description

![image](https://github.com/dotnet/maui/assets/1676321/0ea7a28f-e29c-40db-9180-955c1e97ce2f)
Now gives an error

Docs: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/map#display-a-specific-location-on-a-map

### Steps to Reproduce

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/map#display-a-specific-location-on-a-map

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

I was *not* able test on other platforms

**Comment by jamesmontemagno** [comment]
Ahh i see...

you now have to do this:

```

            xmlns:maps="http://schemas.microsoft.com/dotnet/2021/maui/maps"
```

Docs say: 

```
   xmlns:maps="clr-namespace:Microsoft.Maui.Controls.Maps;assembly=Microsoft.Maui.Controls.Maps"
          
```

**Comment by samhouts** [comment]
paging @davidbritch  🙂
