### ISSUE TITLE
[Enhancement] Rework the WinUI control to NOT use custom control templates

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#1738]
## Summary

WinUI currently has custom control templates for several controls. This was to add support for missing features with UWP.

Since WinUI was implemented all the features that were added with newer versions of Windows reaches the latests packages.

This issue is to switch to using the various ResourceDictionary keys instead.

Using this method, we get all the new styles and any Windows 11 themes.

## API Changes

No code changes, mainly stop using `MauiButton` and use `Button` with resource keys.

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by mattleibow** [comment]
An example is this: https://github.com/dotnet/maui/pull/1698

**Comment by jsuarezruiz** [comment]
Currently we have the following resources:
![image](https://user-images.githubusercontent.com/6755973/167395629-07d32d9d-afa6-4085-8377-200fe347b314.png)

- MauiComboBoxStyle: This resource include a style to allow CharacterSpacing and other details to be used in the title. However, the Picker use directly Microsoft.UI.Xaml.Controls.ComboBox.
- MauiSliderStyle: Contains a style for the Slider Thumb using an image. The Slider use directly Microsoft.UI.Xaml.Controls.Slider .
- MauiStepperStyle: There is not something like the Xamarin.Forms UWP Stepper in WinUI. This resource contains a style to define the Stepper using a Grid with two buttons.
- WindowRootStyle: Here we have some styles to allow to customize the AppBarTitle etc.

**Comment by jfversluis** [comment]
Does this still need work?
