### ISSUE TITLE
[VSCode][MAUI]The App hang after pulling down the RefreshView C2 page on iOS and My Mac target.

### ISSUE THREAD

**Issue by homeyf** [dotnet/maui#17394]
### Description

[VSCode][MAUI]The App hang after pulling down the RefreshView C2 page on iOS and My Mac target.

**Note:** This issue does not repro on VSM.

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Windows.
2.Click or tap on category 'C' for 'RefreshView'.
3.Click or tap on test 'C2'.
4. Pull up and pull down the page to initiate a refresh.

**Actual results:**
The App hang after pulling down the RefreshView C2 page on iOS and My Mac target.
![hangdemo](https://github.com/dotnet/maui/assets/82450723/8f34cdc8-81b0-4230-ace9-85b806ee12e0)

**Expect results:**
RefreshView details page loads fine.

### Link to public reproduction project repository

(https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests)

### Version with bug

7.0.92

### Affected platforms

iOS, MacCatalyst

**Comment by jsuarezruiz** [comment]
Could you try .NET 8 RC1?. There are some important fixes related with the RefreshView there, like https://github.com/dotnet/maui/pull/14302

**Comment by Ying-6** [comment]
This bug only repro on net7, but not repro on net8.

**Comment by QianaJiao** [comment]
Verified this issue with VS 17.10.0 P2, Microsoft.Maui.Controls:8.0.7. Not repro on .NET 8.0 iOS platforms with sample project.
