### ISSUE TITLE
[VSCode][MAUI]The Refresh spinner arrow is not displayed centered on iOS target.

### ISSUE THREAD

**Issue by homeyf** [dotnet/maui#17392]
### Description

[MAUI]The Refresh spinner arrow is not displayed centered on iOS target.
**Note:** This issue does not repro on VSM.

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to iOS.
2.Click or tap on category 'C' for 'RefreshView'.
3.Click or tap on test 'C4'.
4. Pull down to initiate a refresh.

**Actual results:** 
The Refresh spinner arrow is not displayed centered on iOS target.
![juzhong](https://github.com/dotnet/maui/assets/82450723/8758ca93-26ae-4ef0-9ff0-d4a3a9bec0da)

**Expect results:** 
The Refresh spinner arrow is displayed centered.

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

7.0.92

### Affected platforms

iOS

**Comment by QianaJiao** [comment]
Verified this issue with VS 17.10.0 P2, Microsoft.Maui.Controls:8.0.7. Not repro on .NET 8.0 iOS platforms with sample project.
![image](https://github.com/dotnet/maui/assets/91244512/8e1e433b-cfd7-4cd1-813b-7497db3b4cd7)
