### ISSUE TITLE
[Bug] Core library with UseMaui Workload results in NU1101	Unable to find package Microsoft.Maui.Controls.Ref.

### ISSUE THREAD

**Issue by Daniellled** [dotnet/maui#1739]
### Description
A standalone core library with the UseMaui workload results in the following errors:

NU1101	Unable to find package Microsoft.Maui.Controls.Ref.. No packages exist with this id in source(s):
NU1101	Unable to find package Microsoft.Maui.Essentials.Ref.. No packages exist with this id in source(s):
NU1101	Unable to find package Microsoft.Maui.Core.Ref.. No packages exist with this id in source(s):

### Steps to Reproduce

1. Create a standalone net6.0 library
2. Add `<UseMaui>true</UseMaui>` to the csproj file
3. Compile

### Expected Behavior
A dll produced that references the correct MAUI dependencies.

### Actual Behavior
A NU1101 compiler error.

### Basic Information

- Version with issue: 6.0.100-preview.6.21355.2
- Last known good version:
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 2.0

- Platform Target Frameworks: .net 6.0
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
- SDK Check
![image](https://user-images.githubusercontent.com/83433189/126234435-5c5aeb8c-5a3c-4537-ba8e-b67aa7551967.png)
- Workload List
![image](https://user-images.githubusercontent.com/83433189/126234493-49141df5-0dee-499c-b09b-10d3e94564e9.png)
- Csproj
![image](https://user-images.githubusercontent.com/83433189/126234541-1175a7de-30fe-4e7d-8d91-a1bc2690d22c.png)

Additionally I created a nuget.config and added the following sources

`<add key="MAUI" value="https://aka.ms/maui-preview/index.json" />`
`<add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />`
`<add key="xamarin" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" />`

None resolved the issue.

**Comment by profix898** [comment]
I wondered the same thing, see #1734. However, I was not so sure it is actually a bug. But it limits how/where you can use MAUI.

**Comment by jfversluis** [comment]
I see in the linked issue this should be fixed by now. This is definitely not something that should be happening and is a effect of all the things being in preview. The experience should be much better by now and even betterer in the future!
