### ISSUE TITLE
[regression/8.0.0-preview.4.8333] Windows CollectionView is displayed as Grid Layout even if it should be List if initially the collectionView is not visible

### ISSUE THREAD

**Issue by unombun** [dotnet/maui#17400]
### Description

In Windows if you have a regular "list layout" CollectionView that originally is hidden (IsVisible="False") and then it becomes visible it is rendered with a Grid layout.

Initially:
![image](https://github.com/dotnet/maui/assets/11754566/231e12de-f498-45dc-89b9-c26295feb3f4)

After: 
![image](https://github.com/dotnet/maui/assets/11754566/433e2cdf-b2cd-4682-a99a-4deff8ffeb19)

### Steps to Reproduce

1. Create a "list layout" collectionView with items that is not visible
2. Change CollectionView to be visible
3. The collectionView is rendered as "grid layout"

### Link to public reproduction project repository

https://github.com/flesarradu/WindowsInitiallyHiddenCollectionDOTNET8

### Version with bug

[8.0.0-preview.4.8333](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.4.8333)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149)

### Affected platforms

Windows

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.23419.4). Repro on Windows 11, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[WindowsMoveItemCollection.zip](https://github.com/dotnet/maui/files/12657012/WindowsMoveItemCollection.zip)

**Comment by samhouts** [comment]
Confirmed regressed between [8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149) and [8.0.0-preview.4.8333](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.4.8333). https://github.com/dotnet/maui/pull/14532 looks sus.
