### ISSUE TITLE
[Bug] Windows App Title not showing in latest MAUI Blazor

### ISSUE THREAD

**Issue by igalfsg** [dotnet/maui#1741]
### Description
The application title is not showing at the top of the new version of the Win version of .net MAUI Blazor (see Screenshot below)
### Steps to Reproduce

1. Create a new Blazor MAUI Application.
2. Run it.
3. Look at the title

### Expected Behavior
The name of the application should show. 
### Actual Behavior
The name of the application does not show. 
### Basic Information

- Version with issue: preview 6
- Last known good version: N/A
- IDE:Microsoft Visual Studio Community 2019 Preview
Version 16.11.0 Preview 3.0

### Screenshots
![image](https://user-images.githubusercontent.com/8607853/126248332-072660aa-6a18-4e64-9ede-1e52117175f2.png)

### Workaround

Does anybody know if there is a way to manually add it back?

**Comment by pjmagee** [comment]
You need to add the Title to the Window in the `CreateWindow` function.

**Comment by igalfsg** [comment]
Thanks, I took the CreateWindow Function from Weather Twenty one but it creates a black space in between the menu and the app. is it anything different for the Blazor one?

![image](https://user-images.githubusercontent.com/8607853/126335742-0ae986b3-9c96-426a-9799-8136b86f0cf8.png)

**Comment by pjmagee** [comment]
> Thanks, I took the CreateWindow Function from Weather Twenty one but it creates a black space in between the menu and the app. is it anything different for the Blazor one?
> 
> ![image](https://user-images.githubusercontent.com/8607853/126335742-0ae986b3-9c96-426a-9799-8136b86f0cf8.png)

Dont use a `NavigationPAge`, Just pass in the `MainPage` into the `Window`.

So you will want to use

`return new Window(new MainPage())`

MainPage.xaml is the one which holds the BlazorWebView. Wrapping into a Navigation is probably the reason you have this space, since that area is probably for menu items or something.

**Comment by igalfsg** [comment]
Awesome thanks that worked! For anyone having this problem add this to your App.xaml.cs

`protected override Window CreateWindow(IActivationState activationState) =>
            new Window(new MainPage()) { Title = "Weather TwentyOne" };`

**Comment by pjmagee** [comment]
> Awesome thanks that worked! For anyone having this problem add this to your App.xaml.cs
> 
> `protected override Window CreateWindow(IActivationState activationState) => new Window(new MainPage()) { Title = "Weather TwentyOne" };`

Also, we raised a ticket on Responsive / View not responding to Window size - but i I have a responsive fix Ive created which I think is temporary unless its out of scope of Maui and blazor to support out of the box with a template.

**Comment by kotx** [comment]
> Awesome thanks that worked! For anyone having this problem add this to your App.xaml.cs
> 
> `protected override Window CreateWindow(IActivationState activationState) => new Window(new MainPage()) { Title = "Weather TwentyOne" };`

Shouldn't it be `new Window(this.MainPage)`? Since it's created in the App's constructor.

**Comment by pjmagee** [comment]
> > Awesome thanks that worked! For anyone having this problem add this to your App.xaml.cs
> > `protected override Window CreateWindow(IActivationState activationState) => new Window(new MainPage()) { Title = "Weather TwentyOne" };`
> 
> Shouldn't it be `new Window(this.MainPage)`? Since it's created in the App's constructor.

Not when this issue was raised it wasnt. The templates have changed with each version almost.
