### ISSUE TITLE
Ambiguity Between IView.Arrange() and VisualElement.Arrange()

### ISSUE THREAD

**Issue by bradencohen** [dotnet/maui#17417]
### Description

This is super low priority, just a "gotcha" I ran into that I thought was worth mentioning.

When implementing a custom [LayoutManager ](https://github.com/hartez/CustomLayoutExamples/tree/main#creating-custom-layouts-in-maui)and invoking the Arrange method during the ArrangeOverride phase, there's a potential ambiguity between two methods:

1. VisualElement.Arrange() ([from VisualElement class](https://github.com/dotnet/maui/blob/8144b8b047e5922499ec5ceffdb0f5626dd48559/src/Controls/src/Core/VisualElement/VisualElement.cs#L1798))
2. IView.Arrange() ([from IView interface](https://github.com/dotnet/maui/blob/8144b8b047e5922499ec5ceffdb0f5626dd48559/src/Core/src/Core/IView.cs#L132))

Seemingly, only the `IView.Arrange()` method works correctly within the context of a `LayoutManager`.

For example, this doesn't work:
```csharp
 CustomView.TitleLabel.Arrange( destination );
```

But this does:
```csharp
( ( IView ) CustomView.TitleLabel ).Arrange( destination );
```

It took me a decent time debugging to figure out why none of my items were getting arranged on the screen, so at a worst case hopefully this can help some people out. Even if there isn't a fix it might be useful to call this out when the custom layout manager documentation is released.

If I'm misunderstanding something, please let me know, I'm still learning 😄. 

### Steps to Reproduce

1. Create a custom layout manager
2. Within that layout manager, call `.Arrange()` on a `VisualElement` without hard-casting to IView

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Not really relevant

### Did you find any workaround?

Yes, hard cast to IView

**Comment by jsuarezruiz** [comment]
@hartez Thoughts?
