### ISSUE TITLE
[regression/8.0.0] After switching from `net7` to `net8` build fails on `Android`

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#17426]
### Description

I only replaced `net7` with `net8` in my MAUI application. Now I cannot build / run the app due to following issue.

> error APT2260: resource mipmap/appicon (aka com.x.x:mipmap/appicon) not found.
> error APT2260: 
> error APT2260: This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.
> error APT2260: resource mipmap/appicon_round (aka com.x.x:mipmap/appicon_round) not found.
> error APT2260: 
> error APT2260: This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.
> 6>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-rc.1.432\tools\Xamarin.Android.Aapt2.targets(214,3): error APT2067: failed processing manifest.
> 6>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-rc.1.432\tools\Xamarin.Android.Aapt2.targets(214,3): error APT2067:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest
	xmlns:android="http://schemas.android.com/apk/res/android"
	android:versionCode="1" android:versionName="1.0.0"
	>
	<application
		android:allowBackup="true"
		android:label="3D Calculator"
		android:icon="@mipmap/appicon"
		android:roundIcon="@mipmap/appicon_round"
		android:supportsRtl="true"
		android:networkSecurityConfig="@xml/network_security_config"
		>
		<!-- Xam.Plugins.Messaging -->
		<!--android:name="android.support.v4.content.FileProvider"-->
		<provider android:name="androidx.core.content.FileProvider" android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" />
		</provider>
	</application>
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permis
```

### Steps to Reproduce

1. See Repro, try to run it on Android

### Link to public reproduction project repository

https://github.com/AndreasReitberger/MauiNet8AndroidManifestBug

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android

**Comment by AndreasReitberger** [comment]
It seems to run sometimes, if I just keep on building and try a few times.

**Comment by gabsamples6** [comment]
if you are interested in a workaround  
delete  below -    (this should be definetely addressed - been a problem in all the previews

1. android:icon="@mipmap/appicon"
2. android:roundIcon="@mipmap/appicon_round"

**Comment by AndreasReitberger** [comment]
@gabsamples6 
Thanks for the advice, I'll try this and report back :)

**Comment by mattleibow** [comment]
I just tested with the latest RC 1 SDK + MAUI and I got no errors.

Some things to try:
 - make sure you are on the latest VS preview
 - try a clean or delete the bin/obj (this should not be necessary when switching from net7 to net8, but the IDE sometimes caches things)
 - build from the command line `dotnet build /bl`

If you remove the icon in the manifest, then your app will NOT have an icon.

If there is still an issue when building, please attach a binlog so we can have a look at what could be causing the build failures: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

**Comment by gabsamples6** [comment]
@mattleibow  I am affected too 

1. Create a new maui app  vs 2022 .net 8 rc preview 2
2. remove bin/obj
3. and you will see below 

![image](https://github.com/dotnet/maui/assets/109357537/63189ef8-a4bc-4971-8131-d3697c95a48b)
![image](https://github.com/dotnet/maui/assets/109357537/480bcf57-0e75-4cc4-b1f8-eb6e84e9edfd)


![image](https://github.com/dotnet/maui/assets/109357537/670d25ac-a13c-40a4-9831-9bb9dbab3ead)

**Comment by RonnyRos** [comment]
I have the same issue.

**Comment by mattleibow** [comment]
If you are having the issue, I think at this point a binlog is the only way I can help. Not sure why referencing the image in code will affect the generation... And I am still unable to repro the error.
