### ISSUE TITLE
Style inheritance broken for ImageCell

### ISSUE THREAD

**Issue by taori** [dotnet/maui#17429]
### Description

Style inheritance for ImageCell does not appear to be working the way i would expect it to. For other controls the styles did change accordingly, but when setting the TextColor of an ImageCell this was not the case.

### Steps to Reproduce

- Create a default MAUI application
- Have a page like this:

```
 <ListView ItemsSource="{x:Binding Items}">
     <ListView.ItemTemplate>
         <DataTemplate>
             <ImageCell Text="{x:Binding Path=Text}" TextColor="{AppThemeBinding Dark={StaticResource Secondary}, Light={StaticResource Primary}}"
                        Command="{x:Binding Path=Command}"
                        ImageSource="{x:Binding Path=ImagePath}"></ImageCell>
         </DataTemplate>
     </ListView.ItemTemplate>
```
or
```
 <ListView ItemsSource="{x:Binding Items}">
     <ListView.ItemTemplate>
         <DataTemplate>
             <ImageCell Text="{x:Binding Path=Text}"
                        Command="{x:Binding Path=Command}"
                        ImageSource="{x:Binding Path=ImagePath}"></ImageCell>
         </DataTemplate>
     </ListView.ItemTemplate>
```

- add this style to Styles.xaml:

```
    <Style TargetType="ImageCell">
        <Setter Property="TextColor" Value="{AppThemeBinding Dark={StaticResource Secondary}, Light={StaticResource Primary}}"></Setter>
    </Style>
```

Both versions of the ListView should render the same if the ImageCell Style is present like this - but Style inheritance does not appear to work properly for the ImageCell.

### Link to public reproduction project repository

https://github.com/dotnet-architecture/eshop-mobile-client/blob/cd009eba041b55f199a313d99e5ea499b682e672/eShopOnContainers/App.xaml#L336-L350

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 13, latest windows

### Did you find any workaround?

Explicitly specifying the style but that would not be a desired behavior really.

### Relevant log output

```shell
none
```

**Comment by drasticactions** [comment]
@jsuarezruiz https://github.com/dotnet-architecture/eshop-mobile-client/blob/cd009eba041b55f199a313d99e5ea499b682e672/eShopOnContainers/App.xaml#L336-L350

eShopOnContainers is a good repo for this, it uses this and does not work there. 

Also, it's not specific to ImageCell, all Cell types are affected from what I can see, and the same code ran on Forms and worked. It's also broken in net8.0.

**Comment by taori** [comment]
@drasticactions Thanks for finding it so quickly and yeah. Other cell typed definitely are also affected

**Comment by StephaneDelcroix** [comment]
`ImageCell` is an `Element`, not a `VisualElement`, hence not stylable

**Comment by taori** [comment]
@StephaneDelcroix Something which is visible not being a VisualElement to me seems like an oversight, especially considering that this is a regression when comparing it to Xamarin Forms. Making people update their projects to MAUI to then frustrate them with behavior which will definitely be identified as bugs because of just outright closing it seems a little thoughtless to me.
