### ISSUE TITLE
[MAUI7] Label control with TextType set to Html, does not change the Text Color.

### ISSUE THREAD

**Issue by TripleSM** [dotnet/maui#17439]
### Description

Label control with TextType set to Html, does not change Text Color as expected. The rendered text color is always black. 
Sample code provided at below Microsoft documentation also does not work.
Display HTML: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/label

### Steps to Reproduce

Steps to reproduce the bug

1. Create a new .Net 7.0/MAUI App.
2. Add below XAML Layout to MainPage.xaml
3. Build the project and run.

XAML Layout:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MAUI_Label_Test.MainPage">

    <VerticalStackLayout>
        
        <Label TextType="Html" 
            Text="This is &lt;strong style=&quot;color:red&quot;&gt;HTML&lt;/strong&gt; text." />
        <Label TextType="Html">
            <![CDATA[
            This is <strong style="color:red">HTML</strong> text.
            ]]>
        </Label>
    </VerticalStackLayout>

</ContentPage>

![MAUI_Label_Test](https://github.com/dotnet/maui/assets/50290618/b2322ff0-7dc9-41b4-a578-8b210b536935)

### Link to public reproduction project repository

https://github.com/TripleSM/MAUI_Label_Test

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by mohachouch** [comment]
Hi,

According to the documentation :

Displaying HTML in a Label is limited to the HTML tags that are supported by the underlying platform.

Can you try : 

<VerticalStackLayout>
    
    <Label TextType="Html" 
        Text="This is &lt;strong style=&quot;color:red&quot;&gt;HTML&lt;/strong&gt; text." />
    <Label TextType="Html">
        <![CDATA[
        This is <strong><span style="color:red">HTML</span></strong> text.
        ]]>
    </Label>
</VerticalStackLayout>
