### ISSUE TITLE
Custom BindableRadioGroup is not working

### ISSUE THREAD

**Issue by SunilRana7121** [dotnet/maui#17445]
### Description

Custom BindableRadioGroup is not working

BindableRadioGroup  derived from StackLayout and it using Custom Radio button 
[custom_radio_button_issue.zip](https://github.com/dotnet/maui/files/12644853/custom_radio_button_issue.zip)

I have attached BindableRadioGroup ,CustomRadiobutton ,CustomRadioButtonHandleran ,MauiProgram files in Zip.

Please do the needful as we facing issue in Net MAUI Conversion from Xamarin Forms application.

Regards,
Sunil Rana

### Steps to Reproduce

<FlexLayout
    FlowDirection="LeftToRight" Direction="Row" AlignContent="Start"   BackgroundColor="Brown" MaximumWidthRequest="300" HorizontalOptions="FillAndExpand">
    
    <radio:BindableRadioGroup
        ItemsSource="{Binding SearchApplianceOptions , Mode=TwoWay}" IsEnabled="True"  BackgroundColor="Blue" HeightRequest="20"
        Orientation="Horizontal" IsVisible="True" 
        SelectedIndex="{Binding SelectedSearchOption}" WidthRequest="300"
        Spacing="20" HorizontalOptions="FillAndExpand"
        VerticalOptions="CenterAndExpand" />
</FlexLayout>

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.49

### Affected platforms

iOS, Android

**Comment by StephaneDelcroix** [comment]
could you please be more specific than 'my code isn't working' ? thanks
