### ISSUE TITLE
Add back AndroidClientHandler that existed in Xamarin and is now deprecated

### ISSUE THREAD

**Issue by rlennoxmemoro** [dotnet/maui#17440]
In issue [6147](https://github.com/dotnet/maui/issues/6174)

              You could try putting `<UseNativeHttpHandler>false</UseNativeHttpHandler>` in your project.

             To override the default:

             https://github.com/xamarin/xamarin-android/blob/e50b457fa236e6fc127eadc0cfa527934a03e7de/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L94

            The two options in .NET 6 are really `$(UseNativeHttpHandler)` true or false.

           _Originally posted by @jonathanpeppers in https://github.com/dotnet/maui/issues/6174#issuecomment-1113331030_

This really isn't a final solution.

This means that  when developing against localhost with a self-signed certificate, you do not use the native networking that will be used in the real world (assuming you don't want to take the performance hit in the real world and make this compile-conditional).

The problem is that the stacks work differently (e.g handling of partial-content 206 respsonses).  This creates errors that only happen when the app is used against a "real" server (one without a self-signed cert).  Any unit tests that are performed that use an http request will therefore be completely invalid and may fail in the real world.

Please do not deprecate Xamarin.Android.Net.AndroidClientHandler and bring back the ability to use the native stack and still handle self-signed certificates when doing development.  We had this in Xamarin for years ([this link](https://learn.microsoft.com/en-us/xamarin/cross-platform/deploy-test/connect-to-local-web-services#bypass-the-certificate-security-check)), and for what it's worth - the iOS way of handling this still works, so it leads to inconsistency in the different platforms.

**Comment by rmarinho** [comment]
This issue was moved to xamarin/xamarin-android#8345
