### ISSUE TITLE
[regression/8.0.0-preview.4.8333] Borderless Entry Handler Not Working in .NET MAUI 8.0

### ISSUE THREAD

**Issue by mistrypragnesh40** [dotnet/maui#17448]
### Description

Here is the code.

```
        Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping(nameof(CustomEntry), (handler, view) =>
            {
#if ANDROID
                handler.PlatformView.Background = null;
                handler.PlatformView.SetBackgroundColor(Android.Graphics.Color.Transparent);
#elif IOS
            handler.PlatformView.BackgroundColor = UIKit.UIColor.Clear;
            handler.PlatformView.Layer.BorderWidth = 0;
            handler.PlatformView.BorderStyle = UIKit.UITextBorderStyle.None;
#endif
            });```
            
            

### Steps to Reproduce

1. Create CustomEntry Class that inherit Entry Class.
2. Use That Handler in UI.
3. Add Handler Mapping on App.xaml.cs


```
        Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping(nameof(CustomEntry), (handler, view) =>
            {
#if ANDROID
                handler.PlatformView.Background = null;
                handler.PlatformView.SetBackgroundColor(Android.Graphics.Color.Transparent);
#elif IOS
            handler.PlatformView.BackgroundColor = UIKit.UIColor.Clear;
            handler.PlatformView.Layer.BorderWidth = 0;
            handler.PlatformView.BorderStyle = UIKit.UITextBorderStyle.None;
#endif
            });```

### Version with bug

[8.0.0-preview.4.8333](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.4.8333)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149)

### Affected platforms

iOS, Android

### Did you find any workaround?

```
handler.PlatformView.BackgroundTintList = Android.Content.Res.ColorStateList.ValueOf(Colors.Transparent.ToAndroid());
```

**Comment by RonnyRos** [comment]
yes does not work.

**Comment by mistrypragnesh40** [comment]
Hello, 
Here is the repo link : https://github.com/mistrypragnesh40/BorderlessEntryDemo

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.23419.4). Repro on Windows 11 and Android 13.0-API33, not repro on iOS 16.4 with below Project:
[BorderlessEntryDemo.zip](https://github.com/dotnet/maui/files/12679514/BorderlessEntryDemo.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/5b3d8974-cdc1-498c-af70-96c5e22f5aa5)
Android:
![image](https://github.com/dotnet/maui/assets/97647558/d415dd35-311d-4d7f-b8dc-2cbc4d1b44bd)
iOS:
![image](https://github.com/dotnet/maui/assets/97647558/7b2609b0-fafb-4dde-a940-a55b8ec1a363)

**Comment by samhouts** [comment]
Confirmed that this regressed between [8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149) and [8.0.0-preview.4.8333](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.4.8333). https://github.com/dotnet/maui/pull/12227 seems sus.

**Comment by npostma** [comment]
I've tested the fix (pullrequest) in combination with the net8.0 branch. Looks nice again :-)

![image](https://github.com/dotnet/maui/assets/1578820/67291a15-bc20-493b-bf8e-a82e6b29aca9)

**Comment by Equabyte** [comment]
This is not yet fixed in RC2 downloaded today: I am still experiencing the issue in borderless Entry custom controls. Can anyone please confirm the status?

**Comment by Equabyte** [comment]
Still not working in RC2. Can anyone confirm when is this going to be fixed? Any workaround?

**Comment by npostma** [comment]
@samhouts How/When can we expect this fix in a upcoming update? Ive build my app with the latest version of MAUI 8.0.3 on VS2022 Preview. But i still have the borders on android.
