### ISSUE TITLE
[MAUI] D1 text fill editor page lacks an entire line of underlines.

### ISSUE THREAD

**Issue by kevinxufei** [dotnet/maui#17473]
### Description

D1 text fill editor page lacks an entire line of underlines, causing the editing area to be unclear.

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to iOS or MacCatalyst.
2.Navigate to 'D Editer' -> 'D1' and click it.
3.Observe the page, the edit area is missing the entire line underline

Actual Behavior:
The editing area is missing an entire line of underline, causing the editing area to be unclear.
![s1](https://github.com/dotnet/maui/assets/86938401/778e43bc-60f9-474d-8150-cd2d1fada32f)

Expected Behavior:
The entire line of underlines is clearly displayed in the editing area
![s2](https://github.com/dotnet/maui/assets/86938401/1ca71ee5-287d-4789-a9ef-e577d96bc6a8)

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

Microsoft.Maui.Controls: 8.0.0-nightly.9245+sha.391f59ae4d-azdo.8414558

### Is this a regression from previous behavior?

This bug is not a regression, it can be reproduced in the latest stable release: 8.0.0-rc.1.9171.

### Affected platforms

iOS, macOS

**Comment by drasticactions** [comment]
I believe that's the default style for iOS and Mac Catalyst editors: They don't have borders. So I believe how it looks is expected and correct given the styles present in the sample app.

That said, if you want an easier way to see if the editor is expanding or collapsing based on the lines within it, you could probably wrap it around a border.

<img width="1072" alt="スクリーンショット 2023-09-19 18 09 21" src="https://github.com/dotnet/maui/assets/898335/ee9930e2-3f16-40ac-9770-7864f23a01b0">

**Comment by mattleibow** [comment]
Just did a test in Xcode and the editor does not have any border, but the entry does:

<img width="376" alt="image" src="https://github.com/dotnet/maui/assets/1096616/12326912-8dd6-4359-a77c-99c44533d94a">
