### ISSUE TITLE
Can't select MAUI project on visual studio

### ISSUE THREAD

**Issue by BigSpliffy** [dotnet/maui#17480]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows 11

I can't select the MAUI project type, I had to do a clean Windows install and now it won't show anymore. 
![4444444444](https://github.com/dotnet/maui/assets/145439829/09f2a7c1-dbc8-4896-9757-af791a94908c)
![5555555](https://github.com/dotnet/maui/assets/145439829/6da2c026-08e2-47fa-815d-6611dd47c586)

**Comment by jfversluis** [comment]
Hey @BigSpliffy in the last screenshot did you select the Other category? What is under Mobile? Or if you enter MAUI in the search box?
