### ISSUE TITLE
Use 'eg' to describe examples, not 'ex'

### ISSUE THREAD

**Issue by affableashish** [dotnet/maui#17492]
### Description

Please use 'eg' to describe examples not 'ex'. As a flagship product of MSFT, typos like this make product look sloppy.
For eg:

<img width="1239" alt="image" src="https://github.com/dotnet/maui/assets/30603497/0f24cec3-6323-4898-830b-e6b46f19029e">

### Version with bug

8.0.0-preview.1.7762

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

**Comment by drasticactions** [comment]
I don't believe "Ex" is a typo, it's a common abbreviation for "Example" and used quite frequently, 

https://github.com/search?q=org%3Adotnet+%22+ex.+%22+language%3AMarkdown&type=code
https://github.com/search?q=org%3Amicrosoft+%22+ex.+%22+language%3AMarkdown&type=code

And that's only examples through GitHub's limited code search.

**Comment by affableashish** [comment]
@drasticactions 
Yes, you're right, it couldn't have been a typo. But 'ex.' is definitely not an abbreviation for example, so it's best to avoid using it, just so the product doesn't look sloppy. 

<img width="933" alt="image" src="https://github.com/dotnet/maui/assets/30603497/940b9768-a372-439f-8516-8c50f6d7b648">
