### ISSUE TITLE
[Windows]CollectionView not show Header and Footer

### ISSUE THREAD

**Issue by eliasribeiro** [dotnet/maui#17499]
### Description

In Windows platform CollectionView not show Header and Footer.

Below is an example running on Android and Windows.
![CollectionView fw](https://github.com/dotnet/maui/assets/938094/e5220eba-d074-402f-aa29-de0a38906022)

### Steps to Reproduce

1. Create a new Maui Project.
2. Create a CollectionView on the MainPage like this:

```
<CollectionView>
    <CollectionView.ItemsSource>
        <x:Array Type="{x:Type x:String}">
            <x:String>Item 1</x:String>
            <x:String>Item 2</x:String>
        </x:Array>
    </CollectionView.ItemsSource>
    <CollectionView.Header>
        <Label Text="Header" />
    </CollectionView.Header>
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <Label Text="{Binding .}" />
        </DataTemplate>
    </CollectionView.ItemTemplate>
    <CollectionView.Footer>
        <Label Text="Footer" />
    </CollectionView.Footer>
</CollectionView>
```
3. Run in Windows.

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms, No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WinUI 3

### Did you find any workaround?

I found no other alternative

**Comment by drasticactions** [comment]
This should be fixed with https://github.com/dotnet/maui/issues/17499,

It's not in RC1, but should work with Main and whenever RC2 gets released. If you try this against Main and have issues, feel free to reopen this.
