### ISSUE TITLE
[WinUI] Border inside ScrollView not expanding during resize

### ISSUE THREAD

**Issue by cgp1976** [dotnet/maui#17502]
### Description

Basically, I noticed that the border no longer able to auto expand width,height when ScrollView Orientation is set to Both 

### Steps to Reproduce

```
<ScrollView  Orientation="Both" BackgroundColor="Gray" >
    <Border   HeightRequest="20"   StrokeThickness="0" StrokeShape="RoundRectangle 15" BackgroundColor="Pink"></Border>
</ScrollView>

```

Once it's built and loaded, you can minimize and maximinze the app to see the border not expanding at all , but if you remove the orientation attribute away from the scrollview and rerun the app. it's working but it will lose the scrollview orientation capabilities.

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/other

### Affected platforms

Windows

### Did you find any workaround?

Nope.

**Comment by drasticactions** [comment]
Can you please create a reproduction project showing what you're expecting to see and what regressed? 

Based on your description, this sounds like the correct behavior for what should happen with net8.0, and that net7.0 "worked" accidently but it shouldn't have done that. I don't believe border should have an Auto set width and height when inside a scrollview. The border width and height would be set by the contents contained within it, not the other way around. Having an example would help me see what you're seeing though.

**Comment by cgp1976** [comment]
please kindly find the attached. I have created a sample project

build and run the project and do the following things

maximize the app and restore the app
green color=width expanded as expected, it fills the screen with padding as well
pink color = width stays the same. kinda weird
blue color = ignore.  just for visual

resizing the app by clicking the window border and resize
green color=width expanded as expected, it fills the screen with padding as well
pink color = width something following while its resizing. kinda weird
blue color = ignore.  just for visual

do note that blue color (Border) is a child of the green color (Grid)
and also if you remove the Orientation attribute away from the scrollview. everything seems to render correctly


[MauiApp4.zip](https://github.com/dotnet/maui/files/12670696/MauiApp4.zip)

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Windows 11 with below Project:
[17502.zip](https://github.com/dotnet/maui/files/12710692/17502.zip)

![Expand](https://github.com/dotnet/maui/assets/97647558/1d26c017-2b76-4b83-94a9-d3b98a7a3268)

**Comment by samhouts** [comment]
This appears to behave exactly the same on 7.0.92. Doesn't look like a regression to me.
