### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by raselldev** [dotnet/maui#17504]
### Description

i have OnAppearing function like this:

```
protected override async void OnAppearing()
    {
        base.OnAppearing();
        try
        {
            DateTime lastTime = Convert.ToDateTime(Preferences.Get("LAST_ACTIVITY", DateTime.Now));
            DateTime dateTimeNow = DateTime.Now;

            double differentTime = dateTimeNow.Subtract(lastTime).TotalMinutes;
            double lockTime = double.Parse(Preferences.Get("LOCK_TIME", ""));

            if (differentTime > lockTime)
            {
                await doLogout();
            }
            else
            {
                Preferences.Set("LAST_ACTIVITY", DateTime.Now);
                await getDataChartProgress();
                getDataInbox();
            }
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine(ex.Message);
        }
    }
```

went i running for first time, i get crash:

Terminating app due to uncaught exception 'System.ObjectDisposedException', reason: 'Cannot access a disposed object.
Object name: 'Mopups.Platforms.iOS.PopupWindow'. (System.ObjectDisposedException)
   at ObjCRuntime.ThrowHelper.ThrowObjectDisposedException(Object o)
   at Foundation.NSObject.get_SuperHandle()
   at UIKit.UIView.get_Bounds()
   at BigTed.ProgressHUD.PositionHUD(NSNotification notification)
   at Foundation.InternalNSNotificationHandler.Post(NSNotification s)
   
   if i comment OnAppearing(), the app running normally

    
    

### Steps to Reproduce

1. Create MAUI Apps
2. add OnAppearing()
3. App Crash

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS, I was *not* able test on other platforms

**Comment by raselldev** [comment]
in xaml file, 


                        <Border
                            HorizontalOptions="CenterAndExpand">
                            <freakycontrols:FreakyPicker
                                x:Name="pickerBulan"
                                Title="Pilih Bulan"
                                TextColor="{StaticResource Gray950}"
                                ImageSource="down.png"
                                ImageAlignment="Right"
                                HorizontalTextAlignment="Center"
                                VerticalTextAlignment="Center"
                                SelectedIndexChanged="pickerBulan_SelectedIndexChanged"/>
                        </Border>

**Comment by drasticactions** [comment]
We would need a reproduction project with this crash to know for sure, but based on the stack trace you have, my guess is that it's an issue with Mopups (https://github.com/LuckyDucko/Mopups) or whatever control is being referenced in your XAML, and not something specific to this projects code.

**Comment by raselldev** [comment]
> We would need a reproduction project with this crash to know for sure, but based on the stack trace you have, my guess is that it's an issue with Mopups (https://github.com/LuckyDucko/Mopups) or whatever control is being referenced in your XAML, and not something specific to the MAUI UI projects code.

Okay, i just create new issue to Mopups
