### ISSUE TITLE
MAUI Error APT2096 failed to open APK:Invalid file

### ISSUE THREAD

**Issue by NicolasLiaoRan** [dotnet/maui#17503]
### Description

Thanks for helping me. I'm a new beginner to learn MAUI,I created a new MAUI project and without any change,just download associationed Android resources like 'Pixel 5 - API 33(Android 13.0 - API 33)'.

When I debug in Android Emulator,it occured an error

APT2096 failed to open APK:Invalid file

I don't know how to solve it,please help me and thanks a lot

Line 156 in error occured file is belowing
`  <Aapt2Link
      Condition=" '$(_AndroidResourceDesignerFile)' != '' "
      ContinueOnError="$(DesignTimeBuild)"
      DaemonMaxInstanceCount="$(Aapt2DaemonMaxInstanceCount)"
      DaemonKeepInDomain="$(_Aapt2DaemonKeepInDomain)"
      AssemblyIdentityMapFile="$(_AndroidLibrayProjectAssemblyMapFile)"
      ImportsDirectory="$(_LibraryProjectImportsDirectoryName)"
      OutputImportDirectory="$(_AndroidLibrayProjectIntermediatePath)"
      OutputFile="$(ResgenTemporaryDirectory)\resources.apk"
      PackageName="$(_AndroidPackage)"
      JavaPlatformJarPath="$(JavaPlatformJarPath)"
      JavaDesignerOutputDirectory="$(ResgenTemporaryDirectory)"
      CompiledResourceFlatFiles="@(_CompiledFlatFiles)"
      ManifestFiles="$(ResgenTemporaryDirectory)\AndroidManifest.xml"
      AdditionalAndroidResourcePaths="@(_LibraryResourceDirectories)"
      YieldDuringToolExecution="$(YieldDuringToolExecution)"
      ResourceSymbolsTextFile="$(IntermediateOutputPath)R.txt"
      ResourceDirectories="$(MonoAndroidResDirIntermediate)"
      ExtraArgs="$(AndroidAapt2LinkExtraArgs)"
      ToolPath="$(Aapt2ToolPath)"
      ToolExe="$(Aapt2ToolExe)"
      UncompressedFileExtensions="$(AndroidStoreUncompressedFileExtensions)"
  />`

### Steps to Reproduce

1.Create .Net MAUI project
2.Debug in Android Emulator -> Pixel 5 -API 33(Android 13.0 -API 33)
3.Occured error 
Code:APT2096
Description:failed to open APK:Invalid file
File:Xamarin.Android.Aapt2.targets
Line:156

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.92

### Affected platforms

Android, Windows

**Comment by drasticactions** [comment]
Hey @NicolasLiaoRan,

Looking at this error, my guess is it's not going to be specific to MAUI UI apps, but to any .NET Android App you try to deploy. Can you run `dotnet --info` and post the results? Also, what language and local is your computer set to? What is your project you're trying to deploy called?

**Comment by NicolasLiaoRan** [comment]
> Hey @NicolasLiaoRan,
> 
> Looking at this error, my guess is it's not going to be specific to MAUI UI apps, but to any .NET Android App you try to deploy. Can you run `dotnet --info` and post the results? Also, what language and local is your computer set to? What is your project you're trying to deploy called?

Thanks so much,and info is here.

1.dotnet info
PS C:\Users\ranliao> dotnet --info
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.401\

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  7.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

2.local computer language - simplified Chinese
3.project name schc.app,try to deployed in Android

I'm sorry for I'm a new beginner in MAUI program,If you need more information, please feel free to tell me and I will give more as I can.

**Comment by LH1234563** [comment]
https://stackoverflow.com/questions/52509263/aapt2exception-android-resource-linking-failed-output-error-failed-to-open-ap/52514742

**Comment by LH1234563** [comment]
可以看下是不是电脑里有加密软件导致的
[https://stackoverflow.com/questions/52509263/aapt2exception-android-resource-linking-failed-output-error-failed-to-open-ap/52514742](url)
