### ISSUE TITLE
[Windows] Border with rounded corners does not work well

### ISSUE THREAD

**Issue by eliasribeiro** [dotnet/maui#17500]
### Description

The border component when used with rounded corners does not work correctly on Windows. First it cuts the content from the left/top margin, then it lets the content exceed the limits of the right margin.
![BorderError fw](https://github.com/dotnet/maui/assets/938094/040d0772-dcf4-429d-a98c-19451552a11f)

### Steps to Reproduce

1. Create MAUI Project any version (versions 6-8.0rc).
2. In MainPage add border with StrokeShape with Round Rectangle, example:
```
        <Border StrokeShape="RoundRectangle 50" HeightRequest="100" WidthRequest="200" BackgroundColor="White">
            <Label Text="Hello World! I love you!" />
        </Border>
        <Border StrokeShape="RoundRectangle 50" Padding="40, 0,0,0" HeightRequest="100" WidthRequest="200" BackgroundColor="White">
            <Label Text="Hello World! I love you! Hello World! I love you!Hello World! I love you!Hello World! I love you!Hello World! I love you!Hello World! I love you!Hello World! I love you!Hello World! I love you!Hello World! I love you!Hello World! I love you!Hello World! I love you!Hello World! I love you!Hello World! I love you!" />
        </Border>
        <Border StrokeShape="RoundRectangle 50" Padding="40" HeightRequest="100" WidthRequest="200" BackgroundColor="White">
            <Label Text="Hello World! I love you!" />
        </Border>
```
3. Run App in Windows

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WinUI 3

**Comment by jstedfast** [comment]
This will probably be fixed by https://github.com/dotnet/maui/pull/17310

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Windows 11, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[17500.zip](https://github.com/dotnet/maui/files/12697786/17500.zip)
