### ISSUE TITLE
Disapearing controls in CollectionView on scrolling (on Android)

### ISSUE THREAD

**Issue by damiand2** [dotnet/maui#17508]
### Description

This is migration of project from Xamarin.Forms where following code works. Problem is only on Android (on iOS it works fine). When scrolling CollectonView and loading more data some controls for newly loaded data are not shown and upon scrolling back you discover that they also disapear for previously loaded data.
Initial data (notice 2 last rows for each card view - activity and images):
<img width="246" alt="image" src="https://github.com/dotnet/maui/assets/3309366/35249e9b-8794-4db6-afe9-f39de8d77084">
After scrolling and loading more data, 2 last rows are empty, even for previously loaded rows (some random rows do show loaded data still):
<img width="244" alt="image" src="https://github.com/dotnet/maui/assets/3309366/d68ed426-eebe-44b0-914d-ed1f9afb11d6">

### Steps to Reproduce

1. clone repo https://github.com/damiand2/MauiBugDisapearingControls
2. spin up VS, start debugging
3. on main page, scroll down collection view untill it loads more data (untill you stop seeing data in 2 last rows for each card view)
4. scroll back up to see initial cards - notice that they also no longer display data for 2 last rows

### Link to public reproduction project repository

https://github.com/damiand2/MauiBugDisapearingControls

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Workaround that seems to be working is to remove BindableLayout.ItemTemplate for stacklayouts inside scrollview inside collectionview and manually construct control tree for each item inside CollectionView.ChildAdded event

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0. This issue repro on Android 13.0-API33 **.NET 7**, but not repro on Android 13.0-API33**(8.0.0-rc.1.9171)**, iOS 16.4 with below Project:
[MauiBugDisapearingControls.zip](https://github.com/dotnet/maui/files/12711779/MauiBugDisapearingControls.zip)

![Loading](https://github.com/dotnet/maui/assets/97647558/aa6d8847-8483-41ba-b7cf-51f9a61c4930)

**Comment by nsood9** [comment]
I'm also facing similar issue. I've implemented a CollectionView with nested list binding. When I set the BindingContext of a Stacklayout inside the CollectionView DataTemplate with TwoWay binding mode, then the CollectView loads the data only for the first time and then all the data disappears when CollectionView is scrolled or page is changed. I'm doing something like this:

**Comment by nsood9** [comment]
This issue is not yet resolved, so it cannot be closed. We haven't found the solution yet.
