### ISSUE TITLE
Abysmal performance in Interop on iOS

### ISSUE THREAD

**Issue by damiand2** [dotnet/maui#17516]
### Description

During tests on iOS for self made binding library that binds to xcframework for google map utils (https://github.com/googlemaps/google-maps-ios-utils) i found that application slows down to a crawl in specific scenario. After instrumenting app (Instruments on macos) i found that that perf drop was related to switch between my code and native one (overriding method on class that binds to native one). After removal of that override, app is fast again. 
This kind of interop was also used on Xamarin.Forms (albeit with different binding library and earlier native library version) and there were no problems. Sample screen from Instruments showing dramatic cpu time in specific runtime methods responsible for interop between .net and native code:
<img width="620" alt="image" src="https://github.com/dotnet/maui/assets/3309366/4dcd9507-94b1-45e3-9e67-aea2cf4ed4be">

### Steps to Reproduce

1. clone https://github.com/damiand2/MauiBugiOSInteropPerformance
2. put your own google map key inside MauiProgram.cs (library deals with google maps, it was the easiest for me to provide quick sample), set up nuget local source to bindings folder inside repo
3. uncomment method public override bool ShouldRenderAsCluster(ICluster cluster, float zoom) inside ClusterRendererHandler.cs
4. run app on simulator or real iphone, does not matter
5. Map will take you to Czech country, library uses clustering of pins, double click anywhere to zoom in and therefore break down clusters into smaller ones, repeat this untill there are no more cluster and you only get singluar pins. 
6. try to move map left and right, notice how sluggish it becomes (UI hangs for almost second sometimes)
7. Stop app, comment back that override from 3rd point, restart app
8. repeat steps from 5th point, notice that now map scrolling is very smooth

### Link to public reproduction project repository

https://github.com/damiand2/MauiBugiOSInteropPerformance

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by drasticactions** [comment]
This doesn't seem to be a MAUI UI issue, but a [xamarin-macios](https://github.com/xamarin/xamarin-macios) one. 

@rolfbjarne What are your thoughts on this?

**Comment by rolfbjarne** [comment]
I tried your project, but it seems you need to check in the nupkg too:

> error : Could not find file '/Users/rolf/test/bugs/MauiBugiOSInteropPerformance/bindings/maputilsbinding/1.0.1/maputilsbinding.1.0.1.nupkg'.

I have a suggestion though to try to improve performance: disable the interpreter and use the static registrar:

```xml
<PropertyGroup>
    <UseInterpreter>false</UseInterpreter>
    <Registrar>static</Registrar>
</PropertyGroup>
```

that should speed up execution.

**Comment by damiand2** [comment]
@rolfbjarne - sorry for nupkg, you can try again, file is uploaded now.
As for PropertyGroup - did not seem to help.

**Comment by rolfbjarne** [comment]
I can reproduce this, moving to the correct repo.

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#19079
