### ISSUE TITLE
[NET 8, RC1, Windows] wrong initial BindingConext in CollectionView DataTemplate

### ISSUE THREAD

**Issue by malsabi** [dotnet/maui#17515]
### Description

The BindingContext for DataTemplates in CollectionView seems to be broken in .NET 8 RC1. Upon loading the CollectionView Items, the template object initially receives BindingContex reference to the BindingContext of the CollectionView parent. Immediately after it receives another BindingContext reference - this time the right reference to the Model of Items. This behavior has big performance impact because it sets Bindings twice and causes BindingFailures during the first cycle.

Note: I can see the data but a run time exception will occur whenever the button command is executed that is bounded to the view model.

Tested on Windows and Windows subsystem for Android - only Windows version seems affected.

### Steps to Reproduce

1. Load the repository and run the app in debug mode.
2. Observe raising count of BindingFailures with reference to wrong BindingContext. Data are displayed correctly, because it eventually receives the right BindingContext. The behavior is tracked in the Debug output window:

Warnings List:

Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Title' property not found on 'CollectionViewIssue.MainPageViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Program' property not found on 'CollectionViewIssue.MainPageViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Course' property not found on 'CollectionViewIssue.MainPageViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'EndDate' property not found on 'CollectionViewIssue.MainPageViewModel', target property: 'Microsoft.Maui.Controls.Label.Text'

Runtime fatal exception:
Exception = {"Parameter \"parameter\" (object) cannot be of type CollectionViewIssue.MainPageViewModel, as the command type requires an argument of type CollectionViewIssue.Assessment. (Parameter 'parameter')"}

Note: This 100% works without any issues on Android, its only happening on windows.

### Link to public reproduction project repository

https://github.com/malsabi/CollectionViewIssue

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

All the .NET 7 builds seem working properly, including nightly releases.

**Comment by PureWeen** [comment]
This should be fixed by https://github.com/dotnet/maui/pull/17348

Thank you for verifying against nightly!!!
