### ISSUE TITLE
Make DualScreen controls work in MAUI

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#1752]

**Comment by conceptdev** [comment]
Assumption that we keep using the old/existing DisplayMask API.

Source has been updated to Microsoft.Maui.Controls namespace
https://github.com/dotnet/maui/blob/main/src/Controls/DualScreen/src/DualScreenInfo.android.cs
but currently I don't think this is being generated into a NuGet anywhere.

Also, need to confirm whether the [Xamarin.DuoSDK NuGet](https://www.nuget.org/packages/Xamarin.DuoSDK) needs to be updated/rebuilt for .NET 6 (and change to Microsoft.Maui namespace)?
