### ISSUE TITLE
Update DualScreen controls to use new Window Jetpack on Android

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#1753]

**Comment by conceptdev** [comment]
C# binding for Xamarin.AndroidX.Window
https://github.com/xamarin/AndroidX/pull/362

C# sample using the binding in a Xamarin.Android app
https://github.com/microsoft/surface-duo-sdk-xamarin-samples/pull/19

Docs
https://docs.microsoft.com/dual-screen/xamarin/jetpack-window-manager

**Comment by conceptdev** [comment]
In February 2022 https://github.com/xamarin/AndroidX/issues/470 updated the [Xamarin.AndroidX.Window.WindowJava](https://www.nuget.org/packages/Xamarin.AndroidX.Window.WindowJava) to version `1.0.0.7` which binds the stable/release version of Google's [Jetpack Window Manager](https://developer.android.com/jetpack/androidx/releases/window) package.

This updated package was incorporated into the .NET MAUI DualScreen work in https://github.com/conceptdev/maui/commit/99a915e174f3ff43b0a9918b7709e5016499ce36

```xml
<PackageReference Include="Xamarin.AndroidX.Window.WindowJava" Version="1.0.0.7" />
```

The rest of the work updating **.NET MAUI DualScreen** is probably better tracked in https://github.com/dotnet/maui/issues/1752 so maybe we can close this issue @PureWeen ?
