### ISSUE TITLE
How are we doing in the repo? -- spot check

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#17556]
![image](https://github.com/dotnet/runtime/assets/6385855/bd3fe7e2-61e5-477f-af0f-980a62ab3d04)

It's midyear between our surveys and we'd like to hear from you how we're doing.

 https://www.surveymonkey.com/r/VP7BTTV

If you are reading this, we'd welcome your input. There's only one question so it should take just seconds. But we'd also welcome your suggestions in the optional text box as well. 

-- dotnet/maui maintainers

**Comment by danmoseley** [comment]
This survey is now closed. We'll follow up soon here with results.

**Comment by Eilon** [comment]
Hi everyone, the survey is now closed. Please continue reading to see the results.

We measure satisfaction with an aggregate called NSAT (net satisfaction) that is between 0 and 200 and anything over 100 is good. Below is the result for this repo (dotnet/maui). Note there were 21 responses so there's a moderate error bar.

| **NSAT (fall 2023)** | NSAT (spring 2023) | NSAT (spring 2022) |
| ---------------- | ------------------ | ------------------ |
| **48** (this survey)               | 76                 | 103                |

There were several comments and suggestions in the text that are summarized below:

1. General:
   1. More people need to work on .NET MAUI
1. Issue management:
   1. Difficult to understand which bugs will be fixed in which release
   1. What the milestones mean (for example, why does everything seem to go straight to Backlog)
   1. Fixes take too long
   1. Many issues dismissed and then closed by a bot
   1. More fixes should be back-ported to earlier versions
   1. Repros must be provided for every issue in a repo (from @Eilon: This was recently changed to be optional, though it is sometimes requested)
1. Code in the repo:
   1. Not clear which branch has the latest fixes
   1. Add more integration tests to prevent regressions
1. Areas to improve in the product:
   1. Many basic things in .NET MAUI don't work (keyboard issues, crashes)
   1. Make hotreload work with C# UI
   1. Image handling improvements
   1. Better testing support
   1. Publishing issues for iOS/macOS

Feel free to add any other thoughts below -- these are good suggestions for us all to think about. Thank you so much to the folks that filled this out.

**Comment by sasakrsmanovic** [comment]
Massive kudos for sharing these findings. 

Out of curiosity, is your scale out of 5/9/10?

**Comment by danmoseley** [comment]
@sasakrsmanovic Can you clarify, which scale? NSAT is 0-200
