### ISSUE TITLE
[Android] Navigation performance issue

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#17576]
### Description

Navigation performance difference compared to Xamarin.Forms
![xf-vs-maui-chatapp](https://github.com/jsuarezruiz/netmaui-chat-app-challenge/assets/6755973/f448c384-13d5-4dd5-be12-6adeda2fa94d)
(Left Xamarin.Forms 5, Right .NET MAUI .NET 8 main branch)

In .NET MAUI there is, depending on the device, a little more than 500ms of difference when rendering the content. Check the previous gif.

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/netmaui-chat-app-challenge

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-chat-app-challenge

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by PureWeen** [comment]
@jsuarezruiz if you have a moment maybe you can generate a speedscope?
https://github.com/dotnet/maui/wiki/Profiling-.NET-MAUI-Apps

**Comment by moljac** [comment]
I was able to get initial speedscope data, but I cannot navigate.

I will gather bugreport and logcat tomorrow.

**Comment by moljac** [comment]
repro sample

[netmaui-chat-app-challenge-main.zip](https://github.com/dotnet/maui/files/12857894/netmaui-chat-app-challenge-main.zip)

net8.0 - android, ios and maccatalyst - do not react to touches 

@jsuarezruiz I did not go into the app (yet). Are the events hooked??

net7.0 build error

```
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(239,2): error XABLD7024: Xamarin.Tools.Zip.ZipIOException: The file 'obj/Debug/net7.0-android/android/bin/com.jsuarezruiz.chatapp.apk' is not a ZIP archive. [/Users/Shared/Projects/d/tmp/triage/maui/17576/netmaui-chat-app-challenge-main/net7.0/netmaui-chat-app-challenge-main/src/NET MAUI/ChatApp/ChatApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(239,2): error XABLD7024:    at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictConsistencyChecks, IPlatformOptions options) in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/ZipArchive.cs:line 282 [/Users/Shared/Projects/d/tmp/triage/maui/17576/netmaui-chat-app-challenge-main/net7.0/netmaui-chat-app-challenge-main/src/NET MAUI/ChatApp/ChatApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(239,2): error XABLD7024:    at Xamarin.Android.Tasks.ZipArchiveEx..ctor(String archive, FileMode filemode) [/Users/Shared/Projects/d/tmp/triage/maui/17576/netmaui-chat-app-challenge-main/net7.0/netmaui-chat-app-challenge-main/src/NET MAUI/ChatApp/ChatApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(239,2): error XABLD7024:    at Xamarin.Android.Tasks.BuildApk.ExecuteWithAbi(String[] supportedAbis, String apkInputPath, String apkOutputPath, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo, String assemblyStoreApkName) [/Users/Shared/Projects/d/tmp/triage/maui/17576/netmaui-chat-app-challenge-main/net7.0/netmaui-chat-app-challenge-main/src/NET MAUI/ChatApp/ChatApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(239,2): error XABLD7024:    at Xamarin.Android.Tasks.BuildApk.RunTask() [/Users/Shared/Projects/d/tmp/triage/maui/17576/netmaui-chat-app-challenge-main/net7.0/netmaui-chat-app-challenge-main/src/NET MAUI/ChatApp/ChatApp.csproj::TargetFramework=net7.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/33.0.68/tools/Xamarin.Android.Common.Debugging.targets(239,2): error XABLD7024:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17 [/Users/Shared/Projects/d/tmp/triage/maui/17576/netmaui-chat-app-challenge-main/net7.0/netmaui-chat-app-challenge-main/src/NET MAUI/ChatApp/ChatApp.csproj::TargetFramework=net7.0-android]
```

**Comment by jonpryor** [comment]
We believe that [the above](https://github.com/dotnet/maui/issues/17576#issuecomment-1755474401) XABLD7024 error is a duplicate or variation on https://github.com/xamarin/xamarin-android/issues/6067, which is fixed in .NET 8.  This explains why it works reliably in .NET 8 but not .NET 7.

**Comment by moljac** [comment]
> We believe that [the above](https://github.com/dotnet/maui/issues/17576#issuecomment-1755474401) XABLD7024 error is a duplicate or variation on [xamarin/xamarin-android#6067](https://github.com/xamarin/xamarin-android/issues/6067), which is fixed in .NET 8. This explains why it works reliably in .NET 8 but not .NET 7.

Indeed. There was `global.json` in parent folder pinned to net7.0.

**Comment by Redth** [comment]
Release mode is snappy once I upgraded the sample to net8 and fixed some issues with XAML referring to non-existent resources.


https://github.com/dotnet/maui/assets/271950/d8816b8c-19b7-4b17-8699-8aa8ab58fd0b
