### ISSUE TITLE
.NET MAUI does not work with Android 13 Permissions.RequestAsync<Permissions.Camera>(); When One Time Denied From Application

### ISSUE THREAD

**Issue by Sohel3798** [dotnet/maui#17580]
### Description

.NET MAUI does not work with Android 13 Permissions.RequestAsync<Permissions.Camera>(); When One Time Denied From Application On Runtime

`async void Button_Clicked(System.Object sender, System.EventArgs e)
    {
        PermissionStatus status = await Permissions.CheckStatusAsync<Permissions.Camera>();
        if (status != PermissionStatus.Granted)
        {
            status = await Permissions.RequestAsync<Permissions.Camera>();
        }
    } `

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android

**Comment by jfversluis** [comment]
That is how Android (and iOS) work: if the user denies the permission they need to be reenabled from the settings of the app, not much we can do about that unfortunately.

**Comment by Sohel3798** [comment]
> That is how Android (and iOS) work: if the user denies the permission they need to be reenabled from the settings of the app, not much we can do about that unfortunately.

But i think we can do something bcoz in iOS when user once denied permission i understand we need to setup permission from app settings but in android once user denied permission 1st time and when I'm trying request of camera it's asking for permission 2nd time too I'm attaching video

**Comment by Sohel3798** [comment]
https://github.com/dotnet/maui/assets/93022175/a1805510-d27a-4a36-8c77-6017c7a6126e
