### ISSUE TITLE
Style Trigger Binding Not Recognizing Default Setter

### ISSUE THREAD

**Issue by cgp1976** [dotnet/maui#17597]
### Description

Code to Test

         <StackLayout>
             <Entry x:Name="Test_Entry" Text="Remove Text To Disable Button"/>
             <Button Text="Test Button" Margin="0,10,0,0" >
                 <Button.Style>
                     <Style TargetType="Button">
                         <Setter Property="IsEnabled" Value="True"/> 
                         <Style.Triggers>                          
                             <DataTrigger Binding="{Binding Source={x:Reference Test_Entry}, Path=Text.Length}" TargetType="Button"  Value="0">
                                 <Setter Property="IsEnabled" Value="False" />
                             </DataTrigger>
                         </Style.Triggers>
                     </Style>
                 </Button.Style>
             </Button>
         </StackLayout>`
`

### Steps to Reproduce

[MauiApp3.zip](https://github.com/dotnet/maui/files/12705590/MauiApp3.zip)

build and run it. once loaded, 

test case 1 - remove the textbox value . 
test case 2 - input some value in the textbox. 

when textbox has value
expected  result - should be in enabled state 

when textbox is value empty
expected  result - should be in disabled state 

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

Include the following right after the beginning of the style.trigger

```
<DataTrigger  Binding="{Binding Source=0}" TargetType="Button"  Value="0">
	<Setter Property="IsEnabled" Value="True" />
</DataTrigger>

```

**Comment by StephaneDelcroix** [comment]
might be fixed already, checking

**Comment by StephaneDelcroix** [comment]
the original issue (button staying enabled) is resolved, but the button doesn't get reenabled when text is set again
