### ISSUE TITLE
dotnet Publish error (MaterialDesignColor)

### ISSUE THREAD

**Issue by OmidTavana** [dotnet/maui#17600]
### Description

"dotnet publish  -c Release -f:net8.0-android34.0" is not working anymore in the RC update.

Error message : 

`C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-rc.1.432\targets\Microsoft.Android.Sdk.Aot.targets(109,5): error : Precompiling failed.`

error is being caused by materialDesignColor.dll.
could you confirm if the issue is related to Maui Bug or if there have been any recent changes to the publishing code?

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

Android

### Relevant log output

Severity	Code	Description	Project	File	Line	Suppression State
Error		Precompiling failed for C:\Users\OmidTavana_Coder\Documents\Repos\NIlyasGitGub\MAUI\Tarebar_MAUI\MBxMAUI\MBxMAUI\obj\Debug\net8.0-android34.0\android-arm64\aot-in\MaterialDesignColors.dll with exit code 1.
Failed to load method 0x600001b from 'C:\Users\OmidTavana_Coder\Documents\Repos\NIlyasGitGub\MAUI\Tarebar_MAUI\MBxMAUI\MBxMAUI\obj\Debug\net8.0-android34.0\android-arm64\aot-in\MaterialDesignColors.dll' due to Could not load file or assembly 'PresentationFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies..
Mono Ahead of Time compiler - compiling assembly C:\Users\OmidTavana_Coder\Documents\Repos\NIlyasGitGub\MAUI\Tarebar_MAUI\MBxMAUI\MBxMAUI\obj\Debug\net8.0-android34.0\android-arm64\aot-in\MaterialDesignColors.dll
AOTID AFC62FD2-4A90-D500-6C8A-70E54F0DACDB
Using profile data file 'C:\Users\OmidTavana_Coder\.nuget\packages\microsoft.maui.controls.build.tasks\8.0.0-rc.1.9171\buildTransitive\netstandard2.0\maui.aotprofile'
Using profile data file 'C:\Users\OmidTavana_Coder\.nuget\packages\microsoft.maui.controls.build.tasks\8.0.0-rc.1.9171\buildTransitive\netstandard2.0\maui-blazor.aotprofile'
Run with MONO_LOG_LEVEL=debug for more information.
AOT of image C:\Users\OmidTavana_Coder\Documents\Repos\NIlyasGitGub\MAUI\Tarebar_MAUI\MBxMAUI\MBxMAUI\obj\Debug\net8.0-android34.0\android-arm64\aot-in\MaterialDesignColors.dll failed.	MBxMAUI	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-rc.1.432\targets\Microsoft.Android.Sdk.Aot.targets	109

**Comment by drasticactions** [comment]
I don't believe this is a MAUI UI issue. That error seems correct for what's happening. 

Going by the name, I think you're using [MaterialDesignColor](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit) which is designed for UWP and WPF, not MAUI or non-Windows platforms. It's trying to bring in "PresentationFramework" (WPF) which can't be AOTed nor loaded within this context. 

![image](https://github.com/dotnet/maui/assets/898335/594d72ad-68fd-4c56-8aa7-39520451d4cb)

https://github.com/drasticactions/MauiRepros/tree/main/AndroidTest

Here is a sample project where I reference that nuget in a .NET Android app (So, no MAUI UI code) and it fails the same way. It also fails in net7.0-android too.

```
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\targets\Microsoft.Android.Sdk.Aot.targets(91,5): error : Precompiling failed for X:\Code\Wor
k\TestProjects\AndroidTest\obj\Release\net7.0-android33.0\android-x64\linked\MaterialDesignColors.dll with exit code 1. [X:\Code\Work\TestProjects\AndroidTest\A
ndroidTest.csproj::TargetFramework=net7.0-android33.0]
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\targets\Microsoft.Android.Sdk.Aot.targets(91,5): error : Mono Ahead of Time compiler - compi
ling assembly X:\Code\Work\TestProjects\AndroidTest\obj\Release\net7.0-android33.0\android-x64\linked\MaterialDesignColors.dll [X:\Code\Work\TestProjects\Androi
dTest\AndroidTest.csproj::TargetFramework=net7.0-android33.0]
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\targets\Microsoft.Android.Sdk.Aot.targets(91,5): error : AOTID ADE713E9-53AB-C377-B7CA-90378
46BC5B4 [X:\Code\Work\TestProjects\AndroidTest\AndroidTest.csproj::TargetFramework=net7.0-android33.0]
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\targets\Microsoft.Android.Sdk.Aot.targets(91,5): error : Using profile data file 'C:\Program
 Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\targets\dotnet.aotprofile' [X:\Code\Work\TestProjects\AndroidTest\AndroidTest.csproj::TargetFramework=
net7.0-android33.0]
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\targets\Microsoft.Android.Sdk.Aot.targets(91,5): error : Failed to load method 0x6000191 fro
m 'X:\Code\Work\TestProjects\AndroidTest\obj\Release\net7.0-android33.0\android-x64\linked\MaterialDesignColors.dll' due to Could not load file or assembly 'Sys
tem.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.. [X:\Code\Work\TestProjec
ts\AndroidTest\AndroidTest.csproj::TargetFramework=net7.0-android33.0]
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\targets\Microsoft.Android.Sdk.Aot.targets(91,5): error : Run with MONO_LOG_LEVEL=debug for m
ore information. [X:\Code\Work\TestProjects\AndroidTest\AndroidTest.csproj::TargetFramework=net7.0-android33.0]
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\targets\Microsoft.Android.Sdk.Aot.targets(91,5): error : AOT of image obj\Release\net7.0-and
roid33.0\android-x64\linked\MaterialDesignColors.dll failed. [X:\Code\Work\TestProjects\AndroidTest\AndroidTest.csproj::TargetFramework=net7.0-android33.0]
```

**Comment by OmidTavana** [comment]
Thank you for your response.
We were able to run it successfully on the last .Net8 preview, but I believe we might have just gotten lucky.
We will remove the DLL and get rid of all the Material Design styling.

**Comment by jfversluis** [comment]
Seems that this is resolved for now then, let us know if you encounter something else. Thanks!
