### ISSUE TITLE
"Codesign" exited with code 1 issue when try to build iOS app using visual studio 2022 for mac.

### ISSUE THREAD

**Issue by san1109** [dotnet/maui#17612]
### Description

There is "Codesign" exited with code 1 issue when try to build iOS app using visual studio 2022 for mac.

I have been trying to debug the .net maui app using physical iPhone(iPhone 7 plus) device but when I try to run the app using visual studio 2022 to debug with physical iPhone(iPhone 7 plus) device or any iPhone simulator I'm getting "Codesign" exited with code 1 issue. I tried cleaning the solution and rebuilding it several times and also deleting the bin folder but it doesn't fix the issue. The below is the error that is thrown when building the app in IOS.

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7099/tools/msbuild/iOS/Xamarin.Shared.targets(3,3): Error MSB6006: "codesign" exited with code 1. 
[The Image of the issue] 
(https://i.stack.imgur.com/Js6cl.png)

I already tried all answers related to this in stackoverflow it is not working [/usr/bin/codesign failed with exit code 1](https://stackoverflow.com/questions/1090288/usr-bin-codesign-failed-with-exit-code-1)

Environment: visual studio 2022 for mac .NET MAUI version: MAUI 7.0 Device: Iphone 7 plus

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by mmuresan** [comment]
This is not related to visual studio for mac, as I get the same error when build using Rider or even VS Code.
This is related to the Maui build process. It works in Xamarin, on the same Mac M2
