### ISSUE TITLE
MSAL - PublicClientApplication - GetAccountsAsync() doesn't return any Accounts in windows maui

### ISSUE THREAD

**Issue by AnithaRaniT** [dotnet/maui#17623]
### Description

``The MAUI windows app MSAL - PublicClientApplication - GetAccountsAsync() doesn't return any Accounts. 

I followed the process os integrating the MSAL as per the Microsoft document.

Here is the small code snippet:

```cs
AuthenticationResult result = null;
try
{
	IEnumerable<IAccount> accounts = await mPublicClientApplication.GetAccountsAsync();
	IAccount firstAccount = accounts.FirstOrDefault();

	result = await mPublicClientApplication.AcquireTokenSilent
		(mIndustrialAppsADOptions.Scopes, firstAccount).ExecuteAsync();
	return result;
}
catch(MsalUiRequiredException msre)
{
	try
	{
		if(Device.RuntimePlatform == Device.UWP)
		{
			result = await mPublicClientApplication.AcquireTokenInteractive(mIndustrialAppsADOptions.Scopes)
					  .WithUseEmbeddedWebView(true)
					  .ExecuteAsync();

		}
		else
		{

			result = await mPublicClientApplication.AcquireTokenInteractive(mIndustrialAppsADOptions.Scopes)
					  .WithUseEmbeddedWebView(true)
					  .WithParentActivityOrWindow(RootViewController)
					  .ExecuteAsync();
		}


		return result;
	}
	catch(MsalException ex)
	{					
		return null;
	}
	catch(Exception exc)
	{					
		return null;
	}
}
```

--------------------------------------------------------------------------------------

```cs
	public void RegisterTypes(IContainerRegistry containerRegistry)
		{
			IIndustrialAppsADOptions options = ((IContainerProvider)containerRegistry).Resolve<IIndustrialAppsADOptions>();
			string authority = options.Authority;

			if(Device.RuntimePlatform == Device.UWP)
			{
				mPublicClientApplication = PublicClientApplicationBuilder.Create(options.ClientId)
																.WithAuthority(authority)																
																.WithRedirectUri(SpecialRedirectUri?? $"msal{options.ClientId}://auth")
																.Build();
			
			}
			else if(Device.RuntimePlatform == Device.Android)
			{
				mPublicClientApplication = PublicClientApplicationBuilder.Create(options.ClientId)
																.WithAuthority(authority)
																.WithRedirectUri($"msal{options.ClientId}://auth")
																.Build();
			}
			else
			{
				 mPublicClientApplication = PublicClientApplicationBuilder.Create(options.ClientId)
																.WithAuthority(authority)
																.WithIosKeychainSecurityGroup(AppSettingsManager.Settings["IOS_KEYCHAIN_SECURITY_GROUP"]) //The ("*") will be replaced with ("com.microsoft.adalcache") during Production release
																.WithRedirectUri($"msal{options.ClientId}://auth")
																.Build();
			}
					
			containerRegistry.RegisterInstance(mPublicClientApplication);					
			containerRegistry.Register<IAuthenticationService, AuthenticationService>();
		}
```

### Steps to Reproduce

- Create MAUI app 
- Add the MSAL authentication
- When user Runs the application in Windows Platform for the first time Application asks for the MSAL login -> User enters the credentials and validates successfully
- Close the app
- Second time when user opens the app, it is again asking for the MSAL login. 

Expected Behavior :
It should not ask for the Login again. Instead, It should get the Account information which is previously logged in.

Actual Behavior :

It is asking the user MSAL authentication every time when open the application.

But the same is working fine in the Android Platform.

It is only broken in Windows Platform

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

No so far there is work around I found

### Relevant log output

```shell
NA
```

**Comment by AnithaRaniT** [comment]
Thanks for that. If you see my code snippet, I have followed the same. But still the accounts are empty.

**Comment by Vroomer** [comment]
@AnithaRaniT According to docs only mobile apps (Android/iOS) are caching the token. If you want to implement caching for Windows, I recommend following this https://learn.microsoft.com/en-us/entra/msal/dotnet/how-to/token-cache-serialization?tabs=desktop
