### ISSUE TITLE
[iOS] Crash in production: .NET ThreadPool Worker EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by greg84** [dotnet/maui#17626]
### Description

After updating an app from Xamarin to MAUI I am seeing this intermittent error in production from iOS devices. Below is all the information I have from Firebase. It's not enough for me to work out what's going on when the application crashes, where the crash occurs or how to reproduce it.

I've seen 4 events over the last few days from 4 different iOS devices using either iOS 15 or 16.

I appreciate this may not be enough information to determine exactly what's happening, but I'm not sure how else to troubleshoot the issue. I'm hoping someone can look at the below and see what's going on!

Crashed: .NET ThreadPool Worker
0  MyAppName                     0x330de20 corlib_wrapper_alloc_object_AllocVector_intptr_intptr + 4389608992
1  MyAppName                     0x330de18 corlib_wrapper_alloc_object_AllocVector_intptr_intptr + 4389608984
2  MyAppName                     0x3e72410 mono_jit_runtime_invoke + 3614 (mini-runtime.c:3614)
3  MyAppName                     0x3dc88f8 mono_runtime_try_invoke + 2415 (object.c:2415)
4  MyAppName                     0x3dc7418 mono_runtime_class_init_full + 534 (object.c:534)
5  MyAppName                     0x3e6d52c mono_resolve_patch_target_ext + 1584 (mini-runtime.c:1584)
6  MyAppName                     0x3e7d3c0 init_method + 4656 (aot-runtime.c:4656)
7  MyAppName                     0x3e9a338 mini_llvm_init_method + 946 (llvmonly-runtime.c:946)
8  MyAppName                     0x2530de8 mono_aot_System_Net_Sockets_init_method + 4375072232
9  MyAppName                     0x314db08 corlib_System_Threading_Tasks_Task_ExecuteEntryUnsafe_System_Threading_Thread + 4387773192
10 MyAppName                     0x311e2b8 corlib_System_Threading_Thread_StartCallback + 4387578552
11 MyAppName                     0x3e72410 mono_jit_runtime_invoke + 3614 (mini-runtime.c:3614)
12 MyAppName                     0x3dc7048 mono_runtime_invoke_checked + 2415 (object.c:2415)
13 MyAppName                     0x3dd8754 start_wrapper_internal + 1215 (threads.c:1215)
14 MyAppName                     0x3dd84e4 start_wrapper + 1266 (threads.c:1266)
15 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
16 libsystem_pthread.dylib        0xb88 thread_start + 8

### Steps to Reproduce

See call stack in description. Unable to reproduce this locally.

### Link to public reproduction project repository

n/a

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15/16

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Without the underlying context of what your running or any reproduction steps, it's very difficult to debug. My guess, based on the information provided, is that this probably isn't a MAUI UI specific issue, but one of your code running on the .NET Runtime. Seeing `System_Net_Sockets` maybe it's networking related? Something with AOT? Unless the code you're invoking initiated within this repo though, this probably won't be the place to fix it.

@rolfbjarne Do you have ideas on how to debug this?

**Comment by greg84** [comment]
Thanks @drasticactions, I'm now seeing the same error with a slightly different stack trace (below).

This time it includes `HttpResponseMessage.SendAsync`, but the only places in my code I call that have try/catch around them so wouldn't expect it to crash the app.

Crashed: .NET ThreadPool Worker
0  MyAppName                     0x3e7312c mini_init_method_rgctx + 1681 (jit-icalls.c:1681)
1  MyAppName                     0x316d1c4 corlib_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_SetException_System_Exception + 4388999620
2  MyAppName                     0x3521bb0 Microsoft_iOS_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_AsyncStateMachineBox_1_System_Net_Http_HttpResponseMessage_System_Net_Http_NSUrlSessionHandler__SendAsyncd__58_ExecutionContextCallback_object + 4392885168
3  MyAppName                     0x314c3b4 corlib_System_Threading_Tasks_Task_RunContinuations_object + 4388864948
4  MyAppName                     0x314c250 corlib_System_Threading_Tasks_Task_FinishContinuations + 4388864592
5  MyAppName                     0x3124274 corlib_System_Threading_CancellationTokenSource_NotifyCancellation_bool + 4388700788
6  MyAppName                     0x311b1b8 corlib_System_Threading_Thread_StartCallback + 4388663736
7  MyAppName                     0x3e6f310 mono_jit_runtime_invoke + 3614 (mini-runtime.c:3614)
8  MyAppName                     0x3dc3f48 mono_runtime_invoke_checked + 2415 (object.c:2415)
9  MyAppName                     0x3dd5654 start_wrapper_internal + 1215 (threads.c:1215)
10 MyAppName                     0x3dd53e4 start_wrapper + 1266 (threads.c:1266)
11 libsystem_pthread.dylib        0x16cc _pthread_start + 148
12 libsystem_pthread.dylib        0xba4 thread_start + 8

**Comment by greg84** [comment]
Another crash with a different stack trace this time. I still don't think there's enough information here to work out what's going on unfortunately.

Crashed: tid_2d92b
0  MyAppName                     0x3e730dc mini_init_method_rgctx + 1673 (jit-icalls.c:1673)
1  MyAppName                     0x34d280c GetTarget + 385 (Blocks.cs:385)
2  CoreTelephony                  0xd06ec __22-[CTCellularData init]_block_invoke_2 + 92
3  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
5  libdispatch.dylib              0x70c8 _dispatch_queue_override_invoke + 788
6  libdispatch.dylib              0x15a6c _dispatch_root_queue_drain + 396
7  libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
8  libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
9  libsystem_pthread.dylib        0xb98 start_wqthread + 8

**Comment by greg84** [comment]
@drasticactions / @rolfbjarne Another example from production is below. Here, it passes through a method I wrote called HandleImagesDownloaded, but the entire body of this method is wrapped in a try/catch(Exception), so I'm not sure why it's causing the application to crash.

No crashes are reported from the same code in the Xamarin Forms app.


Crashed: .NET ThreadPool Worker
0  MyAppName                     0x3e730dc mini_init_method_rgctx + 1673 (jit-icalls.c:1673)
1  MyAppName                     0x845664 System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_GSHAREDVT_TStateMachine_GSHAREDVT_ + 4305704548
2  MyAppName                     0xb4480c HandleImagesUpdated + 4308846604 (<unknown>:4308846604)
3  MyAppName                     0x88fcd8 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 4306009304
4  MyAppName                     0x3e6f310 mono_jit_runtime_invoke + 3614 (mini-runtime.c:3614)
5  MyAppName                     0x3dc3f48 mono_runtime_invoke_checked + 2415 (object.c:2415)
6  MyAppName                     0x3e729ec mono_gsharedvt_constrained_call + 1477 (jit-icalls.c:1477)
7  MyAppName                     0x894518 wrapper_managed_to_native_object___icall_wrapper_mono_gsharedvt_constrained_call_intptr_intptr_intptr_intptr_intptr + 4306027800
8  MyAppName                     0x845794 System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_GSHAREDVT_TStateMachine_GSHAREDVT_ + 4305704852
9  MyAppName                     0xb2fbe4 <HandleImagesDownloaded>b__0 + 4308761572 (<unknown>:4308761572)
10 MyAppName                     0x314aa08 corlib_System_Threading_Tasks_Task_ExecuteEntryUnsafe_System_Threading_Thread + 4348717576
11 MyAppName                     0x311b1b8 corlib_System_Threading_Thread_StartCallback + 4348522936
12 MyAppName                     0x3e6f310 mono_jit_runtime_invoke + 3614 (mini-runtime.c:3614)
13 MyAppName                     0x3dc3f48 mono_runtime_invoke_checked + 2415 (object.c:2415)
14 MyAppName                     0x3dd5654 start_wrapper_internal + 1215 (threads.c:1215)
15 MyAppName                     0x3dd53e4 start_wrapper + 1266 (threads.c:1266)
16 libsystem_pthread.dylib        0x16b8 _pthread_start + 148
17 libsystem_pthread.dylib        0xb88 thread_start + 8

**Comment by greg84** [comment]
I haven't seen the error since adding the following to the project file:

```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
   <MtouchLink>SdkOnly</MtouchLink>
   <UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```

I will close this issue and reopen it if I get the same error logged again.
