### ISSUE TITLE
.NET MAUI, set Entry style error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#17634]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-set-Entry-style-error/10469321)._

---
[Code(XAML)]

```xaml
<Style TargetType="Entry" x:Key="EntryStyle">
    ......
    <Setter Property="ClearButtonVisibility" Value="WhileEditing"/>
</Style>
```

[Error]
Microsoft.Maui.Controls.Xaml.XamlParseException:“Position 32:25. The PropertyName of Entry.ClearButtonVisibilityProperty is not ClearButtonVisibility”

[Document]
https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.maui.controls.entry?view=net-maui-7.0

![image](https://github.com/dotnet/maui/assets/1096616/dff0397c-5ac6-451e-83e7-c6b4e4dad076)

---
#### Feedback Bot on 9/19/2023, 01:28 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment]
I just tested this with .NET 8 RC 2 and this is not happening. Do you have more information on your setup? What version ov VS or MAUI and what target platform?
