### ISSUE TITLE
.NET MAUI, Entry Size(Heighr) is Error.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#17635]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Entry-SizeHeighr-is-Error/10469366)._

---
[Platforms\Windows\App.xaml]

```xaml
<maui:MauiWinUIApplication.Resources>
    <ResourceDictionary>
        <Style TargetType="TextBox">
            <Setter Property="BorderBrush" Value="Transparent" />
            <Setter Property="BorderThickness" Value="0"/>
        </Style>
    </ResourceDictionary>
</maui:MauiWinUIApplication.Resources>
```

[MainPage.xaml]
```xaml
<VerticalStackLayout Grid.Row="1" Grid.Column="1" WidthRequest="350">
    <Entry x:Name="c_Entry_1" Text="IsEnabled = False" IsEnabled="False"/>
    <Entry x:Name="c_Entry_2" Text="IsEnabled = True" IsEnabled="True"/>
    <Button Text="Test" Clicked="Button_Clicked"/>
</VerticalStackLayout>
```

[MainPage.xaml.cs]
```cs
private void Button_Clicked(object sender, EventArgs e)
{
    StringBuilder sbText = new();

    SizeRequest theSize = this.c_Entry_1.Measure(double.PositiveInfinity, double.PositiveInfinity);
    sbText.AppendLine("Entry IsEnabled = False -> " + theSize.Request.ToString());

    theSize = this.c_Entry_2.Measure(double.PositiveInfinity, double.PositiveInfinity);
    sbText.AppendLine("Entry IsEnabled = True -> " + theSize.Request.ToString());

    this.DisplayAlert("Entry Size", sbText.ToString(), "OK");
}
```
[Result]
![image](https://github.com/dotnet/maui/assets/1096616/968dca2b-2471-4696-84ef-71a1bc068b61)

---
#### 鹰 雪 on 9/18/2023, 10:49 PM: 

(private comment, text removed)
#### Feedback Bot on 9/19/2023, 01:28 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 1. Can not repro on windows machine.
![entryHeighr](https://github.com/dotnet/maui/assets/128687574/1905041a-043b-41c7-8309-381a982bb7bb)
