### ISSUE TITLE
MAUIG1001 An error occured while parsing Xaml: Unexpected XML declaration. Can't build the project.

### ISSUE THREAD

**Issue by MichaelSL** [dotnet/maui#17638]
### Description

Suddenly Visual Studio stopped compiling my MAUI project with the following error:
`MAUIG1001	An error occured while parsing Xaml: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 3, position 7..`
Obviously, project file doesn't start with `<?xml` declaration but starts with `<Project`.

I assume it's a MAUI issue because e. g. ASP.NET projects build is ok.
Before it started VS crashed.

VS version:
```
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.8.0 Preview 2.0
```

I didn't change the `*.csproj` file (it's not marked as modified in git either).

Workloads:
```
ios                        16.4.8825-net8-rc1/8.0.100-rc.1      SDK 8.0.100-rc.1, VS 17.8.34112.27
wasm-tools-net7            8.0.0-rc.1.23419.4/8.0.100-rc.1      SDK 8.0.100-rc.1
maui-windows               8.0.0-rc.1.9171/8.0.100-rc.1         VS 17.8.34112.27
maccatalyst                16.4.8825-net8-rc1/8.0.100-rc.1      VS 17.8.34112.27
android                    34.0.0-rc.1.432/8.0.100-rc.1         VS 17.8.34112.27
```

Can repro building on Windows machine and building for iOS on Mac build host.

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.1.9171

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Relevant log output

```shell
Build started...
1>------ Build started: Project: Tripsta, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\8.0.100-rc.1.23455.8\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>CSC : error MAUIG1001: An error occured while parsing Xaml: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 3, position 7..
1>C:\projects\TrailLocator\TrailLocator\AppShell.xaml.cs(11,9,11,28): error CS0103: The name 'InitializeComponent' does not exist in the current context
1>Done building project "Tripsta.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
========== Build started at 6:13 PM and took 04.428 seconds ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Deploy started at 6:13 PM and took 04.428 seconds ==========
```

**Comment by MichaelSL** [comment]
CLI and Rider build fail with the same error

**Comment by drasticactions** [comment]
As shown by the [error tag](https://github.com/dotnet/maui/blob/main/src/Controls/src/SourceGen/Descriptors.cs), this probably isn't a tooling/IDE related issue, so switching between them won't do anything. Also, I don't believe the error is referencing the csproj. That error, I believe, is from XamlG. It's a source generator. My guess is that if you build a new template project and deploy it, it will most likely work fine. It's something specific to your project and some file within it.

@StephaneDelcroix Do you have ideas on how to debug this?

**Comment by MichaelSL** [comment]
Ok, I found it, it was a non-displayable symbol in `AppShell.xaml`. I believe it got there when VS crashed earlier. I'll close this.

**Comment by StephaneDelcroix** [comment]
> Ok, I found it, it was a non-displayable symbol in `AppShell.xaml`. I believe it got there when VS crashed earlier. I'll close this.

that's what I was about to suggest
