### ISSUE TITLE
Will `PointerPressed` be supported as a visual state in .NET 8?

### ISSUE THREAD

**Issue by MartyIX** [dotnet/maui#17632]
### Discussed in https://github.com/dotnet/maui/discussions/17611

<div type='discussions-op-text'>

<sup>Originally posted by **MartyIX** September 24, 2023</sup>
Currently, MAUI [supports](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/visual-states) in MAUI .NET 7 the following visual states:

*    Normal
*  Disabled
*    Focused
*    Selected
*   PointerOver

Will `PointerPressed` be supported as well? Especially after https://github.com/dotnet/maui/pull/16213 was merged and https://github.com/dotnet/maui/pull/16925 is marked as something that will be delivered in .NET 8 GA.

Regards!</div>

**Comment by jfversluis** [comment]
As you already discovered we are working on it and the still open PR for macOS has the milestone of .NET 8 GA. That means, at this time we're planning to include it. Thanks for your enthusiasm on this!
