### ISSUE TITLE
MAUI Android projects generate an \obj\Debug\net6.0-android\Resource.designer.cs file containing code that ends in 12k+ CS0131 Errors

### ISSUE THREAD

**Issue by patrick-dmxc** [dotnet/maui#17646]
### Description

Hi, i created an new Project with basicly nothing in it, but if i Start the Debugging of an Android Emulator, there is an Resource.designer.cs generated wit 12k+ Errors of CS0131.
No Debugging of android is possible

### Steps to Reproduce

1. Open Project
2. Set Debug to Android-Emulator
3. Debug Android

### Link to public reproduction project repository

https://github.com/Q-light/Q-Light/commit/f4ada3005583fd3e6b40e2b45dbe7d0136e29671

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 33

**Comment by patrick-dmxc** [comment]
[Resource.designer.cs.txt](https://github.com/dotnet/maui/files/12725720/Resource.designer.cs.txt)

**Comment by patrick-dmxc** [comment]
I did some investigatons and found the Trigger for the issue.
So i did a small Project where you can Trigger it.

https://github.com/Q-light/MauiRootNamespace-Bug

Currently the Project is working.

To Trigger the Error:
Open MauiLib1.csproj
Replace:
		<RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
By:
		<RootNamespace>Test</RootNamespace>
Build
And the Error show up.

**Comment by patrick-dmxc** [comment]
In the secound Repo i added in the Comment, the Folder and Project didn't have a space nor a other special sign, and there the Error show up.

**Comment by jfversluis** [comment]
Trying your linked project and it seems to work fine here

![image](https://github.com/dotnet/maui/assets/939291/d419c3b9-86eb-4e48-bace-16f87a5c7f8b)

**Comment by patrick-dmxc** [comment]
Now its working for me as well, if i use "Test" as RootNamespace.
Try <RootNamespace>Test.Test</RootNamespace>

**Comment by patrick-dmxc** [comment]
ok, its funny, 
if "Test.Test" complies, add another ".Test" ant then the Error show up again

**Comment by patrick-dmxc** [comment]
Im running VS 2022 on Windows 11

**Comment by jfversluis** [comment]
Also tried on Windows with Test, Test.Test, Test.Test.Test and then some more tests, I can't reproduce this I'm sorry.

In either case, this seems more something on the Visual Studio side than with us. If you still keep running into this I'd want to ask you to report it through Visual Studio under Help > Provide Feedback > Report a Problem. That will provide them with all the information needed to investigate further.
