### ISSUE TITLE
[Bug] Cant compile a fresh macos project

### ISSUE THREAD

**Issue by LosWochos76** [dotnet/maui#1764]
### Description

Compiling a fresh new macos project fails with the following error (both with Debug and Release):

/usr/local/share/dotnet/sdk/6.0.100-preview.6.21355.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(182,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app.

### Steps to Reproduce

1.  Install maui 6.0.100-preview.6.21355.2 using maui-check on OS X 11.4 
2. Create a blank macos project: dotnet new macos
3. Compile this project: dotnet build

### Expected Behavior

A succesfull build and an executable.

### Actual Behavior

The compilation fails.

### Basic Information

- Version with issue: 6.0.100-preview.6.21355.2

**Comment by caunt** [comment]
I have the same issue.

**Comment by jfversluis** [comment]
Thanks for reporting! Are you still seeing this with all the latest preview bits installed? Thanks!

**Comment by jsuarezruiz** [comment]
@LosWochos76 Could you try again with the latest Preview?. Thanks!

**Comment by jfversluis** [comment]
No answer on repeated ask for more info, closing this for now
