### ISSUE TITLE
Add AddWebAllowedObject extension method for Webview2

### ISSUE THREAD

**Issue by gerthermans** [dotnet/maui#17653]
### Description

In uwp the Webview had a AddWebAllowedObject extension method which allowed us to call c# code in the xamarin app from javascript in the Webview and get a response back if needed. This method is not available for webview2 which is used for winui3. This is stopping our migration to Maui.

### Public API Changes

In some webview handler for windows it should be able to do this:
```
protected override WebView2 CreatePlatformView()
{
    var view = base.CreatePlatformView();
    view.NavigationStarting += async (sender, args) => await View_NavigationStarting(sender, args);
    return view;
}

private async Task View_NavigationStarting(WebView2 sender, Microsoft.Web.WebView2.Core.CoreWebView2NavigationStartingEventArgs args)
{
    var comm = new HtmlCommunicator(); // contains C# code that can be accessed from javascript

    await sender.AddWebAllowedObject("somename", comm);
}
```

### Intended Use-Case

Need to have a way to talk in a request response way from javascript in a webview2 to C# code in the Maui Application. (As how it used to be possible using AddWebAllowedObject)

**Comment by jfversluis** [comment]
> This method is not available for webview2 which is used for winui3.

I think this is the key right here. If this is something that is not implemented in WebView2 there is not much we can do. The "only" thing we as .NET MAUI do is translate the abstract WebView to whatever is used in the underlaying platform. Now that we shifted from UWP to WinUI we're using WebView2 on Windows. However, that does not mean that we are the ones implementing functionality in the WebView2 component.

So looking at the WebView2 repository I found [this issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/212) which also talks about the functionality you mention. While it doesn't have a great resolution, someone links to a [Gist](https://gist.github.com/mqudsi/ceb4ecee76eb4c32238a438664783480) with how they manually added the AddWebAllowedObject to WebView2.

Unfortunately that is about the extend that we can offer here from the .NET MAUI side. If you want more than what is above, make sure to open a request on the WebView2 repository: https://github.com/MicrosoftEdge/WebView2Feedback/
