### ISSUE TITLE
ListView Items Not Taking Full Width of the Screen

### ISSUE THREAD

**Issue by NirmalKumarYuvaraj** [dotnet/maui#17654]
### Description

When embedding a ListView and a Button within a Grid Layout with a height set as Star and Auto, the ListView does not occupy the entire width of the screen. I have confirmed that Xamarin's implementation correctly follows this behavior. I have attached the screenshot of the issue.

![image](https://github.com/dotnet/maui/assets/97871636/202537e1-fe35-48f0-b0f6-76a3241075c8)

Code snippet:

```XML
 <Grid ColumnSpacing="20">
     <Grid.RowDefinitions>
         <RowDefinition Height="*" />
         <RowDefinition Height="Auto" />
     </Grid.RowDefinitions>
     <Grid.ColumnDefinitions>
         <ColumnDefinition Width="*" />
         <ColumnDefinition Width="Auto" />
     </Grid.ColumnDefinitions>
     <ListView ItemsSource="{Binding Monkeys}" Grid.Row="0" Grid.ColumnSpan="2" BackgroundColor="LightBlue" >
         <ListView.ItemTemplate>
             <DataTemplate>
                 <ViewCell>
                     <StackLayout>
                         <Label Text="{Binding Name}" TextColor="Black" FontAttributes="Bold" FontSize="22"/>
                         <Label Text="{Binding Location}"/>
                     </StackLayout>
                 </ViewCell>
             </DataTemplate>
         </ListView.ItemTemplate>
     </ListView>
     <Button Grid.Row="1" Grid.Column="0" Text="Test1"/>
     <Button Grid.Row="1" Grid.Column="1" Text="Test2"/>
 </Grid>
```

### Steps to Reproduce

1.Launch the provided sample application.
2.Choose a ListViewItem within the sample.
3.Observe that while the selection color is applied to the ListView, it does not extend across the entire screen width.

### Link to public reproduction project repository

https://github.com/NirmalKumarYuvaraj/GridWIdthIssue_in_.Net8

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[GridLayoutWidthIssue.zip](https://github.com/dotnet/maui/files/12744740/GridLayoutWidthIssue.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/20d90eca-e5c1-428e-8ec8-f0ddc3bbdf7e)
Android:
![image](https://github.com/dotnet/maui/assets/97647558/64676b11-7a2f-49fe-8beb-439f7f82c16e)
iOS: No selection color is applied to the ListView.
![image](https://github.com/dotnet/maui/assets/97647558/c65765e7-0e1b-4f84-a50e-42d36ef55ac4)

**Comment by hartez** [comment]
The ListView (with the LightBlue background) is taking the full width of the screen. The ListView _items_ are not taking the full width of the screen, as shown by the selection highlight.
