### ISSUE TITLE
problem with .NET MAUI

### ISSUE THREAD

**Issue by mirekXkuzna** [dotnet/maui#17650]
Problem encountered on visual studio 2022 
Operating System: windows

So i got a problem,after instaling a .NET MAUI extension i try to create a project and i dont have option to create net maui project even after reinstaling it couple times still dont work.

**Comment by jfversluis** [comment]
Hey @mirekXkuzna! Thank you for your interest in .NET MAUI, sorry you ran into a snag here.

Just to verify: are you running on Windows? And you mention the .NET MAUI Extension, do you use Visual Studio 2022 or VS Code?

If you run `dotnet new --list` does that show the .NET MAUI option at all? Where do you expect to see the option to create a new .NET MAUI project but don't see it now? Thanks!

**Comment by mirekXkuzna** [comment]
im running on windows and im using vs2022 and it is not showing .NET MAUI
