### ISSUE TITLE
Entry's SelectionLength property is not updating initially on Android, Mac and iOS platforms. 

### ISSUE THREAD

**Issue by SF3969** [dotnet/maui#17657]
### Description

The SelectionLength property in Entry control is experiencing an issue on Android, Mac, and iOS platforms where it fails to update correctly upon initial use.

### Steps to Reproduce

Step 1: Create a sample in .NET MAUI
Step 2: Initialize the Entry .
Step 3: Set SelectionLength property.
Step 4: Execute the application on Android or Mac or iOS platform.

**Sample code**
``` 
<Entry SelectionLength="4" 
       Text="DotNet Maui"/>
```

https://github.com/dotnet/maui/assets/127308786/0ce4d1b5-bc4a-4b3b-b36e-afa4c7829bae

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

_NA_

### Did you find any workaround?

_NA_

### Relevant log output

_NA_

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Android 13.0-API33, not repro on Windows 11 and iOS 16.4 with below Project:
[17657.zip](https://github.com/dotnet/maui/files/12744852/17657.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/d911f2ef-f875-4c43-83bf-8842fc82e571)

iOS:
![image](https://github.com/dotnet/maui/assets/97647558/d015388d-843e-4518-9651-dc61c78ef3c1)
