### ISSUE TITLE
[Android] Images from URLs are not rendered if you do not specify a fixed size

### ISSUE THREAD

**Issue by unombun** [dotnet/maui#17651]
### Description

In a MAUI app if you navigate to page where you a collection view of images, the images are not rendered.
For this to reproduce the source of the images should be URLs, and the image should not have a defined width and height request.

### Steps to Reproduce

1. Create a Maui Android App
2. Navigate to a new screen
3. There is a collection view with images
4. The image does not have a width and height specified
5. The source of the image is an URL
6. The images are not rendered

### Link to public reproduction project repository

https://github.com/flesarradu/AndroidImageIssue

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Doesn't repro on .NET 8 RC1 so there is a fix out there that we probably want to backport to .NET 7 to fix this.

**Comment by BenBtg** [comment]
I can repro this issue using the sample provided in .NET 7 and can confirm is fixed in 8.0.100-rc.1.23463.5

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio Enterprise 17.10 Preview 1.0 on net7, can use sample project to reproduce.
