### ISSUE TITLE
Clarification: Xcode 13 beta requirement

### ISSUE THREAD

**Issue by dasMulli** [dotnet/maui#1766]
I see that the requirement for Xcode changed to 13 beta 1 or higher.

Unfortunately, this is not available on public GitHub or Azure Pipelines hosted agents, making it impossible to update some projects to preview6 or higher until the macos-11 pools are generally available - https://github.com/actions/virtual-environments/issues/2486 (we're using Azure DevOps).

Is this a hard requirement or is it possible to work around it for now?

**Comment by Redth** [comment]
It's a requirement and Preview 7 will require 13 Beta 3 or higher.  There are no plans to support < Xcode 13 for .NET MAUI.
