### ISSUE TITLE
Maui for ios RTL modes problem with ScrollView 

### ISSUE THREAD

**Issue by WAEL20221** [dotnet/maui#17674]
### Description

Maui for ios RTL modes problem with ScrollView .

Example:
```
<ScrollView Orientation="Horizontal" >
................
................
................
................

</ScrollView>
```

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.0-rc.1.9171

### Affected platforms

iOS

### Affected platform versions

ios 15.7.7

**Comment by ninachen03** [comment]
Can not repro this issue at iOS Simulator on the latest Visual Studio 17.10.0 Preview 2. If updating to the latest VS still reproduces, please provide the sample project and expected effects.
