### ISSUE TITLE
MAUI: Listview button is partially visible on UI even with HasUnevenRows

### ISSUE THREAD

**Issue by sreejithsreenivasan139** [dotnet/maui#17683]
### Description

I am facing a weird issue with listview. I have a button in my listview and it is not completely visible on UI like below screenshot:

![Screenshot_20230926_204543](https://github.com/dotnet/maui/assets/118500242/b6c14959-964e-430f-98eb-e9efd3c2db39)

### Steps to Reproduce

**My code:**

**MainPage.xaml:**

	<?xml version="1.0" encoding="utf-8" ?>
	<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
				 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
				 x:Class="ListviewDemo.MainPage">

		<StackLayout>
			<ListView  
				Margin="5"
				SeparatorColor="#cecece"
				x:Name="datalistview"
				HasUnevenRows="True">
				<ListView.ItemTemplate>
					<DataTemplate>
						<ViewCell>
							<StackLayout 
								HorizontalOptions="FillAndExpand" 
								Orientation="Vertical" 
								Padding="5" 
								Margin="5">

								<Label 
									Text="{Binding title}"
									Style="{StaticResource RequestListviewStyle}"/>

								<Label 
									Margin="0,5,0,0"
									Text="{Binding description}"
									VerticalOptions="Center"
									VerticalTextAlignment="Center">
									<Label.FontSize>
										<OnIdiom x:TypeArguments="x:Double">
											<OnIdiom.Phone>15</OnIdiom.Phone>
											<OnIdiom.Tablet>23</OnIdiom.Tablet>
											<OnIdiom.Desktop>15</OnIdiom.Desktop>
										</OnIdiom>
									</Label.FontSize>
								</Label>

								<StackLayout
									Margin="0,5,0,0"
									Orientation="Horizontal">

									<Label 
										VerticalOptions="CenterAndExpand"
										VerticalTextAlignment="Center"
										HorizontalOptions="Start"
										HorizontalTextAlignment="Start"
										Text="{Binding time}">
										<Label.FontSize>
											<OnIdiom x:TypeArguments="x:Double">
												<OnIdiom.Phone>12</OnIdiom.Phone>
												<OnIdiom.Tablet>18</OnIdiom.Tablet>
												<OnIdiom.Desktop>12</OnIdiom.Desktop>
											</OnIdiom>
										</Label.FontSize>
									</Label>

									<Button 
										Text="New"
										TextColor="White"
										BackgroundColor="#81c124"
										HorizontalOptions="EndAndExpand"
										Style="{StaticResource MyRequesterButtonStyle}"/>
								</StackLayout>
							</StackLayout>
						</ViewCell>
					</DataTemplate>
				</ListView.ItemTemplate>
				<ListView.Footer>
					<Label/>
				</ListView.Footer>
			</ListView>
		</StackLayout>
	</ContentPage>

**MainPage.xaml.cs:**

	using Microsoft.Maui.Graphics.Text;
	using Newtonsoft.Json;
	using System.Collections.ObjectModel;
	using System.ComponentModel;
	using System.Diagnostics;
	using System.Net.Http.Headers;
	using System.Runtime.CompilerServices;
	using System.Security.AccessControl;

	namespace ListviewDemo
	{
		public partial class MainPage : ContentPage
		{
			public ObservableCollection<Data> dataCollection;
			public MainPage()
			{
				InitializeComponent();
				dataCollection = new ObservableCollection<Data>();
				SetData();
			}
			
			private void SetData()
			{
				dataCollection.Clear();
				dataCollection.Add(new Data() { title = "data 1", description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.", time = "01-01-2023" });
				dataCollection.Add(new Data() { title = "data 1", description = "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.", time = "01-01-2023" });
				dataCollection.Add(new Data() { title = "data 1", description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.", time = "01-01-2023" });
				dataCollection.Add(new Data() { title = "data 1", description = "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.", time = "01-01-2023" });
				datalistview.ItemsSource = dataCollection;
			}
		}

		public class Data
		{
			public string title { get; set; }
			public string description { get; set; }
			public string time { get; set; }
		}
	}

**Styles:**

	<Style x:Key="RequestListviewStyle" TargetType="Label">
		<Setter Property="FontAttributes" Value="Bold"/>
		<Setter Property="FontSize">
			<OnIdiom
			x:TypeArguments="x:Double"
			Phone="17"
			Tablet="26"
			Desktop="17"/>
		</Setter>
	</Style>

	<Style x:Key="MyRequesterButtonStyle" TargetType="Button">
		<Setter Property="VerticalOptions" Value="Start"/>
		<Setter Property="CornerRadius" Value="{OnIdiom Phone=20, Tablet=40}" />
		<Setter Property="FontSize">
			<OnIdiom
				x:TypeArguments="x:Double"
				Phone="12"
				Tablet="21"
				Desktop="14"/>
		</Setter>
		<Setter Property="HeightRequest">
			<OnIdiom
				x:TypeArguments="x:Double"
				Phone="35"
				Tablet="60"
				Desktop="40"/>
		</Setter>
		<Setter Property="WidthRequest">
			<OnIdiom
				x:TypeArguments="x:Double"
				Phone="120"
				Tablet="225"
				Desktop="150"/>
		</Setter>
	</Style>

Listview has HasUnevenRows="True" property. I tried a lot to find out the reason behind this, but no luck.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

1.Use Grid instead of StackLayout

	<Grid
	   Margin="0,5,0,0"
	   >

	   <Label 
		   VerticalOptions="CenterAndExpand"
		   VerticalTextAlignment="Center"
		   HorizontalOptions="Start"
		   HorizontalTextAlignment="Start"
		   Text="{Binding time}">
		   ...
	   </Label>

	   <Button 
		   Text="New"
		   TextColor="White"
		   .../>
	</Grid>
	
2.Add the below margin for android

	<StackLayout
		 Margin="0,5,0,20"
		 Orientation="Horizontal">

**Comment by drasticactions** [comment]
Thank you for providing the code, but could you please turn this into a reproduction project? it'll make it easier for us to verify the issue when we both have the same codebase.

**Comment by sreejithsreenivasan139** [comment]
I have uploaded a sample project [here](https://drive.google.com/file/d/1at_Z5f-8oC3DZssiLDRAejbKbAEa--GZ/view).

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0. This issue repro on Android 13.0-API33(**7.0.92**), not repro on Android 13.0-API33(**8.0.0-rc.1.9171**), Windows 11 and iOS 16.4 with below Project:
[ListviewDemo(.NET 8).zip](https://github.com/dotnet/maui/files/12839893/ListviewDemo.NET.8.zip)

Android(.NET 8):
![image](https://github.com/dotnet/maui/assets/97647558/3491c379-b9d9-40ce-84c3-002706b913ea)
