### ISSUE TITLE
[MAUI] Click the "+"/"-" button to move the cursor, and the cursor disappears

### ISSUE THREAD

**Issue by kevinxufei** [dotnet/maui#17687]
### Description

Click the "+"/"-" button to move the cursor, and the cursor disappears

### Steps to Reproduce

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Windows.
2. Navigate to 'D Editer' -> 'D10' and Click the "+"/"-" button to move the cursor.
3. The cursor disappears.

**Note: The issue not repro on Android Emulator**

Actual Behavior:
Click the "+"/"-" button to move the cursor, and the cursor disappears
![maui1](https://github.com/dotnet/maui/assets/86938401/0bae0536-544c-4b5f-89a6-d7d8c22e85dc)

Expected Behavior:
After clicking the "+"/"-" button to move the cursor, the cursor is moved and displayed according to the "+/-" operation

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

Microsoft.Maui.Controls: 8.0.0-nightly.9318+sha.2d8cf282d1-azdo.8448823
.NET SDK: 8.0.100-rc.1.23463.5

### Is this a regression from previous behavior?

This bug is not a regression, it can be reproduced in the latest stable release: 8.0.0-rc.1.9171.
### Affected platforms

Windows

**Comment by kevinxufei** [comment]
I have uploaded binglogs and xamarin.logs
[Xamarin.zip](https://github.com/dotnet/maui/files/12736934/Xamarin.zip)
[binglogs.zip](https://github.com/dotnet/maui/files/12736935/binglogs.zip)

**Comment by rachelkang** [comment]
Not an issue. We will update the instructions to better capture the necessary steps for this test case.

Clicking on the button will take away focus from the editor, but pressing Tab to return focus to the ditor will show the cursor position in the updation position.
