### ISSUE TITLE
Server 2022 - Maui app with net .7 is not working

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#17688]
### Description

Hi,

I installed Maui app on server 2019 with this command and its works but on server 2022 its not work:

dotnet publish -f net7.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d"

I also installed .NET7 on server 2019 + 2022 :

https://dotnet.microsoft.com/en-us/download - .NET 7.0

Why is not work on 2022 ?

The error:
![image](https://github.com/dotnet/maui/assets/1079689/a56dcf53-a657-41da-97ab-268ddb7b976e)

### Steps to Reproduce

See description

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

Windows

### Affected platform versions

..

### Did you find any workaround?

No workaround.

**Comment by danies8** [comment]
.net 6 work in server 2022

**Comment by jfversluis** [comment]
Looks like that is related to this: https://github.com/microsoft/WindowsAppSDK/issues/2829

Can you confirm the mentioned update is installed that is mentioned in the linked issue? Do you have any addition log information from the Windows Event Log?

**Comment by danies8** [comment]
No information from information from the Windows Event Log.
I will install  KB5018485 as an optional update directly through windows update and see if there is problem.
I will update this ticket.
Thanks

**Comment by danies8** [comment]
I install brand new server 2022 and run the maui app as exe and is work!!

**Comment by danies8** [comment]
**standard** server 2022

**Comment by jfversluis** [comment]
OK seems like some kind of prerequisite error then. Glad you figured it out!
