### ISSUE TITLE
WinUI - Circle view not rotating from center

### ISSUE THREAD

**Issue by RanjithkumarSyncfusion** [dotnet/maui#17694]
### Description

When loading a graphics view with circle fill and on rotation It gets hovered on bottom control. When loading a rect this is fine, but a circle must rotate within the bounds.

### Steps to Reproduce

Please refer the attached sample -
[MauiApp1.zip](https://github.com/dotnet/maui/files/12739015/MauiApp1.zip)

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

No.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Windows 11, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[MauiApp1.zip](https://github.com/dotnet/maui/files/12839937/MauiApp1.zip)

![Windows](https://github.com/dotnet/maui/assets/97647558/204dbe4c-a2d5-4992-b9c7-2f79fba02ddf)
