### ISSUE TITLE
Android : Maui rc-1 crash on android

### ISSUE THREAD

**Issue by SamuelJames101** [dotnet/maui#17697]
### Description

Background the app
re-open the app from the phones home screen

Expected results
Opens fine

Actual results crashes

I have added a video here to show my devices screen and the crash VS for Mac shows. 

### Steps to Reproduce

1. Create a brand new .Net8 Maui app. (I have added a repo just in case however)
2. Background the app
3. re-open the app from the home screen
(Do not use the ( ||| ) to re-open the the same window as the issue won't occur. 
[Screen Recording 2023-09-27 at 16.24.03.mov.zip](https://github.com/dotnet/maui/files/12740500/Screen.Recording.2023-09-27.at.16.24.03.mov.zip)

### Link to public reproduction project repository

https://github.com/SamuelJames101/AndroidCrash

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (Samsung S20)

**Comment by PureWeen** [comment]
It looks like your repro link is incorrect.

**Comment by SamuelJames101** [comment]
@PureWeen Hi, I pulled down my GitHub under that link and was able to build and deploy it to an Android device. What issue are you seeing? If you continue to have issues though, it's just a blank app project anyway with 0 changes.

**Comment by jsuarezruiz** [comment]
A screenshot from the crash:
![image](https://github.com/dotnet/maui/assets/6755973/c164044f-3646-4247-a9bf-bb5f7a4dc5ec)

**Comment by SamuelJames101** [comment]
I am still seeing this on the release candidate 2

**Comment by SamuelJames101** [comment]
@jsuarezruiz I can see that it doesn't happen as often with Net8 GA but still running into the issue every now and then. When is this being fixed?

**Comment by SamuelJames101** [comment]
It is better but still crashes, easiest way to get this crash now is have the app create a local notification. Click on it (this will attempt to open the app) it'll then crash.

**Comment by ninachen03** [comment]
Thanks for your reply. I can repro this issue now.
![image](https://github.com/dotnet/maui/assets/128687574/0758932d-ba07-42f6-b25a-0ac405cb6ad3)

**Comment by PureWeen** [comment]
Try setting the launchmode to single top in your android activity

If you run MAUI with the latest version the exception message will give you instructions where to add
