### ISSUE TITLE
Only first Item in CollectionView is Visible on Android

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#17709]
### Description

Their are four items in ObservableCollection bound to a CollectionView. But only the first item is visible on Android. 

### Steps to Reproduce

Run the reproduction project on the Android. 

### Link to public reproduction project repository

https://github.com/HobDev/DotNet8MauiBugs/tree/CollectionViewDataIssue

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

No

**Comment by paulvarache** [comment]
Removing the `ItemSizingStrategy` displays all items. I assume the `MeasureFirstItem` strategy is getting a 0

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Android 13.0-API33, not repro on Windows 11 and iOS 16.4 with below Project:
[DotNet8MauiBugs.zip](https://github.com/dotnet/maui/files/12840360/DotNet8MauiBugs.zip)

![image](https://github.com/dotnet/maui/assets/97647558/607f9478-f1a3-4996-b1d1-79733dc1211e)

**Comment by dotMorten** [comment]
Just hit this with .NET 7 SDK as well.
