### ISSUE TITLE
App crash on button click in CollectionView Item

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#17707]
### Description

There are two buttons in a CollectionView ItemTemplate. Starangely the app crashes on clicking the first button. But strangely the app does not crash on clicking the second button.

### Steps to Reproduce

Run the reproduction app. Try Clicking on the buttons in one of the CollectionView items.

### Link to public reproduction project repository

https://github.com/HobDev/DotNet8MauiBugs/tree/CollectionViewDataIssue

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

NO

**Comment by nor0x** [comment]
same!
Here is a repro
https://github.com/dotnet/maui/issues/11956#issuecomment-1717415080

**Comment by samhouts** [comment]
@nor0x I see you're also using the CommunityToolkit. Does it repro without that?

**Comment by PureWeen** [comment]
@HobDev can you test nightly? https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by HobDev** [comment]
@PureWeen  I added https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json in the Package Sources  and Package Source Mapping of the Visual Studio 17.8.0 Preview 2.0. What should I do next to work with the nightly builds.

**Comment by HobDev** [comment]
@drasticactions I can confirm that that removing CommunityToolkit.Mvvm code resolves the issue.  Can this issue be moved the [communitytoolkit](https://github.com/CommunityToolkit/dotnet) repo.

While testing the code without CommunityToolkit.Mvvm and CommunityToolkit.Maui.Markup I catch another two bugs in the CollectionView which are reported [here](https://github.com/dotnet/maui/issues/17735) and [here](https://github.com/dotnet/maui/issues/17736).

**Comment by nor0x** [comment]
> @nor0x I see you're also using the CommunityToolkit. Does it repro without that?

will check that today 👍

**Comment by samhouts** [comment]
This issue was moved to xamarin/XamarinCommunityToolkit#1989
