### ISSUE TITLE
SecureStorage GetAsync not working in .NET 8 MAUI

### ISSUE THREAD

**Issue by DharunAR** [dotnet/maui#17706]
### Description

I am in the process of Migrating our mobile app from Xamarin to MAUI. I have found that SecureStorage.Default.GetAsync(ID_TOKEN); method not executing or returning any value in .NET 8. The same code is working for NET 7 but the issue happens only with the NET8(Preview) version.

I am using Visual Studio 2022 Version 17.8.0 Preview 2.0

This is a similar issue already reported on https://github.com/dotnet/maui/issues/12341. 

### Steps to Reproduce

- Create a sample MAUI application with .NET 8.
- Create two buttons, one for get and another for Set(SecureStorage.GetAsync and SecureStorage.SetAsync)
- Execute the MAUI app and click on the Setasync button(*this is randomly set an string value)
- Close the app
- Re-open the same app and click on GetAsync button.
- await getSecureStorage is kept waiting and the call is not executed 

### Link to public reproduction project repository

https://github.com/DharunAR/SecureTest/

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.49

### Affected platforms

Android

### Affected platform versions

Android 12 and Android 13

### Did you find any workaround?

No.

### Relevant log output

```shell
No
```

**Comment by moljac** [comment]
@DharunAR 

I cannot access https://github.com/DharunAR/SecureTest/

**Comment by DharunAR** [comment]
Can you please try now? I have added public access.

**Comment by moljac** [comment]
OK. Got it. Trying to repro

**Comment by leonluc-dev** [comment]
I can confirm this is also happening with .NET 8 RC 1 for the `net8.0-android` runtime.
It only occurs on Android. iOS doesn't seem to have this issue. (in both .NET MAUI and .NET for iOS/Android native projects)

I also managed to reproduce this if the project runtime is set to `net7.0-android`

**Comment by andyzukunft** [comment]
I can confirm the issue.

I just debugged into the reason my app won't go beyond the Splash Screen after changing from `net7.0-android33` to `net8.0-android34` (using MAUI .NET 8 RC1). Trying to use `SecureStorage.Default.GetAsync("key")` never returns.

This was still working with MAUI .NET 8 Preview 1.

**Comment by andyzukunft** [comment]
I debugged the behaviour further. So far this is what I know:
1. It is an issue relating to Secure Storage. Possibly related to the newest changes.
2. In my case it seems to occur when accessing the Secure Storage during app startup (App.xaml.cs constructor) and blocking the app startup progression (using Wait() or similar) until data is received. Not doing so (meaning: using async calls) will return data.

**Comment by DharunAR** [comment]
So if it is the newest changes from SecureStorage causing this issue, this would be fixed in the upcoming preview version?

**Comment by leonluc-dev** [comment]
It looks like this broke when issue #12341 was fixed. The issues seem to be very similar too.
The problem is that my app is affected by both issue #12341 in .NET 6/7 and issue #17706 in .NET 8 RC2.

I am calling the `SecureStorage.GetAsync()` method a few moments after app startup. The invocation of the SecureStorage itself is in an async/await method but further up the call stack there is a `GetAwaiter().GetResult()` pattern (leading to a similar effect to what others have noted earlier with the `Wait()` calls).

**Comment by leonluc-dev** [comment]
While waiting for release of .NET 8 SR1, is there any known workaround to avoid this issue?

Reverting to `net7.0-android` strangely enough doesn't resolve the issue for me. The Task returned by `SecureStorage.GetAsync()` still never completes.

**Comment by alexanderdibenedetto** [comment]
Will this be in the general availability release? I think I speak for all of us when I say we're blocked on .NET MAUI Android releases until this is released.

**Comment by Redth** [comment]
PR #17928 will not be in the GA release, but is already merged and will be in the first servicing release.  We are hoping to have a preview of that first servicing release available on NuGet around the same time GA is released.

**Comment by alexanderdibenedetto** [comment]
Thank you @Redth - the sooner the better; we already had to implement that "legacy" secure storage to update from XF to .NET MAUI, and now this too. It's just really difficult to make this transition with all of these issues - feels like we're back to XF 2.0 days.

**Comment by omidalig** [comment]
Using as below solved my problem:

var someSecureValue = Task.Run(async () =>  await SecureStorage.Default.GetAsync("SomeKey")).Result;

**Comment by sk1llsh0t** [comment]
awaiting the getasync method worked for me in debug. But when i change from debug configuration to release configuration, the linker breaks securestorage retrieval.

I get this error...
Field version_ for com.google.crypto.tink.proto.AesSivKeyFormat not found

**Comment by andyzukunft** [comment]
A couple days ago I encountered the same error as sk1llsh0t within my log server trying to Read/Write on SecureStorage. I don't know if this behaviour is new with .NET 8 GA as the app integration to the log server is new.

The error message is:
`java.lang.NoSuchFieldError: no "Landroidx/security/crypto/EncryptedSharedPreferences$PrefKeyEncryptionScheme;" field "AES256_SIV" in class "Landroidx/security/crypto/EncryptedSharedPreferences$PrefKeyEncryptionScheme;" or its superclasses`

I can confirm this ONLY happens on Release build and possibly not on emulator devices. I think I was only able to reproduce the behaviour on physical devices (via Google Store, directly to device).

**Comment by sk1llsh0t** [comment]
>  I think I was only able to reproduce the behaviour on physical devices

I do all my testing/development on a physical device which is where i'm seeing the issue.

**Comment by dellis1972** [comment]
My guess is this field is being removed by the android `r8` linker. 
So this documentation although its xamarin based will still apply to .net andorid https://learn.microsoft.com/xamarin/android/deploy-test/release-prep/proguard

You can try to add a proguard `-keep` rule to ensure that the required field is not stripped out by the java linker.

**Comment by sk1llsh0t** [comment]
For my particular issue, I added this proguard rule which appears to be a good workaround:

-keep class com.google.crypto.tink.proto.** { *; }

**Comment by ozersenol** [comment]
When I build debug/release and simullator and real device, When app starts first time, previously stored value from SecureStorage is not read and returns nul from GetAsync method. But running app I can store data in SS and can get / read it normally.

**Comment by NunoBem** [comment]
> When I build debug/release and simullator and real device, When app starts first time, previously stored value from SecureStorage is not read and returns nul from GetAsync method. But running app I can store data in SS and can get / read it normally.

Having the same issue @ozersenol. Found any workaround?

**Comment by ozersenol** [comment]
@NunoBem  I rolled back my project to .Net 7 and waiting for MS team to resolve this issue.

**Comment by andyzukunft** [comment]
"When app starts first time, previously stored value" this is a contradiction. So I assume you have deinstalled the app, deployed / installed it again and THEN you get an error?

Yes, this seems to be a regression. I believe there is an open issue for this somewhere. This has nothing to do with GetAsync() afaik.

If you need to be able to install / reinstall with a working secure store the app you can set "allowBackup=false" in the AndroidManifest.xaml. I am not sure whether pre-existing secure store data can be used or if they need to be re-populated again.

**Comment by NunoBem** [comment]
Ok my case was after logout I removed all keys `SecureStorage.Default.RemoveAll();` and then after login again, the values where always available. BUT, closing and reopening the app, made the keys all vanished.

So, after a few hours around this, I got to a workaround. Have to remove the keys 1 by 1 ( `SecureStorage.Default.Remove("xxx");` ), and it works.

Hope it helps others.

**Comment by uperp** [comment]
> 好的，我的情况是在注销后我删除了所有密钥，然后在再次登录后，这些值始终可用。但是，关闭并重新打开应用程序，使密钥全部消失。`SecureStorage.Default.RemoveAll();`
> 
> 所以，经过几个小时的思考，我找到了一个解决方法。必须逐个 1 （ ） 删除键，它就可以工作了。`SecureStorage.Default.Remove("xxx");`
> 
> 希望它能帮助到其他人。

我遇到了相同问题，但情况有所不同，在我登出时
 bool ok = SecureStorage.Default.Remove("xxx");
 string xxx= await SecureStorage.Default.GetAsync("xxx");
 if (ok && string.IsNullOrEmpty(xxx))
     Application.Current.Quit();
     
 为了调试，有意在删除后又重新获取,此时证实确实已删除
 但是不能理解的是
 下次启动APP时
 string xxx= await SecureStorage.Default.GetAsync("xxx");
 xxx又复活了，天呐，谁在阻止删除敏感信息？

**Comment by chathudan** [comment]
I had the same issue after upgrading to .NET 8 with ` GetAwaiter().GetResult()` . 

`SecureStorage.Default.GetAsync(Constants.CLAIM_OAUTH_TOKEN).GetAwaiter().GetResult();` 

and got it working after replacing 

`Task.Run(async () => await SecureStorage.Default.GetAsync("SomeKey")).Result`

**Comment by PavloLukianets** [comment]
The issue is still present in nightly builds. @jsuarezruiz, only the workaround above helps.

**Comment by jeff-eats-pubsubs** [comment]
I am having this issue on Emulator as well after returning to Android dev from iOS. Pixel 5 & 6 Api 33 & 34.

**Comment by AdrianoBinhara** [comment]
I'm also having this issue after yesterday.
It was working fine even after updating to .net 8, but all of a sudden it stopped working.

**Comment by motmot80** [comment]
Same here. Android 8.1 and .NET and MAUI. 

But the `Task.Run` workaround did work!

**Comment by Baraiboapex** [comment]
> I had the same issue after upgrading to .NET 8 with ` GetAwaiter().GetResult()` .
> 
> `SecureStorage.Default.GetAsync(Constants.CLAIM_OAUTH_TOKEN).GetAwaiter().GetResult();`
> 
> and got it working after replacing
> 
> `Task.Run(async () => await SecureStorage.Default.GetAsync("SomeKey")).Result`

Thank you so much chathudan! This worked for me! :)

**Comment by eapeldoorn** [comment]
Still not working. After closing the app and restarting it SecureStorage.Default.GetAsync("authorizationKey") returns null.

Visual Studio Professional 2022 version 17.8.7

MAUI version 8.0.6

Tested on emulated devices:
Android 12.0 (API 31)
Android 13.0 (API 33)
Android 14.0 (API 34)

Tested on physical device:
Samsung (Android 11 API 30)

**Comment by ssbssb-cmd** [comment]
> `SecureStorage.Default.GetAsync(Constants.CLAIM_OAUTH_TOKEN).GetAwaiter().GetResult();`



> > I had the same issue after upgrading to .NET 8 with ` GetAwaiter().GetResult()` .
> > `SecureStorage.Default.GetAsync(Constants.CLAIM_OAUTH_TOKEN).GetAwaiter().GetResult();`
> > and got it working after replacing
> > `Task.Run(async () => await SecureStorage.Default.GetAsync("SomeKey")).Result`
> 
> Thank you so much @chathudan! This worked for me! :)


Not sure why this is marked as closed. I still cannot run it using the normal 
```
await SecureStorage.Default.GetAsync
```

but the workaround @chathudan put does work for me.

**Comment by eapeldoorn** [comment]
> Still not working. After closing the app and restarting it SecureStorage.Default.GetAsync("authorizationKey") returns null.

My bad. SecureStorage.Default.RemoveAll() was causing the issue in my case.

**Comment by jonebersole** [comment]
> Using as below solved my problem:
> 
> var someSecureValue = Task.Run(async () => await SecureStorage.Default.GetAsync("SomeKey")).Result;

This works for both GetAsync and SetAsync calls. Thanks for the tip!

**Comment by jonebersole** [comment]
> > var someSecureValue = Task.Run(async () => await SecureStorage.Default.GetAsync("SomeKey")).Result;
> 
> The workaround above now throws this exception:AggregateException_ctor_DefaultMessage
> 
> ```
> try
> {
>     jsonState = Task.Run(async () => await SecureStorage.Default.GetAsync(DataKey)).Result;
> }
> catch(Exception e)
> {
>     throw new Exception("Failed to read the stored queue information. " + e.Message, e);
> }
> ```

Make sure you have secure storage as an allowed permission for your target OS. I forgot this when creating a new app recently. I had to remove the Async part of the request (just a normal non-async call) and put in a try catch and the exception told me that i dont have secure storage permissions. Doh! Added secure storage to my iOS app as a permission and it worked fine after that.

**Comment by jonebersole** [comment]
> > Make sure you have secure storage as an allowed permission for your target OS. I forgot this when creating a new app recently. I had to remove the Async part of the request (just a normal non-async call) and put in a try catch and the exception told me that i dont have secure storage permissions. Doh! Added secure storage to my iOS app as a permission and it worked fine after that.
> 
> I added read permission (we already had write permission).
> 
> ```
> 	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
> 	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
> ```
> 
> Still get the same exception AggregateException_ctor_DefaultMessage.

I could be wrong, but i thought writing to external storage was a different permission than 'secure storage'. maybe check on that. I can't look that up right now, but I will have to do that later when I get a chance.

**Comment by b-f-** [comment]
> > > Make sure you have secure storage as an allowed permission for your target OS. I forgot this when creating a new app recently. I had to remove the Async part of the request (just a normal non-async call) and put in a try catch and the exception told me that i dont have secure storage permissions. Doh! Added secure storage to my iOS app as a permission and it worked fine after that.
> > 
> > 
> > I added read permission (we already had write permission).
> > ```
> > 	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
> > 	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Still get the same exception AggregateException_ctor_DefaultMessage.
> 
> I could be wrong, but i thought writing to external storage was a different permission than 'secure storage'. maybe check on that. I can't look that up right now, but I will have to do that later when I get a chance.

Permission requirements are not explicitly mentioned in [documentation](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/secure-storage?view=net-maui-9.0&tabs=android)
On Android, I never had these permissions enabled and it used to work just fine until some workload update.

**Comment by danheinz** [comment]
If it helps, my Android SDK targets are:
`<uses-sdk android:minSdkVersion="29" android:targetSdkVersion="34" />`

Why is this issue closed?  It says it was fixed in [](https://github.com/dotnet/maui/pull/17928) (.NET 8 SR1), but obviously, it is not.

**Comment by danheinz** [comment]
I ended up just using Preferences.Default for storage on Android for now.  While not secure, it will at least be a workaround until this is fixed.
