### ISSUE TITLE
VS Code Mac, Output HE0031: Failed to mount developer tools on iPhone

### ISSUE THREAD

**Issue by hattmann** [dotnet/maui#17718]
### Description

Launching 'com.companyname.mauitest' on the device 'iPhone von Andreas'
warning HE0030: Could not mount developer tools on 'iPhone von Andreas': Could not locate device support files
warning HE0031: Failed to mount developer tools on 'iPhone von Andreas'.
warning HE0030: Could not mount developer tools on 'iPhone von Andreas': Could not locate device support files

Failed to launch the application 'com.companyname.mauitest' on the device 'iPhone von Andreas': Invalid Service Error (error: 0xe8000022)
. You can still launch the application manually by tapping on it.

### Steps to Reproduce

Create New Maui Project
Try to deploy it on my iPhone (just updated to IOS 17.0.2.

Testet with VS Code and with VS Mac

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by samhouts** [comment]
@emaf @dalexsoto Thoughts?

**Comment by hattmann** [comment]
Microsoft must provide an update to develop with maui for IOS 17. All i can do is to wait and hope for an update.

**Comment by samirgcofficial** [comment]
+1

**Comment by rolfbjarne** [comment]
For the record, this is a duplicate of https://github.com/xamarin/xamarin-macios/issues/19101.
