### ISSUE TITLE
Memory leak with CarouselView

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#17726]
### Description

On android with `net8-rc.1`, when navigating to a page containing a `CarouselView` and then back, the memory usage grows.
For comparison, no memory leak when navigating to a page containing a `CollectionView` with the same `ItemsSource` and `ItemTemplate`.

### Steps to Reproduce

1. Open repro project
2. On the first tab, tap on `Go` button, it will navigate to a page with a `CollectionView`.
3. Go back to the main page. Repeat a few times. Observe memory usage with dotnet-gcdump. It is stable.
4. On the second tab, tap on `Go` button, it will navigate to a page with a `CarouselView`.
5. Go back to the main page. Repeat a few times. Observe memory usage with dotnet-gcdump. It is slowly increasing.
6. Alternatively, open the attached gcdump files I've captured when showing the `CarouselView` page a few times. Between the first (memory-20.gcdump) and second (memory-24.gcdump), the memory usage increases quite a lot (the page is really simple).

[gcdump.zip](https://github.com/dotnet/maui/files/12753203/gcdump.zip)

![Screenshot 2023-09-28 172824](https://github.com/dotnet/maui/assets/12516566/38314f44-ba41-4473-8cad-b0633a201ab1)

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppCarouselViewLeak

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 34

### Did you find any workaround?

No workaround

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by jonathanpeppers** [comment]
@tranb3r I compared your two `.gcdump` files above and I only see:

![image](https://github.com/dotnet/maui/assets/840039/bbcdaf69-3ba0-4af7-be19-1776e6038d53)

It will probably take a Java side GC + .NET GC for these `IdentityHashTarget` objects to go away, this should eventually be called:

https://github.com/xamarin/xamarin-android/blob/0945978452a357f0dd8eb89d9c1bca523bbe0e5c/src/Mono.Android/Android.Runtime/AndroidRuntime.cs#L792

If you do something like this, are the MAUI `Page` objects going away in your sample?

![image](https://github.com/dotnet/maui/assets/840039/ba0f00b4-f519-4652-a93b-b2e9c76051ff)

I was hoping to see more than one `Page2` object in your `.gcdump` files, but it only has 1. If you somehow see many `Page2`'s living forever, that 100% seems like it would be a leak in MAUI.

**Comment by nmanocha** [comment]
This problem is reproducible with iOS also with net8-rc.1 and net8-rc.2

**Comment by jonathanpeppers** [comment]
I think the issue with @tranb3r's dumps might be related to:

https://github.com/dotnet/diagnostics/pull/4081#issuecomment-1761654455

I think the finalizer isn't running for `Page2`, but then the Mono runtime + diagnostic tooling isn't showing these objects in the `.gcdump` either.

I will try .NET 7 & latest dotnet/maui/main, maybe I can get the dumps using the [old method in .NET 7](https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md#how-to-get-gc-memory-dumps).

**Comment by jonathanpeppers** [comment]
Seems like .NET 7 also only shows a single `Page2`:

![image](https://github.com/dotnet/maui/assets/840039/07c73219-d9c8-4e86-8c38-cc26e227b107)

But I never see a log message from `~Page2() => Console.WriteLine("~Page2");`.

**Comment by jonathanpeppers** [comment]
I made some progress on this here, could reproduce the issue in tests:

https://github.com/dotnet/maui/compare/main...jonathanpeppers:maui:CarouselViewLeaks

There is an issue in `ObservableItemsSource`, which is used internally by all `ItemsView` types like `CarouselView`.

But there is still a further leak, I'll need to investigate more next week. My two tests here that put `CarouselView` in a `NavigationPage` and `TabbedPage` both still fail on Android.
