### ISSUE TITLE
[regression/8.0.0-rc.1.9171] Window "blinks" when resized

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/maui#17724]
### Description

I assume this probably happens with the `dotnet new maui` project template as well.

The .NET bot and all views "blink" when resized:

![windows-blinky](https://github.com/dotnet/maui/assets/840039/6da53803-eef5-48d6-84cf-a053a687d769)

### Steps to Reproduce

1. Run a `dotnet new maui` template and resize it

### Link to public reproduction project repository

https://github.com/jonathanpeppers/maui-memory-comparison/tree/292d0149f12d582bd70511910b4117cc54bef0b3

### Version with bug

[8.0.0-rc.1.9171](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.1.9171)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842)

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Depends on 

- [ ] https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/47131770

**Comment by PureWeen** [comment]
Related https://github.com/dotnet/maui/issues/17157

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Windows 11 with Maui template:
[17724.zip](https://github.com/dotnet/maui/files/12843035/17724.zip)

**Comment by samhouts** [comment]
Confirmed that this regressed between [8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842) and [8.0.0-rc.1.9171](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.1.9171). https://github.com/dotnet/maui/pull/16637 seems sus.

**Comment by PureWeen** [comment]
It looks like this is a bug with WinUI and NavigationView

https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/47131770
