### ISSUE TITLE
.NET MAUI Blazor project template misses out on the MAUI Blazor package reference

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#17721]
### Description

.NET MAUI Blazor project template misses out on referencing Microsoft.AspNetCore.Components.WebView.Maui NuGet package.

### Steps to Reproduce

1. Create a new .NET MAUI Blazor project
2. Restore the project
3. Completes with warnings as Microsoft.AspNetCore.Components.WebView.Maui package reference is not included

### Link to public reproduction project repository

Default template itself is suffice, no authored code

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All platforms

### Did you find any workaround?

Include the package reference manually and continue.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[17721.zip](https://github.com/dotnet/maui/files/12842983/17721.zip)

![image](https://github.com/dotnet/maui/assets/97647558/488e5374-1176-427d-b057-a845ea2396c3)

**Comment by mkArtakMSFT** [comment]
This should have been fixed in rc1 or rc2. RC2 will be released later today. Can you please try it out and let us know if this is still an issue? Thanks!

**Comment by egvijayanand** [comment]
This issue has been addressed in .NET 8 RC2.

This issue can be marked as resolved.

<img width="602" alt="image" src="https://github.com/dotnet/maui/assets/81947404/8717e589-575a-44a9-96d1-24382b4eea00">
