### ISSUE TITLE
There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'android-arm64

### ISSUE THREAD

**Issue by Ali1Jamal** [dotnet/maui#17725]
### Description

Hello, I am using BlazorMaui and I created a new project that works fine. But when I added a razor class library, I got this error :
`There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'android-arm64`
The problem is that the razor class library is using Microsoft.AspNetCore.App, which is not compatible with some platforms, such as Android (As I understood from the internet) , Here is the .csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
	
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
```
I need to use razor files because I want to share components and pages with .NET MAUI. However, if I remove Microsoft.AspNetCore.App from the razor class library, it will not build because Microsoft.AspNetCore.App is essential for razor class library. Is there any way to resolve this issue?

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.0-rc.1.9171

### Affected platforms

Android

### Affected platform versions

Android 12

### Relevant log output

```shell
There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'android-arm64
```

**Comment by Ali1Jamal** [comment]
ok i remove this from razor class lib:
  ```xml 
<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>
  ```
I added the Microsoft.AspNetCore.Components.Web package to razor class lib and it built successfully.
```xml
<ItemGroup>
   <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.0-rc.1.23421.29" />
</ItemGroup>
```

I tried to run the application on my android device, but I encountered this error:
```
`blazor.webview.js:1  Cannot supply a component of type 'RazorUI.Components.Pages.Index' because the current platform does not support the render mode 'Microsoft.AspNetCore.Components.Web.ServerRenderMode'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ResolveComponentForRenderMode(Type componentType, Nullable 1 
```
i use razor class lib with both a blazor web app and a blazor maui app.
the Index.razor has attribute :
`@attribute [RenderModeServer]
 `
and i don't need to remove this attribute from Index.razor because this feature is Essential in blazor web app .

**Comment by Eilon** [comment]
As you discovered, `Microsoft.AspNetCore.App` cannot be used from within a .NET MAUI app (in most cases) because it requires features not supported in .NET MAUI. That also means that features such as `@attribute [RenderModeServer]` are not compatible with .NET MAUI because there is no such thing as "server rendering" in a .NET MAUI app.

In general, the guidance is to place common cross-platform Razor Components in a Razor Class Library (RCL) project, and then each app project, such as .NET MAUI, ASP.NET, etc. can add anything it needs for specific platforms to be supported.

So for the `Index.razor` file I would suggest putting most of the logic in some common `IndexContent.razor` file that _doesn't_ specify `@attribute [RenderModeServer]`, and then in the ASP.NET app's `Index.razor` you can specify the attribute and also render `<IndexContent />`.

There are of course many other ways to do this, but the idea is the same: have platform-independent content in the RCL, and then each platform "customizes" it for the needs of each platform.

**Comment by Ali1Jamal** [comment]
@Eilon 
Yes, but almost every page in blazor web contains such an attribute as RenderServerMode, RenderModeWebAssembly and RenderModeAuto.  For example, if you have a web project that contains 100 or 50 pages, most of the pages will contain attributes such as RenderServerMode.  If you want to run most of the pages in blazor maui, you will have to do platform specific because of the attributes only.  Therefore, it will be tiring and a bad experience for the programmer, especially beginners. Even if he creates a simple project like Counter in Blazor Web and transfers it to the Razor class lib and wants to run it in Blazor Maui, this problem will appear to him from his first experience, and it is a bad thing in my opinion.  I am understand the limition ،But you get my point.
i use different approach to solve this problem by using static class let's name it EnvironmentInfo that assigned to it manually if the current platform is web or App ,and creating a custom attribute that replace RenderServerMode ,if the current platform in EnvironmentInfo is web it will use server mode ,if it's App it will do nothing ,i have test it and everything is ok in web and Blazor Maui without creating new razor files or platform specific pages.
**Note :** 
I haven't written any code because I'm very far from the computer right now.

**Comment by Eilon** [comment]
For anyone watching here, we think we found a workaround that will help many common cases and you should be able to easily apply it to your app. Check this post here: https://github.com/dotnet/aspnetcore/issues/51235#issuecomment-1946927922
