### ISSUE TITLE
Android App crashes if CollectionView have more than one item

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#17735]
### Description

If the CollectionView ItemsSource have more than one item the Android app crashes. 

### Steps to Reproduce

Run the reproduction app and it will crash on Android because the ItemsSource ObservableCollection have 4 items. But if the three items are commented out and the app is deployed with one item the deployment is successful. 

### Link to public reproduction project repository

https://github.com/HobDev/DotNet8MauiBugs/tree/ButtonClickCrashIssue

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

No

**Comment by HobDev** [comment]
The error message that I get in crash is :

`Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'`

The same error same as reported in this [bug report](https://github.com/dotnet/maui/issues/17711).

**Comment by jsuarezruiz** [comment]
You are creating the Button outside of the ItemTemplate. So, this will create a single instance and will try to reuse it in every cell. Moving the Button inside the template fixes any possible issues (only see a single item, even a possible crash because the parent already has been assigned).

**Comment by HobDev** [comment]
The issue is fixed after implementing the fix suggested by @jsuarezruiz
