### ISSUE TITLE
Windows app only shows first item in the CollectionView

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#17736]
### Description

The ObservableCollection have 4 items. But on Windows only first one is shown.

### Steps to Reproduce

Run the Reproduction app.

### Link to public reproduction project repository

https://github.com/HobDev/DotNet8MauiBugs/tree/ButtonClickCrashIssue

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
You are creating the Button outside of the ItemTemplate. So, this will create a single instance and will try to reuse it in every cell. Moving the Button inside the template fixes any possible issues (only see a single item, even a possible crash because the parent already has been assigned).

**Comment by HobDev** [comment]
@jsuarezruiz The issue is fixed after defining and initiating all the controls within ItemTemplate. Thank you for the help. I learned to keep all the controls within ItemTemplate to avoid any issues in future.
