### ISSUE TITLE
Error compiling after installing the OneSignalSDK.DotNet component in Visual Studio on the MAC 

### ISSUE THREAD

**Issue by MarcoErlwein** [dotnet/maui#17742]
### Description

**I create a new project of type .NET Maui, install the component OneSignalSDK.DotNet from Nuget, and then when compiling the following error is generated:**

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7099/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture arm64:
"OBJC_CLASS$_OSInAppMessage", referenced from:
objc-class-ref in registrar.o
"OBJC_CLASS$_OSInAppMessageClickEvent", referenced from:
objc-class-ref in registrar.o
"OBJC_CLASS$_OSInAppMessageClickResult", referenced from:
objc-class-ref in registrar.o
"OBJC_CLASS$_OSInAppMessageDidDismissEvent", referenced from:
objc-class-ref in registrar.o
"OBJC_CLASS$_OSInAppMessageDidDisplayEvent", referenced from:
objc-class-ref in registrar.o
"OBJC_CLASS$_OSInAppMessageTag", referenced from:
objc-class-ref in registrar.o
"OBJC_CLASS$_OSInAppMessageWillDismissEvent", referenced from:
objc-class-ref in registrar.o
"OBJC_CLASS$_OSInAppMessageWillDisplayEvent", referenced from:
objc-class-ref in registrar.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation) (MauiOneSignal)

**I have Visual Studio for Mac version 17.6.4 and XCode 14.2 installed on the MAC.**

### Steps to Reproduce

1. I create a new .Net Maui Blazor project in the MAC

2. I install the OneSignalSDK.DotNet component from Nuget

3. I compile the project and the error is generated.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by drasticactions** [comment]
Checking that library, I believe they are compiling x64 versions of their binary for the iOS Simulator, but not arm64. Since you're compiling for arm64, clang blows up because it can't reference it.

I would direct this issue to https://github.com/OneSignal/OneSignal-DotNet-SDK/issues. This is not a MAUI UI issue.

**Comment by MarcoErlwein** [comment]
Thanks for the answer, how can I change that compilation mode so as not to have the error?
