### ISSUE TITLE
Nested Border renders top left corner bizarrely wrong with truncation in iOS/Windows (okay in Android)

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#17761]
### Description

If you nest two Border objects so one contains the other, and the outer Border object is set as a Rounded Rectangle, it will truncate the top left corner of the inner Border object in a bizarre fashion in Windows and iOS (while rendering correctly without this truncation on Android).

In Android, correct behavior is seen as follows with the demo code given. An outer dark blue background Border with rounded corners encircles an inner white background Border with no corner rounding and both are rendered correctly:

<img width="270" alt="corner bug 3" src="https://github.com/dotnet/maui/assets/43948450/e43f70dd-fef1-41ff-8e5e-49d16e8c63ec">

If the inner Border is set to round its corners in the proportional amount, you get a nice smooth and symmetrical effect:

<img width="271" alt="corner bug 4" src="https://github.com/dotnet/maui/assets/43948450/2ffd8ee4-5477-4730-b54e-b19f96736d35">

However, in iOS and Windows, when the outer Border is set to rounded corners and the inner is not, you get a bizarre truncation of the top left corner of the inner Border:

<img width="487" alt="corner bug" src="https://github.com/dotnet/maui/assets/43948450/71e224b0-526e-4457-859f-1a4a0351e055">

And when you set the inner Border to proportionately round off, this truncation remains on the top left corner, preventing a truly smooth/symmetrical effect:

<img width="342" alt="corner bug 2" src="https://github.com/dotnet/maui/assets/43948450/2b467b28-0913-427a-973b-72a97d7c49c6">

**CONSEQUENCES**
- This issue is preventing appropriate rendering of any layouts using Borders and rounded corners in iOS/Windows.

### Steps to Reproduce

1. Create a blank MAUI project in Visual Studio 2022 with .NET 7.0 by File > New named "Border Corner Bug"

2. Copy and paste the following code to completely replace the default code of App.xaml.cs:

```
using Microsoft.Maui.Controls.Shapes;

namespace Border_Corner_Bug {
    public partial class App : Application {
        public App() {
            InitializeComponent();

            MainPage = new ContentPage();
            VerticalStackLayout vert = new();
            (MainPage as ContentPage).Content = vert;

            Border border = new();
            border.StyleId = "OUTER BORDER";
            border.BackgroundColor = Colors.DarkBlue;
            border.Padding = new Thickness(10);
            border.Margin = 0;
            border.StrokeShape = new RoundRectangle { CornerRadius = new CornerRadius(30), StrokeThickness = 0 };
            vert.Children.Add(border);

            Border innerBorder = new();
            innerBorder.StyleId = "INNER BORDER";
            innerBorder.HeightRequest = 60;
            innerBorder.BackgroundColor = Colors.White;
            //innerBorder.StrokeShape = new RoundRectangle { CornerRadius = new CornerRadius(20), StrokeThickness = 0 };
            innerBorder.Padding = 0;
            innerBorder.Margin = 0;
            border.Content = innerBorder;
        }
    }
}
```
3. Run project in iOS and Windows to see the left top corner of the inner white Border is bizarrely rounded/truncated as shown in pictures above.

4. Run project in Android to see the left top corner of the inner Border is properly rendered by comparison without truncation.

### Link to public reproduction project repository

https://github.com/jonmdev/Border-Corner-Bug

### Version with bug

7.0.92 & 8.0

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 16.7, Android, Windows 10

### Did you find any workaround?

None.

**Comment by drasticactions** [comment]
If you can turn the code you posted above into a repro project, that will make it easier for anyone who wants to take a look at this to be able to debug it and have a shared codebase with you to work with.

Also, if you can separate out the issues you are hitting into individual ones, that would be great. It's easier to fix issues if they're self contained on their own (and easy to group together later if they're caused by the same thing in the end) rather than trying to fix multiple issues within the same one. Thank you!

**Comment by FreakyAli** [comment]
Seems to be related to https://github.com/dotnet/maui/issues/17753

**Comment by jonmdev** [comment]
I am not sure why a GitHub repro project would be requested when I have already provided the simple code needed to reproduce it. The project can be reproduced in two steps:

1) File New to create new Maui .NET 7.0 project in Visual Studio 2022.
2) Select all of the default App.xaml.cs and copy/paste my code to replace it.

There is no other step? It takes less than 1 minute to reproduce. (?) I can do it in about 10 seconds. (?)

I will remove the bounds issue and repost that in another thread as suggested. Thanks for any help.

**Comment by jonmdev** [comment]
Broke up the report into two reports. Second report for bounds issue here: https://github.com/dotnet/maui/issues/17763

Thanks again.

**Comment by jonmdev** [comment]
I tried .NET 8.0 and it provides the same result. Here it is in Windows with no rounding to the inner border: 
<img width="391" alt="windows net 8" src="https://github.com/dotnet/maui/assets/43948450/139a5286-caf0-4b02-931d-205af64514d6">

It is truncating the top left in a bizarre fashion which it should not be doing.

Here it is in Android where it is rendering correctly - ie. Not truncating the corners, same as on .NET 7:

<img width="266" alt="android corner bug  net 8" src="https://github.com/dotnet/maui/assets/43948450/1bf3365a-516b-4ff8-a92c-7f1d5d0a726d">

Here are my project settings in .NET 8.0 Visual Studio 2022 Preview - selected target as attached:

<img width="359" alt="corner bug targets" src="https://github.com/dotnet/maui/assets/43948450/112bc4ab-5ea1-47be-afed-bd8eab24d60b">

On a possibly unrelated issue, I notice when I try to use .NET 8.0 my Android project drop downs no longer allow me to select a target android framework - the list goes empty. Is that normal? I have API 33 and 34 installed.

In terms of this issue, there is no difference between .NET 7.0 and .NET 8.0. Unless I am missing something in how to upgrade.

Is there some other step I need to take to upgrade to .NET 8.0? Besides opening the same project in Visual Studio 2022 preview with .NET 8.0 selected as target in project settings?

**Comment by jonmdev** [comment]
I posted demo code here though it is just verbatim my OP post code as described so anyone who wants to test it can see for themselves also if that is easier:

https://github.com/jonmdev/Border-Corner-Bug

**Comment by jonmdev** [comment]
Can confirm this is now working in 8.0.0-rc.2.23479.6 for Windows/iOS/Android.

Closing.
