### ISSUE TITLE
DatePicker date format inconsistent

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#17760]
### Description

Add a date picker to a view. Bind it to a date.

Run in Android - it displays in my local date format (dd/MM/yyyy).
Run it in iOS - it displays a different format (M/d/yyyy).

### Steps to Reproduce

Add a date picker to a view.

 <DatePicker  x:Name="dpFromDate" HorizontalOptions="StartAndExpand" WidthRequest="130" Margin="10,0,0,0"
         Date="{Binding Path=FromDate, Mode=TwoWay}" FontSize="Medium" />

Run

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11 - 13, iOS 16

### Did you find any workaround?

Need to hard code the date format to my local format

**Comment by drasticactions** [comment]
The culture for the DatePicker is based on the culture of the device you're running it on. If you're running it on an iOS Simulator, for example, that's probably its default.

For example, My iOS Simulator is setup for ja-JP, so it shows yyyy/mm/dd 

<img width="420" alt="スクリーンショット 2023-10-01 15 26 48" src="https://github.com/dotnet/maui/assets/898335/859a8acb-9cb7-4e71-9803-af65d18160cf">

**Comment by williambuchanan2** [comment]
I'm not running it on a simulator. This is on my physical device which has it's region set to Australia and shows all dates in other apps in the expected format.

**Comment by drasticactions** [comment]
Are you building and deploying your app on a Mac? Through Visual Studio on Windows, or through something like Hot Restart?

**Comment by williambuchanan2** [comment]
I've got my device connected to a Mac, and using VS for Mac to debug.

Side note - debugging iOS device from Windows just doesn't work (or at least doesn't work for anyone I know...).

**Comment by drasticactions** [comment]
Thanks for the side note, you should probably file a VS Feedback for that.

Anyhow, regarding your issue. I'm not sure if I can recreate your exact issue (Without a repro sample, I put a DatePicker into a blank MAUI Template app... and it seems fine with my culture at least. But I did notice something off that may be what you're seeing, or it could be a different issue. If I change the default Date format for my phone, and kill and restart the app (or restart the phone) then the date format shows as the default for the general culture, not the specific date format I had selected for my device. When I change the date, it then flips to the right one.

**Comment by williambuchanan2** [comment]
Thanks for the follow up. I'm not sure I can create a repro sample because there is literally nothing in play other than the date picker, but I am now getting mixed behaviour which is just adding to my confusion.

I took your advice and deployed to my device via CLI, and strangely it worked ok, so I assumed all was well. I committed the code then ran it on my Android emulator (which previously worked without specifying date format) - now the problem has shifted to Android. So now Android is showing the wrong date format but iOS is working fine. It makes absolutely no sense.

Another side note - possibly unrelated.... earlier in the week I had a similar date issue. We are using RestSharp to call an API. We had a new API which took a date as a parameter. The API didn't work on iOS and we discovered that it was due to the date. What we were doing was creating a RestSharp parameter using date.ToString(). This worked fine on Android, but on the iPhone it was mixing up the date format which in turn caused the API call to fail. We fixed it by passing a DTO with a DateTime property so the issue seems to have been with the ToString function.

I have triple checked my region settings so really confused as to why I am having these seemingly random date issues.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 3(net8.0 & net7.0). Not repro on android and iOS platform. 
Android:
![image](https://github.com/dotnet/maui/assets/77434865/1d42f9e9-d5c9-421d-84ac-35a14ad8a77a)
iOS:
![image](https://github.com/dotnet/maui/assets/77434865/71705160-80f4-4089-8bf8-64bdbf6d4de2)
