### ISSUE TITLE
Nested Border objects do not layout their Bounds correctly based on expected settings (iOS/Android/Windows)

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#17763]
### Description

If you nest two Border objects so one contains the other, the bounds are not set appropriately to match the requested sizes based on padding. 1 erroneous pixel is added in every direction by the nesting (in all of Windows/iOS/Android).

In the demo code below, in all operating systems (iOS/Windows/Android), where an outer Border is set to 10 pixels padding,  the bounds of the outer Border (height  or width) minus the inner Border will result in 22 pixels (an extra two pixels - should be 20 pixels, ie. 2x padding).

<img width="487" alt="corner bug" src="https://github.com/dotnet/maui/assets/43948450/433b16b6-14b8-42f8-ac27-5e4455a855f5">

This is preventing correct anticipation of sizes of objects for manual layouts.

### Steps to Reproduce

1. Create a blank MAUI project in Visual Studio 2022 with .NET 7.0 by File > New named "Border Bounds Bug"

2. Copy and paste the following code into App.xaml.cs to replace the entire file:

```
using Microsoft.Maui.Controls.Shapes;
using System.Diagnostics;

namespace Border_Bounds_Bug {
    public partial class App : Application {
        public App() {
            InitializeComponent();

            MainPage = new ContentPage();
            VerticalStackLayout vert = new();
            (MainPage as ContentPage).Content = vert;

            Border border = new();
            border.StyleId = "OUTER BORDER";
            border.BackgroundColor = Colors.DarkBlue;
            border.Padding = new Thickness(10);
            border.Margin = 0;
            border.StrokeShape = new RoundRectangle { CornerRadius = new CornerRadius(30), StrokeThickness = 0 };
            vert.Children.Add(border);

            Border innerBorder = new();
            innerBorder.StyleId = "INNER BORDER";
            innerBorder.HeightRequest = 60;
            innerBorder.BackgroundColor = Colors.White;
            //innerBorder.StrokeShape = new RoundRectangle { CornerRadius = new CornerRadius(20), StrokeThickness = 0 };
            innerBorder.Padding = 0;
            innerBorder.Margin = 0;
            border.Content = innerBorder;

            //==================================
            //CLICK TEST BEHAVIOR
            //==================================
            TapGestureRecognizer gesture = new();
            border.GestureRecognizers.Add(gesture);
            gesture.Tapped += delegate {
                Debug.WriteLine("BORDER WIDTH " + border.Bounds.Width + " INNER BORDER WIDTH " + innerBorder.Bounds.Width + " | DIFFERENCE " + (border.Bounds.Width - innerBorder.Bounds.Width)); 
                Debug.WriteLine("BORDER HEIGHT " + border.Bounds.Height + " INNER BORDER HEIGHT " + innerBorder.Bounds.Height + " | DIFFERENCE " + (border.Bounds.Height - innerBorder.Bounds.Height));
            };
        }
    }
}
```
3. Click on Border on screen to Debug the bounds, which should be a 20 pixel difference from the outer border minus the inner border (due to padding 10 on outer Border) but instead returns a 22 pixel difference on all platforms (iOS/Android/Windows).

### Link to public reproduction project repository

See above

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 16.7, Android, Windows 10

### Did you find any workaround?

None.

**Comment by jsuarezruiz** [comment]
.NET 8 Behavior with the latest changes
![image](https://github.com/dotnet/maui/assets/6755973/3daee24d-7084-4cc3-9c8a-014e537ef732)

cc @jstedfast

**Comment by jonmdev** [comment]
@jstedfast, if you are referring to the border issue, which was posted here: https://github.com/dotnet/maui/issues/17761

Then yes, the correct behavior as illustrated in that thread is as @sjuarezruiz posted here. With that default code over there the corners should not be truncated.

However, in Windows/iOS .NET 7/8 the top left corner of the nested border gets bizarrely chopped off.

That is issue #1. Issue #2 is that the layouts are not precisely correct, as posted in this thread,  but this is more minor.

**Comment by jonmdev** [comment]
I posted the code here which demonstrates both issues. If you play the project in Windows and iOS you will see the top left corner is truncated. If you click the object you will also see the bounds are wrong:

https://github.com/jonmdev/Border-Corner-Bug

**Comment by jonmdev** [comment]
This issue regarding the bounds miscalculation specifically can be closed. I figured out the issue. It was just that:

`border.StrokeShape = new RoundRectangle { CornerRadius = new CornerRadius(20), StrokeThickness = 0 };`

Does not work. You cannot set the stroke thickness this way and must set it as `border.StrokeThickness = 0;` 

So the difference was due to the default 1-2 px stroke. One less issue. :)

**Comment by jstedfast** [comment]
I have noticed, while working on Border, that there was another StrokeThickness on the Shape and thought that was confusing.

I guess it was done that way because you can probably draw a shape w/o the need for a Border.

Good that you figured out how to do what you wanted to do, though.
