### ISSUE TITLE
IOS App Icon no change after publishing

### ISSUE THREAD

**Issue by KieranFleckney** [dotnet/maui#17764]
### Description

When I publish my app for IOS and upload it to app connect via transport (I have only done it this way) the app icon I set doesn't change. This can be seen in multiple places. 1. transporter app 2. app connect 3. test flight.

I can see the Icon in the IOS simulator fine and looks perfect. However, when I publish it only ever shows me the default ".net" with purple background.

I have set the image to be dividable by 8, updated my plist to correct name. I have tried app icon with and without a foreground. 

I have tried .net 7 and .net 8 both have the same effect. Really don't know if I am missing something or doing something wrong.
![Screenshot 2023-09-30 at 10 42 40](https://github.com/dotnet/maui/assets/57374898/6681c35a-c3be-4825-bf95-ef7429fe91e4)
![Screenshot 2023-09-30 at 10 44 17](https://github.com/dotnet/maui/assets/57374898/e1e75af6-b47b-427e-b551-12d281f6596e)
![Screenshot 2023-09-30 at 10 44 21](https://github.com/dotnet/maui/assets/57374898/1b51bf93-c724-48c1-abb6-cf2005b99d9c)
![Screenshot 2023-09-30 at 10 44 46](https://github.com/dotnet/maui/assets/57374898/b5485e68-e0ce-4943-9002-dc66b9844255)
<img width="432" alt="Screenshot 2023-09-30 at 10 45 04" src="https://github.com/dotnet/maui/assets/57374898/e2738b8f-d4ee-4f5f-a6e0-5d6b5a5eeb37">
<img width="821" alt="Screenshot 2023-09-30 at 10 45 28" src="https://github.com/dotnet/maui/assets/57374898/6d81491f-440f-4e3c-9ea2-17f3993e9946">
<img width="444" alt="Screenshot 2023-10-01 at 09 56 37" src="https://github.com/dotnet/maui/assets/57374898/81a3a874-abf3-42e5-aff9-d025fb20ff56">

### Steps to Reproduce

1. Create.a File > New .NET MAUI App
2. Add new Icon to Resources > AppIcon
3. Update csproj <MauiIcon> with new with new icon
4. Update plist in Platforms > IOS > XSAppIconAssets
5. Create a IOS publishing profile in App Store Connect
6. Build and publish with `dotnet publish -f:net8.0-ios -c Release /p:ArchiveOnBuild=true`
7. Open Transporter app and upload IPA file created from publishing

At this point it should show the incorrect icon on transporter. If you then delivery it in Transporter app and it will upload to App Store Connect, you will still see the incorrect icon. You can now follow this all the way to test flight where nothing will change and continue to see the default .NET purple icon

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16.4

**Comment by jsuarezruiz** [comment]
@mattleibow Thoughts?

**Comment by KieranFleckney** [comment]
Update: Seems to be working now. Weirdly after publishing a few more build it has update in both Transporter app and App connect. Include the old build which should have had the app icon too. Maybe this is more of an issue with App connect and taking time to change the app icon. Anyway it seems good. Sorry to waste anyone time.
