### ISSUE TITLE
[Bug] Unable to set image as ContentPage BackgroundImageSource 

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#17766]
### Description

I'm setting the bot image to the background of the page, but nothing appears.

`BackgroundImageSource = "dotnet_bot.png";`

### Steps to Reproduce

This can be tested on template app

### Link to public reproduction project repository

NA

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

No

**Comment by dmm-l-mediehus** [comment]
Any workarounds?

**Comment by AndyG74** [comment]
the bug is always available on .net sdk 8.0.100
