### ISSUE TITLE
InputView MaxLengthProperty appears to be declared incorrectly

### ISSUE THREAD

**Issue by rlennoxmemoro** [dotnet/maui#17780]
https://github.com/dotnet/maui/blob/2955d72cf32bb01d24847ba86cda109b7a81732f/src/Controls/src/Core/InputView/InputView.cs#L26C3-L26C3

InputView has this property:

public static readonly BindableProperty MaxLengthProperty = BindableProperty.Create(nameof(MaxLength), typeof(int), typeof(int), int.MaxValue);

Shouldn't the second typeof be typeof(InputView) ?  --- typeof(int), typeof(**InputView**)

**Comment by jfversluis** [comment]
You're absolute right, good spot, thank you!
