### ISSUE TITLE
Multilingual App Toolkit without the nagging Android bug

### ISSUE THREAD

**Issue by pooran** [dotnet/maui#1780]
## Summary
MAT works amazingly but in Android, it works only if the app is restarted. It was parked and never fixed. Hope with MAUI it will be solved. Sample code and other necessary details can be found at  https://github.com/xamarin/Xamarin.Forms/issues/1595

## Intended Use Case
Without forcing android users, translations should work just like in other platforms - iOS, UWP, and MacOS versions of Xamarin.Forms project.

**Comment by mattleibow** [comment]
Seems the previous issue linked to this issue that seems to have been resolved: https://github.com/xamarin/xamarin-android/issues/3596

Is this a different issue?
