### ISSUE TITLE
[ManualMauiTest][D20+D16] Tab keys do not leave editors

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#17804]
Both test cases fail for Mac Catalyst using 8.0.0-rc.2.9351.

This may be an issue where we need to update the test - the tests both call for the "tab" key to move between Editor controls, which seems incorrect for the platform.

**Comment by mattleibow** [comment]
Duplicat of https://github.com/dotnet/maui/issues/14191

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/14191
