### ISSUE TITLE
Missing sln file

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#17812]
### Description

Using RC2 I don't see a solution file after creating a new project from CLI.

```
> dotnet new maui -n MauiRC2
```

<img width="487" alt="Screenshot 2023-10-03 at 3 34 27 PM" src="https://github.com/dotnet/maui/assets/41873/efbcc72c-10b3-43bd-a06f-b082c36d8ea6">

### Steps to Reproduce

```
Installed Workload Id      Manifest Version                  Installation Source
--------------------------------------------------------------------------------
maui                       8.0.0-rc.2.9351/8.0.100-rc.2      SDK 8.0.100-rc.2
```

```
> dotnet new maui -n MauiRC2
```

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.1.9171

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

**Comment by Eilon** [comment]
This is by-design, see this PR: https://github.com/dotnet/maui/pull/14215
