### ISSUE TITLE
Cannot Publish MAUI App in Intune

### ISSUE THREAD

**Issue by igalfsg** [dotnet/maui#17810]
### Description

When trying to publish a MAUI MSIX on Intune it says that the dependency "Microsoft.WindowsAppRuntime.1.2" is not in the package. Based on my research Intune removed the ability to load external packages from the manifest meaning that "Microsoft.WindowsAppRuntime.1.2" must be part of the application. Is there a way to compile the MAUI application with that dependency? 

![image](https://github.com/dotnet/maui/assets/8607853/6c2cb86f-e6bb-4521-adf3-5a0945a3a30f)

### Steps to Reproduce

1. Create any MAUI MSIX by publishing a MAUI application for Windows. 
2. Try to deploy it in Intune as a line of business application. 

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

I have not found a workaround.

**Comment by samfoucart** [comment]
Bump

**Comment by samfoucart** [comment]
I am experiencing the exact same issue. I am using the publish function in Visual Studio. I was able to edit the msix appxmanifest using the MSIX Packaging Tool to get past this phase of the upload process. But my workaround results in a crash on installation for most users.

**Comment by mattleibow** [comment]
You may need to set `<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>` in your csproj.

This will include the WASDK msix files, but this also is going to prevent any security patches from the OS being applied. However, with intune, this may not be a typical store app so will not really matter as you are doing enterprise things.
