### ISSUE TITLE
.Net Maui using VS 2022 Community Edition

### ISSUE THREAD

**Issue by junarddelossantos** [dotnet/maui#17816]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows 10

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I followed the tutorial, it should be easy to run the 1st application created via template but I encountered immediately upon compiling/building the solution.
![image](https://github.com/dotnet/maui/assets/121910453/4a91e45c-5b25-43b2-b10f-115539b06be8)
That package/sdk should included upon VS 20222 Community Edition right?

Kindly tell what's wrong?

**Comment by MagicAndre1981** [comment]
use .net 7.0 and no longer 6.0
