### ISSUE TITLE
EmbeddedReferenceJar has no equivalent in MAUI

### ISSUE THREAD

**Issue by espritm** [dotnet/maui#17826]
### Description

I want to migrate my Android binding project from Xamarin to MAUI.

In Xamarin, I was able to define a .aar file as the "main library to bind" as LibraryProjectZip and other dependency libraries as EmbeddedReferenceJar, such as : 
```
  <ItemGroup>
    <LibraryProjectZip Include="Jars\coresdk-3.5.2.aar" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedReferenceJar Include="Jars\commons-lang3-3.11.jar" />
    <EmbeddedReferenceJar Include="Jars\commons-text-1.9.jar" />
    <EmbeddedReferenceJar Include="Jars\cameraview-2.7.2.aar" />
  </ItemGroup>
```

With that configuration, I have been able to use the binded library in my Xamarin.Forms app.
I was able to call methods and instanciate classes from the aar "coresdk-3.5.2". 

To migrate my project to MAUI, what I understand with the [documentation](https://learn.microsoft.com/en-us/dotnet/maui/migration/android-binding-projects) is that we only have to use AndroidLibrary.
So LibraryProjectZip become AndroidLibrary and EmbeddedReferenceJar become AndroidLibrary.

But in my case, it gives me hundreds of errors because it tries to bind the four libraries...
I have tried to set ImplicitUsings to disable
I have tried to keep LibraryProjectZip and EmbeddedReferenceJar

### Steps to Reproduce

Create a new Android Binding Project

Add the .aar file you want to bind as AndroidLibrary 

Add a .aar file which you don't want to bind but is needed as dependency from the main library

Build

Expected outcome : the main .aar library is binded, the dependency library should be embeded but not bind so the main library can have all its dependencies

Actual outcome : the main .aar library is binded, but the dependency library is binded too and gives hundred of errors

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by nll** [comment]
From looking into [this](https://learn.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-items#androidlibrary) and [this](https://github.com/xamarin/xamarin-android/blob/e82abf373420f56d6b96b98bca67a80ce3217fec/Documentation/guides/OneDotNetEmbeddedResources.md#msbuild-item-groups) information, did you try not binding those jars ? e.g.

```xml
  <ItemGroup>
    <AndroidLibrary Include="Jars\commons-lang3-3.11.jar" Bind="false" />
    <AndroidLibrary Include="Jars\commons-text-1.9.jar" Bind="false" />
    <AndroidLibrary Include="Jars\cameraview-2.7.2.aar" Bind="false" />
  </ItemGroup>
```

**Comment by espritm** [comment]
I confirm the Udpate keyword works fine and the "Remove" keyword lines is not necessary anmore.
```
  <ItemGroup>
    <AndroidLibrary Update ="Native Dependences\commons-lang3-3.11.jar" Bind="false" />
    <AndroidLibrary Update ="Native Dependences\commons-text-1.9.jar" Bind="false" />
    <AndroidLibrary Update ="Native Dependences\cameraview-2.7.2.aar" Bind="false" />
  </ItemGroup>
```

The above option works too
`
<EnableDefaultAndroidItems>false</EnableDefaultAndroidItems>
`

But it gives me other errors because the file Metadata.xml is not used anymore.

So I prefere the "Update" keyword option 👍

**Comment by jonathanpeppers** [comment]
I believe you've come to the right solution here. It isn't clear to use `Update` unless you know some MSBuild.

`Bind="false"` is normally used in the rare case -- you have a Java dependency and don't want a C# binding for it.

The docs we have on this are:

* https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNet.md
* https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetEmbeddedResources.md
* https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetBindingProjects.md

@espritm if we had some commented examples in the `dotnet new android-bindinglib` template would this have helped you?

https://github.com/xamarin/xamarin-android/blob/main/src/Microsoft.Android.Templates/android-bindinglib/AndroidBinding1.csproj

**Comment by jonathanpeppers** [comment]
Filed here, thanks!

https://github.com/xamarin/xamarin-android/issues/8411
