### ISSUE TITLE
Issue when Publish a Mac Catalyst app for distribution outside the Mac App Store

### ISSUE THREAD

**Issue by petervaradi** [dotnet/maui#17820]
### Description

I have an issue when I follow this tutorial by Microsoft:
```
Publish a Mac Catalyst app for distribution outside the Mac App Store
https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/deployment/publish-app-store?view=net-maui-7.0
```
At the very end when I run the package produced this way the installer pops up fine, it installs something, and then it finishes. But there is no installed app anywhere. What is the output of the .pkg installer?
The app is nowhere to be found. Not in the Applications not on the Launchpad, and Spotlight can't find it either.  

I use the exact same command as the tutorial, with my own certificates
```
dotnet publish -f net7.0-maccatalyst -c Release -p:MtouchLink=SdkOnly -p:CreatePackage=true -p:EnableCodeSigning=true -p:EnablePackageSigning=true -p:CodesignKey="Developer ID Application: John Smith (AY2GDE9QM7)" -p:CodesignProvision="MyMauiApp (Non-App Store)" -p:CodesignEntitlements="Platforms\MacCatalyst\Entitlements.plist" -p:PackageSigningKey="Developer ID Installer: John Smith (AY2GDE9QM7)" -p:UseHardenedRuntime=true
```

Everything goes fine. The .pkg is produced in the publish folder.
I do the xcrun notarytool. It's Accepted. 
I do xcrun stapler and then validate, it's all fine. 

Still the installer installs nothing or at least I have no idea where to find the app. 

Any help would be appreciated. 

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Ventura 13.3.1 x64

**Comment by drasticactions** [comment]
@rolfbjarne Would you have ideas of what to check here?

**Comment by rolfbjarne** [comment]
macOS has the really annoying habit of _updating any existing apps_ instead of installing a new version in /Applications. This includes updating the .app directory inside the bin directory of your project.

So try removing the bin/obj directories of your project, and then open/install the pkg again.

If that doesn't work, try installing from the command line, you'll get some logs, and then attach those here:

```
sudo installer -pkg "/path/to/package.pkg" -target / -verbose -dumplog
```

**Comment by petervaradi** [comment]
Thank you Rolf.
After deleting the bin and obj folder, the pkg installed the app in the Application folder.

**Comment by drasticactions** [comment]
Thanks @rolfbjarne!
