### ISSUE TITLE
[regression/7.0.92] IndicatorView not visible on iOS

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#17831]
### Description

<img width="851" alt="Screenshot 2023-10-04 at 1 22 00 PM" src="https://github.com/dotnet/maui/assets/41873/9cf352a9-8621-4979-820b-82ba45a68de2">

Works on Android, but nothing on iOS. Have tried multiple projects, and different layouts.

I confirmed this in 8.0.0 RC2 and 7.0.92.

### Steps to Reproduce

Run the sample on iOS 17 or 16.4, simulator or device.

```xaml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:viewmodels="clr-namespace:CarouselViewDemos.ViewModels"
             x:Class="CarouselViewDemos.Views.HorizontalLayoutWithIndicatorsPage"
             Title="Indicators">
    <ContentPage.BindingContext>
        <viewmodels:MonkeysViewModel />
    </ContentPage.BindingContext>
    <StackLayout>
        <CarouselView ItemsSource="{Binding Monkeys}"
                      IndicatorView="indicatorView">
            <CarouselView.ItemTemplate>
                <DataTemplate>
                    <StackLayout>
                        <Frame HasShadow="True"
                               BorderColor="DarkGray"
                               CornerRadius="5"
                               Margin="20"
                               HeightRequest="300"
                               HorizontalOptions="Center"
                               VerticalOptions="Center">
                            <StackLayout>
                                <Label Text="{Binding Name}" 
                                       FontAttributes="Bold"
                                       FontSize="20"
                                       HorizontalOptions="Center"
                                       VerticalOptions="Center" />
                                <Image Source="{Binding ImageUrl}" 
                                       Aspect="AspectFill"
                                       HeightRequest="150"
                                       WidthRequest="150"
                                       HorizontalOptions="Center" />
                                <Label Text="{Binding Location}"
                                       HorizontalOptions="Center" />
                                <Label Text="{Binding Details}"
                                       FontAttributes="Italic"
                                       HorizontalOptions="Center"
                                       MaxLines="5"
                                       LineBreakMode="TailTruncation" />
                            </StackLayout>
                        </Frame>
                    </StackLayout>
                </DataTemplate>
            </CarouselView.ItemTemplate>
        </CarouselView>
        <IndicatorView x:Name="indicatorView"
                       IndicatorsShape="Square"
                       IndicatorColor="LightGray"
                       SelectedIndicatorColor="DarkGray"
                       HorizontalOptions="Center"
                       Margin="0,0,0,40" />
    </StackLayout>
</ContentPage>
```

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/7.0/UserInterface/Views/CarouselViewDemos

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

**Comment by edgedj** [comment]
just to add a note, there is a difference between rendering on Android and iOS but we have the indicator view working here and it seems like (at least in our project) a set height request on the CarouselView tag makes the indicator view appear. 

Try setting HeightRequest="200" in your example above between lines 11 & 12

**Comment by jsuarezruiz** [comment]
> just to add a note, there is a difference between rendering on Android and iOS but we have the indicator view working here and it seems like (at least in our project) a set height request on the CarouselView tag makes the indicator view appear.
> 
> Try setting HeightRequest="200" in your example above between lines 11 & 12

Have done a quick test with main branch with a similar result. Required to set the HeightRequest property to the CarouselView.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). Repro on iOS 17.0 and MacCatalyst, not repro on Windows 11 and Android 14.0-API34 with below Project:
[CarouselViewDemos.zip](https://github.com/dotnet/maui/files/13645812/CarouselViewDemos.zip)

**Comment by sabrigo** [comment]
even from the .net maui samples project of official .net maui, this issue can be reproduced

**Comment by kubaflo** [comment]
It seems to be working fine on the latest main branch

https://github.com/user-attachments/assets/0908fd9d-cb10-455f-a149-335bd3e388b2

**Comment by mattleibow** [comment]
Thanks for checking this. I added a note to try updating maui.
