### ISSUE TITLE
CollectionView - Lost focus for Header when new ItemSource assigned

### ISSUE THREAD

**Issue by rafalrita** [dotnet/maui#17845]
### Description

When I implement search field in Header and after searchcollection is updated header lost focus. This bug was also in xamarin forms

### Steps to Reproduce

1. Create collectionView
2. Implement search form inside header
3. Write something in search form
4. Header is losing focus

### Version with bug

8.0.0-preview.5.8529

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 13, iOS 16

### Did you find any workaround?

Using ListView instead of CollectionView

**Comment by QianaJiao** [comment]
Verified this issue was not repro on Visual Studio 17.10.0 Preview 2. 
![image](https://github.com/dotnet/maui/assets/91244512/4dccc0ca-a428-4bb3-8e44-0a4fcc98a8ce)
If your issue still exists, could you share your code or repo with me?
