### ISSUE TITLE
CollectionView still has default spacing between items, despite numerous PRs to fix it

### ISSUE THREAD

**Issue by Vroomer** [dotnet/maui#17851]
### Description

I honestly don't know if I'm missing something, but if I recall corectly, there has been several PRs to fix the issue of CollectionView having unwanted spacing in between the items on Windows.

According to this, it has been fixed and then broken again: https://github.com/dotnet/maui/pull/15584.

According to this PR, the new fix was merged a month ago: https://github.com/dotnet/maui/pull/17261.

Unfortunately no matter which build I try, the gap between the items is still there!

I tried:
7.0.0-ci.net7.21493 - the build of the fix
7.0.0-ci.net7.22387 - latest build
net8 RC1

I rebuilt the solution ten times out of paranoia.

### Steps to Reproduce

Same as https://github.com/dotnet/maui/issues/12495

### Link to public reproduction project repository

https://github.com/samuelradford/Reproduction.MAUICollectionViewSpacing

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No!

**Comment by drasticactions** [comment]
https://github.com/dotnet/maui/pull/15584 was closed with no fixes. It was superseded by https://github.com/dotnet/maui/pull/17261.

https://github.com/dotnet/maui/commit/65edfe095cc3fed824b83ad76bed755b17bd52a1 is in `main` and `net8.0` (not backported to `net7.0`) and is not in a released product yet. It should go out with RC2. I would check with against `main` or `net8.0` to verify your issue, but IMO we shouldn't be closing issues until they actually land in a release for people to use, to avoid issues like yours where you assume that since it's closed, it must be available.

**Comment by Vroomer** [comment]
@drasticactions As I said, I tested this in 7.0.0-ci.net7.22387, which as far as I know is the recent main build from Azure DevOps pipelines. I wanted to test 8.0.0-ci.net8.22361 as well, but it requires Microsoft.Extensions.Logging.Abstractions 8.0.0-rc.2.23457.7, which is not available for me. I thought that given the PR is merged, it should be in the latest nightly builds of main branch and the issue should not reproduce. Also I was able to reproduce the issue even in the build from the PR, i.e. 7.0.0-ci.net7.21493. Can you please clarify this?

**Comment by drasticactions** [comment]
<img width="913" alt="スクリーンショット 2023-10-06 22 40 02" src="https://github.com/dotnet/maui/assets/898335/7a965d9d-21d1-42e7-9a16-bd81cab99471">

Running in the MAUI Main source repo

Can you check your output folder for the MAUI net7 builds and see what versions the `Microsoft.Maui` dlls are? Maybe you're referencing the old version by mistake?

**Comment by Vroomer** [comment]
![image](https://github.com/dotnet/maui/assets/26696962/e8954cdf-c662-477e-a048-40196cdaa56a)
I'm puzzled.

**Comment by drasticactions** [comment]
Check the actual DLL versions that are in your output folder. I'm willing to bet they are the current 7.0.92 version of MAUI.

CC @mattleibow, I'm not sure of the current state of `MauiVersion` or if that's supported.

**Comment by Vroomer** [comment]
Yes, you are right, the file in the bin is actually sha.4a5000b64-azdo.8004946, which is .net 7 SR7 release. I had no idea MauiVersion doesn't work, especially given that in VS it shows like it has the referenced version. Is there some supported way to reference new builds from pipeline in existing projects?

**Comment by mattleibow** [comment]
There is currently a bug in .NET 8 SDK where MauiVersion dores not work for .NET 7. You need to use a global.json and pin to .NET 7 and then MauiVersion will work for net7

**Comment by Vroomer** [comment]
Ok, thank both of you for clarification.

**Comment by drasticactions** [comment]
I'm gonna close this as it should be working with the right versions used. If it's not or there are other issues you find, feel free to reopen it.
