### ISSUE TITLE
Maui Preferences always thows exception while using datatype other than string.

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [dotnet/maui#17858]
I'm using the preferences to store int , bool datatypes,
whenever i call Get function like below

**Preferences.Default.Get(UserContactId,0);**

Always get this exception,
![image](https://github.com/dotnet/maui/assets/44390143/f08a6ce9-24aa-420d-add2-6bfe904fc358)

Why is this happening? I have used preferences in Xamarin forms but its new.
Could you help me resolve this issue ? It would be really helpful.

**Comment by GnanaPriyaNamasivayam** [comment]
I also tried this,
**Int32.Parse(Preferences.Get(MuniAppCommon.CommonFunctions.UserContactId,"0"));**

It throws an exception too..
![image](https://github.com/dotnet/maui/assets/44390143/d0cd0185-d5ff-4b62-bec2-57663bacfca0)

**Comment by jamesmontemagno** [comment]
I would need to see your Set, but you need to align things up... Perhaps you accidentally set it to a string once and are trying to store now an integer. Once it is stored then it can only be retrieved as the same value.

```
Preferences.Set(MuniAppCommon.CommonFunctions.UserContactId,"1");
Preferences.Get(MuniAppCommon.CommonFunctions.UserContactId,"0");

or 


Preferences.Set(MuniAppCommon.CommonFunctions.UserContactId,1);
Preferences.Get(MuniAppCommon.CommonFunctions.UserContactId,0);
```

Either of those would work.... if it is messed up you would need to uninstall the app or change the key or remove it

**Comment by GnanaPriyaNamasivayam** [comment]
Thanks, It has been resolved already.

Anyway, what you have shared is the solution I used to fix.
