### ISSUE TITLE
Android Crashing: "Java.Lang.RuntimeException: 'Canvas: trying to draw too large(109224768bytes) bitmap.'" Runs perfect on iOS/Windows. Any ideas why?

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#17862]
### Description

I am not sure if this is related to the issue I posted here as they both started at the same time: https://github.com/dotnet/maui/issues/17857 

When I comment out the same lines of code causing that issue which are either of:

```
imageView.Source = ImageSource.FromStream(getFromStream);
imageView.Source = ImageSource.FromResource(resourceName, assembly)
```
The problem resolves so I believe it is all the same issue with two different manifestations.

In this case, I get random crashes in Android playback sometimes where I get an alert: `Java.Lang.RuntimeException Message=Canvas: trying to draw too large(109224768bytes) bitmap.`

Debug output looks like this:

```
[View] ContentViewGroup not displayed because it is too large to fit into a software layer (or drawing cache), needs 14197992 bytes, only 10108800 available
[Parcel] Expecting binder but got null!
[Choreographer] Skipped 102 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=1731ms; Flags=1, FrameTimelineVsyncId=4502019, IntendedVsync=126601097047890, Vsync=126601130381222, InputEventId=0, HandleInputStart=126601141730300, AnimationStart=126601141755500, PerformTraversalsStart=126601141802200, DrawStart=126601991805600, FrameDeadline=126601113714556, FrameInterval=126601141689400, FrameStartTime=16666666, SyncQueued=126602660132500, SyncStart=126602669969800, IssueDrawCommandsStart=126602708387900, SwapBuffers=126602830609000, FrameCompleted=126602838011700, DequeueBufferDuration=26400, QueueBufferDuration=295000, GpuCompleted=126602837900600, SwapBuffersCompleted=126602838011700, DisplayPresentTime=-4294967296, CommandSubmissionCompleted=126602830609000, 
```

Call stack looks like this:
```
 	0xFFFFFFFFFFFFFFFF in Android.Runtime.JNIEnv.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12,5	C#
 	0x1E in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:122,26	C#
 	0x17 in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw	C#
 	0x89 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:12324,5	C#
 	0x78 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:75,7	C#
 	0x38 in Android.Views.View.DispatchDraw at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:14916,5	C#
 	0x11 in Microsoft.Maui.Platform.ContentViewGroup.DispatchDraw at D:\a\_work\1\s\src\Core\src\Platform\Android\ContentViewGroup.cs:49,4	C#
 	0x11 in Android.Views.View.n_DispatchDraw_Landroid_graphics_Canvas_ at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:14904,4	C#
 	0x9 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:121,5	C#
```

I have no idea what is causing this. There are only about 20-30 View elements in total in my test project. At most I am loading two 200-400 KB png's to two Images at a time. There is nothing intense or impressive going on for it to be not able to manage it.

The same test project runs perfectly in iOS and Windows. So I suspect perhaps it is all part of the same Android bug and something is going wrong on Image generation in both bugs. Perhaps the bug is causing both problems, where sometimes it is resulting in threading errors (other report) and sometimes perhaps it is running away drawing unnecessarily big bitmaps.

Any thoughts?

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 33, .NET 7.0

### Did you find any workaround?

No, I don't really understand why it is happening.

**Comment by drasticactions** [comment]
Without a repro project, it's very difficult to know what you're doing to be able to reproduce these conditions. If you could create a small reproduction project, outside of your codebase, to demonstrate what you're doing, that would be helpful to debug the problem. Thank you!

**Comment by jonmdev** [comment]
I figured out the root and posted a new issue with repro code here: https://github.com/dotnet/maui/issues/17881

Closing this issue.
