### ISSUE TITLE
[Windows] `CollectionView` throws NRE when `ScrollTo` method is called from a handler of event `Window.Created`

### ISSUE THREAD

**Issue by jns300** [dotnet/maui#17865]
### Description

When the method `ScrollTo` from the class `CollectionViiew` is called from a handler of the event  `Window.Created` then `NullReferenceException` is thrown.
Below code shows the overridden method `CreateWindow` from the `App` class:
```csharp
protected override Window CreateWindow(IActivationState activationState)
{
    Window window = base.CreateWindow(activationState);
    window.Created += (s, e) =>
    {
        CollectionViewScrollToIssue.MainPage.Instance?.RevealLastItem();
    };
    return window;
}
```
Below is the code snippet from the `MainPage` class:
```csharp
public MainPage()
{
    InitializeComponent();
    BindingContext = viewModel = new ItemListViewModel();
    Instance = this;
}

public void RevealLastItem()
{
    var item = viewModel.Items.Last();
    collectionView.ScrollTo(item, null, ScrollToPosition.MakeVisible, false);
}

public static MainPage Instance { get; private set; }
```

### Steps to Reproduce

    1. Download the code of the linked project and start the app.
    2. At the startup the `NullReferenceException` is raised.

### Link to public reproduction project repository

https://github.com/jns300/Bugs/tree/main/CollectionViewScrollToIssue

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Relevant log output

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Platform.ScrollHelpers.<JumpToItemAsync>d__16.MoveNext()
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewHandler`1.<ScrollTo>d__60.MoveNext()
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewHandler`1.<ScrollToRequested>d__59.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Windows 11, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[CollectionViewScrollToIssue.zip](https://github.com/dotnet/maui/files/12854353/CollectionViewScrollToIssue.zip)

**Comment by krdmllr** [comment]
We have the same issue on Windows VS 17.7.5 and 17.8.0 Preview 3.0

**Comment by scriptBoris** [comment]
Any progress?

**Comment by jsuarezruiz** [comment]
The issue will be fixed by https://github.com/dotnet/maui/tree/fix-17865

**Comment by malsabi** [comment]
Im having this issue and its delaying our production. I tried many solutions but all of them failed. If there's any workaround please let us know. @jsuarezruiz
