### ISSUE TITLE
[Enhancement] Provide a Rendered event for WebView

### ISSUE THREAD

**Issue by mikeparker104** [dotnet/maui#1786]
## Summary
The WebView provides a Navigated event that is raised when navigation completes. However, the respective web page may not have fully rendered at this stage. If it's possible to consistently infer when a page has fully rendered across all supported platform targets, this would avoid the need for custom platform code.

## API Changes

Add a Rendered event to compliment the existing Navigated event.

## Intended Use Case
Triggering script functions on a page that cannot be called before the page has rendered.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We think that the `OnAfterRender` is the right place to wire up custom logic to detect whether the application is ready for specific actions or not.
