### ISSUE TITLE
[Bug] Android - App stuck at splash screen after clearing data from settings

### ISSUE THREAD

**Issue by soundaranbu** [dotnet/maui#1787]
MAUI Blazor - Android - App stuck at splash screen after clearing data from settings

### Steps to Reproduce

1. Install Maui Blazor app in android (I tried the default example installed via USB debugging) - 
2. App works normally 
3. Now goto settings -> manage apps -> select Maui blazor app -> clear data
4. Open the app again. Now it gets stuck at the landing page. 

### Expected Behavior
App should work normally even after clearing the app data. 

### Actual Behavior
App stuck at the splash screen

### Basic Information

- Version with issue: .NET 6 preview 6
- Last known good version:
- IDE: Visual Studio 2019
- Android: Android 11 (Redme Note 9 Pro) 

### Screenshots
After clearing data

![Screenshot_2021-07-23-20-47-10-820_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/29944019/126803660-a47d6ac6-9bc9-4323-8370-079fc1e1b96a.jpg)

Stuck at splash screen

![Screenshot_2021-07-23-20-46-37-118_com.companyname.MauiBlazorApp.jpg](https://user-images.githubusercontent.com/29944019/126803802-232fba03-9ba3-4dcf-81a0-695a45eebea9.jpg)

**Comment by Eilon** [comment]
Hi @soundaranbu , can you confirm whether a non-Blazor MAUI app works for you?

There might be some Blazor-specific issues in this scenario that we are fixing, but it could also be some other more general issue.

**Comment by soundaranbu** [comment]
Hi @Eilon sorry for the late response. I just got a chance to try it out. The non blazor Maui app also has the same behavior. I tried the default template comes with `dotnet new maui` command.

**Comment by Eilon** [comment]
@soundaranbu thank you for confirming, good to know it isn't specific to Blazor.

**Comment by soundaranbu** [comment]
Finally, after preview 13, I was able to install the app in release mode. Now this issue don't occur. I hope this issue can be closed. Thanks :)
