### ISSUE TITLE
Splash Screen Issue on Tablets in both portrait and landscape modes

### ISSUE THREAD

**Issue by Brionvega** [dotnet/maui#17887]
### Description

I'm currently developing a .NET MAUI app and have encountered an issue with the splash screen. I'm using an SVG image with a gradient as the splash screen, and while it works perfectly on Android and iPhone devices, it doesn't stretch to cover the entire screen on iPad devices, whether in portrait or landscape mode.

Is it possible to differentiate between the two (iPad and iPhone) within the MAUI project to address this issue? I would like to ensure that the splash screen displays correctly on iPad devices regardless of their orientation.

Additional Context:

Are there any configuration options or platform-specific adjustments that can be made to ensure the splash screen scales properly on iPad devices, adapting to both portrait and landscape orientations, while maintaining compatibility with iPhones and Android devices?

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16+

**Comment by harima34** [comment]
I also got the same problem, there is a way to  select different splashscreen if is a tablet or not ?

**Comment by jsuarezruiz** [comment]
Could you share a reproduction sample or the SVG?. If is not possible, could you share a screenshot from the result?

**Comment by Brionvega** [comment]
> Could you share a reproduction sample or the SVG?. If is not possible, could you share a screenshot from the result?

Hi @jsuarezruiz.

I have attached below a sample of the current SVG and result on both devices.

![Spalsh_Screen_Sample](https://github.com/dotnet/maui/assets/109430133/030183a5-12f4-404f-998f-0ab436705f38)
![Splash_Screen_iOS_iPad jpg](https://github.com/dotnet/maui/assets/109430133/5111e15e-9d94-4a37-ac39-b2f19434a1da)
![Splash_Screen_iOS_iPhone](https://github.com/dotnet/maui/assets/109430133/29d2f79d-ef40-4f28-b3d1-1bd7634caff7)

On the project file, I've set splash screen as follows,

`<MauiSplashScreen Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'" Include="Resources\Splash\test.svg" Resize="false" BaseSize="1850,940" Color="#000000" />`
