### ISSUE TITLE
[Android] Entry.Keyboard == null regression

### ISSUE THREAD

**Issue by DmitryRomenskiy** [dotnet/maui#17899]
### Description

Hello,

When using Android API 29 and set `Keyboard` to `{Null}`, I expect to see that no software keyboard will be shown for this element. This is exactly what happens. When using Android API 33, the keyboard is still present and pops up on focus.

### Steps to Reproduce

1. Add `Entry` to a view
2. Set its `Keyboard` to `null`
3. Launch the application on Android emulator API 33
4. Focus the entry

Expected outcome: The software keyboard is not shown
Actual outcome: The software keyboard is shown

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 33

### Did you find any workaround?

I can hide the keyboard manually on focus:

```
private void OnFocus(object sender, FocusEventArgs e) {
#if ANDROID
            Dispatcher.Dispatch(() => {
                    if (Platform.CurrentActivity.CurrentFocus != null)
                        Platform.CurrentActivity.HideKeyboard(Platform.CurrentActivity.CurrentFocus);
                });
#endif
}
```

**Comment by jsuarezruiz** [comment]
@rachelkang Thoughts?

**Comment by DmitryRomenskiy** [comment]
@rachelkang @jsuarezruiz 
Calling you again just in case

**Comment by RoiChen001** [comment]
I can't repro this issue on the latest 17.10.0 Preview 1.0.
![code](https://github.com/dotnet/maui/assets/143168639/2750b881-1cb5-413c-ae88-b31aaab7e6a9)
