### ISSUE TITLE
SecurityStorage nullability or docs are wrong

### ISSUE THREAD

**Issue by trampster** [dotnet/maui#17893]
### Description

SecureStorage.GetAsync is defined as returning Task<string> of a non nullable string

And the file has the #nullable enable set. So it shouldn't return null.

However the docs say that it's null if there is no value.

https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/secure-storage?tabs=android#use-secure-storage

Which is it? are the docs wrong or is the nullability wrong. If the code is correct what does it return if there is no value?

### Steps to Reproduce

Look at docs and go to definition of SecureStorage in code.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

**Comment by trampster** [comment]
I see that this was fixed in the code on Jan 17, 2023.

However I don't have that fix. How do I update? We have just migrated from Xamarin.Forms using the upgrade assistant. 

It looks like you don't reference the maui packages directly but get them "magically" through ```<UseMaui>true</UseMaui>``` This means you can't set the version.

**Comment by jsuarezruiz** [comment]
> I see that this was fixed in the code on Jan 17, 2023.
> 
> However I don't have that fix. How do I update? We have just migrated from Xamarin.Forms using the upgrade assistant.
> 
> It looks like you don't reference the maui packages directly but get them "magically" through `<UseMaui>true</UseMaui>` This means you can't set the version.
> 
> I have version 7.0.92 for maui-android and maui.ios workloads.

This have been fixed in .NET 8. Could you try with  .NET 8 RC1?

**Comment by trampster** [comment]
I haven't been able to test it but I have review the code change and am sure it will work.
