### ISSUE TITLE
Maui app under iOS 17.0.3 not working crash

### ISSUE THREAD

**Issue by Ahmadmansoor** [dotnet/maui#17908]
### Description

create any Maui app use any DotNet 6~7 then deploy under the physical device, the app will never load and keep crashing at the start logo.

### Steps to Reproduce

1- create any Maui app use any DotNet 6~7 then
2- deploy under the physical device,
3-run the app and you will note that it will never load and keep crashing at the start logo.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.0.3

### Did you find any workaround?

No

### Relevant log output

```shell
I don't have a simulator to check.
```

**Comment by drasticactions** [comment]
Are you deploying on the Mac, on Windows through a remote Mac host, or through Hot Restart?

**Comment by affableashish** [comment]
@AhmadmansoorCan you add a sample project that's crashing?

**Comment by Ahmadmansoor** [comment]
Hi sorry for the late reply, I am trying to get more info about the issue.
I am using the MacOS version 12.7 under VMware
![image](https://github.com/dotnet/maui/assets/7176580/a7e554ca-f38d-4a91-856d-24d3330aede0)
I think Xcode is 14.01 and unable to install the upper version as the MacOS is just 12.7, I tried to install Sonoma many times but I was unable to succeed 👎 .
I think I need the last version of Xcode to check what the problem is exactly which crashes the application at startup.
I connect my registered iPhone and from the menu, I deploy to the phone.
sample project: just create any new Maui app and try to deploy it.

**Comment by Ahmadmansoor** [comment]
Does anybody give it a try?

**Comment by ninachen03** [comment]
Verified this issue on  17.6.9.415, it can deploy on physical phone
