### ISSUE TITLE
Java.Lang.IllegalArgumentException: You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by ac-lap** [dotnet/maui#17915]
### Description

I am building an eBook reader app (primarily targeting android). The app displays list of books (image + text). But whenever the app is 're-initialized' (I am using it for lack of my understanding of correct term), all the images in the app stop loading with the below error.

This 're-initialization' I have noticed happening following scenarios -

1. The app is running, toggle the Android system theme - Dark/Light theme (Happens only on some devices, not all, API 33)
2. The app is running, and it receives an intent. Following is the intent filter defined -
`[IntentFilter(new[] { Intent.ActionView }, Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable }, DataScheme = "com.xx.yy")]`
3. The app is the background for very long, when brought to foreground.

In all these cases `OnCreate()` is called in the `MainActivity`.

From the error in the Glid library, looks like it continuing to use the old activity instance. How can I re-initialize Glide library to use the new activity? or how can I fix this issue, or any workaround?

I am using # 2 above for fetching Google API OAuth token, and upon login the app is wrecked which is very poor experience. It happens on both debug and release build and multiple devices.

```
Unable to load image file '/data/user/0/com.xx.yy/files/CoverImage/a5c6f357-0458-4db1-9999-74387c2ee156.jpg'. --> 
Java.Lang.IllegalArgumentException: You cannot start a load for a destroyed activity

java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:353)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:153)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:217)
	at com.bumptech.glide.Glide.with(Glide.java:902)
	at com.microsoft.maui.PlatformInterop.loadImageFromFile(PlatformInterop.java:244)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by ac-lap** [comment]
Folks, can I plz get some assistance on this issue.

**Comment by ac-lap** [comment]
@jsuarezruiz, @samhouts plz help with this, I am unable to use app activation through intent because of this issue. I believe this is a very fundamental issue.

**Comment by ac-lap** [comment]
I am sharing a sample app that reproes the issue on Android.

Steps -
1. Run/start the app 'TestImageApp'.
2. Minimize the app.
3. Open any file explorer app, try to open any .txt file with the 'TestImageApp' app. (This step is just to call MainActivity.OnCreate() again)
4. Click on the 'Reload Image' button. Now the images disappear.

[TestImageApp.zip](https://github.com/dotnet/maui/files/13366282/TestImageApp.zip)

**Comment by williambuchanan2** [comment]
Any update on this? I am experiencing the same problem and Google sent me an email saying they are going to remove the app from the play store because this is causing it to go against their "Broken Functionality Policy".

**Comment by williambuchanan2** [comment]
Incidentally - error messages like this are largely unhelpful. There isn't really much in there which is understandable to a .NET developer.

**Comment by dupuisdavid** [comment]
Hello, we are experiencing the same problem.
We can easily reproduce it by activating The "don't keep activities in the background" developer option.
On first launch, every images are displayed, but if put app in background then put it back to foreground, every images have disapeared.
Any update on it? It becomes pretty urgent!

**Comment by williambuchanan2** [comment]
> Hello, we are experiencing the same problem. We can easily reproduce it by activating The "don't keep activities in the background" developer option. On first launch, every images are displayed, but if put app in background then put it back to foreground, every images have disapeared. Any update on it? It becomes pretty urgent!

We are also having the same problem with images. Doesn't happen in iOS, but in Android the images are replaced by blank spaces. This even happens if you just move to another tab.

**Comment by dupuisdavid** [comment]
@williambuchanan2. On Android for us too.

**Comment by ac-lap** [comment]
@jsuarezruiz @samhouts @jsuarezruiz can you folks please help get some traction on this issue?
This is a quite fundamental problem and needs to be addressed but unfortunately, we are not getting any help.

**Comment by jonpryor** [comment]
I can't *directly* repro this.

Building upon the [above repro steps](https://github.com/dotnet/maui/issues/17915#issuecomment-1812744500), here are my steps:

 1. Create the file in Downloads to interact with:

    ```sh
    echo "hello" | adb shell 'cat > /storage/emulated/0/Download/hello.txt'
    ```

 2. Begin capturing `adb logcat`:

    ```sh
    adb logcat > log.txt
    ```

 3. Run/start the app 'TestImageApp'; in a different shell from (2), run:

    ```dotnetcli
    dotnet build -f net7.0-android -t:StartAndroidActivity
    ```

 4. On the Android target, go to the Home screen and launch the **Files** app.
 5. Within the **Files** app, tap Categories > Downloads
 6. Tap the "vertical …" menu to the right of "hello.txt", then tap **Open with**, then tap **TestImageApp**
 7. Tap the **Reload Image** button within TestImageApp.

Expected results: images should be shown!

Actual results: images disappear!

So at least I'm able to repro "images disappear".

What I'm *not* able to repro is the original reported stack trace: my `log.txt` (step 2) *does **not** contain* the originally reported message:

```
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
```

When I search for `glide` in my `log.txt`, I instead find:

```
W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
W Glide   : There were 3 root causes:
W Glide   : java.io.FileNotFoundException(/sample_b.jpg: open failed: ENOENT (No such file or directory))
W Glide   : java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
W Glide   : java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
…
```

However, I'm not sure which app launch this corresponds to, and I am not able to reliably recreate this message.

Additionally, something that confuses me is that when I swipe up from the bottom to show the open apps, I see two apps:

 1. TestImageApp
 2. Files app with TestImageApp *on top*.

I don't know what this means, if anything.

Finally, I also override many additional [Activity lifecycle methods](https://developer.android.com/reference/android/app/Activity#ActivityLifecycle), including:

  * `OnCreate`
  * `OnDestroy`
  * `OnRestart`
  * `OnResume`
  * `OnStart`
  * `OnStop`

a'la:

```csharp
    public partial class MainActivity : MauiAppCompatActivity
        protected override void OnDestroy()
        {
            Console.WriteLine($"# jonp: MainActivity.OnDestroy");
            Console.WriteLine(new StackTrace(true));
            base.OnDestroy();
        }
    }
```

`OnDestroy()` is never invoked for me.

**Comment by jonpryor** [comment]
After some further putzing around…

When I carry out step (6) ("Tap the 'vertical …' menu to the right of 'hello.txt', then tap Open with, then tap TestImageApp"), that creates a *new* `Activity` instance to be created.  It is plausible that *whatever is using glide* "caches" the `Activity` instance somewhere, and in .NET 7 MAUI the cached instance was destroyed at some point, resulting in the originally reported `java.lang.IllegalArgumentException`.

I have also found a workaround: in `reload_tap()` within `MainPage.xaml.cs`, instead of:

```csharp
// old and busted
img1.Source = filePath[0];
```

use this workaround:

```csharp
// workaround hotness
((FileImageSource)img1.Source).File = filePath[0];
```

[`ImageSource` has an implicit conversion from `string`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.imagesource.op_implicit?view=net-maui-8.0), so the "old and busted" line is more equivalent to:

```csharp
// old and busted equivalent
img1.Source = ImageSource.FromFile(filePath[0]);

// which in turn is equivalent to
img1.Source = new FileImageSource { File = filePath[0] };
```

and my *guess* is that creating a new `FileImageSource` is where things go wrong.  The workaround instead modifies the existing `FileImageSource` instance instead of creating a new one, and updating the existing instance appears to work as desired.

**Comment by jonpryor** [comment]
With some additional putzing around, consider this diff to `MainActivity.xaml.cs`, which subscribes to the `PropertyChanged` event on the images:

```diff
--- MainPage.xaml.cs.bk	2024-05-22 13:24:30
+++ MainPage.xaml.cs	2024-05-22 13:24:52
@@ -1,4 +1,6 @@
 ﻿using Microsoft.Maui.Storage;
+using System.ComponentModel;
+using System.Runtime.CompilerServices;
 
 namespace TestImageApp
 {
\ No newline at end of file
@@ -8,7 +10,7 @@
 
         public MainPage()
         {
-            Console.WriteLine($"# jonp: MainPage..ctor");
+            Console.WriteLine($"# jonp: MainPage..ctor: id={RuntimeHelpers.GetHashCode(this)}");
             InitializeComponent();
 
             Initialize();
\ No newline at end of file
@@ -32,9 +34,23 @@
                 }
             }
 
+            PropertyChangedEventHandler h = (s, e) => {
+                var instance = s switch {
+                    var o when o == img1 => "img1",
+                    var o when o == img2 => "img2",
+                    var o when o == img3 => "img3",
+                    _ => "unknown"
+                };
+                Console.WriteLine($"# jonp: PropertyChangedEventHandler: sender={instance} e.PropertyName={e.PropertyName}");
+            };
+
             img1.Source = filePath[0];
             img2.Source = filePath[1];
             img3.Source = filePath[2];
+
+            img1.PropertyChanged += h;
+            img2.PropertyChanged += h;
+            img3.PropertyChanged += h;
         }
 
         private void reload_tap(object sender, EventArgs e)
\ No newline at end of file
@@ -47,6 +63,7 @@
             // img2.Source = filePath[1];
             // img3.Source = filePath[2];
             ((FileImageSource)img1.Source).File = filePath[0];
+            Console.WriteLine($"# jonp: setting img1.Source…");
             img1.Source = new FileImageSource { File = filePath[0] };
             ((FileImageSource)img2.Source).File = filePath[1];
             ((FileImageSource)img3.Source).File = filePath[2];
\ No newline at end of file
```

When I just launch the app and tap "Reload Image", `adb logcat` contains:

```
# jonp: reload_tap
# jonp: filePath[0]=/data/user/0/com.companyname.testimageapp/files/0.jpg True
# jonp: filePath[1]=/data/user/0/com.companyname.testimageapp/files/1.jpg True
# jonp: filePath[2]=/data/user/0/com.companyname.testimageapp/files/2.jpg True
# jonp: setting img1.Source…
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=Source
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=IsLoading
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=X
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=Width
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=IsLoading
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=X
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=Width
```

In particular, note that the `IsLoading`, `X`, and `Width` properties are changed *twice*.

When I carry out [steps 4-7](https://github.com/dotnet/maui/issues/17915#issuecomment-2121253554), I see:

```
# jonp: reload_tap
# jonp: filePath[0]=/data/user/0/com.companyname.testimageapp/files/0.jpg True
# jonp: filePath[1]=/data/user/0/com.companyname.testimageapp/files/1.jpg True
# jonp: filePath[2]=/data/user/0/com.companyname.testimageapp/files/2.jpg True
# jonp: setting img1.Source…
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=Source
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=IsLoading
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=X
# jonp: PropertyChangedEventHandler: sender=img1 e.PropertyName=Width
```

Here, note that `IsLoading`, `X`, and `Width` are only modified *once*.

Also interesting (to me) is the `# jonp: MainPage..ctor: id=…` message: it only appears *once*, suggesting that the newly created Activity is using the same `MainPage`/`ContentPage` instance as the originally created Activity.

What does this *mean*?  I have no idea.  I just find it *interesting*.
