### ISSUE TITLE
maui dev ，in android window is ok ,in ios webview <img src=x.png 。not display ,but use remote url is ok ,why ? 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#17912]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/maui-dev-，in-android-window-is-ok-in-io/10482598)._

---
vs 2022 17.7.4 

in ios webview `<a href="x.png"> Image:x.png</a><a href="http://192.168.3.100:88/x.png"> Image:x.png</a> `is ik

maui ios bug ? now in ios use remote url. but svg file is ok , and ios local device (iPhone) debug ,can't use safai or Chrome debug . iphone safai other website  can debug web page . You cannot debug webviews within the app

![image](https://github.com/dotnet/maui/assets/1096616/2ebb947a-99ad-4323-8575-6b0ea8aaed9c)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem.
