### ISSUE TITLE
AAB Android Format

### ISSUE THREAD

**Issue by mohammadaminyza** [dotnet/maui#1792]
Hi, Will Maui Support AAB?

**Comment by vhugogarcia** [comment]
I am pretty sure it will.

**Comment by themronion** [comment]
It will be the default option for an android app since google play market is deprecating apks starting from august

**Comment by Redth** [comment]
Should work already, use the property `<AndroidPackageFormat>aab</AndroidPackageFormat>` in your .csproj in the appropriate place just like in Xamarin.Android.
