### ISSUE TITLE
Android: FileNotFoundException only in Release-Mode when using System.Diagnostics.FileVersionInfo.GetVersionInfo(...)

### ISSUE THREAD

**Issue by monsterkeks** [dotnet/maui#17932]
### Description

Our Application uses NetStandard-library project to reflect the version of the application. This library is used by Maui and Blazor with a project reference. 

We reflect the version:
  ```csharp
        public static string GetVersionInternal()// e.g. => "2.8.0.1";
            => FileVersionInfo
                .GetVersionInfo(AppContext.BaseDirectory).FileVersion;
  ```

it results in an FileNotFoundException:

` ---> System.IO.FileNotFoundException: /ArieTech.Core.Extensions.dll
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String )
   at ArieTech.Core.Extensions.HelperMethods.GetVersionInternal()
   at ArieTech.Tools.Common.ApplicationScope.get_VersionString()`

Our application uses the .Net Assembly-Versioning pattern. The version in the .csproj-file of this library is updated within a GitHub-Action Task. This version is used for displaying the version the footer of the AppShell of the Maui-App as well as a Blazor-Web-App in our solution. This worked in Xamarin and this is working also on Android, but not in Release-Mode. 

This is a duplicate of #15679 (closed), but the workaround @Eilon mentioned there, isn't working for us, because our `VersionName` in the `AndroidManifest.xml` file is partly different from the one in the assembly. In addition we're unable to use MauiEssentials.VersionTracking in a library project.

In my understanding, the fact that this exception only occurs in release mode and only on Android points out, that it is still a bug. 

### Steps to Reproduce

Steps for reproduction can be found in this recently closed #15679

If necessary, we'll create repro-repo.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No. 

Maybe some Linker-Options? But we're unable to figure it out.

**Comment by drasticactions** [comment]
If you create a .NET Android app that doesn't use the MAUI UI Framework (`dotnet new android`), does the same exception occur? If so, this should probably be moved to [dotnet/runtime](https://github.com/dotnet/runtime/issues).

**Comment by monsterkeks** [comment]
@drasticactions: yes, it shows the same behavior. Steps to reproduce

1.  `dotnet new android` 
2. In the `OnCreate` method:
    ```csharp
        System.Reflection.Assembly assembly = System.Reflection.Assembly.GetExecutingAssembly();

        try
        {
            var location = assembly.Location;
            Console.WriteLine($"[Issue17932] Assembly.Location: {location}");

            var fileVersion = System.Diagnostics.FileVersionInfo.GetVersionInfo(location).FileVersion;
            Console.WriteLine($"[Issue17932] FileVersion: {fileVersion}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[Issue17932] Exception: {ex}");
            throw;
        }
    ```

Crashes in Release-Mode and runs in Debug mode.

**Comment by mattleibow** [comment]
I believe Android apps do not have files in a location to check the versions.

There are two alternatives:

1. Use that same `assembly` in the code above and get the assembly attributes: `assembly.GetCustomAttributes< AssemblyFileVersionAttribute>().Version`
2. Use Essentials APIs: `AppInfo.Current.VersionString`

I also think that in various other scenarios, reading the file may not work. Especially with AOT or other things.

**Comment by monsterkeks** [comment]
Thx for the hint @mattleibow, I checked this (again), but:

As I mentioned above, the code, which reflects the version is located in a netstandard library, which is referenced by a Xamarin-App (Production), a Maui-App (Migration) and a Blazor-Web-App. In a previous version of our app we used the generic `assembly.GetCustomAttribute<AssemblyFileVersionAttribute>().Version`-method, but it broke on iOS a few month ago. We were unable to figure out, what was the reason for that, but were able to rule out an XF-Update. So we switched to `FileVersionInfo.GetVersionInfo(..)` and, we were able to retrieve the version on all platforms again.

I checked this again with `dotnet new` on .Net-8-RC1, and it works now on both platforms, iOS and Android, but is still **_not working_** (returning null) on a (native) Xamarin-iOS project. Regarding the Maui-context, `GetCustomAttribute<AssemblyFileVersionAttribute>()` solves this issue, but we're still unable to find a common solution.

**Comment by mattleibow** [comment]
@rolfbjarne  @jonathanpeppers thoughs?

@monsterkeks this does not appear to be a maui issue, maybe open an issue on:
 - Android: https://github.com/xamarin/xamarin-android/issues
 - iOS/Mac Catalyst: https://github.com/xamarin/xamarin-macios/issues

**Comment by rolfbjarne** [comment]
> I checked this again with `dotnet new` on .Net-8-RC1, and it works now on both platforms, iOS and Android, but is still **_not working_** (returning null) on a (native) Xamarin-iOS project. Regarding the Maui-context, `GetCustomAttribute<AssemblyFileVersionAttribute>()` solves this issue, but we're still unable to find a common solution.

This might be because the linker removes the attribute at build time. In any case, please file an issue with your test project at https://github.com/xamarin/xamarin-macios/issues/new and we'll have a look.

**Comment by jonathanpeppers** [comment]
Files like `/ArieTech.Core.Extensions.dll` are never openable on Android as `.apk` files remain compressed on disk. Because this is a thing you can't even do at all on Android, `AppContext.BaseDirectory` likely just returns an empty string. I believe the code above just *will not work* at all on Android.

I would recommend passing in values to the `netstandard` library:
```csharp
//Untested
var context = Application.Context; // or if you are inside an activity, use "this" instead
var versionName = context.PackageManager.GetPackageInfo(context.PackageName, 0).VersionName;
YourLibrary.Initialize(versionName);
```
