### ISSUE TITLE
[regression/8.0.0] SkiaSharp signature check fails for deployment (Visual Studio local iOS device)

### ISSUE THREAD

**Issue by espenrl** [dotnet/maui#17930]
### Description

This happens when deploying a `dotnet new maui` app with package refrences to `SkiaSharp`. It works on .NET 7 and is a regression for .NET 8.

```
Xamarin.Messaging.IDB.Local.DeployAppMessageHandler Error: 0 : An error occurred while trying to deploy the app 'net8test.app'. Details: Could not install the application '<redacted>\AppData\Local\Temp\Xamarin\HotRestart\Signing\net8test.app\out\net8test.ipa' on the device <redacted>. Details: ApplicationVerificationFailed|0xE8008014 - Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Pc97q0/extracted/Payload/net8test.app/Frameworks/libSkiaSharp.framework : 0xe8008014 (The executable contains an invalid signature.)
Xamarin.iOS.Windows.WindowsiOSException: Could not install the application '<redacted>\AppData\Local\Temp\Xamarin\HotRestart\Signing\net8test.app\out\net8test.ipa' on the device <redacted>. Details: ApplicationVerificationFailed|0xE8008014 - Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Pc97q0/extracted/Payload/net8test.app/Frameworks/libSkiaSharp.framework : 0xe8008014 (The executable contains an invalid signature.)
   at Xamarin.iOS.Windows.Installer.ApplicationSession.InstallApp(String appPath, String appBundleId) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\Installer\ApplicationSession.cs:line 276
   at Xamarin.iOS.Windows.Installer.ApplicationSession.Deploy(String appRootFolder, String appBundleId, String appName) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\Installer\ApplicationSession.cs:line 95
   at Xamarin.iOS.Windows.HotRestartClient.Deploy(AppleDevice nativeDevice, String appBundleId, String appBundleName, Boolean& incremental) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\HotRestartClient.cs:line 250
   at Xamarin.Messaging.IDB.Local.DeployAppMessageHandler.<ExecuteAsync>d__5.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\Handlers\DeployAppMessageHandler.cs:line 43: 10.10.2023 13:40:53Z
    DateTime=2023-10-10T13:40:53.6841338Z: 10.10.2023 13:40:53Z
```

### Link to public reproduction project repository

https://github.com/espenrl/issue-repro/tree/main/net8-skiasharp

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by mattleibow** [comment]
@rolfbjarne thoughts?

**Comment by rolfbjarne** [comment]
The sample project works fine for me.

@espenrl can you try running the project directly from the mac using Visual Studio for Mac to see if that works?

**Comment by drasticactions** [comment]
Going by the error in the stack trace, they are using Hot Restart, so it could be specific to that app bundle.

**Comment by espenrl** [comment]
> The sample project works fine for me.
> 
> @espenrl can you try running the project directly from the mac using Visual Studio for Mac to see if that works?

I don't use or have a Mac in my development. I use Windows and Github Actions CI to publish the app. Sorry.

**Comment by espenrl** [comment]
I've also been sure to delete obj/bin and anything in `C:\Users\erl0\AppData\Local\Temp\Xamarin\HotRestart` so it shouldn't be a cache issue.

**Comment by rkone** [comment]
Also happening for me.  Also in 8.0.0.rc.2.9373 and Visual Studio 17.8.0 Preview 3.0

**Comment by espenrl** [comment]
> rkone

Same software versions in my case.

**Comment by rolfbjarne** [comment]
Can you get a binlog as described here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs?

**Comment by espenrl** [comment]
[net8test_Debug_AnyCPU_net8.0-ios_Build_2023-10-17T12_49_57.7879151+02_00.zip](https://github.com/dotnet/maui/files/12927751/net8test_Debug_AnyCPU_net8.0-ios_Build_2023-10-17T12_49_57.7879151%2B02_00.zip)

@rolfbjarne here you go

**Comment by rolfbjarne** [comment]
I can reproduce, and I'm looking at it to see what needs to be done.

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#19278
