### ISSUE TITLE
Maui Splash Screen will not update on iOS App

### ISSUE THREAD

**Issue by ISSPRO-Eng** [dotnet/maui#17940]
### Description

I changed the default splash images in my MAUI solution. The changes were effected on Android device but on iOS device, the default splash images show. Even just changing the Color property in the .csproj file has no effect on iOS device. I am using Visual Studio Version 17.6

### Steps to Reproduce

Create a new MAUI app
Change the splash image. (or just change the Color property of the SplashScreen property in .csproj file.
Run or deploy the app to Android Device - the splash images are updated as expected
Run or deploy the app to iOS device - the changes are not effected. The default .NET splash images still shows,
Try to change the name of the splashscreen svg file, delete app on iOS device, reboot device, clean solution and deploy to iOS device - still splash images not updated.

### Link to public reproduction project repository

none

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 14 and up

### Did you find any workaround?

None yet. I was able to create a new app and was able to update the splash screen, but my current app will not accept the same updates. I have a lot of code, so I am looking for a fix as creating a whole new app would take some time. I have tried clearing bin/obj folders, restarting VS, restarting Mac, rebuilding project etc.

**Comment by MouratidisA** [comment]
A solution that works for me:

1. Use [Photopea](https://www.photopea.com/) to overwrite the existing .svg files for the splash and the app icon of the project.
2. Close Visual studio
3. Delete bin and obj folders
4. Uninstall the app (if installed) from the iOS device
5. Restart the iOS device
6. Open Visual studio
7. Rebuild the solution
8. Run the app on the iOS device

Note:
The splash configurations I used in my .csproj file:
```
<MauiSplashScreen Include="Resources\Splash\splash.svg" Link="Resources\Splash\splash.svg" Color="#D13E43" BaseSize="128,128" />
```

Following the above steps helped me update the splash and app icon updates while testing my application on iPhone devices.
