### ISSUE TITLE
[Bug] I'm getting the `NETSDK1139: The target platform identifier maccatalyst was not recognized.` error

### ISSUE THREAD

**Issue by MahmudX** [dotnet/maui#1795]
### Description

Created a basic maui app and couldn't run it.

### Basic Information

- IDE: Visual Studio 2022 preview
- Windows: 11

### maui-check

```
> OpenJDK 11.0 Checkup...
  - 11.0.10 (C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot\bin\..)

> Visual Studio 17.0.0-pre.2.0 Checkup...
  - 16.10.4
  - 17.0.0-pre.2.1 - C:\Program Files\Microsoft Visual Studio\2022\Preview

> Android SDK Checkup...
  - emulator (30.1.5)
  - build-tools;30.0.2 (30.0.2)
  - platforms;android-30 (3)
  - system-images;android-30;google_apis;x86 (9)
  - platform-tools (30.0.4)

> Android Emulator Checkup...
  - Emulator: piedevice found.

> .NET SDK Checkup...
  - 5.0.302 - C:\Program Files\dotnet\sdk\5.0.302
  - 6.0.100-preview.6.21355.2 - C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2

> .NET SDK - Workload Deduplication Checkup...

> Edge WebView2 Checkup...
  - Found Edge WebView2 version 92.0.902.55

> .NET SDK - Workloads (6.0.100-preview.6.21355.2) Checkup...
  - microsoft-android-sdk-full (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 30.0.100-preview.6.62) installed.
  - microsoft-ios-sdk-full (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-preview.6.63) installed.
  - microsoft-maccatalyst-sdk-full (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-preview.6.63) installed.
  - microsoft-tvos-sdk-full (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-preview.6.63) installed.
  - microsoft-macos-sdk-full (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-preview.6.63) installed.
  - maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-preview.6.1003) installed.
  - microsoft-net-runtime-android (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-preview.6.21352.12)
installed.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

- Congratulations, everything looks great!
```

### Error from the console

```
❯ dotnet run
C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.workload.mono.toolchain\WorkloadManifest.targets(22,9): warning MSB4011: "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.RuntimeConfigParser.Task\6.0.0-preview.6.21352.12\Sdk\Sdk.props" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.ios\WorkloadManifest.targets (8,2)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\Mahmud\Downloads\maui-samples-main\maui-samples-main\HelloMaui\HelloMaui.csproj]
C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.workload.mono.toolchain\WorkloadManifest.targets(30,9): warning MSB4011: "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.RuntimeConfigParser.Task\6.0.0-preview.6.21352.12\Sdk\Sdk.props" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.maccatalyst\WorkloadManifest.targets (4,2)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\Mahmud\Downloads\maui-samples-main\maui-samples-main\HelloMaui\HelloMaui.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(109,5): error NETSDK1139: The target platform identifier maccatalyst was not recognized. [C:\Users\Mahmud\Downloads\maui-samples-main\maui-samples-main\HelloMaui\HelloMaui.csproj]

The build failed. Fix the build errors and run again.
```

### Screenshots I run from IDE

![Screenshot_2](https://user-images.githubusercontent.com/16564582/126860679-0bc0b350-01ee-400a-b653-621e5f36cf95.png)
![Screenshot_3](https://user-images.githubusercontent.com/16564582/126860680-6095968f-7600-4ae1-aca8-a1ca7cb861c4.png)
![Screenshot_4](https://user-images.githubusercontent.com/16564582/126860683-c32799bb-fb5c-4966-a70f-1e4194848f27.png)

### Installed workloads

![Screenshot_5](https://user-images.githubusercontent.com/16564582/126860739-b548f21d-121f-47ce-bffe-0b712bf26e74.png)

**Comment by wstaelens** [comment]
same problem, trying to open MAUI project and having NETSDK1139 (VS2022)

**Comment by jsuarezruiz** [comment]
Seems to be an issue with workloads. 

Use the following script to remove the previous workloads (you could have a mix of old ones).

Update VS 2022 to the latest Preview. Then, install .NET workloads 

`dotnet workload install maui`

or 

`dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.10.json`

**Comment by PaulGH** [comment]
(shot in the dark?) 
Check your PATH (Environment Variables). if you have other version of VS on your box that are 32-bit and its environment variable is appearing first in the list, VS will not be able to find the appropriate workloads for VS2022 Preview.  edit your machine's path and move the **c:\program files\dotnet** statement to the top of the list.  Then, try to run your app.

Found the solution here: https://www.hanselman.com/blog/dotnet-could-not-execute-because-the-application-was-not-found-or-a-compatible-net-sdk-is-not-installed (thanks to Scott Hanselman!).

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
