### ISSUE TITLE
Entry not getting focused if we want to set focus at the time when new activity opens 

### ISSUE THREAD

**Issue by AviralArya** [dotnet/maui#17954]
### Description

Once we navigate to a new activity the entry/editor is not getting focused itself and keyboard is not opening even after we have set up focus from xaml.cs constructor and OnAppearing method. keyboard is opening only when we tap on the entry.

### Steps to Reproduce

1.Create a new Content view or Content page
2.Add a entry in it
3.In the xaml.cs file add the entry focus in constructor 
4.Entry is not getting focused itself once we navigate to that view 

### Version with bug

Microsoft.Maui.Controls 8.0.0-nightly.9331+sha.6aac924e89-azdo.8456294
.NET SDK: 8.0.100-rc.1.23463.5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 9 and above

**Comment by QianaJiao** [comment]
Verified this issue was not repro on Visual Studio 17.10.0 Preview 1.
