### ISSUE TITLE
[regression/8.0.0-rc.2.9373] AmbiguousMatchException thrown for overloaded methods called from xaml event

### ISSUE THREAD

**Issue by NXDMN** [dotnet/maui#17950]
### Description

If there are methods with same name (but different return type and/or parameters), while one of the method is event handler method, ex. `TestBtn(object sender, EventArgs e)`  and `TestBtn()`, `AmbiguousMatchException` will be thrown. But it only throws when the event is binded through xaml, if bind programmatically then no problem.

### Steps to Reproduce

1. Create a new project.
2. Create a Button like this 
```xaml
<Button
        x:Name="CounterBtn"
        Text="Click me"
        Clicked="TestBtn"/>
```
3. Paste these code in code behind file
```cs
void TestBtn(object sender, EventArgs e)
{
    Console.WriteLine("event called");
}

void TestBtn()
{
    Console.WriteLine("normal method called");
}
```

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.1.9171

### Affected platforms

iOS, Android

### Did you find any workaround?

Change method name

**Comment by IndianaGary** [comment]
I can confirm that a project that I ported from Xamarin Forms to Maui 8.0 RC2 exhibits the same behavior.
It works just fine on Maui 7.0 and on Maui 8.0 RC1.
It occurs on Windows and Android.
As noted previously, It occurs on a reference to an Event Handler in code-behind by a XAML binding.
Details provided upon request.

**Comment by StephaneDelcroix** [comment]
is the a build or runtime failure ?

**Comment by NXDMN** [comment]
> is the a build or runtime failure ?

Runtime

**Comment by StephaneDelcroix** [comment]
runtime error in DEBUG (runtime XAML, compiled XAML is fine)

**Comment by IndianaGary** [comment]
Build failure, however, I was able to work around it by changing the name of an event handler.
