### ISSUE TITLE
[regression/8.0.0] Navigating back from a TabbedPage does not invoked a destructor

### ISSUE THREAD

**Issue by VoznichkaSviatoslav1** [dotnet/maui#17959]
### Description

Seems like navigation back from TabbedPage produce memory leak. I have run few simple tests (open view -> navigate back) and noticed then after navigating back from TabbedPage view desctructor is not invoked. 

I faced this issue on all versions of MAUI.

### Steps to Reproduce

1. pull attached repository
2. run application
3. navigate multiple times from main page to myTabbedPagea and back 
5. check console for "Destructor was called" logs. 

### Link to public reproduction project repository

https://github.com/VoznichkaSviatoslav1/TabbedPageMemoryLeak

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

@PureWeen tested this and couldn't find a version that worked

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No

https://github.com/dotnet/maui/assets/129937350/8bdab41c-5761-4b45-8cb3-f550a1cc00c4

**Comment by jonathanpeppers** [comment]
Can you share a sample app with this behavior?

**Comment by VoznichkaSviatoslav1** [comment]
> Can you share a sample app with this behavior?

I've attached the link to the repository, also noticed that if I change my TabbedPage to ContentPage, then the destructor is invoked after nearly 20 navigations, when in a case with TabbedPage destructor is not invoked at all

**Comment by samhouts** [comment]
@VoznichkaSviatoslav1 I can't build your reproduction. Also, it appears to be targetting net7.0. Is this issue present in 7.0 or 8.0? Thanks!

**Comment by VoznichkaSviatoslav1** [comment]
> @VoznichkaSviatoslav1 I can't build your reproduction. Also, it appears to be targetting net7.0. Is this issue present in 7.0 or 8.0? Thanks!

Hi @samhouts thank you for reply, I updated my solution to targeting net8, issue still exist. 
Whats the problem with the build? I've attached video with reproducing, hope it is helpful

**Comment by PureWeen** [comment]
I tested this all the way back to preview1 and back a few versions in NET7
I don't think this is a regression.

**Comment by VoznichkaSviatoslav1** [comment]
Hi there, any updates on this issue?

**Comment by konradzuse** [comment]
I have the same issue in 8.0.7, ContentPage destructor is invoked, but TabbedPage isn't.

I tried with a completely blank TabbedPage, with no tabs or children and get the same behaviour

**Comment by pauldiston** [comment]
This issue is still present in 8.0.10.

**Comment by jonathanpeppers** [comment]
After about an hour debugging... This appears to be a one line fix:

* https://github.com/dotnet/maui/pull/21218/files#diff-c76199129810d626ed8ca8ea05723ccc0f9b73d76d7de83cb353e9cf3a01bbacR126
