### ISSUE TITLE
vscode error while fetching extensions XHR failed

### ISSUE THREAD

**Issue by DarkSky7** [dotnet/maui#17962]
I posted the problem on StackOverflow recently, see: (https://stackoverflow.com/questions/77262356/vscode-error-while-fetching-extensions-xhr-failed)  Following is the content of that post: 
I  have two machines (Windows-10 and Fedora-38), each with VScode running on it. When Private Internet Access (PIA) is disabled on the Linux machine, VScode can access the extensions marketplace. When PIA is enabled, I get: "Error while fetching extensions. XHR failed".

On the W10 machine, it doesn't matter whether PIA is enabled or not, I get that same error. I have 52 extensions installed on the W10 machine, so XHR failure is a new problem. PIA has been installed for at least a couple of years, and it wasn't a headache before. The W10 machine has been through at least two system updates since I remember it working without complaining about XHR.

I've read related StackOverflow posts on the subject and tried the recommendations (Use the proxy support for extensions = On, Override, Fallback) on the W10 machine, but nothing has worked so far. I have not yet tinkered with the Fedora machine's VScode settings because I can just disable PIA and get access to the extensions marketplace. One suggestion asked if I could access https://vscode.dev/ - sure, regardless of PIA's current state.

I'd like to facilitate extension marketplace access (WITH PIA VPN active) on both machines. Suggestions?

**Comment by mattleibow** [comment]
I think this may be the wrong repository?

Maybe open here: https://github.com/microsoft/vscode

**Comment by DarkSky7** [comment]
I moved the issue there.  Deleting here.
