### ISSUE TITLE
[Bug] Impossible to enforce nullable ref warning as errors.

### ISSUE THREAD

**Issue by voroninp** [dotnet/maui#1796]
### Steps to Reproduce

1. Create new MAUI project
2. Enable nullable reference types (`<Nullable>enable</Nullable>`)
3. Treat warnings and errors for nullables. (`<WarningsAsErrors>nullable</WarningsAsErrors>`)

### Expected Behavior
I expect the generated code to support nullables.

### Actual Behavior
Cannot compile the project because of the error:
> Error CS8618 Non-nullable field 'CounterLabel' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.	MainPage.xaml.cs

The file `MainPage.xaml.sg.cs` does not contain `#nullable disable` directive; compiler sees that not nullable field is not initialized in constructor. Unfortunately it's not smart enough to find out that call to `InitializeComponent` will do the job)

**Comment by maxkoshevoi** [comment]
When generating `InitializeComponent()`  `MemberNotNullAttribute` should be added to it for each control. This would resolve the issue.
