### ISSUE TITLE
MediaPicker.CaptureVideoAsync() returns null on Android API 33 (Android 13.0)

### ISSUE THREAD

**Issue by grimmi** [dotnet/maui#17977]
### Description

When using `Microsoft.Maui.Media.MediaPicker.Default.PickVideoAsync` on Android 13, the returned `FileResult` is always `null`.

This worked on previous versions of Android.

We recently updated to the current .NET MAUI Android workload because of a similar problem in `CapturePhotoAsync` where there were missing / wrong permission checks.

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Replace the content of `MainPage.xaml.cs` with this:

```csharp
public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
    }

    private void OnCounterClicked(object sender, EventArgs e)
    {
        _ = StartVideoCapture();
    }

    private async Task StartVideoCapture()
    {
        var file = await Microsoft.Maui.Media.MediaPicker.CaptureVideoAsync();

        if(file != null)
        {
            await DisplayAlert("video", file.FullPath, "OK");
        }
        else
        {
            await DisplayAlert("video", "fail", "OK");
        }
    }
}
```

3. Edit your AndroidManifest.xml to look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round" android:supportsRtl="true"></application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="32" />
  <!-- Required only if your app needs to access images or photos that other apps created -->
  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
  <!-- Required only if your app needs to access videos that other apps created -->
  <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
  <!-- Required only if your app needs to access audio files that other apps created -->
  <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
  <queries>
    <intent>
      <action android:name="android.media.action.IMAGE_CAPTURE" />
    </intent>
  </queries>
</manifest>
```

4. Start the app.
5. Press the button.
6. Record a video and finish via tapping the stop button.

Expected: A popup showing the name of the recorded video file.

Actual: A popup showing that the `FileResult` returned from `CaptureVideoAsync` was `null`.

Note: The version I'm using (7.0.96) is not selectable in your dropdown...

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Unknown.

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No.

**Comment by grimmi** [comment]
I'm glad to see this verified and triaged - is there any info regarding a possible timeline for release? This is a pretty big blocker for us...

**Comment by SliemBeji-FBC** [comment]
We also depend on this and it blocks us from migrating from xamarin to .net maui but sadly this is not the only issue that concerns us
