### ISSUE TITLE
[regression/8.0.0-preview.3.8149] - modal to modal doesnt call OnNavigatedTo

### ISSUE THREAD

**Issue by Zack-G-I-T** [dotnet/maui#17978]
### Description

When you are on a modal page and navigate to another modal page using Shell.Current.GoToAsync, the OnNavigatedTo method is called on the first modal page - but never on the second.

### Steps to Reproduce

1. Download project
2. Add breakpoints to all OnNavigatedTo methods
3. Run app and click buttons to go to each page - see that the breakpoints never get hit.

### Link to public reproduction project repository

https://github.com/Zack-G-I-T/Net8ModalOnNavigatedTo

### Version with bug

[8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.2.7871](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.2.7871)

### Affected platforms

Android

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 3.0(8.0.0-rc.2.9373). This issue does not repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[TestModalNet8.zip](https://github.com/dotnet/maui/files/12914798/TestModalNet8.zip)
![Breakpoint](https://github.com/dotnet/maui/assets/97647558/35e2d0b1-e4f2-4629-9f07-0b4dec5ad771)

**Comment by Zack-G-I-T** [comment]
@XamlTest if you look at the class you are breaking on - it is the same one each time. "TestModalPage.xaml.cs". It never hits the "TestModalPage2.xaml.cs" OnNavigatedTo. 
Why would it hit the OnNavigatedTo method on the first page when you are going away from it?

**Comment by samhouts** [comment]
Confirmed that this regressed between [8.0.0-preview.2.7871](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.2.7871) and [8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149). https://github.com/dotnet/maui/pull/13025 seems sus. Note that in preview 2, the NavigatedTo even fires for Modal1 _every time_, but it also fires the event for the modal on top.

**Comment by XamlTest** [comment]
> @XamlTest if you look at the class you are breaking on - it is the same one each time. "TestModalPage.xaml.cs". It never hits the "TestModalPage2.xaml.cs" OnNavigatedTo. Why would it hit the OnNavigatedTo method on the first page when you are going away from it?

Yes, you are right, thanks for reminder. It never hits the "TestModalPage2.xaml.cs" OnNavigatedTo.
