### ISSUE TITLE
Enable <Nullable> in .NET MAUI project templates

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#17987]
Set `<Nullable>enable</Nullable>` in the .NET MAUI project templates (native, Blazor Hybrid, and library) to align it with C# best practices.

How to make things work in the MAUI templates: 

* The MAUI App template is already nullable-compatible, it's just not enabled
* The MAUI Blazor App template is _not_ nullable-compatible, but should be trivial to enable, because the ASP.NET Blazor Web App template it's based off of _is_ nullable-enabled
* The MAUI Library template is already nullable-compatible, it's just not enabled

As far as what the other cool kids around town are doing, every single project type I looked at is already nullable-enabled:

* Blazor Web App: Nullable-enabled
* ASP.NET Core Web App: Nullable-enabled
* Console app: Nullable-enabled
* WinForms app: Nullable-enabled (and arguably the _coolest_ kid in town)
* WPF app: Nullable-enabled
* MSTest Test Project: Nullable-enabled

So, it's probably worth doing in .NET MAUI unless someone can think of a good reason not to. For example, would the most value come only after we do a full nullable-annotation pass of .NET MAUI itself? Or is that not necessary?

**Comment by mattleibow** [comment]
@samhouts is this something we should do for GA? Then we can be like WinForms :)

**Comment by Eilon** [comment]
I'm happy to do the work (it's almost entirely Blazor-specific changes) if we want to get it done.

BUT: I don't know what risks could be associated with this in terms of user experience, cost of updating docs, and anything else already in motion for GA. No change is without risk, though the change itself should be fairly straightforward.

**Comment by mattleibow** [comment]
This is just the templates, so should be OK, right? Only File | New are affected?

**Comment by Eilon** [comment]
Yes, just the templates. I'm not _aware_ of any potential complications, but I've also never really thought about it.

**Comment by mattleibow** [comment]
I think we probably should get it for GA because a change in SR1 may be unexpected. 

If we get a PR with all the changes, we can see where we can fit it. If there are scary things, maybe we do it for net9, or if it is just a few msbuild props and magic, then maybe we can have a better feel for GA?

**Comment by mattleibow** [comment]
Done!

https://github.com/dotnet/maui/pull/18019
