### ISSUE TITLE
Border controls margin property only seems to affect right and bottom 

### ISSUE THREAD

**Issue by SteveSitekitcare** [dotnet/maui#17982]
### Description

Hey

I have a border with in a border which seems to having a problem with margins for the inner margin.
Android works correct as seen below

![image](https://github.com/dotnet/maui/assets/138577988/6c3f4da0-89bf-4db4-bca3-278b5902d34c)

But IOS does not seem to work no matter what I try as seem below

![image](https://github.com/dotnet/maui/assets/138577988/deb17c86-9d28-46ec-9343-55c8cc0646bb)
 

Code Sample here https://github.com/SteveSitekitcare/Samples/tree/border-margin-issue

I'm using Dotnet 7 on VS 17.7.4

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

no

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 3.0(8.0.0-rc.2.9373). This issue repro on iOS 16.4(**7.0.92**), not repro on iOS 16.4(**8.0.0-rc.2.9373**) with below Project:
[BorderMarginIssue.zip](https://github.com/dotnet/maui/files/12923639/BorderMarginIssue.zip)

iOS(.NET8)
![image](https://github.com/dotnet/maui/assets/97647558/3b4b19d4-dde2-4399-9232-6332cceddd85)

**Comment by SteveSitekitcare** [comment]
> Hi @SteveSitekitcare. We have added the "s/try-latest-version" label to this issue, which indicates that we'd like you to try and reproduce this issue on the latest available public version. This can happen because we think that this issue was fixed in a version that has just been released, or the information provided by you indicates that you might be working with an older version.
> 
> You can install the latest version by installing the latest Visual Studio (Preview) with the .NET MAUI workload installed. If the issue still persists, please let us know with any additional details and ideally a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md) provided through a GitHub repository.
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

I removed the latest dotnet 8 pre release and matching visual studio as it was effecting all my projects I worked on. Everything was building using dotnet 8 build tools which was causing lots of problems. I had to add global.json to every repo to get around it. Which was too much and tbh was causing future upgrade issues further into the future
