### ISSUE TITLE
Weird behavior changing scale between monitors 100% scale vs 125%

### ISSUE THREAD

**Issue by danielancines** [dotnet/maui#17988]
### Description

Using the last release of dotnet sdk 7.0.402 I'm facing a weird behavior using my main display with 100% scale and my second monitor with 125%.

Brand new Maui project, window with 500x700 on main display, 100% scale:
![image](https://github.com/dotnet/maui/assets/2250055/41d6ad78-58b2-4257-bf2e-e338c8011672)

Moved to 125% scale:
![image](https://github.com/dotnet/maui/assets/2250055/213abb46-9f54-4834-a4f2-8efc2b3a1fd3)

Moved back to my 100% scale monitor:
![image](https://github.com/dotnet/maui/assets/2250055/eda83d29-6b47-47e6-ac67-9a2af629b702)

The size remains the same, but when I increase height to 900, something weird happens:
![image](https://github.com/dotnet/maui/assets/2250055/71c2c0a3-5f97-4ce7-afb6-c187e5be5ba0)

On 125% scale monitor
![image](https://github.com/dotnet/maui/assets/2250055/f18849c0-31e8-4c14-84c3-6116a0d5c4a7)

Moving back to my 100% scale monitor
![image](https://github.com/dotnet/maui/assets/2250055/2592641d-550e-4b35-ae3f-aabe6bca342a)

I tested the same scenario using WinForms

100% scale
![image](https://github.com/dotnet/maui/assets/2250055/82dcef13-906d-4042-8f31-e8e0dc6b8d7b)

125% scale
![image](https://github.com/dotnet/maui/assets/2250055/199cece7-529e-4be8-90af-bd3eda1d8a66)

Moved back 100%:
![image](https://github.com/dotnet/maui/assets/2250055/6e34eae8-29d0-45b1-8e0c-a139cc23621e)

This behavior is messing up with my application, specially with my dotnet Maui MDI like app, using Pinvoke.SetParent method.

PS. I tested with WPF and works like WinForms, but using WinUI the problem is the same as Maui.

### Steps to Reproduce

1. Create a dotnet Maui App
2. Check the size on a monitor with 100% scale
3. Move the window to another monitor with 125% scale
4. Move back to main display with 100% scale

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by RoiChen001** [comment]
Can't t repro it on the latest 17.10.0 preview 1.

**Comment by danielancines** [comment]
Hi, testing on 7.0.406 - Visual Studio 17.10.0-Preview 1.0, I'm getting the same behavior:

100%
![image](https://github.com/dotnet/maui/assets/2250055/8c4925ff-b443-44b4-b0a8-a6ec08df821a)

125%
![image](https://github.com/dotnet/maui/assets/2250055/1a8a2d5e-be98-408e-bc27-e7d173d91790)

250%
![image](https://github.com/dotnet/maui/assets/2250055/9aa4be78-a387-41ff-93d2-04572526da1f)

Back to 100%
![image](https://github.com/dotnet/maui/assets/2250055/19d0b6aa-ca72-47b5-949a-bf1e3a6ea0d6)

I created a [Repo](https://github.com/danielancines/maui-17988) with this issue.

Steps
1. Execute this repo at 100% scale
2. Change to 250% scale
3. Back to 100% scale, the size will be massed up.

![image](https://github.com/dotnet/maui/assets/2250055/eeadfd48-aba6-4b10-a187-b1ce1c2d0b97)
![image](https://github.com/dotnet/maui/assets/2250055/eca1412d-4a62-472d-a622-fe44bdca8d81)

**Comment by RoiChen001** [comment]
I used the [Repo](https://github.com/danielancines/maui-17988) project and reproduced the problem on 17.10 Preview 1.

**Comment by danielancines** [comment]
Could you guys, reopen or give us more info about this, the problem still happens.
