### ISSUE TITLE
MAUI is not correctly drawing or updating shadows causing bizarre outcomes in numerous situations in Windows (simple repro project included)

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#17996]
### Description

If you make a RoundRectangle Border and then apply a Shadow to it, it will draw the Shadow as a square even if you have it set to draw a RoundRectangle shape.

For example, here is a simple configuration in Android rendering the shadow shape correctly:

<img width="269" alt="windows shadow mask 2" src="https://github.com/dotnet/maui/assets/43948450/b263db04-8626-4332-93a6-ba4e3d0be290">

Here is the same configuration in Windows:

<img width="415" alt="windows shadow mask 1" src="https://github.com/dotnet/maui/assets/43948450/aeae3b54-fd21-4ef9-a58b-978d19f9672c">

It is drawing an abnormal square shadow which is obviously not the intended design.

I think this is more an issue of it not drawing correctly on the update of the Border shape. Ie. It is not refreshing the Shadow. I have seen it draw Shadows properly on rounded Borders in WIndows under other circumstances.

**Severity of Issue**
There are many bizarre behaviors being exhibited by Windows shadows in MAUI. I have another situation where my entire screen is covered by a shadow from a small element at the top. It is stretching them bizarrely. Sometimes they are in the wrong place on screen. Or the wrong shape as here.

I presume this is all the same bug, where I presume it is just not updating the shadow when it ought to. So I am only providing one repro. If needed, I can provide numerous others.

Windows shadows are mostly unusable at this point.

### Steps to Reproduce

1. Create new MAUI project called "Windows Shadow Mask Bug"
2. Copy and paste the following code to replace App.xaml.cs and play project:
```
using Microsoft.Maui.Controls.Shapes;

namespace Windows_Shadow_Mask_Bug {
    public partial class App : Application {
        public App() {
            InitializeComponent();

            ContentPage mainPage = new();
            mainPage.BackgroundColor = Colors.CornflowerBlue;
            this.MainPage = mainPage;

            VerticalStackLayout vert = new();
            mainPage.Content = vert;

            Border border = new();
            border.Stroke = Colors.White;
            border.StrokeThickness = 5;
            border.Shadow = new Shadow() { Offset = new Point(0, 6), Radius = 5 };
            vert.Add(border);

            AbsoluteLayout abs = new();
            border.Content = abs;

            Image image = new();
            abs.Add(image);
            image.Source = ImageSource.FromUri(new Uri("https://www.readersdigest.ca/wp-content/uploads/2019/11/cat-10-e1573844975155.jpg"));
            image.Aspect = Aspect.AspectFill;

            //resize function
            mainPage.SizeChanged += delegate {
                if (mainPage.Width > 0) {
                    int width = (int)mainPage.Width;
                    border.WidthRequest = border.HeightRequest = width * 0.5;
                    image.WidthRequest = image.HeightRequest = width * 0.5;
                    border.StrokeShape = new RoundRectangle() { CornerRadius = width * 0.25 };
                }
            };
        }
    }
}
```

### Link to public reproduction project repository

https://github.com/jonmdev/Windows-Shadow-Mask-Bug

### Version with bug

7.0.96

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 3.0(8.0.0-rc.2.9373). This issue does not repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[Windows Shadow Mask Bug.zip](https://github.com/dotnet/maui/files/12924855/Windows.Shadow.Mask.Bug.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/e9d87976-f5f6-4951-b728-7a116d11fbcd)

**Comment by jonmdev** [comment]
Closed as made new thread with current repro code.
