### ISSUE TITLE
Can't build only one target in a multi target maui project

### ISSUE THREAD

**Issue by trampster** [dotnet/maui#17994]
### Description

I have a .net maui project with three targets as follows:

```
<TargetFrameworks>net7.0;net7.0-android;net9.0-ios</TargetFrameworks>
```
I use this from a unit test project which I run in our CI on linux (docker). Previously (in Xamarin.Forms) it was a .net standard project so this worked fine. The .net7.0 target is there for the unit tests. And this does work on windows.

On Linux we can't install the ios maui workload. But I do have the android maui workload installed.

When I try to build with:
```
dotnet build -f net7.0
```
It fails with the following message:
```
/usr/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: The project depends on the following workload packs that do not exist in any of the workloads available in this installation: Microsoft.ios.Sdk.net7 [/home/daniel/Work/hydra-src/apps/Xamarin-PTToX/src/Pttox.Core/Pttox.Core.csproj::TargetFramework=net7.0-ios]
/usr/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: You may need to build the project on another operating system or architecture, or update the .NET SDK. [/home/daniel/Work/hydra-src/apps/Xamarin-PTToX/src/Pttox.Core/Pttox.Core.csproj::TargetFramework=net7.0-ios]
```

This is unexpected because I told it to build only for .net7.0 it shouldn't need the ios workload.

### Steps to Reproduce

see description

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

no

**Comment by trampster** [comment]
We would also like to be able to do our android build from linux (docker). But this bug also prevents us from doing that.

**Comment by mattleibow** [comment]
For restore, the `-f` is missing, but you can use /p:TargetFramework=XXX

I logged an issue: https://github.com/dotnet/sdk/issues/35408

You can also condition the TFMs:

```xml
<TargetFrameworks>net8.0-android</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) or $([MSBuild]::IsOSPlatform('macOS'))">net8.0-ios;net8.0-macios</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">net8.0-windows</TargetFrameworks>
```

**Comment by trampster** [comment]
using /p:TargetFramework=XXX works for only doing the restore step.

However if I try to build afterwards it still fails:
```
daniel@WS4320:~/Work/hydra-src/apps/Xamarin-PTToX/tests/Pttox.Core.Tests$ dotnet build -f net7.0 /p:TargetFramework=net7.0
MSBuild version 17.6.8+c70978d4d for .NET
  Determining projects to restore...
/usr/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: The project depends on the following workload packs that do not exist in any of the workloads available in this installation: Microsoft.ios.Sdk.net7 [/home/daniel/Work/hydra-src/apps/Xamarin-PTToX/src/Pttox.Core/Pttox.Core.csproj::TargetFramework=net7.0-ios]
/usr/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: You may need to build the project on another operating system or architecture, or update the .NET SDK. [/home/daniel/Work/hydra-src/apps/Xamarin-PTToX/src/Pttox.Core/Pttox.Core.csproj::TargetFramework=net7.0-ios]
```

**Comment by trampster** [comment]
Doing the following does work as a work around until this issue is fixed.

```
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) or $([MSBuild]::IsOSPlatform('macOS'))">net7.0;net7.0-android;net7.0-ios;</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('linux'))">net7.0;net7.0-android;</TargetFrameworks>
```

**Comment by mattleibow** [comment]
Another thing to try is adding the `--no-restore` to the build comand - this may work.

I am going to close this issue for now as this is an issue with the SDK and also there is a workaround.
