### ISSUE TITLE
[Spec]  Drop .NET Standard 1.0 support

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#18]
# Description

Remove .NET Standard 1.0 support.

Forms currently supports .NET Standard 1.0 in order to support older Windows devices and PCL projects. .NET Standard projects have been the default for Forms for a while now, and eventually moving to newer .NET versions is going to force this transition anyway. Dropping 1.0 support allows us to simplify the builds, project loading, test matrix, and stop supporting some custom 1.0 code. 

# Backward Compatibility

Users who are still using PCL projects will need to convert them to .NET Standard projects. UWP builds targeted at 14393 and earlier will need to be updated to at least 16299 .

# Difficulty : Low

Mostly just deleting code - removing all of the NETSTANDARD1_0 #if checks and removing the .NET Stanard sections from the nuspec files.

**Comment by charlesroddie** [comment]
I think this should be in the Xamarin.Forms repo, as dropping netstandard < 2 should be done now.

> We will begin shipping .NET MAUI previews later this year, and target general availability with .NET 6 in November of 2021

So MPUI can have depend on .Net 5 in previews, and on release on .Net 6 if it brings any advantages.

**Comment by hartez** [comment]
.NET Standard 1.0 support isn't linked in any way to .NET 4, 5, or 6. 

For Forms, .NET Standard 1.0 is supported in 4.x for compatibility reasons. Removing that support would be a breaking change, so if it did happen it would have to be for a major revision, and we'd have to review the impact for folks who are currently using it.

So it's _possible_ that we will drop support for it in Forms (but that hasn't been 100% decided yet), and it's _nearly certain_ that we will drop support for it in MAUI. 

(I say _nearly certain_ because it's possible someone will post a very compelling case for 1.0 in the comments of this spec - which is why we post the spec.)
