### ISSUE TITLE
[Enhancement] Replace Maui types with .NET Standard Equivalent 

### ISSUE THREAD

**Issue by dotMorten** [dotnet/maui#180]
## Summary
Currently a Maui specific color type is introduced here. I'd prefer this got changed to use the color type already present in .NET: `System.Drawing.Color`
List of types that are duplicate:
 - `System.Maui.Color` -> `System.Drawing.Color`
 - `System.Maui.Point` -> `System.Drawing.Point`
 - `System.Maui.Size` -> `System.Drawing.Size`

There are probably more I've overlooked.
## API Changes

All places where System.Maui.Color is used, change to System.Drawing.Color.
All places where System.Maui.Point is used, change to System.Drawing.Point.
All places where System.Maui.Size is used, change to System.Drawing.Size.

## Intended Use Case
No reason to introduce even more duplicate types, but reuse types exposed by .NET already. Especially now when Maui is moving under the .NET umbrella.

**Comment by jfversluis** [comment]
Seems like a duplicate of #110

**Comment by dotMorten** [comment]
@jfleisher d'oh! Good catch. Closing this in favor of 110

**Comment by charlesroddie** [comment]
Relinking #110
