### ISSUE TITLE
Entry field does not get unfocused when you click on another element in the view. This works in Xamarin

### ISSUE THREAD

**Issue by JoacimWall** [dotnet/maui#18000]
### Description

Hi
This is simple example but we use nested templates and controls that in the end has I entry so the KeyboardExtensions.IsSoftKeyboardShowing will not easily fix this.
MAUI left side Xamarin right side

https://github.com/dotnet/maui/assets/9278908/6526e86e-d26c-4a01-a294-583ce46c2195

### Steps to Reproduce

1. add entry somewhere inside you view 
2. klick inside the entry filed and then the keyword shows. 
3. click outside  entry filed and the keyboard is not hiding. 
If you do the same in Xamarin the keyboard is hiding.  

### Link to public reproduction project repository

https://github.com/JoacimWall/Joacim_Bug_Report/tree/main/KeyboardBug/KeyboardBug

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
Try this,

https://github.com/dotnet/maui/pull/16530
