### ISSUE TITLE
maui .net7.0 DisplayAlert button hide on android 8.1 ?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#18017]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/maui-net70-DisplayAlert-button-hide-on/10473748)._

---
    
![image](https://github.com/dotnet/maui/assets/1096616/78f0bd9f-77f2-4782-8e3d-5b23a362a0ec)

```cs
private async Task SystemQuit()
  {
      var s = await App.Current.MainPage.DisplayAlert("退出", "是否退出APP？", "是", "否");
      if (!s) return;
      App.Current.Quit();
  }
```

but click button postion  Action is   true ,and hide

---
#### Feedback Bot on 9/24/2023, 06:45 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment]
I wonder if this may be an issue with the buttons not supporting a specific character? Can you try using plain ansi characters for the button. Probably not the issue, but best to know for sure.

Also, can you still tap the buttons? Are the invisible but work, or not there at all?

Are you able to attach a repro sample?
