### ISSUE TITLE
.NET MAUI Blazor survey

### ISSUE THREAD

**Issue by Kebechet** [dotnet/maui#18022]
### Description

I didnt know where else to report this.

VS showed me if I want to participate in MAUI Blazor survey. 
![image](https://github.com/dotnet/maui/assets/37485681/45056c26-9800-4886-b736-22d96deb268d)

Why not...but after I spent some time filling the form I am not able to send it. I get an error:

![image](https://github.com/dotnet/maui/assets/37485681/2ed0d535-71af-4456-b9c5-c88fdb96d2fe)

Yes, the email is valid.

In past I experienced the same problem

### Steps to Reproduce

1. fill the form
2. fill also the optional name and email
3. form wont be send

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

Yes, dont fill the "Name" field. 
Because on this field seems to be email validation. Without this it sent successfully.

**Comment by mkArtakMSFT** [comment]
@danroth27 do you know where from this survey is showing up ? Who owns it,  we should ask them to review this issue.

**Comment by BethMassi** [comment]
It's a problem with the SurveyMonkey EmailAddress validation. I removed the validation check on the optional field so it should be working now.
