### ISSUE TITLE
[regression/8.0.0-preview.1.7762] TableView row click command does not fire

### ISSUE THREAD

**Issue by gktval** [dotnet/maui#18047]
### Description

Click commands in a dynamic TableView no longer work in .Net 8.0. This is a regression from .Net 7 Maui 7.0.92. The TableView is created by adding sections to it via AttachedBehavior. This is also affecting Windows and Android. Have not tested iOS.

### Steps to Reproduce

Open the repository attached. Click on a row in the table view. This should open a dialog telling the user that the row was clicked.
In the file DynamicTable/SectionHelper.cs is where the section row is created. This is a simple text row with a click command. 

### Link to public reproduction project repository

https://github.com/gktval/MauiTableViewCommandBug

### Version with bug

[8.0.0-preview.1.7762](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.1.7762)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Windows/Android

### Did you find any workaround?

no

**Comment by samhouts** [comment]
Confirmed that this no longer works as of [8.0.0-preview.1.7762](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.1.7762), but it does work in 7.0.96. Not sure the cause, but possibly https://github.com/dotnet/maui/pull/8345?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). Repro on Windows 11, Android 14.0-API34, iOS 17.0 and MacCatalyst with below Project:
[MauiTableViewCommandBug.zip](https://github.com/dotnet/maui/files/13421312/MauiTableViewCommandBug.zip)

**Comment by gktval** [comment]
This would appear to be fixed on the latest .Net 9 preview version.
