### ISSUE TITLE
[Bug] No templates found matching: 'maui'

### ISSUE THREAD

**Issue by Stuart88** [dotnet/maui#1804]
### Description

Following the setup for MAUI preview, I get to the stage of creating a new project and it tells me there are no maui templates available.

I have no idea what I have missed, or what steps to take to ensure templates are there.

### Steps to Reproduce

1. Install VS2022 Preview 2.X and install .NET6/MAUI as per https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation#install-net-6-preview-6
2. Create new project as per https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=windows 
3. Run CLI command `dotnet new maui -n HelloMaui`

### Expected Behavior

New project created in the selected folder

### Actual Behavior

    No templates found matching: 'maui'.
    To list installed templates, run 'dotnet new --list'.
    To search for the templates on NuGet.org, run 'dotnet new maui --search'.`

Running `dotnet new --list` confirms that there are no MAUI templates.

### Basic Information

- Version with issue: Latest
- Last known good version: Latest
- IDE: CLI

### Screenshots

MAUI Check showing no issuee

![image](https://user-images.githubusercontent.com/23031872/126896464-f4062032-477e-4c3c-923a-c6f4b2afce84.png)

**Comment by Stuart88** [comment]
SOLVED

I ran `dotnet workload install` in command prompt with Admin privileges.

Discovered that little snippet here: https://github.com/dotnet/maui-samples#dotnet-workload-install-command

After running the workload, templates were installed and I could successfully create the new project.

So I guess this is a bug in the MAUI Checker??

**Comment by premingiet** [comment]
For anyone still having issues, try to run this command in elevated command prompt ```run command prompt as Administrator ```
```cmd
dotnet workload install maui
```
also run this command after that
```cmd
dotnet new -i Microsoft.Maui.Templates
```

**Comment by jsuarezruiz** [comment]
@Stuart88 Could you try `dotnet workload install maui`?

**Comment by jfversluis** [comment]
No response for a while and should be fixed in newer versions. If not, please let us know!
