### ISSUE TITLE
[regression/8.0.0] [Android] WindowSoftInputModeAdjust not working anymore

### ISSUE THREAD

**Issue by mhrastegari** [dotnet/maui#18041]
### Summary

`WindowSoftInputModeAdjust` not working anymore from `Xaml` or `MainActivity` and the soft keyboard will cover BlazorWebView's `input`!

Xaml

```
<Application ...
             xmlns:android="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;assembly=Microsoft.Maui.Controls"
             android:Application.WindowSoftInputModeAdjust="Resize">
  ...
</Application>
```

MainPage.Xaml.cs
```
        public MainPage()
        {
            InitializeComponent();

            Microsoft.Maui.Handlers.WindowHandler.Mapper.AppendToMapping(nameof(IWindow), async (handler, view) =>
            {
#if ANDROID
                var window = handler.PlatformView.Window;
                window.SetSoftInputMode(Android.Views.SoftInput.AdjustResize);
#endif
            });
        }
```

MainActivity

```
[Activity(Theme = "@style/Maui.SplashTheme", MainLauncher = true, WindowSoftInputMode = SoftInput.AdjustResize,....)]
public class MainActivity : MauiAppCompatActivity
{
}
```

### Version with bug
.NET 8 RC2
Android API 34

### Last version that worked well
Unknown

### Sample project
[AndroidSoftInputIssue.zip](https://github.com/dotnet/maui/files/12930732/AndroidSoftInputIssue.zip)

**Comment by mhrastegari** [comment]
It appears because of using `LayoutFullscreen` flag in our projects `SoftInput.AdjustResize` won't work anymore!

I'll add a sample project to the issue description ASAP!

**Comment by Mittchel** [comment]
Any update on this?

**Comment by m1ksoftware** [comment]
Any workaround for this issue? The issue is still present in 8.0.7 if LayoutNoLimits is set.

**Comment by alzubitariq** [comment]
any updates ?

**Comment by luisabreu84** [comment]
any update?
