### ISSUE TITLE
C# Hot reload not working for Android

### ISSUE THREAD

**Issue by pdurica** [dotnet/maui#18053]
### Description

Hot reload for Android end up with "Hot reload - Unable to build changes. Your changes resulted in build errors."
Microsoft Visual Studio Enterprise 2022 (64-bit) - 17.8.0 Preview 3.0
Android emulator device - Pixel 5 (API 34)

Works just fine on Windows platform (haven't tried Mac/iOS)

### Steps to Reproduce

1. Create new sample MAUI app
2. start Debug in Android
3. in MainPage.xaml.cs, I change line 14 from "count += 1;" to "count += 10;"
4. Click Save MainPage.xaml.cs
5. Click HotRelad button

### Version with bug

8.0.0-preview.1.7762

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 34

### Relevant log output

```shell
14:31 22.27 MauiApp1: Hot Reload session started
14:31 32.80 MauiApp1: Hot Reload session complete
14:33 05.47 MauiApp1: Hot Reload session started
14:33 31.80 Changes were successfully applied.
14:33 31.80 MauiApp1: Sending updates to running application
14:33 31.81 MauiApp1: Updates applied successfully
14:33 37.18 MauiApp1: Hot Reload session complete
14:38 34.74 MauiApp1: Hot Reload session started
14:38 41.33 [Error] C:\Users\Peter\source\repos\MauiSolution3\MauiApp1\Platforms\MacCatalyst\AppDelegate.cs (line 6): error CS0101: The namespace 'MauiApp1' already contains a definition for 'AppDelegate'
14:38 41.33 Invalid changes were found. Please refer to the Error List window to fix those issues.
14:38 59.42 [Error] C:\Users\Peter\source\repos\MauiSolution3\MauiApp1\Platforms\MacCatalyst\AppDelegate.cs (line 6): error CS0101: The namespace 'MauiApp1' already contains a definition for 'AppDelegate'
14:38 59.42 Invalid changes were found. Please refer to the Error List window to fix those issues.
14:39 07.08 MauiApp1: Hot Reload session complete
14:46 30.67 MauiApp1: Hot Reload session started
14:50 20.59 [Error] C:\Users\Peter\source\repos\MauiSolution3\MauiApp1\Platforms\MacCatalyst\AppDelegate.cs (line 6): error CS0101: The namespace 'MauiApp1' already contains a definition for 'AppDelegate'
14:50 20.59 Invalid changes were found. Please refer to the Error List window to fix those issues.
```

**Comment by drasticactions** [comment]
This issue is with C# Hot Reload, which is maintained by a team within Visual Studio. If you can file the issue there using the directions above, the right team and look at your issue, thanks!
