### ISSUE TITLE
.NET MAUI MacCatalyst Menu Bar items count problem

### ISSUE THREAD

**Issue by enkaradag** [dotnet/maui#18054]
### Description

For my .NET MAUI app, i need to use a menu bar for desktop environments (WinUI and MacCatalyst)

I have 80+ MenuFlyoutItem elements. That works good for windows. But for MacCatalyst it is limited to 50 items as related Microsoft Document describes. No item is shown if 50+ Menu Item (MenuBarItem, MenuFlyoutSubItem or MenuFlyoutItem total count) added to top menu

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/menu-bar

But document says;

Additional menu items, beyond the 50 limit, can be added to a menu bar by adding the following code to your AppDelegate class:

```
[Export("MenuItem50: ")]
internal void MenuItem50(UICommand uICommand)
{
    uICommand.SendClicked();
}
```
So I added that piece of code to Platforms/MacCatalyst/AppDelegate.cs like;

```
[Register("AppDelegate")]
public class AppDelegate : MauiUIApplicationDelegate
{

    [Export("MenuItem50: ")]
    internal void MenuItem50(UICommand uICommand)
    {
        uICommand.SendClicked();
    }
    protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
}
```
App builds successfully with this code, but flashes and exits at startup with no error message when it is ran

Am i missing something here?

### Steps to Reproduce

1) Create a new .NET MAUI project
2) Create a MenuBarItem and add 50 new FlyoutMenuItem in it. So totally we will have 51 items

```
MenuBarItem topitem=new MenuBarItem(){Text="TOP MENU 1"};
for (int i=0;i<50;i++)
    topitem.Add(new MenuFlyoutItem(){Text="SUB MENU "+i};
this.MenuBarItems.Add(topitem);
```
3) Run it for MacCatalyst
    

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS Ventura 13.2.1

### Did you find any workaround?

No

**Comment by rolfbjarne** [comment]
1 .There should be no space in the selector:

```cs
[Export("MenuItem50:")] // <-- Should be no space after the colon
internal void MenuItem50(UICommand uICommand)
{
    uICommand.SendClicked();
}
```

2. This code looks incomplete, the menu item should be hooked up to the selector somehow, so that when you select the menu item, the selector (and the corresponding managed method) is called.

**Comment by enkaradag** [comment]
> 1 .There should be no space in the selector:
> 
> ```cs
> [Export("MenuItem50:")] // <-- Should be no space after the colon
> internal void MenuItem50(UICommand uICommand)
> {
>     uICommand.SendClicked();
> }
> ```
> 
> 2. This code looks incomplete, the menu item should be hooked up to the selector somehow, so that when you select the menu item, the selector (and the corresponding managed method) is called.

if i remove that space after ':', it builds, runs. But behaves as if that piece of code is not added. Menu is not seen if total count exceeds 50. When i use the space char there, code builds but cannot run the app.

And yes, i think the same. this code seems to be incomplete. But it is mentioned like this (with space) in microsoft document.

**Comment by enkaradag** [comment]
> @davidbritch For the docs, is the a reference to this limit in Apples documentation? I'm searching and I can't find it.
> 
> I'm not sure what that selector in AppDelegate.cs is meant to do. Looking through GitHub, the only reference to it is our docs. Is there more context to this? @rolfbjarne Would you have any ideas?
> 
> @enkaradag I could not reproduce your issue,
> 
> https://github.com/drasticactions/MauiRepros/tree/main/MenuItemsCatalyst2
> 
> https://github.com/drasticactions/MauiRepros/tree/main/MenuItemsCatalyst
> 
> I tried with your code, and wrote my own in XAML. Both times, all items showed up fine. I actually got 10,000 items showing by running my code multiple times (although it struggled to render them all). My guess is your crash could be do to a specific item you have? I am running this on .NET 8 on Sonoma but judging by the code changes between the two it doesn't seem like it could affect it (If it actually is a limitation in the amount of items shown, that would be a macOS limitation and not a MAUI one that would be related to this codebase), but maybe try running on .NET 8 and see?
> 
> e. Okay, never mind, docs are out of date, lol.

Thank you for your reply,

Currently i am using .net7. I havent installed .net8 yet. Do you test it with the modified (with "MenuItem50:") AppDelegate class? or used it default?

In case i have some other problem, i created a new project. But still the same

**Comment by davidbritch** [comment]
https://github.com/dotnet/docs-maui/issues/1792

**Comment by drasticactions** [comment]
> > @davidbritch For the docs, is the a reference to this limit in Apples documentation? I'm searching and I can't find it.
> > I'm not sure what that selector in AppDelegate.cs is meant to do. Looking through GitHub, the only reference to it is our docs. Is there more context to this? @rolfbjarne Would you have any ideas?
> > @enkaradag I could not reproduce your issue,
> > https://github.com/drasticactions/MauiRepros/tree/main/MenuItemsCatalyst2
> > https://github.com/drasticactions/MauiRepros/tree/main/MenuItemsCatalyst
> > I tried with your code, and wrote my own in XAML. Both times, all items showed up fine. I actually got 10,000 items showing by running my code multiple times (although it struggled to render them all). My guess is your crash could be do to a specific item you have? I am running this on .NET 8 on Sonoma but judging by the code changes between the two it doesn't seem like it could affect it (If it actually is a limitation in the amount of items shown, that would be a macOS limitation and not a MAUI one that would be related to this codebase), but maybe try running on .NET 8 and see?
> > e. Okay, never mind, docs are out of date, lol.
> 
> Thank you for your reply,
> 
> Currently i am using .net7. I havent installed .net8 yet. Do you test it with the modified (with "MenuItem50:") AppDelegate class? or used it default?
> 
> In case i have some other problem, i created a new project. But still the same

I used .net 8.0 RC2. Going by @PureWeen's comments this was addressed in .NET 8, so you would need to upgrade to it. 

Looking at the .NET 7 branch, I'm not sure the "MenuItem50" selector will work correctly. The only current references to that selector, beyond that branch of MAUI, is the docs.

**Comment by davidbritch** [comment]
The 50 item Mac Catalyst limit is mentioned in the PR for MenuBar: https://github.com/dotnet/maui/pull/4839
