### ISSUE TITLE
[regression/8.0.0-preview.7.8842] Labels with max lines and linebreakmode not working even with adding handler workaround

### ISSUE THREAD

**Issue by Zack-G-I-T** [dotnet/maui#18059]
### Description

Adding a label with LineBreakMode="TailTruncation" and MaxLines="2" makes the label only show on one line. Even adding the workaround handler (which fixed this issue in Net7) does not help anymore. I have attached a sample repo showing this - the last label should show on two lines.

### Steps to Reproduce

1. Get repo and see bottom label - it should be on two lines.

### Link to public reproduction project repository

https://github.com/Zack-G-I-T/LabelBugNet8

### Version with bug

[8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.6.8686](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.6.8686)

### Affected platforms

Android

### Did you find any workaround?

Update code to use the new mapper:

```
 public static void AllowMultiLineTruncation()
 {
     static void UpdateMaxLines(Microsoft.Maui.Handlers.LabelHandler handler, ILabel label)
     {
         var textView = handler.PlatformView;
         if (label is Label controlsLabel
             && textView.Ellipsize == TextUtils.TruncateAt.End && controlsLabel.MaxLines != -1)
         {
             textView.SetMaxLines(controlsLabel.MaxLines);
         }
     };

     LabelHandler.Mapper.AppendToMapping(
        nameof(Label.LineBreakMode), (h, v) => UpdateMaxLines((LabelHandler)h, v));

     LabelHandler.Mapper.AppendToMapping(
       nameof(Label.MaxLines), (h, v) => UpdateMaxLines((LabelHandler)h, v));
 }
```

**Comment by samhouts** [comment]
Confirmed that this regressed between [8.0.0-preview.6.8686](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.6.8686) and [8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842). https://github.com/dotnet/maui/pull/13836 is the culprit. The obsolete mappers don't seem to be properly forwarding to the new mappers. The workaround is to update to use the new mappers:

```
 public static void AllowMultiLineTruncation()
 {
     static void UpdateMaxLines(Microsoft.Maui.Handlers.LabelHandler handler, ILabel label)
     {
         var textView = handler.PlatformView;
         if (label is Label controlsLabel
             && textView.Ellipsize == TextUtils.TruncateAt.End && controlsLabel.MaxLines != -1)
         {
             textView.SetMaxLines(controlsLabel.MaxLines);
         }
     };

     LabelHandler.Mapper.AppendToMapping(
        nameof(Label.LineBreakMode), (h, v) => UpdateMaxLines((LabelHandler)h, v));

     LabelHandler.Mapper.AppendToMapping(
       nameof(Label.MaxLines), (h, v) => UpdateMaxLines((LabelHandler)h, v));
 }
```
