### ISSUE TITLE
Valid CSS not parsed correctly, breaks app

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#18056]
### Description

SmartHotel360 makes use of CSS, and in RC2 I noticed it broke which prevented navigation from completing. This used to work:

```css
text-align: right;
```

And is yet still valid.

https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

Now when navigating to a page with that css, the page fails to render. The application output only says:

```
Requested value 'right' was not found.
```

That message seems very muted compared to the impact on the application, and was hard to locate. 

### Steps to Reproduce

Use that css on a page and attempt to render or navigate to that page.

### Link to public reproduction project repository

https://github.com/davidortinau/SmartHotel360-Mobile/blob/main/Source/SmartHotel.Clients/SmartHotel.Clients/Views/Styles/LoginView.css

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Did you find any workaround?

```
text-align: end;
```

**Comment by QianaJiao** [comment]
Verified this issue was not repro on Visual Studio 17.11.0 Preview 2.1 (8.0.60 & 8.0.0-rc.2.9373).
