### ISSUE TITLE
[regression/8.0.0] [WinUI] Back-button drawn only for the very first NavigationPage to be set to Detail.

### ISSUE THREAD

**Issue by Keflon** [dotnet/maui#18064]
### Description

When a `Flyout` can have its `Detail` set to different `NavigationPage` instances, 
the back-arrow will only appear if the *first* `NavigationPage` to be set has 
children pushed to it.  
If the back-arrow is present and `Detail` is set to a different `NavigationPage` 
then the back-arrow will remain, even if the new `NavigationPage` is empty.
The back-arrow, if visible and tapped, will pop a Page from the correct `NavigationPage`.  

### Steps to Reproduce

The repro project has 2 buttons in the Flyout's Flyout. Each sets the `Detail` to a different NavigationPage.  

### Example repro:
1. Pick NavigationPage B from the Flyout.
1. Push a Page.
1. Notice the back-arrow appears.
1. Pick NavigationPage A from the Flyout.
1. [BUG] Notice the back-arrow remains.

### Example repro:
1. Pick NavigationPage B from the Flyout.
1. Pick NavigationPage A from the Flyout.
1. Push a Page.
1. [BUG] Notice the back-arrow does not appear.

Swap A and B and repeat either example and the same problems occur.  

### Link to public reproduction project repository

https://github.com/Keflon/FlyoutNavBug

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.22621.0

**Comment by samhouts** [comment]
@Keflon Did this used to work in NET 7 or another version? Thanks!

**Comment by Keflon** [comment]
Hi @samhouts 
This is a regression.
I confirmed (just to be sure) by pasting the repro code into a new NET 7 project; the back arrow behaves correctly in that project.

**Comment by Redth** [comment]
This was working in `8.0.0-preview.4.8333` and not working in `8.0.0-preview.5.8529`
