### ISSUE TITLE
MAUI Blazor RC2 breaks <script src="foo.js"> type tag includes within body of .razor files

### ISSUE THREAD

**Issue by aarondcoleman** [dotnet/maui#18065]
### Description

RC2 has a breaking change that does not load as a source any `<script src="foo.js"></script>` includes. 

This previously worked in RC1 and the Preview X versions. The only way to force an include is to put it in index.html, however this isn't a workable solution as some .js files need to get loaded in the body along with the corresponding content that comes from .razor files. Many .js libraries depend on this functionality to work.

### Steps to Reproduce

1. Create File -> New .NET MAUI Blazor app.
2. Modify a .razor page and try to include and .js file, local or remote url and use that file within the page. 
3. chrome://inspect and you'll see under "Sources" that this library has not loaded. It will however if you include it in index.html.

### Link to public reproduction project repository

https://github.com/aarondcoleman/DotNetMAUIBlazor8RC2Bug/blob/main/README.md

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.1.9171

### Affected platforms

iOS, Android, Windows, macOS

### Did you find any workaround?

No

**Comment by aarondcoleman** [comment]
Sample project to test this bug: https://github.com/aarondcoleman/DotNetMAUIBlazor8RC2Bug/tree/main

**Comment by samhouts** [comment]
@Eilon fyi

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Script tags in components are not expected to work in Blazor Hybrid. If you intend to run a script, they should be included in the index.html file.

**Comment by aarondcoleman** [comment]
Thanks. For anyone who might land here, I was able to achieve what with javascript interop, like the example here: https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#dom-cleanup-tasks-during-component-disposal
