### ISSUE TITLE
clang++ exited with code 1

### ISSUE THREAD

**Issue by nchrisr** [dotnet/maui#18072]
### Description

Unable to build my iOS MAUI project, I keep getting this error when I try to run on a simulator:

```
clang++ exited with code 1:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BNCCommerceEvent", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCLinkCache", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCLinkData", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCPreferenceHelper", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCProduct", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCServerInterface", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCServerRequest", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCServerRequestQueue", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCServerResponse", referenced from:
     -u command line option
  "_OBJC_CLASS_$_Branch", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BranchActivityItemProvider", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BranchCSSearchableItemAttributeSet", referenced from:
     -u command line op	UnifiedClient.Maui	
```

And if I try to run on a device I get:

```
Assets file 'C:\devl\UC\UnifiedClient\UnifiedClient.Maui\obj\project.assets.json' doesn't have a target for 'net7.0-ios/ios-arm64'. Ensure that restore has run and that you have included 'net7.0-ios' in the TargetFrameworks for your project. You may also need to include 'ios-arm64' in your project's RuntimeIdentifiers.
```

### Steps to Reproduce

1. Create a MAUI project on a **Windows Machine** with Visual Studio
2. Install Branch-Xamarin-Linking-SDK NuGet package
3. Pair to an M1 Mac and try to run on a simulator or a device from the Windows Machine.

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.2, iOS 16.4

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
This issue would be better suited for https://github.com/xamarin/xamarin-macios (This repo is for the MAUI UI project and is unrelated to the tooling your using), but my guess would be that whatever iOS Framework you're consuming is targeting iOS devices specifically (or ARM devices generally) and is not built for the iOS Simulator. You need to make sure the framework or library you're bringing in is built for the target you're deploying to. If you have a repro project showing which library you're bringing in, that could help debug it.

**Comment by nchrisr** [comment]
> This issue would be better suited for https://github.com/xamarin/xamarin-macios (This repo is for the MAUI UI project and is unrelated to the tooling your using), but my guess would be that whatever iOS Framework you're consuming is targeting iOS devices specifically (or ARM devices generally) and is not built for the iOS Simulator. You need to make sure the framework or library you're bringing in is built for the target you're deploying to. If you have a repro project showing which library you're bringing in, that could help debug it.

I have logged this issue there as well https://github.com/xamarin/xamarin-macios/issues/19229

**Comment by nchrisr** [comment]
@drasticactions This should not have a needs-repro tag, The steps I included for this are minimal and should be very easy to follow in order to reproduce this.

**Comment by nchrisr** [comment]
> > @drasticactions This should not have a needs-repro tag, The steps I included for this are minimal and should be very easy to follow in order to reproduce this.
> 
> I did, and it worked. Looking at the nuget, it uses an XCFramework that includes the ARM and x64 libraries and iOS device / Simulators ones, so it should work. I did what you wrote and it deployed fine.
> 
> So, yes, If you can make a repro project with what you did, that would help see if it's different that what I did. Also note, I did this on a Mac, are you doing this from Windows? Are you using something like Hot Restart?

Yes I should have mentioned that I did this on a Windows machine, and paired it to an M1 mac and built from the Windows Machine.

**Comment by drasticactions** [comment]
https://github.com/xamarin/xamarin-macios/issues/19229

Discussion for this is going on here. Closing this, it's not a MAUI UI issue.

**Comment by Wandtket** [comment]
To those who might be struggling, also make sure this nuget Package IS NOT installed:

`Microsoft.Maui.Graphics.Skia`

It's causing the error for me.
