### ISSUE TITLE
[Bug] Opening shell flyout menu in WinUI3 crashes the app

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#1809]
### Description
Opening the shell flyout menu in WinUI3 crashes the app.

And throws this exception in debug mode - Exception thrown at 0x00007FFDF5524ED9 in TestApp.WinUI.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0000008C7DFC5700.

### Steps to Reproduce

1. Create a new .NET MAUI project, add a shell page and set it as a start page
2. Set WinUI as the startup project, do build, and then run the project
3. Click on the hamburger icon to open the shell flyout, which ends up throwing the above mentioned error
4. The same sequence worked fine in .NET 6 Preview 5, refer to below screenshot
<img width="710" alt="WinUI-Shell-Flyout-Issue" src="https://user-images.githubusercontent.com/81947404/126992517-600bd9f0-fa40-40e6-b254-56c18952d7f1.png">

### Expected Behavior
Shell flyout menu should open.

### Actual Behavior
Crashes the application.

### Basic Information

- Version with issue: **.NET 6 Preview 6**
- Last known good version: **.NET 6 Preview 5**
- IDE: **VS2022 17.0.0 Preview 2.1**
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
  - WinUI: Target SDK `net6.0-windows10.0.19041` running on Windows 10 21H1
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by egvijayanand** [comment]
A much better screenshot

<img width="710" alt="WinUI-Shell-Flyout-Issue" src="https://user-images.githubusercontent.com/81947404/127095493-803fe51c-22d6-400e-925c-074721e63025.png">

**Comment by PureWeen** [comment]
This should be fixed in the latest version
