### ISSUE TITLE
[regression/8.0.0] TabbedPage: Child Content overlapping Tabbed Page Menu

### ISSUE THREAD

**Issue by Jean-RochSDX** [dotnet/maui#18096]
### Description

On .NET 8 when showing a scrolling list in a TabbedPage, the child content is overlapping the Tabbed Page Menu.

NET7:
![TabbedPage_NET7](https://github.com/dotnet/maui/assets/133756283/5436a3c0-ee22-487a-b821-f56586963713)

NET8:
![TabbedPage_NET8](https://github.com/dotnet/maui/assets/133756283/5c92939d-bf9c-4bc2-a0ce-0f16e38bcd37)

### Steps to Reproduce

Download project from: https://github.com/Jean-RochSDX/TabbedPageBug
Set solution configuration to "ReleaseNET8"
Run the app and observe the bug.

You can also set the configuration to "ReleaseNET7" to compare the result with .NET7 where it is working.

### Link to public reproduction project repository

https://github.com/Jean-RochSDX/TabbedPageBug

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@Jean-RochSDX if you try toggling this setting https://learn.microsoft.com/en-us/dotnet/maui/ios/platform-specifics/page-safe-area-layout does it start to work for you?

**Comment by PureWeen** [comment]
Related https://github.com/dotnet/maui/issues/17224

**Comment by Jean-RochSDX** [comment]
> @Jean-RochSDX if you try toggling this setting https://learn.microsoft.com/en-us/dotnet/maui/ios/platform-specifics/page-safe-area-layout does it start to work for you?

Enabling or disabling the safe area is not making any difference.

**Comment by kevinxufei** [comment]
This issue was verified in Visual Studio 17.10.0 Preview 1(maui version: 8.0.6) and is not reproduced on iOS platforms.
![p1](https://github.com/dotnet/maui/assets/86938401/8991f0f2-b241-427e-a079-ce9065c31eff)
