### ISSUE TITLE
improve collectionview performance of scrolling

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#181]
When CollectionView default instance Scrolling ,it is choppy .
I found some one has been improve this control via DataTemplateSelector and Mono Nursery Size
Please see it here:
https://codetraveler.io/2020/07/12/improving-collectionview-scrolling/?utm_campaign=Weekly%2BXamarin&utm_medium=email&utm_source=Weekly_Xamarin_268
I think it is possible to improve the collectionview performance of scrolling.
Thanks.

Reference from https://github.com/xamarin/Xamarin.Forms/issues/11483

**Comment by PureWeen** [comment]
Closing for now in favor of issues that already exist on the Forms repository
