### ISSUE TITLE
[regression/8.0.0] Button background does not override implicit visualstate style

### ISSUE THREAD

**Issue by Zack-G-I-T** [dotnet/maui#18103]
### Description

If you create an implicit style with VisualStateGroups, they are no longer overriden in Net 8.
In the sample repo i created an implicit style for all buttons that sets the background to green when visualState is Normal.
I then add a button and override the background to be orange.

In Net7 the button appears orange - this is expected.
In Net8 the button stays green meaning I can no longer override the background color.

### Steps to Reproduce

1. Download repo
2. Run on both net7 and net8 and see the difference - in Net7 it is orange, but in Net8 it is green.

### Link to public reproduction project repository

https://github.com/Zack-G-I-T/ImplicitStyleIssue

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

Android

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 4.0(8.0.0-rc.2.9373). Repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[ButtonBackgroundIssue.zip](https://github.com/dotnet/maui/files/13038740/ButtonBackgroundIssue.zip)

Android(.NET 8):
![image](https://github.com/dotnet/maui/assets/97647558/b7f031c4-d916-4596-8399-98f58bfcd6b3)
Android(.NET 7):
![image](https://github.com/dotnet/maui/assets/97647558/870c8e85-e2fc-471b-91bb-ddd411527222)

**Comment by jsuarezruiz** [comment]
cc @StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
I *think* it's fixed already, checking

**Comment by StephaneDelcroix** [comment]
yep, fixed. thanks for the report

**Comment by Kaiffa** [comment]
@StephaneDelcroix when you say it's fixed you mean with the next release or? Because I still have this issue on newest VS update and net8

**Comment by Zack-G-I-T** [comment]
@StephaneDelcroix I also have tried on the newest version of nightly build and same issue occurs

**Comment by andrewstellman** [comment]
> yep, fixed. thanks for the report

Thanks so much for checking!

**Comment by gabsamples6** [comment]
@StephaneDelcroix @PureWeen   Hi both just to let you know that is one is NOT fixed 8.0.0-rc.2.9511
We use implicit styles in more than 80 xaml pages.. and its causing us issues..

I guess the .net 8 GA  boat has already shipped .. 

thanks

**Comment by drasticactions** [comment]
> yep, fixed. thanks for the report

@StephaneDelcroix As a few people noted that they said it wasn't fixed, and based on this I'm not sure if you meant that it's fixed in RC2 or fixed in Main, could you please check and make sure what versions you think it's fixed in? And if possible if you know the commit or PR that fixed it, could you post that too? It'll make it easier for me to verify.

**Comment by StephaneDelcroix** [comment]
@drasticactions I wrote a test a the time, that was passing. lemme check again

**Comment by StephaneDelcroix** [comment]
ok, I get it
this is a tough one, as in some other cases, the inverse behaviour is expected

**Comment by Zack-G-I-T** [comment]
@StephaneDelcroix  in Xamarin and till MAUI .net 7 this was standard behaviour for implicit styles to be overridden. This will break many pages in our app. Is this going to be addressed for GA?
