### ISSUE TITLE
[Windows] How to style the ScrollBar of the ScrollView

### ISSUE THREAD

**Issue by sjorsmiltenburg** [dotnet/maui#18101]
### Description

In XF I was able to adjust the colors of the scrollbar of the scrollview for my UWP project with the following code in the app.xaml in my UWP project.

```xaml
<Application.Resources>
    <ResourceDictionary>
        <Style TargetType="ScrollBar">
            <Setter Property="Background" Value="{StaticResource LightColor}" />
            <Setter Property="Foreground" Value="{StaticResource DarkColor}" />
        </Style>           
    </ResourceDictionary>
</Application.Resources>
```

It seems as if this ability is lost in MAUI as the Type ScrollBar is no longer recognized. 
I don't see properties on the ScrollView to alter the ScrollBar appearence.
Maybe the 'ScrollBar' was an UWP specific class?

I can not find documentation on how to do this.

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

no

**Comment by sjorsmiltenburg** [comment]
A new UWP (winUI) project shows support for a style with targettype ScrollBar
![image](https://github.com/dotnet/maui/assets/649207/1cdbbcd7-55b6-4a08-bc48-6ab0011939ad)

my old XF.UWP app had this style defined in the App.xaml from my XF.UWP app.
In Maui the App.xaml in the "platforms\windows" directory does not seem to support a resource propery

I also tried an OnPlatform approach when defining a style in the styles.xaml, but this does not work:
![image](https://github.com/dotnet/maui/assets/649207/d8cd4351-022c-4dd7-820b-e331311d0591)

**Comment by mattleibow** [comment]
I think that this is WinUI specific code and probably should go into the Platforms/Windows/App.xaml file instead of the shared code?

You may have to add a resource dictionary in the App.xaml:

```xaml
<maui:MauiWinUIApplication
    x:Class="MauiApp._1.WinUI.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:maui="using:Microsoft.Maui"
    xmlns:local="using:MauiApp._1.WinUI">
    <maui:MauiWinUIApplication.Resources>
        <ResourceDictionary>
            <Style TargetType="ScrollBar">
                <Setter Property="Background" Value="{StaticResource LightColor}" />
                <Setter Property="Foreground" Value="{StaticResource DarkColor}" />
            </Style>           
        </ResourceDictionary>
    </maui:MauiWinUIApplication.Resources>
</maui:MauiWinUIApplication>

```

**Comment by sjorsmiltenburg** [comment]
Thank you, this indeed works. 
At least for the background property. 
The foreground property does not work, but this does also not seem to work in a non-maui WinUI app.

I was thrown off by the warnings shown in Visual Studio IDE:
- the type 'MauiWinUIApplication' was not found. Verify that you are not missing an assembly reference and that all referenced 
assemblies have been built.
- the type 'ResourceDictionary' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.
- the type 'Color' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.
- the type 'Style' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.
- the type 'Setter' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.
