### ISSUE TITLE
CarouselView with Border flickers

### ISSUE THREAD

**Issue by criistii** [dotnet/maui#18104]
### Description

When using a Border within a CarouselView, the image flickers when scrolling the carousel.

Video Demo: https://github.com/dotnet/maui/assets/2300547/5d5faa2b-79fb-41e9-9b09-37bb5716fc0d

XML:
```xml
<Grid
        HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"
        RowDefinitions="*,50,20"
    >
        <CarouselView
            Grid.Row="1"
            ItemsSource="{Binding Items}"
            HorizontalScrollBarVisibility="Never" VerticalScrollBarVisibility="Never"
            PeekAreaInsets="100,0"
        >
            <CarouselView.ItemsLayout>
                <LinearItemsLayout Orientation="Horizontal"
                                   ItemSpacing="16" />
            </CarouselView.ItemsLayout>
            <CarouselView.ItemTemplate>
                <DataTemplate x:DataType="pages:TagViewModel">
                    <Border
                        BackgroundColor="{Binding BackgroundColor}"
                        Padding="20"
                    >
                        <Border.StrokeShape>
                            <RoundRectangle CornerRadius="8" />
                        </Border.StrokeShape>
                        <Label Text="{Binding Text}" FontSize="Large" VerticalOptions="Center" HorizontalOptions="Center" />
                    </Border>
                </DataTemplate>
            </CarouselView.ItemTemplate>
        </CarouselView>
    </Grid>
```

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

Use Frame instead.

**Comment by criistii** [comment]
I just tested it on 17.6 Preview (17.6 build 1569). I can confirm the issue is still happening. The way it looks, the flicker happens when a new cell is about to enter the screen.

**Comment by mattleibow** [comment]
Yeah, it seems that when the cell is reused, it transitions from the old cell to the new cell. Not sure why it is reusing the old cell for the cell that is already presented:

| a | b | c | 
|:-:|:-:|:-:|
| <img width="476" alt="image" src="https://github.com/dotnet/maui/assets/1096616/9e9a1d6d-4e06-4d08-9a91-54cf30fedb81"> | <img width="437" alt="image" src="https://github.com/dotnet/maui/assets/1096616/2bb9c651-226f-49d0-a216-56a456c88efa"> | <img width="446" alt="image" src="https://github.com/dotnet/maui/assets/1096616/36f1d34d-cc58-4baa-b7ae-1161f4d77012"> |

**Comment by karthikraja-arumugam** [comment]
Flickering issue is resolved with NET8. Could you please check the issue in NET8?

https://github.com/user-attachments/assets/da99df95-4cfd-449e-aed1-fe2ab4b07517


https://github.com/user-attachments/assets/aaf55cba-e0ba-4553-845e-c1753884e700
