### ISSUE TITLE
MAUI application shows the telemetry log as XAMARIN APP

### ISSUE THREAD

**Issue by MikeP0911** [dotnet/maui#18124]
### Description

Currently working on migrating the Xamarin form app to MAUI. The app gets freezed after executing to certain level. the app gets freezed before launching the first page in the app. We have changed all reference of Xamarin to MAUI. Yet the telementry log in the build output shows the Xamarin app : true.

[TelemetryLoggerImpl] {"MAM_APP_TARGET_SDK_VERSION":33,"DEVICE_SDK_PREVIEW_INT":0,"WAS_LAUNCHED":true,"IS_XAMARIN_APP":true,"DEVICE_SDK_INT":31,"DEVICE_CPU_ABIS":"arm64-v8a,armeabi-v7a,armeabi","MAM_APP_ID":"jp.co.cegb.archxtractPush","MAM_APP_MIN_SDK_VERSION":29,"MAM_APP_VERSION":"2.0.3","EVENT_CLASS":"com.microsoft.intune.mam.client.telemetry.events.AppInfoEvent","DEVICE_BRAND":"Sony"}

The only Xamarin references used are the

```
<PackageReference Include="Xamarin.Firebase.Common">
    <Version>120.3.3.1</Version>
</PackageReference>

<PackageReference Include="Xamarin.Firebase.Config">
    <Version>121.4.0.2</Version>
</PackageReference>
<PackageReference Include="Xamarin.Firebase.Iid">
    <Version>121.1.0.10</Version>
</PackageReference>
<PackageReference Include="Xamarin.GooglePlayServices.Base">
    <Version>118.2.0.2</Version>
</PackageReference>
<PackageReference Include="Xamarin.GooglePlayServices.Basement">
    <Version>118.2.0.2</Version>
</PackageReference>
<PackageReference Include="Xamarin.GooglePlayServices.Gcm">
    <Version>117.0.0.10</Version>
</PackageReference>
<PackageReference Include="Xamarin.GooglePlayServices.Tasks">
    <Version>118.0.2.3</Version>
</PackageReference>
```
Can these be used in Xamarin apps or is there any alternatives used?
The app is freezed for no reason. Could this be a reason.
Help is much appreciated

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No Work around found

### Relevant log output

```shell
[TelemetryLoggerImpl] {"MAM_APP_TARGET_SDK_VERSION":33,"DEVICE_SDK_PREVIEW_INT":0,"WAS_LAUNCHED":true,"IS_XAMARIN_APP":true,"DEVICE_SDK_INT":31,"DEVICE_CPU_ABIS":"arm64-v8a,armeabi-v7a,armeabi","MAM_APP_ID":"jp.co.cegb.archxtractPush","MAM_APP_MIN_SDK_VERSION":29,"MAM_APP_VERSION":"2.0.3","EVENT_CLASS":"com.microsoft.intune.mam.client.telemetry.events.AppInfoEvent","DEVICE_BRAND":"Sony"}
```

**Comment by mattleibow** [comment]
Looking at this, I think you are using Intune on Android and I am not sure they distinguish between maui vs xamarin because they probably just consider if this is a native Java app or a Xamarin/.NET app.

However, that is probably not related to the freezing.

If you remove/disable Intune, does it still freeze? You say the app freezes before launching the first page, can you replace the contents of the page with an empty screen or start at a different page?

Do you have a smaller repro sample that we could have a look at? If you add some additional logging to the app, can you track page loading and see where the freezing starts?

**Comment by MikeP0911** [comment]
@mattleibow 
Thank you for your reply.
Can you please provide a small sample of Maui Android application using the Microsoft.Intune.Maui.Essentials.android library. There is no document explaining about the intune integration.

We are not sure if we have implemented correctly. As of now i could not give you a sample.

**Comment by MikeP0911** [comment]
@PureWeen 

Could you please give any sample application in maui using the recent Intune SDK version.

Thanks in advance

**Comment by mattleibow** [comment]
I think that may be an issue/request for the intune team? They may have an issue with the new .NET SDKs.
