### ISSUE TITLE
[regression/8.0.0-preview.4.8333] [WinUI] Incorrect size of first item with Border in CollectionView 

### ISSUE THREAD

**Issue by sasharp** [dotnet/maui#18128]
### Description

The first item of CollectionView has another width than all elements inside of Border.
`<CollectionView.ItemTemplate>
    <DataTemplate>
        <Grid Padding="10">
            <Border>
                <VerticalStackLayout BackgroundColor="Aqua">`
![image](https://github.com/dotnet/maui/assets/7774486/ad636550-4c22-41d3-94bf-52af143239c8)

### Steps to Reproduce

Navigate to the page.

### Link to public reproduction project repository

https://github.com/sasharp/MAUI8Bugs

### Version with bug

[8.0.0-preview.4.8333](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.4.8333)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149)

### Affected platforms

Windows

### Did you find any workaround?

The width will be correct when window is resized.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 4.0(8.0.0-rc.2.9373). Repro on Windows 11 with below Project:
[MAUI8Bugs.zip](https://github.com/dotnet/maui/files/13050721/MAUI8Bugs.zip)

**Comment by samhouts** [comment]
Confirmed this regressed in [8.0.0-preview.4.8333](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.4.8333). https://github.com/dotnet/maui/pull/14532/ seems sus.

**Comment by emaf** [comment]
Fixed by https://github.com/dotnet/maui/pull/18356
