### ISSUE TITLE
[Bug] cant install required single project msix package due to 500 error

### ISSUE THREAD

**Issue by BreyerW** [dotnet/maui#1813]
### Description

I wanted to play with maui so i did `maui-check` then `dotnet workload install maui` then launched vs 2022 with no code (and - just to double check - with test project based on maui template) then tried to install msix package extension but got 500 error (internal error) instead. I did it at friday CET and is still happening.

### Steps to Reproduce

As above

### Expected Behavior

No error when installing extension

### Actual Behavior

500 error

### Basic Information

- Version with issue: net 6 latest preview
- IDE: vs 2022
- Platform Target Frameworks: windows 10
- Nuget Packages: none
- Affected Devices: laptop

**Comment by Eilon** [comment]
@BreyerW I think I saw that problem at some point too. I had better luck downloading the VSIX and then installing from the downloaded file. You can download it from the VS Marketplace:

https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17

**Comment by jfversluis** [comment]
Going to assume this was a small disruption at the time and this is better now. If this is still affecting you, please let us know, thanks!
