### ISSUE TITLE
[regression/8.0.0] TapGestureRecognizers do not work with static methods

### ISSUE THREAD

**Issue by samhouts** [dotnet/maui#18165]
@mattleibow I could not get your example to trigger the TapGestureRecognizer.  Even if it did work, I need to use a TapGestureRecognizer in a list and pass in the item being tapped and my use case did not your example.

I created a repo at https://github.com/anotherlab/MauiTapGestureRecognizersNotWorking that shows code that will work with .NET 7, but not with .NET 8

_Originally posted by @anotherlab in https://github.com/dotnet/maui/issues/17948#issuecomment-1760693699_

**Comment by samhouts** [comment]
[jsuarezruiz](https://github.com/jsuarezruiz) commented [10 hours ago](https://github.com/dotnet/maui/issues/17948#issuecomment-1770431758)
I've been reviewing the example. The NET MAUI's internal GestureManager is processing gestures correctly. The problem is that when try to invoke the command it does nothing as it is null.

There are options where this is expected, for example:
Command="{Binding EmployeeTapped}"

The BndingContext of the gesture is Employee where the command does not exist. But in other cases, where use the context of the CollectionView or similar, it should work. The command is static, is it for some particular reason? Removing static from the command, all works as expected.

image

**Comment by samhouts** [comment]
@StephaneDelcroix When we're looking up the methods on a DataContext for binding to commands, are we now excluding the static methods?

**Comment by anotherlab** [comment]
When I changed the method to be non-static it worked as expected. I thought I had been using a static method in .NET 7, but I was mistaken.

**Comment by samhouts** [comment]
Oh, phew. I didn't THINK we changed anything here, but I didn't thoroughly investigate yet. Thank you for confirming!! I'll go ahead and close this for now, but report back if there's still a bug. THANKS!
