### ISSUE TITLE
[regression/7.0.0] Label measuring seems to break the parent layout width

### ISSUE THREAD

**Issue by dirivero** [dotnet/maui#18160]
### Description

The Red Grid In layout below should Fill horizontally but in some scenarios it leaves extra space to the right as can be seen in the image below.

The Yellow Label seems to be the problem since the Red Grid's width kind of follows the Label's width affecting the rest of its children (the Label should also Fill horizontally):

```
    <Grid
        Padding="20"
        BackgroundColor="Blue">

        <Grid BackgroundColor="Red" Padding="5">
            <Label
                BackgroundColor="Yellow"
                Text="This label should always fill"
                FontSize="28"
                HorizontalOptions="Fill"
            />

            <Button Text="Fill Button" VerticalOptions="Center" />
        </Grid>
    </Grid>
```

This is how it looks in an iPhone 14 Pro Max where it can be seen that the right padding is bigger than the left one:
![Simulator Screenshot - iPhone 14 Pro Max - 2023-10-18 at 18 54 55](https://github.com/dotnet/maui/assets/7670773/ec99709d-e76e-48ce-9436-ce7b7d19c7de)

This is how it behaves when changing the label text using the hot reload:
![issue5 1](https://github.com/dotnet/maui/assets/7670773/028851f0-b039-44df-aeb0-8d2fdd152fd8)

### Steps to Reproduce

1. Open the linked project
2. Run on iPhone 14 Pro Max

Reproducing in other iOS and Android devices can be easily done by changing the label text length using the hot reload as shown in the gif above.

### Link to public reproduction project repository

https://github.com/dirivero/MauiMeasuringIssue

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

iOS, Android

### Did you find any workaround?

Adding an empty `<Rectangle  />` next to the label fixes the problem.

This behavior is also observed in .NET 7 latest.

**Comment by Santiago5050** [comment]
This also happens with the CollectionView. The label could break the CollectionView layout according to its text length.

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="IssueCollectionViewLabels.MainPage"
    Title="CollectionView Issue"
    >
    <CollectionView
        ItemsSource="{ Binding . }"
        >
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <Grid
                    BackgroundColor="White"
                    Padding="10"
                    >
                    <Grid
                        BackgroundColor="Gray"
                        >
                        <Label
                            VerticalOptions="Center"
                            BackgroundColor="Red"
                            Text="{ Binding ., StringFormat='This text length breaks the layout: {0}' }"
                            />
                    </Grid>
                </Grid>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</ContentPage>
```

![image](https://github.com/dotnet/maui/assets/18688477/a4fdf528-7d28-4b8f-a98b-4f2333f4e6c8)

**Comment by samhouts** [comment]
Good news! 8.0.0-rc.2.9511 was released today, and it contains this fix!
