### ISSUE TITLE
[regression/8.0.0] New Projects with spaces in the names are putting those spaces into ApplicationId (instead of underscores as previously) causing failure to build

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#18177]
### Description

This is minor, but I just mention it as it may be an easy fix and might otherwise frustrate people who don't figure out the cause. This wasted me some annoying time trying to figure out what the bug was at first too. Affects 8.0.0-rc.2.23479.6.

**CORRECT BEHAVIOR**
Previously you could start a new project and if your project name had spaces in it, it would replace them with underscores:
<img width="246" alt="underscores correct" src="https://github.com/dotnet/maui/assets/43948450/6ada0e60-33ba-4b50-84be-3a40c211c743">

**ABNORMAL BEHAVIOR**
Now if you start a new project in .NET 8 with spaces in the name, it keeps the spaces and the app can't build with them giving an error:

<img width="224" alt="underscores abnormal" src="https://github.com/dotnet/maui/assets/43948450/0f7622fb-5a24-45af-955d-a16138231864">

It can no longer handle underscores in App ID either, so you must replace with dashes or some other character.

I also note it is no longer assigning a GUID, though I don't know if that is significant.

### Steps to Reproduce

1. File New to make new project and name project anything with spaces, try to hit play in Windows and get error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 13, Reason: 'com.companyname.resize lag bug' violates pattern constraint of '[-.A-Za-z0-9]+'.
The attribute 'Name' with value 'com.companyname.resize lag bug' failed to parse.	Resize Lag Bug			
```

2) Replace spaces or underscores with dashes, right click Solution, rebuild, then play, and it builds.

**SOLUTION**
Ideally the app ID schema should again allow and automatically assign underscores to replace spaces.

I think the bug is that underscores are no longer part of the schema and no longer being applied to spaces automatically.

### Link to public reproduction project repository

n/a

### Version with bug

8.0.0-rc.2.23479.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

Windows

### Did you find any workaround?

Manually remove underscores and spaces for now, dashes are okay.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 4.0. This issue does not repro Windows 11(**7.0.96**), repro on Windows 11(**8.0.0-rc.2.9373**) with below Project:
[MauiApp test.zip](https://github.com/dotnet/maui/files/13067373/MauiApp.test.zip)

**Comment by samhouts** [comment]
Probably due to https://github.com/dotnet/maui/pull/13509/.
