### ISSUE TITLE
Sometimes Crash when using Maui Essentials Send Email

### ISSUE THREAD

**Issue by SprengerS** [dotnet/maui#18181]
### Description

After the migration from Xamarin Essentials to Maui Essentials we detect in AppCenter a crash when sending E-Mails. It is a `SIGABRT: net_uri_BadHostName` with the following Stacktrace

```
System.Uri.CreateThis(String , Boolean , UriKind , UriCreationOptions& )
System.Uri..ctor(String uriString, UriKind uriKind)
Foundation.NSUrl.op_Implicit(NSUrl )
Microsoft.Maui.ApplicationModel.Communication.EmailImplementation.ComposeWithUrl(EmailMessage )
Microsoft.Maui.ApplicationModel.Communication.EmailImplementation.PlatformComposeAsync(EmailMessage )
Microsoft.Maui.ApplicationModel.Communication.EmailImplementation.ComposeAsync(EmailMessage )
Hoermann.BleApp.Core.Services.Sharing.SharingService.<>c__DisplayClass9_0.<<SendEmailAsync>b__0>d.MoveNext()
MvvmCross.Base.MvxMainThreadAsyncDispatcher.<>c__DisplayClass1_0.<<ExecuteOnMainThreadAsync>b__0>d.MoveNext()
ObjCRuntime.Runtime.ThrowException(IntPtr )
UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
UIKit.UIApplication.Main(String[] , Type , Type )
Program.<Main>$(String[] args)
```

This seems to be a strange problem, because the URI ist hard coded and usually works. Here is our code snippet how we send the Mail

```c#
public virtual Task SendEmailAsync(EmailConfiguration configuration, SharingApp targetApp = SharingApp.User)
{
	var completion = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

	MainThreadDispatcher.ExecuteOnMainThreadAsync(async () =>
	{
		try
		{
			await _email.ComposeAsync((EmailMessage)configuration).ConfigureAwait(false);
			completion.SetResult();
		}
		catch (FeatureNotSupportedException ex)
		{
			_logger.LogError($"MailFeatureNotSupported: {ex.Message} . Stack: {ex.StackTrace}");
			completion.SetException(new MailClientNotFoundException());
		}
	});

	return completion.Task;
}
```

Is this a bug or a problem with our implementation. This problem is only on iOS.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by mattleibow** [comment]
There may be a problem with the encoding of emails. Are you able to log more details of what the message says when it throws?

We use this code to convert from an email object into the url:

```cs
internal static string GetMailToUri(EmailMessage message) =>
	"mailto:?" + string.Join("&", Parameters(message));

static IEnumerable<string> Parameters(EmailMessage message)
{
	if (message.To?.Count > 0)
		yield return "to=" + Recipients(message.To);

	if (message.Cc?.Count > 0)
		yield return "cc=" + Recipients(message.Cc);

	if (message.Bcc?.Count > 0)
		yield return "bcc=" + Recipients(message.Bcc);

	if (!string.IsNullOrWhiteSpace(message.Subject))
		yield return "subject=" + Uri.EscapeDataString(message.Subject);

	if (!string.IsNullOrWhiteSpace(message.Body))
		yield return "body=" + Uri.EscapeDataString(message.Body);
}

static string Recipients(IEnumerable<string> addresses) =>
	string.Join(",", addresses.Select(Uri.EscapeDataString));
```

This is using the core .NET libraries to do the actual encode of parts, but something is creating an invalid uri. If you detect the exception, can you use the code to create the url and then see if it is valid? I wonder if some special characters or non-standard things are causing the encoding to not work correctly.

**Comment by SprengerS** [comment]
How can I detect a more detailed message @mattleibow ? I can execute your code in parallel way and surround it with a try catch, but the crash is deep in .NET Libraries

**Comment by SprengerS** [comment]
I have released a new App Version with Logging the Uri. But the app seems to be working for a new build with Maui Workloads  7.0.96 and Xcode 15.

**Comment by SprengerS** [comment]
It might be the fix, thank you very much.
