### ISSUE TITLE
[Bug] Changes in view position are not dynamically reflected.

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#1818]
### Description

I'm using the Arrange method to position a label in a grid and update its position when a button is clicked. However, the position of the labels is not updated with the new position value.

When we adjust the intended size of a label while keeping its position, the label's position changes.

### Steps to Reproduce

1. Open sample
2. Open MainPage.xaml.cs file, uncomment issue occuring code. 
3. Run the sample, click button to change label position. See the position not getting changed. 
4. Uncomment issue not occuring code and run the sample. 
5. Click button to change label position. See the position changed correctly.  

### Expected Behavior

Need to change position value, without changing desired size.

### Actual Behavior

Without desired size value change, position value not update. 

### Code

```
<Grid>
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <Grid>
            <Label Text="Label" x:Name="label"/>
        </Grid>
        <StackLayout Grid.Row="1">
            <Button Margin="10" Text="Change Position" 
                    Clicked="OnPositionChangeClicked"/>
        </StackLayout>
    </Grid>
```

```
double i = 10;
		private void OnPositionChangeClicked(object sender, EventArgs e)
		{
			//Issue occuring code.
			//label.Arrange(new Microsoft.Maui.Graphics.Rectangle(i, i, 30, 30));

			//Issue not occuring code.
			//label.Arrange(new Microsoft.Maui.Graphics.Rectangle(i, i, 30 + i, 30));

			i++;
		}
```

### Sample

[MauiSample.zip](https://github.com/dotnet/maui/files/6883308/MauiSample.zip)

### Basic Information

Nuget : Microsoft.Maui : 6.0.100-preview.5.794

**Comment by hartez** [comment]
This is not what the Arrange method is for - the Arrange method is used by the layout system. It won't do what you are trying to do here.

If you need to position controls at exact coordinates, I suggest using an AbsoluteLayout; then you can set the AbsoluteLayout.LayoutBounds for a control to a Rectangle.
