### ISSUE TITLE
CommunityToolkit.Maui.Views.Popup Button Text Alignment

### ISSUE THREAD

**Issue by alaskanrogue** [dotnet/maui#18195]
### Description

If a popup appears after restoring the application from a background state, the button text is aligned to the left where the text is centered if the popup is created while the application is in a foreground state.

Foreground
![image](https://github.com/dotnet/maui/assets/14001196/92ffb443-d96f-4079-a0aa-1fc45d60417f)

Background
![image](https://github.com/dotnet/maui/assets/14001196/9aecdf30-cbb1-4d02-bd1f-980f2d03b4f9)

### Steps to Reproduce

1. Create a simple Android application which can create a popup and is designed to operate in a background state as while as foreground.
2. Trigger the popup appearance after a short period of time, i.e., 10 seconds, so that there is sufficient time to move the application to the background and activate the popup appearance after the background state is entered.

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No.

**Comment by DeepWorksStudios** [comment]
Since you reference a component it's origin is -> https://github.com/CommunityToolkit/Maui

Shouldn't you post that issue there?
