### ISSUE TITLE
Existing android SDK/adb/openJDK install not recognized

### ISSUE THREAD

**Issue by iammephisto** [dotnet/maui#1821]
### Description
On a fresh install of Android Studio + SDK + OpenJDK + ADB with a virtual phone, maui/studio 2022 p2 will not be able to detect the installation correctly (including maui-check tool) and it will re-install everything.

VS Studio will then proceed to keep pointing to the actual OpenJDK folder despite this in it's default parameters for Xamarin, and once switched to the "Default microsoft" value will allow you to run your actual virtual android phone.

### Steps to Reproduce

1. read above 
2. ..
3. ..

### Expected Behavior
The installer should detect current folders or ask you for the actual path if needed, detect your existing adb and be able to run your build on it.

### Actual Behavior
What I wrote above.

### Basic Information

- Version with issue: VS 2022 p2.1
- Last known good version: ?
- IDE: that
- Platform Target Frameworks: 
  - iOS:  
  - Android: latest (v30, os 11) 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/6174852/127142308-14d3e89c-188b-40e0-a6c5-96b4c87ca76b.png)

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
