### ISSUE TITLE
When loading json into the editor control the double quotes get replaces with invalid quotes

### ISSUE THREAD

**Issue by JoacimWall** [dotnet/maui#18220]
### Description

Hi 
the Editor control in MAUI is replacing the double quotes with invalid quotes the make the file invalid to parse as Json.
The char below  
<img width="166" alt="image" src="https://github.com/dotnet/maui/assets/9278908/02b01c5a-20ec-4a29-98fd-20cb6a299518">
is replaced with this before the word
<img width="166" alt="image" src="https://github.com/dotnet/maui/assets/9278908/fdbf7537-02c4-4fcb-97a9-b24c48a0742f">
and this after the word with quotes
<img width="167" alt="image" src="https://github.com/dotnet/maui/assets/9278908/f275da89-8911-4bfc-925a-2fe3c9de8a63">

that create a invalid json

### Steps to Reproduce

```cs
//This is binded to the MAUI Editor Control
private string editFileText;
    public string EditFileText
    {
        get { return editFileText; }
        set { SetProperty(ref editFileText, value); }
    }

//Read file in to property
private async Task ReadFile()
{
// open a valid Jason 
  using Stream fileStream = System.IO.File.OpenRead(filepath);
    using StreamReader reader = new StreamReader(fileStream,System.Text.Encoding.UTF8);
   
    var c = await reader.ReadToEndAsync();
  
   EditFileText = c;
 }
private async Task Save()
    {
        using var dlg = DialogService.GetProgress("");
        using FileStream outputStream = System.IO.File.OpenWrite(currentOpenFilePath);
        using StreamWriter streamWriter = new StreamWriter(outputStream,System.Text.Encoding.UTF8);
        await streamWriter.WriteAsync(editFileText);
       // await streamWriter.WriteAsync(text);
    }
```

### Link to public reproduction project repository

https://github.com/JoacimWall/Visual-studio-multilingual-extension/tree/main/src/MultilingualClient

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Did you find any workaround?

If I skip binding the EditFileText to the editor control and just load the json into the string and then save the string the quotes is not replaced.

**Comment by JoacimWall** [comment]
> Hi @JoacimWall. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

Done

**Comment by mattleibow** [comment]
This is pretty insane, but the OS is deciding that you want these nice quotes. https://stackoverflow.com/questions/44932863/ios-11-disable-smart-quotes

I tried setting this and it helps with keyboard-entered text, but this is more insane:

> I would also add that it only prevents the smart quote from being entered from the keyboard. However, the user can type a smart quote from another app and copy/paste it into your smartQuotesType = .no text field. 

The OS can just bypass your attempts!

**Comment by mattleibow** [comment]
I can reproduce this in Xcode whith this code:

```swift

class ViewController: UIViewController {

    var extractedExpr: UITextView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        extractedExpr = UITextView(frame: CGRect(x: 0, y: 0, width: 800, height: 200))
        extractedExpr.smartQuotesType = UITextSmartQuotesType.no
        
        let btn = UIButton(type: UIButton.ButtonType.system)
        btn.frame = CGRect(x: 0, y: 210, width: 800, height: 40)
        btn.setTitle("Go!", for: UIControl.State.normal)
        btn.addTarget(self, action: #selector(buttonAction(_:)), for: .touchUpInside)
        
        self.view.addSubview(extractedExpr);
        self.view.addSubview(btn);
        
    }
    
    @objc func buttonAction(_ sender:UIButton!) {
       print("Button tapped")
        
        extractedExpr.replace(extractedExpr.textRange(from: extractedExpr.beginningOfDocument, to: extractedExpr.endOfDocument)!, withText: "")
        
        extractedExpr.replace(extractedExpr.textRange(from: extractedExpr.beginningOfDocument, to: extractedExpr.endOfDocument)!, withText: "Hello \"Matthew\"!")
    }
}
```

1. Launch the app
2. Press the button and notice the fancy quotes
3. Focus the editor
4. Press the button and notice the boring quotes

Seems this `smartQuotesType` property only kicks in after the first focus...

**Comment by mattleibow** [comment]
OK, so I have a workaround. I am sure this smart quotes not working until you focus the editor is an OS bug since it happens in Xcode. Or maybe it is by design.

But, with that knowledge, I have a workaround. To fix the cases where typing in the editor autoformats the text, you can add this to your MauiProgram.cs:

```cs
.ConfigureMauiHandlers(_ =>
{
#if MACCATALYST
    Microsoft.Maui.Handlers.EditorHandler.Mapper.AppendToMapping("Smart", (h, v) =>
    {
        h.PlatformView.SmartQuotesType = UIKit.UITextSmartQuotesType.No;
        h.PlatformView.SmartDashesType = UIKit.UITextSmartDashesType.No;
        h.PlatformView.SmartInsertDeleteType = UIKit.UITextSmartInsertDeleteType.No;
    });
#endif
})
```

And then to fix the case of needing a focus, I did this in the code behind of MainPage.xaml.cs:

```cs
public MainPage(MainViewModel vm)
{
    // ...
    Loaded += MainPage_Loaded;
}

private void MainPage_Loaded(object sender, EventArgs e)
{
    fileEditor.Focus();
    fileEditor.Unfocus();
}
```

**Comment by JoacimWall** [comment]
Hi 
Thanks the workaround solves the problem.

//Joacim
