### ISSUE TITLE
Accessing string resource throws a false FileNotFoundException in Android

### ISSUE THREAD

**Issue by FrankVDL2471** [dotnet/maui#18225]
### Description

The issue is descibed entirely in #7443 but this one is closed.
However I still have the same issue.

### Steps to Reproduce

See #7443 

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13 API 33

### Did you find any workaround?

no

### Relevant log output

```shell
[monodroid-assembly] open_from_bundles: failed to load assembly en-US/Crew.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en-US/Crew.resources.dll
**System.IO.FileNotFoundException:** ''

**System.Resources.MissingManifestResourceException:** 'Could not find the resource "Yamas.Resources.AppResources.resources" among the resources "Yamas.App.xaml", "Yamas.AppShell.xaml", "Yamas.Controls.CtrlProduct.xaml", "Yamas.Controls.CtrlTransaction.xaml", "Yamas.Pages.Charger.ViewShop.xaml", "Yamas.Pages.Collector.ViewEcoTokens.xaml", "Yamas.Pages.Collector.ViewLastTransaction.xaml", "Yamas.Pages.Collector.ViewOrder.xaml", "Yamas.Pages.Collector.ViewScanner.xaml", "Yamas.Pages.Collector.ViewTicket.xaml", ... embedded in the assembly "Crew", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.'
```

**Comment by migueBarrera** [comment]
I have the same issue with a project now created with net8 RC 2.

**Comment by PureWeen** [comment]
@jonathanpeppers  thoughts?

**Comment by jonathanpeppers** [comment]
@FrankVDL2471 can you share the full stack trace of the `FileNotFoundException` and/or `MissingManifestResourceException`? The mentioned issue, I only see a snippet like:

```
Inner Exception:
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(Assembly assembly, CultureInfo culture, Version version, Boolean throwOnFileNotFound)
```

This likely needs to move to dotnet/runtime, but we need to see what class (likely BCL) is throwing the exception.
