### ISSUE TITLE
Mixed Content Issue in WebView WinForms: Blocked Request to Insecure Resource

### ISSUE THREAD

**Issue by anan1213095357** [dotnet/maui#18229]
### Description

I am developing a WinForms application and utilizing the WebView control to display web content. My page is loaded over HTTPS at 'https://0.0.0.0/', however, it requests an insecure resource at 'http://stor.hellc.cc:3000/api/uiinterface/drawing?name=S01&page=Page1'. This request has been blocked due to mixed content restrictions, as the content must be served over HTTPS.

### Steps to Reproduce

Create a WinForms project.
Implement WebView to display web content.
Load a page over HTTPS.
Attempt to request an insecure resource over HTTP.

### Link to public reproduction project repository

no

### Version with bug

7.0.96

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.49

### Affected platforms

Windows

### Affected platform versions

win11

### Did you find any workaround?

no

### Relevant log output

```shell
The page at 'https://0.0.0.0/' was loaded over HTTPS, but requested an insecure resource 'http://stor.hellc.cc:3000/api/uiinterface/drawing?name=S01&page=Page1'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by anan1213095357** [comment]
I use src/BlazorWebView/samples/BlazorWinFormsApp
This project, and then import in the blazer to execute JS, passing in an address for the request

`
export async function loadDrawings(address, programme, page) {
    try {

        if (programme == "" || page == "") {
            return;
        }
        let response = await fetch(`${address}/api/uiinterface/drawing?name=${programme}&page=${page}`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
            }
        });


        if (!response.ok) {
            throw new Error('Network response was not ok ' + response.statusText);
        }

        // 解析响应为 JavaScript 对象
        const config = await response.json();

        if (config && config.content != undefined) {
            drawingHistory = JSON.parse(config.content);
            redrawCanvas();
        } else {
            drawingHistory = []
            redrawCanvas();
        }

        console.log('Drawing config loaded successfully.');
    } catch (error) {
        console.log('Error loading drawing config:', error);
    }
}`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The behavior you're observing here is by design. WebView will not allow to request resources over HTTP when the app is loaded over HTTPS by default.
We had a lengthy discussion on this topic in https://github.com/dotnet/maui/issues/10141 so you may find some guidance for how to work around your specific case.
