### ISSUE TITLE
[regression/8.0.0] Software keyboard hides entry box

### ISSUE THREAD

**Issue by NarcohmInomata** [dotnet/maui#18236]
### Description

https://github.com/dotnet/maui/assets/22878959/7abb3c74-82b7-40ed-a5cb-f4e3692369b7

`<Grid RowDefinitions="60, *, 60">
        <Frame BackgroundColor="Blue" Grid.Row="0" />
        <Frame BackgroundColor="Red" VerticalOptions="Fill" Grid.Row="1" />
        <Entry Grid.Row="2" VerticalOptions="End" HorizontalOptions="Fill" Text="aaaaaaa" />
    </Grid>`    

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jsuarezruiz** [comment]
cc @tj-devel709

**Comment by Redth** [comment]
So far I'm unable to see this working properly on any .NET 8 preview of MAUI.

I also tried iOS 15.5 simulator to see if it was potentially something related to iOS17.

**Comment by NarcohmInomata** [comment]
I tested on IOS16.6, VS2022 17.8 preview 4 and found this bug.

**Comment by tj-devel709** [comment]
Related to: https://github.com/dotnet/maui/issues/18354
