### ISSUE TITLE
MAUI Templates not found after install

### ISSUE THREAD

**Issue by dnorambu** [dotnet/maui#18232]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Using Visual Studio Community 2022 17.6.5
Well, for some reason after installing the MAUI component, the project templates are not listed, so you have to install them manually. I used this [SO post](https://stackoverflow.com/questions/70507822/cant-find-net-maui-in-the-list-of-vs) and worked.

**Comment by jsuarezruiz** [comment]
Workaround: `dotnet new --install Microsoft.Maui.Templates`
