### ISSUE TITLE
[Mac][.NET7] There is no dotnet bot image in the title bar of the G8 page

### ISSUE THREAD

**Issue by Chloelong123** [dotnet/maui#18239]
### Description

There is no dotnet bot image in the title bar of the G8 page

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to iOS simulator or maccatalyst.
2.Click or tap on test ‘G8’.

Actual result: There is no dotnet bot image in the title bar
![image](https://github.com/dotnet/maui/assets/109071485/dc97eaf7-32c7-4986-9369-106cdf7a5c19)

Expected results: 
![image](https://github.com/dotnet/maui/assets/109071485/24b426c3-56e2-4dca-b468-5abba18fdb75)

### Link to public reproduction project repository

ManualMauiTests - Repos (visualstudio.com) 

### Version with bug

7.0.97

### Is this a regression from previous behavior?

Not a regression

### Affected platforms

iOS, macOS

### Affected platform versions

net ios 16.4.7120, net maccatalyst 16.4.7120

**Comment by jaosnz-rep** [comment]
Verified on VS for Mac 17.6.10.428, the issue can repro on .NET 7 iOS and macOS platform.

**Comment by jfversluis** [comment]
Looks like this is .NET 7 specific which is out of support as of today so lets now worry about this any more for .NET 7.
