### ISSUE TITLE
[MAUI] Place the cursor in the middle of the editor and the cursor will always move to the end for D10 page

### ISSUE THREAD

**Issue by Ying-6** [dotnet/maui#18241]
### Description

Place the cursor in the middle of the editor below and the cursor will always move to the end for D10 page on iOS simulator.

### Steps to Reproduce

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to iOS simulator.
2. Navigate to 'D Editer' -> 'D10' and click the editor below to place the cursor whitin the middle of the string "testing".

Actual result:
The cursor always automatically moves to the end of editor "testing".
![repro1](https://github.com/dotnet/maui/assets/126375062/3ec5b842-5ea8-4b26-a3e0-d0395ae2eec6)

Expected results:
The cursor moves to the middle of the editor and the "+"/"-" button control updates to the index of the cursor position.

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

7.0.97

### Is this a regression from previous behavior?

Not a regression

### Affected platforms

iOS

### Affected platform versions

net ios 16.4.7120, net maccatalyst 16.4.7120

**Comment by mattleibow** [comment]
@rachelkang  @tj-devel709  Does this sound familiar?

**Comment by rachelkang** [comment]
Nope. This definitely looks like a bug to me, unless it's a simulator issue

**Comment by Ying-6** [comment]
This bug is also repro on .NET8 iOS, the .Maui.Controls version is 8.0.0-nightly.9613+sha.8bc2a2fc1f-azdo.8679878.

**Comment by RoiChen001** [comment]
I can repro this issue on the latest 17.10 preview 1.

**Comment by Redth** [comment]
I think this is functioning as expected at this point.

MAUI Testing here:

https://github.com/dotnet/maui/assets/271950/0e22d98b-8da8-4edb-9390-f9548ff14b6d

With a plain iOS app hosting a UITextField, I see similar behaviour:

https://github.com/dotnet/maui/assets/271950/0c192b81-c76d-4d56-9ad6-ef9a03564a8c
