### ISSUE TITLE
Button ImageSource not Scaling as expected.

### ISSUE THREAD

**Issue by mla03** [dotnet/maui#18242]
### Description

Using a Button and adding a ImageSource, svg, the image is not scaled as expected. 
According to Documentation: While **Button** defines an **ImageSource** property, that allows you to display a image on the **Button**, this property is intended to be used when displaying a small icon next to the **Button** text.

On the screenshots below the first component is a Button with ImageSource, and the Second is a HorizontalStackLayout with ImageButton and Label, set up with same HeightRequest. 

iOS:
![image](https://github.com/dotnet/maui/assets/146819747/fdae5b23-6840-4cdf-8686-2d6341668172)

Android:
![image](https://github.com/dotnet/maui/assets/146819747/35840744-a6af-42c3-bfef-260ec1d34b24)

And since I am using it in a popup dialog from CommunityToolkit i'm unable to use method 2, since GestureRecognizers are not working. 

xaml to reproduce:
![image](https://github.com/dotnet/maui/assets/146819747/efded2bc-e1b7-493e-94d2-51a3d5fb5dae)

### Steps to Reproduce

1. Remove content of VerticalStackLayout in Maui sample app.
2. Add screenshot of xaml as content. (could not get 'code' to work)
            

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 5.0(**8.0.0-rc.2.9373**). Repro on Android 14.0-API34 and iOS 16.4, also repro on Windows 11 with below Project:
[18242.zip](https://github.com/dotnet/maui/files/13162189/18242.zip)
Windows(.NET 8):
![image](https://github.com/dotnet/maui/assets/97647558/ddbd8d4e-1f40-429a-bf87-a040393aeaab)

In addition, the issue does not repro on Windows(**7.0.96**), but repro on Android 14.0-API34 and iOS 16.4 platform.
Windows(.NET 7):
![image](https://github.com/dotnet/maui/assets/97647558/3d1364d2-f9c8-4d59-90a3-74b45a236928)

**Comment by lothrop** [comment]
The Windows behavior is blocking our upgrade to .NET 8.
