### ISSUE TITLE
.NET 8: Mac Cat app with WebView not inspectable in Safari Dev Tools

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#18243]
### Description

A .NET 8 Blazor Hybrid app running on Mac Cat is inspectable in Safari Dev tools:

![image](https://github.com/dotnet/maui/assets/8092460/80b401c0-8128-400e-86a6-29f801ec8f0c)

This is because there are PRs (https://github.com/dotnet/maui/pull/14610 and https://github.com/dotnet/maui/pull/16631) to re-enable this functionality for `BlazorWebView` in .NET 8.

However, a .NET 8 MAUI app containing a `WebView`, running on Mac Cat isn't inspectable in Safari Dev tools:

![image](https://github.com/dotnet/maui/assets/8092460/305a47a0-1957-4eac-8780-14cb215465d7)

In both apps, the required entitlement is present courtesy of the project templates.

It looks like the same inspectable fix for `BlazorWebView` needs inserting into `WebView`.

### Steps to Reproduce

1. Create a new MAUI app using .NET 8.
2. Build/run on Mac Cat.
3. Try and inspect the app using Safari Dev Tools. There's no entry for the app.

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

macOS

**Comment by drasticactions** [comment]
```csharp
       #if MACCATALYST
       Microsoft.Maui.Handlers.WebViewHandler.Mapper.AppendToMapping("Inspect", (handler, view) =>
	       {
		       if (OperatingSystem.IsMacCatalystVersionAtLeast(16, 4))
		       {
			       handler.PlatformView.Inspectable = true;
			       // For older versions .NET Mac Versions that don't include the Inspectable field.
			       // handler.PlatformView.SetValueForKey(Foundation.NSObject.FromObject(true), new Foundation.NSString("inspectable"));
		       }
       });
       #endif
```

You can set it on the webview directly, then it will appear.

https://github.com/drasticactions/MauiRepros/blob/main/MauiWebviewInspect/MauiProgram.cs#L10

<img width="655" alt="スクリーンショット 2023-10-23 20 42 23" src="https://github.com/dotnet/maui/assets/898335/365fad9e-c162-4284-a8bd-f838104b6217">

**Comment by Eilon** [comment]
> @Eilon Do you have any thoughts on this?

Nothing to add. We could probably do some improvements in general to WebView in the future, perhaps along the lines of what the HybridWebView experiment would add.

**Comment by drasticactions** [comment]
@kevinxufei What are you testing? If it's BlazorWebView, that was fixed with https://github.com/dotnet/maui/pull/19909, which was inserted in 8.0.7, so anything newer then that should work fine.

If it's WebView or HybridWebView, those are different and should be turned into a new issue, it's unrelated.

**Comment by drasticactions** [comment]
Closing due to https://github.com/dotnet/maui/pull/19909

If this is a issue with the newest net8.0 or 9.0 versions, make a new issue.
