### ISSUE TITLE
.NET 8: Not sure that the com.apple.security.get-task-allow entitlement in templates for MacCat is required

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#18259]
### Description

I've been playing around with inspecting `BlazorWebView` and `WebView` in Safari dev tools on MacCat, in .NET 8. Here's what I found:

- In .NET 8, a `BlazorWebView` is inspectable by default due to code added to the framework (see https://github.com/dotnet/maui/pull/14610 and https://github.com/dotnet/maui/pull/16631). It doesn't require the com.apple.security.get-task-allow entitlement.
- In .NET 8, a `WebView` is inspectable by adding the following code to your app. It doesn't require the com.apple.security.get-task-allow entitlement.

```csharp
                                Microsoft.Maui.Handlers.WebViewHandler.Mapper.AppendToMapping("Inspect", (handler, view) =>
                                {
                                                if (OperatingSystem.IsMacCatalystVersionAtLeast(16, 4))
                                                                handler.PlatformView.Inspectable = true;
                                });
```

Bearing that in mind, do we need https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/Platforms/MacCatalyst/Entitlements.Debug.plist in the template (and it's Blazor equivalent template), if it's only being added for inspecting WebView in Safari dev tools (which the comment in the file implies)?

Vaguely related to https://github.com/dotnet/maui/issues/18243

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by dustin-wojciechowski** [comment]
Hey David, so there have been a couple very recent changes to the NET8 templates, the Debug and Release entitlement files were consolidated into one, with that entitlement commented out in the maui-mobile templates and enabled for maui-blazor templates. 

That being said, it would be great if we could remove the entitlement altogether for NET8, let me pull this down and take a look at it.
