### ISSUE TITLE
CollectionView is rendered too tall

### ISSUE THREAD

**Issue by NPadrutt** [dotnet/maui#18269]
### Description

On iOS the collection view is rendered to tall so that it runs under the tabs of the App Shell. As far as I can tell as of now it works correctly on Android.
According to https://github.com/dotnet/maui/issues/9135 I expected the issue to be resolved, but I can reproduce it on the current .net 8 RC2 and as far as I can tell with 7.0.92 as well.

### Steps to Reproduce

1. Create new maui project from the .net 8 templates. 
2. Add bottom tab bar and a collection view
3. run the example and see that the last items are under the tab bar

### Link to public reproduction project repository

https://1drv.ms/u/s!Ang3D30bKDOhsOcIEuwd6tsWWReSkQ?e=pnvpOU

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by Redth** [comment]
Looks like this might be the same issue as #18269 ?

**Comment by NPadrutt** [comment]
@Redth Did you by accident paste the wrong issue number or am I overlooking something? Since 18269 is this issue here ^^

**Comment by Redth** [comment]
Whoops, yes, pasted the wrong number, I meant: #17581

**Comment by NPadrutt** [comment]
yes this sounds like the same issue.

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/17581
