### ISSUE TITLE
Can't run unit tests with MAUI and net7.0-windows10.0.19041.0

### ISSUE THREAD

**Issue by jsiemensLatitudegeo** [dotnet/maui#18268]
### Description

If I set the TargetFramework to: net7.0-windows10.0.19041.0, and UseMaui: true, then I get an error when running tests:

```
Architecture: x64
Framework: 'Microsoft.Maui.Core', version '**FromWorkload**' (x64)
.NET location: C:\Program Files\dotnet\
No frameworks were found.
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.Maui.Core&framework_version=**FromWorkload**&arch=x64&rid=win10-x64
```

Here is the csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseMaui>true</UseMaui>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
    <PackageReference Include="coverlet.collector" Version="3.2.0" />
  </ItemGroup>

</Project>

```

Tutorials I've come across on the internet suggest to set the TargetFramework to "net7.0" but I cannot do this due to a library dependency.

### Steps to Reproduce

1. Add new "MSTest Test Project"
2. Edit csproj and set
```
  <TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
  <UseMaui>true</UseMaui>
```
3. Run a test

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by VladislavAntonyuk** [comment]
You need to change your MAUI project and add net7.0 to the target framework. See https://youtu.be/C9vIDLQwc7M?si=ar-jnZIwQhFUj8-4

**Comment by jsiemensLatitudegeo** [comment]
> Hi @jsiemensLatitudegeo. We have added the "s/try-latest-version" label to this issue, which indicates that we'd like you to try and reproduce this issue on the latest available public version. This can happen because we think that this issue was fixed in a version that has just been released, or the information provided by you indicates that you might be working with an older version.

So I tried the latest version (.net8), and it did run so I got further than before. As long as I don't try to use Maui, everything works, but when I try to use a Maui control, I get an exception:

```
        [TestMethod]
        public void TestMethod1()
        {
            var label = new Label() { Text = "abc" };
            Assert.AreEqual("abc", label.Text);
        }
```

```
Test method TestProject2.UnitTest1.TestMethod1 threw exception: 
System.TypeInitializationException: The type initializer for 'Microsoft.Maui.Controls.VisualElement' threw an exception. ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception. ---> System.Runtime.InteropServices.COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
```

**Comment by jsiemensLatitudegeo** [comment]
> You need to change your MAUI project and add net7.0 to the target framework. See https://youtu.be/C9vIDLQwc7M?si=ar-jnZIwQhFUj8-4

I can't use TargetFramework=net7.0 because I have a package dependency that doesn't support that framework.

**Comment by jsiemensLatitudegeo** [comment]
Looking at the maui source, it seems like there are a number of internal utilities to support this: TestUtils.DeviceTests, TestUtils.DeviceTests.Runners, and more infrastructure in Controls.DeviceTests. But none of this is public, so how can 3rd party developers expect to test their apps without replicating all of the internal work inside the maui project?
