### ISSUE TITLE
[iOS, Mac] The editor placeholder can't able to changed, It's default placed at center

### ISSUE THREAD

**Issue by alexharsonjamesh** [dotnet/maui#18282]
### Description

The editor placeholder position can't able to change, It's default placed at center.
It's occurs in the .NET 8.0 version.
And I attach the sample.

Mac:
<img width="277" alt="Screenshot 2023-10-24 at 1 41 10 PM" src="https://github.com/dotnet/maui/assets/125554443/4ed75e71-86f5-4449-8219-a29b412f61e0">

iOS:
![Simulator Screenshot - iPhone 14 Pro Max - 2023-10-24 at 13 53 19](https://github.com/dotnet/maui/assets/125554443/0baa84ea-854d-4de7-ba1b-048284970a06)

[EditorSample.zip](https://github.com/dotnet/maui/files/13112260/EditorSample.zip)

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.4 (simulator)

### Did you find any workaround?

No

### Relevant log output

```shell
NA
```

**Comment by tschbc** [comment]
I'm also experiencing this in iOS. Previously on 7.0.86, the placeholder correctly displayed at the vertical and horizontal Start. After upgrading to MAUI 8 RC1 / RC2 the placeholder is now vertically centered.

**Comment by mattleibow** [comment]
Are you setting the `HorizontalTextAlignment` and `VerticalTextAlignment`?

**Comment by tschbc** [comment]
> Are you setting the `HorizontalTextAlignment` and `VerticalTextAlignment`?

Negative.

My XAML for the Editor:

```xaml
<AbsoluteLayout VerticalOptions="FillAndExpand">
    <Editor
        x:Name="..."
        AbsoluteLayout.LayoutFlags="All"
        AbsoluteLayout.LayoutBounds="0,0,1,1"
        Text="..."
        TextColor="..."
        FontFamily="..."
        FontSize="17"
        Placeholder="placeholder here"
        TextChanged="..."
        Keyboard="Text">

        <Editor.Behaviors>
            <toolkit:UserStoppedTypingBehavior 
                Command="..."
                StoppedTypingTimeThreshold="700" />
        </Editor.Behaviors>
    </Editor>

    <...>
</AbsoluteLayout>
```

**Comment by maonaoda** [comment]
@mattleibow 
Thats because _placeholderLabel in MauiTextView will be set as MauiLabel that VerticalAlignment is Center default;

It will be fixed?

MauiTextView :
```
	public class MauiTextView : UITextView, IUIViewLifeCycleEvents
	{
		[UnconditionalSuppressMessage("Memory", "MA0002", Justification = "Proven safe in test: MemoryTests.HandlerDoesNotLeak")]
		readonly UILabel _placeholderLabel;
		nfloat? _defaultPlaceholderSize;
```
MauiLabel :
```
	public class MauiLabel : UILabel, IUIViewLifeCycleEvents
	{
		UIControlContentVerticalAlignment _verticalAlignment = UIControlContentVerticalAlignment.Center;

```

my workaround:
```
protected override Microsoft.Maui.Platform.MauiTextView CreatePlatformView()
{
            // TODO: use reflection to change the default VerticalAlignment to Top and wait maui fix.
            var placeholderLalble = (MauiLabel?)platformView.Subviews.FirstOrDefault(x => x is UILabel);
            if (placeholderLalble != null)
                InternalAccessHelper.SetInternalProperty(placeholderLalble, "VerticalAlignment", UIControlContentVerticalAlignment.Top);
}
```

**Comment by Redth** [comment]
I think the change here probably happened as part of #15883

@drasticactions is right in that this is the default positioning for it, however I do think the change in behaviour is unexpected here from .NET 7.

Also, Android (didn't test windows) places the vertical alignment of the placeholder text the same as the text input value itself, and follows the `VerticalTextAlignment` value for both.

So I think the 'fix' here is to make the placeholder label vertically (and we should check horizontal too) align the same as the text itself, which is following the MAUI text alignment properties. 

Long term if there's a desire for these alignments to be different for the placeholder and text value, we would want to expose a new set of properties for the placeholder specific alignment.  For now let's just make it consistent across platforms and consistent with previous functionality and expectations.
