### ISSUE TITLE
CATextLayer text is blurry on Catalyst and iOS

### ISSUE THREAD

**Issue by torfluor** [dotnet/maui#18285]
### Description

When creating a custom control using handlers, I noticed that texts using CATextLayer looks blurry. 
I have created a test application that shows the difference between CATextLayer, UILabel, and MAUI standard texts. Here is a screenshot of the test app:

<img width="471" alt="Screenshot 2023-10-24 at 13 34 07" src="https://github.com/dotnet/maui/assets/38349756/fe6ef33a-14d5-4d20-91b9-13f92ce40aa8">

### Steps to Reproduce

1. Create a new MAUI application
2. Create a custom control using handlers
3. Add a CATextLayer to the custom control on iOS or Catalyst
4. Run the application

Expected result:
The text in the CATextLayer should look just as good as other labels

Actual result:
The text in the CATextLayer looks unsharp and blurry

### Link to public reproduction project repository

https://github.com/torfluor/maui-blurry-ios-fonts

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

Mac Ventura 13.3 and iPadOS 16.6

### Did you find any workaround?

I have not found a workaround for this

**Comment by drasticactions** [comment]
I believe the issue you're hitting would happen regardless of if you use the MAUI UI framework. If you made a CATextLayer using the code you posted above in an iOS or Catalyst app directly, it would still be blurry. I think that has to do with how that control works in general, not something MAUI itself is influencing. I wrote a sample to show it.

<img width="724" alt="スクリーンショット 2023-10-24 23 02 12" src="https://github.com/dotnet/maui/assets/898335/7b5aab31-7955-47dc-8eeb-08cf6d128c41">

https://github.com/drasticactions/MauiRepros/tree/main/UIKitTextBlurTest/UIKitTextBlurTestMac

Try setting the `ContentsScale` on the `CATextLayer` to a higher value.

**Comment by torfluor** [comment]
Thank you for you quick response @drasticactions! You are of cause totally correct. 
This is not a MAUI issue since setting the ContentsScale solves the issue:
`textLayer.ContentsScale = UIScreen.MainScreen.Scale`

Sorry for the newbie question!
