### ISSUE TITLE
Assigning "{x:Type ImageButton}" instead of "ImageButton" to the TargetType property of a Trigger in an ImageButton style breaks build

### ISSUE THREAD

**Issue by MauiUIui** [dotnet/maui#18324]
### Description

Almost all in the title. So an `ImageButton` doesn't allow `{x:Type ImageButton}` to be assigned as a value to the `TargetType` property in a Trigger of its style. Doing so yields the famous "Object reference not set to an instance of an object." error which prevents the build from completing. It doesn't matter where the trigger is defined (Default Style in Styles.xaml, in the control itself, in the resources of a containing element...)

### Steps to Reproduce

1. Create a MAUI app.
2. Create an `ImageButton`
3. Give it a style in which a trigger is defined and set the `TargetType` property of that trigger `"{x:Type ImageButton}"`.
4. Build fails

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Did you find any workaround?

Set the `TargetType` property to `"ImageButton"` instead.

**Comment by mattleibow** [comment]
According to the docs, it _should_ be `ImageButton`: https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/triggers#property-triggers

Where are you getting the x:Type from?

**Comment by MauiUIui** [comment]
> Where are you getting the x:Type from?

This is actually the original "form". The `TargetType` property is of type `Type` and thus should be provided a value of such type, which is originally done using the `x:Type` markup extension. The way it's written in the documentation you referred to is actually just a well known, well used XAML shortcut, that I usually don't use, because it dosn't always work, for example with custom types. You can read about it from its own documentation [here](https://learn.microsoft.com/en-us/dotnet/desktop/xaml-services/xtype-markup-extension). The link is from .NET desktop (WPF usage) but it explains it pretty well and it stayed the same over the years:

> WPF supports techniques that enable specifying the value of some properties of type [Type](https://learn.microsoft.com/en-us/dotnet/api/system.type) without requiring an x:Type markup extension usage. Instead, you can specify the value as a string that names the type. Examples of this are [ControlTemplate.TargetType](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.controltemplate.targettype) and [Style.TargetType](https://learn.microsoft.com/en-us/dotnet/api/system.windows.style.targettype). Support for this behavior is not provided through either type converters or markup extensions. Instead, this is a deferral behavior implemented through [FrameworkElementFactory](https://learn.microsoft.com/en-us/dotnet/api/system.windows.frameworkelementfactory).

That's why it MUST work for all controls and everywhere and it actually does with all other controls, `ImageButton` being the exception for now ;)

**Comment by MauiUIui** [comment]
> Hi @MauiUIui. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

Dear bot and MAUI community:
It's pretty obvious (and very easy to repro), what is to do here. The fact that s/needs-repro was assigned to this bug implicates that some of you guys don't read on the job. I don't have time for this. I was trying to be y good developer by reporting a bug. Be my guest and close the issue if it makes happy, I'm not wasting anymore time on this.

**Comment by PureWeen** [comment]
@StephaneDelcroix thoughts?

**Comment by StephaneDelcroix** [comment]
@mattleibow and the doc were right. but I did a change to allow x:Type extension there to support what we support in runtime XAML but weren't in compiled one
