### ISSUE TITLE
.NET 8 regression: MenuBar doesn't work on MacCat

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#18332]
### Description

`MenuBar` isn't working in .NET 8 on MacCat. Given the following XAML I'd expect a MenuBar with menu items to appear:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MenuBarDemo.MainPage">
    <ContentPage.MenuBarItems>
        <MenuBarItem Text="File">
            <MenuFlyoutItem Text="Exit"
                            Command="{Binding ExitCommand}" />
        </MenuBarItem>
        <MenuBarItem Text="Locations">
            <MenuFlyoutSubItem Text="Change Location">
                <MenuFlyoutItem Text="Redmond, USA"
                                Command="{Binding ChangeLocationCommand}"
                                CommandParameter="Redmond" />
                <MenuFlyoutItem Text="London, UK"
                                Command="{Binding ChangeLocationCommand}"
                                CommandParameter="London" />
                <MenuFlyoutItem Text="Berlin, DE"
                                Command="{Binding ChangeLocationCommand}"
                                CommandParameter="Berlin"/>
            </MenuFlyoutSubItem>
            <MenuFlyoutSeparator />            
            <MenuFlyoutItem Text="Add Location"
                            Command="{Binding AddLocationCommand}" />
            <MenuFlyoutItem Text="Edit Location"
                            Command="{Binding EditLocationCommand}" />
            <MenuFlyoutItem Text="Remove Location"
                            Command="{Binding RemoveLocationCommand}" />                            
        </MenuBarItem>
        <MenuBarItem Text="View">
            <MenuFlyoutItem Text="Refresh"
                            Command="{Binding RefreshCommand}" />
            <MenuFlyoutItem Text="Change Theme"
                            Command="{Binding ChangeThemeCommand}" />
        </MenuBarItem>
    </ContentPage.MenuBarItems>
    <Grid>
        <Label Text="Hello world"
               HorizontalOptions="Center"
               VerticalOptions="Center" />
    </Grid>
</ContentPage>
```

Here's what I get on MacCat:

![Screenshot 2023-10-25 at 09 28 47](https://github.com/dotnet/maui/assets/8092460/b99bf98d-d66c-4e50-a089-bc73075b9738)

Whereas on Windows it works:

![Capture](https://github.com/dotnet/maui/assets/8092460/1e8a44f1-3448-4eb8-afde-f1dc4fb62893)

(I'm assuming I can remove the ShellContent title).

This occurs whether the app is a Shell-based app, or a "classic" app (NavigationPage-based).

### Steps to Reproduce

1. Create a new .NET 8 app.
2. Add a MenuBar and menu items.
3. Run app.

### Link to public reproduction project repository

https://github.com/davidbritch/dotnet-maui-issues/tree/main/MenuBarDemo

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

macOS

### Did you find any workaround?

I thought maybe the styling is getting in the way, but removing the default resource dictionaries didn't help.

**Comment by drasticactions** [comment]
<img width="666" alt="スクリーンショット 2023-10-25 18 14 27" src="https://github.com/dotnet/maui/assets/898335/3329c70b-c11e-4f55-aa15-a3c2de73a508">

I think they all go to the system menu bar.
