### ISSUE TITLE
App Icon Not Showing in Android Archive

### ISSUE THREAD

**Issue by ISSPRO-Eng** [dotnet/maui#18355]
### Description

When I go to Archive my Android app, the app icon does not show as it did in Xamarin.

### Steps to Reproduce

1. Create new .NET Maui app named Practice Publish.
2. Connect Android Device, put in release mode and archive.
3. App icon is missing from Archive.
4. (iOS Archive Shows App Icon)

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Testing on Android device running API 33

### Did you find any workaround?

Not yet. 

![Screenshot 2023-10-25 at 9 50 05 AM](https://github.com/dotnet/maui/assets/97247069/247bac7a-92be-4626-ae95-ddf1de014e56)
![Screenshot 2023-10-25 at 10 30 41 AM](https://github.com/dotnet/maui/assets/97247069/82ae4e08-857a-467f-8c7b-f8631a476219)

**Comment by mattleibow** [comment]
Does the icon appear when you install the app? Or is this just the IDE not showing the archive icon?

**Comment by ISSPRO-Eng** [comment]
It shows when I install the app through the IDE. Is this just a VS4Mac thing not showing the icon in the archive?

**Comment by mattleibow** [comment]
Very likely. The build would fail if the icon was missing as the manifest references it. Can you open an issue with the IDE feedback tool so the IDE team can have a look?
