### ISSUE TITLE
MAUI - Android App crashes when using a custom scheme URL to resume with a Frame and Entry

### ISSUE THREAD

**Issue by dba98** [dotnet/maui#18362]
### Description

Hello everyone,
I am encountering a crash when resuming my Microsoft MAUI application from a suspended state using a custom scheme URL (e.g., myapp://) when my view contains a Frame and Entry component. This seems to only occur on Android.

### Steps to Reproduce

1. Run the application normally, which includes a Frame and an Entry combined on the view.
2. Suspend the application and subsequently resume it using a custom scheme URL myapp://.

### Link to public reproduction project repository

https://github.com/dba98/MauiAppCrashReport

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by PureWeen** [comment]
@dba98 can you post a stack trace of the exception?
