### ISSUE TITLE
iOS SearchBar Unfocused Event not fired, Keyboard not disappearing.

### ISSUE THREAD

**Issue by Jean-RochSDX** [dotnet/maui#18369]
### Description

On .NET8 when tapping on a SearchBar control the Focused event will be fired and the keyboard appears in order to tip a text. When tapping somewhere else on the screen to stop editing the text the Unfocused event is NOT fired and the keyboard is NOT disappearing. 

On .NET7 the Focus and Unfocused event are never fired but at least the keyboard was correctly appearing and disappearing, whether the SearchBar control was focused or not.

From my understanding this bug should resolved regarding the following issue: #11542

### Steps to Reproduce

- Run TestSearchBarFocus on iOS device.
- Tip on the SearchBar in order to tip a text => Keyboard is appearing and Label change from to "Default" to "Focused" 
- Tip on the red area to unfocus the SearchBar => Label is not updating to "Unfocused". Keyboard is not disappearing.

### Link to public reproduction project repository

https://github.com/Jean-RochSDX/TestSearchBarFocus

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

iOS

### Affected platform versions

iOS 17, iOS 16

### Did you find any workaround?

Yes see comment below: https://github.com/dotnet/maui/issues/18369#issuecomment-1784553262

**Comment by Jean-RochSDX** [comment]
I found a workaround:
Create a simple ContentView Control:

```
public class KeyboardView : ContentView
{
}
```

The following handler:
```
    internal class IOSKeyboardViewHandler : ContentViewHandler
    {
        /// <inheritdoc/>
        protected override void ConnectHandler(Microsoft.Maui.Platform.ContentView platformView)
        {
            base.ConnectHandler(platformView);
            (VirtualView as KeyboardView).GestureRecognizers.Add(new TapGestureRecognizer { Command = new Command(HideKeyboard) });
        }

        private void HideKeyboard()
        {
            UIApplication.SharedApplication.KeyWindow.EndEditing(true);
        }
    }
```

Register the handler:
`handlers.AddHandler<KeyboardView, IOSKeyboardViewHandler>();`

Put the content inside the new ContentView:
```
<common:KeyboardView>
      <StackLayout BackgroundColor="Red">
              <SearchBar x:Name="searchBar" BackgroundColor="White" />
              <Label x:Name="label" Text="Default" />
       </StackLayout>
</common:KeyboardView>
```

**Comment by PureWeen** [comment]
we added a property to control this in .NET8

https://github.com/dotnet/maui/pull/16530

**Comment by Jean-RochSDX** [comment]
Hi, setting the property HideSoftInputOnTapped on the ContentPage to True solved the issue. Thank you.
