### ISSUE TITLE
 Fix iOS Visual Runner so that all tests pass consistently

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#18378]
### Description

Currently when you run the iOS Device Tests locally a few of them will always fail even though they always pass in CI.

We need to make sure all the Visual Test Runners pass with all green so we can more easily test locally

**Comment by jfversluis** [comment]
Can't really see any errors that are different between CI or locally so I think this is fixed. I opened one PR that makes the iOS tests a bit more robust when running on Intel vs ARM, but other than that I think we're done here for now!
