### ISSUE TITLE
Text Color for Button, Picker, CheckBox cannot be changed on Windows, iOS, MacCatalyst

### ISSUE THREAD

**Issue by tekmun** [dotnet/maui#18393]
### Description

Text Color for Button, Picker, CheckBox cannot be changed in .Net 8.0 RC 2. It is a regression issue.

### Steps to Reproduce

1. Create a new project with Button, Picker and CheckBox.
2. Then, in code, change the text-color property.
3. Nothing happens. Color remains white or black (default color)

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

iOS, Windows, macOS

### Affected platform versions

iOS 15, MacCatalyst 15, Windows 10.0.19041.0

### Did you find any workaround?

No workaround.

**Comment by tekmun** [comment]
It doesn't work on Entry as well.

**Comment by Pastajello** [comment]
Cant say I see this issue:
<img width="462" alt="image" src="https://github.com/dotnet/maui/assets/28345098/7d8fca6b-8828-4fc2-a5fe-13e936ece1b9">
<img width="403" alt="image" src="https://github.com/dotnet/maui/assets/28345098/c6e4d693-d3f1-40d4-af91-4885b12b47b6">



<img width="664" alt="image" src="https://github.com/dotnet/maui/assets/28345098/ceb682cb-85c3-4583-8005-7881fd535cfb">

https://github.com/dotnet/maui/assets/28345098/0f54044c-4bd0-46a5-af28-2c963ae16836

**Comment by jsuarezruiz** [comment]
The TextColor is applied using a Style?, could we have a small attached sample?

**Comment by PureWeen** [comment]
There were a few fixes related to this that will be released with Preview 6.

**Comment by tekmun** [comment]
I found the issue. My project was created two years ago. The Styles.xaml and Colors.xaml files in Resources folder differ from those in the new project. I updated them and it works.
The newest Styles.xaml enforces a minimum size of 44px x 44px for images, buttons, pickers, etc.

**Comment by tekmun** [comment]
I found the issue. My project was created two years ago. The Styles.xaml and Colors.xaml files in Resources folder differ from those in the new project. I updated them and it works.
The newest Styles.xaml enforces a minimum size of 44px x 44px for images, buttons, pickers, etc.
