### ISSUE TITLE
[Bug] Dynamically added label not shown in grid 

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#1839]
### Description

I attempted to include a label in the grid. When I add a label during load time, it becomes visible. When I tried to add dynamic via button click, however, the label was not shown.

### Steps to Reproduce

1. Run the sample
2. Click "Add Label" button.
3. See the added label not shown. 

### Expected Behavior

Added label visible in layout. 

### Actual Behavior

Added label not shown in layout. 

### Code

```
 <Grid>
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <Grid x:Name="grid">
            <Label Text="Label" x:Name="label"/>
        </Grid>
        <StackLayout Grid.Row="1">
          
            <Button Margin="10" Text="Add Label" 
                    Clicked="OnAddLabelClicked"/>
        </StackLayout>
    </Grid>
```

```
private void OnAddLabelClicked(object sender, EventArgs e)
		{
			Label label = new Label();
			label.Text = "New Label";
			label.VerticalOptions = LayoutOptions.Center;
			grid.Children.Add(label);
		}
```

### Basic Information

Nuget : Microsoft.Maui : 6.0.100-preview.5.794

### Sample

[MauiSample.zip](https://github.com/dotnet/maui/files/6891784/MauiSample.zip)

**Comment by PaulAnderson02** [comment]
Adding a child(Label or any view) at runtime to a Grid or Stacklayout does not update in UI. Also Columndefinitions and RowDefinitions not working when changed at runtime
