### ISSUE TITLE
CollectionView Layout breaks if IsVisible starts as False

### ISSUE THREAD

**Issue by megukaphii** [dotnet/maui#18395]
### Description

Using an MVVM architecture with the CommunityToolkit.Mvvm package, if a CollectionView using the vertical LinearItemsLayout has the IsVisible property bound to a value that starts as false, the layout will not apply properly on Windows. Specifically, it ends up just displaying horizontally.

I tested this using the MVVM approach and toolkit, however I suspect the issue would persist in any project where the CollectionView starts invisible.

### Steps to Reproduce

1. Create new MAUI app
2. Add CommunityToolkit.Mvvm package
3. Add a CollectionView to the page
4. Populate with any arbitrary data
5. Add <CollectionView.ItemsLayout> node, with <LinearItemsLayout Orientation="Vertical" /> within
6. Create a bool _visible = false field in the view model, with the [ObservableProperty] attribute
7. Add an IsVisible="{Binding Visible}" attribute to the CollectionView
8. Create a Button node with a Command to set Visible to true
9. Build and run the app, click the button

Expected outcome: The CollectionView appears in a vertical orientation
Actual outcome: The CollectionView appears with a horizontal orientation

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17763.0

**Comment by jsuarezruiz** [comment]
This issue will be fixed in the next release by https://github.com/dotnet/maui/pull/17659
