### ISSUE TITLE
[regression/8.0.0] Grouped CollectionView in NavigationPage on iOS recreates the grouped header view on every scroll event

### ISSUE THREAD

**Issue by mjo151** [dotnet/maui#18421]
### Description

If you place a grouped collection view in a NavigationPage, the views for the GroupedHeaderTemplate get recreated many times on every scroll event of the page. This causes poor performance on scrolling, plus memory usage in the app goes through the roof. This occurs on iOS but does not occur on Android. The problem occurs in .NET 8 but not .NET 7. 

This is currently a show stopper for releasing our app.

### Steps to Reproduce

1. Clone the linked repository
2. Run the app on iOS (simulator is fine)
3. Scroll the main page
4. Look at the debug output and notice the printouts for each instantiation of GroupedLabel
5. Open App.xaml.cs
6. Change setting the MainPage to not wrap the MainPage in a NavigationPage
7. Run the app again and notice the problem does not occur

### Link to public reproduction project repository

https://github.com/mjo151/MauiGroupedCollectionViewBug

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS

### Affected platform versions

iOS 16 and 17

### Did you find any workaround?

No

**Comment by blackforest-tom** [comment]
Workaround:

Use Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility with Version="8.0.3" instead of 8.0.6.

Also makes the CollectionView scroll and render smoother by A LOT.
8.0.6 CollectionViews are unusable for us right now.

**Comment by VNGames** [comment]
8.0.3 - works fine, smooth scroll
8.0.6 - group header overlaps randomly

**Comment by anurag-sukumaran** [comment]
- Same issue here.

Is this fixed on  9.0.0-preview.1.9973 (Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility) ?

**Comment by cwilde123** [comment]
For me 8.0.3 also overlap group headers + really low fps on scroll on iOS 17.3.1 iphone 14/15 pro max

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.6.10 (build428) and 17.10.0 Preview 1. Can repro on iOS platform with sample project.
https://github.com/mjo151/MauiGroupedCollectionViewBug

**Comment by rmarinho** [comment]
I m looking at this issue , but I don't see the recreation of the Label when scrolling. If I clear the log and then start scrolling I don't see anything printing . This was on rc2 so the original issue might have been fixed. Do you still see this issue @mjo151  ?

@VNGames @cwilde123  do you have a repo?

Also  what I see with 8.0.10 is the 1st group not showing when not wrapped by the NavigationPage.
so when using  `MainPage = new MainPage(new MainPageViewModel());`

![Simulator Screenshot - iPhone 15 - 2024-03-14 at 20 00 50](https://github.com/dotnet/maui/assets/1235097/434ec99f-e673-4ca9-8a7b-f7fd322cdeb6)

After scroll I also see some issues on the top of the list: 

![Simulator Screenshot - iPhone 15 - 2024-03-14 at 20 01 32](https://github.com/dotnet/maui/assets/1235097/37205795-38d4-45c1-a2da-7aa60087ef2e)

With the NavigationPage as root it seems to look and scroll fine .

**Comment by mjo151** [comment]
@rmarinho Sorry, I have not had a chance to retest this issue with the newer versions of Maui. I had switched to using the Syncfusion ListView in my app due to this problem. I will try to retest this and will reopen this issue if it's still a problem.

**Comment by mjo151** [comment]
I can reproduce the problem in 8.0.0-rc.2.9373 and 8.0.3, but not in 8.0.6, 8.0.7, or 8.0.10. So it appears this was fixed somewhere between 8.0.3 and 8.0.6.

**Comment by rmarinho** [comment]
Ok, thank you for your confirmation @mjo151

**Comment by blackforest-tom** [comment]
For me, the issue started after 8.0.3 and you can see multiple people confirmed this also in the comments above. I don't know why it's happening with different versions for different users, but for me reverting to 8.0.3 was the only option to release an app.
