### ISSUE TITLE
mini_init_method_rgctx + 1673 (jit-icalls.c:1673)

### ISSUE THREAD

**Issue by tnmp83** [dotnet/maui#18424]
### Description

Hi friends, I had migrate MyProject from Xamarin to Maui (net7.0). 
After releasing the application to the apple store. Receive notification of application crash from crashlytics

Crashed: .NET ThreadPool Worker
0  MyProject.MAUI                  0x4e41f58 mini_init_method_rgctx + 1673 (jit-icalls.c:1673)
1  MyProject.MAUI                  0x28d9db4 System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_GSHAREDVT_TStateMachine_GSHAREDVT_ + 28661012
2  MyProject.MAUI                  0x2c06d58 LoadAndDisplayData + 31990968 (<unknown>:31990968)
3  MyProject.MAUI                  0x45144a4 corlib_System_Threading_Thread_StartCallback + 58260484
4  MyProject.MAUI                  0x4e3d250 mono_jit_runtime_invoke + 3526 (mini-runtime.c:3526)
5  MyProject.MAUI                  0x4d7c124 mono_runtime_invoke_checked + 2415 (object.c:2415)
6  MyProject.MAUI                  0x4d95c78 start_wrapper_internal + 1215 (threads.c:1215)
7  MyProject.MAUI                  0x4d95a08 start_wrapper + 1266 (threads.c:1266)
8  libsystem_pthread.dylib        0x24d4 _pthread_start + 136
9  libsystem_pthread.dylib        0x1a10 thread_start + 8

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.96

### Affected platforms

iOS

### Affected platform versions

iOS 16.6.1, 17.0.3

### Did you find any workaround?

I did some research and workaround by adding the following line

<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
   <MtouchLink>SdkOnly</MtouchLink>
   <UseInterpreter>true</UseInterpreter>
</PropertyGroup>

I'm not sure, this is right the solution. Please help me if, Please help me if you have any other solution

**Comment by tnmp83** [comment]
[issue_jit-icalls.txt](https://github.com/dotnet/maui/files/13345320/issue_jit-icalls.txt)
This is full message from Crashlytics
I added the following config to build
`<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
   <UseInterpreter>true</UseInterpreter>
</PropertyGroup>`
I'm not sure it will be fixed if added.
If anyone has tried it and got results, please let me know
Thanks friends

**Comment by ThinhKVT** [comment]
We added above config but result still not good, crash still happen with same frequent. Anyone have other solution for the issue ? Please help us !!!!

**Comment by JRosanowski** [comment]
We're seeing similar issues.

> 0 Preview              0x74b8e80 mini_init_method_rgctx + 1673 (jit-icalls.c:1673)
> 1  Preview              0x19f8e24 System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_GSHAREDVT_TStateMachine_GSHAREDVT_ + 19057304
> 2  Preview              0x1de459c BruTile_BruTile_Web_HttpTileProvider_GetTileAsync_BruTile_TileInfo + 1185580
> 3  Preview              0x74b4178 mono_jit_runtime_invoke + 3614 (mini-runtime.c:3614)
> 4  Preview              0x73f304c mono_runtime_invoke_checked + 2415 (object.c:2415)

**Comment by QianaJiao** [comment]
I'm unable to repro this bug on the latest 17.11.0 Preview 2.1(8.0.60) with my [repo.zip](https://github.com/user-attachments/files/15967537/App7.zip)

If you are still troubled by this issue could you please provide a repro repo, we will check again.
