### ISSUE TITLE
[regression/8.0.0] Border Background Issue in Android

### ISSUE THREAD

**Issue by surya3655** [dotnet/maui#18427]
### Description

In the border, a black background is displayed on Android, but no color is specified for it.

Output:
<img width="203" alt="image" src="https://github.com/dotnet/maui/assets/102782701/2c0e99b5-aae2-494f-8ffc-c722fdc211ae">

Sample:
[BorderIssue.zip](https://github.com/dotnet/maui/files/13201133/BorderIssue.zip)

### Steps to Reproduce

1. Create a .NET MAUI app.
2. Add a border to the MainPage XAML with height and width requests.

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 6.0(8.0.0-rc.2.9373). Repro on Android 14.0-API34, not repro on Windows 11 and iOS 16.4 with below Project:
[BorderIssue.zip](https://github.com/dotnet/maui/files/13235910/BorderIssue.zip)
