### ISSUE TITLE
[regression/7.0.96] Can't click item or button when scroll ScrollView in IOS

### ISSUE THREAD

**Issue by TUYENZKT** [dotnet/maui#18432]
### Description

When I scroll item in my app, I can't click item or button when I scroll to item below that to scroll to it. 
I try fix it as https://github.com/dotnet/maui/issues/14624 but it still error

Please help me fix this issue! 

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.6.10(build428). Not repro on iOS platform with sample project.
https://github.com/Redth/MauiIssueReproBrowser/tree/main/MauiReproBrowser/Issues/14624
