### ISSUE TITLE
SelectionLength Property Not Applied to Entry at Runtime

### ISSUE THREAD

**Issue by NirmalKumarYuvaraj** [dotnet/maui#18443]
### Description

The SelectionLength property in the Entry control is not being applied at runtime as expected. When attempting to set the SelectionLength dynamically, the changes do not reflect in the Entry control's text selection.

**Code snippet**

```C#
entry.Focused += (sender, e) =>
            {
                entry.SelectionLength = 3;
                Debug.WriteLine("entry.Focused");
            };
```
```XAML
<Entry x:Name="entry" Text="Microsoft Maui Entry"></Entry>
```

### Steps to Reproduce

1. Create a new .NET MAUI App.
2. Add an Entry control to the XAML.
3. Wire the focused event of the Entry and set the SelectionLength property at runtime when the Entry receives focus.

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

**Comment by XamlTest** [comment]
Similar issue: https://github.com/dotnet/maui/issues/17657
Verified this on Visual Studio Enterprise 17.8.0 Preview 5.0(8.0.0-rc.2.9373). Repro on Android 14.0-API34, not repro on Windows 11 with below Project:
[18443.zip](https://github.com/dotnet/maui/files/13247737/18443.zip)
