### ISSUE TITLE
Label FontFamily is not recognized when setting WindowsPackageType to none and WindowsAppSDKSelfContained to true

### ISSUE THREAD

**Issue by RiyashameedM** [dotnet/maui#18447]
### Description

The 'FontFamily' label is not recognized when setting 'WindowsPackageType' to 'none' and 'WindowsAppSDKSelfContained' to 'true' in csproj. Additionally, in the 'launchSetting.json' file, I have modified the command name to 'Project'.

I have set up a .NET MAUI project with only a label inside of it using custom font file and declaring an icon. However, the label does not work as expected in Debug and Release modes. However, I need to load these font icons with the specifications I have mentioned.

Code snippet
image

is there any other possible way to fix this?

### Steps to Reproduce

1.Run the attached sample

### Link to public reproduction project repository

https://github.com/RiyashameedM/FontIconSample

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by RoiChen001** [comment]
@RiyashameedM  Unfortunately, the sample project link is no longer available. Does your problem still exist? If so, could you provide us with the project again to illustrate the problem better?
