### ISSUE TITLE
Border with StrokeShape RoundRectangle does not apply rounding to all corners

### ISSUE THREAD

**Issue by sjorsmiltenburg** [dotnet/maui#18453]
### Description

![image](https://github.com/dotnet/maui/assets/649207/e4352922-79be-4773-8ad2-91078379efff)
In the sample xaml not all corners are rounded, where I would expect them to be

### Steps to Reproduce

open bug repo, press Bug11 button

### Link to public reproduction project repository

https://github.com/sjorsmiltenburg/maui_bugs

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

no

**Comment by MitchBomcanhao** [comment]
I'd say that it looks like the shape is just being clipped to the right, so the rounding might be there, but just not visible.

![image](https://github.com/dotnet/maui/assets/31066938/205c67ba-895c-4469-a09b-f15b39c3db1b)

**Comment by sjorsmiltenburg** [comment]
@MitchBomcanhao  I tested and you are correct. Please close this bugreport.
