### ISSUE TITLE
Slider doesn't work

### ISSUE THREAD

**Issue by Amir000001** [dotnet/maui#18469]
### Description

As the slider moves from maximum to minimum, the old value is written to the value, and the new value is written to the old value.
From minimum to maximum everything works correctly.
The sec value is always positive, no matter which direction the slider moves

### Steps to Reproduce

    private async void PlayerSlider_ValueChanged(object sender, ValueChangedEventArgs e)
    {
        var sec = e.NewValue - e.OldValue;
        if (sec >= 5)
        {
            TimeSpan time = TimeSpan.FromSeconds(PlayerSlider.Value);
            player?.SeekTo(time);
        }
    }

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by mattleibow** [comment]
I am not able to reproduce this. I tested in 7.0.100 and 8.0 RC 2.

In both cases, dragging the slider from min to max yields a positive change and max to min yields a negative change.

Are you able to attach a repro sample so I can have a closer look?

**Comment by Amir000001** [comment]
> I am not able to reproduce this. I tested in 7.0.100 and 8.0 RC 2.
> 
> In both cases, dragging the slider from min to max yields a positive change and max to min yields a negative change.
> 
> Are you able to attach a repro sample so I can have a closer look?

I can't share the project, but I can give you more code

using CommunityToolkit.Maui.Core.Primitives;
using CommunityToolkit.Maui.Views;

private async void PlayMusic_SelectionChanged(object sender, SelectionChangedEventArgs e)
{
    if (e.CurrentSelection.Count != 0)
    {
        player.Source = MediaSource.FromUri( your url );
        player.Play();
        player.PositionChanged += Current_PositionChanged;
        player.StateChanged += Current_StateChanged;
    }
}

private void Current_PositionChanged(object sender, MediaPositionChangedEventArgs e)
{
    PlayerSlider.Maximum = player.Duration.TotalSeconds;
    PlayerSlider.Value = e.Position.TotalSeconds;
}

private async void PlayerSlider_ValueChanged(object sender, ValueChangedEventArgs e)
{
    var sec = TimeSpan.FromSeconds(e.NewValue) - TimeSpan.FromSeconds(e.OldValue);
    if (sec >= new TimeSpan(0,0,5))
    {
        TimeSpan time = TimeSpan.FromSeconds(PlayerSlider.Value);
        player?.SeekTo(time);
    }
}

**Comment by Amir000001** [comment]
used CommunityToolkit.Maui.MediaElement.MediaElement

**Comment by Amir000001** [comment]
> I am not able to reproduce this. I tested in 7.0.100 and 8.0 RC 2.
> 
> In both cases, dragging the slider from min to max yields a positive change and max to min yields a negative change.
> 
> Are you able to attach a repro sample so I can have a closer look?

I was very stupid, please forgive me, you can close the question, everything works fine

**Comment by mattleibow** [comment]
No prob! Thanks for the feedback.
