### ISSUE TITLE
[Enhancement] Hit Testing API for Element selection

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#1846]
## Summary
Given either a specific X,Y `point` or a `rect`, return a set of Elements that are visible at that point or points. 

In order to be able to do things like draw adorners on top of UI or show which element(s) are positioned at any given point a user clicks, we need an API that will, given a point or rect, return a list of possible matches.

**Comment by mattleibow** [comment]
I think this is this PR: https://github.com/dotnet/maui/pull/3351

**Comment by drasticactions** [comment]
We got this added into P11, closing.
