### ISSUE TITLE
Maui Popup Randomly Disrupts the Transitional View

### ISSUE THREAD

**Issue by alaskanrogue** [dotnet/maui#18474]
### Description

On a random basis, the exit from a CommunityToolkit.Maui.Views.Popup causes the view called immediately afterwards to be fully disrupted. Typically, the view would look something like the first screen shot but occasionally like the second screen shot. The result is the app unable to proceed and must be restarted. The master layout settings appear to have been deleted. The two round dots appear to be the spans in the first view shrunken with all other components disabled/shrunk to nothing.

![image](https://github.com/dotnet/maui/assets/14001196/01943403-11d5-4d50-b538-50624ded1a4d)

![image](https://github.com/dotnet/maui/assets/14001196/6d803287-904c-4dd0-8296-ac8ade10993d)

 

### Steps to Reproduce

1. Create a MAUI app.
2. Create two fairly complex views.
3. Place a button on the first view. Have the button cause the popup to appear.
4. Have the popup continue button execution cause the second view to appear. 

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 16.7.2, Android 13

**Comment by maonaoda** [comment]
I think you should report the issue here https://github.com/CommunityToolkit/Maui/issues

**Comment by alaskanrogue** [comment]
Reported
