### ISSUE TITLE
[Enhancement] Update DatePicker and TimePicker to use DateOnly and TimeOnly structs

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#1847]
## Summary
Recently added DateOnly and TimeOnly structs seem like a much better fit for DatePicker and TimePicker contols.
Although I'm not sure whether such breaking change (comparing to Xamarin.Forms) is allowed.

## API Changes
Update DatePicker's properties to have DateOnly types:
- MinimumDate 
- MaximumDate
- Date

Update TimePicker's properties to have TimeOnly types:
- Time

**Comment by hartez** [comment]
For reference: https://github.com/dotnet/runtime/pull/50980

**Comment by davidbuckleyni** [comment]
I think to they need think viusally how this works like if date only in the model the time picker element in the picker shoud disappear and vice versus

**Comment by Dreamescaper** [comment]
@davidbuckleyni 
There is no time picker DatePicker, and no date picker in TimePicker, those are two separate components. So I'm not sure what do you mean?

**Comment by davidbuckleyni** [comment]
> @davidbuckleyni 
> 
> There is no time picker DatePicker, and no date picker in TimePicker, those are two separate components. So I'm not sure what do you mean?

If someone described time only for example in the model i would expect only s time picker to be displayed if they had date only then the just the date. If that the case then why mention time only

**Comment by Dreamescaper** [comment]
Sorry, I'm not following :(

Currently [DatePicker ](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datepicker) control uses DateTime type for properties. But even though DateTime has both date and time components, DatePicker allows you to select date only.

My suggestion is to use DateOnly type to reflect that.

Similar situation with [TimePicker](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/timepicker) control, which currently uses TimeSpan type.

**Comment by Redth** [comment]
Let's make Core only have the Date / Time parts as appropriate, and then keep the old DateTime in both on the Controls level and just have it wrap the Date/Time only.

**Comment by Redth** [comment]
Closing in favour of the updated spec in #1100 which takes care of this and nullable.
