### ISSUE TITLE
Unable to scroll carouselview inside of a tabbed page

### ISSUE THREAD

**Issue by TheresasAccount** [dotnet/maui#18490]
### Description

When using a tabbed page, I have a carouselview inside of it that I want to be able to swipe and currently that appears to not be functional.

This was possible in Xamarin Forms

### Steps to Reproduce

1. Create a tabbed page
2. Make a single child of the tabbed page be a carouselview
3. Try swiping the carouselview

Expected: Swiping works

Actual: Carousel just kinda moves a little bit

### Link to public reproduction project repository

[Here](https://github.com/TheresasAccount/TabbedPageCarouselIssue)

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android Emulator API 34

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 5.0(8.0.0-rc.2.9373). Repro on Android 14.0-API34, not repro on iOS 16.4 with below Project:
[TabbedPageCarouselIssue.zip](https://github.com/dotnet/maui/files/13276862/TabbedPageCarouselIssue.zip)

![image](https://github.com/dotnet/maui/assets/97647558/60911db0-82e8-4078-8920-55cd09500d74)

**Comment by davidortinau** [comment]
I'm able to scroll the `CarouselView` on Android within a `TabbedPage` using this same. I added a second page for emphasis. What I noticed is that you of course have a gesture complication between the default swipe behavior to change tabs, and the swipe gesture to move the carousel. If you hold and then swipe, the carouse takes priority. If you just swipe, the tabs start and then stall. 

So, the give the best experience for the carousel, you can use the platform-specific behavior to disable the tab scroll gesture. 

https://learn.microsoft.com/en-us/dotnet/maui/android/platform-specifics/tabbedpage-page-swiping?view=net-maui-8.0

Add this to your `TabbedPage`:

```
xmlns:android="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;assembly=Microsoft.Maui.Controls"
             android:TabbedPage.IsSwipePagingEnabled="False"
```

## Videos

The original in a `TabbedPage`

https://github.com/dotnet/maui/assets/41873/1ba7b3b2-dd77-4074-b669-40f2d7a0090a

Just the `ContentPage`

https://github.com/dotnet/maui/assets/41873/a4f17876-19d3-404a-96eb-c0dc7fadbde4

The `TabbedPage` with the platform-specific

https://github.com/dotnet/maui/assets/41873/45f99011-3955-469e-8650-60329d4bcdd3
