### ISSUE TITLE
[iOS] When setting ImageSource on a Button, LayoutOptions are completely ignored

### ISSUE THREAD

**Issue by Vetle444** [dotnet/maui#18504]
### Description

No matter what you set on HorizontalOptions and VerticalOptions, it is ignored when the ImageSource property is set on a Button. It works fine if the ImageSource property is not set.

**NB!** Version with bug is: 8.0.0-rc.2.9511 **NOT** 8.0.0-rc.2.9373. I could not find 8.0.0-rc.2.9511 in the list below.

### Steps to Reproduce

Add a `Button` like so: `<Button Text="This is a test"
            HorizontalOptions="Center"
            VerticalOptions="Center"
            BackgroundColor="Green" />` wrapped inside for example a `Grid`. Observe that the `Button` only uses the space that it needs to display the text.

Now add an ImageSource to the `Button` like so: `<Button Text="This is a test"
            HorizontalOptions="Center"
            VerticalOptions="Center"
            BackgroundColor="Green"
ImageSource="icon.png" />`. Observe that the `Button` will use the whole space. It behaves exactly as if the `VerticalOptions` and `HorizontalOptions` are set to `Fill`

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.2.9373

### Affected platforms

iOS

### Did you find any workaround?

You can set 'HeightRequest' and 'WidthRequest' to force the 'Button' to only use that much space. However, not feasible to use.

**Comment by jknaudt21** [comment]
@Vetle444 Thanks for catching and reporting this early!

**Comment by Vetle444** [comment]
> @Vetle444 Thanks for catching and reporting this early!

Thank you for already looking into it 😄

**Comment by haavamoa** [comment]
Just to be clear, is this now available in public .NET 8.0 builds? I still see this issue in the latest version of MAUI.

**Comment by Vetle444** [comment]
@durandt Yes! We have implemented this in our ButtonHandler: 

```
public override Size GetDesiredSize(double widthConstraint, double heightConstraint)
    {
        var desiredSize = base.GetDesiredSize(widthConstraint, heightConstraint);
        if (PlatformView is not UIButton uiButton)
        {
            return desiredSize;
        }

        if (uiButton.ImageView.Image is not null && string.IsNullOrEmpty(uiButton.CurrentTitle)) //A button with only a image
        {
            return desiredSize;
        }
        
        if (uiButton.ImageView.Image is null && !string.IsNullOrEmpty(uiButton.CurrentTitle)) //A button with only a title
        {
            return desiredSize;
        }
        
        //A button with both title and image, which has the bug
        return new Size(uiButton.IntrinsicContentSize.Width, uiButton.IntrinsicContentSize.Height);
    }
```

**Comment by durandt** [comment]
Update: `Image != null AND CurrentTitle == string.Empty` would still trigger the issue for me so my work-around now looks like this:

```
    public override Size GetDesiredSize(double widthConstraint, double heightConstraint)
    {
        var desiredSize = base.GetDesiredSize(widthConstraint, heightConstraint);
        if (PlatformView is not UIButton uiButton)
        {
            return desiredSize;
        }

        if (uiButton.ImageView.Image is null) // A button without an image
        {
            return desiredSize;
        }

        if (uiButton.ImageView.Image is not null && uiButton.CurrentTitle == null) // A button with an image and null title
        {
            return desiredSize;
        }

        // A button with image, which has the bug
        if (VirtualView is View view)
        {
            const double TOLERANCE = 0.001;
            var width = Math.Abs(view.WidthRequest - (-1d)) > TOLERANCE ? view.WidthRequest : uiButton.IntrinsicContentSize.Width;
            var height = Math.Abs(view.HeightRequest - (-1d)) > TOLERANCE ? view.HeightRequest : uiButton.IntrinsicContentSize.Height;
            return new Size(width, height);
        }

        return new Size(uiButton.IntrinsicContentSize.Width, uiButton.IntrinsicContentSize.Height);
    }
```

**Disclaimer:** I wasn't able to test with `CurrentTitle` being null so I cannot really say if the fix should be applied in this case or not.

**Comment by durandt** [comment]
The fix for this is included in the release notes for Service Release [8.0.6 SR1](https://github.com/dotnet/maui/releases/tag/8.0.6) (released yesterday)
