### ISSUE TITLE
SwipeGestureRecognizer is not working on Android. Event handlers are never called.

### ISSUE THREAD

**Issue by maxxentropy** [dotnet/maui#18507]
### Description

Swipe gestures that work fine for our iOS application do not work when the app is installed on Android Devices.

We have the following base class for our emulator page views, and we derive our emulator pages from this class to allow for navigation from view to view. ( See example usage below ) This works fine for the iOS platform but event handlers are not called on Android.

    using System.Windows.Input;
    using Microsoft.Maui.Controls;

    public class SwipeableContentView : ContentView
    {
        public static readonly BindableProperty SwipeLeftCommandProperty = BindableProperty.Create(
            nameof(SwipeLeftCommand), typeof(ICommand), typeof(SwipeableContentView));

        public ICommand SwipeLeftCommand
        {
            get => (ICommand)GetValue(SwipeLeftCommandProperty);
            set => SetValue(SwipeLeftCommandProperty, value);
        }

        public static readonly BindableProperty SwipeRightCommandProperty = BindableProperty.Create(
            nameof(SwipeRightCommand), typeof(ICommand), typeof(SwipeableContentView));

        public ICommand SwipeRightCommand
        {
            get => (ICommand)GetValue(SwipeRightCommandProperty);
            set => SetValue(SwipeRightCommandProperty, value);
        }

        public SwipeableContentView()
        {
            var leftSwipeGesture = new SwipeGestureRecognizer { Direction = SwipeDirection.Left };
            leftSwipeGesture.Swiped += (s, e) =>
            {
                if (SwipeLeftCommand?.CanExecute(e) ?? false)
                {
                    SwipeLeftCommand.Execute(e);
                }
            };

            var rightSwipeGesture = new SwipeGestureRecognizer { Direction = SwipeDirection.Right };
            rightSwipeGesture.Swiped += (s, e) =>
            {
                if (SwipeRightCommand?.CanExecute(e) ?? false)
                {
                    SwipeRightCommand.Execute(e);
                }
            };

            this.GestureRecognizers.Add(leftSwipeGesture);
            this.GestureRecognizers.Add(rightSwipeGesture);
        }
    }

usage example:
<local:SwipeableContentView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="http://prismlibrary.com"
             xmlns:vc="clr-namespace:XTConnect.Module.XTEmulator.Converters"
             xmlns:local="clr-namespace:XTConnect.Module.XTEmulator.Views.BaseClassView"
             x:Class="XTConnect.Module.XTEmulator.Views.XTHomePageView"
             SwipeLeftCommand="{Binding OnLeftSwipedCommand}"
             SwipeRightCommand="{Binding OnRightSwipedCommand}">

Our ViewModel defines the commands for binding as such...
        public ICommand OnLeftSwipedCommand { get; private set; }
        public ICommand OnRightSwipedCommand { get; private set; }

and are mapped to the routines in the constructor...
            OnLeftSwipedCommand = new DelegateCommand(OnSwipeLeft);
            OnRightSwipedCommand = new DelegateCommand(OnSwipeRight);

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

None yet

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.0(8.0.40 & 8.0.21 & 8.0.3 & 8.0.0-rc.2.9373). Can repro on Android platform.
