### ISSUE TITLE
PickMultipleAsync returns after first pick on Android

### ISSUE THREAD

**Issue by borrmann** [dotnet/maui#18514]
### Description

see title

### Steps to Reproduce

1. call 

PickOptions options = new()
{
    PickerTitle = AppResources.PickYourFiles,
    FileTypes = FilePickerFileType.Images
};

var fileResult = await FilePicker.Default.PickMultipleAsync(options);

2. pick a file
3. funtions returns to app after first pick!

### Link to public reproduction project repository

https://github.com/borrmann/PickerIssues

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

no

**Comment by borrmann** [comment]
https://github.com/dotnet/maui/assets/20472867/5a954c3c-2893-4526-b8fe-10761d82e28e

**Comment by Amir000001** [comment]
Try selecting pictures by holding down the press, your code works for me

**Comment by drasticactions** [comment]
I think @Amir000001 is correct here. Long pressing on the file should enable multiple selections which you can then return, which I believe is standard behavior for an Android app.

**Comment by borrmann** [comment]
Thanks both. I didnt know that, I only use Android when testing my apps..
