### ISSUE TITLE
Add API to configure scope validation for dependency injection

### ISSUE THREAD

**Issue by Foda** [dotnet/maui#18519]
### Description

We should expose an API that allows users to configure the `services.BuildServiceProvider(validateScopes)` feature as part of the DI injection in `MauiAppBuilder`. Right now, we only validate this in tests, but it would be useful for users to configure this too.

Context: https://github.com/dotnet/maui/issues/11457

### Public API Changes

Maybe some parameter as part of `MauiAppBuilder.Build`??

### Intended Use-Case

Better DI validation

**Comment by crui3er** [comment]
Hi, 
it's already quite easy to enable scope validation.
I accomplish this with:
```
appBuilder.ConfigureContainer(new DefaultServiceProviderFactory(new ServiceProviderOptions {
    ValidateOnBuild = true,
    ValidateScopes = true,
}));
```
The only issue is that enabling this validation causes that MAUI itself fails to resolve `IDispatcher` and `IEnumerable<IMauiInitializeScopedService>` on root container.
These services are registered as scoped.
See https://github.com/dotnet/maui/blob/main/src/Core/src/Hosting/Dispatching/AppHostBuilderExtensions.cs#L18 and https://github.com/dotnet/maui/blob/main/src/Core/src/Hosting/Dispatching/AppHostBuilderExtensions.cs#L26
I changed lifetime to those services in my hybrid blazor app and after that it works.

If you are able to fix `ConfigureDispatching` in MAUI then it's already possible to use existent API.

**Comment by PureWeen** [comment]
@crui3er what's a use case look like in your Maui App where having this validation would keep you safe?

**Comment by crui3er** [comment]
@PureWeen We have a web and Maui app with shared code. Some services are replaced in Maui.
And I discovered that in some cases one scope service was instantiated more than once and this broke the logic. The service was in fact resolved in scope blazor app service provider and in root provider. 
Validation on service resolving would indicate mis configuration by throwing exception that scoped service is resolving from root service provider.

**Comment by PureWeen** [comment]
> And I discovered that in some cases one scope service was instantiated more than once and this broke the logic. The service was in fact resolved in scope blazor app service provider and in root provider.

How are you accessing the root provider to resolve your services?

**Comment by Eilon** [comment]
@crui3er OK is that the same as the original issue I mentioned in https://github.com/dotnet/maui/issues/11457#issuecomment-1374076757 ? If so, that's part of the problem that needs to be addressed by whoever fixes the core issue. That is, there are at least 2 issues:

1. No easy way to enable ScopeValidation in .NET MAUI apps
2. Even if you could enable it, the app would fail due to a bug in MAUI itself. I think that's the issue that you and I both saw

**Comment by Eilon** [comment]
I think this issue really is covering the same as #11457 so I'm closing it as a dupe so we can keep the discussion in one bug. The other bug is about (1) and (2) that I mention in my previous comment, which I think is everything that should be done.

**Comment by crui3er** [comment]
> I think this issue really is covering the same as #11457 so I'm closing it as a dupe so we can keep the discussion in one bug. The other bug is about (1) and (2) that I mention in my previous comment, which I think is everything that should be done.

Yes, lets continue at #11457 By the way (1) is quite easy to accomplish as I showed above in my initial comment, (2) is indeed an issue.
