### ISSUE TITLE
Date not formatted correctly on iPhone device

### ISSUE THREAD

**Issue by NeilN1** [dotnet/maui#18527]
### Description

Dates formatted with ToString("MMM-dd-yyyy") have a extra period after the month abbreviation for all months except for May when deployed to physical iPhone devices (simulator is fine).

### Steps to Reproduce

1. Create new .NET MAUI app.
2. In MainPage.xaml add:
```            
             <Label 
                    Text     ="{Binding ReceiptDate1}" 
                    Margin           ="10,5,10,0" 
                    FontSize ="12"       
                    VerticalOptions="End" 
                    HorizontalOptions="End"/>
            <Label 
                Text     ="{Binding ReceiptDate2}" 
                Margin           ="10,5,10,0" 
                FontSize ="12"  
                VerticalOptions="End" 
                HorizontalOptions="End"/>
```

3. MainPage.xaml.cs:
```
    public partial class MainPage : ContentPage, INotifyPropertyChanged
    {
        int count = 0;
        private string receiptDate1;
        private string receiptDate2;

        public string ReceiptDate1
        {
            get => receiptDate1;
            set
            {
                if (receiptDate1 != value)
                {
                    receiptDate1 = value;
                    OnPropertyChanged(nameof(ReceiptDate1));
                }
            }
        }

        public string ReceiptDate2
        {
            get => receiptDate2;
            set
            {
                if (receiptDate2 != value)
                {
                    receiptDate2 = value;
                    OnPropertyChanged(nameof(ReceiptDate2));
                }
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;

        public MainPage()
        {
            InitializeComponent();
            ReceiptDate1 = DateTime.Now.Date.ToString("MMM-dd-yyyy");
            ReceiptDate2 = new DateTime(2012, 5, 25, 10, 30, 50).ToString("MMM-dd-yyyy");
            BindingContext = this;
        }

        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        private void OnCounterClicked(object sender, EventArgs e)
        {
            count++;

            if (count == 1)
                CounterBtn.Text = $"Clicked {count} time";
            else
                CounterBtn.Text = $"Clicked {count} times";

            SemanticScreenReader.Announce(CounterBtn.Text);
        }
    }
```

![image](https://github.com/dotnet/maui/assets/12532256/61aa7252-454c-49c5-ae41-549cf7bfc9ac)

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

**Comment by drasticactions** [comment]
I think there are two issues here:

1. I believe all of this is Runtime related, and not specific to the MAUI UI Framework. You're creating DateTime values and turning them into strings, and the MAUI UI Framework doesn't influence that. If you create a .NET iOS app without MAUI (Ex. `dotnet new ios`) and try it there, the same behavior should occur.
2. The default Culture set between your device and simulator is could also be playing a part here. My default culture on my iOS Simulator and device is "ja-JP" so based on your DateTime ToString, with it being set to use whatever the culture is on the given device, I get "11月-06-2023", which is expected and correct. It could be that your simulator has different culture settings than your device.

So I have two questions:
1. What is the .NET Culture value when you run on the Simulator and your physical device?
2. Can you reproduce this in a .NET iOS app without MAUI?

**Comment by borrmann** [comment]
btw you can also define the string format in XAML which I find quite convenient, e.g. like so:
`{Binding MyDateTimeObject, StringFormat='{0:ddd, dd.MM HH:mm}'}`.

You can even do that with a static string format and therefore also with a ResX file if you need it localized.
`{Binding MyDateTimeObject, StringFormat={x:Static mynamespace:MyLocalizedStringFormat}}`

**Comment by NeilN1** [comment]
>     So I have two questions:
> 
>     1. What is the .NET Culture value when you run on the Simulator and your physical device?
> 
>     2. Can you reproduce this in a .NET iOS app without MAUI?

I had en-US in the simulator and en-CA on the phone. When I changed to en-CA in the sim, the extra period showed up.  It's also reproducible in a .NET iOS app without MAUI using: 

```
		var vc = new UIViewController ();
		vc.View!.AddSubview (new UILabel (Window!.Frame) {
			BackgroundColor = UIColor.SystemBackground,
			TextAlignment = UITextAlignment.Center,
			Text = DateTime.Now.Date.ToString("MMM-dd-yyyy") + " " + CultureInfo.CurrentCulture.Name,
			AutoresizingMask = UIViewAutoresizing.All,
		});
```

Any suggestions on where to report this? Note that this issue does not happen with Xamarin apps.

**Comment by NeilN1** [comment]
> btw you can also define the string format in XAML which I find quite convenient, e.g. like so: `{Binding MyDateTimeObject, StringFormat='{0:ddd, dd.MM HH:mm}'}`.
> 
> You can even do that with a static string format and therefore also with a ResX file if you need it localized. `{Binding MyDateTimeObject, StringFormat={x:Static mynamespace:MyLocalizedStringFormat}}`

This has the same issue. Interestingly, en-CA also adds periods after every day name abbreviation. This is definitely not how we format dates in Canada. en-GB has the proper formatting as does en-US.

**Comment by drasticactions** [comment]
> > ```
> > So I have two questions:
> > 
> > 1. What is the .NET Culture value when you run on the Simulator and your physical device?
> > 
> > 2. Can you reproduce this in a .NET iOS app without MAUI?
> > ```
> 
> I had en-US in the simulator and en-CA on the phone. When I changed to en-CA in the sim, the extra period showed up. It's also reproducible in a .NET iOS app without MAUI using:
> 
> ```
> 		var vc = new UIViewController ();
> 		vc.View!.AddSubview (new UILabel (Window!.Frame) {
> 			BackgroundColor = UIColor.SystemBackground,
> 			TextAlignment = UITextAlignment.Center,
> 			Text = DateTime.Now.Date.ToString("MMM-dd-yyyy") + " " + CultureInfo.CurrentCulture.Name,
> 			AutoresizingMask = UIViewAutoresizing.All,
> 		});
> ```
> 
> Any suggestions on where to report this? Note that this issue does not happen with Xamarin apps.

If you enable HybridGlobalization (which, I believe, uses the native iOS handling for globalization values like this), that should fix the formatting.

<img width="1230" alt="image" src="https://github.com/dotnet/maui/assets/898335/1b2b3a3a-976c-4859-a67a-562d244e7c1a">

There have been several changes in the .NET Runtime for net8.0 for iOS and Mac handling of globalization values. It could be a regression in net8.0 due to it. It should go to https://github.com/dotnet/runtime.
