### ISSUE TITLE
8.0.0-rc.2.9511 Button background does not override implicit visualstate style

### ISSUE THREAD

**Issue by gabsamples6** [dotnet/maui#18534]
### Description

.Net8 Regression - Button background does not override implicit visualstate style 

see https://github.com/dotnet/maui/issues/18103

as advised by the bot I have opened a new issue

### Steps to Reproduce

see  https://github.com/dotnet/maui/issues/18103   

### Link to public reproduction project repository

see https://github.com/dotnet/maui/issues/18103

### Version with bug

8.0.0-rc.2.9511

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

iOS, Android

### Affected platform versions

VS 2022 any version net 8 RC 2.9511

### Did you find any workaround?

no

### Relevant log output

```shell
no
```

**Comment by drasticactions** [comment]
@gabsamples6 Reopened https://github.com/dotnet/maui/issues/18103.

**Comment by gabsamples6** [comment]
thank you
