### ISSUE TITLE
SVG Image does not work on Button's ImageSource on Android

### ISSUE THREAD

**Issue by aKatsuhiroMihara** [dotnet/maui#18537]
### Description

When I created a MauiImage resource by SVG image, set Button's ImageSource and run the app on Android, button doesn't display icon.

#7066 was closed, but discussed about macOS and Windows only.

### Steps to Reproduce

1. Create a maui project and Android target project.
2. Create MauiImage with SVG image (ex: sample.svg) into the project file.
3. Set Button's ImageSource to MauiImage with png extension (ex: sample.png).
4. Run the app on Android.

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

PNG images (MauiImage or put files into Android project) works.

**Comment by drasticactions** [comment]
<img width="1049" alt="スクリーンショット 2023-11-06 18 33 26" src="https://github.com/dotnet/maui/assets/898335/3e05c7f6-bec5-4b69-96e8-d801477e65c2">

Works for me in net7.0 and net8.0, using the default dotnet_bot.svg that's included with the template. Can you create a repro project with an included svg?

**Comment by aKatsuhiroMihara** [comment]
Sorry for using this board like a Q&A. This is my mistaken in Android programming.

I want to change the tint of icon in a button and reuse a effect of an old Xamarin.Forms app.

MAUI 7.0.96 sets MaterialButton's IconTintMode to PorterDuff.Mode.Add.
https://github.com/dotnet/maui/blob/7.0.96/src/Core/src/Handlers/Button/ButtonHandler.Android.cs#L30
I set IconTint but without overriding IconTintMode to PorterDuff.Mode.SrcIn, so IconTintColor fills in icon area.

To change the tint of icon,

```C#
button.IconTintMode = Android.Graphics.PorterDuff.Mode.SrcIn;
button.IconTint = color.ToDefaultColorStateList();
```

Thanks.

**Comment by mattleibow** [comment]
@aKatsuhiroMihara Please could you open a new issue for that, or better yet, create a discussion so we can help there instead of having an open issue.
