### ISSUE TITLE
[regression/8.0.0] DynamicResource not working with gradients when switching themes at runtime

### ISSUE THREAD

**Issue by Zack-G-I-T** [dotnet/maui#18545]
### Description

When using a DynamicResource to change colors between light and dark mode in a gradient - .NET 8 no longer works. This worked fine in .NET7. The background stays on the light theme version the whole time.

```
<Border.Background>
                    <LinearGradientBrush EndPoint="0,1">
                        <GradientStop Offset="0.1" Color="{DynamicResource GradientColorStart}" />
                        <GradientStop Offset="1.0" Color="{DynamicResource GradientColorEnd}" />
                    </LinearGradientBrush>
</Border.Background>
```

### Steps to Reproduce

1. Download repo
2. Press button and see issue - in dark mode the border should be purple and orange gradient.

### Link to public reproduction project repository

https://github.com/Zack-G-I-T/DynamicResourceNet8

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

Android

### Did you find any workaround?

Using AppThemeBinding with Light and Dark, but our current app has two theme files for Light and Dark Theme so we use the same color names for both files. It will be very tedious to add "Dark" version to all the colours.

**Comment by developer9969** [comment]
@davidortinau  Can you help prioritize this issue?
we have just hit this problem too!  We need the ability to swap merged resource dictionary at run time, we handle many themes that apptheme binding could not cope with. How are we supposed to swap themes now in .net 8 at run time?

We have come across quite a few xaml resource issues recently , this area used to be solid in xamarin.

**Comment by gabsamples6** [comment]
We are affected too but this one. @samhouts  is this part of any milestone? Inability to work with dynamic resources seems pretty important.
Please advise
thanks

**Comment by Felix-Dev** [comment]
Adding my voice here too - we are also impacted by this regression. Using DynamicResource colors in a gradient brush now crashes our app whereas it worked just fine on .NET 7.

When can we expect a fix for this? Thanks.

**Comment by faheys** [comment]
Also ran into this issue today when upgrading our project to .NET 8!

**Comment by developer9969** [comment]
@StephaneDelcroix hi we are affected too.could u please give us an update on this.is this ever going to be fixed.Designers cannot understand why something simple is not supported as we cannot do what they want

**Comment by Swodah** [comment]
Adding voice to this, we are getting binding failures on Dynamic rosource bindings that previously worked:
BackgroundColor="{Binding Source={DynamicResource ColorPrimary}, Mode=OneWay}"
 Stroke="{Binding Source={DynamicResource ColorPrimary}, Mode=OneWay}"
this definitely worked in .net 7, but it may have been broken/changed since.

PS: the error description says it cannot convert from DynamicResource to Maui.Graphics.Color or Maui.Controls.brush.

**Comment by StephaneDelcroix** [comment]
> BackgroundColor="{Binding Source={DynamicResource ColorPrimary}, Mode=OneWay}

Bindings are immutable. and DynamicResources are only applied to Element. So I don't know what you expect to work there

**Comment by StephaneDelcroix** [comment]
> @StephaneDelcroix hi we are affected too.could u please give us an update on this.is this ever going to be fixed.Designers cannot understand why something simple is not supported as we cannot do what they want

looking into this, but can not repro on today's main branch

**Comment by Zack-G-I-T** [comment]
Hi @StephaneDelcroix , I just tried the project that I linked again and I am still getting the wrong behaviour.
I am using Maui version 8.0.7

I even tried with the nightly and still nothing
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.10-nightly.10055" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.10-nightly.10055" />

What version was you using which doesn't replicate?

**Comment by developer9969** [comment]
@StephaneDelcroix  Hi there, this is still an issue and looking at your test , you are not actually testing the issue but just checking if you can read the colors. that will read the correct colors with the current MergedDictionary

The problem occurs when you switch theme at runtime , the gradient colors set for the light theme in our resource file are different from the one in the dark theme. and this only occurs with gradients.

    private void SwitchToLightTheme()
    {
        Application.Current.Resources.MergedDictionaries.Remove(DarkTheme);
        Application.Current.Resources.MergedDictionaries.Add(LightTheme);
        Application.Current.UserAppTheme = AppTheme.Light;
    }

**Comment by StephaneDelcroix** [comment]
The unittest tests that DynamicResources works inside gradients, which is the originally reported issue 😄 . Trying your 'let's switch themes' thing

**Comment by StephaneDelcroix** [comment]
@developer9969 indeed, switching the theme at app level no longer propagate the resources changed event

**Comment by developer9969** [comment]
@StephaneDelcroix oh thank you for your prompt reply , yes that is the issue - I just hope it can be sorted as our design team as gone a bit mad with gradients... and users can switch between various themes..
