### ISSUE TITLE
[Bug] BackgroundColor is not applied if changed using a binding or in code at runtime

### ISSUE THREAD

**Issue by MariyaGordeeva** [dotnet/maui#1854]
### Steps to Reproduce

1. Create a MAUI app.
2. Put Button into Grid or StackLayout on MainPage.xaml.
3. In the Button.Clicked event handler, assign a new color value to Button.BackgroundColor and Grid.BackgroundColor (or StackLayout.BackgroundColor).
4. Deploy to Android Local Device.
5. Click Button.

### Expected Behavior
All elements change and new BackgroundColor values are applied
![Expected](https://user-images.githubusercontent.com/41049348/127495589-56b2d456-ae36-43b5-a1fe-447576013a8f.png)

### Actual Behavior
No elements change their background colors on the screen.
![Actual](https://user-images.githubusercontent.com/41049348/127495586-9c831d2f-a3e9-45cd-b101-49c9135fd519.png)

### Basic Information
IDE: Visual Studio 2022 
Platform Target Frameworks:
Android: 30, iOS 12.5 

### Code
```xaml

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp.MainPage" BackgroundColor="White">

     <StackLayout x:Name="stackLayout">
        <Button x:Name="button" Text="Click to change BackgroundColor" Clicked="OnClicked" HeightRequest="100"/>
    </StackLayout>
</ContentPage>
```

```cs
public partial class MainPage : ContentPage {
	public MainPage() {
		InitializeComponent();
	}

        void OnClicked(Object sender, EventArgs e) {
	        this.stackLayout.BackgroundColor = Color.FromRgb(255, 0, 0);
	        this.button.BackgroundColor = Color.FromRgb(0, 0, 255);
        }
}
```

**Comment by PaulAnderson02** [comment]
Is there any timeline for this bug?

**Comment by mattleibow** [comment]
This was fixed in the latest previews.
