### ISSUE TITLE
ScrollView layout breaks if child controls IsVisible starts as false

### ISSUE THREAD

**Issue by MPearson14** [dotnet/maui#18542]
### Description

Using an MVVM architecture with the CommunityToolkit.Mvvm package, the IsVisible property for a control in a ScrollView within a CarouselView doesn't behave as expected if the property starts as false.

### Steps to Reproduce

1. Launch the app configured in the reproduction project repository.
2. Tap the "Click Me" button on the first page.
3. In the CarouselView swipe to the right and observe the two controls for Button 1 are displayed (Button 1 Heading, Button 1 Entry).
4. In the CarouselView swipe back to the left so the three radio buttons are visible.
5. Tap on the radio button with text "Button 2".
6. In the CarouselView swipe to the right.

**Expected Result:** Two controls for Button 2 are displayed (Button 2 Heading, Button 2 Entry).
**Actual Result:** No controls are displayed.

### Link to public reproduction project repository

https://github.com/MPearson14/TestMauiApp

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.96

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

No

**Comment by osaleem303** [comment]
Same issue, using MAUI [8.0.100-rc.2.9530](https://github.com/dotnet/maui/releases/tag/8.0.100-rc.2.9530)

https://github.com/dotnet/maui/assets/53020319/4cfa0428-ed21-4c0a-bb1e-14b4ded3e7c2

**Comment by mlyrstad** [comment]
Can confirm, we have the same problem and not just with item visibility, but also if the scrollviewer _itself_ is hidden on start

**Comment by MPearson14** [comment]
Issue is resolved in the latest version, Targeting .NET 8 has resolved the problem for me.

**Comment by mlyrstad** [comment]
We were already on .net 8, so not fixed.
