### ISSUE TITLE
Localization of MenuBarItem on Android not working

### ISSUE THREAD

**Issue by cdavidyoung** [dotnet/maui#18556]
### Description

I have started to convert my app to use the localization as described in [https://www.youtube.com/watch?v=cf4sXULR7os](url).  I notice that it does not seem to work for MenuBarItem on Android, although it works for MenuFlyoutItem.  On Android the text of the MenuBarItem does not show up.

### Steps to Reproduce

Clone [https://github.com/jfversluis/MauiLocalizationSample](url) and add the following lines to the MainPage.xaml:

    <ContentPage.MenuBarItems>
        <MenuBarItem Text="{x:Static lang:AppResources.HelloWorld}">
            <MenuFlyoutItem Text="{Binding LocalizationResourceManager[HelloWorld], Mode=OneWay}" />
        </MenuBarItem>
    </ContentPage.MenuBarItems>

When you run it on Windows it behaves as expected.  On Android, this menu does not show up.  The first screenshot is Android and the second Windows.
![Screenshot_20231106_173306](https://github.com/dotnet/maui/assets/937899/82aeb100-d3bb-45fe-90c6-b61cb30d748a)
![2023-11-06](https://github.com/dotnet/maui/assets/937899/42ced0fb-03ef-47e0-b52d-5c5946a5f988)

### Version with bug

7.0.100

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by PureWeen** [comment]
@cdavidyoung the menubar is a desktop feature and isn't currently implement on Android. 

I'm going to move this to a proposal for now. 
What's your expected outcome on Android? 

How would you want this to act different than the MEnuFlyoutItems do?

**Comment by cdavidyoung** [comment]
Sorry.  I confused MenuBarItems with ToolbarItems.  When I use the latter instead is works as expected.  Thanks!

    <ContentPage.ToolbarItems>
        <ToolbarItem
                   Text="{x:Static lang:AppResources.HelloWorld}"
                   Order="Primary"
                   Priority="0" />
        <ToolbarItem 
                   Text="{Binding LocalizationResourceManager[HelloWorld], Mode=OneWay}"
                   Order="Primary"
                   Priority="0" />
        <ToolbarItem 
                   Text="🗑️Clear"
                   Order="Primary"
                   Priority="0" />
![2023-11-08](https://github.com/dotnet/maui/assets/937899/bc39b4ff-cda5-4667-91bd-a93562544ba5)

    </ContentPage.ToolbarItems>
