### ISSUE TITLE
.NET 7: Can't add a ListView to a grid position if the column's with is "auto" 

### ISSUE THREAD

**Issue by brunt-toast** [dotnet/maui#18563]
### Description

When trying to add a `Microsoft.Maui.Controls.ListView` as the child of a `Microsoft.Maui.Controls.Grid`, positioned in a column that has a width of `Microsoft.Maui.GridLength.Auto`, an exception is thrown when rendering it. This also seems to happen if the ListView is a descendant - e.g. in the following scenario: 
```xaml
<Grid ColumnDefinitions="auto">
    <ScrollView>
        <ListView>...</ListView>
    <ScrollView>
</Grid>
```

The exception message is rather unhelpful, showing "Unspecified error". Further inspection shows that it seems to be an issue with the Grid.EffectsFactory, which throws an exception dependent on when/where you add the child: 
* `myGrid.Add(myListView); Content = myGrid;` -> NullReferenceException that does not cause a break 
* `Content = myGrid; (Content as Grid).Add(myListView);` -> InvalidOperationException with the message "No service for type 'Microsoft.Maui.Controls.Hosting.EffectsFactory' has been registered."

Note that the breaking exception seems to occur inside the application itself, not in user-generated code. I can only deduce that it arises from these exceptions. 

This issue appears to have been introduced in .NET 7, as this issue arose after upgrading a project from .NET 6 to .NET 7. I encounter the issue when running on Windows (SDK windows10.0.22621.0, OS Windows 11 Enterprise version 22H2 version 22621.2428). The issue does not seem to appear on Android. I am unable to test on any other platforms. 

### Steps to Reproduce

The simplest way to demonstrate this error is by creating a new ContentPage and adding a Grid to it: 
```xaml
<Grid ColumnDefinitions="auto">
        <ListView />
</Grid>
```

Or, if you want to inspect the code as it runs: 
```cs
namespace MauiApp.Views.Pages;
public class DemoPage : ContentPage {
    public DemoPage() {
        Loaded += LoadedEvent;
    }
    private void LoadedEvent {
        Content = new Grid() {
            RowDefinitions = new() { Height = GridLength.Star },
            ColumnDefinitions = new() { Width = GridLength.Auto }
        };
        (Content as Grid).Add(new ListView()); // breakpoint here to inspect exception
        return; // breaking exception happens after this function returns
    }
}
```

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.22621.0

**Comment by drasticactions** [comment]
As you didn't provide a repro project, I tried to create one myself, but I couldn't reproduce your crash in net7.0 or net8.0, https://github.com/drasticactions/MauiRepros/tree/main/ListViewAutoNetSeven.

Can you create a project showing your error?
