### ISSUE TITLE
Compile error multilanguage app upgrade existing project to .net 8 (visual studio preview version 6)

### ISSUE THREAD

**Issue by Eves101** [dotnet/maui#18576]
### Description

In a project with resource files for different languages the compiler throws a type or namespace not exist.
In the code file itself the resource for the translation is found and intellisense is working fine.

1>C:\Devops\App\View\SettingsPage.xaml.cs(44,61,44,99): error CS0234: The type or namespace name 'Translations' does not exist in the namespace 'xxxApp.Resources' (are you missing an assembly reference?)
in the Resources folder there are several files for the translations (i.e. Resource.nl.resx and Resource.resx)

So i get a ton of error messages, for the missing translation resource reference
is working on .net 7

### Steps to Reproduce

1. create Resource.resx file. in the Resources/Translations folder
2. create Resource.nl.resx file. in the Resources/Translationsfolder 
3. ad a translation item name/value in each file (i.e. MsgOk    Ok)
4. use it in you app:         

```
using Lang = MauiApp1.Resources.Translations.Resource;
namespace MauiApp1
{
	public partial class MainPage : ContentPage
	{
		int count = 0;

		public MainPage()
		{
			InitializeComponent();
		}

		private async void OnCounterClicked(object sender, EventArgs e)
		{
			count++;

			

			if (count == 1)
				CounterBtn.Text = $"Clicked {count} time";
			else
				CounterBtn.Text = $"Clicked {count} times";

			SemanticScreenReader.Announce(CounterBtn.Text);

			if(Application.Current is not null && Application.Current.MainPage is not null)
			{
				await Application.Current.MainPage.DisplayAlert("Alert", "You have (not) been alerted", Lang.MsgOk );

			}
		}
	}

}

```

it wil not compile

### Link to public reproduction project repository

[repository](https://github.com/Eves101/Languagetest.git)

### Version with bug

8.0.0-rc.2.9511

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

it does not compile

### Did you find any workaround?

Rename the Resource.resx file

### Relevant log output

```shell
1>C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>C:\Devops\xxxApp\Model\NavigationStack.cs(87,38,87,51): error CS0234: The type or namespace name 'Resource' does not exist in the namespace 'FieldServiceApp.Resources' (are you missing an assembly reference?)
1>C:\Devops\xxxApp\View\SettingsPage.xaml.cs(44,61,44,99): error CS0234: The type or namespace name 'Resource' does not exist in the namespace 'FieldServiceApp.Resources' (are you missing an assembly reference?)
1>
```

**Comment by drasticactions** [comment]
Your above code sample isn't going to compile, because you're calling `await` in a method that isn't async, so you may want to fix that.

Also,

<img width="637" alt="image" src="https://github.com/dotnet/maui/assets/898335/a0a2e14c-afd4-4422-9296-237a1c197906">

https://github.com/drasticactions/MauiRepros/tree/main/ResourceTest

This works for me in net8.0. Can you please create a reproduction project showing this error?

**Comment by Eves101** [comment]
Added a github repro

**Comment by Eves101** [comment]
Ok, found the solution:
You can not use the filename Resource.resx. Rename the file to something like Common.resx (like drasticactions did)
But it worked in the previous versions

**Comment by drasticactions** [comment]
Thanks @Eves101!

Yeah, I believe you can reproduce this in any application if you use that as the name in that folder, since the default namespace will be used and will conflict because of the name. If you want to use the "Resource" name, you can put those files in a different folder. They don't need to belong in the Resource folder to be used, since Resx files are code that are invoked.
