### ISSUE TITLE
Events should be triggered on iOS

### ISSUE THREAD

**Issue by gdoyon2** [dotnet/maui#18582]
### Description

Taps events are not triggered in UI on iOS. For example, I have a login form with user name and password entry fields. When I tap into them to edit text, nothing is happening. Same issue for the "submit" button inside the login page.

The same code is working well on Android platform.

Note: I am using iOS simulator and Android simulators.

Visual-Studio 2022 17.8
net7.0-ios (Microsoft.iOS V 16.4.0.0)
XCode 15.1
macOS Ventura V 13.6.2

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17, XCode 15.1.

### Did you find any workaround?

Not yet.

### Relevant log output

```shell
No error logged. Just doing nothing.
```

**Comment by osaleem303** [comment]
Tap events are completely not working in release mode on dotnet-7 (only on iOS, Android works completely fine)
Event tried to compile it with XCode 15.0
