### ISSUE TITLE
[Enhancement] Wifi Adapter Controls

### ISSUE THREAD

**Issue by licon4812** [dotnet/maui#18612]
I propose that Wi-Fi adapter controls be added to Maui so that users will be able to control wifi connections from a Maui app. 

I am happy to try and help with this, I just need to know where it would live

**Comment by PureWeen** [comment]
@licon4812 can you propose a spec for this on how you think it would work and what the APIs would look like?

**Comment by licon4812** [comment]
@PureWeen I can get one done in the next few days. Travelling currently

**Comment by licon4812** [comment]
Created spec

#18661
