### ISSUE TITLE
[Bug] Unable to unit test MAUI Windows Handler to WinUI control

### ISSUE THREAD

**Issue by Daniellled** [dotnet/maui#1862]
### Description
When creating a custom handler, for example a new MyButtonHandler. It is not possible to create a unit test that exercises the handler to native windows button control functionality.

In other words if I wanted to test that this code works

```
		public static void MapBackground(ButtonHandler handler, IButton button)
		{
			handler.NativeView?.UpdateBackground(button, DefaultBackground);
		}
```

### Steps to Reproduce

1. Create a Custom button

```
    public class MyButton : Button
    {
        
    }
```

2. Create a custom button handler

```
    public class MyButtonHandler : ButtonHandler
    {
        static Microsoft.UI.Xaml.Media.Brush? DefaultBackground;

        void SetupDefaults(MauiButton nativeView)
        {
            DefaultBackground = (Microsoft.UI.Xaml.Media.Brush)MauiWinUIApplication.Current.Resources["ButtonBackgroundThemeBrush"];
        }

        public static PropertyMapper<IButton, MyButtonHandler> MyButtonMapper = new PropertyMapper<IButton, MyButtonHandler>(ButtonMapper)
        {
            [nameof(IButton.Background)] = MapMyBackground
        };

        public static void MapMyBackground(ButtonHandler handler, IButton button)
        {
            handler.NativeView?.UpdateBackground(button, DefaultBackground);
        }
    }
```
3. Test the handler

```
           var mockButton = new Mock<IButton>();
            mockButton.Setup(foo => foo.Background).Returns(new SolidColorBrush(Colors.Green));

            MyButtonHandler testHandler = new MyButtonHandler();                    

            MyButtonHandler.MapMyBackground(testHandler, mockButton.Object);

            var nv = testHandler.NativeView;

            Assert.AreEqual(Colors.Green.ToNative(), nv.BackgroundColor);
```

### Expected Behavior

The code would execute and the test would pass or fail

### Actual Behavior

A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files (x86)\dotnet'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'D:\TestHandler\TestHandler\TestConsoleApp\bin\Debug\net6.0-windows10.0.19041\TestConsoleApp.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'D:\TestHandler\TestHandler\TestConsoleApp\bin\Debug\net6.0-windows10.0.19041\TestConsoleApp.runtimeconfig.json' file and specify the appropriate framework.

D:\TestHandler\TestHandler\TestConsoleApp\bin\Debug\net6.0-windows10.0.19041\TestConsoleApp.exe (process 32040) exited with code -2147450749.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.

### Basic Information

- Version with issue: Preview 6
- Last known good version:
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 2.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  10.0.19041
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment]
The handlers will not work in a test app because they require a running native app. 

This is why we have the DeviceTests in our repo. Right now it is very maui dependent so it is still in our.

**Comment by Daniellled** [comment]
@mattleibow is the MAUI team using this? In https://github.com/dotnet/maui/tree/main/src/Controls/tests/DeviceTests I only see Label being used. Does this solution run in a CICD pipeline?

**Comment by mattleibow** [comment]
We are using just label for windows, but it runs all of them for android and ios. Right now, we only have iOS and android running on CI. We use xharness to get it going. Moving the discussion on this to here: https://github.com/dotnet/maui/issues/2323
