### ISSUE TITLE
Error - "Android" system image is incomplete

### ISSUE THREAD

**Issue by ashtarshigri** [dotnet/maui#18629]
Invalid system image

"Android 13.0 – API 33" system image is incomplete therefore the device "Pixel 5 - API 33" could not be created.
Do you want us to reinstall the image?

**Comment by moljac** [comment]
@ashtarshigri 
Thanks for the feedback. 

There could be numerous reasons for this issue - network, lack of disk space, .... Please try to reinstall image and see if that helps.

Related:

https://stackoverflow.com/questions/76469464/android-device-manager-problems-starting-on-visual-studio-2022
