### ISSUE TITLE
[regression/8.0.0-rc.2.9530] Completely broken virtualization in CollectionView

### ISSUE THREAD

**Issue by Vroomer** [dotnet/maui#18639]
### Description

The CollectionView loads all items from ItemSource, including those that are not within the view. This results in catastrophic performance in highly populated lists. The behavior was introduced in version 8.0.0-rc.2.9530. Tested on Windows.

In the sample the CollectionView's ItemSource receives Collection of 100 000 simple strings which results in progressive allocation of 4,4 GB and blocks main thread for several minutes.

### Steps to Reproduce

1. Load the repository and run the app.
2. Observe the raising memory usage in profiler/resource monitor.

### Link to public reproduction project repository

https://github.com/Vroomer/MAUI-CollectionView-broken-virtualization

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.2.9511

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by drasticactions** [comment]
I believe this also applies to net7.0 as well, https://github.com/drasticactions/MauiRepros/tree/main/CollectionViewVirt. Not being strictly able to check every previous version of net7.0, it could be a regression in both.
