### ISSUE TITLE
Xamarin Forms Namespace Caused Failure to Generate Code Behind and Compile ALL XAML Files

### ISSUE THREAD

**Issue by TonyLugg** [dotnet/maui#18637]
### Description

I am migrating an app from Xamarin Forms.  I forgot to change one of the namespaces on a single page.  Sometime later I started getting errors in every XAML file on InitializeComponent and all references to elements in the XAML files stating that they were not found in the current context.  Along with these errors that was a warning in the Error List:

> `CSC warning CS8785: Generator 'CodeBehindGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'`

This warning gave no indication what was wrong, and with nothing compiling I thought something in the configuration must be messed up, but I found the issue after restoring from the day before.  When I brought over the XF file, I changed most of the namespaces except this one:

> `http://xamarin.com/schemas/2014/forms`

Changing it to `http://schemas.microsoft.com/dotnet/2021/maui` solved the issue for the entire project.

Two things are wrong here in my opinion:

1.  This issue on a single page should not break code generation and compiling for the entire project.
2.  The code generator should give a better message so that one knows where to look.

Others have run into this issue.

### Steps to Reproduce

1.  Copy over a Xamarin Forms page to the MAUI project
2.  Leave the XF namespace unchanged.

### Version with bug

7.0.101

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

Android SDK 33, iOS 16

### Did you find any workaround?

Replaced the bad namespace with the correct one.

**Comment by jonathanpeppers** [comment]
There is a `.binlog` on discord here:

* https://discord.com/channels/732297728826277939/732297916680765551/1171812782535098488

**Comment by jsuarezruiz** [comment]
cc @StephaneDelcroix

**Comment by mfeingol** [comment]
Just ran into this as well. Evil evil bug, lost a lot of time chasing it down. Thanks to @TonyLugg for leaving a searchable record.
