### ISSUE TITLE
Image blinks when imagesource connected to mpeg stream 

### ISSUE THREAD

**Issue by Angels200** [dotnet/maui#18642]
https://github.com/dotnet/maui/assets/1786693/6e5ec3d7-49b9-4b59-8dbb-eace43d80da4

### Description

The following code is running fine on plateform : WindowsMachine but when switching to Pixel5-API 33 (Android 13.0 - API 33) the image blinks.

```xaml
<Image
    x:Name="Viewer"
    Aspect="AspectFill" 
    WidthRequest="200"
    HeightRequest="200"
    VerticalOptions="Center"
    HorizontalOptions="Center"/>
```

```cs
private void Mjpeg_FrameUpdated(object sender, FrameUpdatedEventArgs e)
{
    if(state == State.Running) 
    { 
        var ms = new MemoryStream(e.Stream.ToArray());
        ImageStack.Dispatcher.DispatchAsync(() =>
                {
                    image.Source = ImageSource.FromStream(() => ms);
                });
     }
 }
```

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13.0

### Did you find any workaround?

No

**Comment by mattleibow** [comment]
One thing that may be worth trying is the `MediaElement` in the MAUI Community Toolkit to play videos: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement

**Comment by YoungRicky7** [comment]
Using a custom image widget can ease the blinking, but still, it blinks

`
using SkiaSharp.Views.Maui.Controls;
using SkiaSharp;
using SkiaSharp.Views.Maui;
using MmImageLoading;

namespace PipeLineApp.CustomControls
{
    public class FrameImage : SKCanvasView
    {
        private SKBitmap bitmap;

        public static readonly BindableProperty SourceProperty = BindableProperty.Create(
            nameof(Source),
            typeof(ImageSource),
            typeof(FrameImage),
            default(ImageSource),
            propertyChanged: OnSourcePropertyChanged);

        public ImageSource Source
        {
            get { return (ImageSource)GetValue(SourceProperty); }
            set { SetValue(SourceProperty, value); }
        }

        private static async void OnSourcePropertyChanged(BindableObject bindable, object oldValue, object newValue)
        {
            try
            {
                var frameImage = (FrameImage)bindable;
                await frameImage.LoadImageAsync();
                frameImage.InvalidateSurface();
            }
            catch (Exception)
            {

                throw;
            }
            
        }

        private async Task LoadImageAsync()
        {
            try
            {
                if (Source != null)
                {
                    byte[] imageData = await GetImageDataAsync(Source);
                    if (imageData != null)
                    {
                        using (var stream = new MemoryStream(imageData))
                        {
                            bitmap = SKBitmap.Decode(stream);
                            await stream.DisposeAsync();
                        }
                    }
                }

            }
            catch (Exception)
            {

                throw;
            }
        }

        private async Task<byte[]> GetImageDataAsync(ImageSource source)
        {
            try
            {
                if (source is FileImageSource fileImageSource)
                {
                    return await File.ReadAllBytesAsync(fileImageSource.File);
                }
                else if (source is StreamImageSource streamImageSource)
                {
                    using var stream = await streamImageSource.Stream(CancellationToken.None);
                    if (stream != null)
                    {
                        return stream.ToByteArray();
                    }
                }
                else if (source is UriImageSource uriImageSource)
                {
                    using var client = new HttpClient();
                    return await client.GetByteArrayAsync(uriImageSource.Uri);
                }

                return null;
            }
            catch (Exception)
            {

                throw;
            }
           
        }
        protected override void OnPaintSurface(SKPaintSurfaceEventArgs e)
        {
            try
            {
                base.OnPaintSurface(e);
                var canvas = e.Surface.Canvas;
                canvas.Clear();

                if (bitmap != null)
                {
                    using (var paint = new SKPaint())
                    {
                        canvas.DrawBitmap(bitmap, new SKRect(0, 0, e.Info.Width, e.Info.Height), paint);
                    }
                }
            }
            catch (Exception)
            {

                throw;
            }
            
        }

    }
}


`

**Comment by YoungRicky7** [comment]
Using a custom image widget can ease the blinking, but still, it blinks.

`using SkiaSharp.Views.Maui.Controls;
using SkiaSharp;
using SkiaSharp.Views.Maui;

namespace PipeLineApp.CustomControls
{
    public class FrameImage : SKCanvasView
    {
        private SKBitmap bitmap;

        public static readonly BindableProperty SourceProperty = BindableProperty.Create(
            nameof(Source),
            typeof(ImageSource),
            typeof(FrameImage),
            default(ImageSource),
            propertyChanged: OnSourcePropertyChanged);

        public ImageSource Source
        {
            get { return (ImageSource)GetValue(SourceProperty); }
            set { SetValue(SourceProperty, value); }
        }

        private static async void OnSourcePropertyChanged(BindableObject bindable, object oldValue, object newValue)
        {
            try
            {
                var frameImage = (FrameImage)bindable;
                await frameImage.LoadImageAsync();
                frameImage.InvalidateSurface();
            }
            catch (Exception)
            {

                throw;
            }
            
        }

        private async Task LoadImageAsync()
        {
            try
            {
                if (Source != null)
                {
                    byte[] imageData = await GetImageDataAsync(Source);
                    if (imageData != null)
                    {
                        using (var stream = new MemoryStream(imageData))
                        {
                            bitmap = SKBitmap.Decode(stream);
                            await stream.DisposeAsync();
                        }
                    }
                }

            }
            catch (Exception)
            {

                throw;
            }
        }

        private async Task<byte[]> GetImageDataAsync(ImageSource source)
        {
            try
            {
                if (source is FileImageSource fileImageSource)
                {
                    return await File.ReadAllBytesAsync(fileImageSource.File);
                }
                else if (source is StreamImageSource streamImageSource)
                {
                    using var stream = await streamImageSource.Stream(CancellationToken.None);
                    if (stream != null)
                    {
                        return stream.ToByteArray();
                    }
                }
                else if (source is UriImageSource uriImageSource)
                {
                    using var client = new HttpClient();
                    return await client.GetByteArrayAsync(uriImageSource.Uri);
                }

                return null;
            }
            catch (Exception)
            {

                throw;
            }
           
        }
        protected override void OnPaintSurface(SKPaintSurfaceEventArgs e)
        {
            try
            {
                base.OnPaintSurface(e);
                var canvas = e.Surface.Canvas;
                canvas.Clear();

                if (bitmap != null)
                {
                    using (var paint = new SKPaint())
                    {
                        canvas.DrawBitmap(bitmap, new SKRect(0, 0, e.Info.Width, e.Info.Height), paint);
                    }
                }
            }
            catch (Exception)
            {

                throw;
            }
            
        }

    }
}`

**Comment by YoungRicky7** [comment]
Using a custom image widget can ease the blinking, but still, it blinks.

`
using SkiaSharp.Views.Maui.Controls;
using SkiaSharp;
using SkiaSharp.Views.Maui;

namespace your_name_space.CustomControls
{
    public class FrameImage : SKCanvasView
    {
        private SKBitmap bitmap;
        public static readonly BindableProperty SourceProperty = BindableProperty.Create(
            nameof(Source),
            typeof(ImageSource),
            typeof(FrameImage),
            default(ImageSource),
            propertyChanged: OnSourcePropertyChanged);
        public ImageSource Source
        {
            get { return (ImageSource)GetValue(SourceProperty); }
            set { SetValue(SourceProperty, value); }
        }
        private static async void OnSourcePropertyChanged(BindableObject bindable, object oldValue, object newValue)
        {
            try
            {
                var frameImage = (FrameImage)bindable;
                await frameImage.LoadImageAsync();
                frameImage.InvalidateSurface();
            }
            catch (Exception)
            {

                throw;
            }     
        }
        private async Task LoadImageAsync()
        {
            try
            {
                if (Source != null)
                {
                    byte[] imageData = await GetImageDataAsync(Source);
                    if (imageData != null)
                    {
                        using (var stream = new MemoryStream(imageData))
                        {
                            bitmap = SKBitmap.Decode(stream);
                            await stream.DisposeAsync();
                        }
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
        }
        private async Task<byte[]> GetImageDataAsync(ImageSource source)
        {
            try
            {
                if (source is FileImageSource fileImageSource)
                {
                    return await File.ReadAllBytesAsync(fileImageSource.File);
                }
                else if (source is StreamImageSource streamImageSource)
                {
                    using var stream = await streamImageSource.Stream(CancellationToken.None);
                    if (stream != null)
                    {
                        MemoryStream memoryStream = stream as MemoryStream;
                        if (memoryStream != null)
                        {
                            return memoryStream.ToArray();
                        }
                    }
                }
                else if (source is UriImageSource uriImageSource)
                {
                    using var client = new HttpClient();
                    return await client.GetByteArrayAsync(uriImageSource.Uri);
                }

                return null;
            }
            catch (Exception)
            {

                throw;
            } 
        }
        protected override void OnPaintSurface(SKPaintSurfaceEventArgs e)
        {
            try
            {
                base.OnPaintSurface(e);
                var canvas = e.Surface.Canvas;
                canvas.Clear();

                if (bitmap != null)
                {
                    using (var paint = new SKPaint())
                    {
                        canvas.DrawBitmap(bitmap, new SKRect(0, 0, e.Info.Width, e.Info.Height), paint);
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }        
        }
    }
}
`
