### ISSUE TITLE
Add NuGet publishing step/gate for Manifest packages

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#18687]
As we get ready to publish our first Service Release _Preview_ as a NuGet package, we want to avoid publishing the actual Manifest package for the preview.  If we publish the manifest package, since it will be in the same SDK Band version (eg: 8.0.100), anyone who happened to run a workload update/install command after we published it would get the workload manifest update and that would then supersede the stable/GA manifest which is likely not the desired outcome.

In our release pipelines, we have steps for publishing to the various public dotnet7/dotnet8 feeds, however we publish _all_ the packages from the build in this case.

We need to change our pipeline to add one more step in that flow, which is to publish the manifest packages separately from the rest.  This step should be _after_ publishing the other packages.

Our pipeline uses powershell and globs the nupkg's from the artifacts.  We should change the glob to exclude packages matching `.Manifest` in their package id (which should be in the filename too) for the first step, and then _only_ glob that pattern to publish the manifests for the second step.

There's one other benefit from doing this too.  For times we still do intend to publish the manifests at the same time, ideally we would publish allll the other packs first, let NuGet.org catch up in terms of validating and indexing the packages (which there are a lot of, and often we publish when other teams are too, so this step takes some time), and only after that's ready, we can publish the manifest packages.  This avoids the scenario on release days where some packages might not be indexed before the manifest packages are, and if you run a workload install/update command, it would fail because though the manifest updates, it can't find the other packages while installing yet.

**Comment by rmarinho** [comment]
@Redth  how will this work to test MAUI workload when dogfooding for example for dotnet8/dotnet7 feeds.

Or should we always push to dotnet/dotnet8 feeds but to nuget.org there's where we don't push the manifest ?

**Comment by rmarinho** [comment]
OK this was implemented on our release pipeline. here are the rules for different feeds.

- nightly will only push .nupkg , no manifests or msi, to the maui nightly feed (nightly feed without manifests so you can't install maui workload for nightly)
- dotnet8 feed will always have the latest main with manifests and msi so you can use dotnet8 to install the maui workload and test. (basically what we have now)
- nuget.org will have 2 gated steps, first to push only .nupkg , and 2nd to push the manifest and msi ( on release day we have to manually approve each of the 2 gates) the 2nd gate manifests will only when doing insertions, the 1st gate if we want to release only to nuget.org as preview nuget.
