### ISSUE TITLE
[Windows] [RC2] Conditional ToolbarItem Text Display Using OnIdiom Not Working in Release Mode

### ISSUE THREAD

**Issue by malsabi** [dotnet/maui#18697]
### Description

When I use ```Text="{ext:Translate ProfileToolBarText}"``` without ```OnIdiom```, it works correctly in both Release and Debug modes. However, I intend to display the text on Desktop only, but this setup only works in Debug mode. In Release mode, it incorrectly displays ```Microsoft.Maui.Controls.Binding```

Behavior in Release Mode (incorrect)
![Issue1](https://github.com/dotnet/maui/assets/21250940/c55a3556-f596-462b-80c1-80d4b634a7d7)

Behavior in Debug Mode (expected):
![Issue2](https://github.com/dotnet/maui/assets/21250940/29a85181-94b2-496a-8e82-4efc8baddea2)

No exceptions are evident in the output that could indicate the root cause. The issue seems to arise when using OnIdiom.

### Steps to Reproduce

1. Clone the Repository.
2. Run the application in Release Mode.
3. You will notice the text is displaying ```Microsoft.Maui.Controls.Binding```.

### Link to public reproduction project repository

https://github.com/malsabi/ToolBarItemIssue

### Version with bug

8.0.0-rc.2.9511

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows10.0.19041.0

### Did you find any workaround?

No I didn't find any workaround.

**Comment by jsuarezruiz** [comment]
@StephaneDelcroix Thoughts?

**Comment by StephaneDelcroix** [comment]
one path is using SetValue, the other is using SetBinding... I would not have considered this as a bug and only a possible enhancement, but the mismatch between debug and release require a solution

**Comment by malsabi** [comment]
> one path is using SetValue, the other is using SetBinding... I would not have considered this as a bug and only a possible enhancement, but the mismatch between debug and release require a solution

Is there any workaround that we can use at the moment ?

**Comment by malsabi** [comment]
@StephaneDelcroix If there's any workaround for this issue please let me know, we are deploying our app on December.

**Comment by cgomezm** [comment]
@malsabi i have it working like this in case you don't need anything from the binding 
public object ProvideValue(IServiceProvider serviceProvider)
{
return Translator.Instance[Key];
}

**Comment by malsabi** [comment]
@cgomezm 
Hello thanks for replying.
I tried the approach but it didn't work on release mode it kept on crashing, here is how I tried it:
Maybe you could create a PR to the same repo I provided earlier.

 ```csharp
namespace ToolBarItemIssue.Common.Extensions
{
    [ContentProperty(nameof(Name))]
    public class TranslateExtension : IMarkupExtension<BindingBase>
    {
        public string? Name { get; set; }

        public BindingBase ProvideValue(IServiceProvider serviceProvider)
        {
            throw new NotImplementedException();
        }

        object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
        {
            if (string.IsNullOrEmpty(Name))
                return "N/A";
            return LocalizationResourceManager.Instance[Name];
        }
    }
}
```

**Comment by cgomezm** [comment]
@malsabi I moved away from returning the binding and just return the string value.
`[ContentProperty(nameof(Key))]
internal class TranslateExtension : IMarkupExtension
{
    public string Key { get; set; }

    public object ProvideValue(IServiceProvider serviceProvider)
    {
        return Translator.Instance[Key];
    }
}  `

**Comment by malsabi** [comment]
@cgomezm 
I can confirm your code works on Release / Debug mode however when I try to change the language in runtime it does not work. 
I tried using the following snippet:

 ```csharp
 if (AppResources.Culture.TwoLetterISOLanguageName.Equals("en"))
 {
     LocalizationResourceManager.Instance.SetCulture(new CultureInfo("ar"));
 }
 else
 {
     LocalizationResourceManager.Instance.SetCulture(new CultureInfo("en"));
 }
 ```

**Comment by cgomezm** [comment]
@malsabi  yeah, that could be a downside as is the value being returned instead of the binding. Maybe dotnet team has made some progress on their investigation of this.

**Comment by malsabi** [comment]
@jsuarezruiz any thoughts or progress about this issue ?

**Comment by StephaneDelcroix** [comment]
We can not fix this, in either way: it's not possible (using a reasonable effort) to make it succeed (in all cases) when XamlC is on, and it's not possible to have it fail when XamlC is off

one way would be to deprecate OnIdiom in favour of OnIdiom<TReturnType> (oh, well, it used to be that way)

**Comment by malsabi** [comment]
> found a solution, finally

Can you tell us what was the solution ? Is there any changes we need to know about ?
