### ISSUE TITLE
[Bug] Grid on WinUI does not layout correctly

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#1869]
### Description

This can be seen on the "Template" page of the maui sample app. 

### Steps to Reproduce

1. Change the `_pageType` field in the Startup.cs to be `PageType.Template`
2. Run the Windows app
3. Observe an incorrect layout

### Expected Behavior

Correct layout. There is also an image below the button.

### Actual Behavior

| Initial Launch | After Resize |
| :-: | :-: |
| ![image](https://user-images.githubusercontent.com/1096616/127571914-7dd5f649-b1b7-42fc-a236-522df35f12ca.png) | ![image](https://user-images.githubusercontent.com/1096616/127571976-eccb2d6e-7c8e-4012-9221-ab441fe2f2b9.png) |

**Comment by hartez** [comment]
Fixed as of the latest release/6.0.1xx-preview7.
