### ISSUE TITLE
[iOS/Catalyst] CollectionView scrolling performance when height is not constrained drops drastically.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#18696]
### Description

https://github.com/dotnet/maui/assets/898335/1bd005e1-9c33-411e-8816-29f388ecd348

https://github.com/dotnet/maui/assets/898335/68afb3be-2cc2-4059-a25f-234744a5a4dc

When using CollectionView on iOS, if the view is not constrained to a height, the performance of scrolling drops drastically. As far as I can tell, although I am unsure of the exact cause, there is activity happening on the UI thread that blocks it whenever new items are loaded. Virtualization is not broken as far as I can see.

While performance on Catalyst seems better on the surface, there are noticeable hitches that also block the UI Thread. Setting a height on the view mostly eliminates it.

https://github.com/dotnet/maui/assets/898335/27facd04-3360-4bc8-b7e3-7d1e570789ab

https://github.com/dotnet/maui/assets/898335/f9eac1c7-b9e3-496c-a3b8-fb1b136ceee5

### Steps to Reproduce

1. Run the included reproduction project.
2. Open the app, scroll the list.

You'll see that the scroll is jittery and the frames per second count goes down as tons of activity is being called on the UI Thread.

### Link to public reproduction project repository

https://github.com/drasticactions/Drastic.Tools/tree/1b3ea2fd9cba12a8da56bb29a72c6ef8c9049927/sample/Drastic.UITools.Sample

### Version with bug

8.0.0-rc.2.9511

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

**Comment by Take-A-Byte** [comment]
I think the problem is with multiple rerenders/recalculations being made while scrolling. You can see this clearly if you create items of different sizes in the collection view....

https://github.com/dotnet/maui/assets/29909785/4df2134b-6825-4a15-97fa-dcbe0c237631

The strange thing is that it seems to be related to relative sizing i.e. if I use fixed size, the UI works as expected.
Another thing to note is that, it seems to affect iOS and Mac-catalyst but not Windows.

**Comment by rmarinho** [comment]
@drasticactions  are you still seeing this with the latest stable 8.0.10 ?

**Comment by rmarinho** [comment]
```
<CollectionView x:Name="TestCollectionView" ItemSizingStrategy="MeasureFirstItem">
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <Label Text="{Binding .}" HeightRequest="50"/>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
   
  ```
  using this approach with fixed height I get the same performance and frame rate..

**Comment by rmarinho** [comment]
@Take-A-Byte  do you have a sample ?

**Comment by rmarinho** [comment]
I hust test with 8.0.7 stable and I can't reproduce this issue . This was initially open for rc2 so I think the issue got fixe in the meanwhile. 

@drasticactions  feel free to reopen if you can reproduce with latest.

@Take-A-Byte if you have a repo please open a new issue so I can take a look. 

Thanks
