### ISSUE TITLE
[regression/8.0.3]  Image no longer fits container

### ISSUE THREAD

**Issue by BioTurboNick** [dotnet/maui#18698]
### Description

![image](https://github.com/dotnet/maui/assets/1438610/11724ce0-054c-4e42-90c7-40030f8f799e)

The "| 0 | 0 | 0 |" is a PNG that's contained in a Grid in an AbsoluteLayout. Previously, the image was reduced to fit into the container (the yellow box in top left). Now, however, it is being rendered at full size, and somehow also pulling its sibling object along with it.

If the Image source is removed, the triangle shape fits into the container as expected, as seen in the other controls.

```
<AbsoluteLayout
    x:Name="exposedSliderPanel"
    AbsoluteLayout.LayoutFlags="All">

    <Grid
        BackgroundColor="Yellow"
        x:Name="sliderDisplayPanel"
        AbsoluteLayout.LayoutFlags="All"
        AbsoluteLayout.LayoutBounds="0.5,0.85,0.5,0.5">

        <GraphicsView
            x:Name="triangleImageCanvas" />

        <Image
            Opacity="0.5"
            VerticalOptions="Center"
            
            Source="{Binding SlideImageSource}" />

    </Grid>

</AbsoluteLayout>
```

### Steps to Reproduce

See above

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.81

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

**Comment by drasticactions** [comment]
Based on your description alone, I'm not entirely sure how to reproduce these conditions. I tried making this in both net7.0 and net8.0 and they seemed to do the same but I'm not sure if it's what you expect in either case.

Could you please create a reproduction project with this fully set up to show this condition?

**Comment by BioTurboNick** [comment]
I've attached two near-minimal example projects, one configured for MAUI 7.0.81, one configured for MAUI 8-rc2.

I specify 7.0.81 because the issue first appeared in 7.0.86.

[ImageSizeBug8.zip](https://github.com/dotnet/maui/files/13330626/ImageSizeBug8.zip)
![image](https://github.com/dotnet/maui/assets/1438610/82414b5d-a7ed-4f29-abfc-9696a15ea49e)

[ImageSizeBug7.zip](https://github.com/dotnet/maui/files/13330627/ImageSizeBug7.zip)
![image](https://github.com/dotnet/maui/assets/1438610/3f42ccc9-4fe8-443b-af1c-823b98e6152d)

**Comment by BioTurboNick** [comment]
Probably related to #15195, although some of the bad sizing is fixed in 8.0-rc2.

**Comment by BioTurboNick** [comment]
I can grudgingly accept it may not be fixed until SR2, but is there any possible workaround? Even a pointer at what I might try would be great.

**Comment by BioTurboNick** [comment]
Alright I have a workaround. In the LayoutManager I am using for my control, in the ArrangeChildren method, I do this:

```
await Task.Delay(100);
slider.sliderImage.WidthRequest = slider.sliderDisplayPanel.Width;
slider.sliderImage.HeightRequest = slider.sliderDisplayPanel.Height;
```

It's not perfect because it may briefly appear in the incorrect format, but it ensures it reaches the proper size. `slider` is the private field in the LayoutManager to access its control.

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12.0 Preview 1.0(8.0.80 & 8.0.72). Not repro on android platform.

**Comment by BioTurboNick** [comment]
I'm confused, was action needed on my part? Last message said there was a reproduction?


________________________________
