### ISSUE TITLE
Unable to build chain to self-signed root for signer .NET MAUI 7.0

### ISSUE THREAD

**Issue by LordMax2** [dotnet/maui#18693]
### Description

When I try to build my .NET MAUI 7.0 application on my MacBook Pro I get the following exception:

```
Warning: unable to build chain to self-signed root for signer "Apple Distribution: Max Klevebrand (6H3446RVA5)"
  /Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/bin/Release/net7.0-ios/ios-arm64/Trest.Solar.Maui.app: errSecInternalComponent
  
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/tools/msbuild/iOS/Xamarin.Shared.targets(2174,3): error : /usr/bin/codesign exited with code 1: [/Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/Trest.Solar.MAUI.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/tools/msbuild/iOS/Xamarin.Shared.targets(2174,3): error : Warning: unable to build chain to self-signed root for signer "Apple Distribution: Max Klevebrand (6H3446RVA5)" [/Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/Trest.Solar.MAUI.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/tools/msbuild/iOS/Xamarin.Shared.targets(2174,3): error : /Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/bin/Release/net7.0-ios/ios-arm64/Trest.Solar.Maui.app: errSecInternalComponent [/Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/Trest.Solar.MAUI.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/tools/msbuild/iOS/Xamarin.Shared.targets(2174,3): error : Failed to codesign '/Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/bin/Release/net7.0-ios/ios-arm64/Trest.Solar.Maui.app': Warning: unable to build chain to self-signed root for signer "Apple Distribution: Max Klevebrand (6H3446RVA5)" [/Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/Trest.Solar.MAUI.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/tools/msbuild/iOS/Xamarin.Shared.targets(2174,3): error : /Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/bin/Release/net7.0-ios/ios-arm64/Trest.Solar.Maui.app: errSecInternalComponent [/Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/Trest.Solar.MAUI.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/tools/msbuild/iOS/Xamarin.Shared.targets(2174,3): error :  [/Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/Trest.Solar.MAUI.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/tools/msbuild/iOS/Xamarin.Shared.targets(2174,3): error :          [/Users/itadmin/Documents/repos/Trest.Solar.App-MAUI/Trest.Solar.App/Trest.Solar.MAUI.csproj::TargetFramework=net7.0-ios]
```

### Steps to Reproduce

1. Create a new .NET MAUI 7.0 app
2. Setup certificates, provisioning profiles and identity on apple developer page
3. run "dotnet publish -f:net7.0-ios -c Release

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Ive tried this: https://blog.verslu.is/app-publishing/unable-to-build-chain-for-self-signed-root/

And the result was that the certificate wasnt "invalid" anymore, but still the same exception. 

The app was named "*.app" before, so I tried to rename it to end with something different than ".app" to see if that was the problem.

I had a MacInCloud instance before and that worked flawless, but now I am using a physical MacBook Pro running Sonoma 14.1.1 (23B81).

**Comment by jsuarezruiz** [comment]
@rolfbjarne Thoughts?

**Comment by rolfbjarne** [comment]
https://blog.verslu.is/app-publishing/unable-to-build-chain-for-self-signed-root/

**Comment by rolfbjarne** [comment]
Ah, I see you already read that, so nvm.

**Comment by rolfbjarne** [comment]
Can you build an app (and deploy to a device) using Xcode?

**Comment by Hickori** [comment]
I unfortunately don't have an iOS device, borrowing the computer, but I can build it to the simulator without a problem.

**Comment by rolfbjarne** [comment]
> I unfortunately don't have an iOS device, borrowing the computer, but I can build it to the simulator without a problem.

You should still be able to build for device in Xcode, even if you're not able to deploy to one.

**Comment by jaosnz-rep** [comment]
Can be published successfully using dotnet publish -f net8.0-ios -c Release on .NET 8.0 (8.0.21) and .NET 7.0 (7.0.101)
