### ISSUE TITLE
[Bug] All platform Labels do not re-layout after text changes

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#1870]
### Description

When the text in a label changes, the view is not repositioned or resized accordingly. It appears to remain the same size.

### Steps to Reproduce

1. Change the `_pageType` field in the Startup.cs to be `PageType.Template`
2. Run any of the platforms. 
3. Click the button a few times and once you reach 10, the number disappears because it gets clipped or wrapped outside the view's bounds.

### Expected Behavior

Label resizes.

### Actual Behavior

Label does not resize.

### Screenshots

<img src="https://user-images.githubusercontent.com/1096616/127572926-2fc38f6e-03f8-4cf5-b04e-9f1499e223db.gif" width="200" />

**Comment by hartez** [comment]
Working correctly on all platforms on main now.
