### ISSUE TITLE
Borders border looks unsharp and thickness varies across platforms

### ISSUE THREAD

**Issue by torfluor** [dotnet/maui#18705]
### Description

When compared to a button element, the border controls border looks blurred and looks thinner on Windows and wider on Mac Catalyst.

The image below shows a sample app with a border and a button element, both with border color black and border thickness 1. 
<img width="400" alt="WindowsVsMac" src="https://github.com/dotnet/maui/assets/38349756/74853e36-44c5-459a-a9e4-de870de23ff7">

### Steps to Reproduce

1. Create a MAUI app with a border and a button
2. Set the Button BorderColor to black and BorderWidth to 1
3. Set the Border Stroke to black and StrokeThickness to 1

Expected results:
Both borders should have same color and same thickness, and the thickness and color should look the same on every platform.

Actual result:
On Windows the Border looks thinner and more fuzzy than the Button. On Mac the Borders border looks thicker than the button.

### Link to public reproduction project repository

https://github.com/torfluor/MauiButtonVsBorder

### Version with bug

8.0.0-rc.2.9511

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS

### Affected platform versions

Windows 11 Pro 22000.2538 and MacOS Ventura 13.3

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). Repro on Windows 11 with below Project:
[MauiButtonVsBorder.zip](https://github.com/dotnet/maui/files/13372837/MauiButtonVsBorder.zip)

For Windows:  Borders border looks thicker and more fuzzy than the Button.
![image](https://github.com/dotnet/maui/assets/97647558/1ab6cecf-c22d-4f71-ae4b-00a504dd07d8)
For Mac: Borders border looks same with Button, the difference is not obvious.

**Comment by tschbc** [comment]
Has anyone figured out a workaround for this?
