### ISSUE TITLE
XamlC ignores isError option in ObsoleteAttribute

### ISSUE THREAD

**Issue by AidarNurmukhametov** [dotnet/maui#18704]
### Description

Hello, I am confused with XamlC since it completely ignores if ObsoleteAttribute should break compilation. E.g such code builds and when fails successfully:

```csharp
...
    [Obsolete($"Use {nameof(TextChanged)} instead.", true)] // <- should this break the compilation?
    public event EventHandler TextChangedObsolete {
        add => throw new NotImplementedException();
        remove => throw new NotImplementedException();
    }

    public event EventHandler TextChanged;
...
``` 

```xml
<local:ViewWithObsolete TextChanged="ViewWithObsolete_TextChanged" />
```

I see similar issue #8048, but it only adds logging, not actual work with this attribute. This is kind of important since you cannot really check all your application if it has such issues. As I can see there is no workaround, any dependency version update can lead to this situation.

### Steps to Reproduce

1. Create any view
2. Add property and/or event
3. Mark with obsolete and set isError to true.
4. Use obsolete properties in Xaml only.
5. Build, run
6. Note that everything completed successfully
7. Enable <TreatWarningsAsErrors> option
8. Project still builds and runs despite there are warnings

### Link to public reproduction project repository

https://github.com/AidarNurmukhametov/ObsoletesBug

### Version with bug

8.0.0-rc.2.9511

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Did you find any workaround?

No, nothing helps

**Comment by jsuarezruiz** [comment]
cc @StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
yep, #8048 was about detecting Obsolete, but not failing on compilation, we probably should do that
