### ISSUE TITLE
When create and running a new .net MAUI Blazor Hybrid App only show the blue background 

### ISSUE THREAD

**Issue by xccu** [dotnet/maui#18707]
### Description

When create a new  new .net MAUI Blazor Hybrid App and running by Windows Machine , only shown a blue background without Blazor razor pages
![image](https://github.com/dotnet/maui/assets/7534189/608d6e0a-66c4-4080-a7cc-cd7b21b96a5b)
the  Developer Mode has  switch to on
![image](https://github.com/dotnet/maui/assets/7534189/eefb9e6e-50c2-47f3-bb80-c29911e76849)

### Version with bug

7.0.101

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.49

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(**8.0.3 and 7.0.101**). Cannot repro on Windows 11 and Windows 10 with below Project:
[18707.zip](https://github.com/dotnet/maui/files/13362501/18707.zip)

![image](https://github.com/dotnet/maui/assets/97647558/54a768d5-d2f9-4845-965a-cd6f37a18b19)
@xccu Could you try again on .NET 7 and .NET 8? Please let us know if you have any update.
