### ISSUE TITLE
[Bug] iOS layout is off center

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#1871]
### Steps to Reproduce

1. Change the `_pageType` field in the Startup.cs to be `PageType.Template`
2. Run the iOS app
3. Observe the page is a bit to the right
4. Rotating the device causes the contents to become correct.

### Expected Behavior

Content is centered.

### Actual Behavior

<img width="469" alt="Screenshot 2021-07-30 at 00 30 42" src="https://user-images.githubusercontent.com/1096616/127573851-e04908a7-2f20-4ce5-8e1c-1124d59165c2.png">

**Comment by hartez** [comment]
This is fixed in the latest on release/6.0.1xx-preview7.
