### ISSUE TITLE
[Spec]  Support StackLayout "expanding" or "weights"

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#1872]
# StackLayout.Expand  /  StackLayout.Weight

Xamarin.Forms used to use a `*AndExpand` layout option for creating a UI that would expand to fill a stack layout.

With Maui, we can do better. Instead of forcing a second set of members into the LayoutOptions, we can deprecate the `AndExpand` and make use of an attached property to add specific values for just the StackLayout.

If we use an actual number for the expand, then we can have multiple items expanding at a different ratio, and we can be consistent with Grid.

> This is the exact same feature that Grid uses with the Star columns. We probably don't need a `*` in the value since it is always a star, but we can have the converter just ignore it.

# API

```csharp
public class StackLayout {
    public static BindableProperty Expand = BindableProperty.CreateAttached(
        propertyName: "Expand",
        returnType: typeof(int),
        declaringType: typeof(StackBase),
        defaultValue: 1);
}
```

# Scenarios

## C# Example
```csharp
StackLayout.SetExpand(myButton, 1);
```

## XAML Example
```xaml
<StackLayout>
  <Button />
  <Button StackLayout.Expand="1" />
  <Button StackLayout.Expand="1*" />
</StackLayout>
```

## CSS Example
```css
Button {
     -maui-stacklayout-expand: 1;
}
```

# Backward Compatibility

Minimum API levels?
Breaking changes?
Unsupported platforms?

# Difficulty : low

**Comment by jsuarezruiz** [comment]
Take a look to the discussion here: https://github.com/dotnet/maui/discussions/3324

**Comment by jsuarezruiz** [comment]
We have a discussion and the same issue (not exactly the same, but covering the same topic) duplicated. Closing this one to concentrate all the comments in #29.
