### ISSUE TITLE
[iOS] Permissions.RequestAsync<Permissions.CalendarWrite><Permissions.CalendarRead> fails to return a value on iOS 16+

### ISSUE THREAD

**Issue by vikher** [dotnet/maui#18737]
### Description

The Permissions.RequestAsync<Permissions.CalendarWrite> and Permissions.CheckStatusAsync<Permissions.CalendarRead> methods are returning "denied" consistently on iOS 16 & 17 while working as expected on Android. The issue occurs when using both .NET 7.0.96 and 8.0.0 rc.2 versions.

Expected Behavior:
The Permissions.CheckStatusAsync<Permissions.CalendarWrite>() and Permissions.CheckStatusAsync<Permissions.CalendarRead>() methods should return the correct permission status, and Permissions.RequestAsync<Permissions.CalendarWrite>() and Permissions.RequestAsync<Permissions.CalendarRead>() should prompt the user for permission if not granted previously.

Actual Behavior:
Both CheckStatusAsync and RequestAsync methods return "denied" consistently on iOS 16 & 17, failing to grant permission even when requested via the application.

Environment:

Platform: iOS 16 & 17
.NET Versions: 7.0.96 and 8.0.0 rc.2
Device: iOS devices
MAUI

Code Snippet:

```
public async Task<bool> CheckAndRequestCalendarPermission()
{
    try
    {
        var statusWrite = await Permissions.CheckStatusAsync<Permissions.CalendarWrite>();
        var statusRead = await Permissions.CheckStatusAsync<Permissions.CalendarRead>();

        if (statusWrite != PermissionStatus.Granted && statusRead != PermissionStatus.Granted)
        {
            statusWrite = await Permissions.RequestAsync<Permissions.CalendarWrite>();
            statusRead = await Permissions.RequestAsync<Permissions.CalendarRead>();

            if (statusWrite == PermissionStatus.Granted && statusRead == PermissionStatus.Granted)
            {
                return true;
            }
            else
            {
                if (DeviceInfo.Platform == DevicePlatform.iOS)
                {
                    // Prompt the user to turn on in settings
                    // On iOS once a permission has been denied it may not be requested again from the application
                    await App.Current.MainPage.DisplayAlert("Calendar permission has been denied", "You can turn access on from your iPhone Settings->Privacy->Calendars.", "OK");
                }
                return false;
            }
        }

        if (statusWrite == PermissionStatus.Granted && statusRead == PermissionStatus.Granted)
        {
            return true;
        }
        else if (statusWrite == PermissionStatus.Unknown && statusRead == PermissionStatus.Unknown)
        {
            return false;
        }

        return false;
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
        return false;
    }
}
```

Additional Notes:

The issue seems isolated to iOS 16 & 17 as Android works as expected.
This behavior persists across both .NET versions 7.0.96 and 8.0.0 rc.2.
The provided code snippet utilizes MAUI and is meant for managing calendar permissions.

Impact:
The bug significantly affects applications relying on calendar permissions on iOS devices running versions 16 & 17, rendering the functionality non-functional.

### Steps to Reproduce

Deploy the provided code snippet attached in the repository on iOS 16 & 17.
Attempt to check and request calendar permissions using the CheckAndRequestCalendarPermission() method.

### Link to public reproduction project repository

https://github.com/vikher/Calendar

### Version with bug

7.0.101

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

There is no apparent workaround for this issue as the permissions are consistently returning as "denied" without the ability to prompt the user for access.

### Relevant log output

```shell
No exceptions or errors are thrown; instead, the methods consistently return "denied" status on iOS.
```

**Comment by JohnHDev** [comment]
iOS doesn't support that, if a user denies permission the app cannot request permission again. The user can either delete and reinstall the app, which will allow them to be asked again, or they manually go into settings to change the permission.

**Comment by vikher** [comment]
> iOS doesn't support that, if a user denies permission the app cannot request permission again. The user can either delete and reinstall the app, which will allow them to be asked again, or they manually go into settings to change the permission.

even upon reinstalling the app, the permission status consistently remains denied without prompting the user with the permission request popup

**Comment by jfversluis** [comment]
Yeah Apple changed the EventKit permissions and APIs.

While we are working on a fix, please refer to [this documentation](https://learn.microsoft.com/dotnet/maui/platform-integration/appmodel/permissions?tabs=android#extending-permissions) to help yourself and extended the Essentials Permissions APIs.

An example can be seen [here](https://github.com/jfversluis/Plugin.Maui.CalendarStore/pull/46/files).
