### ISSUE TITLE
[Testing] Matrix tests are failing consistency (sometimes) on CI

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#18735]
### Description

Currently the Matrix tests are failing frequently in CI

https://tfsprodcus3.visualstudio.com/Ad0adf05a-e7d7-4b65-96fe-3f3884d42038/public/_TestManagement/Runs?runId=2283178&_a=resultQuery

![image](https://github.com/dotnet/maui/assets/5375137/172a2f7b-afa6-4d93-9f71-4857334d621e)

**Comment by rmarinho** [comment]
these where disable and need to be enable again

**Comment by mattleibow** [comment]
They failied again, but we shall see if it is less often. I might split them into separate test classes and see if that helps. But it has to be something else at this point... Or maybe the test is shomehow bad...
