### ISSUE TITLE
BoxView won't render inside Frame on iOS

### ISSUE THREAD

**Issue by derlidio** [dotnet/maui#18746]
### Description

This is a weird one. A BoxView won't render if it's inside a Frame. Happens on iOS. Tested on 16.4 and 17. Do not happen on Android and Catalyst. Not tested on Windows.

Microsoft.iOS - 17.0.8478
Microsoft.NETCore.App - 8.0.0
Microsoft.Extensions.Logging. Debug - 8.0.0
Microsoft.Maui.Controls - 8.0.3
Microsoft.Maui.Controls.Compatibility - 8.0.3

### Steps to Reproduce

1. Clone the attached repo
2. Build and run on iOS Simulator

The page should show two red BoxView with a text overlay (composed on a Grid). The one outside the Frame will render OK. The one inside the Frame will not render.

### Link to public reproduction project repository

https://github.com/derlidio/FrameBoxBug.git

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17 + iOS 16.4

**Comment by drasticactions** [comment]
As a workaround, you could potentially switch your use of `Frame` and/or `BoxView` with Border. Border doesn't have a predefined style as with Frame, but you could replicate it with Border.

**Comment by derlidio** [comment]
@drasticactions Thanks for the tip. Border works fine and performs better!

**Comment by derlidio** [comment]
@drasticactions Uh-oh! Think I found a similar problem with Border. It will not render inside a Frame, but this time on Android! Opened another issue [here](https://github.com/dotnet/maui/issues/18755).

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). Repro on iOS 17.0, not repro on Windows 11, Android 14.0-API34 and MacCatalyst with below Project:
[FrameBoxBug.zip](https://github.com/dotnet/maui/files/13544388/FrameBoxBug.zip)

**Comment by MSicc** [comment]
I have the same issue. BoxView inside of a Frame does not render, until I explicitly set its WidthRequest. Which is useless, because I have to write a whole bunch of code just to calculate the correct value for the request.

**Comment by NXDMN** [comment]
> I have the same issue. BoxView inside of a Frame does not render, until I explicitly set its WidthRequest. Which is useless, because I have to write a whole bunch of code just to calculate the correct value for the request. Tested with latest packages (8.0.40).

Same happen to me but if i use `Color` property of `BoxView` instead of `BackgroundColor` then problem solved

**Comment by jfversluis** [comment]
Seeing that Frame is officially deprecated as of .NET 9, I don't think we will be working on this anymore. Also its a bit older by now, so maybe its even resolved in current versions 🤞
