### ISSUE TITLE
The text of the buttons of an Alert is not displayed correctly in windows.

### ISSUE THREAD

**Issue by Victor-Porter** [dotnet/maui#18759]
### Description

When I initialise the application in Windows and launch a displayAlert, it displays correctly.
But if I change the theme manually without stopping the application, the displayAlert is no longer displayed correctly.

I attach images of the error.

**Switch from light mode to dark mode:**
![image](https://github.com/dotnet/maui/assets/137196565/8d95590e-6290-499b-bed8-f1dfa047cef6)

**Switch from dark mode to light mode:**
![image](https://github.com/dotnet/maui/assets/137196565/948f1429-149f-4c66-b979-21df476596eb)

### Steps to Reproduce

1. Create a new MAUI project.
2. Change the function `OnCounterClicked` content on `MainPage.xaml.cs` to open an Alert (by displayAlert function).
3. Launch the application.
4. Click the button to open de Alert (It displays correctly).
5. Change the Windows theme manually (Settings > Personalization > Themes).
6. Click the button again to open the alert (displayed incorrectly).

### Link to public reproduction project repository

[Link to the repository](https://github.com/MADSENSE/MADSENSE.MAUI.Sample.App/tree/alert-textColor-wrong)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

I couldn't find anything.

**Comment by AdrLeon** [comment]
+1

**Comment by heikow10** [comment]
+1

**Comment by japarson** [comment]
@Victor-Porter Are you still able to reproduce this issue with the latest version of .NET? I'm not seeing anything out of the ordinary when switching between light/dark mode.

## Dark
![image](https://github.com/dotnet/maui/assets/59936622/afe28bf5-1a43-4d1a-8079-4747b84241f2)

## Light
![image](https://github.com/dotnet/maui/assets/59936622/5cf69675-847d-4998-ac93-bfdc5da78c2f)

**Comment by Victor-Porter** [comment]
I can't reproduce it, @japarson. So, I close the bug. 😎​

**Comment by Victor-Porter** [comment]
I can't reproduce it, @japarson. So, I close the bug. 😎​
