### ISSUE TITLE
.NET 8 MAUI Toolbar Transparency and Disappearance Issue

### ISSUE THREAD

**Issue by doriangh** [dotnet/maui#18764]
### Description

When upgrading a .NET MAUI application from .NET 7 to .NET 8, the toolbar behavior changes unexpectedly. In .NET 7, the toolbar correctly displays the app's principal color. However, in .NET 8, the toolbar becomes transparent, and the text turns light gray. Additionally, in my specific application, the toolbar completely disappeared post-upgrade.

### Steps to Reproduce

1. Create a new .NET MAUI app using .NET 7
2. Create a second page, set the MainPage as new NavigationPage(new MainPage());
3. Open app and observe toolbar
4. Upgrade app to .NET 8
5. Launch and observe toolbar

### Version with bug

8.0.0

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

### Did you find any workaround?

Using the ToolbarHandler to change the background works. However it has no effect on my other app (even though it does reach)

**Comment by PureWeen** [comment]
@doriangh I think this is caused by the styles now being applied correctly in NET8


If you delete these styles from the `Styles.xaml` file then it uses the default android material colors. 

Though I do think we need to pick better defaults here. 

```XAML
    <Style TargetType="NavigationPage">
        <Setter Property="BarBackgroundColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource OffBlack}}" />
        <Setter Property="BarTextColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource White}}" />
        <Setter Property="IconColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource White}}" />
    </Style>
```

**Comment by doriangh** [comment]
That is true, removing those did have the behavior that .net 7 had. However, without changing anything, my app which had a toolbar in .net 7, suddenly doesn't have one. I quickly created two apps (one with .net 7 and one with .net 8) to get an explanation for the issue, and when I saw that there's no toolbar, I opened the ticket. Though the styles were at fault in the demo app, I still cannot seem to get the toolbar in my application. It just doesn't come up. In the ToolbarHandler, if I append to mapping the VirtualView as IsVisible = true, it does show up, but does not have the correct style (from the common styles.xaml file). TitleViews don't seem to appear as well. 
 I'll try to pinpoint the issue.

**Comment by doriangh** [comment]
@PureWeen I've found a way to reproduce the issue. My app uses absolute navigation, and that's where the issue is.
Here's a repo with two solutions, one with .NET 7, one with .NET 8. I have a flyout page as the MainPage, where it has defined as the Detail a NavigationPage, with the MainPage as the content. In the constructor of MainPage I've hidden the NavigationBar. In the constructor of the SecondPage I've set the NavigationBar to visible.
When I replace the Detail of the Flyout (absolute navigation to second page), the NavigationBar comes up in .NET7, but is still hidden in .NET8.

Here's the repo: https://github.com/doriangh/Maui-Android-Toolbar-Issue/

**Comment by doriangh** [comment]
@PureWeen I can confirm that the issue is solved using the latest nightly build. I am also glad to see that one other issue I had, regarding long titles in navigation pages, where the text would be truncated to only 3 letters on android, is also fixed.
