### ISSUE TITLE
NullReferenceException on MemoryMarshal.TryGetArray (iOS only)

### ISSUE THREAD

**Issue by damiand2** [dotnet/maui#18761]
### Description

On production environment (Release, Link Framework SDK only, LLVM on, no concurrent GC) only on iOS devices i get sporadic crashes with sample callstacks like below:
`
System.SpanHelpers.Fill[T_CHAR](T_CHAR& , UIntPtr , T_CHAR )
System.String.PadRight(Int32 , Char )
XXX.JwtTokenParser.ParseToken(String accessToken)
`

`
System.Runtime.InteropServices.MemoryMarshal.TryGetArray[T_BYTE](ReadOnlyMemory``1 , ArraySegment``1& )
System.IO.Stream.ReadAsync(Memory``1 , CancellationToken )
System.IO.Stream.<CopyToAsync>g__Core|27_0(Stream , Stream , Int32 , CancellationToken )
System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task , MemoryStream )
System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
`
No such errors on Android version

### Steps to Reproduce

Cannnot reproduce locally

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

no

**Comment by drasticactions** [comment]
If you could create an example repro of this, that would help us debug it. Most likely this will be a [dotnet runtime](https://github.com/dotnet/runtime) issue.
