### ISSUE TITLE
iOS ScrollView stops working when keyboard is open

### ISSUE THREAD

**Issue by jeryllei** [dotnet/maui#18776]
### Description

On an iPhone, opening the keyboard when tapping on an entry box causes the keyboard to hide the content on the bottom of the page and results in the scroll view stop working. Seems to be the same as #15159 but still an issue on Maui 7.0.96 for iOS, works fine on Android.

![MicrosoftTeams-image (3)](https://github.com/dotnet/maui/assets/70560506/99cc710a-e35a-4466-adb7-91f6a6ae3f7d)
![MicrosoftTeams-image (2)](https://github.com/dotnet/maui/assets/70560506/6a73b32a-5d99-49b5-aa80-b9074ceeee69)

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4, iOS 17.1.1

### Did you find any workaround?

Current using this: https://github.com/PureWeen/ShanedlerSamples

but it still results in the scrolling not working if the user accidentally scrolls the page while focused on an entry box, requiring them to close the keyboard and reopen it.

**Comment by PureWeen** [comment]
@jeryllei I need to release a new version of those Samples that disable with net8. 

You should be able to stop using those workarounds for net8

All the fixes in ShanedlerSamples should already be in net8
