### ISSUE TITLE
[WinUI 3] Windows App Title Bar Buttons Have Button Shadows in .NET8 after project upgrade from .NET7

### ISSUE THREAD

**Issue by michaelrinderle** [dotnet/maui#18773]
### Description

We just upgraded our application to .NET 8 yesterday. When updating our project from .NET 7, we noticed a bug in our app title bar where the minimize, maximize, and close buttons have a shadow in WinUI3. 

![Screenshot 2023-11-15 160537](https://github.com/dotnet/maui/assets/11905488/3c2e53f4-87c3-4d53-88bb-2568fea9d591)

We were currently using a workaround for [#7123](https://github.com/dotnet/maui/issues/7123) in our Windows App.xaml file but when we move from our login page to our AppShell, the flyout icon goes missing so we have to remove it and lose content into titlebar extending. 

```xml
<DataTemplate x:Key="MauiAppTitleBarContainerTemplate">
  <Grid HorizontalAlignment="Stretch">
      <ContentControl
      Grid.Column="4"
      IsTabStop="False"
      HorizontalContentAlignment="Stretch"
      VerticalContentAlignment="Stretch"
      x:Name="AppTitleBarContentControl">
      </ContentControl>
  </Grid>
</DataTemplate>
```

The only other thing that we thought could be affecting this behavior is the window handler mapping:

```csharp
WindowHandler.Mapper.AppendToMapping(nameof(IWindow), (handler, view) =>
{
    if (view.Handler != null)
        ((MauiWinUIWindow)view.Handler.PlatformView)!.ExtendsContentIntoTitleBar = true;
});
```

However, removing or adding this has no effect.

We did not see this behavior with our .NET7 version of our app before the upgrade. We even created a new .NET8 Maui app and added our resources and dependencies to no avail. 

### Steps to Reproduce

1. Upgrade .NET7 .NET MAUI app to .NET8

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

Remove all code that references extending content into Title Bar in WinUI3.

**Comment by PureWeen** [comment]
@michaelrinderle if I understand your comments correctly you've been unable to reproduce this in a standalone app?

**Comment by michaelrinderle** [comment]
I was just able to reproduce the duplicate buttons on a new blank app.  It has something to do with extending the content into title bar in WinUI3 from MauiProgram.cs. Removing the ConfigureLifeCycleEvents extension method or commenting out the ExtendsContentIntoTitleBar property change fixed the issue. 

```csharp
public static nint Hwnd;

public static MauiApp CreateMauiApp()
{
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .ConfigureLifecycleEvents(lifecycle =>
            {
#if WINDOWS
                lifecycle.AddWindows(windows =>
                {
                    windows.OnWindowCreated(xamlWindow =>
                    {
                        var window = (MauiWinUIWindow)xamlWindow;
                        Hwnd = window!.WindowHandle;
                        // window.ExtendsContentIntoTitleBar = true;
                    });
                });
#endif
            });
```

The following also causes the bug in are App.xaml.cs file.

```csharp
#if WINDOWS
        WindowHandler.Mapper.AppendToMapping(nameof(IWindow), (handler, view) =>
        {
            if (view.Handler != null)
                ((MauiWinUIWindow)view.Handler.PlatformView)!.ExtendsContentIntoTitleBar = true;
        });
#endif
```
However, using the workaround in [#7123](https://github.com/dotnet/maui/issues/7123), I haven't been able to figure out why it doesn't work anymore as it hides the AppShell flyout button in our project, and/or doesn't extend content in a blank application.

**Comment by wozpren** [comment]
Same issues

**Comment by J0nathan550** [comment]
> @michaelrinderle if I understand your comments correctly you've been unable to reproduce this in a standalone app?

Can you tell how to modify the title bar of .net maui window?

**Comment by mikebm** [comment]
Was happening to me on a brand new maui app in VS 17.8 with .net 8. Removing the following fixed it:
```
           lifecycle.AddWindows(windows => windows.OnWindowCreated((del) => {
               del.ExtendsContentIntoTitleBar = true;
           }));
```

**Comment by J0nathan550** [comment]
> del.ExtendsContentIntoTitleBar = true;

Do you know how to modify the titlebar?

**Comment by mikebm** [comment]
> > del.ExtendsContentIntoTitleBar = true;
> 
> Do you know how to modify the titlebar?

nope. Super new to Maui. Sorry.

**Comment by Foda** [comment]
`ExtendsContentIntoTitleBar` is set to `true` by default so that we can draw our custom toolbar in Windows. You shouldn't need to set that value in .NET 8.


> > del.ExtendsContentIntoTitleBar = true;
> 
> Do you know how to modify the titlebar?

@J0nathan550  Making a custom Titlebar is easy. Just create a new `DataTemplate` with the name `MauiAppTitleBarTemplate` in your `Windows\App.xaml` file like this:

```xaml
<maui:MauiWinUIApplication
    x:Class="Maui.Controls.Sample.Platform.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:maui="using:Microsoft.Maui"
    xmlns:local="using:Maui.Controls.Sample.Platform">
    <Application.Resources>

        <DataTemplate x:Key="MauiAppTitleBarTemplate">
            <Border
                Canvas.ZIndex="1" 
                VerticalAlignment="Stretch"
                Margin="0,0,0,0">
                <TextBlock 
                    VerticalAlignment="Center"
                    HorizontalAlignment="Center"
                    Text="Hello World" 
                    FontWeight="Bold"/>
            </Border>
        </DataTemplate>

    </Application.Resources>
</maui:MauiWinUIApplication>
```

<img width="445" alt="image" src="https://github.com/dotnet/maui/assets/890772/fd4b391d-450c-4109-b5ab-ceaca75aab0b">

**Comment by J0nathan550** [comment]
> `ExtendsContentIntoTitleBar` is set to `true` by default so that we can draw our custom toolbar in Windows. You shouldn't need to set that value in .NET 8.
> 
> > > del.ExtendsContentIntoTitleBar = true;
> > 
> > 
> > Do you know how to modify the titlebar?
> 
> @J0nathan550 Making a custom Titlebar is easy. Just create a new `DataTemplate` with the name `MauiAppTitleBarTemplate` in your `Windows\App.xaml` file like this:
> 
> ```
> <maui:MauiWinUIApplication
>     x:Class="Maui.Controls.Sample.Platform.App"
>     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>     xmlns:maui="using:Microsoft.Maui"
>     xmlns:local="using:Maui.Controls.Sample.Platform">
>     <Application.Resources>
> 
>         <DataTemplate x:Key="MauiAppTitleBarTemplate">
>             <Border
>                 Canvas.ZIndex="1" 
>                 VerticalAlignment="Stretch"
>                 Margin="0,0,0,0">
>                 <TextBlock 
>                     VerticalAlignment="Center"
>                     HorizontalAlignment="Center"
>                     Text="Hello World" 
>                     FontWeight="Bold"/>
>             </Border>
>         </DataTemplate>
> 
>     </Application.Resources>
> </maui:MauiWinUIApplication>
> ```
> 
> <img alt="image" width="445" src="https://user-images.githubusercontent.com/890772/283622278-fd4b391d-450c-4109-b5ab-ceaca75aab0b.png">

It is really working, but the intellisense gives me an error when in your code.

**Comment by J0nathan550** [comment]
> > `ExtendsContentIntoTitleBar` is set to `true` by default so that we can draw our custom toolbar in Windows. You shouldn't need to set that value in .NET 8.
> > > > del.ExtendsContentIntoTitleBar = true;
> > > 
> > > 
> > > Do you know how to modify the titlebar?
> > 
> > 
> > @J0nathan550 Making a custom Titlebar is easy. Just create a new `DataTemplate` with the name `MauiAppTitleBarTemplate` in your `Windows\App.xaml` file like this:
> > ```
> > <maui:MauiWinUIApplication
> >     x:Class="Maui.Controls.Sample.Platform.App"
> >     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
> >     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
> >     xmlns:maui="using:Microsoft.Maui"
> >     xmlns:local="using:Maui.Controls.Sample.Platform">
> >     <Application.Resources>
> > 
> >         <DataTemplate x:Key="MauiAppTitleBarTemplate">
> >             <Border
> >                 Canvas.ZIndex="1" 
> >                 VerticalAlignment="Stretch"
> >                 Margin="0,0,0,0">
> >                 <TextBlock 
> >                     VerticalAlignment="Center"
> >                     HorizontalAlignment="Center"
> >                     Text="Hello World" 
> >                     FontWeight="Bold"/>
> >             </Border>
> >         </DataTemplate>
> > 
> >     </Application.Resources>
> > </maui:MauiWinUIApplication>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="445" src="https://user-images.githubusercontent.com/890772/283622278-fd4b391d-450c-4109-b5ab-ceaca75aab0b.png">
> 
> It is really working, but the intellisense gives me fake error when i write your code. ![image](https://user-images.githubusercontent.com/88881607/283624398-74eada7c-79c6-4c25-a4ea-2d6478d7b81b.png) ![image](https://user-images.githubusercontent.com/88881607/283624450-b61ad5f0-5237-4a17-a8b9-7ec4429177c1.png)

Nevermind, fixed. Problem was that inside of Visual Studio I did not select Windows dependency in here:
![image](https://github.com/dotnet/maui/assets/88881607/b5483f83-7885-4857-9089-eb30258c16e3)

**Comment by J0nathan550** [comment]
But question remains, I cannot change the title color, how can I do that? 😄

**Comment by J0nathan550** [comment]
Also find out, by using Grid. Now the question remains how to change the color for the Flyout button 😄 
![image](https://github.com/dotnet/maui/assets/88881607/47e30b69-39c3-45fd-8e34-6bacc9c7d2e0)

**Comment by Foda** [comment]
> But question remains, I cannot change the title color, how can I do that? 😄

Looks like you figured out a work-around, but we don't currently have an easy way to set this. Right now, we use the Windows accent color rules and set it to the accent color (if the user enabled the setting) or just transparent.

**Comment by J0nathan550** [comment]
> > But question remains, I cannot change the title color, how can I do that? 😄
> 
> Looks like you figured out a work-around, but we don't currently have an easy way to set this. Right now, we use the Windows accent color rules and set it to the accent color (if the user enabled the setting) or just transparent.

Now I just need to find out how to change atleast the transparent color of burger icon, and I will be satisfied. By the way how did you find out about this template? Where it is written in Docs?

**Comment by Foda** [comment]
> > > But question remains, I cannot change the title color, how can I do that? 😄
> > 
> > 
> > Looks like you figured out a work-around, but we don't currently have an easy way to set this. Right now, we use the Windows accent color rules and set it to the accent color (if the user enabled the setting) or just transparent.
> 
> Now I just need to find out how to change atleast the transparent color of burger icon, and I will be satisfied. By the way how did you find out about this template? Where it is written in Docs?

I've worked on the code so I'm familiar with it :) but it's not very well documented.

**Comment by J0nathan550** [comment]
> > > > But question remains, I cannot change the title color, how can I do that? 😄
> > > 
> > > 
> > > Looks like you figured out a work-around, but we don't currently have an easy way to set this. Right now, we use the Windows accent color rules and set it to the accent color (if the user enabled the setting) or just transparent.
> > 
> > 
> > Now I just need to find out how to change atleast the transparent color of burger icon, and I will be satisfied. By the way how did you find out about this template? Where it is written in Docs?
> 
> I've worked on the code so I'm familiar with it :) but it's not very well documented.

This is how it looks with help of enabled flyout, looks sick!
![image](https://github.com/dotnet/maui/assets/88881607/7ec47e31-ee5b-43b2-912d-2927bf482518)

**Comment by J0nathan550** [comment]
> > But question remains, I cannot change the title color, how can I do that? 😄
> 
> Looks like you figured out a work-around, but we don't currently have an easy way to set this. Right now, we use the Windows accent color rules and set it to the accent color (if the user enabled the setting) or just transparent.

I hope that later, the dotnet team will do the ability to change the title bar colors and everything as default setting. This must have feature.

**Comment by michaelrinderle** [comment]
None of these fixes fix the underlying issue; the ability to extend content based on your view. Our app uses ShellView to put content into our top bar on windows via extending content to title bar. Your workaround just hardcodes a textblock text into the title bar. This is a bug that needs to be fixed as the documented way to extend content into the title bar is through the lifecycle extension method: 

```csharp

public static nint Hwnd;

public static MauiApp CreateMauiApp()
{
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .ConfigureLifecycleEvents(lifecycle =>
            {
#if WINDOWS
                lifecycle.AddWindows(windows =>
                {
                    windows.OnWindowCreated(xamlWindow =>
                    {
                        var window = (MauiWinUIWindow)xamlWindow;
                        Hwnd = window!.WindowHandle;
                        // window.ExtendsContentIntoTitleBar = true;
                    });
                });
#endif
            });

``` 

or by mapping:

```csharp 

WindowHandler.Mapper.AppendToMapping(nameof(IWindow), (handler, view) =>
{
    if (view.Handler != null)
        ((MauiWinUIWindow)view.Handler.PlatformView)!.ExtendsContentIntoTitleBar = true;
});


```

**Comment by michaelrinderle** [comment]
@Foda Where is there documentation that ExtendsContentIntoTitle bar is set to ```true```? 

The only thing that's worked to push page content into the title bar is the workaround for [#7123](https://github.com/dotnet/maui/issues/7123). 

```xml
<DataTemplate x:Key="MauiAppTitleBarContainerTemplate">
  <Grid HorizontalAlignment="Stretch">
      <ContentControl
      Grid.Column="4"
      IsTabStop="False"
      HorizontalContentAlignment="Stretch"
      VerticalContentAlignment="Stretch"
      x:Name="AppTitleBarContentControl">
      </ContentControl>
  </Grid>
</DataTemplate>
```

But the AppShell flyout button disappears on window resize.

**Comment by Foda** [comment]
@michaelrinderle Here's where we set `ExtendsContentIntoTitleBar = true;`: https://github.com/dotnet/maui/blob/77fdceffeda9761e467d52f2e33afb348ce97545/src/Core/src/Platform/Windows/MauiWinUIWindow.cs#L45

Also, could you provide a little sample of the previous behavior/what it used to look like so I can investigate further? Or an example of what you're trying to achieve?

For some context: the title bar is a bit odd on Windows since it's the only platform with a "real" title bar you can customize. Currently, we implement our own custom title bar on Windows so that we can show the navigation view hide/show button and the navigation page back button. We also provide a template (`MauiAppTitleBarTemplate`) so that custom content can be placed there.

So... why does `Shell.TitleView` not get placed into the title bar? Mostly it's due to platform consistency: we want `Shell.TitleView` to have a similar behavior on each platform and appear at the top of the page. Since we use [NaviationView](https://learn.microsoft.com/en-us/windows/apps/design/controls/navigationview) as the backing control on WinUI, this means we put that content at the top of the page:

<img width="648" alt="image" src="https://github.com/dotnet/maui/assets/890772/751fde42-5510-4ae7-9b5d-f096261bba4b">


In the next release we hope to provide APIs to make title bar customization more straight-forward and provide better examples :)

**Comment by J0nathan550** [comment]
> @michaelrinderle Here's where we set `ExtendsContentIntoTitleBar = true;`:
> 
> https://github.com/dotnet/maui/blob/77fdceffeda9761e467d52f2e33afb348ce97545/src/Core/src/Platform/Windows/MauiWinUIWindow.cs#L45
> 
> Also, could you provide a little sample of the previous behavior/what it used to look like so I can investigate further? Or an example of what you're trying to achieve?
> 
> For some context: the title bar is a bit odd on Windows since it's the only platform with a "real" title bar you can customize. Currently, we implement our own custom title bar on Windows so that we can show the navigation view hide/show button and the navigation page back button. We also provide a template (`MauiAppTitleBarTemplate`) so that custom content can be placed there.
> 
> So... why does `Shell.TitleView` not get placed into the title bar? Mostly it's due to platform consistency: we want `Shell.TitleView` to have a similar behavior on each platform and appear at the top of the page. Since we use [NaviationView](https://learn.microsoft.com/en-us/windows/apps/design/controls/navigationview) as the backing control on WinUI, this means we put that content at the top of the page:
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/890772/283901831-751fde42-5510-4ae7-9b5d-f096261bba4b.png">
> In the next release we hope to provide APIs to make title bar customization more straight-forward and provide better examples :)

Look at this video I created myself, that what I was wanted to modify all of the time. 
Only thing would be appriciated is how to change the Panel.ZIndex (WPF fellas hello) of elements in title bar.
Because when you place something in there it is visible but not interactable because of the title bar event. 
https://youtu.be/piwh7bhQr0w?si=7sHsLl1TI2YSSmoW

**Comment by mhrastegari** [comment]
> The only thing that's worked to push page content into the title bar is the workaround for [#7123](https://github.com/dotnet/maui/issues/7123).
> 
> ```
> <DataTemplate x:Key="MauiAppTitleBarContainerTemplate">
>   <Grid HorizontalAlignment="Stretch">
>       <ContentControl
>       Grid.Column="4"
>       IsTabStop="False"
>       HorizontalContentAlignment="Stretch"
>       VerticalContentAlignment="Stretch"
>       x:Name="AppTitleBarContentControl">
>       </ContentControl>
>   </Grid>
> </DataTemplate>
> ```
> 
> But the AppShell flyout button disappears on window resize, then pushes content into the title bar in .NET8.
> 
> This _just_ worked in .NET7. :/

Same happening to us! specially the window resize part!

**Comment by J0nathan550** [comment]
> > `ExtendsContentIntoTitleBar` is set to `true` by default so that we can draw our custom toolbar in Windows. You shouldn't need to set that value in .NET 8.
> > > > del.ExtendsContentIntoTitleBar = true;
> > > 
> > > 
> > > Do you know how to modify the titlebar?
> > 
> > 
> > @J0nathan550 Making a custom Titlebar is easy. Just create a new `DataTemplate` with the name `MauiAppTitleBarTemplate` in your `Windows\App.xaml` file like this:
> > ```
> > <maui:MauiWinUIApplication
> >     x:Class="Maui.Controls.Sample.Platform.App"
> >     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
> >     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
> >     xmlns:maui="using:Microsoft.Maui"
> >     xmlns:local="using:Maui.Controls.Sample.Platform">
> >     <Application.Resources>
> > 
> >         <DataTemplate x:Key="MauiAppTitleBarTemplate">
> >             <Border
> >                 Canvas.ZIndex="1" 
> >                 VerticalAlignment="Stretch"
> >                 Margin="0,0,0,0">
> >                 <TextBlock 
> >                     VerticalAlignment="Center"
> >                     HorizontalAlignment="Center"
> >                     Text="Hello World" 
> >                     FontWeight="Bold"/>
> >             </Border>
> >         </DataTemplate>
> > 
> >     </Application.Resources>
> > </maui:MauiWinUIApplication>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="445" src="https://private-user-images.githubusercontent.com/890772/283622278-fd4b391d-450c-4109-b5ab-ceaca75aab0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU4MjgsIm5iZiI6MTcwNTU4NTUyOCwicGF0aCI6Ii84OTA3NzIvMjgzNjIyMjc4LWZkNGIzOTFkLTQ1MGMtNDEwOS1iNWFiLWNlYWNhNzVhYWIwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxMzQ1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDZhZmNjM2FmNGVhOWI1MDI0NmNkMTAzM2FmMDdlMWY3NjUwOTIxMWM3Yzg2MzdkZjBiNmRhYWZlNmVlZjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I2eYR6jTSHhB8DETBWBW_Jte6K5LVSaF5niIpDY4xNo">
> 
> Thanks @Foda, I have managed to create a custom toolbar from your example as I was trying to make it dark blue to match the company theme but then the window controls (minimize/maximise/close) are black so cannot be seen until hovered over. Would you mind sharing how to make the text on them white? I'm hoping there is an easy way.
> 
> I spent quite a while trying different things but part of the issue is code samples I am finding are not for Net MAUI apps but WinUI or WPF so are not working. One workaround would be to set the dark theme in Windows but I don't want to have to rely on that. Thanks for the help. This is the last thing I need to solve!

WPF has awesome library called [ModernWPF](https://github.com/Kinnara/ModernWpf) it allows users to manage the title bars and everything related to Win 10 UI. The only thing that lacks this library is Acrylic Brush support, but I'm anyway satisfied with that. Because it works on any Windows platforms.

**Comment by robinwilson16** [comment]
@J0nathan550 Thanks for the info on that but does it work with NET MAUI too?
The instructions for installing seem to only relate to WPF and adding code to MainWindow.xaml which does not exist in MAUI.
Hopefully I can avoid additional 3rd party dependencies as it's just to change the font colour of the window buttons which I am hoping there is a built in method for.

**Comment by robinwilson16** [comment]
For anyone looking I have found a way to do it:

Add this to the `Platforms/Windows/App.xaml.cs` after `this.InitializeComponent();`.
I also added lines for disabling resizing and maximising in case you want to control this:

```
Microsoft.Maui.Handlers.WindowHandler.Mapper.AppendToMapping(nameof(IWindow), (handler, view) =>
{
    var nativeWindow = handler.PlatformView;
    nativeWindow.Activate();
    IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(nativeWindow);
    WindowId windowId = Win32Interop.GetWindowIdFromWindow(hWnd);
    AppWindow appWindow = AppWindow.GetFromWindowId(windowId);

    //Make window buttons white
    appWindow.TitleBar.ButtonForegroundColor = Colors.White;

    //Disable resize and maximise
    var presenter = appWindow.Presenter as OverlappedPresenter;
    presenter.IsResizable = false;
    presenter.IsMaximizable = false;
});
```

**Comment by J0nathan550** [comment]
> For anyone looking I have found a way to do it:
> 
> Add this to the `Platforms/Windows/App.xaml.cs` after `this.InitializeComponent();`. I also added lines for disabling resizing and maximising in case you want to control this:
> 
> ```
> Microsoft.Maui.Handlers.WindowHandler.Mapper.AppendToMapping(nameof(IWindow), (handler, view) =>
> {
>     var nativeWindow = handler.PlatformView;
>     nativeWindow.Activate();
>     IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(nativeWindow);
>     WindowId windowId = Win32Interop.GetWindowIdFromWindow(hWnd);
>     AppWindow appWindow = AppWindow.GetFromWindowId(windowId);
> 
>     //Make window button text white
>     appWindow.TitleBar.ButtonForegroundColor = Colors.White;
> 
>     //Disable resize and maximise
>     var presenter = appWindow.Presenter as OverlappedPresenter;
>     presenter.IsResizable = false;
>     presenter.IsMaximizable = false;
> });
> ```

This is perfect! much love!

**Comment by QianaJiao** [comment]
Verified this issue was not repro on Visual Studio Enterprise 17.10 Preview 2.0; .NET 8.0.202; Maui 8.0.7.
