### ISSUE TITLE
[Windows] When the DPI is adjusted to non-100%, drawing strings with GraphicsView creates jitter

### ISSUE THREAD

**Issue by y673893131** [dotnet/maui#18783]
### Description

I want to customize the control according to GraphicsView, refresh based on mouse movements, if the DPI is 100% there is no jitter 

### Steps to Reproduce

This issue reproduce is very easy.
Inherit from the GraphicsView & IDrawable class, bind MoveHoverInteraction event and trigger Invalidate(), then in the IDrawable call the cavans.Drawstriing(the font  size set to 10).
when move the mouse on the view, the string will jitter.

### Version with bug

7.0.100

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows 22H2 19045.3570

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.1 (8.0.40 & 8.0.21). Not repro on Windows platform.
