### ISSUE TITLE
[Enhancement] Add IsVisible to MenuItem 

### ISSUE THREAD

**Issue by Auto72** [dotnet/maui#18792]
### Description

MenuItems in the Shell should have a public .IsVisible property available and also a name or a tag property to be able identify them - and not only by the .Text property - during the loop of Shell items.

```cs
        if (Application.Current?.MainPage is not Shell shell) { return; }
        foreach (var item in shell.Items)
        {
            if (item.GetType().ToString().EqualsIgnoreCase("Microsoft.Maui.Controls.MenuShellItem")) 
            {
                if (item.Tag = "Item_I_want") { item.IsVisible = false; }                 
            }
        }
```

In this way we can easily hide or show items according to the need of the App.

### Public API Changes

Add the .IsVisible and .Tag property to MenulItem. 

### Intended Use-Case

Be able to hide of show MenulItem in the Shell depending on the page the user is on or depending on the actions the user performs. For example if it is connected or not to something, you can show more menu items and hide some others.

**Comment by Auto72** [comment]
I just realized that the property to show or hide the menu is already present and it is called .FlyoutItemIsVisible.
So what I miss is how to identify the MenuItem in the loop by name or tag.

**Comment by Auto72** [comment]
I tried to use ClassId and x:Name, but in the loop above, ClassId is from ShellItem, not MenuItem.

<MenuItem ClassId="mnuLogout" x:Name="mnuLogout" Text="Logout" IconImageSource="logout.png"/>

Is there a way to set the ClassId of the ShellItem for MenuItem in the XAML ?

**Comment by Auto72** [comment]
Adding the menu programmatically from code and specifying the ClassId, then in the loop above the ClassId is popolated.

if (Application.Current?.MainPage is not Shell shell) { return; }
mi = new MenuItem { Text = "Logout", IconImageSource = "logout.png" };
mi.Clicked += MenuItem_Clicked;
mi.ClassId = "mnuLogout";
shell.Items.Add(mi);

**Comment by PureWeen** [comment]
related https://github.com/dotnet/maui/issues/3701

**Comment by mattleibow** [comment]
@Auto72 this issue has several feature requests as well as the fact I can't repro the ClassId issue:

<img width="724" alt="image" src="https://github.com/dotnet/maui/assets/1096616/4a970bd6-8010-4a6b-a173-2ba94e23d578">

Are you able to split this up into each feature as well as a new issue for the ClassId with a repro?

**Comment by Auto72** [comment]
I created the repo. In the source code you can find the test case with the comments.
https://github.com/dotnet/maui/issues/18792#issuecomment-1816985642

**Comment by Auto72** [comment]
In the AppShell.xaml I discovered that the property Shell.FlyoutItemIsVisible can be used to hide/show the menu at design time.

``
<MenuItem ClassId="mnuLogin" x:Name="mnuLogin" Text="Login" Clicked="MenuItem_Clicked" Shell.FlyoutItemIsVisible="True" />

**Comment by Auto72** [comment]
I found also found a solution for the loop above. Here is the working one:

```
        if (Application.Current?.MainPage is not Shell shell) { return; }

        foreach (ShellItem item in shell.Items)
        {
            Debug.WriteLine($"item.GetType(): {item.GetType()} | item.ClassId: {item.ClassId}");

            if (item is null) { continue; }

            // Is it a MenuShellItem ?
            if (item.GetType().ToString().EqualsIgnoreCase("Microsoft.Maui.Controls.MenuShellItem"))
            {
                // MenuShellItem
                Type msiType = item.GetType();
                PropertyInfo? mi = msiType.GetProperty("MenuItem");
                if (mi is null) { continue; }
                if (mi.GetValue(item) is not MenuItem m) { continue; }

                if (m.ClassId.EqualsIgnoreCase("mnuLogin")) { item.IsVisible = !isLogged; }
                if (m.ClassId.EqualsIgnoreCase("mnuLogout")) { item.IsVisible = isLogged; }
                if (m.ClassId.EqualsIgnoreCase("mnuConnect")) { item.IsVisible = !isConnected; }
                if (m.ClassId.EqualsIgnoreCase("mnuDisconnect")) { item.IsVisible = isConnected; }
                if (m.ClassId.EqualsIgnoreCase("mnuSettings")) { item.IsVisible = isAdmin; }
            }
        }

```
