### ISSUE TITLE
MAUI for .net 6 does not work anymore after updating new VisualStudio 2022|.Net8

### ISSUE THREAD

**Issue by hilmican-yuksel** [dotnet/maui#18790]
### Description

Our existing .net6.0 project does not work anymore after updates.
![Screenshot 2023-11-16 100005](https://github.com/dotnet/maui/assets/89516279/38992c36-58e7-4440-9258-5028caaf01e6)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

**Comment by mattleibow** [comment]
I do not believe .NET 6 is supported for mobile anymore. With .NET 8, the oldest version of .NET that is supported is .NET 7.

If you want to use .NET 6, you will have to pin your SDK using global.json.

Please have a look at the .NET MAUI support policy: https://dotnet.microsoft.com/en-us/platform/support/policy/maui
