### ISSUE TITLE
.NET 8 - No reference to MauiUIApplicationDelegate and ViewRenderer<,>

### ISSUE THREAD

**Issue by MLB-BIOMETRIC** [dotnet/maui#18795]
### Description

When swapping to .NET 8 there is no longer a reference to ``MauiUIApplicationDelegate`` and ``ViewRenderer<,>``.

```
The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?)
```

```
The type or namespace name 'ViewRenderer<,>' could not be found (are you missing a using directive or an assembly reference?)
```

**This is my workload verison:**
```
Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui                       8.0.3/8.0.100         SDK 8.0.100       
```

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Create an Platforms/iOS/AppDelegate.cs file
3. Create an Platforms/iOS/Program.cs file
4. Create an MauiProgram.cs file
5. Use the contents below in the files
6. Missing reference

**Excepted behavior:** Work just like .NET 7 with the reference existing
**Actual behavior:** Getting the error that the namespace name could not be found

**AppDelegate.cs**
```csharp
using Foundation;

namespace Test;

[Register("AppDelegateTests")]
public class AppDelegate : MauiUIApplicationDelegate
{
    protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
}
```

**Program.cs**
```csharp
using UIKit;

namespace Tests;

public class Program
{
    static void Main(string[] args)
    {
        UIApplication.Main(args, null, typeof(AppDelegate));
    }
}
```

**MauiProgram.cs**
```csharp
namespace Tests;

public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

		return builder.Build();
	}
}
```

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS, I was *not* able test on other platforms

### Did you find any workaround?

No workaround.

**Comment by MLB-BIOMETRIC** [comment]
Related to https://github.com/dotnet/maui/issues/18739

**Comment by wallym** [comment]
Same.  I have update to release of .net 8 and vs 2022.  I have updated my workloads.  I have deleted the bin and obj directories.  No love.

**Comment by wallym** [comment]
I decided to create a new .NET 8 project, copied all of my code in, and it seems to be working.  I hate that upgrades are so hard now, but it isn't a real killer and I'm back off and running.

**Comment by wallym** [comment]
> Same. I have update to release of .net 8 and vs 2022. I have updated my workloads. I have deleted the bin and obj directories. No love.
> 
> I get this error when compiling on windows for android.

@redth got it resolved.  Thanks.  :-)

**Comment by coderdeluxe21** [comment]
Hey guys,

I am currently on 8 RC1. Just updated to 8.0.3.

I also get this error: 

Error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Test01)

I have run sudo dotnet workload update
deleted bin and obj folder
restarte VS MAC

I am at a loss. We want to go live soon and now I am stuck.
What else can be done? @Redth, any ideas?

Thanks.
