### ISSUE TITLE
Items in a Listview header don't receive gesture events

### ISSUE THREAD

**Issue by Mirksar** [dotnet/maui#18793]
### Description

The elemets that are inside a Listview header don't receive gesture events

### Steps to Reproduce

- Create a new MAUI project
- Create a ContentPage and insert a ListView:

```xaml
    <ListView>
        <ListView.Header>
            <Image Source="dotnet_bot.png">

                <Image.GestureRecognizers>
                    <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"/>

                </Image.GestureRecognizers>
            </Image>

        </ListView.Header>

    </ListView>
```

- Add the gesture response to the code behind

```cs
    async void TapGestureRecognizer_Tapped(System.Object sender, Microsoft.Maui.Controls.TappedEventArgs e)
    {
        await DisplayAlert("Alert", "You have been alerted", "OK");
    }
```
- Run the project. When tapping the image in the header, it should appear a message, but nothing happens.

### Link to public reproduction project repository

https://github.com/Mirksar/ListviewHeader/tree/main

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

**Comment by baaaaif** [comment]
same here using the telerik ListView Control
https://feedback.telerik.com/maui/1631295-net8-listview-footer-issues

worked with 7.0.101

**Comment by PureWeen** [comment]
This is most likely because the ListView header isn't correctly being added as a logical child of the Listview

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). Repro on Windows 11, Android 14.0-API34, iOS 17.0 and MacCatalyst  with below Project:
[ListviewHeader.zip](https://github.com/dotnet/maui/files/13509134/ListviewHeader.zip)

**Comment by baaaaif** [comment]
Retested with 8.0.4-nightly.9750 - there it works. Issue seems to be gone (on my side)

**Comment by JimmyPun610** [comment]
Same issue, updated to 8.0.6

**Comment by ericbrunner** [comment]
Issue is still existing. We noticed that in context of a TabBar switch between pages that items like Button inside the ListView Header don't react to a Tap on Android platform.

When is that fixed and what workaround is suggested ?

**Comment by kubaflo** [comment]
It works in NET9. I think it should also work on the latest nightly build
<video src="https://github.com/user-attachments/assets/d8fb2233-876d-4ddb-a1b5-74fe3844cf28" width="300px"/>

```
<TabbedPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            x:Class="Maui.Controls.Sample.MainPage"
            xmlns:local="clr-namespace:Maui.Controls.Sample">
    <ContentPage Title="page1">
        <ListView>
            <ListView.Header>
                <Image Source="dotnet_bot.png">
                    <Image.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"/>
                    </Image.GestureRecognizers>
                </Image>
            </ListView.Header>
        </ListView>
    </ContentPage>

    <ContentPage Title="page2">
        <ListView>
            <ListView.Header>
                <Image Source="dotnet_bot.png">
                    <Image.GestureRecognizers>
                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"/>
                    </Image.GestureRecognizers>
                </Image>
            </ListView.Header>
        </ListView>
    </ContentPage>
</TabbedPage>
```
