### ISSUE TITLE
[Android] Entry clear button requires tap to the right of appearance

### ISSUE THREAD

**Issue by kklose23** [dotnet/maui#18803]
### Description

When an Entry has a parent with left padding, clicking the entry clear button does not work.  The button needs to be clicked to the right of its appearance.  This is only happening on Android.

### Steps to Reproduce

The following will reproduce the problem:

```
  <Border HeightRequest="45"
          Padding="15,0,0,0">
    <Entry ClearButtonVisibility="WhileEditing" />
  </Border>
```

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
possibly related https://github.com/dotnet/maui/pull/17543

**Comment by jsuarezruiz** [comment]
This issue will be fixed by https://github.com/dotnet/maui/pull/17543
