### ISSUE TITLE
[WinUI3] Cannot publish Windows MSIX when referencing class libraries and using Unit Test project workaround; 

### ISSUE THREAD

**Issue by michaelrinderle** [dotnet/maui#18818]
### Description

Our .NET MAUI app currently references .netstandard and .NET MAUI class libraries. We are currently using the following workaround so we can NUnit test our .NET MAUI application and MAUI class libraries, which works well.

``` xml
<TargetFrameworks>net8.0;net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
<OutputType Condition="'$(TargetFramework)' != 'net8.0'">Exe</OutputType>
```

```csharp
#if NET7_0_OR_GREATER && !ANDROID && !MACCATALYST && !IOS && !WINDOWS
    // workaround for unit tests in Maui https://github.com/dotnet/maui/issues/3552#issuecomment-1172606125
    public static void Main(string[] args) {}
#endif
```

We are able to publish in Android with no issue but when we use the following publishing profile to create a Window's MSIX package,

 ```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PublishDir>bin\Release\net8.0\publish\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <Platform>Any CPU</Platform>
    <Configuration>Release</Configuration>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <SelfContained>True</SelfContained>
    <PublishAppxPackage>true</PublishAppxPackage>
    <AppxPackageDir>bin\Release\net8.0-windows10.0.19041.0\win10-x64\AppPackages\</AppxPackageDir>
  </PropertyGroup>
</Project>
```
we get the following error at publish time:

```
1>------ Publish started: Project: MauiUnitTestBug, Configuration: Release Any CPU ------
1>Determining projects to restore...
1>The specified RuntimeIdentifier 'win10-x64' is not recognized. See https://aka.ms/netsdk1083 for more information.
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
========== Publish completed at 8:28 PM and took 03.018 seconds ==========
========== Package: 0 succeeded, 1 failed ===========
```

The following has been reproduced @ [https://github.com/michaelrinderle/MauiUnitTestBug](https://github.com/michaelrinderle/MauiUnitTestBug)

If we remove the following workaround, we also get the following now : 
```
Assets file 'C:\...\obj\project.assets.json' doesn't have a target for 'net8.0'. Ensure that restore has run and that you have included 'net8.0' in the TargetFrameworks for your project.
```

### Steps to Reproduce

1. Create new solution.
2. Create a new .NET 8 MAUI project.
3. Create a .NET 8 .netstandard library and reference code in .NET MAUI project.
4. Use workaround so .NET Maui project can compile to dll for unit testing.
5. Create unit test project and reference .Net Maui project code for testing.
6. Try to publish Window MSIX package in VS2022.

### Link to public reproduction project repository

https://github.com/michaelrinderle/MauiUnitTestBug

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

Setting the following config in all csproj files:
```xml 
<UseRidGraph>false</UseRidGraph>
```
Then using cli instead of VS2022 publish:

``` dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64 ```

### Relevant log output

```shell
1>------ Publish started: Project: MauiUnitTestBug, Configuration: Release Any CPU ------
1>Determining projects to restore...
1>The specified RuntimeIdentifier 'win10-x64' is not recognized. See https://aka.ms/netsdk1083 for more information.
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
========== Publish completed at 8:28 PM and took 03.018 seconds ==========
========== Package: 0 succeeded, 1 failed ===========
```

**Comment by jfversluis** [comment]
Since it does seem to work from the CLI it seems that the process itself works, but something in Visual Studio is not doing things right with this setup. Can I kindly ask you to report the issue there as per the instructions above? Thank you!

**Comment by michaelrinderle** [comment]
Sure thing. Thank you.

**Comment by e012345678** [comment]
Having the same issue. Will this be fixed so we do not need to do the workaround? We get this error while compiling in Azure DevOps Pipelines "-f:net8.0-windows10.0.19041.0 -r:win10-x64 -c:Release". Exact same code was working fine in net7.0

**Comment by greg-dickie** [comment]
I'm seeing something similar when publishing in Azure DevOps Pipelines as well.  Dotnet publish works on my Windows VM. The workaround is not working for me.  

Here's the error I'm getting:
`C:\hostedtoolcache\windows\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1047: Assets file 'D:\a\1\s\Forms.Web\Forms.Blazor.Mobile\obj\project.assets.json' doesn't have a target for 'net8.0-windows10.0.19041.0/win-x64'. Ensure that restore has run and that you have included 'net8.0-windows10.0.19041.0' in the TargetFrameworks for your project. You may also need to include 'win-x64' in your project's RuntimeIdentifiers. [D:\a\1\s\Forms.Web\Forms.Blazor.Mobile\Forms.Blazor.Mobile.csproj::TargetFramework=net8.0-windows10.0.19041.0]
`

Same pipeline was working fine in .NET 7.0.  The previous action in my pipeline is dotnet restore.

My publish action has "--no-restore" because when it tries to do a restore it fails because of my NuGet.config that includes Telerik credentials.

**Comment by e012345678** [comment]
Also tried to publish with -r:win-x64 rather than -r:win10-x64 but getting the same error, how to do this in .NET 8? (as well as added --no-self-contained)

**Comment by michaelrinderle** [comment]
> Since it does seem to work from the CLI it seems that the process itself works, but something in Visual Studio is not doing things right with this setup. Can I kindly ask you to report the issue there as per the instructions above? Thank you!

https://developercommunity.visualstudio.com/t/WinUI3MAUI-Cannot-publish-Windows-MSI/10519561

**Comment by jfversluis** [comment]
This seems moved to the right place, thank you everyone!

**Comment by CedreLo** [comment]
Any news ?
