### ISSUE TITLE
[regression/8.0.3] [Android] Button ripple effect not working

### ISSUE THREAD

**Issue by OvrBtn** [dotnet/maui#18815]
### Description

In previous .NET when you click on button it by default has this ripple effect. In .NET 8 even in empty template project it doesn't seem to work.

https://github.com/dotnet/maui/assets/76904408/8cbf9adc-e612-498d-b96d-51a335d14cca

### Steps to Reproduce

1. Create new MAUI project with framework target .NET 8
2. Click the button

Expected outcome: ripple effect
 Actual outcome: nothing is happening

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11.0 (API 30)

**Comment by jsuarezruiz** [comment]
This issue will be fixed by https://github.com/dotnet/maui/pull/17821

**Comment by PureWeen** [comment]
Duplicate of #17642
