### ISSUE TITLE
XA1018 on visual studio 2022 0 release 17.8.0

### ISSUE THREAD

**Issue by JedhaDev** [dotnet/maui#18827]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

XA1018 android manifest file does not exist as soon as the project is created

**Comment by mattleibow** [comment]
Thanks for reporting this issue. 

Does it still build? 

I believe this is a few things happening together that result in this error for a few seconds until the nugets restore.

**Comment by JedhaDev** [comment]
hello

it doesn’t builds, nugets indicates restored also at vstudio status
indicates ready

kind regards

**Comment by jfversluis** [comment]
Duplicate of #21406
