### ISSUE TITLE
[Bug] CarouselView on Android causes infinite layout loop

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1882]
### Steps to Reproduce

1. Set CarouselViewPage as the main page in the samples `MainPage = new Pages.CarouselViewPage(); //Services.GetRequiredService<Page>();`
2. Start App
3. App never loads because it's infinitely doing something

**Comment by PaulAnderson02** [comment]
@hartez  Can we expect this to be fixed in the next preview?

**Comment by hartez** [comment]
@PaulAnderson02 We'll try, but I cannot guarantee this will be fixed for the next preview.

**Comment by hartez** [comment]
We're aiming to move the CarouselView to the new architecture as part of preview 11; we're hoping to fix this as part of that effort.

**Comment by codeaphex** [comment]
@hartez Any update on the CarouselView status?

**Comment by shimingsg** [comment]
verified repro with VS  17.2.0 Preview 3.0 [32314.195.main] on Android
[MauiApp1882.zip](https://github.com/dotnet/maui/files/8249610/MauiApp1882.zip)

**Comment by Redth** [comment]
This is fixed in the upcoming RC1 release.
