### ISSUE TITLE
JsonSerializerIsReflectionEnabledByDefault breaks hot reload

### ISSUE THREAD

**Issue by jenscski** [dotnet/maui#18829]
### Description

When using `<JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>` the hot reload functionality is broken.

### Steps to Reproduce

Create new .NET Maui app, add `<JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>` to the project file.

Run and see that Hot reload never get initialized.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Relevant log output

```shell
[08:32:07]  XAML Hot Reload initializing...
[08:34:08]  Caught exception in AgentStatusChangedHandler at 317: Xamarin.HotReload.DebuggerTimeoutException: Failed to Inject Assembly

[08:34:08]  XAML Hot Reload encountered a problem and failed to start. Use Help -> Report a Problem if the issues persists.
[08:34:08]  Stopping All Hot Reload sessions due to Failed ...
[08:34:08]  (Sms.Terminal.Locker.App) Stopping a Hot Reload session due to Failed ...
[08:34:08]  Stopped Hot Reload session.
```

**Comment by mattleibow** [comment]
@drasticactions thoughts?

**Comment by drasticactions** [comment]
For XAML Hot Reload, we currently use System.Text.Json as a serialization system. The types should be cast so it's interesting that it would break on turning off reflection, but if it's breaking while initializing, it could be that the initial handshake messages sent from IDE to Device are having a problem with serialization. As VS maintains this tooling, I would move this issue to VS Feedback.

To work around it, I would enable that setting for debug mode, and turn it off for Release mode.

**Comment by jenscski** [comment]
https://developercommunity.visualstudio.com/t/JsonSerializerIsReflectionEnabledByDefau/10520812
