### ISSUE TITLE
Initially hidden StackLayout doesn't render if bound IsVisible changes

### ISSUE THREAD

**Issue by BioTurboNick** [dotnet/maui#18820]
### Description

I have a layout like this:
```
<ContentView.Resources>
    <ResourceDictionary>
        <toolkit:EnumToBoolConverter x:Key="inResultsMode">
            <toolkit:EnumToBoolConverter.TrueValues>
                <!--workaround for being unable to add just one-->
                <e:MeasurementPageMode>Results</e:MeasurementPageMode>
                <e:MeasurementPageMode>Results</e:MeasurementPageMode>
            </toolkit:EnumToBoolConverter.TrueValues>
        </toolkit:EnumToBoolConverter>
        <toolkit:EnumToBoolConverter x:Key="inEditingMode">
            <toolkit:EnumToBoolConverter.TrueValues>
                <e:MeasurementPageMode>Editing</e:MeasurementPageMode>
                <e:MeasurementPageMode>Editing</e:MeasurementPageMode>
            </toolkit:EnumToBoolConverter.TrueValues>
        </toolkit:EnumToBoolConverter>
    </ResourceDictionary>
</ContentView.Resources>
<toolkit:DockLayout>
<ScrollView>
    <VerticalStackLayout>
        <VerticalStackLayout IsVisible="{Binding PageMode, Converter={StaticResource inEditingMode}}">
            <Label Text="VSL1" />
        </VerticalStackLayout>
        <VerticalStackLayout IsVisible="{Binding PageMode, Converter={StaticResource inResultsMode}}">
            <Label Text="VSL2" />
        </VerticalStackLayout>
        <Grid>
            <Label Text="Grid" />
        </Grid>
    </VerticalStackLayout>
</ScrollView>
</toolkit:DockLayout>
```

If the PageMode is changed from Editing to Results, the first VSL disappears but the second one doesn't appear, however the space on the screen for the VSL is still reserved.

If the screen is rotated, the rendering is corrected.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.81

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

I tried switching manually with a delay using an event handler, but the control was rendered in the wrong location, as if it was the second item in the layout instead of the first.

So instead, I had to restructure it to be like this, and then the event handler + delay approach worked:
```
<toolkit:DockLayout>
<ScrollView>
    <Grid>
        <VerticalStackLayout x:Name="vsl1">
            <Label Text="VSL1" />
            <Grid>
                <Label Text="Grid" />
            </Grid>
        </VerticalStackLayout>
        <VerticalStackLayout x:Name="vsl2">
            <Label Text="VSL2" />
            <Grid>
                <Label Text="Grid" />
            </Grid>
        </VerticalStackLayout>
    </Grid>
</ScrollView>
</toolkit:DockLayout>
```

**Comment by BioTurboNick** [comment]
Hmm, that workaround doesn't work super well actually.

**Comment by BioTurboNick** [comment]
Actually doesn't need to be so nested - was also occurring for Grids as children of the root layout.

**Comment by BioTurboNick** [comment]
Uhh... okay this is more complex than I thought. It appears to be some interaction with other property changes?

**Comment by BioTurboNick** [comment]
Alright, I managed to get a minimal-ish example.

To reproduce, click "Calculate" to see the yellow and green blocks. Then click "Save" and the yellow block should be replaced by a red block; in 8.0 it just disappears. Click "Calculate" again to switch back to the yellow block.

There are some odd load-bearing lines of code. For example, the Revert button *must* be present, and it *must* be connected to the RevertCommand, which *must* use IsCommitted for its CanExecute and *must* respond to the IsCommitted property changing, and the SaveCommand *must* set IsCommitted for this to occur.

Furthermore, the PropertyChanged handler for the view model *must* be hooked up in the page, and it *must* call OnSizeAllocated in response to the PageMode changing.

7.0.81 - works: [VisibleBugMAUI7.zip](https://github.com/dotnet/maui/files/13399250/VisibleBugMAUI7.zip)
8.0.3 - doesn't work: [VisibleBugMAUI8.zip](https://github.com/dotnet/maui/files/13399251/VisibleBugMAUI8.zip)

**Comment by BioTurboNick** [comment]
So I *think* I can actually avoid the issue by omitting the OnSizeAllocated call, which was a workaround for some layout issues in 7.

So possibly this one is on me, though arguably it shouldn't be fragile in this way?

**Comment by samhouts** [comment]
@BioTurboNick Yeah, it's definitely a bummer when we fix something and then the workaround causes a worse behavior 😅. It's super tricky for us to account for those. I haven't investigated this one, but based on your investigation, do you still think there's a bug here, or does everything work as expected now that the workaround is removed? Thanks!

**Comment by BioTurboNick** [comment]
I suppose as far as I'm concerned it can be closed.
