### ISSUE TITLE
MAUI iOS: Command line to build maui ios app for iPhoneSimulator without CodeSigning key on Mac machine

### ISSUE THREAD

**Issue by muffadal53** [dotnet/maui#18836]
### Description

What is the command-line to build .net maui iOS release build on Mac machine for iPhoneSimulator without adding any CodeSigning key to keychain on mac device? I have tried with below command line but it is asking for valid Code signing key which I think should not be required for iPhone simulator:

dotnet build maui.csproj --configuration Release --no-restore -f net7.0-ios /p:verbosity=quiet /p:Platform="iPhoneSimulator"

I am getting following error:

No valid iOS code signing keys found in keychain. You need to request a codesigning certificate from https://developer.apple.com/.

Awaiting help on this. Thanks in advance.

### Steps to Reproduce

What is the command-line to build .net maui iOS release build on Mac machine for iPhoneSimulator without adding any CodeSigning key to keychain on mac device? I have tried with below command line but it is asking for valid Code signing key which I think should not be required for iPhone simulator:

`dotnet build maui.csproj --configuration Release --no-restore -f net7.0-ios /p:verbosity=quiet /p:Platform="iPhoneSimulator"`

I am getting following error:

No valid iOS code signing keys found in keychain. You need to request a codesigning certificate from https://developer.apple.com/.

I am not able to find any relevant information in MAUI documentation.

Awaiting help on this. Thanks in advance.

### Link to public reproduction project repository

N/A

### Version with bug

7.0.101

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS16

### Did you find any workaround?

N/A

### Relevant log output

```shell
No valid iOS code signing keys found in keychain. You need to request a codesigning certificate from https://developer.apple.com/.
```

**Comment by mattleibow** [comment]
@rolfbjarne is there a change in the requirement for a signing key? This is a Release build it seems.

**Comment by mattleibow** [comment]
@muffadal53 does it build in Debug at all?

**Comment by muffadal53** [comment]
> @muffadal53 does it build in Debug at all?

@mattleibow : I checked with Debug build it is the same thing that it needs code signing key. My use case is to build in Release as part of GitLab pipeline without codesigning key without generating .ipa file because generating the ".ipa" would be part of different Deployment job. And, even if I provide the code signing key in the .net maui dotnet build command it asks me for codesigning credentials on my Mac machine with a dialog which I don't want to have while building it as part of pipeline job. So, how can we avoid this part and let it do this part automatically.

In Xamarin forms this was possible without code signing key for iPhoneSimulator by following command:

`msbuild ${APP_PROJECT_DIR}/${EXE_PROJECT_NAME} /p:Configuration="Release" /p:verbosity=quiet /p:Platform="iPhoneSimulator"`

Where the "APP_PROJECT_DIR" is the project directory path and "EXE_PROJECT_NAME" is the project name of iOS project. So,  is there something similar in .Net MAUI?

Awaiting your reply. Thanks.

**Comment by xanril** [comment]
Try adding a runtime identifier as one of the build params `-r iossimulator-x64` or `-r iossimulator-arm64`

**Comment by rolfbjarne** [comment]
> Try adding a runtime identifier as one of the build params `-r iossimulator-x64` or `-r iossimulator-arm64`

Correct, this is how you build for the simulator. If this doesn't work, please add `-bl:msbuild.binlog` to the command line, and attach the resulting msbuild.binlog file.

**Comment by muffadal53** [comment]
@xanril  and @rolfbjarne : I tried as per the inputs from @xanril as per following command and and I am getting following warning and error on the pipeline output:

1. Updated command line: 

`$ dotnet build ${APP_PROJECT_DIR} --configuration Release --no-restore -f net7.0-ios -p:verbosity=quiet -r iossimulator-arm64 -p:Platform="iPhoneSimulator"`

      1. Warning: 
      
        ` warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used.`
      
      2. Error:
      
      `project doesn't have a target for 'net7.0-ios/iossimulator-arm64'. Ensure that restore has run and that you have included 
       'net7.0-ios' in the TargetFrameworks for your project. You may also need to include 'iossimulator-arm64' in your project's 
        RuntimeIdentifiers`

So, what is this error and how to resolve this? 

Thanks.

**Comment by rolfbjarne** [comment]
Try removing `--no-restore` from the command line, that should fix the error.

**Comment by muffadal53** [comment]
@rolfbjarne :  Few queries on your input of removing "--no-restore" . What was that error about? and if I am doing a dotnet restore command like `dotnet restore $SOLUTION_FILE --configfile nuget.config --verbosity quiet`  before the build then why what is wrong in adding "--no-restore" to the build commandline?

And FYI.. that earlier error is gone and I am getting below series of errors:

- clang: error: linker command failed with exit code 1 (use -v to see invocation)
- error : clang++ exited with code 1:
- error : ld: warning: ignoring duplicate libraries..
-  error : ld: building for 'iOS-simulator', but linking in object file..
- error : clang: error: linker command failed with exit code 1

So, do we need this part "Optimizing assemblies for size. This process might take a while." for just building with iPhoneSimulator and how can we disable this or fix this errors?

Thanks.

**Comment by rolfbjarne** [comment]
> Few queries on your input of removing "--no-restore" . What was that error about?

I'd need binlogs to confirm, but this is likely what happened:

1. You ran `dotnet restore $SOLUTION_FILE --configfile nuget.config --verbosity quiet`. This restored the solution using the default runtime identifier(s), which may not have included `iossimulator-arm64`.
2. You can `dotnet build --no-restore -r iossimulator-arm64`, and the build complained that you didn't restore using `iossimulator-arm64`.

It might work if you do `dotnet restore -r iossimulator-arm64 ... ` in step 1 instead.

> And FYI.. that earlier error is gone and I am getting below series of errors:
> 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> error : clang++ exited with code 1:
> error : ld: warning: ignoring duplicate libraries..
> error : ld: building for 'iOS-simulator', but linking in object file..
> error : clang: error: linker command failed with exit code 1

Once again a [binlog](https://aka.ms/binlog) would confirm, but I'm guessing you're including a NuGet or native library that doesn't contain native bits for iossimulator-arm64. You might have more luck using `iossimulator-x64` instead.

**Comment by muffadal53** [comment]
@rolfbjarne: The `iossimulator-x64` input seems to work for me. So, below is the actual commands which I am using are as below to restore and build .Net MAUI iOS:

`dotnet restore -r iossimulator-x64 $SOLUTION_FILE --configfile nuget.config --verbosity quiet

 dotnet build ${APP_PROJECT_DIR} --configuration Release --no-restore -f net7.0-ios -r iossimulator-x64 -p:Platform="iPhoneSimulator" -p:verbosity=quiet`

So, are the above command correct? And as I was struggling to find any documentation or any article on above details, can you please point me to detail documentation on this topic of command line and if not then I suggest that Microsoft to create one so that it will be helpful for the Developers working with command line for build pipelines other than Microsoft Azure.

Thanks.

**Comment by rolfbjarne** [comment]
Personally I would just do this:

> dotnet build path/to/project.csproj -f net7.0-ios -r iossimulator-x64

Important points:

* The default runtime identifier is iossimulator-x64 (on an x64 machine) or iossimulator-arm64 (on an arm64 machine), so I'm assuming there's a RuntimeIdentifier property in your csproj setting it to ios-arm64, and that's why you need to override when building for simulator on the command line.
* We don't use the Platform property, but your csproj might contain logic that depends on it, so I'm unsure whether you can just remove it or not.
* Building simulator builds for the Release configuration is not very typical, any particular reason you're doing it?
* Also restoring and building separately is not necessary, `dotnet build` will automatically restore if need be.

Building and running from the command line is documented here: https://learn.microsoft.com/en-us/dotnet/maui/ios/cli?view=net-maui-8.0

**Comment by muffadal53** [comment]
> Personally I would just do this:
> 
> > dotnet build path/to/project.csproj -f net7.0-ios -r iossimulator-x64
> 
> Important points:
> 
> * The default runtime identifier is iossimulator-x64 (on an x64 machine) or iossimulator-arm64 (on an arm64 machine), so I'm assuming there's a RuntimeIdentifier property in your csproj setting it to ios-arm64, and that's why you need to override when building for simulator on the command line.
> * We don't use the Platform property, but your csproj might contain logic that depends on it, so I'm unsure whether you can just remove it or not.
> * Building simulator builds for the Release configuration is not very typical, any particular reason you're doing it?
> * Also restoring and building separately is not necessary, `dotnet build` will automatically restore if need be.
> 
> Building and running from the command line is documented here: https://learn.microsoft.com/en-us/dotnet/maui/ios/cli?view=net-maui-8.0

@rolfbjarne: Please find my comments to your points and queries below:

- The default runtime identifier is iossimulator-x64 (on an x64 machine) or iossimulator-arm64 (on an arm64 machine), so I'm assuming there's a RuntimeIdentifier property in your csproj setting it to ios-arm64, and that's why you need to override when building for simulator on the command line:   
    Yes, we have a RuntimeIdentifier in my csproj like below:

            <PropertyGroup Condition="'$(TargetFramework)' == 'net7.0-ios'">
                 <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
            </PropertyGroup> 

- We don't use the Platform property, but your csproj might contain logic that depends on it, so I'm unsure whether you can just remove it or not:
      We, have the platform property in my csproj for "Release|net7.0-ios|iPhone" conditional with "CodesignKey", "CodesignEntitlements", "CodesignProvision" etc. Hence, I think we need to specify the platform property in command line for "iPhoneSimulator" and to have clear distinction.

- Building simulator builds for the Release configuration is not very typical, any particular reason you're doing it?
       The simulator build that I am doing is to trigger the iOS build on every commit on the GitLab repository where I don't need deployment .ipa which I do as part of another job.

- Also restoring and building separately is not necessary, dotnet build will automatically restore if need be:
       Yes, I get the point of dotnet build doing it in single step if needed, but that two step commands is for more clarity.

And regarding the documentation part I am not convinced because it no where mentions the command line parameter of `-r iossimulator-x64` if we need to build without any code signing key/ Apple distribution certificate. And the errors we might get with the build like I faced and explanation on how to fix it with different command line options.

Thanks.

**Comment by rolfbjarne** [comment]
> Whether things are progressing or not, I would also like to see the IPA built directly without using code signing

Setting the `EnableCodeSigning` property to `false` might do it (i.e. passing `/p:EnableCodeSigning=false` if building on the command line).

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-macios#20671
