### ISSUE TITLE
Secure Storage GetAsync fails to return on Android

### ISSUE THREAD

**Issue by phillippschmedt** [dotnet/maui#18835]
### Description

.NET 8 Stable Release
Same issue as described here: https://github.com/dotnet/maui/issues/12341

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by phillippschmedt** [comment]
Already addressed here: https://github.com/dotnet/maui/pull/17928

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/12341

**Comment by mattleibow** [comment]
This should be going out with service release 1 soon.
