### ISSUE TITLE
[regression/8.0.3] Using Samsung.Tizen.Sdk/7.0.129 with .NET 7 projects fails to build

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#18837]
### Description

After updating the Samsung.Tizen.Sdk to 7.0.129, .NET 7 project no longer build. There is an error:

```
error : The api-version specified in tizen-manifest file is 7.
error : Current target framework net7.0-tizen is not supported in this api-version.
```

```
dotnet build "D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\Buildmauinet70DebugFalse.csproj" -c Debug -p:RestoreNoCache=true -p:RestorePackagesPath=D:\a\_work\_temp\test-intg\packages -p:RestoreConfigFile=D:\a\_work\_temp\test-intg\NuGet.config -p:CustomBeforeMicrosoftCSharpTargets=D:\a\_work\1\s\src\Templates\TemplateTestExtraTargets.targets -p:DisableTransitiveFrameworkReferenceDownloads=true -p:TreatWarningsAsErrors=true -warnaserror -p:nowarn="NETSDK1201%3BCS1591" -bl:"D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\build-133446453331466794.binlog"

MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  Restored D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\Buildmauinet70DebugFalse.csproj (in 8.21 sec).
  Buildmauinet70DebugFalse -> D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\bin\Debug\net7.0-ios\iossimulator-x64\Buildmauinet70DebugFalse.dll
  Buildmauinet70DebugFalse -> D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\bin\Debug\net7.0-maccatalyst\maccatalyst-x64\Buildmauinet70DebugFalse.dll
  Buildmauinet70DebugFalse -> D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\bin\Debug\net7.0-tizen\tizen-x86\Buildmauinet70DebugFalse.dll
D:\a\_work\1\s\bin\dotnet\packs\Samsung.Tizen.Sdk\7.0.129\targets\Samsung.Tizen.Sdk.Packaging.targets(161,5): error : The api-version specified in tizen-manifest file is 7. [D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\Buildmauinet70DebugFalse.csproj::TargetFramework=net7.0-tizen]
D:\a\_work\1\s\bin\dotnet\packs\Samsung.Tizen.Sdk\7.0.129\targets\Samsung.Tizen.Sdk.Packaging.targets(161,5): error : Current target framework net7.0-tizen is not supported in this api-version. [D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\Buildmauinet70DebugFalse.csproj::TargetFramework=net7.0-tizen]
  Buildmauinet70DebugFalse -> D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\bin\Debug\net7.0-android\Buildmauinet70DebugFalse.dll
  Buildmauinet70DebugFalse -> D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\Buildmauinet70DebugFalse.dll
Build FAILED.
D:\a\_work\1\s\bin\dotnet\packs\Samsung.Tizen.Sdk\7.0.129\targets\Samsung.Tizen.Sdk.Packaging.targets(161,5): error : The api-version specified in tizen-manifest file is 7. [D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\Buildmauinet70DebugFalse.csproj::TargetFramework=net7.0-tizen]
D:\a\_work\1\s\bin\dotnet\packs\Samsung.Tizen.Sdk\7.0.129\targets\Samsung.Tizen.Sdk.Packaging.targets(161,5): error : Current target framework net7.0-tizen is not supported in this api-version. [D:\a\_work\_temp\test-intg\Buildmauinet70DebugFalse\Buildmauinet70DebugFalse.csproj::TargetFramework=net7.0-tizen]
    0 Warning(s)
    2 Error(s)
Time Elapsed 00:01:46.34
```

### Steps to Reproduce

1. File | New | .NET MAUI App
2. Ensure the TFM is net7.0-tizen
3. Build
4. Observe the error

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.2.9511

### Affected platforms

Other (Tizen, Linux, etc. not supported by Microsoft directly)

**Comment by mattleibow** [comment]
In order to update maui to .NET 8 stable, I have blocked the building of .NET 7 & Tizen in this PR: https://github.com/dotnet/maui/pull/18732

The changes will need to be reverted.

**Comment by mattleibow** [comment]
@JoonghyunCho 

I see the build fails when using .NET 8 (and Tizen SDK 7.0.129) but the project is targeting .NET 7 (net7.0-tizen). 

The Tizen manifests always use the same Tizen SDK for all TFMs, so 7.0.129 is used for net7.0-tizen AND net8.0-tizen. I am not sure if that is a design feature? I do not think there is any issues to doing that, but maybe the tasks get more complex as they have to understand different .NET versions.

To avoid this in .NET MAUI we have done this in the manifest json:

```json
"Microsoft.Maui.Sdk.net8": {
  "kind": "sdk",
  "version": "8.0.3",
  "alias-to": {
    "any": "Microsoft.Maui.Sdk"
  }
},
"Microsoft.Maui.Sdk.net7": {
  "kind": "sdk",
  "version": "7.0.101",
  "alias-to": {
    "any": "Microsoft.Maui.Sdk"
  }
}
```

And then in the manifest targets:

```xml
  <Import
      Condition=" ('$(UseMaui)' == 'true') and ($([MSBuild]::VersionEquals($(TargetFrameworkVersion), '8.0'))) and ('$(SkipMauiWorkloadManifest)' != 'true') "
      Project="Sdk.targets" Sdk="Microsoft.Maui.Sdk.net8"
  />
  <Import
      Condition=" ('$(UseMaui)' == 'true') and ($([MSBuild]::VersionEquals($(TargetFrameworkVersion), '7.0'))) and ('$(SkipMauiWorkloadManifest)' != 'true') "
      Project="Sdk.targets" Sdk="Microsoft.Maui.Sdk.net7"
  />
```

This will pull in older SDKs for older TFMs. But, if you are really wanting to use the latest everywhere, then maybe there needs to be a way to use API 7 with .NET 7 TFMs? If the SDK no longer supports net7.0, then maybe the first option of multiple SDKs in the manifest is the preferred option?

For now, I am disabling .NET 7 builds using the .NET 8 SDK.

I opened an issue to track this: https://github.com/dotnet/maui/issues/18837

**Comment by JoonghyunCho** [comment]
Thanks for all the details.
Just for MAUI .NET8, I released the new [Tizen workload](https://www.nuget.org/packages/Samsung.NET.Sdk.Tizen.Manifest-8.0.100/8.0.130) which reverts to set Tizen 8.0 as default platform version(net6.0-tizen goes net6.0-tizen8.0) for net6.0 and net7.0.
I will also try updating Tizen manifests to use different sdk on different .net versions like above solution.

**Comment by JoonghyunCho** [comment]
Tizen Workload is now targeting different Tizen SDK for the different version of .NET sdk.
Thanks again for the suggestion! :)

**Comment by jfversluis** [comment]
Is there something still to do here or is this fixed by now? @mattleibow @JoonghyunCho ?

**Comment by JoonghyunCho** [comment]
@jfversluis done fixing this. I think the issue can be closed :)

**Comment by jfversluis** [comment]
Perfect, thank you!
