### ISSUE TITLE
8.0.3 Android FlyoutPage Doesnt work on .NET 7 no problem

### ISSUE THREAD

**Issue by planyazilim** [dotnet/maui#18846]
### Description

FlyoutPage.cs comes to InitializeComponent(); then crashes.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

### Did you find any workaround?

no

**Comment by drasticactions** [comment]
I created a new net8.0 Android page with a flyout and a new template page, and it worked correctly. Could you please create an example project where you can reproduce this issue? Thank you!

**Comment by planyazilim** [comment]
> I created a new net8.0 Android page with a flyout and a new template page, and it worked correctly. Could you please create an example project where you can reproduce this issue? Thank you!

You are right my mistake. sorry for taking your time regards.

**Comment by planyazilim** [comment]
It works. My mistake. Sorry for taking your time regards.
