### ISSUE TITLE
Platform View Null on a Custom Control

### ISSUE THREAD

**Issue by stevenroman760** [dotnet/maui#18847]
### Description

I'm trying to make a custom control in .Net Maui as a pet project. I found a cool sample on the internet and couldn't get it running from GitHub so I nabbed bits out of it and made a new project. I can get the project to compile but when it enters the constructor or my control and tries to access the handler the handler code says PlatformView cannot be null.
![parentCatch](https://github.com/dotnet/maui/assets/42281577/aa268c2f-3534-4590-bb76-7c7d7b152e7c)
![PlatformViewNull](https://github.com/dotnet/maui/assets/42281577/6e51e059-5f20-4f41-828b-9b252702cd92)

### Version with bug

7.0.59

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No. I'm stuck.

**Comment by mattleibow** [comment]
Hi there! I think you may not need a custom handler for this. A handler is only needed if you need some new/custom platform control. The Handler and PlatformView is set by MAUI when the view is rendered.

I think maybe you just need new bindable properties for your case?

```
public static readonly BindableProperty ButtonColorProperty =
	BindableProperty.Create(nameof(ButtonColor), typeof(Color), typeof(StickyNote),
		propertyChanged: (bindable, oldValue, newValue) =>
		{
			var note = (StickyNote)bindable;
			var color = (Color)newValue;
			if (stickynote.Drawable is StickyNoteDrawable drawable)
			    drawable.ButtonColor = color;
		});
```

Let me know if this works.
