### ISSUE TITLE
Error on right click on Entry control in different Windows

### ISSUE THREAD

**Issue by danielancines** [dotnet/maui#18853]
### Description

When I create and open new windows, the entry control have some weird behaviors:
1. If you press right click on entry and try to close window, app crashes. I've tried using main branch of Maui Repository and the error not occurs inside the Maui project, it appears be a WinUI error.
2. If you press right click and change windows to right click some other entry, the crashes occurs again.

Below I tried to press right click on entry of a second window and crash happens.
![Maui-RightClickCrash-V2](https://github.com/dotnet/maui/assets/2250055/0217832c-d942-4bd8-8a25-1084c00a14e6)

Below I just press right click on entry and immediately try to close window.
![Maui-RightClickCrash](https://github.com/dotnet/maui/assets/2250055/ee6dbac7-0d9f-48f8-a7f8-09c654389d72)

The exception:
![Exception_Closing_Windows](https://github.com/dotnet/maui/assets/2250055/9f22ca79-22f6-406c-8993-e4897956ea25)

This error occurs on 7.0.404 too.

### Steps to Reproduce

1. Create a Maui project
2. Open two windows with a entry
3. Do the steps that I describe above

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by lfmouradasilva** [comment]
Same issue here

**Comment by lfmouradasilva** [comment]
Any updates?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 5(8.0.14&8.0.7&8.0.3). Can repro on windows platform. But on 8.0.20&8.0.21 works fine.
