### ISSUE TITLE
[.NET 8]Shell's return arrow appears on the mainpage.

### ISSUE THREAD

**Issue by GXSA-Qi** [dotnet/maui#18867]
### Description

When using Shell navigation to return to the main page from other pages, a return arrow will briefly appear on the left side of the Shell on the main interface. This problem is currently only found on the Android platform (the framework is .NET 8) in .NET 7 and .NET 6 There is no such problem above, here is a video example:

https://github.com/dotnet/maui/assets/63104968/b11c601d-3b70-423a-82e4-5b0e05f6fbad

### Steps to Reproduce

1.Create a .NET MAUI ContentPage(XAML), and keep the default page for the new page.
2.Follow https://learn.microsoft.com/zh-cn/dotnet/maui/fundamentals/shell/navigation?view=net-maui-8.0 to register the route of the newly created ContentPage.Like this:
`Routing.RegisterRoute(nameof(NewPage), typeof(NewPage));`
3.Change the background code of the "Click Me" button to the execution navigation that jumps to the new page. Like this: `Shell.Current.GoToAsync(nameof(NewPage));`
4.Compile and run on Android platform. Just like the uploaded video, click the "Click Me" button to jump to a new page and return to the main interface. A return arrow will briefly appear on the left side of the Shell on the main interface.

### Link to public reproduction project repository

https://github.com/GXSA-Qi/MAUIIssueInShell.git

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.101

### Affected platforms

Android

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). Repro on Android 14.0-API34, not repro on Windows 11, iOS 17.0, MacCatalyst with below Project:
[DotNet8InMauiShellIssue.zip](https://github.com/dotnet/maui/files/13658600/DotNet8InMauiShellIssue.zip)

**Comment by dbSoft-SoftwareSolutions** [comment]
We have the same problem please fix it
