### ISSUE TITLE
MAUI publish spits out hundreds of unnecessary language folders 

### ISSUE THREAD

**Issue by strich** [dotnet/maui#18862]
### Description

When publishing a MAUI app it spits out a rediculous amount of language folders:
![image](https://github.com/dotnet/maui/assets/987896/692dd1a9-d172-4521-9f91-b1c9092ce524)

Its extremely bad looking and difficult to push this on to end users for simple apps that don't even bother about I18N support.

If these folders are really necessary they should go into a single "language" subfolder and not pollute the main directory.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 5 ( 8.0.21). Can not repro this issue
