### ISSUE TITLE
[regression/8.0.3] iOS Navbar issue is back

### ISSUE THREAD

**Issue by e012345678** [dotnet/maui#18874]
### Description

We just upgraded our app to .NET 8 and the issue that the app is behind the navbar (and not beneath it like 30px or whatever it is) is back. This was an issue that has been back and forth but was working fine in .NET 7. Now its again an issue in .NET 8. See attached screenshot. Is there some setting I am missing that was introduced in .NET 8? This is exact same code as we had for .NET 7.

![iosnavbarerror2](https://github.com/dotnet/maui/assets/97082481/53b0c8d2-fdc3-4eb9-abda-785a7be425ca)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
if you toggle this value does the behavior change for you?
https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.platformconfiguration.iosspecific.page.setusesafearea?view=net-maui-7.0

**Comment by e012345678** [comment]
Can you be more specific on exactly how and where to set that property in Blazor MAUI Hybrid? Not really sure in what segment it should be set. Thanks a lot

**Comment by twofingerrightclick** [comment]
@PureWeen It appears that Position fixed elements are not respecting the same view port that the safe area is. https://learn.microsoft.com/en-us/dotnet/maui/ios/platform-specifics/page-safe-area-layout?view=net-maui-8.0

**Comment by e012345678** [comment]
Setting

```
xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
ios:Page.UseSafeArea="True"
```

in the MainPage.xml seems to work

**Comment by PureWeen** [comment]
> Setting
> 
> ```
> xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
> ios:Page.UseSafeArea="True"
> ```
> 
> in the MainPage.xml seems to work.
> 
> Can you confirm this is the recommended solution @PureWeen @samhouts

yea we changed the default for this property between net7 and net8 to match net6 and XF. This way users migrating from XF would see consistent behavior

**Comment by twofingerrightclick** [comment]
We are still stuck with our Blazor Hybrid MAUI iOS app. We are holding out on manually adjusting all our layouts with CSS to handle the safe area inset, hoping it will be fixed soon. See https://github.com/dotnet/maui/issues/18874#issuecomment-1858374176 for example of how to manually use CSS to ensure positioned items respect safe area inset.

**Comment by axylophon** [comment]
ios:Page.UseSafeArea="True" brings back the behaviour of .NET7.

**Comment by twofingerrightclick** [comment]
@axylophon  I thought "True" is the default value of ios:Page.UseSafeArea so no need to set, but indeed setting it did fix!
![image](https://github.com/dotnet/maui/assets/11265760/1b097711-427d-4ebf-ba05-57243117b199)

**Comment by twofingerrightclick** [comment]
So it looks like despite the [documentation ](https://learn.microsoft.com/en-us/dotnet/maui/ios/platform-specifics/page-safe-area-layout?view=net-maui-8.0)making it sound like "True" is the default value of ios:Page.UseSafeArea it must not be?

**Comment by axylophon** [comment]
I think they changed the default since .NET8

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 1. Not repro on iOS platform with template project.
![image](https://github.com/dotnet/maui/assets/77434865/97d91b8e-8614-4bed-86e0-a200fbd15180)
