### ISSUE TITLE
[regression/8.0.3] SkiaBitmapExportContext.SKImage.Encode JPEG compression bug when encoding the image.

### ISSUE THREAD

**Issue by cropyai** [dotnet/maui#18876]
### Description

Hi,

I have a canvas and my goal is to draw some images on the canvas and save the resulting image. A bug occurs when saving the resulting image. I am creating the canvas like this `SkiaBitmapExportContext bmp = new(background.Width, background.Height, 1.0f);` and the save code & the results are below. I want to say that this was not happening .NET 7. Also, there is no bug in compressing to PNG format. 

Save code:
```
SKData encoded = bmp.SKImage.Encode(SKEncodedImageFormat.Jpeg, 100); // 100 is the quality level
using (var stream = File.OpenWrite(file.AbsolutePath)) encoded.SaveTo(stream);
```

Results (ignore the car image rotation & position & the white rectangles on the license plate, focus on the colors):
![image](https://github.com/dotnet/maui/assets/122940429/f4ad9a6e-011f-4337-957b-808058c0fb05)
![image](https://github.com/dotnet/maui/assets/122940429/aaebdc78-e890-47e5-80a6-f988f9b2bd6f)

The images look dark and some random color is added sometimes. I don't know why this is the case. However, I use a workaround that depends on the Android native code. 

# Workaround
```
using (var stream = File.OpenWrite(file.AbsolutePath)) 
        await bmp.Bitmap.ToBitmap().CompressAsync(Android.Graphics.Bitmap.CompressFormat.Jpeg, 100, stream);
```

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jfversluis** [comment]
@mattleibow Shouldn't this be on the Skia repo?

**Comment by mattleibow** [comment]
I think maybe... Although the entry point is maui graphics `SkiaBitmapExportContext`, it appears the final save step is in skia code.

What happens if you update to the latest skiasharp? You should be able to just install the SkiaSharp.Views package.
