### ISSUE TITLE
Please update the tutorial to not use "Visual Studio for Mac" + CLI command for creating project from template

### ISSUE THREAD

**Issue by Crare** [dotnet/maui#18871]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: macos

As [Visual Studio for Mac is being retired](https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/), I hope this tutorial is going to get updated.
Tutorial could probably be updated to use VSCode instead and create CLI commands to create the project from a template.

**Comment by Eilon** [comment]
@davidbritch - any thoughts on this?

**Comment by mairaw** [comment]
Yes, we're planning to update that tutorial soon. We just couldn't get it done in time for the launch.

/cc @claudiaregio @beckybuckler

**Comment by samhouts** [comment]
Looks like this was done! Thanks all!
