### ISSUE TITLE
[regression/8.0.3] Microsoft.Maui.Storage.FileSystem.Current.AppDataDirectory + CacheDataDirectory Broken - Windows 10

### ISSUE THREAD

**Issue by Bensley96** [dotnet/maui#18880]
### Description

Updated to .net 8 GA release and found on Windows 10 builds Microsoft.Maui.Storage.FileSystem.AppDataDirectory or CacheDataDirectory to be broken. I have tested this on Android Sim and Windows 11 they worked. As well as a clean install of Windows 10 and a new project and neither of them worked.

The Error:
Microsoft.Maui.Storage.FileSystem.Current.AppDataDirectory | 'Microsoft.Maui.Storage.FileSystem.Current.AppDataDirectory' threw an exception of type 'System.TypeInitializationException' | string {System.TypeInitializationException}

I've tried rolling back the same as I would by specifing the Maui Version but it does not seem to work. This was working on the RC before or one before that, i can't remember if i missed one but definitley within the last two RCs.

I've put the affected line in MainPage.xaml.cs just put a breakpoint on it and quick watch it.

i've also tried using both Microsoft.Maui.Storage.FileSystem.AppDataDirectory and Microsoft.Maui.Storage.FileSystem.Current.AppDataDirectory to see if there had been a change, both throw exceptions.

### Steps to Reproduce

1. Create New Project
2. Add line `Console.WriteLine(FileSystem.AppDataDirectory)`
3. Add breakpoint on line
4. Run project

### Link to public reproduction project repository

https://github.com/Bensley96/MAUIBugs

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.2.9373

### Affected platforms

Windows

### Affected platform versions

Windows 10 19045.3693

**Comment by Bensley96** [comment]
Just for more information, It only seems to be an issue on the UI/Main Thread. If you make another thread and access it, atleast from the Watch i have running, it works, the moment you switch to UI it is back to the forementioned error.

Currently i have had to hard code the directories in to continue developing as, without those methods working i cannot access my SQLite databases. Which is ok if i am only testing windows and on the same computer. But means i cannot publish or even QA on other computers or platforms. 
I know i can conditionally compile and if i get desperate that is what i will do for android/macos/ios but i'm not aware of conditionally compiling for windows 10 vs 11 and most of the computers QA'ing are windows and 50/50 10 to 11.

**Comment by jamesmontemagno** [comment]
Are you running the app packaged or unpackaged... aka from VS or from VS Code?

**Comment by Bensley96** [comment]
I'm using VS, and was on the latest preview version at the time.

**Comment by jamesmontemagno** [comment]
Gotcha, thanks @Bensley96. I just ran your sample on stable on Windows 11... i don't have any windows 10 machines anymore

Ourput was `C:\Users\jamont\AppData\Local\Packages\com.companyname.mauiapp4_9zz4h110yvjzm\LocalState`

**Comment by jamesmontemagno** [comment]
this is the code that is run:
```
ApplicationData.Current.LocalFolder.Path
```

The only thing I can think of is.... it checks if it is packaged ahead of time....

You could also try this code:

```
#if WINDOWS
            try
			{
                if (Windows.ApplicationModel.Package.Current != null)
                    Console.WriteLine("is packaged");
			}
			catch
			{
				// no-op
			}

            Console.WriteLine("is not packaged");
#endif
```

However... that was introduced in like 10240 so been there forever

**Comment by Bensley96** [comment]
Currently as a work around for windows i am manually building the folder string which is getting me by.

Yeah, I have both windows 11 (arm), 10 (x64) and Mac hardware and obviously iphone/android emulator. Every platform including Win11 have worked fine. Win 10 not working is recent (when i went on to the released .net 8).

**Comment by jamesmontemagno** [comment]
Did you try to run the code above for me?

**Comment by davidortinau** [comment]
I used this in 8.0.21 on Windows and Mac without an issue. There's a separate issue related to unpackaged, but I think this is  fixed. Please open a new issue with new details if this persists for you.
