### ISSUE TITLE
[Android] "Failed to inflate ColorStateList" error is logged when setting Color to CheckBox

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#18897]
### Description

When setting `Color` to `CheckBox` on Android, the following error is logged, even if the functionality seems to work:
```
[ResourcesCompat] Failed to inflate ColorStateList, leaving it to the framework
[ResourcesCompat] java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f040111 a=-1}, theme={InheritanceMap=[id=0x7f120137com.ouibank.android.app:style/Maui.MainTheme.NoActionBar, id=0x7f120136com.ouibank.android.app:style/Maui.MainTheme, id=0x7f120249com.ouibank.android.app:style/Theme.MaterialComponents.DayNight, id=0x7f120262com.ouibank.android.app:style/Theme.MaterialComponents.Light, id=0x7f12006bcom.ouibank.android.app:style/Base.Theme.MaterialComponents.Light, id=0x7f1200a4com.ouibank.android.app:style/Base.V21.Theme.MaterialComponents.Light, id=0x7f120092com.ouibank.android.app:style/Base.V14.Theme.MaterialComponents.Light, id=0x7f120093com.ouibank.android.app:style/Base.V14.Theme.MaterialComponents.Light.Bridge, id=0x7f120140com.ouibank.android.app:style/Platform.MaterialComponents.Light, id=0x7f12021ccom.ouibank.android.app:style/Theme.AppCompat.Light, id=0x7f120053com.ouibank.android.app:style/Base.Theme.AppCompat.Light, id=0x7f1200b6com.ouibank.android.app:style/Base.V28.Theme.AppCompat.Light, id=0x7f1200b3com.ouibank.android.app:style/Base.V26.Theme.AppCompat.Light, id=0x7f1200adcom.ouibank.android.app:style/Base.V23.Theme.AppCompat.Light, id=0x7f1200abcom.ouibank.android.app:style/Base.V22.Theme.AppCompat.Light, id=0x7f1200a0com.ouibank.android.app:style/Base.V21.Theme.AppCompat.Light, id=0x7f1200b9com.ouibank.android.app:style/Base.V7.Theme.AppCompat.Light, id=0x7f12013dcom.ouibank.android.app:style/Platform.AppCompat.Light, id=0x7f120148com.ouibank.android.app:style/Platform.V25.AppCompat.Light, id=0x1030241android:style/Theme.Material.Light.NoActionBar, id=0x1030237android:style/Theme.Material.Light, id=0x103000candroid:style/Theme.Light, id=0x1030005android:style/Theme], Themes=[com.ouibank.android.app:style/Maui.MainTheme.NoActionBar, forced, com.ouibank.android.app:style/Maui.SplashTheme, forced, com.ouibank.android.app:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
[ResourcesCompat] 	at android.content.res.TypedArray.getColor(TypedArray.java:529)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.inflate(ColorStateListInflaterCompat.java:159)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:124)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:103)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
[ResourcesCompat] 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:562)
[ResourcesCompat] 	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:48)
[ResourcesCompat] 	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:179)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCompoundButtonHelper.loadFromAttributes(AppCompatCompoundButtonHelper.java:81)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCheckBox.<init>(AppCompatCheckBox.java:84)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:231)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:227)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:223)
[ResourcesCompat] 	at crc6452ffdc5b34af3a0f.NavigationViewFragment.n_onCreateView(Native Method)
[ResourcesCompat] 	at crc6452ffdc5b34af3a0f.NavigationViewFragment.onCreateView(NavigationViewFragment.java:42)
[ResourcesCompat] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
[ResourcesCompat] 	at android.os.Handler.handleCallback(Handler.java:958)
[ResourcesCompat] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[ResourcesCompat] 	at android.os.Looper.loopOnce(Looper.java:205)
[ResourcesCompat] 	at android.os.Looper.loop(Looper.java:294)
[ResourcesCompat] 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[ResourcesCompat] 	at java.lang.reflect.Method.invoke(Native Method)
[ResourcesCompat] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[ResourcesCompat] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
Is this hidding some kind of bug? Is it possible to avoid this log?

### Steps to Reproduce

1. Open repro project
2. Click on "Checkbox test" button ; it navigates to a new page with a simple colored checkbox
3. Observe output window in visual studio: an error is logged.

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppMaterialButtonAndCheckbox

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by BaltoAF** [comment]
Exact same problem here with Android 13 and MAUI 8.0.3

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2 (.Net8.0). Repro on Android 14.0-API34 with below project.
[MauiApp1.zip](https://github.com/dotnet/maui/files/13747670/MauiApp1.zip)
![image](https://github.com/dotnet/maui/assets/131441429/e89f57ff-de91-41d5-b0d5-360036a68441)

**Comment by cworth33** [comment]
I'm getting this error too.  Our page is similar to a survey where it is defined by a admin who lays out the questions and answers.  If you get enough of the checkboxes on the UI the app hangs/crashes.

**Comment by mrwatts** [comment]
According to my tests, this error doesn't even need the color to be set to occur. Steps to reproduce:

1. Create a new Maui project using the template
2. Remove the Checkbox styling from Styles.xaml (to prove the point)
3. Add ```<Checkbox/>``` to MainPage.xaml
4. Run app in debug mode in Android emulator
5. Observe the error

**Comment by Larhei** [comment]
Workaround working for me  to stop the exception:

1. Download Colorstates of checkbox from [material-components](https://github.com/material-components/material-components-android/tree/master/lib/java/com/google/android/material/checkbox/res/color)
2. Change `android:color="@xxxx"` to android:color="#FFFFFF"
_The color does not matter._
3. Add a new Folder colors to Platforms/Android/Resources
4. Add the two xml files with Build Action "AndroidResource"

**Comment by last-Programmer** [comment]
@Larhei  i tried and i get the error invalid file path. API2144 for this files during the build

**Comment by Larhei** [comment]
In my cspro
`
<ItemGroup>
<None Remove="Platforms\Android\Resources\color\m3_checkbox_button_icon_tint.xml" />
<None Remove="Platforms\Android\Resources\color\m3_checkbox_button_tint.xml" />
 </ItemGroup>
`

Worked for me with maui 8.0.6 and vs 17.8.4

**Comment by last-Programmer** [comment]
@Larhei thanks

Add a new Folder colors to Platforms/Android/Resources

i created the colors folder instead of color. all good now. i am not getting the exception now. thanks a lot for the heads up.

**Comment by maonaoda** [comment]
This hasn't been fixed yet...

**Comment by mrwatts** [comment]
> Workaround working for me to stop the exception:
> 
> 1. Download Colorstates of checkbox from [material-components](https://github.com/material-components/material-components-android/tree/master/lib/java/com/google/android/material/checkbox/res/color)
> 2. Change `android:color="@xxxx"` to android:color="#FFFFFF"
>    _The color does not matter._
> 3. Add a new Folder color to Platforms/Android/Resources
> 4. Add the two xml files with Build Action "AndroidResource"

Thanks for this. Worked like a charm. I didn't need to add lines to my .csproj file.  Just adding the files to Platforms/Android/Resources/color was enough.

**Comment by bradyguyc** [comment]
This work around is still required in  9.0.100-preview.5.24307.3 visualstudio 17.11.0 preview 2.1

**Comment by OnClickListener2048** [comment]
worked like a charm!

**Comment by MsShiftDev** [comment]
> Larhei

Shoutout to Larhei! I hope someone gives him/her/them a cookie! I did not need step 4, but the first three resolved the issue for me.
