### ISSUE TITLE
Splash screen bug

### ISSUE THREAD

**Issue by iamalexmang** [dotnet/maui#18890]
### Description

Hi,

I'm having issues related to changing a splash screen on my app. 
Originally, I thought there was an issue with my SVG, but I then learnt that there might be something different to it. Specifically, no matter how many changes I applied to the same file, the same splash was always rendered.

Later, I realized that I should validate that the new splash screens are even considered by MAUI, so I decided to have new file names and based on [this comment](https://github.com/dotnet/maui/issues/17940#issuecomment-1757151576) from thread #17940, I decided to re-run the application following this flow:
1. I create a new splash and paste it in my project having a new name
2. I close Visual Studio for Mac
3. I delete the bin and obj folders 
4. I uninstall the app from my simulator
5. I restart the simulator
6. I reopen Visual Studio for Mac
7. I rebuild and deploy the solution to the simulator
8. I run the app

The bug is here: after days of frustration, I realized that SVGs I expected would show up, never show up (there's just a blank screen). What I later found is that if I apply the original svg (saved as splash1.svg), the splash shows up. Yet the exact same file content, called splash7.svg, once configured as my splash screen, doesn't show up. This is the exact same content (down by the character), but with a different name.

This suggests that the bug is rather in MAUI and has nothing to do with my file. Or there's something else I'm missing...

### Steps to Reproduce

I'm providing these SVG files, virtually the same, but with different names.
![splash1](https://github.com/dotnet/maui/assets/5773281/b28787c0-7b64-4639-892d-0e53c4719477)
![splash7](https://github.com/dotnet/maui/assets/5773281/26334cb3-ba33-42ac-ba24-c5f1d87672e9)

This renders a blank screen:!

```
<MauiSplashScreen Include="Resources\Splash\splash7.svg" BaseSize="1179,2556" Color="#FFFFFF" />
```

This renders a logo screen:
```
<MauiSplashScreen Include="Resources\Splash\splash.svg" BaseSize="1179,2556" Color="#FFFFFF" />
```

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

Not yet

**Comment by davidortinau** [comment]
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?view=net-maui-8.0&tabs=android#set-the-base-size

I'm testing this with 8.0 on an M1 Mac using Xcode 15.0.

I think the black screen is related to https://github.com/xamarin/xamarin-macios/issues/18469. Applying the workaround I see the SVGs, both of them.

```
<PropertyGroup>
	<EnableCodeSigning>true</EnableCodeSigning>
	<CodesignRequireProvisioningProfile>true</CodesignRequireProvisioningProfile>
	<DisableCodesignVerification>true</DisableCodesignVerification>
</PropertyGroup>
```

If I remove the base size altogether, OR if I set the base size to `BaseSize="702.9,696.5"`, which is what I see in the svg for the viewport, then I get:

![Simulator Screenshot - iPhone 15 Pro - 2023-11-19 at 18 29 06](https://github.com/dotnet/maui/assets/41873/1b733778-18a3-4f56-98b8-45cdb9e2ef72)

I opened the SVG and noticed is had some hidden assets and it's an odd size even though the art is square. I removed the hidden art and resized the image to 300x300, also updating `BaseSize="300,300"`:

![Simulator Screenshot - iPhone 15 Pro - 2023-11-19 at 19 22 17](https://github.com/dotnet/maui/assets/41873/d3ebf387-4b72-4174-9257-66acf10d534d)

**Comment by iamalexmang** [comment]
I just tried to add the Codesign PropertyGroup in my csproj, but that didn't help. And unlike others who commented on #18469, I do have a Developer Account and valid codesigning keys configured.

This forced me to continue to check the SVG using Android, but the issues get even worse there.

To clarify, what I'm trying to achieve is to have the application logo in the middle and the company logo at the bottom (similar to what you see in with the Instagram or WhatsApp apps, with the Meta logo at the bottom, or Outlook/Excel/Word/Teams/PowerPoint and the Microsoft logo at the bottom).
Hence, logos won't be square.

The issue here is that if I use Android 11 to test the app, the SVG is way to large and despite explicitely configuring Resize="true", the logo is outside the screen bounds
![image](https://github.com/dotnet/maui/assets/5773281/dcf75700-9b49-4f1f-86bf-865ce7f43b5e)

On Android 12.1, the splash doesn't appear at all:
![image](https://github.com/dotnet/maui/assets/5773281/406b79e6-bafe-4667-955e-8d0f9b997e41)

And finally, on Android 13, the splash is tiny and impossible to read:
![image](https://github.com/dotnet/maui/assets/5773281/adda93f9-e883-4ac6-9268-cf84ae96dfba)

In this regard, I'd argue that the MauiSplashScreen doesn't actually resize the splash screen as expected and the fact that the splash screen may or may not show up is counterintuitive.

**Comment by mattleibow** [comment]
Both issues are related to known changes by the platform:
* iOS now requires signing for splash screens to work: https://github.com/xamarin/xamarin-macios/issues/18469
* Android changed the way they do splash screens: pre 12 allows full screen, 12 does not show splash in most cases, 13+ forces the tiny image: https://github.com/dotnet/maui/issues/9794 (and all related issues)

**Comment by davidortinau** [comment]
@iamalexmang you can also [disable the MAUI splash generation](https://learn.microsoft.com/en-us/dotnet/maui/troubleshooting?view=net-maui-8.0#disable-splash-screen-packaging) and make your own using the platform methods. As the last line of that splash screen documentation says "For more advanced splash screen scenarios, per-platform approaches apply."

These older Xamarin docs may be helpful if you need a refresher on how the platforms work, and you can refer to Apple and Google's docs directly for the latest guidance. In .NET MAUI implement this in the Platforms folder.
- https://learn.microsoft.com/en-us/xamarin/android/user-interface/splash-screen
- https://learn.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/launch-screens
