### ISSUE TITLE
[iOS][.NET8] Task not found for Xamarin.MacDev.Tasks.GetFullPaths

### ISSUE THREAD

**Issue by RomanDrechsel** [dotnet/maui#18900]
### Description

Hi,

i just updated my app from .net7 to .net8

Android works just fine, but i can't build my iOS app.
I always get the following error:

>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : MessagingException: An error occurred on client Build1708478 while executing a reply for topic xvs/build/17.0.8478/execute-task/AIMessenger/72af58c002fGetFullPaths
>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : ArgumentException: Task not found for 'Xamarin.MacDev.Tasks.GetFullPaths'
>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : Parameter name: taskName
>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : 

I didn't find any solution yet.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Relevant log output

```shell
12:52:05:574	1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : MessagingException: An error occurred on client Build1708478 while executing a reply for topic xvs/build/17.0.8478/execute-task/AIMessenger/72af58c002fGetFullPaths
12:52:05:574	1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : ArgumentException: Task not found for 'Xamarin.MacDev.Tasks.GetFullPaths'
12:52:05:574	1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : Parameter name: taskName
12:52:05:574	1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error :
```

**Comment by RomanDrechsel** [comment]
Hi,

fyi:
it seems that i find a workaround.

I remembered having a similar problem with GoogleAppMeasurement.xcframework a few month ago.
So i checked the Xamarin.Shared.Sdk.targets file and removed the line
> SessionId="$(BuildSessionId)

in the block

> <GetFullPaths

Now it seems to work.
I have no idea why this is happening.

**Comment by rolfbjarne** [comment]
We'd need a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) to figure out what's going on here.

@RomanDrechsel would you be able to get a binlog for us?

In any case, this is an issue for the xamarin-macios repository, so I'm moving it there.

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#19492
