### ISSUE TITLE
resource mipmap/appicon_round (aka com.companyname.mauiapp:mipmap/appicon_round) not found

### ISSUE THREAD

**Issue by Andrej16** [dotnet/maui#18904]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows
![image](https://github.com/dotnet/maui/assets/31798010/2d470bc6-a082-4ddf-9c31-a32a57116953)

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by activa** [comment]
I've seen this too, and it's usually resolved by doing a "deep clean": delete the `bin` and `obj` folders and also the  `%USERPROFILE%\.nuget\packages` folder

**Comment by jsauve** [comment]
As @activa mentioned, a deep clean seems to work. You can use `git clean -fdx` in your repo to do this quickly and easily (as long as you don't have any untracked files you don't want to lose). It's smart to do a commit or stash before you use `git clean -fdx`.

**Comment by awalker-dsg** [comment]
We see this issue almost every time we build an app after doing a "Clean Solution". We have tried some of the solutions suggested above, but the problem always seems to come back. 

Ultimately what we found works every time it to make ANY change to the `MauiImage` element after the Clean. For example, our MauiImage has a `Color` attribute. If we change that from `White` to `Red` and back again, then build, the `resource mipmap ... not found` build error goes away.

**Comment by ryanlgoldmine** [comment]
@williambuchanan2 agree!! same here

**Comment by claudecarb** [comment]
Hi all, 

Has someone found a more concrete workaround for this? I've tried deleting the bin and obj folders multiple times, restart VS, cleaning. Nothing seems to be working. Yesterday this happened as well but then all of a sudden it stopped occurring, until it started again just now.

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 6.0(8.0.71). Not repro this issue.
