### ISSUE TITLE
.NET MAUI Workload installed But the option to choose MAUI doesn't show up on the third dropdown.

### ISSUE THREAD

**Issue by samm1735** [dotnet/maui#18926]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Duplicate of #18927
