### ISSUE TITLE
[Bug] maui-check typo bug: Environment Variable, "Environemnt Variable"

### ISSUE THREAD

**Issue by peridot9** [dotnet/maui#1892]
![20210802-maui-check typo-Environment Variable](https://user-images.githubusercontent.com/38744638/127792130-ca91529d-cf1a-4c0e-8cf0-41987acebc36.png)

### Description
I found a simple, typo bug in "maui-check".
typo string: "Environemnt Variable"
Please refer to the screenshots.

### Steps to Reproduce

1. install maui-check
> dotnet tool install -g redth.net.maui.check

2. execute maui-check
3. install OpenJDK using maui-check.
For more detail, please refer to the screenshots.

### Expected Behavior
"Environment Variable"

### Actual Behavior
"Environemnt Variable"

### Basic Information

I checked this typo at least in ".NET MAUI Check v0.6.7.0".

- Version with issue:".NET MAUI Check v0.6.7.0".
- Last known good version: unknown.
- IDE: Visual Studio 2022 Preview
- Platform Target Frameworks: 
  - iOS:  n/a
  - Android: n/a 
  - UWP:  n/a 
- Android Support Library Version: 
- Nuget Packages: n/a
- Affected Devices: n/a

### Screenshots
Please refer to the screenshots.

### Workaround
none

**Comment by peridot9** [comment]
[
![20210802-maui-check typo-Environment Variable](https://user-images.githubusercontent.com/38744638/127792030-04a752bb-f577-4bcd-841e-ea8af2d7ab89.png)
](url)

**Comment by hartez** [comment]
You should open this in https://github.com/Redth/dotnet-maui-check
