### ISSUE TITLE
Wrong button width when using ImageSource

### ISSUE THREAD

**Issue by BerndStoltefuss** [dotnet/maui#18924]
### Description

After switching from .NET7 to .NET8 buttons which use an ImageSource are rendered incorrectly in a grid.
Instead of using the minimum width to display it's content, it uses the available width of the grid cell.

### Steps to Reproduce

1. Create sample MauiApp in VS.
2. add a `Grid ColumnDefinitions="*, *, *"` to the main page
3. put three buttons inside the grid with HorizontalOptions "Start", "Center", "End" for column 0,1,2
4. run the app
5. the buttons will only occupy the needed space to display their content. Correct.
6. add an ImageSource like ImageSource="{FontImage FontFamily={StaticResource Ionicons}, Glyph={x:Static my:IonIconCode.IonClock}, Size=25}" to the buttons
7. run again
8. the buttons will now occupy the complete grid cell width although HorizontalOptions != Fill

See attached sample project to reproduce, which has one grid with normal buttons and one grid with buttons using ImageSource in order to show the difference.

### Link to public reproduction project repository

https://github.com/BerndStoltefuss/MauiApp2

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.96

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

ios 17

**Comment by BerndStoltefuss** [comment]
The issue seems to be triggered by the "**Height**Request" attribute of the button style. If i remove the HeightRequest (and just use MinimalHeightRequest) everything works like expected.
So this is a valid workaround as i still consider this to be a bug.

**Comment by PureWeen** [comment]
Can you test this with the nightly?

https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by BerndStoltefuss** [comment]
If this:
`<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.0-nightly.9649" NoWarn="NU1605"/>
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.0-nightly.9649" NoWarn="NU1605"/>`

is enough to use the nightly (or do i have to install a nightly-SDK? Was not mentioned in your link), it does NOT change the behaviour.

I checked some more places in my app and it fails in a different way when the grid uses "Auto" for the cell. Then the button is not visible at all. So it seems to me that it measures it's own width as 0 and falls back to using some constraint from the parent element. It works correctly with "Auto" or "*" when removing the ImageSource. So the ImageSource seems to prevent the button from correctly measuring it's size. Not sure if this is iOS specific, as i only build for iOS.

**Comment by BerndStoltefuss** [comment]
Sample seems to work fine on android (updated sample for correct font reference for android).
Fails on iOS 17 and iOS 15.4. So probably iOS handler related.

**Comment by BerndStoltefuss** [comment]
Probably related to https://github.com/dotnet/maui/pull/18521 ?

**Comment by PureWeen** [comment]
@jknaudt21 thoughts?

**Comment by BerndStoltefuss** [comment]
@PureWeen : were you able to reproduce the issue using the provided sample project and nightly/main?

I am not sure if my test with just referening the two packages really uses #18521 or if i would have to use a local build from maui/main (which i unfortunately can't do because of security restrictions (powershell scripts etc.)). Opening the two changed classes from #18521 in VS shows me the old code (and Microsoft.Maui.dll from 8.0.3 as source).

**Comment by PureWeen** [comment]
The latest nightly build has the fixes from #18521 in it
So if you're still seeing the issue with that nightly build then it's not quite fixed yet.

**Comment by BerndStoltefuss** [comment]
@PureWeen I was able to install a local maui build using main-branch following this [https://dev.to/davidortinau/using-the-latest-net-maui-2f88](url) instructions (based on some input from you i think :-)).

Using this local maui build the problem **IS RESOLVED**.  #18521 seems to fix it.

So, probably the instruction to use the latest nightly are wrong and it is not enough to just point the two packages to the nightly feed???


Thanks for your support and the idea to test it against nightly/main!

Now i only have to wait for the next official build as working with a local maui build will  not work for the whole team (took me some time to bypass restrictions)
