### ISSUE TITLE
Publish IOS App Error ZipArchive.framework/ZipArchive' contains bitcode.

### ISSUE THREAD

**Issue by rajeshsws** [dotnet/maui#18920]
### Description

App is delivered by Transporter but get reject later on by App Store
Any help would be appreciated, Using 17.8.0 VS 2022

TMS-90482: Invalid Executable - The executable 'ProX.app/Frameworks/ZipArchive.framework/ZipArchive' contains bitcode.
Thank you 

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

**Comment by jfversluis** [comment]
Duplicate of #12863
