### ISSUE TITLE
There isn't the "Additional information" window in my VS 2022 17.8. 

### ISSUE THREAD

**Issue by samm1735** [dotnet/maui#18928]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by davidortinau** [comment]
Hmm, I don't know why that would be. Maybe you don't have more than 1 version of .NET installed? I have 7 and 8, and I just tested Windows VS 2022 17.8 again. I see it. 

You mean this screen, right?

<img width="1055" alt="Screenshot 2023-11-21 at 2 04 40 PM" src="https://github.com/dotnet/maui/assets/41873/a4954111-4510-423d-8479-acbd28ca7891">

My version:

<img width="361" alt="Screenshot 2023-11-21 at 2 05 18 PM" src="https://github.com/dotnet/maui/assets/41873/52333046-7950-4197-97c9-d99550edfb1c">
