### ISSUE TITLE
After installing .NET 8, the MAUI workload does not work in vscode. [macos] [vscode]

### ISSUE THREAD

**Issue by mcyenikoylu** [dotnet/maui#18935]
### Description

Yes, after installing .NET 8.0.100 SDK, the MAUI workload does not work in vscode. The operating system is MacOS Ventura. IDE: vscode, last update. Other SDKs. .NET 7.0.11

SS:
[Imgur](https://i.imgur.com/MhBaX8r.png)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

macOS

### Affected platform versions

Ventura 13.2 (22D49)

**Comment by DDHSchmidt** [comment]
Have you tried the command line
` sudo dotnet workload install maui` (emphasis on **sudo**) ?

I didn't see that in the screenshot you posted and the command line pretty much says you're lacking permissions.

**Comment by mcyenikoylu** [comment]
> Have you tried the command line ` sudo dotnet workload install maui` (emphasis on **sudo**) ?
> 
> I didn't see that in the screenshot you posted and the command line pretty much says you're lacking permissions.

Yes, I tried as sudo. I didn't get any results. Since I restarted the computer and opened a new terminal screen, it does not "sudo" appear in the terminal.

**Comment by mcyenikoylu** [comment]
I uninstalled the .NET MAUI Extension, restarted my computer and installed it again. The code "dotnet workload install maui" worked. However, some packages are installetion in older versions. Is this normal? Please see the screenshot. Some bakkets install as .NET 7, some as .NET 8.

https://imgur.com/gallery/X0dc7aT

**Comment by activa** [comment]
It's normal that both .NET7 and .NET8 components are being installed. You can still develop for .NET 7 if you want.

**Comment by mcyenikoylu** [comment]
Yes, all IOS and Android packages have been installed (it took a very long time.) and everything works as it should. Thanks.
SS: https://imgur.com/gallery/Jk9Rbya
