### ISSUE TITLE
keyboard problem

### ISSUE THREAD

**Issue by blyatArtem** [dotnet/maui#18939]
### Description

Keyboard bug

https://github.com/dotnet/maui/assets/91653434/4e7a0390-4ce3-4861-aa6c-4667aec08d04

### Steps to Reproduce

<StackLayout>
<CollectionView VerticalOptions="EndAndExpand"/>
</StackLayout>

### Version with bug

7.0.59

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by drasticactions** [comment]
Without knowing how you wrote your layout, this will be extremely hard to debug. If you could create a project showing this error that would help out a lot.

**Comment by jfversluis** [comment]
Additionally, try .NET 8 and see if we maybe fixed it there already!

**Comment by blyatArtem** [comment]
> Without knowing how you wrote your layout, this will be extremely hard to debug. If you could create a project showing this error that would help out a lot.

https://github.com/blyatArtem/VKanave/blob/master/VKanave/Views/ChatPage.xaml.cs
