### ISSUE TITLE
[Windows] Setting IsClippedToBounds="True" inside a Border control will crash on Windows

### ISSUE THREAD

**Issue by activa** [dotnet/maui#18937]
### Description

Whenever a layout inside a `<Border>` control has `IsClippedToBounds="True"`, the app will crash on Windows. It's working fine on iOS and Android

For example, this will crash on Windows:
```
<Border>
    <StackLayout IsClippedToBounds="True"></StackLayout>
</Border>
```

The same issue is happening with .NET 7. Didn't test .NET 6

### Link to public reproduction project repository

https://github.com/activa/MauiBugClippedToBounds

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Relevant log output

```shell
When launching a debug build, the error message says "An unhandled Win32 error occurred"
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on Windows 11 and MacCatalyst, not repro on Android 14.0-API34 and iOS 17.0 with below Project:
[18937.zip](https://github.com/dotnet/maui/files/13765175/18937.zip)

**Comment by olekssmyk** [comment]
I also see that crash only on Windows

**Comment by activa** [comment]
Is this ever going to be fixed? This bug was reported 8 months ago.

**Comment by Migoked** [comment]
Bug is still there, please fix it.
