### ISSUE TITLE
Using Nightly builds (8.0.0-nightly) breaks packages that require >= 8.0.3

### ISSUE THREAD

**Issue by drmaven** [dotnet/maui#18931]
### Description

Some packages that require the latest version of .NET Maui (currently 8.0.3) do not accept the nightly builds as newer.

What is the workaround for this?

Thank you!

### Steps to Reproduce

1. Add nightly build as per https://github.com/dotnet/maui/wiki/Nightly-Builds
```
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.0-nightly.9643"/>
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.0-nightly.9643"/>
```

2. Add culprit package:

`<PackageReference Include="CommunityToolkit.Maui" Version="7.0.0" />`

4. Error:
Detected package downgrade: Microsoft.Maui.Controls from 8.0.3 to 8.0.0-nightly.9643. Reference the package directly from the project to select a different version. 
App.MAUI -> CommunityToolkit.Maui 7.0.0 -> Microsoft.Maui.Controls (>= 8.0.3) 
 App.MAUI -> Microsoft.Maui.Controls (>= 8.0.0-nightly.9643)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

**Comment by berhir** [comment]
Same error when a package requires a version newer than RC because nightly builds are treated as older than RC.

```
Detected package downgrade: Microsoft.Maui.Controls from 8.0.0-rc.1.9171 to 8.0.0-nightly.9637. Reference the package directly from the project to select a different version. 
App.MAUI -> Prism.Maui 9.0.271-pre -> Microsoft.Maui.Controls (>= 8.0.0-rc.1.9171) 
App.MAUI -> Microsoft.Maui.Controls (>= 8.0.0-nightly.9637)
```

**Comment by doriangh** [comment]
Same problem here, I'm just hoping a new version of .NET Maui will come soon. I've paused development on .NET 8, and keep fixing issues with porting the app from XF to .NET Maui, but with .NET 7.

**Comment by jfversluis** [comment]
@rmarinho is this fixed by just updating the `GitInfo.txt`?

**Comment by BerndStoltefuss** [comment]
I use `<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.0-nightly.9649" **NoWarn="NU1605"**/> <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.0-nightly.9649" **NoWarn="NU1605"**/>`

to bypass the error. Direct PackageReference should override any transitive references, so the nightly should be used i think.

**Comment by drmaven** [comment]
Great, thanks! I hope it's merged soon and that Gitinfo will be updated upon every maui release.
