### ISSUE TITLE
[regression/8.0.3]  Shell.NavBarIsVisible is not working on iOS

### ISSUE THREAD

**Issue by ka4ep** [dotnet/maui#18948]
### Description

I have a shell page with defined Shell.NavBarIsVisible="false". When I was using .NET 7.0.101, the bar with the 'hamburger' button is hidden on both Android and iOS.
After upgrading from MAUI 7.0.101 to 8.0.3, the bar is still visible on iOS. It's hidden on Android as expected.

### Steps to Reproduce

1. Create a new MAUI app from template and choose framework .NET7 or .NET8.
2. In the AppShell.xaml <Shell /> tag add lines:
    Shell.FlyoutBehavior="Flyout"
    Shell.NavBarIsVisible="False"
3. Compile and run on Android/iOS device or simulator.
4. On iOS .NET 8, the navigation bar is visible, even when stated otherwise.

### Link to public reproduction project repository

https://github.com/ka4ep/Maui.NavBar.Repro

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

iOS 15-17

### Relevant log output

```shell
Relevant .log files are in GitHub repository.
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on iOS 17.0, MacCatalyst and Windows 11, not repro on Android 14.0-API34 with below Project:
[NavBar8.zip](https://github.com/dotnet/maui/files/13770221/NavBar8.zip)

**Comment by jbfranklin** [comment]
So I assume this is getting fixed?

**Comment by KevinJalais** [comment]
Hello,
I see that @jsuarezruiz created a pull request that fix the issue.
When this will be release?

I am working on a migration from Xamarin to MAUI and my customer is waiting for this bug fix to release the app on the stores.
Having this ugly navigation bar displayed with no possibility to hide it is a strong impediment.

Please, send some update that I can communicate to my customer.

Many thanks.

**Comment by johannes-steurer** [comment]
Any update on when this is planned to be fixed?
It's still there on version 8.0.6 and I cannot see a fix for 8.0.7.
It's a blocking point for us!
Any workaround you can suggest?

**Comment by KevinJalais** [comment]
@johannes-steurer, on my side, the problem has been resolved with version 8.0.7.
If you use a `NavigationPage` you can set `NavigationPage.SetHasNavigationBar(this, false);` in your code behind (`.xaml.cs` file).

I acknowledge that it has not been resolved for `Shell` component, but as long as I use `NavigationPage` it's temporary satisfying.

**Comment by johannes-steurer** [comment]
@KevinJalais thanks for the quick feedback. as I use Shell the workaround does not work for me.

**Comment by JakodeWet** [comment]
Has there been any update on this? I see the PR is still open.
This is a blocker for us as we use Shell navigation and the workaround doesn't work for us.

**Comment by dbSoft-SoftwareSolutions** [comment]
We have the same issue

**Comment by JakodeWet** [comment]
Ok, so we found a workaround. You can add the Shell.NavBarIsVisible=False property to your actually page and not the Shell itself. If you have a ContentBasePage, adding it there also works.
Currently we have it on our ContentBasePage and not in the Shell itself and its working.

**Comment by msrockswell** [comment]
You can write a handler for iOS to solve this problem. 

MauiProgram.cs
![image](https://github.com/dotnet/maui/assets/85175911/bfb9337c-e526-48f9-8786-44d2d8e40ae4)

Platforms/iOS/AppShell.cs
![image](https://github.com/dotnet/maui/assets/85175911/ba5882f0-9103-42ea-a0fb-6a38a70a8979)
