### ISSUE TITLE
Unable to deploy to iphone from VS 2022 

### ISSUE THREAD

**Issue by sabrigo** [dotnet/maui#18947]
### Description

unable to deploy to iPhone.

my iPhone is running on version 17.1.1 and Xcode is in version 15.0.1

VS: Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.8.1

Error		error MT1045: Failed to execute 'devicectl': 'devicectl -j /var/folders/9_/dj9xmnzx6yx1zkb8fymb2gsh0000gn/T/tmp0NbO13.tmp device install app --device "<device name>" /Users/sabgo/Library/Caches/Xamarin/mtbs/builds/MauiApp3/8caa5ad3d685cb171e60d2fa52180568d2c53ec3fe5c0ddd40f07cfd9bb7784f/bin/Debug/net8.0-ios/ios-arm64/device-builds/iphone14.2-17.1.1/MauiApp3.app' returned the exit code 1.		 	0		

### Steps to Reproduce

1. Create a new .NET MAUI App
2. simply connect to your iphone device running the latest OS version1
3. run to deploy to the phone.

### Link to public reproduction project repository

https://github.com/sabrigo/IconNotShowingIniOS

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.1.1

**Comment by adamkrist1** [comment]
same issue except Xamarin, and Xcode is 15.0 (15A240d)
error MT1045: Failed to execute 'devicectl': 'devicectl -j /var/folders/yr/3kfdg/T/tmpTin0wV.tmp device install app --device ""/Users/ak/Library/Caches/Xamarin/mtbs/builds/Sp.iOS/57d43/bin/iPhone/Debug/device-builds/iphone15.5-17.1.1/Sp.iOS.app' returned the exit code 1.		 	0

**Comment by sabrigo** [comment]
I have reported bug at VS for Windows 

https://developercommunity.visualstudio.com/t/Unable-to-deploy-to-iphone-from-VS-2022/10523574?port=1025&fsid=5a9ea203-9d65-40eb-84db-9410be2ddbcc

**Comment by ben-dean** [comment]
The top answer on this SO question fixed the issue for me. 

https://stackoverflow.com/questions/74128227/error-he0046-failed-to-install-the-app-simctl-returned-exit-code-72.

**Comment by last-Programmer** [comment]
I am also getting the error when deploying native ios application to remote device.
