### ISSUE TITLE
Icons in the Shell TitleView and Shell Toolbar items not displayed in iOS

### ISSUE THREAD

**Issue by sabrigo** [dotnet/maui#18946]
### Description

I am adding icons in the title view and toolbar items, however these arent displayed in iOS but in Android

![image](https://github.com/dotnet/maui/assets/34493700/71d0e53d-ce3e-4d41-832a-cfb626eef65b)

I have attached the github repo for the same to reproduce and also ve

### Steps to Reproduce

1. Create a new .Net MAUI app
2. Add TitleView and ToolbarItems in appshell.xaml
3. with some text and dummy image.

Run the application in iOS simulator

### Link to public reproduction project repository

https://github.com/sabrigo/IconNotShowingIniOS

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15 and up

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on iOS 17.0, Windows 11 and MacCatalyst, not repro on Android 14.0-API34 with below Project:
[IconNotShowingIniOS.zip](https://github.com/dotnet/maui/files/13770075/IconNotShowingIniOS.zip)

**Comment by sabrigo** [comment]
@jfversluis , Can this fix be pushed to .net 8 as well?  as .NET 8 is still LTS, shouldn't be covered there as well.  Plus I raised this issue on .NET 8

**Comment by jfversluis** [comment]
.NET MAUI does not have LTS releases: https://dotnet.microsoft.com/platform/support/policy/maui

So we're probably not going to backport this, sorry.

**Comment by sabrigo** [comment]
that is completely unfair. I raised this issue last November 2023, it doesn't make sense to have separate menu for Android and iOS, which makes .NET MAUI useless.
