### ISSUE TITLE
[regression/8.0.3] creating MSIX is not working

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#18957]
### Description

I moved from NET 7 to net 8.

I tried to create msix as follow:

dotnet publish -f net8.0-windows10.0.19041.0 -c Release /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d"

Lanungh it and **is not open**.
The app run in vs.

I installed also sdk 8.0.100
![image](https://github.com/dotnet/maui/assets/1079689/f30935b0-481c-42a7-8161-03a89a9a9c17)

Thanks in advance,

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

NO.

### Relevant log output

```shell
I have feeling that the sdk 8.0.100 is not the correct.
```

**Comment by danies8** [comment]
Added log from eent viewer:
[exe.txt](https://github.com/dotnet/maui/files/13466251/exe.txt)
[exe2.txt](https://github.com/dotnet/maui/files/13466252/exe2.txt)

I  tried publish both msix and exe(added :RuntimeIdentifierOverride) and both crached i added logs from event viewer.

MSIX:

dotnet publish -f net8.0-windows10.0.19041.0 -c Release /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d" -p:RuntimeIdentifierOverride=win10-x64

EXE(Unpacked)

dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None  -p:WindowsAppSDKSelfContained=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d" -p:RuntimeIdentifierOverride=win10-x64

**Comment by danies8** [comment]
Can you please answer ?

**Comment by danies8** [comment]
Could you please answer?

**Comment by jfversluis** [comment]
You might want to try this https://github.com/dotnet/maui/issues/19456#issuecomment-1885008820
