### ISSUE TITLE
[iOS] AbsoluteLayout not rendering child elements

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#18956]
### Description

AbsoluteLayout not rendering child elements.
![PositionAbsolute](https://github.com/dotnet/maui/assets/6755973/5c3ee759-e923-45ca-b646-b7ecb577bc7e)
The same code running on Android:
![PositionAbsolute](https://github.com/dotnet/maui/assets/6755973/ab5a44e1-5ee0-4d58-8ce1-5fc43eea4ded)

### Steps to Reproduce

1. Download or sync https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Layouts/AbsoluteLayoutDemos
2. Launch the sample on iOS.
3. Navigate to the Chesboard sample.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Layouts/AbsoluteLayoutDemos

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by davidortinau** [comment]
I don't see this issue on 8.0.6, 8.0.7. I reviewed the code and am running the same layout etc. I reviewed all the AbsoluteLayout samples I have and they are working. 

Please review with the latest release and open a new issue with a repro sample if needed.

![Simulator Screenshot - iPhone 15 Pro - 2024-02-29 at 12 58 18](https://github.com/dotnet/maui/assets/41873/9f96a058-67f9-4b52-ad48-1a754fae16e2)
<img width="922" alt="Screenshot 2024-02-29 at 12 54 59 PM" src="https://github.com/dotnet/maui/assets/41873/ef11f8f6-b543-44e9-a725-6a30d8577743">
