### ISSUE TITLE
Safe area layout guide not working in MAUI .NET8 on iOS 17.1.1

### ISSUE THREAD

**Issue by thomasbach-dk** [dotnet/maui#18969]
### Description

Safe area is not respected after upgrading to .NET 8. The problem occurs on an iPhone 14 Pro with iOS 17.1.1.

![image](https://github.com/dotnet/maui/assets/16226473/aab21558-5a11-42b0-9a3c-1361902de765)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

17.1.1

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
https://github.com/drasticactions/MauiRepros/tree/main/SafeGuideTest

Disabling and enabling `UseSafeArea` on a template and Shell app on an iPhone 14 Pro with 17.1.1, I can't replicate this behavior. 

![IMG_4932E4E927EB-1](https://github.com/dotnet/maui/assets/898335/8f8b2041-c5d0-44f1-8f22-f86dc2a1497d)

Could you create a reproduction project showing what you're doing?

**Comment by thomasbach-dk** [comment]
I forgot to mention that I´m using MAUI Blazor. I´ll try explicitly set `UseSafeArea `to **True** to see if that makes any difference for me.

**Comment by thomasbach-dk** [comment]
I was able to fix the issue by setting UseSafeArea explicitly within MainPage.xaml

![image](https://github.com/dotnet/maui/assets/16226473/4cb45b84-7f0c-4705-9656-07e5417efe47)

Closing issue.
