### ISSUE TITLE
IsEnabled not working properly for layout

### ISSUE THREAD

**Issue by mosinms7711** [dotnet/maui#18977]
### Description

IsEnabled not working properly for layout. I have tried this with StackLayout and Grid Layout with UWP in MAUI.

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

**Comment by mattleibow** [comment]
Can you try net8?

![image](https://github.com/dotnet/maui/assets/1096616/4eeecec9-4e96-46bb-bd92-4a40219494c2)
