### ISSUE TITLE
[Enhancement] Hit Testing service for element selection

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#1897]
## Summary
Given an `point` or `rect`, return an element or list of elements that are contained on or in that point. This service is necessary for being able to do element selection within features like Hot Reload or Live Preview, where a user can use an element selector to pick an object they want to know more about.

This ask is similar to https://github.com/dotnet/maui/issues/572, which requires the same functionality in order to draw adorners.

**Comment by rmarinho** [comment]
this was done already right @drasticactions  ?
