### ISSUE TITLE
Page Layout is not applied correctly

### ISSUE THREAD

**Issue by ozersenol** [dotnet/maui#18984]
### Description

Page Layout has problem when I change project to net7.0-ios to net8-ios on MAUI Blazor App. There is no difference  on page codes and  layout or css files. 

<img width="414" alt="Screenshot 2023-11-23 at 16 38 03 jpeg" src="https://github.com/dotnet/maui/assets/44838125/b750ea35-51f4-4a41-bee5-5c12bf2607ea">

<img width="414" alt="Screenshot 2023-11-23 at 16 31 13 jpeg" src="https://github.com/dotnet/maui/assets/44838125/1393180b-bc6e-4168-bbb6-262e5c812f59">

```
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
    <ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <ProvisioningType>automatic</ProvisioningType>
    <OptimizePNGs>True</OptimizePNGs>
    <RuntimeIdentifiers>ios-arm64</RuntimeIdentifiers>
    <CreatePackage>false</CreatePackage>
    <CodesignKey>MY CODE SIGN</CodesignKey>
    <CodesignProvision>ppAdHoc</CodesignProvision>
    <ArchiveOnBuild>True</ArchiveOnBuild>
    <NoSymbolStrip>true</NoSymbolStrip>
    <UseInterpreter>True</UseInterpreter>
    <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
  </PropertyGroup>
```

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

17.1.1

**Comment by Eilon** [comment]
Hi @ozersenol , can you share a repro for this issue? What does the XAML and HTML look like? Also, is the vertical "..." button part of the HTML UI, or is it a native platform control?

This button:

![image](https://github.com/dotnet/maui/assets/202643/ca769c2d-bc2a-4916-99f3-2348ab5b53c2)
