### ISSUE TITLE
Button HeightRequest value not applying lesser than default value

### ISSUE THREAD

**Issue by venkatkonda** [dotnet/maui#18999]
### Description

If we set HeightRequest value to lesser than default value not applying, if we give 20 not applying in Windows, but in Android it is working fine.

### Steps to Reproduce

1. Create MAUI Project.
2. Add Button like  `<Button Text="Small Button" HeightRequest="15" />`
3. Run the application in Windows and check.

### Link to public reproduction project repository

https://github.com/venkatkonda/ButtonHeightIssue

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on Windows 11, iOS 17.0 and MacCatalyst, not repro on Android 14.0-API34 with below Project:
[ButtonHeightIssue.zip](https://github.com/dotnet/maui/files/13785593/ButtonHeightIssue.zip)

**Comment by devanathan-vaithiyanathan** [comment]
Hi @venkatkonda ,
The MinimumHeightRequest in Style.xaml is set to 44, which sets the default height for buttons. To use a smaller height, you need to override this value directly on your button in MainPage.xaml  like this,

```
<Button Text="Small Button"
**MinimumHeightRequest="15"**
HeightRequest="15" FontSize="8" WidthRequest="100" Padding="0" Margin="0"/>
```

Another approach is to change the MinimumHeightRequest for the Button control in Style.xaml
```
<Style TargetType="Button">
        .
	.
	.
    **<Setter Property="MinimumHeightRequest" Value="15"/>**
    <Setter Property="MinimumWidthRequest" Value="44"/>
</Style>
```

**Comment by venkatkonda** [comment]
Thank you, It is working fine now.
