### ISSUE TITLE
TapGestureRecognizer disregards parent's IsEnabled status on iOS and Catalyst.

### ISSUE THREAD

**Issue by derlidio** [dotnet/maui#18995]
### Description

A TapGestureRecognizer will not obey the IsEnabled status of its parent on iOS and Catalyst. It will register touch actions and trigger its Tapped method. Do not happen on Android. Not tested on Windows.

### Steps to Reproduce

1. Clone the attached repo
2. Build and Run on iOS Simulator or Catalyst

The "Click me too" button (composed by a Grid, a BoxView and  a Label) under the normal Button should not be clickable, but it is.

### Link to public reproduction project repository

https://github.com/derlidio/TapGestureBug.git

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 17, macOS Sonoma 14.1.1 (23B81)

### Did you find any workaround?

No workaround besides checking for the control IsEnabled state on it's Tapped method.

**Comment by NXDMN** [comment]
Same here. I use InputTransparent to workaround
```
Microsoft.Maui.Handlers.ContentViewHandler.Mapper.AppendToMapping(nameof(VisualElement.IsEnabled), (handler, view) =>
{
    (view as VisualElement).InputTransparent = !view.IsEnabled;
});
```

**Comment by tjiakwokyung28** [comment]
tapgesture in net 7 better than net 8, net 8 many having problem

**Comment by metalium84** [comment]
I'm facing the same issue within a DataTemplate.
Parents with disregarded IsEnabled properties I found: Grid, Frame
Parent with regarded IsEnabled property: ViewCell

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on iOS 17.0 and MacCatalyst, not repro on Windows 11 and Android 14.0-API34 with below Project:
[TapGestureBug.zip](https://github.com/dotnet/maui/files/13784838/TapGestureBug.zip)

**Comment by BlotskiyDmitriy** [comment]
This problem is still relevant. I noticed that it plays on all platforms except Android. I also studied and noticed that on all these platforms except Android, IsEnabled is not implemented in the gesture class.
