### ISSUE TITLE
Missing PKGBUILD?

### ISSUE THREAD

**Issue by Whodiduexpect** [dotnet/maui#190]
I’ve always used the PKGBUILD from the official KDE Gitlab repo to build Maui, but this mirror doesn’t seem to have one. Is there an alternate way to build the package?

**Comment by vdvman1** [comment]
I think you are mixing this project up with a different project that goes by a very similar/the same name, this is not a mirror of the KDE Maui project, this is an entirely new project

**Comment by Whodiduexpect** [comment]
This is a different UI framework also called Maui? Is it associated with the KDE Maui Project? It's hard to believe that two completely different frameworks which accomplish similar things be called the exact same thing. But in that case, thanks for the heads up.
