### ISSUE TITLE
[regression/8.0.3] Scrollview scrolling does not work in MAC and iOS platforms

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#19005]
### Description

Scrollview scrolling not works properly in.NET 8 and it works correctly in .NET 7. Horizontal stack layout added as the content of scroll view when adding items to the horizontal stack layout, not able to scroll to the newly added last item and also scrolling to the first item there is some space occur. This issue is reproduced on MAC and iOS platforms.

### Steps to Reproduce

1. Run the sample from the below link
https://github.com/jeya-kasipandi/ScrollviewIssue/tree/main/scrollviewissue 
3. Click the button to add a child inside the horizontal stack layout.
4. Now scroll the scroll view to the newly added last item.
5. See the output 
Not able to scroll to the end of the newly added item.
If scroll to the first item, the scroll view is shown with some space.
Attached video for your reference.
MAC
https://github.com/dotnet/maui/assets/92785406/bdaeb1b2-c50d-4ed8-a80c-882ce9f2a3fa 
iOS
https://github.com/dotnet/maui/assets/92785406/b1ca7e1e-d8ae-409b-9b19-828e8ba561fa

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 17.0

**Comment by jeya-kasipandi** [comment]
Please give high priority to this issue

**Comment by Ahamed-Ali** [comment]
This issue occurs on Android and windows also .
   <StackLayout >  
       <ScrollView Orientation="Vertical">
           <StackLayout>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>

               <Entry HeightRequest="200" BackgroundColor="Red"/>
               <Entry HeightRequest="200" BackgroundColor="Red"/>
           </StackLayout>
       </ScrollView>
   </StackLayout>

**Comment by jaosnz-rep** [comment]
Verified this issue with Visual Studio for Mac 17.6.9 build 415, not repro on .NET 8 iOS platform with sample project.
![Notrepro](https://github.com/dotnet/maui/assets/82628041/0510202a-5209-4840-ab58-fd8d6e1c26ef)
