### ISSUE TITLE
Publish iOS App via cmd - Asset Validation failed

### ISSUE THREAD

**Issue by Yannikk1996** [dotnet/maui#19008]
### Description

I am trying to publish my maui app via cmd to the app store by generating an ipa and uploading it with the transporter. 
Publishing the ipa via cmd and using the ipa file from \bin\Release\net8.0-ios\ios-arm64 throws the following error messages:
![Error](https://github.com/dotnet/maui/assets/33956727/5fea60bd-52f6-4d66-bc11-a928e2fe3d7d)

Publishing with visual studio and saving the ipa file works.

### Steps to Reproduce

Generate ipa with following command:
`dotnet publish AbsoluteProjectPath -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="xxx" -p:CodesignProvision="xxx" -p:IsPublishing=true -p:ServerAddress="xxx" -p:ServerUser="xxx" -p:ServerPassword="xxx" -p:TcpPort=58181 -p:_DotNetRootRemoteDirectory="xxx" `

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@rolfbjarne thoughts?

**Comment by rolfbjarne** [comment]
This is strange, there should be no differences between the command-line and the IDE build.

The .ipa files are just .zip files, so could you inspect them to see if there are differences inside in which files they contain? Alternatively can you attach a working and a failing .ipa?

**Comment by Yannikk1996** [comment]
I checked both .ipa files and noticed that the one working has one additional file: MauiInfo.plist. The one not working has only Info.plist. 

For further information my project contains an additional Maui Class Library.

**Comment by rolfbjarne** [comment]
Can you get a binlog for the failing build by adding `-p:msbuild.binlog` and then attaching the resulting msbuild.binlog file here?

**Comment by rolfbjarne** [comment]
Ops, sorry, it's `-bl:msbuild.binlog`

**Comment by Yannikk1996** [comment]
In the project file were the following parameters that caused the issue:
`<MtouchProfiling>True</MtouchProfiling>
<ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>`
