### ISSUE TITLE
App size is too large in Release mode with several native binded libraries

### ISSUE THREAD

**Issue by espritm** [dotnet/maui#19019]
### Description

I am rewritting a native Android and iOS application into a single MAUI application.
This application uses 4 main native libraries, that I have binded successfully.

Those native libraries has many dependancies, like com.vonage:webrtc which is a 200MB aar for instance.

For iOS, the final Release ipa is 210Mb, versus 50MB with the one built in native with Swift and xCode.
For Android, the final Release apk is 400MB, versus 90MB with the one build in native with Java and Android Studio.

In Debug, apk size is 49MB... And the limit to publish an app to the Play Store is 200MB. 

How can I reduce the size please ? Is it an issue with binded library ?
 I really need to go under 200MB, else it is a show stopper :x After months of binding, I cannot believe it.

I've tried to follow those advices https://devblogs.microsoft.com/dotnet/dotnet-7-performance-improvements-in-dotnet-maui

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by drasticactions** [comment]
If you have questions over binding, you may want to move them to [xamarin-macios](https://github.com/xamarin/xamarin-macios) and [xamarin-android](https://github.com/xamarin/xamarin-android). This repo is for the MAUI UI project.

**Comment by espritm** [comment]
Following @drasticactions recommandations I close the ticket.
I have created https://github.com/xamarin/xamarin-android/issues/8530 instead
