### ISSUE TITLE
WebView in android forget user login credentials every app restart

### ISSUE THREAD

**Issue by MichaelAzzer** [dotnet/maui#19010]
### Description

I am developing app with .net maui that contains webview to open a website, this website need user login the problem is if user logged in the website and closed the app and reopen it again website need user to login again this behavior in android only I tested it in windows it works with no problems this problem begin with last update in visual studio and .net 8

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

Android

**Comment by MichaelAzzer** [comment]
I solved this problem by **flushing the native android webview cookies to sotrage** before terminating the app

**Comment by drasticactions** [comment]
I don't think this is an issue with the MAUI WebView implementation. Trying this with an Android WebView without the MAUI UI Framework, it performs similarly, where you need to handle the cookies instance yourself and it's not stored as part of some shared session. Having some system like that would need to be added to the MAUI Implementation.

**Comment by MichaelAzzer** [comment]
The problem in .net maui is cannot access cookies manager from .net maui webview it always return null, If you need to deal with cookies you should to deal with native Android webkit
