### ISSUE TITLE
Target Android Framework Not Settable Via UI 

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#19024]
### Description

The project properties dialog Application section under "Android Targets" has a couple of drop-down boxes to set "Target Android Framework" and "Minimum Target Android Framework" however, the drop downs are both empty. 

### Steps to Reproduce

1. Create a default MAUI program and build it for android
2. Check Properties/Application/Android Targets the input boxes will be empty and so will the pulldowns.
![2023-11-24_14-31-31](https://github.com/dotnet/maui/assets/12423046/49d574e0-f342-4160-827f-aff95ccfb2ea)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Windows 11

### Did you find any workaround?

Yes, either edit the android manifest directly or by using the manifest editor in Properties/Android?

**Comment by drasticactions** [comment]
This is Visual Studio tooling specific for Android, and not controlled under this repo.

**Comment by david-maw** [comment]
ok, will do. Until then, is there a way to edit the project file to avoid the following warning about mismatched levels?
`...AndroidManifest.xml : warning XA4211: AndroidManifest.xml //uses-sdk/@android:targetSdkVersion '33' is less than $(TargetFrameworkVersion) ''. Using API-34 for ACW compilation.
`
I generally prefer to suppress warnings I understand so as not to get in the habit of ignoring warnings in general. If not, oh well once #19027 is fixed the workaround can go away and I probably won't care anyway.

I've omitted the diatribe about, "you're one company, just transfer the incident report", because I've worked for a large corporation...

**Comment by david-maw** [comment]
Looks like it's already reported [here](https://developercommunity.visualstudio.com/t/Target-Android-framework-cannot-be-selec/10515664?ref=native&refTime=1700932462706&refUserId=87be68b7-e95b-4f21-a5ac-92dc4c3f90a9), I'll add my workaround and a back reference to this report. I'm still interested in a project file workaround if anyone has one.

**Comment by jfversluis** [comment]
Looks like this has already been reported in the right place and there is nothing much for us to do on our side for right now. Closing this as such, thanks!
