### ISSUE TITLE
BindingExpression.Apply null reference crash

### ISSUE THREAD

**Issue by Alex-Dobrynin** [dotnet/maui#19020]
### Description

Sometimes I'm getting this exception and app crash. What is interesting, I even don't know where it happens

D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs, line 57
System.NullReferenceException: Object reference not set to an instance of an object.

![image](https://github.com/dotnet/maui/assets/23138430/20f80af8-a76b-47ee-b3bb-6ba3d362b1fc)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

nope

### Relevant log output

```shell
BindingExpression.Apply (Boolean fromTarget) D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:57
Binding.Apply (Boolean fromTarget) D:\a\_work\1\s\src\Controls\src\Core\Binding.cs:115
BindableObject.SetValueActual (BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:627
BindableObject.SetValueCore (BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:559
BindingExpression.ApplyCore (Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:163
BindingExpression.Apply (Object sourceObject, BindableObject target, BindableProperty property, SetterSpecificity specificity) D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:78
Binding.ApplyRelativeSourceBinding (BindableObject targetObject, BindableProperty targetProperty, SetterSpecificity specificity) D:\a\_work\1\s\src\Controls\src\Core\Binding.cs:174
System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
System.Threading.ThreadPoolWorkQueue.Dispatch()
System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
System.Threading.Thread.StartCallback()
```

**Comment by PureWeen** [comment]
@Alex-Dobrynin do you have a sample of the xaml that this RelativeSourceBinding is getting applied to?

**Comment by Alex-Dobrynin** [comment]
@PureWeen 
It could be even the last one of my answer above, because I got this right now
![image](https://github.com/dotnet/maui/assets/23138430/f8a939ab-55c9-47f5-b466-e4737a05463b)

**Comment by Alex-Dobrynin** [comment]
@StephaneDelcroix your 'strongly believe' is reason to close the issue. It's something new to me.
In my app I don't have any place where I use another threads except UI, because I don't need it. If you don't have explanations for NRE in that place, this does not mean that your colleagues don't have.
But thanks, I got your position. Each such case (when you close tickets, just because you 'strongly believe') I lean more and more in favor of another UI framework

**Comment by StephaneDelcroix** [comment]
@Alex-Dobrynin as I said, feel. free to reopen the ticket with a reproduction project. I actually spent quite some time today investigating this, and I'm not closing this ticket lightly.
