### ISSUE TITLE
ERROR WHILE COMPLETING THE .NET MUAI 

### ISSUE THREAD

**Issue by abhinav-232** [dotnet/maui#19034]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

ERROR:- Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 13, Reason: 'com.companyname.jrr_immigrations' violates pattern constraint of '[-.A-Za-z0-9]+'.
The attribute 'Name' with value 'com.companyname.jrr_immigrations' failed to parse.	JRR Immigrations			

WINDOWS 11

**Comment by SokoFromNZ** [comment]
Are you using Visual Studio 2022 v17.8.x?
I cannot publish my existing MAUI app anymore. 3 weeks ago everything worked fine!
