### ISSUE TITLE
[UITEST] CollectionView Enable Legacy Tests

### ISSUE THREAD

**Issue by jfversluis** [dotnet/maui#19050]
Below are all the (legacy) UI tests identified as being a part of the tests that cover `CollectionView` and have been disabled at this time. These should al be reenabled by checking if the test (still) fails and if yes, fix it one way or the other.

Note that there might be more tests associated to this area that haven't been properly identified yet. Feel free to also include those and please add them here.

**iOS**

- [x] CollectionViewBindingErrorsShouldBeZero (src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewBindingErrors.xaml.cs)
- [x] ItemsFromViewModelShouldBeSelected (src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewBoundMultiSelection.cs)
- [x] CollectionViewItemsSourceTypesDisplayAndDontCrash (src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewItemsSourceTypes.cs)
- [x] KeepScrollOffset (src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewItemsUpdatingScrollMode.cs)
- [x] KeepLastItemInView(src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewItemsUpdatingScrollMode.cs)
- [ ] CollectionViewItemsLayoutUpdate (src\Compatibility\ControlGallery\src\Issues.Shared\Issue5354.xaml.cs)
- [x] ClearingGroupedCollectionViewShouldNotCrash (src\Compatibility\ControlGallery\src\Issues.Shared\Issue8899.cs)
- [x] EmptyViewShouldNotCrash (src\Compatibility\ControlGallery\src\Issues.Shared\Issue9196.xaml.cs)
- [x] InitiallyInvisbleCollectionViewSurvivesiOSLayoutNonsense(src\Compatibility\ControlGallery\src\Issues.Shared\Issue12714.cs)
- [x] CollectionViewShouldSourceShouldResetWhileInvisible (src\Compatibility\ControlGallery\src\Issues.Shared\Issue13126_2.cs)
- [x] CollectionViewShouldSourceShouldUpdateWhileInvisible (src\Compatibility\ControlGallery\src\Issues.Shared\Issue13126.cs)
- [x] CollectionShouldInvalidateOnVisibilityChange (src\Compatibility\ControlGallery\src\Issues.Shared\Issue13203.cs)
- [x] VisitAndUpdateItemsSource (src\Compatibility\ControlGallery\src\UITests.Shared\Tests\CollectionViewUITests.cs)

**Android**

- [x] SelectionShouldUpdateBinding (src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewBoundSingleSelection.cs)
- [ ] CollectionViewInfiniteScroll (src\Compatibility\ControlGallery\src\Issues.Shared\Github5623.xaml.cs)
- [x] AddingItemToUnviewedCollectionViewShouldNotCrash (src\Compatibility\ControlGallery\src\Issues.Shared\Issue7700.cs)
- [x] AddingGroupToUnviewedGroupedCollectionViewShouldNotCrash (src\Compatibility\ControlGallery\src\Issues.Shared\Issue7700.cs)

**Comment by tjiakwokyung28** [comment]
create rows and columns maui Grid does not work in net 8.

xaml
<columnDefinition width = 5*/>
<columnDefinition width = 50/>
<columnDefinition width = auto/>

code???? this not working
var clm1 = new columnDefinition () width = new gridlength(5,gridunittype.star)};
var clm2 = new columnDefinition () width = new gridlength(50,gridunittype.absolute)};
var clm3 = new columnDefinition () width = new gridlength(5,gridunittype.auto)};

**Comment by jsuarezruiz** [comment]
`CollectionViewItemsLayoutUpdate (src\Compatibility\ControlGallery\src\Issues.Shared\Issue5354.xaml.cs)` requires DragCoordinates https://learn.microsoft.com/en-us/dotnet/api/xamarin.uitest.iapp.dragcoordinates?view=xamarin-uitest-sdk

**Comment by jsuarezruiz** [comment]
> `CollectionViewItemsLayoutUpdate (src\Compatibility\ControlGallery\src\Issues.Shared\Issue5354.xaml.cs)` requires DragCoordinates https://learn.microsoft.com/en-us/dotnet/api/xamarin.uitest.iapp.dragcoordinates?view=xamarin-uitest-sdk

Added here https://github.com/dotnet/maui/pull/19333

**Comment by jsuarezruiz** [comment]
`Issue5354` and `Github5623` requires the usage of the still not implemented **QueryUntilPresent** emthod.

**Comment by jsuarezruiz** [comment]
CarouselView 
- [x] Issue10300(src\Compatibility\ControlGallery\src\UITests.Shared\Tests\Issue10300.cs)
- [x] Issue11224(src\Compatibility\ControlGallery\src\UITests.Shared\Tests\Issue11224.cs)
- [x] Issue12193(src\Compatibility\ControlGallery\src\UITests.Shared\Tests\Issue12193.cs)
- [x] Issue12574 (src\Compatibility\ControlGallery\src\UITests.Shared\Tests\Issue12574.cs)
- [x] Issue12777(src\Compatibility\ControlGallery\src\UITests.Shared\Tests\Issue12777.cs)
- [x] Issue12848(src\Compatibility\ControlGallery\src\UITests.Shared\Tests\Issue12848.cs)
- [x] Issue13436(src\Compatibility\ControlGallery\src\UITests.Shared\Tests\Issue13436.cs)
- [ ] Issue13616(src\Compatibility\ControlGallery\src\UITests.Shared\Tests\Issue13616.cs)
- [ ] Issue7803(src\Compatibility\ControlGallery\src\UITests.Shared\Tests\Issue7803.cs)
- [ ] Issue9827(src\Compatibility\ControlGallery\src\UITests.Shared\Tests\Issue9827.cs)

**Comment by jsuarezruiz** [comment]
`Issue7803 `requires the usage of the still not implemented **QueryUntilPresent** method.
