### ISSUE TITLE
iOS Background Task is not getting executed in every 15 min time 

### ISSUE THREAD

**Issue by chetananandabbott** [dotnet/maui#19063]
### Description

Task registered using `BGTaskScheduler.Shared.Register` is not getting triggered in every 15 mins/ scheduled time.

There is not enough documentation available on iOS MAUI BG Libs. 

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by baaaaif** [comment]
This is nothing xamarin-ios or MAUI is responsible for. It's a pure iOS thing.
And Apples documentation is unfortunately let's call is thin -.-

It's a difference if yout want it to be executed while the app is in foreground, or while in background, or both.

maybe the MAUI shiny.net plugin (or it's source) will help you
https://shinylib.net/client/jobs/

**Comment by jfversluis** [comment]
As mentioned, this is just how iOS works and it seems a third-party library is involved. There is not much we van do about this on the .NET MAUI side. Hope you can figure it out!
