### ISSUE TITLE
Entry does not lose focus on tapping outside

### ISSUE THREAD

**Issue by cytoph** [dotnet/maui#19062]
### Description

In Xamarin when an `Entry` had focus and one tapped outside of that `Entry`, it got unfocused. In .NET MAUI this is no longer the case. I know about the `HideSoftInputOnTapped` property that was added in PR #4914, but this will only hide the keyboard, not get the `Entry` to lose focus. This bad, as I want to migrate my application from Xamarin and there I bind to the `IsFocused` property of an `Entry` to react to it.

This is kind of a follow-up to #4781 as the PR #4914 mentioned there only fixes half of the original issue (not hiding the keyboard).

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Add an `Entry`
3. [Optional] Add `HideSoftInputOnTapped="true"` to the containing `Page`
4. Tap on the `Entry`
5. Tap outside the `Entry`

Expected outcome: The `Entry` loses focus
Actual outcome: The `Entry` stays focused

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by PureWeen** [comment]
Duplicate #11881

@cytoph AFAIK it's not possible on Android pre-API 28 to unfocus the entry. You have to focus something. The way XF did this was to focus the page layout which completely breaks accessibility. 

https://github.com/dotnet/maui/issues/18854#issuecomment-1817143651

**Comment by cytoph** [comment]
> Duplicate #11881
> 
> @cytoph AFAIK it's not possible on Android pre-API 28 to unfocus the entry. You have to focus something. The way XF did this was to focus the page layout which completely breaks accessibility.
> 
> [#18854 (comment)](https://github.com/dotnet/maui/issues/18854#issuecomment-1817143651)

This could all be good and true, but fact is XF could do this (no matter how or if it broke accessibility) and .NET MAUI can't. You can't just remove/break more and more features but expect users to migrate to .NET MAUI as support for XF ends in May. How should we do this, if half of what developers used in XF and what is absolutely standard behavior doesn't work anymore in MAUI? Tapping outside the `Entry` is one thing, but it doesn't even lose focus - not even close the soft keyboard - when I confirm the input via soft keyboard (not to mention by pressing hardware enter, as this is also currently broken as described in #13921). In almost every app I know (besides maybe chat apps) when I complete an entry, that entry loses focus and the keyboard is hidden. Somehow those can do it, and so should .NET MAUI, as this is really a basic feature.

> What are the scenarios that you are using "IsFocused" for?

On the side of an entry in my view I have a button. This button is either a clear button or a back button. If text has been entered into the entry or if the the entry is focused, the button is a clear button. As soon as the entry loses focus while no text is entered, that clear button should change to a back button.

**Comment by samhouts** [comment]
Duplicate of #11881
