### ISSUE TITLE
Setting Shell.FlyoutWidth in code-behind on Windows throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by jeremy-visionaid** [dotnet/maui#19068]
### Description

Attempting to set the FlyoutWidth in C# on Windows throws:

```System.ArgumentOutOfRangeException: 'Non-negative number required. Arg_ParamName_Name'```

### Steps to Reproduce

Add the following to a button click event:
```
Shell.Current.FlyoutWidth = 260;
```

Actual: throws ArgumentOutOfRangeException
Expected: FlyoutWidth is adjusted to the specified value

### Link to public reproduction project repository

https://github.com/molesmoke/MauiTestApp/tree/flyoutwidth

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

Setting FlyoutWidth in xaml first appears to avoid the exception

**Comment by molesmoke** [comment]
@PureWeen One for your to review, please!

**Comment by mattleibow** [comment]
Thanks for the issue and PR!
