### ISSUE TITLE
vs2022 .net8.0 mauiAPP can't run

### ISSUE THREAD

**Issue by ikraddy** [dotnet/maui#19084]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	APT2067	failed processing manifest.
	MauiApp1	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\Xamarin.Android.Aapt2.targets	214	
错误	APT2260	resource mipmap/appicon (aka com.companyname.mauiapp1:mipmap/appicon) not found.

This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.	MauiApp1	F:\Develop\Projects\csharp\2023\MauiApp1\MauiApp1\Platforms\Android\AndroidManifest.xml	1	
错误	APT2260	resource mipmap/appicon_round (aka com.companyname.mauiapp1:mipmap/appicon_round) not found.

This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.	MauiApp1	F:\Develop\Projects\csharp\2023\MauiApp1\MauiApp1\Platforms\Android\AndroidManifest.xml	1

**Comment by mattleibow** [comment]
Can you attach a binlog so we can have a look: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

**Comment by ikraddy** [comment]
[MSBuildReproLogs.zip](https://github.com/dotnet/maui/files/13495433/MSBuildReproLogs.zip)
ok,here it is.

**Comment by crobinson-expl** [comment]
I get the same three errors on a file...new .NET MAUI App template project using .NET 8.0 in VS 2022 17.8.2.

All I did after creating the project was switch my debugging target to my Android local (emulator) device and right-click Rebuild on the solution, which only has the new project in it.

<img width="467" alt="image" src="https://github.com/dotnet/maui/assets/84980421/2d7f5cee-3d2f-4053-bd73-3a3809d57430">
<img width="528" alt="image" src="https://github.com/dotnet/maui/assets/84980421/1813a7f8-288e-46fe-b18e-e93b9d771aa7">

Here is the binlog file created from my Developer Powershell terminal in VS 2022 using command `dotnet build MauiApp1.csproj /bl:msbuild.binlog`: 
[msbuild_binlog.zip](https://github.com/dotnet/maui/files/13518086/msbuild_binlog.zip)

**Comment by mobycorp** [comment]
I've been getting these same three errors on a sporadic basis for the past several weeks. I can't tie it specifically to a MAUI or Visual Studio version. When I see these errors, I do a clean, exit, and restart VS. That will clear up this issue for a while. I also get errors about these files being "open by another process" way too often... This is very disruptive.

**Comment by Hrishikesh46779** [comment]
Same issue for me.
![image](https://github.com/dotnet/maui/assets/46864647/a8644183-3f51-4cd5-966b-9013c9779386)

**Comment by Hrishikesh46779** [comment]
I have attached .binlog see https://github.com/dotnet/maui/issues/18636#issuecomment-1863024634

**Comment by bcaceiro** [comment]
This just continues to happen several times. Still no workaround??

**Comment by Matt-17** [comment]
I just created a new MAUI app using .net8.0 and I had this issue. 

It helped me to edit .csproj file and remove everything targeting ios, maccatalyst and tizen. Don't know which one caused the issue. But it was writing about missing files for Android (like AndroidManifest.xml directly in project folder) - so definitely unrelated things.

**Comment by jfversluis** [comment]
We think that this might be solved by #21838. Please try the nightly feed or wait for a next release where this change is included. If this turns out not to be the case, please feel free to open a new issue about this and refer to this one, thanks!
