### ISSUE TITLE
Update manually Microsoft.Windows.Compatibility to 8 all icons disapper on windows

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#19096]
### Description

```
From:

<PackageReference Include="Microsoft.Windows.Compatibility" Version="7.0.0" />

To:

<PackageReference Include="Microsoft.Windows.Compatibility" Version="8.0.0" />
```

And all icons disappered.

![image](https://github.com/dotnet/maui/assets/1079689/b1bf520b-2f5d-4f2a-839e-14aa22ef118d)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by danies8** [comment]
Please see:  https://app.screencast.com/aNJLOaovPTGb3

**Comment by jfversluis** [comment]
I appreciate the effort, however that is not a reproduction. Please provide a small project that illustrates this issue. Or at the very least provide relevant code that you are using in this app. This will help us diagnose a potential problem much faster.

**Comment by danies8** [comment]
<Image  Grid.Row="0" Grid.RowSpan="3" Grid.ColumnSpan="3" Source="login_background.png" Aspect="Fill"/>
  <Image  Grid.Row="0" Grid.ColumnSpan="3" Source="gs_logo.png" WidthRequest="250" HeightRequest="110" HorizontalOptions="Start" VerticalOptions="Center"/>
  <Image  Grid.Row="2" Grid.ColumnSpan="3" Margin="0,0,0,30" Opacity="0.7" Source="wave.png" Aspect="Fill"/>

**Comment by danies8** [comment]
It fixed after clean and rebuild twise.

**Comment by danies8** [comment]
It fixed after clean and rebuild twise.
