### ISSUE TITLE
Cannot build iOS widget apps with extensions (ditto exited with code 1)

### ISSUE THREAD

**Issue by testformercury** [dotnet/maui#19104]
### Description

I'm trying to build an iOS app with widget support using Embedded WidgetKit while running the App I'm facing ditto issue the forms version of the app is working good facing ditto problem in maui

### Steps to Reproduce

Reference Video:https://www.youtube.com/watch?v=CJuLYvnxQTE

1.Create an App that supports widget in Xcode by referring the above Video.
2.Create the AppId and AppGroup for your App.
3.Run the App in Xcode it will generate a file in DerivedData Folder.
4.Copy the generated folder path and paste it in csproj file.
5.Run the Project in iOS Simulator now ditto error occurs.

### Link to public reproduction project repository

https://github.com/testformercury/MauiWidgetSample

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

**Comment by drasticactions** [comment]
@rolfbjarne Would this be a xamarin-macios issue? Do you know if there's documentation for supporting this for .NET iOS?

**Comment by testformercury** [comment]
[msbuild.binlog.zip](https://github.com/dotnet/maui/files/13509830/msbuild.binlog.zip)
Hi @rolfbjarne , I have attached the binlog kindly have a look on it.

**Comment by rolfbjarne** [comment]
OK, I believe I see the problem, it's that Platform isn't set anymore, so this logic doesn't work:

```xml
<BuildOutput Condition="'$(Platform)' == 'iPhone'">Debug-iphoneos</BuildOutput>
<BuildOutput Condition="'$(Platform)' == 'iPhoneSimulator'">Debug-iphonesimulator</BuildOutput>
```

This is untested, but something like this may work instead:

```xml
<BuildOutput Condition="!$(RuntimeIdentifier.Contains("simulator"))">Debug-iphoneos</BuildOutput>
<BuildOutput Condition="$(RuntimeIdentifier.Contains("simulator"))">Debug-iphonesimulator</BuildOutput>
```

So the AdditionalAppExtensions part would be:

```xml
<AdditionalAppExtensions Include="/Users/udhayakumar/Library/Developer/Xcode/DerivedData/mauiappwidgetpoc-cqhevuvngckarwdptrnbfgtqdmhu/Build/Products/">
	<Name>widgetExtension</Name>
	<BuildOutput Condition="!$(RuntimeIdentifier.Contains("simulator"))">Debug-iphoneos</BuildOutput>
	<BuildOutput Condition="$(RuntimeIdentifier.Contains("simulator"))">Debug-iphonesimulator</BuildOutput>
</AdditionalAppExtensions>
```

**Comment by entdark** [comment]
I confirm, that helped. The only thing that should be corrected is need to use single quotes in `'simulator'`.
Thanks guys.

**Comment by de-preut** [comment]
For us the proposed work-a-round was not the solution. AdditionalAppExtensions seems to not compatible with Xcode 15 based builds, as (after some investigation) we found out that we need to move the appex file to another subfolder ("Extensions" rather than "Plugins") in the generated .app / ipa structure.


@rolfbjarne do you have a work-a-round to override the "_AppPlugInsRelativePath" (or "_AppPlugInsPath") of the Xamarin.shared.targets?

**Comment by PureWeen** [comment]
Tracking here https://github.com/xamarin/xamarin-macios/issues/19861
