### ISSUE TITLE
Keyboard tabbing around a Modal Page cycles focus onto previous page.

### ISSUE THREAD

**Issue by TomRobson-me** [dotnet/maui#19105]
### Description

When keyboard tabbing around the foreground page of the modal stack, focus cycles to the previous page.

### Steps to Reproduce

1. On Windows
2. In the standard sample app
3. Create a ModalPage with one or more focusable controls.
4. Execute Navigation.PushModalAsync(new ModalPage())
5. Press the tab key a few times
6. Focus moves to button on the MainPage.
I have created a repository for a quick look.

### Link to public reproduction project repository

https://github.com/TomRobson-me/KeyboardTabBug.git

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

**Comment by mattleibow** [comment]
@PureWeen thoughts? @tj-devel709  thoughts-ghts?

**Comment by Saurbaum** [comment]
I see this same problem in iOS as well

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/22938
