### ISSUE TITLE
App crushes when native lib is called (C++ Shared Library project)

### ISSUE THREAD

**Issue by vraziel** [dotnet/maui#19119]
### Description

[libc] Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa in tid 20534 (nyname.mauiapp3), pid 20534 (nyname.mauiapp3) when user clicks on button in emulator.

### Steps to Reproduce

[MauiApp3.zip](https://github.com/dotnet/maui/files/13504105/MauiApp3.zip)

Demo project for reproducing. Switch to dynamic/static compilation for C++ project does not help. It just does not find so lib in such case but, so lib presents in apk (I've checked via jadx).

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.3

### Affected platforms

Android

**Comment by mattleibow** [comment]
@jonathanpeppers thoughts?

**Comment by jonathanpeppers** [comment]
I don't think enough of the error message is shown to know what is wrong. Can you share the full log output? `adb logcat -d > log.txt`

Without knowing details, it could be just your native library can't be loaded for some reason.

**Comment by vraziel** [comment]
You can close the issue. I've found a workaround.

**Comment by Strypper** [comment]
Hi what was the solution you apply?
