### ISSUE TITLE
Triggers are not working on Frame control in .net maui

### ISSUE THREAD

**Issue by nikamvd** [dotnet/maui#19127]
### Description

Triggers are not working on Frame control in .net maui

### Steps to Reproduce

1. Run the sample app from the link below
2. Click the button "Toggle Camera View". True / False represents the current toggle state.
3. Content on the "Frame" does not update but content on "Border" gets updated.

![FrameTriggerBug](https://github.com/dotnet/maui/assets/26141030/ca5ccc60-781f-4ec7-8d70-fc94cc1d2b0d)

### Link to public reproduction project repository

https://github.com/nikamvd/TriggersMauiApp

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.5.1

### Did you find any workaround?

Works if I replace Frame with Border

**Comment by suchithm** [comment]
Observed the same issue after updating to .net 8.0, which was working fine in lower version.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on iOS 17.0 and MacCatalyst, not repro on Android 14.0-API34 and Windows 11 with below Project:
[TriggerMauiApp.zip](https://github.com/dotnet/maui/files/13817750/TriggerMauiApp.zip)

**Comment by kubaflo** [comment]
@nikamvd fix: https://github.com/dotnet/maui/pull/20501
