### ISSUE TITLE
[iOS] MenuItem Command not executed with FlyoutHeader set

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#19149]
### Description

I have a .NET MAUI App with a Shell and several MenuItems. Without a FlyoutHeader, every Command bound to the MenuItems is executed. With a defined FlyoutHeader however, the first (i.e. topmost) MenuItem-Command does not get executed (same for FlyoutItems)

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Add a Shell with Flyout- and MenuItems
3. Add A FlyoutHeader (e.g. a Label)
4. The command bound to the first item (i.e. topmost item, be it a MenuItem or a FlyoutItem) will not get executed on iOS. On Android, it works fine.

### Link to public reproduction project repository

https://github.com/owl-guy/FlyoutWithHeaderExample

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on iOS 17.0 and MacCatalyst, not repro on Android 14.0-API34 and Windows 11 with below Project:
[FlyoutWithHeaderExample.zip](https://github.com/dotnet/maui/files/13825310/FlyoutWithHeaderExample.zip)

**Comment by owl-guy** [comment]
Will someone work on this?

**Comment by kubaflo** [comment]
It seems to be working fine in NET9

https://github.com/user-attachments/assets/7103d837-103a-40d7-b7f2-62b18b44a110
