### ISSUE TITLE
[regression/8.0.0-nightly] [MacCatalyst] Cannot click a button on MAUI nightly

### ISSUE THREAD

**Issue by MartyIX** [dotnet/maui#19154]
### Description

When I switch to .NET MAUI nightly packages for on macOS, I cannot click any button.

### Steps to Reproduce

I created a new .NET MAUI project using

1. `dotnet new maui -n MauiNightlySample`
2. [Set](https://github.com/MartyIX/MauiNightlySample/blob/9ef12cc409faf238ee32daad19ea4340e180fc22/MauiNightlySample.csproj#L43C16-L43C34) MAUI [nightly version](https://dev.azure.com/xamarin/public/_artifacts/feed/maui-nightly) `8.0.4-nightly.9689`
3. Added a [custom](https://github.com/MartyIX/MauiNightlySample/blob/main/NuGet.config) `NuGet.config` to avoid warnings regarding source of packages.
4. Run the app using `dotnet build -t:run -c Debug -f net8.0-maccatalyst`
5. -> Now the button cannot be clicked. It's not like it's disabled. It just doesn't react to any sort of mouse clicking.

Interestingly, changing version to `8.0.3` [here](https://github.com/MartyIX/MauiNightlySample/blob/9ef12cc409faf238ee32daad19ea4340e180fc22/MauiNightlySample.csproj#L42) makes the button clickable.

### Link to public reproduction project repository

https://github.com/MartyIX/MauiNightlySample

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

macOS

### Did you find any workaround?

No.

**Comment by drasticactions** [comment]
Is the build you're using after this comment landed? https://github.com/dotnet/maui/commit/6b3243348252c036011e308fa55515a4e5250e0f

Can you try a build from before this one to see if it works there?

**Comment by drasticactions** [comment]
> With `<MauiVersion>8.0.4-nightly.9657</MauiVersion>` it works! Not sure how old it is because I can't easily see timestamps for those nuget packages.

That's https://github.com/dotnet/maui/commit/01afe33d78 (https://dev.azure.com/xamarin/public/_artifacts/feed/maui-nightly/NuGet/Microsoft.Maui.Controls/overview/8.0.4-nightly.9657%20sha.01afe33d78-azdo.8722613). You can get the SHA from looking at the feed.

So that's from a week ago. The newest build contains this commit, and looking at what this does my guess is that this regressed it. 

CC @rachelkang @PureWeen
