### ISSUE TITLE
Windows | Entry ClearButton not taking color of text

### ISSUE THREAD

**Issue by bennimoser** [dotnet/maui#19152]
### Description

Bug was already fixed for Android and IOS, but it is still not working on Windows.
![TestMauiApp 01 12 2023 10_19_07](https://github.com/dotnet/maui/assets/62222316/2e552133-27e6-4b5e-8766-899dbb1db37c)
![TestMauiApp 01 12 2023 10_18_52](https://github.com/dotnet/maui/assets/62222316/560ceb6a-ee61-4ff1-b7df-ab8e09dd5a5c)

Former Bug: #13432 

### Steps to Reproduce

Make an Entry with Text Color Red on a white background. Clear Button is not visible because it is not using the Text Color.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No not yet. I cannot set it manually with an custom renderer

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on Windows 11, not repro on Android 14.0-API34, iOS 17.0 and MacCatalyst with below Project:
[19152.zip](https://github.com/dotnet/maui/files/13827359/19152.zip)

**Comment by assurasc** [comment]
Still an issue on Windows for MAUI 8.0.22
