### ISSUE TITLE
WebView on iOS causes UriFormatException: 'Invalid URI: The format of the URI could not be determined'

### ISSUE THREAD

**Issue by mariglenpupa** [dotnet/maui#19161]
Hello @javiercn, I did the following to check the behavior on Webview - 

- Created a simple HTML file with the following content

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
    <title>MyTestApp</title>
</head>

<body>
    <h1 style="text-align:center;color:orangered;margin-top:150px">Hello World!</h1>
    <script src="https://js.stripe.com/v3/"></script>
</body>
</html>
```

- Added the html file to the Resources/raw folder
- Used Webview in the MainPage.xaml

```
    <WebView  Source="index.html">
        </WebView>
```

The above code worked on Android and Windows but not on iOS. (Error - System.UriFormatException: 'Invalid URI: The format of the URI could not be determined.')

- I changed the Web view source from index.html to "https://appdir/index.html" . It worked on Windows and iOS displayed a blank-screen.

![iosblankscreen](https://user-images.githubusercontent.com/106889203/179781681-eb4e6a0d-7277-43b0-a37e-0c8a89a2cb41.jpg)

_Originally posted by @pramod-kun in https://github.com/dotnet/maui/issues/8741#issuecomment-1189167770_

**Comment by QianaJiao** [comment]
This issue can't be reproduced at iOS platform on the latest 17.12.0 Preview 1.0 (8.0.81).
![image](https://github.com/user-attachments/assets/2c408501-4597-4699-b000-465163b1c085)
