### ISSUE TITLE
Bundling WASDK in Packaged application throws `TypeInitializationException`

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#19167]
### Description

My goal is to bundle the WASDK runtime in my *packaged* application. Attempting to use 

`<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>` gives a `The platform AnyCPU is not supported for Self Contained mode`.

This led me to `<SelfContained>true</SelfContained>`, unfortunately, this throws `TypeInitializationException` on launch.

### Steps to Reproduce

1. Open your `csproj`
2. Add `<SelfContained>true</SelfContained>`
3. Build, observe exception.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

None at the moment.

**Comment by daltzctr** [comment]
Possibly related to https://github.com/microsoft/WindowsAppSDK/issues/2597

**Comment by mattleibow** [comment]
Are you using single file? There are 3 related terms:

 1. WindowsAppSDKSelfContained - bundle WASDK into the app
 2. SelfContained - bundle the .NET runtime into the app
 3. PublishSingleFile - merge everything into a single file

I do not think 3. is supported by WinUI 3.

If you are passing the properties 1. and 2. via the CLI, this is causing a bug to appear: https://github.com/microsoft/WindowsAppSDK/issues/4008

**Comment by mattleibow** [comment]
Try adding the contents to an existing Directory.Build.targets: 

https://github.com/dotnet/maui/blob/584d99f14d9b54c25819d1594ceecd370183b92c/src/Core/src/nuget/buildTransitive/WinUI.Unpackaged.targets

I will investigate why the publish works on CI and not locally. ANd also how this never came up before. I wonder if the only time we did the WASDKSelfContained was a store app.

I think the typical packaged app would involve people installing the msix dependencies in the output folder:

- Microsoft.WindowsAppRuntime.1.3.msix

But, this is no excuse, I will see what we can do ASAP.
