### ISSUE TITLE
[Bug] An iOS application crashes with custom native framework

### ISSUE THREAD

**Issue by AnatolyChugaev** [dotnet/maui#1916]
### Description
An iOS application crashes if you add a binding library based on a custom native iOS framework.

### Steps to Reproduce
1. Create an iOS framework.
2. Create a binding library based on the framework.
3. Create an iOS App with the binding library.
4. Run the App.

### Expected Behavior
The application runs successfully.

### Actual Behavior
The application crashes.
```Termination Reason:    DYLD, [0x1] Library missing```

### Basic Information
Xcode Version: 13.0 beta 3
.NET Core SDK Version: 6.0.100-preview.6.21355.2
Xamarin.iOS Version: 14.20.0.24

### Reproduction Link
https://github.com/AnatolyChugaev/iOS-framework-crash

### Workaround
Put the framework into the application manually.

**Comment by Redth** [comment]
Closing this issue, continue tracking in: https://github.com/xamarin/xamarin-macios/issues/12450
