### ISSUE TITLE
AndroidManifest no longer gets version number from project file

### ISSUE THREAD

**Issue by imsam67** [dotnet/maui#19164]
### Description

I've noticed that with the upgrade to the lastest verrsion of .NET 8, `AndroidManifest.xml` no longer gets the version number specified in `csproj` file.

I also tested this in a new app I created and if I open `AndroidManifest.xml`, I don't see the version number set in the project file i.e. `<ApplicationVersion>1234</ApplicationVersion>`.

Unfortunately, this can be a nuisance because without thinking too much about checking the `AndroidManifest.xml`, I published my app to create a new package and only after I uploaded the `.aab` file to Google Play, I got a message stating the version number had already been used.

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Open the `csproj` file and change the version number in `<ApplicationVersion>1</ApplicationVersion>` to another number
3. Close `csproj` file
4. Open `AndroidManifest.xml`  and you'll see that it didn't pick up the version number

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

### Did you find any workaround?

Manually open `AndroidManifest.xml` and update it myself

**Comment by jfversluis** [comment]
The version number has never updated directly. This only happens at compile time and the final version is only included in your built application binary, not in the `AndroidManifest.xml` file that is in your source.

From what I can tell this functionality works as it should, you might need to do a proper clean/rebuild for it to clean the cache out. Would you be able to confirm that if you do a rebuild the version number is updated in the apk/aab file?

You should be able to open those files by renaming them to a zip and find the `AndroidManifest.xml` file and inspect the contents.
