### ISSUE TITLE
SQLite db crash the app in .net8

### ISSUE THREAD

**Issue by prok155** [dotnet/maui#19173]
### Description

I try to migrate my app to .net8 and SQLite db crash the app with following exception:

`SQLite.SQLiteException: 'Could not open database file: /data/user/0/com.companyname.mymauiapp/files/Documents/userdb.db3 (CannotOpen)'`

I investigated it and I found that it's probably MAUI bug, not SQLite bug. There is a problem with my database path, I create my db path like this:

`string _dbPath = Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal), "userdb.db3");`

In .net7, the code above returned this path:
`/data/user/0/com.companyname.mymauiapp/files/userdb.db3 `
but in .net8 it returns this path:
`/data/user/0/com.companyname.mymauiapp/files/Documents/userdb.db3 `

The problem is that directory `/data/user/0/com.companyname.mymauiapp/files/Documents` doesn't exists, thats why the app crashes and throws `SQLite.SQLiteException`.  It will also delete all existing data, because db file has new path (which is probably related to #18769).

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.86

### Affected platforms

Android, I was *not* able test on other platforms

### Did you find any workaround?

When I create db path like this:
`string _dbPath = Path.Combine("/data/user/0/com.companyname.mymauiapp/files/", "userdb.db3");`

the app doesn't crash, because it's the same path like in .net7 and that path exists.

**Comment by acaliaro** [comment]
I use string mainDir = FileSystem.Current.AppDataDirectory; and I have no problem

**Comment by albyrock87** [comment]
@prok155 have you checked what `SpecialFolder.ApplicationData` returns? In my experience it matches Xamarin `Personal` one.

Besides that, if you haven't noticed, also be aware that `SecureStorage` is based on a new key so everything stored there using Xamarin Essential is gone when upgrading to MAUI (well, we can retrieve values using platform specific code).

**Comment by moljac** [comment]
> `string _dbPath = Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal), "userdb.db3");`

`System.Environment.SpecialFolder.Personal` would mean it is multi-user system. 

Can you try and turn it on, please? Just to see...

Settings /> System /> Multiple users /> Turn on switch

**Comment by prok155** [comment]
> @prok155 have you checked what `SpecialFolder.ApplicationData` returns? In my experience it matches Xamarin `Personal` one. Also (on new installation) be sure to `CreateDirectory` if it doesn't exist before creating SQLiteConnection

`SpecialFolder.ApplicationData` returns `/data/user/0/com.companyname.mymauiapp/files/.config`

**Comment by suchithm** [comment]
As per the document : https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix#android

Changing to` (Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)).` worked.
