### ISSUE TITLE
BackgroundImageSource  does not work in iOS - .net 8 

### ISSUE THREAD

**Issue by gabsamples6** [dotnet/maui#19176]
### Description

our designers spent lot of time to create some background images for our app, only to find out that does not work in iOS.

This is one of those things that we expect to just work!

![image](https://github.com/dotnet/maui/assets/109357537/d16d3a4d-22bb-4a26-87ca-5e9efed74e7f)

### Steps to Reproduce

1. Create a maui app from template
2. on a page set   BackgroundImageSource="dotnet_bot.png"
3. Launch the app in iOS - its blank   (android works)

### Link to public reproduction project repository

no necessary - launch any app and set     BackgroundImageSource="dotnet_bot.png"

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by eli191** [comment]
Same issue here

**Comment by gabsamples6** [comment]
@jsuarezruiz  if this ticket its not part of any milestone , means its never going to be fixed soon correct? 

As you know some issues might be trivial but lots of effort went into some designs... sure we can find a workaround but this is stuff that should just work.

**Comment by mattleibow** [comment]
We think this was fixed in the upcoming release, and you can verify this by using the nightly builds: https://github.com/dotnet/maui/wiki/Nightly-Builds

Please try it out and let us know.

**Comment by gabsamples6** [comment]
@mattleibow yes that is fixed in the night build. thanks for pointing it out.
