### ISSUE TITLE
[build] Remove GitInfo

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#19185]
### Description

Sometimes we see some failures on ci related with the usage of GitInfo.
We just use it with a small subset, can we write code to get the exact same info? 

We could also look at switching to
https://github.com/dotnet/Nerdbank.GitVersioning

### Link to public reproduction project repository

dotnet/maui

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Relevant log output

```shell
C:\Users\cloudtest\.nuget\packages\gitinfo\2.2.0\build\GitInfo.targets(342,3): error MSB3491: Could not write lines to file "obj\Release\net8.0-android\GitIsDirty.cache". The process cannot access the file 'D:\a\_work\1\s\src\Controls\src\Core\obj\Release\net8.0-android\GitIsDirty.cache' because it is being used by another process. [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-android]
```

**Comment by jfversluis** [comment]
First tried to update the dependency with #20136 and see if that helps.

If not, what is the alternative course of action? Identify all the MSBuild properties and provide those through Cake?
