### ISSUE TITLE
[regression/8.0.3] first item in CollectionView larger than rest

### ISSUE THREAD

**Issue by taylormoyle** [dotnet/maui#19195]
### **Description**

After I upgraded to .NET 8, I noticed that the first item in my CollectionView is being drawn larger than the rest, thus trimming the size and content of the other items. This happens with no code changed, other than changing TargetFramework from
`net7.0-windows10.0.19041` to `net8.0-windows10.0.19041` in the csproj file.

![Net8Bug](https://github.com/dotnet/maui/assets/25063141/cf9cef01-479b-42e8-bc1e-c05c0f49ea1f)

### Steps to Reproduce

1. Build a CollectionView with the necessary bindings (github is hiding the base collectionView tag fsr)

<CollectionView
    x:Name="TestCollection"
    ItemsSource="{Binding Items}"
    Margin="20"
    ItemsLayout="VerticalGrid, 3"
    VerticalScrollBarVisibility="Always"
    VerticalOptions="StartAndExpand"
    SelectionMode="Single"
    SelectedItem="{Binding SelectedItem}"
    SelectionChanged="OnItemSelectionChanged">

    <CollectionView.ItemTemplate>
        <DataTemplate>
            <Grid
                RowDefinitions="50, 90, *, 35, 35, 35"
                ColumnDefinitions="2*, *, *, 2*"
                Padding="{OnIdiom Tablet=0, Desktop=30}"
                BackgroundColor="Black"
                Margin="{OnIdiom Tablet=10, Desktop=20}"
                MinimumWidthRequest="272"
                MinimumHeightRequest="272">

                <Image Grid.Row="0"
                       Grid.Column="1"
                       HorizontalOptions="End"
                       Margin="0,0,10,0"
                       Source="{Binding ConnectionImage}"
                       HeightRequest="{OnIdiom Tablet=24, Desktop=30}" />
                <Image Grid.Row="0"
                       Grid.Column="2"
                       HorizontalOptions="Start"
                       Margin="10,0,0,0"
                       Source="{Binding DataAvailableImage}"
                       HeightRequest="{OnIdiom Tablet=24, Desktop=30}" />
                <Image Grid.Row="1"
                       Grid.ColumnSpan="4"
                       Source="{Binding StatusImage}"
                       HeightRequest="40"
                       VerticalOptions="EndAndExpand" />
                <Label Grid.Row="2"
                       Grid.Column="0"
                       Grid.ColumnSpan="4"
                       Margin="0, 10"
                       Text="Title"
                       LineBreakMode="NoWrap"
                       HorizontalOptions="CenterAndExpand"
                       FontSize="Medium" />

                <HorizontalStackLayout Grid.Row="3" Grid.ColumnSpan="4" HorizontalOptions="Center">
                    <HorizontalStackLayout>
                        <Image HeightRequest="{OnIdiom Tablet=18, Desktop=26}"
                               Source="error.png" />
                        <Label TextColor="Red"
                               FontFamily="OverpassMono"
                               Margin="6,0,12,0"
                               FontSize="Medium"
                               VerticalOptions="CenterAndExpand"
                               Text="{Binding Item.Errors}" />
                    </HorizontalStackLayout>

                    <HorizontalStackLayout>
                        <Image HeightRequest="{OnIdiom Tablet=18, Desktop=26}"
                               Source="warning.png" />
                        <Label TextColor="Yellow"
                               FontFamily="OverpassMono"
                               Margin="6,0,12,0"
                               FontSize="Medium"
                               VerticalOptions="CenterAndExpand"
                               Text="{Binding Item.Warnings}" />
                    </HorizontalStackLayout>

                    <HorizontalStackLayout>
                        <Image HeightRequest="{OnIdiom Tablet=18, Desktop=26}"
                               Source="info.png" />
                        <Label TextColor="Green"
                               FontFamily="OverpassMono"
                               Margin="6,0,12,0"
                               FontSize="Medium"
                               VerticalOptions="CenterAndExpand"
                               Text="{Binding Item.Information}" />
                    </HorizontalStackLayout>

                    <HorizontalStackLayout>
                        <Image HeightRequest="{OnIdiom Tablet=18, Desktop=26}"
                               Source="notification.png" />
                        <Label TextColor="Gray"
                               FontFamily="OverpassMono"
                               Margin="6,0,12,0"
                               FontSize="Medium"
                               VerticalOptions="CenterAndExpand"
                               Text="{Binding Item.Notifications}" />
                    </HorizontalStackLayout>
                </HorizontalStackLayout>

                <Label Grid.Row="4"
                       Grid.Column="0"
                       Grid.ColumnSpan="4"
                       Text="{Binding Item.LastContact, StringFormat='{0:yyyyMMMdd}'}"
                       FontFamily="OverpassMono"
                       TextColor="Gray"
                       LineBreakMode="NoWrap"
                       HorizontalOptions="Center"
                       VerticalOptions="End" />
            </Grid>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>

2. Change TargetFramework from 
`<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041</TargetFrameworks>`
to 
`<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041</TargetFrameworks>` 

### **Expected Result**
No difference to .Net7, each item is sized equally.

### **Actual Result**
The first item is larger than the rest, and the Title is cut off.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

### Did you find any workaround?

Forced to revert back to .net7.

**Comment by drasticactions** [comment]
Could you create a reproduction project showing this? Without a project representing how you've set up your views, it will be extremely hard to debug, and having a simple case showing it will make it both easier to debug and figure out, and turn into test cases later.
