### ISSUE TITLE
[regression/8.0.3] Splash screen no longer working in .Net 8 Maui

### ISSUE THREAD

**Issue by polygonsheep** [dotnet/maui#19200]
### Description

Had an app with .net 7 working fine. Upgraded to .net 8 and the splash screen no longer shows. Just a blank white screen. 
Tried removing the splash screen and re-adding with no luck.

### Steps to Reproduce

1) Spend 7 months working on a .net 7 maui app
2) Getting it feature complete
3) Upgrade to .net 8. 
4) splash screen no longer shows up (blank white screen only)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

iOS for sure. Haven't test on Android because if it doesn't work on iOS there no point.

### Did you find any workaround?

No.

**Comment by SmartmanApps** [comment]
Works for me on Android, so appears to be an iOS issue.

**Comment by mla03** [comment]
We have it working on both Android and iOS running 8.0.3, but on Android the Image is scaled incorrectly.

**Comment by PureWeen** [comment]
How are you running the app? 

Does it work with a file new maui app?

**Comment by Hardikzinzala** [comment]
Any one have solution for this because i am also facing the same issue.

**Comment by EminNiftili** [comment]
Anyone have solution? Same problem for me. But Android work great.
