### ISSUE TITLE
Border Stoke data binding does not work

### ISSUE THREAD

**Issue by kluzen** [dotnet/maui#19201]
### Description

Binding the Stroke property of a Border in order to dynamically set its color does not work. I would expect the property to function the same way BorderColor does on a Frame.

### Steps to Reproduce

Create a new .net maui app.
Replace main page with:
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiTestApp.MainPage">

  <ScrollView>
    <VerticalStackLayout
            Padding="30,0"
            Spacing="25">

      <Entry Text="#FF0000" x:Name="ColorEntry" />

      <Border BindingContext="{x:Reference ColorEntry}"
              Stroke="{Binding Path=Text}">
        <Label Text="Border Test" />
      </Border>

      <Frame BindingContext="{x:Reference ColorEntry}"
             BorderColor="{Binding Path=Text}">
        <Label Text="Frame Test" />
      </Frame>
    </VerticalStackLayout>
  </ScrollView>

</ContentPage>
```
Change entry text to different hex colors. The Frame control updates but the Border control does not.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by drasticactions** [comment]
This could be similar, if not the same as, https://github.com/dotnet/maui/issues/19075

The underlying binding is sending values to Border, but it's not being redrawn if changed. So it may not be the binding not working, but the control not properly updating with the change.
