### ISSUE TITLE
[Android] ScrollOrientation.Neither not disable scroll

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#19213]
### Description

` ScrollOrientation.Neither` not disable scroll on Android.

### Steps to Reproduce

1. Launch the .NET MAUI sln.
2. Launch Issue2680Test_ScrollDisabled (src\Compatibility\ControlGallery\src\Issues.Shared\Issue2680ScrollView.cs).
3. Tap the button to disable the scroll.
4. Try to scroll. Must not be possible.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.3

### Affected platforms

Android

**Comment by riccardominato** [comment]
https://github.com/dotnet/maui/issues/18418

**Comment by PureWeen** [comment]
Duplicate of #18418
