### ISSUE TITLE
How do i fix this? Everytime i try to run mij code in vs it gives me a error

### ISSUE THREAD

**Issue by RamiMaach** [dotnet/maui#19217]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![Schermafbeelding 2023-12-05 103757](https://github.com/dotnet/maui/assets/93382247/c5d7e62e-fe2c-4dfa-9bc0-51262b3ba7eb)

**Comment by drasticactions** [comment]
This would need to be addressed by the Visual Studio team, it's most likely related to underlying tooling within Visual Studio and not something specific to this project.
