### ISSUE TITLE
[regression/8.0.3] [iOS] PushModalAsync navigation doesn't navigate

### ISSUE THREAD

**Issue by Uridel** [dotnet/maui#19225]
### Description

Description
We are currently testing out our migration from Maui .NET 7.0 to .NET 8.0. On iOS we are currently experiencing a problem with regards to modal navigation. In our codebase we cannot navigate using the `PushModalAsync` method.

Whenever we try to push a page to stack nothing happens, at least visually. So what are we attempting? 

We determine the `targetView`, which is a `TemplatedView` wrapped in a Page. 
After which we attempt to push the Modal onto the last `NavigationPage`.  This results in the Modal being “pushed” but no visual change being made. We can still navigate back but the modal is nowhere to be found.

What did we observe
-	We have tried Giving the Modal as a `NavigationPage` and a `Page` , with no success
-	The events `ModalPushing` & `ModalPushed` both are executed
-	Using any other form of navigation actually makes the push happen, with the same Page being pushed, only `PushModalAsync` has no impact
-	Observing the `Navigation.ModalStack` contains the Modal we wish to see pushed, yet we don’t see the page.

### Steps to Reproduce

N/A

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Did you find any workaround?

N/A

**Comment by drasticactions** [comment]
I tried to create an example of what you're doing (https://github.com/drasticactions/MauiRepros/blob/main/MauiModalTest/MainPage.xaml.cs) but I'm not sure what you're trying to do based on your description. Can you please create a repro project of what you're trying to do?

**Comment by LuckyGolfer** [comment]
Same issue here on iOS.  We launch a LoginPage over the HomePage via PushModalAsync.  Stopped working on iOS on .Net 8...worked on .Net 7 with same Maui version.  Our navigation is via the App.xaml.cs where the MainPage (HomePage) is created instead of the codebehind of a page.  

Have also tried to invoke the PushModalAsync on main ui thread to no avail.  HomePage remains visible and active...additional attempts to open another LoginPage also does not change the view.

**Comment by Uridel** [comment]
As @LuckyGolfer pointed out we also didn't override the  ` base.OnActivated(uiApplication)`  , overriding it allowed us to navigate. Is there any explanation as to why this is required in order for modal navigation to work, especially since it worked fine before?
