### ISSUE TITLE
Maui - publish as exe dulicated the files

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#19220]
### Description

Hi,

When I publish my app it duplicates the files and create two exe

one in publish folder and one outside the publish folder.

How do i fixed it ?

I used :

dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d" -p:RuntimeIdentifierOverride=win10-x64

### Steps to Reproduce

1,Create Maui app.
2.Publish it with command line using:
dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true  -p:RuntimeIdentifierOverride=win10-x64
3.**Duplicates files** are generated!!

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

...

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by drasticactions** [comment]
I don't believe this is a bug. I think this is the behavior of publishing self-contained WinUI apps and what you would get by doing the same on a non-MAUI based WinUI App. It creates a release build, then publishes that build into the publish folder. 

@mattleibow Does that sound correct?

**Comment by jfversluis** [comment]
Yes, that is just how Visual Studio or rather probably the publish tool works. It will generate the build output and put the published bits in a second location. The two could be different from each other, but probably in most cases these will probably be the same.

A nice optimalization I guess, but something that transcends .NET MAUI. Probably something for MSBuild the publish tooling or Visual Studio.

**Comment by danies8** [comment]
I found case that the publish folder not work as expected.
If you have class library A that has reference to complied dll D.
And maui App that have project reference to that class library A.
funcuality with this dll D not work as expected and the app is **crash**.
But if i used the **build output** without the publish folder is work as expected.
WHY?

**Comment by danies8** [comment]
Please see https://learn.microsoft.com/en-us/answers/questions/1457426/maui-publish-as-exe-dulicated-the-files
It verified what i said in my comment below.
You have bug in this senario.
[Yonglun Liu (Shanghai Wicresoft Co,.Ltd.)](https://learn.microsoft.com/en-us/users/na/?userid=994fd0f3-fc7a-4621-a8a9-6e3cce0b5bdc) • 
Follow
24,891 Reputation points• Microsoft Vendor
Dec 6, 2023, 9:15 AM
Hello,

After testing, the two exe files are exactly equivalent, but the exe file inside the publish folder is missing static resource references at runtime.

Therefore, you should use the exe file from an external folder.

Best Regards,

Alec Liu.

**Comment by drasticactions** [comment]
<img width="908" alt="image" src="https://github.com/dotnet/maui/assets/898335/0680a667-22bc-4929-99f4-88361bcb84ea">

The build is compiled into `Release`, then copied into Publish. You can replicate this behavior by doing this on a WinUI (Or WPF, WinForms, .NET app, etc) app without MAUI. Moreover, I ran the published build off of the default MAUI template and it worked correctly. That makes sense, as it's the same build and files included in both directories.

If you can prove that you have an app that doesn't work or is different from Release to Publish and that it's affecting you negatively, you're more than happy to file a new bug with a reproduction case showing it. But your original issue wasn't that the build was different, it was that the files were "duplicated" and as @jfversluis said, that's an MSBuild thing and not a MAUI thing.

**Comment by danies8** [comment]
Please see this ticket:
https://learn.microsoft.com/en-us/answers/questions/1457426/maui-publish-as-exe-dulicated-the-files
