### ISSUE TITLE
[Bug] BoxView not reporting correct size 

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1922]
### Description

```
using System;
using Microsoft.Maui;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;

namespace LayoutLab
{	public class SpacingStackPage : ContentPage
	{
		public SpacingStackPage()
		{
            BackgroundColor = Colors.White;
            this.Content = new StackLayout
            {
                Margin = new Thickness(100),
                Spacing = 0,
                Children =
                {
                    new Label { Text = "Primary colors" },
                    new BoxView { Color = Colors.Red },
                    new BoxView { Color = Colors.Yellow },
                    new BoxView { Color = Colors.Blue },
                    new Label { Text = "Secondary colors" },
                    new BoxView { Color = Colors.Green },
                    new BoxView { Color = Colors.Orange },
                    new BoxView { Color = Colors.Purple }
                }
            };
		}
	}
}
```

### Expected Behavior

![Screen Shot 2021-04-15 at 1 33](https://user-images.githubusercontent.com/41873/128032418-12244140-15e7-470a-9e21-1a3bc8cceabc.png)

### Actual Behavior

Minus the title bar issue...

![Screen Shot 2021-08-03 at 9 19 46 AM](https://user-images.githubusercontent.com/41873/128032066-b14b198a-c666-43ea-8b8c-ca4c5bce3bf1.png)

If I give a BoxView an explicit size, it'll appear.

![Screen Shot 2021-08-03 at 9 23 35 AM](https://user-images.githubusercontent.com/41873/128032519-6dd46938-74aa-4ca2-9252-00e5759e97ad.png)

### Basic Information

- Version with issue: pre7

### Reproduction Link

https://github.com/davidortinau/ControlGallery/blob/main/src/ControlGallery/Pages/Stack/SpacingStackPage.cs

**Comment by hartez** [comment]
So what you're saying is that BoxView is broken.
