### ISSUE TITLE
Custom Build Configurations require explicit iOS RuntimeIdentifier values in the csproj file. Can I set these using Conditions?

### ISSUE THREAD

**Issue by tbaggett** [dotnet/maui#19235]
### Description

```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
wasi-experimental          8.0.0/8.0.100          SDK 8.0.100        
ios                        17.0.8478/8.0.100      SDK 8.0.100        
maui                       8.0.3/8.0.100          SDK 8.0.100

```

We're porting our existing Xamarin Forms app to MAUI/.NET 8. We use custom debug and release configurations in our XF solution to select the data environment to build/test against, i.e., "Debug - dev", "Debug - rd" etc. and would like to do the same in the MAUI solution.

I ran into issues where lots of build settings that are automatically assumed in the default "Debug" and "Release" configurations must be explicitly defined when using custom build configurations. This issue is described in https://github.com/dotnet/maui/issues/9627. 

I used the information provided in that ticket to solve most of the problems, except for one. iOS builds require explicitly-defined RuntimeIdentifier values of "iossimulator-x64", "iossimulator-arm64" or "ios-arm64" depending on the Mac build agent's processor architecture and if an iOS Simulator or physical device is being targeted for the build.

Here's an example of the build error when targeting a Simulator image.

/usr/local/share/dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(5,5): Error NETSDK1047: Assets file '.../App/obj/project.assets.json' doesn't have a target for 'net8.0-ios/iossimulator-x64'. Ensure that restore has run and that you have included 'net8.0-ios' in the TargetFrameworks for your project. You may also need to include 'iossimulator-x64' in your project's RuntimeIdentifiers. (NETSDK1047) (....App)

This issue was also previously reported in https://github.com/dotnet/maui/issues/8272. It was closed after it was thought to have been resolved. It is still a problem when using custom build configurations. 

There is a workaround provided in that ticket, which is to manually add the RuntimeIdentifier and edit the csproj whenever you want to switch your target between iOS Simulator and device. That is not an ideal solution.

I would like to add all of the needed RuntimeIdentifier declarations and define conditions for when each one should be used. I have not been able to successfully find the properties needed to do this.

Are there build properties available that can be used to determine the build agent's processor architecture (ARM-64 or X-64) and if the selected iOS build target is a Simulator image or physical device?

### Steps to Reproduce

Create custom build configurations with explicitly-specified build properties. This causes the RuntimeIdentifier to not be automatically set by MAUI/VS.

Here's a version of the csproj file without company-specific info that I am seeing this issue with:

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net8.0-ios</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>App</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	    <WarningLevel>7</WarningLevel>
		<SkipValidateMauiImplicitPackageReferences>true</SkipValidateMauiImplicitPackageReferences>
		
		<WarningsAsErrors>CS8602,CS8603,CS8604,CS8618,CS8622,CS8625,CS8629,CS8767</WarningsAsErrors>

		
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">13.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
		<Configurations>Debug - dev;Debug - rd;Debug - prod;Release - dev;Release - rd;Release - prod</Configurations>
		<TargetPlatformIos>True</TargetPlatformIos>
		<MinTargetFrameworkIos>13.0</MinTargetFrameworkIos>
		<TargetPlatformAndroid>True</TargetPlatformAndroid>
		<ProvisioningType>automatic</ProvisioningType>
	</PropertyGroup>

	

	<PropertyGroup Condition="$(Configuration.Contains('dev')) Or '$(Environment)' == 'DEV'">
	  
	  <ApplicationTitle>App DEV</ApplicationTitle>
	  
	  <ApplicationId>com.dev.app</ApplicationId>
	</PropertyGroup>

	<PropertyGroup Condition="$(Configuration.Contains('rd')) Or '$(Environment)' == 'RD'">
	  
	  <ApplicationTitle>App RD</ApplicationTitle>
	  
	  <ApplicationId>com.rd.app</ApplicationId>
	</PropertyGroup>

	<PropertyGroup Condition="$(Configuration.Contains('prod')) Or '$(Environment)' == 'PROD'">
	  
	  <ApplicationTitle>App PROD</ApplicationTitle>
	  
	  <ApplicationId>com.prod.app</ApplicationId>
	</PropertyGroup>

	

	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) And ($(Configuration.Contains('dev')) Or '$(Environment)' == 'DEV')">
	  <CodesignProvision>App DEV Profile</CodesignProvision>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) And ($(Configuration.Contains('rd')) Or '$(Environment)' == 'RD')">
	  <CodesignProvision>App RD Profile</CodesignProvision>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) And ($(Configuration.Contains('prod')) Or '$(Environment)' == 'PROD')">
	  <CodesignProvision>App PROD Profile</CodesignProvision>
	</PropertyGroup>

	
	
	<PropertyGroup Condition="'$(Configuration)'=='Debug - dev'">
	  <DefineConstants>TRACE;ENV_DEV;DEBUG;DEBUG___DEV;NET;NET8_0;NETCOREAPP</DefineConstants>
	  <_BundlerDebug>true</_BundlerDebug>
	  <Optimize>false</Optimize>
	</PropertyGroup>	

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug - dev|net8.0-android|AnyCPU'">
	  <UseInterpreter>true</UseInterpreter>
	  <DebugSymbols>True</DebugSymbols>
	  <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
	  <EnableLLVM>True</EnableLLVM>
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug - dev|net8.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	  <MtouchDebug>true</MtouchDebug>
	  <DebugSymbols>True</DebugSymbols>
	  <EnableLLVM>True</EnableLLVM>
	  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
	  <MtouchLink>None</MtouchLink>
	  <MtouchFloat32>True</MtouchFloat32>
	</PropertyGroup>

	
	
	<PropertyGroup Condition="'$(Configuration)'=='Debug - rd'">
	  <DefineConstants>TRACE;ENV_RD;DEBUG;DEBUG___RD;NET;NET8_0;NETCOREAPP</DefineConstants>
	  <_BundlerDebug>true</_BundlerDebug>
	  <Optimize>false</Optimize>
	</PropertyGroup>	

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug - rd|net8.0-android|AnyCPU'">
	  <UseInterpreter>true</UseInterpreter>
	  <DebugSymbols>True</DebugSymbols>
	  <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
	  <EnableLLVM>True</EnableLLVM>
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug - rd|net8.0-ios|AnyCPU'">
      <CreatePackage>false</CreatePackage>
      <MtouchDebug>true</MtouchDebug>
      <DebugSymbols>True</DebugSymbols>
      <EnableLLVM>True</EnableLLVM>
      <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
      <MtouchLink>None</MtouchLink>
      <MtouchFloat32>True</MtouchFloat32>
    </PropertyGroup>

	
	
	<PropertyGroup Condition="'$(Configuration)'=='Debug - prod'">
	  <DefineConstants>TRACE;ENV_PROD;DEBUG;DEBUG___PROD;NET;NET8_0;NETCOREAPP</DefineConstants>
	  <_BundlerDebug>true</_BundlerDebug>
	  <Optimize>false</Optimize>
	</PropertyGroup>	

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug - prod|net8.0-android|AnyCPU'">
	  <DefineConstants>$(DefineConstants);ENV_PROD</DefineConstants>
	  <DebugSymbols>True</DebugSymbols>
	  <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
	  <EnableLLVM>True</EnableLLVM>
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug - prod|net8.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	  <MtouchDebug>true</MtouchDebug>
	  <DebugSymbols>True</DebugSymbols>
	  <EnableLLVM>True</EnableLLVM>
	  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
	  <MtouchLink>None</MtouchLink>
	  <MtouchFloat32>True</MtouchFloat32>
	</PropertyGroup>

	
	
	<PropertyGroup Condition="'$(Configuration)'=='Release - dev'">
	  <DefineConstants>TRACE;ENV_DEV;RELEASE;RELEASE___DEV;NET;NET8_0;NETCOREAPP</DefineConstants>
	  <Optimize>true</Optimize>
	</PropertyGroup>	

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release - dev|net8.0-android|AnyCPU'">
      <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
      <AndroidManagedSymbols>true</AndroidManagedSymbols>
      <AndroidPackageFormats>aab;apk</AndroidPackageFormats>
      <PublishTrimmed>true</PublishTrimmed>
      <RunAOTCompilation>true</RunAOTCompilation>
      <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
      <DebugSymbols>False</DebugSymbols>
      <EnableLLVM>True</EnableLLVM>
      <AndroidKeyStore>False</AndroidKeyStore>
      <AndroidLinkTool>r8</AndroidLinkTool>
      <AndroidEnableMultiDex>True</AndroidEnableMultiDex>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release - dev|net8.0-ios|AnyCPU'">
	  <MtouchUseLlvm>true</MtouchUseLlvm>
	  <MtouchDebug>false</MtouchDebug>
	  <EnableAssemblyILStripping>true</EnableAssemblyILStripping>
      <DebugSymbols>False</DebugSymbols>
	  <EnableLLVM>True</EnableLLVM>
	  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
	  <MtouchLink>SdkOnly</MtouchLink>
	  <OptimizePNGs>True</OptimizePNGs>
	  <MtouchFloat32>True</MtouchFloat32>
	</PropertyGroup>

	
	
	<PropertyGroup Condition="'$(Configuration)'=='Release - rd'">
	  <DefineConstants>TRACE;ENV_RD;RELEASE;RELEASE___RD;NET;NET8_0;NETCOREAPP</DefineConstants>
	  <Optimize>True</Optimize>
	</PropertyGroup>	

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release - rd|net8.0-android|AnyCPU'">
      <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
      <AndroidManagedSymbols>true</AndroidManagedSymbols>
      <AndroidPackageFormats>aab;apk</AndroidPackageFormats>
      <PublishTrimmed>true</PublishTrimmed>
      <RunAOTCompilation>true</RunAOTCompilation>
      <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
      <DebugSymbols>False</DebugSymbols>
      <EnableLLVM>True</EnableLLVM>
      <AndroidKeyStore>False</AndroidKeyStore>
      <AndroidLinkTool>r8</AndroidLinkTool>
      <AndroidEnableMultiDex>True</AndroidEnableMultiDex>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release - rd|net8.0-ios|AnyCPU'">
	  <MtouchUseLlvm>true</MtouchUseLlvm>
	  <MtouchDebug>False</MtouchDebug>
      <DebugSymbols>False</DebugSymbols>
	  <EnableLLVM>True</EnableLLVM>
	  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
	  <MtouchLink>SdkOnly</MtouchLink>
	  <OptimizePNGs>True</OptimizePNGs>
	  <MtouchFloat32>True</MtouchFloat32>
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>

	

	<PropertyGroup Condition="'$(Configuration)'=='Release - prod'">
	  <DefineConstants>TRACE;ENV_PROD;RELEASE;RELEASE___PROD;NET;NET8_0;NETCOREAPP</DefineConstants>
	  <Optimize>True</Optimize>
	</PropertyGroup>	

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release - prod|net8.0-android|AnyCPU'">
      <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
      <AndroidManagedSymbols>true</AndroidManagedSymbols>
      <AndroidPackageFormats>aab;apk</AndroidPackageFormats>
      <PublishTrimmed>true</PublishTrimmed>
      <RunAOTCompilation>true</RunAOTCompilation>
      <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
      <DebugSymbols>False</DebugSymbols>
      <EnableLLVM>True</EnableLLVM>
      <AndroidKeyStore>False</AndroidKeyStore>
      <MtouchLink>None</MtouchLink>
      <AndroidLinkTool>r8</AndroidLinkTool>
      <AndroidEnableMultiDex>True</AndroidEnableMultiDex>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release - prod|net8.0-ios|AnyCPU'">
	  <MtouchUseLlvm>true</MtouchUseLlvm>
	  <MtouchDebug>False</MtouchDebug>
      <DebugSymbols>False</DebugSymbols>
	  <EnableLLVM>True</EnableLLVM>
	  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
	  <MtouchLink>SdkOnly</MtouchLink>
	  <OptimizePNGs>True</OptimizePNGs>
	  <MtouchFloat32>True</MtouchFloat32>
	</PropertyGroup>

	<ItemGroup>
		
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Services\" />
	  <None Remove="UI\" />
	  <None Remove="UI\Application\" />
	  <None Remove="UI\Helpers\" />
	  <None Remove="UI\Localization\" />
	  <None Remove="UI\MarkupExtensions\" />
	  <None Remove="UI\Models\" />
	  <None Remove="UI\Templates\" />
	  <None Remove="UI\ViewModels\" />
	  <None Remove="UI\Views\" />
	  <None Remove="UI\Views\Startup\" />
	  <None Remove="UI\ViewModels\Startup\" />
	  <None Remove="UI\Views\Login\" />
	  <None Remove="UI\ViewModels\Login\" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Services\" />
	  <Folder Include="UI\Application\" />
	  <Folder Include="UI\Helpers\" />
	  <Folder Include="UI\Localization\" />
	  <Folder Include="UI\MarkupExtensions\" />
	  <Folder Include="UI\Models\" />
	  <Folder Include="UI\Templates\" />
	  <Folder Include="UI\ViewModels\" />
	  <Folder Include="UI\Views\" />
	  <Folder Include="UI\Views\Startup\" />
	  <Folder Include="UI\ViewModels\Startup\" />
	  <Folder Include="UI\Views\Login\" />
	  <Folder Include="UI\ViewModels\Login\" />
	</ItemGroup>
</Project>

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

The only workaround I know of is to edit the csproj file and manually change the specified RuntimeIdentifier value whenever you want to change the build target between the iOS Simulator and a physical device.

### Relevant log output

```shell
/usr/local/share/dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(5,5): Error NETSDK1047: Assets file '.../App/obj/project.assets.json' doesn't have a target for 'net8.0-ios/iossimulator-x64'. Ensure that restore has run and that you have included 'net8.0-ios' in the TargetFrameworks for your project. You may also need to include 'iossimulator-x64' in your project's RuntimeIdentifiers. (NETSDK1047) (....App)
```

**Comment by kullen** [comment]
+1

**Comment by PureWeen** [comment]
@rolfbjarne thoughts?

**Comment by rolfbjarne** [comment]
I believe this is a known issue in the IDE, maybe @emaf / @mauroa can confirm?

**Comment by emaf** [comment]
@tbaggett Assuming you are facing this from Visual Studio for Mac, this is a known issue (https://developercommunity.visualstudio.com/t/Assets-file-issue-on-build/10312467), and as a workaround running a NuGet restore after facing this problem should make things work again.

**Comment by tbaggett** [comment]
@rolfbjarne / @emaf, I am using VS Mac but the issue persists even after running NuGet restore. 

As a temporary workaround, I have explicitly specified "<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>" in the debug configurations and "<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>" in the release ones. I explained to the team that the csproj must be manually edited if they need to run a debug build on device or release build on the simulator.

Can either of you provide the build properties to check for determining the build host and target architectures? I'm hoping to do something like this if those are available.

`<RuntimeIdentifier Condition="{Intel Mac and Simulator target}">iossimulator-x64</RuntimeIdentifier>
<RuntimeIdentifier Condition="{Arm Mac and Simulator target}">iossimulator-arm64</RuntimeIdentifier>
<RuntimeIdentifier Condition="{Device target}">ios-arm64</RuntimeIdentifier>`

**Comment by emaf** [comment]
@tbaggett I think you can use `_IsArm64Machine`, which is only available for iOS.

**Comment by rolfbjarne** [comment]
I'm not sure of `_IsArm64Machine` is set early enough to be able to be used in a csproj, but you can do this for the simulator:

```xml
<RuntimeIdentifier Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' != 'arm64'">iossimulator-x64</RuntimeIdentifier>
<RuntimeIdentifier Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'arm64'">iossimulator-arm64</RuntimeIdentifier> 
```

Note that this doesn't work when building remotely from Windows, only local Mac builds (it'll use the architecture of the Windows machine in that case).

**Comment by tbaggett** [comment]
@emaf / @rolfbjarne, thanks for much for the info. 

I take it there isn't a way to conditionally determine if a simulator or device is selected as the build target? I'm assuming _IsArm64Machine would be used to determine the build host architecture, not the build target one.

**Comment by rolfbjarne** [comment]
@emaf would the `TargetiOSDevice` property be set according to the selected simulator/device?

**Comment by tbaggett** [comment]
@rolfbjarne @emaf thank you both so much for the provided info! We decided to back away from the custom build configurations and return to the default Debug and Release configs to minimize ongoing maintenance. 

I also see the latest VS Mac update is supposed to potentially address the iOS RuntimeIdentifier issue, which is great!
