### ISSUE TITLE
Button doesn't reset to "Normal" if scrolled quickly to the top in IOS

### ISSUE THREAD

**Issue by hiepis** [dotnet/maui#19246]
### Description

Button doesn't reset to "Normal" if scrolled quickly to the top
![Screenshot 2023-12-06 161924](https://github.com/dotnet/maui/assets/6760552/e1892312-8570-4817-a1d9-ab70aa291acb)

https://github.com/dotnet/maui/assets/6760552/bc5a6756-e0ab-4a70-af14-a8890e2e1de8

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.1.1

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by hiepis** [comment]
I created demo project at https://github.com/hiepis/ButtonBug.git

**Comment by samhouts** [comment]
It's a bit tricky to reproduce, but I did see the behavior once. Did this work for you on NET 7?

**Comment by hiepis** [comment]
@samhouts any idea? My application had a list button with image and I don't know how to fix

**Comment by ninachen03** [comment]
I can repro this issue on the latest 17.11.0 Preview 7.0 (8.0.80 &8.0.3) but not repro on Version 17.11.0 NET 7 SDK
