### ISSUE TITLE
iOS - Label within Border with Background does not display

### ISSUE THREAD

**Issue by Beryl0** [dotnet/maui#19259]
### Description

Specific to iOS only (works displays on Android), if you have a Border with a Label as its Content, and the Border has a background color, the Label will not display on the Border.

![Screenshot 2023-12-06 at 17 51 45](https://github.com/dotnet/maui/assets/49538018/c48b1b7f-f802-434d-8129-4a378a6e01b9)

```
Border helpMessage = new Border()
            {
                Content = new Label()
                {
                    Text = HelpMessageText,
                    HorizontalOptions = LayoutOptions.Center,
                    VerticalOptions = LayoutOptions.Center,
                    FontSize = 18,
                    Padding = 10,
                    FontAttributes = FontAttributes.Bold,                  
                },
                VerticalOptions = LayoutOptions.Start,
                HorizontalOptions = LayoutOptions.Center,
                Padding = 0,
                Margin = new Thickness(20, 10, 20, 0),
                StrokeShape = new RoundRectangle
                {
                    CornerRadius = new CornerRadius(10, 10, 10, 10)
                },
                Stroke = (Color)App.ResourceDictionary["Colors"]["Tertiary"],
                BackgroundColor = (Color)App.ResourceDictionary["Colors"]["Secondary"]
            };
```

### Steps to Reproduce

Created Border
Added Label
Added Border to View

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15, iOS 15.2

### Did you find any workaround?

You can use a Frame, but Border has BindableProperties that Frame doesn't.

Instead I gave the Label the Background Color and messed about with the padding to fill the border.

**Comment by kubaflo** [comment]
@mattleibow @Beryl0 This is fixed on the latest main

```
Border helpMessage = new Border()
{
	Content = new Label()
	{
		Text = "Hello world",
		HorizontalOptions = LayoutOptions.Center,
		VerticalOptions = LayoutOptions.Center,
		FontSize = 18,
		Padding = 10,
		FontAttributes = FontAttributes.Bold,
	},
	VerticalOptions = LayoutOptions.Start,
	HorizontalOptions = LayoutOptions.Center,
	Padding = 0,
	Margin = new Thickness(20, 10, 20, 0),
	StrokeShape = new RoundRectangle
	{
		CornerRadius = new CornerRadius(10, 10, 10, 10)
	},
	Stroke = Colors.Blue,
	BackgroundColor = Colors.Red
};
```

<img src="https://github.com/dotnet/maui/assets/42434498/d8ba9d4d-a5e0-4f58-9f5b-2642f57542aa" width="300px"/>

**Comment by mattleibow** [comment]
@kubaflo  @Beryl0  if this is fixed inmain, it might be fixed in the upcoming SR2 release. Can you try version `8.0.7-preview.10003`?

**Comment by kubaflo** [comment]
@mattleibow I tried with the `8.0.10-nightly.10006` version and it looks good to me
<img src="https://github.com/dotnet/maui/assets/42434498/2c4ce9f4-177b-464d-b60c-f9734e4ceb16" width="300px"/>

**Comment by mattleibow** [comment]
OK, in that case I will close this as fixed by some PR in the SR2.
