### ISSUE TITLE
Not able to change title bar color in MAUI UWP

### ISSUE THREAD

**Issue by Rohit123400000000000** [dotnet/maui#19252]
### Description

We are not able to change title color of the MAUI UWP application , it is showing like darkgray color, we have to apply many approached but not able to fix that issue.

This is one of the sample code but we was apply many things like set property from the appshell etc. but color is not changed.

        var baseColor = Windows.UI.Color.FromArgb(255, 255, 255, 255);
        var nativeWindow = handler.PlatformView;
        nativeWindow.Activate();
        AppWindow appWindow = AppWindow.GetFromWindowId(Win32Interop.GetWindowIdFromWindow(WinRT.Interop.WindowNative.GetWindowHandle(nativeWindow)));
        appWindow.TitleBar.ButtonBackgroundColor = appWindow.TitleBar.BackgroundColor = Windows.UI.Color.FromArgb(255, 255, 255, 255);
        appWindow.TitleBar.ButtonPressedBackgroundColor = Windows.UI.Color.FromArgb(255, 255, 255, 255);
        appWindow.TitleBar.ForegroundColor = Windows.UI.Color.FromArgb(0, 0, 0, 0);
        appWindow.TitleBar.IconShowOptions = IconShowOptions.HideIconAndSystemMenu;
        appWindow.TitleBar.ButtonForegroundColor = Windows.UI.Color.FromArgb(255, 255, 255, 255);

it is still show gray color after the title bar in UWP

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by jfversluis** [comment]
I see you mention .NET 7, could you please try if anything changes when you use .NET 8?

You'll always want to (additionally) test the latest available version to see if we fixed already.

**Comment by olographio** [comment]
Hi, I'm having the same issue after updating to .NET8. I'm using MAUI with WinUI however. I do something extremely similar, but to no avail. It's as if the title bar was frozen to the OS defaults. Everything was working flawlessly with .NET 7.

Screenshot:
![image](https://github.com/dotnet/maui/assets/153293395/0c363e89-5616-4c26-9d18-05df2d0714f0)

My code:

`private MauiWinUIApplication WinUIApp => MPC.MForms.WinUI.App.Current;
private msUIXaml.Window NativeWindow => (msUIXaml.Window)Application.Current.Windows.First().Handler.PlatformView;
private msUIWindowing.AppWindow m_appWindow = null;
private msUIWindowing.AppWindow AppWindow {
    get { 
        if(m_appWindow == null){
            var windowHandle = WinRT.Interop.WindowNative.GetWindowHandle(this.NativeWindow);
            var windowId = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(windowHandle);
            m_appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(windowId);
            m_appWindow.Changed += AppWindow_OnChanged;
        }
        return m_appWindow;
    }
}

private msUIWindowing.AppWindowTitleBar m_titleBar = null;
private msUIWindowing.AppWindowTitleBar TitleBar => m_titleBar ?? (m_titleBar = this.AppWindow.TitleBar);

//Apply arbitrary color to title bar.
public override void ApplyTitleBarColor(Color toColor) {
    var winUiColor = toColor.ToWindowsColor();

    var windowCaptionBackgroundBrush = (msUIMedia.SolidColorBrush)this.WinUIApp.Resources["WindowCaptionBackground"];
    windowCaptionBackgroundBrush.Color = winUiColor;

    var windowCaptionBackgroundDisabledBrush = (msUIMedia.SolidColorBrush)this.WinUIApp.Resources["WindowCaptionBackgroundDisabled"];
    windowCaptionBackgroundDisabledBrush.Color = winUiColor;

    var closeButtonBackgroundPointerOverBrush = (msUIMedia.SolidColorBrush)this.WinUIApp.Resources["CloseButtonBackgroundPointerOver"];
    closeButtonBackgroundPointerOverBrush.Color = winUiColor;

    this.TitleBar.InactiveBackgroundColor = winUiColor;
    this.TitleBar.BackgroundColor = winUiColor;
    this.TitleBar.ForegroundColor = winUiColor;
    this.TitleBar.ButtonBackgroundColor = winUiColor;
    this.TitleBar.ButtonForegroundColor = winUiColor;
    this.TitleBar.ButtonHoverBackgroundColor = winUiColor;
    this.TitleBar.ButtonInactiveBackgroundColor = winUiColor;
    this.TitleBar.ButtonPressedBackgroundColor = winUiColor;
}`

------

TitleBar.ExtendsContentIntoTitleBar does nothing and using a custom title bar by adding code to WinUI's platform app.xaml works, but the background color cannot be changed. (Like you can add text, but the background color is locked to the OS defaults). It's weird.

Screenshot:

![image](https://github.com/dotnet/maui/assets/153293395/3446f58a-2f84-4748-8503-770d44d7fc75)

The code:

`<maui:MauiWinUIApplication
    x:Class="MPC.MForms.WinUI.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:xaml="using:Microsoft.UI.Xaml"
    xmlns:maui="using:Microsoft.Maui"
    xmlns:local="using:MPC.MForms.WinUI">
    <maui:MauiWinUIApplication.Resources>

        <DataTemplate x:Key="MauiAppTitleBarTemplate">
            <Border
                Canvas.ZIndex="1" 
                VerticalAlignment="Stretch"
                Margin="0,0,0,0">
                <TextBlock 
                    VerticalAlignment="Center"
                    HorizontalAlignment="Center"
                    Text="Hello World" 
                    FontWeight="Bold"/>
            </Border>
        </DataTemplate>
...`

Thank you for whoever looks into that.

**Comment by Foda** [comment]
@Rohit123400000000000 we have a bigger story to add better titlebar/window customization in MAUI specifically for Windows, but an easy workaround is to just change the `Border` in your template to a `Grid`

**Comment by olographio** [comment]
@Foda That's great news. I think customizing the title bar should be easy and readily available. It adds a lot of style to an app. 

As for the workaround, thank you. I will try later. No offense, but when upgrading to .net8 I face a ton of issues and I'm not ready to deal with that now. It's as if MAUI and its controls started to behave drastically differently.

**Comment by jfversluis** [comment]
I think a lot of work has gone into #23019 that is coming to .NET 9, please try that. If there are still things you're missing after that, please feel free to open something new. Thanks!
