### ISSUE TITLE
MAUI .NET8 Windows ListView HasUnevenRows crashes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#19269]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-NET8-Windows-ListView-HasUnevenRow/10526509)._

---
[severity:It's more difficult to complete my work]
As long as this property is set, regardless of cell Height set or not or what value or cell contents or anything the result is a com crash in an off thread that brings the program down uncatchable, as long as the list contains more than 1 item. I'm attaching a very simple project, pressing the button creates more populated lists and clicking on one crashes the program. Setting HasUnevenRows to false makes it work as expected

---
#### Feedback Bot on 11/27/2023, 06:12 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Repro is on internal community ticket

**Comment by ninachen03** [comment]
Could you provide us with a sample project so we can investigate it? Looking forward to your reply!

**Comment by jfversluis** [comment]
I don't see the reproduction on the internal ticked unfortunately so its hard to make this issue still actionable. Closing this here for now, if this is still an issue for anyone, please open an issue directly here with a reproduction. Thanks!
