### ISSUE TITLE
Toggling backlight causes UI to hang

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#19267]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Toggling-backlight-causes-UI-to-hang/10528910)._

---
I have a button in my XAML which toggles the screen brightness (called from the code behind) is using the code below to toggle

```
        public void SetBrightness(BrightnessLevel brightness)
        {
            // -1 is the device default brightness
            var level = brightness == BrightnessLevel.Mid ? 0.1 : -1;
#if ANDROID
            var window = MainActivity.AppActivity?. Window;
            if (window is not null)
            {
                using (var attr = new WindowManagerLayoutParams())
                {
                    attr. CopyFrom(window. Attributes);
                    attr. ScreenBrightness = (float)level;
                    window. Attributes = attr;
                }
            }
#endif
        }
```

The code behind to toggle looks like this

```
BrightnessService bright { get; set; } = new BrightnessService();

/// <summary>
 /// Set the initial brightness when the view is loaded
 /// </summary>
 void SetBrightness()
 {
     var level = Settings.IsScreenLightHigh;
     bright. SetBrightness(level ? BrightnessLevel.Mid : BrightnessLevel.High);
     brightButtonImage.Source = !level ? "dark_bulb" : "light_bulb";
 }

// UI event from button
void ScreenLightLevelClicked(object sender, EventArgs args)
{
    Settings.IsScreenLightHigh = ! Settings.IsScreenLightHigh;
    SetBrightness();
}

```

If I continually click on the toggle icon, the app slows to a dead halt and becomes unresponsive. It does not crash. Not sure if this is a MAUI or Android issue

---
#### Feedback Bot on 11/29/2023, 07:13 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Does this brightness code also hang if you do an .NET Android app outside the MAUI SDK?

Is this on a device or emulator?

This might also be helpful for us
https://learn.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows

**Comment by nodoid** [comment]
Only tried within a MAUI app rather than a standard .NET Android app. This is happening on a real device (Android 10). I'm not using fast deploy when testing and get the same result in and out of debug mode

**Comment by nodoid** [comment]
https://github.com/nodoid/LightSwitch

**Comment by jenscski** [comment]
```
using (var attr = new WindowManagerLayoutParams())
{
    attr. CopyFrom(window. Attributes);
    attr. ScreenBrightness = (float)level;
    window. Attributes = attr;
}
```

You are disposing the WindowManagerLayoutParams that you are assigning window.Attributes, this may cause problems?

Isn't is possible to just change window.Attributes.ScreenBrightness directly?

`window. Attributes.ScreenBrightness = (float)level;`

**Comment by PureWeen** [comment]
Are you able to reproduce this inside a `dotnet new android` app?
