### ISSUE TITLE
VerticalTextAlignment of Label is not applied in Popup.

### ISSUE THREAD

**Issue by pulmuone** [dotnet/maui#19279]
### Description

VerticalTextAlignment of Label is not applied in Popup.

### Steps to Reproduce

![image](https://github.com/dotnet/maui/assets/42885949/87f4cbe5-4282-418c-886e-9a011a130997)
The label message is not aligned in the yellow center.

VerticalTextAlignment  to the center of the full screen.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

Android

**Comment by drasticactions** [comment]
As you're doing this in the CommunityToolkit.MAUI Popup, you should first [file the bug there](https://github.com/CommunityToolkit/Maui) to verify it's not an issue with the CommunityToolkit. If it is with MAUI itself, we can reopen this issue.
