### ISSUE TITLE
CollectionView SelectionMode Multiple displays wrong ItemTemplate on Windows

### ISSUE THREAD

**Issue by beto-rodriguez** [dotnet/maui#19277]
### Description

When the `CollectionView.Selection` mode is `Multiple` it renders a barely visible checkbox on each item, there seems that there is no way to remove it or style it, this only happens on WinUI.

There is an almost white checkbox that is not part of my ItemsTemplate:

![image](https://github.com/dotnet/maui/assets/10853349/0fdd7a79-aec2-4c07-ad61-4754d8324b67)

When the background has a different color is easier to see that it is a checkbox:

![image](https://github.com/dotnet/maui/assets/10853349/4f0ac93b-0b7b-40a5-9d4a-f851c83c9451)

But again, that checkbox is not part of my ItemsTemplate, I cannot find a way to style it or remove it.

### Steps to Reproduce

1. Follow up the official [docs article](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/selection?view=net-maui-8.0#multiple-selection)
2. See the issue.

### Link to public reproduction project repository

https://github.com/beto-rodriguez/MauiCollectionViewBug

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No, maybe a complete logic to handle the multiple selection?

**Comment by Vroomer** [comment]
Duplicate to https://github.com/dotnet/maui/issues/10036 and https://github.com/dotnet/maui/issues/16066. There is a workaround mentioned in the latter one, but I don't think it completely solves the issue.

**Comment by beto-rodriguez** [comment]
Nice call, I was not able to find those issues!
