### ISSUE TITLE
Issue with Navigation Back Button Disappearing on Windows Platform in .NET MAUI App

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#19275]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Issue-with-Navigation-Back-Button-Disapp/10519885)._

---
I have encountered a problem with the navigation back button functionality in our .NET MAUI app when running it on the Windows platform. Specifically, when navigating to a page inside a FlyoutPage, the navigation back button is not visible.

I have implemented the code from the official Microsoft documentation page [https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/flyoutpage?view=net-maui-8.0], and added additional pages to enable navigation push and pop.
Despite following the documentation and adding the necessary navigation code, the navigation back button remains invisible on the Windows platform.
I have verified that the navigation code works correctly on Android, but the issue persists only on the Windows platform.

---
#### Feedback Bot on 11/19/2023, 06:04 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Can you test with the latest nightly? 

https://github.com/dotnet/maui/wiki/Nightly-Builds
