### ISSUE TITLE
Scrollview inside of Stacklayout doesn't work at all

### ISSUE THREAD

**Issue by prok155** [dotnet/maui#19290]
### Description

When I create Scrollview inside of StackLayout, it doesn't render correctly and I can't even scroll it. 

### Steps to Reproduce

1. Create following layout in your app:
```XAML
   <StackLayout>
        <ScrollView>
            <Grid>
                <Grid.RowDefinitions>
                    <RowDefinition Height="1000"/>
                    <RowDefinition Height="800"/>
                    <RowDefinition Height="1200"/>
                </Grid.RowDefinitions>
                <Button Grid.Row="0" BackgroundColor="Yellow" Margin="15"/>
                <Button Grid.Row="1" BackgroundColor="Green" Margin="15"/>
                <Button Grid.Row="2" BackgroundColor="Pink" Margin="15"/>
            </Grid>
        </ScrollView>
    </StackLayout>
```

2. You will see, that you can't scroll it and it doesn't render correctly.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by PureWeen** [comment]
This is by design @prok155 

https://learn.microsoft.com/en-us/dotnet/maui/migration/layouts?view=net-maui-8.0#scrollview
