### ISSUE TITLE
[.NET MAUI] [BUG] UI doesn't "always" update inside BottomSheetDialogFragment.

### ISSUE THREAD

**Issue by HMorales-ChipSoft** [dotnet/maui#19291]
### Description

When I switch the ContentPage.Content property inside a BottomSheetDialogFragment, the UI doesn't update. A TemplateBinding to the Button.IsVisible property also not updating the UI. This works as expected on the Application.MainPage but not in my [SheetService](https://github.com/HMorales-ChipSoft/Maui_Issues/blob/main/ReproMauiIssue/ReproMauiIssue/Platforms/Android/SheetService.cs). Maybe I'm missing something?

![UI_Issue](https://github.com/dotnet/maui/assets/141022561/1aba19e1-f48e-4343-9197-2ce07e097497)

![image](https://github.com/dotnet/maui/assets/141022561/e3d65b4c-1f25-4abe-a8ac-6382d6e2874d)

### Steps to Reproduce

**Expected Behavior**
The Button and the Content (highlighted parts in the XAML) must show up like in Xamarin Forms.

![Xamarin](https://github.com/dotnet/maui/assets/141022561/b775a087-1498-455c-acaf-474874cd4570)

**Actual Behavior**
Described above.

### Link to public reproduction project repository

https://github.com/HMorales-ChipSoft/Maui_Issues/tree/main/ReproMauiIssue

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

**Comment by XamlTest** [comment]
[ReproMauiIssue.zip](https://github.com/dotnet/maui/files/13884291/ReproMauiIssue.zip)

**Comment by PureWeen** [comment]
@HMorales-ChipSoft I think the problem here is that you're missing a measure call inside your wrapper

I added this to your `SheetViewGroup` and it works for me now

```C#
 protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
            {
                if (_platformView is null)
                {
                    base.OnMeasure(widthMeasureSpec, heightMeasureSpec);
                    return;
                }

                //base.OnMeasure(widthMeasureSpec, heightMeasureSpec);
                _platformView?.Measure(widthMeasureSpec, heightMeasureSpec);
                SetMeasuredDimension(_platformView.MeasuredWidth, _platformView.MeasuredHeight);
            }
```
