### ISSUE TITLE
Child controls doesn't ignore safeArea even if you've disabled the safe area for the page in .Net 8

### ISSUE THREAD

**Issue by Bennynation** [dotnet/maui#19296]
### Description

If you disable the SafeArea on a page, the child control still won't use the space of the SafeArea.

It is exactly the same problem https://github.com/dotnet/maui/issues/12417 which was closed but it still doesn't work in .net 8.

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp_UseSafe.MainPage"             
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="False"
             >
    <Grid VerticalOptions="Start" Background="Purple" RowDefinitions="*,Auto" MinimumHeightRequest="100"  HeightRequest="200" >
        <Button Text="Top" Background="Green"></Button>
        <Button Grid.Row="1" Text="Bottom" Background="Blue"></Button>
    </Grid>

</ContentPage>
```

### Steps to Reproduce

Maui .Net 8
![image](https://github.com/dotnet/maui/assets/63200099/a9a83d5d-e3a2-4292-a43a-042d7b7d22b6)

Forms
![image](https://github.com/dotnet/maui/assets/63200099/34799f8a-766b-46e9-85bd-fc83094eba69)

### Link to public reproduction project repository

https://github.com/Bennynation/Maui-.net-SafeArea-sample.git

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

You can add `IgnoreSafeArea="True"` to the grid.

**Comment by PureWeen** [comment]
@Bennynation Grid also has a safe area property you'll need to toggle

**Comment by Bennynation** [comment]
I agree that putting IgnoreSafeArea="True" fixes the problem and that's what I'm doing at the moment. However, since this is a bug (according to me) I would have thought that maui .net would open a task to possibly correct it, but I don't see one. All the linked issues seem to have been closed although clearly this is not resolved. Do is it mean we're just supposed to ignore that it worked in Xamarin and now it works like that in Maui ? I just wish the Maui team would at least send it to the backlog so that it would be patched one day.

**Comment by PureWeen** [comment]
@Bennynation at this point we aren't going to change the behavior of how IgnoreSafeArea works. That would be too breaking for people that are already using MAUI. 

The current plan, under internal discussion, is to introduce a new set of APIs that work across more platforms and that are overall less confusing as the randomly spread around APIS that we currently ended up with

**Comment by Axemasta** [comment]
> @Bennynation Grid also has a safe area property you'll need to toggle

I had a similar issue with `AbsoluteLayout`, I had no idea that property now existed. You don't actually need to set the iOS safe area if you set it on the control. Definitely a weird developer experience and I preferred how it worked in Xamarin but at least your suggestion works, thanks 🤩
