### ISSUE TITLE
[regression/8.0.0-nightly] Nightly build 9725 broke boxviews do not get their color set anymore

### ISSUE THREAD

**Issue by Zack-G-I-T** [dotnet/maui#19309]
### Description

Using normal maui version, the boxviews that have a color attribute are shown correctly.
However, when using maui nightly build 8.0.4-nightly.9717 - the boxviews do not have the correct color attributed to them.

I am debugging on a physical ios device using a windows PC.

I have attatched screenshots to show the boxviews. The first one is on the normal maui version - see how the big boxview is blue, but in the second one (using nightly build) it has no color.

![image](https://github.com/dotnet/maui/assets/144355037/d5014cd7-48ef-4dfa-a4cb-5a8c2f46bfa9)
![image](https://github.com/dotnet/maui/assets/144355037/52272702-99be-4d46-89df-5b91e63fa288)
![image](https://github.com/dotnet/maui/assets/144355037/1b9634a1-78d5-43ea-ba08-8d9d543c7225)

### Steps to Reproduce

1. Download repo
2. Run as normal - see the correct behaviour
3. Change to use nightly build - see different behaviour

### Link to public reproduction project repository

https://github.com/Zack-G-I-T/NightlyBuildIssue

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

iOS

**Comment by gabsamples6** [comment]
we are also affected on this one and because we use Maui Community toolkit statecontainer to apply shimmering to our pages and the boxview is used all the pages where we apply the shimmering (loads of them) they look plain white .

It makes our app not suitable for production.

**Comment by jsuarezruiz** [comment]
@jfversluis Have done some tests on main branch and cannot reproduce the issue. Could you do some extra tests?
![image](https://github.com/dotnet/maui/assets/6755973/e3f3f5fb-f956-4635-a263-884737f82e23)
You can find the sample tests ready here https://github.com/dotnet/maui/tree/fix-19309

**Comment by Redth** [comment]
Looks like this regressed in: https://github.com/dotnet/maui/pull/18434

**Comment by davidortinau** [comment]
In case this matters, I'm on nightly 9742 and the first time I navigate to the page I see the box and then it disappears. I resize the window to no avail, but I can navigate away and back to see the BoxView once more. Mac Catalyst.

```csharp
protected override void Build()
    {
        this.Title = "BoxViews";

        this.Content = new ScrollView{
            Content = new VerticalStackLayout{
                Spacing = 12,
                Children = {
                    new H1("100x100"),
                    new Separator(),
                    new BoxView{ Color = AppColors.Primary }.Size(100),       
                }
            }.DynamicResource(Label.StyleProperty, "MainContainer")
        };
    }
```

**Comment by gabsamples6** [comment]
@PureWeen  hi - glad to see this fixed as it affected us too, but could please advise which night build is this in? tried 9742 and we still have an issue 

many thanks
