### ISSUE TITLE
"FragmentManager has been destroyed" upon changing orientation of phone, after app is closed, but after a foreground service has started

### ISSUE THREAD

**Issue by flemingho** [dotnet/maui#19320]
### Description

Debugging on local (by USB) android phone (SamsungZFold), I start a foreground service, I can change phone orientation from portrait to landscape with no issues.

But after I close the app (debugging is still connected and running) the service is still running, but as soon as I change the phone orientation the debugger raises the "FragmentManager has been destroyed" exception, and then the service is no longer running (in the background).

![image](https://github.com/dotnet/maui/assets/18223431/2bbcf34a-d152-4499-b40d-bbb23495403e)

Even without debugging, running the app locally on the device and following the reproducible steps the service is stopped, unexpectedly. 

### Steps to Reproduce

1. Build and deploy (debug) to local device.
2. while debugging click on the hamburger menu
3. enter anything in the text line (at the top) and press the "Start Service" button. This will start the foreground "Examples" service and there will be a notification.
5. While the app/UI is running changing device orientation will not raise the exception.
6. Close the app (while the service is still running, do not stop the service). Debug connection should still be alive.
7. Then change device orientation and the exception should be thrown.

### **NOTE**
I found that changing to .NET7 - by editing the .csproj file and doing a search and replace of "net8" to "net7", and then rebuilding the project - that the exception does not get thrown and that the service continues to run.

**.NET 8**
![image](https://github.com/dotnet/maui/assets/18223431/e985f950-9d0a-4473-ad17-641381306011)

![image](https://github.com/dotnet/maui/assets/18223431/f0da90f3-431a-405c-ae00-db9f6bfca5f5)

**.NET 7**
![image](https://github.com/dotnet/maui/assets/18223431/80fd5600-2d92-48d8-bad2-9a68ef7db108)

### **Source**
Attached is the zip of the source.

[MauiAndroidForegroundService.zip](https://github.com/dotnet/maui/files/13625979/MauiAndroidForegroundService.zip)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No.  Because I actually need  .NET8 features that are not in .NET7. (Not part of this test case)

![image](https://github.com/dotnet/maui/assets/18223431/77c77c4f-3250-4c26-868a-6058c605d7d6)

**------- Visual Studio Info** 
Microsoft Visual Studio Community 2022
Version 17.9.0 Preview 1.1
VisualStudio.17.Preview/17.9.0-pre.1.1+34321.82
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

ASP.NET and Web Tools   17.9.101.55877
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.9.101.55877
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.9.101.55877
Azure Functions and Web Jobs Tools

C# Tools   4.9.0-1.23560.3+78d23490492f4c9ff64c8a3dd0eb0accf9dd56ec
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.9.0 (b3bca6f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.9.1.2356701+b8cf937516af19ae840ef2598c8bd7b2631e6f25
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.9.7.1
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.21025.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-1.23560.3+78d23490492f4c9ff64c8a3dd0eb0accf9dd56ec
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.8.0-beta.23523.7+0c5e24d19dc915b00b8755a8532bfb2582aa2b47
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.9.0.27 (main@0338b26)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.9.1.17 (remotes/origin/main@714487a984)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

**Comment by flemingho** [comment]
Link to public reproduction project repository:  https://github.com/flemingho/Issue_FragmentManagerDestroyed

**Comment by MarcWalen** [comment]
I'm having the exact same problem. Here is the AppCenter stacktrace:
`InstanceMethods.CallIntMethod (JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:20203
JniInstanceMethods.InvokeAbstractInt32Method (String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:492
BackStackRecord.Commit () C:\a\_work\1\s\generated\androidx.fragment.fragment\obj\Release\net7.0-android\generated\src\AndroidX.Fragment.App.BackStackRecord.cs:131
FlyoutViewHandler.UpdateDetailsFragmentView () D:\a\_work\1\s\src\Core\src\Handlers\FlyoutView\FlyoutViewHandler.Android.cs:83
FlyoutViewHandler.LayoutAsFlyout () D:\a\_work\1\s\src\Core\src\Handlers\FlyoutView\FlyoutViewHandler.Android.cs:219
FlyoutViewHandler.LayoutViews () D:\a\_work\1\s\src\Core\src\Handlers\FlyoutView\FlyoutViewHandler.Android.cs:140
FlyoutViewHandler.UpdateFlyoutBehavior () D:\a\_work\1\s\src\Core\src\Handlers\FlyoutView\FlyoutViewHandler.Android.cs:272
FlyoutViewHandler.MapFlyoutBehavior (IFlyoutViewHandler handler, IFlyoutView flyoutView) D:\a\_work\1\s\src\Core\src\Handlers\FlyoutView\FlyoutViewHandler.Android.cs:319
PublicKeyToken=null]].<Add>b__0 (IElementHandler h, IElement v) D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:172
PropertyMapper.UpdatePropertyCore (String key, IElementHandler viewHandler, IElement virtualView) D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:47
PropertyMapper.UpdateProperty (IElementHandler viewHandler, IElement virtualView, String property) D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:72
ElementHandler.UpdateValue (String property) D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:87
FlyoutPage.OnMainDisplayInfoChanged (Object sender, DisplayInfoChangedEventArgs e) D:\a\_work\1\s\src\Controls\src\Core\FlyoutPage\FlyoutPage.cs:346
DeviceDisplayImplementationBase.OnMainDisplayInfoChanged (DisplayInfoChangedEventArgs e) D:\a\_work\1\s\src\Essentials\src\DeviceDisplay\DeviceDisplay.shared.cs:142
DeviceDisplayImplementationBase.OnMainDisplayInfoChanged () D:\a\_work\1\s\src\Essentials\src\DeviceDisplay\DeviceDisplay.shared.cs:149
Listener.OnOrientationChanged (Int32 orientation) D:\a\_work\1\s\src\Essentials\src\DeviceDisplay\DeviceDisplay.android.cs:113
System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
<>c__DisplayClass2_0.<Post>b__0 () /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:36
RunnableImplementor.Run () /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36
IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:84
JNINativeWrapper.Wrap_JniMarshal_PP_V (_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:26
java.lang.IllegalStateException: FragmentManager has been destroyed
androidx.fragment.app.FragmentManager.enqueueAction FragmentManager.java:1666
androidx.fragment.app.BackStackRecord.commitInternal BackStackRecord.java:341
androidx.fragment.app.BackStackRecord.commit BackStackRecord.java:306
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run RunnableImplementor.java:31
android.os.Handler.handleCallback Handler.java:958
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loopOnce Looper.java:230
android.os.Looper.loop Looper.java:319
android.app.ActivityThread.main ActivityThread.java:8893
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:608
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1103`

**Comment by NetCSDev** [comment]
I also experienced similar issue even with  maui control version 8.0.20

Xamarin Exception Stack:
Java.Lang.IllegalStateException: FragmentManager has been destroyed
  at Java.Interop.JniEnvironment.InstanceMethods.CallIntMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
  at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeAbstractInt32Method(String , IJavaPeerable , JniArgumentValue* )
  at AndroidX.Fragment.App.FragmentTransactionInvoker.Commit()
  at Microsoft.Maui.Handlers.FlyoutViewHandler.UpdateDetailsFragmentView()
  at Microsoft.Maui.Handlers.FlyoutViewHandler.LayoutAsFlyout()
  at Microsoft.Maui.Handlers.FlyoutViewHandler.LayoutViews()
  at Microsoft.Maui.Handlers.FlyoutViewHandler.UpdateFlyoutBehavior()
  at Microsoft.Maui.Handlers.FlyoutViewHandler.MapFlyoutBehavior(IFlyoutViewHandler handler, IFlyoutView flyoutView)
  at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IFlyoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IFlyoutViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
  at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
  at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
  at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property)
  at Microsoft.Maui.Controls.FlyoutPage.OnMainDisplayInfoChanged(Object sender, DisplayInfoChangedEventArgs e)
  at Microsoft.Maui.Devices.DeviceDisplayImplementationBase.OnMainDisplayInfoChanged(DisplayInfoChangedEventArgs )
  at Microsoft.Maui.Devices.DeviceDisplayImplementationBase.OnMainDisplayInfoChanged()
  at Microsoft.Maui.Devices.DeviceDisplayImplementation.Listener.OnOrientationChanged(Int32 )
  at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
  at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
  at Java.Lang.Thread.RunnableImplementor.Run()
  at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
  at java.lang.IllegalStateException: FragmentManager has been destroyed
  at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1666)
  at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
  at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
  at mono.java.lang.RunnableImplementor.n_run(Native Method)
  at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
  at android.os.Handler.handleCallback(Handler.java:883)
  at android.os.Handler.dispatchMessage(Handler.java:100)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7397)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

Thread 2:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1720)
2   java.lang.Thread.getAllStackTraces(Thread.java:1796)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1146)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:58)
5   mono.java.lang.RunnableImplementor.n_run(RunnableImplementor.java:-2)
6   mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
7   android.os.Handler.handleCallback(Handler.java:883)
8   android.os.Handler.dispatchMessage(Handler.java:100)
9   android.os.Looper.loop(Looper.java:214)
10  android.app.ActivityThread.main(ActivityThread.java:7397)
11  java.lang.reflect.Method.invoke(Method.java:-2)
12  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
13  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 1.0 (8.0.80) . Can not repro on Android platform.
