### ISSUE TITLE
[Bug] Crash when calling ChangeCanExecute() from non-UI thread

### ISSUE THREAD

**Issue by Daniellled** [dotnet/maui#1932]
### Description

Same bug as https://github.com/xamarin/Xamarin.Forms/issues/5679 but still happens in MAUI

### Steps to Reproduce

Run async methods which triggers ChangeCanExecute(). You can i.e. create a button with async Command which changes one of the binding property and this binding property raise ChangeCanExecute() in the setter.

### Expected Behavior

App should not crash. Xamarin documentation shows that this should work from the VM - https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/commanding

### Actual Behavior

App crashes when running async method which triggers ChangeCanExecute(). The problem exists both on Android and iOS.

### Basic Information

- Version with issue: Preview 6
- Last known good version:
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 2.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  10.0.19041
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Invoke on the UI thread

```
Device.BeginInvokeOnMainThread(() =>
            {
                (ClickCommand as Command).ChangeCanExecute();
            });
```

**Comment by mattleibow** [comment]
A very interesting thing happens... This is exactly the same on WPF.... I can set a string property that is bound to a label, but it throws when firing the event of on changed...

That was a bit weird.

**Comment by mattleibow** [comment]
I see WPF also has an issue logged: https://github.com/dotnet/wpf/issues/4473

**Comment by mattleibow** [comment]
Closing this as we (the framework) cannot be responsible for marshalling things to different threads. 

Bindings work because they are running on the UI thread and respond to the property changed events. However, the `CanExecuteChanged` event does not use bindings and instead just sets the `IsEnabled` property which directly accesses the UI element.
