### ISSUE TITLE
iOS - Incorrect Coordinates Returned by TapGestureRecognizer

### ISSUE THREAD

**Issue by kasanhoon** [dotnet/maui#19327]
### Description

I am encountering an issue with the TapGestureRecognizer in a .NET 8 MAUI iOS environment.

The GetPosition() method from TappedEventArgs is supposed to return the relative coordinates of the touch point, but it's yielding incorrect values

`MainPage.xaml`
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TapTest.MainPage">

    <Grid x:Name="TapAreaGrid" BackgroundColor="LightBlue">
        <Grid.GestureRecognizers>
            <TapGestureRecognizer Tapped="OnTapped" />
        </Grid.GestureRecognizers>
        <Image x:Name="ChildView" Source="dotnet_bot.png" WidthRequest="100" HeightRequest="100" BackgroundColor="LightPink" />        
    </Grid>

</ContentPage>
```
`MainPage.xaml.cs`
```c#
using System.Diagnostics;

namespace TapTest
{
    public partial class MainPage : ContentPage
    {        
        public MainPage()
        {
            InitializeComponent();
        }

        private void OnTapped(object sender, TappedEventArgs e)
        {
            var point = e.GetPosition(ChildView);
            Debug.Print($"point:{point}");
        }
    }
}
```

In the .NET 7 environment, this code correctly returns the relative coordinates of the touch point on `ChildView`. However, in the .NET 8 environment, specifically on iOS, it seems to return absolute coordinates instead of relative ones. This behavior appears to be isolated to the `iOS` platform in the .NET 8 environment.

### Steps to Reproduce

1. Create a default MAUI project.
2. Replace the `MainPage.xaml` and `MainPage.xaml.cs` with the code provided above.
3. Build & Execute the project on iOS.
4. Check the log for the recorded touch coordinates.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

ios 17.0

### Relevant log output

```shell
If you touch the first pixel in the image, the log that appears will be as follows:

.net 7 result (ios)
[0:] point:{X=0 Y=0}

.net 8 result (ios)
[0:] point:{X=147 Y=270}
```

**Comment by kasanhoon** [comment]
@MartyIX You're right. Previously, even if the sender's child was passed as a parameter to GetPosition, it correctly returned relative coordinates. Now, this issue is happening only in the .NET 8 environment on iOS. The same code, when executed on iOS with .NET 7, returns the relative coordinates of the sender's child correctly.

<.net 7 ios screenshot>
![net7tap](https://github.com/dotnet/maui/assets/5285800/283406d1-a777-4b19-9bdd-03ae73fed13a)

<.net 8 ios screenshot>
![net8tap](https://github.com/dotnet/maui/assets/5285800/7fefd02d-6c05-4d19-8c19-21eff002eb6b)

The LightBlue area is the Grid that receives the tap event, and the LightPink area is the child image of the Grid. The size of the LightPink area is the same in both scenarios, with a width of 100px and a height of 100px. When the first pixel of the LightPink area is selected, .NET 7 correctly returns 0,0, but .NET 8 returns the distance from the origin point 0,0 of the LightBlue area.

**Comment by mikeparker104** [comment]
Potential [workaround](https://gist.github.com/mikeparker104/8df7ba3eb4cf2dc4b747d2237811a734) pending updated package release.
