### ISSUE TITLE
Error DEP0700 on defualt MAUI template

### ISSUE THREAD

**Issue by Wemmons831** [dotnet/maui#19325]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: Windows 11
Microsoft Visual Studio Community 2022 Version 17.8.3

I made a new project following the .NET maui tutorial but I get the following error when I try to run the app.
```
DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 13, Reason: 'com.companyname.vector_notes' violates pattern constraint of '[-.A-Za-z0-9]+'.
The attribute 'Name' with value 'com.companyname.vector_notes' failed to parse.
```
I also get this message:
![image](https://github.com/dotnet/maui/assets/69495081/67d98df2-ba50-4c5c-98bd-b88122faf873)
However when I got the my configuration manager Deploy is enabled:
![image](https://github.com/dotnet/maui/assets/69495081/25439652-e0da-4971-865d-ebe44995474d)

**Comment by lukewire129** [comment]
Vector Notes -> VectorNotes

Would you like to rename the project and try again?

**Comment by jfversluis** [comment]
As indicated above, you will want to avoid spaces in your project name. That will be used for also the unique identifier for your app and the app stores have restrictions in place that your identifier has to ad here to this pattern: `[-.A-Za-z0-9]+` which basically means only hyphens, uppercase or lowercase letters and numbers.

Rename your project and it should be all good!
