### ISSUE TITLE
Maui Blazor App Without Root Page (@page "/") Does No Longer Work (Error 'Not Found') With .NET 8

### ISSUE THREAD

**Issue by Thomr77** [dotnet/maui#19326]
### Description

One of our Maui Blazor projects we are currently upgrading from .Net 7 -> .Net 8 does not use `@page` directives (`@page "/[path]"`). With .Net 8 it no longer loads with error 'Not Found'.

This has been working fine previously.

Thanks!

### Steps to Reproduce

- Create a new Maui Blazor project.
- In the file [Project]\Components\Pages\Home.razor replace the `@page "/"` with anything else like `@page "/SomePath"`.
- Run this to see the error 'Not Found'.

### Link to public reproduction project repository

https://github.com/Thomr77/MauiBlazorNoRootPage

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Did you find any workaround?

Add a dummy `@page "/"` into the MainLayout.razor file.

**Comment by jaosnz-rep** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 1, can repro on any platform with Maui Blazor project.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The behavior you're observing after the upgrade is expected and correct. It's not clear how it used to work without the `@page` directive in the past, as there should have been some mapping somewhere to point to that page at startup.
In .NET 8 it is now possible to do the following to indicate which page should be loaded on startup:
```razor
<BlazorWebView StartPath="SomePage" ... />
```
However, given that we haven't seen many customers struggling with this we're going to close this issue as it isn't worth spending time on investigating wrong behavior for .NET 7 that is not critical.
