### ISSUE TITLE
Restore failures - change version, delete bin/obj, reload

### ISSUE THREAD

**Issue by MV10** [dotnet/maui#19339]
### Description

As of .NET 8, if you create a project, change the version numbers, and delete the bin/obj directories, NuGet restore will fail. There have been many, many bugs reported about version and other project-level changes breaking restore, so perhaps this is a duplicate, but I couldn't find anything exactly like this one. This seems to be new in the .NET 8 release, previously I was using .NET 7 and bin/obj deletion was something I had to do regularly and it didn't cause problems. (Not sure which v7 release exactly, though,)

In this case I was using the project properties GUI:
![image](https://github.com/dotnet/maui/assets/794270/90778c97-f012-47fa-8402-d58c54d5e0d3)

The reported errors and locations are:
![image](https://github.com/dotnet/maui/assets/794270/ff51c837-bd99-4fcc-b03d-09fbb566edf4)

Restore works again if the versions are set back to 1.0 and 1 and bin/obj are deleted, then the project is reloaded.

The issue template forces me to choose a platform, but I doubt this is platform-specific. Again it's a purely off-the-shelf template project so Win, Android, and Apple are enabled by default. A build isn't even necessary to reproduce this.

### Steps to Reproduce

1. Create a new MAUI template app
2. Use the project property page to the change the display version to 2.0 and the version to 2
3. Close Visual Studio
4. Delete the bin and obj directories
5. Re-open VS and load the solution

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Not platform specific, as far as I can tell

**Comment by MV10** [comment]
Considering it _only_ happens with MAUI projects, and MAUI has a long history of these types of bugs, and I haven't seen any such thing with any other project type, I very strongly doubt it's a VS issue. Similar MAUI bugs have been (supposedly) fixed over the last two years or so, and there are open version-related MAUI bugs as I write this.

**Comment by jfversluis** [comment]
@MV10 .NET MAUI has some unique concepts in the .NET space. That means, there is also specific tooling inside of VS to support that. Looking at this issue I would think this falls into that category. Please report it there as suggested if you're still experience this. Thanks!
