### ISSUE TITLE
[iOS] Border.Shadow hide the collectionView Header

### ISSUE THREAD

**Issue by Victor-Porter** [dotnet/maui#19338]
### Description

I have created a collectionView with a header, which contains a border.

If I apply shadow style to the border, the header disappears.

**Expectation**
![image](https://github.com/dotnet/maui/assets/137196565/a77dfa3c-4dad-4ea3-a984-f0a7f0f996ed)

**Reality**
![image](https://github.com/dotnet/maui/assets/137196565/88d89864-08d1-4924-832e-ba7dfc682a74)

### Steps to Reproduce

1. Create a new MAUI project.
2. Create a CollectionView with a header.
3. Set a border component in the header.
4. Apply shadow style to the border.
5. Launch the application and check that the header is not displayed.

### Link to public reproduction project repository

[Link to the repository](https://github.com/MADSENSE/MADSENSE.MAUI.Sample.App/tree/border-shadow-collectionView-header)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.3

### Did you find any workaround?

If you set the border component inside a ContentView, works fine for me.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3). Repro on iOS 17.0 and MacCatalyst, not repro on Windows 11 and Android 14.0-API34 with below Project:
[MADSENSE.MAUI.Sample.App-border-shadow-collectionView-header.zip](https://github.com/dotnet/maui/files/13901608/MADSENSE.MAUI.Sample.App-border-shadow-collectionView-header.zip)
