### ISSUE TITLE
CascadeInputTransparent not working

### ISSUE THREAD

**Issue by Yannikk1996** [dotnet/maui#19332]
### Description

CascadeInputTransparent not working as expected. Using a Scrollview/Grid/Stacklayout and settting CascadeInputTransparent  = false and set InputTransparent = true on these layouts leads to InputTransparent childrens.

### Steps to Reproduce

Create a Layout with childrens with touch gestures and set CascadeInputTransparent  = false and InputTransparent = true on Layout.

### Link to public reproduction project repository

https://github.com/Yannikk1996/Maui-CascadeInputTransparent

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

**Comment by PavloLukianets** [comment]
+1 here, currently searching for a workaround

**Comment by mattleibow** [comment]
This is the root ScrollView in your example causing all the issues. If you just set `InputTransparent = true` on the content layout then it should work.
