### ISSUE TITLE
Local Notifications in .NET MAUI Essentials custom sound is not working

### ISSUE THREAD

**Issue by tbink** [dotnet/maui#19346]
### Discussed in https://github.com/dotnet/maui/discussions/4216

I cannot get a Custom sound to play ... I only get the default sound

(12-2-2023 /Maui using.net8, visual studio 2022 preview latest) --  it's working but I can't get a custom sound to load and play | pluging ver. = 11.0.1-preview 01 | the sound file is in Resources/Raw and its BuildAction is MauiAsset
these permissions are set

<manifest xmlns:android="http://schemas.android.com/apk/res/android">

	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:supportsRtl="true"></application>

	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

	<uses-permission android:name="android.permission.INTERNET" />

	<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />

	<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />

	<uses-permission android:name="com.android.alarm.permission.SET_ALARM" />

	<uses-permission android:name="android.permission.USE_EXACT_ALARM"/>

	<uses-sdk android:minSdkVersion="33" android:targetSdkVersion="34" />

</manifest>

            var request = new NotificationRequest
            {
                NotificationId = 1337,
                Title = "Counter",
                Description = $"Current count is {count++}",
                ReturningData = "Dummy data",
                CategoryType = NotificationCategoryType.Alarm,
                Sound = "Tibet2.mp3",
                Schedule = new NotificationRequestSchedule
                {
                    NotifyTime = DateTime.Now.AddSeconds(5)
                },

                Android = new AndroidOptions
                {
                    AutoCancel = false,
                    Priority = (AndroidPriority)NotificationCategoryType.Alarm
                }

            };
            LocalNotificationCenter.Current.Show(request);

**Comment by jfversluis** [comment]
There is no notifications functionality in Essentials (or .NET MAUI). You're probably using this plugin: https://github.com/thudugala/Plugin.LocalNotification

I suggest raising an issue there.
