### ISSUE TITLE
[Testing] iOS compatibility tests currently failing on main

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#19343]
### Description

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8794917&view=logs&s=c4ea5c64-f730-50e7-d210-4676a251abc0&j=bc1d4079-a306-5df1-792a-3c37420504d1

They appear to fail to install on to the iOS device fairly frequently.

**Comment by jfversluis** [comment]
Similar/related/duplicate: #18989
