### ISSUE TITLE
Crash when using Picker while also using UIDeviceFamily 6

### ISSUE THREAD

**Issue by beeradmoore** [dotnet/maui#19354]
### Description

The default MAUI design for Mac Catalyst is not ideal, especially when you disable all styles to get a native look and feel. I want my macOS app to look and feel like a macOS app, not an iPad app. 

Luckily there is support for this by setting `UIDeviceFamily` to 6, as documented [here](https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/user-interface-idiom).

A side effect of doing this is that certain basic UI components now crash. In my case I found out `Picker` crashes. According to some other threads (#10622 , #8715) showing this issue (and that it also happens with a `Slider`)

### Steps to Reproduce

1. Create MAUI app
2. Follow the steps [here](https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/user-interface-idiom) to change to use macOS style layout for Mac Catalyst.
3. Add Picker as per the sample [here](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/picker?view=net-maui-8.0#set-the-itemssource-property).
4. Run the program and try use your picker.

Additionally if you don't do the step in point 2 the picker will be empty, this matches what is happening in #18015

### Link to public reproduction project repository

https://github.com/beeradmoore/maui-issue-picker-test

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 14.1.2

### Did you find any workaround?

To not use `UIDeviceFamily` as 6 but instead 2. But doing so also leads to issues like #18015. It also means your macOS app will not look like a native macOS app.

**Comment by drasticactions** [comment]
So... strictly speaking, this is not a "bug" in MAUI, but it is... kinda... it's complicated.

UIPickerView is not supported in the Mac Catalyst Desktop Idiom, period. If you set your app to use the Catalyst desktop idiom and use it, macOS throws an exception telling you that you can't use that control from the desktop idiom (this also applies to UIRefreshControl and UIStepper as well, and maybe some others). This is not a MAUI bug; it will never work unless Apple supports it in Catalyst (which my guess would be that they wouldn't as if you were building a native Mac Catalyst app, you could use a different view like SwiftUIs Picker control, which is supported). Also, your debug output should show macOS telling you this error, it's not hidden.

Now, if you were hellbent on using UIPickerView within Catalyst, there are ways to [force it](https://github.com/drasticactions/Drastic.ForbiddenControls) to work, but this is very much a hack on hidden APIs within Catalyst and YMMV on it staying "working", if at works at all within a MAUI UI app.

So if MAUI wants to support controls like Picker within a Mac Catalyst Desktop Idiom, it would need to build a custom control to do it. Some controls (like UIButton) let you set a preference for how to [present the view](https://github.com/drasticactions/MauiLang/blob/main/src/MauiLang/MauiProgram.cs#L28C34-L28C59) but that's not available on UIPickerView. There's no way around it that I can think of. 

So this isn't really a "bug" in that "an issue written into the MAUI codebase that can be fixed", it's a new control that has to be written. If nothing else, this should be called out in the docs as controls that are not supported within this mode.

**Comment by beeradmoore** [comment]
That makes a whole lot of sense, thanks for the detailed response.

> your debug output should show macOS telling you this error

Yesterday I was getting a mixture of helpful and unhelpful crashes. Today it is just the unhelpful ones.

```
=================================================================
	Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x104ea5b25 - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : mono_dump_native_crash_info
	0x104e4d7ee - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : mono_handle_native_crash
	0x104dcb2be - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : mono_crashing_signal_handler
	0x7ff8154f637d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x1025 - Unknown
	0x7ff818f09fa9 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : -[NSApplication reportException:]
	0x7ff818ba1de6 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : -[NSApplication run]
	0x7ff818b75d41 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : NSApplicationMain
	0x7ff818e29be9 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : _NSApplicationMainWithInfoDictionary
	0x7ff82ef9d27b - /System/Library/PrivateFrameworks/UIKitMacHelper.framework/Versions/A/UIKitMacHelper : UINSApplicationMain
	0x7ff925303399 - /System/iOSSupport/System/Library/PrivateFrameworks/UIKitCore.framework/Versions/A/UIKitCore : UIApplicationMain
	0x104a8bdda - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : xamarin_UIApplicationMain
	0x104eba835 - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : do_icall
	0x104eb8f97 - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : do_icall_wrapper
	0x104ea9c36 - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : mono_interp_exec_method
	0x104ea73a3 - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : interp_runtime_invoke
	0x104d6b358 - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : mono_runtime_invoke_checked
	0x104d7194b - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : mono_runtime_exec_main_checked
	0x104e2c302 - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : mono_jit_exec
	0x104ab43e3 - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : xamarin_main
	0x104f8a914 - /Users/beeradmoore/Downloads/maui-issue-picker-test-main/PickerTest/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/PickerTest.app/Contents/MacOS/PickerTest : main
	0x7ff81513d386 - /usr/lib/dyld : start

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7ff818f0a219):0x7ff818f0a209  48 89 c7 ff 15 4e 1a 0d 3f 48 89 05 77 4b f8 3d  H....N..?H..wK.=
0x7ff818f0a219  0f 0b 48 89 c7 e8 23 0d c6 00 31 ff 31 f6 31 c0  ..H...#...1.1.1.
0x7ff818f0a229  e8 e0 4c e4 ff e8 43 0d c6 00 0f 0b eb 00 48 89  ..L...C.......H.
0x7ff818f0a239  c3 e8 2b 0d c6 00 48 89 df e8 0f 06 c6 00 e8 14  ..+...H.........

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:xamarin_UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:UIApplicationMain <0x0006e>
	  at UIKit.UIApplication:Main <0x0015a>
	  at PickerTest.Program:Main <0x0002c>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00118>
	  at <unknown> <0x00000>
=================================================================
```

Looking through my search history I can see I was looking at `UICatalystMacIdiomUnsupported_Internal` or `_throwForUnsupportednonMacIdiomBehaviorWithReason`. At the time they both seemed to me like something MAUI would throw if someone had forgotten to implement the backend picker for Mac Catalyst, but looking again I can see how they mean "this does not exist in Mac Catalyst".


App is not destined for AppStore so your ForbiddenControls seemed like a good path, unfortunately using it with UIDeviceFamily=6 brings up box in the middle of the screen with no items much like #18015.


In my case the picker is a box for selecting different connection types to a server, I might make a new popup window so I can also add a summary as to what each option means. I'll then know to avoid picker and a few other controls for desktop MAUI.


Thanks again for the detailed answer. Over the Christmas break I'll see if I can find all controls that fail when UIDeviceFamily=6 so I can do a PR the docs with a warning notice or something on relevant pages.

**Comment by drasticactions** [comment]
@beeradmoore Yeah, there could be more to explain the controls that won't work in this idiom. As it's a native crash, you won't get a nice exception from the Mac for it. 

@davidbritch would it make sense for us to document that `UIStepper`, `UIPickerView`, and `UIRefreshView` (And, by extension, controls that implement it in MAUI) won't work in the Mac Catalyst Desktop Idiom if you enable it? I can write up the doc if needed.

The issue with "Drastic.ForbiddenControlls" is that it is calling private APIs within Catalyst to force it to work. Apple would, most likely, flag it if you use it within the app you submit to the store, and it can also break at any time. IMO I would not recommend it for an application intended for the App Store. It's also not something I would advocate putting into MAUI itself for that reason. IMO the best path would be to either:

- Figure out how to bind SwiftUI or access Swift APIs from C# (Which is really the dream here)
- Write a new picker control.

Of those, writing the new picker seems like the ideal approach.

**Comment by davidbritch** [comment]
@drasticactions I've created a docs issue for this: https://github.com/dotnet/docs-maui/issues/1951

I'll do the update this month.

**Comment by beeradmoore** [comment]
Happy for this to be closed if you don't need it anymore
