### ISSUE TITLE
[IOS] Maui .NET 8 The app has been terminated when start debugging 

### ISSUE THREAD

**Issue by alzubitariq** [dotnet/maui#19358]
### Description

When debug the application, the connection to the Mac is immediately disconnected
The following message appears (The app has been terminated )

Mobile model : iPhone 14 Pro Max with iOS 17
Visual Studio : Enterprise Latest version

if it is related to watchdog ! is there an way to disable it?

actually I found this link about disable-watchdog but don't understand 

> https://github.com/wangyu-/ios-codes/blob/master/Recovery(ios8.1)/disable-watchdog

or maybe this issue related to :

**Quoted**

> I talked to someone at Apple, and they gave me a temporary solution. As others already have said, larger apps with lots of dependencies are taking too long to launch. This is causing the debugger to abort and time out. To fix that, follow the steps:
> 
> Create a file called .lldbinit on your home directory (~)
> Add this line to the file: settings set plugin.process.gdb-remote.packet-timeout 300
> Restart Xcode and try again
> It's working fine after that.

### Steps to Reproduce

1- Create New .Net8 MAUI APP
2- Debug on IOS Physical Device => IPhone

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

iOS, macOS

### Affected platform versions

iOS

### Did you find any workaround?

No

**Comment by alzubitariq** [comment]
In fact, I cannot work on developing applications well
Working with iOS is very annoying and painful. Don't tell me the application is too big. Once I create an empty project, I cannot try it.

I always debug the application on Android, and in the final stages I debug it on iOS, but the attempt fails. :(

**Comment by emaf** [comment]
This is already being tracked on the Visual Studio Developer Community by https://developercommunity.visualstudio.com/t/Visual-Studio-179-Preview-2-cant-debug/10538761

**Comment by alzubitariq** [comment]
@emaf 

Where ? I think your link is broken

**Comment by emaf** [comment]
Sorry, it should be public now
