### ISSUE TITLE
Not able to update CollectionView header

### ISSUE THREAD

**Issue by juniorsaraviao** [dotnet/maui#19379]
### Description

I want to update the CollectionView header using a button, it works as expected on NET Maui Android but not on iOS.

This is the app working as expected on Android:

| Android |
| ------------- |
| <video src="https://github.com/dotnet/maui/assets/43689290/75e5b6e9-aa82-4d1f-9ed9-b21127e3fa34" width=180 height=392> |

but it doesn't change on iOS:

| iOS |
| ------------- |
| <video src="https://github.com/juniorsaraviao/MauiSample8/assets/43689290/41e2ae8b-92c6-47b4-8e39-0b5e030ba8ec" width=180 height=392> |

### Steps to Reproduce

1. Clone the project [link](https://github.com/juniorsaraviao/MauiSample8/tree/master).
2. Execute it on iOS Simulators or iPhones.
3. Tap the button Update the CollectionView header.

### Link to public reproduction project repository

https://github.com/juniorsaraviao/MauiSample8/tree/master

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.2 and above

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3 and 7.0.101). Repro on iOS 17.0 and MacCatalyst, not repro on Android 14.0-API34 with below Project:
[MauiSample8.zip](https://github.com/dotnet/maui/files/13935882/MauiSample8.zip)

For Windows 11:  CollectionView header doesn't display.

**Comment by kubaflo** [comment]
@jsuarezruiz @PureWeen @juniorsaraviao hopefully fixed in this PR: https://github.com/dotnet/maui/pull/20210. BTW the footer didn't update either so I fixed it too :)
