### ISSUE TITLE
Events triggered unexpectedly

### ISSUE THREAD

**Issue by Legends** [dotnet/maui#19378]
### Description

I have attached the eventhandler `AfterContentPageLoaded` to the `Loaded` event of the main contentpage.
`<ContentPage ....  Loaded="AfterContentPageLoaded">`

I have also overriden `OnDisappearing` method.

I am debugging my app on my local android device.

1.)
When I switch to another app, `OnDisappearing` method is called, but it actually shouldn't be triggered:
![image](https://github.com/dotnet/maui/assets/966368/64f7040a-c473-4e6c-8a14-85f39aba117f)

2.) 
When I switch back to my app, the `Loaded` event is triggered again and eventhandler `AfterContentPageLoaded` runs again.
I don't understand the page lifecycle currently. Shouldn't it load only once!?

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

-

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by PureWeen** [comment]
I did a few quick tests and for me `OnDisappearing` isn't called when I switch apps. I'm wondering if your app is getting destroyed when backgrounded. Sometimes Android will destroy an entire app when its backgrounded for memory reasons. This might cause those events to fire again

**Comment by Legends** [comment]
> I did a few quick tests and for me `OnDisappearing` isn't called when I switch apps. I'm wondering if your app is getting destroyed when backgrounded. Sometimes Android will destroy an entire app when its backgrounded for memory reasons. This might cause those events to fire again

I have changed my local code since I posted the issue above.
OnDisappearing is not called again now.

But the `Loaded` event is fired again. But it does not fire on every come back, sometimes.
For this I dont need to create a repo, it's just a fresh .net maui app with the following code:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiAppEventsTriggeredAgain.MainPage" 
             Loaded="ContentPage_Loaded">
```

and in code behind:

```
private async void ContentPage_Loaded(object sender, EventArgs e)
{
	await DisplayAlert("ContentPage_Loaded", "ContentPage_Loaded", "ok");
}

protected override async void OnAppearing()
{
	base.OnAppearing();
	await DisplayAlert("OnAppearing", "OnAppearing", "ok");
}
```

Ok, i figured it out when the `Loaded` event gets triggered again and again:
I have activated gestures (i guess that's how it's called) on my phone, so i dont have the navigation bar at the bottom anymore.

**Procedure**:
Now when the app is loaded the first time, I swipe from the right edge to the left and the app goes into background.
When i swipe from bottom edge upwards and hold, i can see all apps currently running.
I choose another app or just go to the "desktop" of my phone.
Now I switch back to my app again and the loaded event is raised again.

When I repeat the above procedure, the event is raised again and again!

But for example: 
If am using the app and swipe from bottom edge upwards , hold and choose another app and then switch back, the `loaded` event is not raised anymore! 
---

Another question for you:
During debugging, why does the Watch window or Immediate window don't evaluate code anymore?
For example I paste a variable into Immediate window, but it doesn't show anything, same happens when I create a watch entry.

**Comment by andrasjani** [comment]
I experience this issue too. I have two pages. On the second page, every time I open a popup with Application.Current.MainPage.ShowPopupAsync or this.ShowPopupAsync, the second page Loaded event is triggered again. It worked well in the preview version (8.0.0-rc.2.9373). I'm upgrading from preview. I tried on windows and android too.
