### ISSUE TITLE
[Bug] dotnet workload install maui Microsoft.Android.Sdk.BundleTool fail

### ISSUE THREAD

**Issue by mwbinderholz** [dotnet/maui#1937]
### Description
Hello,

i tried to follow the installation guide on https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation

But i am stuck on dotnet workload install maui.
I already tried dotnet workload install maui-android.
Additionally with --verbosity or --include-previews.

But i am still getting only the following error message:
--

Installing pack Microsoft.Android.Sdk version 30.0.100-preview.6.62...
Writing workload pack installation record for Microsoft.Android.Sdk version 30.0.100-preview.6.62...
Installing pack Microsoft.Android.Sdk.BundleTool version 30.0.100-preview.6.62...
Workload installation failed, rolling back installed packs...

Workload installation failed: Downloading microsoft.android.sdk.bundletool version 30.0.100-preview.6.62 failed

--

Everything else works. I already deleted this bundletool from the directory dotnet/sdk-manifests/6.0.100/microsoft.net.sdk.android/WorkloadManifest.json

Then everything runs through smoothly, even the maui-check.

Google tells me nothing other then installing bundletool myself?

I could not find any log files, which indicate this problem.
### Steps to Reproduce

1. Follow Steps here: https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation
2. Open Powershell as administrator
3. dotnet workload install maui

### Expected Behavior
Installing pack Microsoft.Android.Sdk version 30.0.100-preview.6.62...
Writing workload pack installation record for Microsoft.Android.Sdk version 30.0.100-preview.6.62...
### Actual Behavior
Installing pack Microsoft.Android.Sdk.BundleTool version 30.0.100-preview.6.62...
Workload installation failed, rolling back installed packs...

Workload installation failed: Downloading microsoft.android.sdk.bundletool version 30.0.100-preview.6.62 failed
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Windows 10 Pro | Visual Studio 2022 Version 17.0.0 Preview 2.1

### Workaround

I already deleted this bundletool from the directory dotnet/sdk-manifests/6.0.100/microsoft.net.sdk.android/WorkloadManifest.json

Then everything runs through smoothly, even the maui-check.

**Comment by mwbinderholz** [comment]
Updated to Vsual Studio Version 17.0.0 Preview 3.1
Windows Version 10.0.19043 Build 19043
.net 6 preview 7

still the same problem

**Comment by jsuarezruiz** [comment]
@mwbinderholz Use this script https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1 to remove the current workloads (not sure about the status, could have a mix of old versions).

Then, install latest VS 2022 Preview. And finally, install workloads

`dotnet workload install maui `

or

`dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.10.json`

**Comment by mwbinderholz** [comment]
Hello

since that was 3 months ago, I already moved on. 
In the new Visual Studio 2022 Preview .Net Maui can be installed in the visual studio installer and that works fine

thank you though.
