### ISSUE TITLE
Implicit styles declared at different levels do not combine (lowest one wins completely)

### ISSUE THREAD

**Issue by KRA2008** [dotnet/maui#19382]
### Description

When an implicit style is declared at one level, and another implicit style targeting the same type is declared at a lower level, only the lower level style ends up applied to the element. To be clear, I'm NOT describing subtypes that need "ApplyToDerivedTypes" or styles that use "BasedOn".

For example: if you declare an implicit style for labels at the page level, and declare another implicit style for labels at a child layout level, you will find that only the property setters from the layout level style gets applied to a label inside that layout. 

The documentation does not explicitly say what should happen in this case, but the "cascading" behavior for all other types of styling seems like it should apply here as well. This used to work in Forms, as I discovered the bug once I upgraded to MAUI and a bunch of my labels turned ugly. I checked and this happens for Rectangles too, so I assume it happens for all elements.

![Screenshot_20231212-204712](https://github.com/dotnet/maui/assets/5667342/b284c0b1-a96b-461b-80e3-1f0bddbae7de)
![vs](https://github.com/dotnet/maui/assets/5667342/ed3a7280-4bdd-44db-b6ec-361d5e7d124f)

### Steps to Reproduce

1. Make an implicit style at the page level that targets labels and modify just one property with the style
2. Make a child layout on the page
3. Make an implicit style that targets labels at that child layout level that modifies a different property than in step 1
4. Make a label in the child layout
5. Run the app

Expected behavior:
Both property setters from both styles should be applied to the label

Actual behavior:
Only the property setter from the child layout level style is applied to the label

### Link to public reproduction project repository

https://github.com/KRA2008/MAUIImplicitStyleCascading

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

I'm testing on Android 12 but I see no reason it would be specific to this version.

**Comment by PureWeen** [comment]
@StephaneDelcroix thoughts?

**Comment by StephaneDelcroix** [comment]
we do not support this at the moment. a single implicit style per control is applied at one time. you should use BasedOn

**Comment by KRA2008** [comment]
@StephaneDelcroix ok, thanks for the quick response. 

one question though just to make sure i'm doing things as efficiently as possible - i understand if this is no longer supported, but i'm not clear what you mean when you say BasedOn should be used. i understand how i *could* use BasedOn if i used just explicit styles, but it appears (from experimentation) that the styling from an implicit style just cascades down into an explicit style applied to the same element, no BasedOn required. there isn't any way for an implicit style to be referred to by BasedOn, is there?

**Comment by KRA2008** [comment]
ok i found a funny workaround to keep things nice and DRY.

at the App level i declared a style that i intend to use throughout the app, what would have been an implicit style, but instead make it explicit, let's call it _baseLabelStyle. then, also at the App level, make another style, make it implicit, but apparently implicit styles can use BasedOn, so make it based on _baseLabelStyle and make it empty, which will then effectively make the setters in _baseLabelStyle implicit. then at the page level, i can make _another_ implicit style, and make it BasedOn _baseLabelStyle, but i can also add any additional setters i want there. oofta.
