### ISSUE TITLE
In Android, adding views in SizeChanged event does not show the newly added views

### ISSUE THREAD

**Issue by last-Programmer** [dotnet/maui#19391]
### Description

In Android, adding views in SizeChanged event does not show the newly added views

### Steps to Reproduce

1. Create a new .Net Maui Project
2. Delete the MainPage.xaml and MainPage.Xaml.cs
3. Add a new class named MainPage and replace it content with

```C#
public class MainPage : ContentPage
{    
    private bool initiated;
    private VerticalStackLayout layout;

    public MainPage()
    {
        this.SizeChanged += OnSizeChanged;
        this.layout = new VerticalStackLayout();
        this.layout.VerticalOptions = LayoutOptions.Center;
        this.Content = this.layout;
    }

    private void OnSizeChanged(object? sender, EventArgs e)
    {
        if (!this.initiated)
        {
            this.initiated = true;
            Label label = new Label { FontSize  = 20, HorizontalOptions = LayoutOptions.Center, Text = ".NET MAUI ROCKS" };
            this.layout.Children.Add(label);
        }
    }
}
```
Run the project in Android simulator and you can see that the newly added label is not shown. But when you run the same in iOS simulator it is shown. I need to add the views in SizeChanged because i need to know size of the parent containers size to to create new child views based on parent container size.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by last-Programmer** [comment]
Here is the project that is happening the bug
[MauiApp1.zip](https://github.com/dotnet/maui/files/13665316/MauiApp1.zip)

**Comment by PureWeen** [comment]
Can you test with the latest nightly?
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by last-Programmer** [comment]
@PureWeen 

It seems to be that it is working find with nightly build. 

I have this sample code
`namespace MauiApp1;

public class MainPage : ContentPage
{
    private bool initiated;
    private VerticalStackLayout layout;

    public MainPage()
    {

        this.SizeChanged += OnSizeChanged;
    }

    private void OnSizeChanged(object? sender, EventArgs e)
    {
        if (!this.initiated)
        {
            this.initiated = true;
            this.CreateControls();
        }
    }

    private void CreateControls()
    {
        this.layout = new VerticalStackLayout();
        this.layout.VerticalOptions = LayoutOptions.Fill;
        this.layout.HorizontalOptions = LayoutOptions.Fill;
        this.layout.BackgroundColor = Colors.Brown;
        Label label = new Label
        {
            FontSize = 20,
            HorizontalOptions = LayoutOptions.Center,
            VerticalOptions = LayoutOptions.Center,
            VerticalTextAlignment = TextAlignment.Center,
            HorizontalTextAlignment = TextAlignment.Center,
            Text = ".NET MAUI ROCKS",
            BackgroundColor = Colors.Black,
            TextColor = Colors.White
        };

        this.layout.Children.Add(label);

        this.Content = this.layout;
    }

}`

The label is not centering vertically. Is there something i am doing wrong. This is happening with both stable and nightly build.

**Comment by PureWeen** [comment]
@last-Programmer can you create a new issue? Does it center if you create it at startup vs inside SizeChanged?

Once this is resolved it might fix your second issue
https://github.com/dotnet/maui/issues/19432

**Comment by last-Programmer** [comment]
Hi,

The problem is not only adding new controls.  I have a button IsVisble = false in already created control in the constructor. on size changed if i change IsVisible to true the button is not becoming visibile. this works find in iOS. it is not working in android. There seems to be some issue in updating the screen when adding new controls or modifying the properties of existing controls does not work with Android.
