### ISSUE TITLE
.NET Maui is showing 80 errors

### ISSUE THREAD

**Issue by wdharperok** [dotnet/maui#19404]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://github.com/dotnet/maui/assets/145135547/390e60ff-da4a-4c6b-b2d9-84cbd9f22ec2)

Windows 10, with fresh install of VS 2022.

**Comment by mattleibow** [comment]
It appears you do not have the https://api.nuget.org/v3/index.json nuget source defined in VS. Did you change anything since instaling VS?

MAUI depends on several nugets from nuget.org, so when building that source needs to be enabled in VS.
