### ISSUE TITLE
clang++ exited with code 1, error : ld: building for iOS Simulator, but linking in dylib built for iOS

### ISSUE THREAD

**Issue by MikePendo** [dotnet/maui#19406]
### Description

There are a lot of issues about that topic I went over all/most of them but didnt find a solution.
I am using the Calculator app with modification to .net7.  [https://github.com/MikePendo/CalculatorMaui](repo )
Basically the build is failing with the following:
```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/targets/Xamarin.Shared.Sdk.targets(1276,3): error : clang++ exited with code 1: [/Users/mr/Desktop/Calculator/src/Calculator/Calculator.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/targets/Xamarin.Shared.Sdk.targets(1276,3): error : ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/mr/Desktop/Calculator/src/Calculator/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/Pendo.framework/Pendo' [/Users/mrt/Desktop/Calculator/src/Calculator/Calculator.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/targets/Xamarin.Shared.Sdk.targets(1276,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/mr/Desktop/Calculator/src/Calculator/Calculator.csproj::TargetFramework=net7.0-ios]
```
When running `dotnet build Calculator -r iossimulator-arm64` (Running on M1, Xcode 14.3, maui-ios                   7.0.101/7.0.100       SDK 7.0.300)
The pendo sdk is a nugget package that is wrapping XCFramewrok. The native framework is build for both device and simultaor(I excluded all the non relevant stuff). I am not sure why it tries to link the wrong architecture when building for simulators. 
I have tried some different configurations BUT my knowledge in .net/xamarin/maui is limited. The same framework is used on native/ react / flutter .
Please help or suggest what else can be tried.

### Steps to Reproduce

1. Take the following sample project https://github.com/MikePendo/CalculatorMaui
2. try to build for simulator `dotnet build Calculator -r iossimulator-arm64`

### Link to public reproduction project repository

https://github.com/MikePendo/CalculatorMaui

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No 

### Relevant log output

```shell
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/targets/Xamarin.Shared.Sdk.targets(1276,3): error : clang++ exited with code 1: [/Users/mr/Desktop/Calculator/src/Calculator/Calculator.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/targets/Xamarin.Shared.Sdk.targets(1276,3): error : ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/mr/Desktop/Calculator/src/Calculator/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/Pendo.framework/Pendo' [/Users/mrt/Desktop/Calculator/src/Calculator/Calculator.csproj::TargetFramework=net7.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125/targets/Xamarin.Shared.Sdk.targets(1276,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/mr/Desktop/Calculator/src/Calculator/Calculator.csproj::TargetFramework=net7.0-ios]
```
```

**Comment by borrmann** [comment]
Have you tried changing your RunTimeIdentifier in your csproj file to `iossimulator-arm64`, instead `ios-arm64`?

e.g. like this
```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
     <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
</PropertyGroup>
```

**Comment by borrmann** [comment]
maybe this could be mentioned in the [docs](https://learn.microsoft.com/en-us/dotnet/maui/ios/remote-simulator?view=net-maui-8.0)?

**Comment by MikePendo** [comment]
@borrmann 
Yes, I have attached the project with some options that I tried

**Comment by borrmann** [comment]
@MikePendo Have you also tried using this?

``` <MtouchLink>SdkOnly</MtouchLink> ```

maybe, depending on your xcode, also 

``` <MtouchExtraArgs>--weak-framework=NewsstandKit</MtouchExtraArgs> ```

I am just comparing it to my solution, because I also have an M1 machine and very often run into this issue - but currently it works with .net 7.0 in my project

**Comment by MikePendo** [comment]
@borrmann 
No that didnt help can u share docs for those flags? I am not sure how they related to the error I had.
Maybe u have an option to integrate that framework and see if u can build?
https://www.nuget.org/packages/pendo-maui

**Comment by borrmann** [comment]
Before changing and rebuilding this, did you close your solution and rebuilt your project?
I would think this is might be necessary to ensure a change of this property. 
It was just an idea because your second error line indicates there is an issue with the linker, so if you change linking to SdkOnly, Ithought it might work:

`ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/mr/Desktop/Calculator/src/Calculator/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/Pendo.framework/Pendo`

Here are the docs for ios about linking. https://learn.microsoft.com/en-us/dotnet/maui/ios/linking?view=net-maui-8.0&tabs=vs 
I will try if my project builds when I include your project

**Comment by borrmann** [comment]
@MikePendo Yes, as soon as I add this nuget to my project it does not build anymore. 
Also adding `-linkskip=Pendo` did not change anything. 
I get a similar error:

```
Error: clang++ exited with code 1:
ld: warning: ignoring duplicate libraries: '-lSystem.IO.Compression.Native', '-lSystem.Native', '-lSystem.Net.Security.Native', '-lSystem.Security.Cryptography.Native.Apple', '-lmono-component-debugger', '-lmono-component-diagnostics_tracing', '-lmono-component-hot_reload', '-lmonosgen-2.0', '-lxamarin-dotnet-debug'
ld: building for 'iOS-simulator', but linking in dylib ([...]/obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/Pendo.framework/Pendo) built for 'iOS'
clang: error: linker command failed with exit code 1 (use -v to see invocation) 
```

**Comment by MikePendo** [comment]
That strange the framework has the proper arch for device and simulators....

**Comment by MikePendo** [comment]
I can build the app via IDE but it fails in command line so I would guess it's not the issue of the Framework. if it hadn't the proper arch it would fail also on the IDE

**Comment by drasticactions** [comment]
A few things:

- This repo is for MAUI UI / MAUI UI Tooling issues. This will be related to [xamarin/xamarin-macios](https://github.com/xamarin/xamarin-macios) tooling. 
- The underlying framework (https://www.nuget.org/packages/pendo-maui-binding-ios/) isn't an xcframework, it's a framework with a library.

```
/Users/drasticactions/Documents/Pendo/Pendo: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
/Users/drasticactions/Documents/Pendo/Pendo (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/Users/drasticactions/Documents/Pendo/Pendo (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

And it doesn't seem to support the iOS Simulator. I think they built the x86_64 for simulator, and arm64 for device. Since you're deploying to the arm64 simulator from CLI (and the IDE is deploying the x64 version) that's most likely why it's failing.

I don't think this is a bug in MAUI nor the Xamarin iOS tooling. I think Pendo needs an Arm64 Simulator build. @rolfbjarne Does this sound right?

**Comment by rolfbjarne** [comment]
> The pendo sdk is a nugget package that is wrapping XCFramewrok

No, the `pendo-maui-binding-ios` NuGet contains a .framework, not an .xcframework.

> I don't think this is a bug in MAUI nor the Xamarin iOS tooling. I think Pendo needs an Arm64 Simulator build. @rolfbjarne Does this sound right?

Yes, that's correct. The `pendo-maui-binding-ios` NuGet needs to ship an .xcframework with separate .frameworks for device and simulator.

**Comment by MikePendo** [comment]
I am sorry I was sure the Pendo on Maui is released as XCframeworks, as that how we release it to all our frameworks 
Few questions:
1. how do you able to see it was a .framework  by downloading the bindings I see the .dll, how do u see the actual native artifact from there?
(I can see it in the linker-cache under the app, but the arch are stripped correctly there)
2. If we can run the app in the visiual studio I would guess the IDE knows how to slice an select the right arch can we also apply a configuration to the .csproj so the command line will pick the correct arch?

**Comment by rolfbjarne** [comment]
1. We don't support bundling an .xcframework in the assembly (.dll), it's always shipped separately (next to the assembly, either in a separate .resources directory, or in a zip file), so it can't be inside the assembly as a resource.
2. I also inspected the resources in the assembly just in case, and it's a .framework:

```
$ monodis --presources lib/net7.0-ios16.1/PendoBindingiOS.dll
       0: Pendo.framework (size 5175112)
```

**Comment by MikePendo** [comment]
@rolfbjarne 
1. if I download the buinding sdk : [pendo-maui-binding](https://www.nuget.org/packages/pendo-maui-binding-ios/)
I dont see the native artifact there, so are you prefetching it later? (coz PendoBindingiOS.dll  is a few MB, I would assume the framework is embedded inside the .dll)

If I look at how the app is structured it seems that the slicing is done correctly and we manage to run it via VS so is there any work around to also build it in the same way in command line? 
<img width="1516" alt="Screenshot 2023-12-14 at 12 57 15" src="https://github.com/dotnet/maui/assets/56674958/d72c215d-e234-4bb6-98c9-5f5194639b9e">

Sorry for maybe trivial questions but my knowledge related to Maui/Xamarin is limited.

**Comment by rolfbjarne** [comment]
> 1. coz PendoBindingiOS.dll  is a few MB, I would assume the framework is embedded inside the .dll

Correct.

> is there any work around to also build it in the same way in command line?

Yes, you can set the runtime identifier to x64:

> dotnet build ... /p:RuntimeIdentifier=iossimulator-x64

I believe that should work.

**Comment by albyrock87** [comment]
To summarize:

Pendo ships with embedded `.framework` which works only in x64 version of iOS Simulator.

Via terminal it is possible to compile x64 simulator version on Apple Silicon processor but that doesn't solve problem with IDE and debugging.

VisualStudio for Mac (which is going to be EOL soon) is the only IDE supporting: 

```
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0-ios|AnyCPU'">
    <ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>
</PropertyGroup>
```

Therefore in order to support development and debugging on simulator in Apple Silicon processors, the only way is to ship `.xcframework`.

Am I correct?

**Comment by rolfbjarne** [comment]
> Therefore in order to support development and debugging on simulator in Apple Silicon processors, the only way is to ship `.xcframework`.
> 
> Am I correct?

Correct.
