### ISSUE TITLE
Button not rendered correctly

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#1941]
### Description
I was created the custom control to show a list button on horizontal order as much as button rendered on the available space based on its text. The button text values are a text from "A" , "AAAA", "AAAAAAAA" and so on and its padding and margin is 0.

I was measure the each children with available width and available height. In Layout children method, i was arrange the button based on its desired width. but the desired width return 88 for the button holds "A" text and "AAAA" text so that "A" text button shows more white space around the text.

Can you provide suggestion to resolve the issue, if it cannot be resolve, log this is an issue 

### Steps to Reproduce

1. Crate the custom layout with list of button and assign the button text as minimal characters(A, B, AA etc.,)
2. Measure the children with available width and height
3. Layout the buttons based on its desired width and height.
4. Button shown the text "A" with around more space(-------A------)

### Expected Behavior

- Button rendered on width only have text

### Actual Behavior

- Button rendered on text with around more space.

<img src="https://user-images.githubusercontent.com/44917578/128670982-5827484d-fde0-4aba-a962-f9a7cebcce70.png" width="300" />

**Comment by mattleibow** [comment]
Something has changed, and now the button has absolutely no padding:

![image](https://user-images.githubusercontent.com/1096616/130351401-66dbd031-a0e0-45e5-a74e-588254718367.png)


If I add a padding of 20 all round, it doesn't actually work properly for some reason:

![image](https://user-images.githubusercontent.com/1096616/130351437-b2c46a0c-9459-4f78-b2f0-9647ca8b87e5.png)

Looks like something is not telling the button to re-layout the text...

**Comment by Sasikumar3595** [comment]
@mattleibow,

I was mentioned the issue here for space around the **Play** button when its padding and value value is 0.
![image](https://user-images.githubusercontent.com/44917578/130390883-8edd4d17-ccc1-49b5-9835-00a1bcf7d8c8.png)

**Comment by shimingsg** [comment]
verified not repro with VS 17.2.0 Preview 3.0 [32308.378.main] on Android 12:
![image](https://user-images.githubusercontent.com/20982341/157375285-6bcf916e-1ffc-4df8-b325-797f30326c91.png)
demo: 
[1941.zip](https://github.com/dotnet/maui/files/8211768/1941.zip)
