### ISSUE TITLE
setting AreBrowserAcceleratorKeysEnabled does not have effect

### ISSUE THREAD

**Issue by paulvanbladel** [dotnet/maui#19419]
### Description

I want to disable F5 based refresh in an maui hybrid blazor app by means of setting AreBrowserAcceleratorKeysEnabled = false.
That doesn't seem to work.
The strange this is that setting other settings like IsZoomControlEnabled  does work.

### Steps to Reproduce

Start in visual studio a standard maui hybrid blazor app.
We need to and event handler to blazor webview and set the setting in the event handler.

Add BlazorWebViewInitialized event handler in Mainpage.xaml:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiApp1"
             x:Class="MauiApp1.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">

    <BlazorWebView x:Name="blazorWebView" HostPage="wwwroot/index.html" BlazorWebViewInitialized="blazorWebView_BlazorWebViewInitialized">
        <BlazorWebView.RootComponents >
            <RootComponent Selector="#app" ComponentType="{x:Type local:Routes}" />
        </BlazorWebView.RootComponents>
    </BlazorWebView>

</ContentPage>
```

```
        private void blazorWebView_BlazorWebViewInitialized(object sender, Microsoft.AspNetCore.Components.WebView.BlazorWebViewInitializedEventArgs e)
        {
#if WINDOWS
            e.WebView.CoreWebView2.Settings.IsZoomControlEnabled = false; // THIS WORKS
            e.WebView.CoreWebView2.Settings.AreBrowserAcceleratorKeysEnabled = false; // THIS DOES NOT WORK
#endif
        }
```

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

maui-windows       8.0.3/8.0.100    VS 17.8.34322.80

**Comment by jfversluis** [comment]
Setting through a custom mapper also doesn't have any effect:

```csharp
BlazorWebViewHandler.BlazorWebViewMapper.AppendToMapping("NoAccelerators", async (handler, view) =>
{
    await handler.PlatformView.EnsureCoreWebView2Async();
    if (handler.PlatformView.CoreWebView2 is not null)
    {
        handler.PlatformView.CoreWebView2.Settings.AreBrowserAcceleratorKeysEnabled = false;
    }
});
```

**Comment by Eilon** [comment]
The same API doesn't seem to work in a plain WinUI app with WebView2 either.

**Comment by Eilon** [comment]
Works in WPF WebView2.

**Comment by Eilon** [comment]
I filed https://github.com/MicrosoftEdge/WebView2Feedback/issues/4241 because this appears to be an issue with WebView2 itself and not in .NET MAUI or BlazorWebView. Please add any additional comments/votes/details to that issue.
