### ISSUE TITLE
xml files under Android\Resources\xml are *not* packaged in the resulting apk under res\xml

### ISSUE THREAD

**Issue by Giustiniano** [dotnet/maui#19417]
### Description

I need to allow cleartext http traffic in order to call my rest service from my android (.net maui) app.
To do that, I am following the indications provided here https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/local-web-services?view=net-maui-8.0#android-network-security-configuration ,specifically  creating `network_security_config.xml`, putting it under Platforms\Android\Resources\xml and referencing it in `AndroidManifest.xml`. Once I do that, the application does not build because `network_security_config.xml` cannot be found.
If I just add the xml file without referencing it, I can see that indeed the file is missing from the resulting apk

![Screenshot 2023-12-14 154321](https://github.com/dotnet/maui/assets/17346129/eccc43bb-7354-4c40-8ef4-26cd6252e6c9)
![Screenshot 2023-12-14 154625](https://github.com/dotnet/maui/assets/17346129/63338c27-c831-41b6-9aea-1b1f8c494f6c)

### Steps to Reproduce

1) Create a new .NET MAUI App in visual studio, based on .NET 8
2) Follow the steps provided here https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/local-web-services?view=net-maui-8.0#android-network-security-configuration
3) Try to build the application

Expected behaviour: the app is built successfully

Actual Behaviour

the following build error appears

Severity	Code	Description	Project	File	Line	Suppression State
Error		APT2067: failed processing manifest.		 	0	
Error		APT2260: resource xml/network_security_config (aka com.companyname.recycler.app:xml/network_security_config) not found.

This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.		 	0	

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jfversluis** [comment]
If you right-click the `network_security_config.xml` file > Properties and inspect the Build Action, what does that say? Is there anything in your csproj file regarding this file?
