### ISSUE TITLE
When I try to set text from code the textColor do not applied for Entry on iOS

### ISSUE THREAD

**Issue by denhaandrei** [dotnet/maui#19424]
### Description

When I press on the button the text colour do not applied on iOS:

https://github.com/dotnet/maui/assets/13841559/3684bcd2-25c4-427e-8337-ebbda74ef494

### Steps to Reproduce

See description
![exampleCode](https://github.com/dotnet/maui/assets/13841559/cee08070-eb5b-4954-b88e-f612343f01bd)

### Link to public reproduction project repository

https://github.com/denhaandrei/maui8_ios_entry_textColor_buttonPress

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

iOS

**Comment by denhaandrei** [comment]
Any temporary solution or idea on how to fix it? (can`t go LIVE with custom controls and .NET 8) 
What is the planned release date with this fix?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(**8.0.3**). Repro on iOS 17.0 and MacCatalyst, not repro on Windows 11 and Android 14.0-API34 with below Project:
[maui8_ios_entry_textColor_buttonPress.zip](https://github.com/dotnet/maui/files/13946209/maui8_ios_entry_textColor_buttonPress.zip)

This issue does not repro on **7.0.101**.

**Comment by denhaandrei** [comment]
> Verified this on Visual Studio Enterprise 17.9.0 Preview 2(**8.0.3**). Repro on iOS 17.0 and MacCatalyst, not repro on Windows 11 and Android 14.0-API34 with below Project: [maui8_ios_entry_textColor_buttonPress.zip](https://github.com/dotnet/maui/files/13946209/maui8_ios_entry_textColor_buttonPress.zip)
> 
> This issue does not repro on **7.0.101**.

Hi @XamlTest I downloaded the attached repository and run on windows 11 - Microsoft Visual Studio Enterprise 2022 (64-bit) - 
Version 17.8.2. 
The issue is still reproduced on iOS.
Please note, that the issue is only for iOS. 


Android works fine for me!

**Comment by XamlTest** [comment]
@denhaandrei Thanks for the comment, same result with you.
I verified the issue on all platforms according to your description and added other additional information (1. Added reproducible platform: MacCatalyst. 2. The issue works fine on 7.0.101 version for all platforms.)
