### ISSUE TITLE
when i change the XAML UI it doesn't  update automatically. I need to restart the app to update the UI :(

### ISSUE THREAD

**Issue by 1oneman1** [dotnet/maui#19445]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by PureWeen** [comment]
@1oneman1 can you do a screen recording so we can see what you're changing?
