### ISSUE TITLE
problem as i change the first thing 

### ISSUE THREAD

**Issue by CherryPatel** [dotnet/maui#19455]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

global::Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml(this, typeof(MainPage));

**Comment by jfversluis** [comment]
Is there any reason that you're trying to load something from XAML this way? If you just want to show a page that should not be needed. Could you add some more information about what you're trying to do exactly and more details about the error you see?
