### ISSUE TITLE
[Bug] VisualDiagnostics.VisualTreeChanged does not return all Add/Remove events for elements.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#1946]
### Description

When adding or removing elements in a given application, we attach to `VisualDiagnostics.VisualTreeChanged`. This functionality has regressed so now we are not getting all events for when elements are added and created.

### Steps to Reproduce

1.  Create a new MAUI application.
2.  In App.cs, attach to `VisualDiagnostics.VisualTreeChanged`.
3.  In the MainPage.cs, add a button to add or remove new elements on the screen.

### Expected Behavior

Add/Remove events would be supplied when any new element is passed in or removed.
### Actual Behavior

These events now appear to only happen when an application is created. After it has loaded, new events are not fired.

https://user-images.githubusercontent.com/898335/128249938-eef68a32-d920-4ba0-a195-9b7bb83b175e.mp4

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment]
Fixed in main with https://github.com/dotnet/maui/pull/1948
Cherry picked to p7 with https://github.com/dotnet/maui/pull/1954
