### ISSUE TITLE
Views are not vertically centre when layout vertical layout option is set to centre

### ISSUE THREAD

**Issue by last-Programmer** [dotnet/maui#19464]
### Description

View are not vertically center when layout vertical layout option is set to center

You can reproduce the problem with the attached code.

[MauiApp1.zip](https://github.com/dotnet/maui/files/13695426/MauiApp1.zip)

### Steps to Reproduce

Run the attached project and you can see that the label is not vertically centred. 

[MauiApp1.zip](https://github.com/dotnet/maui/files/13695426/MauiApp1.zip)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by Redth** [comment]
```
 private void CreateControls()
    {
        this.layout = new VerticalStackLayout();
        this.layout.VerticalOptions = LayoutOptions.Fill;
        this.layout.HorizontalOptions = LayoutOptions.Fill;
        this.layout.BackgroundColor = Colors.Brown;
        Label label = new Label
        {
            FontSize = 20,
            HorizontalOptions = LayoutOptions.Center,
            VerticalOptions = LayoutOptions.Center,
            VerticalTextAlignment = TextAlignment.Center,
            HorizontalTextAlignment = TextAlignment.Center,
            Text = ".NET MAUI ROCKS",
            BackgroundColor = Colors.Black,
            TextColor = Colors.White
        };

        this.layout.Children.Add(label);

        this.Content = this.layout;
    }
```
From the repro
