### ISSUE TITLE
[iOS] ScrollView height not changing after items are hidden

### ISSUE THREAD

**Issue by kklose23** [dotnet/maui#19479]
### Description

After rendering a page, hiding items within a ScrollView will not change the height of it.

### Steps to Reproduce

See attached repo

### Link to public reproduction project repository

https://github.com/kklose23/maui-scrollview-ios

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
Duplicate of #18207
