### ISSUE TITLE
[Android] The measure and arrange methods are not being called in custom layout with ContentView

### ISSUE THREAD

**Issue by RasikaPalanisamy** [dotnet/maui#19471]
### Description

I possess two ContentViews. The first ContentView contains a custom data grid, while the second one only has a label. 
Within the ContentPage, I have a ContentView that loads the content of another ContentView. Problems occur when I switch pages using the Swap button and scroll the application horizontally. 
During scrolling, I’ve invoked the InvalidateMeasure, but the Measure and Arrange methods aren’t being triggered as expected.
This issue prevents the layout from updating, hindering me from achieving the necessary changes during scrolling.

### Steps to Reproduce

1. Run the attached sample.
2. Click swap button
3. Again click swap buttton.
4. Scroll the app horizontally.

https://github.com/dotnet/maui/assets/92015119/1998d55a-3305-4e30-952a-bb265da7f233

### Link to public reproduction project repository

https://github.com/RasikaPalanisamy/TestSample

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

**Comment by PureWeen** [comment]
@RasikaPalanisamy you most likely want `MEasureOverride` and `ArrangeOverride` 

https://github.com/dotnet/maui/blob/main/docs/design/layout.md

**Comment by RasikaPalanisamy** [comment]
Hi @PureWeen,
I've created a CustomGrid that inherits from CustomLayout, which, in turn, derives from Layout. During the initial loading, the Layout measures its children, triggering ArrangeChildren(). I've verified the functionality of MeasureOverride() and ArrangeOverride(), and they are appropriately triggered during the initial loading and scrolling of the CustomGrid.

However, when I switch pages and scroll the CustomGrid again, MeasureOverride and ArrangeOverride are no longer triggered.

**Comment by PureWeen** [comment]
I don't think those will get called while you scroll. The scrollview and the internal content have already measured so there's no reason for them to measure or arrange again. The platform will just scroll the content into view as you scroll.

**Comment by RasikaPalanisamy** [comment]
@PureWeen ,
In my scenario, I needed to arrange the children or execute specific actions during scrolling, prompting me to use InvalidateMeasure.  Upon returning to my custom control page, the MeasureChildren() and ArrangeChilldren() methods should be triggered to measure and arrange the children during scrolling. This will allow me to perform some actions during scrolling.

**Comment by PureWeen** [comment]
@RasikaPalanisamy I think you'll need to use Scrolled events to perform modifications
It would be super inefficient for us to remeasure/arrange while scrolling
