### ISSUE TITLE
NET Maui app with none shell navigation bug

### ISSUE THREAD

**Issue by atexinspect** [dotnet/maui#19480]
The below works fine in NET 7.0 but when using NET 8.0 the hamburger menu does not behave correctly.
https://github.com/atexinspect/MauiAppWithoutShell

### Configuration
* Which version of .NET is the code running on?
* NET7.0
* Windows 11 Pro - 22631.2861
* What is the architecture (x64, x86, ARM, ARM64)?
* AnyCPU - Debug
* Do you know whether it is specific to that configuration?
* Yes - NET8.0 Target Runtime

### Regression?
* Did this work in a previous build or release of .NET, or from .NET Framework? If you can try a previous release or build to find out, that can help us narrow down the problem. If you don't know, that's OK.
* Yes - Fine when targeting NET7.0

**Comment by atexinspect** [comment]
Tabbed Pages also do not work on either NET7 or NET8 using none shell navigation. This was my original requirement as I have a Xamarin Forms app that heavily uses tabbed pages that I am trying to convert to NET Maui. Thanks Paul.

**Comment by ninachen03** [comment]
I used your repo, and the behavior is consistent on NET7 (VS17.11.0 SDK7.0.101) and the latest NET 8 (17.12.0 Preview 1.0 8.0.80) According to your description, .NET7 is working, so your problem does not reproduce on NET8.
