### ISSUE TITLE
.NET MAUI project using the PDF.js library - Issue loading the PDF from iOS resource

### ISSUE THREAD

**Issue by Auto72** [dotnet/maui#19486]
### Description

The App load an html page from resource, passing a PDF file from resource. 
It works fine on Windows and Android, but on iOS has a problem loading the PDF file from the resource as a parameter of the html file. It should work, but it doesn't. I think it is a BUG.

```csharp
    private void LoadPdfViewer()
    {
        var pdfFilePath = "";

#if WINDOWS
        pdfFilePath = $"pdfjs/web/viewer.html?file=/simple.pdf";

#elif ANDROID
        pdfFilePath = $"file:///android_asset/pdfjs/web/viewer.html?file=file:///android_asset/simple.pdf";

#elif MACCATALYST || IOS
        pdfFilePath = NSBundle.MainBundle.PathForResource("pdfjs/web/viewer", "html");
        var pdf = NSBundle.MainBundle.PathForResource("simple", "pdf");
        
        // NOTE: Doesn't load the PDF from the resoureces (but it should !?!)
        //pdfFilePath = "file://" + pdfFilePath + "?file=file://" + pdf;

        // WORKAROUND: Don't use the PDF.js Library, and the PDF Toolbar is missing! 
        pdfFilePath = pdf;
#endif

        // Windows | URL --> pdfjs/web/viewer.html?file=/simple.pdf
        // Android | URL --> file:///android_asset/pdfjs/web/viewer.html?file=file:///android_asset/simple.pdf
        // iOS     | URL --> file:///private/var/containers/Bundle/Application/DD66FB74-E286-4EC3-9594-9B78DDEA3A65/MauiPDFjsTest.app/pdfjs/web/viewer.html?file=file:///private/var/containers/Bundle/Application/DD66FB74-E286-4EC3-9594-9B78DDEA3A65/MauiPDFjsTest.app/simple.pdf
        Debug.WriteLine($"URL --> {pdfFilePath}");

        // NOTE: "MauiProgram.cs" contains --> Microsoft.Maui.Handlers.WebViewHandler.Mapper
        webView.Source = new UrlWebViewSource { Url = pdfFilePath };
    }
```
### Steps to Reproduce

Use the linked repo and try it on iOS.

### Link to public reproduction project repository

https://github.com/Auto72/MauiPDFjsTest

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

Not to load the PDF file from resource as parameter of the HTML page.

### Relevant log output

```shell
Windows | URL --> pdfjs/web/viewer.html?file=/simple.pdf
Android | URL --> file:///android_asset/pdfjs/web/viewer.html?file=file:///android_asset/simple.pdf
iOS     | URL --> file:///private/var/containers/Bundle/Application/DD66FB74-E286-4EC3-9594-9B78DDEA3A65/MauiPDFjsTest.app/pdfjs/web/viewer.html?file=file:///private/var/containers/Bundle/Application/DD66FB74-E286-4EC3-9594-9B78DDEA3A65/MauiPDFjsTest.app/simple.pdf
```

**Comment by jfversluis** [comment]
Try removing [this section](https://github.com/Auto72/MauiPDFjsTest/blob/master/MauiPDFjsTest/MauiPDFjsTest.csproj#L59-L61) from your csproj and see if it works then.

**Comment by Auto72** [comment]
I just tried to remove the section you pointed out, but it still doesn't work.

**Comment by wiljoetradify** [comment]
@Auto72 despite missing feature could your pdf be interacted(zoom, touch, scroll)?

I am asking cause this issue is a major blocker for me https://github.com/dotnet/maui/issues/18716

**Comment by Auto72** [comment]
In iOS, using the PDF.js library, the PDF file from resource it is not loaded and I think it is a BUG.
In iOS, If you load the PDF file from resource directly, it shows only the first page, but if you use the 

Microsoft.Maui.Handlers.WebViewHandler.Mapper

as I did in the linked repo, you can zoom and scroll the PDF.

**Comment by PureWeen** [comment]
Do you see the same issue inside an iOS platform app?

`dotnet new iOS` ?

This doesn't seem related to the xplat sdk.

**Comment by drasticactions** [comment]
@Auto72 This is not a MAUI bug. You need to allow the WKWebView to have file access from file URLs, which is what you're giving it here. You would have the same issue with a .NET iOS app (or a straight iOS app) without MAUI unless you do this.

In your handler code,

```sharp
#elif MACCATALYST || IOS
            if (handler.PlatformView is WebKit.WKWebView wkWebView) 
            { 
                wkWebView.Configuration.Preferences.SetValueForKey(Foundation.NSObject.FromObject(true), (Foundation.NSString)"allowFileAccessFromFileURLs");
            }
#endif
```

<img width="1760" alt="スクリーンショット 2023-12-20 10 48 49" src="https://github.com/dotnet/maui/assets/898335/4764ff44-26b5-4fe5-b8a7-212bf329d31e">

Then it should work fine.

**Comment by Auto72** [comment]
@drasticactions Yes, now it work, thank you.

**Comment by vishalpr-hs** [comment]
I am currently attempting to integrate the PDF.js library into an Android project, but I am encountering some difficulties. I would appreciate any help, and I am contacting you, @Auto72, in the hopes that you can provide guidance or assist in troubleshooting the issues.
Thank you in advance for any support you can offer to ensure the successful integration of this library.
