### ISSUE TITLE
Button with image does not autosize on iOS when text is changed.

### ISSUE THREAD

**Issue by KayBeeJayBee** [dotnet/maui#19495]
### Description

In my app I have a button with both text and image. The button is supposed to change text depending on what type of item I have selected in my app. Therefore I have binded the Text property of the Button to a property in my view model. So whenever the text changes the button should show the text and also resize itself to fit all text. This works as expected on Android but for MacOs and iOS the button remains with its initial size.

### Steps to Reproduce

1. Create a new Maui project using visual studio.
2. Modify the button in the default project to also include an image.
`<Grid ColumnDefinitions="Auto">
   <Button
        x:Name="CounterBtn"
        Text="Click me" 
        SemanticProperties.Hint="Counts the number of times you click"
        Clicked="OnCounterClicked"
        ImageSource="test.png"/>
</Grid>`

Note 1: I just created a small test.png file and put it into the Resource/Images folder to have something to display.

Note2: I placed my button inside a grid because I don't want the button to stretch across the entire screen. I only want it to be as big as it needs to.

3. Run the app on MacOS or iOS.
4. Click the button a couple of times. (The text changes but the button does not increase its size as needed)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Did you find any workaround?

No workaround found so far. Right now I'm using the button without an image, but that can not be considered a workaround.

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by Larhei** [comment]
@PureWeen 

After upgrading to .Net8 all my Buttons on iOS containing only an image without any Text result in 0 px height because of no minheigt in the implicit Button Style

See this repro. In the FlyoutHeader and Footer of the shell there should be buttons ;-)

**Comment by KayBeeJayBee** [comment]
@PureWeen Yes it works correctly in the latest nightly build 8.0.6-nightly.9783.

**Comment by PureWeen** [comment]
> @PureWeen
> 
> After upgrading to .Net8 all my Buttons on iOS containing only an image without any Text result in 0 px height because of no minheigt in the implicit Button Style
> 
> See this [repro](https://github.com/Larhei/Maui-Issues/tree/main/ButtonIOS). In the FlyoutHeader and Footer of the shell there should be buttons ;-). But not on iOS :-(

Can you try the nightly? If you are still seeing issues please log a new bug.

**Comment by Larhei** [comment]
@PureWeen 
Tested on nightly. Works on my machine.
