### ISSUE TITLE
Is Microsoft gonna use MAUI ?

### ISSUE THREAD

**Issue by Amine-Smahi** [dotnet/maui#195]
If Microsoft wont use MAUI, then there is no need to use it, It only mean that even its creator doesn't seems to care about it so why my team and i would care.

Microsoft is heavily investing in React Native and thats logical because you can make Mobile (Android/IOS) and Desktop(Windows/Mac) apps.

So to me there is no point of using MAUI.

Am I wrong ? Am I the only one who thinks this way ?

**Comment by chelabitarik** [comment]
You're not alone, Im also not excited about MAUI.
- Xamarin is buggy AF 
- Microsoft wont use it
Why a would anyone use haha

**Comment by Mo-ha-mmed** [comment]
I dont think MS will use it, And im certainly not 😅

**Comment by hartez** [comment]
This is not an issue. If you have legitimate constructive questions about the future of the platform, I suggest starting a topic in [Discussions](https://github.com/dotnet/maui/discussions).
