### ISSUE TITLE
Entry doesn't use the TextColor property when the Text value is bound after some seconds (iOS)

### ISSUE THREAD

**Issue by juniorsaraviao** [dotnet/maui#19509]
### Description

I set a `TextColor` in an Entry control, the value is bound after 1.5 seconds but the `TextColor` changes to the default color.

```xaml
<Entry TextColor="Green"
             FontSize="16"
             PlaceholderColor="LightGray"
             Placeholder="Enter Text"
             Text="{Binding Text}"/>
```

```csharp

protected override async void OnAppearing()
    {
        base.OnAppearing();
        await Task.Delay(1500);

        Text = "Updated text in OnAppearing";
    }

```
| iOS |
| ------------- |
| <video src="https://github.com/dotnet/maui/assets/43689290/c54c47e9-1bb5-480b-af12-66c193005530" width=180 height=392> |

### Steps to Reproduce

1. Clone the project [link](https://github.com/juniorsaraviao/EntrySample/tree/master).
2. Run the project on iPhone simulator or iPhone (iOS 15.2 and above).

### Link to public reproduction project repository

https://github.com/juniorsaraviao/EntrySample/tree/master

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.2 and above

### Did you find any workaround?

No

**Comment by CooperWolfe** [comment]
I found a workaround by appending to the EntryHandler mapping in iOS:
``` csharp
Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("TextColorFix", (handler, view) =>
{
    handler.PlatformView.EditingChanged += delegate
    {
       handler.PlatformView.TextColor = handler.VirtualView.TextColor.ToPlatform();
    };
});
```

**Comment by juniorsaraviao** [comment]
Hi @CooperWolfe, great. That workaround worked for me too!

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(8.0.3 version). This issue repro on iOS 17.0 and MacCatalyst, not repro on Windows 11 and Android 14.0-API34.

Verified on 7.0.101 version, TextColor property works fine on iOS 17.0 and MacCatalyst.
