### ISSUE TITLE
On ios, if IsReadOnly is true, the Editor will not be able to scroll

### ISSUE THREAD

**Issue by singhwong** [dotnet/maui#19500]
### Description

On ios, if `IsReadOnly` is true, the `Editor` will not be able to scroll.

### Steps to Reproduce

1. Run sample
[editor_scroll_issue.zip](https://github.com/dotnet/maui/files/13718048/editor_scroll_issue.zip)
2. Click button, change `IsReadOnly` to false or true and try scrolling the Editor.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 2(**8.0.3 and 7.0.101**). Repro on iOS 17.0 and MacCatalyst.
This issue does not repro on Windows 11 and Android 14.0-API34 with provided project.

**Comment by ejwipp** [comment]
When will this be fixed?  Fix is needed ASAP.
