### ISSUE TITLE
Inaccurate results when getting the user's screen dimensions for macOS

### ISSUE THREAD

**Issue by hunterwendroff** [dotnet/maui#19526]
### Description

So I'm having an issue with retrieving the dimensions of the user's screen when running either a .NET MAUI or .NET MAUI Blazor app. I've tried 'DeviceDisplay.Current.MainDisplayInfo', but the dimensions for the Height and Weight are both inaccurate. I'm running the app in Visual Studio Community for Mac 2022, targeting MacCatalyst on a 2019 16 inch MacBook Pro running the latest macOS Sonoma. The dimensions should be 3072 × 1920. Yet 'DeviceDisplay.Current.MainDisplayInfo' is giving me a Width of 3584 and a Height of 2240. The response to posting about this on StackOverflow was: "I tested on my side, and it will appear the issue that it cannot recognize the screen pixel well. You can report this issue on the GitHub."

### Steps to Reproduce

1. Create .NET MAUI Blazor App
2. Target Mac Catalyst
3. Set variable to DeviceDisplay.Current.MainDisplayInfo in MainPage.cs file's constructor after InitializeComponent(); line.

### Link to public reproduction project repository

https://github.com/hunterwendroff/MacOS_Innacurate_Screen_Dimensions_Bug

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Did you find any workaround?

No

### Relevant log output

```shell
N/A
```

**Comment by hunterwendroff** [comment]
> Hi @hunterwendroff. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

Here is the link to the repository: https://github.com/hunterwendroff/MacOS_Innacurate_Screen_Dimensions_Bug

Here is the file where you can see the bug: https://github.com/hunterwendroff/MacOS_Innacurate_Screen_Dimensions_Bug/blob/main/MacOS%20Innacurate%20Screen%20Dimensions%20Bug/MainPage.xaml.cs

**Comment by jamesmontemagno** [comment]
This is the code that runs: https://github.com/dotnet/maui/blob/main/src/Essentials/src/DeviceDisplay/DeviceDisplay.macos.cs#L32 you could put it directly into your app..


Do you have a monitor plugged in?  According to docs it is the one with input currently: https://developer.apple.com/documentation/appkit/nsscreen/1388371-mainscreen  it returns a frame which is an NSRect and that is what is being returned

**Comment by hunterwendroff** [comment]
> This is the code that runs: https://github.com/dotnet/maui/blob/main/src/Essentials/src/DeviceDisplay/DeviceDisplay.macos.cs#L32 you could put it directly into your app..
> 
> Do you have a monitor plugged in? According to docs it is the one with input currently: https://developer.apple.com/documentation/appkit/nsscreen/1388371-mainscreen it returns a frame which is an NSRect and that is what is being returned

I'm running it on a MacBook laptop, so no external monitor plugged in. If you're suggesting that I run that code in the Platforms/MacCatalyst folder, then I'm not sure how it's supposed to work because NSScreen is not recognized. Isn't NSScreen only available in Cocoa and not Mac Catalyst?

**Comment by jamesmontemagno** [comment]
Whoops, yes good catch :)

What are you getting if you run this code:

```csharp
#if MACCATALYST
        var bounds = UIScreen.MainScreen.Bounds;
        var scale = UIScreen.MainScreen.Scale;
#endif
```

**Comment by hunterwendroff** [comment]
> Whoops, yes good catch :)
> 
> What are you getting if you run this code:
> 
> ```cs
> #if MACCATALYST
>         var bounds = UIScreen.MainScreen.Bounds;
>         var scale = UIScreen.MainScreen.Scale;
> 
>       using var scenes = UIApplication.SharedApplication.ConnectedScenes;
>       var windowScene = scenes.ToArray<UIWindowScene>().FirstOrDefault();
>       var bounds2 = windowScene?.Screen.Bounds;
>       var scale2 = windowScene?.Screen.Bounds;
> #endif
> ```

When I try that, the value of 'scale' is 2 and the other variables still have the incorrect dimensions. (1792 by 1120 when they should be 3072 by 1920).

**Comment by drasticactions** [comment]
@hunterwendroff Where are you getting the numbers you expect it to be?

The commands you're running here with the code @jamesmontemagno pointed to are from macOS through the SDK bindings and are not being influenced by the MAUI UI framework. Unless the bindings themselves are influencing it (which at the moment I doubt, but maybe not impossible) then those would be the same values you would get with a straight Mac Catalyst app using Obj-C or Swift. How are you getting the numbers you expect to get, and is it from Obj-C or Swift?

**Comment by rolfbjarne** [comment]
This seems to work fine for me with the test app.

Maybe try printing out the relevant properties for the screen(s) like this?

```cs
foreach (UIScreen screen in UIScreen.Screens) {
	Console.WriteLine ($"    Screen: {screen} Bounds: {screen.Bounds} Scale: {screen.Scale} NativeBounds: {screen.NativeBounds} NativeScale: {screen.NativeScale} CurrentMode: {screen.CurrentMode} PreferredMode: {screen.PreferredMode} AvailableModes: {string.Join (", ", screen.AvailableModes.Select (v => v.ToString ()))}");
}
```

And compare it to the Displays section in the System Settings.

**Comment by jamesmontemagno** [comment]
@rolfbjarne @drasticactions I assume the binding is just fine, but in Essentials we look at UIScreen.MainScreen.Bounds and .Scale.... 

https://github.com/dotnet/maui/blob/main/src/Essentials/src/DeviceDisplay/DeviceDisplay.ios.cs#L16

**Comment by jamesmontemagno** [comment]
Just tested out my mine here.

I think it is important to make sure you dump out your Density property as well.

When i go into my displays and set it manually to 1680x1050 I get:

From Essentials: 3360x2100 with density of 2... which makes sense... you divide those numbers by 2

From the API directly for MainScreen i get a bounds of 1680x1050 with scale of 2... which matches up.... and the same is true iterating over it.


If i change it manually to 2560x1600 i get this back correct with a scale of 1....

Here is the code I uses and would be helpful to see your output and a screenshot of your display in settings... i manually picked the resolution....
