### ISSUE TITLE
How to start a single UI test from the command line?

### ISSUE THREAD

**Issue by MartyIX** [dotnet/maui#19554]
https://github.com/dotnet/maui/wiki/UITests#running-from-the-command-line-you-can-replace-buildps1-by-dotnet-cake explains how to run UI tests. 

It would be useful to mention how to run a single UI test from the command line as well.

Can it be added?

**Comment by mattleibow** [comment]
@PureWeen I think you added a way? Or maybe @jfversluis ?

**Comment by mattleibow** [comment]
The cake testfilter command just takes any dotnet test filter you want to give it

![Image](https://github.com/user-attachments/assets/afec5675-6209-4e52-929c-93958296eeb2)

 
 
 
![Image](https://github.com/user-attachments/assets/dc697d6c-58d2-44ac-9e78-bec061d1a5da)
