### ISSUE TITLE
can't compile on vs for Mac with .net 8 due to missing supporting packages

### ISSUE THREAD

**Issue by michaelonz** [dotnet/maui#19555]
### Description

When I compile on VS for MAC I get the following errors in the output before it aborts the build.
    

    Creating directory "obj/Debug/net8.0-ios/ref".
    Target ResolvePackageAssets:
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.Configuration.Abstractions with version (>= 8.0.0)
        /Users//REDACTEDUSER/REDACTEDPROJECT//AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 115 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ]
        /Users//REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
        /Users//REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.Primitives with version (>= 8.0.0)
        /Users//REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 113 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ]
        /Users/michaelo/BellMinderProCell/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
        /Users/michaelo/BellMinderProCell/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.DependencyInjection.Abstractions with version (>= 8.0.0)
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 112 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ]
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.Options with version (>= 8.0.0)
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 116 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ]
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs

NOTE: I have tried to install all of these nugets - none of them will install they all log the same issue as above.
I also can't update other nugets because of issue above...it errors the same as above when I try and add them.

### Steps to Reproduce

I suspect there is some sort of reference or Nuget missing but I don't know what is triggering the compile issue.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.1.9171

### Affected platforms

macOS

### Affected platform versions

IOS 16.6

### Did you find any workaround?

NO I currently can't compile for Mac

### Relevant log output

```shell
Creating directory "obj/Debug/net8.0-ios/ref".
    Target ResolvePackageAssets:
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.Configuration.Abstractions with version (>= 8.0.0)
        /Users//REDACTEDUSER/REDACTEDPROJECT//AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 115 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ]
        /Users//REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
        /Users//REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.Primitives with version (>= 8.0.0)
        /Users//REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 113 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ]
        /Users/michaelo/BellMinderProCell/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
        /Users/michaelo/BellMinderProCell/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.DependencyInjection.Abstractions with version (>= 8.0.0)
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 112 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ]
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.Options with version (>= 8.0.0)
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 116 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ]
        /Users/REDACTEDUSER/REDACTEDPROJECT/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
```

**Comment by jfversluis** [comment]
Visual Studio for Mac does not officially support .NET 8 as mentioned [here](https://learn.microsoft.com/visualstudio/mac/what-happened-to-vs-for-mac?view=vsmac-2022#support-timeline).

You will probably want to use VS Code with the .NET MAUI extension or build on Windows. If you try that, please let us know if it works. If not, please add the contents of your csproj file at the very least, ideally the full project so we can have a look.

**Comment by michaelonz** [comment]
Thanks @jfversluis  - does .net maui 8.0 actually work for IOS in vscode? - I vaguely recall looking at that and reading it wouldn't work also?

**Comment by jfversluis** [comment]
It absolutely does, find the official extension page [here](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-maui) and my video about it [here](https://www.youtube.com/watch?v=w7bbY3hiowk).

It is one of the potential replacements for when Visual Studio for Mac is being retired. We on the .NET MAUI team are already using it daily, also for iOS. Let me know how it goes.

**Comment by mobilewares** [comment]
> Visual Studio for Mac does not officially support .NET 8 as mentioned [here](https://learn.microsoft.com/visualstudio/mac/what-happened-to-vs-for-mac?view=vsmac-2022#support-timeline).
> 
> You will probably want to use VS Code with the .NET MAUI extension or build on Windows. If you try that, please let us know if it works. If not, please add the contents of your csproj file at the very least, ideally the full project so we can have a look.

I'm a little confused. I'm using VS Mac for compiling and running .NET8 MAUI iOS Apps (and currently using it for 8.0.3 release). It's not terribly fast (even on a Mac Studio) but it does actually work and I don't get any missing package issues.

**Comment by michaelonz** [comment]
I have loaded vscode and installed the maui add on etc.


But when I compile I am getting the same error as I reported in VS MAC (full visual studio) - the issue is with a subproject I am using.

NOTE: Username and project name redacted

dotnet build /Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln /target:Plugin_Maui_AudioWithSetData:rebuild /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.Configuration.Abstractions with version (>= 8.0.0) [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 115 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ] [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.Primitives with version (>= 8.0.0) [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 113 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ] [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.DependencyInjection.Abstractions with version (>= 8.0.0) [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 112 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ] [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102: Unable to find package Microsoft.Extensions.Options with version (>= 8.0.0) [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 116 version(s) in nuget.org [ Nearest version: 8.0.0-rc.2.23479.6 ] [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs [/Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.AudioWithSetData.sln]
  Failed to restore /Users/REDACTED/REDACTED/AudioLibrary/Plugin.Maui.AudioWithSetData/src/Plugin.Maui.Audio/Plugin.Maui.AudioWithSetData.csproj (in 1.68 sec).




Below is the project file that is causing the compile errors - it should look familiar to you @jfversluis  :)  

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">16.1</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">16.1</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">34.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>

        
        <Authors>bijington;jfversluis</Authors>
        <Copyright>Copyright © bijington, jfversluis and contributors</Copyright>
        <IsPackable>True</IsPackable>
        <PackageProjectUrl>https://github.com/jfversluis/Plugin.Maui.Audio</PackageProjectUrl>
        <RepositoryUrl>https://github.com/jfversluis/Plugin.Maui.Audio</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>dotnet-maui;maui;audio;sound</PackageTags>
        <IncludeSymbols>True</IncludeSymbols>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <Title>.NET MAUI Audio Plugin</Title>
        <Description>Plugin.Maui.Audio provides the ability to play audio inside a .NET MAUI application.</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <DebugType>portable</DebugType>
        <PackageIcon>icon.png</PackageIcon>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TargetFramework>net8.0-ios16.4</TargetFramework>
    </PropertyGroup>

    
 
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
      <CreatePackage>false</CreatePackage>
    </PropertyGroup>
    <ItemGroup Condition="$(TargetFramework.StartsWith('net')) == true AND $(TargetFramework.Contains('-ios')) != true AND $(TargetFramework.Contains('-maccatalyst')) != true ">
        <Compile Remove="**\**\*.ios.cs" />
        <None Include="**\**\*.ios.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
        <Compile Remove="**\ios\**\*.cs" />
        <None Include="**\ios\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
        <Compile Remove="**\*.macios.cs" />
        <None Include="**\*.macios.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
        <Compile Remove="**\macios\**\*.cs" />
        <None Include="**\macios\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    </ItemGroup>
    
    <ItemGroup Condition="$(TargetFramework.StartsWith('net')) == true AND $(TargetFramework.Contains('-android')) != true">
        <Compile Remove="**\**\*.android.cs" />
        <None Include="**\**\*.android.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
        <Compile Remove="**\android\**\*.cs" />
        <None Include="**\android\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    </ItemGroup>
    
    <ItemGroup Condition="$(TargetFramework.StartsWith('net')) == true AND $(TargetFramework.Contains('-windows')) != true">
        <Compile Remove="**\*.windows.cs" />
        <None Include="**\*.windows.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
        <Compile Remove="**\windows\**\*.cs" />
        <None Include="**\windows\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    </ItemGroup>
    
    <ItemGroup Condition="!($(TargetFramework.StartsWith('net')) == true AND $(TargetFramework.EndsWith('.0')) == true AND $(TargetFramework.Contains('-')) != true)">
        
        <Compile Remove="**\*.net.cs" />
        <None Include="**\*.net.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
        <Compile Remove="**\net\**\*.cs" />
        <None Include="**\net\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\nuget.png" PackagePath="icon.png" Pack="true" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    </ItemGroup>

</Project>

At this stage I can't compile in either full vs (I understand that's not longer supported with v8) but I also have the same compile issue on vs code

**Comment by michaelonz** [comment]
Hi Guys - I tried something else.... I created a brand new maui project from inside vscode and that has exactly the same compile issue as what I detailed above - so I don't think it's project specific ...... totally at a loss as to what it might be at this stage but I basically can't even run a hello world at this stage on IOS either.

**Comment by michaelonz** [comment]
Just thought I would also add that this project compiles fine in visual studio on windows and runs fine on android - so I suspect it’s somehow environment related but I don’t even reference the things it’s complaining about - after any tips on what
I should be checking - at a loss at this stage… I can’t work on iOS app at all.

**Comment by michaelonz** [comment]
Hi guys - I managed to get this to work (in full visual studio) - it turned out I had iOS 17.2 selected in my project but my test phone was still on 14.6 - I also had the wrong frameworks in the project file - once they all lined up it started working again. 

You can close this issue ( although adding a good compile failure message might save others some time )
