### ISSUE TITLE
Maui SkiaSharp GetPoints Cause App Crash Intermittently in iPad.

### ISSUE THREAD

**Issue by KalaiLandmark** [dotnet/maui#19558]
### Description

We are using skin sharp to create plan using shapes. While creating plans randomly app crash is happening. when noticed in the log which is showing at SKPath get points method. Refer SS.
<img width="868" alt="Screenshot 2023-12-22 at 4 46 18 PM" src="https://github.com/dotnet/maui/assets/123460309/793c58ae-8b96-486f-817d-5fbe9ff3d98f">

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jfversluis** [comment]
This is not a .NET MAUI issue probably but a SkiaSharp one. Besides the screenshot you will want to add relevant code when you [report the issue there](https://github.com/mono/SkiaSharp/). Without code it will be near impossible to find the root cause of this.
