### ISSUE TITLE
[Windows] No Property to hide 'Switch' Label

### ISSUE THREAD

**Issue by BaY1251** [dotnet/maui#19551]
### Description

the image below, a 'On' or 'Off' Label always show. 

![image](https://github.com/dotnet/maui/assets/48309205/2fb46a1b-a544-4ea5-8871-7bf6868d20f5)

### Steps to Reproduce

see amy 'Switch' on Windows

### Link to public reproduction project repository

None

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows10-22H2 net8.0-windows10.0.19041.0

**Comment by jfversluis** [comment]
Thanks for the report! This is by design. That is just the way a Switch looks on Windows.

Also see #6177 and I wrote a little post about the how and why and how to change it in your project: https://blog.verslu.is/maui/remove-switch-text-label/

**Comment by BaY1251** [comment]
Thank you very much!  The solution perfectly meets my requirements
