### ISSUE TITLE
Resizetizer doesn't allow having one-letter named images

### ISSUE THREAD

**Issue by movsar** [dotnet/maui#19574]
### Description

I had a bunch of images I was trying to use as resources, and after hours of banging my head it turns out it's a bug, when I changed my a.png to aa.png it worked perfectly well

### Steps to Reproduce

1. Add an image file to Resources\Images named "a.png"
2. Try to build and run the app

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Did you find any workaround?

change the names to not be single character before extension

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error		One or more invalid file names were detected.  File names must be lowercase, start and end with a letter character, and contain only alphanumeric characters or underscores: a (Resources\Images\a.png)	dosham	C:\Users\x.dr\.nuget\packages\microsoft.maui.resizetizer\8.0.3\buildTransitive\Microsoft.Maui.Resizetizer.After.targets	612
```

**Comment by Xenooooon** [comment]
Sorry for the weirdness in my commits, its my first pull request and I thought I did it incorrectly.
I will strive to do better!
