### ISSUE TITLE
toolkit:MediaElement does not start when asked to play.

### ISSUE THREAD

**Issue by AghaSKhan** [dotnet/maui#19587]
### Description

It works fine when you user clicks on play button, but I would like to see when I issue a play command. I do not want to display media controls, but if I hide the controls, I have no option to play it, because play command does not work. I have N number of vides which I would like to pay. It works fine only two three times then it breaks and never recovered. To test that I added two videos. Just click right and left button couple of time and you will be able to break.  I do not want to use provided controls, but I want to use my own controls. I do not see any option. 
[MauiVideo.zip](https://github.com/dotnet/maui/files/13767311/MauiVideo.zip)

### Steps to Reproduce

The application is provided.
[MauiVideo.zip](https://github.com/dotnet/maui/files/13767313/MauiVideo.zip)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

There may be, but I have no idea

### Relevant log output

```shell
none
```

**Comment by Eilon** [comment]
Hi, if this issue is related to the .NET MAUI Community Toolkit, please post the question here instead: https://github.com/CommunityToolkit/Maui/issues
