### ISSUE TITLE
IsEnabled Not Updating as Expected with Editor's Trigger on net8.0

### ISSUE THREAD

**Issue by usa-33-pyon** [dotnet/maui#19582]
### Description

I have implemented a Trigger where IsEnabled becomes False when the Editor's Text is null. 

The code expects that when the button is tapped an even number of times, a value will be set to the Editor's Text, and when tapped an odd number of times, null will be set to the Editor's Text. Additionally, through the Editor's Trigger, if the Text is null, IsEnabled becomes False, and if not, IsEnabled becomes True. 
```csharp
        private void OnCounterClicked(object sender, EventArgs e)
        {
            count++;

            if (count % 2 == 0)
                TextEditor1.Text = $"Clicked {count} times";
            else
                TextEditor1.Text = null;
        }
```
```xaml
            <Editor 
                x:Name="TextEditor1"
                IsEnabled="True">
                <Editor.Triggers>
                    <Trigger TargetType="Editor" Property="Text" Value="{x:Null}">
                        <Setter Property="IsEnabled" Value="False" />
                    </Trigger>
                </Editor.Triggers>
            </Editor>

            <Button
                x:Name="CounterBtn"
                Text="Click me" 
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Fill" />
```
This works as expected when the TargetFramework is set to net7.0-android and net7.0-ios. 
However, when building and running with TargetFramework set to net8.0-android and net8.0-ios, IsEnabled remains False even when tapping the button continuously.

I have tried it on Android and iOS, but I have not tested it on other platforms.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

**Comment by kubaflo** [comment]
@mattleibow @usa-33-pyon I tested it with the `8.0.10-nightly.10006` and couldn't replicate it. Everything works as expected

https://github.com/dotnet/maui/assets/42434498/9c5e5fcb-1cc9-49e9-b1b9-20ebbc3b15f9

**Comment by QianaJiao** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 1, not repro on .NET 8 iOS & Android platform with sample project.
