### ISSUE TITLE
I Want to disabled minisize button and close button,but I can't find how to setting it.

### ISSUE THREAD

**Issue by Dylan-Jinx** [dotnet/maui#19586]
### Description

I develop the maui run in macOS,I Want to disabled minisize button and close button,but I can't find how to setting it.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

macOS

**Comment by drasticactions** [comment]
Short Answer: You can't.

Long Answer: Mac Catalyst doesn't support disabling those buttons. As MAUI uses it for its cross-platform implementation for MacOS, you can't access it from MAUI, as there's no supported way to do it.

That said, Mac Catalyst UIWindows are built upon NSWindows, and if you know enough about how to access those APIs (Such as what I've [done here](https://github.com/drasticactions/Drastic.Tools/blob/main/src/Drastic.TrayWindow/UINSWindow.Catalyst.cs)) you could access the NSWindow and disable them from there. That said, it's totally unsupported by Apple and requires using private APIs to do it, and also making it unlikely it would get allowed in the Mac App Store should you want it to go there.
