### ISSUE TITLE
Character dIsplayed very differently in Android and Windows. 

### ISSUE THREAD

**Issue by Dumuzy** [dotnet/maui#19597]
### Description

A button which contains only the character "arrow backwards" (Text="&#x21A9;") is displayed how I think it should be on Windows, but the arraow is very small and moved to the bottom on Android. Font is OpenSans-Regular.  It is the same with some of the other arrows. 
![000487](https://github.com/dotnet/maui/assets/115729252/033221a1-c660-48c4-adf5-6032271316b0)
![000488](https://github.com/dotnet/maui/assets/115729252/e18a80ca-e4c4-4f45-9cc2-3fd936c5967a)

### Version with bug

7.0.59

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by tjiakwokyung28** [comment]
this 1st problem is winui property = coef * adroid property, 2nd problem is dynamic layout with we don't adjust it. solved microsoft must be create new spesial layout for winui to convert android or ios layout, then developer self setting it

**Comment by Dumuzy** [comment]
I am sorry, I really don't understand what you want to tell me.  Anyhow, this is a bug and surely soon will be fixed by the Maui team!?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 3(8.0.3). Repro on Windows 11 with below Project:
[19597.zip](https://github.com/dotnet/maui/files/14046328/19597.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/e4cb3e24-925d-4b7a-a204-891bc6e410b7)

Android:
![image](https://github.com/dotnet/maui/assets/97647558/78cda334-29a6-4c2b-b636-faedda8baf59)

**Comment by mattleibow** [comment]
The reason the character is different is because the font is different on each platform.

If you want emojis to be the same, you have to use the same emoji font on all the platforms.

**Comment by Dumuzy** [comment]
1. Emojis? I'm talking about arrows. I wouldn't count those to the Emojis. 
2. I *am* using the same font on Android and Windows.  
3. I have the suspicion, that, if one glyph is not available in the font that is desired, the system takes the glyph from another font, on each system from a different one - AND it tells nobody about this.  This might be the reason of this whole problem. 
4. To make this a bit less unpleasant for the developers, at least there should be some logging of this behaviour. 
5. WHAT? This has been CLOSED? This has happened to other bugs I have reported. CLosing without solving. 
6. I have the feeling, you MAUI guys think that bugs go away if the bug reports are closed. THIS IS NOT THE CASE. THE BUGS STAY, EVEN WHEN THE BUG REPORTS ARE CLOSED. 
7. As you do this very regularly, closing bug reports without fixing the bug, developers like me will stop reporting bugs and MAUI will stay crap forever -  even when the "reported bug numbers" are down.
