### ISSUE TITLE
MAUI pack problem

### ISSUE THREAD

**Issue by Dylan-Jinx** [dotnet/maui#19595]
### Description

I want to pack MAUI Application that use .netCore 8, and generate msix file,but how to pack it can auto install runtime when user use msix file install this application.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

Windows

**Comment by drasticactions** [comment]
Did you try reading the documentation? https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-8.0
