### ISSUE TITLE
TableView bugs

### ISSUE THREAD

**Issue by Strypper** [dotnet/maui#19616]
### Description

TableView doesn't have
+ Font family supported
+ Dark mode background color still stays white on IOS
+ Titles are not "Upper cases" when texts are
+ Image cell don't have a way to control the image width and height

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 5(8.0.7&8.0.3). Can repro on all platforms.
1. TableView doesn't have Font family supported
2. Dark mode displayed black on iOS
3. Upper cases cannot be changed:
![image](https://github.com/dotnet/maui/assets/77434865/93a6a642-8c1d-41f4-916b-8a4a7d073f1d)
4.Image cell don't have a way to control the image width and height：
![image](https://github.com/dotnet/maui/assets/77434865/e6abc57c-fd2d-42fd-8827-c8f38f9e84a5)
