### ISSUE TITLE
Differentiate Left/Right click in PointerGestureRecognizer

### ISSUE THREAD

**Issue by breadnone** [dotnet/maui#19617]
### Description

There's no way to detect left/right  click in PointerGesterRecognizer

### Steps to Reproduce

clickGesture.PointerPressed += (sender, evt)=>
{
    //There's no way to retrieve info of which mouse button was clicking
};

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS

**Comment by cdecron** [comment]
Hello,

I don't really understand why a sample code (more than what has been provided by @breadnone) is needed.
The fact is that `PointerGestureRecognizer` doesn't provide any parameter to detect if it's a left or right click.
To detect left/right click, we need to use `TapGestureRecognizer`, which provides `Buttons` parameter, however `TapGestureRecognizer` doesn't allow to detect pointer down, it only detects pointer up with its event `Tapped`.

Thus, what is need is `PointerGestureRecognizer` which allows to detect left/right click, or a `TapGestureRecognizer` which allows to detect pointer down.

Thank you
