### ISSUE TITLE
Make MAUI Trimming Safe

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#1962]
We should be able to build the library with Trimming enabled and have MAUI work in applications.

 - [ ] Core https://github.com/dotnet/maui/pull/3249
 - [x] Compat https://github.com/dotnet/maui/pull/3161
 - [ ] Controls
 - [ ] Controls.Xaml
 - [x] Essentials
 - [ ] OperatingSystem OS Checks https://github.com/dotnet/maui/issues/461

**Comment by jonathanpeppers** [comment]
Essentials is already done for Android, but maybe not other platforms?

https://github.com/dotnet/maui/blob/a13e89d5df5c7dfafef37767e70fa297a4b4371e/src/Essentials/src/AssemblyInfo/AssemblyInfo.android.cs#L3

**Comment by eerhardt** [comment]
I've noticed that `Microsoft.Maui.Controls.dll` is the largest managed assembly in a `dotnet new maui` android app:

![image](https://user-images.githubusercontent.com/8291187/151254042-99e52d78-d85a-4bba-aae6-9c517484fe24.png)

We should consider adding `IsTrimmable=true` to that assembly (and fix any trimming issues associated with doing that).

**Comment by jonathanpeppers** [comment]
Closing in favor of: https://github.com/dotnet/maui/issues/18658
