### ISSUE TITLE
Not able to change the color of scroller and also scroller is not getting visible on verticalScroll="always*

### ISSUE THREAD

**Issue by Faizankhan22** [dotnet/maui#19622]
### Description

In the tage scroll view I m not able to change the scroller color and also it is not getting visible on property vertical scroll visibility="Always "

### Version with bug

7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

**Comment by hasantr** [comment]
Yes, that's what I wanted to say.

**Comment by QianaJiao** [comment]
I created Maui Blazor project on VS 17.10.0 Preview 1, Maui 8.0.6 
Add a `<div class="scroller">` And 
```
.scroller {
    width: auto;
    height: 200px;
    overflow-y: scroll;
    scrollbar-color: green red;
}
```
I'm unable to repro this issue now. 

![image](https://github.com/dotnet/maui/assets/91244512/8f85a7b3-bc01-4b3f-b550-588505a0b9e3)
![image](https://github.com/dotnet/maui/assets/91244512/40771f50-0311-421f-a927-6c43f441ab52)

**Comment by Faizankhan22** [comment]
This is in web CSS I need the same in .net Maui Xml.
Thanks
Regarding Faizan khan.

**Comment by jfversluis** [comment]
So if I understand correctly you want this for a .NET MAUI app running on Windows, correct?

Would you be able to maybe put together a small project with what it is that you are looking to use in your app? That will make it easier for us to look at and try some things out and maybe rule out some things that you have already tried. Thanks!

**Comment by Faizankhan22** [comment]
Hello Dotnet/Maui and Sir Gerald
I actually was just curious about the You tube videos regarding the .net
maui while there is something that is missing while developers search that
and look for that terminologies.
Regard
Faizan khan
