### ISSUE TITLE
Deploy from windows visual studio to Apple device appicon and splashscreen problem

### ISSUE THREAD

**Issue by enkaradag** [dotnet/maui#19640]
### Description

Hi,

Before, with .net7 we needed a mac computer to debug or deploy from windows to an apple device (iphone, ipad).

Now with .net8, there seems no need for a mac computer. App can be deployed to iphone from a windows machine. This is really handy (I'm not sure this is an ios version feature or comes with .net8)

Everything works good, but whatever i did, appicon and splashscreen images are not shown properly. My app deploys with default purple .net icon and shows up the default purple .net splash screen. When the same app is deployed to ios from visual studio windows over a connected mac, app icon and splash screen show up as expected

I deleted app and deployed again, restarted iphone, clean up project, deleted bin and obj folders, tried with a new project, uninstalled and installed visual studio, tried another iphone and another ipad. Result is the same, app always shows the default appicon

Thanks
Ender

### Steps to Reproduce

1) Create a new .NET MAUI project, in visual studio for windows
2) Change appicon
3a) Connect your ios device to windows pc and deploy, you will see app icon is still default .net8 icon
3b) Connect your ios device to a mac and debug remotely from windows, you will see app icon is correct

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

**Comment by Redth** [comment]
This is one of the [Limitations of iOS Hot Restart](https://learn.microsoft.com/dotnet/maui/ios/hot-restart?view=net-maui-8.0#limitations) on Windows:

> Asset catalogs aren't supported. When using Hot Restart, your app will show a .NET icon and launch screen.

You will need to either develop on a mac, or use iOS Remote builds via [Pair to Mac](https://learn.microsoft.com/dotnet/maui/ios/pair-to-mac?view=net-maui-8.0) from windows to see your splash screen and app icon changes on iOS.
