### ISSUE TITLE
[X] Simplify XamlServiceProvider setup code generated by XamlC when invoking markup extensions

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/maui#19650]
The IL generated by XamlC to prepare an instance of `XamlServiceProvider` for a call to `IMarkupExtension.ProvideValue` often contains unnecessary services. For example, the generated code creates a new instance of `XamlTypeResolver` whenever we call `ConstraintExpression`, `DynamicResourceExtension`, `ReferenceExtension`, or `StaticResourceExtension`, but none of these extensions uses it.

We already have the `[AcceptEmptyServiceProvider]` attribute to optimize the service provider for some extensions. We could add a new attribute `[RequiredService(typeof(IXmlLineInfoProvider))]` which would be used by `XamlC` to prepare only the services which are actually needed.

/cc @StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
we should also warn if a converter doesn't have any attribute
