### ISSUE TITLE
Entry with Handler ignores Placeholder text

### ISSUE THREAD

**Issue by AlleSchonWeg** [dotnet/maui#19651]
### Description

In XF a have a custom renderer for the Entry-Control and i try to migrate this to maui. The custom entry has a placeholder text. In XF the placeholder text is visible but in maui nothing is visible.
![image](https://github.com/dotnet/maui/assets/6727366/348cd16c-9c14-4743-b239-34457d601b44)

Repro:
[CustomEntryPlaceholder.zip](https://github.com/dotnet/maui/files/13810999/CustomEntryPlaceholder.zip)

I tested only android, because i'm in the migration process and iOS is far away from working.

### Steps to Reproduce

Create a "empty" handler for demo:
```C#
#elif (NETSTANDARD || !PLATFORM) || (NET6_0_OR_GREATER && !IOS && !ANDROID)
using PlatformView = System.Object;
#endif
using Microsoft.Maui.Handlers;
using CustomEntryPlaceholder;

public partial class CustomEntryHandler
{
    public static PropertyMapper<CustomEntry, CustomEntryHandler> PropertyMapper = new PropertyMapper<CustomEntry, CustomEntryHandler>(ViewMapper)
    {
        [nameof(CustomEntry.ShowUnderline)] = MapShowUnderline,
    };

    public CustomEntryHandler() : base(PropertyMapper) //set  base(null) and placeholder starts working. But the Placeholder Textcolor is also wrong.
    {
    }
}
```
and the platform:

```C#
using CustomEntryPlaceholder;
using Microsoft.Maui.Handlers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

    public partial class CustomEntryHandler : EntryHandler
    {
    public static void MapShowUnderline(EntryHandler handler, CustomEntry view)
    {
       // SetUnderline(handler, view);
    }
}
```

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by bradencohen** [comment]
I think you should call through to the base method with the `Mapper` property, not `ViewMapper`, although I didn't test.

```csharp
#elif (NETSTANDARD || !PLATFORM) || (NET6_0_OR_GREATER && !IOS && !ANDROID)
using PlatformView = System.Object;
#endif
using Microsoft.Maui.Handlers;
using CustomEntryPlaceholder;

public partial class CustomEntryHandler
{
    public static PropertyMapper<CustomEntry, CustomEntryHandler> PropertyMapper = new PropertyMapper<CustomEntry, CustomEntryHandler>(Mapper)
    {
        [nameof(CustomEntry.ShowUnderline)] = MapShowUnderline,
    };

    public CustomEntryHandler() : base(PropertyMapper) 
    {
    }
}
```

**Comment by AlleSchonWeg** [comment]
> I think you should call through to the base method with the `Mapper` property, not `ViewMapper`, although I didn't test.
> 
> ```cs
> #elif (NETSTANDARD || !PLATFORM) || (NET6_0_OR_GREATER && !IOS && !ANDROID)
> using PlatformView = System.Object;
> #endif
> using Microsoft.Maui.Handlers;
> using CustomEntryPlaceholder;
> 
> public partial class CustomEntryHandler
> {
>     public static PropertyMapper<CustomEntry, CustomEntryHandler> PropertyMapper = new PropertyMapper<CustomEntry, CustomEntryHandler>(Mapper)
>     {
>         [nameof(CustomEntry.ShowUnderline)] = MapShowUnderline,
>     };
> 
>     public CustomEntryHandler() : base(PropertyMapper) 
>     {
>     }
> }
> ```

Thank you. That fixed my issue.
