### ISSUE TITLE
Unable to request android.permission.RECEIVE_SMS 

### ISSUE THREAD

**Issue by tarasverq** [dotnet/maui#19658]
### Description

Hi.

Looks like after merging PR #14203 - `Remove ReceiveSms added by default` it's impossible to request `android.permission.RECEIVE_SMS` permission at all. It's not in the list anymore.

The problem is in the file [Microsoft.Maui.ApplicationModel.Permissions.android.cs](https://github.com/dotnet/maui/blob/4c23669ea751bec750a5b4246583dee782e53eec/src/Essentials/src/Permissions/Permissions.android.cs#L442)
I think it should look like this:

```C#
public partial class Sms : BasePlatformPermission
{
	public override (string androidPermission, bool isRuntime)[] RequiredPermissions
	{
		get
		{
			var permissions = new List<(string, bool)>
			{
			};

			if (IsDeclaredInManifest(Manifest.Permission.SendSms))
				permissions.Add((Manifest.Permission.SendSms, true));
			if (IsDeclaredInManifest(Manifest.Permission.ReadSms))
				permissions.Add((Manifest.Permission.ReadSms, true));
			if (IsDeclaredInManifest(Manifest.Permission.ReceiveWapPush))
				permissions.Add((Manifest.Permission.ReceiveWapPush, true));
			if (IsDeclaredInManifest(Manifest.Permission.ReceiveMms))
				permissions.Add((Manifest.Permission.ReceiveMms, true));


			--> if (IsDeclaredInManifest(Manifest.Permission.ReceiveSms))
			-->	 permissions.Add((Manifest.Permission.ReceiveSms, true));

			return permissions.ToArray();
		}
	}
}

```

My app needs this permission to process messages in background using  `BroadcastReceiver`, but I'm unable to request it :(
I have a proper line in my Manifest file, but anyway it doesn't work:
```xml
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.RECEIVE_SMS"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Giving this permission manually through settings

**Comment by Redth** [comment]
Good catch, I agree, we should be still adding it to the list of requested permissions if it's defined in the manifest, just like the others.

For now you could always implement your own Sms permission class with the correct code until this fix gets merged and released.
