### ISSUE TITLE
Exception Occurs When Updating the Text of a Label Using Task.Run()

### ISSUE THREAD

**Issue by NirmalKumarYuvaraj** [dotnet/maui#19666]
### Description

I need to update the text of the label using Task.Run() to satisfy certain conditions for my convenience. However, it throws a ComException on the Windows platform. The label updates properly when I update it normally without using Task.Run(). I have attached the screenshot for your reference. It is working fine in Android platform.

ScreenShot:
![image](https://github.com/dotnet/maui/assets/97871636/a22c8dca-2cd4-46c4-b405-e65257b5f9a3)

### Steps to Reproduce

1. Run the sample from the Repo.
2. Click on the button.

### Link to public reproduction project repository

https://github.com/NirmalKumarYuvaraj/Task.Run

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on IOS and Mac platforms

### Did you find any workaround?
* Using dispatcher I did not face any exception and it is working fine.
```C#
 Task.Run(() => this.Dispatcher.Dispatch(() => label.Text = "New Text"));
```

**Comment by drasticactions** [comment]
That's because you're updating the label on a different thread, which is not supported on Windows. In general, you should only update UI Elements on the UI Thread (Which is what you're doing when you run Dispatcher). It may happen to work on Android, but that's by happenstance and not something you should rely on.

So as far as I know, this is not a bug. @PureWeen what do you think?

**Comment by SmartmanApps** [comment]
Is there a reason you're not binding the text to a property? [Microsoft Learn MAUI Data Binding Basics](https://learn.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/data-binding-basics?view=net-maui-8.0)

**Comment by Shahid-khan5** [comment]
Try this:
  Task.Run(() =>
  {
      MainThread.BeginInvokeOnMainThread(() =>
      {
          label.Text = "New Text";
      });
  });

**Comment by NirmalKumarYuvaraj** [comment]
> That's because you're updating the label on a different thread other than the UI Thread, which is not supported on Windows. In general, you should only update UI Elements on the UI Thread (Which is what you're doing when you run Dispatcher). It may happen to work on Android, but that's by happenstance and not something you should rely on.
> 
> So as far as I know, this is not a bug. @PureWeen what do you think?

The same exception was thrown when calling invalidate measure for an element with Task.Run.
 
Is this a only way to update VisualElement properties by using a dispatcher?

**Comment by PureWeen** [comment]
> Is this a only way to update VisualElement properties by using a dispatcher?

Yes, for us to schedule UI updates so everything coordinates correctly with all the various types of applications and scenarios would be fairly difficult. It's better for the user to know when they want to switch back to the UI Thread and then update all aspects of the UI that they want updated.
