### ISSUE TITLE
Unable to deploy maui app on ios

### ISSUE THREAD

**Issue by BjoernMSG** [dotnet/maui#19671]
### Description

Ive created a simple project which references an another project. The referenced project has no maui-related code so it has "net8" as targetframework. The deployment fails on. I found in the log a error that the "project.assets.json" does not have a target for "net8.0". if i add "net8.0-ios" as targetframework to the referenced project it seems to work.
For android it is fine.

Demo: https://github.com/BjoernMSG/MauiTest

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Xcode 15.1

**Comment by drasticactions** [comment]
Could you please create an example for how you set up your projects?

**Comment by BjoernMSG** [comment]
[MAUITest.zip](https://github.com/dotnet/maui/files/13821914/MAUITest.zip)

Ive attached a small demo project.

**Comment by drasticactions** [comment]
It builds and deploys fine for me without issue from CLI. Are you doing this from Visual Studio on Windows? VS Mac? Rider?

**Comment by BjoernMSG** [comment]
Im using Rider on a MacOs.
Thats the error i got from the log: 
![image](https://github.com/dotnet/maui/assets/99808004/e5453a2b-096f-497e-9857-3983e48f911b)

And that is project.json from the library:

![image](https://github.com/dotnet/maui/assets/99808004/d414df16-9254-42a1-8f21-4444f9e1a9d9)

**Comment by BjoernMSG** [comment]
We have the same issue for another developer, too

**Comment by BjoernMSG** [comment]
Any news?

**Comment by ChristopherStephan** [comment]
This issue seems to be only reproducible using Rider. Created this issue:

https://youtrack.jetbrains.com/issue/RIDER-104416/iOS-deployment-fails-when-referenced-project-does-not-target-net8.0-iOS-project.assets.json-doesnt-have-a-target-for-net8.0.

**Comment by kevinxufei** [comment]
Verified on 8.0.14 & 8.0.0-rc.2.9530 with the latest 17.6.10(build428), cannot repro on iOS platform.
