### ISSUE TITLE
iOS Memory issue

### ISSUE THREAD

**Issue by NXDMN** [dotnet/maui#19686]
### Description

I migrated a Xamarin Forms project to .NET MAUI, now the app works fine in simulator but not in real iOS device. When navigate from homepage to a detail page, it will crash and logs a single line message (shown below). Try catch cannot catch anything, so i use profiling. 
[my-dev-port2_20240104_133503.speedscope.zip](https://github.com/dotnet/maui/files/13827014/my-dev-port2_20240104_133503.speedscope.zip)

This crash cant reproduce and I couldnt provide any sample project. 

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

### Relevant log output

```shell
error: * Assertion at /Users/runner/work/1/s/src/mono/mono/utils/lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator

Application terminated (with exit code '' and/or crashing signal '6).
```

**Comment by drasticactions** [comment]
Unless something jumps out at somone on the MAUI team as an issue looking at that speedtrace, I think we should need more information to diagnose this. I think you have a ListView on the page, so maybe a reproduction of what that view is? Or what your templated cell(s) are? Or what your view model does?

Having a reproducible sample would really help, though.
