### ISSUE TITLE
Net Maui Windows Titlebar color is not working as expected 

### ISSUE THREAD

**Issue by ssamix** [dotnet/maui#19709]
### Description

                   .ConfigureLifecycleEvents(events =>
                   {
#if WINDOWS
                    events.AddWindows(windowsLifecycleBuilder =>
                    {
                        windowsLifecycleBuilder.OnWindowCreated(window =>
                        {            

                            var handle = WinRT.Interop.WindowNative.GetWindowHandle(window);
                            var id = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(handle);
                            var appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(id);

            

                            var titleBar = appWindow.TitleBar;
                            var favoriteColor = new Windows.UI.Color()
                            {
                                R = 0x1C,
                                G = 0x1C,
                                B = 0x1C,
                            };
                            titleBar.BackgroundColor = favoriteColor;
                            //titleBar.ButtonBackgroundColor = favoriteColor;
                            ////titleBar.ButtonForegroundColor = Colors.White.ToWindowsColor();
                            //titleBar.InactiveBackgroundColor = favoriteColor;
                            ////titleBar.InactiveForegroundColor = Colors.White.ToWindowsColor();
                            //titleBar.ButtonInactiveBackgroundColor = favoriteColor;
                            ////titleBar.ButtonInactiveForegroundColor = Colors.White.ToWindowsColor();
                            ////titleBar.ButtonForegroundColor = Colors.White.ToWindowsColor();
                            ////titleBar.ButtonPressedBackgroundColor = Colors.DarkGray.ToWindowsColor();
                            ////titleBar.ButtonHoverBackgroundColor = Colors.DarkGray.ToWindowsColor();    

                                                                    //middle of screen

                                        if (appWindow is not null)
                                        {
                                            Microsoft.UI.Windowing.DisplayArea displayArea = Microsoft.UI.Windowing.DisplayArea.GetFromWindowId(id, Microsoft.UI.Windowing.DisplayAreaFallback.Nearest);
                                            if (displayArea is not null)
                                            {
                                                var CenteredPosition = appWindow.Position;
                                                CenteredPosition.X = ((displayArea.WorkArea.Width - appWindow.Size.Width) / 2);
                                                CenteredPosition.Y = ((displayArea.WorkArea.Height - appWindow.Size.Height) / 2);
                                                appWindow.Move(CenteredPosition);
                                            }
                                        }
                        });
                    });
#endif
                   });

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by PureWeen** [comment]
@ssamix Does this resolve your issue?

https://github.com/dotnet/maui/issues/18773#issuecomment-1815470830
