### ISSUE TITLE
Unable to debug IOS share extension or notification service extension

### ISSUE THREAD

**Issue by aiemsal** [dotnet/maui#19716]
### Description

Hello, I'm currently migrating my Xamarin.IOS app to net8.0-ios and I'm unable to debug my extensions. I have a share extension and a notification service extension. When I set one of them as startup project, I'm unable to select a target for the build whether I would like to build for simulator or for device. I successfully migrated the main app and the extensions are shipped with it and work but I can't debug them. Visual studio is only showing me the default target.

I'm using visual studio Mac 17.6.7. 
My application is a former Xamarin.IOS native app.

My share extension csproj : 

```
<Project` Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-ios</TargetFrameworks>
		<UseMauiEssentials>true</UseMauiEssentials>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<PropertyGroup>
		<IsAppExtension>true</IsAppExtension>
		<IsWatchApp>false</IsWatchApp>
        </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
	  <MtouchDebug>true</MtouchDebug>
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
	</PropertyGroup>
</Project>
```

Am I missing something ?

### Steps to Reproduce

1. Create a xamarin.IOS project
2. Add a share extension or a notification service extension project to it 
3. Migrate both to net8.0-ios
4. Try building the extension on simulator or device by making it the startup project

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.IOS

### Affected platforms

iOS

**Comment by drasticactions** [comment]
@rolfbjarne Would this make more sense for [xamarin/xamarin-macios](https://github.com/xamarin/xamarin-macios)? I don't think this issue would be related to anything inside of this repo.

**Comment by rolfbjarne** [comment]
@drasticactions I believe this is an issue for VS.

**Comment by drasticactions** [comment]
@aiemsal Could you please file this issue to Visual Studio? This is tooling that is not maintained in this repo and can't be addressed here. Thank you!

**Comment by aiemsal** [comment]
moved to https://developercommunity.visualstudio.com/t/Unable-to-debug-IOS-share-extension-or-n/10556715
