### ISSUE TITLE
[Bug] I installed the latest version of vs2022 (Preview 2.1), I created a new MAUI project, and found that it does not support hot reload, my computer system version is win10

### ISSUE THREAD

**Issue by yangkaikai2014** [dotnet/maui#1971]
I installed the latest version of vs2022 (Preview 2.1), I created a new MAUI project, and found that it does not support hot reload, my computer system version is win10

**Comment by drasticactions** [comment]
Hey @yangkaikai2014, if you could file this through [Visual Studio Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019#:~:text=In%20Visual%20Studio%2C%20choose%20the%20feedback%20icon%20in,How%20to%20report%20a%20problem%20with%20Visual%20Studio.), that would be very helpful. This way we can track the issue within Visual Studio and get better logging for your issue.
