### ISSUE TITLE
[Bug] vs2022 WPF not run

### ISSUE THREAD

**Issue by yangkaikai2014** [dotnet/maui#1972]
I installed the latest version of vs2022 (Preview 2.1). I created a new WPF project and found that it could not run. Compared with the WPF created by the vs2019 preview version (.net 6), I found that the output directory of the WPF program created by the vs2022 version does not have runtimeconfig. json file, my computer system version is win10

**Comment by PureWeen** [comment]
Can you log this issue here?
https://developercommunity.visualstudio.com/home

Or use the feedback tool that's part of Visual Studio?
