### ISSUE TITLE
Border is not displayed when inside a Frame in .net 8

### ISSUE THREAD

**Issue by ALJASAC** [dotnet/maui#19726]
### Description

We can find the detail description in here:
https://github.com/dotnet/maui/issues/19274#issuecomment-1879845136

### Steps to Reproduce

1. Create a new .net 8 maui application.
2. Wrap the CounterBtn in the default MainPage.xaml with a border.
3. Wrap the Border with a Frame.
4. Run the application.
5. The bug is shown, the frame covers the border and button.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by Vroomer** [comment]
Duplicate: https://github.com/dotnet/maui/issues/18755, https://github.com/dotnet/maui/issues/18526
