### ISSUE TITLE
Custom Font Not Loading on iOS in Blazor MAUI App (.net 8)

### ISSUE THREAD

**Issue by nethusan** [dotnet/maui#19734]
### Description

I'm working on a Blazor MAUI application and have encountered an issue with custom fonts. I've added the "Nunito-Regular.ttf" font file to my project, which loads correctly on Android but not on iOS devices.

Font File Placement: The font file is placed in the Resources\Fonts folder of the MAUI project.

**Build Action:** The build action for the font file is set to MauiFont.

Font Registration in MauiProgram.cs:
```
var builder = MauiApp.CreateBuilder();
builder
    .UseMauiApp<App>()
    .ConfigureFonts(fonts =>
    {
        fonts.AddFont("Nunito-Regular.ttf", "NunitoRegular");
    });
```
**Info.plist Configuration:**

Added the font file under UIAppFonts in the Info.plist:

```
<key>UIAppFonts</key>
<array>
    <string>Nunito-Regular.ttf</string>
</array>
```

**CSS Reference:**

Using the registered font name in CSS:

```
@font-face {
    font-family: 'NunitoRegular';
    src: local('NunitoRegular');
}

html, body {
    font-family: 'NunitoRegular' !important;
}
```

**Testing:** The issue persists even after cleaning and rebuilding the project. The font displays correctly on Android but not on iOS (tested on various devices and simulators).

**Questions:**

Is there a specific iOS consideration or step I might be missing?
Could the issue be related to the internal naming of the font file in iOS?
Are there known issues with custom fonts in Blazor MAUI apps on iOS?
Any insights or suggestions to resolve this issue would be greatly appreciated.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by drasticactions** [comment]
Could you please create a repro project showing this behavior? Having a deployable project would make it easier to debug with a shared codebase.

**Comment by Eilon** [comment]
Some things I wonder:

1. Does it happen with a regular WebView and HTML file, or is it specific to BlazorWebView?
2. There seem to be some challenges in general with getting custom fonts to work on iOS web views, but once you get past those challenges it should work: https://stackoverflow.com/questions/10490696/using-custom-font-in-a-uiwebview
