### ISSUE TITLE
publishing Blazor Hybrid MacCatalyst app removes +x on helper apps

### ISSUE THREAD

**Issue by MeestorX** [dotnet/maui#19741]
### Description

If I have an app that runs another app, it works fine within dotnet run, dotnet build, but when using dotnet pubish, the app installed from the .pkg file will have the +x attribute cleared on the helper app.
The helper app is contained in `Resources/Raw/Mac` within this project.

### Steps to Reproduce

Create a dotnet maui-hybrid project. Add a helper app and the appropriate changes to info.plist. `dotnet run` and `dotnet build` produce an app that the helper app will run, but `dotnet publish` does not.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS Catalyst

### Did you find any workaround?

Not yet, but probably an external packager would not have this issue.

**Comment by MeestorX** [comment]
1. Create the Blazor Hybrid sample project using `dotnet new maui-blazor`
2. Add an executable file to the `Resources\Raw` folder
3. `dotnet build -f:net8.0-maccatalyst` (remove android and ios targets if necessary from the `.csproj` so it only builds a maccatalyst app
4. Once built, Open terminal and open the .app file as a folder and go to the `Contents\Resources` folder
5. See if the executable flag is still there for the executable file you had added earlier. In my case, it was intact.
6. `dotnet publish -f:net8.0-maccatalyst`
7. Once built, find the .pkg file and double-click it to install the demo
8. Go to your `/Applications` folder and find the app
9. Open terminal and open the .app file as a folder and go to the `Contents\Resources` folder
10. The executable flag on the executable file will show as cleared. Test by trying `./name-of-exectuable`

**Comment by MeestorX** [comment]
@rolfbjarne I will send you a link to the project. It already includes the .app and .pkg files so if you like, you can simply try them without building if you like.

**Comment by MeestorX** [comment]
If this is not the "approved" way of adding helper apps, then please let me know. I couldn't find any documentation anywhere on the "right" way to add a helper executable to a .NET MAUI app for MacOS.

**Comment by rolfbjarne** [comment]
I think everything is working as expected, although it might be a bit unintuitive.

This are the attributes for the file in the project:

```shell
$ ls -la Resources/Raw/ngrok
-rwxr--r--@ 1 rolf  staff  26441052 Jan  8 16:36 Resources/Raw/ngrok
```

and these for the installed app:

```shell
$ ls -la /Applications/BlazorHybridTemplate.app/Contents/Resources/Mac/ngrok
-rwxr--r--@ 1 root  wheel  26441052 Jan  8 16:36 /Applications/BlazorHybridTemplate.app/Contents/Resources/Mac/ngrok
```

Note that the execute bit is the same: set for the owner, but for neither the group nor all other users.

The difference is that once the app is installed, it's owned by root - which means that only root can execute the executable once it's installed.

The fix is to add execute permissions to the file in the repository:

```shell
$ chmod +x Resources/Raw/ngrok
$ ls -la Resources/Raw/ngrok
-rwxr-xr-x@ 1 rolf  staff  26441052 Jan  8 16:36 Resources/Raw/ngrok
```

and then the file will be executable by everybody once it's installed.

Can you try this to see if it works for you?

**Comment by MeestorX** [comment]
That was it! Damn. I don't know how you figured that one out, but thank you!!
