### ISSUE TITLE
WebView control not loading document from the local file storage

### ISSUE THREAD

**Issue by DharunAR** [dotnet/maui#19743]
### Description

I am downloading my document details on local storage as .mhtml file and viewing from the WebView control, but the webview not displaying the document instead showing below error which refers access denied. Does i have to update the AndroidManifest.XML with any access permissions?

![image](https://github.com/dotnet/maui/assets/87979888/4308e8e8-cd98-4e43-b218-3e8b4252fb65)

### Steps to Reproduce

1. Create a sample MAUI app.
2. Download any document and store on your local android storage folder.
3. On any of the XAML page, add the below code as per screenshot.
![image](https://github.com/dotnet/maui/assets/87979888/bad69843-5bec-4029-8059-fc4ebc7ed4dd)
4. On the image above i have added my source file path, Please change the path.
5. Run the app and check the webview source is loading or not.

### Version with bug

7.0.49

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 and Android 13

### Did you find any workaround?

No. This issue happens only when loading local file. But the URL and other source is working as expected.

**Comment by DDHSchmidt** [comment]
That looks like you expect to be able to load files from totally different applications into your own application?
That would defy the application sandbox aka security concept of the underlying OS.

> Yes, this used to work in Xamarin.Forms

Somehow I doubt this... at least judging from the available description and screenshot 😅

You can only access/load files from below your application's storage directory or from publicly available URLs (if your device has a valid connection).
The easiest way would be to bundle html pages as Maui Assets during compile time.

You can search the issues in this repo or google around. There should be plenty of examples to get you started.

**Comment by jsuarezruiz** [comment]
Could you share the working Xamarin.Forms sample? Will be useful to compare and do some tests.
