### ISSUE TITLE
IDE Issue regarding Hot Reload

### ISSUE THREAD

**Issue by Legends** [dotnet/maui#19742]
### Description

VS Ent 17.8.3

When debugging my maui app and do simple xaml changes and after pressing Save I get the following message:

![image](https://github.com/dotnet/maui/assets/966368/dc7ba3d6-e578-4b21-a57e-ae50b2af7d00)

Nevertheless hot reload is working correctly and the changes are applied to the UI.
So I press "Esc" and I can continue to work.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by drasticactions** [comment]
The "Hot Reload" referred to by that window is for C# Hot Reload. It is unrelated to XAML Hot Reload, so my guess would be that there is something wrong with C# Hot Reload, and most likely unrelated to MAUI or anything in this repo.

This is Visual Studio functionality, it should be moved over there.

**Comment by Legends** [comment]
It happens in both cases XAML edit and C# edit
