### ISSUE TITLE
[Bug] Label text does not rendered correctly

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#1975]
### Description

I was created the stack layout to show list of label in vertical direction and the label vertical text alignment is center and vertical option is center but the label text does not rendered correctly.

### Steps to Reproduce

1. Place list of labels inside the stacklayout on vertical manner
2. Assign label vertical text alignment and vertical option as center
3. Label text not rendered correctly

### Expected Behavior

- Text align correctly based on alignment property

### Actual Behavior

- Text does not align correctly based on alignment property

**Comment by RemcoDEV** [comment]
Hi @Sasikumar3595 

VerticalTextAlignment is not yet implemented as you can see on the [status](https://github.com/dotnet/maui/wiki/Status) page.
![image](https://user-images.githubusercontent.com/23697539/128463493-dc886325-bdc9-4fe1-8a82-e41c2d46b837.png)

**Comment by jfversluis** [comment]
Thanks for the report! I see this issue is a little older by now. Please try the latest release and if you still encounter something that isn't working, please open a new issue with all the details. Thanks!
