### ISSUE TITLE
Directory.GetCurrentDirectory() resturns C:\\Windows\\system32

### ISSUE THREAD

**Issue by aurquiel** [dotnet/maui#19760]
### Description

Maui Blazor

I tried to use `Directory.GetCurrentDirectory();` to obtain the path of the current directory but Directory.GetCurrentDirectory() returns C:\\Windows\\system32

### Steps to Reproduce

1-Create a Blazor Maui Project
2- Create a buuton with @onclik event
3-In the fireing execute this code
` var path = Directory.GetCurrentDirectory();`
4. See that returns C:\\Windows\\system32

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

**Comment by drasticactions** [comment]
The "OnClick" handler is invoked in Web Assembly inside of the WebView. I don't believe this is specific to Blazor Hybrid apps, this is the behavior you would get on a Blazor WASM app in general, outside of MAUI. There is no "Current Directory" in this context, unless you've set one yourself.

If you want the location of the `wwwroot` folder on the local computer from within the WebView context, you would probably need to use:

```csharp
System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "wwwroot");
```

Or call back into your native application and use its System.IO constructs to do file operations.

Moreover, if it is a bug, it would probably be best handled by [dotnet/runtime](https://github.com/dotnet/runtime).

@mattleibow @Eilon what do you think?

**Comment by Eilon** [comment]
@drasticactions there's no WASM in Blazor Hybrid and none of the C# code ever runs in the browser in Blazor Hybrid. It's regular .NET code running in the same process as the rest of the .NET MAUI code, following whatever runtime it's on (.NET Core / Mono, with or without AOT, etc.).

In Windows the 'current directory' is generally set by whatever launched the program. If this is an installed Windows Packaged App then it could perhaps be that Windows itself leaves the 'current directory' _un-set_, which I think defaults to the system32 folder.

**Comment by Eilon** [comment]
Actually this happens in any .NET MAUI app on Windows, without even 'installing' it per se. I changed the default template code to this:

```c#
		private void OnCounterClicked(object sender, EventArgs e)
		{
			var path = Directory.GetCurrentDirectory();

			CounterBtn.Text = $"Current Directory is: {path}";
		}
```

And here it shows system32:

![image](https://github.com/dotnet/maui/assets/202643/0ee98bdb-8c26-44ff-afb8-3628e49ecf64)

Apps in general can't assume any particular current directory, because as I said earlier, whatever _launches_ the app gets to decide that (or just use the default). This is true on all Windows apps, and even going back to MS-DOS. Not sure about non-Windows platforms.

**Comment by aurquiel** [comment]
> ```cs
> System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "wwwroot");
> ```

thanks i use

System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "wwwroot");

as you suggested it work.
