### ISSUE TITLE
[Bug] TapGestures tapped event not trigged

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#1977]
### Description

I was created the custom layout or existing layout(grid, absolute layout) and add the tap gesture recognizer for the layout on backend(c#) but tapped event not triggered.

### Steps to Reproduce

1.  Create the custom layout or existing layout(grid, absolute layout) 
2. Add tap gesture recognizer on c#
3. Tapped event not triggered

### Expected Behavior

- Tap gesture tap event will be trigger

### Actual Behavior

- Tap gesture tap event will not trigger

### Code

```
class CustomLayout : Layout<View>
{
 public CustomLayout
{
TapGestureRecognizer tapGesture = new TapGestureRecognizer();
            tapGesture.Tapped += TapGesture_Tapped;
            this.GestureRecognizers.Add(tapGesture);
}

}
```

```
class CustomLayout : Layout<View>
{
Grid grid;
 public CustomLayout
{
grid = new Grid();
this.Add(grid);
TapGestureRecognizer tapGesture = new TapGestureRecognizer();
            tapGesture.Tapped += TapGesture_Tapped;
            grid.GestureRecognizers.Add(tapGesture);
}

}
```

**Comment by Sasikumar3595** [comment]
@PureWeen,

Any update on this?

Regards,
Sasikumar Arumugam.

**Comment by jfversluis** [comment]
Thanks for the report! I see this issue is a little older by now. Please try the latest release and if you still encounter something that isn't working, please open a new issue with all the details. Thanks!
