### ISSUE TITLE
Text property value does not change at runtime when using a style

### ISSUE THREAD

**Issue by RiyashameedM** [dotnet/maui#19772]
### Description

I have utilized a style for the label and bound its text property to a property in the ViewModel. Initially, I set the label's text value using the property in the ViewModel. Later, I changed its text property value by referencing it with a x:name in a button-clicked event. The text changed accordingly. and then, when I tried changing the binded property in the ViewModel using another button-clicked event, the text on the View did not update.

### Steps to Reproduce

1.Click the changeBinding button.
2.click set selecteditem button

Observed behavior 
Label Text was not changed after clicking the set selected item button.

Expected behavior
Label Text should be changed after clicking the set selected item button.

### Link to public reproduction project repository

https://github.com/RiyashameedM/Label_Text_issue

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

all platforms

### Did you find any workaround?

need to set binding for the label after the label.Text is updated.

**Comment by PureWeen** [comment]
`Later, I changed its text property value by referencing it with a x:name in a button-clicked event. `

AFAIK if you change the value manually that will remove the binding.

**Comment by RiyashameedM** [comment]
Hi @PureWeen ,
I have tested the issue with .NET 7, and I was not able to reproduce it. The issue only occurs in .NET 8.

**Comment by StephaneDelcroix** [comment]
the difference are the priorities
Bindings from Style have a lower priority than direct binding or SetValue (the 2 having the same priority, so you can change one for the other)
