### ISSUE TITLE
[Bug] Crash on WinUI application when using Line or other shapes on Preview 6. 

### ISSUE THREAD

**Issue by sheiksyedm** [dotnet/maui#1978]
### Description

WinUI app crashes when using Line or other shapes. 

### Steps to Reproduce

1. Add Line shape as in the below code. 

 ```
   <Grid>
        <Line X1="50" Y1="200" X2="350" Y2="200" Stroke="Red" StrokeThickness="10" />
    </Grid>

```
2. Target of an innovation exception thrown at runtime. 
3. Same code working fine in the Android platform. 

### Basic Information

- Version with issue:
     - IDE: Visual Studio 2022 Version 17.0.0 Preview 2.1
     - WinUI :  Target framework (net6.0-windows10.0.19041)
     - 
- NuGet Packages: Maui preview 6 NuGet.

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue with Preview 10. Let me know if you still have the issue and we can reopen it or open a new one.
