### ISSUE TITLE
Custom Title Bar Colors not working after migrating to .NET 8

### ISSUE THREAD

**Issue by stephansum** [dotnet/maui#19787]
### Description

With .NET 7 i was able to customize the title bar colors for my windows maui application like this:

```
<maui:MauiWinUIApplication.Resources>
    <ResourceDictionary>
        <SolidColorBrush x:Key="WindowCaptionBackground" Color="#0c0c0c" />
        <SolidColorBrush x:Key="WindowCaptionBackgroundDisabled" Color="Black" />
        <SolidColorBrush x:Key="WindowCaptionForeground" Color="#f2f2f2" />
        <SolidColorBrush x:Key="WindowCaptionForegroundDisabled" Color="White" />
    </ResourceDictionary>
</maui:MauiWinUIApplication.Resources>
```

After migrating to .NET 8 it seems like these dictionairy keys are no longer considered. I am just getting the default title bar appearance.

Note that iam using `ExtendsContentIntoTitleBar = false` in my scenario. When i try go with a fully customized title bar using `window.ExtendsContentIntoTitleBar = true`, i get a different problem already described here: https://github.com/dotnet/maui/issues/18773

I also tried to color my title bar using: 

```
<DataTemplate x:Key="MauiAppTitleBarTemplate">
    <Grid
        Canvas.ZIndex="1" 
        Background="#0c0c0c"
        VerticalAlignment="Stretch"
        Margin="0,0,0,0">
        <TextBlock 
            VerticalAlignment="Center"
            HorizontalAlignment="Left"
            Text="My App" 
            Foreground="#f2f2f2"
            FontWeight="Bold"/>
    </Grid>
</DataTemplate>
```

but i didnt find a way to change the foreground color of the system buttons (close, minimize etc)

Any tips/workarounds are appreciated until this is resolved.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

**Comment by Foda** [comment]
Hello! We have plans to provide more robust APIs for titlebar customization in the next major release, but for now you should be able to modify the titlebar foreground color by using:

`appWindow.TitleBar.ButtonForegroundColor`

**Comment by Yu-Core** [comment]
@stephansum 
I am using Windows 10 (.NET 8),   `appWindow.TitleBar.ButtonForegroundColor` is supported。
