### ISSUE TITLE
[Android] Crash removing item from CarouselView

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#19786]
### Description

Crash removing item from CarouselView.
![image](https://github.com/dotnet/maui/assets/6755973/41984dba-7ec8-40ad-bdbe-b8eff0210a00)
_NOTE: Using 8.0.5 RC1._

### Steps to Reproduce

1. Download or sync https://github.com/rachelkang/recipeSearch
2. Launch the App on Android.
3. Add a new recipe to your list.
4. Navigate back to your recipe list.
5. Select the added recipe and then tap the remove button.

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Relevant log output

```shell
0xFFFFFFFFFFFFFFFF in Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:13,5	C#
 	0x1D in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:27,26	C#
 	0x8 in System.ThrowHelper.ThrowArgumentOutOfRange_IndexMustBeLessException	C#
 	0x9 in System.Collections.Generic.List<object>.get_Item	C#
 	0x2 in System.Collections.Generic.List<object>.System.Collections.IList.get_Item	C#
 	0x11 in Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.ElementAt at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\ItemsSources\ObservableItemsSource.cs:228,5	C#
 	0x8 in Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.GetItem at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\ItemsSources\ObservableItemsSource.cs:67,4	C#
 	0x4F in Microsoft.Maui.Controls.Handlers.Items.MauiCarouselRecyclerView.SetCurrentItem at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\MauiCarouselRecyclerView.cs:456,4	C#
 	0xC in Microsoft.Maui.Controls.Handlers.Items.MauiCarouselRecyclerView. at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\MauiCarouselRecyclerView.cs:264,7	C#
 	0x6 in Microsoft.Maui.Dispatching.Dispatcher. at D:\a\_work\1\s\src\Core\src\Dispatching\Dispatcher.Android.cs:24,24	C#
 	0xE in Java.Lang.Thread.RunnableImplementor.Run at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36,6	C#
 	0x8 in Java.Lang.IRunnableInvoker.n_Run at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:84,4	C#
 	0x8 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:26,5	C#
```

**Comment by jsuarezruiz** [comment]
Can reproduce it also with 8.0.3.

**Comment by npostma** [comment]
Experiencing a déjà vu. Could this possibly be a form of regression? I'm uncertain about the extent to which the old Xamarin code is still in use. I am specifically referring to: https://github.com/xamarin/Xamarin.Forms/issues/14952

**Comment by RobTF** [comment]
+1 to this. Yet again blocked on bugs with CarouselView.

**Comment by dylix** [comment]
Just here so I can keep track of this.. Using the workaround at the moment...

**Comment by plppp2001** [comment]
> Just here so I can keep track of this.. Using the workaround at the moment...

What's the work around?  link please?

**Comment by plppp2001** [comment]
I'm getting this error every time when I'm Removing at item from my CarouselView Collection, this happens everytime on the Last item in the CarouselView. Not sure why:

`public ObservableRangeCollection<ReportCollection> UserReports { get; set; } = new();`

crashes when removing the last item like so:

`UserReports.Remove(reportToDelete);`      (on the last item in the collection for me only)

My setup:
VS2022: Version 17.9.5
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.14" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.14" />
<PackageReference Include="CommunityToolkit.Maui" Version="8.0.1" />
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />



Error:
System.ArgumentOutOfRangeException
  Message=Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

**Comment by dylix** [comment]
> > Just here so I can keep track of this.. Using the workaround at the moment...
> 
> What's the work around? link please?

https://github.com/xamarin/Xamarin.Forms/issues/14952#issuecomment-1027572321

i ended up just clearing my obvcollection before adding to it, and got rid of the errors for me

**Comment by plppp2001** [comment]
> > > Just here so I can keep track of this.. Using the workaround at the moment...
> > 
> > 
> > What's the work around? link please?
> 
> [xamarin/Xamarin.Forms#14952 (comment)](https://github.com/xamarin/Xamarin.Forms/issues/14952#issuecomment-1027572321)
> 
> i ended up just clearing my obvcollection before adding to it, and got rid of the errors for me

What about Removing an item from the collection for CarouselVIew?  

public ObservableRangeCollection<ReportCollection> UserReports { get; set; } = new();

Your doing this, by what you mean Clearing?

UserReports.Clear();  ?

**Comment by plppp2001** [comment]
I did this for now to be able to delete items from CarouselView on ANdroid using the "ObservableRangeCollection":

```
public ObservableRangeCollection<HistoryCollection> UserReports { get; set; } = new();  //this is for my CarsoueView Source on xaml page - shows 20 reports at one time I have a Load More reports button for the users for the carasouelview
private List<UserHistoryCollection> UserHistories = new();  //this hold like about 100 reports in memory filled up on PageLoad from HttpGet
```

```
//https://github.com/jamesmontemagno/mvvm-helpers
//Using MVVM CommunityToolkit.Mvvm  this is in the VM  just the code snippet for delete-------------------

   private async Task DeleteForAndroidWorkAroundBugAsync(UserHistoryCollection ReportToDelete)
    {
        UserHistories.Remove(ReportToDelete);

        int currentItemCount = UserReports.Count;

        if (UserReports.Any())
            UserReports.Clear();

        await Task.Delay(TimeSpan.FromSeconds(1)); //you need this here, stupid but it works for me anyways

        if (currentItemCount > 0)
        {
            if (UserHistories.Any())
            {
                UserReports.AddRange(UserHistories.Take(currentItemCount));
            }
            else
            {
                UserReports.Clear();
            }
                
        }
    }


```

**Comment by RobTF** [comment]
Ah, the old `await Task.Delay(..)` hack... a staple of a good MAUI "fix" ;)

@plppp2001 Your fix is astute and I've seen similar in other codebases, but if you're flushing the collection each time you can probably just get rid of `ObservableCollection` and just swap out the enumeration entirely as you're not getting any benefit from the observable functionality.

```c#
var newReports = UserReports.Except(x => x === toDelete);
UserReports = newReports;
```

**Comment by plppp2001** [comment]
> Ah, the old `await Task.Delay(..)` hack... a staple of a good MAUI "fix" ;)
> 
> @plppp2001 Your fix is astute and I've seen similar in other codebases, but if you're flushing the collection each time you can probably just get rid of `ObservableCollection` and just swap out the enumeration entirely as you're not getting any benefit from the observable functionality.
> 
> ```cs
> var newReports = UserReports.Except(x => x === toDelete);
> UserReports = newReports;
> ```

Thanks kind developer.

**Comment by dylix** [comment]
> Ah, the old `await Task.Delay(..)` hack... a staple of a good MAUI "fix" ;)

LOL

**Comment by plppp2001** [comment]
LOL you guys are hilarious.... haha I'll tell on you to jfversluis
