### ISSUE TITLE
O aplicativo não foi compilado

### ISSUE THREAD

**Issue by garrido273** [dotnet/maui#19814]
Quando tento executar o simples projeto em MIAU no visual studio do mac, aparece a mensagem "O aplicativo não foi compilado"

Problem encountered on https://dotnet.microsoft.com/pt-br/learn/maui/first-app-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by PureWeen** [comment]
Can you try the MAUI Extensions for VS Code?

https://devblogs.microsoft.com/visualstudio/announcing-the-dotnet-maui-extension-for-visual-studio-code/

Do you see the same issue?

**Comment by garrido273** [comment]
> Can you try the MAUI Extensions for VS Code?
> 
> https://devblogs.microsoft.com/visualstudio/announcing-the-dotnet-maui-extension-for-visual-studio-code/
> 
> Do you see the same issue?

I tested it in code and it worked normally. but in the code I was unable to see the changes made to the .xalm in real time. This greatly complicates my development in visual code.

**Comment by garrido273** [comment]
Some observations:

The error only occurs when debugging for Mac Catalyst.
iOS and Android worked normally.
I'm currently running on macos sonoma with m3 pro chip.
I successfully ran the debug for Mac Catalyst on a hackintosh that I had created with an Intel processor. (I don't know if it might have something to do with Silicons).
