### ISSUE TITLE
[Azure pipelines] Error XA5300: The Android SDK directory could not be found

### ISSUE THREAD

**Issue by DelcCorellia** [dotnet/maui#19829]
### Description

Since the latest update of the dotnet sdk, it became impossible for azure agents to build a maui application. 
This happened without any changes to the code, and someone else opened a [stackoverflow](https://stackoverflow.com/questions/77796319/maui-android-app-build-in-pipeline-failing-with-error-the-android-sdk-directory)

It seems that the failures happened with a minor version in dotnet (from 8.0.100 to 8.0.101) but even fixing a specific dotnet version doesn't help with the issue. 

The jump from 8.0.100 to 8.0.101 seem to coincide with the Microsoft.Android.Sdk.Linux version going from 34.0.65 to 34.0.66, but I haven't been able to use the version 34.0.65 on an agent (version not found).

### Steps to Reproduce

-Have a maui version 8.0.3 application with TargetFramework net8.0-android

-Trigger a build in a pipeline

-The agent can't find the android SDK

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

Android

### Relevant log output

```shell
##[error]/opt/hostedtoolcache/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.66/tools/Xamarin.Android.Tooling.targets(70,5): Error XA5300: The Android SDK directory could not be found. Install the Android SDK by following the instructions at: https://aka.ms/dotnet-android-install-sdk
To use a custom SDK path for a command line build, set the 'AndroidSdkDirectory' MSBuild property to the custom path.
```

**Comment by BFuchshofer** [comment]
I had the same issue. I didn't invest further, but the workaround for me was to add the "AndroidSdkDirectory" environment variable to my build server and set the Android SDK manually, as suggested in your attached output log. However, we use our own hosted server. I don't know if this will work on Azure agents.

**Comment by jfversluis** [comment]
This might be due to this announcement here: https://github.com/actions/runner-images/issues/8952

> Old versions of Android SDK & tools will be removed from images on January, 8

There are also suggestions in there on how to fix it. Unfortunately, there is nothing we can do about this from our side.
