### ISSUE TITLE
[Bug] Navigating to the second page on App doesn't render any content until you switch tabs

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1983]
### Description
CollectionViewRenderer not rendering with a height on initial load when navigated to

### Steps to Reproduce

1. switch to branch `recipes`
2. Run the Single project samples
3. Click on any of the recipes buttons (it takes a really long time to load the second page the first time. Just wait for it)
4. At this point the page is blank
5. click on the "My recipes Tab" and then click back
6. Now it shows up

Using Layout inspector you can see that the CollectionViewRenderer has a height of zero

![image](https://user-images.githubusercontent.com/5375137/128541213-e01d907d-2221-433c-aab7-2bf9cda248fd.png)

### Expected Behavior
You should see a grid of recipe results

### Actual Behavior
The page is blank

**Comment by jfversluis** [comment]
Did we verify this is fixed? @hartez ?
