### ISSUE TITLE
[Bug] Cannot dynamically add control to an existing StackLayout with Windows.

### ISSUE THREAD

**Issue by Zachael** [dotnet/maui#1985]
### Description
Cannot dynamically add control to an existing StackLayout with Windows.

### Steps to Reproduce

**MainPage.xaml**
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Test.DCF_UX.MSTest.Tests.MainPage"
             xmlns:controls="clr-namespace:Dell.Client.Framework.UX.Controls.Xaml.Controls;assembly=DCF.UXControlsXamlLib"
             BackgroundColor="{DynamicResource PageBackgroundColor}">

    <StackLayout>
        <Button Text="Click me" Clicked="OnClicked"/>
    </StackLayout>
    
</ContentPage>

**MainPage.xaml.cs**

    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }
        
        private void OnClicked(object sender, EventArgs e)
        {
            var stackLayout = Content as StackLayout;
            var layoutPanel = stackLayout.Handler.NativeView as LayoutPanel;

            var count = stackLayout.Children.Count; // 1
            var nativeCount = layoutPanel.Children.Count; // 1

            stackLayout.Add(new Picker());

            count = stackLayout.Children.Count; // 2
            nativeCount = layoutPanel.Children.Count;   // 1
        }
    }

### Expected Behavior
Expected the nativeCount to be 2 after adding new Picker to StackLayout.

### Actual Behavior
The count is still 1 and the Picker does not display.

### Basic Information

- Version with issue: Maui preview 6 (workload)
- Last known good version: Maui preview 5
- IDE: VS Enterprise 2022 Preview (64-bit) Version 4.8.03752
- Platform Target Frameworks:
  - UWP:  net6.0-windows10.0.19041
- Affected Devices: Windows

**Comment by hartez** [comment]
This was fixed by #1944
