### ISSUE TITLE
RoundRectangle Border is messed up when contains an Image with AspectFill

### ISSUE THREAD

**Issue by ShariatPanah** [dotnet/maui#19877]
### Description

so when you put an image inside of a Border with RoundRectangle set to it, the border itself in the corners doesn't show up correctly, let me show a screenshot:
![image](https://github.com/dotnet/maui/assets/32509267/01a5cc42-800d-44f3-964c-c82dc5b54bc5)
and this is my xaml code:
```
<Border
    HeightRequest="250"
    StrokeShape="RoundRectangle 40"
    StrokeThickness="2"
    Stroke="#e8ff8e"
    WidthRequest="100">
    <Image Source="{Binding Image}" />
</Border>
```

when i set the StrokeThickness to a large value like 20 the result is interesting, there is no curved border:
![image](https://github.com/dotnet/maui/assets/32509267/0bae3138-d944-4ea7-bdea-390b91bf745f)

this behavior is just on Android, i tested with windows and it seems to work fine on small StrokeThickness but with a large value it would do a strange behavior too :)
with small StrokeThickness on Windows:
![image](https://github.com/dotnet/maui/assets/32509267/f352b195-98ba-4ab7-94d9-39cc2455149c)

with a large value, there you can see a gap between the border and the image:
![image](https://github.com/dotnet/maui/assets/32509267/5bb965e9-b45d-4b1c-89ad-a04c0ea536e8)

in fact with a small StrokeThickness you can also see the gap, but its barely visible.
didn't test on iOS so i don't know about it.

### Steps to Reproduce

Just put an AspectFill Image inside of a Border and set the StrokeShape to RoundRectangle with some CornerRadius

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.0

**Comment by ShariatPanah** [comment]
Every single one of bugs i report here, immediately would be added to the backlog, is there anyone working on maui really? Do you need some hands fellas?

**Comment by XamlTest** [comment]
[BorderMessed.zip](https://github.com/dotnet/maui/files/14341021/BorderMessed.zip)

**Comment by kubaflo** [comment]
Hi! Fixed here: https://github.com/dotnet/maui/pull/21250
<img src="https://github.com/dotnet/maui/assets/42434498/1cc8fd93-bd3c-4e66-bd93-a9671ee87c60" width="300px"/>
