### ISSUE TITLE
[Grid] Using Grid.Resources inside Grid (e.g. for Buttons, Labels, ...) with just some Properties set (e.g. HorizontalOptions or TextAlignment) overwrites global Style entirely

### ISSUE THREAD

**Issue by MAUIoxo** [dotnet/maui#19882]
### Description

When using Grid.Resources like in the example below the default Style and Coloring for Buttons defined in the global **Styles.xaml** get overwritten. Not only the properties that are set in the Grid.Resources (e.g. HeightRequest), but the entire Styling.

Tried it with the **Nightly Build:** "**8.0.6-nightly.9863**"

```xaml
<Grid ColumnDefinitions="Auto, Auto" ColumnSpacing="5" HeightRequest="35" Margin="20" HorizontalOptions="End">

    <Grid.Resources>
        <Style TargetType="Button">
            <Setter Property="FontAutoScalingEnabled" Value="True" />
            <Setter Property="HeightRequest" Value="35" />
            <Setter Property="WidthRequest" Value="105" />
            <Setter Property="Padding" Value="15, 7, 15, 10" />
        </Style>
    </Grid.Resources>

    <Button Grid.Column="0" Text="{loc:Translate CancelButtonText}" Command="{Binding CancelFoodItemCommand}" />
    <Button Grid.Column="1" Text="{loc:Translate OKButtonText}" Command="{Binding SaveFoodItemCommand}"  />

</Grid>
```

### Steps to Reproduce

1. Have your own Color for a Button that is set in the global Styles.xaml to see the difference

![grafik](https://github.com/dotnet/maui/assets/140683727/f279d440-701d-4901-9ea4-537d0eb6b759)

2. Define a Grid.Resource just for Buttons within a Grid as in the example Code above
3. Use some Properties that do not overwrite the default Coloring you specified for Buttons (e.g. a HeightRequest Property)
4. See that the Color you specified in Styles.xaml is overwritten by that

![grafik](https://github.com/dotnet/maui/assets/140683727/97c56fc0-4dec-4634-9840-100d09e21f1c)

### Version with bug

8.0.6-nightly.9863

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS, Android

### Did you find any workaround?

Yes, just use a Resource in the ContentPage and using that Style will not overwrite the default Style then:

```xaml
<ContentPage.Resources>
    <ResourceDictionary>
        <Style x:Key="GridButton" TargetType="Button">
            <Setter Property="FontAutoScalingEnabled" Value="True" />
            <Setter Property="HeightRequest" Value="35" />
            <Setter Property="WidthRequest" Value="105" />
            <Setter Property="Padding" Value="15, 7, 15, 10" />
        </Style>
    </ResourceDictionary>
</ContentPage.Resources>
```

```xaml
<Grid ColumnDefinitions="Auto, Auto" ColumnSpacing="5" HeightRequest="35" Margin="20" HorizontalOptions="End">

	<Button Grid.Column="0" Text="{loc:Translate CancelButtonText}" Command="{Binding CancelFoodItemCommand}" Style="{StaticResource GridButton}" />
	<Button Grid.Column="1" Text="{loc:Translate OKButtonText}" Command="{Binding SaveFoodItemCommand}"  Style="{StaticResource GridButton}" />

</Grid>
```

![grafik](https://github.com/dotnet/maui/assets/140683727/f279d440-701d-4901-9ea4-537d0eb6b759)

**Comment by MAUIoxo** [comment]
I don't want to be "pushy" - but this is a topic regarding `Grid`. `Grid` in general is very critical to me as it is used very often and needed in several places in our daily work as developers.

When I look on things that have been fixed at last, it wasn't what I'd consider "main things" that really burn under our nails regarding what we developers deal with in our daily business. Question is if this or `Grid` Issues in general could be ranked higher in the Backlog? As I said, I don't want to push necessarily, but just mention what things are more important.

Regarding this Bug, I know there is a workaround. But, considering the workaround it means several places underneath a `Grid` where we have to resolve the `Grid.Resources` and move it up and higher to the `ContenView.Resources` and add `Style` declarations for every Control (e.g. a `Label` underneath the `Grid` that needs a `HorizontalOption` or whatever was declared with it). This is a lot of rework and needed for every control to have this workaround applied

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12.0 Preview 3( 8.0.92 &8.0.82 & 8.0.6). Not repro this issue on iOS and android platforms.
If you also repro this issue, could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
![Image](https://github.com/user-attachments/assets/07436805-2fd4-42bf-ac31-f93092885f51)
