### ISSUE TITLE
[iOS] error MAUI0000: System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#19899]
### Description

After several VS updates I decided to publish my app again. Android => works. On iOS (I paired VS with my Mac before and it has updated everything) I get really weird errors like this one:

```
Microsoft.Maui.Resizetizer.targets(531,9):
 error MAUI0000: System.MissingMethodException: Method not found: 'SkiaSharp.SKTextBlob SkiaSharp.SKTextBlob.CreatePosi
tioned(System.String, SkiaSharp.SKFont, System.ReadOnlySpan`1<SkiaSharp.SKPoint>
```

Note this is a **.NET 7.0** app.

I searched for it but people say I should update Skia. But I dont have any Skia nuget package so dunno?!

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Relevant log output

```shell
maui-windows                  8.0.3/8.0.100          VS 17.9.34407.89
ios                           17.0.8490/8.0.100      VS 17.9.34407.89
android                       34.0.52/8.0.100        VS 17.9.34407.89
maccatalyst                   17.0.8490/8.0.100      VS 17.9.34407.89

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]
  6.0.126 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by kxgonzalez** [comment]
I'm still facing this issue in a new project.
How did you resolved it?
I had to convert the svgs to pngs

**Comment by Symbai** [comment]
I simply had to connect to my macbook with VS and VS then updated all the tools on my macbook. Found this solution after googling the issue.
