### ISSUE TITLE
[Android] ResfreshView IsEnabled not working

### ISSUE THREAD

**Issue by roubachof** [dotnet/maui#19897]
### Description

When set to `IsEnabled=false`, the `RefreshView` is still enabled (you can still pull to refresh).
It was working in .net 6 (last time I tested the sharpnado's collection view sample).

### Steps to Reproduce

Launch the Maui sample from the collection view repo:
https://github.com/roubachof/Sharpnado.CollectionView
Go to the 'Layout examples' `->` 'Vertical'.
Enable Drag and Drop.
Try to drag and drop toward the bottom.
A refresh is toggled.

**GridPage.xaml**

```xml
<RefreshView
    Command="{Binding SillyPeopleLoaderNotifier.RefreshCommand}"
    IsClippedToBounds="False"
    IsEnabled="{Binding Source={x:Reference DragAndDropSwitch}, Path=IsToggled, Converter={converters:NotConverter}}"
    IsRefreshing="{Binding SillyPeopleLoaderNotifier.ShowRefresher}"
    RefreshColor="{StaticResource Accent}">
```

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

Android

**Comment by acaliaro** [comment]
there are some news about this?

**Comment by kubaflo** [comment]
@acaliaro @roubachof This issue seems to be resolved on the latest main branch

https://github.com/dotnet/maui/assets/42434498/b89016e9-264a-4e99-89f7-509f0628a635

**Comment by kubaflo** [comment]
> @acaliaro @roubachof This issue seems to be resolved on the latest main branch
> 
>  Screen.Recording.2024-02-04.at.12.59.11.mov

It actually doesn't work when RefreshView has a command assigned

**Comment by LeoJHarris** [comment]
`RefreshView` that has a Command prevents Scrolling and breaks all child tap gestures as well. In addition, setting `IsEnabled` True on `RefreshView` makes no difference if a RefreshView has Command attached.

**Comment by LeoJHarris** [comment]
As a work around for anyone looking, the following component resolved my issues: https://github.com/MPowerKit/VirtualizeListView/blob/main/MPowerKit.VirtualizeListView/FixedRefreshView.cs
