### ISSUE TITLE
[Bug] [Android] Grid does not size correctly until a few moments after initial render

### ISSUE THREAD

**Issue by alexkblount** [dotnet/maui#1992]
When displaying a grid, the un-sized version is displayed initially before correctly sizing and popping to its position.

net 6.0 version 6.0.100-rc.1.21403.66

### Video

https://user-images.githubusercontent.com/30159621/128590614-e43ae063-9dfd-4642-afbf-e27b693a0667.mp4

### Reproduction Link

https://github.com/alexkblount/maui-samples

**Comment by hartez** [comment]
This was fixed incidentally by #2265 (specifically by commit https://github.com/dotnet/maui/pull/2265/commits/df6fd4686d846551cca76d8a70ab83996db5c3f6.)
