### ISSUE TITLE
Opacity bug on BoxView.Background

### ISSUE THREAD

**Issue by ShariatPanah** [dotnet/maui#19926]
### Description

when i set the background of a boxview to a linear gradient brush, the opacity works on hotreload but when i stop the application and rerun it, the opacity would be ignored like it was never been set, this is my xaml code:
```
        <BoxView
            HeightRequest="200"
            Opacity="0.3"
            WidthRequest="150">
            <BoxView.Background>
                <LinearGradientBrush StartPoint="0,0" EndPoint="0,1">
                    <GradientStop Offset="0.4" Color="Transparent" />
                    <GradientStop Offset="1" Color="Black" />
                </LinearGradientBrush>
            </BoxView.Background>
        </BoxView>
```

### Steps to Reproduce

Just create a box view using my code snippet

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.0

**Comment by ShariatPanah** [comment]
i tested on windows and boxview opacity works as expected, so apparently it's android handler of boxview bug

**Comment by maxiking01** [comment]
I confirm that problem with BoxView's Opacity appears on Android. On iOS and Windows opacity is applied correctly. I tested  on .Net 8.0.1 .

**Comment by returnZro** [comment]
Is there any work-around for this?

**Comment by awasilik** [comment]
I can observe the same issue in my application. 
There is a workaround but it's unacceptable for me - I need to set the opacity manually from code after the view is rendered.

**Comment by XamlTest** [comment]
Verified this on 8.0.6. Repro on Android 14.0-API34, not repro on Windows, iOS 17.2 and MacCatalyst with below Project:
[OpacityIssue.zip](https://github.com/dotnet/maui/files/14444613/OpacityIssue.zip)

**Comment by kubaflo** [comment]
@awasilik @ShariatPanah this pr might help :) https://github.com/dotnet/maui/pull/21322
