### ISSUE TITLE
[Bug] BlazorWebview app shows only blank page

### ISSUE THREAD

**Issue by AmirImam** [dotnet/maui#1993]
### Description
Hi
I have created empty MAUI Blazor app without any additional code. When I run the app on android it shows blank page in BlazorWebView. Any element in XAML shows up correctly, but HTML code in razor files not appears
SDKs list
![image](https://user-images.githubusercontent.com/26382843/128592602-c455a3d7-569a-4614-8b21-134292ae1f52.png)

maui-check not working and it shows error in the image
![image](https://user-images.githubusercontent.com/26382843/128592628-ab55df54-6864-4aa7-895d-67ec8e4b543c.png)

Workload list
![image](https://user-images.githubusercontent.com/26382843/128592640-3f5e3fba-6410-4504-8592-d1f0b7937ab9.png)

SDK check
![image](https://user-images.githubusercontent.com/26382843/128592642-95c127e7-5b26-4a16-be33-a43b012766b6.png)

Repository for the project
https://edenamir.visualstudio.com/_git/EmptyMauiApp

So what is the problem in that ?
thank you

**Comment by Eilon** [comment]
Hi @AmirImam , I think we've fixed several bugs since the preview 6 release that you're using so this issue might have been fixed. We released preview 7 a while ago that might have this fix: https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-7/

**Comment by alexfdezsauco** [comment]
Hi I'm running in the same issue with the preview 7. 

## Environment

    $ dotnet --list-sdks
    3.0.101 [C:\Program Files\dotnet\sdk]
    3.1.103 [C:\Program Files\dotnet\sdk]
    3.1.302 [C:\Program Files\dotnet\sdk]
    3.1.403 [C:\Program Files\dotnet\sdk]
    5.0.101 [C:\Program Files\dotnet\sdk]
    5.0.201 [C:\Program Files\dotnet\sdk]
    6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

    $ maui-check
    .NET MAUI Check v0.8.6.0
    ...
    > .NET SDK Checkup...
    - 3.0.101 - C:\Program Files\dotnet\sdk\3.0.101
    - 3.1.103 - C:\Program Files\dotnet\sdk\3.1.103
    - 3.1.302 - C:\Program Files\dotnet\sdk\3.1.302
    - 3.1.403 - C:\Program Files\dotnet\sdk\3.1.403
    - 5.0.101 - C:\Program Files\dotnet\sdk\5.0.101
    - 5.0.201 - C:\Program Files\dotnet\sdk\5.0.201
    - 6.0.100-preview.7.21379.14 - C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14
    
    > .NET SDK - Workload Deduplication Checkup...
    
    > Edge WebView2 Checkup...
    - Found Edge WebView2 version 93.0.961.44
    
    > .NET SDK - Workloads (6.0.100-preview.7.21379.14) Checkup...
    - android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 30.0.100-preview.7.110) installed.
    - ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-preview.7.230) installed.
    - maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-preview.7.230) installed.
    - tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-preview.7.230) installed.
    - macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-preview.7.230) installed.
    - maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-preview.7.1345) installed.
    - wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-preview.7.21377.19) installed.
    - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-preview.7.21377.2) installed.


![image](https://user-images.githubusercontent.com/1785664/132934583-923bd0bd-a52a-4a10-b60d-cb4e31e9ab8b.png)


## Running App

![image](https://user-images.githubusercontent.com/1785664/132934395-d727ee31-b204-45a4-97e5-35673c6fb29d.png)

**Comment by alexfdezsauco** [comment]
It works with API Level 30.

**Comment by wmeints** [comment]
Same here, experiencing the exact issue on API level 29.
