### ISSUE TITLE
Adding a Connectivity.ConnectivityChanged handler does not work on Android 14

### ISSUE THREAD

**Issue by mikeluken** [dotnet/maui#19949]
### Description

When targeting Android 14, the following event is never triggered when toggling Wi-Fi on/off:

```Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged;```

### Steps to Reproduce

Create a new MAUI app targeting Android 14 (SDK 34).  As of now, you will need to use the nightly releases because you can't use a ConnectivityChanged event with 8.0.3 while targeting SDK 34 or you will get an error.

In App.xaml.cs (in App constructor), add the following:

```
Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged;
```

```
private async void Connectivity_ConnectivityChanged(object sender, ConnectivityChangedEventArgs e)
{
    Console.WriteLine("Hitting here");
}
```

When toggling on/off wifi, the event is never triggered when targeting Android 14.  It works fine if targeting Android 13.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

Target SDK 33 (Android 13)

**Comment by Redth** [comment]
Fixed by #19968
