### ISSUE TITLE
RadioButton TextColor doesn't change iOS/MacCatalyst 

### ISSUE THREAD

**Issue by olenavasylchak** [dotnet/maui#19943]
### Description

I add simple RadioButton in my .NET MAUI project and set TextColor="Red"
            <RadioButton Content="My RadioButton" TextColor="Red"/>
But color doesn't change, it remains the same(Black iOS and White MacCatalyst).
I have tested it on iOS and MacCatalyst platforms. 

### Steps to Reproduce

-Create new .NET MAUI app
-Add simple RadioButton control and set some TextColor for it
            <RadioButton Content="My RadioButton" TextColor="Red"/>
-Run the app(iOS/MacCatalyst)
-Observe the bug.

### Version with bug

8.0.5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 17.0

### Did you find any workaround?

No workaround found.

**Comment by olenavasylchak** [comment]
<img width="1512" alt="Знімок екрана 2024-01-17 о 14 50 42" src="https://github.com/dotnet/maui/assets/31761497/2283572a-194e-4088-80d3-0f22a98da91c">
<img width="789" alt="Знімок екрана 2024-01-17 о 14 51 31" src="https://github.com/dotnet/maui/assets/31761497/66bdb910-2910-46f3-8c68-64735486ec26">
![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-17 at 14 51 26](https://github.com/dotnet/maui/assets/31761497/d4788a52-4aba-4ae1-bd5d-d5c32b5da327)

**Comment by kubaflo** [comment]
This issue has already been fixed on the main branch
<img src="https://github.com/dotnet/maui/assets/42434498/c0c8f05c-cc05-4c20-8fb5-08d60204988c" width="300px"/>

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio for mac 17.6.10(build428). Can not repro this issue with maccatalyst/iOS platforms.(MauiVersion:8.0.14/8.0.7)

**Comment by dustin-wojciechowski** [comment]
Am currently able to change text color in main currently on ios/maccatalyst (pic from another recent radiobutton issue)
![Simulator Screenshot - iPhone 15 - 2024-05-13 at 16 28 24](https://github.com/dotnet/maui/assets/89540402/7e77479e-521b-4d5b-b453-eead667572cc)
