### ISSUE TITLE
Blazor Isolated CSS in Razor Component Library Ignored

### ISSUE THREAD

**Issue by marqdouj** [dotnet/maui#1995]
### Discussed in https://github.com/dotnet/maui/discussions/1968

<div type='discussions-op-text'>

<sup>Originally posted by **marqdouj** August  5, 2021</sup>
I've created a new Maui-Blazor app with the latest templates and added a razor class library.
When I add an isolated *.css file to a razor component in the class library the css is ignored. If I copy the css to the app.css file it works fine.
Is this by design?
</div>

**Comment by Eilon** [comment]
Hi @marqdouj thank you for reporting the issue. This was a bug and will be fixed in the upcoming preview 7 release.

**Comment by 3DSX** [comment]
@marqdouj 
Could you try to add this to your index.html?
`<link href="_content/ProjectName/ProjectName.bundle.scp.css" rel="stylesheet" />`

**Comment by keeperman159** [comment]
Had the same issue on 6.0.100-rc.1.21458.32 but changed the Build Action from MauiCss to Content and it worked.


Unrelated but does anyone know how to access WinUICoreWebView2SettingsWrapper or similar? Need to enable the context menu while debugging
