### ISSUE TITLE
Flyout doesn't load the page after navigating back

### ISSUE THREAD

**Issue by juniorsaraviao** [dotnet/maui#19955]
### Description

I'm implementing a Flyout page and I realize the page is not loaded after navigating back (it shows an empty page) on Android. It looks ok on iOS.

The Flyout xaml is the following:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<FlyoutPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiFlyout.MainFlyout"
             Title="MainFlyout"
            xmlns:pages="clr-namespace:MauiFlyout">
    <FlyoutPage.Flyout>
        <pages:MainFlyoutMenu x:Name="FlyoutPage"/>
    </FlyoutPage.Flyout>
    <FlyoutPage.Detail>
        <NavigationPage>
            <x:Arguments>
                <pages:FirstPage/>
            </x:Arguments>
        </NavigationPage>
    </FlyoutPage.Detail>
</FlyoutPage>
```

| Android |
| ------------- |
| <video src="https://github.com/juniorsaraviao/MainFlyout/assets/43689290/a73ccf7b-9adf-4cb4-9fa2-1c041ad195ac" width=180 height=392> |

### Steps to Reproduce

1. Clone the project [link](https://github.com/juniorsaraviao/MainFlyout/tree/master).
2. Execute on Android simulator or physical devices.
3. Tap Navigate to Second page button.
4. Tap Return to the Start page button.
5. After navigating back, the Flyout page will show a blank page.

### Link to public reproduction project repository

https://github.com/juniorsaraviao/MainFlyout/tree/master

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and above

### Did you find any workaround?

No

### Relevant log output

```shell
-
```

**Comment by kraemernet** [comment]
You need to change

MainPage = new NavigationPage(new MainFlyout()); to
MainPage = new MainFlyout();

Application.Current.MainPage.Navigation.PopAsync(); to 
Navigation.PopAsync();

Application.Current.MainPage.Navigation.PushAsync(new SecondPage()); to
Navigation.PushAsync(new SecondPage());

**Comment by holesnap** [comment]
@jsuarezruiz @juniorsaraviao  Hi :) any update on this bug? it affects our app too

**Comment by XamlTest** [comment]
Verified this on 8.0.6. Repro on Android 14.0-API34, not repro on Windows 11, iOS 17.2 and MacCatalyst with below Project:
[MainFlyout.zip](https://github.com/dotnet/maui/files/14455662/MainFlyout.zip)

**Comment by Nambukarthy** [comment]
Any updates regarding this issue? I am facing this issue too in the Android devices. 

I cannot use the shell page because my project features a tabbed page, which is currently not supported by the shell page.

I also can't make the flyout page a root page (MainPage = new MainFlyout()) because my detail page shouldn't be part of the flyout page, so the flyout page inside the navigation page (MainPage = new NavigationPage(new MainFlyout()) only suits our requirement.

**Comment by mflplatinum** [comment]
> Any updates regarding this issue? I am facing this issue too in the Android devices.

I'd love to hear any updates as well!

There are multiple, significant bugs with FlyoutPage on Android that have been open for months with no progress, so I can't hold out hope that they'll be fixed anytime soon. 

I've spent several days looking for a workaround or alternative, and outside of coding my own flyout page logic I don't see a good solution. I'm looking at removing FlyoutPage entirely and using modals to display what used to be in the Flyout. Shell's Flyout is very different and doesn't allow much flexibility.

**Comment by PureWeen** [comment]
It looks like some overlapping animations on the android side when you have nested navigationpages is causing the opacity of the page to get stuck at zero. 

In the attached sample if I just add this to the `FirstPage` it starts working for me

```C#
public partial class FirstPage : ContentPage
{
	public FirstPage()
	{
		InitializeComponent();
		this.Loaded += (s, e) =>
		{
			this.Handler?.UpdateValue(nameof(IView.Opacity));
		};
	}

    private void Button_Clicked(object sender, EventArgs e)
    {
		Application.Current.MainPage.Navigation.PushAsync(new SecondPage());
    }
}
```
