### ISSUE TITLE
StackLayout/Grid adds extra padding when there's a Border inside

### ISSUE THREAD

**Issue by juniorsaraviao** [dotnet/maui#19958]
### Description

I'm adding a Border inside a StackLayout/Grid but it looks like it adds internal padding.

Border
<table>
  <tr>
     <td>Android</td>
     <td>iOS</td>
  </tr>
  <tr>
    <td><img src="https://github.com/juniorsaraviao/BorderSample/assets/43689290/541002c9-e0ef-460c-a845-57ee52328842" width=400 height=800></td>
    <td><img src="https://github.com/juniorsaraviao/BorderSample/assets/43689290/8514cfd6-092e-4513-b88e-41cddfcca38a" width=400 height=800></td>
  </tr>  
 </table>

Xaml code:

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="BorderSample.MainPage"
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="False">

    <StackLayout IgnoreSafeArea="True"
                 BackgroundColor="Orange"
                 VerticalOptions="FillAndExpand">

        <Border BackgroundColor="Blue"
                VerticalOptions="EndAndExpand"
                StrokeShape="RoundRectangle 40,40,0,0"
                Margin="0,-25,0,0"
                HeightRequest="300"/>

        <!--<StackLayout BackgroundColor="Blue"
                     VerticalOptions="EndAndExpand"
                     Margin="0,-25,0,0"
                     HeightRequest="300"/>-->
    </StackLayout>

</ContentPage>
```

### Steps to Reproduce

1. Clone the project [link](https://github.com/juniorsaraviao/BorderSample/tree/master).
2. Run on simulators or physical devices (Android and iOS).

### Link to public reproduction project repository

https://github.com/juniorsaraviao/BorderSample/tree/master

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11 and above, iOS 15.2 and above

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@juniorsaraviao if you set the StrokeThickness to zero does that go away?

**Comment by juniorsaraviao** [comment]
@PureWeen I just tested it setting StrokeThickness to zero and the extra padding disappeared on both platforms. Thanks 👍
