### ISSUE TITLE
Maui Nightly Android 34 - Connectivity.ConnectivityChanged doesnt get fired

### ISSUE THREAD

**Issue by Zack-G-I-T** [dotnet/maui#19975]
### Description

Using the nightly build 8.0.6-nightly.9880 we no longer get the exception on Android 34
"Java.Lang.SecurityException - One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED..."

However, the ConnectivityChanged event never gets fired. This works on lower versions of android.
I tried this using the Connectivity page on the recommended PlatformIntegration repo which is linked below.

### Steps to Reproduce

1. Open the linked solution
2. Go to connectivity page and put breakpoint on the  PlatformIntegrationDemo.ViewModels.ConnectivityViewModel.OnConnectivityChanged method
3. Turn off internet - breakpoint never gets hit.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/8.0/PlatformIntegration

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Never worked on Android 34

### Affected platforms

Android

**Comment by PureWeen** [comment]
Duplicate of #19949
