### ISSUE TITLE
[Bug] HTML TextType on Label does not render HTML as elements

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#1998]
### Description

When using `<Label TextType="Html"/>` the label does not render the HTML elements as Native elements. This previously worked on Xamarin.Forms.

### Steps to Reproduce

1. Create a Label
2. Set the text to a valid HTML string.

### Expected Behavior

The content for the label would render the HTML contents as native elements.

### Actual Behavior

The label renders the raw text.

Xamarin.Forms Implementation
![1](https://user-images.githubusercontent.com/898335/128615610-71d5f839-4752-4dc5-a9d8-6eedf3de431b.PNG)

MAUI Implementation
![2](https://user-images.githubusercontent.com/898335/128615612-1d8fad92-519d-46b6-80d3-15b4f20ece4f.PNG)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by GalaxiaGuy** [comment]
A PR to implement `TextType` is still unmerged: https://github.com/dotnet/maui/pull/976

There is also a plan for changing the way this would be set (although I think a compatibility shim maybe added to make the old way still work): https://github.com/dotnet/maui/issues/1082
