### ISSUE TITLE
Calling API method to retrieve byte array fails in MAUI Android app

### ISSUE THREAD

**Issue by darutter0508** [dotnet/maui#19980]
### Description

I have a .NET 7.0 MAUI app that calls an API to retrieve a byte array of a file. The call completes correctly when the iOS version of the app executes, but fails to come back from the call when executed in the Android version of the same app.

### Steps to Reproduce

Create a MAUI app using .NET 7.0
Create page that has a button whose event handler makes a call to retrieve byte array from API
Execute app and press button
When run in iOS, call success and process continues 
When run in Android, call never returns and app eventually times out

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 10 and up

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@darutter0508 can you also test on .NET 8?

**Comment by darutter0508** [comment]
trying to get a sample project to submit to show issue
