### ISSUE TITLE
Launch and Debug for Mac Catalyst from Visual Studio Code succeeds but does not launch app

### ISSUE THREAD

**Issue by soshay1** [dotnet/maui#19985]
### Description

I have not been able to successfully debug my Mac Catalyst app on Visual Studio Code on Mac.
This command generated by VS Code when pressing F5 does not launch the app:
`dotnet build -t:Build -p:Configuration=Debug -f net8.0-maccatalyst /Users/soshay/Documents/MauiApp1/MauiApp1/MauiApp1.csproj`

But this one does (with no ability to debug)
`dotnet build -t:Run -f net8.0-maccatalyst -p:Configuration=Debug`

This issue [is fixed on Visual Studio for Mac](https://developercommunity.visualstudio.com/t/NET-MAUI-in-NET-8-wont-buildrun-macc/10485985?sort=newest&ftype=problem), but I'd rather avoid downloading that since it's approaching EOL. (Also, I can't download VS since the download site is only providing me .exe files)

### Steps to Reproduce

1. Create new Visual Studio Code Maui project
2. Launch and Debug (F5)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS, I was *not* able test on other platforms

**Comment by mattleibow** [comment]
This appears to be a VSCode issue, maybe open an issue there: https://github.com/microsoft/vscode-dotnettools/issues
