### ISSUE TITLE
[Spec] Remove Android Pre-AppCompat 

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#20]
# Description

Remove pre-AppCompat renderers and supporting classes from the Android Platform.

# API Changes

| Class to Remove | AppCompat Replacement |
| ------------- | ------------- |
| FormsApplicationActivity | FormsAppCompatActivity |
| Platform | AppCompat.Platform |
| ButtonRenderer | AppCompat.ButtonRenderer |
| CarouselPageRenderer | AppCompat.CarouselPageRenderer |
| FrameRenderer | AppCompat.FrameRenderer |
| MasterDetailRenderer | AppCompat.MasterDetailPageRenderer |
| NavigationRenderer | AppCompat.NavigationPageRenderer |
| PickerRenderer | AppCompat.PickerRenderer |
| SwitchRenderer | AppCompat.SwitchRenderer |
| TabbedRenderer | AppCompat.TabbedPageRenderer |

# Backward Compatibility

This will be a breaking change for anyone still using the pre-AppCompat renderers. Those users will need to update their applications to use FormsAppCompatActivity and update any renderer customization to use the AppCompat renderers.

# Difficulty : Low

This mostly entails deleting files.

**Comment by domagojmedo** [comment]
@hartez if a class is using Platform and wasn't mentioned in the list above, does it need to change so it uses AppCompat.Platform or should it also be deleted? 
For example ImageButtonRenderer uses 
```
if (Platform.GetRenderer(Element) == this)
{
	Element.ClearValue(Platform.RendererProperty);
} 
```
on line 116. 

What should be done in those cases?

**Comment by PureWeen** [comment]
All done
