### ISSUE TITLE
[Enhancement] Replace all events with IObservable<T>

### ISSUE THREAD

**Issue by ChaseFlorell** [dotnet/maui#200]
## Summary
in order to compete with other mobile frameworks that are already embracing reactive programming principles, I would love to see Maui move away from Events to IObservable<T>. All of the plumbing required to do this is already in the System namespace and will not require any third party dependencies. 

## API Changes

find / replace `public event` / `public IObservable<`

## Intended Use Case
Make .NET Maui more desirable to reactive programmers and move away from legacy event subscriptions.

**Comment by GeraudFabien** [comment]
There is already ReactiveUi (License MIT) who intend to do that. If it's improvement that could be bring to help them i would agree. 
But i don't thinks it's a good idea to do it natively since not everyone want or love Reactive programming.

**Comment by ahoefling** [comment]
I like the idea of greater support for `IObservable<T>`. The 3rd party library ReactiveUI is great for getting reactive programming support into Xamarin.Forms today but it is ultimately a 3rd party library. Getting some level of support at the platform level will definitely make .NET MAUI a more competitive offering.

**Comment by GeraudFabien** [comment]
Explain yourself

> The 3rd party library ReactiveUI is great for getting reactive programming support into Xamarin.Forms today but it is ultimately a 3rd party library. Getting some level of support at the platform level will definitely make .NET MAUI a more competitive offering.

What do you intend to solve/Improve ? Please help us understand you're need ?

The fact that ReactiveUI is a third party is not an problem at all.
FYI : 
 - Some MS employee support ReactiveUI and even made it...  
 - The first commit was made 15 jun, 2010. So it has 10 year.
 - 1,489,946 download on nuget and 423 download a day currently

Has i said : 
>  If it's improvement that could be bring to help them i would agree.

Currently you exposed no problem of ReactiveUI. Expose them and we can have a real discussion.

**Comment by ChaseFlorell** [comment]
ReactiveUI is not a problem, in fact it's fantastic, however the purpose of this request is to make reactive programming a first-class citizen within System.Maui since System.Reactive has everything we need to make observable pipelines within Maui. 

If we have to use RX UI, then we have to add a lot of additional boilerplate code in order to convert events into observables.

All of the non-microsoft cross-platform frameworks are using some form of reactive programming as a first-class citizen within their framework. Managing events in c sharp is a pain, and observables make that pain almost entirely disappear.

**Comment by sharwell** [comment]
I would certainly support a request to ensure that events work in the context of reactive-style application programming model. However, I would discourage attempts to _force_ a move to this style of application. Reactive APIs have a very steep learning curve, and I've observed cases in the past where attempting to adopt the approach resulted in order-of-magnitude increases in the amount of time it took to deliver an application with exactly the same functionality that normal event-based approaches would have offered.

**Comment by pictos** [comment]
If you said to change event handlers to Action<T> and Func<T> I completely agree! But for change to `IObservable<T>` I don't agree, because I'm a dev that doesn't use it.

**Comment by sharwell** [comment]
@ChaseFlorell It may soon be possible to use [source generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) to automatically generate `IObservable<T>` mirrors of events in a type.

**Comment by ahoefling** [comment]
@sharwell 
> @ChaseFlorell It may soon be possible to use source generators to automatically generate IObservable<T> mirrors of events in a type.

I really like the idea of using Source Generators, that would reduce the maintenance  burden and add support for IOBservable<T>
