### ISSUE TITLE
Expander is not working in ios inside collectionview

### ISSUE THREAD

**Issue by NetCSDev** [dotnet/maui#20004]
### Description

The expander is not working in ios when used in collectionview. it works correctly in android when switch back to ios it is showing wierd issue. only first element is getting expanded or collapsed. whenever the other items of collectionview clicked, the first element is expanded or collapsed. 
Code Sample : 
<img width="658" alt="image" src="https://github.com/dotnet/maui/assets/48364088/146da077-9e4b-4cea-aa03-15c662202c5e">

<CollectionView ItemsSource="{Binding Items}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                <toolkit:Expander>
                    <toolkit:Expander.Header>
                    <Border Padding ="20" BackgroundColor="Beige" Margin="5,2,5,2">
                        <Label Text="{Binding .}" VerticalTextAlignment="Center" />
                    </Border>
                     </toolkit:Expander.Header>
                     <Border Padding ="20" BackgroundColor="Green" Margin="5,2,5,2">
                        <Label Text="{Binding .}" VerticalTextAlignment="Center" />
                    </Border>
                     </toolkit:Expander>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

### Steps to Reproduce

1. Create a collection view 
2. add expanded control inside it
3. Run the application in ios

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

**Comment by NetCSDev** [comment]
<CollectionView ItemsSource="{Binding Items}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                <toolkit:Expander>
                    <toolkit:Expander.Header>
                    <Border Padding ="20" BackgroundColor="Beige" Margin="5,2,5,2">
                        <Label Text="{Binding .}" VerticalTextAlignment="Center" />
                    </Border>
                     </toolkit:Expander.Header>
                     <Border Padding ="20" BackgroundColor="Green" Margin="5,2,5,2">
                        <Label Text="{Binding .}" VerticalTextAlignment="Center" />
                    </Border>
                     </toolkit:Expander>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

**Comment by PureWeen** [comment]
@NetCSDev have you reached out to the Community toolkit about this?
https://github.com/CommunityToolkit/Maui

**Comment by jfversluis** [comment]
Most likely a toolkit issue, closing it here.
