### ISSUE TITLE
Strange shadows of Popup on MAC

### ISSUE THREAD

**Issue by workmail20** [dotnet/maui#20003]
### Description

Strange background dark shadows, which repeat the custom dialog box, when displaying Popup on MAC. Does anyone know how to fix it?
![Знімок екрана 2024-01-19 131133](https://github.com/dotnet/maui/assets/74146677/96668c3a-a5e3-43c9-b073-829025353ce6)
![Знімок екрана 2024-01-19 131206](https://github.com/dotnet/maui/assets/74146677/c30914bb-57d2-4bb5-a868-50e2d8d0427b)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Sonoma 14.2.1

### Did you find any workaround?

no

**Comment by drasticactions** [comment]
That popup comes from [CommunityToolkit.Maui](https://github.com/CommunityToolkit/Maui). You should take that question over there.

**Comment by samhouts** [comment]
This issue was moved to CommunityToolkit/Maui#1662
