### ISSUE TITLE
Application display version not updating on iOS Local Device

### ISSUE THREAD

**Issue by seanrco** [dotnet/maui#20000]
### Description

AppInfo.Current.Version.ToString()  or AppInfo.Current.VersionString value not reflecting when deploying to 'iOS Local Device'. It always displays '1.0.0'.  This seems to only be an issue on 'iOS Local Device'. Tested in Android Emulator and correct value displayed.

**Properties**
![NjoARRUuVJ](https://github.com/dotnet/maui/assets/582014/116d3580-bbb3-4711-93ba-f96ca0ae468f)

**Android Emulator**
![xxfnSgbMOd](https://github.com/dotnet/maui/assets/582014/053e3180-2436-45d8-b8ee-9554e3af9cf8)

**iOS Local Device**
![IMG_5756](https://github.com/dotnet/maui/assets/582014/1dc75955-6507-47f2-a8fe-526087b9da23)

### Steps to Reproduce

1. Create test NET MAUI App (my example is using Blazor Hybrid if it matters)
2. Update app Application Display Version
3. Deploy to 'iOS Local Device'

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
android                    33.0.68/7.0.100        VS 17.7.34202.233
maui-windows               7.0.96/7.0.100         VS 17.7.34202.233
maui-maccatalyst           7.0.96/7.0.100         VS 17.7.34202.233
maccatalyst                16.4.7107/7.0.100      VS 17.7.34202.233
maui-ios                   7.0.96/7.0.100         VS 17.7.34202.233
ios                        16.4.7107/7.0.100      VS 17.7.34202.233
maui-android               7.0.96/7.0.100         VS 17.7.34202.233

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by mattleibow** [comment]
@emaf is this possibly a limitation of the hot restart app bundle?

**Comment by seanrco** [comment]
> @emaf is this possibly a limitation of the hot restart app bundle?

@emaf I was wondering if this issue is similar to why custom app splash images, icons, etc. also do not render in 'iOS Local Device'. The hot restart app bundle does not have a true xcode build/singature? Not sure if these issues in case are considered by design or issues. Thanks for looking into it!

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2 (8.0.14), can not repro it with below steps:
1 Created maui project.
2 Added a button to MainPage.xaml <Button Clicked="Button_Clicked" x:Name="Btn"></Button>
3 Added Clicked method to get AppInfo.Version.
private void Btn_Clicked(System.Object sender, System.EventArgs e)
{
    AppInfo.Version.ToString();
    Btn.Text = AppInfo.Version.ToString();
}
