### ISSUE TITLE
[Bug] Unable to pop modal screen on iOS/Mac

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2002]
### Description

When calling `Window.PopModalAsync()` a platform rendering exception is thrown

```
An System.NullReferenceException has occured: Object reference not set to an instance of an object @    at Microsoft.Maui.Controls.Platform.ModalNavigationManager.get__renderer()
at Microsoft.Maui.Controls.Platform.ModalNavigationManager.PopModalAsync(Boolean animated)
at Microsoft.Maui.Controls.Window.NavigationImpl.OnPopModal(Boolean animated)
```

This only happens on iOS and Mac. It works correctly on Android.

### Steps to Reproduce

1. In a new MAUI project, set up a button to create a modal page with the same or different page parameter, and a way to call `Window.PopModalAsync()`
2. Once that page opens, click on the button to close the modal.

### Expected Behavior

The modal closes.

### Actual Behavior

An exception is thrown.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
@drasticactions I tested this on p10 and it looks like it's fixed
