### ISSUE TITLE
FlyoutPage + NavigationPage | Navigation stuck after some time

### ISSUE THREAD

**Issue by kraemernet** [dotnet/maui#20032]
### Description

NavigationPage breaks after some navigation forth and back.

https://github.com/dotnet/maui/assets/156280922/35b734a9-9b6d-47dd-b94c-9c7665da12a6

### Steps to Reproduce

For my Git project:
Navigate to the settings subpage and back a couple of times, around 10-15 times.

### Link to public reproduction project repository

https://github.com/kraemernet/MauiNavigationApp.git

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13.0 API 33

**Comment by drasticactions** [comment]
I couldn't reproduce your issue, but looking at your code...

https://github.com/kraemernet/MauiNavigationApp/blob/master/MauiApp/SettingsPage.xaml.cs#L9-L12

Instead of creating a new subpage every time you navigate, could you instead keep one instance of that page and navigate using that?

```csharp
public partial class SettingsPage : ContentPage
{    public SettingsPage()
	{
        InitializeComponent();
        _settingsSubPage = new SettingsSubPage();
    }
    
    private SettingsSubPage _settingsSubPage;

    private void GoToSubPage_Clicked(object sender, EventArgs e)
    {
        Navigation.PushAsync(_settingsSubPage);
    }
}
```

**Comment by kraemernet** [comment]
As I saw your answer, I recognized that there is an 'await' and 'async' missing. If I add them, it works for me.


```cs
private void GoToSubPage_Clicked(object sender, EventArgs e)
{
  Navigation.PushAsync(new SettingsSubPage());
}
```
    
to
    
```cs
private async void GoToSubPage_Clicked(object sender, EventArgs e)
{
  await Navigation.PushAsync(new SettingsSubPage());
}
```

Thank you for your answer and your time.
