### ISSUE TITLE
[Bug] [iOS] TableView using Commands on Cells only accepts clicks to some cells

### ISSUE THREAD

**Issue by alexkblount** [dotnet/maui#2003]
net6.0 v 6.0.100-rc.1.21403.66

### Description

When creating a list using a TableView and using Command to add click handling, only some of the cells will be selectable. This is random based on the first cell selected.

```csharp
 <TableView Intent="Menu">
        <TableRoot>
            <TableSection Title="XAML">
                <TextCell Text="Default StackLayout"
                          Detail="Vertical"
                          Command="{Binding NavigateCommand}"
                          CommandParameter="{x:Type views:VerticalStackLayoutPage}" />
                <TextCell Text="Horizontal StackLayout"
                          Detail="Orientation property"
                          Command="{Binding NavigateCommand}"
                          CommandParameter="{x:Type views:HorizontalStackLayoutPage}" />
                <TextCell Text="Child spacing"
                          Detail="Spacing property"
                          Command="{Binding NavigateCommand}"
                          CommandParameter="{x:Type views:StackLayoutSpacingPage}" />
            </TableSection>
        </TableRoot>
    </TableView>
```

https://user-images.githubusercontent.com/30159621/128623615-723c3345-1e2a-4cc8-9847-0d2528e7c84a.mp4

**Comment by kristinx0211** [comment]
@alexkblount it works by using a TableView and using Command to add click handling, repro on iPhone 13 pro max IOS 15.2.
![image](https://user-images.githubusercontent.com/99457000/157180086-ccc4402f-b5be-4c75-8302-28f4c7dc2a3f.png)
https://user-images.githubusercontent.com/99457000/157179881-96af97d8-6c8b-48ac-a18c-0572e980e7b4.mov
