### ISSUE TITLE
Window not resizing from the Top

### ISSUE THREAD

**Issue by danielancines** [dotnet/maui#20061]
### Description

When I create a new project, without any change, window cannot be resized pulling from the top.

### Steps to Reproduce

Create a new dotnet 8 Maui Project.
Run
Try to resize window from top of the titlebar to the bottom.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

**Comment by danielancines** [comment]
An example:

![Uploading ResizeProblem.gif…]()

**Comment by danielancines** [comment]
![ResizeProblem](https://github.com/dotnet/maui/assets/2250055/21ddfef4-4f25-4fd4-88b8-aaf04e91d6e6)

**Comment by PureWeen** [comment]
It looks like this is a bug with WinAppSDK

We're waiting for a fix that will hopefully land in WinAPPSDK 1.5 that will let us bump our min version. 

For now you can just update WinAppSDK yourself as a workaround.

Just add this to your csproj file and that should fix you. 

```XML
<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
	<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.4.231219000" />
</ItemGroup>
```

**Comment by danielancines** [comment]
Thank you @PureWeen !!

**Comment by PureWeen** [comment]
> I tried here and it works, any downside using this solution @PureWeen ?

As you've seen from the new issue :-( unfortunately yes. 

Still working with the WinUI team to see if we can find an alternative.

**Comment by danielancines** [comment]
@PureWeen thank you, but this kind of thing stuck us (my company) to avoid .net 8. :-(
