### ISSUE TITLE
[Bug] Issues in setting the MainPage

### ISSUE THREAD

**Issue by vickyanand25005** [dotnet/maui#2006]
### Description
In this release, I cannot set the App.Current.MainPage. if I do this app never navigate to MainPage from LoginPage.
I have to set new Window(new NavigationPage(new LoginPage())); then await Navigation.PushAsync(new MainPage());
Also not able to remove the Status bar.
### Steps to Reproduce

1.Open MAUI sample app
2.Set App.Current.MainPage in your app if you have login page or some there page
3.You won't be able to navigate to Mainpage.

### Expected Behavior
This should have been working just like Xamarin Forms

### Actual Behavior
Not able to navigate to Other Page
### Basic Information

- Version with issue:MAUI 6.0.100-preview.5.794
- Last known good version: Xamarin Forms
- IDE: Visual Studio 2019 Preview 16.11.0 Perview 3
- Platform Target Frameworks: 
 
  - Android: Android SDk - 11.4.0.5
 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
duplicate
https://github.com/dotnet/maui/issues/2517
