### ISSUE TITLE
[Android] Secondary ToolbarItem Icon Color not correct

### ISSUE THREAD

**Issue by FlavioGoncalves-Cayas** [dotnet/maui#20070]
### Description

[This PR ](https://github.com/dotnet/maui/pull/15612) should have fixed the issue, but the issue still persists. At least when not using Shell.

Observed in 
- 8.0.6 SR1
- 8.0.6-nightly-9851

### Steps to Reproduce

1. Add a ToolbarItem with Order 'Secondary' to a ContentPage in a NavigationPage (no Shell)
2. Observe the IconColor not matching the NavigationPage.BarTextColor or IconColor

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by PureWeen** [comment]
@FlavioGoncalves-Cayas can the original issue be used as a repro?

**Comment by FlavioGoncalves-Cayas** [comment]
Hi @PureWeen,
I don't think so, as I think it only mentions Shell.
The repro is pretty straightforward, however right now I do not have the time to setup the repro project.

**Comment by FlavioGoncalves-Cayas** [comment]
I could not reproduce my reported issue in an isolated repro project. Looks like the issue is somewhere else.
