### ISSUE TITLE
Windows app installs on Wndows 10 but fails to install on Windows 11 as it keeps asking for .NET even after installation of .NET 8?

### ISSUE THREAD

**Issue by exquirentibus** [dotnet/maui#20084]
### Description

I'm using Visual Studio 2022 Preview to create a Widows exe of a Maui app.

On two virgin Windows 10 machine it puts up a dialog asking to install .NET 8 and does so without a problem.

On two virgin Windows 11 machines it puts up the same dialog, the .NET install is run, and then when the Maui app is run again it asks "You must install or update .NET to run this application"

dotnet --info shows the exact same runtime installed on Win11 as on Win10?

I even tried installing Visual Studio but Only installing the .NET 8 runtimes.  That had no effect.

Then I installed the Maui entire package in Visual Studio Preview.  No change?

My girlfriend just ran the exact same packaged directory that woudn't install on Win11 but did on Win10 on her Win11 machine and it .. Ran?

But .. she's had Visual Studio 2022 Preview installed and has been developing Maui apps?

How can I get my Windows version of the app installed on Windows 11 for my Client?

BTW - I did Not have this issue with .NET 7 previously?  This is new behavior with .NET 8.

dotnet --info
Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] 

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

no

**Comment by exquirentibus** [comment]
I'd been building using 
 <WindowsPackageType Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">None</WindowsPackageType>
 
 while changing  launchSettings.json MsixPackage to Project 
 
 and building.  This was working well before .NET8.  
 
 It did NOT require a certificate (self-signed or otherwise) which was an advantage to me as I could just zip up the Windows folder in BIN and have my client run the exe from there.
 
 I resolved the problem by using Publish and a self-signed certificate.
 
 This Does force my client to install the certificate properly (would be nice if this could be automated)?
 
 And Publish is Not taking the versions from the project file automatically:
 
 <ApplicationDisplayVersion>2.0</ApplicationDisplayVersion>
 <ApplicationVersion>69</ApplicationVersion>
    
  which was another nice 'feature' of my previous method.
  
  If both of these could be automated into the Publish  msix, that would make it a lot easier for me and for my client.
  
  So I have a solution, and the install program is nice, but in a few ways it requires more work from less computer literate clients?

**Comment by QianaJiao** [comment]
Verified this issue was not repro on Visual Studio Enterprise 17.10 Preview 2.0; .NET 8.0.202; Maui 8.0.7.

**Comment by exquirentibus** [comment]
I ended up publishing with a self-generated cert and that works well now other than user confusion in adding the certificate.   

Would be handy if publish would Optionally offer to add the included certificate after he confirms "Yes" as getting it into the correct certificate location confuses them?
