### ISSUE TITLE
Android: LineBreakMode="WordWrap" not working when label in popup on a row in a multi-row grid - 8.0.7-nightly.9897

### ISSUE THREAD

**Issue by DawidBester** [dotnet/maui#20092]
### Description

(not working for Android) Using 8.0.7-nightly.9897 (also tested 8.0.6-nightly.9755); LineBreakMode="WordWrap" not working when label placed in a popup as a row in a multi-row grid 

(working) Using 8.0.6 and 8.0.3, Android and iOS17.2

| nightly | GA / SR1 |
| :-:|:-:|
|![image](https://github.com/dotnet/maui/assets/33708055/97a6e1b7-9948-45ca-8dea-721135f5952b)|![image](https://github.com/dotnet/maui/assets/33708055/7aea832a-e7f7-4661-84c3-b531f170c7a4)|

### Steps to Reproduce

Run the sample project which uses 8.0.7-nightly.9897 and tap button "Show Label in Popup" for popup to show popup page and see label truncated text

### Link to public reproduction project repository

https://github.com/DawidBester/LabelTextWrapTest

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

Use 8.0.6,

Unfortunately this 8.0.6 has issues with button CornerRadius=0 on Android which is a much more noticeable interface issue, so not an option: https://github.com/dotnet/maui/issues/19421

**Comment by jsuarezruiz** [comment]
We started reviewing it. From first tests, getting the same result rolling back the changes in https://github.com/dotnet/maui/pull/14918 in the Android TextViewExtensions class.
![image](https://github.com/dotnet/maui/assets/6755973/8623f296-1cf1-4986-a71a-5dc252ce6fb6)

**Comment by PureWeen** [comment]
It looks like this regressed between

8.0.4-nightly.9750
and
8.0.4-nightly.9742

**Comment by PureWeen** [comment]
This issue isn't quite a regression.

For example, in 8.0.3 if you update the text after the popup is visible you'll see the same behavior of the text unwrapping itself. 

It's more that #19349 triggers the ticking time bomb earlier

**Comment by PureWeen** [comment]
Moved this to MCT for now
https://github.com/CommunityToolkit/Maui/issues/1664
