### ISSUE TITLE
MAUI Blazor Hybrid App Fails To Load Certain IFrames

### ISSUE THREAD

**Issue by pureooze** [dotnet/maui#20091]
### Description

Sorry if this is not the right place to report this, feel free to move it if needed.

---

I am encountering an issue when trying to embed a Twitch `iframe` as described in https://dev.twitch.tv/docs/embed/video-and-clips/.

The following will work in a Blazor Web App but does not work in a MAUI Blazor Hybrid app:

```
<iframe src="https://player.twitch.tv/?channel=jaaski&parent=localhost"
        height="400px"
        width="400px"
        allowfullscreen>
</iframe>
```

Doing the above in MAUI Hybrid Blazor App gives the following error:
```
Refused to frame 'https://player.twitch.tv/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors http://localhost:* https://localhost:*".
```
<summary>
Screenshot of error
<details>
<img src="https://github.com/dotnet/maui/assets/2337524/164bde07-37f6-4881-ae18-52e12192f310" />
</details>
</summary>

According to these links localhost should work but I suspect the host address being 0.0.0.0 is causing issues here?

https://discuss.dev.twitch.com/t/twitch-embedded-player-updates-in-2020/23956/18
https://discuss.dev.twitch.com/t/twitch-embed-not-working/33873/4

It seems possible to do this in electron [like this](https://github.com/BarryCarlyon/twitch_misc/tree/main/player/electron) so this seems to just be a limitation in MAUI Blazor at the moment?

### Steps to Reproduce

1. Create MAUI Blazor Hybrid App project
2. Open a component (ex. `Home.razor`)
3. Add the following code to the component:
```
<iframe src="https://player.twitch.tv/?channel=jaaski&parent=localhost"
        height="400px"
        width="400px"
        allowfullscreen>
</iframe>
```
4. Run the app
5. The iframe will not load correctly

### Link to public reproduction project repository

https://github.com/pureooze/examples/tree/main/bug-reports/maui/twitch-iframe

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 19045.3930

### Relevant log output

```
Refused to frame 'https://player.twitch.tv/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors http://localhost:* https://localhost:*".
```

**Comment by pureooze** [comment]
Mentioning this because I forgot to in the original post, using a `parent` of `0.0.0.0` causes a `Twitch embed error message`:

![image](https://github.com/dotnet/maui/assets/2337524/6c52c151-ab46-47dc-9f05-eaa2b3a8ce31)

**Comment by mkArtakMSFT** [comment]
This will be resolved by https://github.com/dotnet/maui/issues/11425
