### ISSUE TITLE
LinearGradientBrush in global style does not work

### ISSUE THREAD

**Issue by fusionconsulting** [dotnet/maui#20097]
### Description

I'm migrating a Xamarin Forms project to MAUI and I've run into a problem with styles. I have a linear gradient set on the background of all content pages. This works as expected in XF but I get a white background in MAUI.

The IDE highlights StartPoint, EndPoint and Color as missing properties but the documentation shows them as being present.

### Steps to Reproduce

Add this to Styles.xaml:

    <Style TargetType="ContentPage" ApplyToDerivedTypes="True">
        <Setter Property="Background">
            <LinearGradientBrush StartPoint="0,0"
                                    EndPoint="0,1">
                <GradientStop Color="#25BEFF"
                                Offset="0.1"/>
                <GradientStop Color="#2A7BF4"
                                Offset="1.0"/>
            </LinearGradientBrush>
        </Setter>
    </Style>

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by jaosnz-rep** [comment]
Verified on 8.0.14 & 8.0.7 with the latest 17.10 preview 2, cannot repro on Android platform.
![image](https://github.com/dotnet/maui/assets/82628041/346bc6d5-3a08-4d01-b625-d0f4b39653be)
