### ISSUE TITLE
.NET Maui todo list problem

### ISSUE THREAD

**Issue by janobbb** [dotnet/maui#20123]
### Description

Generally, the problem I have is that when I run the project on Windows, it works perfectly, but on the phone, the logs show only failed to load assembly errors.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Thanks for the report, but unfortunately without any more details it will be near impossible to diagnose what might be going on here. Please open a new issue describing in more detail what you're doing. What project? What are you seeing? What do you expect to see? What Visual Studio are you using? Screenshots, a reproduction... Things like that. Thanks!
