### ISSUE TITLE
[MAUI][.NET8] ‘Review’ module jumps repeatedly when editing recipe page.

### ISSUE THREAD

**Issue by Zhanglirong-Winnie** [dotnet/maui#20126]
### Description

‘Review’ module jumps repeatedly when editing recipe page.

### Steps to Reproduce

1. Deploy https://github.com/rachelkang/recipeSearch to Android platform.
2. Click or tap on the 'My Recipes' tab to navigate to the 'My Recipes' page.
3. Click or tap on any Your recipes page.
4. Click or tap on the 'Edit' button.

Actual results:
The ‘Review’ module on the recipe page jumps repeatedly.
![Recipe](https://github.com/dotnet/maui/assets/77434865/13c594c5-4790-4645-b7b5-752533fa1537)

Expected result:
The page displays normally.

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

Microsoft.Maui.Controls : 8.0.7-nightly.9909+sha.4f32463d01-azdo.8960497
.NET SDK: 8.0.200-preview.23624.5

### Version with bug

8.0.7-nightly.9909

### Is this a regression from previous behavior?

Yes, this is a regression. This issue not repro on 8.0.6+1-sha.87f59a86d4-azdo.8922564.

### Last version that worked well

8.0.6-nightly.9876+sha.abe0025c2d-azdo.8930532

### Affected platforms

Android

**Comment by RoiChen001** [comment]
This problem has a different situation on iOS platform 8.0.7-nightly.9919+sha.8c04a9d4da-azdo. 8968095.When I slide the **Review** value, the page will jump.
![pup up](https://github.com/dotnet/maui/assets/143168639/5b114a64-0fb5-46fa-b0cc-10bf3c6eff4d)

**Comment by PureWeen** [comment]
This was regressed by
https://github.com/dotnet/maui/pull/19794
