### ISSUE TITLE
Label Truncation and MaxLines options do not work when combined

### ISSUE THREAD

**Issue by MitchBomcanhao** [dotnet/maui#20128]
### Description

This is not a new issue, it has been reported multiple times over the years, hasn't been fixed, and the previous bugs have been closed as if things were fixed.

see 
- https://github.com/dotnet/maui/issues/9853
- https://github.com/dotnet/maui/issues/9084

I have found other issues in maui where properties set in xaml are simply not being applied to the controls (mainly when dealing with implicit styles, where some properties have no effect) so I'm wildly speculating this will be a similar issue. when setting up truncation properties, the maxlines setting is likely not getting set at all.

I've reproduced this on Windows and the older bugs also mention iOS and Android so I'm sure they'll also be broken.

### Steps to Reproduce

In my case, I have a label set with `LineBreakMode="TailTruncation"
MaxLines="2"` and it is rendered with a single truncated line.

If you want more details, be sure to check the referenced bugs above which have not been resolved.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by MitchBomcanhao** [comment]
8.0.6
![image](https://github.com/dotnet/maui/assets/31066938/d7797f15-e2d4-427a-bd16-df077a9d80fb)

8.0.7-nightly.9952 (30 January 2024)
![image](https://github.com/dotnet/maui/assets/31066938/2e0aaf8a-ef69-40bc-ae84-0a401901e8b9)

seems like its behaviour has changed in recent builds

**Comment by MitchBomcanhao** [comment]
@PureWeen if the code change has reached production, then I think it can be closed
