### ISSUE TITLE
[Bug] No error when try push outside NavigationPage

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#2013]
### Steps to Reproduce

1. Create a simple app, and make sure that `App.MainPage` is any `ContentPage`
2. Create a button and implement a clicked event that does `Navigation.PushAsync()`
3. Nothing happens

### Expected Behavior
1. See an exception or log that tells me that I need to have a `NavigationPage` as the root page.
2. When `App.MainPage` has a `NavigationPage` as the root page I want the breakpoint, inside click event handler, triggers (as you can see in the video that doesn't happen).
### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: preview 6 (?)
- Last known good version: Na
- IDE: VS 2022
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Na
- Affected Devices: Android

### Screenshots

https://user-images.githubusercontent.com/20712372/128791827-cc4f64e3-af88-4dfc-8544-ec79a1f63083.mp4

### Reproduction Link

[Navigation_Bug.zip](https://github.com/dotnet/maui/files/6958191/Navigation_Bug.zip)

**Comment by YuqinSong** [comment]
Verified Repro with Android 11. Repro project is available:
[#2013.zip](https://github.com/dotnet/maui/files/8129072/2013.zip)

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 2.0. This issue does not repro on Android 33 with below Project:
[2013.zip](https://github.com/dotnet/maui/files/11175753/2013.zip)

**Comment by PureWeen** [comment]
This is still an issue. The bug is that we should throw an exception if you aren't wrapped with a navigationpage.

**Comment by XamlTest** [comment]
Sorry for that, I have updated above comment.

**Comment by kubaflo** [comment]
@PureWeen what about such solution? https://github.com/dotnet/maui/pull/20155

**Comment by jsuarezruiz** [comment]
Related PR https://github.com/dotnet/maui/pull/20155
