### ISSUE TITLE
Xcode 15+ VS 17.8.5 Can't get Simulators

### ISSUE THREAD

**Issue by techbud** [dotnet/maui#20138]
### Description

Hey, I can't seem to get simulators to work on VS 17.8.5 with and Xcode version 15 +. They show on Xcode version 14.3.1, but as soon as I upgrade it stops working and it's a pain as I have to test iOS 17.1 as I'm submitting an app and I guess it is crashing on that version for some reason.

I tried:
Uninstalling reinstalling Xcode
Tried going back every different version.
Deleted the XMA folder.
Uninstalled and reinstalled VS.
Of course restarted.
Updated workloads.

It seems like it will connect to the mac, and I can see my iPad, but it doesn't show the simulators.

Any help with this would be great, thanks ahead of time!

### Steps to Reproduce

1. Create a .net maui app.
2. Connect to Mac
3. It will connect but simulators do not show

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Did you find any workaround?

Not yet

**Comment by archergod** [comment]
I can confirm this is the issue, as I try upgrading and clearly folder as says and it is not working for me.
