### ISSUE TITLE
Window.Destroying event not fired when you swipe the app away on Android

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/maui#20146]
.NET SDK 8.0.200-preview.23624.5

Create a new project and in `MainPage.xaml.cs`:
```cs
public MainPage()
{
	InitializeComponent();

	var window = App.Current.Windows.Single();
	window.Destroying += Window_Destroying;
}

private void Window_Destroying(object? sender, EventArgs e)
{
	// Called if you click the X on Windows, but not if you swipe away the app on Android.
	throw new NotImplementedException();
}
```

Now run the app on Android and try swiping it away from recents. It won't trigger the event.

#6993 ?

**Comment by PureWeen** [comment]
There's no guarantee that Android will call `OnDestroy`

https://developer.android.com/reference/android/app/Activity.html#onDestroy%28%29
