### ISSUE TITLE
Actualizacion de la interfaz

### ISSUE THREAD

**Issue by t3m0c** [dotnet/maui#20151]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/maui/first-app-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

no se muestra el cambio realizado en la interfaz como lo mencionan en el tutorial

![image](https://github.com/dotnet/maui/assets/36984326/703acb1a-39aa-48a9-9fe1-01cfaaf2987e)

**Comment by cjrvdev** [comment]
Tienes que utilizar el boton de hot reload, el de la llamita.
Para proximas ocasione escribe los issues en inglés o no te van a leer.

**Comment by t3m0c** [comment]
Thank you very much for the contribution and I will keep it in mind for future problems.

**Comment by jfversluis** [comment]
Thanks @cjrvdev !

Are we all good here @t3m0c or do you still need anything?
