### ISSUE TITLE
VerticalStackLayout BackgroundColor is ignored

### ISSUE THREAD

**Issue by DominikErnst** [dotnet/maui#20157]
### Description

Latest MAUI. 

### Steps to Reproduce

`<VerticalStackLayout BackgroundColor="Aqua"
		<Label Text="xyz" />
		<Label Text="xyz" />
</VerticalStackLayout>
`

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

NO

**Comment by DominikErnst** [comment]
Found
`	<Style TargetType="VerticalStackLayout">
		<Setter Property="Background" Value="{AppThemeBinding Light={StaticResource Gray100}, Dark={StaticResource Gray950}}" />
		<Setter Property="Padding" Value="0" />
	</Style>
`
in the Styles.xaml File. After removing the Background Setter it works, but shouldn't the property on the control have a higher priority?

**Comment by drasticactions** [comment]
@StephaneDelcroix Could this be a setter specificity issue?

**Comment by bradencohen** [comment]
Could it be because the Styles.xaml is specifying `Background` instead of `BackgroundColor`?

**Comment by PureWeen** [comment]
@DominikErnst what version did this work on for you?

**Comment by DominikErnst** [comment]
Sorry, I think it was my mistake. I used Property="Background" instead of Property="BackgroundColor".
You can close this case.
