### ISSUE TITLE
iOS app crashes in release  mode on physical device

### ISSUE THREAD

**Issue by roughiain** [dotnet/maui#20175]
### Description

The application crashes on after a few screens with 

`[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:] perform input operation requires a valid sessionID`

Googling around found a similar reactNative [bug](https://github.com/facebook/react-native/issues/41801)

also on the apple developer [forums](https://forums.developer.apple.com/forums/thread/731700)  

I have no idea how to get more information on this.

Here are the build settings

```
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios/ios-arm64|AnyCPU'">
        <CreatePackage>false</CreatePackage>
        <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
<!--        <PublishAot>True</PublishAot>-->
        <CodesignProvision>$(CODESIGNPROVISION)</CodesignProvision>
        <CodesignKey>$(CODESIGNKEY)</CodesignKey>
        <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
    </PropertyGroup>
```

### Steps to Reproduce

I can't reproduce as I don't have enough information.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

No

### Relevant log output

```shell
Device log 

`-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID`
```

**Comment by PureWeen** [comment]
@rolfbjarne thoughts?

**Comment by rolfbjarne** [comment]
Does this happen in the simulator or on device (or both)?

A crash report might be helpful: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#crash-reports

That said, this doesn't look like a bug in MAUI (because of all the people running into the same thing in the Apple forums), so we might not be able to do something about it (at most we might be able to work around it somehow, but that really depends on what's triggering the problem, and we'd need a way to reproduce it - aka a test project - in order to even start trying to find a solution).

**Comment by roughiain** [comment]
Hi, I have tracked the issue down to a third party module, please close the ticket

**Comment by brodysctt** [comment]
@roughiain what dependency caused the issue? I'm experiencing a similar bug

**Comment by roughiain** [comment]
It was an event on a DevExpress chip group

So this event was crashing on page load

```void ChipGroupCategories_OnSelectionChanged(object? sender, EventArgs e)```

I still need to create a repo with just the error and submit it to them, but things have been busy.
