### ISSUE TITLE
Android App crashes on startup

### ISSUE THREAD

**Issue by borrmann** [dotnet/maui#20176]
### Description

See following issue:
[dotnet 96872](https://github.com/dotnet/runtime/issues/96872)

### Steps to Reproduce

1. Start Android App and do some threaded work
2. App crashes

### Link to public reproduction project repository

not necessaray

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.2.9511

### Affected platforms

Android

### Did you find any workaround?

Solution from the linked issue seems to work 

```
<Target Name="UpdateRuntimePackVersion" BeforeTargets="ProcessFrameworkReferences">
	<ItemGroup>
		<KnownRuntimePack Condition="%(RuntimePackLabels) == 'Mono'" LatestRuntimeFrameworkVersion="8.0.0" />
	</ItemGroup>
</Target>
```

### Relevant log output

```shell
Assertion at object.c:657, condition `lock->done' not met
```

**Comment by jfversluis** [comment]
It looks like in the linked issue there was a bug there and that is fixed and pending release. So, what is there still to do on our side for this...?

**Comment by borrmann** [comment]
@jfversluis well, I guess there is not much that could be done. I simply, thought this should be tracked here too.
And maybe, this indicates there should be a test added? 
I mean, any MAUI app crashes on android if you do some data fetching in the background at startup. Isn't that a major concern? Where else should MAUI users share such information, if not here? 
Apologies if this is not the right approach to file an issue, just wanted to help by sharing the info I found.
