### ISSUE TITLE
Adding/Removing layout children does not invalidate measures

### ISSUE THREAD

**Issue by albyrock87** [dotnet/maui#20181]
### Description

I'm using a simple `BindableLayout` to add and remove children dynamically from `VerticalStackLayout` and I realized `MeasureInvalidated` event is not being fired when children changes.

On top of that, if child change its measures, the layout is not being invalidated.

So I went inside MAUI repo and added a couple of unit test which in fact are failing:

```cs
static IViewHandler ListenForInvalidation(IView view)
{
	var handler = Substitute.For<IViewHandler>();
	view.Handler = handler;
	handler.ClearReceivedCalls();
	return handler;
}
		
[Fact]
public void AddingChildInvalidatesLayoutHandler()
{
	var layout = new VerticalStackLayout();

	var handler = ListenForInvalidation(layout);
	layout.Add(new Label());
	AssertInvalidated(handler);
}

[Fact]
public void AddingChildInvalidatesLayout()
{
	var layout = new VerticalStackLayout();
	var invalidated = false;
	layout.MeasureInvalidated += (_, _) => invalidated = true;

	layout.Add(new Label());
	Assert.True(invalidated);
}
```

Note: the `Grid` from Compatibility package does behave correctly, in fact you have a working unit test there:

```cs
[Fact]
public void TestAddCell()
{
	var layout = new Grid();
	bool preferredSizeChanged = false;
	layout.MeasureInvalidated += (sender, args) => preferredSizeChanged = true;

	Assert.False(preferredSizeChanged);

	layout.Children.Add(new Label(), 0, 0);

	Assert.True(preferredSizeChanged);
}
```

I would propose a PR but I'm not sure which approach you would like to take here as the fix should probably go in `Layout` base class or maybe in `VisualElement` idk.

### Steps to Reproduce

1. Create a `VerticalStackLayout`
2. Subscribe to `MeasureInvalidated`
3. Add a child
4. Observe nothing was triggered

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Did you find any workaround?

Manually trigger the event `((IVisualElementController)layout).InvalidateMeasure(InvalidationTrigger.MeasureChanged);` which is something that makes `BindableLayout` basically unusable in combination with `Binding` on `ItemSource` because we have to subscribe twice using the view code behind.

**Comment by albyrock87** [comment]
@hartez I think you're the expert here looking at git history

How can someone capture when a visual element measure are invalidated?
Let's say I'm building an expandable content which displays a "Show more" button when the content height exceeds some value, how can I react to measure changes if `MeasureInvalidated` is not working at all?

https://github.com/albyrock87/BrokenMeasureInvalidationSample
https://github.com/albyrock87/BrokenMeasureInvalidationSample/blob/main/MainPage.xaml.cs

See here, not toast is appearing when I add or remove the label, or even when I change `HeightRequest` of that.

I think this is a pretty serious bug, and I couldn't find a viable workaround for now.

Thanks

![Simulator Screen Recording - iPhone 15 Pro - 2024-01-31 at 11 40 39](https://github.com/dotnet/maui/assets/1423005/d98c195e-b510-4b0c-968a-64a4ec9138c1)

**Comment by hartez** [comment]
> @hartez I think you're the expert here looking at git history

Well, I don't work on MAUI anymore, so I think someone else on that team will have to be your new expert. :)
 
> How can someone capture when a visual element measure are invalidated? Let's say I'm building an expandable content which displays a "Show more" button when the content height exceeds some value, how can I react to measure changes if `MeasureInvalidated` is not working at all?

The actual native elements _are_ being invalidated, and are updating. It's just that the cross-platform "MeasureInvalidated" event isn't firing. 

If someone _wanted_ to make that happen, the place to do it would probably be in Layout.cs: https://github.com/dotnet/maui/blob/a01e1ee184d9dcde58f6d6f7d14f03a3222378c3/src/Controls/src/Core/Layout/Layout.cs#L219

The OnAdd, OnInsert, etc. would need to call a method "OnMeasureInvalidated" which could raise that event. 

Now, it depends on what you're ultimately trying to do, but reacting to a measure invalidation in an event is almost never the answer you're looking for. (There may be exceptions, and yours may be one of them; I don't know because I don't know what you're trying to accomplish.) Usually, the way to respond to measure invalidation is to measure and re-layout the component, which is already happening. If you need to customize the logic for that, overriding MeasureOverride is probably what you're looking for. 

> On top of that, the background is still showing when I use layout compression.. how's that possible? is layout compression not working?

Layout compression doesn't do anything in the newer .NET MAUI components; it would only apply if you're using something from Compatibility.

**Comment by albyrock87** [comment]
@hartez I didn't know that, so I really appreciate your kind and precise answer which clarified the situation 100%.

It's unbelievable that they removed such an important feature like layout compression (especially without saying it), because now native platform will have more (useless) layers to render and that will slow down the application performance a lot.

I will try to achieve the `MeasureInvalidated` functionality by adding a "content holder" with a new event which triggers on `MeasureOverride`.

Thanks again!

**Comment by albyrock87** [comment]
In the end I created a custom "content holder" layout and during the `Size Measure(double widthConstraint, double heightConstraint)` pass I'm checking of the content size changed, if so, I'm raising a new event on the layout using `Dispatcher.DispatchDelayed` to do that.

It works well, and it's enough to do many things now I'm just worried about the number of native views MAUI creates and how complex screens will be slow for sure.

**Comment by hartez** [comment]
> It's unbelievable that they removed such an important feature like layout compression (especially without saying it), because now native platform will have more (useless) layers to render and that will slow down the application performance a lot.

I don't know that it was that important - the MAUI architecture already drops the number of rendering layers by a _lot_ simply by eliminating the old renderers (everything is essentially what used to be called "fast renderers" on Android now). It's like half as many layers out of the gate. 

The way "compression" worked in Forms relied on Forms's out-of-band layout process, which caused a ton of other problems. MAUI uses a simpler layout process more closely integrated with the native platforms' processes, but compression would have to be implemented differently. It could be done, but someone would have to work out whether it's worth the added complexity. 

Off the top of my head, I suspect it could be done entirely at the LayoutHandler level, and you could toss out the whole IsHeadless property and just auto-detect opportunities to use it (layouts wouldn't be eligible if they set backgrounds, or had gesture detectors, etc.). Which would avoid the problem of people marking things headless which shouldn't be. 

And you could actually make it work on all the platforms, not just Android and iOS.

**Comment by RoiChen001** [comment]
Can repro this issue at iOS platform on the latest 17.10.0 Preview 3(8.0.7&8.0.20).
