### ISSUE TITLE
Add MediaPicker option to pick or capture

### ISSUE THREAD

**Issue by airwedge1** [dotnet/maui#20180]
### Description

Create a method MediaPicker PickOrCapturePhotoAsync.  Or pass it in as an option to CapturePhoto / PickPhoto

There needs to be a way to allow CapturePhotoAsync to redirect to PickPhotoAsync instead.  I realize that we can prompt the user beforehand which one they want to do but that results in a very clunky user interface.

Essentially I want to replicate what happens with HTML ```<input type="file" capture="environment" /> ``` You get a prompt that allows the user to either take a picture or open the gallery.  

### Public API Changes

```csharp

FileResult photo = await MediaPicker.Default.PickOrCapturePhotoAsync(); //Add PickOrCapturePhotoAsync
```

### Intended Use-Case

Allow a user to either pick or capture a photo without a clunky user interface.

**Comment by joewolford** [comment]
I second this. A file/media picker should be able to be integrated or there should at least be a way to navigate out of the photo picker.

**Comment by jfversluis** [comment]
I'm not sure how this is any different from `MediaPicker.CapturePhotoAsync()`? I'm not familiar with that HTML input tag, but I just tried it and it seems to just open my camera and take a picture on iOS? That's exactly what `CapturePhotoAsync` does?

Could you please add some more information here on how you would like this to work and what value that adds?

**Comment by airwedge1** [comment]
I am just looking for the PickPhotoAsync to have a button on it that will launch CapturePhotoAsync instead.  See the below mock up.   In many use cases the primary use case is to snap a picture, but in some rare cases the user will instead select from the gallery.  If we need to allow both use cases with the current options we have to first prompt with a different screen do you want to pick from gallery or take a photo.  Instead I want to default to taking a picture but still have the option to switch to pick.  Needing the extra click leads to a clunky user interface.  I hope that makes sense.

![image](https://github.com/dotnet/maui/assets/43187078/d8cef08e-ca29-4557-9f6a-9c2d3374d0c4)

**Comment by jfversluis** [comment]
> Needing the extra click leads to a clunky user interface.

Thats a matter of taste I would say. Personally I don't feel there is anything wrong with selecting what you want to do first. You see that in a lot of app. In fact, if I have an actual upload button in HTML from iOS it will also ask me what I want to do first

![image](https://github.com/dotnet/maui/assets/939291/82a7f017-a5e0-4582-b873-748bd764ea73)

And the HTML tag you mention also doesn't have that option to select something from the gallery.

That means, if we want to implement something like this we will need to implement our own control for it as there is nothing available on the platform to provide this for us. And that is typically not something we will want to do.

**Comment by airwedge1** [comment]
Bummer.  We'll figure something else out.
