### ISSUE TITLE
ActivityIndicator IsRunning Property Binding doesn't work

### ISSUE THREAD

**Issue by ShariatPanah** [dotnet/maui#20184]
### Description

i'm using an ActivityIndicator and bind the IsRunning Property to my Boolean Property of ViewModel, in Android ActivityIndicator wont take the value of my property, i manually set the IsRunning to True in xaml and it works, but by binding it to a boolean value nothing shows up

tested on Windows and it works just fine

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.0, Windows

**Comment by kacper51011** [comment]
You can actually try to use `await Task.Yield()` or `await Task.Wait(1)` inside the method after changing the value of binded bool property.

**Comment by ShariatPanah** [comment]
i created a sample and it worked on android too, so i don't know maybe my bad, sorry, i'm closing this
