### ISSUE TITLE
Pre-filled Entry ignores TextColor on iOS

### ISSUE THREAD

**Issue by borrmann** [dotnet/maui#20196]
The linked isssue from this comment was closed as Duplicate by referencing some issue about a Button. This issue was about an Entry however, Another user commented they also have this issue. I do to. Both Style and Setter of the TextColor of an Entry are ignored if the Entry is filled by code. The same styling works for Editors/ Labels etc.

_Originally posted by @arnaudaug in https://github.com/dotnet/maui/issues/17818#issuecomment-1775580788_

Repo:
https://github.com/borrmann/EntryText

**Comment by borrmann** [comment]
As a workaround I set the TextColour again in an EntryHandler

```
 protected override void ConnectHandler(MauiTextField platformView)
 {
     base.ConnectHandler(platformView);

     if (platformView != null)
     {       
            platformView.TextColor = ColourResources.Text.ToPlatform();
     }
 }
```

**Comment by hayer** [comment]
Could you describe the symptoms or take a screenshot? Currently having problems with text in `Entry` appearing transparent/white/invisible but having an hard time reproducing it.

You can place the cursor inside the Entry by tapping it so there is text inside it. The placeholder does not appear. Going in and out of the app seems to fix it.

**Comment by borrmann** [comment]
The App is in Light mode in this case, while the system default is in Dark Mode.
It is a Form, where the Entries are filled in OnNavigatedTo after an async API call. 
As you can see in the first example, after removing the White Text and typing, the text Color changes to dark, as it should have been from the beginning.

https://github.com/dotnet/maui/assets/20472867/98032e0d-645f-448f-b778-d4cbfc608cfa


With aboves Entry Handler it looks like this:

https://github.com/dotnet/maui/assets/20472867/9b51f4ca-06d3-476f-bee3-a0c8ccdfef95

**Comment by borrmann** [comment]
probably fixed with https://github.com/dotnet/maui/pull/20100

**Comment by hayer** [comment]
App sets light mode `UserAppTheme = AppTheme.Light;`.
Changed system to dark theme, text "disappeared". Thanks for the solution @borrmann

**Comment by borrmann** [comment]
All it takes is:
```
<Entry TextColor="Red" x:Name="E_RedText"/>
protected override async void OnNavigatedTo(NavigatedToEventArgs args)
{
    base.OnNavigatedTo(args);

    await Task.Delay(2000);
    E_RedText.Text = "I must be red";
}
```
There may be a race condition as the error does not occur without the Delay.
I have uploaded a git repo and updated the issue

**Comment by dinisvieira** [comment]
I'm also having this issue.
In our case we have two buttons ( + and - ) to set a numeric value on an Entry and the color is incorrect if we use those buttons to set the value programmatically.
Setting the value directly on the Entry results in the correct Text Color.

**Comment by nathenxbrewer** [comment]
> As a workaround I set the TextColour again in an EntryHandler
> 
> ```
>  protected override void ConnectHandler(MauiTextField platformView)
>  {
>      base.ConnectHandler(platformView);
> 
>      if (platformView != null)
>      {       
>             platformView.TextColor = ColourResources.Text.ToPlatform();
>      }
>  }
> ```

Could you please show how to implement this handler? Having trouble figuring that out. This issue is affecting my app. Thanks

**Comment by nathenxbrewer** [comment]
I was able to get around this by using the previous page to query my data async and then passing the data using the IQueryAttributable interface. Seems to definitely be a race condition and setting the value in the constructor without any async work being done allows the TextColor work properly.
