### ISSUE TITLE
Suggestion: Add "Mobile" tag to MAUI project templates

### ISSUE THREAD

**Issue by MSLukeWest** [dotnet/maui#20190]
### Description

In the VS new project dialog, if you set the "Project Types" filter to "Mobile" it will show yoy every .NET iOS and Android template, and every legacy Xamarin template, but not the MAUI templates.  I think we should show MAUI projects here as well.

![image](https://github.com/dotnet/maui/assets/42553283/af391195-8654-4f07-b320-853afe795e66)

### Public API Changes

N/A

### Intended Use-Case

New project creation in Visual Studio.

**Comment by jfversluis** [comment]
Fixed by #20191
