### ISSUE TITLE
Windows 11 Unhandled exception when we try run MauiWinUI

### ISSUE THREAD

**Issue by aokocax** [dotnet/maui#2020]
When I run the Maui WinUI project under Windows 11, I get the attached error.
I tried with both visual studio 2022 preview and Visual Studio 2019 preview (MSIX and Reunion Installed / Maui check is ok)
There is no problem in Windows 10. Thank you.
  
![hand](https://user-images.githubusercontent.com/1059475/128821209-2311cea3-bc87-4625-b181-ea54e286380f.jpg)
![maui](https://user-images.githubusercontent.com/1059475/128822372-c9da71d2-d205-4143-820a-756edc7f5d01.jpg)

**Comment by Redth** [comment]
This is fixed in later releases.
