### ISSUE TITLE
MAUI Editor don't show cursor(carter) position and changed symbols on edit.

### ISSUE THREAD

**Issue by Jurashikku** [dotnet/maui#20209]
### Description

I create Editor
```
 <Editor x:Name="LuaViewEditor" IsEnabled="true" VerticalOptions="Fill" 
                        HorizontalOptions="Fill" AutoSize="TextChanges"  TextColor="Black"
                                TextTransform="None" Keyboard="Text"/>
```
Set TextTransform to None.

Load xml file as string, but when try edit it like, set " editor changed it to » 
<img width="1440" alt="Снимок экрана 2024-01-28 в 17 26 58" src="https://github.com/dotnet/maui/assets/51206075/a73a3708-e821-4f56-b1de-911a68e610cb">

Mb i miss some more setting but don't find in msdn

### Steps to Reproduce

1. Create MauiApp
2. Add Editor
3. Load some xml file to string and append it to text
4. Try add " to text.

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS 13.6.3 (22G436)

**Comment by drasticactions** [comment]
AFAIK TextTransform is not the right API for what you want to do. That affects the literal text (like always enabling upper or lower case) and not special characters.

Those characters (Quotes and Dashs) are automatically updated by iOS/Catalyst when you enter them. MAUI has no API that sets those settings, but you can touch them by invoking the handler

```csharp
	public static MauiApp CreateMauiApp()
	{
		Microsoft.Maui.Handlers.EditorHandler.Mapper.AppendToMapping("SmartQuote", (handler, view) =>
		{
			#if IOS || MACCATALYST
			handler.PlatformView.SmartQuotesType = UIKit.UITextSmartQuotesType.No;
                        // Also not set by MAUI directly.
			handler.PlatformView.SmartDashesType = UIKit.UITextSmartDashesType.No;
			handler.PlatformView.SmartInsertDeleteType = UIKit.UITextSmartInsertDeleteType.No;
			#endif
		});
         ...
``` 

I'm not sure what API would make the most sense for MAUI to access and set these values, but by using the handler you can turn off that behavior, then it should work as expected.

**Comment by Jurashikku** [comment]
> AFAIK TextTransform is not the right API for what you want to do. That affects the literal text (like always enabling upper or lower case) and not special characters.
> 
> Those characters (Quotes and Dashs) are automatically updated by iOS/Catalyst when you enter them. MAUI has no API that sets those settings, but you can touch them by invoking the handler
> 
> ```cs
> 	public static MauiApp CreateMauiApp()
> 	{
> 		Microsoft.Maui.Handlers.EditorHandler.Mapper.AppendToMapping("SmartQuote", (handler, view) =>
> 		{
> 			#if IOS || MACCATALYST
> 			handler.PlatformView.SmartQuotesType = UIKit.UITextSmartQuotesType.No;
>                         // Also not set by MAUI directly.
> 			handler.PlatformView.SmartDashesType = UIKit.UITextSmartDashesType.No;
> 			handler.PlatformView.SmartInsertDeleteType = UIKit.UITextSmartInsertDeleteType.No;
> 			#endif
> 		});
>          ...
> ```
> 
> I'm not sure what API would make the most sense for MAUI to access and set these values, but by using the handler you can turn off that behavior, then it should work as expected.

So, i will try it. 

But what about "caret" ? In window it's shown.

**Comment by drasticactions** [comment]
I'm not sure what you mean

<img width="455" alt="image" src="https://github.com/dotnet/maui/assets/898335/a426f4e6-73bb-4d82-8352-cadbc67b2ea8">

There is a cursor for text input for the current position. Seeing that you have a "light" theme when using a global dark setting, my guess would be that you didn't change the color for it so it's not showing on your view.

<img width="485" alt="スクリーンショット 2024-01-30 12 07 00" src="https://github.com/dotnet/maui/assets/898335/f8fbf7dc-3607-4f69-b4e2-7f46786fd807">

Setting the TintColor would fix it.
