### ISSUE TITLE
@samhouts How/When can we expect this fix in a upcoming update? Ive build my app with the latest version of MAUI 8.0.3 on VS2022 Preview. But i still have the borders on android.

### ISSUE THREAD

**Issue by zh0018** [dotnet/maui#20214]
@samhouts How/When can we expect this fix in a upcoming update? Ive build my app with the latest version of MAUI 8.0.3 on VS2022 Preview. But i still have the borders on android.

_Originally posted by @npostma in https://github.com/dotnet/maui/issues/17448#issuecomment-1813887039_

**Comment by drasticactions** [comment]
It's not in 8.0.3

https://github.com/dotnet/maui/releases/tag/8.0.6

It's tagged in 8.0.6. Try upgrading to the newest net8.0 version.

**Comment by jfversluis** [comment]
Assuming this is fixed in the mentioned version, if not, please open a new issue with all the details referring back to the older issue so we can mark it as a regression appropriately.
