### ISSUE TITLE
[iOS] Custom Debug Configuration Issue & Crash

### ISSUE THREAD

**Issue by RobFrancisAu** [dotnet/maui#20211]
### Description

Hi All,

I am trying to create a custom debug configuration called `DemoDebug` in a Maui project.
When trying to run the project on an iOS simulator (I have not tried other platforms), I have the two following issues;

The property group I am using in my `.csproj` looks like this
```
<PropertyGroup Condition=" '$(Configuration)' == 'DebugDemo' ">
        <DefineConstants>DEBUGDEMO</DefineConstants>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <MtouchDebug>true</MtouchDebug>
</PropertyGroup>
```

1. When running using this configuration, without including `MtouchDebug`, the debugger is never attached and therefore no breakpoints are hit.
2. Adding `<MtouchDebug>true</MtouchDebug>` crashes the app at startup.

I have attached a sample project. here [CustomDebugConfiguration.zip](https://github.com/dotnet/maui/files/14077979/CustomDebugConfiguration.zip) 

Thanks in advance.

### Steps to Reproduce

1. Create a new Maui project.
2. Create a copy the Debug configuration named DebugDemo.
3. Attempt to hit a breakpoint

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Currently unable to find a workaround.

**Comment by drasticactions** [comment]
Can you try this with a net8.0-ios app (`dotnet new ios`) that doesn't include the MAUI UI framework?

**Comment by RobFrancisAu** [comment]
@drasticactions 

This works 
[CustomConfigurationIos.zip](https://github.com/dotnet/maui/files/14081704/CustomConfigurationIos.zip).
`<MtouchDebug>true</MtouchDebug>` is required to enable the debugger, as expected. However it does not crash the app as it does in Maui.

**Comment by rolfbjarne** [comment]
We set `MtouchDebug=true` if `Configuration="Debug"`, so for other debug-like configurations with a different name you'll have to set it in the csproj (there's an issue in dotnet/sdk about improving this: https://github.com/dotnet/sdk/issues/31918).

Setting `MtouchDebug=true` shouldn't cause a crash, do you have a crash report / stack trace?

**Comment by RobFrancisAu** [comment]
Here is a crash report. 
[Crash_Report.txt](https://github.com/dotnet/maui/files/14090880/Crash_Report.txt)

And a snippet of the device logs around the crash.
<img width="1722" alt="Console" src="https://github.com/dotnet/maui/assets/49009679/18c2dcc2-cd89-4bc8-83a8-8cfa2b31f631">

**Comment by rolfbjarne** [comment]
Does it help if you clean the project first?

**Comment by RobFrancisAu** [comment]
> Does it help if you clean the project first?

Nope, tried all of that. 

- Clean & rebuild.
- Delete the bin & obj folders, force Nuget restore, rebuild etc...

Is this not reproducible at your end then with the project I provided?

I created the sample app (attached in the first post) to ensure I could reproduce it. The problem actually became apparent in a different project I was working on.

**Comment by rolfbjarne** [comment]
@RobFrancisAu which IDE and OS are you using?

**Comment by RobFrancisAu** [comment]
> @RobFrancisAu which IDE and OS are you using?

JetBrains Rider : 2023.3.3
MacOS : 14.2.1

**Comment by rolfbjarne** [comment]
@drasticactions you said you could reproduce a crash; which IDE and OS was that with? Do you have a stack trace / crash report?

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio for mac 17.6.10(build428). Can not repro this issue with Android/iOS platforms.(Maui Version:8.0.14/8.0.3/8.0.0-rc.2.9530)

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.6.14(build413)(8.0.82 & 8.0.72 & 8.0.7 & 8.0.3). Not repro on 8.0.82 and 8.0.72 version. 8.0.3 and 8.0.7 do have this issue.
