### ISSUE TITLE
Can't use LinearGradientBrush as Button Background on iOS

### ISSUE THREAD

**Issue by alececihs** [dotnet/maui#20218]
### Description

Works on Android (tested on Pixel 7 API 34 emulator)
![android](https://github.com/dotnet/maui/assets/107032142/ab1d4b89-d4b1-4e95-acec-af16d39e3011)
but on iOS (tested on iPhone 15 Pro Max iOS 17.2 emulator)
![ios](https://github.com/dotnet/maui/assets/107032142/f6aa184d-578f-4fa7-90e2-b4a2f916ac60)
there is something wrong...

### Steps to Reproduce

1. Create a Button.
2. Set Background property to LinearGradientBrush.
3. Run on iOS.

### Link to public reproduction project repository

https://github.com/alececihs/MauiButtonsTest/

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by PontusHolmberg** [comment]
I'm having the same issue. Hope this gets resolved soon.

**Comment by carljohansen** [comment]
I've had the same issue ever since I started working on the iOS version of my app (Android works fine).  I've noticed that the buttons get drawn correctly if I somehow cause a refresh of the page (e.g. by navigating to another page and then back).

**Comment by WebGoose** [comment]
This is happening with a few different controls. I have the same problem with grids, labels and buttons so I'm having to use solid colours on iOS for now.

**Comment by cris-m** [comment]
I am having the same issue with iOS 17.2. Android version is drawn perfectly.

```xml
<StackLayout>
    <Button Text="Transfer">
        <Button.Background>
            <LinearGradientBrush StartPoint="0,0" EndPoint="1,0.5">
                <GradientStop Color="#434A65" Offset="0"/>
                <GradientStop Color="#BC2929" Offset="1"/>
            </LinearGradientBrush>
        </Button.Background>
        <Button.CornerRadius>
            <CornerRadius TopLeft="10" TopRight="10" BottomLeft="10" BottomRight="10"/>
        </Button.CornerRadius>
    </Button>

    <Button Text="Request">
        <Button.Background>
            <LinearGradientBrush StartPoint="0,0" EndPoint="1,0.5">
                <GradientStop Color="#434A65" Offset="0"/>
                <GradientStop Color="#32C397" Offset="1"/>
            </LinearGradientBrush>
        </Button.Background>
        <Button.CornerRadius>
            <CornerRadius TopLeft="10" TopRight="10" BottomLeft="10" BottomRight="10"/>
        </Button.CornerRadius>
    </Button>

    <Button Text="Withdraw">
        <Button.Background>
            <LinearGradientBrush StartPoint="0,0" EndPoint="1,0.5">
                <GradientStop Color="#434A65" Offset="0"/>
                <GradientStop Color="#2079DF" Offset="1"/>
            </LinearGradientBrush>
        </Button.Background>
        <Button.CornerRadius>
            <CornerRadius TopLeft="10" TopRight="10" BottomLeft="10" BottomRight="10"/>
        </Button.CornerRadius>
    </Button>
</StackLayout>

```
<img width="400" src="https://github.com/dotnet/maui/assets/29815096/9b6d420d-ae98-48ab-aff7-b6bb57203bd2" alt="iOS">

**Comment by archergod** [comment]
I am having same issue.

**Comment by grabnerM** [comment]
What is the status of this issue? Is there a solution or any estimated time remaining?

**Comment by afk013** [comment]
Not ideal but wrapping the control within a [Border](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/border?view=net-maui-8.0) seems to keep the gradient contained. 

You have to use the border stroke shape to control gradient overflow.

Before
<img src="https://github.com/dotnet/maui/assets/8859410/d2979c2c-149b-4578-96bd-fc40bc093c5f" height="400" />
```
<Button StyleClass="FilledButton" Text="{Binding Text}" IsEnabled="{Binding IsEnabled}">
    <Button.Background>
        <LinearGradientBrush 
            StartPoint="0,0.5"
            EndPoint="1,0.5"
        >
            <GradientStop 
                Color="Pink"
                Offset="0"
            />
            <GradientStop 
                Color="Purple"
                Offset="1"
            />
        </LinearGradientBrush>
    </Button.Background>
</Button>
```

After
<img src="https://github.com/dotnet/maui/assets/8859410/d580cde0-b240-4287-a9bc-20657eb09f72" height="400" />

```
<Border
    Padding="0"    
    StrokeShape="RoundRectangle 40,40,40,40"
    StrokeThickness="0"
>
    <Button StyleClass="FilledButton" Text="{Binding Text}" IsEnabled="{Binding IsEnabled}">
        <Button.Background>
            <LinearGradientBrush 
                StartPoint="0,0.5"
                EndPoint="1,0.5"
            >
                <GradientStop 
                    Color="Pink"
                    Offset="0"
                />
                <GradientStop 
                    Color="Purple"
                    Offset="1"
                />
            </LinearGradientBrush>
        </Button.Background>
    </Button>
</Border>
```

**Comment by grabnerM** [comment]
@afk013 Thank you for this workaround, but this can´t be the official way to go..  We are moving our apps from xamarin to maui and we already got lots of things to check like change StackLayout with AndExpand to a Grid. We can´t set a Border around every element wich uses a gradient. Especially after it works correct for Android but not on iOS.

Maybe some of the MAUI/Microsoft guys could look into this.

**Comment by archergod** [comment]
> @afk013 Thank you for this workaround, but this can´t be the official way to go.. We are moving our apps from xamarin to maui and we already got lots of things to check like change StackLayout with AndExpand to a Grid. We can´t set a Border around every element wich uses a gradient. Especially after it works correct for Android but not on iOS.
> 
> Maybe some of the MAUI/Microsoft guys could look into this.

The problem discuss in this thread is limited to Buttons only. 

And you are welcome to wait for MS to fix it, as it on official git of the team working on it, and it is been here for 6 months already. So I suggest to use workaround if you really want gradient button. Virtually no other option.

**Comment by carljohansen** [comment]
The workaround has put me back in business; thanks!  I had to be careful about matching the `Button` and `Border` properties, e.g. `MaximumHeightRequest`.  My `Button` has a `CornerRadius` of 8, so setting the `Border`'s `StrokeShape` to `RoundRectangle 16,16,16,16` seemed to worked.  Don't hold your breath waiting for MSFT to provide a proper fix.

**Comment by Dry-Rusk** [comment]
any updates here?

**Comment by eyeveye** [comment]
Using LinearGradientBrush in iOS button, imagesource also will not be visible.
