### ISSUE TITLE
CollectionView ItemTemplate OnSelectTemplate is not called when the ItemsSource is updated

### ISSUE THREAD

**Issue by CyrilleMancini** [dotnet/maui#20220]
### Description

I've created a simple page with elements extracted from one of my other project.

The problem arrived durring the usage of Net7.0 and never stoped since. 

That part of code were functional in previous versions of the application running under Net7. 
The issue arose during the operation of Net7 and has persisted ever since

The issue is present on the Windows Desktop platform. Here is my understanding of the problem:
When the ObservableCollection is populated for the first time with items of either expected type, OnSelectTemplate is correctly called for each item.

When using buttons to modify the content of the bound list on ItemSource, OnSelectTemplate is not consistently called on the Windows platform, leading to binding errors and display issues.

You can show the result for both platform in the video linked

https://github.com/dotnet/maui/assets/94325861/0cf0387d-7cf0-48f4-a836-e78b79eccfbf

The first part shows the expected behavior on Android and the second part shows the windows app's behavior 

### Steps to Reproduce

1. Open the linked solution [MauiItemTemplateSelector.zip](https://github.com/dotnet/maui/files/14083253/MauiItemTemplateSelector.zip)
2. Reproduce the actions shown in the video.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

I'm currently looking for a workaround but I didn't found it yet.

**Comment by CyrilleMancini** [comment]
I finally found something that works. 
If you apply the linked patch, the behavior seems to be fixed. 

[0002-Fix-bad-behavior.patch](https://github.com/dotnet/maui/files/14192711/0002-Fix-bad-behavior.patch)

The patch moves the templates declarations from MainPage.xaml 
```
  <ContentPage.Resources>
        <DataTemplate x:Key="orderHeaderTemplate"
                      x:DataType="local:OrderHeaderItemList">
            <Border Margin="1" 
                    Background="White"
                    Padding="4">
....
....
```

To a separate ContentView and bind it with 

```
<DataTemplate x:Key="orderHeaderTemplate"x:DataType="local:OrderHeaderItemList">
        <local:OrderHeaderItemView HeaderItem="{Binding .}"></local:OrderHeaderItemView>
</DataTemplate>
<DataTemplate x:Key="orderLineTemplate" x:DataType="local:OrderLineItemList">
       <local:OrderLineItemView LineItem="{Binding .}"></local:OrderLineItemView>
</DataTemplate>
```

And the selector is also changed from

```
public DataTemplate OrderHeaderTemplate { get; set; }
public DataTemplate OrderLineTemplate { get; set; }
```
To

```
public DataTemplate OrderHeaderTemplate { get; set; } = new DataTemplate(typeof(OrderHeaderItemView));
public DataTemplate OrderLineTemplate { get; set; } = new DataTemplate(typeof(OrderLineItemView));
```

Hoping it will help you.

**Comment by ninachen03** [comment]
I cannot repro this issue on the latest 17.12.0 Preview 1.0 (8.0.80), but repo in Net7 SDK.
