### ISSUE TITLE
[iOS] Keyboard hides Entry on Grid

### ISSUE THREAD

**Issue by DonkeyKongJr** [dotnet/maui#20231]
### Description

When using an Entry field on the bottom of a grid on iOS, the Keyboard overlays the Entry field. On Android everything seems to be working fine.

Android:
![Screenshot_1706542669](https://github.com/dotnet/maui/assets/29427429/ba7d40a1-b486-437e-bde8-2f2788e64629)
iOS:
![iOS Maui without Keyboard](https://github.com/dotnet/maui/assets/29427429/e6ef3f55-6cc7-43dc-8e26-74d196166618)
![iOS Maui with Keyboard](https://github.com/dotnet/maui/assets/29427429/ac4eef2a-d10a-405f-81c9-47807a38841a)

### Steps to Reproduce

1. Create a new MAUI Project.
2. Add a Grid Layout.
3. Add a Entry Element on the bottom.
4. Select iOS as target.
5. Run the app.
6. Click on the bottom entry field.

See demo project below:

[MauiApp1.zip](https://github.com/dotnet/maui/files/14086481/MauiApp1.zip)

### Link to public reproduction project repository

https://github.com/DonkeyKongJr/MauiKeyboardIssue.git

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.x

### Did you find any workaround?

No.

**Comment by DonkeyKongJr** [comment]
We do get in our customer application a slightly different behavior. The iOS keyboards pops up, but covers the input halfway through. In this particular place, we use an Editor. The BorderlessEditor inherits directly from Editor.

```
<controls:BorderlessEditor
    HorizontalOptions="Fill"
    VerticalOptions="Center"
    Keyboard="Chat"
    AutoSize="TextChanges"
    BackgroundColor="Transparent"
    TextColor="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource White}}"
    Text="{Binding NewMessageText}"
    MaxLength="400">
    <controls:BorderlessEditor.Behaviors>
        <fixes:TapToCloseBehavior />
    </controls:BorderlessEditor.Behaviors>
</controls:BorderlessEditor>
```

![2024-01-30 09_25_33-iPhone 15 Pro Max iOS 17 2](https://github.com/dotnet/maui/assets/29427429/103acdd0-29c8-485a-8275-28b323fe6f67)

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by DonkeyKongJr** [comment]
I just tried it out on .NET MAUI 8.0.7-preview.9929 and the issue seems to be resolved.

![2024-01-31 10_05_13-iPhone 15 Pro Max iOS 17 2](https://github.com/dotnet/maui/assets/29427429/fd5328d3-72d5-498b-8f96-1fcf5011699c)

**Comment by borrmann** [comment]
@PureWeen I have tested it with the nightly build too. It seems fixed when predictive text is turned on in device settings, but not when they are turned off and e.g. an AutoFill mode is used on the Entry or the Keyboard Height changes (e.g. by switching to Emoji keyboard). 
See attached video
In the beginning it works as expected.
Then predictive text is turned off in device settings.

1. After that, the keyboard is above the entry, when a suggestion pops up with a delay.
2. The keyboard is always above the entry, if the emoji keyboard is opened.

https://github.com/dotnet/maui/assets/20472867/4aa1fc68-a291-4e49-84f6-330d7db1f5f2

**Comment by DonkeyKongJr** [comment]
> Then predictive text is turned off in device settings.

I can confirm that toggling the predictive text feature negatively affects the keyboard and the positioning of the input element. 


https://github.com/dotnet/maui/assets/29427429/a18719cc-8949-4cf6-9590-d0a6c3ef42b5

**Comment by borrmann** [comment]
I found this Stackoverflow post. This seems like the default behaviour in swift is actually that the keyboard is included in the Safe Area. Is there a way to turn this default behaviour on?

[stackoverflow](https://stackoverflow.com/questions/65456168/swiftui-why-does-the-keyboard-pushes-my-view/65456215#65456215)

**Comment by QianaJiao** [comment]
This is the results of 8.0.6
![image](https://github.com/dotnet/maui/assets/91244512/321fdf83-6f32-494d-85e4-57fcd37fbb15)
It does not repro on 8.0.14.
![image](https://github.com/dotnet/maui/assets/91244512/b7d48d6e-9542-4d6b-a076-5b93fefed34a)

(As mentioned in the above comment, after switching apps, the keyboard will still overlap the content)
