### ISSUE TITLE
[Bug] FlexLayout NullReferenceException with BindableLayout

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#2023]
### Description
NRE when using BindableLayout with FlexLayout

### Steps to Reproduce

Run the attached sample on Android (haven't tested iOS)

[aaaboop.zip](https://github.com/dotnet/maui/files/6962701/aaaboop.zip)

### Expected Behavior
You should see a layout of colored boxes

### Actual Behavior
Null Reference Exception

**Comment by davidortinau** [comment]
I just figured out this is what crashes WeatherTwentyOne also. Checked main and still occurs. Preview 6 was fine.

Confirmed flipping to a StackLayout worked.

https://github.com/davidortinau/WeatherTwentyOne/blob/main/src/WeatherTwentyOne/Pages/FavoritesPage.xaml#L106

Sadly, error messages were really unhelpful.

![image](https://user-images.githubusercontent.com/41873/129233087-217f2e6a-d028-4251-8adf-4824289737a7.png)
