### ISSUE TITLE
Android Casting in .Net Maui 8 using  Xamarin.GooglePlayServices.Cast.Framework Does Not work

### ISSUE THREAD

**Issue by Jricklefs** [dotnet/maui#20233]
### Description

Android Casting in .Net Maui 8 using  Xamarin.GooglePlayServices.Cast.Framework Does Not work.   Throws error when trying to  get CastContext. 

### Steps to Reproduce

1. Create .Net Maui App. 
2.  Download the Nuget Packages for  Xamarin.GooglePlayServices.Cast.Framework
3. Open Platforms/Android/MainActivity.cs file. 
4. Add  OnCreate Method to Android/MainActivity.cs. 
`        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            // Initialize CastContext
            var castcontext = CastContext.GetSharedInstance(this.ApplicationContext);
        }`
5. Attempt to deploy to android device. 

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

I have not currently found a work aroud.

**Comment by drasticactions** [comment]
If you do this in a .NET 8 Android app that doesn't use the MAUI UI framework (`dotnet new android`), does the same error throw? This doesn't seem like something that would be caused by code in this repo, it would either be in [xamarin/GooglePlayServicesComponents](https://github.com/xamarin/GooglePlayServicesComponents/) or something else.

**Comment by moljac** [comment]
> If you do this in a .NET 8 Android app that doesn't use the MAUI UI framework (`dotnet new android`), does the same error throw? This doesn't seem like something that would be caused by code in this repo, it would either be in [xamarin/GooglePlayServicesComponents](https://github.com/xamarin/GooglePlayServicesComponents/) or something else.
> 

Minimal repro sample would help.

> cc @moljac if you know anything about this

Nope. Never seen this one.

I would move it to https://github.com/xamarin/GooglePlayServicesComponents/ , but I think moving across orgs will not work.

@Jricklefs Please close it here and open new issue in GPS-FB-MLKit repo. And sample would help.

Thanks Joe and Tim

**Comment by Jricklefs** [comment]
I have opened a bug on GPS  closing this to move over there.
