### ISSUE TITLE
Icons in Shell TabBar and AppBar are no longer updated after changing the UserAppTheme

### ISSUE THREAD

**Issue by davidschachtschabel** [dotnet/maui#20243]
### Description

I have built an app with theme switching by user interaction with a button. When the user clicks the button, the UserAppTheme is set to AppTheme.Light or AppTheme.Dark based on the current theme at app start. To change the color of my icons, I used the AppThemeBinding XAML markup extension and set "Light" to black and "Dark" to white.

If the app is in the light theme and the user switches to the dark theme, the icons will be black instead of white. If the user first navigates to another page, performs a theme switch, and navigates back to the main page, you can see that the icon in the app bar will change to the right color defined in AppThemeBinding, but the icons in the shell tap bar won't change.

In this screenshot you can see the app theme at app start.
![Bildschirmfoto 2024-01-30 um 12 36 14](https://github.com/dotnet/maui/assets/84776118/24a86056-9f3e-4821-99cd-aa401cb7ac68)

This screenshot shows the state after a theme change on the main page:
![Bildschirmfoto 2024-01-30 um 12 37 14](https://github.com/dotnet/maui/assets/84776118/9460d248-7ee9-4b31-b8ee-fd529bd80a70)

This screenshot shows the state after a theme switch with back navigation:
![Bildschirmfoto 2024-01-30 um 12 37 47](https://github.com/dotnet/maui/assets/84776118/191aeacf-0d05-4943-a657-c8dfc997a726)

### Steps to Reproduce

Repo steps for the main page behavior:
1. Click the "Change Theme" button on the main page.
2. The theme will change, but the icons will not be white in dark theme or black in light theme.

Repo steps for the behavior with navigation:
1. Click the icon in the application bar to navigate to another page.
2. Change the theme by clicking the "Change Thememode" button
3. Navigate back and you can see that only the icon in the application bar has the right color.

### Link to public reproduction project repository

https://github.com/davidschachtschabel/UserAppThemeTest

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 1.0(8.0.7). Repro on iOS 17.2 and MacCatalyst, not repro on  Windows 11 and Android 14.0-API34 with below Project:
[UserAppThemeTest.zip](https://github.com/dotnet/maui/files/14534056/UserAppThemeTest.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/214d2bfa-7f5b-48da-b897-04bc445303d3)
