### ISSUE TITLE
Migrate legacy UI tests to Appium

### ISSUE THREAD

**Issue by jfversluis** [dotnet/maui#20245]
To be more aligned with our current/new UI tests, we want to migrate our legacy tests also to Appium. Below are the (rough) steps outlined to achieve that.

* [x] Setup a new space for legacy tests based on appium
This would basically be a complete replica of our current appium testing because that already models the gallery (we could probably generalize out this library a bit). Would it make sense to just split up our current Appium tests? Test Explorer doesn't really work very well with our single project concept. We could then just put them all into the current runner and just into a different category. 
* [x] For this project though we'd use separate project heads for the testing frameworks so we can if/def like we have in legacy
* [ ] Copy the entire shared "Issues" folder into one of the projects
[maui/src/Compatibility/ControlGallery/src/Issues.Shared at main · dotnet/maui (github.com)](https://github.com/dotnet/maui/tree/main/src/Compatibility/ControlGallery/src/Issues.Shared)
* [ ] Add that folders with a glob pattern to the other project
* [x] And now starting changing the APIs over to the new Appium APIs we have
* [x] Investigate https://github.com/dotnet/maui/issues/19073 . Currently the appium tests run 131 tests in 90 minutes and Xamarin.UITest runs our gallery of 530 tests in 120 minutes
* [x] Look at adding Categories so we can parallelize the test runs for groups of tests

**Comment by jsuarezruiz** [comment]
Created new projects for legacy tests based on Appium here https://github.com/dotnet/maui/tree/fix-20245

**Comment by jsuarezruiz** [comment]
What is pending?, define the build by categories?
