### ISSUE TITLE
[Bug] - Error installing maui workload - NU3004: Package signature validation failed

### ISSUE THREAD

**Issue by mattcarlucci** [dotnet/maui#2025]
### Description
Error installing maui workload
Followed .NET MAUI installation at : https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation
### Steps to Reproduce

Microsoft Windows [Version 10.0.17763.1935] 
1. Install Visual Studio 2022  Version 17 Preview 2.1
2. Install dotnet [Version 6.0.100-preview.6.21355.2

### NuGet Package references:
https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

### Execute command line
 C:/> dotnet workload install maui

### Output
```
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.tvos.
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Failed to validate package signing.

Verifying Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.100.6.0.0-rc.1.21410.2

**error: NU3004: The package is not signed.**

**Package signature validation failed.**

.
Installing pack Microsoft.Maui.Core.Ref.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Core.Ref.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Core.Runtime.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Core.Runtime.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Controls.Ref.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Controls.Ref.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Controls.Runtime.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Essentials.Ref.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Essentials.Ref.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Essentials.Runtime.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Essentials.Runtime.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Dependencies version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Dependencies version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Controls.Sdk version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Controls.Sdk version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Extensions version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Extensions version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Resizetizer.Sdk version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Resizetizer.Sdk version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Templates version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Templates version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Core.Ref.any version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Core.Ref.any version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Core.Runtime.any version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Core.Runtime.any version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Controls.Ref.any version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Controls.Ref.any version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Controls.Runtime.any version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Controls.Runtime.any version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Essentials.Ref.any version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Essentials.Ref.any version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Essentials.Runtime.any version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Essentials.Runtime.any version 6.0.100-rc.1.1310...
Installing pack Microsoft.Android.Sdk version 30.0.100-preview.7.110...
Writing workload pack installation record for Microsoft.Android.Sdk version 30.0.100-preview.7.110...
Installing pack Microsoft.Android.Sdk.BundleTool version 30.0.100-preview.7.110...
Writing workload pack installation record for Microsoft.Android.Sdk.BundleTool version 30.0.100-preview.7.110...
Installing pack Microsoft.Android.Ref version 30.0.100-preview.7.110...
Writing workload pack installation record for Microsoft.Android.Ref version 30.0.100-preview.7.110...
Installing pack Microsoft.Android.Runtime.android-arm version 30.0.100-preview.7.110...
Writing workload pack installation record for Microsoft.Android.Runtime.android-arm version 30.0.100-preview.7.110...
Installing pack Microsoft.Android.Runtime.android-arm64 version 30.0.100-preview.7.110...
Writing workload pack installation record for Microsoft.Android.Runtime.android-arm64 version 30.0.100-preview.7.110...
Installing pack Microsoft.Android.Runtime.android-x86 version 30.0.100-preview.7.110...
Writing workload pack installation record for Microsoft.Android.Runtime.android-x86 version 30.0.100-preview.7.110...
Installing pack Microsoft.Android.Runtime.android-x64 version 30.0.100-preview.7.110...
Writing workload pack installation record for Microsoft.Android.Runtime.android-x64 version 30.0.100-preview.7.110...
Installing pack Microsoft.Android.Templates version 30.0.100-preview.7.110...
Writing workload pack installation record for Microsoft.Android.Templates version 30.0.100-preview.7.110...
Installing pack Microsoft.NETCore.App.Runtime.Mono.android-arm version 6.0.0-preview.6.21352.12...
Workload installation failed, rolling back installed packs...
Uninstalling workload pack Microsoft.Maui.Core.Ref.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Core.Runtime.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Controls.Ref.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Essentials.Ref.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Essentials.Runtime.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Dependencies version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Controls.Sdk version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Extensions version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Resizetizer.Sdk version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Templates version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Core.Ref.any version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Core.Runtime.any version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Controls.Ref.any version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Controls.Runtime.any version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Essentials.Ref.any version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Essentials.Runtime.any version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Android.Sdk version 30.0.100-preview.7.110.
Uninstalling workload pack Microsoft.Android.Sdk.BundleTool version 30.0.100-preview.7.110.
Uninstalling workload pack Microsoft.Android.Ref version 30.0.100-preview.7.110.
Uninstalling workload pack Microsoft.Android.Runtime.android-arm version 30.0.100-preview.7.110.
Uninstalling workload pack Microsoft.Android.Runtime.android-arm64 version 30.0.100-preview.7.110.
Uninstalling workload pack Microsoft.Android.Runtime.android-x86 version 30.0.100-preview.7.110.
Uninstalling workload pack Microsoft.Android.Runtime.android-x64 version 30.0.100-preview.7.110.
Uninstalling workload pack Microsoft.Android.Templates version 30.0.100-preview.7.110.
Rolling back pack Microsoft.Maui.Core.Ref.android installation...
Rolling back pack Microsoft.Maui.Core.Runtime.android installation...
Rolling back pack Microsoft.Maui.Controls.Ref.android installation...
Rolling back pack Microsoft.Maui.Controls.Runtime.android installation...
Rolling back pack Microsoft.Maui.Essentials.Ref.android installation...
Rolling back pack Microsoft.Maui.Essentials.Runtime.android installation...
Rolling back pack Microsoft.AspNetCore.Components.WebView.Maui installation...
Rolling back pack Microsoft.Maui.Dependencies installation...
Rolling back pack Microsoft.Maui.Controls.Sdk installation...
Rolling back pack Microsoft.Maui.Extensions installation...
Rolling back pack Microsoft.Maui.Resizetizer.Sdk installation...
Rolling back pack Microsoft.Maui.Templates installation...
Rolling back pack Microsoft.Maui.Core.Ref.any installation...
Rolling back pack Microsoft.Maui.Core.Runtime.any installation...
Rolling back pack Microsoft.Maui.Controls.Ref.any installation...
Rolling back pack Microsoft.Maui.Controls.Runtime.any installation...
Rolling back pack Microsoft.Maui.Essentials.Ref.any installation...
Rolling back pack Microsoft.Maui.Essentials.Runtime.any installation...
Rolling back pack Microsoft.Android.Sdk installation...
Rolling back pack Microsoft.Android.Sdk.BundleTool installation...
Rolling back pack Microsoft.Android.Ref installation...
Rolling back pack Microsoft.Android.Runtime.android-arm installation...
Rolling back pack Microsoft.Android.Runtime.android-arm64 installation...
Rolling back pack Microsoft.Android.Runtime.android-x86 installation...
Rolling back pack Microsoft.Android.Runtime.android-x64 installation...
Rolling back pack Microsoft.Android.Templates installation...
Rolling back pack Microsoft.NETCore.App.Runtime.Mono.android-arm installation...
**Workload installation failed: Failed to validate package signing.**

Verifying Microsoft.NETCore.App.Runtime.Mono.android-arm.6.0.0-preview.6.21352.12

**error: NU3004: The package is not signed.**

**Package signature validation failed.**
```

### Basic Information
Microsoft Visual Studio Professional 2022 Preview
Version 17.0.0 Preview 2.1
VisualStudio.17.Preview/17.0.0-pre.2.1+31521.260
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

Visual C++ 2022   00476-70000-00000-AA764
Microsoft Visual C++ 2022

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ASP.NET and Web Tools 2019   17.0.303.37752
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.303.37752
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.303.37752
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.303.37752
Azure Functions and Web Jobs Tools

C# Tools   4.0.0-2.21362.3+5f7ddf6f02d40036fdbf823cd9910027da277acd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.0.4 (62dd685)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2135615+c94df2e3bebc72c937da0389b22d730b5ea7b19b
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62107.02200
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.0701.2001
TypeScript Tools for Microsoft Visual Studio

Xamarin   17.0.0.68 (main@8be0e08)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.19 (remotes/origin/38ad4805f43a9ae53ab6f12d9cd60d08750c49bd@38ad4805f)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.2 (6fd52a2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.99.54 (main/0e5e06f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@a5ed891
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@683f375

Xamarin.iOS and Xamarin.Mac SDK   14.99.0.2 (dd5f9f7b6)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by tstephansen** [comment]
I am having a similar issue but it seems to fail in different places each time I run it. Here are a few examples.

------------------------

Failed to update the advertising manifest microsoft.net.workload.emscripten: Object reference not set to an instance of an object..
Updated advertising manifest microsoft.net.sdk.android.
Failed to update the advertising manifest microsoft.net.sdk.ios: Object reference not set to an instance of an object..
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Failed to validate package signing.

Verifying Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.100.6.0.0-rc.1.21410.4

error: NU3004: The package is not signed.

Package signature validation failed.

.
Failed to update the advertising manifest microsoft.net.sdk.maui: Object reference not set to an instance of an object..
Updated advertising manifest microsoft.net.sdk.macos.
Failed to update the advertising manifest microsoft.net.sdk.tvos: Object reference not set to an instance of an object..
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Installing pack Microsoft.Maui.Core.Ref.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Core.Ref.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Core.Runtime.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Core.Runtime.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Controls.Ref.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Controls.Ref.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-rc.1.1310...
Workload installation failed, rolling back installed packs...
Uninstalling workload pack Microsoft.Maui.Core.Ref.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Core.Runtime.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Controls.Ref.android version 6.0.100-rc.1.1310.
Rolling back pack Microsoft.Maui.Core.Ref.android installation...
Rolling back pack Microsoft.Maui.Core.Runtime.android installation...
Rolling back pack Microsoft.Maui.Controls.Ref.android installation...
Rolling back pack Microsoft.Maui.Controls.Runtime.android installation...
Workload installation failed: Downloading microsoft.maui.controls.runtime.android version 6.0.100-rc.1.1310 failed

------------------------

Updated advertising manifest microsoft.net.sdk.android.
Failed to update the advertising manifest microsoft.net.workload.emscripten: Object reference not set to an instance of an object..
Failed to update the advertising manifest microsoft.net.sdk.ios: Object reference not set to an instance of an object..
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Failed to validate package signing.

Verifying Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.100.6.0.0-rc.1.21410.4

error: NU3004: The package is not signed.

Package signature validation failed.

.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.macos.
Failed to update the advertising manifest microsoft.net.sdk.tvos: Object reference not set to an instance of an object..
Installing pack Microsoft.Maui.Core.Ref.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Core.Ref.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Core.Runtime.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Core.Runtime.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Controls.Ref.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Controls.Ref.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-rc.1.1310...
Writing workload pack installation record for Microsoft.Maui.Controls.Runtime.android version 6.0.100-rc.1.1310...
Installing pack Microsoft.Maui.Essentials.Ref.android version 6.0.100-rc.1.1310...
Workload installation failed, rolling back installed packs...
Uninstalling workload pack Microsoft.Maui.Core.Ref.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Core.Runtime.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Controls.Ref.android version 6.0.100-rc.1.1310.
Uninstalling workload pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-rc.1.1310.
Rolling back pack Microsoft.Maui.Core.Ref.android installation...
Rolling back pack Microsoft.Maui.Core.Runtime.android installation...
Rolling back pack Microsoft.Maui.Controls.Ref.android installation...
Rolling back pack Microsoft.Maui.Controls.Runtime.android installation...
Rolling back pack Microsoft.Maui.Essentials.Ref.android installation...
Workload installation failed: Downloading microsoft.maui.essentials.ref.android version 6.0.100-rc.1.1310 failed

------------------------

**Comment by rgunawans** [comment]
try update maui-check
`dotnet tool update -g Redth.Net.Maui.Check`
and run 
`dotnet workload install maui`

**Comment by mattcarlucci** [comment]
> try update maui-check
> `dotnet tool update -g Redth.Net.Maui.Check`, run **maui-check**
> and run
> `dotnet workload install maui`

It can't find the package. Perhaps I'm missing a NuGet source

```
C:\Windows\system32>dotnet tool update -g Redth.Net.Maui.Check
C:\Users\Matt.Carlucci\AppData\Local\Temp\nfcuvsry.o53\restore.csproj : error NU1101: Unable to find package redth.net.maui.check. No packages exist with this id in source(s): C:\Program Files (x86)\dotnet\library-packs, dotnet6, maui, maui-preview, Microsoft Visual Studio Offline Packages
Tool 'redth.net.maui.check' failed to update due to the following:
The tool package could not be restored.
Tool 'redth.net.maui.check' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

**Comment by rgunawans** [comment]
> > try update maui-check
> > `dotnet tool update -g Redth.Net.Maui.Check`, run **maui-check**
> > and run
> > `dotnet workload install maui`
> 
> It can't find the package. Perhaps I'm missing a NuGet source
> 
> ```
> C:\Windows\system32>dotnet tool update -g Redth.Net.Maui.Check
> C:\Users\Matt.Carlucci\AppData\Local\Temp\nfcuvsry.o53\restore.csproj : error NU1101: Unable to find package redth.net.maui.check. No packages exist with this id in source(s): C:\Program Files (x86)\dotnet\library-packs, dotnet6, maui, maui-preview, Microsoft Visual Studio Offline Packages
> Tool 'redth.net.maui.check' failed to update due to the following:
> The tool package could not be restored.
> Tool 'redth.net.maui.check' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name was found, but it was not a .NET tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.
> 
> For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
> ```

seems you haven't install yet, you can install the maui-check tools by running **dotnet tool install -g Redth.Net.Maui.Check**

**Comment by tstephansen** [comment]
maui-check did not work for me yesterday. However, it is working today and I was able to get maui installed. It reports that I don't have preview 3 of VS2022 but that isn't released yet so I'm not sure why that's happening. Regardless, it is working at this point.

**Comment by rgunawans** [comment]
> maui-check did not work for me yesterday. However, it is working today and I was able to get maui installed. It reports that I don't have preview 3 of VS2022 but that isn't released yet so I'm not sure why that's happening. Regardless, it is working at this point.

you can try update to preview 3, I'm in progress updating to preview 3 right now

**Comment by tstephansen** [comment]
It must have just been released. I updated 2019 and 2019 preview earlier this morning and there wasn't an update for 2022. I'll go ahead and update. Thanks for letting me know!

**Comment by mattcarlucci** [comment]
> maui-check did not work for me yesterday. However, it is working today and I was able to get maui installed. It reports that I don't have preview 3 of VS2022 but that isn't released yet so I'm not sure why that's happening. Regardless, it is working at this point.

Coujd you tell me what NuGet sources are you point to? I've updated to Visual Studio preview 3  dotnet 6 preview 7 and I get the same signing error. 

These are the two I found during my search:

```
https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json
```

**Comment by mattcarlucci** [comment]
> > maui-check did not work for me yesterday. However, it is working today and I was able to get maui installed. It reports that I don't have preview 3 of VS2022 but that isn't released yet so I'm not sure why that's happening. Regardless, it is working at this point.
> 
> Could you tell me what NuGet sources are you point to? I've updated to Visual Studio preview 3 dotnet 6 preview 7 and I get the same signing error.
> 
> These are the two I found during my search:
> 
> ```
> https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json
> https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json
> ```

Turns out I was missing the following:
<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />

**Comment by jsuarezruiz** [comment]
Use this script https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1 to remove the current workloads (not sure about the status, could have a mix of old versions).

Then, install latest VS 2022 Preview. And finally, install workloads

`dotnet workload install maui`

or

`dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.10.json`

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
