### ISSUE TITLE
Android does not update visibility of a visual element if it has a Shadow

### ISSUE THREAD

**Issue by era-maui** [dotnet/maui#20264]
### Description

Hello,

We have encountered with MAUI .NET8 Android app that if a Control has a shadow and has its IsVisible property Binding set up with a viewmodel, there are problems updating its actual visibility. It seems that when the IsVisible mapping is triggered in the Handler, it is not run on the MainThread in case of an update coming from OnPropertyChanged. It seems to be a case only for views that have a container view.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

 We have temporary fixed this by overriding the IsVisible Mapping.
  ```
public class BordorHandler : BorderHandler
  {
	  private static void MapFixedVisibility(BordorHandler arg1, Border arg2)
	  {
		  arg2.Dispatcher.Dispatch(() => MapVisibility(arg1, arg2));
	  }
  
	  protected override void ConnectHandler(ContentViewGroup platformView)
	  {
		  base.ConnectHandler(platformView);
		  Mapper.ReplaceMapping<Border, BordorHandler>(nameof(VisualElement.IsVisible), MapFixedVisibility);
	  }
  } 
```
I have added a sample project with a temporary fix included, but outcommented in the MauiProgram.cs
[SampleApp.zip](https://github.com/dotnet/maui/files/14109651/SampleApp.zip)

**Comment by rehnz** [comment]
Wow, I had been trying to figure this out for a couple days now.  It was this, my buttons have shadows.

In your override solution I see you applying it to the border handler, in my case its just in simple grids, what do you mean by "container view".  

Thanks in advance.

**Comment by era-maui** [comment]
So I checked it again, and it does not seem to be necessarily a Main thread issue. Dispatcher seems to fix it, because it cues up the operation. Maybe its some race condition? Anyway, I made mine in BorderHandler, but you could also just override ViewHandler to apply this change for everything. By Container I meant what is in the base MapVisibility method in ViewHandler.
```
/// <summary>
/// Maps the abstract <see cref="IView.Visibility"/> property to the platform-specific implementations.
/// </summary>
/// <param name="handler">The associated handler.</param>
/// <param name="view">The associated <see cref="IView"/> instance.</param>
public static void MapVisibility(IViewHandler handler, IView view)
{
	if (handler.HasContainer)
		((PlatformView?)handler.ContainerView)?.UpdateVisibility(view);

	((PlatformView?)handler.PlatformView)?.UpdateVisibility(view);
}
```


I think I found a bit more on this. Seems this behavior happens due to me creating the ViewModel and  doing OnPropertyChanged in the same context. If I move ViewModel creation under Loaded event, it also fixes the issue

```
public MainPage()
{
	InitializeComponent();

	Loaded += LoadView;
}

private void LoadView(object? sender, EventArgs e)
{
	_viewModel = new MainPageViewModel();
	BindingContext = _viewModel;
}
```

Does it mean we should move our logic into Loaded Handler?

**Comment by rehnz** [comment]
Well I just tried a really simple example.  Button starts IsVisible = false, set IsVisible on button = true with other event (like switch toggle) and if the button has shadows it wont show, remove the shadows it will.  So its definitely not working, it's not a binding issue.

**Comment by jaosnz-rep** [comment]
Can repro this issue at Android platform on the latest 17.10 preview 2 (8.0.14 &8.0.7)
