### ISSUE TITLE
[Bug] Push symbols for MAUI packs

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#2026]
### Description

We need to push symbols (.snupkg) packs for our workload packs

- How should these be packaged/published?
- Sdk package has the pdb's inside the nupkg
- Ref/etc packs do not

**Comment by lindexi** [comment]
How about add EmbedAllSources?

**Comment by mattleibow** [comment]
Fixed in https://github.com/dotnet/maui/pull/2317
