### ISSUE TITLE
Previously selected Shellitem cannot be reselected

### ISSUE THREAD

**Issue by Legends** [dotnet/maui#20273]
### Description

**Issue**: https://github.com/dotnet/maui-samples/issues/425
**Repo**: https://github.com/dotnet/maui-samples/tree/main/8.0/Fundamentals/Shell

### Steps to Reproduce

1. Run the app.
2. Select a cat. (=> View changes to `CatDetailPage`).
3. Navigate back.
4. Try to select same cat again. => Nothing happens.

**Expected**: Seeing the cats'DetailPage again.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/8.0/Fundamentals/Shell

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11-API 30, Win 10

### Did you find any workaround?

no

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 1.0(8.0.6). Repro on Windows 11, Android 14.0-API34, iOS 17.2 and MacCatalyst with below Project:
[Xaminals.zip](https://github.com/dotnet/maui/files/14568902/Xaminals.zip)

**Comment by jsuarezruiz** [comment]
Related PR https://github.com/dotnet/maui/pull/21490

**Comment by PureWeen** [comment]
This is by design really
https://github.com/dotnet/maui/pull/21490#discussion_r1623301225

You have to unselect something in order for it to be reselect. 
We should update the samples to enable reselection though.
