### ISSUE TITLE
Pages not appearing in .NET MAUI app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#20271]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Pages-not-appearing-in-NET-MAUI-app/10561741)._

---
[severity:It's more difficult to complete my work]
I have a MAUI app. I am using Visual Studio 17.8.3. The app tracks Wines. Wines have Wineries, Regions and Varietals.  AppShell contains a TabBar with tabs for Wineries, Regions and Varietals. When you select Wineries, you see a page with list of wineries. When you select a winery from the list, you see a page with a list of wines for that winery. Same with Regions and Varietals. 

Everything works fine on Windows and also on my iPad. On my iPhone 12 Pro, not all the tabs show up. You have to tap More to see Regions and Varietals. When you tap Regions, you see the page with the list of Regions, but when you select a region from the list you do not see the page with the list of wines. Same with Varietals. Debugging shows all the code runs but the page does not appear. 

If I change the tab order to Regions, Wineries and Varietals then Regions works as expected but Wineries stops showing the page with the list of wines. 

---
#### Feedback Bot on 1/15/2024, 07:04 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Overdrive77** [comment]
This is the same bug I'm getting on Android when using the Shell's TabBar

**Comment by jfversluis** [comment]
Thanks for the report! I appreciate the explanation of what you are seeing in your app. However, without any relevant code or ideally a reproduction, it will be very hard (if not impossible) to diagnose what might be going on here.

Could I please ask you to post some relevant code in terms of how your app is built up? How are your pages set up how do you navigate? Do you use any legacy renderers, custom renderers? Anything that might be relevant.

The easiest way to usually do this is by creating a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md). This way you will be sure it has all the relevant moving parts and its very easy for us to go in there and see what might be going on.

Thanks!
