### ISSUE TITLE
WebView MAUI WinUI Memory Leak

### ISSUE THREAD

**Issue by davide-cavallini** [dotnet/maui#20283]
### Description

Each time a "Webview" tag is added in a Page or ContentView, the memory allocation is not freed by the garbage collector.

### Link to public reproduction project repository

https://github.com/davide-cavallini/webview-winUI-maui-leak

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

The current workaround is to declare the webview in the code behind as static then changing its source binding each time the page/view is navigated.
In that way the leak happens only the first time and the memory allocated still the same.

**Comment by AdamEssenmacher** [comment]
Consider checking out my memory toolkit designed to address these sorts of issues: https://github.com/AdamEssenmacher/MemoryToolkit.Maui

**Comment by bronteq** [comment]
Hi, I opened a duplicate issue that was closed, so I report here some information:
-the bug affects Maui 8.0.3, 8.0.6, 8.0.7, 8.0.10 (previous versions not tested)
-the same problem seems to be present in Maui Android, as described in this issue: https://github.com/dotnet/maui/issues/18021
-other reproduction project: https://github.com/bronteq/maui_webview_issue

After _n_ page changes, Task Manager reports _n_ WebView2 tabs related to the app, but Visual Studio memory report does not indicates the massive memory increase
![image](https://github.com/dotnet/maui/assets/159045969/c95e5fc0-79d3-43bb-867b-b35d61dbec89)

**Comment by jingliancui** [comment]
Multiple windows each contains the webview also have this issue after window get closed, I will raise another new issue.

**Comment by jonathanpeppers** [comment]
@davide-cavallini for now, can you do something like this in your `Page`:
```csharp
    protected override void OnDisappearing()
    {
        base.OnDisappearing();

        webView.Handler?.DisconnectHandler();
    }
```
(I put `x:Name="webView"` in the XAML)

This seems to solve the issue in your sample:

![image](https://github.com/dotnet/maui/assets/840039/94e28a6a-d332-4688-8ad8-8651d6eaf7ea)
