### ISSUE TITLE
Running an iOS app using the command 'sudo dotnet build -t:Run -f net8.0-ios' gets stuck

### ISSUE THREAD

**Issue by javrro** [dotnet/maui#20280]
### Description

I have not been able to run and test a newly created iOS app on the iOS simulator.
it gets stuck at some point.
I've had no issues running on iOS before. Running the app on an android emulator works fine, the app builds and runs in seconds.
I've already tried uninstalling the maui workload and re-installing and still gets stuck.
iOS sim is an iPhone 15 Pro Max - iOS 17.2

### Steps to Reproduce

1. create a new maui app
2. run 'sudo dotnet build -t:Run -f net8.0-ios'

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.0-rc.2.9511

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Relevant log output
this is what I get in the terminal:

MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  Restored /Users/javierrodriguez/Documents/projects/dotnet-vscode-maui-test/MyMauiApp3/MyMauiApp3.csproj (in 1.81 sec).
  Detected signing identity:
          
    Bundle Id: com.companyname.mymauiapp3
    App Id: com.companyname.mymauiapp3
  MyMauiApp3 -> /Users/javierrodriguez/Documents/projects/dotnet-vscode-maui-test/MyMauiApp3/bin/Debug/net8.0-ios/iossimulator-arm64/MyMauiApp3.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Optimizing assemblies for size. This process might take a while.
  xcrun simctl launch --stdout=/dev/ttys008 --stderr=/dev/ttys010 --terminate-running-process E36B9212-BABF-46B7-BE60-4E3C693D9720 com.companyname.mymauiapp3
  com.companyname.mymauiapp3: 48959
objc[48959]: Class CDPRecoveryKeyStatusProvider is implemented in both /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal (0x16c8c5990) and /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDP.framework/CoreCDP (0x15fb789c8). One of the two will be used. Which one is undefined.
objc[48959]: Class CDPKeychainItemDescriptor is implemented in both /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal (0x16c8c4a90) and /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDP.framework/CoreCDP (0x15fb78b58). One of the two will be used. Which one is undefined.
objc[48959]: Class CDPCAReporter is implemented in both /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal (0x16c8c50d0) and /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDP.framework/CoreCDP (0x15fb78ec8). One of the two will be used. Which one is undefined.
objc[48959]: Class CDPRecoveryKeyCache is implemented in both /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal (0x16c8c4e50) and /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDP.framework/CoreCDP (0x15fb78f68). One of the two will be used. Which one is undefined.
objc[48959]: Class MicaPlayer is implemented in both /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppleMediaServicesUI.framework/AppleMediaServicesUI (0x16fe32af8) and /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI (0x15490d9a8). One of the two will be used. Which one is undefined.
objc[48959]: Class AKAlertImageURLProvider is implemented in both /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AuthKitUI.framework/AuthKitUI (0x1597ce010) and /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AuthKit.framework/AuthKit (0x131c01d10). One of the two will be used. Which one is undefined.
2024-01-31 18:10:33.301897-0500 MyMauiApp3[48959:1005228] Microsoft.iOS: Socket error while connecting to IDE on 127.0.0.1:10000: Connection refused
2024-01-31 18:10:44.313494-0500 MyMauiApp3[48959:1005212] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2024-01-31 18:10:53.415124-0500 MyMauiApp3[48959:1005212] [TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <_UIMoreListTableView: 0x28019ec00; frame = (0 0; 0 0); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600000839da0>; backgroundColor = <UIDynamicSystemColor: 0x60000126c1c0; name = tableBackgroundColor>; layer = <CALayer: 0x600000231540>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <UIMoreListController: 0x171994540>>
2024-01-31 18:11:14.828459-0500 MyMauiApp3[48959:1005212] [AXIPC] Exhausted registration attempts for com.apple.accessibility.AXSystemReplyServer-48959-0: Error Domain=IPC Code=0 "Could not send simple message (com.apple.accessibility.AXBackBoardServer). Port:32267. Error:268435460 (0x10000004). 
<AXIPCMessage: 0x600002464730>. Client port: 0. Key: 1952057825. Payload: {
    identifier = "com.apple.accessibility.AXSystemReplyServer-48959-0";
} (33)" UserInfo={NSLocalizedFailureReason=Could not send simple message (com.apple.accessibility.AXBackBoardServer). Port:32267. Error:268435460 (0x10000004). 
<AXIPCMessage: 0x600002464730>. Client port: 0. Key: 1952057825. Payload: {
    identifier = "com.apple.accessibility.AXSystemReplyServer-48959-0";
} (33), AXIPCErrorKeyMachError=268435460}

_No response_

**Comment by drasticactions** [comment]
What version of Xcode do you have on your Mac? My guess would be you probably updated .NET and its iOS/Mac workloads and didn't upgrade Xcode.

**Comment by javrro** [comment]
> What version of Xcode do you have on your Mac? My guess would be you probably updated .NET and its iOS/Mac workloads and didn't upgrade Xcode. Also, if you could run
> 
> `dotnet --info`
> 
> That would be useful.

Im using Xcode version 15.2 which is the latest version.

dotnet --info 

.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.ba313bcd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.2
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.ba313bcd
 [maui]
   Installation Source: SDK 8.0.100
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.3/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.1
  Architecture: arm64
  Commit:       bf5e279d92

**Comment by javrro** [comment]
I figured the issue is not the build process, but running the built app in the iOS Simulator.

**Comment by javrro** [comment]
if I try to run to give it a specific decive ID I get this error

EXEC : error MT1216: Could not find the simulator UDID 'E80E7B9A-4357-43D7-894B-8B5F1712C87B'. [/Users/javierrodriguez/Documents/projects/dotnet-vscode-maui-test/MauiApp2/MauiApp2.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/sdk/8.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1056,5): error MSB3073: The command "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/tools/bin/mlaunch --launchsim bin/Debug/net8.0-ios/iossimulator-arm64/MauiApp2.app/ --device :v2:udid=E80E7B9A-4357-43D7-894B-8B5F1712C87B --stdout /dev/ttys005 --stderr /dev/ttys005 --wait-for-exit:true" exited with code 1. [/Users/javierrodriguez/Documents/projects/dotnet-vscode-maui-test/MauiApp2/MauiApp2.csproj::TargetFramework=net8.0-ios]


any solutions for this?

**Comment by javrro** [comment]
anyways im quitting MAUI for now. back to Flutter I guess. I thought .Net 8 was going to make things better, but it seems it only made everthing worse. apps wont even start now. the developer experience is sooo terrible I cant justify working with MAUI.

I'll be back for .Net 9

**Comment by javrro** [comment]
Tried building and running the app from VS for Mac and it worked. I had to enable .Net 8 for VS Mac preview feature, but it worked the first time.
So, the seems to be something wrong with the CLI

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio for mac 17.6.10(build428). Can not repro this issue.(Maui Version:8.0.14&8.0.3 / Xcode:15.2 / iOS version:17.2)

**Comment by javrro** [comment]
After doing a bit more testing I can confirm the issue doesnt happen if I create the MAUI project from VS Code using the MAUI extension.

it is working properly for me now.
