### ISSUE TITLE
[testing] Enable FlyoutHeaderWithZeroMarginShouldHaveNoY

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#20296]
### Description

the Test FlyoutHeaderWithZeroMarginShouldHaveNoY is failing sometimes on iOS 16.4 and always on iOS 17.0 we need to investigate and enable it back 

The test was [disable here ](https://github.com/dotnet/maui/pull/19941/files#diff-20ef948156ef4648510b33f21ae26ab6b993fdd0c27c30a97d2b505dbf6b5285) for adding iOS17 support

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jsuarezruiz** [comment]
Is already enabled again https://github.com/dotnet/maui/blob/main/src/Compatibility/ControlGallery/src/Issues.Shared/HeaderFooterShellFlyout.cs#L187
