### ISSUE TITLE
[Bug] Navigation transitions with Maui Blazor

### ISSUE THREAD

**Issue by 3DSX** [dotnet/maui#2030]
### Description
How could navigation transitions be done in Maui Blazor? Top to bottom, enter a child from parent, etc.

**Comment by Eilon** [comment]
Hi @3DSX , if you're referring to navigation within the BlazorWebView, it should be the same as in any Blazor app.

Here's an overview of Blazor navigation:
* https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0

And the `NavigationManager` can be retrieved via dependency injection to perform various navigation operations:
* https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.navigationmanager?view=aspnetcore-5.0

If your question is referring to something else, please share more details.

**Comment by 3DSX** [comment]
Hi, @Eilon sorry if I didn't explain enough. I'm not referring to the route navigation controls. 

I'm referring to [this](https://material.io/design/navigation/navigation-transitions.html#peer-transitions).

**Comment by Eilon** [comment]
Hi @3DSX ah OK, then I think whatever works with Blazor in general should work here.

I found some projects that seem to integrate Material Design with Blazor: (I am not endorsing them, it's just the first ones I found)
* https://www.matblazor.com/
* https://material-blazor.com/docs/index.html
