### ISSUE TITLE
.NET MAUI SQL Server doesn't work in release mode

### ISSUE THREAD

**Issue by hammadkhandev888** [dotnet/maui#20307]
### Description

I am using .NET MAUI. I connect to SQL Server using an IP address. I have a specific scenario that requires me to connect to SQL Server within my .NET MAUI application. It works fine in debug mode, and I can connect to SQL Server. However, I am unable to connect to it in release mode.

**Error**

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)

**Connection String**

Server=Server,1434;Database=DB;User ID=penn;Password=asdaf;Encrypt=false;TrustServerCertificate=true;

Could you please help me?

I tried to change the connection string and also searched in the MAUI github repo but no luck.

### Steps to Reproduce

Create .NET MAUi App
Add Microsoft.Data.SqlClient
Add SqlConnection and enter your connection string using IP port,
Run the app on android in release mode

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

**Comment by Redth** [comment]
It looks like maybe you expect a self signed certificate on the server?   Android has some different considerations for secure connections: https://developer.android.com/privacy-and-security/security-ssl

This isn't a MAUI issue, but either you need to use a certificate on the server signed by a trusted authority which android recognizes, or open an issue with the SqlClient library: https://github.com/dotnet/SqlClient to see why their underlying implementation is not respecting the connection string setting to accept the self signed certificate.

Finally, I would generally strongly suggest against connecting from a client app directly to a SQL server instance.  Having your connection string in the client app is not a good security practice.  Instead you should be using an intermediate API server and using an authentication pattern against that API server (eg: using short lived auth tokens and refresh tokens).

**Comment by hammadkhandev888** [comment]
I fixed the issue by upgrading to prelease version and adding INTERNET permission
