### ISSUE TITLE
MSB4062 error when publishing an Android APP on Azure Online Pipeline

### ISSUE THREAD

**Issue by jonathanantoine** [dotnet/maui#20300]
### Description

On an Azure Dev Ops agent, I am trying to publish an android application using this command :
```bash
dotnet publish -c Release -f net8.0-android
```
It fails with this error :
```
##[error]C:\Users\VssAdministrator\.nuget\packages\xamarin.android.support.vector.drawable\28.0.0.3\build\monoandroid90\Xamarin.Android.Support.Vector.Drawable.targets(25,3): 
Error MSB4062: The "Xamarin.Android.Support.Tasks.VectorDrawableCheckBuildToolsVersionTask" task could not be loaded from the assembly C:\Users\VssAdministrator\.nuget\packages\xamarin.android.support.vector.drawable\28.0.0.3\build\monoandroid90\Xamarin.Android.Support.Tasks.VectorDrawable.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 
The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

dotnet build run fine without issue.

### Steps to Reproduce

1. Create an Android Maui project
2. Refrence (directly or indirectly) this package : ` Xamarin.Android.Support.Vector.Drawable`
3. Try to publish the app.

Used pipeline definition :
```yml

trigger:
- maui

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: JavaToolInstaller@0
  displayName: 'Install Java'
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration) -f net8.0-android'
```

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by jonathanantoine** [comment]
In fact the bug happens even with VS on the agent .

**Comment by jfversluis** [comment]
The referenced package is one that is archived and not supported. It targets Xamarin. You probably want to update it, I think this is the one that should work for .NET MAUI: https://www.nuget.org/packages/Xamarin.AndroidX.VectorDrawable

In either case, this is because of a not supported dependency not something we can fix unfortunately so closing this here.
