### ISSUE TITLE
Itext or pdfsharp problem being investigated by Jon.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#20316]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Itext-or-pdfsharp-problem-being-investig/10535481)._

---
Hello Jon.

Not executing any itext or pdfsharp code.  This is directly related to either . Maui or C#

[DirectoryCreate.png](https://aka.ms/dc/file?name=Baace63a8a0ce47c5873ffb1c34c6fc70638374954478536862_DirectoryCreate.png&tid=aace63a8a0ce47c5873ffb1c34c6fc70638374954478536862)

---
#### Feedback Bot on 12/6/2023, 05:54 PM: 

(private comment, text removed)
#### Natale J Montalto on 12/7/2023, 06:11 AM: 

(private comment, text removed)
#### Jon Dick [MSFT] on 12/7/2023, 07:09 AM: 

(private comment, text removed)
#### Natale J Montalto on 12/7/2023, 08:53 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
As indicated in the feedback issue, I don't think this is something that originates in .NET MAUI. Seems like a path permissions issue. Hope it's resolved by now!
