### ISSUE TITLE
[iOS] Grouped CollectionView with a Footer stutters under MAUI 8.0.6

### ISSUE THREAD

**Issue by MichaelShapiro** [dotnet/maui#20320]
### Description

After updating to MAUI 8.0.6, CollectionView with Footer and IsGrouped="True" stutters and lags when scrolling. Stuttering is so significant that renders the use of such CollectionView impractical.

This can be related to #20294 

This is MAUI 8.0.6 - performance is degraded

https://github.com/dotnet/maui/assets/36049508/130cfcc0-e68a-4827-927a-b1e6bf593a51

This is MAUI 8.0.3 - performance is normal

https://github.com/dotnet/maui/assets/36049508/d0bb22c8-2d4b-4341-8eba-cb8d8ab3fb1e   

### Steps to Reproduce

Open repo in the link below. Start CollectionViewFooter project.

### Link to public reproduction project repository

https://github.com/MichaelShapiro/MauiBugs

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

iOS

### Did you find any workaround?

Two options:

1. Downgrade back to MAUI 8.0.3
2. Remove Footer from the CollectionView

**Comment by bcaceiro** [comment]
I faced this with any collectionview - the performance was awful in newest release. Had to downgrade to go back to relatively better results

**Comment by kevinxufei** [comment]
Verified on 17.10.0 Preview 1.0 with iOS platform (MAUI:8.0.7). It is still repro.

**Comment by rmarinho** [comment]
Fixed by #21140

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by MichaelShapiro** [comment]
@PureWeen  tested with 8.0.20-nightly.10336 - doesn't repro anymore. Thank you!
