### ISSUE TITLE
Blazor hybrid app and "error CS5001: Program does not contain a static 'Main' method suitable for an entry point"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#20329]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-hybrid-app-and-error-CS5001:-Pro/10532231)._

---
I'm struggling tailoring a Blazor hybrid project (created with the project template, latest VS2022 version). I want to build for Windows and Android only. If I try to uncheck iOS, maccatalyst is still in the supported TargetFrameworks. So I've changed that:

```
<TargetFrameworks>net8.0;net8.0-android</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
```
I've also added
```
<IsTestProject>false</IsTestProject>
```
to prevent Microsoft's test discovery from crashing and reporting all sorts of errors.

In the Platform directories only Windows and Android code is kept, Mac/Tizen stuff removed. If I build the project in VS2022, the error appears:
```
error CS5001: Program does not contain a static 'Main' method suitable for an entry point
```
Apparently the build is done for three frameworks: net8.0 and net8.0-android and net8.0-windows10.0.19041.0. The latter two succeed, but the net8.0 one fails. But there never is an application built with net8.0 as target platform.

I tried to prevent net8.0 from being used as TargetFramework by removing it from TargetFrameworks. That works (it is no longer used to build the project) but now I get messages like:
```
The project '<my Blazor hybrid project>' ran into a problem during the last operation: The value of the 'TargetFrameworks' property is inconsistent between target frameworks. This property must be identical for NuGet restore to function correctly. The value 'net8.0-android;net8.0-windows10.0.19041.0' from the 'Debug|AnyCPU|net8.0' configuration will be used, other target frameworks may fail to pick NuGet assets. You may need to reload the solution after fixing the problem. 
```
What should I do? I would like to have a build that does not result in nonsensical errors.

This would also be mush easier if it is possible within the IDE to select which target framework to use in the build, as you're typically not developing/testing/debugging all platforms at once but one at a time. How to do that?

---
#### Feedback Bot on 12/3/2023, 06:27 PM: 

(private comment, text removed)
#### Frank Robijn on 12/4/2023, 02:25 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drasticactions** [comment]
The MAUI/MAUI Blazor single project is an App project, so it needs a platform head to launch with. You can't add `net8.0` to that project as it has nothing to launch with (nor is there a reason to do so, since that baseline functionality is already covered by the other target frameworks.

So the fix for this is "Remove net8.0" and it should launch.

As for the Nuget restore, my guess would be because it's still using whatever bin/obj files were from the other, failed, build. Removing the TFM doesn't clear that cache. Removing bin/obj, restoring, and rebuilding, should clear that error.

**Comment by Eilon** [comment]
Indeed, .NET MAUI _apps_ can't have a `net8.0` target framework because that's not used by any target framework that .NET MAUI runs on.
