### ISSUE TITLE
MAUI .NET 8.0 AOT Compilation Always Fails with a Suggestion to set PublishTrimmed = false

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#20322]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-NET-80-AOT-Compilation-Always-Fai/10536540)._

---
[regression] [worked-in:17.7.6]
I am not able to build any MAUI application in AOT mode. No matter how complex or large it is. I thought that it is related to obfucator generated DLLs, that the DLLs are too large, but it is not true. If I refer clean DLL libraries, build fails with the same error.

See the sample solution here: https://github.com/KLO128/KLO128.Nonsense
Debug configuration passes.
Please try to build it in the Release configuration.

You will get an error: **Error NETSDK1144 Build size optimization failed. Optimization can be disabled by setting the PublishTrimmed property to false.**

But it is required to use the trim optimization for AOT and JIT apk is not installable into Android devices.

Please repair also the toolbar title update when flyout navigation detail page changes - it also used to work in .NET6.0. (This had already been reported.)
Thank you!

---
#### Feedback Bot on 12/7/2023, 05:45 PM: 

(private comment, text removed)
#### Jonathan Pryor [MSFT] on 12/12/2023, 00:58 PM: 

(private comment, text removed)
#### Petr Kloza on 12/12/2023, 01:48 PM: 

(private comment, text removed)
#### Jonathan Pryor [MSFT] on 12/12/2023, 05:42 PM: 

(private comment, text removed)
#### Petr Kloza on 12/14/2023, 00:00 AM: 

(private comment, text removed)
#### Feedback Bot on 12/14/2023, 08:29 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jonpryor** [comment]
There was a lot of back-and-forth in the [Developer Community ticket](https://developercommunity.visualstudio.com/t/MAUI-NET-80-AOT-Compilation-Always-Fai/10536540). [This comment](https://developercommunity.visualstudio.com/t/MAUI-NET-80-AOT-Compilation-Always-Fai/10536540#T-N10541209) has the remaining unanswered questions:

> But I have faced 3 issues, that did not appear in .NET6.0. I have made a workaround for first 2 of them… The third one is also reported.
>
> 1. Translations.resx from shared not obfuscated library are not reachable at runtime, FileNotFoundException. - I have made a work around with translations.tt which generates translations.json as an embedded resource.
> 
> 2. I can stop navigation back button with some confirm dialog “Save changes?”, but forcing to PopAsync the page on the main thread freezes the app and fails, even I have 2 items in the NavigationStack. - Workaround: I am persisting the state for the next time hitting the button “New Item” if it is not saved and I am not fighting with back button any more.
> 
> 3. But this I am not able to fix with a workaround: When NavigationPage.CurrentPage changes via TabbedPage or navigation.PushAsync, the title of navigation bar changes - that’s great. However, when I assign a new instance of NavigationPage to FlyoutPage.Detail to get rid of old NavigationStack (when I want change context of pages), the content changes, but the title of the NavigationBar remains the same, also the toolbar items remains the same. I hope, that you are still working on the fix for the next stable release of .NET8.0 and Visual Studio 2022. The same issue was described here: https://github.com/dotnet/maui/issues/18830

**Comment by BenjaminLutz80** [comment]
I have the same issue but only with IOS builds:

Starting: Build the Mobile App
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.235.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
/Users/runner/hostedtoolcache/dotnet/dotnet publish /Users/runner/work/1/s/Survalyzer.PanelPortal/Survalyzer.Panel.Portal/Survalyzer.Panel.Portal.csproj -f net8.0-ios -c Release /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false
MSBuild version 17.9.4+90725d08d for .NET
  Determining projects to restore...
  Restored /Users/runner/work/1/s/Survalyzer.PanelPortal/Survalyzer.Panel.Portal/Survalyzer.Panel.Portal.csproj (in 13.18 sec).
  Detected signing identity:
          
    Code Signing Key: ...
    Provisioning Profile: ...
    Bundle Id: com.survalyzer.panel.portal
    App Id: ...
  Survalyzer.Panel.Portal -> /Users/runner/work/1/s/Survalyzer.PanelPortal/Survalyzer.Panel.Portal/bin/Release/net8.0-ios/ios-arm64/Survalyzer.Panel.Portal.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Optimizing assemblies for size. This process might take a while.
  Failed to create CoreCLR, HRESULT: 0x80070057
/Users/runner/work/1/s/Survalyzer.PanelPortal/c:/p/microsoft.net.illink.tasks/8.0.2/build/Microsoft.NET.ILLink.targets(134,5): error MSB6006: "dotnet" exited with code 137. [/Users/runner/work/1/s/Survalyzer.PanelPortal/Survalyzer.Panel.Portal/Survalyzer.Panel.Portal.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/Survalyzer.PanelPortal/c:/p/microsoft.net.illink.tasks/8.0.2/build/Microsoft.NET.ILLink.targets(87,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/runner/work/1/s/Survalyzer.PanelPortal/Survalyzer.Panel.Portal/Survalyzer.Panel.Portal.csproj::TargetFramework=net8.0-ios]
##[error]Error: The process '/Users/runner/hostedtoolcache/dotnet/dotnet' failed with exit code 1
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : [
  '/Users/runner/work/1/s/Survalyzer.PanelPortal/Survalyzer.Panel.Portal/Survalyzer.Panel.Portal.csproj'
]
Finishing: Build the Mobile App

**Comment by jfversluis** [comment]
@jonpryor it's been a while, but is there still something we need to do on our side for this? Else can we close it?

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10 Preview 6 (8.0.21). Cannot repro it. 
![image](https://github.com/dotnet/maui/assets/128687574/1caaaa25-8a1c-431b-b04b-08526daf8982)
