### ISSUE TITLE
 VS cannot find generated proto code, when I try to build for windows

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#20328]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/-VS-cannot-find-generated-proto-code-wh/10212608)._

---
Hello. I use MAUI along with GRPC. There are no errors during compilation. However, when I try to build for windows, I get errors related to the generated proto code. VS cannot find the required libraries. Please advise how to solve this problem.

---
#### Tracy Wang [MSFT] on 11/24/2022, 06:56 PM: 

(private comment, text removed)
#### Никита Михайлович Погодаев on 11/25/2022, 05:04 AM: 

(private comment, text removed)
#### Feedback Bot on 11/28/2022, 06:16 PM: 

(private comment, text removed)
#### Feedback Bot on 3/2/2023, 00:21 AM: 

(private comment, text removed)
#### John O'Connor on 10/28/2023, 05:43 AM: 

(private comment, text removed)
#### Greene, Adam on 12/21/2023, 10:39 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
The screenshots in the original ticket don't seem to work. I would think that this is maybe more of a Win UI issue than .NET MAUI. A reproduction has already been requested, additionally, please try with a Win UI app without .NET MAUI involved and let us know if it works there.
