### ISSUE TITLE
Frame and RadioButton conflict

### ISSUE THREAD

**Issue by eyeveye** [dotnet/maui#20339]
### Description

in .NET 8 Maui, Radiobutton placed in Frame will not be display, in fact causing other controls not display too.
```
  <Frame>
      <RadioButton Content="test"/>
  </Frame>
```

### Steps to Reproduce

  <Frame>
      <RadioButton Content="test"/>
  </Frame>

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

Android

### Did you find any workaround?

Remove the Frame

**Comment by jsuarezruiz** [comment]
As a workaround, could you use a `Border `instead `Frame`?

**Comment by eyeveye** [comment]
Yes, I am using border as the workaround.
    On Monday, February 5, 2024 at 11:53:33 PM GMT+8, Javier Suárez ***@***.***> wrote:  
 
 


As a workaround, could you use a Border instead Frame?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avg.com |

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 2.0(8.0.7). Repro on **Android 13.0-API33**, not repro on **Android 14.0-API34**, Windows 11, iOS 17.2 and MacCatalyst with below Project:
[FrameIssue.zip](https://github.com/dotnet/maui/files/14584520/FrameIssue.zip)

**Comment by dustin-wojciechowski** [comment]
Looks like this was fixed recently:

Tested against the latest in main by itself:
![Screenshot_1715982252](https://github.com/dotnet/maui/assets/89540402/7ed6c663-3236-42c3-b815-12207a243b9c)

Test with another control in the frame:
![Screenshot_1715983501](https://github.com/dotnet/maui/assets/89540402/2f697c0e-70a2-41a9-9199-f512a22e2810)
