### ISSUE TITLE
Color applied correctly only when deployed

### ISSUE THREAD

**Issue by Legends** [dotnet/maui#20343]
### Description

When I live debug (F5) the following code on my local Android device, the `TextColor` is white instead of black:

```
  <Shell.TitleView>
      <HorizontalStackLayout HorizontalOptions="CenterAndExpand"
                             VerticalOptions="CenterAndExpand">
          <Label Text="I am inside Shell.TitleView in AppShell.xaml"
                 TextColor="Black" // <== black !
                 HorizontalOptions="Center"
                 VerticalOptions="Center"
                 Padding="0,10,10,0" />
```

F5 on Windows,` TextColor` is as expected black.

Deploying the app to my local android device, the `TextColor ` is, as specified, black.

IDE problem?
Where should I open this issue, perhaps you can move it to an appropriate repo.

### Steps to Reproduce

1. Add the above code to AppShell.xaml
2. Choose your local Android device as target
3. Press F5.

**Result:**
TitleView FOregroudn color is white

**Expected:**
To be black as specified.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/8.0/Fundamentals/Shell

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 API 30

### Did you find any workaround?

no

**Comment by jsuarezruiz** [comment]
Happens using Hot Reload?

**Comment by Legends** [comment]
> Happens using Hot Reload?

Actually it didn't work neither way on Android platform.
I tried it right now and it works. Even hot reload works in this case now.

Ooo buddy, maui is very strange currently.
Hope this will be much more stable with .net 9.0.

I will close it, but I guess you know, the currrent status is still volatile.
