### ISSUE TITLE
[Bug] Image position in grid cannot be customised.

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#2039]
### Description

With the **Fill** Aspect, we've added an image to the grid and specified a custom position with the Arrange/Layout function. However, the image's custom position is not set.

**In Maui preview 5, this issue not reproduced.** 

### Steps to Reproduce

1. Run the sample.
2. See the image occupies entire 1st row. 
3. But we have set bounds as new Microsoft.Maui.Graphics.Rectangle(20, 20, 30, 30).

### Expected Behavior

Image have to align with given bounds. 

### Actual Behavior

Image occupies full region of parent space in below Aspect types. 

1. Fill
2. AspectFill
3. AspectFit

In Center Aspect type, I can arrange image in center position with HeightRequest and WidthRequest API. But unable to customize the position with this center aspect. 

### Basic Information

Visual Studio : Visual Studio 2022 Preview
Maui : Maui Preview 6

### Code

```
<Grid>
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <Grid>
            <Grid Background="Yellow" x:Name="grid"/>
        </Grid>
        <StackLayout Grid.Row="1" Orientation="Vertical">
            <Button Text="Click" x:Name="button1" Background="Orange" WidthRequest="20"/>
        </StackLayout>
    </Grid>
```

```
public MainPage()
		{
			InitializeComponent();

			image.Aspect = Microsoft.Maui.Aspect.AspectFill;
            //image.VerticalOptions = LayoutOptions.Center;
            //image.HorizontalOptions = LayoutOptions.Center;
            //image.HeightRequest = 30;
            //image.WidthRequest = 30;

            image.Source = "person1.png";
			grid.Children.Add(image);

			image.Arrange(new Microsoft.Maui.Graphics.Rectangle(20, 20, 30, 30));

            button1.Clicked += Button1_Clicked;

		}

        private void Button1_Clicked(object sender, EventArgs e)
        {
			image.Arrange(new Microsoft.Maui.Graphics.Rectangle(20, 30, 30, 30));
		}
```

### Sample

[Test1.zip](https://github.com/dotnet/maui/files/6967585/Test1.zip)

**Comment by hartez** [comment]
> In Maui preview 5, this issue not reproduced.

Are you saying that you no longer see this issue? Or that the issue started appearing in preview 6?

> image.Arrange(new Microsoft.Maui.Graphics.Rectangle(20, 20, 30, 30));

This is not what the Arrange method is for - Arrange is part of the layout system, and is not intended to be called directly like this. If you're trying to position an image in a specific Rectangle, I suggest you use the AbsoluteLayout and set AbsoluteLayout.LayoutBounds.
