### ISSUE TITLE
[Bug] XmlnsDefinitionAttribute doesn´t work with[XamlCompilation(XamlCompilationOptions.Compile)]

### ISSUE THREAD

**Issue by ahmedalejo** [dotnet/maui#204]
### Description
using the `XmlnsDefinitionAttribute`  fails to compile when `XamlCompilationOptions.Compile` enabled.
### Steps to Reproduce

1. Reference an external library
```csharp
[assembly: XmlnsDefinition(
    xmlNamespace: "http://my.externallibrary.com",
    clrNamespace: "my.externallibrary.components",
    AssemblyName = "my.externallibrary.library")]
```
2. 
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="Openalmz.DonorApp.Features.Donations.NewDonationView"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:components="http://my.externallibrary.com">
    <components:View/>
</ContentPage>
```
### Expected Behavior
- It should compile without errors

### Actual Behavior
- Fails to compile

### Basic Information
- Version with issue: genesis
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9.0

### Workaround
Unfortunately none at the moment

**Comment by PureWeen** [comment]
Can you move this issue over to https://github.com/xamarin/Xamarin.Forms

**Comment by dansiegel** [comment]
If I'm not mistaken there is already an open issue on XmlnsDefinitionAttributes not being properly respected. Before opening a new issue I'd suggest taking a look at that one and providing any details you can to help further the issue.

https://github.com/xamarin/Xamarin.Forms/issues/8451

**Comment by ahmedalejo** [comment]
@dansiegel yep the title should have included `XmlnsDefinitionAttribute`. It would have looked more related.
