### ISSUE TITLE
A possible use case for contentRootRelativePath being overridable

### ISSUE THREAD

**Issue by grleachman** [dotnet/maui#20405]
https://github.com/dotnet/maui/blob/96288c1cff1c6399f42e3e24ea6f5b54557a19c0/src/BlazorWebView/src/WindowsForms/BlazorWebView.cs#L170C1-L171C79

Hello I am trying create a blazorUserControl within a Winforms App, that gets hosted within an Excel Task Pane.

This does not work because the control is trying to create a folder in c:\program files\Microsoft Office\.blah.blah\EBWebView
![image](https://github.com/dotnet/maui/assets/645821/dae4f482-39bf-49f4-b54d-878bf2e79999)

I think the cause of this problem is because the scenario has never been addressed. 

I am constrained to .NetCore6 at the moment, and cannot upgrade.
My setup for this is: Follow the steps : 
https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-8.0
From which I remove the form control.

I then build a regular UserControl in a different project which is then added to a TaskPane for excel.
I follow the same steps for adding the BlazorWebView into the UserControl as was done for the Form in the example project.

When the project runs, excel starts, and the control tries to load, but stops with the error above which implies it's trying to create a data folder in the c:\program files\blah  , which it correctly shouldn't be allowed to do

**Comment by Eilon** [comment]
Hi, I think to set that `EBWebView` folder to a custom location you can register a handler for the `BlazorWebView` control's `BlazorWebViewInitializing` event and set `args.UserDataFolder` to a custom location (say, in `...LocalAppData...` or something similar).

**Comment by grleachman** [comment]
spot on thanks very much.
