### ISSUE TITLE
[BUG] Content of a ContentPage doesn't occupy full height when page is pushed to PrismNavigationPage 

### ISSUE THREAD

**Issue by anpin** [dotnet/maui#20418]
### Description
Content of a PrismNavigationPage has inconsistent layout on MAUI iOS and MacCatalyst. Not sure if this issue belongs here or  in the Prism repo, but I can reproduce it only when using prism. 

Issue in the prism repo ->  https://github.com/PrismLibrary/Prism/issues/3064

Please see the repro for screenshots

### Steps to Reproduce

1. Clone https://github.com/anpin/prism-ios-layout
3. Run Debug on iOS -> tap the "Click me" -> Observe `aquamarine` colored space on top of the list 
4. Run NOPRISM on iOS for vanilla MAUI navigation page with the exact same page shown -> Observe no additional space on top of the list 
5. Run Debug on Mac -> Observe aquamarine space on top of the button ->  tap the "Click me" -> Observe pink colored space on top of the list 
4. Run NOPRISM on Mac for vanilla MAUI navigation page with ``almost`` exact same page shown -> Observe no additional space on top of the button or list on the next page 

### Link to public reproduction project repository

https://github.com/anpin/prism-ios-layout

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 2.0(8.0.7). This issue does not repro on Windows 11, Android 14.0-API34, iOS 17.2 and MacCatalyst with below Project:
[prism-ios-layout.zip](https://github.com/dotnet/maui/files/14633710/prism-ios-layout.zip)

Windows:
![image](https://github.com/dotnet/maui/assets/97647558/3e8b0543-53d3-447d-be41-0f7a9d715445)
Android:
![image](https://github.com/dotnet/maui/assets/97647558/8cbed716-06c0-4efd-a3c2-9cbcef3f1ac7)

**Comment by XamlTest** [comment]
<img width="339" alt="Screenshot 2024-03-18 at 5 27 06 PM" src="https://github.com/dotnet/maui/assets/97647558/ef5b4d8f-bace-4ec0-af26-4f37d10bcff3">

<img width="339" alt="Screenshot 2024-03-18 at 5 27 19 PM" src="https://github.com/dotnet/maui/assets/97647558/3873f4f5-778e-4a01-be82-e070b06af6c0">

<img width="533" alt="Screenshot 2024-03-18 at 5 28 50 PM" src="https://github.com/dotnet/maui/assets/97647558/0e174a3d-ef20-4597-a04c-fe765458691b">

<img width="533" alt="Screenshot 2024-03-18 at 5 29 03 PM" src="https://github.com/dotnet/maui/assets/97647558/fb5459c6-f58c-4e64-9194-6120e080e9e3">
