### ISSUE TITLE
[Bug] Broke MAUI while updating from Preview 6 to Preview 7

### ISSUE THREAD

**Issue by 3DSX** [dotnet/maui#2042]
```
sudo dotnet workload install maui                 ✔  969  14:19:27

Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Garbage collecting for SDK feature bands 6.0.100...
Uninstalling workload pack  version 6.0.100-preview.7.1063+sha.f5acc965e-azdo.5006556.
Workload installation failed: The JSON value could not be converted to Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadPackId. Path: $.Id | LineNumber: 0 | BytePositionInLine: 39.
```

**Comment by 3DSX** [comment]
Running from MacOS , net6 preview7

**Comment by Redth** [comment]
Please try this powershell script which should clean up some older packs/metadata from previous previews and try installing again after: https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1

I would recommend using [maui-check](https://github.com/redth/dotnet-maui-check) to do the installation.

**Comment by 3DSX** [comment]
> Please try this powershell script which should clean up some older packs/metadata from previous previews and try installing again after: https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1
> 
> I would recommend using [maui-check](https://github.com/redth/dotnet-maui-check) to do the installation.

Hey Redth, maui-check couldn't do anything because the install process exited, but Maui couldn't know that the workloads were broken, so it marked the workloads correctly installed when they weren't.

So I've run the following command:

dotnet workload install --sdk-version 6.0.100-preview.7.21379.14 --no-cache --disable-parallel android-aot ios maccatalyst tvos macos maui wasm-tools --skip-manifest-update --source "https://api.nuget.org/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.7.21379.14-shipping-1/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json"

The operation was aborted for an unknown reason, but workloads were installed this time correctly.
Following this journey, I've started to run issues with SDK targets and StaticWebAssets then I figured out they were in consequence of the **API changes** from .NET6 Preview **6** to .NET6 Preview **7**.

So what I did was: 
1. Implement API changes taking a look at what Daniel Roth did on his demo project of [Weather 2021](https://github.com/danroth27/BlazorWeather)
2. Update Visual Studio 2022 from Preview **2** to Preview **3**
3. The "Pair to Mac" functionality at Tools>iOS> Pair To Mac after connected, installed the workloads from **Preview 7** which could've also fixed this problem in the first instance.

Hope this helps!
