### ISSUE TITLE
XAML DatePicker Control Does Not Update DateOnly Items

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#20438]
### Description

If you use a DatePicker control with a bi-directionall binding to a DateOnly object it will fail to update the object when a new date is selected. On Windows it emits the message
`Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: '02/08/2024 00:00:00' cannot be converted to type 'System.DateOnly'` 

### Steps to Reproduce

1. Clone the repo
2. Build and run the app on Windows
3. Select a new date in the UI
4. Note that instead of the message coded into the app, 'set' is never called and the error message above is generated.

If you change the DateOnly items into DateTime items the problem goes away.

### Link to public reproduction project repository

https://github.com/david-maw/OnePage-DateOnly.git

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11, Android 14

### Did you find any workaround?

On the face of it a converter looks like it would be an easy workaround but I have not needed to try it.

**Comment by PureWeen** [comment]
Duplicate of #1100

**Comment by david-maw** [comment]
Well, #1100 is an enhancement if you like but this sure smells like a bug to me.  Strikes me that fixing this narrow problem is a lot simpler than doing the larger enhancement in #1100 but either way, I've done my due diligence and reported it, sorry I didn't notice the original one.

**Comment by jfversluis** [comment]
Merged for .NET 10 RC2
