### ISSUE TITLE
[iOS] CollectionView item sizing wrong after refresh

### ISSUE THREAD

**Issue by naaeef** [dotnet/maui#20443]
### Description

On iOS, after refreshing a CollectionView in a RefreshView, items are not sized correctly. After scrolling down and up, it is displayed correctly.

https://github.com/dotnet/maui/assets/43339071/13fa9f75-dba9-4f41-9889-ac605c910399

This issue is currently blocking us from migrating to MAUI.

### Steps to Reproduce

1. Create a new MAUI app
2. Add a RefreshView and and CollectionView
3. Use a DataTemplateSelector with two DataTemplates having different heights
4. Run the app on iOS, refresh the CollectionView

### Link to public reproduction project repository

https://github.com/naaeef/CollectionViewReproductionSample

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No.

**Comment by PureWeen** [comment]
Related https://github.com/dotnet/maui/issues/15177

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 2.0(8.0.7 and 8.0.10). Repro on iOS 17.2 with below Project:
[TestCollectionView.zip](https://github.com/dotnet/maui/files/14646828/TestCollectionView.zip)

**Comment by rmarinho** [comment]
This seems fixed on net9 using CV2 I added a test [here](https://github.com/dotnet/maui/pull/25157/files#diff-a23cebcd9fdeb28ad4404e61ae5a5ae64b6ef3c22fc9f72b338985ade775e9feR12) manually for now but seems to work correctly @naaeef  do you mind pull my branch and try to see validate is fixed?

**Comment by rmarinho** [comment]
I verified and this is fixed on main for CV1 and CV2
