### ISSUE TITLE
[Bug] The dynamic update of AbsoluteLayout and Grid children's positions is not working.

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#2044]
### Description

1. We used the SetLayoutBounds method to position Label in AbsoluteLayout. And I tried to update the position in dynamic time, but the position did not change.

```
AbsoluteLayout.SetLayoutBounds(label1, new Rectangle(100, 10, 101, 100));

```

2. We used the Arrange method to position Label in Grid. And I tried to update the position in dynamic time, but the position did not change.

```
label2.Arrange(new Rectangle(100, 10, 101, 100));

```

### Steps to Reproduce

1. Run the sample
2. Click the button to change view position
3. See the position not changed. 

### Expected Behavior

Label view position update properly. 

### Actual Behavior

Label position not update properly in dynamic time with different layouts. 

### Basic Information

Visual Studio : Visual Studio 2022 Preview
Maui : Maui Preview 6

### Workaround

Updated position with size value changes, position get update properly. This work around works in Maui Preview 5. 

But in Maui Preview 6, this work around also not work. 

### Code

```
 <Grid>

        <AbsoluteLayout  x:Name="layout1" Grid.Row="1"/>
        <Grid  x:Name="layout2" Grid.Row="2"/>

        <StackLayout Grid.Row="3" Orientation="Vertical">
            <Button Text="Change AbsoluteLayout Child position" TextColor="Red" x:Name="button1"/>
            <Button Text="Change Grid child position" TextColor="Red" x:Name="button2"/>
        </StackLayout>

    </Grid>
```
```
Label label1, label2;
		public MainPage()
		{
			InitializeComponent();
			button1.Clicked += Button1_Clicked;
			button2.Clicked += Button2_Clicked;

			label1 = new Label()
			{
				Text = "Text1",
				TextColor = Colors.Black
			};

			layout1.Children.Add(label1);

			AbsoluteLayout.SetLayoutBounds(label1, new Rectangle(10, 10, 100, 100));

			label2 = new Label()
			{
				Text="Text2",
				TextColor=Colors.Black
			};

			layout2.Children.Add(label2);

			label2.Arrange(new Rectangle(10, 10, 100, 100));
		}

        private void Button1_Clicked(object sender, EventArgs e)
        {
			AbsoluteLayout.SetLayoutBounds(label1, new Rectangle(100, 10, 101, 100));
		}

		private void Button2_Clicked(object sender, EventArgs e)
		{
			label2.Arrange(new Rectangle(100, 10, 101, 100));
		}
```
### Sample

[Test1.zip](https://github.com/dotnet/maui/files/6968359/Test1.zip)

**Comment by hartez** [comment]
This is fixed for preview 10.
