### ISSUE TITLE
Unable to return to Maui MainPage 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#20448]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-return-to-Maui-MainPage-/10577562)._

---
[severity:I'm unable to use this version]
I am running a foreground service on .Net Maui Blazor. Once I got the foreground service to start and exit the app, when I try to reopen the application it wont allow me to return to the MainPage. It is stuck on the SplashScreen/Theme for the MainActivity. To re-enter I have to either stop the service from phone or exit debug. I would appreciate a work around that would return me to the Maui MainPage or an update of the framework or any advise to deal with this issue. I am relatively new to coding and i really enjoy coding with Blazor.

---
#### Feedback Bot on 2/5/2024, 05:06 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Duplicate of #20303

**Comment by waldevelop** [comment]
I have the same problem too
