### ISSUE TITLE
[Bug] CollectionView ItemSource bound to ObservableCollection not updating on collection update

### ISSUE THREAD

**Issue by antigones** [dotnet/maui#2045]
### Description

A CollectionView ItemsSource is bound to an ObservableCollection.
The ObservableCollection is populated with an async call to an endpoint on application start.
Adding items in the collection is not reflected in the UI.

### Steps to Reproduce

1. Bind a CollectionView ItemsSource to an ObservableCollection
2. Populate the collection with a call to an endpoint on ViewModel creation
3. CollectionView in the UI is not displayed
4. Scroll the CollectionView and the CollectionView items are displayed

### Expected Behavior

CollectionView updating according to the underlying ObservableCollection when the application starts.

### Actual Behavior

CollectionView does not update according to the underlying ObservableCollection.
If the user scrolls the view in the emulator or the physical device, the CollectionView is correctly displayed.

### Basic Information

- Version with issue: Maui Preview 6
- Last known good version: N/A (code works with Xamarin.Forms)
- IDE:  Visual Studio 2022 (Version 17.0.0 Preview 2.1)
- Platform Target Frameworks:  
  - iOS:  N/A
  - Android: 9.0
  - UWP:  N/A 

- Affected Devices: emulator and physical device

### Reproduction Link

https://github.com/antigones/MAUI-ToDoApp

### Workaround

After fetching the items and adding them to the underlying ObservableCollection, simulate user scrolling CollectionView with:

_cvToUpdate.ScrollTo(1);
_cvToUpdate.ScrollTo(0);

where _cvToUpdate is the CollectionView.

**Comment by meilleur102** [comment]
See the same thing on preview 10. 
I have a ObservableCollection<Model>
When I Add a new Item to the ObservableCollection everything work fine. 
When I modify an Item that already exit the UI dont update. 

Let me know if you want me to open a Issus on this. 
Thanks

**Comment by shimingsg** [comment]
verified with VS 17.2.0 Preview 2.0 [32228.609.main] on Windows and Android:
on Windows: not repro
on Android: repro

**Comment by VincentBu** [comment]
In 32506.368.main, I tried [shimingsg](https://github.com/shimingsg)'s project and it worked properly on Windows and Android.
