### ISSUE TITLE
[Bug] MAUI Blazor Authorization components not working

### ISSUE THREAD

**Issue by 3DSX** [dotnet/maui#2048]
### Description
Authorization components like AuthorizeRouteView or Authorize are not working in Blazor WebView, that are from the package `Microsoft.AspNetCore.Components.WebAssembly.Authentication` (preview **7** version) they just don't work when I instance one of them (Blazor unhandled exception)

Do they only keep working on Blazor Web Assembly as always or I'm missing something?

Hope someone can tell, because this package helps a lot for managing roles and policies through the **ClaimsPrincipal** class

**Comment by 3DSX** [comment]
Fixed the issue myself, happy to share the solution as always.

First, you need to add the options services and authorization core in your Configure method (Startup.cs)


		services.AddOptions();
		services.AddAuthorizationCore();

Following that, add your custom AuthenticationStateProvider by implementing that class and overriding the `GetAuthenticationStateAsync` method

You can return an anonymous identity in the AuthenticationState Task (Anonymous Claims Principal) like this:
   

            var claimsIdentity = new ClaimsIdentity();

            var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

            var authState = new AuthenticationState(claimsPrincipal);

            return Task.FromResult(authState);

In the end, remember to add your custom AuthenticationStateProvider by adding the service as scoped
`					services.AddScoped<AuthenticationStateProvider, CustomAuthenticationStateProvider>();`

![Screen Shot 2021-08-12 at 7 30 55 PM](https://user-images.githubusercontent.com/32218025/129242273-872f3d18-01b7-4c5b-8bf3-92110ea8864a.png)

**Comment by infofromca** [comment]
Thanks for your info.
but I think this should be reopen , because this is tricky way.
we should investigate that behavior inside blazor to deal with it.
also <CascadingAuthenticationState> seems to have the similar exception.
