### ISSUE TITLE
Could not find a driver for automationName 'UIAutomator2' and platformName 'Android'

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#20482]
### Description

We're starting to hit UIAutomater2 issues again
https://dev.azure.com/xamarin/public/_build/results?buildId=107770&view=results

**Comment by jsuarezruiz** [comment]
@rmarinho Is still happening?

**Comment by PureWeen** [comment]
> @rmarinho Is still happening?

https://dev.azure.com/xamarin/public/_build/results?buildId=113270&view=ms.vss-test-web.build-test-results-tab
