### ISSUE TITLE
Windows: Switch shows On/OffContent text

### ISSUE THREAD

**Issue by dotMorten** [dotnet/maui#20486]
### Description

When using the Switch control, on Windows you'll see "On/Off" text. whereas on other platforms you see no text.
This causes a few problems:
1. Inconsistent UI on different platforms.
2. You can't localize/change this text
3. You can't style this text, so in darkmode it looks awful (see issue https://github.com/dotnet/maui/issues/16047 and https://github.com/dotnet/maui/issues/8965)

The WinUI ToggleSwitch control that is used has OffContent and OnContent properties that default to Off/On, but they are not initialized to empty:
https://github.com/dotnet/maui/blob/40649b6c3015188464c6f901eb24316727d1dbea/src/Core/src/Handlers/Switch/SwitchHandler.Windows.cs#L8
Simplest fix will likely be to change this statement to 
`protected override ToggleSwitch CreatePlatformView() => new ToggleSwitch() { OffContent = null, OnContent = null };`

Long term, exposing these two properties on all platfoms would be very useful.

### Steps to Reproduce

Create a Switch control. Compare Windows with iOS and Android - only Windows shows on/off text. If you're in darkmode you might not even notice.

### Version with bug

8.0.6

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.6

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

You can override the handler, but it seems more appropriate to have consistent behavior on all platforms.

**Comment by rmarinho** [comment]
Fixed by https://github.com/dotnet/maui/pull/20487
