### ISSUE TITLE
Back button not visible on Android in .net 8

### ISSUE THREAD

**Issue by simon1144** [dotnet/maui#20480]
### Description

The back button is missing from the top left corner of pages when running a Maui app on the emulator or a real android device. Clicking where it should be takes you back to the previous page. 
![image](https://github.com/dotnet/maui/assets/31506010/9c5146d5-8c37-45bd-87ba-d67279dc7ed9)
Clicking near where the button should be causes the icon to appear
![image](https://github.com/dotnet/maui/assets/31506010/9d531960-4283-4cad-9fbe-c40fd1298938)

It looks like this is an android theme issue and so not a bug. I will close the issue

### Steps to Reproduce

1. Create a default maui project in .net 8
2. Add a new .NET MAUI ContentPage (XAML)
3. Add the route to the AppShell
```c#
        public AppShell()
        {
            InitializeComponent();
            Routing.RegisterRoute("NewPage1", typeof(NewPage1));
        }
``` 
4. Modify the default OnCouterClicked method in MainPage.xaml.cs
```c#
 private async void OnCounterClicked(object sender, EventArgs e)
 {
     await Shell.Current.GoToAsync($"/NewPage1");
 }
``` 
5. Launch the app in the android emulator
![image](https://github.com/dotnet/maui/assets/31506010/12fa8fd3-f2fd-4b97-a0eb-1e6f0f05bf2a)
6. Click the "Click me" button.
7. The top left corner of the app looks like this 
![image](https://github.com/dotnet/maui/assets/31506010/131a567f-a749-40c9-83fc-e1fe59f24498)
but clicking the top left corner takes you back to the previous page. 

### Link to public reproduction project repository

https://github.com/simon1144/MauiBackButtonBug.git

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET 7 MAUI. After looking at it more closely - this is because the background colour is purple rather than white and so works in the same way.

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?
After experimenting some more - it appears that the colours used in the back button image are automatically turned to white and so disappears when displayed against the default white background colour. 

### Relevant log output

```shell
None
```

**Comment by simon1144** [comment]
It looks like this is an android theme issue and so not a bug.

**Comment by adelmurad24** [comment]
Add these to the shell 

    Shell.NavBarIsVisible="True"
    Shell.BackgroundColor="Black"
    Shell.TabBarBackgroundColor="Red"
    Shell.TabBarTitleColor="White"
    Shell.TitleColor="White">

here:

<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MyMauiApp.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MyMauiApp"
    Shell.FlyoutBehavior="Disabled"
    Title="MyMauiApp"
    Shell.NavBarIsVisible="True"
    Shell.BackgroundColor="Black"
    Shell.TabBarBackgroundColor="Red"
    Shell.TabBarTitleColor="White"
    Shell.TitleColor="White">

<ShellContent
        Title="Todo App"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" />

</Shell>
