### ISSUE TITLE
Interop registered singleton cant be used in Blazor Hybrid 

### ISSUE THREAD

**Issue by Basyras** [dotnet/maui#20499]
### Description

Trying to use custom JS interop registered as singleton but getting: `blazor.webview.js:1  One or more errors occurred. (Cannot invoke JavaScript outside of a WebView context.)`

Similar (or even same) was discussed here. But was closed in favor the other ones linked below
https://github.com/dotnet/maui/issues/1762

https://github.com/dotnet/maui/issues/11457

This one says something was already fixed. Is it related to this issue?
https://github.com/dotnet/maui/issues/5804

So naturally I am confused, was this already fixed but I am using old version? Is this another issue?

### Steps to Reproduce

> Repro example linked below

1. Create Blazor Hybrid app
2. Add `exampleJSInterop.js` in wwwroot
3. Add `ExampleJSInterop.cs`
4. Register interop to DI in `MauiProgram.cs`: `builder.Services.AddSingleton<ExampleJsInterop>();`
5. Call `ExampleJsInterop` in `Home.razor` in `OnAfterRenderAsync`
6. Open dev tools with F12
7. Observe error:
```
blazor.webview.js:1  One or more errors occurred. (Cannot invoke JavaScript outside of a WebView context.)
null
```

### Link to public reproduction project repository

https://github.com/Basyras/BlazorHybridSingletonInteropBug

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

Registering interop service as scoped

### Relevant log output

```shell
Exception thrown: 'System.InvalidOperationException' in Microsoft.AspNetCore.Components.WebView.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.JSInterop.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.AggregateException' in System.Private.CoreLib.dll
```

**Comment by RoiChen001** [comment]
Can repro this issue at Windows on the latest17.10 preview2(8.0.14).
![20499](https://github.com/dotnet/maui/assets/143168639/66dc9175-7f16-4466-a139-7cb02de01fea)

**Comment by Eilon** [comment]
Hi, the `JSInterop` service is registered as a 'Scoped' service, meaning it can only be referenced by services with an equal or smaller scope: either from another scoped service, or from a transient service. A singleton scope is larger than scoped so it can't reference it.

Here's where the JSInterop service is registered for BlazorWebView scenarios: https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebView/WebView/src/ComponentsWebViewServiceCollectionExtensions.cs#L26

So for this app, consider registering the interop type as Singleton or Transient.

**Comment by Basyras** [comment]
@Eilon After some time using the workaround that registers interops as scoped I don't have any issue with this behavior but I think that most people coming from "pure" blazor to Maui hybrid hosting will encounter this and will be quite confused or even discourage. I think having an "official statement" somewhere regarding this behavior in docs would be handy.
