### ISSUE TITLE
Optimizing Assemblies for size limit

### ISSUE THREAD

**Issue by alexiusacademia** [dotnet/maui#20490]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/...../first_app/MauiApp1/MauiApp1.csproj::TargetFramework=net8.0-maccatalyst]

**Comment by PureWeen** [comment]
Can you attach a binlog?
https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

Does it build from the command line?

**Comment by alexiusacademia** [comment]
This I think is an automated submitted message and note literally opened here in github. Thank you
