### ISSUE TITLE
ToolbarItem icon doesn't work with MVVM Binding on iOS

### ISSUE THREAD

**Issue by AncientLust** [dotnet/maui#20508]
### Description

ToolbarItem icon doesn't work with MVVM Binding on iOS

This doesn't work:
```
<ContentPage.ToolbarItems>
    <ToolbarItem>
        <ToolbarItem.IconImageSource>
            <FileImageSource File="{Binding FilterStatusIcon}" />
        </ToolbarItem.IconImageSource>
    </ToolbarItem>
</ContentPage.ToolbarItems>


public partial class MainPageVM : ObservableObject
{
    [ObservableProperty] private string filterStatusIcon = "filter";
}
```
![with binding](https://github.com/dotnet/maui/assets/84724571/732aae3a-7402-46f4-9da9-22a9b677566d)

While this one does:
```
<ContentPage.ToolbarItems>
    <ToolbarItem>
        <ToolbarItem.IconImageSource>
            <FileImageSource File="filter" />
        </ToolbarItem.IconImageSource>
    </ToolbarItem>
</ContentPage.ToolbarItems>
```
![without binding](https://github.com/dotnet/maui/assets/84724571/601a8aef-59bc-405b-8f9d-797a195a37da)

### Steps to Reproduce

1. Open repro proj
2. Deploy to iOS device
3. Check that icon wasn't showed
4. Replace binding by direct icon name: File="{Binding FilterStatusIcon}" -> File="filter"
5. Redeploy, icon will appear

### Link to public reproduction project repository

https://github.com/AncientLust/ToolBarItem-icon-binding-issue

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by PureWeen** [comment]
@AncientLust if you bind to the text does the text binding work?

**Comment by JayMansel** [comment]
It's not due to the property casing is it? **f**ilterStatusIcon in your VM and **F**ilterStatusIcon in your XAML?

**Comment by AncientLust** [comment]
@JayMansel naah, MVVM generates property with capital letter:

```csharp
public string FilterStatusIcon
{
    get => filterStatusIcon;
    [global::System.Diagnostics.CodeAnalysis.MemberNotNull("filterStatusIcon")]
    set
    {
        if (!global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(filterStatusIcon, value))
        {
            OnFilterStatusIconChanging(value);
            OnFilterStatusIconChanging(default, value);
            OnPropertyChanging(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangingArgs.FilterStatusIcon);
            filterStatusIcon = value;
            OnFilterStatusIconChanged(value);
            OnFilterStatusIconChanged(default, value);
            OnPropertyChanged(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangedArgs.FilterStatusIcon);
        }
    }
}
```

It even doesn't work with lower one:

![image](https://github.com/dotnet/maui/assets/84724571/052d3c77-af6d-4c07-8363-9c0a1b29ffc6)
