### ISSUE TITLE
[Bug] Clip is off position

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2051]
### Description

```
<Grid 
                Grid.Row="0"
                Grid.Column="{OnIdiom Phone=0, Default=1}"
                Grid.ColumnDefinitions="16,120,8,*,100,16"
                >
                <Image Grid.Column="1"
                    HorizontalOptions="Start"
                    VerticalOptions="Center"
                    WidthRequest="120"
                    HeightRequest="120"         
                    Aspect="AspectFill"
                    Source="https://devblogs.microsoft.com/xamarin/wp-content/uploads/sites/44/2019/03/Screen-Shot-2017-01-03-at-3.35.53-PM-150x150.png">
                    <Image.Clip>
                        <EllipseGeometry
                            Center="60,60"
                            RadiusX="60"
                            RadiusY="60"/>
                    </Image.Clip>
                </Image>

                <Label Text="David Ortinau" Grid.Column="3" LineBreakMode="WordWrap" VerticalOptions="Center" />

                <Button Text="Sign Out" Clicked="OnSignOut" Grid.Column="4" HorizontalOptions="End" VerticalOptions="Center"/>

                <BoxView Grid.ColumnSpan="6" Color="{StaticResource NeutralDarker}" HeightRequest="1" VerticalOptions="End"/>
            </Grid>
```

### Expected Behavior

Should be centered and positioned like this (Pre6):

![image](https://user-images.githubusercontent.com/41873/129096066-afbd9454-9050-438a-97a6-52c842b7a821.png)

### Actual Behavior

Pre7:

![clip-bug](https://user-images.githubusercontent.com/41873/129096226-f1e17277-819d-4223-8f44-64eb1e75a6cc.png)

### Basic Information

- Version with issue: preview.7.1345

### Reproduction Link

https://github.com/davidortinau/WeatherTwentyOne/blob/main/src/WeatherTwentyOne/Pages/SettingsPage.xaml#L131-L143

**Comment by VincentBu** [comment]
Hi David, does it occur on **android** device? I try your code on IOS simulator and everything is OK.
![image](https://user-images.githubusercontent.com/44959937/154624786-b84f0b63-477e-47fa-bcda-8178f00a103d.png)

**Comment by jsuarezruiz** [comment]
The issue should be fixed with latest Preview 14. I am going to close this issue but open a new one if can reproduce the issue again or find a another one.
