### ISSUE TITLE
Microsoft.Maui.FileImageSourceService: Warning: Unable to load image file

### ISSUE THREAD

**Issue by Andrew-51** [dotnet/maui#20513]
### Description

Whenever I try to build an app, on android and on ios from a mac at least, I get in console the error

```
Microsoft.Maui.FileImageSourceService: Warning: Unable to load image file 'Resources/Images/dotnet_bot.png'.

System.InvalidOperationException: Unable to load image file.
   at Microsoft.Maui.FileImageSourceService.GetImageAsync(IFileImageSource imageSource, Single scale, CancellationToken cancellationToken)
```

This happens even with a just created project in .net8 on visual studio and visual studio code

### Steps to Reproduce

1. Create a new project from File -> New Project -> Multiplatform -> .Net Maui
2. Build the app and launch on a device/simulator

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS, Android, macOS

**Comment by PureWeen** [comment]
@Andrew-51 does the image display?

**Comment by Andrew-51** [comment]
> @Andrew-51 does the image display?
> 
> Can you attach a binlog? https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

No, the image is not showing at all. I've added the build output and also debug build log
[Build output testMauiNet8.txt](https://github.com/dotnet/maui/files/14258320/Build.output.testMauiNet8.txt)
[testMauiNet8_Debug_Build_2024-02-13T08_52_32.4876420Z.msbuild.log](https://github.com/dotnet/maui/files/14258340/testMauiNet8_Debug_Build_2024-02-13T08_52_32.4876420Z.msbuild.log)

**Comment by Andrew-51** [comment]
Hi,
after some investigation, looks like the problem was a duplicate appicon include in the csproj file which for some reseaon gave the problem.
On a different build machine, the problem is not showing neither with a new project either with an old project.
