### ISSUE TITLE
[Bug] Workload installation failed: The JSON value could not be converted to... 

### ISSUE THREAD

**Issue by ryanwoodings** [dotnet/maui#2053]
### Description
When running `dotnet workload install maui` I get the following error. I also get this error when attempting to install `ios` and `maccatalyst` workloads. 

### Steps to Reproduce

1. Installed VS 2022 Preview 3
2. updated maui-check and ran maui-check

### Basic Information

- Affected Devices:
HP Spectre, Windows 11 Beta

### Screenshots

![image](https://user-images.githubusercontent.com/413217/129102976-56937b50-fb31-4f59-8055-cd81d31e65e1.png)

**Comment by vanessagertman** [comment]
I am seeing the same error:
`Uninstalling workload pack  version 30.0.100-preview.7.93.
Workload repair failed: The JSON value could not be converted to Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadPackId. Path: $.Id | LineNumber: 0 | BytePositionInLine: 52.
repair
  Repair workload installations.`


After that, I see this error too:
```Warning: Workload repair failed
SHELL: C:\Program Files\dotnet\dotnet.exe workload update --sdk-version 6.0.100-preview.7.21379.14 --no-cache --disable-parallel --from-rollback-file "C:\Users\vanessa\AppData\Local\Temp\maui-check-dotnet-work-dir\workload.json" --source "https://api.nuget.org/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.7.21379.14-shipping-1/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json"

Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.tvos.
Failed to update the advertising manifest microsoft.net.workload.emscripten: Failed to validate package signing.

Verifying Microsoft.NET.Workload.Emscripten.Manifest-6.0.100.6.0.0-rc.1.21409.2

error: NU3004: The package is not signed.

Package signature validation failed.

.
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Failed to validate package signing.```

**Comment by cqgis** [comment]
I am seeing the same error when running  .NET MAUI Check v0.7.3.0

**Comment by kefyru** [comment]
```% sudo dotnet workload repair```
...
...
Garbage collecting for SDK feature bands 6.0.100...
Workload repair failed: The JSON value could not be converted to Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadPackId. Path: $.Id | LineNumber: 0 | BytePositionInLine: 55.

**Comment by E75** [comment]
Yeps, i'm getting the same error on Windows 10 and VS 2022 Preview 3

**Comment by kefyru** [comment]
For me helped dotnet workload repair —no-cache

**Comment by ryanwoodings** [comment]
@3DSX The dotnet workload command that you posted aborted for me too, and it resolved the problem. I can now build MAUI applications in VS 2022 Preview 3. I'm having emulator issues and target framework issues, but your link to the Weather demo looks promising.

**Comment by 3DSX** [comment]
@ryanwoodings Glad to hear that, and yes, I'm still having some trouble with iOS debugging specifically; I've also had troubles with device emulator list, SDK targets, and some other stuff. If there is something I could help with, please let me know!
