### ISSUE TITLE
[Testing] Re-Enable/move DoneClosesKeyboard to Appium

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#20533]

**Comment by jsuarezruiz** [comment]
Is this test https://github.com/dotnet/maui/blob/0d3e90a8030ef50911ca749c902fc0ba9c1517bd/src/Controls/tests/UITests/Tests/Issues/Issue5724.cs#L38?, complete it and implement close IOS keyboard by tapping ‘Done’?

**Comment by jsuarezruiz** [comment]
@PureWeen
