### ISSUE TITLE
"Codesign exited with code 1" issue when try to build an iOS app using visual studio 2022 for mac, Rider and VS Code

### ISSUE THREAD

**Issue by mmuresan** [dotnet/maui#20530]
### Description

I am running Visual Studio for Mac, Rider and VS Code on an M2 Mac laptop.
The Maui application I have is not building, when selecting an attached iPad and then build.
The error I get is "Codesign exited with code 1"
This is NOT tooling related, as I get exactly the same error building from Visual Studio for Mac, Rider and VS Code.
I saw in the past multiple people reporting this bug, but they were dismissed and redirected to VS for Mac team and this is definitely not related to any IDE we are using.
This is not happening with newly created applications.

### Steps to Reproduce

Unfortunately, the application is very complex and the only thing that I can produce is a build log, or anything that the team might need to be able to unblock this.

### Version with bug

8.0.6

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15

### Did you find any workaround?

I tried quite a lot of things and no workaround yet.

**Comment by drasticactions** [comment]
This is a tooling issue. This repo is for the MAUI UI project and it doesn't control the bundling and deployment of applications to devices. That's handled by the .NET SDK and/or IDE tooling. Whatever issue you are hitting is, most likely, not something that can be fixed within this repo. That's why they get redirected elsewhere, so teams with more knowledge of it can address it and help.

Here are some steps to help debug this further:

- Try building an iOS app that doesn't use the MAUI UI framework (`dotnet new ios`). Can you build and deploy that?
- Try building a new template MAUI app, does that deploy?
- Can you deploy an app with Xcode to that device? Just to make sure you can deploy at all.

@rolfbjarne Would you know of other ways to debug this?

**Comment by rolfbjarne** [comment]
The first step would be to get a build log, preferrably a binlog (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs). The codesigning task will output more information than just `"Codesign exited with code 1"`, you can inspect the binlog to see this. Alternatively you can upload it here and we can have a look at it.

**Comment by mirceamuresanse** [comment]
This is the part from the log that shows the code signing failure, but it doesn't say why it failed.
        /Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app/Frameworks/Runtimecore.framework: signed bundle with Mach-O thin (arm64) [com.esri.arcgis.runtime.core]
        
        The stamp file 'obj/Debug/net8.0-ios/ios-arm64/codesign/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app/Frameworks/Runtimecore.framework/.stampfile' does not exit for the item '/Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app/Frameworks/Runtimecore.framework', and it will be created
        Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign 4BC5B175C60B2E255E6B1E465FF35EA5B197FC41 --entitlements /Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/obj/Debug/net8.0-ios/ios-arm64/Entitlements.xcent /Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app
                
        Tool /usr/bin/codesign execution finished (exit code = 1).
                
        /Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app: code object is not signed at all
        In subcomponent: /Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app/System.Net.Security.dll
        
        /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/tools/msbuild/iOS/Xamarin.Shared.targets(2256,3): error : /usr/bin/codesign exited with code 1:
        /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/tools/msbuild/iOS/Xamarin.Shared.targets(2256,3): error : /Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app: code object is not signed at all
        /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/tools/msbuild/iOS/Xamarin.Shared.targets(2256,3): error : In subcomponent: /Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app/System.Net.Security.dll
        /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/tools/msbuild/iOS/Xamarin.Shared.targets(2256,3): error : Failed to codesign '/Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app': /Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app: code object is not signed at all
        /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/tools/msbuild/iOS/Xamarin.Shared.targets(2256,3): error : In subcomponent: /Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app/System.Net.Security.dll
        /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/tools/msbuild/iOS/Xamarin.Shared.targets(2256,3): error : 
        /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8004/tools/msbuild/iOS/Xamarin.Shared.targets(2256,3): error :         
      Done executing task "Codesign" -- FAILED.
    Done building target "_CodesignAppBundle" in project "SE.Geospatial.Mobile.Viewer.csproj" -- FAILED.

    Done building project "SE.Geospatial.Mobile.Viewer.csproj" -- FAILED.
  Done executing task "MSBuild" -- FAILED.
Done building target "DispatchToInnerBuilds" in project "SE.Geospatial.Mobile.Viewer.csproj" -- FAILED.

Done building project "SE.Geospatial.Mobile.Viewer.csproj" -- FAILED.

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#20113
