### ISSUE TITLE
The navigation menu does not display the current cursor position correctly

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/maui#20539]
### Description

The navigation menu does not display the current cursor position correctly 
![image](https://github.com/dotnet/maui/assets/30250585/4d2ca543-b941-4781-b600-d52c8f5a1e44)

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6

### Affected platforms

Windows

**Comment by HuaFangYun** [comment]
![image](https://github.com/dotnet/maui/assets/30250585/5c75eb9f-2926-4a54-9d7d-00f6222f90a5)
![image](https://github.com/dotnet/maui/assets/30250585/3cc46dbd-aef5-4e52-8b5d-f5861f07dfef)

8.0.7

**Comment by PureWeen** [comment]
@HuaFangYun do you know what version this used to work in?

**Comment by HuaFangYun** [comment]
Thank you for your reply.
Maui 8.0.6 And Maui 8.0.7  + VS17.9.0 and VS 17.8.X It's all like this.
Maui 8.0.7 +VS17.9.1  It's right. But when switching, it shows very slow, and it feels like the old cow is climbing the hill, which is very difficult.

**Comment by HuaFangYun** [comment]
https://github.com/dotnet/maui/assets/30250585/0b7fe029-fbee-4394-9f5b-f095d3e4a740

**Comment by HuaFangYun** [comment]
![image](https://github.com/dotnet/maui/assets/30250585/a4e01dd3-156c-442b-b4e1-95f537c5aa39)

**Comment by HuaFangYun** [comment]
![image](https://github.com/dotnet/maui/assets/30250585/67995cae-5fb0-446f-86e2-780c14c683d8)
