### ISSUE TITLE
Endless measure cycle on Android when WebView is placed inside Frame

### ISSUE THREAD

**Issue by rafalka** [dotnet/maui#20550]
### Description

This simple construction:
```XAML
    <VerticalStackLayout>
    <Frame>
        <WebView/>
    </Frame>
    </VerticalStackLayout>
```
causes endless measure cycle on Android.
On iOS/macOS this works fine (not tested on Windows)

### Steps to Reproduce

1. Create a MAUI app
2. Place XAML from description as a content of a page.
3. Run app on Android

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android (all versions)

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 2.0(8.0.7). Repro on Android 14.0-API34, not repro on Windows 11, iOS 17.2 and MacCatalyst with below Project:
[MauiApp3.zip](https://github.com/dotnet/maui/files/14662889/MauiApp3.zip)

**Comment by jfversluis** [comment]
Seeing that Frame is officially deprecated as of .NET 9, I don't think we will be working on this anymore. Also its a bit older by now, so maybe its even resolved in current versions 🤞
