### ISSUE TITLE
Collection View scroll is laggy 

### ISSUE THREAD

**Issue by thanigaiharan** [dotnet/maui#20557]
### Description

Collection View scroll is laggy (IOS and Android) and app crashes when we scroll continuously (android)

### Steps to Reproduce

In our application we have Collection view which shows list of Vehicles as shown in below screen shot. 

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-02-12 at 10 05 23](https://github.com/dotnet/maui/assets/7297955/7e2a147e-b885-414d-9de8-be6a4a3cf2fa)

The Vehicle layout in the Right side of the cell template is Custom control which we render (we are having Grid control and adding the wheel positions to it) the Vehicle layout based on the corresponding input parameters which is binding to the control . 

Here the cell template items are binding with the values from the View Model , and we are dynamically drawing the Vehicle layout (Adding Wheel position controls to the GRID control) which is shown in the right side .

When we scroll the collection view  it is rendering the visible cells and during this time the cell dynamically draws the  Vehicle layout (Custom Control) which is affecting the scroll performance (Laggy in IOS and app crashes in android during continuous scroll). 

https://github.com/dotnet/maui/assets/7297955/fe5dd33f-0d52-41cb-b3f7-905ac9dea83c

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

Checked to control the cell rendering during scrolling but No Luck.

**Comment by angelru** [comment]
It takes a long time for the vehicles to appear too, right?

**Comment by thanigaiharan** [comment]
@angelru Hi, Yes it is taking time to appear too. 

yes, we tested with Release mode with latest .NET SR2 release as well.

**Comment by samhouts** [comment]
If you could please share a .speedscope file (https://aka.ms/profile-maui) and possibly a sample of what your XAML looks like, that would greatly help us work on this issue! Thank you!

cc @jonathanpeppers

**Comment by thanigaiharan** [comment]
@angelru @samhouts  issue was we designed the  VehicleLayout  as Control , Now we replaced it with Graphic content. Now Scrolling is better .

**Comment by angelru** [comment]
@thanigaiharan what are you talking about? It should work well as a control. If you can give an example.

**Comment by thanigaiharan** [comment]
@angelru  The vehicleLayout Control on the Cell is a custom  control which has Stack of Child Controls  inside and we will dynamically generate based on the Configuration Property. This Seems to be heavy operation in scroll. 
So we created Graphic Lite Control which draws the Vehicle Layout dynamically which has Single Visual Element (Canvas).
