### ISSUE TITLE
remove_RequestedThemeChanged cause null reference

### ISSUE THREAD

**Issue by tikomile** [dotnet/maui#20551]
### Description

From our clients we periodically receiving **System.NullReferenceException**
System.NullReferenceException: Object reference not set to an instance of an object.

------------------
Microsoft.Maui.WeakEventManager.RemoveEventHandler(String eventName, Object handlerTarget, MemberInfo methodInfo)
Microsoft.Maui.WeakEventManager.RemoveEventHandler[AppThemeChangedEventArgs](EventHandler`1 handler, String eventName)
Microsoft.Maui.Controls.Application.remove_RequestedThemeChanged(EventHandler`1 value)
Microsoft.Maui.Controls.AppThemeBinding.SetAttached(Boolean value)
Microsoft.Maui.Controls.AppThemeBinding.Unapply(Boolean fromBindingContextChanged)
Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity)
Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity)
Microsoft.Maui.Controls.Style.ApplyCore(BindableObject bindable, Style basedOn, SetterSpecificity specificity)
Microsoft.Maui.Controls.Style.Microsoft.Maui.Controls.IStyle.Apply(BindableObject bindable, SetterSpecificity specificity)
Microsoft.Maui.Controls.MergedStyle.SetStyle(IStyle implicitStyle, IList`1 classStyles, IStyle style)
Microsoft.Maui.Controls.MergedStyle.set_Style(IStyle value)
Microsoft.Maui.Controls.NavigableElement.<>c.<.cctor>b__22_0(BindableObject bindable, Object oldvalue, Object newvalue)
Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
Microsoft.Maui.Controls.NavigableElement.set_Style(Style value)
Core.UI.Controls.CustomViews.CustomMessageBoxView.InitializeComponent()
Core.UI.Controls.CustomViews.CustomMessageBoxView..ctor()
Core.UI.CustomMessageBoxWrapper.ShowError(String title, String message, String errorButtonText, String iconSource)
Core.ExceptionHandler.<>c__DisplayClass1_0.<Handle>b__0()
Java.Lang.Thread.RunnableImplementor.Run()
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Relevant log output

```shell
Microsoft.Maui.WeakEventManager.RemoveEventHandler(String eventName, Object handlerTarget, MemberInfo methodInfo)
Microsoft.Maui.WeakEventManager.RemoveEventHandler[AppThemeChangedEventArgs](EventHandler`1 handler, String eventName)
Microsoft.Maui.Controls.Application.remove_RequestedThemeChanged(EventHandler`1 value)
Microsoft.Maui.Controls.AppThemeBinding.SetAttached(Boolean value)
Microsoft.Maui.Controls.AppThemeBinding.Unapply(Boolean fromBindingContextChanged)
Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity)
Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity)
Microsoft.Maui.Controls.Style.ApplyCore(BindableObject bindable, Style basedOn, SetterSpecificity specificity)
Microsoft.Maui.Controls.Style.Microsoft.Maui.Controls.IStyle.Apply(BindableObject bindable, SetterSpecificity specificity)
Microsoft.Maui.Controls.MergedStyle.SetStyle(IStyle implicitStyle, IList`1 classStyles, IStyle style)
Microsoft.Maui.Controls.MergedStyle.set_Style(IStyle value)
Microsoft.Maui.Controls.NavigableElement.<>c.<.cctor>b__22_0(BindableObject bindable, Object oldvalue, Object newvalue)
Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
Microsoft.Maui.Controls.NavigableElement.set_Style(Style value)
Core.UI.Controls.CustomViews.CustomMessageBoxView.InitializeComponent()
Core.UI.Controls.CustomViews.CustomMessageBoxView..ctor()
Core.UI.CustomMessageBoxWrapper.ShowError(String title, String message, String errorButtonText, String iconSource)
Core.ExceptionHandler.<>c__DisplayClass1_0.<Handle>b__0()
Java.Lang.Thread.RunnableImplementor.Run()
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
```

**Comment by tikomile** [comment]
hello @Toomas75  we have ArgumentOutOfRange to. Which UI framework you use ? (Telerik, DevExpress)

**Comment by Toomas75** [comment]
@tikomile  No third party UI framework

**Comment by Ghostbird** [comment]
Additionally, I just spotted something interesting when my debugger caught another one of these:

> "Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')"

The debugger shows that:
> index: 35
> this: Count = 42

Why is the error even thrown?

**Comment by Toomas75** [comment]
#20615

**Comment by Ghostbird** [comment]
> #20615

Can you elaborate on that? It seems unrelated.

**Comment by Ghostbird** [comment]
@Redth Sorry to ping you like this, but to us this is a release blocking bug of great significance. Any call to `new Label()` in our application randomly crashes. Can you put the right people on this?

**Comment by Toomas75** [comment]
@Ghostbird  this happens (in our project) only if we are using some static (global or local) style. Like in https://github.com/dotnet/maui/issues/20615

**Comment by Ghostbird** [comment]
I still don't really see how these issues relate. Also, why would it only happen seemingly exclusively on the `new Label()` call?. You claim it _only_ happens when using static global (or local) styles. That would mean it happens constantly, as any `dotnet new maui` generates with a ton of static global styles (`Styles.xaml`)

**Comment by Toomas75** [comment]
@Ghostbird  we have global style using appThemeBinding like:

` <Style TargetType="Label">
     <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource Gray900}, Dark={StaticResource Gray100}}" />
     <Setter Property="BackgroundColor" Value="Transparent" />
     <Setter Property="FontFamily" Value="OpenSansRegular" />
     <Setter Property="FontSize" Value="14" />
     <Setter Property="VisualStateManager.VisualStateGroups">
         <VisualStateGroupList>
             <VisualStateGroup x:Name="CommonStates">
                 <VisualState x:Name="Normal" />
                 <VisualState x:Name="Disabled">
                     <VisualState.Setters>
                         <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource Gray300}, Dark={StaticResource Gray600}}" />
                     </VisualState.Setters>
                 </VisualState>
             </VisualStateGroup>
         </VisualStateGroupList>
     </Setter>
 </Style>`

On the view TextColor binding changes

`<Label TextColor="{StaticResource Brown}"/>`

And race condition (depends on OS version, hardware) triggers issue.
If you look at the WeakEventManager code:
[https://github.com/dotnet/maui/blob/cda3eb3381cfb686567ed05e3eb8e8f26c02d785/src/Core/src/WeakEventManager.cs](url)

They are using (_eventHandlers) Dictionary<TKey,TValue> that is not thread safe, and manipulating without locking...

**Comment by Ghostbird** [comment]
Why then does this happen relatively rarely, and (for us) only on `new Label()`) calls? Every new MAUI‌ app is absolutely loaded with static global appthemebindings from the start.

**Comment by Toomas75** [comment]
MAUI team should answer to your questions :) "Happens rarely" because stars should be aligned first. Label itself definitely is not the cause - could be any UI element.

**Comment by Toomas75** [comment]
AppThemeBinding calling global WeakEventManager instance in Application class.

WeakEventManager uses 
readonly Dictionary<string, List<Subscription>> _eventHandlers = new(StringComparer.Ordinal);

Dictonary is not thread safe and when there are concurrent read and write operations, it can lead to potential race conditions and unpredictable behavior.

There is ConcurrentDictionary for concurrent operations.

**Comment by Toomas75** [comment]
I made some tests. If I Call WeakEventManager.AddEventHandler / RemoveEventHandler from multiple threads in parallel then I get exactly the same Error.
But if you look at the WeakEventManager then it's obvious that it's not thread safe by design.
So during layout initialization (and binding) on UI thread, some other non UI thread must trigger some UI change.
PropertyChanged should be marshaled to UI thread (or not always?).
In our case it's possible that some keydown event can trigger current row change for an example.
Will do some more tests if I get actual device with the issue.

**Comment by Toomas75** [comment]
Did some further testing and finally resolved the issue.
In our case this error happens because view/Page were created in background/threadpool thead and shown/navigated sometimes twice:

Simplified code:

//in background thread
var page=new SomePage();
page.DataContext=new someViewModel();

await MainThread.InvokeOnMainThreadAsync(async ()=>
{ 
// in app main thread, but page  initialize is still in bacground/threadpool thread!
 await mainPage.Detail.Navigation.PushAsync(page).ConfigureAwait(false);
}
)

If only one page instance then it's ok. But if multiple in multiple threads then this error happens as WeakEventManager is not thread safe (by design).
If we create page also in MainThread then there is no error and can create/show many pages as there is no concurrent calls to weakeventmanager.

I hope this information will help resolve your issues. @Ghostbird @tikomile

**Comment by cytoph** [comment]
I get the same exceptions (NullReference and ArgumentOutOfRange) on `RemoveEventHandler`. This is most likely due to this method being invoked from another thread than the UI thread. Would it fix the problem if I'd wrap the add/remove of the event handler in something like `InvokeOnMainThread`?

```csharp
public static async Task<bool> ScrollToAsync(this ItemsView view, int index, int groupIndex = -1, ScrollToPosition position = default, bool animate = true)
{
    ArgumentNullException.ThrowIfNull(view);

    var tcsScrolled = new TaskCompletionSource(); // indicates if any scrolling was done at all
    var tcsArrived = new TaskCompletionSource(); // indicates scrolling has arrived at destination index

    view.Scrolled += OnScrolled;

    try
    {
        view.ScrollTo(index, groupIndex, position, animate);

        await Task.WhenAny([tcsScrolled.Task, Task.Delay(500)]).ConfigureAwait(false);

        if (!tcsScrolled.Task.IsCompleted) // scrolling was never actually triggered
            return false;

        await tcsArrived.Task.ConfigureAwait(false);

        return true;
    }
    finally
    {
        view.Scrolled -= OnScrolled;
    }

    void OnScrolled(object sender, ItemsViewScrolledEventArgs e)
    {
        tcsScrolled.TrySetResult();

        if (index < e.FirstVisibleItemIndex || index > e.LastVisibleItemIndex)
            return;

        tcsArrived.TrySetResult();
    }
}
```

**Comment by cytoph** [comment]
> @cytoph you must access UI elements in UI thread. So, you must call view.ScrollTo(index, groupIndex, position, animate) in UI thread.

I, in fact, already call ScrollAsync from UI thread, because I call it from my pages, but as the methods I'm calling from are void, the execution doesn't wait for it to finish. Therefore everything up **until** the `await` clauses still runs in the UI thread, and everything else does not. That's also the reason why I get the error on removing the event handler, not on adding it.

> You can wrap call to ScrollToAsync in InvokeOnMainThread (if UI is shown in MainThread )...
> var isScrolled = await MainThread.InvokeOnMainThreadAsync(() => ScrollToAsync(view, groupIndex, position, animate));

But I think what you wrote should fix both issues, as with it `ScrollToAsync` should "stay" in the UI thread, even when a task is awaited. Will check this 👍

**Comment by Toomas75** [comment]
@cytoph  Just in case - UI thread is the thread where view instance is created (could be any thread). it's MainThread if view is created on MainThread. Would be helpful to see full stacktrace of the error.
