### ISSUE TITLE
XamlC XC0022 error : Binding could be compiled if x:DataType is specified.

### ISSUE THREAD

**Issue by pijnappel** [dotnet/maui#20568]
### Description

MAUI 8.0.7 reports the Errors XC0022 and XC0023 as errors, not as warnings.
I have treat warnings as error active, but `<WarningsNotAsErrors>XC0022,XC0023</WarningsNotAsErrors>` does not help.

### Steps to Reproduce

Create a Binding, leave out x:DataType or set x:DataType to {x:Null}

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

Android, I was *not* able test on other platforms

### Did you find any workaround?

Stay with 8.0.6 for the moment

**Comment by Hottemax** [comment]
We are facing the same issue, and it is breaking our previously successful builds.

Lots of warnings with this error message.
For me, no error code is displayed, so I dont know how you know that these are  XC0022 and XC0023, @pijnappel.

We have no way to fix or ignore this warning via project file or editorconfig.
We can not fix all instances, as we often bind to ViewModels which use generics like `MyViewModel<T>`, where binding with x:DataType is not really possible, or not documented how to do it.

Very bold decision to just unleash hundreds of warnings without an error code that makes it configurable.

<img width="356" alt="image" src="https://github.com/dotnet/maui/assets/17760200/bfd467e0-4de7-449c-8f18-5fca3b80772c">

**Comment by StephaneDelcroix** [comment]
We use `<WarningsNotAsErrors/>` extensively in our code. What I see is that you use a comma ',' as separator, where we expect a semicolon ';'

Could you please try and see if it helps ?

Reading the doc again, it seems CSC allows both as separators. Fixing this...

**Comment by pijnappel** [comment]
I was going by the documentation and didn't think this could be the problem.
Semicolon ';' worked. These codes are now treated as warnings.

**Comment by StephaneDelcroix** [comment]
<img width="886" alt="Screenshot 2024-02-14 at 15 13 59" src="https://github.com/dotnet/maui/assets/313003/2f9f3fb7-f091-4eb1-a5cb-3d98c266fe72">
the documentation is kinda funny

**Comment by StephaneDelcroix** [comment]
@Hottemax we recommend that you don't ignore the warnings, but you can do it by setting `<NoWarn>$(NoWarn);XC0022;XC0023</NoWarn>`

**Comment by Hottemax** [comment]
> @Hottemax we recommend that you don't ignore the warnings, but you can do it by setting `<NoWarn>$(NoWarn);XC0022;XC0023</NoWarn>`

I did that - already after your first link to the Maui.Compatibility repo sample in your initial reply.
Thanks a lot for the quick help!

**Comment by UnusualJustin** [comment]
> @Hottemax we recommend that you don't ignore the warnings, but you can do it by setting `<NoWarn>$(NoWarn);XC0022;XC0023</NoWarn>`

I agree that this is a useful finding and would be better not to ignore, but is there a way in Maui xaml to specify a datatype for a generic type?

**Comment by daniel-smith-sonepar** [comment]
> > @Hottemax we recommend that you don't ignore the warnings, but you can do it by setting `<NoWarn>$(NoWarn);XC0022;XC0023</NoWarn>`
> 
> @StephaneDelcroix, I agree that this is a useful finding and would be better not to ignore, but is there a way in Maui xaml to specify a datatype for a generic type?

Yes we have same issue of using generic types or interfaces to ensure specific properties exist on an object that is bound via XAML.  Not sure how to handle this situation with this new warning.

**Comment by Hottemax** [comment]
> > @StephaneDelcroix, I agree that this is a useful finding and would be better not to ignore, but is there a way in Maui xaml to specify a datatype for a generic type?
> 
> Yes we have same issue of using generic types or interfaces to ensure specific properties exist on an object that is bound via XAML. Not sure how to handle this situation with this new warning.

Yeah, it would be really nice if we could gain some insight on how to achieve this from this issue. I really felt bad not having compiled bindings in these cases, but found no easy way to do it. All the examples we found were always just something along the lines of how to specify the generic type on CollectionView bindings or something similar.

**Comment by StephaneDelcroix** [comment]
generics in XAML are expressed like this `KeyValuePair(x:String, x:String)`. This works for TypeArguments but as I haven't found any test, I can't guarantee it works for x:DataType. If it does not, report an issue, make sure you ping me, and I'll look into that.

**Comment by Hottemax** [comment]
> generics in XAML are expressed like this `KeyValuePair(x:String, x:String)`. This works for TypeArguments but as I haven't found any test, I can't guarantee it works for x:DataType. If it does not, report an issue, make sure you ping me, and I'll look into that.

@StephaneDelcroix Thanks for your reply!

I have read https://learn.microsoft.com/en-us/dotnet/maui/xaml/generics?view=net-maui-8.0, and I don't exactly understand what you want me to try out/test. What would be the XAML syntax if I want to bind to lets say a ViewModel of type `MyViewModel<MyModel>`?

Currently what we do is have a file where we define dozens of "dummy" classes like this:

```csharp
public class ArticleViewModel : BoViewModel<BoArticle> { }
public class ArticleListViewModel : CardListViewModel<BoArticle> { }

public class PebSampleListViewModel : SamplesListViewModel<BoPebSample> { }
public class EmployeeListPageViewModel : CardListViewModel<BoEmployee> { }
```

and then we can do 

`x:DataType="viewmodels:ArticleViewModel"`, and this works ok

But is there any way to avoid this "dummy class", and just bind to `x:DataType="viewmodels:BoViewModel" x:TypeArguments="models:BoArticle"` directly?

Because this kind of syntax is not working. Or can you illuminate what you want us to try?

Thanks for your patience!

**Comment by StephaneDelcroix** [comment]
@Hottemax the syntax (again, I can guarantee it works) would be `x:DataType="viewmodels:ArticleViewModel(viewmodels:BoArticle)"`

**Comment by Hottemax** [comment]
Unfortunately this does not work for me.

`Error XFC0000	Cannot resolve type "clr-namespace:LastradaApp.ViewModels:viewmodels:BoViewModel(models:BoArticle)".	`

if anyone has a link into some sample repo where I can observe this kind of syntax working, it would be greatly appreciated.

**Comment by jeremy-visionaid** [comment]
I'm hitting this issue too. In my case I couldn't easily tell what `x:Type` should be... For Shell ItemTemplate bindings, the documentation merely says

> Shell provides the Title and FlyoutIcon properties to the BindingContext of the ItemTemplate.

In 8.0.6 I'd had the DataType set to `FlyoutItem`, and this appeared to be working (I thought that it was being compiled OK).
In 8.0.7 it compiled but did not work at run time (the text and items were blank). It seems like the secret sauce was actually `x:DataType="BaseShellItem"`.

So, it seems there's a bug here in that if the binding compile then I expect they should work at run time... But also a possible improvement to be made, if xamlc knows that a binding could be compiled, then doesn't already know what the type should be? It could maybe give us a hint to save us some time in fixing the warnings.

**Comment by Hottemax** [comment]
@StephaneDelcroix, according to your offer, should I create an issue for this now, and tag-mention you? Just want to make sure before doing so that this is a real issue and I am not doing something obvious wrong with 

`x:DataType="viewmodels:BoViewModel(models:BoArticle)"`

**Comment by StephaneDelcroix** [comment]
@Hottemax please do

**Comment by durandt** [comment]
> @Hottemax we recommend that you don't ignore the warnings, but you can do it by setting `<NoWarn>$(NoWarn);XC0022;XC0023</NoWarn>`

@StephaneDelcroix Can you point to a piece of documentation or issue/thread describing why XC0022/XC0023 should be avoided? (Or explain here). The warning itself "Binding could be compiled if x:DataType is specified" does not say much.

**Comment by durandt** [comment]
Confirmed the reason why I get many of these warnings is that I am using CommunityToolkit's StateContainer. 

Not sure if it is an issue to report here or on the CommunityToolkit's repo, or even if it is an issue. 

Repro at: https://github.com/durandt/maui-issue6-xaml-datatype-warnings

Example:
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             xmlns:vm="clr-namespace:maui_issue6_xaml_datatype_warnings.ViewModels"
             x:Class="maui_issue6_xaml_datatype_warnings.SecondaryPage"
             x:DataType="vm:PageViewModel">

    <VerticalStackLayout
        toolkit:StateContainer.CurrentState="{Binding CurrentState}"
        toolkit:StateContainer.CanStateChange="{Binding CanStateChange}">

        <toolkit:StateContainer.StateViews>
            <VerticalStackLayout toolkit:StateView.StateKey="Init">
                <ActivityIndicator IsRunning="True" HorizontalOptions="Center" />
                <Label Text="Loading Content..." HorizontalOptions="Center" />
                <Button
                    Text="Switch to next state"
                    Command="{Binding SwitchStateCommand}"
                    HorizontalOptions="Fill" />
            </VerticalStackLayout>
            <!-- More state views -->
        </toolkit:StateContainer.StateViews>
    </VerticalStackLayout>
</ContentPage>
```

I can get rid of the warning if I specify the x:DataType _again_ at the top of the state view:
```
<VerticalStackLayout toolkit:StateView.StateKey="Init" x:DataType="vm:PageViewModel">
```

**Comment by SunshineSpring666** [comment]
Such issue began to appear again in latest Visual Studio preview with DOTNET 9 preview.

**Comment by Hottemax** [comment]
Hi @StephaneDelcroix,

I can confirm it works in the current MAUI release (I get a compile-time error if the property is not found when x:DataType is specified.

However, it would be nice if the support in the XAML editor can be improved
(I can still not F12 to the bound property in the source code, and properties are not offered with Ctrl+Enter code completion, which is, besides the compile-time safety of ensuring the bound property exists, one of the main reasons to use this feature

![image](https://github.com/dotnet/maui/assets/17760200/2fbeed42-7ec3-4d2a-b425-a6aa9c88e858)
