### ISSUE TITLE
[Bug] Read Blazor Webview unhandled exceptions on iOS/Android

### ISSUE THREAD

**Issue by 3DSX** [dotnet/maui#2057]
I have some errors inside my Blazor application that end up with a Blazor unhandled exception.
I'm running my Maui Blazor project on iOS 14.5 Xcode 13.0 and can't find any way neither in the debug window I can get to read those messages.

Is there any way to read them or something I can do with the ILogger service?

**Comment by 3DSX** [comment]
any update on this?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by TanayParikh** [comment]
Hello @3DSX, just wondering if you're still running into this issue. If so, could you kindly provide a minimal, public, github repository which reproduces this issue.

**Comment by TanayParikh** [comment]
Hey @3DSX, thanks for pointing this out. Great news, it's already possible to access the debug window to read the messages:

![image](https://user-images.githubusercontent.com/14852843/151263886-6ce65f95-1ea1-47d3-a9e6-4aeec20909a7.png)

## iOS 
Steps:
1. Open Safari (MacOS app not in simulator)
2. Preferences > Advanced > Show Develop menu in menu bar
3. Run your Blazor Webview app in the simulator
3. Go back to desktop Safari, Develop > Simulator > `0.0.0.0`. If multiple `0.0.0.0` are shown select the one that highlights the webview (makes blue)
4. Web inspector pops up for the iOS simulator webview. Visit the `Console` tab to see the messages.

![image](https://user-images.githubusercontent.com/14852843/151264650-c544ea51-f60d-4e2c-b1c7-8eadefb2fae1.png)

## Android
Steps:
1. Start emulator and navigate to Blazor Webview app
2. Open Edge / Chrome
3. Go to `chrome://inspect/#devices`, you should see 
![image](https://user-images.githubusercontent.com/14852843/151270012-8fbd6f33-8b92-458b-be93-98dd05104e89.png)
4. Select `inspect` to pop open DevTools. Visit the `Console` tab to see the messages.


@guardrex could we please get this documented somewhere? I feel like this may be a common issue and don't know if this GitHub issue will offer enough discoverability.

**Comment by javiercn** [comment]
@TanayParikh I've captured more details from this issue in https://github.com/dotnet/maui/issues/4441 as there are several issues around exceptions that are overlapping with each other.

**Comment by TanayParikh** [comment]
Thanks @javiercn, I'm going to close this issue out in favor of #4441.
