### ISSUE TITLE
it working ,but now when this is errur Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression Erreur	NU1012	La version de la plateforme n'est pas présente pour un ou plusieurs frameworks cibles, même s'ils ont spécifié une plateforme : net8.0-ios, net8.0-maccatalyst	MauiApp1	C:\Users\cc\Desktop\MauiApp1\MauiApp1\MauiApp1.csproj	1	

### ISSUE THREAD

**Issue by naoufel19** [dotnet/maui#20593]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Hey @naoufel19! Thanks for your interest in .NET MAUI, sorry you hit a snag here. When I translate the error message, I seem to land on the one described here: https://learn.microsoft.com/dotnet/maui/troubleshooting?view=net-maui-8.0#platform-version-isnt-present

There it says: 

> This problem typically results from having an x86 and x64 SDK installed, and the x86 version is being used. Visual Studio and .NET MAUI require the x64 .NET SDK. If your operating system has a system-wide PATH variable that is resolving the x86 SDK first, you need to fix that by either removing the x86 .NET SDK from the PATH variable, or promoting the x64 .NET SDK so that it resolves first. 

This assumes that you know about the PATH variable and how to change it. Is that something you're familiar with? Could you try that and see if it works?

**Comment by naoufel19** [comment]
It was working fine i create the first page login but i see message for update i do it ,all project .xaml and .xaml.cs red line i have now vs 2022 community 17.9.0 and sdk dotnet-sdk-8.0.101-win-x64 i create new project but i have problem
![Uploading Capturedd.PNG…]()

**Comment by naoufel19** [comment]
@jfversluis  @PureWeen

**Comment by jfversluis** [comment]
I'm not sure I understand. You were able to compile and run a .NET MAUI app before? But then you added a new page and then it stopped working? The screenshot you tried to add didn't work it seems.

**Comment by naoufel19** [comment]
@jfversluis Now i create new project .net maui this is the error  
![e](https://github.com/dotnet/maui/assets/159693391/c07cab29-96e9-4671-b79c-70fde1ec4e60)
![e1](https://github.com/dotnet/maui/assets/159693391/56f6f091-416d-4902-93f8-35d5cfc35585)

**Comment by jfversluis** [comment]
If you do `dotnet workload list` in the terminal, what does that give you?

How did you install .NET MAUI? Did you do it through Visual Studio? Are you planning on using iOS and/or Mac Catalyst? If you go into your csproj file and remove `net8.0-ios` and `net8.0-maccatalyst` from the TargetFrameworks and save it, does it work then?

**Comment by naoufel19** [comment]
@jfversluis  this is whene i do dotnet workload list 
![ee](https://github.com/dotnet/maui/assets/159693391/81005738-108d-4734-b9b0-778847b36cb1)
 i install .net maui 
![ss](https://github.com/dotnet/maui/assets/159693391/df871a0f-746a-49e4-ba33-83242cb97806)

**Comment by jfversluis** [comment]
@naoufel19 did you manage to make any progress with this? Did you maybe also run other workload commands in an attempt to install MAUI?
