### ISSUE TITLE
[Bug] Labels with dynamic text do not update.

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#2060]
### Description

When I click the Click Me button on the Maui default sample, the current count value increases. The second digit value is not displayed after reaching the value of two digits.

### Steps to Reproduce

1. Run the sample
2. Click Click Me button
3. When number reach 10, see the second digit not showing. 

### Sample

[Test2.zip](https://github.com/dotnet/maui/files/6973287/Test2.zip)

### Expected Behavior

Updated text have to display complete text with proper alignment.

### Actual Behavior

Updated text cropped. 

### Basic Information

Visual Studio : Visual Studio 2022 Preview
Maui : Maui Preview 6

**Comment by hartez** [comment]
This is fixed in preview 7 (and on main).
