### ISSUE TITLE
Splash Screen does not update iOS

### ISSUE THREAD

**Issue by EminNiftili** [dotnet/maui#20604]
### Description

When changing the splashscreen (or icon), the changes are visible on both Android and iOS simulators, but when deployed to a physical device, it shows the original purple background with .NET in the centre. Also same problem happened for app-icon.

 For this issue, all dotnet version have same problem (DotNet 7, DotNet 8)

My Repo [link](https://github.com/EminNiftili/MauiApp-SplashScreen-Bug)

### Steps to Reproduce

1. Create a new .NET MAUI App application
2. Replace the content of splash.svg with another image.
2. Replace the content of appicon.svg and appiconfg.svg with another image.
4. Run the project on a local device (android). I used an Redmi Note 9 Pro. Android 12. MIUI GLOBAL 14.0.3
5. Note the splash screen has been changed
6. Run the project on a local device (ios) - I am using an iPhone 15 Pro Max, 17.3.1 and Iphone SE gen 3rd gen 15.5
7. Both of device note the splash screen remains with the stock ".NET" item.

### Link to public reproduction project repository

https://github.com/EminNiftili/MauiApp-SplashScreen-Bug

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5, iOS 16.7.5, iOS 17.3.1, 

### Did you find any workaround?

No workaround at this time

**Comment by acaliaro** [comment]
This should happen if you work on a windows machine. You should use a Mac to have the splash screen updated

**Comment by EminNiftili** [comment]
> This should happen if you work on a windows machine. You should use a Mac to have the splash screen updated

I will relocate my project to Mac in accordance with your answer.
