### ISSUE TITLE
[Testing] Rework Appium Runner so that it goes directly to tests instead of navigates

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#20614]
### Description

The legacy tests currently run a lot faster than the appium tests and we should look at making the tests navigate directly to tests opposed to requiring in app navigation

Examples for legacy tests

![image](https://github.com/dotnet/maui/assets/5375137/71533cc7-42e4-424e-98ff-0b02aa6a992d)

![image](https://github.com/dotnet/maui/assets/5375137/c72fd1d6-fee5-455f-a527-93e7b0c1ff2d)

**Comment by jsuarezruiz** [comment]
Work in progress here https://github.com/dotnet/maui/tree/fix-20614
