### ISSUE TITLE
Support compiled bindings for generic ViewModels

### ISSUE THREAD

**Issue by Hottemax** [dotnet/maui#20616]
Please support compiled bindings for ViewModels based on a generic type.

Sample:

- classes: `MyViewModel<T>`, `MyModel`
- in code-behind: `BindingContext = new MyViewModel<MyModel>()`

In Xaml, I want to bind
 
```
x:DataType="viewmodels:MyViewModel(models:MyModel)"
```

_Originally posted by @StephaneDelcroix in https://github.com/dotnet/maui/issues/20568#issuecomment-1946295454_

> @StephaneDelcroix, according to your offer, should I create an issue for this now, and tag-mention you? Just want to make sure before doing so that this is a real issue and I am not doing something obvious wrong with `x:DataType="viewmodels:BoViewModel(models:BoArticle)"`

>@Hottemax please do

  
There was a similar request in the Xamarin.Forms github: https://github.com/xamarin/Xamarin.Forms/issues/7161

**Comment by StephaneDelcroix** [comment]
we would need to support this syntax for x:Type as well.

currently, we're using the type as a string, but we should use the TypeArgumentsParser we already use elsewhere
