### ISSUE TITLE
GeoLocation.GetLocationAsync() failing on sequential calls after initially getting the location.

### ISSUE THREAD

**Issue by BrandanN21** [dotnet/maui#20620]
### Description

When using the location services in iOS we are seeing that it will work for the first geo location call, but if you then force close the application and re open the app it then fails to get the location. The call hangs and will freeze the application with the location call never returning anything and it never errors out. 

We have major inconsistencies with deploying this to a simulator and physical devices. In the last 24 hours we have been able to deploy this twice and have it work, but if we deploy it again to a simulator or device it will then break. This leads us to believe that it could be something that is corrupt when our IDE's are packaging the application and deploying to the devices?

Code:
```
           this._isCheckingLocation = true;

            GeolocationRequest request = new(GeolocationAccuracy.Best, TimeSpan.FromSeconds(10));

            this._cancelTokenSource = new CancellationTokenSource();

            Location location = await Geolocation.Default.GetLocationAsync(request, this._cancelTokenSource.Token);
```

### Steps to Reproduce

Use GeoLocation.Default.GetLocationAsync();
proceed to get location successfully
close out of the application (force close),
restart the application
GeoLocation.Default.GetLocationAsync() is called again
application freezes and the GetLocationAsync call never returns and gets hung up, even with a 10 second timeout. 

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

iOS

### Affected platform versions

iOS 17.2+

### Did you find any workaround?

No we are unable to do any secondary calls to the location service without it hanging up and failing.

**Comment by PureWeen** [comment]
I did a quick test from our sample app and wasn't able to reproduce. 

Can you include a small repro app and then I can try your sequence of events.
So this all works fine for you if you bump down to 8.0.3 GA?
