### ISSUE TITLE
[Bug] `Handler not found for view Microsoft.Maui.Controls.Compatibility.AbsoluteLayout` exception occur when using AbsoluteLayout

### ISSUE THREAD

**Issue by sheiksyedm** [dotnet/maui#2062]
### Description

When using AbsoluteLayout in MAUI app, the exception thrown

Handler not found for view Microsoft.Maui.Controls.Compatibility.AbsoluteLayout.'

### Steps to Reproduce

1. Add the below code and run. 

```
<cmp:AbsoluteLayout Margin="20">
        <BoxView Color="Silver"
                 cmp:AbsoluteLayout.LayoutBounds="0, 10, 200, 5" />
        <BoxView Color="Silver"
                 cmp:AbsoluteLayout.LayoutBounds="0, 20, 200, 5" />
        <BoxView Color="Silver"
                 cmp:AbsoluteLayout.LayoutBounds="10, 0, 5, 65" />
        <BoxView Color="Silver"
                 cmp:AbsoluteLayout.LayoutBounds="20, 0, 5, 65" />
        <Label Text="Stylish Header"
               FontSize="24"
               cmp:AbsoluteLayout.LayoutBounds="30, 25" />
    </cmp:AbsoluteLayout>
```

- IDE: Visual Studio 2022 Preview 3
- .NET MAUI Preview 7.

**Comment by jayaleshwari** [comment]
Hi Team,

We are also facing the same issue when use Microsoft.Maui.Controls.Compatibility.Layout<View>.

**Comment by saravananmadhesh** [comment]
Faced same exception with absolute layout.

**Comment by davidortinau** [comment]
#2136

**Comment by rmarinho** [comment]
Can you remove the compatibility and just use AbsoluteLayout, we have added the new version to the default namespace

**Comment by hartez** [comment]
#3723 should fix this, but we strongly recommend using the new AbsoluteLayout in the default namespace.
