### ISSUE TITLE
Dotnet command not found MAC OS 

### ISSUE THREAD

**Issue by yobad** [dotnet/maui#20629]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am using a Mac mini with the apple M1 chip, Mac OS: 13.0 
1. I installed the botnet sdk 8.0 version 8.0.200
2. I have VS code Version: 1.82.2
3. I added the extension .NET MAUI v0.8.44
4. All dependencies were installed (C# extension and C# Dev Kit) 
5. I opened a new terminal and entered this command: sudo dotnet workload install maui
6. The command is not found

**Comment by jfversluis** [comment]
Hey @yobad thank you so much for your interesting in .NET and .NET MAUI! Sorry you hit a little snag here.

If you navigate manually, either through the command-line or in Finder to `/usr/local/share/dotnet` do you see `dotnet` there? And what is the output of `echo $PATH` is there a reference to the folder I just mentioned there? If not, `dotnet` is not added to your PATH environment variable. That variable is used to identify paths where often used programs are, like `dotnet`.

How to add something to your PATH variable is a bit dependant on what terminal you are using, probably zsh or maybe bash. You should be able to see that if you open the Terminal app and it should say in the title bar of that window. 

Does this help at all?
