### ISSUE TITLE
[iOS] Editor does not scroll when cursor goes behind keyboard

### ISSUE THREAD

**Issue by blakepulman** [dotnet/maui#20631]
### Description

When the text content of an editor is being edited with the soft keyboard open, the editor should scroll to keep the cursor in view (i.e. when a new line is created or the text continues onto another line), however instead, the text continues behind the soft keyboard, and is unable to be scrolled into view. 

Tested on 8.0.3, 8.0.7, and 9.0.0-preview.1.9973, all display the same behaviour. 

### Steps to Reproduce

1. Load the repro project (including setting an app identifier if testing on a physical device)
2. Start the application on an iOS device or simulator
3. Edit text in the editor (bottom half of the screen) with the soft keyboard, so that it would go behind the keyboard.
4. Notice that the view does not scroll, and you are unable to scroll the text into view without closing and reopening the keyboard. 

### Link to public reproduction project repository

https://github.com/blakepulman/MauiiOSEditorNotScrolling

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

**Comment by mattleibow** [comment]
@tj-devel709 @PureWeen thoughts?

**Comment by blakepulman** [comment]
Also tested in .NET 7.0.313 and iOS 16.4, both display the same behavior.

**Comment by awattar** [comment]
Any updates?

**Comment by ajay-mundi** [comment]
Any updates on this or a workaround?
