### ISSUE TITLE
[BUG] Windows Shell Flyout Navigation fails to navigate to same page after navigating back from it

### ISSUE THREAD

**Issue by ne0rrmatrix** [dotnet/maui#20635]
### Description

Open sample app and navigate to any page. Click on back button. Then navigate to page you just left. It fails to change page. This affects all pages in sample app. This is a windows only issue. If you navigate to another page then go back to page you first navigated to it works fine. This only is an issue if you navigate to a page and then back. Then try to navigate to the same page. 

### Steps to Reproduce

1. Open and run sample app from Maui community toolkit.
2. Navigate to any page in menu.
3. Click back button.
4. Navigate to the same page
5. Does not work!

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 Build 10.0.19041.0

### Did you find any workaround?

If you want to navigate back to the page you were just on is to navigate to any other page then click back and then navigate to the page you want. As long as you do not try to load the same page after clicking on back button it works.

**Comment by mattleibow** [comment]
How are you navigating? Using the shell items in the flyout or via some Navigation.Xxx or Shell.Current.GotoAsync?

**Comment by ne0rrmatrix** [comment]
> How are you navigating? Tapping the shell items in the flyout or via some Navigation.PushAsync or Shell.Current.GotoAsync?

Shell.Current.PushAsync() is what we use. The flyout menu itself works fine. It is when we navigate inside page to subpage it fails to navigate. We are using shell flyout menu as base menu.
