### ISSUE TITLE
aot-runtime.c:1579, condition `data' not met

### ISSUE THREAD

**Issue by arek-corp** [dotnet/maui#20657]
### Description

I'm trying to improve the performance of my .NET iOS application by enabling AOT and using interpreter only if absolutely needed. I'm using the following syntax in my .csproj file:
```
<UseInterpreter>true</UseInterpreter>
<MtouchInterpreter>-all,AutoMapper.dll,CommunityToolkit.Mvvm.dll,FluentValidation.dll, and so on </MtouchInterpreter>
```

However, when I run the on on a device, the app builds successfully without any unusual warnings but immediately crashes with no info on the debugger side. In the device logs I can only see the following line:
```
error: * Assertion at /Users/runner/work/1/s/src/mono/mono/mini/aot-runtime.c:1579, condition `data' not met
```

This seems to be related to some issue with loading AOT for specific assembly. I've tried specifying all the assemblies which I can find in my application package (.app) but the app still crashes. At this point I have no idea which DLL the AOT runtime is complaining about since I'm including all DLLs explicitly at the moment in `<MtouchInterpreter>` tag.

How do I figure out which specific DLL is causing the issue? Is there a way to force Mono to log some extra information in the device log when the crash happens?

Note (probably doesn't matter): this is actually not a MAUI app but a .NET iOS-only app which was migrated from Xamarin.iOS.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Enabling interpreter globally by omitting `<MtouchInterpreter>` tag resolves the issue but this means I'm not taking advantage of AOT at all.

**Comment by drasticactions** [comment]
> Note (probably doesn't matter): this is actually not a MAUI app but a .NET iOS-only app which was migrated from Xamarin.iOS.

This 100% matters, because this repo is for the cross-platform MAUI UI project, and you want the SDK [xamarin/xamarin-macios](https://github.com/xamarin/xamarin-macios) or [runtime](https://github.com/dotnet/runtime) repos.

CC @rolfbjarne

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-macios#20133
