### ISSUE TITLE
Getting 'Workload ID maui is not recognized' error when attempting to install .NET Maui

### ISSUE THREAD

**Issue by jimmyshultz** [dotnet/maui#20659]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: macos Sonoma 14.2.1

I am getting the error "Workload ID maui is not recognized" when I run "dotnet workload install maui" in my terminal.
I have the most recent version of dotnet that brew will install on my Mac: 8.0.101.  How can I resolve this?

**Comment by drasticactions** [comment]
To the best of my knowledge, Microsoft doesn't maintain the brew version of .NET, and it's also not up to date ([8.0.200](https://dotnet.microsoft.com/en-us/download) was released on the 15th). While it should "probably" work I don't think workloads of any type are actively tested against it, so YMMV.

Could you try uninstalling the brew version and installing the supported one from [our servers](https://dotnet.microsoft.com/en-us/download)?
