### ISSUE TITLE
[Bug] Span doesn't have property ForegroundColor

### ISSUE THREAD

**Issue by DeanFaizal** [dotnet/maui#2066]
### Description
The Xamarin.Forms Span control has a ForegroundColor but the MAUI Span doesn't.

### Steps to Reproduce

1. Port a Xamarin.Forms app that uses Span.ForegroundColor to MAUI
2. 
3. 

### Expected Behavior
Span can be ported as is

### Actual Behavior
MAUI Span doesn't have ForegroundColor Property

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by shimingsg** [comment]
verified with VS 17.2.0 Preview 2.0 [32228.609.main], span does not have property ForegroundColor

**Comment by Redth** [comment]
Named as TextColor.
