### ISSUE TITLE
Error 0x80070005

### ISSUE THREAD

**Issue by saleemkalro** [dotnet/maui#20661]
When i run Maui app in my window 10 machine. it stopped with error 0x80070005.

**Comment by jfversluis** [comment]
Hey @saleemkalro thanks for the report! Unfortunately this is too little information to say anything useful about it.

[Searching](https://github.com/dotnet/maui/issues?q=is%3Aissue+0x80070005+is%3Aclosed) for the error code you provided there already seem to be a good number of issues describing this possibly with solutions or workarounds.

If you still think this is an issue in the .NET MAUI SDK, please open a new issue with the Bug Report template and make sure you fill out the fields as best as you can providing at least screen shots, reproduction steps and a reproduction sample for us to look at.

Thanks!
