### ISSUE TITLE
EnableLLVM make Application Crash

### ISSUE THREAD

**Issue by Eskissimo** [dotnet/maui#20665]
### Description

When i compile for release with the parameter  EnableLLVM at True. The generate APK Launch, show the splashscreen, the first page for 1/2 seconds and the application crash.

### Release Property group
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
		<DebugType>none</DebugType>
		<EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
		<RunAOTCompilation>True</RunAOTCompilation>
		<EnableLLVM>True</EnableLLVM>
		<PublishTrimmed>True</PublishTrimmed>
		<AndroidUseAapt2>True</AndroidUseAapt2>
		<AndroidEnableProfiledAot>True</AndroidEnableProfiledAot>
		<Optimize>True</Optimize>
		<AndroidEnableMultiDex>True</AndroidEnableMultiDex>
		<AndroidLinkTool>r8</AndroidLinkTool>
		<AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
		<AndroidPackageFormat>apk</AndroidPackageFormat>
	</PropertyGroup>

### Nugets packages
	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.7" />
		<PackageReference Include="CommunityToolkit.Maui" Version="7.0.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.59" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.59.0" />
		<PackageReference Include="SkiaSharp" Version="2.88.7" />
	</ItemGroup>

### Proguard configuration
-keepclassmembers public class androidx.security.crypto.** {
    public <fields>;
}

-keepclassmembers public class androidx.startup.** {
    public <fields>;
}

-keepclassmembers public class androidx.core.app.** {
    public <fields>;
}

_If i don't add androidx.startup & androidx.core.app the application crash immediatly._

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by Eskissimo** [comment]
Adb Log :
[log.zip](https://github.com/dotnet/maui/files/14319083/log.zip)

**Comment by mattleibow** [comment]
This issue was moved to xamarin/xamarin-android#8736
