### ISSUE TITLE
Multiple entries for same Color value DimGrey

### ISSUE THREAD

**Issue by axa88** [dotnet/maui#20675]
https://github.com/dotnet/maui/blob/7773f909f93dabef282e0f6228081e3f04eafe2a/src/Graphics/src/Graphics/Color.cs#L804

One should be removed

**Comment by jfversluis** [comment]
You mean DimGray and DimGrey? Notice how there is an a and an e in there. Probably to account for both British English as wel as American English 😄 

I don't see a real need to remove it tbh. Is there anything I'm overlooking?

**Comment by jfversluis** [comment]
Hey I didn't say it was the best of decisions, but it has been made with this one 😄 and not worth it to make breaking changes over. Thanks!
