### ISSUE TITLE
[BUG] [VS Code] .NET Maui Command Line Tools Not Installed

### ISSUE THREAD

**Issue by jbtdevgit** [dotnet/maui#20674]
### Description

My cmdline-tools is not being detected by the .NET MAUI extension

```
User preferred Java SDK path stored on Settings: C:\Android\Android-Jdk
JAVA_HOME value found: C:\Android\Android-Jdk
Java SDK path to be used: C:\Android\Android-Jdk
 
User preferred Android SDK path stored on Settings: C:\Android\Android-Sdk\sdk
ANDROID_HOME value found: C:\Android\Android-Sdk\sdk
Android SDK path to be used: C:\Android\Android-Sdk\sdk
 
Android components:
	- Java SDK (version: '11.0.21'): installed.
 
	Android SDK recommended required components:
	- platforms/android-34 (version: '2'): installed.
	- build-tools/34.0.0 (version: '34.0.0'): installed.
	- platform-tools (version: '34.0.5'): installed.
	x cmdline-tools/11.0: not installed.
 
	Android SDK recommended optional components:
	- emulator (version: '33.1.24'): installed.
	- system-images/android-34/google_apis/x86_64 (version: '8'): installed.
```

![image](https://github.com/dotnet/maui/assets/44351076/9543975d-26fa-4c3f-aa81-48a606903567)
![image](https://github.com/dotnet/maui/assets/44351076/55a41672-b1f3-4a19-926f-8ac4b2656f08)
![image](https://github.com/dotnet/maui/assets/44351076/ed9c6db8-695a-46ab-8bd8-4c529091854b)

Android Studio CMD Line Tools
![image](https://github.com/dotnet/maui/assets/44351076/c7e65576-0c67-46f5-ae63-c7c18d907d29)

Running a sample app using Android Studio
![image](https://github.com/dotnet/maui/assets/44351076/a69cce89-12cd-48b3-8d44-a1fbcfeb20d2)

Steps To Reproduce
No response

Expected Behavior
Should be able to detect the latest cmd line tools

Environment Information
OS : Windows
VS Code : 1.86.2
.NET MAUI Extension : 0.8.44

### Steps to Reproduce

Open any .NET MAUI app using VS Code

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

Android

### Did you find any workaround?

N/A

**Comment by jbtdevgit** [comment]
Please do not put this to backlog, this is a big issue as it shows on how slow updates gets to the vs code -- especially for those who are using VS code for mac and VS mac is going to be shut down sooner or later. Posted this on https://github.com/microsoft/vscode-dotnettools/issues/842 dotnet tools and it hasn't give any response since January 7. Not sure where should I post this as it is getting ignored.

**Comment by drasticactions** [comment]
This isn't an issue that can be fixed here, as this is the MAUI UI repo and it doesn't maintain that tooling. So it's not going in this repos backlog, it will be closed, as you did post it in the right one. You had also closed that issue and reopened it, so more likely then not they had not seen it.
