### ISSUE TITLE
[Bug] Label is blank until UI is updated

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2067]
### Description

The "Clear" label in this view initial loads blank. If I hot reload the size of the label, it appears. Or if I rotate the emulator.

```
<StackLayout xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             Spacing="15"
             x:Class="WeatherTwentyOne.Views.CurrentWidget">

    <Image
        WidthRequest="200"
        HeightRequest="200"
        HorizontalOptions="Center"
        Aspect="AspectFit"
        Source="weather_partly_cloudy_day.png" />

    <Label
        Text="52℉"
        HorizontalOptions="Center"
        class="Title1" />

    <Grid>
        <Frame
            CornerRadius="15"
            HorizontalOptions="Center"
            Padding="0"
            BackgroundColor="{StaticResource Primary}">
            <Grid
                RowDefinitions="4,*,4"
                ColumnDefinitions="15,*,15"
                RowSpacing="0"
                ColumnSpacing="0"
                HorizontalOptions="Center">
                <Label
                    Grid.Row="1"
                    Grid.Column="1"
                    Text="Clear"
                    HorizontalOptions="Center"
                    FontSize="18"/>
            </Grid>
        </Frame>
    </Grid>

</StackLayout>
```

This view sits here in the page hierarchy:

![image](https://user-images.githubusercontent.com/41873/129227788-2046b552-dc61-48ca-b379-b0e24a6590e4.png)

### Expected Behavior

![Screenshot_1628783153](https://user-images.githubusercontent.com/41873/129227308-88c9394b-775a-4335-b4cb-482cc8f051b6.png)

### Actual Behavior

![Screenshot_1628783142](https://user-images.githubusercontent.com/41873/129227326-37487709-a737-4108-9d73-f2d3e0e8fb52.png)

### Basic Information

- Version with issue: rc.1.1351

### Reproduction Link

https://github.com/davidortinau/WeatherTwentyOne/blob/main/src/WeatherTwentyOne/Views/CurrentWidget.xaml

**Comment by hartez** [comment]
This is fixed for Preview 9.
