### ISSUE TITLE
VScode Maui Code build error

### ISSUE THREAD

**Issue by fynnricardo** [dotnet/maui#20680]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: macos

Build FAILED.

/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/17.2.8022/tools/msbuild/iOS/Xamarin.Shared.targets(1838,3): error : Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools'. Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK). [/Users/ricardofynn/Maui/MauiApp1/MauiApp1.csproj::TargetFramework=net8.0-maccatalyst]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/17.2.8022/tools/msbuild/iOS/Xamarin.Shared.targets(1838,3): error :          [/Users/ricardofynn/Maui/MauiApp1/MauiApp1.csproj::TargetFramework=net8.0-maccatalyst]
    0 Warning(s)
    1 Error(s)

**Comment by drasticactions** [comment]
@fynnricardo You either don't have Xcode installed, or you need to make sure the path to Xcode is set in the command line, as right now it's pointing to the CommandLineTools which are incorrect.

If you have downloaded Xcode, then go to the terminal and run

`sudo xcode-select -s /Applications/Xcode.app`

And replace `/Applications/Xcode.app` with where you downloaded Xcode if it's different from the default. Then it should work.

**Comment by drasticactions** [comment]
Also, the text issue has already been filed by @BretJohnson, 

https://github.com/xamarin/xamarin-macios/issues/19818

And the docs instructions https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=visual-studio-code#iosxcode-setup should also work.
