### ISSUE TITLE
FlyoutHeader on iOS does not change its size after adding new content

### ISSUE THREAD

**Issue by MatthewJer** [dotnet/maui#20696]
### Description

Adding new content does not change the size of the FlyoutHeader on iOS. Even setting the RequestHeight or making parts of the content visible/invisible does not trigger a size change. On Android, the Flyoutheader adjusts it's size perfectly.

iOS:
![image](https://github.com/dotnet/maui/assets/72466347/ae9b8b5f-d4b8-4ce9-a515-67d2e15ec01b)

Android:
![image](https://github.com/dotnet/maui/assets/72466347/2352b961-5ea8-459a-9b7c-5fec744c2a40)

### Steps to Reproduce

1. Open the reproduction project.
2. Start the App on a iOS device.
3. Click the Button.

### Link to public reproduction project repository

https://github.com/MatthewJer/TestDynamicFlyoutMenuHeader

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 2.0(8.0.14). Repro on iOS 17.2, not repro on  Android 14.0-API34 with below Project:
[TestDynamicFlyoutMenuHeader.zip](https://github.com/dotnet/maui/files/14751866/TestDynamicFlyoutMenuHeader.zip)
