### ISSUE TITLE
[.NET 9 Hot Restart] - Cant build and debug MAUI application on iOS

### ISSUE THREAD

**Issue by workmail20** [dotnet/maui#20697]
### Description

I cant run Debug and Release version on last .NET 9 + MAUI 9.
On MAUI 8.0.10 (Nightly) - all was ok

Below I attached error

![Снимок экрана 2024-02-19 140420](https://github.com/dotnet/maui/assets/74146677/7b89cf35-0182-45e6-8ff5-c5d5390b9954)

`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "DetectHotRestartSigningIdentity" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'Xamarin.iOS.Windows.HotRestartClient' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.Tracer, Version=2.0.0.0, Culture=neutral, PublicKeyToken=173d89ffae9ce988' or one of its dependencies. Не удается найти указанный файл.
   at Xamarin.iOS.Windows.HotRestartClient..cctor()
   --- End of inner exception stack trace ---
   at Xamarin.iOS.Windows.HotRestartClient..ctor()
   at Xamarin.iOS.HotRestart.Tasks.DetectHotRestartSigningIdentity.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/Tasks/DetectHotRestartSigningIdentity.cs:line 73
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ABC24	C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.2.9088-net9-p1\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets	36	
`
![Знімок екрана 2024-02-19 140050](https://github.com/dotnet/maui/assets/74146677/47fcdf5c-2976-49d4-8848-4c29323233bf)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

iOS

### Affected platform versions

IOS 16

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
As far as I know, Hot Restart is built on top of a prebuilt .NET 8.0 application, and depends on that toolchain for building and deploying it. .NET 9 is not supported yet, and as far as I know it's not supported yet for MAUI apps in general within VS and its tooling. 

Regardless, it's tooling that's maintained by Visual Studio, so asking there should help move this forward.

**Comment by workmail20** [comment]
I turned it off - Hot Reload.
And now I can debug only on remote iOS simulator, because
I dont see my local iPhone device
![Снимок экрана 2024-02-19 160403](https://github.com/dotnet/maui/assets/74146677/b62249cb-9131-4721-8295-5f30aa22b8e6)

**Comment by drasticactions** [comment]
Because you need to connect the iPhone to the Mac, otherwise Pair To Mac won't see it.

**Comment by workmail20** [comment]
> Because you need to connect the iPhone to the Mac, otherwise Pair To Mac won't see it.

If I connect iPhone, and run through Remote Device, I see this error:
![Снимок экрана 2024-02-19 164610](https://github.com/dotnet/maui/assets/74146677/47b03e6f-afc9-422f-b79f-d60bee347b2f)

If i run on remote iOS simulator, app running well, but when breakpoint is called, app crashed and debug session stopped
![Снимок экрана 2024-02-19 170553](https://github.com/dotnet/maui/assets/74146677/5e803682-5c3b-4798-bd15-1e71607c1df0)

**Comment by drasticactions** [comment]
That would be an issue for the Visual Studio side to look at, that's related to the underlying tooling for debugging and deploying iOS apps and it's independent of the MAUI UI Framework (As in, you would most likely have this issue deploying any iOS app through it regardless of it is uses MAUI or not), and it's something they can look at and help with.

**Comment by jfversluis** [comment]
Assuming this has been reported in the right place by now and/or fixed. Thanks!
