### ISSUE TITLE
Xaml Standardization[Enhancement]  

### ISSUE THREAD

**Issue by mytahir** [dotnet/maui#207]
# [Xaml Standardization] 

As I am making my transition from WPF to Xamarin.Forms, but is there any Xaml Standardization where what I know from WPF is the same thing in Xamarin.Forms, but I found out the differences in Xaml like in <StackPanel /> and other tags, why can't it be one Xaml to all Frameworks where one Xaml experience is enough to all Xaml ecosystem.
So only one Documentation, no need to learn something new.

**Comment by Rand-Random** [comment]
There is this
https://github.com/microsoft/xaml-standard

Though it seems to be born dead, and never really made anything useful.

**Comment by davidortinau** [comment]
@mytahir standardizing XAML on features is one conversation, and standardizing the controls and layouts themselves is another. This has been discussed at length in #43 and #161 .
