### ISSUE TITLE
ContentPage.ToolbarItems is not currently being Garbage Collected

### ISSUE THREAD

**Issue by marco-skizza** [dotnet/maui#20703]
### Description

Hi

With the following Xaml on a `ContentPage`, the page doesn't get garbage collected when navigating back:
```xml
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Test" />
    </ContentPage.ToolbarItems>
```

### Steps to Reproduce

- Put the content on a page you can navigate to
- When navigating back, the Deconstructor of the page is never called

### Link to public reproduction project repository

Please tell me if you need one

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iPadOS 17.3.1 on iPad mini 6

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by williambohrmann3** [comment]
Our GeoView control and our MAUI iOS sample viewer app is being aversely impacted by this issue. Merely navigating to/from page w/ toolbar item and GeoView causes the app to crash. No app crash happens when I remove the line of code for adding a toolbar item. Here is a reproducer [GitHub repository](https://github.com/williambohrmann3/GeoViewAppCrashMaui) to demonstrate the crash. I am only experiencing this on iOS.

**Comment by williambohrmann3** [comment]
Is there any workaround for this on iOS? Merely removing the toolbar items prevents our app from crashing, but we require the toolbar items in our app. Manually calling the garbage collector or clearing the toolbar items upon navigating away from page fails to prevent an app crash. Not a performance expert by any means, but it seems like there is a memory leak with native memory.

**Comment by marco-skizza** [comment]
I replaced the toolbar items with buttons in the content area.
Not very elegant - but does the job for now.

But there are further memory leaks in .NET MAUI that currently prevent me from releasing my app.
I hope these get addressed soon...

**Comment by dotMorten** [comment]
This issue is a bit of a blocker for us.

**Comment by vecalion** [comment]
Experiencing the same issue in 8.0.21.

**Comment by vecalion** [comment]
@Eilon, I kindly suggest adding a memory-leak 💦 label as well.

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

I tested a basic contentpage with a toolbar item and was able to reproduce on 8.0.7 but was not able to reproduce on the nightly. 

If you can still reproduce, can you attach a repro.

**Comment by marco-skizza** [comment]
Many Thanks @PureWeen!

I tried with build `8.0.60-ci.net8.24302.1` and it indeed seems to be fixed there.
So I'll close the issue.

**Comment by nevse** [comment]
I've just tested 8.0.60-ci.net8.24302.1 version and found out that fix doesn't work for toolbar item with click handler
```xaml
  <ContentPage.ToolbarItems>
        <ToolbarItem Text="Test" Clicked="OnTestClicked" />
    </ContentPage.ToolbarItems>
```

**Comment by PureWeen** [comment]
> I've just tested 8.0.60-ci.net8.24302.1 version and found out that fix doesn't work for toolbar item with click handler
> 
> ```
>   <ContentPage.ToolbarItems>
>         <ToolbarItem Text="Test" Clicked="OnTestClicked" />
>     </ContentPage.ToolbarItems>
> ```

can you create a new issue?

**Comment by nevse** [comment]
I created https://github.com/dotnet/maui/issues/22814 bug report
