### ISSUE TITLE
[Bug] Unhandled exception at 0x00007FFDA1822234 (ntdll.dll)

### ISSUE THREAD

**Issue by qt1** [dotnet/maui#2070]
### Description

Unhadled exception when closing application in windows UI

### Steps to Reproduce

1. install and run HelloMauiPreview.WinUI
2. Application opens and counts
3. error on application close:

Unhandled exception at 0x00007FFDA1822234 (ntdll.dll) in HelloMauiPreview.WinUI.exe: 0xC000000D: An invalid parameter was passed to a service or function.

- Version with issue:

PS C:\w\samples\maui\HelloMauiPreview> dotnet --version
6.0.100-preview.6.21355.2

**Comment by mattleibow** [comment]
There has been quite a bit of work around the Windows bits, and I think because we not only removed the second project and are now using a different set of tooling, this should be fixed in p9 or the upcoming p10.
