### ISSUE TITLE
Maui iOS WebView - MauiWKWebView DidFinishNavigation not called.

### ISSUE THREAD

**Issue by RobFrancisAu** [dotnet/maui#20713]
### Description

Hey all,

It appears that `DidFinishNavigation` is not being called in `MauiWKWebView`.

https://github.com/dotnet/maui/blob/7773f909f93dabef282e0f6228081e3f04eafe2a/src/Core/src/Platform/iOS/MauiWKWebView.cs#L79

From what I can gather the `NavigationDelegate` is set in the constructor of `MauiWKWebView` as a `MauiWebViewNavigationDelegate`.

https://github.com/dotnet/maui/blob/7773f909f93dabef282e0f6228081e3f04eafe2a/src/Core/src/Platform/iOS/MauiWKWebView.cs#L41

This `MauiWebViewNavigationDelegate` is what actually contains the implementation for `DidFinishNavigation`

https://github.com/dotnet/maui/blob/7773f909f93dabef282e0f6228081e3f04eafe2a/src/Core/src/Platform/iOS/MauiWebViewNavigationDelegate.cs#L25

As a result of this, when navigating in a webview on iOS the line `await handler.ProcessNavigatedAsync(url);` in the MauiWKWebView

https://github.com/dotnet/maui/blob/7773f909f93dabef282e0f6228081e3f04eafe2a/src/Core/src/Platform/iOS/MauiWKWebView.cs#L88

is not called. This is responsible for syncing cookies.
 https://github.com/dotnet/maui/blob/7773f909f93dabef282e0f6228081e3f04eafe2a/src/Core/src/Handlers/WebView/WebViewHandler.iOS.cs#L134.

### Steps to Reproduce

1. Put a breakpoint on https://github.com/dotnet/maui/blob/7773f909f93dabef282e0f6228081e3f04eafe2a/src/Core/src/Platform/iOS/MauiWKWebView.cs#L82
2. Put a breakpoint on 
https://github.com/dotnet/maui/blob/7773f909f93dabef282e0f6228081e3f04eafe2a/src/Core/src/Platform/iOS/MauiWebViewNavigationDelegate.cs#L28

When navigating inside a webview on iOS I was unable to hit breakpoint 1. Breakpoint 2 hit each time.

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by drasticactions** [comment]
<img width="1134" alt="スクリーンショット 2024-02-20 20 47 25" src="https://github.com/dotnet/maui/assets/898335/ba00c964-ee4d-4e5c-895f-704a75848ba6">

<img width="502" alt="スクリーンショット 2024-02-20 20 49 10" src="https://github.com/dotnet/maui/assets/898335/ab4da875-d39d-4250-b003-958ec33eb930">

Going through the history here, if I understand it right, I believe the Navigation Delegate was added a week or so after the cookie code was added. So that code would have been working for about a week in Main.
