### ISSUE TITLE
[Bug]  Project not selected to build for this solution configuration 

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/maui#2072]
Project not selected to build for this solution configuration 
Even though the project is set to android and the correct emulator is shown.

Repo https://github.com/davidbuckleyni/ConciergeIssueFORMS
1. Update Visual Studio
2. Windows 10 IS Updated
3. Run Maui Check Completes success
4. Have preview 7 installed

Attempt to run to an andriod device it complains about the open sdk is not installed install acording to 
https://docs.microsoft.com/en-gb/xamarin/android/get-started/installation/openjdk
With the latest version.

5. Create File New  Maui Preview 7 Project Template
6. Select Android Emulator 
7. Have the mobile project as start-up
8. 
------ Skipped Deploy: Project: Concierge, Configuration: Debug Any CPU ------
Project not selected to build for this solution configuration 
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========

Proving that the andriod app is choosen as startup project.

![image](https://user-images.githubusercontent.com/5619229/129272365-60b1d8e5-0517-4016-951c-6802ca837283.png)

Emulator correctly selected

![image](https://user-images.githubusercontent.com/5619229/129272569-8669dde6-4cb8-44a0-8b93-0e8e88e7a848.png)

Visual Studio Info 

Microsoft Visual Studio Community 2022 Preview
Version 17.0.0 Preview 3.0
VisualStudio.17.Preview/17.0.0-pre.3.0+31606.5
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00476-70000-00000-AA316
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.0.414.6609
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.414.6609
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.414.6609
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.414.6609
Azure Functions and Web Jobs Tools

C# Tools   4.0.0-3.21403.23+d51d1a7338e32d3a3cd1e5452665964ee8ec15df
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.0.6 (1ebf2f7)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2138002+9e71a625d64fa38b323fa6ac52154e6b1bde703d
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62108.04180
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.0730.2001
TypeScript Tools for Microsoft Visual Studio

UnoPlatformPackage Extension   1.0
UnoPlatformPackage Visual Studio Extension Detailed Info

Visual Basic Tools   4.0.0-3.21403.23+d51d1a7338e32d3a3cd1e5452665964ee8ec15df
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21370.1+9b96c1bde17e9af532ae34eacbfc12d1628183d7
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.145 (main@bdc8369)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.58 (remotes/origin/d17-0@927d548a1)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.3 (a84fb28)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.4.99.70 (main/7e1558c)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@4fb7c14
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@623332d

Xamarin.iOS and Xamarin.Mac SDK   14.99.0.294 (13b1b3c45)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
[LogsFailedBuild.zip](https://github.com/dotnet/maui/files/6978669/LogsFailedBuild.zip)

**Comment by psandgren** [comment]
I also have this for a new MAUI Blazor app.
Win10 21H1
VS 2022 Preview 3
MAUI Preview 7
dotnet 6 Preview 7

I can manually deploy and run in, but the debug doesnt start.
```
1>Done building project "MAUI Blazor.csproj".
2>------ Skipped Deploy: Project: MAUI Blazor, Configuration: Debug Any CPU ------
2>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========
```

**Comment by nahim-alhyane** [comment]
same here...

1>------ Skipped Deploy: Project: MauiTestApp, Configuration: Debug Any CPU ------
1>Project not selected to build for this solution configuration 
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========

**Comment by psandgren** [comment]
This is a template problem. It can be worked around by going in to solution > Configuration Manager, and check the box for deploy.

**Comment by jwooley** [comment]
Thanks @psandgren configuration manager fixed it for me as well.

**Comment by Eilon** [comment]
Hi everyone, is this problem always specific to trying to use Android? Or does this happen for other platforms too?

**Comment by psandgren** [comment]
I only tried with the android emulator.

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
