### ISSUE TITLE
netframe 4.8.1 funktionirt nicht .

### ISSUE THREAD

**Issue by monschischi1927** [dotnet/maui#20720]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Hey @monschischi1927 thanks for the report and wanting to try out .NET MAUI! 

Unfortunately, this issue does not have enough detail to understand what is going on. Please help us understand better what you are looking at and what you want to do so we can see if we can help out! Thanks!

**Comment by janseris** [comment]
Btw on the page https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install

The button "Provide feedback button" inside "I ran into an issue" dialog does nothing.
