### ISSUE TITLE
[Bug] [iOS] Typeload exception breaks iOS debugger

### ISSUE THREAD

**Issue by 3DSX** [dotnet/maui#2073]
![Screen Shot 2021-08-12 at 11 51 52 PM](https://user-images.githubusercontent.com/32218025/129274932-0eeafc35-ec78-4519-b645-3f3419b93a01.png)

I'm launching this demo on the debugger, and it fails with that error, which I didn't have the last time I worked with the iOS debugger after installing preview 3. I can't find a way to get rid of this misleading exception because everything works well on no-debugging mode or when the debugger has exited.

```
2021-08-12 23:50:50.562266+0200 mauitest[68883:2668356] warning: Can't find custom attr constructor image: data-0x7fbd2f67d000 mtoken: 0x0a000006 due to: Could not resolve type with token 01000008 from typeref (expected class 'System.Drawing.BitmapSuffixInSatelliteAssemblyAttribute' in assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Drawing.BitmapSuffixInSatelliteAssemblyAttribute member:(null)
**System.TypeLoadException:** 'Could not resolve type with token 01000008 from typeref (expected class 'System.Drawing.BitmapSuffixInSatelliteAssemblyAttribute' in assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')'
```

Using VS2022 Preview 3 and XCode 13.0 with Maui Blazor.

**Comment by 3DSX** [comment]
Solved this issue by restarting my Windows and macOS, kinda weird, but will reopen this if it comes back.

**Comment by netojoa** [comment]
I had the same issue with Android emulator. Uninstalling the app from the emulator and deploying it again from Visual Studio, fixed the issue for me.

**Comment by Orgbrat** [comment]
I am having same issue with Android emulator too. Uninstalling app from emulator and re-deploying does not work either. But you can build and deploy with Release configuration from VS 2022  Preview 3.1 and it deploys and runs fine on the emulator.  I have tried restarting the Windows machine and anything else I could think of with no luck. Should I open a new issue as I believe this is a debugger issue not just a platform issue?

**Comment by Orgbrat** [comment]
Thank you @TomBruyneel  that workaround does work. So I guess this issue is a Hot Reload issue.

**Comment by TomBruyneel** [comment]
Seems like it, this issue should be reopened with the correct title

**Comment by Orgbrat** [comment]
I agree. I tweeted this to  @maddyleger1 and  @davidortinau  so they would be aware of what is going on.

**Comment by mterhorst** [comment]
Same problem here on my MAUI android app.
Disabling the XAML Hot Reload works, but error comes back once re enabled.

In my case the fix is to delete the `obj`, `debug` and `.vs` folders.

I filled a bug report to VS bug report site here https://developercommunity.visualstudio.com/t/XAML-Hot-Reload-SystemTypeLoadExcepti/1513744.

**Comment by MichaelLant** [comment]
Sam problem here, both iOS and Android, hardware device or emulator. Disabling XAML Hot Reload fixes the problem.
