### ISSUE TITLE
Compiled Xaml Sometimes Ignores Errors in ContentPage.ToolbarItems

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#20735]
### Description

As an example, a XAML page containing this:
```
     ...
     x:DataType="local:TestVm"
     BindingContext="{local:TestVm}"
     ...
    <ContentPage.ToolbarItems>
        <ToolbarItem IconImageSource="{Binding Missing1}"/>
        <ToolbarItem Command="{Binding Missing2}"/>
    </ContentPage.ToolbarItems>
    <Label Text="{Binding TestString}"/>
```
Compiles cleanly, despite the undefined bound items `Missing1` and `Missing2`. Delete one of the `ToolbarItem` objects and the compile will fail parsing the other one.

This does not affect the `Label` object, if you try to bind it to a nonexistent entity the XAML will fail to compile.

### Steps to Reproduce

1. Clone the repository
2. Build the project, the XAML will compile
3. Delete one of the `ToolbarItem `objects
4. Build the project, the XAML compile will fail. with some error like:
                ` XamlC error XFC0045: Binding: Property "Missing1" not found on "XamlCompile.TestVm"`

### Link to public reproduction project repository

https://github.com/david-maw/XamlCompile.git

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by simonrozsival** [comment]
@StephaneDelcroix this was fixed in #20742 (verified with a local maui build)
