### ISSUE TITLE
CollectionView SelectableItemsViewAdapter System.ArgumentOutOfRangeException: ArgumentOutOfRange_IndexMustBeLess Arg_ParamName_Name, index

### ISSUE THREAD

**Issue by Toomas75** [dotnet/maui#20764]
### Description

System.ArgumentOutOfRangeException
System.ArgumentOutOfRangeException: ArgumentOutOfRange_IndexMustBeLess Arg_ParamName_Name, index

crash log
```
System.Collections.Generic.List`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Item(Int32 )
System.Collections.Generic.List`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].System.Collections.IList.get_Item(Int32 )
Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.ElementAt(Int32 )
Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.GetItem(Int32 )
Microsoft.Maui.Controls.Handlers.Items.UngroupedItemsSource.GetItem(Int32 )
Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].UpdateMauiSelection(Int32 )
Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SelectableClicked(Object sender, Int32 adapterPosition)
Microsoft.Maui.Controls.Handlers.Items.SelectableViewHolder.OnViewHolderClicked(Int32 )
Microsoft.Maui.Controls.Handlers.Items.SelectableViewHolder.OnClick(View )
Android.Views.View.IOnClickListenerInvoker.n_OnClick_Landroid_view_View_(IntPtr jnienv, IntPtr native__this, IntPtr native_v)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
```

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.6 SR1

### Affected platforms

Android

### Affected platform versions

Android 8.1

### Relevant log output

```shell
similar https://github.com/xamarin/Xamarin.Forms/issues/7243
```

**Comment by Toomas75** [comment]
No repro. Happens occasionally.

**Comment by PureWeen** [comment]
@Toomas75 can you provide the `XAML` of your CollectionView or try to reproduce? 

It'd be helpful to see your structure.

**Comment by Toomas75** [comment]
> @Toomas75 can you provide the `XAML` of your CollectionView or try to reproduce?
> 
> It'd be helpful to see your structure.

`It's some race condition. Never happens while debugging.

<CollectionView Grid.Row="2" x:Name="lstPickinglists" SelectionMode="Single" Margin="1,-1,1,1"  
                    ItemTemplate="{Binding ListItemDatatemplate}" SelectionChanged="LstPickinglists_SelectionChanged"
                    ItemsSource="{Binding Pickinglists}"
                    SelectedItem="{Binding CurrentPickinglist,Mode=TwoWay}" >
    </CollectionView>

 private void LstPickinglists_SelectionChanged(object sender, SelectionChangedEventArgs e)
 {
     if (DesignTimeHelper.DesignModeOn) return;
     if (e.CurrentSelection.Count == 0) return;
     var items = (IList)lstPickinglists.ItemsSource;

     this.lblCurrentSelectionInfo.Text = $"{items?.IndexOf(e.CurrentSelection[0]) + 1 ?? 0}/{items?.Count ?? 0}";
     if( lstPickinglists.IsLoaded) this.lstPickinglists.ScrollTo(e.CurrentSelection[0], null, ScrollToPosition.MakeVisible, false);
 }`

**Comment by Toomas75** [comment]
<CollectionView Grid.Row="2" x:Name="lstPickinglists" SelectionMode="Single" Margin="1,-1,1,1"  
                    ItemTemplate="{Binding ListItemDatatemplate}" SelectionChanged="LstPickinglists_SelectionChanged"
                    ItemsSource="{Binding Pickinglists}"
                    SelectedItem="{Binding CurrentPickinglist,Mode=TwoWay}" >
    </CollectionView>

 private void LstPickinglists_SelectionChanged(object sender, SelectionChangedEventArgs e)
 {
     if (DesignTimeHelper.DesignModeOn) return;
     if (e.CurrentSelection.Count == 0) return;
     var items = (IList)lstPickinglists.ItemsSource;

     this.lblCurrentSelectionInfo.Text = $"{items?.IndexOf(e.CurrentSelection[0]) + 1 ?? 0}/{items?.Count ?? 0}";
     if( lstPickinglists.IsLoaded) this.lstPickinglists.ScrollTo(e.CurrentSelection[0], null, ScrollToPosition.MakeVisible, false);
 }

**Comment by Toomas75** [comment]
<CollectionView Grid.Row="2" x:Name="lstPickinglists" SelectionMode="Single" Margin="1,-1,1,1"  
                    ItemTemplate="{Binding ListItemDatatemplate}" SelectionChanged="LstPickinglists_SelectionChanged"
                    ItemsSource="{Binding Pickinglists}"
                    SelectedItem="{Binding CurrentPickinglist,Mode=TwoWay}" >
    </CollectionView>

**Comment by Toomas75** [comment]
![image](https://github.com/dotnet/maui/assets/160151104/485adf26-eeec-408c-8086-1f8f6a598547)
![image](https://github.com/dotnet/maui/assets/160151104/5872a43a-2c43-4d16-b5f8-ec2741b4f467)

**Comment by Toomas75** [comment]
@PureWeen somehow unable to post this xaml & code in text.
