### ISSUE TITLE
Navigation menu switching is very slow in Windows

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/maui#20762]
### Description

Navigation menu switching is very slow in Winodws

https://github.com/dotnet/maui/assets/30250585/00226f1c-0177-416c-b4f5-d2bc32796110

![image](https://github.com/dotnet/maui/assets/30250585/a270a943-2bbb-40fa-a76d-d3c2af936725)
Maui8.0.7+VS17.9.1

### Steps to Reproduce

![image](https://github.com/dotnet/maui/assets/30250585/312b1351-bba5-4339-bcc8-8b6119763ce0)

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Win11 VS17.9.1 Maui SR2

**Comment by HuaFangYun** [comment]
[MauiApp1.zip](https://github.com/dotnet/maui/files/14371122/MauiApp1.zip)
Perhaps it is the problem of the animation, after the mouse click, will delay the time mark to display to the current position.

**Comment by drasticactions** [comment]
The animation is from the WinUI 3 [NavigationView](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.navigationview?view=windows-app-sdk-1.4) and/or [Pivot](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.pivot?view=windows-app-sdk-1.4) that the TabBar uses. It's not controlled by MAUI directly. You would see similar animations from the NavigationView when docked on the left size and going between items.

You could modify the base WinUI XAML themes for both to remove it, but IMO this isn't a MAUI issue, it's a preference choice for how the native control renders, and you can change that however you want by changing it within its project/platform folder.

Now if you had performance issues _rendering_ the page (as in, clicking on the tab, it staying static for a few seconds, then showing and rendering the page), then that could be a perf issue. A lot of users I see front load rendering their page in the constructor and block the UI Thread, which would then prevent the page from rendering and that can cause studders and pauses when switching pages. That's not the case here though.

**Comment by PureWeen** [comment]
@HuaFangYun if you update to the latest WinAppSDK is it the same?

You should be able to update to it via the NUGET Manager. 
This might be related to how we apply color resources, but I'd be curious to test it in a WinUI Platform app. 

Is it different in light mode vs dark mode?
