### ISSUE TITLE
FlyoutIsPresented is not working on Android

### ISSUE THREAD

**Issue by bhuwancb99** [dotnet/maui#20779]
### Description

In .NET MAUI, within the AppShell, when 'Shell.NavBarIsVisible' is set to 'False', and a button is clicked on any page, triggering the code 'Shell.Current.FlyoutIsPresented = !Shell.Current.FlyoutIsPresented;' in the code-behind, it does not function as expected on Android. However, it works as intended on iOS. Interestingly, the same implementation in the previous version for Xamarin.Forms was successful. Note: Upon clicking the button, the Hamburger menu does not open. However, after clicking the button for the first time, subsequently clicking any of the tab bar icons does open the menu.

### Steps to Reproduce

i am downloaded code for this URL -https://github.com/dotnet/maui-samples/tree/main/8.0/Fundamentals/Shell

and added one line in AppShell-'Shell.NavBarIsVisible="False"' added button in CatsPage.xaml file- <StackLayout Padding="10,20,10,0"> <Button Text="Flyout Enable" Clicked="Button_Clicked"/> <CollectionView Margin="20" ItemsSource="{x:Static data:CatData.Cats}" ItemTemplate="{StaticResource AnimalTemplate}" SelectionMode="Single" SelectionChanged="OnCollectionViewSelectionChanged" /> </StackLayout>

button event
private void Button_Clicked(object sender, EventArgs e) { Shell.Current.FlyoutIsPresented = !Shell.Current.FlyoutIsPresented; }
![image (1)](https://github.com/dotnet/maui/assets/65246844/5987b17f-5d5c-4c24-9a76-87511b52036a)
![image](https://github.com/dotnet/maui/assets/65246844/d2c6f508-a728-4551-be31-a1a0cf78e6c6)

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/8.0/Fundamentals/Shell

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by bhuwancb99** [comment]
hi @PureWeen - i can't understand your question. can you please explain more.

**Comment by PureWeen** [comment]
@bhuwancb99 I'm pretty sure this will be fixed by SR3

You can test if it's going to be fixed by updating to our nightly nugets as is described here
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by bhuwancb99** [comment]
@PureWeen  thanks now it's working after update.
