### ISSUE TITLE
Mac Mini - Monterey (12.7.3)

### ISSUE THREAD

**Issue by acornsoft** [dotnet/maui#20780]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: macos

Install XCODE 15, can this work against a Monterey based MacOS?

Realize I am using an old Mac, but this is all I have at the moment. Am I able to develop with the toolkit using this machine or I can only use a XCOCDE 15 for development.  This is a MAC MINI, Intel 

mintika:~ $ uname -a
Darwin mintika.local 21.6.0 Darwin Kernel Version 21.6.0: Sun Dec 17 22:55:27 PST 2023; root:xnu-8020.240.18.706.2~1/RELEASE_X86_64 x86_64

**Comment by acornsoft** [comment]
Here are the specifications to my Mac Mini (yes it is old), https://support.apple.com/kb/SP659?locale=en_US, which is a mac mini (Late 2012). Is there a way to develop with .NET MAUI using .NET 7.0 as opposed to .NET 8.0?

**Comment by PureWeen** [comment]
@acornsoft if you set your target platforms to net7 does that fix?

or if you just install the net7 .net sdk and install the maui workloads for that?

**Comment by acornsoft** [comment]
From my limited exposure, it would appear that the https://github.com/dotnet/maui-samples will require me to use .NET 8. Which I am unable to do at this time. Any help to configure for .NET 7 would be great, but will close this comment.
