### ISSUE TITLE
Cannot create an IOS archive 'TestApp'. Process cannot be executed on XMA server. The "Copy" task failed unexpectedly.

### ISSUE THREAD

**Issue by augustusdevree** [dotnet/maui#20786]
### Description

Creating a basic .NET 7 (might happen also with .NET 8) .NET MAUI App, trying to publish to a paired Mac I get the following error;
Cannot create an IOS archive 'TestApp'. Process cannot be executed on XMA server.
The "Copy" task failed unexpectedly.

### Steps to Reproduce

1. Create a new .NET MAUI App (I choose .NET 7)
2. Publish an iOS app for App Store distribution following the following directions; 
    https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-app-store?view=net-maui-8.0&tabs=vs
Results, for me, in a "Cannot create an IOS archive 'TestApp'. Process cannot be executed on XMA server." error.
I have reinitialized the Mac, deleted Visual Studio 2022 Preview, reinstalled, rebooted everything multiple times between retries but I always get this error and don't know where to look in anymore.

### Link to public reproduction project repository

https://github.com/augustusdevree/TestApp

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

### Relevant log output

```shell
Cannot create an IOS archive 'TestApp'. Process cannot be executed on XMA server.
The "Copy" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Messaging.Build.Client.TaskRunner.FixReferencedItems(ITaskItem[] items) in D:\a\_work\1\s\src\MSBuild\Xamarin.Messaging.Build.Client\TaskRunner.cs:line 237
   at Microsoft.Build.Tasks.Copy.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Copy.cs:line 12
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Failed to create App archive 'TestApp'.
```

**Comment by PureWeen** [comment]
@rolfbjarne  thoughts?

**Comment by rolfbjarne** [comment]
This is a known issue. We've already fixed it, and while the fix hasn't been released for .NET 7 yet (it will be included in the next service release), the current .NET 8 release has the fix already.

Ref: https://github.com/xamarin/xamarin-macios/pull/19871

**Comment by augustusdevree** [comment]
@rolfbjarne Thanks for your reply, I confirm it works with .NET 8. Do you have a timeframe when the fix will be released for .NET 7?

**Comment by augustusdevree** [comment]
@rolfbjarne Isn't there any workaround at the moment (roll back to some previous release, visual studio, quick hack, whatever, upgrading to .NET 8 is not an option at the moment)? 
I cannot immagine that nobody can pulish .NET 7 Apps to the Apple Store untill the next service release.

**Comment by augustusdevree** [comment]
@rolfbjarne Also, I managed to publish to the Apple Store to TestFlight the App until 12 days ago.
What happened? Yes I changed the Application ID/Bundle ID to have it upgrade an outdated App.

**Comment by rolfbjarne** [comment]
@augustusdevree can you try publishing from the command line (https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-cli?view=net-maui-8.0) to see if that works better? If not, add `-bl:msbuild.binlog` to the command you execute, and then attach the resulting msbuild.binlog file here.
