### ISSUE TITLE
[Bug] [Android] Modal page shows behind android navigation bar after navigating to another modal page and rotating screen on tablet only

### ISSUE THREAD

**Issue by andyx48** [dotnet/maui#20798]
### Description

When navigating from a modal page to another modal page in portrait mode, and then rotating the device to landscape, the first modal page shows under the Android system navigation bar.

Elements on the first modal can also still be tapped.

We were able to replicate this behavior on an android tablet (Samsung Galaxy Tab S9).

https://github.com/dotnet/maui/assets/36721479/d197d191-8cd9-423f-ab72-0d286f019a0d

### Steps to Reproduce

Attached a reproduction project, open the project and:
1. While on portrait, press navigate to modal button
2. On the second screen press navigate to modal button again.
3. Rotate the screen to landscape mode

### Link to public reproduction project repository

https://github.com/andyx48/NavigationBug

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2(maui version 8.0.3/8.0.10/8.0.0-rc.2.9511). Cannot repro this issue.
