### ISSUE TITLE
[WinUI] Add tests for loading fonts when unpackaged

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#20791]
### Description

Once we are ingesting a version of Win2D that can handle unpackaged fonts then we will add tests. 

We did some exploratory work against the Win2D fix and found that we needed to add this code https://github.com/dotnet/maui/pull/20790 .

This will let people update manually to Win2D before we're actually depending on it ourselves.

**Comment by mattleibow** [comment]
we could potentially merge this for now and add tests in the https://github.com/dotnet/maui/blob/main/src/Controls/samples/Controls.Sample.UITests/Concepts/ImageLoadingGalleryPage.cs and https://github.com/dotnet/maui/blob/main/src/Controls/tests/UITests/Tests/Concepts/ImageLoadingGalleryTests.cs files. I currently just added the tests for the file-based images, not the generated ones.

**Comment by Foda** [comment]
Test added in https://github.com/dotnet/maui/pull/21212
