### ISSUE TITLE
[Android] ImageButton Border does not fit to CornerRadius

### ISSUE THREAD

**Issue by dlange-h3ko** [dotnet/maui#20801]
### Description

When I am using an **ImageButton** which is having a **CornerRadius**, the **Border** does not fit to the **CornerRadius** as it is for normal Buttons. 
You can also see, that the BorderWidth looks unequal even I used the same for button and ImageButton

Android: 
![image](https://github.com/dotnet/maui/assets/60385309/1c2a58f0-7bf3-4d80-a3a8-7defbdd670ff)

iOS works fine: 
![image](https://github.com/dotnet/maui/assets/60385309/6c25b62e-b092-4b35-a6b9-3fbf766a7877)

### Steps to Reproduce

1. Created a new MAUI project.
2. Add an ImageButton, set Border, BorderWidth and CornerRadius.

### Link to public reproduction project repository

https://github.com/dlange-h3ko/Maui-ImageButtonCornerRadiusBorderIssue/tree/main

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

Android

### Affected platform versions

Android 13, Android 14

### Did you find any workaround?

Only workaround currently is to use an extra **Border** component/control around the ImageView

**Comment by ninachen03** [comment]
Verified on 17.10.0 Preview 1.0 with android platform. It is still repro.
![border1](https://github.com/dotnet/maui/assets/128687574/ca89c5c0-8b0f-48ab-809f-b086eeebf4a1)

**Comment by mattleibow** [comment]
I wonder if this PR that fixed a lot of Android issues with image button backgrounds will fix this one: https://github.com/dotnet/maui/pull/22298

@dlange-h3ko  are you able to test the nightly builds and see if the issue is fixed?

**Comment by dlange-h3ko** [comment]
@mattleibow I tested it with the Mauiversion 8.0.40, at least there its still reproducible. 
![image](https://github.com/dotnet/maui/assets/60385309/2752fc53-7f09-4e00-9b24-b63b3ba197d3)

I am using a MacBook, so I don't think I can install a new preview version of VisualStudio. Which maui-version should I test? (I could test it then with VS Code)

**Comment by mattleibow** [comment]
It should be in the nightlies https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by dlange-h3ko** [comment]
@mattleibow Ah I missed your info with the nightly. I took the info from the bot by testing the newest public version. Now I tested with the nightly build 8.0.60-ci.net8.24304.1. It looks good now. So it seems to be fixed.

(left iOS and right Android)
![image](https://github.com/dotnet/maui/assets/60385309/2825439f-4f85-4cd6-b3e4-dfba89118642)
