### ISSUE TITLE
App crashes when you clear a group's record in CollectionView

### ISSUE THREAD

**Issue by simon10says** [dotnet/maui#20819]
### Description

I've a grouped collectionview that is binded to `ObservableCollection`. When I `Clear()` a group of its records and re- `Add()`, I get `IndexOutOfBoundsException` as shown below:

![image](https://github.com/dotnet/maui/assets/32186165/d7aa617f-79e8-4b3d-a771-c7a56a7f1ae6)

### Steps to Reproduce

1. Run my repo and you will see the collectionview with 2 groups (Bears and Monkeys)
![1708706991796(1)](https://github.com/dotnet/maui/assets/32186165/c6af192a-d063-4501-b234-10708b51e232)

2. Click on the `Remove Record` toolbar item and the `Asian Black Bear` record will be removed
3. Click on the `Add Record` and you will get the `IndexOutOfBoundsException`

### Link to public reproduction project repository

https://github.com/simon10says/maui-CollectionViewGroupBug

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

Android, I was *not* able test on other platforms

### Did you find any workaround?

This issue seems to be due to `ObservableCollection.Clear()`. In my code I `Remove Record`  via:
```csharp
Animals[0].Clear(); //Animals[0] is the Bears group and this caused the exception when re-add
```
If I use `RemoveAt()` instead, I will not get the exception when I re-add the record
```csharp
while (Animals[0].Count > 0)
{
    Animals[0].RemoveAt(0);
}
```

**Comment by ninachen03** [comment]
I can repro it with 17.10.0 Preview 1.0 on android platform
![image](https://github.com/dotnet/maui/assets/128687574/c49fb24c-7e92-40c8-bce0-c9b250cef8ee)

**Comment by r-work** [comment]
Can repro with maui `8.0.14`

**Comment by malsabi** [comment]
Is there a clear workaround for this and supports animation when collapsing / expanding ?

**Comment by devanathan-vaithiyanathan** [comment]
This issue does not reproduce in the maui version (9.0.12) with VSCode 1.94.2 and Android Pixel 8 API 35 (Android 15).

<video src="https://github.com/user-attachments/assets/ebdfb35b-8665-44d7-9d60-9bdff14df8cf" width="320" height="240" controls></video>
