### ISSUE TITLE
On Android, using the {x:Type ...} TypeExtension in Style.TargetType causes a compiler error for VisualState.Setters within the Style

### ISSUE THREAD

**Issue by bzd3y** [dotnet/maui#20818]
### Description

Using a TypeExtension in Style.TargetType, as used to work in Xamarin, causes a compiler error for Setters inside of VisualState.Setters saying that it can't convert the property name (TextColor, at least, others might not cause the error) to a BindableProperty. It is like it doesn't know to add "Property" to the end of the property name to find the BindableProperty.

### Steps to Reproduce

1. Open the solution in the reproduction repository
2. Try to build the VisualState project targeting Android (iOS seems to build and work fine)
3. Look at error list. There should be a compiler error stating that "TextColor" cannot be converted to a BindableProperty.

### Link to public reproduction project repository

https://github.com/bzd3y/ReproductionProject

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14/API 34

### Did you find any workaround?

Yes, just using the type name instead of the TypeExtension works.

**Comment by jsuarezruiz** [comment]
@StephaneDelcroix Could these changes https://github.com/dotnet/maui/pull/18540 fix the issue?

**Comment by StephaneDelcroix** [comment]
TargetType expect a string literal, not a {x:Type}. But the {}x:Type seems to be supported by the runtime parser, so the XamlC one should accept it as well

**Comment by bzd3y** [comment]
I updated to Maui.Controls 8.0.7 and the problem still exists, although now I get 4 duplicate errors.

I have updated the reproduction project in the GitHub repository at https://github.com/bzd3y/ReproductionProject

@jsuarezruiz That issue definitely looks related, but I'm not sure if that fix also fixes this.

@StephaneDelcroix I agree. Are you saying this is a slightly different issue from the issue in that PR that @jsuarezruiz linked? I assume that PR has been released? If so, then it didn't fix it for my case.

**Comment by bzd3y** [comment]
@simonrozsival @StephaneDelcroix I think there is also an issue with this in `OnPlatform` tags used in `Setter`s regardless of how the target type is set.

Or maybe something else is going on. The following XAML seems to be valid:
```xml
<OnPlatform>
	<On Platform="iOS">
		<Setter Property="BackgroundColor" Value="White" />
	</On>
</OnPlatform>
```

But on build I get an error: 'Cannot convert value "BackgroundColor" to "Microsoft.Maui.Controls.BindableProperty".'

If I invert the hierarchy like:

```xml
<Setter Property="BackgroundColor">
	<OnPlatform>
		<On Platform="iOS" Value="White" />
	</OnPlatform>
</Setter>
```

It works, however the "White" value isn't recognized as a color and doesn't get the color swatch and Intellisense. And that may be a different issue, but that is what made me think that the first method should have been acceptable.

So I guess I'm asking if this pull request would fix the first issue with the compiler error?

**Comment by simonrozsival** [comment]
@bzd3y I think you need to add `x:TypeArguments` to `<OnPlatform>` to make it work in this case:
```xml
<Setter Property="BackgroundColor">
	<OnPlatform x:TypeArguments="Color">
		<On Platform="Android" Value="White" />
	</OnPlatform>
</Setter>
```

Alternatively, you can try:
```xml
<Setter Property="BackgroundColor" Value="{OnPlatform Android=White}" />
```

If these don't help (I'm not able to run it at the moment and verify that this code works), please open a new issue so we can look into it separately.
