### ISSUE TITLE
[BUG] Back button is not visible on the navigation bar in light mode

### ISSUE THREAD

**Issue by RsZoli** [dotnet/maui#20811]
### Description

After navigating from a page, the back button is not visible (or presumably just white) if the device is in light mode!
The bug is present on Android and iOS platforms as well, but the navigation itself is working!

![IMG_0006](https://github.com/dotnet/maui/assets/28480037/8e2934a0-91f9-4cd3-abe4-61b6f8924ce2)
![IMG_0007](https://github.com/dotnet/maui/assets/28480037/ea818039-f301-4b36-ad46-a663e78c3f44)
![Screenshot_20240223_140518](https://github.com/dotnet/maui/assets/28480037/40e67eba-d7a0-49bf-b229-158cbf3cac7a)
![Screenshot_20240223_140536](https://github.com/dotnet/maui/assets/28480037/f795a5b6-b6ac-42c0-9edc-1aff99383571)

In dark mode, the back button is visible!

### Steps to Reproduce

Create a new .NET MAUI application and navigate from the MainPage.

### Link to public reproduction project repository

https://github.com/RsZoli/GitHubRepros

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 16.2, iOS 17.2.1, Android 13, Android 14

**Comment by GlacierFox** [comment]
Same issue here. Can't change the color of my custom back icon from white to anything else.

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 2.0(8.0.14). Repro on Android 14.0-API34 and iOS 17.2 with below Project:
[GitHubRepros.zip](https://github.com/dotnet/maui/files/14784583/GitHubRepros.zip)

**Comment by japarson** [comment]
This bug has been fixed by https://github.com/dotnet/maui/pull/20152. The fix will be automatically present in newly created MAUI projects. To integrate it into an existing project, replace the existing `Shell.ForegroundColor` property in `Resources\Styles\Styles.xaml` with the following:
```xaml
<Setter Property="Shell.ForegroundColor" Value="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource SecondaryDarkText}}" />
```
