### ISSUE TITLE
[Bug] - Error installing maui workload - arch64-linux-android-ld.exe' because it is being used by another process.

### ISSUE THREAD

**Issue by filipoff2** [dotnet/maui#2082]
### Description
I have installed VS 2022 preview 3

### Steps to Reproduce
1. clean Windows start, NO Visual Studio is open
2. run as admin powershell 
    dotnet workload install maui 

### Expected Behavior
Maui should install

### Actual Behavior
PS C:\WINDOWS\system32> dotnet workload install maui

Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.tvos.
Installing workload manifest microsoft.net.sdk.ios version 15.0.100-preview.7231.
Installing workload manifest microsoft.net.sdk.maccatalyst version 15.0.100-preview.7231.
Installing workload manifest microsoft.net.sdk.macos version 12.0.100-preview.7231.
Installing workload manifest microsoft.net.sdk.tvos version 15.0.100-preview.7231.
Installing pack Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Core.Runtime.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Core.Runtime.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Controls.Ref.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Controls.Ref.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Controls.Runtime.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Essentials.Ref.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Essentials.Ref.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Essentials.Runtime.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Essentials.Runtime.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Dependencies version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Dependencies version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Controls.Sdk version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Controls.Sdk version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Extensions version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Extensions version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Resizetizer.Sdk version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Resizetizer.Sdk version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Templates version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Templates version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Core.Ref.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Core.Ref.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Core.Runtime.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Core.Runtime.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Controls.Ref.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Controls.Ref.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Controls.Runtime.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Controls.Runtime.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Essentials.Ref.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Essentials.Ref.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Essentials.Runtime.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Essentials.Runtime.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Android.Sdk version 30.0.100-preview.7.110...
Workload installation failed, rolling back installed packs...
Installing workload manifest microsoft.net.sdk.ios version 15.0.100-preview.7182.
Installation roll back failed: Failed to install manifest microsoft.net.sdk.ios version 15.0.100-preview.7182: The transaction has aborted..
Rolling back pack Microsoft.Maui.Core.Ref.android installation...
Uninstalling workload pack Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Core.Runtime.android installation...
Uninstalling workload pack Microsoft.Maui.Core.Runtime.android version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Controls.Ref.android installation...
Uninstalling workload pack Microsoft.Maui.Controls.Ref.android version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Controls.Runtime.android installation...
Uninstalling workload pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Essentials.Ref.android installation...
Uninstalling workload pack Microsoft.Maui.Essentials.Ref.android version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Essentials.Runtime.android installation...
Uninstalling workload pack Microsoft.Maui.Essentials.Runtime.android version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.AspNetCore.Components.WebView.Maui installation...
Uninstalling workload pack Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Dependencies installation...
Uninstalling workload pack Microsoft.Maui.Dependencies version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Controls.Sdk installation...
Uninstalling workload pack Microsoft.Maui.Controls.Sdk version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Extensions installation...
Uninstalling workload pack Microsoft.Maui.Extensions version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Resizetizer.Sdk installation...
Uninstalling workload pack Microsoft.Maui.Resizetizer.Sdk version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Templates installation...
Uninstalling workload pack Microsoft.Maui.Templates version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Core.Ref.any installation...
Uninstalling workload pack Microsoft.Maui.Core.Ref.any version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Core.Runtime.any installation...
Uninstalling workload pack Microsoft.Maui.Core.Runtime.any version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Controls.Ref.any installation...
Uninstalling workload pack Microsoft.Maui.Controls.Ref.any version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Controls.Runtime.any installation...
Uninstalling workload pack Microsoft.Maui.Controls.Runtime.any version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Essentials.Ref.any installation...
Uninstalling workload pack Microsoft.Maui.Essentials.Ref.any version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Essentials.Runtime.any installation...
Uninstalling workload pack Microsoft.Maui.Essentials.Runtime.any version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Android.Sdk installation...
Workload installation failed: The process cannot access the file 'C:\Users\xxxx\AppData\Local\Temp\Microsoft.Android.Sdk-30.0.100-preview.7.110-extracted\tools\ndk\aarch64-linux-android-ld.exe' because it is being used by another process.

same with 

PS C:\WINDOWS\system32> dotnet tool update -g Redth.Net.Maui.Check
C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\NuGet.targets(131,5): error : The process cannot access the file 'C:\Users\xxx\.dotnet\tools\.store\.stage\3bcyg4aa.3ar\redth.net.maui.check\0.7.3\tools\netcoreapp3.1\any\shims\win-x64\maui-check.exe' because it is being used by another process. [C:\Users\xxx\AppData\Local\Temp\getab1pf.j41\restore.csproj]
Tool 'redth.net.maui.check' failed to update due to the following:
The tool package could not be restored.
Tool 'redth.net.maui.check' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

### Basic Information

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎3/‎25/‎2021
OS build	19042.985
Experience	Windows Feature Experience Pack 120.2212.2020.0

PS C:\WINDOWS\system32> dotnet sdk check
.NET SDKs:
Version                         Status
-----------------------------------------------------------
2.1.523                         Patch 2.1.525 is available.
3.1.100                         Patch 3.1.118 is available.
3.1.201                         Patch 3.1.202 is available.
5.0.100-preview.1.20155.7       Patch 5.0.104 is available.
5.0.202                         Patch 5.0.206 is available.
6.0.100-preview.7.21379.14      Up to date.

.NET Runtimes:
Name                              Version                       Status
------------------------------------------------------------------------------------------
Microsoft.NETCore.App             2.1.26                        Patch 2.1.29 is available.
Microsoft.AspNetCore.All          2.1.27                        Patch 2.1.29 is available.
Microsoft.AspNetCore.App          2.1.27                        Patch 2.1.29 is available.
Microsoft.NETCore.App             2.1.27                        Patch 2.1.29 is available.
Microsoft.AspNetCore.App          3.1.0                         Patch 3.1.18 is available.
Microsoft.AspNetCore.App          3.1.3                         Patch 3.1.18 is available.
Microsoft.NETCore.App             3.1.3                         Patch 3.1.18 is available.
Microsoft.WindowsDesktop.App      3.1.3                         Patch 3.1.18 is available.
Microsoft.AspNetCore.App          3.1.14                        Patch 3.1.18 is available.
Microsoft.NETCore.App             3.1.14                        Patch 3.1.18 is available.
Microsoft.WindowsDesktop.App      3.1.14                        Patch 3.1.18 is available.
Microsoft.NETCore.App             5.0.0-preview.1.20120.5       Patch 5.0.9 is available.
Microsoft.AspNetCore.App          5.0.0-preview.1.20124.5       Patch 5.0.9 is available.
Microsoft.WindowsDesktop.App      5.0.0-preview.1.20127.5       Patch 5.0.9 is available.
Microsoft.AspNetCore.App          5.0.5                         Patch 5.0.9 is available.
Microsoft.NETCore.App             5.0.5                         Patch 5.0.9 is available.
Microsoft.WindowsDesktop.App      5.0.5                         Patch 5.0.9 is available.
Microsoft.NETCore.App             6.0.0-preview.7.21377.19      Up to date.
Microsoft.AspNetCore.App          6.0.0-preview.7.21378.6       Up to date.
Microsoft.WindowsDesktop.App      6.0.0-preview.7.21378.9       Up to date.

The latest versions of .NET can be installed from https://aka.ms/dotnet-core-download. For more information about .NET lifecycles, see https://aka.ms/dotnet-core-support.

**Comment by rgunawans** [comment]
try clean your %TEMP% folder or `run dotnet workload install maui --temp-dir=c:\temp` , create TEMP folder first before running

**Comment by filipoff2** [comment]
Workload installation failed: The process cannot access the file 'c:\temp\Microsoft.Android.Sdk-30.0.100-preview.7.110-extracted\tools\ndk\aarch64-linux-android-strip.exe' because it is being used by another process.
install

Done:

1. %TEMP% clean done
2. PS C:\WINDOWS\system32> dotnet workload install maui --temp-dir=c:\temp

Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Installing pack Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Core.Runtime.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Core.Runtime.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Controls.Ref.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Controls.Ref.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Controls.Runtime.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Essentials.Ref.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Essentials.Ref.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Essentials.Runtime.android version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Essentials.Runtime.android version 6.0.100-preview.7.1345...
Installing pack Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Dependencies version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Dependencies version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Controls.Sdk version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Controls.Sdk version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Extensions version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Extensions version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Resizetizer.Sdk version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Resizetizer.Sdk version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Templates version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Templates version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Core.Ref.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Core.Ref.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Core.Runtime.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Core.Runtime.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Controls.Ref.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Controls.Ref.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Controls.Runtime.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Controls.Runtime.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Essentials.Ref.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Essentials.Ref.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Maui.Essentials.Runtime.any version 6.0.100-preview.7.1345...
Writing workload pack installation record for Microsoft.Maui.Essentials.Runtime.any version 6.0.100-preview.7.1345...
Installing pack Microsoft.Android.Sdk version 30.0.100-preview.7.110...
Workload installation failed, rolling back installed packs...
Uninstalling workload pack Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Core.Runtime.android version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Controls.Ref.android version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Essentials.Ref.android version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Essentials.Runtime.android version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Dependencies version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Controls.Sdk version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Extensions version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Resizetizer.Sdk version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Templates version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Core.Ref.any version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Core.Runtime.any version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Controls.Ref.any version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Controls.Runtime.any version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Essentials.Ref.any version 6.0.100-preview.7.1345.
Uninstalling workload pack Microsoft.Maui.Essentials.Runtime.any version 6.0.100-preview.7.1345.
Rolling back pack Microsoft.Maui.Core.Ref.android installation...
Rolling back pack Microsoft.Maui.Core.Runtime.android installation...
Rolling back pack Microsoft.Maui.Controls.Ref.android installation...
Rolling back pack Microsoft.Maui.Controls.Runtime.android installation...
Rolling back pack Microsoft.Maui.Essentials.Ref.android installation...
Rolling back pack Microsoft.Maui.Essentials.Runtime.android installation...
Rolling back pack Microsoft.AspNetCore.Components.WebView.Maui installation...
Rolling back pack Microsoft.Maui.Dependencies installation...
Rolling back pack Microsoft.Maui.Controls.Sdk installation...
Rolling back pack Microsoft.Maui.Extensions installation...
Rolling back pack Microsoft.Maui.Resizetizer.Sdk installation...
Rolling back pack Microsoft.Maui.Templates installation...
Rolling back pack Microsoft.Maui.Core.Ref.any installation...
Rolling back pack Microsoft.Maui.Core.Runtime.any installation...
Rolling back pack Microsoft.Maui.Controls.Ref.any installation...
Rolling back pack Microsoft.Maui.Controls.Runtime.any installation...
Rolling back pack Microsoft.Maui.Essentials.Ref.any installation...
Rolling back pack Microsoft.Maui.Essentials.Runtime.any installation...
Rolling back pack Microsoft.Android.Sdk installation...


Workload installation failed: The process cannot access the file 'c:\temp\Microsoft.Android.Sdk-30.0.100-preview.7.110-extracted\tools\ndk\aarch64-linux-android-strip.exe' because it is being used by another process.
install


----------

**BUT  c:/temp is not empty after rollback**

 Directory of c:\temp\dotnet-sdk-advertising-temp

08/16/2021  10:17 AM    <DIR>          .
08/16/2021  10:17 AM    <DIR>          ..
08/16/2021  10:17 AM    <DIR>          microsoft.android.sdk.windows
08/16/2021  10:17 AM    <DIR>          microsoft.aspnetcore.components.webview.maui
08/16/2021  10:17 AM    <DIR>          microsoft.maui.controls.ref.android
08/16/2021  10:17 AM    <DIR>          microsoft.maui.controls.ref.any
08/16/2021  10:17 AM    <DIR>          microsoft.maui.controls.runtime.android
08/16/2021  10:17 AM    <DIR>          microsoft.maui.controls.runtime.any
08/16/2021  10:17 AM    <DIR>          microsoft.maui.controls.sdk
08/16/2021  10:16 AM    <DIR>          microsoft.maui.core.ref.android
08/16/2021  10:17 AM    <DIR>          microsoft.maui.core.ref.any
08/16/2021  10:16 AM    <DIR>          microsoft.maui.core.runtime.android
08/16/2021  10:17 AM    <DIR>          microsoft.maui.core.runtime.any
08/16/2021  10:17 AM    <DIR>          microsoft.maui.dependencies
08/16/2021  10:17 AM    <DIR>          microsoft.maui.essentials.ref.android
08/16/2021  10:17 AM    <DIR>          microsoft.maui.essentials.ref.any
08/16/2021  10:17 AM    <DIR>          microsoft.maui.essentials.runtime.android
08/16/2021  10:17 AM    <DIR>          microsoft.maui.essentials.runtime.any
08/16/2021  10:17 AM    <DIR>          microsoft.maui.extensions
08/16/2021  10:17 AM    <DIR>          microsoft.maui.resizetizer.sdk
08/16/2021  10:17 AM    <DIR>          microsoft.maui.templates
               0 File(s)              0 bytes
              21 Dir(s)   2,273,914,880 bytes free

**Comment by ncarandini** [comment]
Use [maui-check](https://github.com/Redth/dotnet-maui-check)

**Comment by jsuarezruiz** [comment]
Use this script to remove the installed worklods https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1

Then, install again the worklods:

`dotnet workload install maui`

or

`dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.10.json`

**Comment by jsuarezruiz** [comment]
Was an issue with an old Preview (3, actually we have 10) and I am going to close the issue. However, let me know if still have issues with the latest Preview and we can reopen the issue or open a new one.
