### ISSUE TITLE
DataBinding corrupted: not updating values, when it does, it’s alternating with 0 value

### ISSUE THREAD

**Issue by MAUIoxo** [dotnet/maui#20821]
### Description

In my App, I update values of an `ObservableRangeCollection` (connected via `DataBinding` to a View of a `DataTemplate` of a `CollectionView`). The update of the values is done in a method called in the example project below by clicking on a Calculate Button. 

The `ObservableRangeCollection` is bound to the `CollectionView` via `ItemsSource="{Binding SelectedStoreItems, Mode=TwoWay}"` and binds it to the other View via `ItemTemplate="{StaticResource VerticalItemTemplate}"`:

```xaml
<DataTemplate x:Key="VerticalItemTemplate" x:DataType="{x:Type databaseModels:StoreSelection}">
	<sho:DraggableViewCell>
		<views:StoreSelectionItemView />
	</sho:DraggableViewCell>
</DataTemplate>
```

After clicking the Calculate-Button I can see the values updated in the `ObservableRangeCollection<StoreSelection>` in Debugger. But they do not get updated in the UI. It gets even worse when I switch my Views by clicking on the other `Tab` and back the values are finally loaded but toggle between the calculated values and "0"

**I must say when DataBinding or UI stuff is corrupted in some way, it is a prio 1 issue for me when stability is key for future versions. The whole scenario worked before and now the values do not get their updates in UI**

**Hint:** In the ViewModel, I have to clear the bound list in some way. As there were memory issues before in .NET 7, I used the way here to delete every element one by one from the list which solved my problem regarding rising memory consumption. But, maybe the deletion of the list and re-building it, might be a problem with its binding underneath.

<br/>

The whole scenario can be seen here:

![DataBindingCorruptedExample](https://github.com/dotnet/maui/assets/140683727/7fca5bfb-6829-4494-9895-e76f0e6e36e8)

### Steps to Reproduce

1. Set a Breakpoint in ..\DataBindingCorrupted_20821\DataBindingCorruptedExample\ViewModels\TabView1ViewModel.cs at the Beginning of the Method, e.g. in line 127
2. Set another Breakpoint in same method, e.g. on line 130
3. Start the App in Debug Mode
4. Click on the .NET Bot Icon to open BottomSheet
5. Select both items
6. Both values for "Optimal Profit" of the selected items are "0" initially
7. Click on "Calculate" to do the Calculations
8. You will hit the first Breakpoint set above
9. Watch the correpsonding values for "OptimalProfit" of the items in "SelectedStoreItems" **before the Calculation**
[0] - {DataBindingCorruptedExampleDatabase.StoreSelection} => OptimalProfit = 0
[1] - {DataBindingCorruptedExampleDatabase.StoreSelection} => OptimalProfit = 0

10. Stop at the next Breakpoint set above to see the values **after the Calculation** and both are set to "10"
[0] - {DataBindingCorruptedExampleDatabase.StoreSelection} => OptimalProfit = 10
[1] - {DataBindingCorruptedExampleDatabase.StoreSelection} => OptimalProfit = 10

11. After the call of `OnPropertyChanged(nameof(SelectedStoreItems));` in line 130 the UI should be updated as the label in **StoreSelectionItemView.xaml** is bound to this value via DataBinding in **TabView1.xaml** with the `ItemsSource="{Binding SelectedStoreItems, Mode=OneWay}"` and `ItemTemplate="{StaticResource VerticalItemTemplate}"` of the `CollectionView` in line 96/98 of file **TabView1.xaml**
12. Switching to "Tab 2" and back to "Tab 1" shows updates it and shows the calculated value "10"
13. But when switching again to "Tab 2" and back to "Tab 1" it even gets worse and the values toggle between "10" and "0"
14. Where does this old value come from? Is it the `Clear`-Action 

The heart of all the Actions performed is in the following file:
`..\DataBindingCorrupted_20821\DataBindingCorruptedExample\ViewModels\TabView1ViewModel.cs` mostly in methods `GroupStoreItemsApplyingSearchFilter()` and `CollectSelectedStoreItems()` which also are hit when Tabs are switch via method `HandleUpdateSelectedStoreItemsMessage(object recipient, UpdateSelectedStoreItemsMessage updateSelectedStoreItemsMessage)`

### Link to public reproduction project repository

**Example project:** [DataBindingCorrupted_2081](https://github.com/MAUIoxo/DataBindingCorrupted_2081)

### Version with bug

8.0.10-nightly.10061

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS, Android

### Affected platform versions

iOS 17.2, Adroid API 33

### Did you find any workaround?

Unfortunately not - tried with [ObservableProperty]-Attribute as well and it did not change

**Comment by MAUIoxo** [comment]
Here is a quick update on that issue:

In the attached example project I used `INotifyPropertyChanged` in a .NET Core DLL (not MAUI DLL) which is still done for reason. But, it seemed like the notifications on changes did not work in this scenario. Now, I switched to an `ObservableObject` from the `MVVM Community Toolkit` and see how behaves now - values are instantly updated and no toggling anymore:

![DataBindingCorruptedExampleSolved](https://github.com/dotnet/maui/assets/140683727/46f92897-2147-4e69-8867-be78a13bbfc7)

<br/>
With this, at least for me, this issue could be closed. I don't know if you want to dig deeper on the original scenario. But using `ObservableObjects` to get the notifications more reluctantly works fine!

**Comment by MAUIoxo** [comment]
Thank you very much for your update and your findings. In my original App it also did not work for me in Release on my iPhone. But, the example project I created might be as you said.

When I changed it to the `ObservableObject` it seems to work in Debug and on my iPhone. The question is, what would you recommend. Stay with the `PropertyChangedEventHandler` implementation as you changed it or with the `ObservableObject`? My code before the `WeakEvent` implementation caused memory issues due to missing unsubscriptions of the `Events`.

From this standpoint and from how `ObservableObject` manages them, what is the way to go?

Also as we had a good finding in this thread I would recommend, that you can close it. What would you say?

**Comment by simonrozsival** [comment]
AFAIK the `ObservableObject` also doesn't use weak events, that's probably why it works for you. I think you should be fine writing the property change handling yourself or using the community toolkit.
