### ISSUE TITLE
UITextAlignment.Justified not working on iOS

### ISSUE THREAD

**Issue by JuanFcoMiranda** [dotnet/maui#20826]
### Description

On iOS I have created a custom label with a bindable property to justify the text on a Label. I also created a LabelHandler associated with this control and I set the value to UITextAlignment.Justified on the handler.PlatformView.TextAlignment property but the text is not justified:

<img width="437" alt="Screenshot 2024-02-24 at 17 07 29" src="https://github.com/dotnet/maui/assets/502325/1611fcf6-b431-480f-beb3-6bda5711b0ed">

### Steps to Reproduce

1. Create a custom class that inherits from Label
2. Create a custom handler
3. Add the handler to MauiProgram
4. Insert the custom control in a view and set the JustifyText property to true

### Link to public reproduction project repository

https://github.com/JuanFcoMiranda/MauiExample

### Version with bug

8.0.7 SR2 and previous

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jaosnz-rep** [comment]
Verified this issue with VS for Mac 17.6.10 build 428 on 8.0.10, can repro on iOS platform with sample project.

**Comment by kubaflo** [comment]
@JuanFcoMiranda @jsuarezruiz Hi, try to add this line of code `LabelHandler.Mapper.AppendToMapping(nameof(ITextAlignment.HorizontalTextAlignment), MyJustifiedLabelHandler.MapTextAlignment);`

<img src="https://github.com/dotnet/maui/assets/42434498/1e91d7dd-3db3-42bc-a8b1-b2020b7aa6bc" width="300px"/>

**Comment by JuanFcoMiranda** [comment]
Thank you very much @kubaflo, now it works as expected.
