### ISSUE TITLE
REST API interaction tutorial for MAUI shows antipatterns without warning

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#20829]
https://learn.microsoft.com/cs-cz/dotnet/maui/data-cloud/rest?view=net-maui-8.0

is showing sing manual and repeated REST API interaction code without telling about automatically generated REST API clients available in C# or about IHttpClientFactory existence for centralized configuration and without telling why manual code is used

**Comment by drasticactions** [comment]
CC @davidbritch 

From my perspective, I think this tutorial is fine as a tutorial within the context of the Todo app it was written for. It doesn't require third party tools for implementation and while there are other techniques for managing HttpClient's like through `IHttpClientFactory` it's not required or always needed; It's another valid way to do it, one of many ways.

**Comment by jfversluis** [comment]
Docs related issues should go to https://github.com/dotnet/docs-maui/issues

For the rest I agree with @drasticactions. There is many ways to go about certain things, we can only describe so much, the rest should be figured out by the reader and do whatever makes sense according to their knowledge, views and needs.

Thanks for bringing this up!
