### ISSUE TITLE
FontFamily is not set on Editor Placeholder on iOS

### ISSUE THREAD

**Issue by GalaxiaGuy** [dotnet/maui#20839]
### Description

Changing the `FontFamily` property on an `Editor` control does not update the font used for the `Placeholder` text.

This bug was raised about font attributes not applying to the `Placeholder`:
https://github.com/dotnet/maui/issues/20054

Which was fixed in this PR:
https://github.com/dotnet/maui/issues/15883

It seems to have missed setting the actual font.

The folllowing image should have Times New Roman as the font:

![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-26 at 09 11 21](https://github.com/dotnet/maui/assets/475450/17660b53-055b-4c17-ac9f-fa657485022b)

### Steps to Reproduce

Create an `Editor` with a non-default font and a placeholder.
```csharp
<Editor Placeholder="This is Editor with a placeholder" FontFamily="Times New Roman" />
```

### Link to public reproduction project repository

https://github.com/GalaxiaGuy/NullableConverterBug/tree/editor-placeholder-font

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

I believe this has always been this way.

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Adding a mapper method like the following works, but is fragile since the label that needs to be updated is private and needs to be guessed at:

```csharp
private static void MapFontFamily(IEditorHandler handler, IEditor virtualView)
{
    if (handler.PlatformView is { Font: { } font } textView)
    {
        if (textView.Subviews.OfType<UILabel>().FirstOrDefault() is { } placeholderLabel)
        {
            placeholderLabel.Font = font;
        }
    }
}     
```

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 2.0(8.0.14). Repro on Android 14.0-API34, iOS 17.2 and MacCatalyst, not repro on Windows 11 with below Project:
[NullableConverterBug.zip](https://github.com/dotnet/maui/files/14798814/NullableConverterBug.zip)
