### ISSUE TITLE
Android Plattform related Errors CS0246 'MauiAppCompatActivity' & 'MauiApplication'

### ISSUE THREAD

**Issue by BadestcoderEUW** [dotnet/maui#20847]
### Description

![image](https://github.com/dotnet/maui/assets/111186114/467dbcbd-64e6-4044-a3d3-b3a573df2578)
![image](https://github.com/dotnet/maui/assets/111186114/5d49f73a-ef34-46ec-9736-b13d211b4538)

These two Classes where not found by default. I have not changed those classes. In other of my Projects these Classes are equal but don't give Error CS0246. I already deleted obj and bin folder + migrated the code into another project.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by owaits** [comment]
I am seeing this error frequently too, it seems to be intermittent. They way I get around it is by commenting out one of the two TargetFrameworks definitions. Normally after doing this and re-building it wont come up with this issue. Its annoying though as I happen to be developing for Windows, Android and IOS so switching is not as easy as it should be. 

'''
<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>

'''

or 

'''

<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
'''

**Comment by BadestcoderEUW** [comment]
Hello Oliver, 
thanks for the answer. I've tried to solve the problem with your solution. 
The errors disapperead but the application didn't start well.

So after undo the code changes, i've tried to downgrade the NuGet Packages to an older stable versions. Which worked out well. -

**Comment by jfversluis** [comment]
What versions did you use? That is very useful information.

**Comment by owaits** [comment]
I have submitted my logs and a screenshot which relates to this issue to vs developer community. 

`https://developercommunity.visualstudio.com/t/ompileAppManifest-task-failed-unexpected/10616951`

Before upgrading to Preview 2 I was mostly able to work around this issue but all my tricks to fix it no longer seem to work in Preview 2.
