### ISSUE TITLE
.Net Maui Class library template not available

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#2084]
### Description
.Net Maui Class library template not available after installing VS2022 preview 3 version.

Tried repairing VS2022 preview 3.
Installed dotnet workload install maui
Installed using maui-check.

**Comment by Eilon** [comment]
Hi @PaulAnderson02 can you check if the template shows up from the command-line?

You can run `dotnet new -l` from the command line and see if it at least shows up there. That will help us narrow down if the templates aren't installed at all, or if they're just not showing up in VS.
![image](https://user-images.githubusercontent.com/202643/131890612-bdcd8c77-943e-43ff-8c0b-d70f1b17d5fc.png)

**Comment by PaulAnderson02** [comment]
Hi @Eilon 

Please have the requested details.
![image](https://user-images.githubusercontent.com/42271912/131949076-34e351a7-dff2-4d84-93e1-6c05fffde5bd.png)

**Comment by Eilon** [comment]
Ah, well, I think I have an easy explanation for that: the MAUI Class Library template wasn't in .NET 6 Preview 7. It's relatively new so it will be in the next preview that should be coming out this month (here's the PR: https://github.com/dotnet/maui/pull/1827).

**Comment by PaulAnderson02** [comment]
@Eilon  Thanks for the update.
