### ISSUE TITLE
AbsoluteLayout initialized in code-behind does not update view layout on Android

### ISSUE THREAD

**Issue by BeepBeepBopBop** [dotnet/maui#20845]
### Description

I am trying to set 2 views positions and sizes based on the available height on the page.
For that I use an AbsoluteLayout, and I initialize it in the parent page OnSizeAllocated method call.
It works fine on all platform except Android, which simply does not show any of the two views present in the AbsoluteLayout.

I have experienced similar issues with different controls, and unfortunately I did not manage to isolate them correctly, but it seems that trying to set dynamically the size/position of views on Android results in a lot of cases in the View not being shown at all (probably the height and width of the View staying equal to 0).

### Steps to Reproduce

1 Launch the demo app on Android
-> Only the green box shows, not the red and the blue
2 Click the button to trigger a new change in the AbsoluteLayout values
-> The changes are correctly taken into account and you can now correctly see the green and blue boxes contained in the AbsoluteLayout

Demo:
https://ibb.co/Pg7RtJq

Windows (working fine):
https://ibb.co/y54Hm3F

### Link to public reproduction project repository

https://github.com/BeepBeepBopBop/AbsoluteLayoutBug

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 2.0(**8.0.7**). This issue doesn't repro on Windows 11, Android 14.0-API34/Android 11, iOS 17.2 and MacCatalyst with below Project:
[AbsoluteLayoutBug.zip](https://github.com/dotnet/maui/files/14799115/AbsoluteLayoutBug.zip)

Android:
![AndroidLayout](https://github.com/dotnet/maui/assets/97647558/fd1cc0fa-88b3-466f-a6f3-37db592ae774)
