### ISSUE TITLE
.Net MAUI iOS app install but does not update

### ISSUE THREAD

**Issue by faceoffers28** [dotnet/maui#20868]
### Description

I've got a .Net MAUI iOS app that installs but does not update. I get the Verifying, Loading, and Installing messages with a clock spin showing the progress of the app install. There is no error message. The app simply does not update. I know it's not updating because I am displaying the ApplicationDisplayVersion on the login page. I'm also passing the ApplicationDisplayVersion in an API call that I'm storing in a database. The last version that updated was built on Feb 12th. Since then, I've had 29 more builds. I've used both Xamarin and .Net MAUI extensively. I've never seen this issue.  

### Steps to Reproduce

Create a .Net MAUI iOS app with the following configs: 

.NET MAUI 8.03 iOS app built using an Azure DevOps Pipeline. It Targets iOS 17 with Support for iOS 16.1.
.NET MAUI 8.03 iOS app built using an Azure DevOps Pipeline It targets 17.2 with Support for iOS 16.1.
.NET MAUI 8.03 iOS app built using an Azure DevOps Pipeline It targets 17.2 with Support for iOS 16.7.2.
.NET MAUI 8.06 iOS app built using an Azure DevOps Pipeline It targets 17.2 with Support for iOS 16.7.2.

Here are my test devices.

iPhone 12 running iOS 16.7.2. 
iPhone 12 running iOS 17.3.1. 
iPhone 13 running iOS 17.2.

Add version to the home page. Build an Azure DevOps iOS app using XCode 15.0.1 and .NET Core sdk version 8.0.201 along with the latest verion of .Net MAUI in Azure DevOps (Microsoft.Maui.Sdk version 8.0.6). Use App Center to sideload the app. Next, make a version change to the app. Build the new app. Install the new app. The version should update on the home page. 

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

iOS

### Did you find any workaround?

Not yet. I would like to try a rollback version of .NET MAUI but I can't find the rollback file for .Net MAUI 8.0.3. Something like this. https://maui.blob.core.windows.net/metadata/rollbacks/8.0.1xx.json

**Comment by faceoffers28** [comment]
@samhouts I was able to build a .NET MAUI 8.0.3 version of the application using a Rollback file. The problem still persists. I'm at a loss as to why this is happening. It's so frustrating!

**Comment by faceoffers28** [comment]
@samhouts The issue was AppLinks code. I followed these instructions. For whatever reason, the app would install, but it would not update. I commented out the few lines of code I added to 3 or 4 files and the app is now working as expected.

https://github.com/Redth/MAUI.AppLinks.Sample/tree/main

**Comment by faceoffers28** [comment]
@samhouts The real issue is that you have to add Associated Domains to the app Identifier in the Apple Developer Portal. Without this, the app will not update. This step is missing from almost all the docs I've seen on implementing AppLinks on iOS.

**Comment by samhouts** [comment]
@davidbritch Is this something we should add to our docs?

**Comment by davidbritch** [comment]
@samhouts @faceoffers28 already created a docs issue for it a few days ago.

**Comment by samhouts** [comment]
Excellent! We will close this one, then. Thank you!!!!
