### ISSUE TITLE
ImageEditor control is not visible inside Frame on iOS

### ISSUE THREAD

**Issue by Shalini-Ashokan** [dotnet/maui#20862]
### Description

The image editor control fails to appear within the frame, but it is correct on the Windows and Android platforms. The size is not getting properly. 
```
<Frame>
<imageEditor:SfImageEditor x:Name="imageEditor" Margin="0" Source="bannerimage.png"/>
</Frame>
```

### Steps to Reproduce

1. Create a new Maui application.
2. Add an image editor control to the frame.
3. Run the application on an iOS or macOS platform.

### Link to public reproduction project repository

https://github.com/Shalini-Ashokan/IOSImageEditor

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

IOS 16.2, macOS 12.6.3

**Comment by Zhanglirong-Winnie** [comment]
Verified on VS for Mac 17.6.10 build 428 (8.0.7), can repro issue with sample project on iOS and macOS platforms.

**Comment by jfversluis** [comment]
Seeing that Frame is officially deprecated as of .NET 9, I don't think we will be working on this anymore. Also its a bit older by now, so maybe its even resolved in current versions 🤞
