### ISSUE TITLE
VS2022 getting Freezed

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#2086]
I installed all the stuff and after loading a maui project VS2022 is frozen and can only termined with the Taskmanager.
Anyone the same problems ?

**Comment by davidortinau** [comment]
Please open a clean VS22 session, no solution/code, and submit a feedback issue from Help > Send Feedback. This will send the logs from the previous session.

Then share the link back here so others can follow and comment on it please.

**Comment by jfversluis** [comment]
I hope this is resolved for you by now! Else please do as David suggests. Thanks :)
