### ISSUE TITLE
It's impossible on Android to assign 0 value to the Button  CornerRadius:  <Button ...  CornerRadius="0" ... />

### ISSUE THREAD

**Issue by DeveloperLookBook** [dotnet/maui#20923]
### Description

On Android, **"Button" control ignores "0" value for the Button "CornerRadius" property**. If the value is bigger than "0" then everything works as expected. 

### Steps to Reproduce

To reproduce the issue, add this button to XAML markup:
`<Button Text="Click me"  CornerRadius="0" />`

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android SDK Platform 33

**Comment by PureWeen** [comment]
This should be fixed in the next release
https://github.com/dotnet/maui/pull/18959

Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by DeveloperLookBook** [comment]
@PureWeen Hi! 

I have updated my"Microsoft.Maui.Controls" package to  Version "8.0.7" and it looks like everything work good.
