### ISSUE TITLE
Regression Bug. Nested ScrollView does not work in Android. Works in iOS.

### ISSUE THREAD

**Issue by Manish-Pradhan-FP** [dotnet/maui#20920]
### Description

More details here https://github.com/dotnet/maui/issues/7811
This bug existed in DotNet 7 and was fixed in DotNet 8 but in its back in 8.0.7. If I revert back to 8.0.6 the issue goes away.

### Steps to Reproduce

```
<ScrollView Orientation="Horizontal">
    <ScrollView Orientation="Vertical"/>
</Scrollview>
```

The inner scrollview does not scroll in Android.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1
8.0.4-nightly.9742 (I realize 4 is less then 6 but this version is newer than 8.0.6)

### Affected platforms

Android

**Comment by PureWeen** [comment]
My current guess is that this behavior changed here

https://github.com/dotnet/maui/pull/19349
