### ISSUE TITLE
[Bug] Shell labels don't update with AppThemeBinding changes

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2092]
### Description

```
<Color x:Key="Text_Light">#000000</Color>
    <Color x:Key="Text_Dark">#FFFFFF</Color>

<Style
        TargetType="Label"
        Class="FlyoutItemLabelStyle">
        <Setter
            Property="FontSize"
            Value="18" />
        <Setter
            Property="TextColor"
            Value="{AppThemeBinding Dark={StaticResource Text_Dark}, Light={StaticResource Text_Light}}" />
        <Setter
            Property="FontFamily"
            Value="OpenSansRegular"/>
        <Setter
            Property="HeightRequest"
            Value="44" />
    </Style>
```
### Steps to Reproduce

Toggle mode on the simulator

### Expected Behavior

AppThemeBinding usage is reflected everywhere

### Actual Behavior

Not happening

### Basic Information

- Version with issue: preview.7

### Screenshots

![Simulator Screen Shot - iPhone 12 - 2021-08-13 at 15 30 02](https://user-images.githubusercontent.com/41873/129417238-ff0b0db9-505d-4932-9925-fde7655e58ca.png)
![Simulator Screen Shot - iPhone 12 - 2021-08-13 at 15 30 06](https://user-images.githubusercontent.com/41873/129417248-8dfa6cb4-800b-4a28-982b-ff65e6d06b17.png)

### Reproduction Link

https://github.com/davidortinau/ControlGallery

**Comment by PureWeen** [comment]
Tested against main and this appears to be fixed
