### ISSUE TITLE
MtouchInterpreter doesn't seem to exclude dlls listed

### ISSUE THREAD

**Issue by rbakhshi** [dotnet/maui#20932]
### Description

I tried to enable interpreter for everything other than one of the libraries we use so what I did was adding these to project file:

```xml
<PropertyGroup>
    <MtouchInterpreter>all,-library.dll</MtouchInterpreter>
  </PropertyGroup>
```

I can't seem to be able to make this to work, the only assembly that gets AOT in `_aotCompile` step is `System.Private.CoreLib.dll`

```
Target _AOTCompile:
Tool /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.ios-arm64/8.0.2/Sdk/../tools/mono-aot-cross execution started with arguments: --path=/Users/user/workspace/net/app-app/app.Phoenix/obj/Release/net8.0-ios/ios-arm64/linked --aot=mtriple=arm64-ios,data-outfile=obj/Release/net8.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Private.CoreLib.aotdata,static,asmonly,dedup-skip,direct-icalls,interp,readonly-value=ObjCRuntime.Runtime.Arch=i4/0,nodebug,dwarfdebug,llvm-path=/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.ios-arm64/8.0.2/Sdk/../tools,outfile=obj/Release/net8.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Private.CoreLib.dll.s,llvm-outfile=obj/Release/net8.0-ios/ios-arm64/nativelibraries/aot-output/arm64/System.Private.CoreLib.dll.llvm.o --debug --llvm /Users/user/workspace/net/app-app/app.Phoenix/obj/Release/net8.0-ios/ios-arm64/linked/System.Private.CoreLib.dll
```

On the other hand, if I change that line to `<MtouchInterpreter>-all</MtouchInterperter>` then everything gets aot-ed and I get runtime cash due to issues with some of our assemblies.

I also tried the above (`-all`) and excluding assemblies but doesn't seem like any assembly gets excluded.

Seems like only `all` and `-all` are taken into account 

### Steps to Reproduce

1. Use Maui Sample app
2. Add BCrypt.Net-Next 4.0.3 as a nuget package
3. Add a line to App.xaml.cs to use the BCrypt library:
   1. Something like: `BCrypt.Net.BCrypt.Verify("111111", "$2a$12$luf9xtzcPijRzyMnb1PxsuqFUsBba0ve.R.5k00XOsGf2awcHwj8a");`
 4. Run the app for release. It should take around less than a second to run the above code
 5. Now add `<MtouchInterpreter>all,-BCrypt.Net-Next.dll</MtouchInterpreter>` to the release config in csproj file.
 6. Run the app

Expected: the code should still run fast but still takes 2-4 seconds. Also there is no trace of AOT on the above dll.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

no workaround found.

**Comment by drasticactions** [comment]
I think this would be a [xamarin-macios](http://github.com/xamarin/xamarin-macios) tooling issue, I don't think it's related to anything in this repo. @rolfbjarne what do you think?

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#20228
