### ISSUE TITLE
[Bug] Page background isn't updating with AppThemeBinding

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2093]
### Description

I'm using background and brushes. The initial color is correct, but at runtime any change isn't being reflected.

```
<Style TargetType="Page" ApplyToDerivedTypes="True">
        <Setter Property="Padding" Value="15"/>
        <Setter Property="Background"
            Value="{AppThemeBinding
                Dark={StaticResource BlackBrush},
                Light={StaticResource WhiteBrush}}"/>
        <Setter Property="Shell.NavBarIsVisible" Value="false"/>
    </Style>
```

### Steps to Reproduce

1. toggle mode on simulator while running

### Expected Behavior

All AppThemeBinding stuff updates

### Actual Behavior

Not happening

### Basic Information

- Version with issue: preview.7

### Screenshots

![Simulator Screen Shot - iPhone 12 - 2021-08-13 at 15 54 46](https://user-images.githubusercontent.com/41873/129417578-c6a4110b-2a23-458c-9c7d-44cf08a7b744.png)
![Simulator Screen Shot - iPhone 12 - 2021-08-13 at 15 55 20](https://user-images.githubusercontent.com/41873/129417579-5b418fbb-66ef-462a-b17b-3d85d61876ad.png)

### Reproduction Link

https://github.com/davidortinau/ControlGallery

**Comment by mattleibow** [comment]
@PureWeen this feels related to https://github.com/dotnet/maui/issues/3188

Might be a conflict between bindings and explicit values.

**Comment by PureWeen** [comment]
I tested this in a new app and it appears fixed with the latest code

![image](https://user-images.githubusercontent.com/5375137/141513253-bc788e95-4ce7-4c96-9696-0d2a0e315fac.png)
