### ISSUE TITLE
<Border /> property is not working while I write <Label /> property and passing a Text="", text is not being shown in the android emulator.

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [dotnet/maui#20944]
### Description

<ScrollView>
    <VerticalStackLayout>
        <Frame Margin="10" BackgroundColor="AliceBlue">
            <VerticalStackLayout>
                <Image Source="./Resources/Images/dotnet_bot.png" />
                <Label Text="Coding Droplets"
                            FontSize="20"
                            FontAttributes="Bold"
                            HorizontalOptions="Center"
                            TextColor="Sienna" />
            </VerticalStackLayout>
        </Frame>

        <Frame BackgroundColor="AntiqueWhite" Margin="10">
            <Border>
                <Label Text="Welcome" HorizontalOptions="Center" />
            </Border>
        </Frame>
    </VerticalStackLayout>
</ScrollView>

In this code, the text is not being shown under <Border /> property.

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

### Affected platform versions

Android pixel 6 pro emulator API 32

**Comment by PureWeen** [comment]
@SoumyadipYT-OSS why are you using a frame here? Can you just use two borders or no frame?

**Comment by kubaflo** [comment]
@SoumyadipYT-OSS using border instead of frame usually fixes frame's issues :)

**Comment by SoumyadipYT-OSS** [comment]
Thank you @kubaflo for this information.

**Comment by SoumyadipYT-OSS** [comment]
Another thing I wonder is that still using of Semanticproperties.Header the "StackLayout" can't be used under scroll view more than once. @samhouts @kubaflo 

This is the screenshot:
![IMG_20240305_002329786.jpg](https://github.com/dotnet/maui/assets/94290293/a7584e63-2efc-4c91-9e01-962c6c20ef79)

**Comment by SoumyadipYT-OSS** [comment]
> @SoumyadipYT-OSS why are you using a frame here? Can you just use two borders or no frame?

I want to use a frame to write information in it as a box. And there is a border that covers the frame. But it is not showing the output properly. Is there any good way to implement this thing. If you don't mind I didn't understand "use of two borders" as you said in your previous comments.
@PureWeen

**Comment by SoumyadipYT-OSS** [comment]
Solution solved. 
![Screenshot (192)](https://github.com/dotnet/maui/assets/94290293/243661f8-9f7e-45ac-9906-6791d19aac56)
Thank you @kubaflo and @PureWeen

**Comment by SoumyadipYT-OSS** [comment]
Problem Solved.  ✅
![Screenshot (191)](https://github.com/dotnet/maui/assets/94290293/30838eaf-9a8d-463e-ba97-77cc647242a0)

**Comment by PureWeen** [comment]
This fix should be available on the nightly feed as version `8.0.61-ci.net8.24319.3`. 

Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds
