### ISSUE TITLE
Border does not resize correctly (android)

### ISSUE THREAD

**Issue by softlion** [dotnet/maui#20943]
### Description

I use a Border as the root control of a toolkit:Popup.

Inside the control's hierarchy there is an Entry.

On Android, when I paste a large text in the Entry, the popup grows horizontally to match the screen size (it was about 50% of the screen size otherwise).

May be the return of https://github.com/dotnet/maui/issues/7524

![image](https://github.com/dotnet/maui/assets/190756/e7b8e6b1-a9bd-45ed-a6a7-1437a0c05d6e)

### Steps to Reproduce

```xaml
<toolkit:Popup 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:constants="clr-namespace:WzXam2.Constants"
    xmlns:appresource="clr-namespace:WzXam2.Resources"
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
    x:Class="Wz.Views.Shared.PopupContainerPage" 
    Color="Transparent"
    >
 <Border Stroke="{x:Static constants:ViewConstants.ColorWzDarkGray}" 
            BackgroundColor="White" StrokeShape="RoundRectangle 20" StrokeThickness="0">
   <Grid RowDefinitions="50,*,70">
         ....
            <VerticalStackLayout Grid.Row="1">
                <Grid Margin="10,0">
                       <Entry ... />
                </Grid>
            </VerticalStackLayout>
         ....

  </Grid>
    </Border>
</toolkit:Popup>
```

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

no

**Comment by PureWeen** [comment]
Have you reached out to the community toolkit about this issue?

**Comment by softlion** [comment]
No because it looked like more a general issue than a specific issue with the BORDER control.

Here another report from another user: https://github.com/CommunityToolkit/Maui/issues/1724

**Comment by bijington** [comment]
@softlion if you put the same content inside a `Border` on a page does it behave the same way? If it behaves as expected then it is most likely an issue with the toolkit.

**Comment by acaliaro** [comment]
I have the same problem on iOS but I think is a popup problem...

**Comment by kevinxufei** [comment]
Can repro this issue at Android platform on the latest 17.10 preview 2(8.0.10).

**Comment by PureWeen** [comment]
closing in favor of https://github.com/CommunityToolkit/Maui/issues/1724
