### ISSUE TITLE
Hot Reload Button issue

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [dotnet/maui#20945]
### Description

During hot reload, sometimes Android 13 version and API 32 Google Pixel 6 pro Android emulator is unable to fetch real-time update data. I have to restart the emulator to solve. But is there any solution for this hot reload button?

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

7.0.100

### Affected platforms

Android

### Affected platform versions

Android 13 API: 32

**Comment by drasticactions** [comment]
The Hot Reload button functions in their various forms are maintained by the Visual Studio team and can't be addressed here. If you file it through VSFeedback, someone on that team can addressed it and if there is a bug with MAUI, it can be redirected back here.

**Comment by SoumyadipYT-OSS** [comment]
Thank you for this information

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
