### ISSUE TITLE
無法調試執行偵錯觀看設計介面

### ISSUE THREAD

**Issue by adlerlei** [dotnet/maui#20957]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/maui/first-app-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
<img width="1409" alt="截圖 2024-03-02 晚上8 05 46" src="https://github.com/dotnet/maui/assets/9949552/4529e632-16d8-40e2-a980-a4344271da67">

我在執行偵錯的時候一直出現以下信息：
您沒有用於偵錯 XML 的延伸模組。我們是否要在 Marketplace 中尋找 XML 延伸模組?

我已按照網址安裝完所有套件

**Comment by drasticactions** [comment]
Editor features like this are functions of Visual Studio or Visual Studio Code and can't be addressed here directly. You should address this in the VSCode MAUI extension.

Currently (as of this post) there are no formatting or additional features for editing XAML within VSCode with the MAUI extension. Those featueres are coming in the future. While you can edit the XAML and it should build, you can't format it nor see intelisense without additional extensions. These are features not maintained by this repo, they need to be addressed elsewhere.

**Comment by adlerlei** [comment]
Thank you very much for your enthusiastic replies. I think I will look into it. Thank you.
