### ISSUE TITLE
Can't see wireless connected device for iOS

### ISSUE THREAD

**Issue by ptittof57** [dotnet/maui#20958]
### Description

I have followed steps in this documentation: https://learn.microsoft.com/en-us/dotnet/maui/ios/wireless-deployment?view=net-maui-8.0&tabs=vs and it works with my iPhone 7 - iOS 15.8 but I can't make it work with my iPhone XR and iPhone 13 on iOS 17.3
Both are paired on Xcode 15.2 but I can't see them in VS Mac on mac os sonoma

I don't know if it's an issue with iOS version, Xcode or MacOs I think it's related to iOS as it works on my iPhone 7 - iOS 15.8

### Steps to Reproduce

1. Follow theses steps: https://learn.microsoft.com/en-us/dotnet/maui/ios/wireless-deployment?view=net-maui-8.0&tabs=vs
2. Plug and iOS device with iOS 17.3 on mac os sonoma

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.3 / XCode 15.2 / MacOs Sonoma

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
This is not something that is part of the .NET MAUI SDK, but rather something in the tooling that makes .NET MAUI development possible. You might want to raise this through the suggestion above. That way it will land with the right team so they can have a look. Thanks!
