### ISSUE TITLE
on iOS, a control derived from Entry does not display the same of Entry

### ISSUE THREAD

**Issue by czuck** [dotnet/maui#20951]
### Description

In the image below, the first and last controls are an Entry, and the middle two are UnmodifiedEntry which is derived from Entry with no code change.  They should display identically, but the derived one is shorter and has a different default background color.
![image](https://github.com/dotnet/maui/assets/1641428/044aa24b-9d87-466b-989d-da0cc9288933)

When tested on Android the controls look identical.

### Steps to Reproduce

1. Run the linked project 
2. look at the output

### Link to public reproduction project repository

https://github.com/czuck/iOS-Entry

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.0 & 17.3.1

**Comment by czuck** [comment]
What I think you are saying is Entry has a style defined somewhere that isn't automatically applied to UnmodifiedEntry because Styles are not automatically inherited.  But the example you sent is all in XAML, and I've created this object in code.  So what do I need to add to my UnmodifiedEntry class to make it look and behave identical to Entry?  
```
public  class UnmodifiedEntry : Entry
{
}
```

**Comment by bradencohen** [comment]
I think you would have to update your [Styles.xaml](https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml). I would set the Entry styles to apply to derived types.

**Comment by czuck** [comment]
Thanks, I wasn't aware that file existed or that a new blank Maui app would have so many styles set by default.  I was able to get the two controls to behave the same by either finding the Style that targets Entry and adding ApplyToDerivedTypes="True" or deleting the entire style.
