### ISSUE TITLE
Swipe gesture not functioning using two fingers on Touch-pad

### ISSUE THREAD

**Issue by manikandan18102001** [dotnet/maui#20968]
### Description

The swipe gesture, which should be activated by using two fingers on the Touch-Pad, is not functioning as expected. When attempting to perform a swipe gesture, the expected response, such as scrolling or navigating between pages, is not observed. This issue significantly impacts user interaction and productivity, particularly for tasks that rely on multi-finger gestures for efficient navigation and operation.

### Steps to Reproduce

1. Create a New .NET MAUI App
2. Add a Box-View with Swipe Gesture Recogniser as the screen shot attached below
<img width="593" alt="image" src="https://github.com/dotnet/maui/assets/125555579/97b722e1-5e47-46dc-91ef-5be18db2b0c4">

3.Run the sample in Windows Platform
4.Perform Swipe behaviour with two fingers in touch pad
5. Observe the swiped event is not triggered

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by PureWeen** [comment]
@manikandan18102001 can you give us a repro for the Forms app that worked for you?
