### ISSUE TITLE
Trying to create ipa file file but got error from "CreateAssetPack" task during the distribution process

### ISSUE THREAD

**Issue by lowseven** [dotnet/maui#20966]
### Description

Im trying to create a IPA file to uploaded to the App Store, but each time I got the same error message:

*Could not create ipa file for distribution of archive --- the "CreateAssetPack" task was not given a value for the required parameter "Source"*

![image](https://github.com/dotnet/maui/assets/22934629/052cded3-2879-4708-874a-57dff55462e3)

Versions used:
MAUI 7 and NET 7.01
iOS 17.2

### Steps to Reproduce

1. Create an Archive of the app with visual studio 2022
2. click distribute button

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by PureWeen** [comment]
@rolfbjarne  thoughts?

**Comment by rolfbjarne** [comment]
@lowseven can you try archiving from the command line to see if that works? 

https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-8.0

**Comment by lowseven** [comment]
Hi,
hi tried to run the command suggested in the link:

dotnet publish -f net7.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="iPhone Distribution: xxxx" -p:CodesignProvision="Alser Distribution" -p:ServerAddress=x.x.x.x -p:ServerUser=lowseven -p:TcpPort=58181 -p:_DotNetRootRemoteDirectory=/Users/lowseven/Library/Caches/Xamarin/XMA/SDKs/dotnet/

but I got another error:

C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7129\tools\msbuild\iOS\Xamarin.Shared.targets(1757,3): error : Cou
ld not find Microsoft.iOS in C:/Program Files/Git/Users/lowseven/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft
.iOS.Sdk/16.4.7129/. [C:\Users\Railyn\Documents\Github\alsermobile\AlserMobile.csproj::TargetFramework=net7.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7129\tools\msbuild\iOS\Xamarin.Shared.targets(1757,3): error :
      [C:\Users\Railyn\Documents\Github\alsermobile\AlserMobile.csproj::TargetFramework=net7.0-ios]

**Comment by lowseven** [comment]
Hello, many thanks for your replies!

Someone on my team just broke the configuration....

the issue is solved

thanks :)

**Comment by lowseven** [comment]
Hello, many thanks for your replies!

Someone on my team just broke the configuration....

With your suggestion and some other magic, we managed to solve it on our side.

thanks :)
