### ISSUE TITLE
App is crashing in IOS after installing from testflight

### ISSUE THREAD

**Issue by neeleshyadav253** [dotnet/maui#20960]
App is crashing in IOS even it's running in Ios simulator and in debug mode in real device and perfectly working apk in android
so I don't understand why it's getting crash after installing from testflight

**Comment by jfversluis** [comment]
Hey @neeleshyadav253 sorry to hear this is happening to you, however with just this information it will be impossible to diagnose what might be going on. We don't know what your code looks like, what versions of SDKs and tools you are using, what error messages you might be seeing, what device logs you have and what information is in there, etc.

As such, I'm going to have to close this one. If you do want to still get some assistance, I would suggest maybe opening a discussion on the Discussions tab or open a thread on Microsoft Q&A. Please make sure that you add additional information, like what I mentioned above, to that.

Something that does come to mind immediately here is documented on this page: https://learn.microsoft.com/dotnet/maui/macios/interpreter?view=net-maui-8.0 maybe that will help.

Good luck!
