### ISSUE TITLE
maui-check  fail

### ISSUE THREAD

**Issue by HeiDimples** [dotnet/maui#2097]
Fix failed - Workload Repair failed: `dotnet workload repair --source "https://api.nuget.org/v3/index.json" --source
"https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.7.21379.14-shipping-1/nuget/v3/index.json"`

**Comment by HeiDimples** [comment]
Workload update failed: The JSON value could not be converted to Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadPackId. Path: $.Id | LineNumber: 0 | BytePositionInLine: 39.

**Comment by JanLoehr** [comment]
This helps, deleting the folder mentioned in this comment manually:

https://github.com/Redth/dotnet-maui-check/issues/105#issuecomment-898295227

**Comment by jsuarezruiz** [comment]
Use this script https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1 to remove the current workloads (not sure about the status, could have a mix of old versions).

Then, install latest VS 2022 Preview. And finally, install workloads

dotnet workload install maui

or

dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.10.json
