### ISSUE TITLE
SVG to PNG do not render SVG objects of type arc

### ISSUE THREAD

**Issue by ncarandini** [dotnet/maui#20972]
### Description

The PNG images created from the SVG files do not contains object of type a (arcs).
Take as example this SVG image (opened with Inkscape):
![OriginalSVG](https://github.com/dotnet/maui/assets/139274/3e19e6c3-3a1e-4687-a047-3ae5a7d54d0b)
and compare it with the PNG rendered image:
![RenderedPNG](https://github.com/dotnet/maui/assets/139274/be3e674a-e5d0-43fe-b09b-b5821a7550ce)
where you can see that also the small black dot is missing:
![Missing dot](https://github.com/dotnet/maui/assets/139274/a777a850-5d32-4f53-b302-28e6130d7db7)
because it's also described as an arc object on the SVG file:
![Dot is an arc object](https://github.com/dotnet/maui/assets/139274/9208dd6a-8db4-4b51-9aec-1af7975c8cd6)

### Steps to Reproduce

1. Create a MAUI app.
2. Add a SGV image with one or more arc objects in the Resources/Images folder, like the one that I've used:
[sad](https://github.com/dotnet/maui/assets/139274/5869923c-d830-42f9-bb91-f4591fafc8ff)
3. Add an image component to a content page like:
```
 <Image Source="sad.png" />
```
4. Run the app and see the missing SVG arc objects.

Please note that you can also check the rendered PNG images on the bin folder. You can check the sad.scale-400.png file in the Windows Appx folder or use Android Studio to look inside the apk file and check the sad.png file in the drawable-xxxhdpi-v4 folder.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Did you find any workaround?

Replacing arc objects with other type of objects (i.e. with cubic Bezier curve) solve the issue.

**Comment by Redth** [comment]
Related to #16100
