### ISSUE TITLE
Maui projects in Visual Studio stop building when changing Directory.Build.Props file

### ISSUE THREAD

**Issue by BobbyCannon** [dotnet/maui#20971]
### Description

This is very frustrating, and I have lost a lot of hours tracking down what is the problem.

I just learned about Directory.Build.Props a bit ago and I was super excited. Now my Maui projects start acting up. It's not at all hard to repo... I think or at list this constantly bothers me.

1. Just simply add a Directory.Build.Props file in a higher folder than Maui. 
2. Ensure the project has a different <TargetFrameworks entry.
3. Change the version or something else in Directory.Build.props.

VS will refuse to build even those sometimes it works.

![image](https://github.com/dotnet/maui/assets/840590/497c87fc-5c44-4017-8a8b-8f60f3f32326)

However, building from "dotnet" just works. The code below builds without problem.

```
# These works just fine, even when VS refuses to build
dotnet restore C:\Cornerstone\Cornerstone.Maui\Cornerstone.Maui.csproj
dotnet build C:\Cornerstone\Cornerstone.Maui\Cornerstone.Maui.csproj
```

I think this is the problem. All other .NET projects works fine when you override <TargetFrameworks in their csproj but VS pitches a fit for Maui projects.

I would love to use my "directory.build.props" file for all projects even Maui. Here is a shorted example of my directory.props.

```
<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net6.0;net7.0;net8.0</TargetFrameworks>
		<Configurations>Debug;Release</Configurations>
		<Company>Bobby Cannon</Company>
		<Authors>Bobby Cannon</Authors>
		<Copyright>© Copyright 2014-2024</Copyright>
		
		<!-- Versions -->
		<AssemblyVersion>1.0.4.1</AssemblyVersion>
		<FileVersion>1.0.4.1</FileVersion>
		<Version>1.0.4.1</Version>
		
		<!-- Maui Versions -->
		<ApplicationDisplayVersion>1.0.4.1</ApplicationDisplayVersion>
		
		<!-- Android / iOS Version-->
		<ApplicationVersion>1</ApplicationVersion>
		
		<LangVersion>latest</LangVersion>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SignAssembly>false</SignAssembly>
		<DelaySign>false</DelaySign>
		<AssemblyOriginatorKeyFile>$(SolutionDir)..\Cornerstone\Cornerstone.snk</AssemblyOriginatorKeyFile>
		<PackageIcon>Cornerstone.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="FodyWeavers.xml" />
		<None Include="$(SolutionDir)..\Cornerstone\FodyWeavers.xml" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Fody" Version="6.8.0" PrivateAssets="All" />
		<PackageReference Include="PropertyChanged.Fody" Version="4.1.0" PrivateAssets="All" />
	</ItemGroup>
</Project>
```

# Here is a temporary fix.

You can temporarily fix it by putting an empty Directory.build.props file in the project folder. Build the Maui project then delete the file.

```
<?xml version="1.0" encoding="utf-8"?>
<Project>
	<!-- Only here so that the default Directory.Build.props will not be used. -->
</Project>
```

### Steps to Reproduce

1. Just simply add a Directory.Build.Props file in a higher folder than Maui. 
2. Ensure the project has a different <TargetFrameworks entry.
3. Change the version or something else in Directory.Build.props.

### Some details that might help 

Here is what I have found. The file...

`Cornerstone.Maui\obj\project.assets.json`

drops to something around 2k, when there are any instances of Directory.Build.props or if the file is modified. Now running the following command outside VS restores the file back to 386 kb. 

`dotnet restore Cornerstone.Maui\Cornerstone.Maui.csproj`

However, if VS is running the file will get rolled back to the 2k version. I think the targets is getting cleared.

```
{
  "version": 3,
  "targets": {},
  "libraries": {},

```

**Comment by drasticactions** [comment]
The error you are seeing has nothing to do with overriding the TargetFrameworks via the props file, it's the platforms you are trying to target: MAUI project files are applications. By setting a directory.build.props file to include non platform specific TFMs (including netstandard2.0) you are asking VS to build for platforms that don't make sense for the project type (even if they may build, as it does with the CLI tooling). Strickly speaking, I don't believe this is not a MAUI issue. You would have similar issues building .NET native apps (net8.0-android, net8.0-ios, etc) without the MAUI UI tooling in the same way. I think this is something that would need to be addressed with Visual Studio first to verify that, and then circle back here if it's something specific with this project type (my guess is that it's not, as I can replicate this with net8.0-android without the MAUI UI tooling).
 
`directory.build.props` is a global setting. in your MAUI project, you can still set the TargetFrameworks values to only include the platform TFMs. It will ignore the global props file, but still use the other values.

https://github.com/drasticactions/MauiRepros/tree/main/MAUITFMTest

Here I have a global directory.build.props, with the MAUI TFMs set for its project, and the value removed from the class library, and it builds fine for me. If you removed the TFMs from your MAUI project (or are including them in your MAUI project), that would be why it's failing. If you could create a repro project showing exactly how you have this laid out we can see if it's something specific with this project, but my guess is that you're passing in values that don't make sense.

**Comment by BobbyCannon** [comment]
Sorry for the misunderstanding, I wasn't clear. I did NOT remove my TargetFrameworks from the Maui.csproj file.

I'm ensuring Maui overrides them. I think what is happen is that VS is the problem with the maui project type. Why, because the build works fine from "dotnet build".

However, I CAN build in VS with director.build.props in place but if you change something like "ApplicationDisplayVersion" then VS will get into a state where it just refused to build.

The "projects.assets.json" in the obj folder gets reduced greatly. From like ~380kb to 2kb.

You can then do a "dotnet restore" the projects.assets.json file in the obJ will be fix then immediately broken again by VS.

**Comment by BobbyCannon** [comment]
Here are the repo steps with a public repo. I have launched my repo early just so we can have an example.

[Cornerstone Repository](https://github.com/BobbyCannon/Cornerstone)

1. Open the solution "Cornerstone.sln"
1. Build the solution. Everything should build.
1. Open the Cornerstone.Maui.csproj
1. Change the "ApplicationDisplayVersion" from 1.0.4.1 to 1.0.5.1
1. Watch VS
a.  ![image](https://github.com/dotnet/maui/assets/840590/37e162ca-73ea-4141-b4d2-49d633459120)
1. The project will no longer build.
1. Revert the change to the "ApplicationDisplayVersion" from 1.0.5.1 back to 1.0.4.1
1. Watch VS
1. It will start working again, build will work.

**Comment by BobbyCannon** [comment]
https://github.com/dotnet/maui/assets/840590/248051b1-cb9a-4ace-beb6-a29e2ffcf8bf

Video to demo the issue

**Comment by jfversluis** [comment]
As indicated, this is more likely a Visual Studio/build engine issue. Please report the issue there. Unfortunately there is nothing we can do about this on our side.

Thank you for the thorough explanation and investigation!
