### ISSUE TITLE
MethodName(out IntPtr variableName) send null values for out parameter from the iOS Binding dll in .NET 8

### ISSUE THREAD

**Issue by ad5742** [dotnet/maui#20978]
### Description

GeList(out IntPtr variableName) send null values for out parameter from the iOS Binding dll in .NET 8 .NET 8 iOS binding library project . Method in ApiDefinition class.

`//iOS Binding Library Project ApiDefinition.cs 
// @required -(RESULT)getList:(NSMutableArray **)availableList; 
[Export("getList:")] Result getList(out IntPtr availableList);`

in .NET 7 if we call above method in MAUI SAMPLE APP the availableList will received.

`// MAUI app 
//Get avilable List 
NSMutableArray availableList = new NSMutableArray(); 
IntPtr availableHandle = availableList.Handle; 
Result availableListResult = apiInstance.getList(out availableHandle); 
availableList = ObjCRuntime.Runtime.GetNSObject<NSMutableArray>(availableHandle); 
if (availableListResult == Result.Success) 
{ 
System.Diagnostics.Debug.WriteLine("Success " + availableList);
 } `

But in .NET 8 if we call above method in MAUI SAMPLE APP the availableList will get Null , but not in .Net 7 (can get availableList ). Any solution for .Net 8 ?.  

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-macios#20236
