### ISSUE TITLE
[Bug] Unable to run either maui or maui blazor templates from the command line

### ISSUE THREAD

**Issue by rt121212121** [dotnet/maui#2099]
### Description

I am unable to run the WinUI version of these templates from Visual Studio due to other errors. I am also unable to run it on the command line.

### Steps to Reproduce

1. `dotnet new maui-blazor -n MauiBlazor`
2. `dotnet run MauiBlzor.WinUI -t:Run -f net6.0-windows10.0.19041`
3. Observe the following:

```
C:\Data\Git\_username\MauiBlzor\MauiBlzor.WinUI>dotnet run MauiBlzor.WinUI -t:Run -f net6.0-windows10.0.19041
The launch profile "(Default)" could not be applied.
A usable launch profile could not be located.
C:\Users\R\.nuget\packages\microsoft.projectreunion.winui\0.8.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(167,18): error MSB4086: A numeric comparison was attempted on "$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)" that evaluates to "" instead of a number, in condition "'$(AppxUseResourceIndexerApi)' == '' AND '$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)' < '6.3'". [C:\Data\Git\_username\MauiBlzor\MauiBlzor.WinUI\MauiBlzor.WinUI.csproj]

The build failed. Fix the build errors and run again.
```

### Expected Behavior

No idea but not this, presumably some window opens or something, angels sing and .. you fill in the rest.

### Actual Behavior

It displays the above error message.

### Basic Information

- Version with issue: 6.0.100-preview.7.21379.14? This is a fresh first install of MAUI via the new VS2022 preview.
- Last known good version: Never tried before
- IDE: Command line.
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: None
- Affected Devices: Windows 10 computer.

### Screenshots

Not a visual issue.

### Reproduction Link

Above in the listed steps.

### Workaround

No workaround. There are similar errors elsewhere but none of the solutions are things that apply here.

**Comment by Eilon** [comment]
Hi @rt121212121 , I think currently it's not supported to build, deploy, and run WinUI projects from the command line. It must be done from VS. In VS you can right-click on the WinUI projects and select "Deploy" and that will make the app appear in the Start Menu, and then you can run it from there.

**Comment by IceReaper** [comment]
Interesting wise, this registry key exists. So my guess would be that this is simply not properly resolved, resulting in "" instead of "6.3" which my registry holds. Wont install VS just for this, so ill wait for this to officially work, and continue to examine alternatives meanwhile.

**Comment by Eilon** [comment]
@IceReaper I'm not sure what the plans are for running WinUI apps from the command line, so for the foreseeable future I think that doing it from VS is the only supported way.

I'd like to understand the reasons for not wanting to install VS because maybe there's something that needs to be improved there.

**Comment by IceReaper** [comment]
Im working on windows at home at under linux in the office. Vs simply has no linux Version, so i use jetbrains rider as i dont want to switch IDEs constantly.

**Comment by Eilon** [comment]
Ah, yeah, no VS on Linux I can see how that's problematic. Hopefully the command-line experience gets better for WinUI projects, it's something I'd also love to see because it makes some scenarios easier even if you do have VS.

**Comment by Daniellled** [comment]
I hope this gets fixed soon. Our CICD pipeline is command line only. So that means we can only build and test locally in VS.

**Comment by Tealons** [comment]
Oh, wow. This will indeed be crucial when launching a MAUI to production. Doing this without our CI/CD flow is a no-go...

**Comment by shimingsg** [comment]
Verified Repro with Android 11, Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EYTfd_ImHYVDqL1thQa-_DcBUn3uLpxZo-xYAlG1RUKqZQ?e=tEs5s1

**Comment by jfversluis** [comment]
As per the condition that is in the csproj right now: `<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>` this will only work with msbuild at the moment.

I've tried `msbuild /restore /t:Build /p:TargetFramework=net6.0-windows10.0.19041 /p:Configuration=Debug /p:WindowsAppSDKSelfContained=true /p:Platform=x64` to build it first and you will need to add a x64 configuration yourself first and then `msbuild /restore /t:Run /p:TargetFramework=net6.0-windows10.0.19041 /p:Configuration=Debug /p:WindowsAppSDKSelfContained=true /p:Platform=x64` which does try to start it, but it still crashes unfortunately.

Just putting it here for future reference

**Comment by shimingsg** [comment]
attached the repro sample [2099.zip](https://github.com/dotnet/maui/files/8121266/2099.zip)

**Comment by Redth** [comment]
See these publishing issues for more info:

#4397 
#5399 
#4329 
#4377
