### ISSUE TITLE
.NET MAUI: It is not possible to clear focus from the entry control in Android versions equal to or below 8.1.

### ISSUE THREAD

**Issue by GV1072** [dotnet/maui#21009]
https://github.com/dotnet/maui/assets/115541611/f2fbc70e-73af-4bc6-bdc7-0abebd850fcd

### Description

1. The entry focus is not clearing even when the unfocused function is called. If two textboxes are present, the first textbox automatically receives focus.

2. This issue is only reproduced on Android versions equal to or below 8.1.

3. The problem persists in Xamarin.Forms; however, it works fine on both Android and iOS platforms.

4. According to the link provided below, the issue was supposed to be fixed but is still being reproduced in the latest version of .NET 8.

[Link: https://github.com/dotnet/maui/issues/3380](https://github.com/dotnet/maui/issues/3380)

Please investigate this matter, and I am hopeful for a resolution in the upcoming releases.

### Steps to Reproduce

1. Create .NET Maui application with latest version. i.e. .NET 8
2. Create one page, add two entry controls and one button.
3. Put the focus in entry1 and click on button (written entry1 unfocused code). 
4. Now observe the screen.

**Actual Result: -**
Both cursor focus and keyboard are maintained in the screen.

**Expected Result: -** 
Cursor focus should be cleared and keyboard will be closed.
[Android8.1UnfocusIssue.zip](https://github.com/dotnet/maui/files/14493790/Android8.1UnfocusIssue.zip)

### Link to public reproduction project repository

(https://github.com/dotnet/maui/files/14493790/Android8.1UnfocusIssue.zip)

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.3 GA

### Affected platforms

Android

### Affected platform versions

Android <=8.1

### Did you find any workaround?

No

**Comment by Domik234** [comment]
If I remember correctly - adding this to OnCreate method right after base.OnCreate() could fix the autofocus (not working unfocus) for Xamarin.Forms:
```
base.OnCreate(savedInstanceState);
Xamarin.Forms.Forms.SetFlags("Disable_Accessibility_Experimental"); //solved autofocus problem for Androidu 7/8
```

**Comment by PureWeen** [comment]
@GV1072 this is how Android works. Pre 8.1 it was impossible to unfocus everything, Android would always just change focus to the first control in the tree. After 8.1 they've enabled the ability to clear focus. 

We can't fix this, generally clearing focus is very hostile for accessibility so you should typically never do it.

**Comment by GV1072** [comment]
@PureWeen , thanks for the update. 
However, in Xamarin. Forms, we are not experiencing the auto-focus issue on the same platform (Android) and version (>= 8.1). Could you please explain the difference between Xamarin. Forms and .NET MAUI?
