### ISSUE TITLE
vs2022 preview3 don't has android simulator item to debug or run maui preview7

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#2101]
As you can see, no simulator item for choosing and while debug ,it will show the cli output windows.
![1](https://user-images.githubusercontent.com/16309962/129441774-fd07ad75-48dd-4a66-8157-a7638acbdc6f.png)
![2](https://user-images.githubusercontent.com/16309962/129441780-a81da9ba-1487-4295-9efc-bad30da85784.png)

**Comment by jingliancui** [comment]
What an interesting thing is it will use the maui preview 5 package.
And I have install the maui preview package.

![3](https://user-images.githubusercontent.com/16309962/129442312-ddda222d-4c04-45d4-8e30-b59b4939bd02.png)
![4](https://user-images.githubusercontent.com/16309962/129442326-3254dacd-01a1-4533-9f63-3448faefec81.png)

**Comment by campersau** [comment]
I had a similar issue. I installed https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17 and restarted the PC, after that the simulator menu items and also the Xamarin settings worked agian.

**Comment by jingliancui** [comment]
#40 is useful

**Comment by jingliancui** [comment]
I will try this later to see whether it can get some info.
https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=dotnet-cli

**Comment by jfversluis** [comment]
I've had this problem as well, eventually I found out that the workloads weren't properly installed. Try running `dotnet workload install maui` separately and see if that does anything.

**Comment by jingliancui** [comment]
> I had a similar issue. I installed https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17 and restarted the PC, after that the simulator menu items and also the Xamarin settings worked agian.

I try this solution but this doesn't work.

**Comment by jingliancui** [comment]
> I've had this problem as well, eventually I found out that the workloads weren't properly installed. Try running `dotnet workload install maui` separately and see if that does anything.

This isn't work , it will install rc1 and uninstall maui preview7.

**Comment by jfversluis** [comment]
> > I've had this problem as well, eventually I found out that the workloads weren't properly installed. Try running `dotnet workload install maui` separately and see if that does anything.
> 
> This isn't work , it will install rc1 and uninstall maui preview7.

Yeah I've been going back and forth with this one for a little as well. You might want to try the suggestion [here](https://github.com/Redth/dotnet-maui-check/issues/105#issuecomment-898295227), remove all metadata from the filesystem and install the things again.

**Comment by jingliancui** [comment]
> > > I've had this problem as well, eventually I found out that the workloads weren't properly installed. Try running `dotnet workload install maui` separately and see if that does anything.
> > 
> > 
> > This isn't work , it will install rc1 and uninstall maui preview7.
> 
> Yeah I've been going back and forth with this one for a little as well. You might want to try the suggestion [here](https://github.com/Redth/dotnet-maui-check/issues/105#issuecomment-898295227), remove all metadata from the filesystem and install the things again.

Thanks, I have try this ,but the suggestion is for installing the maui p7 , after do this steps , vs2022 still hasn't the android device option for choosing.

**Comment by jfversluis** [comment]
I think this is resolved in newer versions of the tooling. If you still have issues, feel free to open a new one, thanks!
