### ISSUE TITLE
[MAUI][.NET9] Clicking on any recipe page shows blank

### ISSUE THREAD

**Issue by Zhanglirong-Winnie** [dotnet/maui#21032]
### Description

Clicking on any recipe page shows blank in .NET 9 Preview 2

### Steps to Reproduce

1.Deploy https://github.com/rachelkang/recipeSearch to Windows/Android/iOS/MacOS
2.Click on any recipe

**Actual results:** 
Clicking on any recipe page shows blank
Recipe Search page:
![image (2)](https://github.com/dotnet/maui/assets/77434865/6282d24e-0bf0-490b-b1c3-6cd05adebcb6)

My Recipe page:
![image](https://github.com/dotnet/maui/assets/77434865/4a608082-35e9-4075-80ab-81b82732c3fc)
**Expected results:**
The page displays the recipe content normally

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch
.NET SDK: 9.0.100-preview.2.24129.7

### Version with bug

9.0.100-preview.2.24129.7

### Is this a regression from previous behavior?

Yes, this used to work in .NET 9 Preview1 MAUI

### Affected platforms

iOS, Android, Windows, macOS

**Comment by rmarinho** [comment]
The workaround would be to add you csproj:

`<MauiQueryPropertyAttributeSupport>true</MauiQueryPropertyAttributeSupport>`
