### ISSUE TITLE
Window11 cannot debug WinUI project in MAUI template [Bug] 

### ISSUE THREAD

**Issue by yangkaikai2014** [dotnet/maui#2104]
![image](https://user-images.githubusercontent.com/20454123/129447773-8cb59a1a-1c7d-4ea9-aa03-ba604c210e88.png)

**Comment by JanLoehr** [comment]
Can second that, I guess. Assuming this is the same error message in english. I discovered there are some errors in the referenced SDKs though I installed the correct workloads & maui-check doesn't show any errors :/

![image](https://user-images.githubusercontent.com/11177594/129485994-f3de17bf-987e-4fde-9f58-63eb28107759.png)

**Comment by yoshiask** [comment]
Can confirm, I get the same error with a fresh MAUI solution. I suspect this has something to do with `<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>`, the build output only has a DLL (not even an EXE).

**Comment by iamhazel** [comment]
I have the same problem. If @yoshiask is also running Windows 11 then we all have that in common.

**Comment by PaulSorauer-IPG** [comment]
Hey all

This is a known limitation with VS 2022 at present.

For more details you can look at the bottom of [David Ortinau's blog post detailing the Preview 7 release](https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-7/): 

> “At the time of release, we are troubleshooting the latest Windows App SDK [Single-project MSIX extension](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17) for Visual Studio 2022 and .NET MAUI to address a failure to debug. You can successfully deploy the Windows app directly and run it from the Start menu.”

Install the MSIX manually – then choose deploy on the WinUi project and it’ll install to your start menu. From there you can run it and presumably the debugger.

**Comment by jsuarezruiz** [comment]
Is a known limitation for now in VS 2022. Will be fixed in upcoming releases.

**Comment by Eilon** [comment]
I think safe to close this because it's a known issue that is fixed for upcoming releases and has a workaround right now.

**Comment by Eilon** [comment]
Oh and to anyone wondering how to debug:

* To debug an already-running app:
   1. Do a Deploy
   2. Launch the app from the Start Menu
   3. Once it's loaded you can attach the VS debugger "Attach to Process" and then set breakpoints, use watches, etc.
* To debug an app from startup:
   1.  Add the line `System.Diagnostics.Debugger.Launch();` to the first line of your app's startup code (in `Startup.cs`, or soon in `MauiProgram.cs`)
   2. Do a Deploy
   3. Launch the app from the Start Menu
   4. It will immediately ask you to pick a debugger. Pick the VS instance that has your project open
   5. Press the ▶ "Continue" button in VS to resume the app, and debug as usual

**Comment by PaulSorauer-IPG** [comment]
> * To debug an app from startup:

Gold
