### ISSUE TITLE
[Bug] Opening Shell Flyout with compressed jpg background image raises a Java.Lang.RuntimeException when targeting Android emulator

### ISSUE THREAD

**Issue by fernlance** [dotnet/maui#2105]
### Description
When setting a Shell's FlyoutBackgroundImage to a 'compressed' jpg, opening the menu causes the app to raise a Java.Lang.RuntimeException when targeting an android emulator

### Steps to Reproduce

1. Create new dotnet maui application using dotnet cli
2. Add a Shell to the project and set it up to be instantiated in App.xaml 
3. Add destination pages for the flyout items (in my case I created 2 flyout items mapping to 2 pages in the Pages folder)
4. Set the FlyoutBackgroundImage to a compressed jpg. (In my case I used a third party site tiny jpg dot com (not affiliated))

### Expected Behavior
Flyout opens showing image as background
### Actual Behavior
The following run time exception is thrown
Java.Lang.RuntimeException
  Message=Canvas: trying to use a recycled bitmap android.graphics.Bitmap@e721bc1

0xFFFFFFFFFFFFFFFF in Android.Runtime.JNIEnv.monodroid_debugger_unhandled_exception
0x33 in Android.Runtime.DynamicMethodNameCounter.41
0x17 in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
0x8E in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualBooleanMethod
0x65 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualBooleanMethod
0x70 in Android.Views.ViewGroup.DrawChild
0x4 in Microsoft.Maui.Controls.Platform.ShellFlyoutView.DrawChild
0x1C in Android.Views.ViewGroup.n_DrawChild_Landroid_graphics_Canvas_Landroid_view_View_J
0x23 in Android.Runtime.DynamicMethodNameCounter.41

[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
**Java.Lang.RuntimeException:** 'Canvas: trying to use a recycled bitmap android.graphics.Bitmap@e721bc1'

### Basic Information

- Version with issue:  .NET 6 Preview 6
- Last known good version: unknown
- IDE: Visual studio 2022 Preview Version 17.0.0 Preview 3.0
- Platform Target Frameworks: 
  - Android:  
- Android Support Library Version: 
- Affected Devices: Android emulator

### Screenshots

![image](https://user-images.githubusercontent.com/88331715/129458220-32d4bd0c-9830-4855-9f33-fd052a58abb5.png)

![image](https://user-images.githubusercontent.com/88331715/129458236-6b9f9cfb-0414-4bee-9556-4657ceccf068.png)

### Reproduction Link

https://github.com/fernlance/FlyoutBackgroundImageTest
### Workaround

Use uncompressed images

**Comment by PureWeen** [comment]
Ran this against the latest main branch of .NET MAUI and it looks like it loaded fine

![image](https://user-images.githubusercontent.com/5375137/140547894-6e7f62f4-5e67-41b5-960f-6f76c9dae23c.png)
