### ISSUE TITLE
iOS Publishing ignores bundle identifier and uses project name instead

### ISSUE THREAD

**Issue by BierDav** [dotnet/maui#21060]
### Description

This is a reopen of #4397, because the bug still persists and we need a fix or workaround asap, because we want to go to production next week and cannot, because the maui build system always overrides the bundle identifier in publishing.

I want to add that in debug mode, everything works fine, but as soon as you use publish it wildly starts ignoring/overwriting the values of the Info.plist.

### Steps to Reproduce

1. Create a maui project with ios support
2. Change the ApplicationTitle and change the bundle identifier in the Info.plist to some different random value
3. Try to debug and notice that on the Homescreen the name you put in the Info.plist shows up (optional)
4. Create an archive and look at the bundled Info.plist using a suited program as for example, you will see that neither the Application Title has been used nor the Info.plist and instead the project name was inserted as bundle identifier

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by RobFrancisAu** [comment]
Does something like this in your `.csproj` not work? 

```
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
        <ApplicationTitle>My Application Name</ApplicationTitle> <!-- CFBundleDisplayName -->
        <ApplicationId>com.my.bundleIdentifier</ApplicationId> <!-- CFBundleIdentifier -->
</PropertyGroup>
```

And remove `CFBundleDisplayName` and `CFBundleIdentifier` from your info.plist

**Comment by BierDav** [comment]
No it doesn't those not solve the issue because when i remove the lines from Info.plist it also falls back to the project name even in debug ... I think. I just know that it doesn't solve the issue, because i know that i have tried that before.

**Comment by jfversluis** [comment]
Can you maybe expand a little bit more, with screenshot or describing what the values is you are seeing in your project and how those do not line up with what you are seeing in the resulting info.plist? Please add as much info as you can, especially watch out for partial csproj snippets while the full contents might be more relevant because then we can see if there is something else that might be messing things up here.

Take us through the whole process of what you have configured in your project and how that ends up differently in your resulting binary.

**Comment by BierDav** [comment]
The reason why nobody noticed this, is because we have flavoured our app, so therefore we generate a new info.plist directly before the build. I will share more details hopefully today.

**Comment by BierDav** [comment]
I will provide more information on Monday or Thuesday

**Comment by BierDav** [comment]
You are correct!

The solution is to remove `CFBundleDisplayName` from the Info.plist. After that the ApplicationTitle is properly used.
