### ISSUE TITLE
[testing] TestTemplates RuniOS fails a lot on iOS 

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#21077]
### Description

We have an issue running the test templates stage where the simulators is a lot of times not found. we need to address this by making sure we create and start the simulator we need like we do on cake. 

Example:

https://dev.azure.com/xamarin/public/_build/results?buildId=110661&view=logs&s=119c6cfb-9e1c-5c22-f74d-222bbf71fff6&j=3b08a020-e7bc-549b-31e3-5dc38bbd06ff

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Relevant log output

```shell
/Users/builder/azdo/_work/3/s/src/TestUtils/src/Microsoft.Maui.IntegrationTests/AppleTemplateTests.cs(17): error VSTEST1: Microsoft.Maui.IntegrationTests.AppleTemplateTests.AppleTemplateSetup()   Failed to boot simulator with UDID '491595A5-EBC3-4605-9069-7D2E57E826B0'. [/Users/builder/azdo/_work/3/s/src/TestUtils/src/Microsoft.Maui.IntegrationTests/Microsoft.Maui.IntegrationTests.csproj]
```

**Comment by ivanpovazan** [comment]
@rmarinho did https://github.com/dotnet/maui/pull/20817 fix this issues so we could close it?

**Comment by ivanpovazan** [comment]
Closing as fixed by: https://github.com/dotnet/maui/pull/20817
