### ISSUE TITLE
[Bug] Unexpected layout with Grid

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#2107]
### Description

Something is happening with the grids, but I am not sure what I am supposed to expect. In the case, I have nested grids, with the inner one having a `1*` rows defined. The outer one has rows, and the inner grid is in an auto row, with a star row below.

So, during the measure, it is in the auto row of the outer grid (which means it can go to any size). When it gets to the inner grid with a `1*` row is basically skips the measure and uses the full space. That makes sense. There is a `1*` row, and it is asked to measure the size to fill the page.

However, since this grid is now in a grid that has a row as auto and there is a row below with star, I expected this to be an auto row.

Basically the logic to get this is valid, but not sure if it is correct.

We want it to be a star because if I have a grid that has nothing defined, I want the contents to expand to fill it. It is almost like the inner grid should fill to the screen size, except if it is in another container that wants the smallest size

Like, the logic in MeasureCells of the grid layout manager is correct: "I have XXX pixels to fill, give me your size". Is there a way to call measure, but then say "actually, this is the space available, but give me your smallest size".

### Steps to Reproduce

```xaml
    <Grid RowDefinitions="Auto,Auto,*,Auto" Padding="20" RowSpacing="10">
        <Label Text="Tests:" FontAttributes="Bold" />
        <GridLayout ColumnSpacing="10" ColumnDefinitions="*,Auto" Grid.Row="1">
            <Entry Placeholder="filter" Background="Red" />
            <Entry Placeholder="filter" WidthRequest="130" Grid.Column="1" Background="Green" />
        </GridLayout>
        <Label Text="Tests:" FontAttributes="Bold" GridLayout.Row="2" />
    </Grid>
```

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/1096616/129464590-1317fcc9-8ec8-49e2-9f79-4a2f620d578e.png)

### Workaround

Set the inner grid row to `Auto`.

**Comment by jsuarezruiz** [comment]
@hartez Could https://github.com/dotnet/maui/commit/df6fd4686d846551cca76d8a70ab83996db5c3f6 fixed this issue?
