### ISSUE TITLE
Debug start doesn't run the app, getting some errors

### ISSUE THREAD

**Issue by yoniaudi** [dotnet/maui#21084]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	APT2260	resource mipmap/appicon (aka com.companyname.mauiapp1:mipmap/appicon) not found.

This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.	MauiApp1	C:\Users\טם\source\repos\C# MAUI\C# MAUI Exploration\MauiApp1\MauiApp1\Platforms\Android\AndroidManifest.xml	1		

---------------------------------

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	APT2260	resource mipmap/appicon_round (aka com.companyname.mauiapp1:mipmap/appicon_round) not found.

This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.	MauiApp1	C:\Users\טם\source\repos\C# MAUI\C# MAUI Exploration\MauiApp1\MauiApp1\Platforms\Android\AndroidManifest.xml	1		

---------------------------------

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	APT2067	failed processing manifest.
	MauiApp1	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.43\tools\Xamarin.Android.Aapt2.targets	214

**Comment by samhouts** [comment]
[FeedbackTicket 2004811:](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2004811) Android mipmap/appicon failing with "APT2260 resource mipmap/appicon (aka xxx:mipmap/appicon) not found."

**Comment by voroninp** [comment]
@samhouts , unfortunately, that ticket in Azure DevOps is not accessible. Would be nice to track it ;-)

**Comment by samhouts** [comment]
Sorry about that! The link is https://developercommunity.visualstudio.com/t/Android-mipmapappicon-failing-with-APT/10622494. Thanks!
