### ISSUE TITLE
AOT + Trim - Could not resolve type with token 01000005 from typeref

### ISSUE THREAD

**Issue by UkeHa** [dotnet/maui#21082]
### Description

When i enable AOT and Trim in my project i run into this error. Disabling both options let the app run as intended. All projects inside the solution are on .net8 and bin/obj folders have been deleted to force rebuild. How do i fix this?

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

no

### Relevant log output

```shell
'Could not resolve type with token 01000005 from typeref (expected class 'System.Runtime.CompilerServices.InternalsVisibleToAttribute' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')'
```

**Comment by drasticactions** [comment]
The short answer is that MAUI (The UI Framework) is currently not NativeAOT friendly. It's being tracked for [.NET 9](https://github.com/dotnet/maui/issues/18658). Currently, AFAIK, the only platform that could "fully" support compiling with NativeAOT would be Apple platforms (iOS/Mac Catalyst, etc). WinUI doesn't support NativeAOT and Android currently supports it for native code, but with no Java interop.
