### ISSUE TITLE
SearchBar crashes on iOS 17.4

### ISSUE THREAD

**Issue by UnusualJustin** [dotnet/maui#21085]
### Description

On iOS 17.4, the SearchBar will crash the app if a user selects it. 

### Link to public reproduction project repository

https://github.com/UnusualJustin/SearchBarCrashesOniOS

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.4

### Did you find any workaround?

No

**Comment by askman92** [comment]
This also occurs with the entry control

**Comment by letscodewithkalyan** [comment]
@askman92 @UnusualJustin 
Check out below links
https://github.com/dotnet/maui/issues/21051
https://github.com/dotnet/runtime/issues/98941

**Comment by jfversluis** [comment]
As mentioned indeed, see linked issues, this should be resolved when we have official Xcode 15.3 support.
