### ISSUE TITLE
MAUI projects with an ampersand in the name can't be built or loaded

### ISSUE THREAD

**Issue by MSLukeWest** [dotnet/maui#21090]
### Description

If I create a project with a name like "foo&bar" I'm unable to build it from the command line or open it in Visual Studio.  Other types on .NET projects don't seem to have this issue.

### Steps to Reproduce

1. Open dev command prompt, run:

`dotnet new maui --name "foo&bar"`

2. cd to "foo&bar"
3. dotnet build

Result: Fails with:

`error MSB4025: The project file could not be loaded. An error occurred whi
le parsing EntityName. Line 24, position 25.`

The line it's complaining about is the following (position number given is the one after the ampersand):

`<ApplicationTitle>Foo&Bar</ApplicationTitle>`

A potential fix is to use a different token here: https://github.com/dotnet/maui/blob/7639a2cf24ac3e5a17a08fc1eb0103883659d57d/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj#L24

Note: You'll get a similar error if you try to load the project in Visual Studio:

![image](https://github.com/dotnet/maui/assets/42553283/53404974-3b85-4f17-9640-0cc0d51e8249)

 

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Did you find any workaround?

Don't use an ampersand in project names

**Comment by jfversluis** [comment]
I think this will boil down to restrictions on the underlaying platforms. I'm pretty sure that iOS and/or Android will not allow such characters as well in their application names. Having that said, we can still make our code a little better in this regard to at least notify the user or just filter out characters.

As a "fix" right now I would just recommend to stick with only letters and numbers.

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2. Can repro it when creating project named with special characters.
![image](https://github.com/dotnet/maui/assets/128687574/f9f8c2b6-ea09-458a-aee0-e96e04bb9bbe)
