### ISSUE TITLE
[Android] MAUI 8.0.3 -> 8.0.6 regression: custom handler with key listener no longer works

### ISSUE THREAD

**Issue by ysbakker** [dotnet/maui#21109]
## Some context

Localization of numeric keyboards on Android can be pretty confusing, so we wrote a workaround (loosely based on [this solution](https://developercommunity.visualstudio.com/t/Numeric-Entry-uses-wrong-decimal-separat/10453006#T-N10453010)) that allows the user to both use a period and a comma as a decimal separator. We added some logic to always translate the separator to the expected one, and an Android handler which adds a key listener to the Entry view that allows the user to enter both a '.' and a ','.

Handler:
```cs
public partial class DecimalEntryHandler : EntryHandler
{
    public DecimalEntryHandler()
    {
        Mapper.AppendToMapping(nameof(IEntry.Keyboard), SetKeyboard);
    }
}
```

Android handler:
```cs
public partial class DecimalEntryHandler
{
    private static void SetKeyboard(IEntryHandler handler, IEntry entry)
    {
        handler.PlatformView.KeyListener = new NumericKeyListener(handler.PlatformView.InputType);
    }
}
```

NumericKeyListener:
```cs
public class NumericKeyListener : NumberKeyListener
{
    public override InputTypes InputType { get; }
    protected override char[] GetAcceptedChars() => "0123456789-,.".ToCharArray();

    public NumericKeyListener(InputTypes inputType)
    {
        InputType = inputType;
    }

    public override bool OnKeyDown(global::Android.Views.View? view, IEditable? content, Keycode keyCode, KeyEvent? e)
    {
        Application.Current.MainPage.DisplayAlert("OnKeyDown", string.Empty, "OK");
        return base.OnKeyDown(view, content, keyCode, e);
    }
}
```

## The problem

The key listener no longer works in MAUI 8.0.6. The handler is registered, and the key listener is also added to the view. The breakpoint is hit in the `NumericKeyListener` constructor. But it no longer gets used. This results in the user only being able to enter their localized decimal separator.

I made a reproducible example here: https://github.com/ysbakker/MauiAndroidKeyboardIssueReproduction

You can test this by changing the SDK in the `global.json` to either `8.0.100` (working) or `8.0.201` (not working) and running `dotnet workload restore` if you do not have that MAUI version. A dialog should show up whenever you press a button, which doesn't happen on the latter SDK version.

What could be causing this?

### Steps to Reproduce

1. Run the attached project in MAUI 8.0.6
2. Note that the dialog does not show up when pressing a key
3. Note that it does show up in MAUI 8.0.3

### Link to public reproduction project repository

https://github.com/ysbakker/MauiAndroidKeyboardIssueReproduction

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

Android

### Did you find any workaround?

No. But do let me know if you have a different solution for the numeric input.

**Comment by naaeef** [comment]
I found a workaround for the issue.
The issue was introduced with the following change: https://github.com/dotnet/maui/commit/55ed1ea28148f1ae4642873be51fc2cd094a4ac9

There is now a method OnViewAttachedToWindow, this triggers UpdateReturnType and that overwriting the KeyListener. To fix this you can register your own ViewAttachedToWindow listener that sets the KeyListener.

**Comment by david-d-le** [comment]
I have combined temporary workaround proposed by @naaeef and some code from issue #17152 and commit https://github.com/dotnet/maui/commit/55ed1ea28148f1ae4642873be51fc2cd094a4ac9
I have used `NumericKeyListener` from question here but I don't know much about how it works or if there is any difference with `DigitsKeyListener` regarding to **InputType**.

Hopefully there will be permanent fix soon because writing decimal numbers is crucial for my app and can't downgrade due to other fix in Maui CommunityToolkit...

```csharp
Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("NumericEntryHack", (handler, entry) =>
    {
        if (entry.Keyboard == Keyboard.Numeric)
        {
            handler.PlatformView.ViewAttachedToWindow += (object? sender, ViewAttachedToWindowEventArgs e) =>
            {
                handler.PlatformView.KeyListener = new NumericKeyListener(handler.PlatformView.InputType);
                //handler.PlatformView.KeyListener = DigitsKeyListener.GetInstance("0123456789-,.");
                handler.PlatformView.ImeOptions = entry.ReturnType.ToPlatform();
            };
        }
    });
```

**Comment by MPoels** [comment]
I can confirm this solution works, thanks David. I'm now able to set a text handler that replaces the '.' from the  samsung numeric keyboard ignoring localization of the phone into a ',' when the localization requires so. I will share my handler code.  At this might help others. You need to restore the cursor when altering the text. This is now working on samsung phones for entering numeric decimal values. 

```
namespace ShowPrices.Custom
{
	public sealed partial class CustomEntryHandler : EntryHandler
	{
		protected override AppCompatEditText CreatePlatformView()
		{
			var native = base.CreatePlatformView();
			native.BackgroundTintList = Android.Content.Res.ColorStateList.ValueOf(Colors.Transparent.ToAndroid());
			native.KeyListener = new NumericKeyListener(Android.Text.InputTypes.ClassNumber);
			return native;
		}

		protected override void DisconnectHandler(AppCompatEditText platformView)
		{
			base.DisconnectHandler(platformView);
		}

		internal void HandleControlActions(CustomEntry entry)
		{
			if (PlatformView.InputType.HasFlag(Android.Text.InputTypes.ClassNumber))
			{
				PlatformView.ViewAttachedToWindow += (object? sender, Android.Views.View.ViewAttachedToWindowEventArgs e) =>
				{
					PlatformView.KeyListener = new NumericKeyListener(PlatformView.InputType);
					PlatformView.ImeOptions = entry.ReturnType.ToPlatform();
				};
			}

			PlatformView.SetTextSize(Android.Util.ComplexUnitType.Px, (float)entry.FontSize);

			switch (entry.HorizontalTextAlignment)
			{
				case TextAlignment.Start:
					PlatformView.Gravity = GravityFlags.Start;
					break;

				case TextAlignment.End:
					PlatformView.Gravity = GravityFlags.End;
					break;

				case TextAlignment.Center:
					PlatformView.Gravity = GravityFlags.Center;
					break;
			};
		}

		internal void HandleTextActions(CustomEntry entry)
		{
			// Samsung phones workaround
			if (
				(CultureInfo.CurrentCulture.TwoLetterISOLanguageName.Equals("nl") ||
				CultureInfo.CurrentCulture.TwoLetterISOLanguageName.Equals("fr") ||
				CultureInfo.CurrentCulture.TwoLetterISOLanguageName.Equals("de")) &&
				PlatformView.Text != null)
			{
				var newString = PlatformView.Text.Replace(".", ",");
				if (newString != PlatformView.Text)
				{
					int cursorPos = PlatformView.SelectionStart;
					PlatformView.Text = newString;
					PlatformView.SetSelection(cursorPos);
				}		
			}
		}
	}
}
```

The parent code:
```
namespace ShowPrices.Custom
{
	public sealed partial class CustomEntryHandler : EntryHandler
	{
#if ANDROID || IOS
		public CustomEntryHandler()
		{
			Mapper.AppendToMapping("CustomEntryCustomization", MapCustomEntry);
			Mapper.AppendToMapping("Text", MapCustomText);
		}

		private void MapCustomEntry(IEntryHandler handler, IEntry entry)
		{
			if (entry is CustomEntry customEntry)
			{
				try
				{
					if (PlatformView is not null && VirtualView is not null)
					{
						HandleControlActions(customEntry);
					}
				}
				catch
				{ }
			}
		}

		private void MapCustomText(IEntryHandler handler, IEntry entry)
		{
			if (entry is CustomEntry customEntry)
			{
				try
				{
					if (PlatformView is not null && VirtualView is not null)
					{
						HandleTextActions(customEntry);
					}
				}
				catch
				{ }
			}
		}
#else
		public CustomEntryHandler()
		{
		}
#endif
	}
}
```

And the numeric keylistener
```
using Android.Text;
using Android.Text.Method;

namespace ShowPrices.Custom
{
	class NumericKeyListener : NumberKeyListener
	{
		public override InputTypes InputType { get; }
		protected override char[] GetAcceptedChars() => "0123456789-,.".ToCharArray();

		public NumericKeyListener(InputTypes inputType)
		{
			InputType = inputType;
		}
	}
}
```
