### ISSUE TITLE
Xamalicious malware in Maui!?

### ISSUE THREAD

**Issue by Dumuzy** [dotnet/maui#21117]
### Description

I have built a Maui App apk with VS 2022 17.8.5 and put it to my website some weeks ago. Not yet to the playstore as it is not finished fully. Yesterday my website has been shut down by my provider and he states, the apk is malware. Further details say it is infected by "Android Xamalicious payload". My research led to "Android Xamalicious payload" being part of Xamarin and such probably part of Maui.  What should I do?

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by GalaxiaGuy** [comment]
Xamalicious is not part of Xamarin, it is "an Android backdoor implemented with Xamarin".

https://www.mcafee.com/blogs/other-blogs/mcafee-labs/stealth-backdoor-android-xamalicious-actively-infecting-devices/

Either your app is genuinely including it (possibly via a third party library if you know nothing about it), or your app is being detected as a false positive. It's also possible your host has misunderstood the malware and believes all Xamarin code is the malware.

**Comment by Dumuzy** [comment]
VirusTotal says the app is malware free.

**Comment by jfversluis** [comment]
As already mentioned, this malware is not part of Xamarin nor MAUI, but this malware is built to target Xamarin (and will probably also still work on .NET MAUI).

The linked article provides a pretty extensive explanation of how it operates. Especially under **Where is the malicious code?** it might be interesting for you to check if your APK has any of these malicious files. An APK file is just a zip so rename it to .zip and you will be able to inspect the contents. The results are probably predictable as your provider already established the payload is there. Another option as pointed out is that it's a false positive. Did you get any details from your provider as to why they think this malware is in your app? Or maybe you can ask for clarification on this?

Assuming your app is indeed infected, the bigger question is: where does it come from? Are you using any third-party libraries? Do you have a list maybe so we can have a look and which can maybe serve as a warning for others?

**Comment by Dumuzy** [comment]
Thank you all for your help. My provider in between has also concluded that this was a false positive and has re-enabled my site. It might be interesting that the false positive was reported by a company called Netcraft.

**Comment by jfversluis** [comment]
Thanks for letting us know! Glad it was resolved like this!
