### ISSUE TITLE
Flyout menu overlaps with title bar since .Net8

### ISSUE THREAD

**Issue by ChrisAtVault** [dotnet/maui#21127]
### Description

In .Net 7 the flyout menu was below the title bar.
![grafik](https://github.com/dotnet/maui/assets/79156810/23f5935c-9682-4d6f-ba55-91f730a9defc)
After changing to .Net 8 the flyout menu reaches into the title bar.
![grafik](https://github.com/dotnet/maui/assets/79156810/333b72d5-0d40-408d-847e-987f9431a80b)

### Steps to Reproduce

Simply add a Flyout

```xaml
<Shell
    x:Class="FlyoutTestNet7.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:FlyoutTestNet7"
    Shell.FlyoutBehavior="Flyout">

    <ShellContent
        Title="Home"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" />

    <ShellContent Title="Selection"/>

    <ShellContent Title="Input"/>
</Shell>
```

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

Windows

**Comment by QianaJiao** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 1. Can repro on Windows platform.

**Comment by mattleibow** [comment]
does this happen in a plain WinUI app? .NET 8 updated the Windows App SDK to a later version and they reworked the entire title bar.

In the new version you can see the shadow and rounded corners of the flyout. This feels like they made a feature change.

**Comment by mhrastegari** [comment]
This got a way better look!
It's not a bug it's a feature!!! 😅
