### ISSUE TITLE
[Bug] Can't run Maui.WinUI

### ISSUE THREAD

**Issue by Thuyen21** [dotnet/maui#2113]
### Steps to Reproduce

1. I use Maui-Blazor
1. @inject NavigationManager _navigationManager
2.  _navigationManager.NavigateTo("/", true);  It Error

1. Can't Run MauiApp.WinUI

### Expected Behavior
Use  _navigationManager.NavigateTo("/", true) working
Run WinUI

### Actual Behavior
Maybe use  _navigationManager.NavigateTo("/", true)  error not working
Can't run WinUI

### Basic Information

- Version with issue: Maui-Blazor Preview 7
- IDE: Visual Studio 2022
- Platform Target Frameworks: 
  - Android: 11 
 
- Nuget Packages: Microsoft.AspNetCore.Components.Authorization
- Affected Devices: All
 
![2021-08-15 (1)](https://user-images.githubusercontent.com/65522631/129483210-73ce7d5b-878d-4868-81c4-228a82c884d0.png)

**Comment by taozuhong** [comment]
Met the same trouble.

iOS and MacCatalyst could stay together, why not windows(WinUI)?

**Comment by Eilon** [comment]
Hi @Thuyen21 what error did you get with this step?

> 3. _navigationManager.NavigateTo("/", true); It Error

**Comment by iamhazel** [comment]
For what it's worth, I get the same error on brand new projects. Haven't found a way around it yet.

**Comment by Thuyen21** [comment]
@Eilon 
May be in maui blazor it only have _navigationManager.NavigateTo("/");

Step
1. @inject NavigationManager _navigationManager
2. _navigationManager.NavigateTo("/", true);
3. It just show like this

![2021-08-17 (1)](https://user-images.githubusercontent.com/65522631/129649486-d618242c-295e-43e8-bb50-757cb310cce6.png)

**Comment by Thuyen21** [comment]
@Eilon 
Another thing with Visual Studio 2022 preview 3, sometimes when I start the Maui project, it freezes. I must use Task Manager to end Visual Studio, then keep doing the start project and end tasks 3 - 4 times. Then Visual Studio can be used normally.
