### ISSUE TITLE
Infinite ANR loop in MAUI UI with Android 13

### ISSUE THREAD

**Issue by WMLPB** [dotnet/maui#21130]
### Description

Hi all,

we developed an inhouse logistics app in Xamarin Forms for our Android based barcode scanners and ported it to MAUI recently. Those barcode scanners are usually quite expensive but low on processor power and RAM. Our older devices used to run on older versions of Android, now we got the first barcode scanners with Android 13.

On those new devices I suddenly get an "Application is not responding" ANR message by just using the UI. _Important:_ We do no work on the UI-Thread, we load our data with Tasks. The ANR happens on MAUIs side, as far as I can tell. I discovered two main scenarios so far – creating a new Page and scrolling the CollectionView:

`var page = new SettingsPage();`

This SettingsPage _has got no code behind_, but more than 20 controls on it – Labels, Checkboxes and RadioButtons. _It is just XAML with data binding._ So I guess, the ARN must happen in `InitializeComponent()`. And: I can circumvent this ANR by creating all my Pages at application startup – inside the constructor of `MainPage.xaml.cs` – and then just navigating to them with `Navigation.PushAsync(settingsPage)`.

For the second scenario I do not have any workaround. The CollectionView is very laggy when scrolling. It is just a list with a few hundred items – an Image and a Label. The CollectionView hangs after scrolling up / down for five or six items and the ANR shows up.

_And now comes the very annoying part_ – probably a bug by Google in Android 13, but I don’t know:  After the first ANR shows up, I get following ANRs every five seconds. I can click "Wait" as often as I want, the next ANR is five seconds away. There is no way to stop those ANRs – only to click on "Close App".  So – after the first ANR shows up, our users have to close the app and restart it – only to get the next infinite ANR loop just by scrolling the CollectionView.

What can I do? We start a new project for a big international customer soon, we need to order new devices and we need our app working urgently. Please – do not put this issue on your backlog! And I'm sorry, I can't create a repository to reproduce this issue.

Thank you very much for help.

### Steps to Reproduce

1. Create a new Page
2. Scroll the CollectionView

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by Vroomer** [comment]
Does it happen in release mode without debugger? ANR is common behavior during debugging (including consecutive warnings every few seconds) and can be disabled: https://stackoverflow.com/questions/33111495/disable-anr-messages-while-debugging. 

Is it device specific?

Slow CollectionView sounds also a lot like a behavior of debug mode as there is Interpreter doing extra work for Hot Reload.

Furthermore you mention that you load data in Tasks, but async Task doesn't prevent the work to be done on UI-Thread. It just prevents UI-Thread to be blocked during I/O operations. You have to specifically Run CPU heavy tasks on ThreadPool.

As for the release mode performance, CollectionView can be greatly optimized by following:
- Set height of ItemTemplate to be fixed and set CollectionView mode to measure only first item.
- Make ItemTemplate layout as flat as possible (no nesting).
- Don't use "Auto" in Grid and try to keep Heights fixed.
- Always use compiled bindings.
- Try to stay away from Converters and OneWay/TwoWay Bindings.
- Make sure CollectionView has or inherits fixed size. Don't nest CollectionView in ScrollView.

**Comment by Vroomer** [comment]
If the third party CollectionView works for you, maybe it's an issue with virtualization of MAUI CollectionView or just different recycling strategy that is more CPU/memory intense. If you are interested, there is an experimental alternative to CollectionView that you can customize and play with: https://github.com/Redth/Maui.VirtualListView - it's made by Redth, the Engineering Lead Principal of MAUI.

**Comment by PureWeen** [comment]
@WMLPB this might help
https://learn.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows

But I don't know if we'll be able to do much with a repro. 

We have some fixes coming in SR4 that might help?

**Comment by PureWeen** [comment]
This might be resolved by
https://github.com/dotnet/maui/pull/22347

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds
