### ISSUE TITLE
Memory raising when using flyout navigation

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#21147]
### Description

Memory raising when using flyout navigation

### Steps to Reproduce

1. I attached sample code.
2. Go to task manager and see the memory usage when:
-move to page 1 => click on move to page 2
-move to page 1 => click on refresh current page.
-move to page 1 => drill down to details page.
-move to page 2
[FlyoutExample.zip](https://github.com/dotnet/maui/files/14572326/FlyoutExample.zip)

move to page 3

### Link to public reproduction project repository

...

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

No

### Relevant log output

```shell
NO
```

**Comment by mattleibow** [comment]
@jonathanpeppers thoughts?

**Comment by jonathanpeppers** [comment]
@danies8 are you testing this in `Debug` mode? If so, do you have XAML Hot Reload disabled?

They mention turning it off here:

* https://learn.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload-impact-performance?view=vs-2022

On Windows, you should be able to take memory snapshots to understand what object is leaking (if any). While testing this, I'd also recommend temporarily puttings some `GC.Collect()` calls to make it more deterministic:

* https://github.com/dotnet/maui/wiki/Memory-Leaks#determining-if-there-is-a-leak-or-not

**Comment by danies8** [comment]
I disabled Xaml Hot Reload.
Also added GC.Coolect().
Still memory increase on every click on new page.

**Comment by jonathanpeppers** [comment]
@ninachen03 can you attach some of those files in your screenshot next time? Thanks!

In the meantime, I'll try testing myself.

**Comment by jonathanpeppers** [comment]
I put `GC.Collect()` at the beginning of every click event in the side menu: `OnClickedDashboard`, `OnClickedRoutes`, `OnClickedSettings`.

I have XAML hot reload disabled, and I'm not seeing a leak:

![image](https://github.com/dotnet/maui/assets/840039/54d8c7ba-9970-49b7-a060-bdea722e7d37)

The memory goes up on page 1, as there are more controls on it. But it goes down when loading page 2 or 3.

**Comment by danies8** [comment]
@jonathanpeppers 
Thanks for answer.
Does you answer is also same when navigating to page 1 and there are two buttons on it:
Navigate to page or refresh the page.

**Comment by jonathanpeppers** [comment]
@danies8 does the problem occur if I just click refresh on page 1 over and over? (I'd also put a `GC.Collect()` call in there)

We should narrow down the repro steps, or figure out which control is causing this.

**Comment by danies8** [comment]
@jonathanpeppers 
Please navigating to page 1 and there are two buttons on it:
Navigate to page 2 or refresh the page1 or also drill down to details page.
Can you please check if there are no leak memory in these cases?
Does I can use this navigation safely without problem of leak memory?

**Comment by jonathanpeppers** [comment]
I tried using the "Refresh Current page 1" over and over, and here is what I observed.

1. Multiple `RoutesPage` objects will remain in memory for a bit
2. `RoutesPage` instances cap out at 4

![image](https://github.com/dotnet/maui/assets/840039/54614b6b-1fbe-4af9-89bd-7828efb9545c)

4. At this point memory is stable:

![image](https://github.com/dotnet/maui/assets/840039/8ffe15bd-52ca-4984-840e-9fd69b7fdb3b)

I don't see anything wrong here, but it seems like it takes multiple GCs for `RoutesPage` instances to completely go away. I think this makes sense as WindowsAppSDK objects are C# wrappers around native controls.

@danies8 if you click on an individual snapshot, do you see a specific object that it's count goes up and up? That would indicate something is wrong here.

**Comment by danies8** [comment]
I added GC.Collect(); in each page's OnDisappearing method. 
And I test it in debug mode, when I navigate to other pages (page1 -》page2->page3) Memory will not raising continuously. is it ?

protected override void OnDisappearing()
{
     base.OnDisappearing();

     GC.Collect();
}

**Comment by danies8** [comment]
Is it good practice?

**Comment by jonathanpeppers** [comment]
No, only add the `GC.Collect()` calls if you are debugging a memory leak (and remove when finished). We tried to mention this here:

* https://github.com/dotnet/maui/wiki/Memory-Leaks#determining-if-there-is-a-leak-or-not

**Comment by danies8** [comment]
Ok

**Comment by danies8** [comment]
@jonathanpeppers
if you leave this app open after login and don't touch for few hours  and later navigate to a new page it crached , why ?

**Comment by jonathanpeppers** [comment]
Can you share the exception message? or more information about your crash?

**Comment by danies8** [comment]
Faulting application name: XXXXXXX, version: 1.0.0.0, time stamp: 0x65680000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1387, time stamp: 0x0b9a844a
Exception code: **0xc000027b**
Fault offset: 0x000000000010b302
Faulting process id: 0x30c0
Faulting application start time: 0x01da802338803cbe
Faulting application path: XXXXXXXXXX
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 06ccce96-ab0d-447e-bace-eeb686ce73c8
Faulting package full name: 
Faulting package-relative application ID:

**Comment by jonathanpeppers** [comment]
Are you able to get the C# (.NET) stack trace?

I found some examples of that error code, but it doesn't point to a memory issue:

* https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/microsoft-store-apps-fail-to-start#issue-2
* https://github.com/microsoft/WindowsAppSDK/issues/1020

**Comment by danies8** [comment]
I ran this app in publish mode as exe and it crached.
1.How I can get the C# (.NET) stack trace?
2.What does exception code : 0xc000027b mean ?

**Comment by danies8** [comment]
3.
- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-04-09T08:20:22.7150355Z 
 
   EventRecordID 189929 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  0 
   [ ThreadID]  0 
 
   Channel Application 
 
   Computer XXXXXXX 
 
   Security 
 

- EventData 

   XXXXXXX.exe 
   1.0.0.0 
   65680000 
   KERNELBASE.dll 
   10.0.19041.2364 
   5b7d4d22 
   c000027b 
   000000000010fe32 
   5980 
   01da8a4dc8b3710b 
   C:\Users\danis\Desktop\Version_1_0_1_7\XXXXXX\Client\net8.0-windows10.0.19041.0\win10-x64\XXXXXX.exe 
   C:\Windows\System32\KERNELBASE.dll 
   7e120551-cc92-4cca-af4b-5491e4ab8639

**Comment by danies8** [comment]
I also refer to: https://answers.microsoft.com/en-us/windows/forum/all/faulting-module-name-kernelbasedll/d5a7b008-eb11-4e9e-ab5f-63016fe760d9
Now on my machine i run Run compatibility troubleshooter. and this the results what does it mean.
I'm using vs 17.8.4
What does it maen?
![image](https://github.com/dotnet/maui/assets/1079689/37b3282a-03ab-4ddf-b925-1f84ec1ae712)
