### ISSUE TITLE
MAUI Windows application not navigating when app not in focus.

### ISSUE THREAD

**Issue by Kbmobi** [dotnet/maui#21158]
### Description

If you lose focus of the application in Windows, the app will not navigate. 

### Steps to Reproduce

- Launch Windows
- Click the button
- lose focus of the window before the navigation occurs
- the application will not navigate
- do the same action and keep focus of the window
- the app will navigate

### Link to public reproduction project repository

https://github.com/Kbmobi/MauiBugSleepNavIssue

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

No! :(

**Comment by Veilenus** [comment]
This bug affects my team as well.

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 2.0(8.0.14). Repro on Windows 11, not repro on MacCatalyst with Project:
[MauiBugSleepNavIssue.zip](https://github.com/dotnet/maui/files/14912657/MauiBugSleepNavIssue.zip)

**Comment by Veilenus** [comment]
Possibly related to #18982.

**Comment by Kbmobi** [comment]
Yes, this is a duplicate of that issue, I didn't see it come up when I was searching for a solution. Thankfully 3 weeks ago someone posted a workaround solution.

https://github.com/dotnet/maui/issues/18982#issuecomment-2021195256

Hopefully they fix this issue soon.
