### ISSUE TITLE
Text of Shell MenuItem not visible in ReleaseMode on Android

### ISSUE THREAD

**Issue by Niek42** [dotnet/maui#21155]
### Description

I have several <MenuItem>'s in my AppShell like this

   ```
<MenuItem Clicked="ShowUserDetails_Clicked" Text="{x:Static res:Strings.Account}">
        <MenuItem.IconImageSource>
            <FontImageSource
                FontFamily="IconFont"
                Glyph="{x:Static helpers1:IconFont.Account}"
                Color="{AppThemeBinding Light={StaticResource 4AGray},
                                        Dark={StaticResource White}}" />
        </MenuItem.IconImageSource>
    </MenuItem>
```
Those MenuItems are perfectly rendered on iOS emulators and devices in debug and release mode. They are also fine on Android emulators and devices in debug mode, but NOT in release mode.
In release mode only the icons are visible.
This issue did not occur in previous VS2022 version. My current VS2002 version = '17.9.2'

This is in debug mode:
![image](https://github.com/dotnet/maui/assets/81151186/dffb8770-a33a-4666-bad7-cc1adc6246f9)

This is in release mode:
![image](https://github.com/dotnet/maui/assets/81151186/6aa8448e-4eae-4fe2-8b87-1d6a6ec63771)

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

Android

### Affected platform versions

android    34.0.52/8.0.100        VS 17.9.34622.214

**Comment by mattleibow** [comment]
Can you try putting text directly into XAML as a test? I am wondering if for some reason the static fields are being removed.

**Comment by Niek42** [comment]
> Can you try putting text directly into XAML as a test? I am wondering if for some reason the static fields are being removed.

I tried that, but that didn't help.

**Comment by jaosnz-rep** [comment]
Verified on VS 17.10.0 Preview 2.0 (8.0.7) , cannot repro on .NET 8.0 Android Platform, it displays normally in both release and debug modes.
