### ISSUE TITLE
Finished creating package, but nothing package found

### ISSUE THREAD

**Issue by xiaoxstz** [dotnet/maui#21153]
### Description

I cannot publish MAUI to local folder. But the message windows say "Finished creating package"

### Steps to Reproduce

1. Create a new MAUI project with Visual Studio 2022
2. Unchecked other target platform except `Target the Windows platform`
3. Edit the project file to ensure `TargetFrameworks` only contains a single available framework for windows
```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks></TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
...
```
4. Update all the Nuget packages to latest version(`Microsoft.Maui.Controls`: 8.0.7，`Microsoft.Maui.Controls.Compatibility`:8.0.7)
5. Select Release Platform. And then build
6. Publish step by step [here](https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-visual-studio-folder?view=net-maui-8.0)

Then I see the result blow. It seems successful, but no package is generated. Moreover, the `Output location` not exist at all! (no `AppPackages` folder)

![image](https://github.com/dotnet/maui/assets/81862747/4c24bab5-43a1-4a3c-9b08-ee594d0978f4)

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by mattleibow** [comment]
Does this work on the CLI? https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-8.0

**Comment by xiaoxstz** [comment]
> Does this work on the CLI? https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-8.0

Yes. I tried this just now. It works. Thank you.

**Comment by xiaoxstz** [comment]
I found the key point.

**Publishing with CLI always works.**  The command is below

```cmd
dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64
```

**If we want to publish with Visual Studio**, we **cannot** change the **first** `<TargetFrameworks>` configuration in the project file.

* The configuration can be changed in Project's Property Window `; or edit the **first** `<TargetFrameworks>`  in the project file directly

![image](https://github.com/dotnet/maui/assets/81862747/9a7f6d47-d9a1-4a09-9a0f-e89716439885)

* If it's set to nothing (`<TargetFrameworks></TargetFrameworks>`), VS will tell you "Finished creating package" (published successful), but nothing package is generated.
* If any `Target the xxx platform` is unchecked, you will come across the error below. I think it's a Visual Studio stupid bug, why not find `MauiApp1.dll` in `Release\net8.0-maccatalyst\maccatalyst-x64`?
  > Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	NU5026	The file 'D:\Desktop\Projects\MauiAppAOT\MauiApp1\bin\Release\net8.0-maccatalyst\MauiApp1.dll' to be packed was not found on disk.	MauiApp1	C:\Program Files\dotnet\sdk\8.0.200\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets	221	
* If you delete `net8.0-maccatalyst` in the first `<TargetFrameworks>`，publishing will behave like build.

**Comment by xiaoxstz** [comment]
My conclusion: **Visual Studio is not mature for MAUI (at least publishing). If you come across some odd issue, try using command line(CLI)**
