### ISSUE TITLE
UNABLE TO UPDATE SPLASH SCREEN - iOS - Local Dv

### ISSUE THREAD

**Issue by RobDaytona** [dotnet/maui#21154]
### Description

Hi! I have been stuck for hours on something seemingly so simple....
All I need to do is change the splash screen to a jpg file on a brand new Maui App and deploy it using hot restart to a local iOS device. I have been failing miserably, I have checked this forum for previous posts on the topic with many suggestions that do not seem to work.  So I wonder if its something that has regressed? Unfortunately this is my very first project in Maui, so I would not know for sure..

### Steps to Reproduce

1 Create new .NET Maui App. on a pc VS 2022 -V Version 17.9.2   / [ VS 17.9.34622.214 from dotnet workload list]
2 Double click the project scroll down to the section for splash screen:
3 change the background color
		
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#FFFFFF" BaseSize="128,128" />
4  Compile run & deploy to a local iiOSs attached device using hot restart..

Color does not change.. try doing it all over again :

1 Create new .NET Maui App.
2 Double click the project scroll down to the section for splash screen:
3 change the background color
		
		<MauiSplashScreen Include="Resources\Splash\test.jpg" />
4  Compile run & deploy to a local iOS attached device using hot restart..

no changes - still the .net splash screen shows.

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.4

### Did you find any workaround?

no sorry.

**Comment by jfversluis** [comment]
As mentioned in the documentation under [limitations](https://learn.microsoft.com/dotnet/maui/ios/hot-restart?view=net-maui-8.0#limitations) of Hot Restart, when using Hot Restart you cannot change the app icon or splash screen. This is because of the way this technology is setup. 

If you do want to see the end result there you will have to connect to a Mac build host, use a Mac or go through a build pipeline and deploy your app through Test Flight.

**Comment by RobDaytona** [comment]
Hi, Gerald - I cant believe you are the one answering my ticket!

I was just this morning emailing you on your youtube contact email address: subject: 🧙‍♂️🧙‍♂️My Xamarin Big Game Release (interview/chat offer) - please would take a look! I am guessing you don't check that email inbox regularly.

As for this issue, your answer is fine, I understand now its not supported, 

- just a quick follow up question as I am really new to Maui, but is your answer true for any images on the local iOS device, I am getting images render fine on "windows machine" but as soon as I deploy to the local usb iOS device, the images do not appear? a simple yes no answer is all I am looking for - much appreciated.
