### ISSUE TITLE
[BUG] Setting MapType to MapType.Hybrid for Windows does not display street labels with the map

### ISSUE THREAD

**Issue by anotherlab** [dotnet/maui#21163]
### Description

The .NET MAUI Map supports three MapTypes

```
public enum MapType
{
    Street,
    Satellite,
    Hybrid
}
```

On Android and iOS, setting Map.MapType to any of the values will change the map to the appropriate type.  On Windows, setting `Map.MapType` to `MapType.Hybrid` performs the same as setting it to `MapType.Satellite`.

The embedded Javascript in [MapHandler.Windows.cs](https://github.com/CommunityToolkit/Maui/blob/bdcc01f6574403e6cb03d6f9cdc8d784a194fa87/src/CommunityToolkit.Maui.Maps/Handler/Map/MapHandler.Windows.cs#L255C1-L274C9) has the following method that gets invoked when you set MapType

```
function setMapType(mauiMapType)
{
	var mapTypeID = Microsoft.Maps.MapTypeId.road;
	switch(mauiMapType) {
		case 'Street':
		mapTypeID = Microsoft.Maps.MapTypeId.road;
		break;
		case 'Satellite':
		mapTypeID = Microsoft.Maps.MapTypeId.aerial;
		break;
		case 'Hybrid':
		mapTypeID = Microsoft.Maps.MapTypeId.aerial;
		break;
		default:
		mapTypeID = Microsoft.Maps.MapTypeId.road;
	}
	map.setView({
		mapTypeId: mapTypeID
	});
}
```

Setting MapType to Satellite or Hybrid uses the Bing Maps setting of `Microsoft.Maps.MapTypeIdaerial`. Bing Maps doesn't have a "Hybrid" view.  I _think_ Bing Maps uses the Satellite view with the LayerOption set to visible. I think you would need to add one of the following when setting `mapTypeId`.

`map.setView({ labelOverlay: Microsoft.Maps.LabelOverlay.visible});`
or
`map.setView({ labelOverlay: Microsoft.Maps.LabelOverlay.visible});`

### Steps to Reproduce

1. Take the sample project 
2. Open either map page
3. Add `MapType="Hybrid"` to the map control on the page
4. Target Windows

**What you should see**
A satellite map with road labels

**What you see**
A Satellite map without road labels

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples/CommunityToolkit.Maui.Sample/Pages/Views/Maps

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 SDK 10.0.22621

**Comment by QianaJiao** [comment]
I verified on 17.10.0 Preview 2.0, I can repro the issue on Windows platform with sample project with a liite different.
I setting Map.MapType to MapType.Satellite performs the same as setting it to MapType.Street.
![image](https://github.com/dotnet/maui/assets/91244512/483909e3-5c66-4ae4-9b8a-634cae5776fd)

**Comment by jfversluis** [comment]
This issue was moved to CommunityToolkit/Maui#1750
