### ISSUE TITLE
.net8 maui CollectionView.Header bug?

### ISSUE THREAD

**Issue by SamuelPimenta1988** [dotnet/maui#21179]
### Description

Hi, I have a problem with CollectionView.Header in .net maui .net8. I don't know if that is a maui bug. You can see that CollectionView.Header background color isn't responsive and that colunm Name isn't align with your value. i don't know as resolve that. 
Preview with macCatalyst:
![Group 37778](https://github.com/dotnet/maui/assets/86826495/dc5e46ea-bcda-46ad-b2d6-27be25d64b01)
![Captura de pantalla 2024-03-13 a las 10 00 13](https://github.com/dotnet/maui/assets/86826495/d4d9aeca-a000-4d8a-bcfb-c736df6f7b70)

My code: 
```XAML
<CollectionView
    Grid.Row="0"
    ItemsSource="{Binding ListProducts}">
    <CollectionView.Header>
        <Grid
            Padding="0,0,0,0"
            ColumnSpacing="0"
            BackgroundColor="{DynamicResource Culture}"
            HeightRequest="40">

            <Grid.ColumnDefinitions>

                <ColumnDefinition Width="3*" />
                <ColumnDefinition Width="7*"/>
                <ColumnDefinition Width="Auto" />
                <ColumnDefinition Width="Auto" />

            </Grid.ColumnDefinitions>

            <Label
                Grid.Column="0"
                Text="Referencia"
                Style="{DynamicResource TextCaptionSemibold}"
                VerticalOptions="Center"
                Margin="8,0,0,0"/>

            <Label
                Grid.Column="1"
                Text="Nombre"
                Style="{DynamicResource TextCaptionSemibold}"
                VerticalOptions="Center"
                Margin="0,0,0,0"/>

            <Label
                Grid.Column="2"
                Text=""/>

            <Label
                Grid.Column="3"
                Text=""/>

        </Grid>
    </CollectionView.Header>

    <CollectionView.ItemTemplate>
        <DataTemplate
            x:DataType="model:LineProductCatalogDTO">

            <Grid
                Padding="0,0,0,0"
                ColumnSpacing="0"
                HeightRequest="64">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="3*" />
                    <ColumnDefinition Width="7*" />
                    <ColumnDefinition Width="Auto" />
                    <ColumnDefinition Width="Auto" />
                </Grid.ColumnDefinitions>

                <BoxView
                    Grid.ColumnSpan="4"
                    HeightRequest="1"
                    BackgroundColor="{DynamicResource Gray2}"
                    VerticalOptions="Start"/>

                <Label
                    Grid.Column="0" 
                    Text="{Binding Reference}" 
                    VerticalOptions="Center"
                    Style="{DynamicResource TextBodyRegular}"
                    Margin="8,0,0,0"/>

                <Label
                    Grid.Column="1" 
                    Text="{Binding Name}" 
                    VerticalOptions="Center"
                    Style="{DynamicResource TextBodyRegular}"
                    Margin="0,0,0,0"/>

                <ButtonIconStandard:ButtonIconStandard
                    Grid.Column="2" 
                    Icon="ic_info_primary.png"
                    VerticalOptions="Center" 
                    HorizontalOptions="End"
                    Margin="0,0,8,0"
                    Command="{Binding Path=BindingContext.ProductDetailCommand, Source={x:Reference Name=dashboardPage}}"
                    CommandParameter="{Binding Id}"
                    IsVisible="{Binding IsProductDetailButtonVisible, Source={x:Reference Name=containerTableProductListOutputView}}"/>

                <ButtonIconPrimary:ButtonIconPrimary
                    Grid.Column="3" 
                    Icon="ic_add_white.png"
                    VerticalOptions="Center" 
                    HorizontalOptions="End"
                    Margin="0,0,8,0"
                    IsVisible="{Binding IsAddProductButtonVisible, Source={x:Reference Name=containerTableProductListOutputView}}"/>

            </Grid>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

I tried change to: 
<ColumnDefinition Width="80" /> and also <ColumnDefinition Width="*" /> but don't resolve.

CollectionView.Header are fixed data.
CollectionView.ItemTemplate are dinamic data.

First problem as you can see on printsreen is that CollectionView.Header isn't background color responsive and colunm "Name" isn't align with "Nombre del product 1".

I asked for help here [Blog](https://learn.microsoft.com/en-us/answers/questions/1611645/net-maui-collectionview-problems?page=1&orderby=Helpful&comment=answer-1476071#newest-answer-comment)

### Steps to Reproduce

1. define CollectionView.Header `<CollectionView
                                    Grid.Row="0"
                                    ItemsSource="{Binding ListProducts}">
                                    <CollectionView.Header>
                                        <Grid
                                            Padding="0,0,0,0"
                                            ColumnSpacing="0"
                                            BackgroundColor="{DynamicResource Culture}"
                                            HeightRequest="40">

                                            <Grid.ColumnDefinitions>

                                                <ColumnDefinition Width="3*" />
                                                <ColumnDefinition Width="7*"/>
                                                <ColumnDefinition Width="Auto" />
                                                <ColumnDefinition Width="Auto" />

                                            </Grid.ColumnDefinitions>

                                            <Label
                                                Grid.Column="0"
                                                Text="Referencia"
                                                Style="{DynamicResource TextCaptionSemibold}"
                                                VerticalOptions="Center"
                                                Margin="8,0,0,0"/>

                                            <Label
                                                Grid.Column="1"
                                                Text="Nombre"
                                                Style="{DynamicResource TextCaptionSemibold}"
                                                VerticalOptions="Center"
                                                Margin="0,0,0,0"/>

                                            <Label
                                                Grid.Column="2"
                                                Text=""/>

                                            <Label
                                                Grid.Column="3"
                                                Text=""/>

                                        </Grid>
                                    </CollectionView.Header>`

2. I define CollectionView.ItemTemplate `<CollectionView.ItemTemplate>
                                        <DataTemplate
                                            x:DataType="model:LineProductCatalogDTO">

                                            <Grid
                                                Padding="0,0,0,0"
                                                ColumnSpacing="0"
                                                HeightRequest="64">
                                                <Grid.ColumnDefinitions>
                                                    <ColumnDefinition Width="3*" />
                                                    <ColumnDefinition Width="7*" />
                                                    <ColumnDefinition Width="Auto" />
                                                    <ColumnDefinition Width="Auto" />
                                                </Grid.ColumnDefinitions>

                                                <BoxView
                                                    Grid.ColumnSpan="4"
                                                    HeightRequest="1"
                                                    BackgroundColor="{DynamicResource Gray2}"
                                                    VerticalOptions="Start"/>
                                            
                                                <Label
                                                    Grid.Column="0" 
                                                    Text="{Binding Reference}" 
                                                    VerticalOptions="Center"
                                                    Style="{DynamicResource TextBodyRegular}"
                                                    Margin="8,0,0,0"/>

                                                <Label
                                                    Grid.Column="1" 
                                                    Text="{Binding Name}" 
                                                    VerticalOptions="Center"
                                                    Style="{DynamicResource TextBodyRegular}"
                                                    Margin="0,0,0,0"/>
                                                
                                                <ButtonIconStandard:ButtonIconStandard
                                                    Grid.Column="2" 
                                                    Icon="ic_info_primary.png"
                                                    VerticalOptions="Center" 
                                                    HorizontalOptions="End"
                                                    Margin="0,0,8,0"
                                                    Command="{Binding Path=BindingContext.ProductDetailCommand, Source={x:Reference Name=dashboardPage}}"
                                                    CommandParameter="{Binding Id}"
                                                    IsVisible="{Binding IsProductDetailButtonVisible, Source={x:Reference Name=containerTableProductListOutputView}}"/>

                                                <ButtonIconPrimary:ButtonIconPrimary
                                                    Grid.Column="3" 
                                                    Icon="ic_add_white.png"
                                                    VerticalOptions="Center" 
                                                    HorizontalOptions="End"
                                                    Margin="0,0,8,0"
                                                    IsVisible="{Binding IsAddProductButtonVisible, Source={x:Reference Name=containerTableProductListOutputView}}"/>
                                                
                                            </Grid>
                                        </DataTemplate>
                                    </CollectionView.ItemTemplate>
                                </CollectionView>`

3. result on MacCatalyst and ipad 12 ios 17.2:
![Captura de pantalla 2024-03-13 a las 10 00 13](https://github.com/dotnet/maui/assets/86826495/aaf293a8-9de8-4f1d-817f-c1e47db5523c)
![Group 37778](https://github.com/dotnet/maui/assets/86826495/29e7b941-624d-44e1-9905-657c96035d7e)

On ipad 12 ios17.2 you can see that "Nombre" colunm isn't vertical align with "Nombre del product 1"
<img width="547" alt="Captura de pantalla 2024-03-13 a las 10 19 31" src="https://github.com/dotnet/maui/assets/86826495/27711762-bb48-4106-a97f-9889712c87c4">

I can't find a solution on any blog, I think it's a bug in Maui.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

iOS, macOS

### Affected platform versions

IOS 17.2

**Comment by SamuelPimenta1988** [comment]
Hi,

https://github.com/dotnet/maui/assets/86826495/d1ede7f3-c1e9-4cc7-a9f5-cd6f6daa86a2

As I saw <CollectionView.Header> isn't responsive as <CollectionView.ItemTemplate> . I don´t understand. You can see that "Nombre" column isn`t vertical align with "Nombre del product". <CollectionView.Header> background color isn't responsive. You have all code abode.

Is there anyone here who knows the solution or am I on the wrong forum?

Thanks

**Comment by SamuelPimenta1988** [comment]
Hello,
Can someone please explain to me what else I need to add here to reproduce the problem I have? They have all the code, images and video that reproduce the problem. I don't know what they need!

**Comment by egvijayanand** [comment]
Instead of specifying the Width of the last two columns Auto, specify an explicit size such as 0.5* each So that the Header is aligned with the Content.

**Comment by egvijayanand** [comment]
This issue is observed in the Windows platform as well.

The columns with their Width set to **Auto** are NOT considered while calculating their overall Width, they're just included as it is.

Columns with their size set Explicitly behave properly.

**Comment by SamuelPimenta1988** [comment]
@egvijayanand thanks for your help but not resolve.
Windons:
![Captura de pantalla 2024-03-19 a las 14 46 02](https://github.com/dotnet/maui/assets/86826495/542955d1-8c11-4e6b-8d1e-bc1c747971f5)

![Captura de pantalla 2024-03-19 a las 14 53 40](https://github.com/dotnet/maui/assets/86826495/4585ba22-cbff-47a4-a45f-15499d8bf685)

You can see that i continue with the same problem of aligns and not responsive CollectionView.Header.
CollectionView.ItemTemplate is responsive, i don´t understand the diference on code.

**CollectionView.Header**
`<CollectionView.Header>
    <Grid
        Padding="0,0,0,0"
        ColumnSpacing="0"
        BackgroundColor="{DynamicResource Culture}"
        HeightRequest="40">

        <Grid.ColumnDefinitions>

            <ColumnDefinition Width="3*" />
            <ColumnDefinition Width="7*"/>
            <ColumnDefinition Width="0,5"/>
            <ColumnDefinition Width="0,5"/>

        </Grid.ColumnDefinitions>

        <Label
            Grid.Column="0"
            Text="Referencia"
            Style="{DynamicResource TextCaptionSemibold}"
            VerticalOptions="Center"
            Margin="8,0,0,0"/>

        <Label
            Grid.Column="1"
            Text="Nombre"
            Style="{DynamicResource TextCaptionSemibold}"
            VerticalOptions="Center"
            Margin="0,0,0,0"/>

        <Label
            Grid.Column="2"
            Text=""/>

        <Label
            Grid.Column="3"
            Text=""/>

    </Grid>
</CollectionView.Header>`


**CollectionView.ItemTemplate**
`<CollectionView.ItemTemplate>
    <DataTemplate
        x:DataType="model:LineProductCatalogDTO">

        <Grid
            Padding="0,0,0,0"
            ColumnSpacing="0"
            HeightRequest="64">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="3*" />
                <ColumnDefinition Width="7*" />
                <ColumnDefinition Width="0,5" />
                <ColumnDefinition Width="0,5" />
            </Grid.ColumnDefinitions>

            <BoxView
                Grid.ColumnSpan="4"
                HeightRequest="1"
                BackgroundColor="{DynamicResource Gray2}"
                VerticalOptions="Start"/>

            <Label
                Grid.Column="0" 
                Text="{Binding Reference}" 
                VerticalOptions="Center"
                Style="{DynamicResource TextBodyRegular}"
                Margin="8,0,0,0"/>

            <Label
                Grid.Column="1" 
                Text="{Binding Name}" 
                VerticalOptions="Center"
                Style="{DynamicResource TextBodyRegular}"
                Margin="0,0,0,0"/>

            <ButtonIconStandard:ButtonIconStandard
                Grid.Column="2" 
                Icon="ic_info_primary.png"
                VerticalOptions="Center" 
                HorizontalOptions="End"
                Margin="0,0,8,0"
                Command="{Binding Path=BindingContext.ProductDetailCommand, Source={x:RelativeSource AncestorType={x:Type ContentPage}}}"
                CommandParameter="{Binding Id}"
                IsVisible="{Binding IsProductDetailButtonVisible, Source={x:Reference Name=containerTableProductListOutputView}}"/>

            <ButtonIconPrimary:ButtonIconPrimary
                Grid.Column="3" 
                Icon="ic_add_white.png"
                VerticalOptions="Center" 
                HorizontalOptions="End"
                Margin="0,0,8,0"
                IsVisible="{Binding IsAddProductButtonVisible, Source={x:Reference Name=containerTableProductListOutputView}}"/>

        </Grid>
    </DataTemplate>
</CollectionView.ItemTemplate>`.


`<Label
    Grid.Column="1"
    Text="Nombre"
    Style="{DynamicResource TextCaptionSemibold}"
    VerticalOptions="Center"
    Margin="0,0,0,0"/>` is horizontal fixed, i dont understand why, between 
`<Label
    Grid.Column="1" 
    Text="{Binding Name}" 
    VerticalOptions="Center"
    Style="{DynamicResource TextBodyRegular}"
    Margin="0,0,0,0"/>` respect the responsive size.

Do you have other idea?

**Comment by egvijayanand** [comment]
Set to **0.5*** and not **0,5*** which provides a different meaning (a new column altogether)

Period and not a comma.

**Comment by SamuelPimenta1988** [comment]
`<CollectionView.Header>
  <Grid
      Padding="0,0,0,0"
      ColumnSpacing="0"
      BackgroundColor="{DynamicResource Culture}"
      HeightRequest="40"
      ColumnDefinitions="3*,7*,0.5*,0.5*">`

`<CollectionView.ItemTemplate>
  <DataTemplate
      x:DataType="model:LineProductCatalogDTO">

      <Grid
          Padding="0,0,0,0"
          ColumnSpacing="0"
          HeightRequest="64"
          ColumnDefinitions="3*,7*,0.5*,0.5*">`

![Captura de pantalla 2024-03-19 a las 15 05 12](https://github.com/dotnet/maui/assets/86826495/7c6a0405-3134-4c41-a289-572d3a52f067)

![Captura de pantalla 2024-03-19 a las 15 07 08](https://github.com/dotnet/maui/assets/86826495/b1ec439f-db43-493b-b3ad-0ffc541cfd16)

Thanks but your solution dont resolve. 
CollectionView.ItemTemplate continue responsive and fine but CollectionView.Header continue fixed.

**Comment by egvijayanand** [comment]
Check whether you have data for 4 columns. I see only 2 columns and an img.

**Comment by SamuelPimenta1988** [comment]
`<CollectionView
  Grid.Row="0"
  ItemsSource="{Binding ListProducts}">
  <CollectionView.Header>
      <Grid
          Padding="0,0,0,0"
          ColumnSpacing="0"
          BackgroundColor="{DynamicResource Culture}"
          HeightRequest="40"
          ColumnDefinitions="3*,7*,0.5*,0.5*">

          <Label
              Grid.Column="0"
              Text="Referencia"
              Style="{DynamicResource TextCaptionSemibold}"
              VerticalOptions="Center"
              Margin="8,0,0,0"/>

          <Label
              Grid.Column="1"
              Text="Nombre"
              Style="{DynamicResource TextCaptionSemibold}"
              VerticalOptions="Center"
              Margin="0,0,0,0"/>

          <Label
              Grid.Column="2"
              Text=""/>

          <Label
              Grid.Column="3"
              Text=""/>

      </Grid>
  </CollectionView.Header>

  <CollectionView.ItemTemplate>
      <DataTemplate
          x:DataType="model:LineProductCatalogDTO">

          <Grid
              Padding="0,0,0,0"
              ColumnSpacing="0"
              HeightRequest="64"
              ColumnDefinitions="3*,7*,0.5*,0.5*">


              <BoxView
                  Grid.ColumnSpan="4"
                  HeightRequest="1"
                  BackgroundColor="{DynamicResource Gray2}"
                  VerticalOptions="Start"/>

              <Label
                  Grid.Column="0" 
                  Text="{Binding Reference}" 
                  VerticalOptions="Center"
                  Style="{DynamicResource TextBodyRegular}"
                  Margin="8,0,0,0"/>

              <Label
                  Grid.Column="1" 
                  Text="{Binding Name}" 
                  VerticalOptions="Center"
                  Style="{DynamicResource TextBodyRegular}"
                  Margin="0,0,0,0"/>

              <ButtonIconStandard:ButtonIconStandard
                  Grid.Column="2" 
                  Icon="ic_info_primary.png"
                  VerticalOptions="Center" 
                  HorizontalOptions="End"
                  Margin="0,0,8,0"
                  Command="{Binding Path=BindingContext.ProductDetailCommand, Source={x:RelativeSource AncestorType={x:Type ContentPage}}}"
                  CommandParameter="{Binding Id}"
                  IsVisible="{Binding IsProductDetailButtonVisible, Source={x:Reference Name=containerTableProductListOutputView}}"/>

              <ButtonIconPrimary:ButtonIconPrimary
                  Grid.Column="3" 
                  Icon="ic_add_white.png"
                  VerticalOptions="Center" 
                  HorizontalOptions="End"
                  Margin="0,0,8,0"
                  IsVisible="{Binding IsAddProductButtonVisible, Source={x:Reference Name=containerTableProductListOutputView}}"/>

          </Grid>
      </DataTemplate>
  </CollectionView.ItemTemplate>
  </CollectionView>`


this table is in a contentview that is imported into two contentpages. one contentpage shows "ButtonIconPrimary" and the other shows "ButtonIconStandard".
That's why I have 4 columns in CollectionView.ItemTemplate.

But if i make that:
`<CollectionView.Header>
  <Grid
      Padding="0,0,0,0"
      ColumnSpacing="0"
      BackgroundColor="{DynamicResource Culture}"
      HeightRequest="40"
      ColumnDefinitions="3*,7*">

      <Label
          Grid.Column="0"
          Text="Referencia"
          Style="{DynamicResource TextCaptionSemibold}"
          VerticalOptions="Center"
          Margin="8,0,0,0"/>

      <Label
          Grid.Column="1"
          Text="Nombre"
          Style="{DynamicResource TextCaptionSemibold}"
          VerticalOptions="Center"
          Margin="0,0,0,0"/>

      

  </Grid>
  </CollectionView.Header>` the result is the same:
![Captura de pantalla 2024-03-19 a las 15 24 18](https://github.com/dotnet/maui/assets/86826495/f5955e3f-2e71-47dd-a4ef-46a6e327ca50)

I've tried everything to find the error and that's why I think it's a Maui bug.

**Comment by egvijayanand** [comment]
You have to adjust everything. Header and Item. Check.

**Comment by SamuelPimenta1988** [comment]
I don t understand but i can't post here all code. 

Well, to me the best import is that CollectionView.Header isn't responsive as CollectionView.ItemTemplate.
Sorry but i need send for you images. That is what i have now. 

![Captura de pantalla 2024-03-19 a las 15 57 38](https://github.com/dotnet/maui/assets/86826495/8373f65a-7218-4020-b5eb-7ffaebc22d87)

![Captura de pantalla 2024-03-19 a las 15 57 54](https://github.com/dotnet/maui/assets/86826495/5b3485fd-4567-4d80-89b2-8004c9b02cd8)

![Captura de pantalla 2024-03-19 a las 16 10 25](https://github.com/dotnet/maui/assets/86826495/7336780a-2b2a-4f2f-9e38-d8c991a55bd2)

**Comment by egvijayanand** [comment]
> You have to adjust everything. Header and Item. Check.

Why are you still having **Auto** in the Item Template? Told to change everything. Both header and item should represent the same structure for it to get aligned.

Here's my sample XAML.

```xml
<CollectionView
    HorizontalOptions="Center"
    ItemsSource="{Binding Items}"
    VerticalOptions="Center">
    <CollectionView.Header>
        <Grid
            BackgroundColor="Yellow"
            ColumnDefinitions="3*,6*,0.5*,0.5*"
            HeightRequest="40">
            <Label
                Grid.Column="0"
                Text="Id"
                VerticalOptions="Center" />
            <Label
                Grid.Column="1"
                HorizontalOptions="Start"
                Text="Name"
                VerticalOptions="Center" />
            <Label
                Grid.Column="2"
                Text="Item 1"
                VerticalOptions="Center" />
            <Label
                Grid.Column="3"
                Text="Item 2"
                VerticalOptions="Center" />
        </Grid>
    </CollectionView.Header>
    <CollectionView.ItemTemplate>
        <DataTemplate x:DataType="{x:Type m:Item}">
            <Grid
                ColumnDefinitions="3*,6*,0.5*,0.5*"
                HeightRequest="40">
                <Label
                    Grid.Column="0"
                    Text="{Binding Id}" />
                <Label
                    Grid.Column="1"
                    Text="{Binding Name}" />
                <Label
                    Grid.Column="2"
                    Text="{Binding Item1}" />
                <Label
                    Grid.Column="3"
                    Text="{Binding Item2}" />
            </Grid>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

**Comment by SamuelPimenta1988** [comment]
Sorry. I think you don't understand the problem. I changed the code as you suggested. I've tried this in the past and it didn't work but I tried it now so you can see the results.

![Captura de pantalla 2024-03-19 a las 17 42 47](https://github.com/dotnet/maui/assets/86826495/c061cbd1-4d17-4ed1-8540-95db7e7486e3)


![Captura de pantalla 2024-03-19 a las 17 43 07](https://github.com/dotnet/maui/assets/86826495/d6576bf4-d665-44e1-b784-fa3af3d7d323)


<img width="1469" alt="Captura de pantalla 2024-03-19 a las 17 43 26" src="https://github.com/dotnet/maui/assets/86826495/4738ed7f-c89d-445a-ad69-eae12e14e4dd">


<img width="467" alt="Captura de pantalla 2024-03-19 a las 17 43 51" src="https://github.com/dotnet/maui/assets/86826495/864d6168-79b1-4b78-9ebe-bf6d625dc209">

One more, i say that CollectionView.Header isn't responsive or it had a bug.

Thank you for your help.

**Comment by AntHillOracle** [comment]
I also have a reproducible problem with CollectionView.Header.  I don’t appreciate the tone of this thread where it seems the OP is being attacked.  My issue is different than the OP, but, like the OP, exhibits itself on iOS.

My issue is:
1)	The following works in WinUI and Android, but does work on iOS.  If you wrap the Monkey Label inside a VerticalStackLayout, it will work on all three platforms.  No error is produced saying that the Label should be wrapped by a StackLayout (and there is no reason why it should have to be.)

<CollectionView ItemsSource="{Binding Monkeys}"
                ItemTemplate="{StaticResource MonkeyTemplate}" >
    <CollectionView.Header>
                <Label Text="Monkeys" />
    </CollectionView.Header>
</CollectionView>

**Comment by SamuelPimenta1988** [comment]
Hello @AntHillOracle
Thanks for your feedback.
I continue searching help in others blog and I saw that an user wrapped on a stack layout but don t result.

what I know at a moment is that collectionview.head isn’t responsive as collectionview.itemtemplate as you can see in my prints. I only test on iPad and Mac catalist emulator. That app is to iPad. Do you know other solution to I make a table? A library for example.

thanks

**Comment by AntHillOracle** [comment]
I have been putting my table headers above the collection view.  For example, 1) place a grid, 2) Row 0 of the grid, place your table header grid, 3) Row 1 of the grid, place the collection view.  As long as your column measurements are the same for you header grid and the collectionview itemtemplate grid, the items line up with the header.

I tend to use absolute measurements instead of the proportional stars.  For example ColumnDefinitions="60, 120, 10, 10" . It takes trial and error to make thing fit, but it works.  I do find that use "Auto" hurts performance and sometimes give unpredictable results.

Oh, one more thing I've experienced, if your table of items is wider than the screen, you likely won't find a satisfactory solution.  Putting that top level grid I described inside a ScrollView with Orientation="Horizontal" and a Vertical CollectionView results in terrible performance, in particular on Android.

**Comment by SamuelPimenta1988** [comment]
@AntHillOracle There is a doubt that no one has yet been able to explain. If you watch the video I added, you can see that the header is fixed width and the table rows are responsive. the column definitions are the same for the header and for the results lines. Can you explain why the header is fixed and does not have the same behavior as the table rows?

**Comment by SamuelPimenta1988** [comment]
Nobody knew the solution. After many tests I got what I needed. Here is the solution for anyone who has the same problem.
Thanks to anyone who tried to help.

![Captura de pantalla 2024-03-20 a las 10 21 54](https://github.com/dotnet/maui/assets/86826495/4c1283f6-ed51-4d15-94c5-e665e92b3241)

![Captura de pantalla 2024-03-20 a las 10 22 23](https://github.com/dotnet/maui/assets/86826495/d23078a8-8ecd-45bf-8da4-8c39156b735b)

Ipad landscape
<img width="746" alt="Captura de pantalla 2024-03-20 a las 10 25 22" src="https://github.com/dotnet/maui/assets/86826495/30b046f9-6004-4172-9ec6-2ffedfe543d8">

ipad portrait
<img width="551" alt="Captura de pantalla 2024-03-20 a las 10 25 35" src="https://github.com/dotnet/maui/assets/86826495/4372028c-9212-4d77-904c-bc761e4467c5">
