### ISSUE TITLE
About the problem that the VS17.9.3 version project references the Maui version

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/maui#21177]
### Description

After VS is updated to version 17.9.3, create a maui project. The default class library referenced by maui is 8.0.7 instead of 8.0.10, and the nuget needs to be updated manually. Try to reboot, reinstall maui and maui workload, and the problem is the same. The default maui reference type version for projects created with VS17.9.3 is 8.0.7

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by bronteq** [comment]
This does not seem a bug, check the release notes here: https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#1793--visual-studio-2022-version-1793

> VS now includes MAUI 8.0.7 (SR2)
