### ISSUE TITLE
Android Border with RoundRectangle Stroke does not correctly round corners of things within it

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#21173]
### Description

A Border with a RoundRectangle stroke looks like this in Windows (correct):

<img width="300" alt="clip bug windows" src="https://github.com/dotnet/maui/assets/43948450/858dd8cf-a4b8-4ddf-80b7-86b9855aac13">

But this in Android (incorrect):

<img width="300" alt="clip bug android" src="https://github.com/dotnet/maui/assets/43948450/8f981910-4552-4cc9-ac24-b8deed632d26">

You can see in Android the corners of the red Image contained within are not being rounded like they should be.

This was not an issue in .NET 7.0 but is an issue in .NET 8.0

### Steps to Reproduce

1. Create a Project
2. Change App.xaml.cs to the following and build in Windows vs. Android:
```
public partial class App : Application {
    public App() {

        ContentPage page = new();
        MainPage = page;
        page.BackgroundColor = Colors.DeepSkyBlue;
        AbsoluteLayout abs = new();
        page.Content = abs;

        AbsoluteLayout mainAbs = new();
        abs.Add(mainAbs);

        Border border = new();
        border.TranslationX = border.TranslationY = 20;
        border.WidthRequest = border.HeightRequest = 100;
        border.Stroke = Colors.White;
        border.BackgroundColor = Colors.White;
        border.StrokeThickness = 9;
        border.StrokeShape = new RoundRectangle() { CornerRadius = 16 };
        mainAbs.Add(border);

        AbsoluteLayout borderAbs = new();
        border.Content = borderAbs;

        Image image = new();
        image.WidthRequest = image.HeightRequest = 200;
        image.BackgroundColor = Colors.Red;
        borderAbs.Add(image);

    }
}
```

### Link to public reproduction project repository

https://github.com/jonmdev/AndroidBorderCornerBug

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

@jsuarezruiz

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2. Can repro on Android platform with sample project.

**Comment by Phenek** [comment]
Yeah still #7521
