### ISSUE TITLE
Can't find debug target or "{}"

### ISSUE THREAD

**Issue by Narizis** [dotnet/maui#21182]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Hey @Narizis thanks for your interest in .NET MAUI! Sorry you hit a little snag here.

Could you maybe elaborate a little bit more on what you were doing exactly when you hit this message? Do you maybe have a screenshot? Any version information on the .NET MAUI version you're using? Visual Studio for Mac or Visual Studio Code?

Thanks!
