### ISSUE TITLE
PropertyChanged event not picked up for bound indexed property in Release mode with Compiled Bindings

### ISSUE THREAD

**Issue by PieEatingNinjas** [dotnet/maui#21181]
### Description

In .NET MAUI we can bind to an indexed property like this:
```ErrorExposer[DisplayName]```

The `PropertyChanged` event can be triggered on the class exposing the indexed property like this:
```PropertyChanged?.Invoke(this, new PropertyChangedEventArgs($"Item[DisplayName]")); ```

However, when the app is compiled in `Release` mode and `x:DataType` is defined, this doesn't seem to work. When the event is being fired, it is not bing picked-up, resulting in the UI showing the 'old' initial value.

* If I'd call `PropertyChanged?.Invoke(this, new PropertyChangedEventArgs($"Item")); `, the event does get picked-up in `Release` mode and the changes are reflected on the UI.
* If I remove the `x:DataType` from the page, and call `PropertyChanged?.Invoke(this, new PropertyChangedEventArgs($"Item[DisplayName]"));`, the event does get picked-up in `Release` mode and the changes are reflected on the UI.
* Overriding the `x:DataType` to null on the control containing the binding, and calling `PropertyChanged?.Invoke(this, new PropertyChangedEventArgs($"Item[DisplayName]"));`, the event does get picked-up in `Release` mode and the changes are reflected on the UI.

So it's really a combination of being in `Release` mode and using compiled bindings that results in this issue.

This is particularly an annoying issue as the behavior is different between `Debug` and `Release` mode and far from trivial to hunt down.

### Steps to Reproduce

1. Open the attached repo
    - This app contains Label with its Text property bound to `ClassWithIndexProperty[foo]`
    - The first button will set a value 'bar' for index foo and call `PropertyChanged?.Invoke(this, 
            new PropertyChangedEventArgs($"Item[{key}]"));`
    - The second button will set a value 'bar bar' for index foo and call `PropertyChanged?.Invoke(this, 
            new PropertyChangedEventArgs($"Item"));`
2. Run in Debug and notice that when clicking the buttons 'bar' or 'bar bar' is being displayed
3. Run the app in `Release` mode and notice the exact same behavior
5. Add `x:DataType="local:MainPage"` to the page to enable compiled bindings
6. Run again in `Release`mode and notice how the first button doesn't seem to do anything, but the second button does (as it call property changed for "Item" and not "Item[foo]"
7. Add `x:DataType="{x:Null}"` to the Label and notice how both buttons work again

### Link to public reproduction project repository

https://github.com/PieEatingNinjas/ReproIndexedBinding

### Version with bug

8.0.10

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

* Remove compiled bindings (remove x:DataType)
* Call `PropertyChanged?.Invoke(this, new PropertyChangedEventArgs($"Item"));` instead of specifying a specific index
* Set `x:DataType="{x:Null}"` on the control where the databinding is defined on

Although this works, it is not ideal as I would like to use compiled bindings for performance reasons and only trigger the PropertyChanged event for the specific index in order to avoid all binding on the indexed property to be re-evaluated.

**Comment by PureWeen** [comment]
@StephaneDelcroix
