### ISSUE TITLE
SecureStorage in iOS simulator

### ISSUE THREAD

**Issue by ricardommatias** [dotnet/maui#21195]
### Description

Calling **SecureStorage.Default.SetAsync(key, value)** when debugging on an iOS simulator throws an exception:

```
System.Exception: Error adding record: MissingEntitlement
   at Microsoft.Maui.Storage.KeyChain.SetValueForKey(String value, String key, String service)
   at Microsoft.Maui.Storage.SecureStorageImplementation.SetAsync(String key, String value, SecAccessible accessible)
   at Microsoft.Maui.Storage.SecureStorageImplementation.PlatformSetAsync(String key, String data)
   at Microsoft.Maui.Storage.SecureStorageImplementation.SetAsync(String key, String value)
```

I tried setting the **CustomEntitlements** in the .csproj but still it doesn't work:
```
<CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
```

**Entitlements.plist**:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
</dict>
</plist>
```

I also tried to add the **Keychain Sharing** key to the **Entitlements.plist** but still the same exception is thrown:
```
<key>keychain-access-groups</key>
```

### Steps to Reproduce

Call **SecureStorage.Default.SetAsync(key, value)** when debugging in an iOS simulator.

**Expected outcome**: No exception thrown

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

**Comment by assoumemba** [comment]
This error has a workaround
see here: https://learn.microsoft.com/en-us/answers/questions/1057290/when-running-the-(await-securestorage-setasync)-co

basically just create a new file for Entitlements.plist
and put this content where xxx is your bundleId.  **Clean all projects and rebuild. Should work.**

<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">  
<plist version="1.0">  
<dict>  
      <key>keychain-access-groups</key>  
      <array>  
            <string>$(AppIdentifierPrefix)xxx</string>  
      </array>  
</dict>  
</plist>

**Comment by ricardommatias** [comment]
> This error has a workaround see here: https://learn.microsoft.com/en-us/answers/questions/1057290/when-running-the-(await-securestorage-setasync)-co
> 
> basically just create a new file for Entitlements.plist and put this content where xxx is your bundleId. **Clean all projects and rebuild. Should work.**
>       keychain-access-groups                    $(AppIdentifierPrefix)xxx

Like I said in the post, I already tried adding the Keychain Sharing key and it still throws the same exception.

**Comment by assoumemba** [comment]
Hi there
You might just have filetype error.  I had the same issue as well. 
To make sure it is created properly. Instead of creating xml file inside visual studio, You can open Finder and locate your Info.plist. Copy it and rename your copy to Entitlements.plist
Add content also out of IDE using example SublimeText and save. Then Clean projects and rebuild.

**Comment by ricardommatias** [comment]
> Hi there You might just have filetype error. I had the same issue as well. To make sure it is created properly. Instead of creating xml file inside visual studio, You can open Finder and locate your Info.plist. Copy it and rename your copy to Entitlements.plist Add content also out of IDE using example SublimeText and save. Then Clean projects and rebuild.

It's working now. I believe the issue really was that I had not performed a **Clean**, just a **Rebuild**.
Thanks!

**Comment by jfversluis** [comment]
Glad you figured it out! Yeah sometimes there might be some persistent caching issue. Always good to include a clean and rebuild step in your debugging when you see something you can't explain 😄 

Thanks for letting us know!
