### ISSUE TITLE
XAML resource keys cannot be extracted into string constants 

### ISSUE THREAD

**Issue by NetPowerON** [dotnet/maui#21196]
### Description

On compiling get the error
Error	XFC0127	x:Key expects a string literal.	MauiApp1	MauiApp1\Resources\Styles\Styles.xaml	

### Steps to Reproduce

```XAML
<ResourceDictionary 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:abst="clr-namespace:Abstractions;assembly=UI.Abstractions">
<Style TargetType="Button" x:Key="{x:Static abstr:StyleConstants.ImplicitStyleKey}">

</Style>
</ResourceDictionary>
```

```C#
public static class StyleConstants
{
    public static string ImplicitStyleKey = "_implicit";
}
```

I also tried

```C#
public static class StyleConstants
{
    public const string ImplicitStyleKey = "_implicit";
}
```

The error will be x:Key expects a string literal. This works fine in WPF. 

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

**Comment by jaosnz-rep** [comment]
Verified on 17.10 Preview 2.0, can repro this with .NET 8 Maui project.
![image](https://github.com/dotnet/maui/assets/82628041/417d5164-760f-45bc-9da8-9b3af93ba524)

**Comment by StephaneDelcroix** [comment]
not a bug. x:Key does require a string literal, and correctly reports the error if not. It would be technically possible to make it support x:Static, but nothing else than that.

I don't know what you're trying to do here, but implicit styles are supported. just don't specify a x:Key
