### ISSUE TITLE
Multi-Project App template misses out on defining the Style named Headline and Subheadline, thus resulting in an App crash on launch

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#21190]
### Description

MainPage in the shared class library of the Multi-Project App template refers to styles named **Headline** and **Subheadline**. But they're defined nowhere.

Launching the project from the default template causes the app to crash due to this missing style definition.

### Steps to Reproduce

1. Create a Multi-Project App template
2. Build and Launch the App

### Link to public reproduction project repository

Default template itself is suffice, no authored code

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All platforms

### Did you find any workaround?

Define the missing styles or remove the Content.

The default template is expected to work out of the box without any changes.

### Relevant log output

```shell
NA
```

**Comment by PureWeen** [comment]
Thank you @egvijayanand !!!!
