### ISSUE TITLE
[Windows] Button font image source incorrectly sized on 8.0.10 when specifying a button HeightRequest

### ISSUE THREAD

**Issue by MitchBomcanhao** [dotnet/maui#21202]
### Description

From version 8.0.10, using a font image source on a button image source is incorrectly resizing its content when a heightrequest is set on the button, resulting in the UI having different sized elements and the font image itself looking blurry (and increasingly blurrier depending on how small you had set the size for the font image source).

[Note: version 8.0.10 is missing from the list of versions in this bug form, which is why I had to select "other". edit: now manually changed to 8.0.10].

### Steps to Reproduce

1. add the following xaml to any page
 ```
<Button
                FontSize="18.75"
                HeightRequest="60"
                HorizontalOptions="Fill"
                Text="Button with height request set"
                TextTransform="Uppercase">
                <Button.ImageSource>
                    <FontImageSource Glyph="A" />
                </Button.ImageSource>
            </Button>
            <Button
                FontSize="18.75"
                HorizontalOptions="Fill"
                Text="Button without height request"
                TextTransform="Uppercase">
                <Button.ImageSource>
                    <FontImageSource Glyph="A" />
                </Button.ImageSource>
            </Button>
```

2. Expected:
![image](https://github.com/dotnet/maui/assets/31066938/b64e668a-7dec-4562-ae47-a68d60db5137)
3. Observed:
![image](https://github.com/dotnet/maui/assets/31066938/a97de344-11fd-4328-9131-ae4e17b541c5)

### Version with bug

8.0.10

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

Windows

### Did you find any workaround?

Using MinimumHeightRequest instead of HeightRequest stops this issue.
![image](https://github.com/dotnet/maui/assets/31066938/bc4e0f65-a967-4b6c-af56-5843fff8031d)

**Comment by MitchBomcanhao** [comment]
when changing the font image source to include a small size, this is what it looks like
`<FontImageSource Glyph="A" Size="10" />`

![image](https://github.com/dotnet/maui/assets/31066938/0c09b8a6-9ab7-4c03-a2c6-f8915e0df12c)

top is unexpected
bottom is as expected

**Comment by MattePozzy** [comment]
Same issue here
with previous version of MAUI
![image](https://github.com/dotnet/maui/assets/7420345/2e10a8ec-0f07-4b60-9db5-64925d1eedf3)

with 8.0.10
![image](https://github.com/dotnet/maui/assets/7420345/5ceadee1-ccf6-45c9-81b7-421b0342bf14)

**Comment by MitchBomcanhao** [comment]
@MattePozzy Yes I can confirm that the workaround is not functional when using ContentLayout. In this case you don't even need to use Height request to cause it to fail.

```
            <Button
                ContentLayout="Top, 30"
                FontSize="30"
                Text="Button with ContentLayout='Top, 30'">
                <Button.ImageSource>
                    <FontImageSource Glyph="A" />
                </Button.ImageSource>
            </Button>
```

which results in this

8.0.7
![image](https://github.com/dotnet/maui/assets/31066938/3c454cfe-0948-4f5d-94c2-db85248beb53)

8.0.10
![image](https://github.com/dotnet/maui/assets/31066938/7f4693b7-3632-4606-96fe-1d32060b0ff5)

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds
