### ISSUE TITLE
CollectionView is not currently being Garbage Collected (2)

### ISSUE THREAD

**Issue by marco-skizza** [dotnet/maui#21249]
### Description

Hi

Many thanks for your work on the following issue so far: https://github.com/dotnet/maui/issues/20710

Unfortunately, I'm still facing the memory leak on iOS - even with the latest nightly build `8.0.20-nightly.10316`.

It seems, that the leak only occurs when using the `CollectionView` via Xaml:
```xml
    <CollectionView x:Name="MyCollectionView">
        <CollectionView.ItemTemplate>
            <DataTemplate>

                <Label Text="Test" />

            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
```
And then in the code behind:
```cs
    public PageXamlLeak()
    {
        InitializeComponent();

        MyCollectionView.ItemsSource = new ObservableCollection<string> { "1", "2", "3" };
    }
```
When constructing the same control via a C# page, the leak doesn't occur.

I hope you can take a 2nd took at this memory leak.
Many Thanks!

### Steps to Reproduce

- run sample
- click button to go to leaking Xaml page - and navigate back
- do this several times: `~PageXamlLeak() called` never gets logged
- in contrast test the same with the C# page that is not leaking

### Link to public reproduction project repository

https://github.com/marco-skizza/MauiCollectionView

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.3.1 on iPad mini 6

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
I agree, I don't think this issue is fixed. I've reopened it and closing this one as a dupe.
