### ISSUE TITLE
Android - Spashscreen image not scaled correctly

### ISSUE THREAD

**Issue by Legends** [dotnet/maui#21245]
### Description

**Android:**

I have a MauiSplashScreen svg with the following attributes set:
`<svg xmlns="http://www.w3.org/2000/svg" width="2500" height="2500" viewBox="0 0 192.756 192.756">`

The image does not get scaled down as expected, I can only see the center of the image, the rest is outside of the viewport.

> Installed Workload Id      Manifest Version       Installation Source
> ---------------------------------------------------------------------
> maui-windows               8.0.7/8.0.100          VS 17.9.34701.34
> wasm-tools                 8.0.3/8.0.100          VS 17.9.34701.34
> ios                        17.2.8004/8.0.100      VS 17.9.34701.34
> maccatalyst                17.2.8004/8.0.100      VS 17.9.34701.34
> android                    34.0.52/8.0.100        VS 17.9.34701.34
> wasm-tools-net6            8.0.3/8.0.100          VS 17.9.34701.34

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11-API 30

### Did you find any workaround?

no

**Comment by bcaceiro** [comment]
The splashscreen on Android is super inconsistent. In different devices, with different resolutions

**Comment by RoiChen001** [comment]
Can repro this issue at Android platform on the latest 17.10 preview2.
