### ISSUE TITLE
This problem is easy to occur when debugging the real machine in VS17.9.3+Maui8.0.10, which is stuck all the time, and the phone does not have an application installed. VS17.9.3+Maui8.0.7 is normal.

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/maui#21247]
### Description

![image](https://github.com/dotnet/maui/assets/30250585/a703a0f3-83ec-4e95-8a46-653b5433397a)
![image](https://github.com/dotnet/maui/assets/30250585/5635a361-f1d9-470d-9e41-8eb86dfd89af)

This problem is easy to occur when debugging the real machine in VS17.9.3+Maui8.0.10, which is stuck all the time, and the phone does not have an application installed. VS17.9.3+Maui8.0.7 is normal.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

Android

**Comment by Redth** [comment]
First I would try deleting the existing app from your device/emulator and then deleting the bin/ and obj/ folders for your project.

If that doesn't work, can you try setting this in your project file?

```xml
<PropertyGroup>
  <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
</PropertyGroup>
```

@dellis1972 any other thoughts here? seems like maybe a fast deploy related thing?

**Comment by HuaFangYun** [comment]
I opened VS, deleted obj and bin folders, regenerated, connected to the phone with USB, debugged and installed successfully.
When I generate it again, I will always be stuck in Starting: Intent {...
Then I'll try to add a configuration.
< PropertyGroup >.
< EmbedAssembliesIntoApk > true < / EmbedAssembliesIntoApk >.
< / PropertyGroup >.
Will still be stuck in Starting: Intent {...

**Comment by dellis1972** [comment]
> @dellis1972 any other thoughts here? seems like maybe a fast deploy related thing?

A Permission denied error probably means another process like Anti Virus has the temp file locked.

**Comment by HuaFangYun** [comment]
The problem of permissions can be solved by secondary regeneration. But I have turned off the relevant security software. It will show up again sometime. And Visual Studion that runs with administrator privileges. At present, I think the biggest problem is that it will get stuck when the real machine is debugged. I don't know whether other people have this problem or what information they need to provide, please point out. I will cooperate with the operational testing and provide relevant useful information. Thank you!

**Comment by HuaFangYun** [comment]
C:\Users\jianf>dotnet workload list

已安装的工作负载 ID       清单版本                   安装源文件
---------------------------------------------------------
maui              8.0.7/8.0.100          SDK 8.0.200
maui-windows      8.0.7/8.0.100          VS 17.9.34701.34
maccatalyst       17.2.8043/8.0.100      VS 17.9.34701.34
ios               17.2.8043/8.0.100      VS 17.9.34701.34
android           34.0.85/8.0.100        VS 17.9.34701.34

**Comment by HuaFangYun** [comment]
```
已安装的工作负载 ID       清单版本                   安装源文件
---------------------------------------------------------
maui              8.0.7/8.0.100          SDK 8.0.200
maui-windows      8.0.7/8.0.100          VS 17.9.34701.34
maccatalyst       17.2.8043/8.0.100      VS 17.9.34701.34
ios               17.2.8043/8.0.100      VS 17.9.34701.34
android           34.0.85/8.0.100        VS 17.9.34701.34
```

**Comment by kevinxufei** [comment]
Using VS 17.9.3+maui 8.0.10, it can be deployed to Android physical device.
![a](https://github.com/dotnet/maui/assets/86938401/e8a3678b-8cb3-4856-bb42-5e128cd6ec95)

**Comment by HuaFangYun** [comment]
@kevinxufei  My test mobile phone system is Android 14, please debug it many times.
