### ISSUE TITLE
Problem (re)applying DataTemplates generated with a DataTemplateSelector, to collection items that are added to a CollectionView after the Collection is Cleared

### ISSUE THREAD

**Issue by axa88** [dotnet/maui#21252]
### Description

There is a problem (re)applying a `DataTemplate` generated with a `DataTemplateSelector`, to collection items that are added to a CollectionView, after the collection is cleared.

Here is an example of the initial collection of items.  Here we can see 4 custom controls items in the collection, each slightly different but each with a `Label` to identify which `DataTemplate` is used
-1st just some Labels
-2nd has a Switch also
-3rd has an Entry also
-4th has 3 Pickers

![image](https://github.com/dotnet/maui/assets/13371986/a722ee44-6404-4ad6-9e62-3785d5009a48)

Then the `ObserveableCollection` is Cleared and  new items are then added in reverse:
-Pickers
-Entry + Labels
-Switch + Labels
-Labels.

But the result is a mix up where it appears the 1st `DataTemplate` stays in place, and what should have been 1st is pushed down to the 2nd, 2nd to 3rd, 3rd to 4th

![image](https://github.com/dotnet/maui/assets/13371986/2cbe9b2a-97dc-46da-b86b-49422ee001ab)

And since each custom control shares the Same Name Label, it is easier to identify the mismatch of Template and Data

[This issue](https://stackoverflow.com/questions/74823748/datatemplateselector-is-not-executed-when-items-are-cleared-and-added-to-observa) had also been reported long ago elsewhere

### Steps to Reproduce

- Create a `CollectionView` setting its `ItemTemplate` property with a `DatatemplateSelector`

- Add items to your `CollectionView` `ObservableCollection` using different Templates from the selector.

- Observe the listing is as expected.

- Clear the Collection.
- Add new items to the Collection where the item Templates type does not match what was previously in the Collection.

- Observe the mismatch of data and template.

Of course it is expected that these new items will be given their appropriate template

And since it is expected that a `DataTemplateSelector` is reusable, the workaround below as simple as it is, shouldn't be necessary, making this a bug

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0xx

### Did you find any workaround?

When the collection is cleared, use its CollectionChanged event to detect a Reset Action and then nullify and (re)set the ItemTemplate with the very same one that it had before.

```
MyObservableCollection.CollectionChanged += (sender, notifyCollectionChangedEventArgs) =>
		{
			if (notifyCollectionChangedEventArgs.Action == NotifyCollectionChangedAction.Reset)
			{
				ItemTemplate = null;
				ItemTemplate = dataTemplateSelector;
			}
		};
```

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by axa88** [comment]
Ya nightly fixes it...

Ill look forward to seeing this issue marked in the release notes.... 

Now how about that [Selected State](https://github.com/dotnet/maui/issues/20615) problem
