### ISSUE TITLE
'Platform' does not contain a definition for 'Init'

### ISSUE THREAD

**Issue by FANMixco** [dotnet/maui#21253]
### Description

I'm upgrading my Xamarin.Android app to .NET8, I added, the `Microsoft.Maui.Essentials` lib and enabled in my project `<UseMauiEssentials>true</UseMauiEssentials>`

And the platform only displays:
![image](https://github.com/dotnet/maui/assets/1666156/44183091-79b0-4c62-bbf0-208d1b5e9e36)

I'm targeting Android 14 with .NET 8 (it's a new project). I'm not sure if I'm missing something.

### Steps to Reproduce

1. Create an Android App targeting .NET 8.
2. Install Microsoft.Maui.Essentials
3. Try to init the project.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13/14

**Comment by pictos** [comment]
I believe you're looking for this methods instead

`Microsoft.Maui.ApplicationModel.Platform.Init(this);`

**Comment by jfversluis** [comment]
Indeed, looks like you might be using the wrong namespace here. Also see the docs [here](https://learn.microsoft.com/dotnet/maui/migration/native-essentials?view=net-maui-8.0&tabs=android#initialize-the-platform) and note that the `Microsoft.Maui.ApplicationModel` namespace is listed in the using statements at the top.

If you still think there is an problem in the .NET MAUI SDK, please open a new issue with a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md). Thank you!
