### ISSUE TITLE
Line Shape not redraw when X2Property change with binding

### ISSUE THREAD

**Issue by Vannoctar2** [dotnet/maui#21258]
### Description

Hello,

I customized a contentView to be able to act directly on the scrolling of a page by clicking on buttons. On Xamarin, it worked wonderfully.

But on Maui, it's a different story.

I define lines and ellipses and bind the "LineWidth" value to the X2 property. I'm looking for the screen size from the SizeChanged event. The data is well modified and displayed correctly in a label. But the size of the lines remains the same. Where can this bug come from and how to fix it?

### Steps to Reproduce

1 - Open the project
2 - Launch the MainPage
3- The view with circles appears. The linewidth value is not 0 but the lines length is 0.

### Link to public reproduction project repository

https://github.com/Vannoctar2/ReportBugMaui

### Version with bug

9.0.0-preview.1.9973

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14 - API 34. Emulator and other devices.

**Comment by Vannoctar2** [comment]
The actual result :
![image](https://github.com/dotnet/maui/assets/64914479/f3eacdef-92c7-4ddf-b9e0-d935f76c3f3e)

Expected result:

![image](https://github.com/dotnet/maui/assets/64914479/0f903eee-87dd-474e-9810-9e77e2cdd0de)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2. Not repro on Android platform with sample project.
https://github.com/Vannoctar2/ReportBugMaui
![image](https://github.com/dotnet/maui/assets/77434865/c913d4fa-ded2-4b5f-a10b-9b843ae6cf25)

**Comment by Vannoctar2** [comment]
> Vérification de ce problème avec Visual Studio 17.10.0 Preview 2. Pas de reproduction sur la plateforme Android avec un exemple de projet. https://github.com/Vannoctar2/ReportBugMaui ![image](https://private-user-images.githubusercontent.com/77434865/313560026-c913d4fa-ded2-4b5f-a10b-9b843ae6cf25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDI2NzUsIm5iZiI6MTcxMDc0MjM3NSwicGF0aCI6Ii83NzQzNDg2NS8zMTM1NjAwMjYtYzkxM2Q0ZmEtZGVkMi00YjVmLWExMGItOWI4NDNhZTZjZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MDYxOTQ1M2ZiN2VmZDVkMTMwZWVkYzE5NmU3OGNiMDcwMDdiMDQxMGMwYWQxMmRkNjBmOTMyODgzZjAyZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Hf1eBqzkue2uBzYacrLKmFzn8BD5P9EiqEWXekQSYs)

Sur quelle version d'Android ?

**Comment by Vannoctar2** [comment]
I update the version yesterday. I use the last version of Visual Studio preview.

**Comment by Zhanglirong-Winnie** [comment]
> > Vérification de ce problème avec Visual Studio 17.10.0 Preview 2. Pas de reproduction sur la plateforme Android avec un exemple de projet. https://github.com/Vannoctar2/ReportBugMaui ![image](https://private-user-images.githubusercontent.com/77434865/313560026-c913d4fa-ded2-4b5f-a10b-9b843ae6cf25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDI2NzUsIm5iZiI6MTcxMDc0MjM3NSwicGF0aCI6Ii83NzQzNDg2NS8zMTM1NjAwMjYtYzkxM2Q0ZmEtZGVkMi00YjVmLWExMGItOWI4NDNhZTZjZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MDYxOTQ1M2ZiN2VmZDVkMTMwZWVkYzE5NmU3OGNiMDcwMDdiMDQxMGMwYWQxMmRkNjBmOTMyODgzZjAyZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Hf1eBqzkue2uBzYacrLKmFzn8BD5P9EiqEWXekQSYs)
> 
> What is the Android version?

@Vannoctar2 I use Android14-API34 emulator, and android device(XiaoMi), this issue not repro.

**Comment by Vannoctar2** [comment]
Initially I was using this view in a carouselview. seeing that it worked sometimes, I said to myself that it might be the carouselview that was causing the problem. Obviously, this is not the case since I isolated the view in a contentpage.

**Comment by Vannoctar2** [comment]
> > > Vérification de ce problème avec Visual Studio 17.10.0 Preview 2. Pas de reproduction sur la plateforme Android avec un exemple de projet. https://github.com/Vannoctar2/ReportBugMaui ![image](https://private-user-images.githubusercontent.com/77434865/313560026-c913d4fa-ded2-4b5f-a10b-9b843ae6cf25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDI2NzUsIm5iZiI6MTcxMDc0MjM3NSwicGF0aCI6Ii83NzQzNDg2NS8zMTM1NjAwMjYtYzkxM2Q0ZmEtZGVkMi00YjVmLWExMGItOWI4NDNhZTZjZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MDYxOTQ1M2ZiN2VmZDVkMTMwZWVkYzE5NmU3OGNiMDcwMDdiMDQxMGMwYWQxMmRkNjBmOTMyODgzZjAyZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Hf1eBqzkue2uBzYacrLKmFzn8BD5P9EiqEWXekQSYs)
> > 
> > 
> > What is the Android version?
> 
> @Vannoctar2 I use Android14-API34 emulator, and android device(XiaoMi), this issue not repro.

I realize that the Android version for my tests is  : Pixel5- Api30- Android 11.

Does it work for you?

**Comment by Vannoctar2** [comment]
![image](https://github.com/dotnet/maui/assets/64914479/f5748845-5edf-4b2d-97b9-9df95087c021)

I test on android 14- Api 34. No working...

**Comment by Vannoctar2** [comment]
With the last version of Maui Controls on Nuget, it's work. Sorry.
