### ISSUE TITLE
[Android]System.TypeLoadException: Could not resolve type with token 01000004 from typeref

### ISSUE THREAD

**Issue by satya-prismhr** [dotnet/maui#21256]
### Description

.NET MAUI 7 application is crashing randomly in android with error **System.TypeLoadException: Could not resolve type with token 01000004 from typeref (expected class 'System.Reflection.AssemblyInformationalVersionAttribute' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')**

### Steps to Reproduce

No steps to reproduce, its a random crash

### Version with bug

7.0.59

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All Android Devices

### Did you find any workaround?

No

### Relevant log output

`
System.TypeLoadException: Could not resolve type with token 01000004 from typeref (expected class 'System.Reflection.AssemblyInformationalVersionAttribute' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089') at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider , Type , Boolean ) at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider , Type , Boolean ) at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type , Boolean ) at Microsoft.Maui.Platform.ReflectionExtensions.GetCustomAttributesSafe(Assembly assembly, Type attrType) at Microsoft.Maui.Controls.Internals.Registrar.RegisterAll(Assembly[] assemblies, Assembly defaultRendererAssembly, Type[] attrTypes, InitializationFlags flags, Action1 viewRegistered, IFontRegistrar fontRegistrar) at Microsoft.Maui.Controls.Internals.Registrar.RegisterAll(Type[] attrTypes, InitializationFlags flags, IFontRegistrar fontRegistrar) at Microsoft.Maui.Controls.Internals.Registrar.RegisterAll(Type[] attrTypes, IFontRegistrar fontRegistrar) at Microsoft.Maui.Controls.Compatibility.Forms.RegisterCompatRenderers(IMauiContext , Nullable1 ) at Microsoft.Maui.Controls.Compatibility.Forms.SetupInit(IMauiContext , Assembly , Nullable1 ) at Microsoft.Maui.Controls.Compatibility.Forms.Init(IMauiContext , Nullable1 ) at Microsoft.Maui.Controls.Compatibility.Forms.Init(IActivationState , Nullable1 ) at Microsoft.Maui.Controls.Compatibility.Hosting.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__1_1(IMauiContext ) at Microsoft.Maui.Platform.ApplicationExtensions.<>c__DisplayClass1_0.<CreatePlatformWindow>b__0(OnMauiContextCreated del) at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnMauiContextCreated](IServiceProvider services, Action1 action) at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState) at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState) at TLM.NextGenMobileApp.MainActivity.OnCreate(Bundle savedInstanceState) at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr , IntPtr , IntPtr ) at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V , IntPtr , IntPtr , IntPtr )
'

**Comment by satya-prismhr** [comment]
Hi @PureWeen @dotnet-policy-bot 

I am unable to replicate this issue in debug mode and its a random crash happening in the production build. I have shared all the log details found in App center. Please check those details and help me out here

Thanks in advance

**Comment by LeDahu22** [comment]
Same here on Visual Studio 17.9.4 / MAUI 8.0.14 / Android 10
