### ISSUE TITLE
[iOS] button.SetBackgroundImage(image, state) does not work

### ISSUE THREAD

**Issue by kassemyu** [dotnet/maui#21265]
### Description

Hey,

the button.SetBackgroundImage(image, state) seems to not work. Changing the background color works, which is unfortunately not sufficient because I need to show different backgrounds for different states. I saw that 8.0.6 had a fix for the ContentPage background in #17789 and a similar bug was resolved in nightly version for 8.0.0 in #12959 but somehow is still present according to the last comment of the thread. Are there any workarounds for this? 

Thanks in advance!

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by PureWeen** [comment]
@kassemyu  can you use the VSM that's built into .NET MAUI?

if you want to replace how .NET MAUI is handling background your best bet is to use mappers to replace how .NET MAUI  is setting the background

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize?view=net-maui-8.0

**Comment by kassemyu** [comment]
@PureWeen thanks for your reply. I forgot to mention that I use handlers to design iOS and Android buttons (migration from renderers to handlers). I don't use visual state managers in this case. After writing this ticket I found a workaround with Mappers. When having a mapper for Button.IsPressed, the  native button states "Normal" and "Highlighted" are triggered when the button is pressed. I change the background color respectively via:

`handler.PlatformView.BackgroundColor = _backgroundColor;`

Previously, I was using a rounded rectangle shape which is then colored and displayed as background via 

`button.SetBackgroundImage(image, state);`

Other functions using the state such as 

` handler.PlatformView.SetTitleColor(_titleNormalColor, UIControlState.Normal);`

work fine.  The issue seems to be in the button.SetBackgroundImage.

**Comment by PureWeen** [comment]
@kassemyu Do you think this is still a MAUI issue? or something specific to iOS?

Is this something you could test with a MAUI iOS app (not using our cross platform elements) see if that acts accordingly?

**Comment by kassemyu** [comment]
Hey @PureWeen, it was working on Xamarin that way so I suspect it to be a MAUI issue, I can't tell for sure unfortunately.

**Comment by mattleibow** [comment]
Since you are overriding the background logic, you might just need to disable the mapper:

```cs
builder
  .ConfigureMauiHandlers(handlers =>
  {
    // do not map the background
    ButtonHandler.Mapper.ReplaceMapping("Background", (handler, view) => {
    });
  });
```
