### ISSUE TITLE
NET 8 :: Sizing of windows, text buttons and icon buttons are off

### ISSUE THREAD

**Issue by linkaiyu** [dotnet/maui#21285]
### Description

After upgrading to NET8.0.10 (from Net7), sizing of buttons with text and icons appears to be changed. In Net7, when a button has image and text, the image would scale when the size of button changes, but in NET8.0.10 the image would get cropped on Mac. (it is not a problem on Windows)

### Steps to Reproduce

use this xaml to see the difference between Net7 and Net8.0.10 on Mac

```XAML
<Button Text="Button" ImageSource="watchlist.png" MinimumWidthRequest="1" MinimumHeightRequest="1" WidthRequest="100" HeightRequest="32" BackgroundColor="Gray" Padding="11,9,0,9" />
```

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.100

### Affected platforms

macOS

**Comment by linkaiyu** [comment]
link to repro
https://github.com/linkaiyu/MauiNet8-0-10

**Comment by ninachen03** [comment]
Verified on VS for Mac 17.6.10 build 428 and Microsoft.Maui.Controls is 8.0.20-nightly.10326+sha.23171190fc-azdo.9256731 , can repro it on MacCatalyst platform.
![image](https://github.com/dotnet/maui/assets/128687574/59f832d0-bbe8-4779-b96a-1bbb65c62a9a)
