### ISSUE TITLE
Add Maui 8.0.10 to list of Versions (etc)

### ISSUE THREAD

**Issue by MitchBomcanhao** [dotnet/maui#21298]
### Description

Sounds like during the release process someone forgot to update the list of versions when logging issues etc.
this means that people will be logging bugs and marking them against the wrong version.

see example
![image](https://github.com/dotnet/maui/assets/31066938/38a8d797-89ad-4bc4-a6e5-c9bc9fa37390)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

**Comment by ninachen03** [comment]
We can repro this issue and we think it is not related to maui product, we need update the Microsoft.Maui.Controls version in Github web.
and there is a workaround, you can select anyone version and save the issue, then editor the version that you created one.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/pull/21309
