### ISSUE TITLE
.NET 8.0.203 Doesnt compile non .xaml files to the xml namespace "clr-namespace"

### ISSUE THREAD

**Issue by mrajkovicpta** [dotnet/maui#21299]
### Description

When compiling any project in blazor hybrid with the default setup will fail with the error: 
```
1>MainPage.xaml(11,84): XamlC error XFC0000: Cannot resolve type "[ProjectNamespace]:Routes".
```
The file will look like the following
```
<?xml version="1.0" encoding="utf-8"?>

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:[ProjectNamespace]"
             x:Class="IFI.QRScanner.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">

        <BlazorWebView x:Name="blazorWebView" HostPage="wwwroot/index.html">
            <BlazorWebView.RootComponents>
			<RootComponent Selector="#app" ComponentType="{x:Type local:Routes}" />
            </BlazorWebView.RootComponents>
        </BlazorWebView>    
</ContentPage>

```

despite the code completion finding all symbols in the [ProjectNamespace] namespace, when compiling these wont be included for some reason. 
Changing `local:Routes` to any xaml file will allow it to compile but as the type isnt a blazor page inside a blazor web view the app will load with nothing displayed and an exception.

Compiling with the new sdk also gives this warning which is not displayed when compiling with earlier versions but it could just be compiler noise 

```
1>CSC : warning CS9057: The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.203\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'.
```

---

# Last working version to my knowledge
 - .Net 8.0.101 sdk
 - .net 8.0.1 runtime
 -  Visual studio version is irrelevant

### Steps to Reproduce

1, Create new blazor hybrid app via dotnet new maui-blazor
2. Attempt to run

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Not applicable

### Did you find any workaround?

Reverting sdk to 8.101 (a later one might work but I have not tried)

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by mrajkovicpta** [comment]
Issue was not resolved with nightly build, instead it was solved by updating visual studio (Im guessing this was because it forced a workload update)
