### ISSUE TITLE
Seemingly over-aggressive dependency caching when building iOS app

### ISSUE THREAD

**Issue by Ghostbird** [dotnet/maui#21302]
### Description

We have a dependency on a sibling project DLL.
Therefore we have a target that builds this project if the appropriate DLL doesn't exist yet. This target has `BeforeTargets="BeforeBuild"`. This ensures that if needed, the sibling project DLL is built before the main build starts.
This works fine in most circumstances, but fails on MacOS when we try to build the iOS app.

A minimum reproduction is at: https://github.com/Ghostbird/reproduce-assembly-caching

### Steps to Reproduce

1. Clone https://github.com/Ghostbird/reproduce-assembly-caching
2. Run `./build-app.sh`. This succeeds when I run this on my machine (Debian) where it builds an Android app. It fails if you run it on MacOS where it tries to build an iOS app.
3. [On MacOS] run `./build-app.sh` again. Now it succeeds.
4. Run `./clean.sh`
5. Run `./build-console.sh`. This does not fail on MacOS, and is included to show that it seems MAUI related, rather than a generic `dotnet` on MacOS issue.

### Link to public reproduction project repository

https://github.com/Ghostbird/reproduce-assembly-caching

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

It's been there since the first MAUI 8 at least, but before that we had a slightly more convoluted build set-up that might not trigger this issue.

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

Affects build for iOS on MacOS Sonoma Xcode 15.1

### Did you find any workaround?

For now we run the build twice like this:

`dotnet build app || dotnet build app`

This is kind of stupid, but it works. The first time, it correctly builds the DLLs, but the main target aborts because of this bug. Because the command failed, it runs the second command (which is identical). The second time, it sees the DLLs are there, and skips to the main build, which now succeeds.

### Relevant log output

```shell
% ./build-app.sh
MSBuild version 17.9.6+a4ecab324 for .NET
  Determining projects to restore...
  Restored /Users/gijsbert/workspace/reproduce-assembly-caching/app/app.csproj (in 181 ms).
  Detected signing identity:
          
    Bundle Id: com.companyname.app
    App Id: com.companyname.app
/usr/local/share/dotnet/sdk/8.0.203/Microsoft.Common.CurrentVersion.targets(2389,5): warning MSB3106: Assembly strong name "../lib/bin/Debug/net8.0/lib.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\). [/Users/gijsbert/workspace/reproduce-assembly-caching/app/app.csproj::TargetFramework=net8.0-ios]
  MSBuild version 17.9.6+a4ecab324 for .NET
    Determining projects to restore...
    Restored /Users/gijsbert/workspace/reproduce-assembly-caching/lib/lib.csproj (in 27 ms).
    lib -> /Users/gijsbert/workspace/reproduce-assembly-caching/lib/bin/Debug/net8.0/lib.dll
  
  Build succeeded.
      0 Warning(s)
      0 Error(s)
  
  Time Elapsed 00:00:00.53
/Users/gijsbert/workspace/reproduce-assembly-caching/app/AppShell.xaml.cs(1,7): error CS0246: The type or namespace name 'lib' could not be found (are you missing a using directive or an assembly reference?) [/Users/gijsbert/workspace/reproduce-assembly-caching/app/app.csproj::TargetFramework=net8.0-ios]

Build FAILED.

/usr/local/share/dotnet/sdk/8.0.203/Microsoft.Common.CurrentVersion.targets(2389,5): warning MSB3106: Assembly strong name "../lib/bin/Debug/net8.0/lib.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\). [/Users/gijsbert/workspace/reproduce-assembly-caching/app/app.csproj::TargetFramework=net8.0-ios]
/Users/gijsbert/workspace/reproduce-assembly-caching/app/AppShell.xaml.cs(1,7): error CS0246: The type or namespace name 'lib' could not be found (are you missing a using directive or an assembly reference?) [/Users/gijsbert/workspace/reproduce-assembly-caching/app/app.csproj::TargetFramework=net8.0-ios]
    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:04.59
```

Here's the accompanying binlog of that failing app build: 
[msbuild.bin.log](https://github.com/dotnet/maui/files/14650068/msbuild.bin.log)

Note: The file was originally named `msbuild.binlog` but that could not be uploaded because Github has rather arbitrary rules about file _extensions_ (rather than file content).

**Comment by PureWeen** [comment]
@rolfbjarne  thoughts?

**Comment by jaosnz-rep** [comment]
Can repro this issue on Mac with sample project.

**Comment by rolfbjarne** [comment]
The problem is that due to how we inject our own build targets into the build, there ends up being build ordering problem.

Technically your target needs to run before the ResolveAssemblyReferences target, which usually doesn't happen before BeforeBuild. However, due to the injection of our own targets, that changes, so by the time the build iterates over all the references and adds them as C# references, your custom target hasn't executed yet.

The fix is simple, and should work everywhere: run your target before `ResolveAssemblyReferences` instead:

```xml
  <Target Name="Build Library"
    BeforeTargets="ResolveAssemblyReferences">
	...
  </Target>
```

That makes the test case work for me.

**Comment by Ghostbird** [comment]
Ah, thanks a lot. That fixes it indeed. I didn't know about the target `ResolveAssemblyReferences` but it seems that it in all cases is the more appropriate one. That is specifically the step that requires the DLLs.

So the lesson learned is, if you want this to reliably work, you must use the appropriate `BeforeTargets`, and that is `ResolveAssemblyReferences` not `BeforeBuild`.
