### ISSUE TITLE
Incomplete Element Tree in UI Inspector (Accessibility Insights) for .NET MAUI

### ISSUE THREAD

**Issue by SimonDraime** [dotnet/maui#21310]
### Description

I am currently updating my Xamarin.Forms application to .NET MAUI, and I’ve encountered an issue when inspecting the application using UI inspectors (such as Accessibility Insights or inspect.exe). In Xamarin.Forms, I used `AutomationId` on various elements to facilitate automated testing. However, when inspecting the UI tree in .NET MAUI using tools like Accessibility Insights, I’ve noticed that certain controls (such as `Grid`, `ContentView`, `AbsoluteLayout`, and maybe others) are not displayed in the element tree.

With Xamarin.form:
![Xamarin_UWP](https://github.com/dotnet/maui/assets/124704595/60076cac-e89e-4ace-ab4f-53495f55c301)

With MAUI:
![Maui_WinUI](https://github.com/dotnet/maui/assets/124704595/36d66f9b-4c61-405f-8802-f5f399202bbe)

Is there a reason why certain controls are not visible in the UI inspector for .NET MAUI.
Are there alternative ways to identify and interact with these controls for automated testing in .NET MAUI?

### Steps to Reproduce

1. Create a simple .NET MAUI project.
2. Add controls like Grid, ContentView, and AbsoluteLayout in the XAML.
3. Set AutomationId properties for these controls.
4. Use a UI inspector (e.g. Accessibility Insights) to inspect the element tree.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 Build 22631.3296 (app framework net8.0-windows10.0.19041.0)

**Comment by PureWeen** [comment]
@SimonDraime by default, on WinUI, layouts aren't exposed to accessibility insights because they aren't relevant to the accessibility tree. If you want them to show up you'd have to override the CreateUIAutomator on the native views and make the element surface in the accessibility tree. We had this on the FrameRenderer in XF but it broke accessibility so we removed it.

**Comment by SimonDraime** [comment]
Hi @PureWeen,

Thank you for your response. You mentioned that to expose layouts to the accessibility tree, I would need to override the `CreateUIAutomator` on the native views. However, I’m unable to find a method named `CreateUIAutomator` in the base classes of MAUI/WinUI views and when searching for `CreateUIAutomator` on Google the only result I get is this Github issue. Could you please provide more details or point me to the relevant documentation or sample code? This would greatly help me in understanding how to expose these elements in the accessibility tree. 
Thank you.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/blob/c7d1a4ec8d857aba674362d2777d98855f0ca67a/src/Core/src/Platform/Windows/MauiButton.cs#L20-L23
