### ISSUE TITLE
Unable to hit debug point in C# Library from Android MAUI .NET7 App

### ISSUE THREAD

**Issue by VaibhavMethuku01** [dotnet/maui#21323]
### Description

We have a MAUI .NET 7 UWP Application, from the MAUI App C# .NET 6 library is being called. Visual Studio 2022 IDE we are using for development.

When it comes to Windows build, we are able to debug the C# library methods. However from Android, debugging point doesn't hits and same methods are failing in execution which succeeds in windows build. As we are not able to debug the methods altogether for android, hence it is becoming difficult to troubleshoot the problem.

Concerned C# .NET 6 library have embedded resources files, text files, C# class files. VB files .

We are calling the C# library via reflection from MAUI App. However, we tried to directly call the library through project reference , then also debugging didn't worked.

Few of the troubleshooting steps done, but it didn't worked -

Ensured that, within the .NET MAUI project settings under Android options, both the "Use Shared Runtime" and "Enable Developer Instrumentation" settings are activated.

Adjusted the project's PropertyGroups to specify Android as the primary target in the TargetFrameworks.

Explored the possibility of disabling all XML Hot Reload options through Visual Studio's path at Tools -> Options.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

We had tried couple of work arounds. But none of them worked so far.

**Comment by drasticactions** [comment]
The underlying debugger tooling is not MAUI UI specific and is maintained by Visual Studio. I would redirect your issue there first to see if it's something more general with Android debugging within VS.
