### ISSUE TITLE
[Bug] ArrangeChildren does not called for children in custom layout

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#2132]
### Description

I was created the parent custom layout that holds another three custom layouts. The parent custom layout holds the instances for their children layouts. Arrange using the instances not triggers the children arrange children method so the children does not rendered.

Note: If i arrange the children from Children property then it works. I was arrange the children by using its local instance then it does not shown. 

### Steps to Reproduce

1. Create the custom layout which is used to layout the children layout(store the children in list named layouts)
2. Arrange the layouts by saved instances in layouts list
3. The children not shown on view

### Expected Behavior

- Children ArrangeChildren method will call when Arrange the children by its local instance

### Actual Behavior

- Children ArrangeChildren method does not called when Arrange the children by its local instance

**Comment by kristinx0211** [comment]
@Sasikumar3595 Thank you so much for your bug report! Unfortunately, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
