### ISSUE TITLE
[Android/iOS][NavigationPage] Inheritance of NavigationPage breaks TitleView

### ISSUE THREAD

**Issue by Domik234** [dotnet/maui#21327]
### Description

Hello,

I've discovered that when I try to create custom NavigationPage implementation for setting default values like colors, navbar separator visibility and etc. - Title won't render or ignores settings.

<details>
<summary>Example of non-inherited and inherited NavigationPage (without setting any value!)</summary>

<details>
<summary>Android (10.0 / API 29)</summary>

![image](https://github.com/dotnet/maui/assets/9479585/b7adbcc1-5272-4f0a-8911-2c784246be49)

</details>
<details>
<summary>Android (10.0 / API 29) Video</summary>

[NavPageInheritance-Android.webm](https://github.com/dotnet/maui/assets/9479585/93506a4f-d012-4142-890b-fd846103ec8e)

</details>

<details>
<summary>iOS (XS 16.5)</summary>

![image](https://github.com/dotnet/maui/assets/9479585/2ba91815-5c36-4a89-9792-d864a7eaf123)

</details>
<details>
<summary>iOS (XS 16.5) Video</summary>

[NavPageInheritance-iOS.webm](https://github.com/dotnet/maui/assets/9479585/03eda0e0-14b6-4345-adbe-3bc2329a5137)

</details>
</details>
For easier testing I've used page (SelectionPage) that changes App.Current.MainPage for noninherited or inherited case but building it directly with using of one or another acts the same.

Tested on real devices (Honor 20 / iPhone XS).
MAUI on .NET 8 (haven't tested on .NET 6/.NET 7). Version of MAUI 8.0.x looks like doesn't matter.

### Steps to Reproduce

Please use provided repo (it's the same as images/video source)

### Link to public reproduction project repository

https://github.com/Domik234/Issue-MauiInheritanceBreaksNavigationPage

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

Tested on Android 10 | iOS 16.5

### Did you find any workaround?

No.

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2 (8.0.10 &8.0.0-rc.2.9530). Can repro it with sample project

**Comment by Domik234** [comment]
@PureWeen thank you, you are completely right! We are learned in the C# world that derived class inherits properties and methods from base class so intuitively this leads to thinking that it should be inherited too. Closing this issue.
