### ISSUE TITLE
Connect To Mac - Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by ajvanlaningham** [dotnet/maui#21344]
### Description

![image](https://github.com/dotnet/maui/assets/77026821/e1dfb415-e4d0-4fed-8f2a-79702a37f46a)

While attempting to connect to a mac to use it as a deployment agent for .NET MAUI application, I get the error "Object Reference not set to an instance of an object" with no other context. I see this has been an issue in the past on your end but has since been marked as resolved. I have uninstalled/updated visual studio on both of  my machines, upgraded to the latest versions of .NET on both of my machines, deleted and reinstalled xcode on my macbook pro, switched from iOS 17.2 to 17.4... Running out of ideas. 

### Steps to Reproduce

1. On a local network macbook pro, freshly install .NET 8, Visual Studio for Mac, and Xcode 15.3 / iOS 17.4
2. On a windows machine, create a new MAUI app referencing .NET 8 using visual studio 2022 enterprise (17.9.4)
3. Attempt to pair with macbook on local network. 

Observe the error. 

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.4

**Comment by drasticactions** [comment]
This tooling is maintained by the Visual Studio team and can't be addressed in this repo. If you file this issue with VSFeedback it can be addressed by the proper team. Thanks!

**Comment by davidortinau** [comment]
Try Xcode 15.2 instead. Xcode 15.3 is not yet fully compatible. https://github.com/dotnet/maui/wiki/Release-Versions
