### ISSUE TITLE
Wrong Answer in FAQ

### ISSUE THREAD

**Issue by nerdunit** [dotnet/maui#2134]
Hi, in https://github.com/dotnet/maui/wiki/FAQs there is a wrong question/answer.
The question "Will .NET MAUI allow deployment of one code base across iPhone, Android, Windows Desktop, macOS Desktop and Linux?"
Has the answer "Yes, checkout this chart in the README to see the supported platforms.", however there is no linux support for MAUI

**Comment by vhugogarcia** [comment]
This was moved to MS official page and they were updated.

**Comment by nerdunit** [comment]
> This was moved to MS official page and they were updated.

Sorry, I don't understand what do you mean

**Comment by Eilon** [comment]
Hi, I updated the FAQ here: https://github.com/dotnet/maui/wiki/FAQs

**Comment by Eilon** [comment]
(I removed mentions of Linux, because it is not currently supported or planned.)
