### ISSUE TITLE
[Bug]  Frame is not rendered if the Frame.IsClippedToBounds property is set to true

### ISSUE THREAD

**Issue by MariyaGordeeva** [dotnet/maui#2135]
### Steps to Reproduce

1. Create a MAUI app.
2. Put Frame on MainPage.xaml.
3. Set size and corner radius for Frame and set IsClippedToBounds = True.
4. Deploy to Android Local Device.

### Code
```xaml

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp.MainPage">

     <Frame BackgroundColor="Yellow" 
                                   HeightRequest="100"
                                   WidthRequest="100"
                                   VerticalOptions="Center"
                                   HorizontalOptions="Center"
                                   HasShadow="False"  
                                    IsClippedToBounds="True"
                                   CornerRadius="50">
    </Frame>
</ContentPage>
```

### Expected Behavior
Frame with rounded corners (circle) and yellow background color in the center of the MainPage 
![Expected](https://user-images.githubusercontent.com/41049348/129754920-19fb2cf4-367c-49f7-afab-b79b30888054.png)

### Actual Behavior
Empty MainPage
![Actual](https://user-images.githubusercontent.com/41049348/129754979-b67f3ed7-d022-49dd-96e8-4996aa2cb1bf.png)

### Basic Information

IDE: Visual Studio 2022 
Platform Target Frameworks:
Android: 30, iOS 12.5

**Comment by mattscheffer** [comment]
No longer repro. Tested with VS 17.2.0 Preview 1 using Pixel 5 (Android 11). Label appears correctly.

![image](https://user-images.githubusercontent.com/10537189/154360587-432939d9-d815-45f4-ad4b-908227d33190.png)
