### ISSUE TITLE
Xamarin Forms Android WebView Background Image works. MAUI Android WebView Background Image doesn't work

### ISSUE THREAD

**Issue by powerteqtpitman** [dotnet/maui#21355]
### Description

I am porting an app from Xamarin Forms to MAUI with the WebView.

We are hitting a website on our Azure servers. On iOS everything works fine on both the Xamarin version and the MAUI version of the app.When I run the Xamarin version of the app on Android, everything also works fine.

When I run the MAUI version of the app on Android, however, there is a background image that isn't working. This image just doesn't show up. I have tried many things to get it to work and just can't figure it out.

I would like to keep the URL of the website to just those who will help me out. If you are willing to help, please PM me and I will give you the URL of the website.

When I inspect the pages from Android using the Chrome developer inspect tool, here is the topmost css that is being shown:

`body {`
`    background-image: url(/static/media/BackgroundImage.1861cdb8.png);`
`    height: 100%;`
`    background-position: 50%;`
`    background-repeat: no-repeat;`
`    background-size: auto;`
`}`

You can see in this image that the background image is in that location:

![image](https://github.com/dotnet/maui/assets/29659503/3d51f89e-d8b3-458e-8ad6-142a0362a763)

As I said above this all works and shows that image in the Xamarin Forms build of the app on both iOS and Android and also works fine on the MAUI build for iOS.

### Steps to Reproduce

1. Create a MAUI app with a WebView in it.
2. Browse to the site given using a private message to the author of this bug
3. Notice that the background image shows up on iOS, but not on Android

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by powerteqtpitman** [comment]
I do not want to have the URL to our server here in a public forum. I am concerned about making that server a target for attack.

I have a repo ready, but don't want to publish it publicly.

Is there some way to make a private repo and then have any engineers who can work on this sending me a PM for details?

**Comment by powerteqtpitman** [comment]
Is there some way to work with someone directly to share the repo I made with them?

This is really holding me up.

**Comment by QianaJiao** [comment]
Hi, @powerteqtpitman. You can use vs feedback to attach a project that's not publicly visible.
