### ISSUE TITLE
MAUI Community Toolkit EventToCommandBehavior Fails to Pass EventArgs Arguments in Versions > 1.0

### ISSUE THREAD

**Issue by VidyalakshmiMani** [dotnet/maui#21354]
### Description

In versions of the CommunityToolkit.Maui greater than 1.0, the EventToCommandBehavior does not correctly pass event arguments to the bound command's Execute method. This results in the EventArgs parameter being null, which can lead to issues in event handling logic that relies on event-specific data. 

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by drasticactions** [comment]
If your issue is with a CommunityToolkit function, you should file it in the [CommunityToolkit](https://github.com/CommunityToolkit/Maui). If there's something specific within MAUI that would need to be addressed then feel free to reopen this but this feels specific to the CommunityToolkit.
