### ISSUE TITLE
[net9.0][testing] Control iOS device tests don't finish

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#21362]
### Description

There's seems to be a issue with the device tests on iOS on net9

### Steps to Reproduce

https://dev.azure.com/xamarin/public/_build/results?buildId=111599&view=logs&jobId=3b5811f5-993d-5a58-5fa6-4f9503529a9c

### Version with bug

9.0.0-preview.1.9973

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.10 SR3

### Affected platforms

iOS

**Comment by ivanpovazan** [comment]
I can take a look at this.

**Comment by rmarinho** [comment]
This seems to be fixed on the latest net9 previews
