### ISSUE TITLE
iOS Publishing uses project name and ignores bundle identifier

### ISSUE THREAD

**Issue by lhughey** [dotnet/maui#21365]
### Description

The following command creates an IPA with the wrong file name.

` dotnet publish -f $(app-target-framework-ios) -c Release /p:ApplicationId=$(app-id-ios) /p:ApplicationDisplayVersion=1.1 /p:ApplicationVersion=1.1 /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false`

Expected behavior: An IPA with the same name as the bundleIdentifier is created
Actual behavior: The file is named the same as the project name. 

The "ApplicationId" variable above is passing in a value with the format of "com.businessname.appName". This variable is being used in multiple places in the pipeline so I am confident of the value of the variable.

This same issue was reported in this ticket, but was closed due to being stale https://github.com/dotnet/maui/issues/4559

### Steps to Reproduce

1. Create a NET MAUI app. 
2. Create an Azure pipeline pointing to the app (iOS pipeline).
3. Call dotnet publish like ` dotnet publish -f $(app-target-framework-ios) -c Release /p:ApplicationId=$(app-id-ios) /p:ApplicationDisplayVersion=1.1 /p:ApplicationVersion=1.1 /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false`

You will likely be able to remove the ArchiveOnBuild & EnableAssemblyILStripping parameters. You can also hardocde the ApplicationID above.

This is the value being passed to the build command (taken from the build step logs)
`dotnet publish -f net8.0-ios -c Release /p:ApplicationId=com.its.xxxredactedcompany /p:ApplicationDisplayVersion=1.1 /p:ApplicationVersion=1.1 /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false`

The system parameters for the vm Image are:
      vmImage: "macos-13"
      demands: xcode

.net Framework  8.0.203
iOS workload version: 17.2.8043

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS version installed with the

**Comment by Pastajello** [comment]
You can add a -p:IpaPackageName=somethingsomething to the parameters in the build. This will help.

**Comment by PureWeen** [comment]
@rolfbjarne  thoughts?

**Comment by rolfbjarne** [comment]
> Expected behavior: An IPA with the same name as the bundleIdentifier is created
> Actual behavior: The file is named the same as the project name.

Why would you expect the IPA to have the same name as the bundle identifier? We've always used the assembly name + ".ipa" as the filename of the IPA.

If you want a different name, you can pass the `IpaPackageName` property to the build:

```
dotnet publish /p:IpaPackageName=MyIpa.ipa
```

**Comment by lhughey** [comment]
Thanks @Pastajello and @rolfbjarne.
