### ISSUE TITLE
VS2022 (v 17.9.3) will not hit breakpoints in a Task

### ISSUE THREAD

**Issue by buzzbonner** [dotnet/maui#21364]
### Description

I'm creating a Task using Task.Run off App, but no breakpoint is hit during the body of this task, but it is executed successfully.

### Steps to Reproduce

Create a standard .Net Maui Hybrid app using the standard VS template. This should only supports Windows.

In the App.cs, create a new task and in the body of the task add some content and a breakpoint.

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

I have to include Debugger.Break() everywhere, so far from ideal.

**Comment by drasticactions** [comment]
Debugger tooling isn't maintained by this team in this repo. If you file it through Visual Studio Feedback, then the right team can look at it and triage it.

**Comment by buzzbonner** [comment]
Hi, I will now try the latest preview of VS...

**Comment by buzzbonner** [comment]
I have tested with the latest Previiew and it's still a problem. I will raise the issue with the VS team as suggested. Ticket closed.
