### ISSUE TITLE
IsPlatformEnabled is false for RoundRectangle stroke shape of a Border, hence the layouts that are part of the Microsoft.Maui.Controls.Compatibility and their derivateves are not rendered

### ISSUE THREAD

**Issue by marius-jantea** [dotnet/maui#21390]
When setting the StrokeShape for a border, the StrokeShape changed event is triggered, and that adds the StrokeShape element to the `LogicalChildrenInternal` List.

The framework then loops through all the LogicalChildrenInternal list and [if one element has the `IsPlatformEnabled` ](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Layout.cs#L636) set to false, it doesn't further call the `LayoutChildren` method.

A workaround is setting the `IsPlatformEnabled` to true for that element, however, according to the comments, `IsPlatformEnabled` should not be called from outside.

### Discussed in https://github.com/dotnet/maui/discussions/21356

<div type='discussions-op-text'>

<sup>Originally posted by **marius-jantea** March 21, 2024</sup>
Hello, 
I need to use a custom Layout<T> component, and inside of it I want to place a Border that has a RoundRectangle stroke shape. 

I will add bellow a sample code:

                 `<compatibility:FlexLayout BackgroundColor="Pink"  MinimumHeightRequest="200" Grid.Row="2">
                    <ScrollView BackgroundColor="Brown"
                                x:Name="ScrollViewInsideCascadeLayout"
                                Margin="0,0,0,6"
                                Orientation="Vertical"
                                VerticalScrollBarVisibility="Never">
                        <StackLayout  >
                            <StackLayout x:Name="OneLineCheckBoxCell"  ></StackLayout>  
                            <Border Stroke="#C49B33"
                                    StrokeThickness="4"
                                    StrokeShape="RoundRectangle 40,40,0,40"
                                    x:Name="Border"
                                    Background="#2B0B98"
                                    Padding="16,8"
                                    HorizontalOptions="Center">
                                <Label Text=".NET MAUI"
                                       TextColor="White"
                                       FontSize="18"
                                       FontAttributes="Bold" />
                            </Border>
                           <Label Text="hello"></Label>
                        </StackLayout>
                    </ScrollView>
                </compatibility:FlexLayout>`

The problem is that the the scrollview inside the Flex Layout is not displayed. 
I did some investigation, and it seems that the elements are not rendered, because of this condition (the LayotuChildren method is not called because the method returns false):
https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Layout.cs#L636

Does anyone have a workaround for this? If I set the visibility of the border to false, and set it to true when the ScrollView becomes visible, that works. 
I tried setting the IsPlatformEnabled on the Border element, but that doesn't work, since the stroke shape element has the IsPlatformEnabled value false.

Do you have any other ideas / suggestions?

Possible related questions / issues (none with a solution):
https://github.com/dotnet/maui/issues/19274
https://github.com/dotnet/maui/discussions/20534</div>

**Comment by PureWeen** [comment]
@marius-jantea My gut tells me that this probably won't get fixed unless there's a really simple change from a community PR

What bugs are blocking you from using `FlexLayout` ?

**Comment by marius-jantea** [comment]
@PureWeen , thank you for your input! 
We are migrating an application from xamarin to MAUI.

In Xamarin we had a custom layout, that was of `Layout<T> ` which is now a compatibility / legacy type.
Inside that custom layout, we had a border that had the stroke shape defined as a RoundRectangle. And now the layout's children are not displayed anymore when we visit that page. 

We try first to migrate the application and then start fixing the legacy stuff, and we are blocked by this issue (unless we apply the workaround which is not recommended according to the code documentation).

I gave the `FlexLayout` example just to provide a simple way to reproduce the problem (the issue is reproducible on layouts defined in the framework as well, and I took advantage of that). 

Does my answer clarify your question?

Thank you again, have a great week ahead!

**Comment by rmarinho** [comment]
Can't you recreate your Custom layout on .NET MAUI controls new layout system? Did you try and found a road block? Do you have a sample for your custom layout?! 

Thanks

**Comment by marius-jantea** [comment]
> Can't you recreate your Custom layout on .NET MAUI controls new layout system? Did you try and found a road block? Do you have a sample for your custom layout?!
> 
> Thanks

@rmarinho, thank you for your input! 
Our approach was first to migrate to MAUI with minimum changes on the implementation, and then start migrating the MAUI legacy components to the new ones. 
If the custom layout would be of new layout control type, then that will work, but we expected it to work with the original layout type as well.

I will create a sample repository with the example provided in the ticket description (FlexLayout).

Thank you again! Have a great day!

**Comment by Zhanglirong-Winnie** [comment]
Hi, @marius-jantea 
So can you provide the sample repository you created so that we can further reproduce your issue? Looking forward to your reply.

**Comment by jfversluis** [comment]
As already mentioned, chances are small of this actually getting fixed. Adding the add repro tag. If you still have anything to share for this that would be great for if someone else is going to look into it, or maybe you yourself?

Else, maybe just let the "timer" expire and we'll close this for now.
