### ISSUE TITLE
Maui -Android certificate pinning is not kicking in.. but works in ios

### ISSUE THREAD

**Issue by gabsamples6** [dotnet/maui#21396]
### Description

When certificate pinning is setup in the network_security_config  and change a value I expect my app to fail because of certificate pinning .

### Steps to Reproduce

Create any app and add a network_security_config 
and set an expiration date to a date that is expired or change a value in the sha_256

In android nothing happens - in iOS it works!

### Link to public reproduction project repository

n/a

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

no

### Relevant log output

```shell
no
```

**Comment by PureWeen** [comment]
@jonathanpeppers thoughts?

**Comment by gabsamples6** [comment]
Something was wrong at our end.. I will close this ticket as I cannot reproduce
