### ISSUE TITLE
very High Load time in Bindable Layout with vertical Stack Layout 

### ISSUE THREAD

**Issue by thanigaiharan** [dotnet/maui#21405]
### Description

we have a Vehicle summary page as shown in Below Gif which contains below controls.

![Screen Recording 2024-03-23 at 4 07 50 PM-2](https://github.com/dotnet/maui/assets/7297955/752e2017-b165-4a0d-9036-b15e0961ab00)

	Custom Control (Vehicle Layout where we show Vehicle structure with Tires in colors)
	Dynamically Created Item Template to show each Tire Details (1-1, 1-2 … ), we used bindableLayout with Vertical StackLayout to dynamically generate the template. Also the Cell template as Collection View.
	Odometer details Section
	Vehicle Info Section.

  

 

Issue :

1.	Page takes lot of time to load, and Loading time is very high when the number of tires on vehicle is High.
2.	BindableLayout is taking more time to render the UI. Here in the Item Template we have Collection view to display List of tasks.

<img width="405" alt="image" src="https://github.com/dotnet/maui/assets/7297955/cbddb260-7d0f-4a20-b84f-eb7353cdf567">

 

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by joaodarocha1** [comment]
Are you running a debug or release build? I've experienced similar performance issues in debug versions that didn't occur in release builds.

**Comment by thanigaiharan** [comment]
Bindable Layout is not a good option for this Template and with Collectionview it is not feasible since we have a scrollview for this page.
