### ISSUE TITLE
[iOS-Release] CommunityToolkit-MAUI: Showing Toast Crashes 

### ISSUE THREAD

**Issue by HaimoHeymann** [dotnet/maui#21407]
### Description

On iOS only in RELEASE mode: Toast.Show() crashes the app, on Simulator and on iPhone

### Steps to Reproduce

1. Create .NET MAUI App
2. Add Button in MainPage with EventHandler in code behind
3. Inside EventHandler add this line:
 `await Toast.Make("Hello everybody!", CommunityToolkit.Maui.Core.ToastDuration.Short, 20).Show();`

4. Run the app on iOS Simulator or iOS Device and click button -> Crash 

**Environment:**
Microsoft Visual Studio Community 2022 (64-bit) - Version 17.9.3
.NET 8.0
.NET MAUI Community Toolkit 7.0.1

### Link to public reproduction project repository

https://github.com/HaimoHeymann/MauiToast/tree/master

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

iOS 13

### Did you find any workaround?

No

**Comment by Dokug** [comment]
This happened to me as well, a bug is already filed on the community toolkit's repo:
https://github.com/CommunityToolkit/Maui/issues/1752

The workaround described there did work for me:
https://github.com/CommunityToolkit/Maui/issues/1752#issuecomment-1999990148

**Comment by HaimoHeymann** [comment]
Thanks for the link!
According to the suggestion I added these lines to <project>.csproj
```
	<PropertyGroup Condition="$(Configuration.Contains('Release')) And $(TargetFramework.Contains('ios'))">
		<MtouchInterpreter>-all,System.Collections.Immutable</MtouchInterpreter>
	</PropertyGroup>

```
Now the app crashes already while booting ...

**Comment by PureWeen** [comment]
closing in favor of https://github.com/CommunityToolkit/Maui/issues/1752
