### ISSUE TITLE
CarouselView does not render correctly on orientation change

### ISSUE THREAD

**Issue by dfausz-ebsco** [dotnet/maui#21401]
## Issue seen in .Net MAUI in the Carousel View (Android only)

This is a solution made to reproduce an issue found with the CarouselView in .Net MAUI, it has a minimal set of changes from the basic MAUI project template.

The main page contains a CarouselView where the ItemSource is just a list of 10 integers from 0-9 so that there are 10 items in the Carousel. The item template is just a picture that exists in the MAUI project template. 

This is what it looks like when the app is run, the picture is the first item in the CarouselView. 

![Screenshot_20240322-153450](https://github.com/dfausz-ebsco/CarouselIssue/assets/164557428/29895bb6-9706-4959-a977-96f4f16de083)

The issue is that there is inconsistent behavior when changing the orientation of the device, the CarouselView seems to be stuck in between two items. After reaching this state you can swipe to change the CarouselView's selected element and the placement that it rests on will be correct.

![Screenshot_20240322-153520](https://github.com/dfausz-ebsco/CarouselIssue/assets/164557428/aeef6c3e-e796-45a2-a66a-d05502132218)

However, if you do swipe and change the CarouselView after encountering the issue in landscape mode, when you rotate the device back to portrait, the selected image will be slightly off center similar to the issue above but not as skewed. If you swipe to change the CarouselView in this state it will again correct itself.

![Screenshot_20240322-152802](https://github.com/dfausz-ebsco/CarouselIssue/assets/164557428/0745b33b-025b-4e27-916b-6f1ca1713cd7) 

### Steps to Reproduce

1. Create a new MAUI app
2. Add CarouselView to a page
3. Add an ItemTemplate with any kind of element
4. Add a list of any data type with multiple items and bind to ItemSource on the Carousel
5. Run the app and view the Carousel
6. Turn the device sideways to change to landscape
7. Observe the Carousel appears to be halfway in between two elements
8. Swipe to change the Carousel element and observer that CarouselView corrects itself
9. Turn device upright to change back to portrait
10. Observer the Carousel appears to be partially between two elements

### Link to public reproduction project repository

https://github.com/dfausz-ebsco/CarouselIssue

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by ninachen03** [comment]
Can repro this issue at Android platform on the latest 17.10 preview2 (8.0.7 & 8.0.14).
![image](https://github.com/dotnet/maui/assets/128687574/dc14b6a4-6ec1-44e6-8ce6-0a5f80220b85)

**Comment by asi-evin** [comment]
I see this in my project on iOS as well. Have not found a work-a-round yet.

**Comment by PureWeen** [comment]
@asi-evin 

Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by asi-evin** [comment]
> @asi-evin
> 
> Can you test with the latest nightly build? https://github.com/dotnet/maui/wiki/Nightly-Builds

Sorry for not replying sooner, yes I will try and test this today, although I'll note my issue was on iOS so not sure this will help. If it's still there, I'll open a new issue.

**Comment by asi-evin** [comment]
It looks like it did not fix my problem. I do have a hack for it though, so it's not stopping me. I'll create a new issue with a simpler repro than my project. I think it's because I'm using a DataTemplate Selector, but I couldn't see why that would necessarily be an issue, it's all Grids as the topmost layer so I thought it should all be the same.

**Comment by krazazian** [comment]
> It looks like it did not fix my problem. I do have a hack for it though, so it's not stopping me. I'll create a new issue with a simpler repro than my project. I think it's because I'm using a DataTemplate Selector, but I couldn't see why that would necessarily be an issue, it's all Grids as the topmost layer so I thought it should all be the same.

Can i ask what your "hack" was?  I'm having the same issue, and can't figure out what to do to force the resize.

**Comment by asi-evin** [comment]
Sure, I didn't share it because it's quite janky. So while it seems to be working in my setup, no guaruntee it'll work for yours. It involves adding a new property mapping to the CarouselViewHandler. It adds an event handler which invalidates the layout on an orientation change after a small delay, then scrolls to the original position after another little delay (you know a work-a-round is jank when it requires a _second_ delay).

```c#
public static MauiApp CreateMauiApp()
{
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .ConfigureMauiHandlers(handlers => 
            {
#if IOS
                //hack orientation changes on iOS screw up carousel. Force layout reset
                CarouselViewHandler.Mapper.AppendToMapping("CarouselRelayoutHack", (h, v) =>
                {
                    var currentOrientation = DeviceDisplay.MainDisplayInfo.Orientation;
                    var handler = new EventHandler<DisplayInfoChangedEventArgs>(EventHandler);

                    void EventHandler(object? o, DisplayInfoChangedEventArgs e)
                    {
                        if (currentOrientation == DeviceDisplay.MainDisplayInfo.Orientation)
                            return;

                        currentOrientation = DeviceDisplay.MainDisplayInfo.Orientation;

                        var position = v.Position;
                        var item = v.CurrentItem;

                        MainThread.BeginInvokeOnMainThread(async () =>
                        {
                            await Task.Delay(20);

                            var collectionView = h.PlatformView.Subviews[0] as UICollectionView;
                            collectionView?.CollectionViewLayout.InvalidateLayout();

                            await Task.Delay(20);

                            v.CurrentItem = item;
                            v.ScrollTo(position, -1, ScrollToPosition.Center, false);
                            v.Position = position;
                        });
                    }

                    v.Loaded += (sender, args) =>
                    {
                        DeviceDisplay.MainDisplayInfoChanged += handler;

                    };

                    v.Unloaded += (sender, args) =>
                    {
                        DeviceDisplay.MainDisplayInfoChanged -= handler;
                    };
                });
#endif
            })
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("roboto_regular.ttf", "Roboto-Regular");
                fonts.AddFont("roboto_bold.ttf", "Roboto-Bold");
                fonts.AddFont("roboto_italic.ttf", "Roboto-Italic");
            })
            
#if DEBUG
        builder.Logging.AddDebug();
#endif

        return builder.Build();
}
```
