### ISSUE TITLE
XA1018	Specified AndroidManifest 

### ISSUE THREAD

**Issue by msamwelmollel** [dotnet/maui#21406]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Severity	Code	Description	Project	File	Line	Suppression State
Error	XA1018	Specified AndroidManifest file does not exist: C:\Users\msamwelmollel\source\repos\MyFirstMauiApp\MyFirstMauiApp\AndroidManifest.xml.	MyFirstMauiApp	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.52\tools\Xamarin.Android.Common.targets	596

**Comment by jfversluis** [comment]
Hey there, thanks for your interest in .NET MAUI, sorry you hit a little snag here.

Could you elaborate a little bit more about what you were doing when you hit this error message? What were you trying to do? There should be a AndroidManifest.xml file under the Platform/Android folder, can you see it there?

**Comment by DamianSuess** [comment]
Ran into the same problem here as well for the past 2 days. This all started to happen when I upgraded my Target Android API from 31 to 33 to suffice Google Play's new rules.

As a short-term workaround, I manually copied the `AndroidManifest.xml` file from the `Platform/Android/` folder to the project's root. Bing-bang-boom, it compiled.

Coincidentally, I also get false-positive errors about the Central Package Management (which I do use to maintain NuGet versions across projects). Not sure if they coincide.

**Comment by jfversluis** [comment]
Thanks for the extra info @DamianSuess!

Just searched our repo seems there are two older reports of this as well: #19706 and #18827, closing those so we have just 1 issue with all the info. 

If you just create a File > New MAUI project and update that to API 33 does it show this behavior? If so, would you be able to upload that so we can have a look?

**Comment by DamianSuess** [comment]
@jfversluis  Gerald,
Using one of my repos, taking baby steps to reproduce the issue I uncovered a few ways to reproduce it. The most consistent way was when I enabled, `ManagePackageVersionsCentrally` to get NuGet package versions from the `Directory.Packages.props`, accompanied by deleting the `bin` and `obj` folders.

### Test Repository

Currently, I have the following repo/solution set to throw the error for you on one of my sample repo projects

* **Repo**: [https://github.com/DamianSuess/Learn.Maui](https://github.com/DamianSuess/Learn.Maui)
* **Solution**: `Learn.PrismMaui.SampleNav.sln`

### Steps to Fix the Error

1. Edit the `.csproj`
2. Disable, `<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>`
3. (optional) Delete BIN, and OBJ folders
3. Rebuild project

**Comment by DamianSuess** [comment]
@dotnet-policy-bot 

By "_latest public version_" are you referring to [Visual Studio v17.10.5](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.10.5) that was released yesterday? I'd prefer not to use "Preview" product versions to resolve GA issues, as this could have unexpected outcomes for my other projects.

**Comment by DamianSuess** [comment]
On `v17.10.5` this issue is not 100% resolved.
On a fresh repository cloning it will throw XA1018, however, rebuilding resolves it (_sometimes_).

**Comment by DamianSuess** [comment]
May we have a reference link or ID to the resolution/fix?
