### ISSUE TITLE
The privacy report function of iOS is required.

### ISSUE THREAD

**Issue by gwise-vision** [dotnet/maui#21415]
### Description

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests#4239187

In order to create a privacy manifest file, Xcode's privacy report function is also required in VS2022.

### Public API Changes

Xcode automatically generates a privacy report.

### Intended Use-Case

Xcode automatically generates a privacy report.

**Comment by drasticactions** [comment]
This was discussed in https://github.com/xamarin/xamarin-macios/issues/20059. This is not a MAUI UI Specific issue, it would affect anyone building iOS apps, including .NET iOS, etc.

You can view docs for supporting it [here](https://github.com/xamarin/xamarin-macios/blob/main/docs/apple-privacy-manifest.md). Any additional tooling support should be brought up in the xamarin-macios repo.
