### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by ssbssb-cmd** [dotnet/maui#21413]
### Description

Hi I think I have a memory leak issue  potentially which is causing the app to crash - this didn't seem to be an issue with Xamarin.

I have a custom view that I have created (ProfileView) which is made up of a number of elements

- Images
- Borders
- Labels
- Other subviews which themselves are made up of VerticalStackLayouts containing labels, and other elements

ProfileView:
```
<ContentView>
    <VerticalStackLayout>
        <Border> 
            <Label .... />    
           ......
           ......
    </VerticalStackLayout>
</ContentView>
```

I have a SearchView similar to below on which I add ProfileViews
```
<ContentView>
    <AbsoluteLayout x:Name="layout">
    ....
    ....

    </AbsoluteLayout>
</ContentView>
```

I am loading search results and then creating ProfileViews and adding them to the the layout when a user taps on a button.

This will remove the current profileview and add a new one

Remove current ProfileView:

```
 if (currentProfileView != null)
            {
                if (layout.Children.Contains(currentProfileView))
                {
                    var profileView = (ProfileView)currentProfileView.Content;

                    if (profileView != null)
                    {
                        layout.Children.Remove(currentProfileView);
                        currentProfileView = null;
                    }
                }
            }
```

Add new ProfileView:

```
MainThread.BeginInvokeOnMainThread(async () =>
        {
                currentProfileView = createScrollProfileView();
                layout.Children.Add(currentProfileView);
        });
```

```
 private CustomScrollView createScrollProfileView()
    {

        var sView = new ScrollView();

        AbsoluteLayout.SetLayoutFlags(sView, AbsoluteLayoutFlags.All);

        var profileView = new ProfileView();

        var profileVm = new ProfileViewModel();
        profileVm.Profile = vm.Results[vm.CurrentProfileCount];
        profileView.BindingContext = profileVm;

        sView.Content = profileView;

        return sView;

    }
```

Each time i press the button to create a new profile view and remove the existing one, it seems it is not actually clearing or removing the existing item and so then the memory usage etc goes quite high and ultimatly crashes on iOS. Android seems to be OK 

Is there some way that i can manually force the deletion or removal of the ProfileView? I'm relatively new to programming so apologies if this is a basic question 

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by drasticactions** [comment]
@ssbssb-cmd If you could create a sample of how you are laying out your UI, we can try to pinpoint the issues you are seeing. Seeing your code above isn't enough to understand the differences between Xamarin Forms and MAUI and what it or you may have done differently in porting. It doesn't need to be your full application, but something that can show where some view is being held and not released would help get your issue addressed.
