### ISSUE TITLE
Removing TapGestureRecognizer with at least 2 taps causes Exception

### ISSUE THREAD

**Issue by Matt-17** [dotnet/maui#21437]
### Description

When tapping a TapGestureRecognizer with NumberOfTapsRequired of at least 2, which will be removed inside the tap command, it will cause a NullReferenceException in [`InnerGestureListener.cs:65`](https://github.com/dotnet/maui/blob/402fdf7fcc5a550ebc32512791a1121d1961c1bb/src/Controls/src/Core/Platform/Android/InnerGestureListener.cs#L65)
Happens on Android emulator and my phones.

### Steps to Reproduce

1. Create a new MAUI App
2. Replace content of MainPage.xaml `<ContentPage>` with

```xaml
<VerticalStackLayout BindableLayout.ItemsSource="{Binding Items}" HorizontalOptions="Start">
    <BindableLayout.ItemTemplate>
        <DataTemplate x:DataType="system:String">
            <Label Text="{Binding .}" HorizontalOptions="Start">
                <Label.GestureRecognizers>
                    <TapGestureRecognizer NumberOfTapsRequired="2" Command="{Binding TapCommand, Source={RelativeSource AncestorType={x:Type local:MainPage}}}" CommandParameter="{Binding .}" />
                </Label.GestureRecognizers>
            </Label>
        </DataTemplate>
    </BindableLayout.ItemTemplate>
</VerticalStackLayout>
```
3. Replace MainPage.xaml.cs with following: 
```csharp
public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
        BindingContext = this;

    }
    public ObservableCollection<string> Items { get; } = ["Item 1", "Item 2", "Item 3"];

    public ICommand TapCommand => new Command<string>(obj =>
    {
        Items.Remove(obj);
    });
}
```
4. Run app in Android
5. double-tap Item 1, Item 2 or Item 3

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Inserting a short `await Task.Delay()` and then removing the entry works. Also going down to 1 required tap works as well.

**Comment by jaosnz-rep** [comment]
Can repro this issue at Android platform on the latest 17.10 preview2 (8.0.14 & 8.0.6)
