### ISSUE TITLE
Can this cross platform raspberry pi, MAC, Linux?

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/maui#2144]
Can this cross platform raspberry pi, MAC, Linux?

**Comment by vhugogarcia** [comment]
It can on MacOS with Catalist initially.

**Comment by bbhxwl** [comment]
> It can on MacOS with Catalist initially.

Will the support of all platforms be considered in the future?

**Comment by Iron-E** [comment]
I too would appreciate linux support. It's hard to use this when my native platform isn't supported!

**Comment by jfversluis** [comment]
Initial targets are: iOS, Android, WinUI and macOS. As listed here on our Docs: https://docs.microsoft.com/dotnet/maui/supported-platforms

Linux support is being discussed here, go give it your upvote: https://github.com/dotnet/maui/discussions/339
