### ISSUE TITLE
[iOS] Physical Phone device won't open any Maui App with .Net 8

### ISSUE THREAD

**Issue by JPZV** [dotnet/maui#21444]
### Description

As the same as #17268 , any Maui app, either an already existing project, or a new empty app, won't open on my Physical Phone (iPhone 8 with iOS 16.7.6).

Everything is exactly the same as in the mentioned issue. If I try to open an app, it shows the splash screen then closes itself in a fraction of a second.

According to that issue, the problem was an API call from iOS 13 on older phones, but mine isn't either old nor it has an older iOS installed (which is confusing as the OP also didn't have an older iOS, it was just 14.6)

Sadly, my connection to the Mac Host isn't that stable to run an iOS Simulator, but it works at least for compiling and deploying the app correctly, or at least it seems to.

### Additional info:

**Visual Studio 2022 Community**: 17.9.4 (VS 17.9.34714.143)
**.Net**: 8.0.202
**iOS manifest**: 17.2.8004/8.0.100
**xCode**: 15.3

### Steps to Reproduce

1. Create a new empty project with .Net 8
2. Build, Deploy and open the project into an iPhone/iPad
3. Test it

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

iOS 16.7.6

### Did you find any workaround?

Not yet

### Relevant log output

```
Debugger isn't able to connect, the crash happens before it would even try to establish a connection
```

**Comment by dartasen** [comment]
Check #21057, if you have upgraded to the latest xcode version

**Comment by jfversluis** [comment]
As indicated, Xcode 15.3 is not supported right now. Please check the linked issue above. Does that solve it for you?

**Comment by JPZV** [comment]
> Check #21057, if you have upgraded to the latest xcode version

> As indicated, Xcode 15.3 is not supported right now. Please check the linked issue above. Does that solve it for you?

Can confirm. Using Xcode 15.2 works perfectly, so it's a 15.3 problem as #21057
