### ISSUE TITLE
The entry input cursor and the lower border line color have related properties that can be set directly.

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/maui#21441]
### Description

The entry input cursor and the lower border line color have related properties that can be set directly.

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jaosnz-rep** [comment]
Verified on maui 8.0.0-rc.2.9530 and 8.0.21. It is not possible to directly set the input cursor and the lower border line color for the entry in .NET maui and Xamarin.Forms projects, this seems more like a suggestion.

**Comment by HuaFangYun** [comment]
Can you provide the code for the indirect modification method? Sorry, I didn't find the relevant method, thank you!

**Comment by jfversluis** [comment]
Hey @HuaFangYun thanks for the report!

I have a little trouble understanding what you mean by this. It looks like you're looking for a way to set the color of the cursor and the underline of an Entry control, is that correct?
