### ISSUE TITLE
Deployment or Debug removes files in FileSystem.AppDataDirectory

### ISSUE THREAD

**Issue by n3oea** [dotnet/maui#21445]
### Description

I have an application that uses a SQLite database.  While developing under VS 17.9.4 and .NET 8.0.3 (everything is up to date including all NuGet packages), I noticed that I was losing all of my local data on each new debug session.  

The database path is

`Path.Combine(FileSystem.AppDataDirectory, DatabaseFilename);`

I also tried the 
`Path.Combine(FileSystem.Current.AppDataDirectory, DatabaseFilename);`

variant.

The following snippet verified the behavior.  Each time I click DEBUG in Visual Studio, the database is gone.  Yet when I run the app repeatedly on the device (Android emulator or Samsung Galaxy S23 FE), all is happy.  The database remains.  

```
 try
 {
     connectionString = new SqliteConnectionStringBuilder()
     {
         DataSource = ConstantsDB.DatabasePath,
         Mode = SqliteOpenMode.ReadWrite
     }.ToString();

     using (SqliteConnection conn = new(connectionString))
     {
         await conn.OpenAsync();
     }
 }
 catch
 {
     connectionString = new SqliteConnectionStringBuilder()
     {
         DataSource = ConstantsDB.DatabasePath,
         Mode = SqliteOpenMode.ReadWriteCreate
     }.ToString();

     using (SqliteConnection conn = new(connectionString))
     {
         await conn.OpenAsync();
     }
 }
```

### Steps to Reproduce

1.  Create a .NET MAUI app using Microsoft.EntityFrameworkCore.Sqlite
2.  Create a table in SQLite
3.  Put some data into the table
4.  Create a page that shows the data, even in a simple label
5.  Deploy/Debug
6.  Run the app again just on the device (i.e. not debugging)
7.  Deploy/Debug again
8.  Note that the database is gone

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 33 and 34

**Comment by Ghostbird** [comment]
I don't have a solution, but I can provide a data point.‌ In our app we also create an sqlite database on demand, and this has no problems in debugging. However we use https://github.com/praeclarum/sqlite-net to do so, and do not use EF.

Is your SQLite database the only thing that disappears? I know that my debugging extension (.NET Meteor) has an option to uninstall the old version of the app, before installing the new version. In that case, you completely uninstall the app and therefore _all app data is erased_, before the new app is installed. It might be that you're running into something like that.

**Comment by Ghostbird** [comment]
> Everything is being removed from the app data folder on a deployment.

Yeah, that sounds as if something is configured to uninstall your app before installing the new build. Also in our case the _.NET Meteor_ extension _is_ our deployment and debugging extension. And it has an option to perform this behaviour. So you might want to check _your_ debug configuration for such an option.

**Comment by QianaJiao** [comment]
I use the below repo to verify that in Visual Studio 17.10.0 Preview 5, in MAUI 8.0.7/8.0.10/8.0.20 versions, I'm unable to repro this issue. 
https://github.com/dotnet/maui-samples/tree/main/8.0/Data/TodoSQLite.

If you are still bothered by this issue, please provide a repro repo. I would like to reverify it.
