### ISSUE TITLE
Scale transform seems relative instead of absolute?

### ISSUE THREAD

**Issue by roubachof** [dotnet/maui#21457]
### Description

I thought that setting the Scale property on a IView would be an absolute value.
Let's say I want to double the size of my view then reset it to it's original value, I would do:

```csharp
myView.Scale = 2.0;
```

then

```csharp
myView.Scale = 1.0;
```

But looking at the source:

```csharp
public static void UpdateScale(this AView platformView, IView view)
{
	platformView.UpdateScaleX(view);
	platformView.UpdateScaleY(view);
}

public static void UpdateScaleX(this AView platformView, IView view)
{
	var scale = view.Scale;

	if (double.IsNaN(scale))
		return;

	platformView.ScaleX = (float)(scale * view.ScaleX);
}
```

```csharp
myView.Scale = 2.0; // platformView.ScaleX is 2.0;
```

then

```csharp
myView.Scale = 1.0; // platformView.ScaleX  is still 2.0;
```

So, to have the desired effect I should do:

```csharp
myView.Scale = 2.0; // platformView.ScaleX is 2.0;
```

then

```csharp
myView.Scale = 0.5; // platformView.ScaleX  is now back at 1.0;
```

But scale should be relative to the real size of the widget, no?
Is it me or is this weird?
Am I missing something? I'm pretty sure it's one of those times I will go "oooooh what a fool I've been" when you will answer that :)

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by RoiChen001** [comment]
Can't repro this issue at Android platform on the latest 17.10 preview 2(8.0.14).
[MauiApp4.zip](https://github.com/dotnet/maui/files/14786933/MauiApp4.zip)
