### ISSUE TITLE
Maui not working on iPhone 15

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#21473]
### Description

Since the latest Maui update I have been unable to run my app on iPhone 15. I have tried with VS and VS Code and both bomb out in the same way.

There is no useful information - I just get a memory dump like below. It happens as soon as the app loads.

Works ok on iPhone 14 and below.

I had a bunch of other problems as well so it's taken me this long just to get to this point. I have given up entirely on VS for Mac - it just doesn't work.

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x12512414a):
0x12512413a  
ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x12512414a  73 08 48 89 c7 e9 cc 99 ff ff c3 90 90 90 b8 53  s.H............S
0x12512415a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 b4 99  ...I....s.H.....
0x12512416a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...
........I....
Stopping iOS process...
iOS Process was stopped.

### Steps to Reproduce

Run code on Mac to an iPhone 15 simulator (iOS 17.4)

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

iOS

### Affected platform versions

iOS 17.4

### Did you find any workaround?

No

### Relevant log output

```shell
=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x12512414a):
0x12512413a  
ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x12512414a  73 08 48 89 c7 e9 cc 99 ff ff c3 90 90 90 b8 53  s.H............S
0x12512415a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 b4 99  ...I....s.H.....
0x12512416a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...
........I....
Stopping iOS process...
iOS Process was stopped.
```

**Comment by drasticactions** [comment]
Are you using Xcode 15.3? If so, that's not [supported yet](https://github.com/dotnet/maui/issues/21057).

Also, can you try deploying an iOS app (`dotnet new ios`) without the MAUI UI stack and seeing if that works? My guess is that it won't.

CC @rolfbjarne

**Comment by williambuchanan2** [comment]
Ah ok, that could explain it. It had been working with my iPhone 14 sim so I assumed it was supported.

the dotnet new ios command did seem to work:
The template "iOS Application" was created successfully.

**Comment by drasticactions** [comment]
I meant for deployment. If you deployed a .NET iOS app (one created with `dotnet new ios`) and it worked, where one that implements the MAUI UI stack didn't, then that could point to an issue contained within this repo. But if it didn't work (which it shouldn't) then it would be one that would go either into the SDK repo, the runtime, or somewhere else within .NET.
