### ISSUE TITLE
Where is the RelativeLayout?

### ISSUE THREAD

**Issue by yiszza** [dotnet/maui#2147]
![image](https://user-images.githubusercontent.com/42995476/129859500-33e66944-28de-4095-9683-2b10fe0ca128.png)

**Comment by michaelstonis** [comment]
`AbsoluteLayout` and `RelativeLayout` have been moved to the compatibility namespace. There is almost always a better way to resolve your problem using the `Grid` layout FWIW.

More info here: https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-7/

**Comment by yiszza** [comment]
> `AbsoluteLayout` and `RelativeLayout` have been moved to the compatibility namespace. There is almost always a better way to resolve your problem using the `Grid` layout FWIW.
> 
> More info here: https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-7/

thanks!
