### ISSUE TITLE
Duplicate symbol build error

### ISSUE THREAD

**Issue by AlphaNERD-** [dotnet/maui#21483]
### Description

Hello .NET MAUI devs,

i am in the process of migrating an app from Xamarin.Android and Xamarin.iOS to .NET MAUI. And i've ran into a linker issue with 2 SDKs made by Fujitsu for two thermal printer models. Basically when i try to build 2 binding projects wrapping their respective SDKs, i get the following build error:

```
clang++ exited with code 1: [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
duplicate symbol '_FCLReceivedNotification' in: [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
    /Users/juliawolf/SampleProject/obj/Debug/net8.0-ios/ios-arm64/linker-cache/libFTP2176000N0_IOS.a(FTPIOSLibraryClass.o) [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
    /Users/juliawolf/SampleProject/obj/Debug/net8.0-ios/ios-arm64/linker-cache/libFTP2076210N0_IOS.a(FTPIOSLibraryClass.o) [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
duplicate symbol '_FCLReceivedNotificationForMultiplePrinters' in: [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
    /Users/juliawolf/SampleProject/obj/Debug/net8.0-ios/ios-arm64/linker-cache/libFTP2176000N0_IOS.a(FTPIOSLibraryClass.o) [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
    /Users/juliawolf/SampleProject/obj/Debug/net8.0-ios/ios-arm64/linker-cache/libFTP2076210N0_IOS.a(FTPIOSLibraryClass.o) [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
duplicate symbol '_EADSessionDataReceivedNotification' in: [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
    /Users/juliawolf/SampleProject/obj/Debug/net8.0-ios/ios-arm64/linker-cache/libFTP2176000N0_IOS.a(EADSessionController.o) [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
    /Users/juliawolf/SampleProject/obj/Debug/net8.0-ios/ios-arm64/linker-cache/libFTP2076210N0_IOS.a(EADSessionController.o) [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
ld: 3 duplicate symbols for architecture arm64 [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
clang: error: linker command failed with exit code 1 (use -v  [/Users/juliawolf/SampleProject/SampleProject.csproj::TargetFramework=net8.0-ios]
```

I tried to work around this issue by building the binding projects separately and including the resulting DLLs as simple references, however i get the same build error. I can't use only one of the SDKs either unless i want to drop support for one of these thermal printer models. I could get around the build error by binding one of the SDKs using `ObjCBindingNativeLibrary` instead of `NativeReference`, however that SDK was unusable during runtime (See issue https://github.com/dotnet/maui/issues/21352 for more information).

These 2 binding projects used to work together with Xamarin.iOS.

### Steps to Reproduce

Simply build project for a physical iOS device (These libraries do not work on iOS Simulator)

Expected result:
Successful build

Actual result:
See build error posted above

### Link to public reproduction project repository

https://github.com/AlphaNERD-/BuildIssueDemo

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.iOS

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by PureWeen** [comment]
@rolfbjarne thoughts?

**Comment by SKeehnen** [comment]
I'm stuck with the same problem with another NativeReference, which works fine with Xamarin but results in 99 duplicate symbols when using it in Maui.

**Comment by rolfbjarne** [comment]
@AlphaNERD- looks like the test project doesn't compile because the repository doesn't contain all the required projects:

>  error MSB3202: The project file "/Users/rolf/test/bugs/BuildIssueDemo/Binding projects/iOS.ImenseANPR/iOS.ImenseANPR.csproj" was not found.

**Comment by AlphaNERD-** [comment]
I removed the project reference to the missing binding project. Could you give the build another shot?

**Comment by rolfbjarne** [comment]
Now it fails with:

> CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [/Users/rolf/test/bugs/BuildIssueDemo/SampleProject.csproj::TargetFramework=net8.0-ios]

**Comment by AlphaNERD-** [comment]
Okay, the platform-specific stuff was somehow missing. I've added it back in and made sure that this issue can be reproduced with the repo.

Can you try again?

**Comment by rolfbjarne** [comment]
OK, I can reproduce the error.

I noticed that each binding library is binding a native library, and they're slightly differently named:

```
$ ls -la Binding\ projects/iOS.Fujitsu*/Native\ Library/*.a
-rw-r--r--  1 rolf  staff  864004 Apr  5 15:53 Binding projects/iOS.Fujitsu.Legacy/Native Library/libFTP2076210N0_IOS.a
-rw-r--r--  1 rolf  staff  140952 Apr  5 15:53 Binding projects/iOS.Fujitsu/Native Library/libFTP2176000N0_IOS.a
```

Are these native libraries supposed to be different? Or are they just different versions of the same library?

**Comment by AlphaNERD-** [comment]
Hello Rolf,

these libraries are for two different mobile thermal printers made by Fujitsu. The legacy version is designed to work with the older 628 series printers and the non-legacy version with the 62H series.

**Comment by rolfbjarne** [comment]
> Hello Rolf,
> 
> these libraries are for two different mobile thermal printers made by Fujitsu. The legacy version is designed to work with the older 628 series printers and the non-legacy version with the 62H series.

The problem is that both native libraries define some of the same symbols, which means that they can't be used at the same time.

This is a problem with the native libraries themselves, and can typically be reproduced in an Xcode project by disabling dead code stripping.

In a .NET binding project, it's sometimes possible to work around this problem by making sure dead code from the native libraries are stripped away by the native linker, which _sometimes_ works because the offending symbols end up removed.

Two changes are required to make this happen:

* Set `ForceLoad=false` here:
	* https://github.com/AlphaNERD-/BuildIssueDemo/blob/a3856e171f16e96424e4394d0ef2b31caa729cfe/Binding%20projects/iOS.Fujitsu.Legacy/iOS.Fujitsu.Legacy.csproj#L20
	* https://github.com/AlphaNERD-/BuildIssueDemo/blob/a3856e171f16e96424e4394d0ef2b31caa729cfe/Binding%20projects/iOS.Fujitsu/iOS.Fujitsu.csproj#L20

`ForceLoad=True` means to include everything from the native library in the final executable - the opposite of what we need, so set `ForceLoad=False` instead.

* Set `SmartLink=True` here:
	* https://github.com/AlphaNERD-/BuildIssueDemo/blob/a3856e171f16e96424e4394d0ef2b31caa729cfe/Binding%20projects/iOS.Fujitsu.Legacy/iOS.Fujitsu.Legacy.csproj#L19
	* https://github.com/AlphaNERD-/BuildIssueDemo/blob/a3856e171f16e96424e4394d0ef2b31caa729cfe/Binding%20projects/iOS.Fujitsu/iOS.Fujitsu.csproj#L19

If there are *no* binding projects (or NuGets bundling native libraries) that sets `SmartLink=false`, then we'll ask the native linker to remove dead code from native libraries (by passing `-dead_strip` to the native linker).

With these changes the test solution compiles for me.

Here's the diff:

```diff
diff --git a/Binding projects/iOS.Fujitsu.Legacy/iOS.Fujitsu.Legacy.csproj b/Binding projects/iOS.Fujitsu.Legacy/iOS.Fujitsu.Legacy.csproj
index b2f4b1d..601fc54 100644
--- a/Binding projects/iOS.Fujitsu.Legacy/iOS.Fujitsu.Legacy.csproj
+++ b/Binding projects/iOS.Fujitsu.Legacy/iOS.Fujitsu.Legacy.csproj
@@ -16,8 +16,8 @@
       <Kind>Static</Kind>
       <Frameworks>ExternalAccessory</Frameworks>
       <LinkerFlags></LinkerFlags>
-      <SmartLink>False</SmartLink>
-      <ForceLoad>True</ForceLoad>
+      <SmartLink>True</SmartLink>
+      <ForceLoad>False</ForceLoad>
     </NativeReference>
     <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
     <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
diff --git a/Binding projects/iOS.Fujitsu/iOS.Fujitsu.csproj b/Binding projects/iOS.Fujitsu/iOS.Fujitsu.csproj
index 5577a2b..2d1542b 100644
--- a/Binding projects/iOS.Fujitsu/iOS.Fujitsu.csproj
+++ b/Binding projects/iOS.Fujitsu/iOS.Fujitsu.csproj
@@ -16,8 +16,8 @@
       <Kind>Static</Kind>
       <Frameworks>ExternalAccessory</Frameworks>
       <LinkerFlags></LinkerFlags>
-      <SmartLink>False</SmartLink>
-      <ForceLoad>True</ForceLoad>
+      <SmartLink>True</SmartLink>
+      <ForceLoad>False</ForceLoad>
     </NativeReference>
     <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
     <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
```
