### ISSUE TITLE
DataTemplate bindings do not work

### ISSUE THREAD

**Issue by AlphaNERD-** [dotnet/maui#21481]
### Description

Helllo again .NET MAUI dev team,

i have discovered another issue with bindings in .NET MAUI: When trying to bind to a property within a DataTemplate, i do not get the value of the property i bound to. Instead i get the ToString() output of the object whose property i wanted to make a binding to.

I've created a WPF version of this demo project to ensure that i created the bindings correctly: https://github.com/AlphaNERD-/WPFBindingDemo/

### Steps to Reproduce

1. Build the project for Android (See issue https://github.com/dotnet/maui/issues/21431 for the reason why)
2. Enter something within the entry. Ideally one of the first or last names listed within the constructor of ViewModelTest

Expected result:
You should see a list of names appear under the entry.

Actual result:
You see a list of "BindingDemoForGithub.ViewModelTest+TestUser" appear under the entry.

### Link to public reproduction project repository

https://github.com/AlphaNERD-/NETMAUIBindingDemo

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 14

### Did you find any workaround?

One way we could get around this is to use ToString(). This will help users working with VERY simple lists.

**Comment by mattleibow** [comment]
I think this is because `ListView` actually needs to use a `ViewCell`:

```xaml
<ListView ItemsSource="{Binding TestUsers, Mode=TwoWay}">
    <ListView.ItemTemplate>
        <DataTemplate>
            <ViewCell>
                <Label Text="{Binding UserName}"/>
            </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```

Maybe this is a result of the sample app... But, another thing I notice is that you have a list view in a vertical stack and that is in a scroll view. Doing this will cause the entire list to load all views - which will disable virtualization. You probably need to use a Grid and do not put a virtualized control (listview/collection view) in a infinite control - stack layout and scroll view. Nested scrolling controls in the same direction effectively loads all views at startup.

**Comment by AlphaNERD-** [comment]
Adding the `<ViewCell>` tags fixed the binding issue. I do wonder though: Why do i need to use the `<ViewCell>` tags in the first place?

**Comment by jfversluis** [comment]
@AlphaNERD- that is the way it was setup for a ListView, all cells have to inherit from `ViewCell` also see the [docs](https://learn.microsoft.com/dotnet/maui/user-interface/controls/listview?view=net-maui-8.0#view-cell), this was changed for `CollectionView`.

Glad you got this to work!
