### ISSUE TITLE
Bugzilla44166 now failing after ThemeResourcesChange fix

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#21495]
### Description

- open Microsoft.Maui.LegacyControlGallery.slnf
- run android gallery
- navigate to 44166
- click go
- click previous
- click GC

"Success" never shows up

rollback this PR
https://github.com/dotnet/maui/pull/21229

repeat steps
Success shows up

**Comment by baaaaif** [comment]
The PR referenced here is probably also the cause of a crash in the Telerik MAUI controls when testing nightly

https://feedback.telerik.com/maui/1646520-pickerpopupsettings-styling-crashing-in-maui-nightly-upcoming-sr4

i'll test it when this issue in closed and part of a nightly. Maybe it's also affecting the telerik crash
