### ISSUE TITLE
Status of window-level menus and toolbars (for desktop apps)

### ISSUE THREAD

**Issue by profix898** [dotnet/maui#2151]
The MAUI roadmap in July/August 2021 mentioned **Desktop Menu Items** for Preview 6 (see https://github.com/dotnet/maui/wiki/Roadmap/b23f3c1b329b6fd258b97f5ce3cbbde81f568b23). However, I can't find any reference to those in the release notes or blog posts. Are these implemented yet?

I'm trying to create an app with window-level menu and toolbar (for desktop projects) using Maui preview 7, but I can't find either of those. Can anyone please point me in the right direction?

**Comment by profix898** [comment]
Ok, I found that work on desktop menus was moved/delayed to MAUI preview 8.
I include the relevant issues here for reference:

Validate MenuItem API: #1715
Implementation for MacOS: #1716
Implementation for Windows: #1717

**Comment by davidbuckleyni** [comment]
We also must remember ribbon bars and status bars as well here and multi level menus been laking for years in shell.

**Comment by davidbuckleyni** [comment]
@Redth why was this closed is menus in desktop apps not important to team shell wont cut it for business drivin apps.
