### ISSUE TITLE
[Bug] BackgroundColor doesn't update when applied to Page

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2152]
### Description

If you try to change the background color on a page after the page has rendered, nothing will happen. The change will be set for the BackgroundPage value, but it will look exactly the same.

### Steps to Reproduce

Run this sample application and click on the button on top to change the background.
[MauiDynamicPageBackground.zip](https://github.com/dotnet/maui/files/7009017/MauiDynamicPageBackground.zip)

When looking at the output, you should see the old page value and the new one,

```
[0:] OldBackgroundColor: [Color: Red=0.31764707, Green=0.16862746, Blue=0.8745098, Alpha=1]
[0:] NewBackgroundColor: [Color: Red=1, Green=1, Blue=1, Alpha=1]
```

But nothing will change in the running app.

### Expected Behavior

The background color would change.

### Actual Behavior

Nothing happens.

**Comment by PaulAnderson02** [comment]
BackGroundColor not applied dynamically for Stacklayout, Gridlayouts
