### ISSUE TITLE
[Bug] Updating Image Properties through Code-Behind does not reflect in UI.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2153]
### Description

https://user-images.githubusercontent.com/898335/129951350-88fc38a2-f8d1-443e-8e37-ef38d71e6995.mp4

When changing image properties dynamically, the resulting changes don't apply on-screen even though they are in the image properties. If you look at the XAML Hot Reload changes I'm making and compare them to the Live Property Explorer, you can see that the changes I'm making are being properly added to the image object, but most of the time the image doesn't re-render unless it's touching the Aspect or Image width and height.

You can also use the code-behind buttons in the sample to show the same behavior.

### Steps to Reproduce

[MauiImageTester.zip](https://github.com/dotnet/maui/files/7009314/MauiImageTester.zip)

Run this UI Sample. You can either use XAML Hot Reload or the buttons which poke the image values directly.

### Expected Behavior

Updating Image Properties via code-behind would result in the UI being updated.

### Actual Behavior

Nothing happens.

**Comment by hartez** [comment]
This is fixed in preview 10.
