### ISSUE TITLE
ScrollView.ScrollToAsync on iOS scrolls also vertically when Orientation is horizontal but content view is smaller vertically than ScrollView

### ISSUE THREAD

**Issue by VNGames** [dotnet/maui#21537]
### Description

When there is a ScrollView which has a view inside, that is vertically smaller than scrollview itself and
`scrollView.ScrollToAsync(x, 0, true)` is called, it will scroll by X and also it will scroll by Y the distance `insideView.Height - scroillView.Height` which is a negative number.

The problem is here
https://github.com/dotnet/maui/blob/d7dac41200a932ea748569a28b6f26e7e3df69db/src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs#L108

Despite being horizontal only it calculates this value and uses it to scroll vertically
`var availableScrollHeight = uiScrollView.ContentSize.Height - uiScrollView.Frame.Height;`
(on the scrollView OffsetY is 0 and I pass 0 into ScrollToAsync - it shouldn't scroll vertically in such case)

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

The workaround I used is overriding this Command, copy pasting original code and fixing it, PendingScrollToRequest is set using reflection. And only by setting the backing fields, no way to access it other way. If this Property wasn't an auto property it wouldn't be possible.
This is a rough quick workaround. Please don't take this as an example for a fix. I didn't think this through much.
```
            ScrollViewHandler.CommandMapper.ModifyMapping(nameof(IScrollView.RequestScrollTo), (handler, scrollView, args, action) =>
            {
                if (args is ScrollToRequest request)
                {
                    var uiScrollView = handler.PlatformView;

                    if (uiScrollView.ContentSize == CGSize.Empty && handler is ScrollViewHandler scrollViewHandler)
                    {
                        // If the ContentSize of the UIScrollView has not yet been defined,
                        // we create a pending scroll request that we will launch after performing the Layout and sizing process.

                        // Setting the property via reflection
                        var backingField = typeof(ScrollViewHandler).GetField($"<PendingScrollToRequest>k__BackingField", BindingFlags.Instance | BindingFlags.NonPublic);
                        backingField.SetValue(scrollViewHandler, request);
                        return;
                    }

                    var availableScrollHeight = uiScrollView.ContentSize.Height - uiScrollView.Frame.Height;
                    var availableScrollWidth = uiScrollView.ContentSize.Width - uiScrollView.Frame.Width;
                    var minScrollHorizontal = Math.Min(request.HorizontalOffset, availableScrollWidth);
                    var minScrollVertical = Math.Min(request.VerticalOffset, availableScrollHeight);

                    if (scrollView.Orientation == ScrollOrientation.Horizontal)
                    {
                        uiScrollView.SetContentOffset(new CGPoint(minScrollHorizontal, 0), !request.Instant);
                    } 
                    else if (scrollView.Orientation == ScrollOrientation.Vertical)
                    {
                        uiScrollView.SetContentOffset(new CGPoint(0, minScrollVertical), !request.Instant);
                    }
                    else
                    {
                        uiScrollView.SetContentOffset(new CGPoint(minScrollHorizontal, minScrollVertical), !request.Instant);
                    }

                    if (request.Instant)
                    {
                        scrollView.ScrollFinished();
                    }
                }
            });
```

**Comment by RoiChen001** [comment]
Can't repro this issue on iOS platform on the latest 17.10.0 preview 2(8.0.3 & 8.0.7 & 8.0.14.)
[MauiApp8.zip](https://github.com/dotnet/maui/files/14850132/MauiApp8.zip)
