### ISSUE TITLE
The app is crashing after sent to background IOS only

### ISSUE THREAD

**Issue by alaa3latol** [dotnet/maui#21533]
### Description

I have a problem with IOS only when the app sent to background, it crashes and restarted. 
I searched and tried to handle DidEnterBackground but nothing worked for me.

I have sent in the attachments AppDelegate file
[AppDelegate.txt](https://github.com/dotnet/maui/files/14815363/AppDelegate.txt)

### Steps to Reproduce

I handled the DidEnterBackground function in AppDelegate but nothing worked

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Thanks for the report here. I'm very sorry but without any relevant code or logs or anything it will be impossible to determine if this is a potential bug in .NET MAUI or something in your codebase.

**Comment by alaa3latol** [comment]
I have updated the post and attached the appdelegate code file , I really don't know from where I begin.
[AppDelegate.txt](https://github.com/dotnet/maui/files/14815364/AppDelegate.txt)

**Comment by alaa3latol** [comment]
Dear Gerald,
I really don't know which code should I share! , I attached the AppDelegate
file. if there any code files you want me to share please let me know.

best regards
Alaa Atef

**Comment by neelpanchal52** [comment]
Hi,
I have the same issue. When the app is in the background it crashes and restarts and does not get any exceptions or logs.

**Comment by CoeqWEty** [comment]
Hi we have the same issue.  It constantly occurs.  It seems relatively new. We've been trying to convert from xamarin 5  thru several net mauireleases. 

This is likely a net Maui 8 issue.  

This needs a an urgent high priority fix.  Crashing in  background makes it undeployable  or and at minimum a very pooR Zux

**Comment by Pastajello** [comment]
I'd suggest removing api keys from the file at least. If needed consider sending the details to jsuarez/others privately.

**Comment by Yannikk1996** [comment]
any news?

**Comment by umike72** [comment]
Seeing the same issue here. The problem started occurring once I've implemented the OnActivated method in AppDelegate. Even if there is no code in it, I get the exception below when sending the app to background by clicking on the iOS emulator home button.

I can reproduce it as follows (MAUI .net8, VS 17.9.6)

```
        [Foundation.Export("applicationDidBecomeActive:")]
        public override void OnActivated(UIKit.UIApplication application)
        {
            ;
        }
```
The stacktrace looks like this:
```
0xD in RealLoadMobileAppMaui.Program.Main at D:\src\rlmc\xxxxx\Platforms\iOS\Program.cs:13,13
	at D:\src\rlmc\xxxxx\Platforms\iOS\Program.cs(13)

```
Program.cs wasn't modified from the auto-generated code. Commenting out the OnActivated() method makes the crash go away.

**Comment by umike72** [comment]
Update: Ignore my previous comment. If I add the line "base.OnActivated(application);"  to the OnActivated() method shown above, the app won't crash when sending to background.

**Comment by CoeqWEty** [comment]
@umike72 Hi- Did you do something to an app that goes to background  to not restart. Can you send code inline. We still experience the issue and tried multiple things. We get a crash reported by testflight but its just app restarts instead of staying open. 

Update: Ignore my previous comment. If I add the line "base.OnActivated(application);" to the OnActivated() method shown above, the app won't crash when sending to background.



> Update: Ignore my previous comment. If I add the line "base.OnActivated(application);" to the OnActivated() method shown above, the app won't crash when sending to background.
