### ISSUE TITLE
[BUG] Detecting iOS Code Signing Authority does not respect PropertyGroup conditions in Visual Studio 17.10.0 Preview 2.0 / .NET MAUI 9.0

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#21546]
### Description

I have the following code in my MAUI 9.0 project's file, through which I want to use a Distribution profile in Release configuration and Development profile in Debug configuration, similar to Xamarin:

```
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
		<ProvisioningType>manual</ProvisioningType>
		<CodesignKey >Apple Development: Janne Gustafsson (3JF32923Y3)</CodesignKey>
		<CodesignProvision>Apple Dev M Development 2023</CodesignProvision>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
		<ProvisioningType>manual</ProvisioningType>
		<CodesignKey>Apple Distribution: Hyvan mielen pelit ry (CUG8RS847T)</CodesignKey>
		<CodesignProvision>Apple Dev M Distribution March 2024</CodesignProvision>
	</PropertyGroup>
```

However, despite this, whenever I build the MAUI program in Visual Studio 17.10.0 Preview 2, the process always uses the Development certificate (probably the first occurrence in the file, regardless of the conditions). Detecting signing authority should respect the conditions properly.

Also, the property editor does not allow different profiles (or mostly anything else) for release and debug builds separately, which is a major shortcoming compared to Xamarin, along with the inability to choose built target frameworks in VisualStudio without modifying the project file (always builds all frameworks, slowing the development process a lot).

### Steps to Reproduce

1. Create an empty .NET 9.0 project with iOS target framework
2. Modify the project file to have configuration dependent provisioning profiles, as per the description
3. Build the project for both debug and release builds
4. The project is always built using development profile

### Version with bug

9.0.0-preview.1.9973

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.3.1

### Did you find any workaround?

I need to change the provisioning profile manually every time when changing configuration.

**Comment by jfversluis** [comment]
Does it work if you build it from the command-line? If this is specific to Visual Studio and the tooling you probably need to report it with them.

**Comment by janne-hmp** [comment]
> Does it work if you build it from the command-line? If this is specific to Visual Studio and the tooling you probably need to report it with them.

How do I see what provision profile the command line tool is using? I'm also not sure how I can use the command line tool to build the iOS app and deploy it on the iPhone. Normally I use Visual Studio for that, but happy to check how to use the command line tool, too, if I manage somehow to connect it with the Mac and use it to build the app there with the right provisioning profiles etc. The normal dotnet build just works fine of course, but I do not think it deals with provisioning and Mac connection.

**Comment by drasticactions** [comment]
@rolfbjarne @dalexsoto I'm unsure who works on the underlying tooling for provisioning profiles. Is this handled by the SDK or XVS?

Regardless, this most likely won't be specific to the MAUI UI project or tooling in this repo.

**Comment by janne-hmp** [comment]
When you find out who / what teams are relevant people to contact regarding this sort of .NET MAUI build process issues, let me know, too, and I'm happy to be in touch with them, too. This part of the build process in .NET MAUI seems to be extremely buggy, especially including deployment to an Android device, which (1) fails to generate app icons every now and then (see #21542 ) and (2) hangs up at least every other time (see #21536 ), among other difficulties, making the development experience very slow and frustrating. iOS seems to be a bit better, apart from this bug with provisioning profiles.

I might further note that Visual Studio itself is also weird in the sense that (a) you cannot choose which target frameworks you want to build (or choosing the framework does not do anything for building, VS always builds all frameworks, slowing down development) and (b) .NET MAUI project properties are not shown separately for Debug and Release in the Project Properties editor; rather they maybe listed one time only and sometimes with two entries for Debug and Release separately. Somebody should have a look and ensure that the editor reflects the project property file and its conditions accurately; and that the conditions in the project property file are in fact honored by the build process.

**Comment by janne-hmp** [comment]
Interesting. It does work like you suggested. Thanks a lot! I took the format from the property editor, which had created the following entries later in the project file:

```
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	  <MtouchLink>SdkOnly</MtouchLink>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
	  <MtouchLink>SdkOnly</MtouchLink>
	</PropertyGroup>

```

Should I also remove these AnyCPUs generated by the property editor?

**Comment by rolfbjarne** [comment]
> Interesting. It does work like you suggested. Thanks a lot! I took the format from the property editor, which had created the following entries later in the project file:
> 
> ```
> 	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
> 	  <MtouchLink>SdkOnly</MtouchLink>
> 	</PropertyGroup>
> 	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
> 	  <MtouchLink>SdkOnly</MtouchLink>
> 	</PropertyGroup>
> ```
> 
> Should I also remove these AnyCPUs generated by the property editor?

I would do that; unnecessary code just ends up being confusing sooner or later.

Since the property value is the same for both conditions, you can simplify even more:

```xml
<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
    <MtouchLink>SdkOnly</MtouchLink>
</PropertyGroup>
```

**Comment by jfversluis** [comment]
Seems like this is resolved, thanks everyone!
