### ISSUE TITLE
Layout cycle crash on Windows with Button with image inside FlexLayout 

### ISSUE THREAD

**Issue by jeremy-visionaid** [dotnet/maui#21548]
### Description

The following will cause a crash when the FlexLayout is too narrow to fit the buttons on a single row

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiTestApp.MainPage">

    <Grid RowDefinitions="Auto,*">

        <FlexLayout Grid.Row="0" x:Name="Toolbar" Wrap="Wrap" HorizontalOptions="StartAndExpand" JustifyContent="SpaceBetween" MaximumWidthRequest="720">
            <Button ImageSource="dotnet_bot.png" />

            <Button />
        </FlexLayout>

    </Grid>

</ContentPage>
```

The crash manifests differently depending on whether the Window size is too small to start with, or whether it is later resized to be too small.

### Link to public reproduction project repository

https://github.com/molesmoke/MauiTestApp/tree/flexlayout-cycle

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

Windows

**Comment by jaosnz-rep** [comment]
Can repro this issue at Windows platform on the latest 17.10 preview 2 (8.0.14)

**Comment by jeremy-visionaid** [comment]
I started a bisect between release/8.0.1xx-sr2 and release/8.0.1xx-sr3 earlier, but it takes quite a while per build with my slow Internet. I'll update here probably tomorrow unless someone figures out which change broke it before me.

**Comment by jeremy-visionaid** [comment]
FWIW, this also manifests similarly to #18780, but this one is a regression

**Comment by jeremy-visionaid** [comment]
Well, I tried to carry on with the bisect today, but I found that it's pretty hard since for local builds on the expected "good" revision (release/8.0.1xx-sr2), launching an app like a device test or Maui.Controls.Sample on Windows throws:

System.InvalidOperationException: 'Cannot resolve scoped service 'Microsoft.Maui.Dispatching.IDispatcher' from root provider.'

I was able to bisect that problem to #19932, but it persists on main too, so it's difficult to find any build I can actually run tests against without it crashing due to dispatcher problems. @mattleibow Any ideas about how to work around that?

**Comment by jeremy-visionaid** [comment]
So, by cherry-picking the suspicious commits at a point just before #19932, I can show that the regression here was caused by #20949. @Foda I'm hoping you'll know what to do to fix that! I can't really change my app to avoid it, so I'm stuck on 8.0.7 for now.

**Comment by jeremy-visionaid** [comment]
@Foda I put a branch here that's runnable and shows the problem directly in Maui.Controls.Sample:
https://github.com/molesmoke/maui/tree/flex-repro

I'll try and turn it into a bona fide device test if I can find the time later, but I've got other fish to fry right now.

**Comment by jeremy-visionaid** [comment]
Guessing that the dispatcher crash relates to #21081 so maybe will start working with the next VS release...

**Comment by Foda** [comment]
Looking that this now, thanks for the repro!

**Comment by jeremy-visionaid** [comment]
@Foda I don't know why the layout cycle test doesn't crash on the first run in the unit test. It does in a real app. Makes me wonder if the other layout cycle tests are working, but I haven't checked yet.

**Comment by jeremy-visionaid** [comment]
@Foda Oh, the other crazy thing is that if I try to create the handlers like so:

```
foreach (var button in flexLayout.Children.OfType<Button>())
    await CreateHandlerAsync<ButtonHandler>(button);
```

then I find it hangs instead of crashes, hence a dedicated list 🤷

**Comment by Foda** [comment]
Hmmm, @jeremy-visionaid, I'm unable to reproduce this locally. I wonder if my recent change to buttons fixed it? Can you pull the main branch and try again?

**Comment by jeremy-visionaid** [comment]
@Foda Looks like it's not only already fixed on master, but it's fixed in 8.0.20 too 👍Maybe the unit test might still be useful for regressions if someone didn't already add something to the same end?

**Comment by jeremy-visionaid** [comment]
I'm guessing this was fixed by #21516

**Comment by jeremy-visionaid** [comment]
@Foda I spoke too soon, I just tried updating my actual application to 8.0.20 and it turns out that this is still an issue. It still manifests when the application window is too small to start with (but resize now seems to be OK). So, if I rebase #21651 on top of release/8.0.1xx-sr4 (and remove the Skip directive for Windows) then the unit test still fails.

**Comment by jeremy-visionaid** [comment]
@Foda I find the unit test fails on main too. Much easier to test now 17.10.0 Preview 3 is out!

**Comment by jeremy-visionaid** [comment]
@Foda Bump! Please reopen.
