### ISSUE TITLE
CollectionView seems to be really struggling on Android, especially when you scroll through the items quickly.

### ISSUE THREAD

**Issue by mjsb212** [dotnet/maui#21554]
The problem: CollectionView seems to be really struggling on Android, especially when you scroll through the items quickly. 
Look at the example below. The item template is pretty simple and a **very** typical setup.
```xaml
<DataTemplate x:DataType="x:Int32">
    <SwipeView>
        <SwipeView.RightItems>
            <SwipeItems>
                <SwipeItem Text="Action3" BackgroundColor="Pink"/>
            </SwipeItems>
        </SwipeView.RightItems>
        <SwipeView.LeftItems>
            <SwipeItems>
                <SwipeItem BackgroundColor="Yellow" Text="Action1"/>
                <SwipeItem BackgroundColor="PaleVioletRed" Text="Action2"/>
            </SwipeItems>
        </SwipeView.LeftItems>
        <Grid ColumnDefinitions="*,*,*"
                BackgroundColor="White"
                ColumnSpacing="10"
                RowDefinitions="40"
                Padding="0,5">
            <Label VerticalTextAlignment="Center" Grid.Column="0" BackgroundColor="Red" Text="{Binding}"/>
            <Path Grid.Column="0" TranslationX="50" Data="M 0,10 L 10,10 L 5,0Z" Fill="White" VerticalOptions="Center"/>
            <Button Grid.Column="1" BackgroundColor="green" Text="{Binding}" Padding="0"/>
            <Entry Grid.Column="2" BackgroundColor="blue" TextColor="white" Text="{Binding}"/>
        </Grid>
    </SwipeView>
</DataTemplate>
```
It's just a grid with 3 columns, with a `Label`, a `Button`, a `Path`, and an `Entry`. All of these are enclosed in a `SwipeView`. But even with this simple layout, we hit a performance bottleneck pretty quickly. Which is really bad because the real world apps that I had worked on require way more complex layouts than that.

Here is what scrolling through such a collection view looks like on a Xiaomi Note 8T (android 10). It's not a new phone by any means, but it's modern-enough to not have hiccoughs with such simple tasks. I use it daily and it's been working well enough for years that I haven't even considered replacing it yet.

https://github.com/dotnet/maui/assets/28758721/cdd65de3-08b6-4a9f-93e4-28e071f7dc62

Try the fling gesture to scroll through the items and you pretty much get a slideshow. Even trying to go through the list without lifting your finger gives you some small stutters. 

What I'm trying to figure out is what is at fault here and how can we as developers work around it or what can the .NET MAUI team do about it and the timeline of it.

I recorded a trace of what was happening during scrolling. I'm not an expert in analyzing this kind of stuff but it obviously doesn't look good.
![image](https://github.com/dotnet/maui/assets/28758721/6e7757fc-1e2d-4502-8662-3f00cd449014)

If I'm not mistaken there's nothing that I do outrageously wrong in my layout nor are the binding slowing everything down (there's a total of 3 bindings in the example without any converters or anything). 

In this example, the `OnBindViewHolder` calls take a relatively small amount of time but it scales very aggressively with the amount of bindings and complexity of the layout. With a layout with 3 rows, 3 columns, 8-10 labels, 1 image, and 4 paths it took 250ms. This means if you scroll by `4 items` at once you'll get a `1s` lag.

I obviously understand that with using MAUI comes a performance hit but as developers we can't be expected hit such an issue soooo early. I mean, if you use something hard enough you'll eventually break it but this is nowhere near a *heavy* or *unusual* use case.

Here is the project and scope file: https://github.com/Hooterr/AndroidCollectionViewPerformance

# Potential solution: GO NATIVE
After digging for hours through recorded scopes and trying to optimize the layout of item templates I found out that the only solution was to write the layout natively. I translated the real-world-complex from XAML to android XML. I setup the RecyclerView to use my layout and bind my collection of items through the adapter. I even used all the value converters that I used in XAML to set texts and colors inside `OnBindViewHolder` as well as the same `IFontManager` as MAUI to load fonts. Then made a barebones handler to render my native recycler view inside my XAML page. The effect was absolutely **astonishing**. There was nothing I could do to make that list lag or stutter in any way. Even in Debug mode, when the MAUI CollectionView was almost unusable, the native one was just flying. 

It seems that .NET<->Java interop is not to blame here. You wouldn't be able to tell if this sample list was written directly in Java or Xamarin.Android. What it looks like to me is that the underlaying architecture of MAUI just does so much work underneath that it's just unfeasible to make anything more complex than a list of simple labels. 

At this point, what I would recommend to everyone is, if you're having performance issues with CollectionView, just write your layouts natively. It's a shame because you have to do it twice but there seems to be no other choice.

_Originally posted by @Hooterr in https://github.com/dotnet/maui/discussions/18027_

**Comment by 0XDE57** [comment]
> Would you mind to create some example repo of how to do some basic transition from MAUI listview layer to native equivalent on android ?

Yes please! Between the [crashing](#21565) and performance issues I am finding the CollectionView to be an unusable showstopper. We don't even have a complex UI in our case its a basic entry form, there is no reason for it to be this slow and unstable.

**Comment by jonmdev** [comment]
For cross reference, this was also just reported here with good repro projects proving this is a Maui issue:

https://github.com/dotnet/maui/issues/21580

I think it is a problem with how Maui is invalidating the native views on updates and/or garbage collecting. 

As I explain this poor performance can be reproduced even with very simple structures where you simulate a "CollectionView" by translating and occasionally updating simple constructs of AbsoluteLayout/Border/Label/Image. So I suspect it is more fundamental than the code of the CollectionView itself.

**Comment by Phantom-KNA** [comment]
> Yes I agree, ever since i updated to 8.0.6 the scrolling performance of the collection view for android is really bad. When upgrading to 8.0.10 and finally .8.0.14 its even slower. Now simple scroll views also lag. Its really bad and a grouped collection view crashes also sometimes. In 8.0.3 with VS 2022 17.8.6 its much smoother so there has been a huge regression in performance of the whole app basically from 8.0.3 to 8.0.14

The same thing happened to me, I migrated my project to net 8 from net 7 and it's really bad. I ask why you can't use the Sharpnado.Collectionview  It's pretty good, maybe because of copyright. But it really needs to work agilely. In projects with flutter and native kotlin it is wonderful.

**Comment by cwilde123** [comment]
> > Yes I agree, ever since i updated to 8.0.6 the scrolling performance of the collection view for android is really bad. When upgrading to 8.0.10 and finally .8.0.14 its even slower. Now simple scroll views also lag. Its really bad and a grouped collection view crashes also sometimes. In 8.0.3 with VS 2022 17.8.6 its much smoother so there has been a huge regression in performance of the whole app basically from 8.0.3 to 8.0.14
> 
> The same thing happened to me, I migrated my project to net 8 from net 7 and it's really bad. I ask why you can't use the Sharpnado.Collectionview It's pretty good, maybe because of copyright. But it really needs to work agilely. In projects with flutter and native kotlin it is wonderful.

Yeah its really bad optimization of the views it feels like, especially the collection view. There is a bug also in iOS where it shows duplicate headers when scrolling and of course lags a bit. I ended up implementing my own custom grouped ui collection view in ios platform folder and its so smooth and there is no stutter or lag or any bugs or anything so yeah this framework needs a lot of work in regards to performance and also bug fixing
