### ISSUE TITLE
[Bug] Dynamically changing FlexLayout Direction from code-behind does not re-layout UI

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2155]
### Description

If you try and dynamically update a FlexLayout's Direction (Ex. `Column` to `ColumnReverse`.), nothing happens. While the property is set, the UI does not re-render to reflect the change.

### Steps to Reproduce

Run this sample app and click on "Flip Column Rows". The output dialog will show the variable flip, but the UI will not update. If you set the direction in XAML to a different value and rebuild and redeploy, it does use that value, but you can't set it dynamically from code-behind.

[MauiTestApp.zip](https://github.com/dotnet/maui/files/7009681/MauiTestApp.zip)

### Expected Behavior

The layout will update with the new values.

### Actual Behavior

Nothing happens.

**Comment by hartez** [comment]
This is fixed in Preview 10.
