### ISSUE TITLE
BoxView Opacity does not work in Android.

### ISSUE THREAD

**Issue by RobDaytona** [dotnet/maui#21558]
### Description

Boxview Opacity does not work in Android - This only happens in Android - windows and iOS behave as expected.
I have uploaded a very simple example file consisting of MainPage View, 1 label and 1 boxview.
[MauiApp1.zip](https://github.com/dotnet/maui/files/14824712/MauiApp1.zip)

### Steps to Reproduce

Use the sample file uploaded.

Here is my dotnet workload list:

C:\Windows\System32>dotnet workload list

Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.202

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate, run 'dotnet dev-certs https --trust'
Learn about HTTPS: https://aka.ms/dotnet-https

----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
android                    34.0.52/8.0.100        VS 17.9.34723.18
maui-windows               8.0.7/8.0.100          VS 17.9.34723.18
maccatalyst                17.2.8004/8.0.100      VS 17.9.34723.18
ios                        17.2.8004/8.0.100      VS 17.9.34723.18

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

No workaround, have played with setting Color to Transparent as in this case its what I really needed a transparent clickable BoxView, but a Boxview with low opacity say 0.05 would also work. However when setting color to transparent the tap event was no longer fired either..

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 preview2 (8.0.14). Can repro on android platform with sample project.
 
Android:
![image](https://github.com/dotnet/maui/assets/77434865/6e969e75-b0d2-4d5d-93f7-aa727110fe22)
iOS:
![image](https://github.com/dotnet/maui/assets/77434865/84cd6088-3877-4181-ae04-4186d4c65d11)
Windows:
![image](https://github.com/dotnet/maui/assets/77434865/b13daa7a-b34b-44b1-be9f-2afa6cecf884)

**Comment by Zhanglirong-Winnie** [comment]
Sorry, this issue was closed by mistake and has been reopened.

**Comment by RobDaytona** [comment]
Thanks for verifying this! I appreciate this sample project is a really a simple little silly example, but for production code this technique is used to overlay custom images and label elements with transparent Boxviews to handle tap events, so its pretty vital to the game UI. Or just to overlay rows in scrollable tables made up of a number of elements per row/rectangle.

**Comment by RobDaytona** [comment]
Can this be looked at in the next sprint?

**Comment by RobDaytona** [comment]
Hello any ideas on timing on this?

**Comment by RobDaytona** [comment]
I have since used a Frame instead of a Boxview as the Transparency works on all 3 device types.

**Comment by matt-goldman** [comment]
Same as #18234 ?

**Comment by RobDaytona** [comment]
Similar to my ticket, yes, but I think in this example we are speaking of an Image Element? i may be wrong on this, @matt-goldman  what control in your ticket is having the opacity issues?

**Comment by matt-goldman** [comment]
My ticket is in relation to `BoxView` specifically, but it applies to pretty much all non-default values of properties not just opacity, and I think it affects several controls.

**Comment by mattleibow** [comment]
Duplicate of #18234
