### ISSUE TITLE
[MAUI][.NET8] System.InvalidOperationException will be thrown when clicking here to view full recipe.

### ISSUE THREAD

**Issue by RoiChen001** [dotnet/maui#21567]
### Description

System.InvalidOperationException will be thrown when clicking here to view full recipe.

Note:
This problem only occurs on iOS, other platforms are fine.

### Steps to Reproduce

1.Deploy https://github.com/rachelkang/recipeSearch to iOS.
2.Click Vegetarian-->Individual vegetarian Iasagnes.
3.Click here to view full recipe.
![image](https://github.com/dotnet/maui/assets/143168639/a116ee2b-4b66-4d11-8c01-0fcf2f8cd969)

Actual results:
System.InvalidOperationException will be thrown when clicking here to view full recipe.
![View detail](https://github.com/dotnet/maui/assets/143168639/81ddac7c-613e-40cc-8636-100c27b4fa8b)

Expected results:
No exception will be thrown.

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

Microsoft.Maui.Controls: 8.0.20-nightly.10419+sha.d7dac41200-azdo.9336308
.NET SDK: 8.0.203

### Is this a regression from previous behavior?

Not a regression, this issue also repro on 8.0.14+4-sha.6fb9077213-azdo.9266239.

### Affected platforms

iOS

**Comment by PureWeen** [comment]
Fixed by https://github.com/dotnet/maui/pull/21578

I tested this on the latest nightly and didn't reproduce the crash.
I was able to reproduce the crash on the versions noted in the issue
