### ISSUE TITLE
AppThemeBinding : System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'

### ISSUE THREAD

**Issue by AlleSchonWeg** [dotnet/maui#21575]
### Description

AppThemeBinding crashes with Line:
```XAML
  <Line Aspect="Uniform"
        X2="100"
        Stroke="{AppThemeBinding Light=Red, Dark=Green}" />
```
Nightly: 8.0.20-nightly.10423

### Steps to Reproduce

Insert sample xaml from above and change to or from dark theme via system settings.
Result:

>  	0xFFFFFFFFFFFFFFFF in Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception	C#	Annotated Frame
>  	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:13,5	C#	Annotated Frame
>  	0x1E in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:126,26	C#	Annotated Frame
>  	0xA in System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion	C#	Annotated Frame
>  	0x13 in System.Collections.Generic.List<System.Action<object,Microsoft.Maui.Controls.Internals.ResourcesChangedEventArgs>>.Enumerator.MoveNextRare	C#	Annotated Frame
>  	0x4B in System.Collections.Generic.List<System.Action<object,Microsoft.Maui.Controls.Internals.ResourcesChangedEventArgs>>.Enumerator.MoveNext	C#	Annotated Frame
>  	0x2F in Microsoft.Maui.Controls.Element.OnResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:648,64	C#	Annotated Frame
>  	0x2 in Microsoft.Maui.Controls.Element.OnParentResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:623,4	C#	Annotated Frame
>  	0x1B in Microsoft.Maui.Controls.VisualElement.OnParentResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:1446,5	C#	Annotated Frame
>  	0x16 in Microsoft.Maui.Controls.Element.OnParentResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:618,5	C#	Annotated Frame
>  	0x28 in Microsoft.Maui.Controls.Element.OnResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:649,6	C#	Annotated Frame
>  	0x2 in Microsoft.Maui.Controls.Element.OnParentResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:623,4	C#	Annotated Frame
>  	0x1B in Microsoft.Maui.Controls.VisualElement.OnParentResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:1446,5	C#	Annotated Frame
>  	0x16 in Microsoft.Maui.Controls.Element.OnParentResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:618,5	C#	Annotated Frame
>  	0x28 in Microsoft.Maui.Controls.Element.OnResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:649,6	C#	Annotated Frame
>  	0x2 in Microsoft.Maui.Controls.Element.OnParentResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:623,4	C#	Annotated Frame
>  	0x17 in Microsoft.Maui.Controls.Application.OnParentResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\Application\Application.cs:336,5	C#	Annotated Frame
>  	0x4B in Microsoft.Maui.Controls.Application.TriggerThemeChangedActual at D:\a\_work\1\s\src\Controls\src\Core\Application\Application.cs:255,5	C#	Annotated Frame
>  	0x12 in Microsoft.Maui.Controls.Application.set_PlatformAppTheme at D:\a\_work\1\s\src\Controls\src\Core\Application\Application.cs:190,5	C#	Annotated Frame
>  	0x6 in Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.ThemeChanged at D:\a\_work\1\s\src\Controls\src\Core\Application\Application.cs:503,4	C#	Annotated Frame
>  	0x21 in Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureWindow>b__3_0 at D:\a\_work\1\s\src\Core\src\Hosting\LifecycleEvents\AppHostBuilderExtensions.Android.cs:77,7	C#	Annotated Frame
>  	0xD in Microsoft.Maui.MauiAppCompatActivity. at D:\a\_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.Lifecycle.cs:47,114	C#	Annotated Frame
>  	0x1F in Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents<Microsoft.Maui.LifecycleEvents.AndroidLifecycle.OnConfigurationChanged> at D:\a\_work\1\s\src\Core\src\LifecycleEvents\LifecycleEventServiceExtensions.cs:31,5	C#	Annotated Frame
>  	0x40 in Microsoft.Maui.MauiAppCompatActivity.OnConfigurationChanged at D:\a\_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.Lifecycle.cs:47,4	C#	Annotated Frame
>  	0x11 in Android.App.Activity.n_OnConfigurationChanged_Landroid_content_res_Configuration_ at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Activity.cs:2926,4	C#	Annotated Frame
>  	0x9 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:125,5	C#	Annotated Frame
> 

I spend the whole day to find out why my app starts crashing. Please improve the exception message.
Perhaps this happens also with other elements. Not only with Line. I tested only with android.

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2 ( 8.0.14)Can not repro it, and code like below.
![image](https://github.com/dotnet/maui/assets/128687574/e28ee7c5-5688-47c8-8392-34535b48b847)

**Comment by AlleSchonWeg** [comment]
Fixed: https://github.com/dotnet/maui/issues/21503
