### ISSUE TITLE
Unable to turn off Fast Deployment for .Net8 Maui Android project

### ISSUE THREAD

**Issue by gceaser** [dotnet/maui#21572]
### Description

In the Android area of the Maui project properties, I am unable to turn off the Fast Deployment option for custom configurations. 

### Steps to Reproduce

1. Create a new .Net 8 Maui project in Visual Studio 2022.
2. Right click on the solution in the solution explorer and select Configuration Manager.
3. Under Active solution configuration drop down, select <New…>
4. Name the new configuration RELEASE_PROD and select to copy the settings from Release. Ensure the Create new project configuration check box is checked and click the OK button.
5. Close the configuration manager window.
6. Right mouse button click on your .net maui project in the solution explorer and select Properties from the popup menu.
7. In the left hand pane go down to Android and expand it and click on options.
8. Change the Android Package Format for RELEASE_PROD & net8.0-android to bundle.
9. Try to disable Fast Deployment for RELEASE_PROD & net8.0-android and the check mark cannot be removed.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All versions of .Net Maui Android projects

### Did you find any workaround?

No -  For custom configurations I have found no work around.

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2 (8.0.14), can repro it.
![image](https://github.com/dotnet/maui/assets/128687574/edace682-3617-4fd0-9946-fb330f5e5a69)

**Comment by michaelonz** [comment]
same issue here

**Comment by derekswatmaps** [comment]
the workaround seems to be to edit the .csproj and add the following under the PropertyGroup for the release build configuration
<EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-android#8929
