### ISSUE TITLE
random crash on startup dotnet maui app android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#21588]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/random-crash-on-startup-dotnet-maui-app-/10614973)._

---
I am getting the following stack trace on an unhandled exception.   This has been happening for awhile now and if I just run the app again it usually works fine with no other indications of a problem in debug mode.   I have been building release versions through azure pipelines and a month or so ago the app would run in release mode.   Now, the app crashes on startup.   

Do you have any suggestions for how to debug this problem?

I did see an older article about Zindex maybe causing something like this.  I removed Zindex from all my startup pages to get to the first page.   I still have some in subsequent pages.

Thanks
Brady

0xFFFFFFFFFFFFFFFF in Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:13,5	C#
 	0x23 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:368,26	C#
 	0x58 in System.Reflection.MethodBaseInvoker.InvokeWithNoArgs	C#
 	0xB4 in System.RuntimeType.CreateInstanceMono	C#
 	0x1F in System.RuntimeType.CreateInstanceDefaultCtor	C#
 	0x30 in System.Activator.CreateInstance	C#
 	0x3 in System.Activator.CreateInstance	C#
 	0x2 in System.Activator.CreateInstance	C#
 	0x48 in Microsoft.Maui.Controls.ShellContent. at D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellContent.cs:76,8	C#
 	0x27 in Microsoft.Maui.Controls.ElementTemplate.CreateContent at D:\a\_work\1\s\src\Controls\src\Core\ElementTemplate.cs:86,4	C#
 	0x8 in Microsoft.Maui.Controls.Internals.DataTemplateExtensions.CreateContent at D:\a\_work\1\s\src\Controls\src\Core\DataTemplateExtensions.cs:23,4	C#
 	0x77 in Microsoft.Maui.Controls.ShellContent.Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent at D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellContent.cs:81,5	C#
 	0x16E in Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnCreateView at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellSectionRenderer.cs:124,5	C#
 	0x24 in AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ at C:\a\_work\1\s\generated\androidx.fragment.fragment\obj\Release\net6.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:2031,4	C#
 	0xD in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:367,5	C#

---
#### Feedback Bot on 3/13/2024, 07:32 PM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 3/13/2024, 11:10 PM: 

(private comment, text removed)
#### brady on 3/14/2024, 02:03 PM: 

(private comment, text removed)
#### brady on 3/14/2024, 02:12 PM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 3/14/2024, 09:59 PM: 

(private comment, text removed)
#### brady on 3/15/2024, 00:54 PM: 

(private comment, text removed)
#### brady on 3/15/2024, 01:42 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
This exception usually happens from a failure to instantiate the XAML page associated with a given route. 

Maybe enable first chance exceptions to see if that breaks on the actual exception?
