### ISSUE TITLE
Maui LineGeometry not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#21589]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-LineGeometry-not-working/10612185)._

---
Maui LineGeometry not working 

  <Path Stroke="Black" StrokeThickness="3">
  <Path.Data>
    <LineGeometry StartPoint="40,0"
                  EndPoint="100,120" />
  </Path.Data>
</Path>

---
#### Feedback Bot on 3/10/2024, 06:53 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I'm very sorry but this issue lacks a lot of detail which makes it hard to diagnose what might be going on. If you're still experiencing this, please open a new issue on this repository and fill out all the requested information, ideally providing a reproduction project as well.

Thanks!
