### ISSUE TITLE
Net maui scrolling problem in version 17.10 preview 2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#21586]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-maui-scrolling-problem-in-version-17/10618956)._

---
[regression] [worked-in:17.10 preview 1]
Building my app in VS version 17.10 preview 1 scrolling is OK
Building my app in VS version 17.10 preview 2 scrolling is stack when the cursor caret.
in the editor field comes to the top of screen. Its like the caret prevent the scrolling
my app is maui net 8 for android Ver 34  .   my app is for android platform.

---
#### Feedback Bot on 3/19/2024, 01:34 AM: 

(private comment, text removed)
#### Haviv Elbsz on 3/31/2024, 01:08 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
According to the updated notes on the issue this isn't a regression
