### ISSUE TITLE
MAUI - Windows Machine - run error 실행시 오류

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#21591]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI---Windows-Machine---run-error-실행시-오/10605589)._

---
Before you can debug, you need to deploy your project. Enable Configuration Manager deployment.

DEP0700: Failed to register the app. [0x80080204] Error 0xC00CE169: App manifest validation error: App manifest must be valid on a per-schema basis. 
Line 10, Column 13, Reason: com.companyname.MauiApp_HJSoft' is '[-. A-Za-z0-9]+".
Parsing the 'Name' attribute with a value of 'com.companyname.MauiApp_HJSoft' failed.	MauiApp_HJSoft		

Today all of a sudden the build is still having problems..
I got the build done, but I can't run it this time.  Why do I keep having problems?

All of a sudden, the build keeps having problems today..
It's built, but it's not running this time.. Why does it keep causing problems..

---
#### Feedback Bot on 3/1/2024, 00:04 AM: 

(private comment, text removed)
#### 현조 민 on 3/1/2024, 01:18 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
The error message is a bit cryptic, but it tries to say that you should only use `A-Z`, `a-z`, `0-9` and `-` and `.` characters in your application ID. It looks like you have a `_` (underscore) in there which is not supported by all platforms. Remove that from your csproj and it should be all good!

You might have to delete your bin & obj folder to make sure the value is not cached somewhere.
