### ISSUE TITLE
App icon cannot be changed on iOS

### ISSUE THREAD

**Issue by AncientLust** [dotnet/maui#21603]
### Description

No metter what, there is no way to update app icon on iOS.

Tried to:
1. Check if `XSAppIconAssets` value aligned with image name in `info.plist`.
2. Use default icon name `appicon.svg`.
3. Change default icon name `appicon1.svg`.
5. Check if build action for icon file is set to `MauiIcon`.
6. Check if there is no extra entries for `MauiIcon` in `.csproj` file.
7. Deleted app from device + cleaned solution + drop `bin` and `obj` folders + restart the device.
8. Use PNG, SVG, WEBP images. 

Link to related closed issues:
https://github.com/dotnet/maui/pull/10812
https://github.com/dotnet/maui/issues/7786

### Steps to Reproduce

Repro project uses only appicon.svg in `.csproj`.
1. Move non-default icon named `appicon.svg` to some temp place.
2. Rename default icon `appiconfg.svg` to `appicon.svg`
3. Deploy the app 
4. Move non-default icon back, replacing `appicon.svg`
5. Full clean and redeploy
6. The icon won't change

### Link to public reproduction project repository

https://github.com/AncientLust/IconTest

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS  17.3.1

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
@AncientLust are you using Visual Studio on Windows to do this and then deploying through Hot Restart?

If yes, this is one of the [limitations](https://learn.microsoft.com/dotnet/maui/ios/hot-restart#limitations) of developing with Hot Restart.

**Comment by AncientLust** [comment]
Hi @jfversluis, yes I do. But even if I disable Hot restart in VS settings, and switch to Release build, it doesn't help to reflect the icon change.

**Comment by jfversluis** [comment]
I think you are confusing Hot Restart and Hot Reload. Are you using a Mac to build your iOS apps?

Or you connect your physical iOS device to Windows directly and do _not_ connect to a Mac build host? If that's the case then you are using Hot Restart, which you can't disable. That is the technique we use to let you develop iOS apps straight from Windows without using a Mac. However, this has some limitations, one of which is not being able to change your app icon.

Can you confirm that you are not using a macOS based machine other than the device you run your app on?

**Comment by AncientLust** [comment]
@jfversluis yes, I used iPhone wired to my Win PC. I connected it via mac host and now it works as expected. Probably makes sense to add Win Hot restart limitation into the [MAUI icon doc](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?view=net-maui-8.0&tabs=macios).

Thank you for your help.

**Comment by jfversluis** [comment]
Thanks for the suggestion (cc: @davidbritch)! As mentioned it is explicitly mentioned on the Hot Restart docs already.

Glad you figured it out!
