### ISSUE TITLE
Java.Lang.RuntimeException: 'Canvas: trying to draw too large(111335520bytes) bitmap.'

### ISSUE THREAD

**Issue by JohnYang1210** [dotnet/maui#21608]
### Description

```xaml
<ContentPage>
       <Grid>
<Image Source="hollywood.jpg"/>
</Grid>
</ContentPage>
```
UI is above described, when I run it in Android simulator, an exception called "Java.Lang.RuntimeException: 'Canvas: trying to draw too large(111335520bytes) bitmap." is throwed.
![image](https://github.com/dotnet/maui/assets/43445333/2009c695-9bc2-4323-be66-251d74c0ae05)

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

not yet

### Relevant log output

```shell
not yet
```

**Comment by RoiChen001** [comment]
Can't repro this issue on Android platform on the latest 17.10.0 preview 2(8.0.14.)

**Comment by jfversluis** [comment]
Have a look at this relevant discussion for Xamarin.Forms: https://github.com/xamarin/Xamarin.Forms/discussions/14978

If you search for the error message there are more examples available. This is because you're loading a very big image and basically your app runs out of memory. You will want to find a way to optimize that. This is however not a bug in the .NET MAUI SDK.

**Comment by JohnYang1210** [comment]
Fine,thanks for your reply.



---Original---
From: "Gerald ***@***.***&gt;
Date: Wed, Apr 3, 2024 18:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dotnet/maui] Java.Lang.RuntimeException: 'Canvas: trying to drawtoo large(111335520bytes) bitmap.' (Issue #21608)




 
Have a look at this relevant discussion for Xamarin.Forms: xamarin/Xamarin.Forms#14978
 
If you search for the error message there are more examples available. This is because you're loading a very big image and basically your app runs out of memory. You will want to find a way to optimize that. This is however not a bug in the .NET MAUI SDK.
