### ISSUE TITLE
. NET MAUI 7.0 & 8.0 HttpClientHandler.ClientCertificates is null

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#21601]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/-NET-MAUI-70--80-HttpClientHandlerC/10583320)._

---
Hi,

We are unable to add client certificate in HttpClientHandler. ClientCertificate is null;

Here's a code snippet:

var httpClientHandler = new HttpClientHandler();

httpClientHandler.ClientCertificateOptions = ClientCertificateOption.Manual;
httpClientHandler.SslProtocols = SslProtocols.Tls12;
httpClientHandler.ServerCertificateCustomValidationCallback = ValidateServerCertificate;

httpClientHandler.ClientCertificates.Add(clientCert);

ClientCertificates is null

We have the same problem using .Net 7 or .Net 8

Using the same code in Xamarin.Forms it is all good again.

Is this a bug in the library?

Thanks

---
#### Feedback Bot on 2/12/2024, 05:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Looks like this issue might be relevant here: https://github.com/dotnet/runtime/issues/73960

In either case, this is not something that originates in .NET MAUI, if the guidance in the issue above does not help, please report the error directly there for proper support. Thanks!
