### ISSUE TITLE
After rotating the emulator from horizontal to vertical orientation, the card of page My Recipes is truncated.

### ISSUE THREAD

**Issue by ninachen03** [dotnet/maui#21609]
### Description

After rotating the emulator from horizontal to vertical orientation, the card of page My Recipes is truncated.

### Steps to Reproduce

Steps to Reproduce
1.Download the project https://github.com/rachelkang/recipeSearch and open it in Visual Studio.
2.Click on the 'My Recipes' tab to navigate to the 'My Recipes' page.
3.Rotate the emulator clockwise (to the right) to the horizontal orientation.
4.Rotate the emulator counterclockwise (to the left) so that it is in the original vertical orientation.
Result:
After rotating the emulator from horizontal to vertical orientation, the card of page My Recipes is truncated.
![card ](https://github.com/dotnet/maui/assets/128687574/c131a213-c7eb-4538-be1c-dd7668a83833)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

8.0.20-nightly.10426+sha.f0c4dd19d4-azdo.9353326

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.14

### Affected platforms

Android

**Comment by ninachen03** [comment]
There was a same issue https://github.com/dotnet/maui/issues/16850 and closed fixed in Microsoft.Maui.Controls: 8.0.7

**Comment by MAUIoxo** [comment]
This question is not related to this big especially, but I am mostly working with iOS Simulator and noticed that my Android Simulator does rotate the entire screen and not scale from Portrait to Landscape. How can I get my Android Emulator to switch and change the view as shown in your animation?
