### ISSUE TITLE
TappedGestureRecognizer ignores Frame's IsEnabled

### ISSUE THREAD

**Issue by Mano176** [dotnet/maui#21619]
### Description

When having a TapGestureRecognizer inside a Frame that has IsEnabled set, the TapGestureRecognizer behaves weird depending on the platform.

### Steps to Reproduce

MainPage.xaml:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestMauiApp.MainPage"
             x:Name="this">

    <StackLayout>

        <Frame IsEnabled="{Binding IsFrameEnabled, Source={x:Reference this}}">

            <Frame.GestureRecognizers>
                <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" />
            </Frame.GestureRecognizers>
            
            <Label Text="I am a Label" />
        </Frame>

        <Button Text="IsEnabled-Switcher" 
                Clicked="Button_Clicked" />

    </StackLayout>
</ContentPage>
```

MainPage.xaml.cs:
```
using System.ComponentModel;

namespace TestMauiApp;

public partial class MainPage : ContentPage, INotifyPropertyChanged
{
    public MainPage()
    {
        InitializeComponent();
    }

    public new event PropertyChangedEventHandler? PropertyChanged;

    protected virtual void NotifyPropertyChanged(string propertyName)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    public bool IsFrameEnabled { get; set; }

    private void TapGestureRecognizer_Tapped(object sender, TappedEventArgs e)
    {
        Console.WriteLine("Here");
    }

    private void Button_Clicked(object sender, EventArgs e)
    {
        IsFrameEnabled = !IsFrameEnabled;
        NotifyPropertyChanged(nameof(IsFrameEnabled));
    }
}
```
- Android:
    - Current behaviour:
        - The Label's TextColor changes when clicking the IsEnabled-Switcher-Button.
        - The Frame is never clickable (the TapGestureRecognizer never fires).
    - Expected behaviour:
        - The Label should behave like it currently does.
        - The Frame should be clickable, when IsFrameEnabled is true.

If we initialize the IsFrameEnabled-Property like this
`public bool IsFrameEnabled { get; set; } = true;`, 
the Frame behaves like expected.

- WinUI:
    - Current behaviour:
        - The Label behaves like on Android (like it should)
        - The Frame is always clickable (the TapGestureRecognizer completely ignores the Frame's IsEnabled-Property).
    - Expected behaviour:
        - Same as mentioned above for Android

- iOS:
    - Current behaviour:
        - Not tested yet
    - Expected behaviour:
        - Same as mentioned above for Android and WinUI

### Link to public reproduction project repository

https://github.com/Mano176/MauiTapGestureRecognizerRepo

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

**Comment by mattleibow** [comment]
Does this work with Border?

**Comment by Mano176** [comment]
I added a reproduction projekt repository.

@mattleibow Sorry, I don't understand what you mean by "Does this work with Border?"

**Comment by XamlTest** [comment]
Verified on VS 17.10.0 Preview 3.0(8.0.20). Repro on Windows 11, Android 14.0-API34. Work as expected on iOS 17.2 and MacCatalyst.
[TestMauiApp.zip](https://github.com/dotnet/maui/files/14944262/TestMauiApp.zip)

**Comment by sisaacks** [comment]
I have somewhat of a similar issue, I have a frame inside of a contentview.  The contentview is display on another page.  The tap gesture does not work at all.  I can put a button outside of the tap gesture and it works just fine.

**Comment by JavierFajardoSecanda** [comment]
It's not working also with StackLayout

**Comment by jfversluis** [comment]
Since `Frame` is going to be deprecated in favor or `Border` for .NET 9 I think this has a low probability of still being fixed. As of such, I will be closing this one here. Thanks everyone!
