### ISSUE TITLE
Packaged Windows App Missing Permissions after installed?

### ISSUE THREAD

**Issue by ejwipp** [dotnet/maui#21626]
### Description

I'm finalizing a Xamarin to Maui port of an app that utilizes Bluetooth.  Bluetooth works when debugging with Visual Studio - my app is able to see and connect to Bluetooth devices.  When I publish the app for sideloading, the app is not able to access bluetooth services - it is like it is missing permissions.  The problem is not related to Debug/Release builds.  Bluetooth works when running the app within Visual Studio in either build.  Neither Debug/Release work when published.

I have the following in the package.appxmanifest:
```
<DeviceCapability Name="radios"/>
<DeviceCapability Name="bluetooth"/>
```

I've created a small test project that exhibits the same behavior as my app.  Please see the github link in this report.

An interesting note is that the test app worked correctly in the debugger even without the above <DeviceCapability> declarations.

### Steps to Reproduce

1. Make sure Bluetooth is enabled on the test machine.
2. Download the project, build and run in debug mode.
3. Click the 'Update' button.
4. The page will show 'Enabled' for Bluetooth and the last line of the Debug log will have "First or default: True".
5. Use add/remove programs to remove 'TestBluetooth'.
6. Publish the Windows app for sideloading - you will need to provide a signing certificate.
7. Run the .msix to install the app.
8. After the app loads, click the 'Update' button.
9. The page will show 'Disabled' for Bluetooth and the Debug Log will have a COM exception, and the last line will have "First or default: False".

### Link to public reproduction project repository

https://github.com/ejwipp/TestBluetoooth

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0 .net8.0

### Did you find any workaround?

No.  This behavior is preventing further testing of our app and release.  We need a fix or workaround ASAP.

**Comment by mattleibow** [comment]
Does it work if you use a valid certificate from the app store? Does it work when publishing as unpackaged?

I am wondering if you need to use a valid/windows-accepted cert for this.

**Comment by ejwipp** [comment]
I'm using the code signing certificate that we've previously used when submitting apps to the store.

I have not tried publishing as unpackaged.  I will have to investigate how to do that.  Do you have a link that describes it?

**Comment by mattleibow** [comment]
Basically set `<WindowsPackageType>None</WindowsPackageType>` in your app csproj: https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-unpackaged-cli?view=net-maui-8.0

If that works, then it may be some packaging related issue.

The fact that it works until you publish is weird and maybe some permission is being lost in the final app. If you unzip the msix file and look for an app manifest, are your permissions still listed? I think it is called AppxManifest.xml in the root of the msix.

**Comment by ejwipp** [comment]
It seems to me that this is a bug.  Shouldn't an x86 build be able to run fine?  Why does only the x64 work?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 3(8.0.7). Not repro on windows platform with sample project. 
https://github.com/ejwipp/TestBluetoooth
![image](https://github.com/dotnet/maui/assets/77434865/2514e1bb-4098-4dc5-b911-90c677784470)
