### ISSUE TITLE
MAUI Hybrid fails to build on Mac when a JSON file is present

### ISSUE THREAD

**Issue by datvm** [dotnet/maui#21633]
### Description

Unfortunately since #17078 is not getting reopened, I am creating this issue.

When a MAUI with Razor project (`Sdk="Microsoft.NET.Sdk.Razor"`) is compiled on MacOS with `dotnet build`, if there is a JSON file, it always fails with the following error:

```
MyFile/test-ja.json : error : The path '../../../../../../../../../Users/lukevo/Documents/Temp/TestLib/MyFile/test-ja.json' would result in a file outside of the app bundle and cannot be used. [/Users/lukevo/Documents/Temp/TestLib/TestLib.csproj::TargetFramework=net8.0-ios]
MyFile/test-ja.json : error :          [/Users/lukevo/Documents/Temp/TestLib/TestLib.csproj::TargetFramework=net8.0-ios]
MyFile/test.json : error : The path '../../../../../../../../../Users/lukevo/Documents/Temp/TestLib/MyFile/test.json' would result in a file outside of the app bundle and cannot be used. [/Users/lukevo/Documents/Temp/TestLib/TestLib.csproj::TargetFramework=net8.0-ios]
MyFile/test.json : error :          [/Users/lukevo/Documents/Temp/TestLib/TestLib.csproj::TargetFramework=net8.0-ios]
```

It doesn't matter if the JSON is referred by the project or not. No matter which combination you use below, the error always shows up.

```xml
	<ItemGroup>
		<!-- <None Remove="MyFile/**/*" /> -->
		<!-- <EmbeddedResource Include="MyFile/**/*" /> -->
	</ItemGroup>
```

It doesn't happen when compiling the same code on Windows.

### Link to public reproduction project repository

https://github.com/datvm/MauiHybridJsonFail

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Did you find any workaround?

Build on Windows.

**Comment by drasticactions** [comment]
@datvm You're correct, that issue is still happening and shouldn't have been closed. I reopened it, and am closing this one.
