### ISSUE TITLE
ScrollView with bindableLayout is not resized on Andorid

### ISSUE THREAD

**Issue by JohnYang1210** [dotnet/maui#21634]
### Description

Here is my xaml:
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiMoviesY.MainPage" Title="Home" >
    <VerticalStackLayout x:Name="wholeVS" >
        <Border Stroke="Blue"
                StrokeThickness="2"
                StrokeShape="RoundRectangle 5" x:Name="myBorder">
            <VerticalStackLayout Padding="2">
                <VerticalStackLayout.GestureRecognizers>
                    <TapGestureRecognizer NumberOfTapsRequired="1"
                                          Command="{Binding ChooseGenres}"/>
                </VerticalStackLayout.GestureRecognizers>
                <Label Text="Genres:"/>
                <FlexLayout BindableLayout.ItemsSource="{Binding Genres}" Wrap="Wrap">
                    <BindableLayout.ItemTemplate>
                        <DataTemplate>
                            <Border Stroke="CadetBlue"
                                    StrokeShape="RoundRectangle 15">
                                <Label Text="{Binding name}"
                                       TextColor="White"
                                       Padding="10"
                                       Background="CadetBlue"
                                       />
                            </Border>
                            
                        </DataTemplate>
                    </BindableLayout.ItemTemplate>
                </FlexLayout>
            </VerticalStackLayout>
        </Border>


        <ScrollView x:Name="myScrollViewer" >
            <VerticalStackLayout BindableLayout.ItemsSource="{Binding Movies}" x:Name="myVS" >
                <BindableLayout.ItemTemplate>
                    <DataTemplate>
                        <VerticalStackLayout Margin="10" 
                                             Spacing="10">
                            <VerticalStackLayout.GestureRecognizers>
                                <TapGestureRecognizer NumberOfTapsRequired="1"
                                                      Command="{Binding ShowMovies}"/>
                            </VerticalStackLayout.GestureRecognizers>
                            <Image Source="{Binding poster_path}"
                                   Aspect="AspectFit"
                                   />
                            <HorizontalStackLayout>
                                <Label Text="{Binding title}"
                                       FontAttributes="Bold"
                                       />
                                <Label HorizontalOptions="EndAndExpand"
                                       HorizontalTextAlignment="End"
                                       Text="{Binding vote_average,StringFormat='{0:N1} ⭐'}"/>
                            </HorizontalStackLayout>
                        </VerticalStackLayout>
                    </DataTemplate>
                </BindableLayout.ItemTemplate>
            </VerticalStackLayout>
        </ScrollView>
    </VerticalStackLayout>

</ContentPage>

```
then,I find the ScrollView did not work as expect, and below video is the thing:

https://github.com/dotnet/maui/assets/43445333/61519839-09a9-4ca2-bd54-1a6651b48c18

and I assign the scrollview's `HeightRequest` in `OnAppearing` method by hand
```
myScrollViewer.HeightRequest = wholeVS.Height - myBorder.Height;
```
and it really works:

https://github.com/dotnet/maui/assets/43445333/1d79fdec-ad20-4624-9429-6febd582ad84

Next,  again I find that, sometimes when I scroll , some picture in scrollview will not be shown integrally, like this:

https://github.com/dotnet/maui/assets/43445333/2a402f1d-e07e-4c32-836b-ed8482b605ff

finally, I have to register scroll event to make sure `myScrollViewer.HeightRequest` always equals `wholeVS.Height - myBorder.Height`, and it works.

https://github.com/dotnet/maui/assets/43445333/1fdf71cb-764a-4dd0-b59a-606605bcbaad

I have noticed similar issue (https://github.com/dotnet/maui/issues/12727), but it aims to IOS, and it is claimed to be solved(https://github.com/dotnet/maui/pull/16385), and 
is closed now. So I reopen this issue to hope for a perfect solution.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

yes, it is depicted in section `Description`

### Relevant log output

```shell
no response
```

**Comment by durandt** [comment]
(Not a MAUI team member)
I think using the ScrollView in a StackLayout is discouraged. Although what you are trying to achieve would have worked in Xamarin.Forms, the StackLayout seems to behave a bit differently in MAUI. 

See https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/scrollview?view=net-maui-8.0#scrollview-as-a-child-layout

The iOS bug you are referring to was the other way around, the ScrollView would not react to SizeChanged-events of its child-StackLayout.
