### ISSUE TITLE
Hamburger menu is always enabled

### ISSUE THREAD

**Issue by ganikapudisham** [dotnet/maui#21641]
### Description

I have this hamburger menu in my App. Though the hamburger menu is not visible its still clickable and pops out when clicked.
It should be visible and clickable only when the user is logged into the app.

### Link to public reproduction project repository

https://github.com/ganikapudisham/maui-matri

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2(8.0.14). Can not repro on android platform with sample project. I did not see the hamburger menu. if you still repro, could you help confirm that any different from yours

![hamburger](https://github.com/dotnet/maui/assets/128687574/9e817bde-06cd-4e24-8264-a60890d5b8ec)

**Comment by ganikapudisham** [comment]
Hi ,
After the splash screen , login screen will be displayed.
Click on the top left corner, though the hamburger icon is not visible. Menu will show up.

Regards
