### ISSUE TITLE
Border has an unexpected background animation

### ISSUE THREAD

**Issue by zeniya-takeshi** [dotnet/maui#21643]
### Description

When the BackgrondColor or CornerRadius of a Border is changed, unexpected animation occurs on iOS.
This is not a duplicate of https://github.com/dotnet/maui/issues/18204
#18204 workaround(NotAnimatedBorderHandler) can't solve this.
 
iOS(BackgroundColor)

https://github.com/dotnet/maui/assets/40626279/165f9c1c-0cb6-48f3-a83e-5cc65d9b92c4

iOS(CornerRadius)

https://github.com/dotnet/maui/assets/40626279/4fcd87c3-d9b1-4c0b-98b9-ee5181941ffe

Android(BackgroundColor) (This is not problem)

https://github.com/dotnet/maui/assets/40626279/034bdcee-7b40-400a-946e-79a8991f4f97

### Steps to Reproduce

1. create a Border
2. change its Background or CornerRadius

### Link to public reproduction project repository

https://github.com/zeniya-takeshi/BorderHasBackgroundAnimation.git

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

Use Frame.
But Microsoft recommends that developers use Border.

**Comment by RoiChen001** [comment]
Can repro this issue at iOS platform on the latest 17.10 preview 2(8.0.6&8.0.14).

**Comment by Phenek** [comment]
Border within a CollectionView appears to have a default BackgroundColor animation. 
This seems to be related to this issue.

This can be observed at the bottom of the CollectionView, where recycled view with different colors are use.
<img src="https://github.com/dotnet/maui/assets/4518686/a03095b0-575c-410e-b9d5-76f4c596987c" width="200" height="428" />

**Comment by albyrock87** [comment]
May you try using NuGet packages from my PR?
https://dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_apis/build/builds/122164/artifacts?artifactName=nuget&api-version=7.1&%24format=zip

**Comment by zeniya-takeshi** [comment]
Thanks for the bug fix! I’ve tested the NuGet packages, and the issue is now resolved. I really appreciate your help.

https://github.com/user-attachments/assets/444d51b9-a80b-4460-9697-9332a80585ba

https://github.com/user-attachments/assets/dd7cd99b-fe7c-4a62-b6aa-a724a1cc9738
