### ISSUE TITLE
System.Net.NetworkInformation.Ping support

### ISSUE THREAD

**Issue by gytangyao** [dotnet/maui#2167]
## Summary
support ping in every Platform

![image](https://user-images.githubusercontent.com/46317512/130028536-9491bd52-e5b9-4dde-9f1f-c21f3021c888.png)

**Comment by jfversluis** [comment]
This is not a .NET MAUI issue, this API lives in the [runtime](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs). They should add support for it. Please open an issue there to request it. Thanks!
