### ISSUE TITLE
Lots of build Error when Creating MAUI Blazor App using VS2022 File New Project Template

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#2168]
I am getting Lots of Build Error when creating MAUI Blazor Project using File-->New MAUI Blazor Project Template
![MAUI PRoject Build error](https://user-images.githubusercontent.com/3267605/129905853-74ca95af-7a1c-4052-9233-5930f7101b93.png)

![Visual Studio About](https://user-images.githubusercontent.com/3267605/129905887-0681d527-2cda-47d9-9584-b79db81958c4.png)

![dotnet info](https://user-images.githubusercontent.com/3267605/129905907-680dd29b-f9d5-4d7c-8966-dc1812489a44.png)

![MAUI Check](https://user-images.githubusercontent.com/3267605/129905945-819eb0e0-4245-4cc1-ad35-326ef68fa832.png)

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

@Eilon this sounds more like a Maui setup issue than anything else.

**Comment by Eilon** [comment]
@nssidhu does this happen with a .NET MAUI app _without_ Blazor?

**Comment by Eilon** [comment]
It looks like .NET 6 Preview 7 is somehow not properly installed. Can you try uninstalling it from Add/Remove Programs in Windows, and then run `maui-check` again? Also, please make sure you've installed the Windows App SDK from https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17 so that WinUI projects build. I think that `maui-check` doesn't install this.

**Comment by nssidhu** [comment]
Since .NET 6 Preview 7 got installed as part of VS2022 it does not allow uninstalling it from Add/Remove.
I will have to uninstall the VS 2022 and re-install it again.

Will update once i am done re-installing.

**Comment by nssidhu** [comment]
OK, 
1 )I removed all .NET SDK using Add/Remove (Except .NET 7 preview )
2) Uninstalled VS 2020 (This also removed .NET 7 Preview
3) Delete dotnet folder under program files

Installed VS 2022
Maui-check requires .NET 5 , so installed that
1) Ran Mau-check successfully installed everything
2) Installed Windows App SDK from

Created New MAUI Project(Not the Blazor one)

Build failed complaining about downgrading of the following package 

	<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0-preview" />
		<PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0-preview" />
		<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0-preview" />


Upgraded their version

```
<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.1" />
		<PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.1" />
		<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.1" />
```


Was able to successfully launch Simulator for IoS, since i don't have proper tools to develop for Ios, changed to Pixel

Build the project and build failed with the following error

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB3785	No SDKs were found for TargetPlatform = Windows v10.0.19041.0. SDKReference items will not be resolved. If your application requires these references there may be compilation errors.	MauiApp2.WinUI	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	2491
```	

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	APPX3217	SDK folder containing 'UAP.props' for 'UAP 10.0.19041.0' cannot be located. See http://go.microsoft.com/fwlink/?LinkID=798187 for more information.	MauiApp2.WinUI	C:\Users\admin\.nuget\packages\microsoft.projectreunion.winui\0.8.1\buildTransitive\Microsoft.Build.Msix.ReunionManifest.targets	22	
```

**Comment by nssidhu** [comment]
Yes I did that. I even tried this on clean VVM.Still would get error using provided file new project template.


Sent from Yahoo Mail for iPhone


On Friday, August 27, 2021, 11:28 AM, Eilon Lipton ***@***.***> wrote:




@nssidhu can you confirm you installed this VSIX? https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17

(It looks like your text got cut off in your previous message, so I wasn't sure.)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Eilon** [comment]
@nssidhu in the VS Installed can you make sure you have `Windows 10 SDK (10.0.19041.0) installed?

![image](https://user-images.githubusercontent.com/202643/131379995-b2ecf885-2a75-4060-9902-0c91e61d5cbd.png)

**Comment by nssidhu** [comment]
Thanks @Eilon , Indeed it is not showing up as installed. 
Is this in addition to the ProjectReunion installation via Marketplace or a better way of doing the same ?

FYI, I did installation of ProjectReunion via the Link, https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17 

I will try some time later in the week to check if everything works after installing that.

**Comment by Eilon** [comment]
Yes, this is an additional requirement.

**Comment by nssidhu** [comment]
OK, Tried it. No compile error after installing both the Packages.
did run maui-check again after installing the above packages.

But when i run, nothing shows up. I am running VS2022  in VMWare Workstation.

![image](https://user-images.githubusercontent.com/3267605/132002658-16b80604-941e-45fb-aed2-39d24a2a3da0.png)

**Comment by Eilon** [comment]
To run the WinUI version, you have to run it from VS. I don't think it's supported at this time to run from command line.

To run from VS there are two steps:

1. Right-click on the `MyProject.WinUI` project and select `Deploy`. This will install the app into the Start Menu.
    ![image](https://user-images.githubusercontent.com/202643/132040403-dabd5a49-09a2-44fb-806a-badd07a89103.png)
2. In your Start Menu find the app and click to run (it should be at the very top because it's a "new" app).

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
