### ISSUE TITLE
Moving items in grouped CollectionView is moving the wrong items

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#21698]
### Description

When moving items in a grouped CollectionView, after moving several groups and items, the CollectionView starts behaving strangely, and it looks like it's moving the wrong items.

### Steps to Reproduce

1. Open the repro project.
2. Open the second tab with a grouped CollectionView.
3. Move items in the second group: it works properly.
4. Move group1 down and up again.
5. Move items in the second group: it seems like item1 from group1 is also moving now.

Move items in Group2: OK
[untitled2.webm](https://github.com/dotnet/maui/assets/12516566/44f516be-1ddd-40fd-8402-e9b0471c9f0d)

Move Group1: OK
[untitled1.webm](https://github.com/dotnet/maui/assets/12516566/e47c1adb-43ad-4d37-8820-9cf70f1dee5b)

Move items in Group2: KO
[untitled3.webm](https://github.com/dotnet/maui/assets/12516566/5e542943-3a02-4052-8179-49ed5de499f5)

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppCollectionViewReorder

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No workaround

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2(8.0.14 & 8.0.10). Can repro on android platform with sample project.

**Comment by tranb3r** [comment]
@rmarinho 
I've just tested the latest maui nightly.
I do not consider that this issue is totally fixed. When moving items within a group, items from the other groups below still flicker (although they do not move anymore). Can this be fixed?
