### ISSUE TITLE
@ontouchstart:stopPropagation | @ontouchstart:preventDefault in iOS is not working.

### ISSUE THREAD

**Issue by rwecho** [dotnet/maui#21699]
### Description

Stop event propagation.

<img width="1023" alt="image" src="https://github.com/dotnet/maui/assets/8048753/527808fc-a337-4225-b640-524c89b81bee">

### Steps to Reproduce

1. Create a MAUI Blazor Hybrid project.
2. Add Block1 and Block2 two div.
3. Add @ontouchstart:preventDefault  @ontouchstart:stopPropagation to Block2
4. Debug in iOS

``` Html
<div class="block1">
    block1 hello world


    <div class="block2"
        @ontouchstart:preventDefault
        @ontouchstart:stopPropagation>block 2</div>
</div>

```

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

### Did you find any workaround?

addEventListener with touchstart to Block2, and in the function with handling e.prentDefault(); e.stopPropagation()

**Comment by rwecho** [comment]
I ran it on iOS simulator not real device.

**Comment by Eilon** [comment]
@rwecho thank you for the detailed info. Can you try the same code in a Blazor Web app and run the app in Safari on iOS (even in the emulator)? Does the same issue take place there?

**Comment by Eilon** [comment]
@rwecho can you also let us know what `not working` means? Does it crash the app? Or does it not respect the touch events?

**Comment by rwecho** [comment]
@Eilon `not working` is that the event did not be triggered?

As the above image, if I click the block 2 div, “block1 touch start”  should not print.

**Comment by rwecho** [comment]
@Eilon  I test it on browser, the preventDefault & stopPropagation  can't constraint the event bubbling in js.
It's that right? If that would explain it.

**Comment by Eilon** [comment]
> @Eilon I test it on browser, the preventDefault & stopPropagation can't constraint the event bubbling in js. It's that right? If that would explain it.

OK, so you're saying that if you have a regular Blazor Web app and you use Safari to browse to it, it's also not working?
