### ISSUE TITLE
[Windows Only]ImageButton get stuck in "PointerOver" state if right click

### ISSUE THREAD

**Issue by wjoygz** [dotnet/maui#21706]
### Description

ImageButton get stuck in "PointerOver" state if right click

### Steps to Reproduce

1. New a MAUI app 
2. Add an ImageButton and set the visual state like this way

```
<ImageButton Source="image.png"
             ...>
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroup x:Name="CommonStates">
            <VisualState x:Name="Normal">
                <VisualState.Setters>
                    <Setter Property="BackgroundColor"
                            Value="blue" />
                </VisualState.Setters>
            </VisualState>
            <VisualState x:Name="PointerOver">
                <VisualState.Setters>
                    <Setter Property="BackgroundColor"
                            Value="red" />
                </VisualState.Setters>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>
</ImageButton>
```

4. Right click the ImageButton and it get stuck in "PointerOver" state

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

macOS works good

### Did you find any workaround?

no

**Comment by kevinxufei** [comment]
Can repro this issue at Windows platform on the latest 17.10.0 Preview 3 (8.0.0-rc.2.9530/8.0.20).
