### ISSUE TITLE
[Bug] Valid splash screen colors populated from SKColor

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#2170]
### Description

Imagine my surprise when I set the Color property of a MauiSplashScreen to Red, and I got a red background on my splash screen. I thought that only hex values would work. So nice feature :)

However, when I looked at the resizeter code, I saw the valid values for Color are populated from `SKColor` rather than `Microsoftsoft.Maui.Graphics.Colors`. I get that they are both similar (or even identical), but it's a difficult one to have to introduce a SkiaSharp type into a MAUI doc, when most users won't know SkiaSharp.

**Comment by davidbritch** [comment]
Closing, as I realise this won't be changing.

**Comment by mattleibow** [comment]
I think they have the same items in the list? Since we already use SkiaSharp it is not an additional dep.

**Comment by davidbritch** [comment]
SKColors has 142 fields. Colors has 148.

**Comment by davidbritch** [comment]
Values that SKColors has, that Colors doesn't:

- Empty

Values that Colors has, that SKColors doesn't:

- DarkGrey
- DarkSlateGrey
- DimGrey
- Grey
- LightGrey
- LightSlateGrey
- SlateGrey

So it's purely that `Colors` duplicates its gray values with both ...Gray and ...Grey spellings (e.g. SlateGray and SlateGrey).

**Comment by mattleibow** [comment]
I see. I might as well do that in skia too then.

**Comment by rmarinho** [comment]
fixed by #9788
