### ISSUE TITLE
[iOS] Collectionview itemslayout styling changes with footer

### ISSUE THREAD

**Issue by Uridel** [dotnet/maui#21728]
### Description

When using a collectionview that has the itemslayout property and a footer the styling becomes all wrong.
So far I have only encountered this on iOS and when there is 1 item in the collection.

Code to reproduce:

`<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			  xmlns:cs="http://chipsoft.com/core/presentation"
             x:Class="MauiApp1.MainPage">

	<ContentPage.Resources>
	</ContentPage.Resources>

	<CollectionView x:Name="collection" ItemsLayout="VerticalGrid, 2">
		<CollectionView.ItemTemplate>
			<DataTemplate>
				<Label Text="{Binding Name}" BackgroundColor="red" HeightRequest="200" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"/>
			</DataTemplate>
		</CollectionView.ItemTemplate>
		<CollectionView.Footer>
			<ContentView >
				<ContentView.ControlTemplate>
					<ControlTemplate>
						<Grid RowDefinitions="Auto, *">
							<ContentPresenter Grid.Row="0"/>
							<ContentView Grid.Row="1"  HeightRequest="100" InputTransparent="True"/>
						</Grid>
					</ControlTemplate>
				</ContentView.ControlTemplate>
			</ContentView>
		</CollectionView.Footer>
	</CollectionView>
</ContentPage>
`

### Steps to Reproduce

1. Create a collectionview with 1 item and add `ItemsLayout="VerticalGrid, 2"`
2. Add a Footer with a contentview controltemplate
3. have it contain any 2 controls 
4. The item will be displayed in the middle instead of to the left.

Expected behavior
The item is shown on the left side of the page

Actual behavior
The item is shown on the middle of the page

### Link to public reproduction project repository

https://github.com/Uridel/CollectionviewLayout

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

no

**Comment by Uridel** [comment]
Here is a link to the project with which it can be reproduced https://github.com/Uridel/CollectionviewLayout

**Comment by QianaJiao** [comment]
Can repro this issue at iOS platform on the latest 17.10 Preview 6 (8.0.3 & 8.0.21).
