### ISSUE TITLE
MAUI CI build hangs when running on ARM Apple M machines

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#21727]
### Description

We are trying to move our CI to use more modern build machines , but we are facing issues with stability in our builds.  when using the new Somonoma machines Mac mini M1 and M2. Sometimes they are just hanging during some build step. 

We have connected to the machines remotely to see if there's any popup on the machine but nothing is showing.

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9385437&view=logs&j=0e3f2fb8-7a3a-523c-6f79-029322d7bc72&t=69af17c4-48e9-5b60-0f8e-574934ce351e&l=13

Locally seems we can't reproduce the issue. 

### Steps to Reproduce

Start new CI build for Device Tests here

https://devdiv.visualstudio.com/DevDiv/_build?definitionId=14934&_a=summary

Change the iOS or Android pool to be :

```
name: MAUI-Testing
demands:
- macOS.Name -equals Sonoma
```

You can start only the iOS stage and see if any of the builds will hang. 

<img width="504" alt="Screenshot 2024-04-09 at 14 42 40" src="https://github.com/dotnet/maui/assets/1235097/37d512fd-74c6-477a-a76a-49dbbc68bfed">

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

**Comment by dimonovdd** [comment]
@rmarinho Hi, did you manage to find any workarounds?

**Comment by rmarinho** [comment]
Nop not yet

**Comment by bmacombe** [comment]
I recently had random M2 Mac build hangs on my CI pipeline, it was because the DevOps agent installed was the x64 version (so running in Rosetta) and not arm64. I assume this wouldn't be an issue on MS hosted machines, but there was an issue for with the add agenda UI in dev ops that wasn't presenting the arm64 download in some cases, so I installed the wrong version.

Mainly posting this here if it helps anyone with similar issues.

**Comment by rmarinho** [comment]
This was fixed using that fix @bmacombe thanks

**Comment by dimonovdd** [comment]
@rmarinho both Xamarin and MAUI projects are build on my CI. I really don't understand how to solve this.

To install dependencies, I use a similar script:

https://gist.github.com/dimonovdd/226a48a00f9bbe89578615225cd7bd34

**Comment by rmarinho** [comment]
@dimonovdd  this is related with the azdo agent you install on a ARM Mac. following these instructions make sure you instal arm64 agent and not x64  https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/osx-agent?view=azure-devops#azure-pipelines

**Comment by dimonovdd** [comment]
@rmarinho I don't use Azure.

**Comment by bmacombe** [comment]
@dimonovdd Also, unless it's been fixed, there is a bug in DevOps that doesn't show the arm64 version in one of the agent setup screens. That is how I ended up with the x64 agent installed, I didn't even realize there was an arm64 version.

https://developercommunity.visualstudio.com/t/When-setting-up-an-Agent-on-MacOS-the-do/10733866
