### ISSUE TITLE
Firebase Messaging (FCM) is not working in Maui net8.0

### ISSUE THREAD

**Issue by ganikapudisham** [dotnet/maui#21730]
### Description

Firebase token is not getting generated.

### Steps to Reproduce

1) Add break point on FirebaseService class within OnNewToken() method.
2) Execute the github repo.
3) The breakpoint does not get hit.

### Link to public reproduction project repository

https://github.com/ganikapudisham/maui-matri/tree/firebase

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

SDK Version: 8.0.202

### Did you find any workaround?

No, I could not find any workaround.

**Comment by RoiChen001** [comment]
Can repro this issue at Android platform on the latest 17.10.0 Preview 3(8.0.14&8.0.20).

**Comment by RoiChen001** [comment]
Can repro this issue at Android platform on the latest 17.10.0 Preview 3(8.0.14&8.0.20).

**Comment by ganikapudisham** [comment]
This worked for me
https://github.com/dotnet/maui/issues/5458
