### ISSUE TITLE
RoundRectangle on Grid Column set to Auto... Slowly stretches the Grid column 

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#21746]
### Description

RoundRectangle on Grid Column set to Auto... Slowly stretches the grid column 
To verify Comment out  RoundRectangle set on Column  2 and uncomment Rectangle:

            <Grid

                Background="LightPink"
                ColumnDefinitions="1*,50,Auto,3*,1*"
                ColumnSpacing="2" HeightRequest="300">
                <RoundRectangle
                    CornerRadius="6" Fill="Red"
                    HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand" />
                <RoundRectangle
                    Grid.Column="1" CornerRadius="6"
                    Fill="Red" HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand" />
                <RoundRectangle
                    Grid.Column="2" CornerRadius="6"
                    Fill="blue" 
                     />
                
                <RoundRectangle
                    Grid.Column="3" CornerRadius="6"
                    Fill="Red" HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand" />
                <RoundRectangle
                    Grid.Column="4" CornerRadius="6"
                    Fill="Red" HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand" />

            </Grid>

### Steps to Reproduce

RoundRectangle on Grid Column set to Auto... Slowly stretches the Grid column 

### Link to public reproduction project repository

https://github.com/pierre01/MAuiAutoGridTest)

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

### Did you find any workaround?

Use rectangle instead

**Comment by pierre01** [comment]
![RoundRect](https://github.com/dotnet/maui/assets/2603287/3c624ce0-7bb8-405f-9ee3-9b45855b339f)

**Comment by RoiChen001** [comment]
Can repro this issue on the latest 17.10.0 Preview 3(8.0.20), but 8.0.0-rc.2.9530 works fine.
