### ISSUE TITLE
Unable to cache image Exception after version 8.0.9

### ISSUE THREAD

**Issue by JoacimWall** [dotnet/maui#21748]
### Description

After upgrading from 8.0.6 to 8.0.9 or higher like 8.0.20 we get this error. 

This is image from Azure and is valid for 24 hours so you would need a new url from me when you debug it.  FYI this error is not related to that I use a simulator this error has bin reproduced in TestFlight also. 

Microsoft.Maui.UriImageSourceService: Warning: Unable to load image URI 'https://saprodbabyappvb3o.blob.core.windows.net/userprofileimages/libero.se/1e063891-df37-41e2-9622-3dbe7b2c0f15.jpg?skoid=51d2c490-473d-4ba8-abb6-2e58e5c9b21a&sktid=f101208c-39d3-4c8a-8cc7-ad896b25954f&skt=2024-04-10T06%3A43%3A16Z&ske=2024-04-11T06%3A48%3A16Z&sks=b&skv=2023-11-03&sv=2023-11-03&st=2024-04-10T06%3A43%3A16Z&se=2024-04-11T06%3A48%3A16Z&sr=b&sp=r&sig=RItiGd%2Fm8KojDt2vX5lRbgiVrBvtc7kHdR10WNWlXb0%3D'.

System.InvalidOperationException: Unable to cache image at '/Users/joacimwall/Library/Developer/CoreSimulator/Devices/80FF6BFF-8F71-47B6-B3D1-FED80EC0B3DD/data/Containers/Data/Application/3D672B73-8730-4BEE-B943-6D234D87D46E/Library/Caches/com.microsoft.maui/MauiUriImages/D9FCD29404245B2E.jpg?skoid=51d2c490-473d-4ba8-abb6-2e58e5c9b21a&sktid=f101208c-39d3-4c8a-8cc7-ad896b25954f&skt=2024-04-10T06%3A43%3A16Z&ske=2024-04-11T06%3A48%3A16Z&sks=b&skv=2023-11-03&sv=2023-11-03&st=2024-04-10T06%3A43%3A16Z&se=2024-04-11T06%3A48%3A16Z&sr=b&sp=r&sig=RItiGd%2Fm8KojDt2vX5lRbgiVrBvtc7kHdR10WNWlXb0%3D'.
   at Microsoft.Maui.UriImageSourceService.CacheImage(NSData imageData, String path)
   at Microsoft.Maui.UriImageSourceService.DownloadAndCacheImageAsync(IUriImageSource imageSource, CancellationToken cancellationToken)
   at Microsoft.Maui.UriImageSourceService.GetImageAsync(IUriImageSource imageSource, Single scale, CancellationToken cancellationToken)

### Steps to Reproduce

Start the provided project that's target MAUI version 8.0.9 then you would see that the image not showing.
Down grade to 8.0.6 and the image works. 

### Link to public reproduction project repository

https://github.com/JoacimWall/Joacim_Bug_Report/tree/main/ImagBbug

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

iOS

### Did you find any workaround?

downgrade to 8.0.6. but this is not an option we need other bug fixes that is in newer versions.

**Comment by RoiChen001** [comment]
Can repro this issue at iOS platform on the latest 17.10.0 Preview3 (8.0.20).
![8 0 20](https://github.com/dotnet/maui/assets/143168639/f524cca2-974d-4c45-82a5-40cd5128f2ae)

**Comment by mattleibow** [comment]
I broke this I think when calculating the image filename. Before it was forcing everything to be a png, but I used the url extension: https://github.com/dotnet/maui/commit/e15cf82cf6ca18292fe90d9bde1f3e7d23e69cd2#diff-5b4c12343494c46071fc9079950656933700a4d80490aed3a136c4ca581ff533L28
