### ISSUE TITLE
Issues fetching data during splash screen loading (deadlock)

### ISSUE THREAD

**Issue by BrandanN21** [dotnet/maui#21763]
### Description

We are trying to fetch some necessary data required to run our application during the splash screen loading in AppShell.xaml.cs. We have our OnAppearing() method where we are wanting to make our method calls and await them before loading into the main page of the application. 

This logic is as follows:
```
protected override async void OnAppearing()
    {
        base.OnAppearing();
        
            try
            {
                Task.Run(async () => await FetchDataOnLoad()).Wait();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
    }
  
```

This creates a deadlock when loading our app and seeing the splash screen come up. 

We have tried various methods of await and async operations as well as using .RunSynchronously() to figure out how to get our data loaded into the app before displaying the main page. 

Is this something that is possible to do on the AppShell.xaml.cs file? Or are we going about fetching data incorrectly during splash screen loading? 

Would appreciate some insight to what the best approach is to achieve this functionality. Thanks!

### Steps to Reproduce

Use some fashion of Task.Wait() in AppShell.xaml.cs within the OnAppearing() method.

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

No workaround has been found

### Relevant log output

```shell
We get no relevant log output just a native stack trace error after the application hangs: Exiting early due to double fault.
```

**Comment by Ghostbird** [comment]
I solved the same problem in a different way, and that hasn't deadlocked on us _yet_.

```csharp
public static MauiApp CreateMauiApp() {
  var app = MauiApp.CreateBuilder().Build();
  Task.Run(() => {
    // Load data with blocking call
  }).Wait();
  return app;
}
```

The crux here is that we block the thread that runs `CreateMauiApp`, and that seems to be fine. The splash screen only disappears after `CreateMauiApp` returns and app startup continues.

Of course our real code obscures this a bit with abstractions that ensure the data is loaded on the correct services and hides it behind an extension method, but I think this is example captures the gist of it.

**Comment by PureWeen** [comment]
Using `Wait` or `Result` is never going to be a good idea because you will always block the UIThread. 

Doing so inside CreateMauiApp might cause your iOS app to crash because iOS requires your app to start in a certain amount of time and if you are blocking that process it will kill your app. 

For these scenarios you might look at creating a landing page that looks like your splashscreen or a loading screen that resembles your first page and then once the data has loaded you can swap that in. 

https://developer.apple.com/design/human-interface-guidelines/loading#Best-practices

**Comment by aritchie** [comment]
Async Waits freeze the thread.  You really want to avoid them at all causes ESPECIALLY on mobile where the OS has far more of a death grip on the execution platform.

My recommendation if you have async processes that need to run "before" your app is to create a "StartupPage" and navigate to that almost like a secondary splash screen.  Do your async code there without the Wait

**Comment by Ghostbird** [comment]
I know that in theory that is true, but that is exactly something that is so extremely common that I'd rather see it as part of the framework, rather than as something every developer has to build themselves.

As I said, our `Wait` usage hasn't caused problems _yet_, and we'll address that when it happens.

**Comment by BrandanN21** [comment]
Thanks for all the great information! I think given we want to stick with best practices we are going to explore the option of using a sort of extended splash screen to achieve what we are looking for. Appreciate all the advice and insight to how others handle this in their mobile applications!

**Comment by BrandanN21** [comment]
@PureWeen or @aritchie We are working to implement our 'extended' splash screen for data loading but we are having trouble registering our content page and injection our view model as we traditionally do with all our other pages. 

Within our AppShell.xaml.cs file onAppearing() we navigate our users to this new extended splash screen. We keep getting an error `No parameterless constructor found for 'LoadingPage'. ` Are we doing something wrong here? Our view and view model are registered the same as all of our others and nothing is standing out to us other than we are trying to navigate to this page from the AppShell.xaml.cs file. 

Is this the best approach here, or should this 'loading page' be set up in another way to allow us to inject our view model for binding context?

Appreciate any help with this. Thanks!
