### ISSUE TITLE
Android-CollectionView - MeasureFIrstItem breaks layout

### ISSUE THREAD

**Issue by Alex-111** [dotnet/maui#21778]
### Description

If I use a collectionview on Android with ItemSizingStrategy="MeasureFirstItem" then the layout of the items does not work as expected - see Repro

### Steps to Reproduce

Just start the repro.
I use a grid with fixed columns (3*,1*). but the CollectionView items did not respect that layout.

![image](https://github.com/dotnet/maui/assets/18511703/ef657a44-0fb1-4481-836b-953d7c72e590)
 

### Link to public reproduction project repository

https://github.com/Alex-111/ReproCollectionViewFirstItem

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

-

### Did you find any workaround?

use MeasureAllItems, but this has a big impact of performance!

Maybe it is related to https://github.com/dotnet/maui/issues/7562

**Comment by XamlTest** [comment]
Verified on VS 17.10.0 Preview 3.0(8.0.20). Repro on Android 14.0-API34, not repro on iOS 17.2 with below Project:
[ReproCollectionViewFirstItem.zip](https://github.com/dotnet/maui/files/14955779/ReproCollectionViewFirstItem.zip)

**Comment by markusroessler** [comment]
I started to notice this bug after updating from 8.0.21 to 8.0.40. Elements within the ItemTemplate's Grid start to overlap 
and elements within a VerticalStackLayout don't use all available width when setting ItemSizingStrategy="MeasureFirstItem". @PureWeen is this caused by https://github.com/dotnet/maui/pull/22270 ?

**Comment by vecalion** [comment]
Experiencing the same issue after updating to 8.0.40.

**Comment by PeWu09** [comment]
In our case, where an item template contains several labels and canvas (which means it is not completely trivial) scrolling performance on Android with _MeasureAllItems_ is utterly not acceptable - laggy and scrolling tends to stop at random points. On the other hand, _MeasureFirstItems_ greatly improves performance, but then the layout is corrupted - some elements are only partially rendered, some disappears, etc.

Not reproducible on iOS. Tested on both 8.0.61 SR6.1 and 9.0.0-preview.5.24307.10.

Just take a look at android trace for initial displaying of collectionview/scrolling (looks quite familiar for both scenario). When I see something like that I am a bit sceptical about the performance. Despite some ordinary setup, every single list item is measured and layouted sequentially. Yea, we all know the concept of UI thread, but then final effect is what matters.

![image](https://github.com/dotnet/maui/assets/174720388/ac41af81-630c-4c85-a314-67f508a08061)

**Comment by bcaceiro** [comment]
I am also facing this: using MeasureFirstItem, the layout does not render correctly - I can see, ind ebug, and with hotreload, that it appears and then disappears, so :
- Excess of layout measures / passes and the last one is making the elements disappear / getting cut.

**Comment by Domik234** [comment]
I am also facing saming similar.

CollectionView.ItemSizingStrategy: MeasureFirstItem

Only on Android this happens:
https://github.com/user-attachments/assets/8e018a00-744f-49ad-8e60-287ea2cce9da

Basically first item is measured wrong and oversizes to second item. All items after the first are measured the same size. Interacting with the first one (pressing on it invokes BackgroundColor change) leads to remeasuring and correcting the position. So then they are all aligned correctly but all of them (first to last) have some additional space that should not be there. 

On iOS this works correctly and background color on pressing fills whole bounds of view.
