### ISSUE TITLE
DesignMode.IsDesignModeEnabled always returns true when in Debug (with Hot Reload enabled?), breaking OrientationStateTrigger

### ISSUE THREAD

**Issue by FlavioGoncalves-Cayas** [dotnet/maui#21776]
### Description

Apparently DesignMode.IsDesignModeEnabled always returns true when running in Debug. 
I noticed this when my OrientationStateTrigger did not react to MainDisplayInfoChanged, as it only subscribes to the event when IsDesignModeEnabled returns false.

Observed on Android (Emulator) and iOS (Simulator iOS 17.2 and iPhone XS Max iOS 17.4).

### Steps to Reproduce

1. Clone repro repository
2. Start
3. Observe Label showing the value of IsDesignModeEnabled

### Link to public reproduction project repository

https://github.com/FlavioGoncalves-Cayas/MAUI_IsDesignModeEnabledIssueRepro

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

iOS 17.2, iOS 17.4, Android 14

**Comment by FlavioGoncalves-Cayas** [comment]
It looks like Hot Reload might be the culprit here. As deactivating Hot Reload results in IsDesignModeEnabled being false again.

**Comment by PureWeen** [comment]
@drasticactions thoughts?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 3(8.0.14&8.0.20). Not repro on android and iOS platforms. IsDesignModeEnabled lable value always displays false

**Comment by drasticactions** [comment]
None of the VS XAML Hot Reload agents (Xamarin.Forms or MAUI) change IsDesignModeEnabled, and none of our implementations depend on that setting. Rider has their own implementation and I don't have a way to verify what they are doing or if they are influencing it, but running it in Rider on my Mac it does show as true. In VS with our agents, it's false (unless you've changed it in your program).

I would file the bug with them.

**Comment by PureWeen** [comment]
Closing based on @drasticactions 's comments
