### ISSUE TITLE
Linking errors when running a maui app on physical iOS device referencing nuget packages

### ISSUE THREAD

**Issue by deelw** [dotnet/maui#2179]
### Description
Using Nuget packages in a Maui project lead to linker errors when running on physical iOS device while they run successfully on the iOS Simulator

### Steps to Reproduce

1. Add one or more of the following packages:
```shell
	  <ItemGroup>
		<PackageReference Include="Microsoft.AppCenter" Version="4.1.0" />
		<PackageReference Include="Microsoft.AppCenter.Analytics" Version="4.1.0" />
		<PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.1.0" />
		<PackageReference Include="Portable.BouncyCastle" Version="1.8.10" />
		<PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
		<PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
		<PackageReference Include="zetetic-sqlite-net-base" Version="4.4.3" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.8.0" />
	</ItemGroup>
```
2. Succesfull run on simulator: `dotnet build -t:Run -f net6.0-ios` 
3. Change the RuntimeIdentifier iossimulator-x64 to ios-arm64 in the project file
4. Run on physical device:  `dotnet build -t:Run -f net6.0-ios`

### Expected Behavior
I expect the app successfully running on my device

### Actual Behavior
I get linker errors:

```shell
ILLink : iOS error IL6999: Failed to execute the custom steps. [/Users/username/Projects/MauiApp/MauiApp/MauiApp.csproj]
ILLINK : error MT2362: The linker step 'Registrar' failed during processing: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) [/Users/username/Projects/MauiApp/MauiApp/MauiApp.csproj]
/usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(82,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/username/Projects/MauiApp/MauiApp/MauiApp.csproj]
```

### Basic Information

- Version with issue: .Net Maui Preview 7
- IDE: Visual Studio Code on Mac
- Platform Target Frameworks:
  - iOS:  net6.0-ios
- Nuget Packages:
  - Microsoft.AppCenter Version="4.1.0"
  - Microsoft.AppCenter.Analytics Version="4.1.0"
  - Microsoft.AppCenter.Crashes Version="4.1.0"
  - Portable.BouncyCastle Version="1.8.10"
  - Newtonsoft.Json Version="12.0.3"
  - System.Numerics.Vectors Version="4.5.0"
  - zetetic-sqlite-net-base Version="4.4.3"
  - System.IdentityModel.Tokens.Jwt Version="6.8.0"

- Affected Devices:
  - iPhone 7

**Comment by juansturla** [comment]
I know you are not using Visual Studio 2022, but maybe it's related to this?

![image](https://user-images.githubusercontent.com/10248860/130638998-b61c362f-5e3f-40ab-941a-c2f7f95af651.png)

**Comment by deelw** [comment]
@juansturla Thanks for your suggestions :)
I think it's not related because I can deploy to my physical iOS device. Only when I reference nuget packages it fails.
