### ISSUE TITLE
XAML ContentPage.Content required for data to appear.

### ISSUE THREAD

**Issue by StewBash** [dotnet/maui#21790]
### Description

During testing I was having a problem with data not showing in a very simple CollectionView. After a few attempts I discovered that if the XAML <ContentPage.Content> section is a any StackLayout. The data will not appear in the bound collectoin view.

Per the MS instructions: 

The Content property isn't required in XAML because elements defined for use in .NET MAUI XAML are allowed to have one property specified as the [ContentProperty](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.contentpropertyattribute) attribute on the class:

### Steps to Reproduce

New Project...
Place a CollectionView inside of any stack layout that is the primary content element. Bind the collection view ItemsSource property to a class and the contents will not show, despite having several items in the source.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Use ContentPage.Content and it appear to no longer have issues.

**Comment by jfversluis** [comment]
Can you please provide some code to demonstrate what you mean? I don't think this has to do with having to specify the `Content` property, but more with wrapping a `CollectionView` inside of a `StackLayout` and then the size not being updated accordingly.

For more information about layouts, please see: https://github.com/dotnet/maui/blob/main/docs/design/layout.md
