### ISSUE TITLE
ToolTipProperties.Text does not update when used in DataTemplate

### ISSUE THREAD

**Issue by MSicc** [dotnet/maui#21827]
### Description

Trying to update the Text of ToolTipProperties.Text does not work when used in a DataTemplate

Tested to update:

1. via Binding to a Boolean Value, using the BoolToObjectConverter from the Toolkit
2. via Binding to a string in a ViewModel (to verify it does not work)

I use compiled bindings.

### Steps to Reproduce

1. Attach a ToolTipProperties.Text to any of the controls inside a DataTemplate
2. Try to update the Text from the ViewModel

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS, I was *not* able test on other platforms

### Affected platform versions

macOS 14.4.1

### Did you find any workaround?

no

**Comment by jfversluis** [comment]
Besides a description of what you're trying to do, please also add some code, ideally a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md).

Thanks
