### ISSUE TITLE
[Bug] Drawn line does not shown on view while it point difference is 8000

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#2182]
### Description

I was create the custom drawable view by NativeGraphicsView. In that view, draw the line on canvas from(0, 0) to (8000, 0) but the line was not shown. 

### Steps to Reproduce

1. Draw the line on canvas
2. Specify the drawable view bounds more than 7000
3.  Drawn line on canvas not shown

### Expected Behavior

- Drawn line shown on view

### Actual Behavior

- Drawn line does not shown on view

**Comment by jsuarezruiz** [comment]
@Sasikumar3595 Could you attach a small sample where reproduce the issue?. If not possible, could you share the versions used etc?

**Comment by Sasikumar3595** [comment]
@jsuarezruiz ,

It was replicated on latest preview version 11 also.
