### ISSUE TITLE
ScrollView does not work inside VerticalStackLayout

### ISSUE THREAD

**Issue by vitalbit** [dotnet/maui#21822]
### Description

Using ScrollView inside VerticalStackLayout does not provides scroll ability.

### Steps to Reproduce

You can use the following XAML markup to verify it:
```
<Grid ColumnDefinitions="*, *">
    <VerticalStackLayout Grid.Column="0">
        <Label Text="ScrollView inside VerticalStackLayout"
               HorizontalTextAlignment="Center"/>
        <ScrollView>
            <VerticalStackLayout BackgroundColor="AliceBlue">
                   <!-- Put here a lot of content to see some scroll -->
            </VerticalStackLayout>
        </ScrollView>
    </VerticalStackLayout>
</Grid>
```
Or just see provided repository link, **MainPage.xaml** contains similar example (Grid.Column="0") and workaround (Grid.Column="1").

### Link to public reproduction project repository

https://github.com/vitalbit/ScrollViewInVerticalStackLayout/tree/master

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 5.1, I was *not* able test on other OS versions.

### Did you find any workaround?

We can put ScrollView inside Grid. In this case it works fine to me. Please see provided repository sample (Grid.Column="1").

**Comment by davidortinau** [comment]
This **is** the designed behavior. `VerticalStackLayout` doesn't size children, and will take up **all** the space needed by its children, even going off screen as it does here. Hence there's no constraint. The inner VStack child measures all the labels and says "I need X height" and the ScrollView says to the parent Layout "how much room do I have, should I scroll my children that need X?" and the parent is a VStack that says "I'll give you all the space you need" and so...no scroll. `Grid` on the other hand (or other column as you have here) gets its height constraint from the parent `Grid` which got it from the `Window`, and thus the `ScrollView` gets a constraint from which to determine it needs to scroll its children.

Grid > VStack > ScrollView > VStack is inefficient and won't get you the results you want. 

Grid > Grid > ScrollView > VStack is still inefficient, but get's the desired result. Do something like that. Optimize by collapsing the Grids into one. I realize this is just a sample.

https://learn.microsoft.com/en-us/dotnet/maui/migration/layouts?view=net-maui-8.0#stacklayout

**Comment by vitalbit** [comment]
Got it, thanks a lot for explanation. Now I know how VerticalStackLayout thinking :)
