### ISSUE TITLE
I think you mean that the ellipses inside the `if`s stand for the code you want executed _only_ on change? Then that implementation would make sense.

### ISSUE THREAD

**Issue by CaLRos15** [dotnet/maui#21833]
I think you mean that the ellipses inside the `if`s stand for the code you want executed _only_ on change? Then that implementation would make sense.
Would the [approach I took](https://github.com/dotnet/maui/issues/10294#issuecomment-1489779147) (clear the dictionary on every navigation) have worked for you too?
An advantage of that approach is that you can omit the change detection code. A disadvantage is that you have to add more property set code. In this case when a _new_ navigation to the _same value_ happens explicitly, the property change is fired, even if the property is changed _to the same value_. This can be an advantage, or a disadvantage depending on your use case.

You'd get something like this:
```csharp
public void ApplyQueryAttributes(IDictionary<string, object> query)
{
  if (query.TryGetValue(nameof(Prop1), out var newProp1)
  {
    Prop1 = newProp1;
  }
  // To clear all route data
  query.Clear();
}
```

_Originally posted by @Ghostbird in https://github.com/dotnet/maui/issues/10294#issuecomment-1606272945_

**Comment by jsuarezruiz** [comment]
Duplicated https://github.com/dotnet/maui/issues/21832
