### ISSUE TITLE
[TotalAV] Debug build works for android maui8 but release doesnt compile because file is being used by another process

### ISSUE THREAD

**Issue by michaelonz** [dotnet/maui#21836]
### Description

When i compile in debug my maui 8 app compiles and runs - when i try and compile from the command line using debug it also works but when i try and compile from command line for release it fails:

`dotnet build -c Release -f net8.0-android -bl REDACTED.csproj
`
I get 9 different errors (all the same error but 9 different xaml files mentioned) 

```
The process cannot access the file 'C:\share\repomike\REDACTED\obj\Release
\net8.0-android\REDACTED.dll' because it is being used by another process. [C:\share\repomike\REDACTED\REDACTED.csproj::TargetFramework=net8.0-android]
```

When i open the msbuild.binlog I get the following also:
Views\HelpPage.xaml The process cannot access the file 'C:\share\repomike\BellMinderProCell\obj\Release\net8.0-android\BellMinderPro.dll' because it is being used by another process. [C:\share\repomike\BellMinderProCell\bellminderpro.csproj]

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Did you find any workaround?

I have no work around - at this stage i cannot release the application.

### Relevant log output

```shell
see above
```

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by jonathanpeppers** [comment]
Can you share a `.binlog` of the failure? https://aka.ms/binlog

From the info above, I can't tell what MSBuild target or task the error is coming from. There should also be a C# stacktrace of some kind?

**Comment by michaelonz** [comment]
@jonathanpeppers do you have an email address i can send it to as there is a lot of information in that file and would rather not have that on public website.

**Comment by michaelonz** [comment]
Hi @jonathanpeppers  - I have emailed the file to you -thx

**Comment by jonathanpeppers** [comment]
This this the XamlCTask, so a general MAUI issue:

![image](https://github.com/dotnet/maui/assets/840039/e749c6bd-68f5-479c-8197-6ffefa6c975b)

(It's complaining about the project's `.dll` file)

@michaelonz do you have some antivirus enabled? Can you exclude the source folder where this project is?

**Comment by michaelonz** [comment]
This solved my @jonathanpeppers - disabling the virus checker for that folder

**Comment by jonathanpeppers** [comment]
@michaelonz which antivirus software caused it?

**Comment by michaelonz** [comment]
@jonathanpeppers - I went into totalav and added a rule to exclude the root of the solution folder and the problem went away.

**Comment by jonathanpeppers** [comment]
I guess this is: https://totalav.com/

**Comment by jfversluis** [comment]
And with that, I think this issue is resolved. Thanks all!
