### ISSUE TITLE
Enable CSS for VerticalStackLayout and HorizontalStackLayout

### ISSUE THREAD

**Issue by bradencohen** [dotnet/maui#21843]
### Description

Wasn't sure whether this was a feature request or issue. Right now -- VerticalStackLayout and HorizontalStackLayout do not respect the same CSS that StackLayout does (such as `-maui-spacing`).

This proposal is to enable that feature set.

I believe this would be an extremely easy addition, check out these comments: https://github.com/dotnet/maui/blob/ccffb28c1d54a1f4fd244af4b460c414ce7fddd9/src/Controls/src/Core/Properties/AssemblyInfo.cs#L153-L157

When I get some free time I'll write a PR.

### Public API Changes

No new API needed, but this should work:

```css
^verticalstacklayout { -maui-spacing: 6; }
```

### Intended Use-Case

To use CSS for all variants of StackLayout.

**Comment by Giviruk** [comment]
Do I need to uncomment a few lines in this issue?

**Comment by bradencohen** [comment]
I don't think `-maui-orientation` makes sense for `HorizontalStackLayout` or `VerticalStackLayout`.

To enable `-maui-spacing` I _think_ you would just need to do something like:
`[assembly: StyleProperty("-maui-spacing", typeof(StackBase), nameof(StackBase.SpacingProperty))]`

**Comment by bradencohen** [comment]
Is this good to be closed?

**Comment by kubaflo** [comment]
Fixed by https://github.com/dotnet/maui/pull/22419
