### ISSUE TITLE
DatePicker not respecting UserAppTheme

### ISSUE THREAD

**Issue by hayer** [dotnet/maui#21858]
### Description

1. `DatePicker` does not respect the `UserAppTheme` and still changes style if user goes to dark theme.

### Steps to Reproduce

1. Set `UserAppTheme = AppTheme.Light`
2. Create a `DatePicker`
3. Start with dark theme
4. `DatePicker` displays using the dark theme instead of the light one.

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

**Comment by Lightnerr** [comment]
Same here on both IOS and Android. When creating a new Maui app and setting the UserAppTheme to Light and my device OS theme to dark, the OS components: datepicker, keyboard, etc. will be displayed in the OS theme, in this case dark.

**Comment by XamlTest** [comment]
Verified on VS 17.10.0 Preview 3.0(8.0.20). Repro on Android 14.0-API34 and iOS 17.2 with below Project:

[21858.zip](https://github.com/dotnet/maui/files/15005086/21858.zip)

![image](https://github.com/dotnet/maui/assets/97647558/101b6f47-2a52-4421-ac7a-4cc7912bd4e9)

**Comment by PureWeen** [comment]
@hayer @Lightnerr @XamlTest does this work on 8.0.7 of MAUI?

**Comment by NiekRossenInfoSupport** [comment]
> @hayer @Lightnerr @XamlTest does this work on 8.0.7 of MAUI?

Im using the following versions, where it is still broken.

Installed Workload Id      Manifest Version       Installation Source
-------------------------------------------------------------------------------
android                    34.0.95/8.0.100        SDK 8.0.200, VS 17.9.34723.18
ios                        17.2.8053/8.0.100      SDK 8.0.200, VS 17.9.34723.18
maui                       8.0.7/8.0.100          SDK 8.0.200
wasm-tools-net7            8.0.4/8.0.100          VS 17.9.34723.18
maccatalyst                17.2.8053/8.0.100      VS 17.9.34723.18
maui-windows               8.0.7/8.0.100          VS 17.9.34723.18
