### ISSUE TITLE
[Bug] Nested childs inside ScrollView not layouting properly

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#2188]
### Description
Adding nested views say Grid/Stacklayout inside ScrollView not layout properly. the Width and Height are not set properly. VerticalOptions and HorizontalOptions are not taken into consideration.

### Steps to Reproduce

> <Grid HeightRequest="80">
        <Grid HorizontalOptions="Fill" VerticalOptions="Fill">
            <ScrollView Orientation="Horizontal" HorizontalOptions="Fill" VerticalOptions="Fill">
                <Grid BackgroundColor="Red" HorizontalOptions="Fill" VerticalOptions="Fill">
                    <Grid ColumnDefinitions="Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto" BackgroundColor="Yellow" HorizontalOptions="Fill" VerticalOptions="Fill">
                        <Label Text="Text" GridLayout.Column="0"/>
                        <Label Text="Text" GridLayout.Column="1"/>
                        <Label Text="Text" GridLayout.Column="2"/>
                        <Label Text="Text" GridLayout.Column="3"/>
                        <Label Text="Text" GridLayout.Column="4"/>
                        <Label Text="Text" GridLayout.Column="5"/>
                        <Label Text="Text" GridLayout.Column="6"/>
                        <Label Text="Text" GridLayout.Column="7"/>
                    </Grid>
                </Grid>
            </ScrollView>
        </Grid>
    </Grid>

### Expected Behavior
The height should be filled to the height of the top level grid.
### Actual Behavior
layout is not proper.

- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/42271912/130247686-93b74a27-780b-465c-a529-dadc87f0b387.png)

### Reproduction Link

[MauiApp9.zip](https://github.com/dotnet/maui/files/7022172/MauiApp9.zip)

**Comment by hartez** [comment]
This is fixed in Preview 10.
