### ISSUE TITLE
[Enhancement] Contributor Documentation

### ISSUE THREAD

**Issue by lukewis** [dotnet/maui#219]
## Summary
I recently cloned this repo and I'm very interested in (at minimum) following along, or possibly contributing.  I looked at https://github.com/dotnet/maui/tree/build/docs, but did not see anything that would help me get started with building the code and running tests.  I'm hoping these contributor docs will be fleshed out sooner rather than later......or possibly I'm just looking in the wrong spot?

**Comment by mrj001** [comment]
Same problem.

I decided to try this:
```
$ ./build.sh
Feeds used:
  /Users/mj/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /Users/mj/Documents/develop/maui/caketools/packages.config are already installed.
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Could not load /Users/mj/Documents/develop/maui/tools/Addins/Cake.Boots.1.0.2.421/lib/netstandard2.0/System.Text.Json.dll (missing Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
Compiling build script...
XamarinFormsVersion: 
ANDROID_RENDERERS: FAST
configuration: 
ANDROID_HOME: 
Team Project: 
buildForVS2017: False
EnvironmentVariable buildForVS2017: [NULL]
Argument buildForVS2017: not set
Release Channel: Stable
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
XCODE 11.4
androidSDK: 
monoSDK: 
macSDK: 
iosSDK: 
Error: One or more errors occurred. (No target specified.
Parameter name: settings)
	No target specified.
Parameter name: settings
```

However, the build failed.

This is the output from "dotnet --info"

> .NET SDK (reflecting any global.json):
>  Version:   5.0.100-preview.8.20362.3
>  Commit:    a5c8f426c2
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /Users/mj/Documents/develop/runtime/.dotnet/sdk/5.0.100-preview.8.20362.3/
> 
> Host (useful for support):
>   Version: 5.0.0-preview.8.20361.2
>   Commit:  f37dd6fc85
> 
> .NET SDKs installed:
>   5.0.100-preview.8.20362.3 [/Users/mj/Documents/develop/runtime/.dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 5.0.0-preview.8.20360.11 [/Users/mj/Documents/develop/runtime/.dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 5.0.0-preview.8.20361.2 [/Users/mj/Documents/develop/runtime/.dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download

**Comment by mrj001** [comment]
Things I've worked out so far.

I've worked around this error
>Could not load /Users/mj/Documents/develop/maui/tools/Addins/Cake.Boots.1.0.2.421/lib/netstandard2.0/System.Text.Json.dll (missing Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)

by copying the missing file from my ~/.nuget cache to the folder in the error message.

One needs to have the Android SDK versions 24 and 29 installed to build the Android portions.  I installed them via Visual Studio for Mac, under Preferences.

There is more information about the "error" that Xcode build requires Xcode [here](https://github.com/nodejs/node-gyp/issues/569).

Re: the error for "no target specified", I found the targets in the build.cake script.  They are found listed as various calls to Task("NameOfTarget").  It appears that there is supposed to be a default target of "Build".  However, I found that this target had to be specified explicitly.  Note that the ./build.cmd on Windows does work with a default target.
```$ ./build.sh --target Build```

At this point, it's producing two types of errors:

1. it is trying (and failing) to compile for WPF and UWP, which won't work on a Mac.
2. errors like this:

>   KeyboardDesignTypeConverter.cs(14,13): error CS0246: The type or namespace name 'StandardValuesCollection' could not be found (are you missing a using directive or an assembly reference?) [/Users/mj/Documents/develop/maui/System.Maui.Core.Design/System.Maui.Core.Design.csproj]
>   ItemsLayoutDesignTypeConverter.cs(19,39): error CS1069: The type name 'ITypeDescriptorContext' could not be found in the namespace 'System.ComponentModel'. This type has been forwarded to assembly 'System, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' Consider adding a reference to that assembly. [/Users/mj/Documents/develop/maui/System.Maui.Core.Design/System.Maui.Core.Design.csproj]

**Comment by lukewis** [comment]
I'm seeing similar behavior.  It seems that there should maybe be separate sln files for building on mac vs windows?  I was trying to build System.Maui.sln using the latest preview of VS Mac.  Haven't yet tried the commandline build like you did.  I'm still exploring the files to see what the various sln files are intended for.

**Comment by PureWeen** [comment]
This project is currently in flux

We'll have updates coming in a few weeks with more functional code and then at a later point Contributor docs

We're not quite ready for contributors
