### ISSUE TITLE
Privacy updates for App Store submissions

### ISSUE THREAD

**Issue by AakashChoubey29** [dotnet/maui#21907]
### Description

Privacy updates for App Store submissions for ios

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by drasticactions** [comment]
I'm assuming you're referring to the [privacy manifest updates](https://learn.microsoft.com/en-us/dotnet/maui/ios/privacy-manifest?view=net-maui-8.0). I've linked the docs on it.

**Comment by AakashChoubey29** [comment]
Yes

**Comment by drasticactions** [comment]
Okay, cool. I'm going to close this issue then, since hopefully the answers your questions on it. If you have specific questions, feel free to post them, although it may be more appropriate to ask in [xamarin-macios](https://github.com/xamarin/xamarin-macios).
