### ISSUE TITLE
[WinUI3] Program has exited with code 2147942405 (0x80070005)

### ISSUE THREAD

**Issue by Vampeyer** [dotnet/maui#21901]
Hello lovely human, thank you for your comment on this issue. Because this issue has been closed for a period of time, please strongly consider opening a new issue linking to this issue instead to ensure better visibility of your comment. Thank you!

_Originally posted by @ghost in https://github.com/dotnet/maui/issues/12581#issuecomment-1426847704_

**Comment by Vampeyer** [comment]
Exactly same problem. The message is
The program '[22700] MauiApp1.exe' has exited with code 2147942405 (0x80070005).


----- This is april of 2024 , and I am running f - ing .NET 9.0 
What in the literal FK.     Who in the h3ll is responsible for releasing this absolute horrible atrocity on mankind , before fixing a simple , child's compilation issue , I mean good god , K & R , did it by hand in the 80,s so we wouldn't have to edure this mess , why in the absolute heck is a multi-million dollar company so completely incompetent towards developers and CONSISTENTLY self - sabotaging.      


Dear Microsoft and Bill Gates ,  
FIX YOUR BUILD ISSUE < ITS NOT ROCKET SCIENCE < STOP SELLING AND BEING TRASH FOR US ALL PLEASE < THX. 

- Ladies , Gentlemen ,and etc.   -  Good day.

**Comment by drasticactions** [comment]
https://github.com/dotnet/maui/issues/12080#issuecomment-1398635826

@Redth laid out, IMO, a through explanation of the issue and, at the time, workarounds for an OS level bug.

> To summarize, there are a few ways this issue can be mitigated:
> 
> Update to the latest [Windows 10 OS January 19](https://support.microsoft.com/en-us/topic/january-19-2023-kb5019275-os-builds-19042-2546-19044-2546-and-19045-2546-preview-8ae1b678-d38c-4249-848d-06b722e7c0ad) update
> Manually install the runtime with the [Windows App SDK Runtime Installer](https://aka.ms/windowsappsdk/1.2/latest/windowsappruntimeinstall-x64.exe)
> Set the project property in your MAUI app project: <PropertyGroup><WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize></PropertyGroup>
> Update to MAUI 7.0.59 when it is released in the coming weeks

Are you running Windows 10? Do you have the newest updates installed?
