### ISSUE TITLE
Broken MSBuild on Android Build .NET MAUI

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/maui#21921]
---
**Issue moved from dotnet/msbuild#10034**
- Please respond to @BrandonHilligenn.

---

_From @BrandonHilligenn on Thursday, April 18, 2024 2:00:12 PM_

### Issue Description

I have been struggling with this exception trying to deploy my app to an android device 

1>MSBUILD : error :     System.Runtime.Remoting.RemotingException: Object '/665a9900_0123_47df_ab79_cf6f79551165/xqergvgyaiklqjxad3przta7_4.rem' has been disconnected or does not exist at the server.

This makes no sense as it never happened before and my device is connected via usb cable.

### Steps to Reproduce

Literally just trying to build to any android device in debug or release mode.

### Expected Behavior

The app builds to the device as always.

### Actual Behavior

I get this error even though the device is connected via usb cable:

1>MSBUILD : error :     System.Runtime.Remoting.RemotingException: Object '/665a9900_0123_47df_ab79_cf6f79551165/xqergvgyaiklqjxad3przta7_4.rem' has been disconnected or does not exist at the server.

**Comment by JanKrivanek** [comment]
---
**Issue moved from dotnet/msbuild#10034**
- Please respond to @baronfel.

---

_From @baronfel on Thursday, April 18, 2024 2:05:58 PM_

Hey @BrandonHilligenn - since the MSBuild team doesn't own the build tasks/targets for building and publishing to Android devices I'm going to transfer this to the dotnet/maui repo. They should be able to help triage the issue faster/with more context, and if there is an issue in the underlying MSBuild engine or the Common targets that live here, we can come back to it.

Thanks for reporting!

_actually_ I lack permissions to transfer this to dotnet/maui, so could you please re-open this there?

**Comment by jfversluis** [comment]
Assuming this has been reported in the right place by now and/or fixed. Thanks!
