### ISSUE TITLE
Seeing error The program '...Program Trace' has exited with code 0 (0x0) 

### ISSUE THREAD

**Issue by rnallani** [dotnet/maui#21924]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: Windows 10 Enterprise

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mattleibow** [comment]
Exit code 0 is usually success.... Can you:

> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Thanks!
