### ISSUE TITLE
AbsoluteLayout for MAUI

### ISSUE THREAD

**Issue by asafgo** [dotnet/maui#2192]
I am using AbsoluteLayout for creating diagrams dynamically using Pan Gesture where it cannot be done with other layouts. So please keep AbsoluteLayout for MAUI.
Example of code [https://github.com/asafgo/PanInAbsoluteLayout](https://github.com/asafgo/PanInAbsoluteLayout)

**Comment by DoubleDBE** [comment]
A simple search would've yielded this https://github.com/dotnet/maui/pull/2136

**Comment by asafgo** [comment]
Sorry I am not so familiar with github so #2136 means that AbsoluteLayout will be included in MAUI?

**Comment by DoubleDBE** [comment]
Yes it seems like it 👌
