### ISSUE TITLE
Action Sheet is displayed behind the popup page

### ISSUE THREAD

**Issue by ESO-ST** [dotnet/maui#21934]
### Description

Action sheet get displayed behind the popup page (Mopups) instead of on top of it when using
`await DisplayActionSheet("Action Sheet Clicked", "Cancel", "Destruction", "Action1", "Action2");` from the popup page.

### Steps to Reproduce

1. open a popup page (in our case we are using Mopups)
2. from the popup page, display the action sheet; `await DisplayActionSheet("Action Sheet Clicked", "Cancel", "Destruction", "Action1", "Action2");`
3. action sheet is displayed behind the popup page.

### Link to public reproduction project repository

https://github.com/ESO-ST/WebViewCrashMidLoad/tree/ActionSheetAlertShowsBehindPage

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

no

**Comment by PureWeen** [comment]
@ESO-ST @jaosnz-rep 

I'm probably not following the steps correctly, but, I'm not quite seeing this issue

![image](https://github.com/dotnet/maui/assets/5375137/f545e427-7942-4e1b-bbc6-0c056a869ab6)

**Comment by ESO-ST** [comment]
On the simulator iPad(10th gen) iOS 17.2

App Starts here
![image](https://github.com/dotnet/maui/assets/140424692/92d6bf10-3c15-436c-9924-a032a259e498)
Press Click me to open the popup page
![image](https://github.com/dotnet/maui/assets/140424692/3d53d98d-fa46-48f8-8517-efb70245e00a)
Press Call Action Sheet to show the actions sheet. This is where the problem happens, the action sheet is shown behind the popup page.
Press Click me to close the popup page, now we can see the action sheet, it showed up behind the popup page
![image](https://github.com/dotnet/maui/assets/140424692/2fc951a5-54a5-4bb9-a0f2-2210c1aca542)
