### ISSUE TITLE
Changing ControlTemplate on Frame dynamically from XAML with DataTrigger does not trigger change on screen

### ISSUE THREAD

**Issue by the-gozo** [dotnet/maui#21947]
### Description

Changing Frame's ControlTemplate with DataTriggers by clicking the Button does not reflect on screen. Looking at Live Visual Tree in VS the the child element of Frame is changing successfully, but Frame keep being empty always. Looked only on Android. 

State 1:
![image](https://github.com/dotnet/maui/assets/48405693/46f2606d-ce5f-4279-8343-a3649f9207db)

State 2:
![image](https://github.com/dotnet/maui/assets/48405693/97738001-4e01-4a82-a7e3-9dc41eab4fb7)

Frame keeps being empty.
![Screenshot_1713537867](https://github.com/dotnet/maui/assets/48405693/b3025b48-6e29-4d37-aa93-d6283ea141c3)

### Steps to Reproduce

1. Create a Flie new MAUI project
2. Add a Frame with  a ResourceDicionary containing two ControlTemplates.
3. Change the Frames ControlTemplate using DataTrigger.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ControlTemplatePoc.MainPage">
    <VerticalStackLayout Padding="30,0"
                         Spacing="25">
        <Button x:Name="CounterBtn"
                Text="Click me"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Fill" />
        <Frame x:Name="frame"
               HeightRequest="500">
            <Frame.Resources>
                <ControlTemplate x:Key="First">
                    <Label Text="First"
                           IsVisible="True" />
                </ControlTemplate>
                <ControlTemplate x:Key="Second">
                    <Label Text="Second"
                           IsVisible="True" />
                </ControlTemplate>
            </Frame.Resources>
            <Frame.Triggers>
                <DataTrigger TargetType="Frame"
                             Binding="{Binding Boolean}"
                             Value="True">
                    <Setter Property="ControlTemplate"
                            Value="{StaticResource First}" />
                </DataTrigger>
                <DataTrigger TargetType="Frame"
                             Binding="{Binding Boolean}"
                             Value="False">
                    <Setter Property="ControlTemplate"
                            Value="{StaticResource Second}" />
                </DataTrigger>
            </Frame.Triggers>
        </Frame>
    </VerticalStackLayout>
</ContentPage>
```

```cs

using CommunityToolkit.Mvvm.ComponentModel;

namespace ControlTemplatePoc
{
    public partial class MainPage : ContentPage
    {
        private bool _boolean;
        public MainPage()
        {
            InitializeComponent();
            BindingContext = this;
        }

        public bool Boolean 
        { 
            get => _boolean; 
            set  { _boolean = value; OnPropertyChanged(); } 
        }

        private void OnCounterClicked(object sender, EventArgs e)
        {
            Boolean = !Boolean;
            var ct = frame.ControlTemplate; //to check if ControlTemplate is being set by xaml
        }
    }

}

```

### Link to public reproduction project repository

https://github.com/the-gozo/ControlTemplatePoc

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Nope.

**Comment by the-gozo** [comment]
Maybe related:
https://github.com/dotnet/maui/issues/4135

**Comment by RoiChen001** [comment]
Can repro this issue at Android platform on the latest 17.10.0 Preview 4(8.0.20).

**Comment by XamlTest** [comment]
Verified on 17.10.0 Preview 4.0(8.0.20), also repro on Windows 11, but not repro on iOS 17.2.

**Comment by PureWeen** [comment]
`Frame` doesn't support having a ControlTemplate property. If you want to use `ControlTemplates` you'll need to use `ContentView`
