### ISSUE TITLE
MAUI Target Android Framework doesn't seem to be used

### ISSUE THREAD

**Issue by lobbo232** [dotnet/maui#21945]
### Description

I have my MAUI project settings set as the below image, targeting Framework 34 with a Minimum Target of 21. However, when I build and upload the bundle to Google Play it says it's targeting 29. I'm not sure where this is coming from.
![image](https://github.com/dotnet/maui/assets/17614851/066bb360-4f4f-4fa9-a814-81a63ca91ff1)

In my Android Manifest I have both Target and Minimum empty so that it would use the project settings.
![image](https://github.com/dotnet/maui/assets/17614851/aa5161f0-e965-445d-bb98-a8333f7aba04)

### Steps to Reproduce

this is occurring in new maui android project in latest visual studio build

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by AlleSchonWeg** [comment]
Hi,
if you have a uses-sdk node in your android manifest then delete this node.

**Comment by AlleSchonWeg** [comment]
Do you remove the node? An empty node is not working. And delete bin/obj folder.

**Comment by lobbo232** [comment]
Yeah, there's no node in manifest, and I deleted bin and obj.

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 4 (8.0.14 & 8.0.20).I can not repro this issue
![image](https://github.com/dotnet/maui/assets/128687574/adc7b4d3-c59b-40fa-869d-a974daac5c8a)

**Comment by lobbo232** [comment]
this is working for me, thanks.
