### ISSUE TITLE
TitleView causes memory leaks 

### ISSUE THREAD

**Issue by GUELIANEBelkacem** [dotnet/maui#21968]
### Description

Adding a TitleView to any page, no matter how simple, causes a catastrophic memory leak.

In the repo i included, you'll find the basic MAUI new project with 3 test pages, one is for a simple page with a TitleView. I included in the repo a GC dump resulting from 1 navigation to/ back from the TitleView Test Page.

In order to limit the scope of this discussion i won't go into the many many many other leaks we have, i'll try to create separate bug reports and app samples whenever possible. But my god how is it possible that one small leak caused by TitleView results in the entire page, context and all child elements living forever in memory??!!! 

Leaks happen, and that's fine as long as some effort goes into compartimentalisation and fault tolerance, it cannot be that 1 small leak in 1 small component could root the entire page and its object tree in memory, this just should not be! This is the real discussion. I would refer anyone insterested into https://github.com/dotnet/maui/discussions/21918#discussion-6524507.

### Steps to Reproduce

1. Clone the test repo and run the project
2. In the main page, click on Goto TitleView Test
3. Navigate back from the test page
4. A GC dump will confirm that the TitleViewTestPage is still in memory and is never cleared
5. Compare the same operation with the EmptyTestPage (which is just the new navigation page "Welcome to .Net MAUI" template) where the page is cleared correctly

### Link to public reproduction project repository

https://github.com/GUELIANEBelkacem/MySuperLeakyApp.git

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 4(8.0.10). Can repro on iOS and Android platforms with sample project.
https://github.com/GUELIANEBelkacem/MySuperLeakyApp.git
