### ISSUE TITLE
[Bug] [HotReload] Removing all or the last view in a layout does not refresh the tree

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#2196]
### Description

If I have a layout with some elements in and the remove them one by one in xaml, they disappear - except for the last one. I can also see this when I delete everything, the LVT does not refresh.

They disappear for the app and a refresh of the tree corrects it.

Not sure if this is our bad code or something missing in the IDE? @drasticactions 

### Steps to Reproduce

```xaml
<Grid>
    <Label Text="One" />
    <Label Text="Two" />
</Grid>
```

Delete both labels and save. The LVT should not update.

### Screenshots

![not-cleaning](https://user-images.githubusercontent.com/1096616/130330051-8bfbc180-ea48-4711-b5e6-167c5af8961c.gif)

**Comment by drasticactions** [comment]
This is a MAUI bug, if you tap into `VisualDiagnostics.VisualTreeChanged`, no events are sent when you remove all of the content from the grid. If there are no events from VisualDiagnostics, LVT can't update.

https://user-images.githubusercontent.com/898335/130337089-ff6ac817-5ee6-4ec4-b5e4-80d9923a0d2b.mp4

```
public partial class App : Application
	{
		public App()
		{
			InitializeComponent();
			VisualDiagnostics.VisualTreeChanged += VisualDiagnostics_VisualTreeChanged;
			MainPage = new MainPage();
		}

		private void VisualDiagnostics_VisualTreeChanged(object sender, VisualTreeChangeEventArgs e)
		{
			try
			{
				var parentSourInfo = VisualDiagnostics.GetXamlSourceInfo(e.Parent);
				var childSourInfo = VisualDiagnostics.GetXamlSourceInfo(e.Child);
				Debug.WriteLine($"VisualTreeChangeEventArgs {e.ChangeType}:" +
					$"{e.Parent}:{parentSourInfo?.SourceUri}:{parentSourInfo?.LineNumber}:{parentSourInfo?.LinePosition}-->" +
					$" {e.Child}:{childSourInfo?.SourceUri}:{childSourInfo?.LineNumber}:{childSourInfo?.LinePosition}");
			}
			catch (Exception ex)
			{
				Debug.WriteLine(ex);
			}
		}
	}
```

**Comment by mattleibow** [comment]
Is there a way to find out what deleting all the items in a layout does? Does it call `Remove`/`RemoveAt` from hot reload or `Clear`?

I think the https://github.com/dotnet/maui/pull/2200 might fix it if it is a clear.

**Comment by mattleibow** [comment]
I just copied the dlls over the workload and then ran an app. Seems to fix it :)
