### ISSUE TITLE
Layout cycle crash on Windows with Button with image inside FlexLayout

### ISSUE THREAD

**Issue by jeremy-visionaid** [dotnet/maui#21970]
### Description

Reopen #21548

### Steps to Reproduce

Reopen #21548

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

Windows

**Comment by jeremy-visionaid** [comment]
@Foda Please reopen #21548

**Comment by schlaman** [comment]
I have the same exception using FlexLayout and it works just fine with 8.0.14 but has the Layout Cycle crash with 8.0.20 (.NET Maui SR4).

This is a pretty severe bug. Will this be addressed quickly?

Thanks,
Craig

**Comment by jeremy-visionaid** [comment]
@schlaman Oh, that's interesting. The original bug pointed out that there were two manifestations of the problem. But it was closed permaturely since only one case (resizing) got fixed.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 4(8.0.20&8.0.14&8.0.10). Can repro on windows platform with sample project. 
https://github.com/molesmoke/MauiTestApp/tree/flexlayout-cycle
8.0.10&8.0.14&8.0.20
![image](https://github.com/dotnet/maui/assets/77434865/d411137c-cfbb-4a4d-9aa0-f8dea3c1f9dc)
8.0.7
![image](https://github.com/dotnet/maui/assets/77434865/4d446781-8a8d-4d5d-b692-335707b376f7)

**Comment by schlaman** [comment]
Awesome that you have it repro'd!

**Comment by jeremy-visionaid** [comment]
I also wrote a unit test to prevent regressions (currently with a Skip directive for Windows since it fails):
https://github.com/dotnet/maui/pull/21651

**Comment by schlaman** [comment]
Totally love the regression prevention!! I appreciate you being on this so quick. I'm about ready to release a major product I've worked on for the last year and really rely on .NET Maui being solid. I totally love what it has become :)

**Comment by PureWeen** [comment]
Can you test with the latest nightly?

https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by mattleibow** [comment]
I wonder if this is fixed by https://github.com/dotnet/maui/pull/21737

**Comment by jeremy-visionaid** [comment]
@PureWeen @mattleibow I can do better than that, the referenced device test is still failing on main (Although it's currently manifesting as a hang, you can still see the layout cycle messages in the debug output)

**Comment by BurkusCat** [comment]
This was something I was going to post myself a few weeks ago but it appeared to go away / not be in the release builds. Now I am getting it consistently and in the release builds in 8.0.20 SR4 (I think I got it in previous versions too).

Any workaround suggestions would be much appreciated!

**Comment by jeremy-visionaid** [comment]
@BurkusCat Looks like @Foda reworked the device test I wrote for it into #21733, so I'm hopeful this will all go away when it gets merged. But setting both MaximumWidthRequest and MaximumHeightRequest on the Buttons does prevent the layout cycle crash for me as a workaround.

**Comment by BurkusCat** [comment]
In MAUI 8.0.60 this appears to be fixed. I was able to remove the workaround and things look a lot nicer now 👍 Thank you
