### ISSUE TITLE
[Bug] LayoutOptions not respected in Hot Reload

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#2197]
### Description

Changing the LayoutOptions (HorizontalOptions and VerticalOptions) does not update the view during a HR session.

If I removed and then add the child view, it renders correctly.

### Screenshots

![layout-options](https://user-images.githubusercontent.com/1096616/130330166-c6fa070f-39b1-425b-bae7-403b7bb83ed2.gif)

**Comment by hartez** [comment]
Fixed for Preview 10.
