### ISSUE TITLE
.NET MAUI > Publish iOS Enterprise App > Wrong Profile

### ISSUE THREAD

**Issue by marco-skizza** [dotnet/maui#21984]
### Description

Dear .NET MAUI Team

I already filed a Visual Studio issue regarding this:
https://developercommunity.visualstudio.com/t/NET-MAUI--Publish-iOS-Enterprise-App-/10643561

I just wanted to ask if I'm doing something wrong - or if others have that problem as well...

### Steps to Reproduce

See issue above

### Link to public reproduction project repository

-

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPad mini 6 with iPadOS 17.3.1

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
This is something that has to do purely with the tooling so opening a ticket there is the right place. Closing this one here, thanks!
