### ISSUE TITLE
Maui app run with Exception Unhandled "System.StackOverflowException: 'Exception of type 'System.StackOverflowException' was thrown.'" when change maui control to 8.0.40-nightly.10537

### ISSUE THREAD

**Issue by ninachen03** [dotnet/maui#21991]
### Description

Maui app run with Exception Unhandled "System.StackOverflowException: 'Exception of type 'System.StackOverflowException' was thrown.'" when change maui control to 8.0.40-nightly.10537

Binlogging: [BuildLoggin.zip](https://github.com/dotnet/maui/files/15071991/BuildLoggin.zip)

### Steps to Reproduce

1. Add maui-nightly "https://pkgs.dev.azure.com/xamarin/public/_packaging/maui-nightly/nuget/v3/index.json" feed to your local Nuget.config file. 
2. Created Maui project or use https://github.com/rachelkang/recipeSearch project.
3. Open .csproject file replace the package version for **Microsoft.Maui.Controls** & **Microsoft.Maui.Controls.Compatibility** to **8.0.40-nightly.10537+sha.b0e562e532-azdo.9451576**
4. Wait for package loading to complete, then run with windows machine, or android device.
![image](https://github.com/dotnet/maui/assets/128687574/42fd7efc-a6a9-421b-bb91-c69588a69965)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

Nightly /8.0.40-nightly.10537+sha.b0e562e532-azdo.9451576 /8.0.40-nightly.10539+sha.be17057ee6-azdo.9453171
### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.20 SR4/ 8.0.40-nightly.10515+sha.d6a3c50c93-azdo.9437127

### Affected platforms

Android, Windows

### Relevant log output

```shell
Expecption Unhandled
System.StackOverflowException
  HResult=0x800703E9
  Message=Exception of type 'System.StackOverflowException' was thrown.

Microsoft.Maui.dll!Microsoft.Maui.EnumerableExtensions.IndexOf<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext>(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext> enumerable, System.Func<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext, bool> predicate)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.EnumerableExtensions.IndexOf<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext>(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext> enumerable, System.Func<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext, bool> predicate)	Unknown
 	[The 1 frame(s) above this were repeated 5655 times]	
 	Microsoft.Maui.Controls.HotReload.Forms.dll!Microsoft.VisualStudio.DesignTools.MauiTap.ElementSelectionManager.RegisterWindow(Microsoft.Maui.IWindow window)	Unknown
 	Microsoft.Maui.Controls.HotReload.Forms.dll!Microsoft.VisualStudio.DesignTools.MauiTap.ElementSelectionManager.Initialize()	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Dispatching.Dispatcher.DispatchImplementation.AnonymousMethod__0()	Unknown
 	Microsoft.InteractiveExperiences.Projection.dll!ABI.Microsoft.UI.Dispatching.DispatcherQueueHandler.Do_Abi_Invoke(nint thisPtr)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
>	MauiApp5.dll!MauiApp5.WinUI.Program.Main(string[] args) Line 31	C#
```

**Comment by baaaaif** [comment]
this should be fixed in the next nightly, see
https://github.com/dotnet/maui/pull/21965

**Comment by PureWeen** [comment]
@drasticactions thoughts? Exception looks like it's from hot reload
