### ISSUE TITLE
Scrollview\CollectionView doesn't scroll

### ISSUE THREAD

**Issue by MattePozzy** [dotnet/maui#22005]
### Description

Hi,
I have a page like this  one:
 
```
<AbsoluteLayout>
    <VerticalStackLayout Background="Green" AbsoluteLayout.LayoutFlags="SizeProportional" AbsoluteLayout.LayoutBounds="0,0,1,1">
        <Grid RowDefinitions="auto,*">
            <Label  
                Grid.Row="0"
                HorizontalTextAlignment="Center" VerticalTextAlignment="Start"
                VerticalOptions="Start"
                FontSize="Large"
                FontAttributes="Bold"
                TextColor="Orange"
                Text="This scrollview doesn't work at all!"
                LineBreakMode="WordWrap" />

            <ScrollView Grid.Row="1">
                <CollectionView ItemsSource="{Binding MyList}">
                    <CollectionView.ItemTemplate>
                        <DataTemplate x:DataType="local:MyClass">
                            <Grid RowDefinitions="100,100" RowSpacing="10">
                                <Label Grid.Row="0" Text="{Binding Name}" Background="LightBlue" HeightRequest="200" />
                                <Label Grid.Row="1" Text="{Binding Surname}" Background="LightCoral" HeightRequest="200" Margin="0,0,0,20" />
                            </Grid>
                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
            </ScrollView>
        </Grid>
    </VerticalStackLayout>
</AbsoluteLayout>

```

I have tried this code on windows, android and ios and the scrollview doesn't scroll.
I have tried to remove the scrollview and leave only the collectionview; same result.

The only way that I have found to make the scrollview to scroll is set its HeightRequest, thing that I cannot do, due to diversity of devices screen size.

Tried also with version 8.0.20, same result.

### Steps to Reproduce

1 - Download the repo
2 - Run the project
3 - Try to scroll

### Link to public reproduction project repository

https://github.com/MattePozzy/scrollviewnotscroll

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
I think this applies to your scenario?

https://github.com/dotnet/maui/issues/21822#issuecomment-2057903531

**Comment by MattePozzy** [comment]
> I think this applies to your scenario?
> 
> [#21822 (comment)](https://github.com/dotnet/maui/issues/21822#issuecomment-2057903531)

Hi thank you for the reply.
I have change the layout like this and now works.

        <AbsoluteLayout>
            <Grid RowDefinitions="auto,*" ColumnDefinitions="*" Background="Green" AbsoluteLayout.LayoutFlags="SizeProportional" AbsoluteLayout.LayoutBounds="0,0,1,1">
                <Label  
                    Grid.Row="0"
                    HorizontalTextAlignment="Center" VerticalTextAlignment="Start"
                    VerticalOptions="Start"
                    FontSize="Large"
                    FontAttributes="Bold"
                    TextColor="Orange"
                    Text="This scrollview doesn't work at all!"
                    LineBreakMode="WordWrap" />

                <ScrollView Grid.Row="1">
                    <CollectionView ItemsSource="{Binding MyList}">
                        <CollectionView.ItemTemplate>
                            <DataTemplate x:DataType="local:MyClass">
                                <Grid RowDefinitions="100,100" RowSpacing="10">
                                    <Label Grid.Row="0" Text="{Binding Name}" Background="LightBlue" HeightRequest="200" />
                                    <Label Grid.Row="1" Text="{Binding Surname}" Background="LightCoral" HeightRequest="200" Margin="0,0,0,20" />
                                </Grid>
                            </DataTemplate>
                        </CollectionView.ItemTemplate>
                    </CollectionView>
                </ScrollView>
            </Grid>
        </AbsoluteLayout>


Thank you!
