### ISSUE TITLE
[Windows] Carousel changes the current position when window is resized

### ISSUE THREAD

**Issue by unombun** [dotnet/maui#22000]
### Description

On Windows while resizing the window, the carousel changes the current position

### Steps to Reproduce

1. (Windows) Add a carousel with some images in it.
2. Resize the window
3. The carousel changes the current position while resizing.
Expected behavior: The carousel should keep the same item displayed while resizing.

### Link to public reproduction project repository

https://github.com/flesarradu/CarouselImageTest

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 4(8.0.20&8.0.14&8.0.7). Can repro on Windows platform with sample project.
![22000](https://github.com/dotnet/maui/assets/77434865/0cf46c89-da98-4cff-9a12-b350464a7261)

**Comment by Zhanglirong-Winnie** [comment]
[https://github.com/dotnet/maui/issues/18559](url)

**Comment by Stedy59** [comment]
@davidortinau
@PureWeen
@samhouts

I brought this bug, and others to your attention over a year ago...

https://github.com/dotnet/maui/issues/18014

I also provided a fix... Why not look at what I provided instead of ignoring it?

**Comment by bronteq** [comment]
Hi @Stedy59, where is the fix that you povided? I didn't find it in the related issues

**Comment by Stedy59** [comment]
> Hi @Stedy59, where is the fix that you povided? I didn't find it in the related issues

The original post is here...
https://github.com/dotnet/maui/issues/16322

It has a link to the code. Ultimately, I ended up authoring my own "CarouselView" for WinUI and Android, which I posted showcased here...
https://github.com/dotnet/maui/discussions/18063
