### ISSUE TITLE
[Bug] Typing in an entry sets the cursor position to 0 after each character

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#2201]
### Description

Each text change (add and remove) the cursor is reset to the start of the text box.

<img src="https://user-images.githubusercontent.com/1096616/130340356-c5fcbc52-f7a3-4a24-ad1a-4952830b5315.gif" width="300" />

**Comment by Chase-William** [comment]
I have downloaded the main maui branch and setup my enviroment to run the source. I have just started debugging; that said, I can immediately see that MapCursorPosition is not called when characters are added & removed from the Entry. Although, the handler is called upon initialization which is expected and is properly ignored in the extensions (for performance and there is no need to calc things when everything is 0). When my Entry.CursorPosition & Entry.SelectionLength PR was merged to main this was not an issue, so something external or new is causing the handler to not be called when needed (characters added / removed). Lastly, it is important to note that the CursorPosition will update the SelectionLength and vise versa if appropriate.

As far as what is responsible for the Handler not being called, I am not sure. I do believe that the handlers are called from Comet if I am not mistaken. As what goes on in Comet or where/how exactly it is being integrated with MAUI, I am not sure, for I haven't done much exploring there (although I mean to soon!). Hopefully this is helpful!
