### ISSUE TITLE
Error "The type 'NSObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'Xamarin.iOS, Version=0.0.0.0"

### ISSUE THREAD

**Issue by navkumar401** [dotnet/maui#22021]
0

In my iOS MAUI project, I'm getting an error "The type 'NSObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'" for references that are referring to a Binding Project that has been upgraded to Microsoft.iOS framework.

I can see that the Binding Project is referencing Microsoft.iOS in the decoded DLL but still, the iOS project is throwing the above error for Xamarin.iOS.

I couldn't find much help online and being stuck with this for a long time, any help would be great.

**Comment by drasticactions** [comment]
CC @rolfbjarne 

Can you make a repro project for how you're setting up your binding projects? my guess is that you're directly referencing the binding project to your app, which I believe won't work. You would either need to package your library into a nuget, or reference the outputted DLL from the project, not the project itself.

**Comment by navkumar401** [comment]
I am referencing the binding project as a DLL only. As you said, it will not work as a project reference.

Another weird thing is that the IntelliSense is not working properly on the binding project. I cannot see what package of iOS (Xamarin.iOS or Microsoft.iOS) the "Foundation" namespace refers to. But since the binding project is referencing Microsoft.iOS physically, I can see the same in the output DLL.

I have uploaded a piece of code from the binding project [here](https://github.com/navkumar401/SampleProjs/tree/main/iOSBindingSample)

I could not get the sample iOS project (I will continue to try) but we're getting the error in question if we use any type (from the binding project dll. ex: UPCA) in the iOS project.

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-macios#20570
