### ISSUE TITLE
[Bug] Setting ScrollbarVisibility in ScrollView is not working

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#2202]
### Description
I'm having a scrollbar with horizontal orientation and set the HorizontalScrollbarVisibility as Never. But still the scrollbar is visible on scrolling. Same is the case for Vertical scrolling.

### Steps to Reproduce

>     <ScrollView Orientation="Horizontal" HorizontalScrollBarVisibility="Never">
        <HorizontalStackLayout>
            <Grid x:Name="MainGrid" RowSpacing="25" 
                  RowDefinitions="Auto,Auto,Auto,Auto,*">
                <Label Text="Hello, World!"
                x:Name="First"
                Grid.Row="0"
                BackgroundColor="Yellow"
                FontSize="32"
                HorizontalOptions="CenterAndExpand" />

                <Label Text="Welcome to .NET Multi-platform App UI"
                Grid.Row="1"
                BackgroundColor="Green"
                x:Name="Second"
                FontSize="16"
                HorizontalOptions="CenterAndExpand" />

                <Label Text="Current count: 0"
                Grid.Row="2"
                FontSize="18"
                HorizontalOptions="Center" />

                <Button Text="Click me"
                Grid.Row="3"
                x:Name="Forth"
                HorizontalOptions="Center" />

            </Grid>
            <Button Text="Reverse Grid Layout"/>
            <Button Text="Update First Row Grid Height to 20"/>
            <Button />
            <Button />
            <Button />
            <Button />
            <Button />
        </HorizontalStackLayout>
    </ScrollView>

### Expected Behavior
Scrollbar should be hidden
### Actual Behavior
Scrollbar is visible

### Reproduction Link

[MauiLayoutTest2.zip](https://github.com/dotnet/maui/files/7026680/MauiLayoutTest2.zip)

**Comment by hartez** [comment]
@PaulAnderson02 Are you experiencing this on Android, iOS, Windows, or all of the above?

**Comment by PaulAnderson02** [comment]
@hartez  Currently facing Android. Not sure about other platforms

**Comment by PaulAnderson02** [comment]
Still the scrollbar is visible on mouse over

**Comment by SuthiYuvaraj** [comment]
I having a scrollbar with vertical orientation and set the VerticalScrollbarVisibilty as Never But still the scrollbar is visible on scrolling
<ScrollView Orientation="Vertical" VerticalScrollBarVisibility="Never">
