### ISSUE TITLE
(iOS) Entrys ignoring textColor-property if text-property set via binding

### ISSUE THREAD

**Issue by LukasHeintze-LabelSoftware** [dotnet/maui#22025]
### Description

Only in iOS:
If the text-property of an Entry is set via binding, the textColor-property doesn't have any effect. Maui always overrides the text color with the default color depending which mode you set on your device (dark / light). 

There were already two other closed issues with this topic, unfortunately without any solution:
https://github.com/dotnet/maui/issues/17818
https://github.com/dotnet/maui/issues/17843

### Steps to Reproduce

Please use my demo project -> https://github.com/LukasHeintze-LabelSoftware/Entry-textColor-issue/tree/main

### Link to public reproduction project repository

https://github.com/LukasHeintze-LabelSoftware/Entry-textColor-issue/tree/main

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Unfortunately not

**Comment by jaosnz-rep** [comment]
Can repro this issue at iOS platform on the latest 17.10 Preview 5 (8.0.21 & 8.0.20 & 8.0.14)

**Comment by kramer-e** [comment]
I have the same issue, but it is fixed in https://github.com/dotnet/maui/pull/20100 (8.0.40-nightly.10587)

**Comment by jsuarezruiz** [comment]
Fixed by https://github.com/dotnet/maui/pull/20100
