### ISSUE TITLE
iOS: Space appears between TitleView and Content when Entry is focused.

### ISSUE THREAD

**Issue by Fraktalchen** [dotnet/maui#22026]
### Description

When Entry is in TitleView and is focused, a gap between TitleView and Content appears. The test sample contains the TitleView and Content with yellow background. The background of the ContentPage itself is blue. Blue areas should not be visible.

Result:
When entry is focused, blue area becomes visible and disappears when the keyboard is closed. Behavior only occurs on iOS

Expected Result:
Layout does not change when Entry is focused.

![Animation](https://github.com/dotnet/maui/assets/167978525/e94a4518-46ee-43a9-a715-df836dc85c74)

`
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestProject.TestPage"
             Title="TestPage" Background="Blue">

    <NavigationPage.TitleView>
        <AbsoluteLayout HeightRequest="50" Margin="0" Background="Yellow">          
            <Entry x:Name="filterEntry" 
                        AbsoluteLayout.LayoutFlags="All" 
                        AbsoluteLayout.LayoutBounds="0,0.5,1,1"
                        Margin="0,0,20,0"
                        Placeholder="test"/>
        </AbsoluteLayout>
    </NavigationPage.TitleView>

    <ContentPage.Content>
        <AbsoluteLayout Background="Yellow">
            <Border></Border>

            <ScrollView AbsoluteLayout.LayoutFlags="All" AbsoluteLayout.LayoutBounds="0,0,1,1" AutomationId="b1105fba-1234-4b4c-97b2-a4117eb5d89c">
                <StackLayout Spacing="10">

                    <Border Margin="0,15,0,0" Padding="15,0,0,15">
                        <StackLayout Spacing="10">
                          
                            
                            <StackLayout Margin="10,5,10,5" Spacing="5" Orientation="Vertical" VerticalOptions="Start">
                                <Label Text="awdfrgaerger" AutomationId="e15e072d-2e82-48c6-a666-d149b3e598f6"/>
                                <Label Text="awdwafwaf" AutomationId="8a7c87cb-1b7a-4e49-b132-c3490222e9ca"/>
                            </StackLayout>

                            
                            <StackLayout Margin="10,5,10,5" Spacing="5" Orientation="Vertical" VerticalOptions="Start">
                                <Label Text="aergaergeargaerg" AutomationId="e15e072d-2e82-48c6-a666-d149b3e598f6"/>
                                <Label Text="awfwaadawd"  MaxLines="10" AutomationId="8a7c87cb-1b7a-4e49-b132-c3490222e9ca"/>
                            </StackLayout>

                            
                            <StackLayout Margin="10,5,10,5" Spacing="5" Orientation="Vertical" VerticalOptions="Start">
                                <Label Text="aergeargeargeargerage" AutomationId="abd62b95-bcee-4beb-ab37-4b11fff56af8"/>
                                <Label Text="awawdwadwadwadwa"  AutomationId="6803f73d-6a75-49b8-89c6-45b84ffe1b51"/>
                            </StackLayout>

                        </StackLayout>
                    </Border>
                </StackLayout>
            </ScrollView>
        </AbsoluteLayout>
    </ContentPage.Content>
</ContentPage>`

Test Project to reproduce this issue.
[TestProject.zip](https://github.com/dotnet/maui/files/15092988/TestProject.zip)

### Steps to Reproduce

1. Create Title with TitleView
2. Add Entry in TitleView
3. Fill ContentView with any content
4. Deploy on iOS
5. Focus Entry.
6. Gap between TitleView and ContentView appears

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by tj-devel709** [comment]
Hi @Fraktalchen, this seems to be the same issue as https://github.com/dotnet/maui/issues/21630 which should be fixed in SR4 by this PR https://github.com/dotnet/maui/pull/21806. Thanks, and I will close this for now!
