### ISSUE TITLE
iOS : Shell FlyoutItem Tab Selected Icon Color not changing if using Font icons

### ISSUE THREAD

**Issue by akhilvswoodplc** [dotnet/maui#22032]
### Description

Shell FlyoutItem Tab Selected Icon Color not changing if using Font image source in iOS.
Only the Title color is changing 

### Steps to Reproduce

Shell FlyoutItem Tab Selected Icon Color not changing if using Font image source in iOS.
Only the Title color is changing 

### Link to public reproduction project repository

na

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS All versions

### Did you find any workaround?

No

### Relevant log output

```shell
na
```

**Comment by jaosnz-rep** [comment]
Can repro this issue at iOS platform on the latest 17.10 Preview 5(8.0.21&8.0.7).
We found the following known bugs similar to this issue, which can be used for reference.
[(Un)SelectedTabColor do not work for TabbedPage icons (FontImageSource) on iOS · Issue #12250 · dotnet/maui (github.com)](https://github.com/dotnet/maui/issues/12250)
[Font Icons in Shell Tabs not showing in iOS · Issue #20866 · dotnet/maui (github.com)](https://github.com/dotnet/maui/issues/20866)

**Comment by PureWeen** [comment]
@jaosnz-rep can you attach the project you used to repro this?

**Comment by jaosnz-rep** [comment]
> @jaosnz-rep can you attach the project you used to repro this?

The project I use is this https://github.com/tranb3r/Issues/tree/main/MauiAppTabbedPageIconColor
