### ISSUE TITLE
Memory Leak in Style with Trigger

### ISSUE THREAD

**Issue by markmccaigue** [dotnet/maui#22036]
### Description

A memory leak occurs when an implicit style with an associated trigger is used.

Please see the linked repository for a reproduction, where I have created a rudimentary test harness to illustrate the issue.

### Steps to Reproduce

1. Run the sample at the linked repository
2. Use the navigate button to navigate to a new page, and press the back arrow to go back to the original page. Repeat this a number of times.
3. Back on the main page, use the GC button to trigger garbage collections by clicking a few times.
4. Observe the memory usage does not return to baseline.
5. Remove the style from the App constructor and repeat the steps above
6. Observe the memory returns to baseline

![Simulator Screenshot - iPX15 4 - 2024-04-24 at 16 43 33](https://github.com/dotnet/maui/assets/736783/15c0be35-82a1-4759-a0b3-f0984ee2330d)
_Above: Image with style present_

![Simulator Screenshot - iPX15 4 - 2024-04-24 at 16 42 31](https://github.com/dotnet/maui/assets/736783/f9857aa2-cb35-4397-ae3b-6ca8bd4ccd05)
_Above: Image with style removed_

### Link to public reproduction project repository

https://github.com/markmccaigue/mauitriggerleaktest

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 5(8.0.20). Can repro on iOS and android platforms with sample project.
