### ISSUE TITLE
WebView needs Width and Height for Filling screen

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2203]
Hi,

[https://social.msdn.microsoft.com/Forums/en-US/0519256c-e968-4459-aac8-06b74d8d68e7/webview-not-filling-the-screen-in-xamarin-formswhy-is-there-a-gap-at-the-top?forum=xamarinforms](https://social.msdn.microsoft.com/Forums/en-US/0519256c-e968-4459-aac8-06b74d8d68e7/webview-not-filling-the-screen-in-xamarin-formswhy-is-there-a-gap-at-the-top?forum=xamarinforms)

Why do you need to set the WidthRequest and HeightRequest if I already mentioned HorizontalOptions. and VerticalOptions to FillAndExpand?

**Comment by wenwen60** [comment]
Not repro on Android 12 with VS2022 17.2.0 Preview 2.0 [32215.517.main].
