### ISSUE TITLE
ListView not visible in Android

### ISSUE THREAD

**Issue by gktval** [dotnet/maui#22037]
### Description

List View is not visible on Android devices. It does display in Windows--not sure about iOS.

### Steps to Reproduce

1. Open the repository attached
2. Run the program in Android
3. Notice that the list view content in the frame is empty.
4. If the frame is remove, it appears

### Link to public reproduction project repository

https://github.com/gktval/MauiFrameBug

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

Android

### Affected platform versions

Android 32+

### Did you find any workaround?

No

**Comment by reddvid** [comment]
I believe AbsoluteLayout fails to compute the sizing of the ListView without specifying (minimum) LayoutBounds. Also, this UI code is not recommendable.

**Comment by gktval** [comment]
You are right. It is because of the absolute layout. The UI here is part of a popup in production code. Just an example.

**Comment by gktval** [comment]
Apparently I had forgotten about this aver 6 months.
https://github.com/dotnet/maui/issues/18377
