### ISSUE TITLE
[Bug] ICommandMapper and IPropertyMapper usage is very inconsistent

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#2204]
### Description

Just like when we created IPropertyMapper for better inheritance.

And, should we be using IPropertyMapper in all the handlers, not just Label

**Comment by PureWeen** [comment]
@mattleibow 

> should we be using IPropertyMapper in all the handlers, not just Label

Yes! I ran into this issue when customizing button mapper inside controls
