### ISSUE TITLE
[Bug][Template] Move splash screen to Resources\Images folder of the template

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#2208]
### Description

The template currently references the app splash screen in the **Resources** folder of the project:

https://github.com/dotnet/maui/blob/9dc69b46e903eb87f5ebb43689c572de71b3a987/src/Templates/src/templates/maui-mobile/MauiApp1/MauiApp1.csproj#L35

Can the template be updated so that the splash screen is in the **Resources\Images** folder, and the .csproj updated accordingly? It's a nicer story to tell in the docs.

**Comment by Eilon** [comment]
Still there: https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj#L37
