### ISSUE TITLE
[Bug] Mark one of the Geocoding APIs as obsolete

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#2209]
### Description

Essentials has a geocoding API (https://github.com/dotnet/maui/tree/main/src/Essentials/src/Geocoding). Maui.Maps also has a geocoding API (https://github.com/dotnet/maui/blob/main/src/Controls/Maps/src/Geocoder.cs). Can one be marked as `Obsolete` by GA?

**Comment by mattleibow** [comment]
I do not believe Maps is part of GA, but removing that API is what will happen.

**Comment by jfversluis** [comment]
Which one should we obsolete? I guess Maps is more logical place?

**Comment by davidbritch** [comment]
Yes, obsoleting in Maps makes sense to me.

**Comment by mattleibow** [comment]
@jfversluis  @rmarinho this is relevant for the Maps work you are doing.

**Comment by rmarinho** [comment]
But we never shpipped that API on MAUI right? can we just remove it ?

**Comment by jfversluis** [comment]
I think this has been resolved!
