### ISSUE TITLE
Vertical Scrolling in ScrollView Orientation = "BOTH" is not working [Android]

### ISSUE THREAD

**Issue by KamalaKannan-SF4101** [dotnet/maui#22133]
### Description

When setting the scrollview orientation to both, I am unable to scroll vertically.

### Steps to Reproduce

1. Clone the given Repository.
2.  Run the sample in Android.
3.  Try to scroll in vertical direction.
4.  It need to be scroll vertically 

### Link to public reproduction project repository

https://github.com/KamalaKannan-SF4101/VerticalScrolling

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.10 Preview 5 (8.0.21&8.0.3). Can not repro on android platform with sample project.
