### ISSUE TITLE
[iOS] Splash and app icon doesn't work on a real device

### ISSUE THREAD

**Issue by Blinchik91** [dotnet/maui#22136]
### Description

The given splash and app icon doesn't work on a real iOS device (in my case iPhone 12), it always shows the .NET splash and icon.
I found similar problems but none of the suggested solutions work. (Clearing data, restart, renaming resources etc.)

It works without any problems with the iOS emulator.

### Steps to Reproduce

1. Deploy the App on a iOS device
2. .NET App Icon is set (Should be a goat)
3. .NET Splash is set (Should be a goat)

### Link to public reproduction project repository

https://github.com/Blinchik91/MauiApp1

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.4.1

### Did you find any workaround?

No

**Comment by ewerspej** [comment]
Please include a screenshot to show what the problem looks like.

Did you simply replace the files in their location? 

Have you tried renaming the files followed by a clean build?

**Comment by asi-evin** [comment]
I cloned your repo and built your app in debug to a remote iOS device and I see the goat. I'm going to make the bold assumption that you're not pushing to a local iOS device, as that will not use your icon.

Check your "obj\Debug\net8.0-ios\ios-arm64\resizetizer" directory and see if your expected splash and icons are there. Delete the obj folder if they are not correct before you rebuild.

You can also try uninstalling the app AND restarting your iOS device, I think I remember a long time ago I had an issue with my icon not changing and that fixed it.

**Comment by jfversluis** [comment]
Are you using [Hot Restart](https://learn.microsoft.com/previous-versions/xamarin/xamarin-forms/deploy-test/hot-restart)? In other words, are you deploying to a physical iOS device from Windows without a Mac involved? If yes, this is a known limitation.

Could you please confirm?
