### ISSUE TITLE
[android] Identified crash in toolbar extensions when using a custom image source

### ISSUE THREAD

**Issue by softlion** [dotnet/maui#22138]
### Description

On Android, when using a custom image source as the source for an IconImageSource of a Toolbar item, and that source does not implement GetConstantState, maui crashes:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                     xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                     xmlns:svg="https://vapolia.eu/svg">
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="{x:Static appresource:AppResources.Home_Filter}" 
                     Command="{Binding OpenFilterViewCommand}" 
                     Order="Primary"
                     IconImageSource="{svg:Svg my_icon.svg}" />
    </ContentPage.ToolbarItems>
```

### Steps to Reproduce

The issue is caused by the code in 
https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs

which ignores the null value returned by `baseDrawable.GetConstantState()` as not all custom drawable implements that caching feature.

![image](https://github.com/dotnet/maui/assets/190756/e6ce2f40-ea2d-4fae-8ba0-b8c0a9d0e031)

Instead, it should not ignore the null value, and provides an alternate implementation when GetConstantState() returns null

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android all versions

### Did you find any workaround?

no

### Relevant log output

```shell
04-30 10:56:46.028 I/DOTNET  (19040): 97|2024-04-30T10:56:46.0278601+00:00|ERROR|1|IImageSource|Unexpected exception in LoadImage. --> System.NullReferenceException: Object reference not set to an instance of an object.
04-30 10:56:46.028 I/DOTNET  (19040):    at Microsoft.Maui.Controls.Platform.ToolbarExtensions.<>c__DisplayClass13_0.<UpdateMenuItemIcon>b__0(IImageSourceServiceResult`1 result) in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\Extensions\ToolbarExtensions.cs:line 366
04-30 10:56:46.028 I/DOTNET  (19040):    at Microsoft.Maui.ImageSourceExtensions.LoadImageResult(Task`1 task, Action`1 finished) in D:\a\_work\1\s\src\Core\src\ImageSources\ImageSourceExtensions.cs:line 32
04-30 10:56:46.028 I/DOTNET  (19040):    at Microsoft.Maui.TaskExtensions.FireAndForget(Task task, Action`1 errorCallback) in D:\a\_work\1\s\src\Core\src\TaskExtensions.cs:line 36
```
```

**Comment by softlion** [comment]
The repro is in the comment. Along with the line where the bug is.

**Comment by PureWeen** [comment]
@softlion can you attach a full project please?

**Comment by softlion** [comment]
Man, the issue is so obvious - I pointed the exact line in the maui source code - that i won't spend 1 more hour on it.

The maui code voluntarily ignores the null return value with an exclamation mark. If it can return null, why ignore it ?

I'm the publisher of a custom component that creates a full custom imagesource with a custom android Drawable.  
I already updated my component so it now implements that optional Drawable override, So that issue is worked around.

**Comment by PureWeen** [comment]
> So that issue is worked around.
Good to hear!

**Comment by softlion** [comment]
> > So that issue is worked around.
> 
> Good to hear!

Do you have a financial bonus when you close an issue ?

I would like to understand why you dont add a `if( xxxx is not null )` in the source code instead of leaving that bug there and closing that issue ?
