### ISSUE TITLE
[Bug] Image sizing is not working as expected

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#2213]
### Description

Seems the Images are not respecting the bounds they should be layout on. The image will be bigger than it's bounds

### Steps to Reproduce

1. Pull https://github.com/dotnet/maui/tree/collectionview-handler-samples
2. Check the DataTemplate sample `TemplateCodeCollectionViewGallery`
3 the image overflows to go above the label

![image](https://user-images.githubusercontent.com/1235097/130462744-08da31a5-fdcd-4456-b519-0a963fb022d5.png)

4. Go to ExampleTemplates.PhotoTemplate(); and  remove `WidthRequest = 100,` see how the image behaves

![image](https://user-images.githubusercontent.com/1235097/130463328-dc5948ce-ab9b-40a2-8818-3f7a1f30c3bf.png)
 

### Expected Behavior

If there's no image size i expect the image to be shrinked to 43 in height ( 50 less the margins)

### Actual Behavior
Image sees to just overflow the height it should.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

above

### Reproduction Link

https://github.com/dotnet/maui/tree/collectionview-handler-samples

**Comment by hartez** [comment]
The repro is in the CollectionView/CarouselView test pages in the gallery app.

**Comment by VincentBu** [comment]
In 32506.368.main, I used code from #2741. If there is anything doesn't make sense, please point it out. Here is the screenshot:
![image](https://user-images.githubusercontent.com/44959937/167240297-2d99cca8-6c4b-4db3-84e6-7b55f9d67f84.png)

Feel free to reopen the issue if it occurs again.
