### ISSUE TITLE
CollectionView scrolling not working when using SwipeView (only in iOS)

### ISSUE THREAD

**Issue by divyesh008** [dotnet/maui#22165]
### Description

The CollectionView scrolling gets freez/hang when using SwipeView control, and it appears to affect iOS devices exclusively. 

The sensitivity of the SwipeView in iOS is notable, as it tends to open automatically when scrolling. This behavior makes it exceedingly challenging to perform a purely vertical scroll, as even the slightest horizontal movement triggers the swipe menu to open. 

This might sound like a small thing, but it completely breaks the experience as almost every scroll opens the swipe menu plus it hangs the CollectionView scroll. 

Tried to use Simultaneous pan gesture recognition as mentioned here, but it does not resolve issue:
https://learn.microsoft.com/en-us/dotnet/maui/ios/platform-specifics/application-pan-gesture?view=net-maui-8.0

**Testing Procedure**
- Launch the app from the reproduction project.
- Start scrolling the list vertically.
- Notice that the Swipe view opens automatically to some extent due to its high sensitivity.
- The screen becomes unresponsive, causing scrolling to halt.
- Swipe right to close the Swipe view.
- Subsequent scrolling may still encounter interruptions, with the scrolling halting intermittently when moving up and down.

**Screen recording**
https://github.com/dotnet/maui/assets/10617244/40fe7f7f-bcab-4619-95ae-bab6284f6871

### Steps to Reproduce

1. You start scrolling a view vertically
2. Due to the sensitivity of the swipe view it opens on the any item (from right in my case)
3. You continue scrolling normally
4. The swipe view either disappears at this stage or stays visible
5. No matter if it disappears or not, the actual item stays on the left side, as if the swipe view item was visible
6. The UI may lock up

### Link to public reproduction project repository

https://github.com/divyesh008/CollectionWithSwipeView_Bug.git

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2 

### Did you find any workaround?

For the work around I have to use Bindable Layout.

**Comment by PureWeen** [comment]
Duplicate of #16856
