### ISSUE TITLE
[Bug] TabbedPage->SelectedTabColor no work

### ISSUE THREAD

**Issue by Coloryr** [dotnet/maui#2217]
### Description
code:
```
<TabbedPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage"
             xmlns:local="clr-namespace:MauiApp1;assembly=MauiApp1"
             BackgroundColor="{DynamicResource SecondaryColor}"
             UnselectedTabColor ="Bisque"
             BarTextColor="Black"
             SelectedTabColor="AliceBlue">
    <local:NewPage1 />
    <local:NewPage2 />
</TabbedPage>
```
### Steps to Reproduce

1. build
2. run

### Basic Information

- Version with issue:6.0.100-p7
- IDE:VS2022 P3.1
- Platform Target Frameworks: 
  - Android: 30
- Nuget Packages:6.0.100-preview.7.1345+sha.8665ea184-azdo.5075445
- Affected Devices:Pixel_4_API_30

### Screenshots

![image](https://user-images.githubusercontent.com/26276037/130498575-3298b6b0-a08c-4a2a-b0c8-fcdfc6aa6749.png)

### Workaround

```
– android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 30.0.100-preview.7.110) installed.
  – ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-preview.7.230) installed.
  – maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-preview.7.230) installed.
  – tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-preview.7.230) installed.
  – macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-preview.7.230) installed.
  – maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-preview.7.1345) installed.
  – wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-preview.7.21377.19) installed.
  – microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-preview.7.21377.2)
```

**Comment by XamlTest** [comment]
@Coloryr If you delete BarTextColor="Black" code, the UnselectedTabColor and SelectedTabColor will work.
![image](https://user-images.githubusercontent.com/97647558/157828888-80303984-a52c-4751-862a-4a1ec04ff250.png)

**Comment by XamlTest** [comment]
Verified this with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main]. Not repro on Android with Project:
[2217.zip](https://github.com/dotnet/maui/files/8230272/2217.zip)
