### ISSUE TITLE
[Android] Large loading time of a Page with CollectionView using template selector

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#22189]
### Description

Large loading time of a Page with CollectionView using template selector with 100 items (around 5-7s).

![perf-selector-vertical](https://github.com/dotnet/maui/assets/6755973/efd73feb-7326-4d6d-832c-cf5ac17cd9d3)

### Steps to Reproduce

1. Sync or download https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CollectionViewDemos
2. Launch the App on Android.
3. Navigate to the section Vertical list Data template selector.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CollectionViewDemos

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by PureWeen** [comment]
@jsuarezruiz it looks like this sample has the CV nested in a SL

https://github.com/dotnet/maui-samples/blob/main/8.0/UserInterface/Views/CollectionViewDemos/CollectionViewDemos/Views/Layout/VerticalListDataTemplateSelectorPage.xaml#L70-L73

That's going to cause the entire CV to renderer since an SL allows for infinite spacing. Can you try changing this to a grid and see what happens?

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz it looks like this sample has the CV nested in a SL
> 
> https://github.com/dotnet/maui-samples/blob/main/8.0/UserInterface/Views/CollectionViewDemos/CollectionViewDemos/Views/Layout/VerticalListDataTemplateSelectorPage.xaml#L70-L73
> 
> That's going to cause the entire CV to renderer since an SL allows for infinite spacing. Can you try changing this to a grid and see what happens?

Right. The Grid fixed the issue.

**Comment by mohachouch** [comment]
@jsuarezruiz @PureWeen I am surprised that this bug has been closed. A large number of projects use a CollectionView in a StackLayout. It worked perfectly on Xamarin Forms. From my point of view, it's a bug
