### ISSUE TITLE
[Android] Deleting an item from the CollectionView takes a long time

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#22190]
### Description

Deleting an item from the CollectionView takes a long time (5-7s).
![remove-perf](https://github.com/dotnet/maui/assets/6755973/772ebcb3-f090-4a75-b838-249b0ef44971)

### Steps to Reproduce

1. Sync or download Sync or download https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CollectionViewDemos
2. Launch the App on Android.
3. Navigate to the sample Context menu items (the last one).
4. Swipe and remove any item.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CollectionViewDemos

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by PureWeen** [comment]
@jsuarezruiz I think this is the same issue

https://github.com/dotnet/maui-samples/issues/467
