### ISSUE TITLE
[Windows] FlexLayout crashes when using a custom display scale factor value (regression)

### ISSUE THREAD

**Issue by BurkusCat** [dotnet/maui#22209]
### Description

When using a custom display scale factor in Windows, FlexLayout appears to throw an exception.
![image](https://github.com/dotnet/maui/assets/7528322/1d32753d-91e0-4ca2-8447-3334afb947aa)

The exception is:
`{Microsoft.UI.Xaml.UnhandledExceptionEventArgs} Layout cycle detected.  Layout could not complete.`

This a regression I think. 8.0.7 didn't appear to have the crash. The latest nightly (8.0.40-nightly.10602) does not resolve the issue.

### Steps to Reproduce

1. Create a new MAUI app
2. Put a `ScrollView` on the page with a `VerticalStackLayout` inside
3. Put a `FlexLayout` inside that
4. Set a custom display scaling factor (110% or 170% were two random ones I tried)
5. In case its relevant, set screen resolution to 5120x1440
6. Start app on Windows

Expected
App starts

Actual
App crashes on startup

### Link to public reproduction project repository

https://github.com/BurkusCat/FlexLayoutDisplayScaleCrash

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

Windows

### Affected platform versions

Windows 23H2 22631.3527

### Did you find any workaround?

No

**Comment by BurkusCat** [comment]
> Hi I'm an AI powered bot that finds similar issues based off the issue title.

I think there are a lot of related FlexLayout issues (I've experienced #21970). This seems like a unique issue that on FlexLayouts that would otherwise work, custom display scaling causes a crash with even a simple layout.

**Comment by jaosnz-rep** [comment]
The error can be reproduced on the latest 8.0.21 and 8.0.40-nightly.10602 versions, but verified on 8.0.10 that it works fine.

**Comment by jeremy-visionaid** [comment]
Oh yup, I just hit this one too, and sadly setting the maximum width/height (like for #21970) is ineffective as a workaround.

**Comment by jeremy-visionaid** [comment]
Eek, it's not just custom display factors. It seems to be machine specific, but it can also happen on the device's default/recommended scale factor (e.g. 200% on a 2560x1600 laptop). It also occurs at 175% on Surface Pro 7. So it turns out this is quite common in the field - more than 50% of devices are affected on my app's canary release channel.

**Comment by BurkusCat** [comment]
That's quite interesting! 😯 I tested several standard scale factors and it worked fine for me. I just assumed it was only custom! I only tested on one monitor.

**Comment by BurkusCat** [comment]
8.0.60 appears to resolve this issue thank you :)
