### ISSUE TITLE
ListViewItem doesn't exists any more

### ISSUE THREAD

**Issue by Mafyou** [dotnet/maui#22202]
### Description

Just put a ListView in your Stacklayout and try to get an item. Precisely. The object which identify the ListViewItem doesn't seems to exist any more in Maui !

### Public API Changes

ListViewItem is back();

### Intended Use-Case

Focus or whatsoever a ListViewItem in a ListView.

**Comment by jfversluis** [comment]
I'm sorry I don't understand, a `ListViewItem` has never been something that is provided with Xamarin.Forms.

Doing a quick search it seems that you might mean something that is built into [SyncFusion](https://help.syncfusion.com/cr/xamarin/Syncfusion.ListView.XForms.ListViewItem.html). If they have removed something that you need, you probably want to contact them.

**Comment by Mafyou** [comment]
@jfversluis, I totally understand your point but:
I want just the "ListViewItem" object to do stuff that are handle from a ListView Items Object. As Focus() Or Index.
It was provided by Xamarin.

**Comment by jfversluis** [comment]
As far as I know and can tell there never has been a `ListViewItem` type in the Xamarin.Forms codebase. There is a type from SyncFusion or from UWP. We have removed very little in the transition from Xamarin.Forms to .NET MAUI, so I'm afraid I don't know what you are talking about here 😄

**Comment by Mafyou** [comment]
The property "SelectedItem" is bound to your custom C# class.
The Item, in the ListView contains your custom C# class.
The property "SelectedItem" is the item ? => Yes, of your C# Class and not the behavior which has ListViewItem normally.
=> The problem still is to focus one item for example in Maui.
