### ISSUE TITLE
Update .NET MAUI Blazor hybrid template 

### ISSUE THREAD

**Issue by BethMassi** [dotnet/maui#22205]
### Description

We need to update the .NET MAUI Blazor hybrid template to incorporate the same patterns in Blazor. We'll want to have "include sample code" as an option and make sure the files and folders are consistent with Blazor web template sample code. 

### Public API Changes

None

### Intended Use-Case

Creating new .NET MAUI Blazor hybrid project with or without sample code.

**Comment by BethMassi** [comment]
Also clean up the template by removing the unnecessary favicon.ico https://github.com/dotnet/maui/issues/16542

**Comment by BethMassi** [comment]
https://github.com/dotnet/maui/issues/9126

**Comment by Eilon** [comment]
This is covered by the linked issues, so closing this as dupe.
