### ISSUE TITLE
Calling UseMauiMaps() in the MAUI startup pipeline in a multi-platform targeted App throws an exception

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#22214]
### Description

Calling `UseMauiMaps()` in the MAUI startup pipeline in a multi-platform targeted App throws an exception with the below message.

`.NET MAUI Maps is currently not implemented for Windows. For more information, please see: https://aka.ms/maui-maps-no-windows`

The same call works fine on .NET 7 and throws exception on .NET 8 onwards

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Add a reference to Maps package
3. Chain the `UseMauiMaps()` method in the `MauiProgram.cs`
4. Build and run the app
5. Repeat the step on .NET 7, it works fine

### Link to public reproduction project repository

https://github.com/egvijayanand/maui-issue-22214

### Version with bug

On .NET 8 and above.

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

### Affected platform versions

Common behavior

### Did you find any workaround?

Have to wrap the call in a compiler directive so that this piece of code is excluded for the Windows platform to avoid the exception.

```cs
#if !WINDOWS
    .UseMauiMaps()
#endif
```

### Relevant log output

```shell
.NET MAUI Maps is currently not implemented for Windows. For more information, please see: https://aka.ms/maui-maps-no-windows
```

**Comment by jfversluis** [comment]
This is expected to provide a bit more context around why Windows is not working and where to find more information. Unfortunately there is not great solution here until the official Maps implementation for Windows is done which is tracked here #20356

Until then, the workaround is the correct way to deal with it.

**Comment by egvijayanand** [comment]
The question here is how it worked in .NET 7 and throws a runtime error when migrated to .NET 8.
