### ISSUE TITLE
Using WebSockets     Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by solrac3f** [dotnet/maui#22221]
### Description

Using the following code in a .NET Form app. A Websocket connection to a Server is established and the commands are send correctly and received correctly on the server side.

Using the same code in a .NET MAUI app a Exception Error is  thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll

```c#
        private async void BtnOn_Clicked(object sender, EventArgs e)
        {
            await SendCommand("O");
        }

        private async void BtnOff_Clicked(object sender, EventArgs e)
        {
            await SendCommand("F");
        }

        private async Task SendCommand(string command)
        {
            ClientWebSocket socket = new ClientWebSocket();

            try
            {
                await socket.ConnectAsync(new Uri("ws://192.168.0.2:80/command"), CancellationToken.None);

                byte[] buffer = Encoding.UTF8.GetBytes(command);
                await socket.SendAsync(new ArraySegment<byte>(buffer), WebSocketMessageType.Text, true, CancellationToken.None);

                Trace.WriteLine("Incoming message: " + command);

                // Receive response if needed
                var responseBuffer = new byte[1024];
                var response = await socket.ReceiveAsync(new ArraySegment<byte>(responseBuffer), CancellationToken.None);
                var responseMessage = Encoding.UTF8.GetString(responseBuffer, 0, response.Count);

            }
            catch (Exception ex)
            {
                await DisplayAlert("Error", $"Error: {ex.Message}", "OK");
            }
            finally
            {
                if (socket.State == WebSocketState.Open || socket.State == WebSocketState.Connecting)
                    await socket.CloseAsync(WebSocketCloseStatus.NormalClosure, "Closed by the client", CancellationToken.None);

                socket.Dispose();
            }
        }
```

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by solrac3f** [comment]
Yes, with WinForms app it works. I will try a WinUI app (without MAUI).

**Comment by jfversluis** [comment]
Please let us know the result!

That WinForms app does that run on the same .NET version? .NET 8? Or is that still .NET Framework? Can you maybe provide some more version information?

**Comment by solrac3f** [comment]
Yes the WinForms app runs on .NET 8. I created a WinUI app without MAUI. Like in the WinForms app it is working.

Follows the code for the WinUI app: 

`
using System;
using System.Diagnostics;
using System.Net.WebSockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;

// The Blank Page item template is documented at https://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

namespace App2
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            await SendCommand("O");
        }

        private async void Button_Click_1(object sender, RoutedEventArgs e)
        {
            await SendCommand("F");
        }

        private async Task SendCommand(string command)
        {
            ClientWebSocket socket = new ClientWebSocket();

            try
            {
                await socket.ConnectAsync(new Uri("ws://192.168.0.2:80/command"), CancellationToken.None);

                byte[] buffer = Encoding.UTF8.GetBytes(command);
                await socket.SendAsync(new ArraySegment<byte>(buffer), WebSocketMessageType.Text, true, CancellationToken.None);

                Trace.WriteLine("Incoming message: " + command);

                // Receive response if needed
                var responseBuffer = new byte[1024];
                var response = await socket.ReceiveAsync(new ArraySegment<byte>(responseBuffer), CancellationToken.None);
                var responseMessage = Encoding.UTF8.GetString(responseBuffer, 0, response.Count);

            }
            catch (Exception ex)
            {

                Console.WriteLine("Error", $"Error: {ex.Message}", "OK");
            }
            finally
            {
                if (socket.State == WebSocketState.Open || socket.State == WebSocketState.Connecting)
                    await socket.CloseAsync(WebSocketCloseStatus.NormalClosure, "Closed by the client", CancellationToken.None);

                socket.Dispose();
            }
        }
    }
}

`

**Comment by Eilon** [comment]
@solrac3f can you share the full stack trace of the exception?
