### ISSUE TITLE
MAUI.iOS  /usr/bin/codesign exited with code 2:   invalid option

### ISSUE THREAD

**Issue by Jakar510** [dotnet/maui#22235]
### Description

After doing the workaround for this [issue](https://github.com/dotnet/maui/issues/22177), I get the following error  

	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8053\tools\msbuild\iOS\Xamarin.Shared.targets(2257,3): error :
	    /usr/bin/codesign exited with code 2:
		codesign: invalid option --  
		Usage: codesign -s identity [-fv*] [-o flags] [-r reqs] [-i ident] path ... # sign
			codesign -v [-v*] [-R=<req string>|-R <req file path>] path|[+]pid ... # verify
			codesign -d [options] path ... # display contents
			codesign -h pid ... # display hosting paths
			codesign --validate-constraint path ... # check the supplied constraint plist
		Failed to codesign '<project>': codesign: invalid option --  
		Usage: codesign -s identity [-fv*] [-o flags] [-r reqs] [-i ident] path ... # sign
			codesign -v [-v*] [-R=<req string>|-R <req file path>] path|[+]pid ... # verify
			codesign -d [options] path ... # display contents
			codesign -h pid ... # display hosting paths
			codesign --validate-constraint path ... # check the supplied constraint plist

### Steps to Reproduce

Create/open MAUI project. try the workaround listed above.
Disable Hot Reload (required due to AppCenter known issue)
Try to build...boom

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.x

### Did you find any workaround?

Nope

### Relevant log output

```shell
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8053\tools\msbuild\iOS\Xamarin.Shared.targets(2257,3): error :
	    /usr/bin/codesign exited with code 2:
		codesign: invalid option --  
		Usage: codesign -s identity [-fv*] [-o flags] [-r reqs] [-i ident] path ... # sign
			codesign -v [-v*] [-R=<req string>|-R <req file path>] path|[+]pid ... # verify
			codesign -d [options] path ... # display contents
			codesign -h pid ... # display hosting paths
			codesign --validate-constraint path ... # check the supplied constraint plist
		Failed to codesign '<project>': codesign: invalid option --  
		Usage: codesign -s identity [-fv*] [-o flags] [-r reqs] [-i ident] path ... # sign
			codesign -v [-v*] [-R=<req string>|-R <req file path>] path|[+]pid ... # verify
			codesign -d [options] path ... # display contents
			codesign -h pid ... # display hosting paths
			codesign --validate-constraint path ... # check the supplied constraint plist
```

**Comment by drasticactions** [comment]
@rolfbjarne Do you know if this and the other issue they referenced MAUI UI issues, issues with SDK tooling, or something else?

**Comment by rolfbjarne** [comment]
I'm not sure what's going on here.

@Jakar510 can you get a binary build log (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) that shows the build error?

**Comment by jaosnz-rep** [comment]
I used your demo app(TestMauiAp) and the MAUI project I created myself (8.0.7 and 8.0.21), and I couldn't reproduce this error. It built successfully without errors and warnings.

**Comment by Jakar510** [comment]
I updated to Visual Studio v17.10.0 Preview 7 and I get the following error: `Verification of iOS environment is running. Please try again in a moment.`

I tried restarting the mac, VS and windows. no change.
