### ISSUE TITLE
exception of type 'javax.crypto.aeadbadtag exception' was thrown when calling SecureStorage.Default.SetAsync on Android

### ISSUE THREAD

**Issue by JimAIT** [dotnet/maui#22239]
### Description

Upgraded MAUI to 8.0.20 and now when I call SecureStorage.Default.SetAsync, I get "exception of type 'javax.crypto.aeadbadtag exception' was thrown" on Android.  Works find on Windows.

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by drasticactions** [comment]
Seeing that the exception is from `javax` it makes sense it would work in Windows. @jonathanpeppers @jonpryor would you have any ideas? would this be a runtime or SDK issue?

**Comment by jonathanpeppers** [comment]
@JimAIT can you past the full stacktrace of the exception? `adb logcat` will have this information:

* https://docs.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log

If MAUI has a `SecureStorage` API, this is probably the right place for the issue.

**Comment by JimAIT** [comment]
Sorry for the delay, I was able to get around this by deleting the App Data on my device.

**Comment by jonathanpeppers** [comment]
@JimAIT was there a problem during an upgrade between MAUI versions? Or perhaps a migration from Xamarin.Forms -> MAUI?

Or was this a fluke and we can close this? Thanks!

**Comment by moljac** [comment]
@jonathanpeppers 

SecureStorage runtime issues might have root in this problem/issue:

https://github.com/dotnet/maui/issues/18230#issuecomment-2021422788

https://github.com/dotnet/maui/pull/4211/files#diff-93ca7559b0a2eaf2bab3285f6d90c92ed92eee598bfbc814b368201753a0ef29

Seems like problem of documentation and overeagerly rebranding.
