### ISSUE TITLE
FileSystem.Current.AppDataDirectory returns an invalid path when built for Windows as unpackaged

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#22231]
### Description

I'm getting very different results for FileSystem.Current.AppDataDirectory between VS22 and VS Code. Both claim to be using .NET 8.0.300-preview.24203.14. The fact they are different was confusing, but I learned VS Code preview is defaulting to unpackaged. 

"User Name" is the publisher name from the manifest. We should give this a better name.

Also, would be good if we actually create this folder when used. `Preferences` used to do this according to @mattleibow .

VS22 says it's 
C:\Users\davidortinau\AppData\Local\Packages\com.simplyprofound.sentencestudio_9zz4h110yvjzm\LocalState\

VS Code says it's 
C:\Users\davidortinau\AppData\Roaming\User Name\com.simplyprofound.sentencestudio\Data\

Both are debugging to Windows. Same project. Packaged version doesn't require manual creation, but unpackaged seems it does. When I try to put my database there it has create permissions - must only apply to the file, not the path.

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

Didn't try, but could probably create the folder myself.

**Comment by marossi7** [comment]
Any solution to this ?

I have the same problem, FileSystem.AppDataDirectory returns the same path for me:

`C:\Users\*myuser*\AppData\Roaming\User Name\*someid*\Data\`

The `\Data` folder does not even exist in the path and it throws and exception.

**Comment by marossi7** [comment]
@kevinxufei the visual studio path example - is the application built as unpackaged ?
