### ISSUE TITLE
Displaying a map using iOS 17.4 causes crash

### ISSUE THREAD

**Issue by michaelstonis** [dotnet/maui#22241]
### Description

When using a an iOS device running 17.4, tested with simulator only, attempting to display a map will result in an immediate crash.

### Steps to Reproduce

1. Clone the repository using the reproduction project repository provided.
2. Attempt to run the application using an iOS 17.4 simulator

### Link to public reproduction project repository

https://github.com/michaelstonis/MauiNet8MapsTest

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.4

### Did you find any workaround?

The easiest workaround for testing purposes is to use an iOS 17.2 simulator or device.

**Comment by RoiChen001** [comment]
Can repro this issue at iOS simulator 17.4 on the latest 17.10 Preview 6(8.0.21).

**Comment by drasticactions** [comment]
https://github.com/dotnet/maui/issues/21057

Xcode 15.3 (And by extension, iOS 17.4, etc) are not supported by .NET iOS (and by extension, the MAUI UI Toolkit). This isn't a MAUI UI issue.
