### ISSUE TITLE
[net9.0][testing] Android Compatibility UITests are not working on net9.0 branch

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#22267]
### Description

Seems something broke the old Control Gallery UITests for Android on net9.0 It would be great to have this fixed or ported to the new Appium

### Link to public reproduction project repository

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9539875&view=logs&j=9874f22e-7603-559c-9c5b-d2d8bb2e9740&t=ae92220e-833c-53d5-7f8d-25f60cff4b6c&l=646

### Version with bug

9.0.0-preview.3.10457

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.21 SR4.1

### Affected platforms

Android

### Relevant log output

```shell
emulatorProcess.Kill()
AndroidAvdDelete
Resolved tool to path /Users/builder/Library/Developer/Xamarin/android-sdk-macosx/cmdline-tools/latest/bin/avdmanager
Executing: /Users/builder/Library/Developer/Xamarin/android-sdk-macosx/cmdline-tools/latest/bin/avdmanager delete avd -n DEVICE_TESTS_EMULATOR
Error: System.Exception: All tests are marked inconclusive, no tests ran. There is probably something wrong with running the tests. Error message extracted from /Users/builder/azdo/_work/3/a/test-results/android/TestResult.xml, check this file for more details: App did not start for some reason: System.Exception: No .NET assemblies were found in the application. Please disable Fast Deployment in the Visual Studio project property pages or edit the project file in a text editor and set the 'EmbedAssembliesIntoApk' MSBuild property to 'true'.
  at Xa
```

**Comment by PureWeen** [comment]
we should evaluate if this is worth spending time on
or if we should put more of our efforts here https://github.com/dotnet/maui/issues/20245

**Comment by PureWeen** [comment]
Closing this in favor of
https://github.com/dotnet/maui/issues/20245
