### ISSUE TITLE
Razor-maui-hybrid template shows a black window often.

### ISSUE THREAD

**Issue by Gavin-Williams** [dotnet/maui#22273]
### Description

Sometimes when I run the template the window is black. This happens about 1 / 4 times, which makes it completely unusable. I couldn't possibly hand an app over with such a high failure rate. It has to render properly every time.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.31

**Comment by Eilon** [comment]
Dup of #15533
