### ISSUE TITLE
InputTransparent="true" on a Layout breaks child controls on Android

### ISSUE THREAD

**Issue by rudyspano** [dotnet/maui#22289]
### Description

On Android, setting InputTransparent=true on a layout (for example: Grid) leads to bugs on child controls.
If we want to display after a user action a child control that was previously not visible (IsVisible=false => true), the first time the control is not displayed as you can see in my reproduction sample.
[InputTransparentIssue.zip](https://github.com/dotnet/maui/files/15246627/InputTransparentIssue.zip)

https://github.com/dotnet/maui/assets/21014908/750258f0-fc4d-488c-9064-86075c3c950f

I've also seen that animating other properties on child controls of a layout also causes weird behaviors.

 

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10 Preview 6.0 (8.0.21). Can repro on android platform with sample project.
