### ISSUE TITLE
Mouse selection broken with the FluentUI package from MAUI > 8.0.7

### ISSUE THREAD

**Issue by euantorano** [dotnet/maui#22297]
### Description

Original issue found here: https://github.com/microsoft/fluentui-blazor/issues/1741 - was advised this is a bug in MAUI.

When upgrading `Microsoft.Maui.Controls` and/or `Microsoft.Maui.Controls.Compatibility` with a Blazor Hybrid app, the `<FluentComboBox>` and `<FluentSelect>` components from the FluentUI package stop accepting mouse inputs to select items. Keyboard actions to select items still work.

`Microsoft.Maui.Controls` > 8.0.7 causes this bug.
`Microsoft.Maui.Controls.Compatibility` > 8.0.7 causes this bug.

Using older versions of these libraries (e.g. using 8.0.7 for both) resolves the problem.

Note that other components may also be broken, but I have observed both `FluentCombobox` and `FluentSelect` myself.

Demo of the problem in action:

![Demo Recording](https://github.com/microsoft/fluentui-blazor/assets/748913/52432c1b-1392-459c-8e0f-4c98b05d6a2a)

### Link to public reproduction project repository

https://github.com/euantorano/fluentui-combo-and-select

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

Windows

### Affected platform versions

Windows 11 Pro Build 22631.3527

**Comment by Eilon** [comment]
This appears to be a bug in WinUI WebView2 specifically. I opened a MAUI-less repro bug here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/4545

**Comment by euantorano** [comment]
Thanks
