### ISSUE TITLE
Button with image not scaling to HeightRequest on iOS

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#22306]
### Description

Extension of https://github.com/dotnet/maui/issues/9734

Button with an image fails to correctly scale the source image to the size of the button this results in the full size image being displayed in Android and a skewed image in iOS

iOS
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-08-29 at 17 43 58](https://user-images.githubusercontent.com/4401594/187150523-b3df1c90-fbf6-48c4-b62a-d4b216d391d7.png)

### Steps to Reproduce

Create a new example Maui App

Add the following line of xaml to MainPage.xaml

```
<Button
                ImageSource="dotnet_bot.png"
                Text="Im a happy button"
                HeightRequest="40"
                WidthRequest="200"/>
```

Run the solution, works correctly in WinUI and results in the full sized image next to the button in Android and the image skewed and distorted but with the correct height in iOS 

I expect this to correctly render the image in the button to the left of the text in the button using the heightrequest to scale down to the requested height maintaining the images aspect ratio, see WinUI example above where the image and button are rendered correctly

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

### Did you find any workaround?

Reduce the image size manually to be the correct size desired on a device

**Comment by tj-devel709** [comment]
Leaving a note here that the change was implemented but crashed upon device rotation
