### ISSUE TITLE
Workload installation error

### ISSUE THREAD

**Issue by KrishMishra007** [dotnet/maui#2232]
Workload installation failed: Workload not found: microsoft-android-sdk-full. Known workloads: android android-aot ios maccatalyst macos maui maui-mobile maui-desktop maui-core maui-android maui-maccatalyst maui-ios maui-windows tvos microsoft-net-sdk-emscripten wasm-tools microsoft-net-runtime-android microsoft-net-runtime-android-aot microsoft-net-runtime-ios runtimes-ios microsoft-net-runtime-maccatalyst runtimes-maccatalyst microsoft-net-runtime-macos microsoft-net-runtime-tvos runtimes-tvos microsoft-net-runtime-mono-tooling

**Comment by airtaxi** [comment]
I have the same issue.

**Comment by jfversluis** [comment]
Is this using the maui-check tool? Please check the latest instructions on the [repo for that](https://github.com/Redth/dotnet-maui-check/) and especially look for the cleanup script in there that you might want to run first.

If it then still doesn't work please open an issue there or see if there is already an appropriate issue. In either case, we need a lot more detail than just this message to be able to diagnose what is going on :)

Thanks!
