### ISSUE TITLE
App did not automatically reflect changes to the label

### ISSUE THREAD

**Issue by LukeMertonWay** [dotnet/maui#22331]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/modify
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Made the change to the label as instructed by the app did not update to reflect the new label, I saved the file and this still did not update.

**Comment by PureWeen** [comment]
@LukeMertonWay can you attach a repro? Are you using vscode? Are you making changes while the app is running and hoping changes will happen?
