### ISSUE TITLE
MS build pair to mac optimization

### ISSUE THREAD

**Issue by Serge-N** [dotnet/maui#22352]
### Description

It would be faster to check if dotnet is already installed on that machine before downloading the SDK. In this case the sdk was already installed directly on the target machine.

<img width="293" alt="image" src="https://github.com/dotnet/maui/assets/51508252/9c545bbf-3789-4436-b32e-d75693c53256">

### Public API Changes

Check that the installed SDK matches the lastest.

### Intended Use-Case

Improve developer experience.

**Comment by drasticactions** [comment]
The MAUI UI Team does not maintain the Pair To Mac tooling, so it would be better to direct this to VS Feedback than here.

That said, I believe they specifically provision builds of dotnet that are siloed from the ones installed on your Mac, specifically so they won't conflict with ones installed on your system. Say you have a newer dotnet installed on Windows than on your Mac. If it installed globally on your Mac, that could introduce new issues on your Mac that you wouldn't know of until you went back and saw the version change. Matching the version of dotnet you are running on Windows and provisioning that specifically for Pair To Mac cuts down on those issues, albeit with the side effect of needing to download another dotnet build even if you have that installed.

So IMO, I think the current system is fine.

**Comment by jfversluis** [comment]
Assuming this has been reported in the right place by now. Thanks!
