### ISSUE TITLE
[Bug] Incorrect SupportedOSPlatform attribute?

### ISSUE THREAD

**Issue by dotMorten** [dotnet/maui#2235]
### Description

I'm looking at the [Maui doc here](https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms), and I see that to run Maui you need:
> .NET Multi-platform App UI (.NET MAUI) apps can be written for the following platforms:
>  - Android 5.0 (API 21) or higher.
>  - iOS 10 or higher.

However when I build an iOS app targeting 13.6 and set the SupportedOSPlatform to 10, or Android app targeting 30 but min-target is 21, I get analyzer warnings that my code is reachable below 13.6 and 30.
Looking at the assembly attributes, it confirms that the supportedos platform is set to 13.6 and 30 instead of 10 and 21. So which one is wrong?

Did you just forget to set the SupportedOSPlatformVersion in the project settings? (since that'll make it default min to the target version)

### Steps to Reproduce

1. Create a new Maui project template.
2. Change target frameworks to: `<TargetFrameworks>net6.0-ios13.6;net6.0-android30.0</TargetFrameworks>`
3. Define minimum supported versions in a property group:
```xml
    <SupportedOSPlatformVersion Condition="'$(TargetFramework)'=='net6.0-android30.0'">23.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="'$(TargetFramework)'=='net6.0-ios13.6'">13.0</SupportedOSPlatformVersion>
```
Compile.

### Expected Behavior
No analyzer warnings

### Actual Behavior
Warnings generated:
> 1>E:\sources.tmp\App7\MauiApp1\MauiApp1\Startup.cs(15,13,20,19): warning CA1416: This call site is reachable on: 'iOS' 13.0 and later. 'AppHostBuilderExtensions.ConfigureFonts(IAppHostBuilder, Action<IFontCollection>)' is only supported on: 'iOS' 13.6 and later.
1>E:\sources.tmp\App7\MauiApp1\MauiApp1\App.xaml.cs(14,13,14,21): warning CA1416: This call site is reachable on: 'iOS' 13.0 and later. 'Application.MainPage' is only supported on: 'iOS' 13.6 and later.
1>E:\sources.tmp\App7\MauiApp1\MauiApp1\Startup.cs(19,21,19,77): warning CA1416: This call site is reachable on: 'iOS' 13.0 and later. 'FontCollectionExtensions.AddFont(IFontCollection, string, string?)' is only supported on: 'iOS' 13.6 and later.
1>E:\sources.tmp\App7\MauiApp1\MauiApp1\Startup.cs(15,13,16,35): warning CA1416: This call site is reachable on: 'iOS' 13.0 and later. 'AppHostBuilderExtensions.UseMauiApp<App>(IAppHostBuilder)' is only supported on: 'iOS' 13.6 and later.
1>E:\sources.tmp\App7\MauiApp1\MauiApp1\App.xaml.cs(14,13,14,21): warning CA1416: This call site is reachable on: 'Android' 23.0 and later. 'Application.MainPage' is only supported on: 'Android' 30.0 and later.
1>E:\sources.tmp\App7\MauiApp1\MauiApp1\Platforms\Android\MainApplication.cs(12,13,12,38): warning CA1416: This call site is reachable on: 'Android' 23.0 and later. 'MauiApplication<Startup>' is only supported on: 'Android' 30.0 and later.
1>E:\sources.tmp\App7\MauiApp1\MauiApp1\Startup.cs(19,21,19,77): warning CA1416: This call site is reachable on: 'Android' 23.0 and later. 'FontCollectionExtensions.AddFont(IFontCollection, string, string?)' is only supported on: 'Android' 30.0 and later.
1>E:\sources.tmp\App7\MauiApp1\MauiApp1\Startup.cs(15,13,20,19): warning CA1416: This call site is reachable on: 'Android' 23.0 and later. 'AppHostBuilderExtensions.ConfigureFonts(IAppHostBuilder, Action<IFontCollection>)' is only supported on: 'Android' 30.0 and later.
1>E:\sources.tmp\App7\MauiApp1\MauiApp1\Startup.cs(15,13,16,35): warning CA1416: This call site is reachable on: 'Android' 23.0 and later. 'AppHostBuilderExtensions.UseMauiApp<App>(IAppHostBuilder)' is only supported on: 'Android' 30.0 and later.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2022 Preview 3.1
- Platform Target Frameworks: 
  - iOS:  11->13.6
  - Android: 23->30
  - UWP:  N/A
- Nuget Packages: Preview 7 with `<UseMaui>true</UseMaui>`
- Affected Devices: Android, iOS

### Screenshots

![image](https://user-images.githubusercontent.com/1378165/130683794-9b3557ac-3dd7-4bb0-a0a1-8aee6a725927.png)
![image](https://user-images.githubusercontent.com/1378165/130683805-04b093a7-dee7-402a-b439-f8b7cf229642.png)

![image](https://user-images.githubusercontent.com/1378165/130684475-477afa5a-19ee-4ab7-aeaf-ab70e4ed248d.png)

**Comment by kristinx0211** [comment]
Not reproducible with Android 11 and iPhone 13 pro max IOS 15.2.

**Comment by dotMorten** [comment]
It it reproducible but was addressed in https://github.com/dotnet/maui/pull/2905
