### ISSUE TITLE
ImageButton Padding stops working with .NET 8 

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#22364]
### Description

Padding seems to stop working after upgrading to .NET 8 on all `ImageButton` for Android.

Relevant Screenshots 

### Steps to Reproduce

Add an `ImageButton` to your page with padding, 
Notice how the padding is ignored on Android but works on iOS.

| iOS | Android |
| --- | --- |
| <img src="https://github.com/dotnet/maui/assets/31090457/237518c3-5d43-421d-a59d-2ae448d5989d" width="250" height="550"/>| <img src="https://github.com/dotnet/maui/assets/31090457/5edbd97b-7d84-4654-8920-746cd12f769f" width="250" height="550"/> |

### Link to public reproduction project repository

https://github.com/FreakyAli/Maui.FreakyControls/tree/r4-gh/fix/pin-control

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.101

### Affected platforms

Android

### Affected platform versions

Android 12 and 13 

### Did you find any workaround?

NO

**Comment by FreakyAli** [comment]
@mattleibow The latest version of MAUI does not fix this, Why was this closed?

**Comment by NoelleRousselle** [comment]
> @mattleibow The latest version of MAUI does not fix this, Why was this closed?

I think it is part of the .NET 8 SR6 Milestone which is not finished yet

**Comment by mattleibow** [comment]
> Why was this closed?

Typically, the issues are closed when the code is merged into the main branch. This does not mean that the issue is fixed and shipped. However, we have nightly builds that you can test and use.

We also release new versions to NuGet periodically outside of VS release schedules that you can use. This fix is not yet part of any official release.
