### ISSUE TITLE
IndicatorLayout isn't being correctly cleared out when bindable property is set to null

### ISSUE THREAD

**Issue by liufeias** [dotnet/maui#22361]
https://github.com/dotnet/maui/blob/39f90eeb9866940117d5501f8b864498b9db0c88/src/Controls/src/Core/IndicatorView/IndicatorView.cs#L155-L159

**Meaningless code found inside the indicatorView.cs file**

**IndicatorView.IndicatorLayout is already null, still use as to convert to IndicatorStackLayout**

**Comment by PureWeen** [comment]
I don't think the code is meaningless, I think the if statement is wrong

**Comment by drasticactions** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/7465/files#diff-058a6dc771a8401a8be8a54fa8c48d741f9cc316244e34ba553dd6508b3354bdR138-R149

This has been here since Xamarin.Forms, unchanged, for five years. I guess no one ever hit it? lol.

**Comment by liufeias** [comment]
> https://github.com/xamarin/Xamarin.Forms/pull/7465/files#diff-058a6dc771a8401a8be8a54fa8c48d741f9cc316244e34ba553dd6508b3354bdR138-R149
> 
> This has been here since Xamarin.Forms, unchanged, for five years. I guess no one ever hit it? lol.

It's really confusing.

**Comment by liufeias** [comment]
> I don't think the code is meaningless, I think the if statement is wrong

That's true. I've been confused for a long time.
