### ISSUE TITLE
The style on the switch is not working

### ISSUE THREAD

**Issue by IknowL1f3** [dotnet/maui#22373]
### Description

I'm using xaml code:
```
<Switch Margin="0, 20, 0, 0, 0"
        ThumbColor="Black"
        Toggled="OnToggeled"
        x:Name="agree"
        />
```
After clicking on the component, it resets its style to normal. I tried directly through the code to set it when changing it:
```
private void OnToggeled(object sender, EventArgs e)
{
    Switch switchControl = (Switch)sender;
    if (switchControl.IsToggled)
    {
        switchControl.ThumbColor = Colors.Green;
    }
    else
    {
        switchControl.ThumbColor = Colors.Red;
    }
}
```
But it didn't lead to anything....

### Steps to Reproduce

1. Create project
2. add switch in page
3. add ThumbColor

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.10 Preview 7.0 (8.0.21/8.0.3). Can repro it on android platform and found a similar issue(https://github.com/dotnet/maui/issues/18625).

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue:

![issue-22373](https://github.com/dotnet/maui/assets/6755973/95405b0c-caad-41a4-8358-fa12b808c554)

Could you attach a small sample where reproduce the problem?

**Comment by IknowL1f3** [comment]
> Не удается воспроизвести проблему:
> 
> ![проблема-22373](https://private-user-images.githubusercontent.com/6755973/330308088-95405b0c-caad-41a4-8358-fa12b808c554.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODkxNTUsIm5iZiI6MTcxNTY4ODg1NSwicGF0aCI6Ii82NzU1OTczLzMzMDMwODA4OC05NTQwNWIwYy1jYWFkLTQxYTQtODM1OC1mYTEyYjgwOGM1NTQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTIxNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkwYzE4OWNjMmJjOTYwYWYxNTFmNzlhZDM3NDdhZmY0NDk2MzI5NTA2M2U4Nzk3NjMxN2Y1NmQxNmVhM2ZiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AeNniclSJp74xMWTmimep8jc4hmPkEzPvxy0VN-itv8) [ ![проблема-22373](https://private-user-images.githubusercontent.com/6755973/330308088-95405b0c-caad-41a4-8358-fa12b808c554.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODkxNTUsIm5iZiI6MTcxNTY4ODg1NSwicGF0aCI6Ii82NzU1OTczLzMzMDMwODA4OC05NTQwNWIwYy1jYWFkLTQxYTQtODM1OC1mYTEyYjgwOGM1NTQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTIxNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkwYzE4OWNjMmJjOTYwYWYxNTFmNzlhZDM3NDdhZmY0NDk2MzI5NTA2M2U4Nzk3NjMxN2Y1NmQxNmVhM2ZiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AeNniclSJp74xMWTmimep8jc4hmPkEzPvxy0VN-itv8) ](https://private-user-images.githubusercontent.com/6755973/330308088-95405b0c-caad-41a4-8358-fa12b808c554.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODkxNTUsIm5iZiI6MTcxNTY4ODg1NSwicGF0aCI6Ii82NzU1OTczLzMzMDMwODA4OC05NTQwNWIwYy1jYWFkLTQxYTQtODM1OC1mYTEyYjgwOGM1NTQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTIxNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkwYzE4OWNjMmJjOTYwYWYxNTFmNzlhZDM3NDdhZmY0NDk2MzI5NTA2M2U4Nzk3NjMxN2Y1NmQxNmVhM2ZiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AeNniclSJp74xMWTmimep8jc4hmPkEzPvxy0VN-itv8) [ ](https://private-user-images.githubusercontent.com/6755973/330308088-95405b0c-caad-41a4-8358-fa12b808c554.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODkxNTUsIm5iZiI6MTcxNTY4ODg1NSwicGF0aCI6Ii82NzU1OTczLzMzMDMwODA4OC05NTQwNWIwYy1jYWFkLTQxYTQtODM1OC1mYTEyYjgwOGM1NTQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTIxNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkwYzE4OWNjMmJjOTYwYWYxNTFmNzlhZDM3NDdhZmY0NDk2MzI5NTA2M2U4Nzk3NjMxN2Y1NmQxNmVhM2ZiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AeNniclSJp74xMWTmimep8jc4hmPkEzPvxy0VN-itv8)
> 
> Не могли бы вы прикрепить небольшой образец, в котором воспроизводится проблема?

Here is the repository with all the files
https://github.com/IknowL1f3/Parking

**Comment by jsuarezruiz** [comment]
Added the xaml label. Removing the global Switch Style works as expected. The local changes must override the global style.

**Comment by indieshack** [comment]
> Added the xaml label. Removing the global Switch Style works as expected. The local changes must override the global style.

Can you be more specific about the resolution please; what XAML label?

**Comment by ewerspej** [comment]
> Can you be more specific about the resolution please; what XAML label?

@indieshack @jsuarezruiz meant that he added the "area-xaml" label to this GitHub issue

**Comment by jfversluis** [comment]
Using the reproduction project I can no longer reproduce this with .NET 9 RC1 so I'm going to assume this is fixed. Let us know if that doesn't seem right!

Thanks!
