### ISSUE TITLE
iOS Simulator and phone showing partial keyboard or crashing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#22375]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/iOS-Simulator-and-phone-showing-partial-/10628374)._

---
In this app I’m building, there are 2 Editor element, one on each tab. In the first one, when clicked or tapped, just the top part of the soft keyboard is displayed with Done on the right. And if I tap in the second tab Editor field, it just crashes. 
Both were working fine before updating the whole package (macOs, iOS and VS).

---
#### Feedback Bot on 4/1/2024, 03:33 PM: 

(private comment, text removed)
#### Paul Wang [MSFT] on 4/1/2024, 03:43 PM: 

(private comment, text removed)
#### Luis Souza on 4/1/2024, 04:44 PM: 

(private comment, text removed)
#### Paul Wang [MSFT] on 4/1/2024, 07:12 PM: 

(private comment, text removed)
#### Luis Souza on 4/2/2024, 05:41 PM: 

(private comment, text removed)
#### Feedback Bot on 4/7/2024, 07:24 PM: 

(private comment, text removed)
#### Luis Souza on 4/8/2024, 04:06 PM: 

(private comment, text removed)
#### Luis Souza on 4/28/2024, 02:27 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
The original issue lists that this has been fixed

> I could finally isolate and fix this issue. It was caused by an attempt to set unfocus of the Editor when loaded the view, and for some reason, when tapped, it was displaying the kbd that way.
