### ISSUE TITLE
App net.maui problems with backgruod color application

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#22374]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/App-netmaui-problems-with-backgruod-col/10652542)._

---
[severity:It's more difficult to complete my work]
Hi I am making a net.maui project with Microsoft Visual Studio Community 2022 (64 bit) - Current Version 17.9.6 and can't set the contentPage background. I have tried with bacgroud, backgruodcolor, bacgroudImmage, I have tried to inseir all of them together, but the background always stays white with black Title. The problem is that if I insert ToolbarItem or FlyoutItem the hamburger or the three dots do not show as they are white. The problem remains even when loading the app on an android device. I would like to report the inability to change the background. Thank you kind regards

Translated with DeepL.com (free version)

---
#### Feedback Bot on 5/6/2024, 06:25 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by minis237** [comment]
I solved the problem by adding shell to backgroud, the project came from xamarin and this was not needed

**Comment by jfversluis** [comment]
Seems like this issue is resolved then.

If not, please open a new issue directly on this repository including relevant code and ideally a reproduction project. Thanks!

**Comment by minis237** [comment]
Yes problem solved thank you
