### ISSUE TITLE
[IOS] Maui .NET 8 The app has been terminated when start debugging

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#22379]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IOS-Maui-NET-8-The-app-has-been-termi/10631976)._

---
[severity:I'm unable to use this version]
Hello good,

I am trying to debug an app on IOS under .Net Maui 8.0 with Visual Studio 2022 on an Ipad Mini 4 with IOS 15.8.2 but when the splash screen is removed the application closes. The version of XCode is 15. If I try to launch it again from the iPad itself, the behavior is the same.

---
#### Feedback Bot on 4/6/2024, 08:14 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
The original issue is more than a month old at this point. Dear author, if you get to see this, please open a new issue directly on this repository. Make sure to include relevant code and/or other details.

The information in the original report is unfortunately not enough to diagnose what might be going on. Ideally, provide us with a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md) that shows this behavior.

Thank you!
