### ISSUE TITLE
The "ProjectReference" rule is missing the "{ItemType}" property. When Publishing maui android app

### ISSUE THREAD

**Issue by michaelonz** [dotnet/maui#22415]
### Description

My app compiles and run on android when i debug from laptop to device.
When i compile for release it compiles.
When i PUBLISH my app it wont build the app bundle.
It reports error:

The "ProjectReference" rule is missing the "{ItemType}" property. 
Failed to create App archive 'APPNAME'

At this stage i cannot publish my application so it is a show stopper.

### Steps to Reproduce

Select Build then Publish Selection with maui app that is targeting android 

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 13

### Did you find any workaround?

no - cant publish at all right now.

### Relevant log output

```shell
Xamarin - 17.9.0.140-d17-9+7ca5d58
Starting Broker in-process...
Successfully started Broker in-process
Connecting to Local Broker...
Successfully connected to Local Broker
Starting IDB Local Agent...
Successfully started IDB Local Agent
Checking xma 17.9.0.140 installation...
SetSelectedDeviceAsync BEST Android Emulator
Archiving App Bundle 'APPNAME'...
The "ProjectReference" rule is missing the "{ItemType}" property.
Failed to create App archive 'APPNAME'.
Archiving App Bundle 'APPNAME'...
The "ProjectReference" rule is missing the "{ItemType}" property.
Failed to create App archive 'APPNAME'.
```

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10 Preview 7.0 (8.0.21&8.0.20). Not repro on android platform. Android publish can be successful
