### ISSUE TITLE
Multiple project template is empty

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/maui#22412]
### Description

![image](https://github.com/dotnet/maui/assets/30250585/5bf32b32-3718-4632-952e-91f7469004da)
![1715732760484](https://github.com/dotnet/maui/assets/30250585/ac3ad85e-4825-4376-94a5-43a29f3707e7)
Multiple project template is empty

After opening the project folder by right-clicking, reopen the project to show that the related project does not exist

![image](https://github.com/dotnet/maui/assets/30250585/587adbaf-382c-4d49-8def-7ec9c27854ae)

### Steps to Reproduce

Create a default project directly with multiple project templates

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10 Preview 7(8.0.21 ). Can repro it.

**Comment by mattleibow** [comment]
This is fixed by https://github.com/dotnet/maui/pull/22294
