### ISSUE TITLE
Bindings to Width and Height of a Control never stop triggering, even if size did not change at all.

### ISSUE THREAD

**Issue by Picao84** [dotnet/maui#22432]
### Description

I have a font size converter that takes a label width and height to adjust the font size using native code. Long after the font size has been set the converter keeps being triggered, as if the label width and height was changed, but its the exact same values as before. 

This has only started happening from version 8.0.6 onwards on Android (iOS works perfectly fine). On a static screen this may not be noticeable  but if you have animations (e.g. panels moving) they are very choppy. It can potentially lead to higher resource usage and low performance.

### Steps to Reproduce

1 - Create a XAML page and add a label.

2 - Create an implementation of IMultiValueConverter.

3 - Add a multibinding to label for any property (e.g. Font Size) like this:

```xaml
<Label.FontSize>
    <MultiBinding Converter="{StaticResource FontSizeConverter}">
         <Binding Source="{RelativeSource Self}" Path="Text"/>
         <Binding Source="{RelativeSource Self}" Path="Width"/>
         <Binding Source="{RelativeSource Self}" Path="Height"/>
    </MultiBinding>
</Label.FontSize>
```

4 - Put a breakpoint on on the IMultiValueConverter implementation Convert method and see it being triggered all the time.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

Android

### Affected platform versions

Android 13 and Android 14

### Did you find any workaround?

Unfortunately not.

**Comment by PureWeen** [comment]
Possibly related
https://github.com/dotnet/maui/pull/22347

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by Picao84** [comment]
The issue seems to be partially fixed only. It still happens in modal pages. Plus the nightly build broke a lot of stuff, including border corner radius on Android, custom fonts, etc.. Totally unusable!!

**Comment by Picao84** [comment]
The latest nightly build seems to have fixed this issue. Unfortunately it created other issues like custom fonts not working at all and border corner radius not working when set from code...

**Comment by PureWeen** [comment]
> The latest nightly build seems to have fixed this issue. Unfortunately it created other issues like custom fonts not working at all and border corner radius not working when set from code... sigh.

Can you please log issues for these so we can fix ASAP?

The border issue might be fixed by
https://github.com/dotnet/maui/pull/22558
