### ISSUE TITLE
App Crash on Android due to ScrollViewHandler.DisconnectHandler call during Scroll Animation while navigating away from Page.

### ISSUE THREAD

**Issue by PATRICKdallat** [dotnet/maui#22443]
### Description

The android application experiences a crash when a user attempts to navigate back (i.e. removing the page from the stack) while a scroll animation is in progress and the ScrollViewHandler has been disconnected.

Here are three suggested improvements:

1. Refine the RequestScrollTo CommandMapping by adding a null-check for the VirtualView within the OnFinish Action Callback. This will prevent potential null reference errors.

2. Prior to disposing of the ScrollView from the ScrollViewHandler.DisconnectHandler, cancel the _scrollCompletionSource. This will ensure that no tasks are left open, improving resource management.

3. Create a publicly (or protected) accessible method to cancel the ScrollView Scroll animation task. This will provide greater flexibility and control over the Scroll animation.

### Steps to Reproduce

1. Clone the reproduction project repository
2. Run on Android device
3. Navigate to Second Page
4. On Appearing of Second Page navigate back to main page (before scroll animation finishes)
5. App will crash

### Link to public reproduction project repository

https://github.com/PATRICKdallat/ScrollViewHandlerCrash

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Replacing the CommandMapper for IScrollView.RequestScrollTo

`        ScrollViewHandler.CommandMapper.ReplaceMapping<IScrollView, ScrollViewHandler>(nameof(IScrollView.RequestScrollTo), (handler, _, args) => 
        {
            var context = handler.PlatformView.Context;
            
            if (args is not ScrollToRequest request || context is null)
            {
                return;
            }
        
            var horizontalOffsetDevice = (int)context.ToPixels(request.HorizontalOffset);
            var verticalOffsetDevice = (int)context.ToPixels(request.VerticalOffset);
        
            handler.PlatformView.ScrollTo(horizontalOffsetDevice, verticalOffsetDevice,
                request.Instant, () => handler?.VirtualView?.ScrollFinished());
        });`

### Relevant log output

`Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception (Unknown Source:0)
Android.Runtime.JNINativeWrapper._unhandled_exception (JNINativeWrapper.g.cs:13)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (JNINativeWrapper.g.cs:126)
Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.IScrollView,Microsoft.Maui.Platform.MauiScrollView>.get_VirtualView (ViewHandlerOfT.cs:42)
Microsoft.Maui.Handlers.ScrollViewHandler.Microsoft.Maui.Handlers.IScrollViewHandler.get_VirtualView (ScrollViewHandler.cs:53)
Microsoft.Maui.Handlers.ScrollViewHandler. (ScrollViewHandler.Android.cs:150)
Microsoft.Maui.Platform.MauiScrollView. (MauiScrollView.cs:288)
Android.Animation.AnimatorEventDispatcher.OnAnimationEnd (Animator.cs:86)
Android.Animation.Animator.IAnimatorListenerInvoker.n_OnAnimationEnd_Landroid_animation_Animator_ (Android.Animation.Animator.cs:142)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (JNINativeWrapper.g.cs:125)`

**Comment by RoiChen001** [comment]
Can repro this issue at Android platform on the latest 17.10 Preview 7(8.0.10&8.0.40).

**Comment by PATRICKdallat** [comment]
@kubaflo  
Unfortunately this is not a fix, this would be covering up the issue. 
The underlying issue that the ScrollTo task is still alive as we have not cancelled and the task has not completed. 

Can you take a look at the improvements listed above and that should address this issue. 
Let me know if there is anything you are not sure on and I am happy to help.

**Comment by PATRICKdallat** [comment]
@PureWeen 
I believe I am addressing the right person with this question, if not, point me in the right direction of someone who can clarify this.
I would just like some clarification for myself and my team, when should a ViewHandler be Disconnected (ViewHandler.DisconnectHandler)?

**Comment by PATRICKdallat** [comment]
@PureWeen 
Thank you @kubaflo for the fix for eliminating the chance of a crash on scroll view finish callback. 

However, can this ticket be reopened as the _scrollCompletionSource has not been cancelled/completed issue has not been addressed.

**Comment by PATRICKdallat** [comment]
@kubaflo 

Making the change from the merged PR does not resolve the issue.
App still crashes but the exception is now around the PlatformView rather than the VirtualView. 

Please attempt the same steps as above with the updated repo -> [https://github.com/PATRICKdallat/ScrollViewHandlerCrash](ScrollViewHandlerCrash)

**Comment by kubaflo** [comment]
@PATRICKdallat I think you should try with the latest nightly build

**Comment by PATRICKdallat** [comment]
@kubaflo 
Would you be able to answer the following - when should a ViewHandler be Disconnected (ViewHandler.DisconnectHandler)?
