### ISSUE TITLE
Error when running MyFirstMauiApp saying "Optimizing assemblies for size failed" in vscode.

### ISSUE THREAD

**Issue by siratsapon** [dotnet/maui#22449]
I cannot execute the C# MAUI example programme from this URL: https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run.

An error message will show stating that "Optimising assemblies for size failed." You can stop optimisation by setting the PublishTrimmed attribute to false. [/Users/...../MyFirstMauiApp/MyFirstMauiApp.csproj::TargetFramework=net8.0- maccatalyst]"

Please let me know how to repair it.

Thank you!

**Comment by mattleibow** [comment]
Can you attach a binlog?
https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

Does it build from the command line?
