### ISSUE TITLE
Haven't found the My Mac from the list of Debug target in curl braces

### ISSUE THREAD

**Issue by aditya429** [dotnet/maui#22471]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Assuming this has been reported in the right place by now and/or fixed. Thanks!
