### ISSUE TITLE
(1)Error running default MAUI/NET8 win10 solution. (2)Another user has already installed an unpackaged version of this app (3) Could not establish trust relationship for the SSL/TLS secure channel

### ISSUE THREAD

**Issue by parth211prajapati** [dotnet/maui#22489]
### Description

Hello👋
If anyone is experiencing this issue, please provide guidance on the correct method to resolve it.
I Used =>visual studio 2022 preview(.NET 8) ,Microsoft Windows 10 Pro, SDK 8.0.300-preview.24203

I Also Update WASDK(Version 5001.119.156.0)

Show output from: Build
Updating the layout...
DEP0840: Project 'MauiApp58' requires packages 'MicrosoftCorporationII.WinAppRuntime.Main.1.5_8wekyb3d8bbwe' and 'MicrosoftCorporationII.WinAppRuntime.Singleton_8wekyb3d8bbwe' with version >= '5001.70.1338.0'. These packages should be installed on first run, if not please visit http://go.microsoft.com/fwlink/?linkid=2222757 for installation instructions.
Deployment complete (0:00:00.17). Full package name: "com.companyname.mauiapp58_1.0.0.1_x64__9zz4h110yvjzm"
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========
========== Deploy completed at 18:09 and took 00.442 seconds ==========

and POP SHOW 

![331578346-b4edf692-2d72-44ff-8bdd-64dc5da35184](https://github.com/dotnet/maui/assets/122508473/1294c2bd-0f8f-42c2-8d93-9d5b4a36de45)

AppX Deployment operation failed for package com.companyname.mauiapp58_1.0.0.1_x64__9zz4h110yvjzm with error 0x80073CFB. The specific error text for this failure is: Another user has already installed an unpackaged version of this app. The current user cannot replace this with a packaged version. The conflicting package is com.companyname.mauiapp58 and it was published by CN=User Name.
![331582464-2db9b29a-1168-432f-af61-edd29dcaf648](https://github.com/dotnet/maui/assets/122508473/91d44949-2368-4b0c-a637-645fc2bf259d)

And also facing Nuget problem, This issue i facing Only MAUI Project.(https://api.nuget.org/v3/index.json This URL Proper Work on browser )
[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.
An error occurred while sending the request.
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
The remote certificate is invalid according to the validation procedure.

![331588386-4dfc76e7-5071-4f80-bd54-19febff8bf9b](https://github.com/dotnet/maui/assets/122508473/c40c8311-ec73-49de-9113-38775a362517)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-Windows10.0.19041.0)

**Comment by SmartmanApps** [comment]
Not that exact message, but a very similar one, which the solution was to uninstall the existing one AND reboot - only doing both those things in that order cleared it out.

**Comment by jfversluis** [comment]
I'm unclear what the status is here or even the issue. Please report 1 issue per err... issue 😄 which makes it easier to track things. I hope all is resolved by now. If not, feel free to open something new. For some of these issues please report to Visual Studio Feedback as suggested above.

Thanks!
