### ISSUE TITLE
XAML error is shown when the content of a DataTemplate is not a View

### ISSUE THREAD

**Issue by marchev-prgs** [dotnet/maui#22485]
### Description

There is an error shown in VS when in XAML the Content of a DataTemplate is not a View:

![image](https://github.com/dotnet/maui/assets/91615935/10da2213-b7ba-4664-8c6f-8640c9edcfea)

        <DataTemplate x:Key="template1">
            <local:MyTabViewItem>
                <local:MyTabViewItem.Header>
                    <Label Text="{Binding MyHeaderText}" />
                </local:MyTabViewItem.Header>
                <local:MyTabViewItem.Content>
                    <Grid>
                        <Label Text="{Binding MyContentText}" />
                    </Grid>
                </local:MyTabViewItem.Content>
            </local:MyTabViewItem>
        </DataTemplate>

The error says "Property DataTemplateContent does not support value of type MyTabViewItem". 

Note that MyTabViewItem is not a View, it is a BindableObject:
public class MyTabViewItem : BindableObject { }

Rationale:
In our case, we have a custom TabView. Each TabView-item contains two views - one header view, and one content view. This is one of the reasons we chose for the MyTabViewItem to not be a view, and it has two properties that contain the two views - Header and Content properties. 
While we understand that most items-controls will use the DataTemplate with a View in them, this is not necessarily a restriction, as the DataTemplate can create content of type object (for reference see the signature of the CreateContent() method of the DataTemplate - https://github.com/dotnet/maui/blob/f2cc45e3e95370fb170464b6af141e1cb88172c2/src/Controls/src/Core/ElementTemplate.cs#L73).

This is why we would like for that error to be removed as users of our custom TabView may think there is an error with their code.

### Steps to Reproduce

1. Download the repo from the link (https://github.com/telerik/ms-samples) and go to Maui/XamlErrorForDataTemplate
2. Open the project
3. Go to MainPage.xaml

Expected Behavior: No error should be displayed.

Actual Behavior: The whole DataTemplate is underlined and an error is displayed - "Property DataTemplateContent does not support value of type MyTabViewItem".

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/XamlErrorForDataTemplate

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.7 SR2

### Affected platforms

iOS, Android, Windows, macOS

### Did you find any workaround?

I did not find a workaround.

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10 Preview 7 (8.0.40 & 8.0.3). Can repro it.
![image](https://github.com/dotnet/maui/assets/128687574/ccecdaa1-9b7a-43b5-bf10-bfd9f4c250b9)

**Comment by PureWeen** [comment]
@mgoertz-msft @StephaneDelcroix  thoughts?

**Comment by mgoertz-msft** [comment]
What is the property type of DataTemplate.DataTemplateContent? Is MyTabViewItem assignable to it?

**Comment by marchev-prgs** [comment]
> What is the property type of DataTemplate.DataTemplateContent? Is MyTabViewItem assignable to it?

Yes, it is assignable, the sample runs correctly. It's just the shown error that casts doubt.

The signature of the method in the DataTemplate is object CreateContent() ([link](https://github.com/dotnet/maui/blob/f2cc45e3e95370fb170464b6af141e1cb88172c2/src/Controls/src/Core/ElementTemplate.cs#L73)). And in my case a tab-item is a BindableObject.

**Comment by mgoertz-msft** [comment]
Sorry, this was just now brought again to my attention. We don't usually look here for VS tooling bugs. Creating a Developer Community ticket in those cases is a better way to track issues with VS.

I created the following bug for VS for this:

[Bug AB#2199135](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2199135): XAML error is shown when the content of a DataTemplate is not a View

**Comment by jstedfast** [comment]
The AzDO bug report was closed as fixed on 8/13 and is slated as part of 17.12.

**Comment by mariusmcalpine** [comment]
Good day, When can we expect this fix to be available? Thanks

**Comment by mgoertz-msft** [comment]
@mariusmcalpine The fix is available in VS 17.12 Preview 2.0.
