### ISSUE TITLE
Error when running the project as windows machine

### ISSUE THREAD

**Issue by Thobs-Tricks** [dotnet/maui#22498]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 13, Reason: 'com.companyname.test_2' violates pattern constraint of '[-.A-Za-z0-9]+'.
The attribute 'Name' with value 'com.companyname.test_2' failed to parse.	Test_2

**Comment by jamesmontemagno** [comment]
Can you re-create the name as Test2 without the underscore

**Comment by moljac** [comment]
Hi

` 'com.companyname.test_2'` is not valid regex `[-.A-Za-z0-9]+`.

Remove `'_'` from the name in `csproj` file please.

And report if that worked.
