### ISSUE TITLE
[Bug]  Theme not applied to Switch control (Android)

### ISSUE THREAD

**Issue by I4-PJ** [dotnet/maui#2249]
Hello,

I have found an issue when theme is not correctly applied to SWITCH control running under Android project (haven't tested other platforms). In any state the button is just white. I can see it even in default MAUI template project after adding <Switch/> to MainPage.xaml. Haven't found any sample project where it works correctly either. Tried on API 30 and API 27 devices.

MAUI Preview 7, VS2022 3.1

Best regards
PJ.

**Comment by XamlTest** [comment]
@I4-PJ Could you provide your repro project, thanks?

**Comment by I4-PJ** [comment]
I can see it already fixed with latest release.

**Comment by XamlTest** [comment]
Thank you for your reply! We will close the the issue, if it reproduces again, feel free to open it and share your repro project.
