### ISSUE TITLE
Spans with FontAttributes do not render on Android (When Span.Text uses data binding)

### ISSUE THREAD

**Issue by CodingOctocat** [dotnet/maui#22491]
### Description

See:
https://github.com/dotnet/maui/pull/6536
https://github.com/dotnet/maui/issues/4729

This issue is not completely fixed, and `Span.Text` still fails to render ~~if it uses data binding~~ **(In my latest tests, this is also true for the non-data-binding case)**.

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10 Preview 7.0(8.0.408.0.21&8.0.10). Can repro on Android platform.
![image](https://github.com/dotnet/maui/assets/77434865/003fc555-b992-4f32-9f80-cbe6ab4f0e91)

**Comment by kubaflo** [comment]
Hi it works for me now
```
<VerticalStackLayout>
            <Label Text="label" x:Name="label">
                <Label.FormattedText>
                    <FormattedString>
                        <Span Text="Hello"/>
                        <Span Text="World" FontAttributes="{Binding FontAttributes}"/>
                        <Span Text="MAUI!" FontAttributes="Italic"/>
                    </FormattedString>
                </Label.FormattedText>
            </Label>
</VerticalStackLayout>
```
<img  alt="Screenshot 2024-06-09 at 11 22 52" src="https://github.com/dotnet/maui/assets/42434498/dd8d5781-6101-4c05-9af5-2bd24ac2d7f4">

**Comment by CodingOctocat** [comment]
@kubaflo Could you please provide your development environment details? It seems like it can't be fixed automatically.

**Comment by kubaflo** [comment]
@CodingOctocat I'm using the nightly latest build

**Comment by CodingOctocat** [comment]
It seems to have fixed

- 8.0.40 SR5
- VS 17.10.35013.160
- PackageReference Include="Microsoft.Maui.Controls" Version="8.0.60"
- PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.60"
