### ISSUE TITLE
[MAC OS] SNMP Socket Permission Issues

### ISSUE THREAD

**Issue by mauisansan** [dotnet/maui#22516]
### Description

- I want to use "System.Net.Sockets.Socket" on MacOS for very simple SNMP communication, 
However, I get a "Permission denied" message when receiving.

- What I have implemented this time is based on maui's sample code and only "MainPage.xaml.cs" is modified.

- On the other hand, when I use the same code in a c# console application, I can receive without any problem. (The communication partner is the same for both Maui and the console application).

- Same maui code worked fine in windows environment.

The execution environment is
- mac: intel cpu
- os: Ventura 13.6.1
- account: admin user
- .net: .net8.0.201 
- maui(vscode): v0.10.61

### Steps to Reproduce

1. create a new project in maui.
2. change "MainPage.xaml.cs" to the following.

```
using System.Net.Sockets;
using System.Net;

namespace MauiApp1
{
    public partial class MainPage : ContentPage
    {
        int count = 0;

        public MainPage()
        {
            InitializeComponent();

            byte[] packet = new byte[1024];

            Socket sock = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
            sock.SetSocketOption(SocketOptionLevel.Socket,
                            SocketOptionName.SendTimeout, 2000);

            IPEndPoint iep = new(IPAddress.Parse("192.168.0.1"), 2000);
            EndPoint ep = (EndPoint)iep;

            try
            {
                sock.SendTo(packet, packet.Length, SocketFlags.None, iep);
            }
            catch (SocketException ex)
            {

                Console.WriteLine(ex);
            }
            int recv;
            byte[] response = new byte[1024];
            
            //Receive response from packet
            try
            {
                recv = sock.ReceiveFrom(response, ref ep);
            }
            catch (SocketException ex)
            {
                Console.WriteLine(ex);
            }
        }

        private void OnCounterClicked(object sender, EventArgs e)
        {
            count++;

            if (count == 1)
                CounterBtn.Text = $"Clicked {count} time";
            else
                CounterBtn.Text = $"Clicked {count} times";

            SemanticScreenReader.Announce(CounterBtn.Text);
        }
    }

}

```

3. Create an environment that allows communication with Machine A, which responds immediately upon receipt of a command.
4. Execute program
5. Line 38. Error occurs with `recv = sock.ReceiveFrom(response, ref ep);` and the error is output in catch
> System.Net.Sockets.SocketException (13): Permission denied at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MAC OS: Ventura 13.6.1

### Relevant log output

```shell
System.Net.Sockets.SocketException (13): Permission denied at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
```

**Comment by drasticactions** [comment]
@mauisansan A C# console app isn't the same as a .NET iOS app. They're running on different runtimes and in very different contexts. What happens if you run this code in a .NET iOS app (`dotnet new ios`) that doesn't implement the MAUI UI framework?

**Comment by mauisansan** [comment]
@drasticactions 

The same code was implemented in .NET Mac app (dotnet new maccatalyst).
The communication was successful.

The procedure is as follows.
1. create a new .NET Mac app ( use "dotnet new maccatalyst").
2. change "Main.cs" to the following.
```
using testmac;
using System.Net.Sockets;
using System.Net;

// This is the main entry point of the application.
// If you want to use a different Application Delegate class from "AppDelegate"
// you can specify it here.

byte[] packet = new byte[1024];

Socket sock = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
sock.SetSocketOption(SocketOptionLevel.Socket,
                SocketOptionName.SendTimeout, 2000);

IPEndPoint iep = new(IPAddress.Parse("192.168.0.1"), 2000);
EndPoint ep = (EndPoint)iep;

try
{
    sock.SendTo(packet, packet.Length, SocketFlags.None, iep);
}
catch (SocketException ex)
{

    Console.WriteLine(ex);
}
int recv;
byte[] response = new byte[1024];

//Receive response from packet
try
{
    recv = sock.ReceiveFrom(response, ref ep);
}
catch (SocketException ex)
{
    Console.WriteLine(ex);
}



UIApplication.Main (args, null, typeof (AppDelegate));


```
3. Execute and confirm that line 33 "recv = sock.ReceiveFrom(response, ref ep);" succeeds



Is this enough to determine that the problem is in maui?

**Comment by drasticactions** [comment]
Did you disable the app sandbox? It’s enabled by default for MAUI template apps, but not .NET Mac Catalyst ones.

**Comment by mauisansan** [comment]
@drasticactions 

By adding "com.apple.security.network.server", the communication worked properly.
thank you.

**Comment by drasticactions** [comment]
Cool! Glad that fixed it!

it might be worth one day revisiting the differences between the templates, since that can create confusion and different expectations. For now, we can close this.
