### ISSUE TITLE
Newly installed VS 2022 In combination with Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compativility leads to The type or namespace name 'MauiWinUIApplication' does not exist in the namespace 'Microsoft.Maui'

### ISSUE THREAD

**Issue by SpeerBlick** [dotnet/maui#22515]
### Description

I observed that behaviour on an existing porject. Because I was not able to resolve it, I uninstalled VS 2022 and reinstalled it.
I created a new Maui App project. This one could be built without any error. But after I updated Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility to the newes availabe version 9.0.0-preview.3.10457 the issue appered.
![Screenshot 2024-05-20 113419](https://github.com/dotnet/maui/assets/48653825/b94e68eb-48b6-4717-9406-13056f523e5f)

### Steps to Reproduce

1. VS 2022 Version 17.97 installed
2. Create new Maui App project
3. Build and run the template app => ervery thing is find
4. Update Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility from the default version 8.0.7 to  the newest available on version  9.0.0-preview.3.10457
5. Build will end with build error shown in the attached image
![Screenshot 2024-05-20 113419](https://github.com/dotnet/maui/assets/48653825/b5b7b622-bc7c-4f78-b362-1c8a4bef3e30)
![Screenshot 2024-05-20 114112](https://github.com/dotnet/maui/assets/48653825/0809b4a6-d450-4d24-a7f2-392dd7b481a7)

### Version with bug

9.0.0-preview.3.10457

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

See attached images

### Did you find any workaround?

No workaround found.

**Comment by RoiChen001** [comment]
@SpeerBlick Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility rely on the .NET 9 SDK. You need to install the .NET 9 SDK and the corresponding .NET 9 MAUI Workload on your machine.
[Download .NET 9.0 (Linux, macOS, and Windows) (microsoft.com)](https://dotnet.microsoft.com/en-us/download/dotnet/9.0).
If you don't have any other questions, we will close this issue.

**Comment by jfversluis** [comment]
As indeed indicated, if you're going to update to a new major version of the NuGet packages, you will also need to have the .NET SDK with the matching major version installed on your machine.

Since you have .NET 8 installed, you should not go and add the 9.* packages on your project. If that is what you want, you'll have to install the .NET 9 SDK as well. The 8.* packages should work as expected.

Does that help?

**Comment by SpeerBlick** [comment]
Thanks for the hit.
What you are saying maks sence to me.
But I realy was under the impresion that bevore I updeted my VS 2022 to the newest version I already had the setup of a .NET8 project using .NET 9 Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility and it worked. But most likly I did a mistake and I am sorry for the inconvinienc.
Any way thanks for your respons.
