### ISSUE TITLE
Consider rounding numbers in `TransformationExtensions`

### ISSUE THREAD

**Issue by MartyIX** [dotnet/maui#22513]
### Description

https://github.com/dotnet/maui/pull/22481#discussion_r1605046260 contains a discussion regarding use of non-rounded values in https://github.com/dotnet/maui/blob/60a46c58df8cca8dc6f7e90f0ef65edfc8453a19/src/Core/src/Platform/Windows/TransformationExtensions.cs#L24-L25.

@jonathanpeppers pointed out that rounding might be good here. It might improve performance in corner/edge cases.

If rounding operations are missing, how should it be fixed?

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by mattleibow** [comment]
Fixed with https://github.com/dotnet/maui/pull/22481
