### ISSUE TITLE
ImageButton border (BorderWidth) overlaps the image instead of adding space

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#22520]
### Description

With null/no background:

| Android | iOS | Windows |
|:-:|:-:|:-:|
| ![ImageButtonUITests_BorderWidth](https://github.com/dotnet/maui/assets/1096616/5d36bcd9-a3ab-40ca-b445-190d33e06778) | ![ImageButtonUITests_BorderWidth](https://github.com/dotnet/maui/assets/1096616/02cd381b-06d3-44d8-a9db-c493fec2297b) | ![ImageButtonUITests_BorderWidth](https://github.com/dotnet/maui/assets/1096616/f4260a6f-67c0-453c-98c9-1fe20c8c9ec3) |

With background:

| Android | iOS | Windows |
|:-:|:-:|:-:|
| ![ImageButtonUITests_BorderWidth_WithBackground](https://github.com/dotnet/maui/assets/1096616/5197747c-06a8-47a2-ae32-3eb9e974f458) | ![ImageButtonUITests_BorderWidth_WithBackground](https://github.com/dotnet/maui/assets/1096616/dd48ba61-fea9-4731-9557-dd7afe6b1bc8) | ![ImageButtonUITests_BorderWidth_WithBackground](https://github.com/dotnet/maui/assets/1096616/a232dfd6-06b8-44da-be25-cc90029e0628) |

### Steps to Reproduce

Run the `ImageButtonUITests` or "Image Button Gallery" page.

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

**Comment by mattleibow** [comment]
Observed when adding UI tests to https://github.com/dotnet/maui/pull/22298

**Comment by espenrl** [comment]
This one could be relevant.

https://stackoverflow.com/questions/62341037/shapeableimageview-with-strokewidth-stroke-trimmed-on-all-four-side

It is very obvious that half the border stroke is clipped when using CornerRadius such that the border becomes circular. It can be combatted using `Padding`. But something has changed in MAUI and `ImageButton.Padding` doesn't do anything.

**Comment by mattleibow** [comment]
@espenrl the padding fix was _just_ merged https://github.com/dotnet/maui/issues/22364

**Comment by espenrl** [comment]
Found this PR which is about the issue I mentioned #21259
