### ISSUE TITLE
[Android & iOS]: In ListView with IsPullToRefreshEnabled enabled the PullToRefresh activity indicator remains stuck and doesnt get closed in .net 8 MAUI

### ISSUE THREAD

**Issue by muffadal53** [dotnet/maui#22532]
### Description

In .Net 8 MAUI if we have a ListView and we have set "IsPullToRefreshEnabled" to true with all the relevant properties then if we try to do a "Pull" to refresh the ListView items the "IsRefreshing" indicator remains displayed continously and doesn't get closed even after setting the "IsRefreshing" property to false in RefreshCommand as final step.

Below is the screenshot of the same:

![image](https://github.com/dotnet/maui/assets/20536331/72177dfd-e645-407b-b8aa-f36085209fac)

Please let me know how this can be fixed for both Android and iOS platforms or is there any workaround for this issue till it is fixed in .Net MAUI.

### Steps to Reproduce

1. Run the sample app from the reproduction repository.
2. Use PullToRefresh to refresh the ListView items.
3. Notice the "IsRefreshing" activity indicator is not getting closed after Refresh command is completed.

### Link to public reproduction project repository

https://github.com/muffadal53/ListViewRefreshApp

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

N/A

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10 Preview 7 (8.0.40 & 8.0.3). Can repro it.

**Comment by muffadal53** [comment]
@jfversluis: Can you please help in fixing this issue with workaround or urgent service pack release of .NET 8.0 as it is common usecase to use PullToRefresh functionality of ListView and it is urgent for our app release?

**Comment by eynerdevp** [comment]
same error here

**Comment by jfversluis** [comment]
Is there any reason you're setting Mode=OneWay on the IsRefreshing property? I think that might be the issue here. The ListView will set that to false whenever it's done refreshing, but now it can't because you set the mode to OneWay? Have you tried that?

**Comment by muffadal53** [comment]
> Is there any reason you're setting Mode=OneWay on the IsRefreshing property? I think that might be the issue here. The ListView will set that to false whenever it's done refreshing, but now it can't because you set the mode to OneWay? Have you tried that?

@jfversluis: The reason I have set the Mode=OneWay is because I am managing the value of IsRefreshing from the ViewModel during Reload operation. And even if you remove the Mode=OneWay the IsRefreshing spinner remains stuck
And if you look at the documentation of MAUI it is contradicting to what you have mentioned in your comment and here is what it is says in the documentation "Once the [ListView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.listview) is refreshed, the IsRefreshing property should be set to false, or the EndRefresh method should be called on the [ListView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.listview), to indicate that the refresh is complete."

So, please let me know how this issue cam be fixed.

**Comment by jfversluis** [comment]
@muffadal53 actually it's the other way around, I was mistaken. The `ListView` sets the `IsRefreshing` for you. So what happens is that the `ListView` sets `IsRefreshing` to `true` before it gets to this check: https://github.com/muffadal53/ListViewRefreshApp/blob/master/ViewModel/TestConfigViewModel.cs#L33

That check will evaluate to being false and then entire thing is being skipped and `IsRefreshed` is never set to `false`.

This is not a bug in .NET MAUI but rather something that is not correct in your code.

Thanks for the report!

**Comment by muffadal53** [comment]
@jfversluis: Yes it is other way round. The "IsRefreshing" is set to true by the ListView and we need to set it to "false" after Refresh. And I have updated my code and below is the updated version. Now, the "IsRefreshed" is set to false but even with that change the "IsRefreshing" spinner doesn't get closed.

Below us the updated code in the ViewModel:

`private void RefreshListItems()
{            
    try
    {
        TestConfigList.Clear();
        ReloadFromSource();
    }
    finally
    {
        ListRefreshing = false;
    }

}`

You can check the repositry too:
https://github.com/muffadal53/ListViewRefreshApp/blob/master/ViewModel/TestConfigViewModel.cs#L33

So, without checking the code by making the change you are suggesting as not an issue you just closed the issue by giving the reference of the MAUI document. This doesn't seem to be right. And it is not only me who has got this issue. Along with me @ninachen03  and @eynerdevp also are able to reproduce the issue. So, please use my updated version of the ListView sample and run it on your side and let me know the behavior.

@davidortinau: Please look into this issue and let me know the solution as it is urgent on our side.

Awaiting feedback at the earliest.

Regards

**Comment by muffadal53** [comment]
@samhouts: This issue is not resolved.So, can you please reopen this issue.Thanks.

**Comment by muffadal53** [comment]
It is really surprising that without providing working solution or workaround MAUI issues are just getting closed. Please provide answer to this issue @jfversluis, @davidortinau, @samhouts.

**Comment by jfversluis** [comment]
I pulled down your code again and added `OnPropertyChanged(nameof(ListRefreshing));` right after you set `ListRefreshing = false;`. This makes it work as it should.

There is no issue with .NET MAUI, this works as intended, therefore it's closed. The issue is somewhere in the logic in your code unfortunately.

**Comment by muffadal53** [comment]
Thanks @jfversluis for the clarification. I think it would be better to have a concrete example in MAUI documentation of ListView showing in section of [https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/listview?view=net-maui-8.0#pull-to-refresh](url) Pull to refresh on how this property must be handled. The current example doesn't seem to explain this detail properly.
