### ISSUE TITLE
Binding Border.StrokeShape stopped working in 8.0.60-ci.net8.10665

### ISSUE THREAD

**Issue by AlleSchonWeg** [dotnet/maui#22549]
### Description

Hi,
after upgrade the nuget nightlys my binding stopped working. Sample code:
```XAML
      <Border x:Name="myBorder"
              Margin="0,10,0,0"
              BackgroundColor="Blue"
              StrokeShape="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:TestViewModel}}, Path=RoundedRect}"
              Padding="0"
              StrokeThickness="0">
        <!--<Border.StrokeShape>
          <RoundRectangle CornerRadius="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:TestViewModel}}, Path=Radius}" />
        </Border.StrokeShape>-->
```
I init the StrokeShape wiith a CornerRadius of 4 and on the button click i create a new CornerRadius of 12. The change was not applied. 
```C#
        private void OnCounterClicked(object sender, EventArgs e)
        {
            count++;

            if (count == 1)
                CounterBtn.Text = $"Clicked {count} time";
            else
                CounterBtn.Text = $"Clicked {count} times";
            var model = (TestViewModel)BindingContext;
            var r = model.RoundedRect;
            r.CornerRadius = new CornerRadius(12, 12, 12, 12);
            model.RoundedRect = r;
            //SemanticScreenReader.Announce(CounterBtn.Text);
        }
```

### Steps to Reproduce

Start demo app und click button. Corner should be 12, but it's still 4.
Open csproj file and change nightl version to: 8.0.60-ci.net8.10656. Clean, build and start app again. Click the button, now the corner was changed.
Latest working version: 8.0.60-ci.net8.10656
First broken version: 8.0.60-ci.net8.10665
[MauiApp8.zip](https://github.com/dotnet/maui/files/15390650/MauiApp8.zip)

The StrokeShape was updated if Hot Reload is triggered or the device was rotated.

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by PureWeen** [comment]
@StephaneDelcroix @simonrozsival thoughts?

**Comment by PureWeen** [comment]
Latest working version: 8.0.60-ci.net8.10656
First broken version: 8.0.60-ci.net8.10665

https://github.com/dotnet/maui/commit/ea5ca41a763b3177eb5e686a555fef1958198f14
https://github.com/dotnet/maui/commit/97b9ecdc50745a912b97c46215822d90b3034d0b
