### ISSUE TITLE
Ios Maui sample app uses Chinese Simplified when Chinese Traditional is set in phone preferences

### ISSUE THREAD

**Issue by Czapek83** [dotnet/maui#22547]
### Description

Created new maui project. Created Strings.resx, Strings.zh.resx, Strings.zh-Hans.resx, and Strings.zh-Hant.resx files with below values of SampleText:
![image](https://github.com/dotnet/maui/assets/11677674/398a7ba0-b16f-4d52-bb9a-97008af50144)

On MainPage.xaml added label that will display proper text according to current language:
![image](https://github.com/dotnet/maui/assets/11677674/46413552-15c7-454e-a3dd-3fb11c4355bc)

And now, when setting Iphone Region to "China mainland" and language to "Chinese Traditional", the SampleText is taken from Chinese, Simplified, but should be taken from Chinese, Traditional:
![image](https://github.com/dotnet/maui/assets/11677674/5e86213e-8714-4c4a-8cd7-efba74c2b7d7)

### Steps to Reproduce

1. Create new maui project.
2. Create localized strings in Resources (Strings.zh-Hans.resx for Chinese Simplified and Strings.zh-Hant for Chinese Traditional) with different strings in it.
3. Use localized string in one of your screens
4. Change your Iphone region to "China mainland" and language to "Chinese Traditional".
5. Run your application and you can see that Chinese Simplified string is used.

### Link to public reproduction project repository

https://github.com/Czapek83/Chinese_LanguageIssue

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16.7.7, IOS 17.4.1

### Did you find any workaround?

Unfortunatelly, not at all.

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-macios#20626

**Comment by rolfbjarne** [comment]
I can reproduce this.

Adding the following in the managed Main method:

```cs
Console.WriteLine ($"CurrentCulture: {Thread.CurrentThread.CurrentCulture.Name}");
Console.WriteLine ($"CurrentUICulture: {Thread.CurrentThread.CurrentUICulture.Name}");
Console.WriteLine ($"NSLocale.CurrentLocale.LocaleIdentifier: {NSLocale.CurrentLocale.LocaleIdentifier}");
Console.WriteLine ($"NSLocale.CurrentLocale.CountryCode: {NSLocale.CurrentLocale.CountryCode}");
Console.WriteLine ($"NSLocale.CurrentLocale.LanguageCode: {NSLocale.CurrentLocale.LanguageCode}");
Console.WriteLine ($"NSLocale.CurrentLocale.ScriptCode: {NSLocale.CurrentLocale.ScriptCode}");
```

prints:

```

CurrentCulture: zh-CN
CurrentUICulture: zh-CN
NSLocale.CurrentLocale.LocaleIdentifier: zh-Hant_CN
NSLocale.CurrentLocale.CountryCode: CN
NSLocale.CurrentLocale.LanguageCode: zh
NSLocale.CurrentLocale.ScriptCode: Hant
```

Debugging a bit it seems we hit this code path:

https://github.com/dotnet/runtime/blob/994a410b4478eef496bd230f6d95f576d4aff6d7/src/native/libs/System.Globalization.Native/pal_locale.m#L27-L30

which means the current (ui) culture is determined using the current locale's LanguageCode-CountryCode (which results in "zh-CN"), not the locale's LocaleIdentifier, nor taking into account the ScriptCode value (which both contain "Hant").
