### ISSUE TITLE
Dragging a file from Explorer over top of the application window will launch another process

### ISSUE THREAD

**Issue by jschick04** [dotnet/maui#22556]
### Description

I am working on a project that is basically an alternative to the Event Viewer MMC snap-in where we load evtx files and parse and display those events. Recently, I have noticed that dragging and dropping a .evtx files onto the application window is now launching an additional application process. If go into settings and change the .evtx extension default handler back to the Event View MMC then dragging and dropping a file onto the window will launch the Event Viewer MMC snap-in.

There have been no code changes to how we handle OnDrop or OnDragging and I have not been able to pinpoint any specific change around when this issue started. If I install a previous version of the app before the issue started then it does not repro but if I roll back to the commit tied to that release then I can reproduce the issue again. I have also tested previous .NET SDK versions with no success.

My suspicion is that it may be tied to the fix for the following issue that was recently resolved but do not have any hard evidence against this right now.
https://github.com/microsoft/microsoft-ui-xaml/issues/7366

I have been able to reproduce this issue on a clean MAUI Hybrid project in VS 17.9.

### Steps to Reproduce

1. Create New Project > .NET MAUI Blazor Hybrid App
2. Add the following to MainPage.xaml inside BlazorWebView
```
<BlazorWebView.GestureRecognizers>
    <DropGestureRecognizer AllowDrop="True" />
</BlazorWebView.GestureRecognizers>
```
3. Run the app and drag a file over the window and 2 ghost icons will show up
![image](https://github.com/dotnet/maui/assets/17906967/4ad61bce-b9ca-4405-b773-8efe82a46d00)
4. Release the mouse button and the default application for the extension of the file being dragged will be launched. In the case of the above screen shot, dragging a .PML file over the window and releasing will launch procmon

Expected Outcome:
App should be able to handle this file via OnDrop and no other applications should be launched 

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No workaround at this time

**Comment by mattleibow** [comment]
@Eilon how does the blazor web view handle things being dropped onto it? It seems weird that a new app instance would launch, but also the extension differences somehow tells me that the OS is getting a launch request?

**Comment by jschick04** [comment]
If it helps, it seems like it may be EmbeddedBrowserWebView!base::LaunchProcess that is making the call to CreateProcess that results in the default extension handler in windows launching based on the extension.

```
kernel32.dll!CreateProcessWStub
windows.storage.dll!CInvokeCreateProcessVerb::CallCreateProcess
EmbeddedBrowserWebView.dll!base::LaunchProcess
EmbeddedBrowserWebView.dll!embedded_browser_webview::internal::WebViewFactory::EnsureConnection
EmbeddedBrowserWebView.dll!embedded_browser_webview_current::EmbeddedBrowserWebView::CreateWebViewOnIOThread
<snip>
```

**Comment by Eilon** [comment]
The BlazorWebView itself doesn't do anything with drag/drop as far as I know. But it could be that to drop onto a WebView2 you have to write code in the HTML world to react to that? Or perhaps there's some WebView2-specific API that needs to be used to implement it (though I couldn't find anything for that in particular)? I'm not sure how the .NET MAUI Gestures interact with WebView2, so it could be that they are not compatible.

**Comment by Eilon** [comment]
And indeed according to https://github.com/microsoft/microsoft-ui-xaml/issues/7366#issuecomment-2011200143, this type of scenario _should_ be possible starting with WinAppSDK 1.5, but I couldn't find details on how to use it - so maybe there are no .NET APIs for it and it's really up to the app to implement the 'drop' functionality in the JavaScript world (which, with Blazor, might be possible using C# instead of JS).

Either way I think this comes down to being a WebView2 usage question, so I am closing this issue because there is no .NET MAUI or Blazor issue to be fixed as far as I can tell. If there is a need for more info on WebView2-specific features, I recommend continuing the discussion in the https://github.com/microsoft/microsoft-ui-xaml/ repo.
