### ISSUE TITLE
[Spec]  Should BorderWidth be converted to Thickness?

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#2256]
Should the controls which implement IBorderElement and have a uniform border width specified by `double BorderWidth` be converted to use a `Thickness` instead?

**Comment by mattleibow** [comment]
How would this work when it comes to corners? Will we have a transitions between the edges?

**Comment by AmrAlSayed0** [comment]
@mattleibow like this https://codepen.io/XXISerenaIXX/pen/YzxOLwm ?

**Comment by YZahringer** [comment]
please re-open it
