### ISSUE TITLE
Unable to debug MAUI android source code as it contains the bug because VS 2022 cannot find source symbol files

### ISSUE THREAD

**Issue by devhls** [dotnet/maui#22577]
### Description

When I set breakpoint in the maui-android source code of the MAUI project I can't reach it because the following error is displayed:

No compatible code running on the thread. 

`The selected debug engine does not support any code executing on the current thread (e.g. only native runtime code is executing). You can switch to another thread to see if there is compatible code running`

I did not test other platforms. Probably this does not work there too.

### Steps to Reproduce

1.Open Microsoft.Maui.Controls.ContentPage. 
2.Set a breakpoint in the class constructor.
3.Run android app in debug mode (emulator or local device wifi-debugging).
4.Open a content page.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No, there is no clue after several days with it.

**Comment by drasticactions** [comment]
The MAUI UI Framework team does not maintain the debugger tooling, it's maintained by the Visual Studio team. If you ask there, they could help you out.

**Comment by beefydog** [comment]
Just started to happen to me. Code, unchanged, ran just fine yesterday, now this! dead in the water
