### ISSUE TITLE
Cross TabBar navigation broken on iOS

### ISSUE THREAD

**Issue by albyrock87** [dotnet/maui#22570]
### Description

On iOS, using TabBar and navigating to a new Tab also pushing a page onto the navigation stack does not work:
- No exception is thrown
- Task is not completed

```cs
var shell = Shell.Current;
try
{
    // "main" is the `TabBar`
    // "Foo" is a different `ShellContent`
    // "Bar" is a page registered in the `Routing`
    await shell.GoToAsync("//main/Foo/Bar");
}
catch (Exception ex)
{ 
    // Add breakpoint here => not hit
    Console.WriteLine(ex.Message);
}
finally
{
    // Add breakpoint here => not hit
    Console.WriteLine("Finally");
}
```

### Link to public reproduction project repository

https://github.com/albyrock87/maui-shell-issues/blob/main/MainPage.xaml.cs#L14-L28

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

### Did you find any workaround?

No workaround.

**Comment by kubaflo** [comment]
Hi @albyrock87, thanks for your repository! I've made some investigation and this issue is related, but not the same as #16568

The later one is about the navigation inside the 'more' tab and yours is about the navigating between the visible-tabs-in-toolbar. I have a fix for your issue: https://github.com/dotnet/maui/pull/22655

**Comment by albyrock87** [comment]
@kubaflo I also have a fix for my issue: https://github.com/dotnet/maui/pull/22574
anyway, I guess two is better than one 😉
Thanks for looking into it, I appreciate!
