### ISSUE TITLE
Button/ImageButton RippleEffect not working in some cases

### ISSUE THREAD

**Issue by AlleSchonWeg** [dotnet/maui#22603]
### Description

This PR (https://github.com/dotnet/maui/pull/22298) should fix the ripple effect on android. It works in almost every case but there are some cases which don't work.

### Steps to Reproduce

Open repro app. The first three image buttons are not working.

![image](https://github.com/dotnet/maui/assets/6727366/a175c8d5-18a4-4f94-bf36-5cb6fc79eb40)

[MauiApp9.zip](https://github.com/dotnet/maui/files/15416861/MauiApp9.zip)

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by kevinxufei** [comment]
Can repro this issue at android platform on the latest 17.11.0 Preview 1.0(8.0.60-ci.net8.24273.1/8.0.40).

**Comment by AlleSchonWeg** [comment]
The standard buttons also have this behaviour. The problem could be the background color from the button or from the parent element. If the color is white, transparent or not set no ripple is not working.

**Comment by mattleibow** [comment]
Looking at this some more, I see the following with each of the buttons:
 - no background => "use default OS background" - so for image buttons, the OS does not have a ripple
 - transparent => this has a ripple, but it is not visible since the ripple is white and appears under the image
 - white => this has a ripple but it is not visible since the ripple is white and appears under the image
 - color => the white ripple is visible and under the image.

**Comment by mattleibow** [comment]
Since ImageButton has no ripple so it feels wrong, I will make sure it gets a ripple if no background is set.

**Comment by AlleSchonWeg** [comment]
Perhaps it makes sense -if possible- to set a colour for the ripple. If the ripple is always white and is sometimes not visible the user has not the android typical feedback.

**Comment by mattleibow** [comment]
For normal Button, there is a RippleColor property, but for the ImageButton, it is all fake as an image button is not a thing supported by Android and we are using a fancy image control.

But, changing the ripple color sounds like a feature request and we could see about adding that if people want it.

**Comment by AlleSchonWeg** [comment]
> For normal Button, there is a RippleColor property
Interesting. I didn't know that. Is this accessable via platform specific code: `On<Android>()` or via handler?

Thank you

**Comment by mattleibow** [comment]
This is not really a xplat feature, so we don't have an api for it. But, if you want you can add your own mapper for Android. And maybe even your own attached property - or even an effect to not have to do anything.

```cs
PlatformView.RippleColor = color.ToPlatform();
```

That in an effect is all that is needed.
