### ISSUE TITLE
[Bug] Android looks like it has a rounding different when apply Corner Radius vs iOS

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#2261]
### Description
![50BC4735-E985-4EF9-BB70-7D9D2EBE0580](https://user-images.githubusercontent.com/5375137/130858262-e8be7385-efac-4ca1-bd33-ababa639c26b.GIF)

**Comment by v-longmin** [comment]
@PureWeen Could you share your repro project/solution, thanks?

**Comment by jsuarezruiz** [comment]
This issue is already fixed. I am going to close this issue but open a new one if can reproduce the issue again or find a another one.
