### ISSUE TITLE
How are we doing in the repo? Survey inside!

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#22623]
![image](https://github.com/dotnet/runtime/assets/6385855/bd3fe7e2-61e5-477f-af0f-980a62ab3d04)

It's been several months since the last survey and we'd like to hear from you how we're doing.

`https://www.surveymonkey.com/r/73LFZ67` (survey is now CLOSED - 2024-05-31)

If you are reading this, we'd welcome your input. There's only one question so it should take just seconds. But we'd also welcome your suggestions in the optional text box as well.

Some updates we've made based on the [last survey's results](https://github.com/dotnet/maui/issues/17556) are:

* Clarified which branches to use for which work #20543
* Improved docs on using nightly builds of .NET 8 updates: #20159 and https://github.com/dotnet/maui/wiki/Nightly-Builds
* Updated `area-` labels to help with issue organization
* Enabled a "Similar Issues Bot" to help identify related or duplicate issues ([example here](https://github.com/dotnet/maui/issues/22273#issuecomment-2098845063))

We will share results once the survey is closed (in about a week).

-- dotnet/maui maintainers

**Comment by Eilon** [comment]
Hello everyone and thank you for all the feedback and responses! We had 35 responses in all, and the survey is now closed.

The NSAT result, which calculates net satisfaction, was 51 (out of a maximum 200). This is a slight improvement from [last survey's result of 48](https://github.com/dotnet/maui/issues/17556#issuecomment-1760184814).

| Survey                             | NSAT |
| ---------------------------------- | ---- |
| NSAT (spring 2022)                 | 103 |
| NSAT (spring 2023)                 |  76 |
| NSAT (fall 2023)                      |  48 |
| **NSAT (spring 2024 - this survey)** |  **51** |

24 responses included optional comments, which I've summarized:
		
**Contribution challenges:**
* Difficult to contribute due to complex build process
* More tests to prevent regressions
* PRs with label=perf remain open for a long time, which is wasteful
* Request for tutorial on contributing to .NET MAUI with VS, VS Code, and Rider
* Not clear how to contribute to MAUI, which tools to use
* Unclear what is in the nightly builds, perhaps could have release notes with list of fixes
		
**Issue management:**
* (6) Issue milestone/labels/prioritization is unclear, when will an issue be fixed
* (3) Various old/important bugs are not fixed
* (1) Lack of responses on status of issues, progress made on issues, for example:
  * Lack of issue response even when a lot of effort was put into creating the issue with a quality repro
  * Resorting to making local fixes because submitting a PR gets no action
		
**Other:**
* (10) General issues with .NET MAUI itself (as opposed to the GitHub repo)
   * Several responses included mentions of quality issues in .NET MAUI. While this survey was focused on the dotnet/maui repo itself, these responses were also reviewed

All the raw responses will be shared with the .NET MAUI team. As we work on ways to resolve some of these issues, we will do our best to keep people posted.

I'll leave this issue open for a while longer so that it has more visibility.

**Comment by jonmdev** [comment]
Thank you for listening. We are all of us here submitting bug reports because we are fully invested and hoping for many years of solid Maui performance to come.

**Comment by Eilon** [comment]
Thank you everyone for the responses and the healthy discussion. We are working on improving things based on the feedback and we will see you in the next survey.
