### ISSUE TITLE
RemovePage by Name

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2263]
Hi,

Please provide an easy way to remove a page from the Navigation Stack so it can be removed by name like this:

Navigation.RemovePage(PAGENAME)

Navigation.RemovePage<ContentPage>(PAGENAME)

or any other method..

This will make it easier to remove the page by name from anywhere in the app.

Thanks,
Jassim

**Comment by jfversluis** [comment]
I would love to see a more elaborate request for details on why and how you would want to use this. For now, this has too little detail to be considered I think, sorry.

**Comment by jrahma** [comment]
> I would love to see a more elaborate request for details on why and how you would want to use this. For now, this has too little detail to be considered I think, sorry.

Let say we have the following steps.

1. You are on HomePage
2. Click New to add a Post
3. It will PopModal a NewPost page
4. Enter the details and click Save
5. Once you click Save it will Open MyPost page
6. When MyPost page you will need to close the NewPost page

and it become more complex when you open PostGallery after NewPost and then you open MyPost then you need to close both NewPost and PostGallery.
