### ISSUE TITLE
Unable to scroll Horizontal GridItemsLayout in CollectionView with a mouse wheel

### ISSUE THREAD

**Issue by davidsebesta1** [dotnet/maui#22659]
### Description

Hello, I am having issue with CollectionView scrolling. ItemLayout is set to
```xaml
<CollectionView.ItemsLayout>
    <GridItemsLayout Orientation="Horizontal" Span="2" HorizontalItemSpacing="10" VerticalItemSpacing="5"/>
</CollectionView.ItemsLayout>
```
Every other option works just fine _(linear vertical/horizontal and vertical grid layouts)_. But I am unable to scroll this one with a mouse wheel. Using touchpad or manually moving with horizontal bar works.

Whole CollectionView is wrapped inside of a grid. Changing it to other things doesnt help.
Thanks.

### Steps to Reproduce

1. Create a CollectionView with 
```xaml
<CollectionView.ItemsLayout>
    <GridItemsLayout Orientation="Horizontal" Span="2" HorizontalItemSpacing="10" VerticalItemSpacing="5"/>
</CollectionView.ItemsLayout>
```
2. Fill it with data
3. Try scrolling with a mouse wheel

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows Framework 10.0.19041.0

### Did you find any workaround?

No

**Comment by RoiChen001** [comment]
Can repro this issue at the Windows platform on the latest 17.11.0 Preview 1.0(8.0.20/8.0.21).

Sample project:
https://microsoft-my.sharepoint.com/:f:/p/v-chenda/EoQz0ApqtjhHs4FsRaJyRfYBOrTNYPtK2xhYY_AqkZNlhQ?e=E51UfJ
