### ISSUE TITLE
[iOS] Tooltip doesn't work

### ISSUE THREAD

**Issue by dartasen** [dotnet/maui#22658]
### Description

`Tooltip.Text=""` used to display tooltip while long pressing a view doesn't seem to show up on Apple devices, while being fully functional on Android

### Steps to Reproduce

* Create a new MAUI app
* Add a tooltip with `ToolTipProperties.Text="Hello"` on any control
* Run on iOS
* Hover or long click and observe no tooltip

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.x

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.0 (8.0.40 & 8.0.3). Can repro it on android and iOS platforms, Note windows platform works fine.

**Comment by mattleibow** [comment]
> On iOS, to show a tooltip your app must be an iPhone or iPad app running on a Mac with Apple silicon. Providing this criteria is met, tooltips are displayed when the pointer is positioned over the view for a few seconds, and remain visible until the pointer moves away from the view. Tooltips on iOS require the use of iOS 15.0+. For more information about using iPhone and iPad apps on a Mac with Apple silicon, see [Use iPhone and iPad apps on Mac with Apple silicon](https://support.apple.com/guide/app-store/fird2c7092da/mac).

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/tooltips?view=net-maui-8.0

It appears that iOS does not have a gesture to display tooltips. If you were to connect a keyboard or mouse to the iPad the tooltips should display.
