### ISSUE TITLE
[Enhancement] Maui controls demo app

### ISSUE THREAD

**Issue by taozuhong** [dotnet/maui#2269]
## Summary
We need a Maui controls demo app like GTK demo,

it will show control examples with themes, and show the source code to demonstrate the control.

**Comment by jsuarezruiz** [comment]
Something like https://github.com/dotnet/maui/tree/main/src/Controls/samples/Controls.Sample/Pages?

**Comment by jsuarezruiz** [comment]
Let me know if you are thinking in something different. I am going to close the request for now if you mean have a gallery app, but feel free to let me know if is something different and we can reopen it!
