### ISSUE TITLE
Unable to Login with Social  Media  like Facebook 

### ISSUE THREAD

**Issue by lakhan-bairawat** [dotnet/maui#22704]
### Description

i am unable to implement  login with Facebook and Apple ,
like Xamarin Forms.
Could you please suggest any alternative  way to achieve this.   

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.20 SR4

### Affected platforms

iOS, Android

**Comment by moljac** [comment]
Thanks for the feedback, but we'll need more info. Information you provided is not enough to investigate what is going on.

Even better: small repro sample would help a lot.

Thanks
regards

**Comment by lakhan-bairawat** [comment]
Facebook Login not supporting,
please suggest

**Comment by lakhan-bairawat** [comment]
please share any small sample with Facebook login implemented in maui .net 8

**Comment by RoiChen001** [comment]
@lakhan-bairawat Sorry for the delay, does your problem still exist? Please refer to https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?view=net-maui-8.0&tabs=android to see if it helps you?
