### ISSUE TITLE
Add Translucent Status Bar Setter to Community Toolkit

### ISSUE THREAD

**Issue by lakhan-bairawat** [dotnet/maui#22706]
### Description

Enhance the Community Toolkit with a feature to easily set the status bar to be translucent in .NET MAUI applications. This addition would simplify the process for developers who wish to achieve a translucent status bar without managing different platform-specific services.

### Public API Changes

<ContentPage.Behaviors>
        <toolkit:StatusBarBehavior StatusBarColor="Fuchsia" StatusBarStyle="LightContent" />
    </ContentPage.Behaviors>

### Intended Use-Case

in my app i requires  translucent status.

**Comment by MitchBomcanhao** [comment]
perhaps you should be adding this to the community toolkit repo, then? 😉

**Comment by drasticactions** [comment]
This repo is for the MAUI UI Framework. If you would like to request features for the CommunityToolkit, you should ask in [their repo](https://github.com/CommunityToolkit/Maui).
