### ISSUE TITLE
Image File Size Increases Excessively Upon Saving on iOS Platform

### ISSUE THREAD

**Issue by VishalOmprasad** [dotnet/maui#22708]
### Description

When saving an image in iOS platform (by encoding the image using UIImage.AsJPEG()), there is a significant increase in the image's size compared to the image's original size. For example, an image with a size of 300KB is being saved with a size of 500KB or more. The image’s size also increases even when providing/passing the compression quality as a parameter directly to the UIImage.AsJPEG() method.

### Steps to Reproduce

1. Create a new .NET MAUI Application.
2. Add the image and button control in your MainPage.xaml
```
<Grid RowDefinitions="*, auto">
    <Image x:Name="image"
           Source="testimage_a.jpg" />
    <Button Text="Save"
            WidthRequest="150"
            Clicked="OnSaveButtonClicked"
            Grid.Row="1" />
</Grid>
```
3. Add the following code snippet in the Button.Clicked event handler in the MainPage.xaml.cs.
```
if (this.image != null && this.image.Handler != null && this.image.Handler.PlatformView is UIImageView uiImage)
{
    var nativeImage = uiImage.Image;
    if (nativeImage == null)
    {
        return;
    }

    var formattedImage = nativeImage.AsJPEG();
    if (formattedImage == null)
    {
        return;
    }

    Stream? stream = formattedImage.AsStream();
    if (stream == null || stream == Stream.Null)
    {
        return;
    }

    string downloadFilePath = "/Users/syncfusion/Downloads";
    string filePath = Path.GetFullPath(Path.Combine(downloadFilePath, "IosImage.jpeg"));

    NSData? imageData = NSData.FromStream(stream);
    if (imageData != null)
    {
        imageData.Save(filePath, false, out NSError? nsError);

    }
}
```
4. Deploy the sample in iOS platform.
5. Click the button.
6. Notice, the size of the saved image is greater than the image’s original size. (eg: image of size 200 KB has increased to 450 KB, image of size 3 MP has increased to 5.7 KB, etc.,)

### Link to public reproduction project repository

https://github.com/VishalOmprasad/Image-Save-Issue-iOS

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

**Comment by drasticactions** [comment]
This isn't a MAUI bug. "AsJpeg" is a UIKit extension method.

<img width="692" alt="スクリーンショット 2024-05-29 21 03 58" src="https://github.com/dotnet/maui/assets/898335/6a8332bd-0928-4937-be90-f1b7e739dbe2">

It takes in a compression value. Right now you're not setting it, so it's effectively 100%. You would hit the same thing if you did this in ObjectiveC or Swift with UIKit.
