### ISSUE TITLE
Scanner is not working with iOS Maui.

### ISSUE THREAD

**Issue by lakhan-bairawat** [dotnet/maui#22705]
### Description

Scanner is not working with iOS Maui.
but its working fine in android and i used below plugin for this.
            
xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI.Controls"

please suggest !!

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS all versions

**Comment by moljac** [comment]
Thanks for the feedback, but we'll need more info. Information you provided is not enough to investigate what is going on.

Even better: small repro sample would help a lot.

Thanks
regards

**Comment by lakhan-bairawat** [comment]
this issue resolved, use below code if you have   this issue
<zxing:CameraBarcodeReaderView x:Name="scanView"
                                   BarcodesDetected="scanView_OnScanResult"                                     
                                     VerticalOptions="FillAndExpand"
                                     HorizontalOptions="FillAndExpand"
                                 AbsoluteLayout.LayoutBounds="0, 0, 1, 1" AbsoluteLayout.LayoutFlags="All"/>
