### ISSUE TITLE
[Bug] Change Android Image Handler to Load into view instead of loading a drawable

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#2271]
### Description

Currently for the Android Image Handler implementation we are always loading the drawables into managed code and then setting the drawable directly on the ImageView. We should be using the Glide APIS to pass the (filename/uri/etc... ) directly into glide along with the ImageView and then glide will just handle loading the image without ever having to bring it over the bridge.

We should also look at the possibility of always passing in the destination view to glide. The glide setup code takes a `.With(view)` parameter that lets you scope/size the glide command to the same view. This will cause glide to manage the life cycle/caching of the images more effectively

#### Windows Consideration
- Currently when loading images on WinUI we are setting "CompleteLoaded" on retrieval of the IImageSourceResult. In `Xamarin.Forms` we were connecting `Loaded` to the actual `Loaded` event of the Image control. We will probably want to re-use the structures for Android with WinUI so that the "Loaded" event will be more accurate

**Comment by mattleibow** [comment]
Main work was done in #5198 and then improved in follow up PRs.
