### ISSUE TITLE
[XamlC] Produce warning when Binding inside of DataTemplate inherits x:DataType from outside of the template

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/maui#22714]
I think XamlC should produce a warning when there is a `{Binding ...}` inside of a `DataTemplate` which inherits `x:DataType` from outside of the template. Consider the following example:

```xml
<ScrollView x:DataType="local:PageViewModel">
    <StackLayout BindableLayout.ItemsSource="{Binding Items}">
        <BindableLayout.ItemTemplate>
            <DataTemplate>
                <Label Text="{Binding .}" />
            </DataTemplate>
        </BindableLayout.ItemTemplate>
    </StackLayout>
</ScrollView>
```
- XamlC won't report any warning
- The `Text` property will contain a `TypedBinding<PageViewModel, PageViewModel>` and when the item will have a different type, the label will be empty without producing any warning (https://github.com/dotnet/maui/pull/22056)

My suggestion is to report a warning something like
```
XC0024: Binding might be compiled incorrectly because it is using an x:DataType local:PageViewModel that is defined outside of the current DataTemplate scope. Consider adding x:DataType directly to the DataTemplate. See https://learn.microsoft.com/dotnet/maui/fundamentals/data-binding/compiled-bindings for more information.
```
... and add a paragraph describing this issue to the linked documentation page.

Related to https://github.com/dotnet/maui/pull/22056

/cc @StephaneDelcroix @ivanpovazan @PureWeen @mattleibow

**Comment by ivanpovazan** [comment]
For reference: 
@PureWeen recently fixed an issue with the same root cause in: https://github.com/rachelkang/recipeSearch/commit/b63c3a7e07b9f8942dbd6b0de1dfbdf4b5dc22eb

**Comment by ivanpovazan** [comment]
FWIW: 
Another idea for the warning message could be that our recommendation is to always specify `x:DataType` for bindings in templates explicitly, as if it is omitted it could inherit `x:DataType` from a parent scope and cause runtime failures.

**Comment by simonrozsival** [comment]
The implementation was merged into the `net9.0` branch
