### ISSUE TITLE
NamedFontSize ignores FontAutoScalingEnabled

### ISSUE THREAD

**Issue by nk-alex** [dotnet/maui#22732]
### Description

NamedFontSize ignores FontAutoScalingEnabled configuration. It only works when font size is set using a double value.

### Steps to Reproduce

//Place this on MainActivity used to work on Xamarin. Now it only works when font size is set using double value

```cs
protected override void AttachBaseContext(Android.Content.Context @base)
{
	try
	{
		Configuration configuration = new Configuration(@base.Resources.Configuration);
		configuration.FontScale = 1.0f;
		ApplyOverrideConfiguration(configuration);
		base.AttachBaseContext(@base);
	}
	catch (System.Exception)
	{

	}
}
```

![Screenshot_1717055019](https://github.com/dotnet/maui/assets/101177816/d7603d96-6285-4200-a878-8c4707bbbd9e)

```xml
	<StackLayout Orientation="Vertical">
		<Label Text="One" FontSize="Medium"/>
		<Label Text="Two" FontSize="14"/>
		<Label Text="Three" FontSize="Medium" FontAutoScalingEnabled="False"/>
		<Label Text="Four" FontSize="14" FontAutoScalingEnabled="False"/>
		<Label Text="Five" FontSize="Medium" FontAutoScalingEnabled="True"/>
		<Label Text="Six" FontSize="14" FontAutoScalingEnabled="True"/>
	</StackLayout>
```

![Screenshot_1717055060](https://github.com/dotnet/maui/assets/101177816/57d6acab-cbe1-4c08-98d5-c25a774cf842)

Now we change the system font configuration:

![Screenshot_1717055114](https://github.com/dotnet/maui/assets/101177816/d132205c-a8fe-4c3b-8959-2d09901c48b2)

This is the result:

![Screenshot_1717055147](https://github.com/dotnet/maui/assets/101177816/183667ee-e62a-4352-a564-fb719c3acbcb)

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 21

**Comment by kevinxufei** [comment]
I can't reproduce this issue on 17.11.0 Preview 1.0 (8.0.21), can you share a repo for reference? And can you try again with an emulator/device with a higher Android API version (e.g. api30 and above)? Thanks!
