### ISSUE TITLE
No service for type 'Microsoft.Maui.Controls.Hosting.EffectsFactory' has been registered

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#22748]
### Description

After upgrading from XF I have a couple of custom controls on a page that throw an error:

```
'No service for type 'Microsoft.Maui.Controls.Hosting.EffectsFactory' has been registered.'
```

The stacktrace is https://gist.github.com/davidortinau/46e27e7e7536e1e67dcf68c7bd04e3ca

One is a `ContentView` and the other a `Frame`.

https://github.com/davidortinau/Xappy/tree/maui/Xappy/Xappy/Content/Scenarios/OtherLogin/Controls

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Did you find any workaround?

```
builder.ConfigureEffects(null);
```

Added this in `MauiProgramExtensions.cs` (multi-project setup) and it works now.

**Comment by kevinxufei** [comment]
Verified on 17.11.0 Preview 1.1 (8.0.40/8.0.3). Can not repro this issue.
I commented out ‘**builder.ConfigureEffects(null);**’ and deployed to Android emulaotr (api34/33) & android device (api30), clicked all controls multiple times and changed parameters. But no exception occurred; I wonder if you have other different operations?
