### ISSUE TITLE
[Android] Numeric Editor's cursor is not visible when tapping it inside a ListView

### ISSUE THREAD

**Issue by RicardoValdezT** [dotnet/maui#22745]
### Description

In **Android**, when you tap over a **Editor** which **Keyboard** property is set to **Numeric** and its _inside a ListView_, the cursor just blinks when the numeric soft keyboard appears losing its focus and you need to tap it again.

I have a complex UX which includes a ListView and a variety of components inside this ListView, and i noticed that when one of this items is an Editor of Keyboard type Numeric the focus is lost immediately after tapping it when the App's WindowSoftInputModeAdjust is set to Resize 

When calling: 
_On<Microsoft.Maui.Controls.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(**WindowSoftInputModeAdjust.Resize**);_ method in the application class.

I isolated the issue to a simple layout and the issue still happends.

### Steps to Reproduce

1. Create a New MAUI App.
2. Set the MainPage to contain a ListView with an Numeric Editor as ItemTemplate:
<img width="502" alt="image" src="https://github.com/dotnet/maui/assets/168673188/ee1dc1ba-856b-49ef-b9cb-eb8a8be6ff70">

3. In the code behind for MainPage set the ItemSource for the ListView:
<img width="458" alt="image" src="https://github.com/dotnet/maui/assets/168673188/c244f05f-bc20-4404-b346-a720f96acccc">

4. In the App Application class call UseWindowSoftInputModeAdjust(**WindowSoftInputModeAdjust.Resize**)
<img width="964" alt="image" src="https://github.com/dotnet/maui/assets/168673188/01584178-6741-4cdb-83ea-06454214a09e">

5. Run the project for Android, and click over the Numeric Editor.
6. Notice the cursor just blinks and focus on the editor is lost.

https://github.com/dotnet/maui/assets/168673188/7abc4f9c-70eb-4871-956c-c66f8d766122

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

1. _Set the WindowSoftInputModeAdjust to **Pan**_ solves the issue but the behavior of the appearing keyboard is not the desired.

2. _Putting the ListView Inside a **VerticalStackLayout**_ resolves the issue but modifies your UX.

3. _Setting the **HeightRequest** of the ListView to a fixed value_ resolves the issue but modifies your UX.

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.0 ( 8.0.40 & 8.0.21& 8.0.3 ) Can repro it.

**Comment by kubaflo** [comment]
Hi! It seems to be working fine in Net9
<video src="https://github.com/user-attachments/assets/72c42e99-fbaa-438e-8684-c8402f6f4fbf"/>
