### ISSUE TITLE
Using radiobuttons in a group, pressing one button works fine, but pressing the seconf button does not reset the first hence "blocks" the radio buttons all together.

### ISSUE THREAD

**Issue by SorenBech2** [dotnet/maui#22750]
### Description

As a response to issue #18251 (IllegalArgumentException .NET MAUI 8 RC 2)  Microsoft.Maui.Controls v. 8.0.60-ci.net8.24277.1 has been developed and it fixes the Tabbar issue of #18251. However, it introduces two new issues (as far as our test has unveiled).

Issue 1:
In XAML a border does not expand when a Label inside the border expamds from one to several lines through a bindable variable in code behind.  (Issue easy to identify in repro code)

Issue 2:
Using radiobuttons in a group, pressing one button works fine, but pressing the seconf button does not reset the first hence "blocks" the radio buttons all together. (see repro for demo)

### Steps to Reproduce

To reproduce the issues, download the repro code and follow instructions below.

The code is set up to previous version (8.0.40) where there are no issues (with border nor radio buttons). In order reproduce the issues go to TabbarTest.csproj and follow the instructions below:

      <ItemGroup>
            <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />

            
            <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.40" />
            <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.40" />
            
            
            
            
            
            <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
      </ItemGroup>

When the app is compiled (Android) and launched, press the first tab (Border Test). On the Border Test page press the Yes an No buttons to provoke the issues.

### Link to public reproduction project repository

https://github.com/SorenBech2/TabbarTest

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

Android

### Affected platform versions

Android 13 (have not tested on prior versions

### Did you find any workaround?

No

### Relevant log output

```shell
N/A
```

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.0(8.0.60-ci.net8.24277.1 & 8.0.60-ci.net8.24280.2). Can repro on android platform with sample project. This issue works fine on 8.0.40.
![image](https://github.com/dotnet/maui/assets/77434865/24a8928a-3cb7-4502-8128-28aea0dfa9a3)

**Comment by jfversluis** [comment]
@SorenBech2 of course any report is appreciated, but to track things properly could you please next time report 1 problem per issue? 😊 thanks!

**Comment by PureWeen** [comment]
Made this one about RB
Issue 1 should be fixed on latest nightly

Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by SorenBech2** [comment]
Hi Shane

Issue with border not expanding has been solved in nightly build 8.0.60-ci.net8.24302.1.
Thanks for your help on this.

Issue with RB remains in that version.


Med venlig hilsen / Best regards


Søren Bech

Marmorvej 35

DK-2100 København Ø

+45 4076 5050

***@***.***



________________________________

**Comment by MitchBomcanhao** [comment]
@PureWeen @jsuarezruiz can someone with the relevant permissions delete the PII from @SorenBech2's message above?
