### ISSUE TITLE
(iOS) - Memory Leak in CollectionView with GroupItemTemplate on iOS in MAUI

### ISSUE THREAD

**Issue by Alex-stewart1** [dotnet/maui#22752]
### Description

When using the CollectionView with the GroupItemTemplate and IsGroup functionality, a memory leak occurs on iOS. Specifically, when a data template is added to the CollectionView, it prevents the Page containing the CollectionView from being collected by the Garbage Collector (GC). This issue has been verified on iOS and does not occur on Android.

### Steps to Reproduce

1. Create a new MAUI project.
2. Add a Page with a CollectionView.
3. Configure the CollectionView to use GroupItemTemplate and set IsGroup to true.
4. Add a data template to the CollectionView.
5. Navigate to the Page containing the CollectionView.
6. Navigate away from the Page to allow it to be eligible for garbage collection.
7. Force a GC from somewhere within the app using GC.Collect() and GC.WaitForPendingFinalizers().
8. Use a memory profiler, debugging tools or print to the console from the Page's destructor to check if the Page has been collected by the GC.

### Link to public reproduction project repository

https://github.com/Alex-stewart1/maui-cv-group-bug/tree/main

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Not while maintaining any semblance of the CollectionViews grouped functionality

**Comment by Alex-stewart1** [comment]
This has seemingly been fixed, updating 

<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />

To
 
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.40" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.40" />

Fixed the issue

**Comment by jari-schuurman** [comment]
I also see this issue on windows using the Community Toolkit popup. Popup gets disposed correctly but still increases memory. Tried to not use collectionview = no memory leak
collectionview with itemtemplate defined = memory leak
collectionview without any itemtemplate = no memory leak

Honestly, how are we supposed to use the collectionview and clean up properly? Some documentation and/or examples would be appreciated.
