### ISSUE TITLE
[Enhancement] Color.FromArgb should take each component as parameters of byte

### ISSUE THREAD

**Issue by beto-rodriguez** [dotnet/maui#2279]
## Summary
Currently `Microsoft.Maui.Graphics.Color.FromArgb( string )` takes the color as a hex string.

We should be able to build colors passing each component (a, r, g, b) as byte.

The current behavior is inconsistent with older versions in the dot net framework and other methods in the same class such as `FromRgba(byte, byte, byte, byte)` and `FromRgb(byte, byte, byte)`.

## Intended Use Case

Instead of 

``` c#
var white =  Microsoft.Maui.Graphics.Color.FromArgb("#ffffffff")`;
```

It should be

``` c#
var white =  Microsoft.Maui.Graphics.Color.FromArgb(255, 255, 255, 255) ;
```

**Comment by jsuarezruiz** [comment]
Actually the `Microsoft.Maui.Graphics.Color.FromArgb` method have different options with different parameters:

- Color FromRgba(float r, float g, float b, float a)
- Color FromRgba(double r, double g, double b, double a)
- Color FromRgba(string colorAsHex)

**Comment by beto-rodriguez** [comment]
@jsuarezruiz Notice you mixed the methods, `FromRgba` != `FromArgb `.

The same confusion happened to me, thus I opened this issue.
