### ISSUE TITLE
Maui Blazor app freezes after pressing back button on Android.

### ISSUE THREAD

**Issue by martinstoeckli** [dotnet/maui#22819]
### Description

After pressing the system back button on Android, the app cannot be restarted, it freezes showing the splash screen. The problem can be reproduced with a pure unaltered Maui-Blazor project (but does not occur with a Maui project).

When trying to make the app active again, the `MainActivity.OnCreate()` method is still called but it never makes it to `MainActivity.OnResume()`.

Tested it with different Android emulators:
Android 7 ➽ freezes
Android 10 ➽ freezes
Android 12 ➽ works correctly
Android 13 ➽ works correctly

Tested it also without attached debugger, to avoid problems with HotReload.
The app context switch as proposed in [#22496](https://github.com/dotnet/maui/pull/22496) doesn't solve the problem.

### Steps to Reproduce

1. Create new Maui Blazor .Net 8 project.
2. Start Android Emulator with Android version <= 10
3. Start the new app ➽ startup works correctly, app is shown
4. Press the system ◀ back button ➽ app is stopped and shown in the list of recent apps
5. Reactivate app from list of recent apps ➽ app shows the splash screen and then freezes

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 and lower

### Did you find any workaround?

No unfortunately not.

**Comment by Kebechet** [comment]
I have this problem also on Android 14.0 (API 34)

**Comment by Eilon** [comment]
Hi @martinstoeckli  - this sounds like an issue that many people have run into and we made a recent patch to .NET MAUI 8 where you can enable a workaround for this issue. See https://github.com/dotnet/maui/pull/22496 for full details.

If you are encountering hangs in Android with BlazorWebView, you can enable this [AppContext Switch](https://learn.microsoft.com/dotnet/api/system.appcontext.trygetswitch?view=net-8.0) with one line of code in your app's `MauiProgram.cs`:

```c#
AppContext.SetSwitch("BlazorWebView.AndroidFireAndForgetAsync", isEnabled: true);
```

Make sure you're updated to the latest patch of .NET MAUI, and try out this switch. If it resolves your issue (or not!), please let us know.

**Comment by martinstoeckli** [comment]
I already tested this workaround and mentioned it explicitely in the description, it didn't solve the problem, but I will try again after updating to the newest version.

**Comment by Eilon** [comment]
> I already tested this workaround and mentioned it explicitely in the description, it didn't solve the problem, but I will try again after updating to the newest version.

My apologies for missing that part of your text!

The good news is that this fix wasn't in SR5, but is in SR6: https://github.com/dotnet/maui/releases/tag/8.0.60

So hopefully if you update the MAUI version you're using, then the switch will start 'activating', and I think that should fix the problem.

I'll be more careful to read the whole report next time 😁

**Comment by Kebechet** [comment]
@Eilon is this switch just temp workaround or it will become a part of Maui Blazor template ? In case it is only a workaround what thread we can watch to remove it in the future ?

**Comment by martinstoeckli** [comment]
@Eilon - just updated to Maui 8.0.71 and added the workaround and can confirm that the problem is fixed. Thanks for your work!

**Comment by Eilon** [comment]
> @Eilon is this switch just temp workaround or it will become a part of Maui Blazor template ? In case it is only a workaround what thread we can watch to remove it in the future ?
> 
> Docs: [dotnet/docs-maui#2306](https://github.com/dotnet/docs-maui/issues/2306)

I logged https://github.com/dotnet/maui/issues/24250 to consider changing it.
