### ISSUE TITLE
VS 2022, emulated device, Debug vs Release

### ISSUE THREAD

**Issue by bsdRuf** [dotnet/maui#22825]
### Description

Hello, my issue doesnt make sense to me. I googled for several hours without finding a solution to it.

I am using VS 2022 V 17.9.7 with net8.0 and several NuGets (nothing has any updates available)
- CommunityToolkit.Maui (v9.0.0)
- CommunityToolkit.Maui.Core (v9.0.0)
- Microsoft.Maui.Controls (v8.0.40)
- Microsoft.Maui.Controls.Compatibility (v8.0.40)
- Microsoft.Data.SqlClient
- Microsoft.Extensions.Logging.Debug
- Microsoft.NET.ILLink.Tasks
- EzSmb
- sqlite-net-pcl
- ZXing.Net
- ZXing.Net.Maui
- ZXing.Net.Maui.Controls

My Maui App (Android only atm) works perfectly in the "debug" mode but when I release the app on physical or emulated devices not matter what Android version (12.0 or above) it straight crashes without errors when I try to start it.

### Steps to Reproduce

1. Start the project with debug mode - it starts, the settings page comes up
2. Start the project with release mode - straight crashes

### Link to public reproduction project repository

https://github.com/bsdRuf/first_maui/tree/main

### Version with bug

9.0.0-preview.1.9973

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

What I tried so far:

- Sadly I have no errors that gave me a hint, so I expect it to be a xaml that works diffrent in "release" mode? But i really dont see why it would behave like that
- On StackOverflow I've seen that i could try to [XamlCompilation(XamlCompilationOptions.Skip)] on my Pages. It didnt fix my issue.
- I disabled other plattforms in case this might have been a thing since my interface is just for android (other have the PlatformNotSupportedException)
- Disbaled hot reload
- Checked if all styles are available / have no typo in the Styles.xaml (same for Colors)
- Threw a apk on the device to install (acted the same)

**Comment by RoiChen001** [comment]
Can't repro this issue on the android emulator API34 on the latest 17.10.1(8.0.40/9.0.0-preview.1.9973). When the project is in release mode, the crash will not occur.
