### ISSUE TITLE
Cannot load images on MAUI app

### ISSUE THREAD

**Issue by MatiasGabrielTommasi** [dotnet/maui#22839]
### Describe the bug
I've just updated Visual Studio and installed .Net 8 SDK on my Windows machine, when I create a new MAUI project it's not being able to load any image, even though the default app image

### To Reproduce
go to
File -> new -> proyect -> choose .NET MAUI application -> set the project name -> choose .NET 8.0 long term support -> hit create button -> compile -> hit F5 (run app in local windows machine) -> *the default dotnet_bot.png image is not loaded*

### Exceptions (if any)
No exceptions were thrown

### Further technical details
.NET SDK version 8.0.204
Visual Studio Community 2022 Community version 17.9.6

**Comment by jonathanpeppers** [comment]
Duplicate of https://github.com/dotnet/maui/issues/22839

**Comment by jonathanpeppers** [comment]
> jonathanpeppers, this is not a duplicate og 40514, this one is 40514

Sorry _was there_ an issue opened on the dotnet/maui repo? I just moved it for now.
