### ISSUE TITLE
[Bug] OnMeasure not triggered while dynamically add the children

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#2283]
### Description

I was created the custom layout that holds the custom views(label, button etc.,) and the custom layout placed inside the scroll view. Initially views are rendered correctly, but add the another child view on custom layout dynamically does not trigger the measure and layout. So the newly added view does not shown on layout. I was tried with InvalidateMeasure but it does not triggered the OnMeasure.

### Steps to Reproduce

1.  Create the custom layout holds the list of views and add the custom layout into scroll view
2.  Dynamically add the view to the layout children
3.  Newly added view does not shown on layout.

### Expected Behavior

- OnMeasure will trigger while dynamically add the children

### Actual Behavior

- OnMeasure not triggered while dynamically add the children

**Comment by Sasikumar3595** [comment]
I was created the control with architecture(**parent layout -> scroll view -> layout -> last layout**), i was added the child dynamically in **last layout** and invalidate measure. The measure triggered for **parent layout** measure to measure **scroll view** but **layout** measure and arrange not triggered.

Suggest me to resolve the issue.

**Comment by Sasikumar3595** [comment]
@jsuarezruiz ,

Any update on this?

**Comment by YuqinSong** [comment]
Not reproducible on 17.2.0 Preview 2.0 [32214.334.main]. Dynamically add the view to the layout children, newly added view shows on layout.
