### ISSUE TITLE
Disappearing UI in CollectionView on Scrolling (Andriod)

### ISSUE THREAD

**Issue by NijishaN** [dotnet/maui#22847]
### Description

When scrolling CollectionView and loading more data then scrolling back the UI disappear for previously loaded data. Problem is only on Android (on iOS it works fine).

Initially the UI comes as expected.
![Screenshot_1717577429](https://github.com/dotnet/maui/assets/117098569/be09ff6d-bbd1-4fd8-9c5d-26361e170df1)

After scrolling and loading more data, previously loaded UI has been disappear.
![Screenshot_1717577416](https://github.com/dotnet/maui/assets/117098569/79ecd24f-2898-471d-aec2-1685be63dd5f)

### Link to public reproduction project repository

https://github.com/NijishaN/MauiCollectionViewBug

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

Android

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.1(8.0.40). Can repro it on android platform with sample project.  but (8.0.21) can not repro.

**Comment by PureWeen** [comment]
I tested this on the latest nightly and it's fixed there
So, this will be fixed in SR6

Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds
 
 
![image](https://github.com/dotnet/maui/assets/5375137/59e4e0c6-b5eb-4aef-ad98-080fc7dc681e)
