### ISSUE TITLE
Missing "appxrecipe" Maui Won't Deploy

### ISSUE THREAD

**Issue by dgerding** [dotnet/maui#22842]
### Description

Error DEP1700: The recipe file "G:\QuickJournalSync\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\QuickJournalSync.build.appxrecipe" does not exist. You may need to build your project.

### Steps to Reproduce

Use the repo [here](https://github.com/dgerding/QuickJournalSync) and let me know if you get the error like above:

- "Missing appxrecipe"

I have deleted all bin and obj, cleaned solution and repaired visual studio. No change same result: can't debug app because it won't deploy because "missing recipe".

This may be same phenomenon as:

- [16975](https://github.com/dotnet/maui/issues/16975) 
- [SO](https://stackoverflow.com/questions/76936780/visual-studio-2022-preview-maui-deployment-errors-to-android-devices) 

Any help appreciated. Delete and reinstall VS? 

Thanks in advance for any guidance.

### Link to public reproduction project repository

https://github.com/dgerding/QuickJournalSync

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

no

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP1700: The recipe file "G:\QuickJournalSync\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\QuickJournalSync.build.appxrecipe" does not exist. You may need to build your project.	QuickJournalSync			


Installed Workload Id      Manifest Version       Installation Source            
---------------------------------------------------------------------------------
android                    34.0.95/8.0.100        SDK 8.0.300, VS 17.11.34929.205
aspire                     8.0.1/8.0.100          SDK 8.0.300, VS 17.11.34929.205
ios                        17.2.8053/8.0.100      SDK 8.0.300, VS 17.11.34929.205
maccatalyst                17.2.8053/8.0.100      SDK 8.0.300, VS 17.11.34929.205
maui-windows               8.0.21/8.0.100         SDK 8.0.300, VS 17.11.34929.205
```

**Comment by RoiChen001** [comment]
@dgerding Unfortunately, I tried to download your project but got 404. Can you provide it again? Looking forward to your reply!

**Comment by dgerding** [comment]
@RoiChen001 I fixed the visibility error on the example repo. Thanks! Any help appreciated.

**Comment by RoiChen001** [comment]
Can repro this issue at Windows platform on the latest 17.11.0 Preview 1.1(8.0.40).

**Comment by dgerding** [comment]
@jsuarezruiz What info do you want me to add?

**Comment by dgerding** [comment]
Deleted VS 2022 Preview entirely, restarted machine, reinstalled VS 2022 Preview latest. Deleted all bin, obj and vs folders in project. Build still failing. 

This is a blocking issue for me because I can't get support from 3rd party vendor (SF referenced lib in project) if I can't even provide them with a solution that will deploy to test and debug.

Any help appreciated or suggestions about other approaches. 

![image](https://github.com/dotnet/maui/assets/523279/b8d2c422-064d-42c2-826d-936ccbee6ca0)

**Comment by dgerding** [comment]
I cross-posted on SO and the first respond there was somebody bailing on Maui because they are experiencing same bug on a LOB app on .net 8 Maui. Same error. 

Someone please prioritize. 

Happy to helpn any way I can but seems Maui tooling bound way beyond my depth. Any help appreciated.

**Comment by dgerding** [comment]
@MartyIX Thanks for the help. Are you able to get the code to work by setting Packaged or Unpackaged? I'm eventually going to push through windows app store. I'll read the doc you sent. Do you have any related links about how you knew this was the issue? 

Which choice, packaged or unpackaged, worked for you? How did you set it to make it work? (Something I can try?) And thanks!!

**Comment by dgerding** [comment]
@MartyIX Checking now. Thanks!

**Comment by dgerding** [comment]
@MartyIX This DOES fix it. I'm going to plaster this thread and my SO thread with lots of "appxrecipe missing" check Windows publish property in project file. Also going to advocate for updating the error message to include a note to check the publishing status? again, thanks!
