### ISSUE TITLE
Setting a Style With TargetType="Border" Faults at Run Time

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#22862]
### Description

I added a default style for "Border" in `Styles.Xaml`and the resulting Windows app failed to run, throwing an exception with the message "Position 10:37. Type converter failed: Exception has been thrown by the target of an invocation.". Interestingly the generated `Styles.Xaml` has no style definition for `Border` but does for the non=preferred alternative `Frame`.

### Steps to Reproduce

1. Create a new MAUI App targeted at .NET 8
2. Open up Styles.Xaml and add (I added it before the `Frame` style, but I suspect it does not matter):
``` XAML
    <Style TargetType="Border">
        <Setter Property="StrokeThickness" Value="2" />
    </Style>
```
3. Build and run it on Windows - the app should fault during initialization.

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

### Did you find any workaround?

Adding an x:key specification seems to prevent the bug but changes the semantics.

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.1(8.0.40 & 8.0.21 & 8.0.3). Can repro it.
![image](https://github.com/dotnet/maui/assets/128687574/5767a0b6-6cab-4aca-8c4a-da64b0b369aa)
This shouldn't be a problem
The definition of Border already exists in Styles.Xaml file in line 16. If you need to add something else, you need to add x:Key

**Comment by david-maw** [comment]
You're absolutely correct, I've no idea how I missed that, but thanks, I can just edit the style that's there rather than incorrectly trying to add one.

That means the bug is not about a default Border style at all. The actual bug is that if you try and set a default style for the same TargetType twice you get a weird run time error rather than what should be a straightforward compile time error.

Interestingly I also noted that the list of TargetType vlues in the generated Styles.Xaml is _almost_ in Alphabetical Order, as if it started out that way and a few things got inserted in random places.

**Comment by david-maw** [comment]
I submitted #23225 to report the actual issue.
