### ISSUE TITLE
[WinUI] Displaying an `ActionSheet` does not expand

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#22885]
### Description

When showing an `ActionSheet` on `Windows`, the size is not updated if the content is longer as the window itself.

```cs
await Shell.Current.DisplayActionSheet("Title of action sheet", "Cancel is not short", "Delete is also very long...", ["A very long item to select from the action sheet"]);
```

![image](https://github.com/dotnet/maui/assets/2952443/6dc5c30f-6f4b-46a8-8aab-cd61f7922e7e)

The dialog window has enough space to expand, but it always stays the same size.

### Steps to Reproduce

1. Check the repro
2. Run on Windows and click the `Counter` button

### Link to public reproduction project repository

https://github.com/AndreasReitberger/MauiAppActionSheetIssue

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.1 (8.0.40 & 8.0.21). Can repro on Windows platform with sample project.
