### ISSUE TITLE
MAUI Blazor project created earlier in .Net 7 is not launching now with VS 17.10.1

### ISSUE THREAD

**Issue by gbthakkar** [dotnet/maui#22888]
### Description

I see that, it take infinite time to lunch android emulator .. and never deploy the project to 

### Steps to Reproduce

This is existing project created earlier with .Net 7. Even I create a fresh MAUI+Blazor hybrid project using .Net8. It does not work and never been deployed to android emulator.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.100

### Affected platforms

Android

**Comment by jfversluis** [comment]
Thanks for opening this issue, sorry to hear that you're having issues!

I'm afraid this is too little information to diagnose what might be going on. Would you be able to share a screen recording or screenshots at least? Is there something in the log output at all?

**Comment by gbthakkar** [comment]
Hi,
Second day after cold reboot. it started working.
I could not figure out the underlaying cause. So closing it for now.

Thank you for your support and all great work.
