### ISSUE TITLE
Title not updated after OnAppearing for TabbedPage in NavigationPage

### ISSUE THREAD

**Issue by TWEESTY** [dotnet/maui#22899]
### Description

The title of the navigation page is not updated if we set the title after the "OnAppearing" event. We only have the problem with the "TabbedPage", so we don't have it with a classic "ContentPage".
If we set the title inside the "OnAppearing" method, the title is well updated.

The problem exists at least with Android API 33 and 29.
Microsoft.Maui.Controls v8.0.40.

![image](https://github.com/dotnet/maui/assets/1401675/3677b153-8785-402a-9224-df11c2c43e88)

### Steps to Reproduce

1. Create a tabbed page in a navigation page
2. For example, override the "OnAppearing" method inside the TabbedPage with 
```
protected override void OnAppearing()
{
	base.OnAppearing();

    this.Title = "On Appearing Title";

    var timer = Dispatcher.CreateTimer();
    timer.Interval = TimeSpan.FromMilliseconds(2000);
    timer.Tick += (s, e) =>
    {
        MainThread.BeginInvokeOnMainThread(() =>
        {
            this.Title = DateTime.Now.ToString();
        });
    };
    timer.Start();
}
```

Expected : Firstly, the title is "On Appearing Title", then the title is updated every two seconds with the date
Actual : The title is "On Appearing Title", and it doesn't change

### Link to public reproduction project repository

https://github.com/TWEESTY/MAUI_Issue_TabbedPage_Title

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android 10, Android 13

### Did you find any workaround?

No.

**Comment by RoiChen001** [comment]
Can repro this issue at Android platform on the latest 17.11.0 Preview 1.1(8.0.21&8.0.40).
