### ISSUE TITLE
XAML Hot Reload breaks Prism Region application when running with Rider Debugger

### ISSUE THREAD

**Issue by thisisthekap** [dotnet/maui#22900]
### Description

See https://youtrack.jetbrains.com/issue/RIDER-68161/Rider-Xamarin-MAUI-Debug-Regions-are-not-displayed-by-Application for details. Disabling XAML Hot Reload works as workaround.

### Steps to Reproduce

**Taken from https://youtrack.jetbrains.com/issue/RIDER-68161/Rider-Xamarin-MAUI-Debug-Regions-are-not-displayed-by-Application**

## What steps will reproduce the issue?

Create Xamarin project with Prism and use region functionality in debug.

## What is the expected result?

The region view should be properly displayed as it is without debugging.

## What happens instead?

During debugging the regions are not displayed and below errors are logged:

2021-09-23 12:04:44.697 +02:00 [ERR] The region manager does not contain the ThirdStep region.

System.Collections.Generic.KeyNotFoundException: The region manager does not contain the ThirdStep region.

### Link to public reproduction project repository

https://github.com/PrismLibrary/Prism/tree/master/e2e/Maui

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

Disable XAML Hot Reload

**Comment by jfversluis** [comment]
Sounds like this should be fixed on the Rider side, why is this reported here? What am I missing? 😄

**Comment by drasticactions** [comment]
Looking at the issue, this is a Rider XAML Hot Reload issue. The XAML Hot Reload tooling within Visual Studio is separate and not part of MAUI itself. This issue would need to be fixed by Jetbrains. Sorry.

**Comment by thisisthekap** [comment]
Agree. @drasticactions @jfversluis Thank you for your insights/clarification!
