### ISSUE TITLE
[Android] Resolve issues with FlyoutPage recreating the details page whenever it's navigated to

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#22919]
### Description

Make the sample here https://github.com/dotnet/maui/issues/19955#issue-2087000242 work by changing the code [here](https://github.com/dotnet/maui/blob/d91e682cd1da4cbf5651e1002297f7f5c255f398/src/Core/src/Platform/Android/Navigation/ScopedFragment.cs#L31) to `ToPlatform`

If we use `ToPlatform`, that will just update the `MauiContext` with the new FM and LayoutInflater and thus won't recreate the entire details page hierarchy. 

I tried to do that as a fix to #19955 but the life cycles of the FragmentManagers were a bit too complicated to resolve at this point in time

Possible Repro to validate against https://github.com/returnZro/MainFlyout/tree/master

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 7.0(8.0.61 & 8.0.80 & 9.0.0-preview 6). Not repro on Android platform.
