### ISSUE TITLE
MacCatalyst build on mac results in "Unknown Scheme", but iOS build working fine.

### ISSUE THREAD

**Issue by caliberdigitalllc** [dotnet/maui#22942]
### Description

When I build my Maui app (.net core 9 preview 4), the iOS build loads into organizer for test flight deployment fine, but the Mac build loads in as "Unknown Scheme".

<img width="247" alt="image" src="https://github.com/dotnet/maui/assets/59370138/da6d24b0-b172-45dd-aced-3cad8ad319cb">

### Steps to Reproduce

My iOS build command is:
dotnet publish -f net9.0-ios -c Release -p:ArchiveOnBuild=true -p:CodesignKey="ACAA1377B9F55A124AF8FB28BB218352AA3DC7B9" -p:CodesignProvision="ad3e7c5a-dcb6-4834-9841-12e2e79b4f81" -p:CodesignTeamId="8DVSMQ7G8N"

Which is working perfect. I get a build I can send to TestFlight, and all is well.

The Mac command, I have tried countless iterations of this command with various parameters being changed based on googling, and no luck.

dotnet publish -f net9.0-maccatalyst -c Release -p:MtouchLink=SdkOnly -p:UseHardenedRuntime=true -p:CreatePackage=true -p:EnableCodeSigning=true -p:EnablePackageSigning=true -p:ArchiveOnBuild=true -p:CodesignKey="Apple Distribution: AlzBetter LLC (8DVSMQ7G8N)" -p:CodesignProvision="0d81ee50-7a46-44e6-8f61-5671fa4a92fa" -p:CodesignTeamId="8DVSMQ7G8N" -p:CodesignEntitlements="Platforms/MacCatalyst/Entitlements.plist"

My iOS Info.plist (again, this build works great)
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>AlzBetterAI</string>
	<key>XSAppIconAssets</key>
	<string>Assets.xcassets/appicon.appiconset</string>
	<key>CFBundleIdentifier</key>
	<string>com.alzbetterai.app</string>
	<key>CFBundleShortVersionString</key>
	<string>2.0.0</string>
	<key>MinimumOSVersion</key>
	<string>15.0</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app requires access to the microphone to provide voice interaction features.</string>
	<key>NSCameraUsageDescription</key>
	<string>This app requires access to the camera to capture photos and videos for app features.</string>
</dict>
</plist>

versus my mac info.plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    
    
    
    

    
    
    
    
    <key>UIDeviceFamily</key>
    <array>
        <integer>2</integer>
    </array>
    <key>UIRequiredDeviceCapabilities</key>
    <array>
        <string>arm64</string>
    </array>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationPortraitUpsideDown</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>XSAppIconAssets</key>
    <string>Assets.xcassets/appicon.appiconset</string>
    <key>MinimumOSVersion</key>
    <string>15.0</string>
    <key>CFBundleIdentifier</key>
	<string>com.alzbetterai.app</string>
	<key>CFBundleShortVersionString</key>
	<string>2.0.0</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app requires access to the microphone to provide voice interaction features.</string>
	<key>NSCameraUsageDescription</key>
	<string>This app requires access to the camera to capture photos and videos for app features.</string>
</dict>
</plist>

### Version with bug

9.0.0-preview.4.10690

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Did you find any workaround?

No

### Relevant log output

```shell
I get no errors. The build comes out successfully with no warnings provided. I see the .pkg file in the release folder.
```

**Comment by drasticactions** [comment]
@rolfbjarne Would this be specific to the MAUI tooling? 

@caliberdigitalllc If you try building a Mac Catalyst app (`dotnet new maccatalyst`) that doesn't implement the MAUI UI Toolkit, can you deploy that to testflight?

**Comment by rolfbjarne** [comment]
> @rolfbjarne Would this be specific to the MAUI tooling?

I don't think so, if this turns out to be a bug, it would probably belong to xamarin-macios.

**Comment by caliberdigitalllc** [comment]
> @rolfbjarne Would this be specific to the MAUI tooling?
> 
> @caliberdigitalllc If you try building a Mac Catalyst app (`dotnet new maccatalyst`) that doesn't implement the MAUI UI Toolkit, can you deploy that to testflight?

That also went to "Unknown Scheme". I did assign the bundle that matched the certificate of course, that was the only change I made to the dotnet new template that was generated.

**Comment by caliberdigitalllc** [comment]
Just a ping @drasticactions, this has us pretty blocked up.

**Comment by drasticactions** [comment]
@caliberdigitalllc This needs to get moved to [xamarin/xamarin-macios](https://github.com/xamarin/xamarin-macios). This isn't a MAUI bug and can't be fixed here. I don't have the power to do that.

@rolfbjarne (Or anyone with that power) Could you please move this?

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#20714
