### ISSUE TITLE
Resize, when 200% Zoomed Items present under ingredients section are getting truncated: A11y_.NET Core_Recipes App My Recipes Recipe_Recipe Screen_Resize.

### ISSUE THREAD

**Issue by keerthiduvvuri** [dotnet/maui#22969]
### GIT Hub Tags
#AI Limited; #A11yTCS; #A11ySev2; #.NET Core; #E2E-.NET Core-Android-MAUI-JUNE2024; #Talkback; #Android; #WCAG1.4.4; #Resize Text; #FTP; #A11yMAS;

### Environment and OS details:
Android Version 14

### Reproduction Steps

1. Install and open ".NET MAUI" app.
2. Swipe to "My Recipes" and double tap.
3. Swipe to any existing recipe and double tap.
4. "Existing Recipe" Screen will open.
5. Observe that Resize, when 200% Zoomed Items present under ingredients section are getting truncated.

### Actual behavior
Resize, when 200% Zoomed Items present under ingredients section are getting truncated.

### Expected behavior
Resize, when 200% Zoomed Items present under ingredients section should not be getting truncated

### User Impact
Visually impaired users will face difficulty if Resize, when 200% Zoomed Items present under ingredients section are getting truncated..

### Attachments:
[22969_A11y_.NET Core_Recipes App My Recipes Recipe_Recipe Screen_Resize..zip](https://github.com/user-attachments/files/15786585/22969_A11y_.NET.Core_Recipes.App.My.Recipes.Recipe_Recipe.Screen_Resize.zip)

**Comment by RoiChen001** [comment]
Can repro this issue at Android platform on the latest 17.6.12(build 410)(8.0.21&8.0.40).

**Comment by Yash14j** [comment]
GithubTags:#Rev:yaja;

**Comment by tj-devel709** [comment]
I am able to reproduce this but am wondering what the desired behavior is. Would the desired behavior be that the labels go into the next lines?

**Comment by keerthiduvvuri** [comment]
Hi @tj-devel709 yes we are expecting the labels should clearly visible to users in next line or in same line with out any truncations or overlapping.

#Regressed:07-11-24;

**Comment by keerthiduvvuri** [comment]
Verified this bug in latest environment, Issue is Fixed. hence closing the bug. 
Added attachment for reference.
[22969_Closing attachment.zip](https://github.com/user-attachments/files/16943420/22969_Closing.attachment.zip)

#Regressed:09-10-24;
#Closed;
