### ISSUE TITLE
[MAUI]Clicking on the page will trigger opening the page twice and you must return twice before you can return to the original page

### ISSUE THREAD

**Issue by ninachen03** [dotnet/maui#22966]
### Description

Clicking on the page will trigger opening the page twice.

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Android.
2.Click any catalog EG:D Editor.
3.Click return for the first time.
4.Click return for the second time.
![sec](https://github.com/dotnet/maui/assets/128687574/bbf8e304-67bb-4083-a101-f0b6ff58ff12)

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

8.0.60/8.0.3/9.0.0-preview.5.24307.10
### Is this a regression from previous behavior?
We guess this has nothing to do with the SDK, since the app was working before this PR [!55634](https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml/commit/fcd4b8cf71b9667e946c9d749d3556e9136327a7?refName=refs%2Fheads%2Fmain)  was submitted.

### Affected platforms

iOS, Android, Windows

**Comment by XamlTest** [comment]
@ninachen03 The [PR](https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml/pullrequest/557230) fixed the issue, please verify again.

**Comment by ninachen03** [comment]
> @ninachen03 The [PR](https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml/pullrequest/557230) fixed the issue, please verify again.
Thanks, it works fine today.
