### ISSUE TITLE
AndroidAttachDebugger=true causes app to crash, but AndroidAttachDebugger=false doesn't.

### ISSUE THREAD

**Issue by richaplinvs** [dotnet/maui#22979]
### Description

I have installed 9.0.0-preview.4.24260.3 and I am having trouble running my application on Android. Any time the -p:AndroidAttachDebugger=true is set then the app runs but closes a second later. Setting it to -p:AndroidAttachDebugger=false and the app works fine.

I used the command line, dumped during compilcation, to change the AndroidAttachDebugger value, and ran it manually from the command line.

e.g.

`dotnet build -t:Run -p:Configuration=Debug -f net9.0-android -p:AdbTarget=-XYZ -p:AndroidAttachDebugger=false -p:AndroidSdbTargetPort=56946 -p:AndroidSdbHostPort=56946 -p:CustomAfterMicrosoftCSharpTargets="/Users/me/.vscode/extensions/ms-dotnettools.dotnet-maui-0.12.42-darwin-arm64/dist/resources/Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile="/var/folders/rx/ngjhd49d78lg2jq012by2k800000gn/T/dotnet-maui/maui-vsc-f2694a9b-6222-4c53-8c89-42a7a2d108f8.json" -p:AndroidSdkDirectory="/Users/me/Library/Android/sdk" -p:JavaSdkDirectory="/opt/homebrew/opt/openjdk@17" /Users/me/MyProject/MyProject.csproj 
`
`dotnet build -t:Run -p:Configuration=Debug -f net9.0-android -p:AdbTarget=-XYZ -p:AndroidAttachDebugger=true -p:AndroidSdbTargetPort=56946 -p:AndroidSdbHostPort=56946 -p:CustomAfterMicrosoftCSharpTargets="/Users/me/.vscode/extensions/ms-dotnettools.dotnet-maui-0.12.42-darwin-arm64/dist/resources/Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile="/var/folders/rx/ngjhd49d78lg2jq012by2k800000gn/T/dotnet-maui/maui-vsc-f2694a9b-6222-4c53-8c89-42a7a2d108f8.json" -p:AndroidSdkDirectory="/Users/me/Library/Android/sdk" -p:JavaSdkDirectory="/opt/homebrew/opt/openjdk@17" /Users/me/MyProject/MyProject.csproj 
`

The logcat output doesn't give too much away - `I ActivityManager: Force stopping com.appid.app appid=10340 user=0: from pid 31443`.

Even going back to .net 8.0.301, I now get the same behaviour.

### Version with bug

9.0.0-preview.4.10690

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.40 SR5

### Affected platforms

Android

### Did you find any workaround?

Only running the command line with -p:AndroidAttachDebugger=false but this doesn't allow for debuging.

**Comment by drasticactions** [comment]
If you try this on a .NET Android app that doesn't use the MAUI UI Framework (`dotnet new android`) does the same behavior happen?

**Comment by richaplinvs** [comment]
> If you try this on a .NET Android app that doesn't use the MAUI UI Framework (`dotnet new android`) does the same behavior happen?

No, it runs fine using the android plugin (adelphes.android-dev-ext). So must be the .net maui VSCode extension. Thanks for the help.
