### ISSUE TITLE
Win platform WebView cannot be release after its parent window get close

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#22972]
### Description

Please see the Reproduce

### Steps to Reproduce

1. Open the sln using VS 2022
2. Press F5 to start debuging
3. Enter 50 or more to the Entry control
4. Click "new windows" Button
5. Close all WebView windows except the MainPage window

Expect result:
Memory should be reduced

Actual result:
Memory does not get reduced

### Link to public reproduction project repository

https://github.com/jingliancui/MAUIWebViewMultipleWinIssue

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

no

### Relevant log output

```shell
no
```

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.1 (8.0.40 & 8.0.21). Can repro on windows platform with sample project.

**Comment by jingliancui** [comment]
@mattleibow @jsuarezruiz @PureWeen 
May I know if any workarounds can be used before this gets fix?
For example manually dispose the control or handler etc...

**Comment by jonathanpeppers** [comment]
@jingliancui for now, can you do something like this in your `Page`:
```csharp
    protected override void OnDisappearing()
    {
        base.OnDisappearing();

        webView.Handler?.DisconnectHandler();
    }
```
This seems to solve the issue in your sample:

![image](https://github.com/dotnet/maui/assets/840039/94e28a6a-d332-4688-8ad8-8651d6eaf7ea)

**Comment by jingliancui** [comment]
Hi @jonathanpeppers 
PlatformView cannot be null here
![image](https://github.com/dotnet/maui/assets/16309962/41bd944a-4467-4121-8fb8-60cf9b110ad6)

**Comment by jingliancui** [comment]
@jonathanpeppers You can try my sample repo, it also can reproduce the exception, even I updated the nuget to latest version.

**Comment by jonathanpeppers** [comment]
This has the fix for the underlying problem, if you are interested:
* https://github.com/dotnet/maui/pull/23540

It would no longer require `DisconnectHandler()` to be called.

**Comment by jingliancui** [comment]
> This has the fix for the underlying problem, if you are interested:
> 
> * https://github.com/dotnet/maui/pull/23540
> 
> 
> 
> It would no longer require `DisconnectHandler()` to be called.

Cool! May I know if the fix will be released at next sr8? Thanks
