### ISSUE TITLE
Cannot publish Windows app package due to sign tool error

### ISSUE THREAD

**Issue by wasker** [dotnet/maui#22985]
### Description

I'm trying to publish a package. At the end of the process, I'm getting an error

```
1>C:\Users\xxx\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(515,5): Error APPX1204: Failed to sign 'mypackage.msix'. SignTool Error: An unexpected internal error has occurred.
```

There're no other details that could help me debug this problem.

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

No workaround.

**Comment by ninachen03** [comment]
I can not repro this issue on the latest 17.11.0 Preview 2.1 (8.0.60 & 8.0.40 & 8.0.21). Repro step as below. Please correct me if my reproduction steps are different from yours. 

1. Create a .NET MAUI App named of "MauiApp"
2. Open Powershell and cd to your project location path 
  Run below code: New-SelfSignedCertificate -Type Custom `
                          -Subject "CN=MauiApp" `
                          -KeyUsage DigitalSignature `
                          -FriendlyName "My temp dev cert" `
                          -CertStoreLocation "Cert:\CurrentUser\My" `
                          -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
3. Add the key to csproject.Add below code to the first PropertyGroup in .csproj file and save: <GenerateAppxPackageOnBuild>true</GenerateAppxPackageOnBuild>
		<AppxPackageSigningEnabled>true</AppxPackageSigningEnabled>
<PackageCertificateThumbprint>xxxxxxxxxx</PackageCertificateThumbprint>
4. Open Developer Command Prompt for VS2022 and cd to your project location path
 Run dotnet publish Mauiapp.csproj -f net9.0-windows10.0.19041.0 -c Release
