### ISSUE TITLE
WebView is not showing web pages properly

### ISSUE THREAD

**Issue by Thorastur** [dotnet/maui#22994]
### Description

The problem is how the webview shows the web pages. It is difficult to explain in words that is why I have added screenshots, I think it will be better understood. 
Basically the problem seems to be that the webview zooms in on the entire page., and many times there are parts of the page that cannot be seen even by scrolling. Furthermore, any page that looks good in any browser does not look good in MAUI webview.
I have discovered that the error started from some updates of nuget packages. I think Microsoft.Maui.Graphics.8.0.7 is good but later not anymore or maybe Microsoft.Maui.Resizetizer.8.0.7 is good but later not anymore.
![noerrorfullscreen](https://github.com/dotnet/maui/assets/44666626/0604d85c-da8f-40ba-ad39-d5a3f6677270)
![google](https://github.com/dotnet/maui/assets/44666626/806d77a7-86d6-4ca4-a936-e84b0b6333e2)
![bugfullscreen](https://github.com/dotnet/maui/assets/44666626/d0759891-77b6-41e2-9590-a2ab08586a94)
![edge2](https://github.com/dotnet/maui/assets/44666626/95c7a39d-496d-41e9-bfcc-ffdc359c46ff)
![bugcompare1](https://github.com/dotnet/maui/assets/44666626/5c48b3c1-d230-47ce-a57e-4fa447040a1e)

### Steps to Reproduce

Create a new MAUI project, load a web page in a webview.
You can see the size of the web page it is different of any browser.
The normal it is the webview show the page like a browser.
I have added two github repositorys
one with the bug: https://github.com/Thorastur/BugShow
one without bug: https://github.com/Thorastur/NoBug

### Link to public reproduction project repository

https://github.com/Thorastur/BugShow , https://github.com/Thorastur/NoBug

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

Yes not update nuget packages

**Comment by RoiChen001** [comment]
Can't repro this issue at Windows platform on the latest 17.11.0 Preview 2.0(8.0.7&8.0.40&8.0.60).
