### ISSUE TITLE
Splash screen and Material Icons not showing correctly on Android Release build, real device.

### ISSUE THREAD

**Issue by sachinkanadia** [dotnet/maui#22999]
### Description

The Android release build of my App does not show the splash screen and material icons correctly.

Here is my release bulld config:
![Screenshot 2024-06-12 at 14 01 53](https://github.com/dotnet/maui/assets/18262347/71d72e9b-7c31-48d7-be97-70685e828aa0)
![Screenshot 2024-06-12 at 14 03 22](https://github.com/dotnet/maui/assets/18262347/cb463b8f-3d26-4693-9aec-81635e4f8ff0)

Here are screen shots of the issues on the release build:
![Screenshot_20240612-140000](https://github.com/dotnet/maui/assets/18262347/c732efc6-ffb2-4f9b-89b3-3d29b8695766)
![Screenshot_20240612-140010](https://github.com/dotnet/maui/assets/18262347/8f5909f9-80f3-487d-865c-3c23dde88d89)
As you can see in the above screen shot the Material Icons show as Chinese.

Here are screen shots of my debug build which works fine:
![Screenshot_1718197914](https://github.com/dotnet/maui/assets/18262347/16ec040d-3ec3-435d-b27a-bafda4157e6c)
![Screenshot_1718197928](https://github.com/dotnet/maui/assets/18262347/e9cb9385-fb20-442c-a235-7114a25167e4)

I have no idea whats causing these issues. Please help and thanks in advance.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android SDK Version 30 upwards.

**Comment by kevinxufei** [comment]
Hi, @sachinkanadia. We are unable to reproduce your issue. Can you upload a sample project for us to verify? Thanks!

**Comment by sachinkanadia-se** [comment]
Hi @kevinxufei ,

I'm not sure how to replicate this issue to another project as I don't know what's causing the problem.

I was hoping if anyone would have ideas of what to check given the behaviour I've described.

Thanks

**Comment by jfversluis** [comment]
If you haven't figured it out yet, could you please add the contents of your csproj file? Make sure that anything sensitive is redacted. We might see something strange in there. I don't think this is a bug in MAUI but rather some weird config somehwere.

**Comment by sachinkanadia** [comment]
@jfversluis I have attached the zipped-up csproj file. Thank you
[LightWork copy.csproj.zip](https://github.com/user-attachments/files/16101539/LightWork.copy.csproj.zip)

**Comment by sachinkanadia** [comment]
@sk1llsh0t that worked! You smashed it! Thanks!

**Comment by sk1llsh0t** [comment]
I don't know that downgrading is the fix. It just needs to be fixed in the latest version.
