### ISSUE TITLE
Can't build MAUI project in Release mode

### ISSUE THREAD

**Issue by SerlokPK** [dotnet/maui#22995]
### Description

I've finished the MAUI project, and tested with both windows and android environments. 
When I got to the last step, creating APK, I've realized that my project isn't building in Release mode.
I've tried disabling AoT and trimming for Release, but still no luck.

This is some of the errors I am facing:

Precompiling failed for C:\Users\Public\score-tracker\obj\Release\net8.0-android\android-arm\aot-in\ScoreTracker.dll with exit code 1.
The specified response file can not be read	ScoreTracker (net8.0-android)	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\targets\Microsoft.Android.Sdk.Aot.targets

### Steps to Reproduce

1. Change mode to "Release"
2. Rebuild solution

### Link to public reproduction project repository

https://github.com/SerlokPK/score-tracker

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 34.0.95

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Did you try building/publishing it from CLI?

<img width="788" alt="スクリーンショット 2024-06-13 17 30 58" src="https://github.com/dotnet/maui/assets/898335/f1cc4201-e0e1-4043-abdb-fb7dec818164">

I ran `dotnet publish --configuration Release -p:TargetFramework=net8.0-android` and it built fine.

**Comment by SerlokPK** [comment]
Tried it yesterday, with the keystore and everything. Tried it today as well, same error 
![image](https://github.com/dotnet/maui/assets/37025473/0b896b0e-d9b4-45fd-8712-66ba476d6b99)

But since it works at your PC, maybe it's due some permissions on my corporal PC, will try it on my personal PC

**Comment by SerlokPK** [comment]
On my personal PC it works, so it must be something related to permissions/ long characters...
