### ISSUE TITLE
Android entry handler not working anymore in .net8

### ISSUE THREAD

**Issue by mknotzer** [dotnet/maui#22997]
### Description

worked in .net7, same issue in PickerHandler and EditorHandler

		EntryHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
		{
			handler.PlatformView.SetPadding(5, 5, 5, 5);

			GradientDrawable oBorder = new GradientDrawable();
			oBorder.SetColor(((Entry)view).BackgroundColor.ToAndroid());
			oBorder.SetCornerRadius(3);
			oBorder.SetStroke(1, Android.Graphics.Color.Rgb(0xDD, 0xDD, 0xDD));

			GradientDrawable oBackground = new GradientDrawable();
			oBackground.SetColor(Android.Graphics.Color.Transparent);
			oBackground.SetCornerRadius(0);
			oBackground.SetStroke(1, Android.Graphics.Color.Transparent);

			handler.PlatformView.Background = new LayerDrawable(new Drawable[2] { oBackground, oBorder });
		});

see https://github.com/dotnet/maui/issues/17448

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.11 Preview 2.0 (8.0.40 & 8.0.21 & 8.0.14). Not repro on android platform.
![android](https://github.com/dotnet/maui/assets/86938401/ad050ae5-9bd1-45f8-8553-61b3e8c49054)
