### ISSUE TITLE
NotificationHubs Version 4.2 Runtime Error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#23009]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NotificationHubs-Version-42-Runtime-Err/10679843)._

---
[severity:I'm unable to use this version]
In Maui, we are getting errors while trying to update the Microsoft.Azure.NotificationHubs' Version='4.2.0'.
According to NuGet Gallery Microsoft.Azure.NotificationHubs 4.2.0 the dependency in .NETStandard 2.1 is for package Microsoft.Extensions.Caching.Memory with version (greater or = 6.0.1) 
but at runtime version 6.0.0 is expected.

As of June 2024, FCM legacy APIs will no longer be supported and will be retired. I have to use NotificationHubs 4.2.0 to migrate to the FCM v1

Github Issue: 
https://github.com/Azure/azure-notificationhubs-dotnet/issues/316

---
#### Feedback Bot on 6/11/2024, 06:41 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drasticactions** [comment]
This is unrelated to the MAUI UI project. As in the linked GitHub issue, you would hit this with any application and not just MAUI UI ones.

I would continue to track https://github.com/Azure/azure-notificationhubs-dotnet/issues/316, that's what needs to be fixed to fix your issue. There's nothing in MAUI that could be done.
