### ISSUE TITLE
Maui programs on Windows and Android do not access sites and url

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#23011]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-programs-on-Windows-and-Android-do-/10669693)._

---
I am using VS 2022 community with the MAUI. Everything works fine but when it comes to accessing url or site, it does not work!
All other programs and browsers on my laptop (Windows 10) works very well and access sites. 
I also installed and tested programs on my Android phone. The same problem, all programs on my phone worked and could access the internet. But the programs I installed using VS 2022 with MAUI could not access urls or sites.
Programs that do not access the internet works very nicely on windows and Android. But when trying to access the internet, The MAUI program hangs on Windows and blows up on Android.
I tried changing networks but the problem remains the same.

Please anyone can help???

---
#### Feedback Bot on 5/29/2024, 01:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 3. Not repro on windows and android platforms.
How did you open the URL in the app?
I added a button to open the URL in the MAUI app, and the URL can be opened normally on both Windows and Android. The problem did not repro, please check the screen recording.
![Image](https://github.com/user-attachments/assets/db8304ef-d650-495e-a74d-bfda4d5c3103)
Code:
Uri uri = new Uri("https://learn.microsoft.com/en-us/aspnet/core/?view=aspnetcore-8.0");
await Browser.Default.OpenAsync(uri, BrowserLaunchMode.SystemPreferred);

Can you provide a sample project for us to investigate the issue.
