### ISSUE TITLE
Splash Screen background does not respect the Color define in MauiSplashScreen

### ISSUE THREAD

**Issue by bloiseleo** [dotnet/maui#23018]
### Description

When you create a .NET MAUI Multiproject App and tries to define a Splash Screen with the property color "white" or #FFFFFF, it does not shows the background of the splash screen white when using Dark Theme in the Cellphone. But, if you define it to be "red", it changes the background correctly. My goal was creating a splash screen with the background white even though the system theme is Dark.

Configuration with White and Dark Theme:  
```
<MauiSplashScreen Include="Resources\Images\dotnet_bot.svg" Color="White"></MauiSplashScreen>
```
![WhatsApp Image 2024-06-12 at 16 44 06_f0532633](https://github.com/dotnet/maui/assets/105981050/1f76b2a6-3acb-4c39-8fac-104b4f240fef)

Configuration with red and Dark Theme:
```
<MauiSplashScreen Include="Resources\Images\dotnet_bot.svg" Color="red"></MauiSplashScreen>
```
![WhatsApp Image 2024-06-12 at 16 43 13_e8e985a1](https://github.com/dotnet/maui/assets/105981050/2fbc66e4-23fb-45b2-90cf-46c930e6ebec)

Configuration with White and Light Theme:
```
<MauiSplashScreen Include="Resources\Images\dotnet_bot.svg" Color="White"></MauiSplashScreen>
```
![WhatsApp Image 2024-06-12 at 16 45 36_8c7638e6](https://github.com/dotnet/maui/assets/105981050/d23d0e7d-f122-46b1-ae1d-59c79ca3f911)

Devices used:
![image](https://github.com/dotnet/maui/assets/105981050/fd301fde-dd14-4de3-93ca-fb5febf64eb5)

### Steps to Reproduce

1 - Create the project below:
![image](https://github.com/dotnet/maui/assets/105981050/cef6a5ed-9283-45a0-839e-bc48c9b30b9b)
2 - Go to the core project:
![image](https://github.com/dotnet/maui/assets/105981050/6575fb39-dc29-4ef8-a3aa-2f21b691e4db)
3 - Open the Project File and add:
```
<MauiSplashScreen Include="Resources\Images\dotnet_bot.svg" Color="White"></MauiSplashScreen>
```
![image](https://github.com/dotnet/maui/assets/105981050/63d096b6-8313-4f65-a0cb-43edee08350f)

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 2.0 (8.0.40). Not repro on Android emulator(13 & 14) and device(12 & 13) platform with sample project. 
![23018](https://github.com/dotnet/maui/assets/77434865/0c15366a-8f8b-4ca0-acda-8734c4d20193)

**Comment by bloiseleo** [comment]
I will try the latest version of Visual Studio
