### ISSUE TITLE
Carousel on MAUI .NET Application Not working.

### ISSUE THREAD

**Issue by Baraiboapex** [dotnet/maui#23020]
### Description

on iOS, the carousel does not work as expected when swiping forward and then swiping back to the previous slide. 

### Steps to Reproduce

1.) Load the Carousel with basic item objects

2.) Launch the project in iOS 17.0 or 16.0

3.) Swipe forward on the carousel.

4.) Swipe back. Notice how the content of the previous item disappears.

### Link to public reproduction project repository

https://github.com/Baraiboapex/Armory2

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

17, 16

### Did you find any workaround?

No

### Relevant log output

```shell
N/A
```

**Comment by kevinxufei** [comment]
Hi, @Baraiboapex 
Unfortunately, the project you provided may not have permission, the page shows' 404 '. So please offer it again. Thanks!

**Comment by phillippschmedt** [comment]
Update to 8.0.60 it fixed this issue for me.

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 2.0 (8.0.40). Can repro on iOS platform with sample project; but works fine on 8.0.60.
![maui4](https://github.com/dotnet/maui/assets/86938401/61dded6a-b9bc-4607-9b01-7401a722210b)
