### ISSUE TITLE
Regression Issue: CollectionView SizeChanged does not work in SR6 but it works in SR5  (.NET 8)

### ISSUE THREAD

**Issue by malsabi** [dotnet/maui#23029]
### Description

I have a CollectionView and a registered behavior called 'ResponsiveGridBehavior'. The behavior hooks the 'SizeChanged' event to control the number of span columns. The behavior is intended to work only on Desktop Idiom like Windows, Mac Catalyst

```csharp
public class ResponsiveGridBehavior : Behavior<CollectionView>
{
	protected override void OnAttachedTo(CollectionView bindable)
	{
		base.OnAttachedTo(bindable);
		if (DeviceInfo.Idiom == DeviceIdiom.Desktop)
			bindable.SizeChanged += OnSizeChanged;
	}

	protected override void OnDetachingFrom(CollectionView bindable)
	{
		if (DeviceInfo.Idiom == DeviceIdiom.Desktop)
			bindable.SizeChanged -= OnSizeChanged;
		base.OnDetachingFrom(bindable);
	}

	private void OnSizeChanged(object? sender, EventArgs e)
	{
		if (sender is CollectionView collectionView && collectionView.ItemsLayout is GridItemsLayout gridItemsLayout)
		{
			double maxWidthPerItem = Application.Current!.GetResource<double>("CardMaximumWidth", 300);
			gridItemsLayout.Span = Math.Max(1, (int)(collectionView.Width / maxWidthPerItem));
		}
	}
}
```

After updating to SR6 the event 'SizeChanged' is never called.

### Link to public reproduction project repository

https://github.com/malsabi/CollectionViewSizeChangedIssue

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

Windows, macOS

### Did you find any workaround?

I had to roll back to SR5.

**Comment by malsabi** [comment]
@PureWeen  @mattleibow  After doing some tests, I realized that SizeChanged will work if the CollectionView is **NOT** wrapped inside a RefreshView. I attached a repo where you can see with / without adding RefreshView.

It's really important to have a GridLayout in CollectionView and it was achievable using the behavior I Implemented it, specially in Desktop / Mac devices. I'm unable to update to SR6 due to this issue unless if there's a workaround.

**Comment by RoiChen001** [comment]
This issue can be reproduced on Windows platform on the latest 17.11.0 Preview 2.1(8.0.60), but it works fine in 8.0.40.
