### ISSUE TITLE
[Bug] ControlTemplate isn't rendering

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#2302]
### Description

When you navigate to a Page that uses a control template, that Page doesn't renderer.

### Steps to Reproduce

1. Create a new maui app
2. Crate a ControlTemplate inside your App.xaml
3. Use this control in a ContentPage and navigate to it

### Expected Behavior

Page loads the control template.

### Actual Behavior

Page is empty :(

### Basic Information

- Version with issue: 6.0.100-preview.7.1345
- Last known good version: N/A
- IDE: VS 2022 Windows
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: N/A
- Affected Devices: All

### Reproduction Link

https://github.com/pictos/MauiBugRepro/tree/ControlTemplate-issue

**Comment by kristinx0211** [comment]
not repro on windows using 32223.341.mian, ControlTemplate is rendering, sample:
[ControlTemplate.zip](https://github.com/dotnet/maui/files/8166959/ControlTemplate.zip)

**Comment by hartez** [comment]
This should not have been closed - the original repro on GitHub demonstrates the issue.

**Comment by StephaneDelcroix** [comment]
related to #5976
