### ISSUE TITLE
Memory leaks when replacing Application.Current.MainPage by a new one keep the old page in memory

### ISSUE THREAD

**Issue by Djakar** [dotnet/maui#23034]
### Description

I created a new MAUI app from scratch, removed the Shell and created 2 ContentPages named Page1 and Page2.
In Page1, I just placed a button that calls `Application.Current.MainPage = new Page2();`
In Page2, I started a thread with a serie of GC.Collect();
After memory analysis, I saw that Page1 is kept in memory.

### Steps to Reproduce

1. Create a new MAUI application
2. Remove the Shell and the page created by the wizard
3. Create a new content page and name it Page2.
4. In code behind, in the ctor, start a new thread like this:
`new Thread(async () => {
  await Task.Delay(5000);
  GC.Collect();
  GC.Collect();
  GC.Collect();
}).Start();`

5. Create a new content page an name it Page1
6. In Page1, add a button with this statement in the click event handler: `Application.Current.MainPage = new Page2();`
7. In App.xaml.cs, replace the shell by `MainPage = new Page1();`

The issue is similar with 8.0.60 SR6

![image](https://github.com/dotnet/maui/assets/97114162/cf69b033-94c9-45f6-b1b2-eb27901dcf77)
![image](https://github.com/dotnet/maui/assets/97114162/c7cec4ce-4c00-493f-9f77-a5906e1771bb)
![image](https://github.com/dotnet/maui/assets/97114162/d13729e9-9d2c-440b-a17b-5fd9d0c49e52)
![image](https://github.com/dotnet/maui/assets/97114162/bafcbc7f-f9ea-49a2-8fc3-14ed9d52bb2b)
![image](https://github.com/dotnet/maui/assets/97114162/65352bce-8bfd-4b18-a3c8-005d56d74cf6)
![image](https://github.com/dotnet/maui/assets/97114162/c79c35f8-1f1e-443a-8b24-12cedb14b04b)
[MauiApp1.zip](https://github.com/user-attachments/files/15817814/MauiApp1.zip)

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

Not yet

**Comment by RoiChen001** [comment]
Can repro this issue at Windows platform on the latest 17.11.0 Preview 2.0(8.0.40&8.0.60).
