### ISSUE TITLE
[net8.0] [iOS] Memory leak on page with CollectionView

### ISSUE THREAD

**Issue by Dani3654** [dotnet/maui#23032]
### Description

Hello,
Since in last release notes of .Net MAUI (8.0.40) there is an issue solved related with CollectionView memory leak, https://github.com/dotnet/maui/pull/21850, and this one https://github.com/dotnet/maui/issues/14654 is closed, I created another app with the same functionality as the one provided in the issue with the latest version (8.0.40). The memory leaks seems to not be solved, I uploaded a video where it shows how the memory keeps going up.

Edit:
Video link: https://www.youtube.com/watch?v=kDIkyekor10

### Steps to Reproduce

1. Clone repository: https://github.com/Dani3654/CollectionViewMemoryLeaks
2. Run the app using Xcode Instruments
3. Navigate between pages to see how memory keep growing

### Link to public reproduction project repository

https://github.com/Dani3654/CollectionViewMemoryLeaks

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

**Comment by Zhanglirong-Winnie** [comment]
Hi, @Dani3654 
I tried to repro your problem. But I can't see the video, could you provide it again? By the way, what version of XCode are you using? When using XCode 15 or higher, I always encounter the problem that the record button stops automatically when I click it.
![image](https://github.com/dotnet/maui/assets/77434865/016bc132-8717-4e6f-ad30-42121d85d10f)

**Comment by Dani3654** [comment]
@Zhanglirong-Winnie just edited the comment adding the video link, I attache it here too: https://www.youtube.com/watch?v=kDIkyekor10.
Xcode version is 15.2, I'm used a physical device for this test, don't know if that would be the problem

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.6.12(build410)(8.0.60 & 8.0.40 & 8.0.21). Can repro on iOS device platform with sample project. 
![image](https://github.com/dotnet/maui/assets/77434865/c51ddcee-43f7-4581-9aaf-c7ed13d8e2ce)

**Comment by jonathanpeppers** [comment]
So, I made this change to the app to debug this issue:
* `~CollectionViewSamplePage() => Console.WriteLine("~CollectionViewSamplePage() called");`
* Call `GC.Collect()` in both `MainPage` and `CollectionViewSamplePage`

For details on this:
* https://aka.ms/maui-memory-leaks

I'm seeing the log message just fine:
```
2024-06-21 11:01:51.077310-0500 CollectionViewMemoryLeaks[68484:910061] ~CollectionViewSamplePage() called
```

Instruments shows memory go up the first couple navigations, but it is stable after doing a few:

![image](https://github.com/dotnet/maui/assets/840039/4c582ee4-93d8-4dba-8c6f-d0e5e26935c0)

This is all testing with .NET MAUI 8.0.60 as the sample has currently. The `GC.Collect()` calls are just for debugging, as it makes the `GC` deterministic (remove them later). The sample has giant race car images in each `CollectionView` row, so I would recommend using a smaller image (thumbnail) that won't be downscaled as much. That would help the `GC` keep up.

I'm not seeing an issue here, but please let me know if I missed something. Thanks!
