### ISSUE TITLE
Multiple project templates. The project file is being loaded all the time. You need to reopen the solution in order to work properly.

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/maui#23040]
### Description

![image](https://github.com/dotnet/maui/assets/30250585/54c8176b-4eca-4fbd-ba6a-37b639f9650f)
Multiple project templates. The project file is being loaded all the time. You need to reopen the solution in order to work properly.
![image](https://github.com/dotnet/maui/assets/30250585/b6e6762f-a9c0-4549-a412-7f6e269fdc86)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 2.0 (8.0.60 ). Can repro it, it may dup of https://github.com/dotnet/maui/issues/22308 [MAUI][Multi-Project] The Solution Explorer window was empty when creating Maui Multi-project

**Comment by mattleibow** [comment]
Does this happen with older vs? It was working when I merged it with vs 17.9 and I think @Eilon was using 17.10.

Did vs regress?

**Comment by HuaFangYun** [comment]
17.10.3 resolved
