### ISSUE TITLE
Got error XA0129: Error deploying 'files/.__override__/System.Data.Common.dll'. 

### ISSUE THREAD

**Issue by yuval-koren** [dotnet/maui#23055]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have created an emulator using hyper-v, then ran it, than built the solution into the emulator, then got this error message:

Error XA0129: Error deploying 'files/.__override__/System.Data.Common.dll'.
Please set the 'EmbedAssembliesIntoApk' MSBuild property to 'true' to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor.	

I could not find this property, as I am new to MAUI.

I am using win10.

**Comment by yuval-koren** [comment]
It worked the second time I ran it (stopped the emulator, rerun it and then build the project again...)

**Comment by jfversluis** [comment]
Hey @yuval-koren! Glad you still got it to work, sorry about the little hiccup. Have fun developing with .NET MAUI!
