### ISSUE TITLE
Add Maui 8.0.60 to list of Versions (etc) 

### ISSUE THREAD

**Issue by MitchBomcanhao** [dotnet/maui#23059]
### Description

Sounds like during the release process someone forgot (again) to update the list of versions when logging issues etc. (see previous issue raised in march https://github.com/dotnet/maui/issues/21298)
this means that people will be logging bugs and marking them against the wrong version.
it shouldn't be too difficult to have someone add another step to the release process to update the version lists in github, no? 

see example:
![image](https://github.com/dotnet/maui/assets/31066938/cddc292d-23a6-4e53-951e-bbe194c03bda)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

**Comment by PureWeen** [comment]
Closed by https://github.com/dotnet/maui/issues/23071
