### ISSUE TITLE
[Windows] App based on FlyoutPage uses incorrect title bar colours when system is set to Dark theme and app set to Light theme - illegible content

### ISSUE THREAD

**Issue by MitchBomcanhao** [dotnet/maui#23057]
### Description

When the windows app is set to Light theme, and the computer is set to Dark theme, the application window's buttons at the top are shown in white against a white background while the app window has focus. If focus is moved away from the app, the button icons change color and become visible.

This fails on maui from the first v8 up to SR6. I've not been able to try older versions of maui. This works fine on xamarin forms.

### Steps to Reproduce

1. Create a new maui base project.
2. in App.xaml.cs, replace `MainPage = new AppShell();` with `MainPage = new MainPage();`
3. Change MainPage to be a FlyoutPage - it doesn't matter what content you put in FlyoutPage.Flyout or FlyoutPage.Detail.
4. in the Windows platform app.xaml.cs file, add this line to the Aop class constructor: `RequestedTheme = ApplicationTheme.Light;`
5. Set windows to dark theme.
6. Run the app
7. EXPECTED
8. The app's window title bar and its buttons are correctly rendered
9. OBSERVED
10. The title bar is shown in white and the various buttons' icons are also shown in white, making them impossible to see.
11. ![image](https://github.com/dotnet/maui/assets/31066938/9b3de786-c0d1-4547-9e7d-1260ea2e119d)
12. Click away from the app window. OBSERVE
13. the button icons will now become visible:
14. ![image](https://github.com/dotnet/maui/assets/31066938/16da516b-2899-46cd-8d56-b2b330cfbf21)
15. Change windows to light theme. OBSERVE
16. now the buttons are correctly visible when the app is focused (pictured below) and unfocused
17. ![image](https://github.com/dotnet/maui/assets/31066938/fc87c8fd-214d-492c-a35e-989f13a2e951)

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Reproduced in Windows 11 22631.3737

**Comment by ninachen03** [comment]
Verified this original issue with Visual Studio 17.11.0 Preview 2.0 (8.0.60 & 8.0.3 ). Can repro it.
[MauiApp4.zip](https://github.com/user-attachments/files/15883699/MauiApp4.zip)

**Comment by MitchBomcanhao** [comment]
> It is also possible that the application name is missing from the top left of the application window...

@Foda @PureWeen buttons are visible but the application title is indeed still missing after this new release
