### ISSUE TITLE
Image Loaded event not firing in 8.0.60 version which is used to fire in 8.0.40 and earlier versions. Selected 8.0.40 I am unable to see 8.0.60

### ISSUE THREAD

**Issue by letscodewithkalyan** [dotnet/maui#23058]
### Description

We are displaying error image on image Loaded event. We are registering image loaded event when we set image source. it used to work in preivous versions 8.0.40, 8.0.21., etc.. But stopped in 8.0.60.

### Steps to Reproduce

1. Change the image source for image dynamically same time add image loaded event
2. First time event is firing when we change it is not firing

### Link to public reproduction project repository

https://github.com/letscodewithkalyan/MauiImageLoaded

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.21 SR4.1

### Affected platforms

Android

**Comment by PureWeen** [comment]
Closed by https://github.com/dotnet/maui/issues/23071

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 2.0 (8.0.60 & 8.0.40 &8.0.21). Not repro on Android platform with sample project.

**Comment by PureWeen** [comment]
This fix should be available on the nightly feed as version `8.0.61-ci.net8.24319.3`. 

Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds
