### ISSUE TITLE
Cannot reference Microsoft.AspNetCore.Mvc.NewtonsoftJson version 8.0.6 in net8.0-ios

### ISSUE THREAD

**Issue by JoshuaNormanCGI** [dotnet/maui#23066]
### Description

/usr/local/share/dotnet/sdk/8.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(491,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'iossimulator-arm64'. [/Users/New.User/Projects/MauiJson/“MauiAppPlusJson”/“MauiAppPlusJson”.csproj::TargetFramework=net8.0-ios]

### Steps to Reproduce

dotnet new maui -n MauiAppPlusJson
Remove net8.0-android; from target framework.
cd MauiAppPlusJson
dotnet build
dotnet add package Microsoft.AspNetCore.Mvc.NewtonsoftJson --version 8.0.6
dotnet build

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No.

### Relevant log output

```shell
/usr/local/share/dotnet/sdk/8.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(491,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'iossimulator-arm64'. [/Users/New.User/Projects/MauiJson/“MauiAppPlusJson”/“MauiAppPlusJson”.csproj]
```

**Comment by JoshuaNormanCGI** [comment]
I'm running:
XCode 15.4
MacBook Pro
Apple M1 Pro
Sonoma 14.5
chip Apple M1 Pro

[msbuild 5.zip](https://github.com/user-attachments/files/15842611/msbuild.5.zip)

**Comment by drasticactions** [comment]
I could be mistaken, I believe this error is correct. I don't believe ASP.NET Runtime packs exist for iOS. Why are you trying to reference this library? 

@rolfbjarne I don't believe you can run ASP.NET Core services directly within iOS, right?

**Comment by rolfbjarne** [comment]
> @rolfbjarne I don't believe you can run ASP.NET Core services directly within iOS, right?

I don't think so.

However, according to NuGet.org, the package in question is compatible with net8.0-ios:

https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson/#supportedframeworks-body-tab

It took some digging, but I believe the package brings in the `Microsoft.AspNetCore.App` framework using this from the nuspec:

```xml
<frameworkReferences>
    <group targetFramework="net8.0">
        <frameworkReference name="Microsoft.AspNetCore.App" />
    </group>
</frameworkReferences>
```

So this seems to be a visualization issue on NuGet.org, where it shouldn't show that packages referencing Microsoft.AspNetCore.App are compatible with our platforms.

**Comment by JoshuaNormanCGI** [comment]
Thanks, knowing that Microsoft.AspNetCore.App isn't compatible allowed us to move some things around and get around our issue resolved. I was confused since it seemed the documentation indicated it was compatible and I thought I had found another post indicating it was compatible. Thanks for the help!
