### ISSUE TITLE
ListView items disappearing while scrolling on iOS

### ISSUE THREAD

**Issue by albyrock87** [dotnet/maui#23062]
### Description

Using today's (June 24th 2024) main branch testing app we can see that collection view items disappear while scrolling.

![Simulator Screen Recording - iPhone Xs (iOS 17 2) - 2024-06-14 at 12 59 28](https://github.com/dotnet/maui/assets/1423005/1d7648df-28f2-43ab-a2ed-17c1a185a466)

### Steps to Reproduce

Just run the controls test app from MAUI repo and scroll.

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

iOS, I was *not* able test on other platforms

**Comment by rmarinho** [comment]
I think you are referring to `ListView` and not `CollectionView` ? 

https://github.com/dotnet/maui/blob/main/src/Controls/tests/TestCases/CoreViews/CorePageView.cs#L13

**Comment by albyrock87** [comment]
You're right @rmarinho , I was about to change the bug report.
At this point I don't even know if this was already an existing issue.
Shall I close this one?

**Comment by albyrock87** [comment]
Yeah it's better because the information is not correct at all.
