### ISSUE TITLE
My mac doesnt show up

### ISSUE THREAD

**Issue by Georgia-Gibbison** [dotnet/maui#23067]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

my mac doesn't show up
<img width="826" alt="Screenshot 2024-06-14 at 21 25 12" src="https://github.com/dotnet/maui/assets/144613481/1a2ef960-57ab-4a5c-b7db-4ed7aa5472d7">
<img width="823" alt="Screenshot 2024-06-14 at 21 25 32" src="https://github.com/dotnet/maui/assets/144613481/bdccd077-a075-4f65-bcac-61cefe5dda67">

**Comment by drasticactions** [comment]
The MAUI UI team does not maintain this tooling. If you file your issue to [vscode-dotnettools](https://github.com/microsoft/vscode-dotnettools) they could help figure out what's going on.

**Comment by jfversluis** [comment]
Assuming this has been reported in the right place by now. Thanks!
