### ISSUE TITLE
Cannot publish iOS from Windows after connecting to Mac

### ISSUE THREAD

**Issue by ericgrantholland** [dotnet/maui#23069]
### Description

Maui Publish for iOS does not work. I get a spinner saying "archiving app bundle" that never finishes. After many hours of trying, I tried from command line and get the cryptic error below:

`C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8053\tools\msbuild\iOS\Xamarin.Shared.targets(1838,3): error : Cou
ld not find Microsoft.iOS in '/Users/ericholland/Library/Caches/Xamarin/XMA/SDKs/dotnet/'packs/Microsoft.iOS.Sdk/17.2.8
053/. [C:\Dev\Devops\TaxComm\TaxCommPro.MAUI\TaxCommPro.MAUI.csproj::TargetFramework=net8.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8053\tools\msbuild\iOS\Xamarin.Shared.targets(1838,3): error :
      [C:\Dev\Devops\TaxComm\TaxCommPro.MAUI\TaxCommPro.MAUI.csproj::TargetFramework=net8.0-ios]`

I can't find any guidance on how to fix this. 

### Steps to Reproduce

1. Create a maui application on Windows. 
2. Get a mac, setup XCode 15.0.1
3. Setup App in Apple developer etc.
4. Pair Visual studio to the Mac and attempt to publish to iOS

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by drasticactions** [comment]
The MAUI UI team does not maintain this tooling, Visual Studio does. If you file your question there, they should be able to help.

**Comment by jfversluis** [comment]
Assuming this has been reported in the right place by now. Thanks!
