### ISSUE TITLE
Border on iOS redraws with 1 frame lag, creating flashes of (1) square corners on redraws, and (2) old background color before new color update

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#23070]
### Description

In iOS, when Maui must redraw a Border, it does so with a 1 frame lag which is evident in two ways:

1) The Border is sometimes re-drawn briefly fully square, causing a flash of a square over the corners (rather than the round corners expected)
2) The old background color is still visible on update when it is changed for one frame, causing a visual flash of the old color each time

### Steps to Reproduce

Reproduction project contains TWO reproduction demonstrations (one for each redraw problem, although they are likely the same underlying issue). To toggle between these projects, open App.xaml.cs and set TestProject here:

```
 enum TestProjects {
     testProject1, //==> DEMONSTRATES FLASH AT CORNERS OF LOWER SCREEN "HELLO" BORDER
                   //AS BORDER IS INITIALLY DRAWN SQUARE (RATHER THAN ROUND) ON THE FIRST "CLICK ME" BUTTON CLICK

     testProject2 //==> DEMONSTRATES FLASH OF PRIOR COLOR ON EACH UPDATE
                  //AS EACH TIME BORDER IS REDRAWN THE COLORATION LAGS ONE FRAME
 }
 public App() {

     //=================================
     //SET WHICH TEST PROJECT HERE
     //=================================
     TestProjects testProject = TestProjects.testProject1;
     //=================================
```

### 1) TestProject1
This shows a button on screen like this, which when clicked will alter the bottom Border. The bottom Border will flash on the first click made, creating the single frame square border effect shown on the "HELLO" border here:

![issue-screencap](https://github.com/dotnet/maui/assets/43948450/aebd80aa-64e4-4f0a-8eda-5c50c688a39c)

### 2) TestProject2
This shows a Border on screen which is automatically toggled by a timer visible or invisible. Each time the background color changes. However, you will see on each update the old color still flashes momentarily before the new one replaces it.

### Notes:
Note that the slowest method of building (eg. Debug to device or simulator) is preferred to see the flashes for as long as possible so it is obvious to the eye.

Please note this is also NOT an animation effect - it is a 1 frame drawing lag which is separate from other issues, as animations in test project have been successfully removed by NotAnimatedBorderHandler.cs as per: https://github.com/dotnet/maui/issues/18204

@jsuarezruiz  I know you were able to fix some of the Windows/Android Border drawing bugs previously reported and it has been appreciated. Any suggestions on a fix or workaround for this one for iOS? Thanks for any help.

### Link to public reproduction project repository

https://github.com/jonmdev/iOSBorderShadowAnimationBug

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 2.0 (8.0.60 & 8.0.40 & 8.0.21). Can repro on iOS platform with sample project.
[iOSBorderShadowAnimationBug-main.zip](https://github.com/user-attachments/files/15863489/iOSBorderShadowAnimationBug-main.zip)

**Comment by thisisthekap** [comment]
We verified that issue as well. This is one of the main blockers in our effort to migrate to maui.

**Comment by thisisthekap** [comment]
@jonmdev Were you able to implement a workaround in the meantime?

**Comment by albyrock87** [comment]
May you verify if this issue persists with the latest commit on `main`?
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by albilaga** [comment]
@albyrock87 still the same issue https://github.com/albilaga/MauiBorderIssue

**Comment by jonmdev** [comment]
> @jonmdev Were you able to implement a workaround in the meantime?

I am not aware of any workaround. It would be great to have one. From my perspective, the two biggest remaining glitches in iOS are:

1) This Border redraw bug. Makes corners of Borders constantly flicker (which is unsettling as a user) and redraw sometimes lags behind other objects by one frame causing momentary alignment glitch issues.

2) Editor is broken in iOS as per: https://github.com/dotnet/maui/issues/17757 - but that one is currently marked p/2 and on the work list for .NET 8 service so hopefully it will be fixed soon.

If we could get solutions for these two we could at least theoretically build basic working iOS apps in Maui from the simple components which would be great.

**Comment by jonmdev** [comment]
> @jonmdev may you try out the build from this PR and confirm all issues have been fixed? #23648

Sure great, can you explain how I do that? Sorry I don't know how to test such things. I have only been using the formal Maui releases.

**Comment by jonmdev** [comment]
> @jonmdev it's like testing the nightly.. This should be the version: 8.0.80-ci.net8.24367.6 The build number can be found in the Azure Pipeline build logs under the MAUI-public pipeline.

I will try but I must point out that in your fixed gif there is still a problem. Maybe a new problem.

As you see the border is drawn one frame behind the text creating a lag.

Thank you for your effort in any case. It is at least a bit better but not quite there. There should be no lag behind the text showing ideally.

![349459240-b53c3a55-717a-46dc-a483-bf795be6dba1](https://github.com/user-attachments/assets/65c2d060-929c-4d8d-8e1b-1b9761d99fbd)

**Comment by albyrock87** [comment]
@jonmdev I see, thanks for pointing it out, at this point I'll seek for a different solution.

At least I'm closer to the source of the problem.

**Comment by jonmdev** [comment]
For reference this does not close the bug. It just changes it. We not have proper rendering but still with a 1 frame lag. Do you want a new bug report @PureWeen?

**Comment by albyrock87** [comment]
@jonmdev reopen the bug, I'll look into it again and open a new PR

**Comment by jonmdev** [comment]
I cannot open this issue ocne closed but I made a new report for the remaining 1 frame lag here @albyrock87 if you can help with the final fix:

https://github.com/dotnet/maui/issues/23688

Thanks for all your help on this.
