### ISSUE TITLE
[Bug] Contribution Build Failing

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/maui#2307]
I was able to get the pull request in but not without some fighting.

I have the following errors causing my builds to fail I don't no why, I followed @jamesmontemagno video the best I could on contribution. Am using .Microsoft.Maui Solution to build as even james had issues in his video on this matter.

Oh and yes am using the maui branch here on my fork
https://github.com/davidbuckleyni/maui

![image](https://user-images.githubusercontent.com/5619229/131269334-934c524f-06bf-4e60-a05c-e598a7bd2a55.png)
[MauiLogs.zip](https://github.com/dotnet/maui/files/7073392/MauiLogs.zip)
 but still getting some errors here on build.

I did get the exact same error message as james on his video here https://www.youtube.com/watch?v=NEzb48bUJLk&t=2311s

![image](https://user-images.githubusercontent.com/5619229/131269466-4b6b3110-2522-46a4-9f41-4dfa9f8952be.png)

https://www.screencast.com/t/yBa7tJ8SfGC

Microsoft Visual Studio Community 2022 Preview
Version 17.0.0 Preview 3.1
VisualStudio.17.Preview/17.0.0-pre.3.1+31612.314
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00476-70000-00000-AA316
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.0.414.6609
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.414.6609
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.414.6609
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.414.6609
Azure Functions and Web Jobs Tools

C# Tools   4.0.0-3.21403.23+d51d1a7338e32d3a3cd1e5452665964ee8ec15df
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.0.6 (1ebf2f7)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2138002+9e71a625d64fa38b323fa6ac52154e6b1bde703d
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62108.04180
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.0730.2001
TypeScript Tools for Microsoft Visual Studio

UnoPlatformPackage Extension   1.0
UnoPlatformPackage Visual Studio Extension Detailed Info

Visual Basic Tools   4.0.0-3.21403.23+d51d1a7338e32d3a3cd1e5452665964ee8ec15df
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21370.1+9b96c1bde17e9af532ae34eacbfc12d1628183d7
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.145 (main@bdc8369)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.58 (remotes/origin/d17-0@927d548a1)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.3 (a84fb28)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.4.99.70 (main/7e1558c)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@4fb7c14
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@623332d

Xamarin.iOS and Xamarin.Mac SDK   14.99.0.294 (13b1b3c45)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by Eilon** [comment]
@davidbuckleyni can you show how you tried to open VS? Depending on where you open it from, it might not work correctly if it picks up the wrong `dotnet` instance.

In general I do these steps to build .NET MAUI and open it in VS:

```
dotnet tool restore
dotnet cake --target=VS-NET6 --workloads=global
```

You can find these instructions (and others) here: https://github.com/dotnet/maui/blob/main/DEVELOPMENT.md#compile-with-globally-installed-dotnet

**Comment by davidbuckleyni** [comment]
> @davidbuckleyni can you show how you tried to open VS? Depending on where you open it from, it might not work correctly if it picks up the wrong `dotnet` instance.
> 
> 
> 
> In general I do these steps to build .NET MAUI and open it in VS:
> 
> 
> 
> ```
> 
> dotnet tool restore
> 
> dotnet cake --target=VS-NET6 --workloads=global
> 
> ```
> 
> 
> 
> You can find these instructions (and others) here: https://github.com/dotnet/maui/blob/main/DEVELOPMENT.md#compile-with-globally-installed-dotnet

I open it from task bar as an administrator

**Comment by Eilon** [comment]
@davidbuckleyni yeah I think that might be the problem. For me it works only when I run VS _from the command prompt_ where I set up & built MAUI.

So, after I run those commands (which will also launch VS), if I close VS and want to launch it again, I run something like this:

```
C:\GitHub\maui>"C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\devenv.exe" Microsoft.Maui-net6.sln
```

(That's the Solution for working on "generic" stuff and on Android/iOS/MacCatalyst.)

Or for Windows you could run:

```
dotnet tool restore
dotnet cake --target=VS-WINUI --workloads=global
```

And if you close that VS and want to launch it again, I run something like this:

```
C:\GitHub\maui>"C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\devenv.exe" Microsoft.Maui-winui.sln
```

When I switch between Windows and non-Windows solutions, I do a `git clean -xdf` to **delete all un-tracked files*** (warning!) before running the `dotnet cake ...` command.

**Comment by davidbuckleyni** [comment]
To be clear @jamesmontemagno had exact same issues in his video. And he had to open the non dot net six solutions to be able to build so its not just the case of that. 

> @davidbuckleyni yeah I think that might be the problem. For me it works only when I run VS _from the command prompt_ where I set up & built MAUI.
> 
> 
> 
> So, after I run those commands (which will also launch VS), if I close VS and want to launch it again, I run something like this:
> 
> 
> 
> ```
> 
> C:\GitHub\maui>"C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\devenv.exe" Microsoft.Maui-net6.sln
> 
> ```
> 
> 
> 
> (That's the Solution for working on "generic" stuff and on Android/iOS/MacCatalyst.)
> 
> 
> 
> Or for Windows you could run:
> 
> 
> 
> ```
> 
> dotnet tool restore
> 
> dotnet cake --target=VS-WINUI --workloads=global
> 
> ```
> 
> 
> 
> And if you close that VS and want to launch it again, I run something like this:
> 
> 
> 
> ```
> 
> C:\GitHub\maui>"C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\devenv.exe" Microsoft.Maui-winui.sln
> 
> ```
> 
> 
> 
> When I switch between Windows and non-Windows solutions, I do a `git clean -xdf` to **delete all un-tracked files*** (warning!) before running the `dotnet cake ...` command.

**Comment by VincentBu** [comment]
it's issue related to code contribution, so add `s/verified` tag for it.

**Comment by jfversluis** [comment]
I think the https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md file has seen a lot of improvements and personally its working pretty good as long as you stick to the "cake method".

To not leave this issue linger around too long, please try the updated instructions there and see how it works these days. If you feel it's still not great, feel free to open something new. I think it would be a good idea to then try and make more concrete what you can't get to work and what suggestions would be to make it better to make the next issue more actionable.

Thanks!
