### ISSUE TITLE
Softkeyboard Return key of an Entry control shows Done when the property ReturnType is set to Next

### ISSUE THREAD

**Issue by maictoa** [dotnet/maui#23086]
### Description

Adding an entry control to a xaml file and setting the ReturnType property to Next will show the Done key in the softkeyboard instead of the Next key.

### Steps to Reproduce

1. Create a new .Net Maui App
2. Select framework .NET 8.0
3. Open the MainPage.xaml
4. Add the control Entry ReturnType="Next"
5. Add the control Entry ReturnType="Done"
6. Verify that the Nuget packages for Microsoft.Maui.Controls and Microsoft.Maui.Control.Compatibility are still in version 8.0.40
7. Run the project and observe that one entry shows Next and the other shows Done when the softkeyboard is displayed
8. Update the Nuget packages for Microsoft.Maui.Controls and Microsoft.Maui.Control.Compatibility to version 8.0.60
9. Run the project again and observe that Done shows on both entries for the keyboard return key
![image](https://github.com/dotnet/maui/assets/166420785/7565cdf4-4d7f-4348-9c5d-3a477b16b085)

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

Android

### Affected platform versions

Android 10 and up

**Comment by ninachen03** [comment]
Verified this original issue with Visual Studio 17.11.0 Preview 2.0 (8.0.60 & 8.0.3 ). Can repro it on android device, but I can not repro it on android emulator.

**Comment by baaaaif** [comment]
ReturnType="Search" doesn't work too

**Comment by dineshmike** [comment]
I am having the same issue in both MAUI 8.0.60 & 8.0.61.
Downgrading to 8.0.40 fixes the issue.

Alternatively, you can use force update the input type using handler:

```
EntryHandler.Mapper.AppendToMapping("EntryReturnTypeFix", (handler, view) =>
{
#if ANDROID
        handler.PlatformView.UpdateReturnType(view);
#endif
});
```

**Comment by FlavioGoncalves-Cayas** [comment]
Same on MAUI 8.0.80.
Honestly, I would expect regressions to be fixed fast than >2 months, but here we are.

@dineshmike thanks for the workaround.

**Comment by LaBoss** [comment]
Got same problem on 8.0.90

**Comment by afernandes** [comment]
Alternative to fix:

```c#
    public static class ReturnTypeNextHandler
    {
        public static void UseReturnTypeNextSetup()
        {
#if ANDROID
            Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("ReturnTypeNextSetup", static (handler, view) =>
            {
                if (handler.VirtualView?.ReturnType == ReturnType.Next)
                {
                    handler.PlatformView.SetImeActionLabel("Next", Android.Views.InputMethods.ImeAction.Next);
                    handler.PlatformView.ViewAttachedToWindow += (sender, args) =>
                    {
                        if (sender is Android.Widget.EditText platformView)
                        {
                            if (platformView.ImeActionLabel == "Next")
                                platformView.ImeOptions = Android.Views.InputMethods.ImeAction.Next;
                        }
                    };

                    handler.PlatformView.EditorAction += (sender, args) =>
                    {
                        if (sender is Android.Widget.EditText platformView)
                        {
                            if (platformView.ImeActionLabel == "Next")
                            {
                                platformView.FocusSearch(Android.Views.FocusSearchDirection.Forward)?.RequestFocus();
                                args.Handled = true;
                            }
                        }
                    };
                }
            });
#endif
        }
    }
```

Then invoke the method at startup:

```c#
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        ReturnTypeNextHandler.UseReturnTypeNextSetup();

        //...
    }
}
```

**Comment by Mertsch** [comment]
Still an issue with 9.0.10 and the fix https://github.com/dotnet/maui/issues/23086#issuecomment-2450667322 still works.

**Comment by riccardominato** [comment]
I'm a bit worried about these kind of regressions. Aren't there tons of tests run on every PR?
I thought problems like this one would be catched.

**Comment by FlavioGoncalves-Cayas** [comment]
There is a lot to worry about unfortunately. 
Even if there is no test catching this bug, you would at least expect it to be fixed shortly after it being reported. But it's obviously not.

**Comment by Kiriakos41** [comment]
@afernandes thanks mate 😊

**Comment by maexsp** [comment]
The workaround [https://github.com/dotnet/maui/issues/23086#issuecomment-2450667322](https://github.com/dotnet/maui/issues/23086#issuecomment-2450667322) fixes only the initial problem but also **_introduces a new bug_**! Having a list of multiple (dynamic) Entries than the very last Entry control the keyboard can not be closed anymore and stays open -> even if NEXT was pressed! Focused get removed but keyboard stays open.

**Comment by jfversluis** [comment]
There is a [PR](https://github.com/dotnet/maui/pull/26501) open for this now. Would you be able to test this and see if it resolves the issue correctly?

Instructions on how to do so can be found in [this video](https://youtu.be/B2FOBjZKm9k). Please let us know!

**Comment by jfversluis** [comment]
@maictoa it should be here: https://dev.azure.com/xamarin/public/_build/results?buildId=130432&view=artifacts&pathAsName=false&type=publishedArtifacts
