### ISSUE TITLE
The color of hamburger icon in FlyoutPage always be changed to the white in Maui.

### ISSUE THREAD

**Issue by Jiang-Junjie** [dotnet/maui#23087]
### Description

My project is using `FlyputPage` as follows:

```xaml
<FlyoutPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:local="clr-namespace:FlyoutPageNavigation"
            x:Class="FlyoutPageNavigation.MainPage">
    <FlyoutPage.Flyout>
        <local:FlyoutMenuPage x:Name="flyoutPage" />
    </FlyoutPage.Flyout>
    <FlyoutPage.Detail>
        <NavigationPage>
            <x:Arguments>
                <local:ContactsPage />
            </x:Arguments>
        </NavigationPage>
    </FlyoutPage.Detail>
</FlyoutPage>
```

You could see that I set a `hamburger.png` icon in FlyoutMenuPage:

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:FlyoutPageNavigation"
             x:Class="FlyoutPageNavigation.FlyoutMenuPage"
             Padding="0,40,0,0"
             IconImageSource="hamburger.png"
             Title="Personal Organiser">
 //...
       
</ContentPage>
```
![image](https://github.com/dotnet/maui/assets/81734605/5a2d4f5d-cf15-482c-b3c4-49263f527773)

The origin color of hamburger icon is **blue**, however it always show **white** when program is running.

![Screenshot 2024-07-03 at 08 51 51](https://github.com/dotnet/maui/assets/81734605/d6acda50-cbd4-4a16-9488-c8abad4087bb)

Maybe it's a bug of Maui, we need to find a solution to solve this.

Note: We are using .**net 7.0** with __Visual Studio Community 2022 for Mac__ Version 17.6.12 (build 410), and running it in iOS 17.3 devices.

Thanks for taking care of this problem in advance.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.6.12(build410)(.net7&.net8). Can be reproduced on iOS platform.

**Comment by Thaldoras** [comment]
NavigationPage has a BarTextColor property. This color is used to recolor the hamburger icon. You can set it to what you want.
Additionally you can use the following method inside your pages to change the icon color
`NavigationPage.SetIconColor(this, AppColours.PrimaryDark);`

**Comment by Jiang-Junjie** [comment]
> NavigationPage has a BarTextColor property. This color is used to recolor the hamburger icon. You can set it to what you want. Additionally you can use the following method inside your pages to change the icon color `NavigationPage.SetIconColor(this, AppColours.PrimaryDark);`

Hi, whether you have a try this in `FlyoutPage`? it not works for me.

**Comment by Thaldoras** [comment]
> Hi, whether you have a try this in `FlyoutPage`? it not works for me.

Inside "ContactsPage" you can use that method.
Or on your NavigationPage you can set BarTextColor.

`var navigationPage = new NavigationPage
{
    BarTextColor = AppColours.PrimaryDark
};`
