### ISSUE TITLE
IOS: PDF Readers are not shown in open in menu

### ISSUE THREAD

**Issue by South2AK** [dotnet/maui#23083]
### Description

When using launcher to open a PDF file which has been downloaded previously, I can´t see any of the PDF readers when the Open With request comes.

### Steps to Reproduce

`await Launcher.OpenAsync(new OpenFileRequest("PDF", new ReadOnlyFile(filePath)));`

I also tried opening it with a direct adobe reader NS URL but it didn´t help:

```
  if (File.Exists(filePath))
           {
               var targetUrl = NSUrl.FromFilename(filePath);
               var docController = UIDocumentInteractionController.FromUrl(targetUrl);
               var adobeUrl = new NSUrl("com.adobe.Adobe-Reader:");

               if (UIApplication.SharedApplication.CanOpenUrl(adobeUrl))
               {
                   var rootViewController = UIApplication.SharedApplication.KeyWindow.RootViewController;
                   var view = rootViewController.View;

                   docController.PresentOpenInMenu(new CoreGraphics.CGRect(0, 0, 1, 1), view, true);
                   Console.WriteLine("Adobe-Reader");

               }
               else
               {
                   Console.WriteLine("Adobe-Reader is not installed");
               }
           }
           else
           {
               Console.WriteLine("File does not exist");
           }
```

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by drasticactions** [comment]
https://github.com/drasticactions/MauiRepros/tree/main/PdfTest

I may be misunderstanding your issue, but I don't think I can reproduce this.

![IMG_3147](https://github.com/dotnet/maui/assets/898335/d775c3c7-562d-4385-9afa-e364233f6051)

Using Launcher.OpenAsync (which is using [OpenUrlAsync](https://github.com/dotnet/maui/blob/main/src/Essentials/src/Launcher/Launcher.ios.tvos.cs#L20-L21)) it shows Adobe Reader in the menu, once I installed it on my device. If you're not seeing it when invoking that UIKit API yourself, it may be something on your device, or I'm missing some context here.

Could you try running my sample, or create your own?

**Comment by South2AK** [comment]
Hi @drasticactions,

with a new project it seems fine. I can open the file and it shows open in acrobat on a new project.

But unfortunately I can´t fix my two other projects (two completely different projects). 
![image](https://github.com/dotnet/maui/assets/48831239/9f266fda-77c4-490c-a58e-b8f3f823ac31)

**Comment by drasticactions** [comment]
Are they using the newest .NET 8? Maybe remove and reinstall them from your device? Have you tried a different device?

The API is consistent from the previous .NET versions as far as I can tell. I'm not sure if there are any other ways to debug something like this. @rolfbjarne would you have any ideas?

**Comment by rolfbjarne** [comment]
> Hi @drasticactions,
> 
> with a new project it seems fine. I can open the file and it shows open in acrobat on a new project.
> 
> But unfortunately I can´t fix my two other projects (two completely different projects).

There's clearly something special about those two other projects, if a new project works fine.

1. Does it work on a different device?
2. Do you get the same behavior in the simulator?
3. Can you try deleting the app from the device first, to see if that makes a difference?

If not, the next step would be to look into what's special about your two other projects. I'd do this by copying over settings from the two special projects into the working one. My guess is that this is not something in actual code, so I'd start with what's in the csproj and the Info.plist file (although I might be wrong, it might be something in the code after all).
