### ISSUE TITLE
The type 'Color' is defined in an assembly that is not referenced. You must add a reference to assembly 'OpenTK-1.0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

### ISSUE THREAD

**Issue by marcusts** [dotnet/maui#2310]
### Description

I wrote a color converter:

```csharp
      public static Color ToMauiColor(this System.Drawing.Color color)
      {
         var oldHsv = **color.ToHsv();**
         return Color.FromHsv((float)oldHsv.h, (float)oldHsv.s, (float)oldHsv.v);
      }
```

... which produces this error (see the bold text).

I can't load the requested NuGet, as it appears to be incompatible with Maui.

### Steps to Reproduce

1. Insert my color converter into any empty Maui project.
2. Compile.

### Expected Behavior

No error, or can add the required NuGet.

### Actual Behavior

Error: requires an inaccessible Nuget.

### Basic Information

See the environment at the bottom.

- Version with issue: Maui 0.8.4

### Workaround

None

### My environment

Microsoft Visual Studio Community 2022 Preview
Version 17.0.0 Preview 3.1
VisualStudio.17.Preview/17.0.0-pre.3.1+31612.314
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00476-70000-00000-AA055
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019   17.0.414.6609
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.0.414.6609
Azure App Service Tools v3.0.0

C# Tools   4.0.0-3.21403.23+d51d1a7338e32d3a3cd1e5452665964ee8ec15df
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Clean Solution   1.4.35
Cleans up the solution for the next time you open it. Closes open documents and collapses folders automatically when a solution is being closed.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

ILSpy.AddIn   1.0
Integration of the ILSpy Decompiler into Visual Studio.

Image Optimizer   4.0.142
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.0.6 (1ebf2f7)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.4.236
2.4.236

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

TypeScript Tools   17.0.0730.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.0-3.21403.23+d51d1a7338e32d3a3cd1e5452665964ee8ec15df
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21370.1+9b96c1bde17e9af532ae34eacbfc12d1628183d7
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.145 (main@bdc8369)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.58 (remotes/origin/d17-0@927d548a1)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.3 (a84fb28)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.4.99.70 (main/7e1558c)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@4fb7c14
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@623332d

Xamarin.iOS and Xamarin.Mac SDK   14.99.0.294 (13b1b3c45)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by mattleibow** [comment]
This should no longer be an issue since we don't use System.Drawing.* anymore. Also, when using these types on iOS, you need to manually add a reference to `OpenTK-1` which can be found in the framework dependencies. However, this has been moved to a new package now I think for backwards compatibility.

@dalexsoto was there an actual nuget package released for this yet?
