### ISSUE TITLE
Confirmation box cannot open in Mac Catalyst 

### ISSUE THREAD

**Issue by dhruvindudhat** [dotnet/maui#23110]
### Description

I have created Maui Blazor Server app and currently I are working on MacCatalyst application.
I want to show confirmation dialog when user close the application using close button. So I bind the Window Destroying event and in that bind one function which can show the confirmation box.
I used DisplayAlert() and manual designed xaml page show as popup, etc.. but that popups are not shown and application instance destroyed.
In Windows app I have used MessageBox.Show() which will open the confirmation and page which is binded with screen is destroyed and screen becomes blank but still popup is visible. Although this would be fine same thing try to do in MACCatalyst but not working.
Is there any possible way to show this confirmation popup when user close the application in MacCatalyst?

here is the code in MainPage.xaml for this scenario, Initialize event at blazorwebview initialization process,
```
private void BlazorWebView_Loaded(object sender, EventArgs e)
        {
            App.Current.MainPage.Window.Destroying += OnMainWindowClosed;
        }

private async void OnMainWindowClosed(object sender, EventArgs e)
        {
            _commonEventhandlerService.InvokeDatabaseUpdateEvent(); //check file is updated
            if (DatabaseStatus.IsModified)
            {
#if WINDOWS
                var result = MessageBox.Show(DataModels.Globalization.Resources.UnsavedMsg, DataModels.Globalization.Resources.Warning, MessageBoxButton.YesNo);
                _commonEventhandlerService.InvokeSaveEvent(result == MessageBoxResult.Yes ? true : false); //save or close the files
#endif
#if MACCATALYST

//HERE I WANT TO OPEN CONFIRMATION POPUP
       _commonEventhandlerService.InvokeSaveEvent(false);
 
#endif
 _appOperationService.ShutDownApplication(); // process.kill(); close the app
            }
            else
            {
                _appOperationService.ShutDownApplication();
            }
        }
```

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS Sonoma 14.2.1

**Comment by jfversluis** [comment]
Can you show a little more code that actually shows the dialog? How do you do that?

My suspicion is that it runs on a background thread or something and you'll need to maybe use [this](https://learn.microsoft.com/dotnet/api/microsoft.maui.dispatching.dispatcher.dispatch). Have you tried the Dispatcher and did that change the behavior at all?

**Comment by dhruvindudhat** [comment]
@jfversluis I have tried this solutions with  Dispatch and without also. Please review
`   Application.Current.MainPage.Dispatcher.Dispatch(async () =>
                  await DisplayAlert("Confirmation", "Hello", "cancel")
                );

var taskCompletionSource = new TaskCompletionSource<bool>();
                var alertController = UIAlertController.Create("Confirmation", "Are you sure you want to close the app?", UIAlertControllerStyle.Alert);
                alertController.AddAction(UIAlertAction.Create("Yes", UIAlertActionStyle.Default, action => _commonEventhandlerService.InvokeSaveEvent(true)));
                alertController.AddAction(UIAlertAction.Create("No", UIAlertActionStyle.Cancel, action => _commonEventhandlerService.InvokeSaveEvent(false)));
 
                UIApplication.SharedApplication.InvokeOnMainThread(async () =>
                {
                    await UIApplication.SharedApplication.KeyWindow.RootViewController.PresentViewControllerAsync(alertController, true);
                    taskCompletionSource.SetResult(true);
                });
 
                // 6. Wait for the task completion source
                var presentationSuccessful = await taskCompletionSource.Task;
 
                // 7. Code to execute after successful/failed presentation (optional)
                if (presentationSuccessful)
                {
                    _appOperationService.ShutDownApplication();
                }
                else
                {
                    // Code to handle failed popup presentation (optional)
                }`

**Comment by drasticactions** [comment]
I think you need to create a small repro project for what you're trying to do. From the looks of it, you're calling into straight UIKit code for showing your dialog, which is fine to do but that's not really a MAUI UI issue or bug.

**Comment by dhruvindudhat** [comment]
@drasticactions We have tight deadline and due to that not able to create small project. Can you just tell me is there any way to open confirmation popup when user close the application in Mac Catalyst?? I have already done for windows app using MessageBox.
