### ISSUE TITLE
How to disable vertical moving of collection view on ios?

### ISSUE THREAD

**Issue by bahoss** [dotnet/maui#23134]
### Description

https://github.com/dotnet/maui/assets/7480657/97de7cbc-292f-4d6d-bca4-4bf1ab2958b0

When I use a collection view to menu elements with horizontal scroll the collection view moved and refreshed

`<ContentPage
    x:Class="Aerodrome.Views.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:extension="clr-namespace:Aerodrome.Extensions"
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
    BackgroundColor="#F8F8F8"
    Shell.NavBarIsVisible="False">
    <ContentPage.Resources>
        <toolkit:InvertedBoolConverter x:Key="InvertedBoolConverter" />
    </ContentPage.Resources>
    <ContentPage.Behaviors>
        <toolkit:EventToCommandBehavior Command="{Binding AppearingCommand}" EventName="Appearing" />
    </ContentPage.Behaviors>
    <RefreshView Command="{Binding RefreshCommand}" IsRefreshing="{Binding IsRefreshing, Mode=TwoWay}">
        <Grid
            Padding="16"
            RowDefinitions="48,100"
            RowSpacing="16">
            <Grid
                Grid.Row="0"
                Margin="16,0"
                ColumnDefinitions="48,*,36"
                ColumnSpacing="16">
                <toolkit:AvatarView
                    BackgroundColor="#A3A3A3"
                    BorderColor="Transparent"
                    HeightRequest="48"
                    HorizontalOptions="Start"
                    ImageSource="{Binding Avatar.AvatarUrl}"
                    WidthRequest="48">
                    <toolkit:AvatarView.GestureRecognizers>
                        <TapGestureRecognizer Command="{Binding GoToProfileCommand}" />
                    </toolkit:AvatarView.GestureRecognizers>
                </toolkit:AvatarView>
                <Label
                    Grid.Column="1"
                    FontAttributes="Bold"
                    FontSize="17"
                    Text="{extension:Translation Key=main_page_profile}"
                    VerticalOptions="CenterAndExpand">
                    <Label.GestureRecognizers>
                        <TapGestureRecognizer Command="{Binding GoToProfileCommand}" />
                    </Label.GestureRecognizers>
                </Label>
                <Frame
                    Grid.Column="2"
                    Padding="16"
                    BackgroundColor="{StaticResource LightGray}"
                    BorderColor="Transparent"
                    CornerRadius="24"
                    HasShadow="False"
                    HeightRequest="48"
                    IsVisible="True"
                    VerticalOptions="CenterAndExpand"
                    WidthRequest="48">
                    <Frame.GestureRecognizers>
                        <TapGestureRecognizer Command="{Binding LogOutCommand}" />
                    </Frame.GestureRecognizers>
                    <ImageButton
                        Aspect="AspectFit"
                        BackgroundColor="Transparent"
                        Command="{Binding LogOutCommand}"
                        Source="ic_logout" />
                </Frame>
            </Grid>
               <CollectionView
                    x:Name="MenuCollectionView" Grid.Row="1"
                    HorizontalScrollBarVisibility="Always"
                    HeightRequest="80"
                    ItemsSource="{Binding MenuItems}"
                    SelectionChangedCommand="{Binding MenuItemTappedCommand}"
                    SelectionMode="Single">
                    <CollectionView.ItemsLayout>
                        <LinearItemsLayout Orientation="Horizontal" />
                    </CollectionView.ItemsLayout>
                    <CollectionView.ItemTemplate>
                        <DataTemplate>
                            <Frame
                                Margin="5,0"
                                Padding="16"
                                BackgroundColor="White"
                                BorderColor="Transparent">
                                <Grid ColumnDefinitions="auto, *" ColumnSpacing="10">
                                    <Image Grid.Column="0" Source="{Binding Icon}" />
                                    <Label
                                        Grid.Column="1"
                                        FontAttributes="Bold"
                                        FontSize="11"
                                        Text="ITEM"
                                        VerticalOptions="Center" />
                                </Grid>
                                <Frame.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding BindingContext.MenuItemTappedCommand, Source={x:Reference MenuCollectionView}}" CommandParameter="{Binding .}" />
                                </Frame.GestureRecognizers>
                            </Frame>
                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
         </Grid>
    </RefreshView>
</ContentPage>`

I try to use ScrollView and wrap all in Refresh view and disable, but don't help(((

What I do wrong?

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 17.2

**Comment by bahoss** [comment]
I fixed the refreshing by add
<RefreshView Grid.Row="1" IsEnabled="False">
             <ContentView>
               <CollectionView>
                        ....
                 </CollectionView>
               </ContentView>
            </RefreshView>

But how can i disable vertical moving?

**Comment by npostma** [comment]
I am experiencing the same issue. I have a carousel view embedded within a refresh view. On Android, the carousel behaves as expected, moving only horizontally. However, on iOS, the entire carousel can move up and down. I want to disable this vertical movement on iOS. How can we achieve this?

**Comment by QianaJiao** [comment]
Hi,@bahoss @npostma. I tried to paste this code into my template project, but some associated resources are missing. So if possible, could you give me a repo and I'll verify if it still repro on latest version.
