### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple

### ISSUE THREAD

**Issue by baihao** [dotnet/maui#23141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Ask for the `PrivacyInfo.xcprivacy` manifest as required by Apple, please refer to the Apple's document https://developer.apple.com/documentation/bundleresources/privacy_manifest_files for the detailed information, thanks.

### Describe the solution you'd like

A PrivacyInfo.xcprivacy for macOS just like the page mentioned: https://devblogs.microsoft.com/dotnet/apple-privacy-manifest-support/, in the page, dotnet already included the manifest for iOS, iPadOS, and tvOS platforms, but macOS is excluded.

### Additional context

None

**Comment by mkArtakMSFT** [comment]
@Eilon FYI

**Comment by drasticactions** [comment]
@mkArtakMSFT @baihao There's documentation for this: https://devblogs.microsoft.com/dotnet/apple-privacy-manifest-support/

Does this cover what you need?

**Comment by drasticactions** [comment]
Ah, sorry. I didn't see you already linked to it. 

I believe the docs should also apply to Mac Catalyst as well, so long as you change "iOS" to "Catalyst", 

ex:

```
<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
    <BundleResource Include="Platforms\MacCatalyst\PrivacyInfo.xcprivacy" LogicalName="PrivacyInfo.xcprivacy" />
</ItemGroup>
```

@mcumming This should work on Catalyst too, right?

**Comment by jfversluis** [comment]
Just to confirm the above, this should work for macOS the exact same. From the already linked [blogpost](https://devblogs.microsoft.com/dotnet/apple-privacy-manifest-support/)

> Mac Catalyst and macOS apps
> At this time it seems that macOS apps, including Mac Catalyst do not seem to need privacy manifest entries for the required reasons APIs. However, a manifest file and relevant entries are still needed if your app, or any SDK you are using inside of your app, is collecting personal data. Please refer to the [Apple documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) for more information about the required entries.
> 
> Adding the PrivacyInfo.xcprivacy file to your project follows the same procedure as described above, however you should place the file under the `Contents/Resources/` subfolder in your macOS app bundle instead of in the root as for iOS.

You should indeed update it to use your Mac Catalyst bits. So that means:

1. Add a `PrivacyInfo.xcprivacy` file with the correct content to your `Platforms/MacCatalyst` folder.
2. Add this node to your csproj file
   ```xml
   <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
       <BundleResource Include="Platforms\MacCatalyst\PrivacyInfo.xcprivacy" LogicalName="PrivacyInfo.xcprivacy" />
   </ItemGroup>
   ```
3. Build your app and submit to the store!

Have you done that? Is it not working? If not, can you please provide more information about what you have put in your csproj file to link the `PrivacyInfo.xcprivacy` file? Thanks!
