### ISSUE TITLE
'Platform' does not contain a definition for 'Init' (iOS)

### ISSUE THREAD

**Issue by metal450** [dotnet/maui#23145]
### Description

I'm seeing the same issue as https://github.com/dotnet/maui/issues/21253, but in iOS rather than Android. Responses to the previous issue say he was using the wrong namespace & needs to use `Microsoft.Maui.ApplicationModel`...however...his original post states that he was using exactly that namespace (?). To eliminate any ambiguity, I'm using the full namespace inline:

* I have an existing Xamarin.iOS app with TargetFramework `net7.0-ios`. It works perfectly, including Maui.Essentials
* Upon updating the TargetFramework to `net8.0-ios16.1`, the same code no longer builds. The error is `'Platform' does not contain a definition for 'Init' ` on the line `Microsoft.Maui.ApplicationModel.Platform.Init(() => window.RootViewController);`
* The project has a reference to `Microsoft.Maui.Essentials` 8.0.60.
* The project previously worked without `<UseMauiEssentials>true</UseMauiEssentials>`, but I tried adding it after the error appeared in .Net 8. The behavior was the same.

### Steps to Reproduce

1. Create a new C# iOS application
2. Add a reference to Microsoft.Maui.Essentials 8.0.60 from nuget
3. Paste into AppDelegate.cs:

```
public void test()
{
    Microsoft.Maui.ApplicationModel.Platform.Init(() => new UIViewController());
}
```
4. You'll see the error `CS0117	'Platform' does not contain a definition for 'Init'`
5. Edit the project properties & downgrade the .NET target runtime from 8.0 to 7.0
6. The error immediately resolves

### Link to public reproduction project repository

[link](https://github.com/metal450/maui-bug-repro)

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 2.0 (Microsoft.Maui.Essentials 8.0.60), Can not repro on .NET iOS application(Xcode:15.2  Simulator: IPhone15 17.2/17.0 & iOS device:16.2).
Through the project and operation steps you provided, this error cannot be reproduced in either method. If you have other special operation steps, please add it. Thanks!

**Comment by drasticactions** [comment]
<img width="1045" alt="スクリーンショット 2024-06-20 17 27 58" src="https://github.com/dotnet/maui/assets/898335/b2f3b72f-dddb-454e-8f78-2edff2a20bd8">

Yeah, your repro shows this working. 

My guess, based on your error, is that you either have that code inside a file that is being referenced by another target framework. Even though you mentioned this happening in AppDelegate in (I think) a MAUI  UI project, which I also tried and worked fine, as expected.

https://github.com/dotnet/maui/blob/9f0d6166e62f6cba5e659a957aaa9cb7e71dea48/src/Essentials/src/Platform/Platform.shared.cs#L119

This would only works on iOS/Catalyst, and the single target MAUI solution targets iOS, Catalyst, Windows, and Android. So maybe you have it placed somewhere we're it's trying to be compiled for other platforms. Or maybe your IDE is targeting that file for other platforms and it's showing it as failing, but it would compile fine from CLI. My guess looking at that other issue you linked to is they had the same issue. Without having a sample project nor context into where they were typing their code, it was probably targeting the base TFM where nothing exists for Platform.

There is no change in that API from net7.0 to net8.0. IMO I don't think there's a bug here, I think it's more a configuration issue with your project and/or IDE. Could you try creating a MAUI UI project showing your issue?

**Comment by metal450** [comment]
Ok, I had to do 2 things:

* Upon updating Visual Studio, it fixed it in the repro project. But it still occurred in my actual app.
* I had to change the Target OS version of the project to 17.2. Anything lower than that (even 17.0) causes this to occur, including in the sample project.

When the issue is present, if I go to the definition of Microsoft.Maui.ApplicationModel, I can see that it's because the `#elif IOS || MACCATALYST` case isn't being compiled. aka `IOS` isn't defined. I'm not sure why it should be necessary to both upgrade Visual Studio and change the target OS version for that to be defined, but in any event, it is an extremely unclear error that seems to crop up on multiple platforms, so it seems like there'd be a better way to handle it / report the issue to the user...?

**Comment by drasticactions** [comment]
My best guess would be it depends on what dotnet workloads you have, and what target framework you have selected in the IDE (As in, in the Editor dropdown, did you select ios, catalyst, or android). If your code compiles in CLI but the IDE shows errors then some wires are crossed in the IDE with what it thinks it can build and run.

In any case, those are more fundamental issues with target framework support in dotnet and the IDE/Editor your using, and not something that's specific to the MAUI UI framework. That can't be addressed here. I would direct that to VSFeedback.
