### ISSUE TITLE
Moving one item between groups of a Grouped CollectionView results in the temporary fading out of two items instead of one on Android

### ISSUE THREAD

**Issue by inimirpaz** [dotnet/maui#23152]
### Description

Probably related to: https://github.com/dotnet/maui/issues/23138

The opereation of `.Remove` from a grouped list, results in the appearing fading out of the wanted item and the (unwanted) subsequent one.

https://github.com/dotnet/maui/assets/56956625/9c7e24b0-d54b-4e6f-8fb6-63ebc0dc9aaa

### Link to public reproduction project repository

https://github.com/inimirpaz/maui_issues/tree/grouped_cv_issue

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.3

### Affected platforms

Android

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 2.0 (8.0.60 & 8.0.40). Can repro on Android platform with sample project.
