### ISSUE TITLE
Width value return -1

### ISSUE THREAD

**Issue by IXChinmayD** [dotnet/maui#23171]
### Description

When I try to use the Application.Current.MainPage.Width, it returns -1 in Android. Please look into it.

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jfversluis** [comment]
Please provide more information as to where you are trying to query for this value, for example also see: https://github.com/dotnet/maui/issues/10747#issuecomment-1286068734

You might be too early to get the right value. Please provide some relevant code or ideally a reproduction that shows the behavior that you're seeing so we can provide you with information or look into a potential bug.

**Comment by IXChinmayD** [comment]
Hi @jfversluis, I had another query related to MAUI Custon Editor. Here is the link https://learn.microsoft.com/en-us/answers/questions/1719817/entered-text-for-customized-editor-is-not-visible?page=1&orderby=Helpful&comment=answer-1553931#newest-answer-comment  There I realized that `Application.Current.MainPage.Width` does not work and found the alternative solution for it.

**Comment by jfversluis** [comment]
OK glad you figured it out!
