### ISSUE TITLE
Color.FromHsla only returns white color

### ISSUE THREAD

**Issue by DieselSoup** [dotnet/maui#23180]
### Description

When I try to use the `Microsoft.Maui.Graphics.Color.FromHsla` method, it only produces a white color regardless of the hue, saturation, or lightness passed in as arguments.

### Steps to Reproduce

1. Create a new .NET MAUI app.
2. In MainPage.xaml.cs, add the following code to the In the constructor:
```
var color = Color.FromHsla(143, 80, 30);
CounterBtn.BackgroundColor = color;
```

The button will turn white instead of the expected green color.

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

**Comment by ninachen03** [comment]
I can repro this issue on the latest 17.11.0 Preview 2.1 (8.0.60 & 8.0.40 & 8.0.21)

**Comment by jfversluis** [comment]
I think the values should be specified as floats or doubles, also see the [examples in our docs](https://learn.microsoft.com/dotnet/maui/user-interface/graphics/colors#examples).

In your case, you probably want to specify it as `var color = Color.FromHsla(1.43, 0.8, 0.3);` which then makes the button show up like below.

![Screenshot of a running .NET MAUI app. The button is showing the correct background color.](https://github.com/dotnet/maui/assets/939291/47a0f821-33d3-4b43-8c1c-964bc135f062)
