### ISSUE TITLE
Building Release Version of Maui/Blazor Hybrid for iOS brings in Lots of Build Errors

### ISSUE THREAD

**Issue by AathifMahir** [dotnet/maui#23182]
### Description

Building Release Version of Maui/Blazor Hybrid for iOS brings in Lots of Build Errors and Most of the Errors were related Path, Most Notably this issue happens on Fresh Blazor Hybrid Project without Touching or Changing Anything on csproj

### Steps to Reproduce

1. Create New Blazor Hybrid/Maui App
2. Publish it for iOS

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

**Comment by AathifMahir** [comment]
> @AathifMahir are you still getting this? To be honest, this does not appear to be a runtime issue. I'm going to transfer it to MAUI as they may have a better idea.

Yeah, I do get these errors some days ago but not checked recently with the latest Maui Versions, I'll try build a Sample Project on My Mac again and get back to you

**Comment by Zhanglirong-Winnie** [comment]
Hi, @AathifMahir 
Can you still reproduce the problem? If so, could you provide your sample project?

**Comment by AathifMahir** [comment]
> Hi, @AathifMahir 
> Can you still reproduce the problem? If so, could you provide your sample project?

This happened on unmodified New Blazor Hybrid Project. Therefore creating a new Blazor Hybrid Project would be sample project for this

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.6.14(build413)(8.0.82 & 8.0.80). Can not repro on iOS platforms. Building Release Version succeeded.
