### ISSUE TITLE
Maui MediaPicker.Default.CapturePhotoAsync fails under iOS with no error message

### ISSUE THREAD

**Issue by grantsss** [dotnet/maui#23197]
### Description

Hi,

When I try to capture an image on a physical Apple device using MediaPicker.Default.CapturePhotoAsync() the calling function stops functioning with no error message and returns a null.

My project is running the following packages:

<PackageReference Include="CommunityToolkit.Maui" Version="9.0.1" />

<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />

<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.4" />

<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.60" />

<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.60" />

<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />

<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />

I am getting the same results on a iPhone 8 running iOS 16.3.1 and a iPad Air 2 running iOS 15.8.2. 

Works under Windows and Android.

Thanks for your help,

Grant

### Steps to Reproduce

When I try to capture an image on a physical Apple device using MediaPicker.Default.CapturePhotoAsync() the calling function stops functioning with no error message and returns a null.

Code sample:

        public async Task<List<Photo>> TakePic(ContentPage page)
        {
            var Photos = new List<Photo>();

            Photo photo = new Photo();

            try
            {
                await page.DisplayAlert("Debug", $"IsCaptureSupported {MediaPicker.Default.IsCaptureSupported}", "Ok");
                if (MediaPicker.Default.IsCaptureSupported)
                {
                    await page.DisplayAlert("Debug", $"taking pic", "Ok");

                    var photoFile = await MediaPicker.Default.CapturePhotoAsync();

                    if (photoFile != null) /iOS returns null here?

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPhone 8 running iOS 16.3.1 and a iPad Air 2 running iOS 15.8.2

### Did you find any workaround?

No

### Relevant log output

```shell
No exceptions raised, just a null FielResult returned.

Works perfectly under Windows and Android
```

**Comment by DCorrBECare** [comment]
Hi @grantsss, does it works if you call the CapturePhotoAsync inside the `MainThread.InvokeOnMainThreadAsync`?

**Comment by grantsss** [comment]
I will this and let you know … ty Sent from Mail for Windows From: DCorrBECareSent: Thursday, June 27, 2024 6:27 AMTo: dotnet/mauiCc: grantsss; MentionSubject: Re: [dotnet/maui] Maui MediaPicker.Default.CapturePhotoAsync fails under iOS with no error message (Issue #23197) Hi @grantsss, does it works if you call the CapturePhotoAsync inside the MainThread.InvokeOnMainThreadAsync?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
