### ISSUE TITLE
Memory leak in RadioButton ControlTemplate

### ISSUE THREAD

**Issue by krdmllr** [dotnet/maui#23199]
### Description

Hi, 
we found that when refreshing a list which contains customized RadioButtons, hundreds of Ellipse objects from the template remain in memory.
I created a sample repo which just uses the control template from the maui documentation https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton?view=net-maui-8.0#redefine-radiobutton-appearance

When refreshing the list a few times, doing GC.Collects in between and taking a snapshot just using Visual Studio, I found the same issue occuring in the sample repo:
![image](https://github.com/dotnet/maui/assets/11095003/f9c8d903-5624-4c18-813b-057f7c1f274c)

Same behavior happens with a Release build + JetBrains dotMemory in our production app.

### Steps to Reproduce

1. Start app
2. Click "Recreate List" button, this does a GC.Collect(), clears and fills the list again

### Link to public reproduction project repository

https://github.com/krdmllr/MauiMemoryLeaks

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows 10.0.19041.0

**Comment by RoiChen001** [comment]
I can repro this issue at Windows platform on the latest 17.11.0 Preview 2.1(8.0.60).

**Comment by krdmllr** [comment]
Hi, thank you very much for taking a look! 

I will retest that in our environment to see if anything changes.

We are actually replace the whole collection and just use an array instead of ObservableCollection in our app. However, we also use a lot of rx with DynamicData where we filter and sort lists and bind them using ReadOnlyObservableCollections. They use Reset when swapping larger collections. Would you generally recommend to change that to replace the collections instead?

**Comment by jonathanpeppers** [comment]
The main thing to check is that an event fires once, instead of `ObservableCollection.CollectionChanged` firing 1-per item.

In my example, it was actually `OnPropertyChanged(nameof(Items))` that refreshed the screen.

**Comment by krdmllr** [comment]
Can confirm that calling GC more often shows that the object count stays at 80 ellipses.

The overall memory consumption still increases when reloading the data, is that something that is expected?

![image](https://github.com/dotnet/maui/assets/11095003/8ce528ca-798d-4289-86f9-ac6c0eefa376)

**Comment by jonathanpeppers** [comment]
If you are always seeing 80, it's probably not a leak. It just means that it takes a few GCs for them to go away. A leak would mean 80->100->120 that continuously grows.

In my screenshot above, if I let the app "rest" for a second, that is what caused this drop to appear:

![image](https://github.com/dotnet/maui/assets/840039/43977932-a427-437d-8363-fc661613ea64)

If you are testing and see something different than me, see if you can find out which object type is growing. I can take another look in that case, thanks!

**Comment by krdmllr** [comment]
> If you are always seeing 80, it's probably not a leak. It just means that it takes a few GCs for them to go away. A leak would mean 80->100->120 that continuously grows.

Yes, I see that the ellipse is not leaking like I suggested initially, I have the same results after adding the additional GC calls. I was wondering why the heap size is still increasing between the snapshots (+200kp in my snapshot), should it not go back to 0 increase or even decrease when calling GC manually?

**Comment by jonathanpeppers** [comment]
For me, it was going down (lower than a previous collection) as I waited longer & clicked longer. There was a stable point the memory usage would hover around.

If you see it going up, diff a few snapshots to see if you can figure out what object (full namespace + type) is the cause.

**Comment by krdmllr** [comment]
@jonathanpeppers thank you, I will close the issue for now and raise a new one if necessary.
