### ISSUE TITLE
ToolbarItem font icon color not updating with AppThemeBinding

### ISSUE THREAD

**Issue by CodingOctocat** [dotnet/maui#23201]
### Description

ToolbarItem Icon Color Not Updating with AppThemeBinding

```xaml
<ToolbarItem Text="Search">
    <ToolbarItem.IconImageSource>
        <FontImageSource FontFamily="SegoeFluentIcons"
                         Glyph="&#xE721;"
                         Color="{AppThemeBinding Light={StaticResource Black},
                                                 Dark={StaticResource White}}" />
    </ToolbarItem.IconImageSource>
</ToolbarItem>
```

Light mode now:
![image](https://github.com/dotnet/maui/assets/7220248/b8d95792-b8a0-4317-89cd-e4e06a01a71d)

Toggle to dark mode:
![image](https://github.com/dotnet/maui/assets/7220248/ae6d773f-cff1-447e-b34f-8ed7c2eb6600)

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android API 34

### Did you find any workaround?

Use file icon

```xaml
IconImageSource="{AppThemeBinding Light='search_light.svg',
                                  Dark='search_dark.svg'}"
```

**Comment by Zhanglirong-Winnie** [comment]
This issue can be reproduced on Visual Studio 17.11.0 Preview 2.1 (8.0.40 and 8.0.21).
