### ISSUE TITLE
I wanna create my self predictor aviator

### ISSUE THREAD

**Issue by Qwerty123-del** [dotnet/maui#23203]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
I'm sorry but with the given information its not clear to me what you want to do here or what issue you might have.

If there is still something we can do for you, please open a new issue with a bit more detail. Thanks!
