### ISSUE TITLE
Add better support for Android 12+ Splash Screen APIs

### ISSUE THREAD

**Issue by nguyenvuhoang** [dotnet/maui#23228]
### Description

Add better support for Android 12+ Splash Screen APIs

### Steps to Reproduce

Add better support for Android 12+ Splash Screen APIs

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.60 SR6

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by jfversluis** [comment]
Duplicate of #10604
