### ISSUE TITLE
[iOS} Crashed: tid_103 EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

### ISSUE THREAD

**Issue by Parthu11** [dotnet/maui#23235]
### Description

maui app in background and phone is locked after sometime suspended app for ios devices.Below is all the information I have from Firebase

### Steps to Reproduce

 Crashed: tid_103
0  MyAppName                0x1ee080 MyAppName.ViewModels.ConnectRecorderViewModel:<ExecuteDeviceSelection>b__28_0 + 1 (<unknown>:1)
1  MyAppName                0x1ee078 MyAppName.ViewModels.ConnectRecorderViewModel:<ExecuteDeviceSelection>b__28_0 + 1 (<unknown>:1)
2  MyAppName                0x1ddca24 System.Reactive.AnonymousObserver`1<T_REF>:OnNextCore + 67 (AnonymousObserver.cs:67)
3  MyAppName                0x1deaaa0 System.Reactive.ObserverBase`1<T_REF>:OnNext + 36 (ObserverBase.cs:36)
4  MyAppName                0x1ddf1e0 System.Reactive.AutoDetachObserver`1<T_REF>:OnNextCore + 62 (AutoDetachObserver.cs:62)
5  MyAppName                0x1deaaa0 System.Reactive.ObserverBase`1<T_REF>:OnNext + 36 (ObserverBase.cs:36)
6  MyAppName                0x1fa4f2c System.Reactive.Linq.ObservableImpl.Do`1/Actions/_<TSource_REF>:OnNext + 158 (Do.cs:158)
7  MyAppName                0x1ddf1e0 System.Reactive.AutoDetachObserver`1<T_REF>:OnNextCore + 62 (AutoDetachObserver.cs:62)
8  MyAppName                0x1deaaa0 System.Reactive.ObserverBase`1<T_REF>:OnNext + 36 (ObserverBase.cs:36)
9  MyAppName                0x23bab68 Shiny.BluetoothLE.BleManager/<>c__DisplayClass9_1:<Scan>b__3 + 107 (BleManager.cs:107)
10 MyAppName                0x1ddccac System.Reactive.AnonymousSafeObserver`1<T_REF>:OnNext + 43 (AnonymousSafeObserver.cs:43)
11 MyAppName                0x1de5e5c System.Reactive.Sink`1<TTarget_REF>:ForwardOnNext + 50 (Sink.cs:50)
12 MyAppName                0x41312ac gsharedvt_out_trampoline + 68113984
13 MyAppName                0x2221d94 System.Reactive.Linq.ObservableImpl.SelectMany`2/ObservableSelector/_/InnerObserver<TSource_GSHAREDVT,_TResult_GSHAREDVT>:OnNext + 951 (SelectMany.cs:951)
14 MyAppName                0x4130c2c gsharedvt_trampoline + 68112320
15 MyAppName                0x1df2c84 System.Reactive.Subjects.Subject`1<T_REF>:OnNext + 147 (Subject.cs:147)
16 MyAppName                0x23b2248 Shiny.BluetoothLE.Internals.ManagerContext:DiscoveredPeripheral + 118 (ManagerContext.cs:118)
17 MyAppName                0x40a3078 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 67531788
18 MyAppName                0x4e5bb50 mono_jit_runtime_invoke + 3614 (mini-runtime.c:3614)
19 MyAppName                0x4d9c3c0 mono_runtime_try_invoke + 2399 (object.c:2399)
20 MyAppName                0x4d9e3ec mono_runtime_invoke + 2448 (object.c:2448)
21 MyAppName                0x4f271a0 native_to_managed_trampoline_41(objc_object*, objc_selector*, _MonoMethod**, objc_object*, objc_object*, objc_object*, objc_object*, unsigned int) + 2595 (registrar.mm:2595)
22 MyAppName                0x4f26d84 -[Shiny_BluetoothLE_Internals_ManagerContext centralManager:didDiscoverPeripheral:advertisementData:RSSI:] + 12213 (registrar.mm:12213)
23 CoreBluetooth                  0xe524 -[CBCentralManager handlePeripheralDiscovered:] + 1100
24 CoreBluetooth                  0xdd78 -[CBCentralManager handleMsg:args:] + 224
25 CoreBluetooth                  0xdc5c -[CBManager xpcConnectionDidReceiveMsg:args:] + 228
26 CoreBluetooth                  0xdb34 __30-[CBXpcConnection _handleMsg:]_block_invoke + 48
27 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
28 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
29 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
30 libdispatch.dylib              0xbf64 _dispatch_lane_invoke + 432
31 libdispatch.dylib              0x124b4 _dispatch_main_queue_drain + 748
32 libdispatch.dylib              0x121b8 _dispatch_main_queue_callback_4CF + 44
33 CoreFoundation                 0x3751c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
34 CoreFoundation                 0x34218 __CFRunLoopRun + 1996
35 CoreFoundation                 0x33968 CFRunLoopRunSpecific + 608
36 GraphicsServices               0x34e0 GSEventRunModal + 164
37 UIKitCore                      0x22aedc -[UIApplication _run] + 888
38 UIKitCore                      0x22a518 UIApplicationMain + 340
39 MyAppName                0x4b71df8 xamarin_UIApplicationMain + 131 (bindings.m:131)
40 MyAppName                0x4301730 ut_10429 + 70015684
41 MyAppName                0x422c444 UIKit.UIApplication:UIApplicationMain + 58 (UIApplication.cs:58)
42 MyAppName                0x422c65c UIKit.UIApplication:Main + 94 (UIApplication.cs:94)
43 MyAppName                0x162eec MyAppName.Program:Main + 1 (<unknown>:1)
44 MyAppName                0x40a3078 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 67531788
45 MyAppName                0x4e5bb50 mono_jit_runtime_invoke + 3614 (mini-runtime.c:3614)
46 MyAppName                0x4d9aa24 mono_runtime_invoke_checked + 2399 (object.c:2399)
47 MyAppName                0x4da2634 do_exec_main_checked + 4419 (object.c:4419)
48 MyAppName                0x4e61b38 mono_jit_exec + 1365 (driver.c:1365)
49 MyAppName                0x4b8619c xamarin_main + 490 (monotouch-main.m:490)
50 MyAppName                0x4f19398 main + 474 (main.arm64.mm:474)
51 ???                            0x1bf252d84 (Missing)
        

### Link to public reproduction project repository

N/A

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.100

### Affected platforms

iOS

### Affected platform versions

ios 17.4.1

### Did you find any workaround?

Yes, this used to work in Xamarin.Forms

### Relevant log output

```shell
N/A
```

**Comment by jfversluis** [comment]
Thanks for this report! Unfortunately without any relevant code or a reproduction it will be near to impossible to diagnose what is going on here. So please provide a lot more detail and ideally a reproduction project on a public repository so we can have a look.

I also see that you mention .NET 7 as the version you're using, you might want to consider to update to .NET 8 to see if that resolves the issue for you.

**Comment by Parthu11** [comment]
Debugging after I found a crash in this code, why?


if (string.Compare(x.Peripheral.Name, _prevSelectedSerNum.Name) == 0)
                                            {
                                                try
                                                {
                                                    _curSelectedSerNum = _prevSelectedSerNum;
                                                }
                                                catch (Exception ex)
                                                {
                                                    DependencyService.Get<ICrashlyticsService>().RecordException(ex);
                                                }

                                            }

**Comment by jfversluis** [comment]
Thank you for that, I'm afraid this is a bit thin still to further investigate. Please refer to the [doc](https://github.com/dotnet/maui/blob/main/.github/repro.md) we have on reproductions, that might give you an idea of what we are looking for.

Additionally I asked for some more information about other things, but maybe you have read over that. Without this information or anything to make this issue more actionable, I'm afraid I'm going to have to close it.

Thanks!
