### ISSUE TITLE
VisualElement.OnMeasure currently routes to some inconsistent logic compared to OnMeasureOverride

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#23244]
### Description

VE.OnMeasure follows this path

![image](https://github.com/dotnet/maui/assets/5375137/6a1bc065-fad6-4a00-8ff1-28c8a8244467)

Which calls this

![image](https://github.com/dotnet/maui/assets/5375137/73df9338-5be3-4d3a-ace1-6f7bf1c38b0c)

It should probably call this in both places of the `OnMeasure` override

![image](https://github.com/dotnet/maui/assets/5375137/043695cb-e424-4cca-b56d-7d0e500a4169)

The checks on the constraints of "0" also is going to cause inconsistent behavior. MAUI treats zero as zero.

We should review all the measure code inside `VisualElement` and just force everything to route to the MAUI paths. 

Right now we hit a lot of inconsistent behavior because

button.Measure
and
(button as IView).Measure

Do different things. 

we should make it so those both do the same thing and then if users need to switch back to old behavior they can via a switch.

**Comment by mattleibow** [comment]
This is the new logic in OnMeasure after my PR https://github.com/dotnet/maui/pull/23725:

<img width="700" alt="image" src="https://github.com/user-attachments/assets/a698bdfe-a6aa-4811-a35c-7ad10efdd508">

**Comment by mattleibow** [comment]
Why do we have both, and why does the old Measure -> OnMeasure do a whole bunch of min/max checks where the new one just returns the size?

They seem to be very different. IView.Measure -> MeasureOveride is _just_ the desired size, but the old one is trying to do more. Do we even use the old path?

**Comment by bradencohen** [comment]
Can this also be fixed for `Arrange`?:  #17417
