### ISSUE TITLE
IsNullOrWhiteSpace with non-string

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2324]
Hi,

When using IsNullOrWhiteSpace with a Value returns double, for example Range control or Rating control it thriws an error:

**Error CS1503: Argument 1: cannot convert from 'double' to 'string'**

This should be fixed because it says Null OR and if the value is not set then it's null otherwise what is the difference between:

`if (string.IsNullOrWhiteSpace(RateBusinessModel.Value))
`
and:

`if (RateBusinessModel.Value != null)
`

**Comment by Askar938** [comment]
`string.IsNullOrWhiteSpace` expects a string as the argument, not a double.
If you want to use `string.IsNullOrWhiteSpace` you must first convert your `double` to a `string` by calling `.ToString()`.
Also, this issue isn't specific to .NET MAUI, it probably belongs to https://github.com/dotnet/csharplang.

**Comment by davidbuckleyni** [comment]
Yeah as above says its by design its not an error it must be converted to string.
