### ISSUE TITLE
net8 MainPage.xaml   Button problem  Clicked = "OnClickButton5" does not work!!!<?xml version="1.0" encoding="utf-8" ?> <ContentPage xmlns="http://sch

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#23253]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/net8-MainPagexaml---Button-problem--Cli/10688716)._

---
[severity:I'm unable to use this version] [regression] [worked-in:it has not worked yet]
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:Zl1800LPIphone"
             x:Class="Zl1800LPIphone.YourPage"
             xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             Title="IsEqualConverterPage">

<AbsoluteLayout>

        <Button x:Name="Button5"
           Text="EXIT"
           FontSize="14"
           AbsoluteLayout.LayoutFlags="PositionProportional"
           WidthRequest="69"
           AbsoluteLayout.LayoutBounds="70, 130, 68, 50"
           Clicked = "OnClickButton5"/>

Clicked = "OnClickButton5"/> does not compare event handler correctly

---
#### Feedback Bot on 6/23/2024, 06:53 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Unfortunately this does not contain enough detail to be actionable. Please provide more relevant code, a detailed description of what you're trying to do and ideally a reproduction project.

Closing this one, feel free to open a new issue directly on this repository providing all the requested information. Thanks!
