### ISSUE TITLE
SetCornerRadius of GradientDrawable doesn't work anymore

### ISSUE THREAD

**Issue by WMLPB** [dotnet/maui#23267]
### Description

Hi All,

Because of MAUI didn’t have a ripple effect for a long time I created my own `RippleBehavior` class for Android. This worked fine up until MAUI version 8.0.40.

With MAUI version 8.0.60 `SetCornerRadius` of GradientDrawable on Android doesn’t work anymore and there seems to be a problem with `SetColors` as well. Please see the following screenshots:

![Screenshot](https://github.com/dotnet/maui/assets/150668629/15fd9305-5f03-4bba-9c4b-fb7a3656e8fd)

What is strange: Only the ImageButton seems to be affected. When I put an Image into a Grid, it still works.

I’m sorry, I can’t provide a repository because of company policy. But I’ve attached a sample application. Thank you very much for help.

[MauiApp1.zip](https://github.com/user-attachments/files/15985345/MauiApp1.zip)

### Steps to Reproduce

Please run the sample.

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

Android

**Comment by RoiChen001** [comment]
I can repro this issue at Android platform on the latest 17.11.0 Preview 2.1(8.0.60). But the problem doesn't exist on 8.0.40.

**Comment by KarthikRajaKalaimani** [comment]
Hi @WMLPB , 

In version 8.0.60, a RippleDrawable background was introduced for the ImageButton. This change causes the true block of code to execute, which sets the ripple color for the ImageButton, as its background is now a RippleDrawable. Conversely, the false block will execute for the Grid, where both the corner radius and ripple color are applied correctly.

To set a corner radius for an ImageButton with a RippleDrawable background, the best workaround is to use the CornerRadius property of the ImageButton. Alternatively, you can retrieve the GradientDrawable from the RippleDrawable and set the corner radius on the GradientDrawable, as shown in the screenshot below.
![image](https://github.com/user-attachments/assets/8d5a7c92-5dd1-49f0-a85c-ba9d87b4bdd7)

**Comment by mattleibow** [comment]
If you were using your ripple behaviour and now it is causing issues because we fixed it, what happens if you do not use your behaviour? Does the ripple work as expected?
