### ISSUE TITLE
Throwing in a background thread freezes the UI when debugging a MAUI app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#23261]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Throwing-in-a-background-thread-freezes-/10639803)._

---
[severity:It's more difficult to complete my work]
Hi, i'v created a new MAUI project with the simple click the button feature, added a looping background thread throwing rapidely and it freezes the UI (clicking fast on the button does not refresh the count directly) ONLY when in debugging mode and not while in the 'Start without debugging' mode.

I also tried disabling all exception handling in VS as seen in the video, but it still lags when debugging. I did a Dotnet/maui github issue and they redirected me here since they couldnt reproduce (https://github.com/dotnet/maui/issues/21741)

---
#### Feedback Bot on 4/16/2024, 07:28 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drasticactions** [comment]
Closing in favor of reopening https://github.com/dotnet/maui/issues/21741
