### ISSUE TITLE
Cannot use Shared Project with MAUI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#23260]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-use-Shared-Project-with-MAUI/10651324)._

---
[severity:It's more difficult to complete my work]
In my MAUI project I want to use some shared sources like I used in Xamarin project - creating Shared Project from the VS template.
I prefer this instead of compiling into class lib (which has another problems).
I want to put some xaml and corresponding xaml.cs files into this Shared Project.
But after moving the files from the standalone compilable project to the shared one (and adding reference) I have a compile errors (example component SplLabel):

Error (active)	CS0122	'SplLabel.InitializeComponent()' is inaccessible due to its protection level

I also cannot select MauiXaml as a Build Action for SplLabel.xaml and trying to force it gives the error:

An error has occurred while saving the edited properties listed below:
	Build Action
One or more values are invalid. The item type 'MauiXaml' is not supported by this project item provider.

Does it mean I cannot use the very usable Shared Project in MAUI like it was possible in Xamarin Forms ?

Best regards, Tomasz

---
#### Feedback Bot on 5/2/2024, 06:31 PM: 

(private comment, text removed)
#### Mandy Yu(CSI Interfusion Inc) [MSFT] on 5/6/2024, 10:41 PM: 

(private comment, text removed)
#### Tomasz Barczyk on 5/10/2024, 10:14 AM: 

(private comment, text removed)
#### Mandy Yu(CSI Interfusion Inc) [MSFT] on 5/11/2024, 01:48 AM: 

(private comment, text removed)
#### Tomasz Barczyk on 5/25/2024, 11:52 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
In your `projitems` file change 

```xml
    <Page Include="$(MSBuildThisFileDirectory)NewPage1.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
```

to

```xml
    <MauiXaml Include="$(MSBuildThisFileDirectory)NewPage1.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
```

Then it compiles. We're still using this approach in one of our own projects: https://github.com/dotnet/maui/blob/main/src/Compatibility/ControlGallery/src/Issues.Shared/Compatibility.ControlGallery.Issues.Shared.projitems

While you can make it work, I doubt if the tooling will be very helpful and if there will be much investment in making that better. I don't think we have officially deprecated shared projects, but it is also not very much used anymore.

Hope this will help you!
