### ISSUE TITLE
[MAUI] I4_ Selection - The default items not highlight in Single Pre-selection and Multiple Pre-selection Page

### ISSUE THREAD

**Issue by QianaJiao** [dotnet/maui#23299]
### Description

Affected case:
Single Pre-selection (Vertical list)
Multiple Pre-selection (Vertical list)

### Steps to Reproduce

**Steps to Reproduce**

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Windows.
2. Navigate to 'I CollectionView' ->'I4 Selection '
3. Open Single Pre-selection or Multiple Pre-selection Page
4. Check the default items should be highlighted

**Actual Behavior:**
![image](https://github.com/dotnet/maui/assets/91244512/2f014c93-00b3-4dc6-8099-fe229a60a32e)

**Expected Behavior:**
The fourth item should be highlighted by default. 

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug
Microsoft.Maui.Controls 8.0.70-ci.net8.24325.2

### Is this a regression from previous behavior?
Not a regression, The issue also repro on 8.0.61& 8.0.3

### Affected platforms

iOS, Windows, macOS

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3.0 [35025.246.main] (8.0.61 & 8.0.70-ci.net8.24328.1). Not repro. So I closed this issue.

**Comment by ninachen03** [comment]
It fixed in android platform, others platform still repro.

**Comment by davidortinau** [comment]
I see this on .NET 9 RC2 on iOS and Mac Catalyst. The initial selection based on SelectedItem is not showing the Selected visual state. Works as expected on Android.
