### ISSUE TITLE
CarouselView - iOS - Changing Position no longer works after navigation away then coming back

### ISSUE THREAD

**Issue by ryanalford-suzy** [dotnet/maui#23291]
### Description

On iOS, programmatically changing the `Position` of the CarouselView no longer works if you navigate away and come back when using Shell navigation.

Android works fine.

EDITED: Tested using NavigationPage instead of Shell navigation, and the issue still exists.

### Steps to Reproduce

1. Run the project
2. Tap the bottom buttons to see the CarouselView switch between fragments.
3. Tap the Open Second Page button
4. Tap the Back button at the top left.
5. Tap the bottom buttons again.

### Link to public reproduction project repository

https://github.com/ryanalford-suzy/CarouselViewTest

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

iOS

### Affected platform versions

iPhone - iOS 16.7.7, iOS Simulator 17.4 

### Did you find any workaround?

No workaround

**Comment by RoiChen001** [comment]
I can repro this issue at iOS platform on the latest 17.11.0 Preview 2.1(8.0.60).

**Comment by watfordsuzy** [comment]
Proximate cause? https://github.com/dotnet/maui/pull/22861

**Comment by PureWeen** [comment]
@RoiChen001 were you able to confirm if this works on 8.0.40 and regressed in later versions?

**Comment by ryanalford-suzy** [comment]
I've added a second branch in the sample repo that targets 8.0.40.

Make sure to delete bin/obj folders when switching maui versions.

**Comment by RoiChen001** [comment]
@PureWeen  Yes, it works fine at iOS platform on 17.11.0 Preview 2.1(8.0.40).
