### ISSUE TITLE
[MAUI]I5-EmptyView- filter not responding.

### ISSUE THREAD

**Issue by ninachen03** [dotnet/maui#23301]
### Description

Affected case:
I5 - EmptyView String for Filtering.
I5 - EmptyView with multiple views for Filtering.
I5 - EmptyView with EmptyViewTemplate for Filtering.
I5 - EmptyView with EmptyViewTemplate for Data template selector.
I5 - EmptyView swap for Filtering.

### Steps to Reproduce

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Windows.
2. Navigate to 'I CollectionView' ->'I5 Selection '
3. Open any case for Filtering
4. Type any word then search.

Actual Behavior: filter not responding.
![Filter](https://github.com/dotnet/maui/assets/128687574/30f1b41d-4421-4e8f-a1b3-967f29b77a21)

Expected Behavior:
Filter works fine, can filter items by search term.

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug
Microsoft.Maui.Controls 8.0.70-ci.net8.24326.4

### Is this a regression from previous behavior?

Not a regression, The issue also repro on 8.0.61& 8.0.3

### Affected platforms

iOS, Android, Windows, macOS

**Comment by Nina-1210** [comment]
@ninachen03 The issue has been fixed in this PR: [https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml/pullrequest/560855](https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml/pullrequest/560855), please download the latest code and try again.

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3.0 [35025.246.main] (8.0.61 & 8.0.70-ci.net8.24328.1). Not repro. So I closed this issue.
