### ISSUE TITLE
[MAUI] Unable to scroll up and down

### ISSUE THREAD

**Issue by ninachen03** [dotnet/maui#23309]
### Description

Affected case:
all I3,I4,I5,I6,I7,I8,I9

### Steps to Reproduce

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to MacCatalyst.
2. Navigate to 'I CollectionView' ->'i3_Sizing->Variable size items. (all I3,I4,I5,I6,I7,I8,I9 case.)

Actual Behavior: Unable to scroll up and down

![Scrolled](https://github.com/dotnet/maui/assets/128687574/3dca8c3c-d982-47c7-81f5-88fc9797f334)
Expected Behavior:
Can scroll up and down.

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

Microsoft.Maui.Controls 8.0.70-ci.net8.24326.4

### Is this a regression from previous behavior?
Not a regression, The issue also repro on 8.0.61& 8.0.3

### Affected platforms

iOS, Android, Windows, MacOS

**Comment by Nina-1210** [comment]
@ninachen03 The issue has been fixed in this PR: [https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml/pullrequest/560855](https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml/pullrequest/560855), please download the latest code and try again.

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3 (8.0.80-ci.net8.24360.1). Cannot repro it.
