### ISSUE TITLE
[MAUI] I1_Layout - Horoizontal grid for DataTemplate & Horoizontal grid for Text pages display only three-rows grid.

### ISSUE THREAD

**Issue by kevinxufei** [dotnet/maui#23303]
### Description

Horoizontal grid for DataTemplate & Horoizontal grid for Text pages display only three-rows grid

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to iOS simulator.
2.Navigate to 'I CollectionView' ->'I1 Layout' -> 'Horoizontal grid for DataTemplate' & 'Horoizontal grid for Text'.
3.The pages display only three-rows grid.

**Actual Behavior:**
The pages display only three-rows grid.
![image](https://github.com/dotnet/maui/assets/86938401/6ccd9793-0d93-443b-a46d-0968c771ca9a)

**Expected Behavior:**
The pages should display four-rows grid.
![image](https://github.com/dotnet/maui/assets/86938401/2d104cb2-e678-46a0-8a77-1758aaba4bf1)

### Link to public reproduction project repository
https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug
Microsoft.Maui.Controls 8.0.70-ci.net8.24326.4

### Is this a regression from previous behavior?
Not a regression, The issue also repro on 8.0.61& 8.0.3

### Affected platforms
iOS

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio Code 1.90.2 (8.0.61 & 8.0.70-ci.net8.24328.1). Not repro on iOS platform.
So I closed this issue.
