### ISSUE TITLE
[Bug] [Android] Wrong text color in menu items

### ISSUE THREAD

**Issue by mterhorst** [dotnet/maui#2330]
### Description

I noticed that the text color of the menu item isn't readable anymore.
![image](https://user-images.githubusercontent.com/24865628/131513748-0d2773ba-f323-4f49-9e10-319ceb4abf5d.png)

### Steps to Reproduce

1. CLI `dotnet maui new`
2. Set `MainPage` to use a `NavigationPage`
3. Add a toolbar with order value `Secondary`
4. Run

### Basic Information

- Version with issue: 6.0.0-rc.1.21426.8
- Last known good version: 6.0.0-preview.7.21377.19
- IDE: Visual Studio 2022 Preview 3.1
- Platform Target Frameworks: 
  - Android: 5.0

**Comment by mterhorst** [comment]
I seem to not see this problem anymore. I will close if no one says otherwise.

**Comment by PureWeen** [comment]
@mterhorst thank you for retesting and following up!!
