### ISSUE TITLE
Debugging MAUI gives "Could not found a valid Xcode app bundle at..."

### ISSUE THREAD

**Issue by ebugge** [dotnet/maui#23326]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: macos

When trying to debug the application from the tutorial I get this error. I am not sure where to set this preference as I do not use Visual Studio for Mac.

`/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(1838,3): error : Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools'. Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK). [/Users/ME/repos/private/MyFirstMauiApp/MyFirstMauiApp/MyFirstMauiApp.csproj::TargetFramework=net8.0-maccatalyst]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/17.2.8053/tools/msbuild/iOS/Xamarin.Shared.targets(1838,3): error :          [/Users/ME/repos/private/MyFirstMauiApp/MyFirstMauiApp/MyFirstMauiApp.csproj::TargetFramework=net8.0-maccatalyst]`

I tried running `xcode-select -p` which gave me this result: `/Library/Developer/CommandLineTools`. So the setting seems to be correct?

**Comment by jfversluis** [comment]
Hey there, glad to see you're trying .NET MAUI! Sorry you're running into a snag here.

Did you try and start Xcode? It might prompt you to install additional command-line tools. Does it do that, and if you install those, does this error go away?

I also see some thing here that might help: https://github.com/dotnet/maui/issues/3888#issuecomment-1003880709

Could you let me know? Thanks!

**Comment by ebugge** [comment]
@jfversluis Your link to #3888 helped me out. When I opened the option, the drop-down was already set to "Xcode ver. xx". I set to it to blank and then back to "Xcode ver. xx", restarted VS Code and now it works. Thanks!

**Comment by jfversluis** [comment]
Perfect, thanks for letting us know and have fun with your .NET MAUI adventures!
