### ISSUE TITLE
Frame offsets inner content view by 1pt

### ISSUE THREAD

**Issue by filipnavara** [dotnet/maui#23333]
### Description

The `Frame` control implements the `IBorderElement` interface and unconditionally returns `IBorderElement.BorderWidth => 1` whether the border is visible or not. The default color for the border is `null`.

In Xamarin.Forms you could make a round frame by instantiation `Frame` with `IsClippedToBounds = true, CornerRadius = N/2, WidthRequest = N, HeightRequest = N` (roughly) and the inner content view set to the `Content` property would be clipped to a circle.

In MAUI, however, the inner view is offset by the `IBorderElement.BorderWidth` during layout. If you set `BackgroundColor` to `Colors.Tan` and then the background of the inner content to something else, you'll notice that the "border area" remains tan despite the frame having no border set.

Example of the visual artifact:
<img width="136" alt="image" src="https://github.com/dotnet/maui/assets/1764393/8525e459-5548-4f0f-b41e-11bc63230550">

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

Yes, implement `IBorderElement.BorderWidth` in our control derived from `Frame` and return 0.

**Comment by PureWeen** [comment]
@filipnavara TBH this probably won't get scheduled any time soon. 

We're marking `Frame` as obsolete in .NET9 so that's where we'll be putting most of our effort

**Comment by filipnavara** [comment]
I filed the issue mostly to make it easy to search for a workaround, and I don’t expect it to get any prioritisation at all. Once I figured the root cause the workaround was just 8 lines of code in our project.
