### ISSUE TITLE
Incorrect CollectionView height inside VerticalStackLayout

### ISSUE THREAD

**Issue by lucasbrahm** [dotnet/maui#23359]
### Description

With a CollectionView inside a VerticalStackLayout, it is expected that the CollectionView will grow with the remaining space available of the page and the itens of the collection should be scrollable.

But what is happening is that CollectionView is growing until the height size to display all itens, being this height greater than the page size, making it impossible to scroll to the last element.

Specifying the height (HeightRequest) of the CollectionView is a workaround, but I want it to grow with the remaining space.

### Steps to Reproduce

1. Create a page with a VerticalStackLayout and add CollectionView inside of it.
2. Add a lot of itens the CollectionView (enough to need to be scrollable).
3. As CollectionView grew greater than page height, it is not possible to scroll to the last element.

### Link to public reproduction project repository

https://github.com/lucasbrahm/MauiTestBugVerticalStackLayoutCollectionView

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

Specifying the height (HeightRequest) of the CollectionView

**Comment by albyrock87** [comment]
Afaik `VerticalStackLayout` is supposed to grow indefinitely (it sets no vertical constraint on the children`.
To achieve what you probably want, a `Grid` must be used, or you can simply put the collection view as page content.

**Comment by RoiChen001** [comment]
I can repro this issue at Android platform on the latest 17.11.0 Preview 2.1(8.0.61).
