### ISSUE TITLE
[Bug] System.Exception: 'Handler not found for view Microsoft.Maui.Controls.Compatibility.RelativeLayout.'

### ISSUE THREAD

**Issue by laipd** [dotnet/maui#2335]
I want to use "RelativeLayout", i have use
==> xmlns:cmp="clr-namespace:Microsoft.Maui.Controls.Compatibility;assembly=Microsoft.Maui.Controls"
and "<cmp:RelativeLayout>", but have error.
please help me
thanks.

![image](https://user-images.githubusercontent.com/29567846/131505131-2c76306b-460b-4b26-b608-07de08a664f5.png)

=====> error

![image](https://user-images.githubusercontent.com/29567846/131505032-3e062f9c-8d01-4006-baa1-117229c3faa2.png)

**Comment by Askar938** [comment]
I am experiencing the same.
Possibly related to #2062.

**Comment by laipd** [comment]
@Askar938 
Looks like MAUI layout still has many problems to deal with.
now i am facing problem of menu layout like (file -> opent,new..) has sub menu, do you have any solution for my problem.
thanks a lot.

**Comment by laipd** [comment]
i have resolve problem with example under.
https://github.com/dotnet/maui/blob/main/src/Controls/samples/Controls.Sample/Pages/Layouts/RelativeLayoutPage.xaml
