### ISSUE TITLE
MauiSplashScreen when setting the color to #FFFFFF and #FFF

### ISSUE THREAD

**Issue by ExtroZ-ui** [dotnet/maui#23361]
### Description

When in the project assembly we set the color white in MauiSplashScreen
it turns to gray, and the color is set only on the image itself

### Steps to Reproduce

<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#FFF"/>

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13.0 - API 33

### Did you find any workaround?

Use a different shade of white

**Comment by ExtroZ-ui** [comment]
![Screenshot_2024-06-29-19-29-21-445_com.companyname.otpeoffice24.jpg](https://github.com/dotnet/maui/assets/64098846/9c6f9c9d-049f-400c-8a98-45ebaec1fc53)

**Comment by jfversluis** [comment]
I'm not sure I understand. Could you please explain a little more and maybe add some relevant code?
