### ISSUE TITLE
Assets file '... QueryEngine\obj\project.assets.json' doesn't have a target for 'net7.0'. 

### ISSUE THREAD

**Issue by robreno** [dotnet/maui#23368]
### Description

When Project -> Publish -> Create App Packages is run it fails with:

1>Assets file 'C:\Archive\Projects\UBViews_2023\UBViews\QueryEngine\obj\project.assets.json' doesn't have a target for 'net7.0'. Ensure that restore has run and that you have included 'net7.0' in the TargetFrameworks for your project.
1>Assets file 'C:\Archive\Projects\UBViews_2023\UBViews\QueryFilter\obj\project.assets.json' doesn't have a target for 'net7.0'. Ensure that restore has run and that you have included 'net7.0' in the TargetFrameworks for your project.
1>Assets file 'C:\Archive\Projects\UBViews_2023\UBViews\LexParser\obj\project.assets.json' doesn't have a target for 'net7.0'. Ensure that restore has run and that you have included 'net7.0' in the TargetFrameworks for your project.

### Steps to Reproduce

This is a ebook/audiobook Maui App that uses FSharp projects for accessing SQLite databases. The App compiles and runs on Windows locally just fine, but I am unable to create MSIX or App Packages.

### Link to public reproduction project repository

https://github.com/robreno/UBViews.net7

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

Without solving this problem, I cannot publish app.

**Comment by robreno** [comment]
I am completely unable to publish or sideload this app. Please, I need some help.

**Comment by RoiChen001** [comment]
I can publish it successfully using the latest 17.10.3.
![image](https://github.com/dotnet/maui/assets/143168639/2affd2ce-951c-4551-8d13-1708965f7d74)
