### ISSUE TITLE
Failure Building Due to Splash Screen Image splashSplashScreen.png

### ISSUE THREAD

**Issue by nguyenvuhoang** [dotnet/maui#23363]
### Description

Failure Building Due to Splash Screen Image splashSplashScreen.png

### Steps to Reproduce

Failure Building Due to Splash Screen Image splashSplashScreen.png

### Link to public reproduction project repository

Failure Building Due to Splash Screen Image splashSplashScreen.png

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.61 SR6.1

### Affected platforms

Windows

### Affected platform versions

window

**Comment by Zhanglirong-Winnie** [comment]
Hi, @nguyenvuhoang 
We would like to try to reproduce your issue. Can you provide more information, such as sample projects, screenshots, error messages, etc.

**Comment by ewerspej** [comment]
Have you tried renaming your splash screen file to just "splash.png"?

**Comment by Zhanglirong-Winnie** [comment]
Yes, I tried renaming your splash screen file to just "splash.png"
This issue has been verified using Visual Studio 17.11.0 Preview 2.1(8.0.61). Not repro on windows platform. 
![image](https://github.com/dotnet/maui/assets/77434865/7247f1a1-a1b5-408d-aeb3-fa63df30f1d7)
