### ISSUE TITLE
CollectionView Footer - Deleting Items From the Collectionview hides the Content Of The Footer

### ISSUE THREAD

**Issue by Cr15Denis** [dotnet/maui#23387]
### Description

I have a data collection and a collection footer and when deleting items from the collection the footer is hidden or shown when interacting with item deletions. When deleting the first item nothing happens, after deleting the second item the problem occurs.

https://github.com/dotnet/maui/assets/70722700/a3571741-26a4-43aa-8fb4-888e5cd2770d

### Link to public reproduction project repository

https://github.com/Cr15Denis/CollectionViewFooterBug

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 2.1(8.0.61 & 8.0.40). Can repro on Android platform.

**Comment by jsuarezruiz** [comment]
Similar or duplicate https://github.com/dotnet/maui/issues/23700

**Comment by kubaflo** [comment]
https://github.com/user-attachments/assets/6b4d9d39-b9e2-4b4a-b71f-6beaa60630a2

It seems to be working fine in Net9

**Comment by Cr15Denis** [comment]
Hello friend @kubaflo, it works well in .net 9 :)

**Comment by kubaflo** [comment]
Cool! So, I will close this one :)
