### ISSUE TITLE
Android - NullReferenceException thrown from ItemContentView

### ISSUE THREAD

**Issue by markmccaigue** [dotnet/maui#23394]
### Description

We are seeing a crash caused by a NullReferenceException thrown from Microsoft.Maui.Controls.Handlers.Items.ItemContentView.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Items.ItemContentView.OnMeasure(Int32 widthMeasureSpec, Int32 heightMeasureSpec) in D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\ItemContentView.cs:line 179
   at Android.Views.View.n_OnMeasure_II(IntPtr jnienv, IntPtr native__this, Int32 widthMeasureSpec, Int32 heightMeasureSpec) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.View.cs:line 19598
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPII_V(_JniMarshal_PPII_V callback, IntPtr jnienv, IntPtr klazz, Int32 p0, Int32 p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 154
```

The stack traces sometimes point to line 179, and sometimes to line 196. Both of these are inside the OnMeasure function, and both have references to the View property with no null checks.

I suspect there could be a race condition whereby View can be null, as we are only seeing this with fast scrolling in a complex rendering scenario where the rendering might be a bit slow. We've only seen this thrown on Android 11 devices, although it's tough to say for certain that's the only affected OS.

I'm not sure if it's logical for View to be null in these locations, but there is a null check on the View property elsewhere in the ItemContentView, which suggests null handling logic has been applied in some scenarios and perhaps could be added in these two locations also.

Due to the complexity of the views involved, I don't have a simple reproduction project for this one, but hopefully the code references I have provided are helpful enough to narrow down the issue. I have also not tested a range of MAUI versions, but the main branch still has the references to View with no null checking, so I would suspect the issue is present there.

### Steps to Reproduce

1. Fast scrolling of a collection view with complex views and infinite scrolling on Android 11.
2. Observe NullReferenceExceptions at lines 196 and 179 of Microsoft.Maui.Controls.Handlers.Items.ItemContentView

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by markmccaigue** [comment]
Quick comment to confirm the crash still happens on 8.0.61.

**Comment by PureWeen** [comment]
This looks like this would happen if something were to call disconnecthandler on any of the views inside the CollectionView

Do you by chance know the type of view that's throwing a NRE?

I suspect if we fixed this with a null check the result would just be blank cells. The View that's attached to the handler here really shouldn't be getting disconnected from the virtual view.

**Comment by markmccaigue** [comment]
> This looks like this would happen if something were to call disconnecthandler on any of the views inside the CollectionView
> 

You are totally right, and this helped us find the issue, thank you. We have some code which runs on the "unloaded" event, after some further checks to ensure we are "really done" with some views, to perform cleanup, including calling DisconnectHandler. It turns out that this code was running when the header of our CollectionView was recycled during scrolling, when our intention would have been to run it only when the user navigates away permanently from the CollectionView.

I would imagine that it's a bad idea to cleanup views which are being held during recycling for later re-use, and so we've added more checks to ensure we can differentiate between these two scenarios and leave the recycled views alone, and now the crash is no longer present.

> Do you by chance know the type of view that's throwing a NRE?

In terms of the virtual view it was a custom Content View, which contained a PanCardView.CarouselView, which rotated through autoplaying video previews, hence we're trying to be aggressive about memory cleanup. I believe this would make the platform view a ContentViewGroup.

> I suspect if we fixed this with a null check the result would just be blank cells. The View that's attached to the handler here really shouldn't be getting disconnected from the virtual view.
> 
> Are you using a `Frame` anywhere? Maybe try switching to a `Border` control

Could you say more about your hunch on the Frame usage, please? We make use of a lot of frames, including in this view, and it does seem relevant.

Whilst I was experimenting I did manage at one point to hit the below exception 


```
System.NotSupportedException: Unable to activate instance of type Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer from native handle 0x7fc5c61354 (key_handle 0xa539ab2).
 ---> System.MissingMethodException: No constructor found for Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
 ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
```

which did go away when converting to Borders. Ultimately this wasn't the direct cause of the problem, and the fix we applied is working with the Frames, but if there's an issue with Frames we'd be glad to hear more so we could start work on moving to Borders - we have been doing so, but still have a few dozen Frames in our app. Thanks again!

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 5.0(8.0.70&8.0.60&8.0.40). Can repro on Android platform.

**Comment by jsuarezruiz** [comment]
> This issue has been verified using Visual Studio 17.11.0 Preview 5.0(8.0.70&8.0.60&8.0.40). Can repro on Android platform.

What example did you use to reproduce the issue?
