### ISSUE TITLE
Scrolling on a List View causes massive memory leak

### ISSUE THREAD

**Issue by ajsuydam** [dotnet/maui#23406]
### Description

Unfortunately, providing repro code is going to be difficult, as this issue is presenting on an internal project.

However, I have a custom collection that is both observable and thread-safe (concurrent). I implemented it by adding `INotifyCollectionChanged` and `INotifyPropertyChanged` to a standard `Collection<T>`. It's very simple, no frills. Simply locks for reads and writes and implements busy waiting.

I have a ListView that is using that collection ("Messages") as it's ItemSource. There are hundreds to thousands of items in the collection. If I scroll on the collection, I get a runaway memory leak.

Here is the code for the ListView:

```XAML
<ListView
    x:Name="LogConsole"
    CachingStrategy="RecycleElement"
    HasUnevenRows="False"
    HeightRequest="800"
    ItemsSource="{Binding Messages}">
    <ListView.ItemTemplate>
        <DataTemplate x:DataType="mydatatype">
            <ViewCell>
                <Border BackgroundColor="Transparent">
                    <Grid Padding="10">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="1*" />
                            <ColumnDefinition Width="1*" />
                            <ColumnDefinition Width="1*" />
                            <ColumnDefinition Width="5*" />
                        </Grid.ColumnDefinitions>

                        <Grid.RowDefinitions>
                            <RowDefinition Height="Auto" />
                        </Grid.RowDefinitions>

                        <Label
                            Grid.Column="0"
                            FontAttributes="Bold"
                            Text="{Binding Peroperty1, Mode=OneTime}"
                            VerticalTextAlignment="Center" />
                        <Label
                            Grid.Column="1"
                            FontAttributes="Bold"
                            Text="{Binding Property2, Mode=OneTime}"
                            VerticalTextAlignment="Center" />
                        <Label
                            Grid.Column="2"
                            FontAttributes="Bold"
                            Text="{Binding property3, Mode=OneTime}"
                            VerticalTextAlignment="Center" />
                        <Label
                            Grid.Column="3"
                            Text="{Binding Property4, Mode=OneTime}"
                            VerticalTextAlignment="Center" />
                    </Grid>
                </Border>

            </ViewCell>

        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```

Here is a screenshot of heap analysis number 1
![image](https://github.com/dotnet/maui/assets/137317087/48e73a53-c827-47b9-884b-09a027384e0e)

Number two:
![image](https://github.com/dotnet/maui/assets/137317087/10899f85-b3f9-41da-9074-cb57dff48a1c)

I added the OneTime binding mode and the Border wrapping as a result of some googling that I have done (hours worth, btw), and they have helped, but not completely eliminated the problem. Are there good ways of debugging where these issues are coming from?

Could someone help me understand why this is happening? I am a total newbie to memory leak issues, and I'm not sure where my issues begin and MAUI's end. This is our first hop into MAUI as a company and there is a lot riding on this.

### Steps to Reproduce

N/A

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows Build 22631.3737

### Did you find any workaround?

Not yet.

**Comment by ajsuydam** [comment]
> Hi I'm an AI powered bot that finds similar issues based off the issue title.
> 
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!
> ### Open similar issues:
> 
>     * [Memory Leak with CollectionView (#14993)](https://github.com/dotnet/maui/issues/14993),  similarity score: 0.80
> 
>     * [Memory leak reloading list items on Windows (#18030)](https://github.com/dotnet/maui/issues/18030),  similarity score: 0.80
> 
> 
> ### Closed similar issues:
> 
>     * [Memory leaks EVERYWHERE (#12039)](https://github.com/dotnet/maui/issues/12039),  similarity score: 0.82
> 
>     * [Massive memory leak in CollectionView while scrolling (#10560)](https://github.com/dotnet/maui/issues/10560),  similarity score: 0.81
> 
>     * [ListView/CollectionView memory leak under Windows (#9162)](https://github.com/dotnet/maui/issues/9162),  similarity score: 0.81
> 
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

While all of those are similar, unfortunately they do not cover my specific issue. They were good reads though and help me not feel so bad that I'm causing gigs of memory to leak. Seems like there's a lot of work to do. 

In the mean time, another question is if there are any good alternatives to ListView. That is a potential work around.

**Comment by PureWeen** [comment]
@ajsuydam Have you tried CollectionView?

**Comment by ajsuydam** [comment]
@PureWeen so that's weird, I just tried it, and the exact same code (just switching out ListView for Collection View) gives me a null reference exception. It's supposed to be a drop-in replacement right?

**Comment by ajsuydam** [comment]
@PureWeen Ok can confirm the issue is not present with the CollectionView. Not sure why that is though....

**Comment by jonathanpeppers** [comment]
@ajsuydam do you see the same issue in a sample app with a `ListView`? Can you share a sample project?

In the [nightly build](https://github.com/dotnet/maui/wiki/Nightly-Builds), we should have fixed a problem for `ListView` on iOS, but not Windows:
* https://github.com/dotnet/maui/pull/23143

**Comment by ajsuydam** [comment]
> @ajsuydam do you see the same issue in a sample app with a `ListView`? Can you share a sample project?
> 
> In the [nightly build](https://github.com/dotnet/maui/wiki/Nightly-Builds), we should have fixed a problem for `ListView` on iOS, but not Windows:
> 
>     * [[ios] fix leak in ListView *Cells #23143](https://github.com/dotnet/maui/pull/23143)

I'll see if I have some spare time next week to come up with something, but it will be difficult, timeline here is pretty tight. 

On a related note, are there any good resources you'd recommend for getting started with improving the memory performance of my app? I have tons of data to display, and the number of binding references looks set to increase exponentially. Need to figure out a way to analyze these heap snapshot reports, and then take action on them.

**Comment by ajsuydam** [comment]
Also just want to say thanks to both of you @jonathanpeppers @PureWeen for your quick responses on this. Confidence boost for sure.

**Comment by ajsuydam** [comment]
> > On a related note, are there any good resources you'd recommend for getting started with improving the memory performance of my app?
> 
> https://learn.microsoft.com/en-us/dotnet/maui/deployment/performance?view=net-maui-8.0 is the best I know of

@MartyIX Thanks, I have referenced that already a bunch. I think maybe a better question that I should have asked is are there any good resources for how to use the .net memory analyzers and how to find the patterns in my programming that are resulting in the objects being kept alive.

**Comment by ajsuydam** [comment]
@jonathanpeppers @PureWeen For now I'm going to mark this as closed since the immediate issue has been resolved. But I would appreciate any resources y'all have!
