### ISSUE TITLE
Method "OnAppearing" for ContentPage not called after application is resumed

### ISSUE THREAD

**Issue by TWEESTY** [dotnet/maui#23401]
### Description

When the application is resumed (i.e. when the application is putting on the front after being in the background), the method "OnAppearing" of the current page is not called. The behavior is different from Xamarin.

### Steps to Reproduce

Put a breakpoint inside the method "OnAppearing" of the page "MainPage.xaml.cs"
Launch the application
The breakpoint is hit.
Then, put the application in background, then return to the application => the breakpoint is not hit.

### Link to public reproduction project repository

https://github.com/TWEESTY/MAUI_Issue_OnAppearing

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

No

**Comment by SmartmanApps** [comment]
Maybe related https://github.com/dotnet/maui/issues/15767

**Comment by PureWeen** [comment]
> The behavior is different from Xamarin.

This behavior is only different on Android. 

For iOS and Windows "OnAppearing" didn't fire in XF when an app was backgrounded and then brought back into the foreground. 

If you want to listen to lifecycle events on the window, I'd recommend accessing the Window property or wiring into the lifecycle events on the builder
