### ISSUE TITLE
BackButtonBehavior IsVisible="False" does not hide the back button on iOS

### ISSUE THREAD

**Issue by acaliaro** [dotnet/maui#23424]
### Description

if I use 

```
    <Shell.BackButtonBehavior>
        <BackButtonBehavior IconOverride="ico_back.png" IsVisible="False" />
    </Shell.BackButtonBehavior>
```

The back button is not hide

### Steps to Reproduce

1- open and run the project
2- press "popup problem!!!!" button
3- on the new page, the back button is visible

### Link to public reproduction project repository

https://github.com/acaliaro/MauiBackButtonBehaviorIsVisibleProblem

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.3 iphone 12

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 2.1(8.0.61 & 8.0.60 & 8.0.40). Can repro on iOS platform with sample project.

**Comment by bappitybup** [comment]
I'm having this issue with the Android platform. 
Visual Studio 17.10.3, net 8
