### ISSUE TITLE
Xamarin framework Support for net8.0-ios?

### ISSUE THREAD

**Issue by ljzj2** [dotnet/maui#23434]
### Description

I created net8.0-ios and Want to use GPUImage framework it is using objective-c .
I can not compile it to `net-ios-binding` since there is too many errors.
then I find that there is `Xamarin.GPUImage` is for `xamarinios` not `netios`
please support it to netios

### Public API Changes

`Xamarin.GPUImage` to `net-ios-GPUImage`

### Intended Use-Case

I want to use it for camera picking and edge detecting. you may say I should use `VisionKit` but it not support ios13.
So I have to use this.

what I want to do is to take photos of ticket.

**Comment by drasticactions** [comment]
You should redirect your issue to the [xamarin-macios](http://github.com/xamarin/xamarin-macios/) repo. This repo is for the cross-platform MAUI UI toolkit and does not handle this tooling.
