### ISSUE TITLE
iOS AppDelegate - Overrides for handling remote notifications not available

### ISSUE THREAD

**Issue by mikeparker104** [dotnet/maui#23451]
### Description

In Xamarin.Forms, the following [UIApplicationDelegate](https://learn.microsoft.com/en-us/dotnet/api/uikit.uiapplicationdelegate?view=xamarin-ios-sdk-12) methods could be overridden on ```FormsApplicationDelegate```. 

- [UIApplicationDelegate.RegisteredForRemoteNotifications](https://learn.microsoft.com/dotnet/api/uikit.uiapplicationdelegate.registeredforremotenotifications)
- [UIApplicationDelegate.ReceivedRemoteNotification](https://learn.microsoft.com/dotnet/api/uikit.uiapplicationdelegate.receivedremotenotification)

```csharp
public virtual void RegisteredForRemoteNotifications (UIKit.UIApplication application, Foundation.NSData deviceToken);
public virtual void ReceivedRemoteNotification (UIKit.UIApplication application, Foundation.NSDictionary userInfo);
```

These methods aren't exposed in ```MauiUIApplicationDelegate``` alongside with other [UIApplicationDelegate](https://learn.microsoft.com/en-us/dotnet/api/uikit.uiapplicationdelegate?view=xamarin-ios-sdk-12) methods like ```FinishedLaunching```, ```OpenUrl```, and ```PerformFetch```. The methods must be directly exported instead. 

As was the case with the more recently added ```PerformFetch``` method ([#7957 - iOS AppDelegate - Override for PerformFetch is not available](https://github.com/dotnet/maui/issues/7957)), this may also be a candidate for inclusion as part of ```ConfigureLifecycleEvents```.

```csharp
events.AddiOS(ios => ios.RegisteredForRemoteNotifications(HandleRegisteredForRemoteNotifications));
events.AddiOS(ios => ios.ReceivedRemoteNotification(HandleReceivedRemoteNotification));
```

### Steps to Reproduce

1. Try to override the ```RegisteredForRemoteNotifications``` and ```ReceivedRemoteNotification``` methods on iOS (AppDelegate)

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Directly export the requisite methods in the AppDelegate class.

```csharp
[Export("application:didRegisterForRemoteNotificationsWithDeviceToken:")]
public void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)  { ... }

[Export("application:didReceiveRemoteNotification:")]
public void ReceivedRemoteNotification(UIApplication application, NSDictionary userInfo) { ... }
```

**Comment by mikeparker104** [comment]
@jfversluis @mattleibow See draft PR ([#23452](https://github.com/dotnet/maui/pull/23452)) for proposed updates.

**Comment by mattleibow** [comment]
This is now fixed in .NET 9: https://github.com/dotnet/maui/pull/23452

The next preview will have this included.

**Comment by SergTomcat** [comment]
Correct me if I'm wrong, it won't be in 8? 9 is not even released...
