### ISSUE TITLE
unable to debug android apps on Linux

### ISSUE THREAD

**Issue by MandeepSingh-MS** [dotnet/maui#23472]
### Description

I am new to .NET MAUI. I setup the development environment as per the documentation.

i am using the latest version of VS Code and the required extensions for .NET MAUI.
The release build is working fine.

But unable to run the debug mode. During debug mode the following error appears.

> /dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Android.Common.Debugging.targets(678,5): error XA0129: Error deploying 'files/.__override__/Microsoft.Maui.Controls.Compatibility.dll'. 

> /dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Android.Common.Debugging.targets(678,5): error XA0129: Please set the 'EmbedAssembliesIntoApk' MSBuild property to 'true' to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor.

_As I am new to .NET MAUI, I tried to set the **EmbedAssembliesIntoApk**  property. But then the following message appears in the debug console_

> You may only use the Microsoft Visual Studio .NET/C/C++ Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you
develop and test your applications.
------------------------------------------------------------------------------
> The program 'MauiApp1.dll' has exited with code 0 (0x0).

**VERSIONS**

1. dotnet = 8.0.302
2. maui-android = Manifest version = 8.0.40/8.0.100 , Installation Source =  SDK 8.0.300  
3. vs code = 1.91.0
4. OS = LINUX (linux-mint) => Linux x64 5.15.0-41-generic
5. .net maui extension = 1.0.6
6. c# extension = 2.34.12
7. c# dev kit = 1.7.27

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by kevinxufei** [comment]
This issue has been verified using VS Code(1.91.0) (8.0.61). Can not repro on Android platform. All extension versions are the latest release versions like users.

**Comment by MandeepSingh-MS** [comment]
I did.
Closed the issue from here.
Opened in the suggested repository.

[Link of the issue](https://github.com/microsoft/vscode-dotnettools/issues/1273)
