### ISSUE TITLE
Inconsistence Frame Padding

### ISSUE THREAD

**Issue by mknotzer** [dotnet/maui#23482]
### Description

Frame Padding on Android 20px, on iOS 10px

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Did you find any workaround?

```
<Style TargetType="Frame">
    <Setter Property="Padding" Value="10" />
</Style>
```

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 2.1(8.0.61 & 8.0.21). Can repro it. 
![image](https://github.com/dotnet/maui/assets/128687574/db4923f0-763c-4935-8189-40b7a3098d8b)

**Comment by PureWeen** [comment]
@mknotzer if you use Border does that work?

**Comment by mknotzer** [comment]
@PureWeen the Border attribute doesn't exist in Maui

**Comment by PureWeen** [comment]
I'm referring to the border control 
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/border?view=net-maui-8.0

**Comment by mknotzer** [comment]
@PureWeen border control works but is lacking the bordercolor attribute

**Comment by jfversluis** [comment]
Seeing that Frame is officially deprecated as of .NET 9, I don't think we will be working on this anymore. Also its a bit older by now, so maybe its even resolved in current versions 🤞
