### ISSUE TITLE
TabbedPage Clear and Adding existing page does not display across the entire screen [iOS]

### ISSUE THREAD

**Issue by siem300** [dotnet/maui#23484]
### Description

In our apps we use a TabbedPage to display different tabs. In some cases we want to reload these tabs (based on personalization preferences of our user). When this happens we check which pages already exist and which don't. 

So when this happens we want to persist pages that are already loaded so we don't lose the users information. When we call Children.Clear() and add the new pages (some of them are persisted) the persisted pages aren't sized correctly. See the following screenshots. 

**Initial Load**
![image](https://github.com/dotnet/maui/assets/7387334/19ee8c98-eff1-448b-8050-307292fd7384)

**Clear and Add with persisted page**
![image](https://github.com/dotnet/maui/assets/7387334/232dd9b3-f195-4b1c-9b84-72c37b3ee0ff)

If you keep repeating the steps, the page keeps getting smaller and smaller until it dissappears completely.
This only happens on iOS. Android and Windows work as expected.

### Steps to Reproduce

1. Start the attached reproduction project on iOS
2. Click the "Clear and Add pages" button
3. The first page is reused and the content of the page is sized incorrectly. The pages that are not reused display correctly.

### Link to public reproduction project repository

https://github.com/siem300/Maui-TabbedPage-Sizing-Issue

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Did not find a workaround

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 2.1(8.0.61 & 8.0.40 & 8.0.10). Can repro on iOS platform.

**Comment by PureWeen** [comment]
I feel like this might be related to how we handle safeareas in mauiview and then tabbedpage is probably doing double work

**Comment by pictos** [comment]
Visually it looks like #6994, maybe the way how iOS is computing its View's size is making that
