### ISSUE TITLE
Debug app crashes on iPhone 8 when running it directly, not debugging it.

### ISSUE THREAD

**Issue by tpitman** [dotnet/maui#23499]
### Description

I am converting a Xamarin Forms app to MAUI. I am using Visual Studio 2022 for Mac.

This is not the first app I have done this with. I feel like this same issue happened when I ported other apps, but can't seem to remember what solved it.

When I debug the app using VS to an actual iPhone 8, it runs fine.

If I then tap on the exact same app from the iPhone home screen it starts to run and then crashes.

I looked through the Console app log output and the only thing I found that seemed to give an actual error was this entry:

```
Scene FBSceneManager/sceneID:com.holley.classicinstruments.zeus-default update failed: <NSError: 0x280ce4630; domain: FBSceneErrorDomain; code: 1 (operation-failed); reason: "Scene update failed."> {
    NSUnderlyingError = <NSError: 0x280ceee80; domain: BSServiceConnectionErrorDomain; code: 3 (OperationFailed); reason: "XPC error received on message reply handler">;
}
```

Up until that point the log output all seem to indicate things are moving along fine.

### Steps to Reproduce

1. Have a Xamarin Forms app solution
2. Create a new MAUI project to the same solution
3. Port over all source forms and files
4. Update all Xamarin Forms references to the proper MAUI references
5. Resolve issue that prevent building and running
6. Debug the app using VS2022 for Mac on a Mac
7. Note the app runs as intended
8. Close the app
9. On the iPhone tap on the exact same app icon
10. Note that it starts to run and then crashes

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

I have encountered this same thing before in other ports, but cannot remember what the fix was.

**Comment by tpitman** [comment]
How did you determine this would be an issue with Visual Studio (Code)?

**Comment by drasticactions** [comment]
I agree that I think it's too early to call that it's a VS issue (Although IMO, I would probably move to VS Code or Rider now and not use VS Mac, especially for .NET8+)

Can you build a reproduction app that shows this issue? I'm not sure how exactly you ported your Forms app to MAUI and I can't reproduce these conditions you're seeing.

**Comment by tpitman** [comment]
I wish I could make a reproduction for you. I am not even sure how to make a legacy Xamarin app at this point and if I did I doubt the same thing would happen.

As state above, this is not the first app that I have done this with. Same process of porting and they don’t do this same thing. I remember having this happen with one of them, but can’t remember how I solved it.

I can build, debug and run those other apps with all of the same current versions of everything and they don’t crash when I run them stand alone after having just debugged them.

I really posted this for a few reasons:

1. I hoped that maybe someone would have a similar experience and give some tips.
2. Maybe someone was familiar with something specific that causes the exact error that I put in the original post.
3. Maybe someone would have some tips on how to debug this more.

The fact that the exact same EXE (for lack of a better word) works when you debug it, but not when you just run it confuses me. It seems it might have something to do with VS trying to connect to it or it waiting for the debugger to attach, but then why do my other 3 apps I have ported not do this?

My porting process is the steps above. I start with a Xamarin Forms solution with the 3 projects. I then make a new MAUI project and move the source files from the shared project into it. I then modify the platform specific files with code from the Xamarin.ios and Xamarin.android project files to the MAUI platform files. I then have to convert some of the old ways of doing things to the new ways like Handlers.

Hopefully all of this triggers something from someone. If not I will just have to keep poking at it until I remember what fixed it last time.

If I do find a solution I will post it here for sure so when I port my next app I will have documentation of how to fix it :-)

**Comment by drasticactions** [comment]
Without a way to reproduce this and little context about what you did or what other libraries you may be pulling in, it's extremely difficult to know where to start.  

If I take an existing Forms template app, run it through the .NET Upgrade assistant (turning it into a multiplatform project MAUI app) and run it, it works fine for me directly deploying the app to an iOS device and running it without a debugger.

@rolfbjarne Is there a way for this person to get more information about why their app is crashing?

**Comment by rolfbjarne** [comment]
> Debug the app using VS2022 for Mac on a Mac
> Note the app runs as intended
> Close the app
> On the iPhone tap on the exact same app icon

That's unusual, I don't think I've seen that particular failure mode before.

A few questions / things to try:

* Do you have Hot Restart / Hot Reload enabled? If so, try turning them off.
* Do you see the crash when building for Release as well?
* You don't specify, but it could be useful to know if the same thing happens in the simulator as well.

> @rolfbjarne Is there a way for this person to get more information about why their app is crashing?

There might be crash reports: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#crash-reports

Otherwise anything is typically printed to the Console app, so you could sprinkle Console.WriteLines in your app to see where it ends up crashing (or maybe it doesn't even reach the managed Main method?)

**Comment by tpitman** [comment]
I found the ips crash report. Is there a way to connect the addresses given in the report to the C# source code in my app so I can see what line it is crashing on?

One interesting note is that I went back into my source control for my other apps that I ported and found a comment about fixing this same crash on another app.

The change that seemed to make the difference in that app was that one of my views was a ContentPage, but being used as the child of another ContentPage and for some reason this would cause a crash, but only when running the app by tapping on it. When I would debug that app it wouldn't happen. To fix that app I just had to change that view from ContentPage to ContentView and it fixed the crash.

Sadly I don't have that same situation in this app, so this must be a new crash that just happens to also only happen when running the debug app while not debugging.

As you suggested and I have done many times, now I just need to remove stuff until it doesn't crash and then back it out to find this.

Being able to connect the addresses in the ips crash report to C# code would be very helpful....

**Comment by JamesBrooksbankIceland** [comment]
From the sounds of it... just based on my experience, these kinds of things occur when there is a problem in the xaml side of things. We have had the same occurrences when bindings have failed or static resources have gone missing. One time we had a conditional binding which was causing the error. Like you described, it worked in debug when connected, but then when disconnected the problem occurred again.

It seems that debugging in vs has something in place to cope with binding errors and from the looks of the error pasted, it definitely looks like something on the xaml side of things.

When I have had the error and nothing jumped out, I went traditional Perl debugging route and doing what you are doing, deleting everything, then testing it, adding a small bit in again, testing it again. 

You might want to check the xaml binding errors window in vs as well, this may help. 

Good luck to you.

**Comment by rolfbjarne** [comment]
> I found the ips crash report. Is there a way to connect the addresses given in the report to the C# source code in my app so I can see what line it is crashing on?

Yes, the easiest is to disable symbol stripping by adding this to your csproj:

```xml
<PropertyGroup>
    <NoSymbolStrip>true</NoSymbolStrip>
</PropertyGroup>
```

Then rebuild your project and trigger a new crash report.

**Comment by tpitman** [comment]
I also just tried running this in the simulator and get the same results. It will run when I debug it, but when I tap on the same EXE it crashes.

Thanks for the tip on the no strip. I will try that and see what I find.

**Comment by tpitman** [comment]
After turning on that setting in the project file and causing the app to crash I don't seem to be getting any new crash logs.

How do I trigger getting the new logs? Are they maybe just taking a long time to load because they are much bigger?

Before turning on that setting when I would trigger a new crash it seemed like the log would just show up even if I had the Open File dialog open to the log opener.

Any idea why I am not seeing new logs even though the app is still crashing?

**Comment by tpitman** [comment]
I decided to try it on a different phone and now have a ips file after turning on that setting. How do I now correlate the crash log with symbol lookup?

**Comment by tpitman** [comment]
Figured it out. Just have to use the Finder preview window and it now shows symbols instead of addresses in the preview.

The symbols only show that we ended up in the xamarin unhandled exception handler.

I will try adding a try / catch at the root and see if that helps. Probably won't though, so I will revert to removing stuff until it works.

I will report back if I find it.

Any other ideas would be appreciated.

**Comment by tpitman** [comment]
BINGO. By putting a try / catch around the main part of my code I was able to catch the exception by using Console.WriteLine and then using the Macos console app to view it.

I see the exception has to do with a library that I ported to MAUI and probably need to update the source code similar to what I did in the other apps.

I will be able to figure it out from here.

Thanks for all the attention that got me thinking along these lines!!

FYI it has to do with the DSoft library that I use for a color picker. Not sure why it works when debugging, but not when just running the same app.

**Comment by tpitman** [comment]
Well, more to the story. There is a class in the DSoft library I am using. The class is called ColorWheelView.

I have this at the top of the xaml:

```
	xmlns:colorPicker="clr-namespace:DSoft.Maui.Controls.ColorPicker;assembly=DSoft.Maui.Controls"
```

I have this later in the xaml:

```
<colorPicker:ColorWheelView SelectedColor="{Binding LabelColor}" HeightRequest="200" WidthRequest="200"/>
```

As you know, when I run this in the debugger everything works fine, but when I tap on the same app without debugging it crashes. The exception is this:

```
Position 215:34. Type colorPicker:ColorWheelView not found in xmlns clr-namespace:DSoft.Maui.Controls.ColorPicker;assembly=DSoft.Maui.Controls
```

I get that exception on this line of code in my App.xaml.cs file:

```
MainPage = new MainPage();
```

MainPage is my parent Page and the above xaml is in a ContentView embedded in the MainPage xaml.

I wanted to see what would happen if I just added this line:

```
var temp = ColorWheelView();
```

Right above my assignment to MainPage, so I ended up with this:

```
var temp = ColorWheelView();

MainPage = new MainPage();
```

Well, just doing that fixes the issue. Now it runs fine both while debugging and when I just tap on the app to start it on the phone.

Obviously there is some kind of startup timing issue or DLL loading issue that is different between debugging and running.

Any ideas? Is this a bug that needs to be researched? If so, I can't post my project for the public, but could send it to a Microsoft engineer privately to investigate....

**Comment by tpitman** [comment]
I have some more information. When I debug the app and go to the view that is supposed to have the ColorWheelView on it, it isn't there.

Since Hot Reload is working I am able to make changes to the xaml in real time.

If I do this and change the containing StackLayout with a Grid, then the ColorWheelView object shows up!!!!

If I quit the app, change leave the xaml as a grid, start it up again the ColorWheelView is not there. If I change it back to a StackLayout while Hot Reload is running, then it shows up!!!!

So even though I don't get the exception while debugging the app, it would appear that class is really not available at the time the xaml is being parsed. During debug it doesn't except, but when tapping the app it does.

So now the real question is why is the ColorWheelView not there for the xaml parser?

I can right click on it in the editor and go to definition and it goes to the correct source code.

Changing the container in Hot Reload causes it to show up.

I have tried adding delays before where the MainPage class is created and that doesn't seem to help.

Having that var temp = new ColorWheelView helps with the exception but doesn't help the class be there for the xaml parser at startup.

Keep in mind that I am using the same DSoft library and as far as I can tell set it all up the same way in 2 other apps that work fine.

I need you smart people who know more about the internals to help me figure this one out.

**Comment by tpitman** [comment]
Well, dang, mystery solve.

Turns out I had duplicated some of the code in the DSoft library in my MAUI project. It is code for doing the Touch Handler stuff.

For some reason that causes the entire DSoft library to not be available like normal and all of the above issues.

When I realized my mistake I just removed those files from the MAUI project.

Sorry to have wasted all your time. Please leave this around so that it will be a lesson that could help others or even me again in the future....

Thank you!!!
