### ISSUE TITLE
Starting a new Activity from main activity throws error

### ISSUE THREAD

**Issue by Take-A-Byte** [dotnet/maui#23493]
### Description

When I try to start a new activity (which should be started in the same app window) from main activity, it throws an error.
> **System.InvalidOperationException:** 'This window is already associated with an active Activity (AndroidMultipleActivities.Droid.MainActivity). Please override CreateWindow on AndroidMultipleActivities.App to add support for multiple activities https://aka.ms/maui-docs-create-windowor set the LaunchMode to SingleTop on AndroidMultipleActivities.Droid.OtherActivity.'

I have also added `LaunchMode=LaunchMode.SingleTop` to both activities as suggested in the error, but this does not fix the issue.

### Steps to Reproduce

1. Clone https://github.com/Take-A-Byte/AndroidMultipleActivities/tree/master
2. Run project

The above project is a simple MAUI project with Android platform. I added `OtherActivity` and added `StartActivity` in `MainActivity`.

### Link to public reproduction project repository

https://github.com/Take-A-Byte/AndroidMultipleActivities/tree/master

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Relevant log output

```shell
**System.InvalidOperationException:** 'This window is already associated with an active Activity (AndroidMultipleActivities.Droid.MainActivity). Please override CreateWindow on AndroidMultipleActivities.App to add support for multiple activities https://aka.ms/maui-docs-create-windowor set the LaunchMode to SingleTop on AndroidMultipleActivities.Droid.OtherActivity.'
```

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 2.1(8.0.61 & 8.0.40 & 8.0.10). Can repro on Android platform. 
![image](https://github.com/dotnet/maui/assets/86938401/7082af47-8d37-4073-b284-dc6eace2d08b)

**Comment by Take-A-Byte** [comment]
I was using `MauiAppCompatActivity` for both activities which caused the exception. I am not yet sure why this exception is caused, when should we use `Activity` and when should we use `MauiAppCompatActivity`. 
Is there any documentation containing details about this?

**Comment by PureWeen** [comment]
> Please override CreateWindow on AndroidMultipleActivities.App 

You need to override `CreateWindow` on `AndroidMultipleActivities.App ` and supply your own window class and contentpage for each activity that's created
