### ISSUE TITLE
[iOS] IndicatorView IndicatorSize Overwritten to Default After Updating ObservableCollection in CarouselView

### ISSUE THREAD

**Issue by npostma** [dotnet/maui#23508]
### Description

In a .NET MAUI application, when using a CarouselView with an associated IndicatorView, the IndicatorSize property of the IndicatorView is being reset to its default value after the observable collection bound to the CarouselView is updated.

Actual Behavior:
The IndicatorSize property of the IndicatorView is reset to its default value after the ObservableCollection is updated. If updated with e.g. hotreload it goes back to the set value. But after chaning the collection, the indicators are changed to the default size

### Steps to Reproduce

Create a .NET MAUI project with a CarouselView and an IndicatorView. (I have it in a grid. Row 0 Col 0 is the carousel, Row 1 Col 0 is the indicatorview)
Bind the CarouselView to an ObservableCollection.
Set the IndicatorSize property of the IndicatorView to a custom value.
Update the ObservableCollection (e.g., add or remove an item).
Expected Behavior:
The IndicatorSize property of the IndicatorView should retain its custom value after the ObservableCollection is updated.

```xaml
<IndicatorView 
    Grid.Row="1"
    x:Name="carouselViewIndicator" 
    SelectedIndicatorColor="{StaticResource PrimaryBackground}" 
    IndicatorColor="{StaticResource PrimaryBackgroundAccent}" 
    IndicatorSize="8" 
    Margin="0,0,0,0" 
    HorizontalOptions="FillAndExpand"
    VerticalOptions="FillAndExpand"
    BackgroundColor="Transparent"
    ZIndex="5"
/>
```

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 14 and up for sure

### Did you find any workaround?

No, tried a lot of things. Setting hights, adding containers to restrict. Nothing seems to help.

**Comment by npostma** [comment]
It is still an issue..... code for the IndicatorView is posted in the original post.

**Comment by PureWeen** [comment]
Can you push a reproduction to github?
