### ISSUE TITLE
Obsolete Setting MainPage and direct users to CreateWindow

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#23518]
### Description

Because .NET MAU is multi window there are a lot of confusions that currently happen because users are unaware of the `CreateWindow` override on app.xaml. 

There is also currently a lot of confusion because there's no indication to users that something called "Window" even exists. 

### Proposal

- Obsolete Application.Current.MainPage (set/get)
- change the template to use the override vs setting the MainPage
- Provide guidance (docs and obsolete message) that users can access the windows on Application.Current.
   - Application.Current.MainPage can become Application.Current.Windows[0].Page
   - Check if we can add to migration
- Make the following extension method public https://github.com/dotnet/maui/blob/fe224da90bccc3c1926c1c547c780aec409b2315/src/Core/src/Platform/iOS/UIApplicationExtensions.cs#L77. The android/winui versions of that method are already public 
- Create Item Template for a Window

### Probably won't do this yet
- Possibly make Window.get_IsActivated public. This will help developers make decisions about what window they want to return.
  - This is risky because IsActivated can mean a lot of different things to people 

### MainPage scenarios
- Application.Current.get_MainPage
  - Application.Current.Windows[FigureOutWhatWindowYouWant].Page
- Inside an Android class
  - AndroidView.Context.GetWindow().Page
  - Microsoft.Maui.ApplicationModel.Platform.CurrentActivity.GetWindow().Page

**Comment by pictos** [comment]
> Application.Current.MainPage can become Application.Current.Windows[0].Page

Instead of using the index, can we've something like `CurrentWindow` or `PresentedWindow`, to have access the focused Window?

**Comment by mattleibow** [comment]
On some platforms, there can be multple windows shown next to each other that are interactable: Windows, macOS and iPad.

**Comment by mattleibow** [comment]
I see `Window.IsActivated` exists, so we can technically do something like this:

```cs
var current = Application.Current.Windows.FirstOrDefault(w => w.IsActivated);
```

Not sure how platforms handle side-by-side, but I think they trigger a pause so this will be false. This could even be a property (if we want) on app:

```cs
class Application {
    public Window? ActiveWindow => Windows.FirstOrDefault(w => w.IsActivated);
}
```

so you can do something like this:

```cs
Application.Current.ActiveWindow?.DoThing();
```

Keep in mind, this will return null if all the windows are minimized or the app has a PIP popup.

**Comment by PureWeen** [comment]
I agree with @mattleibow 
Our Window does have an `IsActivated` property but it's internal

I've made a note on the issue that as part of this effort we should probably make `IsActivated` public

**Comment by pictos** [comment]
Maybe this could help guide some docs around this changes...

For me is quite confusing what `Windows[0]` means, when I see a code like this `Application.Current.Windows[0].Page` I can think that `Windows[0] ` means:

- The first Window created;
- The top most Window;
- The focused WIndow.

> I see Window.IsActivated exists, so we can technically do something like this:

When @mattleibow said that, the `IsActivated` means what? Because I can have a multi-window app, where two windows will be showed side by side, so both windows will return `true` for `IsActivated` property? (Didn't find anything on docs and the `Activated` [event is very vague](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/windows?view=net-maui-8.0))
