### ISSUE TITLE
[Properties > Build Actions] options available depend on order of TargetFrameworks in .csproj - Cannot see all options at once - Only the first OS's options are shown

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#23523]
### Description

When you build a default Maui project, it will create a line in the csproj file like:

```
<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
```

However, the order of these affects the options if you right click on something > Properties > Build Actions.

Only the OS-specific options for the first one in the list are shown. For example if iOS is first, you will get an option like "ITunes Artwork" but not with Android first.

And all the Android options like "AndroidAsset" or "ProguardConfiguration" only show up if Android is first.

It took me hours today to try to add a ProguardConfiguration until I figured out this bug. I had no option for it.

### Steps to Reproduce

1) File > New > Maui Project
2) Open csproj and change order of line: `<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>`
3) Close and re-open project
4) Right click anything > Properties > Build Actions and see that the special OS-specific options provided are only for the first entry in the list

### Link to public reproduction project repository

n/a, default Maui Project

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Did you find any workaround?

None. If you need OS specific type, place it first in list. Bizarre.

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3.0(8.0.70). Can repro on all platforms.
![image](https://github.com/dotnet/maui/assets/77434865/5f2858eb-dd2d-4492-a821-aa0ce24fcf3c)

**Comment by drasticactions** [comment]
I think this is all handled by Visual Studio tooling. I don't think MAUI UI itself influences what's shown in those menus. Unless I'm mistaken (@PureWeen?) I think this should be moved to VS Feedback.

**Comment by jonmdev** [comment]
I do not see any easy way to report a Visual Studio problem so I will leave this up to Microsoft employees if they wish to report or fix it. At least it is now documented here if anyone wants to know why this behavior is happening or try to work around it.

For reference, this issue was previously reported in May 2023, which I found when I was initially trying to figure out this issue. However, that user seems to have gotten the nature of the problem slightly wrong:

https://developercommunity.visualstudio.com/t/MAUI-build-actions-such-as-AndroidResou/10374447?

They thought the issue was using `net7.0-android33.0` instead of `net7.0-android` but if you look at their "working" version for Android, the main difference is again that they put Android first not last, suggesting this is the same issue and that was the actual "solution". 

Thus I expect this bug has been present since at least that time or longer. That report was closed by Microsoft as they felt it was not worth fixing.

**Comment by drasticactions** [comment]
I have reopened that feedback item and tried to direct it to the correct resources. Based on the internal ticket, it was being worked on but, at some point, was directed to the wrong team to look at and eventually closed due to the low feedback. To me, this feels like a general issue around multiple target frameworks in VS and how they are considered (With possible issues in the runtime as well), but they are most likely not MAUI specific, especially not something that could be addressed in this repo.

I would upvote that bug and direct your issues onto it. Sorry for the trouble.
