### ISSUE TITLE
Hot Reload - Changes not supported

### ISSUE THREAD

**Issue by Enzymism** [dotnet/maui#23521]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Thanks for your interest in .NET MAUI, sorry you ran into a snag!

As indicated, the thing you seem to describe is something that has to do with Visual Studio. Please report it through the ways described above. Thank you!
