### ISSUE TITLE
cannot disable animation when navigate back

### ISSUE THREAD

**Issue by ibrahimahmed1998** [dotnet/maui#23524]
### Description

cannot disable animation when navigate back,
I using PushModalAsync 

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by PureWeen** [comment]
probably fixed by https://github.com/dotnet/maui/pull/22869
