### ISSUE TITLE
Scrollview iOS - size out of bounds, sizing does not work.

### ISSUE THREAD

**Issue by RobDaytona** [dotnet/maui#23530]
### Description

Regression of this bug:
https://github.com/dotnet/maui/issues/13246
.Net 8
Visual studio Version 17.10.3

### Steps to Reproduce

https://github.com/dotnet/maui/issues/13246

Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
android                    34.0.95/8.0.100        VS 17.10.35013.160
aspire                     8.0.0/8.0.100          VS 17.10.35013.160
maui-windows               8.0.40/8.0.100         VS 17.10.35013.160
maccatalyst                17.2.8053/8.0.100      VS 17.10.35013.160
ios                        17.2.8053/8.0.100      VS 17.10.35013.160

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

Not that I have found.

**Comment by RobDaytona** [comment]
https://github.com/dotnet/maui/issues/14986

**Comment by drasticactions** [comment]
@RobDaytona I checked out that repo referenced in that issue, updated the dependencies to .NET 8, and ran it on iOS and Catalyst. Scrolling was fine for me with items overflowing the list. Unless I'm misunderstanding the issue here.

Could you please create a repo showing your issue?

**Comment by RobDaytona** [comment]
Sorry can't you get your repos from the previous bug reports?
https://github.com/dotnet/maui/issues/14986
and
https://github.com/dotnet/maui/issues/13246

**Comment by RobDaytona** [comment]
@drasticactions is it possible to send you a screen recording?

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3.0(8.0.70 & 8.0.40). Can not repro on iOS platform(iOS simulator:15 version:17.2) with [MauiSampleExpander-main.zip](https://github.com/user-attachments/files/16159108/MauiSampleExpander-main.zip). Please upload your project for us to investigate, thank you!

**Comment by RobDaytona** [comment]
I guess please close this ticket, I mean I am seeing similar issue to  https://github.com/dotnet/maui/issues/13246, but  I can't repro on new project, and in my existing monolith project, even creating a new view from scratch it happens on, and actually other weird behavior happens.. Given I have have 4 or 5 open bugs here with simple repro steps that have never been fixed.. there is really no point keeping this one open at this point , so I advise close it. tx
