### ISSUE TITLE
[Memory leak] Critical MAUI memory leak in transient views

### ISSUE THREAD

**Issue by DarrenStasiak** [dotnet/maui#23537]
### Description

In recent days our company discovered serious memory leak in MAUI app we are working on i.e. views set as transient don't get disposed of correctly resulting in linear memory growth. Firstly we tried using MAUI wiki page on memory leaks, which yield no concrete results to our problem. Our team decided look up how it is done in eShop demo, and we found same leak there.

In demo we added GC.Collect, destructors to each view (on which we put a breakpoints) and label (under "Adventure Works'" title) that displays current heap size.

# Examples:

## Cheap size on startup:

![Pasted image 20240710125722](https://github.com/dotnet/maui/assets/58084104/7d8b517b-d311-4ce3-be98-ab39524b7e0d)

## Heap size after opening and closing BasketView 10 times 

![Pasted image 20240710125812](https://github.com/dotnet/maui/assets/58084104/a45b8df4-ccf5-4020-ae2a-f818fc01188c)

On opening and closing BasketView breakpoints weren't triggered single time and heap size kept increasing.

After deleting command from button in BasketView destructor started working.
![Pasted image 20240710140645](https://github.com/dotnet/maui/assets/58084104/564edde8-013f-4ad8-90ee-f023443bc4af)
![Pasted image 20240710130458](https://github.com/dotnet/maui/assets/58084104/dbd76634-d02c-4119-b27d-574a2f6f2d57)

# Questions

Why does it happen, is there some explanation to why MAUI behaves this way?
If it is not problem with MAUI, then where lays that issue?
Do we need to use some practices that aren't shown in official Microsoft demo?

### Steps to Reproduce

Only changes from original repo are:
### BasketView.xaml.cs
![image](https://github.com/dotnet/maui/assets/58084104/77968422-0a58-477c-9c73-9f43f7448c0d)
### CatalogView.xaml.cs
![image](https://github.com/dotnet/maui/assets/58084104/691a919d-f7aa-4ad6-88d4-142ed2593fb9)
### CatalogView.xaml
![image](https://github.com/dotnet/maui/assets/58084104/05759f57-5c0d-45c6-85db-da8b5d1587e2)

### Link to public reproduction project repository

https://github.com/dotnet/eShop

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Did you find any workaround?

After deleting command from button in BasketView destructor started working.
In our project we used singletons instead of transient, so memory grows only to certain point.

**Comment by PureWeen** [comment]
eShops leaks aren't going to be symmetrical to yours

For example, if any of your transients implement IDisposable those won't get removed until this is fixed https://github.com/dotnet/maui/issues/8538

If your transient views aren't getting collected that doesn't really have anything to do with the ServiceProvider
We would need a repro with your specific example.

Also, there's been a bunch of memory fixes since 8.0.3, so, maybe try the latest nuget release?

**Comment by DarrenStasiak** [comment]
I am in a process of making example repo for reproducing this bug.

**Comment by NeilMalcolm** [comment]
> I am in a process of making example repo for reproducing this bug.

@DarrenStasiak did you get past this memory leak issue in newer releases of MAUI?
