### ISSUE TITLE
CarouselView Position-- not working on Windows

### ISSUE THREAD

**Issue by mknotzer** [dotnet/maui#23533]
### Description

`myCarouselView.Position++` 
works, switch to next item

`myCarouselView.Position--`
nothing happens

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by PureWeen** [comment]
Duplicate of #15443
