### ISSUE TITLE
CarouselView ItemsSource not updated when triggered via button click

### ISSUE THREAD

**Issue by mknotzer** [dotnet/maui#23538]
### Description

CarouselView is ignoring changes of the ItemsSource (ObservableCollection) when executed via an event handler

[CarouselViewBug.zip](https://github.com/user-attachments/files/16164184/CarouselViewBug.zip)

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

```
myCarouselView.ItemsSource = null;
myCarouselView.ItemsSource = myItemsSource;
```

**Comment by mknotzer** [comment]
[CarouselViewBug.zip](https://github.com/user-attachments/files/16163683/CarouselViewBug.zip)

**Comment by karthikraja-arumugam** [comment]
It seems the issue was resolved by PR [23779](https://github.com/dotnet/maui/pull/23779).
