### ISSUE TITLE
[Binding SG] BindingSourceGen generates invalid code when referencing fields generated by XamlG

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/maui#23531]
### Description

It is possible to use fields generated by XamlG in the getter lambda in the `SetBinding` call. The source generator isn't able to access the type of the field and infer the `TProperty` value. The generated code is invalid and the SG doesn't even produce any warning.

### Steps to Reproduce

1. Create a new MAUI project using .NET 9 P6
2. Add the following line to the `MainPage` constructor:
```
CounterBtn.SetBinding(Button.TextProperty, static (MainPage page) => page.CounterBtn.Width);
```
3. The compiler generates invalid code similar to this:
```c#
[GeneratedCodeAttribute("Microsoft.Maui.Controls.BindingSourceGen, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "1.0.0.0")]
[InterceptsLocationAttribute(@"/Users/simonrozsival/Projects/dogfooding/TestP6/MainPage.xaml.cs", 27, 14)]
public static void SetBinding1(
	this BindableObject bindableObject,
	BindableProperty bindableProperty,
	Func<global::TestP6.MainPage, > getter, // --- missing type
	BindingMode mode = BindingMode.Default,
	IValueConverter? converter = null,
	object? converterParameter = null,
	string? stringFormat = null,
	object? source = null,
	object? fallbackValue = null,
	object? targetNullValue = null)
{
	Action<global::TestP6.MainPage, >? setter = null; // --- missing type
	if (ShouldUseSetter(mode, bindableProperty))
	{
		setter = static (source, value) =>
		{
			source.CounterBtn.Width = value;
		};
	}
	var binding = new TypedBinding<global::TestP6.MainPage, >( // --- missing type
		getter: source => (getter(source), true),
		setter,
		handlers: new Tuple<Func<global::TestP6.MainPage, object?>, string>[]
		{
			new(static source => source, "CounterBtn"),
			new(static source => source.CounterBtn, "Width"),
		})
	{
		Mode = mode,
		Converter = converter,
		ConverterParameter = converterParameter,
		StringFormat = stringFormat,
		Source = source,
		FallbackValue = fallbackValue,
		TargetNullValue = targetNullValue
	};
	bindableObject.SetBinding(bindableProperty, binding);
}
```

I am not sure what the right fix would be at the moment. We could either default to `object` or maybe just produce a warning that using references to XAML elements via `x:Name` doesn't currently work with this source generator.

Another option might be to merge the source generator with XamlG and use the information about the types of the fields that will be generated. I'm not sure if this would work reliably though. More investigation is needed.

Moreover, the field generated by XamlG is `private` and the generated interceptor cannot see it.

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Did you find any workaround?

It is necessary to declare an `internal` proxy property:
```c#
public partial class MainPage : ContentPage
{
    internal Button CounterBtnProxy => CounterBtn;

    public MainPage()
    {
        InitializeComponent();
        BindingContext = this;

        CounterBtn.SetBinding(Button.TextProperty, static (MainPage page) => page.CounterBtnProxy.Width);
    }
}
```

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3.0(9.0.0-preview.6.24321.8). Can repro on all platforms. 
![image](https://github.com/user-attachments/assets/46da7ec7-0b1c-4bfa-9cb1-733ffcd97f6b)
