### ISSUE TITLE
Adding aps-environment on Entitlement.plist causes Provisioning profile issues

### ISSUE THREAD

**Issue by hyper6teen** [dotnet/maui#23542]
### Description

When ever I try to run the app with aps-environment on Entitlement.plist, Provisioning profile is having issue which causes the app to prompt "This app cannot be installed because its integrity could not be verified."

### Steps to Reproduce

Run the app with Entitlement.plist and has aps-environment as property.

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.4

### Did you find any workaround?

Yes, Run the app without the Entitlement.plist property aps-environment first to successfully install on the app.
then Run the app again with aps-environment included.

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.6.12 build 410 (8.0.70). Not repro on iOS platform. Deploying an application with the property aps-environment installs successfully
