### ISSUE TITLE
[Binding SG] XamlPreCompile task fails on Windows

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/maui#23558]
### Description

Building MAUI apps that will use the new `SetBinding<TSource, TProperty>(...)` API will fail during the `XamlPreCompile` task with the following error:
```
 C:\Users\...\obj\Debug\net9.0-windows10.0.19041.0\win10-x64\intermediatexaml\Microsoft.Maui.Controls.BindingSourceGen\Microsoft.Maui.Controls.BindingSourceGen.BindingSourceGenerator\GeneratedBindableObjectExtensions.g.cs(45,4): error CS9137: The 'interceptors' experimental feature is not enabled in this namespace. Add '<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Microsoft.Maui.Controls.Generated</InterceptorsPreviewNamespaces>' to your project.
```

This problem is caused by https://github.com/dotnet/msbuild/issues/9785

### Steps to Reproduce

1. Create a new MAUI app
2. Modify `MainPage.cs` with:
```c#
internal Button CounterBtnProxy => CounterBtn;

public MainPage()
{
    InitializeComponent();
    CounterBtn.SetBinding(Button.TextProperty, static (MainPage page) => page.X);
}
```
3. Build the app

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

1. Create a new file in the project root called e.g. `XamlPreCompileFeatures.rsp`
```
/features:"InterceptorsPreviewNamespaces=Microsoft.Maui.Controls.Generated"
```
2. Update the project file by adding this property:
```xml
<!-- https://github.com/dotnet/msbuild/issues/9785 -->
<CompilerResponseFile Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">$(CompilerResponseFile);XamlPreCompileFeatures.rsp</CompilerResponseFile>
```

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3 (9.0.0-preview.6.24327.7). Can repro it.

**Comment by mattleibow** [comment]
Is this a MAUI bug or a WinUI bug? I am pretty sure `XamlPreCompile` is not maui and is the way windows app sdk works...

**Comment by simonrozsival** [comment]
@mattleibow it is a WinUI bug. It should be fixed soon but until then I thought it could be helpful to have the workaround documented somewhere so that devs can find it if they run into the issue while experimenting with the .NET 9 previews.

**Comment by simonrozsival** [comment]
This issue is fixed now in the latest internal VS preview
