### ISSUE TITLE
On IOS - After Updating new Package Microsoft.Maui.Controls-8.0.70 App is not Compiling 

### ISSUE THREAD

**Issue by RAMESHKUMAR502** [dotnet/maui#23554]
### Description

On IOS - 
After Updating new Package Microsoft.Maui.Controls-8.0.70 we are seeing below Build Errors:

**/Resources/Raw/pdfjs/build/pdf.sandbox.js: Error: The name 'Resources' is reserved and cannot be used.**
**/Resources/Raw/pdfjs/build/pdf.sandbox.js.map: Error: The name 'Resources' is reserved and cannot be used.**

To Support the loading PDF using Javascript we have added PDF.js library from the official [PDF.js GitHub repository](https://github.com/mozilla/pdf.js)

After Upgrading the Application to new Nuget package Microsoft.Maui.Controls-8.0.70  we see the issue on IOS, Andriord is working Fine.

Please find the folder Structure Image and Error Image Below
<img width="304" alt="image" src="https://github.com/dotnet/maui/assets/5734910/1e3c906b-48f3-419c-ac5a-40e701484978">
![image](https://github.com/dotnet/maui/assets/5734910/7ff262e7-9d4a-4baa-b172-c906db960a6b)

### Steps to Reproduce

After Updating new Package Microsoft.Maui.Controls-8.0.70 we are seeing below Build Errors:

**/Resources/Raw/pdfjs/build/pdf.sandbox.js: Error: The name 'Resources' is reserved and cannot be used.**
**/Resources/Raw/pdfjs/build/pdf.sandbox.js.map: Error: The name 'Resources' is reserved and cannot be used.**

To Support the loading PDF using Javascript we have added PDF.js library from the official [PDF.js GitHub repository](https://github.com/mozilla/pdf.js)

After Upgrading the Application to new Nuget package Microsoft.Maui.Controls-8.0.70  we see the issue on IOS, Andriord is working Fine.

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.60 SR6

### Affected platforms

iOS

### Did you find any workaround?

NO

### Relevant log output

```shell
Resources/Raw/pdfjs/web/cmaps/78ms-RKSJ-V.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/83pv-RKSJ-H.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/83pv-RKSJ-H.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/90ms-RKSJ-H.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/90ms-RKSJ-H.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/90ms-RKSJ-V.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/90ms-RKSJ-V.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/90msp-RKSJ-H.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/90msp-RKSJ-H.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/90msp-RKSJ-V.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/90msp-RKSJ-V.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/90pv-RKSJ-H.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/90pv-RKSJ-H.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/90pv-RKSJ-V.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/90pv-RKSJ-V.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Add-H.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Add-H.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Add-RKSJ-H.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Add-RKSJ-H.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Add-RKSJ-V.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Add-RKSJ-V.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Add-V.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Add-V.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-0.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-0.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-1.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-1.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-2.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-2.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-3.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-3.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-4.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-4.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-5.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-5.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-6.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-6.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-UCS2.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Adobe-CNS1-UCS2.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-GB1-0.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Adobe-GB1-0.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-GB1-1.bcmap : error : The name 'Resources' is reserved and cannot be used.
Resources/Raw/pdfjs/web/cmaps/Adobe-GB1-1.bcmap : error :         
Resources/Raw/pdfjs/web/cmaps/Adobe-GB1-2.bcmap : error : The name 'Resources' is reserved and cannot be used.
```

**Comment by shobanasuresh** [comment]
We too are getting this build error. Please see https://github.com/dotnet/maui/issues/23557#issue-2402425395 for repro test app.

Hi @jfversluis - Could this build error be caused due to some internal change that was made for https://github.com/dotnet/maui/pull/21350?

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.6.12(build 410) (8.0.70)Can repro it, 8.7.61 cannot repro it.

**Comment by cagriy** [comment]
Same problem on 8.0.70, cannot compile anymore. Testing on Rider, the problem goes away if I revert to 8.0.61

**Comment by Redth** [comment]
Has anyone tried deleting their bin and obj folders and compiling again? Wondering if something changed between versions and some old intermediate output is conflicting.

**Comment by RAMESHKUMAR502** [comment]
yes, we Tried Many times by deleting bin and obj..still, we have the same error as above.

**Comment by PureWeen** [comment]
Can you create and attach a binlog please? 
https://github.com/dotnet/maui/wiki/Capturing-Binary-Logs

**Comment by shobanasuresh** [comment]
@PureWeen Attaching binlog for the test app shared in https://github.com/dotnet/maui/issues/23557#issue-2402425395

[msbuild_binlog.zip](https://github.com/user-attachments/files/16243697/msbuild_binlog.zip)

**Comment by vtmonilgandhi** [comment]
I fixed this issue by removing 

`<ItemGroup>
<None Remove="Resources\Fonts\Precious.ttf" />
<None Remove="Resources\Images\header.png" />
...
</ItemGroup>`

and removing 
`<ItemGroup>
	  <BundleResource Include="Resources\Images\appicnormal.png" />
	  <BundleResource Include="Resources\Images\app_ic.png" />
	  <BundleResource Include="Resources\Images\logo_white.png" />
...
</ItemGroup>`

As we already include all images with this line `<MauiImage Include="Resources\Images\*" />`

**Comment by RsZoli** [comment]
I can confirm this, i'm having the same problem with Maui.Controls 8.0.70, our pipelines suddenly just stopped after the update!

Reverting back to 8.0.61 fixes this!

**Comment by Pastajello** [comment]
Nightly build 
https://dev.azure.com/xamarin/public/_artifacts/feed/maui-nightly/NuGet/Microsoft.Maui.Controls/versions/8.0.70-ci.net8.24326.4
 works well, just next nightly starts failing so issie appeared somewhere in :
https://dev.azure.com/xamarin/public/_artifacts/feed/maui-nightly/NuGet/Microsoft.Maui.Controls/overview/8.0.70-ci.net8.24327.1

Propably #23269  ? @PureWeen

**Comment by mmiller-d8** [comment]
Same.  Just updated to 8.0.7 broke it for me too

**Comment by Kebechet** [comment]
++

**Comment by Kebechet** [comment]
Is fix in https://github.com/dotnet/maui/releases/tag/8.0.71 related to this issue ?

**Comment by mnxamdev** [comment]
This doesn't work either. We have a project with the word "Resources" in it. Please fix this ASAP, this sidetracked us a bit. This issue keeps coming up apparently as I found existing issues for this problem.
```
<BundleResource Include="..\..\MyProject.Core.Resources\XML\my.xml">
    <Link>Resources\Raw\XML\my.xml</Link>
</BundleResource>
```

**Comment by mnxamdev** [comment]
This also doesn't work either:
```
<BundleResource Include="Resources\HTML\bootstrap.min.css" Condition=" '$(EnableDefaultCssItems)' == 'true' " />
```

**Comment by Redth** [comment]
@mnxamdev I think you're trying to add the Resources subdirectory when that's already where this file will go in the app bundle.

Try this instead:

```
<ItemGroup>
  <BundleResource Include="..\..\MyProject.Core.Resources\XML\my.xml" LogicalName="Raw\XML\my.xml" />
</ItemGroup>
```

Alternatively you can glob them in:

```
<ItemGroup>
  <BundleResource Include="..\..\MyProject.Core.Resources\**" LogicalName="Raw\%(RecursiveDir)%(Filename)%(Extension)" />
</ItemGroup>
```

**Comment by jfversluis** [comment]
> This doesn't work either. We have a project with the word "Resources" in it. Please fix this ASAP, this sidetracked us a bit. This issue keeps coming up apparently as I found existing issues for this problem.
> 
> ```
> <BundleResource Include="..\..\MyProject.Core.Resources\XML\my.xml">
>     <Link>Resources\Raw\XML\my.xml</Link>
> </BundleResource>
> ```

This shouldn't block you, revert back to the last version that worked for now until we get it sorted.
