### ISSUE TITLE
Unable to Navigate Between Entries Using Tab Key

### ISSUE THREAD

**Issue by surya3655** [dotnet/maui#23559]
### Description

When using the application on macOS Intel OS 14.5, pressing the Tab key does not navigate to the next Entry control.

### Steps to Reproduce

1.Launch the application on a macOS Intel OS 14.5 machine.
2.Navigate to a screen containing multiple Entry controls.
3.Attempt to navigate between Entry controls using the Tab key.

### Link to public reproduction project repository

https://github.com/surya3655/entry-tabkey-issue

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MAC Intel OS 14.5

### Relevant log output

Uploading EntryIssue - Trim.mp4…

**Comment by surya3655** [comment]
@Zhanglirong-Winnie , With your solution, it works fine, but without VoiceOver, pressing the Tab key will navigate to the next entry, which is the expected behavior. This issue does not occur on MacBook Air with Apple M1 chip running macOS version 14.4.1.

**Comment by ian-barber** [comment]
Using the Tab key works as expected with standard Maui Controls but **not** with SyncFusion Controls.
This is the case for Mac x64 and also Mac arm64.
Windows does work as expected

**Comment by kbsanders** [comment]
@surya3655 Are you able to test with the latest Microsoft.Maui.Controls version 8.0.70? Tabbing between vanilla MAUI Entry fields is working for us under that version.

**Comment by surya3655** [comment]
@kbsanders , I have updated the package and verified that it works. Thanks for your support.
