### ISSUE TITLE
Sqlite issue in MAUI after upgrade from Xamarin forms application  to MAUI application

### ISSUE THREAD

**Issue by kiranbasvaraj** [dotnet/maui#23555]
### Description

If we upgrade the app from Xamarin forms to MAUI in Android and IOS the application is getting installed as a fresh install and no data is being read from a local database.Xamarin forms SQLite version- sqlite-net-standard(version 1.5.1)
MAUI Sqlite version-sqlite-net-pcl (version1.9.172)

Sqlite path android-
string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);  folder
                var path = Path.Combine(documentsPath, "test.db3");
          
 Sqlite path IOS-
 string documentsPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "..", "Library");
var path = Path.Combine(documentsPath, "test.db3");

### Steps to Reproduce

1. Install the Xamarin forms application which has an SQLite database with some data within it (iOS and Android).
2. Upgrade the same application to MAUI 
3. Observe-The application is not retaining the data in both IOS and Android Rather it treats it as a fresh install

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 12,IOS 17.5

### Did you find any workaround?

no

**Comment by drasticactions** [comment]
As mentioned in https://github.com/dotnet/maui/issues/23525, this is not an MAUI UI bug. There's a breaking change in the dotnet runtime for Android for .NET 8 regarding where that folder path goes.

https://github.com/dotnet/runtime/issues/102110

https://github.com/dotnet/runtime/issues/102110#issuecomment-2105629718

- To get the desired behaviour, the recommended action is to use: Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) instead.

Closed as duplicate.

**Comment by kiranbasvaraj** [comment]
I have tried using Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) in MAUI but the Application failed to deploy on top of Xamarin.
