### ISSUE TITLE
Nunits/Xunits support only .net8.0 and cannot be written specifically for either .net8.0 android or ios

### ISSUE THREAD

**Issue by SurajImmanuel** [dotnet/maui#23568]
### Description

Some of the external libraries released for MAUI does not support generic .net8.0 and are targeted towards android or IOS . N-units or X-units require .net8.0 to be added as a target framework which is not supported by these libraries. Although for .cs files, you have a way to make it compile still ,by having multi target platform codes . XAML does not have any option when a class from that library is used inside it .

### Steps to Reproduce

1. Create a new MAUI project
2. Download Scandit MAUI as nuget package
3. Include Scandit library as namespace in xaml and use its datacapture view 
4. Now create a new Xunit/Nunit project and add this MAUI as project reference
5. You will notice that XAML file is not recognized by this .net8.0 framework.

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

IOS11,Android13,Xunit

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@SurajImmanuel you'll need to open issues on the repositories to provide those targets. 

My guess is that those libraries don't really have any useful code they can run inside a net8.0 target, so, if you want to include them inside some tests you'll want to follow the guidelines for appium
https://learn.microsoft.com/en-us/samples/dotnet/maui-samples/uitest-appium-nunit/

**Comment by SurajImmanuel** [comment]
@PureWeen  My issue is Nunit demands us to include .net8.0 as target framework which is not our project demands and the libraries that we use do not support .Net8.0 and are more platform specific ( either android or IOS ) , I really cannot do much if .net8.0 does not support the namespace included in XAML .
