### ISSUE TITLE
[Bug] Button doesn't resize when text is changed

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2357]
### Description

Using Hot Reload I changed the button text to be longer. The text updates, but the button doesn't grow.

```
<HorizontalStackLayout HorizontalOptions="Start">
                    <Button Text="Button Button Button"/>
                    <Button Text="Button" IsEnabled="False"/>
                </HorizontalStackLayout>
```

![Screenshot_1630550640](https://user-images.githubusercontent.com/41873/131773228-7ec03b55-6a95-4226-bcaf-dd2442f575eb.png)

### Expected Behavior

When the button should size to fit the content I expect the change in content to trigger a layout of the button.

### Actual Behavior

No layout is changed.

### Basic Information

- Version with issue: rc.1.1567
- Platform Target Frameworks: 
  - Android: 28

**Comment by hartez** [comment]
Fixed on main.
