### ISSUE TITLE
MAUI default project template Windows platform creation completed and running failed

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/maui#23571]
### Description

![image](https://github.com/user-attachments/assets/d764c74c-ee7d-456d-9080-13da5789766d)
Create a maui default project. Run directly and report an error

### Steps to Reproduce

Create a maui default project. Run directly and report an error

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.61 SR6.1

### Affected platforms

Windows

**Comment by HuaFangYun** [comment]
Solution: Clean up the project, rebuild it, run it again, and the problem disappears.

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3 (8.0.70 & 8.0.61). Can not repro it. Maybe it is an unstable error.
