### ISSUE TITLE
[Bug] Issue in Pixel 2 Pie 9.0 - (Android 9.0 - API 28) in .NET 6 RC1

### ISSUE THREAD

**Issue by zeus2nawaz** [dotnet/maui#2358]
I had installed VS2022 preview 7 but later found some issue in Camera, So I had installed RC1 version for MAUI, After installing it my application works as expected with **Android_Emulator_30 (Android 11.0 - API 30)**

When I change the emulator to run on **Pixel 2**, It start the application but debugging was unattached after running the app, But When I tried to open that app without debug mode, it opens some functionalities from my app but in some functionalities it crash the app. 

In Android emulator every functionalities work as expected
Here is system information
Visual Studio Version
![image](https://user-images.githubusercontent.com/53426219/131781631-a1cf3655-c5f7-4b9e-bddf-189d4614c7cc.png)

SDK Version
![image](https://user-images.githubusercontent.com/53426219/131781738-3a2ab4dd-ee32-4613-868f-47b0bf23d88a.png)

Last Good SDK Version
6.0.100-preview.7.21379.14

**Comment by jfversluis** [comment]
Thank you for your patience! It seem some time has passed, I hope you got it to work in the meantime.

If you're still having problems please open a new issue with some more details about what code you have implemented. If the crashes give you any error messages or stacktraces, etc.

Thanks!
