### ISSUE TITLE
Support debuging windows unpackaged app

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#23598]
### Description

Due to my windows platform product is not planing to publish in windows app store, but notification can ignore the config for Package.appxmanifest when I want to use notification on unpackage app.
More detail please see on below use case.

### Public API Changes

not sure

### Intended Use-Case

Refer to the winui3 document for notification here https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cs
![image](https://github.com/user-attachments/assets/5bd458f5-701c-424c-bc14-603d5e1b7ade)
We can ignore the config for Package.appxmanifest, I believe that config is only for packaged app.
So here is an embarrassed scenario:
1. Quick to setup using community toolkit https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/snackbar?tabs=windows%2Cios
2. No need to config the Package.appxmanifest
3. Debug the app but crash was occurred
4. But publish the app using the unpackaged command and run it, no crash and notification is also no problem.

SampleApp code:
[SampleApp.zip](https://github.com/user-attachments/files/16202717/SampleApp.zip)

**Comment by jingliancui** [comment]
Hi @jfversluis , any thought? thanks.

**Comment by mattleibow** [comment]
This appears to be an issue with the community toolkit.

The enable unpackaged, add `<WindowsPackageType>None</WindowsPackageType>` to your csprok and then edit your `Properties\launchSettings.json` to have a `commandName` of `Project`:

```json
{
  "profiles": {
    "Windows Machine": {
      "commandName": "Project"
    }
  }
}
```

I see in the stack trace in the community toolkit issue this is the notifications failing so they will have to investigate.

**Comment by jingliancui** [comment]
Let me open new issue with the sample later

**Comment by mattleibow** [comment]
That app looks to be a packaged app.

However, the issue is in the way the community toolkit works and I am not sure if they have tested the unpackaged app scenarios. This is a bug in that library, not maui as far as I can see.
