### ISSUE TITLE
CTRL+ALT+L

### ISSUE THREAD

**Issue by montyc123** [dotnet/maui#23591]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
I'm sorry but its not clear to me what is meant here. Please provide a bit more detail. Although the shortcut key seems to indicate that this might be something inside of Visual Studio or Visual Studio Code. Please report it through the instructions above.

Thanks!
