### ISSUE TITLE
[Spec, TODO]  Define work for Forms/Device/Platform/Application

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#236]
# Define Application for MAUI

- Consolidate the xplat application and the native applications into a single class
- Create a better application concept for android that doesn't tie application to the activity
- Multi Window considerations
- How does this tie into https://github.com/dotnet/maui/issues/24
- How can we expose platform level events? OnNewIntent etc...

**Comment by mattleibow** [comment]
Just noticed that we may need some features from the Activity (such as the bundle and Intent) to get data...

**Comment by KPixel** [comment]
I'm glad to see Multi-Window in the list. I was surprised by the many gotchas for that scenario in X.F.
And the main culprit was `Device.BeginInvokeOnMainThread()`. Ideally, we should remove it, but even if we keep it, it must never be used inside X.F/MAUI. The proper pattern is to always pass the `IDispatcher`.

**Comment by bmitc** [comment]
I found this issue by looking for existing issues for multiple window support before creating one. Thanks for calling it out!

I am an F# developer and have been investigating [Fabulous](https://github.com/fsprojects/Fabulous) for a desktop application, but since it is built upon Xamarin Forms, it does not support multiple windows, so it's basically unusable for desktop applications.

Would it be better to separate out multiple window support into its own issue? I think that is an absolute must have if .NET MAUI is intended to support desktop applications.

**Comment by mrwcjoughin** [comment]
@bmitc i have found having tabs is an ideal way to do a modern MDI interface

infact 10 years ago I built a WPF app where I used tabs to open items the
users clicked on and it worked very well - much like a browser does...

**Comment by bmitc** [comment]
> i have found having tabs is an ideal way to do a modern MDI interface

Tabs are not an acceptable replacement for multiple windows for many applications.

**Comment by jetersen** [comment]
I'd like to ask what consideration are there made for windows parity? As someone who depends on third party software that has us using DDE dynamic data exchange on Windows, which requires a WinForm application to be running. I would still like to get some of the benefits of building on Linux but target Windows.

We recently taken https://github.com/Specshell/specshell.software.ndde and made it work on `net5.0-windows` which is great but would be great for all our downstream application which are in private repos to be able to build on Linux machines on GitHub actions.

See also
https://github.com/dotnet/sdk/issues/3592

**Comment by Redth** [comment]
Mostly handled by https://github.com/dotnet/maui/issues/1965 and the rest by other various PR's and issues/specs

**Comment by bmitc** [comment]
@Redth Do you know where the multiple windows feature is being tracked?
