### ISSUE TITLE
Publishing with uiAccess

### ISSUE THREAD

**Issue by tqphan** [dotnet/maui#23601]
### Description

I'm trying to publish a .NET MAUI app on Windows with the following node added to the `app.manifest`.

```
<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
  <security>
    <requestedPrivileges>
      <requestedExecutionLevel level="asInvoker" uiAccess="true" />
    </requestedPrivileges>
  </security>
</trustInfo>
```

I followed the instructions on the [official deployment documentation](https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-visual-studio-folder?view=net-maui-8.0).

I copied the self-signed certificate to Trusted Root Certification Authorities under Local Machine. 

When I try to run the app, I get the following error.
<img src="https://tqphan.github.io/img/error.png">

I also tried to run the app as administrator.

### Steps to Reproduce

1. Create an .Net Maui App
2. Add the above XML node to `app.manifest`
3. Deploy for Windows using a self-signed certificate 
4. Install the self-signed certificate to Trusted Authorities 
5. Install package and run the app

Minimal repository: https://github.com/tqphan/MauiDeployTest

### Link to public reproduction project repository

https://github.com/tqphan/MauiDeployTest

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Did you try this with a WinUI Template app that doesn't implement the MAUI UI Framework? Does it work there?

**Comment by tqphan** [comment]
I figured out the problem. UIAccess requires the executable to be signed and located in C:\Program Files\

Apparently the `dotnet publish` only sign the msix package and not the executable itself (bug or strange design decision?)
