### ISSUE TITLE
Shared projects are not visible in .NET MAUI Multi-Project App.

### ISSUE THREAD

**Issue by gwise-vision** [dotnet/maui#23619]
### Description

Shared projects are not visible in .NET MAUI Multi-Project App.
![111](https://github.com/user-attachments/assets/6b5df912-f4cd-4040-9f9a-7e2314dd7d8b)

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.61 SR6.1

### Affected platforms

iOS, Android

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3.0(8.0.70). Can repro it. If you add the .csproj of main project to solution, then all projects are visible.
![image](https://github.com/user-attachments/assets/4378597b-972c-4f31-b65e-b285cb53eebb)

**Comment by SmartmanApps** [comment]
It was intentionally removed in (approx) November, though I have no idea why. You just need to manually add it back in the csproj...

`<TargetFrameworks>net8.0;net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>`

**Comment by ccsousa01** [comment]
1. Right-click the Solution
2. Select Add -> Existing Project
3. Find your current project and add the .csproj of main project, which is missing from solution.

![image](https://github.com/user-attachments/assets/9cb52f9b-16c2-4cb7-ba4b-523cf994f698)

**Comment by jfversluis** [comment]
Seems this was either resolved with the suggestions here, if not, please report through the instructions of the bot. This is something in Visual Studio and unfortunately not something we can fix on our side.
