### ISSUE TITLE
`OnPropertyChanged("Item")` invalid in 'Release' mode

### ISSUE THREAD

**Issue by BaY1251** [dotnet/maui#23621]
### Description

Unable to update interface by calling 'OnPropertyChanged("Item") '

Maui-8.0.3
![8 0 3](https://github.com/user-attachments/assets/f56a1e40-e9ae-428a-9bce-a2ec6729a13b)

Maui-8.0.70
![8 0 70](https://github.com/user-attachments/assets/a1168793-0092-43d9-8152-7824de202333)

### Steps to Reproduce

Download https://github.com/BaY1251/MauiDebug.git

Open /PropertyInvalid/PropertyInvalid.sln
deployment the project in 'Release' mode
click 'Click me'

### Link to public reproduction project repository

https://github.com/BaY1251/MauiDebug.git

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

Android, Windows

**Comment by simonrozsival** [comment]
@BaY1251 you need to call `OnPropertyChanged($"Item[{i}-{j}]");` and not just `OnPropertyChanged("Item")`. Does this resolve your problem?

**Comment by BaY1251** [comment]
@simonrozsival Sorry, there are a lot of elements on my XAML page, and in your way, I have to repeat almost the same code in C# code. It's also very inconvenient to make changes

**Comment by simonrozsival** [comment]
@BaY1251 I see. I managed to repro the regression and pinpoint that it happened somewhere between [8.0.14 and 8.0.20](https://github.com/dotnet/maui/compare/8.0.14...8.0.20).

**Comment by simonrozsival** [comment]
This could be the relevant change: https://github.com/dotnet/maui/pull/21366 cc @StephaneDelcroix

**Comment by simonrozsival** [comment]
@BaY1251 I opened a PR with a fix: https://github.com/dotnet/maui/pull/24229

**Comment by BaY1251** [comment]
@simonrozsival Great! I tested Pipeines' Nuget and confirmed that it has been fixed
