### ISSUE TITLE
WebAuthenticator freezes in case when system kills app process

### ISSUE THREAD

**Issue by sleushunou** [dotnet/maui#23622]
### Description

The bug appears because your logic depends on a flag **AuthenticatingWithCustomTabs** whose object (**IWebAuthenticator.Default**) is in a static property that is destroyed when the application is killed. After the login is completed, an activity **WebAuthenticatorCallbackActivity** is created, and condition **WebAuthenticator.Default.IsAuthenticatingWithCustomTabs()** returns false instead of true, because **Default** object recreated, and **AuthenticatingWithCustomTabs** by default = false.

### Steps to Reproduce

1. Start login with WebAuthenticator. Custom tabs activity opens.
2. Lock screen for several minutes and wait until system kills app. **OR simulate this behavior: run adb shell am kill <packagename>.**
3. Continue login process.
4. Custom tabs activity cannot be closed, because this code does not execute
`
				// start the intermediate activity again with flags to close the custom tabs
				var intent = new Intent(this, typeof(WebAuthenticatorIntermediateActivity));
				intent.SetData(Intent.Data);
				intent.AddFlags(ActivityFlags.ClearTop | ActivityFlags.SingleTop);
				StartActivity(intent);
				`

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin 1.8.0-preview1

### Last version that worked well

Any Xamarin version

### Affected platforms

Android

### Did you find any workaround?

write IsAuthenticationInProgress flag to internal settings

**Comment by Zhanglirong-Winnie** [comment]
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
