### ISSUE TITLE
[iOS] Image on Button doesn't properly centered when setting ContentLayout to Top and text has 2 or more lines.

### ISSUE THREAD

**Issue by mecvillarina** [dotnet/maui#23635]
### Description

Image on Button doesn't properly centered when setting ContentLayout to Top and text has 2 or more lines. Please attached image

![Screenshot 2024-07-16 at 11 02 51 PM](https://github.com/user-attachments/assets/266bfadd-7053-42f1-8145-dae6d22b2437)

### Steps to Reproduce

1. Create a new MAUI App
2. Add the following lines on the MainPage.cs
` <Button ImageSource="ic_heart" LineBreakMode="WordWrap" Text="Add Waypoint" ContentLayout="Top,2" HorizontalOptions="Center" HeightRequest="150" WidthRequest="100" BackgroundColor="Blue" TextColor="White"/>`
3. Use the attached asset for your testing
![ic_heart](https://github.com/user-attachments/assets/96af8793-de41-4b03-bdae-3096a4b31913)
4. Run the App.

### Link to public reproduction project repository

https://github.com/mecvillarina/PocMaui

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by RoiChen001** [comment]
I can repro this issue at iOS platform on the latest 17.16.12 (build 410) (8.0.40&8.0.60).

**Comment by tj-devel709** [comment]
<img width="446" alt="image" src="https://github.com/user-attachments/assets/e5e6e1d9-453d-4ca4-bee7-26f82d6b92e4">

Hello, looks like this will be fixed in this PR: https://github.com/dotnet/maui/pull/22476!
