### ISSUE TITLE
When resizing the application window in Windows, if the resizing is done horizontally then elements within the window will resize correctly, but if resizing is done only vertically then resizing does not occur.

### ISSUE THREAD

**Issue by KloakLtd** [dotnet/maui#23641]
### Description

When resizing the application window in Windows, if the resizing is done horizontally then elements within the window will resize correctly, but if resizing is done only vertically then resizing does not occur.

The issue can be seen here:

[https://youtu.be/Q5QasHA6G3M](https://youtu.be/Q5QasHA6G3M)

### Steps to Reproduce

1. Create a new Application in MAUI Blazor
2. Create a new element on the page such as a button.
3. Position the element such that it is positioned absolutely within a relative container a fixed distance from the bottom and left.
4. Observe that when resizing the application window horizontally, the element snaps to the correct position in the view.
5. Observe that when resizing the application window vertically, the element does not snap to the correct position in the view.

Expected results: When the user resizes the application in any direction, the elements within the application window will adjust to the correct new position as defined in their CSS.

Actual results: Under some conditions when the user resizes the application window, the elements within the window will not adjust to the new position within the application view.

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Not sure, did not test other versions

### Last version that worked well

7.0.101

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

This issue is only affecting one of my projects at the moment, so I have not committed the resources to finding a workaround yet.

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3 (8.0.70 &8.0.3). Can repro it.
![resizing](https://github.com/user-attachments/assets/c581ea14-40a8-43fd-b6ac-ce38eea34d70)

**Comment by ninachen03** [comment]
> @ninachen03 I don't think your repro quite matches what the user has described

Thank you for your correction, I will verify it after getting the sample.

**Comment by KloakLtd** [comment]
@PureWeen @ninachen03 I think both issues are relevant to the problem, even if they are separate under the hood, as they both relate to how elements are displayed to the user responsively. I am happy to provide a quick repro as requested, and will look to get this to you both before the end of next week. 

Thank you for taking the time to look into this, I appreciate it!

**Comment by KloakLtd** [comment]
Embarrassingly, I'm now unable to reproduce, with the same code; must have just been my PC having a bad day, sorry to waste your time.
