### ISSUE TITLE
IntuneMAMAppConfig returns NULL value in IOS MAUI application

### ISSUE THREAD

**Issue by MikeP0911** [dotnet/maui#23670]
### Description

We are trying to migrate our Xamarin IOS app to MAUI with MSAL integration. Intune logged in successfully and also acquiring access token, but while getting App config values from the Intune portal it returns NULL value, so we are unable to proceed further. This used to work properly in Xamarin.Forms. Kindly share if any sample available for connecting with Intune (MSAL integration) in MAUI IOS app.

### Steps to Reproduce

1. Create Maui application for IOS platform.
2. Integrate MSAL in it.
3. Try to get the AppConfig values from Intune using IntuneMAMAppConfig.
4. It's not getting any values for given identity (Email) from Intune.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

iOS 14 and up

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@MikeP0911 we don't maintain the MSAL integration bits here. 

Can you create a new issue here https://github.com/AzureAD/microsoft-authentication-library-for-dotnet ?

**Comment by MikeP0911** [comment]
Sure, thank you @PureWeen
