### ISSUE TITLE
DataTrigger does not work on Mac Catalyst

### ISSUE THREAD

**Issue by xibeat** [dotnet/maui#23672]
### Description

We are trying to use a data trigger that reacts to a value change and change the text decoration. Basic todo list that strikes out text when marked complete. Unfortunately, Maui is not capable to handle this small thing. Please suggest a workaround/fix for this. Our timelines are getting affected because of this. This issue is there since September 2023. 

<img width="335" alt="Screenshot 2024-07-18 at 12 57 18 PM" src="https://github.com/user-attachments/assets/75a6dd88-8497-444b-9490-486ee9d03ef0">

`<Label
                                                Style="{StaticResource LabelTextRegular16}"
                                                Text="{Binding Title}"
                                                TextDecorations="None"
                                                VerticalTextAlignment="Start">
                                                
                                                <Label.Triggers>
                                                    <DataTrigger
                                                        Binding="{Binding IsCompleted}"
                                                        TargetType="Label"
                                                        Value="True">
                                                        <Setter Property="TextDecorations" Value="Strikethrough" />
                                                    </DataTrigger>
                                                </Label.Triggers>
                                            </Label>`
                                            
PS: We were considering Maui for our flagship product and have bet lot of resources on this. However we have mostly spent times on finding workaround than actually delivering features. We might have to shift away completely from MAUI if this persists. Very sad. 

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Sonoma

### Did you find any workaround?

No

### Relevant log output

```shell
None
```

**Comment by xibeat** [comment]
I am travelling and don't have access to a computer right now but here are
the repro steps.

Repro Steps:

1. Add a Collectionview
2. Add a data template with Imagebutton and text
3. Bind it to Text and IsComplete property of the model.
4. Add a data trigger on Imagebutton to change image based on IsComplete
property change.
5. Add a data trigger on the Text to change decoration to Strike through
based on IsComplete property change.
6. Run the project on Mac.
7. Change the IsComplete flag of the model with the help of command and
notice.
Image changes but the text strike through doesn't.
Prasun Singha Roy

**Comment by QianaJiao** [comment]
Hi @xibeat , would you mind share me a repo, I just create one with label and data trigger, it worked fine. Let's see if there is anything special in your code.
