### ISSUE TITLE
Shell Tabs on Android are sometimes not visually removed from view when IsVisible is set to false.

### ISSUE THREAD

**Issue by dantelegacyheating** [dotnet/maui#23717]
### Description

If you have a tab which sets its own IsVisible property to false in OnDisappearing, this tab can occasionally bug out and remain visible even though it has been logically removed somewhere in the code; evident because it throws an ArgumentOutOfRangeException if you try to tap it again once it should technically be hidden.

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Define a hiding tab class (code below)
3. Setup your appshell with 3 tabs, the latter being the hiding tab (code below)
4. Launch the app
5. Tap the 3rd tab (hiding tab)
6. Tap the 2nd tab (tab will not hide)
7. If you try to tap the 3rd tab again, the app will throw an ArgumentOutOfRangeException

Note that if you tap other tabs in the app and do not do it specifically in this order, the bug will not happen. I believe it is because you must navigate to a tab that you have not navigated to before in order to bug out the hiding tab.

HiddenTab.cs
```cs

namespace MauiApp1
{
	public class HiddenTab : Tab
	{
		public HiddenTab()
		{
			Disappearing += HiddenTab_Disappearing;
		}

		private void HiddenTab_Disappearing(object? sender, EventArgs e)
		{
			IsVisible = false;
		}
	}
}

```

AppShell.xaml

```xaml
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiApp1.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp1"
    Shell.FlyoutBehavior="Disabled"
    Title="MauiApp1">

    <TabBar>
        <Tab Route="MainPage" Title="Home">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}"/>
        </Tab>
        <Tab Route="MainPage2" Title="Home">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}"/>
        </Tab>
        <local:HiddenTab Title="Hiding"  Route="MainPageHiding">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}"/>
        </local:HiddenTab>
    </TabBar>


</Shell>
```

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Did you find any workaround?

I have yet to find a workaround for this issue, if anyone knows of one, please let me know.

**Comment by dantelegacyheating** [comment]
#8788 Seems to be related, but I've provided a quite different method of reproduction

**Comment by kevinxufei** [comment]
I can repro this issue at Android platform on the latest 17.11.0 Preview 4.0 (8.0.61&8.0.70).

**Comment by mattleibow** [comment]
@PureWeen thoughts?
