### ISSUE TITLE
Update to cake 1.2.0

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#2372]
It fixes some bugs, such as quoting binlog names that may have spaces in them.

But, that version is not on the internal feeds we use. Let's get Cake 1.2.0 pushed to the feeds, and update the version specified in `.config/dotnet-tools.json`, revert the binlog quote change I made in https://github.com/dotnet/maui/pull/2368, and test it.

**Comment by rmarinho** [comment]
i asked for the update.

**Comment by Eilon** [comment]
Ah looks like @rmarinho did the bump here: https://github.com/dotnet/maui/pull/2386/files#diff-7afd3bcf0d0c06d6f87c451ef06b321beef770ece4299b3230bb280470ada2f6L6-R6

I opened PR https://github.com/dotnet/maui/pull/2410 to remove the extra quotes I temporarily added that are no longer needed now that we use Cake 1.2.0.

**Comment by Eilon** [comment]
It turns out Cake 1.2.0 doesn't fix the particular quoting issue we ran into, so I'm closing this issue because we did in fact upgrade to Cake 1.2.0.
