### ISSUE TITLE
My Splash screen is not working in ios after upgrade to net8.0

### ISSUE THREAD

**Issue by viveklpu2011** [dotnet/maui#23736]
### Description

When it was net7.0 beow code was working for ios

```xml
<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-ios'">
    <MauiSplashScreen Include="Resources\Splash\playbg.png" Color="#27a4de" />
</ItemGroup>
```

but after upgrade to net8.0 the above code is not working, tried multiple ways to fix this but not working any of the solution

### Steps to Reproduce

After upgrade to net8.0 I am getting below screen in ios

<img src="https://github.com/user-attachments/assets/889f0d2f-6eb7-46ec-b0fb-f579d11fd01b" width="300" />

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 4.0(8.0.70&8.0.3). Can repro on iOS platforms. 
We already have a similar issue: https://github.com/xamarin/xamarin-macios/issues/18469. And below is the workaround:
You could add the following to the csproj:

```
<PropertyGroup>
    <EnableCodeSigning>true</EnableCodeSigning>
    <CodesignRequireProvisioningProfile>true</CodesignRequireProvisioningProfile>
    <DisableCodesignVerification>true</DisableCodesignVerification>
</PropertyGroup>
```

Hope it helps you.

**Comment by mnidhk** [comment]
I'm getting the same blue screen on my Android Api 34 simulator

- Working on Api 31 Android simulator
- Working on Android device Api 33
- Not working Android Api 34 simulator

Don't have a Api 34 Device but i think it has to do something with Api 34?
Using 8.0.61 Maui workload

**Comment by jfversluis** [comment]
Is this still an issue for you? Are you deploying from your Windows machine directly to the iOS device? 

If you deploy directly from Windows to your iDevice, you're using Hot Restart. If you look at [the documentation](https://learn.microsoft.com/dotnet/maui/ios/hot-restart) and look under Limitations, you will find

> Asset catalogs aren't supported. When using Hot Restart, your app will show a .NET icon and launch screen.

So this is expected and a known limitation.

Let me know if that helps at all.
