### ISSUE TITLE
[Bug] ContentPage.OnSizeAllocated is never called.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2373]
### Description

In Xamarin.Forms, OnSizeAllocated would be called as part of, I believe, the creation of a page when it inflates all of its elements. This method does not seem to ever be invoked in MAUI.

### Steps to Reproduce

Run this reproduction project. It should play an animation when the page loads on the image, but OnSizeAllocated is never called, so it never plays.

[MauiAnimationTest.zip](https://github.com/dotnet/maui/files/7102034/MauiAnimationTest.zip)

**Comment by Falo900** [comment]
Yeh

**Comment by wenwen60** [comment]
Not reproducible with Android 11 using above project.

**Comment by redek91** [comment]
I made a test with the Maui project template template (counter). It never is invoked.
Tested on Android 10(emulator) and 12(device)

**Comment by kojini** [comment]
I override `OnSizeAllocated(double width, double height)` in a Page but it is never called when I rotate my Android emulator (Android 11 - API 30).
The emulator's auto-rotate is on, MainActivity has `ConfigurationChanges = ConfigChanges.ScreenSize, ConfigChanges.Orientation` and `ScreenOrientation = ScreenOrientation.FullUser`.
Am I missing some sort of settings? or is this a bug?
