### ISSUE TITLE
Android Back Button Minimizes App When BlazorWebView Inside RefreshView

### ISSUE THREAD

**Issue by samanson123** [dotnet/maui#23740]
### Description

I was trying to implement RefreshView functionality in my BlazorWebView however down the line I realised that my back button presses when testing on Android were no longer navigating as I expected them to do in my blazor components. 

After working my way back, I found the RefreshView to be the root cause of the issue. Removing the RefreshView fixed the issue and added it back in caused the issue again. I had several navigation based methods across my Blazor Hybrid application such as NavigationLock on one component and a subscribe to the NavigationManager LocationChanged event on another and neither of them fire when the BlazorWebView is surrounded by the RefreshView.

### Steps to Reproduce

1. Create MAUI Blazor Hybrid application and ensure you have at least 2 pages to navigate between with Navigation Manager.
2. Navigate between pages without a RefreshView control surrounding the BlazorWebView and test back button on android. Will navigate back to the previous page.
3. Change the BlazorWebView to have a RefreshView surrounding it and repeat step 2. Will minimise the app to the background.

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by samanson123** [comment]
> Hi I'm an AI powered bot that finds similar issues based off the issue title.
> 
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!
> 
> ### Open similar issues:
> * [[regression/8.0.3] Disabling RefreshView disables the keyboard (#19091)](https://github.com/dotnet/maui/issues/19091),  similarity score: 0.75
> * [RefreshView is not initialized properly on Windows platform (#19715)](https://github.com/dotnet/maui/issues/19715),  similarity score: 0.74
> * [Maui Blazor app freezes after pressing back button on Android. (#22819)](https://github.com/dotnet/maui/issues/22819),  similarity score: 0.74
> 
> ### Closed similar issues:
> * [[Android] Blazor hybrid back navigation (#23381)](https://github.com/dotnet/maui/issues/23381),  similarity score: 0.78
> * [MAUI Blazor App OnBackPressed not firing after launching Modal XAML Window from Blazor (#11105)](https://github.com/dotnet/maui/issues/11105),  similarity score: 0.74
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

Issue is briefly commented about in #19091

**Comment by RoiChen001** [comment]
@samanson123  Could you provide us with a sample project so we can investigate it? Looking forward to your reply!
