### ISSUE TITLE
Unable to Disable the Window preview in MAUI 

### ISSUE THREAD

**Issue by dhinakaran-dgs-avasoft** [dotnet/maui#23754]
### Description

In Android and Xamarin we have an implementations in styles like
```xml
<?xml version="1.0" encoding="utf-8" ?> 
<resources xmlns:tools="http://schemas.android.com/tools">
    <!-- Base application theme. -->
    <style name="Theme.Icon" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
        <!-- Primary brand color. -->
        <item name="colorPrimary">#FE9900</item>
        <item name="colorPrimaryVariant">#FE9900</item>
        <item name="colorOnPrimary">#FE9900</item>     
        <!-- Status bar color. -->
        <item name="android:statusBarColor">?attr/colorPrimaryVariant</item>

        <item name="android:windowDisablePreview">false</item>
        <!-- Customize your theme here. -->
    </style>
</resources>
```
 but this in MAUI is missing

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All Android

### Did you find any workaround?

NO

**Comment by dhinakaran-dgs-avasoft** [comment]
<?xml version="1.0" encoding="utf-8" ?> 
<resources xmlns:tools="http://schemas.android.com/tools">
    <style name="Theme.Icon" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
        <item name="android:windowDisablePreview">true</item>
    </style>
</resources>
Need to implement this in MAUI but this does not work as expected

**Comment by dhinakaran-dgs-avasoft** [comment]
**You take Xamarin Android Project where we have a separate file called Style which can be used to setup Themes in Android but on MAUI we are unable to set up any theme for android the main issue is I cannot disable the white preview screen that comes before any content page which has large components.**

**Comment by dhinakaran-dgs-avasoft** [comment]
![image](https://github.com/user-attachments/assets/82149c75-4212-49ae-8ce0-114a86cc5af6)

You see here we have style.xml what should I do this to replicate same functions in MAUI

**Comment by jfversluis** [comment]
Did you also update the theme name in the `Platforms/Android/MainActivity.cs`? In the `Activity` attribute?

**Comment by dhinakaran-dgs-avasoft** [comment]
> Did you also update the theme name in the `Platforms/Android/MainActivity.cs`? In the `Activity` attribute?

@jfversluis  yes updated but still it has no effect

**Comment by jfversluis** [comment]
Could you please provide a small [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md)?
