### ISSUE TITLE
[WIN] MAUI Not Returning and Sending Microsoft.UI.Xaml.Input.PreviewKeyDown Event When Subscribed.

### ISSUE THREAD

**Issue by cgp1976** [dotnet/maui#23789]
### Description

There are two issues here

1. MAUI Not Returning Microsoft.UI.Xaml.Input.PreviewKeyDown Event When Subscribed.
2. MAUI Stop Sending Microsoft.UI.Xaml.Input.PreviewKeyDown Event When Subscribed.

```
var platformView = this.Handler.PlatformView as Microsoft.Maui.Platform.ContentPanel;
platformView.PreviewKeyDown += PlatformView_PreviewKeyDown;

private void PlatformView_PreviewKeyDown(object sender, Microsoft.UI.Xaml.Input.KeyRoutedEventArgs e)
{
    Debug.WriteLine($"Invoked @ {DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss:fff")}");
}
```
For Point 1
if the entire layout doesn't have a button control. this will never trigger the event.

For Point 2
We put a button control in the grid and from there onwards, we are able to receive the event but for some reasons, this will only work two times after it successfully invoked.

### Steps to Reproduce

[MauiApp1.zip](https://github.com/user-attachments/files/16357508/MauiApp1.zip)

Unzipped the attached file

For Point 1 
Go to MainPage.xaml and replace the entire Grid xaml with the following

```
    <Grid BackgroundColor="Gray">
        <Label BackgroundColor="Pink" Text="Label" VerticalTextAlignment="Center" HorizontalTextAlignment="Center" HeightRequest="30" WidthRequest="100"></Label>
    </Grid>
```
Run and Debug the project , once page loaded, you can input some keyboard input to see if event was invoked or not.
Expected - PlatformView_PreviewKeyDown is never called

For Point 2 
Go to MainPage.xaml and replace the entire Grid xaml with the following

```
    <Grid BackgroundColor="Gray">
        <Button Text="Button" BackgroundColor="Blue" HeightRequest="30" WidthRequest="100"></Button>
    </Grid>
```
Run and Debug the project , once page loaded, you can input some keyboard input to see if event was invoked or not.
Expected - PlatformView_PreviewKeyDown was Invoked, and it will fail after two times

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

nil

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 5.0(9.0.0-preview.6.24327.7). Can repro it on windows platform with sample project. After adding a click event to the button, clicking the button does not respond.

**Comment by Foda** [comment]
I've verified that this also doesn't work with NET8 versions, but I don't think it's a bug. I suspect that the preview key down events only trigger when a control has focus (ie: the button).

If your goal is to invoke commands, keyboard accelerators might be a solution: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/keyboard-accelerators
