### ISSUE TITLE
Getting object reference error while implement localization 

### ISSUE THREAD

**Issue by zeus2nawaz** [dotnet/maui#2379]
I want to perform localization MAUI
I had added three resources, en, ta, fr and adding picker to pick language 
But when I pick the language it gives me error object reference error, I had handle try catch block every possible in code, still not found from where it gives me error

Please help me to resolve this one
I am using .Net version RC1 
![image](https://user-images.githubusercontent.com/53426219/131947145-cf8c21a6-5e9c-4e13-98aa-263e8dba62d5.png)

NOTE:
Same code is working fine in Xamarin form project

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?

**Comment by hartez** [comment]
Duplicate of #2345
