### ISSUE TITLE
[Android] Span GestureRecognizers don't work when the span is wrapped over two lines.

### ISSUE THREAD

**Issue by SamuelJames101** [dotnet/maui#23801]
### Description

Create a label with some formatted text.
Add a span with text such as a link "https://en.wikipedia.org/wiki/Tottenham_Hotspur_F.C."
This link needs to be long enough to wrap.
Add a GestureRecognizer to that specific span.

Expected result
The whole span is clickable

Actual result
The first line is not clickable

### Steps to Reproduce

Click/Tap a wrapped span with an attached TapGestureRecognizer.
Not the whole string is tappable.

### Link to public reproduction project repository

https://github.com/SamuelJames101/MultiLineLinkIssue

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 5.0(8.0.70). Can repro on Android platform.
