### ISSUE TITLE
Can't take photos on MacOS

### ISSUE THREAD

**Issue by xebamart** [dotnet/maui#23815]
### Description

From an application MAUI on macOS does not allow you to take photos from an application. As you can see in the attached images.

<img width="1135" alt="Captura de pantalla 2024-07-24 a las 18 39 44" src="https://github.com/user-attachments/assets/d7268e46-8c41-4187-8096-94d279ca4800">

I attach the calling code:

```
        if (MediaPicker.Default.IsCaptureSupported)
        {
            var photo = await MediaPicker.Default.CapturePhotoAsync();

            if (photo is not null)
            {
                // save the file into local storage
                await using var sourceStream = await photo.OpenReadAsync();
            }
        }
```

In addition, she has been granted access permissions to the camera.

<img width="418" alt="Captura de pantalla 2024-07-24 a las 18 42 30" src="https://github.com/user-attachments/assets/9c5d3640-7acd-4b27-8666-e8b7046cfe68">

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS Sonoma 14.5

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Can you please create a reproduction project where you can recreate this issue in an isolated environment?
