### ISSUE TITLE
Unable to add different resolution images for platform specific in .net MAUI while migration

### ISSUE THREAD

**Issue by Utkarsh-Sway** [dotnet/maui#23822]
### Description

I am migrating my Xamarin forms project to .NET MAUI and while migrating i have multiple drawable folder for different screen resolutions and when i drag that folder to MAUI it throws error of multiple files with same name and i tried to do the same for iOS but the error is same, also i tried to rename the file with filename.png, filename_2x.png and filename_3x.png but while running in large screen also it is showing the base but it should show the larger image(filename_3x.png)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

**Comment by ninachen03** [comment]
I'm unable to repro this issue with the template Maui and Xamarin project (I'm in 17.12.0 Preview 1.0(8.0.82 & 8.0.3)), could you share me your repo？
The following document may help you
https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/configure-multi-targeting?view=net-maui-8.0
