### ISSUE TITLE
Accessing Deployment Files

### ISSUE THREAD

**Issue by jbeen25** [dotnet/maui#23833]
### Description

This seems to be a long-standing issue of not being able to access an assortment of files that are deployed with the application: SQLite, images, binary, (anything that is not text-based).

I am presuming the only solution around this is creating a Rest API or FTP server and downloading content to  ```csharp FileSystem.AppDataDirectory ```; even though, they are relatively tiny files.

I have created a small [project](https://github.com/jbeen25/AccessDeployedFiles) to test some theories with no success in getting around this so far.

### Link to public reproduction project repository

https://github.com/jbeen25/AccessDeployedFiles

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

**Comment by RoiChen001** [comment]
I can repro this issue at Windows platform on the latest 17.11.0 Preview 5.0 (9.0.0-preview.6.24327.7&8.0.70).

**Comment by jfversluis** [comment]
You have some extra clutter that describes these files and might interfere with how the resources are added.

If you remove [these](https://github.com/jbeen25/AccessDeployedFiles/blob/main/src/AccessDeployedFiles/AccessDeployedFiles/AccessDeployedFiles.csproj#L75-L83), does that change anything?

**Comment by jbeen25** [comment]
> You have some extra clutter that describes these files and might interfere with how the resources are added.
> 
> If you remove [these](https://github.com/jbeen25/AccessDeployedFiles/blob/main/src/AccessDeployedFiles/AccessDeployedFiles/AccessDeployedFiles.csproj#L75-L83), does that change anything?

Yes, it now works. I honestly can't believe it was that simple.

Here are the steps I took, which automatically created this code:
1) Select any file from File Explorer.
2) Drag the selected file to Visual Studios->Solution Explorer.
3) Drop the file in the Raw folder.

This automatically triggers an event within Visual Studios to edit project code adding the following lines you have pointed out.

**Comment by jfversluis** [comment]
All good, this was resolved!
