### ISSUE TITLE
.NET 8 MAUI Android - Storage.Preferences returns default value when executed whilst the application isn't open/running

### ISSUE THREAD

**Issue by tommyw1996** [dotnet/maui#23837]
### Code

bool showNotification = Preferences.Get(UserPreferenceKeys.ShowNotification, true);
bool showNotificationUsingDefault = Preferences.Default.Get(UserPreferenceKeys.ShowNotification, true);

### Issue

Returns default value when executed whilst the application isn't open/running.

### Scenario

My application is deployed via an ARM template and installed onto a local Android device via an APK file.

I'm currently trying to access some application preferences via a firebase messaging service using Firebase.Messaging.FirebaseMessagingService, specifically inside the OnMessageReceived method. I use these to determine if a notification should be shown or not. This method can be triggered in the background whilst the application isn't open/running, but when this happens, the preferences are returning the default values passed in, which in this case is **true**. 

If I set my preference to **false** from inside of the application, when the application is reloaded, I can see that the preferences have persisted still and stored correctly.

### Steps to Reproduce

1. Create .NET 8 MAUI Android application
2. Add some code to call _Preferences.Get(UserPreferenceKeys.ShowNotification, true)_ or _Preferences.Default.Get(UserPreferenceKeys.ShowNotification, true)_ that can be executed in the background whilst the application isn't open/running e.g. in my case here, this would be the firebase messaging service, explained more above in the description.
3. Add some code to be able to view the returned preference value whilst the application isn't running e.g. in my case, I use the preference to determine if a notification can be shown or not.
4. Add some code to set the preferences.

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

34

**Comment by Zhanglirong-Winnie** [comment]
@tommyw1996 
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
