### ISSUE TITLE
DatePicker Text hide while hovering in Windows

### ISSUE THREAD

**Issue by MohanrajSF3559** [dotnet/maui#23843]
### Description

When using a Date Picker in a .NET MAUI application on the Windows platform, the text and icon become hidden while hovering over the Date Picker. This behavior disrupts the user experience, as users cannot see the date text or the calendar icon when they move their cursor over the control.

### Steps to Reproduce

**Step:**
1. Run the application on a Windows platform.
2. Hover the cursor over the Date Picker control.
3. As you can see the issue like below video.
4. 
### Link to public reproduction project repository

[DataPickerFrameWorkIssue.zip](https://github.com/user-attachments/files/16386820/DataPickerFrameWorkIssue.zip)

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

NA

### Relevant log output

[_No response_](https://github.com/user-attachments/assets/6883064f-f145-40be-85cd-d1bcc643c40a)

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 5.0(8.0.70 & 8.0.61). Can repro on Windows platform.

**Comment by MitchBomcanhao** [comment]
```
    <Grid BackgroundColor="Black" WidthRequest="200" HeightRequest="50">
        <DatePicker x:Name="datePicker" TextColor="White" />
    </Grid>
```

you put a black background on a different control underneath the DatePicker, and you manually changed the text color on the picker to be white.
Looks like you wanted to use the control in dark mode, so maybe use that instead?

**Comment by MohanrajSF3559** [comment]
I tried this work around not working, Can you please reopen again.

 <Grid BackgroundColor="Black" WidthRequest="200" HeightRequest="50">
        <DatePicker x:Name="datePicker" TextColor="White" />
    </Grid>

**Comment by MohanrajSF3559** [comment]
<Grid BackgroundColor="Black" WidthRequest="200" HeightRequest="50">
        <DatePicker x:Name="datePicker" TextColor="White" />
    </Grid>

The above rendering is fine. But if I try to hover on DatePicker, the text is hide.
