### ISSUE TITLE
Can't install MAUI on Windows 11

### ISSUE THREAD

**Issue by MoonWaIker** [dotnet/maui#23864]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: Windows

Can't install MAUI on Windows 11
![image](https://github.com/user-attachments/assets/caa66847-2d93-4199-aa30-a933fe4bb631)

**Comment by jfversluis** [comment]
Hey there, thanks for wanting to try out .NET MAUI!

Can you post more details about the machine you're trying to install this on? If you try to install the .NET MAUI workload through the Visual Studio installer, does it work then?
