### ISSUE TITLE
Will maui be much bugful as painful as Xamarin.Forms?

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/maui#2387]
Will maui be much bugful as painful as Xamarin.Forms?Please dont mind .Xamarin is horrible an bugful .Again please answer truely.I have lost my one job for Xamarin.Will maui give me any hope or I should learn new framework like flutter ??

**Comment by vhugogarcia** [comment]
No it won't be that way. In fact, Xamarin.Forms is not what you are saying. .NET is a huge collaboration between the best MS devs + community devs, creating the best cross-platform technology and that is going be beyond any expectation. Imagination won't have limits.

Learn any technology you wish to. Just remember Flutter is based on Dart.

**Comment by Barshan-Mandal** [comment]
but i can use flutter bindings

**Comment by Barshan-Mandal** [comment]
> No it won't be that way. In fact, Xamarin.Forms is not what you are saying. .NET is a huge collaboration between the best MS devs + the best community devs out there, creating the best cross-platform technology and that is going be beyond any expectation. Imagination won't have limits.
> 
> Learn any technology you wish to. Just remember Flutter is based on Dart.

but i can use flutter bindings..
Even maui uses blazor which may be obsolate anytime,no surity.
According to your answer I will learn maui.
Please dont break my trust

**Comment by davidbuckleyni** [comment]
How can you blame xamrain for jib i had one incident quite similar. But this was down to sales person making promises devs could not keep.

**Comment by saint4eva** [comment]
> Will maui be much bugful as painful as Xamarin.Forms?Please dont mind .Xamarin is horrible an bugful .Again please answer truely.I have lost my one job for Xamarin.Will maui give me any hope or I should learn new framework like flutter ??

It seems you were not good at the job anyways?

**Comment by Barshan-Mandal** [comment]
> > Will maui be much bugful as painful as Xamarin.Forms?Please dont mind .Xamarin is horrible an bugful .Again please answer truely.I have lost my one job for Xamarin.Will maui give me any hope or I should learn new framework like flutter ??
> 
> It seems you were not good at the job anyways?
No.But the bug fixing would take much time

**Comment by Barshan-Mandal** [comment]
> > Will maui be much bugful as painful as Xamarin.Forms?Please dont mind .Xamarin is horrible an bugful .Again please answer truely.I have lost my one job for Xamarin.Will maui give me any hope or I should learn new framework like flutter ??
> 
> It seems you were not good at the job anyways?

I think you dont know the matter.So shut up.

**Comment by GeraudFabien** [comment]
> I think you dont know the matter.So shut up.

He was good enough to not be fired so he don't know. Don't blame him 😂.

Also this thread should be close. It's only a useless troll to begin with. So expect some troll to come.

**Comment by Barshan-Mandal** [comment]
> > I think you dont know the matter.So shut up.
> 
> He was good enough to not be fired so he don't know. Don't blame him 😂.
> 
> Also this thread should be close. It's only a useless troll to begin with. So expect some troll to come.

I think you are mad.Without understanding the topic please dont talk.Shut your mouth up.
