### ISSUE TITLE
MAUI Splash screen does not take full screen size Xiaomi device  

### ISSUE THREAD

**Issue by ibrahimahmed1998** [dotnet/maui#23878]
### Description

I tried to make splash screen to take full screen size of Xiaomi device but it appears like a small box 
I tried to get a large value of Base size to be able to test the full fill of screen

`<ItemGroup>
		<MauiSplashScreen Include="Resources\Splash\splash.png" Color="#96433F" BaseSize="2000,2000" TintColor="#96433F" Resize="False" />
</ItemGroup>`

![058f2706-c795-49c6-ab0e-4c1a0523ec3c](https://github.com/user-attachments/assets/25ebedc7-168d-495b-9228-23252e7545e1)

MIUI Version : MIUI Global 14.0.01 
Android Version:12 SKQ1.211.006.001  

MainActivity.cs Code: 

```
public class MainActivity : MauiAppCompatActivity
 {
        protected override void OnCreate(Bundle savedInstanceState){
             base.OnCreate(savedInstanceState);
HandleIntent(Intent);
CreateNotificationChannelIfNeeded();
        }
```
        protected override void OnNewIntent(Intent intent)
        { base.OnNewIntent(intent);  HandleIntent(intent); }

        private static void HandleIntent(Intent intent)
        {
            FirebaseCloudMessagingImplementation.OnNewIntent(intent);
        }

        private void CreateNotificationChannelIfNeeded()
        {
            if (Build.VERSION.SdkInt >= BuildVersionCodes.O)
            {
                CreateNotificationChannel();
            }
        }

        private void CreateNotificationChannel()
        {
            var channelId = $"{PackageName}.general";
            var notificationManager = (NotificationManager)GetSystemService(NotificationService);
            var channel = new NotificationChannel(channelId, "General", NotificationImportance.Default);
            notificationManager.CreateNotificationChannel(channel);
            FirebaseCloudMessagingImplementation.ChannelId = channelId;
            //FirebaseCloudMessagingImplementation.SmallIconRef = Resource.Drawable.ic_push_small;

AndroidManifest.xml Code: 

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.companyname.Tenant2" android:versionCode="1">
	<application android:allowBackup="true" android:name="android.support.multidex.MultiDexApplication" android:supportsRtl="true" android:label="Tenant" android:icon="@mipmap/appicon">
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
				<category android:name="${applicationId}" />
			</intent-filter>
		</receiver>
	</application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />
	<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
	<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
	<uses-permission android:name="android.permission.BATTERY_STATS" />
	<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
	<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
	<uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="34" />
	<queries>
		<intent>
			<action android:name="android.intent.action.DIAL" />
			<data android:scheme="tel" />
		</intent>
	</queries>
	<queries>
		<intent>
			<action android:name="android.intent.action.SENDTO" />
			<data android:scheme="mailto" />
		</intent>
	</queries>
	<queries>
		<intent>
			<action android:name="android.intent.action.VIEW" />
			<data android:scheme="geo" />
		</intent>
	</queries>
	<queries>
		<intent>
			<action android:name="android.intent.action.VIEW" />
			<data android:scheme="http" />
		</intent>
		<intent>
			<action android:name="android.intent.action.VIEW" />
			<data android:scheme="https" />
		</intent>
	</queries>
	<queries>
		<intent>
			<action android:name="android.intent.action.VIEW" />
			<data android:scheme="smsto" />
		</intent>
	</queries>
</manifest>`

### Steps to Reproduce

I tried to make splash screen to take full screen size of Xiaomi device but it appears like a small box 
I tried to get a large value of Base size to be able to test the full fill of screen
`<ItemGroup>
		<MauiSplashScreen Include="Resources\Splash\splash.png" Color="#96433F" BaseSize="2000,2000" TintColor="#96433F" Resize="False" />
</ItemGroup>`

![058f2706-c795-49c6-ab0e-4c1a0523ec3c](https://github.com/user-attachments/assets/25ebedc7-168d-495b-9228-23252e7545e1)

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by ibrahimahmed1998** [comment]
still exists after attached links

**Comment by RoiChen001** [comment]
I can repro this issue at Android platform on the latest 17.12.0 Preview 1.0(8.0.80 &8.0.72 & 8.0.10).

**Comment by DaanKwilia** [comment]
I have the same issue, It has to do with dark mode. I found: https://github.com/dotnet/maui/issues/24837 and implemented the propsed change, but that dit not resolve the issue.

**Comment by mattleibow** [comment]
This is the forced behaviour of the OS. Since android 12, no app is allowed to have a full screen splash. All you have is that small square and no matter what you do it will be forced into it.

Maybe one day Google will allow full screen again.
