### ISSUE TITLE
cant build app

### ISSUE THREAD

**Issue by Yash000** [dotnet/maui#23876]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://github.com/user-attachments/assets/52e03e80-9108-4f16-bd0a-f029542be1b2)

**Comment by jfversluis** [comment]
Hi there, thanks for your interest in .NET MAUI! Sorry to hear you're having some trouble getting started.

Are you trying to deploy to Windows? Did you successfully install the .NET MAUI workload through Visual Studio?
Could you maybe expand that first node in the Error output and show us the complete error message? Or maybe attach the complete build output?

Thanks!
