### ISSUE TITLE
App sometimes crashes in Background on iOS Release

### ISSUE THREAD

**Issue by phillippschmedt** [dotnet/maui#23882]
### Description

Hi,

my app sometimes crashes when it receives a silent push notification. Some of the crash logs indicate that the app is trying to render UI while being in background and woke up from the push. This part takes too long and is then terminated by watchdog. Even if I remove all my push related logic from the app it will still sometimes crash upon receiving the push notification. 

I reported the issue here earlier but without any success: https://github.com/xamarin/xamarin-macios/issues/20769

I see the crash on iOS devices on testflight. I can't seem to reproduce the issue outside the test flight environment even when building for release. The crash seems to happen at times where the app receives a silent push (I send the silent push to the full hour and it crashes on the full hour). 

According to the crash reports the app is killed by apple because the app takes too much time. Since there is no custom code that I execute I assume this is a bug somewhere inside .NET MAUI.

Devices I saw the crash on:
iPhone XR
iPad 9. Gen
iPhone 13

Crash seems to effect older devices more than newer.

Crash Logs:
[myApp2024-07-23-114651_symbolicated.txt](https://github.com/user-attachments/files/16409304/myApp2024-07-23-114651_symbolicated.txt)
[myApp-2024-07-18-120045_symbolicated.txt](https://github.com/user-attachments/files/16409305/myApp-2024-07-18-120045_symbolicated.txt)
[myApp-2024-06-27-100234_symbolicated.txt](https://github.com/user-attachments/files/16409306/myApp-2024-06-27-100234_symbolicated.txt)
[myapp2024-06-26-220557_symbolicated.txt](https://github.com/user-attachments/files/16409307/myapp2024-06-26-220557_symbolicated.txt)
[myApp-2024-07-29-150203_symbolicated.txt](https://github.com/user-attachments/files/16425285/myApp-2024-07-29-150203_symbolicated.txt)
[myApp-2024-07-29-120225_symbolicated.txt](https://github.com/user-attachments/files/16425281/myApp-2024-07-29-120225_symbolicated.txt)
[myApp-2024-07-29-140157_symbolicated.txt](https://github.com/user-attachments/files/16425283/myApp-2024-07-29-140157_symbolicated.txt)
[myApp-2024-07-29-130425_symbolicated.txt](https://github.com/user-attachments/files/16425284/myApp-2024-07-29-130425_symbolicated.txt)

Any help is highly appreciated.
Cheers

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

17.5.1 / 17.6

### Did you find any workaround?

No

**Comment by phillippschmedt** [comment]
More Crash Reports: 
[myApp-2024-07-29-150203_symbolicated.txt](https://github.com/user-attachments/files/16425285/myApp-2024-07-29-150203_symbolicated.txt)
[myApp-2024-07-29-120225_symbolicated.txt](https://github.com/user-attachments/files/16425281/myApp-2024-07-29-120225_symbolicated.txt)
[myApp-2024-07-29-140157_symbolicated.txt](https://github.com/user-attachments/files/16425283/myApp-2024-07-29-140157_symbolicated.txt)
[myApp-2024-07-29-130425_symbolicated.txt](https://github.com/user-attachments/files/16425284/myApp-2024-07-29-130425_symbolicated.txt)

**Comment by mattleibow** [comment]
Thanks for the extra info. I reopened the issue in macios and will close this for now.

**Comment by its-jefe** [comment]
Not sure if this is related (I'll probably create a new issue) but similarly my iOS 17+ apps crash when sent to background but only on iPad. Testflight crash report indicates UIKitCore: _UIGraphicsBeginImageContextWithOptions as the culprit.
