### ISSUE TITLE
After updating the timezone, App is still showing the old date and time of the previously set time zone

### ISSUE THREAD

**Issue by kiranbasvaraj** [dotnet/maui#23894]
### Description

When we update the time zone in the IOS device version 17.5.1 the app still sends the old date and time of the previously set timezone

### Steps to Reproduce

1. create a new app in Maui
2 set the device time to IST(Indian standard timezone)
3. let's say the device time is 8:15 PM-Use DateTime.Now.Local() and print it
4. now change the time zone to Madrid, Spain  from the settings app of the ios device (assume time is 4:15 PM)without killing the MAUI app
5. Bring the MAUI app back and try printing it again 
 Issue-It prints 8:15 PM instead of 4:15PM

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS-17.5.1

### Did you find any workaround?

only force closing the app and reopening it will work

**Comment by mattleibow** [comment]
@rolfbjarne will changing the OS timezone trigger some sort of event or something in the app to update the current dotnet instance?

**Comment by kiranbasvaraj** [comment]
even after doing the above change this is not working  system DateTime is still giving the time of old timezone but not the newly updated one

**Comment by kiranbasvaraj** [comment]
> We don't listen for timezone changes, it's the app's responsibility to do that.
> 
> You can listen to the [ObserveSignificantTimeChange](https://learn.microsoft.com/en-us/dotnet/api/uikit.uiapplication.significanttimechangenotification?view=xamarin-ios-sdk-12) even to detect when the time zone changed.
> 
> Then you can clear the cached timezone data by calling [TimeZoneInfo.ClearCachedData](https://learn.microsoft.com/en-us/dotnet/api/system.timezoneinfo.clearcacheddata?view=net-8.0#system-timezoneinfo-clearcacheddata).

could you suggest work around

**Comment by rolfbjarne** [comment]
> > We don't listen for timezone changes, it's the app's responsibility to do that.
> > You can listen to the [ObserveSignificantTimeChange](https://learn.microsoft.com/en-us/dotnet/api/uikit.uiapplication.significanttimechangenotification?view=xamarin-ios-sdk-12) even to detect when the time zone changed.
> > Then you can clear the cached timezone data by calling [TimeZoneInfo.ClearCachedData](https://learn.microsoft.com/en-us/dotnet/api/system.timezoneinfo.clearcacheddata?view=net-8.0#system-timezoneinfo-clearcacheddata).
> 
> could you suggest work around

This worked for me:

```cs
notification = UIApplication.Notifications.ObserveSignificantTimeChange ((sender, args) => {
    Console.WriteLine ("Notification: {0}", args.Notification);
    TimeZoneInfo.ClearCachedData ();
});
// notification is a class-level instance field

NSTimer.CreateRepeatingScheduledTimer (TimeSpan.FromSeconds (1), (v) =>
{
	Console.WriteLine ($"{DateTime.Now}");
});
```

Output is something like this:

```
8/8/2024 11:21:52
8/8/2024 11:21:53
Notification: NSConcreteNotification 0x283e4c920 {name = UIApplicationSignificantTimeChangeNotification; object = <UIApplication: 0x108b35050>}
8/8/2024 05:21:54
8/8/2024 05:21:55
8/8/2024 05:21:56
8/8/2024 05:21:57
8/8/2024 05:21:58
8/8/2024 05:21:59
8/8/2024 05:22:00
8/8/2024 05:22:01
8/8/2024 05:22:02
8/8/2024 05:22:03
Notification: NSConcreteNotification 0x283fc58c0 {name = UIApplicationSignificantTimeChangeNotification; object = <UIApplication: 0x108b35050>}
8/8/2024 11:22:04
8/8/2024 11:22:05
```
