### ISSUE TITLE
[HELP] How to specify a fixed size for the application window? (.NET MAUI Blazor WinUI)

### ISSUE THREAD

**Issue by jwiggenhorn** [dotnet/maui#2389]
### Discussed in https://github.com/dotnet/maui/discussions/2370

<div type='discussions-op-text'>

<sup>Originally posted by **jwiggenhorn** September  2, 2021</sup>
Hi, I'm working on an application using the .NET MAUI Blazor template. This application is mainly targeting Windows and I'd like to be able to specify a fixed application window size. Is this currently possible? 

I'm able to set the size of the BlazorWebView within MainPage.xaml using the WidthRequest and HeightRequest properties but this does not affect the overall window size.</div>

**Comment by Eilon** [comment]
Hi @jwiggenhorn , it looks like there's an open issue on that in the WinUI repo: https://github.com/microsoft/microsoft-ui-xaml/issues/2731

That issue includes some workarounds.

**Comment by jwiggenhorn** [comment]
For anyone else having this issue, here's what ended up working for me:

```
// App.xaml.cs

	public App()
	{
		InitializeComponent();

                Microsoft.Maui.Handlers.WindowHandler.WindowMapper[nameof(IWindow)] = (handler, view) =>
                {
#if WINDOWS
                	var nativeWindow = handler.NativeView;
            		nativeWindow.Activate();
            		IntPtr windowHandle = PInvoke.User32.GetActiveWindow();

            		PInvoke.User32.SetWindowPos(windowHandle, 
					PInvoke.User32.SpecialWindowHandles.HWND_TOP,
                                        0, 0, width, height,  // width and height are ints
                                        PInvoke.User32.SetWindowPosFlags.SWP_NOMOVE);
#endif
        	};
    	}
```
