### ISSUE TITLE
xcode-select --install xcode-select: note: Command line tools are already installed. Use "Software Update" in System Settings or the softwareupdate command line interface to install updates

### ISSUE THREAD

**Issue by immanjeba98** [dotnet/maui#23907]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mattleibow** [comment]
re you having issues building a maui app, or is this just an error that you saw?

I think this should not prevent you from building as it is just saying this has already been done. But, please let us know if there are issues building still.
