### ISSUE TITLE
Invalid scene used in WindowStateManager for iOS with CarPlay app

### ISSUE THREAD

**Issue by jpiechowiak** [dotnet/maui#23910]
### Description

There is a bug in `WindowStateManager.ios.cs` in code which resolves Window:

We have code like this:

```csharp
using var scenes = UIApplication.SharedApplication.ConnectedScenes;
var windowScene = scenes.ToArray<UIWindowScene>().FirstOrDefault();
return windowScene?.Windows.FirstOrDefault();
```

It works fine (in general), but in case when CarPlay app is used (we are migrating XF app with CarPlay), then it doesn't work fine in certain scenarios because `CarPlay` scene might be used. 

Additionally notice override for `GetConfiguration` in `AppDelegate`. Default version produces warnings. 

REPO NOTICE
You need to have CarPlay capabilities to test repo fully, right now It is more like a scratch, but should be enough. 

--- 
Additional issue occurs also in Mopups library. Here is proposal PR (not mine) for this library which fixes that: https://github.com/LuckyDucko/Mopups/pull/125/files

### Steps to Reproduce

1. Create Maui App 
2. Add application and CarPlay scene 
3. Run mobile app
4. Run CarPlay app
5. Send mobile app to background

### Link to public reproduction project repository

https://github.com/jpiechowiak/maui-scenes-bug

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 13+

### Did you find any workaround?

Yes. A little bit hacky, but works.

Add following method to `AppDelegate`

```csharp
private static void OverrideWindowStateManager()
{
    var type = Type.GetType("Microsoft.Maui.ApplicationModel.WindowStateManager, Microsoft.Maui.Essentials");
    type.SomeNotNull()
        .FlatMap(t => t.GetMethod("SetDefault",
            BindingFlags.Static | BindingFlags.NonPublic,
            null,
            new Type[] { typeof(IWindowStateManager) },
            null).SomeNotNull())
        .MatchSome(mi => mi.Invoke(null, new object[] { new MyWindowStateManager() }));
}
```

call this method on the beginning of `CreateMauiApp` method. Here is scratch of `MyWindowStateManager` implementation: 

```csharp
public class MyWindowStateManager : IWindowStateManager
{
    // Rest of the code

    static UIWindow? GetKeyWindow()
    {
        // if we have scene support, use that
        if (OperatingSystem.IsIOSVersionAtLeast(13) || OperatingSystem.IsMacCatalystVersionAtLeast(13))
        {
            try
            {
                using var scenes = UIApplication.SharedApplication.ConnectedScenes.ToArray().OfType<UIWindowScene>;
                var windowScene = scenes.FirstOrDefault(x.Session.Role == UIWindowSceneSessionRole.Application);
                return windowScene?.Windows.FirstOrDefault();
            }
            catch (InvalidCastException)
            {
                // HACK: Workaround for https://github.com/xamarin/xamarin-macios/issues/13704
                //       This only throws if the collection is empty.
                return null;
            }
        }

        // use the windows property (up to 13.0)
        return UIApplication.SharedApplication.KeyWindow;
    }

    static UIWindow[]? GetWindows()
    {
        // if we have scene support, use that
        if (OperatingSystem.IsIOSVersionAtLeast(13) || OperatingSystem.IsMacCatalystVersionAtLeast(13))
        {
            try
            {
                using var scenes = UIApplication.SharedApplication.ConnectedScenes.ToArray().OfType<UIWindowScene>;
                var windowScene = scenes.FirstOrDefault(x => x.Session.Role == UIWindowSceneSessionRole.Application);
                return windowScene?.Windows;
            }
            catch (InvalidCastException)
            {
                // HACK: Workaround for https://github.com/xamarin/xamarin-macios/issues/13704
                //       This only throws if the collection is empty.
                return null;
            }
        }

        // use the windows property (up to 15.0)
        return UIApplication.SharedApplication.Windows;
    }
}
```

**Comment by mattleibow** [comment]
Would you be interested in opening a PR to fix this? Would be great to call you a .NET MAUI contributor!

**Comment by jpiechowiak** [comment]
Added PR https://github.com/dotnet/maui/pull/23945
