### ISSUE TITLE
Webservice SOAP ASMX downt work in Android and iOS .net MAUI 8.0

### ISSUE THREAD

**Issue by herickfaro** [dotnet/maui#23922]
### Description

I try to consume a SOAP WebService on an Android device and it shows the error "Connection failure". On iOS, the error is "dynamic code generation is not supported on this platform", even with AOT enabled. It works normally on Windows Machine  connect to webservice.

Error at line 19 from MauiSoapConsumer/MainPage.xaml.cs
Repro project: [https://github.com/markos-jr/MauiSoapConsumer]( https://github.com/markos-jr/MauiSoapConsumer)

### Steps to Reproduce

For iOS:
1. Create a new .NET MAUI App.
2. Choose the "iPhone 15 SE iOS 17.4" simulator from the list iOS Simulators targets.
3. Enable AOT Compilation
4. Debug the app.
5. Observe the app launch in the simulator, but the debugger detach and report "dynamic code generation is not supported on this platform"

For Android:
1. Create a new .NET MAUI App.
2. Choose the "Pixel 5 API 34 (Android 14.0 - API 34)" simulator from the list Android Simulators targets.
3. Enable AOT Compilation
4. Debug the app.
5. Observe the app launch in the simulator, but the debugger detach and report "Connection failure"

### Link to public reproduction project repository

https://github.com/markos-jr/MauiSoapConsumer

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by mattleibow** [comment]
This looks like the SOAP libraries are not working correctly on mobile because they generate code at runtime - which is not supported. 

Please open an issue in their repository for AOT support.

**Comment by herickfaro** [comment]
@mattleibow what's repository?

This look loke the SOAP is working in .net 7. May be a problem at .net 8. Ok?

**Comment by herickfaro** [comment]
@mattleibow please, reopen this issue. it's not resolved

**Comment by TiberiusDRAIG** [comment]
We don't use MAUI for Android, so I can't speak to that, but we do build our app for MacCatalyst and enabling the Mono interpreter allows the dynamic code in our SOAP client (generated with VS 'Connected Services') to run as expected. The same can be done on iOS.

See: https://learn.microsoft.com/en-us/dotnet/maui/macios/interpreter?view=net-maui-8.0
