### ISSUE TITLE
[Bug] Grid Maui Control don't automatically expand the child when wrap inside the NavigationPage

### ISSUE THREAD

**Issue by AlfonChitoSalano** [dotnet/maui#2393]
### Description
Grid Maui Control don't automatically expand the child when wrap inside the NavigationPage

### Steps to Reproduce

1. in the app.xaml.cs add this lines of code
protected override Window CreateWindow(IActivationState activationState)
            => new Window(new NavigationPage(new GridBugPage()));
2. Bug occur in android (could be in ios as well)

### Expected Behavior

The Child view should fill and expand when loaded

### Actual Behavior

The Child view Dont fill and expand when loaded

### Basic Information
- Version with issue:
Microsoft Visual Studio Community 2022 Preview
Version 17.0.0 Preview 3.1
VisualStudio.17.Preview/17.0.0-pre.3.1+31612.314
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.145 (main@bdc8369)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.58 (remotes/origin/d17-0@927d548a1)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.3 (a84fb28)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.4.99.70 (main/7e1558c)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@4fb7c14
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@623332d

Xamarin.iOS and Xamarin.Mac SDK   14.99.0.294 (13b1b3c45)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

- Last known good version: NA
- IDE: 2022 preview
- Platform Target Frameworks: 
  Ocuured in Android but could be in other platforms as well
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: NA
- Nuget Packages: Microsoft.Maui.Dependencies

### Screenshots

![image](https://user-images.githubusercontent.com/20876086/132078658-73f4b610-78dc-4398-9304-cdc7a0fe2097.png)

### Reproduction Link

https://github.com/AlfonChitoSalano/MauiExamples/tree/gridbug/ReproducibleBugs

### Workaround

don't wrap the contentpage inside the navigationpage

**Comment by hartez** [comment]
This is fixed in Preview 10.
