### ISSUE TITLE
The bug of LinearItemLayout for CollectionView

### ISSUE THREAD

**Issue by JieNiGui06** [dotnet/maui#23936]
### Description

If I set itemspacing as any number such as 10，then the collection view will lag，and if a scroll view was outside，before the collection view scroll to edge ，the external scroll view will be scroll edge together.More，see this   https://learn.microsoft.com/zh-cn/answers/questions/1846045/collectionview?comment=question#newest-question-comment

### Steps to Reproduce

https://learn.microsoft.com/zh-cn/answers/questions/1846045/collectionview?comment=question#newest-question-comment

### Link to public reproduction project repository

https://learn.microsoft.com/zh-cn/answers/questions/1846045/collectionview?comment=question#newest-question-comment

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android9-14 

### Did you find any workaround?

no

**Comment by ninachen03** [comment]
Could you provide a sample project for us to investigate it further?
Looking forward to your reply!
