### ISSUE TITLE
Activity client record must not be null to execute transaction item

### ISSUE THREAD

**Issue by nk-alex** [dotnet/maui#23939]
### Description

I'm just getting this random crash by debugging my applicaton on Android enulator (Pixel 5 - API 34):

```
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: io.contafact.com, PID: 5758
[AndroidRuntime] java.lang.IllegalArgumentException: Activity client record must not be null to execute transaction item: TopResumedActivityChangeItem{onTop=true}
[AndroidRuntime] 	at android.app.servertransaction.ActivityTransactionItem.getActivityClientRecord(ActivityTransactionItem.java:66)
[AndroidRuntime] 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:43)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:205)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:294)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
**Java.Lang.IllegalArgumentException:** 'Activity client record must not be null to execute transaction item: TopResumedActivityChangeItem{onTop=true}'

[monodroid-assembly] Shared library 'liblog' not loaded, p/invoke '__android_log_print' may fail
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.IllegalArgumentException: Activity client record must not be null to execute transaction item: TopResumedActivityChangeItem{onTop=true}
[MonoDroid] 
[MonoDroid]   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
[MonoDroid] java.lang.IllegalArgumentException: Activity client record must not be null to execute transaction item: TopResumedActivityChangeItem{onTop=true}
[MonoDroid] 	at android.app.servertransaction.ActivityTransactionItem.getActivityClientRecord(ActivityTransactionItem.java:66)
[MonoDroid] 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:43)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[MonoDroid] 	at android.os.Looper.loopOnce(Looper.java:205)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:294)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[MonoDroid] 
[MonoDroid]   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
[MonoDroid] java.lang.IllegalArgumentException: Activity client record must not be null to execute transaction item: TopResumedActivityChangeItem{onTop=true}
[MonoDroid] 	at android.app.servertransaction.ActivityTransactionItem.getActivityClientRecord(ActivityTransactionItem.java:66)
[MonoDroid] 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:43)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[MonoDroid] 	at android.os.Looper.loopOnce(Looper.java:205)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:294)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[MonoDroid] 
[Process] Sending signal. PID: 5758 SIG: 9
```

### Steps to Reproduce

I don't really know how to reproduce this issue. Just sometimes when start debugging, the application is crashing. Fond some information that could be helpful [here](https://stackoverflow.com/questions/72390747/crash-activity-client-record-must-not-be-null-to-execute-transaction-item-only)

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 28.0

### Did you find any workaround?

-

### Relevant log output

```shell
-
```

**Comment by jfversluis** [comment]
Do you have any relevant code of where this happens in your application? What APIs are you using? What is the action you take in your app? Without any information it will be very hard to make this issue actionable.

**Comment by jfversluis** [comment]
Is there anything you do at you app startup? It must be something in your project as it doesn't happen with a new .NET MAUI app. What do you mean by random? It doesn't happen every time? Or only after a while? have you tried commenting out some of your code or revert back to an older .NET MAUI version? There must've been some change that triggered this behavior to show up. 

It would be super helpful to narrow it down. As we don't have your code nor experience with this it will be like looking in a crystal ball and guess what might be going on here which is going to cost a lot of time and probably frustration and typically those issues don't get resolved. The more investigation you can do and the details you can provide, the more helpful we can be.

@jonathanpeppers does this mean anything to you by any chance?

Thanks!

**Comment by jonathanpeppers** [comment]
For troubleshooting problems like this, you should look for similar errors in the Java/Kotlin work, for example:
* https://stackoverflow.com/questions/72390747/crash-activity-client-record-must-not-be-null-to-execute-transaction-item-only

They are saying it is a bug in Android 12, so perhaps there is some service release to that version that fixes it?

If you can reproduce it yourself, you might try skipping MAUI's splash screen on Android 12.

**Comment by jonathanpeppers** [comment]
I think this is an Android bug (Google's bug), as noted here:

* https://issuetracker.google.com/issues/210886009

So, you might be best to follow up there with more info.

Someone was still reporting this happening in Feb 2024, even though it was closed. Are you seeing this on Android 12 devices only?

**Comment by jfversluis** [comment]
The linked issue even shows reports in June and August now and also on Android 14. I think its safe to say that this is an Android bug unfortunately.

**Comment by mattleibow** [comment]
Google has marked the issue as fixed, so I guess all we can do is update the OS or download the latest emulators.
