### ISSUE TITLE
Blazor + Web App template produces version mismatch warning

### ISSUE THREAD

**Issue by BretJohnson** [dotnet/maui#23946]
### Description

When creating a .NET MAUI Blazor Hybrid and Web App (in .NET 9 P6), get a version mismatch warning for Microsoft.AspNetCore.Components.Web.

### Steps to Reproduce

1. Install .NET9 P6 (latest preview)
2. In VS Windows do File / New Project / .NET MAUI Blazor Hybrid and Web App
3. Build the Shared project and look at the Build output (or the warning icon in solution explorer which shows the same message)

Result:
This message appears:
`1>Q:\test\MauiApp4\MauiApp4\MauiApp4.Shared\MauiApp4.Shared.csproj : warning NU1603: MauiApp4.Shared depends on Microsoft.AspNetCore.Components.Web (>= 9.0.0-preview.6.24324.2) but Microsoft.AspNetCore.Components.Web 9.0.0-preview.6.24324.2 was not found. An approximate best match of Microsoft.AspNetCore.Components.Web 9.0.0-preview.6.24328.4 was resolved.`

Things work otherwise. But we should ideally fix so that it doesn't happen in subsequent previews / GA.

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 6.0(9.0.0-preview.6.24327.7). Can repro this warning NU1603.

**Comment by Eilon** [comment]
Thanks, this was an issue with how the final preview build was generated. It's harmless to ignore the warning.
