### ISSUE TITLE
[Bug]  maui-check is ok,but can not create maui project

### ISSUE THREAD

**Issue by athinboy** [dotnet/maui#2394]
1、maui-check is ok:
      _   _   _____   _____     __  __      _      _   _   ___
     | \ | | | ____| |_   _|   |  \/  |    / \    | | | | |_ _|
     |  \| | |  _|     | |     | |\/| |   / _ \   | | | |  | |
  _  | |\  | | |___    | |     | |  | |  / ___ \  | |_| |  | |
 (_) |_| \_| |_____|   |_|     |_|  |_| /_/   \_\  \___/  |___|

¤ .NET MAUI Check v0.8.4.0 ¤
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
This tool will attempt to evaluate your .NET MAUI development environment.
If problems are detected, this tool may offer the option to try and fix them for you, or suggest a way to fix them
yourself.

Thanks for choosing .NET MAUI!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
? Synchronizing configuration... ok
? Scheduling appointments... ok

? OpenJDK 11.0 Checkup...
  – 11.0.10 (C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot\bin\..)
  – 1.8.0-25 (C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25)
  – 11.0.10 (C:\Program Files\Common Files\Oracle\Java)

? Visual Studio 17.0.0-pre.3.0 Checkup...
  – 17.0.0-pre.3.1 - d:\Program Files\Microsoft Visual Studio\2022\Preview
  – 16.11.1

? Android SDK Checkup...
  – emulator (30.8.4)
  – build-tools;30.0.2 (30.0.2)
  – platforms;android-30 (3)
  – system-images;android-30;google_apis;x86 (10)
  – platform-tools (31.0.3)
  – cmdline-tools;3.0 (3.0)

? Android Emulator Checkup...
  – Emulator: pixel_2_pie_9_0_-_api_28 found.

? .NET SDK Checkup...
  – 3.1.412 - C:\Program Files\dotnet\sdk\3.1.412
  – 5.0.303 - C:\Program Files\dotnet\sdk\5.0.303
  – 5.0.400 - C:\Program Files\dotnet\sdk\5.0.400
  – 6.0.100-preview.7.21379.14 - C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14

? .NET SDK - Workload Deduplication Checkup...

? Edge WebView2 Checkup...
  – Found Edge WebView2 version 93.0.961.38

? .NET SDK - Workloads (6.0.100-preview.7.21379.14) Checkup...
  – android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 30.0.100-preview.7.110) installed.
  – ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-preview.7.230) installed.
  – maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-preview.7.230) installed.
  – tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-preview.7.230) installed.
  – macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-preview.7.230) installed.
  – maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-preview.7.1345) installed.
  – wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-preview.7.21377.19) installed.
  – microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-preview.7.21377.2)
installed.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

– Congratulations, everything looks great!

Press enter to exit...

2、can not create maui project

dotnet new maui -n HelloMauiPreview
找不到匹配的模板: 'maui'。

若要列出已安装的模板，请运行:
   dotnet new --list
要在 NuGet.org 上搜索模板，请运行:
   dotnet new maui --search

Microsoft Visual Studio Community 2022 Preview
版本 17.0.0 Preview 3.1
VisualStudio.17.Preview/17.0.0-pre.3.1+31612.314
Microsoft .NET Framework
版本 4.8.04084

已安装的版本: Community

Visual C++ 2022   00476-70000-00000-AA417
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.0.414.6609
ASP.NET and Web Tools 2019

Azure Functions and Web Jobs Tools   17.0.414.6609
Azure Functions and Web Jobs Tools

Azure 应用服务工具 3.0.0 版   17.0.414.6609
Azure 应用服务工具 3.0.0 版

C# 工具   4.0.0-3.21403.23+d51d1a7338e32d3a3cd1e5452665964ee8ec15df
IDE 中使用的 C# 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Linux 核心转储调试   1.0.9.31606
启用 Linux 核心转储的调试。

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ 向导   1.0
Microsoft Visual C++ 向导

Microsoft Visual Studio VC 软件包   1.0
Microsoft Visual Studio VC 软件包

Mono Debugging for Visual Studio   17.0.6 (1ebf2f7)
Support for debugging Mono processes with Visual Studio.

NuGet 包管理器   6.0.0
Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2138002+9e71a625d64fa38b323fa6ac52154e6b1bde703d
提供 ASP.NET Core Razor 的语言服务。

SQL Server Data Tools   17.0.62108.04180
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.0730.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic 工具   4.0.0-3.21403.23+d51d1a7338e32d3a3cd1e5452665964ee8ec15df
IDE 中使用的 Visual Basic 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。

Visual C++ for Linux Development   1.0.9.31606
Visual C++ for Linux Development

Visual F# Tools   17.0.0-beta.21370.1+9b96c1bde17e9af532ae34eacbfc12d1628183d7
Microsoft Visual F# Tools

Visual Studio Code 调试适配器主机包   1.0
用于在 Visual Studio 中托管 Visual Studio Code 调试适配器的互操作层

Visual Studio IntelliCode   2.2
Visual Studio 的 AI 协助开发。

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio 容器工具扩展   1.0
查看、管理和诊断 Visual Studio 中的容器。

VisualStudio.DeviceLog   1.0
有关我的包的信息

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.145 (main@bdc8369)
用于启用 Xamarin.iOS 和 Xamarin.Android 的开发的 Visual Studio 扩展。

Xamarin Designer   17.0.0.58 (remotes/origin/d17-0@927d548a1)
用于在 Visual Studio 中启用 Xamarin Designer 工具的 Visual Studio 扩展。

Xamarin Templates   17.0.3 (a84fb28)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.4.99.70 (main/7e1558c)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@4fb7c14
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@623332d

Xamarin.iOS and Xamarin.Mac SDK   14.99.0.294 (13b1b3c45)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

适用于 Google Test 的测试适配器   1.0
启用带有针对 Google Test 编写的单元测试的 Visual Studio 测试工具。扩展安装目录中提供了使用条款和第三方通知。

适用于跨平台移动开发的 Visual C++ (Android)   17.0.31606.05
适用于跨平台移动开发的 Visual C++ (Android)

用于 Boost.Test 的测试适配器   1.0
通过针对 Boost.Test 编写的单元测试启用 Visual Studio 测试工具。扩展安装目录中提供用户条款和第三方通知。

用于容器的 Microsoft Visual Studio Tools   1.2
在目标环境中开发、运行、验证 ASP.NET Core 应用程序。按 F5，应用程序经调试后直接进入容器，或者按 Ctrl+F5 可编辑和刷新应用，无需重新生成容器。

**Comment by Barshan-Mandal** [comment]
maui-check --force-dotnet

use this command

**Comment by athinboy** [comment]
@Barshan-Mandal  thanks!
