### ISSUE TITLE
widgets

### ISSUE THREAD

**Issue by JosefPRajmon** [dotnet/maui#23953]
### Description

can you create widget documentacion? im trying create widget with listview but after 7 hour a didnt information for widgets in maui

### Public API Changes

i didnt have it

### Intended Use-Case

i didnt have it

**Comment by jfversluis** [comment]
Widgets are not directly supported from .NET MAUI, you can however build a widget (or other extensions) with the native tooling and release those together with your .NET MAUI app.

Unfortunately, we don't have much content on this right now. For docs specific requests, please use [this repository](https://github.com/dotnet/docs-maui/issues/new?assignees=&labels=&projects=&template=doc-request.md&title=).
