### ISSUE TITLE
iOS PostNotifications permission check is always granted

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/maui#23962]
### Description

Have this code that checks the PostNotifications permission status -
```csharp
public async Task<bool> HasPushNotificationPermission()
{
	PermissionStatus status = await Permissions.CheckStatusAsync<Permissions.PostNotifications>();
	return status == PermissionStatus.Granted;
}
```

The status is always `Granted`, even on a fresh install of the app, with 'Allow notifications' set to false

_Android works as expected_

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

```csharp
public async Task<bool> HasPushNotificationPermission()
{
#if IOS

	TaskCompletionSource<bool> tcs = new();

	UNUserNotificationCenter.Current.GetNotificationSettings((settings) =>
	{
		switch(settings.AuthorizationStatus)
		{
			case UNAuthorizationStatus.Authorized:
				tcs.SetResult(true);
				break;

			case UNAuthorizationStatus.Denied:
			case UNAuthorizationStatus.NotDetermined:
			default:
				tcs.SetResult(false);
				break;
		}
	});

	return await tcs.Task;

#else

	PermissionStatus status = await Permissions.CheckStatusAsync<Permissions.PostNotifications>();
	return status == PermissionStatus.Granted;

#endif
}
```

**Comment by themronion** [comment]
@IeuanWalker hello there, this is an android 13+ specific permission. AFAIK, it wasn't intended to work with iOS. U can close this one

**Comment by IeuanWalker** [comment]
@themronion thanks, is there not a way to check iOS permission? _(other than my work around)_

**Comment by jfversluis** [comment]
This is indeed an Android specific permission and as mentioned in [the docs](https://learn.microsoft.com/dotnet/maui/platform-integration/appmodel/permissions?view=net-maui-8.0&tabs=macios#available-permissions):

> If a permission is marked as ❌, it will always return [Granted](https://learn.microsoft.com/dotnet/api/microsoft.maui.applicationmodel.permissionstatus#microsoft-maui-applicationmodel-permissionstatus-granted) when checked or requested.

As far as I know there is no way to check this for iOS, at least this is not implemented in our Permissions APIs at this time.

@davidbritch seems like the above doc needs to be updated with this PostNotifications permission

**Comment by IeuanWalker** [comment]
thanks @jfversluis, my workaround shows a way to handle it on iOS

**Comment by jfversluis** [comment]
Oh sorry, I totally read over that one, thanks! You could wrap that in the Permissions API like so: https://learn.microsoft.com/dotnet/maui/platform-integration/appmodel/permissions?view=net-maui-8.0&tabs=android#extending-permissions

If you're up for it, this could be a great contribution to .NET MAUI to add it to our codebase!

**Comment by IeuanWalker** [comment]
@jfversluis Thanks, ye will take a look :)

**Comment by IeuanWalker** [comment]
@jfversluis I've done the code around it - https://github.com/IeuanWalker/maui-ios-notification-permission/commit/518b90cb55e052cf7f455b263a285b38d864d83f

But struggling to test it, VS keeps not responding/ crashing :/

**Comment by jfversluis** [comment]
@IeuanWalker find my email on my GitHub profile to reach out so we can more easily figure it out
