### ISSUE TITLE
[Bug] Can not create a new content page

### ISSUE THREAD

**Issue by mans0987** [dotnet/maui#2396]
### Description
Created a new empty content page using VS 2022 and tried to compile it but there are several errors.
### Steps to Reproduce

1. Create a new MAUI project in VS 2022
2. Compile and run it for an android device (the project should be compiled and shows on the emulator)
3.  Add a content page to the project
4. Try to compile and run the application again. The application is not compiled with several errors (mostly related to Xamarin form, when it is not a xamarin form)

### Expected Behavior
The application should be compiled and runs on the emulator
### Actual Behavior
There are several compile errors.
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual studio 2022
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

I could not find any workaround. there is no way to add new page to the solution.

**Comment by sambhavyadav90** [comment]
Change namespace of newly content page and compile it

**Comment by mans0987** [comment]
Thanks,
Changed the code for new page to this one:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Microsoft.Maui.Controls.Xaml;
using Microsoft.Maui;
using Microsoft.Maui.Controls;

namespace MauiApp2
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Page1 : ContentPage
    {
        public Page1()
        {
            InitializeComponent();
        }
    }
}
```
and 

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.Page1">
    <ContentPage.Content>
        <StackLayout>
            <Label Text="Welcome to Xamarin.Forms!"
                VerticalOptions="CenterAndExpand" 
                HorizontalOptions="CenterAndExpand" />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```
but I am still getting this error:

```
C:\Users\mans0\source\repos\MauiApp2\MauiApp2\MauiApp2\Page1.xaml.cs(18,13,18,32): error CS0103: The name 'InitializeComponent' does not exist in the current context
```

How can I fix this error?

**Comment by sambhavyadav90** [comment]
After changing namespace to MAUI, 
Please updated the Build Action
- [ ] RightClick on Xaml Page
- [ ] Properties>>BuildAction
- [ ] Change XAML Page to MauiXaml

**Comment by mans0987** [comment]
That solved the problem. Thanks
