### ISSUE TITLE
XamlC error : The given key 'Microsoft.Maui.Controls.Xaml.ElementNode' was not present in the dictionary.

### ISSUE THREAD

**Issue by davishoang96** [dotnet/maui#23970]
### Description

Hi, I'm trying to test my app with .NET 9 preview. I couldn't build the app and got this error message when using OnIdiom and OnPlatform together on one line in the XAML pages.

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp007.MainPage">

    <ScrollView>
        <VerticalStackLayout Padding="30,0"
                             Spacing="{OnPlatform iOS={OnIdiom Default=35, Phone=25}, WinUI=25, Android={OnIdiom Default=45, Phone=25}}">

         // Some other things

        </VerticalStackLayout>
    </ScrollView>

</ContentPage>

Example app: [MauiApp007.zip](https://github.com/user-attachments/files/16466567/MauiApp007.zip)

### Steps to Reproduce

1. Create a new MAUI net 9 preview project
2. Try to add {OnPlatform iOS={OnIdiom Default=35, Phone=25}, WinUI=25, Android={OnIdiom Default=45, Phone=25}}

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.61 SR6.1

### Affected platforms

iOS, Android

### Relevant log output

```shell
C:\Users\JohnDoe\source\repos\MauiApp007\MauiApp007\MainPage.xaml : XamlC error : The given key 'Microsoft.Maui.Controls.Xaml.ElementNode' was not present in the dictionary.
  MauiApp007 net9.0-ios failed with 1 error(s) and 9 warning(s) (3.3s)
```

**Comment by ninachen03** [comment]
I can repro this issue on maui control: 9.0.0-preview.7.24401.3 but not repro in 8.0.71.
