### ISSUE TITLE
MSBuild <Include /> (global using directive) does not work for platform-specific namespaces

### ISSUE THREAD

**Issue by datvm** [dotnet/maui#23986]
### Description

Instructions like `<Using Include="Android.App" />` does not work. The instruction simply disappears in their respective platform.

### Steps to Reproduce

1. Create a new MAUI project.
2. Add this code to the `.csproj` file:

```xml
	<ItemGroup>
		<Using Include="SomethingCrazy" />
		<Using Include="Android.App" />
	</ItemGroup>
```
3. Set target framework to android only for now: `<TargetFrameworks>net8.0-android</TargetFrameworks>`.
4. In any code file like `MauiProgram.cs`, try declaring `Activity activity;`. The compiler fails to understand `Activity` is from `Android.App`. Try to compile anyway.
5. Open the generated `obj\Debug\net8.0-android\MauiApp1.GlobalUsings.g.cs`: `global using global::SomethingCrazy;` is there but no `Android.App` there.
6. Switch the target framework to ios and try to compile. Now the generated `\obj\Debug\net8.0-ios\iossimulator-x64\MauiApp1.GlobalUsings.g.cs` contains `Android.App`. However if we use `<Using Include="UIKit" />`, it is not printed now.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Did you find any workaround?

Use C# `global using` instead. However this is not reusable like MSBuild's `.targets`.

**Comment by kevinxufei** [comment]
I can repro this issue on the latest 17.12.0 Preview 1.0(8.0.80 & 8.0.3)

**Comment by mattleibow** [comment]
I am pretty sure it has to do with this: https://github.com/dotnet/maui/blob/bd7aeadbbe3670e74ef0753aeb82bab4cd5459f3/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.Build.Tasks.After.targets#L11-L13

I think if you want platform usings you would have to set `<MauiEnablePlatformUsings>true</MauiEnablePlatformUsings>` so that we don't remove it.
