### ISSUE TITLE
MAUI NET8.0 Android HTTPClient isn't working as intend, SendAsync() and GetAsync() send nothing. But works well on Windows

### ISSUE THREAD

**Issue by warrenZY** [dotnet/maui#23993]
### Description

I tried to kinds of writing but non of them work, while connecting to my ZTE device and debug.

![image](https://github.com/user-attachments/assets/fe589397-5972-425a-b2b0-8dbe129d8b71)
![image](https://github.com/user-attachments/assets/8e4ee931-36e7-4b57-b192-0f1143458a11)

I need to send Get with customized cookie.

I tried:

        if (DeviceInfo.Current.Platform == DevicePlatform.Android)
        {
#if __ANDROID__
            //HttpClientHandler handler = new HttpClientHandler();
            var Msghandler = new Xamarin.Android.Net.AndroidMessageHandler() { UseCookies = false };
            httpClient = new HttpClient(new Xamarin.Android.Net.AndroidMessageHandler());
            
#endif
        }
        else
        {
            var httpClientHandler = new HttpClientHandler() { UseCookies = false };
            httpClient = new HttpClient(httpClientHandler);
            
        }
        //var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, uri);

var httpClientHandler = new HttpClientHandler() { UseCookies=false };
//httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
//httpClientHandler.AllowAutoRedirect = false;
//var httpClient= new HttpClient(httpClientHandler);
if (DeviceInfo.Current.Platform == DevicePlatform.Android)
{
    var httpClient = new HttpClient(new Xamarin.Android.Net.AndroidMessageHandler());
}
else {
    var httpClient = new HttpClient(httpClientHandler);
}
       
var httpRequestMessage =new HttpRequestMessage(HttpMethod.Get, uri);
httpRequestMessage.Headers.Add("Cookie", $"mobile_enterprise={mobileNumber}");
var ret= await httpClient.SendAsync(httpRequestMessage);
ret.EnsureSuccessStatusCode();
return await ret.Content.ReadAsStringAsync();

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Relevant log output

```shell
Non Error log output in this situation
```

**Comment by XiaoZeYu** [comment]
The code just work right well in windows as image shows, it correctly sends the GET and get Response from server.
but just sending noting well running on Android 
![image](https://github.com/user-attachments/assets/b606b2d7-b59a-4831-b8ea-f98cf5b0f4e8)
In Android, when I press the send button, nothing happend. Debug shows that it just jumping back forth between Line 33,41,46 and never runs to Line 47
![image](https://github.com/user-attachments/assets/ef0c642d-eb0b-4288-b4a4-267090fac013)

**Comment by XiaoZeYu** [comment]
![image](https://github.com/user-attachments/assets/57df0263-69fd-4d90-9c59-2c36f6251d9b)
This is what i captured from the network  traffic(I open a hotspot and connect my phone through it), unlike the windows  its just show nothing. The only request show that's come from my web browser well testing connectivity and ensure there's nternet Access.

**Comment by warrenZY** [comment]
I thought I find the real reason, Android system restricted clear text traffic causing this http Get Request cannot being Send.
![image](https://github.com/user-attachments/assets/70411b00-1062-41e1-a95d-09505e04b084)
Fix it by adding android:usesCleartextTraffic="true" at manifest

**Comment by jonmdev** [comment]
> I thought I find the real reason, Android system restricted clear text traffic causing this http Get Request cannot being Send. ![image](https://private-user-images.githubusercontent.com/22209669/354806645-70411b00-1062-41e1-a95d-09505e04b084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDIzNTksIm5iZiI6MTcyMjcwMjA1OSwicGF0aCI6Ii8yMjIwOTY2OS8zNTQ4MDY2NDUtNzA0MTFiMDAtMTA2Mi00MWUxLWE5NWQtMDk1MDVlMDRiMDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE2MjA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OTk5ZjAwZWFhMzk5OGYzMDZiMWI3OWE5MDUwMzRkYmQ2YjdkZDgyMGFiMDMyN2EyNTA5YjVkYzAxZTQyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xk86s0rNB58x75h2I7XuCx5AGIaJeMWFJLDBsiNcygM) Fix it by adding android:usesCleartextTraffic="true" at manifest

Android intends you to only use https. If you try http ur you get this problem. Change to https and it works.

**Comment by warrenZY** [comment]
> Android intends you to only use https. If you try http url you get this problem. Change to https and it works.

That's right, but I did own that server. And the server only supports Http, instead of Https. What  a mess,
 I'm not sure if there's any way else can solve this problem, Hope there would be an easier way to One Click Config. LOL!

**Comment by sviluppomania** [comment]
Hi,
currently from Xamarin to .NET 8 MAUI these NuGet assemblies/packages are not compatible, what are the solutions?
Xamarin.Android.Google.BillingClient
Xamarin.GooglePlayServices.Ads
Xamarin.GooglePlayServices.Location
Xamarin.Google.UserMessagingPlatform
Xamarin.AndroidX.Browser
Xamarin.AndroidX.Core
Xamarin.AndroidX.Lifecycle.LiveData
Xamarin.AndroidX.MediaRouter
Xamarin.AndroidX.Palette
Xamarin.AndroidX.RecyclerView
Xamarin.GooglePlayServices.SafetyNet
AdsJumbo
SkiaSharp.Views.Forms
Xamarin.Android.Support.Collections
Xamarin.Android.Support.CustomTabs
Xamarin.Android.Support.Interpolator
Xamarin.Essentials
Xamarin.Forms
Xamarin.Android.Support.Design
Xamarin.Android.Support.v7.AppCompat
Xamarin.Android.Support.v4
Xamarin.Android.Support.v7.CardView
Xamarin.Android.Support.v7.MediaRouter
Xamarin.Essentials
Xamarin.Forms
Microsoft.NETCore.UniversalWindowsPlatform
Thanks so much to anyone who will help! 🙂

**Comment by jfversluis** [comment]
@sviluppomania please do not randomly ask questions in other issues. 

@warrenZY unfortunately there is no other way. Both Android and iOS enforce using https unless you opt-out of it with what you just did. This is not a .NET MAUI thing, but rather something on the platform. Glad you figured it out!
