### ISSUE TITLE
[Bug] Could not resolve type with token 01000008 from typeref (expected class 'System.Drawing.BitmapSuffixInSatelliteAssemblyAttribute' in assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')'

### ISSUE THREAD

**Issue by qcjxberin** [dotnet/maui#2399]
System.TypeLoadException: 'Could not resolve type with token 01000008 from typeref (expected class 'System.Drawing.BitmapSuffixInSatelliteAssemblyAttribute' in assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')'

**Comment by Askar938** [comment]
You might want to try to update the nuget package `System.Drawing.Common`
https://www.nuget.org/packages/System.Drawing.Common/

If that doesn't solve your problem, try to delete `bin`, `debug `and `.vs` folders and do a rebuild.

**Comment by PaulAnderson02** [comment]
Try disabling the hot reload for maui. The error will get resolved

**Comment by zeus2nawaz** [comment]
Delete **bin** and **obj** folder, it will work or restart visual studio 

Hope it helps

**Comment by jfversluis** [comment]
Deleting obj/bin folders seems to be the trick for this one, thanks all!
