### ISSUE TITLE
[Bug] - Which devices supports MAUI

### ISSUE THREAD

**Issue by zeus2nawaz** [dotnet/maui#2400]
I want to know in Android, which version it supports, Can it supports 2016+ devices ? 
I want to know in IOS, which version it supports

I had seen https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms, where it says it support Android 5

So is it support with Android 5 target OS Version 31 or do we need to set minimum OS Version ?

In properties there is no items to select minimum OS requirement.
![image](https://user-images.githubusercontent.com/53426219/132205339-0ac65ede-9728-44c4-9500-b01eddfcf5cf.png)

**Comment by vhugogarcia** [comment]
You can in the meantime edit the manifest.xml and set a minimum version 😎.

**Comment by juansturla** [comment]
The project properties are not very clear right now. But you can still use the AndroidManifest.xml as always
![image](https://user-images.githubusercontent.com/10248860/132252303-2d807a0a-d57b-4891-a8ff-4bc8b7bd26be.png)

If you want the min version to be Android 5, then you have to set ` android:minSdkVersion="21"`

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="30" />
	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round" android:supportsRtl="true"></application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`

**Comment by zeus2nawaz** [comment]
@juansturla , @vhugogarcia 
Thank you very much for answering this, I am closing this issue
