### ISSUE TITLE
CollectionView has inconsistent behavior if GroupHeaderTemplate not specified

### ISSUE THREAD

**Issue by BretJohnson** [dotnet/maui#24007]
### Description

When a CollectionView uses grouping, and the GroupHeaderTemplate isn't specified (as it's not required, per the docs), the resulting behavior is inconsistent on different platforms:
- Android: There's no header (no space for it)
- iOS: There's a header, with the Name text
- Windows: There's space for the header, but it's blank

### Steps to Reproduce

1. Clone the https://github.com/dotnet/maui-samples repo
2. Open the `CollectionViewDemo.sln` (under `8.0/UserInterface/Views/CollectionViewDemos`)
3. Open `VerticalListGroupingPage.xaml` and remove the GroupHeaderTemplate and GroupFooterTemplate 
4. Run the app on different platforms
5. Navigate to "Vertical list with DataTemplates" choice in the UI

Results:
- On iOS, the group header shows, with the Name present
- On Android, nothing shows for the header
- On Windows, there's space for the header but it's blank

This problem seems consistent in .NET8 and .NET9 P6.

I'm not sure what the right/intended behavior is, but at least the doc here https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/grouping?view=net-maui-8.0 should be updated to note what happens if GroupHeaderTemplate isn't specified. The doc currently implies it's optional. If the recommendation is to always specify a GroupHeaderTemplate, then the doc should say that.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples repo

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Did you find any workaround?

The workaround seems to be to always specify a GroupHeaderTemplate, so you can control what it shows.

**Comment by RoiChen001** [comment]
According to your steps, as shown in the picture, I didn't reproduce the problem you mentioned on the latest 17.11.0 Preview 7.0(8.0.71 & 9.0.0-preview.6.24327.7). If you have any questions, please feel free to contact me.
![image](https://github.com/user-attachments/assets/76d7d81a-9661-418d-ae11-6ee8ba5154b6)
