### ISSUE TITLE
MauiUIApplicationDelegate could not be found

### ISSUE THREAD

**Issue by myCollections** [dotnet/maui#24009]
### Description

Hello, i just update to 9.0.0-preview.6.24327.7, and i get this error  in my ios project:

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0246	The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?)	myLittleResto.iOS	C:\Users\jean_\source\repos\myLittleResto\myLittleResto.iOS\AppDelegate.cs	6	

the code is :

[Register(nameof(AppDelegate))]
public class AppDelegate : MauiUIApplicationDelegate

Any clue for this ?

Thanks for your help

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

iOS

**Comment by jfversluis** [comment]
I think this usually happens when packages don't restore successfully. If you go into your projects Dependencies node. Does it show any warning signs there? If you run `dotnet restore` does that work? Is there any other helpful log output?

**Comment by myCollections** [comment]
Hello Gerald,

I try dotnert restore after installation of .net 9 without sucess.
So i downgrade to .net 8, remove .net 9, make a dotnet restore and same issue on ios project :

```
----- Build started: Project: myLittleResto.iOS, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\8.0.400-preview.0.24324.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>C:\Users\jean_\Source\Repos\myLittleResto\myLittleResto.iOS\AppDelegate.cs(1,7,1,17): error CS0246: The type or namespace name 'Foundation' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\jean_\Source\Repos\myLittleResto\myLittleResto.iOS\Main.cs(1,7,1,18): error CS0246: The type or namespace name 'ObjCRuntime' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\jean_\Source\Repos\myLittleResto\myLittleResto.iOS\Main.cs(2,7,2,12): error CS0246: The type or namespace name 'UIKit' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\jean_\Source\Repos\myLittleResto\myLittleResto.iOS\AppDelegate.cs(6,28,6,53): error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\jean_\Source\Repos\myLittleResto\myLittleResto.iOS\AppDelegate.cs(5,2,5,10): error CS0246: The type or namespace name 'RegisterAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\jean_\Source\Repos\myLittleResto\myLittleResto.iOS\AppDelegate.cs(5,2,5,10): error CS0246: The type or namespace name 'Register' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "myLittleResto.iOS.csproj" -- FAILED.
```

**Comment by RoiChen001** [comment]
@myCollections You need to install the .NET 9 SDK and the corresponding .NET 9 MAUI Workload on your machine.
[Download .NET 9.0 (Linux, macOS, and Windows) (microsoft.com)](https://dotnet.microsoft.com/en-us/download/dotnet/9.0).
If you don't have any other questions, we will close this issue.

**Comment by myCollections** [comment]
Hello,

I install latest sdk and load correct workload but still the same issue. But i restart a new project, copy/past everything from old project and it works fine. 

Thanks a lot for your help.

Maui really rocks.
