### ISSUE TITLE
ios test flight crash

### ISSUE THREAD

**Issue by sergey-malue** [dotnet/maui#24011]
### Description

We're developing maui app, looks like it stoped working after latest ios updates.

Test flight app crashes right after launch don't even show start screen. (It works on ios 17.5 simulator)

For building and publishing we are using azure pipelines (mac-os 14, xcode 15.3/15.4)

Old build(with old pipeline) which defenetly was working previously, now does not work too, I attached logs i can grab from iphone, could you please advice for workaround? (if there is no enough logs could you advice a tool we should use get more)

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.21 SR4.1

### Affected platforms

iOS

### Affected platform versions

ios 17.5.1

### Relevant log output

```shell
https://gist.github.com/sergey-malue/392c2a209f1921be15f3b5e2e5e86878
```

**Comment by jfversluis** [comment]
Looks like you're on an older version: 8.0.21 SR4.1, could you try updating and see if that resolves it?

Also I'm not 100% clear on what is working and what is not. Could you maybe add a clearer description of the version numbers where you don't see it working versus where you did see it working? Has there been an update to Xcode? .NET version?

It seems like you're using hosted build agents to updates might happen at any time. I think it would be helpful to learn what versions were used for the last working version and what version is used now or any other changes between those two versions.

Without that and just this stack trace it will be very hard to trace back what might be going on here.

**Comment by sergey-malue** [comment]
@jfversluis i updated maui version to 8.0.61, .net toolkit 8.0.303, still facing the same issue.

app works in ios simulator (mac os 14, xcode 15.4, VS 17.10.5)
app crashes in testflight (build with mac os 14, xcode 15.4)

our azure pipeline looks following way:

- stage: BuildiOS
  condition: and(succeededOrFailed(), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: BuildAndTest
  jobs:
  - job: BuildiOS
    timeoutInMinutes: 90
    displayName: Build IOS
    pool:
      vmImage: 'macOS-14'
      demands:
      - MSBuild
      
    steps:

    - task: PowerShell@2
      displayName: "Display Build Number"
      inputs:
        targetType: 'inline'
        script: |
              Write-Host "App Version: $(Version)"

    - task: Bash@3
      displayName: XCode Version
      inputs:
        targetType: 'inline'
        script: |
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          xcodebuild -version
          
    - task: Bash@3
      displayName: XCode SDKs
      inputs:
        targetType: 'inline'
        script: |
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          xcodebuild -showsdks

    # https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build#sign-your-apple-ios-macos-tvos-or-watchos-app
    # Setup Secret Pipeline Variable or Library Secrets Variable for iOS Certificate Password
    - task: InstallAppleCertificate@2
      displayName: 'Install an Apple certificate'
      inputs:
        certSecureFile: 'Apple.DistributionCertificate.p12'
        certPwd: '$(AppleCertificate.Password)'
        setUpPartitionIdACLForPrivateKey: false

    - task: InstallAppleProvisioningProfile@1
      displayName: 'Install an Apple provisioning profile'
      name: ProvisioningProfile
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'Apple.AppStoreDistributionDEV.mobileprovision'
      
    - task: Bash@3
      displayName: List folder contents
      inputs:
        targetType: 'inline'
        script: |
          ls -R /Users/runner/work

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(TOOLKIT_VERSION)'
      inputs:
        packageType: 'sdk'
        version: $(TOOLKIT_VERSION)
        includePreviewVersions: false
    
    - task: Bash@3
      displayName: Install MAUI workloads
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear 
          dotnet workload install maui ios
		  
	- task: Bash@3
      displayName: 'Show Installed MAUI Version'
      inputs:
        targetType: 'inline'
        script: |
          dotnet workload list | grep maui
    
    - task: PowerShell@2
      displayName: "Update Version Numbers"
      inputs:
        targetType: 'inline'
        script: |
          $xml = [Xml] (Get-Content .\src\App.UI.MAUI\App.UI.MAUI.csproj)
          $ns = New-Object Xml.XmlNamespaceManager($xml.NameTable)
          $ns.AddNamespace("p", $xml.Project.NamespaceURI)
          $applicationDisplayVersionNode = $xml.SelectSingleNode("//p:PropertyGroup/p:ApplicationDisplayVersion", $ns)
          $applicationVersionNode = $xml.SelectSingleNode("//p:PropertyGroup/p:ApplicationVersion", $ns)
          $applicationDisplayVersionNode.InnerText = $env:BaseVersion
          $applicationVersionNode.InnerText = $env:BuildVersion
          $xml.Save(".\src\App.UI.MAUI\App.UI.MAUI.csproj")
    
    - task: Bash@3
      displayName: 'Update CFBundleVersion'
      inputs:
        targetType: 'inline'
        script: |
          plutil -replace CFBundleShortVersionString -string $(BaseVersion) Info.plist
          plutil -replace CFBundleVersion -string $(Version) Info.plist
        workingDirectory: 'src/App.UI.MAUI/Platforms/iOS'
    
    - task: Bash@3
      displayName: NuGet restore
      inputs:
        targetType: 'inline'
        script: |
          cd $(System.DefaultWorkingDirectory)/src
          dotnet restore App.sln

  # https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview
    - task: Bash@3
      displayName: Build IOS Package
      inputs:
        targetType: 'inline'
#       script: |
#          cd $(System.DefaultWorkingDirectory)/src
#          dotnet publish $(System.DefaultWorkingDirectory)/src/App.UI.MAUI/App.UI.MAUI.csproj -f net8.0-ios -c Release /p:CodesignKey="$(Apple.CodesignKey.Release)" /p:CodesignProvision=$(Apple.CodesignProvision.Release) /p:ServerAddress={IP} /p:ServerUser=admin /p:ServerPassword=$(MacInCloud.Password) /p:TcpPort={Port}/p:_DotNetRootRemoteDirectory=/Users/admin/Library/Caches/Xamarin/XMA/SDKs/dotnet/
        script: |
          cd $(System.DefaultWorkingDirectory)/src
          dotnet publish $(System.DefaultWorkingDirectory)/src/App.UI.MAUI/App.UI.MAUI.csproj -f net8.0-ios -c Release /p:CodesignKey="$(Apple.CodesignKey.Release)" /p:CodesignProvision=$(ProvisioningProfile.provisioningProfileName)

    - task: CopyFiles@2
      displayName: 'Copy Files to Staging - app-ios'
      inputs:
        Contents: |
          **/*.app
          **/*.ipa
        TargetFolder: '$(Build.ArtifactStagingDirectory)/app-ios'
        CleanTargetFolder: true
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/app-ios'
        ArtifactName: 'drop_ios'
        publishLocation: 'Container'

appretiate in advance for any advice

**Comment by jfversluis** [comment]
Thank you for the information. I'm still not 100% clear though. Re-reading your initial message you also say

> Old build(with old pipeline) which defenetly was working previously, now does not work too

So an old build that did work now does not work? That is uncommon. How did you verify this? Does it work on other devices? Something must have changed in the meanwhile either on the device where you're trying to run it or in the pipeline or your code.

Its very hard as a third-party to determine what might be going on here without some hardcore debugging.

**Comment by sergey-malue** [comment]
@jfversluis Yes, 
Old build with old pipeline does not work now, but it defenetly was working.
Since that time only ios updated, from 17.4 to 17.5.1.

Anyway probably we found the reason of the issue, looks like it's related with our release pipeline where we override variables in ready build, so moslikely  it our release pipeline or ios but not MAUI issue, I'll let you know when be sure for 100%.

**Comment by jfversluis** [comment]
It almost has to be something like that. This doesn't sound like something that originates with us tbh.

Hope you will figure it out! I'll close this for now, let us know if there is something more we can help with.
