### ISSUE TITLE
Package from Xamarin to .NET 8 MAUI

### ISSUE THREAD

**Issue by sviluppomania** [dotnet/maui#24019]
### Description

Hi,
currently from Xamarin to .NET 8 MAUI these NuGet assemblies/packages are not compatible, what are the solutions?

Xamarin.Android.Google.BillingClient
Xamarin.GooglePlayServices.Ads
Xamarin.GooglePlayServices.Location
Xamarin.Google.UserMessagingPlatform
Xamarin.AndroidX.Browser
Xamarin.AndroidX.Core
Xamarin.AndroidX.Lifecycle.LiveData
Xamarin.AndroidX.MediaRouter
Xamarin.AndroidX.Palette
Xamarin.AndroidX.RecyclerView
Xamarin.GooglePlayServices.SafetyNet

AdsJumbo

SkiaSharp.Views.Forms
Xamarin.Android.Support.Collections
Xamarin.Android.Support.CustomTabs
Xamarin.Android.Support.Interpolator
Xamarin.Essentials
Xamarin.Forms
Xamarin.Android.Support.Design
Xamarin.Android.Support.v7.AppCompat
Xamarin.Android.Support.v4
Xamarin.Android.Support.v7.CardView
Xamarin.Android.Support.v7.MediaRouter
Xamarin.Essentials
Xamarin.Forms
Microsoft.NETCore.UniversalWindowsPlatform

Thanks so much to anyone who will help! 🙂

### (Public) API Changes

.

### Usage Scenarios

.

### Backward Compatibility

.

### Difficulty

Medium

**Comment by davidortinau** [comment]
Nuget.org is your help to determine compatibility. Look at the Frameworks tab for the net6+ dark blue indication it's compatible.

https://www.nuget.org/packages/Xamarin.AndroidX.Core#supportedframeworks-body-tab

You'll find our supported packages for AndroidX as well as community options for GooglePlayService and Firebase.

If you need to do something yourself, this is an option:
- https://github.com/CommunityToolkit/Maui.NativeLibraryInterop
- https://devblogs.microsoft.com/dotnet/native-library-interop-dotnet-maui/

Xamarin.Forms is now .NET MAUI
Xamarin.Essentials is now part of .NET MAUI
UWP is now WinUI3 in WinAppSDK
SkiaSharp.Views.Forms is SkiaSharp.Views.Maui.Controls

Your guide to upgrading: https://learn.microsoft.com/en-us/dotnet/maui/migration/?view=net-maui-8.0
