### ISSUE TITLE
Maui library? 

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#2402]
Why there is no a _Maui Class Library_ project template? Should I create an app an remove the undesired parts?

Is there any documentation about creating Maui controls from scratch?

**Comment by juansturla** [comment]
I think there is no such thing as "MAUI Class library" project
It's just a Class Library, and it targets NET6.
![image](https://user-images.githubusercontent.com/10248860/132252563-901b14e7-ae1b-4e43-9ad8-01321728cfc4.png)

There is not much documentation about MAUI right now. It is still work in progress, you can check that https://github.com/dotnet/docs-maui/issues

**Comment by arivoir** [comment]
A Net6 class library doesn't seem enough for control's libraries, which will need the "Platforms" folder magic to locate the platform-specific code as well as multi-targeting.

**Comment by juansturla** [comment]
In that case yes, you can create a MAUI App and delete the things you don't need
OR
You can create a Library Class, and then modify the .csproj file
Replace `	  <TargetFramework>NET6</TargetFramework>`	 with  `<TargetFrameworks>net6.0-ios;net6.0-android;</TargetFrameworks>` Notice that it uses TargetFrameworkS with an S

**Comment by vhugogarcia** [comment]
Visual Studio RC1 will probably add the missing template 🙂. Which is expected to be released this week or early next one. 

A little more of patient!!

**Comment by Eilon** [comment]
We have additional project templates and item templates coming int he next preview, including a new `.NET MAUI Class Library` project template:

```
C:\GitHub\maui>dotnet new -l
These templates matched your input:

Template Name                                 Short Name           Language    Tags
--------------------------------------------  -------------------  ----------  ---------------------------------------------------
.NET MAUI App                                 maui                 [C#]        MAUI/Android/iOS/macOS/Mac Catalyst/WinUI
.NET MAUI Blazor App                          maui-blazor          [C#]        MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Blazor
.NET MAUI Class Library                       mauilib              [C#]        MAUI/Android/iOS/macOS/Mac Catalyst/WinUI
.NET MAUI ContentPage                         maui-page-xaml       [C#]        MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentPage (C#)                    maui-page-csharp     [C#]        MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentView                         maui-view-xaml       [C#]        MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentView (C#)                    maui-view-csharp     [C#]        MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
```

**Comment by Eilon** [comment]
Here's the PR where it was merged a short while ago: https://github.com/dotnet/maui/pull/1827
