### ISSUE TITLE
Cannot Load JavaScript in WebView in .NET MAUI

### ISSUE THREAD

**Issue by ibrahimahmed1998** [dotnet/maui#24029]
### Description

I am encountering an issue with loading JavaScript in a WebView within a .NET MAUI application. Specifically, the errors observed are related to the JavaScript file and the WebChat component.

   var url = $"https://mywebsite.azurewebsites.net/chatbot.html";

        cookieContainer.Add(new Uri(url), cookie);
        MenuCurve.Cookies = cookieContainer;
        MenuCurve.Source = new UrlWebViewSource { Url = url };

Error Messages:

`[chromium] [INFO:CONSOLE(2)] "Uncaught SyntaxError: Unexpected token .", source: https://mywebsite.azurewebsites.net/js/webchat.js (2)
[chromium] [INFO:CONSOLE(57)] "Uncaught (in promise) ReferenceError: WebChat is not defined", source: https://mywebsite.azurewebsites.net/chatbot.html (57)`

The first error indicates a syntax error in the webchat.js file, specifically an unexpected token. The second error indicates that the WebChat object is not defined, which occurs when trying to load the chatbot.html file.

Note: when I open Index.html alone it works fine

Steps to Reproduce:

Create a new .NET MAUI project.
Add a WebView component to the project.
Set the WebView source to https://redtenantmobilenotification.azurewebsites.net/chatbot.html.
Run the application and observe the console for errors.
Expected Behavior:
The WebView should load the JavaScript files without any syntax errors and properly define all necessary objects, such as WebChat.

Actual Behavior:
JavaScript files fail to load correctly, leading to syntax errors and reference errors in the console.

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.10 SR3

### Affected platforms

Android

### Affected platform versions

pixel_5 api_26:5554

**Comment by jfversluis** [comment]
There must be more to this because it works fine here.

![image](https://github.com/user-attachments/assets/bddfb5d8-fb4a-44de-9c3b-e4fab7829083)

Can you please add a reproduction project?

**Comment by ibrahimahmed1998** [comment]
Hi @jfversluis,
I tried to write your code, but it gives me the same result 
this is repo link 
https://github.com/ibrahimahmed1998/Tenant
the code location is Views -> Main -> ChatbotAgent.xaml && ChatbotAgent.xaml.cs
I appreciate your help

**Comment by jfversluis** [comment]
The repository does not work. You probably set it to private

**Comment by ibrahimahmed1998** [comment]
@jfversluis Please try now

**Comment by jfversluis** [comment]
I stand by my advice, even for a test environment.

In any case, this is not a reproduction. I see a whole lot of code, including JavaScript you might want to include, that might as well show you a valid JavaScript error in the console. Please show a condensed sample of the potential issue you think is in .NET MAUI. Issues are about bugs or features inside of the .NET MAUI SDK. This is not meant for support, unfortunately I cannot go debugging your code.

From what I'm seeing so far, I see no indication that there is a bug with our WebView.

**Comment by jfversluis** [comment]
That is impossible to say with just this information. These URLs don't seem to exist for me so I can't look at them. You mention an index.html file which I do not see in your first message.

Based on the error message there is a `.` symbol in the webchat.js file apparently that is not supposed to be there. I think the error after that is triggered by the first error.

Following your reproduction steps I can see this works, so unless you can provide me with a situation where it doesn't work, which is not your full project that I need to debug, it's very hard to say something useful about it 😄

**Comment by ibrahimahmed1998** [comment]
<!doctype html>
<html lang="en">

<head>
  <title>RED365 CHATBOT2</title>
  <style>
    html,
    body {
      height: 100%;
      margin: 0;
      font-family: Arial, sans-serif;
      /* Better fallback font */
    }

    body {
      margin: 0;
      padding: 0;
    }

    h1 {
      color: whitesmoke;
      font-family: Segoe UI, sans-serif;
      font-size: 1rem;
      /* Scalable font size */
      line-height: 1.5rem;
      margin: 0;
      padding: 0 1rem;
      /* Responsive padding */
    }

    #banner {
      align-items: center;
      background-color: #96433F;
      display: flex;
      height: 3rem;
      /* Responsive height */
      justify-content: center;
      /* Center the content */
    }

    #webchat {
      height: calc(100vh - 3rem);
      /* Adjust the height based on banner height */
      overflow: hidden;
      position: fixed;
      top: 3rem;
      /* Adjust to match banner height */
      width: 100%;
      /* Full width */
    }

    /* Responsive adjustments */
    @media (max-width: 600px) {
      h1 {
        font-size: 0.875rem;
        /* Smaller font size for mobile */
      }

      #banner {
        height: 2.5rem;
        /* Adjust banner height for mobile */
      }

      #webchat {
        top: 2.5rem;
        /* Adjust to match banner height */
      }
    }

    @media (min-width: 601px) and (max-width: 768px) {
      h1 {
        font-size: 1rem;
        /* Adjust font size for tablet */
      }

      #banner {
        height: 3rem;
        /* Adjust banner height for tablets */
      }

      #webchat {
        top: 3rem;
        /* Adjust to match banner height */
      }
    }
  </style>
</head>

<body>
  <div>
    <div id="banner">
      <h1>RED365 CHATBOT2</h1>
    </div>
    <div id="webchat" role="main"></div>
  </div>

  <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>

  <script>

    function getCookie(name) {
      const value = `; ${document.cookie}`;
      const parts = value.split(`; ${name}=`);
      if (parts.length === 2) return parts.pop().split(';').shift();
    }

    (async function () {
      const styleOptions = {
        hideUploadButton: true
      };

      const tokenEndpointURL = new URL('https://99677f854f704c4b9da8d9d1187c76.58.environment.api.powerplatform.com/powervirtualagents/botsbyschema/crf2d_redChatbot/directline/token?api-version=2022-03-01-preview');

      const locale = document.documentElement.lang || 'en';

      const apiVersion = tokenEndpointURL.searchParams.get('api-version');

      const [directLineURL, token] = await Promise.all([
        fetch(new URL(`/powervirtualagents/regionalchannelsettings?api-version=${apiVersion}`, tokenEndpointURL))
          .then(response => {
            if (!response.ok) {
              throw new Error('Failed to retrieve regional channel settings.');
            }
            return response.json();
          })
          .then(({ channelUrlsById: { directline } }) => directline),
        fetch(tokenEndpointURL)
          .then(response => {
            if (!response.ok) {
              throw new Error('Failed to retrieve Direct Line token.');
            }
            return response.json();
          })
          .then(({ token }) => token)
      ]);

      const directLine = WebChat.createDirectLine({ domain: new URL('v3/directline', directLineURL), token });

      var CurrentUser98 = getCookie('CurrentUser98');

      const subscription = directLine.connectionStatus$.subscribe({
        next(value) {
          if (value === 2) {
            directLine
              .postActivity({
                localTimezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
                locale,
                name: 'startConversation',
                type: 'event',
                value: { username: CurrentUser98 }
              })
              .subscribe();

            subscription.unsubscribe();
          }
        }
      });

      WebChat.renderWebChat({ directLine, locale, styleOptions }, document.getElementById('webchat'));
    })();
  </script>
</body>

</html>

**Comment by ibrahimahmed1998** [comment]
i call the last html page 
and the error exists in <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script> 
it works fine as a html page and it's also work on server side 
only not working when embedded it in WebView in .NET MAUI

**Comment by ibrahimahmed1998** [comment]
<pre>
<!doctype html>
<html lang="en">
<body>
  <div>
    <div id="banner">
      <h1>RED365 CHATBOT2</h1>
    </div>
    <div id="webchat" role="main"></div>
  </div>

  <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>

  <script>

    function getCookie(name) {
      const value = `; ${document.cookie}`;
      const parts = value.split(`; ${name}=`);
      if (parts.length === 2) return parts.pop().split(';').shift();
    }

    (async function () {
      const styleOptions = {
        hideUploadButton: true
      };

      const tokenEndpointURL = new URL('https://99677f854f704c4b9da8d9d1187c76.58.environment.api.powerplatform.com/powervirtualagents/botsbyschema/crf2d_redChatbot/directline/token?api-version=2022-03-01-preview');

      const locale = document.documentElement.lang || 'en';

      const apiVersion = tokenEndpointURL.searchParams.get('api-version');

      const [directLineURL, token] = await Promise.all([
        fetch(new URL(`/powervirtualagents/regionalchannelsettings?api-version=${apiVersion}`, tokenEndpointURL))
          .then(response => {
            if (!response.ok) {
              throw new Error('Failed to retrieve regional channel settings.');
            }
            return response.json();
          })
          .then(({ channelUrlsById: { directline } }) => directline),
        fetch(tokenEndpointURL)
          .then(response => {
            if (!response.ok) {
              throw new Error('Failed to retrieve Direct Line token.');
            }
            return response.json();
          })
          .then(({ token }) => token)
      ]);

      const directLine = WebChat.createDirectLine({ domain: new URL('v3/directline', directLineURL), token });

      var CurrentUser98 = getCookie('CurrentUser98');

      const subscription = directLine.connectionStatus$.subscribe({
        next(value) {
          if (value === 2) {
            directLine
              .postActivity({
                localTimezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
                locale,
                name: 'startConversation',
                type: 'event',
                value: { username: CurrentUser98 }
              })
              .subscribe();

            subscription.unsubscribe();
          }
        }
      });

      WebChat.renderWebChat({ directLine, locale, styleOptions }, document.getElementById('webchat'));
    })();
  </script>
</body>

</html>
</pre>

**Comment by jfversluis** [comment]
Please add everything you need to do to the reproduction project that I have provided, which is a good starting point; a new MAUI project. Keep adding the files and things that influence the behavior until you hit the issue, then please share that project back.

**Comment by ibrahimahmed1998** [comment]
https://github.com/ibrahimahmed1998/new-maui-app1-chat

**Comment by ibrahimahmed1998** [comment]
Hi @jfversluis,
I created a new project only I need this line :

 `   <ScrollView>
        <WebView Source="https://redtenantmobilenotification.azurewebsites.net/chatbot.html"></WebView>
    </ScrollView>`
 
and this is result:
`[chromium] [INFO:CONSOLE(2)] "Uncaught SyntaxError: Unexpected token .", source: https://redtenantmobilenotification.azurewebsites.net/js/webchat.js (2)
[chromium] [INFO:CONSOLE(58)] "Uncaught (in promise) ReferenceError: WebChat is not defined", source: https://redtenantmobilenotification.azurewebsites.net/chatbot.html (58)`

![image](https://github.com/user-attachments/assets/dea4fe03-229d-492c-9353-c15fe5f135a3)

**Comment by kubaflo** [comment]
Hi @ibrahimahmed1998 you should explicitly set the `Height` property of your WebView or you can also wrap it inside a Grid like this
 ``` 
 <Grid RowDefinitions="*">
    <ScrollView>
      <WebView Source="https://redtenantmobilenotification.azurewebsites.net/chatbot.html"/>
    </ScrollView>
  </Grid>
 ```
 
 <img src="https://github.com/user-attachments/assets/20dbed61-a4f0-4459-8f37-b5ca734a5bac" height="700px" />

**Comment by ibrahimahmed1998** [comment]
Hi @kubaflo 
thanks for helping the issue were in Android simulator I tried another device and works fine 
thanks for all

**Comment by ibrahimahmed1998** [comment]
I have another Issue when I type my message the keyboard covers the typing message and I can't control input area because it not .NET MAUI Control it's related to WebView Component, how control in this view?
