### ISSUE TITLE
Shadow is not updating on change of parent control.

### ISSUE THREAD

**Issue by ankitgupta2oct** [dotnet/maui#24034]
### Description

Hey,
I am facing an issue in Shadow.
When I changed the size of Shadow's parent control, I expected Shadow to update it.
It's working fine with iOS but not working in Android.
I tried with different parent controls like Border, VerticalStackLayout, etc. but the results are the same.
Can someone look into this?

App Code: 
[Test2.zip](https://github.com/user-attachments/files/16509881/Test2.zip)

Not working sample in Android:

https://github.com/user-attachments/assets/fc7c192b-31e4-4f88-81e6-ad8b808f409e

Working sample in iOS:

https://github.com/user-attachments/assets/35480344-c02c-4170-b583-8b27d9f6c4dc

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All versions.

### Did you find any workaround?

No

**Comment by ninachen03** [comment]
I can repro this issue at Android platform on the latest 17.11.0 Preview 6.0( 8.0.3 & 8.0.70 & 8.0.71)
