### ISSUE TITLE
[MacCatalyst-resizetizer] SVG file does not generate density-dependent png files.

### ISSUE THREAD

**Issue by tounaobun** [dotnet/maui#24030]
### Description

At build time, SVG files located from Resources/Images generate png files, however, png file is not density-dependent. For example, SVG file base size is 24*24 pixels. The generated png file is also 24*24 pixels, which is not correct for MacCatalyst.

### Steps to Reproduce

See above.

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Did you find any workaround?

No.

### Relevant log output

```shell
No.
```

**Comment by tounaobun** [comment]
<img width="1040" alt="Screenshot 2024-08-06 at 17 27 34" src="https://github.com/user-attachments/assets/a61c38d7-f207-4586-b2fe-2a0a05dd3c5f">

**Comment by kevinxufei** [comment]
I can repro this issue at Maccatalyst platform on the latest 17.6.13(build 424) (8.0.71 & 8.0.61 & 8.0.3). The resolution of the downloaded SVG format image is 64*64, and the resolution of the PNG format image generated by the build is also 64*64.![Screenshot 2024-08-07 154314](https://github.com/user-attachments/assets/7f30a2f8-30ce-49bd-a6ae-839063188e19)

**Comment by tounaobun** [comment]
@kevinxufei  Hope they can fix it in the near future.
