### ISSUE TITLE
HarmonyOS support

### ISSUE THREAD

**Issue by hxmcn** [dotnet/maui#2405]
## Summary
Any plan for Huawei HarmonyOS Apps development support with MAUI single codebase solution?

## More Info
[HarmonyOS Dev Home](https://developer.huawei.com/en/)
[HarmonyOS is an open source OS](https://github.com/Awesome-HarmonyOS/HarmonyOS)

**Comment by vhugogarcia** [comment]
There is no plans for the current release. However, Huawei can collaborate as Samsung is doing it right now with Tizen. The platform support depends on Huawei or other developers out there. 

.NET MAUI, seems to be open to support other platforms.

**Comment by hxmcn** [comment]
Thanks, @vhugogarcia 
No, HarmonyOS is a different OS thought it take many AOSP codes, it has Android compatible APIs which makes it can run Android Apps directly, but HarmonyOS has it's own APIs as far as I know. @kcrg
