### ISSUE TITLE
CS0616 error with NSPasteboard.NSPasteboardTypeString on latest workloads

### ISSUE THREAD

**Issue by kevcrooks** [dotnet/maui#24060]
### Description

After updating my workloads to the latest versions, I now have an error:
`error CS0618: 'NSPasteboard.NSPasteboardTypeString' is obsolete: 'Use the 'NSPasteboardType' enum instead.`

This comes from the following lines:
```
var pb = NSPasteboard.GeneralPasteboard;
pb.DeclareTypes([NSPasteboard.NSPasteboardTypeString], null);
```

However I cannot see an available `NSPasteboardType` enum to use inside `AppKit`.

The build previously worked fine until the latest `dotnet workload update`, so my current packages are:
```
macos                      14.5.8018/8.0.100      SDK 8.0.300
maui                       8.0.71/8.0.100         SDK 8.0.300
```
I think it's likely to be a change to one of these that caused the CS0616.

### Steps to Reproduce

Ran `dotnet workload update` to the latest versions of `macos` and `maui` - I'm not sure how to determine which of these specifically causes the error.

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by jfversluis** [comment]
Just to be clear this is something in your code right? 

It looks like this should be available: https://github.com/xamarin/xamarin-macios/pull/20643, but only from .NET 9 preview 6. I'm not sure if this will be backported to net8 at this time. But I think you'll have enough time during the .NET 9 cycle to get this done.

Looks like there is nothing to be done here right now, so closing this for now.

**Comment by kevcrooks** [comment]
> Just to be clear this is something in your code right?
Yes the example above was from my code, but also used in this repo here, however perhaps you're right it's a case of updating to .NET 9 to remove the error.

https://github.com/dotnet/maui/blob/698f64dd21954fd321bb78c90b5cd22fed0924cf/src/Essentials/src/Clipboard/Clipboard.macos.cs#L10

**Comment by rolfbjarne** [comment]
Reopening, this is an issue in xamarin-macios.

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#20993
