### ISSUE TITLE
Changing the MainPage resets the ModalStack of Navigation without popping the pages

### ISSUE THREAD

**Issue by era-maui** [dotnet/maui#24090]
### Description

If you have a place in the code where you need to change the MainPage to something else, we usually change the MainPage and then dispose of the old main page and its Navigation. This is done to prevent memory leaks of the pages related to the old Main Page. However, in the following example

```
oldMainPage = MainPage;
vat t = oldMainPage.Navigation.ModalStack;		
MainPage = newMainPage;
vat t1 = oldMainPage.Navigation.ModalStack;	
```	
I can see that the t and t1 differ, t1 will be an empty IReadOnlyList. Meaning that reference to the Modal pages is gone and can only be accessed in Window. This is not the case for oldMainPage.Navigation.NavigationStack, this one still keeps reference of the old pages.

Is this a known or expected thing?

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

The workaround in this particular case is to Pop the pages before we change the main page, which can create visual artifacts

**Comment by jfversluis** [comment]
Just a heads up, we probably won't be prioritizing this as [MainPage will be obsoleted](https://github.com/dotnet/maui/pull/23692) as of .NET 9. So you might want to look into doing things differently altogether.

**Comment by PureWeen** [comment]
I might have misunderstood but when I tested the stack is cleared. From what I can remember when you query the modal stack it basically just walks up to the window until it finds the window and returns the modal stack. 

If a page doesn't have a window it returns zero. 

Maybe you're pushing modals before a window has loaded and those are staying cached somewhere and then are still around when it swaps?

![image](https://github.com/user-attachments/assets/32c5807c-6403-4e00-915c-24ec500954f8)

**Comment by era-maui** [comment]
The stack is cleared, but as far as I can see, the modal page stays in Windows[0].LogicalChildren for a while. We mainly experience this because we want to call DisconnectHandler on the pages in modal stack. We cannot do it before we change MainPage and after we change MainPage we do not have them in ModalStack. The current workaround is to manually pop them before MainPage is changed.

Also, judging from previous comments this might work differently in .net9

**Comment by PureWeen** [comment]
This behavior probably didn't change in net9 can you attach a repro?
