### ISSUE TITLE
How to assign the default Handler of a Maui control?

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#2411]
I'm in the process of creating a new MAUI control from scratch. I didn't find any documentation about it, is there any? 
I found this https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize it tells how to customize an existing handler, but it doesn't mention how to specify the default handler of a custom View.

**Comment by juansturla** [comment]
I'm curious about that too. 
I think one way of doing that is just by adding a parent to the control. Of course every custom View would still have the View handler.
If you have to create a handler, and the mapper, and everything I think that is going to be really messy.

**Comment by arivoir** [comment]
I'm building basic control I named _C1Border_, just a border around another element.

I tried setting the Handler property in the constructor of the control

`Handler = new C1BorderHanlder();`

The handler _C1BorderHandler_ implements **IViewHandler** interface. 

I see the method _SetVirtualView_ is called, and looks reasonable, but then the _NativeView_ property is called, so the native element must be created, but in Android it is necessary to have the Context, and the _SetMauiContext_ is called after _NativeView_.

The order the methods are called doesn't seem reasonable, or maybe is that setting Handler is not supposed to be used inside the constructor of the control. I don't know. I need the documentation urgently.

**Comment by juansturla** [comment]
When the release comes out, it suposed to feature "Borders everywhere" https://github.com/dotnet/maui/wiki/status
Of course, your question is still valid on how are handlers supposed to be used and when.

**Comment by arivoir** [comment]
Probably not in the way I need them, like having the ability to specify every side thickness, or every corner width and height, or whether the border stroke is centered in the border of the control. It's part of a bigger thing.
Anyway, my point is about a understanding the Handlers. I hope the doc or samples appear soon https://twitter.com/jsuarezruiz/status/1435533224885772289?s=20 @jsuarezruiz

**Comment by pictos** [comment]
@arivoir what do you mean with ` but it doesn't mention how to specify the default handler of a custom View.`? I created a customHandler for a ProgressBar control and didn't need to do that... But maybe I missed something.

**Comment by arivoir** [comment]
@pictos how do the native progress bar is provided? Did you created the ProgressBar or customized an existing one?

**Comment by Eilon** [comment]
Hi everyone, you can associate the handlers for your controls by calling `MauiAppBuilder.ConfigureMauiHandlers(handlers => handlers.AddHandler<IMyControl, MyControlHandler>());`, where `IMyControl` is the interface of your control, and `MyControlHandler` is the platform-specific handler (you'll probably have multiple `MyControlHandler` types - one for each platform you support).

To see what a fully-contained .NET MAUI control looks like, have a look at the BlazorWebView control for .NET MAUI that's also in this repo:

* Everything is in here: https://github.com/dotnet/maui/tree/main/src/BlazorWebView/src/Maui
* The [platform-independent control](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/BlazorWebView.cs) implements the [platform-independent interface](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/IBlazorWebView.cs)
   * Note: You don't strictly need the interface, but it's a pattern that .NET MAUI follows
* Each platform has a handler:
   * [Android](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs)
   * [Windows](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Windows/BlazorWebViewHandler.Windows.cs)
   * [iOS/Mac Catalyst](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/iOS/BlazorWebViewHandler.iOS.cs) (these share the same code in this case, and often will)
   * The [NetStandard](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/BlazorWebViewHandler.cs) 'variation' is used when there's no associated platform, and also for code that is identical on all platforms

**Comment by arivoir** [comment]
That really helped @Eilon. Thank you very much!
