### ISSUE TITLE
iOS push notification fails with NotificationHubClient in release mode

### ISSUE THREAD

**Issue by intellimedhu** [dotnet/maui#24118]
### Description

I was able to send push notifications in debug to my iPhone, through AzureNotificationHub.
But it fails in release mode (using TestFlight).

Using nuget package: Microsoft.Azure.NotificationHubs 4.2.0

During debugging, I found out that it fails to register to the NotificationHub.
When calling NotificationHubClient.CreateOrUpdateRegistrationAsync() method, it throws an exception.

**Exception:**
```
UnexpectedElementExpectingElements, Element, DeviceToken, http://schemas.microsoft.com/netservices/2010/10/servicebus/connect, PushVariables
System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowRequiredMemberMissingException(XmlReaderDelegator xmlReader, Int32 memberIndex, Int32 requiredIndex, XmlDictionaryString[] memberNames)
```

I tried enabling the Mono interpreter, just like they recommended in a [previous issue](https://github.com/dotnet/maui/issues/11131) and in the [documentation](https://learn.microsoft.com/en-us/dotnet/maui/macios/interpreter?view=net-maui-8.0) but the problem still remains.

```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <UseInterpreter>true</UseInterpreter>
</PropertyGroup>

```
```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <MtouchInterpreter>-all</MtouchInterpreter>
</PropertyGroup>
```

```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <MtouchInterpreter>all</MtouchInterpreter>
</PropertyGroup>
```

### Steps to Reproduce

1. Create new MAUI app
2. Add Microsoft.Azure.NotificationHubs nuget
3. Try to register to NotificationHub

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.5.1

### Did you find any workaround?

No

### Relevant log output

```shell
UnexpectedElementExpectingElements, Element, DeviceToken, http://schemas.microsoft.com/netservices/2010/10/servicebus/connect, PushVariables
System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowRequiredMemberMissingException(XmlReaderDelegator xmlReader, Int32 memberIndex, Int32 requiredIndex, XmlDictionaryString[] memberNames)
```

**Comment by jfversluis** [comment]
Could you maybe try this and see if that helps: https://github.com/dotnet/maui/issues/11131#issuecomment-1305816109

**Comment by intellimedhu** [comment]
I also tried it with this:
```
<MtouchExtraArgs Condition="'$(TargetFramework)' == '$(iOSTargetFramework)' and '$(Configuration)' == 'Release'">
        --linkskip=Microsoft.Azure.NotificationHubs
</MtouchExtraArgs>
```

but this causes the whole app to crash, I can't even start it.

**Comment by PureWeen** [comment]
@rolfbjarne @dalexsoto  thoughts?

@intellimedhu can you attach the exception you are seeing?

**Comment by rolfbjarne** [comment]
> @rolfbjarne @dalexsoto thoughts?
> 
No idea what's going on here, but the exception details + stack trace might help us to start looking in the right direction.

**Comment by intellimedhu** [comment]
> @rolfbjarne @dalexsoto thoughts?
> 
> @intellimedhu can you attach the exception you are seeing?

```
ErrorInLine, 1, 995
UnexpectedElementExpectingElements, Element, DeviceToken, http://schemas.microsoft.com/netservices/2010/10/servicebus/connect, PushVariables---- at

System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowRequiredMemberMissingException(XmlReaderDelegator, Int32, Int32, XmlDictionaryString[]) at

System.Runtime.Serialization.XmlObjectSerializerReadContext.GetMemberIndexWithRequiredMembers(XmlReaderDelegator, XmlDictionaryString[], XmlDictionaryString[], Int32, Int32, ExtensionDataObject) at

System.Runtime.Serialization.ReflectionXmlReader.ReflectionReadMembers(XmlReaderDelegator, XmlObjectSerializerReadContext,  XmlDictionaryString[],  XmlDictionaryString[], ClassDataContract, Object&) at

System.Runtime.Serialization.ReflectionReader.ReflectionReaderClass(XmlReaderDelegator, XmlObjectSerializerReadContext,
XmlDictionaryString[],  XmlDictionaryString[], ClassDataContract) at

System.Runtime.Serialization.ReflectionXmlClassReader.ReflectionReaderClass(XmlReaderDelegator xmlReader, 
XmlObjectSerializerReadContext context, XmlDictionaryString[] memberNames, XmlDictionaryString[] memberNameSpaces) at

System.Runtime.Serialization.DataContracts.ClassDataContract.ReadXmlValue(XmlReaderDelegator, XmlObjectSerializerReadContext ) at

System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract, XmlReaderDelegator ) at

System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator , String, String,
Type, DataContract&) at

System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator , Type, DataContract,
String, String) at

System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator , Boolean, DataContractResolver ) at

System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadObjectHandleExceptions(XmlReaderDelegator, Boolean, DataContractResolver ) at

System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlReader ) at

Microsoft.Azure.NotificationHubs.Messaging.EntityDescriptionSerializer.Deserialize(XmlReader reader, String typeName) at

Microsoft.Azure.NotificationHubs.NotificationHubClient<ReadEntityAsync>d_219` 1[[Microsoft.Azure.NotificationHubs.RegistrationDescription, Microsoft.Azure.NotificationHubs, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext() at

Microsoft.Azure.NotificationHubs.NotificationHubClient.<>c_DisplayClass209_0`1.<<CreateOrUpdateRegistrationImplAsync>b_0>d[[Microsoft.Azure.NotificationHubs.RegistrationDescription, Microsoft.Azure.NotificationHubs, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext() 
--- End of stack trace from previous location --- 

at

Microsoft.Azure.NotificationHubs.NotificationHubRetryPolicy.<RunOperation>d_4`1[[Microsoft.Azure.NotificationHubs.RegistrationDescription, Microsoft.Azure.NotificationHubs, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext() at

Microsoft.Azure.NotificationHubs.NotificationHubRetryPolicy.<RunOperation>d_4`1[[Microsoft.Azure.NotificationHubs.RegistrationDescription, Microsoft.Azure.NotificationHubs, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext() at

Microsoft.Azure.NotificationHubs.NotificationHubClient.<CreateOrUpdateRegistrationImplAsync>d_209`1
[[Microsoft.Azure.NotificationHubs.RegistrationDescription, Microsoft.Azure.NotificationHubs, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext() at

```

**Comment by rolfbjarne** [comment]
I wonder if it's the linker removing stuff.

Can you try disable the linker + enable the interpreter:

```xml
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <UseInterpreter>true</UseInterpreter>
    <MtouchLink>None</MtouchLink>
</PropertyGroup>
```

and see if that changes anything?

**Comment by intellimedhu** [comment]
> I wonder if it's the linker removing stuff.
> 
> Can you try disable the linker + enable the interpreter:
> 
> ```
> <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
>     <UseInterpreter>true</UseInterpreter>
>     <MtouchLink>None</MtouchLink>
> </PropertyGroup>
> ```
> 
> and see if that changes anything?

Sorry for the late reply. This causes the whole app to crash, it can't even start.

**Comment by rolfbjarne** [comment]
> > I wonder if it's the linker removing stuff.
> > Can you try disable the linker + enable the interpreter:
> > ```
> > <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
> >     <UseInterpreter>true</UseInterpreter>
> >     <MtouchLink>None</MtouchLink>
> > </PropertyGroup>
> > ```
> >   
> > and see if that changes anything?
> 
> Sorry for the late reply. This causes the whole app to crash, it can't even start.

What about this? This should be pretty close to the working Debug configuration.

```xml
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <UseInterpreter>true</UseInterpreter>
    <MtouchUseLlvm>false</MtouchUseLlvm>
</PropertyGroup>
```

**Comment by intellimedhu** [comment]
> > > I wonder if it's the linker removing stuff.
> > > Can you try disable the linker + enable the interpreter:
> > > ```
> > > <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
> > >     <UseInterpreter>true</UseInterpreter>
> > >     <MtouchLink>None</MtouchLink>
> > > </PropertyGroup>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and see if that changes anything?
> > 
> > 
> > Sorry for the late reply. This causes the whole app to crash, it can't even start.
> 
> What about this? This should be pretty close to the working Debug configuration.
> 
> ```
> <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
>     <UseInterpreter>true</UseInterpreter>
>     <MtouchUseLlvm>false</MtouchUseLlvm>
> </PropertyGroup>
> ```

This solved the problem, thank you! I was able to receive notifications, which were sent through the Azure Hub.
These changes how much affect the app (size, speed)?

**Comment by rolfbjarne** [comment]
> This solved the problem, thank you!

That's great!

It looks like this is a problem with our LLVM support then. Would you be able to provide a test project we could use to reproduce the problem in order to track it down and fix it?

> These changes how much affect the app (size, speed)?

Not compiling with LLVM can make the app slightly smaller (LLVM typically produces more code) although also slightly slower. Depending on the app, the slowness can range from impossible to measure to a noticeable delay, in particular for apps that use a lot of math in C# (for instances games). Most UI apps won't see any difference whatsoever though. If your app feels responsive as usual, then you're fine performance-wise.

**Comment by intellimedhu** [comment]
> > This solved the problem, thank you!
> 
> That's great!
> 
> It looks like this is a problem with our LLVM support then. Would you be able to provide a test project we could use to reproduce the problem in order to track it down and fix it?
> 
> > These changes how much affect the app (size, speed)?
> 
> Not compiling with LLVM can make the app slightly smaller (LLVM typically produces more code) although also slightly slower. Depending on the app, the slowness can range from impossible to measure to a noticeable delay, in particular for apps that use a lot of math in C# (for instances games). Most UI apps won't see any difference whatsoever though. If your app feels responsive as usual, then you're fine performance-wise.

I created a test project and invited you.

But I also found out what causes the problem. 
In my solution I have 2 projects (maui and a simple class library), if the class library contains the NotificationHubs nuget (and the maui project doesn't), then it throws the exception. But if there's only one project, it works fine.

**Comment by rolfbjarne** [comment]
> But I also found out what causes the problem.
> In my solution I have 2 projects (maui and a simple class library), if the class library contains the NotificationHubs nuget (and the maui project doesn't), then it throws the exception. But if there's only one project, it works fine.

That's interesting.

Can you get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) for a build that works, and one that doesn't?

**Comment by Zack-G-I-T** [comment]
We have a class library that uses the Microsoft.Azure.NotificationHubs which our maui app references. The notifications work in debug, and when releasing the app to firebase. However when the same code is uploaded to TestFlight we get nothing. I tried  disabling the linker and enabling the interpreter but no luck.

**Comment by mattleibow** [comment]
@rolfbjarne should we move this to macios or runtime or a different repo?

**Comment by rolfbjarne** [comment]
> I created a test project and invited you.

Thanks, I tried the test project, but unfortunately I wasn't able to reproduce any problems.

In any case it's possible we've fixed this in .NET 9, can you try upgrading your test projects to `net9.0-ios` and see if that works?
