### ISSUE TITLE
[Bug] Building to ios-arm64 with Microsoft.Maui.Controls throws "The stream does not support seeking"

### ISSUE THREAD

**Issue by BButner** [dotnet/maui#2412]
### Description
Creating a new MAUI project, and in Startup.cs importing `Microsoft.Maui.Controls` then calling "Device.GetAssemblies()" causes the build to throw when launching on a physical device:

```
Unhandled Exception:
  System.NotSupportedException: The stream does not support seeking
  [ERROR] FATAL UNHANDLED EXCEPTION: System.NotSupportedException: The stream does not support seeking
```

### Steps to Reproduce

1. Create a new MAUI project with `dotnet new maui -n ErrorTesting`
2. `cd ErrorTesting/ErrorTesting`
3. Edit `Startup.cs` and add `using Microsoft.Maui.Controls;`
4. Edit the `Configure` method and add `Device.GetAssemblies();`
5. Edit `ErrorTesting.csproj` to edit `ApplicationId` to match the Provisioning Profile Bundle ID, and edit the `RuntimeIdentifier` to change "iossimulator-x64" => "ios-arm64". (This assumes that all Apple Developer work has been done for device provisioning and provisioning profiles)

### Expected Behavior
Specifically, `Device.GetAssemblies()` is used when doing `DependencyService.Register(Device.GetAssemblies());`

Expected functionality is to be able to run the application.

### Actual Behavior

The code compiles, then once the app launches and makes it past the Splash Screen it throws the aforementioned error.

### Basic Information

*All dev being done on MacBook Pro (macOS Big Sur Version 11.5.2)

- Version with issue: 6.0.100-preview.7.21379.14
- Last known good version: N/A
- IDE: Visual Studio Code
- Platform Target Frameworks: 
  - iOS: 15.0
- Nuget Packages: None
- Affected Devices:
  - iPhone XS Max (iOS 15 Beta 8)
  - iPad Pro (14.4.2)

### Reproduction Repo
https://github.com/BButner/maui-issue

**Comment by shimingsg** [comment]
@BButner, thanks for reporting this issue.
verified with VS 17.2.0 Preview 3.0 [32317.342.main], .net version: 6.0.300-preview.22154.4
it can't find the method "Device.GetAssemblies();" , could you have a try on the latest version?
add below RuntimeIdentifier,  output folder of  ios-arm64 is empty.
```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
	</PropertyGroup>
```
