### ISSUE TITLE
Pair to Mac really needs a timeout option, at least for the "Executing SayHello Task"

### ISSUE THREAD

**Issue by datvm** [dotnet/maui#24131]
### Description

Right now Pair to Mac suffers a connection issue very often and no amount of reinstall makes it work. I have learnt to just deal it it "gently". In both Visual Studio and command line, a build with connection to Mac usually fails at this:

```
> dotnet build -t:Run -f net8.0-ios

  Determining projects to restore...
  Restored <Project>.csproj (in 394 ms).
  6 of 7 projects are up-to-date for restore.
  Executing SayHello Task to establish a connection to a Remote Server.
                        Properties:
                                SessionId=1dd10a1740ece6a4371b5d3976b35a03f8f40ae0f108122e24126b253f1c1766,
                                Addresss=192.168.1.5,
                                SshPort=22,
                                TcpPort=,
                                User=lukevo,
                                AppName=Demo,
                                VisualStudioProcessId=,
                                ContinueOnDisconnected=true
```

It simply wouldn't fail and stay at this indefinitely. In Windows Terminal, pressing Ctrl + C wouldn't terminate it and I have to close the terminal window. In VS, the Pair to Mac dialog would be stuck at "Connecting to Mac" and the only solution is to restart VS.

This gets annoying real quick as connection gets dropped randomly while working as well. Please add an option to timeout this operation so at least it can be retried automatically or manually without restarting the whole work environment.

### Public API Changes

None

### Intended Use-Case

Build iOS apps from Windows. I cannot build it on the Mac directly due to #17078

**Comment by datvm** [comment]
@jfversluis are you sure this should belong to VS Feedback? This issue happens with CLI as well (running `dotnet build` with Mac info) so I thought VS feedback would redirect back here.

**Comment by jfversluis** [comment]
@datvm at least it shouldn't be here 😄 

Depending on what the solution looks like its either something for VS or https://github.com/xamarin/xamarin-macios. Maybe best to start with the latter. Unfortunately they are not part of the dotnet org yet here on Github so its not easy to transfer. Could I ask you to maybe open the issue there?

Thanks!
