### ISSUE TITLE
[Testing] HandlerDoesNotLeak.DatePicker

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#24147]
### Description

HandlerDoesNotLeak.DatePicker fails a lot. 

We setup a general structure [here](https://github.com/dotnet/maui/pull/23784) for testing memory leaks. We could move this test (or all of them) over to appium, which should have a more accurate run pattern. 

For now we could just move this one and make a note in the device tests.

**Comment by jsuarezruiz** [comment]
Done https://github.com/dotnet/maui/pull/24585/files
