### ISSUE TITLE
About MAUI appicon and splash not updating on iOS device

### ISSUE THREAD

**Issue by flogeiger** [dotnet/maui#24159]
### Description

I've created a new MAUI Application and attempted to change the app icon and splash screen using Inkscape. The changes work fine on a physical Android device but not on my iPhone 11. I followed the instructions from the official documentation [(https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?view=net-maui-8.0&tabs=macios#platform-specific-configuration).

I connected to a Mac to build the application, cleaned the obj and bin folders multiple times, deleted the app from the iPhone several times, restarted the phone, and recompiled. Despite trying all these steps, the pre-configured app icon and splash screen are still being displayed on the iPhone.

I didn't use new SVGs; instead, I reused the provided SVGs and edited them with Inkscape. Under the path MauiAppTEST\obj\Debug\net8.0-ios\ios-arm64\resizetizer\r\Assets.xcassets\appicon.appiconset, I can see my updated icons.
![Screenshot 2024-08-12 161535](https://github.com/user-attachments/assets/8e2cdc25-f1b2-4d46-a332-e59afa83cc84)

i created a repo for it so you can check the weird behavior! I already checked every closed ticket regarding that topic but still could not finde a solution!
https://github.com/flogeiger/MauiAppTEST
please help me!
This is the Version which i am currently using:
![further Information](https://github.com/user-attachments/assets/f10ab220-1d14-44c0-a9d5-4f87fbbbb8e3)

### Steps to Reproduce

1. created a new Maui App
2. changed the app icon and splash screen using Inkscape
3. Phisical andriod device shows the changes 
4. I phone not!

### Link to public reproduction project repository

https://github.com/flogeiger/MauiAppTEST

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by flogeiger** [comment]
Already tried 16731, 14288,8685, 11654 and 17940 didnt help! connected Mac with Visual Studio (18414)!

**Comment by jfversluis** [comment]
No change in your code, just ran and shows up alright for me

![image](https://github.com/user-attachments/assets/2bfe48fe-4996-4edc-a1ac-00ff0bd56b4c)

**Comment by jfversluis** [comment]
Deploying on a physical device does show some weird(er) behavior indeed.

When I remove 

```xml
<sodipodi:namedview
   id="namedview26"
   pagecolor="#ffffff"
   bordercolor="#000000"
   borderopacity="0.25"
   inkscape:showpageshadow="2"
   inkscape:pageopacity="0.0"
   inkscape:pagecheckerboard="0"
   inkscape:deskcolor="#d1d1d1"
   showgrid="false"
   inkscape:zoom="0.64275388"
   inkscape:cx="371.0596"
   inkscape:cy="236.48243"
   inkscape:window-width="1920"
   inkscape:window-height="1009"
   inkscape:window-x="4472"
   inkscape:window-y="105"
   inkscape:window-maximized="1"
   inkscape:current-layer="g204" />
```

From the SVG its much better. Looks like Inkscape adds some unsupported SVG stuff in there.

**Comment by flogeiger** [comment]
@jfversluis i removed the sodipodi Element from the svg. But still when i build the application on my iphone 11 i still get the pre configured .net maui Icon with the splash. What kind of hard ware device are you using?
![image](https://github.com/user-attachments/assets/e4f604e1-0b58-437d-9b41-1aa98b338d17)
![image](https://github.com/user-attachments/assets/e1951262-0f7f-4567-a888-4630e3aba306)

i deleted the application and recompiled it while being connected to the mac...
could it also be, that i need to upgrade my sdk?

**Comment by flogeiger** [comment]
already running the latest SDK:
![image](https://github.com/user-attachments/assets/ab3b5b3e-7171-4764-a0f1-519ab02ca0a4)

As I already shared the app Icon set. It should work for my Iphone... Are you able to check it with a phisical Iphone 11 device?
![image](https://github.com/user-attachments/assets/2fe75d3b-275f-4318-8f92-d837fa50e8d9)
the json looks like this:
{
  "images": [
    {
      "idiom": "iphone",
      "size": "20x20",
      "scale": "2x",
      "filename": "appicon20x20@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "20x20",
      "scale": "2x",
      "filename": "appicon20x20@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "20x20",
      "scale": "3x",
      "filename": "appicon20x20@3x.png"
    },
    {
      "idiom": "iphone",
      "size": "29x29",
      "scale": "2x",
      "filename": "appicon29x29@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "29x29",
      "scale": "2x",
      "filename": "appicon29x29@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "29x29",
      "scale": "3x",
      "filename": "appicon29x29@3x.png"
    },
    {
      "idiom": "iphone",
      "size": "40x40",
      "scale": "2x",
      "filename": "appicon40x40@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "40x40",
      "scale": "2x",
      "filename": "appicon40x40@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "40x40",
      "scale": "3x",
      "filename": "appicon40x40@3x.png"
    },
    {
      "idiom": "iphone",
      "size": "60x60",
      "scale": "2x",
      "filename": "appicon60x60@2x.png"
    },
    {
      "idiom": "iphone",
      "size": "60x60",
      "scale": "3x",
      "filename": "appicon60x60@3x.png"
    },
    {
      "idiom": "ipad",
      "size": "76x76",
      "scale": "2x",
      "filename": "appicon76x76@2x.png"
    },
    {
      "idiom": "ipad",
      "size": "83.5x83.5",
      "scale": "2x",
      "filename": "appicon83.5x83.5@2x.png"
    },
    {
      "idiom": "ios-marketing",
      "size": "1024x1024",
      "scale": "1x",
      "filename": "appiconItunesArtwork.png"
    }
  ],
  "properties": {},
  "info": {
    "version": 1,
    "author": "xcode"
  }
}

**Comment by kevinxufei** [comment]
This problem cannot be reproduced on the latest 17.11.0 Preview 7.0 ( 8.0.80 & 8.0.3 & 8.0.0-rc.1.9171).
IOS device:
iphone13(17.5.1)/iphoneSE(16.2)/iphone11(17.2.1)

**Comment by flogeiger** [comment]
@kevinxufei can you also verify it with an iphone11( iOS-Version: 17.5.1)
because i don't now anymore what i can do...

**Comment by flogeiger** [comment]
Hi all,

sorry for wasting your time!

I found out what i did wrong. I used for deployment Hot Restart:
https://learn.microsoft.com/en-us/dotnet/maui/ios/hot-restart?view=net-maui-8.0&viewFallbackFrom=net-maui-7.0#:%7E:text=.NET%20MAUI%20apps%20that%20use%20iOS%20asset%20catalogs%20are%20currently%20unsupported%20by%20hot%20restart.

Under Limitations i found the following sentence:
Asset catalogs aren't supported. When using Hot Restart, your app will show a .NET icon and launch screen.

Therefore i tried the wireless deployment and it worked :
https://learn.microsoft.com/en-us/dotnet/maui/ios/wireless-deployment?view=net-maui-8.0&tabs=vs

Can you please add a remark to the following document for the limitation!:
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?view=net-maui-8.0&tabs=macios#platform-specific-configuration

@jfversluis can you please remove the information:
https://github.com/dotnet/maui/issues/24159#issuecomment-2284226056 from the ticket. I might get problems at work if they see the splash screen!

After deleting the comment you can close the Ticket.

**Comment by jfversluis** [comment]
Thanks for letting us know!
