### ISSUE TITLE
Toolbar is not displayed after deactive an app and activate it again.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24169]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Toolbar-is-not-displayed-after-deactive-/10712114)._

---
After starting the app all works fine and the mainpage's toolbar is shown. After app deactivation (with middle smartphone button) and activate it again the toolbar is gone. The app works otherwise fine. Only the toolbar is not loaded.

Maui App / .Net 8.0
Microsoft Visual Studio Community 2022 (64-Bit) - Current
Version 17.10.5

---
#### Feedback Bot on 7/29/2024, 06:33 PM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 7/31/2024, 02:00 AM: 

(private comment, text removed)
#### Stefan Sattler on 7/31/2024, 02:25 AM: 

(private comment, text removed)
#### Stefan Sattler on 8/1/2024, 01:38 PM: 

(private comment, text removed)
#### Stefan Sattler on 8/2/2024, 03:01 AM: 

(private comment, text removed)
#### Stefan Sattler on 8/3/2024, 02:37 AM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 8/1/2024, 04:09 AM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 8/1/2024, 10:51 PM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 8/2/2024, 04:35 AM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 8/5/2024, 03:49 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
@kevinxufei Could you attach the sample you used to verify the issue?
