### ISSUE TITLE
IOS and ANDROID status bar cannot change color

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24177]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IOS-and-ANDROID-status-bar-cannot-change/10703788)._

---
\[severity:I’m unable to use this version\]  
Previously, adding this syntax to MainPage.xaml can change the status column color.  
But upgrade to .net8.0 and use visual studio 17.11.0 Preview 3.0  
can’t change him

Want to ask for a solution

```  
 NavigationPage.HasNavigationBar="False"
 BackgroundColor="{DynamicResource PageBackgroundColor}"
  
```

![螢幕擷取畫面 2024-07-16 133033.png](https://aka.ms/dc/image?name=Bd27b767f644c408b8c3c0af5bc6f5bce638568032142990694_%E8%9E%A2%E5%B9%95%E6%93%B7%E5%8F%96%E7%95%AB%E9%9D%A2_2024-07-16_133033.png&tid=d27b767f644c408b8c3c0af5bc6f5bce638568032142990694)

---
#### Feedback Bot on 7/16/2024, 01:35 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
.NET MAUI does not directly support influencing the status bar color. At least not on all platforms. For Android you can set the color from the `Platforms/Android/Resources/values/colors.xml`. 

Another alternative that works for both iOS and Android can be found in the .NET MAUI Community Toolkit StatusbarBehavior.

Hope that helps!
