### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error (active)	CS0104	'Permissions' is an ambiguous reference between 'Microsoft.Maui.Ap

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24183]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Severity	Code	Description	Project	File	L/10701447)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.10.3]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0104	'Permissions' is an ambiguous reference between 'Microsoft.Maui.ApplicationModel.Permissions' and 'Java.Security.Permissions'	Zl1800phone (net8.0-android34.0)	C:\Users\joepuhich\source\repos\Zl1800phone - Copy - Copy\Platforms\Android\MainActivity.cs	225	

---
#### Feedback Bot on 7/11/2024, 06:39 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by RoiChen001** [comment]
Could you provide a sample project for us to investigate it further?
Looking forward to your reply!
