### ISSUE TITLE
Issue with updating to Microsoft.Identity.Client v4.61.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24189]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Issue-with-updating-to-MicrosoftIdentit/10659399)._

---
I am setting up a new Maui cross platform app. It needs to use Azure B2C authentication so although I had done this for Xamarin some years ago, I was starting from scratch with a simple test app.

I got the test app working a few weeks ago. But when I started building the real app, I couldn't get it to work.

I finally identified the issue was caused by using the latest Microsoft.Identity.Client v4.61.0. (and . MSAL)

Using version 4.60.3 the code below works. However, using 4.61.0 I was getting a loopback error on the line 
```
var authResult = await _clientApp.AcquireTokenInteractive(Scopes). ExecuteAsync();
```
Microsoft.Identity.Client.MsalClientException: 'Only loopback redirect uri is supported, but msal.trackmeprov2sf://3.0.0.0/ was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details'

Please advise if this is a planned effect of the new version? Or a bug?

I am working through the link 'https://aka.ms/msal-net-os-browser' but I am not sure if I need to implement this.

```
public AuthenticationService()
{
    //string appName = AppDomain.CurrentDomain.FriendlyName;
    //string appVersion = Assembly.GetExecutingAssembly(). GetName(). Version.ToString();
    string appName = "TrackMePro";
    string appVersion = "2.0.0.0";

string redirectUri = $"msal. {appName}://{appVersion}";
    _clientApp = PublicClientApplicationBuilder.Create(clientId)
        . WithB2CAuthority("https://spotnzmaster.b2clogin.com/tfp/spotnzmaster.onmicrosoft.com/B2C_1_susi")
        . WithRedirectUri(new Uri(redirectUri). AbsoluteUri)
        . Build();
}

public async Task<UserContext> SignInAsync()
{
    try
    {
        var authResult = await _clientApp.AcquireTokenInteractive(Scopes). ExecuteAsync();
        UserContext newContext = UpdateUserInfo(authResult);

return newContext;
    }
    catch (Exception ex)
    {
        // Handle the exception
        throw new Exception("Sign In Failed", ex);
    }
}
```

---
#### Feedback Bot on 5/15/2024, 06:48 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I would think this needs to go to this library's repo. From the looks of it this is nothing that originates in .NET MAUI. Thanks!
