### ISSUE TITLE
[Bug] VisualDiagnostics SourceInfo URIs are absolute instead of relative. 

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2418]
### Description
We request SourceInfo from MAUI in order to get the locations of XAML files created by users. In Xamarin.Forms, these URIs would be relative to the user's project (I.E, `MainPage.xaml;assembly=FormsVisualProject`.)

But when calling `VisualDiagnostics.GetXamlSourceInfo` in MAUI, these URIs are absolute to the file system (I.E, `/Users/drasticactions/Developer/Work/MauiSourceInfo/App.xaml;assembly=MauiSourceInfo`

For XAML Hot Reload to work, we need relative URIs. Right now, this happened to still work because, on Windows, we were adding a forward slash to these paths, making them "relative" even though they are not. On Mac, these URIs end up as true file URIs `file://` and break the project system compatibility. We can't find the related XAML in the users project anymore.

### Steps to Reproduce

You can reproduce this by creating a MAUI and Xamarin.Forms application, and calling VisualDiagnostics.GetXamlSourceInfo on a given object. You can also run this code to get the full list.

```
Type type = typeof(VisualDiagnostics);
			FieldInfo info = type.GetField("sourceInfos", BindingFlags.NonPublic | BindingFlags.Static);
			ConditionalWeakTable<object, XamlSourceInfo> value = (ConditionalWeakTable<object, XamlSourceInfo>)info.GetValue(null);
```

**Comment by StephaneDelcroix** [comment]
note to self:
- this was ok in Forms, but has regressed in MAUI
- comes from turning XamlG into a sourcegen
- sourcegen doesn't have the context of project (AFAIK), so it's hard to generate relative paths
