### ISSUE TITLE
Runtime pack errors for new MAUI project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24187]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Runtime-pack-errors-for-new-MAUI-project/10696378)._

---
error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'maccatalyst-x64'.

error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'iossimulator-x64'.

Both showing as errors for new MAUI Blazor project.

---
#### Feedback Bot on 7/3/2024, 06:35 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by RoiChen001** [comment]
This problem cannot be reproduced on the latest 17.11.0 Preview 2.1(8.0.80 & 8.0.72).
