### ISSUE TITLE
Unable to upgrade nuget package Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility 8.0.14 to 8.0.7

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24190]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-upgrade-nuget-package-Microsof/10659605)._

---
I originally opened this case: https://developercommunity.visualstudio.com/t/Unable-to-upgrade-nuget-package-Microsof/10575432 which is related to this.

I had to disable the "useMaui" in the project file. which then allowed me to upgrade to 8.0.14.

I went on vacation, came back and went to work on this project again.  I wasted a day trying to figure out why I could not see my physical iPad in VS 2022.  I finally stumbled on this:

https://stackoverflow.com/questions/76016227/missing-ios-local-devices-and-android-emulators-from-the-play-dropdown

Which says if this is disabled, the physical (and virtual) device will not show to run on.  I re-enabled the useMaui and it showed up again.

This morning I loaded up the project again and now it's giving me the message:

Severity	Code	Description	Project	File	Line	Suppression State	Details

Error	NU1605	Warning As Error: Detected package downgrade: 
Microsoft.Maui.Controls.Compatibility from 8.0.14 to 8.0.7. Reference the package directly from the project to select a different version. 
myapp -> CommunityToolkit.Maui 9.0.0 -> Microsoft.Maui.Controls.Compatibility (>= 8.0.14) 
 myapp -> Microsoft.Maui.Controls.Compatibility (>= 8.0.7)	myapp	D:\AzureDevOps\myapp	1		

So obviously, this IS an issue.  The packages are loaded directly from nuget into my application so your resolution of "adding the packages directly into the application" is NOT a fix.

I'm stuck now, I cannot work on this at all as it won't let me compile in this state.  I can't remove the useMaui because my test environment will not show up to debug on.  Please fix asap, this has been going on way too long.

I'm on VS2022 version 17.9.7, and the issue is the same as the originally linked bug report above.

---
#### Feedback Bot on 5/15/2024, 06:49 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I think we had a one-time misalignment with the version numbers here. With more recent versions this should all be good. Please try those, if something still doesn't look right, please open a new issue here on the repository. Thanks!
