### ISSUE TITLE
RefreshView IsEnabled not working (iOS/Android)

### ISSUE THREAD

**Issue by dzebas** [dotnet/maui#24228]
### Description

Setting IsEnabled to false does not disable RefreshView as per XAML sample below:

```
    <RefreshView
        Command="{Binding RefreshCommand}"
        IsEnabled=false
        IsRefreshing="{Binding IsHeaderRefreshing}">

    <ScrollView> .. </ScrollView> 

    </RefreshView>
```

### Steps to Reproduce

1. Add page with RefreshView 
2. Set IsEnabled to true
3. RefreshView works fine
4. Set IsEnabled to false
5. RefreshView still works

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by ninachen03** [comment]
The IsEnabled property is set to whether the refresh button is displayed. It has nothing to do with the refresh function. When it is false, it can also refresh. Just the progress spinner does not appear.

**Comment by ninachen03** [comment]
I can not repro this issue on the latest 17.11.0 Preview 7.0( 8.0.80 & 8.0.71)
![Refresh](https://github.com/user-attachments/assets/189175ec-0047-4ac0-911d-a4823c2dd704)

**Comment by dzebas** [comment]
Hi @ninachen03 ,

Thank you for your reply. What I discovered in my case is that if I remove "Command="{Binding RefreshCommand}" then it works as expected, but as soon as I add it back then refresh always works even if disabled.

I've attached sample project, you will notice that setting IsEnabled=False doesn't disable refresh.
[MauiApp2.zip](https://github.com/user-attachments/files/16622434/MauiApp2.zip)

**Comment by ninachen03** [comment]
Thanks for the sample, I have reproduced it on 17.12.0 Preview 1.0(8.0.80 & 8.0.72).

**Comment by PureWeen** [comment]
Hmm not sure why the same code that fixed [this](https://github.com/dotnet/maui/issues/16947) doesn't fix this issue

**Comment by PureWeen** [comment]
related
https://github.com/dotnet/maui/issues/19897

**Comment by LeoJHarris** [comment]
👀
