### ISSUE TITLE
[Bug] FlyoutPage does not render Flyout

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#2422]
### Description
FlyoutPages does not render Flyout on Mac neither iOS
### Steps to Reproduce

1. Download sample that reproduces the error from https://github.com/juanlao/MauiIssues/tree/master/FlyoutDoNotRender
2. Run via dotnet with cli "dotnet build -t:Run -f net6.0-maccatalyst" or "dotnet build -t:Run -f net6.0-ios"  
3. swipe from left to right to make the flyout appear

### Expected Behavior
A flyout with a label appears

### Actual Behavior
An empty view appears 

### Basic Information

- IDE: Visual Studio 2022 Version 17.0.0 Preview 3.1
- Platform Target Frameworks: 
  - iOS:  ✔ ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-preview.7.230) .
  - MacOS:  maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-preview.7.230) installed.
 

### Reproduction Link

https://github.com/juanlao/MauiIssues/tree/master/FlyoutDoNotRender

**Comment by vickyanand25005** [comment]
Hi 

Flyout is not getting rendered in Android as well.

**Comment by kristinx0211** [comment]
can be repro on IOS 15.2. repro sample:
[2422.zip](https://github.com/dotnet/maui/files/8204017/2422.zip)

**Comment by PureWeen** [comment]
AFAICT this is fixed

I tested on MacCatalyst and a flyout appears
