### ISSUE TITLE
[Bug] OnIdiom doesn't identify Mac as Desktop

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2423]
### Description

```
<Grid
        ColumnDefinitions="{OnIdiom Phone='*', Desktop='*,480', Default='*,240'}"
        RowDefinitions="*"
        >
```

This results in the mac app sizing with the Default rather than Desktop values.

### Basic Information

- Version with issue: rc1

**Comment by Redth** [comment]
Fixed by #3763
