### ISSUE TITLE
Problem initializing WindowsForms.BlazorWebView -- The path is empty. (Parameter 'relativeTo')

### ISSUE THREAD

**Issue by mike3sullivan** [dotnet/maui#24234]
### Description

When running an Excel add-in (unmanaged code) that starts a COM add-in (managed code), I can't open a Blazor WebView in a Windows Form (partial stack trace below). This worked in 8.0.7 and 8.0.20 but not since then.

I have tracked it back to maui/src/BlazorWebView/src/WindowsForms/BlazorWebView.cs
lines 170-181.

			// We assume the host page is always in the root of the content directory, because it's
			// unclear there's any other use case. We can add more options later if so.
			string appRootDir;
			var entryAssemblyLocation = Assembly.GetEntryAssembly()?.Location;
			if (!string.IsNullOrEmpty(entryAssemblyLocation))
			{
				appRootDir = Path.GetDirectoryName(entryAssemblyLocation)!;
			}
			else
			{
				appRootDir = AppContext.BaseDirectory;
			}

The problem is that Assembly.GetEntryAssembly() returns null when managed code is lauched from unmanaged code
https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly?view=net-8.0

...AND there is no AppContext because it initiallly launched from unmanaged code, so both values are null. 

Possible solution:
Use Assembly.GetCallingAssembly()?.Location in this case, which does yield a value.

---
error: The path is empty. (Parameter 'relativeTo')

Partial stack trace:
   at System.IO.Path.GetRelativePath(String relativeTo, String path, StringComparison comparisonType)
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.BlazorWebView.StartWebViewCoreIfPossible()
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
...

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.20 SR4

### Affected platforms

Windows

### Did you find any workaround?

no, but could fix by adding extra case when appRootDir  is till null or empty::

Use Assembly.GetCallingAssembly()?.Location in this case, which does yield a value.

**Comment by mike3sullivan** [comment]
I have confirmed the following change fixes my problem:

in maui/src/BlazorWebView/src/WindowsForms/BlazorWebView.cs, 
Line 173 from:
			var entryAssemblyLocation = Assembly.GetEntryAssembly()?.Location;

to:
			var entryAssemblyLocation = Assembly.GetEntryAssembly()?.Location ?? Assembly.GetCallingAssembly()?.Location;

**Comment by Eilon** [comment]
@mike3sullivan alright that's a new one for me! It looks like *maybe* you could set the app's 'base directory' to be a location of your choosing by running some code like this before the BlazorWebView initializes:

```c#
AppContext.SetData("APP_CONTEXT_BASE_DIRECTORY", @"c:\whatever\folder\you\want");
```

And then even though the entry assembly location is null, the code already falls back to calling `AppContext.BaseDirectory`, which I *think* you can override with the code I showed.

Can you try that out and see if that works?

**Comment by mike3sullivan** [comment]
That works perfectly! Thank you!

**Comment by avidesk** [comment]
Just wanted to chime in here and say that I had the same issue in developing a plugin for a CAD software that is loaded via COM. Adding `AppContext.SetData("APP_CONTEXT_BASE_DIRECTORY", @"c:\whatever\folder\you\want");` also worked for this project. Thank you!
