### ISSUE TITLE
Application configuration is invalid (.NET MAUI/Windows)

### ISSUE THREAD

**Issue by E75** [dotnet/maui#24242]
### Description

I have a .NET MAUI App, but I can't debug/build it anymore against Windows, because of an issue in the manifest. Only I don't see anything strange in the manifest files. Mabye I missed something?

Windows 11 22H2 (22621.3880)
Visual Studio 2022 17.10.6

![afbeelding](https://github.com/user-attachments/assets/c58194aa-7a6c-4f91-9025-39645ba8fd28)

Package.Manifest file:
![afbeelding](https://github.com/user-attachments/assets/593b6efa-8556-431d-8501-9c1b67478e34)

App.manifest:
![afbeelding](https://github.com/user-attachments/assets/ac623da0-49b3-468d-ae75-428bd12b2183)

Dotnet workload list:
![afbeelding](https://github.com/user-attachments/assets/3f4fd2d9-4349-4c31-bebd-5faa90671bd4)

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

net8.0-windows10.0.19041.0

**Comment by kevinxufei** [comment]
Hi,@E75  
Could you provide a sample project so that we can reproduce the problem? Thank you!

**Comment by E75** [comment]
@kevinxufei 
This issue cannot be recreated with a new .net maui template (solution). I will clean up my solution and submit it.

**Comment by E75** [comment]
I was able to find the problem.

The version number in the App.manifest was "1.0.0", but it should have been "1.0.0.0". 
Unfortunately, there is not enough logging available to pinpoint this problem right away.

So <assemblyIdentity version="1.0.0" => <assemblyIdentity version="1.0.0.0"

**Comment by jfversluis** [comment]
Perfect, glad you figured it out, thanks for letting us know!
