### ISSUE TITLE
System.IO.FileNotFoundException: '' on App Startup

### ISSUE THREAD

**Issue by munkii** [dotnet/maui#24240]
### Description

The app throws the FileNotFoundException on startup but the file is ''. 

The call stack is when deploying to an Android device is	

> 0x26 in System.Reflection.Assembly.Load	C#
>  	0x55 in System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly	C#
>  	0x4 in System.Resources.ManifestBasedResourceGroveler.InternalGetSatelliteAssembly	C#
>  	0x4D in System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly	C#
>  	0x31 in System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet	C#
>  	0xA4 in System.Resources.ResourceManager.InternalGetResourceSet	C#
>  	0x5A in System.Resources.ResourceManager.GetString	C#
>  	0x12B in System.SR.InternalGetResourceString	C#
>  	0xC in System.SR.GetResourceString	C#
>  	0x5 in System.SR.get_Globalization_cp_1200	C#
>  	0x60 in System.Text.EncodingTable.GetDisplayName	C#
>  	0x4A in System.Text.EncodingTable.InternalGetCodePageDataItem	C#
>  	0xBF in System.Text.EncodingTable.GetCodePageDataItem	C#
>  	0xF in System.Text.Encoding.GetDataItem	C#
>  	0x9 in System.Text.Encoding.get_WebName	C#
>  	0x1 in System.Xml.XmlTextReaderImpl.SwitchEncoding	C#
>  	0x23E in System.Xml.XmlTextReaderImpl.ParseXmlDeclaration	C#
>  	0xC8 in System.Xml.XmlTextReaderImpl.Read	C#
>  	0xFD in Microsoft.Maui.Controls.Xaml.XamlLoader.Load at /_/src/Controls/src/Xaml/XamlLoader.cs:61,5	C#
>  	0x4 in Microsoft.Maui.Controls.Xaml.XamlLoader.Load at /_/src/Controls/src/Xaml/XamlLoader.cs:53,82	C#
>  	0x2C in Microsoft.Maui.Controls.Xaml.XamlLoader.Load at /_/src/Controls/src/Xaml/XamlLoader.cs:49,4	C#
>  	0x7 in Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml<ProjectBreatheApp.Maui.App> at /_/src/Controls/src/Xaml/ViewExtensions.cs:37,4	C#
>  	0xC in ProjectBreatheApp.Maui.App.InitializeComponent at C:\Projects\MB\PilotMobileApplication\ProjectBreatheApp.Maui\obj\Debug\net8.0-android34.0\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\App.xaml.sg.cs:22,4	C#
> 	0x21 in ProjectBreatheApp.Maui.App..ctor at C:\Projects\MB\PilotMobileApplication\ProjectBreatheApp.Maui\App.xaml.cs:14,13	C#
>  	0x1B in System.Reflection.RuntimeConstructorInfo.InternalInvoke	C#
>  	0xF in System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor	C#
>  	0x2D in System.Reflection.MethodBaseInvoker.InvokeWithNoArgs	C#
>  	0x52 in System.Reflection.RuntimeConstructorInfo.Invoke	C#
>  	0x4D in Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor	C#
>  	0x47 in Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext,object>.VisitCallSiteMain	C#
>  	0x63 in Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache	C#
>  	0x52 in Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext,object>.VisitCallSite	C#
>  	0x27 in Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve	C#
>  	0x55 in Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor	C#
>  	0x4A in System.Collections.Concurrent.ConcurrentDictionary<Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier,Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor>.GetOrAdd	C#
>  	0x1A in Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService	C#
>  	0xD in Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService	C#
>  	0x2D in Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService at /_/src/Core/src/MauiContext.cs:72,5	C#
>  	0x2D in Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService at /_/src/Core/src/MauiContext.cs:72,5	C#
>  	0x2A in Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService	C#
>  	0x16 in Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.Maui.IApplication>	C#
>  	0x51 in Microsoft.Maui.MauiApplication.OnCreate at /_/src/Core/src/Platform/Android/MauiApplication.cs:46,4	C#
>  	0x8 in Android.App.Application.n_OnCreate at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Application.cs:1087,4	C#
>  	0x8 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:22,5	C#

There is a very familiar call stack when deploying to iOS device. I have tried Emulator and it is the same issue. If I create a NEw Template MAUI app i do not get this issue.

I have removed everything from our App.xaml. The last line of our code that run before this happens is InitializeComponent

```
 public partial class App : Microsoft.Maui.Controls.Application
 {
     public App()
     {
         this.InitializeComponent();
     }

```

Our App.Xaml looks like this

```
<?xml version="1.0" encoding="UTF-8" ?>
<Application
    x:Class="ProjectBreatheApp.Maui.App"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:ProjectBreatheApp.Maui">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

### Steps to Reproduce

Run app

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

If I untick ALL "Common Language Runtime" exceptions in the "Break When Thrown" settings blade the app will continue to run as if there was no issue.

I don't want to **not** have the App break immediatly on Exceptions. I have tried just unticking FileNotFoundException but that does not stop the app breaking. I assume that is a VS issue.

**Comment by munkii** [comment]
This does not happen with a simple Templated project and our actual MAUI project is an XF port that is massive so I'm not going to be able to produce a small repro project

**Comment by kevinxufei** [comment]
I can repro this issue at Android/iOS platforms on the latest 17.12.0 Preview 1.0(8.0.80 & 8.0.3). But it works fine on Xamarin.Forms. So it is a migration issue from Xamarin to Maui.

**Comment by mattleibow** [comment]
@munkii is it possible to attach a repro project?

The repro by @kevinxufei has one issue where the MainPage was not set, and then another where there was a resource in use on a page that was not found because there were no imported styles.

If you travel deep into the exception messages, it does say this:

![image](https://github.com/user-attachments/assets/fae5dfa4-71d4-484b-b1a9-08fd18d36d3a)

Windows is a bit hard, but I think Android will log directly to the console if you let it continue.

But, attaching a repro sample will help isolate the issue on your side.

**Comment by munkii** [comment]
> @munkii is it possible to attach a repro project?
 
I wish it was but I suspect that'll be our entire solution. I have however spent the morning digging through the Debug output on Android.

> If you travel deep into the exception messages, it does say this:

When you say "travel deep into the exception messages" I'm not sure what you mean or indeed how you got the output from that screenshot.

For some background, I am using Prism for MAUI and the first Exeception I get it is 

```
DryIoc.ContainerException: 'code: Error.UnableToResolveUnknownService;
message: Unable to resolve Prism.Events.IEventAggregator as parameter "eventAggregator" (IsSingletonOrDependencyOfSingleton)
```

This makes little to no sense because if I Ignore that exception and then go into the class that is having IEventAggregator injected into it I can set a breakpoint and once the app is started I can see that instance is just fine.

If I ignore that error I get to FileNotFoundException with a call stack of 

> 0x26 in System.Reflection.Assembly.Load	C#
> 0x55 in System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly	C#
> 0x4 in System.Resources.ManifestBasedResourceGroveler.InternalGetSatelliteAssembly	C#
> 0x4D in System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly	C#
> 0x31 in System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet	C#
> 0xA4 in System.Resources.ResourceManager.InternalGetResourceSet	C#
> 0x5A in System.Resources.ResourceManager.GetString	C#
> 0x12B in System.SR.InternalGetResourceString	C#
> 0xC in System.SR.GetResourceString	C#
> 0x5 in System.SR.get_Globalization_cp_1200	C#
> 0x60 in System.Text.EncodingTable.GetDisplayName	C#
> 0x4A in System.Text.EncodingTable.InternalGetCodePageDataItem	C#
> 0xBF in System.Text.EncodingTable.GetCodePageDataItem	C#
> 0xF in System.Text.Encoding.GetDataItem	C#
> 0x9 in System.Text.Encoding.get_WebName	C#
> 0x1 in System.Xml.XmlTextReaderImpl.SwitchEncoding	C#
> 0x23E in System.Xml.XmlTextReaderImpl.ParseXmlDeclaration	C#
> 0xC8 in System.Xml.XmlTextReaderImpl.Read	C#
> 0xFD in Microsoft.Maui.Controls.Xaml.XamlLoader.Load at /_/src/Controls/src/Xaml/XamlLoader.cs:61,5	C#
> 0x4 in Microsoft.Maui.Controls.Xaml.XamlLoader.Load at /_/src/Controls/src/Xaml/XamlLoader.cs:53,82	C#
> 0x2C in Microsoft.Maui.Controls.Xaml.XamlLoader.Load at /_/src/Controls/src/Xaml/XamlLoader.cs:49,4	C#
> 0x7 in Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml<ProjectBreatheApp.Maui.App> at /_/src/Controls/src/Xaml/ViewExtensions.cs:37,4	C#
> 0xC in ProjectBreatheApp.Maui.App.InitializeComponent at C:\Projects\MB\breathe.breatherm-app\ProjectBreatheApp.Maui\obj\Debug\net8.0-android34.0\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\App.xaml.sg.cs:22,4	C#
> 0x21 in ProjectBreatheApp.Maui.App..ctor at C:\Projects\MB\breathe.breatherm-app\ProjectBreatheApp.Maui\App.xaml.cs:18,13	C#
> 

I do not get the standard "View Details" button so I cannot drill into the Exception's InnerExceptions.


![image](https://github.com/user-attachments/assets/9fbdf5f2-4e1c-49e9-9fab-3f1a1671535f)

**Comment by realrubberduckdev** [comment]
I am also hitting this issue, with the project targeting `net8.0-android` only. In a brand new project and not migration from Xamarin.

Have managed to create a cutdown of my project where I can reproduce the issue. [Check repo](https://github.com/realrubberduckdev/repro24240).
Have added some steps in the readme.

A resolution or any hints on what I could be doing wrong would be much appreciated.

**Comment by mattleibow** [comment]
The break when thrown exception flag may not be what you want. If you throw an exception in a try/catch block, it will still break the app.

For example, in maui we want to test if the windows app is packaged or unpakcaged. The way to do this is to call a specific API and then that throws. We catch it and then return true or false. The exception is both desired and expected. Setting the IDE to break on all exceptions means that you will have all sort of things breaking.

Also, in some cases - probably the file not found on android - it is too expensive for us to first check for the existence of a font file, so we just load it. If it throws, then we know we need to use the alternative extension or something. I forget the layers of implementation, but typically when browsing the Android package contents for a font or image, it is better to assume everything is correct and try load the file. We do log if a file is missing to the debug console. But, I think this particular exception may be OK to have as it is as by design. 

If there is a real error that is being missed, the debug console will log the error from the app. Check the IDE debug console and the android logcat: https://learn.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows

**Comment by munkii** [comment]
@mattleibow sorry to drag this back into the light. I've been unwell. I do understand the cost of checking files rather than just chucking exceptions. I've been relying on the "break when thrown exeption" flag for many many years as I;ve been burnt by local system problems being ignored.

Maybe it is an IDE issue because I don't seem to be able to untick for instance all the know MAUI processing exceptions so that they can be ignored. I know I am in the minority relying on Exceptions being highlighted like this and to be honest that has always surprised me

**Comment by Snsaiu** [comment]
how to fix?

**Comment by Snsaiu** [comment]
I found that this exception might be a bug in vs2022. I used rider for development and it worked fine.
