### ISSUE TITLE
[Bug] Non-Windows csproj hardcoded OutputPath causes build failure

### ISSUE THREAD

**Issue by Daniellled** [dotnet/maui#2425]
### Description
If the developer changes the non-Windows csproj OutputPath to a hardcoded path the build fails.

### Steps to Reproduce

1. Create a new folder to house the project `mkdir testOutputPath`
2. Go into the newly created folder `cd testOutputPath`
3. Create a new maui project `dotnet new maui -n testOutputPath -o src`
4. Navigate to the properties for the non-Windows csproj
![image](https://user-images.githubusercontent.com/83433189/132574110-8a8afddb-c83b-44b0-9265-f877a5a06eaf.png)

5. Create a new folder in the root folder that houses the project named `bin`
![image](https://user-images.githubusercontent.com/83433189/132574510-9baeb46a-a3f5-4069-953b-6e1ee57a86b0.png)

6. Set the output folder to the new `bin` folder
![image](https://user-images.githubusercontent.com/83433189/132574603-dd62909a-1ca8-4474-abde-93f8e23e1fe6.png)

7. Save and Build

### Expected Behavior
Everything compiles and the iOS/Android/Mac files are placed in `d:\testOutputPath\bin\` in the appropriate configuration and platform folder.

### Actual Behavior
The build fails with the error(s)

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	MSB4184	The expression "[MSBuild]::MakeRelative(D:\testOutputPath\src\testOutputPath\D:\testOutputPath\bin\Debug\net6.0-ios\iossimulator-x64\publish\, D:\testOutputPath\src\testOutputPath\..\..\bin\Debug\net6.0-ios\iossimulator-x64\testOutputPath.app\\)" cannot be evaluated. The given path's format is not supported.	testOutputPath	C:\Program Files (x86)\dotnet\packs\Microsoft.iOS.Sdk\15.0.100-preview.6.63\targets\Xamarin.Shared.Sdk.targets	1

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	MSB4184	The expression "[MSBuild]::MakeRelative(D:\testOutputPath\src\testOutputPath\D:\testOutputPath\bin\Debug\net6.0-maccatalyst\maccatalyst-x64\publish\, D:\testOutputPath\src\testOutputPath\..\..\bin\Debug\net6.0-maccatalyst\maccatalyst-x64\testOutputPath.app\\Contents\MonoBundle\)" cannot be evaluated. The given path's format is not supported.	testOutputPath	C:\Program Files (x86)\dotnet\packs\Microsoft.MacCatalyst.Sdk\15.0.100-preview.6.63\targets\Xamarin.Shared.Sdk.targets	1

![image](https://user-images.githubusercontent.com/83433189/132575017-e5a00989-921e-4e58-9216-b14e9a79b7be.png)

### Basic Information

- Version with issue: Preview 6
- Last known good version: Unknown 
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 2.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Template Package: Microsoft.Maui.Templates::6.0.100-preview.6.1003
- Affected Devices:

**Comment by Eilon** [comment]
Hi @Daniellled , this issue should be fixed in the updated preview we released earlier this month. The extra `.WinUI` project is gone and its contents are merged into the main project. We also fixed several other issues with the templates so I think this should no longer be an issue.
