### ISSUE TITLE
[net9.0] Shift platforms specific code from HybridWebView to the handler using Command Mappers

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#24269]
### Description

https://github.com/dotnet/maui/pull/23769#pullrequestreview-2241370886

The code here should use the CommandMapper pattern

https://github.com/dotnet/maui/blob/net9.0/src/Controls/src/Core/HybridWebView/HybridWebView.cs#L122

The best example of this is probably `IScrollView`

There's a request you can make to the `CommandMApper`

![image](https://github.com/user-attachments/assets/2ebe24ab-7543-4c03-87e2-f6bf20cd84d8)

And then the response can come from

![image](https://github.com/user-attachments/assets/afc36bcf-9ac7-419a-9383-155412e429d6)

**Comment by mattleibow** [comment]
See also: https://github.com/dotnet/maui/pull/23769#pullrequestreview-2241370886

**Comment by Eilon** [comment]
I believe this is all done now?
