### ISSUE TITLE
Targeting Android SDK 33 but seen error related to targetSDK=35 (Android.App.MissingForegroundServiceTypeException) at runtime.

### ISSUE THREAD

**Issue by RobbiewOnline** [dotnet/maui#24260]
### Description

Version with bug: Dot9 **Preview 7** (pick list doesn't offer preview 7 at this time).

When building with dotnet 9 preview 7 I had a runtime error Android.App.MissingForegroundServiceTypeException but my project is explicitly set to support Android version as SDK **33** which shouldn't have this limitation.

```
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">33.0</SupportedOSPlatformVersion>
```

Note that the runtime error explicitly references targetSDK=**35** ...

```
Exception has occurred: CLR/Android.App.MissingForegroundServiceTypeException
An unhandled exception of type 'Android.App.MissingForegroundServiceTypeException' occurred in Mono.Android.Runtime.dll: 'Starting FGS without a type  callerApp=ProcessRecord{d41c731 28886:com.devology.myapp.app/u0a371} targetSDK=35'
```

It fails when invoking the line 

```
StartForeground(SERVICE_RUNNING_NOTIFICATION_ID, notification);
```

Within this method...

```
        private void registerForPersistentNotificationService()
        {
            if (!NeedsToRegisterForPersitentNotification)
            {
                Logger.Log(this, $"registerForService started NeedsToRegisterForPersitentNotification:" + NeedsToRegisterForPersitentNotification + " - ignored (already done)");
            }
            else
            {
                Logger.Log(this, $"registerForService started NeedsToRegisterForPersitentNotification:" + NeedsToRegisterForPersitentNotification);

                NeedsToRegisterForPersitentNotification = false;

                if (Build.VERSION.SdkInt >= BuildVersionCodes.O) // Oreo = 8.0+
                {
                    Logger.Log(this, $"registerForService Oreo+ is creating channel");

                    var CHANNEL_ID = "MyApp-BackgroundService";
                    var channel = new NotificationChannel(CHANNEL_ID, "Channel", NotificationImportance.Default)
                    {
                        Description = "Foreground Service Channel"
                    };

                    Logger.Log(this, $"registerForService creating notification channel");

                    var notificationManager = (NotificationManager)GetSystemService(NotificationService);
                    notificationManager.CreateNotificationChannel(channel);

                    Logger.Log(this, $"registerForService creating notification");

                    var nb = new Notification.Builder(this, CHANNEL_ID);
                    setCommonNotification(nb);

                    var notification = nb.Build();

                    // Enlist this instance of the service as a foreground service
                    Logger.Log(this, $"registerForService starting foreground service");
                    StartForeground(SERVICE_RUNNING_NOTIFICATION_ID, notification); ///<<<--- FAILS HERE
                }
                else
                {
                        // Before Oreo
                    Logger.Log(this, $"registerForService pre-Oreo - creating notification");

                    var nb = new Notification.Builder(this);
                    setCommonNotification(nb);

                    var notification = nb
                        .Build();

                    // Enlist this instance of the service as a foreground service
                    Logger.Log(this, $"registerForService starting service");
                    StartForeground(SERVICE_RUNNING_NOTIFICATION_ID, notification);
                }
            }

            Logger.Log(this, $"registerForService completed");

        }
```

To resolve this I changed my service from...

```
namespace MyApp.Droid.Services
{
    [Service(IsolatedProcess = false, Enabled = true, Exported =false)]
    public class BackgroundService : Service, ILocationListener
    {
```

to include ForegroundServiceType = Android.Content.PM.ForegroundService.TypeLocation ...

```
namespace MyApp.Droid.Services
{
    [Service(IsolatedProcess = false, Enabled = true, Exported = false, 
ForegroundServiceType = Android.Content.PM.ForegroundService.TypeLocation)]
    public class BackgroundService : Service, ILocationListener
    {

```

I subsequently needed too add the following permission to my manifest...

```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" />
```

SDK **35** is stricter on foreground services, so I understand this would be required, but why did I get the error when I'm targeting SDK **33**?

Is this the correct place to raise this bug, or a build tool repo?

### Steps to Reproduce

Run an Android project that starts a foreground service that targets SDK 33 and it will provide an error about SDK 35

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Added to the Foreground Service annotation and Android manifest.xml file for permissions related to SDK 35, even though I'm targeting SDK 33.

**Comment by jfversluis** [comment]
I think that value sets the minimum Android version. Does it change anything when you update `TargetFrameworks` to be net8.0-android33.0?

**Comment by RobbiewOnline** [comment]
Thanks @jfversluis.

After previously Googling I ended up interpreting these values as...

**TargetPlatformMinVersion** (21.0) - This line specifies that your .NET MAUI app supports Android devices starting from API level 21 (Android 5.0 Lollipop). The app **will not run on devices with an Android version lower than this**.

**SupportedOSPlatformVersion** (33.0) - This indicates that your app is **designed to work with Android API level 33** (Android 13). This doesn’t mean your app can’t run on devices with higher Android versions; it just means that you haven’t tested or used features introduced in SDKs beyond API level 33. If users run your app on a device with a **newer OS version (e.g., API level 34), it should still work**, but it won’t use any new features or changes introduced in that newer API.

---

To set some context, I rolled back my code permission / foreground service changes (that I thought was related to Android 35) before experimenting as per your last comment 

> "TargetFrameworks to be net8.0-android33.0?"

I tried the **TargetFramework** of `net8.0-android33.0` but one of my libraries stated "is not compatible with net8.0-android33.0" so I tried `net9.0-android33.0` and had the same issue, so I tried 'net8.0-android**34.0**' and that compiled but failed to run with an error about targetSDK=**34**

Exception has occurred: CLR/Android.App.MissingForegroundServiceTypeException
An unhandled exception of type 'Android.App.MissingForegroundServiceTypeException' occurred in Mono.Android.Runtime.dll: 'Starting FGS without a type  callerApp=ProcessRecord{582adc4 21073:com.devology.myapp.app/u0a371} targetSDK=34'

When I tried **net9.0-android34.0** I got this error

```
  MyProject net9.0-android34.0 failed with 1 error(s) (0.0s)
    /usr/local/share/dotnet/sdk/9.0.100-preview.7.24407.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(259,5): error NETSDK1140: 
      34.0 is not a valid TargetPlatformVersion for Android. Valid versions include:
      35.0
```

It seems one of my libraries explicitly says it's compatible with SDK **34**. But using Dotnet 9 I can't set that target framework version for Android and I'm not sure why.

So I think I need a good source that clarifies how to set the TargetFrameworks / TargetPlatformMinVersion / SupportedOSPlatformVersion work with each other and how they map to iOS, Android and Windows min/max/target.

Does that help?

**Comment by jonathanpeppers** [comment]
This doc best explains it:
* https://learn.microsoft.com/dotnet/maui/migration/android-projects?view=net-maui-8.0#changes-to-androidmanifestxml

@RobbiewOnline said:

> SupportedOSPlatformVersion (33.0) - This indicates that your app is designed to work with Android API level 33 (Android 13). This doesn’t mean your app can’t run on devices with higher Android versions;

I don't think this is correct. If you put `SupportedOSPlatformVersion=33`, then you will have `android:minSdkVersion="33"` in the automatically generated manifest. Android won't install the app, unless it is 33 or higher.

 * .NET 8 targets API 34 (TargetPlatformVersion), min is 21 (SupportedOSPlatformVersion)
 * .NET 9 targets API 35, min is 21
 * Generally, don't put `<uses-sdk/>` in your `AndroidManifest.xml` and use the MSBuild properties

Making changes to `AndroidManifest.xml` manually is a way to override the two properties: `TargetPlatformVersion` and `SupportedOSPlatformVersion`. But you'll likely get build warnings. The only case I know of that you would need to do this, is if you're trying to _lower_ `targetSdkVersion` to work around some new Android behavior. In that case, it might be easier to stay on the previous .NET version.

**Comment by RobbiewOnline** [comment]
Thanks @jonathanpeppers 

If I interpret this correctly then the guidance is ...

- Use `TargetFrameworks` to identify the target platform OS / SDK version, i.e. the highest SDK version you've developed & tested for?
- Use an **explicit** version, e.g. `net9.0-android34.0` to lock in the platform SDK version, such that if we update the dotnet SDK / MAUI workload (I'm not sure which one to blame) and unknowingly get a newer SDK version then it's not unintentionally used?
- Use a **generic** version e.g. `net9.0-android` to use the latest and greatest platform SDKs?
- Set the **minimum OS** version via the `SupportedOSPlatformVersion`, i.e. the minimum SDK version you support, (not `TargetPlatformMinVersion` even though the latter sounds semantically correct - it's confusing since TargetPlatform**Min**Version sounds like what SupportedOSPlatformVersion does)!?

Is there a published table of .NET TargetFramework version and how they map to the respective platform min & target values?

Is there anything I can include in the project build debug that'll output the mapped min & target SDK versions for the built platform(s), i.e. 

```
	<Target Name="PrintMauiVersion" AfterTargets="Build">
		<Message Text="GetTargetPlatformIdentifier: $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)'))" Importance="high" />
		<Message Text="Configuration: $(Configuration)" Importance="high" />
		<Message Text="TargetFramework: $(TargetFramework)" Importance="high" />
		<Message Text="Platform: $(Platform)" Importance="high" />
		<Message Text="MauiVersion: $(MauiVersion)" Importance="high" />

		<Message Text="Platform Min: $(XXX)" Importance="high" />
		<Message Text="Platform Target: $(XXX)" Importance="high" />
  </Target>
```

**Comment by jonathanpeppers** [comment]
I don't know what `$(TargetPlatformMinVersion)`; this is something for Windows App SDK. I don't think it was designed by the .NET SDK team.

For Android, I would just always use `net8.0-android` or `net9.0-android` and not put the `$(TargetPlatformVersion)`. It should only move automatically if you transition from `net8.0` -> `net9.0`.

**Comment by RobbiewOnline** [comment]
Thanks @jonathanpeppers - would all dotnet 9 previews & release candidates always point to the same $(TargetPlatformVersion), I believe it changed in Preview 7?  I wouldn't want to be caught out by a runtime issue like the Foreground service Location issue not being picked up at compile time.

I appreciate your help and plan to close this issue, as it's clear I misunderstood these 

SupportedOSPlatformVersion 
TargetPlatformMinVersion 

Perhaps I can provide feedback to a team member so that File > New MAUI projects include a XML header in the solution to provide guidance since it simply has a header (vscode)

```
<!-- Versions -->
```

It would be good to know in that header how they relate to min / max (target) in the relevant OS platforms, especially if only Windows uses TargetPlatformMinVersion.

**Comment by jonathanpeppers** [comment]
> Not all dotnet 9 previews & release candidates point to the same $(TargetPlatformVersion)

We have no control when Google declares the next Android "API stable" or "Platform Stability". At the time they do it, we bump the number in the next .NET 9 Preview (or .NET vNext).

Google's schedule is here:

* https://developer.android.com/about/versions/15/overview

**Comment by Equabyte** [comment]
Meanwhile how to test with SDK 35 and avoid error "35.0 is not a valid TargetPlatformVersion for Android. Valid versions include: 34.0"? This occurs despite using net8.0-android35 in csproj file.

**Comment by jonathanpeppers** [comment]
@Equabyte you would use .NET 9 to use API 35.

**Comment by Equabyte** [comment]
> @Equabyte you would use .NET 9 to use API 35.

Thanks @jonathanpeppers. Just to confirm: .NET 8 is an LTS version with three years support, will there be any way to use SDK 35 at some point later or .NET 9 is truly a must?

**Comment by jonathanpeppers** [comment]
MAUI and all mobile workloads are never LTS:

* https://dotnet.microsoft.com/platform/support/policy/maui

This is the same policy Xamarin had, pretty much.

Mobile moves so quickly, you basically have to keep updating Xcode and the Android SDK each year if you want to submit to app stores.

**Comment by Equabyte** [comment]
> MAUI and all mobile workloads are never LTS:

Thanks @jonathanpeppers, got it. Final question is then: are all .NET 8 fixes being worked on through the various SRs also maintained in .NET 9 so we won't miss any of them?

**Comment by RobbiewOnline** [comment]
@jonathanpeppers I note that the MAUI documentation here https://learn.microsoft.com/en-us/dotnet/maui/supported-platforms?view=net-maui-8.0 indicates that the supported minimum iOS version is iOS 11 or higher is required, but with dotnet9 preview 7 it forces me to set the minimum to 12.2.

'<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">12.2</SupportedOSPlatformVersion>'
