### ISSUE TITLE
[Windows, 9.0 Preview 7] Debugger crashes the app on Windows almost immediately in debug configuration

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#24293]
### Description

When trying to debug my app on Windows in 9.0 Preview 7, the debugger crashes almost immediately, crashing the app as well. Preview 6 works fine.

![image](https://github.com/user-attachments/assets/1e3c2b11-3d37-4b2b-bcef-da2c5beb4f97)

### Steps to Reproduce

1. Try to debug GnollHackM on Windows
2. The debugger crashes almost immediately along with the app

### Link to public reproduction project repository

https://github.com/hyvanmielenpelit/GnollHack

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-preview.6.24327.7

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.22631

### Did you find any workaround?

No. Cannot use the debugger on Windows.

**Comment by janne-hmp** [comment]
The exception does not always seem to be the same:

![image](https://github.com/user-attachments/assets/4486fc5a-ad56-4ec1-a492-1963867dad14)

**Comment by QianaJiao** [comment]
Verified this issue on windows platform, it works fine on 17.12.0 Preview 1.0 (9.0.0-preview.6.24327.7) and get  crashes on 17.12.0 Preview 2.0 [35212.213.main] (9.0.0-preview.7.24408.5)

**Comment by PureWeen** [comment]
@Eilon

**Comment by janne-hmp** [comment]
This seems to be a problem with VS 2022 17.12.0 Preview 1 in my case. On VS 2022 17.11.1, the Maui debugger on Windows works fine.

**Comment by janne-hmp** [comment]
In fact, after more testing, I do get eventually the crash with the debugger also in VS 2022 17.11.1, but not as nearly as fast / immediately as in VS 2022 17.12.0 Preview 1.

**Comment by drasticactions** [comment]
<img width="277" alt="スクリーンショット 2024-08-28 13 31 10" src="https://github.com/user-attachments/assets/f8b146d5-75e2-4996-afb2-5f855d90e275">

Going by the stack, at some point the WinUITap (That's XAML Hot Reload code) is invoked. I'm not sure if that's related to your crash here but that seems suspect. @janne-hmp Could you try turning off XAML Hot Reload to see if it lets it through?

@etvorun Would you have any ideas here?

**Comment by janne-hmp** [comment]
I switched off the following Hot Reload features in Tools > Options:
- Preview Features > MAUI Full Page Hot Reload
- Debugging > General > Enable Hot Reload
- .NET / C++ Hot Reload > Enable Hot Reload
- XAML Hot Reload > Enable XAML Hot Reload

and then the problem seems to be fixed. Thanks a lot!

**Comment by etvorun** [comment]
This seems to be WinUI bug. I created https://github.com/microsoft/microsoft-ui-xaml/issues/9982 to track it

**Comment by PureWeen** [comment]
Closing as external issue
