### ISSUE TITLE
El sdk microsoft.net.sdk especificado no se pudo encontrar

### ISSUE THREAD

**Issue by Nivia17** [dotnet/maui#24297]
El sdk microsoft.net.sdk especificado no se pudo encontrar

Cuando creo cualquier proyecto me sale ese codigo de error y no me carga el explorador de soluciones o carga incompleto. Ya instale la ultima version de .net y el problema persiste. Ademas, ahora estoy intenta realizar el tutorial de inicio de "Tutorial de .NET MAUI: Compilación de la primera aplicación multiplataforma en C#" y aunque instalo el paquete "Desarrollo de.NET Multi-Platform App UI." al momento de crear proyecto nuevo no me aparece entre las plantillas la opcion "Aplicación .NET MAUI". 

He instalado y desinstalado Visual Studio Community varias veces pero el problema persiste.

Esto es la información que aparece en el cmd cuando digito dotnet --info

 C:\Users\nivia>dotnet --info

Host:
  Version:      8.0.8
  Architecture: x86
  Commit:       08338fcaa5
  RID:          win-x86

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jfversluis** [comment]
For some reason you don't have the .NET SDK installed. What options did you select when installing Visual Studio?

You can go to https://dotnet.microsoft.com/download and download the .NET SDK. Once you have do that it should be much better! Hope that helps, let us know.
