### ISSUE TITLE
[Bug] MPNowPlayingInfoCenter.default.playbackState not mapped

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#2429]
### Description
I am trying to work with Control Center in Mac from a Maui service. Seems the property from [PlaybackState](https://docs.microsoft.com/es-es/dotnet/api/mediaplayer.mpnowplayinginfocenter.playbackstate?view=xamarin-mac-sdk-14) in Xamarin.Mac is not ported to Xamarin.MacCatalyst. 
I had developed a native app and a Maui app you can find [here](https://github.com/juanlao/MauiIssues/tree/master/MacOSControlCenter/nativemacplayer).
I have ported to Maui [here](https://github.com/juanlao/MauiIssues/tree/master/MacOSControlCenter/MacControlCenter)

### Steps to Reproduce

1. Run Maui version on mac by running with CLI command dotnet build -t:Run -f net6.0-maccatalyst
2. Press the play button
3. 

### Expected Behavior
Info on Control center should appear and be able to play and pause
### Actual Behavior
Info con control center appears but is not able to play and pause as the events are not received by the app.

### Basic Information
I was hoping the "UpdateIsPlayingOnControlCenter" method on Platforms/MacCatalyst/AudioService.cs will do the magic as is the corresponding port from the native ViewController.Swift UpdateIsPlayingOnControlCenter method. 
But the PlaybackState is not available, so if "GoTodefinition" on "MPNowPlayingInfoCenter" I get this in the metadata: 
![image](https://user-images.githubusercontent.com/603023/132648685-085d2080-5932-431f-bef0-245ff3f94635.png)

That is making me think that property is not mapped in Xamarin.MacCatalyst.

¿Is there some workaround?

**Comment by kristinx0211** [comment]
repro this issue, click the button but is not able to play and pause.
[MauiApp12.zip](https://github.com/dotnet/maui/files/8281702/MauiApp12.zip)

**Comment by jfversluis** [comment]
I'm afraid this might have gone stale and hopefully it has already been fixed. If not, please open an issue on: https://github.com/xamarin/xamarin-macios which is the better place for this one as it's not specific to .NET MAUI.

Thanks!
