### ISSUE TITLE
Erro ao Criar um projeto com o .NET MUI APP

### ISSUE THREAD

**Issue by marfortuna** [dotnet/maui#24291]
Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Erro (ativo)	NU1105	Não é possível encontrar as informações do projeto para 'D:\TrabalMarcia\SENAC\Cursos da SEDU\TesteAndroid\prj_TesteAndroid\prj_TesteAndroid\prj_TesteAndroid.csproj'. Se você está usando o Visual Studio, isso pode ocorrer porque o projeto não está carregado ou não faz parte da solução atual. Portanto, execute uma restauração usando a linha de comando. Do contrário, o arquivo de projeto pode ser inválido ou pode haver destinos obrigatórios para a restauração ausentes.	prj_TesteAndroid.Droid	D:\TrabalMarcia\SENAC\Cursos da SEDU\TesteAndroid\prj_TesteAndroid\prj_TesteAndroid.Droid\prj_TesteAndroid.Droid.csproj	1	

Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Erro (ativo)	NU1105	Não é possível encontrar as informações do projeto para 'D:\TrabalMarcia\SENAC\Cursos da SEDU\TesteAndroid\prj_TesteAndroid\prj_TesteAndroid\prj_TesteAndroid.csproj'. Se você está usando o Visual Studio, isso pode ocorrer porque o projeto não está carregado ou não faz parte da solução atual. Portanto, execute uma restauração usando a linha de comando. Do contrário, o arquivo de projeto pode ser inválido ou pode haver destinos obrigatórios para a restauração ausentes.	prj_TesteAndroid.WinUI	D:\TrabalMarcia\SENAC\Cursos da SEDU\TesteAndroid\prj_TesteAndroid\prj_TesteAndroid.WinUI\prj_TesteAndroid.WinUI.csproj	1	

Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Erro (ativo)	NETSDK1047	O arquivo de ativos 'D:\TrabalMarcia\SENAC\Cursos da SEDU\TesteAndroid\prj_TesteAndroid\prj_TesteAndroid.iOS\obj\project.assets.json' não tem um destino para 'net8.0-ios/ios-arm64'. Verifique se a restauração foi executada e se você incluiu 'net8.0-ios' no TargetFrameworks do projeto. Talvez você também precise incluir 'ios-arm64' no RuntimeIdentifiers do projeto.	prj_TesteAndroid.iOS	C:\Program Files\dotnet\sdk\8.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	266	

Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Erro		A restauração do pacote falhou. Revertendo as alterações no pacote para 'prj_TesteAndroid.Droid'.				

Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Erro	NU1105	Não é possível encontrar as informações do projeto para 'D:\TrabalMarcia\SENAC\Cursos da SEDU\TesteAndroid\prj_TesteAndroid\prj_TesteAndroid\prj_TesteAndroid.csproj'. Se você está usando o Visual Studio, isso pode ocorrer porque o projeto não está carregado ou não faz parte da solução atual. Portanto, execute uma restauração usando a linha de comando. Do contrário, o arquivo de projeto pode ser inválido ou pode haver destinos obrigatórios para a restauração ausentes.	prj_TesteAndroid.Droid	D:\TrabalMarcia\SENAC\Cursos da SEDU\TesteAndroid\prj_TesteAndroid\prj_TesteAndroid.Droid\prj_TesteAndroid.Droid.csproj	1	

Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Aviso (ativo)	WMC1006	Cannot resolve Assembly or Windows Metadata file 'D:\TrabalMarcia\SENAC\Cursos da SEDU\TesteAndroid\prj_TesteAndroid\prj_TesteAndroid\bin\Debug\net8.0\prj_TesteAndroid.dll'	prj_TesteAndroid.WinUI	D:\TrabalMarcia\SENAC\Cursos da SEDU\TesteAndroid\prj_TesteAndroid\prj_TesteAndroid.WinUI\prj_TesteAndroid.WinUI.csproj	1	

Lembro que o meu Visual Studio 2022 já estava instalado, só efetuei a inclusão do .NET MAUI APP e fiz todas as atualizações.

Abraços

**Comment by jfversluis** [comment]
Hi there! With just this information its a bit hard to diagnose what might be going on.
Can you please post a screenshot of your solution in Visual Studio? The error message seems to indicate that the projects are not part of the solution? Is that the case?

Which template did you use to add this? What version of .NET are you using? Thanks!

**Comment by marfortuna** [comment]
![image](https://github.com/user-attachments/assets/66740915-b4fd-4ddc-963f-0a2992a3610f)
![image](https://github.com/user-attachments/assets/770c58f8-e519-4492-b324-bcfe884b753c)
Seguem as imagnes conforme solicitado

**Comment by QianaJiao** [comment]
Hi, @marfortuna This is a known issue, and here is a workaround: 
Right-click the solution node -> Click add existing project -> Select the shared project you just create, select the .csproj, wait for the project to load, and then the error will disappear.
![Animation](https://github.com/user-attachments/assets/0ece930e-3bde-4b50-b687-8e935339887c)

Enjoy your development and let me know if you have any other questions

**Comment by marfortuna** [comment]
Thanks

**Comment by mattleibow** [comment]
I believe this issue was fixed in this PR https://github.com/dotnet/maui/pull/24095
