### ISSUE TITLE
Localizing strings in iOS Info.Plist not working after updating to MAUI 8.0.80

### ISSUE THREAD

**Issue by shobanasuresh** [dotnet/maui#24302]
### Description

After updating to MAUI version 8.0.80 from 8.0.61, the localized permission usage description strings are not appearing in the app.

Could be caused due to below PRs

- https://github.com/dotnet/maui/pull/23835
- https://github.com/dotnet/maui/pull/21350

### Steps to Reproduce

- The app shared in below public repo adds lproj folders to iOS platform for InfoPlist.strings localization as per https://learn.microsoft.com/en-us/previous-versions/xamarin/ios/app-fundamentals/localization/#strings-file-locations
- Set iOS device language to French
- Run app
- Click the button displayed in the app
- Observe that the location permission usage description string is displayed in English
- Update the app's csproj to use MAUI version 8.0.61 instead of 8.0.80
- Run App
- Observe that the location permission usage description string is displayed in French as expected based on the string set in https://github.com/shobanasuresh/MauiTestApp/blob/main/Resources/iOS/fr.lproj/InfoPlist.strings

**8.0.80**
![8 0 80](https://github.com/user-attachments/assets/c1eaca7d-8c39-4e6c-aace-8407718a5b64)

**8.0.61**

![8 0 61](https://github.com/user-attachments/assets/29241e22-15df-4729-b6b0-f0c58855a5db)

### Link to public reproduction project repository

https://github.com/shobanasuresh/MauiTestApp

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.61 SR6.1

### Affected platforms

iOS

**Comment by jfversluis** [comment]
Thanks so much for the detailed report and reproduction! Much appreciated! That makes it a lot easier to look at this problem.

Yeah, the thing is for 8.0.80 it actually finally works correct and earlier you had to implement workarounds. While we did our best to make all scenarios work, unfortunately that is not always possible.

I looked at your project and could make it work by removing this: https://github.com/shobanasuresh/MauiTestApp/blob/main/MauiTestApp.csproj#L59-L65

And then copying the lproj files to `Platforms/iOS/Resources` which is the way it "should".

If you do want to keep your files where they are, change it like this:

```xml
   	<ItemGroup Condition="$(TargetFramework.Contains('-ios')) == true">
		<BundleResource Include="Resources\iOS\*.lproj\InfoPlist.strings" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
```

Note that I added the `LogicalName` node. This will remove the `Resources\iOS` prefix. Without it, it will end up in the `iOS/*.lproj` folder in the app bundle and that is why its not picked up by the app.

You can remove this, as its not needed (anymore):

```xml
   	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
   	   	<IPhoneResourcePrefix>Resources;Resources\iOS</IPhoneResourcePrefix>
   	</PropertyGroup>
```
