### ISSUE TITLE
Issue with iOS Application Icon: App Store Publishing Failed - AppIcon Missing (Asset Validation Error)

### ISSUE THREAD

**Issue by mrsathish24** [dotnet/maui#24300]
### Description

Hello!

I've successfully generated the IPA file for my iOS app, but when attempting to distribute it using the Transporter tool, I've been stuck for days due to an asset validation error:

"Asset validation failed (90704): Missing app icon. Include a large app icon as a 1024 by 1024 pixel PNG in the asset catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps can't be submitted for review...."

I've tried various workarounds, such as switching between SVG and PNG formats, creating an asset group with multiple file sizes, and even simplifying the implementation, but nothing seems to work.

I've also looked into the error ID #22421 but couldn't find a workaround that resolves the issue.

I'm using Visual Studio Code Version 1.92.2 (Universal) on a MacBook Pro running macOS Sonoma 14.5 with Xcode 15.4. The build process completes without issues, and my .csproj file appears to be correctly configured. I'm not sure if this is a genuine issue or a configuration error in my project.

Could you please assist us in resolving this issue or suggest an alternative way to publish the app to TestFlight? Thanks!

<img width="706" alt="Archives" src="https://github.com/user-attachments/assets/520bb8ae-1101-405c-81b2-3d6b623caaa2">

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.80 SR8

### Affected platforms

iOS, macOS

### Affected platform versions

.NET 8, Xcode 15.4

**Comment by Sathish-kumar94** [comment]
Hi,

Thanks for the suggestions, but I have already tried all the solutions mentioned in the similar issues you provided, including issues #11124, #22421, #9067, #17764, and #9133. Unfortunately, none of them have resolved the problem for me.

I would appreciate any further assistance or alternative solutions to help resolve this issue. Thank you!

**Comment by jfversluis** [comment]
What are the entries in your csproj file in regard to the icon? Can you maybe post the contents here and make sure you redact any sensitive values? This has worked before with a previous release?

**Comment by Sathish-kumar94** [comment]
Hi @jfversluis 

Below is our .csproj file:

<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net8.0-ios</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>Mobile</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		
		<ApplicationTitle>iAMS Mobile</ApplicationTitle>
		<ApplicationId>com.acsys.acsysmobilemaui</ApplicationId>
		<ApplicationIdGuid>XXXXXX</ApplicationIdGuid>
		
		<ApplicationDisplayVersion>1.1.1</ApplicationDisplayVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
	</PropertyGroup>
	<PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
		<ApplicationVersion>200240812</ApplicationVersion>
		
		<MauiAndroidExcludeJar>androidx.collection.collection-jvm.jar</MauiAndroidExcludeJar>
	</PropertyGroup>
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
		<ApplicationVersion>2.0.024.0812</ApplicationVersion>
		
	</PropertyGroup>
	<PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
		<AndroidKeyStore>True</AndroidKeyStore>
		<AndroidSigningKeyStore>moacsys.keystore</AndroidSigningKeyStore>
		<AndroidSigningKeyAlias>key</AndroidSigningKeyAlias>
		<AndroidSigningKeyPass>123456</AndroidSigningKeyPass>
		<AndroidSigningStorePass>123456</AndroidSigningStorePass>
	</PropertyGroup>
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<UseInterpreter>true</UseInterpreter> 
		<CodesignKey>Apple Distribution: Acsys Technologies Ltd. (24K9VYD2A5)</CodesignKey>
		<CodesignProvision>AcsysMobileMAUIAppStore</CodesignProvision>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-android|AnyCPU'">
		<MtouchLink>None</MtouchLink>
		<AndroidLinkMode>None</AndroidLinkMode>
		<AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidMessageHandler</AndroidHttpClientHandlerType>
		<JavaMaximumHeapSize>1G</JavaMaximumHeapSize>
		<AndroidPackageFormat>apk</AndroidPackageFormat>
		<AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
		<AndroidUseAapt2>true</AndroidUseAapt2>
		<AndroidManifest>AndroidManifest.xml</AndroidManifest>
		<AndroidDexTool>d8</AndroidDexTool>
		<EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
		<MtouchLink>None</MtouchLink>
		<MtouchFloat32>False</MtouchFloat32>
		<AndroidLinkTool>r8</AndroidLinkTool>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
		<CreatePackage>false</CreatePackage>
		<MtouchDebug>true</MtouchDebug>
		<CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
		<BuildIpa>False</BuildIpa>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
		<CreatePackage>false</CreatePackage>
		<CodesignKey>Apple Development: sathishkumar muthusamy (F66HZ6XBT7)</CodesignKey>
		<CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
		<MtouchLink>None</MtouchLink>
		<CodesignProvision>AcsysMobileMAUDevelopment</CodesignProvision>
		<BuildIpa>False</BuildIpa>
	</PropertyGroup>
	<ItemGroup>
		
		<MauiIcon Include="Resources\AppIcon\appicon.png" BaseSize="128,128" Resize="false" />
		
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#ffffff" BaseSize="256,256" />
		
		<MauiImage Include="Resources\Images\*" />
		<MauiFont Include="Resources\AppIcon\Fonts\*" />
	</ItemGroup>
</Project>

Here's the content of the iOS Info.plist file:


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>MinimumOSVersion</key>
	<string>11.0</string>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
	</array>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UIUserInterfaceStyle</key>
	<string>Light</string>
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleDarkContent</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>XSAppIconAssets</key>
	<string>Assets.xcassets/appicon.appiconset</string>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>Required to enable BLE functionalites</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>Required to enable BLE functionalites</string>
	<key>NSCameraUsageDescription</key>
	<string>Requires to access your camera for Open/Close image verification</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>This app needs access to the photo gallery for picking photos and videos.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Required to Access Photo Library</string>
	<key>NSFaceIDUsageDescription</key>
	<string>Acsys Mobile requires Face ID to unlock app</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Acsys Mobile requires GPS to get site location</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Acsys Mobile requires GPS to get site location</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Acsys Mobile requires GPS to get site location</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
		<string>audio</string>
	</array>
	<key>CFBundleIdentifier</key>
	<string>com.acsys.acsysmobilemaui</string>
	<key>CFBundleDisplayName</key>
	<string>iAMS Mobile</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>mailto</string>
	</array>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>XIEnableUITracking</key>
	<false/>
	<key>NSMicrophoneUsageDescription</key>
	<string>We need access to the microphone to play sound for notifications.</string>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
</dict>
</plist>

This configuration has worked with previous releases, so I'm unsure if the issue lies within the project setup or elsewhere. Any guidance or suggestions would be greatly appreciated!

**Comment by jfversluis** [comment]
Other linked solutions seem to indicate that setting a background color on the MauiIcon helped, did you try that?

In your app bundle can you see the icons there? Is the 1024x1024 one actually missing?

**Comment by Sathish-kumar94** [comment]
Yes, I included the `ForegroundFile` and `Color` properties in the `MauiIcon`, as shown in the `.csproj` file:

`<MauiIcon Include="Resources\AppIcon/appicon.png" ForegroundFile="Resources\AppIcon/appiconfg.svg" Color="#000000" BaseSize="128,128" Resize="false" />`

However, this did not resolve the issue. I also resized the image to 1024x1024 and added it to the bundle, but the problem persists.

**Comment by jfversluis** [comment]
You say as shown in the csproj file, but what you pasted here is not what you pasted to be above in the csproj file, so... which is it? 😄

**Comment by Sathish-kumar94** [comment]
Hi @jfversluis, Yes, I had previously added the properties to the `MauiIcon` and tested them, but I didn’t include that in the `.csproj `file I shared earlier.

Could you please guide me on what exactly I should inspect within the contents of the generated IPA file?

I've attached the Package Contents file for your reference. Please take a look and guide me on how to resolve this issue. Thanks!

[Payload-Mobile.zip](https://github.com/user-attachments/files/16668924/Payload-Mobile.zip)

**Comment by mrsathish24** [comment]
Hi @jfversluis ,

Just following up on my previous message. I attached the Package Contents file for your review. Could you please guide me on what I should inspect in the generated IPA file to resolve the issue?

Thanks for your assistance!

**Comment by mrsathish24** [comment]
Hi @jfversluis,

I wanted to follow up on my previous message as I'm still encountering the same error. I’ve thoroughly checked the icon-related settings, and everything appears to be in order, but I’m still unsure how to resolve this issue. Our customers are eagerly awaiting a solution. I’ve attached the Package Contents file for your review. Could you please provide guidance to help resolve this problem?

Thank you for your assistance!

**Comment by mrsathish24** [comment]
Dear @jfversluis,

I wanted to let you know that I've identified and resolved the issue. The problem was related to the `<TargetiOSDevice> `key values in the `.csproj.user` file. After removing these settings, I was able to successfully upload the app to TestFlight. Interestingly, these key values were added two years ago, and the issue only surfaced recently.

Here's the setting that caused the problem:
```
<TargetiOSDevice>&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"&gt;
&lt;plist version="1.0"&gt;
&lt;dict&gt;
    &lt;key&gt;device&lt;/key&gt;
    &lt;dict&gt;
        &lt;key&gt;architecture&lt;/key&gt;
        &lt;string&gt;ARMv6, ARMv7, ARMv7s, ARM64&lt;/string&gt;
        &lt;key&gt;model&lt;/key&gt;
        &lt;string&gt;iPhone14,5&lt;/string&gt;
        &lt;key&gt;os-version&lt;/key&gt;
        &lt;string&gt;17.6.1&lt;/string&gt;
        &lt;key&gt;os&lt;/key&gt;
        &lt;string&gt;iOS&lt;/string&gt;
    &lt;/dict&gt;
&lt;/dict&gt;
&lt;/plist&gt;
</TargetiOSDevice>
```
Thankfully, everything is working now. Thanks for your support!
