### ISSUE TITLE
[Enhancement] Add ONLY in-code layout creation (or easiest from code)

### ISSUE THREAD

**Issue by Mondonno** [dotnet/maui#2433]
## Summary

Add only in-code layout creation instead of creating XAML files.
It will be cleanest and the projects will look better on code side.
Also this feat. request calls to create more readable and easier in-code layout creation.

## API Changes

There are no needed API changes, just instead of downloading the layout and other things from XAML do it from code side.

## Intended Use Case

It can be usefull. This will not require any external files. Just when a widget is declared, add a method that renders it, easliy.

**Comment by rogihee** [comment]
Have you seen [https://github.com/communitytoolkit/Maui.Markup](url)?

**Comment by hartez** [comment]
@Mondonno All of the layouts and controls in MAUI can already be created entirely from C# code; XAML is not required for any of the features. 

Can you elaborate more on what you are trying to do that you cannot do from code?

**Comment by Mondonno** [comment]
@hartez Hi! I can do everything with XAML, but in my opinion, it is better to have all in-code, it is easier to imagine all project structer, instead of jumping around XAML files. Flutter very nicley resolved this.

@rogihee Yes, i saw. Is it builted into MAUI?

**Comment by hartez** [comment]
@Mondonno You can also do everything from code; XAML is not required to build a UI in MAUI.
