### ISSUE TITLE
Change default BlazorWebView local address from 0.0.0.0 to something safer

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#24363]
Several browsers either already have, or will soon start disabling support for using `0.0.0.0` as an address for the platform WebView. BlazorWebView uses that address because it's never a valid IP address, and never requires DNS resolution, so assuming it *works*, it's both fast and safe.

However, some browsers already don't support it, and others soon won't.

We should find a new address to use - ideally one that can work on all platforms.

Some ideas:

* Use another syntactically valid IP address that isn't an actual address (let's just say 0.0.0.1 or something)
   * Pro: No DNS (has this actually been a problem in any recent browser?), similar to what already worked
   * Con: Is it just buying us time until it also gets disabled? 
* Use `localhost` (possibly with a port?)
   * Pro: It's simple and should always work
   * Con: It could prevent other things from working, such as if the machine has something else running on `localhost`, then JS code in the webview couldn't access it
* Use a fake/random address, kind of like what browser extensions do
   * Pro: Will never conflict with anything
   * Con: Gotta make sure it works. Possible DNS concerns (see above)

I kind of feel like the DNS issue, even if it was a problem at some point, has long since not been an issue, because it seems that many other systems have used 'fake' addresses and they're presumably fine.

If anyone else has thoughts on these, please let us know.

**Comment by MarkusRodler** [comment]
I can remember that we had problems with SVGs and using 0.0.0.0. They just won't show up if you link to them in a separate .svg file. With localhost, everything works fine but it is not possible to load them with 0.0.0.0. (Ugly) workaround was to insert them all in to the index.html but that will not scale very well in the future. So I think the best solution is to use localhost.

**Comment by Eilon** [comment]
@MarkusRodler oh that's weird that SVG specifically has an issue with it. I'm kind of leaning towards using `localhost` anyway. It's what we did in a patch to make iOS/MacCatalyst 18 beta and newer work anyway. And it seems to be what other hybrid-ish/webview-based systems use.

I think the only downside I can think of for using localhost is in the case where you happen to also have an app running on port 80 on your local system - then JS code inside the WebView couldn't access it directly. But I suspect that's astonishingly rare. For local dev you're almost always using some random-ish port (rather than port 80).

**Comment by MarkusRodler** [comment]
@Eilon If I researched it correctly, it isn't a SVG problem directly. It's a security feature from the browser 😄 
And I can agree with the other point. I think it is the best way.

**Comment by Redth** [comment]
@Eilon we could also make this a bit configurable?  What if we at least allowed specifying a different port than the default 80 we would use?

We could allow for configuring the host too?  In that sense we could use a default which we know generally works, but still provide a way to change things if it conflicts with those rare cases.

**Comment by Eilon** [comment]
> @Eilon we could also make this a bit configurable? What if we at least allowed specifying a different port than the default 80 we would use?
> 
> We could allow for configuring the host too? In that sense we could use a default which we know generally works, but still provide a way to change things if it conflicts with those rare cases.

Yeah that's been asked a few times. While I think there are many valid cases to pick a very custom name, it also can lead people down a path of using Blazor/HybridWebView as a regular webview, which it most certainly is not. So things like trying to use web flow interactions with payment/login sites is likely to cause pain. But, it's still a nice feature to have, and can also serve as an escape hatch.

**Comment by sonali-vaghela** [comment]
@Eilon Is there any other way without localhost?
I am using Sci Chart JS in my blazor hybrid application.
Now If I host my application on localhost, Sci Chart understand that it is developer user (due to localhost) and stops working for the end user.
And I also required fixed hostname for my sci chart licensing. So, I can not use any random address.

**Comment by MarkusRodler** [comment]
Well other frameworks work the same way with localhost and would have the same problem. Maybe it's an option to address this issue within Sci Chart Js?

**Comment by sonali-vaghela** [comment]
@MarkusRodler Yes, In it's licensing there is like "localhost" = developer account and for that it will allow only in one user's pc.
So either we need to go for advance licensing that allow unlimited localhost user which is a bit costlier option.
That we don't want to go.
So do we add some other domain/address except 0.0.0.0 & localhost that works permanently?

**Comment by Eilon** [comment]
Maybe just using a 'fake' address is safe then? It's what some other systems do in similar cases. They use a name like `scheme://technology-name/<path>`, so we could do `scheme://blazor/<path>` and that is unlikely to conflict with anything? I think the only thing that could conflict with is if your computer's name happens to be `blazor` *and* you're hosting something on port 80 *and* need to access it 😁

**Comment by MarkusRodler** [comment]
@Eilon Unfortunately, the SVG problem is not solved now, which I consider very uncomfortable. Wouldn't it be an option to make it configurable so that you can also use localhost?

**Comment by Eilon** [comment]
@MarkusRodler because this is late in .NET 9 we were aiming for a safe fix that would prevent BlazorWebView from being completely broken on multiple platforms.

For the SVG issue was it broken on all platforms or just some? We might be able to come up with a workaround for that.

**Comment by MarkusRodler** [comment]
@Eilon I understand that and yes it's broken on all plattforms. By the way, reproducing this is very simple. Put any svg in the wwwroot and link it in the html with svg tag and use href: `<svg><use href="path/to/svg.svg"></use></svg>`
If it is changed to an img tag, then the image is displayed, but can no longer be styled. If it is loaded under localhost, it will also show up with svg tag. There are workarounds for this, but unfortunately they are not satisfactory.

**Comment by lord-executor** [comment]
As the loopback address space is actually 127.0.0.0/8, so a 24-bit subnet, couldn't we pick one of them basically at random, like 127.251.241.239? Since, as I understand it, the traffic is intercepted anyway, it shouldn't matter _which_ loopback address it is using and as I've basically _never_ seen any loopback address except for 127.0.01 used in the wild, I doubt that this would ever create a conflict.

**Comment by JLfub** [comment]
@Eilon Reading SVGs from an image folder via href did not work for me on Android and iOS either, only when working with the img tag, but as @MarkusRodler mentioned, they can no longer be styled.

**Comment by gerneio** [comment]
I see this marked to be included in [.NET 9.0 GA](https://github.com/dotnet/maui/milestone/67) milestone/release. Can we get it be included with next release of .NET 8 workloads as well ([.NET 8 SR9.2](https://github.com/dotnet/maui/milestone/68) or [.NET 8 SR10](https://github.com/dotnet/maui/milestone/69)). I'm assuming `.NET 8 SR9.2` is scheduled to be dropped pretty soon.
