### ISSUE TITLE
DisplayPromptAsync not working in iOS 17.4

### ISSUE THREAD

**Issue by pedrohdezj** [dotnet/maui#24368]
### Description

The DisplayPrompt crash app when a call in codebehind a ContentView, only iOS 17.4, compile with Xcode 15.4, Xcode 15.2 not problem

Code example crash

`var code = await Shell.Current.CurrentPage.DisplayPromptAsync("titulo", "message");`

Relation with bug DisplayPromptAsync not working in iOS 17.4 #21131

### Steps to Reproduce

Create a button inside a ContentView
Inside ContentView in codebehind call a 

`var code = await Shell.Current.CurrentPage.DisplayPromptAsync("titulo", "message");`

App crash

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

17.4

**Comment by jfversluis** [comment]
You specified .NET 8.0.3 as your current version, is that correct? There have been service releases. If you use that, does that work? You will need those for Xcode 15.4 compatibility. If you can create a reproduction project we can rule these things out. Thanks!

**Comment by MisterAcoustic** [comment]
I am not the original poster, but I see this issue as well.

IOS 17.5.1, VS 17.10.6, MAUI workload 8.0.71, ios workload 17.5.8018.

My code is equivalent to:
string result = await Application.Current.MainPage.DisplayPromptAsync("blah", "blah");

The result of the call is nothing at all - it fails silently in Release mode. In debug mode, it doesn't reach the next line of code. I added a try/catch block, and no exception occurs.

I don't have a repro project for you, but I would expect that if you drop that line into a sample project, that is all that you would need to see the issue.

**Comment by danilt2000** [comment]
I tested this in IOS 17.6.1 without Xcode for me everything work stable

**Comment by ninachen03** [comment]
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
