### ISSUE TITLE
[Bug] Multiple reports of templates missing from Visual Studio 2022 latest preview

### ISSUE THREAD

**Issue by adegeo** [dotnet/maui#2436]
The install docs seem to be out of date; something is missing. Can someone from the product team please review these issues and the documentation for accuracy?

Doc: https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation

Issue: dotnet/docs-maui#150
Duplicate issues: dotnet/docs-maui#151 dotnet/docs-maui#152

**Comment by jfversluis** [comment]
The Docs have been updated in the meantime so I'm assuming this is no longer an issue.

If there are issues with the docs, please report them in the appropriate place. Find the Feedback heading at the bottom of the page and select This Page to report something about the Docs and This Product for something about .NET MAUI :)

![image](https://user-images.githubusercontent.com/939291/140490353-cf3c73fd-4949-4fb1-9a34-cee57d7cafbe.png)
