### ISSUE TITLE
Editor control on Windows uses CR as line ending

### ISSUE THREAD

**Issue by andrekoehler** [dotnet/maui#24361]
### Description

When I enter two lines of text into an Editor control like this one:
`<Editor Text="{Binding SomeString}" />`
SomeString will use a single CR (0x0D) as the line separator.
On my Windows machine.
I expected Environment.NewLine (== CR LF) or LF, but not CR, which should only ever be used on MacOS.

Running on German Windows 11 23H2

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

Use a value converter for the string binding to replace the line endings:
```
class LineBreakConverter : IValueConverter
{
    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        if (value is string crlf)
        {
            return crlf.ReplaceLineEndings("\r");
        }
        return value;
    }

    public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        if (value is string cr)
        {
            return cr.ReplaceLineEndings();
        }
        return value;
    }
}
```

**Comment by ninachen03** [comment]
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by jfversluis** [comment]
Could you please show us how you update the value? Are you sure there are no "weird" line endings in the text that you try to set it to?
