### ISSUE TITLE
didReceiveIncomingPushWithPayload does not work with closed or background application

### ISSUE THREAD

**Issue by GuilhermeHeibelTech** [dotnet/maui#24374]
### Description

didReceiveIncomingPushWithPayload  não funciona com aplicativo fechado ou em segundo plano, configurado info.pList, adicionada a funcionalidade em appDelegate para solicitações voip aguardando receber um push via didReceiveIncomingPushWithPayload  

### Steps to Reproduce

```csharp
  public class PushRegistryDelegate : PKPushRegistryDelegate
  { 
  [Export("pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:")]
   [Foundation.Preserve(Conditional = true)]
   public async override void DidReceiveIncomingPush(PKPushRegistry registry, PKPushPayload payload, string type, Action completion)
   {
  
       var userInfo = payload.DictionaryPayload;
  .....
  }
}
```

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

**Comment by jaosnz-rep** [comment]
@GuilhermeHeibelTech Could you provide us with a sample project so we can investigate it? Looking forward to your reply!
