### ISSUE TITLE
[net9.0] Blazor MAUI App hangs during back navigation because of disconnect code

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#24407]
### Description 

With NET9.0 we now call "DisconnectHandler" by default on all components of a page when they are popped from the stack. 

It looks like this code is now causing the UI to hang

![image](https://github.com/user-attachments/assets/526e6b61-1d4e-47d9-85a0-4e2a32c73ad2)

### Reproduction

- Deploy a to Windows our Maui.Samples project from the MAUI repository 
- Navigate to the Blazor Sample
- wait for it to load
- click the back button
- app hangs

**Comment by malsabi98** [comment]
Is there a workaround for this? I'm having this issue in BlazorWebView I'm targeting 8.0.82 SR8.2. The issue happens In Windows, I tested on Android its working fine.

**Comment by malsabi** [comment]
Is there a workaround for this? I'm having this issue in BlazorWebView I'm targeting 8.0.82 SR8.2. The issue happens In Windows, I tested on Android its working fine.

**Comment by malsabi** [comment]
@PureWeen  @Eilon @mkArtakMSFT  If possible please to add this into the SR9.2 release.

**Comment by malsabi** [comment]
I also tested on iOS the issue is there as well. My app hangs forever.

**Comment by malsabi** [comment]
@Eilon Maybe this information will help, but the reason why its working on Android is because I have set this:

`AppContext.SetSwitch("BlazorWebView.AndroidFireAndForgetAsync", isEnabled: true);`

If i removed it and tested again the app will hang just like Windows and iOS.

**Comment by Eilon** [comment]
Thanks, will investigate this.
