### ISSUE TITLE
.Net 8 MAUI Memory Leaks after navigating to multiple pages and then navigating to root page.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24409]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-8-MAUI-Memory-Leaks-after-navigatin/10729562)._

---
[severity:I'm unable to use this version]
.Net 8 MAUI Memory Leaks after navigating to multiple pages and then navigating to root page.

We are seeing that due to memory leaks there is increase in memory usage each time we navigate from one page to another page and when we pop to root page then to the memory usage is not decreased. We have migrated app from Xamarin Forms to MAUI. This has impacted our app release plan. Any help from you would be appreciated.

---
#### Feedback Bot on 8/22/2024, 06:33 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattsetaro** [comment]
After some debugging, I was able to find the following code which is causing a memory leak:
```
Page.cs
...
internal void OnAppearing(Action action)
{
    if (_hasAppeared)
    action();
    else
    {
    EventHandler eventHandler = null;
    eventHandler = (_, __) =>
    {
	    this.Appearing -= eventHandler;
	    action();
    };
    
    this.Appearing += eventHandler;
    }
}
```

Page.Appearing is not being unsubscribed properly:
![Screenshot 2024-08-28 at 10 26 23 AM](https://github.com/user-attachments/assets/97e06fb1-f027-412d-a3c6-e98288250914)

**Comment by mattleibow** [comment]
Is this still happening in the latest releases? I am testing the code in main and I am not seeing these types of numbers (I got 3 max) and I am using this sample code: https://github.com/mattsetaro/MauiMemoryLeak/tree/main/MauiApp1

In that sample, I tried 8.0.3, 8.0.41 and 8.0.82 and was not really able to see any change. If I ran it as is, the size grew from 3 "mb" to 10 "mb" and then the GC collected it all. And, if I put this code in the OnAppearing that was logging, I see that it never changes even after running for a minute:

```cs
GC.Collect();
GC.WaitForPendingFinalizers();
await Task.Yield();
```

But, I was able to repro it in the test code:

```cs
public class ShellNavigatingTests : ShellTestBase
{
  readonly ITestOutputHelper _testOutputHelper;
  
  public ShellNavigatingTests(ITestOutputHelper testOutputHelper)
  {
	  _testOutputHelper = testOutputHelper;
  }
  
  [Fact]
  public async Task MemoryLeak()
  {
	  Routing.RegisterRoute("page1/page2", typeof(DummyPage));
	  Routing.RegisterRoute("page1/page2/page3", typeof(DumberPage));
  
	  var shell = new TestShell(
		  CreateShellItem(shellSectionRoute: "page1")
	  );
  
	  int ctr = 0;
	  while (ctr < 5_000)
	  {
		  GC.Collect();
		  GC.WaitForPendingFinalizers();
		  await Task.Yield();
  
		  await shell.GoToAsync("page1/page2/page3");
		  Assert.True(shell.CurrentPage is DumberPage);
  
		  await shell.GoToAsync("..");
		  Assert.True(shell.CurrentPage is DummyPage);
  
		  if (++ctr % 500 == 0)
		  {
			  _testOutputHelper.WriteLine("Total memory: " + GC.GetTotalMemory(false).ToString("N0"));
		  }
	  }
  }
  
  class DummyPage : Page
  {
  
  }
  
  class DumberPage : Page
  {
  
  }
}
```

**Comment by jaosnz-rep** [comment]
I can repro this issue at Windows platform on the latest 17.12.0 Preview 1.0(8.0.82 & 8.0.80).
Sample project:
[MauiApp8 (1).zip](https://github.com/user-attachments/files/16926752/MauiApp8.1.zip)

**Comment by PureWeen** [comment]
> I can repro this issue at Windows platform on the latest 17.12.0 Preview 1.0(8.0.82 & 8.0.80). Sample project: [MauiApp8 (1).zip](https://github.com/user-attachments/files/16926752/MauiApp8.1.zip)

This sample isn't really correct. 

This sample is pushing pages onto the stack so those pages aren't ever going to collect unless they are popped off the stack

for example, if I pop all the pages then the memory collects

![Image](https://github.com/user-attachments/assets/d43369aa-da29-4219-afc2-618fecfe0320)
