### ISSUE TITLE
App does not want to publish to ios not even simulator

### ISSUE THREAD

**Issue by IQTechSolutions** [dotnet/maui#24400]
### Description

Application works perfectly in android debug released and published to app store. App also builds and publishes to apple store but throw and exception on startup. I have narrowed it down to the following issues, that has to do the the linker.

The deserialization constructor for the type System.Collections.Generic.KeyValuePair... contains parameters with null values. This might happen because the parameter names have been trimmed in ILLINK. I have tried every trimming setting, but nothing works. This only happens on ios. Can someone please help me out with this, been banging my head for weeks now
![Screenshot 2024-08-23 132216](https://github.com/user-attachments/assets/a376eff5-8dea-400b-9108-5ff19c8489a3)

### Steps to Reproduce

Create maui app 
add mudblazor nuget pagkage, use mudcolor anywher
 and publish to ios simulator

### Link to public reproduction project repository

https://github.com/NeuralTech-Group/NeuralTechDNA

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.80 SR8

### Affected platforms

iOS

### Affected platform versions

All iOS

### Did you find any workaround?

No Workaround found yet

**Comment by kevinxufei** [comment]
Hi, @IQTechSolutions 
I'm sorry I don't have permission to open your project. Can you open the permission and upload again, thank you!

**Comment by IQTechSolutions** [comment]
I solved the issue thank you very much, I ended up just turning off linking.

**Comment by jfversluis** [comment]
Thanks for letting us know, Glad you figured it out!
