### ISSUE TITLE
Windows: Entry with right aligned text keeps text jumping to the left during editing

### ISSUE THREAD

**Issue by jbe2277** [dotnet/maui#24405]
### Description

After updating MAUI from 8.0.71 to 8.0.80 we see that our Entry with right aligned text keeps text jumping to the left during editing:

![grafik](https://github.com/user-attachments/assets/6b6f43ee-4872-41a3-8234-c1b6182b3511)

### Steps to Reproduce

1. Create a new MAUI 8 App in Visual Studio
2. Replace `MainPage.xaml` with the following code:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
    <ScrollView>
        <VerticalStackLayout Padding="30,0" Spacing="25" MaximumWidthRequest="500">
            <Entry Placeholder="Enter text here" HorizontalTextAlignment="End"/>

            <Entry Placeholder="Enter text here" HorizontalTextAlignment="End"/>
            
            <Button x:Name="CounterBtn" Text="Click me" Clicked="OnCounterClicked" />
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
```
3. Set the MAUI version in `MauiApp.csproj`
```
<MauiVersion>8.0.80</MauiVersion>
```
4. Start the App on Windows and enter a text in an entry. You will see that the text jumps to the left as shown in the screenshot.

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.71 SR7.1

### Affected platforms

Windows

**Comment by PureWeen** [comment]
@jbe2277 I've tested your repro back to 8.0.3 and I'm seeing the same behavior there as well

![image](https://github.com/user-attachments/assets/6a7024c8-706d-488e-a840-560c0227292f)

**Comment by jbe2277** [comment]
@PureWeen This worked with MAUI 8.0.71 - it is a regression bug. Please, see my screenshot below:

![grafik](https://github.com/user-attachments/assets/41fd2e36-2e4b-4fb5-972b-4d025a657c4e)

**Comment by jaosnz-rep** [comment]
I can repro this issue at Windows platform on the latest 17.12.0 Preview 1.0(8.0.80), and it used to work in 8.0.72, 8.0.71 and 8.0.3.
<img width="526" alt="8 0 3" src="https://github.com/user-attachments/assets/1af469f9-4409-428f-8741-ef9bc1086ca4">
