### ISSUE TITLE
ContentPage unload event fires, if another page is opened, not if at unload

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24410]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ContentPage-unload-event-fires-if-anoth/10728499)._

---
Maui project, (android emulator) newest VS version 17.11.1

The contentPage unload event fires, if another page is opened.
Yes the page disappears. Xamarin makes it right to fire the disappearing event.
But Maui fires the unload event, if the page is not unloaded.

Repro steps:

- Create a new maui app.
- Add a handler to the mainpage Unload event.
- Set a break point to this eventhandler.
- Add another page to the project.
- Add a button to mainpage that code behind opens the other page.
- The break point is active without unloading the mainpage.

---
#### Feedback Bot on 8/21/2024, 06:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
The unloaded event fires when something is removed from the visual tree

https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.visualelement.unloaded?view=net-maui-8.0

We're just monitoring platform events for when the view is removed. Maybe try using Navigating/Navigated events instead?
