### ISSUE TITLE
App crash in Release Mode when binding ItemSource in CollectionView

### ISSUE THREAD

**Issue by GhostDestroyex** [dotnet/maui#24416]
### Description

Hello Maui team,
Hello, I am using visual studio 2022 and I have a movie application project that has a search engine and when something is typed it makes a call to an API to return the search results, which I assign to the ItemSource property of the CollectionView.
When I do that process in Release mode the application crashes.
The property that I bind is an ObservableCollection, I have also tried using a ListView but the same thing happens to me.

This is my workload list:
![image](https://github.com/user-attachments/assets/f14e3858-d4a7-487c-b9fd-b645e1b58b85)

### Steps to Reproduce

Create a File > New .Net MAUI App
Add a CollectionView
Set the ItemsSource property of the CollectionView binding in Xaml
Set release mode

### Link to public reproduction project repository

https://github.com/GhostDestroyex/MoviesShowApp

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by Serebie** [comment]
I tested your project and it works fine for me after changing 2 small things.

In your .csproj I changed the package references for `Microsoft.Maui.Controls` and `Microsoft.Maui.Controls.Compatibility` from this
```
<PackageReference Update="Microsoft.Maui.Controls" Version="8.0.60" />
<PackageReference Update="Microsoft.Maui.Controls.Compatibility" Version="8.0.60" /> 
```
to this
```
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.60" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.60" /> 
```

And in your Home.xaml file there is a the style `SelectedResultStyle` which is accidentally  using x:Name instead of x:Key.

After changing these 2 things, I could run your app in release mode.

**Comment by GhostDestroyex** [comment]
I've tested the solution and it already works correctly, thank you very much, I am closing the issue.  Thanks @Serebie
