### ISSUE TITLE
[Bug] [Android] WebView Not Filling Contents of RefreshView unless Width or HeightRequested set.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2442]
### Description
![image](https://user-images.githubusercontent.com/898335/132773025-9129c874-0446-4262-ac89-b0ceddda5485.png)

![image](https://user-images.githubusercontent.com/898335/132773090-b8a62fed-f31e-437f-a808-77a3af5c7abb.png)

When using a webview on Android, the width and height of the view are -1 unless you set a `WidthRequested` or `HeightRequested`. Even if you also set VerticalOptions or HorizontalOptions to try and expand it, it won't change.

On WinUI it works correctly and fills the entire page without setting additional values.

### Steps to Reproduce

Create a new page and set its contents to be RefreshView with a webview. Check how it works on Android Vs. WinUI.

```
<RefreshView RefreshColor="Green">
            <WebView x:Name="FeedWebView" Source="https://www.google.com"/>
</RefreshView>
```

**Comment by wenwen60** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
