### ISSUE TITLE
[Bug] Blazor css isolation does not work in WinUI application

### ISSUE THREAD

**Issue by StrgX** [dotnet/maui#2446]
### Description

Using VS 2022 preview and MAUI preview 7.

The css isolation does not work for the WinUI project. Adding a scoped css file in the main project does not create a link in the WinUI project. Adding the link manually via the "content" tag shows the file, however the isolation still does not work in WinUI.

Same issue (but closed): https://github.com/dotnet/aspnetcore/issues/35195

### Steps to Reproduce

1.  Create new Maui-Blazor app in VS using the '.NET Maui Blazor App (Preview)' template.
2.  In the main app/pages folder add a 'Counter.razor.css' file.
3.  Check the WinUI pages folder - the *.css file is not added

**Comment by Eilon** [comment]
Hi @StrgX this was indeed not working in preview 7, but should be working as of this week's updated preview release: https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/

I'll confirm it's working, and if so, I'll close the issue.

**Comment by Eilon** [comment]
I confirmed this does work starting with the latest preview. But, depending on how you add the CSS file, there is one extra step, which is to set the CSS file's `Build Action` to `Content` (the default might be `MauiCss`):

![image](https://user-images.githubusercontent.com/202643/133837967-eec5d662-30d9-4222-ad13-2a1cbbba6a9e.png)
