### ISSUE TITLE
BindableObjects not getting collected causing memory leak, android

### ISSUE THREAD

**Issue by GBarbieri-IPS** [dotnet/maui#24478]
### Description

I have a pretty large application that we migrated over from xamarin to MAUI. Seems that after navigating through our app x~40 times we end up with a memory leak causing the application to hang. I've collected memory dumps at the time of the crash which I'll post here. 

![image (1)](https://github.com/user-attachments/assets/81712273-48c6-4e55-85d1-16dc0048fd10)
![image (2)](https://github.com/user-attachments/assets/7526ce4f-f78b-409b-90a1-5e1a53225a13)
![image](https://github.com/user-attachments/assets/94af4a9c-80e3-4958-93f2-c97031f4861b)

I can see that MIcrosoft.Maui.Controls.SetterSpecificiityList and BindablePropertyContext seem to be eating up a bunch of our resources as dead objects. I was wondering if there was a way to get these bindings to be cleaned up by the GC as I believe these seem to be the cause of our memory leak? I've tried traversing through the visual tree, removing handlers, setting binding context to null, setting the styles to null, unapplying bindings upon disposal. Can't see to get any progress on resolving this issue.

### Steps to Reproduce

1. Navigating through 5 pages of our app
2. Navigating back to root
3. Repeat 22 times
4.  Notice application hangs during OnAppearing or OnPageDisappearing

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No workaround yet.

**Comment by Toomas75** [comment]
I had problems with SetterSpecificiityList when used BindableLayout and loaded itemtemplate in non ui thread.

**Comment by GBarbieri-IPS** [comment]
@Toomas75 Were you seeing similar issues as to what I mentioned? If so how did you get around it? Thanks :)

**Comment by Toomas75** [comment]
> @Toomas75 Were you seeing similar issues as to what I mentioned? If so how did you get around it? Thanks :)

Just checked my history. It wasn't views leaking problem as you experience.
