### ISSUE TITLE
[Bug] Cannot deploy Maui. Net Blazor App to Windows, files missing from build

### ISSUE THREAD

**Issue by AndrewBryanScott** [dotnet/maui#2447]
### Description
Cannot get the MAUI.Net Blazor application to run on windows, or deploy the app to windows.

### Steps to Reproduce

1. create a new .NET MAUI Blazor App in Visual Studio 2022 (v 17.0.0 preview 3.1)
2. add missing RuntimeIdentifiers to Android/ios/mac project, this will allow you to run it on an actual Android Device.
<RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
4. Set the startup project to the <projectname>.WinUI
5. clean and rebuild the solution in debug mode.
6. right-click WinUI project and select deploy while in debug mode. (run does not work and is known)
7. error is thrown
8.  Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP1700: The recipe file "C:\XXXXXXXX\MauiBlazorApp1.WinUI\bin\Debug\net6.0-windows10.0.19041\win-x64\MauiBlazorApp1.WinUI.build.appxrecipe" does not exist. You may need to build your project.	MauiBlazorApp1.WinUI

also if creating this missing file to check if this would help, it then complains its needs a missing AppxManifest.xml. also rebuilding does not create the missing files.		

### Expected Behavior
selecting deploy should deploy the app to windows so it can be used.

### Actual Behavior
files needed to complete the deployment are not being created by the build process in debug or release mode.

### Basic Information

- Version with issue: 
- Last known good version:
- IDE: Visual Studio 2022 (v 17.0.0-pre.3.1)
- Platform Target Frameworks: 
  - UWP: .netFramework  6.0.100-preview.7.21379.14
- Nuget Packages:
standard from project.
microsoft.aspnetcore.components.webview.maui\6.0.100-preview.7.1345
microsoft.extensions.fileproviders.embedded\6.0.0-preview.7.21378.6
microsoft.maui.dependencies\6.0.100-preview.7.1345
microsoft.projectreunion\0.8.1
microsoft.projectreunion.foundation\0.8.1
microsoft.projectreunion.interactiveexperiences\0.8.1
microsoft.projectreunion.winui\0.8.1

### Workaround

none yet

**Comment by Eilon** [comment]
Hi @AndrewBryanScott , this issue is likely fixed in the updated preview we released earlier this month. The extra `.WinUI` project is gone and its contents are merged into the main project. We also fixed several other issues with the templates so I think it's worth trying the new preview to confirm it works for you.

You can read some specific notes about the Windows / WinUI experience in this blog post: https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/
