### ISSUE TITLE
Changing view size/layout/position does not update the shadow

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#24476]
### Description

I have some code:

```xaml
<Border
    Grid.Row="1"
    Grid.ColumnSpan="2"
    VerticalOptions="End"
    Margin="0,0,0,24"
    HeightRequest="52"
    StrokeThickness="0"
    Background="#EEEEEE"
    StrokeShape="RoundRectangle 26"
    MaximumWidthRequest="300"
    HorizontalOptions="Center">
    <Border.Shadow>
        <Shadow
            Offset="0,25"
            Opacity="0.3"
            Radius="25"/>
    </Border.Shadow>
```

There are some items in the border, and if I change (for example) the HorizontalOptions to Fill or Center, the shadow just moves but n=does not reflect the bounds.

This is noticeable during hot reloading. 

However, this appears to be working fine if I change the contents - such as hid/show - or other content things.

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/4ddce0bb-c665-41a5-96f8-0137bd51370d)

![image](https://github.com/user-attachments/assets/78b36b62-8dd6-4c4c-a3a6-64766adc2f24)

### Link to public reproduction project repository

https://github.com/mattleibow/scorecard-day-nft-marketplace/tree/issues/shadow

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by kubaflo** [comment]
Hi @mattleibow I think this Pr might fix it: https://github.com/dotnet/maui/pull/24561
