### ISSUE TITLE
[Windows, 9.0 Preview 7] Every quit and exit method throws an exception

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#24486]
### Description

I've been trying to exit my .NET MAUI 9.0 Windows application cleanly, but it seems that every exit or quit method throws an exception (at least so in .NET MAUI 9.0 Preview 7). The exceptions are different in each case, though. I tried with and without `MainThread.BeginInvokeOnMainThread` in the case this were a threading issue, but the results are the same either way.

`Microsoft.Maui.Controls.Application.Exit()`:

![image](https://github.com/user-attachments/assets/0d472615-f6e5-4916-96b9-f233e3710615)

`Application.Current.Quit()`:

![image](https://github.com/user-attachments/assets/9af10a12-30f7-4b1f-a7d1-9a27d386b0b3)

`Environment.Exit(0)`:

![image](https://github.com/user-attachments/assets/1b8d827b-a25d-44c0-954b-82bdc575e894)

What is the appropriate way to close a MAUI Windows app when the user wants to close it, e.g., by pressing a Quit button on the app's UI?

### Steps to Reproduce

1. Build and start GnollHackM for Windows in Debug mode
2. Press Exit on the MainPage.
3. Any of the aforementioned exit or quit calls throws an exception

### Link to public reproduction project repository

https://github.com/hyvanmielenpelit/GnollHackMAUIEasyBuild

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

No

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.22631

### Did you find any workaround?

No, but the exception crashes the app, so it sort of does the trick, but SentrySDK reports the crash so we get a huge number of crash exceptions reported.

**Comment by janne-hmp** [comment]
Interestingly, this seems to happen only when the app is in full screen mode. The exception is not thrown in WindowedMode. Full screen mode is implemented via:

```
                        bool maximizeWindow = !Preferences.Get("WindowedMode", false);
                        if(maximizeWindow)
                        {
                            window.ExtendsContentIntoTitleBar = false;
                            switch (appWindow.Presenter)
                            {
                                case Microsoft.UI.Windowing.OverlappedPresenter overlappedPresenter:
                                    overlappedPresenter.SetBorderAndTitleBar(false, false);
                                    overlappedPresenter.Maximize();
                                    break;
                            }
                        }

```

I did also test this with default Maui app in full screen mode, and at least `Environment.Exit(0)` does not work in full screen there, similar to my app. However, by contrast, `Application.Current.Quit` seems to work without exception, so there may be more than just the full screen mode in my app's setup that causes the crash.

**Comment by CathyZhu0110** [comment]
Hi @janne-hmp I couldn't repro this issue using the default MAUI app in full screen mode (not repro for both `Environment.Exit(0)` and `Application.Current.Quit` ) on VS 17.12 P3 with MAUI: 9.0.0-rc.2.24503.2 & 9.0.0-preview.7.24407.4. Can you share your simple sample that can repro this issue?

**Comment by jfversluis** [comment]
Hey @janne-hmp! 

Would you be able to provide a more concise reproduction?

I appreciate your involvement with this and how you report issues, however the one thing that proves a bit difficult for us is that your linked repository is huge and that makes it hard to determine all the moving parts for a potential issue. That in turn, makes it hard to determine if something is happening in the .NET MAUI SDK or maybe something in your own app code.

Could we please ask you to lift the code involved into a separate project so we can look at only the code that shows this issue and not all the rest of your amazing game. That will make it easier for us to look at this and potentially fix it faster, but also it might make more clear to you what you are doing in your code and how to change it or workaround it.

That would be really amazing and helpful, thank you! Also for this one in this case, there has been a couple of new releases, also let us know if this is still happening in the latest version. Thank you!

**Comment by janne-hmp** [comment]
Hi, let me look into this soon. I could even make an easily buildable copy of the Windows version of the game in another repository. I've been travelling a bit lately, so haven't been able to work on this for the past couple of weeks, but should have more time pretty soon.

**Comment by janne-hmp** [comment]
Hi, since I don't know where the problem comes from, I now created a version of GnollHack that should build somewhat straightforwardly: https://github.com/hyvanmielenpelit/GnollHackMAUIEasyBuild. All you need to is to follow the instructions in the README file to unzip the sound bank files from Releases to the right folders (too big to be directly in the repository), after which the project should more or less build immediately, at least for Windows, but also most likely for Android and iOS. I had to run `dotnet restore` to get things working first, but this is noted in the instructions

I will also update this issue's reproduction repository. Let me know if you run into any problems.

**Comment by CathyZhu0110** [comment]
> Hi, since I don't know where the problem comes from, I now created a version of GnollHack that should build somewhat straightforwardly: https://github.com/hyvanmielenpelit/GnollHackMAUIEasyBuild. All you need to do is to follow the instructions in the README file to unzip the sound bank files from Releases to the right folders (too big to be directly in the repository), after which the project should more or less build immediately, at least for Windows, but also most likely for Android and iOS. I had to run `dotnet restore` to get things working first, but this is noted in the instructions
> 
> I will also update this issue's reproduction repository. Let me know if you run into any problems.

Hi @janne-hmp Thanks for providing a version which can easily build, I can debug succeeded now, while I still couldn't repro this issue on VS 17.12 P3 with MAUI: 9.0.0-rc.2.24503.2 & 9.0.0-preview.7.24407.4. Can you try again and see whether you can still repro using latest build?

**Comment by CathyZhu0110** [comment]
This issue has been verified and can repro (To repro, need to disable xaml hot reload) using Visual Studio 17.12.0 Preview 5(9.0.0-rc.2.24503.2, [9.0.0-preview.7.24407.4), while works fine on 9.0.0-preview.6.24327.7 and latest nightly build [9.0.10-ci.net9.24553.1](https://github.com/dotnet/maui/wiki/Nightly-Builds)
