### ISSUE TITLE
Picker to Entry selections causes keyboard to cover low inputs

### ISSUE THREAD

**Issue by Axelmdez** [dotnet/maui#24496]
### Description

In my iOS app, we have a large amount of pickers and entry inputs. 

When a picker is selected, without tapping ‘Done’, selecting an input that is lower on the screen than the normal keyboard height can cause the keyboard to cover it. At this point users cannot see the text that is being typed, even if they try to scroll to the bottom. 

Users can only hide the keyboard by pressing return or the dismiss keyboard button and then tap another input. Keyboard displaying will work this time, letting the page scroll up until the input is visible.

_Tapping on an entry that causes the keyboard to display and the page to scroll, and then tapping on another entry/picker after that, will work. It’s only the other way around that is an issue._

Also shown in the video
Tapping high placed entries works fine until you need to scroll to the bottom to select another entry. The keyboard is still hiding the bottom rows of inputs, and you can’t scroll down far enough to see the additional inputs.
Users won’t know there are more inputs on screen unless they know to hide the keyboard every time. 

Though I’ve seen other fixes/problems reported about keyboards covering inputs, this one may be closer to issue #23901.
Unfocused events not firing when clicking on other controls seems like a theme here. 

https://github.com/user-attachments/assets/a8ed5e18-4430-4aff-8516-a9a9d57f8234

In Xamarin, our app lets us scroll and see the bottom inputs, it also auto scrolls up if the newly selected entry is below the keyboard. 

first reproduced on maui version: 

ios                        17.5.8018/8.0.100      VS 17.11.35201.85, VS 17.10.35122.118 

tested on simulator iPadOS 17.5 10th gen and on 8th gen hardware

finally retested on this version and result is the same

ios                        17.5.8018/8.0.100      SDK 8.0.400, VS 17.11.35201.85, VS 17.10.35122.118
maui-ios                   8.0.71/8.0.100         SDK 8.0.400

### Steps to Reproduce

**Picker to Entry issue**

1. Create a new Maui app.
2. Fill the main page with pickers and entry inputs
3. Select a picker on the lower half of screen
4. don't click done
5. Select an entry on the lower half of screen.

expected result: keyboard appears, and page scrolls up to reveal the entry that is focused.

actual result: keyboard appears, and page does not scroll. 

**Low Inputs Cut off Issue** 

1. Create a new Maui app.
2. Fill the main page with pickers and entry inputs
3. Select a picker on the top part of the page (such that you have to scroll down wards to see the bottom)
4. don't click done
5. try to select an entry on the lower part of the page

expected result: page scrolls to reveal the inputs at the bottom of the page.

actual result: keyboard covers all inputs below it, page does not let you keep scrolling 

### Link to public reproduction project repository

https://github.com/Axelmdez/MauiAppKeyboardTests

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPadOS 17.5

**Comment by Axelmdez** [comment]
#20200 seems like its the same as what I was calling "Low Inputs Cut off Issue" and is getting added in SR9 possibly? If so we can ignore it here.

The other ones are close to my main issue but you are actually able to scroll still. This is more about an issue with inputs being covered after switching between controls.

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.6.14(build413)(8.0.80 & 8.0.3 & 7.0.101). Can repro on iOS platform.

**Comment by tj-devel709** [comment]
Thank you for bringing this case up to us! I have addressed the changes in a PR coming soon!
