### ISSUE TITLE
Using Binding with OnIdiom throw this exception on release mode only: InitializeComponent () System.InvalidCastException: Unable to cast object of type 'Microsoft.Maui.Controls.Binding' to type 'System.Boolean'.

### ISSUE THREAD

**Issue by MahmoudAlEssawi** [dotnet/maui#24500]
### Description

 IsVisible="{OnIdiom Default={Binding EditingMode,Converter={StaticResource InvertedBoolConverter}},Phone=False}" 
Throw this exception on release mode Only:
InitializeComponent () System.InvalidCastException: Unable to cast object of type 'Microsoft.Maui.Controls.Binding' to type 'System.Boolean'.

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

WINDOWS 10.0.19045, Android 12

### Did you find any workaround?

Remove OnIdiom

**Comment by jaosnz-rep** [comment]
@MahmoudAlEssawi  Can you provide us with a sample project so we can investigate further? Looking forward to your reply!

**Comment by kdotdk** [comment]
Same problem exists in windows with OnPlatform using bindings.
E.g.
`CanBeDismissedByTappingOutsideOfPopup="{OnPlatform Android=True, WinUI={Binding CanBeDismissedByTappingOutsideOfPopup}, Default=True}"`
