### ISSUE TITLE
ContentLayout="Left,5" ignored when no space after the comma

### ISSUE THREAD

**Issue by softlion** [dotnet/maui#24538]
### Description

`ContentLayout="Left,5"` does not work properly, no space is added between the icon and the text.

But `ContentLayout="Left, 5"` does work properly.

### Steps to Reproduce

That issue is on any Button, on both iOS and Android (at least).

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

### Did you find any workaround?

Add a space after the comma, and magivally it works !

**Comment by ninachen03** [comment]
This issue has been verified using latest Visual Studio 17.12.0 Preview 1.0 (8.0.82) & 17.11.2（7.0.101). Cannot repro on Android  platform.
[MauiApp48.zip](https://github.com/user-attachments/files/16836057/MauiApp48.zip)

![left](https://github.com/user-attachments/assets/6503d5e9-bd09-4363-a039-b0a94154984e)
