### ISSUE TITLE
Undefined symbols for architecture arm64 Error, while using Native libraries in MAUI iOS

### ISSUE THREAD

**Issue by v-npadhy** [dotnet/maui#24536]
### Description

We are working on MAUI.iOS migration project from Xamarin.iOS.

In Xamarin.iOS we have used few iOS Native libraries(.a files). The Xamarion.iOS project was working fine. But when we used those native libraries in MAUI.iOS project we are getting build errors.

IOS Version: 17.6.1

Device Type: Real Device
[Visual Studio Enterprise 2022 for Mac.ini.txt](https://github.com/user-attachments/files/16815995/Visual.Studio.Enterprise.2022.for.Mac.ini.txt)

<PropertyGroup>
<MtouchExtraArgs>--cxx -gcc_flags "-lstdc++ -L $(MSBuildProjectDirectory)/lib/debug -lc++ -lz -lcrypto -lssl -lxml2 -lmat -lsqlite3 -lmip_dotnet -lmip_upe_and_protection_sdk_static -lresolv -framework CoreTelephony -framework Foundation -framework CoreFoundation -framework CoreServices -framework Security -framework IOKit -framework UIKit -framework SystemConfiguration -framework Network -force_load $(MSBuildProjectDirectory)/lib/debug/libcrypto.a -force_load $(MSBuildProjectDirectory)/lib/debug/libssl.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmat.a -force_load $(MSBuildProjectDirectory)/lib/debug/libsqlite3.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmip_dotnet.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmip_upe_and_protection_sdk_static.a" --registrar:static --aot=nopagetrampolines,ntrampolines=40960,nrgctx-trampolines=40960,nrgctx-fetch-trampolines=256,ngsharedvt-trampolines=4096,nimt-trampolines=4096 --optimize=-remove-dynamic-registrar</MtouchExtraArgs>
<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
</PropertyGroup>

<ItemGroup>
<NativeReference Include="......\AzIP-Viewer\RPMSGViewer\iOS\App\lib\Debug\libcrypto.a">
<Kind>Static</Kind>
  <SmartLink>True</SmartLink>
</NativeReference>
<NativeReference Include="..\..\..\AzIP-Viewer\RPMSGViewer\iOS\App\lib\Debug\libmat.a">
  <Kind>Static</Kind>
  <SmartLink>True</SmartLink>
</NativeReference>
<NativeReference Include="..\..\..\AzIP-Viewer\RPMSGViewer\iOS\App\lib\Debug\libmip_dotnet.a">
  <Kind>Static</Kind>
  <SmartLink>True</SmartLink>
</NativeReference>
<NativeReference Include="..\..\..\AzIP-Viewer\RPMSGViewer\iOS\App\lib\Debug\libmip_upe_and_protection_sdk_static.a">
  <Kind>Static</Kind>
  <SmartLink>True</SmartLink>
</NativeReference>
<NativeReference Include="..\..\..\AzIP-Viewer\RPMSGViewer\iOS\App\lib\Debug\libsqlite3.a">
  <Kind>Static</Kind>
  <SmartLink>True</SmartLink>
</Nativeeference>
<NativeReference Include="..\..\..\AzIP-Viewer\RPMSGViewer\iOS\App\lib\Debug\libssl.a">
  <Kind>Static</Kind>
  <SmartLink>True</SmartLink>
</NativeReference>
</ItemGroup>

Build Error:

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:

Undefined symbols for architecture arm64:

  "_initGenericErrorDefaultFunc", referenced from:

      l002 in libmip_upe_and_protection_sdk_static.a(xml_helper.o)

  "_nw_path_get_status", referenced from:

      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_is_constrained", referenced from:

      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_is_expensive", referenced from:

      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_monitor_cancel", referenced from:

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::~NetworkInformation() in libmat.a(NetworkInformationImpl.mm.o)

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_monitor_create", referenced from:

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_monitor_set_queue", referenced from:

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_monitor_set_update_handler", referenced from:

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_monitor_start", referenced from:

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_uses_interface_type", referenced from:

      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)

  "_res_9_dn_expand", referenced from:

      mipns::DnsServerResolverImpl::lookup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libmip_upe_and_protection_sdk_static.a(dns_server_resolver_impl_static.obj)

  "_res_9_nclose", referenced from: (com.microsoft.rightsmanagement.mobile.viewer.ios)

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

No

### Relevant log output

```shell
Build Error:

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:

Undefined symbols for architecture arm64:

  "_initGenericErrorDefaultFunc", referenced from:

      l002 in libmip_upe_and_protection_sdk_static.a(xml_helper.o)

  "_nw_path_get_status", referenced from:

      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_is_constrained", referenced from:

      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_is_expensive", referenced from:

      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_monitor_cancel", referenced from:

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::~NetworkInformation() in libmat.a(NetworkInformationImpl.mm.o)

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_monitor_create", referenced from:

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_monitor_set_queue", referenced from:

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_monitor_set_update_handler", referenced from:

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_monitor_start", referenced from:

      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)

  "_nw_path_uses_interface_type", referenced from:

      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)

  "_res_9_dn_expand", referenced from:

      mipns::DnsServerResolverImpl::lookup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libmip_upe_and_protection_sdk_static.a(dns_server_resolver_impl_static.obj)

  "_res_9_nclose", referenced from: (com.microsoft.rightsmanagement.mobile.viewer.ios)
```

**Comment by rolfbjarne** [comment]
Are you building for device or for the simulator? If you're building for the simulator, I suspect you're running into the fact that we're building for arm64 for the simulator, and your .a files probably don't contain arm64 code for the simulator.

There are a couple of potential fixes:

1. Don't build for arm64 in the simulator. You can do this by adding `<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>` in the csproj. Note that you'll have to add a condition/configuration to only run this when you target the simulator, otherwise it will interfere when trying to run on a device.
2. Rebuild the native library and create an xcframework bundle that supports all architectures, including arm64 for the simulator. Here's Apple's documentation about how to create an xcframework: https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle: https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle (there are also numerous other guides online).

If you're seeing this problem when building for device, then please attach an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) so that we can see exactly what's going on during the build.

**Comment by v-npadhy** [comment]
> Are you building for device or for the simulator? If you're building for the simulator, I suspect you're running into the fact that we're building for arm64 for the simulator, and your .a files probably don't contain arm64 code for the simulator.
> 
> There are a couple of potential fixes:
> 
> 1. Don't build for arm64 in the simulator. You can do this by adding `<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>` in the csproj. Note that you'll have to add a condition/configuration to only run this when you target the simulator, otherwise it will interfere when trying to run on a device.
> 2. Rebuild the native library and create an xcframework bundle that supports all architectures, including arm64 for the simulator. Here's Apple's documentation about how to create an xcframework: https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle: https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle (there are also numerous other guides online).
> 
> If you're seeing this problem when building for device, then please attach an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) so that we can see exactly what's going on during the build.

@rolfbjarne 
1. I am building on real device only not simulator.
2. The same native libraries are working fine in Xamarin in both device and simulator. So obviously arm64, x64 architectures will be there.

Its not something we are using the native libraries for this first time. Its a migration work, migrating code base from Xamarin to MAUI. 

What other possibilities could be there,so that I can investigate in details.

**Comment by rolfbjarne** [comment]
> 2\. The same native libraries are working fine in Xamarin in both device and simulator. So obviously arm64, x64 architectures will be there.

Note that arm64 for the simulator and arm64 for device are not the same and they're not interchangeable. Additionally, it's not possible to create a .a archive with both versions of arm64 (which is why Apple created the xcframework format).

FWIW Xamarin didn't support arm64 in the simulator, so this was never a problem there - while it's the default build architecture when building for the simulator with .NET on an arm64 CPU.

> What other possibilities could be there,so that I can investigate in details.

It's hard to say without investigating the errors.

You can start investigating by looking at the first symbol the build complains about:

```
Undefined symbols for architecture arm64:

"_initGenericErrorDefaultFunc", referenced from:

  l002 in libmip_upe_and_protection_sdk_static.a(xml_helper.o)
```

and try to find the answer to a few questions:

* Where is this symbol defined?
* If you can't find out where it's defined, then the next question becomes: how did this work in the Xamarin version?
* If you can find it, the next question is: why isn't the corresponding native library included in the build?

You can inspect native libraries from the command line using the `nm` tool, typically `nm libNative.a | grep <symbol>` will tell you if the native library references or provides said symbol.

**Comment by v-npadhy** [comment]
@rolfbjarne We found the route cause of the issue. But didn't found the solution.

For system Frameworks in Xamarin.IOS we have used  MTouchExtraArgs, and it was working fine. But same MTouchExtraArgs is not working in MAUI.iOS. All the system frameworks are already defined in MtouchExtraArgs which are causing undefined symbol error in MAUI.

We are using MAUI iOS with .NET 8.

<MtouchExtraArgs>--cxx -gcc_flags "-lstdc++ -L $(MSBuildProjectDirectory)/lib/debug -lc++ -lz -lcrypto -lssl -lxml2 -lmat -lsqlite3 -lmip_dotnet -lmip_upe_and_protection_sdk_static -lresolv -framework CoreTelephony -framework Foundation -framework CoreFoundation -framework CoreServices -framework Security -framework IOKit -framework UIKit -framework SystemConfiguration -framework Network -force_load $(MSBuildProjectDirectory)/lib/debug/libcrypto.a -force_load $(MSBuildProjectDirectory)/lib/debug/libssl.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmat.a -force_load $(MSBuildProjectDirectory)/lib/debug/libsqlite3.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmip_dotnet.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmip_upe_and_protection_sdk_static.a" --registrar:static --aot=nopagetrampolines,ntrampolines=40960,nrgctx-trampolines=40960,nrgctx-fetch-trampolines=256,ngsharedvt-trampolines=4096,nimt-trampolines=4096 --optimize=-remove-dynamic-registrar</MtouchExtraArgs>

**Comment by rolfbjarne** [comment]
Can you provide an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) that shows the error?

**Comment by v-npadhy** [comment]
Please check the attached binlog. binlog extension is not a valid extension as an attachment. Just download the file and change the extension as binlog.
[msbuild.txt](https://github.com/user-attachments/files/16907496/msbuild.txt)

**Comment by rolfbjarne** [comment]
You're building for the simulator (`RuntimeIdentifier=iossimulator-ar64`), and the problem is exactly as I explained in my [previous comment](https://github.com/dotnet/maui/issues/24536#issuecomment-2325144095).

**Comment by v-npadhy** [comment]
Hi @rolfbjarne, I am building in device only. For your reference I have capture a screen recording and new msbuild binlog file.

Linker Flags:
<MtouchExtraArgs>--cxx -gcc_flags "-lstdc++ -L $(MSBuildProjectDirectory)/lib/debug -lc++ -lz -lcrypto -lssl -lxml2 -lmat -lsqlite3 -lmip_dotnet -lmip_upe_and_protection_sdk_static -lresolv -framework CoreTelephony -framework Foundation -framework CoreFoundation -framework CoreServices -framework Security -framework IOKit -framework UIKit -framework SystemConfiguration -framework Network -force_load $(MSBuildProjectDirectory)/lib/debug/libcrypto.a -force_load $(MSBuildProjectDirectory)/lib/debug/libssl.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmat.a -force_load $(MSBuildProjectDirectory)/lib/debug/libsqlite3.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmip_dotnet.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmip_upe_and_protection_sdk_static.a" --registrar:static --aot=nopagetrampolines,ntrampolines=40960,nrgctx-trampolines=40960,nrgctx-fetch-trampolines=256,ngsharedvt-trampolines=4096,nimt-trampolines=4096 --optimize=-remove-dynamic-registrar</MtouchExtraArgs>
		
The below reference error are causing due to unavailability of system framework  -framework Network, but we are passing -framework Network in MtouchExtraArgs. What ever system frameworks we are passing in MtouchExtraArgs, is not considering by MAUI. But it was working fine in Xamarin.

[msbuild.txt](https://github.com/user-attachments/files/16929207/msbuild.txt)

https://github.com/user-attachments/assets/5658db8b-3488-4b6f-8d01-333d71e5c915

Build Error:

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_nw_path_get_status", referenced from:
      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_is_constrained", referenced from:
      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_is_expensive", referenced from:
      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_monitor_cancel", referenced from:
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::~NetworkInformation() in libmat.a(NetworkInformationImpl.mm.o)
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_monitor_create", referenced from:
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_monitor_set_queue", referenced from:
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_monitor_set_update_handler", referenced from:
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_monitor_start", referenced from:
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_uses_interface_type", referenced from:
      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)
  "_res_9_dn_expand", referenced from:
      mipns::DnsServerResolverImpl::lookup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libmip_upe_and_protection_sdk_static.a(dns_server_resolver_impl_static.obj)
  "_res_9_nclose", referenced from:
      mipns::DnsServerResolverImpl::lookup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libmip_upe_and_protection_sdk_static.a(dns_server_resolver_impl_static.obj)
  "_res_9_ninit", referenced from: (com.microsoft.rightsmanagement.mobile.viewer.ios)

**Comment by rolfbjarne** [comment]
That build is still for the simulator, even though you've selected a device.

I think the problem is here in your csproj:

```xml
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Develop|iPhone' ">
```

The `Platform` property isn't used nor set in iOS .NET projects, so it ends up being the default ("AnyCPU"), and the configuration you think is being used, actually isn't.

I believe it'll work if you change the condition to:

```xml
<PropertyGroup Condition=" '$(Configuration)' == 'Develop' ">
```

Can you try that and see if anything changes?

**Comment by v-npadhy** [comment]
@rolfbjarne Still getting same error
Build Configuration:

<PropertyGroup Condition=" '$(Configuration)' == 'Develop' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\iPhone\Develop</OutputPath>
		<DefineConstants>__UNIFIED__;__MOBILE__;__IOS__;DEBUG;__DEVELOP__</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
		<ConsolePause>false</ConsolePause>
		<MtouchOptimizePNGs>True</MtouchOptimizePNGs>
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<MtouchI18n>cjk,mideast,other,rare,west</MtouchI18n>
		<CodesignKey>iPhone Developer</CodesignKey>
		<MtouchDebug>true</MtouchDebug>
		<MtouchExtraArgs>--cxx -gcc_flags "-lstdc++ -L $(MSBuildProjectDirectory)/lib/debug -lc++ -lz -lcrypto -lssl -lxml2 -lmat -lsqlite3 -lmip_dotnet -lmip_upe_and_protection_sdk_static -lresolv -framework CoreTelephony -framework Foundation -framework CoreFoundation -framework CoreServices -framework Security -framework IOKit -framework UIKit -framework SystemConfiguration -framework Network -force_load $(MSBuildProjectDirectory)/lib/debug/libcrypto.a -force_load $(MSBuildProjectDirectory)/lib/debug/libssl.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmat.a -force_load $(MSBuildProjectDirectory)/lib/debug/libsqlite3.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmip_dotnet.a -force_load $(MSBuildProjectDirectory)/lib/debug/libmip_upe_and_protection_sdk_static.a" --registrar:static --aot=nopagetrampolines,ntrampolines=40960,nrgctx-trampolines=40960,nrgctx-fetch-trampolines=256,ngsharedvt-trampolines=4096,nimt-trampolines=4096 --optimize=-remove-dynamic-registrar</MtouchExtraArgs>
		<_BundlerArguments Condition="'$(_PlatformName)' != 'macOS'">$(MtouchExtraArgs)</_BundlerArguments>
		<MtouchEnableBitcode>false</MtouchEnableBitcode>
		<MtouchHttpClientHandler>NSUrlSessionHandler</MtouchHttpClientHandler>
		<IpaPackageName>
		</IpaPackageName>
		<CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
		<_AppManifest>Info.plist</_AppManifest>
		<CodesignProvision>
		</CodesignProvision>
		<BuildIpa>false</BuildIpa>
		<MtouchNoSymbolStrip>true</MtouchNoSymbolStrip>
		<MtouchLink>SdkOnly</MtouchLink>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<MtouchInterpreter>-all</MtouchInterpreter>
		<CreatePackage>false</CreatePackage>
	</PropertyGroup>

Build Error:
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_nw_path_get_status", referenced from:
      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_is_constrained", referenced from:
      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_is_expensive", referenced from:
      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_monitor_cancel", referenced from:
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::~NetworkInformation() in libmat.a(NetworkInformationImpl.mm.o)
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_monitor_create", referenced from:
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_monitor_set_queue", referenced from:
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_monitor_set_update_handler", referenced from:
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_monitor_start", referenced from:
      Microsoft::Applications::Events::PlatformAbstraction::NetworkInformation::SetupNetDetect() in libmat.a(NetworkInformationImpl.mm.o)
  "_nw_path_uses_interface_type", referenced from:
      ____ZN9Microsoft12Applications6Events19PlatformAbstraction18NetworkInformation14SetupNetDetectEv_block_invoke.11 in libmat.a(NetworkInformationImpl.mm.o)
  "_res_9_dn_expand", referenced from:
      mipns::DnsServerResolverImpl::lookup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libmip_upe_and_protection_sdk_static.a(dns_server_resolver_impl_static.obj)
  "_res_9_nclose", referenced from:
      mipns::DnsServerResolverImpl::lookup(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libmip_upe_and_protection_sdk_static.a(dns_server_resolver_impl_static.obj)
  "_res_9_ninit", referenced from: (com.microsoft.rightsmanagement.mobile.viewer.ios)

**Comment by rolfbjarne** [comment]
Could you get an updated binlog?

**Comment by v-npadhy** [comment]
Updated binlog
[msbuild.txt](https://github.com/user-attachments/files/16944480/msbuild.txt)

**Comment by v-npadhy** [comment]
@rolfbjarne Please let me know if you need any more information to troubleshoot this native framework reference  issue in MAUI for iOS.

**Comment by rolfbjarne** [comment]
That's still a simulator build (the "Configuration" property is "Debug", not "Develop")

**Comment by v-npadhy** [comment]
The issue was in the build configuration. After fixing the build configuration issue, code is building and running without any issues.
