### ISSUE TITLE
Difference between Paint and Brush

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#2453]
I see MAUI View has property Background of type Brush, but IView.Background is of type Paint.

- What's the difference? Why 2 classes for the apparent same thing?
- How can a Brush be converted to a Paint?

In a custom control I'm exposing other properties of type Brush, and I'd like to use the ToDrawable extension to have a native Android drawable, but the extension is of type Paint, so I firstly need to convert the Brush to Paint.

**Comment by juansturla** [comment]
I am not sure about the difference
Brush was introduced with [Xamarin.Forms 4.8](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/brushes/), it is related to the gradient background
Paint is a new class. I think it's related to the new Maui.Graphics and how to draw the components (might be similar to [SKPaint ](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skpaint?view=skiasharp-2.80.2)from SkiaSharp)

But I am just guessing

It seems that there is an implicit conversion from one type to the other.
![image](https://user-images.githubusercontent.com/10248860/133306736-ac8ac7d8-f752-46d8-a2b2-a7fbe5641e9e.png)

**Comment by jsuarezruiz** [comment]
> I am not sure about the difference Brush was introduced with [Xamarin.Forms 4.8](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/brushes/), it is related to the gradient background Paint is a new class. I think it's related to the new Maui.Graphics and how to draw the components (might be similar to [SKPaint ](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skpaint?view=skiasharp-2.80.2)from SkiaSharp)
> 
> But I am just guessing
> 
> It seems that there is an implicit conversion from one type to the other. ![image](https://user-images.githubusercontent.com/10248860/133306736-ac8ac7d8-f752-46d8-a2b2-a7fbe5641e9e.png)

Is correct. A Brush is used in the .NET MAUI Api to defines objects used to fill the interiors of graphical shapes such as rectangles, ellipses, pies, polygons, and paths, also in views background. While Paint is a new class in  Maui.Graphics  similar to SKPaint, holds the style and color information about how to draw geometries, etc.
