### ISSUE TITLE
Shell navigation back is not working after update 2 NuGet packages  'Microsoft.Maui.Controls' and 'Microsoft.Maui.Controls.Compatibility'

### ISSUE THREAD

**Issue by bhuwancb99** [dotnet/maui#24555]
### Description

```xml
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.72" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.72" />
```  
After updating these two packages to the latest versions, Shell navigation's back functionality stopped working. When clicking the back arrow button, nothing happens, and it gets stuck. It works fine with version 8.0.72, but after updating to the newer version, it's no longer functional.

### Steps to Reproduce

add button inside page

```xaml
<Button Grid.Row="2" x:Name="Btn_MonthlyPointReport" 
    Clicked="Btn_MonthlyPointReport_Clicked"
    Text="{x:Static resources:GlobalResource.MONTHLY_POINT}" 
    Style="{StaticResource ButtonStyle}"/>
```
 
 when click on this button
 
```cs
 /// <summary>
/// Btn_MonthlyPointReport_Clicked
/// </summary>
/// <param name="sender"></param>
/// <param name="e"></param>
 private async void Btn_MonthlyPointReport_Clicked(object sender, EventArgs e)
{
    try
    {
        ShellNavigationState state = Shell.Current.CurrentState;
        await Shell.Current.GoToAsync($"{state.Location}/{nameof(StudentListPage)}");
    }
    catch (Exception ex)
    {
       
    }
}
```

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by mattleibow** [comment]
I just want to check what versions are working and what are not. In the issue you have a few versions mentioned:

 - 8.0.72
 - 9.0 preview 7
 - 8.0.82

Which version is having the issue?

**Comment by bhuwancb99** [comment]
Hi @mattleibow 

I have created a separate application, and it’s working there, but in my application, it’s not working. I am now searching for the root cause of this issue.
` public static class NavigationExtensions
 {
     /// <summary>
     /// PushModalAsyncSingle
     /// </summary>
     /// <param name="nav"></param>
     /// <param name="page"></param>
     /// <param name="animated"></param>
     /// <returns></returns>
     public static async Task PushModalAsyncSingle(this INavigation nav, Page page, bool animated = false)
     {
         if (DevicePlatform.Android == DeviceInfo.Current.Platform)
         {
             if (nav.ModalStack.Count == 0 || nav.ModalStack.Last().GetType() != page.GetType())
             {
                 await nav.PushModalAsync(page, animated);
             }
         }
         else
             await nav.PushModalAsync(page, animated);
     }

     /// <summary>
     /// PushAsyncSingle
     /// </summary>
     /// <param name="nav"></param>
     /// <param name="page"></param>
     /// <param name="animated"></param>
     /// <returns></returns>
     public static async Task PushAsyncSingle(this INavigation nav, Page page, bool animated = false)
     {
         if (DevicePlatform.Android == DeviceInfo.Current.Platform)
         {
             if (nav.NavigationStack[nav.NavigationStack.Count - 1] == null || nav.NavigationStack.Count == 0 || nav.NavigationStack.Last().GetType() != page.GetType())
             {
                 await nav.PushAsync(page, animated);
             }
         }
         else
             await nav.PushAsync(page, animated);
     }
 }`

**Comment by bhuwancb99** [comment]
i am facing issue after update this 2 packages
![image](https://github.com/user-attachments/assets/c6218dc9-280e-41b1-be7b-5e0ce4d5423d)

**Comment by jaosnz-rep** [comment]
@bhuwancb99  Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by bhuwancb99** [comment]
@jaosnz-rep - I have created a sample app, and it's working there, but it's not working in my mobile application. If you'd like, I can share my test APK along with the credentials.

**Comment by bhuwancb99** [comment]
Hi @mattleibow / @jaosnz-rep 

I have now reproduced the issue, and it occurs when adding different <Shell.TitleView> elements inside a NavigationPage based on the pages (TitleView content change based on your requirement). The back arrow stops working with the mentioned NuGet packages. Please find the attached project for your reference.

[DemoApp.zip](https://github.com/user-attachments/files/16978111/DemoApp.zip)
![Screenshot_1726139688](https://github.com/user-attachments/assets/421ae452-5d40-4745-981b-c95c9d069f04)
![Screenshot_1726139694](https://github.com/user-attachments/assets/1836b2db-e66f-4334-b94c-03be540bddbf)
![Screenshot_1726139701](https://github.com/user-attachments/assets/7c07e3a4-ed35-458f-9839-47dff395c315)

**Comment by QianaJiao** [comment]
Thanks for your sharing.
I just verified this issue on VS 17.11.3. It can be repro on Android platform with Maui 8.0.82, 8.0.80. And not repro on 8.0.72. It's a regression issue.

**Comment by mattleibow** [comment]
Were there any errors or messages in the logcat or output windows when navigating or when clicking back?

But thanks for the info and reports, we will have a look.

**Comment by bhuwancb99** [comment]
Hi,
Tested on the latest release (8.0.90), and now it's working as expected. Thanks for fixing this issue!
