### ISSUE TITLE
Delayed Update of Navbar Title and TabBar Background Color in .NET MAUI on Android When Switching Tabs

### ISSUE THREAD

**Issue by IX-OmkarP** [dotnet/maui#24568]
### Issue Description:
I am encountering an issue with delayed updates to the Navbar title and Navbar background color when switching tabs on an Android device in a project that I am migrating from Xamarin.Forms to .NET MAUI.

### Problem Details:

- Expected Behavior:
   - When switching between tabs, the Navbar title and Navbar background color should update immediately to reflect the values assigned to the selected tab.

- Actual Behavior:
    - When I click on Tab 2, the TabBar background color changes as expected, but the Navbar title and Navbar background color remain as those of Tab 1.
    - Upon switching to Tab 3, the Navbar title and Navbar background color update to the values for Tab 2 instead of those for Tab 3. The updates seem to be delayed by one tab click. 
    - This issue does not occur in Xamarin.Forms; the expected behavior is observed in the original Xamarin.Forms implementation.

### Additional Information:
- .NET MAUI Version: 8
- Android Device : Android

Screenshots:
![Screenshots GIF](https://github.com/user-attachments/assets/4656d2e2-f505-4055-8405-dba1585fce9f)

### Steps to Reproduce

- Create a .NET MAUI project with three tabs.
- Assign different Navbar titles and background colors for each tab.
- Run the project on an Android device.
- Switch between the tabs and observe the Navbar title and background color.

### Link to public reproduction project repository

https://github.com/IX-OmkarP/Tabbed_Page_POC

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

**Comment by ninachen03** [comment]
This issue has been verified using latest Visual Studio 17.12.0 Preview 1.0 (8.0.82) & 17.11.2（7.0.101）, Can repro on Android platform.

**Comment by kubaflo** [comment]
Hi, could you please try with the latest nightly build? It seems to be working fine for me

**Comment by kubaflo** [comment]
https://github.com/user-attachments/assets/73a5eb23-66d1-4453-aedc-787ca5abddd0

**Comment by IX-OmkarP** [comment]
> Hi, could you please try with the latest nightly build? It seems to be working fine for me

@kubaflo  Thanks for answering! I will try it and let you know if it works for me.

**Comment by IX-OmkarP** [comment]
@kubaflo Thank you! It's working with the latest nightly build. Now I just need to wait for the public NuGet package.

**Comment by kubaflo** [comment]
> @kubaflo Thank you! It's working with the latest nightly build. Now I just need to wait for the public NuGet package.

Cool!
