### ISSUE TITLE
[Android] `RemainingItemsThresholdReachedCommand` of `CarouselView` is not triggered

### ISSUE THREAD

**Issue by FroggieFrog** [dotnet/maui#24571]
### Description

When running in Android (14) the `RemainingItemsThresholdReachedCommand` of the `CarouselView` is not triggered.

When running in Windows, everything works fine.

### Steps to Reproduce

1. run the app
2. scroll through the items
3. there are never more than 10 items

### Link to public reproduction project repository

https://github.com/FroggieFrog/BugMauiCarouselIncremental

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by ninachen03** [comment]
I can repro this issue at Android platform on the latest 17.12.0 Preview 1.0 (8.0.82 & 8.0.3).

**Comment by kubaflo** [comment]
Hi, @FroggieFrog try to set `Loop` to false
