### ISSUE TITLE
when I create a new project and search for MAUI i am getting this, even afte modifying installer

### ISSUE THREAD

**Issue by MaitriBhuva** [dotnet/maui#24576]
not finding what you are looking for ?

**Comment by MitchBomcanhao** [comment]
?

**Comment by MaitriBhuva** [comment]
Even after installing required workload for MAUI , when i open Visual
studio to create new project , .NET MAUI option is not available.

**Comment by jfversluis** [comment]
I'm sorry but in order to be able to help you and give a sensible answer we will need a lot more detail than what is in this issue right now. What are you trying to do? What version of Visual Studio (Code)? What operating system? Do you get any errors? What version of .NET do you have installed?

**Comment by MaitriBhuva** [comment]
Yes, please proceed.

**Comment by MaitriBhuva** [comment]
> I'm sorry but in order to be able to help you and give a sensible answer we will need a lot more detail than what is in this issue right now. What are you trying to do? What version of Visual Studio (Code)? What operating system? Do you get any errors? What version of .NET do you have installed?

I am trying to install .NET MAUI workload. The version of my visual studio is 17.11. I have windows operating system. After installing.NET MAUI workload when I open the visual studio to create my First MAUI  app , when i search for the .NET MAUI App, it says that no related search found, try to install tools.

**Comment by jfversluis** [comment]
If you open a command terminal and do `dotnet new list` are the .NET MAUI templates in there? 

You can install them manually with `dotnet new install Microsoft.Maui.Templates.net8` assuming you are targeting .NET 8, there is also one for .NET 9. 

If you do that, do they show up then?

**Comment by mattleibow** [comment]
Did you install the maui workload on the command line or by checking the box in visual studio?

**Comment by MaitriBhuva** [comment]
Yes, I did!

**Comment by mattleibow** [comment]
Oh sorry. Which mechanism did you use to install? I wonder if the cli did not make the templates available.

Can you run `dotnet new maui -o MyNewMauiApp` and see what it does.

Also, try `dotnet --info`

Please share the output of both commands so we can see what actually installed and what is happening.

**Comment by MaitriBhuva** [comment]
Yes, everything is fine.

**Comment by jfversluis** [comment]
Seems like this is resolved. THanks!

**Comment by MaitriBhuva** [comment]
Yes, it works!
