### ISSUE TITLE
[iOS, macOS] Text in the Editor control disappeared when reducing the Scale of the Editor control

### ISSUE THREAD

**Issue by VishalOmprasad** [dotnet/maui#24583]
### Description

When reducing the Scale of the Editor control, the text on the Editor control disappeared and reappeared after the Editor.Scale increases. This works fine on Android and Windows platforms.
#### Issue reproducible video ####
- **iOS**

https://github.com/user-attachments/assets/eba7a685-c5a7-4221-badd-8001ffe5cedc

- **macOS**

https://github.com/user-attachments/assets/4364e429-26b8-4d13-954a-6d514a57ee68

### Steps to Reproduce

1. Create a new .NET MAUI application.
2. Add the Editor control and the Slider control (whose Minimum=0 and Maximum-1) inside the StackLayout.
3. Bind the Editor.Scale to the Slider.Value.
4. Run the application on either iOS or macOS platform.
5. Drag the Slider to reduce the Editor.Scale value.
6. Notice that the text will disappear.

### Link to public reproduction project repository

https://github.com/VishalOmprasad/Editor-Scale-Issue-iOS-macCatalyst

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.6.14(build413)(8.0.82 & 8.0.80). Can repro on iOS and macOS platforms.
