### ISSUE TITLE
Class Libraries throw Exception when building for MacCatalyst

### ISSUE THREAD

**Issue by WoistdasNiveau** [dotnet/maui#24595]
### Description

When you add a Class Library targeting .net 8 to a Maui app it throws an Exception when building the app for MacCatalyst but not for iOS.
The Exception:
`0>Microsoft.PackageDependencyResolution.targets(266,5): Error NETSDK1005 : Die Ressourcendatei "/Users/oliverstockl/RiderProjects/Oegeg/OegegEtd/ClassLibrary1/obj/project.assets.json" weist kein Ziel für "net8.0-maccatalyst" auf. Stellen Sie sicher, dass die Wiederherstellung ausgeführt wurde, und dass Sie "net8.0-maccatalyst" in die TargetFrameworks für Ihr Projekt eingeschlossen haben.
0>------- Finished building project: ClassLibrary1. Succeeded: False. Errors: 1. Warnings: 0
`

### Steps to Reproduce

1. Create a new Maui App
2. Add a Class Library
3. Reference the Class library in the App
4. Try to start the app

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacCatalyst

### Did you find any workaround?

Unfortunately not

### Relevant log output

```shell
0>Microsoft.PackageDependencyResolution.targets(266,5): Error NETSDK1005 : Die Ressourcendatei "/Users/oliverstockl/RiderProjects/Oegeg/OegegEtd/ClassLibrary1/obj/project.assets.json" weist kein Ziel für "net8.0-maccatalyst" auf. Stellen Sie sicher, dass die Wiederherstellung ausgeführt wurde, und dass Sie "net8.0-maccatalyst" in die TargetFrameworks für Ihr Projekt eingeschlossen haben.
0>------- Finished building project: ClassLibrary1. Succeeded: False. Errors: 1. Warnings: 0
```

**Comment by drasticactions** [comment]
How are you building your application? Going by the error, the net8.0-maccatalyst nuget packages was not restored, but this doesn't seem like it would be specific to something within the MAUI UI framework, it could be a TargetFramework issue.

Can you try restoring and building from CLI instead of (Guessing by the directory name) Rider? It may be a Rider bug.

**Comment by WoistdasNiveau** [comment]
@drasticactions indeed it is a Rider bug, I will report it there restoring, building and running via the CLI worked perfectly fine. Thank you a lot.
