### ISSUE TITLE
DeviceIdiom detects notebook as tablet

### ISSUE THREAD

**Issue by lenardg** [dotnet/maui#24596]
### Description

There was an issue on this already, #11126 , that has already been fixed in MAUI 7 and 8.

However, we are now seeing this behavior again with the latest MAUI version. We have a ThinkPad P1 Gen 3 notebook that has a touchscreen. This device is detected as DeviceIdiom.Tablet. Note that it is not possible to fold the screen into tablet mode, this is a regular notebook. 

We use Windows 10 and tablet mode is OFF. In fact, the notebook is connected to a dock, the internal (touch) display is off and an external keyboard and mouse is connected. 

I think DeviceIdiom should not be Tablet at this point. 

### Steps to Reproduce

Just read DeviceInfo.Current.Idiom on this device, which will say Tablet. 

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows target 10.0.19041

### Did you find any workaround?

For our purposes we can treat WinUI always as a desktop:

```
IsDesktop =
		DeviceInfo.Current.Platform == DevicePlatform.WinUI ||
		DeviceInfo.Current.Idiom == DeviceIdiom.Desktop;
```

But I think this is wrong behavior.

**Comment by daltzctr** [comment]
Probably fixed in #22809

**Comment by lenardg** [comment]
Thanks, will test when that comes out!

**Comment by jfversluis** [comment]
I'm going to assume this is fixed by that PR. If not, please open a new issue by the time that is released. Thanks!
