### ISSUE TITLE
Cannot publish to App Store . IPA generation error

### ISSUE THREAD

**Issue by admindeytabyte** [dotnet/maui#24591]
### Description

![Screenshot 2024-09-03 233043](https://github.com/user-attachments/assets/b3cb9a91-8823-4b4b-9ac4-4d4e2780d684)

### Steps to Reproduce

1. Build Maui Release for IOS by connecting to Remote Device
2. Use manual provisioning profile, Automatic Distribution
3. Archive (Completed Successfully)
4. Distribute and select location

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by drasticactions** [comment]
I believe the tools you're using above are maintained by the Visual Studio team and not the MAUI UI team. If you submit your issue to VSFeedback, the right team can look at your issue.

**Comment by QianaJiao** [comment]
I'm unable to repro this issue with the template Maui and Xamarin project (I'm in 17.12.0 Preview 1.0(8.0.82 & 8.0.3)).
The following document may be useful, or you could submit the issue to VSFeedback for help： 
https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-app-store?view=net-maui-8.0#publish-the-app

**Comment by Kremed** [comment]
I was encountering the same issue, but I managed to resolve it by generating the IPA file using the command line with the following command:

`dotnet publish -f:net8.0-ios -c:Release /p:ServerAddress=192.168.0.000 /p:ServerUser={MacUserName} /p:ServerPassword={MacPassword} /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory=/Users/{MacUserName}/Library/Caches/Xamarin/XMA/SDKs/dotnet/`

For further reference, you can check out the official documentation here:
[https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-cli?view=net-maui-8.0](url)

Additionally, this YouTube video may be helpful: 
[https://www.youtube.com/watch?v=kpZi5xAvpZA&t=1283s](url)

For those facing the same issue, you might find some insights in the issue tracker: [#24652](https://github.com/dotnet/maui/issues/24652)
