### ISSUE TITLE
CheckBox Bug(for Android)

### ISSUE THREAD

**Issue by gwise-vision** [dotnet/maui#24602]
### Description

https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CheckBoxDemos

When I display a screen with a CheckBox in Android, I get the following error in the debug screen:

---------------------------------------------------------------------------

[ResourcesCompat] Failed to inflate ColorStateList, leaving it to the framework
[ResourcesCompat] java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f03010f a=-1}, theme={InheritanceMap=[id=0x7f100137com.companyname.checkboxdemos:style/Maui.MainTheme.NoActionBar, id=0x7f100136com.companyname.checkboxdemos:style/Maui.MainTheme, id=0x7f100249com.companyname.checkboxdemos:style/Theme.MaterialComponents.DayNight, id=0x7f100262com.companyname.checkboxdemos:style/Theme.MaterialComponents.Light, id=0x7f10006bcom.companyname.checkboxdemos:style/Base.Theme.MaterialComponents.Light, id=0x7f1000a4com.companyname.checkboxdemos:style/Base.V21.Theme.MaterialComponents.Light, id=0x7f100092com.companyname.checkboxdemos:style/Base.V14.Theme.MaterialComponents.Light, id=0x7f100093com.companyname.checkboxdemos:style/Base.V14.Theme.MaterialComponents.Light.Bridge, id=0x7f100140com.companyname.checkboxdemos:style/Platform.MaterialComponents.Light, id=0x7f10021ccom.companyname.checkboxdemos:style/Theme.AppCompat.Light, id=0x7f100053com.companyname.checkboxdemos:style/Base.Theme.AppCompat.Light, id=0x7f1000b6com.companyname.checkboxdemos:style/Base.V28.Theme.AppCompat.Light, id=0x7f1000b3com.companyname.checkboxdemos:style/Base.V26.Theme.AppCompat.Light, id=0x7f1000adcom.companyname.checkboxdemos:style/Base.V23.Theme.AppCompat.Light, id=0x7f1000abcom.companyname.checkboxdemos:style/Base.V22.Theme.AppCompat.Light, id=0x7f1000a0com.companyname.checkboxdemos:style/Base.V21.Theme.AppCompat.Light, id=0x7f1000b9com.companyname.checkboxdemos:style/Base.V7.Theme.AppCompat.Light, id=0x7f10013dcom.companyname.checkboxdemos:style/Platform.AppCompat.Light, id=0x7f100148com.companyname.checkboxdemos:style/Platform.V25.AppCompat.Light, id=0x1030241android:style/Theme.Material.Light.NoActionBar, id=0x1030237android:style/Theme.Material.Light, id=0x103000candroid:style/Theme.Light, id=0x1030005android:style/Theme], Themes=[com.companyname.checkboxdemos:style/Maui.MainTheme.NoActionBar, forced, com.companyname.checkboxdemos:style/Maui.SplashTheme, forced, com.companyname.checkboxdemos:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
[ResourcesCompat] 	at android.content.res.TypedArray.getColor(TypedArray.java:529)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.inflate(ColorStateListInflaterCompat.java:160)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:125)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:104)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
[ResourcesCompat] 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:558)
[ResourcesCompat] 	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:48)
[ResourcesCompat] 	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:179)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCompoundButtonHelper.loadFromAttributes(AppCompatCompoundButtonHelper.java:81)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCheckBox.<init>(AppCompatCheckBox.java:84)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:231)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:227)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:223)
[ResourcesCompat] 	at crc640ec207abc449b2ca.ShellContentFragment.n_onCreateView(Native Method)
[ResourcesCompat] 	at crc640ec207abc449b2ca.ShellContentFragment.onCreateView(ShellContentFragment.java:62)
[ResourcesCompat] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
[ResourcesCompat] 	at android.os.Handler.handleCallback(Handler.java:958)
[ResourcesCompat] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[ResourcesCompat] 	at android.os.Looper.loopOnce(Looper.java:230)
[ResourcesCompat] 	at android.os.Looper.loop(Looper.java:319)
[ResourcesCompat] 	at android.app.ActivityThread.main(ActivityThread.java:8919)
[ResourcesCompat] 	at java.lang.reflect.Method.invoke(Native Method)
[ResourcesCompat] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
[ResourcesCompat] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
[ResourcesCompat] Failed to inflate ColorStateList, leaving it to the framework
[ResourcesCompat] java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f03010f a=-1}, theme={InheritanceMap=[id=0x7f100137com.companyname.checkboxdemos:style/Maui.MainTheme.NoActionBar, id=0x7f100136com.companyname.checkboxdemos:style/Maui.MainTheme, id=0x7f100249com.companyname.checkboxdemos:style/Theme.MaterialComponents.DayNight, id=0x7f100262com.companyname.checkboxdemos:style/Theme.MaterialComponents.Light, id=0x7f10006bcom.companyname.checkboxdemos:style/Base.Theme.MaterialComponents.Light, id=0x7f1000a4com.companyname.checkboxdemos:style/Base.V21.Theme.MaterialComponents.Light, id=0x7f100092com.companyname.checkboxdemos:style/Base.V14.Theme.MaterialComponents.Light, id=0x7f100093com.companyname.checkboxdemos:style/Base.V14.Theme.MaterialComponents.Light.Bridge, id=0x7f100140com.companyname.checkboxdemos:style/Platform.MaterialComponents.Light, id=0x7f10021ccom.companyname.checkboxdemos:style/Theme.AppCompat.Light, id=0x7f100053com.companyname.checkboxdemos:style/Base.Theme.AppCompat.Light, id=0x7f1000b6com.companyname.checkboxdemos:style/Base.V28.Theme.AppCompat.Light, id=0x7f1000b3com.companyname.checkboxdemos:style/Base.V26.Theme.AppCompat.Light, id=0x7f1000adcom.companyname.checkboxdemos:style/Base.V23.Theme.AppCompat.Light, id=0x7f1000abcom.companyname.checkboxdemos:style/Base.V22.Theme.AppCompat.Light, id=0x7f1000a0com.companyname.checkboxdemos:style/Base.V21.Theme.AppCompat.Light, id=0x7f1000b9com.companyname.checkboxdemos:style/Base.V7.Theme.AppCompat.Light, id=0x7f10013dcom.companyname.checkboxdemos:style/Platform.AppCompat.Light, id=0x7f100148com.companyname.checkboxdemos:style/Platform.V25.AppCompat.Light, id=0x1030241android:style/Theme.Material.Light.NoActionBar, id=0x1030237android:style/Theme.Material.Light, id=0x103000candroid:style/Theme.Light, id=0x1030005android:style/Theme], Themes=[com.companyname.checkboxdemos:style/Maui.MainTheme.NoActionBar, forced, com.companyname.checkboxdemos:style/Maui.SplashTheme, forced, com.companyname.checkboxdemos:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
[ResourcesCompat] 	at android.content.res.TypedArray.getColor(TypedArray.java:529)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.inflate(ColorStateListInflaterCompat.java:160)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:125)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:104)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
[ResourcesCompat] 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:558)
[ResourcesCompat] 	at 
androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:48)
[ResourcesCompat] 	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:179)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCompoundButtonHelper.loadFromAttributes(AppCompatCompoundButtonHelper.java:81)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCheckBox.<init>(AppCompatCheckBox.java:84)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:231)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:227)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:223)
[ResourcesCompat] 	at crc640ec207abc449b2ca.ShellContentFragment.n_onCreateView(Native Method)
[ResourcesCompat] 	at crc640ec207abc449b2ca.ShellContentFragment.onCreateView(ShellContentFragment.java:62)
[ResourcesCompat] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
[ResourcesCompat] 	at android.os.Handler.handleCallback(Handler.java:958)
[ResourcesCompat] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[ResourcesCompat] 	at android.os.Looper.loopOnce(Looper.java:230)
[ResourcesCompat] 	at android.os.Looper.loop(Looper.java:319)
[ResourcesCompat] 	at android.app.ActivityThread.main(ActivityThread.java:8919)
[ResourcesCompat] 	at java.lang.reflect.Method.invoke(Native Method)
[ResourcesCompat] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
[ResourcesCompat] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
[ResourcesCompat] Failed to inflate ColorStateList, leaving it to the framework
[ResourcesCompat] java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f03010f a=-1}, theme={InheritanceMap=[id=0x7f100137com.companyname.checkboxdemos:style/Maui.MainTheme.NoActionBar, id=0x7f100136com.companyname.checkboxdemos:style/Maui.MainTheme, id=0x7f100249com.companyname.checkboxdemos:style/Theme.MaterialComponents.DayNight, id=0x7f100262com.companyname.checkboxdemos:style/Theme.MaterialComponents.Light, id=0x7f10006bcom.companyname.checkboxdemos:style/Base.Theme.MaterialComponents.Light, id=0x7f1000a4com.companyname.checkboxdemos:style/Base.V21.Theme.MaterialComponents.Light, id=0x7f100092com.companyname.checkboxdemos:style/Base.V14.Theme.MaterialComponents.Light, id=0x7f100093com.companyname.checkboxdemos:style/Base.V14.Theme.MaterialComponents.Light.Bridge, id=0x7f100140com.companyname.checkboxdemos:style/Platform.MaterialComponents.Light, id=0x7f10021ccom.companyname.checkboxdemos:style/Theme.AppCompat.Light, id=0x7f100053com.companyname.checkboxdemos:style/Base.Theme.AppCompat.Light, id=0x7f1000b6com.companyname.checkboxdemos:style/Base.V28.Theme.AppCompat.Light, id=0x7f1000b3com.companyname.checkboxdemos:style/Base.V26.Theme.AppCompat.Light, id=0x7f1000adcom.companyname.checkboxdemos:style/Base.V23.Theme.AppCompat.Light, id=0x7f1000abcom.companyname.checkboxdemos:style/Base.V22.Theme.AppCompat.Light, id=0x7f1000a0com.companyname.checkboxdemos:style/Base.V21.Theme.AppCompat.Light, id=0x7f1000b9com.companyname.checkboxdemos:style/Base.V7.Theme.AppCompat.Light, id=0x7f10013dcom.companyname.checkboxdemos:style/Platform.AppCompat.Light, id=0x7f100148com.companyname.checkboxdemos:style/Platform.V25.AppCompat.Light, id=0x1030241android:style/Theme.Material.Light.NoActionBar, id=0x1030237android:style/Theme.Material.Light, id=0x103000candroid:style/Theme.Light, id=0x1030005android:style/Theme], Themes=[com.companyname.checkboxdemos:style/Maui.MainTheme.NoActionBar, forced, com.companyname.checkboxdemos:style/Maui.SplashTheme, forced, com.companyname.checkboxdemos:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
[ResourcesCompat] 	at android.content.res.TypedArray.getColor(TypedArray.java:529)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.inflate(ColorStateListInflaterCompat.java:160)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:125)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:104)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
[ResourcesCompat] 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:558)
[ResourcesCompat] 	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:48)
[ResourcesCompat] 	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:179)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCompoundButtonHelper.loadFromAttributes(AppCompatCompoundButtonHelper.java:81)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCheckBox.<init>(AppCompatCheckBox.java:84)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:231)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:227)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:223)
[ResourcesCompat] 	at crc640ec207abc449b2ca.ShellContentFragment.n_onCreateView(Native Method)
[ResourcesCompat] 	at crc640ec207abc449b2ca.ShellContentFragment.onCreateView(ShellContentFragment.java:62)
[ResourcesCompat] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
[ResourcesCompat] 	at android.os.Handler.handleCallback(Handler.java:958)
[ResourcesCompat] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[ResourcesCompat] 	at android.os.Looper.loopOnce(Looper.java:230)
[ResourcesCompat] 	at android.os.Looper.loop(Looper.java:319)
[ResourcesCompat] 	at android.app.ActivityThread.main(ActivityThread.java:8919)
[ResourcesCompat] 	at java.lang.reflect.Method.invoke(Native Method)
[ResourcesCompat] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
[ResourcesCompat] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
[ResourcesCompat] Failed to inflate ColorStateList, leaving it to the framework
[ResourcesCompat] java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f03010f a=-1}, theme={InheritanceMap=[id=0x7f100137com.companyname.checkboxdemos:style/Maui.MainTheme.NoActionBar, id=0x7f100136com.companyname.checkboxdemos:style/Maui.MainTheme, id=0x7f100249com.companyname.checkboxdemos:style/Theme.MaterialComponents.DayNight, id=0x7f100262com.companyname.checkboxdemos:style/Theme.MaterialComponents.Light, id=0x7f10006bcom.companyname.checkboxdemos:style/Base.Theme.MaterialComponents.Light, id=0x7f1000a4com.companyname.checkboxdemos:style/Base.V21.Theme.MaterialComponents.Light, id=0x7f100092com.companyname.checkboxdemos:style/Base.V14.Theme.MaterialComponents.Light, id=0x7f100093com.companyname.checkboxdemos:style/Base.V14.Theme.MaterialComponents.Light.Bridge, id=0x7f100140com.companyname.checkboxdemos:style/Platform.MaterialComponents.Light, id=0x7f10021ccom.companyname.checkboxdemos:style/Theme.AppCompat.Light, id=0x7f100053com.companyname.checkboxdemos:style/Base.Theme.AppCompat.Light, id=0x7f1000b6com.companyname.checkboxdemos:style/Base.V28.Theme.AppCompat.Light, id=0x7f1000b3com.companyname.checkboxdemos:style/Base.V26.Theme.AppCompat.Light, id=0x7f1000adcom.companyname.checkboxdemos:style/Base.V23.Theme.AppCompat.Light, id=0x7f1000abcom.companyname.checkboxdemos:style/Base.V22.Theme.AppCompat.Light, id=0x7f1000a0com.companyname.checkboxdemos:style/Base.V21.Theme.AppCompat.Light, id=0x7f1000b9com.companyname.checkboxdemos:style/Base.V7.Theme.AppCompat.Light, id=0x7f10013dcom.companyname.checkboxdemos:style/Platform.AppCompat.Light, id=0x7f100148com.companyname.checkboxdemos:style/Platform.V25.AppCompat.Light, id=0x1030241android:style/Theme.Material.Light.NoActionBar, id=0x1030237android:style/Theme.Material.Light, id=0x103000candroid:style/Theme.Light, id=0x1030005android:style/Theme], Themes=[com.companyname.checkboxdemos:style/Maui.MainTheme.NoActionBar, forced, com.companyname.checkboxdemos:style/Maui.SplashTheme, forced, com.companyname.checkboxdemos:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
[ResourcesCompat] 	at android.content.res.TypedArray.getColor(TypedArray.java:529)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.inflate(ColorStateListInflaterCompat.java:160)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:125)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:104)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
[ResourcesCompat] 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:558)
[ResourcesCompat] 	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:48)
[ResourcesCompat] 	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:179)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCompoundButtonHelper.loadFromAttributes(AppCompatCompoundButtonHelper.java:81)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCheckBox.<init>(AppCompatCheckBox.java:84)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:231)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:227)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:223)
[ResourcesCompat] 	at crc640ec207abc449b2ca.ShellContentFragment.n_onCreateView(Native Method)
[ResourcesCompat] 	at crc640ec207abc449b2ca.ShellContentFragment.onCreateView(ShellContentFragment.java:62)
[ResourcesCompat] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
[ResourcesCompat] 	at android.os.Handler.handleCallback(Handler.java:958)
[ResourcesCompat] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[ResourcesCompat] 	at android.os.Looper.loopOnce(Looper.java:230)
[ResourcesCompat] 	at android.os.Looper.loop(Looper.java:319)
[ResourcesCompat] 	at android.app.ActivityThread.main(ActivityThread.java:8919)
[ResourcesCompat] 	at java.lang.reflect.Method.invoke(Native Method)
[ResourcesCompat] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
[ResourcesCompat] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CheckBoxDemos

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.2(8.0.82 & 8.0.80 & 8.0.3 ). Can repro on Android platform. 
But on 7.0.101 works fine.
