### ISSUE TITLE
iOS <button> onclick event not firing with linker behavior set to 'Link Framework SDKs Only'

### ISSUE THREAD

**Issue by Danaj-Zigic** [dotnet/maui#24616]
### Description

When I publish or simulate on an iOS device through Visual Studio and have the Linker behavior set to 'Link Framework SDKs Only' or 'Link All', button events do not fire.

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Disable linker behavior

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12.0 Preview 1.0( 9.0.0-preview.7.24407.4 & 8.0.82). Not repro on iOS platform.
I set 'Link Framework SDKs Only' and set a breakpoint. The button's Click event can be triggered. If you still reproduce the problem, could you provide us with a sample project so we can investigate it further?
