### ISSUE TITLE
[Bug] Project Build Error 

### ISSUE THREAD

**Issue by Ultra-max99** [dotnet/maui#2461]
Related to  #1379?

### Description

WinUI project shows missing SDKs, while all necessary extensions and workloads are installed and maui-check had succeeded.
![image](https://user-images.githubusercontent.com/80412399/132955554-ed564bc5-eda5-46e1-be2f-e7f95a9819f4.png)
Trying to build the WinUI project in Visual Studio 2022 only shows the output of the normal MAUI project. Building the project via commandline gives this output: 
```
Microsoft (R) Build Engine version 17.0.0-preview-21378-03+d592862ed for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Users\cuent\.nuget\packages\microsoft.projectreunion.winui\0.8.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(167,18): error MSB4086: A numeric comparison was attempted on "$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)" that evaluates to "" instead of a number, in condition "'$(AppxUseResourceIndexerApi)' == '' AND '$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)' < '6.3'". [C:\Users\cuent\source\repos\TestM\TestM\TestM.WinUI\TestM.WinUI.csproj]

Build FAILED.

C:\Users\cuent\.nuget\packages\microsoft.projectreunion.winui\0.8.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(167,18): error MSB4086: A numeric comparison was attempted on "$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)" that evaluates to "" instead of a number, in condition "'$(AppxUseResourceIndexerApi)' == '' AND '$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)' < '6.3'". [C:\Users\cuent\source\repos\TestM\TestM\TestM.WinUI\TestM.WinUI.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.42

```
Trying to run in Visual Studio shows this dialog: 
![image](https://user-images.githubusercontent.com/80412399/132955721-1b6e9498-8dea-40dd-8bd9-f9402b12277c.png)

### Steps to Reproduce

1. make a new MAUI Proejct
2. Switch to the WinUI side 
3. try to build

### Expected Behavior

Being able to build and run the project.

### Actual Behavior

Not being able to.

### Basic Information

- Version with issue: latest stable
- Last known good version: ?
- IDE: Visual Studio 2022 Preview 3.1
- Platform Target Frameworks: 
  - UWP:

**Comment by juansturla** [comment]
Now it's not working and was already reported.
You cannot debug it, but you can right click the winui project and Deploy it. 
Then go to your windows start menu and the app should be there

**Comment by AraHaan** [comment]
I prefer not to deploy it currently as it would depend on an sqlite db file that has to be there and preexisting and I prefer to run it like any other desktop application (exe) file that does not get automatically added to the start menu, but instead can be itself zipped up and ready for distribution without any need to install it. As such I like to prefer ``dotnet build`` over ``dotnet publish`` and then then place any additional files I want in that output folder and then zip them all up.

**Comment by Daniellled** [comment]
I can confirm it is still happen in RC 1 with VS 2022 Preview 4.1 when you build from the command line

`
C:\Users\XXX\.nuget\packages\microsoft.windowsappsdk.winui\1.0.0-experimental1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(167,18): error MSB4086: A numeric comparison was attempted on "$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)" that evaluates to "" instead of a number, in condition "'$(AppxUseResourceIndexerApi)' == '' AND '$(registry:HKEY_LOCAL_MA
CHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)' < '6.3'". [D:\XXX\YYY.csproj] [D:\XXX\ZZZ]
`

**Comment by jfversluis** [comment]
This has been a while without activity and we're already a couple of previews further. Closing this for now, please open a new issue if this is still a problem with the latest previews. Thanks!
