### ISSUE TITLE
Hot reloading a TabBar page (without Shell) duplicates all tabs

### ISSUE THREAD

**Issue by softlion** [dotnet/maui#24623]
### Description

When modifying anything on one of the ContentPage inside a TabbedPage having 3 tabs, hot reload is triggered correctly, but after that the tab bar contains 6 tabs. After a second hot reload trigger, the tab bar contains 9 tabs. Etc ...

normal tabs:
![image](https://github.com/user-attachments/assets/7d9bdf95-241a-47ec-a140-872daf5f6572)

after a couple of hot reload:
![image](https://github.com/user-attachments/assets/1d655837-e3c7-4072-a0e9-89ea964966a7)

(tap on the vertical bar to the right of the tab bar)
![image](https://github.com/user-attachments/assets/c884dd87-5230-4476-b910-44d43403e431)

### Steps to Reproduce

1. Create a maui Android app not using shell
2. Modify the 1st page to be a TabbedPage 
3. Create 2 ContentPage and add them to the TabbedPage
4. Start debugging on Android simulator or Android device
5. Modify the content of one of the ContentPage.
6. Observe the tabs

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 34

### Did you find any workaround?

no

**Comment by Zhanglirong-Winnie** [comment]
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
