### ISSUE TITLE
[Bug] Invoking Shapes API throws System.DllNotFoundException on WinUI.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2463]
Using MAUI `6.0.100-rc.2.1651`

If you try to invoke any Shape within Xaml while using the WinUI Head, your app with throw an exception while trying to load Win2D and its related dependencies.

![image](https://user-images.githubusercontent.com/898335/133005702-bd418e1c-7454-4cdc-bef5-1c82fca61133.png)

This will cause the app to crash.

**Comment by drasticactions** [comment]
If I include package references to Microsoft.Graphics.Win2D and Microsoft.Maui.Graphics.Win2D.WinUI.Desktop (after downloading a build and putting it into my local Nuget cache) it would work.

```
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.0.26-experimental1" />
		<PackageReference Include="Microsoft.Maui.Graphics.Win2D.WinUI.Desktop" Version="6.0.100-rc.1.415" />
```

**Comment by AraHaan** [comment]
Odd for me it won't let me install the templates to use rc.2 of MAUI.

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue with Preview 10.
