### ISSUE TITLE
MAUI blazor , consequence  JS api calling  DO NOT WORK

### ISSUE THREAD

**Issue by infofromca** [dotnet/maui#24659]
### Description

if there 2 or more api calling to the server , only first js calling work, the following js calling  not work. in my case, both are fetch POST 

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

**Comment by infofromca** [comment]
They are diff. issues

**Comment by infofromca** [comment]
After invistigation,  the issue is after http post , maui blazor cannot get the response.
 ```
async function fetchPostAsync(path) {
     const response = await fetch(
         `${urlPrefix}/${path}`,
         { method: 'POST', body: new FormData(form) }
     );
     alert(response.ok);
     alert(response.status);
     if (!response.ok) {
         throw new Error(`HTTP error! status: ${response.status}`);
     }
     const data = await response.json();
     return data;
 }
```
even  alert(response.ok);
     alert(response.status); cannot work.
another way:
```
function fetchPost(path) {
    alert("inside fetch post");
    return fetch(`${urlPrefix}/${path}`, { method: 'POST', body: new FormData(form) })
        .then(response => {
            alert(response.status);
            if (!response.ok) {
                alert("not ok");
            } else {
                alert("ok");
            }
            alert(response);
            alert(response.json());
            return response.json();
        })
        ;           
}
```
all alerts are not working.
return response.json(); cannot work.
the same code work in browser blazor.

**Comment by Eilon** [comment]
What is the URL being called in `urlPrefix`?
