### ISSUE TITLE
Thank You to Our Outstanding Contributors: @MartyIX and @albyrock87

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#24650]
I’d like to take a moment to thank the .NET MAUI community for their ongoing contributions. We appreciate the effort our community members put into reporting issues, submitting pull requests, and helping to maintain a welcoming and safe environment for everyone, especially newcomers.
 
@MartyIX has been a triager for some time now and has made significant [contributions](https://github.com/dotnet/maui/pulls?q=is%3Apr+author%3AMartyIX+) through pull requests. Their consistent efforts in managing issues and PRs, along with their valuable input, have greatly benefited our project. We are grateful for their dedication and the positive impact they’ve had on our community.
 
Similarly, @albyrock87 has made remarkable [contributions](https://github.com/dotnet/maui/pulls?q=is%3Apr+author%3Aalbyrock87+) to our project. Their attention to detail and commitment to improving the quality of our codebase have been invaluable. We appreciate their ongoing efforts and the support they provide to both new and experienced community members alike.
 
We welcome any feedback or suggestions on how we can better support and recognize our community here. Thank you for your continued support.

**Comment by jonmdev** [comment]
I will second the thanks to @albyrock87  who shockingly seemed to single handedly fix all the iOS Border animation and redraw lag issues which were previously making Maui in iOS look absolutely bizarre.

Microsoft should be sending you on a free all inclusive vacation to your destination of choice as a bounty for that alone. 

Where's Bill Gates and why is he too busy to make this happen? 😂

**Comment by albilaga** [comment]
I do want to appreciate bug fix from @albyrock87 that prevent migration our app especially with this bug fixes https://github.com/dotnet/maui/pull/24360. This is really well done. But now, we need time again to wait until dotnet 9 stable 😅😅😅

**Comment by mattleibow** [comment]
Closing this because it is not an issue and the issue system is complaining. It does not mean we now appreciate you less :)
