### ISSUE TITLE
Problem with accessing NavigatedToEventArgs.PreviousPage in OnNavigatedTo in Page

### ISSUE THREAD

**Issue by gwise-vision** [dotnet/maui#24657]
### Description

In the OnNavigatedTo event of Page, PreviousPage of NavigatedToEventArgs is declared as internal, so it cannot be used.

Is there a reason why you declared PreviousPage as internal? I want PreviousPage to be declared as public.

namespace Microsoft.Maui.Controls
{
	public sealed class NavigatedToEventArgs : EventArgs
	{
		internal NavigatedToEventArgs(Page previousPage)
		{
			PreviousPage = previousPage;
		}

		**internal Page PreviousPage { get; }**
	}
}

### Public API Changes

In the OnNavigatedTo event of Page, PreviousPage of NavigatedToEventArgs is declared as internal, so it cannot be used.

Is there a reason why you declared PreviousPage as internal? I want PreviousPage to be declared as public.

namespace Microsoft.Maui.Controls
{
	public sealed class NavigatedToEventArgs : EventArgs
	{
		internal NavigatedToEventArgs(Page previousPage)
		{
			PreviousPage = previousPage;
		}

		**internal Page PreviousPage { get; }**
	}
}

### Intended Use-Case

In the OnNavigatedTo event of Page, PreviousPage of NavigatedToEventArgs is declared as internal, so it cannot be used.

Is there a reason why you declared PreviousPage as internal? I want PreviousPage to be declared as public.

namespace Microsoft.Maui.Controls
{
	public sealed class NavigatedToEventArgs : EventArgs
	{
		internal NavigatedToEventArgs(Page previousPage)
		{
			PreviousPage = previousPage;
		}

		**internal Page PreviousPage { get; }**
	}
}

**Comment by PureWeen** [comment]
Duplicate of #21814
