### ISSUE TITLE
[Bug] Polygon doesn't redraw when given new points programmatically.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2467]
### Description
This may be related to https://github.com/dotnet/maui/issues/2464.

If you set an existing Polygon with new points, it does not redraw and will stay the same.

### Steps to Reproduce

Run this reproduction project and click "Update path"

[MauiTestSuite.zip](https://github.com/dotnet/maui/files/7150825/MauiTestSuite.zip)

### Expected Behavior

The polygon will change shape.

### Actual Behavior

Nothing happens.

**Comment by jsuarezruiz** [comment]
Already fixed in main branch.
![issue2467](https://user-images.githubusercontent.com/6755973/140287875-208ecbf1-fc98-465c-b0eb-ae4613cc5952.gif)
