### ISSUE TITLE
Android CollectionView loads all Views and locks up UI when soft keyboard shown.

### ISSUE THREAD

**Issue by JRC-BitBull** [dotnet/maui#24675]
### Description

On Android CollectionView appears to allocate Views for all elements when the soft keyboard is shown.

### Steps to Reproduce

1. Create a page with a CollectionView and Entry on Android
2. Set ItemsSource to a collection with a large number of elements
3. Set the MainActivity to respond to screen size changes
4. Click on the entry on the page to show the soft keyboard.

There is a massive lag and the UI locks up. This is due to a View being loaded from XAML for every item in the CollectionView. Initially the CollectionView loads fine with only visible Views being loaded but something about the screen resize causes a View to be loaded for every item.

I am testing this with the CollectionView in a grid, vertical layout, grid row set to '*' but not wrapped in any other layouts.

This issue pretty much renders CollectionView + Entry unusable on Android, at least for CollectionViews with a large number of elements.

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by JRC-BitBull** [comment]
Also happens with ListView.

**Comment by PureWeen** [comment]
Related https://github.com/dotnet/maui/issues/24078?
