### ISSUE TITLE
[Android] SearchHandler.Focused event never fires

### ISSUE THREAD

**Issue by peruchali** [dotnet/maui#24670]
### Description

The Focused event for Shell.SearchHandler does not fire on selecting it, even though the keyboard shows up.

### Steps to Reproduce

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.NewPage1"
             Title="NewPage1">
    <Shell.SearchHandler>
        <SearchHandler
            Focused="SearchHandler_Focused"
            Placeholder="Click to focus.." />
    </Shell.SearchHandler>
    <VerticalStackLayout>
        <Label 
            Text="Welcome to .NET MAUI!"
            VerticalOptions="Center" 
            HorizontalOptions="Center" />
    </VerticalStackLayout>
</ContentPage>
```

```cs
namespace MauiApp1;

public partial class NewPage1 : ContentPage
{
    public NewPage1()
    {
        InitializeComponent();
    }

    private void SearchHandler_Focused(object sender, EventArgs e)
    {
        // Set a breakpoint
    }
}
```

SearchHandler_Focused is never invoked on tapping on the SearchHandler.

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No workaround.

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12.0 Preview 1.0(8.0.82 & 8.0.80 &8.0.72). Can repro on Android platform.
