### ISSUE TITLE
Freeze when invoking SecureStorage.GetAsync().Result multiple times on Windows  

### ISSUE THREAD

**Issue by suugbut** [dotnet/maui#24687]
### Description

This issue has been fixed in Android: https://github.com/dotnet/maui/pull/17928, but still exists in Windows.

### Steps to Reproduce

Replace the code behind of `MainPage`  provided by Maui project's default template with the following code.

```cs
public partial class MainPage : ContentPage
{
    int count = 0;

    public MainPage()
    {
        InitializeComponent();
    }

    private async void OnCounterClicked(object sender, EventArgs e)
    {
        if (await SecureStorage.GetAsync("key") is null)
        {
            await SecureStorage.SetAsync("key", "value");
            Title = "key is created";
        }
        else
        {
            count++;

            // async version works for multiple calls
            // var key = await SecureStorage.GetAsync("key");

            // sync version freezes for the second call.
            var key = SecureStorage.GetAsync("key").Result;

            Title = $"{key} - {count}";
        }
    }
}
```

### Affected platforms

Windows

### Did you find any workaround?

```cs
// but sync version can be fixed with Task.Run()
var key = Task.Run(() => SecureStorage.GetAsync("key")).Result;
```

**Comment by mattleibow** [comment]
You really should not just call Result on Tasks as this will most certainly cause deadlocks. You can maybe try `GetAsync("X").GetAwaiter().GetResult()` but who knows what that will do.

We do not start task or anything in our code, so it is most likely the Windows implementation that is being deadlocked as you try and force it to run on your thread while it is busy doing something.
