### ISSUE TITLE
`HybridWebView` - `RawMessageReceived` event is not firing in .NET MAUI 9 RC1

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#24705]
### Description

`HybridWebView` - `RawMessageReceived` event is not firing in .NET MAUI 9 RC1.

This worked fine in .NET MAUI 9 Preview 7.

*Note: Add the RC1 version in the Version with bug field and Preview 7 version in the Last version that worked well field.*

### Steps to Reproduce

1. Clone the solution in the referenced GitHub repo
2. Build and run the app
3. Type and send a message from JS to C# from the second text field from the top.
4. Typically, this message would be received in the code-behind event handler but it's not working

### Link to public reproduction project repository

https://github.com/egvijayanand/maui-issue-24705

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI.

### Last version that worked well

9.0.0-preview.7.24407.4

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

Nope.

### Relevant log output

```shell
The message is logged with one character per line in the Web Dev Tools Debug console. It seems some dev debugging piece checked in.
```

**Comment by egvijayanand** [comment]
Here's the link to the repository with a sample project to simulate this issue.

https://github.com/egvijayanand/maui-issue-24705

**Comment by Eilon** [comment]
Hi @egvijayanand , it's probably because the HybridWebView.js file is out-of-date. It changed significantly from preview7 to rc1.

In your app replace the contents of this file: https://github.com/egvijayanand/maui-issue-24705/blob/main/src/HwvApp/Resources/Raw/wwwroot/scripts/hwv.js

With this file: https://github.com/dotnet/maui/blob/release/9.0.1xx-rc1/src/Controls/samples/Controls.Sample/Resources/Raw/HybridSamplePage/scripts/HybridWebView.js

**Comment by egvijayanand** [comment]
There's no mention about the modifications in the changelog?

Kindly include it here.

https://github.com/dotnet/core/blob/main/release-notes%2F9.0%2Fpreview%2Frc1%2Fdotnetmaui.md

And also suggest to pack the associated JS as an embedded resource like Blazor with a naming convention and a reference can be in the HTML file, so that it need not be looked into for every version.

**Comment by Eilon** [comment]
Thanks @egvijayanand , I sent a PR here to update the notes: https://github.com/dotnet/core/pull/9501

For embedding the JS file, that is unfortunately out of scope for .NET 9 right now but definitely something we'll look into in the future.

**Comment by egvijayanand** [comment]
Cool, the release notes got updated.

#24730 - Logged as a feature request to track the JS as an embedded resource.
