### ISSUE TITLE
file

### ISSUE THREAD

**Issue by najibebrahimi** [dotnet/maui#24719]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mattleibow** [comment]
Please:

> Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
