### ISSUE TITLE
[Unstable][MAUI][NET8]Recipe names are truncated on recipe pages

### ISSUE THREAD

**Issue by Zhanglirong-Winnie** [dotnet/maui#24735]
### Description

Recipe names are truncated on recipe pages

### Steps to Reproduce

1. Deploy  https://github.com/rachelkang/recipeSearch to iOS/MacCatalyst platform.
2. Observe the recipe name displayed on the recipe page

**Actual Behavior:**
Recipe names are truncated on recipe pages
![image](https://github.com/user-attachments/assets/ca7fa5e3-a9e2-4df4-816f-573e419e94f2)

**Expected Behavior:**
Recipe names on recipe pages are displayed in full
![image](https://github.com/user-attachments/assets/9ba8cf4e-554e-40a9-b7b7-6ddd342d6121)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch 

### Version with bug

Microsoft.Maui.Controls 8.0.90-ci.net8.24461.1

### Is this a regression from previous behavior?

Not a regression, the issue is not stable and reproducible on lower versions.

### Affected platforms

iOS, macOS

**Comment by mattleibow** [comment]
This looks to be a scrollview with buttons: https://github.com/rachelkang/recipeSearch/blob/main/WhatToEat/Views/StartingPage.xaml#L42-L51

@tj-devel709 maybe this is related to your changes?

**Comment by mattleibow** [comment]
@Zhanglirong-Winnie you mention "the issue is not stable and reproducible on lower versions" what versions have this and what versions work correctly?

**Comment by Zhanglirong-Winnie** [comment]
Hi, @mattleibow 
This issue sometimes repro on 8.0.82, and sometimes repro on 8.0.3.
