### ISSUE TITLE
Remove excessive API docs in comments

### ISSUE THREAD

**Issue by axa88** [dotnet/maui#24731]
### Description

in the spirit of #24037 and #24114, the excesses in `Picker` should be removed as well.
There's probably others.  Full examples have no place here

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

NA

**Comment by jfversluis** [comment]
Thanks! Opened a PR for this. If you're up for it, indeed open a PR yourself! These should be easy contributions and ".NET MAUI contributor" would look amazing on your LinkedIn profile! 😉
