### ISSUE TITLE
iOS Buttons without enough padding are truncated in certain scenarios

### ISSUE THREAD

**Issue by tj-devel709** [dotnet/maui#24746]
## Description
In SR9, iOS Buttons have a lot of changes that allow more customization and more accurate layouts. A product of these changes is that the control will respect the values given by the user as much as it can. However, when iOS's UIButton lays out the image and text, they are always rendered side-by-side horizontally. If there is not enough room for the whole title and image, the title is truncated.

Prior to these SR9 button changes, there were situations where the spacing between the image and title and the padding were not accurate but tried to make the button fit. This behavior was not very intuitive for the user and sometimes led to unexpected behavior. The new changes make it so the customer has more control, but given how iOS lays out the button, there are cases that may need to be adjusted by the user.

In the case where a user has the image on top or bottom of the title and the parent of the button has an infinite width constraint (such as a button inside a HorizontalStackLayout) or when the button does not have the horizontalOption set to fill, we are required to have enough space for the image and title to be rendered before we move the image above or below the title. This can be done through padding or by requesting the width of the button be large enough. 

Right now, if the button has the default padding, it will try to change the padding to whatever the button needs to not have the title truncated. If you have an explicit padding set, the button will use that padding value.

#### In the images below, you can see what the button looks like before moving the image above the title.<br /><br />
 

In this first image, the padding is not set so the button will use a padding to ensure the image and title are not truncated.
<img height="250" alt="image" src="https://github.com/user-attachments/assets/9a0b842a-1be2-461c-a056-772ff90d8124">

In this second image, the padding is set to a small value. On the left, it is apparent that there is not enough space for both the image and the title thus the title gets truncated.
<img height="250" alt="image" src="https://github.com/user-attachments/assets/9bde1c24-ef31-4fa3-b69d-7acdd68925de">

In this third image, the padding is the same small value, but a WidthRequest was added to ensure the button had enough space for the image and title.
<img height="250" alt="image" src="https://github.com/user-attachments/assets/0839bea4-8668-4d16-8517-a9e1f78ca619">
 
## Action
If you had a iOS button that was not truncated before in the scenario described above and is now truncated you can do either of the following:
1) Remove the padding on that button so that MAUI will generate a padding that will ensure the title and image are not truncated.
2) Increase the padding to a value that creates enough space for the image and title to fit.
3) Add a WidthRequest to your button large enough for the image and title to fit.

## Future Proposal
What we may do in the future is ensure there is always enough room in the button for the title and image by increasing the padding to the required amount. If the set padding already ensures there is enough room, we can just use that value.
<br /><br /><br /><br />
### Steps to Reproduce

1. Create a MAUI project.
2. Add a Button that has HorizontalOption set to Center and change the ContentLayout so the image is on top with a small padding.
```xaml
<VerticalStackLayout>
    <Button Text="Hello, longer world!" ImageSource="dotnet_bot.png" TextColor="White"
        Background="purple" Padding="10" ContentLayout="Top,0" HorizontalOptions="Center" />
</VerticalStackLayout>
```
3. Deploy to an iOS device and see the title is truncated

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Did you find any workaround?

Any of the following three steps:

1) Remove the padding on that button so that MAUI will generate a padding that will ensure the title and image are not truncated.
2) Increase the padding to a value that creates enough space for the image and title to fit.
3) Add a WidthRequest to your button large enough for the image and title to fit.

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12.0 Preview 2.0(9.0.0-rc.1.24453.9 & 8.0.82). Can repro on iOS platform. 8.0.82 works fine.
