### ISSUE TITLE
[Bug] MediaPicker.CapturePhotoAsync() issue in OnePlus Pro physical device

### ISSUE THREAD

**Issue by zeus2nawaz** [dotnet/maui#2474]
I have an application which is using Camera Via **MediaPicker.CapturePhotoAsync()**, It is working as expected in Android Emulator 30, But issue in real device, When I run this it crash the application 

I am using NET 6 RC1

**Comment by Tkumar2021** [comment]
@zeus2nawaz I have also implemented this feature in one of my .Net MAUI demo but it was not working on emulator as well on my side. Can you help me how could you able to do it on emulators?
