### ISSUE TITLE
[Bug] FlyoutBehavior in WinUI shows duplicated hambruger and crash

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#2475]
### Description
Using a Flyout with FlyoutBehavior="Split" hamburger menu icon is duplicated in the detail page and the flyout:
![image](https://user-images.githubusercontent.com/603023/133251749-a6b33329-a56a-491b-a9de-3d43b7547189.png)

### Steps to Reproduce

1. Run WinUI protect from the given zip
[FlyoutDoNotRender.zip](https://github.com/dotnet/maui/files/7161580/FlyoutDoNotRender.zip)
2. Tap on hamburger menu

### Expected Behavior
No hamburger menu must be shown
### Actual Behavior
The hamburger menu is duplicated
When hamburger menu is tapped the app crashes

**Comment by PureWeen** [comment]
appears to be fixed on P14

![image](https://user-images.githubusercontent.com/5375137/156812819-7434caee-eddc-487d-b48e-177032c40502.png)
