### ISSUE TITLE
.NET 9 Preview not working on android

### ISSUE THREAD

**Issue by Natriss** [dotnet/maui#24761]
### Description

Visual Studio does not want to run a .net 9 preview maui project in android. It does deploy and fully launches on windows.

https://github.com/user-attachments/assets/0cb662bc-bf81-41a8-af9f-2d653c719c24

### Steps to Reproduce

1. Create a .NET 9 preview maui project
2. Click on run with debugger

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by Natriss** [comment]
https://developercommunity.visualstudio.com/t/NET-9-Preview-not-working-on-android/10745522

**Comment by jaosnz-rep** [comment]
@Natriss Please open the solution's properties page and check the deploy option. If you have any other questions, please feel free to contact me.
<img width="583" alt="image" src="https://github.com/user-attachments/assets/48783efc-ed07-4cdc-b60d-f291520af525">

**Comment by Natriss** [comment]
So that is not checked by default anymore.
That is so weird of them to disable that by default.
