### ISSUE TITLE
Regression Alert! Shadow parameters got factored?! Danger to production apps!

### ISSUE THREAD

**Issue by MauiUIui** [dotnet/maui#24773]
### Description

Somewhere between Maui Controls 8.0.40 (I was using before this) and 8.0.90 (Version where I updated and noticed problem) something went wrong with the shadows (I'm experiencing that on label shadows). Using the same shadow values I suddenly have a totally different outcome:
`<Shadow Radius="10" Opacity="0.8" Brush="{StaticResource Gray600}" Offset="12,12" />`
To get *almost* the same result I had before, I had to use:
`<Shadow Radius="3.7" Opacity="0.8" Brush="{StaticResource Gray600}" Offset="4,4" />`
![40 vs 90](https://github.com/user-attachments/assets/24685a7d-fb04-4313-bb1f-0fca5fa79389)
It seems like the values were factored down to about 1/3
Is that correct?
I was about to launch an update for my app already in production and noticed this after updating. I could update the values of my shadows (I have many) but such an effect throughout an update shouldn't happen in non-preview versions. Was a notice given about this?

### Steps to Reproduce

Using Microsoft.Maui.Controls 8.0.40
Add a label with the following shadow:
`<Shadow Radius="10" Opacity="0.8" Brush="{StaticResource Gray600}" Offset="12,12" />`
Run App
Make screenshot
Upgrade to Microsoft.Maui.Controls 8.0.90
Run app
Make screenshot
compare screenshots

### Link to public reproduction project repository

No need to reproduce on own machine. Screenshots were added

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by PureWeen** [comment]
@MauiUIui if you test on version 8.0.82 do you see the same issue?

**Comment by albyrock87** [comment]
So the fact is: shadows on iOS have always been wrong in `Radius` (while offset is correct).

> It seems like the values were factored down to about 1/3

The factor is actually 0.5.
We've corrected the shadow size to match the expectations.
See #24415 for all the details.

**Comment by PureWeen** [comment]
@MauiUIui unfortunately when Shadows were first written we weren't converting the scaled sizes to pixels so the shadow on android was unfortunately inaccurate. This would actually cause the shadow to change based on the type of device/scale factor the app was running on. The shadows should now be rendering in a way that is much more consistent and accurate to the passed in values.

**Comment by MauiUIui** [comment]
@PureWeen thanks for the clarification. One suggestion would be to include a (rather huge) note about this in the release notes, since it is something that notably changes the looks of apps in production once an update is done.
Probably something like:
```
Appearance Changes:
1-
2-
```

**Comment by MauiUIui** [comment]
> The factor is actually 0.5. We've corrected the shadow size to match the expectations. See #24415 for all the details.

@albyrock87 Thanks for the  clarification. 0.5 would be for both offset and radius (on Android)? Knowing would ease up my modifications hugely :)

**Comment by albyrock87** [comment]
So let's say you had radius=5 and offset=8,8 on iOS with MAUI 8.0.40.

To keep the appearance you had at that time, you should now use radius=10 and keep offset=8,8.

Then I guess you want to have the same appearance on Android. If that's the case, just put the same values you now use on iOS: radius=10 and offset=8,8.

Basically you can get rid of `OnPlatform`.
Now all platforms behave the same.

**Comment by MauiUIui** [comment]
> Then I guess you want to have the same appearance on Android. If that's the case, just put the same values you now use on iOS: radius=10 and offset=8,8.

I'm only doing Android for now. But I'm actually experiencing quite the opposite. 
With radius=5 and offset=8,8 before, I find myself now having to **halve** (not double) the amount, and that for both offsite and radius to get a result **close to** what I had.

**Comment by albyrock87** [comment]
Wait, Android had a different issue.
Instead of using DP (device pixels) it was using physical PX.

So the behavior varied depending on the display density of each device.

Let's say you had radius=5 and offset=8,8.

Now if you were using a device with pixel density=2, your shadow was actually looking as radius=2.5 offset=4,4.
A different device with different density resulted in a different shadow.

We can say that on average the display density used by manufacturers is probably around 2.3 or 2.5.
So you should probably divide everything you had by 2.5 (both radius and offset).

With the latest SR Android uses DP to set shadows, so what you set is what you get.

**Comment by MauiUIui** [comment]
@albyrock87 That would explain why I was seeing almost a /3 factor. I'm doing (/3 - x) so almost deviding by 2.5 to get the before results. Thanks. Should I close the issue now?

**Comment by albyrock87** [comment]
> @albyrock87 That would explain why I was seeing almost a /3 factor. I'm doing (/3 - x) so almost deviding by 2.5 to get the before results. Thanks. Should I close the issue now?

MAUI is now behaving correctly, so yes, you can close this issue, which was useful to explain what happened in detail :)
