### ISSUE TITLE
Linebreaks in XAML content is not persistent during HotReload

### ISSUE THREAD

**Issue by Toine-db** [dotnet/maui#24770]
### Description

HotReload removes line breaks (and possibly spacing) from XAML content, resulting in displaying the views as not what it really will be. 

For example using the Label property Text, it supports linebreaks in XAML like so: 
[(see documentation)](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/label?view=net-maui-8.0#add-new-lines)
```
<Label>
    <Label.Text>
        First line with some extra text
        Second line
    </Label.Text>
</Label>
```

Resulting on screen after hot Reloaded in:
>         First line with some extra textSecond line

Issue:
- First build and visual on debug device is not the same after the first HotReload

The examples are based on Label because it the easiest and most common view supporting line breaks, but this also happens with other views that support and/or are dependent on line breaks in XAML.

### Steps to Reproduce

1. Add Label with multiple line in XAML, like:
```
<Label>
    <Label.Text>
        First line
        Second line
    </Label.Text>
</Label>
```
2. Start Debug session
3. Show view on debug device, it will show:
>         First line
>         Second line
4. Change Label text (while shown on debug device), like:
```
<Label>
    <Label.Text>
        First line, adding some text
        Second line
    </Label.Text>
</Label>
```
5. Check view on debug device, it will show:
>         First line, adding some textSecond line

it should be:
>         First line, adding some text
>         Second line

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

Using `xml:space="preserve"` on specific view (like a Label) prevents loosing line breaks and spacing during HotReload.
BUT...you can not build with `xml:space` because you will get the build error that it can't find property 'Space'.

So the workaround is a combination of 
1. using `xml:space="preserve"` in XAML 
2. adding the (unused) property 'space' to the specific view like this:
```
public class MyCustomLabel : Label
{
    /// <summary>
    /// Workaround: space (lowercase) required for using xml:space="preserve" in XAML to keep linebreaks and spaces during HotReload
    /// </summary>
    public static readonly BindableProperty SpaceProperty = BindableProperty.Create(nameof(space), typeof(string), typeof(MyCustomLabel), "preserve");
    public string space
    {
        get => (string)GetValue(SpaceProperty);
        set => SetValue(SpaceProperty, value);
    }
}
```

Note: when using a Label you first need to create your inherited custom label, to be able to change/add the property to the Label. When using your own (already) custom view, you just need to add the property.

**Comment by drasticactions** [comment]
CC @etvorun 

Yeah, the new lines inside those fields are stripped when you edit the text in the editor during the hot reload session. If you set new text with new lines for the given label text, it updates with new lines fine. The literal value being inserted has no spaces. This is not a MAUI bug, it should be moved to Visual Studio.

**Comment by Toine-db** [comment]
For the MAUI devs, the workaround should allow you to continue working.

I passed this issue on to the VS team.
https://developercommunity.visualstudio.com/t/Linebreaks-in-XAML-content-is-not-persis/10745941?port=1025&fsid=a4f27135-4e59-492f-a3a4-27e19258e685

**Comment by tj-devel709** [comment]
Thanks for creating the issue with the VS team. I will close this issue here, but feel free to re-open the issue if needed!
