### ISSUE TITLE
[iOS] [8.0.90] Images not showing up

### ISSUE THREAD

**Issue by borrmann** [dotnet/maui#24784]
### Description

since 8.0.90 images aren't always rendered

### Steps to Reproduce

it is completely random. Sometimes they show, sometimes they don't. 
It effects both DataTemplates and regular Xaml.

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

iOS

### Affected platform versions

only tested iOS

### Did you find any workaround?

rolling back to 8.0.82

**Comment by tj-devel709** [comment]
Hello, could you please provide us with a repro sample or link to github project that sometimes displays this behavior?

**Comment by borrmann** [comment]
Apologies, this seemed to have been some caching issue. after several cleans and rebuilds the issue disappeared.
