### ISSUE TITLE
Error in Xamarin .Shared.targets

### ISSUE THREAD

**Issue by zekedaddy17** [dotnet/maui#24790]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: macos

[{
	"resource": "/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk.net8.0_17.5/17.5.8030/tools/msbuild/iOS/Xamarin.Shared.targets",
	"owner": "maui",
	"severity": 8,
	"message": "0 Warning(s)",
	"startLineNumber": 1866,
	"startColumn": 3,
	"endLineNumber": 1866,
	"endColumn": 3
}]

I am trying to run the .NET MAUI Tutorial and get to the run and debug piece and there are errors that won't let me proceed forward. In Xamarin.Shared.targets there is an error on line 1866 where the DetectSdkLocations is at. 

Sonoma 14.6.1
Xcode installed today.
VS Code installed today. 
dotnet --verstion 8.0.401
dotnet --list-sdks several but also 8.0.401

**Comment by zekedaddy17** [comment]
additional comment is Xcode is 15.4

**Comment by jfversluis** [comment]
Does the VS Code extension give any meaningful output? If you do run the command to refresh the Apple environment in VS Code does that do anything?
