### ISSUE TITLE
+[IMKClient subclass]: chose IMKClient_Legacy +[IMKInputSession subclass]: chose IMKInputSession_Legacy macOS 15.0

### ISSUE THREAD

**Issue by markatosi** [dotnet/maui#24794]
### Description

Created a new Maui Blazor and or regular Maui application and run the application on Mac Intel. The Maui application window
displays and when you click anywhere on the Maui window the following message displays in the JetBrains run log window. The message only displays one time and the application appears to function normally. I tried this with both 8.0.82 and 8.0.90

2024-09-16 09:43:18.090 MauiApp15Hybrid2[12274:200309] +[IMKClient subclass]: chose IMKClient_Legacy
2024-09-16 09:43:18.090 MauiApp15Hybrid2[12274:200309] +[IMKInputSession subclass]: chose IMKInputSession_Legacy   

### Steps to Reproduce

1. Create a new Maui application (Either blazor hybrid or regular Maui app)
2. Run the application on a Mac (I'm using Intel so I can't test silicon at the moment)
3. Click on the running Maui window
4. Observe the error in whatever output window you are using

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Maccatalyst on macOS 15

### Did you find any workaround?

No.

### Relevant log output

```shell
2024-09-16 09:43:18.090 MauiApp15Hybrid2[12274:200309] +[IMKClient subclass]: chose IMKClient_Legacy
2024-09-16 09:43:18.090 MauiApp15Hybrid2[12274:200309] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
```

**Comment by daniel-moulton** [comment]
Perhaps may be of use, but as of today I started getting a similar message in my python project (program also seems to function as normal), so might not inherently be a Maui issue but a macOS issue perhaps.
```
python3 main.py
2024-09-17 19:39:41.775 Python[16833:333096] +[IMKClient subclass]: chose IMKClient_Legacy
2024-09-17 19:39:41.775 Python[16833:333096] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
```

**Comment by markatosi** [comment]
I also later noticed it in an Electron version of my application but that version wouldn’t fully start. This issue wasn’t happening in a developer beta of Sequoia last month, so it’s something relatively new.

**Comment by jfversluis** [comment]
I see other reports of this happening for completely other ecosystems so probably something in Sequoia and we don't support that yet, see https://github.com/xamarin/xamarin-macios/issues/20802

Lets reevaluate if this is still a thing once the official support is there and this is still an issue. If that's the case, you probably want to open this issue on the macios repo directly. Closing this for now here!

**Comment by Anonymouse-dev** [comment]
Immediately after upgrading to sequoia, I started getting these messages on an off in the Terminal:
2024-09-19 02:08:59.925 Python[22821:402672] +[IMKClient subclass]: chose IMKClient_Legacy
2024-09-19 02:08:59.925 Python[22821:402672] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
Series([], Name: corr_esm_minmax_30m_slope, dtype: float64) 

(corr_esm_minmax_30m_slope,) refers to a specific column in a Pandas dataframe

Nothing has been changed in the code recently, so this is quite certainly a Sequoia issue. App otherwise appear to be functioning normally. Running Python 3.12 on MacOS. OS Version: Darwin 24.0.0

**Comment by PedanticHacker** [comment]
Visual Studio has been retired for Mac as of August 31, 2024, so perhaps this is why we are now seeing such strange messages in VS Code on the Mac. I have a MacBook Air M3 running macOS 15.0 (a.k.a. Sequoia) and I'm also seeing exactly these messages.

I found this information here: https://learn.microsoft.com/en-us/visualstudio/releases/2022/what-happened-to-vs-for-mac

**Comment by PedanticHacker** [comment]
Maybe because of the retirement, VS Code reports that it is using a legacy client. I'm also thrown away by this. I'll probably use my good old Sublime Text from now on. ;)

**Comment by PedanticHacker** [comment]
I have switched from VS Code to Sublime Text on macOS 15.0 and I'm getting the very same messages, as the OP does, on both apps.

Can anyone running the latest beta of macOS 15.1 try to see whether it's the same story on macOS 15.1?

**Comment by dexwert** [comment]
yea I have this annoying message too, when ever I am working on my platform layer for my game engine in xcode because I need objc support the program run 3 times the first one is in xcode the the others in terminal to show this messages I thought its an xcode issue but its not when I tried to run it on terminal (I have macOS 15.0.1)

**Comment by couet** [comment]
I have it also on may mac running sequoia with my application started for the terminal

**Comment by dexwert85** [comment]
did they fix the issue?

**Comment by crkhov** [comment]
Same with **Eclipse 2024-09 (4.33.0)** on **macOS Sequoia 15.0.1**.

- _From_ **Eclipse**; _ran_ an '_unsigned_' Java app and **Eclipse's Console** _outputted_:

```log
java[79662:1266128] +[IMKClient subclass]: chose IMKClient_Legacy
java[79662:1266128] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
```

- Launched **macOS**' native **Console.app** to determine _system_ or _software_ issue(s).

I caught a few messages RE: Eclipse's _**system**_ and _**file permissions**_. _**To decrease time to troubleshoot any further**_, fixed those issues by _explicitly_ adding **Eclipse.app** to the list of apps that have **Full Disk Access**. _Re-ran Java app a few times_ for duplicated messages.

Based on the time that _I ran the Java app from Eclipse_ and _Eclipse's Console output_, then comparing that time with time of attribution logged on _macOS' Console.app_, my Java app had triggered macOS' **TCC** (**tccd**) **Framework**.

```
/System/Library/PrivateFrameworks/TCC.framework/Support/tccd
```

And the message:

```log
AUTHREQ_ATTRIBUTION: msgID=79662.1, attribution={responsible={TCCDProcess: identifier=SigningServlet-###################-unsigned-eclipse, pid=79408, auid=502, euid=502, responsible_path=/Users/${whoami}/eclipse/java-2024-09/Eclipse.app/Contents/MacOS/eclipse, binary_path=/Users/${whoami}/eclipse/java-2024-09/Eclipse.app/Contents/MacOS/eclipse}, requesting={TCCDProcess: identifier=net.java.openjdk.java, pid=79662, auid=502, euid=502, binary_path=/opt/homebrew/Cellar/openjdk@21/21.0.5/libexec/openjdk.jdk/Contents/Home/bin/java}, },
```

**Comment by PedanticHacker** [comment]
I just installed macOS 15.1 (final public version) and this annoyance still persists!

**Comment by crkhov** [comment]
**UPDATE**, Going to stop traversing into  rabbit hole, but after I post this **UPDATE**.

- RE: _**Unsigned**_ _Java_ app triggered **macOS' TCC Framework**. 

 
- RE: IMKClient_Legacy and IMKInputSession_Legacy [(Apple Developer / Framework / InputMethodKit),](https://developer.apple.com/documentation/inputmethodkit) these topics are out of my scope.
- What I've searched and understood thus far is posted here, **[Why This Message Appears](https://github.com/zegervdv/homebrew-zathura/issues/129#issuecomment-2360382975)**. Warnings can be suppressed.
>The messages indicate that macOS is using legacy versions of IMKClient and IMKInputSession for handling input. 
- Also, someone has posted issue via OpenJDK Bug Forum; [JDK](https://bugs.openjdk.org/browse/JDK)[JDK-8340330](https://bugs.openjdk.org/browse/JDK-8340330)

**EOM**

**Comment by GameBakerStudio** [comment]
This is an issue I've seen everywhere on MacOS Sequoia 15. I've seen it in Tauri, Swing, OpenGL, GLFW, and now Maui. According to someone on the GLFW website, it was likely a debug left in on Apple, which could be related to their switch to SwiftUI or Metal from OpenGL. The warning seems to have no impact on performance or security, and I would simply wait until a future update, and contact AppleINC.

**Comment by dexwert85** [comment]
> I just updated to Sequoia **15.1**, the warning message still persists..

Me too

**Comment by dexwert85** [comment]
> This is an issue I've seen everywhere on MacOS Sequoia 15. I've seen it in Tauri, Swing, OpenGL, GLFW, and now Maui. According to someone on the GLFW website, it was likely a debug left in on Apple, which could be related to their switch to SwiftUI or Metal from OpenGL. The warning seems to have no impact on performance or security, and I would simply wait until a future update, and contact AppleINC.

I dont think its because of the switch to SwiftUI or Metal because even if you used them it will give you the same issue for example if you use cocoa you will get the issue even if its for apple

**Comment by svenschwarz** [comment]
Apple also seem to give a f*** about that.

**Comment by nuncio-bitis** [comment]
I'm getting the same errors for applications built on Mac OS Sequoia for Mac OS Sequoia in Qt, python, and VS Code
I've been searching around and it looks like there are bugs in Sequoia that we have to wait for Apple to fix in the next OS version.

**Comment by dexwert85** [comment]
But why they dont fix it

**Comment by bjanders** [comment]
I'm learning OpenGL, and did the most simple tutorial OpenGL application ("Hello triangle") and I get these messages on macOS 15.1 as soon as I call glfwPollEvents().
