### ISSUE TITLE
FlyoutItemIsVisible property in Shell Items is always true

### ISSUE THREAD

**Issue by gonultasmf** [dotnet/maui#24797]
### Description

The following definition is made within the Shell:
```xaml
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiApp4.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp4"
    Shell.FlyoutBehavior="Disabled"
    Title="MauiApp4">

    <ShellContent
        Title="Home"
        ContentTemplate="{DataTemplate local:MainPage}"
        FlyoutItemIsVisible="True"
        Route="MainPage" />

    <ShellContent
        Title="NewPage1"
        ContentTemplate="{DataTemplate local:NewPage1}"
        FlyoutItemIsVisible="False"
        Route="NewPage1" />

    <ShellContent
        Title="NewPage2"
        ContentTemplate="{DataTemplate local:NewPage2}"
        FlyoutItemIsVisible="False"
        Route="NewPage2" />

</Shell>

```
As you can see, only one of the ShellContent has its FlyoutItemIsVisible property set to **true**.

```csharp
namespace MauiApp4
{
    public partial class AppShell : Shell
    {
        public AppShell()
        {
            InitializeComponent();

            var list = this.Items.Where(e => e.FlyoutItemIsVisible).ToList();
        }
    }
}

```
![image](https://github.com/user-attachments/assets/15adf45d-3ff7-49b0-a74d-b6d58e33745c)

But when I debug the code; all ShellContent items have come to my list variable. When I examine it, the FlyoutItemIsVisible value of all items is True.

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

Unfortunately

**Comment by PureWeen** [comment]
I don't think this is a bug

One of the somewhat unfortunate things about `Shell` is that the structure in your XAML doesn't fully match the logical structure that gets created. 

The Items you are filtering there are ShellItems not ShellContent

If you use Linq to `SelectMany` down to the `ShellContent` you'll notice that it is set on all of the `ShellContent` elements

**Comment by gonultasmf** [comment]
I understand what you mean. This is a sad thing. When I filtered as you said, I saw that it worked correctly:
```csharp
namespace MauiApp4
{
    public partial class AppShell : Shell
    {
        public AppShell()
        {
            InitializeComponent();

            var visibleShellContents = this.Items
                .SelectMany(e => e.Items)
                .SelectMany(e => e.Items)
                .Where(content => content.FlyoutItemIsVisible)
                .ToList();
        }
    }
}
```

Thank you for your support
