### ISSUE TITLE
Unable to validate .IPA file because of AppIcon missed

### ISSUE THREAD

**Issue by FAQEnD** [dotnet/maui#24796]
### Description

We migrated a project from Xamarin.Forms to MAUI. Now we need to publish it on AppStore, tried with [Transporter](https://apps.apple.com/us/app/transporter/id1450874784) app and with manual terminal command. Always faces same error (Please see logs section).
Then we tried with simple app from MAUI templates. We created a new, clear MAUI app, updated it with our bundleID and signed with our distribution cerfitifacte. Same result! Even with a super-simple MAUI template app.

### Steps to Reproduce

1. Create a file > New MAUI .NET app
2. Update it with proper BundleID and cerificate
3. Build and sign it with your distribution certificate (Jenkins do it for us)
4. Try to verify your .IPA file with Transporter app by Apple

Actual result: You will face errros from log section
Expected result: App should be verified successfully

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17, iOS 18 beta

### Did you find any workaround?

Not yet

### Relevant log output

```shell
Asset validation failed (90713)
Missing Info.plist value. A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'com.ourcompanybundle.app'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7. (ID: f20bb72c-02ab-40bb-a1f2-6a0ec480d6c9)
 
Asset validation failed (90022)
Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 10.0. To support older versions of iOS, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface (ID: 336a3ded-5d7f-4010-a21d-44cd57af4a27)
 
Asset validation failed (90023)
Missing required icon file. The bundle does not contain an app icon for iPad of exactly '152x152' pixels, in .png format for iOS versions >= 10.0. To support older operating systems, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface (ID: d91e7650-addf-4c9c-96a3-e599bf64af39)
 
Asset validation failed (90023)
Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format for iOS versions supporting iPad Pro. To support older operating systems, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface (ID: 814870e5-8047-4bea-922a-7fb296c0a391)
```

**Comment by w0desym** [comment]
@jfversluis I see a bunch of issues related to Transporter which you worked on. Could you take a look at this one?

**Comment by tj-devel709** [comment]
Hi, thank you for your feedback. Could you confirm that the appIcon exists in the Resources of your project and maybe could you paste your csproj file with any sensitive information redacted?

**Comment by jfversluis** [comment]
As asked by TJ, check your csproj file for multiple entries of your icon file, that sometimes messes up things. If you like us to have a look please post the contents of your .NET MAUI project csproj file and make sure to remove any potential sensitive data from there.

If you download the IPA file and rename it to .zip and inspect what is in there, do you see your icons somewhere in there?

**Comment by FAQEnD** [comment]
Hi everyone, after two days we finally solved issue. Now we have .IPA file which successfully validated by Apple Transporter app.
We using this command to build .IPA file:
`dotnet msbuild ${component}/${component}.csproj /p:Configuration=${configuration} /p:Platform=AnyCPU /p:TargetFramework=net8.0-ios /p:RuntimeIdentifiers="ios-arm64" /p:BuildIpa=true /p:OutputPath='../Builds/' /p:IpaPackageDir='../Builds/' /t:Build \
/p:SetVersion=true /p:BundleVersion=${version} /p:Version=${version} /p:BundleShortVersionString=${shortVersion}`

### How we managed to fix it:
We removed `/p:RuntimeIdentifiers="ios-arm64"` from build flags and put it into **.csproj** file like this: `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>`. **After this changes it works as expected. MAUI builded a proper .IPA file and Transporter validated it successfully.**

### Additional notes: 
I'm working on Rider IDE using MacBook. We build distribution builds using Jenkins and rebuild everything from scratch, so it's not a cache or bin/obj issue.

@jfversluis answering on your question. If we unpack "invalid" .IPA file, we able to see all required AppIcons in all sizes inside **Assets.car** file, so I think **.png** files are generated properly, but then under the hood path to this images or something else was misconfigured because MAUI was not able to find `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` in **.csproj**  file.
I think it would be super useful if you can add somewhere in MAUI docs information about this field and put it in MAUI standard template.

Best Regards,
Anton

**Comment by jfversluis** [comment]
Glad you figured it out! Thanks for letting us know!
