### ISSUE TITLE
Default .NET MAUI Blazor Hybrid App fails to run on Windows 11 with Visual Studio 17.11.2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24795]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Deafult-NET-MAUI-Blazor-Hybrid-App-fail/10741406)._

---
I created a default .NET MAUI Blazor Hybrid App in Visual Studio 2022 v17.11.2.  
Using Windows 11 Pro 23H2

Then I switched to Release mode and Windows Machine and built.

The app built fine (weirdly for both Android and Windows which is a huge nuisance and time delay).

In the bin directory MauiApp1\\bin\\Release\\net8.0-windows10.0.19041.0\\win10-x64 there is a MauiApp1.exe but trying to launch it failed.  
Event viewer shows:

Faulting application name: MauiApp1.exe, version: 1.0.0.0, time stamp: 0x66960000  
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4111, time stamp: 0x03c619d0  
Exception code: 0xe0434352  
Fault offset: 0x000000000005fabc  
Faulting process id: 0x0x6598  
Faulting application start time: 0x0x1DB030C9B7A90A1  
Faulting application path: C:\\Dev\\MauiApp1\\bin\\Release\\net8.0-windows10.0.19041.0\\win10-x64\\MauiApp1.exe  
Faulting module path: C:\\WINDOWS\\System32\\KERNELBASE.dll  
Report Id: fe9cd5fc-bb71-4e24-bd24-e32e61769e98  
Faulting package full name:  
Faulting package-relative application ID:

---
#### Feedback Bot on 9/9/2024, 08:43 PM: 

(private comment, text removed)
#### Matthew Leibowitz [MSFT] on 9/10/2024, 10:49 AM: 

(private comment, text removed)
#### Dave Anderson on 9/10/2024, 02:29 PM: 

(private comment, text removed)
#### Dave Anderson on 9/10/2024, 02:58 PM: 

(private comment, text removed)
#### Dave Anderson on 9/10/2024, 02:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Looked through the public comments on the original VS Feedback issue and the issue happens for regular MAUI apps too. So this is not Blazor related.

**Comment by mkArtakMSFT** [comment]
@samhouts I've removed the blazor label intentionally, based on the comment above. So this is not a Blazor specific issue.
Also, @BethMassi mentioned that she can't reproduce this issue so I'll let you handle this as needed.

**Comment by jfversluis** [comment]
How did you start the app? Just by double-clicking? Because that might not always work depending on how the app is built. What are the exact steps that were taken to get into this state?
