### ISSUE TITLE
[META] Xcode 16.0 Support for .NET 8/9 and MAUI

### ISSUE THREAD

**Issue by jfversluis** [dotnet/maui#24819]
_Description below is copied from the .NET for iOS repository, please check [that issue](https://github.com/xamarin/xamarin-macios/issues/20802) for the latest actual state._

---

⚠️ Xcode 16 support is now released for .NET 8, please see release notes https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-8.0.1xx-xcode16.0-8303 for installation instructions. This version of the macios workloads will be also included in the next version of Visual Studio 17.11.5.

---
The current plan is to release Xcode 16 support with .NET 9 in November.

The current stable version of our workload _is not compatible with Xcode 16_. We recommend against upgrading until .NET 9 is released.

> [!WARNING]
Xcode 15.4 does not support macOS 15 (Sequoia). This also means that we don't recommend upgrading your macOS development machines until .NET 9.

---

You can follow our progress here:

https://github.com/xamarin/xamarin-macios/wiki/xcode16.0-Bindings-Status

**Comment by phillippschmedt** [comment]
This breaks your promise on the LTS. 
.NET 8 is LTS until November 10, 2026.
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
_"Add support for a new operating system version or new hardware platform."_

Or does this LTS not include .NET MAUI?

**Comment by phillippschmedt** [comment]
Thanks a lot for your work. I would kindly ask to provide XCode 16 support for .NET 8/MAUI. We need a break from updating and bug fixing. Please.

.NET 8 is suppose to be supported until November 10, 2026 (https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
.NET 8 MAUI is suppose to be supported until May 14, 2025 (https://dotnet.microsoft.com/en-us/platform/support/policy/maui)

**Comment by davidortinau** [comment]
We are currently validating Xcode 16 compatible builds for .NET 8 and .NET 9. Thanks for your patience as we complete that QA work.

In the meantime, let me recommend that you verify all your tools and SDKs are compatible with a major OS release **before** you update your primary development environment. I also recommend you don't allow key things like macOS, Xcode, Android, etc. to auto-update, at least to major breaking versions.

**Comment by yalamandarao** [comment]
Currently I'm also facing same issue after I update Mac OS and Xcode 16. I'm unable to run the application.

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8030/targets/Xamarin.Shared.Sdk.targets(2260,3): error : /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8030/tools/bin/mlaunch exited with code 1: [/Users/testmac/Desktop/Delete/TTTT_iOS2/iOSApp1/iOSApp1.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8030/targets/Xamarin.Shared.Sdk.targets(2260,3): error : error HE0004: Could not load the framework 'IDEDistribution' (path: /Applications/Xcode.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/IDEDistribution):  [/Users/testmac/Desktop/Delete/TTTT_iOS2/iOSApp1/iOSApp1.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8030/targets/Xamarin.Shared.Sdk.targets(2260,3): error : dlopen(/Applications/Xcode.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/IDEDistribution, 0x0001): Library not loaded: @rpath/AppThinning.framework/Versions/A/AppThinning [/Users/testmac/Desktop/Delete/TTTT_iOS2/iOSApp1/iOSApp1.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8030/targets/Xamarin.Shared.Sdk.targets(2260,3): error :   Referenced from: <33FF2F3B-A96F-37B4-BA4E-887BD882BF9D> /Applications/Xcode.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/IDEDistribution [/Users/testmac/Desktop/Delete/TTTT_iOS2/iOSApp1/iOSApp1.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8030/targets/Xamarin.Shared.Sdk.targets(2260,3): error :   Reason: tried: '/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8030/tools/lib/mlaunch/mlaunch.app/Contents/Frameworks/AppThinning.framework/Versions/A/AppThinning' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/Frameworks/AppThinning.framework/Versions/A/AppThinning' (no such file), '/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8030/tools/lib/mlaunch/mlaunch.app/Contents/Frameworks/AppThinning.fra [/Users/testmac/Desktop/Delete/TTTT_iOS2/iOSApp1/iOSApp1.csproj]
```

**Comment by AuriR** [comment]
The XCode 16 auto-update broke our ability to publish. Can we use the preview version of VS while we wait? It seems unreasonable - and I'd imagine some would say unacceptable - that you'd know there's a breaking change and advise "just wait until November."

**Comment by AuriR** [comment]
I did fix the sudden "Entitlements.plist" issue that occurred after realizing XCode had auto-updated. Simply added an Entitlements.plist file (with empty XML, not just empty) and build worked fine for debug. However, Publish ability is completely broken, regardless of which device I target, updated to iOS 18 or not. Microsoft's been very good about day-and-date support with Xamarin in the past - is that continuing with MAUI, please? :)

**Comment by AuriR** [comment]
And thanks Dave - I hope I'm not coming across as a ranter, friend :)

**Comment by AuriR** [comment]
Heads up - If you have Rider, you can target the previous XCode 15.4 and continue to build/publish apparently..

**Comment by AuriR** [comment]
I was able to successfully downgrade to XCode 15.4 and build again. I'm still on Sonoma, though. Agreed about staying away from new macOS builds, as they limit your downgradability.

**Comment by sindrevr** [comment]
Installing Xcode 15.4 workaround works... but still hot reload does not. Any workarounds to have hot reload up running again?

**Comment by AuriR** [comment]
> Installing Xcode 15.4 workaround works... but still hot reload does not. Any workarounds to have hot reload up running again?

On an iOS 18 device? Might need to stick with a 17.x device for now. Unless Preview supports it - but haven't tried.

**Comment by victorivan1692** [comment]
> > La instalación de Xcode 15.4 funciona, pero la recarga en caliente no. ¿Existe alguna solución alternativa para que la recarga en caliente vuelva a funcionar?
> 
> ¿En un dispositivo iOS 18? Es posible que deba quedarse con un dispositivo con la versión 17.x por ahora, a menos que Preview lo admita, pero no lo he probado.


I am getting the following error:
Error loading partial Info.plist template file 'obj\Release\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist': No se puede encontrar una parte de la ruta de acceso 'D:\Apps\FalconSAT\FalconSAT.DxSuppNostics\obj\Release\net8.0-ios\ios-arm64\resizetizer\sp\MauiInfo.plist'

**Comment by MarcoErlwein** [comment]
How do we solve the blank screen problem for users who updated their devices to IOS 18.0 version?

**Comment by AuriR** [comment]
> How do we solve the blank screen problem for users who updated their devices to IOS 18.0 version?

I imagine if it hasn't been reported, report it, with full repro steps. I haven't had blank screens fyi. But I'm using a MAUI/Blazor Hybrid app.

**Comment by rcarde** [comment]
@jfversluis   Not sure where this sits; however, the .NET for iOS team (xamarin-macios @dalexsoto) just pushed out Xcode 16 and iOS 18 support in dotnet workload set version 8.0.402.1.  This breaks our pipelines that pull in the latest workload with linker errors.

`##[warning]ILLINK(0,0): Warning MT0079: The recommended Xcode version for Microsoft.iOS 18.0.8303 is Xcode 16.0 or later. The current Xcode version (found in /Applications/Xcode_15.4.app/Contents/Developer) is 15.4.`

`Error MT4162: The type 'UIKit.UITextFormattingViewController' (used as a parameter in UIKit.UITextView/_UITextViewDelegate.DidEndFormatting) is not available in iOS 17.5 (it was introduced in iOS 18.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode).`

Probably need a warning somewhere about sticking with workload set version 8.0.402.

**Comment by dasunmax89** [comment]
Hi all,
I also mistakenly upgraded mac os to Sequoia and non of above methods worked for me. (MAUI)
then I switched to Jetbrains Rider IDE and installed XCode 15.4 in a separate folder and set the sdk location to there. yikes it works.
I still couldn't test with real device so far because my dev environment really f'ed up and wasted nearly one week to fix that
you will definitely need to set the Xcode command line tools to 15.4

for that simply invoke this command to open obsolete Xcode
/[path]/[to]/[XXXXCode 15.4]/Xcode.app/Contents/MacOS/Xcode
for me
/Users/dasunnayanajith/Documents/Xcode.app/Contents/MacOS/Xcode

**Comment by Cheesebaron** [comment]
@dasunmax89 tried updating your workloads and running with xcode 16? They were updated today.

**Comment by dasunmax89** [comment]
> @dasunmax89 tried updating your workloads and running with xcode 16? They were updated today.

@Cheesebaron wow. I need to try that. but my company officially purchased Jetbrains rider and I will go with that dude.
thanks for the reply.

**Comment by jfversluis** [comment]
Please see the update to the initial comment. Xcode 16 support for .NET 8 is out now!

**Comment by Cheesebaron** [comment]
Seems like Rider EAP 2024.3 doesn't support it yet. Devices not detected: https://youtrack.jetbrains.com/issue/RIDER-118000/Refreshing-devices-not-working-with-Xcode-16

**Comment by Cheesebaron** [comment]
So updated to .NET SDK 8.0.402 and latest iOS workload 18.0.8303.

```
brew upgrade dotnet-sdk
sudo dotnet workload install ios
```

Running and debugging in VSCode works well 🤘

![image](https://github.com/user-attachments/assets/ed89e4eb-2895-4681-a8df-6d8e4ee19c21)

**Comment by NatWobble** [comment]
@Cheesebaron

It seems to be running Ok on Rider 2024.2.5

**Comment by omghb** [comment]
Our iOS build is broken since yesterday:
```
ILLink : iOS error IL7000: An error occurred while executing the custom linker steps. Please review the build log for more information. [/___.csproj::TargetFramework=net8.0-ios]
/Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UITextView.g.cs(3343): error MT4162: The type 'UIKit.UITextFormattingViewController' (used as a parameter in UIKit.UITextView/_UITextViewDelegate.DidBeginFormatting) is not available in iOS 17.5 (it was introduced in iOS 18.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode). [/___.csproj::TargetFramework=net8.0-ios]
```

Our build servers install the workload with `dotnet workload install ios maui --source https://api.nuget.org/v3/index.json`. Yesterday a new `ios` workload was published which does not work anymore with `Xcode 15.4`.
```
ios                        18.0.8303/8.0.100      SDK 8.0.400
```

How can we install the previous workload?
```
ios                        17.5.8030/8.0.100      SDK 8.0.400
```

**Comment by Cheesebaron** [comment]
18.0.8303 will throw that error if you are not using Xcode 16.0

So if you want to stay on 15.4, pin 17.5.xxxx workload.

**Comment by omghb** [comment]
@Cheesebaron How do I pin the 17.5.xxxx workload?

**Comment by Cheesebaron** [comment]
I think something like this could work:

```
sudo dotnet workload install ios --version 8.0.401
```

See: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets

**Comment by Cheesebaron** [comment]
> @Cheesebaron
> 
> It seems to be running Ok on Rider 2024.2.5

Yeah seems like it is only the 2024.3 EAP 1 that is having issues finding them, latest stable 2024.2.5 seems ok. Neat!

**Comment by AuriR** [comment]
> Please see the update to the initial comment. Xcode 16 support for .NET 8 is out now!

Fantastic, thanks! Is that in Preview or a nuget update? I didn't see any VS updates. Great work, all!

**Comment by Cheesebaron** [comment]
> > Please see the update to the initial comment. Xcode 16 support for .NET 8 is out now!
> 
> Fantastic, thanks! Is that in Preview or a nuget update? I didn't see any VS updates. Great work, all!

It is all in the dotnet SDK. So update the SDK to 8.0.402 and update the dotnet workloads

**Comment by omghb** [comment]
> I think something like this could work:
> 
> ```
> sudo dotnet workload install ios --version 8.0.401
> ```
> 
> See: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets

👍 Thanks, your solution works fine.

I tried with a rollback-file first. This works too but I prefer your approach.

```
dotnet workload install ios maui --source https://api.nuget.org/v3/index.json --from-rollback-file https://github.com/dotnet/maui/releases/download/8.0.82/8.0.82.json
```

**Comment by nll** [comment]
Shouldn't people on .NET 8.0.40x be running  `dotnet workload install ios --version 8.0.402` (not `401`) to receive the most recent iOS workload that is a few hours old ?

![image](https://github.com/user-attachments/assets/bd4ddb25-35d3-4633-81a6-d6f284980bd8)
 
Workloads are a nightmare ...

**Comment by MichaelLHerman** [comment]
> I think something like this could work:
> 
> ```
> sudo dotnet workload install ios --version 8.0.401
> ```
> 
> See: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets

@Cheesebaron Can you provide a `global.json` that would do the same thing?  My build process is using `dotnet workload restore` and is still pulling in 18.0.8303

**Comment by MarcoErlwein** [comment]
I resolved this way:

Install Xcode 16
Install Simulators 18.0
Add the lines of code from the attached image, line 25 to 29

![IOS18](https://github.com/user-attachments/assets/4c6faaa3-26c0-4cf5-82f9-c2ea3dcf5183)

**Comment by pininfarino** [comment]
> Our iOS build is broken since yesterday:
> 
> ```
> ILLink : iOS error IL7000: An error occurred while executing the custom linker steps. Please review the build log for more information. [/___.csproj::TargetFramework=net8.0-ios]
> /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UITextView.g.cs(3343): error MT4162: The type 'UIKit.UITextFormattingViewController' (used as a parameter in UIKit.UITextView/_UITextViewDelegate.DidBeginFormatting) is not available in iOS 17.5 (it was introduced in iOS 18.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode). [/___.csproj::TargetFramework=net8.0-ios]
> ```
> 
> Our build servers install the workload with `dotnet workload install ios maui --source https://api.nuget.org/v3/index.json`. Yesterday a new `ios` workload was published which does not work anymore with `Xcode 15.4`.
> 
> ```
> ios                        18.0.8303/8.0.100      SDK 8.0.400
> ```
> 
> How can we install the previous workload?
> 
> ```
> ios                        17.5.8030/8.0.100      SDK 8.0.400
> ```

A have same problem into Azure DevOps
- yet I don't find way to fix 
fck Microsoft - https://www.youtube.com/watch?v=2zpCOYkdvTQ

**Comment by nll** [comment]
For people on .NET 8.0.400 band (probably check the `global.json` file)

- For Xcode 16    - `dotnet workload install ios --version 8.0.402.1`
- For Xcode 15.4 - `dotnet workload install ios --version 8.0.402.0`

We can see the _workload set_ versions [here](https://www.nuget.org/packages/Microsoft.NET.Workloads.8.0.400#versions-body-tab) and documentation [here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets) how it can be specified on `global.json` file.

**Comment by rcarde** [comment]
> I think something like this could work:
> 
> ```
> sudo dotnet workload install ios --version 8.0.401
> ```
> 
> See: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets

You can also pin 8.0.402. The point release 8.0.402.1 breaks Xcode 15.4 used in pipelines.

**Comment by zijianhuang** [comment]
If you have upgraded to xcode v16 and macos Sequoia 15, this is not the end of the world, before November when the magic may come.
At least in this instance, you don't need to download xCode to v15.4 or alike.

## Don't run to such situation again
Before upgrading xCode, make sure checking https://github.com/dotnet/maui/wiki/Release-Versions since Visual Studio could be a few weeks or a few months behind the latest xCode.

Remarks:
* I have great respects to Xamarin/MAUI teams, since I understand the difficulty of developing cross platforms dev tools, as I have been through qt and Kylix etc.
* I urge app developers to be patient, especially the .NET and MAUI teams might have suffered from recent massive layoff of staffs.

## What you can do before November
You can do local test with AdHoc profile though without debugging, and build with production profile, as long as you can pair with the mac, yes, VS 2022 v17.11.4  can pair with xcode v16 and macos Sequoia 15, even though in VS:
1. Emulators not appearing
2. iOS devices connected to Mac not appearing.
3. You can see only "Remote device, Local device, Simulators (xcode mismatch)

For testing, though without debugging, you can do these steps:
1. Build with the AdHoc profile locked with your iOS devices. Making debug build is for saving build time, while release build is OK too. And the IPA file will be generated on the mac side: (/Users/myUserName/Library/Caches/Xamarin/mtbs/builds/My.App.iOS/5415201399a22f416e1bab831c712aee75c7d2a4c970ced5391e2/bin/Debug or Release/net8.0-ios/ios-arm64/
2. On Mac, go to "xCode/Window/Devices and Simulator". And in the Devices tab, you see the connected devices, click one of them, Mac may try to pair with it and copy some dev needed files. You may get a warning asking you to put your iOS device to Developer Mode, and do it.
3. On Mac, locate the IPA file and drag & drop (or Plus) it to "Installed Apps", then Mac will upload the IPA to your device.
4. Then run the app on your iOS device.

Without debugging, it may not be good for new app development, or legacy apps with dirty codes, which need intensive debugging, often with simulators. Other than this, this workaround is just less ideal than the November magic.

**Comment by yalamandarao** [comment]
@ronanj2 thank you. We are also facing same issue for iOS and macOS application while submitting the app to AppStore. 

Any one know how to fix the issue ?

**Comment by mackayn** [comment]
> Please see the update to the initial comment. Xcode 16 support for .NET 8 is out now!

I know I've asked on Twitter but would appreciate any workarounds to allow us VS2022 users to install and use the XCode 16 support.

**Comment by MysterDru** [comment]
This is the `global.json` we are using across our 3 MAUI projects.

```json
{
  "sdk": {
    "version": "8.0.401",
    "workloadVersion": "8.0.401.0",
    "rollForward": "disable",
    "allowPrerelease": false
  }
}
```

We've pinned the dotnet sdk & workload set to 8.0.401 as we haven't done any testing against 8.0.402.

I did confirm that the same settings would work for 402 to pull in the correct iOS sdk version.

To pull in the 17.5 ios sdk
```json
{
  "sdk": {
    "version": "8.0.402",
    "workloadVersion": "8.0.402"
 }
```

To pull in the 18.0 ios sdk.
```json
{
  "sdk": {
    "version": "8.0.402",
    "workloadVersion": "8.0.402.2"
 }
```

**Comment by mackayn** [comment]
> This is the `global.json` we are using across our 3 MAUI projects.
> 
> ```json
> {
>   "sdk": {
>     "version": "8.0.401",
>     "workloadVersion": "8.0.401.0",
>     "rollForward": "disable",
>     "allowPrerelease": false
>   }
> }
> ```
> 
> We've pinned the dotnet sdk & workload set to 8.0.401 as we haven't done any testing against 8.0.402.
> 
> I did confirm that the same settings would work for 402 to pull in the correct iOS sdk version.
> 
> To pull in the 17.5 ios sdk
> 
> ```json
> {
>   "sdk": {
>     "version": "8.0.402",
>     "workloadVersion": "8.0.402"
>  }
> ```
> 
> To pull in the 18.0 ios sdk.
> 
> ```json
> {
>   "sdk": {
>     "version": "8.0.402",
>     "workloadVersion": "8.0.402.1"
>  }
> ```

Are you using VS2022 to a remote mac build host ?

**Comment by MysterDru** [comment]
> > This is the `global.json` we are using across our 3 MAUI projects.
> > ```json
> > {
> >   "sdk": {
> >     "version": "8.0.401",
> >     "workloadVersion": "8.0.401.0",
> >     "rollForward": "disable",
> >     "allowPrerelease": false
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We've pinned the dotnet sdk & workload set to 8.0.401 as we haven't done any testing against 8.0.402.
> > I did confirm that the same settings would work for 402 to pull in the correct iOS sdk version.
> > To pull in the 17.5 ios sdk
> > ```json
> > {
> >   "sdk": {
> >     "version": "8.0.402",
> >     "workloadVersion": "8.0.402"
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To pull in the 18.0 ios sdk.
> > ```json
> > {
> >   "sdk": {
> >     "version": "8.0.402",
> >     "workloadVersion": "8.0.402.1"
> >  }
> > ```
> 
> Are you using VS2022 to a remote mac build host ?

No, we use rider on a mac for local development and a macOS-14 agent in azure Devops for our pipelines.

This global.json configuration was not tested on a VS2022 windows environment as we have no developers on our team with that setup.

**Comment by jcmanke** [comment]
> For people on .NET 8.0.400 band (probably check the `global.json` file)
> 
> * For Xcode 16    - `dotnet workload install ios --version 8.0.402.1`
> * For Xcode 15.4 - `dotnet workload install ios --version 8.0.402.0`
> 
> We can see the _workload set_ versions [here](https://www.nuget.org/packages/Microsoft.NET.Workloads.8.0.400#versions-body-tab) and documentation [here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets) how it can be specified on `global.json` file.

Is there something I'm missing that clearly documents what the dependencies are of a specific workload version short of installing it and reading the output for what it pulls down?

**Comment by nll** [comment]
@jcmanke the sdk documentation refer to the package that contains the workload set information, we can open it and check the json inside that contains all the workloads versions (for instance using "Open in NuGet Package Explorer").

As far as I understand from other issue comments we may have a new command to display that information. 

I'm not sure if there is anything else.

I did compile a list of workload versions per workload set for 8.400 if that can be useful 

| Workload                                      | 8.400.0   | 8.401.0   | 8.401.1   | 8.402.0   | 8.402.1   |
|:----------------------------------------------|:----------|:----------|:----------|:----------|:----------|
| Microsoft.NET.Sdk.Aspire                      | 8.1.0     | 8.1.0     | 8.2.0     | 8.2.0     | 8.2.1     |
| Microsoft.NET.Workload.Emscripten.net6        | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     |
| Microsoft.NET.Workload.Mono.ToolChain.net6    | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     |
| Microsoft.NET.Workload.Mono.ToolChain.Current | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     |
| Microsoft.NET.Sdk.Maui                        | 8.0.71    | 8.0.72    | 8.0.72    | 8.0.82    | 8.0.82    |
| Microsoft.NET.Workload.Emscripten.net7        | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     |
| Microsoft.NET.Workload.Emscripten.Current     | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     |
| Microsoft.NET.Workload.Mono.ToolChain.net7    | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     | 8.0.8     |
| Microsoft.NET.Sdk.iOS                         | 17.2.8078 | 17.5.8020 | 17.5.8020 | 17.5.8030 | 18.0.8303 |
| Microsoft.NET.Sdk.MacCatalyst                 | 17.2.8078 | 17.5.8020 | 17.5.8020 | 17.5.8030 | 18.0.8303 |
| Microsoft.NET.Sdk.macOS                       | 14.2.8078 | 14.5.8020 | 14.5.8020 | 14.5.8030 | 15.0.8303 |
| Microsoft.NET.Sdk.tvOS                        | 17.2.8078 | 17.5.8020 | 17.5.8020 | 17.5.8030 | 18.0.8303 |
| Microsoft.NET.Sdk.Android                     | 34.0.113  | 34.0.113  | 34.0.113  | 34.0.138  | 34.0.138  |

**Comment by DarkWingDuck1020** [comment]
All,

Try to explain to your boss that, the tool he invested in, is basically not up to scratch.  I myself as an engineer and not someone who constantly has to play puzzles. Upgrading and moving forward is good but please do it properly.

**Comment by mackayn** [comment]
> _Description below is copied from the .NET for iOS repository, please check [that issue](https://github.com/xamarin/xamarin-macios/issues/20802) for the latest actual state._
> 
> ⚠️ Xcode 16 support is now released for .NET 8, please see release notes https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-8.0.1xx-xcode16.0-8303 for installation instructions. This version of the macios workloads will be also included in the next version of Visual Studio 17.11.5.
> 
> The current plan is to release Xcode 16 support with .NET 9 in November.
> 
> The current stable version of our workload _is not compatible with Xcode 16_. We recommend against upgrading until .NET 9 is released.
> 
> Warning
> 
> Xcode 15.4 does not support macOS 15 (Sequoia). This also means that we don't recommend upgrading your macOS development machines until .NET 9.
> 
> You can follow our progress here:
> 
> https://github.com/xamarin/xamarin-macios/wiki/xcode16.0-Bindings-Status

Any ideas when 17.11.5 might become available. Need to give some realistic timescales to management.

**Comment by Kalyxt** [comment]
You guys are insane, you have learn nothing over the years ? DON'T TOUCH something that works, especially if its Xamarin/MAUI tool chain. Why would you update to latest MacOS or even update VS ? I am creating restore point on windows PC before each Visual studio update, partially thanks that, downgrade is limited to professional version, but same applies to Mac. You can experiment but always have backup plan.

**Comment by mackayn** [comment]
> You guys are insane, you have learn nothing over the years ? DON'T TOUCH something that works, especially if its Xamarin/MAUI tool chain. Why would you update to latest MacOS or even update VS ? I am creating restore point on windows PC before each Visual studio update, partially thanks to, downgrade is limited to professional version, but same applies to Mac. You can experiment but always have backup plan.

I've been doing Xamarin dev since 2014 and know fine well how badly these upgrades can go but the announcement above suggested XCode 16 support was generally available for MAUI, it doesn't mention breaking the Azure pipelines (something they clearly didn't consider) and that pinning the workloads won't work in VS2022. It's poor messaging. Also assuming they could force companies onto .NET9 after the horrors of going from .NET7 to .NET8 is simply unrealistic (lets ignore .NET6). You don't jump straight into a new SDK and hope for the best, especially when it's Microsoft as your doing their beta testing essentially, getting a little fed up with doing that since 2014 (not insane)

**Comment by DarkWingDuck1020** [comment]
All, as much as I agree with that statement, I am currently having my car serviced. I do not have any problems with it afterwards. The tool, the car, does what it says on the tin. I pay for that service, the same has to go for the tools that we use and the service we pay for. The times of winging it with products like Maui should be long gone. MS wants us to go this route, they are pushing this. In the end we want just a product that works not playing catch up on every new release. I know it is not the space shuttle, even that went wrong, but some courtesy to your customers, MS customers, would be appreciated. From the carrouselview debacle to these "improvements" we are constantly busy with reading and puzzling just to have some basic things all of a sudden not working anymore. If MS wants visual studio and with that Maui like products to stay relevant they have to start with getting stuff to a stage that it works and have the "balls" to leave it alone for a while.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jfversluis** [comment]
I think we're getting a bit sidetracked here. The initial support is out now and I think this issue now describes most scenarios and how to get into a working state. As such, I think we can close this one! Thanks everyone!

**Comment by Kremed** [comment]
After updating to Xcode 16 and trying to build my .NET MAUI iOS project (targeting net8.0-ios), I encountered an error during the publishing process when attempting to build for Release or Debug on a simulator. The error occurred while running the strip tool, which resulted in the following error message:

`strip exited with code 139`

Steps taken:
1. Updated to the latest stable workload: Workload version: 8.0.402.1.
2. Re-synced both Windows and Mac machines to ensure they both had the same version.
3. Cleared Xamarin Shared cache files.
4. Confirmed that the issue persisted with the same error message after reattempting the build.

Here’s the exact output from the build log showing the error:
```
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\tools\msbuild\iOS\Xamarin.Shared.targets(2848,3): error : strip exited with code 139 [C:\Users\USER\OneDrive\Desktop\SwapPay\Swapay\Mobile\Mobile.csproj::TargetFramework=net8.0-ios]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\tools\msbuild\iOS\Xamarin.Shared.targets(2848,3): error :          [C:\Users\USER\OneDrive\Desktop\SwapPay\Swapay\Mobile\Mobile.csproj::TargetFramework=net8.0-ios]
```

Temporary Workaround:
I discovered a solution that allows the build process to continue successfully. By adding the following tag to the iOS Release property in the .csproj file, I was able to bypass the strip error:

```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhone' ">
  <_ExportSymbolsExplicitly>false</_ExportSymbolsExplicitly>
</PropertyGroup>
```

Environment Details:
Workload version: 8.0.402.1

```
Installed Workload Id      Installation Source
----------------------------------------------------------
android                    SDK 8.0.400, VS 17.11.35312.102
aspire                     SDK 8.0.400, VS 17.11.35312.102
ios                        SDK 8.0.400, VS 17.11.35312.102
maccatalyst                SDK 8.0.400, VS 17.11.35312.102
maui-windows               SDK 8.0.400, VS 17.11.35312.102
wasm-tools                 SDK 8.0.400, VS 17.11.35312.102
```

**Comment by angularsen** [comment]
Several issues related to strip exit code 139.

Good summary here:
https://github.com/getsentry/sentry-dotnet/issues/3620#issuecomment-2406022823 

And some others, for cross reference links in github:
https://github.com/xamarin/xamarin-macios/pull/18408
https://github.com/xamarin/xamarin-macios/issues/19157
https://github.com/apple-oss-distributions/cctools/pull/2
