### ISSUE TITLE
Cannot build .NET Maui app from vs code on mac following macOS 15.0 update

### ISSUE THREAD

**Issue by els-red** [dotnet/maui#24816]
### Description

Since updating my macOS to vs code 15.0, I am now unable to build my .NET Maui application and get an error "Could not find the task `maui: Build`". 

![Screenshot 2024-09-18 at 11 50 26](https://github.com/user-attachments/assets/0d0a189e-a3f1-4cca-a8a5-3a36ca18f252)

This is my launch.json file:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug .NET MAUI",
            "type": "maui",
            "request": "launch",
            "configuration": "Debug",
            "preLaunchTask": "maui: build"
        },
        {
            "name": "Release .NET MAUI",
            "type": "maui",
            "request": "launch",
            "configuration": "Release",
            "preLaunchTask": "maui: Build"
        },
        {
            "name": "AppStore .NET MAUI",
            "type": "maui",
            "request": "launch",
            "configuration": "AppStore",
            "preLaunchTask": "maui: Build"
        }
    ]
}
```

This issue isn't affected by the debug target.

### Steps to Reproduce

1. Create a new .NET Maui app and select C# as the debugger
2. Add a new default configuration to launch.json
3. Click run and debug

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.21 SR4.1

### Affected platforms

macOS

### Affected platform versions

macOS 15.0

**Comment by dartasen** [comment]
See https://github.com/xamarin/xamarin-macios/issues/2080

**Comment by jfversluis** [comment]
As indeed pointed out Xcode 16 is not supported yet, keep your eye on the linked issue!

**Comment by els-red** [comment]
> As indeed pointed out Xcode 16 is not supported yet, keep your eye on the linked issue!

Would Xcode 16 not being supported be the cause of this particular issue though? It's not that VS Code cannot build my project, it's that VS Code can't even find the build task. This issue happens if I'm targeting an Android device as well.
