### ISSUE TITLE
I cannot select API Level 35 for Android.

### ISSUE THREAD

**Issue by voroninp** [dotnet/maui#24813]
### Description

I've installed .NET 9 RC1 and VS 17.12.0 Preview 2.
When I create MAUI application from the template, I see these settings for Android:
![image](https://github.com/user-attachments/assets/ea5500e8-c755-4ef0-ba95-8dccc50f541d)

![image](https://github.com/user-attachments/assets/35a12568-1223-4e36-a293-32c9e43a0f9a)

If I explicitly set 34 level, I get this error:
> 34.0 is not a valid TargetPlatformVersion for Android. Valid versions include:
35.0

I've installed 35 in SDK Manager:
![image](https://github.com/user-attachments/assets/f4a01b6f-beea-49fc-bcee-aa7b26568a81)

![image](https://github.com/user-attachments/assets/ba7f4005-26b4-47aa-9eec-a3b6df041e37)

### Steps to Reproduce

Just create an application from template.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 15

### Did you find any workaround?

No

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12.0 Preview 2.0(9.0.0-rc.1.24453.9 & 8.0.82 & 8.0.3). Can repro this issue on .net9 and .net8. Only can set API34.

**Comment by jfversluis** [comment]
So you mean it works targeting API 35, but there just isn't a setting in Visual Studio?

**Comment by voroninp** [comment]
No, I could not deploy to emulator when there was empty selection, and could not build when it was API 34.

**Comment by jfversluis** [comment]
What is the build error for the empty selection?

**Comment by voroninp** [comment]
For some reason it was:
![image](https://github.com/user-attachments/assets/9645f4cf-2d06-466e-9841-2b72a3c72a29)

And I was getting:
> The project Android35FailingBuild needs to be deployed before it can be started. Verify the project is selected to be deployed in the Solution Configuration Manager.

**Comment by jfversluis** [comment]
Small update: this is something in our tooling which is tracked through a different system. Unfortunately, I don't have a link with status updates from their side so I'll leave this open until we get it fixed and release to notify you!

**Comment by voroninp** [comment]
@stmoor , hm... my VS installer does not show me preview 3.0 yet. I have 2.1 installed now.

**Comment by jfversluis** [comment]
@voroninp it seems that this is the version we have in our internal preview right now so hopefully that will be released soon. It seems that that has the fix for this. Closing this here now in anticipation of that. If preview 3 does not fix that for you, please report it through Visual Studio. Under the Help menu go to Provide Feedback and Report a Problem. That will land it with the right team so it can be looked at sooner and more efficient.

Thanks!

**Comment by ra-bedo11** [comment]
I can't find it 
preview3 ??? in visual studio 2022

**Comment by voroninp** [comment]
@ra-bedo11 , not released into public yet.

The message above yours:
> it seems that this is the version we have in our internal preview right now
