### ISSUE TITLE
[BUG] Disabled Forced Dark Mode Xiaomi phones

### ISSUE THREAD

**Issue by jpmm94** [dotnet/maui#24837]
### Description

Hi everyone,
I'm working in an app which has only light mode, and with Xiaomi phones forces dark mode as a result we had this splash
![image](https://github.com/user-attachments/assets/8468756c-e5e9-4cc4-bf24-1a05d4c67faf)
I'd like to have all background white, with another Android brands it works perfectly.
I tried as a workaround the next steps:
android:forceDarkAllowed="false" 

 if (Build.VERSION.SdkInt >= BuildVersionCodes.Q) 
            Window.DecorView.ForceDarkAllowed = false;
It does not work
I need help THX

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.90 SR9

### Affected platforms

Android

**Comment by jfversluis** [comment]
This will be a harder one to figure out because I don't have a Xiaomi device to test. From what I could find, people are able to disable this behavior through the entry you mentioned in the `styles.xml` file.

Can you share a little bit more about the fixes you have tried? Are you sure that the `styles.xml` file was recognized by your project? Did you change any other values or colors to verify that the values in there were applied but just the `forceDarkAllowed` is not working?

**Comment by AndrewYehozha** [comment]
Hi there. I've fixed it. Here is a code:

=> YOUR_PROJECT/Platforms/Android/MainApplication.cs

`[Application]
public class MainApplication : MauiApplication
{
    public MainApplication(IntPtr handle, JniHandleOwnership ownership)
        : base(handle, ownership)
    {
        DisableDarkMode();
    }

    protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();

    private void DisableDarkMode()
    {
        if (OperatingSystem.IsAndroidVersionAtLeast(31))
        {
            var uiModeManager = (UiModeManager)GetSystemService(UiModeService);
            uiModeManager.SetApplicationNightMode((int)UiNightMode.No);
            return;
        }

        AppCompatDelegate.DefaultNightMode = AppCompatDelegate.ModeNightNo;
    }
}`

=> Add this to the your theme. YOUR_PROJECT/Platforms/Android/Resources/values/styles.xml

`<item name="android:forceDarkAllowed">false</item>`

=> MAUI App file:

`public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		Application.Current.UserAppTheme = AppTheme.Light;
	}
}`

**Comment by jfversluis** [comment]
Going to assume that is enough information to force this for Xiaomi devices. If there is anything we can still do here, let us know! Thanks!
