### ISSUE TITLE
Visual State manager change in behavior in 8.0.90 breaks "Normal"

### ISSUE THREAD

**Issue by gabsamples6** [dotnet/maui#24849]
### Description

when using visual state manager to dictate if a button is enabled or disabled the "normal" state no longer works as used to.

Notice here button is enabled when should be disabled – used to work in 8.0.82  

  
![NoLongerWorkingVSM](https://github.com/user-attachments/assets/29189794-b354-43bf-846e-b285f170dbef)

Using this visual state is working -  
![WorkingVSM](https://github.com/user-attachments/assets/626220c0-19ef-427f-bf99-e77c56b39a29)

  
What I am saying is that the top pic style  used to work using Visual state manager, and doesnt.

thanks

### Steps to Reproduce

See repo attached, 

1. unzip
2. run the project
3. see button enabled when shouldnt 
4. uncomment code in styles and see working.

behaviour has changed on how it used to work.

### Link to public reproduction project repository

https://github.com/gabsamples6/BrokenVisualState.git

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

iOS, Android

### Affected platform versions

VS 2022 any version

### Did you find any workaround?

use visual state manager  like below -notice "Normal is together  but that has in impact on all our pages.

 ```
<VisualStateGroupList>
    <VisualStateGroup x:Name="CommonStates">
        <VisualState x:Name="Normal" />
        <VisualState x:Name="Disabled">
            <VisualState.Setters>
                <Setter Property="TextColor" Value="{DynamicResource PrimaryButtonDisabledTextColor}" />
                <Setter Property="Background" Value="{DynamicResource PrimaryButtonDisabledBackgroundColor}" />
            </VisualState.Setters>
        </VisualState>
        <VisualState x:Name="PointerOver" />
    </VisualStateGroup>
</VisualStateGroupList>
```

**Comment by PureWeen** [comment]
It looks like it's an issue with the initial state not being set to the right color

- If I use 8.0.90
- add text to both inputs to enable the button
- remove the text
- the button now looks disabled

Whereas in 8.0.82 it's correctly disabled on load

I validated this on android/ios and it's broken the same way on both.

**Comment by hwsmo** [comment]
I can confirm the problem, we can also reproduce it in our app. Annoying and (once again) a showstopper. PLEASE fix it very quickly and release an update!

**Comment by StephaneDelcroix** [comment]
I wrote a unit test based on your report that passes on 8.0.90 and main. Could you have a look and see if there's something missing ?

**Comment by StephaneDelcroix** [comment]
ok, the diff between the test and the app is the place where the implicit style is declared. if the style is declared in the page, everything works. updating the test...
