### ISSUE TITLE
MAUI .NET 8.0 v 8.0.90 Android WebView with SharePoint page - "We couldn't sign you in. Please try again." followed by "Unknown error." in SharePoint

### ISSUE THREAD

**Issue by mgschwendner** [dotnet/maui#24840]
### Description

Was working fine for several months, and now SharePoint will not sign in from WebView in a Android app built using MAUI .NET 8.0 for users who have previously authenticated. Issues started happening this week. I get the error: "We couldn't sign you in. Please try again." followed by "Unknown error."

Tried with no effect:
(1) Cleared the app cache, deleted data on both the custom app and System WebView - no effect.
(2) Reinstalling the custom app - same sequence of issues.
(3) Other MAUI apps - same issue.
(4) Reinstalling the O365 apps (Outlook, Teams, M365) - no effect.
(5) Opened the app in the Chrome browser - so far, no issues.

Issues also explained here:

https://learn.microsoft.com/en-us/answers/questions/2057452/maui-net-8-0-android-webview-with-sharepoint-page
https://issues.chromium.org/issues/368222743

### Steps to Reproduce

1. Create a ContentView with a WebView Control and a Sharpoint page as Source "https://xxx.sharepoint.com"
2. Build for Android
3. Start App
4. Sharepoint Azure Login-Screen shows
5. Enter credentials
6. Accept MFA if neccessary
7. You are redirected to Account Choose page of Azure with error ""We couldn't sign you in. Please try again."

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android up from Version 11

**Comment by jfversluis** [comment]
According to the linked web pages this is something that happens in the Android WebView, not something in .NET MAUI unfortunately. The good news is it seems to be fixed already, but the bad news is that that is still in beta and you will have to wait for that to be released and then your users have to update it.

Unfortunately I don't think there is much we can do about it at our end, so closing this for now.
