### ISSUE TITLE
[Bug] [iOS] Contents in RefreshView don't expand to full width and height, set to -1.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2485]
### Description

When using a RefreshView on iOS, whatever the contents are within the RefreshView are not expanded to match the width and height. Instead, they are -1.

![image](https://user-images.githubusercontent.com/898335/133330768-1e77bcc5-61f0-4ef3-af18-aac44f78e330.png)

In this example, if I move the inner CollectionView outside of the RefreshView, it will render correctly.

### Steps to Reproduce

1. Create a RefreshView
2. Add inner content to it that that should render with some height.

**Comment by filipnavara** [comment]
Hit this when I tried to port our application.

**Comment by shimingsg** [comment]
verified not repro with VS 17.2.0 Preview 3.0 [32321.361.main] on iOS 15.2 Emulator, here is the demo:
[MauiApp2485.zip](https://github.com/dotnet/maui/files/8320698/MauiApp2485.zip)


is this your expected result?
![image](https://user-images.githubusercontent.com/20982341/159399616-13a668e2-3416-4e43-8837-014c924f77aa.png)
