### ISSUE TITLE
Android  ImageButton  Aspect="AspectFit" not display correctly

### ISSUE THREAD

**Issue by HuaFangYun** [dotnet/maui#24856]
### Description

![image](https://github.com/user-attachments/assets/c54b4b7b-27d4-4d64-9f4c-a354d921a629)
```
        <VerticalStackLayout>
            <Frame Margin="10,70,10,10" HeightRequest="300">
            </Frame>
            <ImageButton Source="avatar.png"  CornerRadius="10" BorderColor="{StaticResource White}" BorderWidth="3" Aspect="AspectFit"  BackgroundColor="{StaticResource PrimaryDark}" WidthRequest="80" HeightRequest="80" HorizontalOptions="StartAndExpand" Margin="30,-335,20,0"/>

        </VerticalStackLayout>
```
On Windows correctly:
![image](https://github.com/user-attachments/assets/52457e22-db83-47ad-a2b8-e9ccc36d639c)

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by Zhanglirong-Winnie** [comment]
@HuaFangYun 
Could you provide me with your pictures or sample projects separately? It will be convenient for me to repro your issue. I look forward to your reply!

**Comment by HuaFangYun** [comment]
[MauiApp4.zip](https://github.com/user-attachments/files/17114805/MauiApp4.zip)
@Zhanglirong-Winnie

**Comment by HuaFangYun** [comment]
![image](https://github.com/user-attachments/assets/859e5e26-2204-44bc-8d4d-778285ef5579)
Maybe this picture is really special

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12.0 Preview 2.0(8.0.90 & 8.0.82 & 8.0.60 & 8.0.40). Can repro this issue on Android platform. This issue does not repro in 8.0.40.
