### ISSUE TITLE
Asp.net core

### ISSUE THREAD

**Issue by Samiir1234** [dotnet/maui#24853]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Hey @Samiir1234 thank you for your interest in .NET MAUI! Sorry to see you hit a snag here. From the description its not really clear what you are running into and thus how we can help you get you started on your .NET MAUI journey.

Would you be able to provide a bit more info? Thanks!
