### ISSUE TITLE
Role-based authorization not working correctly when using Blazor WebView in MAUI App

### ISSUE THREAD

**Issue by efonsecab** [dotnet/maui#24874]
### Description

I have a MAUI Blazor Hybrid App which uses Role-Base authorization.
The authorization works, and roles are correctly read by the CustomAuthenticationStateProvider.
Problem is the AuthorizeRouteView is never refreshing as expected, items requiring authorization are never shown.
I tried a force reload approach, however, there seems to be a bug related to reload:
https://github.com/microsoft/fluentui-blazor/issues/1036#issuecomment-2309420135

https://github.com/dotnet/aspnetcore/issues/52119

Here is part of my code:
https://github.com/pticostaricags/FairPlayCombined/blob/development/src/FairPlayCombinedSln/FairPlayTube.MAUI/MauiProgram.cs

https://github.com/pticostaricags/FairPlayCombined/blob/development/src/FairPlayCombinedSln/FairPlayTube.MAUI/Components/Pages/Login.razor

https://github.com/pticostaricags/FairPlayCombined/blob/development/src/FairPlayCombinedSln/FairPlayTube.MAUI/Components/Layout/MainLayout.razor

Is there any solution or workaround for this behavior so I can make the authorization flow work as expected.

### Steps to Reproduce

1. Create a MAUI Blazor Hybrid App
2. Create an authorization API
3. Perform role-based authorization from the Blazor pages inside the MAUI App

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

No workaround found yet.

**Comment by halter73** [comment]
> Problem is the AuthorizeRouteView is never refreshing as expected

I noticed that your `CustomAuthenticationStateProvider` doesn't implement `AuthenticationStateChanged`. How are you expecting `AuthorizeRouteView` to "refresh"? If the initial `AuthenticationState` needs to be refreshed, don't you need to signal the change?

> Yes, this used to work in .NET MAUI

Did this work in a MAUI Blazor Hybrid App before? If so, can you please provide a minimal repro pinpointing the behavior that changed between versions and instructions on how to build and run the app in a way that demonstrates the regression between .NET 8 and .NET 9?

https://github.com/pticostaricags/FairPlayCombined/tree/development/src/FairPlayCombinedSln/FairPlayTube.MAUI isn't exactly minimal.

**Comment by efonsecab** [comment]
> > Problem is the AuthorizeRouteView is never refreshing as expected
> 
> I noticed that your `CustomAuthenticationStateProvider` doesn't implement `AuthenticationStateChanged`. How are you expecting `AuthorizeRouteView` to "refresh"? If the initial `AuthenticationState` needs to be refreshed, don't you need to signal the change?
> 
> > Yes, this used to work in .NET MAUI
> 
> Did this work in a MAUI Blazor Hybrid App before? If so, can you please provide a minimal repro pinpointing the behavior that changed between versions and instructions on how to build and run the app in a way that demonstrates the regression between .NET 8 and .NET 9?
> 
> https://github.com/pticostaricags/FairPlayCombined/tree/development/src/FairPlayCombinedSln/FairPlayTube.MAUI isn't exactly minimal.

It used to work in another application before, with the same approach, with no need of using the event:
![image](https://github.com/user-attachments/assets/bc32c0f0-ce7c-4767-b585-5da6c35a9bd6)

**Comment by halter73** [comment]
Can you provide aingle-project repro that clearly demonstrates what breaks after updating from .NET 8 to .NET 9 that's as minimal as you can make it?  It should be published to its own repository on GitHub with a commit pointing to the working code on .NET 8 just before the upgrade and another commit after the upgrade to .NET 9 where it breaks.

The custom `AuthenticationStateProvider` shouldn't involve any secrets, clients, or anything like that. You can construct hard-coded ClaimsPrincipals for the purpose of the repro since the details about how a custom `AuthenticationStateProvider` creates its `AuthenticationState` is irrelevant to the framework.
