### ISSUE TITLE
AppThemeBinding does not work on ToolbarItems

### ISSUE THREAD

**Issue by Moes81** [dotnet/maui#24878]
### Description

Hi all,

I didn't find a report that fitted my description, that's why I created a new one. Please feel free to close it as duplicate if I missed the existing report.

In `Styles.xaml` we can set a style for `TargetType="Shell"` and set an `AppThemeBinding` for  `Shell.TitleColor`. As far as I understand this color is used for the page title as well as for the `ToolbarItems` and I expect that the color of the ToolbarItems is by default the same as for the Title. If I now change the theme from light to dark, or dark to light, depending on with which theme you started the app, I would expect that the `ToolbarItem`s change their color according to the theme. Unfortunately, the color remains the same.

<img width="359" alt="Screenshot 2024-09-23 at 17 19 29" src="https://github.com/user-attachments/assets/00389749-a74e-41e6-9524-667804d97af1">
<img width="361" alt="Screenshot 2024-09-23 at 17 19 40" src="https://github.com/user-attachments/assets/3cbf304b-680b-4d0c-b926-b6a03e5262be">

I was able to reproduce the behaviour on:
- Android 8
- Android 13
- On iOS 17.6.1 the ToolbarItems don't show up at all.

### Steps to Reproduce

1. Create a new MAUI solution
2. update `Microsoft.Maui.Controls` and `.Compatibility` to 8.0.90
3. Add one or more `ToolbarItem`s to the `MainPage.xaml` or to `AppShell.xaml`
4. Run the app
5. Switch from light to dark theme

Expected:
The ToolbarItem color changes according to the `AppThemeBinding` in style `Shell.TitleColor` and thus have the same color as the title.

Actual:
The ToolbarItem color does not change remains black.

Alternative:
Check out and run my sample project (see below).

### Link to public reproduction project repository

https://github.com/Moes81/maui_toolbaritems_themecolor

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8 and greater, iOS 17.6.1

### Did you find any workaround?

No workaround found so far.

**Comment by SmartmanApps** [comment]
Not sure if https://github.com/dotnet/maui/issues/6748 is related, but there's been issues with ToolbarItem colours for a long time! (wish this would get fixed)

**Comment by codewerfer** [comment]
Looks like in 9.0.0 it is back again.
