### ISSUE TITLE
MAUI template missing in visual studio 2022 17.12

### ISSUE THREAD

**Issue by Kesu8888** [dotnet/maui#24888]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows 11
Problem description: I have just installed visual studio 2022 Preview 17.12. During the pre-install, I selected the '.NET multi-platform App UI development' and nothing else as the workload. After everything installed, I open the visual and try to create a new project with template .NET MAUI as shown in "https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create". Also, I check the project type and I did not see the MAUI option as shown in the provided picture. I want to know what happenes and how to fix it so I can get a .NET MAUI template.
<img width="784" alt="Screenshot 2024-09-24 155720" src="https://github.com/user-attachments/assets/1f7167e9-37e8-4555-8321-ba0156be1354">

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Hey there @Kesu8888 thank you for your interest in .NET MAUI, sorry this happened to you!

Can you confirm that you indeed installed the .NET MAUI workload? If you run the Visual Studio Installer and press Modify, see screenshot below

![image](https://github.com/user-attachments/assets/5a445bb6-f96b-4761-8dc0-4b42514f963d)

Does that show the .NET MAUI workload as checked, as seen below?

![image](https://github.com/user-attachments/assets/71a3228c-d75a-45c0-8683-f71e620be4ac)

Is this a fresh installation? Did you have Visual Studio on this machine before? Could you maybe share a screenshot of that overview page like I did?

To still install them and get started right now you can open a terminal window and run `dotnet new install Microsoft.Maui.Templates.net8` assuming you want to use .NET 8. End it with net9 is you want to use .NET 9. That should also make it show up in Visual Studio.
