### ISSUE TITLE
[regression/8.0.99-ci.net8.24472.1] Invalidate Shadow Issue: VisualElement.Shadow property change no longer invalidates platform shadow

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#24882]
### Description

Changes to a control's "shadow property" or changes to the shadow's properties directly no longer invalidate the platforms shadow.

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.70 SR7

### Affected platforms

Android

### Affected platform versions

Android - All

**Comment by Stedy59** [comment]
Working in build 8.0.70-ci.net8.24321.1

https://github.com/user-attachments/assets/e05bb9cf-b04e-4dd9-88aa-661af7a95269

No shadow invalidate in build 8.0.99-ci.net8.24472.1

**NOTE** - my custom handler for the dropdown receives the bound property change and modifies the AppCompatTextViews Shadow.

The only way to force the invalidate was to change the font on the views controls.

https://github.com/user-attachments/assets/9962990c-d3f6-40b0-aa58-94ee85308cb3

**Comment by albyrock87** [comment]
I've tested this (on iOS) with b2c1d25f7a71197666c2053c1e40dbdea6049cc7 and it works fine:

```
	private void ChangeShadowClicked(object sender, EventArgs e)
	{
		var button = (View)TheButton.Parent;
		button.Shadow.Radius += 8;
	}
```

```
<Border
        HorizontalOptions="Center"
        BackgroundColor="LightBlue"
        Shadow="{Shadow Brush=Black, Offset='0,2', Radius=24, Opacity=0.2}"
        StrokeShape="{RoundRectangle CornerRadius=20}">
        <Button x:Name="TheButton" BackgroundColor="LightGreen" WidthRequest="200" HeightRequest="400" />
</Border>
```

**Comment by Stedy59** [comment]
> I've tested this (on iOS) with [b2c1d25](https://github.com/dotnet/maui/commit/b2c1d25f7a71197666c2053c1e40dbdea6049cc7) and also [e0b3526](https://github.com/dotnet/maui/commit/e0b3526697a8ccd68a37ca1cc8e8e0a5d60d847d) => it works fine:
> 
> ```
> 	private void ChangeShadowClicked(object sender, EventArgs e)
> 	{
> 		var button = (View)TheButton.Parent;
> 		button.Shadow.Radius += 8;
> 	}
> ```
> 
> ```
> <Border
>         HorizontalOptions="Center"
>         BackgroundColor="LightBlue"
>         Shadow="{Shadow Brush=Black, Offset='0,2', Radius=24, Opacity=0.2}"
>         StrokeShape="{RoundRectangle CornerRadius=20}">
>         <Button x:Name="TheButton" BackgroundColor="LightGreen" WidthRequest="200" HeightRequest="400" />
> </Border>
> ```

Issue is with Android... Not IOS. Thanks.

**Comment by albyrock87** [comment]
@Stedy59 reading `Affected platform versions / Android - All` confused me, sorry :)

I've opened a PR to fix the issue :)

**Comment by albyrock87** [comment]
For reference this is very likely what broke it:
https://github.com/dotnet/maui/pull/24222

**Comment by albyrock87** [comment]
![image](https://github.com/user-attachments/assets/db82f683-6790-4b95-9f5d-e04b8a020394)
Shape changes are broken too.

**Comment by albyrock87** [comment]
@rmarinho I suggest you to revert #24222 which broke:
- shadow changes
- clip changes

@jonathanpeppers `setHasShadow` and `setHasClip` are misleading names.. an invalidation is always expected there in order to update drawing upon changes.
I think we we could call `invalidate` instead of `postInvalidate` there considering MAUI will call those methods only from the main thread.

**Comment by jonathanpeppers** [comment]
@albyrock87 can you send a PR that just calls `invalidate()` instead? The slowdown was how `postInvalidate()` was queuing up so many callbacks. The sample was queuing up 100s of those.

**Comment by albyrock87** [comment]
@jonathanpeppers yes, I can create a simple PR just with that code.
Someone from the team will have to regenerate the .aar after it's merged though (for security reasons).

**Comment by albyrock87** [comment]
@jonathanpeppers https://github.com/dotnet/maui/pull/24990
