### ISSUE TITLE
Rollback JSON file links are not accessible (Azure Pipeline is failing)

### ISSUE THREAD

**Issue by Kamal-Joshi111** [dotnet/maui#24892]
### Description

Today, the following rollback json links are not accessible any more:
https://maui.blob.core.windows.net/metadata/rollbacks/7.0.92.json
https://maui.blob.core.windows.net/metadata/rollbacks/7.0.101.json
https://maui.blob.core.windows.net/metadata/rollbacks/8.0.7.json

Probably, It may failing almost all links from today.

Facing below error: 
Workload installation failed: One or more errors occurred. (Response status code does not indicate success: 409 (Public access is not permitted on this storage account.).)

I am running below command:
dotnet workload install maui-ios --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/7.0.92.json -- source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json

Suddenly today, Run above command, My Azure pipeline is faling. Even trying to open link in the browser https://maui.blob.core.windows.net/metadata/rollbacks/7.0.92.json 
getting the error:
PublicAccessNotPermittedPublic access is not permitted on this storage account. RequestId:818ea050-201e-0061-105e-0ec3bd000000 Time:2024-09-24T08:51:35.9916411Z

### Steps to Reproduce

1. open link in the browser https://maui.blob.core.windows.net/metadata/rollbacks/7.0.92.json 
2. Getting the error:
PublicAccessNotPermittedPublic access is not permitted on this storage account. RequestId:818ea050-201e-0061-105e-0ec3bd000000 Time:2024-09-24T08:51:35.9916411Z

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS, Android

### Did you find any workaround?

No

### Relevant log output

```shell
Workload installation failed: One or more errors occurred. (Response status code does not indicate success: 409 (Public access is not permitted on this storage account.).)
```

**Comment by Kamal-Joshi111** [comment]
The following links are not working as what expected in https://github.com/dotnet/maui/issues/12772, similarity score: 0.83
https://maui.blob.core.windows.net/metadata/rollbacks/7.0.92.json
https://maui.blob.core.windows.net/metadata/rollbacks/7.0.101.json
https://maui.blob.core.windows.net/metadata/rollbacks/8.0.7.json

**Comment by zachdean** [comment]
the rollback files have moved github per @rmarinho https://github.com/dotnet/maui/issues/12772#issuecomment-2371091925

**Comment by watsonlu** [comment]
We need a list of the existing json files, for example I need 8.0.62

**Comment by rmarinho** [comment]
Going forward we are pointing people to use workload sets to pin your versions https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets#pin-the-install-command

In the meanwhile you can use these public links I just updated on the releases 

https://github.com/dotnet/maui/releases/download/8.0.61/8.0.61.json
https://github.com/dotnet/maui/releases/download/8.0.7/8.0.7.json
https://github.com/dotnet/maui/releases/download/8.0.6/8.0.6.json
https://github.com/dotnet/maui/releases/download/8.0.3/8.0.3.json
https://github.com/dotnet/maui/releases/download/7.0.101/7.0.101.json
https://github.com/dotnet/maui/releases/download/7.0.96/7.0.96.json
https://github.com/dotnet/maui/releases/download/7.0.92/7.0.92.json

**Comment by rmarinho** [comment]
Going forward we are pointing people to use workload sets to pin your versions https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets#pin-the-install-command

In the meanwhile you can use these public links I just updated on the releases

https://github.com/dotnet/maui/releases/download/8.0.61/8.0.61.json
https://github.com/dotnet/maui/releases/download/8.0.7/8.0.7.json
https://github.com/dotnet/maui/releases/download/8.0.6/8.0.6.json
https://github.com/dotnet/maui/releases/download/8.0.3/8.0.3.json
https://github.com/dotnet/maui/releases/download/7.0.101/7.0.101.json
https://github.com/dotnet/maui/releases/download/7.0.96/7.0.96.json
https://github.com/dotnet/maui/releases/download/7.0.92/7.0.92.json

**Comment by Captnwalker1** [comment]
`dotnet workload install maui --version 8.0.3` does not work

**Workload installation failed: Workload version 8.0.3 not found.**

Will this not be backwards compatible with previous rollbacks then?

**Comment by rmarinho** [comment]
> `dotnet workload install maui --version 8.0.3` does not work
> 
> **Workload installation failed: Workload version 8.0.3 not found.**
> 
> Will this not be backwards compatible with previous rollbacks then?

That s right is not backward compatible, you will also need a dotnet sdk net8 4XX . 
For older versions please use the files from the releases on GitHub

**Comment by ESO-ST** [comment]
@rmarinho so if we were using `dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/8.0.40.json` how would we do so now?

there's no https://github.com/dotnet/maui/releases/download/8.0.40/8.0.40.json

**Comment by jameslavery** [comment]
> @rmarinho so if we were using `dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/8.0.40.json` how would we do so now?
> 
> there's no https://github.com/dotnet/maui/releases/download/8.0.40/8.0.40.json

Similarly we need 8.0.21, which isn't available.

**Comment by ESO-ST** [comment]
> > @rmarinho so if we were using `dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/8.0.40.json` how would we do so now?
> > there's no https://github.com/dotnet/maui/releases/download/8.0.40/8.0.40.json
> 
> Similarly we need 8.0.21, which isn't available.

we ended up using https://github.com/dotnet/maui/releases/download/8.0.61/8.0.61.json which worked for our purposes, I'm not sure if we can simply make our own .json file and set the versions we want in there, that's all there .json files really contain anyhow, packages with specific versions. You might want to give that a shot.

**Comment by rmarinho** [comment]
Sorry, maybe I miss upload that one? But yeah you can create and use your own .json file .
