### ISSUE TITLE
Carousel view Dynamic Height doesn't work.

### ISSUE THREAD

**Issue by sunilsolanki-alight** [dotnet/maui#24896]
### Description

Carousel view Dynamic Height doesn't work.

### Steps to Reproduce

Carousel view Dynamic Height doesn't work.

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

iOS

### Affected platform versions

17.5.1

### Did you find any workaround?

NO

### Relevant log output

```shell
Carousel view Dynamic Height doesn't work.
```

**Comment by jfversluis** [comment]
Duplicate of #24077
