### ISSUE TITLE
Rollback JSON file links are not accessible (again)

### ISSUE THREAD

**Issue by mikebaumannch** [dotnet/maui#24890]
### Description

As part of our CI build process, we publish rollback .json files for the versions of the workloads we built a given commit for and the version of the maui workloads we produced.

These rollback files can be used from the dotnet workload install maui --from-rollback-json https://aka.ms/dotnet/maui/main.json command.

The azure blob storage container has recently stopped allowing public access to those files and so these commands will currently fail.

### Steps to Reproduce

dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/8.0.61.json

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

**Comment by mikebaumannch** [comment]
This issue is a regression of https://github.com/dotnet/maui/issues/12772

**Comment by rmarinho** [comment]
We will not provide anymore the links for rollback , going forward one should use workload set versions that should be already working with net8 4xxx sdk and net9.

I uploaded the rollbacks on the releases on GitHub so to workaround you can reference this file for example 

https://github.com/dotnet/maui/releases/download/8.0.82/8.0.82.json

**Comment by mikebaumannch** [comment]
I understand the desire to always use the latest version to take advantage of new features. BUT, it’s crucial to ensure that critical bugs and regressions are minimized in these newer releases. Currently, there are several critical issues in recent versions of .NET MAUI (>8.0.62) that remain unresolved. For instance, https://github.com/dotnet/android/issues/9039  makes our app unsuitable for production environments. As a result, we've been advised to roll back to a more stable version.

But thanks for your workaround to still use the rollback

**Comment by mikebaumannch** [comment]
@rmarinho Could you provide a rollback file for 8.0.61? This is the latest working maui version for our environment

**Comment by rmarinho** [comment]
Sure here it goes

https://github.com/dotnet/maui/releases/download/8.0.61/8.0.61.json
