### ISSUE TITLE
[Bug] Visual Studio 2022 Preview 4 shows old MAUI templates 

### ISSUE THREAD

**Issue by nor0x** [dotnet/maui#2489]
### Description
I have followed the steps to get started (https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/#get-started-today)

1. Uninstall old previews of Visual Studio 2022
2. Uninstall all previous versions of .NET 6
3. Install Visual Studio 2022 Preview 4 with workloads (Mobile, Desktop, UWP, Desktop C++, MAUI preview)
4. Install Single-Project Extension

However, it seems that Visual Studio still has the previous MAUI templates, because the icons are different and there is still a separate WinUI project within the solution

### Expected Behavior
Usage of the lateste templates and single project

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2022 Preview 4

### Screenshots
![image](https://user-images.githubusercontent.com/3210391/133395224-c0b812b5-3777-42f3-8366-61e7d1e0732a.png)

**Comment by AswinPG** [comment]
Same issue for me too and the project does not load in vs2022 either. Giving this error
C:\Users\aswin\source\repos\MauiApp2\MauiApp2\MauiApp2\MauiApp2.csproj : error  : The project file cannot be opened. The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.macos\WorkloadManifest.json'.

**Comment by Lorymi** [comment]
@nor0x same

**Comment by Zachael** [comment]
The third template (with the correct icon) is coming from C:\Program Files\dotnet\template-packs\Microsoft.Maui.Templates.6.0.100-rc.1.1608.nupkg.

When I remove Microsoft.Maui.Templates.6.0.100-rc.1.1608.nupkg and restart VS 2022, I can still see the first two Maui templates with the different icon.

**Comment by Zachael** [comment]
There was a directory called .templateengine under my user directory. It had a folder named packages with the file Microsoft.Maui.Templates.6.0.100-preview.6.1003.nupkg.

I removed the file .templateengine and it fixed the problem.

**Comment by sergiojrdotnet** [comment]
Got the same error here. Even removing .templateengine did not solve the problem.

I did the following:

1. Uninstall all Visual Studio and its components.
2. Uninstall all versions of .NET.
3. Delete _.dotnet_ and _.templateengine_ from user folder.
4. Delete _Visual Studio 2022_ folder from user Documents.
5. Delete _Microsoft Visual Studio_ and _dotnet_ folders from Program Files.
6. Follow install steps from https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/#get-started-today

Now, none templates for maui are visible: 😢

![image](https://user-images.githubusercontent.com/72770006/133495370-fa411c60-de68-4769-bd89-b55ce7953524.png)

**Comment by sergiojrdotnet** [comment]
I have just installed the template manually from "%Program Files%\dotnet\template-packs" and now it works!

```
cd "C:\Program Files\dotnet\template-packs"
dotnet new -i .\Microsoft.Maui.Templates.6.0.100-rc.1.1608.nupkg
```

I also installed Android, iOS and MacCatalyst templates:

```
dotnet new -i .\Microsoft.Android.Templates.31.0.100-rc.1.12.nupkg
dotnet new -i .\Microsoft.iOS.Templates.15.0.100-rc.1.1534.nupkg
dotnet new -i .\Microsoft.MacCatalyst.Templates.15.0.100-rc.1.1534.nupkg
```

Visual Studio IDE

![Captura de tela 2021-09-15 173634](https://user-images.githubusercontent.com/72770006/133505902-d1737172-8436-46f8-a920-25dae73d8da0.png)

**Comment by nor0x** [comment]
thanks everyone for the info and suggestions. In my case the `.templateengine` tip from @Zachael did the trick

> There was a directory called .templateengine under my user directory. It had a folder named packages with the file Microsoft.Maui.Templates.6.0.100-preview.6.1003.nupkg.
> 
> I removed the directory .templateengine and it fixed the problem.

**Comment by HClausing** [comment]
> I have just installed the template manually from "%Program Files%\dotnet\template-packs" and now it works!
> 
> ```
> cd "C:\Program Files\dotnet\template-packs"
> dotnet new -i .\Microsoft.Maui.Templates.6.0.100-rc.1.1608.nupkg
> ```
> 
> I also installed Android, iOS and MacCatalyst templates:
> 
> ```
> dotnet new -i .\Microsoft.Android.Templates.31.0.100-rc.1.12.nupkg
> dotnet new -i .\Microsoft.iOS.Templates.15.0.100-rc.1.1534.nupkg
> dotnet new -i .\Microsoft.MacCatalyst.Templates.15.0.100-rc.1.1534.nupkg
> ```
> 
> Visual Studio IDE
> 
> ![Captura de tela 2021-09-15 173634](https://user-images.githubusercontent.com/72770006/133505902-d1737172-8436-46f8-a920-25dae73d8da0.png)

By this way the templates worked here. Thank you so much!
