### ISSUE TITLE
[Bug] The IDE has some errors after using the template to create the MAUI project

### ISSUE THREAD

**Issue by xiao-cao-x** [dotnet/maui#2490]
I have followed the steps to get started (https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/#get-started-today)

Uninstall old previews of Visual Studio 2022
Uninstall all previous versions of .NET 6
Install Visual Studio 2022 Preview 4 with workloads (Mobile, Desktop, UWP, Desktop C++, MAUI preview)
Install Single-Project Extension

And created a new project
![image](https://user-images.githubusercontent.com/76673990/133418292-3f285f93-69f1-4e59-bdcf-a497fb7f8ff2.png)

**Comment by zeus2nawaz** [comment]
IDE is correct, you need create project with new template than add all your files in to this project or you need set manually as there is no more start up class, now it is changed to MauiProgram

**Comment by xiao-cao-x** [comment]
> IDE is correct, you need create project with new template than add all your files in to this project or you need set manually as there is no more start up class, now it is changed to MauiProgram,
@zeus2nawaz  I created a project using a new template

**Comment by zeus2nawaz** [comment]
@xiao-cao-x ,what's your Maui version, 
Mine is v0.7.7.0 and it is working as expected new template with replace of MauiProgram class instead of start up,
Please update your maui version may be it will resolve your issue

**Comment by xiao-cao-x** [comment]
@zeus2nawaz 
How to check the maui version?

**Comment by zeus2nawaz** [comment]
maui-check from command prompt of powershell

**Comment by zeus2nawaz** [comment]
**dotnet tool update -global Redth.Net.Maui.Check** to update Maui

**Comment by xiao-cao-x** [comment]
> **maui-check** from command prompt or powershell

I have installed the MAUI workloads in Visual Studio 2022 Preview 4, but the maui-check output is as follows
![image](https://user-images.githubusercontent.com/76673990/133422088-37db04ab-dd33-43a4-88f2-7480ba91bd00.png)

**Comment by zeus2nawaz** [comment]
Try to install new MAUI templates by **dotnet new maui --search** from cmd, than install latest template may be resolve your issue

**Comment by TFreudi1** [comment]
Same thing for me, I updated everything create a new project and can't execute nothing, no Windowspart, no iOS part noc Androidpart, mostly it complaining  about IStartup, iAppHostbuilder.
![mauitest16092021](https://user-images.githubusercontent.com/4739177/133623769-8eb43b67-adf3-4942-8a11-49aaefd94c27.png)

**Comment by TFreudi1** [comment]
I mean since starting with the MAUI Previews I naver was able to run it, also not the samples like the Weather App. On different computers/installations but all are in German.

**Comment by xiao-cao-x** [comment]
> I mean since starting with the MAUI Previews I naver was able to run it, also not the samples like the Weather App. On different computers/installations but all are in German.

I can run Preview 4, Preview 5, Preview 6
But only Preview 6 successfully ran the WinUI option

**Comment by xiao-cao-x** [comment]
@TFreudi1 
Did you solve this problem?

**Comment by xiao-cao-x** [comment]
```
C:\Users\Administrator>maui-check
      _   _   _____   _____     __  __      _      _   _   ___
     | \ | | | ____| |_   _|   |  \/  |    / \    | | | | |_ _|
     |  \| | |  _|     | |     | |\/| |   / _ \   | | | |  | |
  _  | |\  | | |___    | |     | |  | |  / ___ \  | |_| |  | |
 (_) |_| \_| |_____|   |_|     |_|  |_| /_/   \_\  \___/  |___|

¤ .NET MAUI Check v0.8.6.0 ¤
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
This tool will attempt to evaluate your .NET MAUI development environment.
If problems are detected, this tool may offer the option to try and fix them for you, or suggest a way to fix them
yourself.

Thanks for choosing .NET MAUI!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
? Synchronizing configuration... ok
? Scheduling appointments... ok

? OpenJDK 11.0 Checkup...
  – 1.8.0-25 (C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25)
  – 11.0.12 (D:\SDK\JDK\jdk-11.0.12)
  – 16.0.2 (D:\SDK\JDK\jdk-16.0.2)

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
¤ Recommendation: Install OpenJDK11
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
! Attempt to fix? [y/n] (y): n

? Visual Studio 17.0.0-pre.4.0 Checkup...
  – 17.0.0-pre.4.1 - D:\IDE\Microsoft Visual Studio\2022\Preview
  – 16.11.3

× Skipped: Android SDK

× Skipped: Android Emulator

? .NET SDK Checkup...
  – 6.0.100-rc.1.21463.6 - C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6

? .NET SDK - Workload Deduplication Checkup...

? Edge WebView2 Checkup...
  – Found Edge WebView2 version 93.0.961.52

? .NET SDK - Workloads (6.0.100-rc.1.21458.32) Checkup...
  – android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 31.0.100-rc.1.12) installed.
  – ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-rc.1.1534) installed.
  – maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-rc.1.1534) installed.
  × tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-rc.1.1534) not installed.
  × macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-rc.1.1534) not installed.
  – maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-rc.1.1608) installed.
  – wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-rc.1.21451.13) installed.
  – microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-rc.1.21430.3) installed.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
¤ Recommendation: Install or Update SDK Workloads
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

! Attempt to fix? [y/n] (y): n
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


! There were one or more problems detected.
Please review the errors and correct them and run maui-check again.

Press enter to exit...
```

**Comment by TFreudi1** [comment]
No. I get also the both errors about tvOS and macos, but I'm not interested in that platforms. I still missing all mostly all options that are shown in this pic from the weather sample:
https://github.com/davidortinau/WeatherTwentyOne
![run-static-profiles](https://user-images.githubusercontent.com/4739177/134127851-41f97ab9-c925-46d2-963e-4a810982bd0c.png)

**Comment by xiao-cao-x** [comment]
> No. I get also the both errors about tvOS and macos, but I'm not interested in that platforms. I still missing all mostly all options that are shown in this pic from the weather sample

I still get exactly the same error:
![img](https://user-images.githubusercontent.com/76673990/133418292-3f285f93-69f1-4e59-bdcf-a497fb7f8ff2.png)

**Comment by TFreudi1** [comment]
What for options do you have here
![run](https://user-images.githubusercontent.com/4739177/134172835-099d926a-fd24-46d5-b212-c8ccd69ca970.png)
:

**Comment by matt-goldman** [comment]
I've got the same issue. COnfirming that I was using earlier previews of MAUI successfully (with nuget packages), everything up to date in maui-check, latest preview of VS2022, new MAUI app from template, and get this issue. It generates startup rather than MauiProgram.

Could this be an issue of interference from templates in earlier previews? Is there some cleanup required?

**Comment by matt-goldman** [comment]
Ok I am having some deployment issues still but the problem seems largely fixed for me. Here's how I did it:

1. Uninstall Vs2022 preview
2. Uninstall any .NET 6 SDKs from Control Panel
3. Reboot
4. Install VS2022 preview as per instructions at link above
5. Install single project SDK (as per link above)
6. Install Powershell 7
7. Make sure the maui-check tool is installed and up to date
8. Run the cleanup script from the maui-check repo (here: https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1)
9. Run `maui-check --force-dotnet`

After this I fired up VS2022 again (preview 4.1)  and the correct templates are now installed and a new MAUI app seems correct. As I said I'm having some deployment issues but at this stage they seem unrelated.
