### ISSUE TITLE
.net8 maui ios app crashing on startup on actual device 

### ISSUE THREAD

**Issue by sisaacks** [dotnet/maui#24932]
### Description

I am using vscode on a MAC 
The app runs fine in emulators 
But when I debug to the actual device...the app deploys, launches and then crashes and I get the errors listed below.
There is a lot about cannot find syncufusion PDB files but then why does the emulator work just fine?
I have tried different version of XCode, 15.2, 15.3, 15.5 and 16 but I always get the same result

The dotnet sdk version is 8.0.402

The dotnet workloads are
maui-ios -- Manifest Version: 8.0.82/8.0.100 -- Installation Source: SDK 8.0.400
ios -- Manifest Version: 17.5.8030/8.0.100 -- Installation Source: SDK 8.0.400
maui-mobile -- Manifest Version: 8.0.82/8.0.100 -- Installation Source:  SDK 8.0.400
maui -- Manifest Version: 8.0.82/8.0.100 -- Installation Source:  SDK 8.0.400

I am not sure what is going on, I have found many similar type issues on github but I have not yet found a solution.

I am also seeing a strange error Invalid Debug Adapter in vscode window output, and I am not sure what that is about.  I have googled and googled and have not found anything.  

ultimately I am getting a sigbart error which really doesnt tell me anything. (which you can see towards the bottom)

```
-----------------------------------------------------------------------------
You may only use the Microsoft Visual Studio .NET/C/C++ Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you
develop and test your applications.
------------------------------------------------------------------------------

2024-09-25 13:50:08.906 MauiMobileApp[995:337597] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
1|2024-09-25T20:50:09.0880770+00:00|TRACE|1|New log manager created
2|2024-09-25T20:50:09.2978110+00:00|TRACE|1|New log manager created
3|2024-09-25T20:50:09.3140290+00:00|TRACE|1|CreateLogger App
4|2024-09-25T20:50:09.3285790+00:00|TRACE|1|Created Logger 'App'
5|2024-09-25T20:50:09.3305860+00:00|TRACE|1|CreateLogger App
6|2024-09-25T20:50:09.3317160+00:00|TRACE|1|Created Logger 'App'
7|2024-09-25T20:50:09.3340880+00:00|TRACE|1|CreateLogger NFODataService
8|2024-09-25T20:50:09.3367950+00:00|TRACE|1|Created Logger 'NFODataService'
9|2024-09-25T20:50:09.3373630+00:00|TRACE|1|CreateLogger NFODataService
10|2024-09-25T20:50:09.3379160+00:00|TRACE|1|Created Logger 'NFODataService'
11|2024-09-25T20:50:09.3545170+00:00|TRACE|1|CreateLogger BLEService
12|2024-09-25T20:50:09.3578820+00:00|TRACE|1|Created Logger 'BLEService'
13|2024-09-25T20:50:09.3584640+00:00|TRACE|1|CreateLogger BLEService
14|2024-09-25T20:50:09.3589960+00:00|TRACE|1|Created Logger 'BLEService'
15|2024-09-25T20:50:09.3598860+00:00|TRACE|1|CreateLogger ApiUserUtility
16|2024-09-25T20:50:09.3607730+00:00|TRACE|1|Created Logger 'ApiUserUtility'
17|2024-09-25T20:50:09.3629570+00:00|TRACE|1|CreateLogger ApiUserUtility
18|2024-09-25T20:50:09.3648050+00:00|TRACE|1|Created Logger 'ApiUserUtility'
19|2024-09-25T20:50:09.3670650+00:00|TRACE|1|CreateLogger NFODataRetrievalService
20|2024-09-25T20:50:09.3701150+00:00|TRACE|1|Created Logger 'NFODataRetrievalService'
21|2024-09-25T20:50:09.3710840+00:00|TRACE|1|CreateLogger NFODataRetrievalService
22|2024-09-25T20:50:09.3739770+00:00|TRACE|1|Created Logger 'NFODataRetrievalService'
NightforceMauiMobileApp.dll: Loaded '/Users/sethisaacks/NFO/MauiMobileApp/bin/Debug/net8.0-ios/ios-arm64/MauiMobileApp.app/Microsoft.Maui.Controls.HotReload.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
NightforceMauiMobileApp.dll: Loaded '/Users/sethisaacks/NFO/MauiMobileApp/bin/Debug/net8.0-ios/ios-arm64/MauiMobileApp.app/Syncfusion.Maui.Picker.dll'. Cannot find or open the PDB file.
23|2024-09-25T20:50:10.1831130+00:00|TRACE|1|CreateLogger IImageSource
24|2024-09-25T20:50:10.7742420+00:00|TRACE|1|Created Logger 'IImageSource'
25|2024-09-25T20:50:10.7763430+00:00|TRACE|1|CreateLogger IImageSource
26|2024-09-25T20:50:10.7778870+00:00|TRACE|1|Created Logger 'IImageSource'
27|2024-09-25T20:50:10.9403260+00:00|TRACE|1|CreateLogger FileImageSourceService
28|2024-09-25T20:50:11.0261080+00:00|TRACE|1|Created Logger 'FileImageSourceService'
29|2024-09-25T20:50:11.0272410+00:00|TRACE|1|CreateLogger FileImageSourceService
30|2024-09-25T20:50:11.0282090+00:00|TRACE|1|Created Logger 'FileImageSourceService'
31|2024-09-25T20:50:11.0525830+00:00|TRACE|1|CreateLogger ModalNavigationManager
32|2024-09-25T20:50:11.0727870+00:00|TRACE|1|Created Logger 'ModalNavigationManager'
33|2024-09-25T20:50:11.0735680+00:00|TRACE|1|CreateLogger ModalNavigationManager
34|2024-09-25T20:50:11.0743780+00:00|TRACE|1|Created Logger 'ModalNavigationManager'
35|2024-09-25T20:50:11.1140060+00:00|TRACE|1|CreateLogger CreateUserViewModel
36|2024-09-25T20:50:11.1561860+00:00|TRACE|1|Created Logger 'CreateUserViewModel'
37|2024-09-25T20:50:11.1568150+00:00|TRACE|1|CreateLogger CreateUserViewModel
38|2024-09-25T20:50:11.1575240+00:00|TRACE|1|Created Logger 'CreateUserViewModel'
39|2024-09-25T20:50:11.4073380+00:00|TRACE|1|CreateLogger FontImageSourceService
40|2024-09-25T20:50:11.5395170+00:00|TRACE|1|Created Logger 'FontImageSourceService'
41|2024-09-25T20:50:11.5402760+00:00|TRACE|1|CreateLogger FontImageSourceService
42|2024-09-25T20:50:11.5409850+00:00|TRACE|1|Created Logger 'FontImageSourceService'
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x1011da400 - /private/var/containers/Bundle/Application/E1D2004F-5D07-4009-88F3-998BF382ECEB/MauiMobileApp.app/MauiMobileApp: mono_dump_native_crash_info
	0x1011c52ec - /private/var/containers/Bundle/Application/E1D2004F-5D07-4009-88F3-998BF382ECEB/MauiMobileApp.app/MauiMobileApp: mono_handle_native_crash
	0x101323a04 - /private/var/containers/Bundle/Application/E1D2004F-5D07-4009-88F3-998BF382ECEB/MauiMobileApp.app/MauiMobileApp: sigabrt_signal_handler.cold.1
	0x1011d9bf0 - /private/var/containers/Bundle/Application/E1D2004F-5D07-4009-88F3-998BF382ECEB/MauiMobileApp.app/MauiMobileApp: mono_runtime_setup_stat_profiler
	0x221632274 - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x200a7ac14 - /usr/lib/system/libsystem_kernel.dylib : <redacted>
	0x200a7ac48 - /usr/lib/system/libsystem_kernel.dylib :
	0x1df0c29b4 - /System/Library/PrivateFrameworks/TCC.framework/TCC : <redacted>
	0x1df0c318c - /System/Library/PrivateFrameworks/TCC.framework/TCC : <redacted>
	0x1df0c01bc - /System/Library/PrivateFrameworks/TCC.framework/TCC : <redacted>
	0x221727ee4 - /usr/lib/system/libxpc.dylib : <redacted>
	0x22171aee8 - /usr/lib/system/libxpc.dylib : <redacted>
	0x1c9205f2c - /usr/lib/system/libdispatch.dylib : <redacted>
	0x1c9223e38 - /usr/lib/system/libdispatch.dylib : <redacted>
	0x1c921869c - /usr/lib/system/libdispatch.dylib : <redacted>
	0x2216c7e14 - /usr/lib/system/libsystem_pthread.dylib : _pthread_wqthread
	0x2216c7b7c - /usr/lib/system/libsystem_pthread.dylib : start_wqthread
=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x200a583a4):0x200a58394  ff 0f 5f d6 c0 03 5f d6 30 41 80 d2 01 10 00 d4  .._..._.0A......
0x200a583a4  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
0x200a583b4  74 cd ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  t........{...._.
0x200a583c4  c0 03 5f d6 90 32 80 d2 01 10 00 d4 03 01 00 54  .._..2.........T
Application 'com.companyname.MauiMobileApp' terminated (with exit code '' and/or crashing signal '6).
The program 'NightforceMauiMobileApp.dll' has exited with code 0 (0x0).

[log output.txt](https://github.com/user-attachments/files/17138933/log.output.txt)

```

### Steps to Reproduce

Created .net MAUI project on windows machine....save in source control
On a MAC, use VSCode to pull from your repo
In debug mode run the project to an actual device.....the app loads and instantly crashes
However the emulator works perfectly

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No, I googled for days and looked on github at similar issues but nothing has fixed this

**Comment by drasticactions** [comment]
@rolfbjarne Do you know ways to help this user debug this?

The PDBs are probably not the issue. The Debug Adapter error you see is probably because the app is crashing at start up so it doesn't have time to attach. It most likely isn't the direct cause of the crash you see.

Have you tried deploying your application without debugging? Does it work then? 
Does your app consume native iOS frameworks? If so, are those compatible with iOS Devices or just the simulator?

**Comment by rolfbjarne** [comment]
> /System/Library/PrivateFrameworks/TCC.framework/TCC

You're missing a feature description string in the Info.plist.

The log unfortunately doesn't explain much as to which string you're missing, but I believe this is printed to the device log (https://support.apple.com/en-in/guide/console/cnsl1012/mac).

A crash report might also give some clues (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#crash-reports).

**Comment by sisaacks** [comment]
@rolfbjarne thank you for the input, but I am confused was an emulator would work just fine?  I can go back to my old xamarin project and no issues...and the plist are identical.  I have been at this for a couple weeks now and just continually spinning my wheels. 

I thought maybe it was the linker, so I set debug to LinkAll and that brought forth yet another problem I had never seen.  

Each thing I have tried I get more and more errors...yet it works fine in Xamarin.

**Comment by rolfbjarne** [comment]
> I am confused was an emulator would work just fine?

I don't think iOS enforces the feature description strings in the simulator.

> I have been at this for a couple weeks now and just continually spinning my wheels.

Please attach the device log + crash reports as I mentioned in my previous comment, and we can have a look at them.

**Comment by sisaacks** [comment]
@rolfbjarne thank you for your  help, I figured it out.  Turns out, my plist files were not the same.  How did you know it was a plist issue from the errors I posted?  was it this "/System/Library/PrivateFrameworks/TCC.framework/TCC" ?

**Comment by rolfbjarne** [comment]
> @rolfbjarne thank you for your help, I figured it out. Turns out, my plist files were not the same. How did you know it was a plist issue from the errors I posted? was it this "/System/Library/PrivateFrameworks/TCC.framework/TCC" ?

Yes, TCC means "Transparency, Consent, and Control)", and is the code on iOS (and macOS) that is responsible for making sure the user has consented to what the app is trying to do. If it shows up in a crash report, it's pretty much always something missing from the Info.plist.

Closing, since I understand you've figured out the problem.
