### ISSUE TITLE
Maui app is not built into any iOS device 

### ISSUE THREAD

**Issue by giwonseoneolab** [dotnet/maui#24937]
### Description

Ever since I updated to new mac OS and iOS18.0, MAUI app is not built into the iOS device.

### Steps to Reproduce

1. Update your mac os to the newest version
2. Update Xcode to 16.0
3. In Visual Studio 2022, build the app into iOS device.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Did you find any workaround?

Not at all. Wasted my time real good.

**Comment by drasticactions** [comment]
https://github.com/dotnet/maui/issues/24819

The pinned issue at the top of this repo explains that Xcode 16.0 support is being worked on and is currently not supported by the shipping iOS SDK (and by extension, MAUI UI).
