### ISSUE TITLE
Workload sets don't seem to work for pinning a MAUI version (in DevOps)

### ISSUE THREAD

**Issue by jameslavery** [dotnet/maui#24940]
### Description

Following #24892, I've tried using Workload Sets as documented [here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets).

However, when configuring our DevOps pipeline to use workload sets, we're getting the following output and error.

> C:\hostedtoolcache\windows\dotnet\dotnet.exe workload install maui --version 8.0.21
> 
> Successfully updated workload install mode to use workload-set.
> Installing workload version 8.0.21.
> Workload installation failed. Rolling back installed packs...
> Workload installation failed: Failed to install workload version 8.0.21: Version 8.21.0 of package microsoft.net.workloads.8.0.0 is not found in NuGet feeds [https://api.nuget.org/v3/index.json;C:\Program](https://api.nuget.org/v3/index.json;C:/Program) Files (x86)\Microsoft SDKs\NuGetPackages\".

Is this a known problem? Or am I 'doing it wrong'?

I have not tried using locally - only in DevOps.

### Steps to Reproduce

1. Create a DevOps pipeline template to install MAUI:
 ```
  - task: DotNetCoreCLI@2
    displayName: Install MAUI
    inputs:
      command: 'custom'
      custom: 'workload'
      arguments: 'install maui $(WorkloadArguments)'
```

2. Set the DevOps _WorkloadArguments_ variable to "--version 8.0.21"
3. Run a pipeline which uses the template.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

n/a

### Did you find any workaround?

No.

### Relevant log output

```shell
C:\hostedtoolcache\windows\dotnet\dotnet.exe workload install maui --version 8.0.21

Successfully updated workload install mode to use workload-set.
Installing workload version 8.0.21.
Workload installation failed. Rolling back installed packs...
Workload installation failed: Failed to install workload version 8.0.21: Version 8.21.0 of package microsoft.net.workloads.8.0.0 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".
```

**Comment by jfversluis** [comment]
Reading the doc it says this is supported as of .NET 8.0.400 and up, is that the case for you?

Also what is suspicious is that in the error message it talks about 8.21.0 instead of 8.0.12.

@rmarinho ?

**Comment by jameslavery** [comment]
> Reading the doc it says this is supported as of .NET 8.0.400 and up, is that the case for you?
> 
> Also what is suspicious is that in the error message it talks about 8.21.0 instead of 8.0.12.
> 
> @rmarinho ?

Yes, I've upgraded to .NET 8.0.400 as follows:

>   - task: UseDotNet@2
>     displayName: Set .NET Version
>     inputs:
>       version: $(DotNetVersion)

with a DotNetVersion set to 8.0.400

I assume that this is the right way to do it! Think so because there's a message in the output "Successfully updated workload install mode to use workload-set." - before updating to 8.0.400, I was getting an error that --version wasn't recognised.

Good point on the versions in the error message. You had me go back to check I hadn't made a silly typo of 8.21.0! But yes, I wonder if there's a typo in a manifest somewhere up there.

**Comment by jfversluis** [comment]
While the version number is still weird, thinking about it for a bit more this makes sense.

The cause is still "this only works from 8.0.400" and up, because that includes the version of .NET MAUI that corresponds to .NET 8.0.400, which is 8.0.82 at least. Also see: https://github.com/dotnet/maui/wiki/Release-Versions.

If you use that version of .NET MAUI, does it start working then?

**Comment by rmarinho** [comment]
Can you try do `--version 8.0.82` ?

**Comment by baronfel** [comment]
Yes - workload set versions typically mirror the version of the _SDK_ in use, not of any specific workload component (MAUI, Aspire, etc). We have improvements coming in the 9.x series of SDKs to help users discover what valid versions might be (including tab-completion for `--version`, a dedicated command to query versions, etc) but in addition we should probably have stronger safeguards for when users input clearly-incorrect (from the system's point of view) version numbers.

Over the longer term we do want to support [installing a particular workload set by these specific-component versions](https://github.com/dotnet/sdk/issues/42367#install-workload-set-from-workload-version), but that requires additional work to flow through data about what components are in each workloads and what versions they are at in a way that is efficient and doesn't cause a big perf hit.

**Comment by jameslavery** [comment]
> Can you try do `--version 8.0.82` ?

Still fails:

> C:\hostedtoolcache\windows\dotnet\dotnet.exe workload install maui --version 8.0.82
> 
> Successfully updated workload install mode to use workload-set.
> Installing workload version 8.0.82.
> Workload installation failed. Rolling back installed packs...
> Workload installation failed: Failed to install workload version 8.0.82: Version 8.82.0 of package microsoft.net.workloads.8.0.0 is not found in NuGet feeds [https://api.nuget.org/v3/index.json;C:\Program](https://api.nuget.org/v3/index.json;C:/Program) Files (x86)\Microsoft SDKs\NuGetPackages\".

**Comment by baronfel** [comment]
@jameslavery what about `--version 8.0.402`?

**Comment by nll** [comment]
Using 8.0.402 (`dotnet workload install maui --version 8.0.402`) does work and installs MAUI workload 8.0.82. So the confusion is with the version used, that is about the workload set and not with the workload version it self.

**Comment by jameslavery** [comment]
Yes, using `dotnet workload install maui --version 8.0.402` does work. Thank you.

Is there a resource which gives the MAUI version in a workload set? I thought I saw a link earlier, but can't find it now.

**Comment by baronfel** [comment]
@jameslavery not yet, unfortunately. The team is chatting now about the best way to surface that information in docs, release notes, etc. , but the next step for the CLI will be letting you ask "what workload set contains MAUI X"

**Comment by jameslavery** [comment]
> @jameslavery not yet, unfortunately. The team is chatting now about the best way to surface that information in docs, release notes, etc. , but the next step for the CLI will be letting you ask "what workload set contains MAUI X"

Ok - good to know it's in the pipeline (pun intended 😄 ).

Thanks all for the help on this.

**Comment by jameslavery** [comment]
Maybe my last question... 

So back to the original version I wanted to use. Do those 'in the know' know which workload set contains MAUI 8.0.21?

Or is 8.0.21 too old to be in a workload set?

**Comment by nll** [comment]
The versions in .NET are confusing at times and workloads (sets now) adds to that with multiple levels of indirection.

- [Workload Set Versions](https://www.nuget.org/packages/Microsoft.NET.Workloads.8.0.400#versions-body-tab) 
- [MAUI Workload Versions](https://www.nuget.org/packages/Microsoft.NET.Sdk.Maui.Manifest-8.0.100#versions-body-tab)
- [MAUI Controls Versions](https://www.nuget.org/packages/Microsoft.Maui.Controls/#versions-body-tab)

@jameslavery You can check the MAUI workload version referenced in each workload set quickly  by going to its Nuget page and on the "Open in NuGet Package Explorer" look at the json file inside. e.g. https://nuget.info/packages/Microsoft.NET.Workloads.8.0.400/8.402.0

Workload sets seems to be a new thing, the MAUI workload that is defined on the first workload set is 8.0.71. 

Then on top of that MAUI (Controls) used by the app is controlled at the project level like [this](https://github.com/dotnet/maui/discussions/24807).

**Comment by rmarinho** [comment]
YEah and my bad to add to the confusion I was thinking the feature to lookup the maui version was already working. :) Sorry @jameslavery .

**Comment by amilici** [comment]
So, in summary, once you have 8.0.4 installed there is no way to go back to 8.0.201? I kind of need to this this, but from what I can tell it is not possible. Is it even possible to set a new environment to use 8.0.201 and associated workloads?

**Comment by amilici** [comment]
So, in summary, once you have 8.0.4 installed there is no way to go back to 8.0.201? I kind of need to this this, but from what I can tell it is not possible. Is it even possible to set a new environment to use 8.0.201 and associated workloads?

**Comment by rmarinho** [comment]
for net8 you can create or use one of the rollback files on the releases here in Github

**Comment by amilici** [comment]
Thanks for the reply. What would the rollback file to get from 

Workload version: 8.0.400

Installed Workload Id      Installation Source
----------------------------------------------
maui-android               SDK 8.0.400        
ios                        SDK 8.0.400        
android                    SDK 8.0.400     

to 8.0.201 ?

Or where could I find it? I don't see any documentation on how to create a rollback file.
