### ISSUE TITLE
The RuntimeIdentifier 'iossimulator-x64' is invalid. 

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#2495]
After upgrading Visual Studio 2022 to preview 4. I can't complie iOS libraries.

> The RuntimeIdentifier 'iossimulator-x64' is invalid. 

What does this mean?

**Comment by arivoir** [comment]
Since iOS compilation is broken MAUI projects can not be compiled either. It would be interesting to have a way to disable iOS compilation. Now the only way to disable is to edit every single file and remove the TargetFramework

**Comment by drasticactions** [comment]
iOS Complication isn't broken, that specific iOS TargetFramework from an earlier version of the SDK package, and so workarounds that were in place in earlier maui templates are not needed.

In your csproj, you should be able to remove these lines

```
		<InvariantGlobalization Condition="$(TargetFramework.Contains('-maccatalyst'))">true</InvariantGlobalization>
		<RuntimeIdentifier Condition="$(TargetFramework.Contains('-ios'))">iossimulator-x64</RuntimeIdentifier>
		<RuntimeIdentifier Condition="$(TargetFramework.Contains('-maccatalyst'))">maccatalyst-x64</RuntimeIdentifier>
```

**Comment by arivoir** [comment]
That's the problem, after removing those lines, which I had removed before posting the issue, the problem is still there. Already deleted all "bin" and "obj" folder, what else should I remove?

**Comment by arivoir** [comment]
Somo more things I found it can help figure out the issue.

The project I'm not being able to compile targets both iOS and MacCatalyst

`<TargetFrameworks>net6.0-ios;net6.0-maccatalyst</TargetFrameworks>`

When clicking in the error in the "Error List" window of VS. it drives me to this
![image](https://user-images.githubusercontent.com/17496741/133635648-5cb5c3eb-e3f2-4ae0-ba14-40feed1c31f7.png)

So, apparently the problem is with mac-catalyst compilation

**Comment by arivoir** [comment]
Removing MacCatalyst from the TargetFramework's worked. What's the problem with targeting both platforms?

**Comment by arivoir** [comment]
Adding this workarounds the issue

```
  <PropertyGroup>
    <RuntimeIdentifier Condition="$(TargetFramework.Contains('-maccatalyst'))">maccatalyst-x64</RuntimeIdentifier>
  </PropertyGroup>
```
This wasn't needed in preview7. Looks like a regresion

**Comment by arivoir** [comment]
I compiled the project again, referencing it in another solution and the problem reappeared, even with the hard coded runtime-identifier. I went back to the original solution and now it also fails there.

**Comment by filipnavara** [comment]
It seems there's a funky glitch in how the runtime identifier is verified.

Let's say I have project A with `<TargetFramework>net6.0-ios</TargetFramework>` and project B with `<TargetFrameworks>netstandard2.1;net6.0-macos</TargetFrameworks>`. Project A references project B. I would expect that building project A succeeds but what seems to happen is that it tries to build both TFMs of project B while flowing `RuntimeIdentifier` from the parent project. That results in an attempt to build project B with TFM `net6.0-macos` and RID `iossimulator-x64` which is invalid combination.

cc @rolfbjarne

**Comment by rolfbjarne** [comment]
@filipnavara would you happen to have a test solution for those results, or a binlog from the build?

**Comment by filipnavara** [comment]
I tried to repro it on a smaller project but it didn't trigger so I guess it must be somewhat more complex. I should be able to make the binlog though (already had it and deleted it and then reinstalled .NET on the machine so let's hope it reproduces).

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#13482
