### ISSUE TITLE
Setting NavigationPage.HasNavigationBar="False" on modally presented NavigationPage causes top padding on iOS

### ISSUE THREAD

**Issue by Axemasta** [dotnet/maui#24972]
### Description

If you push a modal page (`new NavigationPage(new FooPage())`) and set `NavigationPage.HasNavigationBar="False"` there is a small top padding applied to the content page. This padding is not present when the navigation bar is being displayed.

Originally I thought this was an issue caused somewhere in prism (see [#3064](https://github.com/PrismLibrary/Prism/issues/3064)) however after upgrading to the latest maui controls & workloads version (8.0.91 controls, 8.0.82/8.0.400.2 workloads) I have noticed the issue got worse (the padding required has gone from 5px to 8px). I have been able to reproduce, in my reproduction the base page has no padding & the modal does:

Landing - non modal page
<img width="250" alt="Screenshot 2024-09-27 at 17 29 58" src="https://github.com/user-attachments/assets/bf7c4d12-2cc3-4508-9234-73c2a106276a">

Modal page, the thin like between the yellow & green should not be there
<img width="250" alt="Screenshot 2024-09-27 at 17 30 23" src="https://github.com/user-attachments/assets/33341f85-561d-4a56-8dbd-1d71a3828f7b">

### Steps to Reproduce

1. Navigate modally to a navigation page wrapped content page
2. On the content page set `NavigationPage.HasNavigationBar="False"`
3. Try and place content at the very top of the content page

### Link to public reproduction project repository

https://github.com/Axemasta/NavigationBarPaddingRepro

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16+

### Did you find any workaround?

Set a negative top padding of `-8px`:
```xml
<ContentPage.Padding>
    <OnPlatform x:TypeArguments="Thickness">
        <!-- <On Platform="iOS" Value="0,-8,0,0" /> -->
    </OnPlatform>
</ContentPage.Padding>
```

**Comment by Axemasta** [comment]
This issue is most likely the same root cause as #20418, however that issue closed without resolution and required prism whereas this issue reproduces the issue outside of prism!

**Comment by jaosnz-rep** [comment]
I can repro it at iOS platform on the latest 17.11.5(8.0.91&8.0.90).
![Image](https://github.com/user-attachments/assets/ab14ab0a-52c0-429e-9900-79e233fcee1c)

**Comment by kubaflo** [comment]
Hi, @Axemasta in my opinion it is not a bug, the pages are correctly placed within their safe area

<img src="https://github.com/user-attachments/assets/c90c60f8-619b-4e69-ab70-2c6748daf623"/>

It looks more like a status bar issue which is not handled by MAUI, but by the Community toolkit

**Comment by Axemasta** [comment]
> Hi, [@Axemasta](https://github.com/Axemasta) in my opinion it is not a bug, the pages are correctly placed within their safe area

I think you are right, I've checked the sample without the behavior applied and it seems to layout fine. I'll raise it with the MCT team

**Comment by kubaflo** [comment]
@Axemasta here it is: https://github.com/CommunityToolkit/Maui/pull/2309 :)

**Comment by Axemasta** [comment]
Oh wow! you are a machine Jakob! 🥳
