### ISSUE TITLE
[iOS] Trimming in Release is too aggressive, is there a workaround?

### ISSUE THREAD

**Issue by semdevel** [dotnet/maui#24976]
### Description

I'm facing a problem that I'm trying to resolve. My MAUI Blazor Hybrid app implements Blazor wrapper for a JavaScript library Leaflet for interactive maps in Blazor. Everything works well, map is properly drawed for Windows (Debug/Release) and for Android (Debug/ Release).

Debug mode on iOS platform works normally. Release mode on iOS doens't work properly and map is not drawed. On Android it works, because it is possible to turn trimming off and publish without it, but it is not allowed on iOS.

Is there a workaround or can someone help? I created public repo, the problem can be demostrated there.

### Steps to Reproduce

1. Switch to Release.
2. Start without debugging on physical devices. Expect same behaviour on iOS simulators.

### Link to public reproduction project repository

https://github.com/semdevel/MapApp

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18.0, iOS 12.5.5

### Did you find any workaround?

Not yet

**Comment by pictos** [comment]
From docs you can define a descriptor format, as shown in docs. [Here](https://github.com/dotnet/runtime/blob/main/docs/tools/illink/data-formats.md#descriptor-format) you can find guidance on how to do it

**Comment by semdevel** [comment]
I made changes according to you description.

What I did:

1. I created **ILLink.Descriptors.xml** file.
![image](https://github.com/user-attachments/assets/d118d313-08c9-4848-a61f-91b5337fb735)

2. Then I set the file as embedded resource.
![image](https://github.com/user-attachments/assets/183a6a6c-a059-4535-ba5d-1f55dc2482db)

4. Then I set a content of created file to preserve both razor components so they should not be trimmed?
![image](https://github.com/user-attachments/assets/974f6923-c4a1-402d-aeb0-996de4c9da1c)

5. At the end, I used this according to the docs.
![image](https://github.com/user-attachments/assets/c11bee0b-5ceb-4918-b062-eb891dab48ad)

Still same, it doesn't work. Can you or somebody else try to implement it using my demo app in  public repo? I still don't know what I'm doing wrong.

**Comment by semdevel** [comment]
Is there anyone who could test the issue?

**Comment by jonmdev** [comment]
What was your solution @semdevel ?
