### ISSUE TITLE
iOS Crashes when debug into iPhone Emulator.

### ISSUE THREAD

**Issue by rrodriguez1989** [dotnet/maui#24974]
### Description

After updated the .Net Maui workload, I getting and error when drug into iOS Emulator, I'm trying updated to the lasted version of Xcode but is not working, when I use the Physical device is working as expected. 

### Steps to Reproduce

1. Create a .Net Maui App
2. Try to run on iOS device emulator
<img width="1253" alt="image" src="https://github.com/user-attachments/assets/040d6945-9106-4f8c-8e36-0dc033ba1d09">

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.91 SR9.1

### Affected platforms

iOS

**Comment by jfversluis** [comment]
What version of Xcode? What version of the workloads? Do you have more logging or error messages? Is this a blank .NET MAUI project or did you add something more? Have you deleted the bin & obj folders and rebuild the project?

**Comment by rrodriguez1989** [comment]
Hi @jfversluis , Thanks for your reply, I'm using Xcode version 16, before to update Xcode I'm getting the same error, I'm trying deleting the bin and obj folders. But for some reason, when I run and debug the application into the emulator using Visual Studio for Mac (Retired on August :*( ) Is working. I think the problem is on Visual Studio Code using the .NET MAUI extension. I'm using the Pre-Release version because is the only release that have HotReload for XAML and I need Hot Reload for my development. Any recommendations such as Uninstall and reinstall the Visual Studio Code or switch to the release version of .NET MAUI Extension? Thanks :)

**Comment by jfversluis** [comment]
Make sure to have .NET 8.0.402 installed and then can you do `dotnet workload install maui --version 8.0.402.1`?

Then also be sure the Xcode 16 is selected. Does that work? If not, does it work to do `dotnet build -t:Run -f net8.0-ios` from the command-line?

**Comment by rrodriguez1989** [comment]
Thanks @jfversluis , Is working again, but the Hot Reload for XAML is stopped working. Maybe for the future updates of the VS Code Extension for .NET MAUI must be resolved. I'm waiting for that.

**Comment by jfversluis** [comment]
Perfect, glad you got it resolved! Thanks for letting us know!
