### ISSUE TITLE
MAUI 8.0.82 raises on Android Javax.Crypto.AEADBadTagException

### ISSUE THREAD

**Issue by erossini** [dotnet/maui#24986]
### Description

I have my `.NET 8 MAUI` application and I tried to deploy it on a real Android device after updating `MAUI` to the version 8.0.82

When the application starts I get this error

> Javax.Crypto.AEADBadTagException

![image](https://github.com/user-attachments/assets/d00cc2af-c68c-4ac9-aeb7-cbb729f8cc11)

I understood the error comes from changes from the `SecurityStorage` in the Maui Essentials. On GitHub, I read that the workaround is to set to `False` in the `AndroidManifest` the backup like that

```xml
<application android:allowBackup="false" 
        android:fullBackupContent="@xml/auto_backup_rules" 
        android:icon="@mipmap/appicon" android:supportsRtl="true" 
	    android:label="Language In Use" 
        android:dataExtractionRules="@xml/appcenter_backup_rule">
```

but I continue to receive the message and I can't run the application. Checking the [preview documentation](https://github.com/dotnet/docs-maui/blob/3bc393baacecec73e806fda94f320a13e85ba436/docs/platform-integration/storage/secure-storage.md), I read I have to update also the *auto_backup_rules.xml* like the following

```xml
<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
        <include domain="sharedpref" path="."/>
        <exclude domain="sharedpref" 
                 path="${applicationId}.microsoft.maui.essentials.preferences.xml"/>
</full-backup-content>
```

but it is not working. How can I fix this issue?

### Public API Changes

Looking around, this could be related to the `SecurityStorage`.

### Intended Use-Case

When the application starts, this error is immediately raised by the app only in Android.

I saw a few posts but none of them offer a solutions. For example:
- https://github.com/dotnet/maui/issues/18872
- https://github.com/dotnet/maui/issues/18230
- https://stackoverflow.com/questions/79034046/maui-android-javax-crypto-aeadbadtagexception
- https://github.com/dotnet/maui/issues/22239

**Comment by AramMar** [comment]
I have the same issue on A25. On other phones work

**Comment by jaosnz-rep** [comment]
@erossini Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
