### ISSUE TITLE
Cannot using the control of CommunityToolkit.WinUI.Controls.Primitives

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#24982]
### Description

Repo sample
https://github.com/jingliancui/MAUIWinuiCommunityIssue

![image](https://github.com/user-attachments/assets/86483916-6756-4d09-8bdb-9056b397c451)

### Steps to Reproduce

1. Download the sample repo and open the sln using vs2022
2. Change the build platform in windows in vs2022
3. Build the app

Expect: build pass
Actual: build failed

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Can you please create a sample repro project of how you've set this up and are using this library? I'm assuming you want to use this only with the WinUI portion of your app (since that's the only one it would work with).

**Comment by jingliancui** [comment]
@drasticactions uploaded
https://github.com/jingliancui/MAUIWinuiCommunityIssue

**Comment by drasticactions** [comment]
This is not a bug in MAUI.

<img width="865" alt="image" src="https://github.com/user-attachments/assets/ea845c0d-a788-4090-9387-313744a1117e">

https://github.com/jingliancui/MAUIWinuiCommunityIssue/blob/main/SampleApp/SampleApp/SampleApp.csproj#L4C84-L5C3

The list of supported versions for that library does not include `net8.0-windows10.0.19041.0`, which is the default TFM set in the template. If you change the default TFM in your csproj to one of the windows10.0 TFMs the library uses (like `net8.0-windows10.0.22621.0`), it should work fine. I'm not sure why they compile it for every other version of `windows10` except for that one, but I would ask them about that.

**Comment by jingliancui** [comment]
> This is not a bug in MAUI.
> 
> 
> 
> <img width="865" alt="image" src="https://github.com/user-attachments/assets/ea845c0d-a788-4090-9387-313744a1117e">
> 
> 
> 
> https://github.com/jingliancui/MAUIWinuiCommunityIssue/blob/main/SampleApp/SampleApp/SampleApp.csproj#L4C84-L5C3
> 
> 
> 
> The list of supported versions for that library does not include `net8.0-windows10.0.19041.0`, which is the default TFM set in the template. If you change the default TFM in your csproj to one of the windows10.0 TFMs the library uses (like `net8.0-windows10.0.22621.0`), it should work fine. I'm not sure why they compile it for every other version of `windows10` except for that one, but I would ask them about that. 
> 
> 

yeah, thanks and please help to ask, thanks so much.
