### ISSUE TITLE
In MacCatalyst App Email.Default.IsComposeSupported always returns false in macOS!!!

### ISSUE THREAD

**Issue by last-Programmer** [dotnet/maui#24991]
### Description

I am trying to send mails from MacCatalyst App and when checkeing Email.Default.IsComposeSupported it always returns false.

I would like to know whether sending emails is supported in MacCatalyst?

According to the documentation here https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/email?view=net-maui-8.0&tabs=macios it seems to be supported. But it is not working.

### Steps to Reproduce

Create a Maui App and check for Email.Default.IsComposeSupported and run it as a MacCatalyst app in macOS and you will see that it always retunrs false.

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Looking at the source this was disabled as a whole, so no wonder its not working right now 😄 

Opened a PR to reenable it! Thanks for the report!
