### ISSUE TITLE
Platform specific Razor pages compiled for all platforms

### ISSUE THREAD

**Issue by RamType0** [dotnet/maui#25019]
### Description

I have a Purchase.razor file in Platform/Android/Pages folder, which has some platform specific codes inside.
And then build project, It will emits error for platforms other than Android.

### Steps to Reproduce

1. Create Purchase.razor at Platforms/Android/Pages
``` razor
@page "/Purchase"

@using global::Android;

```

2. Build for other platforms.

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

**Comment by drasticactions** [comment]
https://github.com/dotnet/maui/blob/efa6b9795e5d6fc75f34a18aa6ebf1fb890c82ba/src/MultiTargeting.targets#L26-L31

Those folders work by a multitargetting targets file. It's for `.cs` files, not `.pages` so that code is going to compile for all platforms. That was always the design, and the docs only show those folders [working with code](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code?view=net-maui-8.0), not Razor. I would also verify in your `.csproj` if that file is listed for Compile. If it is, it's going to be listed for all platforms.

I'm not sure if that means pages or other types of "Not strictly `.cs` but still can be compiled" should be included in that list. The simple way around this would be to wrap the page in an `#if ANDROID` and then it should only compile for it.

@mattleibow What do you think?

**Comment by RamType0** [comment]
I am using #if workaround for now.
But it is impossible to use using directive with this workaround.
________________________________
差出人: Tim Miller ***@***.***>
送信日時: Tuesday, October 1, 2024 2:41:52 PM
宛先: dotnet/maui ***@***.***>
CC: Ram.Type-0 ***@***.***>; Author ***@***.***>
件名: Re: [dotnet/maui] Platform specific Razor pages compiled for all platforms (Issue #25019)


https://github.com/dotnet/maui/blob/efa6b9795e5d6fc75f34a18aa6ebf1fb890c82ba/src/MultiTargeting.targets#L26-L31

Those folders work by a multitargetting targets file. It's for .cs files, not .pages so that code is going to compile for all platforms. That was always the design, and the docs only show those folders working with code<https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code?view=net-maui-8.0>, not Razor. I would also verify in your .csproj if that file is listed for Compile. If it is, it's going to be listed for all platforms.

I'm not sure if that means pages or other types of "Not strictly .cs but still can be compiled" should be included in that list. The simple way around this would be to wrap the page in an #if ANDROID and then it should only compile for it.

@mattleibow<https://github.com/mattleibow> What do you think?

**Comment by jfversluis** [comment]
Why is that impossible? You can also wrap using statements in #if directives.

**Comment by RamType0** [comment]
.razor does not allow preprocessor directive at root.
It only allows preprocessor inside `@code{}` or `@{}`. but we cannot use `using` inside of these blocks.

**Comment by RamType0** [comment]
> Why is that impossible? You can also wrap using statements in #if directives.

@jfversluis I said using directive, not a statement.

**Comment by jfversluis** [comment]
Gotcha, that makes sense. You can still work around it then by using fully qualified types in your code block I guess. 

From a architectural standpoint I think what I would do is create an interface and have the implementation differ between platforms and inject that. Depending on what you're trying to do exactly that will also be better for your code reuse. Or at least use partial classes. All that is described [here](https://learn.microsoft.com/dotnet/maui/platform-integration/invoke-platform-code).

What @drasticactions is saying I guess would look something like this in your csproj, [adding the multi-targeting](https://learn.microsoft.com/dotnet/maui/platform-integration/configure-multi-targeting#configure-folder-based-multi-targeting) yourself and be able to control it.

```xml
    <!-- Android -->
    <ItemGroup Condition="$(TargetFramework.StartsWith('net9.0-android')) != true">
        <Compile Remove="**\Android\**\*.cs" />
        <Compile Remove="**\Android\**\*.razor" />
        <None Include="**\Android\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
        <None Include="**\Android\**\*.razor" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    </ItemGroup>
```

Not 100% convinced this would work though.

Then there is also the option to add a code-behind file. If you add a MyFile.razor.cs file it will be picked up as a code-behind file. That way the same rules apply as to any other cs file.

See [here](https://learn.microsoft.com/aspnet/core/blazor/components/#partial-class-support).

Couple of options here to explore and use, I don't think this is a but in the .NET MAUI SDK necessarily, so I'll be closing this one here. Good luck!

**Comment by RamType0** [comment]
> What @drasticactions is saying I guess would look something like this in your csproj, [adding the multi-targeting](https://learn.microsoft.com/dotnet/maui/platform-integration/configure-multi-targeting#configure-folder-based-multi-targeting) yourself and be able to control it.
> 
> ```
>     
>     <ItemGroup Condition="$(TargetFramework.StartsWith('net9.0-android')) != true">
>         <Compile Remove="**\Android\**\*.cs" />
>         <Compile Remove="**\Android\**\*.razor" />
>         <None Include="**\Android\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
>         <None Include="**\Android\**\*.razor" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
>     </ItemGroup>
> ```
> 
> Not 100% convinced this would work though.

I tried this, but this doesn't work and my razor file is still compiled for other platforms.

Also I found another issue that we could not attach breakpoint inside `#if` directives.(This must be Blazor problem but not MAUI)

**Comment by RamType0** [comment]
https://github.com/dotnet/razor/issues/10954#issuecomment-2392849974
It was actually MAUI specific issue.
