### ISSUE TITLE
Error missing assembly when add bundle ID

### ISSUE THREAD

**Issue by raselldev** [dotnet/maui#25021]
### Description

i just add bundle ID to my MAUI App, after adding bundle ID i got some error:

1. Error CS0246: The type or namespace name 'Application' could not be found (are you missing a using directive or an assembly reference?) (CS0246) 

2.Error CS0246: The type or namespace name 'Shell' could not be found (are you missing a using directive or an assembly reference?) (CS0246)

3.Error CS0246: The type or namespace name 'ContentPage' could not be found (are you missing a using directive or an assembly reference?) (CS0246)

4.Error CS0246: The type or namespace name 'MauiApp' could not be found (are you missing a using directive or an assembly reference?) (CS0246)

Device for development: iMac 2020 M1
IDE: Visual Studio Mac 17.6.14(Build 413)

### Steps to Reproduce

1. Create new Maui App
2. Run without adding bundle ID -> success
3. Add bundle ID and save
4. Build and clean project
5. Run Project

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.5

**Comment by jfversluis** [comment]
What do you mean with Bundle ID? I don't understand what you added exactly.

Can you elaborate a bit more on the exact steps that you have taken with the exact values that you put in somewhere? Also a [reproduction](https://github.com/dotnet/maui/blob/main/.github/repro.md) is always super helpful.

Thanks!

**Comment by raselldev** [comment]
> What do you mean with Bundle ID? I don't understand what you added exactly.
> 
> Can you elaborate a bit more on the exact steps that you have taken with the exact values that you put in somewhere? Also a [reproduction](https://github.com/dotnet/maui/blob/main/.github/repro.md) is always super helpful.
> 
> Thanks!

Bundle ID is unique indentifier for each apps. 
This problem just fixed by update dotnet workload and using VSCode for development.

But Visual Studio Mac cannot use again for long term production?

**Comment by jfversluis** [comment]
Ah ok! Glad you figured it out.

Yes, unfortunately official support for Visual Studio for Mac has stopped in August. So if it still works for what you are doing, thats great! But other things might stop working over time and will not be fixed any more.

The recommended way forward is using VS Code or use the remote build agent connected to Visual Studio on Windows.
