### ISSUE TITLE
[WinUI] Command on TableView only invokes once.

### ISSUE THREAD

**Issue by mthanson8333** [dotnet/maui#25037]
### Description

Downloaded sample code from https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CollectionViewDemos.  Tried to run CollectionView sample code under Windows emulator and the menu on the MainPage did not work as expected.  Under windows when the app starts I click a menu item and are taken to the proper page.  When I return to menu and click on another menu item, nothing happens.  This happens under Windows emulator.  On Android app works as expected.  Not building for Apple.  I checked community and the closes article I found https://github.com/dotnet/maui/issues/2003 did not answer my question.

### Steps to Reproduce

1.  Download source code from https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CollectionViewDemos. 
2. Compile and run code under Windows emulator.
3. Click on a menu item.  You will be taken to the proper page.
4. Return to menu and click on other menu items.  Nothing happens

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Views/CollectionViewDemos

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 version 22631.4249

### Did you find any workaround?

Yes. MainPage.Xaml
```csharp
<ListView ItemsSource="{x:Static local:PageDataViewModel.All}"
              ItemSelected="OnListViewItemSelected"
              HasUnevenRows="True">
		<!-- Allow rows to adjust height based on content -->
		<ListView.ItemTemplate>
			<DataTemplate>
				<ViewCell>
					<Frame Margin="0,0,0,10" Padding="0" HasShadow="False" BorderColor="Transparent">
						<StackLayout>
							<Label Text="{Binding Title}" FontSize="Medium" VerticalOptions="Start" />
							<Label Text="{Binding Description}" FontSize="Small" TextColor="Gray" LineBreakMode="WordWrap" VerticalOptions="Start" />
						</StackLayout>
					</Frame>
				</ViewCell>
			</DataTemplate>
		</ListView.ItemTemplate>
	</ListView>
```
MainPage.cs:
```csharp  
private async void OnListViewItemSelected(object sender, SelectedItemChangedEventArgs args)
        {
            (sender as ListView).SelectedItem = null;

            if (args.SelectedItem != null)
            {
                PageDataViewModel pageData = args.SelectedItem as PageDataViewModel;
                Page page = (Page)Activator.CreateInstance(pageData.Type);
                await Navigation.PushAsync(page);
            }
        }
```

PageDataViewModel.cs
```csharp
public class PageDataViewModel
    {
        public PageDataViewModel(Type type, string title, string description)
        {
            Type = type;
            Title = title;
            Description = description;
        }

        public Type Type { private set; get; }

        public string Title { private set; get; }

        public string Description { private set; get; }

        static PageDataViewModel()
        {
            All = new List<PageDataViewModel>
            {
                new PageDataViewModel(typeof(VerticalListPage), "Vertical List",
                                      "DataTemplate"),
            };
        }

        public static IList<PageDataViewModel> All { private set; get; }
    }
```

**Comment by drasticactions** [comment]
I can reproduce this.

https://github.com/dotnet/maui-samples/blob/main/8.0/UserInterface/Views/CollectionViewDemos/CollectionViewDemos/Views/MainPage.xaml#L6-L213

That menu is a `TableView`, and apparently once you invoke _one_ event, you can't invoke another one, even if it's a different command. I don't think the issue you linked is related to this though: The construction of that view is different.

**Comment by mthanson8333** [comment]
Closing issue since question is asked at https://github.com/dotnet/maui/issues/21112

**Comment by umeshkamble** [comment]
@mthanson8333 
I have tried below code its works.
Return to menu and click on other menu items. **Its working**
`<TableView x:Name="tableList" Intent="Menu">
     <TableRoot>
            <TableSection Title="Layout">
             <TextCell
                 Command="{Binding Path=BindingContext.NavigateCommand, Source={x:Reference tableList}}"
                 CommandParameter="{x:Type views:VerticalListTextPage}"
                 Detail="Text"
                 Text="Vertical list" />
            </TableSection>
     </TableRoot>
 </TableView>`
