### ISSUE TITLE
How does the new Maui Blazor Template can run on Windows?

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/maui#2506]
I cant find WinUI in the new Maui Blazor App template. target frameworks are only `net6.0-ios;net6.0-android;net6.0-maccatalyst`

**Comment by Snsaiu** [comment]
me too

**Comment by aledevbr** [comment]
me too... not work on WinUI

**Comment by Lorymi** [comment]
Same for Maui App template.

**Comment by tharlab** [comment]
blazor + maui is game chager

**Comment by Eilon** [comment]
Hi @HeroinGyrl and others, you can double-click on the project and edit the CSPROJ to add support for WinUI. You can read more about this in the installation section of the docs: https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation
