### ISSUE TITLE
Tab bar showing at the top instead of bottom in ios 18

### ISSUE THREAD

**Issue by kiranbasvaraj** [dotnet/maui#25065]
![Simulator Screenshot - iPad (10th generation) - 2024-10-03 at 12 40 26](https://github.com/user-attachments/assets/87860a1f-2f36-4c41-b515-db0d1b1ad6e4)

![Simulator Screenshot - iPad (10th generation) - 2024-10-03 at 12 38 50](https://github.com/user-attachments/assets/e482a70a-b792-4169-9af1-303c78a2c1d3)

### Description

The tab bar is showing at the top when we create a tab bar using a shell in MAUI.
but the expected behaviour is to show at bottom

### Steps to Reproduce

1. Create a new project using the shell in Maui 
2.Use tab bar in app shell 
3.Observe it show at the top instead of bottom

### Link to public reproduction project repository

https://github.com/kiranbasvaraj/MAU_Tabbar.git

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 18

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
This is new behavior in iOS 18 and Apple does not offer a way to revert to the old way without building your own control. So... Not a bug, sorry!

**Comment by jfversluis** [comment]
Also additional work for some minor glitches in .NET MAUI can be tracked here: https://github.com/dotnet/maui/issues/23380
