### ISSUE TITLE
DeploymentManagerCS is back - app can't start

### ISSUE THREAD

**Issue by lostmsu** [dotnet/maui#25062]
### Description

Exception thrown: 'System.TypeInitializationException' in Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll
The type initializer for 'WinRT.ActivationFactory`1' threw an exception.

 
```
 at WinRT.ActivationFactory`1.ActivateInstance[I]()
 at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
 at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options()
  in C:\Users\XXXX\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\include\DeploymentManagerAutoInitializer.cs:line 44
```

### Steps to Reproduce

Launch a MAUI app on Windows 26100.1742
I am launching from Visual Studio 17.11.4

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

26100.1742

### Did you find any workaround?

No. Running VS as admin does not help.

### Relevant log output

```shell
get-appxpackage micro*win*app*run* -allusers | Select-Object -Property PackageFullName

PackageFullName
---------------
Microsoft.WindowsAppRuntime.1.3_3000.934.1904.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.5_5001.214.1843.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.5_5001.214.1843.0_x86__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.CBS_5001.184.1607.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.3_3000.934.1904.0_x86__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.4_4000.1309.2056.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.4_4000.1309.2056.0_x86__8wekyb3d8bbwe
MicrosoftCorporationII.WinAppRuntime.Main.1.5_5001.214.1843.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.6_6000.266.2241.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.6_6000.266.2241.0_x86__8wekyb3d8bbwe
MicrosoftCorporationII.WinAppRuntime.Singleton_6000.266.2241.0_x64__8wekyb3d8bbwe
```
```

**Comment by jfversluis** [comment]
You say "is back", which indicates you have seen this before? Is there an issue for it, where is the previous discussion? What did you do then but didn't work this time?

Also is there a reproduction for this? Does this happen only on your project or also on a new blank .NET MAUI project?

**Comment by lostmsu** [comment]
The stack trace and exception are identical to https://github.com/dotnet/maui/issues/16652 , except I am not launching from command line, but from Visual Studio.

Some extra info that might help:

On the machine where I have this problem, I don't have a `Properties\launchSettings.json` file, and the toolbar looks like this:

![image](https://github.com/user-attachments/assets/14837954-924d-4b9a-a12f-49118b5dbec1)

On the older machine it looks like this, and you can also see what launchSettings.json looks like:
![image](https://github.com/user-attachments/assets/3e7158dd-51f7-4403-8d69-fb859c453105)

It looks like Visual Studio is not picking up the idea that the project must be launched as MSIX.

BTW, `launchSettings.json` file was not committed because it was listed in one of the (maybe older) .gitignore files as
```
# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/
**/Properties/launchSettings.json
```

And I see logic in that: launch configurations are generally specific to dev machine.

**Comment by jaosnz-rep** [comment]
I created a new blank .NET MAUI project on the latest VS 17.11.5(Windows 26100.1742) to verify this issue, but 8.0.91 didn't reproduce. 
Could you provide your project so that we can investigate it further?
