### ISSUE TITLE
Memory leak in .Net 8 using Entity Framework and Sqllite

### ISSUE THREAD

**Issue by SebastianKleu** [dotnet/maui#25087]
### Description

Hi,

We have been running our .Net Maui Android app on .Net 7 for some time now and upgraded to .Net 8.

After the upgrade, we realized that the app crashes after a few hours of use.

I have narrowed down the culprit to EF call on Sqllite. I am able to induce this problem by just reading from a table. See below:
```
private async Task TesterLoop()
    {
        while (true)
        {
            var testDataMessages = await GetTestDataMessages(new CancellationToken());
        }
    }

private async Task<List<TestData>> GetTestDataMessages(CancellationToken cancellationToken)
    {
	await using var dbContext = await _dbContextFactory.CreateDbContextAsync(cancellationToken);

        List<TestData> returnResult = await dbContext.TestData.AsNoTracking()
            .ToListAsync(cancellationToken);

        await dbContext.DisposeAsync().ConfigureAwait(false);

        return returnResult;
 }
```
Please see attached zip of test application where you can clearly see the memory rise in .Net 8 and not using .Net 7.

See below memory usage of .Net 7 app after 10 min.
![image](https://github.com/user-attachments/assets/c5fb02b5-8e45-44af-8d82-73a0f47e5e89)

See below memory usage of .Net 8 app after 10 min.
![image](https://github.com/user-attachments/assets/cf59a18b-faa1-4bd0-bc51-58635b9475c9)

See below test application.
[TestMaui.zip](https://github.com/user-attachments/files/17260077/TestMaui.zip)

### Steps to Reproduce

1. Run Test.Maui.7 on Android device
2. Notice memory stays constant
3. Run Test.Maui.8 on Android device
4. Notice native memory climb fast

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
From what I'm reading this issue should be opened with Entity Framework? Why do you think this is something in the .NET MAUI SDK?

**Comment by drasticactions** [comment]
@SebastianKleu A good way to test that would be to create a .NET Android project that doesn't use the MAUI UI project `dotnet new android` and try running the code there, without influence of the UI framework. 

That said, I would be _very_ surprised if the UI framework would affect this at all. I would put my bets on EFCore itself or the runtime.

**Comment by SebastianKleu** [comment]
I created apps that doesn't use the MAUI UI and the memory leak still occurs on Dotnet 8 Android projects.
I will close the bug here on Maui.
For reference, I created a bug on EF Core: https://github.com/dotnet/efcore/issues/34836
