### ISSUE TITLE
Getting 403 when trying to download MAUI nightly

### ISSUE THREAD

**Issue by JohnTraDolta** [dotnet/maui#25112]
### Description

When i add the package in my csproj eg
``` csharp
...
<MauiVersion>8.0.99-ci.net8.24505.3</MauiVersion>
...
<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
...
```
and run restore i get 403 from nuget.
log entry:
```
Failed to download package 'Microsoft.Maui.Controls.Core.8.0.99-ci.net8.24505.3' from 'https://pkgs.dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_packaging/42c1603f-3d61-4146-8020-ec5b7b392084/nuget/v3/flat2/microsoft.maui.controls.core/8.0.99-ci.net8.24505.3/microsoft.maui.controls.core.8.0.99-ci.net8.24505.3.nupkg'.
Response status code does not indicate success: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.).
```

When i go to https://dev.azure.com/xamarin/public/_artifacts/feed/maui-nightly and try to download the package manually i get the same error. 

Do i need to be authenticated or do I do anything wrong here?

I followed the guide from here: [maui nightly](https://github.com/dotnet/maui/wiki/Nightly-Builds)

I got it to work with 8.0.99-ci.net8.24504.1, but initially had the same problems. I cant remember what i did to get it to work

Thanks in advance

### Steps to Reproduce

1. Add the nightly nuget feed 
2. Update the maui packages to 8.0.99-ci.net8.24505.3
3. Restore nuget packages 

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.91 SR9.1

### Affected platforms

iOS, Android

### Did you find any workaround?

No

**Comment by jaosnz-rep** [comment]
The 403 issue cannot be reproduced on the latest 17.12.0 Preview 2.1(8.0.91 & 8.0.99-ci.net8.24505.3 & 8.0.99-ci.net8.24508.1).

**Comment by JohnTraDolta** [comment]
When i run "dotnet restore --interactive" in the terminal i get this prompt.
```
[CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/xamarin/public/_packaging/maui-nightly/nuget/v3/index.json
      [CredentialProvider]ATTENTION: User interaction required.

      **********************************************************************

      To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ******* to authenticate.

      **********************************************************************
```
When i follow the link and enter the code i get this message 


Pick an account
You will be signed in to Azure Artifacts on a remote device or service. Select Back if you aren’t trying to sign in to this application on a remote device or service.
Selected user account does not exist in tenant 'Microsoft' and cannot access the application 'd5a56ea4-7369-46b8-a538-c370805301bf' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account.

I dont get why i need to login in the first place because the packages should be public?

**Comment by JohnTraDolta** [comment]
And also, im on a mac so can not use visual studio 17.12.0 Preview 2.1

**Comment by mattleibow** [comment]
I wonder if the IT peoples did something bac in Oct... That is a public feed so should not require auth at all.

Can you try again as it seems to work now.

**Comment by jfversluis** [comment]
Assuming this is resolved by now, thanks!
