### ISSUE TITLE
NullReferenceException when setting BarBackgroundColor for a NavigationPage

### ISSUE THREAD

**Issue by MitchBomcanhao** [dotnet/maui#25114]
### Description

From 8.0.90 (as far as I can tell) I get NRE when attempting to set a NavigationPage's BarBackgroundColor.
I'm not sure of how this is failing (ie I can't share a repro project at the moment), but it can't hurt to get the ball rolling on this topic, perhaps others have had similar issues?

this is running on a `Flyout` page - its detail is set to a navigation page that encapsulates a content page.
when the content page triggers `OnAppearing` we set the BarBackgroundColor for the navigation page.

however, when it gets to the `NavigationPageToolbar.ApplyChanges` method, it blows up, as it seemingly receives a null navigationPage object

![image](https://github.com/user-attachments/assets/b0eda698-0d91-4bf9-9265-fe18447b38a8)

and that null object comes from the call from `NavigationPageToolbar.OnPagePropertyChanged`
![image](https://github.com/user-attachments/assets/167d3bc8-923a-4b40-ab62-db903b4af400)

Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.NavigationPageToolbar.ApplyChanges(Microsoft.Maui.Controls.NavigationPage navigationPage)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.NavigationPageToolbar.OnPagePropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.MenuItemTracker<System.__Canon>.OnPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs propertyChangedEventArgs)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(string propertyName)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.OnPropertyChanged(string propertyName)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.BindableObject.SetValueActual(Microsoft.Maui.Controls.BindableProperty property, Microsoft.Maui.Controls.BindableObject.BindablePropertyContext context, object value, bool currentlyApplying, Microsoft.Maui.Controls.Internals.SetValueFlags attributes, Microsoft.Maui.Controls.SetterSpecificity specificity, bool silent)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.BindableObject.SetValueCore(Microsoft.Maui.Controls.BindableProperty property, object value, Microsoft.Maui.Controls.Internals.SetValueFlags attributes, Microsoft.Maui.Controls.BindableObject.SetValuePrivateFlags privateAttributes, Microsoft.Maui.Controls.SetterSpecificity specificity)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.BindableObject.SetValue(Microsoft.Maui.Controls.BindableProperty property, object value)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.NavigationPage.BarBackgroundColor.set(Microsoft.Maui.Graphics.Color value)	Unknown

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

Windows, I was *not* able test on other platforms

**Comment by MitchBomcanhao** [comment]
this NavigationPageToolbar class was changed a few weeks ago and the OnPagePropertyChanged method was modified - this is likely where the issue is coming from - check commit https://github.com/dotnet/maui/commit/fa9e3702f4006ffabad6381cb7eadfc504f28de8


the original OnPropertyChanged method was removed
![image](https://github.com/user-attachments/assets/7f0b3697-a167-401c-9a4d-28db635f9b13)

the OnPagePropertyChanged method was changed to include most of the code that was removed from the other method
![image](https://github.com/user-attachments/assets/84f2a0f1-f9a2-4077-b715-67e810815537)

this is clearly doing things slightly differently, which is breaking things.

**Comment by markmccaigue** [comment]
We've also hit what I believe to be the same issue.

I can confirm that this also happens on both iOS and Android, and that it is a regression introduced in 8.0.90.

[I have made a small reproduction, here, which demonstrates the issue](https://github.com/markmccaigue/MAUI8090BarBackgroundColorCrash/tree/main)

When running this project, the app will crash on launch. The expected behaviour, and the behaviour observed on previous MAUI releases, is that no crash occurs, and the color is correctly updated.

Our production application exhibiting this issue is more complex than the reproduction sample, and makes heavy use of dynamic resources for colors. The impact there is that the main section of our app is inaccessible, on Android the app hangs completely, on iOS it hangs, but will crash after user interaction with this same stack trace. I'm not currently aware of any viable workaround, so it's a pressing issue for us.

Thanks for your consideration. cc @MitchBomcanhao @samhouts

**Comment by samhouts** [comment]
@kubaflo This seems related to some changes you made recently. Would you like to take a look? Thank you!!!

**Comment by kubaflo** [comment]
@samhouts @markmccaigue @MitchBomcanhao the fix: https://github.com/dotnet/maui/pull/25197

**Comment by markmccaigue** [comment]
Thanks so much for the quick PR!

Just for our planning purposes, in your opinion is it likely that this fix for the regression would make it's way into a service release in the near future? Thanks again @samhouts @kubaflo

**Comment by jaosnz-rep** [comment]
I can repro this issue at Windows platform on the latest 17.12 Preview 2.1(8.0.90 & 8.0.91), but it works fine on 8.0.82.
