### ISSUE TITLE
[Android] Java.Lang.IllegalArgumentException: 'No view found for id 0x7f0900fd (com.twe.elon:id/labeled) for fragment NavigationRootManager_ElementBasedFragment{e99ccf3} (d735450b-8b7e-4e10-87d0-3b9a8251e4b3 id=0x7f0900fd)' #24774

### ISSUE THREAD

**Issue by eli191** [dotnet/maui#25113]
### Description

I ran across this bug today. My code didn't change and I don't know how to fix it.
I am using MAUI 8.0.82.

[Android] Java.Lang.IllegalArgumentException: 'No view found for id 0x7f0900fd (com.twe.elon:id/labeled) for fragment NavigationRootManager_ElementBasedFragment{e99ccf3} (d735450b-8b7e-4e10-87d0-3b9a8251e4b3 id=0x7f0900fd)' #24774

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

Android

**Comment by ninachen03** [comment]
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
