### ISSUE TITLE
RC2: XC0022 Excessive and incorrect binding warnings

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#25138]
### Description

I have migrated an application from RC 1 and RC 2 and encountered a staggering amount of warnings. Nearly every binding that is contained in a `DataTemplate` or `Path` throws a XC0022 warning.

For example, the following throws warnings that were not present in RC 1

Static bindings
```
<customviews:SelectableLabel
    Grid.Row="0"
    Grid.Column="1"
    Text="{Binding Source={Static Constants.MyConstant, x:DataType=Constants}, Path=.}" />
 ```
 
 Multi bindings
 ```
 <VerticalStackLayout.IsVisible>
    <MultiBinding Converter="{StaticResource AllTrueConverter}">
        <Binding Path="MyConnectionServer.MyThing" /> <!-- my connection server is a property on my currently binded type -->
        <Binding
            Converter="{toolkit:IsNotEqualConverter}"
            ConverterParameter="Disconnected"
            Path="Version.Version" />
    </MultiBinding>
```
 AppShell itemtemplate
 
 ```
     <Shell.ItemTemplate>
        <DataTemplate>
            <Grid Padding="{OnPlatform MacCatalyst=5}" ColumnDefinitions="auto, *">
                <Image
                    Margin="5"
                    HeightRequest="{OnPlatform WinUI=35,
                                               MacCatalyst=45,
                                               Android=35,
                                               iOS=35}"
                    Source="{Binding FlyoutIcon}" />
                <Label
                    Grid.Column="1"
                    FontAttributes="Bold"
                    FontSize="15"
                    Text="{Binding Title}"
                    VerticalTextAlignment="Center" />
            </Grid>
        </DataTemplate>
    </Shell.ItemTemplate>
```

datatriggers

```
<DataTrigger
    Binding="{Binding IsDoingAction}"
    TargetType="Button"
    Value="True">
    <Setter Property="Text" Value="RUNNING" />
    <Setter Property="BackgroundColor" Value="Green" />
</DataTrigger>
```

### Steps to Reproduce

Migrate any decently complex application to .NET 9 RC 2. (why is WeatherTwentyOne not part of the mono repo and constantly used as a test?)

### Link to public reproduction project repository

NA

### Version with bug

9.0.0-rc.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-rc.1

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

.NET MAUI RC 2

### Did you find any workaround?

It doesn't actually affect any code.

**Comment by daltzctr** [comment]
I am investigating. I believe most of these warnings are legitimate, it was just really strange that they were not present in RC 1.

**Comment by daltzctr** [comment]
Edit 1: `DataTrigger` does seem to not be applying it's parent datatype.

**Comment by simonrozsival** [comment]
@daltzctr if you do not wish to compile bindings in your XAML, you can disable this warning code by adding this to your project file:
```xml
<NoWarn>$(NoWarn);XC0022</NoWarn>
```

> `{Binding Source={Static Constants.MyConstant, x:DataType=Constants}, Path=.}`

Here it looks like a typo - the `x:DataType` is on `{Static}`, it should be on `Binding`. I am also confused why you need the `{Binding}` in this case at all. Shouldn't you use the value of `{Static ...}` directly?
```
Text="{Static Constants.MyConstant}"
```

For more information about compiled bindings and how to use `x:DataType`, you can read the documentation: https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/compiled-bindings?view=net-maui-9.0

---

What seems weird is that you say you weren't getting these warnings in .NET 9 RC1 but they started appearing after updating to RC2. I'm not aware of any change that could change when we report this specific warning, but I will look into this tomorrow in more depth.

**Comment by daltzctr** [comment]
I do wish to compile bindings, but I think certain controls are not obeying their parent datatypes which is resulting in annoying warnings. I am updating my previous tracker as I go through my RC 2 migration (from RC 1)

**Comment by simonrozsival** [comment]
> Edit 1: DataTrigger does seem to not be applying it's parent datatype nor does VS warn on it
> Edit 2: MultiBindings does not seem to be applying it's parent datatype nor does VS warn on it

@daltzctr can you please share an example from your code where you define the x:DataType in parent scope and it is not applied so I can try to reproduce it?

**Comment by StephaneDelcroix** [comment]
those warnings were not shown in net8.0, but are in net9.0. that's not an issue. but if you get warnings where you shouldn't, please report.

as @simonrozsival said, you can hide then with NoWarn, or have them in WarningsNotAsErrors if you like to treat all your warnings as errors

**Comment by daltzctr** [comment]
See the following. It warns on the multibindings @simonrozsival 

```
<CollectionView
    Grid.Row="1"
    ItemsSource="{Binding MyQueeu}"
    SelectedItem="{Binding SelectedItem}"
    SelectionMode="Single">
    <CollectionView.ItemTemplate>
        <DataTemplate x:DataType="modal:MyAttributes">
            <Grid
                Margin="10,2,10,2"
                ColumnDefinitions="*, 0.5*, auto"
                HeightRequest="35">
                <Label
                    FontSize="13"
                    LineBreakMode="TailTruncation"
                    Opacity="1.0"
                    Text="{Binding FilePath}"
                    ToolTipProperties.Text="{Binding FilePath}"
                    VerticalTextAlignment="Center">
                    <Label.Triggers>
                        <DataTrigger
                            Binding="{Binding DoingAction, x:DataType=modal:MyAttributes}"
                            TargetType="Label"
                            Value="True">
                            <Setter Property="Opacity" Value="0.7" />
                        </DataTrigger>
                    </Label.Triggers>
                    <FlyoutBase.ContextFlyout>
                        <MenuFlyout>
                            <MenuFlyoutItem
                                Command="{Binding Source={Static vmroot:MySingleton.Instance}, Path=CopyToClipboardCommand, x:DataType=vmroot:GlobalViewModel}"
                                CommandParameter="{Binding FilePath}"
                                Text="Copy to clipboard" />
                        </MenuFlyout>
                    </FlyoutBase.ContextFlyout>
                </Label>
                <Button
                    Grid.Column="1"
                    Command="{Binding Source={x:Reference root}, Path=BindingContext.DoActionCommand, x:DataType={x:Null}}"
                    CommandParameter="{Binding .}"
                    HeightRequest="28"
                    MinimumHeightRequest="0"
                    Text="Do Action"
                    VerticalOptions="Center"
                    WidthRequest="100">
                    <Button.IsVisible>
                        <MultiBinding Converter="{customconverters:BooleanAndConverter}">
                            <Binding
                                Converter="{toolkit:InvertedBoolConverter}"
                                Path="FlagOne" />
                            <Binding
                                Converter="{toolkit:InvertedBoolConverter}"
                                Path="FlagTwo" />
                            <Binding
                                Converter="{toolkit:InvertedBoolConverter}"
                                Path="FlagThree" />
                        </MultiBinding>
                    </Button.IsVisible>
                </Button>
            </Grid>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

@StephaneDelcroix this is an app that migated from .NET 9 RC 1 to .NET 9 RC 2. I did not have these issues in RC 1, presumably due to https://github.com/dotnet/maui/pull/24513

**Comment by daltzctr** [comment]
To be clear, I think the root of this issue is that some bindings aren't applying their parent datatype.

**Comment by simonrozsival** [comment]
@daltzctr right, https://github.com/dotnet/maui/pull/24513 could be related. I have to leave now but I will follow-up on this tomorrow. It would be very helpful if you could create a sample repro project based on `dotnet new maui` that would show the warnings you think should be annotated correctly but aren't and make it a public repo on github.

**Comment by daltzctr** [comment]
I've finished my migration. I am going to open up a new issue that is more clear.
