### ISSUE TITLE
Cannot Pair with Mac

### ISSUE THREAD

**Issue by BharatRamH** [dotnet/maui#25131]
### Description

I have a remote Mac machine with an Apple M1 chip, running macOS Sonoma 14.5, and Visual Studio 2022 for Mac (v17.6.12). I have configured it following the steps from the [Pair to Mac for iOS development - .NET MAUI | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac?view=net-maui-8.0). However, I am unable to pair the Mac with my Windows machine when working on a Blazor MAUI App in Visual Studio 2022 (v17.11.4) using .NET SDK v8.0.400.

### Steps to Reproduce

1.	Click: Tools -> iOS -> Pair with Mac
2.	Click: Add Mac...
3.	Enter the Mac's IP address
4.	Click: Add

#### Expected Behavior

The Mac pairs successfully with the Windows machine.

#### Actual Behavior

An error message stating "Couldn't resolve Mac '#####'" appears.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Visual Studio 2022 (v17.11.4) using .NET SDK v8.0.400

**Comment by drasticactions** [comment]
@BharatRamH Pair to Mac tooling is owned and maintained by Visual Studio and not this team. If you file your issue through VSFeedback as the note above directs, they can help you debug your issue.

**Comment by BharatRamH** [comment]
Thank you @drasticactions, I have logged an [issue](https://developercommunity.visualstudio.com/t/Cannot-Pair-with-Mac-for-Blazor-MAUI-IOS/10763695) as per the suggestion.
