### ISSUE TITLE
RC2: Triggers and MultiBindings do not inherit their parent datatype

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#25141]
### Description

Triggers such as `DataTrigger` and `Multibindings` do not inherit their parent datatype. This is likely due to https://github.com/dotnet/maui/pull/24513. This triggers an XC0022 unless explicitly declaring datatype in the binding itself.

These bindings did not trigger any warnings in .NET 9 RC 1

### Steps to Reproduce

```
<MultiBinding Mode="TwoWay" StringFormat="{}Version ({0})">
    <Binding Path="Version.Version"/>
</MultiBinding>
```

or 

```
<DataTrigger
    Binding="{Binding MyObject.IsDoingAction}"
    TargetType="Button"
    Value="True">
    <Setter Property="Text" Value="DOING ACTION" />
    <Setter Property="BackgroundColor" Value="Green" />
</DataTrigger>
```

triggers an XC0022

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Did you find any workaround?

Explicitly declare the `DataType` in the bindings inside of `MultiBinding` or `DataTrigger`

**Comment by ninachen03** [comment]
I can repro this issue at Windows platform on the latest 17.12.0 Preview 3(9.0.0-rc.2.24503.2).

![Image](https://github.com/user-attachments/assets/8dabaf33-d4ba-43ea-b8a4-7ca9b339dedb)

**Comment by PureWeen** [comment]
Closed by
https://github.com/dotnet/maui/pull/25152
