### ISSUE TITLE
iOS "dotnet" exited with code 150. (MSB6006)

### ISSUE THREAD

**Issue by pulmuone** [dotnet/maui#25165]
### Description

Error Message : 

/Users/gwise/.nuget/packages/microsoft.net.illink.tasks/8.0.10/build/Microsoft.NET.ILLink.targets(5,5): Error MSB6006: "dotnet" exited with code 150. (MSB6006) (ExpiryDateScanner.iOS)
/Users/gwise/.nuget/packages/microsoft.net.illink.tasks/8.0.10/build/Microsoft.NET.ILLink.targets(5,5): Error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. (NETSDK1144) (ExpiryDateScanner.iOS)

### Steps to Reproduce

iOS For Mac VS2022
Microsoft.NET.ILLink.Tasks : 8.0.10 -> Error
Microsoft.NET.ILLink.Tasks : 8.0.8 -> OK

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.91 SR9.1

### Affected platforms

iOS

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-macios#21409
