### ISSUE TITLE
SKStoreReviewController is deprecated in iOS 18, and replacement is not accesible in MAUI.

### ISSUE THREAD

**Issue by MerSpyro** [dotnet/maui#25169]
### Description

Hello,

with iOS 18 it seems that Apple deprecated SKStoreReviewController. Now every plugin and call made from SKStoreReviewController are not working. There is a replacement with AppStore.requestReview(in: scene). But from MAUI it is inaccessible. 

https://developer.apple.com/documentation/storekit/appstore/3954432-requestreview/

### Steps to Reproduce

Create an application
on ios18 invoke
```
if (UIApplication
                            .SharedApplication?
                            .ConnectedScenes?
                            .ToArray<UIScene>()?
                            .FirstOrDefault(x => x.ActivationState == UISceneActivationState.ForegroundActive) is UIWindowScene windowScene)
                    {
                        SKStoreReviewController.RequestReview(windowScene);
                        return Task.CompletedTask;
                    }
```
see that application hangs.

same code on iOS 17.5 works, create a review popup or just passes quietly.

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18+

### Did you find any workaround?

No

**Comment by MerSpyro** [comment]
It seems like application downloaded from AppCenter produces popup still, so faulty behaviour is only present on the development machines. Still having a replacement when Apple finally removes the API would be nice.

**Comment by PureWeen** [comment]
Moved to: https://github.com/xamarin/xamarin-macios/issues/21410
