### ISSUE TITLE
IOS Xcode 16 Strip exited with code 139 error

### ISSUE THREAD

**Issue by TheSundayDev** [dotnet/maui#25162]
### Description

Last version of VS 17.11.5 requires Xcode 16. After Xcode update now I have this error when i compile: Strip exited with code 139
thanks

### Steps to Reproduce

Build IOS app

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

iOS

### Affected platform versions

ios

**Comment by gwise-vision** [comment]
same issue.
This error makes the app too big. When will it be fixed?

**Comment by jfversluis** [comment]
Duplicate of https://github.com/xamarin/xamarin-macios/issues/19157
