### ISSUE TITLE
Android: Minimum and MaximumHeightRequest are not respected on controls when HeightRequest is also set (same for Width)

### ISSUE THREAD

**Issue by spadapet** [dotnet/maui#25163]
### Description

Layout for controls (`Button`, `Entry`, etc) on Android does not take `MinimumHeightRequest` into account when `HeightRequest` is also set. Maximum and Width have the same issue. Removing `HeightRequest` allows the min/max to work, but when `HeightRequest` is set, it is always used for the final size.

This doesn't apply to Layouts such as `VerticalStackPanel` because they don't go through the same layout code that has the bug:
* https://github.com/dotnet/maui/blob/7f56f6c65a4b937b68983f7f7f8efa42f9f85fc0/src/Core/src/Platform/Android/ContextExtensions.cs#L381-L390

### Steps to Reproduce

1. New MAUI app
2. Replace contents of main XAML page with:
    * `<Button HeightRequest="100" MinimumHeightRequest="200" MaximumHeightRequest="300" Text="{Binding Height, Source={RelativeSource Self}}" />`
3. Run on Android (Windows and iOS will not have the bug)

**RESULT:**
The button's height is 100

**EXPECT:**
Button's height is 200

Same for `HeightRequest="300"`, it should be clamped to 200, but it isn't.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Removing the HeightRequest can work around the issue, but that shouldn't be needed.

**Comment by rubendmribeiro** [comment]
Please fix this issue asap :(
