### ISSUE TITLE
CollectionView ItemSizingStrategy:"MeasureFirstItem" renders labels  incorrectly (.net8, .net9)

### ISSUE THREAD

**Issue by bcaceiro** [dotnet/maui#25191]
### Description

When setting the MeasureFirstItem  property in a CollectionView, this results in an incorrect render of the CV. The first item of the list gets rendered corectly most of the times, however the rest of the list, gets the text cut in the labels. (This happens in 8.0.91 and also in .net9 RC2)

Without ItemSizingStrategy:
![Imgur Image](https://i.imgur.com/5xb0duT.png)

With MeasureFirstItem:
![Imgur Image](https://i.imgur.com/pw7fiuM.png)

Since there are still issues with the CV rendering performance, would figure this setting is a must have for templates that have the same sizing ( I guess the majority of the CVs)

The MeasureFirstItem sizing strategy will result in increased performance when used in situations where the item size is intended to be uniform across all items.

The code can be found here: https://github.com/bcaceiro/net9-repros/tree/main/CompiledBindings/CompiledBindingsSample

### Steps to Reproduce

1. Clone https://github.com/bcaceiro/net9-repros/tree/main/CompiledBindings/CompiledBindingsSample
2. Run in Android (haven't tested in other platforms)
3. Change the ItemSizingStrategy to "MeasureFirstItem" or to "MeasureAllItems" and see the differences

### Link to public reproduction project repository

https://github.com/bcaceiro/net9-repros/tree/main/CompiledBindings/CompiledBindingsSample

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 14

### Did you find any workaround?

Not use the ItemSizingStrategy (which is not the desired result)

**Comment by Alex-111** [comment]
There were so many changes regarding measurement in the past so my question is:

Is there really a performance benefit in the current version when choosing the MeasureFirstItem option?

On my side some longer time ago scrolling was much better with this parameter. But in the last few versions i hardly can notice any difference when comparing MeasureFirstItem vs. MeasureAllItems

**Comment by bcaceiro** [comment]
Hi @Alex-111 , well in my best guess, there would be advantages, since it is easier to calculate the sizes for 1 cell and apply to the rest, rather than measure all items. Nevertheless, rendering incorrectly is a bigger issue. I am not using MeasureFirstItem, exactly because of the wrong effect, so can't really say the difference

**Comment by Alex-111** [comment]
Well, since measurement code cannot be just shortcutted or skipped,because of e.g this issue and also other layout issues, I wonder if there is really a performance advantage when using MeasureFirstItem?

**Comment by jaosnz-rep** [comment]
I can repro this issue at Android platform on the latest 17.12.0 Preview 2.1(9.0.0-rc.1.24453.9 & 9.0.0-preview.7.24407.4).
