### ISSUE TITLE
[iOS] New CollectionViewHandler2 "swallows" attached properties

### ISSUE THREAD

**Issue by DDHSchmidt** [dotnet/maui#25195]
### Description

I'm using effects with attached properties on the DataTemplates for my CollectionView.
When testing out the new CollectionViewHandler2 from .Net 9 I noticed that the attached properties couldn't be read within the Effect code anymore.

Reverting back to the normal CollectionViewHandler makes the attached properties work as expected.

I'm testing out effects as a workaround to the [inability of CommunityToolkit's TouchBehavior](https://github.com/dotnet/maui/issues/24313), that's why the attached properties are referencing values via RelativeSource.

Not working with CollectionViewHandler2:
![Image](https://github.com/user-attachments/assets/f33cdf52-16d5-44fb-acee-716e24f856f4)

Working with "normal" CollectionViewHandler:
![Image](https://github.com/user-attachments/assets/3aa3cd6c-5e50-4dd8-8d89-da480b6bfec4)

### Steps to Reproduce

1. Check out reproduction project
2. Start on any iOS simulator/device
3. Try clicking on any line within the CollectionView
4. No messages appear
5. Outcomment `AddHandler`-line in MauiProgram.cs
6. Restart project
7. Try clicking on any line within the CollectionView
8. Messages will appear, signaling that the attached propertes worked.

### Link to public reproduction project repository

https://github.com/DDHSchmidt/SourceBindingTest

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.91 SR9.1

### Affected platforms

iOS

### Did you find any workaround?

Don't use new CollectionViewHandler2

**Comment by Zhanglirong-Winnie** [comment]
I can repro it at Windows platform on the latest 17.12.0 Preview 2.1(9.0.0-rc.1.24453.9), but it works fine on 8.0.91.

**Comment by rmarinho** [comment]
I tried to repo this on main and couldn't reproduce , does this seem ok?

https://github.com/dotnet/maui/commit/1b5ce9a85d9ea23d965301fb82723bc56a5f7d1d

**Comment by DDHSchmidt** [comment]
> I tried to repo this on main and couldn't reproduce , does this seem ok?
> 
> [1b5ce9a](https://github.com/dotnet/maui/commit/1b5ce9a85d9ea23d965301fb82723bc56a5f7d1d)

On a superficial glance: Yes.
Have there been some changes in the meantime to make this work?
Does it also work against my test project?
If it is fixed: Will it be included in the official .Net 9 release next week?

**Comment by rmarinho** [comment]
Yeah when i was using the gGA release on your sample it was still a issue, i m confused, i don t see anything on main that fixed that and was not on GA. but i need to double check again.

**Comment by rmarinho** [comment]
I can t repro this on main and if anything I think if anything was happening [this fixed it.](https://github.com/dotnet/maui/commit/b4795133f86c79ef73d9e08a5bc4f277c1813320)
