### ISSUE TITLE
MAUI Create your app - not able to create and facing error XA1018 Specified AndroidManifest file does not exist

### ISSUE THREAD

**Issue by arunvishwa24** [dotnet/maui#25196]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Editor:
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.9.6

Facing below issues:

**Package issue -**
![Image](https://github.com/user-attachments/assets/314c08bf-ddcd-45f0-819a-a2a75ca89318)

**Error List -**
Severity	Code	Description	Project	File	Line	Suppression State
_**Error	XA1018	Specified AndroidManifest file does not exist: C:\Users\Arun\source\repos\MauiAppNewDemo\MauiAppNewDemo\AndroidManifest.xml.	MauiAppNewDemo	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.52\tools\Xamarin.Android.Common.targets	596**_	

**Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1301	Unable to load the service index for source https://api.nuget.org/v3/index.json.	MauiAppNewDemo	C:\Users\Arun\source\repos\MauiAppNewDemo\MauiAppNewDemo\MauiAppNewDemo.csproj	1**	

To fix this I follow this reference https://stackoverflow.com/questions/69630528/androidmanifest-xml-file-doesnt-exist-in-default-maui-project but does not work for me and getting more errors not sure it is package dependency issue or something else.

**Comment by arunvishwa24** [comment]
@samhouts mention issues fixed as explained here https://github.com/dotnet/maui/issues/1211

Facing new issue - 

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(34,27): error 0x80070002: Cannot install or update package com.companyname.mauiappnewdemo_9zz4h110yvjzm because the splash screen image [splashSplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found

I tried to fix this using below refs but does not work for me
https://github.com/microsoft/microsoft-ui-xaml/issues/6378
https://stackoverflow.com/questions/73679622/visual-studio-2022-dep0700-registration-of-the-app-failed-0x80070005

**Comment by MitchBomcanhao** [comment]
you say `Microsoft Visual Studio Professional 2022 (64-bit) - Current - Version 17.9.6`
but that really isn't current? that's quite a few versions behind current (which is 17.11.5).

in any case, my workaround for this (recurring) issue is to clone the repo into a new working folder. it'll stop working after a while, and I'll have to do this again. it is horrible.

**Comment by arunvishwa24** [comment]
Issue resolved -  creating new app and used commands mentioned here https://github.com/dotnet/maui/issues/1211 

Thanks!

**Comment by v-gaolisa** [comment]
Hi @samhouts. Just double confirm with you, is this issue resolved in 17.11.5? Thanks in advance！
