### ISSUE TITLE
[Bug] VS2022 Preview 4 deploys to iOS device but does not debug

### ISSUE THREAD

**Issue by UweReisewitz** [dotnet/maui#2520]
### Description
VS2022 Preview 4 is able to deploy a MAUI app to iOS (iPhone 11 with 14.7.1). The app cann be started on the device but it is not possible to debug it.

Build Log:
Build started...
1>------ Build started: Project: MauiApp1, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>Detected signing identity:
1>  Code Signing Key: "Apple Development: XXXXXXXX"
1>  Provisioning Profile: "VS: WildCard Development" 
1>MauiApp1 -> C:\Users\ur\source\repos\MauiApp1\MauiApp1\bin\Debug\net6.0-ios\ios-arm\MauiApp1.dll
2>------ Deploy started: Project: MauiApp1, Configuration: Debug Any CPU ------
2>Starting deploy 'MauiApp1' into the device 'Uwes iPhone 11'...
2>Deploying 'MauiApp1.app' into the device 'Uwes iPhone 11'...
Xamarin.iOS.Windows.Installer.ApplicationSession Information: 0 : 
Creating application ipa file: C:\Users\ur\AppData\Local\Temp\Xamarin\HotRestart\Signing\MauiApp1.app\out\MauiApp1.ipa
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Uploading file 'C:\Users\ur\AppData\Local\Temp\Xamarin\HotRestart\Signing\MauiApp1.app\out\MauiApp1.ipa' to 'PublicStaging'...
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Validating device directory 'PublicStaging'...
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Creating file 'PublicStaging/com.companyname.MauiApp1' in 'PublicStaging'...
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Writing content to file 'PublicStaging/com.companyname.MauiApp1'...
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Closing file 'PublicStaging/com.companyname.MauiApp1'...
Xamarin.iOS.Windows.Installer.ApplicationSession Information: 0 : 
The application has been installed successfully
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Creating file '/Documents/Installed' in '/Documents'...
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Writing content to file '/Documents/Installed'...
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Closing file '/Documents/Installed'...
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Creating file '/Documents/Flags' in '/Documents'...
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Writing content to file '/Documents/Flags'...
Xamarin.iOS.Windows.FileSystem.FileSession Information: 0 : 
Closing file '/Documents/Flags'...
2>Deploy succeeded. The app 'MauiApp1.app' has been successfully deployed on Uwes iPhone 11.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========

==> Here Visual Studio enables the Start button again.

### Steps to Reproduce

1. Create a new MAUI APP
2. Select iOS Local Device
3. Press Start to start debugging

### Expected Behavior
The app should be deployed to the device and the debugger should start

### Actual Behavior
The app is built and deployed successfully but the debugger doesn't start. 
### Basic Information

- Version with issue: VS 2022 Preview 4; Workload installed with VS installer
- Last known good version: N/A
- IDE:
- Platform Target Frameworks: 
  - iOS:  No MAC, just VS 
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iPhone 11

**Comment by UweReisewitz** [comment]
This does not happen on my second machine. On this machine the debugger starts, XAML Hot Reload is working but I'm unable to modify my code at runtime. It seems that no code changes are sent to my device.

I will reinstall VS 2022 and dotnet on my first machine and verify this.

**Comment by UweReisewitz** [comment]
@yxawpKL I have deinstalled Preview 3, rebooted and installed Preview 4 according to this video: https://www.youtube.com/watch?v=Q0qLiBmbOTI by James Montemagno. 
My iPhone is connected dirctly to the PC, not a MAC. There is no MAC involved. After plugging it in and switching to Platform NET6-IOS it shows up as a target to debug on.

**Comment by UweReisewitz** [comment]
@Prarik I'm sorry I have never tried TestFlight or App Store since the current version is development only. 
I have connected my iPhone to my laptop. When switching to iOS for the first time VS asked for my Apple Developer Account and downloaded the required certificates. After that I was able to deploy to the device without a MAC.

**Comment by jfversluis** [comment]
This is quite some previews ago. I am going to close this one for now. If someone is still running into this with the latest preview bits please open something new with all the details. Thanks!
