### ISSUE TITLE
In VS2022 17.11 Preview 5.0, when creating multi-project solution, the solution file gets duplicated and the progress is shown indefinitely

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#25213]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/In-VS2022-1711-Preview-50-when-creati/10709542)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.11 Preview 4.0]
Have updated to VS2022 17.11 Preview 5.0, and now it creates duplicate solution files physically (refer to the attached screenshot). On previous occasions, this occurred only as a virtual entry in the Recent list in the Start Window.

But now once the Create (Project) action button is clicked, the progress dialog window is open for indefinite.

Even when I click cancel, it does not get dismissed, and not responding at all. The only option is to kill the VS instance in the Task Manager.

To add some context, what I’m trying to create is a multi-project solution, and observed that **this issue happens only for the first time**, and on further attempts the same template works perfectly fine. But once the VS instance is closed and relaunched, this resurfaces.

As observed, the project artifacts are created in the physical folder but the solution file is duplicated and VS is trying to load the wrong solution file so that it is waiting indefinitely because of a race condition. This might help to understand the issue better.

The project creation in Preview 5.0 is completely blocked as creating a dummy project for the first time is not a feasible solution in the long term.

![image.png](https://aka.ms/dc/image?name=Be07d338b7fd04e7687b89bb430ed7007638574342194686365_20240724-214017-image.png&tid=e07d338b7fd04e7687b89bb430ed7007638574342194686365)

---
#### Vijay Anand E G on 7/24/2024, 09:20 AM: 

<p>While submitting the issue, have attached the recordings but not sure how good it is because the screen recorder itself hung!!!</p>
<p>Let me know if it is not helpful.</p>

#### Feedback Bot on 7/24/2024, 06:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vijay Anand E G on 8/13/2024, 01:56 PM: 

<p>I have updated to VS2022 17.12 Preview 1.0 today and see this issue has been addressed in this version.</p>
<p>This issue can be marked as resolved.</p>

**Comment by Zhanglirong-Winnie** [comment]
Can repro this issue on 17.11 Preview 5, But this issue has been verified using  Visual Studio 17.12.0 Preview 2.1. Not repro.
