### ISSUE TITLE
.NET MAUI how to render HTML in Label

### ISSUE THREAD

**Issue by SaraIsabelleLima** [dotnet/maui#25211]
### Description

.NET MAUI To render HTML content in a Label on iOS and Android, I am using the TextType="Html" attribute on the Label element. However, iOS does not render any HTML, while Android only supports bold text. Any ideas on how to fix this issue?"

                            <Label Text="{Binding texto}"
                                         Style="{StaticResource CommonTextStyle}"
                                         x:Name="LabelText"
                                         FontSize="17"
                                         TextType="Html"/>
I want the TextType="Html" to recognize the HTML tags in my text and display them on the screen.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by jaosnz-rep** [comment]
I can repro this issue at Windows platform on the latest 17.12.0 Preview 2.1(9.0.0-rc.2.24503.2 & 9.0.0-rc.1.24453.9).

**Comment by drasticactions** [comment]
Can you please create a repro project that shows the HTML you're trying to render?

**Comment by aherrick** [comment]
basic <UL> and <OL> won't render in NET 9 RC - NET 8 worked fine.

**Comment by jsuarezruiz** [comment]
> basic UL and OL won't render in NET 9 RC - NET 8 worked fine.

Could you attach a small sample where reproduce the issue?
