### ISSUE TITLE
BindingContext is returning null

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#25210]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/BindingContext-is-returning-null/10746990)._

---
Hi, we are migrating from xamarin to MAUI.

Using MVVM pattern since the xamarin version we met this code ( red arrow)

![mvvm.jpg](https://aka.ms/dc/image?name=Be9b72c36f5ee467dbdb533e674664ad3638621801954516027_mvvm.jpg&tid=e9b72c36f5ee467dbdb533e674664ad3638621801954516027)

To pass the bindingcontext and process our logic... 

the big problem is that the variable paginaInizialeViewModel is null when the bindingcontext instruction is processed... and so, calling the viewmodel methods goes in error....

Do MAUI changed this approach? 

thank you very much
Angelo

---
#### Elijah Hilliker on 9/17/2024, 08:42 AM: 

<p>It would be best practice to change your app over to used dependency injection. Hopefully this article helps<br>
<a target='_blank' href="https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/">https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/</a></p>

#### Feedback Bot on 9/17/2024, 06:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by suugbut** [comment]
Reattaching the image.

![Image](https://github.com/user-attachments/assets/bcd1a6ea-446c-406a-905b-7fb885b01225)

**Comment by StephaneDelcroix** [comment]
We can't infer when/how you set the BindingContext (are you using a 3rd party component ?). please provide a small repro project for this
