### ISSUE TITLE
Crash Out

### ISSUE THREAD

**Issue by Thobs-Tricks** [dotnet/maui#25226]
### Description

So the issue is, that the app crashes when I navigate to another page using a button also having deployed the app on a physical device. 

Please watch the attached video as I explain fully what an issue is.

https://github.com/user-attachments/assets/883bd395-a8e9-40a7-af14-0c3ab224a764

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

9.0.0-preview.7.24407.4

### Affected platforms

Android

**Comment by suugbut** [comment]
Please provide a github repo with **minimal** code to illustrate the problem.

**Comment by drasticactions** [comment]
Thank you for the video, but this is not enough information to debug your issue. If you can create a reproducible sample application, we can help isolate your issue.

**Comment by Thobs-Tricks** [comment]
![Image](https://github.com/user-attachments/assets/f9a7c614-0ac5-4a07-9c95-5453efdb248b)


I was able to solve the issue, it seems the usage of  <Label Style="{StaticResource LargeLabel}" Text="{Binding Description}" FontAttributes="Bold"/>
 <Label Style="{StaticResource MediumLabel}" Text="{Binding Datetime}" />, specifically the **### Style** part is an issue, not sure if it's because I'm using **### staticResource** or not. I just removed that part, and it was not crashing anymore.

**Comment by jfversluis** [comment]
Thanks for letting us know you managed to resolve it!
