### ISSUE TITLE
In the component Entry, ClearButtonVisibility="WhileEditing" doesn't work.

### ISSUE THREAD

**Issue by damusthe** [dotnet/maui#25225]
### Description

Using `Entry` component, with the property `ClearButtonVisibility="WhileEditing"` doesn't work.

Context : 
VS 2022 17.11.5
Net 8.0
NuGet Microsoft.Maui.Controls 8.0.91
Emulator Pixel 5 Android 14 API 34

### Steps to Reproduce

Create a new MAUI default project in .Net 8.
In the MainPage.xaml, add a component `Entry `and add the property `ClearButtonVisibility="WhileEditing"`.
`<Entry Text="text to clear" ClearButtonVisibility="WhileEditing"/>`

Write some text an try to click on the cross/clear button : Nothing happens.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio Enterprise 17.11.5 (8.0.91 &8.0.3), it can repro at android platform.
I did more verification on Visual Studio 17.12.0 Preview 3 (8.0.91), it can not reproduced, so this issue may fixed on 17.12.0 Preview 3(8.0.91).

**Comment by damusthe** [comment]
I tried again on VS 2022 v17.12.0 and in .Net 9.
It works on an `Entry` with `IsPassword="True"`, but not with other kinds.
