### ISSUE TITLE
[MAUI] ListView rendering issues when binding the IsVisible property. 

### ISSUE THREAD

**Issue by samhouts** [dotnet/maui#25221]
<div style="box-sizing:border-box;font-size:16px;font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;margin-top:0px !important;"><p style="box-sizing:border-box;margin-top:0px !important;margin-bottom:16px;"><span style="font-size:14px;">Description</span><br> </p> </div><div style="box-sizing:border-box;margin:15px 0px;"><div style="box-sizing:border-box;margin:0px 0px 6px;"><div style="box-sizing:border-box;font-size:16px;font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;"><p style="box-sizing:border-box;margin-top:0px !important;margin-bottom:0px !important;"><span style="font-size:14px;">Items being replaced (removed and re-added) to a bound observable collection do not render completely after being added when the IsVisible property is changed via a binding.&nbsp;<br></span><br><span style="font-size:14px;">Expected vs actual:</span><br> </p> </div> </div><div style="box-sizing:border-box;"><br> </div><div style="box-sizing:border-box;"><img src="https://dev.azure.com/devdiv/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/wit/attachments/c3b2fd60-db9e-4b19-b2c7-4d7a953522fc?fileName=image.png" alt=Image style="width:330px;" width=330 height=1435><img src="https://dev.azure.com/devdiv/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/wit/attachments/bec44a1d-cfb6-41b2-828c-49c7bd438e41?fileName=image.png" alt=Image style="width:364px;" width=364 height=1431><br> </div> </div><div style="box-sizing:border-box;margin:15px 0px;"><div style="box-sizing:border-box;margin:0px 0px 6px;"><label style="box-sizing:border-box;display:block !important;">Steps to Reproduce</label><div style="box-sizing:border-box;font-size:16px;font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;"><p style="box-sizing:border-box;margin-top:0px !important;margin-bottom:0px !important;"> </p><ol><li>Open attached test project </li><li>Deploy to Android emulator (tested on API 34) </li><li>ListView starts invisible. </li><li>Items will be added on a timer every 5 seconds.&nbsp; </li><li>Watch console output for items count and observe the ListView. </li><li>It should become visible and the first item render completely in 5 seconds. </li> </ol><div>Expected result: </div><div>Every item added to the ObservableCollection will render completely in the ListView and remain visible unless removed.&nbsp; </div><div><br> </div><div>Actual Result: </div><div>Only the yellow box shows on the newly added item. If you scroll the ListView manually, the ListView then renders correctly, but the next added item will again be just a yellow box and no more items will appear until ListView scrolled.&nbsp;&nbsp; </div><p> </p> </div> </div><div style="box-sizing:border-box;"><div style="box-sizing:border-box;"> </div> </div> </div><div style="box-sizing:border-box;margin:15px 0px;"><div style="box-sizing:border-box;margin:0px 0px 6px;"><label style="box-sizing:border-box;display:block !important;"><b>Link to public reproduction project repository</b></label><label style="box-sizing:border-box;display:block !important;">See attached</label> </div> </div><div style="box-sizing:border-box;margin:15px 0px;"><div style="box-sizing:border-box;margin:0px 0px 6px;"><label style="box-sizing:border-box;display:block !important;"><b>Version with bug</b></label><div style="box-sizing:border-box;font-size:16px;font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;"><p style="box-sizing:border-box;margin-top:0px !important;margin-bottom:0px !important;">8.0.21 SR4 </p> </div> </div> </div><div style="box-sizing:border-box;margin:15px 0px;"><div style="box-sizing:border-box;margin:0px 0px 6px;"><label style="box-sizing:border-box;display:block !important;"><b>Is this a regression from previous behavior?</b>&nbsp;</label><label style="box-sizing:border-box;display:block !important;"><span style="color:rgb(0, 0, 0);"><b>No</b></span></label><label style="box-sizing:border-box;display:block !important;"><span style="color:rgb(0, 0, 0);"><b>Possibly related closed issues:</b></span></label><label style="box-sizing:border-box;display:block !important;"><span style="color:rgb(0, 0, 0);"><p style="margin:0in;font-size:12pt;font-family:Aptos, sans-serif;"><a href="https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fgithub.com%2fdotnet%2fmaui%2fissues%2f13095&amp;data=05%7c02%7cJonathan.Goldberger%40microsoft.com%7cac574791625743e165f908dc6560a217%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638496712940582842%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c0%7c%7c%7c&amp;sdata=oxvVuWdlHdO7e0ToUHcs0Uxgjsqzbo50kjXmnpmyOa8%3D&amp;reserved=0">ListView
IsVisible Strange Behavior · Issue #13095 · dotnet/maui (github.com)</a> </p><p style="margin:0in;font-size:12pt;font-family:Aptos, sans-serif;">Which is marked as a dupe of </p><p style="margin:0in;font-size:12pt;font-family:Aptos, sans-serif;"><a href="https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fgithub.com%2fdotnet%2fmaui%2fissues%2f10303&amp;data=05%7c02%7cJonathan.Goldberger%40microsoft.com%7cac574791625743e165f908dc6560a217%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638496712940588028%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c0%7c%7c%7c&amp;sdata=YNed6ef3OkK5s1atR%2fWc84Rmi5H3c7Yv6mDr5PwWzZw%3D&amp;reserved=0">IsVisible
Property not update in ListView · Issue #10303 · dotnet/maui (github.com)</a> </p><p style="margin:0in;font-size:12pt;font-family:Aptos, sans-serif;">And is marked as a dupe of </p><span style="font-size:12pt;font-family:Aptos, sans-serif;"><a href="https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fgithub.com%2fdotnet%2fmaui%2fissues%2f15826&amp;data=05%7c02%7cJonathan.Goldberger%40microsoft.com%7cac574791625743e165f908dc6560a217%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638496712940593142%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c0%7c%7c%7c&amp;sdata=uUyfXpe7dEA8nhj14pjHmR3HK2L%2fIuKtq8rgKuYnmvU%3D&amp;reserved=0">[regression/8.0.0-preview.5.8529]
[Android] ListView doesn't get rendered · Issue #15826 · dotnet/maui
(github.com)</a></span><br></span></label><div style="box-sizing:border-box;font-size:16px;font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;"><p style="box-sizing:border-box;margin-top:0px !important;margin-bottom:0px !important;"><br> </p> </div> </div> </div><div style="box-sizing:border-box;margin:15px 0px;"><div style="box-sizing:border-box;margin:0px 0px 6px;"><label style="box-sizing:border-box;display:block !important;"><b>Affected platforms</b></label><div style="box-sizing:border-box;font-size:16px;font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;"><p style="box-sizing:border-box;margin-top:0px !important;margin-bottom:0px !important;">Android </p> </div> </div> </div><div style="box-sizing:border-box;margin:15px 0px;"><div style="box-sizing:border-box;margin:0px 0px 6px;"><div style="box-sizing:border-box;font-size:16px;font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;"><p style="box-sizing:border-box;margin-top:0px !important;margin-bottom:0px !important;">Please provide the version numbers of the platforms you see this issue on. </p><p style="box-sizing:border-box;margin-top:0px !important;margin-bottom:0px !important;">Tested on API 34 </p> </div> </div> </div><div style="box-sizing:border-box;margin:15px 0px;"><div style="box-sizing:border-box;margin:0px 0px 6px;"><label style="box-sizing:border-box;display:block !important;"><b>Did you find any workaround?</b></label><div style="box-sizing:border-box;font-size:16px;font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;"><p style="box-sizing:border-box;margin-top:0px !important;margin-bottom:0px !important;">Yes, don't use the binding and instead update the IsVisible property directly from the code behind. </p> </div> </div><div style="box-sizing:border-box;"><br><div style="box-sizing:border-box;"> </div> </div> </div><div style="box-sizing:border-box;margin:15px 0px;"><div style="box-sizing:border-box;margin:0px 0px 6px;color:rgb(31, 35, 40);font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;;"><label style="box-sizing:border-box;display:block !important;"><br></label> </div> </div><div> </div>
	
[View on AzDO](https://dev.azure.com/DevDiv/DevDiv/_workitems/edit/2047081)

**Comment by jaosnz-rep** [comment]
It works fine at Android platform on the latest 17.12.0 Preview 2.1(8.0.91). 
By the way, it does have the described problem on 8.0.21.
