### ISSUE TITLE
Text Disappearing on Reducing Scale in .NET MAUI SfImageEditor

### ISSUE THREAD

**Issue by VidyalakshmiMani** [dotnet/maui#25249]
#### **Description:**
In the NET MAUI SfImageEditor control, text added to the image disappears when resizing or reducing the scale, particularly on Mac and iOS platforms. This issue persists despite a similar problem being recently resolved in the Editor control. We have tested with the latest MAUI nightly build and confirmed that the issue still persists.
 
#### **Steps to Reproduce:**
1. Run the attached sample application.
2. Add a text (e.g., "Hello World") to the image editor.
3. Resize the text box or reduce the scale.
4. Observe that part of the text ("World") disappears upon scaling down.
 
#### **Expected Behavior:**
Text should remain visible and scaled correctly without disappearing, even when resizing or reducing the scale.
 
#### **Actual Behavior:**
Text partially disappears when reducing the scale or resizing the text box.
 
#### **Platforms Affected:**
- Mac
- iOS

#### **Issue Replicated Sample:**
[MAUIImageEditorSample.zip](https://github.com/user-attachments/files/17365625/MAUIImageEditorSample.zip)

**Comment by StephaneDelcroix** [comment]
SfImageEditor isn't a MAUI control. can you reproduce the issue on a maui control so we could look ? thanks
