### ISSUE TITLE
TitleBar visual state typo

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#25245]
### Description

`TitleBar` defines a load of visual states. There's a slight discrepancy in the naming of the `Subtitle` visual states:

- `SubtitleVisible`
- `SubTitleCollapsed`

Throughout the code it's always `Subtitle` so `SubTitleCollapsed` should ideally be `SubtitleCollapsed`.

https://github.com/dotnet/maui/blob/release/9.0.1xx-rc2/src/Controls/src/Core/TitleBar/TitleBar.cs

### Version with bug

9.0.0-rc.2

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

Windows

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 2.1,Can repro this issue.
![Image](https://github.com/user-attachments/assets/0eca6ad3-9b49-431f-820a-b452ebcfe0be)
