### ISSUE TITLE
[Bug] [WinUI] Replacing CollectionView ItemTemplate Programmatically sets items to zero height, doesn't clear old items.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2525]
### Description

If you programmatically set the ItemTemplate of a collection view from one template to another, all of the items in the list lose their height, and the old items are not removed at all and new ones are appended to the bottom of the children.

https://user-images.githubusercontent.com/898335/133657463-774e32a0-9f09-495e-b715-7e0b148f9597.mp4

### Steps to Reproduce

Use this reproduction project

[BrandNewMauiApp.zip](https://github.com/dotnet/maui/files/7179836/BrandNewMauiApp.zip)

### Expected Behavior

The templates for the items within the list would be replaced with the new items.

### Actual Behavior

The old items are not removed and all of the items have zero height.

**Comment by v-longmin** [comment]
Verified repro. Repro project:
[BrandNewMauiApp.zip](https://github.com/dotnet/maui/files/8159262/BrandNewMauiApp.zip)

**Comment by VincentBu** [comment]
@drasticactions , would you like to verify this project. I can't repro on android and windows.
[MauiApp2525.zip](https://github.com/dotnet/maui/files/8644670/MauiApp2525.zip)

**Comment by samhouts** [comment]
Looks fixed to me! Thanks!  6.0.300-rc.4.5742
