### ISSUE TITLE
Unable to add localization for .NET MAUI app in VS Code on macOS

### ISSUE THREAD

**Issue by mariuszmatusiak** [dotnet/maui#25260]
### Description

I am creating a .NET MAUI application on macOS (M1 Pro) in VS Code (due to the recently dropped support for Visual Studio for Mac).
I followed the official documentation https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/localization?view=net-maui-8.0 but since not using Visual Studio I was forced to add the *.resx file manually. I figured out the format by using the resgen port available in Mono (version 6.12.0.0). Unfortunately though my compilation fails due to the "Undefined CLR namespace. The 'clr-namespace' URI refers to a namespace 'App.Resources.Languages' that could not be found." error thrown in the main page xaml definition 
`xmlns:strings="clr-namespace:App.Resources.Languages"`
inside the ContentPage. After a thorough search, I then figured out that this might be due to the missing *.Designer.cs file which is normally generated by Visual Studio. I think resgen should also support its generation but the available Mono port version lacks this feature.
How can I proceed further in this case?

### Steps to Reproduce

1. Create a new .NET MAUI project with command line for Visual Studio Code
2. Follow the Localization guide in .NET MAUI documentation 

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Sonoma v14.7

### Did you find any workaround?

No

### Relevant log output

/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(297,3): warning : RuntimeIdentifier was set on the command line, and will override the value for RuntimeIdentifiers set in the project file. [/Users/mariusz/Projects/App/App.csproj::TargetFramework=net8.0-maccatalyst]
Views/CreateProfilePage.xaml(13,62): XamlC XC0022 warning : Binding could be compiled if x:DataType is specified. [/Users/mariusz/Projects/App/App.csproj::TargetFramework=net8.0-maccatalyst]
Views/CreateProfilePage.xaml(25,13): XamlC XC0022 warning : Binding could be compiled if x:DataType is specified. [/Users/mariusz/Projects/App/App.csproj::TargetFramework=net8.0-maccatalyst]
Views/MainPage.xaml(30,16): XamlC error XFC0000: Cannot resolve type "clr-namespace:App.Resources.Languages:Locale". [/Users/mariusz/Projects/App/App.csproj::TargetFramework=net8.0-maccatalyst]
    3 Warning(s)
    1 Error(s)

**Comment by StephaneDelcroix** [comment]
we do not maintain the tooling for this

**Comment by drasticactions** [comment]
As mentioned by @StephaneDelcroix, this is unrelated to the MAUI UI Project. This is generic tooling handled by the runtime and to the best of my knowledge, MAUI does not handle Resx files any different than the runtime.

https://github.com/drasticactions/MauiLang/blob/main/src/MauiLang/MauiLang.csproj#L73-L78
https://github.com/drasticactions/MauiLang/tree/main/src/MauiLang/Translations
My guess would be is you're missing the generator commands in your csproj. If you add those, then compile, it should generate the needed glue logic to get you what you need. If it still doesn't work, you should probably request this in VSCode or dotnet runtime.

**Comment by mariuszmatusiak** [comment]
Hi @StephaneDelcroix, @drasticactions 
Thanks for your insights. According to your suggestions, I registered a similar thread in the vscode-dotnet repository: https://github.com/microsoft/vscode-dotnettools/issues/1545 
In the meantime, I will try the @drasticactions's suggestions though I've already tried similar approaches.
