### ISSUE TITLE
XAML Object Self Reference Gets Warning

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#25272]
### Description

With MauiEnableXamlCBindingWithSourceCompilation set, objects that self-refer get warning

`XamlC warning XC0045: Binding: Property "property name" not found`

For example, this XAML (which draws a circle of diameter `MainViewModel.Diameter`

```XAML
            <Ellipse Stroke="Red"
                 Fill="White"
                 StrokeThickness="5"
                 WidthRequest="{Binding Diameter}"
                 HeightRequest="{Binding Source={RelativeSource Self},Path=WidthRequest}"
                 HorizontalOptions="Center"
                 VerticalOptions="End"
                 Margin="20"/>
```

gets the warning

`XamlC warning XC0045: Binding: Property "WidthRequest" not found`

Because Widthrequest is a property of the Ellipse class whereas Diameter is a property of the MainViewModel class which is specified in an enclosing page level x:DataType.  

### Steps to Reproduce

1. Open the project from Git
2. Build It
3. Observe The Warning

### Link to public reproduction project repository

https://github.com/david-maw/ItemSelfRef.git

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

I was *not* able test on other platforms

**Comment by jaosnz-rep** [comment]
I can repro this issue at Windows platform on the latest 17.12.0 Preview 2.1(9.0.0-rc.2.24503.2 & 9.0.0-rc.1.24453.9).

**Comment by simonrozsival** [comment]
@david-maw in this case, the best way to do this is to specify the `x:DataType` directly on the `{Binding}` like this:
```c#
HeightRequest="{Binding Source={RelativeSource Self}, Path=WidthRequest, x:DataType=Ellipse}"
```
Does this solve your issue?

**Comment by StephaneDelcroix** [comment]
very similar to #25271

**Comment by david-maw** [comment]
I had not realized you could even do that, and VS autocomplete doesn't offer it yet!
I'll be a bit tedious to do, but I can do it, and until #21834 can be implemented, it'll do, thanks.
