### ISSUE TITLE
RC2 : Maui App failed to build with XamlC error : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by khagesh-medtronic** [dotnet/maui#25309]
### Description

If we use BoolToObjectConverter from community toolkit the app build is failing with **XamlC error : Object reference not set to an instance of an object** in dotnet 9  RC2. 
Here is example code snippet : 

 
  ```
<ContentPage.Resources>
        <ResourceDictionary>
            <Color x:Key="LightGray">#B1B3B3</Color>
            <Color x:Key="myBlue">#140F4B</Color>

            <SolidColorBrush x:Key="TrueColorBrush">Green</SolidColorBrush>
            <SolidColorBrush x:Key="FalseColorBrush">Red</SolidColorBrush>

            <toolkit:BoolToObjectConverter x:Key="IsValidConverter"
                                           TrueObject="{StaticResource myBlue}"
                                           FalseObject="{StaticResource LightGray}"/>
        </ResourceDictionary>
    </ContentPage.Resources>


```

The issue is when we use StaticResource ({StaticResource LightGray}) binding in the BoolToObjectConverter converter. 

### Steps to Reproduce

1. Create new Maui app 
2. add below code snippet in the MainPage.xaml 
 
```
<ContentPage.Resources>
        <ResourceDictionary>
            <Color x:Key="LightGray">#B1B3B3</Color>
            <Color x:Key="myBlue">#140F4B</Color>

            <SolidColorBrush x:Key="TrueColorBrush">Green</SolidColorBrush>
            <SolidColorBrush x:Key="FalseColorBrush">Red</SolidColorBrush>

            <toolkit:BoolToObjectConverter x:Key="IsValidConverter"
                                           TrueObject="{StaticResource myBlue}"
                                           FalseObject="{StaticResource LightGray}"/>
        </ResourceDictionary>
    </ContentPage.Resources>
```
3. build  the App. 
4. The build fails with error **XamlC error : Object reference not set to an instance of an object.**

### Link to public reproduction project repository

https://github.com/khagesh-medtronic/Maui-Sample/tree/main/MauiAppRC2CommunityToolkit

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Affected platforms

iOS, Android

### Did you find any workaround?

Able to build and run if I provide direct value to the TrueObject and FalseObject false object instead using StaticResource binding.
```
<ContentPage.Resources>
        <ResourceDictionary>
            <Color x:Key="LightGray">#B1B3B3</Color>
            <Color x:Key="myBlue">#140F4B</Color>

            <SolidColorBrush x:Key="TrueColorBrush">Green</SolidColorBrush>
            <SolidColorBrush x:Key="FalseColorBrush">Red</SolidColorBrush>

            <toolkit:BoolToObjectConverter x:Key="IsValidConverter" 
                               TrueObject="#140F4B"
                               FalseObject="#74358F" x:TypeArguments="Brush"/>
        </ResourceDictionary>
    </ContentPage.Resources>


```

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 3 (9.0.0-rc.2.24503.2 &9.0.0-rc.1.24453.9). Can repro this issue, and works fine on 17.12.0 Preview 3 (9.0.0-rc.1.24453.9)
![Image](https://github.com/user-attachments/assets/3ca3adfa-97b5-4104-abe5-39b103647823)

**Comment by khagesh-medtronic** [comment]
@ninachen03 I am using VS code for the development as Visual studio is no more option for people working on Mac, Visual studio for Mac doesn't support .net 9 development.

**Comment by StephaneDelcroix** [comment]
ok, we regressed this because we now pre-compile {StaticResource}

**Comment by StephaneDelcroix** [comment]
other workaround is to skip compilation on that file, or write your own converter that doesn't involves generic properties

**Comment by PureWeen** [comment]
This is resolved by https://github.com/dotnet/maui/pull/25352

I tested the repro against our latest GA bits and the error is no longer present
