### ISSUE TITLE
iOS simulator does not launch

### ISSUE THREAD

**Issue by JasonGCross** [dotnet/maui#25301]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

macOS version: Sequoia 15.0.1
Visual Studio Code version: 1.94.2 (Universal)

Repro steps:
1. create a new blank .NET MAUI project
2. select iOS as a debug target
3. click "Run and Debug"

Expected outcome:
- the iOS simulator will open

Observed outcome:
- the iOS simulator never opens
- BUT build does succeed, showing debugger attached

Terminal output:

 *  Executing task: dotnet build -t:Build -p:Configuration=Debug -f net7.0-ios -r iossimulator-x64 -p:CustomAfterMicrosoftCSharpTargets="/Users/{user_name}/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/resources/Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile="/var/folders/km/zsdqbjrd2rb6hzkwvh95r7ww0000gn/T/dotnet-maui/maui-vsc-5abdbe76-2ed9-4f95-84dd-026a618550f1.json" -p:XamlTools="/Users/{user_name}/.vscode/extensions/ms-dotnettools.csharp-2.50.27-darwin-arm64/.xamlTools" /Users/{user_name}/Projects/MauiApp1/MauiApp1.csproj 

  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/local/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(251,5): warning NETSDK1201: For projects targeting .NET 8.0 and higher, specifying a RuntimeIdentifier will no longer produce a self contained app by default. To continue building self-contained apps, set the SelfContained property to true or use the --self-contained argument. [/Users/{user_name}/Projects/MauiApp1/MauiApp1.csproj::TargetFramework=net7.0-ios]
  Detected signing identity:
          
    Bundle Id: com.companyname.mauiapp1
    App Id: com.companyname.mauiapp1
  Including assemblies for Hot Reload support
  MauiApp1 -> /Users/{user_name}/Projects/MauiApp1/bin/Debug/net7.0-ios/iossimulator-x64/MauiApp1.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink

Build succeeded.

/usr/local/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(251,5): warning NETSDK1201: For projects targeting .NET 8.0 and higher, specifying a RuntimeIdentifier will no longer produce a self contained app by default. To continue building self-contained apps, set the SelfContained property to true or use the --self-contained argument. [/Users/{user_name}/Projects/MauiApp1/MauiApp1.csproj::TargetFramework=net7.0-ios]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.82
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by drasticactions** [comment]
The MAUI team does not maintain the underlying tooling for deploying .NET applications. This repo is for the MAUI UI Toolkit.

If you move your issue to VSFeedback or the .NET MAUI VS Code Extension repo, they can help diagnose your issue.

**Comment by JasonGCross** [comment]
Thank-you for your replies. The first link provided: [Visual Studio for Windows feedback tool](https://learn.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) describes using Visual Studio on Windows.

I am using Visual Studio Code on a Mac. The "normal" Visual Studio has been discontinued / deprecated / discouraged on Mac.

I have opened a new bug using the second link provided. The [new bug may be found here](https://github.com/microsoft/vscode-dotnettools/issues/1543)
