### ISSUE TITLE
Blazor Desktop tenets: Global readiness

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#2532]
- In general, globalization and localization
- But also patterns for building apps that use these patterns. It is likely that both Blazor and the native UI platforms each have their own flavors of this, so we need to see how these fit into a single app.
- Does each native WebView component have some of its own concerns/features we need to be aware of?

**Comment by pranavkm** [comment]
I spent a bit of time working this out today. 

To start with MAUI configures the CurrentCulture / CurrentUICulture based on the device's ambient information. Closest available docs are from Xamarin.Forms, but they apply to MAUI too https://docs.microsoft.com//xamarin/xamarin-forms/app-fundamentals/localization/text?pivots=windows#test-localization. 

This allows `IStringLocalized<>` to work out of the box just the way our docs explain it. Similar globalization also works - all of the formatting / parsing / binding use the culture correctly. 

Interestingly, .NET's resourcing system also supports embedding images as blobs in to the app which IStringLocalizer does not support. Even if a user were to read these images using ResourceManager, we [currently don't](https://github.com/dotnet/aspnetcore/issues/25274) have a component that allows rendering the retrieved Stream as an image. 

In addition to this, there are [platform specific](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=windows#local-images) ways to include [localized images](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/localization#resource-folders). This problem would apply to WebViews in general, but browser elements do not know how to do the interact with these systems. That said, I couldn't get this to work with my Android sample, I'm working on following up with devs on this if this is meant to work.

Dynamically changing the app culture at runtime is a bit interesting - in WASM, we expect the app to be reloaded if the culture changes. This take care of re-rendering the root component and flushing the new culture to child components. There are some instances of users trying this in their [Xamarin.Forms apps](https://stackoverflow.com/a/44417380) which relies on triggering an event causing their app to re-render. A determined user could do something similar to re-render the root component in this case.

**Comment by pranavkm** [comment]
@guardrex could I get some help with the docs for this? The plan is to document this as another pivot on the localization page of the Blazor docs: https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-6.0&pivots=webassembly?

**Comment by guardrex** [comment]
We're going to have a focused *Blazor Hybrid* node, so we can have a topic on this there. I've added it to the tracking issue and cross-linked this issue for work.

**Blazor Hybrid tracking**
https://github.com/dotnet/AspNetCore.Docs/issues/24956

**Comment by pranavkm** [comment]
Thanks. I'll close this issue since we're already tracking work in the docs issue.
