### ISSUE TITLE
Blazor Desktop navigation

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#2533]
- General navigation within the browser, i.e. clicking on links within a Blazor page to another Blazor page
- Use Blazor's existing built-in navigation interfaces/services
- Integration with native gestures/hardware and other UI for navigation, for example:
  - Android Back Button
  - Swipe gestures
  - Accessibility-related browser controls (such as?)
  - Alternate navigation UI, such as app-specific native buttons for browser nav (e.g. using Forms Shell, or custom buttons)

**Comment by mkArtakMSFT** [comment]
Closing as there is a separate issue tracking the remaining work with the `Back` button.
