### ISSUE TITLE
Blazor Hybrid templates have an empty title bar

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#25337]
The default Blazor Hybrid templates have an empty window title bar. The regular .NET MAUI templates have the app's name in the title bar.

| Blazor Hybrid, even if I set the ContentPage's Title | .NET MAUI |
|---|---|
| ![Image](https://github.com/user-attachments/assets/f73d724f-d09a-4454-bbc5-45cabf538d64) | ![Image](https://github.com/user-attachments/assets/fef0c78b-89eb-4550-bfc7-926352bedfb7) |
| Taskbar (no title) | Taskbar (has title) |
| ![Image](https://github.com/user-attachments/assets/482864ac-e94a-4fed-9923-e74b36ea97c4) | ![Image](https://github.com/user-attachments/assets/73caced4-4498-44b5-847d-90a7ee09245c) |

I'm not sure the right way to fix this. It seems that the Shell control picks up the title and makes it the app window's title. But without Shell I'm not sure how to do it.

**Comment by jfversluis** [comment]
Looks like its this: https://github.com/dotnet/maui/blob/f86bf4771a828a41358818f10f9498870acd5524/src/Controls/src/Core/Window/Window.cs#L110

We only cast it to `Shell` and take that title, but don't do it for any other page type?

The other thing we could to is set the title in the `App.xaml.cs` when we create a new window but I don't think that's a great solution as you'll have another separate place where you need to set a title.

**Comment by jfversluis** [comment]
Added a potential fix here: #25338 lets try the resulting binaries and see if that has the desired effect. Also cc: @PureWeen

**Comment by PureWeen** [comment]
> The default Blazor Hybrid templates have an empty window title bar. The regular .NET MAUI templates have the app's name in the title bar.
> 
> Blazor Hybrid, even if I set the ContentPage's Title	.NET MAUI
> ![Image](https://github.com/user-attachments/assets/f73d724f-d09a-4454-bbc5-45cabf538d64)	![Image](https://github.com/user-attachments/assets/fef0c78b-89eb-4550-bfc7-926352bedfb7)
> Taskbar (no title)	Taskbar (has title)
> ![Image](https://github.com/user-attachments/assets/482864ac-e94a-4fed-9923-e74b36ea97c4)	![Image](https://github.com/user-attachments/assets/73caced4-4498-44b5-847d-90a7ee09245c)
> I'm not sure the right way to fix this. It seems that the Shell control picks up the title and makes it the app window's title. But without Shell I'm not sure how to do it.

All shell does it set it on the Window

The guidance here for users has been to just set it on the `Window` itself

every element in the hierarchy has access to the window so it can set it that way. 

Now that we make people override CreateWindow you can set it there

**Comment by Eilon** [comment]
See new attempt here: https://github.com/dotnet/maui/pull/25387

**Comment by Eilon** [comment]
9.0.1xx PR: #25426

**Comment by Eilon** [comment]
Fixed by #25426
