### ISSUE TITLE
First debug

### ISSUE THREAD

**Issue by K3rly94** [dotnet/maui#25358]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Hey there, thank you for your interest in .NET MAUI! Sorry you hit a snag here.

However, without any information we will be unable to help you as I can't tell what the thing is you're seeing. Could you please provide some more information? Thanks!

**Comment by K3rly94** [comment]
![Screenshot_20241018_141010_Gmail.jpg](https://github.com/user-attachments/assets/8dbcf8aa-9c65-4a12-ba9c-39065391e8bb)


I cant explain it, this was like someone else controls my device, such a veird move and opens apps what i didnt opened.. but today is nothing like that, and i got my gmail also back.
