### ISSUE TITLE
Hyper v activation

### ISSUE THREAD

**Issue by someonesunclesmith** [dotnet/maui#25354]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I can't activate hyper- v since i have windows 11 and it does not include hyper -v in the windows feature
Visual Studio Community 2022

**Comment by jfversluis** [comment]
Please check the requirements for enabling Hyper-V on your Windows machine: https://learn.microsoft.com/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

If your machine does not meet the requirements I'm afraid there is not much we can do unfortunately.

You can still run on a physical device or find an alternative emulator that does not require Hyper-V.
