### ISSUE TITLE
Collection View Scrolling Not Smooth on iOS 18 (Version 8.0.92), While Versions 8.0.40 and iOS 17 Perform Smoothly

### ISSUE THREAD

**Issue by alpayclsr1** [dotnet/maui#25369]
### Description

 I am experiencing significant lag when attempting to scroll in the CollectionView with .NET MAUI version 8.0.92 on iOS 18. When I downgrade to .NET MAUI version 8.0.40, the lag is somewhat reduced, but it remains noticeably bothersome. However, with version 8.0.4, the application runs smoothly on an below iOS 18 devices without any lag. In summary:

.NET MAUI 8.0.92 on iOS 18: Severe lag during scrolling.
.NET MAUI 8.0.40 on iOS 18: Reduced lag but still disruptive.
.NET MAUI 8.0.4 on devices running iOS versions below 18: CollectionView operates perfectly with zero lag.

### Steps to Reproduce

Reproduction app maui version 8.0.4 run application below ios 18 and see there is no lag when scrolling.
then change maui version 8.0.92 run application on  ios 18 and see significant lag.
then change maui version 8.0.4 run application on  ios 18 and there is still lag but less than 8.0.92

### Link to public reproduction project repository

https://github.com/alpayclsr1/CollectionViewPerformanceIssueReproductionApp.git

### Version with bug

8.0.92 SR9.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

iOS

### Affected platform versions

iOS 18

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12.0 Preview 3(8.0.92& & 8.0.80 & 8.0.60 & 8.0.40). Can repro this issue on iOS platform.

**Comment by ssbssb-cmd** [comment]
Did you manage to sort this out or get some workaround?

**Comment by PureWeen** [comment]
@alpayclsr1 

can you test the following nightly build version 

8.0.100-ci.net8.24556.5

https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by alpayclsr1** [comment]
Yes, I tested on version 8.0.100-ci.net8.24556.5, and it’s much better than 8.0.92—the scroll is smooth now.

**Comment by PureWeen** [comment]
@alpayclsr1 thank you for checking!

Going to close this issue as fixed
