### ISSUE TITLE
Mac Catalyst MAUI build Application Name appearing as Assembly Name - Causing Apple Rejection

### ISSUE THREAD

**Issue by caliberdigitalllc** [dotnet/maui#25364]
### Description

I am producing a Mac Catalyst build for release with the following command:

```
dotnet publish -f net9.0-maccatalyst -c Release \
    -p:ArchiveOnBuild=true \
    -p:CreatePackage=true \
    -p:EnableCodeSigning=true \
    -p:CodesignKey="Apple Distribution: AlzBetter LLC (8DVSMQ7G8N)" \
    -p:CodesignProvision="MacOS Distribution" \
    -p:CodesignEntitlements="Platforms/MacCatalyst/Entitlements.plist" \
    -p:EnablePackageSigning=true
```

I have these keys in info.plist:
```
<key>CFBundleName</key>
<string>AlzBetter Coach</string>
<key>CFBundleDisplayName</key>
<string>AlzBetter Coach</string>
```

I have this key in CSPROJ:
`<ApplicationTitle>AlzBetter Coach</ApplicationTitle>`

But when I deploy the build out to the app store, when installed, it installs as "AbMobileMaui" which is the assembly/project name. Apple is refusing to release the app because the app name doesn't match the actual app name (AlzBetter Coach) due to it installing as AbMobileMaui.

What setting/key am I missing here? The iOS build installs perfectly fine as the right app name.

This has been like this for several .net releases - I am just reporting it now.

### Steps to Reproduce

Create a mac catalyst app, build in release mode, release to testflight/app store.

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-macios#21478
