### ISSUE TITLE
.NET MAUI Windows app can't start

### ISSUE THREAD

**Issue by BennKjaer62** [dotnet/maui#25372]
### Description

I have a Maui Windows app that runs fine in VS 2022. But when I want to execute the app outside VS nothing happens.
The app is only used for Windows, so iOS and Android platform has been disabled.
I can see in the Event Viewer that two error is returned when the app tries to start.

I have tested in VS2022 v.17.11.5 and in VS2022 Preview 17.12.0 Preview 3.0

[Maui test error 1.txt](https://github.com/user-attachments/files/17433755/Maui.test.error.1.txt)
[Maui test error 2.txt](https://github.com/user-attachments/files/17433756/Maui.test.error.2.txt)
![Image](https://github.com/user-attachments/assets/d4e9b6be-077f-4bac-b621-44424b2800b3)
[Maui test - VS2022_17115.txt](https://github.com/user-attachments/files/17433757/Maui.test.-.VS2022_17115.txt)
[Maui test - Windows and dot Net Version.txt](https://github.com/user-attachments/files/17433759/Maui.test.-.Windows.and.dot.Net.Version.txt)

### Steps to Reproduce

1. Create a standard MauiApp.
2. Disable iOS and Android under Ssettings for the Project.
3. Rebuild the app in Release mode.
4. Go to [Your project]\bin\Release\net8.0-windows10.0.19041.0\win10-x64 and run the .exe file from Explorer.
5. Open Event Viewer and take a look at the latest two errors.

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19045.5011

### Did you find any workaround?

No workaround found.

**Comment by bronteq** [comment]
Hi this is the normal behavior.
If you want execute the Windows app outside Visual Studio you need to publish the app.
Follow these steps https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/overview?view=net-maui-8.0

**Comment by BennKjaer62** [comment]
Hi again.

I have tried what you suggested. But that just ended up with an new error, where the system is looking for a file where it's not placed.

Error:
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	NU5026	The file '[project]\bin\Release\net8.0-maccatalyst\MauiAppTest.runtimeconfig.json' to be packed was not found on disk.	MauiAppTest	C:\Program Files\dotnet\sdk\8.0.403\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets	221	

There are no files placed directly under [project]\bin\Release\net8.0-maccatalyst\

And I don't understand why the "publisher" looks for files under \net8.0-maccatalyst\ when it's a net8.0-windows10.0.19041.0 Framework I'm working on.

**Comment by bronteq** [comment]
This should be a csproj file problem, probably some important lines are missing, I also got a similar problem in the past.
You have to decide which publishing type you want to execute (packaged or unpackaged), based on this decision you have to add some specific rows to the csproj file and then you can publish your app.

Packaged app: https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-8.0
Unpackaged app: https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-unpackaged-cli?view=net-maui-8.0
