### ISSUE TITLE
DataTrigger doesn't change Rectangle background color on iOS

### ISSUE THREAD

**Issue by MaxxDelusional** [dotnet/maui#25385]
### Description

I have a Rectangle defined in XAML, and I want to adjust its color based on a Data Trigger. I started with something simple like this.

```
 <Rectangle Grid.Row="0" Grid.Column="0" BackgroundColor="#00FF00">
     <Rectangle.Triggers>
         <DataTrigger TargetType="Rectangle" Binding="{Binding Cancelled}" Value="True">
             <Setter Property="BackgroundColor" Value="#FF0000" />
         </DataTrigger>
     </Rectangle.Triggers>
</Rectangle>
```

This works on Android, but on iOS the color is always `#00FF00`.  

`Cancelled` is a Nullable Boolean defined in my ViewModel. I have verified that the value is indeed set to `true`. I am able to use the `Cancelled` binding on other Views to control things like visibility. For example, this works as expected.

```
 <Label IsVisible="{Binding Cancelled}" Text="Canceled" />
```

The last iteration in my attempt to make this works looks like this.

```
<Rectangle Grid.Row="0" Column="0">
    <Rectangle.Style>
        <Style TargetType="Rectangle">
            <Style.Triggers>
                <DataTrigger TargetType="Rectangle" Binding="{Binding Cancelled}" Value="{x:Null}">
                    <Setter Property="BackgroundColor" Value="#0000FF" />
                </DataTrigger>
                <DataTrigger TargetType="Rectangle" Binding="{Binding Cancelled}" Value="False">
                    <Setter Property="BackgroundColor" Value="#00FF00" />
                </DataTrigger>
                <DataTrigger TargetType="Rectangle" Binding="{Binding Cancelled}" Value="True">
                    <Setter Property="BackgroundColor" Value="#FF0000" />
                </DataTrigger>
            </Style.Triggers>
        </Style>
    </Rectangle.Style>
    
</Rectangle>

```

But, the color is still always `#00FF00` on iOS. This issue seems to only affect BackgroundColor. For example, this trigger works as expected.

```
<Rectangle.Triggers>
    <DataTrigger TargetType="Rectangle" Binding="{Binding Cancelled}" Value="True">
        <Setter Property="HeightRequest" Value="500" />
    </DataTrigger>
</Rectangle.Triggers>

```

Using `Background` instead of `BackgroundColor` still doesn't work.

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by MaxxDelusional** [comment]
There's plenty of code in my bug description that will help you reproduce this issue.

**Comment by drasticactions** [comment]
> There's plenty of code in my bug description that will help you reproduce this issue.

Writing a repro project that can be deployed makes it easier to have a shared instance of the code that every one can agree doesn't work. If someone tried to replicate this based on what you wrote, and it works, then there will be back and forth trying to get it to reproduce. Having a deployable project makes it easier.

**Comment by drasticactions** [comment]
Can you also please try what @MartyIX suggested?

**Comment by MaxxDelusional** [comment]
@MartyIX solution did not work. All of the Rectangles are still Green.

I also tried using a custom ValueConverter. In doing so, I can verify that my `Cancelled` flag is definitely set to `true`, but I always get the False binding.

```
public class BoolToColorConverter : BaseConverterOneWay<bool?, Color>
{
    public Color TrueColor { get; set; } = Colors.Red;
    public Color FalseColor { get; set; } = Colors.Green;

    public override Color DefaultConvertReturnValue { get; set; } = Colors.Transparent;

    public override Color ConvertFrom(bool? value, CultureInfo? culture)
    {
        if (value == true)
        {
            return TrueColor;
        }
        else if (value == false)
        {
            return FalseColor;
        }
        return DefaultConvertReturnValue;
    }
}

```

> Writing a repro project that can be deployed makes it easier to have a shared instance of the code that every one can agree doesn't work. If someone tried to replicate this based on what you wrote, and it works, then there will be back and forth trying to get it to reproduce. Having a deployable project makes it easier.

I understand the need for this, but I have a day job with deadlines. If you want to close this issue because I am unable to spend time putting together a standalone example, that's your call, but the issue is definitely still valid.
