### ISSUE TITLE
didn't find curly braces

### ISSUE THREAD

**Issue by dummertom** [dotnet/maui#25394]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: macos
System version: macOS 15.0.1

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I was following your tutorial mentioned above. at the point, where I should run the .xaml
You mentioned, that I should have curly braces on the bottom of the VS-Code window. But on my window there's nothing.
![Image](https://github.com/user-attachments/assets/63eb1d00-9848-4b20-a549-53ea9df2b273)
however, when I go to an c# file the curly braces are there.
![Image](https://github.com/user-attachments/assets/459f77b8-e880-4349-97c8-59263c1c5e3c)
I followed your tutorial as mentioned but have no clue, where i went wrong.

**Comment by jfversluis** [comment]
Thanks for the feedback! This tutorial is hosted somewhere else, I have created a PR that adds some clarity around this. Otherwise, there is not much else we can do about it here for now. Hopefully it will be merged soon for the next person!
