### ISSUE TITLE
Blazor Desktop API review

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#2539]
Need to review the public API for these features, considering several scenarios:

* Typical usage of the features, such as adding a BlazorWebView to a native UI page and which properties/methods/events it exposes
* More advanced usage, such as customizing the inner WebView to control per-WebView settings (e.g. context menus, debugging options, etc.)
* Extension usage, such as people looking to write libraries to support additional platforms or alter behavior of the control, including accessing various "implementation details" of the controls

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS given that there are now follow-up issues filed, should this one be closed?

**Comment by SteveSandersonMS** [comment]
Yes, closing as this is now superseded by other issues.
