### ISSUE TITLE
Blazor Desktop tenets: Security

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#2540]
- Need to define what are the threats here
- Rogue-ish 3rd party component?
- Need to look at the threat models for other native client platforms, e.g. WPF, because we will likely have some subset of the same concerns
- Need to review guidance from docs of each native WebView component for any best practices

**Comment by mkArtakMSFT** [comment]
Closing as the remaining work is being addressed and is tracked: https://github.com/aspnet/specs/issues?q=is%3Aissue+is%3Aopen+label%3Asecurity
