### ISSUE TITLE
Codesign fails with replacing existing signature and errSecInternalComponent

### ISSUE THREAD

**Issue by tpitman** [dotnet/maui#25432]
### Description

I was using MAUI SDK 401. Everything was working fine. I got tired of dealing with VSCode issue and decided to switch to using VS 2022 on Windows on ARM in Parallels. I am on a Mac.

I had everything installed, but saw there was an update to 17.11.5. I installed the update and it seems that it installed an update to 8.0.403.

When I tried to debug with that it said I needed XCode 16. I had been holding off, but decided to go ahead and see if I could get this all working on the latest.

Long story short I am able to build and debug to an iOS physical device, but when I try to do a release build for distribution to the app store I get an error.

It happens during the codesign step.

I get 2 and they are happening on one of the framework files included in my app as far as I can tell. Here are the 2 lines for the errors:

![Image](https://github.com/user-attachments/assets/6c45b9f7-1f94-43fb-a316-58570725bbfd)

If I use the publish feature in VS 2022 for Windows it does build an archive, but when I try to upload it I get an error trying to upload it.

The command I use to do the build is:

`dotnet publish -f net8.0-ios -c Release`

That is the command I have been using ever since I had to stop using VS For Mac and it has worked fine until 8.0.403.

Now I am stuck and can't release the app update that I really need to update.

Please help. I am in a bad way right now.

### Steps to Reproduce

1. Build on command line for release.
2. Get codesign error

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.70 SR7

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 3.0(8.0.92). Cannot repro it.
![Image](https://github.com/user-attachments/assets/5dbab237-2ca7-4296-9abf-b29c7cb78eeb)

**Comment by tpitman** [comment]
I am trying to do the build on the Mac using the command line. Can you tell me how to update the dotnet stuff to 8.0.92? I have been using the VSCode .NET Install Tool plugin for VSCode. It only shows 8.0.403 as an option when it gets to the version.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/20159
 https://github.com/dotnet/maui/wiki/Nightly-Builds

Have some info that should help you

**Comment by tpitman** [comment]
There are so many moving parts and pieces. I just realized that the 8.0.92 you are talking about is the nuget component versions that I just have to change in my csproj files. I did that and that was able to build at the command line without giving the signing error.

It is amazing we are able to ever get anything done with all the different parts and pieces that have to come together in the right sequence. SDKs, workloads, nuget packages.

I thank you and your team for making it all happen. It is complicated and you guys are amazing.

**Comment by tpitman** [comment]
As an FYI, I decided to try publishing from Windows VS again. It built fine, but then wouldn't upload. So I copied the IPA file to my Mac and used my command line to try to upload it. It said the provisioning profile was invalid.

The exact same settings in the csproj project file work fine when I publish on the Mac and it was set to automatic provisioning.

I then tried manually setting the profile in the settings, built and that uploaded fine and the build doesn't crash.

So I am able to build and upload using Windows VS, but not the Mac on the same project.

I will do that for now, but am not happy about this result.

I know others have said this, but I sure wish VS for Mac had not been discontinued. It was soooooo sweet. The new VSCode path just doesn't work well and this Windows VS combined path is also not great.

I will try to make due.

**Comment by tpitman** [comment]
That may be why it started working without me knowing why. I thought is was other things I changed, but now I back at 8.0.82 and it is still working, so maybe?

**Comment by Kanat9494** [comment]
I'm getting the same error after I bought a new mac. I can't run app on ios simulators, though I can publish ios app with Windows Visual Studio, but I can't run and check the app on simulators. I'm just testing on Android and publishing for ios without testing on ios device or simulator
