### ISSUE TITLE
Referenced assembly 'Microsoft.AspNetCore.Components.WebView.WindowsForms does not have a strong name

### ISSUE THREAD

**Issue by e1em3ntoDX** [dotnet/maui#25439]
### Description

Hello,

We, at DevExpress, plan to wrap our own Blazor Chat Component using the WebView and extend our WinForms product line with a new WinForms Chat control. In our library, targeting .NET 8, we use the Microsoft.AspNetCore.Components.WebView.WindowsForms v8.0.92 package for these purposes and at the build stage we receive the following error: 

>error CS8002: Referenced assembly 'Microsoft.AspNetCore.Components.WebView.WindowsForms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\builds\XXXX\DevExpress.AIIntegration.WinForms.Chat\DevExpress.AIIntegration.WinForms.Chat.csproj]

Our assemblies are all signed with the strong name SNK file. I see that the issue is similar to [Using Microsoft.AspNetCore.Components.WebView.WindowsForms in Visual Studio says it does not have a strong name](https://github.com/dotnet/maui/issues/13711).

Please let me know if you have plans to sign this assembly in the upcoming .NET 9 release/further .NET 8 updates? 

Thank you,
Dmitry 

Product Manager at DevExpress

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

Yes, the workaround from this thread helped us to overcome the issue https://github.com/dotnet/maui/issues/749. 

### Relevant log output

>error CS8002: Referenced assembly 'Microsoft.AspNetCore.Components.WebView.WindowsForms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\builds\XXXX\DevExpress.AIIntegration.WinForms.Chat\DevExpress.AIIntegration.WinForms.Chat.csproj]

**Comment by PureWeen** [comment]
@mkArtakMSFT thoughts?

**Comment by MackinnonBuck** [comment]
@PureWeen, do assemblies produced in the `maui` repo not get signed with a strong name? Or is this specific assembly misconfigured?

**Comment by e1em3ntoDX** [comment]
@MackinnonBuck, based on the information in [this thread](https://github.com/dotnet/maui/issues/749), it appears that this issue affects all MAUI assemblies. The thread also indicates that the issue was added to the backlog quite some time ago. As .NET 9 release approaches, we’re wondering if there have been any updates or changes in the plans regarding this matter.

Cheers

**Comment by mkArtakMSFT** [comment]
> [@MackinnonBuck](https://github.com/MackinnonBuck), based on the information in [this thread](https://github.com/dotnet/maui/issues/749), it appears that this issue affects all MAUI assemblies. The thread also indicates that the issue was added to the backlog quite some time ago. As .NET 9 release approaches, we’re wondering if there have been any updates or changes in the plans regarding this matter.
> 
> Cheers

You're absolutely right, @e1em3ntoDX. There has unfortunately been no progress on this front in .NET 9 based on the updates on the linked issue. Having said that, I'm going to close this issue as the linked issue is tracking the main problem.
