### ISSUE TITLE
Processing Resources failed with error: Duplicate Entry

### ISSUE THREAD

**Issue by sitecompass** [dotnet/maui#25434]
### Description

Hello!

We are going through the process of upgrading our current project from .NET 8 to .NET 9 GA for MAUI.

After going through the process of changing the targets and upgrading NUGET packages, there were some issues that made us target the latest nightly build to allow us to bypass some of the fixed issues (currently targeting nightly build: 9.0.10-ci.net9.24521.2).

This appears to resolve all the build issues that we were previously experiencing, but a new one has since appeared:

```
1>WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.
1>WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI277: 0x80073b0f - Conflicting values for resource 'Files/Microsoft.Maui/Platform/Windows/Styles/WindowRootViewStyle.xbf'
```

Any help with how this could be resolved would be greatly apricated.

Also these are the additional packages that are used with the project (if this provides any insight)

```
<PackageReference Include="AdamE.MemoryToolkit.Maui" Version="1.0.0" />
<PackageReference Include="CommunityToolkit.Maui.Markup" Version="4.2.0" />
<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
<PackageReference Include="CommunityToolkit.Maui" Version="9.1.0" />
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0-rc.2.24473.5" />
<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0-rc.2.24473.5" />
<PackageReference Include="Sentry.Maui" Version="4.4.0" />
<PackageReference Include="Syncfusion.Maui.Buttons" Version="26.2.13" />
<PackageReference Include="Syncfusion.Maui.Picker" Version="26.2.13" />
<PackageReference Include="Syncfusion.Maui.ProgressBar" Version="26.2.13" />
<PackageReference Include="Syncfusion.Maui.TreeView" Version="26.2.13" />
<PackageReference Include="Syncfusion.XlsIO.NET" Version="26.2.13" />
<PackageReference Include="Syncfusion.Maui.Core" Version="26.2.13" />
<PackageReference Include="Syncfusion.Maui.DataForm" Version="26.2.13" />
<PackageReference Include="Syncfusion.Maui.DataGrid" Version="26.2.13" />
<PackageReference Include="Syncfusion.Maui.Inputs" Version="26.2.13" />
<PackageReference Include="Syncfusion.Maui.ListView" Version="26.2.13" />
<PackageReference Include="Syncfusion.Maui.Popup" Version="26.2.13" />
<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
<PackageReference Include="Syncfusion.Maui.TabView" Version="26.2.13" />
<PackageReference Include="System.Text.Json" Version="9.0.0-rc.2.24473.5" />
<PackageReference Include="Telerik.UI.for.Maui" Version="7.1.0" />
<PackageReference Include="The49.Maui.BottomSheet" Version="8.0.3" />
<PackageReference Include="UraniumUI" Version="2.7.4" />
<PackageReference Include="UraniumUI.Material" Version="2.7.4" />
```

### Steps to Reproduce

1. Open an existing project
2. Add nightly build nuget url to nuget.config file ```<add key="nuget.org - nightly" value="https://pkgs.dev.azure.com/xamarin/public/_packaging/maui-nightly/nuget/v3/index.json" protocolVersion="3" />```
3. Set ```<MauiVersion>9.0.10-ci.net9.24521.2</MauiVersion>```
4. Set 
```
<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
```

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.92 SR9.2

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

No workaround has been found so far.

### Relevant log output

6>SiteCompass -> C:\Users\developer\Source\repos\SiteCompassMaui\SiteCompass\bin\Debug\net9.0-windows10.0.19041.0\win10-x64\SiteCompass.dll
6>WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.
6>WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI277: 0x80073b0f - Conflicting values for resource 'Files/Microsoft.Maui/Platform/Windows/Styles/WindowRootViewStyle.xbf'
6>Done building project "SiteCompass.csproj" -- FAILED.
========== Build: 5 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 12:33 PM and took 26.767 seconds ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Deploy completed at 12:33 PM and took 26.767 seconds ==========

**Comment by jaosnz-rep** [comment]
This issue can't be reproduced at Windows platform on the latest 17.12.0 preview 3(9.0.10-ci.net9.24521.2 & 9.0.0-rc.2.24503.2 & 8.0.92).
![Image](https://github.com/user-attachments/assets/c120b4bc-5b79-41ec-9775-547628f3722a)

**Comment by riesem** [comment]
I have had the same error. Upgrading Syncfusion controls to the latest version 27 resolved it.

**Comment by sitecompass** [comment]
> I have had the same error. Upgrading Syncfusion controls to the latest version 27 resolved it.

Thank you so much! I updated the Syncfusion packages and its fixed!!!
