### ISSUE TITLE
Blazor Desktop test infrastructure and plans

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#2543]
- Automated tests for headless behaviors
- CTI scripts for UI tests
- Consider some automation for UI tests

**Comment by SteveSandersonMS** [comment]
Note: the scope of my work here doesn't include *writing all the tests*. It's about figuring out:

 * What stuff should be tested
 * What the basic pattern for testing (automated or CTI) is, to the point of having some example(s)

... and then I'm going to ask other people to fill in tests for their areas or at least distribute the work of writing tests.

**Comment by mkArtakMSFT** [comment]
Test matrix / validation work is tracked at https://github.com/dotnet/aspnetcore/issues/39933

**Comment by mkArtakMSFT** [comment]
Closing as all follow-ups are already tracked / in-progress
