### ISSUE TITLE
[.NET 9] Shell Flyout menu not rendering after navigating from a MenuItem page

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#25436]
### Description

Shell Flyout menu not rendering after navigating from a MenuItem page.

### Steps to Reproduce

1. Clone the sample project from the repository
2. With Windows as the target platform, build and run the project
3. Select 'Logout' from the Shell Flyout menu to navigate to the Login screen, which is configured as a MenuItem
4. Click on the 'Login' button to return to the Home page
5. Note that now the Flyout menu is not being displayed

### Link to public reproduction project repository

[egvijayanand/maui-issue-25436](https://github.com/egvijayanand/maui-issue-25436)

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.92 SR9.2

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

Nope

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12.0 Preview 3(9.0.0-rc.2.24503.2 & 9.0.0-rc.1.24453.9). Can repro this issue on windows platform. 8.0.92 works fine.

**Comment by egvijayanand** [comment]
It seems that this issue is not limited to the Windows platform. On Android, the Shell Flyout menu is locked and does not respond to user input after navigating from a MenuItem page.

Validate on the other supported platforms as well.
