### ISSUE TITLE
Ios crash when returning from background

### ISSUE THREAD

**Issue by HeinA** [dotnet/maui#25449]
'ello

I have a MAUI app that crashes on iOS only

It seems to only happen when the app is returning from the background.

Attached is the symolicated crash log.

Any help will be greatly appreciated.

Thanx alot. 

[symbolicated.txt](https://github.com/user-attachments/files/17476525/symbolicated.txt)

**Comment by PureWeen** [comment]
@rolfbjarne anything ring a bell from the txt file?

**Comment by rolfbjarne** [comment]
> Termination Reason: RUNNINGBOARD 0xdead10cc

https://developer.apple.com/documentation/xcode/sigkill

> 0xdead10cc (3735883980) — pronounced “dead lock”
> The operating system terminated the app because it held on to a file lock or SQLite database lock during suspension.
