### ISSUE TITLE
Connectivity NETWORK_CAPABILITIES_CHANGED causing SIGSEGV Segfault?

### ISSUE THREAD

**Issue by RobbiewOnline** [dotnet/maui#25446]
### Description

There's not much to go on here, except sentry.io capturing a segfault early in the application startup on numerous devices (Armor X7 Pro, Pixel 8, Honor X7, Pixel 6 Pro and others, across all Android versions.

![Image](https://github.com/user-attachments/assets/ca63ae36-e21f-4cc3-bb56-793f16645b4b)

![Image](https://github.com/user-attachments/assets/7abeeb5b-0ad7-4d74-b71f-867f08f2411e)

The app is generally running okay, so it seems there's some network event causing it to be triggered which is making it hard to capture.

### Steps to Reproduce

There's none of the usual sentry.io tracking for my app present, so it seems to crash early during the app lifecycle, always just after capturing a network event NETWORK_CAPABILITIES_CHANGED

I am using the MAUI Essentials, primarily the Connectivity.ConnectivityChanged event.

I don't know whether it's related, but I have also noticed previously that registering as a listener sometimes fails too on some devices, because I've witnessed crashes when registering the line marked `<<<<<<`

```
            try
            {
                Connectivity.ConnectivityChanged += Current_ConnectivityChanged; <<<<<<
                Logger.Log(_this, "PageManager - listening for ConnectivityChanged events");
            }
            catch (Exception e)
            {
                Logger.Log(_this, $"PageManager - TODO - UNABLE TO LISTEN FOR CONNECTIVITYCHANGED EVENTS reason {e.Message}");
            }
```

The error was 

```
Exception has occurred: CLR/Java.Lang.SecurityException
An unhandled exception of type 'Java.Lang.SecurityException' occurred in Mono.Android.Runtime.dll: 'com.devology.myteamsafe.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 Android.OS.RemoteException : Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16580)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11530)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2928)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3195)
	at android.os.Binder.execTransactInternal(Binder.java:1375)
<Cannot evaluate the exception stack trace>
```

As far as I know essentials should be doing this behind the scenes anyway? For example in the obj folder I do see manifests with

```
  <permission android:name="com.devology.myteamsafe.app.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" android:protectionLevel="signature" />
  <uses-permission android:name="com.devology.myteamsafe.app.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" />
```

Like I say, I'm not sure whether that's related or not to the crashes.

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Affected platforms

Android

### Affected platform versions

Armor X7 Pro, Pixel 8, Honor X7, Pixel 6 Pro and others, across all Android versions.

### Did you find any workaround?

None - its a segfault that kills the app

**Comment by PureWeen** [comment]
@jonathanpeppers  does this ring any bells?

**Comment by jonathanpeppers** [comment]
It looks to me like Java (Android OS) is throwing this exception:
```
An unhandled exception of type 'Java.Lang.SecurityException' occurred in Mono.Android.Runtime.dll: 'com.devology.myteamsafe.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts'
```

Can you make a quick sample using `Connectivity.ConnectivityChanged` that shows how to cause this? It would also be helpful to know if there is a specific Android OS version this happens on.

It's possible something needs to be changed in MAUI essentials here, but I'm not sure we have enough info to know yet.

**Comment by kellyethridge** [comment]
I'm also experiencing the Segfault error as recorded by Sentry. However, I'm not using the `Connectivity.ConnectivityChanged` event, so I'm not sure how relevant the event is to the error. Also, I'm on .NET 8 MAUI, not 9rc.

**Comment by RobbiewOnline** [comment]
@PureWeen in reply to your questions...

> Can you make a quick sample using `Connectivity.ConnectivityChanged` that shows how to cause this? 

I've added it to my test project that I created to find out why Application.Current.Windows would reset to an empty list.  It simply registers and listens to the connectivity event, with a binding to overlay a panel to indicate when there's no internet.

https://github.com/RobbiewOnline/MauiAppWindowTest

I've run it on a simulator in release mode and toggled wifi without issue, so I'm not sure yet whether I need to put it through a Google Play approval (so it's tested on more devices).  

Judging by Sentry it crashes, but it's not all the time.

> It would also be helpful to know if there is a specific Android OS version this happens on.

As per Sentry for my Beta application...

Armor X7 Pro, Pixel 8, Honor X7, Pixel 6 Pro and others, across all Android versions.

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.12 Preview 5(9.0.0-rc.2.24503.2). Not repro this issue on android emulator(Pixel 8 & Pixel 6 Pro ) and Android device(Google & SM) platform. Debugging was successful, no Exception was detected and no crash.

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.12 Preview 5(9.0.0-rc.2.24503.2). Not repro this issue on android emulator(Pixel 8 & Pixel 6 Pro ) and Android device(Google & SM) platform. Debugging was successful, no Exception was detected and no crash.

**Comment by RobbiewOnline** [comment]
I note the s/try-latest-version tag has been removed, does this mean it's not expected to be fixed?

**Comment by mattleibow** [comment]
Hmm, that was the bot... Not sure if it was supposed to do that.

**Comment by RobbiewOnline** [comment]
> Hmm, that was the bot... Not sure if it was supposed to do that.

Not supposed to add or remove the tag? 🤣

**Comment by PureWeen** [comment]
Yea, I think the bot just removes it if you add a comment.

**Comment by vchelaru** [comment]
We've been seeing this ** a lot** as well in our production app. IT happens on Android 15, 14, 13, 12, 11. It doesn't seem to be related to a particular version.

**Comment by drewrobey** [comment]
We're getting this same error on both .NET 8 and .NET 9. Only occurs on Release builds we've put into Google Play Console for test builds.

As per the OP I'm also using Sentry, the crash report doesn't give much:

```
SIGSEGV: Segfault
Network Event
data: {"upload_bandwidth":37228,"action":"NETWORK_CAPABILITIES_CHANGED","vpn_active":false,"signal_strength":-76,"network_type":"wifi","download_bandwidth":29562}
```

The app stays up for about 10 to 15 seconds, then crashes with the segfault. Sounds like some kind of polling routine checking for network connectivity, despite the fact our app doesn't use any network features whatsoever.

**Comment by drewrobey** [comment]
This isn't complete; bad bot.
