### ISSUE TITLE
Cannot deploy a maui applikation on IOs!

### ISSUE THREAD

**Issue by flogeiger** [dotnet/maui#25451]
### Description

we are not able to assign a Apple Account under Visual Studio Code!
https://developercommunity.visualstudio.com/t/Issue-with-Adding-Apple-Developer-Accoun/10772787?space=22&entry=problem&sort=newest&scope=follow

### Steps to Reproduce

1. Navigate to Tools>Options..
2. go to Xamaring> Apple Accounts
3. Add a Apple Account
4. you get the following error message!
![Image](https://github.com/user-attachments/assets/0c1fdd72-b5d5-4361-91d8-8a45bd9b2908)

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

iOS

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Specifically, this is the ticket you're looking for: https://developercommunity.visualstudio.com/t/Cannot-add-Apple-Account-VS-2002-Enter/10773193

Make sure to upvote it and/or add your details! Thanks!
