### ISSUE TITLE
Documentation: macOS install link redirects

### ISSUE THREAD

**Issue by breyed** [dotnet/maui#25452]
### Description

On https://github.com/dotnet/maui/wiki/, the "macOS Install" link points to https://github.com/dotnet/maui/wiki/macOS-Install, which redirects back to https://github.com/dotnet/maui/wiki/.

There used to be a dedicated page for "macOS Install" that indicated what versions of Xcode was supported by MAUI.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by PureWeen** [comment]
Thank you for letting us know!

Updated link to https://learn.microsoft.com/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=visual-studio-code
