### ISSUE TITLE
Documentation: Contradictory workload versions

### ISSUE THREAD

**Issue by breyed** [dotnet/maui#25454]
### Description

The macOS installation say to use different versions of the MAUI workload, depending on where you look.

1. The [Installation](https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=visual-studio-code) page says in "Install .NET and .NET MAUI workloads" to install the latest stable version via `sudo dotnet workload install maui`, which is currently 8.0.403.
2. However, that same page, in the "Prerequisites" section refers to the [Release Versions](https://github.com/dotnet/maui/wiki/Release-Versions) page, which lists the compatible .NET SDK workload versions. It lists a range of versions from 8.0.100 to 8.0.401.

It's not clear whether dev tools should be set to 8.0.401 or 8.0.403. Getting the version right is important to save time and frustration working around tooling issues. For example xamarin/xamarin-macios#19157 (which has evolved into a MAUI issue), which lists 8.0.402 as a bug workaround. So having clear, unambiguous instruction is very helpful.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

macOS

**Comment by PureWeen** [comment]
@breyed In general .NET MAUI should work for all major releases and the next major release of the .NET SDK. If that isn't true then we will make a note on that table of incompatible versions, or min version.

The table really only lists the combination that we ran our whole set of tests against. 
We don't release a new version of .NET MAUI with each updated dot release of the .NET SDK

I've updated our wiki with a comment at the top to illustrate this. 

Thank you for bringing this to our attention.
