### ISSUE TITLE
Blazor Desktop tenets: DPI awareness

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#2549]
- Need to review guidance from docs of each native WebView component for any best practices
- Also need to consult docs of each UI platform to see if there are best practices we need to follow

**Comment by Eilon** [comment]
Some info on WebView2 DPI awareness in this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/58. This ultimately links to this spec: https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/RasterizationScale.md

We might not have to do anything ourselves here (not sure), but I linked these in case they are relevant.

**Comment by mkArtakMSFT** [comment]
Closing as we have seen no evidence from customers that there are issues related to DPI.
