### ISSUE TITLE
FlyoutPage memory leaks - iOS, MacCatalyst

### ISSUE THREAD

**Issue by banditoth** [dotnet/maui#25505]
### Description

The weak references of FlyoutPage's handlers, controls, references are not being deallocated, and stays in the memory. For more compex views (like having a map and several images on the detail page) two assignment could be enough to crash the application completely.
Issue Affecting .90, .92 versions iOS and macOS for sure, i have not had time to test it on other platforms.

### Steps to Reproduce

Constatly assign a new instance of a FlyoutPage to the Application.Current.MainPage.

### Link to public reproduction project repository

https://github.com/banditoth/Maui.Sample.FlyourPageMemoryleak

### Version with bug

8.0.92 SR9.2

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

macOS, iOS

### Affected platform versions

iOS 18, MacOS 15

**Comment by PureWeen** [comment]
We fixed a lot of this in .NET 9

Can you test on .NET 9?

**Comment by banditoth** [comment]
Hey @PureWeen 

Tested out on .NET 9, the issue is not persists, if i did everything right:

Setting the MainPage on button click with : `Application.Current.Windows[0].Page = new MemoryFlyPage();`
And overriding the `app.xaml.cs`'s with this:
```cs
protected override Window CreateWindow(IActivationState? activationState)
    {
        return new Window(new MemoryFlyPage());
    }
```

**Comment by jfversluis** [comment]
Perfect, seems fixed then. Thanks for letting us know!
