### ISSUE TITLE
Maui.Android debugger is not working correctly Net6 (RC1)

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#2550]
When I set a breakpoint in the Handler of a MAUI control that I'm running on Android, 

![image](https://user-images.githubusercontent.com/17496741/133675360-dd99fbe2-f245-450c-99f0-64692faf5253.png)

the application stops, but it shows nothing but this page

![image](https://user-images.githubusercontent.com/17496741/133675144-1b067e4d-3022-440a-9a74-3b3385a90ad1.png)

The call stack is empty

![image](https://user-images.githubusercontent.com/17496741/133675227-1747af78-e42f-4d3a-8263-60fa70e02c1d.png)

**Comment by humbertojaimes** [comment]
I got the same page and what works for me as a temporary solution for debugging was remove all the target frameworks in the csproj and only keep Android

<TargetFrameworks>net6.0-android;</TargetFrameworks>

**Comment by jsuarezruiz** [comment]
Could you try to update to Preview 10 and share your feedback?.
