### ISSUE TITLE
Menu Bar - ContentPage.MenuBarItems doesn't render on Android?

### ISSUE THREAD

**Issue by antonycartwright** [dotnet/maui#25516]
### Description

According to this article, [https://learn.microsoft.com/en-us/dotnet/maui/user-interface/menu-bar?view=net-maui-8.0](url), making a menu is easy. But for me, it simply does nothing when deployed to my Android phone (but it does work on Windows). Is this a known problem?

Thanks, Antony

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

Android

**Comment by jfversluis** [comment]
The very first line in the linked article says: 

> A .NET Multi-platform App UI (.NET MAUI) menu bar is a container that presents a set of menus in a horizontal row, at the top of an app on Mac Catalyst and Windows.

So this is only supported on the desktop platforms that we support. This is because there is no equivalent available on the mobile operating systems.
