### ISSUE TITLE
iOS development blocked by "Service Unavailable" error

### ISSUE THREAD

**Issue by sjbthfc2** [dotnet/maui#25520]
### Description

Hi MAUI Team,

There is currently a serious blocking issue raised with the Visual Studio team regarding not being able to publish iOS Maui apps due to a "Service Unavailable" error:
[Issue](https://developercommunity.visualstudio.com/t/Cannot-add-Apple-Account-VS-2002-Enter/10773193#T-ND10774886)

This is causing serious blicking issues for lots of developers. I know you do not explicitly cover the VS tooling support, but from a developer/business perspective, this is really hurting the perception of MAUI as a platform that can be trusted for delivering business critical products

Please, if there is anything you can do to unblock thi sissue pleas ehelp s no one seems to be getting much of a response or anything in the way of hopeful communication from the VS team.

Thank you

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All iOS versions

**Comment by Kultman** [comment]
I'm getting heat from clients... some remembering me making the argument for using Maui in the first place... Stuff like this is the worst case scenario...

**Comment by jfversluis** [comment]
Already reported in the right place here: https://developercommunity.visualstudio.com/t/Cannot-add-Apple-Account-VS-2002-Enter/10773193

Not much we can do from this side unfortunately.
