### ISSUE TITLE
sign in to apple give authentication service unavailable in visual studio 2022

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#25531]
### Description

I removed my apple account and when I attempt to re-add I enter my apple id and password and I get an error

when logging in "Authentication Service unavailable"

I uninstalled workloads and reinstalled them.
I deleted possible cache
I used a new maui project
to no avail

Please hel

### Steps to Reproduce

1 - Create a new dot net maui app
2 - got to Tools option Apple
3 - sign in or add an apple account using apple id
4 - observe error appears 

### Link to public reproduction project repository

not applicable

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

iOS

### Affected platform versions

ios 17.2

### Did you find any workaround?

no

**Comment by jfversluis** [comment]
Seems like this is already reported and discussed here: https://developercommunity.visualstudio.com/t/Cannot-add-Apple-Account-VS-2002-Enter/10773193

Please add your upvote and details there. Thanks!
