### ISSUE TITLE
A Grid in a ListView - Why won't it render properly in Android?

### ISSUE THREAD

**Issue by antonycartwright** [dotnet/maui#25533]
### Description

Hi All, I have a really simple setup, shown below in windows:

![Image](https://github.com/user-attachments/assets/5b62424e-076c-4c55-bc9d-0e7a7bb44315)

But in Android, it renders like this (below) for no apparent reason. You can negotiate with it by setting lots of heights and so on, but then other problems come. By the time you've messed with it, it becomes unwealdy.

![Image](https://github.com/user-attachments/assets/773be977-87b7-44a8-a9ff-4bc9181bff04)

Origainally, I had a frame in it also, but it seems that frames make the problem worse in Android.

Here's my code:

> `        <ListView ItemsSource="{Binding Library_Summaries}" SelectionMode="None" BackgroundColor="Transparent">
>             <ListView.ItemTemplate>
>                 <DataTemplate>
>                     <ViewCell>
>                         
>                             <Grid RowDefinitions="*,*" ColumnDefinitions="*,*,*,*" ColumnSpacing="10" RowSpacing="10">
>                                 <Label Grid.Column="0" Grid.Row="0" Grid.ColumnSpan="2" Text="{Binding Name}" Margin="0" Padding="0" FontSize="22" FontAttributes="Bold"/>
>                                 <Label Grid.Column="2" Grid.Row="0" Grid.ColumnSpan="2" Text="{Binding Words_Decks}" Margin="0" Padding="0" HorizontalTextAlignment="End" FontSize="22" FontAttributes="Bold"/>
>                                 <Button Grid.Column="0" Grid.Row="1" Text="Manage Words" Clicked="btnViewWords_Clicked" HorizontalOptions="FillAndExpand"/>
>                                 <Button Grid.Column="1" Grid.Row="1" Text="View Decks" Clicked="btnView_Clicked"/>
>                                 <Button Grid.Column="2" Grid.Row="1" Text="Rename Library" Clicked="btnEdit_Clicked" BackgroundColor="Orange"/>
>                                 <Button Grid.Column="3" Grid.Row="1" Text="Delete Library" Clicked="btnDelete_Clicked" BackgroundColor="Red"/>
>                             </Grid>
>                         
>                     </ViewCell>
>                 </DataTemplate>
>             </ListView.ItemTemplate>
>         </ListView>`

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Android

**Comment by jaosnz-rep** [comment]
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
