### ISSUE TITLE
[Bug] "Path not Legal Form" when creating a MAUI app project from Preview8 templates

### ISSUE THREAD

**Issue by MickBadran** [dotnet/maui#2553]
Hi folks, running vs2022 prev4, with MAUI templates(Preview 8) yields this error when creating a project.

The project files appear to be created and compiles on a vanilla project, however when deploying this error comes up too.

Seems like there's a value missing somewhere.

NB: IF I select the MAUI App project (NOT Prev8) from my list of templates - I get the single App experience.
Works a treat.

Cheers,

Mick

**Comment by Eilon** [comment]
Hi @MickBadran , at exactly what point do you get that error? Are you able to post a screenshot?

**Comment by jfversluis** [comment]
No response for a long time, going to assume this is no longer an issue.
