### ISSUE TITLE
[9.0 RC2, Windows] Windows debugger crashes often with SkiaSharp 3.0 Preview 5.4, works with Preview 4.1

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#25562]
### Description

Windows debugger crashes in the opening screen of my app GnollHack when SkiaSharp is updated to 3.0 Preview 5.4. The game works without debugger. The debugger works when SkiaSharp 3.0 Preview 4.1. is used instead. It does not seem to happen every time, but somewhat randomly.

![Image](https://github.com/user-attachments/assets/fa6d1db9-dd0c-4b05-a2fa-df9328639b22)

![Image](https://github.com/user-attachments/assets/98c899ac-67fb-4a7a-a1be-0f269dcbd5da)

### Steps to Reproduce

1. Build and run the game in https://github.com/hyvanmielenpelit/GnollHackMAUIEasyBuild using a debugger on Windows (make sure that SkiaSharp 3.0 Preview 5.4 is being used)
2. Pretty often when starting the game, the debugger crashes almost immediately upon entering the starting screen

### Link to public reproduction project repository

https://github.com/hyvanmielenpelit/GnollHackMAUIEasyBuild

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.22621

### Did you find any workaround?

No, the debugger crashes always with SkiaSharp 3.0 Preview 5.4. Need to downgrade to Preview 4.1 or Preview 3.1.

**Comment by janne-hmp** [comment]
When I disable hot reload, the debugger works again, so it seems to be incompatibility between debugger, hot reload and SkiaSharp 3.0 Preview 5.4.

**Comment by drasticactions** [comment]
@janne-hmp If you try using that version of SkiaSharp in a WinUI app outside of your app, with or without Hot Reload being enabled, what happens?

CC @spadapet @etvorun

**Comment by janne-hmp** [comment]
I have another test repository with SkiaSharp (https://github.com/hyvanmielenpelit/iOSMauiSkiaSharpMemoryLeak) which can also be used on Windows. It uses SkiaSharp just a little bit, but probably enough anyway. With short testing, things seem to be working fine there with Hot Reload when using SkiaSharp 3.0 Preview 5.4.

The game has a update timer on the starting screen, which might be part of the reason. In any case, the game and the debugger worked fine with an earlier version (3.0 Preview 3.1) of SkiaSharp on Windows.

**Comment by CathyZhu0110** [comment]
Hi @janne-hmp I also couldn't repro this issue on VS 17.12 P5 with MAUI: 9.0.0-rc.2.24503.2 using the [GnollHackMAUIEasyBuild](https://github.com/hyvanmielenpelit/GnollHackMAUIEasyBuild) you provided. I tried about 7 times, no crash. I checked the SkiaSharp 3.0 Preview 5.4 is being used.
