### ISSUE TITLE
no me sale las llaves en esta parte

### ISSUE THREAD

**Issue by Gonzaloogm** [dotnet/maui#25566]
Problem encountered on https://dotnet.microsoft.com/es-es/learn/maui/first-app-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Hey there @Gonzaloogm thanks for your interest in .NET MAUI!

Unfortunately I don't see any details on what you are seeing or what you're running into so I'm not able to provide any guidance. Could you please elaborate a bit more on what is goin wrong? Then we'll try and help you get started successfully. Thanks!

**Comment by Gonzaloogm** [comment]
Cuando intento ejecutar la aplicación no aparencen en el xaml las {} que deberia tener para ejecutar.

**Comment by Gonzaloogm** [comment]
si intento ejecutar un archivo .cs me sale este error: 
''/Users/alumnoad/Tec_Mov/Prueba/MauiApp1/MauiApp1.csproj'' no admite la depuración. No se ha encontrado ningún destino que se pueda iniciar.

**Comment by jfversluis** [comment]
What platform are you trying to deploy to? iOS, macOS, Android? Did you try to deploying to another one, does that work? Do you maybe have a screenshot of what you're seeing?

**Comment by Gonzaloogm** [comment]
Quiero poder seleccionar iOS o Android pero lo que pasa es que no puedo hacerlo a ninguna. Deberían aparecer estos símbolos " {} " y no lo hacen. He intentado seguir el tutorial al pie de la letra pero no funciona

**Comment by Gonzaloogm** [comment]
![Image](https://github.com/user-attachments/assets/3cf3d652-2c8c-410c-8852-027072dd0a72)

**Comment by Gonzaloogm** [comment]
abajo a la izquierda deberían salir {} pero no están

**Comment by jsuarezruiz** [comment]
You need to select a C# class. Once you open a C# file must appear. 
Also, could you share a screenshot of your installed extensions?, do you have already installed also the maui workloads?

**Comment by Gonzaloogm** [comment]
I try to do that but when I click on the {} It says: "MauiApp1 (net8..0-ios) - contexto de archivo activo" and if I try to run it, it deploys this error: ''/Users/alumnoad/Tec_Mov/Prueba/MauiApp1/MauiApp1.csproj'' no admite la depuración. No se ha encontrado ningún destino que se pueda iniciar." Origen: kit de desarrollo de C# extension"

**Comment by jfversluis** [comment]
If you open a terminal in the folder of the project and do `dotnet build -t:Run -f net8.0-ios` does that work?

**Comment by jfversluis** [comment]
And if you do `dotnet build -t:Run -f net8.0-maccatalyst` or `dotnet build -t:Run -f net8.0-android`?

The NSMachErrorDomain seems to indicate some connection error which seems strange. Doesn't really ring a bell for me unfortunately.

**Comment by Gonzaloogm** [comment]
The mac catalyst one works fine, the android gives this error: ![Image](https://github.com/user-attachments/assets/043b4f2b-b949-43e0-9ba3-59a9e5ea8382)

**Comment by Gonzaloogm** [comment]
The thing is that I can't run the project and the {} menu doesn't work, I don't know why

**Comment by Gonzaloogm** [comment]
I checked all the extensions in vs code and all seem to be fine

**Comment by Gonzaloogm** [comment]
It does work with commands but the {} system don't work

**Comment by jfversluis** [comment]
Hey @Gonzaloogm sorry its been a minute. Did you resolve this by any chance?
