### ISSUE TITLE
Maui Android deployment fails with error XABLD7023

### ISSUE THREAD

**Issue by delwarthink** [dotnet/maui#25583]
### Description

Trying to deploy Maui project into the device and see this error:

XABLD7023: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Think Projects\ThinkDroid_MAUI\ThinkDroid\obj\Debug\net8.0-android34.0\android-arm\linked\shrunk\_Microsoft.Android.Resource.Designer.dll'

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

Android

### Affected platform versions

Android api 34 and Windows 2022

**Comment by delwarthink** [comment]
https://github.com/dotnet/maui/issues/23796 was not resolved. That error just magically went away for the author of the issue.

**Comment by ninachen03** [comment]
Could you try to Clean you project and delete the bin/ obj file under your project, then build first, and debug again. If not, please provide the sample project so that we can investigate it further. Looking forward to your reply!
