### ISSUE TITLE
Editor Scaling creating new lines on older iOS versions

### ISSUE THREAD

**Issue by tj-devel709** [dotnet/maui#25581]
### Description

The issue is when an editor is scaled down on older iOS versions, the text splits in the middle and moves on to the next line causing text to seem to disappear.

This issue was believed to be fixed with: https://github.com/dotnet/maui/pull/24859.
Removing the call to SizeThatFits seemed to not cause this scaling issue but it turns out this is only on iOS 17 and up.

On iOS 15.5, the bad editor scaling behavior is still present and on iOS 16.4, it seems that there is still slightly different, but wrong behavior.

### Some things I've tried
* I removed all references to the Placeholder label to see if that subview was doing anything strange and it does not look like this has any effect. Also removing the other calls in LayoutSubviews to UpdatePlaceholderLabelFrame() and ShouldCenterVertically() do not affect this behavior which leads me to believe this issue is happening on the backend of things.
* It seems like the issue may be related to the ContentSize and the Bounds when scaling happens and these could perhaps be differences in how the different iOS versions handle it?

Inside the [MauiTextView.LayoutSubviews](https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/iOS/MauiTextView.cs#L116-L122) method, I am setting a breakpoint and scaling down the editor by 0.5 and then scaling it back up to 1.0. It appears that there are two passes in the LayoutSubviews call and I capture the Bounds and ContentSize. The first image below shows iOS 17.0 and the second shows iOS 15.5.  You'll even see when the editor on iOS 15.5 is at the full scale and appears on one line, it still has a much larger ContentSize.Height than the iOS 17.0 equivalent. 

<img src="https://github.com/user-attachments/assets/e7bc5afb-f229-4199-9e6e-e5279182b8eb" height="400">

<img src="https://github.com/user-attachments/assets/ea6ab848-5b7b-4e81-acf1-5d730a0d7681" height="400">

<p float="left">
  <img src="https://github.com/user-attachments/assets/b82f244d-49d9-45d3-8e9b-50dcc21d5558" width="45%" />
  <img src="https://github.com/user-attachments/assets/2fac5524-ed43-4738-92a8-a450d650d6e4" width="45%" />
</p>

<p float="left">
  <img src="https://github.com/user-attachments/assets/b7b94aed-5ea2-4931-8f47-a79bb0b7549d" width="45%" />
  <img src="https://github.com/user-attachments/assets/8f2274ba-67e3-42fb-8f66-356b8cebd99b" width="45%" />
</p>

### Steps to Reproduce

By adding the following code and then sliding the slider value, you'll see the editor will split the text into two lines on iOS 15.5 but not iOS 17+

```xaml
    <ScrollView>
        <VerticalStackLayout>
            <Slider
                x:Name="mySlider"
                Minimum="0.5"
                Maximum="1"
                Value="1"/>

            <Editor
                x:Name="myEditor"
                Text="1234567890"
                Scale="{Binding Value, Source={x:Reference mySlider}}"
                Background="Red"
                FontSize="32"
                HorizontalOptions="Center"
                HorizontalTextAlignment="Center" />

        </VerticalStackLayout>
    </ScrollView>
```

### Version with bug

8.0.92 SR9.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5 - iOS 16.4

**Comment by tj-devel709** [comment]
To note: this happens in net8 and net9!

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 5(8.0.82 & 9.0.0-rc.2.24503.2). Can repro this issue at iOS platform on 15.5-17.2 .
