### ISSUE TITLE
.net maui help

### ISSUE THREAD

**Issue by graciaheng** [dotnet/maui#25591]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

the option to run as maui isnt available even though i have the .net maui extension installed :(

**Comment by jsuarezruiz** [comment]
Could you provide more details, or logs?

What platform are you trying to deploy to?, do you have the necessary workloads installed?, the MAUI extension for VSCode etc.
