### ISSUE TITLE
Binding context type check fails for relative binding sources

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/maui#25608]
### Description

When we check for `x:DataType` and binding context mismatch when a `Binding` is applied, we compare the `x:DataType` with an instance of `RelativeBindingSource` instead of the resolved source object.

As a result, the runtime log contains misleading warnings:
```
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: Mismatch between the specified x:DataType (Microsoft.Maui.Controls.VerticalStackLayout) and the current binding context (Microsoft.Maui.Controls.RelativeBindingSource).
```

### Steps to Reproduce

Starting from `dotnet new maui`:
 
1. Enable `$(MauiEnableXamlCBindingWithSourceCompilation)` in project file:
```xml
<PropertyGroup>
    <MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>
</PropertyGroup>
```
2. Add a binding with relative source and `x:DataType` to `MainPage.xaml`:
```xml
<VerticalStackLayout Spacing="25">
      <Image
          Source="dotnet_bot.png"
          HeightRequest="{Binding Spacing, x:DataType=VerticalStackLayout, Source={RelativeSource AncestorType={x:Type VerticalStackLayout}}}" />
</VerticalStackLayout>
```

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-rc.2.24503.2

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

**Comment by ne0rrmatrix** [comment]
If using `<MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>` from `origin:main` you this fix does not work. Tested against CommunityToolkit PR for dotnet 9. For relative sources to work I have to set the above to `false`

**Comment by domneedham** [comment]
I am also still seeing this issue, the binding is working fine but the log is filling with the warning of a binding mismatch.

**Comment by simonrozsival** [comment]
@domneedham could you please share a repro app so I can look into it?

**Comment by jeff922** [comment]
I also see this issue with the following snippet:

MainPage.xaml
```
<CollectionView Grid.Column="0"
		          ItemsSource="{Binding CustomList}"
			  SelectedItem="{Binding SelectedItem}"
			  SelectionMode="Single">
	<CollectionView.ItemTemplate>
		<DataTemplate x:DataType="model:CustomItem">
			<Border>
				<Border.GestureRecognizers>
					<TapGestureRecognizer NumberOfTapsRequired="2"
						CommandParameter="{Binding .}"
						Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:MainPageViewModel}}, Path=GoToDetailsCommand}">
					</TapGestureRecognizer>
				</Border.GestureRecognizers>
			</Border>
		</DataTemplate>
	</CollectionView.ItemTemplate>
</CollectionView>
```

MainPageViewModel.cs
```
[RelayCommand]
async Task GoToDetailsAsync(CustomItem itemToView)
{
	// This method is never reached when
	// <MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation> is present
	// if the above is set to false, binding works.
}
```
