### ISSUE TITLE
Only HTTP and HTTPS URLs are supported when opening browser

### ISSUE THREAD

**Issue by RsZoli** [dotnet/maui#25625]
### Description

I'm using ad-hoc distribution on iOS, opening the manifest file from code using "itms-services" protocol:

`await Browser.Default.OpenAsync(new Uri("itms-services://?action=download-manifest&url=" + updateTaskCompletion.Task.Result), BrowserLaunchMode.SystemPreferred);`

It was working fine just a few days ago, however now i got the following error:

ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported.

### Steps to Reproduce

1. Create a new .NET MAUI application
2. Open the default browser from code using any protocol other than "http" or "https"

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jfversluis** [comment]
This is something that originates in iOS and thus something that Apple needs to fix/change. There is nothing we can do unfortunately about this on our side.

**Comment by RsZoli** [comment]
@jfversluis Thank you for your help, i managed to resolve this issue, it was indeed something that i have done!

I use this method on various pages to open content via browser and i always use the "BrowserLaunchMode.SystemPreferred", however in this case i was using "BrowserLaunchMode.External". I have made a change so every method use the "SystemPreferred" flag and that triggered the issue, i reverted is back, to "External" and the "itms-services" protocol is working again!

**Comment by jfversluis** [comment]
@RsZoli glad to see you figured it out! Thanks for letting us know!
