### ISSUE TITLE
iOS App Randomly Crashing with Memory Leak During Large Data Load, Navigation, and Save Operations

### ISSUE THREAD

**Issue by rahulrthor07** [dotnet/maui#25621]
### Description

Our .NET MAUI iOS application crashes randomly when handling large collections of data, saving data, and performing navigation actions. The issue persists even with .NET 9 preview, where memory usage spikes, leading to out-of-memory (OOM) errors and suspected memory leaks.

Steps to Reproduce:

Load a large collection of data into a ListView or CollectionView(also tried with Syncfusion SFListview).
Navigate between pages while keeping the large data collection in memory.
Save data or perform operations on the collection.
After repeated navigation or data operations, observe increased memory usage, leading to eventual app crashes.
Expected Behaviour:

The app should handle large data sets, navigation, and data-saving operations without causing memory issues or crashes.
Actual Behaviour:

Random app crashes occur during data load, save, or navigation.
Memory usage increases consistently without being released, eventually causing OOM errors.

Environment:

.NET MAUI Version: .NET 9 Preview
IDE: Visual Studio 2022 for Mac (or Windows, specify if applicable)
Device/Simulator: iOS 16+ (specify device model if on physical device)

### Steps to Reproduce

Steps to Reproduce:

Load a large collection of data into a ListView or CollectionView(also tried with Syncfusion SFListview).
Navigate between pages while keeping the large data collection in memory.
Save data or perform operations on the collection.
After repeated navigation or data operations, observe increased memory usage, leading to eventual app crashes.

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

9.0.0-rc.2.24503.2

### Affected platforms

iOS

### Affected platform versions

all iOS version 16, 17, 18

### Relevant log output

Main Thread - Crashed
libsystem_kernel.dylib
__pthread_kill
libsystem_c.dylib
abort
QuartzCore
CA::Render::Encoder::grow(unsigned long)
QuartzCore
CA::Render::Encoder::encode_data_async(void const*, unsigned long, void (*)(void const*, void*), void*)
QuartzCore
CA::Render::Image::encode(CA::Render::Encoder*) const
QuartzCore
CA::Render::Layer::encode(CA::Render::Encoder*) const
QuartzCore
CA::Render::encode_set_object(CA::Render::Encoder*, unsigned long, unsigned int, CA::Render::Object*, unsigned int)
QuartzCore
___ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd_block_invoke
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Layer::commit_if_needed(CA::Transaction*, void (CA::Layer*, unsigned int, unsigned int) block_pointer)
QuartzCore
CA::Context::commit_transaction(CA::Transaction*, double, double*)
QuartzCore
CA::Transaction::commit()
QuartzCore
CA::Transaction::flush_as_runloop_observer(bool)
UIKitCore
_UIApplicationFlushCATransaction
UIKitCore
_UIUpdateSequenceRun
UIKitCore
schedulerStepScheduledMainSection
UIKitCore
runloopSourceCallback
CoreFoundation
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
CoreFoundation
__CFRunLoopDoSource0
CoreFoundation
__CFRunLoopDoSources0
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
GraphicsServices
GSEventRunModal
UIKitCore
-[UIApplication _run]
UIKitCore
UIApplicationMain
Viewpoint
0x104708000 + 3636224
Viewpoint
0x104708000 + 6295164
Viewpoint
0x104708000 + 6289276
Viewpoint
0x104708000 + 6242700
Viewpoint
0x104708000 + 6233380
Viewpoint
0x104708000 + 6033492
Viewpoint
0x104708000 + 5688952
Viewpoint
0x104708000 + 5713596
Viewpoint
0x104708000 + 6055208
Viewpoint
0x104708000 + 3681500
Viewpoint
0x104708000 + 6977368
0x0 + 0

**Comment by jsuarezruiz** [comment]
Is something new happens from RC2?, works without issues in RC1?

Do have more detailed logs?

**Comment by rahulrthor07** [comment]
I'm encountering a persistent issue in .NET 8.0 while creating bulk entries in my app. The application randomly crashes when inserting records in bulk, typically after every 10 to 20 records. Unfortunately, there is no clear error message or stack trace to indicate the cause of the crash, which makes debugging challenging.

This issue has occurred across multiple attempts, and it's impacting the app's stability. I wanted to reach out to see if anyone else has experienced similar issues or has suggestions on how to obtain more detailed information to help identify the root cause.

Any advice or insights would be greatly appreciated. Thank you in advance!

**0x1003ac000 + 3636224
SIGABRT** 

Main Thread - Crashed
libsystem_kernel.dylib
__pthread_kill
libsystem_c.dylib
abort
QuartzCore
CA::Render::Encoder::grow(unsigned long)
QuartzCore
CA::Render::Encoder::encode_data_async(void const*, unsigned long, void (*)(void const*, void*), void*)
QuartzCore
CA::Render::Image::encode(CA::Render::Encoder*) const
QuartzCore
CA::Render::Layer::encode(CA::Render::Encoder*) const
Viewpoint
0x100570000 + 3636224
Viewpoint
0x100570000 + 6295164
Viewpoint
0x100570000 + 6289276
Viewpoint
0x100570000 + 6242700
Viewpoint
0x100570000 + 6233380
Viewpoint
0x100570000 + 6033492
Viewpoint
0x100570000 + 5688952
Viewpoint
0x100570000 + 5713596
Viewpoint
0x100570000 + 6055208
Viewpoint
0x100570000 + 3681500
Viewpoint
0x100570000 + 6977368
0x0 + 0

**Comment by jaosnz-rep** [comment]
I can repro this issue at iOS platform on the latest 17.12 Preview 5(9.0.0-rc.2.24503.2 & 8.0.92).

**Comment by mattleibow** [comment]
@jaosnz-rep do you have a sample repo?

**Comment by mattleibow** [comment]
@TargetReacher @rahulrthor07 any sample repos? Does this crash in a new template app?

**Comment by TargetReacher** [comment]
@mattleibow I could not reproduce the error or memory allocation in a sample.

I used [`MemoryToolkit.Maui`](https://github.com/AdamEssenmacher/MemoryToolkit.Maui) and found some memory leak issues with a custom element which was used in my `ItemTemplate` and ended up manually Disconnect the Handlers, implement WeakEventManager and rewrote some parts. 

But I wonder why the memory allocation got so big in the first place.
Changing from a CollectionView to a custom RepeaterView (basically StackLayout with ItemSource, ItemTemplate and some handling code) the memory allocation went down significantly from 3 GB to about 1 GB. This was with .net 8, it is further reduced when using .net 9
The Data itself is just few KB.

Now when the page is removed from the stack everything also frees up correctly.

**Comment by jfversluis** [comment]
Love this investigation here, but without some kind of repro its pretty hard to investigate on our side.
