### ISSUE TITLE
HarmonyOS has a huge market in China, are you considering supporting it?

### ISSUE THREAD

**Issue by bxjg1987** [dotnet/maui#25639]
### Description

In China, HarmonyOS is very important and even receives first level support from the government. It has huge market potential. Should we consider supporting it.
At present, Unity3D has launched a special edition for China and supports HarmonyOS. We hope that Maui can evaluate its support for HarmonyOS.

### Public API Changes

none

### Intended Use-Case

none

**Comment by tjiakwokyung28** [comment]
https://github.com/dotnet/maui/discussions/164

**Comment by tjiakwokyung28** [comment]
https://github.com/dotnet/maui/discussions/15536
