### ISSUE TITLE
MAUI iOS looking for obfuscar imeplementation doesn't works

### ISSUE THREAD

**Issue by rubenmorameneses** [dotnet/maui#25636]
### Description

I want use the Obfuscar Extension (https://marketplace.visualstudio.com/items?itemName=AvinabMalla.obfuscarvs). I reach the goal on MAUI Android, but iOS is alittle bit difficult because I'm trying look for the extension Obfuscar in Visual Studio for Macos, there is no such extension, and in the old way I made in Xamarin doesn't works neither.

###  Steps to Reproduce

1. Instar Visual Studio for Macos
2. Create a basic MAUI app for iOS
3. Click on Visual Studio/ Extensions/ 

![Image](https://github.com/user-attachments/assets/24a426dc-0a24-4b7f-92c5-99c9fcec75dd)

4. Look for "Obfuscar" extension

![Image](https://github.com/user-attachments/assets/8bf1f24d-979a-46a3-bb47-848f3b21c335)

This is my VS version:

![Image](https://github.com/user-attachments/assets/2dba9567-3b5a-4731-960f-f18f2a2a8c4a)

**Comment by drasticactions** [comment]
This is not a MAUI UI issue. You should talk to the [maintainers of that project](https://github.com/obfuscar/obfuscar) if they have a way to integrate that support outside of Windows and Visual Studio. 

Also note that Visual Studio for Mac has been deprecated and is no longer receiving support.
