### ISSUE TITLE
Hot Reload does not seem to work

### ISSUE THREAD

**Issue by seanbo** [dotnet/maui#25637]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/modify
Operating System: windows

I tried to run the ho reload and nothing happened.  I confirmed it was enabled in the debugging settings.  There is also no button for it on my toolbar

**Comment by drasticactions** [comment]
This repo is for the MAUI UI project, and doesn't maintain the Hot Reload tooling. If you move this issue to VS Feedback, the Visual Studio team can help you debug your issue.
