### ISSUE TITLE
Collection View not populating with Observable Collection in Android

### ISSUE THREAD

**Issue by ISSPRO-Eng** [dotnet/maui#25633]
### Description

I have a collection view that is bonded to an observable collection that populates with nearby BT devices. 

### Steps to Reproduce

This is a larger app, so I have not recreated the issue elsewhere. I will gladly share the GitHub repo if needed. This is a mini snippet of the code. 

VIEW
```cs
     if (!ignore)
     {
             try
             {
                         _vm.AvailableDevices.Add(deviceObj);
                         Console.WriteLine(device.Name);
             }
            catch (Exception ex)
            {
                         Console.WriteLine(ex);
            }
     }
```
VIEW MODEL
```cs
        IDevice _device;
        
        public IDevice DeviceInterface { get => _device; }
        public string Name { get => _device.Name; }


          public Device(IDevice device)
        {
            _device = device;
        }
    }
    public class BTDeviceListPopupViewModel : BaseViewModel
    {
        private ObservableCollection<Device> _availableDevices = new ObservableCollection<Device>();
        private bool _isScanning;
        public ObservableCollection<Device> AvailableDevices { get => _availableDevices; 
                                                               set { _availableDevices = value; 
                                                                    OnPropertyChanged(nameof(AvailableDevices)); }  }`
```
### Link to public reproduction project repository

https://github.com/ISSPRO-Eng/MauiProductionProgrammer (Currently Private)(Can make public if needed).

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All Android Devices

### Did you find any workaround?

When I touch/scroll the collection view, it populates with all of the nearby devices. I can clearly see in the code the binding being updated with each device, but it does not show on the screen. This does not happen in iOS devices.

**Comment by jfversluis** [comment]
I can imagine the devices being scanned for happens in a background thread (on Android) and therefore it does not update the UI?

Have you tried adding an extra call to notify the property changed for the event, or invoke the adding of the new device on the main thread?

**Comment by ISSPRO-Eng** [comment]
> I can imagine the devices being scanned for happens in a background thread (on Android) and therefore it does not update the UI?
> 
> Have you tried adding an extra call to notify the property changed for the event, or invoke the adding of the new device on the main thread?

I tried this.

`MainThread.BeginInvokeOnMainThread(() =>
                                    {
                                        _vm.AvailableDevices.Add(deviceObj);
                                        Console.WriteLine(device.Name);
                                    });`. 

I did try an extra call to notify the property changed as well to no avail. Any other options?

**Comment by mattleibow** [comment]
What happens if you replace your item templates with a plain label or something super simple? Maybe it is a row layout issue somehow.

Also, maybe make the repo public if possible.

Another thing to try is to not use real scanning to get devices, just add a fake device on some button click and see if that renders. It may be that the UI is struggling to update from the scanning...
