### ISSUE TITLE
Unable to run a first MAUI app

### ISSUE THREAD

**Issue by BobHD** [dotnet/maui#25641]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Hi,

I have installed VS 2022 17.11.1 and the .NET five Desktop & Mobile components using Window 10 Pro version 1909.

I created a new .NET MAUI project, but when I click on the "Windows Machine" button, I get the following error:

The program '[31932] MyFirstApp.exe' has exited with code 2147942405 (0x80070005)

I enabled the developer mode as asked to.

Any idea how I can solve this?

Thanks.

**Comment by mattleibow** [comment]
Sorry to hear this is happening. If you close and reopen the sln/IDE, does anything change?

Can you select any other platform, such as android?

**Comment by BobHD** [comment]
Hi,

I solved the problem: my Windows version was an old one, 1909.

When trying on a virtual machine using 22H22, it worked. So I upgraded the host to 22H22 too, and it worked.

Thank you for trying to help.
