### ISSUE TITLE
Waiting for debugger to attach error

### ISSUE THREAD

**Issue by ovie-daveth** [dotnet/maui#25648]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: Windows

I am using a Windows 10 hp laptop. I have installed android studio and tried to run my mui app to my emulator, but the emulator is saying the emulator is waiting for the debugger to attach, what could be the cause?

**Comment by jfversluis** [comment]
Hey @ovie-daveth thank you for your interest in .NET MAUI!

Do you see anything in the Visual Studio Output window? Maybe it gives some more information there. Does running the project on Windows work as it should? Is the emulator otherwise working?

**Comment by ovie-daveth** [comment]
Hy, @jfversluis  

Thanks, It is working well now, had to create a new emulator, thanks

**Comment by ovie-daveth** [comment]
@jfversluis 

Thanks,

I Heard there is an inbuilt emulator that comes with mui, it tried to open on my device when I startup the project but it closed automatically, so I am using android studio emulator. Is there a reason why it failed, is there way I can use the inbuilt emulator??

**Comment by jfversluis** [comment]
I'm not entirely sure if I understand what you mean. In Visual Studio we also have a Device Manager with which you can manage the Android Virtual Devices (or emulators), but it shouldn't matter if you create them with Android Studio or Visual Studio.

You can find more information here: https://learn.microsoft.com/dotnet/maui/android/emulator/

If the emulator management in Visual Studio is giving you issues, please report it through Visual Studio. Click the Help menu, then Provide Feedback and Report a Problem. That will make sure it shows up in the right place for the right team.

**Comment by ovie-daveth** [comment]
Alright thanks, I think I meant Device manager, thanks
