### ISSUE TITLE
[Bug] PNG Image set to Application Icon for MAUI Application loses transparency.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/maui#2564]
### Description
When I tried an application that replaces the original svg images from the template for the Application icon for an PNG image with transparency, the resulting macos icon created from that PNG image loses all transparency embedded inside of it when I changed the ``.svg`` to ``.png`` inside of my csproj like so:

```xml
<!-- from the template, we want to use a png image instead for the appicon. -->
<!-- <MauiImage Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" IsAppIcon="true" Color="#512BD4" /> -->
<MauiImage Include="Resources\appicon.png" IsAppIcon="true" />
```

### Steps to Reproduce

1. Create a new MAUI application using the RC.2 .NET SDK.
2. Delete all of the original svg files and the images directory inside of a new project.
3. Pick any png image 256px by 256px with transparency and rename it to ``appicon.png`` and place it under the Resources folder inside of your new .NET MAUI application.
4. Change the csproj to match that xml above.
5. Notice that the transparency goes away when you do not want it to at all. Perhaps ``<MauiImage`` could get an node to configure to preserve transparency (only valid if the image name included ends with ``.png``)?

### Expected Behavior

For the resulting application icon when building the bundle to have it's transparency on the icon preserved.

### Actual Behavior

The Transparency on the icon is replaced with black.

### Basic Information

- Version with issue: 
- Last known good version: None that I know of.
- IDE:
- Platform Target Frameworks: ``net6.0`` for project references, ``net6.0-maccatalyst`` for the MAUI project I am making. 
  - iOS:  None
  - Android: None  
  - UWP:  None 
  - MacOS: v12 (Trying to use it to make a universal application bundle).
- Android Support Library Version: 
- Nuget Packages: Remora.Discord (version ``*-*``), Remora.Discord.Caching (version ``*-*``), IDisposableAnalyzers (version ``*-*`` and for checking my code for forgotten disposables), CsvHelper (version ``*-*``), Microsoft.EntityFrameworkCore (version ``*-*``), and Microsoft.EntityFrameworkCore.Sqlite (version ``*-*``).
- Affected Devices: MacOS

### Screenshots

I do not think it is a visual issue at all (other than what the icon would output as when you look inside the app bundle generated while compiling). I think the easiest way to see it is to follow the repro steps above.

### Reproduction Link

I think the shortest reproduction that I can give you is to follow the reproduction steps above.

### Workaround

Currently I do not know of any workaround other than having a premade icns file that has the transparency and overwrite the one generated when the build creates the application bundle.

**Comment by kristinx0211** [comment]
verified on windows with 32301.586.main.the Transparency on the icon is replaced with black. repro project:
[MauiApp16.zip](https://github.com/dotnet/maui/files/8221906/MauiApp16.zip)

**Comment by mattleibow** [comment]
If this is still an issue after all the resizetizer fixes, a workaround may be to set the Color value to transparent.
