### ISSUE TITLE
Did not run app

### ISSUE THREAD

**Issue by FireCreator418** [dotnet/maui#25659]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I cannot run the app even i put devoleper tools true.

**Comment by FireCreator418** [comment]
Fixed! YDIMDPWIFA

**Comment by jfversluis** [comment]
Thanks for letting us know, have fun building your apps!
