### ISSUE TITLE
Error with Application.Current.Quit

### ISSUE THREAD

**Issue by cty901** [dotnet/maui#25672]
### Description

On the Android platform, as long as the Application.Current.Quit is called anywhere in the APP after quitting the APP, opening the APP again will inevitably relaunch, and I have been unable to open it.

For example, call it in the button event:
```csharp
 private void OnCloseClicked(object sender, EventArgs e)
    {
        Application.Current.Quit();
    }
```

Or call it in a method:
```csharp
private async Task SaveSettings()
{
          // Ensure that it is executed on the main thread
          await MainThread.InvokeOnMainThreadAsync(async () =>
          {
          // Pop up the confirmation dialog and wait for the user to make a selection
          bool confirmed = await DisplayAlert(“Alert”, “Configuration changed successfully, click OK and the APP will close automatically and re-run manually!” , “OK”, “Cancel”);

            if (confirmed)
            {
                Application.Current.Quit();
            }
        });
    }
```

---

Original message:

### Description

在安卓平台上，只要在APP中任何地方调用了Application.Current.Quit退出APP后，再次打开APP就必然闪退，而且一直就无法打开了。

比如，在按钮事件中调用：
    private void OnCloseClicked(object sender, EventArgs e)
    {
        Application.Current.Quit();
    }
或者在某个方法中调用：
    private async Task SaveSettings()
    {
        // 确保在主线程上执行
        await MainThread.InvokeOnMainThreadAsync(async () =>
        {
            // 弹出确认对话框，等待用户选择
            bool confirmed = await DisplayAlert("提示", "配置修改成功，点击确定后APP将自动关闭，手动重新运行！", "确定", "取消");

            if (confirmed)
            {
                Application.Current.Quit();
            }
        });
    }

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

Android

**Comment by ninachen03** [comment]
I cannot repro this issue at android platform on the latest 17.12.0 Preview 5.0(8.0.92 & 8.0.82). It works fine on our side, could you please help confirm that our repro steps are correct? If not, please provide a sample project. Below is my project and Screen Recording
[MauiApp29 (2).zip](https://github.com/user-attachments/files/17629320/MauiApp29.2.zip)

![Image](https://github.com/user-attachments/assets/c91d3d63-49b8-4325-9e90-8304c90a70d2)
