### ISSUE TITLE
[WinUI] Editor width is not updated when setting styles for native view

### ISSUE THREAD

**Issue by Lakshminatarajan** [dotnet/maui#25684]
### Description

We are using editor with custom style to disable the border of the editor. This customization affects the border to be width to be filled to the available screen width. The editor layout to the placeholder's size.

```

  public class CustomStyleEditor : Editor

    {

#if WINDOWS
 
        private void ApplyTextBoxStyle(Microsoft.UI.Xaml.Controls.TextBox? textbox)

        {

            var textBoxStyle = new Microsoft.UI.Xaml.Style(typeof(Microsoft.UI.Xaml.Controls.TextBox));

            textBoxStyle.Setters.Add(new Microsoft.UI.Xaml.Setter() { Property = Microsoft.UI.Xaml.Controls.Control.BorderBrushProperty, Value = new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(0, 0, 0, 0)) });

            textBoxStyle.Setters.Add(new Microsoft.UI.Xaml.Setter() { Property = Microsoft.UI.Xaml.Controls.Control.BorderThicknessProperty, Value = new Thickness(0) });
 
            textbox!.Resources.Add(typeof(Microsoft.UI.Xaml.Controls.TextBox), textBoxStyle);

        }

#endif
 
    }
 
```

**Actual output**
![Image](https://github.com/user-attachments/assets/c54eae93-f3d3-4694-8d88-3aa70f95510a)

Expected output:
![Image](https://github.com/user-attachments/assets/334c2048-9511-4447-b980-5695083a3798)

**Note: Previously the issue occurred in v8.0.90. This has been resolved in the latest release, version 8.0.92. But it again is not working in .NET 9.0.0-rc.1.24431.7 and 9.0.0-rc.2.24503.2.** 

### Steps to Reproduce

1. Run the attached sample.
2. Notice editor width issue.

### Link to public reproduction project repository

https://github.com/Lakshminatarajan/MAUIEditorIssue

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.92 SR9.2

### Affected platforms

Windows

### Did you find any workaround?

No.

**Comment by jaosnz-rep** [comment]
I can repro this issue at Windows platform on the latest 17.12.0 preview 5(9.0.0-rc.2.24503.2), but it used to work in 8.0.92.
