### ISSUE TITLE
[Bug] Assembly References Get Added to Every Platform TFM

### ISSUE THREAD

**Issue by LanceMcCarthy** [dotnet/maui#2568]
### Description

If you add an assembly reference to one TFM's Dependencies, it gets added to every TFM's Dependencies.

### Steps to Reproduce

1. Right click on Android's Dependencies
2. Add a new assembly reference (a local DLL, not a NuGet package)
3. Observe the assembly was also added to every TFM's dependencies (iOS, MacCatalyst and WinUI)

### Expected Behavior

The added assembly references should only be added to the selected TFM, not to all the TFMs

### Actual Behavior

![image](https://user-images.githubusercontent.com/3520532/133834745-0407a58f-0644-420a-81d3-fe8db57a3c7f.png)

### Basic Information

- Version with issue: NET6-RC1
- Last known good version: unknown
- IDE: VS 2022 Preview 4

### Workaround

None determined. If you remove an assembly reference form one project, it also gets removed from the other TFM dependencies.

**Comment by drasticactions** [comment]
This isn't strictly a MAUI issue, but how Visual Studio and .NET 6 works with multiple TFMs and would happen with any project, I believe. Multiple target frameworks are not a MAUI-specific feature.

If you look in a csproj generated by MAUI, you can see it has condition statements for Nuget packages for different TFMs.

```
<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
		<!-- Required - WinUI does not yet have buildTransitive for everything -->
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0-experimental1" />
		<PackageReference Include="Microsoft.WindowsAppSDK.Foundation" Version="1.0.0-experimental1" />
		<PackageReference Include="Microsoft.WindowsAppSDK.WinUI" Version="1.0.0-experimental1" />
		<PackageReference Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="1.0.0-experimental1" NoWarn="NU1701" />
	</ItemGroup>
```

The same thing could be used for assembly references as well. Although I would say that none of the current tooling in Visual Studio makes any of this obvious, for NuGet or Dependency references. For that, I would file feedback against Visual Studio.

**Comment by LanceMcCarthy** [comment]
I'll file with VS.

Indeed, the reason I even brought this up is that I see VS handles NuGet package platforms correctly. When you add a NuGet package for MAUI, it will properly create the individual TFM sections and then define the platform specific resource (dlls) within.

In the mean, I'll manually edit the csproject with DLLs for each specific TFM. Thanks!

**Comment by LanceMcCarthy** [comment]
Whoops, sorry @jsuarezruiz I closed this because I didn't see your tag. Reopening so that you all can handle whether it should be open or closed.

**Comment by Eilon** [comment]
It sounds like @LanceMcCarthy files this through VS Feedback as well, which is the best way forward for this issue, because that's where the fix would be. So, closing this issue here because there is no action for the .NET MAUI team.
