### ISSUE TITLE
[testing] Some builds hang when running iOS samples or template tests

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#25695]
### Description

We see a number of builds that just hang with no real info. 

These are runnining on some ARM machines and we are not sure if this is still related with it . 

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10505585&view=ms.vss-test-web.build-test-results-tab&runId=115263604&resultId=100003&paneView=attachments

### Steps to Reproduce

Are they just hitting a 15minute timeout limit ? 

![Image](https://github.com/user-attachments/assets/b277c759-acca-44ea-a1f2-4dfa430b7491)

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by rmarinho** [comment]
@rolfbjarne any ideas how we can debug this, why is tking 15 minutes for just a sim dotnet run ?

**Comment by rolfbjarne** [comment]
Not much we can do without knowing exactly where it's stuck (if it's stuck at all, or just hitting the timeout).
