### ISSUE TITLE
OnNavigatingFrom called even if not navigating back on swipe in IOS

### ISSUE THREAD

**Issue by dzebas** [dotnet/maui#25699]
### Description

Hi,

In my app I've a "hack" to fix issue described [here](https://github.com/dotnet/maui/pull/25004)

Basically on certain pages when navigating to page I hide Shell TabBar and when navigating back I show it as per below:

```
    protected override void OnNavigatedTo( NavigatedToEventArgs args )
    {
        base.OnNavigatedTo( args );
        Shell.SetTabBarIsVisible( this, false );
    }

    protected override void OnNavigatingFrom( NavigatingFromEventArgs args )
    {
        base.OnNavigatingFrom( args );
        Shell.SetTabBarIsVisible( this, true );
    }
```

Problem is in iOS OnNavigatingFrom is called straight away when you start swiping back. If you release swipe and it doesn't actually navigate back this method is still getting called, which I think it's incorrect behaviour e.g it should only call this method if you are actually navigating back?

### Steps to Reproduce

1. Create new MAUI app
2. Create new page and implement OnNavigatingFrom:
```
   protected override void OnNavigatingFrom( NavigatingFromEventArgs args )
    {
        base.OnNavigatingFrom( args );
    }
```
and put a breakpoint inside this method.

3. Run this app in IOS simulator or device
4. Navigate to this page
5. Start swiping back, break point will be hit straight away

### Version with bug
8.0.92 SR9.2

**Comment by jaosnz-rep** [comment]
This issue can't be reproduced at iOS platform on the latest 17.12 Preview 5.
