### ISSUE TITLE
drawing text is not same as in winform with same font and font size?

### ISSUE THREAD

**Issue by ljzj2** [dotnet/maui#25703]
I am drawing text using winform and .net android
in winform I use graphics and bitmap and in .net android I use Canvas and Paint.
the font is Arial and the font size is 12
and in winform I set `TextRenderingHint` to `AntiAliasGridFit` and `CompositingQuality` to `SystemDefault` and `SmoothingMode` to `None`
in .net android I also set the antialise.

winform is using .net framework and run in windows 10.
.net android is using .net 8 
in winform (Zoomed)
![Image](https://github.com/user-attachments/assets/39139cb7-12a8-43c7-8cc4-bd1d7721bd09)

in .net android (Zoomed):
![Image](https://github.com/user-attachments/assets/5bc21639-41cf-48c5-b610-5d64861e6894)

why it is not same? with same font ?

**Comment by ljzj2** [comment]
any updates?

**Comment by mattleibow** [comment]
Not sure which one you want?

You said you are setting "in .net android I also set the antialise." which means it will antialias and smooth things out. If you want it to no do that, you should set AntiAlias to false.
