### ISSUE TITLE
[Bug] VS2022 Preview 4 won't create working MAUI apps

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/maui#2571]
### Description
When I create a new MAUI app, I get the following

```
Error	XA1018	Specified AndroidManifest file does not exist: C:\Users\x\source\repos\MauiApp9\MauiApp9\MauiApp9\AndroidManifest.xml.	MauiApp9	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.100-rc.1.12\tools\Xamarin.Android.Common.targets	509	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst	MauiApp9	C:\Users\x\source\repos\MauiApp9\MauiApp9\MauiApp9\MauiApp9.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst	MauiApp9	C:\Users\x\source\repos\MauiApp9\MauiApp9\MauiApp9\MauiApp9.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst	MauiApp9	C:\Users\x\source\repos\MauiApp9\MauiApp9\MauiApp9\MauiApp9.csproj	1	
Warning	MSB3779	The processor architecture of the project being built "Any CPU" is not supported by the referenced SDK "Microsoft.VCLibs.Desktop, Version=14.0". Please consider changing the targeted processor architecture of your project (in Visual Studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, x64, ARM, ARM64".	MauiApp9.WinUI	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	2586	
Warning	MSB3779	The processor architecture of the project being built "Any CPU" is not supported by the referenced SDK "Microsoft.UniversalCRT.Debug, Version=10.0.19041.0". Please consider changing the targeted processor architecture of your project (in Visual Studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, x64, ARM, ARM64".	MauiApp9.WinUI	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	2586	
Warning	MSB3779	The processor architecture of the project being built "Any CPU" is not supported by the referenced SDK "Microsoft.VCLibs, Version=14.0". Please consider changing the targeted processor architecture of your project (in Visual Studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, x64, ARM, ARM64".	MauiApp9.WinUI	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	2586	
```

### Other info

I tried MAUI-CHECK, which gave the following output

```
PS C:\WINDOWS\system32> maui-check
      _   _   _____   _____     __  __      _      _   _   ___
     | \ | | | ____| |_   _|   |  \/  |    / \    | | | | |_ _|
     |  \| | |  _|     | |     | |\/| |   / _ \   | | | |  | |
  _  | |\  | | |___    | |     | |  | |  / ___ \  | |_| |  | |
 (_) |_| \_| |_____|   |_|     |_|  |_| /_/   \_\  \___/  |___|

¤ .NET MAUI Check v0.8.6.0 ¤
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
This tool will attempt to evaluate your .NET MAUI development environment.
If problems are detected, this tool may offer the option to try and fix them for you, or suggest a way to fix them
yourself.

Thanks for choosing .NET MAUI!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
» Synchronizing configuration... ok
» Scheduling appointments... ok

> OpenJDK 11.0 Checkup...
  - 11.0.12 (C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\..)
  - 1.8.0-25 (C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25)
  - 11.0.10 (C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot\bin\..)
  - 15 (C:\Program Files\Common Files\Oracle\Java)

> Visual Studio 17.0.0-pre.4.0 Checkup...
  - 16.10.4
  - 16.11.2
  - 17.0.0-pre.4.0 - C:\Program Files\Microsoft Visual Studio\2022\Preview

> Android SDK Checkup...
  - emulator (30.8.4)
  - build-tools;31.0.0 (31.0.0)
  - platforms;android-31 (1)
  - system-images;android-31;google_apis;x86_64 (8)
  - platform-tools (31.0.3)
  - cmdline-tools;3.0 (3.0)

> Android Emulator Checkup...
  - Emulator: pixel_2_pie_9_0_-_api_28 found.

> .NET SDK Checkup...
  - 3.1.413 - C:\Program Files\dotnet\sdk\3.1.413
  - 5.0.104 - C:\Program Files\dotnet\sdk\5.0.104
  - 5.0.207 - C:\Program Files\dotnet\sdk\5.0.207
  - 5.0.302 - C:\Program Files\dotnet\sdk\5.0.302
  - 5.0.303 - C:\Program Files\dotnet\sdk\5.0.303
  - 5.0.400 - C:\Program Files\dotnet\sdk\5.0.400
  - 6.0.100-rc.1.21458.32 - C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32

> .NET SDK - Workload Deduplication Checkup...

> Edge WebView2 Checkup...
  - Found Edge WebView2 version 93.0.961.47

> .NET SDK - Workloads (6.0.100-rc.1.21458.32) Checkup...
  - android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 31.0.100-rc.1.12) installed.
  × ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-rc.1.1534) not installed.
  × maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-rc.1.1534) not installed.
  - tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-rc.1.1534) installed.
  - macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-rc.1.1534) installed.
  × maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-rc.1.1608) not installed.
  - wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-rc.1.21451.13) installed.
  - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-rc.1.21430.3) installed.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
¤ Recommendation: Install or Update SDK Workloads
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

! Attempt to fix? [y/n] (y):
```

Attempting to fix gave the following output (with errors)

```
» Attempting to fix: .NET SDK - Workloads (6.0.100-rc.1.21458.32)
SHELL: C:\Program Files\dotnet\dotnet.exe workload update --no-cache --disable-parallel --from-rollback-file "C:\Users\x\AppData\Local\Temp\maui-check-321a8d4d\workload.json" --source "https://api.nuget.org/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.1.21458.32-shipping/nuget/v3/index.json"

Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.workload.mono.toolchain.

Successfully updated workload(s): android-aot macos tvos wasm-tools.

SHELL: C:\Program Files\dotnet\dotnet.exe workload install --no-cache --disable-parallel android-aot ios maccatalyst tvos macos maui wasm-tools --skip-manifest-update --source "https://api.nuget.org/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.1.21458.32-shipping/nuget/v3/index.json"

Downloading Microsoft.iOS.Sdk.Msi.x64 (15.0.100-rc.1.1531)
Downloading Microsoft.iOS.Sdk.Msi.x64 (15.0.100-rc.1.1531)
Workload installation failed. Rolling back installed packs...
Downloading Microsoft.iOS.Sdk.Msi.x64 (15.0.100-rc.1.1531)
Installation rollback failed: One or more errors occurred. (microsoft.ios.sdk.msi.x64::15.0.100-rc.1.1531 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.1.21458.32-shipping/nuget/v3/index.json".)
Workload installation failed: One or more errors occurred. (microsoft.ios.sdk.msi.x64::15.0.100-rc.1.1531 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.1.21458.32-shipping/nuget/v3/index.json".)
Description:
  Install one or more workloads.

Usage:
  dotnet [options] workload install [<WORKLOAD_ID>...]

Arguments:
  <WORKLOAD_ID>  The NuGet package ID of the workload to install.

Options:
  --sdk-version <VERSION>                  The version of the SDK.
  --configfile <FILE>                      The NuGet configuration file to use.
  -s, --source <SOURCE>                    The NuGet package source to use during the restore. To specify multiple sources, repeat the option.
  --skip-manifest-update                   Skip updating the workload manifests.
  --from-cache <from-cache>                Complete the operation from cache (offline).
  --download-to-cache <download-to-cache>  Download packages needed to install a workload to a folder that can be used for offline installation.
  --include-previews                       Allow prerelease workload manifests.
  --temp-dir <temp-dir>                    Specify a temporary directory for this command to download and extract NuGet packages (must be secure).
  --disable-parallel                       Prevent restoring multiple projects in parallel.
  --ignore-failed-sources                  Treat package source failures as warnings.
  --no-cache                               Do not cache packages and http requests.
  --interactive                            Allows the command to stop and wait for user input or action (for example to complete authentication).
  -v, --verbosity <LEVEL>                  Set the MSBuild verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
  -?, -h, --help                           Show command line help.

Fix failed - Workload Install failed: `dotnet workload install --no-cache --disable-parallel android-aot ios maccatalyst
tvos macos maui wasm-tools --skip-manifest-update --source "https://api.nuget.org/v3/index.json" --source
"https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.1.21458.32-shipping/nuget/v3/index.json"`
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


! There were one or more problems detected.
Please review the errors and correct them and run maui-check again.

Press enter to exit...
```

**Comment by Gsonovb** [comment]
hi
It is recommended to uninstall and reinstall vs2022
In the installation options, select mobile development, which has a Maui option.
I remember incompatible changes in workloads,
The following directories need to be deleted manually
C:\Program Files\dotnet\metadata\workloads
It is recommended to uninstall all preview versions of. Net 6

**Comment by mrpmorris** [comment]
Unfortunately, that didn't fix it.

Now when I create a new Maui app I see MauiApp10 and MauiApp10.WinUI, no other projects, and both of those say `(unloaded)`

**Comment by Gsonovb** [comment]
Hi 
I created a new Maui project with vs2022preview4. There is only one project
The windows part has been integrated, but you need to modify the project file and uncomment the part.

I didn't use the "Maui check" tool. It wasn't updated when I downloaded the preview version.


I have experienced workload installation problems,
The way to find it is to delete all files in the directory `C:\Program Files\dotnet\metadata\workloads` and then reinstall  `dotnet workload install maui`.
Vs2022 preview4 has provided Maui workload project, so maui-chip is not required



refer to the [installation documentation](https://docs.microsoft.com/zh-cn/dotnet/maui/get-started/installation)

**Comment by Broussd** [comment]
The above worked for me... thanks Gsonovb

**Comment by mrpmorris** [comment]
Determining projects to restore...
C:\Program Files\dotnet\packs\Microsoft.MacCatalyst.Sdk\15.0.100-rc.1.1534\targets\Xamarin.Shared.Sdk.targets(1065,3): error : The RuntimeIdentifier 'iossimulator-x64' is invalid. [C:\Users\x\source\repos\MauiApp12\MauiApp12\MauiApp12\MauiApp12.csproj]

Build FAILED.

C:\Program Files\dotnet\packs\Microsoft.MacCatalyst.Sdk\15.0.100-rc.1.1534\targets\Xamarin.Shared.Sdk.targets(1065,3): error : The RuntimeIdentifier 'iossimulator-x64' is invalid. [C:\Users\x\source\repos\MauiApp12\MauiApp12\MauiApp12\MauiApp12.csproj]
    0 Warning(s)

**Comment by Gsonovb** [comment]
Sorry @mrpmorris 
I don't have an IOS compilation environment. There is no error in this runtimeidentifier. It may be that the Mac computer needs to update the. Net SDK

**Comment by jamesmontemagno** [comment]
There is a powershell script you can run https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1 that will clean you machine.

Uninstall VS 2022
Run script
Re-install VS 2022 + extensions

Should be working smoothly. 

Also you should double check that you didn't accidentally have old nuget feeds in the CLI. Make sure you see the purple icons on file new else you need to manually install the latest templates https://www.nuget.org/packages/Microsoft.Maui.Templates/6.0.100-rc.1.1608

**Comment by acaliaro** [comment]
> There is a powershell script you can run https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1 that will clean you machine.
> 
> Uninstall VS 2022
> Run script
> Re-install VS 2022 + extensions
> 
> Should be working smoothly.
> 
> Also you should double check that you didn't accidentally have old nuget feeds in the CLI. Make sure you see the purple icons on file new else you need to manually install the latest templates https://www.nuget.org/packages/Microsoft.Maui.Templates/6.0.100-rc.1.1608

Hi @jamesmontemagno 
It's not so simple...
Every time I reinstall VS2022 I have different problems.
Already sent logs to Microsoft..

**Comment by mrpmorris** [comment]
I'm disappointed I can't even try this out :(

**Comment by DevCisse** [comment]
> There is a powershell script you can run https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1 that will clean you machine.
> 
> Uninstall VS 2022
> Run script
> Re-install VS 2022 + extensions
> 
> Should be working smoothly.
> 
> Also you should double check that you didn't accidentally have old nuget feeds in the CLI. Make sure you see the purple icons on file new else you need to manually install the latest templates https://www.nuget.org/packages/Microsoft.Maui.Templates/6.0.100-rc.1.1608
Hi @jamesmontemagno 
I have followed the instructions in your video, the project builds, but I can't an emulator. It says incompatible jdk.

**Comment by jamesmontemagno** [comment]
@DevCisse  make sure to install JDK 11 and make sure it is set properly -> https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation#android

**Comment by DevCisse** [comment]
> @DevCisse make sure to install JDK 11 and make sure it is set properly -> https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation#android

Thanks James.
I am not sure what happened. But I had to install Xamarin Workload in VS 2019 and I created an emulator there. I then came to VS 2022 and was able to run it.

**Comment by hawkerm** [comment]
I think I also hit this issue?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	XA1018	Specified AndroidManifest file does not exist: ...\AndroidManifest.xml.	App.Mobile	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.100-rc.1.12\tools\Xamarin.Android.Common.targets	509	
```

Clicking on 'XA1018' goes to a 404 page on the docs.

**Comment by jfversluis** [comment]
This is quite some previews ago. I am going to close this one for now. If someone is still running into this with the latest preview bits please open something new with all the details. Thanks!

**Comment by pdinbkk** [comment]
Gerald, there is still an issue with VS2022 Preview 6 - fresh install with Maui selected, when creating a new Maui Blazor App.  The scaffolding completes, but the project is not buildable:
Build started...
1>------ Build started: Project: fcBlazorMaui, Configuration: Debug Any CPU ------
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Failed to restore C:\Users\Admin\source\repos\fcBlazorMaui\fcBlazorMaui\fcBlazorMaui.csproj (in 26 ms).
1>C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maui-android
1>C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload install maui-android
1>Done building project "fcBlazorMaui.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maui-ios
1>C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload install maui-ios
1>Done building project "fcBlazorMaui.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maui-maccatalyst
1>C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload install maui-maccatalyst
1>Done building project "fcBlazorMaui.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maui-windows
1>C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload install maui-windows
1>Done building project "fcBlazorMaui.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
![image](https://user-images.githubusercontent.com/14819955/153754591-3a5beddb-b977-441c-aeab-1f359b53ab2d.png)

**Comment by jfversluis** [comment]
@pdinbkk it seems to complain you didn't install the maui workload(s). You mention fresh install, that means a completely fresh Windows installation, or you uninstalled VS and reinstalled that? Or did you do more?

**Comment by pdinbkk** [comment]
I uninstalled VS and then did a full reinstall with all the components selected.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by pdinbkk** [comment]
I didn't do that.  Will give try that on one of the machines now.

**Comment by pdinbkk** [comment]
Problem solved.  Removed all .Net 6 previews with the dotnet-core-uninstall tool, removed VS2022, rebooted and re-installed.  New MAUI Blazor project scaffolds and builds without error.

**Comment by jfversluis** [comment]
Perfect, glad you figured it out!
