### ISSUE TITLE
NU1100  & NU1103  396 erreurs je ne sais plus quoi faire

### ISSUE THREAD

**Issue by jlm1309** [dotnet/maui#25714]
NU1103 Package stable Microsoft.Maui.Controls avec la version (>= 8.0.82) introuvable
  - Version(s) 1 trouvée(s) dans Microsoft Visual Studio Offline Packages [version la plus proche : 9.0.0-rc.2.24503.2]
  - Les versions de C:\Program Files\dotnet\library-packs n'ont pas été prises en compte
  - Les versions de Package source n'ont pas été prises en compte

NU1100 Impossible de résoudre 'Microsoft.NET.ILLink.Tasks (>= 8.0.10)' pour 'net8.0-android34.0'. PackageSourceMapping est activé, les sources suivantes n'ont pas été prises en compte : C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, Package source.

**Comment by jlm1309** [comment]
oui c'est le même problème

**Comment by jfversluis** [comment]
@jlm1309 do I understand correctly that the suggested issue is the same as what you are seeing? Did that also resolve it for you?

**Comment by jlm1309** [comment]
‌Yes This is the same issue .
Best Regards
 

De : "Gerald Versluis"
A : "dotnet/maui" ,"jlm1309" ,"Mention"
Envoyé: vendredi 8 Novembre 2024 13:22
Objet : Re: [dotnet/maui] NU1100 & NU1103 396 erreurs je ne sais plus quoi faire (Issue #25714)
 

 

@jlm1309 do I understand correctly that the suggested issue is the same as what you are seeing? Did that also resolve it for you?

**Comment by mattleibow** [comment]
This version is on nuget: https://www.nuget.org/packages/Microsoft.Maui.Controls/8.0.82

The error says:

> PackageSourceMapping is enabled, the following sources were not considered: C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, Source Package.

It appears that you have not added the Microsoft.Maui packages to your source mappings. Did you enable this feature?

**Comment by mattleibow** [comment]
Can you follow this guide and turn it off?

https://learn.microsoft.com/nuget/consume-packages/package-source-mapping#enable-by-using-visual-studio-options-dialog

Specifically, what does this UI say here:

![Image](https://github.com/user-attachments/assets/04c0400d-3577-498d-a559-35a671c5ec15)
