### ISSUE TITLE
"ObjectDisposedException" When Toggling Header/Footer in CollectionView Dynamically

### ISSUE THREAD

**Issue by praveenkumarkarunanithi** [dotnet/maui#25724]
### Description

When dynamically toggling the header or footer in a CollectionView by setting it to null and then re-assigning it, a System.ObjectDisposedException occurs. The exception message indicates that a disposed object. 

"Make sure that in the MauiProgram file, the CollectionView2 handlers are not registered or used."

### Steps to Reproduce

1. Open and run the attached CollectionView sample code in sandbox project.
2. Click the "Toggle Header" button once and observe that the header is removed from the UI.
3. Click the "Toggle Header" button again to re-add the header to the CollectionView.
4. Observe that an exception is thrown at this point.

### Version with bug

8.0.92 SR9.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

**Comment by praveenkumarkarunanithi** [comment]
Issue reproduced with iOS 18.1 in iphone 16 with maui sandbox project code removed in MauiProgram on the sandbox app that uses the CollectionView2 Handlers.
[CollectionViewHeaderException.zip](https://github.com/user-attachments/files/17657563/CollectionViewHeaderException.zip)

**Comment by jaosnz-rep** [comment]
I can repro this issue at macOS platform on the latest VS Code for Mac(1.95.1)(9.0.0-rc.2.24503.2 & 8.0.92).
![Image](https://github.com/user-attachments/assets/f3f6c98f-1602-497d-a34a-93674cf1e96c)
