### ISSUE TITLE
[NAA] Enable disable Exchange Legacy Tokens in your tenant 

### ISSUE THREAD

**Issue by ozgrozo** [dotnet/maui#25733]
On the devblogs : https://devblogs.microsoft.com/microsoft365dev/updates-on-deprecating-legacy-exchange-online-tokens-for-outlook-add-ins/?commentid=1131

You say, "We’ll provide tooling for administrators to reenable Exchange tokens for tenants and add-ins if those add-ins are not yet migrated to NAA." What kind of tool is it? How can I get access to it?

**Comment by jfversluis** [comment]
I'm not sure how this issue ended up in this repository, but I don't think this is relevant to .NET MAUI 😄
