### ISSUE TITLE
Publishing MAUI App to the Store - The newly created provisioning profile is not listed, but the old ones are, and the "Download manual profiles" process has been done from Xcode

### ISSUE THREAD

**Issue by Raul-fc** [dotnet/maui#25741]
### Description

I am trying to publish my MAUI app, but the newly created provisioning profile is not showing up, although the old ones that are about to expire are listed. I have Xcode 16, Visual Studio 2022, and Visual Studio Code installed.

I followed the process of 'Request a certificate from a certificate authority' from Keychain Access, then created the distribution certificate, identifier, provisioning profile, and created the app in App Store Connect.

Then, from Xcode, I linked my account and performed the "download manual profiles" process.

I created a MAUI project in Visual Studio 2022 and another one in Visual Studio Code using the '.NET MAUI - Archive / Publish tool' extension, and added 'ApplicationTitle', 'ApplicationId', and 'ApplicationGuid' in the .csproj file.

Then, from Visual Studio 2022, in the properties under iOS, Bundle Signing, I tried adding the 'Signing Identity', but the created provisioning profile does not show up in the Provisioning Profile section.

![Image](https://github.com/user-attachments/assets/1c7d7f75-7639-441c-9627-49bcf4cda64d)
[](url)

In VSCode, after running 'Maui Archive: Publish iOS', selecting the .csproj, and choosing a signing identity, the newly created provisioning profile is also not shown

![Image](https://github.com/user-attachments/assets/82e1479f-9150-41e8-ab68-41ff459d9ba5)

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

iOS

**Comment by jfversluis** [comment]
This is a tooling issue and not something that originates in the .NET MAUI SDK. Unfortunately, there is not much we can do from our team about this. See the comment above for instructions on how to report this to the right team so it will be handled appropriately, thanks!

**Comment by MarcoErlwein** [comment]
I have the same problem, with old certificates and provision profiles there is no problem, it's just new ones.  What other way is there now to generate the Bundled and send it to Testflight? thank you
