### ISSUE TITLE
What is the status of the Editor control for iOS when using multi-line?

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#25759]
### Description

Editor is completely broken in iOS for multi-line text. This means any app that requires a multi-line text input still cannot launch with Maui in iOS. This is an absolutely core and critical component in Maui. 

Here is the timeline of [the issue](https://github.com/dotnet/maui/issues/17757):

- [Issue ](https://github.com/dotnet/maui/issues/17757) was reported with reproduction project Sep 30, 2023 (14 months ago)
- @samhouts quickly marked it as p/1 on Oct 10, 2023 (13 months ago)
- @mikeparker104 adjusted the tags on Oct 10, 2023
- @samhouts added it to the .NET 8 SR2 target Oct 13, 2023
- @Eilon adjusted the tags Oct 17, 2023
- @pureween verified the issue Dec 11, 2023
- @tj-devel709 verified it a second time Dec 12, 2023
- @samhouts added to MAUI SDK Ongoing Dec 21, 2023
- @Redth removed it from the .NET 8 SR2 target and moved it to .NET 8 + Servicing Jan 10, 2024
- @samhouts removed it from MAUI SDK Ongoing Jan 10, 2024
- @jaosnz-rep verified it a third time and adjusted the tags Feb 28, 2024 
- @Eilon adjusted the tags May 10, 2024
- @PureWeen removed the p/1 tag and added p/2 on Jul 2, 2024 
- @Pureween removed it from .NET 8 + Servicing and moved it to Backlog Aug 2, 2024

Thus we have had at least 13 formal actions from 7 official Microsoft employees over the past 14 months. The effect of this however appears to have been to only kick the can down the road and now into Backlog with no visible progress over the past 14 months to fix the issue. 

What is the current meaning of this? Are we suggested to abandon Maui on iOS? Is there an alternative Maui component planned or available for apps that require multi-line text input? Is this an error? Is there any plan to make this basic component work in iOS and if so what is the timeline? 

When the issue was initially marked p/1 I assumed (reasonably I believed) that this meant the team would consider such a broken core component high importance to fix and a fix would follow. 7 active Microsoft employees commenting on the bug seemed to imply this as well. I have thus labored under the Maui project since for >14 months presuming a solution would be forthcoming.

Now >14 months later, there remains no way to release anything on iOS that requires >1 line text input and no visible progress to fix it has materialized.

Can you please advise on what we as users should be doing regarding this going forward or what the plan is on this component? @davidortinau are you still managing the team and perhaps can you provide any advice?

I have said many times it seems evident to me that Microsoft has visibly underfunded and understaffed the team and I imagine there is likely just far too much work to go around for everyone. So I can appreciate if the team is stretched thin and in raising this I still do empathize with that.

Thank you sincerely for any help.

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

No

### Last version that worked well

None working

### Affected platforms

iOS

**Comment by kubaflo** [comment]
Hi @jonmdev try to put editor inside a content view it should help :)

**Comment by kubaflo** [comment]
You can also check if this PR perhaps fixes your issues: https://github.com/dotnet/maui/pull/25098

**Comment by maonaoda** [comment]
@kubaflo 
Thank you very much for your efforts, but there is another problem with this PR #25098 . :(
