### ISSUE TITLE
iOS app crash with MAUI 8.0.72 Xcode 15.4 simulator MacOS 14.7.1

### ISSUE THREAD

**Issue by vinajava** [dotnet/maui#25756]
### Description

Create new MAUI app. Add an Entry, then run in simulator. Click on Entry to enter text. App crashes.
It has never happened with Maui 8.0.72 before. It just happened from yesterday.
Note: Update to MAUI 8.0.80 or later and Xcode 16 is not an option for us because of this bug :
https://github.com/dotnet/maui/issues/25237
https://github.com/dotnet/maui/issues/19099

I attach the video for this bug so you can see.
I also attach full bug report.

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.71 SR7.1

### Affected platforms

iOS

### Did you find any workaround?

https://github.com/user-attachments/assets/ff2f5ccf-043f-4fd9-9a63-c1309c1984fa
[bug report.txt](https://github.com/user-attachments/files/17685071/bug.report.txt)

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
Looks like this: https://github.com/dotnet/runtime/issues/98941

If you don’t want to update there is a workaround listed in there you can use for the time being.

**Comment by vinajava** [comment]
Thank you for the workaround. It works.
