### ISSUE TITLE
Measurement of Control within a TriggerAction seems not to work

### ISSUE THREAD

**Issue by Intelli-Soft** [dotnet/maui#2577]
### Description
I try to Measure a string within the override void Invoke of a TriggerAction, which is always -1 (width and height)

### Steps to Reproduce

1.  Within the invoke procedure, I try to create a new Entry Control, fill it with some text
2.  I try to measure the size, but it always returns -1

   ```
 internal class SizeChangedAction : TriggerAction<Entry>
    {
        public SizeChangedAction()
        {
            
        }
            protected override void Invoke(Entry sender)
        {
                Entry locEntry = new Entry();
                locEntry.Text = "Want to measure this text length";
                locEntry.FontFamily = sender.FontFamily;
                locEntry.FontSize = sender.FontSize;
                locEntry.UpdateFormsText(sender.MeasureTextTemplate.Trim(), Microsoft.Maui.TextTransform.Uppercase);
                var locSize =  locEntry.Measure(double.PositiveInfinity, sender.Height);
               // locSize should have some value
        }
   }
```
### Expected Behavior
locSize should have some width / height size
### Actual Behavior
locSize always = -1 within height and width

**Comment by hartez** [comment]
That Measure method won't return anything useful if the control doesn't have any native backing control to actually measure. 

Here's an alternative that might work for you:

```
Entry locEntry = new Entry();
locEntry.Text = "Want to measure this text length";
locEntry.ToNative(this.Handler.MauiContext);
var locSize = locEntry.Handler.GetDesiredSize(double.PositiveInfinity, TheEntry.Height);
```

With that, `locSize` should be a `Microsoft.Maui.Graphics.Size` value with the measured size.

**Comment by Intelli-Soft** [comment]
Hey @hartez 
Sorry for the really late reply.
I tested your solution, but the problem is, that 
`this.Handler.MauiContext`
Is always NULL (the Handler itself)

What I tried so far:

`    public class ISEditBox : Entry
    {
        public ISEditBox()
            {

            Microsoft.Maui.Handlers.EditorHandler.EditorMapper.AppendToMapping(nameof(IView), (handler, control) =>
             {

                 if (control is ISEditBox)
                 {
                     this.Handler = handler;
                 }

             });
            }

        public static readonly BindableProperty TextMeasurementProperty = BindableProperty.Create(nameof(TextMeasurement), 
                                                                                                  typeof(TypeOfTextMeasurement), 
                                                                                                  typeof(ISEditBox),
                                                                                                  propertyChanging: OnTextMeasurementPropertyChanging);

        private static void OnTextMeasurementPropertyChanging(BindableObject bindable, object oldValue, object newValue)
        {
            try
            { 
                var locCurrentControl = (ISEditBox)bindable;
                var locNewTypeOfTextMeasurement = (TypeOfTextMeasurement)newValue;
                locCurrentControl.SetControlWidth(locNewTypeOfTextMeasurement);
            }
              
            catch (Exception)
            {

                throw;
            }
        }

        public TypeOfTextMeasurement TextMeasurement
        {
            get => (TypeOfTextMeasurement)GetValue(TextMeasurementProperty);
            set => SetValue(TextMeasurementProperty, value);
        }

        private void SetControlWidth(TypeOfTextMeasurement typeOfTextMeasurement)
        {
            Entry locEditor = new Entry();
            locEditor.Text = "Want to measure this text length";
            locEditor.FontFamily = this.FontFamily;
            locEditor.FontSize = this.FontSize;
            locEditor.ToNative(this.Handler.MauiContext);
            var locSize = locEditor.Handler.GetDesiredSize(double.PositiveInfinity, locEditor.Height);
            locEditor = null;
            this.MinimumHeightRequest = locSize.Height;
            this.MaximumHeightRequest = locSize.Height;
            this.MinimumWidthRequest = locSize.Width;
            this.MaximumWidthRequest   = locSize.Width;
        }
}`
