### ISSUE TITLE
[iOS] Fix CarouselViewRemoveAt so that it's passing on both CV1 and CV2 sets of handlers

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#25776]
### Description

This test was modified to only run on CV2 because it's not passing on CV1
https://github.com/dotnet/maui/pull/25719/files

We need to fix it so the test is passing on both sets of handlers

**Comment by NirmalKumarYuvaraj** [comment]
@PureWeen , Could you provide more details about the issue you're facing with CollectionViewHandler1, including the specific test case, expected vs. actual behavior and a video comparison of the behavior with CollectionViewHandler2?

**Comment by NirmalKumarYuvaraj** [comment]
## Issue details

When using CV1 handlers, removing the first item from the CarouselView during navigation doesn't work as expected. The removed item remains visible in the view . This functionality works correctly with CV2 handlers.

## Steps to Reproduce
1. Go to this file [CarouselViewRemoveAt](https://github.com/dotnet/maui/blob/3992a45f2a00d20222963fc959f3568239449bb9/src/Controls/tests/TestCases.HostApp/Issues/CarouselViewRemoveAt.cs#L9) and Replace CarouselView2 with CarouselView1.
2. Run the test case.
3. Notice the first slide with text as 1 is still in the view.

## Output
|Expected|Actual|
|--|--|
| <video src="https://github.com/user-attachments/assets/e4d593ef-9794-4767-b9af-3ab5c89d2ece" height ="600" width="300"> | <video src="https://github.com/user-attachments/assets/11e350b1-039b-41e1-a444-a728897bf90a" height ="600" width="300"> |
