### ISSUE TITLE
New HybridWebView .NET 9 functions to invoke Javascript - documentation, uncaught exceptions, forcing all Javascript to return JSON?

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#25782]
### Description

HybridWebView was moved to the main .NET9 Maui project with numerous breaking changes. I am happy HybridWebView is in there now as it is a fantastic project. This will hopefully provide longevity to it. But we need clear instruction on how to use it or fixes for what is broken. I have now spent the whole day on it but cannot make sense of or find any explanation for anything. 

## OLD VS. NEW DOCUMENTATION
Previously the usage was well documented by Eilon's [ReadMe](https://github.com/Eilon/MauiHybridWebView/). The instructions there worked and made sense. Everything was easy to follow.

The only current instructions I can find are [here](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/hybridwebview) but these instructions do not work as best I can follow them..

## MISSING FUNCTIONS
Furthermore, according to [this update](https://github.com/dotnet/maui/issues/22303) as of Aug 2024 by @Eilon we should still have the following functions:

```
public async Task<string?> InvokeJavaScriptAsync(string methodName, params object[] paramValues) { ... }
public async Task<TReturnType?> InvokeJavaScriptAsync<TReturnType>(string methodName, params object[] paramValues) { ... }
```

These are similar the original functions we had in the original project and what we generally need. Simple, clear, effective great.

It seems they are still not there however. I cannot run them. They show as not existing. I am using version `9.0.0-rc.2.24503.2` and that report was "fixed" in `9.0.0-rc.1.24453.9` but yet these functions don't exist still now. Or I don't know how to access them. What happened to them or how do we use them?

![Image](https://github.com/user-attachments/assets/65b8e8f9-f000-4280-8ef1-a115212a102f)

## ONLY CURRENT AVAILABLE FUNCTION 
The only function for we have for `InvokeJavaScriptAsync` is this very bizarre one that doesn't seem to work properly either:

```
/// <inheritdoc/>
public async Task<TReturnType?> InvokeJavaScriptAsync<TReturnType>(
	string methodName,
	JsonTypeInfo<TReturnType> returnTypeJsonTypeInfo,
	object?[]? paramValues = null,
	JsonTypeInfo?[]? paramJsonTypeInfos = null)
```

There are two problems with this (besides the fact that the other two methods above are the ones we actually need):

### 1) `returnTypeJsonTypeInfo` as null causes missed errors

You cannot set `JsonTypeInfo<TReturnType> returnTypeJsonTypeInfo` to null even if you have no use or desire for this. But setting it to null fails silently in Windows returning an uncaught exception that doesn't tell you the problem. In Android at least it tells you the issue by saying `System.ArgumentNullException: 'Value cannot be null. (Parameter 'jsonTypeInfo')`

If this can't be null and that is a problem, it should be caught in all OS's. Though I don't know why it can't be null or what the point of it is.

### 2) Suggested method also doesn't work

I have absolutely no idea what the point of this is. There is no clear explanation for what it does or how to use it. Is it to specify a Json Deserializer or something about that for the result? Why? How? What if I just want to return a string and parse it myself?

The article doesn't explain it either except saying we are to add this apparently magical code which "makes it work":

```
[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(double))]
internal partial class HybridSampleJsContext : JsonSerializerContext
{
    // This type's attributes specify JSON serialization info to preserve type structure
    // for trimmed builds.
}
```
Doing that and then running a function like this:

```
var result = await hybridWebView.InvokeJavaScriptAsync<string>("setBackgroundRandomColor", HybridSampleJSContext.Default.String);
```
Where the Javascript being invoked is:

```
function setBackgroundRandomColor(){
	let randomColor = getRandomHexColor();
	document.body.style.backgroundColor = randomColor;
	return '[{"result": "okay"}]';
}
````

Still returns an error though which is again unhandled in Windows causing a crash. In Android you get `'The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1.'`

No matter what I put for the javascript function to return it gives this error. What is it expecting? What are we supposed to do?

## OLD VS. NEW
One of the great things about the HybridWebView was the simplicity of sending and receiving things. I would like to know how to make the new function work, but we should not need to over-complicate it either for most usage. The original methods worked fine and as suggested by @Eilon  it looks like they are still supposed to be there now again?

There are numerous other issues, but I will report them each separately for clarity. Thanks for any help, fixes, and/or improvement to the documentation.

### Steps to Reproduce

See bug project. All webview files are stored in:

`Resources/Raw/webview` 

which is just a short  index.html and a copy paste of the code we must now seemingly add for HybridWebView.js (previously used to be automatically included in projects with `<script src="_hwv/HybridWebView.js"></script>` but now it looks like we create this ourselves?

Then the Maui code is all in App.xaml.cs.

Run the project and try to click "Change Color" button. See it crash or return the errors. Comment in/out methods in App.xaml.cs to see the various problems.

Try using the "fixed" original functions above and see they don't exist.

### Link to public reproduction project repository

https://github.com/jonmdev/HybridWebView9Bug

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3 GA

### Affected platforms

iOS, Android, Windows

### Affected platform versions

All

### Did you find any workaround?

No

**Comment by jonmdev** [comment]
## FURTHER INFO:

Looks like I just needed to keep reading @Eilon's thread for a link to at least some answers.

It looks like from this post:

https://github.com/dotnet/maui/pull/23769

You decided not to go ahead with adding those old functions. This new function is the only one we can have.

I was able to get a return out of the javascript without error by returning:

```
return "okay".json();
```

It thus seems we must return something from every javascript function now which is run through `.json()` on that side. Is that correct?

Thus since we always must return something, we must tell C# what to deserialize the json into I guess, and that is the whole point.j

Any further explanation or thoughts? Or updated documentation to explain this?

Thanks again. It looks like the new method works at least. If you know how to use it.

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 5(9.0.0-rc.2.24503.2) When debug in windows platform, I set the Exception settings windows and I see the info as you mentioned The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1, As you can see, this is what I see in the Debug windows pltaform, but on the Android platform, it stays on the .net page. You can view my screen recordings and screenshots
![Image](https://github.com/user-attachments/assets/bf74458f-eb7e-48cf-94de-63a87af731ad)
![Image](https://github.com/user-attachments/assets/ed4d25c0-2d71-4c5d-8f49-8e1160ff3f78)

**Comment by Eilon** [comment]
Hi @jonmdev , thank you so much for all the feedback you've provided. There are indeed some rough areas in HybridWebView that we will be improving. I've tried to split this issue into multiple independent issues so that we can track the work required to address what you've listed.

Here are the related issues (some already existed, some were also opened by you, and for some I created new issues):

* Embed HybridWebView JS as a resource: https://github.com/dotnet/maui/issues/24730
* Support JS to call async C# methods: https://github.com/dotnet/maui/issues/25968
* HybridWebView can't call JS that returns a string: https://github.com/dotnet/maui/issues/26765
* HybridWebView can't call JS that has no return value: https://github.com/dotnet/maui/issues/26766
* No good way to handle permission requests: https://github.com/dotnet/maui/issues/25784

And I also posted a workaround PR for some of the issues listed: https://github.com/jonmdev/HybridWebView9Bug/pull/1 (though you may have already independently found some of this).

If I've missed any specific issues you've found, please let us know or log new items (ideally 1 issue per item, for better tracking). Thank you!
