### ISSUE TITLE
Hyper-V

### ISSUE THREAD

**Issue by sidsyyy** [dotnet/maui#25788]
I can't find the Hyper-V option in the Windows feature.

**Comment by jfversluis** [comment]
Hyper-V has a couple of minimum requirements as seen in the [documentation](https://learn.microsoft.com/virtualization/hyper-v-on-windows/about/#system-requirements)

> Hyper-V requires:
>
> * A processor with second level address translation (SLAT) capabilities.
>
> * Windows 10 (Pro or Enterprise) or Windows 11 (Pro or Enterprise).

So make sure that you have that and it should be there. Hope that helps!
