### ISSUE TITLE
Touchscreen not working after rapidly touch .net maui hybrid app

### ISSUE THREAD

**Issue by Mubashir222** [dotnet/maui#25790]
I create .net maui hybrid app, now after creating project i have an issue of touchscreen. As when user rapidly touch screen then application hanged. I don't know why, But it crash the system. How to resolve that problem? Kindly assist me so that my project is completed, now it occure that issue.

**Comment by drasticactions** [comment]
Does this happen in _any_ .NET MAUI Hybrid app, or your app specifically?

Can you please create a small reproduction sample showing the crash? Or provide a stack trace?

**Comment by Mubashir222** [comment]
https://we.tl/t-D25LgtFVDf
here is sample video where i create project of .net maui hybrid app then you check it touch is not working

**Comment by drasticactions** [comment]
Thank you for the video! If you could please provide a reproduction project or a stack trace, that could help us debug the issue further.

**Comment by Mubashir222** [comment]
@drasticactions @radical @shanselman @AArnott  
Steps to reproduce to issue.
Create a new Maui Blazor Project
Deploy it on windows tablet
Repeatly touch the screen inside the app window as quickly as you can

**Comment by Mubashir222** [comment]
Kindly assist me to resolve that problem so that i working on that project. @drasticactions @radical @shanselman @AArnott

**Comment by AArnott** [comment]
@Mubashir222 picking random people to mention in an attempt to make progress on one particular repo (that I don't work in at all) is poor sport. Please don't do that.

**Comment by mattleibow** [comment]
Please see https://github.com/MicrosoftEdge/WebView2Feedback/issues/3685
