### ISSUE TITLE
Image and Font Failed to load on iPhone 15 plus which results to a white empty page

### ISSUE THREAD

**Issue by mrjcitadel** [dotnet/maui#25796]
### Description

When I run the app on iPhone 15, it works fine but when I run it on iPhone 15 plus, it only shows white empty screen.![Image](https://github.com/user-attachments/assets/62c15d13-991d-4273-9b2e-67d66af49816)

### Steps to Reproduce

Create an app. import .svg images on image folder.
Add Font
run on iPhone 15 plus

![Image](https://github.com/user-attachments/assets/f835a1c6-13c6-4492-868e-c4dd5a2fdf6c)

### Version with bug

8.0.93 SR9.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.93 SR9.3

### Affected platforms

iOS

### Affected platform versions

iOS 18.1

### Did you find any workaround?

No work around yet.

### Relevant log output

```shell
IIOImageSource:439: *** ERROR: can't open '[Simulator image path]'(fileExists == false)

GSFont: "Gotham-Medium" already exists.
GSFontRegisterCGFont(<CGFont (0x600003f59180): Gotham-Medium>) failed 305
```

**Comment by LeoJHarris** [comment]
Cant say this is related at this point but the same issue on Android, none of of the images are loading at all through the entire app.

**Comment by Ying-6** [comment]
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
