### ISSUE TITLE
Full list of bugs and issues with new .NET 9 HybridWebView

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#25804]
### Description

I spent the full day yesterday struggling to implement the .NET 9 HybridWebView. I wrote two bug reports based on that [here](https://github.com/dotnet/maui/issues/25782) and [here](https://github.com/dotnet/maui/issues/25784). But after some rest, I thought it best to try again to better clarify and enumerate all the problems. This may help people as well until the issues are fixed.

## 1) Javascript functions are forced to always return something 

 @Eilon you said "The methods can be invoked as async, have **optional** return values, and optional parameters." However this does not seem to be the case.

If you run my bug project [here](https://github.com/dotnet/maui/issues/25782) or make your own, you can play with the functions and set for example in C#:
```
hybridWebView.InvokeJavaScriptAsync<string>("setBackgroundRandomColor", HybridSampleJSContext.Default.String);
```
with Javascript:
```
function setBackgroundRandomColor(){
	let randomColor = getRandomHexColor();
	document.body.style.backgroundColor = randomColor;
}
```
You will get uncaught exception `Message = "'u' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0." ` which is something I saw all day yesterday. This is obviously not meaningful. This is the error for "no return received from Javascript," at least with string. It seems unintentional as you said your intent was to make returning optional, which I agree it should be. The forced return causes weird design patterns as I explained in my other thread and you will see here also.

If you need to add a new type for `InvokeJavaScriptAsync<HybridViewNoReturn>` even that would be okay although a bit silly looking perhaps. My feeling is no return should be set by making the second argument null and then simply not awaiting obviously or if awaiting with second argument null it just returns immediately. Or for no return, a single or three argument untyped non-async function like `InvokeJavaScript("setBackgroundRandomColor", new object[]{arg}, new[]{ argType});`

## 2) Return from Javascript must be precisely formulated

The only consistent way I could get such functions to return was as follows:

```
const returnOk = JSON.stringify("okay"); //use at end of every function

function setBackgroundRandomColor(){
	let randomColor = getRandomHexColor();
	document.body.style.backgroundColor = randomColor;
        return returnOk;
}
```

To "solve" this I thus created wrappers for all my Javascript code like above to access from C# and had them return something generic like this `returnOk`. But this is also I am sure unintentional based on your quote above stating return should be optional.

If you try `return "Okay"` this doesn't work, or `return "['Okay']"` or `return '["Okay"]'` which say `The JSON value could not be converted to System.String`. I am not sure of the rules here but using `JSON.stringify` on all string returns seems to solve it. I don't know how to manually format a string in Javascript to make it return without using `stringify`. Is there a manually written Javascrript string format that is accepted?

## 3) Setting the second argument to null fails with an uncaught exception. 

This is even if you have no intention of returning anything (and thus the second argument is irrelevant).

You can try this as:
```
var result = await hybridWebView.InvokeJavaScriptAsync<string>("setBackgroundRandomColor", null);
```

## 4) Setting the fourth argument to null (or omitting) fails silently

If you use a function that invokes parameters, but omit the fourth argument (so it defaults to null) but use the first three arguments, it fails silently - the function is not called to my knowledge at all and nothing alerts you of this. 

For example if you run this from C# you will get no errors:

```
List<Color> colors = new (){Colors.DarkBlue, Colors.DarkGreen, Colors.DarkRed};
var color = colors[Random.Shared.Next(0, colors.Count)];
string colorString = color.ToHex();
var result = hybridWebView.InvokeJavaScriptAsync<string>(
    "setBackgroundColor",
    HybridSampleJSContext.Default.String,
    new object[] {colorString}
    //,new[] { HybridSampleJSContext.Default.String }
    );
```
with Javascript:

```
function setBackgroundColor(colorString){
    document.body.style.backgroundColor = colorString;
    return JSON.stringify("okay");
}
```
I did not test further but I imagine similar problems then if the count of objects in parameters and parameter json types are not the same (ie. this should cause a warning but doubt it will - for each parameter need one JSON type that is not null.)

## 5) Permissions requests cannot be caught in Android

It is no longer possible to catch permissions requests from Android HybridWebView using the available prior method as per: https://github.com/dotnet/maui/issues/25784 This obviously needs a fix. 

Unlike the rest of things I mention here I found no workaround to this so it is likely the biggest issue.

## 6) Key documentation is hidden in GitHub

The only documentation of the new methods are in [this thread](https://github.com/dotnet/maui/pull/23769) and [this article ](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/hybridwebview?view=net-maui-9.0) which are missing a lot of instruction and obviously GitHub is not an easy place to search. The GitHub page I only found by clicking through @Eilon's issue reports. The official Microsoft page needs more work.

## 7) Documentation needs section on sending raw messages from Javascript to C#

It would ideally need a section explaining that the method to send messages from Javascript to C# (has changed names now) is called by the fullest name of `window.HybridWebView.sendRawMessage` or just `HybridWebView.sendRawMessage`. This is not explained in the documentation I see. I see there is one line implementing this with Ctrl+F in one line of demo code, but a proper section explaining it would be better.

## 8) Json Type method needs more explanation

This method is now key to the system. It should be elaborated on what it means, what it is doing, and with more types and their Json Type equivalents. It should also be clarified that this method creates errors in Visual Studio as you type, because these things are generated on build, and those errors disappear after building. I would add to the demo code (with further explanation):

```
[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(Dictionary<string, string>))] //becomes "HybridSampleJSContext.Default.DictionaryStringString"
[JsonSerializable(typeof(string))] //becomes HybridSampleJSContext.Default.String
[JsonSerializable(typeof(bool))] //becomes HybridSampleJSContext.Default.Boolean
[JsonSerializable(typeof(float))] //becomes HybridSampleJSContext.Default.Single
[JsonSerializable(typeof(double))] //becomes HybridSampleJSContext.Default.Double
internal partial class HybridSampleJSContext : JsonSerializerContext
{
    // This type's attributes specify JSON serialization info to preserve type structure
    // for trimmed builds.  
}
```
Those would be the common types needed. None of this is immediately apparent and the logic for the expected names of the types for the created `JsonSerializerContext` (or how to debug what they will be if any code will tell you) should be better explained, especially given these are only actually created after building. 

## 9) Possible new design pattern?

If there is an intended use case (which I just thought of after yesterday) that we can trigger our own Javascript functions while bypassing all these typing and checking and returning issues (though I still think they should be fixed), this could be explained as that you can run `hybridWebView.sendRawMessage("functionName")` and then running in Javascript to receive:

```
        window.addEventListener(
            "HybridWebViewMessageReceived",
            function (e) {
                let message = e.detail.message;
                if (message == "runFunction1"){ window.runFunction1(); }
            });
```
I am not sure if this would be an intended design pattern but it just occurred to me. One could create their own "interop language" just through the raw messages back and forth. This could provide similar function to the original design again except without the nice automatic parameter handling. We would have to manually parse our parameters out of the raw messages based on our own logic.

## Conclusion
I think that's everything. It should have been a very quick conversion but took an entire day because of all the above. Fixing this will save other people the same problems. 

Overall, the new system does work well once you understand all the issues above. I believe this change was implemented to fix problems with the .NET 8 method not returning properly or consistently and maybe some things being stripped out on build. If so, it is not a bad way of working. If it is necessary, so be it. It requires more explicit typing and boilerplate. 

I do think returning from Javascript should be optional still somehow. Uncaught exceptions must be fixed. Permissions issue must be fixed of course.

Worse case scenario, one can code their own logic to work around all of this system with raw messages back and forth as noted above, though it probably should not be necessary really since this method is good once the bugs and issues above are removed. 

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.1.7762

### Affected platforms

iOS, Android, Windows

**Comment by mattleibow** [comment]
Thanks for this detailed feedback! I'll let @Eilon comment and break this one up.

**Comment by atanubanerjee** [comment]
Has anybody able to get HybridWebView working at all with .Net Maui 9.0 GA? If so, then can they point to working code for this?

With .Net 9.0 GA any page with a HybridWebView causes an uncaught exception on Windows, even if I just try the sample in online documentation or the HybridWebView sample in the Maui samples repo. 

For comparison, I had the HybridWebView mostly working with 9.0 RC1 and RC2 - I could send messages back and forth in Windows. And on Android I could send messages to the HybridWebView, but it would fail with a thread exception if I tried to send messages back. Also Eilon's earlier experimental HybridWebView control shipped outside of Maui worked great for me with .Net 8.0 - both on Windows and Android.

**Comment by jonmdev** [comment]
Unfortunately I must add another error (regression) which has newly been added. 

## Version
This error is not present in:

```
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.0-rc.2.24503.2" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.0-rc.2.24503.2" />
```
But it is present in:

```
		<!--<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.21" />-->
		<!--<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.21" />-->
```

## Error
With the above version change, we can no longer receive "RawMessage" type messages from Javascript into the HybridWebView.

The error received on attempting to do so is:
```
**System.ArgumentException:** 'The message type 'RawMessage' is not recognized. (Parameter 'rawMessage')'
```
For reference, the type `RawMessage` and parameter `rawMessage` are not mine, but rather Maui's. I have no such parameter or type in my code. The call stack localizes this to line 55 here:

https://github.com/dotnet/maui/blob/07f41ae8209b9f00e784dacb87d70860622ff4e9/src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Android.cs#L55C1-L55C39

This is being triggered by:

```
    window.HybridWebView.SendRawMessage("MESSAGE");
```

```
hybridWebView.RawMessageReceived += delegate (object sender, HybridWebViewRawMessageReceivedEventArgs e) {
     //whatever to respond
}
```
## OS

Android

## Workaround

I can at least still run my project then in 9.0.0-rc.2.24503.2. But somewhere between there and 9.0.21 a new bug was introduced. This has become a minefield. Hopefully it will settle down soon.

Any thoughts @Eilon or expectation on possible timelines? Thanks for any help.

**Comment by mattleibow** [comment]
I would hope we embed this js into assembly and inject somehow. Or have a package somewhere. Copy from docs is not my idea if a complete feature.

**Comment by jonmdev** [comment]
> I would hope we embed this js into assembly and inject somehow. Or have a package somewhere. Copy from docs is not my idea if a complete feature.

That is how it used to work. As per [Eilon's old project](https://github.com/Eilon/MauiHybridWebView) you would add the following to your index.html:

```
    <script src="_hwv/HybridWebView.js"></script>
```
And it would magically work. We would never see this file at any point. It was presumably being added to the temp build files only each time you build or debug and at all other times it didn't exist.

Having now used the system a fair bit both ways, my preference would be a compromise between these two approaches.

When I could not see the `HybridWebView.js` I was constantly wondering (literally for weeks and months) - What is this thing? Where is it? How does it work? What functions does it contain? Yes, I could have probably looked in Eilon's package and found it but it was just a background nagging question.

By contrast seeing it right in front of you is much more transparent and it offers some extra benefits worth considering.

## Suggestion

My suggestion would be to have Maui create the `HybridWebView.js`, but do so visibly and persistently on each build in the web project's root folder, either named as `_hwv/HybridWebView.js` (perhaps ideally to get it out of the way) or `_HybridWebView.js` perhaps to avoid any naming conflicts with any probable user created files. 

I presume that is the reason `RawMessage` was changed to `__RawMessage` - to reduce risk of clashing with any user-created name types, which is probably wise. So, `_hwv/HybridWebView.js` was probably wise.

I had many such concerns I had when I could not see `HybridWebView.js` - What functions does it contain? What if I create a function that matches its name? What does it actually do? Seeing that it is just a `window.HybridWebView = (whatever)` script was also very helpful to understanding it is not really doing any major voodoo. It is just attaching a few needed functions to the `window`. I could also then quickly check those Javascript function names when needed rather than going to a website to see the API.

Lastly, being able to see exactly what is in it allows you to mock it if needed. For example, you could do:

```
<script>
  // Define your condition here (e.g., environment check)
  var isProduction = true; // This can be dynamically set based on your environment

  // Create the script element
  var script = document.createElement('script');
  
  // Conditionally set the source based on the condition
  if (isProduction) {
    script.src = '_hwv/HybridWebView.js';
  } else {
    script.src = 'mock/HybridWebView.js';
  }

  // Append the script element to the head or body of the document
  document.head.appendChild(script);
</script>
```

Then you could easily create a mock version based on the existing `_hwv/HybridWebView.js` if you want to be able to run that Javascript module on its own without C# around it and just switch the production flag to use it or the real functions.

## End Solution
So my suggestion would be that when you click Debug > Start Debugging or Build > Build Solution, this automatically checks the root folder of each `hybridWebView` such as:

```
            hybridWebView.HybridRoot = "jsfolder";
            hybridWebView.DefaultFile = "index.html";
```
And then automatically it creates and adds a file at say `jsfolder/_hwv/HybridWebView.js` which is permanently added to that folder (or overwritten each time if already exists to auto-handle upgrades or changes).

This file could have a simple annotation at the top like:

/* This file is auto-generated for Maui HybridWebView javascript-C# interoperability. 
Do not edit this file directly. 
It will be replaced on each Debug/Build automatically. */

This approach:
- creates transparency on how the system works, 
- allows users to look up the Javascript functions directly from the file created in their directory
- keeps the HybridWebView.js out of the user's way if at `/_hwv/HybridWebView.js`, 
- doesn't require us to monitor and keep copying and pasting the code from a random Microsoft webpage with each update, and 
- allows easier mocking function to keep running and testing the Javascript project outside of the Maui context

Having used it both ways - (i) auto-generated and hidden from the user, and (ii) manually added and fully visible - this would certainly give the best of both worlds in my opinion.

**Comment by jonmdev** [comment]
In the interest of completion, there is one more issue that I will repeat here and then this thread has all of them.

## Cannot set `WKWebViewConfiguration()` in iOS without Reflection

As per this thread I made on [Eilon's package](https://github.com/Eilon/MauiHybridWebView/issues/67) we cannot set the parameters for playback on the HybridWebView, except by Reflection and overriding as follows:

```
#if IOS || MACCATALYST

            HybridWebView.HybridWebViewHandler.PlatformViewFactory = (handler) => {
                
                var config = new WKWebViewConfiguration();
                //====================================================//
                //CUSTOM CODE
                //====================================================//
                config.AllowsAirPlayForMediaPlayback = true;
                config.AllowsInlineMediaPlayback = true;
                config.AllowsPictureInPictureMediaPlayback = true;
                config.MediaTypesRequiringUserActionForPlayback = WebKit.WKAudiovisualMediaTypes.None;

                //simple enough can just redundancy this one:
                Action<Uri, string> MessageReceivedAction = delegate (Uri uri, string message) { // to replace https://github.com/Eilon/MauiHybridWebView/blob/3ca801076a1e3fbe3b8922b2429524df20def6a4/HybridWebView/Platforms/iOS/HybridWebViewHandler.iOS.cs#L40
                    ((HybridWebView.HybridWebView)handler.VirtualView).OnMessageReceived(message);
                };

                //REFLECTION METHOD ie. as per https://stackoverflow.com/a/39076814/10305478
                object CreatePrivateClassInstance(string typeName, object[] parameters) {
                    Type type = AppDomain.CurrentDomain.GetAssemblies().
                             SelectMany(assembly => assembly.GetTypes()).FirstOrDefault(t => t.Name == typeName);
                    return type.GetConstructors()[0].Invoke(parameters);
                }

                //USE REFLECTION
                IWKScriptMessageHandler webViewScriptMessageHandler = (IWKScriptMessageHandler)CreatePrivateClassInstance("WebViewScriptMessageHandler", [MessageReceivedAction]);
                config.UserContentController.AddScriptMessageHandler(webViewScriptMessageHandler, "webwindowinterop");

                IWKUrlSchemeHandler? wKUrlSchemeHandler = (IWKUrlSchemeHandler?)CreatePrivateClassInstance("SchemeHandler", [handler as HybridWebViewHandler]);
                config.SetUrlSchemeHandler(wKUrlSchemeHandler, urlScheme: "app");

                //============================================//

                // Legacy Developer Extras setting.
                var enableWebDevTools = ((HybridWebView.HybridWebView)(handler as HybridWebViewHandler).VirtualView).EnableWebDevTools;
                config.Preferences.SetValueForKey(NSObject.FromObject(enableWebDevTools), new NSString("developerExtrasEnabled"));
                var platformView = new MauiWKWebView(RectangleF.Empty, handler as HybridWebViewHandler, config);

                if (OperatingSystem.IsMacCatalystVersionAtLeast(major: 13, minor: 3) ||
                    OperatingSystem.IsIOSVersionAtLeast(major: 16, minor: 4)) {
                    // Enable Developer Extras for Catalyst/iOS builds for 16.4+
                    platformView.SetValueForKey(NSObject.FromObject(enableWebDevTools), new NSString("inspectable"));
                }

                return platformView;
            };
#endif
```

I also believe we should not be needing Reflection for such a task in a finished product. I mention some ways I think this could be handled in the other thread also.

**Comment by Eilon** [comment]
I posted a comment in the other bug you opened here: https://github.com/dotnet/maui/issues/25782#issuecomment-2557549398

But for completeness, here are some additional responses:

* We have some docs that are planned or in progress as listed here: https://github.com/dotnet/docs-maui/issues?q=is%3Aissue%20state%3Aopen%20hybridwebview
   * If you have thoughts on additional topics or sub-topics, please update those issues or create a new one
   * The topic of sending/receiving raw messages seems to be covered here already, but let us know if anything is missing or unclear: https://learn.microsoft.com/dotnet/maui/user-interface/controls/hybridwebview?view=net-maui-9.0#create-a-net-maui-hybridwebview-app
* Have a way to customize HybridWebView creation of platform webview: https://github.com/dotnet/maui/issues/26767

**Comment by Eilon** [comment]
Also logged this, which is possibly relevant to some of the issues: https://github.com/dotnet/maui/issues/26768
