### ISSUE TITLE
Enable Publish a MacCatalyst app from Windows

### ISSUE THREAD

**Issue by thirstyape** [dotnet/maui#25805]
### Description

Now that VS2022 for Mac is dead I think it would make quite a bit of sense to have remote publishing for macOS from Windows made available as it is already for iOS. 

### Public API Changes

Specifically, add the following CLI options:

* `-p:ServerAddress=[my.macbook.ip.address]`
* `-p:ServerUser=[my.macbook.username]`
* `-p:TcpPort=58181`
* `-p:_DotNetRootRemoteDirectory=/Users/[my.macbook.username]/Library/Caches/Xamarin/XMA/SDKs/dotnet/`

### Intended Use-Case

Simplify the overly complex publishing for .NET MAUI apps so there is one more thing you can do on a single machine. Which will also aid in enabling build servers such as Jenkins to be able to automate publishing.

**Comment by mattleibow** [comment]
This is not really a MAUI issue but more the VS/IDE, so please open the issue there for that team to add the capability.
