### ISSUE TITLE
[9.0 GA, Android] ScrollView starts at the position of first Entry control on the bottom rather than at 0

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#25829]
### Description

In .NET MAUI 9.0 GA, Android has a new annoying feature that ScrollView does not start at position 0  but at the position where the content's first Entry control is located on the bottom of the ScrollView. I have a long list of settings on the app's Settings page and it is very confusing if the page is opened in the middle of the settings list rather than at start.

Windows seems to work fine, didn't test iOS. This also worked fine on Android in .NET MAUI 9.0 RC2.

### Steps to Reproduce

1. Download and build [GnollHackMAUIEasyBuild](https://github.com/hyvanmielenpelit/GnollHackMAUIEasyBuild) for Android by following the given instructions
2. Start the app and press the Settings button
3. Settings are opened in the middle of the list with User Name entry being on the bottom

### Link to public reproduction project repository

https://github.com/hyvanmielenpelit/GnollHackMAUIEasyBuild

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-rc.2.24503.2

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

Disabling all Entries at start and then enabling them with a 0.5 sec one-off timer seemed to help, but is not very elegant.

### Relevant log output

```shell

```

**Comment by ninachen03** [comment]
@janne-hmp  Where can I get the bank zip file, Could you help me, I can't find it in your https://github.com/hyvanmielenpelit/GnollHackMAUIEasyBuild

**Comment by mattleibow** [comment]
@ninachen03 did this happen in .NET 8? What about net9 preview6 or 7?

**Comment by PureWeen** [comment]
@janne-hmp can you provide a simplified sample that reproduces the behavior? 

[Archive.zip](https://github.com/user-attachments/files/17804935/Archive.zip)

I did a quick test here with entries in a scrollview and it's not scrolling to the first entry automatically.

**Comment by janne-hmp** [comment]
Hi, the game works just on .NET MAUI 9 (and Xamarin) currently. As Nina Chen mentioned, the problem appears on Android just with 9.0 GA, not with 9.0 RC2. Xamarin works well, too. I cannot check .NET 8 or 7 at the moment, as a meaningful amount of additional work would potentially be needed to add the support for older framework versions.

**Comment by ninachen03** [comment]
> Hi, the game works just on .NET MAUI 9 (and Xamarin) currently. As Nina Chen mentioned, the problem appears on Android just with 9.0 GA, not with 9.0 RC2. Xamarin works well, too. I cannot check .NET 8 or 7 at the moment, as a meaningful amount of additional work would potentially be needed to add the support for older framework versions.

I used the provided repro on RC2, the problem reappeared. It worked fine on RC1.

**Comment by janne-hmp** [comment]
Thanks for the clarification, Nina. I probably did not notice the bug in RC2, so good to hear the regression has been found to have occurred already in RC2 instead, and RC1 is the version which works.

**Comment by PureWeen** [comment]
Fairly sure this was caused by 

https://github.com/dotnet/maui/pull/24064

**Comment by jsuarezruiz** [comment]
> Fairly sure this was caused by
> 
> [#24064](https://github.com/dotnet/maui/pull/24064)

Just as reference, the implementation on Xamarin.Forms https://github.com/xamarin/Xamarin.Forms/blob/2f8f4864a4d289dc89a6228e2ca9d6a49993e365/Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs#L57
