### ISSUE TITLE
Version 8.0.100 produces compilation errors in standard application

### ISSUE THREAD

**Issue by MerSpyro** [dotnet/maui#25820]
### Description

Hello,

recently I have udpated to the version 8.0.100 from 8.0.91 and I started to see compilation errors on most common classes like:
![Image](https://github.com/user-attachments/assets/515c5450-7349-4a97-bc22-31cb915c1b51)

### Steps to Reproduce

Create a new project.
Change MAUI version to 8.0.100(SR10)
See that application doesnt build because of compilation issues.

### Link to public reproduction project repository

https://github.com/MerSpyro/Maui8100Issue

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.93 SR9.3

### Affected platforms

Android, iOS, I was *not* able test on other platforms

### Did you find any workaround?

No

### Relevant log output

```shell
dotnet workload list
maui-tizen                 8.0.83/8.0.100         SDK 8.0.400        
maui-ios                   8.0.83/8.0.100         SDK 8.0.400        
maui-android               8.0.83/8.0.100         SDK 8.0.400        
maccatalyst                18.0.8314/8.0.100      SDK 8.0.400        

dotnet --list-sdks

6.0.425 [/usr/local/share/dotnet/sdk]
7.0.317 [/usr/local/share/dotnet/sdk]
8.0.401 [/usr/local/share/dotnet/sdk]
8.0.404 [/usr/local/share/dotnet/sdk]
```

**Comment by Syed-RI** [comment]
I cant see version `8.0.100` in  nuget yet 🧐

**Comment by MerSpyro** [comment]
@Syed-RI 
It was reelased some 12 hours ago
![Image](https://github.com/user-attachments/assets/b8191b50-b73c-40e4-81b9-055da34aa5f5)

**Comment by Syed-RI** [comment]
I reference them in the csproj, and when updated encountered a restore error so i checked nuget.org![Image](https://github.com/user-attachments/assets/ad1fa033-197c-4c20-b842-3b4e35da1a15)

The latest for `8` is  `8.0.93`. Even the repro you have attached references the same

**Comment by Syed-RI** [comment]
@MerSpyro I wouldnt close the issue yet and wait for the team to respond. As it looks like issues you are experiencing are due to a mismatch somewhere or you are experiencing them in `8.0.93`. I dont know how the workload thing works, but I think I need to get `8.0.404` .net sdk first, then update the workload to get `8.0.100`. But in your case, I think, given you have `8.0.404` sdk installed, it is trying to use `8.0.100` but the workload may no be updated or is incompatible for some reason. Please reopen and tag @PureWeen @rmarinho

**Comment by PureWeen** [comment]
> It seems like Im not the brightest. I assumed ![Image](https://github.com/user-attachments/assets/e2e98379-b853-4c5a-9d67-b31819915422) That installed is really what it is, but Rider only shows what it..?? have specified to be installed as installed? but not always. The 8.0.100 is really not available yet so uh. Yea. Case closed [@Syed-RI](https://github.com/Syed-RI) thank you

Why is your Maui.Controls.Compatibility set to 9.0.0?

**Comment by egvijayanand** [comment]
That's how the NuGet package resolution works.

Since it can't find a package version 8.0.100, it resolves to 9.0.0.

The core issue is that the service release SR10 (v8.0.100) has no packages uploaded to NuGet.

**Comment by egvijayanand** [comment]
Output of `dotnet list package` command:

![Image](https://github.com/user-attachments/assets/0635c221-c796-43a0-a315-a3de841511aa)

**Comment by Zhanglirong-Winnie** [comment]
According to repro steps, we can used 8.0.100 to repro this issue on Visual Studio 17.13 Preview 1. 8.0.93 works fine.

**Comment by janusw** [comment]
> I cant see version `8.0.100` in nuget yet 🧐

Still not there apparently:

https://www.nuget.org/packages/Microsoft.Maui.Controls#versions-body-tab

@PureWeen Is there a reason why the package has not been uploaded yet, although the tag is almost a week old already ...?

**Comment by Syed-RI** [comment]
Yes I think the package is not uploaded

**Comment by PureWeen** [comment]
Dang, sorry about this. Didn't notice the last stage of push had failed.

Just checked nuget.org and it looks like 8.0.100 is up now

**Comment by Syed-RI** [comment]
> Dang, sorry about this. Didn't notice the last stage of push had failed.
> 
> Just checked nuget.org and it looks like 8.0.100 is up now

Thanks for your help! 😃
