### ISSUE TITLE
After updating Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility to version 9.0.0, I am facing issues with the handlers in MauiProgram.cs file

### ISSUE THREAD

**Issue by bhuwancb99** [dotnet/maui#25850]
### Description

After updating Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility to version 9.0.0, I am facing issues inside MauiProgram handlers. These issues were not present in the previous version (8.0.92). After upgrading both packages, I am unable to build the application or release the app.

![Image](https://github.com/user-attachments/assets/9a648d44-bdd8-40db-a9f3-dc659b2455b2)
![Image](https://github.com/user-attachments/assets/ee5a7266-add8-4db2-bd03-26676795532e)
![Image](https://github.com/user-attachments/assets/9bb2ba13-3e3e-4d56-a581-085359015576)
![Image](https://github.com/user-attachments/assets/21301a3a-3e5b-4eda-b683-a54bf722dd2a)
![Image](https://github.com/user-attachments/assets/ff707c07-1407-4b7f-9c6f-465dcad18be8)

### Steps to Reproduce

1. Create New Project in .NET MAUI
2. Update Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility both version 9.0.0
3. try to below code

        `#region DatePicker Handler
        Microsoft.Maui.Handlers.DatePickerHandler.Mapper.AppendToMapping("MyDatePickerHandler", (handler, view) =>
        {
#if ANDROID

            handler.PlatformView.BackgroundTintList = Android.Content.Res.ColorStateList.ValueOf(Android.Graphics.Color.Transparent);
#endif
#if IOS
            handler.PlatformView.BackgroundColor = UIKit.UIColor.Clear;
#endif
        });
        #endregion

        Microsoft.Maui.Handlers.PickerHandler.Mapper.AppendToMapping("MyPickerHandler", (handler, view) =>
        {
            if (view is CustomPicker picker)
            {
#if ANDROID
                picker.SelectedIndexChanged += (s, e) =>
                {
                    if (picker.IsFocused)
                    {
                        picker.Unfocus();
                    }
                };
                handler.PlatformView.Background = null;
                handler.PlatformView.SetTextColor(Android.Graphics.Color.Black);
                handler.PlatformView.SetBackgroundColor(Android.Graphics.Color.Transparent);
                handler.PlatformView.BackgroundTintList = Android.Content.Res.ColorStateList.ValueOf(Android.Graphics.Color.Transparent);
#elif IOS
                handler.PlatformView.BackgroundColor = UIKit.UIColor.Clear;
                handler.PlatformView.Layer.BorderWidth = 0;
                handler.PlatformView.BorderStyle = UIKit.UITextBorderStyle.None;
#endif
            }
        });`

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

iOS, Android

### Affected platform versions

Android 14

### Relevant log output

```shell

```

**Comment by FreakyAli** [comment]
Is your current Project on .NET 8 or 9?

**Comment by bhuwancb99** [comment]
@FreakyAli  .NET 8

**Comment by FreakyAli** [comment]
Controls 9.0 is not for .NET 8 projects, it's for .NET 9 please read the supported versions:

https://www.nuget.org/packages/Microsoft.Maui.Controls.Core/9.0.0#dependencies-body-tab

**Comment by bhuwancb99** [comment]
<TargetFrameworks>net8.0-ios;net8.0-android34.0</TargetFrameworks>

**Comment by ninachen03** [comment]
Did your problem get solved? You need to change TargetFrameworks in the csproj file from 8 to 9 and delete <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" /> from <ItemGroup>

**Comment by bhuwancb99** [comment]
@ninachen03 - so it's not working on .NET 8
