### ISSUE TITLE
In windows and ios the RequestedThemeChanged event only fires the first time.

### ISSUE THREAD

**Issue by JPfahl** [dotnet/maui#25864]
### Description

Works in Android but in windows and ios you only ever get the event once, you have to restart the app to get it to fire again.

### Steps to Reproduce

The following code in App.xaml.cs demonstrates the issue in a new default maui project:

    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();

            MainPage = new AppShell();

            RequestedThemeChanged += App_RequestedThemeChanged;
        }

        private void App_RequestedThemeChanged(object? sender, AppThemeChangedEventArgs e)
        {
            UserAppTheme = e.RequestedTheme;
        }
    }

### Version with bug

8.0.93 SR9.3

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

iOS, Windows

### Relevant log output

```shell

```

**Comment by drasticactions** [comment]
@JPfahl https://github.com/dotnet/maui/issues/15350#issuecomment-1596523882

I believe this is your issue: By setting `UserAppTheme,` you're saying, "I will handle theme updates from now on," so that event won't be raised again.

**Comment by JPfahl** [comment]
When I wrote this code originally the app would not switch themes without setting UserAppTheme from the event.  It must have been fixed along the way.  Thanks for the info.
