### ISSUE TITLE
iOS 18.0+ Maui bug with MediaPicker.PickPhotoAsync

### ISSUE THREAD

**Issue by Matadin75** [dotnet/maui#25879]
### Description

Hi guys!
I have recently run into an issue with Maui app, MediaPicker.PickPhotoAsync().

### Steps to Reproduce

this is my current code that fires when i click on a button to upload an image:

             await showAI(true);
                if (MediaPicker.Default.IsCaptureSupported)
                {
                    await Task.Delay(100);
                    var photos = await MediaPicker.PickPhotoAsync(new MediaPickerOptions()
                    {
                        Title = "Select an Image"
                    });

                    if (photos != null)
                    {
                        Stream sourceStream = await photos.OpenReadAsync();

                        MemoryStream ms = new MemoryStream();
                        using (sourceStream)
                        {
                            sourceStream.CopyTo(ms);
                            images.Add(new UploadImages()
                            {
                                Image = ms.ToArray(),
                            });
                        }
                    }
                }

![Image](https://github.com/user-attachments/assets/18cb0e3b-2777-435b-a327-d5c463279213)

this is what pops up from the PickPhotoAsync 
after this, the app is stuck. i can't select an image, nor can i cancel.

I have tested this on a iPhone 15 pro max simulator, running iOS 17.5 and it works perfectly: 

![Image](https://github.com/user-attachments/assets/f0fba375-4975-4f44-bfc3-452de78bf488)

![Image](https://github.com/user-attachments/assets/fb3a4d03-3405-4913-b35d-740be1f011cf)

my workload versions are 8.0.400
my mac is on the latest versions 
my visual studio is up to date

the only thing i could think of it the nuget versions, but when i upgraded them, i had a bunch of errors that i couldnt resolve.

Please help.
Thank you

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18

### Relevant log output

```shell

```

**Comment by Matadin75** [comment]
sorry, forgot to add:
the issue seems that the picker itself extends beyond the normal view (see difference between the first 2 images)
this only happens on iOS 18
i have yet to test on a physical device

**Comment by Zhanglirong-Winnie** [comment]
Hi, @Matadin75 
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by Matadin75** [comment]
> Hi, [@Matadin75](https://github.com/Matadin75) Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

Hi! I've actually found and sorted out the issue
Turns out it was because I needed to update everything to .NET 9 or to work with .NET 9.

Everything worked as expected after a quick clean and rebuild after the updates 

Thank you the reply 🙏

**Comment by jfversluis** [comment]
Thanks for letting us know! Glad you figured it out!

**Comment by wearemeeters** [comment]
> Turns out it was because I needed to update everything to .NET 9 or to work with .NET 9.

You mean, there is no way to use Media picker with .net 8?
I ran into the same issue with Media Picker on  .NET 8, but I would prefer to stick with .NET 8.
