### ISSUE TITLE
ContentPresenter just rendering component string in .Net9

### ISSUE THREAD

**Issue by DrJShoff** [dotnet/maui#25887]
### Description

Im using ContentPresenter to redifine RadioButton appearance. This has stopped working on Android after upgrading to .Net9. 

### Steps to Reproduce

1. Create new MAUI project.
2. Follow this example to reproduce: [https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton?view=net-maui-9.0#redefine-radiobutton-appearance](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton?view=net-maui-9.0#redefine-radiobutton-appearance)

![Image](https://github.com/user-attachments/assets/f90a389c-5c3b-4ccc-af45-57437f535c95)

Expected behavior is to get the components rendered correctly

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

It renders correctly if targeting .Net8

### Relevant log output

```shell

```

**Comment by ninachen03** [comment]
I can repro this issue at Windows platform on the latest 17.13.0 Preview 1.0(9.0.10 &9.0.0), but it worked for (8.0.100). It's a regression from .NET 8 to .NET 9.

![Image](https://github.com/user-attachments/assets/92888ef3-1b05-40e2-9e46-76a47c8e3cfa)

**Comment by jsuarezruiz** [comment]
> I can repro this issue at Android platform on the latest 17.13.0 Preview 1.0(9.0.10 &9.0.0), but it worked for (8.0.100). It's a regression from .NET 8 to .NET 9.
> 
> ![Image](https://github.com/user-attachments/assets/92888ef3-1b05-40e2-9e46-76a47c8e3cfa)

Happens using the **Content** property, **ControlTemplate** property or both?

**Comment by jsuarezruiz** [comment]
> > I can repro this issue at Android platform on the latest 17.13.0 Preview 1.0(9.0.10 &9.0.0), but it worked for (8.0.100). It's a regression from .NET 8 to .NET 9.
> > ![Image](https://github.com/user-attachments/assets/92888ef3-1b05-40e2-9e46-76a47c8e3cfa)
> 
> Happens using the **Content** property, **ControlTemplate** property or both?

Already tested, happens using **ContentPresenter**.

**Comment by jsuarezruiz** [comment]
Found the cause of the problem. The binding from ContentPresenter changed here https://github.com/dotnet/maui/commit/4c3a09c249f0b6a0980c99e160a9985749c761bb#diff-f01d408e1d2b3cd4a4c1bcf731586c215c9d57d4585d6815d5c89118a1ef3f44R20 (changes to allow trimming).
