### ISSUE TITLE
[Bug] ToolbarItems not rendered in Windows app

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#2589]
### Description
ToolbarItems not rendered in Windows app

### Steps to Reproduce

1. New Maui app
2. Edit MainPage.xaml.cs constructor and add following code:

           ToolbarItems.Add(new ToolbarItem()
            {
                Text = "Bla",
            });

3. Edit App.xaml.cs and change MainPage assignment to:
            MainPage = new NavigationPage(new MainPage());

4. Run with Windows Machine

### Expected Behavior
Toolbar button should appear

### Actual Behavior
Toolbar button does not appear

### Basic Information

- Version with issue: Maui preview 8
- IDE: VS2022 preview 4
- Platform Target Frameworks: Windows

### Workaround
None

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EasbXlc-tTdHoal0jDeCuscBXTuCfalXPASzRoR3CQjV4g?e=ZqES2R

**Comment by Redth** [comment]
Fixed in a newer release.
