### ISSUE TITLE
.NET MAUI 9 does not support Android 14.0 (API 34)

### ISSUE THREAD

**Issue by SorenBech2** [dotnet/maui#25898]
### Description

Creating a new .net MAUI 9 app using Visual Studio 17.12.0 through 
File > New > Project (updating nuget packages to latest version 9.0.10)  

and subsequently selecting the target android framework through:	
Project > Properties > Application > Android Targets
 
Selecting Android 14.0 renders an entry in the .csproj file as per below:
\<TargetFrameworks\>net9.0-ios;net9.0-maccatalyst;**net9.0-android34.0**\</TargetFrameworks\>

When trying to build the app to a Android 14.0 device (Samsung) below error message is received: 
**Error (active)      NETSDK1140	34.0 is not a valid TargetPlatformVersion for Android. Valid versions include: 35.0	
MauiApp1 (net9.0-android34.0)	C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	259**

If the API version is removed from the .csproj file 
\<TargetFrameworks\>net9.0-ios;net9.0-maccatalyst;**net9.0-android**\</TargetFrameworks\>

the following error displays when trying to build (release configuration):
**The project cannot be launched for Android. Please chech the error log for more details.**
 
If trying to build/deploy in debug configuration, the app builds and crashes while displaying flash screen with no error messages at all.

(For description including screen shots see attached document[dotnet 9 maui does not support Android14.docx](https://github.com/user-attachments/files/17783882/dotnet.9.maui.does.not.support.Android14.docx)

### Steps to Reproduce

See description above

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100

### Affected platforms

Android

### Affected platform versions

Android 14

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
Unless I'm mistaken you can't target API 34 with Android on .NET 9 (and thus .NET MAUI on .NET 9) @jonathanpeppers ?

Also see: https://github.com/dotnet/maui/issues/24260#issuecomment-2291695989

So the only issue I see here is that you're actually able to select 34 through Visual Studio. Unfortunately, that is something that is outside of the scope of this repository and we have no great way of moving tickets between these systems. I'll add a label on here with instructions on how to report it to Visual Studio so that it lands with the right team.

**Comment by SorenBech2** [comment]
Hi Gerald et all


I hope that your assumption, that Android API 34 cannot be targeted on .NET 9 is not true.
It seems a bit premature to skip API 34 just yet, as Samsung does not ship API 35 until 2025 . There is no specific dates for when Android 15 is available on all Samsung devices - meaning it could be well into 2025 before .NET 9 then becomes relevant to businesses that are developing mobile apps. Samsung being the largest suppler of mobile devices ensuring  a mobile app runs on Samsung devices is paramount.
If your assumption is true, then .NET 9 is more or less irrelecant as .NET 10 would then be the version to go fore. This could be a solution, if it wasn’t for the case, that .NET 8 MAUI has so many issue and .NET 9 hopefully should bring (much) more robustness to MAUI.
Please confirm/reject, that your assumption holds.



________________________________

**Comment by AlleSchonWeg** [comment]
Perhaps this issue could help: https://github.com/dotnet/android/issues/8331 (It explains it for .Net 8. But 9 should be analog)

But with target API 35 (.Net 9) you can install your app on devices lower than 35. SupportedOSPlatformVersion controls the android:minSdkVersion. If you set this to 27 for example you can install your app on devices >= API 27
If you receive a crash you could look at the logcat for expample.

**Comment by aspnetde** [comment]
@jonathanpeppers 

> .NET 9: Defaults to TargetPlatformVersion=35, targetSdkVersion=35

My understanding of this (and everything I found while going through the docs for the last hour or so) is that it should still be possible to target any other target platform version besides the default, e.g., `net9.0-android34.0`. However, that does not seem possible, as, in fact, it results in:

```
Microsoft.NET.TargetFrameworkInference.targets(259,5): Error NETSDK1140 : 34.0 is not a valid TargetPlatformVersion for Android. Valid versions include:
35.0
```

In our case we are about to upgrade to dotnet 9 but want to stick with targeting SDK 34 for a while as there are some [chores](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge) needed to make it properly work with SDK 35.

Just to make it clear: That's not possible – dotnet 9 is tied to SDK 35 and that is what it is for now. Correct?

**Comment by jonathanpeppers** [comment]
@aspnetde you have two options if you want to _target_ `android.jar` from API 34:

1. Stay on .NET 8
2. Add `<uses-sdk android:targetSdkVersion="34" />` manually in your `AndroidManifest.xml`. This will have a build warning, you would just ignore.

I haven't tried no. 2, but I think it will work. You could possibly get a build error if you use API-35-only APIs from C#.

**Comment by aspnetde** [comment]
@jonathanpeppers Thank you!
