### ISSUE TITLE
Cross platform UX for .NET 5

### ISSUE THREAD

**Issue by 4creators** [dotnet/maui#259]
.NET Core does not support directly any desktop or mobile UI. It was designed and implemented without such a goal at least up to v2.1.0. Nevertheless, it is a feature which potentially may expand usage scenarios very significantly. It is one of the oldest and most voted up features on Visual Studio UserVoice as well.

- [Bring Windows 10 Universal Apps to Android and iOS](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/8912350-bring-windows-10-universal-apps-to-android-and-ios) **3 658 Votes**

- [Create a Ubiquitous .NET Client Application Development Model](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/10027638-create-a-ubiquitous-net-client-application-develo) **11 213 Votes**

Microsoft and Xamarin jointly own an XAML based UX code stack (WPF, UWP, Xamarin Forms, WinUI) which could form a basis for .NET 5 UX stack. Unfortunately, work on [XAML-Standard](https://github.com/Microsoft/xaml-standard) has stalled despite that IMHO it would be a good place to make decision about UX in .NET 5.

Even more important [Microsoft Fluent Design](http://fluent.microsoft.com/) could be adopted in Core UX at least on Windows if not at least partially on other platforms. This would put .NET Core on bleeding edge of modern, universal xplat framework development.  Currently I would prefer to run Microsoft Fluent API based app on my Mac. It was quite different at Windows Vista and 7 times (I work daily on both Mac and Windows).

One of the most important requirements would be a hardware support. Providing that MSFT and Xamarin currently use DirectX and OpenGL based technologies one should be able with significant investment  create modern hardware accelerated graphics/media cross platform backend. This would as an additional benefit allow for providing modern graphics API as an alternative to outdated  [System.Drawing API](https://github.com/dotnet/corefx/issues/20325) resurrected for .NET Core v2.1.0 

Related not only DotNet issues:

[Port System.Xaml to .NET Core](https://github.com/dotnet/corefx/issues/5766)

[Include WPF in the standard (XAML Standard)](https://github.com/Microsoft/xaml-standard/issues/20)

[Port Winforms to CoreFX](https://github.com/dotnet/corefx/issues/21803)

[XAML Standard scope discussion](https://github.com/Microsoft/xaml-standard/issues/222)

[WinUI 3.0 roadmap - we need your input!](https://github.com/microsoft/microsoft-ui-xaml/issues/717)

## It's good time to start porting them to other platforms

- https://github.com/dotnet/wpf

- https://github.com/dotnet/winforms

- https://github.com/Microsoft/microsoft-ui-xaml

### Last updated 2019-05-20

**Comment by terrajobst** [comment]
I believe this issue is addressed by this repo.
