### ISSUE TITLE
Tailwindcss has no intellisense in MAUI App

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/maui#2590]
I installed the tailwindcss framework but the intellisense is not working for this. It only works for Visual Studio Code using a Extension.

**Comment by Eilon** [comment]
Hi @HeroinGyrl , can you upload your project to a GitHub repo so that we can investigate what's happening?

**Comment by HeroinGyrl** [comment]
hey @Eilon I just created a MAUI Blazor App and installed this [tailwind framework](https://codewithmukesh.com/blog/integrating-tailwind-css-with-blazor/). however I cant use the intellisense of this framework.

**Comment by Eilon** [comment]
OK, so you use `npm` to install tailwindcss into the MAUI Blazor app? Can you provide more info on which intellisense isn't working? Can you show a screenshot of where you are expecting to see it?

**Comment by HeroinGyrl** [comment]
Sure @Eilon , I installed tailwindcss and it fully works I can use as example
```html
<div class="min-h-screen bg-black"></div>
```
this will make the whole app black. but the intellisense does not work here so I have to acutally go to the tailwindcss playaround
https://play.tailwindcss.com/ and design there my app and then copy the code into my blazor app. what I want is that visual studio can use the intellisense of tailwindcss like in their website.

Intellisense working in https://play.tailwindcss.com/ 
![23232e2e](https://user-images.githubusercontent.com/33988671/134043347-353ee513-2f91-4e3d-9504-4e98c3633dd8.gif)

Intellisense not working in Visual Studio 2022 Preview 
![23232e2e2323](https://user-images.githubusercontent.com/33988671/134043391-e6ba91f0-100b-4c9a-b2f6-a2df6559b12d.gif)
4

**Comment by Eilon** [comment]
Does the app work as expected when you run it, in terms of loading the CSS and displaying it as you expect?

**Comment by HeroinGyrl** [comment]
@Eilon Yes everything works fine. I only want that there is a intellisense support for tailwindcss

**Comment by iamgmd** [comment]
We need first class support for tailwindcss in Visual Studio :-)

**Comment by kblyr** [comment]
I'm trying to use TailwindCSS in my Blazor Web Assembly app, and the intellisense will help a lot.

**Comment by Eilon** [comment]
Thanks for the issue report! Could you use the [VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report the issue? That way it will get to the routed to the right that owns this experience in VS.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks.
