### ISSUE TITLE
VS upgrade to 17.12 fails to recognize iOS simulators from XCode 16.1

### ISSUE THREAD

**Issue by npagare** [dotnet/maui#25904]
After upgrading VS to 17.12, I'm getting errro of No Simulators (XCode mismatch).
**_Please help?_**
Thank you

![image](https://github.com/user-attachments/assets/153b5d01-200a-4edc-9a75-31a5e4221196)

Here is the workload on the PC
![image](https://github.com/user-attachments/assets/cb165877-0441-4f35-a45f-4fcee9878254)

On Mac, I have XCode 16.1 installed
![image](https://github.com/user-attachments/assets/032f634a-4d02-491a-a966-fd24e4b5da72)

Available simulators on Mac
![image](https://github.com/user-attachments/assets/3de3fdad-bc8a-49fa-8668-49cd4bceac83)

_Originally posted by @npagare in https://github.com/dotnet/maui/discussions/25803#discussioncomment-11279929_

**Comment by jfversluis** [comment]
I think 16.1 is not yet supported. Use [Xcodes](https://www.youtube.com/watch?v=Lpq3-5VdizA) to manage versions and use Xcode 16 for now.

@dalexsoto @rolfbjarne ?

**Comment by npagare** [comment]
Thank you @jfversluis.

Hello @dalexsoto, @rolfbjarne - any ETA on support for 16.1? Thanks

**Comment by maonaoda** [comment]
I use Xcode 16.1 RC and can show the simulator

**Comment by jfversluis** [comment]
> I use Xcode 16.1 RC and can show the simulator

You can't right now, you'll have to use Xcode 16.0 for the time being. As indicated by Rolf just above here, probably .NET 9 Service Release!

Stay tuned!

**Comment by maonaoda** [comment]
@jfversluis 

> You can't right now, you'll have to use Xcode 16.0 for the time being. As indicated by Rolf just above here, probably .NET 9 Service Release!
> 
> Stay tuned!

Are you serious?
![Image](https://github.com/user-attachments/assets/f1edb456-a602-4587-8272-0afcca70c37e)
![Image](https://github.com/user-attachments/assets/9411aba6-70e5-4d3a-85f0-f3cc4892c69c)

**Comment by jfversluis** [comment]
Guess the release candidate didn't include the breaking change yet that they added to 16.1 final version.

We recommend using 16.0 for now, anything beyond that is not officially supported at the time being.

**Comment by npagare** [comment]
@jfversluis , 
Is .Net 9 workload for Maui iOS compatible with Xamarin Forms?
