### ISSUE TITLE
[9.0] [iOS] [Regression] - ToolbarItem color when used with IconImageSource is always white.

### ISSUE THREAD

**Issue by DevDachi** [dotnet/maui#25912]
### Description

In Maui 9 on iOS, ToolbarItem color when used with IconImageSource is always white. In Maui 8, we can set any color we want.

### Steps to Reproduce

1. Add a toolbar item to a page. e.g.

    ``` 
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Add" Command="{Binding NewCommand}" IconImageSource="{FontImage Glyph='+', Color=Green, Size=22}" />
    </ContentPage.ToolbarItems>
   ```
2. Build and run the app on iOS

Actual: The Icon color is white
Expected: The Icon color should be green (or whatever we set)

The following sample can used to repro this issue. This icon color is white on white toolbar; hence not visible.

https://github.com/dotnet/maui-samples/tree/main/9.0/Tutorials/ConvertToMvvm

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/9.0/Tutorials/ConvertToMvvm

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 17, 18

### Did you find any workaround?

No

### Relevant log output

```shell

```

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1(9.0.10 & 9.0.0 & 8.0.100). Can repro this issue on iOS platform. And 8.0.100 works fine.

**Comment by Gekidoku** [comment]
For now i found a workaround for shellpages. It makes the icon clear and its not dynamic. so doesnt accept a different color for each icon.
But you can ofcourse change it from clear to green. if all your icons need to be green. dont see another workaround yet.
https://stackoverflow.com/questions/78639479/toolbar-colored-icons-are-appearing-in-shell-foregroundcolor-property-on-ios/78645459#78645459

**Comment by Gekidoku** [comment]
Could use someone better than me at making handlers to make one for contentpages
