### ISSUE TITLE
Implement FormattedText in Controls

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#2591]
### Steps to Reproduce

```xaml
    <VerticalStackLayout>
        <Label Text="Regular label:"/>
        <Label Text="Test1"/>
        <Label Text="FormattedText label:"/>
        <Label >
            <Label.FormattedText>
                <FormattedString>
                    <Span Text="Test2"></Span>
                </FormattedString>
            </Label.FormattedText>
        </Label>
    </VerticalStackLayout>
```
EDIT: The implementation of this is not quite finished - see https://github.com/dotnet/maui/pull/3637

### Expected Behavior

Regular label:
Test1
FormattedText label:
Test2

### Actual Behavior
![image](https://user-images.githubusercontent.com/17177729/133944633-d5d9e52e-0282-4996-961b-05d8de864ddd.png)

### Basic information
I have tested it on Android only (Pixel 4 API 30), and don't know whether it reproduces on other platforms.

### Repro project
[MauiApp3.zip](https://github.com/dotnet/maui/files/7193011/MauiApp3.zip)

**Comment by Axemasta** [comment]
+1 seeing this issue with Win UI

**Comment by IndianaGary** [comment]
I have tested the same sample on WINUI and it doesn't work there either.

**Comment by chris-ux** [comment]
+1 WinUI

**Comment by hartez** [comment]
> +1 seeing this issue with Win UI

Please open a separate issue for Win UI.
