### ISSUE TITLE
DisplayPromptAsync does not accept Enter Key Press from scanner data read

### ISSUE THREAD

**Issue by delwarthink** [dotnet/maui#25932]
### Description

I've this below code to receive barcode data from scanner. Scanning barcode does not accept Enter key press of the scanner and I've to press OK button to continue.   This is very unproductive on business operation. On scanning a barcode DisplayPromptAsync should return the value of the barcode by automatically triggering OK/accept button.

va barcode= await DisplayPromptAsync("Barcode","Scan Barcode","OK","Cancel",initialValue:"");

### Steps to Reproduce

1. Create a simple Maui app.
2. Add simple DisplayPromptAsync to read scanner data.
va barcode= await DisplayPromptAsync("Barcode","Scan Barcode","OK","Cancel",initialValue:"");
4. Scan a barcode.
5. Display stays open just displaying the scanned value and does not act on scanner Enter key press \n.

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

Android

### Relevant log output

```shell

```

**Comment by delwarthink** [comment]
Hi, I've added the sample project to git. 
1. Please run it on any barcode scanner android device. I used Honeywell CT47.
2. Click the button which will open a DisplayPromptAsync
3. Scan a barcode and you'll see DisplayPromptAsync is not accepting scanner Enter key press and stays on screen. You'll have to touch on 'Ok' to get the data, which is unproductive.

https://github.com/delwarthink/DisplayPromptAsync.git

**Comment by jfversluis** [comment]
Just for my understanding... I don't think this has ever worked like that, right? So basically this is a feature request more than anything?

I think these prompts and dialogs on the platforms do not out of the box support this type of behavior. Did this work in Xamarin.Forms? Does it work if you use a dialog in Android without using .NET MAUI?

Personally I think you probably want to implement this another way and not through these prompts.

**Comment by delwarthink** [comment]
This should be a basic required feature for a input dialogue to accete Enter key press event. Could you please consider adding this feature for greater interest of the microsoft community?
