### ISSUE TITLE
[Android, IOS, Mac] Unable to Remove Thumb Image in Slider Control

### ISSUE THREAD

**Issue by NafeelaNazhir** [dotnet/maui#25939]
### Description

When the ThumbImageSource property of the Slider control is set to a valid image source (e.g., image_source.png), the image is displayed correctly on the thumb. However, if the ThumbImageSource is later set to null or an empty value (to remove the image), the image remains visible on the thumb, and it cannot be cleared
![Image](https://github.com/user-attachments/assets/c884e7f5-14f4-464d-9c4a-91e23b7d587b)
 1. Click Thumb Image button
![Image](https://github.com/user-attachments/assets/1e5eb3e8-b0e9-48aa-a736-5e407a892b19)
 2.. Click Reset Button , thumb image is not removed
![Image](https://github.com/user-attachments/assets/dd75f864-5354-4578-8609-208eb9eb5a4e)

 

### Steps to Reproduce

1. Click Thumb Image button
2. Click Reset button 
3. Observe thumb image is not removed.
4. [SliderSampleTest (2).zip](https://github.com/user-attachments/files/17811208/SliderSampleTest.2.zip)

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Android, macOS, iOS

### Relevant log output

```shell

```

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.13.0 Preview 1.0 (9.0.10 & 9.0.0-rc.2.24503.2 &8.0.100 &8.0.3). Can repro on Android &iOS platform.
