### ISSUE TITLE
[iOS] Editor when entering a text which exceeds the maximum height resets the position

### ISSUE THREAD

**Issue by SuthiYuvaraj** [dotnet/maui#25938]
### Description

Create a Editor with MaximumHeight and AutoSize as TextChanges , when the text exceeds the maximum height ,each time when you enter the text , the frame gets resetted to the default position

### Steps to Reproduce

1.Create a MAUI project 
2. Add Editor with MaximumHeight and AutoSize as TextChanges 
`     
 <VerticalStackLayout>
            <Editor BackgroundColor="Yellow"
                    AutoSize="TextChanges"
                    MaximumHeightRequest="200"   />
        <Label Text="Editor iOS Bug Demonstration:
                    - Editor does maintains the position , each the frame get resetted to default)"/>
 </VerticalStackLayout>
`
3.Expected Behavior : Scroller should maintain the same position
4.Actual Behavior : Odd flicker due to reset , we need to scroll to see the text entered[TestMaui.zip](https://github.com/user-attachments/files/17811387/TestMaui.zip)

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Relevant log output

```shell

```

**Comment by tj-devel709** [comment]
Also verified that this happened in .NET 8 as well!

**Comment by SuthiYuvaraj** [comment]
This appears to be an issue where `UITextView` and `UIScrollView` fail to reset their offset appropriately when text is entered. The behavior becomes more noticeable when using the Return key to add new lines or spaces, causing the visible content to exceed the bounds of the view without proper scrolling adjustments

https://github.com/user-attachments/assets/a298df81-2193-401b-aa65-cde41cf21428

**Comment by kubaflo** [comment]
Hi, @tj-devel709 this PR fixes this:https://github.com/dotnet/maui/pull/26087 though it was aimed to fix a different bug 😅

**Comment by snice1981** [comment]
Same problem here...

Any fix soon or any workaround?
