### ISSUE TITLE
iOS hangs when choosing to Select All text on an Editor when AutoSize = TextChanges

### ISSUE THREAD

**Issue by InquisitorJax** [dotnet/maui#25940]
### Description

When adding an Editor to the AutoSize property set to TextChanges... adding a bunch of text and then tapping the editor to make use of the "Select All" option from UITextView freezes the app:

![Image](https://github.com/user-attachments/assets/c1f554fd-e8e3-4ff6-a67c-c8ae23c55add)

### Steps to Reproduce

Craete the default new Maui app, and add an editor:

`<Editor HorizontalOptions="Fill" BackgroundColor="Yellow" AutoSize="TextChanges"/>`

When you type in a bunch of text, and the choose the "Select All" from the UITextView options, the app will freeze.

Full main page:
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.MainPage">

        <VerticalStackLayout
            Padding="30,0"
            Spacing="25">
            <Image
                Source="dotnet_bot.png"
                HeightRequest="185"
                Aspect="AspectFit"
                SemanticProperties.Description="dot net bot in a race car number eight" />

            <Label
                Text="Hello, World!"
                Style="{StaticResource Headline}"
                SemanticProperties.HeadingLevel="Level1" />

            <Label
                Text="Welcome to &#10;.NET Multi-platform App UI"
                Style="{StaticResource SubHeadline}"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I" />

            <Button
                x:Name="CounterBtn"
                Text="Click me" 
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Fill" />

            <Editor HorizontalOptions="Fill" BackgroundColor="Yellow" AutoSize="TextChanges"/>
        </VerticalStackLayout>

</ContentPage>
```

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18.1

### Did you find any workaround?

Yes - see custom handler implementation in this [issue](https://github.com/dotnet/maui/issues/17757)

### Relevant log output

```shell

```

**Comment by Ying-6** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1(9.0.10 & 9.0.0 & 8.0.100). Can repro this issue on iOS platform.

**Comment by formerlymisterhenson** [comment]
Maybe this can be fixed with the workaround mentioned in https://github.com/dotnet/maui/issues/17757 as this worked for me for a very similiar freezing issue (mark bigger chunks of text fast).

**Comment by InquisitorJax** [comment]
I can confirm that the work-around fixes the issue - thanks @formerlymisterhenson :)
