### ISSUE TITLE
[Bug] There are no example NUnit or MSTest projects for testing Maui libraries using VS 2022 preview 4

### ISSUE THREAD

**Issue by Zachael** [dotnet/maui#2594]
Prior to the introduction of workloads, it was possible to write NUnit projects for a Maui library. The project created virtual controls within a Windows executable without creating the native controls. 

With VS 2022 preview 4, the project gives the error:
**The framework 'Microsoft.Maui.Core', version '**FromWorkload**' (x64) was not found.**

It was also possible to write MSTest unit tests that launched the unit tests as a MSIX application using the the following code in App.xaml.cs (using MSTest.TestFramework, MSTest.TestAdapter, Microsoft.TestPlatform.TestHost and coverlet.collector).

```
protected override void OnLaunched(LaunchActivatedEventArgs args)
{
     base.OnLaunched(args);

     Microsoft.Maui.Essentials.Platform.OnLaunched(args);

     Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.CreateDefaultUI();

     UITestMethodAttribute.DispatcherQueue = MainWindow.DispatcherQueue;

     Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.Run(Environment.CommandLine);
}
```

With VS2022 preview 4, the MSTest project gives the error:
**error CS7069: Reference to type 'DispatcherQueue' claims it is defined in 'Microsoft.WinUI', but it could not be found**

What is the guidance for writing unit tests which can be run within VS for testing Maui libraries for Windows?

**Comment by Eilon** [comment]
Dup of https://github.com/dotnet/maui/issues/2112
