### ISSUE TITLE
.NET Maui app crashes on startup on 17.10.5

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#25963]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-Maui-app-crashes-on-startup-on-171/10784465)._

---
[regression] [worked-in:17.10.3]
I have one instance of VS version 17.10.3 which runs my .NET Maui app ok and a newer installation 17.10.5 which crashes on startup.  I rolled back to 17.10.3 and it works again.

The version 17.10.5 that failed was a Community one.

---
#### Feedback Bot on 11/6/2024, 05:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Zack Yang [MSFT] on 11/6/2024, 10:01 PM: 

<p>Could you please follow these steps to provide a memory dump so we can inspect the VS crash properly?</p>
<ol>
<li>Open one VS which will be used to reproduce crash issue.</li>
<li>Open another VS instance and attach to the 1st VS process (<code>Ctrl + Alt + P</code> or <code>Debug &gt; Attach to Process… &gt; Select the 1st VS process (devenv.exe) from the Process list</code>)</li>
<li>Click on <code>Attach</code></li>
<li>Reproduce the issue in 1st VS</li>
<li>Then debug VS will throw exception</li>
<li>Save the Dump (<code>Debug &gt; Save Dump As...</code>) and select <code>Minidump with Heap (*.dmp)</code> from the file dialog</li>
<li>Attach the resulting dump</li>
</ol>
<p>Take into account that the size of the dump is usually big, so it could take a while to attach.<br>
If the dump file is too large to attach here, you can upload the dump file to a shared location like OneDrive, Github, Google drive, then share the path to us.</p>
<p>Thanks in advance.</p>

#### Craig Wittenberg on 11/7/2024, 09:36 AM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 11/8/2024, 01:05 AM: 

<p>This feedback is being re-triaged as we are moving it to another team that can better help with the issue. Thanks for your patience.</p>

**Comment by PureWeen** [comment]
can you run 

dotnet workload list

When running VS 17.10.5 and then when you've reverted to VS 17.10.3? 

So we can see if different version of MAUI are causing you issues?

If you update to 17.11 or 17.12 do you see the same issues?
