### ISSUE TITLE
App fails to inject INavigationRootManager when using PushModalAsync

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#25961]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/App-fails-to-inject-INavigationRootManag/10789059)._

---
[severity:Other]
Summary: 

After using the MAUI app for a certain amount of time (periods that can range from a few hours to a week and a half depending on the tests done), the program has an exception due to an injection of internal dependency (No service for type 'Microsoft.Maui.Platform.NavigationRootManager' has been registered.).  
When investigating the Memory Trace we can see that there are several instances of the NavigationRootManager at the time of the exception. And that some time before it, the garbage collector deletes an instance of NavigationRootManager, probably causing the error. 
In the same way, we have noticed a memory leak in each view. Each time a modal is initialized, the class that initialized it remains in memory forever. 
Any task that is performed on the MainPage seems to reduce the time that the application can remain stable. (It seems that the memory leak is getting worse) 

Context and code: 

MAUI Program.cs
1. public static MauiApp CreateMauiApp()
        {
            MauiAppBuilder builder = MauiApp.CreateBuilder();

// Add NLog for Logging
            Builder. Logging.ClearProviders();
            Builder. Logging.AddNLog();

Builder
                . UseMauiApp&lt;App&gt;()
                . ConfigureFonts(fonts =&gt;
                {
                    Fonts. AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    Fonts. AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                    Fonts. AddFont("cour.ttf", "Courier New");
                });

SetupSerilog();

Builder. Logging.AddSerilog(dispose: true);
            Configuration to pull Info level logs
            LogManager.Setup(). RegisterMauiLog()
                . LoadConfiguration(c =&gt; c.ForLogger(NLog.LogLevel.Info). WriteToMauiLog())
                . GetCurrentClassLogger();
            Only for Windows we apply the maximized and hide bar confiration
#if WINDOWS
            Builder. ConfigureLifecycleEvents(events =&gt;
            {
                Make sure to add "using Microsoft.Maui.LifecycleEvents;" in the top of the file
                Events. AddWindows(windowsLifecycleBuilder =&gt;
                {
                    windowsLifecycleBuilder.OnWindowCreated(window=&gt;
                    {
                        window. ExtendsContentIntoTitleBar = false;
                        window. Closed += (sender, eventArgs) =&gt;
                        {
                            MainPageUtil.CloseApp();
                        };
                        nint handle = WinRT.Interop.WindowNative.GetWindowHandle(window);
                        Microsoft.UI.WindowId id = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(handle);
                        Microsoft.UI.Windowing.AppWindow appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(id);
                        switch (appWindow.Presenter)
                        {
                            case Microsoft.UI.Windowing.OverlappedPresenter overlappedPresenter:
                                We've hidden the top bar of the app and removed the maximized and minimized options
                                overlappedPresenter.SetBorderAndTitleBar(false, false);
                                overlappedPresenter.IsMaximizable = false;
                                overlappedPresenter.IsMinimizable = false;

We maximize the screen
                                overlappedPresenter.Maximize();
                                break;
                        }
                    });
                });
            });
            
#endif

Return Builder. Build();
        }

The exception can occur in any Method that calls the PushModalAsync method of the INavigation interface.
The block of code in which this exception is most frequent is the following (taking into account that it is also the most frequently invoked modal) 

1. MainThread.BeginInvokeOnMainThread(async() =&gt;
   {
           if (this. Navigation.ModalStack.Count == 0 || this. Navigation.ModalStack.First(). GetType(). Name == "NavigatorModal")
           {
               var modalNav = new(message);
               await this. Navigation.PushModalAsync(modalNav);
           }});
The time of the application running and the number of modals you can open before the error appears varies, ranging from a few modals to more than 2,000.

Versions

.NET: It's the same with . NET7 as with . NET8
MAUI Workload: 
android 34.0.143/8.0.100 SDK 8.0.400, VS 17.11.35327.3
aspire 8.2.2/8.0.100 SDK 8.0.400, VS 17.11.35327.3
ios 18.0.8303/8.0.100 SDK 8.0.400, VS 17.11.35327.3
maccatalyst 18.0.8303/8.0.100 SDK 8.0.400, VS 17.11.35327.3
maui-tizen 8.0.83/8.0.100 SDK 8.0.400
maui-windows 8.0.83/8.0.100 SDK 8.0.400, VS 17.11.35327.3
wasm-tools-net7 8.0.10/8.0.100 SDK 8.0.400, VS 17.11.35327.3

Platform

Windows 10, Windows 11. The instability is much greater in Windows 10. In a production environment using Windows 11 the application can run for 2 weeks without failures, while in Windows 10 the maximum it has been without terminal exceptions is 2 days. 

WorkArounds

Numerous workarounds were tried, but none have worked. 
Attempts were made to declare the pages (MainPage, Modales, etc...) as Singleton to avoid the memory leak, the memory leak disappeared, but dependency injection continued to fail. 
In MauiProgram.cs
1. Builder. Services.AddSingleton&lt;MainPage&gt;();
            Builder. Services.AddSingleton&lt;FormModal&gt;(); //modal1
            Builder. Services.AddSingleton&lt;AlertManager&gt;(); //modal2

modal N

An attempt was made to tie the INavigation to a static variable so that the Garbage Collector does not clean the NavitationRootManger. 

An attempt was made to prevent the MainPage from executing the code on the MainThread. (Remove the MainThread Invoke) 
	     var modalNav = new(message);
               await this. Navigation.PushModalAsync(modalNav);

An attempt was made to make modal calls synchronous with . Wait() to limit the number of processes that run when opening or closing a modal. 
	Attempted to Stop Accessing Navigation by the Navigation property of the page (Ex, FormModal extending from ContentPage) and accessed via "Application.Current.MainPage.Navigation") 

We tried to put a delay of 250ms both in the opening of modals and in the closing of them. 

Error log: 

No service for type 'Microsoft.Maui.Platform.NavigationRootManager' has been registered. Stacktrace: at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) Frame:GetRequiredService at offset 18622385 in file:line:column &lt;filename unknown&gt;:0:0
One or more errors occurred. (No service for type 'Microsoft.Maui.Platform.NavigationRootManager' has been registered.) Stacktrace: at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Frame:ThrowIfExceptional at offset 54 in file:line:column &lt;filename unknown&gt;:0:0

Reproduce the error: 
1. Create a MAUI app 
2. Create two simple manners. 
3. Modal 1 must invoke modal 2 from:
1.  .     MainThread.BeginInvokeOnMainThread(async() =&gt;
   {
           if (this. Navigation.ModalStack.Count == 0 || this. Navigation.ModalStack.First(). GetType(). Name == "NavigatorModal")
           {
               var myModal = new(myParams);
               await this. Navigation.PushModalAsync(myModal);
           }})
Wait for the error to appear, the number of manners to open is variable and depends on the computer. To observe the problem at the memory level, open the diagnostic tool and take snapshots of the memory. 

Equipment specifications of an affected machine: 

Windows 11 Pro Edition
Version 23H2
Installed on 25/04/2024
OS version 22631.4317
Windows Experience Feature Experience Pack 1000.22700.1041.0
Device Name RMD-LGD-CL-XX00
Full name of the device RMD-LGD-CL-XX00.ramondin.es
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz 3.60 GHz processor
Installed RAM 16.0 GB
Device ID DB0ACE71-7C4E-4195-8C78-BF4645A7540A
Product ID: 00330-80000-00000-AA903
System Type 64-bit operating system, x64-based processor
Pen and touch input Touch or inking is not available for this display

Notes: 
1. Computer resources are healthy at the time of the error. There is no lack of resources either at the CPU level or at the memory level. 
2. We don't use Shell. 

Memory leak issues on all platforms: 

https://github.com/dotnet/maui/issues/20094 
https://github.com/dotnet/maui/issues/21143
https://github.com/dotnet/maui/issues/21453
Post of more memory leaks: 
https://github.com/dotnet/maui/wiki/Memory-Leaks

---
#### Feedback Bot on 11/13/2024, 06:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by LucasC-Extreme-IT** [comment]
Hi, 

We tried the update to MAUI9 and that didn't solved our issue. We have already sent the code.  (related to #25833)
