### ISSUE TITLE
Improve error message when users are referencing a .NET 9 NUGET from a .NET 8 TFM

### ISSUE THREAD

**Issue by santo998** [dotnet/maui#25970]
### Description

In a class under my Windows platform folder, the following types are missing:
Microsoft.UI.Xaml.Application
Microsoft.UI.Xaml.UnhandledExceptionEventArgs

This happened after updating these packages:
Microsoft.Maui.Controls 8.0.92 → 9.0.10
Microsoft.Maui.Controls.Compatibility 8.0.92 → 9.0.10

<details>
<summary>This is my .csproj (targeting net8.0-*)</summary>

```xml

<Project Sdk="Microsoft.NET.Sdk">
	
	<!-- Versión -->
	<PropertyGroup>
		<VersionPrefix>0.14.8</VersionPrefix>
		<!--<VersionSuffix Condition="'$(DesignTimeBuild)' != 'true' OR '$(BuildingProject)' == 'true'">beta-$([System.DateTime]::UtcNow.ToString(yyyyMMdd-HHmmss))</VersionSuffix>-->
	</PropertyGroup>

	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AssemblyVersion></AssemblyVersion>
		<FileVersion></FileVersion>
	</PropertyGroup>

	<!-- Android -->
	<ItemGroup Condition="$(TargetFramework.StartsWith('net8.0-android')) != true">
		<Compile Remove="**\Android\**\*.cs" />
		<None Include="**\Android\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<!-- Both iOS and Mac Catalyst -->
	<ItemGroup Condition="$(TargetFramework.StartsWith('net8.0-ios')) != true AND $(TargetFramework.StartsWith('net8.0-maccatalyst')) != true">
		<Compile Remove="**\MaciOS\**\*.cs" />
		<None Include="**\MaciOS\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<!-- iOS -->
	<ItemGroup Condition="$(TargetFramework.StartsWith('net8.0-ios')) != true">
		<Compile Remove="**\iOS\**\*.cs" />
		<None Include="**\iOS\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<!-- Mac Catalyst -->
	<ItemGroup Condition="$(TargetFramework.StartsWith('net8.0-maccatalyst')) != true">
		<Compile Remove="**\MacCatalyst\**\*.cs" />
		<None Include="**\MacCatalyst\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<!-- Windows -->
	<ItemGroup Condition="$(TargetFramework.Contains('-windows')) != true">
		<Compile Remove="**\Windows\**\*.cs" />
		<None Include="**\Windows\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="9.1.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.10" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.10" />
		<PackageReference Include="Plugin.Maui.Audio" Version="3.0.1" />
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="src\Vistas\BasePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="src\Vistas\TareasPreviasBasePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="src\Platforms\MaciOS\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Amsoft.Base.DA\Amsoft.Base.DA.csproj" />
	  <ProjectReference Include="..\Amsoft.Base\Amsoft.Base.csproj" />
	</ItemGroup>

</Project>
```
</details>

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.92 SR9.2

### Affected platforms

Windows

### Relevant log output

```shell

```

**Comment by santo998** [comment]
@OvrBtn so, can't I update to MAUI 9 using .NET 8?

Then, shouldn't developers specify that MAUI 9 nuget requires .net 8, so it would give me an error when trying updating it?

**Comment by PureWeen** [comment]
> [@OvrBtn](https://github.com/OvrBtn) so, can't I update to MAUI 9 using .NET 8?
> 
> Then, shouldn't developers specify that MAUI 9 nuget requires .net 8, so it would give me an error when trying updating it?

Correct, I've updated the title of this issue

We should really throw a better exception when users are trying to reference net9 nugets inside a net8 project

**Comment by dellis1972** [comment]
> Another option here is to actually drop netstandard and use net47 or something for the IDE only? In our targets we can use net9.0 in apps and net4x in the IDE.
> 
> We lose the netstandard, but that is something we actually want, right?
> 
> [@Redth](https://github.com/Redth) [@PureWeen](https://github.com/PureWeen) [@mgoertz-msft](https://github.com/mgoertz-msft) [@mauroa](https://github.com/mauroa) [@jonathanpeppers](https://github.com/jonathanpeppers) [@dellis1972](https://github.com/dellis1972) any thoughts on this?

Not sure I get how using netstandard for the sdk stuff is related to this issue?

**Comment by mattleibow** [comment]
I can solve the problem by removing netstandard from the nuget package and instead building for net47. Does the Android workload have netstandard2.0 build tasks, or does it multitarget net8.0 and net4x?

I can either write a complex logic to detect a scenario where the user installed newer nugets into an older project - like maui 9 into net8 and then throw an error. Or, we can let NuGet install fail with a useful error message.

**Comment by dellis1972** [comment]
We only use netstandard2.0 cos it works everywhere.

**Comment by mattleibow** [comment]
OK, thanks!

I created a PR to report an error: https://github.com/dotnet/maui/pull/25993

@Redth should I investigate dropping netstandard and adding netfx as a TFM for msbuild tasks? That will be more work and require more changes. aka: scary But is maybe more correct and then NuGet does the real TFM work.
