### ISSUE TITLE
[Enhancement] Introduce an AppThemeColor

### ISSUE THREAD

**Issue by dansiegel** [dotnet/maui#2597]
## Summary

While the `AppThemeBinding` absolutely helps to achieve better experiences going between light/dark mode, it would be really great if we an `AppThemeColor` with the explicit intent of making it even easier to setup of Setup styles. This would reduce the amount of code that needs to be written to get the same result.

Currently for every single Named Color that we need for the color pallet, two colors must actually be added to the ResourceDictionary.

```xml
<ResourceDictionary>
  <Color x:Key="PrimaryColor">#1A237E</Color>
  <Color x:Key="PrimaryColorDark">#000051</Color>
</ResourceDictionary>
```

Then after adding all of the colors EVERY single style needs the much more verbose AppThemeBinding like:

```xml
<ResourceDictionary>
  <Style x:Key="PrimaryButton" TargetType="Button">
    <Setter Property="BackgroundColor" Value="{AppThemeBinding Default={StaticResource PrimaryColor}, Dark={StaticResource PrimaryColorDark}}" />
  </Style>
</ResourceDictionary>
```

## Proposal

Adding a new AppThemeColor could really make this a lot easier to deal with like:

```xml
<ResourceDictionary>
  <AppThemeColor Default="#1A237E" Dark="#000051" x:Key="PrimaryColor" />
  <Style x:Key="SecondaryButton" TargetType="Button">
    <Setter Property="BackgroundColor" Value="{AppThemeColor PrimaryColor}" />
  </Style>
</ResourceDictionary>
```

This would have the effect of much cleaner code, and make it easier to maintain as you would have a single point where you need to manage the actual color without concern that perhaps you had a copy paste error and mismatched the Default / Dark color.

**Comment by SF-Simon** [comment]
Hi, @Redth 

This idea has existed for more than a year. In fact, it is not difficult to implement, but it can greatly simplify the code and facilitate reading.

And, I think it should not rely on the community toolkit package to complete, because current applications should basically support brightness.

I hope the MAUI team can consider adding it to the version as soon as possible.

As for the tag name, I think this way may be more with expectations:
`<DefaultOrDark default=... dark=...></ DefaultOrDark>`

Will it become more important without limiting to color? 😀

**Comment by DoubleDBE** [comment]
I agree with @SF-Simon, this should be in the core product and not in a third party package.

**Comment by jfversluis** [comment]
For the time being this will be implement through the .NET MAUI Community Toolkit, you can currently follow the progress [here](https://github.com/CommunityToolkit/Maui/pull/1264). We are implementing both something for color as well as a generic version for resources and a way for you to implement your own custom type if needed.

Let's evaluate in the future if we can and should bring that over to be in .NET MAUI directly. Thanks for all the feedback and efforts here!

**Comment by jfversluis** [comment]
This is now released through the .NET MAUI Community Toolkit as part of [version 5.3.0](https://github.com/CommunityToolkit/Maui/releases/tag/5.3.0)
