### ISSUE TITLE
[Windows] Opening the flyout menu result in a binding failure

### ISSUE THREAD

**Issue by Natriss** [dotnet/maui#25995]
### Description

When you open and debug a .NET MAUI Windows app and open the navigation pane (flyout menu). It will give a binding failure.
Severity - Error
Count - 1
Data Context - Microsoft.UI.Xaml.Controls.SplitView
Binding Path - TemplateSettings.CompactPaneGridLength
Target - Microsoft.UI.Xaml.Media.Animation.SplineDoubleKeyFrame.Value
Target Type - Double
Description - Converter failed to convert value of type 'Windows.Foundation.IReference`1<Microsoft.UI.Xaml.GridLength>' to type 'Double'
File - null
Line - null
Project - null

https://github.com/user-attachments/assets/d3696e8a-34c6-49df-bd9b-3255d61cd1e3

### Steps to Reproduce

1. Create a .NET MAUI app
2. Set Shell.FlyoutBehavior to Flyout
3. Debug the app and open the Flyout

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041.0

### Relevant log output

```shell

```

**Comment by kevinxufei** [comment]
This issue cannot be reproduced at Windows platform on the latest 17.13 Preview 1(9.0.10 & 9.0.0),but it's worth mentioning that I reproduced this problem on 8.0.100.

**Comment by Natriss** [comment]
https://github.com/[Natriss/MauiFlyoutIssue](https://github.com/Natriss/MauiFlyoutIssue)
Because the video is too big I've uploaded on my OneDrive so you can see it.
It's a full process from start to end.
[Full video](https://1drv.ms/v/c/41b7b8151d009a6a/EYswkDQsOcNEktSThoXe7ngBiAwqq3t5e4rg3u-5CYWk0w?e=dbXzAz)

**Comment by Tamilarasan-Paranthaman** [comment]
@Natriss, I tested this with the latest Visual Studio **17.13 Preview 2.1 version (9.0.21)**, and the issue is not reproducible. I have attached a video for your reference below. Could you please check your current version, update it to the latest version if you are using an older one, and check if the issue still persists?

https://github.com/user-attachments/assets/924094f9-ad6c-4cfe-9289-744c5a82360c

**Comment by Natriss** [comment]
@Tamilarasan-Paranthaman 
With Visual Studio 17.12.3 and 17.13.0 Preview 2.1 + version 9.0.21, it's now fixed.
Now it also works with version 9.0.0, what I find weird, fixed is fixed :3
