### ISSUE TITLE
[Bug] Shell Flyout items are never deselected on Android

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#2600]
### Steps to Reproduce

```xaml
<Shell xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       x:Class="MauiApp3.MainPage">

    <FlyoutItem FlyoutDisplayOptions="AsMultipleItems">
        <ShellContent Title="Title1">
            <ContentPage/>
        </ShellContent>

        <ShellContent Title="Title2">
            <ContentPage/>
        </ShellContent>

        <ShellContent Title="Title3">
            <ContentPage/>
        </ShellContent>
    </FlyoutItem>

</Shell>
```

### Steps to reproduce
1. Select Title2
2. Select Title3

### Expected Behavior

1. Only Title 2 has selected background color
2. Only Title 3 has selected background color

### Actual Behavior
![0NOsss4x24](https://user-images.githubusercontent.com/17177729/134057425-7334dd4f-75cb-46ac-906c-eb8de8241b5b.gif)

### Basic information
I have tested it on Android only (Pixel 4 API 30), and don't know whether it reproduces on other platforms.

### Repro project

[MauiApp3.zip](https://github.com/dotnet/maui/files/7198003/MauiApp3.zip)

**Comment by PureWeen** [comment]
This will be fixed on P14
