### ISSUE TITLE
System.InvalidCastException when using a custom map handler on iOS and .NET 9.

### ISSUE THREAD

**Issue by kaniosm** [dotnet/maui#26000]
### Description

After updating to .NET 9 (MAUI 9.0.10) whenever opening my customized map control while the app is still looking for the GPS location the app crashes with the below error:
NativeHandle __Registrar_Callbacks__.callback_1320_MapKit_MKMapView__MKMapViewDelegate_GetViewForAnnotation(IntPtr pobj, IntPtr sel, IntPtr p0, IntPtr p1, IntPtr* exception_gchandle).
The same was not happening in .NET 8.
This is happening only in release mode.

### Steps to Reproduce

1. Create a new .NET 9 MAUI project.
2. Create a custom map hander with a handler to the GetViewForAnnotation.
3. Opt-out from automatic handler disconnect since this will crash the app after opening the map page for a second time. (see https://github.com/dotnet/maui/issues/20612).
4. Deploy the release build to a physical device.
5. Request the user location
6. Immediately open the map page

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS

### Relevant log output

```shell

```

**Comment by eerojaaskelainen** [comment]
Might be relative to #25762.

**Comment by kaniosm** [comment]
Thanks @eerojaaskelainen, 
It seems that the issue is indeed the same, but it's not happening all times.
In my case I noticed that it always happens whenever I open the map while the user location is still running, but I faced the same under different conditions that are more difficult to replicate.

I'll try to to reproduce this in a clear project and post here.
As commented on the other post, I believe it has to do with the cast of the user location to IMKAnnotation by looking at this from the original source.

// https://bugzilla.xamarin.com/show_bug.cgi?id=26416
var userLocationAnnotation = Runtime.GetNSObject(annotation.Handle) as MKUserLocation;

**Comment by kaniosm** [comment]
> Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
Sample project below.
In this project the issue is reproducible only in release.

[MauiMapTest.zip](https://github.com/user-attachments/files/17849226/MauiMapTest.zip)

**Comment by michaelonz** [comment]
I am seeing this issue also

**Comment by jfversluis** [comment]
Would someone maybe be able to create .NET for iOS app (`dotnet new ios`) and use a map in there that shows the user? Does that work? I looked into it for a little but it doesn't even hit my breakpoints in the .NET MAUI SDK, so I have a feeling this might be a level deeper...

Thanks!
