### ISSUE TITLE
[Bug] UriImageSourceService fails to load some images on Windows

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#2601]
### Steps to Reproduce

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       x:Class="MauiApp3.MainPage">

    <VerticalStackLayout VerticalOptions="Start">
        <Label Text="1:"/>
        <Image MaximumHeightRequest="80" 
            Source="https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Paintedcats_Red_Star_standing.jpg/187px-Paintedcats_Red_Star_standing.jpg"/>

        <Label Text="2"/>
        <Image MaximumHeightRequest="80" 
            Source="https://upload.wikimedia.org/wikipedia/commons/f/f6/Mammuthus_exilis.jpg"/>

        <Label Text="3"/>
        <Image MaximumHeightRequest="80" 
            Source="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Sphinx2_July_2006.jpg/180px-Sphinx2_July_2006.jpg"/>
    </VerticalStackLayout>

</ContentPage>
```

### Expected Behavior
All images are displayed.

### Actual Behavior
Only the first one is displayed. 

If you load the image inside a browser first then WinUI is able to load the image. 

Logs:
```
Microsoft.Maui.UriImageSourceService: Warning: Unable to load image URI 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Sphinx2_July_2006.jpg/180px-Sphinx2_July_2006.jpg'.

System.InvalidOperationException: Unable to load image stream.
   at Microsoft.Maui.UriImageSourceService.GetImageSourceAsync(IUriImageSource imageSource, Single scale, CancellationToken cancellationToken)

Microsoft.Maui.UriImageSourceService: Warning: Unable to load image URI 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Mammuthus_exilis.jpg'.

System.InvalidOperationException: Unable to load image stream.
   at Microsoft.Maui.UriImageSourceService.GetImageSourceAsync(IUriImageSource imageSource, Single scale, CancellationToken cancellationToken)
```

### Basic Information

- Version with issue: MAUI Preview 8
- SKD: net6.0-windows10.0.19041

It works fine on Android.

### Screenshots
![image](https://user-images.githubusercontent.com/17177729/134060875-d705a30a-f9b6-4de0-bb7c-f34b5175ed5c.png)

### Reproduction Link

[MauiApp3.zip](https://github.com/dotnet/maui/files/7198166/MauiApp3.zip)

**Comment by hartez** [comment]
I just opened the repro project and ran it on Windows, and it seems ... fine? All 3 images loaded.

![Screenshot 2021-09-20 155647](https://user-images.githubusercontent.com/538025/134081302-1d1259c4-62ca-45dc-87df-5d948bd5b41c.png)

**Comment by Dreamescaper** [comment]
Re-checked again - it's still same for me. And yes - happens every time. Is there any additional info I could provide?

**Comment by Dreamescaper** [comment]
OK, today I have this issue for all three of those images.

**Comment by Dreamescaper** [comment]
I've added the fourth image, which works fine (at least for now):
```xaml
        <Label Text="4"/>
        <Image MaximumHeightRequest="80" 
            Source="https://pbs.twimg.com/media/EY-hGd6UYAAIeLk.jpg"/>
```

And I can see that order is irrelevant.
![image](https://user-images.githubusercontent.com/17177729/134240488-f7f1b620-d83b-4f0d-807d-3c58628831f1.png)
![image](https://user-images.githubusercontent.com/17177729/134240581-0d0bc488-87dd-486f-b443-2e0a511ab35a.png)
![image](https://user-images.githubusercontent.com/17177729/134240658-f6f6e138-2a35-43d3-bbd3-cc5a212ab7fb.png)

**Comment by matt-goldman** [comment]
I've got a similar issue. Images don't load at al on Windows. Works fine on Android.

**Comment by PureWeen** [comment]
@Dreamescaper @matt-goldman if you go to the image first in your browser and then run the app again does it show up?

**Comment by matt-goldman** [comment]
@PureWeen I can try that if you like, although I have found that explicitly setting HeightRequest seems to make the image appear. Again only happens on Windows, on Android or iOS it shows up without it.

**Comment by Dreamescaper** [comment]
@PureWeen 
Yes, if I open the image in browser beforehand, it does show up.

**Comment by Amir-Care** [comment]
Repro,attached the repro sample[MauiApp14.zip](https://github.com/dotnet/maui/files/8122892/MauiApp14.zip)
When i run the project on Windows /Android Platform:
  Windows:  No image displayed, but If you load the image inside a browser first then WinUI is able to load the image.
  Android:  No image displayed

**Comment by VSadov** [comment]
I see a similar behavior. One image out of three did not show up. 
After looking at the URL in the browser, the image started to show. Possibly some timing/race issue.

**Comment by VSadov** [comment]
The error that I am getting is `Forbidden. Please comply with the User-Agent policy: https://meta.wikimedia.org/wiki/User-Agent_policy`

**Comment by marcusts** [comment]
This is now occurring to me on Maui iOS.  Android works fine.  It will stop me from using Maui (at least currently).

I can't see what image is causing the issue.  Stack trace:

```
System.InvalidOperationException: Unable to load image stream.
   at Microsoft.Maui.StreamImageSourceService.GetImageAsync(IStreamImageSource imageSource, Single scale, CancellationToken cancellationToken)
   at Microsoft.Maui.Platform.ImageSourcePartExtensions.UpdateSourceAsync(IImageSourcePart image, UIView destinationContext, IImageSourceServiceProvider services, Action`1 setImage, CancellationToken cancellationToken)}	System.InvalidOperationException

```

When will ".NET 7" milestones be completed?

**Comment by rachelkang** [comment]
@marcusts If you're still experiencing the issue on iOS, please open a new issue so that we can make to give it the needed attention!

**Comment by praveenmohanmm** [comment]
The issue still exists in ios, 
unable to load image URI 
System.InvalidOperationException: Unable to load image stream from URI '{your remote img url}'.
   at Microsoft.Maui.UriImageSourceService.GetImageAsync(IUriImageSource imageSource, Single scale, CancellationToken cancellationToken)
