### ISSUE TITLE
XFDF File Type Not Functioning in Input Element on Blazor MAUI Android

### ISSUE THREAD

**Issue by GokulprasathVenkatachalam** [dotnet/maui#26017]
### Description

When using the following input element in a Blazor MAUI Android application:

`<input type="file" accept="application/xfdf, .xfdf, application/vnd.adobe.xfdf" />`

The XFDF file cannot be selected through the input file element for upload or selection. This issue impacts workflows that depend on selecting and processing XFDF files. 

### Steps to Reproduce

1. Create new Blazor MAUI Hybrid application
2. Add a Input element like - `<input type="file" accept="application/xfdf, .xfdf, application/vnd.adobe.xfdf" />`
3. Deploy the app in Android
4. Click the input element of "Choose File". Not able to select or upload the xfdf file
5. ![Image](https://github.com/user-attachments/assets/f07e5b12-5273-45a7-bf67-e760318f3572)
6. ![Image](https://github.com/user-attachments/assets/270930c5-9ede-41db-a491-90894b9dd9b0)

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Android

### Affected platform versions

Android 13

### Relevant log output

```shell

```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please try to use the same html markup in a pure WebView within a plan MAUI app and see if that reproes?
