### ISSUE TITLE
When i run .net maui hybrid project, then its not working in window 11 pro dev

### ISSUE THREAD

**Issue by Mubashir222** [dotnet/maui#26012]
When i run .net maui hybrid project it run and open window application but sometime it hanged, stop events working and sometime its open application but not respond even previous days its working correctly. There is no issue like error, i check it. I don't know what is happening even other apps like skype, sql server also occure problem sometimes.

**Comment by jfversluis** [comment]
Without any kind of details its impossible to make this actionable. Please us the issue template when opening an issue.

Ideally you will have to provide a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md), this will also help you determine better if this is maybe something in the code you have written or a potential bug in the .NET MAUI/Blazor Hybrid SDK.

Closing this here for now, if you decide to open something new, please provide a lot more detail in order for us to be able to have a look.
