### ISSUE TITLE
Updating Visual Studio 2022 to 17.12.1 breaks all Maui builds

### ISSUE THREAD

**Issue by drewrobey** [dotnet/maui#26020]
### Description

We have a 5 Maui projects, and since updating Visual Studio last night, all now fail to build, with a variety of new error messages:

- resource style/Maui.SplashTheme (aka XXXXXXX:style/Maui.SplashTheme) not found.
- failed linking references.
- The type or namespace name 'MauiAppCompatActivity' could not be found (are you missing a using directive or an assembly reference?)
- Cannot implicitly convert type 'XXXXXXX.MainActivity' to 'Android.App.Activity'
- 'Platform' does not contain a definition for 'OnRequestPermissionsResult'
- The name 'Resources' does not exist in the current context
- style attribute 'attr/windowNoTitle (aka XXXXXXX:attr/windowNoTitle)' not found.
- style attribute 'attr/windowActionBar (aka XXXXXXX:attr/windowActionBar)' not found.
- The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?)
- The type or namespace name 'MauiWinUIApplication' could not be found (are you missing a using directive or an assembly reference?)

All of these projects built successfully yesterday before the update, both on Android and iOS.

### Steps to Reproduce

1. Update Visual Studio to 17.12.1
2. Attempting to build any Maui project.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

Android, iOS, Windows, macOS

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
Besides updating Visual Studio did you update anything else? At the very least updating Visual Studio probably updated your workloads. Are you using `$(MauiVersion)` in your csproj file to reference the .NET MAUI version? If yes, then also your .NET MAUI SDK got updated.

Do you have some more complete build logs or anything besides just the error messages?

Are you building .NET 8 or .NET 9? What is the output of `dotnet --info` and `dotnet workload list`?

**Comment by drewrobey** [comment]
Hi @jfversluis 

The VS update was the first thing we did this morning, and we close every day with working builds, so nothing else has changed.

I'm attempting a `dotnet workload update` now. All errors seem to be connected to Visual Studio no longer recognising the Maui compatibility toolkit on both Android and iOS, so I'm guessing that solving that will eliminate all the errors.

**Comment by jfversluis** [comment]
Let us know how it goes!

**Comment by drewrobey** [comment]
Unfortunately that hasn't fixed it. The core lynchpin error is, for Android at least, is:

- The type or namespace name 'MauiAppCompatActivity' could not be found (are you missing a using directive or an assembly reference?)

We use the compat toolkit in all our projects, so the class signature on Android's MainActivity is always:
`public class MainActivity : MauiAppCompatActivity`

...and if it can't resolve that, then it can't build anything else, or find any of the compat stuff used elsewhere.

**Comment by MitchBomcanhao** [comment]
what do you mean by compat toolkit? do you mean a reference to `Microsoft.Maui.Controls.Compatibility`?
that line for `public class MainActivity : MauiAppCompatActivity` has no connection to `Microsoft.Maui.Controls.Compatibility`

**Comment by drewrobey** [comment]
Well if that's not the compat toolkit stuff then the build issue is at a higher Maui level than the compat stuff.

**Comment by MitchBomcanhao** [comment]
well, on microsoft's maui documentation it says to remove the compatibility package reference when going from .net8 to .net9

**Comment by drewrobey** [comment]
Interesting. We'd not moved any of the apps to .net 9 yet, but I think it might be time.

**Comment by MitchBomcanhao** [comment]
if you updated maui to 9.0, aren't you using a .net9 package?

**Comment by drewrobey** [comment]
Not until this morning.

**Comment by drewrobey** [comment]
Solved it. The sequence that worked for us is:

1. Upgrade projects to .net 9.
2. Purge Nuget cache and restore.
3. Update all Nugets to latest versions (Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility in Nuget must be same version - v9.0.10 - or apps won't build).
4. Delete bin and obj folders.

We've done this on 3 of 7 workstations, and things will build again (with a ton of new warnings that weren't there before, but never mind).

I'll presume that the other 4 will also succeed with this, so I think this can be closed.

**Comment by drewrobey** [comment]
@philosowaffle Are you using Microsoft.Maui.Controls.Compatibility?

**Comment by NickDrouin** [comment]
I was going to try out Maui today, I'm hitting this same problem, I installed 17.12.2.

I can build and run a new Maui .net8 project, I can build a new .net9 maui project, I can't build the sample project from:

https://github.com/CommunityToolkit/Maui

On a fresh install of the git repo.

```
C:\Users\...\source\repos\microsoft\Maui>dotnet --info
.NET SDK:
 Version:           8.0.404
 Commit:            7b190310f2
 Workload version:  8.0.400-manifests.22517898
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.404\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [android]
   Installation Source: SDK 8.0.400, VS 17.12.35521.163
   Manifest Version:    34.0.145/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.145\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: SDK 8.0.400, VS 17.12.35521.163
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.400, VS 17.12.35521.163
   Manifest Version:    18.0.8316/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\18.0.8316\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 8.0.400, VS 17.12.35521.163
   Manifest Version:    18.0.8316/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\18.0.8316\WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.83/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.83\WorkloadManifest.json
   Install Type:        FileBased

 [maui-android]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.83/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.83\WorkloadManifest.json
   Install Type:        FileBased

 [maui-ios]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.83/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.83\WorkloadManifest.json
   Install Type:        FileBased

 [maui-maccatalyst]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.83/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.83\WorkloadManifest.json
   Install Type:        FileBased

 [maui-tizen]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.83/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.83\WorkloadManifest.json
   Install Type:        FileBased

 [maui-windows]
   Installation Source: SDK 8.0.400, VS 17.12.35521.163
   Manifest Version:    8.0.83/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.83\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  8.0.404 [C:\Program Files\dotnet\sdk]
  9.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Users\...\source\repos\microsoft\Maui\global.json
```

Where global.json is the default from the repo: 

```
{
  "sdk": {
    "version": "8.0.303",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}
```

Errors are:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0234	The type or namespace name 'Composition' does not exist in the namespace 'Microsoft.UI' (are you missing an assembly reference?)	CommunityToolkit.Maui.Sample (net8.0-windows10.0.19041.0)	C:\Users\...\source\repos\microsoft\Maui\samples\CommunityToolkit.Maui.Sample\MauiProgram.cs	38	
Error (active)	CS0234	The type or namespace name 'Windowing' does not exist in the namespace 'Microsoft.UI' (are you missing an assembly reference?)	CommunityToolkit.Maui.Sample (net8.0-windows10.0.19041.0)	C:\Users\...\source\repos\microsoft\Maui\samples\CommunityToolkit.Maui.Sample\MauiProgram.cs	39	
Error (active)	CS0234	The type or namespace name 'Media' does not exist in the namespace 'Microsoft.UI.Xaml' (are you missing an assembly reference?)	CommunityToolkit.Maui.Sample (net8.0-windows10.0.19041.0)	C:\Users\...\source\repos\microsoft\Maui\samples\CommunityToolkit.Maui.Sample\MauiProgram.cs	40	
Error (active)	CS0246	The type or namespace name 'MauiWinUIApplication' could not be found (are you missing a using directive or an assembly reference?)	CommunityToolkit.Maui.Sample (net8.0-windows10.0.19041.0)	C:\Users\...\source\repos\microsoft\Maui\samples\CommunityToolkit.Maui.Sample\Platforms\Windows\App.xaml.cs	6	

```

**Comment by sbricchi** [comment]
> Does anyone have steps for resolving this without having to upgrade to .NET 9 (currently on .net 7)?
> 
> Example error: [GitHub Action runners](https://github.com/philosowaffle/peloton-to-garmin/actions/runs/12053490728).
> 
> I do not have the bandwidth to upgrade all my projects to .NET 9 right now. That is on the roadmap for 2025.
> 
> [This](https://github.com/dotnet/maui/issues/25160#issuecomment-2470557349) fixed my local builds in Visual Studio, but it did not fix GHA builds.

Sounds as a real world consideration...

**Comment by philosowaffle** [comment]
Eventually found my way to [this issue](https://github.com/dotnet/maui/issues/25845) and a solution that would allow me to build .net7 workloads in GitHub Actions.

The changeset is [here](https://github.com/philosowaffle/peloton-to-garmin/pull/687/files#diff-e76e5134b85a9eb3e0d9ce8e671ce97c8c577ff3c24162c45d71691078201347), but I believe the magic sauce was adding these two steps:

```yaml
     - name: Set global.json
      run: dotnet new globaljson --sdk-version 7.0.100

    - name: Restore MAUI Workloads
      run: dotnet workload restore
```
