### ISSUE TITLE
Search control BackgroundColor

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2602]
Hi,

![image](https://user-images.githubusercontent.com/6236241/134064907-c2090903-c686-4439-b4cf-f9e5271d143b.png)

In the above image you can see that even when you set the BackgroundColor of Search control it will still have an area which is not getting changed so you have to use custom renderer to fix this.

This should be done from MAUI directly without having to use the specific platform code or custom renderer

Thanks,
Jassim

**Comment by jsuarezruiz** [comment]
Tested with Preview 11 and works as expected.
