### ISSUE TITLE
CollectionView Faults With InvalidOperationException on Windows

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#26038]
### Description

In trying to write a repro for a bug I created a simple CollectionView app. It works fine on Android but on Windows selecting an item by way of setting a property bound to CollectionView.SelectedItem (with Mode=TwoWay) faults with an InvalidOperationException with the message "Unexpected type for enumerator". 

### Steps to Reproduce

Clone the repository, build and run the app on Windows, you should see:
![Image](https://github.com/user-attachments/assets/11bd153f-f1b9-4189-bfa5-dfcd1a7dffa3)

Click on the "Select First Item" button and it will fault.

In contrast, if you build and run it on Android and click on the "Select First Item" button it will simply select the first item.

Alternatively, if you first click on of the buttons labelled 'Button' the app will catch and ignore the exception, but the item will not be selected although the property will be updated. The values of the SelectedPerson Property and of CollectionView.SelectedItem are both displayed by the app. It's not clear to me whether this is the same problem or a different one, so I didn't raise a separate incident.

One other observation. If you run the app on Android you'll see this:

![Image](https://github.com/user-attachments/assets/51b5337a-3287-41af-a205-2082906a4805)

Note that OnCollectionViewScrolled has been called, allowing the app to see initial values. This initial call is helpful and does not happen on Windows. 

### Link to public reproduction project repository

https://github.com/david-maw/SimpleCollectionView-Exception.git

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Relevant log output

```shell

```

**Comment by sheiksyedm** [comment]
@david-maw  This issue occurs due to changes in the underlying Windows SDK version, specifically when the <WindowsSdkPackageVersion> is set to 10.0.19041.41. Please remove the <WindowsSdkPackageVersion> setting in the sample app to resolve this. By doing so, this issue should be resolved.
![Image](https://github.com/user-attachments/assets/ab81624b-d475-42e6-8c25-2b4c95cb90f3)

**Comment by david-maw** [comment]
Thanks that fixed the problem, sorry to have wasted your time with this, I wonder how that setting crept in there, I've got literally hundreds of project files and the SimpleCollectionView set is the only one with a `WindowsSdkPackageversion` in it.  I'll keep an eye out for that project file change in future and see if I can figure out what caused it.
