### ISSUE TITLE
Build stuck on Extracting  Extracting ...\XamarinBuildDownloadCache\GMps-9.1.1.tgz to ...\XamarinBuildDownloadCache\GMps-9.1.1

### ISSUE THREAD

**Issue by LeoJHarris** [dotnet/maui#26045]
### Description

I'm having a hard time trying to get a deployment onto any device including a simple emulator on my current project, the issue is the following is getting stuck. Targeting .NET 8.

```csharp
1>Done building target "_GMpsDownloadedItems" in project "XXXX.csproj".
1>Target "_XamarinBuildAddDownloadedItems" in file "C:\.nuget\packages\xamarin.build.download\0.11.4\buildTransitive\Xamarin.Build.Download.targets":
1>Done building target "_XamarinBuildAddDownloadedItems" in project "XXXX.csproj".
1>Target "_XamarinBuildDownloadCore" in file "C:\.nuget\packages\xamarin.build.download\0.11.4\buildTransitive\Xamarin.Build.Download.targets":
1>  Using "XamarinDownloadArchives" task from assembly "C:\.nuget\packages\xamarin.build.download\0.11.4\buildTransitive\Xamarin.Build.Download.dll".
1>  Task "XamarinDownloadArchives"
1>    Task Parameter:IsAndroid=False
1>    Task Parameter:CacheDirectory=C:\Users\XXXX\AppData\Local\XamarinBuildDownloadCache\
1>    Task Parameter:
1>        Archives=
1>            GMps-9.1.1
1>                    Kind=Tgz
1>                    Url=https://dl.google.com/dl/cpdc/9555231399d822b1/GoogleMaps-9.1.1.tar.gz
1>    Task Parameter:VsInstallRoot=C:\Program Files\Microsoft Visual Studio\2022\Community
1>    Task Parameter:AllowUnsecureUrls=False
1>    Task Parameter:DestinationBase=C:\Users\XXXX\AppData\Local\XamarinBuildDownloadCache\
1>    Assembly loaded during TaskRun (Xamarin.Build.Download.XamarinDownloadArchives): Microsoft.Win32.Registry, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\.nuget\packages\xamarin.build.download\0.11.4\buildTransitive\Microsoft.Win32.Registry.dll, MVID: f165d2aa-905d-4dd4-8e4a-317d747f8224, AppDomain: [Default])
1>    Extracting C:\Users\XXXX\AppData\Local\XamarinBuildDownloadCache\GMps-9.1.1.tgz to C:\Users\XXXX\AppData\Local\XamarinBuildDownloadCache\GMps-9.1.1
```

Its just not moving at all, left the project to build for over an hour and nothing. Currently this is blocking my ability to even test our iOS app.

Frustratingly, if I quickly create an iOS MAUI app I can get a deployment so seems specific to my project but would appreciate some assistance. 

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

No

### Relevant log output

```shell

```

**Comment by maonaoda** [comment]
https://github.com/dotnet/android-libraries/pull/1048

**Comment by LeoJHarris** [comment]
@maonaoda Is there any ETA when this might be fixed? This is quite a serious issue for us as we cannot even deploy the app no matter which configuration we use.

**Comment by ninachen03** [comment]
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by LeoJHarris** [comment]
@ninachen03 is this not related to https://github.com/dotnet/android-libraries/pull/1048 which has an open PR?

**Comment by maonaoda** [comment]
Before the PR, you can try to use this temporarily.
https://www.nuget.org/packages/Maonaoda.Xamarin.Build.Download

**Comment by LeoJHarris** [comment]
@maonaoda how do I instruct the project to use that package instead?

The build still shows the following:

```
1>    Assembly loaded during TaskRun (Xamarin.Build.Download.XamarinDownloadArchives): Microsoft.Win32.Registry, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\.nuget\packages\xamarin.build.download\0.11.4\buildTransitive\Microsoft.Win32.Registry.dll, MVID: f165d2aa-905d-4dd4-8e4a-317d747f8224, AppDomain: [Default])
1>    Extracting C:\Users\\###\AppData\Local\XamarinBuildDownloadCache\GMps-9.1.1.tgz to C:\Users\###\AppData\Local\XamarinBuildDownloadCache\GMps-9.1.1
```

**Comment by maonaoda** [comment]
You may need to close the current 7zip process first.

**Comment by LeoJHarris** [comment]
@maonaoda Can you advise on how to do that?

**Comment by maonaoda** [comment]
From Task Manager, open the Resource Monitor, and under CPU, search for associated processes like 7z.exe or XamarinBuildDownloadCache, locate them, and terminate them.
![Image](https://github.com/user-attachments/assets/628858fb-2e83-460b-a51a-40025838e5d3)

**Comment by LeoJHarris** [comment]
@maonaoda thanks for the response, on terminating the 7z.exe I get the following and the build immediately stops

```
Unpacking failed. Please download 'https://dl.google.com/dl/cpdc/9555231399d822b1/GoogleMaps-9.1.1.tar.gz' and extract it to the 'C:\Users\Myself\AppData\Local\XamarinBuildDownloadCache\GMps-9.1.1' directory and create an empty file called 'C:\Users\Myself\AppData\Local\XamarinBuildDownloadCache\GMps-9.1.1.unpacked'.
```

**Comment by LeoJHarris** [comment]
@maonaoda seems to be like I would need to remove the `Onion.Maui.GoogleMaps` package which is what the above is complaining about, this is not a solution I can run with. Ill wait on PR to be available.

**Comment by maonaoda** [comment]
Sure, but I can use it :)
![Image](https://github.com/user-attachments/assets/7b568963-6ee2-4d1b-b4cb-cc986e65a3c9)

**Comment by LeoJHarris** [comment]
@maonaoda I'm not sure what further you would suggest I do, when I terminate the process for 7z.exe the application stops building, when I rebuild it gets stuck again?

**Comment by xcrackia** [comment]
@maonaoda thank you for finding this and pkg to assist with identifying the source issue.  I battled this for days after upgrading my MAUI project to .NET 9 / VS 17.12    

I was able to manual download the package and extract it to get my app to build/publish again.   

Can't wait for this to be resolved. :)

**Comment by LeoJHarris** [comment]
@maonaoda I got this working now by cloning the `Onion.Maui.GoogleMaps` repo and adding directly to my project and installing your package [Maonaoda.Xamarin.Build.Download](https://www.nuget.org/packages/Maonaoda.Xamarin.Build.Download) into that repo as well. I also added the `GMps-9.1.1.unpack` file as without that it kept on getting stuck.

**Comment by jfversluis** [comment]
I think this is indeed the right place for it: https://github.com/dotnet/android-libraries/pull/1048

At least this is not something that is controlled from this repository unfortunately. Else I would report this through Visual Studio, Help menu, Provide Feedback and Report a Problem. Thanks for all the help here!
