### ISSUE TITLE
provide a properly configured and signed bearer token and make sure that it has not expired visual studio

### ISSUE THREAD

**Issue by bhuwancb99** [dotnet/maui#26047]
### Description

I am getting the error: "Provide a properly configured and signed bearer token and make sure that it has not expired" in Visual Studio. I have generated the proper key and added the correct details, but I am still not able to add the account. I have updated to the latest Visual Studio version 17.12.1 and .NET 9.0.

![Image](https://github.com/user-attachments/assets/1f3d2d7e-642c-4226-8a18-5e3b8da6274b)

### Steps to Reproduce

1- In Visual Studio > Tools > Options > Xamarin > Apple Accounts
2- Click Add
3- Select Enterprise Account or Individual Account.
4- Add all details which is required for Enterprise Program API Key Information like Name, Issuer ID, Key ID and add private key path which is download under Integration Tab for User developer account where create Key.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

9.0.10 SR1

### Affected platforms

iOS

### Relevant log output

```shell

```

**Comment by bhuwancb99** [comment]
this is how it seems fixed

1 - create a team key admin

2 - in visual studio DO NOT use enterprise account but use individual

https://developercommunity.visualstudio.com/t/Unable-to-add-Apple-account---Provide-a/10795534?fTime=6m&sort=newest

**Comment by michalpr** [comment]
> this is how it seems fixed
> 
> 1 - create a team key admin
> 
> 2 - in visual studio DO NOT use enterprise account but use individual
> 
> https://developercommunity.visualstudio.com/t/Unable-to-add-Apple-account---Provide-a/10795534?fTime=6m&sort=newest


I confirm @bhuwancb99 comment helped me to solve this issue (https://developercommunity.visualstudio.com/t/Error-when-entering-App-Store-Connect-AP/10729145)

There is valuable info in this comment:
https://developercommunity.visualstudio.com/t/Unable-to-add-Apple-account---Provide-a/10795534#T-N10797800
