### ISSUE TITLE
[IOS] Dotnet 9 Memory leaks: BindableLayout leaks if nested inside a CollectionView, CarouselView ...etc

### ISSUE THREAD

**Issue by GUELIANEBelkacem** [dotnet/maui#26042]
### Description

After updating to .Net 9, i have 2 new memory leak behaviors:

~~1 ViewModel never removed if it contains a collection that is the ItemsSource of some control:**~~ 

~~If a ViewModel, which is the BindingContext of a page, contains a collection (List, ObservableCollection ..etc), and that collection is bound to the ItemsSource of a control (BindableLayout, CollectionView ...etc) ====> The ViewModel is never garbage collected !~~ 

~~I would like to specify that the control in question IS garbage collected, no issues on the display level, it's the ViewModel itself that stays in memory~~ 

~~This bahavior is consistent across platforms (tested Android, IOS and Windows)~~

**To be ignored i was just a mistake on my part ^^'**

**2 BindableLayout nested inside another control such as CarouselView, CollectionView or another BindableLayout is never garbage collected**

In this case, not only the ViewModel remains in memory, but the BindableLayout (Grid, AbsoluteLayout, StackLayout...whatever) and, of course, this leak cascades and THE ENTIRE PAGE remains in memory!!!!

This behavior is only reproducable on IOS, on Android and Windows the page is garbage collected

Might be important: The combo CollectionView inside CollectionView doesn's cause an issue, only BindableLayout inside some other collection (in my example it's a BindableLayout inside a CarouselView)

![Image](https://github.com/user-attachments/assets/d03f9e8a-273e-48c4-b724-c666b0090e55)

### Steps to Reproduce

1. Clone the attached project and run
2. The first issue (ViewModel leak) can be reproduced with the 2 first button (observe that, even though the pages are collected, the ViewModel itself is still in memory)
3. The second issue (Entire page leak) can be reproduced with the 3rd button (observe that the entire page stays in memory as we have a HorizontalStackLayout with BindableLayout inside a CarouselView)

### Link to public reproduction project repository

https://github.com/GUELIANEBelkacem/BindableLayoutLeakyApp.git

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.92 SR9.2

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Latest

### Did you find any workaround?

Quit my job :)

### Relevant log output

```shell

```

**Comment by GUELIANEBelkacem** [comment]
Ah yes, sorry for that it makes perfect sense. The first issue wasn't something i noticed in production code only in the test project and i found it very weird. Thank you very much!

That leaves us with the second IOS issue then (that drove me to create the test project in the first place)

**Comment by GUELIANEBelkacem** [comment]
I just updated the Title and the sample project with the correction of the first problem to not waste dev time

**Comment by PureWeen** [comment]
I ran your sample and nothing leaked for me

i clicked each button and after navigating back all the numbers go to zero.
Try with the debugger not attached? Sometimes hot reload can make things leak

![Image](https://github.com/user-attachments/assets/38b7cef0-11ba-4af6-b433-a6a31afdbfa2)

**Comment by GUELIANEBelkacem** [comment]
Thank you @PureWeen for your time.

I reproduce without the debugger attached : / but your test gave me a clue.

I was testing on IOS 17.5 and i reproduce consistently.
When I tested on IOS 18 the problem appears to go away!!

![Image](https://github.com/user-attachments/assets/7fb1ec04-1ae0-401f-b2e8-6592a50167cc)

This is very good news, i can at a minimum ask some of my clients to update their devices. But for those with older devices it will be complicated ^^

**Comment by jfversluis** [comment]
Looks like this is resolved, thanks everyone!
