### ISSUE TITLE
The Unloaded events of the page is not triggered when navigating to next page on android

### ISSUE THREAD

**Issue by KarthikRajaKalaimani** [dotnet/maui#26050]
### Description

I have a Shell page and am using Shell.Current.GoToAsync(nameof(NewPage)) to navigate to another page when a button is clicked. However, the Unloaded event of the MainPage is not triggered when navigating to NewPage. This issue occurs only on the Android platform, and not on iOS, macOS, or Windows.

### Steps to Reproduce

1. Run the attached sample.
2. Put the break on Unloaded event of the Main Page. 
3. Click the "Click Me" button to navigate to New Page. 
4. Note the Unloaded event is not triggered.[ShellPage.zip](https://github.com/user-attachments/files/17866163/ShellPage.zip)

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 15

### Did you find any workaround?

no

### Relevant log output

```shell
no
```

**Comment by kevinxufei** [comment]
I can repro this issue at Android platform on the latest 17.13 Preview 1(9.0.10 & 9.0.0).

**Comment by PureWeen** [comment]
@KarthikRajaKalaimani Yea, I realize this is somewhat confusing but the loaded/unloaded events are just tied directly to platform events

Android => attachedtowindow
iOS => MovedtoWindow
WinUI => Loaded/Unloaded

Each platform might keep views attached to the Visual tree for some scenarios but not others. Android keeps views in the visual hierarchy when pushing pages where as iOS/Windows don't
