### ISSUE TITLE
CurrentCulture region not read correctly from device (iOS 18.0)

### ISSUE THREAD

**Issue by Xopabyteh** [dotnet/maui#26079]
### Description

`CultureInfo.CurrentUICulture` is not read correctly. 

**Observation:**
When testing on an **iPhone 14 simulator with iOS 18.0:**
The device language is set to Čeština (cs) and region is set to Česko (CZ), but
`CultureInfo.CurrentUICulture.Name` returns "cs-US" instead of expected "cs-CZ"

When testing on **iPhone 12 device with iOS 18.1**
The configuration is the same, but this time the expected correct result is given.

I've also seen this happen on an iOS 17.6 device, the culture is not read properly (but i am unsure what configuration lead to what result)

### Steps to Reproduce

1. Code:
```cs
        Console.WriteLine(CultureInfo.CurrentUICulture.Name);
```

2. Start iOS 18.0 iPhone 14 simulator
3. Set device region to Czechia (Česko) and language to Czech (Čeština)
4. Observe "cs-US" in console

### Version with bug

8.0.83 SR8.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

iOS

### Affected platform versions

iOS 18.0

### Did you find any workaround?

Reading just the language code part and manually re-creating the culture info based on expected cultures (localized languages).

### Relevant log output

```shell

```

**Comment by drasticactions** [comment]
Can you try this in a .NET iOS Application that doesn't implement that MAUI UI framework? You can do this by creating an app using `dotnet new ios` in the command line.

Most likely this would be a [runtime](https://github.com/dotnet/runtime) issue.

**Comment by Xopabyteh** [comment]
I've done more testing and the mistake is on my side. It wasn't a MAUI error, nor a runtime one.

What happened is that when choosing a language (e.x. Czech) on an iOS device, the user is asked whether he wants to use it as default, or use English (USA) as default. When he chooses the other option (which for me came pre-set on my simulator) the resulting culture is cs-US, if he had chosen the first option, the result would've been cs-CZ.

A bit of a pain, but not an issue, with that i am closing this issue :)
