### ISSUE TITLE
Starting up MacOs server for iOS simulator does not work

### ISSUE THREAD

**Issue by twannie83** [dotnet/maui#26084]
### Description

I got myself a new MacBook 15 Seqoia.

Installed:
XCode 16.1
.NET 8.0

With my old MacBook connection was no problem. But now it keeps in a loop described in this log.
It does not startup iOS simulator. If I startup iOS simulator manually no problem.

### Steps to Reproduce

1> On VS2022 I allready had MAUI latest version.
2> I load my MAUI App and connect to Macbook successfully.
3> I press run on iOS 16

Expected iOS Simulator runs
Reality: Keeps looping on starting up server, Connecting 

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

macOS, Windows, iOS

### Affected platform versions

MacBook 15 Seqoia

### Did you find any workaround?

I connected ols Macbook succesfully.

### Relevant log output

```shell
SSH connected
Connection state changed:
	State: SshConnected
Connection state changed:
	State: CheckingServer
Connection state changed:
	State: SettingUpServer
Starting server
[Server] ready:51337
Connection state changed:
	State: Connecting
Connection state changed:
	State: CheckingServer
Connection state changed:
	State: Connected
Connection state changed:
	State: Disconnected
Connection state changed:
	State: Connecting
```

**Comment by jfversluis** [comment]
Additionally, Xcode 16.1 is not supported at this time, please downgrade to Xcode 16, that will probably make it work.

**Comment by twannie83** [comment]
Thanx, I made report on [VS2022 Developer Community](https://developercommunity.visualstudio.com/t/Starting-up-MacOs-server-for-iOS-simulat/10800886?port=1025&fsid=619bc330-d24d-48e1-9ee4-079323eee422).

**Comment by twannie83** [comment]
> Additionally, Xcode 16.1 is not supported at this time, please downgrade to Xcode 16, that will probably make it work.

On my old Mac Book 14.6.1 I also run Xcode 16.1 with no issues.
