### ISSUE TITLE
BindTapGesture shows error in .net 9

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#26088]
### Description

I was using BindTapGesture() with Border in my .net 8 project. After the release of .net 9 I changed the target version from 8 to 9 and try to build the project from VSCode on Mac. But getting the following error:

The type arguments for method 'GesturesExtensions.BindTapGesture<TGestureElement, TCommandBindingContext>(TGestureElement, Expression<Func<TCommandBindingContext, ICommand>>, Action<TCommandBindingContext, ICommand>?, TCommandBindingContext?, BindingMode, int?)' cannot be inferred from the usage. Try specifying the type arguments explicitly.(CS0411)

The code snippet where I am getting the error:

```
 new Border
                    {
                        StrokeThickness = 0,
                        StrokeShape = new RoundRectangle { CornerRadius = new CornerRadius(7) },
                        Padding = new Thickness(0),
                        BackgroundColor = Colors.Transparent,
                        Content = new Image
                        {
                            Source="coach_banner.png",

                            Aspect = Aspect.AspectFill,
                        }
                     }.BindTapGesture(nameof(viewModel.NavigateToCoachViewCommand)).Row(BodyRow.second).Column(BodyColumn.first),
```

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Android

### Affected platform versions

Android 35

### Relevant log output

```shell

```

**Comment by StephaneDelcroix** [comment]
the slight be related to nullable changes, quite sure nothing changed there in maui lately

**Comment by rlebowitz** [comment]
I ran into a similar issue myself.  Try substituting TouchBehavior for TapBehavior as seen in the example below as a workaround.  In my case, I created a method to create the border object which is called within my C# Markup.  This is intended as a work-around; it would be nice if the TapGesture worked as it did in .Net 8.0.

<pre>

    private Border GetBorder()
    {
        var border = new Border()
        {
            HorizontalOptions = LayoutOptions.Start,
            Style = AppStyles.EllipseBorderStyle,
            Content = new Image
            {
                Source = "back_arrow.png",
                HorizontalOptions = LayoutOptions.Center,
                VerticalOptions = LayoutOptions.Center
            }
        };
        border.Behaviors.Add(new TouchBehavior
        {
            DefaultAnimationDuration = 250,
            DefaultAnimationEasing = Easing.CubicInOut,
            PressedOpacity = 0.6,
            PressedScale = 0.8
        });
        return border;
    }

</pre>

**Comment by tj-devel709** [comment]
Would you be able to provide a reproduction?

**Comment by HobDev** [comment]
**Unable to replicate the issue in new project. Is it possible to find the cause from the below terminal output:**

> *  Executing task: dotnet build -t:Build -p:Configuration=Debug -f net9.0-windows10.0.19041.0 -p:WindowsPackageType=None C:\Users\spara\repos\Dome-backend\Vendor\Vendor.csproj 
> 
>   Dome.Shared succeeded (0.2s) → Dome.Shared\bin\Debug\net9.0\Dome.Shared.dll
>   Vendor net9.0-windows10.0.19041.0 failed with 1 error(s) and 163 warning(s) (8.2s)
>     C:\Users\spara\repos\Dome-backend\Vendor\Views\BookingView.cs(233,73): error CS1739: The best overload for 'BindTapGesture' does not have a parameter named 'commandSource'     
> 
> Build failed with 1 error(s) and 163 warning(s) in 8.6s
> 
> Workload updates are available. Run `dotnet workload list` for more information.
> 
>  *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command dotnet build -t:Build -p:Configuration=Debug -f net9.0-windows10.0.19041.0 -p:WindowsPackageType=None C:\Users\spara\repos\Dome-backend\Vendor\Vendor.csproj" terminated with exit code: 1. 
>  *  Terminal will be reused by tasks, press any key to close it.

**The error is in the below code in the BindTapGesture method:**

```
  new CollectionView
                {
                   ItemsLayout = new GridItemsLayout(5,ItemsLayoutOrientation.Vertical)
        {
           VerticalItemSpacing = 0,
           HorizontalItemSpacing = 5,
        },
        ItemTemplate =new DataTemplate(() =>
        {
            return new Border
                {
                     StrokeThickness = .5,
                     HeightRequest=41,
                     WidthRequest=109,
                    Stroke= new SolidColorBrush(Color.FromArgb("#C1BFBF")),
                    StrokeShape = new RoundRectangle { CornerRadius = 8 },
                    Padding=new Thickness(7),
                    Content = new Bold18Label { HorizontalOptions=LayoutOptions.Center}.Bind(Bold18Label.TextProperty, nameof(VenueDate.Date), stringFormat: "{0:HH.mm}").Bind(Bold18Label.TextColorProperty, nameof(VenueDate.TimeStatus), convert: (string status)=> status == VenueBookingStatus.UnAvailable?Colors.Black:Colors.White)

            }.BindTapGesture(nameof(viewModel.NewTimeSelectionCommand), commandSource: viewModel, parameterPath:".").Bind(Border.BackgroundColorProperty, nameof(VenueDate.TimeStatus), converter: new StringToColorConverter());
        }),
    }.Bind(ItemsView.ItemsSourceProperty, nameof(viewModel.TimeList), BindingMode.OneWay).Row(BodyRow.fifth),
```

The code snippet I provided in the bug report is now not showing any error.

**Comment by HobDev** [comment]
In another project of same solution I am getting this error 16 times wherever the Tap Gesture is used:

`/Users/paramjit/Desktop/Dome-backend/Player/Views/Book/BookingTimingView.cs(254,32): error CS0411: The type arguments for method 'GesturesExtensions.BindTapGesture<TGestureElement, TCommandBindingContext>(TGestureElement, Expression<Func<TCommandBindingContext, ICommand>>, Action<TCommandBindingContext, ICommand>?, TCommandBindingContext?, BindingMode, int?)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`

**Comment by jfversluis** [comment]
Does it work without using .NET MAUI Community Toolkit Markup? Isn't it a bug in that project?
What version of that plugin are you using?
