### ISSUE TITLE
MSB4057	The target "StaticWebAssetsPrepareForRun" does not exist in the project.

### ISSUE THREAD

**Issue by drewid** [dotnet/maui#2609]
### Description
Getting the following error with a brand new Maui App Project created from a brand new instance of Visual Studio 2022 RC 1 (with jdk 11 loaded per instructions:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4057	The target "StaticWebAssetsPrepareForRun" does not exist in the project.	MauiApp	C:\Users\userxyz\.nuget\packages\microsoft.aspnetcore.components.webview.maui\6.0.100-rc.1.1608\build\Microsoft.AspNetCore.Components.WebView.Maui.targets	20	

### Steps to Reproduce

1.  Create a Maui Project and build.  Creates the error
2.  Brand new Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 4.1

### Expected Behavior

Clean Build

### Actual Behavior

Error with build:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4057	The target "StaticWebAssetsPrepareForRun" does not exist in the project.	MauiApp	C:\Users\userxyz\.nuget\packages\microsoft.aspnetcore.components.webview.maui\6.0.100-rc.1.1608\build\Microsoft.AspNetCore.Components.WebView.Maui.targets	20	

### Basic Information

- Version with issue:
- Last known good version: N/A
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit) Version 17.0.0 Preview 4.1
- Platform Target Frameworks:  net6.0-ios;net6.0-android;net6.0-maccatalyst
- Android Support Library Version: N/A
- Nuget Packages: out of the box
- Affected Devices: basic build

### Screenshots

![image](https://user-images.githubusercontent.com/375184/134088010-b1e65ee8-c78f-4428-961f-bfef6664d984.png)

### Workaround

None Found

**Comment by Eilon** [comment]
@javiercn any thoughts on this? This is using the latest release (ASP.NET Core 6 RC1 + MAUI Preview 8).

**Comment by javiercn** [comment]
@Eilon that sounds weird.

Can you get a binlog and see the files being imported? It sounds as it is importing the wrong set of files.

**Comment by javiercn** [comment]
https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets#L404

**Comment by jonatan1024** [comment]
Changing project sdk from `Microsoft.NET.Sdk` to `Microsoft.NET.Sdk.Razor` resolved the issue for me.

**Comment by javiercn** [comment]
@jonatan1024 thanks for the additional details.

This is by design, since `Microsoft.NET.Sdk.Razor` is required for Blazor Desktop
