### ISSUE TITLE
iOS tabbar not visible with 8.0.100 SR10

### ISSUE THREAD

**Issue by sbloomztf** [dotnet/maui#26104]
### Description

Upon updating to 8.0.100 from 8.0.93, the toolbar in ios is no longer visible.

I have not isolated this issue in a sample app, but my app sets Shell.TabBarIsVisible = true in appshell and has a sign in view that hides the navbar (Shell.TabBarIsVisible = "False"), and upon successful sign in and navigation to the home screen, the navbar does not show as it did in 8.0.93.  

Perhaps setting Shell.TabBarIsVisible = true in appshell and overriding this value on individual views and navigating to the next screen exposes the issue.

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.93 SR9.3

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

revert back to 8.0.93

### Relevant log output

```shell

```

**Comment by PureWeen** [comment]
@sbloomztf can you include a repro/screenshots?

The Tab behavior in XCODE 16 changed. It moved the tabbar to the header. We added code in 8.0.100 that reverted this to Xcode 15.4 behavior. I'm not clear based on the current state of things what you're specifically referring to.

A repro would be helpful here
