### ISSUE TITLE
IL2026 Trim warning from Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator

### ISSUE THREAD

**Issue by jamescrosswell** [dotnet/maui#26115]
### Description

Getting IL2026 trim warnings from the Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator when trying to publish a MAUI app that is compiled AOT. 

### Reproduction Steps

Clone the repository at:
- https://github.com/jamescrosswell/TrimWarning

Then run:

```zsh
dotnet restore
dotnet publish -c Release --framework net9.0-ios18.0 /t:Run /p:_DeviceName=<DEVICE_ID>
```

### Expected behavior

The project should build and run on the specified device.

### Actual behavior

The project fails to build with the following errors:

```
  Sentry.Samples.Maui net9.0-ios18.0 failed with 3 error(s) (20.4s) → bin/Release/net9.0-ios18.0/ios-arm64/Sentry.Samples.Maui.dll
    /TrimWarning/obj/Release/net9.0-ios18.0/ios-arm64/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/Resources_Styles_Styles.xaml.sg.cs(33): Trim analysis error IL2026: __XamlGeneratedCode__.__Type68A1B57D17E9473E.InitializeComponent(): Using member 'Microsoft.Maui.Controls.Xaml.OnPlatformExtension.Default.get' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The OnPlatformExtension is not trim safe. Use OnPlatform<T> instead.
    /TrimWarning/obj/Release/net9.0-ios18.0/ios-arm64/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/Resources_Styles_Styles.xaml.sg.cs(33): Trim analysis error IL2026: __XamlGeneratedCode__.__Type68A1B57D17E9473E.InitializeComponent(): Using member 'Microsoft.Maui.Controls.Xaml.OnPlatformExtension.Default.set' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The OnPlatformExtension is not trim safe. Use OnPlatform<T> instead.
    /.nuget/packages/microsoft.dotnet.ilcompiler/9.0.0/build/Microsoft.NETCore.Native.targets(317,5): error MSB3073: The command ""/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/9.0.0/tools/ilc" @"obj/Release/net9.0-ios18.0/ios-arm64/native/Sentry.Samples.Maui.ilc.rsp"" exited with code -1.
```

### Configuration

Running .NET 9.0.100 on an Mac M2 Max running Mac OS Sonoma 14.6.1 (23G93) with the following workloads installed:
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
android                    35.0.7/9.0.100         SDK 9.0.100        
ios                        18.0.9617/9.0.100      SDK 9.0.100        
maccatalyst                18.0.9617/9.0.100      SDK 9.0.100        
macos                      15.0.9617/9.0.100      SDK 9.0.100        
maui-android               9.0.0/9.0.100          SDK 9.0.100        
maui-ios                   9.0.0/9.0.100          SDK 9.0.100        
maui-maccatalyst           9.0.0/9.0.100          SDK 9.0.100        
maui-tizen                 9.0.0/9.0.100          SDK 9.0.100        
wasm-tools-net8            9.0.0/9.0.100          SDK 9.0.100        
```

### Other information

The sample project provided in the reproduction steps is the MAUI sample from the Sentry repo with all the Sentry specific stuff (and indeed most of the UI) removed. Ultimately I'm trying to "upgrade" that sample project from .NET 8 to .NET 9.

**Comment by simonrozsival** [comment]
@jamescrosswell the problem is in the XAML code, where you're using the `{OnPlatform ...}` markup extension which isn't AOT compatible. The easiest solution to fix this problem is to use the generic `OnPlatform<T>`:

```xml
<!-- <Setter Property="Shell.ForegroundColor" Value="{OnPlatform WinUI={StaticResource Primary}, Default={StaticResource White}}"></Setter> -->
<Setter Property="Shell.ForegroundColor">
    <Setter.Value>
        <OnPlatform x:TypeArguments="Color">
            <On Platform="WinUI" Value="{StaticResource Primary}" />
            <On Platform="Default" Value="{StaticResource White}" />
        </OnPlatform>
    </Setter.Value>
</Setter>
```

I think we are lacking documentation that would help developers solve this issue. The warning message is accurate, but it should point to a documentation page that would show how to use the trimming safe generic variant of `OnPlatform`.

**Comment by jamescrosswell** [comment]
@simonrozsival where are you seeing that XAML code? I can't find that anywhere in the project...

**Comment by simonrozsival** [comment]
> But yes, the error message could be more helpful. Currently it points to a line number in the generated source code... 

Yes, this is unfortunately the case at the moment with trimming warnings with compiled XAML code. There are ideas how to improve this (https://github.com/dotnet/maui/pull/24865) but there's no easy way to fix it at the moment.
