### ISSUE TITLE
MAUI source generator interferes with other projects

### ISSUE THREAD

**Issue by miloush** [dotnet/maui#26125]
It seems that when a MAUI library is referenced by a project, the MAUI source generator is run for that project. If the project happens to have XAML files, it interferes with the project's own code generation.

See https://github.com/dotnet/wpf/issues/10113

Expected: do not include MAUI analyzers in a project that only references another MAUI project.

**Comment by StephaneDelcroix** [comment]
do you have any proposition for this ?

**Comment by miloush** [comment]
What is the mechanism that makes a project that references a MAUI library run the MAUI analyzers?

**Comment by StephaneDelcroix** [comment]
closing as the WPF issue referencing this was closed

**Comment by miloush** [comment]
I don't think that is appropriate. We shouldn't be pushing MAUI analyzers to projects that have nothing to do with MAUI.
