### ISSUE TITLE
Label display bug

### ISSUE THREAD

**Issue by yangshuxin199393** [dotnet/maui#26151]
### Description

In.net maui 8, using the Label's FormattedText FormattedString format string, there are two spans, and the second Span has the content "kiwi2!" If it is other strings, it will be displayed. If the Span of Label is not used for display, there is no problem. The model of the phone is Samsung SM-A226B, and the operating system is Android 13![Image](https://github.com/user-attachments/assets/174295d3-4e90-4afe-b9a3-37cf010ef1db)
![Image](https://github.com/user-attachments/assets/cdfa68cc-d5d1-4e5f-bb99-651b2a3e7e78)

### Steps to Reproduce

<Label
    FontAttributes="Bold"
    FontSize="24"
    LineBreakMode="WordWrap"
    TextColor="#002C4F"
    VerticalTextAlignment="Center">
    <Label.FormattedText>
        <FormattedString>
            <Span Text="{helpers:Translate MOBILE_APP_GUIDE_WELCOME}" />
            <Span Text="kiwi2!" />
        </FormattedString>
    </Label.FormattedText>
</Label>

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

Android

### Affected platform versions

Android 13

### Relevant log output

```shell

```

**Comment by StephaneDelcroix** [comment]
I'm sorry I'm not sure I understand. please provide a small reproduction project

**Comment by yangshuxin199393** [comment]
![Image](https://github.com/user-attachments/assets/da626dc2-9f14-4d0a-9011-4f38b8783080)
Today, I verified that there is no problem with the normal demo. In our project, the content of FirstName can be displayed in this way, which is strange
