### ISSUE TITLE
[Bug] Unable to change App Icon in IOS iPad

### ISSUE THREAD

**Issue by owaits** [dotnet/maui#2616]
I have not been able to change the app icon and splash screen when deploying a MAUI app using the blazor template to an IOS iPad. I am not sure if I have understood fully how to change the icon, what I think is that the icons are generated from the single appicon.svg. This is amazing but for the iPad does not appear to be working for me. 

I am developing in Visual Studio 2022 using a paired Mac build agent. I create the standard MAUI Blazor project using the template and deploy it to an android device via USB connected to the Windows machine. The app shows up with the .NET logo and icon correctly. I then deploy the same app to the IOS iPad and I get the blue Xamarin logo for both the icon and the splash screen. 

I have not found any way to change the app icon on the iPad, it always deploys with the Xamarin icon and not the icon specified in the MAUI project.

I am using .Net 6 RC1

**Comment by jamesmontemagno** [comment]
When you are deploying from Windows using iOS hot restart you will see the base images icon/splash screen. This is expected when using this. If you connect to a mac and plug your ipad into your mac then you will see your actual assets. This is a limiation of Hot Restart for iOS. https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart#limitations

**Comment by owaits** [comment]
Thank you James for looking at this! I had a suspicion it might be a limitation of developing on Windows, unfortunately I don't have a MAC for development and I am not planning to get one. I use a cloud ios build server so connecting the iPad to it is not an option. I guess if I run it through a build pipeline it would work though so I will try this as a workaround.

I did manage to get the app done and delivered to a customer (I know preview but it was a simple one off in a very low risk scenario) it just used the Xamarin icon. 

Thank you so much for all the hard work on MAUI, it was such a joy to develop in! I have been using the Xamarin framework since its very early days when it was mono. So nice to see two frameworks I have grown to love, Blazor and Xamarin combine!
