### ISSUE TITLE
ScrollView seem wrong with Border.Stroke Thickness change

### ISSUE THREAD

**Issue by hiepis** [dotnet/maui#26181]
### Description

ScrollView scroll random when border change StrokeThickness

### Steps to Reproduce

https://github.com/user-attachments/assets/c9e31143-a7c0-4f76-a49e-b74977387854

### Link to public reproduction project repository

https://github.com/hiepis/ScrollViewandBorder.git

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android version 7,14

### Relevant log output

```shell

```

**Comment by hiepis** [comment]
> Hi [@hiepis](https://github.com/hiepis), I can't open the project you provided and it shows 404. Please help to see if you do not give us the corresponding permissions to open it.

Sorry, I updated project to public

**Comment by Ying-6** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1 (9.0.10 & 8.0.100 & 8.0.83). Not repro this issue on Pixel 7 - API 34 (Android 14.0 - API 34) emulator.
![Image](https://github.com/user-attachments/assets/2b37af21-fc06-44fe-adad-0133a77b365c)

**Comment by bricefriha** [comment]
I could reproduce the issue from the `main` branch by copying the code of the provided repo into `Maui.Controls.Sample.Sandbox`. I'm using Visual Studio 17.13.0 Preview 1.0
