### ISSUE TITLE
[MAUI] Select items traces are preserved

### ISSUE THREAD

**Issue by ninachen03** [dotnet/maui#26187]
### Description

[MAUI] 
Affected case: All test cases

### Steps to Reproduce

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to iOS or MacCatalyst.
2. Click any categories EG: "C RefreshView "-> C1 or others.
3. Back to C1 you will see the C1 display gray
4. Back to categories, you will see the "C RefreshView" show gray too.

Actual Behavior:
![Image](https://github.com/user-attachments/assets/b50c9f48-39f1-413d-8d2f-5478eca44091)
Expected Behavior:
Selection trace disappears and should not be retained
![Image](https://github.com/user-attachments/assets/a011686f-ec13-4997-a044-6c2c315bb211)

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

Microsoft.Maui.Controls: 9.0.20-ci.main.24577.4
### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Microsoft.Maui.Controls: 9.0.20-ci.main.24573.3

### Affected platforms

iOS, macOS

**Comment by rmarinho** [comment]
Can you check if it behave the same on Android and Windows ?

**Comment by ninachen03** [comment]
> Can you check if it behave the same on Android and Windows ?

Can't reproduce on Android and Windows platforms, as I mentioned above, only affects iOS, macOS

**Comment by Zhanglirong-Winnie** [comment]
Hi, all
I verified this issue on the latest released version **9.0.70**: this issue is reproduced in both CollectionView1 and CollectionViewHandler2.

**Comment by FlavioGoncalves-Cayas** [comment]
It's been almost a year. And a PR was opened 4 months ago...
Is there a workaround?
