### ISSUE TITLE
Android - CollectionView scroll wrong item when set animation is false

### ISSUE THREAD

**Issue by hiepis** [dotnet/maui#26191]
### Description

ScrollTo(int index, int groupIndex = -1,ScrollToPosition position = ScrollToPosition.MakeVisible, bool animate = true) seem not working when animate  = false
I add many entry in collectionview, the keyboard has strange behaviour.

Using .net8 
Microsoft.Maui.Controls 8.0.100

### Steps to Reproduce

https://github.com/user-attachments/assets/f7403f12-7599-43fc-800e-1348c3401b65

### Link to public reproduction project repository

https://github.com/hiepis/CollectionView_scroll-.git

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Relevant log output

```shell

```

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1 (9.0.10  & 8.0.100 & 8.0.92). Can repro this issue on Android platform.

**Comment by kubaflo** [comment]
Hi, @hiepis It looks to me that it doesn't work only in a particular case when you do `entry.Focus();` before scrolling
```
	private void OnItem2Tapped(object sender, TappedEventArgs e)
	{
		var stackLayout = sender as StackLayout;
		var entry = stackLayout?.Children[0] as Entry;
		if (entry != null)
		{
                        entry.Focus();
			var index = ((IList<string>)collectionView.ItemsSource).IndexOf(entry.Placeholder);
			collectionView2.ScrollTo(index, position: ScrollToPosition.Start, animate: SwitchAnimation.IsToggled);
			currentIndex = index;
		}
	}
```

**Comment by hiepis** [comment]
@kubaflo I create 2 list. First list I set focus after call ScrollTo

**Comment by tj-devel709** [comment]
@hiepis Thanks for the feedback. If I'm following correctly, would doing what @kubaflo suggested work as a workaround in this situation? Seems like there may be some timing things going on when focusing before scrolling to the index without the animations. Is there a particular scenario you want this focus before the scroll?

**Comment by hiepis** [comment]
@tj-devel709 Remove event OnItem2Tapped and add scrolling to item when entry focused(ScrollToPosition is Start). If you touch on Entry, The Entry will focused first then scrolling. It's show bug like second collection

**Comment by jfversluis** [comment]
I see this talks about .NET 8, could you also try .NET 9? Maybe its resolved in ther?

**Comment by pierre01** [comment]
I have the same issue but also without the groups (verified in 9.0.12) Android only...
ExercisesCollectionView.ScrollTo(e, position: ScrollToPosition.MakeVisible);

https://github.com/user-attachments/assets/ac2a222b-e2f3-4413-919a-de003dc78cae
