### ISSUE TITLE
[Bug] Not able to correctly install and use MAUI on Visual Studio 2022 Preview 4

### ISSUE THREAD

**Issue by anaselhajjaji** [dotnet/maui#2620]
### Description

I followed the [installation guide](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
But also the [James's tutorial](https://www.youtube.com/watch?v=Q0qLiBmbOTI).

### Steps to Reproduce

1. Having multiple previous previews
2. Uninstall Visual Studio 2022 (for info, I kept Visual Studio 2019 installed on my machine)
3. Run Clean-Old-DotNet6-Previews.ps1
4. Follow the [James's tutorial](https://www.youtube.com/watch?v=Q0qLiBmbOTI)
5. Open Visual Studio 2022
6. Create MAUI APP project

### Expected Behavior

MAUI should work as shown in the [James's demo](https://www.youtube.com/watch?v=Q0qLiBmbOTI)

### Actual Behavior

Problem in Windows and Android workload, see screenshot:

![image](https://user-images.githubusercontent.com/3309485/134235626-a5e45ebe-e8c1-47b5-b2c7-e6d33166a747.png)

When I click on install, I get the popup below:

![image](https://user-images.githubusercontent.com/3309485/134345954-f4632326-1e74-4bd8-9e8d-7d3596fce444.png)

### Basic Information

![image](https://user-images.githubusercontent.com/3309485/134235720-4f70f4ba-cd50-44bb-a1a5-1795a7e29445.png)

### Detailed Info

Microsoft Visual Studio Enterprise 2022 Preview
Version 17.0.0 Preview 4.1
VisualStudio.17.Preview/17.0.0-pre.4.1+31717.71
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2022   00476-70000-00000-AA819
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.0.616.20688
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.616.20688
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.616.20688
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.616.20688
Azure Functions and Web Jobs Tools

C# Tools   4.0.0-4.21458.2+2bfff7b9348e779628a06b86af04b5239d3a926d
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.0.11 (54f19d2)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2143108+3355b17aa26a41735ddf03b9fd3f71df166c0411
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   17.0.62109.15100
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.0901.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.0-4.21458.2+2bfff7b9348e779628a06b86af04b5239d3a926d
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21431.1+a7e1ca9200c21fd832dd9829fe1c655b69424ae8
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.266 (d17-0@56a1e79)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.101 (remotes/origin/main@533d7d10b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.11 (a04c9af)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.99.13 (main/fe2e7e6)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@b7982e4
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9b658b2

Xamarin.iOS and Xamarin.Mac SDK   14.99.0.598 (11838db7d)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by rr222cy** [comment]
Hi! Just popped on over here to check out if anyone had a similar issue and what do you know, @anaselhajjaji had just created an issue.

My problem is very similar, followed the guide over here: [](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=windows) doing the setup-steps as per the "Prerequisites" section. My issue is that MAUI is not even showing up as an alternative in the new project dialogue, Xamarin and the other stuff shows up as usual.

Running Visual Studio 2022 Preview 4.1, .NET 6, Android SDK 31 (Installed through VS2022) and the other prerequisites listed by the getting started guide. 😊

**Comment by anaselhajjaji** [comment]
@rr222cy  when I click on install in the warning I end up with the dialog in your screenshot. I will update the description to add that.

**Comment by jfversluis** [comment]
Please retry with the latest previews and let us know if you still run into any issues, thanks!
