### ISSUE TITLE
Local resources not working in release configuration with more than one resource inside

### ISSUE THREAD

**Issue by knoll-ds** [dotnet/maui#26206]
### Description

Hello team,

After upgrading my project to 9.0.10, I'm facing a weird problem with local resources - in release configuration, the app crashes if there is more than one resource in the dictionary. It works fine in debug mode.

### Steps to Reproduce

Run following code sample in release configuration:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
    <ContentPage.Resources>
        <x:Double x:Key="ResourceOne">25</x:Double>
        <x:Double x:Key="ResourceTwo">185</x:Double>
    </ContentPage.Resources>
    <ScrollView>
        <VerticalStackLayout
            Padding="30,0"
            Spacing="{StaticResource ResourceOne}">
            <Image
                Source="dotnet_bot.png"
                HeightRequest="185"
                Aspect="AspectFit"
                SemanticProperties.Description="dot net bot in a hovercraft number nine"/>

            <Label
                Text="Hello, World!"
                Style="{StaticResource Headline}"
                SemanticProperties.HeadingLevel="Level1"/>

            <Label
                Text="Welcome to &#10;.NET Multi-platform App UI"
                Style="{StaticResource SubHeadline}"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"/>

            <Button
                x:Name="CounterBtn"
                Text="Click me"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Fill"/>
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
```

To get it work again, just comment the line with "ResourceTwo" out.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.93 SR9.3

### Affected platforms

iOS, macOS, I was *not* able test on other platforms

### Affected platform versions

iOS 18.1.1, macOS 15.1.1

### Relevant log output

```shell

```

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio code1.95.3  (9.0.10). Cannot repro on iOS  (Simulator18.1) / Maccatalyst platform.
I just create the maui project and replaced the mainPage.xmal file with the xaml code that you provided above. If I missed anything, please let me know.
The following is the screen recording
![Image](https://github.com/user-attachments/assets/d63bffd5-ec7d-4de5-963e-9908beb920d1)

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio code1.95.3 (9.0.10 & 9.0.0-preview.1.9973). Can repro on iOS (Simulator18.1)  Maccatalyst platform. but can not repro in build Visual Studio code1.95.3 (8.0.100). So It's a regression from .NET 8 to .NET 9.

**Comment by StephaneDelcroix** [comment]
it would be nice to include a stack trace, or an exception message if any when the app is crashing

**Comment by StephaneDelcroix** [comment]
I can not reproduce this in a unit test

**Comment by PureWeen** [comment]
@ninachen03 can you attach a repro as well if you've reproduced it

**Comment by knoll-ds** [comment]
@StephaneDelcroix  @PureWeen 

XAML for repro is attached above, just run it in **Release Mode**  

![Image](https://github.com/user-attachments/assets/fe50c1e2-1584-44ca-a2e3-c99a2882ef31)

**Comment by StephaneDelcroix** [comment]
you've attached a code snippet, that I can run in release. please provide a repro project.

**Comment by knoll-ds** [comment]
> Your code snippet is not usable as such, and require modification, or assumptions, to run (HeadLine and SubHeadline resources are not defined in the scope of your snippet)
> 
> Given the right subset of modifications/assumptions, well, it runs JustFine(™) on both Debug and Release.
> 
> Please lift any ambiguity by providing a small project that we can run

Ok, here is the repro project, I made it a bit clearer: [https://github.com/knoll-ds/maui-bug-repro](https://github.com/knoll-ds/maui-bug-repro)

And here is a screen capture of what happens when it is run in the Release mode:
![Image](https://github.com/user-attachments/assets/1ab7bd91-6b2a-4ae4-a946-b609b6533491)

**Comment by jfversluis** [comment]
Can you maybe verify that [this PR](https://github.com/dotnet/maui/pull/26465) fixes the issue you're seeing and let us know? This [video](https://youtu.be/B2FOBjZKm9k) will show you how to do it!
