### ISSUE TITLE
emulator chashes when dragged on second screen

### ISSUE THREAD

**Issue by MaMon1963** [dotnet/maui#26211]
### Description

emulator chashes when dragged on second screen

I updated Visual Studio 2022 to version 17.12, unfortunately this also coincided with the installation of an "Asus Hyper M.2 X16 Card V2", which does not allow me to fully establish the causes of the problem, and I cannot remove it because it hosts my own "Dev drive". 
What happens to me is that I can no longer display the emulator on the second screen to test my Blazor MAUI applications. On the first screen (connected via "Display Port") I can work fine, but if I try to drag the emulated device onto the second screen (connected via "HDMI"), as soon as half of the window exceeds the edge of the first screen the emulator freezes and with it the window. 
For the record I have an "ASUS Rog Strix Z390-E Gaming" motherboard and an "ASUS Rog Strix 1660 S" video card with all the drivers updated to the latest versions. 
The PC is running Windows 11 Professional with Hyper-V and Windows Hypervisor Platform enabled. 
In addition, all the tests on Microsoft platforms that I found to verify the installation of Hyper-V and Windows Hypervisor Platform were successful.

### Link to public reproduction project repository

n.d.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Android

### Affected platform versions

Android Platform 14 and 15 - Android SDK 17.12.0.32

### Did you find any workaround?

I have done a lot of research and attempts and so far I have not been able to solve the problem.

### Relevant log output

```shell
This is what I get when I force close the emulator after dragging:

------------------------

Device error: WARNING | unexpected '-prop' value ('monodroid.avdname=tablet_m-dpi_10_1in_-_api_34'), only 'qemu.' properties are supported
WARNING | unexpected '-prop' value ('emu.uuid=f7ef78f3-f1a5-4b44-b1b4-ff47cb3363a9'), only 'qemu.' properties are supported
netsimd I 11-28 22:00:35.384 daemon\src\rust_main.rs:98 - netsim artifacts path: "C:\\Users\\mauri\\AppData\\Local\\Temp\
etsimd"
netsimd I 11-28 22:00:35.385 daemon\src\rust_main.rs:101 - NetsimdArgs {
 fd_startup_str: None,
 no_cli_ui: true,
 no_web_ui: true,
 pcap: false,
 disable_address_reuse: false,
 hci_port: None,
 connector_instance: None,
 instance: None,
 logtostderr: false,
 dev: false,
 disable_wifi_p2p: false,
 rust_grpc: false,
 vsock: It is not,
 config: None,
 host_dns: Some(
 "192.168.1.1",
 ),
 http_proxy: None,
 test_beacons: false,
 no_test_beacons: false,
 no_shutdown: false,
 verbose: false,
 version: false,
}
dsound: Could not initialize DirectSoundCapture
dsound: Reason: No sound driver is available for use, or the given GUID is not a valid DirectSound device ID
WARNING | The emulator now requires a signed jwt token for gRPC access! Use the -grpc flag if you really want an open unprotected grpc port
WARNING | ** Basic token auth should only be used by android-studio **
WARNING | Device 'cache' does not have the requested snapshot 'default_boot'
WARNING | Failed to load snapshot 'default_boot'
netsimd I 11-28 22:00:53.410 daemon\src\rust_main.rs:98 - netsim artifacts path: "C:\\Users\\mauri\\AppData\\Local\\Temp\
etsimd"
netsimd I 11-28 22:00:53.410 daemon\src\rust_main.rs:101 - NetsimdArgs {
 fd_startup_str: None,
 no_cli_ui: true,
 no_web_ui: true,
 pcap: false,
 disable_address_reuse: false,
 hci_port: None,
 connector_instance: None,
 instance: None,
 logtostderr: false,
 dev: false,
 disable_wifi_p2p: false,
 rust_grpc: false,
 vsock: None,
 config: None,
 host_dns: Some(
 "192.168.1.1",
 ),
 http_proxy: None,
 test_beacons: false,
 no_test_beacons: false,
 no_shutdown: false,
 verbose: false,
 version: false,
}
```

**Comment by jfversluis** [comment]
I think Visual Studio is a better place to report this, although I doubt if even they can fix this because the emulators is really just the stuff from Google.

**Comment by MaMon1963** [comment]
Actually it could be the most appropriate thing, I'll make the report as suggested, thanks

 

Da: Gerald Versluis ***@***.***> 
Inviato: venerdì 29 novembre 2024 08:24
A: dotnet/maui ***@***.***>
Cc: Maurizio ***@***.***>; Mention ***@***.***>
Oggetto: Re: [dotnet/maui] emulator chashes when dragged on second screen (Issue #26211)

 

I think Visual Studio is a better place to report this, although I doubt if even they can fix this because the emulators is really just the stuff from Google.
