### ISSUE TITLE
iOS - OnNavigatedFrom is not fired when navigating back by swiping

### ISSUE THREAD

**Issue by eth-ellis** [dotnet/maui#26216]
### Description

On iOS devices, OnNavigatedFrom is not fired when navigating back from a page by swiping.

It does work when navigating back using the back button.

Video:
![Image](https://github.com/user-attachments/assets/f8eb880d-ed29-4492-b785-f7dadf46d6c3)

### Steps to Reproduce

Steps:
1. Open the repro app
2. Tap the navigate button
3. Navigate back by swiping
4. The navigated from alert is not shown

The alert is show if navigating back using the back button.

### Link to public reproduction project repository

https://github.com/eth-ellis/Issue-Repro/tree/main/OnNavigatedFromAfterSwipe

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Relevant log output

```shell

```

**Comment by Ying-6** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1 (9.0.10 & 8.0.100 & 8.0.93). Can repro this issue on iOS platform.
