### ISSUE TITLE
Enable .NET MAUI on source.dot.net

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#26210]
### Description

Investigate if it s possible to enable sourceIndex in our internal builds with arcade so we can appear on https://source.dot.net/

### Public API Changes

update yaml maybe with 

```
 sourceIndexParams:
            - sourceIndexBuildCommand: powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -Command "eng/common/build.ps1 -restore -build -binarylog -ci"
```

### Intended Use-Case

BE able to browse the .NET MAUI API on https://source.dot.net/

**Comment by jfversluis** [comment]
Make sure to close this one #6814

**Comment by rmarinho** [comment]
Duplicate of #6814
