### ISSUE TITLE
[Enhancement] Mixed developments use native language

### ISSUE THREAD

**Issue by xtuzy** [dotnet/maui#2624]
## Summary
Old project use native language like java or object-c, migrate them to c# is big task. I know we can use binding library to link native language with c#, can we mixed developments use them? This can let migration smooth.

**Comment by John0King** [comment]
other platfrom is developer use native lanauge/platfrom to serve the "cross platfrom"

**Comment by jfversluis** [comment]
I don't think this will happen anytime soon. This will be a bigger effort spanning over .NET MAUI and not sure if this will ever happen. The big advantage of our ecosystem is to do everything with one language, there will always be need for a bridge of sorts.
