### ISSUE TITLE
AppShell Navigating (Event) ShellNavigationSource.Unknown when using back-arrow from detail page

### ISSUE THREAD

**Issue by FaithfulDev** [dotnet/maui#26261]
### Description

I'm navigating from my main page (shell root) to a detail page and then to another detail page. When I try to navigate back using the "back-arrow" from the shell, I want to go directly to the main page, instead of navigating back to the previous detail page. For this, I'm handling the `AppShell.Navigating` event. In this event handler, I would expect the source to be `ShellNavigationSource.Pop`, but it's set to `ShellNavigationSource.Unknown`.

I tested it on Windows and on Android. Both have the issue.

### Steps to Reproduce

1. Start the provided reproduction app, either on Android or on Windows.
2. Click the "Go to Detail Page 1" button.
3. Click the "Go to Detail Page 2" button.
4. Click the "arrow-back" of the shell.

![Image](https://github.com/user-attachments/assets/94248846-1c62-4753-a9c3-17adb3ceeb84)

Expected: Back on the Main Page
Actually: Back on Detail Page 1.

### Link to public reproduction project repository

https://github.com/FaithfulDev/NavigationSourceBugMinimal

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Did you find any workaround?

I'm now checking for `ShellNavigationSource.Unknown || ShellNavigationSource.Pop`.

### Relevant log output

```shell

```

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1 (9.0.10 & 9.0.0 & 8.0.100 ). Can repro this issue on Android and Windows platforms.

**Comment by NirmalKumarYuvaraj** [comment]
After analysis, the issue appears to stem from registering the route at the sample level. The routes are currently registered as MainPage/DetailsPage2. This registration causes the global route to include an additional instance of MainPage, resulting in targetPathsLength being set to 6 (IMPL_MainPage/IMPL_MainPage/MainPage/MainPage/DetailsPage1), the same as currentPathsLength, which is also 6 (IMPL_MainPage/IMPL_MainPage/MainPage/DetailsPage1/DetailsPage2). Modifying the route registration to DetailsPage2 resolves the issue and produces the expected output. I have attached the modified sample for your reference.

[NavigationSourceBugMinimal.zip](https://github.com/user-attachments/files/18007477/NavigationSourceBugMinimal.zip)

**Comment by FaithfulDev** [comment]
@NirmalKumarYuvaraj Thanks, that solved the issue indeed.

But I'm not sure if this would only be considered a workaround. The reason I had them as "sub" routes is because that's their hierarchical structure, meaning both pages are in fact children of my MainPage (the example doesn't really meaningfully convey that). And I also would argue, that even if their paths are the same length, it still a "pop" in the technical sense, since I go back in the stack? Maybe there should be additional checks?

Well, perhaps something for the future.
