### ISSUE TITLE
[iOS] Unable to launch app after it's uploaded

### ISSUE THREAD

**Issue by imadofficial** [dotnet/maui#26294]
### Description

This is a bug specifically affecting .NET 9. When you upload the app to ASC (whilst targetting .NET9), it would compile successfully & upload. However when Apple is done processing it and me opening the app to test it. It wouldn't launch whatsoever. I've also tried updating to .NET 9.0.1 where it might be fixed but the issue still precists. Downgrading to .NET 8 seemed to immediately fix every issue i've had.

I've also tried it on an empty project (linked here in the bug report) but the same issue occured.

Do note, that everything works fine inside the simulator though.

### Steps to Reproduce

1) Create a project file
2) Publish it and upload the xcarchive using XCode to AppStore Connect
3) Run it on your iPhone, just to see it crash on startup.

### Link to public reproduction project repository

https://github.com/imadofficial/UploadIssue

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS

### Affected platform versions

All iOS versions

### Did you find any workaround?

I was unable to find a work around.

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
Do you get any logs, messages, anything?

One thing I immediately notice about your repro is: https://github.com/imadofficial/UploadIssue/blob/main/Plus/Plus.csproj#L56

You target .NET 9, but you reference the .NET 8 NuGet. Either update that to be 9.0.10 or set it to $(MauiVersion) to use the workload version

Does that help?

**Comment by imadofficial** [comment]
No no, that's after I tried doing it with .net 9.0.0 & 9.1.0 nuget, i attempted targeting .NET 8.0 packages to see if that would make a difference. But it didn't.

**Comment by imadofficial** [comment]
[testflight_feedback.zip](https://github.com/user-attachments/files/17975714/testflight_feedback.zip)
This is what i'm getting off of Testflight, but as said in the simulator it all works just fine.

**Comment by jfversluis** [comment]
![Image](https://github.com/user-attachments/assets/34e094e1-4ff4-4101-9d23-eb0a0a771ee2)

Just took your repo, built it against .NET 9, submitted it and it works fine on my TestFlight.

**Comment by imadofficial** [comment]
Yeah, using that command, everything worked first try. I was using the built-in publishing function in Rider. Turns out, that was what's causing issues this whole time. I'm so sorry for bothering you guys...
