### ISSUE TITLE
Debugging issue from Visual studio 2022 preview 4.0 and 4.1

### ISSUE THREAD

**Issue by Tkumar2021** [dotnet/maui#2629]
### Description
Facing issue in debugging of .Net MAUI project even in the new project as well.

### Steps to Reproduce

1. Update visual studio 2022 to preview 4.0
2. Create a new .Net MAUI project
3. Run the app with break point
4. You will get an error like "No compatible code running on the thread"

### Expected Behavior
-- Pointer should come on the break point 

### Actual Behavior
-- Got error ("No compatible code running on the thread") and skip the execution of debugging

### Basic Information

- Version with issue: Visual Studio 2022 Preview 4.0 and 4.1
- Last known good version: Visual studio 2022 Preview 3
- IDE: Visual Studio 2022 Preview 3

### Screenshots

![image](https://user-images.githubusercontent.com/91191039/134327437-073841ca-fe83-4815-b2d8-50ac94727077.png)
![image](https://user-images.githubusercontent.com/91191039/134327541-703f8f8b-014a-4eb9-b04d-628c69b6c114.png)
![image](https://user-images.githubusercontent.com/91191039/134327619-893e2483-ddb4-438f-a2d9-1b9ce987a732.png)

**Comment by drasticactions** [comment]
I don't think this is a MAUI bug: it's an issue with the .NET6 Android Platform support and/or the .NET6 SDK you're running. You can, most likely, replicate it with a straight .NET6 Android project and trying to set breakpoints within it. 

I would file a bug against Visual Studio.

**Comment by Tkumar2021** [comment]
@drasticactions yes please file a bug against visual studio.

**Comment by Tkumar2021** [comment]
> @drasticactions yes please file a bug against visual studio.

and, i would be good for me if you can send me the link of filed bug.  Thanks.

**Comment by I4-PJ** [comment]
Hello, I have already reported the same (or very similar) issue at 
https://developercommunity.visualstudio.com/t/VS2022-MAUI-exception-thrown-asynchronou/1534748
So any other comments there are welcome

**Comment by jfversluis** [comment]
Issue with tooling and reported in the right place. Closing it here for now. Thank you!
