### ISSUE TITLE
Significant drop in supported Android devices after updating app to .NET 9

### ISSUE THREAD

**Issue by BenDTU** [dotnet/maui#26301]
### Description

After updating an app currently in production to .NET 9, the Google Play console is reporting a significant reduction in supported devices:

![Image](https://github.com/user-attachments/assets/90a22fad-e9b1-41f1-a4c9-4a297a52a9ee)

The TargetFrameworkVersion seems to have increased from 34 to 35, though I'm not sure what determines this. I have only changed the bare minimum to get it running against .NET 9.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

### Relevant log output

```shell

```

**Comment by davidverriere** [comment]
Hi,
according to the updatingn notes, you have to specify the android-arm target : 
[https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0#64-bit-architectures-by-default](https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0#64-bit-architectures-by-default)

**Comment by jfversluis** [comment]
Thanks for the help @davidverriere

**Comment by minhiclick** [comment]
My app uses .NET 9.0, after publishing to Google Play, some devices cannot install it. Google Play reports the error "This app is no longer compatible with your device...". Galaxy A02s phone (armx64), Android 14 operating system. Previously, this phone installed the app with .NET 8.0 and it worked normally.
