### ISSUE TITLE
Install/Upgrade scenario with new host builder pattern

### ISSUE THREAD

**Issue by profix898** [dotnet/maui#2630]
The new HostBuilder pattern is pretty great. But, I'm struggling to implement an install/upgrade scenario with it. Let me explain:

This is/was my startup path in Xamarin.Forms:
1. App (with default window) launches
2. Show install/upgrade page (-> perform install/upgrade tasks)
3. Create and populate DI container
4. Instantiate main page (which involves resolving DI dependencies) and show it

In a Xamarin.Forms app you start with the main (and only) application window. So in the Ctor of your application class or in OnStart you could show an install/upgrade page (with user interaction or progress reporting) and then, after all install/upgrade task are completed (e.g. upgrade database, move files, etc.), you would create and populate a custom DI container and launch your app's main page. In MAUI that's no longer possible.

The HostBuilder pattern requires me to populate any services required by the app before the app is actually created. So in principle, I could do install/upgrade before that, but since no window has been created yet at that stage, there can't be any user interaction or progress page.
But you can't do it after the builder phase either, because at that point the DI container is already locked and DI dependencies have been resolved (injected etc.).

The question is: How would you realize such a scenario in a MAUI app?

**Comment by Eilon** [comment]
Hi @profix898 , in general there shouldn't be any special relationship between install/upgrading an app, and what goes on to do with the MauiAppBuilder / DI / hosting / HostBuilder / startup.

The "stuff" that goes into DI / HostBuilder / etc. is all the various requirements of the app, such as services, configuration, etc. Then your app can start to show its UI. If that UI happens to be some sort of upgrade UI, you can choose to show that, or not.

If your app needs different services between the "upgrade" scenario and "non-upgrade" scenario then I would like to learn more about that. In general it's safe to always _register_ all the services your app could ever need. They'll only be _created_ if you actually use them, which I could easily see being different in upgrade/non-upgrade.

Can you share more info about what services you're not able to register, and why?

**Comment by profix898** [comment]
**What services you're not able to register ...**

Well, in my app (or at least in the current design), an install/upgrade task is required before the services can execute (move files, download something required for run, database upgrade, etc.). Obviously, you could have "upgrade checks/routines" in each service, but it is so much easier to simply execute a task at startup, so that each service can "boot" into its latest version and expected state.
Another typical situation would be that configuration decides which services to register/load. (Yes, I understand that register/consume is not necessarily the same)

In general, it is not so unusual that you want to display something during bootstrap. For desktop apps you sometimes even have a progress bar or component loading info on the splash screen, which is displayed while preparing services.

**App structure and DI bootstrap**

I guess the problem is that in MAUI the application class itself is part of the DI bootstrap. Before (in XF), you would have a custom DI container created from inside of the application class (at which point you have UI abilities).

I played with the latest MAUI bits some more and I found that the above scenarios are still possible. You can use a secondary/custom DI container, e.g. in CreateWindow or the Ctor of the application class. And there you can show a page (user interaction, progress report) in the first/main application window (as before).
This way, you also enable re-composition scenarios, e.g. where you enable/disable a component of your modular app and then recompose (typically with a new DI container) to build an adapted experience/UI. That is also not be possible with the standard DI container.

**Demo project**

I created a (very) simple demo project to show how I would design my app to enable a) the install/upgrade screen at start and b) the recomposition scenario: https://github.com/profix898/MauiDIIntro
I hope that some demo code makes it a little easier to understand what I'm trying to do.

As I said, it is perfectly doable in MAUI (now that I understand the design, anyway). However, its quite unfortunate that all application-relevant DI stuff happens separately (in custom DI container) in that case. It makes the build-in DI as part of the host builder somewhat redundant. For simple applications, its still a good concept.
*I'm just trying to point out things that are not possible or more difficult to achieve with the new pattern.*

P.S. Feel free to close this issue if you think the current design works well enough for most apps ;)

**Comment by Eilon** [comment]
@profix898 thank you for the additional info.

> install/upgrade task is required before the services can execute

I think this is perfectly reasonable, but also it shouldn't _necessarily_ be a problem with setting up the DI container in `MauiProgram`. In `MauiProgram` the code only _sets up_ the services. It isn't creating any services or running any code in those services. It's not even instantiating those services. It's just registering that _if_ someone needs a `typeof(ISomeService)` to _then_ go create a `SomeServiceImplementation`. But if the upgrade code paths in the app don't use that service, then none of that code at all will run.

In the case where there is a service that needs to change its behavior between "upgrade" and "regular" then I think it could make sense to have some other singleton stateful service in the app that indicates the "mode" so that other services can query it to know how to behave. Here's an outline:

```c#

// Common services
enum AppMode { Regular, Upgrade }
interface IAppModeService
{
    AppMode CurrentAppMode { get; }
    void ChangeMode(AppMode newMode);
    event Action ModeChanged { add; remove; }
}

// Upgrade services/logic
interface IUpgradeManager
{
    void DoUpgrade();
}
class UpgradeManager : IUpgradeManager
{
    readonly IAppModeService _appModeService;
    public UpgradeManager(IAppModeService appModeService)
    {
        _appModeService = appModeService;        
    }

    public void DoUpgrade()
    {
        // TODO: Do the upgrade stuff (move files, etc...)

        // Then alert the rest of the app that the upgrade is done
        _appModeService.ChangeMode(AppMode.Upgrade);
    }
}

// Other app services/logic
interface ISomeService
{
    void DoStuffThatDependsOnAppMode();
}
class SomeServiceImplementation : ISomeService
{
    readonly IAppModeService _appModeService;
    public SomeServiceImplementation(IAppModeService appModeService)
    {
        _appModeService = appModeService;
        // here you can monitor changes to the app mode (might not be useful/needed)
        _appModeService.ModeChanged += { ... };
    }
    public void DoStuffThatDependsOnAppMode()
    {
        // here you can do something that depends on the app mode
        if (_appModeService.CurrentAppMode == AppMode.Upgrade)
        { ... }
        else
        { ... }
    }
}

// MauiProgram registration
var builder = MauiApp.CreateBuilder();
builder
    .UseMauiApp<App>();
builder.Services.AddSingleton<IAppModeService, ...>();
builder.Services.AddSingleton<IUpgradeManager, UpgradeManager>();
builder.Services.AddSingleton<ISomeService, SomeServiceImplementation>();
```

I think it's also worth mentioning that you can plug in various other DI systems, such as Autofac, in case there's one that has some features that you'd find useful in your apps: https://github.com/dotnet/maui/pull/2137#issuecomment-903457201

So maybe some of this clears a few things up about one way to go about this? Or maybe I missed the point and made it even more confusing 😁
