### ISSUE TITLE
Shell.Current.FlyoutBehavior is not taking account in a mixed Flyout Behavior scenario

### ISSUE THREAD

**Issue by davidverriere** [dotnet/maui#26302]
### Description

After updating from .Net 8 to .Net 9
Shell.Current.FlyoutBehavior is not taking account in a mixed Flyout Behavior scenario.

I tested to change the setting in 
- AppShell for each page
- Directly in the apge (xaml and cs)

The behavior was ok in .Net 8

### Steps to Reproduce

Use AppShell
One Page with Shell.Current.FlyoutBehavior = FlyoutBehavior.Disable
One Page with  Shell.Current.FlyoutBehavior = FlyoutBehavior.Locked

When you switch page Shell.Current.FlyoutBehavior is not applied.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Android

### Did you find any workaround?

The workaround is to force the switch like that : 
    protected override void OnAppearing()
    {
        base.OnAppearing();
        Shell.Current.FlyoutBehavior = FlyoutBehavior.Disabled;
        Shell.Current.FlyoutBehavior = FlyoutBehavior.Locked;
    }

### Relevant log output

```shell

```

**Comment by karthikraja-arumugam** [comment]
@davidverriere, can you add a simple reproduction sample?

**Comment by colemcarthur** [comment]
This issue also effects .NET 9 Windows and iOS platforms.

**Comment by colemcarthur** [comment]
Here's an example of the issue. Please note that it only occurs when the pages are registered as singletons. If the pages are not registered, this issue does not arise.

https://github.com/colemcarthur/MAUI_Issue_26302_Project

**Comment by Ying-6** [comment]
This issue has been verified using Visual Studio 17.13 Preview 2.0 (9.0.10). Can repro on android and Windows platform. But not repro on 9.0.21 & 8.0.100.

**9.0.10:**
![Image](https://github.com/user-attachments/assets/e0ead379-e1b8-4150-970c-afbae7695a6e)

**9.0.21:**
![Image](https://github.com/user-attachments/assets/34c098d6-3e26-4857-a1ed-44c7f721f71a)

**Comment by colemcarthur** [comment]
9.0.21 appears to have fixed the Shell.FlyoutBehavior but there is another issue that happens in 9.0.21 that crashes the application (Switch back and forth between the navigation):![Image](https://github.com/user-attachments/assets/576e425d-50dc-4b0b-8183-58d8ccb14822)
