### ISSUE TITLE
Bugs in Absolute Layout with .NET 9

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [dotnet/maui#26317]
### Description

I can see there is small bug, in the <AbsoluteLayout> property.

I have uploaded video here,

https://github.com/user-attachments/assets/55a1d896-fa34-4045-9cf9-018f79ad176e

The Y-Axis <BoxView> part works fine but sometime it automatically can't detect the Rotation property or the LayoutBounds, I am not sure, which property has exactly bugs, but it comes with a extra line as a X-Axis but the thing is that code is remain same, when I remove the code and paste it again then it solved, but after some time it happens again. So look into this issue.

### Steps to Reproduce

<BoxView Color="Black" SemanticProperties.Description="Yaxis"
                 AbsoluteLayout.LayoutFlags="None"
                 AbsoluteLayout.LayoutBounds="150, 0, 3, 300"
                 Rotation="90" />

But see this code, 

Expected outcome: Make it Y-Axis, I have used the Rotation property, it show the Vertically.
Actual outcome: It shows vertically fine, but sometime later it generates another X-Axis line with that, even hot reload doesn't work, if I remove the 
                           code and write it again, then it solve, again it shows the line.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.1.9171

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android

### Did you find any workaround?

As far I remember, it worked well in 8.0.0; but it creates this issue, I did not checked this layout in iOS. But also check for iOS, currently I have no iOS device near to me. So please check it.

### Relevant log output

```shell

```

**Comment by SoumyadipYT-OSS** [comment]
This issue is open, MAUI senior engineer please look into this issue, I found this bug. Hope you understand from it. And chat section is open for discussion on this topic.

**Comment by SoumyadipYT-OSS** [comment]
https://github.com/user-attachments/assets/12966bdf-5169-4837-9386-6be9a192e266


I have taken another video, see it is happening again, I just posted this issue on GitHub, after that I checked in the code and run again and same the issue happening.

**Comment by SoumyadipYT-OSS** [comment]
I found it, the Rotation property has its issue, 

If we implement method overloading for AbsoluteLayout.LayoutBounds class, with (x, y, width, height) that we alreadly have, and add another method with the same name with changing the parameter value (x, y, height, width), but the developer should have pass the parameter name with value like that:

example:
AbsoluteLayout.LayoutBounds=(0, 300, "height={3}", "width={300}"); it could solve the issue, but if there other options, let me know, I want to know more about core components of .NET MAUI.  Discussion open .NET MAUI team, and other .Net developers.
Thanking you,
S Majmder

**Comment by Ying-6** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1 (9.0.10 & 9.0.0 & 8.0.100 & 8.0.0-rc.1.9171). Can repro this issue on Android platform.

**Comment by SoumyadipYT-OSS** [comment]
@tj-devel709 thank you for modified the milestones, I found that you don't need to implement rotation property you can do even exchange the value between the layoutbounds property values where we pass 4 parameters.

@radical @Ying-6 @sheiksyedm I have found the root cause of this property but currently I could not solve but yes I am working on it.

**Comment by SoumyadipYT-OSS** [comment]
﻿<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="_04_AbsoluteLayout.MainPage">

    <Grid Margin="10" HeightRequest="320" WidthRequest="320">
        
        <Image Source="graphpaper.png"
               Aspect="AspectFill"
               Grid.RowSpan="2"
               Grid.ColumnSpan="2" />

        
        <AbsoluteLayout Grid.Row="0" Grid.Column="0" Grid.RowSpan="2" Grid.ColumnSpan="2">
            
            <Image Source="graphchart.png"
                   AbsoluteLayout.LayoutFlags="All"
                   AbsoluteLayout.LayoutBounds="0, 0, 1, 1"
                   Aspect="AspectFit" />

            
            <BoxView Color="Black"
                     AbsoluteLayout.LayoutFlags="All"
                     AbsoluteLayout.LayoutBounds="0, 1, 1, 0.01" />
            <Label Text="X-Axis" SemanticProperties.Description="Xaxis"
                   TextColor="Black"
                   FontSize="14"
                   AbsoluteLayout.LayoutFlags="PositionProportional"
                   AbsoluteLayout.LayoutBounds="0.5, 1.08, AutoSize, AutoSize" />

            
            <BoxView Color="Black" SemanticProperties.Description="Yaxis"
                     AbsoluteLayout.LayoutFlags="All"
                     AbsoluteLayout.LayoutBounds="0, 0, 0.01, 1" />
            <Label Text="Y-Axis"
                   TextColor="Black"
                   FontSize="14"
                   AbsoluteLayout.LayoutFlags="PositionProportional"
                   AbsoluteLayout.LayoutBounds="-0.15, 0.5, AutoSize, AutoSize" />


            
            <BoxView BackgroundColor="#45556050"
                     Color="Transparent"
                     AbsoluteLayout.LayoutFlags="PositionProportional, All"
                     AbsoluteLayout.LayoutBounds="0.33, 1, 0.1, 0.4" />

            <BoxView BackgroundColor="#50008080"
                     Color="Transparent"
                     AbsoluteLayout.LayoutFlags="PositionProportional, All"
                     AbsoluteLayout.LayoutBounds="0.5, 1, 0.1, 0.65" />


            
            <Label Text="(Value)"
                   TextColor="DarkViolet"
                   FontSize="20"
                   AbsoluteLayout.LayoutFlags="YProportional"
                   AbsoluteLayout.LayoutBounds="5, 0" />
            <Label Text="(Time)"
                   TextColor="DarkCyan"
                   FontSize="20"
                   AbsoluteLayout.LayoutFlags="XProportional"
                   AbsoluteLayout.LayoutBounds="1, 320" />
        </AbsoluteLayout>
    </Grid>

</ContentPage>

This code works fine for now, I am looking for the Rotation property solution. If anybody found discussion is still open.

**Comment by SoumyadipYT-OSS** [comment]
Issue solved! We can successfully closed this issue, if somebody is there please don't forget to give feedback on this

**Comment by karthikraja-arumugam** [comment]
@SoumyadipYT-OSS, The rotation issue can be resolved by modifying the default style.

In the default BoxView style in the Resource, the BackgroundColor is set. To fix this, you can use the **Color** property in the style instead of **BackgroundColor**. This ensures that the color is applied correctly after the rotation.

 ```
  <Style TargetType="BoxView">
        <Setter Property="Color" Value="{AppThemeBinding Light={StaticResource Gray950}, Dark={StaticResource Gray200}}" />
    </Style>
```

**Comment by SoumyadipYT-OSS** [comment]
@karthikraja-arumugam Is the AppThemeBinding a default library for this?
