### ISSUE TITLE
Visual Studio XAML Editor shows error for new keyboard types on Editor and Entry controls

### ISSUE THREAD

**Issue by Bowman74** [dotnet/maui#26321]
### Description

When adding the Keyboard attribute to an Editor or Entry field in Visual Studio using the three new values, Password, Date, and Time, the xaml editor and Visual Studio see it as an error. However, the application is still able to compile (Tried on iOS, Android and Windows) and appears to work fine when running. This seems to be solely an issue with the XAML values that the Visual Studio editor thinks are correct for the Keyboard attribute.

### Steps to Reproduce

1) Create a new MAUI project with XAML files
2) Open a xaml file and add an Entry view `<Entry Keyboard="Date" />`
3) Observe error in xaml editor and Visual Studio Error Area

![Image](https://github.com/user-attachments/assets/a2df01c7-cb9b-4716-b3eb-77f70cdb93c3)

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Did you find any workaround?

It is not a show stopper. Likely the xaml validation needs to be updated to honor the new values for Keyboard.

### Relevant log output

```shell

```

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1 (9.0.10 & 9.0.0 & 8.0.100 ). Can repro this issue on any platform.

**Comment by jfversluis** [comment]
When [this PR](https://github.com/dotnet/maui/pull/26329) build completes, would you be able to [test](https://youtu.be/B2FOBjZKm9k) and see if that makes it better?

**Comment by Bowman74** [comment]
@jfversluis 
Absolutely, my pleasure. I'll just spin up a new copy of my VM to implement the prerelease code when I'm done watching your how to video.

I'm creating a LinkedIn Learning class on what is new in MAUI in .Net 9 and just entering these as I find them.

**Comment by Bowman74** [comment]
@jfversluis 
That did it, thanks! After updating the package and restarting Visual Studio, the three new options now show us as valid in the xaml editor.

![Image](https://github.com/user-attachments/assets/48536eba-820e-443a-840c-1a7f28ee1be4)

**Comment by jfversluis** [comment]
Amazing @Bowman74 thanks for verifying! Keep those reports coming!
