### ISSUE TITLE
.Net MAUI [Windows] - The Project does't know how to run the Profile Windows Machine

### ISSUE THREAD

**Issue by Only-Xam** [dotnet/maui#2633]
### Description
.Net MAUI [Windows] - The Project does't know how to run the Profile Windows Machine

### Steps to Reproduce

1. Followed installation guide https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation and 
2. When select Framework .net6.0-windows10.0.19041 
![image](https://user-images.githubusercontent.com/66119201/134363320-672f0f2a-f458-4420-a1ff-33165bd62cc2.png)

and build then below popup appear. Please let me know if anything missing and need to be fixed.

![image](https://user-images.githubusercontent.com/66119201/134363721-e860de42-5925-406c-9fd5-8c753057fb22.png)

### Basic Information

Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 4.1

Microsoft Windows Version 21H1 (OS Build 19043.1237)

**Comment by drasticactions** [comment]
Did you install the Single Project MSIX Vsix? https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17

**Comment by Only-Xam** [comment]
Hi @drasticactions ,

I was trying to downloaded that but somehow it was not working. So I tried to download it again from the link you shared and now it is working fine on Windows. Thanks for your **help.**

![image](https://user-images.githubusercontent.com/66119201/134373958-8dd928f2-a5e3-4195-a65e-7c31dbf1cb7d.png)


Now i see below when using Framewrok android 6.0

The selected emulator couldn't be started. This can be caused by the process not having enough permissions. Please try to start VS as administrator, which can help to avoid it.
Emulator Android_Emulator_30 cannot be started.
2>------ Deploy started: Project: HelloMaui, Configuration: Debug Any CPU ------
2>Need recipe file
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

![image](https://user-images.githubusercontent.com/66119201/134377138-7108a594-3bec-4df3-8854-99a0dfaaac31.png)

Launched VS as admin, then see below:

![image](https://user-images.githubusercontent.com/66119201/134378459-028f5c1b-2140-4478-8e56-e6e1b6e0c111.png)

Any input please, else I will check it further. Thanks for your help

**Comment by drasticactions** [comment]
You need to either install Intel HAXM to enable Hardware Virtualization or enable Hyper-V. This guide can help you get started on enabling the emulator. https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows

I would always set up Hyper-V over HAXM (HAXM only works on Intel based systems, if you have an AMD based system you need to choose Hyper V), and since you don't have either installed, I would choose that given the option.

**Comment by Only-Xam** [comment]
Hi @drasticactions,

Once again thank you for your help. It worked. Just keeping in detail incase anyone else came across similar issue.

Followed link given by you and Installed HAXM - https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows

![image](https://user-images.githubusercontent.com/66119201/134383160-51f0e0ad-5117-4038-b3a8-191f447920e4.png)


Highlighted link in yellow points to - https://github.com/intel/haxm/releases (downloaded file - **haxm-windows_v7_7_0.zip**)
Finally ran the setup file insizde the zip and now I see below is running:

**BEFORE HAXM INSTALL:**

C:\Users\>sc query intelhaxm
_[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service._

**AFTER HXAM INSTALL**

C:\Users>sc query intelhaxm

SERVICE_NAME: intelhaxm
        TYPE               : 1  KERNEL_DRIVER
        **STATE              : 4  RUNNING**
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

Finally all ok.

![image](https://user-images.githubusercontent.com/66119201/134383950-3355a361-b3e5-4901-a364-1067af2f2cfa.png)

**Comment by Only-Xam** [comment]
In addition if you need to enable Hyper-V, refer - How to Install Hyper-V on Windows 10 Home - https://beebom.com/install-hyper-v-on-windows-10-home/
