### ISSUE TITLE
Only few builds fail on build agent with reference to specific iOS Workload Version

### ISSUE THREAD

**Issue by thoefkens** [dotnet/maui#26339]
### Description

On our build agents we have installed MAUI release [8.0.40 (SR5)](https://github.com/dotnet/maui/releases/tag/8.0.40).

A `dotnet workload list` only shows 

`maui - manifest 8.0.40 / 8.0.100 - SDK 8.0.200`

Most builds work perfectly fine, yet somehow, some MAUI builds error:

```
ILLINK : warning MT0079: The recommended Xcode version for Microsoft.iOS 17.2.8053 is Xcode 15.1 or later. The current Xcode version (found in /Applications/Xcode_15.0.1.app/Contents/Developer) is 15.0.1. [xxx.csproj::TargetFramework=net8.0-ios]
08-Nov-2024 11:40:01 	ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [xxx.csproj::TargetFramework=net8.0-ios]
```

What we do not understand: we have tons of projects with the exact same build settings, all set to use MAUI 8.0.40 and XCode 15.0.1 - all builds agents have only MAUI 8.0.40 installed, and yet for one or 2 projects, where we can find not distict difference in the project properties, we get this error.

Why would the MAUI workload - which we assume always installed iOS 17.2.8053 or 17.2.8043 under the hood - fail for certain projects?

### Steps to Reproduce

Automatically build MAUI apps on Bamboo Build Agents (macOS) with XCode 15.0.1 installed 
Install the given maui workload manifest 8.0.40 / 8.0.100 - SDK 8.0.200

Setup build jobs, they may (but mostly do not) fail with error:

```
ILLINK : warning MT0079: The recommended Xcode version for Microsoft.iOS 17.2.8053 is Xcode 15.1 or later. The current Xcode version (found in /Applications/Xcode_15.0.1.app/Contents/Developer) is 15.0.1. [xxx.csproj::TargetFramework=net8.0-ios]
08-Nov-2024 11:40:01 	ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [xxx.csproj::TargetFramework=net8.0-ios]
```

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.3 GA

### Affected platforms

iOS

### Did you find any workaround?

No workaround found. We cannot yet upgrade all machines to XCode 15.1 or 16, this is planned for beginning 2025.

### Relevant log output

```shell

```

**Comment by rolfbjarne** [comment]
The MT0079  warning might not have anything to do with the actual error that happens.

Please get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) for a failing build, this will hopefully have enough info to get a better idea of what's going on.

**Comment by thoefkens** [comment]
Hi @rolfbjarne , please find a bingo attached for the failing build.
I hope this will shed some clarity...

[mspublish.binlog.zip](https://github.com/user-attachments/files/18052613/mspublish.binlog.zip)

Thank you
Thomas
