### ISSUE TITLE
Custom ResourceDictionary fails to load in .NET 9 app

### ISSUE THREAD

**Issue by dotMorten** [dotnet/maui#26348]
### Description

When create a subclass of ResourceDictionary with merged dictionaries for a custom style library targeting .net8.0, the following code is generated:
```
[GeneratedCode("Microsoft.Maui.Controls.SourceGen", "1.0.0.0")]
private void InitializeComponent()
{
	ResourceDictionary resourceDictionary = new ResourceDictionary();
	NameScope nameScope = new NameScope();
	Uri source;
	resourceDictionary.SetAndLoadSource(source = new Uri("Resources/Styles/Brushes.xaml;assembly=MyStyleAssembly", UriKind.RelativeOrAbsolute), "Resources/Styles/Brushes.xaml", typeof(MyStyleAssembly).Assembly, (IXmlLineInfo)new XmlLineInfo(7, 29));
       ...
```
In .NET 9, the `SetAndLoadSource` was changed to internal [here](https://github.com/dotnet/maui/commit/e1400c5438455c8f8ed9203e11915294c551864a), which causes this generated code to fail when referencing the assembly from a nuget package (for some reason I don't quite understand, it doesn't happen with project reference).

![Image](https://github.com/user-attachments/assets/ea78cf15-7b18-4f93-a0a2-680f683cc22c)

If you target .NET 8, the crash does not occur. This change was a breaking binary change that caused a regression. It's probably better to just mark the method non-browsable.

### Steps to Reproduce

1. Open the attached project: [MauiResources.zip](https://github.com/user-attachments/files/17999219/MauiResources.zip)
2. Make sure the class library is set to release build (doesn't repro if the class library is compiled for debug)
3. Observe the above mentioned error.
4. Change the app target to 8.0 and notice the app no longer crashes.

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Android, Windows, macOS, iOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Did you find any workaround?

Add net9 target to class library and reference 9.0.0 of `Microsoft.Maui.Controls`. This only works if you have access to that library though.

### Relevant log output

```shell

```

**Comment by simonrozsival** [comment]
> for some reason I don't quite understand, it doesn't happen with project reference

My best guess is that when you use project reference, the XAML code is rebuilt with XamlC in .NET MAUI 9 which generates code that doesn't need `SetAndLoadSource`. The NuGet package contains the pre-built XAML though, so it will still call `SetAndLoadSource`.

**Comment by dotMorten** [comment]
Sorry ignore my comment on project reference. That was from before I realized it was only release builds causing it and forgot to update that comment. Reproducer shows it reproduces with project reference.

**Comment by Ying-6** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1 (9.0.12 & 9.0.10). Not repro this issue on Windows Platform.
