### ISSUE TITLE
Release build iOS MAUI project takes over 30 minutes

### ISSUE THREAD

**Issue by tj-devel709** [dotnet/maui#26349]
### Description

Using VSCode on Mac, I am having trouble building in release mode. This happens on a brand new Maui App created in VSCode.
This occurs with versions: 9.0.10-ci.net9.24524.5, 9.0.0, 9.0.12, 8.0.100. In the 9.0.X versions, the simulator was not created at all and in the 8.0.100 version, the simulator was prompted but still does not do anything. VSCode version is: 1.95.3

I am setting the build configuration to release as shown here:
![Image](https://github.com/user-attachments/assets/cfec0a24-9927-4058-afe9-3a22a8f90361)

On iOS (18.1 iPhone15 simulator), the `_AOTCompile` step goes on for 20+ minutes until I stop it.
![Image](https://github.com/user-attachments/assets/cebd7be4-367e-4aa8-9ca8-5e2a6f401a14)

** UPDATE - It built after 30 minutes and 40 seconds so it just takes a really long time

### Steps to Reproduce

1. Create a new Maui App
2. Set the build to Release mode
3. Build the project and observe the app does not finish deploying

### Link to public reproduction project repository

New Maui App

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Relevant log output

```shell

```

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio Code (9.0.12 & 9.0.0). Can repro this issue on iOS platform. 8.0.100 not repro this issue. And this is a unstable issue.

**Comment by tj-devel709** [comment]
Actually there is already an issue on MaciOS so I'll close this issue but tag this one there just in case!
