### ISSUE TITLE
[Windows] ListView ScrollTo Method Throws NullReferenceException

### ISSUE THREAD

**Issue by nivetha-nagalingam** [dotnet/maui#26345]
### Description

When using ListView's ScrollTo method with a custom List implementation that implements INotifyCollectionChanged, a NullReferenceException occurs in the ListViewRenderer on Windows.

### Steps to Reproduce

- Create new .NET MAUI project
- Implement custom List<T> class implementing INotifyCollectionChanged
- Create ListView with 1000+ items using custom List
- Call ScrollTo() to last item
- Click button to replace last item
- Run the project and Observe NullReferenceException in ListViewRenderer
- [Issue3788ListView.zip](https://github.com/user-attachments/files/17996198/Issue3788ListView.zip)

Expected Behavior:
- ListView should visible and scroll to last item
- When click the button , Replacing item should update single item only

Actual Behavior:
- NullReferenceException thrown when ScrollTo is called
- Exception occurs in ListViewRenderer.cs

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Relevant log output

```shell

```

**Comment by ninachen03** [comment]
Could you provide a sample project for us to investigate it further?
Looking forward to your reply!

**Comment by nivetha-nagalingam** [comment]
Here, I have attached the project file for your investigation.[Issue3788ListView.zip](https://github.com/user-attachments/files/18002893/Issue3788ListView.zip)
And also Please refer to the file attached in the description for further details.

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.13.0 Preview 1.0(9.0.12 & 8.0.100 & 8.0.3). Can repro this issue at Window platform.
![Image](https://github.com/user-attachments/assets/403287f4-7766-4e46-b161-7fde23420274)
[Issue4973.zip](https://github.com/user-attachments/files/18021348/Issue4973.zip)
