### ISSUE TITLE
[iOS] App Freezes When Pressing Return Key in Editor with Text Binding to Entry

### ISSUE THREAD

**Issue by anandhan-rajagopal** [dotnet/maui#26341]
### Description

The application consistently freezes when typing text into an editor component and pressing the return button on the iOS keyboard. This behavior prevents further interaction with the app and requires a restart to regain functionality. On other platforms it works fine.

### Steps to Reproduce

Reproduction Steps:

1. Create a new MAUI application.

2. Replace the MainPage.xaml.cs content with the following code:

```
namespace MauiApp1;

public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();

        Editor editor;
        Entry entry;

        editor = new Editor();
        entry = new Entry();

        editor.SetBinding(Editor.TextProperty, "Text");
        editor.BindingContext = entry;
        editor.Placeholder = "Editor";
        editor.AutoSize = EditorAutoSizeOption.TextChanges;
        editor.AutomationId = "EditorAutomationId";

        entry.SetBinding(Entry.TextProperty, "Text");
        entry.BindingContext = editor;
        entry.Placeholder = "Entry";
        entry.AutomationId = "EntryAutomationId";

        Content = new StackLayout()
        {
            new Label(){ Text = "Typing into either text field should change the other field to match" },
            entry,
            editor
        };
    }
}
```
3. Deploy the application to an iOS simulator or physical device.

4. Type text into the Editor component.

5. Press the return button on the iOS keyboard and observe the application behavior.

Expected Result:
The application should process the return key without freezing, allowing the binded entry text to update without interrupting the user interaction.

Actual Result:
The application freezes upon pressing the return key, requiring a force restart to recover.

### Link to public reproduction project repository

NA

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18.0

### Did you find any workaround?

NA

### Relevant log output

```shell

```

**Comment by kubaflo** [comment]
Hi @anandhan-rajagopal You're setting the BindingContext of editor to entry and vice versa. This probably causes an infinite loop when trying to resolve the binding because they are referencing each other directly. This is not how bindings are typically established.

Would it work like you intend when you do either of these?

`editor.SetBinding(Editor.TextProperty, "Text", mode: BindingMode.OneWay);`
or
`entry.SetBinding(Entry.TextProperty, "Text", mode: BindingMode.OneWay);`

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1 (9.0.10 & 9.0.0 & 8.0.100 ). Can repro this issue on iOS platform.
