### ISSUE TITLE
[MAUI] D13_ The background color is inconsistent and varies in light and dark colors.

### ISSUE THREAD

**Issue by ninachen03** [dotnet/maui#26356]
### Description

[MAUI] D13_The background color is inconsistent and varies in light and dark colors.
**Affected case**:
D13 - Customize text alignment

### Steps to Reproduce

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Android
2. Navigate to 'D_Editor' ->'D13_ Customize text alignment'
3. Observed the background color.

**Actual Behavior**:
The background color is inconsistent and varies in light and dark colors.
![Image](https://github.com/user-attachments/assets/603f9a31-dd21-4939-b916-ea306cd5fc7a)
**Expected Behavior**:
The background color is consistent 

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug
Microsoft.Maui.Controls 9.0.20-ci.main.24603.2

### Is this a regression from previous behavior?

**Not a regression**, the issue also reproduces on 9.0.10 & 9.0.0& 8.0.100 & 8.0.3

### Affected platforms

Android

**Comment by tj-devel709** [comment]
I am using a Pixel 3a API 35 device with version Microsoft.Maui.Controls 9.0.20-ci.main.24603.2 and am not seeing these different colors. Have you tried using a different simulator or a physical device and seen similar behavior?

![Image](https://github.com/user-attachments/assets/757424df-daea-4c42-9199-5f9fcbf4e108)

**Comment by tj-devel709** [comment]
Also do not see when using Pixel 7 with Microsoft.Maui.Controls 9.0.20-ci.main.24603.2
![Image](https://github.com/user-attachments/assets/45f13722-a096-45b9-9452-1f8669af6a97)

**Comment by ninachen03** [comment]
I found that this issue is reproduced on the remote machine, not on the local machine and Physical Device. I will change the step.

**Comment by ninachen03** [comment]
@tj-devel709  I found this problem, it only occurs when it is remote, and it does not occur on local machines or physical devices.

**Comment by jfversluis** [comment]
@ninachen03 you mean remote as in when you log in with Remote Desktop? I think that might be a factor... I will close this for now as I don't think its an issue with us but just because how things show up when using Remote Desktop :)

Thanks!
