### ISSUE TITLE
Maui CarousselView is still no sizing correct in iOS

### ISSUE THREAD

**Issue by nvgogh** [dotnet/maui#26389]
### Description

This issue has been raised multiple times but it's still not resolved.

In iOS Maui app when you add a CarouselView without an ItemHeight. So the control need to figure out itself how much space it can allocate. It always defaults to the full page height.

The red part is the space claimed

![Image](https://github.com/user-attachments/assets/50e47e80-e881-46b1-b8de-c4558276e013)

### Steps to Reproduce

I used the sample project
https://github.com/dotnet/maui-samples/tree/main/9.0/UserInterface/ControlGallery

And change the CarouselViewDemoPage.xaml to the following content

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ControlGallery.Views.XAML.CarouselViewDemoPage"
             Title="CarouselView Demo">
    <ScrollView>
    <StackLayout Margin="20">
        <Label Text="CarouselView"
               FontSize="50"
               FontAttributes="Bold"/>
        <CarouselView ItemsSource="{Binding Monkeys}">
            <CarouselView.ItemTemplate>
                <DataTemplate>
                    <StackLayout BackgroundColor="Red">
                        <Border Stroke="DarkGray"
                                StrokeShape="RoundRectangle 5"
                                Margin="20"
                                Padding="20">
                            <StackLayout>
                                <Label Text="{Binding Name}" 
                                       FontAttributes="Bold"
                                       FontSize="20"
                                       HorizontalOptions="Center"
                                       VerticalOptions="Center" />
                                <Image Source="{Binding ImageUrl}" 
                                       Aspect="AspectFill"
                                       HeightRequest="150"
                                       WidthRequest="150"
                                       HorizontalOptions="Center" />
                                <Label Text="{Binding Location}"
                                       HorizontalOptions="Center" />
                                <Label Text="{Binding Details}"
                                       FontAttributes="Italic"
                                       HorizontalOptions="Center"
                                       MaxLines="5"
                                       LineBreakMode="TailTruncation" />
                            </StackLayout>
                        </Border>
                    </StackLayout>
                </DataTemplate>
            </CarouselView.ItemTemplate>
        </CarouselView>
        <Label Text="Test" />
    </StackLayout>
    </ScrollView>
</ContentPage>
``` 

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/9.0/UserInterface/ControlGallery

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

I haven't found a proper workaround other then setting ItemHeight to a fixed value (which I don't want since the content it dynamic)

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
> This issue has been raised multiple times but it's still not resolved.

Is there a current open issue about this, like this one suggested by the bot #24077?

If yes, please don't open new issues about the same thing, that will only create multiple issues with a lower priority instead of 1 issue where people can +1 and _that_ will because an issue of importance.

If there is another issue that describes what you are seeing, please add your details to that one and close this one. Thanks!

**Comment by nvgogh** [comment]
I had hoped (and that is the reason I did all the work to upgrade the maui app to net9) that the new improved carouselview would fix the issue. I am just reporting that it is still not working also with the new control.

**Comment by jfversluis** [comment]
I totally understand and I'm sorry that that is not the case. But its much more helpful to add to an existing issue, that way it will increase its importance, instead of opening new ones. Thanks for letting us know!
