### ISSUE TITLE
Net 9 Android - StatusBar Color overriden on modal pages

### ISSUE THREAD

**Issue by Zack-G-I-T** [dotnet/maui#26388]
### Description

In MAUI Android, when adding CommunityToolkit StatusBarBehavior to change the color, and then going to a modal page - the status bar color gets replaced with the colorPrimary color from colors.xml.

This only happens on NET 9. In NET 8 the status bar color remained the same as the previous page.
I think its because int NET 9 in the App.cs you have to create a new Window for the app shell, but is there a solution to the status bar changing?

`protected override Window CreateWindow(IActivationState? activationState)
{
    var window = new Window(new AppShell());
    return window;
}`

In the modal page, the status bar color should be the same as the previous normal page. This was the behaviour in NET 8

### Steps to Reproduce

1. Open repo
2. Run in NET 9 for Android and click on the button - see the status bar color change from orange to green/red.
3. Change to NET 8 - see the color stays orange throughout.

### Link to public reproduction project repository

https://github.com/Zack-G-I-T/StatusBarIssue-Net9

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Android

### Relevant log output

```shell

```

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.13.0 Preview 1.0 (9.0.12 & 9.0.0 &8.0.100). Can repro on android platform.

**Comment by jfversluis** [comment]
This issue was moved to CommunityToolkit/Maui#2371
