### ISSUE TITLE
Navigation.PopModalAsync() - When popping a modal page off the stack and app loses focus - Modal Page does not leave the UI.

### ISSUE THREAD

**Issue by krookdfinger** [dotnet/maui#26418]
### Description

When popping off a modal page in a method that has a long running task and the app loses focus, either by minimizing or clicking off the app. It will be removed from the modal navigation stack but will not be removed from the UI. 

### Steps to Reproduce

1) In the MainPage  Push a modal page on the navigation stack.

```
        private void OnAddModalPageClicked(object sender, EventArgs e)
        {
            Navigation.PushModalAsync(new modal());
        }
```

2) On the modal page create a delay task.  

```
 private async void OnPopModalPageClicked(object sender, EventArgs e)
    {
        // Lose focus either by clicking off the app or minimizing it, before the delay finishes... 
        await Task.Delay(2000);
        await Navigation.PopModalAsync();
    }
```
3) run the app... click add modalPage... 
4) Click Pop Modal Page Button and then click off the app

You will see that the page does not get removed on screen... but if you inspect the Navigation stack count it is physically gone.

### Link to public reproduction project repository

https://github.com/krookdfinger/TestNavigationStack

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

Have not found a work around yet... 

### Relevant log output

```shell

```

**Comment by kevinxufei** [comment]
I can repro it at Windows platform on the latest 17.13 preview 1(8.0.100 & 8.0.93).

**Comment by colemcarthur** [comment]
I can also reproduce this issue on the Windows platform (8.0.100). It severely disrupts navigation, rendering the application unusable with the modal remaining on the stack. This should be considered a top priority.

**Comment by powderf1nger** [comment]
I am also experiencing this problem using 8.0.100 and cannot find a work around.

**Comment by krookdfinger** [comment]
I updated the test project to .Net 9 and the issue doesn’t exit as it does with .Net 8.0.100

Unfortunately, I can’t move my production application to .Net 9 right now as it will take weeks to test thoroughly under .Net 9 with other components for any other issues 9 may present.

I need a fix under .Net 8. ASAP as users are getting very upset with this issue.

**Comment by jfversluis** [comment]
I don't think we will take the effort to backport to .NET 8 and even if we would, that release will probably happen around Jan/Feb 2025 so that will be weeks away as well.

Also, keep in mind that .NET 8 will be supported (for .NET MAUI) [until May 2025](https://dotnet.microsoft.com/platform/support/policy/maui). So personally I think starting to look into .NET 9 is the right move for you here.

**Comment by krookdfinger** [comment]
Thank you Gerald.  Appreciate it. Not really the answer I was hoping for.  I'm just under a tight time line and worried about all the other monsters hiding .Net 9.

**Comment by jfversluis** [comment]
It shouldn't be that many! Hoping upgrading will be smooth. Thanks for your understanding!

**Comment by krookdfinger** [comment]
Upgraded project and started to test .Net9....  Now I have this issue...  This is killing me guys...

https://github.com/dotnet/maui/issues/26302

On a positive note, I do notice a very big improvement on speed when moving to .Net9
