### ISSUE TITLE
System.ArgumentOutOfRangeException: ArgumentOutOfRange_IndexMustBeLess Arg_ParamName_Name, index

### ISSUE THREAD

**Issue by minhiclick** [dotnet/maui#26419]
### Description

This bug occurs for Collection View control. The bug occurs randomly, it is difficult to make the bug appear because the rate is low. This bug has existed for a long time. 

Below is the log track:

System.Collections.Generic.List`1[[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Item(Int32 )
System.Collections.Generic.List`1[[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].System.Collections.IList.get_Item(Int32 )
Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.ElementAt(Int32 index)
Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.GetItem(Int32 position)
Microsoft.Maui.Controls.Handlers.Items.UngroupedItemsSource.GetItem(Int32 position)
Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].UpdateMauiSelection(Int32 adapterPosition)
Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SelectableClicked(Object sender, Int32 adapterPosition)
Microsoft.Maui.Controls.Handlers.Items.SelectableViewHolder.OnViewHolderClicked(Int32 adapterPosition)
Microsoft.Maui.Controls.Handlers.Items.SelectableViewHolder.OnClick(View view)
Android.Views.View.IOnClickListenerInvoker.n_OnClick_Landroid_view_View_(IntPtr jnienv, IntPtr native__this, IntPtr native_v)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

This pull seems to have fixed it but is not updated in .NET 9.0:
https://github.com/dotnet/maui/pull/22676

### Relevant log output

```shell

```

**Comment by wooolly** [comment]
I've just started using Collection View for the re-ordering capability, and when I try to move the bottom item in the list upwards, it will throw an out of range exception. This is a consistent issue for me and happens every time, only on Android.

**Comment by minhiclick** [comment]
@wooolly This is a very serious bug of Collection View but it has not been fixed for a long time.
As in this post, the fix is ​​quite simple.
https://github.com/dotnet/maui/pull/22676.

Programmers all feel that Collection View is a terrible control because it is slow and has many errors.

**Comment by jfversluis** [comment]
Are you able to maybe test the fix from [this PR](https://github.com/dotnet/maui/pull/22676) on your project and let us know if that indeeds resolves your issue? If you need any instructions on how to test, please use [this video](https://youtu.be/B2FOBjZKm9k).

**Comment by jfversluis** [comment]
Fixed by #22676
