### ISSUE TITLE
[Bug] Grid's GestureRecognizers not working

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2642]
Hi,

Thet TapGestureRecognizer is having a problem in below attached sample.

Here is the details:

[https://docs.microsoft.com/en-us/answers/questions/548661/grid39s-gesturerecognizers-not-working.html?childToView=561698#comment-561698](https://docs.microsoft.com/en-us/answers/questions/548661/grid39s-gesturerecognizers-not-working.html?childToView=561698#comment-561698
)

**Comment by VincentBu** [comment]
@jrahma I write a simple project and Grid.GestureRecognizer works well on IOS. Let mw know if I lost any detail.
[2642.zip](https://github.com/dotnet/maui/files/8122475/2642.zip)

**Comment by Redth** [comment]
Fixed in recent previews, please open a new issue if you still have problems.
