### ISSUE TITLE
Shell.FlyoutItemIsVisible on FlyoutItem in Shell binding does not update

### ISSUE THREAD

**Issue by StefanCuypers** [dotnet/maui#26434]
### Description

When binding the Shell.FlyoutItemIsVisible the visibility does not update.
This used to work in Maui .Net8, but in .Net9 it does not work any more.

### Steps to Reproduce

See example in repro repository.
MauiAppProblemFlyout : .Net 9 version
MauiAppProblemFlyout8 : .Net 8 version

Run it and look at the flyouts: Applications is not visible. Now check the checkbox. In .Net8 the Applications flyout becomes visible, in .Net9 it does not.

### Link to public reproduction project repository

https://github.com/StefanCuypers/MauiAppProblemFlyout

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.83 SR8.3

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11, Android 13.0 API33

### Did you find any workaround?

You can do the binding manually. Registering on INotifyPropertyChanged and setting visibility manually based on changes to the property.

### Relevant log output

```shell

```

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1 (9.0.10 & 9.0.0). Can repro this issue on Android and Windows platforms. It works fine on 8.0.100 and 8.0.83.

**Comment by StefanCuypers** [comment]
@karthikraja-arumugam 
Yes, that indeed works. Thanks a lot for sharing that.

So solution is to use FlyoutItemIsVisible instead of Shell.FlyoutItemIsVisible.
