### ISSUE TITLE
Android Splash Screen

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2644]
Hi,

Please provide a UI for the android splash screen similar to the Assets in iOS project so the developer can just pick the file of the splash screen.

Thanks,
Jassim

**Comment by jfversluis** [comment]
The splash screen is something that is handled now in a shared way over the different projects. If you want to do something per platform you're going to have to do some platform-specific code for this.

If you would still like to see something like this, I would love to see a more detailed feature request following our template that we have in place.
