### ISSUE TITLE
"java.exe" exited with code 1.

### ISSUE THREAD

**Issue by quantraxgit** [dotnet/maui#26442]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Do you have any more information like build logs or anything? With just this error message it’s impossible to determine what might be causing this :)

Thanks!

**Comment by quantraxgit** [comment]
I was able to fix the issue by increasing the RAM size of the emulator.

Thank you.
