### ISSUE TITLE
Android 15 navigation/title bar overlapping app.

### ISSUE THREAD

**Issue by kounenis** [dotnet/maui#26452]
### Description

On Android 15 the App is extending edge to edge by default. The top and bottom parts of the app are overlapped by Android navigation bar and status bar. This happens on .net 8 and also .net 9 targetting Android 15.

![Image](https://github.com/user-attachments/assets/fffd2de0-90ed-4f0d-bf9c-b9d391c0e6ce)
![Image](https://github.com/user-attachments/assets/746cebb0-e917-4033-8212-840b591085c9)

### Steps to Reproduce

1. Create new Maui project (Blazor hybrid or classic)
2. Run on pixel 7 (android 15) emulator.

It is also be reproduced on real Pixel 7 devices upgraded to Android 15.

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 15

### Did you find any workaround?

No

### Relevant log output

```shell

```

**Comment by kubaflo** [comment]
Hi @kounenis I'm pretty sure @Redth fixed it in this PR: https://github.com/dotnet/maui/pull/25517

You're probably using the MAUI version without this fix

Maybe try with the following:

`<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.12" />`

**Comment by kounenis** [comment]
That worked, thank you.
