### ISSUE TITLE
Video Splash Screen

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2645]
Hi,

Please provide a UI to pick and set a video file as splash screen for both iOS and Android apps.

Thanks,
Jassim

**Comment by maxkoshevoi** [comment]
Starting Android 12 you can do animated splash screens: https://developer.android.com/guide/topics/ui/splash-screen#set-theme
Before that, they can only be static

**Comment by jfversluis** [comment]
Duplicate of #3300

**Comment by jfversluis** [comment]
Please make sure you don't open the same suggestion more than once as it will only add noise
