### ISSUE TITLE
Android FlyoutPage does not display navigation bar NET 8

### ISSUE THREAD

**Issue by Ashishghi** [dotnet/maui#26472]
### Description

i have been working on xamarin migration to maui and in my project, i integrated flyout page feature , it's working fine on ios but on android, elements on navigation bar is not displayed (such as title of the page, hamburger icon, navigation tools on top right side).
this issue only occurs initially when try to open my app, after tapping on any item and then back, elements on navigation bar including hamburger icon are displayed.

2. second observation - when this issue happens initially, i tried swiping flyout menu, works fine, able to swipe.

3. third observation - tried commenting flyout page feature, then i see elements on navigation bar like title of the page and tools on top right side is displayed,

means, using flyout page causing issue, where hamburger icon and elements on navigation bar is not displayed and that happens only initially when open the app.

please help me out if anyone have any idea?
![Image](https://github.com/user-attachments/assets/9dccf2a2-0665-4856-9137-9ade5f18d54f)

![Image](https://github.com/user-attachments/assets/d7b1f18d-72fd-47cd-9668-2ddf46c5a9c7)

![Image](https://github.com/user-attachments/assets/dba05cc6-2b98-4ebb-852f-41c27fe9f3b7)
elements on navigation bar are displayed when intracting with app, like tap on any item and back, then they are displayed works fine.

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Affected platforms

Android

### Did you find any workaround?

i tried with some solution but none of them worked out.

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
Without any relevant code or a reproduction its near impossible to say something that can help you further unfortunately.

**Comment by Ashishghi** [comment]
i am using a custom navigation to manage ViewModels and Pages in a .NET MAUI app, please see the code below for your understading - 

if (viewModel.DrawerMenuViewModelType != null)
            {
                var flyoutPage = new FlyoutPage
                {
                    Flyout = ResolvePageAndViewModel(viewModel.DrawerMenuViewModelType, null),
                    Detail = page,
                };
                if (DeviceInfo.Current.Idiom == DeviceIdiom.Tablet)
                {
                    // iPad
                    flyoutPage.FlyoutLayoutBehavior = FlyoutLayoutBehavior.Popover;
                }
                flyoutPage.IsPresentedChanged += (sender, eventArgs) =>
                {
                    if (flyoutPage.IsPresented)
                    {
                        ((IBaseViewModel)flyoutPage.Flyout.BindingContext).OnAppearing();
                    }
                    else
                    {
                        ((IBaseViewModel)flyoutPage.Flyout.BindingContext).OnDisappearing();
                    }
                };
                return flyoutPage;
            }
            return page;

NavigationPage.CS :-

 public void SetMainViewModel<T>(object args = null) where T : IBaseViewModel
        {
            Action setmainView = () =>
            {
                try
                {
                    var page = ResolvePageFor<T>(args);

                    if (page == null)
                        throw new Exception("Resolve page for " + typeof(T).Name + " returned null!");

                    var flyoutPage = page as FlyoutPage;
                    if (flyoutPage != null)
                    {
                        flyoutPage.Detail = new BaseNavigationPage(flyoutPage.Detail);
                        Navigation = flyoutPage.Detail.Navigation;
                        App.MainPage = flyoutPage;
                    }
                    else
                    {

                        var navigationPage = new BaseNavigationPage(page);
                        Navigation = navigationPage.Navigation;
                        App.MainPage = navigationPage;
                    }
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.Message);
                }
            };

            if (DeviceInfo.Platform == DevicePlatform.Android)
            {
                MainThread.BeginInvokeOnMainThread(setmainView);
            }
            else
            {
                if (App.MainPage == null)
                {
                    setmainView();
                }
                else
                {
                    MainThread.BeginInvokeOnMainThread(setmainView);
                }
            }
        }

**Comment by Ashishghi** [comment]
Hi, any update on this bug?

**Comment by Bowman74** [comment]
@Ashishghi 
They are going to need a repo with just the code in a complete MAUI project to recreate the issue or it is going to be very hard for them to help you.

**Comment by Ashishghi** [comment]
i have shared all the required screenshots , descriptions and codes for flyout navigation setup,
as mentioned earlier, using flyout causing navigation bar disappearing initially  only when try to open the app on Android. works fine on iOS, no such issue on iOS.

after intracting with app, like taping on any items or opening any items and press back button, then all works fine, Navigation bar with elements is displayed, it wonders me why all working fine after intracting with app.
