### ISSUE TITLE
Maui net8 & net9 - Tab pages do not activate OnAppearing [Mac]

### ISSUE THREAD

**Issue by SamuelJames101** [dotnet/maui#26499]
### Description

OnAppearing is not fired when clicking on tabs other than the first tab.

### Steps to Reproduce

1.Create an app
2.Add multiple appshell tabs
3.Click between the tabs

Expected result
OnAppearing is fired

Actual result
OnAppearing does not fire

This only happens in my Mac M1, for android, ios and windows it works fine

### Link to public reproduction project repository

https://github.com/SamuelJames101/MacTabOnAppearing

### Version with bug

8.0.92 SR9.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac M1 15.0

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
I see you're saying this happens in .NET 8, could you please verify if this still happens in .NET 9? Maybe we have already fixed it there?

**Comment by SamuelJames101** [comment]
It happens in 8.0.40, 8.0.91, 8.0.92 and 9.0.100. I can test it in the newest .Net 9 version but our teams aren't going to .Net9 for a few months.

**Comment by jfversluis** [comment]
Just wanted to make sure, I don't think the latest is going to make a difference, but if this is something you already did, that is very useful information to include. Thanks!

Also,  you do mention that this did used to work, if that is the case; what is the version that it did work in?

**Comment by SamuelJames101** [comment]
I believe It worked pre 8.0.40 but I had updated to 15.0 (Mac version) around the same time so it could be related to that instead

**Comment by Zhanglirong-Winnie** [comment]
Hi, @SamuelJames101 
This issue has been verified using Mac M1(15.2) and Visual Studio Code 1.96.2 (9.0.14 & 9.0.0 & 8.0.92). Not repro this issue on MacCatalyst platform. Could you verify that it still repro on the latest Mac version?
