### ISSUE TITLE
TabbedView layout jumps after loading collection view

### ISSUE THREAD

**Issue by godiamond98** [dotnet/maui#26510]
### Description

I have a tabbedpage with approx 5 different pages/tabs, each tab has either a collectionview or a datagrid. Once the collectionview is loaded the page layout changes and pushes the top part of my page up. This is an app that worked fine in xamarin for years and is being converted to .net maui.

### Steps to Reproduce

1. Create a tabbedpage with a couple content pages for tabs
2. put a collection view in each content page
3. populate the collection view with data ( i am executing a command in the OnAppearing override)
4. the tab bar jumps up on the screen approx 200px when the collection view is rendered. 
5.![Image](https://github.com/user-attachments/assets/d68700ed-bc1d-4ff2-bec3-aaa4db5a072d)
![Image](https://github.com/user-attachments/assets/9fb1d96f-ef0c-45ab-9271-c88345d0deea)

### Version with bug

8.0.83 SR8.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 17 and higher as far as i know

### Did you find any workaround?

no i have tried setting static heights on everything, different controls like grid with row definitions, nothing is preventing the jump.  I have another tabbed layout that does not have collection view or data grids and it works fine.

### Relevant log output

```shell

```

**Comment by Ying-6** [comment]
Could you provide a sample project for us to investigate it further? Looking forward to your reply!

**Comment by godiamond98** [comment]
I have a demo app created, i will get that on github by mondaySent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: "dotnet-policy-service[bot]" ***@***.***> Date: 12/11/24  3:22 AM  (GMT-06:00) To: dotnet/maui ***@***.***> Cc: godiamond98 ***@***.***>, Mention ***@***.***> Subject: Re: [dotnet/maui] TabbedView layout jumps after loading collection
  view (Issue #26510) 
Hi @godiamond98. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

**Comment by PureWeen** [comment]
> Quick demo with datagrid demonstrating the issue, does the same thing when a collection view is used.
> 
> https://github.com/godiamond98/TabbedPagesWithCollectionViewDemo.git

I'm getting a page not found error

One thing that might help you here is to generated a speedscope file
https://github.com/dotnet/maui/wiki/Profiling-.NET-MAUI-Apps

And then you can see what might be taking a lot of time.

**Comment by godiamond98** [comment]
has nothing to with taking a lot of time, not sure where you got that from?
 Also, I forgot to make the repo public, should be able to access it now

**Comment by PureWeen** [comment]
There were a few fixes in 8.0.100 with TabbedPage

can you test that version and see if it acts the same

**Comment by godiamond98** [comment]
8.0.100 seems to have it fixed. I will updated our main project and see how it goes.
