### ISSUE TITLE
Error on dotnet workload install or update

### ISSUE THREAD

**Issue by caliberdigitalllc** [dotnet/maui#26518]
### Description

I'm running into issues installing the maui workload. I have tried dotnet install workload maui, I've tried dotnet restore, I've tried dotnet workload  update... they all end in some variation of this outcome.

PM> dotnet restore

Welcome to .NET 9.0!
---------------------
SDK Version: 9.0.101

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate, run 'dotnet dev-certs https --trust'
Learn about HTTPS: https://aka.ms/dotnet-https

----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Checking the state of installed workloads...
Installing Microsoft.Android.Sdk.Windows.Msi.x64 ................ Done
Installing Microsoft.Android.Sdk.Windows.Msi.x64 ......... Done
Installing Microsoft.Android.Ref.35.Msi.x64 ..... Done
Installing Microsoft.Android.Runtime.35.android-arm.Msi.x64 ..... Done
Installing Microsoft.Android.Runtime.35.android-arm64.Msi.x64 ..... Done
Installing Microsoft.Android.Runtime.35.android-x86.Msi.x64 ..... Done
Installing Microsoft.Android.Runtime.35.android-x64.Msi.x64 ..... Done
Installing Microsoft.Android.Templates.Msi.x64 .... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-arm64.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-x64.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-x86.Msi.x64 ....... Done
Installing Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 ..... Done
Installing Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 .... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-arm64.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-x64.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-x86.Msi.x64 ....... Done
Installing Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 .... Done
Installing Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 .... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64.Msi.x64 ...... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm.Msi.x64 ...... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64.Msi.x64 ...... Done
Installing Aspire.Hosting.Sdk.Msi.x64 ..... Done
Installing Aspire.ProjectTemplates.Msi.x64 .... Done
Installing Microsoft.iOS.Sdk.net9.0_18.1.Msi.x64 ...... Done
Installing Microsoft.iOS.Sdk.net8.0_18.0.Msi.x64 ...... Done
Installing Microsoft.iOS.Sdk.net9.0_18.0.Msi.x64 ...... Done
Installing Microsoft.iOS.Windows.Sdk.net9.0_18.1.Msi.x64 ....... Done
Installing Microsoft.iOS.Windows.Sdk.net8.0_18.0.Msi.x64 .... Failed
Removing Microsoft.iOS.Windows.Sdk.net9.0_18.1.Msi.x64 ...... Done
Removing Microsoft.iOS.Sdk.net9.0_18.0.Msi.x64 ...... Done
Removing Microsoft.iOS.Sdk.net8.0_18.0.Msi.x64 ....... Done
Removing Microsoft.iOS.Sdk.net9.0_18.1.Msi.x64 ...... Done
Removing Aspire.ProjectTemplates.Msi.x64 .... Done
Removing Aspire.Hosting.Sdk.Msi.x64 ..... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86.Msi.x64 .... Done
Removing Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 .... Done
Removing Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-x86.Msi.x64 ....... Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-x64.Msi.x64 ........ Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-arm64.Msi.x64 ........ Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 ........ Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86.Msi.x64 .... Done
Removing Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 .... Done
Removing Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-x86.Msi.x64 ........ Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-x64.Msi.x64 ........ Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-arm64.Msi.x64 ........ Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 ........ Done
Removing Microsoft.Android.Templates.Msi.x64 .... Done
Removing Microsoft.Android.Runtime.35.android-x64.Msi.x64 .... Done
Removing Microsoft.Android.Runtime.35.android-x86.Msi.x64 .... Done
Removing Microsoft.Android.Runtime.35.android-arm64.Msi.x64 .... Done
Removing Microsoft.Android.Runtime.35.android-arm.Msi.x64 .... Done
Removing Microsoft.Android.Ref.35.Msi.x64 .... Done
Removing Microsoft.Android.Sdk.Windows.Msi.x64 ........ Done
Removing Microsoft.Android.Sdk.Windows.Msi.x64 ........ Done
An issue was encountered verifying workloads. For more information, run "dotnet workload update".
  Determining projects to restore...
C:\Program Files\dotnet\sdk\9.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maui-android [G:\Development\AlzBetter\abmobile-maui\AbMobileMaui.csproj::TargetFramework=net9.0-android]
C:\Program Files\dotnet\sdk\9.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload restore [G:\Development\AlzBetter\abmobile-maui\AbMobileMaui.csproj::TargetFramework=net9.0-android]
PM> dotnet workload update

Updated advertising manifest microsoft.net.workload.emscripten.net8.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.workload.mono.toolchain.current.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.workload.emscripten.net7.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.workload.mono.toolchain.net6.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.workload.emscripten.current.
Updated advertising manifest microsoft.net.workload.emscripten.net6.
Updated advertising manifest microsoft.net.workload.mono.toolchain.net7.
Updated advertising manifest microsoft.net.sdk.aspire.
Updated advertising manifest microsoft.net.workload.mono.toolchain.net8.
Installing Microsoft.Android.Sdk.Windows.Msi.x64 ................ Done
Installing Microsoft.Android.Sdk.Windows.Msi.x64 ......... Done
Installing Microsoft.Android.Ref.35.Msi.x64 ..... Done
Installing Microsoft.Android.Runtime.35.android-arm.Msi.x64 ..... Done
Installing Microsoft.Android.Runtime.35.android-arm64.Msi.x64 ..... Done
Installing Microsoft.Android.Runtime.35.android-x86.Msi.x64 ..... Done
Installing Microsoft.Android.Runtime.35.android-x64.Msi.x64 ..... Done
Installing Microsoft.Android.Templates.Msi.x64 .... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-arm64.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-x64.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-x86.Msi.x64 ....... Done
Installing Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 .... Done
Installing Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 .... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-arm64.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-x64.Msi.x64 ....... Done
Installing Microsoft.NETCore.App.Runtime.Mono.android-x86.Msi.x64 ....... Done
Installing Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 .... Done
Installing Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 .... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm.Msi.x64 ..... Done
Installing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64.Msi.x64 ..... Done
Installing Aspire.Hosting.Sdk.Msi.x64 ..... Done
Installing Aspire.ProjectTemplates.Msi.x64 .... Done
Installing Microsoft.iOS.Sdk.net9.0_18.1.Msi.x64 ...... Done
Installing Microsoft.iOS.Sdk.net8.0_18.0.Msi.x64 ...... Done
Installing Microsoft.iOS.Sdk.net9.0_18.0.Msi.x64 ...... Done
Installing Microsoft.iOS.Windows.Sdk.net9.0_18.1.Msi.x64 ...... Done
Installing Microsoft.iOS.Windows.Sdk.net8.0_18.0.Msi.x64 .... Failed
Workload installation failed. Rolling back installed packs...
Removing Microsoft.iOS.Windows.Sdk.net9.0_18.1.Msi.x64 ...... Done
Removing Microsoft.iOS.Sdk.net9.0_18.0.Msi.x64 ...... Done
Removing Microsoft.iOS.Sdk.net8.0_18.0.Msi.x64 ...... Done
Removing Microsoft.iOS.Sdk.net9.0_18.1.Msi.x64 ...... Done
Removing Aspire.ProjectTemplates.Msi.x64 .... Done
Removing Aspire.Hosting.Sdk.Msi.x64 ..... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86.Msi.x64 .... Done
Removing Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 .... Done
Removing Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-x86.Msi.x64 ........ Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-x64.Msi.x64 ........ Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-arm64.Msi.x64 ....... Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 ........ Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86.Msi.x64 .... Done
Removing Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 .... Done
Removing Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 .... Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-x86.Msi.x64 ....... Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-x64.Msi.x64 ........ Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-arm64.Msi.x64 ....... Done
Removing Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 ....... Done
Removing Microsoft.Android.Templates.Msi.x64 .... Done
Removing Microsoft.Android.Runtime.35.android-x64.Msi.x64 .... Done
Removing Microsoft.Android.Runtime.35.android-x86.Msi.x64 .... Done
Removing Microsoft.Android.Runtime.35.android-arm64.Msi.x64 .... Done
Removing Microsoft.Android.Runtime.35.android-arm.Msi.x64 .... Done
Removing Microsoft.Android.Ref.35.Msi.x64 .... Done
Removing Microsoft.Android.Sdk.Windows.Msi.x64 ........ Done
Removing Microsoft.Android.Sdk.Windows.Msi.x64 ......... Done
dotnet : Workload update failed: Failed to install 625f7e2c81d7c6ecee875c9dd80f6436-x64.msi. Error: 0x00000643, Fatal error during installation.
At line:1 char:1
+ dotnet workload update
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Workload update...g installation.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
PM> 

### Steps to Reproduce

Run dotnet workload install maui, or dotnet restore, or dotnet workload update.

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0 GA

### Affected platforms

Windows

### Did you find any workaround?

no

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
While this has to do with .NET MAUI, this is unfortunately not something we control from this repository. Please report it as per the instructions above. I did do a little searching if this occurred before and I hit this which might be helpful: https://developercommunity.visualstudio.com/t/Empty-MAUI-App-NET-7-does-not-compile/10433335
