### ISSUE TITLE
Unable to load MacCatalyst Arm64 dll

### ISSUE THREAD

**Issue by ashtkumar2023** [dotnet/maui#26529]
### Description

Hello Team,

We are working for a product which obfuscates the dll by feeding the dll as input to our product.

We are unable to load ONLY  the dll that targets net8.0- maccatalyst and arm64.

The other targets like net8.0-ios, net8.0-android and maccatalyst-arm64 loads successfully without any exception.

**https://github.com/ashtkumar2023/MAUI_ARM64**  - this is the repository which has sample MAUI app, Net8 and Net481 console based sample applications

Could you please let us know if there is any corruption of the ARM64 dll when it is built with MAUI and VS2022 due to which we are unable to load it successfully? 

Please let me know if you need any other information.

### Steps to Reproduce

**Steps**:

1) We have a sample MAUI app created in Net8 built in net8.0-maccatalyst configuration [Release mode + AnyCPU] on VS2022.PFA NetMAUIApp.
2) We tried to feed this MAUI application's 'maccatalyst-arm64.dll' to our product in order to load the same and we encountered "System.BadImageException" even before the actual obfuscation process starts to execute. Our product  target  both the frameworks i.e. Net472 and Net8.0
3) In order to confirm the above exception, 
a) we created a simple console application targeting Net472/NET481 framework , tried to load the 'maccatalyst-arm64.dll'  generated  in step 1) and  observed "System.BadImageException" during the load. PFA Net481ConsoleApp.
b) We created another console application targeting Net8.0 ,tried to load the 'maccatalyst-arm64.dll'  and  observed 
"System.IO.FileNotFoundException". PFA Net8ConsoleApp.

The above exceptions in  a) and b) are only observed when we tried to load MAUI sample built for 'maccatalyst-arm64'

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Windows

### Affected platform versions

Net8.0-maccatalyst

### Relevant log output

```shell

```

**Comment by ashtkumar2023** [comment]
The issue described in https://github.com/dotnet/maui/issues/26500   not in bug template format and hence closed this and recreated #25529. Kindly look into this and let us know your thoughts.

**Comment by ashtkumar2023** [comment]
> We've found some similar issues:
> 
> * [MAUI building MAC catalyst Arm64 dll is not getting loaded and throws System.BadImageException #26500](https://github.com/dotnet/maui/issues/26500) , similarity score: 88%
> 
> If any of the above are duplicates, please consider closing this issue out and adding additional context in the original issue.
> 
> > Note: You can give me feedback by 👍 or 👎 this comment.
👎

**Comment by jfversluis** [comment]
As indicated [here](https://github.com/dotnet/maui/issues/26500#issuecomment-2532024996).

> This won't work; the output of a Mac Catalyst project is a self-contained app bundle (a .app directory). It's not possible to load selected pieces of this app bundle from elsewhere.
> 
> Exactly what do you need to do? If you could explain what you want done, we might be able to give alternative solutions to your problem.

What are you trying to do exactly? This seems like something that might not be supported at all.

**Comment by ashtkumar2023** [comment]
> As indicated [here](https://github.com/dotnet/maui/issues/26500#issuecomment-2532024996).
> 
> > This won't work; the output of a Mac Catalyst project is a self-contained app bundle (a .app directory). It's not possible to load selected pieces of this app bundle from elsewhere.
> > Exactly what do you need to do? If you could explain what you want done, we might be able to give alternative solutions to your problem.
> 
> What are you trying to do exactly? This seems like something that might not be supported at all.
> 
> cc: [@rolfbjarne](https://github.com/rolfbjarne)

@jfversluis ,we are just trying to load the arm64dll in our product using reflection assembly "LoadFrom"  to extract the resources in the assembly  [dll ] to encrypt them.

**Comment by rolfbjarne** [comment]
Your test project work for me. I added a script and updated the Program.cs a bit like this: https://gist.github.com/rolfbjarne/d3af4d48f7ba95e6a0bb21d3fbcc536a, and my output is:

```
[...]
+ dotnet run --project Net8ConsoleApplication/Net8ConsoleApplication.csproj -- NetMAUIApp/bin/Release/net8.0-maccatalyst/maccatalyst-arm64/NetMAUIApp.dll
Hello, World!
Testing to load maccatalyst-arm64 dll: NetMAUIApp/bin/Release/net8.0-maccatalyst/maccatalyst-arm64/NetMAUIApp.dll
Success
```

Can you zip up and attach the dll that doesn't work for you?

**Comment by ashtkumar2023** [comment]
> Your test project work for me. I added a script and updated the Program.cs a bit like this: https://gist.github.com/rolfbjarne/d3af4d48f7ba95e6a0bb21d3fbcc536a, and my output is:
> 
> ```
> [...]
> + dotnet run --project Net8ConsoleApplication/Net8ConsoleApplication.csproj -- NetMAUIApp/bin/Release/net8.0-maccatalyst/maccatalyst-arm64/NetMAUIApp.dll
> Hello, World!
> Testing to load maccatalyst-arm64 dll: NetMAUIApp/bin/Release/net8.0-maccatalyst/maccatalyst-arm64/NetMAUIApp.dll
> Success
> ```
> 
> Can you zip up and attach the dll that doesn't work for you?

@rolfbjarne I am building the MAUI app on windows 10 and attaching the dll here.[NetMAUIApp.zip](https://github.com/user-attachments/files/18112267/NetMAUIApp.zip)

**Comment by ashtkumar2023** [comment]
> > Your test project work for me. I added a script and updated the Program.cs a bit like this: https://gist.github.com/rolfbjarne/d3af4d48f7ba95e6a0bb21d3fbcc536a, and my output is:
> > ```
> > [...]
> > + dotnet run --project Net8ConsoleApplication/Net8ConsoleApplication.csproj -- NetMAUIApp/bin/Release/net8.0-maccatalyst/maccatalyst-arm64/NetMAUIApp.dll
> > Hello, World!
> > Testing to load maccatalyst-arm64 dll: NetMAUIApp/bin/Release/net8.0-maccatalyst/maccatalyst-arm64/NetMAUIApp.dll
> > Success
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you zip up and attach the dll that doesn't work for you?
> 
> [@rolfbjarne](https://github.com/rolfbjarne) I am building the MAUI app on windows 10 and attaching the dll here.[NetMAUIApp.zip](https://github.com/user-attachments/files/18112267/NetMAUIApp.zip)

I couldn't attach the entire arm64 dll folder due to space issues.

**Comment by rolfbjarne** [comment]
On window I get this with your assembly:

> System.IO.FileLoadException: 'Could not load file or assembly 'C:\Users\rokvin\Downloads\NetMAUIApp.dll'. The assembly architecture is not compatible with the current process architecture.'

which seems correct.

I believe the fix is to use [MetadataLoadContext](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext) to load the assemblies instead, because then the current executing environment doesn't matter.

Please try this instead, and let us know if it doesn't work, and we'll reopen this issue.

**Comment by ashtkumar2023** [comment]
> On window I get this with your assembly:
> 
> > System.IO.FileLoadException: 'Could not load file or assembly 'C:\Users\rokvin\Downloads\NetMAUIApp.dll'. The assembly architecture is not compatible with the current process architecture.'
> 
> which seems correct.
> 
> I believe the fix is to use [MetadataLoadContext](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext) to load the assemblies instead, because then the current executing environment doesn't matter.
> 
> Please try this instead, and let us know if it doesn't work, and we'll reopen this issue.

@rolfbjarne , With Net472,  it throws  system.BadImageException.

**Comment by rolfbjarne** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/249268?s=64&amp;v=4">@rolfbjarne](https://github.com/rolfbjarne) , With Net472, it throws system.BadImageException.

MetadataLoadContext throws BadImageException?

**Comment by ashtkumar2023** [comment]
> > [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/249268?s=64&amp;v=4">@rolfbjarne](https://github.com/rolfbjarne) , With Net472, it throws system.BadImageException.
> 
> MetadataLoadContext throws BadImageException?

No. 
1) With Net472-  when used with System.Refelction.Assembly,   system.BadImageException.is thrown.
2) With Net8 -    when used with System.Refelction.Assembly, System.IO.FileLoadException is thrown.

I will try 'MetadataLoadContext ' and update the results here.
