### ISSUE TITLE
MAUI App re-installs every time its deployed via VS Code

### ISSUE THREAD

**Issue by vaibhav-sukhdeve** [dotnet/maui#26525]
I am using VS code for development of MAUI app in MAC. Every time I deploy the app to mobile all the data stored in SQLite db and Preferences is getting deleted. And the app launches on the Login screen. The same behaviour is not observed when the same app is deployed using IntelliJ Rider or Visual Studio for Mac. 

#MAUI #VSCode

**Comment by jfversluis** [comment]
This is an issue for the tooling which, unfortunately, should be reported elsewhere, please see the instructions above. Thanks!
