### ISSUE TITLE
After Installing VS 17.12, iOS Debugging Only Works Once

### ISSUE THREAD

**Issue by Felix-Dev** [dotnet/maui#26528]
### Description

Originally posted by Tony Lugg in the Visual Studio developer community here: https://developercommunity.visualstudio.com/t/After-Installing-VS-1712-iOS-Debugging/10791670?sort=newest&topics=visual+studio+2019

`After installing VS 17.12, iOS debugging only works once. The first time it connects and launches the app. If I stop the app and start debugging again, the VS output window is blank and nothing happens. When I click the stop button in VS, I get an hourglass and eventually an error window stating “The debugger was unable to terminate one or more processes”, “N/A Mono: The debugger is still attaching to the process or the process is not currently executing the type of code selected for debugging.”, “The debugger may be unstable now. It is recommended that you save all files and exit”. I’ve restarted VS, restarted Windows, restarted the Mac, but this continues to plague me.`

![Image](https://github.com/user-attachments/assets/25c45c6f-5d5e-45f7-8770-f9847aa2c8e3)

For the MAUI team: I know this probably is the wrong repository to report this error as it looks to be a Visual Studio error. However, as you can see in the VS community issue, it has been reported on 15th, November this year and no response form the VS engineering team so far (I'm not counting the initial feedback Bot reply). Not being able to debug the app twice in a row and instead having to restart Visaul Studio is an absolute blocker for us so we cannot use VS 17.12.X for now and thus are also misisng out on the .NET 9 (MAUI) goodies.

Would it be possible if the MAUI team could internally query the Visual Studio engineering team about progress on this issue? And maybe ask for an increased priroity of solving that issue?

Many thanks in advance.

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

iOS

### Did you find any workaround?

Using Visual Studio 17.10.5.

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
This is the right place to report it and it seems its under investigation and being worked on: https://developercommunity.visualstudio.com/t/After-Installing-VS-1712-iOS-Debugging/10791670?sort=newest&topics=visual+studio+2019

Please add all details there and follow the progress in that ticket. There is nothing we can do on our side. Thanks!

**Comment by Felix-Dev** [comment]
@jfversluis Thanks for reaching out internally at Microsoft. Much appreciated.
