### ISSUE TITLE
Android `Entry` inserts character at the start of text

### ISSUE THREAD

**Issue by rbakhshi** [dotnet/maui#2654]
### Steps to Reproduce

1. Create sample project
2. Insert And `Entry` element on screen
3. Run the project
4. Try typing `abcd`

### Expected Behavior
It must insert `abcd` in the textbox

### Actual Behavior
It inserts `dcba` in textbox and leaves cursor at the start of textbox all the time.
Also sometimes randomly repeats the pressed character
### Basic Information

- Version with issue:
- Last known good version: MAUI preview 7
- IDE: VS2022 Version 17.0.0 Preview 4.1
- Platform Target Frameworks: 
  - Android: 29
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/4858458/134457648-16986b4b-8890-402f-93da-c577fb785673.png)

### Workaround
No workaround found at the moment.

**Comment by rbakhshi** [comment]
Sample code
[MauiTest.zip](https://github.com/dotnet/maui/files/7215109/MauiTest.zip)

**Comment by hartez** [comment]
This is fixed by #2638
