### ISSUE TITLE
Unable to remove new secondary navigation/title bar on Android

### ISSUE THREAD

**Issue by lobbo232** [dotnet/maui#26544]
### Description

In the latest release of MAUI and .NET 9 there is a new title/navigation bar appearing at the top of the page on Android that I can't seem to get rid of.

I'm still able to control the Navigation bar visibility with the normal NavigationPage.HasNavigationBar property and hide and show that as expected but this new "title" bar seems to just be fixed. I can't work out how to remove it.

Where did it come from? What properties control its visibility? Did I accidentally enable it without knowing how?

My app has been migrated from Xamarin, this didn't appear on Xamarin. It also didn't appear in MAUI until I think upgrading the latest MAUI.Controls packages, though rolling back to 9.0.0 doesn't seem to remove it.

![Image](https://github.com/user-attachments/assets/1fd4079e-cc2b-426c-b269-f71265c8e270)

### Link to public reproduction project repository

[inspct app repro.zip](https://github.com/user-attachments/files/18109212/inspct.app.repro.zip)

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

9.0.0 GA

### Affected platforms

Android

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
Without any XAML or a reproduction it will be impossible to tell what might be going on here unfortunately.

**Comment by lobbo232** [comment]
I've added a project that reproduces this issue. I run it in Visual Studio 17.12.3 on Windows.

**Comment by jfversluis** [comment]
If I comment out all the styles in your App.xaml it goes away. So _something_ in there is causing this. Additionally I see a lot of deprecated property (values) in there. So you probably want to look at those and complete your conversion to .NET MAUI first.

I don't think there is a bug here, rather something specific to your project. Thanks!

**Comment by lobbo232** [comment]
Also do you think you could provide any info on what the secondary bar actually is? I can't find anything by searching online because I don't know what to search for.

**Comment by lobbo232** [comment]
@jfversluis I'm not able to replicate your result.
<img width="910" alt="Image" src="https://github.com/user-attachments/assets/cce290bd-4526-472b-97dc-b411fd213325" />

**Comment by lobbo232** [comment]
@jfversluis any chance you could take another look at this? I'd really appreciate the support because as it stands this is still an issue for me even after following your ideas.

**Comment by jenscski** [comment]
You change the theme in MainActivity, search for line `base.SetTheme(Resource.Style.MainTheme)`

Remove this line, and the extra bar will go away

**Comment by lobbo232** [comment]
Thanks @jenscski this helps. Still not sure what is in that style that would make it display though 😄

**Comment by jenscski** [comment]
The Maui.SplashTheme inherits from Maui.MainTheme.NoActionBar, so by using `base.SetTheme(Resource.Style.MainTheme)`, and not base.SetTheme(Resource.Style.MainTheme_NoActionBar)` you reenables the action bar

Se: https://github.com/dotnet/maui/blob/2e4ca4a4d16017fcafbf16d07e6f299456004fff/src/Core/src/Platform/Android/Resources/values/styles.xml#L37
