### ISSUE TITLE
[MAUI]Button 'Add to My Recipes' on the recipe detail page cannot be fully displayed.

### ISSUE THREAD

**Issue by kevinxufei** [dotnet/maui#26562]
### Description

Button 'Add to My Recipes' on the recipe detail page cannot be fully displayed.

**Note:**
1.This problem only occurs when deploying to Maccatalyst.
2.In fact, when we click on the green bar at the bottom, we can successfully add a recipe to 'My Recipes'.

### Steps to Reproduce

1.Deploy to https://github.com/[rachelkang/recipeSearch](https://github.com/rachelkang/recipeSearch) on MacCatalyst.
2.Click Breakfast.
3.Click 'Recipe:Muffin-Pan Breakfast Sliders' and view the page.

**Actual result:**
Button 'Add to My Recipes' on the recipe detail page cannot be fully displayed.
![Image](https://github.com/user-attachments/assets/adfa6221-663d-45ac-943e-d13534de7db7)

**Expected result:**
Button 'Add to My Recipes' on the recipe detail page can be fully displayed.
![Image](https://github.com/user-attachments/assets/585f3b90-e392-41c8-ba50-0a135f21a216)

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

9.0.0 

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-rc.2.24503.2 

### Affected platforms

macOS

**Comment by kevinxufei** [comment]
@jfversluis I'd like to add that this problem no longer exists on the latest 9.0.14 and 9.0.30-ci.main.24612.3.

**Comment by jfversluis** [comment]
Oh great so we fixed it already then? 😄 thanks for letting me know!
