### ISSUE TITLE
DisplayAlert action buttons are backwards on Windows

### ISSUE THREAD

**Issue by jo-ruch** [dotnet/maui#26569]
### Description

I would expect the alert window on Windows to match the example, where the "Accept" button is on the right and the "Cancel" button on the left, but on Windows they are backwards.

![Image](https://github.com/user-attachments/assets/aebfbb98-2f0d-4259-af3c-960e407d9645)

![Image](https://github.com/user-attachments/assets/f70e833a-cd63-4cfc-80d8-6975586514ba)

### Steps to Reproduce

1. Open an alert window on Windows in a ContentPage
2. Observe that the action buttons are backwards

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

net8.0-windows10.0.19041.0

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
According to the docs [here](https://learn.microsoft.com/windows/apps/design/controls/dialogs-and-flyouts/dialogs#general-guidelines).

> The "do it" action button(s) should appear as the leftmost buttons. The safe, nondestructive action should appear as the rightmost button.

So this is indeed how we expect things to show up on Windows!

**Comment by jo-ruch** [comment]
Alright, then that makes sense! Thank your for the quick reply and the clarification!
