### ISSUE TITLE
[Bug] On iOS, SafeArea returns Thickness of zero

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#2657]
Given:
var safeArea = On<Microsoft.Maui.Controls.PlatformConfiguration.iOS>().SafeAreaInsets();

SafeAreaInserts is returning a Thickness of zero on iPhone 11 simulator running iOS 14.5.

### Steps to Reproduce

1. Add the above code to a Maui project
2. Set a breakpoint
3. Run it

### Expected Behavior
Should return correct safe area

### Actual Behavior
Returns an empty safe area

### Basic Information

- Version with issue: Maui Preview 8
- Last known good version: **There are no good versions of .NET MAUI**
- IDE:
- Platform Target Frameworks: 
  - iOS:  
- Affected Devices: iPhone 11 14.5 simulator

### Workaround
None

**Comment by mattscheffer** [comment]
Bug repros in 17.2 Preview 1. Tested with iPhone 13 iOS 15.2. Repro project is here: https://microsoft.sharepoint.com/:u:/r/teams/Mauitriage/Shared%20Documents/General/ReproProjects/2657.zip?csf=1&web=1&e=M8w3am

![image](https://user-images.githubusercontent.com/10537189/154176057-2cc3aec8-968e-467b-a96d-863cf3f2f767.png)

**Comment by KSemenenko** [comment]
I have the same isuse, iPhone 14 Max
Looks like SafeArea is applied, but 
``` cs
On<iOS>().SetUseSafeArea(false);
```
has no effect, 
also 
``` cs
On<iOS>().SetSafeAreaInsets(new Thickness(100, 100, 100, 0));
```
has no effect. 

.NET 7

**Comment by KSemenenko** [comment]
looks like "windows" is now deprecated too.

**Comment by drmaven** [comment]
Adding to the previous comments, there is something wrong with SafeArea on iPhones, since if SafeArea is set to false and the phone is horizontal, the app crashes.

**Comment by KSemenenko** [comment]
and in Maui 

``` cs
static UIWindow? GetKeyWindow()
{
	// if we have scene support, use that
	if (OperatingSystem.IsIOSVersionAtLeast(13) || OperatingSystem.IsMacCatalystVersionAtLeast(13))
	{
		try
		{
			using var scenes = UIApplication.SharedApplication.ConnectedScenes;
			var windowScene = scenes.ToArray<UIWindowScene>().FirstOrDefault();
			return windowScene?.Windows.FirstOrDefault();
		}
		catch (InvalidCastException)
		{
			// HACK: Workaround for https://github.com/xamarin/xamarin-macios/issues/13704
			//       This only throws if the collection is empty.
			return null;
		}
	}

	// use the windows property (up to 13.0)
	return UIApplication.SharedApplication.KeyWindow;
}
```

but for me sometime this windowScene?.Windows still is empty

**Comment by KSemenenko** [comment]
but anyway, if I use this code (copied from MAUI) it works.
but On<iOS>().SafeAreaInsets() is not
<img width="1061" alt="Screenshot 2022-11-24 at 15 39 32" src="https://user-images.githubusercontent.com/4385716/203810327-d5d4566e-aec5-408a-97d5-da6316dceffd.png">

**Comment by bcaceiro** [comment]
Having the same issue, setting SafeArea to false, has no response, specially in landscape mode, which is a blocker to me

**Comment by Hooterr** [comment]
Still not working to this day.

**Comment by JohnHDev** [comment]
@Redth @hartez Any idea when this will get picked up? Ive just tried it again in our .NET MAUI test app with the latest Maui workload, still broken. This bug was reported 16 months ago, during Maui preview, was verified, others are reporting the same issue and yet it still isn't fixed.

Why should we report bugs when they don't get fixed? You are wasting my time, Im not paid to debug .NET MAUI for you, I had enough of doing that for Xamarin Forms.

I can't sell migrating to .NET MAUI from Xamarin Forms when simple bugs like this don't get picked up after reporting them over a year ago.
Our Xamarin Forms code base is full of workarounds for various issues that never got resolved, we don't want to have to do the same for .NET MAUI and we won't start migrating until Maui is much more stable.

**Comment by Hooterr** [comment]
Looking at the sprint board, there are 37 items planned for the current sprint. There are 2,2k issues reported, to fix them would take 2,5 yrs at this pace (assuming no new bugs are reported during that time). I think it's safe to assume that we're on our own...

**Comment by KSemenenko** [comment]
@JohnHDev any way you have to migtate your code to MAUI in some day, because xamarin will be depricated.
so I just copy-past my old code from XF into Maui, all of us know how to fix issues by yourself, so this is not a problem =)
kind of annoyng but not a problem

**Comment by KSemenenko** [comment]
I fill this issue relatod to pages, or time of createing page or so

**Comment by JohnHDev** [comment]
> @JohnHDev any way you have to migtate your code to MAUI in some day, because xamarin will be depricated.
> so I just copy-past my old code from XF into Maui, all of us know how to fix issues by yourself, so this is not a problem =)
> kind of annoyng but not a problem

@KSemenenko 
We don't have to migrate to .NET MAUI at all, there are alternatives and we might have the budget to move to a different framework. I'd rather not, I'd rather see better support than... this.

**Comment by KSemenenko** [comment]
@JohnHDev I have now switched to MAUI and Blazor Mobile, and I really like C#, but at this point I'm not sure it's worth it either =(
I don't know what to say about the native binding of ios and android, the broken tooling and the inability to debug applications on devices that make me struggle with something that is supposed to work, not my job.

**Comment by kramer-e** [comment]
This is basic functionality, why is this issue still open after such a long time?  I agree, we shouldn't be wasting time on these issues after MAUI GA.

As KSemenenko said, calling the same code directly works, so it should be an easy fix:

```var safeAreaInsets = Microsoft.Maui.ApplicationModel.WindowStateManager.Default.GetCurrentUIWindow().SafeAreaInsets;```

**Comment by KSemenenko** [comment]
@kramer-e i think our best case is .net8

**Comment by scriptBoris** [comment]
Вisgusting job

**Comment by QianaJiao** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 2.0. Still repro on .NET 7 Maui Project: 
![image](https://user-images.githubusercontent.com/91244512/231103732-cd282425-9734-419c-9427-d4302b092566.png)

**Comment by kramer-e** [comment]
I use this for a workaround on iOS, because of the issue that `View.IgnoreSafeArea` doesn't work on .NET 7 #12823 

I need to show content behind the statusbar and controls below that in the safe area.  I've set `ios:Page.UseSafeArea="False"` on the page to ignore the SafeArea (content behind status bar) and use the `SafeAreaInsets` to set the margin on controls such as an Entry and Buttons.

**Comment by KSemenenko** [comment]
> Out of curiosity, what are folks using the SafeAreaInsets property for?

To make design good locking on iOS, especially bottom, where you no need bold line with background color.

like map, you want full screen map, or the same ful screen map but with margins only on top

**Comment by Hooterr** [comment]
It's very often that you need some layouts, or images to go beyond the safe area.
I know that as a workaround you can set `BackgroundColor` of a page, which will in turn change the color of those elements, but you can't control the color of bottom and top safe area separately.
To sum up, when you build anything else than hello world you will need this to work.
