### ISSUE TITLE
The keyboard is not opening in the Android 15 simulator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#26587]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-keyboard-is-not-opening-in-the-Andro/10791971)._

---
[severity:I'm unable to use this version]
When clicking an entry field the keyboard is not opening in the Android 15 simulator.
I do not have an Android 15 device so I'm not able to test it on a real phone.
It does work on a Android 14 simulator and phone.

Visual Studio 17.12.0
.NET 9
Microsoft.Maui.Controls Version 9.0.10

Sample repository: https://github.com/geertgeerits/MauiBugKeyboardAndroid15

---
#### Feedback Bot on 11/17/2024, 07:04 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 11/18/2024, 02:29 AM: 

<p>Thank you for taking time to report the issue.<br>
I try to repro you reported issue on my local machine, update VS to 17.12.0, debug your provided sample app to Android 15.0 - API 35, clicking entry field the keyboard is opening, everything works fine.<br>
Could you please restart your android emulator or create a new Android 15.0 - API 35 emulator have a double check<br>
<img src="https://aka.ms/dc/image?name=Bd7e2b515bbf345aaac0edb8999d104da638675227755208056_KeyboardOpen.png&amp;tid=d7e2b515bbf345aaac0edb8999d104da638675227755208056" alt="KeyboardOpen.png"></p>

#### Geert Geerits on 11/18/2024, 03:20 AM: 

<p>Thanks for your answer.<br>
I created a new Android 15.0 - API 35 emulator and the keyboard opens. But when I close the solution and open it again the keyboard doesn’t appear anymore.</p>
<p>Instead of creating a new emulator, a factory reset of the emulator also works. This has to be done every time after opening a new solution.</p>

#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 11/20/2024, 01:30 AM: 

<p>Yes, I can repro you reported the issue, once close solution, reopen solution then debug to Android 15.0 - API 35 emulator once more, the keyboard is not opening anymore.<br>
This feedback is being re-triaged as we are moving it to another team that can better help with the issue. Thanks for your patience.</p>

**Comment by jfversluis** [comment]
This is probably some setting of the emulator or the Android version running running on the emulator. For instance see [this](https://stackoverflow.com/questions/10238769/how-can-i-make-the-android-emulator-show-the-soft-keyboard).

I highly doubt this is something that is in the .NET MAUI SDK. If you open another app on the emulator that is not a .NET MAUI app, does the keyboard show then?

**Comment by kubaflo** [comment]
@jfversluis is 100% right. This seems to be an emulator 'feature' meh


<img width="414" alt="Image" src="https://github.com/user-attachments/assets/4cf3edd5-7845-4776-b0e1-3ccf1b2f04d5" />

**Comment by jfversluis** [comment]
Going to assume that is it, thanks for the help!
