### ISSUE TITLE
After installing VS2022  17.12, build  apparently does nothing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#26585]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/After-installing-VS2022--1712-build--a/10791437)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.11]
I have just installed VS2022 17.12 general  availability.
Any attempt to build one of my solutions has no effect, there are no errors reported or any build messages shown in the output window.

---
#### Pat Moran on 11/15/2024, 03:47 AM: 

<p>The solution contains 4 projects, a class library, a console app,  <a target='_blank' href="http://asp.net">asp.net</a> core web api project and a MAUI app project.<br>
If I remove the MAUI app project, the remaining projects all build normally but if i add the MAUI project nothing builds.</p>

#### Pat Moran on 11/16/2024, 02:15 PM: 

(private comment, text removed)
#### Feedback Bot on 11/17/2024, 06:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by jfversluis** [comment]
Looking at the ticket I'm not sure if you still need help here?

Seems like its building, albeit it being with errors? The errors seem to indicate that the workload and/or NuGet isn't aligned or restored/installed correctly. Do you still need help with anything here?
