### ISSUE TITLE
Can't add windows as targetframework to .net maui project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#26582]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-add-windows-as-targetframework-to-/10804444)._

---
[severity:I'm unable to use this version]
i developed a ios (ipados) app and it is already finished and deployed to the apple app store
now i want to compile the app for windows.

first i tried to simply add windows as the second target framework to the project file.
but sadly this did not work

it seems like that vs has a problem to restore the nuget packages for my project and no matter what i am trying the result is the same:

i can't build my project

can you please help me out?

![image.png](https://aka.ms/dc/image?name=B0acf5e406cfb4999be9bba07609a4980638688090039634137_20241203-085002-image.png&tid=0acf5e406cfb4999be9bba07609a4980638688090039634137)

greetings

---
#### Feedback Bot on 12/2/2024, 11:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### TJ Lambert [MSFT] on 12/4/2024, 10:00 AM: 

<p>Thank you for your feedback. Would you be able to share your .csproj file? Which packages had different values?</p>

#### Matthew Leibowitz [MSFT] on 12/5/2024, 00:07 AM: 

<p>I think this may happen if you have set the ApplicationDisplayVersion using a Condition, which the IDE may have done for you.</p>
<p>Make sure there is just one <code>&lt;ApplicationDisplayVersion&gt;</code> in your csproj and it is not in a property group that has a condition. Typically, you can put the version in the first property group next to the <code>&lt;TargetFramework&gt;</code> property.</p>
<p>But, a copy of your csproj, as TJ says, will help us know for sure.</p>

**Comment by jfversluis** [comment]
As requested, the csproj content would be very useful. Thank you.
