### ISSUE TITLE
[Bug] On iOS: SetUseSafeArea(true) isn't setting a safe area at the top of the screen, and doubles the safe area at the bottom of the screen

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#2658]
Given:
On<Xamarin.Forms.PlatformConfiguration.iOS>().SetUseSafeArea(true);

No safe area appears at the top, and the safe area at the bottom is double in size. (Probably the top safe area size has been added to the bottom, haven't checked).

EDIT:: Also, take a look at what happens when you rotate to landscape, it is completely misaligned.

### Steps to Reproduce

1. Paste the below code in a page constructor:
            On<Xamarin.Forms.PlatformConfiguration.iOS>().SetUseSafeArea(true);
            BackgroundColor = Colors.Red;
            Content = new Frame()
            {
                BackgroundColor = Colors.Blue
            };
2. Run on iPhone 11 simulator

### Expected Behavior
Red safe areas at the top and bottom of the page

### Actual Behavior
Both red safe areas are at the bottom of the page

### Basic Information

- Version with issue: Preview 8

- Platform Target Frameworks: 
- iOS:  

### Workaround
None

**Comment by Redth** [comment]
This should be fixed in a more recent preview release.  Please open a new bug if you are having issues with it on the latest MAUI preview.
