### ISSUE TITLE
In MAUI (.net 8) , when I update the Microsoft.MAUI.Controls and Microsoft.Maui.Controls.Compatibility to version 9.0.10 app fails builds

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#26586]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/In-MAUI-net-8--when-I-update-the-Mic/10798064)._

---
After using nuget package manager to update the Microsoft.MAUI.Controls and Microsoft.Maui.Controls.Compatibility to version 9.0.1, the app fails to build with the errors below
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0246	The type or namespace name 'MauiAppCompatActivity' could not be found (are you missing a using directive or an assembly reference?)	LotteryApp (net8.0-android)	D:\Development\LotteryTest\LotteryApp\Platforms\Android\MainActivity.cs	8	

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0246	The type or namespace name 'MauiApplication' could not be found (are you missing a using directive or an assembly reference?)	LotteryApp (net8.0-android)	D:\Development\LotteryTest\LotteryApp\Platforms\Android\MainApplication.cs	7

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0246	The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?)	LotteryApp (net8.0-ios)	D:\Development\LotteryTest\LotteryApp\Platforms\iOS\AppDelegate.cs	6		
		
The app is currently targeted at .net 8 
Forcing both packages back to 8.0.100, the app builds.

---
#### Feedback Bot on 11/24/2024, 06:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by PureWeen** [comment]
Fixed by https://github.com/dotnet/maui/pull/25993
