### ISSUE TITLE
Error in Microsoft.Maui.Controls version 9.0.0 or later App.xaml.cs (SC0246)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#26584]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-in-MicrosoftMauiControls-version/10801970)._

---
1）Visual Studio 2022　( 17.12.2 )
2) Create a new project
3）. NETMAUI APP
4) Project name: M9.0.10
5）. NET8.0
6) Tools - &gt; NetGet Package Manager - &gt; Manage NetGet packages for your solution
7) Select Microsoft.Maui.Controls.
8)Install version 9.0.10
9）\M9.0.10\Platforms\Windows\App.xaml.cs
　of
　public partial class App : MauiWinUIApplication
　(SC0246)
----
Verify each version as described above
Microsoft.Maui.Controls
8.0.83 OK
8.0.90 OK
8.0.91 OK
8.0.92 OK
8.0.93 OK
8.0.100 OK
9.0.0  NG
9.0.10 NG 

---
#### Feedback Bot on 11/28/2024, 00:52 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### TJ Lambert [MSFT] on 12/4/2024, 09:49 AM: 

<p>Hello, thank you for your feedback. Would you be able to share more information about what the error says?</p>

#### 鈴木　啓一 on 12/4/2024, 06:10 PM: 

(private comment, text removed)

**Comment by PureWeen** [comment]
Fixed by https://github.com/dotnet/maui/pull/25993
