### ISSUE TITLE
New MAUI App Missing Namespaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#26581]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/New-MAUI-App-Missing-Namespaces/10808157)._

---
[severity:It bothers me. A fix would be nice]
Hi I am having problem creating new MAUI App.
I got the workload installed, and .NET 8 SDK Installed.
However, when creating new MAUI app, and on initial building of the solution, I kept getting below error that the namespaces could not be found.
**********************************
The type or namespace name 'MauiAppCompatActivity' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'MauiApplication' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'MauiWinUIApplication' could not be found (are you missing a using directive or an assembly reference?)
**********************************
I have tried upgrading my VS to latest version but still not effect.
Also have updated all the packages to latest version but still the same.
Appreciate any assistance or tips to sort this out.
Thank you in advance.
Jarnen

---
#### Feedback Bot on 12/8/2024, 09:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Kitts Peter Lubega on 12/11/2024, 10:38 AM: 

<p>Am also facing the same challenge here - I installed Visual Studio 2022 yesterday - with the MAUI workload but now these very errors. We need to get this fixed ASAP.</p>

**Comment by PureWeen** [comment]
Fixed by https://github.com/dotnet/maui/issues/26584

You have to be on .NET9 in order to use v9 versions of .NET MAUI
