### ISSUE TITLE
Button always overlaps (infront) of other views

### ISSUE THREAD

**Issue by LeoJHarris** [dotnet/maui#26600]
### Description

We have a situation where the button always overlaps other view items, this started happening on updating MAUI. Previously the red counter acted as a badge and sat over the button but now its in reverse and changing the order of the XAML makes no difference

![Image](https://github.com/user-attachments/assets/b334251d-4bf9-4924-80a0-748f504294e8)

For the corresponding XAML

```xaml
 <HorizontalStackLayout Grid.Column="1">
     <Button
         Command="{Binding SubmitOrderCommand}"
         Style="{StaticResource PositiveSmallButtonStyle}"
         Text="Submit Order">
         <Button.Triggers>
             <DataTrigger
                 Binding="{Binding CartItemCount, Converter={toolkit:CompareConverter ComparisonOperator=Greater, ComparingValue={StaticResource ZeroValue}}}"
                 TargetType="Button"
                 Value="True">
                 <Setter Property="Opacity" Value="1" />
             </DataTrigger>
             <DataTrigger
                 Binding="{Binding CartItemCount, Converter={toolkit:CompareConverter ComparisonOperator=Greater, ComparingValue={StaticResource ZeroValue}}}"
                 TargetType="Button"
                 Value="False">
                 <Setter Property="Opacity" Value="0.5" />
             </DataTrigger>
         </Button.Triggers>
     </Button>
     <Border
         Margin="-8,0,0,0"
         BackgroundColor="{StaticResource BrandRedColor}"
         HeightRequest="16"
         HorizontalOptions="End"
         IsVisible="{Binding CartItemCount, Converter={toolkit:CompareConverter ComparisonOperator=Greater, ComparingValue={StaticResource ZeroValue}}}"
         StrokeShape="RoundRectangle 8"
         StrokeThickness="0"
         VerticalOptions="Start"
         WidthRequest="16">
         <Label
             FontSize="Micro"
             HorizontalTextAlignment="Center"
             Style="{StaticResource LabelSmallBoldStyle}"
             Text="{Binding CartItemCount}"
             TextColor="White"
             VerticalTextAlignment="Center" />
     </Border>
 </HorizontalStackLayout>
```

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.10 SR3

### Affected platforms

Android

### Affected platform versions

Android 34

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
Have you tried the [ZIndex property](https://learn.microsoft.com/dotnet/api/microsoft.maui.controls.visualelement.zindex?view=net-maui-9.0)?

**Comment by LeoJHarris** [comment]
@jfversluis Yes I tried doing that ealier and no difference, the thing is this only started happening when we updated MAUI NuGet, maybe Ill see if I can get a sample repo although it shouldnt be hard to reproduce.

**Comment by ninachen03** [comment]
Could you provide a sample project for us to investigate it further?
Looking forward to your reply!
