### ISSUE TITLE
Shadow property in BoxView in .NET MAUI

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [dotnet/maui#26610]
### Description

In the IDE, the shadow property is being shown in the BoxView class, but actually it does not support the class, so please remove the property or method from the BoxView class, or fix the issue Shadow property in the BoxView class, I am using .NET 9  for MAUI.

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

I was *not* able test on other platforms

### Relevant log output

```shell

```

**Comment by kubaflo** [comment]
HI @SoumyadipYT-OSS, but the shadow works in MAUI for BoxView. Can you attach a repo?
```
<BoxView BackgroundColor="Green" HeightRequest="50" WidthRequest="50">
    <BoxView.Shadow>
        <Shadow Radius="10"
                Offset="5,5"
                Brush="Red" />
    </BoxView.Shadow>
</BoxView>
```

<img width="200" alt="Image" src="https://github.com/user-attachments/assets/bbbedbda-2c97-4366-b6e8-dd9370940cc4" />

**Comment by jfversluis** [comment]
At the same time as @kubaflo I did the same exercise and it works for me. So yes, please post more details of what you mean. Thanks!

![Image](https://github.com/user-attachments/assets/1c37dcdd-108b-4f55-9d34-9c6328e89e65)

**Comment by SoumyadipYT-OSS** [comment]
@kubaflo Thank you for your knowledge, it really helps me a lot! Thank you again @jfversluis Sir as usual, one of my greatest motivation. Issue solved. Thank you again .NET team.

**Comment by SoumyadipYT-OSS** [comment]
@kubaflo @jfversluis I have uploaed a video here, now its fine its working!

https://github.com/user-attachments/assets/a2b1ca20-8eec-4da2-9524-126c4cc5198a

**Comment by kubaflo** [comment]
Nice!
