### ISSUE TITLE
ScrollView Does Not Work When Touching a Custom Grid with PanGestureRecognizer in .NET MAUI (iOS)

### ISSUE THREAD

**Issue by VidyalakshmiMani** [dotnet/maui#26612]
### Description

In a .NET MAUI application, adding a `PanGestureRecognizer` to a `Grid` inside a `ScrollView` prevents the `ScrollView` from functioning properly on iOS. When attempting to scroll the page by touching the `Grid` area, the `ScrollView` does not respond. This issue is specific to iOS, as the scrolling works as expected on other platforms, including Windows, Android, and Mac.

### Steps to Reproduce

1. Open the attached sample project.
2. Run the app on an iOS device or simulator.  
3. Attempt to scroll the page by dragging on the `Grid`.  

[ScrollingCheck.zip](https://github.com/user-attachments/files/18124910/ScrollingCheck.zip)

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

iOS

### Relevant log output

```shell

```

**Comment by kubaflo** [comment]
Hi, @VidyalakshmiMani I'm not sure if it is a correct issue. I think that iOS behaves as expected since you shouldn't scroll and detect a pan gesture simultaneously. And you can test that Android performs scroll indeed, but doesn't recognize the pan gesture (vertical one)

@jfversluis what do you think?

**Comment by jfversluis** [comment]
Yeah mixing controls and gestures is always a bit tricky. And as @kubaflo indicates: maybe the scroll works, but the gesture still doesn't work as it should. Can you confirm this? What is the scenario that you're trying to achieve with all this?
