### ISSUE TITLE
Label Text Binding Renders Extra Degree Symbol (°) in .NET MAUI

### ISSUE THREAD

**Issue by SethupathyD** [dotnet/maui#26630]
### Description

When using a Label in a .NET MAUI application with a binding that includes a degree symbol (°) in the StringFormat, the label renders an extra degree symbol (°°).

![Image](https://github.com/user-attachments/assets/714e4828-dd89-4a2d-938d-ae019dc7402e)

### Steps to Reproduce

1. Define a Label and bind its Text property with a StringFormat containing the degree symbol (°).
2. Use a value converter that appends the degree symbol (°).
3. Observe the output in the UI.

**Expected Behavior:**
The Label should render the text with a single degree symbol (e.g., "$100.00°").

**Actual Behavior:**
The Label renders an extra degree symbol (e.g., "$100.00°°").

### Link to public reproduction project repository

https://github.com/SethupathyD/LabelConverterIssue

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

No

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
I think there is no bug here. You should only call string format in 1 of the places. Either the converter or the binding, not both.

If you just return the plain string from the converter, does is then show correctly?
