### ISSUE TITLE
[Bug] WinUI & Android - Font Icon not appearing

### ISSUE THREAD

**Issue by Only-Xam** [dotnet/maui#2664]
### Description
Font Icon not appearing - On Windows a rectangle appears and on Android build fails.

### Steps to Reproduce
Used code excerpt from https://github.com/dotnet/maui-samples/blob/main/archive/HelloMaui/MainPage.xaml

App.xaml

            <Style x:Key="Glyph" TargetType="Label">
                <Setter Property="TextColor" Value="{DynamicResource GlyphColor}" />
                <Setter Property="FontFamily" Value="IonIcons" />
                <Setter Property="FontSize" Value="15" />
            </Style>

MainPage.xaml

            <HorizontalStackLayout HorizontalOptions="CenterAndExpand">
                <Label Style="{DynamicResource Glyph}" Text="Testing Font Icon"/>
                <Label Style="{DynamicResource Glyph}" Text="&#xf388;" SemanticProperties.Description="Heart" />
            </HorizontalStackLayout>

MauiProgram.cs

            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("ionicons.ttf", "IonIcons");
                });

![image](https://user-images.githubusercontent.com/66119201/134530189-c342f671-238f-415b-9c42-1f5c6f898f22.png)

### Expected Behavior
Font Icon should appear, example shown below:

![image](https://user-images.githubusercontent.com/66119201/134528147-4d883b97-c2c0-4e86-bddf-1f277c60d2f1.png)

### Actual Behavior
Font Icon not appearing - On Windows it appear as rectangle and on Android build simply fails.

Build Error on Android:

Microsoft.Maui.FontManager: Error: Error loading font 'ms-appx:///Assets/ionicons.ttf'.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)

### Basic Information
Microsoft Visual Studio Community 2022 Preview (64-bit) Version 17.0.0 Preview 4.1
net6.0-android
net6.0-windows.10.0.19041

### Screenshots

![image](https://user-images.githubusercontent.com/66119201/134530686-4f25c1ba-c368-41f0-8eec-6b4e86273fe2.png)

Similar to [Bug] Font icon not working on Mac Catalyst #1286

**Comment by PineYi** [comment]
Verified Repro with Windows and Android. Android compiles successfully and has the same problem with Windows. Repro project available here: 
[#2664.zip](https://github.com/dotnet/maui/files/8122428/2664.zip)

**Comment by PineYi** [comment]
Verified Repro with Windows and Android. Android compiles successfully. A rectangle also appears on Android. Repro project available here:
[#2664.zip](https://github.com/dotnet/maui/files/8122490/2664.zip)

**Comment by davidortinau** [comment]
Font icons are working in labels and images here with main (rc2).

<img width="485" alt="image" src="https://user-images.githubusercontent.com/41873/164580363-400e61d3-8750-4835-bbdb-ff952954ea1d.png">

I also tested the sample provided. It was missing the font file, and works after I found and added it.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/41873/164580897-86745b5f-887d-4dc1-928d-9aaba9b3cddc.png">
