### ISSUE TITLE
Firebase analytics symbols not loading in IOS proj

### ISSUE THREAD

**Issue by sasupallisantosh** [dotnet/maui#26660]
Previously, I encountered a build issue with the MAUI iOS application due to the plugin.firebase (https://github.com/dotnet/maui/issues/26455) After resolving the issue, the build was successful. However, when I connected to a Mac and ran the iOS application on a simulator, I received the following error:
`clang++ exited with code 1: Undefined symbols for architecture arm64: "_APMAnalyticsConfiguration", referenced from: +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMAppMeasurementOriginFirebase", referenced from: +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMConsentSettings3P", referenced from: +[FIRAnalytics setConsent:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMFormattedEventName", referenced from: +[FIRAnalytics logEventWithOrigin:name:parameters:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMFormattedUserPropertyName", referenced from: +[FIRAnalytics setUserPropertyString:forName:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMIsAnalyticsCollectionDeactivated", referenced from: +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMIsAnalyticsCollectionEnabled", referenced from: +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMMonitorLogTagOptionKey", referenced from: +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMUserDataFieldEmailAddress", referenced from: +[FIRAnalytics initiateOnDeviceConversionMeasurementWithEmailAddress:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMUserDataFieldHashedEmailAddress", referenced from: +[FIRAnalytics initiateOnDeviceConversionMeasurementWithHashedEmailAddress:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMUserDataFieldHashedPhoneNumber", referenced from: +[FIRAnalytics initiateOnDeviceConversionMeasurementWithHashedPhoneNumber:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o) "_APMUserDataFieldPhoneNumber", referenced from: +[FIRAnalytics initiateOnDeviceConversionMeasurementWithPhoneNumber:] in FirebaseAnalytics[arm64][10](FIRAnalytics.o)` 

Please help me resolve this issue.

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-macios#21817
