### ISSUE TITLE
tutorial(macos): Fresh XCode 16.2 errors out when trying the Run with Debug step

### ISSUE THREAD

**Issue by kamranayub** [dotnet/maui#26686]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: macos

I just installed .NET 9 and XCode 16.2 on my M1 Mac for the first time while following the MacOS MAUI tutorial.

I went through the steps as directed, so far as launching XCode and accepting the agreement (and seeing the splash screen to create a new project).

When I ran `xcode-select --install` after installing, it said the Command-Line Tools were already installed:

> xcode-select: note: Command line tools are already installed. Use "Software Update" in System Settings or the softwareupdate command line interface to install updates

Figuring that was fine, I proceeded to go through the VS Code steps, but when I got to Run and Debug, the build failed saying the tools weren't found:

```sh
  HelloWorldMacOS net9.0-maccatalyst failed with 1 error(s) (0.1s)
    /usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk.net9.0_18.1/18.1.9163/tools/msbuild/iOS/Xamarin.Shared.targets(1931,3): error : 
      Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools'. Please verify that 'xcode-select -p' point
      s to your Xcode installation. For more information see https://aka.ms/macios-missing-xcode.
```

The error message had me [go to this page](https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-9.0&viewFallbackFrom=net-maui-8.0&tabs=visual-studio-code#iosxcode-setup) and **that worked**. Specifically, I had to go into **XCode -> Settings -> Locations** and **select** the XCode 16.2 version, because it said no version was selected. When I did that explicitly, it prompted for a password, then showed the library path to XCode.

![Image](https://github.com/user-attachments/assets/e90d7b96-75e9-49f6-af40-0ab1882095d0)

After that, Run and Debug succeeded.

So it seems like there's now a missing step to explicitly set that CL tools path in XCode _before_ moving onto the VS Code steps.

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-macios#21820

**Comment by rolfbjarne** [comment]
I've opened an internal issue for this here: https://github.com/dotnet/website/issues/7221
