### ISSUE TITLE
MAUI .NET9.0 does not build, getting lots of errors VS17.12.3

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#26688]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-NET90-does-not-build-getting-lot/10812872)._

---
[regression] [worked-in:17.12.3]
i have a MAUI project which was building find before but now (after some recent VS update) the project fails to build.
getting thousands of errors:
![image.png](https://aka.ms/dc/image?name=Bfef0878acd0044a5b468dabc525258da638697003659056067_20241213-152612-image.png&tid=fef0878acd0044a5b468dabc525258da638697003659056067)
![image.png](https://aka.ms/dc/image?name=B5a3198c7790c48c8876005582a89fd27638697004370553180_20241213-152724-image.png&tid=5a3198c7790c48c8876005582a89fd27638697004370553180)

i'm targeting .NET 9.0. running VS latest 17.12.3

---
#### Feedback Bot on 12/15/2024, 08:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by PureWeen** [comment]
Are you seeing the same thing as this issue?
https://github.com/dotnet/maui/issues/25930
