### ISSUE TITLE
Can't opt out of edetoedge opt out.

### ISSUE THREAD

**Issue by asi-evin** [dotnet/maui#26683]
### Description

I see that as of 9.1, I MAUI is now opting out of edge to edge. I see there is a way to opt back in in the pull request, but I can't seem to get it to work.

https://github.com/dotnet/maui/pull/25517

### Steps to Reproduce

1. Create a new MAUI app
2. Update all packages to latest
3. Add the following content/new file to ```Platforms/Android/Resources/Values/Styles```:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<style name="MainThemeEdgeToEdge" parent="Maui.MainTheme.NoActionBar">
		<item name="maui_edgetoedge_optout">false</item>
	</style>
</resources>
```
4. Add the following to function to MainActivity class in ```Platforms/Android/MainActivity.cs```:
```c#
protected override void OnCreate(Bundle? savedInstanceState)
{
    SetTheme(Resource.Style.MainThemeEdgeToEdge);

    base.OnCreate(savedInstanceState);
}
```
5. Run application on Android 35 emulator or device.

### Expected Result
- Status and Navigation Bar are transparent
- Content extends behind Navigation and Status Bar

### Actual Result
- Content contained within confines of System Bars.
![Image](https://github.com/user-attachments/assets/cc07d423-49d8-4d73-b33f-46221231fcfb)

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

35

### Did you find any workaround?

You can do things like set window flags edge to edge, override window insets, but it's a LOT of fighting the opt out and some edge cases in my own app are blocking a release.

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
@Redth ?

**Comment by Redth** [comment]
Correct, currently if you choose to opt back into 'edge to edge' all it means is that you are on your own for managing this.  If you're using Shell, it currently still tries to lay out content around unsafe areas and the effects may be not be as desired.  If you're not using Shell, there's still more work to force our use of AppBarLayout and bottom Tabs to behave properly too.

This is why we have opted out of edge to edge on 35 for now until we can properly make our underlying implementations for both Shell and non-Shell behave as expected in those scenarios.

**Comment by asi-evin** [comment]
Understood
