### ISSUE TITLE
Expose styling for the tooltips

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#26695]
### Description

I would like you expose styling for the tooltips like background , colors.....
Since it produces problems like seen in:
https://learn.microsoft.com/en-us/answers/questions/2131832/tooltip-look-transperant

### Public API Changes

I would like you expose styling for the tooltips like background , colors

### Intended Use-Case

.....

**Comment by MitchBomcanhao** [comment]
as the link you provided mentions, tooltips seem to be styled by the system, not the maui app?

**Comment by danies8** [comment]
I want maui app can override it if i want.

**Comment by jfversluis** [comment]
I don't think the tooltips are typically something that can be heavily stylized, at least not on all platforms. As indicated in the linked article, there is also the factor that at user can influence these settings on their operating system, which is apparently what is happening here.

On Windows the `TooltipService` seems to be static, so with some custom mappers you might actually be able to already influence some of the behavior today.

Additionally, this feature request lacks any detail on what an implementation should look like and thus is not really actionable at this time. And looking at the other priorities we have for the foreseeable future, I don't think this will make it to the top of the list anytime soon. As such, I'm closing this for now.
