### ISSUE TITLE
Image Picker stuck on iOS with .NET 8

### ISSUE THREAD

**Issue by giacomo-cc** [dotnet/maui#26721]
### Description

I have an application created one year ago on the MAUI early days. Recently we had to integrate images for the first time, so I started using the `MediaPicker.PickPhotoAsync();` method provided by the framework. Unfortunately we faced an odd bug with the iOS image picker, once the system image picker is shown it freezes and is impossible to click anything (both images or cancel buttons). I tried with a brand new application with the same iOS simulator and same framework and everything works fine.

I've noticed a difference between the two systems: 

This is the screenshot of my application where the problem occurs
![Image](https://github.com/user-attachments/assets/46200dee-d680-4be7-a2f3-1b3429107890)

This is the screenshot of the test application where everything works as expected
![Image](https://github.com/user-attachments/assets/fafd6574-1f82-4a0c-a49b-da5511c51a90)

As you can see it seems that on the first application the image picker is in some ways zoomed in (the time overlap the top left cancel button), maybe this is related to the bug.

Anybody knows how to fix?

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18.1

### Relevant log output

```shell

```

**Comment by giacomo-cc** [comment]
This is similar to #25879 but on that one the issue author resolved upgrading to .NET 9 that unfortunately is something we cannot do at the moment.

**Comment by giacomo-cc** [comment]
I just tried the buggy application on a real device (iphone 14 pro max) and seems working fine, so its probably something related only to the simulator, but I cannot understand why on a brand new application everything works fine. Btw seems something related also on other framework, like flutter: https://github.com/flutter/flutter/issues/155401 and react native https://github.com/react-native-image-picker/react-native-image-picker/issues/2312

**Comment by PureWeen** [comment]
> This is similar to [#25879](https://github.com/dotnet/maui/issues/25879) but on that one the issue author resolved upgrading to .NET 9 that unfortunately is something we cannot do at the moment.

Unfortunately, at this point the bar is really high for fixing anything on .NET8

.NET 9 GA and .NET 8 are very similar so you shouldn't hit many issues moving up to .NET 9

**Comment by iadwait** [comment]
For me it's working fine on Real Device but not on Simulator.
