### ISSUE TITLE
Unable to update MainPage on iOS using CloseWindow and OpenWindow

### ISSUE THREAD

**Issue by Rajkumarcs41** [dotnet/maui#26745]
### Description

The following code works as expected on Android, but on iOS, it stays on the same page and does not navigate to the next page as intended:
`Application.Current.CloseWindow(Application.Current.Windows[0]);
Application.Current.OpenWindow(new Window(new NavigationPage(new SecondPage())));
`

### Steps to Reproduce

1. Create a new .NET MAUI application.
2. Add a button or event that executes the above code.
3. Run the application on an Android device or emulator:
    3.a) Observe that the window closes and reopens with the SecondPage.
4.Run the application on an iOS device or simulator:
     4.a)The application stays on the same page without navigating to SecondPage.

### Link to public reproduction project repository

https://github.com/Rajkumarcs41/MAUIWindowIssue_iOS 

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Workaround using MainPage Property
`// Set MainPage to a new NavigationPage containing SecondPage
Application.Current.MainPage = new NavigationPage(new SecondPage());
`

### Relevant log output

```shell

```

**Comment by PureWeen** [comment]
Page not found on repro

Have you configured everything on iOS for multi window?
https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/windows?view=net-maui-9.0#ipados-and-macos-configuration

**Comment by Rajkumarcs41** [comment]
@PureWeen 

I have updated the repository with a sample and made it public for your reference.

Currently, we are not working with a multi-window application; our focus is on a single-window app. Recently, we migrated from .NET 8 to .NET 9. After the migration, we encountered a warning indicating that Application.MainPage is deprecated. To address this warning, we attempted to implement the new window-based approach as recommended. However, this resulted in the reported issue.

Note: Our application requires dynamic updates to the main page at various points. Previously, we used Application.Current.MainPage to achieve this functionality. With its deprecation, we are seeking a solution in the window-based approach that supports this requirement.

Let me know if further clarification or updates are needed.

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.13.0 Preview 2.1 (9.0.21 & 9.0.0). Can repro on iOS platform.

**Comment by PureWeen** [comment]
> [@PureWeen](https://github.com/PureWeen)
> 
> I have updated the repository with a sample and made it public for your reference.
> 
> Currently, we are not working with a multi-window application; our focus is on a single-window app. Recently, we migrated from .NET 8 to .NET 9. After the migration, we encountered a warning indicating that Application.MainPage is deprecated. To address this warning, we attempted to implement the new window-based approach as recommended. However, this resulted in the reported issue.
> 
> Note: Our application requires dynamic updates to the main page at various points. Previously, we used Application.Current.MainPage to achieve this functionality. With its deprecation, we are seeking a solution in the window-based approach that supports this requirement.
> 
> Let me know if further clarification or updates are needed.

You can still achieve the same thing by accessing the `MainPage` via the windows property on the application

Application.Current.Windows[0].Page = <new Page>

**Comment by Rajkumarcs41** [comment]
> > [@PureWeen](https://github.com/PureWeen)
> > I have updated the repository with a sample and made it public for your reference.
> > Currently, we are not working with a multi-window application; our focus is on a single-window app. Recently, we migrated from .NET 8 to .NET 9. After the migration, we encountered a warning indicating that Application.MainPage is deprecated. To address this warning, we attempted to implement the new window-based approach as recommended. However, this resulted in the reported issue.
> > Note: Our application requires dynamic updates to the main page at various points. Previously, we used Application.Current.MainPage to achieve this functionality. With its deprecation, we are seeking a solution in the window-based approach that supports this requirement.
> > Let me know if further clarification or updates are needed.
> 
> You can still achieve the same thing by accessing the `MainPage` via the windows property on the application
> 
> Application.Current.Windows[0].Page = `new Page`

@PureWeen  I truly appreciate the prompt response. The solution works perfectly on my end—thank you!
