### ISSUE TITLE
[Bug] [Mac Catalyst] Device.RuntimePlatform is set to Device.iOS

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2675]
<img width="671" alt="スクリーンショット 2021-09-23 午後4 34 10" src="https://user-images.githubusercontent.com/898335/134580071-85e50cd0-b745-4fe6-b01a-5ca37921a4f1.png">

### Description

If you use `Microsoft.Maui.Controls.Device.RuntimePlatform` to detect which platform your app is being run on, it will be iOS even though this is a Mac Catalyst app.

**Comment by jamesmontemagno** [comment]
We had some conversation about this. previously -> https://github.com/xamarin/Essentials/issues/1700

There are 2 situations... 1.) mac catalyst 2.) iOS app on a mac

**Comment by jfversluis** [comment]
Related to #2423

**Comment by v-longmin** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by jfversluis** [comment]
This one is fixed by #3763
