### ISSUE TITLE
[Bug] Maui Blazor InputFile

### ISSUE THREAD

**Issue by ElliottBrand** [dotnet/maui#2678]
The Blazor InputFile component doesn't seem to work in a Maui Blazor app (Android). I receive no errors, it just doesn't do anything when clicked and never hits the breakpoint within the method called by OnChange.

```<InputFile OnChange="ImageFileChange" accept="image/jpeg, image/png, image/gif, image/webp" multiple />```

**Comment by jamesmontemagno** [comment]
I tried this on Windows and it did bring up the file picker which makes sense.

On Android you will need to verify permissions and prompt them with .NET MAUI Essentials, which is built in. I tried this out and got the proper permissions, but still nothing. Could be an Android/iOS thing, but probably you would want to use the F[ilePicker API](https://docs.microsoft.com/en-us/xamarin/essentials/file-picker?context=xamarin%2Fandroid&tabs=android):

MainActivity.cs
```csharp
        protected override void OnCreate(Bundle savedInstanceState)
        {
            //...
            base.OnCreate(savedInstanceState);
            Platform.Init(this, savedInstanceState); // add this line to your code, it may also be called: bundle
                                                     //...
        }
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults)
        {
            Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
```

```html
@using Microsoft.Maui.Essentials
<button class="btn btn-primary" @onclick="PickFile">Pick File</button> 
```
```csharp
private async void PickFile()
	{
		var file = await FilePicker.PickAsync();
	}
```

@danroth27 & @Eilon thoughts?

**Comment by Eilon** [comment]
Looks like we have to do work on at least some platforms to make this work: https://stackoverflow.com/questions/28136144/android-webview-input-type-file

**Comment by jamesmontemagno** [comment]
For iOS this works it also gives the option to take a photo so you would have to add these permissions:

```
<key>NSCameraUsageDescription</key>
<string>This app needs access to the camera to take photos.</string>
<key>NSMicrophoneUsageDescription</key>
<string>This app needs access to microphone for taking videos.</string>
<key>NSPhotoLibraryAddUsageDescription</key>
<string>This app needs access to the photo gallery for picking photos and videos.</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>This app needs access to photos gallery for picking photos and videos.</string>
```
And probably actually want to check permissions with .NET MAUI Essentials

**Comment by ElliottBrand** [comment]
As a workaround, I ended up implementing what James recommended and used the Maui Essentials File Picker.

- I used a cascading parameter to pass a boolean from the Maui project to set a IsNativeApp value within the blazor components project (a class library that contains the blazor components).
- If IsNativeApp is true, I know to display a button instead of the FileInput component.
- If the button is clicked, I fire an event through an App State class to notify File Picker (in the Maui project) to pick files. Once the file is picked, I add the file to a list, which is passed down through a cascading parameter into the blazor project. _(This way I don't have to add Maui Essentials to the blazor components project, since the Web Assembly site won't need it)_.
- Then I fire another event in the App State to notify the blazor component that the file is picked and the blazor component can retrieve the file from the cascading parameter.

**Comment by dannyBies** [comment]
> As a workaround, I ended up implementing what James recommended and used the Maui Essentials File Picker.
> 
> * I used a cascading parameter to pass a boolean from the Maui project to set a IsNativeApp value within the blazor components project (a class library that contains the blazor components).
> * If IsNativeApp is true, I know to display a button instead of the FileInput component.
> * If the button is clicked, I fire an event through an App State class to notify File Picker (in the Maui project) to pick files. Once the file is picked, I add the file to a list, which is passed down through a cascading parameter into the blazor project. _(This way I don't have to add Maui Essentials to the blazor components project, since the Web Assembly site won't need it)_.
> * Then I fire another event in the App State to notify the blazor component that the file is picked and the blazor component can retrieve the file from the cascading parameter.

Hi Elliott,

I just came accross your comment. I was wondering if you have a small sample project with these steps implemented as I'm quite interested in your approach!

**Comment by ElliottBrand** [comment]
I've put together a very general implementation of what I did and uploaded the project to [https://github.com/ElliottBrand/MauiBlazorFileTransporter](https://github.com/ElliottBrand/MauiBlazorFileTransporter)

**Comment by dannyBies** [comment]
Amazing, thanks a lot!

**Comment by jamesmontemagno** [comment]
Main concern -> https://github.com/dotnet/maui/pull/4928#issuecomment-1051405185

**Comment by Eilon** [comment]
Re-opening because I guess this fix is _essentially_ incomplete.

**Comment by Eilon** [comment]
From @jamesmontemagno comment in the PR:

> One thing to be aware of is if you target Android 30+ which is basically required READ_EXTERNAL_STORAGE is super not really allowed anymore :(
> 
> See: [xamarin/Essentials#1961](https://github.com/xamarin/Essentials/issues/1961)

**Comment by TanayParikh** [comment]
> One thing to be aware of is if you target Android 30+ which is basically required READ_EXTERNAL_STORAGE is super not really allowed anymore :(
> 
> See: [xamarin/Essentials#1961](https://github.com/xamarin/Essentials/issues/1961)

Thanks for pointing that out @jamesmontemagno. Given this PR just uses the underlying Maui Essentials File Picker, I believe the resolution of https://github.com/xamarin/Essentials/issues/1961 will also resolve this issue automatically (assuming no API changes). Let's keep this open for tracking, but I don't imagine it'll require any additional work on the Blazor WebView end.

**Comment by TanayParikh** [comment]
@jamesmontemagno once your [maui port](https://github.com/xamarin/Essentials/pull/1968#issuecomment-1040742293) goes through, I'll double check this version works fine without any additional perms on Android 30+. 

Just to confirm, we'll still need to provide guidance to request for perms for Android < 30, correct?

**Comment by VincentBu** [comment]
feel free to remove the `s/verified` tag if it's not proper here.

**Comment by TanayParikh** [comment]
Blocked on https://github.com/xamarin/Essentials/pull/1968.

**Comment by jfversluis** [comment]
The Essentials change @TanayParikh mentions has been merged last month with [this PR](https://github.com/dotnet/maui/pull/4697). Can we confirm if this is still an issue?

**Comment by TanayParikh** [comment]
Thanks @jfversluis. I've verified this is working as expected **without** the storage permission, thus we should be good to go for Android 30+. 🎉 

Optional PR: https://github.com/dotnet/maui/pull/5853/files
