### ISSUE TITLE
App Store, consume REST-based web service: Exception message 'Typeinitialization_Type, a'

### ISSUE THREAD

**Issue by bluebeenet** [dotnet/maui#26793]
### Description

I already have several versions of my app in .net 8 approved by Apple but when updating it to .net 9 it was rejected for failing on iPad Air 5th generation, I managed to get it approved with 'UseInterpreter'.

When launching this version in release from VS paired with my mac to my iPhone device everything works fine. But when launching it from the App Store, when consuming a REST-based web service an Exception occurs with the message "Typeinitialization_Type, a".

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS

### Affected platform versions

iOS Version 18.2, iPadOS Version 18.1.1 

### Relevant log output

```shell

```

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-macios#21852
