### ISSUE TITLE
[Bug] Breakpoints not working

### ISSUE THREAD

**Issue by cdavernas** [dotnet/maui#2682]
### Description

Breakpoints on Android are not working from time to time

### Steps to Reproduce

1. Set a breakpoint in your code
2. Debug the app on Android

### Expected Behavior

Breakpoint is hit, Visual Studio displays it

### Actual Behavior

Visual Studio shows a message saying that it fails showing breakpoints in remote debug

**Comment by drasticactions** [comment]
This is an issue with the .NET 6 Android Tooling in Visual Studio and I think it is unrelated to MAUI, as you can replicate it with a straight Android app running on .NET 6 through Visual Studio.

I would file this through [Visual Studio Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019#:~:text=%20Visual%20Studio%20feedback%20options%20%201%20Report,tool%20at%20the%20top-right%20of%20any...%20More%20).

**Comment by cdavernas** [comment]
@drasticactions Allright, thanks, will do!

**Comment by cdavernas** [comment]
For those encountering the same problem, I'm not sure why, but restarting the VS and/or the emulator and/or the OS seems to fix it.
