### ISSUE TITLE
[Bug] Backward and laggy typing on Android

### ISSUE THREAD

**Issue by cdavernas** [dotnet/maui#2683]
### Description

Typping in an Entry control is not properly working.

### Steps to Reproduce

1. Debug on Android Emulator
2. Type some text in an Entry

### Expected Behavior

The text should be displayed as expected.

### Actual Behavior

Huge lags when typping. Writting 'Hello', for example, actually displays (at best) 'olleh'.  Characters might be missing due to aweful lag. To erase the text, I must go to its end, then use backspace, and repeat for every single character.

### Basic Information

Typping anywhere but on the debugged app works perfectly: no lag, no backward typping, no missing characters.

**Comment by drasticactions** [comment]
I think this is a duplication of https://github.com/dotnet/maui/issues/2654

**Comment by cdavernas** [comment]
@drasticactions It seems so indeed. Missed that one, sorry.

**Comment by hartez** [comment]
Fixed by #2638
