### ISSUE TITLE
Maui Check workload update failed

### ISSUE THREAD

**Issue by Intelli-Soft** [dotnet/maui#2684]
Hey

I have updated the Maui Check to version: v0.8.6.0

but the maui check ends up with the following:

      _   _   _____   _____     __  __      _      _   _   ___                                                          
     | \ | | | ____| |_   _|   |  \/  |    / \    | | | | |_ _|                                                         
     |  \| | |  _|     | |     | |\/| |   / _ \   | | | |  | |                                                          
  _  | |\  | | |___    | |     | |  | |  / ___ \  | |_| |  | |                                                          
 (_) |_| \_| |_____|   |_|     |_|  |_| /_/   \_\  \___/  |___|                                                         
                                                                                                                        
Ï .NET MAUI Check v0.8.6.0 Ï
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
This tool will attempt to evaluate your .NET MAUI development environment.
If problems are detected, this tool may offer the option to try and fix them for you, or suggest a way to fix them 
yourself.

Thanks for choosing .NET MAUI!
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
¯ Synchronizing configuration... ok
¯ Scheduling appointments... ok

> OpenJDK 11.0 Checkup...
  - 11.0.12 (C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\..)
  - 1.8.0-25 (C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25)
  - 17 (C:\Program Files\Common Files\Oracle\Java)

> Visual Studio 17.0.0-pre.4.0 Checkup...
  - 17.0.0-pre.4.1 - C:\Program Files\Microsoft Visual Studio\2022\Preview
  - 16.11.3

> Android SDK Checkup...
  - emulator (30.8.4)
  - build-tools;31.0.0 (31.0.0)
  - platforms;android-31 (1)
  - system-images;android-31;google_apis;x86_64 (8)
  - platform-tools (31.0.3)
  - cmdline-tools;3.0 (3.0)

> Android Emulator Checkup...
  - Emulator: android_tv_1080p_pie_9_0_-_api_28 found.

> .NET SDK Checkup...
  - 3.1.413 - C:\Program Files\dotnet\sdk\3.1.413
  - 5.0.100-preview.5.20279.10 - C:\Program Files\dotnet\sdk\5.0.100-preview.5.20279.10
  - 5.0.202 - C:\Program Files\dotnet\sdk\5.0.202
  - 5.0.207 - C:\Program Files\dotnet\sdk\5.0.207
  - 5.0.303 - C:\Program Files\dotnet\sdk\5.0.303
  - 5.0.401 - C:\Program Files\dotnet\sdk\5.0.401
  - 6.0.100-rc.1.21463.6 - C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6

> .NET SDK - Workload Deduplication Checkup...

> Edge WebView2 Checkup...
  - Found Edge WebView2 version 93.0.961.52

> .NET SDK - Workloads (6.0.100-rc.1.21458.32) Checkup...
  - android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 31.0.100-rc.1.12) installed.
  - ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-rc.1.1534) installed.
  - maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-rc.1.1534) installed.
  ž tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-rc.1.1534) not installed.
  ž macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-rc.1.1534) not installed.
  - maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-rc.1.1608) installed.
  - wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-rc.1.21451.13) installed.
  - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-rc.1.21430.3) installed.

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Ï Recommendation: Install or Update SDK Workloads
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

! Attempt to fix? [y/n] (y): y
¯ Attempting to fix: .NET SDK - Workloads (6.0.100-rc.1.21458.32)
SHELL: C:\Program Files\dotnet\dotnet.exe workload update --no-cache --disable-parallel --from-rollback-file "C:\Users\hbaci\AppData\Local\Temp\maui-check-14367e0c\workload.json" --source "https://api.nuget.org/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.1.21458.32-shipping/nuget/v3/index.json"

Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Workload update failed: Invalid rollback definition. The manifest IDs in rollback definition C:\Users\hbaci\AppData\Local\Temp\maui-check-14367e0c\workload.json do not match installed manifest IDs.
Description:
  Hiermit aktualisieren Sie ein globales Workload.

Usage:
  dotnet [options] workload update

Options:
  --configfile <FILE>                      Die zu verwendende NuGet-Konfigurationsdatei.
  -s, --source <SOURCE>                    The NuGet package source to use during the restore. To specify multiple sources, repeat the option.
  --sdk-version <VERSION>                  Die Version des zu installierenden Toolpakets.
  --from-cache <from-cache>                Complete the operation from cache (offline).
  --include-previews                       Allow prerelease workload manifests.
  --download-to-cache <download-to-cache>  Download packages needed to install a workload to a folder that can be used for offline installation.
  --temp-dir <temp-dir>                    Specify a temporary directory for this command to download and extract NuGet packages (must be secure).
  --from-previous-sdk                      Include workloads installed with earlier SDK versions in update.
  --advertising-manifests-only             Only update advertising manifests.
  --disable-parallel                       Hiermit wird die parallele Wiederherstellung mehrerer Projekte verhindert.
  --ignore-failed-sources                  Paketquellfehler als Warnungen behandeln.
  --no-cache                               Pakete und HTTP-Anforderungen nicht zwischenspeichern.
  --interactive                            Hiermit wird zugelassen, dass der Befehl anh„lt und auf eine Benutzereingabe oder Aktion wartet (beispielsweise auf den Abschluss der Authentifizierung).
  -v, --verbosity <LEVEL>                  Hiermit wird der Ausfhrlichkeitsgrad von MSBuild festgelegt. Zul„ssige Werte sind "q[uiet]", "m[inimal]", "n[ormal]", "d[etailed]" und "diag[nostic]".
  -?, -h, --help                           Hiermit wird die Hilfe zur Befehlszeile angezeigt.

Fix failed - Workload Update failed: `dotnet workload update --no-cache --disable-parallel --from-rollback-file 
"C:\Users\hbaci\AppData\Local\Temp\maui-check-14367e0c\workload.json" --source "https://api.nuget.org/v3/index.json" 
--source "https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.1.21458.32-shipping/nuget/v3/index.json"`
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

! There were one or more problems detected.
Please review the errors and correct them and run maui-check again.

Press enter to exit...

**Comment by KrishMishra007** [comment]
I have uninstall previous version completely with delete folder .net in  c drive and reinstall new version. it work perfect for me

**Comment by nmase88** [comment]
I did the same as KrishMishra007 and it resolved it for me as well

**Comment by acaliaro** [comment]
> I have uninstall previous version completely with delete folder .net in c drive and reinstall new version. it work perfect for me

Can you explain better what have you done?

**Comment by KrishMishra007** [comment]
> > I have uninstall previous version completely with delete folder .net in c drive and reinstall new version. it work perfect for me
> 
> Can you explain better what have you done?

I followed this steps.
1. Uninstall Visual studio.
2. Remove all app related Visual studio > Control Panel > Programs> Uninstall a Program
3. Delete folder .net and related visual studio from C drive> Program Files(both folder 32 and 64 bit)
4. After Fresh install the VS 20222 it work with latest version perfectly.

**Comment by jsuarezruiz** [comment]
You can remove old workloads versions using this script https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1

Then, install agian the workloads manually:

`dotnet workload install maui`

or

`dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.10.json`

**Comment by jsuarezruiz** [comment]
If still have issues updating the workloads let me know to reopen the issue or open a new one.
