### ISSUE TITLE
Confusing MAUI Build Warning

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#26855]
### Description

Building my app for Android generates:
```
XA0141: NuGet package '<unknown>' version '<unknown>' contains a shared library 'libimage_processing_util_jni.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
```

### Steps to Reproduce

1. Clone the repository
2. Switch to the 'alpha' branch
3. Build the 'DivisiBill' project for Android 

### Link to public reproduction project repository

https://github.com/david-maw/DivisiBill.git

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

N/A, it's a build time problem

### Did you find any workaround?

No, though I'm sure I could figure out by a process of elimination which package is triggering this. Be a lot easier if the first <Unknown> was a name though! 

### Relevant log output

```shell

```

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.13.0 Preview 2.1 (9.0.21). Cannot repro on android platform. it build no error no warning on my side

![Image](https://github.com/user-attachments/assets/8b9ab671-4a1b-4901-b4e5-109c556bd4b8)

**Comment by david-maw** [comment]
Yep, that fixed it, thanks.
