### ISSUE TITLE
Make Item Templates visible in Visual Studio

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#2686]
We have item templates, and they appear in the CLI but not in the IDE.

Let's make them available here.

@BretJohnson - can you help us understand how to do this?

**Comment by BretJohnson** [comment]
FYI - Sayed's team as adding this supported, targeted for 17.1 Some discussion here: 

https://teams.microsoft.com/l/message/19:989ffa44998147aca4ceaf7482967668@thread.skype/1632858228256?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0056f60b-301f-43ac-bbcf-f356d3c42c92&parentMessageId=1632858228256&teamName=VS%20Client%20Experiences&channelName=MAUI%20%F0%9F%8C%BA&createdTime=1632858228256
