### ISSUE TITLE
[Bug] Border with Ellipse shape isn't sized correctly

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2691]
### Description

Ellipse is way off

![image](https://user-images.githubusercontent.com/41873/134745282-c9b6769a-03fa-453d-be79-83dc8bcb4021.png)

Rectangle sizes ok

![image](https://user-images.githubusercontent.com/41873/134745300-4aa47a42-a276-41de-9a5a-f91fb47b58f0.png)

### Basic Information

- Version with issue: pre9

**Comment by YuqinSong** [comment]
Not reproducible. The size of the ellipse is different with you described.
