### ISSUE TITLE
[Bug] Border sizes to container instead of wrapping content

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2692]
### Description

My expectation for a border is that I'm putting a stroke around the content that is wrapped, however the stroke is drawn to fill the container by default. I know I can set the layout options to start|center|end to overcome this, but it seems like a Border ought to default to wrapping content and not filling the container. 

![image](https://user-images.githubusercontent.com/41873/134745580-9a7954e3-7ba3-429d-95c6-c2daa6618496.png)

```
<Border Stroke="Red"
                        StrokeThickness="3"
                        Padding="12,8"
                        >
                    <Border.StrokeShape>
                        <RoundRectangle CornerRadius="12"/>
                    </Border.StrokeShape>
                    <Label Text="Images" TextColor="#999999" 
                           FontSize="42"
                           Background="Green"
                           HorizontalOptions="Start"
                           StyleClass="Headline"/>
                </Border>
```

### Basic Information

- Version with issue: pre9

**Comment by XamlTest** [comment]
Verified this issue on Visual Studio Enterprise 17.6.0 Preview 2.0. Repro on Windows and Android emulator (13.0-API 33) with below Project:
[2692.zip](https://github.com/dotnet/maui/files/11188465/2692.zip)

![image](https://user-images.githubusercontent.com/97647558/230847431-f6a1c33d-4b1a-4d50-a400-1fe5fc4692e3.png)

**Comment by hartez** [comment]
This is how the Border control on WinUI/UWP works. If you want it to compress to the size of the content, you just need to set the layout options (`HorizontalOptions`/`VerticalOptions`) to match the content's options.
