### ISSUE TITLE
[Bug] Border with RoundRectangle doesn't use CornerRadius or Clip content

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2694]
### Description

I set the radius on the RoundRectangle and:

1. The size isn't respected
2. the content isn't clipped

![image](https://user-images.githubusercontent.com/41873/134746843-078ff6d8-39e2-4e87-af83-cbdc58c2d1c6.png)

```
<Border Stroke="Red"
                        StrokeThickness="3"
                        HorizontalOptions="Start"
                        >
                    <Border.StrokeShape>
                        <RoundRectangle 
                            CornerRadius="20"/>
                    </Border.StrokeShape>
                    <Label Text="Images" TextColor="#999999" 
                           FontSize="42"
                           Background="Green"
                           Padding="12,8"
                           HorizontalOptions="Start"
                           StyleClass="Headline"/>
                </Border>
```

### Basic Information

- Version with issue: pre9

**Comment by YuqinSong** [comment]
Verified repro with Andriod 11. Repro project available: 
[#2694.zip](https://github.com/dotnet/maui/files/8122255/2694.zip)

**Comment by Redth** [comment]
![image](https://user-images.githubusercontent.com/271950/164544838-653d4a6e-9931-4f4d-94c6-b70bb960b35c.png)

Looks fixed here
