### ISSUE TITLE
[Bug] MAUI Template is missing VS 2022 Prew 4.1

### ISSUE THREAD

**Issue by Midnayt** [dotnet/maui#2697]
### Steps to Reproduce

1. Download VS Installer
2. Install all components to run MAUI (from oficcial docs)
3. Create a new project -> MAUI and Blazor - not present

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2022 Version 17.0.0 Preview 4.1

### Screenshots

![SharedScreenshot](https://user-images.githubusercontent.com/31686881/134779631-65694bde-29f4-45a5-b720-3f2ad09833e9.jpg)

### Workaround
install template mannually

dotnet new --install Microsoft.Maui.Templates::6.0.101-preview.9.1756

**Comment by jfversluis** [comment]
This has been reported a couple of times and I think has been fixed in the meanwhile with newer previews. Let us know is you're still having trouble!
