### ISSUE TITLE
[Bug] MAUI wan't run

### ISSUE THREAD

**Issue by Midnayt** [dotnet/maui#2698]
### Steps to Reproduce

1. Create new MAUI project
2. Run
3. 

### Basic Information

- IDE: VS 2022 Version 17.0.0 Preview 4.1

### Screenshots

![SharedScreenshot1](https://user-images.githubusercontent.com/31686881/134779987-10a2da3a-d6b3-49f0-a501-ef3372423f88.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/31686881/134779989-e9ba7fef-d070-489e-bd2e-d5d5fd6adef2.jpg)
![SharedScreenshot3](https://user-images.githubusercontent.com/31686881/134779990-fd43d60d-2017-4377-8f3f-7158b6871b22.jpg)

**Comment by ElliottBrand** [comment]
I suspect you're missing some workloads. I recommend checking out the Maui Check tool at https://github.com/Redth/dotnet-maui-check

**Comment by Midnayt** [comment]
> I suspect you're missing some workloads. I recommend checking out the Maui Check tool at https://github.com/Redth/dotnet-maui-check That tool should install everything you may be missing.

maui-check doesn't work. this tool can't install workloads, VS Installer - same.
cmd - dotnet workload install maui - same

**Comment by ElliottBrand** [comment]
It looks like there are a few threads out there about workload install issues. Check these out to see if either resembles your issue or are helpful:

https://github.com/dotnet/maui/issues/2037

https://github.com/dotnet/sdk/issues/19739

**Comment by Midnayt** [comment]
> It looks like there are a few threads out there about workload install issues. Check these out to see if either resembles your issue or are helpful:
> 
> #2037
> 
> [dotnet/sdk#19739](https://github.com/dotnet/sdk/issues/19739)

None of them doesn't provide a solution to fix this.

**Comment by Kalyxt** [comment]
I was trying out MAUI few days ago and I had to look around too as dotnet maui (maui-check) isn't working anymore.

Check this page if you haven't already. I followed all steps and I could run android/ios/win10 app at the end. 
https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation

**Comment by ElliottBrand** [comment]
If nothing else works, something else you can try is to delete the workloads folder at C:\Program Files\dotnet\metadata\workloads and re-run maui-check.

If that still doesn't work, there's a PowerShell script that can be ran to clean up old previews which can cause conflicts. See item number 3 in the troubleshooting section at https://github.com/Redth/dotnet-maui-check

**Comment by Midnayt** [comment]
> If nothing else works, something else you can try is to delete the workloads folder at C:\Program Files\dotnet\metadata\workloads and re-run maui-check.
> 
> If that still doesn't work, there's a PowerShell script that can be ran to clean up old previews which can cause conflicts. See item number 3 in the troubleshooting section at https://github.com/Redth/dotnet-maui-check

maui-check doesn't work at all(this tool can't update/install maui workloads in different configurations).

**Comment by jfversluis** [comment]
You should be able to use `dotnet workload` now or Visual Studio to install this. Newer versions of all the tooling have been released, I'm going to assume this works by now. If not, don't hesitate to let us know!
