### ISSUE TITLE
[Bug] Breakpoints when debugging always point to external code

### ISSUE THREAD

**Issue by AustinEnos95** [dotnet/maui#2699]
### Description
I have been working on a MAUI android application and whenever I boot up in debug mode and interact in a way that would trigger a breakpoint to be hit, I just hit a break, but not in the code, it always comes up with 
'Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code)."

I've checked all the debug settings and everything seems to be setup correctly.

### Steps to Reproduce

1. With your MAUI application set to debug mode, using either an emulator or physical device, start the application.
2. Interact with the application to trigger a breakpoint you have set.
3. The message seen above will display ^.

### Expected Behavior
I should hit a breakpoint in my code so that I can step debug.

### Actual Behavior
Breakpoints claim to be pointing to external code.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2022 Preview
- Platform Target Frameworks: 
  - net6.0-ios;
  - net6.0-android;
  - net6.0-maccatalyst
- iOS:  
- Android:  
- UWP:   
- Android Support Library Version: 
- Nuget Packages: N/A
- Affected Devices: 
  - Pixel 2 Pie 9.0 - API 28 Android Emulator
  - Galaxy S21 Ultra Physical device.

**Comment by drasticactions** [comment]
This is an issue with the .NET 6 Android Tooling in Visual Studio and I think it is unrelated to MAUI, as you can replicate it with a straight Android app running on .NET 6 through Visual Studio.

I would file this through [Visual Studio Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019#:~:text=%20Visual%20Studio%20feedback%20options%20%201%20Report,tool%20at%20the%20top-right%20of%20any...%20More%20).

**Comment by whann0205** [comment]
I have exact the same problem as AustinEnos95!
Decided to test what drasticactions said, regarding that one being a visual studio issue.
So i created a new project with a template "Android App (Xamarin)". 
And there the breakpoint is working without problems.
Problem exists definitely at least for projects with templates MAUI regardless if blazor
or regular maui app.

**Comment by drasticactions** [comment]
It's not an MAUI-specific problem, it's Android in general. You can replicate the issue with a standard (non-maui) Android app. It doesn't mean it will _always_ happen, just as there are some who can break inside new MAUI apps and have it work just fine.

I've also seen it happen, on Android with the current VS 2022, with class projects referenced in a MAUI app or a standalone Android app. It's not consistent, sometimes it works, sometimes it doesn't, but it's not just related to MAUI, it's an Android tooling issue.

**Comment by whann0205** [comment]
I have finally played around a little more. Seems that the problem is indeed iffy and not only based on maui. 
Although it seems to be project related. I got a project (net maui without blazor) to work fine.
A new created maui blazor app does not nor my own project. 
Its really Annoying!! 
You always refer to android tooling, so i tried the debugger on vs 2019 again which seems to use
the same tooling and it works ok. 
Anyway what can we do / tell who what to get this fixed? Not having a debugger is impossible in these days...

**Comment by I4-PJ** [comment]
Hello, I have reported the same at Visual Studio dev forums

https://developercommunity.visualstudio.com/t/VS2022-MAUI-exception-thrown-asynchronou/1534748

PJ.

**Comment by rudyspano** [comment]
Hi @jsuarezruiz . Any workaround ? That's very complicated to test MAUI without debugging on Android...

**Comment by JohnHDev** [comment]
This isn't Android specific, Im seeing this on iOS as well. VS2022 preview 10 paired to Mac.

**Comment by JohnHDev** [comment]
@jsuarezruiz any suggestions on this? I am currently unable to debug iOS for the same reasons.
Has anyone at MS replicated the problem? Is a fix in the pipeline? Or does anyone know a way to resolve this?
I am happy to assist with logs if it will help, just tell when what, where, and when.

**Comment by whann0205** [comment]
I installed yesterday the latest Visual Studio 2022 Preview Version, before i did accidentially install the current version. Also on the machine is VS 2019 which is used for production.
Net Maui was installed automatically with VS 2022 Preview. 
I migrated the application again from 3.1 and now the debugger works!!
At least for Android, have not had time to test IOS though

**Comment by BradChase2011** [comment]
For me if I remove <DebugSymbols>true</DebugSymbols> then I can debug the startup project.  I still cannot debug the other project references, but its a start.

**Comment by john-technegol** [comment]
I'm getting this on a maui app. Works using Android Emulator but can't debug on a local iPhone. I'm using Visual Studio 2022 Preview 5

**Comment by wenwen60** [comment]
Not repro on Android 11 and iOS, with VS2022 17.2.0 Preview 2.0 [32215.517.main].
