### ISSUE TITLE
How can I change the MAUI Blazor App Window properties

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/maui#2701]
I m trying to change th MAUI Blazor APP title but this not works. also how do I change the window size on startup or like any other property?
![Screenshot 2021-09-26 210516](https://user-images.githubusercontent.com/33988671/134820898-aa00a74b-7717-4aa3-a754-e5deed561e4c.jpg)
![Screenshot 2021-09-26 210547](https://user-images.githubusercontent.com/33988671/134820899-c903d1ea-1b8c-4380-8f64-b640801ed425.jpg)

**Edit**
I found out that we have to override the CreateWindow method I used the Weather example app to find it out
https://github.com/davidortinau/WeatherTwentyOne/blob/main/src/WeatherTwentyOne/App.xaml.cs#L18

**Comment by mattleibow** [comment]
Using the CreateWindow is the correct place, or you can do `Application.Current.Windows[0].Title` or even in the page `OnAppearing`: `((Window)this.Parent).Title`

**Comment by jfversluis** [comment]
Seems like this is answered!
