### ISSUE TITLE
[Bug] Maui Essentials WebAuthenticator not working in WinUI

### ISSUE THREAD

**Issue by ElliottBrand** [dotnet/maui#2702]
I'm attempting to use WebAuthenticator in Maui Essentials to authenticate a WinUI project, but it's having an issue finding the manifest file. It throws an exception saying:

**Could not find file 'C:\WINDOWS\system32\AppxManifest.xml'.**

If I add a local version of https://github.com/dotnet/maui/blob/main/src/Essentials/src/WebAuthenticator/WebAuthenticator.uwp.cs into my project (_I made PlatformAuthenticateAsync public to test it and just passed the url and callbackUrl in the WebAuthenticatorOptions_) and adjust line 51 to:

```csharp
var doc = XDocument.Load($"{AppDomain.CurrentDomain.BaseDirectory}AppxManifest.xml", LoadOptions.None);
```

It then finds the file, however, a new error is thrown that says:

**System.Runtime.InteropServices.COMException: 'There are no remote procedure calls active on this thread. (0x800706BD)'**

Additionally, I set the CallbackUrl to:

```csharp
new Uri("io.identitymodel.native://callback")
```

and the Url to:

```csharp
new Uri("https://demo.identityserver.io")
```

**Comment by jamesmontemagno** [comment]
Did you add the extension into your app:

```xml
<Applications>
    <Application Id="App" Executable="$targetnametoken$.exe" EntryPoint="MyApp.App">
        <Extensions>
            <uap:Extension Category="windows.protocol">
            <uap:Protocol Name="myapp">
                <uap:DisplayName>My App</uap:DisplayName>
            </uap:Protocol>
            </uap:Extension>
        </Extensions>
    </Application>
</Applications>
```

**Comment by ElliottBrand** [comment]
Yeah, here's the Package.appxmanifest file from this sample app.

```
<?xml version="1.0" encoding="utf-8"?>

<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
  IgnorableNamespaces="uap rescap">

  <Identity
    Name="DC54F990-A6CD-4BED-B2AE-1942F4470BCC"
    Publisher="CN=User Name"
    Version="1.0.0.0" />

  <Properties>
    <DisplayName>MauiAppFileInput</DisplayName>
    <PublisherDisplayName>Microsoft</PublisherDisplayName>
    <Logo>Assets\appiconStoreLogo.png</Logo>
  </Properties>

  <Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.17763.0" MaxVersionTested="10.0.19041.0" />
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.17763.0" MaxVersionTested="10.0.19041.0" />
  </Dependencies>

  <Resources>
    <Resource Language="x-generate"/>
  </Resources>

  <Applications>
    <Application Id="App"
      Executable="$targetnametoken$.exe"
      EntryPoint="$targetentrypoint$">
      <uap:VisualElements
        DisplayName="MauiAppFileInput"
        Description="MauiAppFileInput"
        BackgroundColor="transparent"
        Square150x150Logo="Assets\appiconMediumTile.png"
        Square44x44Logo="Assets\appiconLogo.png">
        <uap:DefaultTile
          Wide310x150Logo="Assets\appiconWideTile.png"
          Square71x71Logo="Assets\appiconSmallTile.png"
          Square310x310Logo="Assets\appiconLargeTile.png"
          ShortName="MauiAppFileInput">
          <uap:ShowNameOnTiles>
            <uap:ShowOn Tile="square150x150Logo"/>
            <uap:ShowOn Tile="wide310x150Logo"/>
          </uap:ShowNameOnTiles>
        </uap:DefaultTile >
        <uap:SplashScreen Image="Assets\appiconfgSplashScreen.png" />
      </uap:VisualElements>
      <Extensions>
        <uap:Extension Category="windows.protocol">
          <uap:Protocol Name="io.identitymodel.native">
            <uap:DisplayName>WebAuthenticatorDemo</uap:DisplayName>
          </uap:Protocol>
        </uap:Extension>
      </Extensions>
    </Application>
  </Applications>

  <Capabilities>
    <rescap:Capability Name="runFullTrust" />
  </Capabilities>

</Package>
```

**Comment by ElliottBrand** [comment]
In MainPage.xaml.cs I have a using directive for OidcClient (and a few others that can be easily resolved in the editor)

```using IdentityModel.OidcClient```

Variables
```
OidcClient _oidcClient;
LoginResult _loginResult;
```

 and a method to handle a login button click:

```
async void OnLoginButtonClicked(object sender, EventArgs e)
{
    var options = new OidcClientOptions
    {
        Authority = "https://demo.identityserver.io",
        ClientId = "interactive.public",
        Scope = "openid profile email api offline_access",
        RedirectUri = "io.identitymodel.native://callback",
        Browser = new Browser()
    };

    _oidcClient = new OidcClient(options);
    _loginResult = await _oidcClient.LoginAsync(new LoginRequest());
    if (_loginResult.IsError)
    {
        Console.WriteLine("ERROR: {0}", _loginResult.Error);
        return;
    }
}
```

And the Browser.cs file. As I mentioned initially, I'm calling WebAuthenticator.PlatformAuthenticateAsync(authenticatorOptions) in my local file. Except for a few namespace adjustments to prevent conflicts and the adjustment to line 51, it's the same file as what's used in Maui Essentials.

```
using IdentityModel.OidcClient.Browser;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace MauiAppSample
{
    public class Browser : IBrowser
    {
        public async Task<BrowserResult> InvokeAsync(BrowserOptions options, CancellationToken cancellationToken = default)
        {
            var authenticatorOptions = new Microsoft.Maui.Essentials.WebAuthenticatorOptions
            {
                CallbackUrl = new Uri("io.identitymodel.native://callback"),
                Url = new Uri("https://demo.identityserver.io")
            };

            Microsoft.Maui.Essentials.WebAuthenticatorResult authResult =
                await WebAuthenticator.PlatformAuthenticateAsync(authenticatorOptions);
            return new BrowserResult()
            {
                Response = ParseAuthenticatorResult(authResult)
            };
        }

        string ParseAuthenticatorResult(Microsoft.Maui.Essentials.WebAuthenticatorResult result)
        {
            string code = result?.Properties["code"];
            string scope = result?.Properties["scope"];
            string state = result?.Properties["state"];
            string sessionState = result?.Properties["session_state"];
            return $"{"io.identitymodel.native://callback"}#code={code}&scope={scope}&state={state}&session_state={sessionState}";
        }
    }
}
```

**Comment by Berets** [comment]
Any news about this? Same error here

**Comment by ElliottBrand** [comment]
Sorry, no news. I'm still experiencing it too.

**Comment by hexjourney** [comment]
Same error

**Comment by RichardCain** [comment]
Same here

**Comment by RichardCain** [comment]
ps. If I copy the appxmanifest to c:\windows\system32, it finds it and gets the protocol, but barfs with "There are no remote procedure calls active on this thread. (0x800706BD)"

**Comment by samifahmy** [comment]
any news i have same error too?

**Comment by enisn** [comment]
same error

**Comment by enisn** [comment]
I've tried on a couple of different computers but the reason is the same. Also, I've tried clean installation of Maui & workloads, and tried on cleanly installed windows but nothing changed. 

It tried to find `Could not find file 'C:\WINDOWS\system32\AppxManifest.xml` file but it doesn't exist in system32 folder in any windows machine.

Then, I've tried to check my `Package.appxmanifest` file, I think AppxManifesat can't be generated for application and I see it can't be opened in Visual Studio

![image](https://user-images.githubusercontent.com/23705418/154896896-7c5c0820-bee4-4c61-b47a-fc8b62dd6d9e.png)

I think there might be an error in **`Package.appxmanifest`** file on MAUI project template. Unfortunetely I'm not pro on Win apps, so I can't see what is wrong with that file.

> Note: I've also added windows.protocol extension in that file with VSCode

---

Could anyone get over this issue?

**Comment by wenwen60** [comment]
Reproduce on windows with VS2022 17.2.0 Preview 2.0 [32215.517.main], attach repro sample
[2702.zip](https://github.com/dotnet/maui/files/8195469/2702.zip).

**Comment by mattleibow** [comment]
I believe there was a bug in the packaging process before. @Eilon I think there was an issue at some point where the targets were copying the Package.appxmanifest into the root of the package and this caused some issues. 

I can't seem to locate the issue I am thinking of, but I felt it was maybe the blazor content copying being too happy and grabbing all files or something?

**Comment by shv07** [comment]
Any updates on the issue? I have been facing the exactly same issue in windows with the latest Release Candidate.

**Comment by mattleibow** [comment]
It appears that auth is not supported natively on WinUI :(
 - https://github.com/microsoft/WindowsAppSDK/issues/441
 - https://github.com/microsoft/WindowsAppSDK/issues/398

**Comment by dotMorten** [comment]
Here's one implementation that can probably be more or less lifted as is into MAUI: https://github.com/dotMorten/WinUIEx/blob/main/src/WinUIEx/WebAuthenticator.cs
You might want to change the use of the module initializer and instead do it on app launch constructor

**Comment by shv07** [comment]
> Here's one implementation that can probably be more or less lifted as is into MAUI: https://github.com/dotMorten/WinUIEx/blob/main/src/WinUIEx/WebAuthenticator.cs You might want to change the use of the module initializer and instead do it on app launch constructor

Thanks for the repo. I tried using this class as replacement. It is now able to open the browser, initiate the authentication and redirect back to the application, but immediately after that, throws a "invalid state" error within the oidc client. On closer inspection, the value for the "state" key in the returned WebAuthenticatorResult.Properties (from AuthenticateAsync) seems quite different from what is received on a similar android project.

**Comment by dotMorten** [comment]
@shv07 Mind opening an issue over in the WinUIEx repo and we can discuss there?

**Comment by jayveedee** [comment]
On a slightly different note but still related to the WebAuthenticator. On Android the documentation for Xamarin Essentials, it still only supports Android 11 or SDK 30. Will this be updated? Because if you target Android 12 as of right now and use the WebAuthenticator you will get an error which says "java crashed with exit code 1"
Think this should probably be fixed if Android 12 will be targeted by default on a fresh install and essentials will be in the Maui framework by default.

**Comment by shv07** [comment]
@jayveedee I was able to fix that error by setting ```Exported = true``` in the Activity class. You get this information if you see the build logs after setting it to more verbose from the VS settings.

My final Activity was like this:-

```c#
// MainActivity.cs
[Activity(NoHistory = true, LaunchMode = LaunchMode.SingleTop, Exported = true)] 
[IntentFilter(new[] { Android.Content.Intent.ActionView },
        Categories = new[] { Android.Content.Intent.CategoryDefault, Android.Content.Intent.CategoryBrowsable },
        DataScheme = "myapp")]
public class WebAuthenticationCallbackActivity : WebAuthenticatorCallbackActivity
 {
 }
```

**Comment by jamesmontemagno** [comment]
@shv07 can you send a PR to the docs?

**Comment by shv07** [comment]
@jamesmontemagno Sure, done. MicrosoftDocs/xamarin-docs#3455

**Comment by dotMorten** [comment]
@davidbritch did you mean to close this with a doc issue?

**Comment by enisn** [comment]
**Status update:**
`AppxManifest.xml` file problem has been resolved with the latest release but still OpenID Connect login doesn't work.

The following issue can be tracked: 
https://github.com/microsoft/WindowsAppSDK/issues/441

**Comment by osnipezzini** [comment]
Any news about this ?

**Comment by ElliottBrand** [comment]
I was able to get my MAUI WinUI app to log in successfully, primarily with the help of the code provided up above by @dotMorten. 

> Here's one implementation that can probably be more or less lifted as is into MAUI: https://github.com/dotMorten/WinUIEx/blob/main/src/WinUIEx/WebAuthenticator.cs You might want to change the use of the module initializer and instead do it on app launch constructor

Just copy that code into a file called something like ```WebAuthenticator.cs``` and drop it into the Platforms > Windows folder of your MAUI project (_or wherever works best for you_), then reference it instead of the current Essentials Web Authenticator.

I did have one issue with an exception throwing in my OIDC Client Browser that said "Invalid state".  It turned out being that the state information being added in new Web Authenticator class (appInstanceId & signinId) wasn't expected while building the ```BrowserResult```, so this is what I did.

```csharp
using IdentityModel.OidcClient.Browser;
using System.Diagnostics;

namespace MyAwesomeMauiApp.WinUI;

public class Browser : IdentityModel.OidcClient.Browser.IBrowser
{
    public async Task<BrowserResult> InvokeAsync(BrowserOptions options, CancellationToken cancellationToken = default)
    {
        try
        {
            Microsoft.Maui.Authentication.WebAuthenticatorResult authResult =
                await WinUIEx.WebAuthenticator.AuthenticateAsync(new Uri(options.StartUrl), new Uri("myapp://callback")); // Add your callback URL 

            var authorizeResponse = ToRawIdentityUrl(options.EndUrl, authResult);

            return new BrowserResult
            {
                Response = authorizeResponse
            };
        }
        catch (TaskCanceledException ex)
        {
            Debug.WriteLine(ex);
            return new BrowserResult
            {
                ResultType = BrowserResultType.UserCancel
            };
        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex);
            return new BrowserResult()
            {
                ResultType = BrowserResultType.UnknownError,
                Error = ex.ToString()
            };
        }
    }

    public string ToRawIdentityUrl(string redirectUrl, WebAuthenticatorResult result)
    {
        try
        {
            IEnumerable<string> parameters = result.Properties.Select(pair => $"{pair.Key}={pair.Value}");
            var modifiedParameters = parameters.ToList();

            var stateParameter = modifiedParameters
                .FirstOrDefault(p => p.StartsWith("state", StringComparison.OrdinalIgnoreCase));

            if (!string.IsNullOrWhiteSpace(stateParameter))
            {
                // Remove the state key added by WebAuthenticator that includes appInstanceId
                modifiedParameters = modifiedParameters.Where(p => !p.StartsWith("state", StringComparison.OrdinalIgnoreCase)).ToList();
                
                stateParameter = System.Web.HttpUtility.UrlDecode(stateParameter).Split('&').Last();
                modifiedParameters.Add(stateParameter);
            }
            var values = string.Join("&", modifiedParameters);
            return $"{redirectUrl}#{values}";
        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex);
            throw;
        }
    }
}
```

**Comment by mattleibow** [comment]
Closing this as it is a bug in the Windows App SDK and is being tracked there: https://github.com/microsoft/WindowsAppSDK/issues/441

**Comment by osnipezzini** [comment]
WebAuthenticator its working now ?

**Comment by dotMorten** [comment]
Yup https://learn.microsoft.com/en-us/windows/apps/develop/security/oauth2?tabs=cpp
Will need some work in Maui app lifecycle to incorporate though

**Comment by dotMorten** [comment]
One thing I'm hitting is the windows apis only supports code requests, and the sample app only requests a token, which isn't really what apps should be doing anyway (you get the token afterwards by doing a refresh token call using the code, and refresh the token based on its expiration, whereas the code is long-lasting).
Could https://xamarin-essentials-auth-sample.azurewebsites.net/mobileauth be changed to use a code instead?

**Comment by omghb** [comment]
We run into the same issue.

**Comment by Syed-RI** [comment]
> Yup https://learn.microsoft.com/en-us/windows/apps/develop/security/oauth2?tabs=cpp Will need some work in Maui app lifecycle to incorporate though

@dotMorten do you have some MAUI examples? Or we have to build a native implementation using `OAuth2Manager` https://learn.microsoft.com/en-us/windows/apps/develop/security/oauth2?tabs=csharp? cc @davidortinau @jfversluis @jamesmontemagno @jsuarezruiz

**Comment by solomonfried** [comment]
Still not working .NET 10 and VS2026. Is Windows MAUI ever planning to support WebAuthenticator again?
My MAUI version of my app is now being planned for release on Android and iOS only. My users are in schools, and many have MS Surfaces. I really hope this issue get escalated.

**Comment by dotMorten** [comment]
@solomonfried did you try any of the alternative solutions? For instance [this](https://dotmorten.github.io/WinUIEx/concepts/Maui.html#use-winuiexs-webauthenticator-instead-of-net-mauis).

**Comment by solomonfried** [comment]
Thanks,

I will give that a try. I was trying to delay hoping that MAUI’s WebAuthenticator would get fixed.

Right now, when I add the WinUIEx nuget package, I get a build failure with…

The MSIX build tools use the 'CustomBeforeMicrosoftCommonTargets' MSBuild property to wire up a custom .props file that sets some necessary properties. This .props file does not appear to have been imported correctly. This likely means that someone has also overridden 'CustomBeforeMicrosoftCommonTargets', without ensuring to also chain the import of the previously assigned .props and .targets set to that property. You can use a binlog to learn more about where that assignment was done (set the verbosity to diagnostics, and search for 'reassignment: $(CustomBeforeMicrosoftCommonTargets').


Your documentation mentions how to address this but the message does not reference an SDK version.  Which do I use? I tried looking through the nuget packages and the obj directory for a manifest file that would have this information.

<ItemGroup> <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.250907003" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'" /> </ItemGroup>


Thanks.

**Comment by solomonfried** [comment]
> [@solomonfried](https://github.com/solomonfried) did you try any of the alternative solutions? For instance [this](https://dotmorten.github.io/WinUIEx/concepts/Maui.html#use-winuiexs-webauthenticator-instead-of-net-mauis).

Trying the solution there. 
Added this to my project
```
  <ItemGroup>
    <PackageReference Include="WinUIEx" Version="2.8.0" Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.250907003" Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'" />
  </ItemGroup>
```

Getting these errors on build
Could not copy the file "C:\Users\solfr\.nuget\packages\microsoft.maui.controls.compatibility\10.0.11\lib\net10.0-windows10.0.19041\Microsoft.Maui\Handlers\HybridWebView\HybridWebView.js" because it was not found.
Could not copy the file "C:\Users\solfr\.nuget\packages\microsoft.maui.controls.core\10.0.11\lib\net10.0-windows10.0.19041\Microsoft.Maui\Handlers\HybridWebView\HybridWebView.js" because it was not found.
Could not copy the file "C:\Users\solfr\.nuget\packages\microsoft.maui.core\10.0.11\lib\net10.0-windows10.0.19041\Microsoft.Maui\Handlers\HybridWebView\HybridWebView.js" because it was not found.

I did some back and forth with chatGPT, Ended up launching a browser which then launched a second version of my app.

Also, on 
WinUIEx.WebAuthenticator getting a warning that WinUIEx.WebAuthenticator is obsolete.


Is there zero chance that MAUI will support Windows apps in its own WebAuthenticator?!?!?

**Comment by FedeRusconi** [comment]
@solomonfried 

Not sure if this helps, but I needed to open a third-party web authentication flow using OAuth and SSO, with the callback returning to my .NET MAUI app on Windows. I ended up doing a rather hacky approach:

- The Windows app opens the web link to the authentication page with a callback URL using my app’s custom URI protocol (e.g., `myapplication://auth`) and starts a `NamedPipeServerStream `to listen.
- The user signs in on the webpage.
- Once the sign-in is complete, the third-party auth flow sends the auth code to my callback URL, which opens a second instance of the app.
- In `Platforms/Windows/App.xaml.cs`, I override the `OnLaunched` method. Here, I extract command-line arguments, which may include the auth code and any state passed. I check whether this launch is from the auth completion or a regular app start.
- After confirming that another instance is already running and extracting the auth code, I connect to the same named pipe using `NamedPipeClientStream`, write the auth code to the stream, disconnect, and terminate this second instance. Placing this code in `App.xaml.cs` allows me to intercept the call before the app fully initializes, so the user never sees a second instance.
- The first instance, listening on the stream, receives the message, disconnects, and completes the sign-in process.

It’s hacky, but it works. I implemented it a few years ago and haven’t reviewed it since.

**Comment by solomonfried** [comment]
Is the web page in the app or in an external browser?
I may try this. For now I am actually reverting back to my Xamarin version of my app to release critical bug fixes. 
I hope the Windows app store still takes Xamarin builds (iOS and Android do not do to Xamarin's reliance on older versions of iOS and Android.

**Comment by FedeRusconi** [comment]
> Is the web page in the app or in an external browser? I may try this. For now I am actually reverting back to my Xamarin version of my app to release critical bug fixes. I hope the Windows app store still takes Xamarin builds (iOS and Android do not do to Xamarin's reliance on older versions of iOS and Android.

The web page opens in an external browser. I’m using .NET MAUI with Blazor, so I just have an <a> link with an external href in my Razor page, which opens the page automatically in the user’s browser. I haven’t tried the “MAUI” way of opening a link with a WebView.

**Comment by dotMorten** [comment]
Opening in an external browser is the recommended way from a security point of view anyway, albeit it's a slightly more jarring experience until Windows will provide a more OS-integrated way like iOS and Android did.

**Comment by solomonfried** [comment]
I'm willing to live with the browser issue (don't really have a choice).
But I also need to deal with the flow opening a second instance of my app. 
For immediate support, I am still maintaining the Xamarin version of my app just for Windows. 
iOS and Android are converted.
I really hope MS gets around to this.

**Comment by solomonfried** [comment]
Worked today with CoPilot (via Claude) and it provided a solution that seems to be working for MAUI Windows.
It uses WebView2 and no other dependencies...

The end result is a clean dialog, showing withing the app (not a separate windows) and returns right after the AuthenticateAsync call (exactly as on all other platforms).

I do not understand why Microsoft could not fold this solution into the MAUI WebAuthenticator.

Still need to do some serious testing. But it seems to be working

Here is my code as is: Adjust namespaces as needed.
Under Platforms/Windows add the class WindowsWebAuthenticator (see code below).
Where you normally call AuthenticateAsync change to this..

```
#if WINDOWS
                result = await ProviderLogin.WindowsWebAuthenticator.AuthenticateAsync(authUrl, callbackUrl);
#else
                result = await WebAuthenticator.AuthenticateAsync(authUrl, callbackUrl);
#endif
```

Then you need to add this to MauiProgram.cs.
Change the IsOAuthCallback method to identify something in your oAuth callback that identifies it as you oAuthCallback.
In my case my Server Authenticate Get request returns with a url that looks like "com.companyname.appname:///#"  with user auth information added.  In my app, I support Single Sign On so I can get activations with Urls from Google/Apple, etc...so need to make sure this is coming from my own Authenticate endpoint.

```
#if WINDOWS
    private static void AppInstance_Activated(object? sender, AppActivationArguments e)
    {
        if (e.Kind != ExtendedActivationKind.Protocol ||
            e.Data is not ProtocolActivatedEventArgs protocol)
        {
            return;
        }

        var uri = protocol.Uri;

        // Simple check: OAuth uses ///#, SSO uses actual paths
        if (IsOAuthCallback(uri))
        {
            ProviderLogin.WindowsWebAuthenticator.HandleProtocolActivation(uri);
            return;
        }

        // Handle SSO deep links
        var app = Application.Current as App;
        app?.Dispatcher.Dispatch(async () => await app.HandleAppLink(uri));
    }

    private static bool IsOAuthCallback(Uri uri)
    {
        return uri.ToString().StartsWith("com.companyname.appname:///#", StringComparison.OrdinalIgnoreCase);
    }
#endif

```

Here is the WindowsWebAuthenticator class (place in Platforms/Windows or wrap in an #if WINDOWS block.
```
#nullable enable
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.Web.WebView2.Core;
using System.Diagnostics;
using System.Web;
using Application = Microsoft.Maui.Controls.Application;

// ReSharper disable once CheckNamespace
namespace ProviderLogin;

public static class WindowsWebAuthenticator
{
    private static TaskCompletionSource<WebAuthenticatorResult>? _pendingAuth;
    private static ContentDialog? _activeDialog;

    public static async Task<WebAuthenticatorResult> AuthenticateAsync(
        Uri url,
        Uri callbackUrl)
    {
        var tcs = new TaskCompletionSource<WebAuthenticatorResult>();
        _pendingAuth = tcs;

        await MainThread.InvokeOnMainThreadAsync(async () =>
        {
            try
            {
                var webView = new WebView2
                {
                    Width = 500,
                    Height = 600
                };

                await webView.EnsureCoreWebView2Async();

                // NOTE: NavigationStarting won't fire for protocol URLs (com.pnqsys.classtars://)
                // Windows intercepts them before WebView2 sees them
                // So we handle the result in HandleProtocolActivation instead

                webView.CoreWebView2.NavigationCompleted += (s, e) =>
                {
                    // Ignore expected cancellation
                    if (e.WebErrorStatus == CoreWebView2WebErrorStatus.ConnectionAborted)
                        return;

                    // Handle real navigation errors
                    if (!e.IsSuccess && !tcs.Task.IsCompleted)
                    {
                        tcs.TrySetException(new Exception(
                            $"Authentication navigation failed: {e.WebErrorStatus}"));
                        _activeDialog?.Hide();
                        _pendingAuth = null;
                        _activeDialog = null;
                    }
                };

                var dialog = new ContentDialog
                {
                    Content = webView,
                    Title = "Sign In",
                    CloseButtonText = "Cancel",
                    DefaultButton = ContentDialogButton.Close,
                    XamlRoot = GetXamlRoot()
                };

                _activeDialog = dialog;  // Store for HandleProtocolActivation to close

                dialog.Closed += (s, e) =>
                {
                    if (!tcs.Task.IsCompleted)
                    {
                        tcs.TrySetCanceled();
                    }
                    _pendingAuth = null;
                    _activeDialog = null;
                };

                webView.Source = url;
                _ = dialog.ShowAsync();
            }
            catch (Exception ex)
            {
                tcs.TrySetException(ex);
                _activeDialog?.Hide();
                _pendingAuth = null;
                _activeDialog = null;
            }
        });

        return await tcs.Task;
    }

    // Called from MauiProgram.cs when protocol activation occurs
    public static void HandleProtocolActivation(Uri activationUri)
    {
        MainThread.BeginInvokeOnMainThread(() =>
        {
            if (_pendingAuth == null)
            {
                Debug.WriteLine("[WindowsWebAuthenticator] No pending authentication");
                return;
            }

            if (_pendingAuth.Task.IsCompleted)
            {
                Debug.WriteLine("[WindowsWebAuthenticator] Authentication already completed");
                return;
            }

            try
            {
                Debug.WriteLine($"[WindowsWebAuthenticator] Processing callback: {activationUri}");

                var parameters = ParseQueryAndFragment(activationUri);
                var result = new WebAuthenticatorResult(parameters);

                _pendingAuth.TrySetResult(result);
                Debug.WriteLine("[WindowsWebAuthenticator] Result set successfully");

                // THIS is where the dialog gets hidden (not in NavigationStarting)
                if (_activeDialog != null)
                {
                    _activeDialog.Hide();
                    Debug.WriteLine("[WindowsWebAuthenticator] Dialog hidden");
                }
                else
                {
                    Debug.WriteLine("[WindowsWebAuthenticator] WARNING: No active dialog to hide!");
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"[WindowsWebAuthenticator] Error: {ex.Message}");
                _pendingAuth.TrySetException(ex);
                _activeDialog?.Hide();
            }
            finally
            {
                _pendingAuth = null;
                _activeDialog = null;
            }
        });
    }

    private static XamlRoot? GetXamlRoot()
    {
        var mauiContext = Application.Current?.Windows[0]?.Handler?.MauiContext;
        if (mauiContext != null)
        {
            var platformWindow = mauiContext.Services.GetService<Microsoft.UI.Xaml.Window>();
            return platformWindow?.Content?.XamlRoot;
        }

        return null;
    }

    private static IDictionary<string, string> ParseQueryAndFragment(Uri uri)
    {
        var result = new Dictionary<string, string>();

        // Parse query string
        if (!string.IsNullOrEmpty(uri.Query))
        {
            var queryParams = HttpUtility.ParseQueryString(uri.Query);
            foreach (string key in queryParams.AllKeys)
            {
                if (key != null)
                    result[key] = queryParams[key] ?? string.Empty;
            }
        }

        // Parse fragment (where your OAuth tokens are)
        if (!string.IsNullOrEmpty(uri.Fragment))
        {
            var fragment = uri.Fragment.TrimStart('#');
            var fragmentParams = HttpUtility.ParseQueryString(fragment);
            foreach (string key in fragmentParams.AllKeys)
            {
                if (key != null)
                    result[key] = fragmentParams[key] ?? string.Empty;
            }
        }

        return result;
    }
}
```

**Comment by ltouro** [comment]
Since this is listed on https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?view=net-maui-10.0&viewFallbackFrom=net-maui-8.0&tabs=windows and the issue is very old, can you provide updated description? 

Issues: It is pointing to a closed issue with. No clean future direction. Provides no workaround. Very long thread of related issues.

Is this still planned to be resolved some day? 5years for a P1 bug is rather discouraging

**Comment by dotMorten** [comment]
> I do not understand why Microsoft could not fold this solution into the MAUI WebAuthenticator.

Because embedded webview is considered a bad practice. You have to trust the app to not peek inside the webview and steal the password. Also some Authenticator websites will detect and block webviews.
Microsoft already provided a solution in the winappsdk. We just need the Maui team to adopt it. Until that happens you can use the winappsdk APIs yourself inside an `#if WINDOWS` section

**Comment by solomonfried** [comment]
Got it. However, so far with Google, Apple, MS AD, and the 3 other enterprise School-bases oAuth providers all work,
I clearly am not an expert on this, but working with Copilot it agreed about the vulnerability, but gave me a list of reasons why the SDK would be more complicated to use. For example, it needs a protocol section in Package.appxmanifiest among other items, all of which I'd be willing to tackle. Except for the claim that it would pop up a second browser. Is this, in fact, true?
For me this is a major UI break from the MAUI WebAuthenticator. Sending users out of your app Windows is never a good idea.

**Comment by dotMorten** [comment]
> For me this is a major UI break from the MAUI WebAuthenticator. Sending users out of your app Windows is never a good idea.

Technically the maui authenticator does do this on iOS and Android. It's just that iOS and Android built a better UI experience so it feels like you aren't truly leaving the app. I've numerous times requested the Windows team to build something similar (which they did do with UWP). Most of the OAuth services you list above will actually block webview usage on iOS and Android, but for now left Windows users alone (I repeat: for now). Google ToS for instance tells you to not use a webview: https://developers.google.com/identity/protocols/oauth2/policies#browsers

**Comment by solomonfried** [comment]
Thanks for the feedback
For now I am using this code
```
  try
  {
      // Try WebView2 first (better UX)
      return await AuthenticateWithWebView2(url, callbackUrl);
  }
  catch (Exception ex) when (IsOAuthBlockedException(ex))
  {
      Debug.WriteLine("[WindowsWebAuthenticator] WebView2 blocked, falling back to system browser");

      // Fallback to WebAuthenticationBroker
      return await AuthenticateWithBroker(url, callbackUrl);
  }
```
Try WebView and fall back to Broker Authentication

I still need to work on the WebAuthenticationBroker.AuthenticateAsync
it throws an exception with no error message.

If anyone can point me to working code, it would be appreciated.

It is EXTREMELY frustrating that Microsoft seems to be kicking support for their own platform to the curb.
I am advising my clients to use iPads if possible. But in some schools they already have invested in Surface tablets so I need to keep my Xamarin version alive until this issue is resovled.

**Comment by Axemasta** [comment]
I brought this issue up to the team during last weeks Maui Day 2026, I was told to keep bumping the thread.

This is blocking our windows release as we can't ship with an insecure (integrated webview) login mechanism. Something worth noting is that when running WSA (if you still have it installed), the web authenticator **does** work. I know its not using WinUI but I'm able to run my WSAndroid app, login, have chrome (default browser) open, do my external login, come back to the app and continue with my acquired auth token. If it works opening an external application when using WSA, why can't it work for a WinUI app?

**Comment by dotMorten** [comment]
WSA is Android. It’s a different beast. And if you read the thread this issue shouldn’t block you as there are ways to make it work with external login using Windows’ own APIs instead of relying on MAUI’s web authenticator
