### ISSUE TITLE
[Bug] FileProvider android in maui and xamarin.essentials conflict

### ISSUE THREAD

**Issue by yunusefendi52** [dotnet/maui#2705]
### Description
Add reference (or as dependency) https://www.nuget.org/packages/xamarin.essentials causing conflict fileProvider in maui xamarin.essentials with error compilation `error XA4215: The Java type 'xamarin.essentials.fileProvider' is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.`

### Steps to Reproduce

1. Create maui app (with maui essentials)
2. Add reference (or as dependency) to https://www.nuget.org/packages/xamarin.essentials
3. build project

### Expected Behavior
Success compilation and can run the app

### Actual Behavior
Error compilation

### Basic Information

- Version with issue: 6.0.100-rc.1.21463.6
- Last known good version:
- IDE: vscode (with command line)
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Dreamescaper** [comment]
Why do you need to add reference for Xamarin.Essentials?

**Comment by yunusefendi52** [comment]
There are libraries that uses Xamarin.Essentials without Xamarin.Forms, I use [Xamarin.Essentials.Interfaces](https://www.nuget.org/packages/Xamarin.Essentials.Interfaces) and I am trying to port to maui and just want to see if the build is success and the app is running without changing the Xamarin.Essentials.Interfaces part. But I think It'd be better if the FileProvider changed anyway to maui's own name (maui.essentials.fileProvider maybe)
https://github.com/dotnet/maui/blob/8163614acac0c8edd48f6d4edf78629591e061d5/src/Essentials/src/Types/FileProvider.android.cs#L14

**Comment by yunusefendi52** [comment]
This should be fixed by #4211
