### ISSUE TITLE
[Bug] SearchCommand not working in Android

### ISSUE THREAD

**Issue by migueBarrera** [dotnet/maui#2712]
### Description
The search command does not work with the search control on Android. The command is never executed.

### Steps to Reproduce

1. Use SearchBar control
2. Put a Command in SearchCommand with a ViewModel

### Expected Behavior
SearchCommand called when press search button on virtual keyboard

### Actual Behavior
On Android. the command is not called.
On UWP the command works fine.

### Basic Information

- Version with issue: SDK 6.0.100-rc.1.21463.6
- Last known good version:
- IDE: VS 2022 preview 4.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[test.zip](https://github.com/dotnet/maui/files/7236814/test.zip)

**Comment by PureWeen** [comment]
This should be fixed in RC2
https://github.com/dotnet/maui/pull/2454
