### ISSUE TITLE
[Bug] In Entry the textchanged event doesn't work

### ISSUE THREAD

**Issue by ThanhDN96** [dotnet/maui#2719]
### Description
Entry in maui 8 preview not receiving text changed event

### Steps to Reproduce

1. Create maui app
2. Code file MainPage.xaml
   
    
![image](https://user-images.githubusercontent.com/91511722/135011664-4959f7f0-88b7-4c02-8e1e-430c36abdfbc.png)

3. Code file MainPage.xaml.cs
        
        private void Entry_TextChanged(object sender, TextChangedEventArgs e)
        {
            this.textChangedLabel.Text = $"Text changed from {e.OldTextValue} to {e.NewTextValue}";
        }

        private void Entry_Completed(object sender, EventArgs e)
        {
            this.textChangedLabel.Text = "User completed entering text";
        }

###  Expected Behavior
      When the value in the entry is changed, the Entry_TextChanged event is called
###  Actual Behavior
      Entry_TextChanged event not called

### Basic Information
- Version with issue:
- Last known good version:
- IDE: visual studio 2022 preview 
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - Windows machine:  net6.0-windows10.0.19041
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

 ### Screenshots
![image](https://user-images.githubusercontent.com/91511722/135011314-59cdb7e3-6c54-48c9-9880-e234c3f7e92d.png)

![image](https://user-images.githubusercontent.com/91511722/135011358-80580d55-2b17-49b7-9902-6aea45073000.png)

### Workaround

**Comment by jsuarezruiz** [comment]
Fixed by https://github.com/dotnet/maui/pull/3054
