### ISSUE TITLE
[Bug] Childs inside Stacklayout not layout properly

### ISSUE THREAD

**Issue by SujaVenkatesan** [dotnet/maui#2732]
### Description
When we have nested child say(button and scrollview) inside the stacklayout, height is not set properly for scrollview. Items are not getting scrolled.

### Steps to Reproduce

1.Initilaize the stacklayout with vertical orientation
2. Add button/Label as first child to the stacklayout
3. Then Initialize scrollview with more scrollable content as second child to the stacklayout

### Expected Behavior
Items inside the scrollview need to scrolled while scrolling

### Actual Behavior
Items are not getting scrolled.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Samsung S8+ (API-28)

### Reproduction Link

[MauiApp2.zip](https://github.com/dotnet/maui/files/7244565/MauiApp2.zip)

**Comment by programmation** [comment]
This is also a problem with `FlexLayout` inside a `ScrollView`. Adding content to the `FlexLayout` such that it expands larger than the `ScrollView` does not enable scrolling (preview 8).

**Comment by hartez** [comment]
Change your outermost container from a StackLayout to a Grid. StackLayout.FillAndExpand does not currently work (see #1702 and related issues).
