### ISSUE TITLE
[Bug] [Android] Screen orientation not getting locked

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#2739]
### Description
In Android , adding the screenorientation as Portrait does not lock the orientation. Still switches to landscape of rotation.

Added code:
AndroidManifest file: android:screenOrientation="portrait"

Expected:
The app should not switch to landscape on device rotation

Actual: 
The app switches to landscape

**Comment by PureWeen** [comment]
@PaulAnderson02 not sure how you adding it to the manifest but if you add it to the activity it seems to work fine

```C#
	[Activity(
		Label = "@string/app_name",
		Theme = "@style/Maui.SplashTheme",
		MainLauncher = true,
		ScreenOrientation = ScreenOrientation.Portrait,
		ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode)]
	[IntentFilter(
		new[] { Microsoft.Maui.Essentials.Platform.Intent.ActionAppAction },
		Categories = new[] { Android.Content.Intent.CategoryDefault })]
	public class MainActivity : MauiAppCompatActivity
	{
	}
```

If you still have issues please attach a repro
