### ISSUE TITLE
Make MAUI AOT profile the default for MAUI Apps in Release configurations

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#2740]
See https://github.com/dotnet/maui/pull/2496 for more details

**Comment by jonathanpeppers** [comment]
A couple issues on this:

1. The `maui` workload does not extend `android-aot`, only `android`. The `Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.*` packs look to be about 272MB extracted on disk and 100MB download size.

2. Using AOT requires the Android NDK to be installed.

So it really depends on what we want to balance for install/download size vs getting started. You probably don't need AOT until you're going to submit something to Google Play.
