### ISSUE TITLE
[Bug] [WinUI] "Element Not Found" thrown when changing Window Size

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2744]
MAUI 6.0.101-preview.10.1790

https://user-images.githubusercontent.com/898335/135163864-9286d07a-8884-4049-ac20-3563b7530fe2.mp4

If you run the WinUI head and drag the window, the app will crash with "Element Not Found" after calling `NewWindowProc.CallWindowProc`

**Comment by hartez** [comment]
Fixed.
