### ISSUE TITLE
[Bug] Unable to start winUI app other than from the start menu

### ISSUE THREAD

**Issue by Berrion** [dotnet/maui#2750]
### Description
After deploy I am unable to run winUI app other than from the start menu. I tried to run same app that is run through start menu but nothing happens also tried to run it with PowerShell.  I try to run in like this to see how different UI auto test would work on that If somebody happens to know how to run those in some other way would also be thankful for any advice.

### Steps to Reproduce

1. Create sample MAUI project
2. build 
3. deploy
4. Try to run app from bin\Debug\net6.0-windows10.0.19041\win-x64\AppX (this is the one that is run from start menu) 

### Expected Behavior
I should be able to run app in some other way than from the start menu only. 
### Actual Behavior
I am able to run app only from the start menu after deploy
### Basic Information

- Version with issue: Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-rc.1.1608
- Last known good version:
- IDE: VS 2022 17.0.0 Preview 4.1
- Platform Target Frameworks: net6.0-windows10.0.19041
- Nuget Packages: None
- Affected Devices: Windows

**Comment by jfversluis** [comment]
Possibly related to things in #4329

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
