### ISSUE TITLE
[Bug] Windows app lifecycle overrides called multiple times on app startup

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#2751]
### Description

The `Window` class has overrides that are invoked when app lifecycle events fire. Here's the calling order of the overrides when a Windows app starts:

- OnCreated
- OnActivated
- OnDeactivated
- OnResumed
- OnActivated

When a Windows app closes (quit), for completeness:

- OnDestroying
- OnStopped
- OnDeactivated

Compare to Android - app start:

- OnCreated
- OnActivated

App close (home):

- OnDeactivated
- OnStopped

### Steps to Reproduce

1. Run the attached sample (on Windows) and put breakpoints in the lifecycle overrides in the `MyWindow` class.

### Expected Behavior

Required lifecycle events/overrides invoked once. Definitely not a suspend/resume cycle when an app first starts.

### Actual Behavior

Some lifecycle events/overrides invoked more than once.

### Basic Information

- Version with issue: Preview 8

### Reproduction Link

[P8MauiApp.zip](https://github.com/dotnet/maui/files/7250940/P8MauiApp.zip)

**Comment by davidbritch** [comment]
I've since realised the Windows lifecycle events that were firing were because of using breakpoints to observe the event order. When I use `Debug.WriteLine` instead, we end up with the following far more sensible overrides being executed on app startup on Windows:

- OnCreated
- OnActivated

`OnDeactivate` is executed the moment focus goes from the app to VS.

So I think this isn't a bug after all, but I'll let @jsuarezruiz or @PureWeen close it.

**Comment by Eilon** [comment]
Yeah deactivate/activate I think is related to Window foreground-ness, so if you're hitting a breakpoint in VS, I would indeed expect the _app_ to see Deactivate, and then when you resume, it will get an Activate.

**Comment by jfversluis** [comment]
Looks like not a bug after all, thanks for being observant though Dave!
