### ISSUE TITLE
[Bug]  Unable to build app over command line

### ISSUE THREAD

**Issue by DominikKulis** [dotnet/maui#2754]
### Description
Unable to build windows app over command line.

### Steps to Reproduce
1. `dotnet new maui -n ButtonDemos`
2. `cd ButtonDemos`
3. `dotnet restore`
4. Uncomment `<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>` in `ButtonDemos.csproj`
5. `dotnet build -t:Run -f net6.0-windows10.0.19041`

### Expected Behavior
Compiled application.

### Actual Behavior
Error: `C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\NuGet.targets(130,5): error : Invalid framework identifier ''. [C:\_projects\ButtonDemos\ButtonDemos.sln]`

Build correctly in Visual Studio 2022 preview. 

### Basic Information
- Version with issue: Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-rc.1.1608
- Last known good version:
- IDE: VS 2022 17.0.0 Preview 4.1
- Platform Target Frameworks: net6.0-windows10.0.19041
- Nuget Packages: None
- Affected Devices: Windows

### Screenshots

![image](https://user-images.githubusercontent.com/49745879/135275934-85e47d09-676a-4a19-8d49-cb5447f6b49f.png)

**Comment by VladislavAntonyuk** [comment]
use the next commands:
```pwsh
msbuild MauiApp1.sln /restore /p:TargetFramework="net6.0-windows10.0.19041"
MakeAppx pack /v /h SHA256 /d "bin\Debug\net6.0-windows10.0.19041\win-x64" /p MyPackage.msix
SignTool sign /fd SHA256 /a /f "MauiApp1_TemporaryKey.pfx" /p "1" MyPackage.msix
```

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.

**Comment by VladislavAntonyuk** [comment]
@Eilon does this command work `dotnet build -t:Run -f net6.0-windows10.0.19041`? I think we still have to use msbuild

**Comment by Eilon** [comment]
@VladislavAntonyuk I believe that WinUI apps (which is what .NET MAUI uses on Windows) can be built only with msbuild.exe for the time being.
