### ISSUE TITLE
[Bug] Cannot hot reload Shell styles

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2761]
### Description

When debugging on Android I'm trying to hot reload from a styles.xaml (ResourceDictionary) changes to the Shell colors. Nothing updates until I rebuild.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/41873/135323629-3f9dd625-4fba-4a3d-af26-c33b1bc8da5e.png">

### Expected Behavior

Updates live.

### Actual Behavior

Doesn't

### Basic Information

- Version with issue: pre9/main
- Platform Target Frameworks: 
  - Android: 28

### Reproduction Link

https://github.com/davidortinau/ControlGallery

**Comment by drasticactions** [comment]
This may be a XET issue and not a MAUI one. 

If you edit the colors directly (Say, changing the Color value of "White" to "Red") it should change, but changing the static resource to a different resource doesn't apply. Changing the value didn't show an update to the property, so XET may not be sending the value for the resource that it should be.

**Comment by davidortinau** [comment]
I cannot change anything directly or via StaticResouces. I'm testing in the DefaultTheme.xaml of WeatherTwentyOne.

```xaml
    <Style x:Key="BaseStyle"
           TargetType="Element">
            <Setter Property="Shell.FlyoutBackground"
                        Value="Green"/>
            <Setter Property="Shell.BackgroundColor"
                    Value="{AppThemeBinding Light={StaticResource NeutralDarker}, Dark={StaticResource Background_Mid}}" />
            <Setter Property="Shell.ForegroundColor"
                Value="White" />
            <Setter Property="Shell.TitleColor"
                Value="White" />
            <Setter Property="Shell.DisabledColor"
                Value="#B4000000" />
            <Setter Property="Shell.UnselectedColor"
                Value="#CC0000" />
            <Setter Property="Shell.NavBarHasShadow"
                Value="False"/>

    </Style>
```

Windows:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/41873/149575491-ee607f42-6e96-4af9-87fb-662e71f2cc5a.png">

**Comment by wenwen60** [comment]
Reproduce on windows with VS2022 17.2.0 Preview 2.0 [32215.517.main], attach repro sample
[2761.zip](https://github.com/dotnet/maui/files/8195259/2761.zip).

**Comment by etvorun** [comment]
@Redth, @davidortinau, @chabiss  root issue is #9526, which might require servicing

**Comment by StephaneDelcroix** [comment]
@drasticactions to verify the status of this right now. Thanks Tim

**Comment by drasticactions** [comment]
Checking with the current .NET 6 and 7 MAUI builds in VS Main, Shell Styles should be working for Hot Reload.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/898335/189788578-c95876a1-b0b2-4677-80e8-8206e475f521.png">

The underlying root issue @etvorun should also enable more use cases of divided resource dictionary types being hot reloadable as well, but I do not know the best way to verify that. In any case, I would say this is closed.
