### ISSUE TITLE
[Bug] Title in navigation bar is wrong

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2762]
### Description

When my app first loads, the title displayed in the Navigation bar is the title in AppShell.xaml and not the title of my ContentPage.

```
<?xml version="1.0" encoding="UTF-8"?>
<Shell xmlns="http://schemas.microsoft.com/dotnet/2021/maui" 
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       xmlns:pages="clr-namespace:ControlGallery.Pages"
       xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
       ios:Page.UseSafeArea="true"
       xmlns:app="clr-namespace:LayoutLab"
       Title="ControlGallery"
       FlyoutBehavior="{OnIdiom Phone=Flyout, Default=Locked}"
       x:Class="ControlGallery.AppShell">
```

![Screenshot_1632940723](https://user-images.githubusercontent.com/41873/135329151-74ea6fcb-6550-46ee-863c-852b90261fd3.png)

If I navigate away and back, it's correct.

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:app="clr-namespace:ControlGallery"
             xmlns:droid="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;assembly=Microsoft.Maui.Controls"
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="true"
             x:Class="ControlGallery.Pages.ImagePage"
             Title="Image">
```

![Screenshot_1632940732](https://user-images.githubusercontent.com/41873/135329168-1d94a4b5-4433-455b-adc9-604783939bf2.png)

### Expected Behavior

If I have a title on my page, that is what should be used.

### Actual Behavior

Title from AppShell is used instead of the page.

### Basic Information

- Version with issue: pre9/main
- Platform Target Frameworks: 
  - Android: 28
  
### Reproduction Link

https://github.com/davidortinau/ControlGallery

**Comment by kristinx0211** [comment]
Not reproducible with Android 11.
