### ISSUE TITLE
[Bug] Flyout item selection not reset

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2764]
### Description

Click around a bit between pages and note that the selected bg color doesn't always reset, so it appears multiple pages are the current page.

<img width="241" alt="image" src="https://user-images.githubusercontent.com/41873/135337831-6c382354-608c-4995-b741-7decdf4638af.png">

### Basic Information

- Version with issue: pre9/main
- Platform Target Frameworks: 
  - Android: 28

### Reproduction Link

https://github.com/davidortinau/ControlGallery

**Comment by kristinx0211** [comment]
Verified repro with Android 11 and the above project.

**Comment by PureWeen** [comment]
This should be fixed on RC1
