### ISSUE TITLE
[Bug] Choose Target OS will create <TargetFramework>net6.0-android13.6</TargetFramework> in Project Property setting. 

### ISSUE THREAD

**Issue by xtuzy** [dotnet/maui#2767]
### Description
When i choose Android as Target OS, at .csproj file, will creat `<TargetFramework>net6.0-android13.6</TargetFramework>` or `<TargetFramework>net6.0-ios31</TargetFramework>`.The default Target OS is iOS, I can't change Target OS to Android by choose, only by delete ios in TargetFrameworks can do.
### Steps to Reproduce

1. Creat default Maui Project
2. open project Property 
3. change Target OS

### Expected Behavior
`<TargetFramework>net6.0-ios13.6</TargetFramework>` or `<TargetFramework>net6.0-android31</TargetFramework>`
### Actual Behavior
`<TargetFramework>net6.0-android13.6</TargetFramework>` or `<TargetFramework>net6.0-ios31</TargetFramework>`
### Basic Information

- Version with issue:
- Last known good version:
- IDE:Microsoft Visual Studio Community 2022 Preview 17.0.0 Preview 4.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![sharex-20210930113957](https://user-images.githubusercontent.com/17793881/135383883-49c34e2e-e6b0-4d3e-bec3-e0763b91f17b.png)
![sharex-20210930114005](https://user-images.githubusercontent.com/17793881/135383892-5cb69aa3-3082-4b23-820b-332b19803142.png)

**Comment by jfversluis** [comment]
Hey there @xtuzy are you still running into this with all the latest bits?

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
