### ISSUE TITLE
Need list of API's for Control.Layout

### ISSUE THREAD

**Issue by RanjithkumarSyncfusion** [dotnet/maui#2771]
## Summary
Can we except the following methods and overrides for Maui.Controls.Layout in feature release.
* RaiseChild
* LowerChild
* ShouldInvalidateOnChildAdded
* ShouldInvalidateOnChildRemoved

## Intended Use Case
We need these methods to implement Interaction related feature. When tried manually removing and inserting child touches getting interrupted.

**Comment by hartez** [comment]
We have not yet determined if we are going to add RaiseChild/LowerChild to the new layout system, or simply add a z-index property. We'll know more after we've explored z-index (see #3285).

At the moment, we have no plans to add ShouldInvalidateOnChildAdded/ShouldInvalidateOnChildRemoved - neither method makes sense with the new layout system.
