### ISSUE TITLE
[Bug] Intellisense does not work with the Background property

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#2775]
### Description

Intellisense does not work with the Background property.

### Steps to Reproduce

1. Create a .NET MAUI App.
2. Set the Background property to any View, for example a Grid.

### Expected Behavior

Intellisense suggest a color list (to use a SolidColorBrush) like happens with the BackgroundColor property.

### Actual Behavior
Intellisense does not suggest a color list (to use a SolidColorBrush) like happens with the BackgroundColor property.

### Basic Information

- IDE: VS2022 Preview 5

### Workaround

Use BackgroundColor property.

**Comment by Amir-Care** [comment]
Not repro on VS version 17.2.0 Preview 2.0 [32219.17.main]
