### ISSUE TITLE
[Bug] Wrong default colors in TabbedPage

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#2776]
### Description

Wrong default colors in TabbedPage.

### Steps to Reproduce

1. Create a .NET MAUI App using a TabbedPage.

### Expected Behavior
![image](https://user-images.githubusercontent.com/6755973/135468107-52bd69d8-b635-4728-9853-6f815d0bd475.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/6755973/135464639-c68af2cb-b761-4a22-af7d-d42cb51088fd.png)

### Basic Information

- IDE: Visual Studio 2022 Preview 5
- Platform Target Frameworks: 
  - Android 11

**Comment by VincentBu** [comment]
@jsuarezruiz Would you like to share your code or xaml?

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz Would you like to share your code or xaml?

Sure, let me create a sample with the latest Preview and attach it (if still happens).

**Comment by jsuarezruiz** [comment]
No longer happens on main branch.
