### ISSUE TITLE
[Bug] Scroll view scroll x position does not working on horizontal orientation 

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#2777]
### Description

- I was created the custom layout that placed inside the horizontal orientation scroll view and check whether the scroll view is not positioned 0 then move to 0 position and the scroll view scroll x position is always 0.

### Steps to Reproduce

1. Create a layout inside the scroll view with horizontal orientation
2. Check the scroll x position and if not 0 then move to 0.
3. But it always return 0 and it working fine in vertical orientation scroll y position

### Expected Behavior

- Scroll view scroll x position will return the scrolled position.

### Actual Behavior

- Scroll view scroll x position always return value 0.

**Replication Sample:** [MauiIssue.zip](https://github.com/dotnet/maui/files/7260129/MauiIssue.zip)

**Working fine for vertical orientation:**  

https://user-images.githubusercontent.com/44917578/135472181-e2f9f328-85ab-45e9-8c02-69c30cf8aaac.mp4

**Issue replication for horizontal orientation:**  

https://user-images.githubusercontent.com/44917578/135472259-3442b871-da1e-498b-acfc-61a782ed21e5.mp4

**Comment by Sasikumar3595** [comment]
@hartez ,

We tried to fix the issue by implementing the native scroll view to get the scroll position, but the android native view (MauiScrollView) also returns the wrong value. It is working fine on a vertically scrollable view.

**Comment by Sasikumar3595** [comment]
@hartez ,

Any update on this?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 2.0. Can repro on android platform with sample project.
[MauiIssue.zip](https://github.com/dotnet/maui/files/7260129/MauiIssue.zip)

**Comment by davidortinau** [comment]
Tested with 8.0 SR1 and this no longer repros. `ScrollToStart()` resets the scroll position as expected.

 

https://github.com/dotnet/maui/assets/41873/9e506ac3-cfa8-4464-b6ef-dd615cd40500
