### ISSUE TITLE
<!-- Thanks for reporting issues of Telegram Messenger for iOS!

### ISSUE THREAD

**Issue by Mahfouz0** [dotnet/maui#2785]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
when someone replies to your voice message you cant see what message someone replies to.

### Expected Behavior
the message will get lighter and you can see what massage someone replies to

### Actual Behavior
the program sends you to a place of message, but it doesn't show specific massage. i mean that massage doesn't become lighter. But it worked before one of updates of telegram.

### Steps to Reproduce
1. turn on black theme
2. send some voice massages
3. reply to one from another account
4. press "voice massage" in replied massage to and you can see that the current massage doesn't become lighter.

### Environment
**Device:** `iPhone 11`

**iOS version**: `14.6`

**App version:** `7.9.2`

__Originally posted by @h1lary7 in https://github.com/TelegramMessenger/Telegram-iOS/issues/605__

**Comment by jsuarezruiz** [comment]
Seems like an error choosing the repo?
