### ISSUE TITLE
Support to get drag and drop position from DragEventArgs

### ISSUE THREAD

**Issue by KarthikRajaAKR** [dotnet/maui#2793]
## Summary
In Maui DragEventArgs there is no support to get dragging or drop position. If you look at the native platforms, all having support to get drag points but Maui DragEventArgs has limited support than native platforms.

## API Changes
DragPoint in DragEventArgs

## Intended Use Case
Consider a calendar month view, here each date cell is drawn and not a separate cell.
Here if we want to drag an event from one date to another date, we can get the dropping date with the help of drop point.

## Additional Info
I further analyzed on Maui source and found this could be so easy to provide an extra parameter for drag point.

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Platform/Android/DragAndDropGestureHandler.cs

Native DragEvent class is having support to get drag point using GetX() method, similar for iOS and windows platforms.

Hoping to get it soon.

**Comment by slab99** [comment]
Any idea on when it is going to be worked on for a coming release?
I would expect the DragEventArgs to have a GetPosition to decide if we accept a Drop inside a partial region of a view.

**Comment by morganwu** [comment]
Any progress on this one? Thanks.
We are trying to implement a workflow designer in a cross platform desktop app, really need to know where the node is put after been dropped.

**Comment by Nijamudeen-Mohamed** [comment]
Could you please share us the status of this?

**Comment by akshayamantya** [comment]
Any updates on  - will this be implement this anytime soon?

**Comment by saiganesh-sakthivel** [comment]
any update @jfversluis

**Comment by acaliaro** [comment]
@jfversluis this is an important request and seems not so difficult to implement. Can you help to have this asap? Thanks

**Comment by jfversluis** [comment]
Unfortunately nothing to share right now

> seems not so difficult to implement.

Feel free to help us out with a PR!

**Comment by acaliaro** [comment]
> Unfortunately nothing to share right now
> 
> > seems not so difficult to implement.
> 
> Feel free to help us out with a PR!

My friend, I'd like to propose a PR, but my skills are very poor (as you must have realized all these years :)).

It seemed to me that @KarthikRajaAKR had clear ideas on how to do it... maybe he could lend a hand.

**Comment by acaliaro** [comment]
@Redth https://github.com/dotnet/maui/milestone/42 what does it mean?
can I already test now with the preview of .net 8?

**Comment by jsuarezruiz** [comment]
I've been reviewing and seeing possibilities. It is really possible to implement on all platforms.

The changes would be:
- Add Point **Position** in `DragStartingEventArgs` and `DragEventArgs`.

Questions:
- Should it be a property or a method like in WinUI? In WinUI we have the GetPosition method. https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.dragstartingeventargs.getposition?view=winrt-22621
- Should the position always be relative to the View from where the Drag starts, or if it is changed to the View where the Drop will be made, does the position become relative to it?
