### ISSUE TITLE
[Bug] (Android)  Entry control returns cursor when typing to the beginning after each character typed in

### ISSUE THREAD

**Issue by I4-PJ** [dotnet/maui#2798]
### Description

Cursor is moved to starting position of the text field after each character typed.

### Steps to Reproduce

1. Create default MAUI app via template
2. Add Entry control to the MainPage.xaml
`        <Grid RowSpacing="25" RowDefinitions="Auto,Auto,Auto,Auto,*">

            <Entry Text="Test"/>

            <Label 
                Text="Hello, World!"
                Grid.Row="0"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />

            <Label 
                Text="Welcome to .NET Multi-platform App UI"
                Grid.Row="1"
                SemanticProperties.HeadingLevel="Level1"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />

            <Label 
                Text="Current count: 0"
                Grid.Row="2"
                FontSize="18"
                FontAttributes="Bold"
                x:Name="CounterLabel"
                HorizontalOptions="Center" />

            <Button 
                Text="Click me"
                FontAttributes="Bold"
                Grid.Row="3"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />

            <Image Grid.Row="4"
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                WidthRequest="250"
                HeightRequest="310"
                HorizontalOptions="Center" />

        </Grid>`

3. Run in simulator or at device
4. Try to type into Entry with any keyboard

### Expected Behavior
Characters are typed one after each other in sequence as typed
### Actual Behavior
After each character the cursor is moved back to the beginning
### Basic Information

- Version with issue:
- Last known good version: MAUI Preview 7
- IDE: VS2022 4.1
- Platform Target Frameworks:
  - Android: 10

**Comment by drasticactions** [comment]
That issue should be fixed with https://github.com/dotnet/maui/pull/2638
