### ISSUE TITLE
[Bug] Layout width measure issue with margin

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2808]
### Description

`Margin="0"`

![image](https://user-images.githubusercontent.com/41873/135668717-4f6c5dd6-b414-48e0-97ab-94a66b218b75.png)

`Margin="15"`

Sets the margin on the left, but the inner grid doesn't resize and the image button (grey box to the right) on the right goes offscreen.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/41873/135668698-fb193616-8c03-4cd4-a29e-393507004e3c.png">

```
<ScrollView>
        <VerticalStackLayout Spacing="25"
                             Margin="15">
            <Label 
                Text="Packing"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32" />

            <GridLayout ColumnDefinitions="40,*,40">
                <CheckBox/>
                <Entry GridLayout.Column="1" Placeholder="Add a task"/>
                <ImageButton GridLayout.Column="2"/>

            </GridLayout>
        </VerticalStackLayout>
    </ScrollView>
```

### Expected Behavior

The grid should size to the available content width of the parent container.

### Actual Behavior

It sizes as if the entire width of the screen is available and then goes offscreen.

### Basic Information

- Version with issue: pre9/main
- Platform Target Frameworks: 
  - Android:  28

**Comment by hartez** [comment]
Fixed for Preview 10.
