### ISSUE TITLE
[Bug] Padding on container clips children content

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2809]
### Description

Padding of zero you can see the image button (grey box) on the right.

![image](https://user-images.githubusercontent.com/41873/135669864-a1448cd7-cb98-4db8-8d88-391e0a288768.png)

Padding of 15 on the container pads from the left, but crops the content to the right. 

![image](https://user-images.githubusercontent.com/41873/135669857-c8c5dbc8-1f2d-43bf-b1a8-283f1b4e89a5.png)

```
<ScrollView Padding="0">
        <VerticalStackLayout Spacing="25"
                             Padding="15"
                             >
            <Label 
                Text="Packing"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32" />

            <GridLayout ColumnDefinitions="40,*,40">
                <CheckBox/>
                <Entry GridLayout.Column="1" Placeholder="Add a task"/>
                <ImageButton GridLayout.Column="2"/>

            </GridLayout>
        </VerticalStackLayout>
    </ScrollView>
```

### Expected Behavior

Padding of container is accounted for when setting the width of the child grid.

### Basic Information

- Version with issue: pre10/main

**Comment by v-xiaofchen** [comment]
Not reproducible with 17.2.0 Preview 2.0 [32209.335.main]  using Android. Here are the results.
Padding of zero
![Picture2](https://user-images.githubusercontent.com/99376012/155284456-71ca9807-fc4f-4be5-b578-1a94d6aa4896.png)
Padding of fifteen
![Picture3](https://user-images.githubusercontent.com/99376012/155284559-e83c7d01-b6f1-482d-8fd3-1505251178d0.png)
attached the repro sample
[#2809.zip](https://github.com/dotnet/maui/files/8122853/2809.zip)
