### ISSUE TITLE
[Enhancement] Allow apps to be programmatically exited

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#2814]
## Summary

This is primarily for desktop apps, but also for some mobile configurations. Apps should be able to trigger the quit operation and terminate safely.

For things like Windows, this is easy, but on some platforms (Android) this requires a bit more work and might need checks with OS guidelines.

For example: https://github.com/dotnet/maui/pull/2653#discussion_r714906973

@AmrAlSayed0:

> There seems to be a kind of consensus that [ActivityManager.AppTask.finishAndRemoveTask()](https://developer.android.com/reference/android/app/ActivityManager.AppTask.html#finishAndRemoveTask()) can be used to end the task of the current Application
> 
> It will go something like this
> ```csharp
> // AppTasks is a static property/method that gets the tasks of the current Application
> foreach (var appTask in ActivityManager.AppTasks)
> {
>     appTask.FinishAndRemoveTask();
> }
> ```
> or a less aggressive approach is to call [finishAffinity()](https://developer.android.com/reference/android/app/Activity#finishAffinity()) on the main/all activities.

**Comment by jfversluis** [comment]
I think especially on iOS it's against guidelines and if the reviewer picks up on it, your app will be denied to the App Store.

See: https://developer.apple.com/library/archive/qa/qa1561/_index.html but also this one stating that this is not mentioned anymore in newer Apple guidelines: https://developer.apple.com/forums/thread/672098

Something to be aware of though.

**Comment by mattleibow** [comment]
Closing this for now as iOS/Android apps are not really allowed to quit themselves according to guidelines. However, this does not prevent anyone from implementing this themselves if they wish.

If these rules change, please open a new issue.
