### ISSUE TITLE
[Bug] Cannot put files in Platforms platform folders

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2820]
### Description

Moving over Effects code to single project I cannot just put files in their respective platform folders. 

 
 Image Build Action
One or more values are invalid. Cannot add 'Platforms\Android\Effects\ParticleEffect.cs' to the project, because the path is explicitly excluded from the project (C:\Users\davidortinau\.nuget\packages\microsoft.maui.controls.build.tasks\6.0.101-preview.10.1824\build\Microsoft.Maui.Controls.SingleProject.targets (66,5)).

I expect to be able to put Android files and resources in the Android folder and have them build for me. 

### Actual Behavior

Build task error

### Basic Information

- Version with issue: pre10

**Comment by Eilon** [comment]
How did you move the file? Was the project open in VS and you drag/dropped it, and VS showed an error? Or some other gesture?

**Comment by davidortinau** [comment]
I don't recall how I moved it, probably just via File Explorer. The error occurs at build. I did manually clean up the csproj bc the proj system seems to always want to add stuff that isn't needed.

**Comment by VincentBu** [comment]
@davidortinau would you like to provide more detail about repro steps? It would be better if there is source code.

**Comment by v-longmin** [comment]
@davidortinau could you share more detail about repro steps? It would be better if there is source code.
