### ISSUE TITLE
[Bug] Cannot add an AndroidResource to single project

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2821]
### Description

I made a drawables folder in the expected place within Android and put a file there. I couldn't choose AndroidResource from the property panel. It's not an option. 

### Expected Behavior

I have a clear path to move Android resources into a single project. 

### Actual Behavior
 I'm lost

### Basic Information

- Version with issue: pre10

**Comment by pictos** [comment]
@davidortinau this is expected behavior, you can't select AndroidResource in build actions, but that resource should be available for you. As you can see [here](https://youtu.be/bWdilOWAEt4?list=PLfbOp004UaYVq2Dk8FaYCI8e_vdVkP_wl&t=886)

**Comment by davidortinau** [comment]
Well, I'm glad to know the resource will get picked up, but I still think the build action should reflect that it's an AndroidResource.

**Comment by wenwen60** [comment]
Not repro in VS2022 17.2.0 Preview 2.0 [32215.517.main], AndroidResource can be set.
