### ISSUE TITLE
[Bug] Resizetizer - SVG with gradients does not work

### ISSUE THREAD

**Issue by pablolop002** [dotnet/maui#2825]
### Description

`
Gravedad | Código | Descripción | Proyecto | Archivo | Línea | Estado suprimido
-- | -- | -- | -- | -- | -- | --
Error | MAUI0000 | System.Exception: In C:\Users\pablo\source\repos\MauiApp\MauiApp\Resources\appiconfg.svg:<stop> is not supported<stop> is not supported<stop> is not supported<stop> is not supported<stop> is not supported<stop> is not supported   en Svg2VectorDrawable.Svg2Vector.ParseSvgToXml(String inputSvgFilename, Stream outputStream) en /Users/runner/work/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2Vector.cs:línea 776   en Svg2VectorDrawable.Svg2Vector.Convert(String inputSvgFilename, String outputXmlFilename) en /Users/runner/work/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2Vector.cs:línea 759   en Microsoft.Maui.Resizetizer.AndroidAdaptiveIconGenerator.Generate() en D:\a\1\s\src\SingleProject\Resizetizer\src\AndroidAdaptiveIconGenerator.cs:línea 73   en Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessAppIcon(ResizeImageInfo img, ConcurrentBag`1 resizedImages) en D:\a\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:línea 132   en Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass26_0.<ExecuteAsync>b__0(ResizeImageInfo img) en D:\a\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:línea 88   en Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) en D:\a\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:línea 21 | MauiApp | C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.100-rc.1.1608\targets\Microsoft.Maui.Resizetizer.targets | 450 |  

<br class="Apple-interchange-newline">`

System exception: <stop> is not supported when building. As far as I know, this tag is used when there is a gradient. 

### Steps to Reproduce

1. Use a SVG file with gradients.
2. Build.

### Expected Behavior

Successful building.

### Actual Behavior

System exception.

### Basic Information

- Version with issue: Preview 8
- Last known good version: -
- IDE: VS 2022 Preview 4.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by profix898** [comment]
I filed an issue for this against the original Svg2VectorDrawable.Net project (which is used here internally by Resizetizer):
https://github.com/Redth/Svg2VectorDrawable.Net/issues/3

The issue contains at least a little more info and a very simple SVG file to reproduce the problem.

**Comment by shimingsg** [comment]
@pablolop002 , I just have a try with your gradient svg. update the demo.svg file name to appicon.svg. what I ran into as following，the icon generated. verified on Android 12 and iOS 15.2 while I compile with VS 17.2.0 Preview 2.0 [32303.288.main]
![image](https://user-images.githubusercontent.com/20982341/156689533-47351daa-7544-4ebd-8361-038cfbdd5731.png)

**Comment by mattleibow** [comment]
This should be fixed in Preview 14. Please open another issue if there are still problems.
