### ISSUE TITLE
[Enhancement] x:Double's OnIdiom

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2830]
Hi,

Please make it possible to add OnIdiom for x:Double and other similar types like this as an example:

```
<Application.Resources>
     <x:Double x:Key="HeaderHeight">{OnIdiom Phone=200, Tablet=400}</x:Double>
 </Application.Resources>

```

Thanks,
Jassim

**Comment by jfversluis** [comment]
I guess you could work around this by using it in a style, which seems the most obvious use-case.

```xml
<Style TargetType="MyHeader">
    <Setter Property="HeightRequest" Value="{OnIdiom Phone=200, Tablet=400}" />
</Style>
```

Closing this for now as I don't see a lot of traction for this enhancement. Maybe writing a more extensive description about why you want this and how you would use this will help with that.
