### ISSUE TITLE
[Bug] Frame content does not update from Device.StartTimer callback method for Windows app

### ISSUE THREAD

**Issue by anotherlab** [dotnet/maui#2832]
### Description
When the Text property of a Label control that is wrapped inside a Frame control and the Text property is bound to a ViewModel and the ViewModel is updated using a Device.StartTimer() callback method, the Label control is not visible while the callback is executing.

### Steps to Reproduce

Create a label on a page using XAML like the following
```xaml
<Frame Padding="0" BackgroundColor="#5c5c5c" Margin="4,0,4,10" HasShadow="True">
  <Frame Padding="0" BackgroundColor="#d6d6d6" Margin="4,4,4,4" >
    <Label Text="{Binding ElapsedTime}" Style="{StaticResource numericStyle}" />
  </Frame>
</Frame>
```
ElapsedTime property is defined in a ViewModel
```cs
private string elapsedTime;
public string ElapsedTime
{
    get {  return elapsedTime; }
    set {  SetProperty(ref elapsedTime, value);}
}
```
Add code to start and stop a StartTimer loop that updates that property.
```cs
private void Start()
{
    stopwatch.Restart();

    IsRunning = true;

    Device.StartTimer(TimeSpan.FromMilliseconds(100), () =>
    {
        Device.BeginInvokeOnMainThread(() =>
        {
            ElapsedTime = stopwatch.Elapsed.ToString(@"mm\:ss\.fff");
        });
        return isRunning;
    );
}
private void Stop()
{
    stopwatch.Stop();
    IsRunning = false;
}
```
### Expected Behavior
The label control would display the elapsed time while the StartTimer callback method is executing.

### Actual Behavior
For the Windows platform, the label control is blank or missing until after the StartTime callback completes.  If you resize the app while the callback is being called, the label control will flash on the screen
Works as expected under Android (not tested for iOS)

### Basic Information

- Version with issue: 6.0.100-rc.1.21463.6
- Last known good version:
- IDE: VS 2022 Preview 4.1
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: Target SDK 31
  - WinUI:  6.0.0-rc.1.21451.3
- Android Support Library Version: N/A
- Nuget Packages:
  - CommunityToolkit.Maui 1.0.0-pre2
- Affected Devices: N/A

### Screenshots

![mauistopwatch](https://user-images.githubusercontent.com/1191188/135956593-d23c8e05-ee1a-412a-be6e-5ec1a4bc8e57.gif)

### Reproduction Link

[Sample project](https://github.com/anotherlab/stopwatch-maui) 

### Workaround
Remove the Frame controls

**Comment by hartez** [comment]
Fixed by #2677.
