### ISSUE TITLE
the debug was canceled. please create an android emulator to debug the application.

### ISSUE THREAD

**Issue by poornimanayar** [dotnet/maui#2838]
Trying to run a MAUI Blazor App on Android emulator and get this message 

the debug was canceled. please create an android emulator to debug the application.

**Comment by jfversluis** [comment]
Hey there @poornimanayar thanks for the report! Unfortunately it doesn't have much detail. Also, the error message seems pretty self-explanatory. Go to Tools > Android Device Manager and setup an emulator first that you can use to run the application.

I'm closing this one, if you still have an issue with this information, please open a new issue and make sure you fill out the issue template with a bit more details on your development environment and what you have already tried etc.
