### ISSUE TITLE
Mangled UI rendering in BlazorWebView on Android

### ISSUE THREAD

**Issue by danroth27** [dotnet/maui#2848]
I'm seeing some mangled overlapping UI rendering in a BlazorWebView on Android:

![image](https://user-images.githubusercontent.com/1874516/136142058-5cb86881-e79a-4ab1-8791-517e841988e4.png)
![image](https://user-images.githubusercontent.com/1874516/136142030-8a35854b-b20f-4be8-bb3c-a81cb1cd9919.png)

https://github.com/danroth27/blazorweather/tree/net6rc2

6.0.100-rc.2.21478.25

@Eilon

**Comment by danroth27** [comment]
@Eilon I've never seen it happen on desktop or web, but it also doesn't always happen on Android with the same app.

**Comment by javiercn** [comment]
@danroth27 gave this a try and it seems to work fine for me on the current bits (6.0 + latest Maui)

<img width="383" alt="image" src="https://user-images.githubusercontent.com/6995051/155346905-b1788a77-579c-4e68-b423-3aac05443a9c.png">

I did try resizing the emulator and it works as expected

<img width="155" alt="image" src="https://user-images.githubusercontent.com/6995051/155347042-8b4a0648-8bf5-4dd6-8c21-5a1eaaff81bd.png">

**Comment by Eilon** [comment]
@javiercn even for @danroth27 the repro was not consistent, so who knows...
