### ISSUE TITLE
[Bug] [Mac] Grouped collections views does not scroll vertically

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#2850]
### Description
In MacOS, given a grouped collectionview and setting the ItemsLayout to VerticalGrid has no effect.
It does not scroll, neither organize items on grid.

**Comment by v-longmin** [comment]
Could you share your repro project/solution, thanks?

**Comment by VincentBu** [comment]
Hi @juanlao , I run this project on Mac and it scrolled. 
[MauiApp2.zip](https://github.com/dotnet/maui/files/8251985/MauiApp2.zip)

**Comment by jfversluis** [comment]
No response to this for a long time, going to assume this is fixed. If not, please open a new issue with detailed information. Thanks!
