### ISSUE TITLE
[Bug] Path doesn't render

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2860]
### Description

This path isn't rendering at all. Works in Xamarin.Forms.

![image](https://user-images.githubusercontent.com/41873/136285118-3964a748-c587-4bd6-b3e4-5da43787a389.png)

```
<Label Text="Path"
        Margin="0,80,0,0"
        StyleClass="Headline" />
<BoxView StyleClass="HRule"/>

<Path 
    Fill="{StaticResource PrimaryBrush}"
    Data="M50,0 L50,50 L25,50 C11.1928813,50 0,38.8071187 0,25 C0,11.3309524 10.9701429,0.224119049 24.5865793,0.00334928573 L25,0 L50,0 Z" />
```

Should look like (dif color):

![image](https://user-images.githubusercontent.com/41873/136286001-2876e82c-db11-42db-9f90-7dc959f07bad.png)

### Basic Information

- Version with issue: preview.10.1844

**Comment by mattscheffer** [comment]
Verified repro using 17.2.0 Preview 1. Tested with Android 11. Repro project here:
[2860.zip](https://github.com/dotnet/maui/files/8145492/2860.zip)
