### ISSUE TITLE
[Bug] While measuring, grid children does not return the desired size.

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#2863]
### Description

I have added layout in below structure. When we try to measure child grid, it returns complete size of parent grid instead of required size for label. 

Same issue reproduce in AbsoluteLayout too.

```
 <local:GridExt>
        <Grid>
            <Label Text="Text" TextColor="Black"/>
        </Grid>
    </local:GridExt>
```

```
public class GridExt : Grid
    {
        protected override Size MeasureOverride(double widthConstraint, double heightConstraint)
        {
            if (Children.Count > 0)
            {
                Size size = this.Children[0].Measure(widthConstraint, heightConstraint);
                Debug.WriteLine("Width : " + size.Width.ToString() + " Height : " + size.Height.ToString());

                size = this.Children[0].ComputeDesiredSize(widthConstraint, heightConstraint);
                Debug.WriteLine("Width : " + size.Width.ToString() + " Height : " + size.Height.ToString());

            }
            return base.MeasureOverride(widthConstraint, heightConstraint);
        }
    }
```

### Steps to Reproduce

1. Run the sample
2. See the results in output window
3. Child returns parent whole size instead of required size. 

### Expected Behavior

Child grid have to return, its required size. 

### Actual Behavior

Child grid returns parent available size. 

### Basic Information

Visual Studio : Visual Studio 2022 Preview
Maui : Maui Preview 8

### Screenshots

![image](https://user-images.githubusercontent.com/32541057/136330982-89d27a5b-6c01-46dc-a320-ecfb6b1a2cd7.png)

### Sample
[MauiMeasureSample.zip](https://github.com/dotnet/maui/files/7299328/MauiMeasureSample.zip)

**Comment by hartez** [comment]
The root Grid is using the default RowDefinition and ColumnDefinition, which are GridLength.Star. The inner Grid is using the default RowDefinition and ColumnDefinition, which are GridLength.Star. So the inner Grid takes up the full space available. The size of the content (the Label) doesn't come into play in this scenario.

If you want the size of the Label, I'd suggest calling Measure on the Label. Alternatively, you can set the Row and Column definitions to Auto for both Grids, which will size them to the size of their content.

**Comment by MuneeshKumarG** [comment]
We don't know the inner elements in GridExt. So, we are unable to iterate the exact measurable content. 

And unable to set each time with below code. 

```
<Grid>
                                            <Grid.RowDefinitions>
                                                <RowDefinition Height="Auto"/>
                                            </Grid.RowDefinitions>
                                            <Grid.ColumnDefinitions>
                                                <ColumnDefinition Width="Auto"/>
                                            </Grid.ColumnDefinitions>
                       
                                            <Label Text="Grid" TextColor="Black"/>
                                        </Grid>
```

So, please update us the proper way to measure grid children.
