### ISSUE TITLE
[Bug] [Android] CollectionView inside a VerticalStackLayout inside a Shell doesn't render any items

### ISSUE THREAD

**Issue by migueBarrera** [dotnet/maui#2865]
### Description
I you have a shell with a page and a collectionView inside a VerticalStackLayout in this page , the collectionView doesn't render any item.

You must set items in an async method (api call).

PD: If you remove VerticalStackLayout or Shell, the collectionview renders all items.

### Steps to Reproduce

1. Create a shell with tabs
2. Create a Page with a VerticalStackLaoyout with a CollectionView
3. Put the Page inside de Shell.
4. Set items in async method(simulate server api call), for example, onAppearing method.

### Expected Behavior
Any items is render

### Actual Behavior
Render all items
### Basic Information

- Version with issue:
- Last known good version: any
- IDE: VS 2022 17.0.0 PReview 4.1
- Platform Target Frameworks: 
  - Android:  
  - UWP:   
- Android Support Library Version: 

### Reproduction Link

[TestAsyncMethodList.zip](https://github.com/dotnet/maui/files/7302558/TestAsyncMethodList.zip)
In this sample, any items is render, but if you remove the VerticalStackLayout, the collectionView renders all items.

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by Redth** [comment]
This is fixed in the upcoming RC1 release.

![image](https://user-images.githubusercontent.com/271950/161121300-6681cff7-fb0a-4837-8f2a-c9c325ac0cdf.png)
