### ISSUE TITLE
[Bug] WinUI: Entry.Text is always null

### ISSUE THREAD

**Issue by phoneyman** [dotnet/maui#2877]
### Description
The Text field of the Entry element is always null
### Steps to Reproduce

1.  Create a ContentPage with an Entry element
2. Run the project and enter text into the Entry element
3. In the code behind, try to retrieve the text that was entered from the Text field

### Expected Behavior
The text entered would be retrieved from the Text field

### Actual Behavior
The Text field is null

### Basic Information
.NET MAUI Preview 8
Target Framework: net6.0-windows10.0.19041
IDE: Visual Studio 2022 Preview 4.1

### Code
XAML:
<img width="736" alt="EntryTextNullXAML" src="https://user-images.githubusercontent.com/29587719/136478478-ffb77bd6-f7fc-46ec-894d-51b90454d734.PNG">

Code behind:
<img width="505" alt="EntryTexTNullCode" src="https://user-images.githubusercontent.com/29587719/136478499-30b34c2c-2193-4b6a-9643-6465cfbb8ff2.PNG">

Output:
<img width="901" alt="EntryTextNullOutput" src="https://user-images.githubusercontent.com/29587719/136478670-b363dc37-062b-49d2-a1ef-9f3683048fc3.PNG">

**Comment by svedmark** [comment]
Seems like Entry is all sorts of broken.  (I have a workaround going on this other issue since I started looking at why binding didn't work)

#2580

**Comment by NogginBox** [comment]
While we're waiting for the fix to come out in a release: A temp fix you can add in your code if you're trying to get at the text property in your code behind is:

```
if (Device.RuntimePlatform == Device.UWP)
{
    MyEntry.Text = (string)UriToScanEntry.Handler.NativeView.GetType().GetProperty("Text").GetValue(MyEntry.Handler.NativeView);
}
```

**Comment by hartez** [comment]
This is fixed in preview 10.
