### ISSUE TITLE
Button text not rendered properly in RTL flow direction

### ISSUE THREAD

**Issue by KarthikRajaAKR** [dotnet/maui#2880]
### Description
Button text sequence changes while set RTL flow direction.

I'm using below code to find button text
`DateTime.Now.ToString("d MMM") + " - " + DateTime.Now.Date.AddDays(7).ToString("d MMM yyyy")`

Actual Text from above code - **8 Oct - 15 Oct 2021**
LeftToRight (Default)- Working fine
![image](https://user-images.githubusercontent.com/41435300/136543241-109e5e4a-eb1c-40f3-894d-c2111adc10b2.png)

RightToLeft - Text sequence changes
![image](https://user-images.githubusercontent.com/41435300/136543058-72d15002-c6eb-4337-9dc0-88b01dafdc34.png)

### Steps to Reproduce
1. Ues below code in simple sample, you will get the issue

**Xaml**
`  <StackLayout Margin="50">
        <Button x:Name="headerDate" WidthRequest="200" HeightRequest="50"/>
    </StackLayout>`

**C#**
`this.headerDate.Text = DateTime.Now.ToString("d MMM") + " - " + DateTime.Now.Date.AddDays(7).ToString("d MMM yyyy");`

### Expected Behavior
The button text should render as normal.

### Actual Behavior
Text sequence changes with RTL.

### Basic Information

- Last known good version: No
- IDE: Visual Studio 2022 Preview 4.0
- Platform Target Frameworks: 
  - Android: SDK - 12, API -31
- Nuget Packages: Microsoft.Maui.Dependencies - 6.0.100-rc.1.1608
- Affected Devices: Samsung M35, Mi A1

### Screenshots
Please refer description.

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EYy6iPf979REvr1CLvI5g98BnSeBCQ2QZgyOiArfoQVpKQ?e=tzyss6
