### ISSUE TITLE
[Bug] Not rendering Shadows off-screen controls in ScrollView

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#2881]
### Description

Shadows from off-screen controls in ScrollView are not rendering on Android.

[shadows-issue.zip](https://github.com/dotnet/maui/files/7310990/shadows-issue.zip)

### Steps to Reproduce

1. Get the attached sample.
2. Launch the App in Android emulator or device.
3. Scroll to the bottom.

### Expected Behavior

All the shadows are rendered.

### Actual Behavior

![issue-shadows-droid](https://user-images.githubusercontent.com/6755973/136551672-1d620689-1424-4125-94c1-06018d8bc9e1.gif)

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/ET6ur5T0J6FOlpmxhQgU57MBOK_NvUwBtfrQCKFf1XdeaQ?e=zo5Icf
