### ISSUE TITLE
[Bug] VS 2022 automatic selecting wrong jdk-11

### ISSUE THREAD

**Issue by shirok1** [dotnet/maui#2884]
### Steps to Reproduce

1. Install ms-openjdk-11 with winget
2. Open Visual Studio 2022, go to settings, Xamarin jdk become jdk 11, NO OTHER PLATFORM shown in run menu
3. Manually set jdk to "Microsoft's Mobile OpenJDK Distribution", restart VS, xamarin jdk become 11 automaticly

if startup vs without project and manually set jdk to "Microsoft's Mobile OpenJDK Distribution" before actually open a maui project, run menu works again

### Expected Behavior
no need to manually set jdk

### Actual Behavior
always select an obviously unusable jdk-11

### Basic Information

- Version with issue: Microsoft Visual Studio Community 2022 Preview 4.1 Stock
- Last known good version: idk
- IDE: Microsoft Visual Studio Community 2022 Preview 4.1
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: idk

**Comment by VincentBu** [comment]
Hi @shirok1 , have you tried to click `Tools -> Options -> Xamarin -> Android Settings` then set jdk location?
![image](https://user-images.githubusercontent.com/44959937/158340349-9c62e034-0564-4d58-b7ad-9c177870cacd.png)

**Comment by Redth** [comment]
This was fixed in a more recent preview release.
