### ISSUE TITLE
[Bug]  Labels should have cross thread checking

### ISSUE THREAD

**Issue by stephen-hawley** [dotnet/maui#2887]
### Steps to Reproduce

1. Build a default Maui application and change MainPage.xaml.cs into this code:
```
using System;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Essentials;
using System.Threading;
using System.Threading.Tasks;

namespace AsyncLabels
{
	public partial class MainPage : ContentPage
	{
		int count = 0;

		public MainPage()
		{
			InitializeComponent();
			var task = MakeRelabelTask();
			task.Start();
		}

		private void OnCounterClicked(object sender, EventArgs e)
		{
			count++;
			CounterLabel.Text = $"Current count: {count}";

			SemanticScreenReader.Announce(CounterLabel.Text);
		}

		void Relabeler ()
        {
			Thread.Sleep(8000);
			CounterLabel.Text = "Sleeping first.";
			//MainThread.BeginInvokeOnMainThread(() => CounterLabel.Text = "Sleeping first.");
			Thread.Sleep(200);
			CounterLabel.Text = "Sleeping second";
			//MainThread.BeginInvokeOnMainThread(() => CounterLabel.Text = "Sleeping second");
        }

		Task MakeRelabelTask ()
        {
			return new Task(Relabeler);
        }
	}
}
```
2. Run the app and wait 10 seconds.
3. Click on "Click me"

### Expected Behavior
An exception warning of cross-thread changes to the `Text` property

### Actual Behavior
Android: text doesn't change. Clicking the button changes the text to "Sleeping first."
iOS: text doesn't change. Clicking the button does nothing.
maccatalyst: text doesn't change. Clicking the button does nothing.

When replaced with code to invoke on main thread, it behaves as expected: the text changes on time and the button works.

### Basic Information

- Version with issue: Don't know how to find this - downloaded with .NET 6.0.100-rc.1.21452.4
- Last known good version:
- IDE: none
- Platform Target Frameworks: 
  - iOS:  15.0 simulator
  - Android: 10.0 emulator
  - MacCatalyst: Big Sur 11.6

### Workaround

Make changes to the controls using `BeginInvokeOnMainThread`.

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EaS793eRtoNIoiIQUiCkrBEBiX5qd9P5jQXx1NokFwZI0g?e=9xMscs

**Comment by Redth** [comment]
We don't guard against thread marshalling and require developers to be aware of when this is necessary.
