### ISSUE TITLE
[Bug] Obsolete some of the AutomationProperties?

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#2888]
### Description

The recommendation for MAUI is to use `SemanticProperties` over `AutomationProperties` (where equivalents exist).

`AutomationProperties.Name`, `AutomationProperties.HelpText`, and `AutomationProperties.LabeledBy` seem to only be present for users migrating their apps from Xamarin.Forms. `Name` and `HelpText` have new `SemanticProperties` equivalents, and `LabeledBy` can be replaced by a binding. Therefore, can `Name`, `HelpText`, and `LabeledBy` be labelled with the `Obsolete` attribute? Without that, the doc will have to treat them as no less important than `SemanticProperties` which will result in an awful accessibility story, and user confusion.

**Comment by jfversluis** [comment]
Blocked until #8048 is implemented. Technically not blocked, we can already mark them as obsoleted, but it won't have much effect until the aforementioned issue is implemented.
