### ISSUE TITLE
[Bug] Crash trying to use RefreshView on Android

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#2889]
### Description

If try to use RefreshView on Android, the App crash.

[collectionview-issue.zip](https://github.com/dotnet/maui/files/7313125/collectionview-issue.zip)

### Steps to Reproduce

1. Download the attached sample.
2. Launch on Android device or emulator and navigate to any sample from the Pull to Refresh section.
3. Crash!

### Expected Behavior

The sample works without exceptions.

### Actual Behavior

Crash.

**Comment by shugaoye** [comment]
I have the same problem. RefreshView cannot work on Android, iOS and Windows. 

---

Microsoft Visual Studio Community 2022
Version 17.1.0 Preview 2.0
VisualStudio.17.Preview/17.1.0-pre.2.0+32104.313
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA630
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019   17.1.229.41008
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.1.229.41008
Azure App Service Tools v3.0.0

C# Tools   4.1.0-2.21607.5+4e139d3fdfc73247aece2e29d7abcecd0d4f6464
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.1.10 (65f98f5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2160703+95aa380e1d4fd51f7f032aa44e903c892f6bde89
Provides languages services for ASP.NET Core Razor.

TypeScript Tools   17.0.1203.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-2.21607.5+4e139d3fdfc73247aece2e29d7abcecd0d4f6464
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21561.4+56d49a0f5a876dbadeaf34af91972c7a10de858b
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.1.0.269 (main@be6679a)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.1.0.87 (remotes/origin/main@d50fb5635)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.1.8 (590388a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.99.117 (main/c52e6e6)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@7f1a5ab1
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.37.0@88e12a9
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@35c89dd


Xamarin.iOS and Xamarin.Mac SDK   15.3.0.215 (faa966ba2)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by kristinx0211** [comment]
Verified repro with Android 11 and the above project.

**Comment by jsuarezruiz** [comment]
Have done several test with main branch and seems to work correctly:
![issue-2889](https://user-images.githubusercontent.com/6755973/160594201-678c221d-4568-4692-ac27-79b04b710a79.gif)

However, the images are not loading!. Can debug some exceptions in the `ImageLoaderResultCallback `class.

`An attempt was made to transition a task to a final state when it had already completed.`

@Redth You are reviewing now issues with images and Glide, could you include this sample/case in your tests?, should we maintain this issue with the focus on images or close it and open a new one?
