### ISSUE TITLE
[Bug] CollectionView EmptyView using a View never appears on Android

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#2892]
### Description

CollectionView EmptyView using a View never appears on Android.

![image](https://user-images.githubusercontent.com/6755973/136598883-52ad49da-f38f-4b4b-91da-bdebb7d86668.png)

[collectionview-issue.zip](https://github.com/dotnet/maui/files/7313202/collectionview-issue.zip)

### Steps to Reproduce

1. Download the attached sample.
2. Open the sample in an Android emulator or device.
3. Navigate to the EmptyView sample using a View. Filter the list with something.

### Expected Behavior
Appear the EmptyView.

### Actual Behavior
Non EmptyView is visible.other people while waiting for this issue to be resolved -->

**Comment by kristinx0211** [comment]
Not reproducible with Android 11 and the above project.
