### ISSUE TITLE
Indecipherable exception when loading a MauiImage into an Image view

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#2893]
I'm trying to load an image using 

`ImageSource.FromResource(@"Resources\Images\" + Thumbnail, typeof(App))`

The Build Action of the images is "MauiImage"

There is no exception in the call, but then an exception is thrown and the image is not loaded into the "Image" view

> System.NullReferenceException
>   Message=Object reference not set to an instance of an object.

That's all the exception says. Impossible to know the problem from exceptions like that.

**Comment by PureWeen** [comment]
@arivoir MauiImage files aren't added as resource files inside the assembly. They generate native images that are packaged with the native project. Just set the `Source` property on the Image to the name of the file you are using.

We should still review your exception here to figure out if we can raise a better exception

**Comment by mattleibow** [comment]
The usage of a path inside the resources API probably needs a better exception, but it is unsupported.
