### ISSUE TITLE
[Enhancement] Provide public methods for access to Page.InternalChildren

### ISSUE THREAD

**Issue by Daniellled** [dotnet/maui#2899]
## Summary
If someone wants to extend Page. For example if they wanted to provide a customized Flyout page. When InternalChildren changes it causes an event to be fired that handles measure invalidating etc.

Today Page.InternalChildren is a public api that exist within the Page object. However, the Xamarin Forms documentation (https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.page.internalchildren?view=xamarin-forms) says

> For internal use by the Xamarin.Forms platform.

I would not feel comfortable using Page.InternalChildren for fear one day it could be removed.

## API Changes

Add the following methods

```
public void AddChild(Element e)
{
    InternalChildren.Add(e);
}

public void RemoveChild(Element e)
{
    InternalChildren.Remove(e);
}
```

## Intended Use Case
Create a customized flyout page that provides additional content besides flyout and detail to a native user control.

**Comment by davidbuckleyni** [comment]
Check with @PureWeen he has something already planed this was out topic I think he is asking for shane

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/pull/14132
