### ISSUE TITLE
[Bug] Exception when using ControlTemplate with ContentPresenter

### ISSUE THREAD

**Issue by eliolo** [dotnet/maui#2901]
### Description
Using Visual Studio 2022 preview 4 template for MAUI with modified App.xaml and MainPage.xaml I'm trying to use a ControlTemplate with a ContentPresenter on a nested ContentView but an exception is thrown. Using the ContentTemplate without a ContentPresenter works fine. When using any of the ContentTempaltes directly on the ContentPage, the ContentTemplate is ignored but no exceptions are thrown.

App.xaml:
![App](https://user-images.githubusercontent.com/54113463/136691146-38d24cb6-0f70-46b4-ad5d-8d684478fad4.png)

MainPage:
![MainPage](https://user-images.githubusercontent.com/54113463/136691157-5eb7f93d-1145-4f33-b9ab-6181a5076b22.png)

### Expected Behavior
MainPage displaying App.xaml ControlTemplate content along with MainPage.xaml content in place of ContentPresenter tag:

<img src="https://user-images.githubusercontent.com/54113463/136690136-c591851c-2937-4f95-bba0-3a2461e8b716.png"  width="50%" height="50%" />

### Actual Behavior
System.Exception: 'Handler not found for view Microsoft.Maui.Controls.ContentPresenter.' is thrown.

### Basic Information
- Version with issue: Visual Studio 2022 preview 4 default Maui project template
- Tested on: Android, Windows

### Reproduction Link
https://github.com/VVienerboy/MauiContentPresenter

**Comment by VVienerboy** [comment]
Issue is fixed for ControlTemplate used on ContentView in VS 2022 preview 5, but when used on ContentPage ControlTemplate content still gets ignored. Only the content of MainPage is displayed.

![image](https://user-images.githubusercontent.com/54113463/137953124-c31170e2-8199-4621-871e-84e27c5e7694.png)

**Comment by kristinx0211** [comment]
Not reproducible with Android 11 and the above repro project.
