### ISSUE TITLE
[Bug] IntentFilter WebAuthenticator - Resources+NotFoundException appIcon

### ISSUE THREAD

**Issue by auriou** [dotnet/maui#2902]
Description

I use Microsoft Visual Studio Enterprise 2022 Preview (64 bits) Version 17.0.0 Preview 4.1
  6.0.100-rc.1.21463.6 - C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6

* i set up google authentication with a "WebAuthenticator" 
* i added an android activity class which inherits from "Microsoft.Maui.Essentials.WebAuthenticatorCallbackActivity" with an "IntentFilter" 
* all works, but i have an error in my debug from visual studio when I'm redirected to google authentication (which works).

Here is the error : 

Android.Content.Res.Resources+NotFoundException
  Message=Drawable com.myproject:mipmap/appicon with resource ID #0x7f0c0000

![image](https://user-images.githubusercontent.com/1873587/136847820-93e92192-9ccb-4baa-9d56-5db4f4e66a3b.png)

**Comment by dhabierre** [comment]
Hi,

I've the same issue.
I'm playing with the [.NET MAUI app sample](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=windows).

First, in the OnCounterClicked method, I've wrote:
```cs
private async void OnCounterClicked(object sender, EventArgs e)
{
    var selected = await FilePicker.PickAsync(new PickOptions { PickerTitle = "Select the ZIP file" });
    if (selected != null)
    {
      // TODO
    }
}
```

Then I've added in **Platforms\Android\AndroidManifest.xml**:
```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

Error:
```
System.NullReferenceException: 'The current Activity can not be detected. Ensure that you have called Init in your Activity or Application class.'
```

This seems to fix it (**Platforms\Android\MainActivity.cs**):
```cs
[Activity(...)]
public class MainActivity : MauiAppCompatActivity
{
    protected override void OnCreate(Bundle savedInstanceState)
    {
        base.OnCreate(savedInstanceState);

        Platform.Init(this, savedInstanceState);
    }
}
```

Next execution:
```
Android.Content.Res.Resources+NotFoundException: 'Drawable com.companyname.Vaultage:mipmap/appicon_round with resource ID #0x7f0c0001'
```

Finally I've tried this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="31" />

  <!--Android.Content.Res.Resources+NotFoundException: Message=Drawable com.companyname.Vaultage:mipmap/appicon_round with resource ID #0x7f0c0001-->
  <!--<application android:allowBackup="true" android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round" android:supportsRtl="true"></application>-->
  <application android:allowBackup="true" android:supportsRtl="true"></application>

  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
</manifest>
```

Hope it helps.

**Comment by dhabierre** [comment]
> here is an example which reproduces the error : https://github.com/auriou/MauiWebAuthenticator

Ho great! I'd like to play with WebAuthenticator too :)
But the project does not build on my computer:
```
Error	XA0003	VersionCode 1.0 is invalid. It must be an integer value.
```

To fix it I have to build the **csproj**:
```xml
<ApplicationVersion>1.0</ApplicationVersion>
```
=>
```xml
<ApplicationVersion>1</ApplicationVersion>
```

The rebuild.
It will update:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.companyname.MauiWebAuthenticator" android:versionCode="1.0" android:versionName="1.0.0">
```
=>
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.companyname.MauiWebAuthenticator" android:versionCode="1" android:versionName="1.0.0">
```

Now the emulator has black screen... =)

**Comment by auriou** [comment]
> Finally I've tried this:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <manifest xmlns:android="http://schemas.android.com/apk/res/android">
>   <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="31" />
> 
>   
>   
>   <application android:allowBackup="true" android:supportsRtl="true"></application>
> 
>   <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
>   <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
> </manifest>
> ```
> 
> Hope it helps.

This is perfect it works by removing the attributes "android: icon" and "android: roundIcon"

Thank you

**Comment by shimingsg** [comment]
Glad to see you get project working and close this issue.

**Comment by thomiel** [comment]
Does everyone who wants web authentication really need to run into this issue? I think you prematurely closed this. Either the maui project template or the Maui.Essentials Samples need to be fixed.
