### ISSUE TITLE
[Bug] Entry boxes double enter keys

### ISSUE THREAD

**Issue by stephen-hawley** [dotnet/maui#2908]
### Steps to Reproduce

1. Start with a default maui project (`dotnet new maui --name SomeProj`)
2. Change the second grid row from a `Label` to an `Entry` with the following contents
```
<Entry 
   Placeholder="enter text here" PlaceholderColor="Gray"
   Grid.Row="1"
   FontSize="18"
   HorizontalOptions="Center"
   x:Name="TextBox"/>
```
3. run the project on the Android emulator (`dotnet build -t:Run -f net6.0-android`)
4. Click on the Entry and type.

### Expected Behavior
The characters typed should appear in the order typed and leave the insertion point after the character entered.

### Actual Behavior
If you type `a` you get `aa` and insertion point ends up at the front of the line.
If you move the entry point to the end and type a character, it inserts one character at the end then jumps the insertion point to the beginning and enters another character.

### Basic Information

- Version with issue: current
- Last known good version:
- IDE: n/a
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by kristinx0211** [comment]
Not reproducible with Android 11.
