### ISSUE TITLE
[Bug] Xaml Live Preview option not showing up

### ISSUE THREAD

**Issue by ShrutiJaiswal1494** [dotnet/maui#2924]
Hi,

I was following the [documentation ](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=windows)to build my first App in MAUI. However, while running the project in debug mode on Windows I do not see the `Xaml Live Preview` Window. I have tried selecting the various options in the `Xaml Hot Reload` tab but nothing has worked yet. Also, any changes that I make to the XAML files are not getting reflected in the Local App even if I explicitly click on the hot reload button. 

![image](https://user-images.githubusercontent.com/79670853/137050796-9dfb042e-6f1d-46c2-ad57-be40ac46506a.png)

**Comment by v-xiaofchen** [comment]
Not reproducible with 17.2.0 Preview 2.0 [32209.335.main] using Windows. Xaml Live Preview option can showing up.
