### ISSUE TITLE
[Bug] CollectionView not working

### ISSUE THREAD

**Issue by ShrutiJaiswal1494** [dotnet/maui#2929]
Hi,

### Description
I am creating a Collection/ListView in MAUI following the example in Xamarins.Forms but it's complaining that `The type DataTemplate does not support direct Content` for the `Grid` control. I also tried using `ListView`  instead of `CollectionView` and it was also showing the same error for `ViewCell` control inside the `DataTemplate`.

It is also complaining about the `Binding` used with `Entry` control as `Type Binding is used like a markup extension but does not derive from MarkupExtension`

### Steps to reproduce
You can download this [folder ](https://microsoft-my.sharepoint-df.com/:f:/p/shjaiswal/EnlL-AM1YmtEtukVS6HFS5MBj6SSn156djBkhfJilpBJag?e=rCsXei) and open the TodoMAUI.sln file from VS 2022. It's a simple Todo application that I created following this [link](https://subscribe.packtpub.com/getting-started-with-microsoft-net-maui/).

### Expected behavior
On running the project it should have a UI like this and on clicking the + button a new page should pop up.
![image](https://user-images.githubusercontent.com/79670853/137207570-49566cd0-97e1-4f66-813b-9e9277ae0e59.png)

### Actual behavior
The UI that I see on running the Application is very different and also the function bindings are not working like on clicking the `+` button a page should pop up.

### Basic Information
IDE: Visual Studio Version 17.0.0 Preview 5.0
- IDE:Visual Studio Version 17.0.0 Preview 5.0
- Platform Target Frameworks: net6.0-windows 10.0.19041

### Screenshots
![image](https://user-images.githubusercontent.com/79670853/137078486-3067baf9-ce33-442e-b829-0669204648ae.png)

![image](https://user-images.githubusercontent.com/79670853/137080088-9c69751b-5b64-46ba-b22a-0662e947ac83.png)

**Comment by pierre01** [comment]
I have the Same issue Using Maui:
 VS Studio 2022 Preview 7 and MAUI 6.0.101-preview.10.2068
Bindings don't seem to work on windows (but work on android) and the ListView is not working.

running the same todo list inspired from:
https://subscribe.packtpub.com/getting-started-with-microsoft-net-maui/

**Comment by greatoceansoftware** [comment]
I have the same issue with binding working on Android but not Windows.
Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.1.0 Preview 1.1

I build my own test application with two-way bindings from a List<POCO> to ListView, and then from the ListView.SelectedItem to Editor.Text. Editing the text in the Editor control does not update the ListView SelectedItem's TextCell.Text property, nor the underlying POCO on Windows. Works as expected on Android.

This isn't even necessary in WPF. It would be nice if ListView and CollectionView had an IsSynchronizedWithCurrentItem property like WPF, which controls bindings to all other controls bound to the same data source. I will look for an enhancement request, and make a new one if necessary.

**Comment by wenwen60** [comment]
@[ShrutiJaiswal1494](https://github.com/ShrutiJaiswal1494) I can't reproduce your issue with project you provided. I can't see labels when running this project, but then I click + page can pop up. If I miss some steps?

**Comment by jfversluis** [comment]
Can't reproduce it as well. IntelliSense in VS is not giving me any squigglies and running the code seems to work as intended for both Windows and Android. Going to assume this is fixed. Let us know if there is still anything wrong.
