### ISSUE TITLE
[Bug] images loaded from URI's on iOS/WinUI aren't currently re-measuring 

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#2932]
## Description

Run the attached sample 

[aamuisample.zip](https://github.com/dotnet/maui/files/7339620/aamuisample.zip)

There's supposed to be an image at the top but the image doesn't load.

In the MAUI source code if you add an InvalidateMeasure call after the image is set then it will reload the image

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/2213 related

**Comment by wenwen60** [comment]
Not reproducible with 17.2.0 Preview 2.0 on windows.
