### ISSUE TITLE
[Bug] Grid doesn't appear to be consistently constraining 

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#2933]
### Description

You'll need to fix this issue first to recreate
https://github.com/dotnet/maui/issues/2932

### Steps to Reproduce

You can try with the following app:
[aamuisample.zip](https://github.com/dotnet/maui/files/7339778/aamuisample.zip)
But you'll need to have fixed the image loading problem

Another way to recreate is to use the recipes branch off this commit
https://github.com/dotnet/maui/commit/db5ece02e8b06152f82658193f232854d889d591
- click breakfast
- click any of the images you see
- you'll notice now that the images load behind the frameview

### Expected Behavior

iOS and Android layout the same
### Actual Behavior

Looking at the `NativeArrange` calls

On iOS the `rect` is 300x300 which is the size of the image whereas on android it's 381x114

iOS:
![image](https://user-images.githubusercontent.com/5375137/137171378-0d9f3ba4-b0b8-43bc-8c46-2a2a20534384.png)

Android: 
![image](https://user-images.githubusercontent.com/5375137/137175501-c96f9648-1fba-4015-b625-f67bfc237079.png)

**Comment by wenwen60** [comment]
Should fix this issue first [#2932](https://github.com/dotnet/maui/issues/2932) to recreate.
