### ISSUE TITLE
Multiple NU1603 warnings with Microsoft.Maui.Extensions 6.0.101-preview.9.1843

### ISSUE THREAD

**Issue by Zachael** [dotnet/maui#2934]
### Steps to Reproduce

Build MAUI Library generated from VS template

### Expected Behavior

No warnings

### Actual Behavior

warning NU1603: Microsoft.Maui.Extensions 6.0.101-preview.9.1843 depends on Microsoft.Extensions.Configuration (>= 6.0.0-rc.2.21470.23) but Microsoft.Extensions.Configuration 6.0.0-rc.2.21470.23 was not found. An approximate best match of Microsoft.Extensions.Configuration 6.0.0-rc.2.21480.5 was resolved.

warning NU1603: Microsoft.Maui.Extensions 6.0.101-preview.9.1843 depends on Microsoft.Extensions.DependencyInjection (>= 6.0.0-rc.2.21470.23) but Microsoft.Extensions.DependencyInjection 6.0.0-rc.2.21470.23 was not found. An approximate best match of Microsoft.Extensions.DependencyInjection 6.0.0-rc.2.21480.5 was resolved.

warning NU1603: Microsoft.Maui.Extensions 6.0.101-preview.9.1843 depends on Microsoft.Extensions.Hosting (>= 6.0.0-rc.2.21470.23) but Microsoft.Extensions.Hosting 6.0.0-rc.2.21470.23 was not found. An approximate best match of Microsoft.Extensions.Hosting 6.0.0-rc.2.21480.5 was resolved.

warning NU1603: Microsoft.Maui.Extensions 6.0.101-preview.9.1843 depends on Microsoft.Extensions.Hosting.Abstractions (>= 6.0.0-rc.2.21470.23) but Microsoft.Extensions.Hosting.Abstractions 6.0.0-rc.2.21470.23 was not found. An approximate best match of Microsoft.Extensions.Hosting.Abstractions 6.0.0-rc.2.21480.5 was resolved.

warning NU1603: Microsoft.Maui.Extensions 6.0.101-preview.9.1843 depends on Microsoft.Extensions.Logging (>= 6.0.0-rc.2.21470.23) but Microsoft.Extensions.Logging 6.0.0-rc.2.21470.23 was not found. An approximate best match of Microsoft.Extensions.Logging 6.0.0-rc.2.21480.5 was resolved.

warning NU1603: Microsoft.Maui.Extensions 6.0.101-preview.9.1843 depends on Microsoft.Extensions.Logging.Abstractions (>= 6.0.0-rc.2.21470.23) but Microsoft.Extensions.Logging.Abstractions 6.0.0-rc.2.21470.23 was not found. An approximate best match of Microsoft.Extensions.Logging.Abstractions 6.0.0-rc.2.21480.5 was resolved.

### Basic Information

Visual Studio 2022 Preview 5.0

**Comment by jayaleshwari** [comment]
I am also getting same error for newly created for library project.

**Comment by ni-xue** [comment]
I'm glad that you are still waiting for feedback on this problem. I have solved it here. The reason is that the project folder name, path file name and other non English symbols, including many XML pages, coding format, default non-utf-8 and other errors.

**Comment by ni-xue** [comment]
The above problems will only be prompted for projects generated in previous versions, but not for newly generated projects.

**Comment by ni-xue** [comment]
@maxkoshevoi Are you sure your project is new?
![image](https://user-images.githubusercontent.com/68054432/137862819-245f2e44-261f-449d-ae6d-6fb9ea7612c3.png)

**Comment by maxkoshevoi** [comment]
> Are you sure your project is new?

@ni-xue Yes, I've  created this project

> After that, I can debug normally

`NU1603` is a warning (not an error), it won't prevent project from being built or debugged.

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
