### ISSUE TITLE
[Enhancement] RetryOnConnectionFailure

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#2936]
Please add RetryOnConnectionFailure to the HttClient without having to use rendered.

For example:

```
HttpClient httpClient = new HttpClient();
httpClient.RetryOnConnectionFailure = true;

```

**Comment by jfversluis** [comment]
`HttpClient` is not something that is part of .NET MAUI, but the bigger .NET Runtime, please open an issue with them and don't forget to use the right template!
