### ISSUE TITLE
[Bug] iOS app missing splash screen after updating

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#2937]
The first time I build the app, the splash screen is generated and works fine. If I make a change and build again, the splash screen no longer displays and the app is shrunk to late-2000's proportions. 

It looks like maybe the splash screen generation isn't happening in incremental builds:

```
Target ProcessMauiSplashScreens:
  Skipping target "ProcessMauiSplashScreens" because all output files are up-to-date with respect to the input files.
```

**Comment by JohnHDev** [comment]
Ive seen this too but reported it via Send Feedback, I should have posted here instead!

**Comment by mattleibow** [comment]
This is fixed in p10! So exciting to finally figure out this and get it working. No more iPhone 1 apps on the iPhone 25!

**Comment by florianwachs** [comment]
Yes! Thanks so much @mattleibow, have to try it tomorrow on my iPad pro
