### ISSUE TITLE
[Enhancement] Allow selecting of specific target frameworks.

### ISSUE THREAD

**Issue by abhidotnet** [dotnet/maui#2939]
Is it possible to remove the target frameworks or allow an option to remove them? Each time, I compile a project it is prompting me to download iTunes and connect to a Mac. I don't have a Mac at this time and I would like to continue development for just android and windows.

I believe this feature already exists in Xamarin Forms as of today
![XamarinOptions](https://user-images.githubusercontent.com/164457/137229364-f9a09f37-852c-471c-86d8-46516d3f9032.png)
.

**Comment by jfversluis** [comment]
Seems that this didn't get a lot of traction and is some time old. Going to close this for now, let's revisit in the future. Thanks for your input!
