### ISSUE TITLE
[Bug] Unable to run published WinUI app

### ISSUE THREAD

**Issue by sprabha1990** [dotnet/maui#2941]
I'm trying to run the default templated .Net MAUI-WinUI application from the publish folder but it fails saying I need to install frameworks.

![image](https://user-images.githubusercontent.com/22351687/137229756-18836ae1-71f5-4f6d-8324-dbf92c2c6512.png)

The app runs from the visual studio as expected.

I have Net6 RC1, Net5 and NetFramework4.7.2 SDK's installed in my PC and I'm using VS 2022 Preview 4.1
What other frameworks are required?

To Reproduce:
#1. Create a default MAUI application.
#2. Publish it with TF: net6.0-windows10.0.19041 and TR: Portable
![image](https://user-images.githubusercontent.com/22351687/137230222-7dd2dcd5-df1e-4a6e-a71a-a59165a39ee8.png)
#3. Run the application from the published folder

**Comment by taozuhong** [comment]
met the same trouble on VS 2022 Preview 5 + MAUI Preview 9 + NET SDK 6 rc.2

**Comment by Redth** [comment]
Thanks this is currently unsupported but is on our roadmap #3166
