### ISSUE TITLE
[Bug] MAUI Preview 9: Changes to iOS info.plist are ignored

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#2943]
### Description
Make a change to the iOS info.plist, e.g. privacy permission text for calendar access. Build the app, and request calendar permission, the change is ignored.

### Steps to Reproduce

1 Make a change to the info.plist, e.g. privacy permission text for calendar access
2 Build the app, and request calendar permission
3 The change is ignored.

### Basic Information

- Version with issue: MAUI preview 9
- Last known good version: MAUI preview 8
- IDE: VS2022
- Platform Target Frameworks: iOS

### Workaround
None I could find

**Comment by kristinx0211** [comment]
@JohnHDev how do you  add the privacy permission text for calendar access with IOS info.plist?
