### ISSUE TITLE
Upgrading Microsoft.WindowsAppSDK crashes MAUI application

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#2953]
Upgrading the package-reference "Microsoft.WindowsAppSDK" from _1.0.0-experimatal1_ to _1.0.0-preview1_ causes the application to crash at start, in a MAUI application.

> System.TypeLoadException: 'Could not load type 'Microsoft.UI.Xaml.Controls.ElementAnimator' from assembly 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'.'

**Comment by Eilon** [comment]
@mattleibow - is this something you ran into while working on the WindowsAppSDK updates?

**Comment by mattleibow** [comment]
You can't use the new previews with maui because there have been several API breaking changes in WinUI. We have a new build of maui using the new previews in the p10 series, but due to some issues we are waiting for preview 3 of WinUI

**Comment by mattleibow** [comment]
Closing this as we are releasing soon and we are shipping with p3!
