### ISSUE TITLE
[Bug] Occasionally Maui Repository fails to compile because staticwebassets.pack.sentinel file can't be written to

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#2955]
### Description

When the error message pops up again I'll copy out the details. For now here's a screen shot

![image](https://user-images.githubusercontent.com/5375137/137379491-4cb8d7b0-08e6-4441-b5ff-5c9709fb92bc.png)

### Steps to Reproduce

1. pull down this repository
2. `dotnet cake --target=VS-NET6 --workloads=global`
3. Launch the single project solution a few times, change some things, launch it again.

It seems very random when it pops up. I haven't been able to narrow it down to any specific sequence of steps

### Basic Information

Visual Studio: 17.1

**Comment by mattleibow** [comment]
I have seen this pretty often I think. Not sure if this was with only winui or also with wasm projects.

**Comment by javiercn** [comment]
@Eilon this is being addressed https://github.com/dotnet/sdk/pull/25011
