### ISSUE TITLE
[Bug] CollectionView does not reflect added items properly on navigated page

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#2958]
### Description
When I use Shell navigation, and navigated page contains CollectionView, and I add/remove items from ItemsSource collection, those items are not reflected. They appear when I try to scroll the page, but CollectionView's size is not recalculated based on items.

It works perfectly fine when Shell navigation is not involved.

### Steps to Reproduce

1. Run the attached sample on Android.
2. Click Navigate button.
3. Click Clear button.
4. Click Add button 10 times.

### Expected Behavior
Added items are visible.

### Actual Behavior
Added items are not visible. 
They become visible after you attempt to scroll the page, but CollectionView is not resized based on items.

### Basic Information

I have reproduced on Android devices. I haven't tested it with Apple devices. I've tried to test it with Windows, but I wasn't able to see any items at all there.

- Version with issue: Preview 9
- Last known good version: -
- IDE: Visual Studio
- Platform Target Frameworks:
- Android: API 30
- Nuget Packages:
- Affected Devices: Android Emulator Pixel 4 API 30

### Reproduction Link
[MauiRepro.zip](https://github.com/dotnet/maui/files/7349323/MauiRepro.zip)

### Screen recording

![86LOGaxA5g](https://user-images.githubusercontent.com/17177729/137393991-264c857e-c3fc-43a5-b481-e6c6f33bd82e.gif)

**Comment by SarthakGz** [comment]
I don't think collection view is completely ported to MAUI yet!

**Comment by wenwen60** [comment]
Not reproducible with Android 11 with the above repro project.
