### ISSUE TITLE
[Bug] Exception thrown: 'System.TypeLoadException' in Microsoft.Maui.Controls.dll

### ISSUE THREAD

**Issue by taozuhong** [dotnet/maui#2961]
### Description
![image](https://user-images.githubusercontent.com/13451009/137418002-141fb246-8c4a-4b28-9517-08643d6f1fc3.png)

### Steps to Reproduce

1. Make a Maui app, choose framework: net6.0-windows
![image](https://user-images.githubusercontent.com/13451009/137418116-6dfc6951-b029-4e80-9d74-9800b82de5ea.png)

2. build and run the app, then exception is thrown:
‘System.TypeLoadException’ in Microsoft.Maui.Controls.dll
The program has exited with code 3221226107 (0xc000027b).

### Basic Information

- Version with issue:
- Last known good version: VS 2022 Preview 5 + MAUI Preview 9 + NET SDK 6 rc.2
- IDE: VS2022 Preview 5.0 with MAUI Preview 9 (Just follow the installation of Maui preview 9)

**Comment by mattleibow** [comment]
Just checking this... What version are you using? You mention the last know good version was p9, and that is the latest.

Are you testing p10?

Also, do you still have the Windows extensions installed? https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17

**Comment by shimingsg** [comment]
Not reproducible with windows 10.0.19041.
