### ISSUE TITLE
[Bug] UI not updating after property removed and hot reloaded

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2963]
### Description

I can add a new `Background="Red"` to a `ContentPage` in a `Shell` app and it will hot reload. 

<img width="875" alt="image" src="https://user-images.githubusercontent.com/41873/137422289-f88bd05f-59fc-43b3-8e59-29ef4bc288d2.png">

When I remove it, it hot reloads but doesn't update the UI.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/41873/137422339-1711505b-d7af-4741-accf-28521e3275f2.png">

... until I rotate the emulator and trigger a layout cycle. 

<img width="899" alt="image" src="https://user-images.githubusercontent.com/41873/137422389-c07becf3-b424-43ae-9c71-fcd5321a3f7e.png">

### Expected Behavior

Removing the code both reloads and renders the visual change without rotating the emulator

### Actual Behavior

Described above.

### Basic Information

- Version with issue: 9.1843

### Reproduction Link

https://github.com/dotnet/maui/issues/2962

**Comment by mattleibow** [comment]
Tested in .NET MAUI 7.0.59 and this is now working in the stable VS.
