### ISSUE TITLE
[Bug] UI doesn't update when content is added to XAML

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2964]
### Description

I added a `Label` at the top of the `VerticalStackLayout` in a Shell app. It doesn't update the UI.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/41873/137422672-951a7f80-2a6c-4e48-9be1-fc704d4d8514.png">

... until I rotate the emulator

<img width="871" alt="image" src="https://user-images.githubusercontent.com/41873/137422753-2adcda70-02fe-4c16-b724-1947d810b471.png">

### Basic Information

- Version with issue: 9.1843

### Reproduction Link

https://github.com/davidortinau/ControlGallery

**Comment by wenwen60** [comment]
Not reproducible with Android 11 with the above repro project.
