### ISSUE TITLE
[Bug] Removing content from layout hot reloads blank

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2965]
### Description

See https://github.com/dotnet/maui/issues/2964

I removed the Label at the top of the VerticalStackLayout that is populated with a BindableLayout. The content hot reloaded, but the page is now blank. 

Rotating the emulator doesn't bring the content back.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/41873/137423054-4b29b739-555c-4751-ac5b-04e6a0ea4a52.png">

### Basic Information

- Version with issue: 9.1843

### Reproduction Link

https://github.com/davidortinau/ControlGallery

**Comment by wenwen60** [comment]
Not reproducible with Android 11 and the above repro project.
