### ISSUE TITLE
[Bug] Unable to set image as ContentPage BackgroundImageSource

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2966]
### Description

I'm setting the bot image to the background of the page, but nothing appears.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/41873/137425090-90494709-e2f0-4b80-a708-493d390f51f7.png">

### Basic Information

- Version with issue: 9.1843

**Comment by wenwen60** [comment]
Reproduce on Android, attach the repro sample
[MauiApp23.zip](https://github.com/dotnet/maui/files/8123254/MauiApp23.zip)
