### ISSUE TITLE
[Bug] XAML Hot Reload throwing error on LinearGradientBrush code

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#2968]
### Description

I added this code, and it worked during hot reload. I can recompile and run fine. I just noticed trying something unrelated that these errors had appeared. 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/41873/137425422-79383cd6-d7b0-4150-9c19-a2c0abb34cbe.png">

### Expected Behavior

This valid code shouldn't be triggering XHR errors

### Basic Information

- Version with issue: 9.1843

**Comment by mattleibow** [comment]
This does not appear to be happening anymore.
