### ISSUE TITLE
[Bug] IOS Simulators Not Populated on Pair

### ISSUE THREAD

**Issue by samminnella** [dotnet/maui#2970]
Maui Razor template Preview 9 (RC2) the iOS simulators are not populated when you pair Mac.  I was only able to get the list to populate once but no idea how.  All that is found is a device name Simulator. There is supposed to be around 10 ios devices in the list. Please give the "Play Button" some love.

**Comment by jfversluis** [comment]
This has been working fine for me for some time now. Please open a new issue if this is still a problem for you with all the latest versions. Thanks!
