### ISSUE TITLE
[Bug] <MauiImage> won't accept PNG file for Android AppIcon

### ISSUE THREAD

**Issue by shirok1** [dotnet/maui#2972]
### Description

Trying to build with a PNG file path (not SVG) set to `Include` and `ForegroundFile` will produce following log:

```
1>Resources\izetizer\r\drawable-v24\background_background.xml(2): error APT2000: no element found.
1>Resources\izetizer\r\drawable-v24\background_background.xml : error APT2261: file failed to compile.
```

It seems that AndroidAdaptiveIconGenerator will always assume that you are using a SVG file and try to convert it to Android drawable. (Also it won't accept a SVG file with embedded <Image> (which Android drawable actually supports), causing another error)

- Version with issue: VS 2022 Preview 5.0 stock 
- IDE: VS 2022 Preview 5.0
- Platform Target Frameworks:
  - Android: 21.0
- Android Support Library Version: stock

**Comment by jfversluis** [comment]
This issue seems from a while ago and a lot of bugs have been fixed in this area or are about to be fixed with #8020.

Please test it again and let us know if this is still an issue. If so, please open a new issue with all the details. Thanks!
