### ISSUE TITLE
[Bug] Buttons's Border Color not rendering

### ISSUE THREAD

**Issue by tj-devel709** [dotnet/maui#2980]
### Description
Hi this is TJ from the Xamarin/macios team. For the Hackathon, I decided to get my feet wet with Maui. I worked on this project on my Mac and used the CLI and Visual Studio Code. I created a Button and tried to give it a border, but nothing was rendered. I also made sure that I changed the border width and tried it with numerous colors. Please let me know if this is a known problem, something that is not supported yet, or just something of my fault! This was also on the iOS simulator running an iPad mini with iOS 15.0. ~~(I was not able to use the Android or the MacCatalyst simulators, let me know if you would like a separate issue for that!)~~

### Steps to Reproduce

1. Create a button in xaml.
2. Give it the attributes:
```
    BorderColor="#9C27B0"
    BorderWidth="2"
```

### Expected Behavior
The button has a border around it.

### Actual Behavior
The button does not have a border around it.

### Basic Information

Hopefully this [maui-check](https://gist.github.com/tj-devel709/079402292f2a4866b7039d9dbbe500ce) provides all the needed information

### Screenshots

Here is actual behavior, there should be a border around the 'Sign In' and 'Create Account' buttons
![image](https://user-images.githubusercontent.com/50846373/137523544-dfb71a91-d6ff-4a99-ab66-8113fd51e537.png)

I was going for something like this (in regards to the borders on the buttons)
![image](https://user-images.githubusercontent.com/50846373/137523605-a24115a3-1f72-4285-a1a6-6ddd16cb4443.png)

### Reproduction Link

https://microsoft-my.sharepoint.com/:u:/p/antlambe/EQ0W7TsEDSRAgXy92K6_BakBL9abckbXd3YVSrIyeXKM4Q?e=TKzuUm

**Comment by NogginBox** [comment]
Is this related to #3791?

**Comment by jsuarezruiz** [comment]
This properties (BorderColor, BorderWidth etc) were implemented later https://github.com/dotnet/maui/pull/3411 
Could you try again with latest version?
