### ISSUE TITLE
Map Controls.DatePicker.TextTransform

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#2987]
This will not be a Core property. It will remain on Controls.DatePicker, and Controls.DatePicker will need to add a custom mapping  which applies the current TextTransform (after applying Format).

See the Label.cs partial class under HandlerImpl/Label for an example of a custom Controls-level mapping for this.

**Comment by buyaa-n** [comment]
I also wonder what property the `TextTransform` result should apply here
