### ISSUE TITLE
Map Controls.InputView.TextTransform

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#2990]
This will not be a Core property. It will remain on Controls.InputView, and Controls.InputView's subclasses (Editor, Entry, SearchBar)  will need to add custom mappings which apply the current TextTransform.

See the Label.cs partial class under HandlerImpl/Label for an example of a custom Controls-level mapping for this.

**Comment by pierre01** [comment]
TextTransform="Uppercase" does not work on Editor.
