### ISSUE TITLE
[Bug]Debugger Stops attaching to iOS build after few cycles.

### ISSUE THREAD

**Issue by samminnella** [dotnet/maui#2996]
Maui Preview 9 XAML Template
After 5-6 cycles the debugger stops attaching to iOS simulator or device attached to mac. 
There is no stop button and message at bottom left of screen just says deploy succeeded. 
The app is not automatically started.
Restart VS to fix.

**Comment by mattscheffer** [comment]
No repro with 17.2.0 Preview 1 Maui app targeting iPhone 13 iOS 15.2 simulator. Stop button appears throughout debugging in the editor. Simulator continues to attach to Mac
