### ISSUE TITLE
[Bug] iOS build and deploy to mac seems slow

### ISSUE THREAD

**Issue by samminnella** [dotnet/maui#2997]
Maui Preview 9 Razor

Sincerely sorry for this one not looking to get bashed (too much) but better to speak up now while Maui is still a moving target. 

Currently it takes between 40 and 75 seconds for me to deploy a change to iPhone simulator running on the latest MAC MINI. 
I understand hot reload advantages but adding a class or adding a property require a rebuild.
We could blame the mini and try a mac pro but $7000 seems  like a steep tax and have doubts it would be incrementally better.
Def going to require a workflow adjustment.

**Comment by samminnella** [comment]
Fresh install of VS2022 RC2 including the Maui preview.
Below is the output from maui-check 0.9.0.0. 

» Synchronizing configuration... ok
» Scheduling appointments... ok

> OpenJDK 11.0 Checkup...
  - 11.0.12 (C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\..)
  - 11.0.10 (C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot\bin\..)

> Visual Studio 17.0.0-pre.5.0 Checkup...
  - 16.8.3
  - 16.11.2
  - 17.0.0-pre.5.0 - C:\Program Files\Microsoft Visual Studio\2022\Preview

> Android SDK Checkup...
  - emulator (30.8.4)
  - build-tools;31.0.0 (31.0.0)
  - platforms;android-31 (1)
  - system-images;android-31;google_apis;x86_64 (8)
  - platform-tools (31.0.3)
  - cmdline-tools;5.0 (5.0)

> Android Emulator Checkup...
  - Emulator: pixel_2_-_api_28 found.

> .NET SDK Checkup...
  - 3.1.414 - C:\Program Files\dotnet\sdk\3.1.414
  - 5.0.101 - C:\Program Files\dotnet\sdk\5.0.101
  - 5.0.104 - C:\Program Files\dotnet\sdk\5.0.104
  - 5.0.208 - C:\Program Files\dotnet\sdk\5.0.208
  - 5.0.303 - C:\Program Files\dotnet\sdk\5.0.303
  - 5.0.400 - C:\Program Files\dotnet\sdk\5.0.400
  - 5.0.402 - C:\Program Files\dotnet\sdk\5.0.402
  - 6.0.100-rc.2.21505.57 - C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57

> .NET SDK - Workload Deduplication Checkup...

> Edge WebView2 Checkup...
  - Found Edge WebView2 version 94.0.992.50

> .NET SDK - Workloads (6.0.100-rc.2.21505.57) Checkup...
  - android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 31.0.101-preview.9.16) installed.
  - ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.101-preview.9.31) installed.
  - maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.101-preview.9.31) installed.
  - tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.101-preview.9.31) installed.
  - macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.101-preview.9.31) installed.
  - maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.101-preview.9.1843) installed.
  - wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-rc.2.21480.5) installed.
  - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-rc.2.21474.1) installed.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

- Congratulations, everything looks great!

**Comment by Redth** [comment]
This should be fixed now, there were bugs fixed in recent ios previews to dramatically reduce build and deploy times.
