### ISSUE TITLE
[Bug] Preview 9 breaks CollectionView update with ObservableCollection

### ISSUE THREAD

**Issue by quibenefacit** [dotnet/maui#3002]
### Description
Preview 9 breaks CollectionView showing data from ObservableCollection when run in Android Emulator or an Android physical phone (other configurations not tested). 
This used to work before Preview 9.

### Steps to Reproduce
XAML code (had to remove left brackets in order for GitHub to let me post it(: 

CollectionView ItemsSource="{Binding ViewModel_MyConns}"
    CollectionView.ItemTemplate>
         DataTemplate>
             Label Text="{Binding LastName}" TextColor="Red"/>
         /DataTemplate>
    /CollectionView.ItemTemplate
/CollectionView

MVVM code:

public class ConnsViewModel: INotifyPropertyChanged {
     public ObservableCollection<STuser> ViewModel_MyConns { get; }
    IList locallist;

    public ConnsViewModel() {
         ViewModel_MyConns = new ObservableCollection<STuser>();
         locallist = ReadDataFromDB();
         foreach (var item in locallist) {
             ViewModel_MyConns.Add(item);
         }
    }
}

### Expected Behavior
CollectionView should show the data.

### Actual Behavior
CollectionView doesn't show the data.

### Basic Information

- Version with issue: Preview 9 
- Last known good version: Preview 7
- IDE: Visual Studio 2022
- Platform Target Frameworks: 
  - iOS:  
  - Android:  10
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Android Emulators and Android physical phones.

**Comment by shimingsg** [comment]
verified not repro with VS 17.2.0 Preview 2.0 [32228.609.main] in Android 12 Emulator 
demo: 
[3002.zip](https://github.com/dotnet/maui/files/8166857/3002.zip)

![image](https://user-images.githubusercontent.com/20982341/156301678-3b91bea5-9874-48a1-a6a1-3e6539857cc0.png)
