### ISSUE TITLE
[Bug] Handler not found for view Microsoft.Maui.Controls.Compatibility.RelativeLayout

### ISSUE THREAD

**Issue by dothanh1996** [dotnet/maui#3006]
### Description
I have a source code that still works properly on maui preview 8, visual studio 2022 preview 4. When upgrading should use maui preview 9, visual studio 2022 preview 5, I get the following error: Handler not found for view Microsoft.Maui.Controls.Compatibility.RelativeLayout

### Steps to Reproduce

1. Create new project maui preview 9
2. Add "xmlns:cmp="clr-namespace:Microsoft.Maui.Controls.Compatibility;assembly=Microsoft.Maui.Controls""
3. Add 
    <Grid GridLayout.Column="1" Padding="25 5 5 10">
                        <Grid.GestureRecognizers>
                            <PanGestureRecognizer PanUpdated="Preview_PanUpdated"
                                                  ParentChanged="PanGestureRecognizer_ParentChanged" />
                        </Grid.GestureRecognizers>
                        <Frame Background="#f2f2f2" 
                               HeightRequest="480" 
                               BorderColor="Black" 
                               CornerRadius="1" 
                               Padding="0"
                               HorizontalOptions="FillAndExpand"
                               VerticalOptions="FillAndExpand">
                            <ContentView Padding="0"
                                         VerticalOptions="FillAndExpand"
                                         HorizontalOptions="FillAndExpand">
                                <ContentView.BindingContext>
                                    <model:MainPageObject/>
                                </ContentView.BindingContext>
                                **<cmp:RelativeLayout x:Name="RelativePreview"
                                    VerticalOptions="FillAndExpand"
                                                HorizontalOptions="FillAndExpand">
                                </cmp:RelativeLayout>**
                            </ContentView>
                        </Frame>
                    </Grid>

### Expected Behavior
The program builds and runs successfully as preview 8
### Actual Behavior
Error: Handler not found for view Microsoft.Maui.Controls.Compatibility.RelativeLayout.
### Basic Information
- Visual studio preview 5
- Maui preview 9
- Build and run with: .net 6 windows 10.0.19041

### Screenshots

![image](https://user-images.githubusercontent.com/22495616/137711148-26266739-f742-429a-b66e-1f4c8e2fad5e.png)

![image](https://user-images.githubusercontent.com/22495616/137711180-a96d8e0b-2986-4cc0-aebc-806f036ef895.png)

**Comment by rmarinho** [comment]
Can you remove the compatibility from the namespace and use RelativeLayout new version? that's on the default namespace.. So basically just use <RelativeLayout

**Comment by hartez** [comment]
> Can you remove the compatibility from the namespace and use RelativeLayout new version? that's on the default namespace.. So basically just use `<RelativeLayout `

That won't work just yet - we still haven't ported RelativeLayout to a new handler. 
We'll need to add the Compatibility renderer in the configuration until we port it.
