### ISSUE TITLE
[Bug] cant add content to grid from c#

### ISSUE THREAD

**Issue by Xami3Shah** [dotnet/maui#3008]
try to add a child to grid layout on specific row and column using preview 9, it does not work because Add overloaded method is marked as internal in sourcecode
```
            Grid rootlayout = new Grid();
            Entry entry = new Entry();

            rootlayout.Children.Add(entry, 0, 0);
```
Only iList Add works, which is

 `rootlayout.Children.Add(entry);`

**Comment by hartez** [comment]
This is a duplicate of #780 - we still need to add the convenience overloads. 

In the meantime, you can add the control and then set the Row/Column using `Grid.SetRow()` and `Grid.SetColumn()` or `rootLayout.SetRow()` and `rootLayout.SetColumn()`.
