### ISSUE TITLE
[Bug] By default .NET MAUI Project doesn't target all Android ABIs

### ISSUE THREAD

**Issue by juansturla** [dotnet/maui#3011]
### Description

When you build an MAUI app and try to deploy it to a Samsung Galaxy Tab A 10
The tablet has:
- CPU Architecture: ARMv7-A
- Instruction set: armeabi-v71, armeabi

Error thrown is
`ADB0020: Mono.AndroidTools.IncompatibleCpuAbiExceptiopn: The package does not support the CPU architecture of this device.`

### Steps to Reproduce

1. Connect an Android physical device with an Instruction set mentioned above
2.  Try to deploy any .NET MAUI APP
3. It builds correctly, but throws error on deploy

### Expected Behavior

It can be deployed correctly

### Actual Behavior

It doesn't :(

### Basic Information

- Version with issue: .NET MAUI preview 9
- Last known good version: None on .NET MAUI
- IDE: Visual Studio 2022 Preview 5.0
- Platform Target Frameworks: 
  - Android: Min 21, target 30
- Affected Devices: Samsung SM-T580

### Workaround

Add a to the .csproj
`<RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>`

**Comment by Eilon** [comment]
Could this be related to https://github.com/xamarin/xamarin-android/issues/5388 ?

**Comment by mattleibow** [comment]
Not sure if this is still an issue?
