### ISSUE TITLE
[Bug] CollectionView.EmptyView does not render on android

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3012]
### Description
In the sample project: [Collectionview.zip](https://github.com/dotnet/maui/files/7367084/Collectionview.zip) There is a CollectionView with an empty view that is not rendered in android

### Steps to Reproduce for Android
1. Run in Android
### Expected Behavior
Empty view should be rendered
### Actual Behavior
A white page is rendered

### Screenshots
![image](https://user-images.githubusercontent.com/603023/137773466-c95e96eb-d6a8-47a1-a259-95f1efff9d07.png)

**Comment by wenwen60** [comment]
Reproduce using the above project on 17.2.0 Preview 2. Tested with Android 11.

**Comment by mterhorst** [comment]
I can repro the provided sample project when running on local Android 9 device or emulator.

**Comment by jamesmontemagno** [comment]
My EmptyView shows... but when I fill up the list with data it won't go away when running on Android 12 emulator. 

However, if I run it on Window it seems to work! @jsuarezruiz

**Comment by rmarinho** [comment]
@jamesmontemagno  do you still have this problem?

**Comment by jamesmontemagno** [comment]
I am pretty sure this is fixed, but I have the reverse is that it wouldn't go away after i filled items in the collectionview on andriod... but maybe you fixed that? i did open a bug on it.
