### ISSUE TITLE
[Bug] CollectionView.EmptyView does not raises clicked event on UWP

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3013]
### Description
In the sample project: [Collectionview.zip](https://github.com/dotnet/maui/files/7367084/Collectionview.zip) There is a CollectionView with an empty view containing a button but the onClicked event handler is not raised

### Steps to Reproduce
1. Run in Windows
2. Tap on "Click me"
### Expected Behavior
Current count must be incremented.
### Actual Behavior
Current count is not incremented

### ScreenShots
![image](https://user-images.githubusercontent.com/603023/137773899-53fdd242-9ebd-4876-ab70-af9dbecfef73.png)

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EffupXrlSJZDk2tEloXvMjABDlBVrGeyZ6WX6JbjtyD-ZA?e=EQn4hz

**Comment by Redth** [comment]
Validated still an issue.

**Comment by buyaa-n** [comment]
I have been looking into this issue a month ago, here is what I found:
The button or any control inside `EmptyView` is not responding to any event, not only click (like normally I can see the style change on mouse over for a button but not within empty view). If I put a button inside the Header/Footer or CollectionView itself it is clickable. My conclusion is there is no any event handler support added for `EmptyView` at all, though I was not able to find where/how that is set, I was hoping while working on the other issues I could see/find the solution for this, but did not and I don't think I could figure that out before `6.0.300-rc.3` deadline, so unassigning myself. It must be easy fix for somebody has more experience with Event handlers

**Comment by VincentBu** [comment]
Still occur in VS [32506.368.main].
