### ISSUE TITLE
Remove Blazor Desktop workarounds for iOS/Android Content warnings

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#3014]
The MAUI Blazor Desktop targets contain various workarounds to avoid various warnings related to MSBuild `Content` items. The workaround to avoid those warning is to use BeforeTargets/AfterTargets to temporarily remove certain `Content` items, and then later restore them.

Ideally we would have a proper way of avoiding these warnings. Maybe one of these:

1. Do something to avoid getting into this problem in the first place? This might not be possible due to each SDK having its own, incompatible view of what `Content` means.
2. Have a generic MAUI way of doing the workaround so it isn't unique to Blazor. Perhaps if Blazor Desktop could tag the items as being `MauiWebContent` or similar, the MAUI targets could "do the needful" (which might be identical to the current workarounds, but in a common location) (credit: @mattleibow )

**Comment by javiercn** [comment]
@Eilon I imagine you are referring to 

https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/build/Microsoft.AspNetCore.Components.WebView.Maui.targets#L46-L82

@pranavkm does your work in this area help with this issue?

**Comment by javiercn** [comment]
For Android, I think @pranavkm approach will make the target workaround obsolete.

For iOS It comes down to this Task https://github.com/xamarin/xamarin-macios/blob/2972e1b715a11dd508023ea5bb71085d4dbf43ce/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CollectBundleResourcesTaskBase.cs#L44

Which gets invoked in MSBuild like this in `Microsoft.iOS.Sdk\15.2.301-preview.13.2\tools\msbuild\iOS\Xamarin.Shared.targets`

```
<CollectBundleResources
	SessionId="$(BuildSessionId)"
	Condition="'$(IsMacEnabled)' == 'true'"
	OptimizePropertyLists="$(OptimizePropertyLists)"
	OptimizePNGs="$(OptimizePNGs)"
	BundleResources="@(Content);@(BundleResource)"
	ProjectDir="$(MSBuildProjectDirectory)"
	ResourcePrefix="$(_ResourcePrefix)"
	TargetFrameworkMoniker="$(_ComputedTargetFrameworkMoniker)"
	>
	<Output TaskParameter="BundleResourcesWithLogicalNames" ItemName="_BundleResourceWithLogicalName" />
</CollectBundleResources>
```

We would need a way to exclude the item on this task in the iOS SDK if we want to remove the workaround.

**Comment by javiercn** [comment]
I think this is related to https://github.com/dotnet/maui/issues/2981

**Comment by javiercn** [comment]
Here is my take of what's going on here:
* IOS is adding all `Content` items to the bundle without any way to filter them out.
* ASP.NET Core/Razor adds items to the content itemgroup as expected.
* iOS finds these Content items and doesn't like them, producing an error.

Based on this, I think we need the following:
* An official extensibility point where we can hook before these checks are done for Android/iOS or an explicit agreement that it is ok for us to hook into those targets.
* An official way of excluding Content items from these tasks/checks.
  * There is already a way in Android to do this as @pranavkm was in the process of implementing the other day.

With these two things, we will hook into the pipeline in our Maui targets and do as follows:
* Update content items recognized as static web assets to skip this check.
* Update Razor files content items to skip this check.

The goal here is twofold:
* Razor SDK doesn't have code specific to Maui.
* iOS/Android SDKs provide a standard way of opting out of these checks/bundling.
* The MauiBlazorWebview targets update the content items to reflect that these items shouldn't be considered.

I think if we do this based on Razor and Static Web Assets, it makes the feature future proof, as in when we add new functionality we don't have to worry about updating anything else.

**Comment by Eilon** [comment]
@javiercn I think @pranavkm has discussed with the Android and iOS SDK folks and we have solutions in progress.

**Comment by javiercn** [comment]
@Eilon Yes, @pranavkm and myself synced offline on what to do here, and we believe we can do this in a way that avoids us having to update this in the future for new Razor features.

We'll piggyback on Convert...ToMauiAssets and update the content items there.
