### ISSUE TITLE
[Bug] Rectangle types issues

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#3022]
### Description

Using Rectangle from XAML creates a Shape by default. However, to set position and size we sometimes need to use Rectangle struct from Microsoft.Maui.Graphics.

Although it is possible to do it from C#, not from XAML.

```
<ContentPage.Resources>
   <ResourceDictionary>
      
      <!-- This is a Shape -->
      <Rectangle  x:Key="Rectangle" />
      
   </ResourceDictionary>
</ContentPage.Resources>

<!-- Here we need a  Microsoft.Maui.Graphics.Rectangle type -->
<ScrollView AbsoluteLayout.LayoutBounds="{StaticResource Rectangle}" />
```

Because we have more than one Rectangle type. The only way is to use a specific namespace:

`xmlns:graphics="clr-namespace:Microsoft.Maui.Graphics;assembly=Microsoft.Maui.Graphics"`

### Steps to Reproduce

1. Create a Rectangle in the Page Resources.
2. Try to use it with AbsoluteLayout.LayoutBounds (for example).

### Expected Behavior
We can create Rectangle Shape from XAML but also, set position and size using the Rectangle struct.

### Actual Behavior
Can only create the Rectangle Shape from XAML.

### Workaround

Use C#.

**Comment by Redth** [comment]
Fixed in P14
