### ISSUE TITLE
[Bug] [Android] [MAUI Blazor] Crash on Android 5 device/emulator

### ISSUE THREAD

**Issue by mterhorst** [dotnet/maui#3023]
### Description

Default MAUI Blazor app crashes on Android with following exception.
![image](https://user-images.githubusercontent.com/24865628/137902005-14689122-53a7-4e31-87a1-872bfc8bef0e.png)

### Steps to Reproduce

1. Run `dotnet new maui-blazor`
2. Create emulator with API 21
![image](https://user-images.githubusercontent.com/24865628/137902280-f9041716-e8b1-43a3-9b24-6b14c306aa85.png)
3. Run in Debug

### Actual Behavior

Crash.

### Basic Information

- Version with issue: MAUI preview 9
- IDE: Visual Studio 2022 preview 5
- Platform Target Frameworks:
  - Android: SDK 21

### Workaround

Not aware of any.

**Comment by Eilon** [comment]
It would be a low priority to update that code and test it. That code has been through many revisions to get to where it is, so it's quite risky to change it.

Also, Google Play has a requirement of API Level 30 for all new and updated apps starting next month: https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html

For these reasons, I think it is unlikely we would support something so old.

**Comment by AmrAlSayed0** [comment]
Google's requirement is API 30 for the API to _build_ against (the target API), there are no requirements for what API level to run on and net6.0-android should support API level 21. This min number will probably be bumped up by 1 each year but for now it is 21.

Anyway, I'm not too invested into this myself. I just thought I would offer sum ideas.

**Comment by mterhorst** [comment]
I realize it's a preview product and that things aren't finalized yet. Eventually I would expect a list of API levels MAUI blazor can run under. For now I figured it would be API level 21 (see docs), but that seems to be incorrect for MAUI Blazor. However for "regular" MAUI it is correct and does work.

**Comment by RaspeR87** [comment]
Same behaviour for me. Is it possible to make this MAUI Blazor working with older API version in future, or we'll have to take API 23 or newer?

**Comment by VincentBu** [comment]
repro on android device

**Comment by mkArtakMSFT** [comment]
Two things we can do here:
1. Document this API requirement
2. Keeping this on the backlog to make the error experience better in the future.

**Comment by BoobalanK** [comment]
Hello Team, Please let me know is there any workaround for this issue ?

**Comment by Eilon** [comment]
@BoobalanK we are not aware of any workaround for this.

**Comment by MackinnonBuck** [comment]
Closing since the docs have now been updated with the correct Android API requirements.
