### ISSUE TITLE
[Bug] Custom namespace schemas not working

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#3027]
### Description

Adding custom namespace schemas not working. It works when the source code is attached and using a library/assembly throwing error on compilation.

Namespace:
using Company.CustomLibrary;

public class CustomControl
{
}

Schema defined:
```csharp
[assembly: XmlnsDefinition("http://schemas.company.com/maui", "Company.CustomLibrary")]
```

xaml:
xmlns:company="http://schemas.company.com/maui"
Error:
1>MainPage.xaml(32,10): XamlC error XFC0000: Cannot resolve type "company.CustomControl".

**Comment by davidbritch** [comment]
I've just tried this today, and it worked. See https://github.com/davidbritch/dotnet-maui-samples/tree/main/XAML/CustomNamespaceSchemaDemo

**Comment by jfversluis** [comment]
It's been a while since we've seen activity here and seems to work with recent versions. Closing this for now, let us know if. this still doesn't seem to work for you, thanks!
