### ISSUE TITLE
[Bug] Scroll view not working correctly after October 12, 2021 release

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#3028]
### Description

I was created the custom layout that holds the top and bottom labels with in between scroll view but the scroll view overlapped with top and bottom labels. This issue raised due to October 12, 2021 release, before that it was working fine

### Steps to Reproduce

1. Run the below added code to main page.xaml
2. scroll the scroll view
3. It was overlayed to top and bottom labels

### Expected Behavior

- Scroll view rendered correctly

### Actual Behavior

- Scroll view does not rendered correctly

### Sample Code

```
<Grid>
  <Grid.RowDefinitions>
    <RowDefinition Height="100"/>
    <RowDefinition Height="*"/>
    <RowDefinition Height="100"/>
  </Grid.RowDefinitions>

<Label
  Text="Welcome to .NET Multi-platform App UI"
  Grid.Row="0"
  SemanticProperties.HeadingLevel="Level1"
  SemanticProperties.Description="Welcome to dot net Multi platform App U I"
  FontSize="18"
  HorizontalOptions="Center" />

<ScrollView Grid.Row="1" VerticalScrollBarVisibility="Always">
  <Grid HeightRequest="1200" BackgroundColor="Red"/>
  </Grid>
</ScrollView>

<Label
  Text="Welcome to .NET Multi-platform App UI"
  Grid.Row="2"
  SemanticProperties.HeadingLevel="Level1"
  SemanticProperties.Description="Welcome to dot net Multi platform App U I"
  FontSize="18"
  HorizontalOptions="Center" />

</Grid>

```

### Replication Video

https://user-images.githubusercontent.com/44917578/137917661-fed16342-d0f1-4e3c-b37a-8f329faf4807.mp4

**Comment by hartez** [comment]
This is fixed for preview 10.
