### ISSUE TITLE
[Bug] Shell FlyoutBackgroundColor property has no effect

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3030]
### Description
Setting the flyoutBackgroundColor property has no effect on the app.

### Steps to Reproduce

1. Run sample protect 
2. Make de flyout appear
### Expected Behavior
Backgroundcolor of Flyout is red
### Actual Behavior
Backgroundcolor of Flyout is the system default.
### Basic Information

- Version with issue: 6.0.101-preview.9.1843
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 5.0

For mac and iOS maui-check says that is all ok: 
![image](https://user-images.githubusercontent.com/603023/137925670-3bbe38a3-2a0f-43bb-acf7-26341bbb0334.png)

Am I wrong? or can I have some issue with the upgrade to preview 9 in Mac?
### Screenshots

Windows: 
![image](https://user-images.githubusercontent.com/603023/137926935-6b35927c-865b-4e75-8dcb-329d22045b26.png)

Android: 
![image](https://user-images.githubusercontent.com/603023/137926998-41b2cc8f-f324-4d87-ba34-6664406fff78.png)

iOS:
![image](https://user-images.githubusercontent.com/603023/137927089-9b047295-fe77-4392-bbb5-7726b7156574.png)

Mac:
![image](https://user-images.githubusercontent.com/603023/137927153-222700ea-e80d-4687-b7ee-5661a52f56bf.png)

### Reproduction Link

[ShellBackground.zip](https://github.com/dotnet/maui/files/7373980/ShellBackground.zip)

**Comment by darioxz** [comment]
@PureWeen Great, that did the trick. It also helped me to get more familiar with Maui and XAML in general! 

Thank you!
