### ISSUE TITLE
Dependency injection of ILogger not working when using Serilog in Maui Blazor app [Bug] 

### ISSUE THREAD

**Issue by julianadormon** [dotnet/maui#3031]
Serilog (ILogger) fails to log silently in razor pages when using dependency injection

### Steps to Reproduce

1. Add Serilog to main program with configuration (works perfectly when called there)
2. AddSerilog() middleware (tried with and without)
3. Use Inject ILogger in razor view

### Basic Information

- Version with issue: Publishing to Windows app 6.0.101-preview.9.1843
- Last known good version: n/a
- IDE: Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 5.0

- Platform Target Frameworks: 
UWP:  10.0.19041.21

Complete code and description can be found here:
https://stackoverflow.com/questions/69610206/net-maui-blazor-unable-to-inject-serilog

### Workaround

Newing-up Logger in razor page each time.

**Comment by Eilon** [comment]
Hi @julianadormon , I am not able to reproduce this.

Here's what I added to my CSPROJ (I picked the most recent package versions, I think):

```xml
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.2-dev-10289" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
```

And here's what I added to my `MauiProgram.cs`:

```c#
...
			Log.Logger = new LoggerConfiguration()
			 .Enrich.FromLogContext()
			 .WriteTo.Debug()
			 .WriteTo.File(path: @"C:\temp\serilog.log")
			 .CreateLogger();

...

			services.AddLogging(logging =>
			{
				logging.AddSerilog(dispose: true);
			});
```

And then in one of my `.razor` files I have this code:

```razor
@page "/"
@using Microsoft.Extensions.Logging
@using Serilog
@inject ILogger<Index> logger

<h1>This is the count in the main app: @count</h1>
<button @onclick="Increment">Increment</button>

@code {
    int count = 0;

    void Increment()
    {
        count++;

        logger.LogInformation("Add Job initialized");
        Log.Information("Add Job initialized (static method call)");
    }
}
```

And when I run the app and click the button to call `Increment()` on the counter I see this in the VS debug output:

```
Maui.Controls.Sample.Pages.Blazor.Index: Information: Add Job initialized
[11:44:23 INF] Add Job initialized
[11:44:23 INF] Add Job initialized (static method call)
```

And I have the file `c:\temp\serilog.log` created with these contents:

```
2021-12-08 11:43:33.908 -08:00 [WRN] Replaced an existing DispatcherProvider with one from the service provider.
2021-12-08 11:44:23.144 -08:00 [INF] Add Job initialized
2021-12-08 11:44:23.176 -08:00 [INF] Add Job initialized (static method call)
```
