### ISSUE TITLE
[Bug] BlazorWebView not provide "MediaPlaybackRequiresUserGesture"

### ISSUE THREAD

**Issue by Asyvix** [dotnet/maui#3033]
if play audio from javascript in Android, it needs set "setMediaPlaybackRequiresUserGesture" as false.

but i think blazorwebview's defualt value is true and not provide to set it's value.

Xamarin(and maybe maui) webview support "Settings.MediaPlaybackRequiresUserGesture" property.
So I think need to change the default or expose the setting in BlazorWebView as well.

**Comment by dannyBies** [comment]
I ran into the same issue and have created a hacky workaround for this:
```
public class MauiBlazorWebViewHandler: BlazorWebViewHandler
{
    protected override WebView CreateNativeView()
    {
        var aWebView = new AWebView(Context!)
        {
#pragma warning disable 618 // This can probably be replaced with LinearLayout(LayoutParams.MatchParent, LayoutParams.MatchParent); just need to test that theory
            LayoutParameters = new Android.Widget.AbsoluteLayout.LayoutParams(LayoutParams.MatchParent, LayoutParams.MatchParent, 0, 0)
#pragma warning restore 618
        };

        AWebView.SetWebContentsDebuggingEnabled(enabled: true);

        if (aWebView.Settings != null)
        {
            aWebView.Settings.MediaPlaybackRequiresUserGesture = false;
            aWebView.Settings.JavaScriptEnabled = true;
            aWebView.Settings.DomStorageEnabled = true;
        }

        var _webViewClient = GetWebViewClient();
        aWebView.SetWebViewClient(_webViewClient);

        var _webChromeClient = GetWebChromeClient();
        aWebView.SetWebChromeClient(_webChromeClient);

        return aWebView;
    }
}
```
Then configure the handler in `MauiProgram`:
```
builder.ConfigureMauiHandlers(handlers =>
{
    handlers.AddHandler<IBlazorWebView, MauiBlazorWebViewHandler>();
 })
```
Code based on: https://github.com/dotnet/maui/blob/7ebd79a302da71c266bab595a0c8211afe5a8321/src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs#L26
With this change I can now play audio from JS. Unfortunately this means you're unable to dispose `_webViewClient` and `_webChromeClient` and thus it would be better if this was supported out of the box or changing these properties to protected so we can customize the behaviour ourselves.

**Comment by Asyvix** [comment]
make play audio fuction on javascript,
and call that from SignalR Client or timer.

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up. We're going to document how to configure webview options as part of this issue: https://github.com/dotnet/maui/issues/6823
