### ISSUE TITLE
[Bug] OnChildMeasureInvalidated method is Not triggered at runtime.

### ISSUE THREAD

**Issue by RasikaPalanisamy** [dotnet/maui#3043]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
Duplicate of #3044
