### ISSUE TITLE
[Bug] OnChildMeasureInvalidated Method is not triggered at runtime.

### ISSUE THREAD

**Issue by RasikaPalanisamy** [dotnet/maui#3044]
Description
OnChildMeasureInvalidated is not triggered at runtime when add content using DataTemplate create content. Inside the DataTemplate when we add the Label directly OnChildMeasureInvalidated method is triggered. But when we add the Grid or stacklayout as parent for label inside the DataTemplate OnChildMeasureInvalidated is not triggered.

Note:
we are developing custom component which has AutoFit item height logic. To achieve this , "OnChildMeasureInvalidated" method should be invoked to update the height when user changed content or style at run time.

Steps to Reproduce

1. Run the sample
2. Click the change button
3.  Note the OnChildMeasureInvalidated() method  is not triggered.

Basic Information

MAUI Preview 9

Android : API 28

### Screenshots
![image](https://user-images.githubusercontent.com/92015119/138054427-26aa3bec-78b2-4a25-b0f5-66b21c0e333f.png)
![image](https://user-images.githubusercontent.com/92015119/138054614-299cb154-fc24-4d37-81d6-52e2ab9fcb8a.png)

### Reproduction Link
[GettingStarted.zip](https://github.com/dotnet/maui/files/11246579/GettingStarted.zip)

**Comment by wenwen60** [comment]
Reproduce on Android 11 with VS2022 17.2.0 Preview 2.0 [32215.517.main], attach repro sample
[MauiApp8.zip](https://github.com/dotnet/maui/files/8184269/MauiApp8.zip).

**Comment by jayaleshwari** [comment]
HI team,

Any update on above

**Comment by jayaleshwari** [comment]
Hi Team,

Can you please update on this

**Comment by jayaleshwari** [comment]
Hi Team,

Any update on this

**Comment by John-Prass** [comment]
Hi Team,

Can you please update on this

**Comment by hartez** [comment]
We don't have anyone currently scheduled to work on this.

Out of curiosity, why do you need `OnChildMeasureInvalidated` for this? If the Label is a descendant of the ContentViewExt, then changing the size of the Label should trigger the layout for the ContentViewExt. If you override the ContentViewExt's `MeasureOverride` and `ArrangeOverride` methods, are those called?

**Comment by XamlTest** [comment]
Verified this issue on Visual Studio Enterprise 17.6.0 Preview 2.0. Repro on Android emulator (13.0-API 33) with below Project:
[3044.zip](https://github.com/dotnet/maui/files/11189548/3044.zip)

**Comment by RasikaPalanisamy** [comment]
@hartez, As I have mentioned in the issue, we are trying to implement AutoFit item height logic for our custom component. To achieve this , "OnChildMeasureInvalidated" method should be invoked to update the height when user changed content or style at run time. 
Yes, MeasureOverride and ArrangeOverride methods are called.

**Comment by RasikaPalanisamy** [comment]
Hi Team,
In this comment, https://github.com/dotnet/maui/issues/3044#issuecomment-1511007880,
I have already updated details to the queries, still the issue was closed automatically. 
This issue needs to be fixed. Can you please re-investigate on this?

**Comment by samhouts** [comment]
Duplicate of #14741

**Comment by hartez** [comment]
> @hartez, As I have mentioned in the issue, we are trying to implement AutoFit item height logic for our custom component. To achieve this , "OnChildMeasureInvalidated" method should be invoked to update the height when user changed content or style at run time. Yes, MeasureOverride and ArrangeOverride methods are called.

If `MeasureOverride` is called, why not update the height then?
