### ISSUE TITLE
[Bug] Dynamic changes inside navigation page not getting reflected in UI

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#3046]
### Description
Changing any content or adding a element to the page that is of type NavigationPage does not reflect in UI until we manually hotreload or change the device orientation.

App.xaml.cs: MainPage = **new NavigationPage(new MainPage());**

MainPage.xaml.cs
	public partial class MainPage : ContentPage
	{
		int count = 0;

		public MainPage()
		{
			InitializeComponent();

			//this.Content = new Button() { Text = "Dummy Label"};
		}

		private void OnCounterClicked(object sender, EventArgs e)
		{
			count++;
			CounterLabel.Text = $"Current count: {count}";

			SemanticScreenReader.Announce(CounterLabel.Text);

			**this.Content = new Button() { Text = "Dummy Label" };**
		}
	}

Sample:
[MauiApp33.zip](https://github.com/dotnet/maui/files/7381240/MauiApp33.zip)

**Comment by PureWeen** [comment]
@PaulAnderson02 what platform did you see this on? I tested on the latest and it looks like this is fixed
