### ISSUE TITLE
Only Android dll's are produced when building a MAUI library

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#3049]
I have a MAUI library that targets iOS, Android and Windows

`<TargetFrameworks>net6.0-ios;net6.0-android;net6.0-windows10.0.19041</TargetFrameworks>`

It also has

`    <UseMaui>true</UseMaui>`
`    <SingleProject>true</SingleProject>`

When building the project both the iOS and folders are empty

bin\Debug

![image](https://user-images.githubusercontent.com/17496741/138132759-1530523a-f299-4595-9871-c3067604019b.png)

Android is ok

![image](https://user-images.githubusercontent.com/17496741/138132846-47078389-b437-4c27-838a-4f20741440b5.png)

But iOS and Windows have just an empty "ref" folder

![image](https://user-images.githubusercontent.com/17496741/138133012-56199429-1bfe-4f09-9050-2295820f1ef1.png)

Visual Studio Version 17.0.0 Preview 6.0 and the _Single-project MSIX Packaging tools..._ extension is installed.

**Comment by Eilon** [comment]
Just to check, if you create a brand new .NET MAUI project in its own new solution, does everything work correctly?

**Comment by arivoir** [comment]
In an MAUI application with a single project (No libraries) the compilation seems to work but deploying has the famous "Need recipe file" bug. And the device is always in "Windows Machine" no matter the chosen Framework.

After adding a library and building that library I'm seeing it creates the dll's for all the platforms, which is different from what I had seen in another project that always compiled Android.

If instead of building the library I build the MAUI app referencing the library  in "ios" says

> The Build Agent 'Build 1.4.0.4' is not running on the Mac. Please ensure that the assembly versions between the XMA Agents and the XMA clients matches. The build can't continue without a compatible Build Agent

Which is funny because I previously compiled the application and didn't complain about this until I referenced a library.

When building the MAUI app in Android the application only produces the Android dlls and the library produces the dll for all the platform, it doesn't run because of the "Need recipe file" bug.

In mac-catalyst seems to work like android, it compiles but it doesn't run.

Tried again with iOs and shows the same error. Strange it compiles mac-catalyst but not iOs.

I didn't try adding native libraries, but I can continue if you need.

**Comment by arivoir** [comment]
I tried commenting "net6.0" from the TArgetFrameworks of the library project, 
`    
		<TargetFrameworks>net6.0-ios;net6.0-android;net6.0-maccatalyst</TargetFrameworks>
`

and when changed the "Framework" to "iOS" it got populated with the iPhone simulators

![image](https://user-images.githubusercontent.com/17496741/139499946-904775d2-7c7d-4188-8f4d-f47ae9bdf77b.png)

But the Framework menu disappeared and I can't get back to Android

**Comment by arivoir** [comment]
I tried running it, but the _"The Build Agent 'Build 1.4.0.4' is not running on the Mac."_ error appeared again, and the menu got back to the original state

![image](https://user-images.githubusercontent.com/17496741/139500311-69a76409-13ec-4861-a07d-57453be1c127.png)

**Comment by arivoir** [comment]
This is still broken on MAUI Preview 10

If you compile the MauiLib2 you  get 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0006	Metadata file 'C:\Users\arivo\source\repos\Nueva carpeta\iOSLib3\bin\Debug\net6.0-ios\ref\iOSLib3.dll' could not be found	MauiLib2 (net6.0)	C:\Users\arivo\source\repos\Nueva carpeta\MauiLib2\CSC	1	N/A

If compile the app

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0006	Metadata file 'C:\Users\arivo\source\repos\Nueva carpeta\iOSLib3\bin\Debug\net6.0-ios\ref\iOSLib3.dll' could not be found	MauiLib2 (net6.0)	C:\Users\arivo\source\repos\Nueva carpeta\MauiLib2\CSC	1	N/A
> Error	CS0006	Metadata file 'C:\Users\arivo\source\repos\Nueva carpeta\iOSLib3\bin\Debug\net6.0-ios\ref\iOSLib3.dll' could not be found	MauiApp5 (net6.0-android)	C:\Users\arivo\source\repos\Nueva carpeta\MauiApp5\CSC	1	N/A
> Error	CS0006	Metadata file 'C:\Users\arivo\source\repos\Nueva carpeta\MauiLib2\bin\Debug\net6.0-ios\ref\MauiLib2.dll' could not be found	MauiApp5 (net6.0-android)	C:\Users\arivo\source\repos\Nueva carpeta\MauiApp5\CSC	1	N/A

Depending on the order you get different results, and things that didn't work start working, really unpredictable

[MauiApp.zip](https://github.com/dotnet/maui/files/7507492/MauiApp.zip)

**Comment by arivoir** [comment]
Please test MAUI libraries referencing native libraries, there are all kind of problems

**Comment by shimingsg** [comment]
Not reproducible with windows 10.0.19041.
