### ISSUE TITLE
[Bug] .NET MAUI Blazor App crashed on physical device

### ISSUE THREAD

**Issue by RaspeR87** [dotnet/maui#3060]
### Description
If I build empty **.NET MAUI Blazor App (Preview)** VS template with command **dotnet build -f net6.0-android -c Release** and then install .apk file into one of the physical Android 10 Phone and then run it, it always crash after startup.

So the point is that I want to create .apk for my Blazor MAUI project, which could be send to some phones to test it.

If I try same process with empty **.NET MAUI App (Preview)** and same command **dotnet build -f net6.0-android -c Release**  it works well on physical Android Phone.

I think there is a problem with some Blazor component or something. Because of that I try to clear all blazor stuff (script include blazor.webview.js etc.) inside index.html file and leave only this inside it:

```
<!DOCTYPE html>
<html>
<head>
</head>

<body>
    Živjo!
</body>

</html>
```

But this doesn't help. Screen attached below is shown just for one second and then app crashed.
![Screenshot_20211021_130820_com huawei android launcher](https://user-images.githubusercontent.com/14901702/138265958-a7bdfde6-f436-4a98-adca-9765bdb72636.jpg)

### Steps to Reproduce

1. Create default .NET MAUI Blazor App Visual Studio template
2. run command **dotnet build -f net6.0-android -c Release**
3. Copy .apk from "bin/Release/net6.0-android" folder
4. install it into some physical Android phone
5. run it

### Expected Behavior
Run without problem like **.NET MAUI App** template.

### Actual Behavior
App is crashing all time.

### Basic Information

- Version with issue: MAUI P9
- Last known good version:
- IDE: VS 2022 P6
- Platform Target Frameworks: 
  - Android: API 29

**Comment by aokocax** [comment]
Hello https://github.com/dotnet/maui/issues/2246#issuecomment-942080171

**Comment by CutAndDry** [comment]
the `<AndroidLinkMode>None</AndroidLinkMode>` fix dident work for me untill I restarted my Visual studio so if any one else is trying this and its not working they might have to do the same 

took me way to long to find this out 
thank you 
![image](https://user-images.githubusercontent.com/80890007/142286219-99c77a9e-b409-44bb-8d28-fa81d22418a9.png)

**Comment by SteveSandersonMS** [comment]
I've been trying to investigate this, and I do get a crash in the Android emulator in release builds. It looks as if this may be coming from something deeper in MAUI rather than BlazorWebView, so have filed https://github.com/dotnet/maui/issues/4262. If it is a BlazorWebView issue, we'll need help understanding how to track down which .NET code might be involved, since the error trace isn't about .NET at all but rather is phrased in terms of Java code.

Until there is a response to https://github.com/dotnet/maui/issues/4262 I can't take other action, so am going to reschedule this issue for the next preview.

**Comment by soundaranbu** [comment]
Same problem when I tried the .NET Podcast app. I'm updating the issues that I faced here 
https://github.com/microsoft/dotnet-podcasts/issues/30

**Comment by danroth27** [comment]
@SteveSandersonMS Now that #4262 is resolved and closed, should this be closed as well? Or is there more to do here?

**Comment by SteveSandersonMS** [comment]
Yes let's close it.
