### ISSUE TITLE
[Bug] CollectionView with grids and stacklayouts on itemtemplate

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3062]
### Description
I am trying to create an itemtemplate for collectionviews items with three columns and two rows:
FirstRow:
- First column:
- An image and a text
- Second Column:
   - An image and there labels on the right
- Thrid Column
   - An image

Second row:
- A label with a long text with a maximum of three lines with TailTruncation
- A separator

### Steps to Reproduce

1. Run the [CollectionviewGridSTack.zip](https://github.com/dotnet/maui/files/7388611/CollectionviewGridSTack.zip) sample on each platforms (UWP, Android, iOS, and MAC)

### Expected Behavior
Interface painted as described in the description:
![image](https://user-images.githubusercontent.com/603023/138269951-97b3727c-21e0-4c50-bb4a-a3ce95852a85.png)

### Actual Behavior
In Windows it appears:
![image](https://user-images.githubusercontent.com/603023/138270030-1dd9a6c1-bc60-427d-8188-53efd53ba095.png)
And if I rescale the app the separator and the little dotnet_bot disappears 
![image](https://user-images.githubusercontent.com/603023/138270228-278473e6-1297-40e7-9e25-10d1b13d7dd7.png)

In Android:
![image](https://user-images.githubusercontent.com/603023/138270323-37df8359-0a4e-4b9e-b32f-9195542ead61.png)

In Mac:
![image](https://user-images.githubusercontent.com/603023/138270381-5ec04320-361c-4fd1-b8f4-96759bca0c7c.png)

In iOS:
![image](https://user-images.githubusercontent.com/603023/138270462-c73299d3-8f2e-43a2-a97f-ec3e7e36b2e3.png)

Seems as there are some issues with the measures on platforms.
For sure, I am not doing all things well as I have been try to find a workaround, I know is not a good idea to nest grids, stacklaouts to create a grid layout, but i am trying to find a workaround for that

### Basic Information

- Version with issue: Preview 9
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 5.0

**Comment by shimingsg** [comment]
Verified Repro with windows 10.0.19041. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EakFOmNFcdVNuPszC-BHI38BtBmGznzU8H4wpH77zT5hvQ?e=vwhdhy

**Comment by VincentBu** [comment]
repro on Windows and Android with vs [32506.368.main]. Here is the example:
[MauiApp3062.zip](https://github.com/dotnet/maui/files/8644735/MauiApp3062.zip)

@kristinx0211 would you like to verify it on IOS and mac?

**Comment by samhouts** [comment]
No longer repros on 6.0.300-rc.4.5742. Appears identical on iOS, Windows, and Android with no clipping and no elements disappearing on resize or rotate.
