### ISSUE TITLE
[Bug] Consuming WCF Service Problem System.Servicemodel

### ISSUE THREAD

**Issue by mwbinderholz** [dotnet/maui#3073]
### Description
I am trying convert the Xamarin WCF example to Maui but I have Problems with it: https://github.com/xamarin/xamarin-forms-samples/tree/main/WebServices/TodoWCF

When I am opening my project on an Android API 28 Emulator and try to link my WCF Client library it throws an Exception "failed to load assembly System.ServiceModel.dll"

I tried installing the Nuget Packages System.ServiceModel.Http (4.8.1) and System.ServiceModel.Primitives (4.8.1)

![image](https://user-images.githubusercontent.com/88394046/138436187-51561a75-3ec1-4ced-aa2a-650e6f210f03.png)
 
But it is not possible to reference this for Android.

### Steps to Reproduce

1. Make a new Maui Project
2. Add a second project as class library .net framework 4.8 with following Cs Files from the xamarin sample:
   ISoapService.cs | SoapService.cs | TodoItemManager.cs | TodoItem.cs | Constants.cs
3. Set project reference in Maui Project to second project
4. Call TodoManager = new TodoItemManager (new SoapService ()); somewhere in the Maui Project
5. Error

You do not have to actually set up a service. It already throws the Exception as soon as he tries to load the second project in the Maui project.

### Basic Information

Version with issue: Maui 6.0.101-preview.9.1843 .NET 6.0
IDE: Visual Studio 2022 Version 17.0.0 Preview 5.0
Affected Devices: Emulator API 28

Maybe I am on the wrong path to consume Wcf Webservices in Maui. Please help.

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?.

**Comment by mwbinderholz** [comment]
Hello,

I hope this Sample Solution is sufficient.

If you need further info, just write.

Regard
[GitHubWcfIssueSample.zip](https://github.com/dotnet/maui/files/7495704/GitHubWcfIssueSample.zip)
s
