### ISSUE TITLE
[Bug] Shell.BackgroundColor in UWP and iOS

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3077]
### Description
Setting Shell.BackgroundColor on a contentpage take no effect in UWP neither iOS
### Steps to Reproduce

1. Run [ShellIssues.zip](https://github.com/dotnet/maui/files/7396538/ShellIssues.zip) on Windows and iOS

### Expected Behavior

The background of the title in "First page" in windows must be in Green
The background of the title in "First page" in iOS must be in Green

### Actual Behavior
The background of the title in "First page" in windows is light blue
The background of the title in "First page" in iOS is white

### Basic Information

- Version with issue: Maui Preview 9
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 5.0

### Screenshots

Windows: 
![image](https://user-images.githubusercontent.com/603023/138443724-bf358f54-2276-4855-8a54-3e14cecb236d.png)

iOS:
![image](https://user-images.githubusercontent.com/603023/138443740-54401fd7-5737-42fe-8eb0-1d61c72e35ef.png)

**Comment by kristinx0211** [comment]
Verified repro on iPhone 13 pro max 15.2  and window 10.0.19041 with the above project.

**Comment by Redth** [comment]
Still doesn't appear to do the expected thing in this sample.
