### ISSUE TITLE
[Bug] Shell.ForegroundColor in WINUI different from other platforms

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3078]
### Description
Setting Shell.ForegroundColor on a contentpage take no effect in UWP
### Steps to Reproduce

1. Run [ShellIssues.zip](https://github.com/dotnet/maui/files/7396538/ShellIssues.zip) on Windows

### Expected Behavior

The Foreground of the hamburger menu in windows must be yellow

### Actual Behavior
The Foreground of the hamburger menu in windows is black

### Basic Information

- Version with issue: Maui Preview 9
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 5.0

### Screenshots
UWP: 
![image](https://user-images.githubusercontent.com/603023/138444089-a35b2594-4676-4463-b34d-778f94a6f7ce.png)

Android:
![image](https://user-images.githubusercontent.com/603023/138444111-5fabe3ad-9f20-4ba9-81da-bc87747aa837.png)

Mac: 
![image](https://user-images.githubusercontent.com/603023/138444129-4bc27031-38e7-4992-8702-e721096079ed.png)

iOS: 
![image](https://user-images.githubusercontent.com/603023/138444139-ab20f475-bbe7-4efd-9595-a3bdf3459aa8.png)

**Comment by kristinx0211** [comment]
Verified Repro with windows 10.0.10941. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EZ_GTS_MPdpKnW7KA0tIeLkBSx1_Aze3WqZxDva3tFnHXg?e=fEdYSL

**Comment by shimingsg** [comment]
repro proj could be found here:
[3078.zip](https://github.com/dotnet/maui/files/8129910/3078.zip)

**Comment by japarson** [comment]
@samhouts @Redth I'm not able to repro this issue in a fresh MAUI project. The hamburger foreground is as expected.
![image](https://user-images.githubusercontent.com/59936622/217365817-777d8048-7855-44cc-93d7-9793b28dd932.png)

TFM: `net7.0-windows10.0.19041.0`
WinAppSDK: `Microsoft.WindowsAppSDK (1.2.221209.1)`
VS: `Version 17.6.0 Preview 2.0 [33406.452.main]`

![image](https://user-images.githubusercontent.com/59936622/217366838-ace0eaf6-2411-4ca0-9fc9-91c0ddb385d2.png)

**Comment by samhouts** [comment]
@japarson Great! You fixed it! 😂 

@juanlao Please confirm that this is working as intended for you. Thank you!!
