### ISSUE TITLE
[Bug] Toolbar item on a content page behaves different on platforms

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3079]
### Description
Adding a toolbar item to a content page behaves differently on platforms
### Steps to Reproduce

1. Run [ShellIssues.zip](https://github.com/dotnet/maui/files/7396538/ShellIssues.zip) on Windows, Android,, mac and ios

### Actual Behavior
UWP renders the text
Android does not render anything (if you tap on the second page and return to firstpage, the toolbaritem text flicker)
iOS renders the image
Mac renders the image

### Expected Behavior

Behaves the same on all platforms

### Basic Information

- Version with issue: Maui Preview 9
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 5.0

### Screenshots
UWP: 
![image](https://user-images.githubusercontent.com/603023/138444971-4fca9e3e-8c12-4c8f-bc8c-4c5763d04151.png)

Android:
![image](https://user-images.githubusercontent.com/603023/138444990-0e747345-f8ec-4ad4-b870-d5bb5ceeb960.png)

Mac: 
![image](https://user-images.githubusercontent.com/603023/138445002-64d23347-cec0-4cd7-92f7-e5701a8ae965.png)

iOS: 
![image](https://user-images.githubusercontent.com/603023/138445020-f29636a6-3e00-4b4a-b810-296c811579a5.png)

**Comment by kristinx0211** [comment]
Verified repro on iPhone 13 pro max 15.2, Android 11 and window 10.0.19041 with the above project.

**Comment by PureWeen** [comment]
This should be fixed with RC1

If it's still an issue please let me know and we can re-open @juanlao
