### ISSUE TITLE
Clip property is not working properly after MAUI preview 9 release

### ISSUE THREAD

**Issue by E-Mani** [dotnet/maui#3081]
### Description

I am clipping the BoxView/ContentView using the RoundRectangeGeometry and PathGeometry, clipping is not working properly. But it was working fine before the preview 9 release.

### Steps to Reproduce

1. Add a BoxView in a vertical stacklayout or any other layout 
2. Clip the BoxView with RoundRectangleGeometry.
3. BoxView not clipped properly with corner radius.

### Expected Behavior
BoxView/ContentView must clip correctly.

### Actual Behavior
BoxView/ContentView is not clipping correctly.

### Basic Information

MAUI preview 9

### Screenshots
![Clip Issue](https://user-images.githubusercontent.com/35995426/138454002-94fc6082-af70-458e-85b4-45147c1c3508.jpg)

### Reproduction Link
Sample link: 
[ClipIssue.zip](https://github.com/dotnet/maui/files/7397082/ClipIssue.zip)

**Comment by wenwen60** [comment]
Reproduce using the above project on 17.2.0 Preview 2. Tested with Android 11.

**Comment by jsuarezruiz** [comment]
The issue should be fixed with latest Preview 14. I am going to close this issue but open a new one if can reproduce the issue again or find a another one.
