### ISSUE TITLE
[Bug] Ain't no shadow like a Windows shadow

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#3082]
### Description

I've been experimenting with shadows, and they render beautifully on Android:

```
<Image Source="dotnet_bot.png"
       WidthRequest="250"
       HeightRequest="310">
    <Image.Shadow>
        <Shadow Brush="Black"
                Offset="20,20"
                Radius="40"
                Opacity="0.8" />
    </Image.Shadow>
</Image>
```

![image](https://user-images.githubusercontent.com/8092460/138461921-73ded317-33bb-42d9-b12b-3aec61a1e056.png)

Then I switched to Windows:

![win1](https://user-images.githubusercontent.com/8092460/138462055-44c387b7-7084-4875-868f-44d357ff09c6.PNG)

'Nuff said.

### Steps to Reproduce

1. Run the attached sample on Windows.

### Expected Behavior

Shadows as per on Android.

### Actual Behavior

The horror. The horror.

### Basic Information

- Version with issue: preview.9.1843
- IDE: VS 17.0 P6
- Platform Target Frameworks:
  - Android: API 31
  - Win: 10.0.18362.0

### Reproduction Link

[ShadowsDemo.zip](https://github.com/dotnet/maui/files/7397479/ShadowsDemo.zip)

**Comment by davidortinau** [comment]
Samsies. 6.0.101-preview.10.2068

<img width="383" alt="image" src="https://user-images.githubusercontent.com/41873/139546524-5600fd5c-f88f-4c82-a59f-36da129882e0.png">

![image](https://user-images.githubusercontent.com/41873/139546722-96ad1f70-5207-4ce7-b03c-4b70949931db.png)

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/ERqLL7tup3pHg_F9ntkXW-wB4-sbM9OO6-AFsew4Cuqgfw?e=e3KaZ7

**Comment by VSadov** [comment]
I am able to reproduce the bug
