### ISSUE TITLE
[Bug] Windows clipping ran amok

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#3083]
### Description

I've been experimenting with shadows, and they render beautifully on Android, particularly when combined with clipping:

```
<Image
       Source=https://aka.ms/campus.jpg
       Aspect="AspectFill"
       HeightRequest="220"
       WidthRequest="220"
       HorizontalOptions="Center">
    <Image.Clip>
        <EllipseGeometry Center="220,250"
                         RadiusX="220"
                         RadiusY="220" />
    </Image.Clip>
    <Image.Shadow>
        <Shadow Brush="Black"
                Offset="10,10"
                Opacity="0.8" />
    </Image.Shadow>
</Image>
```

![clipped-image](https://user-images.githubusercontent.com/8092460/138463179-f6525e6f-9e5e-445b-979d-653c909f4a46.png)

Then I switched to Windows:

![win2](https://user-images.githubusercontent.com/8092460/138463214-00499c09-100b-4457-9ec9-0755b15d028b.PNG)

I've logged the shadow issue in #3082. This issue is about the clipping having gone wrong.

### Steps to Reproduce

1. Run the attached sample on Windows.

### Expected Behavior

Second displayed object is a circular image with shadow.

### Actual Behavior

Clipping disaster for the second displayed object.

### Basic Information

- Version with issue: preview.9.1843
- IDE: VS 17.0 P6
- Platform Target Frameworks:
  - Android: API 31
  - Win: 10.0.18362.0

### Reproduction Link

[ShadowsDemo.zip](https://github.com/dotnet/maui/files/7397513/ShadowsDemo.zip)

**Comment by davidortinau** [comment]
Yeh, I'm seeing this in my WeatherTwentyOne app as well today. 6.0.101-preview.10.2068

Profile circle upper left:

![image](https://user-images.githubusercontent.com/41873/139545405-4d63ad30-01e2-449e-8bec-08cd10de0922.png)

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EfXQQeVa9GFAtsj2lY1ZXvYBZaTbO20q2ARZ303Le8omAQ?e=NnDZC3

**Comment by jsuarezruiz** [comment]
The second element is a clipped image also using a Shadow.

![issue-3083](https://user-images.githubusercontent.com/6755973/160587774-43f9f1a0-6918-4ace-981d-c788d5275a0a.gif)

The issue should be fixed with latest version. I am going to close the PR but, feel free to contact or open a new one if find any detail.
