### ISSUE TITLE
[Bug] Unable to install workloads

### ISSUE THREAD

**Issue by CalaxDev** [dotnet/maui#3087]
### Description

After the recent Update of Visual Studio I am no longer able to install MAUI workloads.
I am calling the following commands:

> C:\Users\me>dotnet --version
> 6.0.100-rc.2.21505.57
> 
> C:\Users\me>dotnet workload install maui
> Workload ID maui is not recognized.

Maui-Check results in the same error, sadly

### Steps to Reproduce

1. Install latest Visual Studio 2022 Preview according to the Documentation on the Microsoft Maui Instlal Page
2. Try to install maui workload

### Expected Behavior

Workload Installation should work out of the box after a fresh VS 2022 install.
Maui-Check is not working either

### Actual Behavior

Error resulting in "Workload maui not found"

### Basic Information

- Version with issue: VS2022 Preview 6.0 - dotnet version 6.0.100-rc.2.21505.57
- Last known good version: Preview 5.0
- IDE: Visual Studio 2022 - Latest Update (Preview 6.0)

### Screenshots

![image](https://user-images.githubusercontent.com/10726046/138516440-737bd151-ecd4-4bcd-833f-a32a15053755.png)

---

Does anyone face the same Problem? What am I doing wrong here?
I only updated from Preview 5.0 to 6.0 and, sadly, this broke my setup.

**Comment by nmase88** [comment]
double check you don't have a copy of dotnet/sdk in both Program Files and Program Files (x86) that was the issue I had that was causing these problems for me, spent a day banging my head against a wall before I discovered that.
Though good luck being able to do anything if you do get past that bit, as developing with maui doesn't seem to get any easier once you resolve the install issues.

**Comment by Z3roCoder** [comment]
> double check you don't have a copy of dotnet/sdk in both Program Files and Program Files (x86) that was the issue I had that was causing these problems for me, spent a day banging my head against a wall before I discovered that. Though good luck being able to do anything if you do get past that bit, as developing with maui doesn't seem to get any easier once you resolve the install issues.

Hey there,

I tried your suggestions, but I've even setup a brand new windows install and followed all the instructions both on here and maui-check, and am still getting the same error.

But thanks for the advice!

**Comment by jsuarezruiz** [comment]
Remove the previous workloads using this script https://github.com/Redth/dotnet-maui-check/blob/main/Clean-Old-DotNet6-Previews.ps1 (could have a mix of old versions).

And then, install again the workloads:

`dotnet workload install maui `

or

`dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.10.json`

Etc

**Comment by jsuarezruiz** [comment]
Could you share your errors?

**Comment by Z3roCoder** [comment]
> Could you share your errors?

It's the same as the ones in my screenshots above

"Workload ID xxx is not recognized"

where as xxx can be Maui, android-aot, or whatever else I try to install

**Comment by TanayParikh** [comment]
I'm having the same issue. This seems to be a dup of https://github.com/dotnet/maui/issues/3099
