### ISSUE TITLE
[Bug] Simple arithmetic operations taken too much in maui platform 

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#3100]
### Description

I have checked performance time for simple arithmetic operations in 200000 length for loop. 

**Maui** takes **750 ms.** 

But the same operation in **xamarin** takes only **110 ms.**  I have attached the code below, please find it. 

```
 <Label 
                Text="Time : "
                Grid.Row="2"
                FontSize="18"
                FontAttributes="Bold"
                x:Name="CounterLabel"
                HorizontalOptions="Center" />

        <Button 
                Text="Click me"
                FontAttributes="Bold"
                Clicked="Button_Clicked_1"
                HorizontalOptions="Center" />
```
```
private void Button_Clicked_1(object sender, EventArgs e)
        {
			float[] data = new float[200000];
			double value = 300;
			Random randomNumber = new Random();
			Stopwatch stopwatch = new Stopwatch();
			stopwatch.Start();

			for (int i = 0; i < 200000; i++)
			{
				if (randomNumber.NextDouble() > .5)
				{
					value += randomNumber.NextDouble();
				}
				else
				{
					value -= randomNumber.NextDouble();
				}

				data[i] = (float)Math.Round(value, 2) * 2.625f;
			}

			stopwatch.Stop();

			CounterLabel.Text = "Time : " + stopwatch.ElapsedMilliseconds.ToString() + " ms";
		}
```

### Steps to Reproduce

1. Run the sample
2. Click the button
3. See the taken time for this operation. 

### Expected Behavior

Maui have to do arithmetic operations in quicker than xamarin

### Actual Behavior

Xamarin completes the arithmetic quicker than Maui

### Basic Information

Visual Studio : Visual Studio 2022 Preview 5
Maui : Maui Preview 9

### Sample

[MauiApp6.zip](https://github.com/dotnet/maui/files/7410071/MauiApp6.zip)

**Comment by MuneeshKumarG** [comment]
Any update for this?

**Comment by hartez** [comment]
Try building in Release mode.

When I build your sample project in Release mode, the task completes in ~20ms on average, which is comparable to the same code in Forms in Release mode (~12 ms on average).

**Comment by MuneeshKumarG** [comment]
But now also, Xamarin Forms completes the arithmetic operations quicker than Maui. 

May I know the reason for this?
