### ISSUE TITLE
[Bug] Unexpected behavior when InvalidateMeasure is invoked in Android

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#3102]
### Description

Recently we have updated to Preview 9 and started to experience some unexpected behavior when InvalidateMeasure is invoked in Android. If we have a control inside a NavigationPage and InvalidateMeasure is called the Measure and Arrange phases of the control are not triggered. It is only observed if the control is inside NavigationPage in Preview 9 - with the previous release (Preview 8) everything is working as expected.

I have prepared a [sample](https://progresssoftware-my.sharepoint.com/personal/apopatan_progress_com/Documents/HelloMaui.zip) project that demonstrates the described behavior.

Do you have any suggestions for a workaround?

**Comment by activa** [comment]
I can confirm that this is indeed an issue. Calling `InvalidateMeasure()` will not trigger a Measure pass on Android when the page is used with `NavigationPage`

**Comment by jsuarezruiz** [comment]
Cannot longer reproduce the issue.
