### ISSUE TITLE
[Bug] iOS device test visual runner CollectionView crash

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#3104]
### Description

![image](https://user-images.githubusercontent.com/5375137/138742400-9695fc38-5296-4477-86a6-35509077c33d.png)

### Steps to Reproduce

1.  Run the device tests GUI on iOS using the latest main branch

### Expected Behavior

Doesn't crash and allows you to run tests

### Actual Behavior

Crashes directly after startup as it tries to populate the list of tests

**Comment by alexeystrakh** [comment]
I was able to reproduce this issue with the MAUI p11 `<MauiVersion>6.0.101-preview.11.2268</MauiVersion>`. I have a simple collection view bound to observable collection and view model logic to populate that collection view from a background thread. To post these updates on UI I use the following code:

```xaml
<CollectionView ItemsSource="{Binding Items}" />
```

```C# (ViewModel)

  public ObservableCollection<object> Items { get; } = new ObservableCollection<object>();

// update received from a remote server in a background thread
  private void OnItemUpdate(object item)
        {
            _mainThreadService.InvokeOnMainThread(() =>
            {
                var existing = Items.FirstOrDefault(s => s.Key == item.Key);
                if (existing != null)
                    existing.Update(item);
                else
                    Stocks.Add(item);
            });
        }

```

```C# (Service)
public void InvokeOnMainThread(Action action)
    => Application.Current.Handler.MauiContext.Services.GetService<IDispatcher>().Dispatch(action);
```

Without invoking the update on the main thread, there is no crash but also no data is reflected in CollectionView (this is another issue reported separately).

**Comment by alexeystrakh** [comment]
This issue is no longer reproducible after p12/p13 updates.
