### ISSUE TITLE
[Bug] ScrollView doesn't center a child if the child has Shadow defined

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/maui#3106]
### Description

ScrollView doesn't center a child if the child has Shadow defined. The issue is specific to Windows target only, works fine on Android (although the Android platform doesn't render the Shadow, another issue, not covered here).

### Steps to Reproduce

The provided solution reproduces the issue:
https://github.com/alexeystrakh/MauiShadowBreaksLayout

```
 <ScrollView BackgroundColor="Goldenrod">
        <Grid BackgroundColor="Aqua"
              WidthRequest="300"
              HeightRequest="200"
              VerticalOptions="Center"
              HorizontalOptions="Center">
            <Grid.Shadow>
                <Shadow
                   Radius="12"
                   Offset="6,6"
                   Opacity="0.75" />
            </Grid.Shadow>
        </Grid>
    </ScrollView>
```

1. Clone and open the provided solution
2. Switch to Windows Machine / Windows target
3. Run the sample with the [Shadow enabled](https://github.com/alexeystrakh/MauiShadowBreaksLayout/blob/main/MainPage.xaml#L12-L17)

### Expected Behavior

![image](https://user-images.githubusercontent.com/3697084/138760931-2abed478-e91d-4784-b875-faeb4f4467cc.png)

### Actual Behavior

<img width="862" alt="shot_211025_123906" src="https://user-images.githubusercontent.com/3697084/138760946-257b6fd4-a696-4618-b9ec-909d3c2b50af.png">

### Basic Information

- Version with issue: 6.0.100-rc.2.21505.57
- Last known good version: NA
- IDE: VS2022 - Preview 5
- Platform Target Frameworks: iOS, Android, Windows

### Reproduction Link

https://github.com/alexeystrakh/MauiShadowBreaksLayout

### Workaround

Not to use Shadow

**Comment by v-xiaofchen** [comment]
Not reproducible with 17.2.0 Preview 2.0 [32209.335.main] using Windows and above project. works fine
![Picture14](https://user-images.githubusercontent.com/99376012/155677413-7afa97c4-38ff-49d1-a2d5-0de4fd121c1e.png)
