### ISSUE TITLE
[Bug] Borders in UWP does not render

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3113]
### Description
Render on UWP seems have some issue with borders.
### Steps to Reproduce

1. Run [Borders.zip](https://github.com/dotnet/maui/files/7419646/Borders.zip) in UWP
2. Tap on "Click me"

### Expected Behavior
Counter gets incremented
### Actual Behavior
Counter label with border disapear
### Basic Information

- Version with issue: PReview 9
- IDE:Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 5.0

### Screenshots
Before tap on clickme: 
![image](https://user-images.githubusercontent.com/603023/138916684-de1e264f-73a8-448d-b543-e7f29d231465.png)

After tapped:
![image](https://user-images.githubusercontent.com/603023/138916721-c50645cc-4f8d-4d2a-9c25-5e89784ba5e7.png)

**Comment by NogginBox** [comment]
Is this related to #3791?

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EfuUgEtcn-VDlJA4ddKh9HUBWBwG7GPppY7iFgFbOWvh7Q?e=VLvoEf

**Comment by VSadov** [comment]
Fixed in #5324
