### ISSUE TITLE
Creating MAUI app called "MauiApp" results in broken project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3114]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Creating-MAUI-app-called-MauiApp-resul/1563181)._

---
[severity:It bothers me. A fix would be nice]
The default MAUI app project name is "MauiApp1". I don't like the number so I just called it "MauiApp". That results in a project with many build failures.

! [image.png] (https://aka.ms/dc/image?name=B3ce9a9b53d684972bd710873b30150f1637707928325277132_20211025-140712-image.png&tid=3ce9a9b53d684972bd710873b30150f1637707928325277132)

REPRO:
1. New project -> .NET MAUI App (Preview) -> Next
2. Change "MauiApp1" to "MauiApp" -> Create
3. Build

RESULT:
See previous screenshot for error list

EXPECT:
The generated code from the template shouldn't use a system class called MauiApp if the namespace is now MauiApp, they conflict. MauiApp the class needs to be fully qualified, or prevent me from naming my project MauiApp.

---
#### Feedback Bot on 10/26/2021, 00:46 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I don't think there is any real fix for this, apart from what Eilon is mentioning with verbosing a lot about our template. This is behavior of the .NET ecosystem. Using the same names will confuse the system. 

I feel this won't impact a lot of people and it's easy to get around by using a different name. Closing this for now.
