### ISSUE TITLE
[Bug] VerticalAligment not working on SearchBar, Editor and Label for 

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#3119]
### Description

We added code to set the VerticalAligment for some controls on WINUI but it's not working as expected .

This is related with pr's #2723 #2738

### Steps to Reproduce

1. Run Sample app from MAUI repo

### Expected Behavior

Text should center vertical

### Actual Behavior

Text vertical aligment doesn't change

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EWyCWjUyIXxOiH-wmmcSz5YBhK7ADiqkMWjsFYL_5oEqRg?e=FfNApc

**Comment by bricelam** [comment]
Editor appears to be working correctly now. SearchBar and Lable still broken.

![image](https://user-images.githubusercontent.com/1226749/159067422-ddb8fa61-18b3-40d0-83b4-e3642fe8876a.png)

**Comment by bricelam** [comment]
Fixing **Label** will require introducing a surrounding parent element (like Border) before VerticalAlignment can take effect.

Fixing **SearchBar** will require drilling down into the AutoSuggestBox template to set VerticalAlignment on a child element. This is what Editor does:

https://github.com/dotnet/maui/blob/35af6fb7dfec887f6ae72106916ef1e101d06371/src/Compatibility/Core/src/Windows/FormsTextBox.cs#L172

https://github.com/dotnet/maui/blob/35af6fb7dfec887f6ae72106916ef1e101d06371/src/Compatibility/Core/src/Windows/FormsTextBox.cs#L192

**Comment by bricelam** [comment]
For some reason, VerticalAlignment isn't working TextBlock even when it's inside a WrapperView. This may be a red herring, but for some reason, TextBlock.Parent is null even after adding it to WrapperView.Children.

**Comment by bricelam** [comment]
**SearchBar** was fixed by PR #5482

**Comment by bricelam** [comment]
This appears to have something to do with HeightRequested. VerticalTextAlignment works when that's not set.

Similar behavior is exhibited in a vanilla WinUI project when TextBlock.Height is specified instead of deferring to the Height of its container.

**Comment by bricelam** [comment]
Got a fix! Preparing a PR...
