### ISSUE TITLE
[Bug] WebView Related event failure, Android and cookie Setting failure

### ISSUE THREAD

**Issue by ni-xue** [dotnet/maui#3130]
### Description
WebView Related event failure, Android and cookie Setting failure

- Version with issue: maui 9.0
- Last known good version:
- IDE: 2022 7.0
  - Android:  10
- Android Support Library Version:  not applicable
- Affected Devices: Android

**Comment by ni-xue** [comment]
@Eilon  ok,Let me give you an overview of the information on this page

**Comment by ni-xue** [comment]
Here are the relevant codes
1. It's hard to understand that the same code in earlier versions would have shown exactly the right behavior, but now it has completely changed
2. I also packaged it in the 0.86 version. At present, the device is still normal. After updating 0.9, the new package can not be used directly

C# `public partial class ZmPage : ContentPage
    {
        public readonly Size size;
        public ZmPage(string token)
        {
            InitializeComponent();

            size = Device.Info.ScaledScreenSize;

            //NavigationPage.SetHasNavigationBar(this, false);

            if (WebZm.Cookies is null) WebZm.Cookies = new System.Net.CookieContainer();

            var cookie = new System.Net.Cookie("Session", token, "/", "cs.com") { HttpOnly = true };

            WebZm.Cookies.Add(cookie);

            WebZm.Navigating += OnNavigating;

            WebZm.WidthRequest = size.Width;
            WebZm.HeightRequest = size.Height;

            WebZm.Source = "https://cs.com/User";

            //var android = WebZm.On<Microsoft.Maui.Controls.PlatformConfiguration.Android>();
            //android.EnableZoomControls(true);
            //android.DisplayZoomControls(true);
        }

        private async void OnNavigating(object sender, WebNavigatingEventArgs e) //Not triggered
        {
        }

        protected override void OnAppearing()
        {
            IsOverride = true;

            base.OnAppearing();
        }

        private bool IsOverride = true;
        protected override Size ArrangeOverride(Rectangle bounds)  //Not triggered
        {
            if (IsOverride)
            {
                base.ArrangeOverride(bounds);
                IsOverride = false;
            }
            return bounds.Size; // base.ArrangeOverride(bounds);
        }

        async void OnRefreshing(object sender, EventArgs e)
        {
            RefreshView refreshView = sender as RefreshView;

            WebZm.Reload();

            await Task.Delay(500);

            refreshView.IsRefreshing = false;
        }
    }`


Xml：
`        <RefreshView RefreshColor="Green" Refreshing="OnRefreshing">
            <WebView x:Name="WebZm" HorizontalOptions="Fill" VerticalOptions="StartAndExpand"/>
        </RefreshView>`

**Comment by Redth** [comment]
Fixed in newer previews.
