### ISSUE TITLE
[Bug] Date and Time pickers keyboard typing should not work

### ISSUE THREAD

**Issue by Xami3Shah** [dotnet/maui#3131]
Create xaml page using either preview 9 OR 10
```
        <Grid RowSpacing="10"
              RowDefinitions="Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,*"
              Padding="{OnPlatform iOS='30,60,30,30', Default='15'}">
            <local:RoundDatePicker Grid.Row="0"
                                   FontSize="16"
                                   FontAutoScalingEnabled="True" />
            <local:RoundTimePicker Grid.Row="1"
                                   FontSize="16"
                                   FontAutoScalingEnabled="True" />
        </Grid>
```
What to do ?

1. run the app on either android or ios. 
2. select any of the picker
3. type something random on keyboard hardware keyboard i mean which is attacked to your pc/laptop
4. Picker accepts the text 

 
while it must not accept the text because it defeats the purpose of the date or time popup. If you want to accept the keyboard then use can only type valid text in a specified format without popping up the date or time dialogs, in that case use can have soft keyboard may be.

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue, could you attach a small sample where reproduce it?. Thanks in advance.
