### ISSUE TITLE
[Bug] Editor height request not working on ios

### ISSUE THREAD

**Issue by Xami3Shah** [dotnet/maui#3138]
Create new project using preview 9 or 10, add editor to your page
`            <Editor  HeightRequest="120" />`

run the app. 
1. on android it is working fine.
2. on iOS editor height is not increased.

**Comment by kristinx0211** [comment]
Verified Repro with iPhone 13 pro max IOs 15.2. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EU83J3MnYrhFvO5yPi6IS-cBtMMlrIGX4NC-4-EGGnK_Mg?e=JQakIz

**Comment by shimingsg** [comment]
repro could be found here:
[3138.zip](https://github.com/dotnet/maui/files/8129941/3138.zip)

**Comment by davidortinau** [comment]
This is working for me. Closing as fixed.
