### ISSUE TITLE
[Bug] empty space appears on ios 

### ISSUE THREAD

**Issue by Xami3Shah** [dotnet/maui#3139]
Create app with preview 10, set Grid background color to Orange.

Run the app. 

1. on android is it rendering fine
2. on ios there is empty spaces to the top and bottom of the page.

the page should take the whole page

**Comment by shimingsg** [comment]
@Xami3Shah Not reproducible with iPhone 13 pro max IOs 15.2.

**Comment by hartez** [comment]
@shimingsg Can you clarify that - you say it's _not_ reproducible, but you added the "verified" label. Is it just not reproducible on that model/OS version?
