### ISSUE TITLE
[Enhancement] Allow to invalidate GraphicsView

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#3140]
## Summary

GraphicsView allow to create a Canvas a draw anything using .NET MAUI Graphics. However, to create some stuff is necessary to be able to invalidate the Canvas.

Add an Invalidate to be able to do:

`Canvas.Invalidate();`

**Comment by jsuarezruiz** [comment]
Already implemented!

**Comment by nichojo89** [comment]
Is there no longer a canvas.Invalidate()? 

There is only GraphicsView.Invalidate, however, GraphicsView.Invalidate does not trigger Draw() to fire in in Microsoft.Maui.Graphics.Skia 6.0.200-preview.12.852?
