### ISSUE TITLE
[Bug] Not able to add axml files

### ISSUE THREAD

**Issue by SnapADrag0n** [dotnet/maui#3159]
### Description
I am trying to make use of axml files for a custom Android design, but the axml files doesn't seem to be supported anymore and VS 2022 Pre doesn't provide any option to create a new one as well.

### Steps to Reproduce

1. Create a new MAUI app
2. Add axml file inside Android platforms folder
3. Refer axml file from code

### Expected Behavior
axml file should be recognized

### Actual Behavior
axml file is not recognized:
![Axml issue](https://user-images.githubusercontent.com/68341156/139252933-c424de14-31cc-48ed-a820-c24777b41614.png)

### Basic Information

- Version with issue: .Net SDK V6.0.100-rc.2.21505.57
- Last known good version: Xamarin V16.10.000.234
- IDE: Visual Studio Community 2022 Preview (64-bit) Version 17.0.0 Preview 7.0
- Platform Target Frameworks: 
  - Android: 11

**Comment by YuqinSong** [comment]
Verified Repro. Repro project is available:
[#3159.zip](https://github.com/dotnet/maui/files/8150908/3159.zip)

**Comment by Redth** [comment]
These need to go into the Platforms\Android\Resources\layouts directory instead.
