### ISSUE TITLE
[Bug] Error loading images on Windows

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#3160]
### Description

There are errors loading images in Windows. Images are used inside every ItemTemplate in a CollectionView. The biggest problem I see is that every time the window is resized... the images are loaded again! This also has a negative impact on performance.
```
System.InvalidOperationException: Unable to load image stream.
       at Microsoft.Maui.UriImageSourceService.GetImageSourceAsync(IUriImageSource
    imageSource, Single scale, CancellationToken cancellationToken)
    Microsoft.Maui.UriImageSourceService: Warning: Unable to load image URI
```

To reproduce use the internal Podcast sample on Windows and resize the application Window.

### Expected Behavior

Resize the Window could adapt the item sizes but is not necessary to get again the same remote image.

### Actual Behavior

Get again the same images, and failing a big part of the times.

**Comment by v-xiaofchen** [comment]
Verified repro with Windows .Can not load images on Windows. As below, only one of three pictures can be displayed
![Picture7](https://user-images.githubusercontent.com/99376012/155475575-da509ff3-b815-466c-88cf-5f2ec849048b.png)
attached the repro sample
[MauiApp14.zip](https://github.com/dotnet/maui/files/8130373/MauiApp14.zip)

**Comment by VSadov** [comment]
This is a dupe of https://github.com/dotnet/maui/issues/2601
