### ISSUE TITLE
VS Pro 2022 Preview 5 & MAUI project not loading properly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3168]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-Pro-2022-Preview-5--MAUI-project-not/1555861)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.0 Prev 4.1]
There is a major issue with MAUI after upgrade from previos preview version to 5

1) Start VS
2) Create or open sample MAUI project
3) Build
4) My output in attachments

Something is definitly missing ...

---
#### Feedback Bot on 10/17/2021, 07:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Seems this is fixed then, thanks for letting us know @eltra-ch !
