### ISSUE TITLE
Which version of Microsoft.WindowsAppSDK for Maui Single project?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3169]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Which-version-of-MicrosoftWindowsAppSDK/1555558)._

---
I created a Maui Preview 8 single project application with VS2022 Preview 4.0 and it uses the Microsoft.WindowsAppSDK 1.0.0-experimental1 package. It builds, deploys and runs with no issues on Windows. But now since I have upgraded to VS2022 Preview 5.0 and it seems to have installed Maui Preview 9 the nuget manager shows the Microsoft.WindowsAppSDK can be upgraded to version Microsoft.WindowsAppSDK 1.0.0-preview2 but when I upgrade to that nuget package it builds but will not deploy to Windows. 

Should Microsoft.WindowsAppSDK  package be updated? 
Is anyone else seeing this issue with the Microsoft.WindowsAppSDK  package? 
Do I need to update or change some setting somewhere when updating the Microsoft.WindowsAppSDK package?

Steve

---
#### Feedback Bot on 10/17/2021, 06:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Questions answered for now, case closed!
