### ISSUE TITLE
Unable to install and run mauiapp1 deterministically

### ISSUE THREAD

**Issue by rom320** [dotnet/maui#3174]
### Description
After ~8hrs working to install Visual Studio 2022 version 17.0 RC2 and Preview 6, .net 6 (6.0.100-rc.2.21505.57) and .NET MAUI Preview 9, I was able to get the mauiapp1 to run (hello world-click counter).  I close the solution, reopen it and receive build errors android, ios and other targets not found.  Reboot, reopen  solution  and it builds, but no no longer can see/run in the android AVD.  20 yrs ago, I chose MS development because of the integrated tools.  This feels like java open source anarchy.  The VS, .Net, MAUI, android/ios/etc sdk stack needs to design component dependency and compatibility verification.... Like .net framework.

### Steps to Reproduce
I tried to take notes on how I was able to get a successful run.

Started by following these simple directions - 
https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation.    Couldn't build the app.
This provided some help.   I also received most of his errors.
https://www.claudiobernasconi.ch/2021/09/19/how-to-set-up-dotnet-maui-on-windows/  maui check failed with .net 6 sdk
So i applied this tip.
https://stackoverflow.com/questions/63746838/net-sdks-not-installing-correctly
then reran maui-check 
at this point i got a clean build, but couldn't debug in the android avd.
So i installed AndroidStudio and created an AVD there.
Reopened solution and couldnt build - android, ios  targets couldn't be found
Close solution
Reopened solution. Clean build, but now can't debug in android AVD.  just see "windows machine" as an option

### Expected Behavior
https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation
https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=windows

### Actual Behavior
see above Steps to Reproduce
 
### Basic Information

- Version with issue: .NET MAUI Preview 9
- Last known good version: none
- IDE:  Visual Studio 2022 version 17.0 RC2
- Platform Target Frameworks: 
  - iOS:  
  - Android:  api 29
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
