### ISSUE TITLE
[Bug] Focus is lost when you press Ctrl+F + Esc

### ISSUE THREAD

**Issue by jairbubbles** [dotnet/maui#3182]
### Description

Focus is not restored to WebView when pressing Esc in find window.

### Steps to Reproduce

1. Run the WPF sample from https://github.com/MicrosoftEdge/WebView2Samples
2. Click on the page to get focus
3. Press Ctrl + F to do a search
4. Press Esc
5. Press Ctrl + F to do a new search

### Expected Behavior

The find window appears.

### Actual Behavior

The find window does not appear.

### Basic Information

- Version with issue: WebView2 Runtime 95.0.1020.30
- IDE: Visual Studio 2022
- Nuget Packages: The sample uses 1.0.1056-prerelease but I have the issue with latest version too (1.0.1020.30 )

**Comment by Eilon** [comment]
@jairbubbles is this a problem specific to WebView2 in any app? If so, the place to file those bugs is in https://github.com/MicrosoftEdge/WebView2Feedback/issues.

This repo is specifically for .NET MAUI and for the BlazorWebView control (both of which _use_ WebView2).

**Comment by jairbubbles** [comment]
My bad, I was looking for similar bugs and I lost myself 😓

**Comment by Eilon** [comment]
@jairbubbles no worries, I have a hard time finding the right repo all the time too! I'm closing this bug here, but please do open a bug in the other repo to make sure it's tracked!
