### ISSUE TITLE
[Bug] AppThemeBinding survives longer then it should if Binding type is OneTime

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#3188]
### Description

```C#
this.SetOnAppTheme<Brush>(Shell.FlyoutBackgroundProperty, Brush.White, Brush.Black);
this.FlyoutBackground = SolidColorBrush.Purple
```

FlyoutBackground  should be purple now but it remains White or Black depending on the theme.

The only way to change FlyoutBackground is to call RemoveBinding on FlyoutBackgroundProperty

### Reproduction

If you use the following Unit Tests you can reproduce the behavior

```C#
		[Test]
		public void ThemeBindingRemovedWhenPropertySet()
		{
			var shell = new Shell();
			shell.FlyoutBackgroundColor = Colors.Pink;
			SetAppTheme(OSAppTheme.Dark);
			Assert.AreEqual(Colors.Pink, shell.FlyoutBackgroundColor);
		}
```

If you delete the OneTime binding on FlyoutBackgroundColor then the unit test passes

**Comment by mattleibow** [comment]
Should setting the value explicitly override the binding? Not sure the rules between bindings and explicit values.

**Comment by StephaneDelcroix** [comment]
> Should setting the value explicitly override the binding? Not sure the rules between bindings and explicit values.

yes, it should. and a theme binding shouldn't override a manually set value

**Comment by StephaneDelcroix** [comment]
is it still the case. I fixed something related to that lately...

**Comment by StephaneDelcroix** [comment]
this test passes

```csharp
		[Test]
		//https://github.com/dotnet/maui/issues/3188
		public void ThemeBindingRemovedOnOneTimeBindablePropertyWhenPropertySet()
		{
			var shell = new Shell();
			shell.SetAppThemeColor(Shell.FlyoutBackgroundProperty, Colors.White, Colors.Black);
			shell.FlyoutBackgroundColor = Colors.Pink;
			SetAppTheme(AppTheme.Dark);
			Assert.AreEqual(Colors.Pink, shell.FlyoutBackgroundColor);
		}
```
