### ISSUE TITLE
[Bug] AppActions and other gestures trigger multiple windows or instances to display

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#3199]
### Description

When I click an App Action on Windows or click the notification that is generated from WeatherTwentyOne, another instance (or window?) is launched.

https://github.com/davidortinau/WeatherTwentyOne

<img width="381" alt="image" src="https://user-images.githubusercontent.com/41873/139543616-d5eb1f92-d10c-424f-914a-db01604ae6e6.png">

### Expected Behavior

Not a new window. 

### Basic Information

- Version with issue: 6.0.101-preview.10.2068

**Comment by MagnusMikkelsen** [comment]
I reproduced this in the template that comes with VS 2022.
Just added `AppActions.SetAsync(new AppAction("foo", "Do Foo", "Want some foo?"));` to `MainPage.xaml.cs`

In WeatherTwentyOne new instances are also started when you click the TrayIcon two-three times.

**Comment by YuqinSong** [comment]
Not reproducible on 17.2.0 Preview 2.0 [32214.334.main]. There is no new window launched.
