### ISSUE TITLE
[Bug] File -> New MAUI App does not compile

### ISSUE THREAD

**Issue by coosmiin** [dotnet/maui#3204]
**Steps to Reproduce**
1. Create a new .NET MAUI App project in Visual Studio 2022 (17.0.0 Preview 7.0).
2. Try to build.

**Expected behavior**
Since it's the default app template, the app should compile.

**Actual behavior**
The app opens the "Setup Hot Restart" to setup deploying to a local iOS device. But hey, I don't have an iOS device (and I want to just start with only Android at first). So I close the popup and then the solution does not compile. Not 100% sure that the two are related, but considering that trying to rebuild I get the same popup, I guess they are.

**Expected behavior**
I should be able to compile without setting up iOS device. Maybe a dialog asking for what platforms do you want to build for?

**Additional details**
- Even if I delete all the other Platforms (except Android) folders from the solution and `SupportedOSPlatformVersion` property group from csproj it still does not compile.
- Compile Errors:
![image](https://user-images.githubusercontent.com/3222985/139578354-d7bd6bc4-f764-452e-96cc-34e0fae022f6.png)

**Comment by MagicAndre1981** [comment]
MAUI und VS2022 are still unusable , I also can't get my Pixel phone or Android subsystem recognized by VS2022 P7. The tooling is broken, in past previews it was working

**Comment by Xami3Shah** [comment]
For new solution it does not work. vs only shows windows option for running the app, i have to close vs2020 after creating new project. Reopening solution works for me. 
after reopening solution second time Dependencies restores properly and the solution also pick the android phone properly.

**Comment by Xami3Shah** [comment]
i am using the "Version 17.0.0 Preview 7.0". i had to remove my vs2019 installation. jsdk version "jdk-8.0.302.8-hotspot". i can run apps with android and iOS with mac on network. the hot-restart never worked for me even in vs2019.

**Comment by MagicAndre1981** [comment]
I run 2022 in a separate Win11 VM, when I load a Xamarin.Forms app I see my phone and the Android subsystem, so this is a MAUI tooling issue of VS2022

**Comment by jallmen** [comment]
https://subscribe.packtpub.com/getting-started-with-microsoft-net-maui/
If you scroll far enough you should see how to edit the page so it doesn't give you this error.
Sometimes unloading and reloading the project works.

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.

**Comment by MagicAndre1981** [comment]
yes, VS 17.1 Preview 6.0 fixed my compile issue and I see my connected Pixel phone and can deploy it.

**Comment by sergiomf** [comment]
Version 17.2.0 Preview 1.0  issue not yet fixed:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst	MauiApp1	C:\Users\sergi\source\repos\MauiApp1\MauiApp1.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst	MauiApp1	C:\Users\sergi\source\repos\MauiApp1\MauiApp1.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst	MauiApp1	C:\Users\sergi\source\repos\MauiApp1\MauiApp1.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst	MauiApp1	C:\Users\sergi\source\repos\MauiApp1\MauiApp1.csproj	1	




<img width="877" alt="01" src="https://user-images.githubusercontent.com/5129439/158015461-58c5bbea-c65f-4b11-8877-ad5dd61789be.png">
