### ISSUE TITLE
[Enhancement] Image FailedImage / LoadingImage

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3206]
Hi,

Please add the following properties to the Image so we don't need to use image controls from a third-party.

1. LoadingImage : Showing a Loading animated or not animated Images when Image is loading.
2. FailedImage : if Image failed to load from Http or local then the FailedImage will be shown.

Thanks
Jassim

**Comment by jfversluis** [comment]
Same as #3207 I would appreciate it if you could put a little more effort into requesting these features.
