### ISSUE TITLE
Unable to debug android emulator

### ISSUE THREAD

**Issue by mahebisht** [dotnet/maui#3208]
Unable to debug the Maui application using android emulator. It says Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code)

### Steps to Reproduce

1.  Run maui application in Android emulator.

Microsoft Visual Studio Community 2022 Preview (64-bit), Version 17.0.0 Preview 7.0
.Net Maui 0.9 version

![BreakMode](https://user-images.githubusercontent.com/80498223/139615467-4d99e62e-bf6e-4f76-9dd3-9e54284ccd68.PNG)

**Comment by Amir-Care** [comment]
Not repro on VS 17.2.0 Preview 2.0 [32208.484.main]
