### ISSUE TITLE
[Bug] When showing DisplayActionSheet first time, custom control (ViewRenderer) that is placed in same page is recreated

### ISSUE THREAD

**Issue by jakovMR** [dotnet/maui#3210]
### Description
I have custom control (ViewRenderer) added from layout in one page. When I show DisplayActionSheet on the same page (on button click or after page is created and appearing is finished) for the first time, custom control is recreated even without disposing previous one.

### Steps to Reproduce

1.  Create custom control (simple View in portable project and ViewRenderer in Android platform)
2.  Add compatibility renderer on MAUI handlers
3.  Add this custom control in some page
4.  After page is initialized and completely appeared show DisplayActionSheet

### Expected Behavior
Custom control shouldn't be recreated
### Actual Behavior
Custom control is completely recreated. **OnElementChanged** is trigged where **OldElement and NativeControl are null**.
### Basic Information
I work only with Android platform so far, don't know if the same issue persist on iOS platform as well.
- Version with issue:
- 6.0.101-preview.9.1843
- Last known good version:
- Unknown
- IDE:
- VS 2022 Version 17.0.0 Preview 7.0
- Platform Target Frameworks:
  - Android: 31
- Nuget Packages:
- Microsoft.Maui.Controls.Build.Tasks, Microsoft.Maui.Dependencies, Microsoft.Maui.Extensions, Microsoft.Maui.Resizetizer.Sdk
- Affected Devices:
- Samsung Galaxy A52, Samsung Galaxy Note 8

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?. Thanks.

**Comment by jakovMR** [comment]
Hi @jsuarezruiz,
Here is small sample application where very basic empty view is used. Let me know if you need anything else from my side.

[CustomRendererBug.zip](https://github.com/dotnet/maui/files/7496499/CustomRendererBug.zip)

**Comment by v-xiaofchen** [comment]
Not reproducible with 17.2.0 Preview 2.0 [32209.335.main] using Android. I ran the project above，it seems fine.Here are the results
![Picture6](https://user-images.githubusercontent.com/99376012/155468443-1ca9cceb-4d28-4484-8838-34aedd47532a.png)
