### ISSUE TITLE
[Bug] On iOS: The type initializer for 'SQLite.SQLiteConnection' threw an exception (Android works)

### ISSUE THREAD

**Issue by jallmen** [dotnet/maui#3211]
### Description

```
  public class Database
  {
      public Database()
      {
          var dbPath = Path.Combine(FileSystem.AppDataDirectory, "databaseTest.db3");

          Connection = new SQLiteAsyncConnection(dbPath);
          Connection.CreateTableAsync<User>().Wait();
      }

      public SQLiteAsyncConnection Connection { get; set; }
  }
```
This seems to work fine with Android applications allowing me to manipulate the database from anywhere.

However, when I run this application through an IOS simulator with an active Mac connection I get the following error: 

> "The type initializer for 'SQLite.SQLiteConnection' threw an exception."

I believe that an active connection to an SQLite database cannot be resolved but I don't know why.

### Steps to Reproduce

1. Create a database class that uses SQLite-net-plc to establish a connection with a database in the constructor
2. Pass this class through the MAUI dependency injection

### Expected Behavior
Database connection connects and you can use the database

### Actual Behavior
> "The type initializer for 'SQLite.SQLiteConnection' threw an exception."

### Basic Information

- Version with issue: 6.0.101-preview.9.1843
- Last known good version: n/a
- IDE: VS 2022
- Platform Target Frameworks: 
  - iOS:  15.0
  - Android: n/a
  - UWP:  n/a
- Android Support Library Version: n/a
- Nuget Packages: sqlite-net-plc, SQLitePCLRaw.provider.dynamic_cdecl
- Affected Devices: Iphone 11 Pro Max IOS 15.0

### Screenshots

n/a

### Reproduction Link

not available

**Comment by VladislavAntonyuk** [comment]
I don't think the issue is with the MAUI. by the way I created a test project where SQLite works with Maui https://github.com/VladislavAntonyuk/KanbanBoard

**Comment by jsuarezruiz** [comment]
Could you attach a sample where we can reproduce the issue?

**Comment by jallmen** [comment]
> I don't think the issue is with the MAUI. by the way I created a test project where SQLite works with Maui https://github.com/VladislavAntonyuk/KanbanBoard

Does this work on IOS?

**Comment by VladislavAntonyuk** [comment]
yes,
![image](https://user-images.githubusercontent.com/33021114/140583615-4174e94b-f6b7-4b9c-8b06-bba11689dff7.png)

**Comment by jallmen** [comment]
> yes, iOS ![image](https://user-images.githubusercontent.com/33021114/140583615-4174e94b-f6b7-4b9c-8b06-bba11689dff7.png)
> 
> and macOS ![image](https://user-images.githubusercontent.com/33021114/140584296-b0bd3b0f-d059-41aa-aa20-cdd3ac6e439f.png)
> 
> make sure you set the provider (`SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_sqlite3());`) before MauiApp initialization

Do you mean before this line: 
![image](https://user-images.githubusercontent.com/75501095/140903454-7a118129-d390-4085-b6c9-f4d76c89a0f3.png)

**Comment by VladislavAntonyuk** [comment]
no, in AppDelegate: https://github.com/VladislavAntonyuk/KanbanBoard/blob/maui/KanbanBoard/Platforms/iOS/AppDelegate.cs

**Comment by jallmen** [comment]
Yes that fixed the issue, Thanks.

**Comment by mattleibow** [comment]
Awesome!

**Comment by wuyuansushen** [comment]
Thanks a lot.

**Comment by VladislavAntonyuk** [comment]
https://vladislavantonyuk.azurewebsites.net/articles/Adding-SQLite-to-the-.NET-MAUI-application

**Comment by RaspeR87** [comment]
@VladislavAntonyuk your sample on Github didn't work anymore on latest Visual Studio 17.1.0 Preview 5 & MAUI Preview 12.
It doesn't recognise SQLite3Provider_sqlite3 in the AppDelegate class. I can get it to build if I change it to SQLite3Provider_e_sqlite3, but then the app crashes on start-up with the following:

[0:] An error occurred: 'e_sqlite3'. Callstack: ' at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)

As you mentioned on your blog, it can be builded just with CLI command `dotnet build -f net6.0-ios` and not with UI.
But then app cannot be pushed to iOS simulator with command `dotnet build -t:Run -f net6.0-ios -p:_DeviceName=:v2:udid=<UDID>`

It can be builded with UI too only if you add one additional Nuget package: **SQLitePCLRaw.provider.sqlite3**
But when you want to run that app on iOS simulator you get this error:
![2022-02-02_20-06-06](https://user-images.githubusercontent.com/14901702/152220909-35b8948f-be4e-42ca-8d5c-d6e0f5119b52.png)

@hartez I think this bug is not Done. Is there any way how we can currently use SQL database in our MAUI app (in iOS and Android app)?

**Comment by VladislavAntonyuk** [comment]
> @VladislavAntonyuk your sample on Github didn't work anymore on latest Visual Studio 17.1.0 Preview 5 & MAUI Preview 12.
> 
> It doesn't recognise SQLite3Provider_sqlite3 in the AppDelegate class. I can get it to build if I change it to SQLite3Provider_e_sqlite3, but then the app crashes on start-up with the following:
> 
> 
> 
> [0:] An error occurred: 'e_sqlite3'. Callstack: ' at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
> 
> at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
> 
> 
> 
> As you mentioned on your blog, it can be builded just with CLI command `dotnet build -f net6.0-ios` and not with UI.
> 
> But then app cannot be pushed to iOS simulator with command `dotnet build -t:Run -f net6.0-ios -p:_DeviceName=:v2:udid=<UDID>`
> 
> 
> 
> It can be builded with UI too only if you add one additional Nuget package: **SQLitePCLRaw.provider.sqlite3**
> 
> But when you want to run that app on iOS simulator you get this error:
> 
> ![2022-02-02_20-06-06](https://user-images.githubusercontent.com/14901702/152220909-35b8948f-be4e-42ca-8d5c-d6e0f5119b52.png)
> 
> 
> 
> @hartez I think this bug is not Done. Is there any way how we can currently use SQL database in our MAUI app (in iOS and Android app)?
> 
> 

I haven't installed preview 12 on my macOS (it requires .net 6.0.2 which hasn't released yet). I will take a look and update the app.
The app should work on Android

**Comment by RaspeR87** [comment]
@VladislavAntonyuk no, I am talking about VS and MAUI on Windows and remote debugging on remote iOS simulator via Mac

**Comment by VladislavAntonyuk** [comment]
> @VladislavAntonyuk no, I am talking about VS and MAUI on Windows and remote debugging on remote iOS simulator via Mac

By the way what is your iOS version?

**Comment by RaspeR87** [comment]
> > @VladislavAntonyuk no, I am talking about VS and MAUI on Windows and remote debugging on remote iOS simulator via Mac
> 
> By the way what is your iOS version?

iOS 15.2

**Comment by VladislavAntonyuk** [comment]
@RaspeR87 could you try to install this package `<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.0.7" />`
