### ISSUE TITLE
BlazorDesktop - Failed to create component 'BlazorWebView'  in WinForms Designer

### ISSUE THREAD

**Issue by AaronAnz** [dotnet/maui#3212]
I'm trying to build a Blazor Desktop application with WinForms and receiving an error when trying to add the BlazorWebView to WinForm. 

Project: WinForms .net6.0 ( tried setting project to Microsoft.NET.Sdk.Razor and Microsoft.NET.Sdk.WindowsDesktop in csproj )
Visual Studio Version: 2022 Preview 7.0
Windows Version: 11 no pending updates
Nuget package: Microsoft.AspNetCore.Components.Web.WindowsForms (6.0.101-preview.9.1843 and 6.0.100-rc.1.1608)
Microsoft Edge WebView2 Runtime: 95.0.1020.30

The error received when trying to add it to windows form:
![image](https://user-images.githubusercontent.com/27394920/139575134-f2b538a5-ddbc-4d17-a014-53a0b49b0e67.png)

I can download projects that have it in side and it works fine but I cant add it to my own new project.

Not really sure what to do to get designer to work. Guess I'll have to do it all from code behind.

**Comment by Eilon** [comment]
Hi @AaronAnz , does this happen when you try to drag & drop a BlazorWebView onto the form in the designer? Or do you already have the BlazorWebView and you're opening up the form in the designer?

**Comment by Eilon** [comment]
I think I've reproed an issue with BlazorWebView in the WinForms designed but I'm not sure if it's the same issue. I'm working on a fix for that, which might also fix the issue reported here.

**Comment by AaronAnz** [comment]
Sorry, just seen this. Happens when I drag it into the form in the
designer.

**Comment by Eilon** [comment]
@AaronAnz I think I have a fix ready for this. Hopefully it fixes the issue you're seeing!
