### ISSUE TITLE
[Bug] ContentPage.OnAppearing is not getting called

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/maui#3216]
### Description

In an attempt to control page logic programmatically need to handle `OnAppearing` override. Unfortunately, it's not getting called.

### Steps to Reproduce

1. Create a new content page derived class.
2. Override the `OnAppearing` method

### Expected Behavior

The method is getting called on the page appearing

### Actual Behavior

The method is not getting called

### Basic Information

- Version with issue: 6.0.100-rc.2.21505.57
- Last known good version: NA
- IDE: VS2022 - Preview 5
- Platform Target Frameworks: iOS, Android, Windows

### Reproduction Link

```
protected override void OnAppearing()
{
    // ... never getting called
}
```

### Workaround

Use OnNavigatedTo instead:

```
protected override void OnNavigatedTo(NavigatedToEventArgs args)
{
    // ... custom code here
    base.OnNavigatedTo(args);
}
```

**Comment by PureWeen** [comment]
@alexeystrakh This should be fixed by
https://github.com/dotnet/maui/pull/2781

If you're still seeing this on the latest p10 bits then please re-open

**Comment by PureWeen** [comment]
Tested on P11 and looks to be fixed

**Comment by marwalsch** [comment]
@PureWeen I have the same issue targeting windows (Android and iOS work fine). Is the fix expected to work on all platforms?

**Comment by PureWeen** [comment]
> @PureWeen I have the same issue targeting windows (Android and iOS work fine). Is the fix expected to work on all platforms?

yes
