### ISSUE TITLE
[Bug] ToolbarItem handler is not getting called

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/maui#3217]
### Description

ToolbarItem handler is not getting called

### Steps to Reproduce

1. Create a new content page derived class.
2. Create a new ToolbarItem, supply click handler, and add to the buttons collection

### Expected Behavior

The toolbar item handler is getting called on item click

### Actual Behavior

The toolbar item handler is not getting called

### Basic Information

- Version with issue: 6.0.100-rc.2.21505.57
- Last known good version: NA
- IDE: VS2022 - Preview 5
- Platform Target Frameworks: iOS, Android, Windows

### Screenshots

![image](https://user-images.githubusercontent.com/3697084/139744296-e400d649-21a6-450a-a65f-548872e15b2f.png)

### Reproduction Link

```
// contstructor
ToolbarItem mauiButton = new ToolbarItem
{
    Text = "Add",
    Order = ToolbarItemOrder.Primary,
    Priority = 0
};
mauiButton.Clicked += MauiButtonClicked;
this.ToolbarItems.Add(mauiButton);
```

### Workaround

None is found

**Comment by PureWeen** [comment]
@alexeystrakh This should be fixed by
https://github.com/dotnet/maui/pull/2781

If you're still seeing this on the latest p10 bits then please re-open
