### ISSUE TITLE
No intellisense to specify Grid.Row\Column properties[Bug] 

### ISSUE THREAD

**Issue by KirillPom** [dotnet/maui#3224]
VS 2022 preview 7.
Just created MAUI app from template.
![image](https://user-images.githubusercontent.com/65759581/139878262-14841912-3e4f-4848-ad20-4eca22d4b9e8.png)

**Comment by jamesmontemagno** [comment]
Workaround is to use GridLayout.Row or just Grid.Row

**Comment by mattscheffer** [comment]
Appears to be fixed. No repro as of VS 17.2.0 Preview 1. Grid shows up as an option and both Column/Row show up intellisense after "Grid." is typed

![image](https://user-images.githubusercontent.com/10537189/154778567-93189363-a1ca-47a3-991d-88d9745f9c3c.png)
![image](https://user-images.githubusercontent.com/10537189/154778574-b6ef1f39-a609-4eab-97cf-9ce0af169621.png)
