### ISSUE TITLE
[Enhancement] Add support to generate event handler code from XAML Editor

### ISSUE THREAD

**Issue by KirillPom** [dotnet/maui#3225]
VS 2022 preview 7.
Just created MAUI project from template.
Add Button control.
Try to set Clicked property.

Opposite to WPF there is no menu item <New Event Handler> to autogenerate handler method

**Comment by jsuarezruiz** [comment]
Thanks for the feedback. Duplicated https://github.com/dotnet/maui/issues/3225 I am going to concentrate the comments and effort in 3225.
