### ISSUE TITLE
[Bug] OnChildAdded is not getting called when a child is added to a layout control

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/maui#3229]
### Description

In a custom layout control (Grid, AbsolutLayout), the `OnChildAdded` overridden method is not getting called when a child is added to the layout.

### Steps to Reproduce

1. Create a new `CustomGrid` class derived from `Grid`.
2. Override the `OnChildAdded` method
3. Place the custom grid on a page and add a child control on user action, such as button click or anything else

### Expected Behavior

The control is added to the custom grid and the `OnChildAdded` is called.

### Actual Behavior

The control is added to the custom grid and the `OnChildAdded` is not getting called.

### Basic Information

- MAUI Version: 6.0.101-preview.9.1843
- DOTNET Version: 6.0.100-rc.2.21505.57
- Last known good version: NA
- IDE: VS2022 - Preview 5
- Platform Target Frameworks: iOS, Android, Windows

### Reproduction Link

```
public class CustomGrid : Grid
{
    protected override void OnChildAdded(Element child)
    {
        // never called
        System.Diagnostics.Debug.WriteLine($"CustomGrid.OnChildAdded {child}");
        base.OnChildAdded(child);
    }
}

<local:CustomGrid x:Name="Root" BackgroundColor="GreenYellow">
    <Button Text="Add New Child" 
            Clicked="Button_Clicked" 
            VerticalOptions="Center" 
            HorizontalOptions="Center"/>
</local:CustomGrid>

private void Button_Clicked(object sender, EventArgs e)
{
    var newChild = new BoxView { WidthRequest = 50, HeightRequest = 50, BackgroundColor= Colors.Red };
    Root.Add(newChild);
}
```

### Workaround

None is found

**Comment by hartez** [comment]
See also #3309 for some additional info (and note that ChildRemoved also needs to be covered).
