### ISSUE TITLE
Workload Repair failed: `dotnet workload repair - MAUI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3235]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Workload-Repair-failed:-dotnet-workload/1500424)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:.net 6 preview 7]
Faced  Workload Repair failed: `dotnet workload repair while checking maui. Workload check fails with below with .net 6 preview 7

.NET SDK - Workloads (6.0.100-preview.7.21379.14) Checkup...
  x android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 30.0.100-preview.7.110) not installed.
  x ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-preview.7.230) not installed.
  x maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-preview.7.230) not installed.
  x tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-preview.7.230) not installed.
  x macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-preview.7.230) not installed.
  x maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-preview.7.1345) not installed.
  - wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-preview.7.21377.19) installed.
  - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-preview.7.21377.2)
installed.

Error log:
Fix failed - Workload Repair failed: `dotnet workload repair --source "https://api.nuget.org/v3/index.json" --source
"https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.7.21379.14-shipping-1/nuget/v3/index.json" --source
"https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" --source
"https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json"`
──────

---
#### Saravanan Madheswaran on 8/11/2021, 10:30 AM: 

<p>Fix failed - Workload Install failed: <code>dotnet workload install --sdk-version 6.0.100-preview.7.21379.14 --no-cache --disable-parallel android-aot ios maccatalyst tvos macos maui wasm-tools --skip-manifest-update --source &quot;https://api.nuget.org/v3/index.json&quot; --source &quot;https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.7.21379.14-shipping-1/nuget/v3/index.json&quot; --source &quot;https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json&quot; --source &quot;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json&quot;</code></p>
<p>Anyone know the reason</p>

#### Feedback Bot on 8/12/2021, 00:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Issue is rather old so closing this for now. The workload CLI tooling should be better by now and/or not even needed when you install through VS. Please let us know if there is still a problem here. Thanks!
