### ISSUE TITLE
.NET MAUI Entry Text only use the value assigned not the typed value (VS2022 Preview 7)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3236]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Entry-Text-only-use-the-value-/1567675)._

---
Using Visual Studio 2022 preview 7 and .NET MAUI project.

You can assign a value to an Entry control (in design or by code) then that value is the only value you can get for that Entry.

I only test in Windows app, not Android or iOS (I can't run it on Android or iOS).

If I look at the value on Entry.Completed event the value is the assigned one not the number I type.
I only try with numbers, but it's possible the same occurs on alphabetic text.

I will try on a new blank project, but... 

Guillermo

---
#### Feedback Bot on 10/31/2021, 11:15 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Guillermo Som on 11/1/2021, 09:50 AM: 

<p>At last, I can do a project to show the error.</p>
<p>Is a .NET MAUI standard project using an Entry control, a Label and a Button.<br>
If you type a number (or whatever else), then click the button and the text you type is shown in a label.<br>
Or this is the intention, because only shows the text was initial assigned to the Entry control.</p>
<p>Here is the project.</p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=B06879203bbc84624a75e960b825059d1637713822236149510_Entry_bug_MauiApp2.zip&amp;tid=06879203bbc84624a75e960b825059d1637713822236149510">Entry_bug_MauiApp2.zip</a></p>
<p>Guillermo</p>

---
### Original Solutions
(no solutions)

**Comment by williamlee1982** [comment]
same situation from here. this is absolutely a bug.

**Comment by elGuille-info** [comment]
Also happens with **Editor** control and both Windows and Android (on iOS I can't test)
