### ISSUE TITLE
Missing Packages when ".NET MAUI App (Preview)" project is created

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3238]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Missing-Packages-when-NET-MAUI-App-Pr/1564138)._

---
[severity:It bothers me. A fix would be nice]
! [image.png] (https://aka.ms/dc/image?name=B70fd9a802aa84e09a37e5a8b2330d7f0637708619048956497_20211026-121824-image.png&tid=70fd9a802aa84e09a37e5a8b2330d7f0637708619048956497)

---
#### Feedback Bot on 10/26/2021, 07:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 10/27/2021, 02:02 AM: 

<p>Hi Ken, thank you for your feedback and I am sorry to hear that you are running into this issue.<br>
According to your description, I tried to follow it and not sure the Debug TargetFramework toolbar menu that you mentioned, would you please share the screenshot about this? Usually, we can right click the project name and choose Properties-Application-General-Target frameworks to specific the target frameworks.</p>

#### Ken Annable on 10/28/2021, 07:39 AM: 

<p>Here’s the screen shot:<br>
<img src="https://aka.ms/dc/image?name=B5f4f0343782f44bfa398d10f8f61a527637710286470366501_20211028-103725-image.png&amp;tid=5f4f0343782f44bfa398d10f8f61a527637710286470366501" alt="image.png"></p>
<p>Then I select the “net6.0-android” option.  Note, that I tried this today after upgrading VS to Preview 7 and still get the same warnings when building.</p>

#### Sara Liu [MSFT] on 10/29/2021, 00:28 AM: 

<p>Hi Ken, thanks for your detailed information. We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Older issue, going to assume this is better by now. Let us know if there is still an issue here. Thanks!
