### ISSUE TITLE
versioncode 1.0 is invalid

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3239]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/versioncode-10-is-invalid/1553498)._

---
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error	XA0003	VersionCode 1.0 is invalid. It must be an integer value.
Nombre del parámetro: VersionCode	MauiApp1	C:\Users\DEVSRV\source\repos\MauiApp1\MauiApp1\MauiApp1\obj\Debug\net6.0-android\android\AndroidManifest.xml	1

---
#### Feedback Bot on 10/13/2021, 11:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Brad Walter on 10/16/2021, 00:24 AM: 

<p>Hello, I have the same issue and have not found a fix. It started after the VS2022 upgrade applied today.</p>
<p>VS version:<br>
Microsoft Visual Studio Community 2022 Preview (64-bit)<br>
Version 17.0.0 Preview 5.0</p>
<p>Any help would be appreciated.</p>

#### JASON Zhao [MSFT] on 10/21/2021, 03:06 AM: 

<p>@<a target='_blank' href="https://developercommunity.visualstudio.com/users/345625/JorgeArturoAviles.html">Jorge Arturo Aviles</a><br>
Thanks for your feedback!<br>
Does your VS upgrade install or clean install?</p>

#### chris on 10/21/2021, 06:03 AM: 

<p><a target='_blank' href="https://developercommunity2.visualstudio.com/user/2e43e195-b62c-6bda-97d8-059df7c7395e/profile">JASON Zhao [MSFT]</a><br>
My install was a clean install, but that is probably not a factor.  Root cause of the problem appears to be</p>
<pre><code><span class="hljs-comment">&lt;!-- Versions --&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">ApplicationVersion</span>&gt;</span>1.0<span class="hljs-tag">&lt;/<span class="hljs-name">ApplicationVersion</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">AndroidVersionCode</span>&gt;</span>1<span class="hljs-tag">&lt;/<span class="hljs-name">AndroidVersionCode</span>&gt;</span>
</code></pre>
<p>That was in the .csproj for .NET MAUI projects created in Preview 4.  Current Preview uses</p>
<pre><code><span class="hljs-comment">&lt;!-- Versions --&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">ApplicationVersion</span>&gt;</span>1.0<span class="hljs-tag">&lt;/<span class="hljs-name">ApplicationVersion</span>&gt;</span>
</code></pre>
<p>This is reproducible with Preview 6, change the “1” to a “1.0” for ApplicationVersion and you will get the “XA0003	VersionCode 1.0 is invalid” error message.</p>

#### JASON Zhao [MSFT] on 10/22/2021, 03:06 AM: 

<p>This feedback is being re-triaged as we are moving it to another team that can better help with the issue. Thanks for your patience.</p>

---
#### chris solved on 10/20/2021, 08:02 PM, 0 votes: 

<p>I received this error with a demo project created with Preview 4.  When I compile with Preview 6, I get the error</p>
<pre><code><span class="hljs-attr">Severity</span>	<span class="hljs-string">Code	Description	Project	File	Line	Suppression State</span>
<span class="hljs-attr">Error</span>	<span class="hljs-string">XA0003	VersionCode 1.0 is invalid. It must be an integer value.</span>
<span class="hljs-attr">Parameter</span> <span class="hljs-string">name: VersionCode	StopwatchMaui	....\StopwatchMaui\obj\Debug\net6.0-android\android\AndroidManifest.xml	1</span>
</code></pre>
<p>The AndroidManifest in the Platforms\Android folder looks like this:</p>
<pre><code><span class="hljs-meta">&lt;?xml version="1.0" encoding="utf-8"?&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">manifest</span> <span class="hljs-attr">xmlns:android</span>=<span class="hljs-string">"https://schemas.android.com/apk/res/android"</span>&gt;</span>
	<span class="hljs-tag">&lt;<span class="hljs-name">uses-sdk</span> <span class="hljs-attr">android:minSdkVersion</span>=<span class="hljs-string">"21"</span> <span class="hljs-attr">android:targetSdkVersion</span>=<span class="hljs-string">"31"</span> /&gt;</span>
	<span class="hljs-tag">&lt;<span class="hljs-name">application</span> <span class="hljs-attr">android:allowBackup</span>=<span class="hljs-string">"true"</span> <span class="hljs-attr">android:icon</span>=<span class="hljs-string">"@mipmap/appicon"</span> <span class="hljs-attr">android:roundIcon</span>=<span class="hljs-string">"@mipmap/appicon_round"</span> <span class="hljs-attr">android:supportsRtl</span>=<span class="hljs-string">"true"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">application</span>&gt;</span>
	<span class="hljs-tag">&lt;<span class="hljs-name">uses-permission</span> <span class="hljs-attr">android:name</span>=<span class="hljs-string">"android.permission.ACCESS_NETWORK_STATE"</span> /&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">manifest</span>&gt;</span>
</code></pre>
<p>The build time generated AndroidManifest in obj\Debug\net6.0-android includes the following line:<br>
<code>&lt;manifest xmlns:android=&quot;https://schemas.android.com/apk/res/android&quot; android:versionCode=&quot;1.0&quot; package=&quot;com.companyname.StopwatchMaui&quot; android:versionName=&quot;1.0.0&quot;&gt;</code></p>
<p>Creating a new project with Preview 6 does not generate the error and the same line in the generated manifest looks like this:</p>
<p><code>&lt;manifest xmlns:android=&quot;https://schemas.android.com/apk/res/android&quot; android:versionCode=&quot;1&quot; package=&quot;com.companyname.StopWatchMaui2&quot; android:versionName=&quot;1.0.0&quot;&gt;</code></p>
<p><strong>android:versionCode=“1”</strong> is valid, <strong>android:versionCode=“1.0”</strong> is not.</p>
<p>In the .csproj generated by Preview 4, the version information was two lines</p>
<pre><code><span class="hljs-comment">&lt;!-- Versions --&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">ApplicationVersion</span>&gt;</span>1.0<span class="hljs-tag">&lt;/<span class="hljs-name">ApplicationVersion</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">AndroidVersionCode</span>&gt;</span>1<span class="hljs-tag">&lt;/<span class="hljs-name">AndroidVersionCode</span>&gt;</span>
</code></pre>
<p>In the .csproj generated by Preview 6, the version information was one line</p>
<pre><code><span class="hljs-comment">&lt;!-- Versions --&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">ApplicationVersion</span>&gt;</span>1<span class="hljs-tag">&lt;/<span class="hljs-name">ApplicationVersion</span>&gt;</span>
</code></pre>
<p>When I changed the “Versions” lines .csproj to match the single line used in the new .csproj Preview 6, the app compiled and deployed to Android.</p>

**Comment by jfversluis** [comment]
This issue is fixed in the current templates
