### ISSUE TITLE
Xml version will be in Android manifest handled as Android version code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3241]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xml-version-will-be-in-Android-manifest-/1552142)._

---
in the newest version of Preview the xml version is be handled from the Coompiler as android version coode, this is a fatal bug within the compiler

---
#### Feedback Bot on 10/13/2021, 00:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/15/2021, 06:33 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by wenwen60** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
