### ISSUE TITLE
Project reference with target framework specified fails to resolve and build within VS IDE whereas same thing works fine in .NET CLI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3243]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Project-reference-with-target-framework-/1537023)._

---
Created a .NET MAUI project (Preview 8) with VS2022 Preview 4.

And created a new class library that multi-targets .NET Standard 2.0 and .NET 6.0.

Have referenced that class library to the .NET MAUI project and specified the target framework as net6.0.

Tried using `AdditionalAttributes` and even `SetTargetFramework` in the Project Reference node, but to no avail, build always fails within VS IDE, whereas the same gets compiled successfully in .NET CLI.

```xml
<ProjectReference Include="..\ClassLib\ClassLib.csproj" AdditionalAttributes="TargetFramework=net6.0" />
```
```xml
<ProjectReference Include="..\ClassLib\ClassLib.csproj">
	<SetTargetFramework>TargetFramework=net6.0</SetTargetFramework>
</ProjectReference>
```

Kindly fix the missing piece within VS IDE as it works on .NET CLI without any issues.

---
#### Feedback Bot on 9/22/2021, 11:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mattscheffer** [comment]
Bug repros in 17.2.0 Preview 1. Repro solution is here: https://microsoft.sharepoint.com/:u:/r/teams/Mauitriage/Shared%20Documents/General/ReproProjects/3243.zip?csf=1&web=1&e=iYhSOn

![image](https://user-images.githubusercontent.com/10537189/154170023-d7ae384d-3a0e-453f-b59b-c9fddf31cca8.png)
