### ISSUE TITLE
[Bug] Some input files use or override a deprecated API, Recompile with -Xlint:deprecation for details

### ISSUE THREAD

**Issue by realZhangChi** [dotnet/maui#3245]
### Description
Hi, 
I created an Android binding library using the android-bindinglib project template, and referenced this binding class library by project reference in another Maui project. This is the Maui project can run normally on Android devices. I want to package this binding class library into nuget, and the Maui project uses the Nuget package to reference the binding class library, but an error will be reported when the Maui project is compiled.
Sorry I don't speak much English, and the approximate meaning of the error message translated into English is as follows:
```
Error: The package com.tencent.mm.opensdk.diffdev does not exist
Some input files use or override a deprecated API,
Recompile with -Xlint:deprecation for details
Some input files used unchecked or unsafe operations,
Recompile with -Xlint:-uncheckedfor details
```
### Steps to Reproduce

1. Create android-bindinglib for [com.tencent.mm.opensdk](https://mvnrepository.com/artifact/com.tencent.mm.opensdk/wechat-sdk-android-without-mta/6.8.0)
2. Use `dotnet pack` command to package
3. Add the nuget package of the binding library to the Maui project
4. run `dotnet build`

### Expected Behavior
build success
### Actual Behavior
build failed with error
### Basic Information

- Version with issue: dotnet 6.0.100-rc.2.21505.57
- Last known good version:
- IDE: vs2022 pre7.0

### Reproduction Link

project repo: [Booster](https://github.com/realZhangChi/Booster)
binding lib: [/src/Booster.WeChat/Booster.WeChat.Binding.Android/](https://github.com/realZhangChi/Booster/tree/main/src/Booster.WeChat/Booster.WeChat.Binding.Android)
Maui project: [/sample/Booster.Sample/](https://github.com/realZhangChi/Booster/tree/main/sample/Booster.Sample)

Any help is appreciated, thanks!

**Comment by realZhangChi** [comment]
Hi,
I tried to convert [another aar library](https://mvnrepository.com/artifact/com.ezviz.sdk/ezviz-sdk/4.16.1) and got the same error. I guess this problem may be caused by deprecated API or unchecked or unsafe code used in the aar library, but there is nothing we can do about this aar library. 😢
Repos is [here](https://github.com/realZhangChi/Booster/tree/ezviz/src/Booster.Ezviz/Booster.Ezviz.Binding.Android)

**Comment by Redth** [comment]
I'm not sure what the ask is here exactly.  Can you provide more information about what you are trying to accomplish, what the expected outcome should be?

**Comment by jfversluis** [comment]
Seems like the bot didn't do its work 😅, but there has been no response, so closing this for now.
