### ISSUE TITLE
[Bug] [Android] RefreshView not resizing

### ISSUE THREAD

**Issue by LarsBehl** [dotnet/maui#3248]
### Description
When using a padding on `VerticalStackLayout`, to which elements get added after finishing an HTTP-request, inside a `RefreshView`, the size of the refresh views content is not getting calculated (updated) correctly.

### Steps to Reproduce

1. Create `ContentPage`
2. Add `RefreshView`
3. Add `ScrollView`
4. Add `VerticalStackLayout`
5. Add padding to `VerticalStackLayout`
6. Perform HTTP-request and add components to `VerticalStackLayout`

### Expected Behavior
The `RefreshView` gets resized correctly.

### Actual Behavior
The size of `RefreshView` is not updated.

### Basic Information

- Version with issue: 6.0.101-preview.9.1843
- Last known good version: -
- IDE: Visual Studio 2022 Preview 7

#### Actual:
![image](https://user-images.githubusercontent.com/26459044/140169497-715cc617-1174-496a-b3e6-6e40165c31c2.png)
#### Expected:
![image](https://user-images.githubusercontent.com/26459044/140169901-d6db911e-4b7b-4f9c-98b6-ab81bb6fb596.png)
(Removed padding due to the issue)

### Reproduction Link
[Here](https://github.com/LarsBehl/StatusApp/blob/feature/stat-07_refreshView/MainPage.xaml) is a link to the `XAML` where the issue is currently present.

**Comment by LarsBehl** [comment]
I noticed, that if the `RefreshView` already contains an element, like a `Label` for example, the size of the `RefreshView` is also not getting updated

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/ETPBIyE2NlVCmV1osKd8g9QBwdeghMxPLZ2u3BqnEdrLBw?e=gVt7Jv

**Comment by Realinspirer** [comment]
Possible relation with this - https://github.com/dotnet/maui/issues/5772
Bug still on VS Preview 1.1
