### ISSUE TITLE
[Bug] MAUI Blazor - Router AppAssembly could not find pages if assembly is different

### ISSUE THREAD

**Issue by sencagri** [dotnet/maui#3258]
### Description
I am building a blazor project which has a common razor library. WASM and Blazor server uses same project to serve pages and components. I have added a new MAUI Blazor project and referenced the library. Project builds and runs but Router couldn't find the pages. It just show a white blank screen. I am adding a sample project for reproducing.

### Expected Behavior
It should run like Blazor Server and Blazor WASM. 

### Actual Behavior
Router can find MainLayout but cannot find the actual page.

#### MAUI Blazor - Not Working Blank Screen
![MAUI Blazor - Not Working Blank Screen](https://user-images.githubusercontent.com/7950917/140319876-708b0dda-ed70-49fe-ae5d-e8f7e9eaddb9.png)

#### Blazor WASM - Working
![Blazor WASM - Working](https://user-images.githubusercontent.com/7950917/140319974-ba7453c8-d137-4cba-856e-8a012f5f0423.png)

#### Blazor Server - Working
![Blazor Server - Working](https://user-images.githubusercontent.com/7950917/140320092-a6c9a83c-81d8-46ab-a610-774ad79e4632.png)

### What I have tried

![image](https://user-images.githubusercontent.com/7950917/140320815-2c0a6f54-dff4-4d28-90d7-8040ed9ecf77.png)

### Reproduction Link
[BlazorSharedProject.zip reproducing project](https://github.com/dotnet/maui/files/7474967/BlazorSharedProject.zip)

**Comment by rogihee** [comment]
You need to tell the Router that there are additional assemblies to scan for routes by setting the "AdditionalAssemblies" property, so something like:

```
AdditionalAssemblies="new[] { typeof(BixTextComponent).Assembly }" 
```

**Comment by sencagri** [comment]
I already tried that both with changing AppAssembly and adding my component assembly to AdditionalAssemblies. It didn't work.

![image](https://user-images.githubusercontent.com/7950917/140479574-24f42bd5-d943-4fc0-9944-488010529e34.png)

**Comment by Eilon** [comment]
I just tried this with AdditionalAssemblies and it worked fine.

In my MAUI app project I have `Main.razor` with this:

```
<Router
    AppAssembly="@GetType().Assembly"
    PreferExactMatches="true"
    AdditionalAssemblies="new[]{typeof(MauiRazorClassLibrarySample.Component2).Assembly}"> @* <------- THIS *@    <Found Context="routeData">
        <RouteView RouteData="@routeData" />
    </Found>
    <NotFound>
        <h1>Not found</h1>
        <p>Sorry, there's nothing here.</p>
    </NotFound>
</Router>
```

And in some page in the main app I have this navigation link:

```html
<a href="/page1">Page1</a>
```

And in my Razor Class Library (RCL) I have a file `Component2.razor` with exactly these contents:

```
@page "/page1"

<h3>Component2</h3>

@code {

}
```

And when I click the link, it correctly loads the `page1` page defined in the RCL's `Component2.razor` file.

**Comment by sencagri** [comment]
It looks same as mine. But I will try it again asap.

**Comment by Eilon** [comment]
I think I found the difference. In your repro app the file `BlazorShared.Native\Main.razor` has the app assembly also listed as an AdditionalAssembly:

```
AdditionalAssemblies="new[]{GetType().Assembly, typeof(BlazorShared.Docs.Pages.Index).Assembly}">
```

If you change it to just this;

```
AdditionalAssemblies="new[]{typeof(BlazorShared.Docs.Pages.Index).Assembly}">
```

Then it works.

**Comment by Eilon** [comment]
BTW there is actually a hidden exception that says something about a duplicate route, which makes sense, because the main assembly has everything duplicated, but unfortunately that hidden exception just makes Blazor fail to load.

So I think there are two unrelated bugs here:

1. Blazor should possibly have a specific error saying that an assembly is duplicated, or just allow it (by ignoring the duplicate)
2. The duplicate route error should be more visible to the user somehow

**Comment by sencagri** [comment]
Thank you so much!

8 Ara 2021 Çar 03:23 tarihinde Eilon Lipton ***@***.***> şunu
yazdı:

**Comment by Eilon** [comment]
I filed these issues:

* Blazor bug for how duplicated app assembly is treated: https://github.com/dotnet/aspnetcore/issues/38882
* Improve Blazor Hybrid experience with invalid routes (possibly due to duplicated router assembly): https://github.com/dotnet/maui/issues/3695

But I think the specific issue in this bug is resolved, so I'm closing this out. Very interesting issue 😄
