### ISSUE TITLE
[Enhancement] StoreReview

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3263]
Hi,

Please add the [StoreReview](https://github.com/jamesmontemagno/StoreReviewPlugin)  plugin to .NET MAUI.

Thanks,
Jassim

**Comment by jfversluis** [comment]
It's available in the plugin, to be honest I don't see why this should be part of .NET MAUI directly. I would love to hear a detailed explanation of why you would think otherwise.

Thanks!

**Comment by jrahma** [comment]
> would

Review and Rating is a very important part when it comes to Marketing and it became a core / essentials not just an add-on
