### ISSUE TITLE
[Bug] Crash when debugging app on Android emulator

### ISSUE THREAD

**Issue by Kirbyrawr** [dotnet/maui#3264]
### Description
Debugging an app without any big change in an Android API 31 Emulator crash due to an Unauthorized Access Exception

### Steps to Reproduce

1. Try to run an app with fonts targeting Android API 31 Emulator (Android 12)

### Expected Behavior
Runs normally

### Actual Behavior
Throws an error on app start
`System.UnauthorizedAccessException: 'Access to the path '/data/fonts' is denied.'`

### Basic Information

- Version with issue: Preview 9
- Last known good version: N/A
- IDE: Visual Studio Community 2022 Preview 7
- Platform Target Frameworks: 
  - Android: Android 12 - API 31

**Comment by pierre01** [comment]
the bug is easily reproducible by using any shape on the main page from the default MAUI Template:
to  reproduce: Create a MAUI APP, and on the MainPage.XAML 
replace:
    <Image Grid.Row="4"
                Source="dotnet_bot.png" .... />
with: 
     <Rectangle Grid.Row="4" Fill="Red" WidthRequest="250" HeightRequest="250"/>

**Comment by kristinx0211** [comment]
Not reproducible with Android 11.
