### ISSUE TITLE
`<MauiAsset>` is hard to use

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#3270]
### Description

I added a `<MauiAsset Include="Resources\Assets\*">` in my project and I was unable to easily find how to retrieve it. I used Essentials' `FileSystem.OpenAppPackageFileAsync` and I found that it went to different folders:

- Windows => Assets\Resources\Assets\*
- Android => Resources\Assets\*
- iOS/MacCat => error : The name 'Resources' is reserved and cannot be used.

**Comment by mattleibow** [comment]
@Eilon I think whatever we do is going to affect Blazor. I think we need to get that #791 change in. Just looking at your issues, I see there are a few around this.

We probablu need somehting for Blazor (that can convert to a MauiAsset under the hood with special values), but right now we need something way better than what we have.

**Comment by Eilon** [comment]
@mattleibow maybe we should have a chat about MauiAssets and whatever we'd like to change/improve there?

**Comment by IIARROWS** [comment]
So... did anyone found a way to access assets?

**Comment by limefrogyank** [comment]
@IIARROWS I may be "doing it wrong" but for UWP, MauiAssets doesn't work.  I have to use `Content` type build action, then use `Maui.Essentials.FileSystem.OpenAppPackageFileAsync` and a relative path to the file.

For Android, I **must** use `MauiAsset` build action and the same package.  

This seems broken to me.

**Comment by limefrogyank** [comment]
Guess I was doing it wrong.  With UWP, you should set your build action to `MauiAsset` then:

`await Microsoft.Maui.Essentials.FileSystem.OpenAppPackageFileAsync("Assets/{same path in app });`

**Comment by Eilon** [comment]
Hi folks, we definitely have some work to do to make _consuming_ MauiAssets easier.

Here's the "rough" code that we have in BlazorWebView for each platform (Android, iOS/MacCatalyst, and WinUI):

* Android (uses Android AssetManager): https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Android/AndroidMauiAssetFileProvider.cs
* iOS/MacCatalyst (reads from disk using the bundle resource path): https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/iOS/iOSMauiAssetFileProvider.cs#L20
* WinUI (using the package's install location storage APIs): https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs#L74-L76

But of course we should just make this a lot easier to use. But hopefully this unblocks people in the meantime.

**Comment by Eilon** [comment]
Notes from meeting with @mattleibow :

1. Remove "Assets" special folder from Windows targets in Resizetizer to make it consistent with other platforms
2. Consider updating project template to have MauiAsset glob
	a. Add glob to template: <MauiAsset Include="Resources/Raw/**" LogicalName="%(RecursiveDir)%(FN)%(EXT)" />
	b. Add a sample raw resource "txt" file to "Resources/Raw/asset.txt" --> the content of this file can show the code to read it using Essentials.OpenPackageFileAsync()
	c. Fix the bug where LogicalName doesn't work on some platforms
3. Remove "Assets" path combine workaround from BlazorWebViewHandler on Windows: src\BlazorWebView\src\Maui\Windows\WinUIWebViewManager.cs
4. Fix up any samples in the MAUI repo to be more consistent with how we expect MauiAssets to be used
