### ISSUE TITLE
[Bug] ImageButtons Aspect behave diferent depending on platform

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3272]
### Description
Property Aspect on ImageButton does not behave the same as Image
### Steps to Reproduce

1. Run [ImageButtons.zip](https://github.com/dotnet/maui/files/7481960/ImageButtons.zip) on each platform
2. Tap on each aspect option

### Expected Behavior
dotnet bot must be shown equals on both images
### Actual Behavior
dotnet bot does not shown equals on both images

### Screenshots
![image](https://user-images.githubusercontent.com/603023/140487868-3427b613-6b83-4938-b8dd-2e65ad5cbeba.png)
![image](https://user-images.githubusercontent.com/603023/140487909-e73fe276-f5fd-47d7-86b8-3cdd01f8e394.png)
![image](https://user-images.githubusercontent.com/603023/140487946-0a113a0c-8587-4462-bedb-5f56f6dd3967.png)
![image](https://user-images.githubusercontent.com/603023/140487988-38b2f3d3-fc80-4848-9471-20dd94e46568.png)

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EREgSRv7YpNEhfQ-9VpLQ5ABm7yCcXWogc1bIrsCPT5ivA?e=P5B85x

**Comment by Redth** [comment]
Will be fixed in #5198
