### ISSUE TITLE
[Bug] wwwroot is not included when using blazor + WPF + MSIX for Windows Store

### ISSUE THREAD

**Issue by albertwoo** [dotnet/maui#3275]
### Steps to Reproduce

1. Pull https://github.com/jorgearteiro/BlazorDesktopWPF
2. Add "Windows Application Packaging project" for BlazorDesktopWPF
3. Create a bundle
4. Check the bundle file you will see the wwwroot is not included and the app will not be able to start

### Expected Behavior
All razor resourcces should be included when MSIX bundling

**Comment by jfversluis** [comment]
Thanks for reporting! However this does not seem like the appropriate place. This project is a pure WPF project and has nothing to do with .NET MAUI :)

Probably a better place for it would be in the project that you linked to maybe get some guidance or at the WPF repo: https://github.com/dotnet/wpf

**Comment by budcribar** [comment]
@jfversluis This should not be closed as the project is a BlazorDesktopWPF project which is owned by the maui team I will run into this problem soon.

**Comment by jfversluis** [comment]
@Eilon does this seem correct?

**Comment by Eilon** [comment]
Yeah, the .NET MAUI, WPF, and WinForms BlazorWebView controls for Blazor Hybrid/Desktop are all here! Surprise 😄

**Comment by Eilon** [comment]
This might be fixed by https://github.com/dotnet/maui/pull/3532. I'll have to check it out.

**Comment by Eilon** [comment]
Not fixed by  #3532, but the fix depends on it. In  #3532 we get the build targets to be included, but the targets there are insufficient. I think I have this fixed locally, just doing some more tests to verify WPF and WinForms.
