### ISSUE TITLE
[Bug] [Android] FlyoutPage.Detail not updating correctly on async operation

### ISSUE THREAD

**Issue by LarsBehl** [dotnet/maui#3279]
### Description
Content of `Flyout.Detail` not getting updated correctly when performing `async` operations, e.g. performing HTTP-requests.

#### Note
While debugging I noticed, that the issue emerges as soon as `await` is called on the `HttpClient`. When adding an additional `Task.Delay(1000)` infront of the call to the `HttpClient`, the `ActivityIndicator`, which is present on the page, gets displayed. When omitting th `Task.Delay(1000)` the `ActivityIndicator` won't be displayed.

### Steps to Reproduce

1. Create `FlyoutPage`
2. Set created `FlyoutPage` as MainPage
3. Create `ContentPage`
4. Request some resources on button press, which are displayed in the `ContentPage`, with `HttpClient`
5. Set the `ContentPage` as `FlyoutPage.Detail`

### Expected Behavior
The behavior of the `ContentPage` is the same as without `FlyoutPage`, updating the UI correctly.

### Actual Behavior
The behavior of the `ContentPage` changes, the UI is not getting updated correctly

### Basic Information

- Version with issue: 6.0.101-preview.9.1843
- Last known good version: -
- IDE: Visual Studio 2022 Preview 7
- Platform Target Frameworks: 
  - Android: 28  

#### After application initialization:
![image](https://user-images.githubusercontent.com/26459044/140510214-9ea844c0-ed65-469c-bf1e-c615526307af.png)
#### After performing the HTTP-request:
![image](https://user-images.githubusercontent.com/26459044/140510258-a2d198cd-b4f7-4647-9070-78db4cfa3c5c.png)

### Reproduction Link
[Here](https://github.com/LarsBehl/MauiFlyoutPageDetail) is a link to a repro.

**Comment by kristinx0211** [comment]
@LarsBehl thanks for your report. but your reproduction link is lost, please take a check that should greatly speed up the process, thanks!

**Comment by LarsBehl** [comment]
@kristinx0211 sorry, deleted the branch without setting a perma link. However, I still had the branch locally available and checked out the old commit. The issue was originally reported with preview 9. I ran the code with preview 11 and everything seems to work just fine. So the issue seems to be fixed 🤔

**Comment by LarsBehl** [comment]
Just created a repo with a minimal repro which can be found [here](https://github.com/LarsBehl/MauiFlyoutPageDetail). As my spare time is currently pretty limited, I won't be able to once again check preview 9 with the repro. But once again, I was not able to reproduce the issue with preview 11

**Comment by kristinx0211** [comment]
@LarsBehl thanks for your update, glad to see the issue has been fixed on the new build. so I will close this issue.
