### ISSUE TITLE
[Bug] Collection view empty in Mac

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3280]
### Description
Collection view in mac does not render setting items source in xaml
### Steps to Reproduce

1. Run [CollectionView.zip](https://github.com/dotnet/maui/files/7486071/CollectionView.zip) in maccatalist with command  
dotnet build -t:Run -f net6.0-maccatalyst

### Expected Behavior
A white page with items: 
![image](https://user-images.githubusercontent.com/603023/140512921-6d823afe-1e65-4c0a-b87c-f96c2b7f6eb1.png)

### Actual Behavior
An empty page
![image](https://user-images.githubusercontent.com/603023/140513051-d20edcad-122e-4958-bb98-ffbe15feaab0.png)

**Comment by kristinx0211** [comment]
verified repro on mac and with the above project.

**Comment by jamesmontemagno** [comment]
I am now seeing a collection view on macos populate with 1 of 13 items and then crash after that.

Repro in the final folder in https://github.com/dotnet-presentations/dotnet-maui-workshop @hartez  @PureWeen

**Comment by davidortinau** [comment]
Original issue fixed. Please open a new issue for related.

**Comment by paratype-fonts** [comment]
@davidortinau Please clarify is the fix has been merged into the latest available version. I have:
% dotnet workload list
Installed Workload Ids      Installation Source
-----------------------------------------------
maui                        SDK 6.0.400        

The issue with the empty CollectionView is still there.
