### ISSUE TITLE
[Spec] Publishing MAUI apps should be consistent across platforms from the command line for CI/CD

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#3283]
Goal: Make `dotnet publish` relatively consistent and relatively free of platform specific arguments required...

Consider the following scenario for building in CI:
`dotnet publish -f net6.0-android -c Release -o ./artifacts`

Expected output:
- `./artifacts/com.app.id.aab` (Signed)
- `./artifacts/com.app.id.apk` (Signed)

`dotnet publish -f net6.0-ios -c Release -o ./artifacts`

Expected output:
- `./artifacts/com.app.id.app`
- `./artifacts/com.app.id.ipa`

 - [x] Android https://github.com/xamarin/xamarin-android/issues/6393
 - [x] iOS https://github.com/xamarin/xamarin-macios/issues/12997

**Comment by jonathanpeppers** [comment]
I remember there was some talk about making `dotnet build` be "the way" and potentially deprecating `dotnet publish`. (I can't find a public GitHub issue on it, though). I know the WASM team was going to move to using `dotnet build` as much as possible.

Is there a reason `dotnet build -c Release` isn't sufficient here? It also has an `-o` argument; that just changes `bin\Release\` to something else.

**Comment by jfversluis** [comment]
Also see: 

* https://github.com/dotnet/maui/issues/4377
* https://github.com/dotnet/maui/issues/4397
* https://github.com/dotnet/maui/issues/4329

**Comment by HobDev** [comment]
Building CI/CD pipeline would become simpler with this.

**Comment by RichardMarsh** [comment]
Would just like to add that this would be great. We are using CI/CD to produce the apps and push them to app center. Right now the tooling to do this doesn't feel well documented or consistent for iOS and Android.
