### ISSUE TITLE
[Bug] [Windows] Narrator randomly announces "Desktop child side bridge pane" before various controls

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#3284]
### Description

Narrator randomly announces "Desktop child side bridge pane" before various controls

### Steps to Reproduce

1.  Run the .NET MAUI control gallery on Windows
2.  Activate Narrator
3.  Navigate through the page via keyboard tab navigation
4.  Observe the described behavior

### Expected Behavior
"Desktop child side bridge pane" should not be announced at any point

### Actual Behavior
"Desktop child side bridge pane" is sporadically announced

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by XamlTest** [comment]
Verified Repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32227.94.main]. Repro Project is available(A simple .NET MAUI APP):  "\\mlangfs1\Public\dotnet maui\Repro Project\3284.zip"

**Comment by XamlTest** [comment]
Verified this issue on Visual Studio Enterprise 17.6.0 Preview 2.0. Repro on Windows with below Project:
[3284.zip](https://github.com/dotnet/maui/files/11195927/3284.zip)

**Comment by PureWeen** [comment]
This has been fixed by the latest stable 1.3 release of WinAPPSDK
