### ISSUE TITLE
[Spec]  Setup Platform Device Tests to use xHarness

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#329]
# Setup CI and local cake scripts to use xHarness

### Steps

- Merge essentials PR into main-handler https://github.com/xamarin/Xamarin.Forms/pull/13583
- extract the xharness/device parts of this file https://github.com/xamarin/Xamarin.Forms/blob/1dafd742f4cd55d3180060cca7748f00cc5be5f8/src/Essentials/other/device-tests-build.cake to `eng/devices.cake`
- Generalize the TestInstrumentation code that's now apart of the platform handler tests code so that Essentials and our Platform device tests are using the same bits 
  -  https://github.com/xamarin/Xamarin.Forms/blob/main-handler/src/Platform.Handlers/tests/Xamarin.Platform.Handlers.DeviceTests.Android/TestInstrumentation.cs
- At this point we need the code that's able to run the tests against essentials to also work against our Platform.HandlerTests so do whatever makes sense here for splitting up the code. 
   - Is it just one cake file? maui-device-tests.cake that has an array of projects?
   - Should we have essentials-device-tests.cake,  maui-device-tests.cake, common-device-tests.cake ?

**Comment by mattleibow** [comment]
With regards to cake files, we can totally do a reuse over multiple files: https://cakebuild.net/docs/writing-builds/preprocessor-directives#load-directive

I use that all over the show for SkiaSharp and have each native platform have its own cake with tasks, and then they all reference a base native which references a base shared cake.

We can do this for forms as well. Have each device test have a simple cake file, and then include all the actual work in a base. This can be done for all other types of testing. Sort of the way Makefiles were in each folder, but then as you go up, it builds more.

**Comment by PureWeen** [comment]
That sounds perfect @mattleibow  !!
