### ISSUE TITLE
Does MAUI have any plans to make software developed through MAUI run on Windows 7?

### ISSUE THREAD

**Issue by sogeisetsu** [dotnet/maui#3294]
There are still many people using windows 7. Is it possible for MAUI to make software developed through MAUI run on windows7? Even if there is no way to get an excellent experience on win10 in Windows 7, it doesn't matter. Sometimes there is no way to give up users who use windows7 and do not want to re-use WPF to develop again. Is there a better solution besides uno now?

[Related discussions about maui and win7](https://github.com/dotnet/maui/discussions/2576)

**Comment by pierre01** [comment]
Microsoft support for Windows 7 started to end in 2020. You can develop Apps in WPF that are more powerful than what MAUI offers at this time, still reuse  85% of your business logic code and WPF is a great XAML learning tool for what MAUI can become.

**Comment by sogeisetsu** [comment]
> Microsoft support for Windows 7 started to end in 2020. You can develop Apps in WPF that are more powerful than what MAUI offers at this time, still reuse 85% of your business logic code and WPF is a great XAML learning tool for what MAUI can become.

Thank you for your answer👍, I almost forgot that Microsoft has ended support for win7. Maui is not a stable version now. Perhaps few people will use win7 after maui is perfected. Maybe now I can just use maui as a tool for developing Android and ios software. Use wpf to develop general desktop programs. If I need support for some new features of windows, such as support for touch, I will use winui3. This may seem troublesome, but as long as  pay attention when developing, quite a lot of code can be reused in wpf, maui and winui3 projects.

**Comment by hanjunjun** [comment]
We also have a large number of C-end products that use win7. If win7 is not supported across platforms, we can only replace other cross-platform client solutions.
