### ISSUE TITLE
[Net6][Android] Could not activate JNI Handle exception

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#3296]
When running a native android application which contains a control that is in a separate assembly I get the following exception

> System.NotSupportedException: 'Could not activate JNI Handle 0xbeeb42d8 (key_handle 0xd5ceccc) of Java type 'crc645e9136c190843a3c/FlexGrid' as managed type 'C1.Android.Grid.FlexGrid'.'

The application runs fine in an emulator

The control is defined in a axml layout resource

```
    <c1.android.grid.FlexGrid
        android:id="@+id/grid"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
```

and the application project definition is the following
```
  <PropertyGroup>
    <TargetFramework>net6.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AndroidSupportedAbis>armeabi-v7a</AndroidSupportedAbis>
    <RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
  </PropertyGroup>
```

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?. Thanks in advance!.

**Comment by arivoir** [comment]
Now this is also happening in the emulator too. Unfortunately I can't share the code. Any other way to know what's the real cause of this issue?

**Comment by hartez** [comment]
Does running in Release vs Debug mode make any difference?

**Comment by arivoir** [comment]
I needed to set PublishTrimmed to false (otherwise it didn't compile) and it happened the same as Debug

**Comment by arivoir** [comment]
This is still happening in Visual Studio Enterprise 2022 Version 17.2.0 Preview 1.0

Xamarin.Android SDK   12.2.99.75 (main/398afd4)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a5d1934
    Java.Interop: xamarin/java.interop/main@32635fd6
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.37.2@51b4821
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0e80ea1

**Comment by arivoir** [comment]
Now I can see the exception details, seems a problem with a resource

> {System.NotSupportedException: Could not activate JNI Handle 0xffec68c8 (key_handle 0xbeeebe2) of Java type 'crc645e9136c190843a3c/FlexGrid' as managed type 'C1.Android.Grid.FlexGrid'. ---> Android.Content.Res.Resources+NotFoundException: Drawable android:color/text_color_primary with resource ID #0x106015f ---> Android.Content.Res.Resources+NotFoundException: File res/color/text_color_primary.xml from drawable resource ID #0x106015f ---> Org.XmlPull.V1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable  --- End of managed Org.XmlPull.V1.XmlPullParserException stack trace ---org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:190)	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:122)	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)	at android.content.res.Resources.loadDrawable(Resources.java:897)	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)	at mono.android.TypeManager.n_activate(Native Method)	at mono.android.TypeManager.Activate(TypeManager.java:7)	at crc645e9136c190843a3c.FlexGrid.<init>(FlexGrid.java:32)	at java.lang.reflect.Constructor.newInstance0(Native Method)	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)	at android.view.LayoutInflater.createView(LayoutInflater.java:647)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420)	at android.app.Activity.setContentView(Activity.java:2771)	at crc64ea0344f159b2163b.ColumnLayoutActivity.n_onCreate(Native Method)	at crc64ea0344f159b2163b.ColumnLayoutActivity.onCreate(ColumnLayoutActivity.java:32)	at android.app.Activity.performCreate(Activity.java:7136)	at android.app.Activity.performCreate(Activity.java:7127)	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loop(Looper.java:193)	at android.app.ActivityThread.main(ActivityThread.java:6669)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)  --- End of managed Org.XmlPull.V1.XmlPullParserException stack trace ---org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:190)	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:122)	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)	at android.content.res.Resources.loadDrawable(Resources.java:897)	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)	at mono.android.TypeManager.n_activate(Native Method)	at mono.android.TypeManager.Activate(TypeManager.java:7)	at crc645e9136c190843a3c.FlexGrid.<init>(FlexGrid.java:32)	at java.lang.reflect.Constructor.newInstance0(Native Method)	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)	at android.view.LayoutInflater.createView(LayoutInflater.java:647)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420)	at android.app.Activity.setContentView(Activity.java:2771)	at crc64ea0344f159b2163b.ColumnLayoutActivity.n_onCreate(Native Method)	at crc64ea0344f159b2163b.ColumnLayoutActivity.onCreate(ColumnLayoutActivity.java:32)	at android.app.Activity.performCreate(Activity.java:7136)	at android.app.Activity.performCreate(Activity.java:7127)	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loop(Looper.java:193)	at android.app.ActivityThread.main(ActivityThread.java:6669)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)   --- End of inner exception stack trace ---  --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---android.content.res.Resources$NotFoundException: File res/color/text_color_primary.xml from drawable resource ID #0x106015f	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)	at android.content.res.Resources.loadDrawable(Resources.java:897)	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)	at mono.android.TypeManager.n_activate(Native Method)	at mono.android.TypeManager.Activate(TypeManager.java:7)	at crc645e9136c190843a3c.FlexGrid.<init>(FlexGrid.java:32)	at java.lang.reflect.Constructor.newInstance0(Native Method)	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)	at android.view.LayoutInflater.createView(LayoutInflater.java:647)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420)	at android.app.Activity.setContentView(Activity.java:2771)	at crc64ea0344f159b2163b.ColumnLayoutActivity.n_onCreate(Native Method)	at crc64ea0344f159b2163b.ColumnLayoutActivity.onCreate(ColumnLayoutActivity.java:32)	at android.app.Activity.performCreate(Activity.java:7136)	at android.app.Activity.performCreate(Activity.java:7127)	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loop(Looper.java:193)	at android.app.ActivityThread.main(ActivityThread.java:6669)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:190)	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:122)	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)	... 34 more  --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---android.content.res.Resources$NotFoundException: File res/color/text_color_primary.xml from drawable resource ID #0x106015f	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)	at android.content.res.Resources.loadDrawable(Resources.java:897)	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)	at mono.android.TypeManager.n_activate(Native Method)	at mono.android.TypeManager.Activate(TypeManager.java:7)	at crc645e9136c190843a3c.FlexGrid.<init>(FlexGrid.java:32)	at java.lang.reflect.Constructor.newInstance0(Native Method)	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)	at android.view.LayoutInflater.createView(LayoutInflater.java:647)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420)	at android.app.Activity.setContentView(Activity.java:2771)	at crc64ea0344f159b2163b.ColumnLayoutActivity.n_onCreate(Native Method)	at crc64ea0344f159b2163b.ColumnLayoutActivity.onCreate(ColumnLayoutActivity.java:32)	at android.app.Activity.performCreate(Activity.java:7136)	at android.app.Activity.performCreate(Activity.java:7127)	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loop(Looper.java:193)	at android.app.ActivityThread.main(ActivityThread.java:6669)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:190)	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:122)	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)	... 34 more   --- End of inner exception stack trace ---   at Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/builder/azdo/_work/2/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 11283   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/builder/azdo/_work/2/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 389   at Android.Content.Res.TypedArray.GetDrawable(Int32 index) in /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Android.Content.Res.TypedArray.cs:line 394   at C1.Android.Grid.FlexGrid.InitializeStyle(IAttributeSet attrs, Int32 defStyleAttr) in C:\Projects\GrapeCity\c1-netcore\Shared\Controls\Grid\FlexGrid.cs:line 357   at C1.Android.Grid.FlexGrid..ctor(Context context, IAttributeSet attrs) in C:\Projects\GrapeCity\c1-netcore\Android\Controls\Grid\C1.CodeGeneration\C1.CodeGeneration.ControlGenerator\FlexGrid.g.cs:line 274   at Java.Interop.TypeManager.Activate(IJavaPeerable o, IntPtr jobject, ConstructorInfo cinfo, Object[] parms) in /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:line 177  --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---android.content.res.Resources$NotFoundException: Drawable android:color/text_color_primary with resource ID #0x106015fCaused by: android.content.res.Resources$NotFoundException: File res/color/text_color_primary.xml from drawable resource ID #0x106015f	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)	at android.content.res.Resources.loadDrawable(Resources.java:897)	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)	at mono.android.TypeManager.n_activate(Native Method)	at mono.android.TypeManager.Activate(TypeManager.java:7)	at crc645e9136c190843a3c.FlexGrid.<init>(FlexGrid.java:32)	at java.lang.reflect.Constructor.newInstance0(Native Method)	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)	at android.view.LayoutInflater.createView(LayoutInflater.java:647)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420)	at android.app.Activity.setContentView(Activity.java:2771)	at crc64ea0344f159b2163b.ColumnLayoutActivity.n_onCreate(Native Method)	at crc64ea0344f159b2163b.ColumnLayoutActivity.onCreate(ColumnLayoutActivity.java:32)	at android.app.Activity.performCreate(Activity.java:7136)	at android.app.Activity.performCreate(Activity.java:7127)	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loop(Looper.java:193)	at android.app.ActivityThread.main(ActivityThread.java:6669)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:190)	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:122)	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)	... 34 more  --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---android.content.res.Resources$NotFoundException: Drawable android:color/text_color_primary with resource ID #0x106015fCaused by: android.content.res.Resources$NotFoundException: File res/color/text_color_primary.xml from drawable resource ID #0x106015f	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)	at android.content.res.Resources.loadDrawable(Resources.java:897)	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)	at mono.android.TypeManager.n_activate(Native Method)	at mono.android.TypeManager.Activate(TypeManager.java:7)	at crc645e9136c190843a3c.FlexGrid.<init>(FlexGrid.java:32)	at java.lang.reflect.Constructor.newInstance0(Native Method)	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)	at android.view.LayoutInflater.createView(LayoutInflater.java:647)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420)	at android.app.Activity.setContentView(Activity.java:2771)	at crc64ea0344f159b2163b.ColumnLayoutActivity.n_onCreate(Native Method)	at crc64ea0344f159b2163b.ColumnLayoutActivity.onCreate(ColumnLayoutActivity.java:32)	at android.app.Activity.performCreate(Activity.java:7136)	at android.app.Activity.performCreate(Activity.java:7127)	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loop(Looper.java:193)	at android.app.ActivityThread.main(ActivityThread.java:6669)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:190)	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:122)	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)	... 34 more   --- End of inner exception stack trace ---   at Java.Interop.TypeManager.Activate(IJavaPeerable o, IntPtr jobject, ConstructorInfo cinfo, Object[] parms) in /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:line 184   at Java.Interop.TypeManager.n_Activate(IntPtr jnienv, IntPtr jclass, IntPtr typename_ptr, IntPtr signature_ptr, IntPtr jobject, IntPtr parameters_ptr) in /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:line 170}
