### ISSUE TITLE
[Enhancement] Replace IsVisible with Visibility (similar to Android)

### ISSUE THREAD

**Issue by GalaxiaGuy** [dotnet/maui#33]
## Summary
Xamarin Forms uses a two state visibility system, something is visible or it is not. Android has a three state visibility system. The third state is not rendered, but is still used for layout. It would mainly be `Layout`s that care about this third state.

## API Changes

```csharp
public enum Visibility
{
    Visible,
    Invisible,
    Gone    
}

public class VisualElement
{
    public static readonly BindableProperty VisibilityProperty = BindableProperty.Create(
        nameof(Visibility), typeof(Visibility), typeof(VisualElement), Visibility.Visible);

    public Visibility Visibility
    {
        get => (Visibility)GetValue(VisibilityProperty);
        set => SetValue(VisibilityProperty, value);
    }
}
```

## Backwards compatibility

`IsVisible` would be deprecated.
`true` would map to `Visible` and `false` to `Gone`. `Invisible` could go either way., since using both `IsVisible` and `Visibility` in the same view hierarchy is likely to be broken (i.e. setting `Visibilty` and getting `IsVisible` would not be recommended).

One big caveat is whether this can be reasonably implemented - i.e. can all native renderers be correctly measured while invisible.

## Intended Use Case

This can be useful in several situations, for example when something can be toggled visible or invisible, but is also not a predictable size. Using the `Invisible` state means the surrounding layout can be stable while the visibility is toggled.

**Comment by BillHenning** [comment]
While on the topic, all prior Microsoft UI platforms have used "Visible", "Hidden", and "Collapsed" as the three Visibility options.  Would those be better to use since they are known to XAML devs?

**Comment by h82258652** [comment]
```Visibility``` is an enum that means we can use different names for the same value.
How about this:
```C#
public enum Visibility
{
    Visible = 0,
    Hidden = 1,
    Invisible = 1,
    Collapsed = 2,
    Gone = 2
}
```

**Comment by GalaxiaGuy** [comment]
The exact name is less important. I think having both would be a mistake though. A new user looking at some XAML that included both `Collapsed` and `Gone` would naturally assume they did different things.

**Comment by bkaankose** [comment]
In WPF, it is Hidden. In UWP XAML, there is no Hidden and only Visible and Collapsed exists. If MAUI must include this support, I suggest Visible, Collapsed and Hidden naming as part of the .NET legacy. There should be no confusion for the new developers by introducing different names for the same functionality.

**Comment by BillHenning** [comment]
Since Maui is a XAML variant and XAML developers are familiar with the Visible/Collapsed naming (and WPF devs with the Hidden value), it seems like using those established standard names is best.

**Comment by ChaseFlorell** [comment]
I do like this proposal. Currently if I need to reserve the space for something but make it invisible, I have to have `IsVisible = true` and also `Opacity = 0`

**Comment by vdvman1** [comment]
`Gone` feels less descriptive than `Collapsed` in my opinion, `Gone` feels like the component is actually destroyed and no longer exists, whereas `Collapsed` is more like it is still there but taking no space.
