### ISSUE TITLE
[Bug] Maui Templates doesn't automatically update with VS installer (17.1.0 Preview 1.0)

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#3312]
### Description

Updated VS2022 from 17.0.0 Preview 7.0 to 17.1.0 Preview 1.0, but .NET MAUI templates are still with the previous Preview 9 version. Doesn't update as part of VS installer. A manual update is required.

### Steps to Reproduce

1. Install VS2022 17.1.0 Preview 1.0
2. Create a new .NET MAUI project, WinUI3 references still pointing to 1.0.0-experimental1 package reference

### Expected Behavior

Should have updated the package templates to Preview 10

### Actual Behavior

Package templates are still pointing to Preview 9

### Basic Information

- Version with issue: **17.1.0 Preview 1.0**
- Last known good version: NA
- IDE: **VS2022**
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Installed the .NET MAUI templates from NuGet using the below command, but this manual step needs to be automated within the installer.

```shell
dotnet new --install Microsoft.Maui.Templates::6.0.101-preview.10.2068
```

Output:

C:\\>dotnet new --install Microsoft.Maui.Templates::6.0.101-preview.10.2068
The following template packages will be installed:
   Microsoft.Maui.Templates::6.0.101-preview.10.2068

**Microsoft.Maui.Templates is already installed, version: 6.0.101-preview.9.1843, it will be replaced with version 6.0.101-preview.10.2068.**
Microsoft.Maui.Templates::6.0.101-preview.9.1843 was successfully uninstalled.
Success: Microsoft.Maui.Templates::6.0.101-preview.10.2068 installed the following templates:
Template Name                         Short Name        Language  Tags
------------------------------------  ----------------  --------  ---------------------------------------------------
.NET MAUI App (Preview)               maui              [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI
.NET MAUI Blazor App (Preview)        maui-blazor       [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Blazor
.NET MAUI Class Library (Preview)     mauilib           [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI
.NET MAUI ContentPage (C#) (Preview)  maui-page-csharp  [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentPage (Preview)       maui-page-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentView (C#) (Preview)  maui-view-csharp  [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentView (Preview)       maui-view-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code

**Comment by drchilds** [comment]
To add to the OP's issue, it appears that a clean installation of VS 17.1.0 Preview 1 with a clean install of the .NET 6.0.0 SDK, the template package isn't installed at all. Installing the templates with the command line as suggested fixes the issue.

**Comment by egvijayanand** [comment]
This issue has been observed even when installing the Preview 12 updates also:

Below is the log of template update-check from the command line post Preview updates through VS Installer:

E:\>dotnet new --update-check
An update for template packages is available:
Package                   Current                  Latest
------------------------  -----------------------  -----------------------
Microsoft.Maui.Templates  6.0.101-preview.11.2349  6.0.200-preview.12.2441

To update the package use:
   dotnet new --install <PACKAGE_ID>::<VERSION>
   dotnet new --install Microsoft.Maui.Templates::6.0.200-preview.12.2441

To update all the packages use:
   dotnet new --update-apply

E:\>dotnet new --update-apply
The following template packages will be updated:
   Microsoft.Maui.Templates::6.0.200-preview.12.2441

Microsoft.Maui.Templates::6.0.101-preview.11.2349 was successfully uninstalled.
Success: Microsoft.Maui.Templates::6.0.200-preview.12.2441 installed the following templates:
Template Name                           Short Name        Language  Tags
--------------------------------------  ----------------  --------  ---------------------------------------------------
.NET MAUI App (Preview)                 maui              [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI
.NET MAUI Blazor App (Preview)          maui-blazor       [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Blazor
.NET MAUI Class Library (Preview)       mauilib           [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI
.NET MAUI ContentPage (C#) (Preview)    maui-page-csharp  [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentPage (XAML) (Preview)  maui-page-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentView (C#) (Preview)    maui-view-csharp  [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentView (XAML) (Preview)  maui-view-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code

Kindly fix this issue as it's recurring.

Regards,
Vijay Anand E G

**Comment by wenwen60** [comment]
Not repro on VS2022 17.2.0 Preview 2.0 [32215.517.main].

**Comment by egvijayanand** [comment]
Below is the log of templates update check and update apply post upgrade of Visual Studio 17.2 Preview 2.0

It's quite obvious that the issue is still open.

**Update check log:**

An update for template packages is available:
Package                   Current                  Latest                 
------------------------  -----------------------  -----------------------
Microsoft.Maui.Templates  6.0.200-preview.13.2865  6.0.200-preview.14.5099


To update the package use:
   dotnet new install <package>::<version>
   dotnet new install Microsoft.Maui.Templates::6.0.200-preview.14.5099

To update all the packages use:
   dotnet new update

**Update apply log:**

The following template packages will be updated:
   Microsoft.Maui.Templates::6.0.200-preview.14.5099

Microsoft.Maui.Templates::6.0.200-preview.13.2865 was successfully uninstalled.
Success: Microsoft.Maui.Templates::6.0.200-preview.14.5099 installed the following templates:
Template Name                           Short Name        Language  Tags                                               
--------------------------------------  ----------------  --------  ---------------------------------------------------
.NET MAUI App (Preview)                 maui              [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/Windows        
.NET MAUI Blazor App (Preview)          maui-blazor       [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Blazor 
.NET MAUI Class Library (Preview)       mauilib           [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/Windows        
.NET MAUI ContentPage (C#) (Preview)    maui-page-csharp  [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentPage (XAML) (Preview)  maui-page-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentView (C#) (Preview)    maui-view-csharp  [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
.NET MAUI ContentView (XAML) (Preview)  maui-view-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code

**Comment by egvijayanand** [comment]
Attaching the log as a file.

[Templates-Update.txt](https://github.com/dotnet/maui/files/8284817/Templates-Update.txt)
