### ISSUE TITLE
[Bug] Android back button doesnt work on .NET MAUI app

### ISSUE THREAD

**Issue by brzezinol** [dotnet/maui#3314]
### Description

After create .NET MAUI App (Preview) which is default "Counter" sample app, back button not work for exit from app.
I tested on Galaxy s20+ (Android 11), Emulator with Android 11.

It is related to #2835 

### Steps to Reproduce

1. Create default project
2. Build & Run debug
3. After app started, touch back button
4. App does not exit.

### Expected Behavior
App exits after touch back button, as default Android behavior.

### Actual Behavior
Nothing happens ater touch back button.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Microsoft Visual Studio Community 2022 Preview (64-bitowy) Wersja 17.0.0 Preview 7.0
- Microsoft Visual Studio Community 2022 Preview
Wersja 17.0.0 Preview 7.0
VisualStudio.17.Preview/17.0.0-pre.7.0+31825.309
Microsoft .NET Framework
Wersja 4.8.04084

Zainstalowana wersja: Community

Visual C# 2022   00482-90000-00000-AA800
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019   17.0.786.62401
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.786.62401
Aby uzyskać dodatkowe informacje, odwiedź stronę https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.786.62401
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.786.62401
Azure Functions and Web Jobs Tools

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Debugowanie .NET Core Debugging za pomocą podsystemu WSL   1.0
Debugowanie .NET Core Debugging za pomocą podsystemu WSL

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Kreatory programu Microsoft Visual C++   1.0
Kreatory programu Microsoft Visual C++

Menedżer pakietów NuGet   6.0.0
Menedżer pakietów NuGet w programie Visual Studio. Więcej informacji na temat narzędzia NuGet można znaleźć na stronie https://docs.nuget.org/

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Programuj, uruchamiaj i weryfikuj aplikacje platformy ASP.NET Core w środowisku docelowym. Używaj klawisza F5, aby uruchamiać aplikację z debugowaniem bezpośrednio w kontenerze, lub klawiszy CTRL+F5, aby edytować i odświeżać aplikację bez konieczności ponownego kompilowania kontenera.

Mono Debugging for Visual Studio   17.0.11 (54f19d2)
Support for debugging Mono processes with Visual Studio.

Narzędzia języka C#   4.0.0-6.21521.2+68d3c0e77ff8607adca62a883197a5637a596438
Składniki języka C# używane w środowisku IDE. Zależnie od typu projektu i jego ustawień może być używana inna wersja kompilatora.

Narzędzia języka Visual Basic   4.0.0-6.21521.2+68d3c0e77ff8607adca62a883197a5637a596438
Składniki języka Visual Basic używane w środowisku IDE. Zależnie od typu projektu i jego ustawień może być używana inna wersja kompilatora.

Pakiet hosta adaptera debugowania programu Visual Studio Code   1.0
Warstwa międzyoperacyjności na potrzeby hostowania adapterów debugowania programu Visual Studio Code w programie Visual Studio

Pakiet VC programu Microsoft Visual Studio   1.0
Pakiet VC programu Microsoft Visual Studio

Programowanie wieloplatformowych aplikacji mobilnych w języku Visual C++ (Android)   17.0.31822.380
Programowanie wieloplatformowych aplikacji mobilnych w języku Visual C++ (Android)

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2150514+d9e17e7b7f06829e976f616716a987599c5c66e9
Oferuje usługi językowe dla składni Razor platformy ASP.NET Core.

Rozszerzenia narzędzi kontenerów programu Visual Studio   1.0
Wyświetlanie i diagnozowanie kontenerów oraz zarządzanie nimi w programie Visual Studio.

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.1001.2002
Narzędzia TypeScript Tools dla programu Microsoft Visual Studio

Visual F# Tools   17.0.0-beta.21519.2+727a6abda5bb3276f3e8dd918b721c5d21464aac
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
Programowanie wspomagane przez sztuczną inteligencję na potrzeby programu Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Informacje o moim pakiecie

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.331 (d17-0@4dde409)
Rozszerzenie programu Visual Studio umożliwiające programowanie aplikacji Xamarin.iOS i Xamarin.Android.

Xamarin Designer   17.0.0.182 (remotes/origin/d17-0@ea204898d)
Rozszerzenie programu Visual Studio umożliwiające obsługę narzędzi programu Xamarin Designer w programie Visual Studio.

Xamarin Templates   17.0.13 (1bcd73e)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.0.5 (d17-0/6b0e6b2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d17-0@febb1367
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-0@a5194e9

Xamarin.iOS and Xamarin.Mac SDK   15.0.0.18 (577ff6329)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Affected Devices:
Samsung Galaxy s20+
Emulator Android 11

**Comment by julienGrd** [comment]
same probem here but different behavior

the app go in background but not really close (the Ondisappearing of my MainPage is not called)

if i reopen the app after (with the icon) it throw an exception System.NotImplementedException: 'Either set MainPage or override CreateWindow.' on  the OnCreate of my MainActivity.

I try but this kind of code in my MainPage but no effect
````
protected override bool OnBackButtonPressed()
    {
		(Application.Current).Quit();
		return base.OnBackButtonPressed();
    }
````

Do you have any workaround to properly close the app ? actually my main concern is because i include a webview in my MainPage and the unload of the webview is never called, i don't know if solve the first problem will solve this unload problem)

Any news on when it will be fixed ?

Thanks !

**Comment by VincentBu** [comment]
> 

@julienGrd we decide to close this issue since it doesn't repro, but your comment is a good question! Would you like to open a new issue?

**Comment by julienGrd** [comment]
@VincentBu I already open a specific issue here https://github.com/dotnet/maui/issues/4669, so you can close this one, thanks for your concern !
