### ISSUE TITLE
[Bug][Android] DisplayAlert does not work with NavigationPage

### ISSUE THREAD

**Issue by Jens-K-S** [dotnet/maui#3335]
### Description

DisplayAlert does not display a message when the MainPage is loaded in a NavigationPage.

### Steps to Reproduce

1.  Create new MauiApp
2.  Change App.xaml.cs
`MainPage = new NavigationPage(new MainPage());`
3. Change MainPage.xaml.cs: add line to method OnCounterClicked
`DisplayAlert("Test", "Hello world!", "Ok");`

### Expected Behavior

Show message "Hello world!"

### Actual Behavior

Message is not displayed.

### Basic Information

- Version with issue: maui 6.0.101-preview.10.2068
- Last known good version: maui preview 9
- IDE: Visual Studio Professional 17.1.0 Preview 1.0
- Platform Target Frameworks: net6.0-android
- Android Emulator: API 30 and 31

### Sample project

[MauiAppDA.zip](https://github.com/dotnet/maui/files/7513965/MauiAppDA.zip)

**Comment by mterhorst** [comment]
I am also experiencing the same issue.

**Comment by noelex** [comment]
DisplayPromptAsync also has this issue.

**Comment by VitalsTheCynical** [comment]
This is super frustrating for me. I ran the same exact program on an empty project without the NavigationPage, and it worked perfectly, as expected.

**Comment by hotrieudat** [comment]
I also got the same error

**Comment by PureWeen** [comment]
This appears to be fixed in Preview11. If you are still seeing this issue once Preview11 comes out please let me know and we can re-open

**Comment by PureWeen** [comment]
FYI for anyone that finds themselves here after installing Preview11

There are probably additional scenarios with Preview11 where if you are very deeply nested inside various page types then Alerts might not work

This should be completely fixed in Preview12

https://github.com/dotnet/maui/pull/3629
