### ISSUE TITLE
[Bug][Android] IllegalStateException on Navigation.PopAsync()

### ISSUE THREAD

**Issue by Jens-K-S** [dotnet/maui#3338]
### Description

When calling the method Navigation.PopAsync() an exception is thrown.

`Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'`

### Steps to Reproduce

1.  Create new MauiApp
2.  Change App.xaml.cs
`MainPage = new NavigationPage(new MainPage());`
3. Change MainPage.xaml.cs: add line to method OnCounterClicked
`Navigation.InsertPageBefore(new MainPage(), this);
_ = await Navigation.PopAsync();`

### Expected Behavior

The new page is displayed

### Actual Behavior

An exception is thrown

### Basic Information

- Version with issue: maui 6.0.101-preview.10.2068
- Last known good version: maui preview 9
- IDE: Visual Studio Professional 17.1.0 Preview 1.0
- Platform Target Frameworks: net6.0-android
- Android Emulator: API 30 and 31

### Sample project

[MauiAppNP.zip](https://github.com/dotnet/maui/files/7514348/MauiAppNP.zip)

**Comment by Jens-K-S** [comment]
The exception seems to be thrown only when a new root page is to be displayed.

**Comment by kristinx0211** [comment]
'ArgumentOutOfRangeException' throws on Navigation.PopAsync() when repro this issue by above project on Android 11. same issue as: [https://github.com/xamarin/Xamarin.Forms/issues/10666](url)

**Comment by PureWeen** [comment]
Fixed by
https://github.com/dotnet/maui/pull/5744
