### ISSUE TITLE
[Bug] ListView ObservableCollection ItemsSource not updating properly. CollectionView item selection highlight not selecting

### ISSUE THREAD

**Issue by emceelovin** [dotnet/maui#3342]
### Description
As the title suggests, when working with ListView and an ObservableCollection ItemsSource, the view is not updated properly on windows when items are CRUD'd until you resize the window or trigger a redraw in whatever way.

CollectionView with an ObservableCollection ItemsSource on both Windows and Android works wonderfully. I was hoping this release would fix that issue for both ListView and CollectionView, but wasn't expecting it. Except only CollectionView works properly when bound to an ObservableCollection. I appreciate all of your hardwork so much by the way. this release really enables productivity for me.

CollectionView with a TapGestureRecognizer isn't functioning how id expect. CollectionView might already have its own TapGestureRecognizer? It works when you double tap outside of CollectionView items, but not when you double tap an item itself. Even when the GridLayout and Label's inside the GridLayout are set to InputTransparent="True".

Also, CollectionView item selection HIGHLIGHT on android is not working with SelectionMode="Single". SelectedItem being bound to a property is indeed working, but there is no color highlight indicating the slected item(am i suppose to supply a style?).
### Steps to Reproduce

1. Create a ListView and CollectionView
2. Bind both to an ObservableCollection
3. Set timer or some other aynchronous operation(in my case a backend api subscription populates my ObservableCollection) and add items to the ObservableCollection

### Expected Behavior
Windows: Items appear in the ListView and CollectionView as theyre CRUD'd in the ObservableCollection
Android: Ditto

Windows: CollectionView selected item is highlighted
Android: Ditto

### Actual Behavior
Windows: Items do not appear in ListView. Items appear in CollectionView
Android: Items appear in ListView. Items appear in CollectionView

Windows: CollectionView selected item is highlighted
Android: CollectionView selected item is not highlighted

### Basic Information

- Version with issue: MAUI Preview 10
- Last known good version: None(?)
- IDE: VS2022 17.1 Preview.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by meilleur102** [comment]
do we have a timestamp on when this issue will be fixed? (or any other issues) 
Is there a time stamp that we can see or it's random what is fixed for the next preview? 
Im stuck until this feature work unfortunatly

**Comment by pierre01** [comment]
I have the same Issue, **SelectedItem shows oultlined on Windows but not on Android**
Tested on Maui preview 10 - Windows 11 - Android Emulator, Device and WSA

![image](https://user-images.githubusercontent.com/2603287/145328131-ffc76bf6-5799-4ca1-9910-dbf22b5b8565.png)
