### ISSUE TITLE
[Bug] Platform Extensions are not working on Android

### ISSUE THREAD

**Issue by VladislavAntonyuk** [dotnet/maui#3346]
### Description
https://docs.microsoft.com/en-us/xamarin/essentials/platform-extensions

### Steps to Reproduce

I use it with Microsoft.Identity.Client.PublicClientApplicationBuilder where it is required to set Android activity. when I pass  Microsoft.Maui.Essentials.Platform.CurrentActivity as a parameter, nothing happens.

### Expected Behavior
Browser is opened

### Actual Behavior
nothing happens

### Basic Information

- Version with issue: Preview 10
- Platform Target Frameworks: 
  - Android: 11

### Workaround

override OnCreate with calling Microsoft.Maui.Essentials.Platform.Init(this, savedInstanceState);

**Comment by wenwen60** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by VladislavAntonyuk** [comment]
As I mentioned the issue reproduced only with preview 10 and has been fixed with preview 12
