### ISSUE TITLE
[Enhancement] Device and Page Orientation

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3358]
Hi,

Please add n Orientation command to the device and page-level (even if orientation was disabled by default at the app level).

For example, if my app was set to only show in Portrait mode but for a specific screen I was to show in landscape mode, e.g. for a a wide photo or media play, then I should be able to use:

`Device.Orientation = Landscape
`

or:

`Page.Orientation = Landscape
`

**Comment by jfversluis** [comment]
Please use the feature request template

**Comment by jrahma** [comment]
Thanks @jfversluis 

Original Request is updated now.
