### ISSUE TITLE
[Bug] Editor throws UnhandledExceptionEventArgs on Windows

### ISSUE THREAD

**Issue by emceelovin** [dotnet/maui#3370]
### Description
Editor throws UnhandledExceptionEventArgs as soon as you type one character on Windows, but does not throw an exception on Android. Entry works on both Windows and Android.

### Steps to Reproduce

1. Define an Entry in a StackLayout
2. Build & Deploy on windows
3. Type one character
4. Swap Entry to Editor
5. Type one character

### Expected Behavior
Windows: Accepts input/Accepts input
Android: Accepts input/Accepts input

### Actual Behavior
Windows: Entry functions properly. Editor, UnhandledExceptionEventArgs "Object reference not set to an instance of an object." Assuming this is from bad manually emitted IL where a reference wasn't pushed onto the stack when accessing the field/prop/member function.

Android: Entry functions properly. Editor functions properly(there is a slight bug(?) where, the editor with bottom margin is delayed when respecting that margin with the keyboard open. It takes a few seconds for the editor to move upward after the editor expands with the newline spacing.

### Basic Information

- Version with issue: Preview 10
- Last known good version: Preview 9(?)
- IDE: Visual Studio 2022 17.1 Preview 1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by chaoyebugao** [comment]
Same problem. My workaround is set a `string.Empty` value to Binding Property as default.

**Comment by emceelovin** [comment]
> 

good to know! thanks! have you tried using it on preview 11? i updated a couple days ago, but I haven't tried using entry on android on preview 11.

**Comment by kristinx0211** [comment]
verified on windows 10.0.19041, using editor and entry are no exceptions, but after typing character, it doesn't accepts my input.

**Comment by buyaa-n** [comment]
I could not repro, and just noticed there were closed PR where there is a [comment](https://github.com/dotnet/maui/pull/3392#pullrequestreview-812221232) it should have been fixed, feel free to reopen if any of you can repro
