### ISSUE TITLE
[Enhancement] First class Web support developed by Microsoft

### ISSUE THREAD

**Issue by Suriman** [dotnet/maui#338]
It is essential that MAUI supports the generation of web applications using exclusively XAML and C#.

When I say web applications, I do not mean web pages for portals where design is essential and visual appeal, I mean a LOB (Line Of Business) web application. That is, an application to manage business with the typical data entry and query forms. Nothing else.

When I say 'using XAML and C # only' I mean not using HTML or CSS or Razor (as in the case of Mobile Blazor Binding). This option obliges companies, which have always developed LOB desktop applications, to train our staff in these technologies. To keep two teams separate, one for the front and one for the back, which is inefficient and more difficult to coordinate. I know, I know, you can reuse some of the code, but it is better to reuse 100%.

There are initiatives, led by the community, to fill this gap from practically the beginning of Xamarin.Forms, like Ooui, but let's be honest and sincere, making a web backend in XF or Maui is not a simple and quick task to do it in free time on weekends. This work requires the commitment of a company behind that pays its employees to do this work.

I suspect that Microsoft has a strategic decision problem due to the overlap between Maui and Blazor, assuming, of course, that Maui supports the generation of web applications. If this is so, all of us would greatly appreciate an honest answer and not the typical "it's on our radar" answer. Companies need to know for sure if this is going to be done in the future or not (regardless of the time) to make a decision to continue with XF and Maui or to definitely jump to other options such as UNO Platform.

**Comment by GeraudFabien** [comment]
You already open a discussion #143. and there was already someone who say it's a duplicate #62 . Why do you fill it's okay to open a new issue.
