### ISSUE TITLE
[Bug] [Android] Calling Unfocus on Entry has no effect

### ISSUE THREAD

**Issue by LarsBehl** [dotnet/maui#3380]
### Description
Calling `Unfocus()` on an `Entry` has no effect. The `Entry` will stay focused and the keyboard won't be dismissed.

#### Note
In my opinion, the focus behavior of the `Entry` is weird. Even after navigating to another view of the application, the keyboard won't be dismissed and the `Unfocused` event won't get fired.

### Steps to Reproduce

1. Add an `Entry` to a view
2. Call `Unfocus()` on the `Entry` in the `Completed` handler

### Expected Behavior
The `Entry` loses the focus and the keyboard gets dismissed.

### Actual Behavior
Nothing happens. The `Unfocused` event does not get fired.

### Basic Information

- Version with issue: 6.0.101-preview.10.2068
- Last known good version: -
- IDE: Visual Studio 2022 Version 17.1.0 Preview 1.0
- Platform Target Frameworks: 
  - Android: 28

#### Expected
![image](https://user-images.githubusercontent.com/26459044/141647288-692b60e9-387b-44db-ad77-56ba91de5223.png)

#### Actual
![image](https://user-images.githubusercontent.com/26459044/141655929-1c36dc79-f8b5-4d6e-8603-ee840c209f72.png)

### Reproduction Link
The issue is present [here](https://github.com/LarsBehl/StatusApp/blob/9554fb14bc9aa497eb4697c2f790b4bb87b45c9b/Views/SettingsView.xaml.cs)

### Workaround
Setting `Entry.IsEnabled` to `false` and immediately to `true` again unfocuses the `Entry` and closes the keyboard

**Comment by mas985** [comment]
Any ETA for this?

The Unfocused event doesn't seem to fire.

**Comment by LarsBehl** [comment]
@mas985 as @jsuarezruiz pointed out, focusable logic is not implemented. I think this also includes the `Unfocused` event

**Comment by mas985** [comment]
I understand it is not yet implemented. I was wondering if/when it might be implemented as it was mentioned that it will be available in upcoming previews but that was 24 days ago.

**Comment by danielftz** [comment]
Any ETA for this?

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EQ-83_HprwpFoHd0WoPNJ34BVVEL13YPDdzbC8h1BgKDiw?e=CfEj42

**Comment by Redth** [comment]
Fixed in #4914
