### ISSUE TITLE
[Bug] Default project Maui shows an empty app on macOS

### ISSUE THREAD

**Issue by MaksimAdamenko** [dotnet/maui#3381]
### Description

After creating the Maui application template. It builds under MacOS and opens, but the window is empty.

### Steps to Reproduce

1.  Create default project Maui
2.  Build and run debug

### Expected Behavior

An application with a counter should open

### Actual Behavior

Application launches but nothing is rendered

### Basic Information

- Version with issue: Preview 10
- IDE: Visual Studio 2022 for Mac version 17.0 Preview 3

macOS Big Sur 11.4
processor Intel Core i7

### Screenshots

![unnamed](https://user-images.githubusercontent.com/63460828/141647535-a4f9c58f-c5c2-4416-a873-83614298173f.png)

**Comment by davidbuckleyni** [comment]
Why was this closed with no interaction with customers
