### ISSUE TITLE
[Bug] BlazorWebView Issue if href to external site is clicked - can't return to app

### ISSUE THREAD

**Issue by ElliottBrand** [dotnet/maui#3385]
While working with a MAUI Blazor Android app in Android Emulator, I discovered that if any text in the app contains a link to an external site and that link is clicked, the external site loads in the web view of the app and there's no way to return to the app itself.  Should there be some method that detects if the Url doesn't match some set list of Urls (i.e. localhost for the device, login url, etc...) then maybe add a panel to the web view with a back/return button?

**Comment by Seanxwy** [comment]
Have the same needs

**Comment by ElliottBrand** [comment]
@Eilon have you had any time to look into this? Would we be able to override ShouldOverrideUrlLoading ([https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs)) and do something like

```csharp
...
if (uri.Host == "0.0.0.0")
{
    view.LoadUrl(uri.ToString());
    return true;
}
else
{
    // Do some magic here to open the url in browser
}
...
```

And do something similar for iOS ([https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs)). iOS currently just crashes if an external link is clicked, whereas Android loads it in the webview (as mentioned initially).

Some related conversation occurred in #3474

**Comment by Eilon** [comment]
Sorry I haven't had a chance to look at this yet.

**Comment by ElliottBrand** [comment]
I've created a workaround for this that seems to work fine, so I'll go ahead and post the general methods I've used in case anyone else needs finds this thread and needs a workaround. Although, I'm generating the anchor tag html around the content links, so that helps make this easier.

I'm passing in an 'isNativeApp' parameter to the method that builds my anchor tag. Anyone building a MAUI Blazor app probably needs to pass this down as a cascading parameter anyway, since it'll come in handy throughout the app. Then when I call this method from my Blazor component, I just pass the boolean with it.
```csharp
public static string AddWebLinks(string contentText, bool isNativeApp)
{
    // Use regex to pull links out of content
    Regex regex = new Regex(@"(?:(?:https?):\/\/)?[\w/\.-]+(?<!\.)(\.)(?!\.)[a-zA-Z]+(?<!\?)[a-zA-Z0-9/\-&?=%#_]+");
    contentText = regex.Replace(contentText, delegate (Match m) {

        // This is just a custom method that adds http:// to any link in the content that doesn't start http
        var fullLink = Shared.Helpers.UriHelpers.Formatting.AddHttpIfMissing(m.Value);

        // Add JavaScript onclick attribute if it is a native app, so link can open in a new browser
        // instead of the webview.
        var onClickVal = isNativeApp ? $"onclick=\"window.mauiBrowserTab.openUrl('{ fullLink }');\"" : string.Empty;

        // Only add link attributes if it's not a native app
        var htmlLink = !isNativeApp ? $"target=\"_blank\" href=\"{ fullLink }\"" : string.Empty;
        return $"<a { onClickVal } { htmlLink }>{ m.Value }</a>"; 
    });
    return contentText;
}
```

I created a simple JavaScript file for the MAUI Blazor app, which needs to be referenced in the MAUI Blazor index.html file, and this is the function. This invokes a JSInvokableAttribute in the Main.razor file within the MAUI Blazor project.
```javascript
window.mauiBrowserTab = {
    openUrl: function (url) {
        // Replace 'MyProject.MauiBlazorApp' with the correct namespace for your MAUI Blazor project
        DotNet.invokeMethodAsync('MyProject.MauiBlazorApp', 'OpenWebLinkInNewBrowser', url);
    }
}
```

In Main.razor, add the following method. You'll also need to add a using directive to the top of the file for Microsoft.Maui.Essentials
```csharp
    [JSInvokableAttribute("OpenWebLinkInNewBrowser")]
    public static async void OpenWebLinkWithMauiEssentials(string url)
    {
        await Browser.OpenAsync(url, new BrowserLaunchOptions
        {
            LaunchMode = BrowserLaunchMode.SystemPreferred,
            TitleMode = BrowserTitleMode.Show,
            PreferredToolbarColor = Microsoft.Maui.Graphics.Color.FromArgb("#2381B8")
        });
    }
```

With this, the Blazor WebAssembly app (isNativeApp would be false) will create the link normally, but the native app will just not load the href and target attributes at all. Instead, it adds the onclick event to fire the JavaScript function, which invokes a C# method that loads the link via MAUI Essentials in a new browser window.

NOTE: I haven't tested this in a WinUI project, but you could just set the isNativeApp to false for WinUI and I believe it should open in a browser fine.

**Comment by TanayParikh** [comment]
Cross-linking @ElliottBrand's comment: https://github.com/dotnet/maui/issues/3474#issuecomment-976214176

@Eilon should this be closed out as by design in that case?

**Comment by Eilon** [comment]
@TanayParikh how would this be by design?

**Comment by Seanxwy** [comment]
How to design in the Maui Blazor project @TanayParikh

**Comment by TanayParikh** [comment]
> @TanayParikh how would this be by design?

Based on @ElliottBrand's comment, it appeared this may've been how Xamarin has worked for a while, so it became the expected behavior / by design. 

> was something I thought was an issue, but after more research, I believe it's just how Xamarin has worked for a while. Coming from web development, I just expected it to work, but it now looks like Xamarin developers must have been adding a method to catch all link clicks (like in AppDelegate.cs or something) and handle them at that point...I haven't figured out how to get it working yet. The link click wasn't throwing an error in Android, it just takes over the webview and you're stuck there.

Ie, by changing this behavior now, we _may_ create a breaking change, or do something contrary to what a developer may have anticipated based on (legacy?) behavior.


> How to design in the Maui Blazor project @TanayParikh

I'm not sure I follow, could you please clarify @Seanxwy.

**Comment by ElliottBrand** [comment]
My comment was more about the way a Xamarin developer may have expected it in the past. I believe Blazor developers may expect a simpler approach, since their native app may be using the same code their website is using. Eilon had a few ideas about how to implement it and make it easy to implement, but I created a workaround with JavaScript for now.

**Comment by ElliottBrand** [comment]
And this particular issue was that the user is trapped after clicking the link. My comment was in relation the link clicks on iOS I believe.

**Comment by Eilon** [comment]
@TanayParikh this can't be a breaking change or any expectation because BlazorWebView is brand new 😄

**Comment by TanayParikh** [comment]
> the user is trapped after clicking the link on an Android device

Hey @ElliottBrand, I just tried this out and I'm not able to repro being 'trapped'. 

I added `<a href="https://microsoft.com">Open (no target) link</a>` within the WebView. Once an external site link is clicked within the webview, the `back` button returns the user to the home screen of the app. I've put together https://github.com/dotnet/maui/pull/4364 which ensures the WebView navigation stack is respected (back button first goes through the webview navigation stack / history before returning to the app home screen).

Please let me know if this doesn't solve your original issue.

**Comment by ElliottBrand** [comment]
Hi @TanayParikh , I've since implemented some custom JavaScript (mentioned above) to open the links in new browser windows, so I haven't ran into it again, but what I was experiencing in the Android emulator at the time was the link seemed to open in the same webview window and clicking the back arrow didn't return to the app. It's been a few months, so if you aren't able to reproduce it, perhaps it has been corrected, or maybe it was a bug in the emulator. I would test it on a new project right now, but I'm performing a Visual Studio Preview re-install to see if it cleans up some issues. At the time, I was using a different emulator than I have been lately...I think it was the Google emulator (that looks like an actual phone, with casing and everything).

If you can't reproduce it, it may be okay to close this one.

**Comment by ElliottBrand** [comment]
Also, I noticed you implemented the ability to automatically open iOS links in a new window when the <a> tag had a _blank target. I think that'll be helpful to a lot of Blazor developers!
