### ISSUE TITLE
Use Microsoft Edge HTML/CSS renderer as self-contained in Blazor MAUI apps

### ISSUE THREAD

**Issue by ahra04** [dotnet/maui#3390]
Use Microsoft Edge HTML/CSS renderer as lightweight self-contained in Blazor MAUI apps and other .NET app development workloads for Windows, MacOS, iOS, Android, WearOS, iPadOS etc.,

**Comment by Eilon** [comment]
Hi @ahra04 , we already use the Edge WebView2 control for .NET MAUI + Blazor apps. There is no control available outside of Windows right now, so we use each platform's native controls (many platforms don't even allow other controls, so using Edge isn't an option on iOS, for example).

If this question is asking for something else, please let us know.

**Comment by ahra04** [comment]
@Eilon Consider using SkiaSharp for painting HTML/CSS UI onto the screen.
