### ISSUE TITLE
MAUI + Azure Communication Services

### ISSUE THREAD

**Issue by aodegov** [dotnet/maui#3393]
## Summary
MAUI AND AZURE COMMUNICATION SERVICES INTEROPERABILITY

## REQUEST. MAUI / Xamarin NuGet package (or embedded into MAUI mobile dll) for Azure Communication Services (ACS)

Request to have a chance to work with Azure Communication Services from MAUI / Xamarin mobile app through the appropriate NuGet package.
Also we'd like to ask about Azure Communication Services documentation update with samples "How To" use this with Xamarin / MAUI

## Intended Use Case
Would be great to have an opportunity to work with Azure Communication Services (ACS) right from MAUI / Xamarin mobile app.
This option allows many developers build connections with ACS in order to provide users the video, audio calls, chats etc.
It will be a really killer feature from MS, since a lot of devs/companies strive to have this option for apps on Xamarin / MAUI

___  
12.10.2021 update:   
[this one related issue](https://github.com/Azure/Communication/issues/426) was closed with no any understanding how will it be processed.

__
Thanks

**Comment by jfversluis** [comment]
This is now open on the Azure Feedback portal: https://feedback.azure.com/d365community/idea/4c3c83f6-8948-ec11-a819-0022484bf651

Getting upvotes there will help prioritize this feature for the Azure team. Thanks!

**Comment by aodegov** [comment]
@jfversluis thanks for promoting my post [there](https://feedback.azure.com/d365community/idea/4c3c83f6-8948-ec11-a819-0022484bf651). 
We'd be thankful to see your and your colleagues votes there.
Thank you.
