### ISSUE TITLE
WebRTC + MAUI

### ISSUE THREAD

**Issue by aodegov** [dotnet/maui#3394]
## Summary
MAUI AND WebRTC  INTEROPERABILITY

## REQUEST. WebRTC NuGet package for MAUI (or embedded into MAUI dll) 

Request to have a NuGet package / or embedded dll (to use this through the namespace),
 to work with WebRTC  from MAUI / Xamarin mobile app.

## Intended Use Case
Would be great to have an opportunity to work with WebRTC  right from MAUI / Xamarin mobile app.
This option allows many developers build connections with WebRTC in order to provide users the video, audio calls, chats etc.

__
Thanks

**Comment by AmSmart** [comment]
Isn't this already possible? There are native bindings for Google's WebRTC libraries for Android and iOS. With MAUI Blazor, you can also achieve this fairly easily with JS interop.

**Comment by aodegov** [comment]
@AmSmart , please read carefully this issue description.
This is not about numerous of workarounds about "How to" use WebRTC through the JS calls inside the Xamarin / MAUI mobile app, and this is also not about calls of the native apps code written either on Java (for Android) or on Objective-C (iOS) from the C# mobile app code (Xamarin / MAUI).
But this issue is about creation appropriate NuGet package (or embedded functionality) into Xamarin / MAUI mobile solutions in order to allow developers work with such stuff like WebRTC and also [ACS](https://docs.microsoft.com/en-us/azure/communication-services/)  (which is using the WebRTC under the hood) right from the box, means right from cross platform mobile app (Xamarin / MAUI)
With no additional workarounds in order to figure out how to call this Java method or that Objective-C, or JS one.
And since people have a bunch of issues and questions related to this, so that's why this issue was created.

Also, please note that this issue is about mobile apps, not web apps like Blazor.

Thanks.

**Comment by AmSmart** [comment]
I see... this is a request for an OOTB WebRTC implementation. It is definitely a great addition, might not be worth the effort at the moment though🤷🏽‍♂️. I'll leave it to those who know better than myself to weigh in on the issue.

**Comment by VisualByteStudios** [comment]
Perhaps something similar to [WinRTC](https://docs.microsoft.com/en-us/winrtc/)?

**Comment by Eagle3386** [comment]
@VisualByteStudios Do you mind helping a Padawan regarding WinRTC on how to integrate it into a .NET MAUI app?

Just the first couple of steps, no full implementation, would be sufficient, I guess.
It's just that I don't really get how to start integrating WinRTC into my .NET MAUI app.. 🙈

**Comment by Eagle3386** [comment]
@VisualByteStudios WinRTC is obviously dead (see microsoft/winrtc#134 & neither any commit since April 2021 nor actual roadmap - "Coming soon" is the latest info on that).

So, what alternatives do we have to implement WebRTC in a MAUI app?

**Comment by aodegov** [comment]
@Eagle3386 as an attempt I created this issue: https://github.com/dotnet/maui/issues/3393
which was closed by @jfversluis without any reasons and progress from MS side on this issue.

**Comment by jfversluis** [comment]
I'm sorry if the reason wasn't clear to you. In my opinion this is what is going on: yes, this would be amazing to have. In fact, I'd love to have this. However, we (.NET MAUI) are "just" a UI framework. We can't do everything ourselves and we shouldn't. I feel that features like these are too far outside of the scope of what we are doing with this framework.

WebRTC (and also the related Azure services you are talking about) add a lot of complexity. And most of the functionality isn't even visible. .NET MAUI as it is, is complex enough and we already have enough work on our plate with the features that I think are much more in scope.

I feel that functionality like this is perfect for a third-party library and ideally something that is provided by the team that is actually working on the services like WebRTC or in our case the Azure services related to that.

In light of all this, I am actually also going to close this one for now. Even if this were something that we would eventually incorporate in our framework directly, which I doubt, it won't be in the foreseeable future. Thanks!

**Comment by sipsorcery** [comment]
It's sad to see the winrtc project die before it even got to v0.1. I thought WebRTC, and realtime comms in general, might finally get some love from Microsoft now that there's a potential direct revenue angle with Azure Communication Services. Not to be I guess. Maybe in another couple of decades :).

For other readers the two projects I know of are:

 - https://github.com/sipsorcery-org/sipsorcery: this is the one I work on but the BIG problem is audio/video device access and video codecs. The WebRTC stuff is in a reasonable state up until the point devices or video codecs are needed. At that point it descends into a quagmire of native libraries. unsupported APIs on different dotnet versions etc.

- https://github.com/Unity-Technologies/com.unity.webrtc: It's Unity specific and wraps libwebrtc but may be an option for people previously using the [MixedReality-WebRTC](https://github.com/microsoft/MixedReality-WebRTC) library.

**Comment by aodegov** [comment]
True, this is really sad. 
Since mobile phones created in order to let people communicate with each other,
and suddenly, Xamarin and newest MAUI frameworks doesn't contain communication options to have video / voice calls
right from own apps.
This is definitely odd, softly speaking.
