### ISSUE TITLE
[Bug] Dynamic time allotted size not reflect in maui view

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#3397]
### Description

Hi Team,

I have set size for image and grid in dynamic time, but the size not reflect in view. 

I have checked the HeightRequest and WidthRequest properties, set values are reflect in these properties, but not in view. 

I have faced this issue in Maui Preview 9 -> Please confirm the issue resolved in Maui Preview 10 or not. 

**This issue not reproduced in Maui-WinUI. Reproduced only in android and iOS.**

### Steps to Reproduce

```

<Image Source="sun.png" HeightRequest="25" WidthRequest="25"/>


```
```

          private void Button_Clicked149(object sender, EventArgs e)
        {
            image1.HeightRequest = 35;
            image1.WidthRequest = 35;
        }
```
### Expected Behavior

Dynamic time set size should be reflect in view

### Actual Behavior

Dynamic time set size not reflect in view

### Basic Information

Maui Preview 9

**Comment by kristinx0211** [comment]
not repro this issue, the size is reflect when click the button.
code snippet:
![image](https://user-images.githubusercontent.com/99457000/157386321-90d75af6-3459-4153-9d2b-0dbe3560c76a.png)
![image](https://user-images.githubusercontent.com/99457000/157386136-1177f29f-ca46-488f-a372-54306f07fa04.png)

https://user-images.githubusercontent.com/99457000/157386177-2ccdd593-651e-4f2c-9c2f-ac4c45772f9c.mp4

**Comment by mattleibow** [comment]
This should be fixed in Preview 14. Please open another issue if there are still problems.
