### ISSUE TITLE
[Android] Origin not working for maui view transform (Scale, Rotation)

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#3398]
## Summary

I have used maui view's transform APIs -> ScaleX, ScaleY, Rotation. But the transform happens from (0,0) position. 

Can we have a option to change the origin point of these transforms. Like **RenderTransformOrigin**  in **WinUI**

Currently I am using Maui Preview 9, please let me know this option available in Maui Preview 10 or any of upcoming. 

## Intended Use Case

If you have provided the origin customization option for transform means, no need to reposition the view based on transform.

**Comment by hartez** [comment]
Have you tried setting the AnchorX and AnchorY properties of the view before applying the scale and rotation?
Those properties should allow you to set the origin point of the transforms. The properties are proportional from 0 to 1. So `AnchorX = 0.5; AnchorY = 0.5;` would be the center of the view; `AnchorX = 0; AnchorY = 0;` would be the top left corner of the view.

**Comment by MuneeshKumarG** [comment]
AnchorX and AnchorY properties default values are 0.5. So when we update scale and rotation, view doesn't render from center of view.

**Comment by MuneeshKumarG** [comment]
I have tested the scale and rotation transformation in Maui-Windows. It renders the transformation from center position by default. 

Android and iOS have this position change issue.

**Comment by Keboo** [comment]
Also bumped into this on Android as well. 

Sample XAML. The intent is to make 4 navigation arrows for up/down/left/right.

```xaml
<Grid HorizontalOptions="Center" VerticalOptions="Center" >
  <Grid.RowDefinitions>
    <RowDefinition Height="80" />
    <RowDefinition Height="80" />
    <RowDefinition Height="80" />
  </Grid.RowDefinitions>
  <Grid.ColumnDefinitions>
    <ColumnDefinition Width="80" />
    <ColumnDefinition Width="80" />
    <ColumnDefinition Width="80" />
  </Grid.ColumnDefinitions>

  <Button ImageSource="arrow.svg" GridLayout.Column="1" GridLayout.Row="0" />
  <Button ImageSource="arrow.svg" GridLayout.Column="2" GridLayout.Row="1" Rotation="90" />
  <Button ImageSource="arrow.svg" GridLayout.Column="1" GridLayout.Row="2" Rotation="180"/>
  <Button ImageSource="arrow.svg" GridLayout.Column="0" GridLayout.Row="1" Rotation="270"/>

</Grid>
```

Output looks like this:
![image](https://user-images.githubusercontent.com/952248/144374232-a646bea8-7330-49eb-83cf-6fda6c450843.png)

The desired output would be this (with the arrows properly rotated)
![image](https://user-images.githubusercontent.com/952248/144374296-52640aec-23db-4d6c-b455-be9a7991b2b7.png)

**Comment by MuneeshKumarG** [comment]
Currently I am using the work around for this problem in android. 

By setting AnchorX and AnchorY as 0.49, we can achieve the center transform. We have to set these values in dynamic time, load time it doesn't work.

**Comment by Redth** [comment]
![image](https://user-images.githubusercontent.com/271950/154725186-41b5e76b-3530-47d1-9a42-571bcf044767.png)
Appears to be fixed at least as of current main.

I don't have the arrow.svg but it's laying out as seems to be expected.

Closing, please open a new issue if necessary :)

**Comment by Keboo** [comment]
@Redth that screenshot appears to be running under a Window's head. As the title of this issue indicates the issue appears to be Android specific.

**Comment by Redth** [comment]
@Keboo  yeah sorry it’s deceiving but that screenshot is running on the android subsystem for windows.
