### ISSUE TITLE
[Bug] Windows desktop application only runs in Visual Studio

### ISSUE THREAD

**Issue by jlouw2** [dotnet/maui#3402]
### Description
Windows desktop application only runs in Visual Studio

### Steps to Reproduce
1. Create .NET Maui app, build and run in Visual Studio
2. Go to the bin\Release\net6.0-windows10.0.19041 folder and launch the .exe
3. Same results with Debug build

### Expected Behavior
App window should appear

### Actual Behavior
No app window appears. Task Manager shows that the process starts and immediately terminates.

### Basic Information
- Version with issue: .NET MAUI Preview 10
- Last known good version: not known
- IDE: Visual Studio 17.1
- Platform Target Frameworks: Windows Desktop
- Nuget Packages: 
  - Microsoft.Maui.Graphics 6.0.101-preview.10.640
  - Microsoft.Maui.Graphics.Win2D.WinUI.Desktop 6.0.101-preview.10.640
- Affected Devices: Windows 10 version 21H1

**Comment by HeroinGyrl** [comment]
this problem was already mention and already added to Triage then it got moved to ready to work.

still not fixed?

https://github.com/dotnet/maui/issues/2583

**Comment by dhindrik** [comment]
In the latest preview OutputType is set to Library in csproj instead of Exe. I had to change to Exe to run the project. I am using VS4Mac on Macbook Pro M1.

Not working:
`<OutputType>Library</OutputType>`

Working:
`<OutputType>Exe</OutputType>`

**Comment by shimingsg** [comment]
Verified Repro with Windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EfHSvETgTR1JjPDSyHGAMgwBr2nG_AZytoQOdU64rNJDVA?e=URvISw

**Comment by jfversluis** [comment]
Probably related to things in #4329 in regard to the missing Microsoft.ui.xaml.dll and what Matthew has been doing in #3166

**Comment by gcadmes-extron** [comment]
VS 2022 17.2 Preview 3.0, not fixed.
