### ISSUE TITLE
We can no longer be complacent like Ballmer's period. A truly powerful company does not rely on monopoly, but on technological innovation. Therefore, we suggest that it is very necessary to support Linux

### ISSUE THREAD

**Issue by 564064202** [dotnet/maui#3404]
We can no longer be complacent like Ballmer's period. A truly powerful company does not rely on monopoly, but on technological innovation. Therefore, we suggest that it is very necessary to support Linux

**Comment by hartez** [comment]
We have an open discussion on this topic: https://github.com/dotnet/maui/discussions/339

**Comment by Mesum-Hussain** [comment]
> We have an open discussion on this topic: https://github.com/dotnet/maui/discussions/339

I just hope that this discussion #339 conclude with a positive result soon. Not supporting Linux is bad press for MAUI for the least and is simply going to tarnish it's reputation when compared to to other frameworks.
