### ISSUE TITLE
We can no longer be complacent like Ballmer's period. A truly powerful company does not rely on monopoly, but on technological innovation. Therefore, we suggest that it is very necessary to support Linux

### ISSUE THREAD

**Issue by Szymon2601** [dotnet/maui#3408]
We can no longer be complacent like Ballmer's period. A truly powerful company does not rely on monopoly, but on technological innovation. Therefore, we suggest that it is very necessary to support Linux

__Originally posted by @564064202 in https://github.com/dotnet/[maui](https://github.com/Szymon2601/d63de202088f03d560055892c5e25865665dc8907da68924e86074831/impo](https://github.com/Szymon2601/@d63de202088f03d560055892c5e25865665dc8907da68924e86074831/import)issues/3404__

**Comment by jsuarezruiz** [comment]
Duplicated #3404
