### ISSUE TITLE
[Spec]  Remove padding/spacing defaults

### ISSUE THREAD

**Issue by CarnageMarkus** [dotnet/maui#341]
# Remove layout defaults

Number of Xamarin.Forms layouts and views contain very specific set of default values.

- Grid has default row and column spacing of 6
- Stacklayout has spacing of 6
- Frame has default padding of 20

I think it is very counterintuitive to look at layout, done exactly by spec (not matching obviously), just to realize I forgot to revert spacing / padding defaults.
Anytime I use one of those layouts, I just copy paste snipped to set those properties to 0.

# Backward Compatibility

This is breaking change, but on every project I worked, those values are overridden anyway.
So the impact is rather questionable.

I mean, what are the odds that anybody's design doc had spacing somewhere exactly 6, and they went: "Great! That's the default value, so I don't have to specify that!"

We could add flag to "bring them back" for projects being ported. And recommend turning it on when porting their project.

# Difficulty : [low/medium/high]

low.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/discussions/39
