### ISSUE TITLE
VS17.1prv1 - WeatherTwentyOne app error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3414]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS171prv1---WeatherTwentyOne-app-error/1582760)._

---
not sure what this means but repro steps are
download most recent version of WeatherTwentyOne maui app
unzip and let it load completely - no errors
Run Android API31 emulator
throws this error when deployed

-------------
System.UnauthorizedAccessException
  Message=Access to the path '/data/fonts' is denied.

---
#### Thomas Giebink on 11/13/2021, 09:53 AM: 

<p>it builds OK</p>

#### Thomas Giebink on 11/13/2021, 09:55 AM: 

<p>after a build that works… try to deploy to API31 Android… fails during “hot reload init”</p>

#### Thomas Giebink on 11/13/2021, 10:02 AM: 

<p>switched to Windows Machine… build OK<br>
Run fail<br>
<img src="https://aka.ms/dc/image?name=Bad4edd2c9aeb4536a6ae1c01639ec2bd637724231401583864_WeatherFail.jpg&amp;tid=ad4edd2c9aeb4536a6ae1c01639ec2bd637724231401583864" alt="WeatherFail.jpg"></p>
<p>video recording shows the intellisense message</p>

#### Feedback Bot on 11/14/2021, 11:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Older issue, I hope this is resolved by now. If there is still an issue here, please let us know!
