### ISSUE TITLE
Xamarin Maui DisplayAlert does not appear (no message display pop-up) when using NavigationPage

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3415]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-Maui-DisplayAlert-does-not-appea/1580887)._

---
Steps to reproduce:

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.1.0 Preview 1.0
 6.0.100-rc.2.21505.57 - C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57

1) Create a new Xamarin Maui default project using the above dev environment.
2) Go to App.Xaml.cs and change the startup/rootpage from
//MainPage = new MainPage(); to
MainPage = new NavigationPage(new MainPage());
3) In the main page code behind add to OnCounterClicked;
private void OnCounterClicked(object sender, EventArgs e)
{
    App.Current.MainPage.DisplayAlert("Alert", "Display Alert Message.", "Okay");
}
3) Select project framework to compile to Android.
4) Compile and deploy the app to the emulator. (Android 11 API 30 or 12 API 31)
5) Click on the "Click Me" button to test.

Expected behavior:
1) A message box pop-up should appear as in Xamarin Forms.

---
#### Feedback Bot on 11/11/2021, 11:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by paaltuv** [comment]
Can confirm this, as described above. No alert popup, no crash and no output.

**Comment by VitalsTheCynical** [comment]
Tried using a DisplayAlert on a TabbedPage and it worked great.

**Comment by Brutiquzz** [comment]
Can also confirm this as described above. Nothing happens for NavigationPage but for a regular page it works fine.

**Comment by Amir-Care** [comment]
Not repro on  VS Version 17.2.0 Preview 2.0 [32219.17.main]
Creat a .NET MAUI App and add above code , Click the "Click me" button, the alert popup.
![image](https://user-images.githubusercontent.com/99456025/155636611-743904a1-f359-495d-a16f-a073c4c81832.png)
