### ISSUE TITLE
VS2022 17.0.1 P1  Can't build MAUI sample project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3416]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-1701-P1--Cant-build-MAUI-sampl/1580818)._

---
[severity:I'm unable to use this version]
Hello! I have started testing VS2022 community edition when it was available for download. I have installed it alongside VS2019 which I use daily. 

When 17.0.1 was released I have upgraded VS2022 and installed MAUI using Visual Studio installer. 

What I have done after that:
1. File -> New Project -> .NET MAUI App (all of those fancy windows to accept license for android emulator was shown to me)
2. I have tried to run it, but I get errors which you can see on screenshot attached.

What I have tried:
1. To remove and add again .NET MAUI workload using Visual Studio installer
2. I have tried to repair VS2022 with Visual Studio installer
3. Complete uninstall of VS22 and install again

All steps above didn't help, same errors each time..

In case you need, I have made screenshot of VS2019 installed workloads..

---
#### Feedback Bot on 11/11/2021, 11:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by KirillPom** [comment]
Same here. 
![image](https://user-images.githubusercontent.com/65759581/146939844-00db72e3-b2fd-4f42-9213-b34c52b88844.png)

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
