### ISSUE TITLE
VS17.1Prv1: MAUI fails default project build even after updating manually via maui-check & template update

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3419]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS171Prv1:-MAUI-fails-default-project-b/1577206)._

---
[regression]
I tried a few things to try to get the default MAUI solution to be created without error and nothing worked

1- create default Maui project after updating VS2022 Prv7 to VS17.1prv1
2- throws error during creation (reported previously)
3- CMD:  
! [image.png] (https://aka.ms/dc/image?name=Bd20885d59e7d460c970bf3b998c373c2637720954824248078_20211109-155813-image.png&tid=d20885d59e7d460c970bf3b998c373c2637720954824248078)
4- this surprised me because I thought the VS update would have done this
5- create a MAUI solution and BUT the template is an old one... and throws all sorts of errors
6- CMD (update the Maui templates manually): 
! [image.png] (https://aka.ms/dc/image?name=B8f7c6edee82e41cd933b00983dc9122b637720956193161223_20211109-160029-image.png&tid=8f7c6edee82e41cd933b00983dc9122b637720956193161223)
7- create a default MAUI project... fails to build with errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	XA5301	Failed to generate Java type for class: AndroidX.Core.View.Accessibility.AccessibilityManagerCompat/ITouchExplorationStateChangeListenerImplementor due to MAX_PATH: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\giebi\Source\Repos\VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD\VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD\obj\Debug\net6.0-android\android\src\mono\androidx\core\view\accessibility\AccessibilityManagerCompat_ TouchExplorationStateChangeListenerImplementor.java'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream.. ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.Android.Build.Tasks.Files.CopyIfStreamChanged(Stream stream, String destination) in /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 170
   at Xamarin.Android.Tasks.GenerateJavaStubs.CreateJavaSources(IEnumerable`1 javaTypes, TypeDefinitionCache cache)	VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD	c:\program files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.10.59\tools\Xamarin.Android.Common.targets	1423	
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD (net6.0-ios), VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD (net6.0-maccatalyst), VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD (net6.0-windows10.0.19041)	C:\Users\giebi\Source\Repos\VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD\VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD\MainPage.xaml.cs	13	Active
Error	CS0103	The name 'CounterLabel' does not exist in the current context	VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD (net6.0-ios), VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD (net6.0-maccatalyst), VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD (net6.0-windows10.0.19041)	C:\Users\giebi\Source\Repos\VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD\VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD\MainPage.xaml.cs	19	Active
Error	CS0103	The name 'CounterLabel' does not exist in the current context	VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD (net6.0-ios), VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD (net6.0-maccatalyst), VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD (net6.0-windows10.0.19041)	C:\Users\giebi\Source\Repos\VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD\VS17-1_prv1_aftMauiCheck_tmplUpdate_CMD\MainPage.xaml.cs	21	Active

---
#### Feedback Bot on 11/9/2021, 11:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
This is quite old by now. Going to assume this is better for newer previews. If not, please let us know!
