### ISSUE TITLE
VS17.1Prv1: Maui default solution loads of errors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3421]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS171Prv1:-Maui-default-solution-loads-/1576714)._

---
[regression] [worked-in:17.1 prv1]
On my main development machine.  The last version had Android API30 and Windows Machine build/run/deploy working.  Just updated to VS17.1 Prv1 and now that's all broken
1- Update
2- new default Maui solution
3- throws a bunch of errors when it is created

errors shown (also see image)

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst	VS17-2prv1_01	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\VS17-2prv1_01.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst	VS17-2prv1_01	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\VS17-2prv1_01.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst	VS17-2prv1_01	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\VS17-2prv1_01.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst	VS17-2prv1_01	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\VS17-2prv1_01.csproj	1	
Error	NETSDK1139	The target platform identifier android was not recognized.	VS17-2prv1_01	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	112	
Error	NETSDK1139	The target platform identifier ios was not recognized.	VS17-2prv1_01	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	112	
Error	NETSDK1139	The target platform identifier maccatalyst was not recognized.	VS17-2prv1_01	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	112	
Error	CS0234	The type or namespace name 'Maui' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	VS17-2prv1_01 (net6.0-windows10.0.19041)	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\MainPage.xaml.cs	2	Active
Error	CS0234	The type or namespace name 'Maui' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	VS17-2prv1_01 (net6.0-windows10.0.19041)	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\MainPage.xaml.cs	3	Active
Error	CS0246	The type or namespace name 'ContentPage' could not be found (are you missing a using directive or an assembly reference?)	VS17-2prv1_01 (net6.0-windows10.0.19041)	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\MainPage.xaml.cs	7	Active
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	VS17-2prv1_01 (net6.0-windows10.0.19041)	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\MainPage.xaml.cs	13	Active
Error	CS0103	The name 'CounterLabel' does not exist in the current context	VS17-2prv1_01 (net6.0-windows10.0.19041)	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\MainPage.xaml.cs	19	Active
Error	CS0103	The name 'SemanticScreenReader' does not exist in the current context	VS17-2prv1_01 (net6.0-windows10.0.19041)	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\MainPage.xaml.cs	21	Active
Error	CS0103	The name 'CounterLabel' does not exist in the current context	VS17-2prv1_01 (net6.0-windows10.0.19041)	C:\Users\giebi\source\repos\VS17-2prv1_01\VS17-2prv1_01\MainPage.xaml.cs	21	Active

---
#### Thomas Giebink on 11/9/2021, 07:58 AM: 

<p>Did a REPAIR of the VS installation<br>
*reboot<br>
1-open VS no code<br>
2- create default maui… same errors shown<br>
3- ran maui-check and says I need to update .NET SDK to 6.0.100<br>
4- now doing that… will report results in a following comment</p>

#### Thomas Giebink on 11/9/2021, 08:10 AM: 

<p>well… this is really screwed up.  All I did was UPDATE my VS2022 installation as described … and now NOTHING works for MAUI.  Please advise.<br>
I could uninstall / reinstall VS2022 but I REALLY don’t want to SPIN MY WHEELS on this…</p>
<h2>I ran maui-check and that throws an error that it can’t fix:</h2>
<p>Microsoft Windows [Version 10.0.19043.1320]<br>
© Microsoft Corporation. All rights reserved.</p>
<p>C:\WINDOWS\system32&gt;maui-check’<br>
‘maui-check’’ is not recognized as an internal or external command,<br>
operable program or batch file.</p>
<p>C:\WINDOWS\system32&gt;maui-check<br>
_   _   _____   _____     __  __      _      _   _   ___<br>
| \ | | | <em><em><em><em>| |</em>   <em>|   |  /  |    / \    | | | | |</em> <em>|<br>
|  | | |  <em>|     | |     | |/| |   / _ \   | | | |  | |<br>
_  | |\  | | |</em></em></em>    | |     | |  | |  / ___ \  | |</em>| |  | |<br>
(</em>) |<em>| _| |_____|   |</em>|     |<em>|  |</em>| /<em>/   _\  _<strong>/  |</strong></em>|</p>
<p>☼ .NET MAUI Check v0.9.0.0 ☼<br>
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────This tool will attempt to evaluate your .NET MAUI development environment.<br>
If problems are detected, this tool may offer the option to try and fix them for you, or suggest a way to fix them<br>
yourself.</p>
<p>Thanks for choosing .NET MAUI!<br>
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────» Synchronizing configuration… ok<br>
» Scheduling appointments… ok</p>
<blockquote>
<p>OpenJDK 11.0 Checkup…</p>
</blockquote>
<ul>
<li>11.0.12 (C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin…)</li>
<li>1.8.0-25 (C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25)</li>
<li>11.0.12 (c:\program files\microsoft\jdk-11.0.12.7-hotspot\bin…)</li>
</ul>
<blockquote>
<p>Visual Studio 17.1.0-pre.1.0 Checkup…</p>
</blockquote>
<ul>
<li>17.1.0-pre.1.0 - C:\Program Files\Microsoft Visual Studio\2022\Preview</li>
<li>16.11.5</li>
</ul>
<blockquote>
<p>Android SDK Checkup…</p>
</blockquote>
<ul>
<li>emulator (30.8.4)</li>
<li>build-tools;31.0.0 (31.0.0)</li>
<li>platforms;android-31 (1)</li>
<li>system-images;android-31;google_apis;x86_64 (8)</li>
<li>platform-tools (31.0.3)</li>
<li>cmdline-tools;5.0 (5.0)</li>
</ul>
<blockquote>
<p>Android Emulator Checkup…</p>
</blockquote>
<ul>
<li>Emulator: pixel_5_r_11_0_-_api_30 found.</li>
</ul>
<blockquote>
<p>.NET SDK Checkup…</p>
</blockquote>
<p>─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────☼ Recommendation: Download .NET SDK (6.0.100)<br>
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<br>
! Attempt to fix? [y/n] (y): y<br>
» Attempting to fix: .NET SDK<br>
Downloading .NET SDK 6.0.100…<br>
Downloading… 10%…<br>
Downloading… 20%…<br>
Downloading… 30%…<br>
Downloading… 40%…<br>
Downloading… 50%…<br>
Downloading… 60%…<br>
Downloading… 70%…<br>
Downloading… 80%…<br>
Downloading… 90%…<br>
Downloading… 100%…<br>
Downloaded .NET SDK 6.0.100.<br>
Installing .NET SDK 6.0.100…<br>
Installed .NET SDK 6.0.100.<br>
Fix applied.  Checking again…</p>
<blockquote>
<p>.NET SDK Checkup…</p>
</blockquote>
<p>──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────☼ Recommendation: Download .NET SDK (6.0.100)<br>
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<br>
! Attempt to fix? [y/n] (y): y</p>
<p>x Skipped: .NET SDK - Workload Deduplication</p>
<blockquote>
<p>Edge WebView2 Checkup…</p>
</blockquote>
<ul>
<li>Found Edge WebView2 version 95.0.1020.44</li>
</ul>
<p>x Skipped: .NET SDK - Workloads (6.0.100)<br>
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</p>
<p>! There were one or more problems detected.<br>
Please review the errors and correct them and run maui-check again.</p>
<p>Press enter to exit…</p>
<p>C:\WINDOWS\system32&gt;maui-check<br>
_   _   _____   _____     __  __      _      _   _   ___<br>
| \ | | | <em><em><em><em>| |</em>   <em>|   |  /  |    / \    | | | | |</em> <em>|<br>
|  | | |  <em>|     | |     | |/| |   / _ \   | | | |  | |<br>
_  | |\  | | |</em></em></em>    | |     | |  | |  / ___ \  | |</em>| |  | |<br>
(</em>) |<em>| _| |_____|   |</em>|     |<em>|  |</em>| /<em>/   _\  _<strong>/  |</strong></em>|</p>
<p>☼ .NET MAUI Check v0.9.0.0 ☼<br>
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<br>
This tool will attempt to evaluate your .NET MAUI development environment.<br>
If problems are detected, this tool may offer the option to try and fix them for you, or suggest a way to fix them yourself.</p>
<p>Thanks for choosing .NET MAUI!<br>
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<br>
» Synchronizing configuration… ok<br>
» Scheduling appointments… ok</p>
<blockquote>
<p>OpenJDK 11.0 Checkup…</p>
</blockquote>
<ul>
<li>11.0.12 (C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin…)</li>
<li>1.8.0-25 (C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25)</li>
<li>11.0.12 (c:\program files\microsoft\jdk-11.0.12.7-hotspot\bin…)</li>
</ul>
<blockquote>
<p>Visual Studio 17.1.0-pre.1.0 Checkup…</p>
</blockquote>
<ul>
<li>17.1.0-pre.1.0 - C:\Program Files\Microsoft Visual Studio\2022\Preview</li>
<li>16.11.5</li>
</ul>
<blockquote>
<p>Android SDK Checkup…</p>
</blockquote>
<ul>
<li>emulator (30.8.4)</li>
<li>build-tools;31.0.0 (31.0.0)</li>
<li>platforms;android-31 (1)</li>
<li>system-images;android-31;google_apis;x86_64 (8)</li>
<li>platform-tools (31.0.3)</li>
<li>cmdline-tools;5.0 (5.0)</li>
</ul>
<blockquote>
<p>Android Emulator Checkup…</p>
</blockquote>
<ul>
<li>Emulator: pixel_5_r_11_0_-_api_30 found.</li>
</ul>
<blockquote>
<p>.NET SDK Checkup…</p>
</blockquote>
<p>───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<br>
☼ Recommendation: Download .NET SDK (6.0.100)<br>
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</p>
<p>! Attempt to fix? [y/n] (y): y<br>
» Attempting to fix: .NET SDK<br>
Downloading .NET SDK 6.0.100…<br>
Downloading… 10%…<br>
Downloading… 20%…<br>
Downloading… 30%…<br>
Downloading… 40%…<br>
Downloading… 50%…<br>
Downloading… 60%…<br>
Downloading… 70%…<br>
Downloading… 80%…<br>
Downloading… 90%…<br>
Downloading… 100%…<br>
Downloaded .NET SDK 6.0.100.<br>
Installing .NET SDK 6.0.100…<br>
Installed .NET SDK 6.0.100.<br>
Fix applied.  Checking again…</p>
<blockquote>
<p>.NET SDK Checkup…</p>
</blockquote>
<p>───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<br>
☼ Recommendation: Download .NET SDK (6.0.100)<br>
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</p>
<p>! Attempt to fix? [y/n] (y): y</p>
<p>x Skipped: .NET SDK - Workload Deduplication</p>
<blockquote>
<p>Edge WebView2 Checkup…</p>
</blockquote>
<ul>
<li>Found Edge WebView2 version 95.0.1020.44</li>
</ul>
<p>x Skipped: .NET SDK - Workloads (6.0.100)<br>
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</p>
<p>! There were one or more problems detected.<br>
Please review the errors and correct them and run maui-check again.</p>
<p>Press enter to exit…</p>

#### Feedback Bot on 11/9/2021, 05:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Thomas Giebink solved on 11/11/2021, 07:35 AM, 0 votes: 

<p>I think I’ve figured this out finally.  There’s a problem with the VS17.1prv1 installer… but it didn’t affect both of my development machines.  Sadly the one it affected was my main machine.  I’ll report this on a separate post in more detail but here’s the gist.  Somehow this installation affected the ORDER of my path variables for dotnet.  (See images)<br>
*I found the lead to the answer here:  <a target='_blank' href="https://github.com/dotnet/core/issues/5962#issuecomment-780084535">https://github.com/dotnet/core/issues/5962#issuecomment-780084535</a></p>
<p><img src="https://aka.ms/dc/image?name=B7678651be6f148d7bbdf9502a816184d637722412839793302_ProblemDOTNET_02.jpeg&amp;tid=7678651be6f148d7bbdf9502a816184d637722412839793302" alt="ProblemDOTNET_02.jpeg"><br>
<img src="https://aka.ms/dc/image?name=B1a9c147de6954bb5b88947e83ea2a602637722413055716029_ProblemDOTNET_01.jpeg&amp;tid=1a9c147de6954bb5b88947e83ea2a602637722413055716029" alt="ProblemDOTNET_01.jpeg"><br>
<img src="https://aka.ms/dc/image?name=B2c05067964d54c50b61ea2052d9629d3637722413880244338_FIX_Dotnet_Path_afterVS17.1prv1_installed.jpg&amp;tid=2c05067964d54c50b61ea2052d9629d3637722413880244338" alt="FIX_Dotnet_Path_afterVS17.1prv1_installed.jpg"><br>
<img src="https://aka.ms/dc/image?name=B7820a2bc9a6e46a09ab7cdb03bc1c9e9637722414356087153_AfterDotNet_Fix_CheckSdks.jpg&amp;tid=7820a2bc9a6e46a09ab7cdb03bc1c9e9637722414356087153" alt="AfterDotNet_Fix_CheckSdks.jpg"></p>
<p>Before this fix all my dotnet cmd 's failed<br>
including this example<br>
<img src="https://aka.ms/dc/image?name=B4e517e957cb04ad6b05f9d39f3b798ab637722415527715682_va17.1prv1_maui-check_problem_throws-error.jpg&amp;tid=4e517e957cb04ad6b05f9d39f3b798ab637722415527715682" alt="va17.1prv1_maui-check_problem_throws-error.jpg"></p>
<p>There was a hidden post that I found made on Sept 15 that lead me to find this solution.<br>
I believe that it’s an installer issue… but I don’t know why it occurred on one machine but not the other…</p>

**Comment by Redth** [comment]
Fixed in an upcoming release.
