### ISSUE TITLE
Error NU1605 after upgrading to 17.1.0 Preview 1.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3422]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-NU1605-after-upgrading-to-1710-P/1574467)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.0.0 Preview 7.0]
Have a solution with a MAUI single project preview 9 application created in Visual Studio 2022 Preview 7.0 and it uses WindowsAppSDK 1.0.0-experimental1. I have upgraded to Visual Studio 2022 17.1.0 Preview 1.0 which updates MAUI to Preview 10. The MAUI application fails to build now with the error below.

Error NU1605 Detected package downgrade: Microsoft.WindowsAppSDK from 1.0.0-preview3 to 1.0.0-experimental1. Reference the package directly from the project to select a different version.

How do I update my MAUI solution to correctly use Microsoft.WindowsAppSDK 1.0.0-preview3 correctly now?

---
#### Feedback Bot on 11/8/2021, 06:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NogginBox** [comment]
I found upgrading from preview 9 to 10 quite painful. Instructions would have been nice.

I ended up starting a new project and comparing the project files.

Several lines were no longer needed like:

```
<PackageReference Include="Microsoft.WindowsAppSDK.Foundation" Version="1.0.0-experimental1" /> 
<PackageReference Include="Microsoft.WindowsAppSDK.WinUI" Version="1.0.0-experimental1" /> 
<PackageReference Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="1.0.0-experimental1" NoWarn="NU1701" /> 
```
