### ISSUE TITLE
its Impossible to do more than one MAUI-Library Project into a Solution in VS2022 RC !!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3424]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/its-Impossible-to-do-more-than-one-MAUI-/1571130)._

---
I have tried to add a second MAUI-LIbrary into my solution file on VS2022 RC thats not possible, because it maked the added library as incomatibble

---
#### Srdjan Jovčić [MSFT] on 11/3/2021, 05:37 PM: 

<p>Hello <a target='_blank' href="https://developercommunity.visualstudio.com/users/3433/MarkusLein.html">Markus</a>,</p>
<p>Can you provide more information on failure you are seeing? I was not able to reproduce your issue.</p>
<p>Thanks,<br>
Srdjan</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Markus Lein on 11/3/2021, 06:53 PM: 

(private comment, text removed)
#### Markus Lein on 11/3/2021, 11:48 PM: 

(private comment, text removed)
#### Markus Lein on 11/4/2021, 02:46 AM: 

(private comment, text removed)
#### Markus Lein on 11/4/2021, 03:25 AM: 

(private comment, text removed)
#### Feedback Bot on 11/4/2021, 09:36 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
This issue is older, I'm going to assume that this is fixed by now. If this is still an issue for you in the current release, please open an issue with all the details.
