### ISSUE TITLE
Editor inside VerticalStackLayout automatically grows vertically on Android/WinUI but not on iOS

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#3425]
### Description

Given the following XAML

```XAML
        <VerticalStackLayout Margin="12">
            <Editor AutoSize="TextChanges"  />
        </VerticalStackLayout>
```

If you enter a new line Android/WinUI will grow vertically but iOS does not

Once this is fixed uncomment the following test
https://github.com/AndrewLang/maui/blob/4901cd7e50ccef841f148f78334004001591f72a/src/Controls/tests/DeviceTests/Elements/EditorTests.cs#L14

### Steps to Reproduce

[aeditortest.zip](https://github.com/dotnet/maui/files/7548759/aeditortest.zip)

1) run app
2) type text
3) hit the "Enter" key 

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

main

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by kristinx0211** [comment]
Verified repro with Android 11 and the above code snippet.

**Comment by hartez** [comment]
Just tested this on latest stable and it's working now. Need someone to PR re-enabling the test.
