### ISSUE TITLE
[Bug] [Android] Button in FlexLayout not clickable

### ISSUE THREAD

**Issue by LarsBehl** [dotnet/maui#3435]
### Description

When adding a `Button` or `ImageButton` to a `FlexLayout`, no click events are raised when clicking the button. A reproduction of the issue could be found [here](https://github.com/LarsBehl/StatusApp/blob/6ef0fd1368e7f2a615363127ede204fa1c75a09d/Views/SettingsView.xaml#L26).

#### Expected behavior
The `Button`s/`ImageButton`s `Clicked` event is raised.

#### Actual behavior
The `Clicked` event is not raised.

### Steps to Reproduce

1. Create new Maui App
2. Add `FlexLayout` to the `MainView`
3. Add a `Button` to the `FlexLayout`
4. Register a `Clicked` Handler for the `Button`
5. Click the button

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9/API 28

**Comment by PineYi** [comment]
Verified Repro with Android 11. Repro Project is available:
[#3435.zip](https://github.com/dotnet/maui/files/8151317/3435.zip)

**Comment by davidortinau** [comment]
If I give the FlexLayout a Minimum size such as when it's in a stack layout, the Button within the layout is clickable.

If the Button is within a FlexLayout that is sized by a container Grid, then the button is also clickable. This is the same FlexLayout sizing issue noted in several other issues.

**Comment by VincentBu** [comment]
not repro with vs [32506.368.main]. As [davidortinau](https://github.com/davidortinau) said, putting FlexLayout in Grid container make the button clickable.
