### ISSUE TITLE
Implement Navigating, Navigated events in WebViewHandler

### ISSUE THREAD

**Issue by Hooterr** [dotnet/maui#3440]
### Description

I wanted to check out the new WebView and it turns out the events for when Navigating and Navigated are not doing anything.
As suggested by @mattleibow WebView was switched from renderer to handler and the events were not ported.

Similar PR: https://github.com/dotnet/maui/pull/3316

### Steps to Reproduce

1. Open started MAUI projet
2. Add WebvView anywhere
3. Hook up to Navigating and Navigated events
4. The events are never fired

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

All versions

**Comment by joelving** [comment]
Is there any workaround to this? As a newcomer to Maui and Xamarin, I don't know whether i.e. the Source-property is supposed to be updated as the user navigates (it's currently not). Similarly, without a handler, EvalJavascriptAsync is unavailable, so it's not readily possible to extract the URL via i.e. the window.location.href.

This is using preview 11.
