### ISSUE TITLE
Consider using SkiaSharp for painting HTML/CSS UI onto the screen.

### ISSUE THREAD

**Issue by dk7796** [dotnet/maui#3449]
@Eilon Consider using SkiaSharp for painting HTML/CSS UI onto the screen in Blazor MAUI.

_Originally posted by @ahra04 in https://github.com/dotnet/maui/issues/3390#issuecomment-972994299_

**Comment by AmSmart** [comment]
What advantages would this offer over the current rendering approach via native WebViews?

**Comment by Eilon** [comment]
@AmSmart - if you wanted your app to have 100% identical UI on every platform (as in, exactly the same pixels), you usually need to render everything custom. With SkiaSharp you could theoretically do this.

**Comment by AmSmart** [comment]
Oh! I see the appeal.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We have no plans for rendering HTML with SkiaSharp.
