### ISSUE TITLE
[Windows] ContentView not rendering until resize Window

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#3462]
### Description

A ContentView is not rendering until resize Window:
![layout-issue](https://user-images.githubusercontent.com/6755973/142617782-87ad9531-35fd-4b21-b484-6c58bd872e09.gif)

Maybe could be a Layout issue?

### Steps to Reproduce

1. Download the sample: [FoodDeliveryApp.zip](https://github.com/dotnet/maui/files/7569978/FoodDeliveryApp.zip)
2. Launch the sample and resize the Window.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17134.0

**Comment by v-xiaofchen** [comment]
Verified repro with windows and the above project.
![Picture16](https://user-images.githubusercontent.com/99376012/155680206-60015f2e-397b-4061-8e7c-8ac5e2a712a5.png)

**Comment by samhouts** [comment]
Looks a lot different on 6.0.300-rc.4.5673, but definitely not better.

![image](https://user-images.githubusercontent.com/7827070/166572211-3e42f5bb-bd7e-4b22-9d2c-b08e36b2aab1.png)

**Comment by Redth** [comment]
I suspect Frame is at least partially to blame here.  If I replace all the Frame's with Borders I'm MUCH closer to how this should look.

![image](https://user-images.githubusercontent.com/271950/166615077-593f5741-f4f9-4def-b981-988f5a3bfae1.png)

@PureWeen was going to look at the cases where Frame and BoxView seem to be causing more layout issues.

**Comment by VincentBu** [comment]
not repro in vs main.
