### ISSUE TITLE
[Android] Crash: Canvas trying to draw too large

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#3463]
### Description

Trying to launch the attached sample:

![image](https://user-images.githubusercontent.com/6755973/142620254-e20e4176-5abd-4cbe-84d7-813ce923dcf2.png)

(Also Visual Studio 2022 freeze and crash at the end)

### Steps to Reproduce

1. Download the attached sample: https://github.com/dotnet/maui/files/7569879/FoodDeliveryApp.zip
2. Launch the sample on Android emulator.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Yes?. The issue is trying to use a **CarouselView**. Removing it from the View avoid the issue.

**Comment by shimingsg** [comment]
Verified Repro with Android 11 and VS17.2.0 Preview 2.0 [32223.271.main
updated the these 2 packages to latest version
Microsoft.Graphics.Win2D 
Microsoft.WindowsAppSDK

repro project: 
[3463.zip](https://github.com/dotnet/maui/files/8131395/3463.zip)

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro project:
[FoodDeliveryApp.zip](https://github.com/dotnet/maui/files/8569640/FoodDeliveryApp.zip)

**Comment by samhouts** [comment]
does not crash for me on 6.0.300-rc.4.5673, Android 11
