### ISSUE TITLE
Unable to delete bin folder while VS is open

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#3468]
### Description

obj folder deletes fine, but something is holding on to files in the bin folder. Leads me to think files aren't being properly handled and perhaps that's why my changes aren't working when debugging. But it's confusing b/c maybe it is a bug in MAUI and not that my changes aren't working. 

### Steps to Reproduce

Clean solution
open file explorer on windows
delete bin and obj folders

obj goes away, but a msg pops up that bin cannot be deleted.

close vs
delete bin again
pooof

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

all

**Comment by mattscheffer** [comment]
No repro with 17.2.0 Preview 1. Bin and Obj folders deleted successfully
