### ISSUE TITLE
iOS App Crashes if Hyperlink is Clicked in MAUI Blazor Project - NullReferenceException

### ISSUE THREAD

**Issue by ElliottBrand** [dotnet/maui#3474]
### Description

In iOS, clicking a hyperlink (it has a target of _blank in case it makes a difference) simply crashes the app and throws an error that says "System.NullReferenceException: 'Object reference not set to an instance of an object.'"  and it's displayed next to the following line in Program.cs

```
UIApplication.Main(args, null, typeof(AppDelegate));
```

Worst case, I'd expect nothing to happen (no error). Best case, I'd like to see links (that don't match the Uri) open in a new window or default browser. I'm working on trying to wire up something to detect a url link click and maybe open a browser...but the error seems to crash things before any of the other code can do anything.

### Steps to Reproduce

1. Create a new MAUI Blazor solution.
2. Open the index.razor page (probably the first page automatically loaded in the IDE).
3. Add a link into the page - something like ```<div><a href="https://blazot.com" target="_blank">https://blazot.com</a></div>```. 
4. Pair Visual Studio 17.1.0 Preview 1.1 to a Mac
5. In the debugger dropdown, select Simulators then choose an iPhone version to launch/debug in (i.e. iPhone 13 iOS 15) and click it to launch a simulator.
6. Once the app is running in the simulated iPhone, click the link.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15 (haven't tried others)

### Relevant log output

```shell
objc[16038]: Class _PathPoint is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore (0x12ac70a78) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TextInputUI.framework/TextInputUI (0x164d558b0). One of the two will be used. Which one is undefined.

objc[16038]: Class _PointQueue is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore (0x12ac70a50) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TextInputUI.framework/TextInputUI (0x164d558d8). One of the two will be used. Which one is undefined.

**System.NullReferenceException:** 'Loading...'
```

**Comment by Eilon** [comment]
Possible dup of https://github.com/dotnet/maui/issues/3385.

**Comment by ElliottBrand** [comment]
I opened both and believe they are two separate things. #3385 was something I thought was an issue, but after more research, I believe it's just how Xamarin has worked for a while. Coming from web development, I just expected it to work, but it now looks like Xamarin developers must have been adding a method to catch all link clicks and do something with them at that point...I haven't figured out how to handle it yet. The link click wasn't throwing an error in Android, it just takes over the webview and you're stuck there.

This issue here is iOS specific. It doesn't take me to the destination, it just crashes completely.

**Comment by Eilon** [comment]
Ah, got it! At a minimum it shouldn't crash, of course 😄 But I think having the links at least raise some event so that the app can handle it could be nice. And maybe by default open the link in the platform's default browser if the event isn't handled.

**Comment by ElliottBrand** [comment]
Haha. Yeah, I agree. Having some default behavior to open in a new browser makes sense, especially since many who are using MAUI Blazor are probably using the same components in a website. It would be a much easier experience. If it will take a while for anyone to get to, an example of how to intercept the link click and launch with the Essentials Browser would probably be helpful to many (including me).

**Comment by Eilon** [comment]
The BlazorWebView does its own hosting of the native webview components on each platform, so this would be different from what Essentials does.

**Comment by ElliottBrand** [comment]
What I was thinking was, if there was a way to intercept the link click in the AppDelelgate/MainActivity (maybe by overriding a method that provides the link) or something along those lines, perhaps then I could take that link and launch it in the Essentials browser if necessary. I could be way off base though... If the functionality is built in by default, I guess it wouldn't really matter.

**Comment by Eilon** [comment]
Oh, I see. I'll see what we can do to at least detect these link clicks and offer an event. If possible, I'll see how to wire it to a good default behavior, or at least a sample on how to go through Essentials browser, or something else.
