### ISSUE TITLE
NRE when typing into Editor on Windows

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#3477]
### Description

NRE when typing into `Editor` on Windows.

![image](https://user-images.githubusercontent.com/41873/142697806-2553cf37-42d0-4fdf-a729-8c45b9e48719.png)

Source https://github.com/davidortinau/ControlGallery

### Steps to Reproduce

Click Editor and type a single character while debugging

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Win11

**Comment by jsuarezruiz** [comment]
Will be fixed by https://github.com/dotnet/maui/pull/3392

**Comment by hartez** [comment]
Or possibly fixed by #3444

**Comment by pierre01** [comment]
Crash occurs When **Placeholder**  text is set.
Otherwise the editor does not crash.

**Comment by hartez** [comment]
> Crash occurs When **Placeholder** text is set. Otherwise the editor does not crash.

That sounds like a different bug, then. Please submit an issue and we'll take a look.

**Comment by shimingsg** [comment]
Not reproducible with Windows.
