### ISSUE TITLE
FlexLayout Basis doesn't update live on Windows

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#3481]
### Description

<img width="773" alt="image" src="https://user-images.githubusercontent.com/41873/142699305-2317cb2e-8578-4165-b68b-129b10ee95f9.png">

https://github.com/davidortinau/ControlGallery

After resizing window

<img width="778" alt="image" src="https://user-images.githubusercontent.com/41873/142699447-8de4a172-95d4-4f47-97ac-21d5fe2ae308.png">

### Steps to Reproduce

Run FlexLayout sample or my ControlGallery

Untoggle Auto for Label 2 and use the slider. Layout should update instantly.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Win11

**Comment by shimingsg** [comment]
Verified repro with windows and the above project.

**Comment by davidortinau** [comment]
Re-verified on main (rc3)

**Comment by shimingsg** [comment]
verified still repro on windows with VS 17.3.0 Preview 2.0 [32506.315.main]
![3481](https://user-images.githubusercontent.com/20982341/167527079-d712cdd8-7b91-453e-935c-83c1901af542.gif)

**Comment by hartez** [comment]
This is fixed in GA.
