### ISSUE TITLE
Fresh MAUI project failing to deploy

### ISSUE THREAD

**Issue by DeeJayhX** [dotnet/maui#3485]
### Description

A fresh MAUI UI project (non-blazor) gives deployment errors regarding Appxmanifest.xml.

This happens on:

- Windows 10 => 11 upgraded desktop running 5900x/128GB RAM
- Windows 11 brand new install on a Dell Latitude 7490

Both on VS 17.1.0 Preview 1.1 with Developer mode enabled. Cannot get them to run on the installed Pixel emulator for android either. No iPhone to test iOS. Tried modifying Appxmanifest.xml to have full control by Everyone, deploy, same issue. Let me know if I can provide anything else.

### Steps to Reproduce

Create Project > new .NET MAUI App
Start with debugging for Windows Machine

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 21H2 Build 22000.318 - SDK net6.0-windows10.0.19041

### Did you find any workaround?

No

### Relevant log output

```shell
Creating a new clean layout...
Copying files: Total 113 mb to layout...
Checking whether required frameworks are installed...
Registering the application to run from layout...
2>Deployment of the application to the target device failed.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
DEP0700: Registration of the app failed. [0x80070005] error 0x80070005: Opening file from location: AppxManifest.xml failed with error: Access is denied.
```

**Comment by StevenTCramer** [comment]
I had this problem also then ran. https://github.com/Redth/dotnet-maui-check

which updated some Android SDKs.

But now I get some 1990s looking phone when it is supposed to be a Pixel

![image](https://user-images.githubusercontent.com/357219/144888452-f3fcefd9-4bbe-46b5-a39f-62d7c29f2899.png)

**Comment by azizimusa** [comment]
just deploy to your real device.

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
