### ISSUE TITLE
Grid with auto row and column not sizing correctly on Windows when child has a margin

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#3488]
### Description

Given a grid with auto column and row, a child at those coords is cut off when using margin. This is only on Windows, Android is fine and iOS has a different issue.

### Steps to Reproduce

Replace MainPage.cs with the following constructor:

        public MainPage()
        {
            var frame = new Frame
            {
                BackgroundColor = Colors.Red,
                HorizontalOptions = LayoutOptions.CenterAndExpand,
                VerticalOptions = LayoutOptions.CenterAndExpand,
                HeightRequest = 60,
                WidthRequest = 60,
                CornerRadius = 30,
                Margin = 10
            };

            Grid.SetRow(frame, 1);
            Grid.SetColumn(frame, 1);

            var grid = new Grid()
            {
                HorizontalOptions = LayoutOptions.CenterAndExpand,
                VerticalOptions = LayoutOptions.CenterAndExpand,
                BackgroundColor = Colors.LightGray,
                ColumnDefinitions =
                {
                    new ColumnDefinition { Width = GridLength.Auto },
                    new ColumnDefinition { Width = GridLength.Auto },
                    new ColumnDefinition { Width = GridLength.Auto },
                },
                RowDefinitions =
                {
                    new RowDefinition { Height = GridLength.Auto },
                    new RowDefinition { Height = GridLength.Auto },
                    new RowDefinition { Height = GridLength.Auto },

                },
                Children =
                {
                    frame
                }
            };

            Content = grid;
        }

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows, don't know which

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EWOt3k0QQbRMnkqRNnxnd0IBbUx-kYjKEP8Ua-DEMCzSSw?e=ccGeSJ

**Comment by davidortinau** [comment]
This looks correct to me. Closing as fixed.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/41873/165562024-afc66292-ba8e-4156-89fb-873514cab2c7.png">
