### ISSUE TITLE
Grid with auto row and column not rendering child Frame with correct height on iOS when child has a margin

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#3489]
### Description

Given a grid with auto column and row and a margin, the height and width request is incorrect when a margin is specified.

### Steps to Reproduce

Replace MainPage.cs with the following constructor:

    public MainPage()
    {
        var frame = new Frame
        {
            BackgroundColor = Colors.Red,
            HorizontalOptions = LayoutOptions.CenterAndExpand,
            VerticalOptions = LayoutOptions.CenterAndExpand,
            HeightRequest = 60,
            WidthRequest = 60,
            CornerRadius = 30,
            Margin = 10
        };

        Grid.SetRow(frame, 1);
        Grid.SetColumn(frame, 1);

        var grid = new Grid()
        {
            HorizontalOptions = LayoutOptions.CenterAndExpand,
            VerticalOptions = LayoutOptions.CenterAndExpand,
            BackgroundColor = Colors.LightGray,
            ColumnDefinitions =
            {
                new ColumnDefinition { Width = GridLength.Auto },
                new ColumnDefinition { Width = GridLength.Auto },
                new ColumnDefinition { Width = GridLength.Auto },
            },
            RowDefinitions =
            {
                new RowDefinition { Height = GridLength.Auto },
                new RowDefinition { Height = GridLength.Auto },
                new RowDefinition { Height = GridLength.Auto },

            },
            Children =
            {
                frame
            }
        };

        Content = grid;
    }

The child Frame should appear as a circle, but it is clear the height and width requests are being effected by the Margin. If you set margin to zero it renders correctly.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15, but I resume all

**Comment by shimingsg** [comment]
Verified Repro with iPhone 13 pro max IOs 15.2. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/ETqrBw8aGAJPuNimHLJo59ABxa9LEZqVIJKw88RcOqDLeA?e=ouhBgX

**Comment by davidortinau** [comment]
This is working now as expected on Mac Catalyst and iOS.
