### ISSUE TITLE
Clarify meaning of community support?

### ISSUE THREAD

**Issue by leo60228** [dotnet/maui#349]
When I saw that Linux was listed as community support in the README I assumed that Linux support was implemented but not maintained by Microsoft. However, as far as I can tell, Linux isn't yet implemented.

**Comment by PureWeen** [comment]
Once we're in a state where we can start accepting community PRs we'll clarify how to contribute linux .NET MAUI bits

**Comment by YoshiRulz** [comment]
Can we get a clear answer to the question "Will Microsoft add Linux desktop support to MAUI by its launch?" And by "Linux desktop support" I only mean if it will be mostly functional, like GTK# in Xamarin.Forms is today.

I'd also like to know if projects for Android, macOS, or Windows can be built on a Linux host (see also #359).
