### ISSUE TITLE
Microsoft.AspNetCore.Components.WebView.WindowsForms  use  with NotifyIcon

### ISSUE THREAD

**Issue by liuxiping** [dotnet/maui#3491]
### Description

mainwindow and a  NotifyIcon component  when click close system buton    I add Code as below

```c#
 private void MainWindow_FormClosing(object sender, FormClosingEventArgs e)
        {
            e.Cancel = true;
            this.Hide();
            this.ShowInTaskbar = false;

        }
```

when  maximize the mainwindow  ,   and then click the  system close button 

but when I  restore the window  from NotifyIcon  click event  

```c#
private void niMain_MouseClick(object sender, MouseEventArgs e)
        {
            if (e.Button == MouseButtons.Left)
            {
                this.ShowInTaskbar = true;
                this.Show();
            }
        }
```

the BlazorWebView Control  disappear 

### Steps to Reproduce

mainwindow and a  NotifyIcon component  when click close system buton    I add Code as below

```c#
 private void MainWindow_FormClosing(object sender, FormClosingEventArgs e)
        {
            e.Cancel = true;
            this.Hide();
            this.ShowInTaskbar = false;

        }
```

when  maximize the mainwindow  ,   and then click the  system close button 

but when I  restore the window  from NotifyIcon  click event  

```c#
private void niMain_MouseClick(object sender, MouseEventArgs e)
        {
            if (e.Button == MouseButtons.Left)
            {
                this.ShowInTaskbar = true;
                this.Show();
            }
        }
```

the BlazorWebView Control  disappear 

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

Windows

### Affected platform versions

Windows10    19042.1348

**Comment by XamlTest** [comment]
@liuxiping Could you provide your repro project, thanks?
