### ISSUE TITLE
[Bug] [Android] Modal content not resizing

### ISSUE THREAD

**Issue by LarsBehl** [dotnet/maui#3494]
### Description

When content is dynamically added to a page which is currently displayed inside a modal, the page/modal content is not getting resized.

You can find the repro [here](https://github.com/LarsBehl/MauiModalResize).

#### Expected
![image](https://user-images.githubusercontent.com/26459044/142763063-27f01925-bdd3-4d84-be83-488048978acb.png)

#### Actual
![image](https://user-images.githubusercontent.com/26459044/142763089-660a7ea3-b55b-4104-80b4-ae7a49b24482.png)

### Steps to Reproduce

1. Create new Maui Application
2. Add new `ContentPage` (xaml) to application
3. Replace the content of the `ContentPage` with a `VerticalStackLayout` and give it a name
4. Add a `Button` to the Layout
5. Add click handler for the button which adds a Label to the named `VerticalStackLayout`
6. Add a `Button` to the applications `MainPage`
7. Add click handler for the button which opens the created `ContentPage` as a modal: `Navigation.PushModalAsync(...)`
8. Start the application, open the modal and click the `Button` for adding labels

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9/API 28

**Comment by wenwen60** [comment]
Not reproducible with Android 11.
