### ISSUE TITLE
The minimum value in the slider is not being updated.

### ISSUE THREAD

**Issue by SuryaChinnadurai** [dotnet/maui#3498]
### Description

When setting the slider minimum value as 50,  maximum as 100, and value as 75 and moving the slider to the start, which is able to get the slider value is 0.

**Code snippet:**
```
<StackLayout Margin="10" Spacing="10" VerticalOptions="Center">
      <Slider x:Name="FrameworkSlider" Minimum="50" Maximum="100" Value="75"></Slider>
      <HorizontalStackLayout>
         <Label Text="Slider Value : "></Label>
         <Label BindingContext="{x:Reference Name=FrameworkSlider}" Text="{Binding Path= Value}"></Label>
     </HorizontalStackLayout>
</StackLayout>
```
**Expected:**

![Expected output](https://user-images.githubusercontent.com/72392561/142806233-56755ec4-02f6-4725-83e3-e424ac9b8dfc.gif)

**Actual:**

![Actual output](https://user-images.githubusercontent.com/72392561/142806263-1a6cffb8-a35a-4c59-8432-df8396d9ae0f.gif)

### Steps to Reproduce

1. Create a new Maui Application
2. Add slider and label in the stack layout
3. Set the slider minimum as 50, maximum as 100, and value as 75.
4. Bind the slider value to the label.
5. Move the slider to the start point

### Version with bug

Preview 9

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Android 9/API 28

### Did you find any workaround?

No

### Relevant log output

```shell
No response
```

**Comment by jsuarezruiz** [comment]
Could you try with the latest Preview?. Tried in main branch and cannot reproduce the issue.

**Comment by SuryaChinnadurai** [comment]
@jsuarezruiz I tried with the latest preview. This occurs when we set the slider properties as shown below

Xmal:
```
<Label Text="Minimum (5) and Maximum (15)"/>

 <Slider x:Name="MinMaxSlider"
                Minimum="5"
                Maximum="15"
                ValueChanged="OnValueChanged"/>

  <Label FontSize="Micro"
                Text="{Binding Source={x:Reference MinMaxSlider}, Path=Value}"/>
```

Cs:
```
void OnValueChanged(object sender, ValueChangedEventArgs args)
{
	Debug.WriteLine($"Slider Value: {args.NewValue}");
}
```
