### ISSUE TITLE
[Bug] Name clash with Maui Linux and MauiKit

### ISSUE THREAD

**Issue by probonopd** [dotnet/maui#35]
### Description

A multi-platform app UI toolkit with the name of __maui__ was introduced by Microsoft on May 19th, 2020 according to https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/:

> **MAUI** simplifies the choices for .NET developers, providing a single stack that supports all modern workloads: Android, iOS, macOS, and Windows. The native features of each platform and UI control are within reach in a simple, cross-platform API for you to deliver no-compromise user experiences while sharing even more code than before.

There has been https://mauilinux.org/ for a long time:

> Fast and easy to use, yet powerful for computer users of all levels, **Maui** is a part-rolling distribution based on KDE Neon/Ubuntu. Maui features its own managed repositories and backport channels and ships with the following software components and applications for day-to-day use

According to [Wikipedia](https://fr.wikipedia.org/wiki/Maui_Linux), Maui Linux has been around sine 2016.

Also, there has been [**Maui**Kit](https://mauikit.org/) for a long time:

> **MauiKit**, a free and modular front-end framework for developing fast and compelling user experiences

There is clearly a name clash.

### Steps to Reproduce

1.  Visit https://mauilinux.org/ and https://fr.wikipedia.org/wiki/Maui_Linux
2. Visit https://mauikit.org//
3. Visit https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/

### Expected Behavior

Microsoft chooses names not already used in the Linux community.

### Actual Behavior

Microsoft chooses names already used in the Linux community.

### Screenshots

![](https://user-images.githubusercontent.com/2480569/82367816-effaec80-9a03-11ea-9887-9d5675f11698.png)

**Comment by dansiegel** [comment]
Perhaps the Linux project should change its name as they've conflicted with a city in Hawaii which existed long before. Look again, the name isn't Maui, the name is Multi-platform App UI which abbreviates to M.A.U.I.

**Comment by veggero** [comment]
I feel like there's much less confusion between a city in Hawaii and a multi platform app framework both called Maui than a multi platform app framework and a multi platform app framework both called Maui.

**Comment by IlyaBizyaev** [comment]
So you think of a Hawaian city when reading "Maui", but not when reading "MAUI"? Really?

**Comment by dansiegel** [comment]
You find the comparison between a city in Hawaii and MauiKit ridiculous just like I find your comparison between an the Maui abbreviation and MauiKit ridiculous

**Comment by IlyaBizyaev** [comment]
> You find the comparison between a city in Hawaii and MauiKit ridiculous just like I find your comparison between an the Maui abbreviation and MauiKit ridiculous

The project is called Maui, has been called that for a long time, and is even stylized as "MAUI" on https://mauikit.org. So yeah, there's an obvious naming clash here.

**Comment by ptdave20** [comment]
This is a non issue.

**Comment by veggero** [comment]
How is having two product with the same name and same basic scope (multi platform framework) a non issue?

**Comment by dansiegel** [comment]
You can be mad all you want, but let's be realistic here... this project you're fighting for so passionately doesn't have as many stars as I have thumbs down for telling you that you'e being ridiculous 

![image](https://user-images.githubusercontent.com/3860573/82369702-4b10ed00-99cc-11ea-8090-18139fe8d746.png)

**Comment by IlyaBizyaev** [comment]
That's because GitHub stars are not a currency in which you measure a project that is not even developed on GitHub.

**Comment by veggero** [comment]
That's because it's a mirror. The actual project is developed in KDE gitlab instance.

**Comment by probonopd** [comment]
You know what KDE is, right?

**Comment by TheAssassin** [comment]
They even refer _themselves_ to Hawaii. Check https://github.com/dotnet/maui/commit/c7e2c55ace3ec55a0858f1c4bb55476375ea72f8, its commit message says, "Aloha fix".

I don't think they took into account either confusion with the "Linux project" *nor with the Hawaiian island*.

(By the way, is it seriously necessary to mention that when there's an obvious name conflict with some other free software project in the exactly same domain (UI toolkit)? Come on, get over this "Linux vs. Windows" mantra you still seem to follow.)

**Comment by mirkobrombin** [comment]
> You can be mad all you want, but let's be realistic here... this project you're fighting for so passionately, doesn't have as many stars as I have thumbs down for telling you that you'e being ridiculous
> 
> ![image](https://user-images.githubusercontent.com/3860573/82369702-4b10ed00-99cc-11ea-8090-18139fe8d746.png)

Let's pretend that this is not a mirror but the official repository (not so).. can a project name be stolen because it has less fame?

**Comment by ptdave20** [comment]
It's a non issue because things are allowed to have the same or similar
names. To be honest, I never heard of the others except for the location.

No matter the name, there is probably someone or something using it.

**Comment by probonopd** [comment]
https://en.wikipedia.org/wiki/Confusing_similarity

**Comment by veggero** [comment]
And this is not even a confusing _similarity_.
We are talking about a multi platform framework called MAUI, and a multi platform framework called MAUI. You could've at least googled the name you were giving to your product before doing so, or choose one that's used from a product with a different scope.

**Comment by IlyaBizyaev** [comment]
> No matter the name, there is probably someone or something using it.

Somehow all other cross-platform frameworks I can think of have managed to choose a name that would not conflict with other similar projects. I wonder what's so different here that would prevent Microsoft from finding a scope-unique name.

**Comment by dansiegel** [comment]
@probonopd @mirkobrombin so you like this cute little side project... but let's be honest here when it comes to being a serious project it's not one. There isn't major support for MauiKit, the likelihood is that most people probably never heard of it before today, and there is no widespread adoption of it. Can you name 10 large companies that have adopted it?

Your attitude is as if Microsoft is being some big evil corporation. The reality is I highly doubt anybody heard of MauiKit, and frankly nobody cares.

> Let's pretend that this is not a mirror but the official repository (not so).. can a project name be stolen because it has less fame?

Ok let's look at kde... there are 10 open issues... are you seriously going to tell me that a serious cross platform framework has 10 open issues... that's not realistic in any shape way or form. So again your complaints are just being ridiculous.

**Comment by UriHerrera** [comment]
@dansiegel Are you an _official_ Microsoft or Xamarin representative, and if so, is this the official position of your company?.

**Comment by IlyaBizyaev** [comment]
> ridiculous
> cute little side project
> nobody cares
> anybody heard of
I hope this is not Microsoft's general attitude towards open source projects these days...

**Comment by veggero** [comment]
> Your attitude is as if Microsoft is being some big evil corporation. The reality is I highly doubt anybody heard of MauiKit, and frankly nobody cares.

Because it's a recent project. It has been under development for two years, but it's public. It was - until today - literally the first result when searching for "maui framework". 

> Ok let's look at kde... there are 10 open issues... are you seriously going to tell me that a serious cross platform framework has 10 open issues... that's not realistic in any shape way or form. So again your complaints are just being ridiculous.

Microsoft's Maui has 21 issues. 10 issues bad, 21 issues good?

**Comment by TheAssassin** [comment]
@all what do you expect, providing some real arguments against nonsense or offending replies like "you're all mad" or "it's the others' fault, they need to rename" (aka "we are Microsoft (related), we are bigger, you need to comply" or, my favorite, "same name is not a problem at all", pretending that confusion was not an issue...

@dansiegel great strategy, being offending once you run out of arguments! Really! Is that how Microsoft's unpaid marketers aka "Microsoft MVP" are chosen? How can you seriously accuse others of like, thinking in this old "it's a big evil company" way (which nobody really has), while yourself being extremely off-putting towards the open-source community? It makes no sense...

Remember, Microsoft recently admitted [they've been on the wrong side of history with regard to open source](https://www.theregister.co.uk/2020/05/15/microsoft_brad_smith_open_source/). You have *zero* reason to belittle this or _any_ other open-source project. Especially since this one's also open-source.

**Comment by Manueljlin** [comment]
Imagine trying to put up a façade with ms❤️linux, then turning stuff into a dick size competition with repo stars and other stats because you know you messed up and don't want to admit it lmfao

**Comment by ChaseFlorell** [comment]
> @dansiegel Are you an official Microsoft or Xamarin representative, and if so, is this the official position of your company?.

He is not affiliated with MS at all, but he definitely has done more for the .NET Ecosystem than anyone else in these comments. [>3 million downloads](https://www.nuget.org/packages/Prism.Core/)

**Comment by IlyaBizyaev** [comment]
> he definitely has done more for the .NET Ecosystem than anyone else in these comments

How much has he done for the Qt Ecosystem though? ;)

**Comment by dansiegel** [comment]
@UriHerrera you can see my profile.. I am a member of the Xamarin developer community, I do not work for Microsoft. And if you don't like it nobody is forcing you to use it, use MauiKit if that's what you love, but developers who actually use this tech think you're being ridiculous.

> Microsoft's Maui has 21 issues. 10 issues bad, 21 issues good?

Maui was just created... and is a port of Xamarin.Forms so yeah you want to see what a real Open Source application framework looks like I suggest you start taking notes. 

@TheAssassin - bro I am an Open Source author and maintainer so don't try lecturing me about being against "off-putting towards the open-source community"

**Comment by boingo-00** [comment]
> there are 10 open issues

This is a tiny amount, big projects have bigger issue count, and this is OK
Why you even pointing on this? It is unethical, you are don't have any arguments?
__P.S. replying in epic thread__

**Comment by UriHerrera** [comment]
> > @dansiegel Are you an official Microsoft or Xamarin representative, and if so, is this the official position of your company?.
> 
> He is not affiliated with MS at all, but he definitely has done more for the .NET Ecosystem than anyone else in these comments. [>3 million downloads](https://www.nuget.org/packages/Prism.Core/)

That is great, but I did not ask that. If no representative wants to even _talk_  about this, so be it. I'll take that as Microsoft and Xamarin's official position regarding this issue hand.

**Comment by mirkobrombin** [comment]
> @probonopd @mirkobrombin so you like this cute little side project... but let's be honest here when it comes to being a serious project it's not one. There isn't major support for MauiKit, the likelihood is that most people probably never heard of it before today, and there is no widespread adoption of it. Can you name 10 large companies that have adopted it?
> 
> Your attitude is as if Microsoft is being some big evil corporation. The reality is I highly doubt anybody heard of MauiKit, and frankly nobody cares.
> 
> > Let's pretend that this is not a mirror but the official repository (not so).. can a project name be stolen because it has less fame?
> 
> Ok let's look at kde... there are 10 open issues... are you seriously going to tell me that a serious cross platform framework has 10 open issues... that's not realistic in any shape way or form. So again your complaints are just being ridiculous.

So a project has value based on open issues?

I have nothing against Microsoft, here we talk about a name and who chose it before (in the same context). 

I don't know how you can question the seriousness of one of the biggest communities that drive open source principles many years before Microsoft fell in love with open source.

**Comment by ChaseFlorell** [comment]
>  If no representative wants to even talk about this
Since the issue was opened a mere 60 minutes ago 😂

**Comment by IlyaBizyaev** [comment]
> you want to see what a real Open Source application framework looks like I suggest you start taking notes
There appear to be more passive-aggressive comments towards another project in this thread from you alone than there are from all other people towards this .NET repository. That's not because others really love .NET, but because they try to stay constructive here.

**Comment by ChaseFlorell** [comment]
Unless MauiKit has a ™ on the name, I can't see how this is at all an issue.

**Comment by UriHerrera** [comment]
> Unless MauiKit has a ™ on the name, I can't see how this is at all an issue.

Unless you _actually_ work for the companies involved, your opinion is probably negligible here.

**Comment by ChaseFlorell** [comment]
I'm surprised no one complained about Microsoft's use of the name `core`

 - https://github.com/home-assistant/core
 - https://github.com/dotnet/core
 - https://github.com/owncloud/core
 - https://github.com/stackblitz/core
 - https://github.com/flarum/core
 - https://github.com/c9/core
 - https://github.com/adonisjs/core
 - [et al](https://github.com/search?q=core&ref=opensearch)

**Comment by lnjX** [comment]
@ChaseFlorell Good constructive argument. :+1:

lol

**Comment by ChaseFlorell** [comment]
Nothing about this thread is constructive.

**Comment by boingo-00** [comment]
Продам гараж

**Comment by IlyaBizyaev** [comment]
> I'm surprised no one complained about Microsoft's use of the name `core`

Maybe because "Core" is not a marketed Microsoft product name, but a component of a marketed product named ".NET"?
There is Qt Core, and somehow Qt Core and .NET Core don't read as similar as "MAUI" and "MAUI" do.

**Comment by dansiegel** [comment]
@mirkobrombin projects do have value based on the value that they provide. The most notable measure of that is the community around that project. You might not like hearing it but MauiKit doesn't seem to have a community. It looks like a side project. I asked before `Can you name 10 large companies that have adopted it?` and you didn't or couldn't.

MauiKit whether you want to hear it or not has no fundamentals of what I as an Open Source Author and Maintainer would consider signs of a healthy project. I do not see a community around that project at all. I do not see adoption within the enterprise. What I do see is a bunch of people who want to complain but probably never have used Xamarin and probably never will use Maui regardless of what it's called.

**Comment by ChaseFlorell** [comment]
> There is Qt Core, and somehow Qt Core and .NET Core don't read as similar as "MAUI" and "MAUI" do.

I presume you mean "MauiKit" and  ".NET Multi-platform App UI (MAUI)"

**Comment by davidortinau** [comment]
Hi all, the official legal name is .NET Multi-platform App UI and MAUI is an acronym, code name. This has been through legal review. 

I don't believe this is not the forum for this discussion. If there are ongoing concerns, please email me and we can loop in the appropriate teams.

**Comment by boingo-00** [comment]
Beautiful! You steal name and say that it's OK! Good position!

**Comment by Project-Magenta** [comment]
> I don't believe this is not the forum for this discussion. If there are ongoing concerns, please email me and we can loop in the appropriate teams.

If you don't believe this is not the forum, why close issue?

**Comment by TheAssassin** [comment]
@davidortinau this is less about a legal issue, but more or less about a name conflict.

... not sure if you expect us all to email you now, but please be prepared...

**Comment by davidortinau** [comment]
Email me david.ortinau@microsoft.com. Stealing is not ok and has not been intended. Happy to work throught conflicts.

**Comment by mirkobrombin** [comment]
> @mirkobrombin projects do have value based on the value that they provide. The most notable measure of that is the community around that project. You might not like hearing it but MauiKit doesn't seem to have a community. It looks like a side project. I asked before `Can you name 10 large companies that have adopted it?` and you didn't or couldn't.
> 
> MauiKit whether you want to hear it or not has no fundamentals of what I as an Open Source Author and Maintainer would consider signs of a healthy project. I do not see a community around that project at all. I do not see adoption within the enterprise. What I do see is a bunch of people who want to complain but probably never have used Xamarin and probably never will use Maui regardless of what it's called.

It continues to not be an applausible reason to claim that Microsoft deserves that name compared to other projects that have adopted it before in the exact same context.It is not about image, size or who adopted the technology but who first applied that name in that context.We are talking about open source projects, there should be a common philosophy, not a competition for those who have the biggest issue counter.

**Comment by UriHerrera** [comment]
> Email me [david.ortinau@microsoft.com](mailto:david.ortinau@microsoft.com). Stealing is not ok and has not been intended. Happy to work throught conflicts.

Will do. Thank you.

**Comment by veggero** [comment]
> Email me [david.ortinau@microsoft.com](mailto:david.ortinau@microsoft.com). Stealing is not ok and has not been intended. Happy to work through conflicts.

Perfect. Thank you!

**Comment by Project-Magenta** [comment]
> I don't believe this is not the forum for this discussion. If there are ongoing concerns, please email me and we can loop in the appropriate teams.

Why close issue when you "don't believe this is not the forum"

**Comment by IlyaBizyaev** [comment]
> > There is Qt Core, and somehow Qt Core and .NET Core don't read as similar as "MAUI" and "MAUI" do.
> 
> I presume you mean "MauiKit" and ".NET Multi-platform App UI (MAUI)"

In the announcement, it is referred to as MAUI most of the time. Obviously, this is how developers are going to reference it, and google it, and mention it in other resources.

Thank you @davidortinau.

**Comment by thatnerdyguy** [comment]
In addition to all the other problems "MAUI" is not google/bing-able... it brings up the city. "Xamarin Forms" is, "DotNetUI" would be, "MAUI", not so much.

**Comment by davidortinau** [comment]
@dansiegel your tone and style of commenting is violating our [Code of Conduct](https://dotnetfoundation.org/about/code-of-conduct). We have marked the problematic comments as abusive and blocked you for 7 days. If this behavior persists, we’re going to block you permanently.

It’s OK to be passionate but attacking another open source project for any reason is not okay. This is not the kind of community we want to have and such behavior will not be tolerated.
