### ISSUE TITLE
[Enhancement] Remove use of EditorBrowsableState.Never

### ISSUE THREAD

**Issue by wjk** [dotnet/maui#350]
## Summary

In many places within Xamarin.Forms/.NET MAUI, types that ought to be internal are instead declared public, but decorated with `[EditorBrowsable(EditorBrowsableState.Never)]` to hide them from users’ autocompletion. Since I use autocompletion extensively (it’s the one tool I use the most when I write code), I believe this to be an egregious antipattern. In places where `InternalsVisibleToAttribute` would perform the same task (of allowing MAUI assemblies to share internal classes with each other, but not with app code), it is even more annoying.

## API Changes

I suggest removing all usage of `EditorBrowsableAttribute` from the codebase, change the types that were annotated with that attribute from public to internal, and add `InternalsVisibleToAttribute` to assemblies as needed to fix the build. This may be a major breaking API change, but I find use of `EditorBrowsableAttribute` to be extremely obnoxious when I am debugging MAUI code, as the names of types that might help diagnose the problems won’t show up in autocomplete. It also interferes with maintenance and enhancement of the MAUI code itself. If this truly cannot work for certain APIs, mark those classes as public, and add doc comments stating “Internal use only.” Other UI frameworks have done this in similar situations.

**Comment by PureWeen** [comment]
Legacy code will still have it but Maui code won't
