### ISSUE TITLE
System.TypeLoadException: VTable setup of type BindableObject failed

### ISSUE THREAD

**Issue by PiruthivirajM** [dotnet/maui#3501]
### Description

Hi Team,

We are developing custom component in MAUI and in that, we have a class "LinearLayout" which derived from "BindableObject". We used to initialize object for this class in component constrcutor.

While running the sample, we getting below exception on loading,
![image](https://user-images.githubusercontent.com/44426156/142822404-ee2c686f-07b8-430e-889d-ef79e0c9ba86.png)

Please share any suggestions to find reason and solutions.

### Steps to Reproduce

-

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 28

**Comment by devmikew** [comment]
A VTable is a function pointer table. It is created by the compiler when you build your code. Normally you don't have to do anything with it in your code.

So, maybe there is something wrong with your class hierarchy/inheritance, and/or your overriding methods in your code.

**Comment by PureWeen** [comment]
This usually happens if your reference libraries are out of sync from your main project library or if you are referencing a library built against an old version of MAUI

Can you please attach a repro?

**Comment by wenwen60** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
