### ISSUE TITLE
In preview 10 absolute layout draw override method not called

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#3509]
### Description

In absolute layout draw override method not called in iOS and WinUI. 

This issue not reproduced in android. 

In iOS and WinUI also, upto preview 9, this issue not reproduced. 

This issue reproduced only in Preview 10. 

Please check and update us. 

### Steps to Reproduce

```
public override void Draw(ICanvas canvas, RectangleF dirtyRect)
        {
            base.Draw(canvas, dirtyRect);

        }
```

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 9

### Affected platforms

iOS, Windows

### Affected platform versions

net6.0-windows10.0.19041

**Comment by hartez** [comment]
What is the name of the base class you are extending?

**Comment by MuneeshKumarG** [comment]
We have parent layout as 

"internal AbsoluteLayout AnnotationsLayout;"

And we have added View extended class to this parent. Please find the extended class below. 

```
 internal class CustomView : View
    {
        
        public override void Draw(ICanvas canvas, RectangleF dirtyRect)
        {
            base.Draw(canvas, dirtyRect);
        }

    }
```
In run time, this draw override method not getting hit. If I change the parent layout as Grid means, this method getting called correctly.

**Comment by hartez** [comment]
What is the full name of `View`? Is it a `Microsoft.Maui.Controls.View`? Or some other class?

**Comment by MuneeshKumarG** [comment]
Yes. That view is Microsoft.Maui.Controls.View.

**Comment by hartez** [comment]
`Microsoft.Maui.Controls.View` does not have a virtual method that matches the signature `void Draw(ICanvas canvas, RectangleF dirtyRect)`. 

Are you sure that is the class you are extending?

**Comment by MuneeshKumarG** [comment]
Yes. We have used View inherited class and added Draw virtual method in that. When call  handler.Invalidate(), it called the Draw method automatically upto preview 9.

**Comment by hartez** [comment]
Please submit a small project which reproduces the issue, and we will take a look.
Thank you.
