### ISSUE TITLE
Navigation back causing app to crash

### ISSUE THREAD

**Issue by ossimc82** [dotnet/maui#3511]
### Description

**Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'**

When using microsofts dependency injection, the app will crash if you visit a page again after you used the hardware back button of your device.

### Steps to Reproduce

1. Clone the demo project from this git repo: https://github.com/ossimc82/MauiNavigationCrashDemo
2. Run the project.
3. Click "Goto Page1"
4. Press the **_hardware_** back button (not the one in the navigation bar)
5. Again click "Goto Page1"
6. Dead

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Tested on Android 10 and 11

**Comment by PureWeen** [comment]
I tested this with the latest P12 build and it's currently working fine. 

There's a good chance it's also fixed in P11
