### ISSUE TITLE
[WinUI] Parent measure override not called while children collection change in dynamic time

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#3512]
### Description

I have added label in grid in dynamic time. I have set label position in grid extension class measure override method. 

But in WinUI dynamic time children collection change not calling measure override method. 

This issue not reproduced in android and iOS.

### Steps to Reproduce

```
grid.Children.Insert(0, label);

```

```

protected override Size MeasureOverride(double widthConstraint, double heightConstraint)
{
}
```

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

**Comment by MuneeshKumarG** [comment]
In preview 11, this issue reproduce for iOS and Maccatalyst also. 

In android only this issue not reproduced.

**Comment by XamlTest** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
