### ISSUE TITLE
xamarin simulator Failed to install XXX. the app directory does not exists

### ISSUE THREAD

**Issue by ganluo960214** [dotnet/maui#3523]
### Description

xamarin simulator Failed to install XXX. the app directory does not exists

### Steps to Reproduce

vs 2022 preview community
![image](https://user-images.githubusercontent.com/8499204/143003711-7cbf962d-f194-4a74-861b-79a8ca890ff2.png)

create the .net maui app(preview)
<img width="736" alt="image" src="https://user-images.githubusercontent.com/8499204/143003889-8582f4e5-3ffb-4666-a550-aa1f54e37d6b.png">

start debug
![image](https://user-images.githubusercontent.com/8499204/143005175-d875ce92-7824-4825-9fe2-2e26758975ee.png)
![image](https://user-images.githubusercontent.com/8499204/143005234-a299f5ad-343a-4137-947a-00ed99c06836.png)

got a error
<img width="307" alt="image" src="https://user-images.githubusercontent.com/8499204/143005372-7bbe9ae0-eb03-43d8-b647-9bfa37b62364.png">

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios15

**Comment by ganluo960214** [comment]
I do know which version I use. where I can find it.

**Comment by shimingsg** [comment]
Not reproducible with Ipod touch(7 th generation) IOS 15.2.
![image](https://user-images.githubusercontent.com/20982341/154633975-0b2246c4-6832-4df1-b011-891af6c3ae91.png)
