### ISSUE TITLE
Label text disappears in template app

### ISSUE THREAD

**Issue by THoferSchmitz** [dotnet/maui#3524]
### Description

I created a new Maui App and changed it to a Shell application. As a beginner, I diddn't do much yet, I simply made the default MainPage a FlyoutItem in App.xaml and removed the `MainPage = new MainPage()` Code from App.xaml.cs (See Stepps to Reproduce).

I can compile and start this without a problem. But when I click on the Button, the Label disappears and does not reappear after further clicks or waiting some time.

I then added a background color to the Label which does not disappear. So I know it's the text that disappears, not the Label itself. Debugging showed that the text property changed as defined in `OnCounterClicked`.

I also tried adding another MainPage as a second FlyoutItem. When I change to that second page it does not show the same behaviour. Additionally, when changing back to the first page, the text is back and does update when clicking on the Button as expected, there are no more signs of any bugs.

I tried running this on my Android tablet (not emulator), it showed the same behaviour and corrupted the tablet (I will make a second report about that).

### Steps to Reproduce

1. Create a new Maui App
2. Remove `MainPage = new MainPage()` from App.xaml.cs
3. Add ``<Application.MainPage>
        <Shell FlyoutBackgroundColor="Red">
            <FlyoutItem Title="MainPage">
                <ShellContent ContentTemplate="{DataTemplate local:MainPage}"/>
            </FlyoutItem>
            <FlyoutItem Title="MainPage">
                <ShellContent ContentTemplate="{DataTemplate local:MainPage}"/>
            </FlyoutItem>
        </Shell>
    </Application.MainPage>`` to App.xaml (based on WheatherTwentyOne Demo App)

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11, Android (Version unknown due to Problems, I think 9)

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EWRvZqKxepRJhWTRytR6W3ABtWoU45I4ODumZvSdYDjEhw?e=PfRdZ2

**Comment by Redth** [comment]
We believe this is fixed in a newer or upcoming version of MAUI.

Please open a new bug if it's still and issue there.
