### ISSUE TITLE
NuGet Package Update causes issue compiling for non-windows debugging

### ISSUE THREAD

**Issue by kla50** [dotnet/maui#3527]
### Description

NuGet update of the Microsoft.Graphics.Win2D and Microsoft.WindowsAppSDK NuGet packages is not replacing the existing PackageReferences in the conditional ItemGroup in the .csproj file.  This causes a build error when targeting Android device for debugging.

### Steps to Reproduce

1.	Add a new project using the ".NET MAUI App (Preview)" template.
2.	When I open NuGet Package Manager I see the following updates
a.	 
![image](https://user-images.githubusercontent.com/66872908/143059324-60636c47-8e18-42b4-8af0-a0de55d041b3.png)

3.	Select them and then update.
4.	The update is not replacing the PackageReferences in the conditional ItemGroup.  It is adding them to a new ItemGroup.  So the .csproj file looks like this:
5. 
![image](https://user-images.githubusercontent.com/66872908/143059720-fd5b5dcb-f580-4c21-8f43-663d600ec302.png)

5.	This causes the following error when you target an Android device for debugging.
a.	 
![image](https://user-images.githubusercontent.com/66872908/143059851-8284e465-c180-4790-9dcb-a5f3231567ba.png)

6.	If I manually edit the .csproj file and copy the two updated PackageReferences into the Windows conditional ItemGroup replacing the old PackageReferences and delete the ItemGroup created during the NuGet package update, then debugging on Android device starts working again.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Physical Android device with 5.1

### Did you find any workaround?

Manually update the .csproj file moving the updated PackageReferences into the Windows conditional ItemGroup and deleting the ItemGroup created during the NuGet package update.

**Comment by devmikew** [comment]
See #3489. It is a similar problem.

**Comment by devmikew** [comment]
Sorry, it should be #3490 (a copy/paste problem).

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EdPltf3FC4xPtIt92UKj2rIB3kjI2vyC9uvFBcvzjw5TcQ?e=UxBZUh

**Comment by Redth** [comment]
Fixed in latest MAUI Preview.
