### ISSUE TITLE
[Bug] Can't find package 'Microsoft.iOS.Runtime.ios-x64'

### ISSUE THREAD

**Issue by HyEnjoys** [dotnet/maui#353]
I'm sorry, but when I run "dotnet build Sample.iOS-net6.csproj", that I got an error 
**_"Can't find package 'Microsoft.iOS.Runtime.ios-x64' "_**
I'm confused, please help me how to fix it.

**Comment by PureWeen** [comment]
Closing for now

If you're still having issues after P2 then we can re-open
