### ISSUE TITLE
Get xplat element from native view

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#3530]
### Description

In case of WinUI/MAUI apps we need a way to navigate between native elements and xplat elements. Currently we can navigate from native element for xplat via VisualElement.Handler.NativeView. But there is no API to go the reverse way.

### Public API Changes

```csharp
public static class VisualElementExtensions {
  public static VisualElement TryGetNativeElement(object xplatElement);
}
```

### Intended Use-Case

For VS XAML Hot Reload to better support WinUI/MAUI scenarios (and reach parity with UWP/Xamarin) we need a way to get xplat element from native view. Consider UWP/Xamarin screenshot below. In order to show info tips in XAML Live Preview we start by interacting with HWND and UWP app to find a UWP element (LabelRenderer in this case). Next, we ask in-app Xamarin hot reload agent (Xamarin.HotReload.Forms.dll) to provide info tip info for LabelRenderer. The agent then finds underlying Xamarin element (label) via [IVisualElementRenderer](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.UAP/IVisualElementRenderer.cs) and provides all the necessary info.

For similar scenario to work for WinUI/MAUI we need similar way of going from WinUI element to MAUI element.

![image](https://user-images.githubusercontent.com/48451158/143080715-6e06aa47-d90d-4f1e-8f99-d315b8e2febb.png)

**Comment by etvorun** [comment]
This API might not be needed. We think we can do everything needed via `Microsoft.Maui.VisualTreeElementExtensions.GetVisualTreeElements`. We'll know for sure within next 3-4 weeks. We'll update this issue then.

**Comment by StephaneDelcroix** [comment]
> This API might not be needed. We think we can do everything needed via `Microsoft.Maui.VisualTreeElementExtensions.GetVisualTreeElements`. We'll know for sure within next 3-4 weeks. We'll update this issue then.

That would be good. doing the bookkeeping in app would have a measurable perf impact
