### ISSUE TITLE
[BUG] MAUI Blazor App uses MAUI Control in webview

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/maui#3531]
### Description

when I use as example 
```cs
<select>
    <option>Test<option/>
</select>
```
it replaces the html control with the MAUI Control. I also cant click on the it because the select instantly closes.

![23232e2e2323](https://user-images.githubusercontent.com/33988671/143095328-81559422-5f55-4407-b078-72f1c02f51ee.gif)
### Steps to Reproduce

1. Create new MAUI Blazor Application.
2. inside index.razor write the code snippet in description.
3. run the app and click on the select

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No workaround found.

**Comment by Eilon** [comment]
Hi, this is unfortunately a bug in WebView2 in WinUI specifically. You can find more info in the duplicate bug here: https://github.com/dotnet/maui/issues/1353

If you follow various links from that bug you can see the discussions on the WebView2 issue, as well as other options/workarounds.
