### ISSUE TITLE
Border does not size and display properly

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#3541]
### Description

With size:

![image](https://user-images.githubusercontent.com/1096616/143197983-0465d6ea-9cdc-4a9a-a008-266d67627aae.png)

No size:

![image](https://user-images.githubusercontent.com/1096616/143198026-34cb1f02-b39d-4b62-90cc-4541a4616866.png)

### Steps to Reproduce

```xaml

<Border
    GridLayout.Row="0"
    GridLayout.Column="0"
    GridLayout.RowSpan="2"
    WidthRequest="72"
    HeightRequest="72"
    Background="Azure"
    Stroke="Red"
    StrokeThickness="6">
    <Border.StrokeShape>
        <Ellipse />
    </Border.StrokeShape>

    <Label
        Text="{Binding Timestamp, Converter={StaticResource ShortDateConverter}}"
        HorizontalTextAlignment="Center"
        VerticalTextAlignment="Center"
        FontSize="24"
        LineHeight="0.9" />

</Border>
```

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 30

**Comment by mattscheffer** [comment]
Bug is repro in 17.2.0 Preview 1. Tested with API 30 - Android 11.0. Repro project here:
[3541.zip](https://github.com/dotnet/maui/files/8145581/3541.zip)

**Comment by davidortinau** [comment]
The ellipse does paint with or without size, but it's wrong. I'd expect a circle in any case b/c the Grid sizing amounts to 78 square and the Border width/height + Stroke is also 78.

Android with size is a circle, but cut's off. In both cases the no-size XAML results in a collapsed ellipse instead of a 78x78 circle.

Android with size

```
<Grid ColumnDefinitions="78,*,*"
                      RowDefinitions="48,30"
                      ColumnSpacing="20"
                      RowSpacing="0">
                    <Border Grid.Row="0"
                            Grid.Column="0"
                            Grid.RowSpan="2"
                            Background="Azure"
                            Stroke="Red"
                            StrokeThickness="6"
                            WidthRequest="72"
                            HeightRequest="72"
                            HorizontalOptions="Center"
                            VerticalOptions="Center"
                            >
                        <Border.StrokeShape>
                            <Ellipse/>
                        </Border.StrokeShape>
                        <Label Text="Hello"
                               HorizontalOptions="Center"
                               VerticalOptions="Center"
                               FontSize="24"
                               LineHeight="0.9"/>
                    </Border>
                </Grid>
```

<img width="403" alt="image" src="https://user-images.githubusercontent.com/41873/165650905-066c484a-086c-4502-b700-25c11e750535.png">

Android without size

```
<Grid ColumnDefinitions="78,*,*"
                      RowDefinitions="48,30"
                      ColumnSpacing="20"
                      RowSpacing="0">
                    <Border Grid.Row="0"
                            Grid.Column="0"
                            Grid.RowSpan="2"
                            Background="Azure"
                            Stroke="Red"
                            StrokeThickness="6"
                            HorizontalOptions="Center"
                            VerticalOptions="Center"
                            >
                        <Border.StrokeShape>
                            <Ellipse/>
                        </Border.StrokeShape>
                        <Label Text="Hello"
                               HorizontalOptions="Center"
                               VerticalOptions="Center"
                               FontSize="24"
                               LineHeight="0.9"/>
                    </Border>
                </Grid>
```

<img width="400" alt="image" src="https://user-images.githubusercontent.com/41873/165650995-83609811-fd00-4e89-a2bf-d8960e8183c7.png">

Windows with size:

<img width="96" alt="image" src="https://user-images.githubusercontent.com/41873/165651311-f06bf249-7708-4bf9-b6fc-4d9fd94382ce.png">


Windows without size:

<img width="126" alt="image" src="https://user-images.githubusercontent.com/41873/165651212-fcbfcdc9-b2f9-47f7-8369-ff88d58bfe33.png">

**Comment by Redth** [comment]
@davidortinau  or  @samhouts  can you test this again with main builds? 

I think it's working correctly now, seems to for me anyway.

**Comment by VincentBu** [comment]
I tried [davidortinau](https://github.com/davidortinau)'s code with main build(32507.29.main).
On windows:
![image](https://user-images.githubusercontent.com/44959937/167329962-087055a9-45bd-42e9-8273-1c99773731ec.png)

but on Android emulator:
![image](https://user-images.githubusercontent.com/44959937/167330024-dc468e44-5bd7-4ef9-ba3a-f12590cef866.png)

**Comment by samhouts** [comment]
Looks great on 6.0.300-rc.4.5742!
![image](https://user-images.githubusercontent.com/7827070/167677295-22d35544-1a5c-4ce8-8ac4-91c96b2c6a3c.png)
