### ISSUE TITLE
The HideContentFromiOSBundleResources must also run for _CollectHotRestartBundleResources

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#3546]
### Description

Hot restart for iOS uses a different set of targets to collect resources. So we also need to do the same hide target for _CollectHotRestartBundleResources

### Steps to Reproduce

1. dotnet new maui-blazor
2. Hot restart

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

iOS

### Affected platform versions

iOS 14

**Comment by mkArtakMSFT** [comment]
Related PRs:
- https://github.com/dotnet/maui/pull/4187
- https://github.com/dotnet/maui/pull/4185
