### ISSUE TITLE
Namespace names in MAUI.

### ISSUE THREAD

**Issue by devmikew** [dotnet/maui#3548]
### Description

There is a problem with namespace names in MAUI. Eg:
at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)

This is from a stack trace from another issue. It indicates the namespace names are a bit crazy.

See #3500.

This is not the only issue with namespace names across MAUI.

### Steps to Reproduce

Dont know

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

iOS, Windows, NetStandard - all non Android projects

### Did you find any workaround?

no

### Relevant log output

```shell
See #3500.
```

**Comment by devmikew** [comment]
I've been trying to track this down and I can see its isn't in Maui, but in Microsoft.UI.Xaml. 

Sorry, my mistake.

**Comment by jfversluis** [comment]
Thanks for letting us know @devmikew !
