### ISSUE TITLE
VS 17.1.0 Preview 1.1 is using the complete absolute Path for BundleResources for SmartCopy Task for iOS

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#3551]
### Description

SmartCopy-Task is generating wrong path for BundleResources if used from Visual Studio for Windows connected with a Mac:

Instead of cutting of the project path it uses the whole path which incl. drive letter and all. 

>        SmartCopy: 2021-11-25T17:05:07.2018056+01:00 - Creating output 'bin\Debug\net6.0-ios\iossimulator-x64\SimpleDemo.app\D:\git\maui-playground\SimpleDemo\SimpleDemo\Platforms\iOS\Resources\LaunchScreen.xib'...
5>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.0.101-preview.10.251\tools\msbuild\iOS\Xamarin.Shared.targets(1041,3): warning : Das angegebene Pfadformat wird nicht unterstützt.

So, the resources are not copied and are not available during runtime.

### Steps to Reproduce

Create a dotnet maui project on Visual Studio for Windows
Connect with a mac
Deploy on a ios Simulator

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

ios 15 Simulator

### Did you find any workaround?

-

### Relevant log output

```shell
5>        SmartCopy: 2021-11-25T17:05:07.2018056+01:00 - Creating output 'bin\Debug\net6.0-ios\iossimulator-x64\SimpleDemo.app\D:\git\maui-playground\SimpleDemo\SimpleDemo\Platforms\iOS\Resources\LaunchScreen.xib'...
5>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.0.101-preview.10.251\tools\msbuild\iOS\Xamarin.Shared.targets(1041,3): warning : Das angegebene Pfadformat wird nicht unterstützt.
```

**Comment by rogerbriggen** [comment]
It did some more tests:
 It works if you add a BundleResource yourself to the .csproj. 
The error is only for things you add below platforms/iOS/resources which is picked up automatically.

**Comment by v-longmin** [comment]
Verified the issue on windows, VS 17.2.0 preview 2.0 32223.408.main, the issue does not repro.
