### ISSUE TITLE
Layouts are not clip to bounds

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#3554]
### Description

StackLayot is not arranged only within its bounds. It occupies the total screen width.

### Steps to Reproduce

1. Create a sample and place below code in xaml fine.
```<Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="0.5*"/>
            <ColumnDefinition Width="0.5*"/>
        </Grid.ColumnDefinitions>
        <StackLayout Orientation="Horizontal"  GridLayout.Column="0">
            <Button Text="1" Margin="1" HeightRequest="50"/>
            <Button Text="2" Margin="1" HeightRequest="50"/>
            <Button Text="3" Margin="1" HeightRequest="50"/>
            <Button Text="4" Margin="1" HeightRequest="50"/>
            <Button Text="5" Margin="1" HeightRequest="50"/>
            <Button Text="6" Margin="1" HeightRequest="50"/>
            <Button Text="7" Margin="1" HeightRequest="50"/>
            <Button Text="8" Margin="1" HeightRequest="50"/>
        </StackLayout>
        <BoxView GridLayout.Column="1" WidthRequest="500" Background="Red" Opacity="0.5"/>
    </Grid>
```
2. Note that stack layout is not arranged within its bounds and it overlaps on 2nd column above box view.

Output Screenshot for above code
![image](https://user-images.githubusercontent.com/92788387/143535696-30037576-af2e-4d94-92e3-1ae49d0e90a5.png)

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 9.0, Windows SDK 10.0.19041 

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
https://github.com/dotnet/maui/issues/2334 is pending. I am going to include this topic to review and see if we can include it for Preview 11.

**Comment by hartez** [comment]
#3709 makes the layouts all clip by default. Should be available in preview 12.

**Comment by karthikraja-arumugam** [comment]
Hi @jsuarezruiz & @hartez,

If we use the clip property to make the layout clip to its bounds, the view is clipped but the interaction is not restricted.  
For example, 

In column 0 we have a button and column 1 scroll view. The button is cropped to its bounds but we can still click the button from its clipped area.

https://user-images.githubusercontent.com/92788387/146177150-19d7039c-cb28-4876-a128-f03538c2e4be.mp4

Can you please make sure this also will be fixed in Preview 12?

**Comment by Sasikumar3595** [comment]
@hartez and @jsuarezruiz,

We are facing the same issue while creating the custom layout. If we use the clip property to clip the custom layout based on its bounds, but in iOS and Mac, pan gesture does not working for the custom layout.

**Comment by hartez** [comment]
> #3709 makes the layouts all clip by default. Should be available in preview 12.

Update - after some review, layouts will remain _unclipped_ by default (same as in Forms); setting `IsClippedToBounds = true` will force them to clip.

**Comment by karthikraja-arumugam** [comment]
Hi @hartez,
We are still facing this issue in preview 12.
