### ISSUE TITLE
Broken Links on <> Code page of this repo for "Contributing"

### ISSUE THREAD

**Issue by pfafft33** [dotnet/maui#356]
### Description
At the bottom of the <> Code page of this repo, there are 2 links to find info about "Contributing".
Both of those links are broken, and display a 404 error.

### Steps to Reproduce

1. Go to the dotnet/maui repo
2. Click on the <> Code page
3. Scroll down to the bottom
4. Click on either of the links that are supposed to send you to info about "Contributing".
5. The 404 error occurs

### Expected Behavior
It is expected that the links would send you to an existing page about "Contributing".

### Actual Behavior
The 404 error occurs

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
Thank you for the heads up
Should be fixed now
