### ISSUE TITLE
Animation RelRotateTo Behaves different on windows and android

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#3560]
### Description

Animation **RelRotateTo** Behaves different on windows and android

If you rotate an image using animation extensions:
The center of rotation on windows is the center of the image.
On Android it is the upper left corner.

Expected behavior: consistent across platforms.

### Steps to Reproduce

1:  create a maui app, add an image on the screen (myImage)
2: inside a button event, call the animation extension function:
**myImage.RelRotateTo(45,250, Easing.CubicOut);**

3: On android the center of rotation is the upper left corner
4: On Windows the center of rotation is the center of the image

Expected behavior: The default center of rotation should be consistent across platforms.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11 API 30 - Windows 11 Pro 22000.348

**Comment by pierre01** [comment]
Update: All rotations are affected . relative or not

**Comment by stefanbogaard86** [comment]
Have the same issue with animations on android. 

On android:
https://user-images.githubusercontent.com/15085413/143775442-d214a099-6663-4f29-b659-fc887d6ecfe9.mp4

On windows:
https://user-images.githubusercontent.com/15085413/143775470-95f29f98-c46d-4069-85e7-63e586576c0d.mp4

**Comment by AmrAlSayed0** [comment]
@pierre01 I think AnchorX and AnchorY take values from 0 to 1 not a pixel value. At least it was that way in Xamarin.Forms

**Comment by pierre01** [comment]
> @pierre01 I think AnchorX and AnchorY take values from 0 to 1 not a pixel value. At least it was that way in Xamarin.Forms

You are right : I played with the Anchor property and values of 1 and 0 will move the center of rotation to different corners on Android.
BUT
**Anchor values under 1 are rounded to 0;**
so **the bug might very well be a rounding issue** as and anchor of  0.5 , 0.5 is considered as 0,0
I tried anchors of 1,0  or 0,1 or 1,1 or 0,0 and they work.

**Comment by pierre01** [comment]
it seems that on Android : 
**AnchorX and AnchorY are rounded or casted to int values**

**Comment by jsuarezruiz** [comment]
Could you attach a sample where reproduce the issue?. Thanks!
![issue3560](https://user-images.githubusercontent.com/6755973/144451854-6d7d01ef-a955-4de7-9695-b107aeb3392c.gif)

**Comment by pierre01** [comment]
Here you have the same exact code running on Android and Windows (code shown between window

https://user-images.githubusercontent.com/2603287/144583657-94829e67-3e59-4faa-9ab7-e10eaac5a7dc.mp4

s)

**Comment by pierre01** [comment]
Do you still need more info? 
I send you code and video of the issue and hints of where the bug can be originating 21 days ago.

**Comment by pierre01** [comment]
May be it has to do with the easing functions. I saw the code in 
https://github.com/dotnet/maui/blob/6.0.101-preview.11.3/src/Core/src/Animations/Easing.cs
and double numbers input are casted in floats during calculations. Just a hunch.

**Comment by Clancey** [comment]
This has nothing to do with the easing/animation casting. It had to do with the rotation point.

**Comment by pierre01** [comment]
> This has nothing to do with the easing/animation casting. It had to do with the rotation point.

Thanks, I thought so, I just was wondering why @jsuarezruiz  posted a sample that works in his video.

**Comment by hartez** [comment]
> Thanks, I thought so, I just was wondering why @jsuarezruiz posted a sample that works in his video.

Because it seems to work just fine. I've tried using exactly the code you posted in your video, and I'm not seeing the same error (see the gif below). Could you please put a minimal project up on GitHub which demonstrates the issue and add a link to it here? It's possible that we're missing an important detail that's crucial to reproducing the issue. 

![2021-12-27_16-10-26](https://user-images.githubusercontent.com/538025/147513148-98789482-768b-4856-a7f5-ae09f79667f7.gif)

**Comment by pierre01** [comment]
@hartez @jsuarezruiz Here is a repo where I reproduced the issue.
I am running Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.1.0 Preview 1.1
MAUI Preview 10

https://github.com/pierre01/RelRotateTest

**Comment by pierre01** [comment]
This issue can be closed, I verified that it works now on android and windows with MAUI preview 12
