### ISSUE TITLE
Touch does not pass to parent when it child is scroll view

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#3561]
### Description

I was create the custom layout that have pan gesture and i was added the scroll view as it child. Touch was not passed to custom layout when scroll view reaches it end position.

### Steps to Reproduce

1. Create a custom layout and add pan gesture to the layout
2. Add the child as scroll view
3. Touch does not passed to custom layout when the scroll view reaches it end.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

iOS 15 Android 30

### Did you find any workaround?

No

**Comment by wenwen60** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
