### ISSUE TITLE
[Bug] [Android] Incorrect spacing of components inside Frame

### ISSUE THREAD

**Issue by LarsBehl** [dotnet/maui#3568]
### Description

When using a `Frame` which contains a `VerticalStackLayout` containing one `Label` with a `FontSize` set to another value than default and some other component, the vertical spacing of the components is incorrect. A repro can be found [here](https://github.com/LarsBehl/MauiFrameSpacing).

## Expected behaviour
![image](https://user-images.githubusercontent.com/26459044/143613026-6d5e456b-7ecf-4fb6-87a5-94e5c265a8dd.png)

## Actual behaviour
![image](https://user-images.githubusercontent.com/26459044/143613063-7239f812-5ece-42a1-a893-7a9850853f2e.png)

### Steps to Reproduce

1. Create new Maui project
2. Replace content of `MainPage` with `VerticalStackLayout`
3. Add `Frame` to `VerticalStackLayout`
4. Add `VerticalStackLayout` to `Frame`
5. Add `Label` with some text to inner `VerticalStackLayout`
6. Change the `FontSize` of `Label` to some other value
7. Add another `Label`

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11/API 30, Android 9/API 28

**Comment by PineYi** [comment]
Reproduce in Android with above project.

**Comment by PineYi** [comment]
Not reproducible with Android 11.

**Comment by hartez** [comment]
@PineYi is it verified, or is it not reproducible?
