### ISSUE TITLE
Back navigation doesn't work for modal pages on a windows app.

### ISSUE THREAD

**Issue by spencerparkin** [dotnet/maui#3572]
### Description

The PopModalAsync() call is failing by throwing an exception when awaited from a modal page's event handler.

The exception details follow...

System.Runtime.InteropServices.COMException
  HResult=0x800F1000
  Message=No installed components were detected.

  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.DelegateExtensions.DynamicInvokeAbi(Delegate del, Object[] invoke_params)
   at ABI.System.Collections.Generic.IList`1.global::Windows.Foundation.Collections.IVector<T>.Append(T value)
   at ABI.System.Collections.Generic.IList`1.FromAbiHelper.Add(T item)
   at ABI.System.Collections.Generic.ICollection`1.global::System.Collections.Generic.ICollection<T>.Add(T item)
   at Microsoft.UI.Xaml.Controls.UIElementCollection.Add(UIElement item)
   at Microsoft.Maui.Controls.Platform.ModalNavigationManager.AddPage(Page page)
   at Microsoft.Maui.Controls.Platform.ModalNavigationManager.SetCurrent(Page newPage, Page previousPage, Boolean popping, Action completedCallback)
   at Microsoft.Maui.Controls.Platform.ModalNavigationManager.PopModalAsync(Boolean animated)
   at Microsoft.Maui.Controls.Window.NavigationImpl.<OnPopModal>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FifteenPuzzle.SettingsPage.<OnBackButtonClicked>d__1.MoveNext() in C:\git_repos\FifteenPuzzleApp\SettingsPage.xaml.cs:line 23

  This exception was originally thrown at this call stack:
    [External Code]
    FifteenPuzzle.SettingsPage.OnBackButtonClicked(object, System.EventArgs) in SettingsPage.xaml.cs

### Steps to Reproduce

1) Clone https://github.com/spencerparkin/FifteenPuzzleApp
2) Open solution, compile and run for windows platform.  (It should compile easily and quickly out-of-the-box.)
3) Click the options button to bring up the options page (not yet fleshed out.)
4) Hit the "Go back" button to see it crash.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No.

### Relevant log output

```shell
'FifteenPuzzle.exe' (CoreCLR: clrhost): Loaded 'c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xamarin\hotreload\protobuf-net.Core.dll'. 
'FifteenPuzzle.exe' (CoreCLR: clrhost): Loaded 'C:\git_repos\FifteenPuzzleApp\bin\Debug\net6.0-windows10.0.19041\win-x64\AppX\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x3694 has exited with code 0 (0x0).
The thread 0x382c has exited with code 0 (0x0).
The thread 0x3774 has exited with code 0 (0x0).
The thread 0x2f80 has exited with code 0 (0x0).
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
An exception of type 'System.Runtime.InteropServices.COMException' occurred in System.Private.CoreLib.dll but was not handled in user code
No installed components were detected.

'FifteenPuzzle.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

**Comment by spencerparkin** [comment]
Additional observation...

The await call that pushes the modal page doesn't block while the modal dialog is in play.  Isn't that to be the expected behavior?

**Comment by spencerparkin** [comment]
Additional note...

I just tested this on my phone (Android API 29), and the back button on the modal page works fine.  So the code I currently have might be correct, but it just doesn't work on Windows.

**Comment by spencerparkin** [comment]
I just fixed a crash bug for my app on windows that prevented it from coming up.  It comes up now so that the bug cited here can be repro'd.

**Comment by spencerparkin** [comment]
I just tested my app on an emulated tablet device and, oddly, you have to push the back-button twice to get the modal dialog to go away.  From Windows, to phone to tablet, they're all running the same code to bring up the dialog and then dismiss it, so my feeling is that the bug is in the framework, not the app code, but of course, I could always be wrong.

**Comment by spencerparkin** [comment]
One more message for the black hole...

Testing on my physical Android device, I can remove the "async" and "await" keywords from the code that pops up the modal page and the code that dismisses the modal page, and everything works just the same.  That is, if running a debug build of the app.  If I run in release, then it crashes, with or without those keywords.

Lots of problems with modal pages in .NET MAUI.

**Comment by v-xiaofchen** [comment]
Not reproducible with 17.2.0 Preview 2.0 [32209.335.main] using Windows. Not crush when hit the "Go back" button .Can come back to the last page.
![Picture17](https://user-images.githubusercontent.com/99376012/155681786-f265a0b8-daf5-49ff-bd90-8a1d0cc2961a.png)
![Picture18](https://user-images.githubusercontent.com/99376012/155681814-06bc3b38-6c82-4a3c-9aec-f022531f6a70.png)

**Comment by spencerparkin** [comment]
Thanks for looking at that.  I am running VS 2022, Version 17.1.0, Preview
5.0.  I'll try to see about upgrading.

It seems, though, that VS 2022 is so demanding on the hardware, that I need
to upgrade my PC as well.
