### ISSUE TITLE
RCL css bundle 404 not found 

### ISSUE THREAD

**Issue by wizd** [dotnet/maui#3578]
### Description

can't access RCL css isolation boundle css from url specified by [link](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0#razor-class-library-rcl-support), F12 tools show the resource is not found. (404 error).

walk around: copy the css from normal project, add to MAUI project's wwwroot, and update the link.

### Steps to Reproduce

1, create RCL;
2, create css;
3, reference the assembly from MAUI project;
4, load and run, F12 to see a 404 error that the ...boundle.scp.css is not found.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

windows 10.0.19041

### Did you find any workaround?

copy the css from normal project (via F12 tools), add to MAUI project's wwwroot, and update the link.

**Comment by Eilon** [comment]
Can you provide a repro project in a GitHub repo that we can take a look at? We need to see how the CSS is being referenced, and from what file.

In general with Scoped CSS you shouldn't need to reference the `Xyz.scp.css` file. It will be automatically included when you reference the app's main generated CSS file, which would usually be something like `MyAppName.styles.css` from the main `wwwroot/index.html` file.

**Comment by wizd** [comment]
sure. I created a project to demonstrate the bug. I added a simple button to the counter page. the button was from Blazorised components library. the component assembly contains many resource which can't be loaded by MAUI properly. when navigated to the counter page, an unhandled error will be thrown out. 

demo: https://github.com/wizd/MauiApp1

**Comment by Eilon** [comment]
@wizd thank you for posting the app, we'll take a look.

**Comment by Eilon** [comment]
Hi @wizd , I took a look at this and this is a dup of bug https://github.com/dotnet/maui/issues/3288. Right now there's a bug where a Razor Class Library that also has UseMaui=true doesn't work.
