### ISSUE TITLE
Error Reusing Blazor Hosted Wasm in Blazor App MAUI Project

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#3581]
I am using Visual Studio 2022 Version 17.1.0 Preview 1.1

I have an existing Blazor Wasm Hosted App that i want to publish to Apple App Store and Google app Store.

I added .NET MAUI Blazor App(Preview) to my existing Blazor Hosted WASM Solution.

![SolutionExplorer1](https://user-images.githubusercontent.com/3267605/143791928-8582ec2f-32c9-4571-b576-dae51e0abc36.png)

![SolutionExplorer](https://user-images.githubusercontent.com/3267605/143791967-0e03a5ee-580d-4711-b753-1ebbbb35245b.png)
In MAUI Project i added the Project Reference to Blazor client Project. 
I have set MAUI as startup Project and in that i configured to run as windows desktop.
I am running into few Errors as show hereunder. These error don't show when using Blazor Hosted wasm.
![MAUI Error 1](https://user-images.githubusercontent.com/3267605/143798575-6c42a2e0-85f1-4ed9-bdbf-9fdc777ab6b3.png)

if i set the project reference to the Server Project in MAUI Project, i still get different errors.

![MAUI Error 3](https://user-images.githubusercontent.com/3267605/143824318-8b664f42-0a18-4eab-94a9-3eb739a3800b.png)

I want to confirm first whether i did the setup correctly ?
Secondly how do i overcome the Build/Deploy errors ?

A side Question, when using WebView in MAUI, can i refer to Remote deployed Blazor App ? 
if that works i don't need to include additional projects in my solutions.

Also for someone new to Mobile device Platform and one who is coming from Web Development, it would be helpful to have document on how to publish it to AppStore and Playstore as well.

**Comment by Eilon** [comment]
Hi @nssidhu , for this scenario it's best to move the Razor components into a Razor Class Library (RCL) project and then reference that RCL from the Blazor WASM and .NET MAUI Blazor projects.

We will work on getting a doc published on this to clarify what to do.

**Comment by nssidhu** [comment]
will appreciate also if docs could include all the necessary steps on publishing to Apple Store and Google Play Store.

**Comment by Eilon** [comment]
Indeed, we are working on docs for many areas of .NET MAUI. Many things are the same as they were in Xamarin.Forms so you can often refer to those docs, but of course some things are different.

With a regular .NET MAUI WebView you can point it at any remote URL and it shows whatever content is there, for example, www.microsoft.com or your own site. It doesn't matter what the site was built with - it's all HTML, JS, CSS, etc.

**Comment by nssidhu** [comment]
@Eilon 

I tried loading remote site(which is Blazor Hosted WASM) and it failed to load with the following error.
```

    <b:BlazorWebView HostPage="https://xxxxxxxt/index.html">
        <b:BlazorWebView.RootComponents>
            <b:RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
        </b:BlazorWebView.RootComponents>
    </b:BlazorWebView>
```

![MAUI Error](https://user-images.githubusercontent.com/3267605/143977261-eb374e70-bf9a-4599-bcc5-1d86587887af.png)

Could you please post what correct settings would look like to remotely deployed Balzor Hosted WASM & Blazor Server ?

**Comment by nssidhu** [comment]
I was able to show website using WebView in place of BlazorWebView

<WebView x:Name="MyWebView"  Grid.Row="1" Grid.ColumnSpan="2"
                Source="https://microsoft.com" />

**Comment by Eilon** [comment]
The `BlazorWebView` control is for _locally_ hosting Blazor components that run natively on the device. You can't use it for loading a remote web site.

For hosting a remote web site (_any_ web site), use the `WebView` control.

**Comment by nssidhu** [comment]
@Eilon  
Will Blazor Components Downloaded via WebView also run at same performance(i.e. at native speed or they have to execute via some interop's) ?

**Comment by mkArtakMSFT** [comment]
Closing as there is no further action pending here.
