### ISSUE TITLE
[Bug] Custom font not working when used inside a custom library

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#3584]
### Description

Created a custom font ttf file and used that file under Resources/Fonts of a custom library class and set that font to a canvas.fontname. The font is not recognised and rendered as boxes.

Tested in Android and Windows

### Steps to Reproduce

Create a library project and attach a font file [.ttf]. Use that font to a canvas and draw string inside the custom library.

`public override void Draw(ICanvas canvas, RectangleF dirtyRect)
        {
            base.Draw(canvas, dirtyRect);
            canvas.StrokeColor = Colors.Red;
            canvas.FontSize = 12;
            
            canvas.FontName = "BadgeIcons.ttf#Badge icon";
            canvas.FontColor = Colors.Red;

            var textBounds = new RectangleF();
            textBounds.X = 5;
            textBounds.Y = 5;
            textBounds.Right = 20;
            textBounds.Bottom = 20;
            textBounds.Width = 15;
            textBounds.Height = 15;

            canvas.DrawString("\ue701", textBounds, HorizontalAlignment.Center, VerticalAlignment.Center, TextFlow.ClipBounds, 0);
        }`

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by shimingsg** [comment]
@PaulAnderson02 , thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project that we can reproduce your issue? That should greatly speed up the process, thanks!
