### ISSUE TITLE
DefaultLanguage property

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3596]
### Description

Hi,

Please add DefaultLanguage property to the Entry and Editor to set the default keyboard language because the majority of users have more than one language.

### Public API Changes

`DefualtLanguage="en"`

### Intended Use-Case

When the app is multilingual and needs to avoid entering wrong values, for example, if the app uses Arabic and English and need to make sure the TextEnglishName has English Values and TextArabicName has only Arabic.

It will also be great if it's possible to add an option to prevent the user from changing the language if I want only Arabic characters. be entrered.

**Comment by jfversluis** [comment]
Maybe I'm not understanding it correctly but this seems like a very specific use-case and also not really a good idea imo. As a user I hate being limited in this way. I don't have a thorough understanding of Arabic, but even in Dutch some things simply aren't translated. I can imagine that's the same for Arabic and users will find scenarios where you can't get around entering other characters.

Either way, like I said, this use-case seems very specific and feels to me like something that needs to be implemented on the .NET MAUI consumer side or maybe a third-party library. I don't think this will be a priority for us in the foreseeable future.

Thanks for the suggestion!

**Comment by jrahma** [comment]
Thanks @jfversluis 

This is not specific for Arabic but for any multi or single language app.

For example if the app uses Chineese only and the user has two keyboards (English and Chineese) then the developer wants to force chineese keyboard for the Entry or Editor for example

Same thing when the user has something like this:

English First Name
English Last NAme
Arabic First Name
Arabic Last NAme

so the keyboard when it's inside the English should default to English and when it's inside the Arabic it should default to Arabic language.
