### ISSUE TITLE
Device.InvokeOnMainThreadAsync() throws when called from background thread

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#3597]
### Description

BlazorWebView uses `Device.InvokeOnMainThreadAsync` to ensure user UI code runs on the UI thread. This seems to fail at least on Windows, throwing this exception `"BindableObject was not instantiated on a thread with a dispatcher nor does the current application have a dispatcher."`:

https://github.com/dotnet/maui/blob/9b3b888abd08fba83682f7d79234ae87169ce40a/src/Controls/src/Core/DispatcherExtensions.cs#L29

### Steps to Reproduce

1. Create any new MAUI app, add a button to it
2. Add this code to the button's event handler:
   ```c#
			var newThread = new System.Threading.Thread(() =>
			{
				Device.InvokeOnMainThreadAsync(async () => // <--- this line throws, saying it can't find the dispatcher
				{
					await Task.Delay(0);
				});
			});
			newThread.Start();
   ```

### Version with bug

Preview 11

### Last version that worked well

Preview 10 (current)

### Affected platforms

Windows

### Affected platform versions

N/A

### Did you find any workaround?

`Application.Current.Dispatcher.Dispatch()` seems to work fine:

   ```c#
			var newThread = new System.Threading.Thread(() =>
			{
				Application.Current.Dispatcher.Dispatch(() =>
				{
					Thread.Sleep(0);
				});
			});
			newThread.Start();
   ```

**Comment by Eilon** [comment]
Tagging @mattleibow who made some changes here recently.

**Comment by mattleibow** [comment]
Interesting... `Device.InvokeOnMainThreadAsync` should be using the application just like in the workaround.

**Comment by Eilon** [comment]
```
System.InvalidOperationException
  HResult=0x80131509
  Message=BindableObject was not instantiated on a thread with a dispatcher nor does the current application have a dispatcher.
  Source=Microsoft.Maui.Controls
  StackTrace:
   at Microsoft.Maui.Controls.DispatcherExtensions.FindDispatcher(BindableObject bindableObject) in C:\GitHub\maui\src\Controls\src\Core\DispatcherExtensions.cs:line 30

>	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.DispatcherExtensions.FindDispatcher(Microsoft.Maui.Controls.BindableObject bindableObject = {Maui.Controls.Sample.XamlApp}) Line 29	C#
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Device.InvokeOnMainThreadAsync(System.Func<System.Threading.Tasks.Task> funcTask = {Method = {System.Reflection.RuntimeMethodInfo}}) Line 91	C#
 	Maui.Controls.Sample.dll!Maui.Controls.Sample.Pages.ButtonPage.OnIncreasingSpacing.AnonymousMethod__3_0() Line 45	C#
 	System.Private.CoreLib.dll!System.Threading.Thread.StartCallback()	Unknown
 	[Native to Managed Transition]	
 	kernel32.dll!00007ffb0b3d54e0()	Unknown
 	ntdll.dll!00007ffb0d26485b()	Unknown

```
