### ISSUE TITLE
DisconnectHandler is never called 

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#3604]
### Description

I created a Custom Control that inherits from `ElementHandler` and at the moment that the control is closed the `DisconnectHandler` method isn't called, even if I set the `VirtualView.Handler` to `null`.

### Steps to Reproduce

1. Add breakpoints [here](https://github.com/CommunityToolkit/Maui/blob/pj%2Fpopup-port/src/CommunityToolkit.Maui/Views/Popup/Android/PopUpViewHandler.android.cs#L94)
2. Start the sample app
2. Scroll to the bottom and press the button
3. See the popup
4. Click outside the popup to close it
5. The `DisconnectHandler ` isn't called

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by J-Swift** [comment]
Just ran into this when writing a custom handler that extends `PageHandler` on iOS. I assume I'm leaking event subscriptions because of it, but I haven't tested.

**Comment by pictos** [comment]
Hey @kristinx0211, here's the link for the light repro: https://github.com/pictos/MauiBugRepro/tree/DisconnectHandlerNotCalled

**Comment by VincentBu** [comment]
Hi @pictos , Could you give more details about repro steps for [MauiBugRepro](https://github.com/pictos/MauiBugRepro/tree/DisconnectHandlerNotCalled)?

**Comment by pictos** [comment]
@VincentBu , sure.
1. Checkout this [branch](https://github.com/pictos/MauiBugRepro/tree/DisconnectHandlerNotCalled) and run the sample app;
2. Add a breakpoint [here](https://github.com/pictos/MauiBugRepro/blob/DisconnectHandlerNotCalled/MauiBugRepro/CustomEntryHandler.cs#L16) to make sure that the sample is using the `CustomEntryHandler`
3. If you run on iOS add a breakpoint [here](https://github.com/pictos/MauiBugRepro/blob/DisconnectHandlerNotCalled/MauiBugRepro/CustomEntryHandler.cs#L22) if you're on Android add a breaking point [here](https://github.com/pictos/MauiBugRepro/blob/DisconnectHandlerNotCalled/MauiBugRepro/CustomEntryHandler.cs#L27)
4. Click on the Button with the Text `Navigate to Next Page`
5. The breakpoint on `CustomEntryHandler ctor` should be triggered, just press `Continue`
6. Navigate back to the previous page
7. The breakpoints on the `DisconnectHandler` will not be triggered. But they should, no?

**Comment by VincentBu** [comment]
@pictos  you are right. `DisconnectHandler` isn't triggered on Android emulator. @kristinx0211 , Could you repro this on IOS emulator?

**Comment by kristinx0211** [comment]
repro on iPhone13 IOS 15.2. BR can't be hit when navigate back, repro  sample:
[MauiApp2.zip](https://github.com/dotnet/maui/files/8301364/MauiApp2.zip)

**Comment by PureWeen** [comment]
@pictos Do you still need DisconnectHandler here? Can you use the new Loaded/Unloaded events to know when to unsubscribe or call DisconnectHandler yourself?

**Comment by pictos** [comment]
@PureWeen would be good if the .NET MAUI does that for me (lazy developer mode on), but it's fine if I've to call the `DisconnectHandler` myself.

**Comment by PureWeen** [comment]
I'm going to close this issue for now. 

The current behavior for MAUI is to not automatically call `DisconnectHandler` as we can't predict when users might want resources cleaned up. 

I suspect we'll need to eventually add some helpers or possibly lifecycle properties so users can tie Disconnect to being attached/detached from a window

**Comment by J-Swift** [comment]
Thats really surprising : counterintuitive. Isnt that the whole point of connect/disconnect, that I want my resources cleaned up at that point? I dont put anything in those blocks if I dont want that. Especially because ConnectHandler is where you attach touch handlers etc as far as Im aware, I think its a recipe for surprising behavior and memory leaking.

**Comment by pictos** [comment]
@PureWeen will you create the issue about the lifecycle properties?

**Comment by MichaelRumpler** [comment]
> The current behavior for MAUI is to not automatically call `DisconnectHandler` as we can't predict when users might want resources cleaned up.

I want to clean up when the platform view is not needed anymore. Where would I put that code if not in `DisconnectHandler`? What was the intention of `DisconnectHandler` if not for that purpose?

**Comment by PureWeen** [comment]
@MichaelRumpler `DisconnectHandler` is used to cleanup the resource but we can't make assumptions about when the user will want that to happen. Us assuming when to disconnect a handler works for one set of problems but then messes up another set.

**Comment by PureWeen** [comment]
@pictos yea this is definitely going to become a [thing ](https://github.com/dotnet/maui/pull/7349#discussion_r878484367) :-)

An issue and some design docs around current recommendations will definitely be in order.
