### ISSUE TITLE
Feature parity with Xamarin.Forms on Popups

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#3616]
### Description

Currently Xamarin.Forms support following Popups:

1. DisplayToastAsync
2. DisplayActionSheet
3. DisplayAlert
4. DisplayPromptAsync
5. DisplaySnackBarAsync

The .NET MAUI only have the following:

1. DisplayActionSheet
2. DisplayAlert
3. DisplayPromptAsync

The missing Popups are `DisplayToastAsync` and `DisplaySnackBarAsync`.  

### Public API Changes

Add support for  `DisplayToastAsync` and 'DisplaySnackBarAsync`. 

### Intended Use-Case

All these Popups have their usability in different scenarios. Thus remaining ones should also be included in the Maui Popups.

**Comment by hartez** [comment]
> The missing Popups are `DisplayToastAsync` and `DisplaySnackBarAsync`.

Aren't these part of https://github.com/xamarin/XamarinCommunityToolkit ? I don't think Toast and SnackBar are in the main Xamarin.Forms repo.

**Comment by pictos** [comment]
@hartez you're correct. These APIs are in XCT

**Comment by VladislavAntonyuk** [comment]
@HobDev you can already try snackbar with https://github.com/CommunityToolkit/Maui . Toast will be added a bit later

**Comment by HobDev** [comment]
@hartez @pictos @VladislavAntonyuk  I didn't see that. Thank you for the information.
