### ISSUE TITLE
NetworkInterface.GetAllNetworkInterfaces() on Android leads to FileNotFoundException ('/etc/resolv.conf')

### ISSUE THREAD

**Issue by dos-ise** [dotnet/maui#3617]
### Description

Hi,

we tried to port our Xamarin.Forms app to MAUI and encountered a bug.

When calling System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces() we get an FileNotFoundException
On Windows this works.

![image](https://user-images.githubusercontent.com/20043350/144380555-3b949a8d-b002-46d7-b925-d90f03077ce9.png)

Callstack
`{System.Net.NetworkInformation.NetworkInformationException (0x80004005): Success
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetAllNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()
   at Busmonitor.MAUI.MainPageViewModel.Discover() in C:\git\Busmonitor\Busmonitor.MAUI\ViewModels\MainPageViewModel.cs:line 70}`

Best regards

### Steps to Reproduce

1. In MAUI Template add NetworkInterface.GetAllNetworkInterfaces() to Button Handler 
2. On Executing the code a file  System.IO.FileNotFoundException: 'Could not find file '/etc/resolv.conf'.' get thrown

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

no

**Comment by AmrAlSayed0** [comment]
The correct place for this issue is probably [dotnet/runtime](https://github.com/dotnet/runtime). That's where this [code](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxNetworkInterface.cs#L72) is.

Are you by any chance running this on an Android emulator running on a Mac?

**Comment by spektor56** [comment]
I have the same issue, works fine in my Xamarin.android project.  The debugger doesn't work at all for .net Android projects that use async enumerables, had to write the exception to a file to be able to see what was going on.  Visual studio 2022 just detaches itself

**Comment by dos-ise** [comment]
No, this is running on an Pixel Phone attached via USB.

**Comment by dos-ise** [comment]
After looking at the code you linked I think there is no way this code could every run on android.
The implementation completely relies on parsing the resolv.conf file. Which is not available on android. 
I think this is also not available on some linux distros and I am not sure if this is available on iOS.

[https://github.com/dotnet/runtime/blob/b201a16e1a642f9532c8ea4e42d23af8f4484a36/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxNetworkInterface.cs#L56](ParseResolveFile)

The mono implementation on the other hand seems much better here.
[https://github.com/mono/mono/blob/bdd772531d379b4e78593587d15113c37edd4a64/mcs/class/System/System.Net.NetworkInformation/LinuxNetworkInterface.cs#L64](mono)

**Comment by dos-ise** [comment]
https://github.com/dotnet/runtime/pull/62780

This seems to fix the problem when merged.
