### ISSUE TITLE
Boilerplate MAUI project on a clean 17.1.0 Preview 1.1 install doesn't compile; missing components

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3624]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Boilerplate-MAUI-project-on-a-clean-171/1589247)._

---
[severity:I'm unable to use this version]
I completely uninstalled VS 2019 and VS 2022 17.1.0 Preview 1.1 that I had before.
I then restarted the machine (just in case).

I cleanly installed a brand new VS 2022 17.1.0 Preview 1.1 including the Mobile workload.

File -> New Project -> .NET MAUI App (Preview)
The app as it is does not compile.

Then followed advice on similar issues, running `dotnet workload install maui` which resulted in this error:

![image.png](https://aka.ms/dc/image?name=B25a907cd175c495fbf54b9fcb38dc953637728437659413526_20211119-014925-image.png&tid=25a907cd175c495fbf54b9fcb38dc953637728437659413526)

And then trying `maui-check` which resulted in this error:

![image.png](https://aka.ms/dc/image?name=Bf407d1a057e44ed3ad01ba0a56711577637728437993326712_20211119-014959-image.png&tid=f407d1a057e44ed3ad01ba0a56711577637728437993326712)

Tried answering Y (despite the advice on the screen not to do it since other avenues didn't work), but that didn't work as well.

---
#### Feedback Bot on 11/18/2021, 05:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by oferze** [comment]
The bot that migrated this from Developer Community did not migrate the images.

These are the 2 images missing on the issue description, respectively:

![image](https://user-images.githubusercontent.com/5157769/145137270-8bb7f924-0451-4ac4-a984-2975f4ef871a.png)

![image](https://user-images.githubusercontent.com/5157769/145137275-bd61f465-1e10-4f6f-aaea-8bbd5461f3bc.png)

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.

**Comment by oferze** [comment]
Yep, fixed!
