### ISSUE TITLE
.NET Maui application throws System.DllNotFoundException for Microsoft.ui.xaml.dll

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3626]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-Maui-application-throws-SystemDllN/1597649)._

---
[severity:I'm unable to use this version]
Full message:

System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=MauiApp2
  StackTrace:
   at MauiApp2.WinUI.Program.XamlCheckProcessRequirements()
   at MauiApp2.WinUI.Program.Main(String[] args) in D:\Projects\MAUI\MauiApp2\obj\Debug\net6.0-windows10.0.19041\win-x64\Platforms\Windows\App.g.i.cs:line 28

---
#### dharber on 11/28/2021, 09:02 PM: 

<p>Visual Studio Community 2022<br>
Version 17.1.0 Preview 1.1</p>
<p>.NET MAUI Preview 10</p>
<p>Only affects Windows version of app</p>

#### Feedback Bot on 11/29/2021, 00:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AArnott** [comment]
This repros for me with 17.1.0 Preview 3 (32102.18.main)

**Comment by AArnott** [comment]
Note that due to #3923, this happens after a CLI build with this command line:
```
msbuild /r -p:targetframework=net6.0-windows10.0.19041 -v:m
```

Running the generated .exe does nothing apparently. So when I try running the .dll with dotnet.exe, that's when I see the error given in the issue description.

```
> dotnet C:\temp\MauiApp1\MauiApp1\bin\Debug\net6.0-windows10.0.19041\win10-x64\MauiApp1.dll
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at MauiApp1.WinUI.Program.XamlCheckProcessRequirements()
   at MauiApp1.WinUI.Program.Main(String[] args) in C:\temp\MauiApp1\MauiApp1\obj\Debug\net6.0-windows10.0.19041\win10-x64\Platforms\Windows\App.g.i.cs:line 28
```

**Comment by ewendeng** [comment]
I has same problem with debug windows app.

**Comment by AaronViviano** [comment]
I have the same issue with a Release build for a Windows Blazor app with VS 17.2.0 Preview 1.0. I built the application from Visual Studio directly.

**Comment by AArnott** [comment]
@ewendeng @AaronViviano You can help to get traction on the issue by up-voting with a 'thumbs up' on the issue description itself.

**Comment by andyabarnard** [comment]
Same issue here.  It seems to be trying to load DLLs from the WinUI library, but even after following the instructions [here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b) to install WinUI 3, nothing changes.  It seems to leave me unable to use Navigation properly, as no pages will load.  The constructor for the next page is called, but the UI itself isn't updated.

**Comment by amandas-slabsys** [comment]
I am having this issue as well.
Visual Studio Enterprise 2022 17.2 Preview 1.0
.NET MAUI Preview 13
Only affects Windows version of app

Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)

**Comment by v-longmin** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by amandas-slabsys** [comment]
```
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=CashFlow
  StackTrace:
   at CashFlow.WinUI.Program.XamlCheckProcessRequirements()
   at CashFlow.WinUI.Program.Main(String[] args) in C:\Users\amand\source\repos\cashflowapp\CashFlow\obj\Debug\net6.0-windows10.0.17763\win-x64\Platforms\Windows\App.g.i.cs:line 28
```


The corresponding lines:


```
    public static class Program
    {
        [global::System.Runtime.InteropServices.DllImport("Microsoft.ui.xaml.dll")]
        private static extern void XamlCheckProcessRequirements();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.STAThreadAttribute]
        static void Main(string[] args)
        {
            XamlCheckProcessRequirements();
            
            global::WinRT.ComWrappersSupport.InitializeComWrappers();
            global::Microsoft.UI.Xaml.Application.Start((p) => {
                var context = new global::Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext(global::Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread());
                global::System.Threading.SynchronizationContext.SetSynchronizationContext(context);
                new App();
            });
        }
    }
```

**Comment by amandas-slabsys** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/6377

Response by runceel helped me. I did not have launchSettings.json at all, which for some reason caused this error to happen. 

I am currently running:
Microsoft Visual Studio Community 2022 (64-bit) Preview
Version 17.2.0 Preview 2.0
.NET MAUI Preview 14
WindowsAppSDK 1.0.1
