### ISSUE TITLE
[Bug] Build fails with missing XliffTasks nuget package

### ISSUE THREAD

**Issue by trampster** [dotnet/maui#363]
### Description
If I try and build  Xamarin.Forms.Build.Tasks.csproj it fails because it can't find the nuget package XliffTasks. I've had a look on nuget.org and it's true no package exists with this name.

I'm trying to get the GTK projects building but I'm not sure how to resolve this one.

### Steps to Reproduce

1. Try and build Xamarin.Forms.Build.Tasks.csproj using dotnet build

### Expected Behavior
It builds

### Actual Behavior
> /home/daniel/Work/maui/src/Forms/src/Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj : error NU1101: Unable to find package XliffTasks. No packages exist with this id in source(s): nuget.org

### Basic Information

- Version with issue: Current github main branch
- Last known good version: None
- IDE: vscode on linux

**Comment by PureWeen** [comment]
Closing for now 
If you're still having issues after P2 then we can re-open

**Comment by trampster** [comment]
Please be aware that closing this bug prevents me from working on Maui for Linux until P2 is released. Linux is officially listed as community supported but this missing package effectly prevents the community from working on it.

Is the signal that you wan't to send to the linux community?
