### ISSUE TITLE
MAUI Grid renders differently from Forms Grid

### ISSUE THREAD

**Issue by DeanFaizal** [dotnet/maui#3630]
### Description

Basic grid doesn't have spacing and shows extra margin at the bottom. GridDemos was ported from the Xamarin.Forms samples repository.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/2334530/144495800-2ac6b58c-5bb3-4e17-9941-b10d908feb32.png">

Full comparison document is located here: https://github.com/alexkblount/maui-samples/blob/main/FormsMigrations/ComparisonDocumentation/UserInterface/Layout/GridDemos/GridDemos.md

This will be a hindrance for users wanting to upgrade from Forms to MAUI.

### Steps to Reproduce

1. Create a Grid in XAML with various rows and columns.
2. Use the same XAML in a Xamarin.Forms and MAUI app.
3. The layouts do not match. 

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

Manually setting margins and spacings could work.

**Comment by yunusefendi52** [comment]
I think this is the same as StackLayout where in Forms StackLayout has spacing of 6. This should be documented in migration tool somewhere, in the meantime you could add Style in App.xaml globally for Grid
```xaml
<Style TargetType="Grid">
      <Setter Property="RowSpacing" Value="6"/>
      <Setter Property="ColumnSpacing" Value="6"/>
</Style>
```

**Comment by DeanFaizal** [comment]
Can confirm StackLayout spacing is also missing @yunusefendi52

<img width="603" alt="image" src="https://user-images.githubusercontent.com/2334530/144641182-cdce3ef6-1569-4f08-8ee2-ecf7372eee26.png">

source: https://github.com/alexkblount/maui-samples/blob/main/FormsMigrations/ComparisonDocumentation/UserInterface/Layout/LayoutOptions/LayoutOptions.md

**Comment by hartez** [comment]
As @yunusefendi52 said, MAUI replaces the arbitrary default spacing values with a default of 0. The migration tools will apply the Forms styling to provide the old spacing defaults.
