### ISSUE TITLE
Back arrow not visible for navigation page in Android

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#3638]
### Description

With the latest .NET MAUI preview 10 back arrow of navigation page back button not visible in Android platform. Works fine with iOS.

![image](https://user-images.githubusercontent.com/42271912/144555348-e927ff62-473a-40c9-a1e1-80680e75aece.png)

### Steps to Reproduce

Create a new .net maui project and use navigation page.
Navigate to a new page.

Expected: Back arrow should be shown.
Actual:: Back button is there not no arrow image

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 9

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
If you are still seeing this issue when P11 comes out can you attach a repro and we can reopen
