### ISSUE TITLE
Maui content page not available 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3649]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-content-page-not-available/1591158)._

---
I am trying to add new xaml content page in a Maui project. But Xamarin.Forms content page is added.

---
#### Feedback Bot on 11/21/2021, 11:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pierre01** [comment]
This is a workaround but I found this Visual Studio Extension, which adds the templates you need. (supported in preview 10)
https://github.com/egvijayanand/dotnet-maui-templates

**Comment by HobDev** [comment]
@jfversluis I don't know who to contact, this issue can be closed as official templates are now available.

**Comment by jfversluis** [comment]
Perfect, thanks for letting us know!
