### ISSUE TITLE
StackLayout is an ambiguous reference between Microsoft.Maui.Controls.Compatibility.StackLayout and Microsoft.Maui.Controls.StackLayout

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3650]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/StackLayout-is-an-ambiguous-reference-be/1591089)._

---
I am developing new Maui App and writing UI in c#. I want to use common Layouts like stackLayout. But the above error arises when I use `using Microsoft.Maui.Controls;` . It goes away if I use `using StackLayout = Microsoft.Maui.Controls.StackLayout;`
This could be useful for porting a Xamarin.Forms App. But when developing new Maui App this is a issue. How to remove this compatibility issue?

---
#### Feedback Bot on 11/21/2021, 10:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by HobDev** [comment]
Hope this to be resolved by Pre12.

**Comment by hartez** [comment]
> But the above error arises when I use using Microsoft.Maui.Controls;

Do you have `using Microsoft.Maui.Controls.Compatbility;` declared as well?

**Comment by jfversluis** [comment]
I haven't seen this and it's from a while ago. No response to our question. I am assuming this is fixed. If not, please let us know!
