### ISSUE TITLE
Default Maui projects giving various errors. It did work 4 days ago before the last update

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3652]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Default-Maui-projects-giving-various-err/1590906)._

---
Ok few days ago i download 17.1 visual studio preview. I was excited to learn to build in all mobile platform + desktop. Was never interested in tedious winforms or wpf 
I thought maui will solve my development issue with simplify everything. So that is the introduction.

I downloaded VS and created project in Maui and Blazor-Maui. It all worked in windows. 

But yesteday whole thing failed and gave various error. So i decided to remove visual studio and comepletely restarted pc and reinstalled visual studio 17.1 with maui templates.

I am having same issues ... cant build default maui or blazor maui projects.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1603	Microsoft.Maui.Extensions 6.0.101-preview.9.1805 depends on Microsoft.Extensions.Configuration (>= 6.0.0-rc.2.21470.23) but Microsoft.Extensions.Configuration 6.0.0-rc.2.21470.23 was not found. An approximate best match of Microsoft.Extensions.Configuration 6.0.0-rc.2.21480.5 was resolved.	MauiApp5	C:\Dashboard\Workspace\microsoft\windowsforms\MauiApp5\MauiApp5\MauiApp5.csproj	1	
Error	CS1705	Assembly 'Microsoft.Maui' with identity 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Java.Interop, Version=0.1.2.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Java.Interop' with identity 'Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'	<Unknown> 	C:\Dashboard\Workspace\microsoft\windowsforms\MauiApp4\MauiApp4\CSC	1	N/A

Please make one working build so i can start learning. Default projects must work. What is going on?

---
#### Alex Kumar on 11/21/2021, 07:38 AM: 

(private comment, text removed)
#### Feedback Bot on 11/21/2021, 06:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
