### ISSUE TITLE
:net Maui StackLayout with radiobuttons inside StackLayout

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3653]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/:net-Maui-StackLayout-with-radiobuttons-/1587042)._

---
If I add a StackLayout (containing 3 RadioButtons) inside another StackLayout containing other controls I am not able anymore to run the project.
 <StackLayout>
                        <RadioButton x:Name="radioAll" Content="{x:Static localize:Resources.everyOne}" IsChecked="true" CheckedChanged="OnSexRadioButtonCheckedChanged"/>
                        <RadioButton x:Name="radioFemale" Content="{x:Static localize:Resources.female}" CheckedChanged="OnSexRadioButtonCheckedChanged"/>
                        <RadioButton x:Name="radioMale" Content="{x:Static localize:Resources.male}" CheckedChanged="OnSexRadioButtonCheckedChanged"/>
                    </StackLayout>

and this is the working code (where the StackLayout portion is commented out)

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="OneClick.Office.DentalSoftware.Pages.PatientsPage"
             xmlns:localize="clr-namespace:OneClick.Localization;assembly=OneClick.Localization"
             xmlns:telerikInput="clr-namespace:Telerik.XamarinForms.Input;assembly=Telerik.Maui.Controls.Compatibility"
             xmlns:telerikDataControls="clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.Maui.Controls.Compatibility"
             xmlns:telerikListView="clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.Maui.Controls.Compatibility" 
             BackgroundColor="{DynamicResource SecondaryColor}">
    <Grid RowSpacing="5" RowDefinitions="Auto, *"
          Padding="{OnPlatform iOS='30,60,30,30', Default='10'}">
        <Label x:Name="labelSelectedPerson" FontSize="Large" FontAttributes="Bold" HorizontalOptions="Center"  Grid.Row="0"/>
        <Grid Grid.Row="1">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="1*"/>
                <ColumnDefinition Width="4*"/>
            </Grid.ColumnDefinitions>
            <Grid>
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto"/>
                    <RowDefinition Height="*"/>
                </Grid.RowDefinitions>
                <StackLayout>
                    <telerikInput:RadButton Text="{x:Static localize:Resources.refreshList}" 
                                            BackgroundColor="Transparent" 
                                            BorderColor="Black" BorderThickness="1"
                                            Clicked="OnRefreshListClicked"/>
                    <telerikInput:RadEntry x:Name="lastNameFilter" 
                                           WatermarkText="{x:Static localize:Resources.familyName}"
                                           Keyboard="Text"
                                           TextChanged="OnTextChanged">
                    </telerikInput:RadEntry>
                    <telerikInput:RadEntry x:Name="firstNameFilter" 
                                           WatermarkText="{x:Static localize:Resources.givenName}"
                                           Keyboard="Text"
                                           TextChanged="OnTextChanged">
                    </telerikInput:RadEntry>
                    
                </StackLayout>
                <telerikDataControls:RadListView x:Name="bobListView" Grid.Row="1"  SelectionMode="Single" SelectionChanged="OnSelectionChanged">
                    <telerikDataControls:RadListView.ItemTemplate>
                        <DataTemplate>
                            <telerikListView:ListViewTemplateCell>
                                <telerikListView:ListViewTemplateCell.View>
                                    <Grid>
                                        <HorizontalStackLayout Margin="3">
                                            <Label Margin="3" Text="{Binding LastName}" FontAttributes="Bold" />
                                            <Label Margin="3" Text="{Binding FirstName}" />
                                            <Label Margin="3" Text="{Binding NickName}" FontAttributes="Italic" TextColor="Black"/>
                                        </HorizontalStackLayout>
                                    </Grid>
                                </telerikListView:ListViewTemplateCell.View>
                            </telerikListView:ListViewTemplateCell>
                        </DataTemplate>
                    </telerikDataControls:RadListView.ItemTemplate>
                </telerikDataControls:RadListView>
            </Grid>
        </Grid>
    </Grid>
</ContentPage>

and this is the behind code:

using Microsoft.Maui.Controls;
using OneClick.Office.ProtoClient;
using OneClick.Service;

namespace OneClick.Office.DentalSoftware.Pages;
public partial class PatientsPage
{
    private List<PeopleModel> _peopleList = new();
    public PatientsPage()
    {
        InitializeComponent();
    }

private void OnSelectionChanged(object sender, EventArgs e)
    {
        if (bobListView.SelectedItem is PeopleModel peopleModel)
        {
            labelSelectedPerson.Text = $"{peopleModel.LastName} {peopleModel.FirstName} {peopleModel.NickName}". TrimEnd();
        }
        else
        {
            labelSelectedPerson.Text = $"Nessuna selezione";
        }
    }
    async void OnSexRadioButtonCheckedChanged(object sender, CheckedChangedEventArgs e)
    {
        await RefreshPatientList();
    }
    protected override async void OnAppearing()
    {
        base. OnAppearing();
        await RefreshPatientList();
    }
    private async void OnTextChanged(object sender, TextChangedEventArgs e)
    {
        await RefreshPatientList();
    }

private void OnRefreshListClicked(object sender, System.EventArgs e)
    {
        _peopleList = new List<PeopleModel>();
        ClearFilters();
    }

private void ClearFilters()
    {
        lastNameFilter.Text = firstNameFilter.Text = string. Empty;
    }
    private async Task RefreshPatientList()
    {
        if (!_peopleList.Any())
        {
            using var channel = new ClientChannel();
            var request = new PeopleListRequest();
            var response = await channel. GetRepeatedPeopleList(request). ConfigureAwait(true);
            _peopleList = new List<PeopleModel>(response. ListOfPeople);
        }

IEnumerable<PeopleModel> contacts = _peopleList;
        if (lastNameFilter.Text.Length > 0)
        {
            contacts = contacts. Where(c => c.LastName.StartsWith(lastNameFilter.Text, StringComparison.OrdinalIgnoreCase));
        }
        if (firstNameFilter.Text.Length > 0)
        {
            contacts = contacts. Where(c => c.FirstName.StartsWith(firstNameFilter.Text, StringComparison.OrdinalIgnoreCase));
        }

//if (radioFemale.IsChecked)
        //{
        //    contacts = contacts. Where(c => c.IsFemale);
        //}
        //if (radioFemale.IsChecked)
        //{
        //    contacts = contacts. Where(c => !c.IsFemale);
        //}
        bobListView.ItemsSource = contacts. OrderBy(n => n.LastName). ThenBy(p => p.FirstName);
    }
}

---
#### Feedback Bot on 11/17/2021, 06:15 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
When you say "not able to run the project" - is the application crashing immediately, or does the application not build?

**Comment by PureWeen** [comment]
If this isn't fixed by P13 please attach a reproduction 

But this issue should be fixed by the following PR
https://github.com/dotnet/maui/pull/3784
