### ISSUE TITLE
VerticalStackLayout doesn't pass proper constraints to its children

### ISSUE THREAD

**Issue by PraveenGopalsamy** [dotnet/maui#3654]
### Description

When setting the padding value to the vertical stack layout, it didn't get considered when measuring the size of its children.

### Steps to Reproduce

1. Create a project under the Maui app.
2. Create a new class extending from the View, IContentview.
3. Now, set the child to the content
```
Drawing content = new Drawing(this);
object IContentView.Content => content;
IView IContentView.PresentedContent => content;
```
4. Measure the content using the crossplatformMeasure method
```
Size IContentView.CrossPlatformMeasure(double widthConstraint, double heightConstraint)
{
Console. WriteLine(" Width - "+widthConstraint.ToString()); // Output expected: 960, but getting as 1000 i.e entire screen size.
Console. WriteLine(" Height- "+heightConstraint.ToString()); // Infinity.
return this.MeasureContent(widthConstraint, heightConstraint);
}
```
5. Arrange the content as like same. Now run this in the **Windows** platform under the vertical stack layout with padding as (20,0). This value hasn't been considered when measuring the child.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.18362.0 and up

### Did you find any workaround?

In the vertical stack layout, you have missed to minus the padding with actual width and height.
```
public override Size Measure(double widthConstraint, double heightConstraint)
		{
			var padding = Stack.Padding;

			double measuredHeight = 0;
			double measuredWidth = 0;

			for (int n = 0; n < Stack.Count; n++)
			{
				var child = Stack[n];

				if (child.Visibility == Visibility.Collapsed)
				{
					continue;
				}

				var measure = child.Measure(widthConstraint, double.PositiveInfinity); // Missed to consider padding here.
				measuredHeight += measure.Height;
				measuredWidth = Math.Max(measuredWidth, measure.Width);
			}

			measuredHeight += MeasureSpacing(Stack.Spacing, Stack.Count);
			measuredHeight += padding.VerticalThickness;
			measuredWidth += padding.HorizontalThickness;

			var finalHeight = ResolveConstraints(heightConstraint, Stack.Height, measuredHeight, Stack.MinimumHeight, Stack.MaximumHeight);
			var finalWidth = ResolveConstraints(widthConstraint, Stack.Width, measuredWidth, Stack.MinimumWidth, Stack.MaximumWidth);

			return new Size(finalWidth, finalHeight);
		}
```

**Comment by Redth** [comment]
This should be fixed in the latest preview release.  Please open a new bug if it is still not working for you.
