### ISSUE TITLE
FlowDirection has changed when set MauiDrawable as NativeView's background at run time

### ISSUE THREAD

**Issue by PiruthivirajM** [dotnet/maui#3662]
### Description

In our MAUI sample,  changing background of native view (**ContentViewGroup**) by using MauiDrawable when clicking on content like below code,
`var selectionBackground = new MauiDrawable(handler.NativeView.Context);
selectionBackground.SetBackground(Microsoft.Maui.Controls.Brush.Gray);
handler.NativeView.Background = selectionBackground;`

In RightToLeft direction, content direction is changed to LTR from RTL when setting background at run time.
![image](https://user-images.githubusercontent.com/44426156/144700190-6141b360-c9d4-45df-af32-f073bd2df74d.png)

We tried below codes to resolve this, but not worked
![image](https://user-images.githubusercontent.com/44426156/144700251-33a90647-de9d-42e4-8f57-8e2d933b2dbf.png)

This problem occurs when having more than one label in DataTemplate.

Please share any suggestions to keep that selected content in parent element's flow direction.

### Steps to Reproduce

.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 28 and not sure about other versions

**Comment by XamlTest** [comment]
@PiruthivirajM Could you share your repro project? Thanks!
