### ISSUE TITLE
RadioButton Content squished on Android

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#3663]
### Description

Android radio buttons  content are squished on android

### Steps to Reproduce

1: Create new MAUI App
2: Add some radio buttons:

![RadioCode](https://user-images.githubusercontent.com/2603287/144709661-98c10bb2-f47a-40ce-98e2-db9f913a6e2b.jpg)

3: Run the app on Windows :All is fine

![RadioWindows](https://user-images.githubusercontent.com/2603287/144709493-aa92102f-44c1-4b28-a55f-ef48fe5d7d15.jpg)

4: Run the App om android, the content get squished

![RadioAndroid](https://user-images.githubusercontent.com/2603287/144709514-ef817a1a-465b-44a7-bf13-08865cf162bb.jpg)

Expected behavior: Android Displays content correctly

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 API 30 - Windows 11 Pro 22000.348

**Comment by carlosmunozrodriguez** [comment]
I have this exact issue. 
It looks so bad I can't include any radio buttons on my app yet.
I had to resort to use switches that get disabled by their peers which is totally unexpected to the user.
