### ISSUE TITLE
Port Button.Padding to Handler

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#367]
Please read the [Handler Property PR Guidelines](https://github.com/dotnet/maui/wiki/Handler-Property-PR-Guidelines) for instructions on how to create and submit a PR for this issue.

Thanks for your help!

**Comment by pictos** [comment]
Can I work on this one?

**Comment by hartez** [comment]
> Can I work on this one?

Go for it!

**Comment by pictos** [comment]
@hartez you can close this one, sorry I forgot to link the issue with the PR

**Comment by mattleibow** [comment]
No prob. Thanks for the PR. Closing this with a smile 😄
