### ISSUE TITLE
Access controls inside DataTemplate

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3675]
### Description

Currently, it is not straightforward to access control inside a DataTemplate and requires a lot of codes just to get or set a value. This should be in a very easy way by directly reading or setting a property.

### Public API Changes

```
<SyncfusionListView:SfListView x:Name="ListViewBrowseNotification">
    <SyncfusionListView:SfListView.ItemTemplate>
        <DataTemplate>
            <Grid>
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto" />
                </Grid.RowDefinitions>

                <Label x:Name="MyLabel" Grid.Row="0" />
        </DataTemplate>
    </SyncfusionListView:SfListView.ItemTemplate>
</SyncfusionListView:SfListView>
```

in Codebehid:

```
void TapGestureRecognizer_Tapped(System.Object sender, System.EventArgs e)
{
          MyLabel.Text = "Hellow World";
}

```

### Intended Use-Case

Every developer needs to access items inside a DataTemplate and it will save a lot of time for us if we can directly access it without Binding.

**Comment by GalaxiaGuy** [comment]
In your example, how do you know which label to set to "Hellow World"? You have a list view which presumably has lots of instantiated cells, each with a label with the name "MyLabel".

**Comment by jrahma** [comment]
> In your example, how do you know which label to set to "Hellow World"? You have a list view which presumably has lots of instantiated cells, each with a label with the name "MyLabel".

I would say something like this:

MyListView.Items[index].FindbyName("MyLabel")

`to access the control in a specific row for get and set
`
or:

`MyListView.Items.FindbyName("MyLabel")
`

to access the control in a all row for get and set but get here will require a loop.

**Comment by jfversluis** [comment]
This is simply not possible due to the nature of templates. As pointed out: a template will be instantiated multiple times or might not even exist for every item if you're using virtualization. You will have to do this through data-binding.
