### ISSUE TITLE
OpenAPI CodeGen

### ISSUE THREAD

**Issue by plettb** [dotnet/maui#3679]
### Description

Today I tried to add an OpenAPI service reference to my Maui project and whereas the "OpenAPIs" folder got created, the "swagger.json" file got copied to the folder, and all the right entries were made in the ".csproj" file, the code does not get generated and the classes can't be used.  If I try to "View generated code" I get "The following code file(s) were not found.  Try building the project again...".

Walking through the exact same steps in a console app added to the same solution works like a charm.  All NuGets in both projects are current and consolidated.

### Steps to Reproduce

1. Create a new MAUI App.
2. Right-click "Dependencies" and click "Manage Connected Services".
3. Click the "+" beside "Service References (OpenAPI, gRPC, WCF Web Service).
4. Select "OpenAPI" and click "Next".
5. Fill out the required info and click "Finish".
6. With for the "Service reference configuration progress" to finish and click "Close".
7. Click the ellipsis beside the newly added service and click "View generated code".

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

all

### Did you find any workaround?

No.  Obviously I can copy the generated file from another project, but I don't think that qualifies as a workaround

**Comment by v-longmin** [comment]
Verified repro. Repro project:
[MauiApp7.zip](https://github.com/dotnet/maui/files/8175320/MauiApp7.zip)

**Comment by timvandenhof** [comment]
Can confirm this issue still exists, as of MAUI RC3.

Swagger.json is being downloaded into an OpenAPI's folder and the csproj file is modified:

```XML
<ItemGroup>
	<OpenApiReference Include="OpenAPIs\swagger.json" CodeGenerator="NSwagCSharp" Namespace="ApiClientNamespace" ClassName="ApiClientClassName">
	<SourceUri>http://localhost/swagger/v1/swagger.json</SourceUri>
	</OpenApiReference>
</ItemGroup>

<ItemGroup>
	<PackageReference Include="Microsoft.Extensions.ApiDescription.Client" Version="3.0.0">
	<PrivateAssets>all</PrivateAssets>
	<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
	<PackageReference Include="NSwag.ApiDescription.Client" Version="13.0.5">
	<PrivateAssets>all</PrivateAssets>
	<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
</ItemGroup>
```

This might be faced by users migrating from Xamarin app with an `OpenApiReference` to MAUI, or new users starting a new MAUI project and adding a service reference. No error is given to the user that code is not being generated, except when navigating to service references in an attempt to browse the generated code.

Workaround: 
1. Create a new .net 6.0 class library;
2. Add the `OpenApiReference` to the class library project (either via csproj, GUI or commandline);
3. Add a project reference to the new class library from your MAUI project.

Would be cool if the NSwagCSharp code generator would be using `System.Text.Json` instead of `Newtonsoft.Json`, but that is not a MAUI specific thing.

**Comment by fzbeatrice** [comment]
Still an issue with VS 2022 Enterprise and .NET 7

**Comment by abdu292** [comment]
> Can confirm this issue still exists, as of MAUI RC3.
> 
> Swagger.json is being downloaded into an OpenAPI's folder and the csproj file is modified:
> 
> ```
> <ItemGroup>
> 	<OpenApiReference Include="OpenAPIs\swagger.json" CodeGenerator="NSwagCSharp" Namespace="ApiClientNamespace" ClassName="ApiClientClassName">
> 	<SourceUri>http://localhost/swagger/v1/swagger.json</SourceUri>
> 	</OpenApiReference>
> </ItemGroup>
> 
> <ItemGroup>
> 	<PackageReference Include="Microsoft.Extensions.ApiDescription.Client" Version="3.0.0">
> 	<PrivateAssets>all</PrivateAssets>
> 	<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
> 	</PackageReference>
> 	<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
> 	<PackageReference Include="NSwag.ApiDescription.Client" Version="13.0.5">
> 	<PrivateAssets>all</PrivateAssets>
> 	<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
> 	</PackageReference>
> </ItemGroup>
> ```
> 
> This might be faced by users migrating from Xamarin app with an `OpenApiReference` to MAUI, or new users starting a new MAUI project and adding a service reference. No error is given to the user that code is not being generated, except when navigating to service references in an attempt to browse the generated code.
> 
> Workaround:
> 
> 1. Create a new .net 6.0 class library;
> 2. Add the `OpenApiReference` to the class library project (either via csproj, GUI or commandline);
> 3. Add a project reference to the new class library from your MAUI project.
> 
> Would be cool if the NSwagCSharp code generator would be using `System.Text.Json` instead of `Newtonsoft.Json`, but that is not a MAUI specific thing.

@timvandenhof You can add `Options="/JsonLibrary:SystemTextJson"`
Ref:  http://michielpost.nl/posts/using-a-servicereference-in-blazor-webassembly-with-systemtextjson

**Comment by jfversluis** [comment]
From the looks of this, this might not be specific to .NET MAUI. If you think otherwise, please let us know why.
