### ISSUE TITLE
Docs: How to debug Blazor hybrid apps

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#3685]
How to debug managed code (easy), how to use F12 dev tools to debug/observe web view contents.

**Comment by Eilon** [comment]
Look at Mobile Blazor Bindings docs for inspiration (though all the native UI stuff doesn't apply, of course):
* Docs: https://docs.microsoft.com/en-us/mobile-blazor-bindings/
* Docs sources: https://github.com/MicrosoftDocs/mobile-blazor-bindings

**Comment by mkArtakMSFT** [comment]
This is going to be covered as part of https://github.com/dotnet/docs-maui/issues/281
