### ISSUE TITLE
[Windows] The DesiredSize doesn't get the proper size.

### ISSUE THREAD

**Issue by SuryaChinnadurai** [dotnet/maui#3687]
### Description

When setting the width and height request to the stack layout, it didn't return the stack layout size in the desired size property.

**Xaml:**
`<StackLayout x:Name="layout" WidthRequest="300" HeightRequest="397"/>`

**CS:**
`public MainPage()
		{
			InitializeComponent();
			Console.WriteLine(layout.DesiredSize);
}`

In the above code snippet, we have set the width request as 300 and the height request as 397. But we are getting stack layout desired size as `Size(300,397.3333435058)`

### Steps to Reproduce

1. Create a new Maui Application
2. Add stack layout
3. Set the width request as 300 and the height request as 397.
4. Print the stack layout desired size.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0 and up

### Did you find any workaround?

No.

### Relevant log output

```shell
No
```

**Comment by mattscheffer** [comment]
Appears to be not repro in VS 17.2.0 Preview 1. Tested against WindowsUI. The DesiredSize value is getting the correct values for Width and Height when using the repro above.

![image](https://user-images.githubusercontent.com/10537189/154595054-98cb5e68-c21d-4555-99f1-b210d9aabd1f.png)
