### ISSUE TITLE
iOS binding library project template

### ISSUE THREAD

**Issue by realZhangChi** [dotnet/maui#3688]
### Description

For android, we can create the `android-bindinglib` project to build the binding library. For ios, we also need a project template to build the binding library. This project template should be based on .net 6 maui, not xamarin.

### Public API Changes

none.

### Intended Use-Case

In my maui app, I need to integrate the ios sdk of other mobile vendors.

**Comment by PureWeen** [comment]
Moved to here

https://github.com/xamarin/xamarin-macios/issues/15896
