### ISSUE TITLE
Versioning my Maui Android App raise multiple errors

### ISSUE THREAD

**Issue by Bronzato1** [dotnet/maui#3690]
### Description

Previously the way to define version code for Android in Maui .csproj file was like this:

```
<!-- Versions -->
<ApplicationVersion>3.1.2</ApplicationVersion>
<AndroidVersionCode>3</AndroidVersionCode>
```

With the new release of Visual Studio Preview, this has changed to:
```
<ApplicationVersion>3</ApplicationVersion>
```

It works, from Visual Studio, I can bundle a new .aab package (see image below). We see the version code is defined to 3. Unfortunately the version is defined to 1.0.0.

![Bronzato_0-1638270460170](https://user-images.githubusercontent.com/13705487/145016210-c1bbd4ce-a698-4822-bf3a-9c04a11f6cf9.png)

...when imported on the Google Play Console, it look like this:
![Bronzato_2-1638270667736](https://user-images.githubusercontent.com/13705487/145016502-24e0f3f5-61c6-49c4-b4e3-7eb517235413.png)

Unfortunately, when imported on the Google Play Console I only see the versionCode 3 (which is defined in the .csproj file as ApplicationVersion). What about the versionName (in parentheses) ? Nothing is planned in the .csproj file ? When imported on the Google Play Console, I don't want to have  3 (1.0.0) but I want 3 (3.1.2)...

[https://developer.android.com/studio/publish/versioning](https://developer.android.com/studio/publish/versioning) 

versionCode — A positive integer used as an internal version number.
versionName — A string used as the version number shown to users.

Someone suggested me to update my csproj file by adding:
`<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>`

or manually set in your androidmanifest.xml:
[https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetSingleProject.md](https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetSingleProject.md) 

**By adjusting my csproj file to add _ApplicationDisplayVersion_ it raise me multiple errors:**

![image](https://user-images.githubusercontent.com/13705487/145018372-c7c4a393-6aee-4755-904a-7c5d44025015.png)

**Is this a bug ?**

As soon as I remove this code in my csproj file, the errors disappeared.

I'm using Visual Studio Professional 2022 - Preview Version 17.1.0 Preview 1.1

I did a `maui-check`

### Steps to Reproduce

**By adjusting my csproj file to add _ApplicationDisplayVersion_ it raise me multiple errors:**

![image](https://user-images.githubusercontent.com/13705487/145018372-c7c4a393-6aee-4755-904a-7c5d44025015.png)

### Version with bug

Visual Studio Professional 2022 - Preview Version 17.1.0 Preview 1.1

Maui Preview 10

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

OS: Windows 10 - Visual Studio Professional 2022 - Preview Version 17.1.0 Preview 1.1

### Did you find any workaround?

Manually set inside my AndroidManifest.xml do the trick.

![image](https://user-images.githubusercontent.com/13705487/145018279-60f581f4-208b-4664-b466-b0c3fe006560.png)

![Bronzato_2-1638636605253](https://user-images.githubusercontent.com/13705487/145017259-df4c1923-4364-41ec-92df-8d1baca75dbc.png)

**Comment by SilverioMiranda** [comment]
Same problem here

**Comment by kristinx0211** [comment]
Repro on Version 17.2.0 Preview 2.0 [32216.282.main] and the above project.

**Comment by SilverioMiranda** [comment]
Steps do reproduce : 

Download latest VS 2022 Preview Version
Create New MAUI Blazor App
Change ApplicationDisplayVersion to anything other than 1.0
Build

![image](https://user-images.githubusercontent.com/1939153/160317785-f9ae52e8-6578-4b80-a952-1a1f8f10b8d2.png)

**Comment by Eilon** [comment]
Seems related:
* https://github.com/dotnet/maui/issues/6037
* https://github.com/dotnet/maui/issues/6040

**Comment by zetaFairlight** [comment]
I have VS 2022 RC, and in a MAUI new app by simply changing the version number in the project file, it creates fatal errors. 
How to replicate the bug: Change from 1 to 0.1 `<ApplicationDisplayVersion>0.1</ApplicationDisplayVersion>`

The error in this case was: Error NETSDK1005	
**_Assets file 'C:\Users\Pablo\source\repos\Test1\Test1\obj\project.assets.json' doesn't have a target for 'net6.0-windows10.0.19041'. Ensure that restore has run and that you have included 'net6.0-windows10.0.19041' in the TargetFrameworks for your project._**

![2022-04-25 21_02_12-Test1 - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/99433/165193971-417b7bce-2497-46ca-b29c-e8b38ba0a7c2.png)
![2022-04-25 21_02_40-Test1 - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/99433/165193976-275f1eaf-ad1c-41ca-b293-ebdde1061eba.png)

**Comment by jonathanpeppers** [comment]
It looks like changing `$(ApplicationDisplayVersion)` triggers a bug in NuGet (when inside Visual Studio).

See:
* https://github.com/dotnet/maui/issues/6626#issuecomment-1112504084
* https://github.com/NuGet/Home/issues/6461
