### ISSUE TITLE
Blazor MAUI - Camera/Microphone Android - NotAllowedError: Permission denied

### ISSUE THREAD

**Issue by patrykplay** [dotnet/maui#3694]
### Description

I am trying to show live stream from camera & microphone in video html element.
For blazor wasm or blazor maui windows works great!
For iOS I not tested yet.
For Android I got issue.

When i use below code in javascript:
```
// Create request options
let options = {
    audio: true,
    video: true
};

// Request user media
navigator.mediaDevices
    .getUserMedia(options)
    .then(gotLocalStream)
    .catch(logError);
```

I got "NotAllowedError: Permission denied", but I am sure that permissions are requested correctly because I got camera/microphone stream natively (not used javascript, just by SDK).

It looks like to be need fixed in MAUI libs.

More details:
https://stackoverflow.com/questions/70229906/blazor-maui-camera-and-microphone-android-permissions

### Steps to Reproduce

1. Download my sample for this issue: https://github.com/patrykplay/BlazorMauiAndroidDevices
2. Run that on android device.
3. Exception will be see on label in html view.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

I have no workaround. I need to receive MediaStream object in Javascript, in order to use it for streaming media data.

### Relevant log output

```shell
NotAllowedError: Permission denied
```

**Comment by DannyBiezen** [comment]
I also ran into this issue and got it working for Android by creating the following classes:
```
public class MauiWebChromeClient: WebChromeClient
{
    public override void OnPermissionRequest(PermissionRequest request)
    {
        request.Grant(request.GetResources());
    }
}

public class MauiBlazorWebViewHandler: BlazorWebViewHandler
{
    protected override WebChromeClient GetWebChromeClient()
    {
        return new MauiWebChromeClient();
    }
}
```

Then make sure you're using the handler in `MauiProgram`:
```
builder.ConfigureMauiHandlers(handlers =>
{
    handlers.AddHandler<IBlazorWebView, MauiBlazorWebViewHandler>();
})
```

It's not working perfectly in my scenario but it may be a good starting point for anyone running into this issue. It'd be great if this was supported out of the box in Maui

**Comment by dannyBies** [comment]
I also ran into this issue and got it working for Android by creating the following classes:

public class MauiWebChromeClient: WebChromeClient
{
    public override void OnPermissionRequest(PermissionRequest request)
    {
        request.Grant(request.GetResources());
    }
}

public class MauiBlazorWebViewHandler: BlazorWebViewHandler
{
    protected override WebChromeClient GetWebChromeClient()
    {
        return new MauiWebChromeClient();
    }
}
Then make sure you're using the handler in MauiProgram:

builder.ConfigureMauiHandlers(handlers =>
{
    handlers.AddHandler<IBlazorWebView, MauiBlazorWebViewHandler>();
})
It's not working perfectly in my scenario but it may be a good starting point for anyone running into this issue. It'd be great if this was supported out of the box in Maui

**Comment by dannyBies** [comment]
I'm unable to get this working properly.
Using the code below changes the error from `
DOMException: Permission denied` to `
DOMException: Could not start video source`
```
public override void OnPermissionRequest(PermissionRequest request)
{
    request.Grant(request.GetResources());
}
```
It seems I am still missing audio/video permissions, even with the following in my AndroidManifest:
```
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.CAPTURE_SECURE_VIDEO_OUTPUT" />
    <uses-permission android:name="android.permission.CAPTURE_VIDEO_OUTPUT" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />

    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.CAPTURE_AUDIO_OUTPUT" />
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="true" />
    <uses-feature android:name="android.hardware.camera.front" android:required="true" />
    <uses-feature android:name="android.hardware.camera" android:required="true" />
    <uses-feature android:name="android.hardware.camera.level.full" android:required="true" />
    <uses-feature android:name="android.hardware.camera.capability.raw" android:required="true" />
    <uses-feature android:name="android.hardware.camera.any" android:required="true" />
    <uses-feature android:name="android.hardware.microphone" android:required="true" />
    <uses-feature android:name="android.hardware.camera2" android:required="true" />
```

JS causing the errors:
```
await navigator.mediaDevices.getUserMedia({ video: true })
```

**Comment by masoodafar-web** [comment]
Hi, I have the same problem, but my problem is different.
I want to get my request Permissin from the user in **Blazor pages** (For example. `FetchData.razor`), for example with a **snackbar** or some other Message way, But when the user rejects my permission request => **Deny**, I can not request again, please help !!

```
if (ActivityCompat.ShouldShowRequestPermissionRationale(this, Manifest.Permission.AccessFineLocation))
        {
            // Provide an additional rationale to the user if the permission was not granted
            // and the user would benefit from additional context for the use of the permission.
            // For example if the user has previously denied the permission.

            var requiredPermissions = new String[] { Manifest.Permission.AccessFineLocation };
            Snackbar.Make(Test,
                           "plz",
                           Snackbar.LengthIndefinite)
                    .SetAction("ok",
                               new Action<View>(delegate (View obj) {
                                   ActivityCompat.RequestPermissions(this, requiredPermissions, 1);
                               }
                    )
            ).Show();
        }
        else
        {
            ActivityCompat.RequestPermissions(this, new String[] { Manifest.Permission.Camera }, REQUEST_LOCATION);
        }
```
