### ISSUE TITLE
The status page does not tell you what version it's talking about

### ISSUE THREAD

**Issue by NogginBox** [dotnet/maui#3699]
### Description

I'm developing with the latest released version of .NET MAUI and I want to know what features have been implemented. This is helpful so I know not to try and use features that are not implemented yet. To find this out I go to the [status page](https://github.com/dotnet/maui/wiki/Status).

But the status page does not tell me what version it's talking about. I think it's talking about the latest dev changes that have not been released as it says the feature I want is done, but the feature does not feel done.

Adding some explanation of what version this is about would be really helpful. Having a status page for the latest released version would also be really useful (if that is not what the page already is).

### Steps to Reproduce

1. Go to the status page at https://github.com/dotnet/maui/wiki/Status
2. Look up a feature such as Shell
3. Try to work out if it's done for preview 10.
4. Be confused.

**Comment by jsuarezruiz** [comment]
You are absolutely right. The Status page share information about the main dev branch. Let us think about how we can organize this better and update it.

**Comment by jfversluis** [comment]
While I understand it's not ideal, the status page is a temporary thing anyway. At this point we're also close to having all APIs finalized and thus everything should be implemented apart from bugfixes we still need to do.

All things considered I don't think we should spend our valuable time trying to come up with a fix for this. Sorry if this is not what you wanted to hear, but I hope you'll understand.
