### ISSUE TITLE
Port Entry.SelectionLength to Handler

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#370]
Please read the [Handler Property PR Guidelines](https://github.com/dotnet/maui/wiki/Handler-Property-PR-Guidelines) for instructions on how to create and submit a PR for this issue.

Thanks for your help!

**Comment by ChaseRoth** [comment]
Hey hartez, I can take this one.

**Comment by Redth** [comment]
@ChaseRoth is taking this one
