### ISSUE TITLE
Flyout works on Windows but not mobile devices

### ISSUE THREAD

**Issue by marwalsch** [dotnet/maui#3700]
### Description

I integrated the [Flyout](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/modal) navigation into a MAUI project and noticed the following issues on mobile devices: 

Android Simulator/Device:
- The header is missing completely;
- instead of through the burger button the menu can be swiped out of the left-hand site;
- this menu is completely empty.

iOS Simulator: 
- The headline is visible, but the burger button is missing;
- the menu appears on headline press, but just as on Android the content is missing.

Windows:
- Everything seems to work as expected, but when the title overflows the pop-over menu, it gets cropped out.

It should also be worth noting that unlike in Xamarin, the `FlyoutPage` now throws an exception if no title is provided.

### Steps to Reproduce

Copy the Flyout Tutorial into a MAUI Xaml project and adjust the namespaces to refer to the MAUI dependencies.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, I was *not* able test on other platforms

### Affected platform versions

the latest versions shipped with preview 10

### Did you find any workaround?

No.

### Relevant log output

![Screenshot 2021-12-08 093050](https://user-images.githubusercontent.com/72074423/145188612-76024d4f-26ce-4cb6-a279-29b4bb58dea9.jpg)
![Screenshot 2021-12-08 104641](https://user-images.githubusercontent.com/72074423/145188635-fb37ddef-fe7b-40ac-8d5e-a4230ca0f4c0.jpg)
l
![Screenshot 2021-12-08 102016](https://user-images.githubusercontent.com/72074423/145188641-b938876d-ec95-41b4-b117-40ece3b23a0f.jpg)
![Screenshot 2021-12-08 105439](https://user-images.githubusercontent.com/72074423/145188649-21538a56-9488-4983-8226-518cae675ec0.jpg)

**Comment by filipnavara** [comment]
Reproduce using the following steps:
1) Create new app using `dotnet new maui`
2) Change `App` constructor to:
```
		public App()
		{
			InitializeComponent();

			MainPage = new FlyoutPage
			{
				Flyout = new ContentPage { Title = "Bar ", Content = new Label { Text = "BOOO" } },
				Detail = new NavigationPage(new MainPage() { Title = "Foo" }),
			};
		}
```

On `main` branch this seems to work on Android, presumably as a result of https://github.com/dotnet/maui/commit/963d68563c8499906e64c1d6debc96754a5c1506. On iOS it's still broken.

**Comment by marwalsch** [comment]
Though I can't comprehend what exactly causes this to work on Android (didn't test it yet) it's really just a platform specific workaround rather than a fix, which is urgently needed for such a basic feature. But thanks for the suggestion.

**Comment by filipnavara** [comment]
It seems to be a general bug when mixing handlers with the legacy renderers. I am hitting the same bug and I filed https://github.com/dotnet/maui/issues/3657 previously.

**Comment by kristinx0211** [comment]
Not repro on Version 17.2.0 Preview 2.0 [32216.282.main].
