### ISSUE TITLE
Image CornerRadius

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3707]
### Description

Hi,

Please add CornerRadius to the Image control.

Thanks,
Jassim

### Public API Changes

<Image CornerRadius="25" />

### Intended Use-Case

For all images.

**Comment by jsuarezruiz** [comment]
You can use the Clip property with the RoundRectangle to set every CornerRadius and have an image with customs corners, that could cover your scenario?

**Comment by jrahma** [comment]
Yes but it would be much easier if we can just set the radius

Also it will be great if there is a border and border color but not sure if that needs to be a separate thread.

**Comment by Redth** [comment]
You can use clip as @jsuarezruiz mentioned.

No currently plans to add Radius.
