### ISSUE TITLE
Maui Essentials will always open settings in split-screen if above Android N

### ISSUE THREAD

**Issue by taz4270** [dotnet/maui#3712]
### Description

Short Description:
ActivityFlags.LaunchAdjacent is meant to open as a split-screen if possible, you can see this article about this:

https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_LAUNCH_ADJACENT

### Steps to Reproduce

1. Create or use with any MAUI Essentials or Xamarin.Essentials project.
2. Use AppInfo.ShowSettingsUI().

It will appear as a split-screen even if your app does not support it.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android N+

### Did you find any workaround?

Since I didn't want any intent to split-screen, I did this:
```
public override void StartActivity(Intent intent)
{
    if (Build.VERSION.SdkInt >= BuildVersionCodes.N)
        intent.RemoveFlags(ActivityFlags.LaunchAdjacent);

    base.StartActivity(intent);
}
```
So it could cancel the previous flag

**Comment by taz4270** [comment]
Somehow GitHub didn't what was the line I was referring so I will put it here https://github.com/dotnet/maui/blob/7ebd79a302da71c266bab595a0c8211afe5a8321/src/Essentials/src/AppInfo/AppInfo.android.cs#L60

**Comment by GalaxiaGuy** [comment]
If a fix for this is accepted, what would be the process for also fixing it in Xamarin Essentials (which appears to use the same code)?

**Comment by taz4270** [comment]
If you are asking me I don't really know xD
It really depends on what do you want to do with this because I'm not the only one using this library (I'm using Xamarin Essentials btw) but what I suggest is making a type of flag (I don't know how other platforms work with multi-screen) but if so:
```
if (Platform.HasApiLevelN && flag)
> flags |= ActivityFlags.LaunchAdjacent;
```
Allowing people to choose what they want
PS: I think I saw more of these ActivityFlags.LaunchAdjacent though out other code files

Also here is the same code on the xamarin essentials library if you want to use this as a shortcut
https://github.com/xamarin/Essentials/blob/8657192a8963877e389a533b8feb324af6f89c8b/Xamarin.Essentials/AppInfo/AppInfo.android.cs#L64

**Comment by YuqinSong** [comment]
Not reproducible with Android 11. It didn't appear as a split-screen.

**Comment by taz4270** [comment]
Have you tried with a physic phone instead of an emulator?
Samsung phone might be affected by this, like my Samsung Note 9 (Android 10)
