### ISSUE TITLE
Essentials GetMainDisplayInfo uses unsupported API (and throws exception)

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#3722]
### Description

The `GetMainDisplayInfo()` method uses `DisplayInformation.GetForCurrentView();` to retrieve display information. That method is [not supported in WASDK](https://github.com/microsoft/microsoft-ui-xaml/issues/4228) and throws an exception.

### Steps to Reproduce

Call `var x = Microsoft.Maui.EssentialsDeviceDisplay.MainDisplayInfo;` in a Windows app. 

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041

**Comment by jsuarezruiz** [comment]
Should use Win32 PInvoke for this cases?

**Comment by hartez** [comment]
> Should use Win32 PInvoke for this cases?

The referenced issue suggests "If you want to get monitor info to replace ScreenHeightInRawPixels, you can try using MonitorFromWindow to get the HMONITOR and plug that into GetMonitorInfoW." 

So I think you're right, we'll have to use PInvoke.
