### ISSUE TITLE
Maui App template - Windows - "The project doesn't know how to run the profile Windows Machine"

### ISSUE THREAD

**Issue by ToolmakerSteve** [dotnet/maui#3725]
### Description

The message in the title pops up, whenever attempt to run a Maui App (unmodified) on Windows.

Works fine on Android.

I've run on Windows before, on earlier Previews.

### Steps to Reproduce

1. New Project - .NET MAUI App (Preview).
2. Select "Windows Machine" as target.
3. Run. (Green Arrow; Start Debugging)

Output from build indicates success:

> Build started...
1>------ Build started: Project: MauiApp3, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>MauiApp3 -> C:\Users\toolm\source\repos\MauiApp3\bin\Debug\net6.0-windows10.0.19041\win-x64\MauiApp3.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Then the popup saying "The project doesn't know how to run the profile Windows Machine".

POSSIBLY RELATED: Sometimes when quit VS and load same project again, it hangs forever Preparing Solution. Only way out is to kill with Task Manager. Next time, it skips loading documents, and is able to proceed.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other (Had it running at one time; not sure which Preview.)

### Affected platforms

Windows

### Affected platform versions

"Framework (net6.0-windows 10.0.19041)"

### Did you find any workaround?

No workaround. Rebooted. Deleted bin & obj. Ran maui-check (all green). Created a new project same steps. Tried running Android first. Tried not running Android first.

[maui-check.txt](https://github.com/dotnet/maui/files/7690084/maui-check.txt)

Repo: https://github.com/ToolmakerSteve/MauiApp3NoWindowsProfile

**Comment by drasticactions** [comment]
@ToolmakerSteve The VS Hang when opening a solution is because of a bug with MEF and the XAML Designer. That should be fixed with d17.1 Preview 2 when it's related.

It's unrelated to what you're seeing.

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
