### ISSUE TITLE
ImageSource.FromStream causes crash on Android

### ISSUE THREAD

**Issue by filipnavara** [dotnet/maui#3730]
### Description

```
12-10 14:04:55.094  7990  8103 E GlideExecutor: Caused by: android.runtime.JavaProxyThrowable: System.NotSupportedException: Unable to activate instance of type Android.Runtime.InputStreamAdapter from native handle 0x7e47963f81ec (key_handle 0xdda955c).
12-10 14:04:55.094  7990  8103 E GlideExecutor:  ---> System.MissingMethodException: No constructor found for Android.Runtime.InputStreamAdapter::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
12-10 14:04:55.094  7990  8103 E GlideExecutor:  ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
```

Full exception text and grefs trace available at https://gist.githubusercontent.com/filipnavara/0068f601f88cb1ea8d56a8552d62e9e7

The stream wrapper created here gets explicitly `Dispose`ed while native code still holds a reference to it:
https://github.com/dotnet/maui/blob/afc363d20ed643fc16468797c97971f822a1c162/src/Core/src/ImageSources/StreamImageSourceService/StreamImageSourceService.Android.cs#L33-L40

### Steps to Reproduce

1. Use `ImageSource.FromStream(File.OpenRead(...))` and assign the result to an `Image` view.

### Version with bug

Preview 12

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

emulator pixel_5_-_api_30

### Did you find any workaround?

Nope.

**Comment by filipnavara** [comment]
Repro: [MauiApp1.zip](https://github.com/dotnet/maui/files/7693995/MauiApp1.zip) - click the button

**Comment by filipnavara** [comment]
cc @mattleibow

**Comment by filipnavara** [comment]
Actually it's likely Preview 12 and may be caused by https://github.com/dotnet/maui/commit/b1f068703c00440deb42095f3dada47aa3f134c9. cc @PureWeen

**Comment by PureWeen** [comment]
@filipnavara I'm wondering if you're not on the latest build that includes my commit.  The exception you are indicating there is the exact exception we were getting until my commit 

Can you try setting?
`<MauiVersion>6.0.101-nightly.2357</MauiVersion>`

You'll have to copy the nuget.config file from here
https://github.com/dotnet/maui/blob/main/NuGet.config

in your csproj file and see if it still comes up? I ran your repro locally and for me it doesn't crash but my local maui bits include my commit

**Comment by filipnavara** [comment]
I'll recheck the exact versions when I get home but it's Preview 12 workloads from around 5 days ago IIRC.

**Comment by filipnavara** [comment]
It was happening on `6.0.101-preview.12.2339`. I am not sure if there's an easy way to map it to particular commit. I updated the workloads to `6.0.101-preview.12.2356` and it stopped crashing.
