### ISSUE TITLE
[Bug] [iOS] Reads "empty list" after last button

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#3731]
### Description

When swiping through the image buttons on the home screen, with VoiceOver activated, it reads out "empty list" after the last button. This is most likely an issue with the VLV which will be investigated further at a later time.

### Steps to Reproduce

1. Run recipes app on iOS
2. Activate VoiceOver
3. Swipe through the buttons under "Search by diet" and reach the "Keto" button
4. From "Keto", swipe right
5. Hear "Empty list" get read aloud

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by shimingsg** [comment]
@rachelkang can you share your repro project?

**Comment by rachelkang** [comment]
duplicate of #5815
