### ISSUE TITLE
ShowVideo Property for MediaElement

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3733]
### Description

Hi,

Many time we want to play sounds and not videos using the MediaElemnt so it will be great if you add ShowVideo property with a true / false value to show or hide the Video and make it a sound player only.

### Public API Changes

`ShowVideo="[True / False]"
`

### Intended Use-Case

Sound apps.

**Comment by pictos** [comment]
@jrahma the MediaElement control is part of Xamarin Community Toolkit/CommunityToolkit.Maui.

Can you close this issue and open a discussion [here](https://github.com/CommunityToolkit/Maui/discussions/new)

**Comment by jrahma** [comment]
> @jrahma the MediaElement control is part of Xamarin Community Toolkit/CommunityToolkit.Maui.
> 
> Can you close this issue and open a discussion [here](https://github.com/CommunityToolkit/Maui/discussions/new)

The suggestions option is disabled there and referred to .NET MAUI

**Comment by pictos** [comment]
> The suggestions option is disabled there and referred to .NET MAUI

@jrahma sorry, I didn't understand that, the link is working for me

**Comment by Redth** [comment]
Closing as per @pictos comment that this is a community toolkit related request.
