### ISSUE TITLE
TabbedPage inside a ShellContent fails on Android with Java.Lang.IllegalArgumentException

### ISSUE THREAD

**Issue by emorell96** [dotnet/maui#3741]
### Description

So I am trying to use a TabbedPage inside a ShellContent. On Windows all works, but on Android you get an exception when the app loads, or you navigate to the tabbed page.

The code is simple:

This is inside App.xaml
```xml
    <Application.MainPage>
        <Shell>
            <ShellContent Title="TabbedPage" Route="TabbedPage" ContentTemplate="{DataTemplate local:TabbedPageExample}" />
            <ShellContent Title="ContentPage" Route="ContentPage" ContentTemplate="{DataTemplate local:MainPage}" />
        </Shell>
    </Application.MainPage>
```

The ``local:TabbedPageExample`` is just a TabbedPage with two empty ContentPage inside the ``TabbedPage.Children``. You can see the code in the github I linked at the end.

Windows WinUI example:
![image](https://user-images.githubusercontent.com/20151415/145706066-58cc5f3e-5adc-49cd-bbbb-7e4a70b6198b.png)

On Android it just fails with the exception:

Java.Lang.IllegalArgumentException
  Message=No view found for id 0x7f08013d (com.companyname.TabbedPageBugDemo:id/navigationlayout_toptabs) for fragment ViewFragment{7e5f7b2} (bec44d9c-f254-4734-854a-1a8f9615c311 id=0x7f08013d)

I have created a minimal version to showcase the bug. You can find it here: https://github.com/StockDrops/TabbedPageBugDemo

Thank you!

### Steps to Reproduce

1. Create a new MAUI app from the Visual Studio template.
2. Create a shell with a tabbed page.
3. The app fails when you visit the tabbed page through the shell navigation or when the shell loads if it's the main page.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30, Android 11

### Relevant log output

```shell
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.companyname.TabbedPageBugDemo, PID: 30772
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(Fragm12-12 00:46:37.721 E/AndroidRuntime(30772): java.lang.IllegalArgumentException: No view found for id 0x7f08013d (com.companyname.TabbedPageBugDemo:id/navigationlayout_toptabs) for fragment ViewFragment{7e5f7b2} (bec44d9c-f254-4734-854a-1a8f9615c311 id=0x7f08013d)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:938)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:223)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7656)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
**Java.Lang.IllegalArgumentException:** 'No view found for id 0x7f08013d (com.companyname.TabbedPageBugDemo:id/navigationlayout_toptabs) for fragment ViewFragment{7e5f7b2} (bec44d9c-f254-4734-854a-1a8f9615c311 id=0x7f08013d)'
```

**Comment by PureWeen** [comment]
Mixing TabbedPage and FlyoutPage with Shell is currently not supported this experience might be better once we get to P13

**Comment by Dreamescaper** [comment]
Is it possible at least to throw a better exception if that's not a supported scenario?

**Comment by PureWeen** [comment]
Duplicate of #6389
