### ISSUE TITLE
Use HttpClient in Maui

### ISSUE THREAD

**Issue by ssccinng** [dotnet/maui#3742]
### Description

When I use HttpClient in MauiApp. It works well in the Emulator, but not on the mobile phone, Why is that?(android) its a bug(?
``` C#
private void OnCounterClicked(object sender, EventArgs e)
         {
 //            HttpClient httpClent = CreateHttpClient();
 //#if __ANDROID__
 //                        httpClent = new HttpClient(new Xamarin.Android.Net.AndroidMessageHandler());
 //#endif
    
             HttpClient httpClent = new();
             var res = httpClent.GetAsync($"https://xxxx.xxx/Image/Pochama/pocha-{count}.jpg");
             //PokeImg.Source = ImageSource.FromStream(() => new MemoryStream(res.Content.ReadAsByteArrayAsync().Result));
              
             //File.WriteAllBytes($"{count}.png", res.Content.ReadAsByteArrayAsync().Result);
             //var stream1 = new MemoryStream(imageAsBytes);
             //PokeImg.Source = $"pocha_{count % 88}.png";
             count++;
             CounterLabel.Text = $"Current count: {count}";
    
             SemanticScreenReader.Announce(CounterLabel.Text);
         }
```

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. add code in OnCounterClicked
3. run on mobile phone(android)
4. crash

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

Android

### Affected platform versions

Android11

**Comment by KPixel** [comment]
Can you put a try/catch around your code to log the exception and post it here?

**Comment by PureWeen** [comment]
If this isn't fixed by the following issue 

https://github.com/dotnet/runtime/issues/60896

Please attach a repro

**Comment by tobiasbaur** [comment]
Hello. 
I also have issues with the http client. I use a standard postAsync command. When I use it in Windows i works fine. On an M1 Mac it crashes instantly both on Mac and iOS. 

Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
