### ISSUE TITLE
Page title won't update when switching tabs with top bars inside a TabBar inside a shell on Android

### ISSUE THREAD

**Issue by emorell96** [dotnet/maui#3743]
### Description

If you use top Tabs by using multiple ``ShellContent`` elements inside a ``Tab``, the page title will not update when switching tabs.

Something like this:

```xml
<Shell xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       xmlns:pages="clr-namespace:TabBarBugRepo.Pages"
             x:Class="TabBarBugRepo.Pages.MobileShell">
    <TabBar>
        <Tab Title="Page 1"
             >
            <ShellContent ContentTemplate="{DataTemplate pages:Page1}" />
        </Tab>
        <Tab Title="Page 2 and 3">
            <ShellContent Title="Page 2"
                          ContentTemplate="{DataTemplate pages:Page2}" />
            <ShellContent Title="Page 3"
                          ContentTemplate="{DataTemplate pages:Page3}" />
            
        </Tab>
    </TabBar>
</Shell>
```

When you click Page 2 it looks like this:
![image](https://user-images.githubusercontent.com/20151415/145761789-b5905957-7090-4e37-a9c0-0a209765e619.png)
And when you click Page 3 it looks like this:
![image](https://user-images.githubusercontent.com/20151415/145761931-d47d219e-bac4-4bc3-acb9-1448fc416daa.png)
And yet the titles in each page is different ("Page 2", and "Page 3" respectively).

On Windows it works as expected:

![image](https://user-images.githubusercontent.com/20151415/145762101-7ec7c8ef-a3a3-4457-9a68-aaa0174f1f20.png)
![image](https://user-images.githubusercontent.com/20151415/145762123-4162b6ab-57d9-4148-bda6-4baa92ad4597.png)

But not on Android. I cannot test it on Mac nor iOS since I do not have a Mac available.

### Steps to Reproduce

1. Create a Shell with a TapBar inside.
2. Inside the TapBar use a Tab item with multiple ShellContent.
3. You'll see the Page Title won't update when you switch tabs.

You can find a minimal repo with the bug in: https://github.com/StockDrops/TabBarBugRepo
It's the template where I just added 3 blank content pages. And a shell (MobileShell.xaml and its cs file).
You can test it yourself by cloning the repo.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30, Android 11

### Did you find any workaround?

None

**Comment by emorell96** [comment]
This one is similar: https://github.com/dotnet/maui/issues/3382 although different in that it only happens on start up.

**Comment by shimingsg** [comment]
verified repro with android emulator with vs 17.2.0 Preview 2.0 [32223.271.main] with the minimal repo : https://github.com/StockDrops/TabBarBugRepo

**Comment by PureWeen** [comment]
Fixed on RC1
