### ISSUE TITLE
dotnet/dotnet exited with code 1

### ISSUE THREAD

**Issue by newcc845** [dotnet/maui#3744]
### Description

Seeking advise for following error, I was try to use iOS simulator but not successful (but I confirm on Xamarin is working fine) with the same project, I able to execute for android or windows.

`Severity	Code	Description	Project	File	Line	Suppression State
Warning		The given path's format is not supported.	MauiApp4	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.0.101-preview.10.251\tools\msbuild\iOS\Xamarin.Shared.targets	1041`

`/Library/Caches/Xamarin/XMA/SDKs/dotnet/dotnet exited with code 1
MauiApp4	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.0.101-preview.10.251\targets\Xamarin.Shared.Sdk.targets	870`

`Severity	Code	Description	Project	File	Line	Suppression State
Error		The AOT compiler '' does not exist.	MauiApp4	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.0.101-preview.10.251\targets\Xamarin.Shared.Sdk.targets	870	`

### Steps to Reproduce

Version 17.1.0 Preview 1.1 (clean version)

1) Open VS 2022 Preview
2) File > .Net MAUI APP (Preview)
3) Need pair with Mac [Tools > Options > Xamarin > iOS Settings OR Tools > Options > Xamarin > Apple Accounts]
4) For my case I use macbook (need to pair)
5) On Run > iOS > Simulators

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

iOS

### Affected platform versions

15.0.101-preview.10.251

**Comment by karthikraja-arumugam** [comment]
Hi @PureWeen, @jsuarezruiz,

I'm also facing this same issue. Does anyone have a workaround for this? Or when can we expect a fix for this?

**Comment by shimingsg** [comment]
@karthikraja-arumugam @newcc845 Is there a problem with debugging on the IPhone? it works ok on iphone 13 IOS 15.2.

**Comment by kristinx0211** [comment]
Not reproducible with iPhone 13 pro max IOs 15.2.
