### ISSUE TITLE
Picker , DatePicker and TimePicker popup did not open in MacCatalyst

### ISSUE THREAD

**Issue by MuniappanSubramanian** [dotnet/maui#3748]
### Description

While tapping the Picker, DatePicker, and TimePicker in Maccatalyst the picker does not open the popup and it is working fine in the iOS.

### Steps to Reproduce

1. Run the attached sample
2. Tap picker

Expected Result:
Popup should open.

Sample:
[Archive.zip](https://github.com/dotnet/maui/files/7704651/Archive.zip)

![Screen Shot 2021-12-13 at 6 21 16 PM](https://user-images.githubusercontent.com/46158936/145834845-4436639a-a219-4991-8baf-989d2d3fbec7.png)

.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

iOS15

**Comment by matt-goldman** [comment]
I also noticed this problem today. It's fine on iOS though.

**Comment by VincentBu** [comment]
I verified this issue. Picker, DatePicker, and TimePicker don't work on Mac.

**Comment by Redth** [comment]
Related to #5475
