### ISSUE TITLE
Empty view is shown in DatePicker instead of dates in Android platform.

### ISSUE THREAD

**Issue by MuniappanSubramanian** [dotnet/maui#3749]
### Description

While navigating the date picker and again tapping the date picker it shows as an empty view.,

### Steps to Reproduce

1. Run the sample
2. Tap date picker
3.   Forward three times using the forward button and tap ok.
4.  Again tap the date picker.

Expected Result: 
Dates should be shown.

![image](https://user-images.githubusercontent.com/46158936/145838047-ea1fa848-0b4c-4b47-9b49-ca1720a96892.png)
[DatePicker.zip](https://github.com/dotnet/maui/files/7704826/DatePicker.zip)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android latest and old version

**Comment by zhouwangyang** [comment]
same issue can be reproduced.

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/Ea_6tN_YtxdEm9WllszAJx4BBjoLj7ZM80LZGpSgQgeUkw?e=MYLDIQ

**Comment by J-Swift** [comment]
When I ran into this, I could tap the empty view and the calendar would show back up. However, if I then navigated _back_ to the page with the DatePicker, the DatePicker dialog would automatically show up. Every time I navigated back it would do that.
