### ISSUE TITLE
Blazor with WPF and WebView2: Scoped CSS files not found

### ISSUE THREAD

**Issue by Devmawi** [dotnet/maui#3751]
### Description

I want to integrate the new Blazor WebView in a WPF project. For this I tried to reproduce the examples on:

* https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-preview-3/#blazorwebview-controls-for-wpf-windows-forms
* https://github.com/dotnet/maui/tree/main/src/BlazorWebView/samples/BlazorWpfApp

The first problem was that apparently the razor components located in the WPF project were not being builed. In consequence my webview only loads the `_framework/blazor.webview.js`, but no components. It seems that some `*.targets` are missing.
Happily I could load the components inclusive content of `wwwroot`, because I transfered this to a dedicated `Razor Class Library`
and every thing nearly worked.

#### Bug behaviour description

The last bug is the felowing: At debugging time I see (`DevTools, ctrl + shift + I`), that my `*.styles.css` for `scoped CSS` files of the Razor Class Library, that was embedded in `index.html`, is not loaded and returns `404 NOT FOUND`. My class library is called `BlazorWpfApp.BlazorApp`, so I assume the scoped CSS bundle is named `BlazorWpfApp.BlazorApp.styles.css` like in the [docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0#css-isolation-bundling).

### To reproduce

I have provided a minimal project with Balzor WebView and WPF:

- https://github.com/Devmawi/Blazor-Samples
- https://github.com/Devmawi/Blazor-Samples/tree/master/BlazorWpfApp , WPF host
- https://github.com/Devmawi/Blazor-Samples/tree/master/BlazorWpfApp.BlazorApp, Razor Class Lib
- [Index.html of Razor Class Lib, that is loaded to BlazorWebView](https://github.com/Devmawi/Blazor-Samples/blob/d939977c467bf37e5e10e62a3ef61b42d64b2b64/BlazorWpfApp.BlazorApp/wwwroot/Index.html#L12)

Feel free to clone, build and debug.

### Some technical parameters

- Visual Studio 2022 Preview (Microsoft Visual Studio Community 2022 (64-bit) - Preview, Version 17.1.0 Preview 1.1)
- WebView Package: Microsoft.AspNetCore.Components.WebView.Wpf, version: 6.0.101-preview.10.2068

``` 
dotnet --info
.NET SDK ("global.json"):
 Version:   6.0.100
 Commit:    9e8b04bbff

Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by Devmawi** [comment]
Thank you very much for your response. This is very interesting. How have you figured that out? In my output folder I see only my custom *.css files. So I would assume the *.Desktop.styles.css is embedded in the assembly. But nothing is present. I have also read the docs and some provides samples in https://github.com/dotnet/maui/tree/main/src/BlazorWebView/samples/**.
I have also tried out the following (my targets are net6.0 and net6.0-windows):

- `net6.0.Desktop.styles.css`
- `net6.0-windows.Desktop.styles.css`
- ...

But nothing worked. Could you provide an code example of your `index.html`?

**Comment by nvmkpk** [comment]
Your WPF project references `Microsoft.NET.Sdk` sdk. You need to change it to `Microsoft.NET.Sdk.Razor` for generating the scoped css and bundle.

**Comment by Devmawi** [comment]
Hey @nvmkpk . Who can read is better off: https://github.com/dotnet/maui/blob/1cd8f03814a65ee221024e4f169961d6edea23b0/src/BlazorWebView/samples/BlazorWpfApp/BlazorWpfApp.csproj#L1

This makes absolutely sense. Without `Microsoft.NET.Sdk.Razor` the build targets for static web assets are missing and in consequence the nothing is build.

I have sucessfully updated my Blazor WPF project and everything was working &#127919; ...  &#128526;:
* https://github.com/Devmawi/Blazor-Samples/blob/master/BlazorWpfApp/BlazorWpfApp.csproj

Thank for your fast support!

**Comment by Eilon** [comment]
Yep that should be it! We are working on getting some documentation for this so that will hopefully make this easier in the future!
