### ISSUE TITLE
App icon not showing in build 

### ISSUE THREAD

**Issue by PK268** [dotnet/maui#3755]
### Description

Hey, so I'm making an app and I'm trying to change the app icon (you know, the icon that shows in your taskbar) but what i tried doesn't work. This is a code snippet from my .csproj file

`<!-- App Icon --> <MauiIcon Include="Resources\app_icon.png" ForegroundFile="Resources\app_icon.png" IsAppIcon="true"/>`

I double checked to make sure all the file names and locations were correct. Is there something I'm missing?
Btw I'm not entirely sure what .NET MAUI version I have but I'm pretty sure it's 10 just because when I look at the VS installer there is no update option and 10 is "current".

(Bonus points if you can tell me how to change the app to be a fixed resolution, un-sizeable window)

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Import [image](https://matgames.net/d/app_icon.png) and put into resources folder.
2. Double click on the .sln
3. Change app icon Include and ForegroundFile to the path to the file
4. Save and build for WindowsMachine

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by bwoebi** [comment]
Seems like for unpackaged executables you need to set the icon manually via <ApplicationIcon> property in the csproj.

Would be great if Maui would also be able to handle Win32 icons natively.

**Comment by PK268** [comment]
Het, i don't really see any documentation for <ApplicationIcon>. How do i use it?

**Comment by bwoebi** [comment]
like `<ApplicationIcon>icon.ico</ApplicationIcon>` - an embedded resource in ico format.

Then, to also display it in the active window, load it (persist it in some class variable as long as the application lives):
```
System.Drawing.Icon icon = new(Assembly.GetExecutingAssembly().GetManifestResourceStream("icon.ico")!);
```
and set it via
```
WindowHandler.WindowMapper.Add(nameof(IWindow), (handler, view) => {
	IntPtr windowHandle = ((Microsoft.Maui.MauiWinUIWindow)handler.NativeView).WindowHandle;
	PInvoke.User32.SendMessage(windowHandle, PInvoke.User32.WindowMessage.WM_SETICON, (IntPtr)0, icon.Handle);
	PInvoke.User32.SendMessage(windowHandle, PInvoke.User32.WindowMessage.WM_SETICON, (IntPtr)1, icon.Handle);
});
```
in your Application entry point.

(And kudos to the maui maintainers for making the window handle so easily accessible.)

**Comment by PK268** [comment]
Hey! Thanks again for the response! I have a few problems now. Right now VS isn't recognizing System.Drawing.Icon, PInvoke, or MauiWinUIWindow. Control + space doesn't pull up any results. Also when using SpplicationIcon like you specified, I
get 
"Items that are outside Target elements must have one of the following operations: Include, Update, or Remove."
Any fixes for this?

**Comment by IIARROWS** [comment]
> like `<ApplicationIcon>icon.ico</ApplicationIcon>` - an embedded resource in ico format.
> 
> Then (put it in `#if WINDOWS`), to also display it in the active window, load it (persist it in some class variable as long as the application lives):
> 
> ```
> System.Drawing.Icon icon = new(Assembly.GetExecutingAssembly().GetManifestResourceStream("icon.ico")!);
> ```
> 
> and set it via
> 
> ```
> WindowHandler.WindowMapper.Add(nameof(IWindow), (handler, view) => {
> 	IntPtr windowHandle = ((Microsoft.Maui.MauiWinUIWindow)handler.NativeView).WindowHandle;
> 	PInvoke.User32.SendMessage(windowHandle, PInvoke.User32.WindowMessage.WM_SETICON, (IntPtr)0, icon.Handle);
> 	PInvoke.User32.SendMessage(windowHandle, PInvoke.User32.WindowMessage.WM_SETICON, (IntPtr)1, icon.Handle);
> });
> ```
> 
> in your Application entry point.
> 
> (And kudos to the maui maintainers for making the window handle so easily accessible.)

I'm pretty sure it doesn't work for Android though...
I followed the documentation but it still shows me the blue grid with the bot head.

**Comment by bwoebi** [comment]
For Android the normal MauiIcon works fine for me. This is exclusively for windows.

**Comment by IIARROWS** [comment]
Yes, but I have the same problem but for Android.

**Comment by AbuMandour** [comment]
> Yes, but I have the same problem but for Android.

Me too even in splash screen

**Comment by YuqinSong** [comment]
Verified Repro. Repro project is available:
[#3755.zip](https://github.com/dotnet/maui/files/8150872/3755.zip)

**Comment by CliffAgius** [comment]
I am seeing the same issue with Android and iOS the builds fail complaining they can't find the AppIcon this is VS22 17.2.0 Preview 1.0 and MAUI SDK version of 6.0.200-preview.13

However I solved this by: 

 1. using an SVG instead of a PNG
 2. Calling the file the same as the default so appicon.svg
 3. Making it a basic SVG file so before I used  InkScape to make the Icon but this had lots of extra stuff in there, so I took the Icon PNG file and used https://convertio.co/ a tool I found with a web search and converted the PNG to SVG.

Not perfect and the issue is still there but with Preview 13 this seems an easy fix.

**Comment by IIARROWS** [comment]
I want to say that it works for me now, I think it's from the last update.
I had to manually resize the viewbox of the SVG because to make space for the border, as it was not clear I had to do it (according to Android guidelines https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive)

**Comment by PK268** [comment]
> I am seeing the same issue with Android and iOS the builds fail complaining they can't find the AppIcon this is VS22 17.2.0 Preview 1.0 and MAUI SDK version of 6.0.200-preview.13
> 
> However I solved this by:
> 
> 1. using an SVG instead of a PNG
> 2. Calling the file the same as the default so appicon.svg
> 3. Making it a basic SVG file so before I used  InkScape to make the Icon but this had lots of extra stuff in there, so I took the Icon PNG file and used https://convertio.co/ a tool I found with a web search and converted the PNG to SVG.
> 
> Not perfect and the issue is still there but with Preview 13 this seems an easy fix.

This fix is only for Android and iOS correct? Will it work on Windows and Mac?

**Comment by Redth** [comment]
Only SVG's were supported for app icons up until a more recent release but should be now.  Please open a new issue if you still have problems with it.
