### ISSUE TITLE
DatePicker popup is not showing the selected date 

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#3756]
### Description

DatePicker popup is not showing the selected date in the popup on popup opening. **If we set a Date property in code behind** to any date value, the text field is showing that date but the popup is loading for next month of the Date which is set.

### Steps to Reproduce

1. Use below code

**XAML**
`<StackLayout>
        <DatePicker x:Name="datePicker"/>
    </StackLayout>`

**C#**
`this.datePicker.Date = new DateTime(2021, 10, 05);`

2. Open date picker popup after loading into view.
3. Note that the date is updated in text field but the popup is showing wrong month. 
Set date : October 5, 2021.
Popup date: November 5, 2021

![image](https://user-images.githubusercontent.com/92788387/145942147-eaac5c4c-7da4-4bf2-a4e8-744712b6cc2a.png)

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

Android

### Affected platform versions

Android 10.0

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
This issue should be fixed in P11 by https://github.com/dotnet/maui/pull/3298
Tested with main branch:
![issue3756](https://user-images.githubusercontent.com/6755973/145975084-0dd6f9ff-dc10-4fbb-aad0-99942c6a4495.gif)
