### ISSUE TITLE
The Onplatform condition does not work properly in MacCatalyst.

### ISSUE THREAD

**Issue by MuniappanSubramanian** [dotnet/maui#3758]
### Description

The button visibility is handled based on the platform by using the OnPlatform condition, if I set **macOS=false** the button is still visible in MacCatalyst. 

### Steps to Reproduce

1. Use the below code snippet

**XAML:**
 `<StackLayout VerticalOptions="Center">
     <Button x:Name="TestButton" IsVisible="{OnPlatform Android=true, iOS=true, macOS=false}" BackgroundColor="Red"/>
 </StackLayout>`

If false set for {OnPlatform Android=true, **iOS=false, macOS=false**} the button will be collapsed in MacCatalyst.

**Expected Behavior:**
The button should be visible based on platform conditions.

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

macOS

### Affected platform versions

iOS15

**Comment by vanka78bg** [comment]
This is impacting us severely as well. Mac OS UI/UX is different from iOS. Often it is necessary to apply different styling and/or accommodate the UI to the native look and feel of the underlying operating system.

After some testing, we have discovered that `Device.RuntimePlatform` returns `iOS` and `Device.Idiom` returns `Tablet` on Mac OS. This explains why the `OnPlatform` and `OnIdiom` markup extensions do not work correctly.

One possible workaround we have found is to re-implement the `OnPlatform` and `OnIdiom` markup extensions ourselves and use preprocessor directives to determine the correct platform at compile time. Duplicating something that is already in the framework just to fix a bug seems counter-productive however.
