### ISSUE TITLE
[iOS, Android] Date and Time Picker shows wrong date in popup.

### ISSUE THREAD

**Issue by MuniappanSubramanian** [dotnet/maui#3759]
### Description

While setting the Selected date and selected time for DatePicker and Timepicker, the popup shows the wrong date and time on Android and IOS platform.

### Steps to Reproduce

**Issue 1:**
1. Run the sample
2. Tap the DatePicker 

**Actual Result:**
The Date was rendered wrong in the popup.
![Simulator Screen Shot - iPhone 8 - 2021-12-14 at 12 56 07](https://user-images.githubusercontent.com/46158936/145965300-8e81bb47-0526-430c-bcf1-98339ba4c9f4.png)

Picker Date: Dec 12, 2021, but the popup shows Dec 14, 2021

**Expected Result:**
The popup should be rendered on the correct date.

**issue 2:**
1. Run the sample
2. Tap the TimePicker 

**Actual Result:**
The Time was rendered wrong in the popup.
![Simulator Screen Shot - iPhone 8 - 2021-12-14 at 12 56 15](https://user-images.githubusercontent.com/46158936/145965697-92aa2b6d-e091-4343-a7ee-f8aaeda61ffd.png)

TimePicker selected time: 09:00 AM, but the popup shows 07:26 AM

**Expected Result:**
The popup should be rendered at the correct time.

**Sample:** 
[Sample.zip](https://github.com/dotnet/maui/files/7710143/Sample.zip)

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

iOS

### Affected platform versions

iOS15

**Comment by hartez** [comment]
@MuniappanSubramanian Does the date/time update when you tap the "Done" button? Or are they still incorrect after tapping "Done"?

**Comment by MuniappanSubramanian** [comment]
@hartez After tapping the "Done" button the date is updated

**Comment by shimingsg** [comment]
Not reproducible with Android 11, but verified repro with IOS 15.2 and the above project.
