### ISSUE TITLE
[Windows] The shadow doesn't shows when using the GraphicsView

### ISSUE THREAD

**Issue by SuryaChinnadurai** [dotnet/maui#3762]
### Description

When I tried to draw the shadow for custom shape using GraphicsView, it doesn't show in the windows platform.

Xaml:

```
<ContentPage.Resources>
        <ResourceDictionary>
            <local:GraphicsDrawable x:Key="GraphicsDrawable" />
        </ResourceDictionary>
    </ContentPage.Resources>

    <ContentPage.Content>
        <StackLayout>
            <GraphicsView
                 HeightRequest="500"
                WidthRequest="500"
                Drawable="{StaticResource GraphicsDrawable}"></GraphicsView>
        </StackLayout>
    </ContentPage.Content>
```

CS:
```
public class GraphicsDrawable : IDrawable
{
	public void Draw(ICanvas canvas, RectangleF dirtyRect)
	{
		canvas.SaveState();
		canvas.FillColor = Colors.CornflowerBlue;
		canvas.SetShadow(new SizeF(10, 10), 4, Colors.Grey);
		canvas.FillRectangle(50, 100, 100, 50);

		canvas.SetShadow(new SizeF(10, 10), 4, Colors.Red);
		canvas.FillEllipse(200, 100, 100, 50);
		canvas.RestoreState();
	}
}
```

Expected:

![image](https://user-images.githubusercontent.com/72392561/145998795-982c9d4d-0dda-40bb-85a6-e86ee212b121.png)

Actual:

![image](https://user-images.githubusercontent.com/72392561/145998870-2d45a54c-4deb-4ff1-aec3-d20b9c22c07f.png)

### Steps to Reproduce

1. Create a new Maui Application
2. Add GraphicsView and set height and width as 500.
3. Create a new class and extend the class from IDrawable
4. Draw the custom shape and shadow using canvas in the draw method.
4. Bind the new class to the GraphicsView drawable property.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0 and up

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by PaulChek** [comment]
Same problem on preview 11

**Comment by wenwen60** [comment]
Not reproducible with windows in VS2022(17.2.0 Preview 2.0).
