### ISSUE TITLE
When can we expect documentation on distribution to Appstore and google Playstore ?

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#3766]
### Description

I am coming from Web Background and created small app using MAUI,  but finding it very hard to find step by step guide on distributing to Apple AppStore and Google Play Store.

I had gone through steep learning from various articles and still not able to publish app. This is something not obvious for someone coming from web background and even more so when this is my first Mobile app.

So any documentation on Step-by-Step articles on distributing to both the stores including anything necessary steps that needs to be in done on the store itself will be appreciated.

This will also encourage web developers to flex their hand/skills on mobile app development.

### Public API Changes

This is related to having documentation on all the steps necessary to distribute MAUI app to Apple App store or Google Play Store

### Intended Use-Case

I am not finding any articles on step-by-step documentation to distribute the app to App store.

**Comment by davidbritch** [comment]
Hi @nssidhu 

It'll be added when the product launches.

**Comment by jfversluis** [comment]
For now have a look at #4397, #4329  and #4377 the official docs will come when .NET MAUI goes GA. At this time we do not recommend publishing apps to stores with .NET MAUI as it's still in preview.

Closing this for now, creating the docs is on our list :)
