### ISSUE TITLE
Stepper doesn't fire ValueChanged event

### ISSUE THREAD

**Issue by hflexgrig** [dotnet/maui#3774]
### Description

`<Stepper Minimum="0" Increment="1" ValueChanged="ValueChangedHandler" />` 

ValueChangedHandler not getting fired!

### Steps to Reproduce

1. Create Stepper. `<Stepper Minimum="0" Increment="1" ValueChanged="ValueChangedHandler" />` 
2. Click on plus minus buttons
3. ValueChangedHandler not getting fired!

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows

### Did you find any workaround?

No

### Relevant log output

```shell
No need log
```

**Comment by Dreamescaper** [comment]
https://github.com/dotnet/maui/issues/3585

**Comment by hflexgrig** [comment]
Why I see issues closed when they're reproducable? There was also issue with image source not displaying at android, https://github.com/dotnet/maui/issues/1210

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue.
![issue3774](https://user-images.githubusercontent.com/6755973/146186924-05a21348-0551-49cd-88aa-99a00fe3fa04.gif)

Could you attach a small sample where reproduce it?. Are you using Preview 11, right?. Thanks in advance.

**Comment by hflexgrig** [comment]
@jsuarezruiz  Well, this is my stepper on xaml
![image](https://user-images.githubusercontent.com/24684337/146189803-f03fee61-e106-41e5-9b5e-d6a9fc628745.png)

this is handler
![image](https://user-images.githubusercontent.com/24684337/146189901-08ce5734-8bba-4d19-bcbf-b7306d170875.png)

When I run on windows, breakpoint not hitting on handler

**Comment by hflexgrig** [comment]
And those are dependencies I have 

![image](https://user-images.githubusercontent.com/24684337/146190411-68b3e896-990d-49ac-bbf8-b64b770ff4df.png)

**Comment by jsuarezruiz** [comment]
@hflexgrig Could you try again with the latest version?.

**Comment by hflexgrig** [comment]
It works, thanks
