### ISSUE TITLE
RTL flow direction not working properly in stack layout

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#3779]
### Description

**Windows:** 

If we set RTL to stack layout, it only changes the horizontal options to End and it doesn't arrange the child from the right.
![image](https://user-images.githubusercontent.com/92788387/146196735-a9f47526-82ba-4b16-8dee-0e96da5bd24f.png)

**Android:**

It arranges the child in reverse, but horizontal options not set to End
![image](https://user-images.githubusercontent.com/92788387/146197380-2283d380-8afa-431f-955e-c3b6f0828627.png)

**Expected behavior** - Native WinUI
![image](https://user-images.githubusercontent.com/92788387/146198577-566858d0-9876-4bd3-9ae3-dc7a4b741692.png)

### Steps to Reproduce

1. Try below code
```
<StackLayout FlowDirection="RightToLeft" Orientation="Horizontal">
        <Button Text="1" HeightRequest="50"/>
        <Button Text="2"  HeightRequest="50"/>
        <Button Text="3"  HeightRequest="50"/>
    </StackLayout>
```

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 9.0, Windows SDK 10.0.19041

### Did you find any workaround?

No

**Comment by wenwen60** [comment]
Reproduce on Android 11, attach repro sample
[MauiApp16.zip](https://github.com/dotnet/maui/files/8150957/MauiApp16.zip).
