### ISSUE TITLE
[Windows] Application crash when call a DisconnectHandler while remove the view.

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#3787]
### Description

We are creating a custom layout that holds a list of views and has an option to remove the views (removing view calls disconnect handler). Application crash while removing the view on windows, other platforms (Android, iOS, Mac) working fine. 

### Steps to Reproduce

[DisconnectHandlerWindows.zip](https://github.com/dotnet/maui/files/7728047/DisconnectHandlerWindows.zip)

1. Run the sample
2. click the remove label button 
3. application crash.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

No

### Relevant log output

```shell
System.InvalidOperationException: 'NativeView cannot be null here'
```

**Comment by Sasikumar3595** [comment]
@Redth ,

We are still facing this issue in preview 12.

**Comment by Redth** [comment]
Yes, the fix was merged too late for preview 12, it will be in preview 13.
