### ISSUE TITLE
[WinUI] Border disappears when content placed inside.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#3791]
### Description

On WinUI, whenever you have content placed within a border visible, the border and its background will disappear. This does not happen on iOS and Android. I've attached a reproduction project to show this.

This is how it looks on first run.
![image](https://user-images.githubusercontent.com/898335/146419938-3ea1f7d3-2494-4663-8af3-3fc2fbda087d.png)

When you make the image inside visible, the border and its background disappear.
![image](https://user-images.githubusercontent.com/898335/146420009-cf4a070c-3942-4779-8c9c-c98f425ee150.png)

For reference, this is how it looks on Android:
![image](https://user-images.githubusercontent.com/898335/146419825-23e0b47e-d14b-47d7-85cd-bd8299c2ae98.png)

### Steps to Reproduce

Run this reproduction project.

[MauiBorderBug.zip](https://github.com/dotnet/maui/files/7729283/MauiBorderBug.zip)

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK

**Comment by mattscheffer** [comment]
Repro with the above project (after some minor changes). Border and background disappear after pressing the button on Windows. Tested with 17.2.0 Preview 1.

**Comment by v-xiaofchen** [comment]
Verified repro with windows and the above project.

**Comment by VSadov** [comment]
Fixed in #5324
