### ISSUE TITLE
Visual Studio Professional 2022 Preview 17.1.0 Preview 1.1 throwing error on initial app start

### ISSUE THREAD

**Issue by zpertee** [dotnet/maui#3792]
### Description

After a fresh install Visual Studio 2022 on Windows 11 I attempt to create a .NET Maui Blazor App.  Immediately after selecting the template on Visual Studio, I chose to run it on my Windows machine and made sure that I had the proper .net 6 sdk indicated.  I made zero code changes and just rolled with the initial template.  

Unfortunately, I receive the following error: : C:\Users\User\nuget\packages\microsoft.windowsappsdk\1.0.0-preview3\build\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(616,9): Xaml Internal Error error WMC9999: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)).  I cannot continue any farther due to this error.    

I am not sure how to resolve and I have attempted to uninstall & reinstall Visual Studio multiple times as well as "run as administrator" and unfortunately none of these methods work for me.  Any help would be greatly appreciated.  

### Steps to Reproduce

1.  Create new .Net Maui Blazor App.  
2.  Set configuration to Windows Machine & set to .net6.0-windows10.0.19041.
3.  Run solution 

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by emceelovin** [comment]
this could be caused by having hot reload enabled. i run preview 11, and it was mentioned that hot reload will not work. i disabled it before i rebuilt my project with the preview-11 workloads, so i'm just assuming that might be the case

**Comment by mattscheffer** [comment]
No repro with 17.2.0 Preview 1. Tested with Windows Machine and ensured project was targeting .net6.0-windows10.0.19041. Hot reload is enabled.

![image](https://user-images.githubusercontent.com/10537189/154155221-28f0ff65-7a85-43d1-920f-2694fb1a142c.png)
