### ISSUE TITLE
ControlTemplates loaded from Styles fail to load correctly when not using XAMLCompilation

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#3793]
### Description

The following XAML will crash at startup if you don't enable XAML Compilation

![image](https://user-images.githubusercontent.com/5375137/146427630-a595651e-aaae-4b63-8a06-cfd418020781.png)

Currently it seems like XAML compilation isn't working with .NET MAUI apps at all so you can't really test and see it working with "Compile" enabled. This issue also exists on XF so you can test it there with the same XAML and you will see it work with `Compile` vs `Skip`

### Steps to Reproduce

Run the attached reproduction
[ControlTemplateLoadFromXaml.zip](https://github.com/dotnet/maui/files/7729614/ControlTemplateLoadFromXaml.zip)

You can also see this on XF by running our Control Gallery and going to

RadioButtonGallery => RadioButton Template from Style (TemplateFromStyle.XAML)

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All of them

### Did you find any workaround?

Not on .NET MAUI

**Comment by StephaneDelcroix** [comment]
Is it normal that your `ControlTemplate` doesn't contains any `ContentPresenter` ?

**Comment by PureWeen** [comment]
The sample provide was just copy pasted from our Xamarin Forms gallery tests 

https://github.com/dotnet/maui/blob/c8939a51d6a48e68849c5cf6c5bba4c985087874/src/Controls/samples/Controls.Sample/Pages/Controls/RadioButtonGalleries/TemplateFromStyle.xaml#L9

@hartez  ?  Any reason you created all those samples without a `ContentPresenter`?

**Comment by StephaneDelcroix** [comment]
my wrong, it does have a ContentPresenter

**Comment by StephaneDelcroix** [comment]
I can reproduce this in a unittest
