### ISSUE TITLE
TapGestureRecognizer doesn't call Tap handler when used in a DataTemplate

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/maui#3796]
### Description

TapGestureRecognizer doesn't call Tap handler when used in a DataTemplate. It works fine outside of DataTemplate (directly in Page layout). For comparison, I put a button nearby and the same handler is getting called normally regardless of DataTemplate.

```XAML
<DataTemplate x:Key="MyCoolDataSetTemplate">
            <StackLayout Orientation="Horizontal">
                <Label Text="ClickMe">
                    <Label.GestureRecognizers>
                        <TapGestureRecognizer Tapped="ClickMe_Clicked" />
                    </Label.GestureRecognizers>
                </Label>
                <Button Text="ClickMe"  Clicked="ClickMe_Clicked" />
            </StackLayout>
        </DataTemplate>

        <Button x:Name="StatusButton" Text="Test Me">
        </Button>

        <StackLayout 
            BindableLayout.ItemsSource="{Binding Items}" 
            BindableLayout.ItemTemplate="{StaticResource MyCoolDataSetTemplate}" />
```

```C# (codebehind)
public void ClickMe_Clicked(object sender, EventArgs e)
        {
            StatusButton.Text = Environment.TickCount.ToString();
        }
```

```C# (view model)
 public int[] Items { get; } = new [] { 1, 2 };
```

The video demo of the issue is below:
https://user-images.githubusercontent.com/3697084/146444396-4c06a91f-612c-449d-b209-dfdcaae3ccf2.mov

I have also confirmed that this layout works for Windows platform and doesn't work for at least MacCatalyst.

### Steps to Reproduce

1. File a new MAUI project `dotnet new MAUI -n "BugRepro"
2. Define xaml, codebehind and viewmodel as specified above
3. Run for MacCatalyst platform: `dotnet build -t:Run -f net6.0-maccatalyst`

### Version with bug

Preview 11

### Last version that worked well

Preview 10 (current)

### Affected platforms

macOS

### Affected platform versions

maccatalyst 13.1

### Did you find any workaround?

Use buttons instead

### Relevant log output

```shell
N/A
```

**Comment by PureWeen** [comment]
@alexeystrakh this is fixed on P12

To workaround this on P11 you can add an event handler to HandlerChanged and then set UserInteractionEnabled = true on the native control
