### ISSUE TITLE
[iOS, Mac] Pan gesture not working while using clip

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#3800]
### Description

We are creating a custom layout that holds a list of layouts in a horizontal manner and using pan gestures to handle the layout switching. In that case, the parent panel holds the layout larger than its size and using pan gestures to view all the child layouts.

In the scenario, render the custom layout inside the grid then it render outside of the grid. So using clip on control to remove the custom layout content overflow. But it removes the pan gesture touch from it layout in Mac and iOS platform. 

### Steps to Reproduce

[DisconnectHandlerWindows 2.zip](https://github.com/dotnet/maui/files/7734624/DisconnectHandlerWindows.2.zip)

1. Run the sample
2. Pan/swpie the layout after the scroll view does not trigger pan gesture pan updated event.

Actual Output:

https://user-images.githubusercontent.com/44917578/146537412-592336b7-a209-4f4d-b792-92ed57423a02.mov

Expected Output:

https://user-images.githubusercontent.com/44917578/146537487-f6a0d952-9bbe-4dcb-8daf-b2328ba225e6.mov

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No

**Comment by shimingsg** [comment]
Verified repro with iPhone 13 pro max IOS 15.2 and the above project.

**Comment by QianaJiao** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 4. Not Repro on iOS Platform with above project.
![3800](https://user-images.githubusercontent.com/91244512/233331881-2145a95f-28a4-48ff-9170-1f738ee33947.gif)
