### ISSUE TITLE
RuntimeConfigParserTask

### ISSUE THREAD

**Issue by onurart** [dotnet/maui#3810]
### Description

First of all hi everyone...

When I try to open the project I just created, it gives me such an error. I can't understand why. Thank you from now, Regards ...

___________________________________________________________________________________________

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4036	The "RuntimeConfigParserTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64" directory.	BirTestDenemesi	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.10.59\targets\Microsoft.Android.Sdk.RuntimeConfig.targets	36	

### Steps to Reproduce

I'm a New User

### Version with bug

Preview 8

### Last version that worked well

Preview 8

### Affected platforms

Android

### Affected platform versions

Yeni Deniyorum 

### Did you find any workaround?

-

### Relevant log output

```shell
No
```

**Comment by onurart** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/48415080/146660492-05fa4888-ae8d-4124-86d8-cfa88d6e865d.JPG)

**Comment by wenwen60** [comment]
I can't repro your issue. Could you please provide a repro sample?
