### ISSUE TITLE
Archiving .NET MAUI Blazor Android apps not working 

### ISSUE THREAD

**Issue by patrykplay** [dotnet/maui#3816]
### Description

I need to release .apk/.aab signed file. When I am trying to install my archived package, application is crashed right after loading BlazorMobileView on the device.
Deployment via release mode doesnt work also, but in debug mode all works fine.

Unfortunately I have no idea how can I take logs, because in debug mode works all fine, but in release mode it crashes right after loading app.
Do you have idea what need to be changed (eg. included values in .csproj) in order to application works fine?
I have included two extra properties in .csproj file:
```
		<!--Include android supported architectures-->
		<RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
		<!--Force apk build for android-->
		<AndroidPackageFormat>apk</AndroidPackageFormat>
```
But it looks like not enough.

### Steps to Reproduce

1. Create new project from template "MAUI Blazor App".
2. Add following properties to .csproj file:
```
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0-android|AnyCPU'">
		<!--Include android supported architectures-->
		<RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
		<!--Force apk build for android-->
		<AndroidPackageFormat>apk</AndroidPackageFormat>
	</PropertyGroup>
```

3. Build project in release mode.
4. Press 'Archive...' option by right click on project.
5. Sign apk your own certificate.
6. Install apk on your device. 
7. Wait for start app. (start is crashing)

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

I have no workaround.

### Relevant log output

```shell
I have no idea how to catch exception in release mode on the device.
```

**Comment by Seanxwy** [comment]
Hope it can be repaired soon

**Comment by soundaranbu** [comment]
Same problem when I tried the .NET Podcast app. I'm updating the issues that I faced here 
https://github.com/microsoft/dotnet-podcasts/issues/30

**Comment by shimingsg** [comment]
Not reproducible with Android 11. app start up succeed.
![image](https://user-images.githubusercontent.com/20982341/154904623-3cdea211-de6f-49f7-bbbf-7fe6b56a2f33.png)
![image](https://user-images.githubusercontent.com/20982341/154904528-3144b915-fa38-45fc-90ab-a49f7206d415.png)

**Comment by Redth** [comment]
Information in #4377
