### ISSUE TITLE
VisualElement Focused, Unfocused, and SizeChanged events aren't getting fired.

### ISSUE THREAD

**Issue by kla50** [dotnet/maui#3820]
### Description

I've created a simple MAUI App with MainPage containing a Grid containing a fixed width column for a Label and a * column for an Entry control.  I want the Entry control to have Focus when the window is displayed but using the Focus method does not work.  In fact, it seems like none of the events, properties, or functions in the VisualElement ancestor of the Entry control work.  I tested events on Entry, InputView and BindableObject ancestors and they seem to work.  I setup handlers for Focused, Unfocused, and SizeChanged - none of them are executed.  I accessed the IsFocused property, and it is always false.  Any ideas why the VisualElement events, functions, and properties don't work?  At least, the ones related to control focus.  Interestingly, a PropertyChanged event for Size occurs on the BindableObject but it's not making its way to SizeChanged event on VisualElement.

### Steps to Reproduce

1. Create a .NET Maui App using ".NET MAUI App (Preview)" template.
2. Comment out ResourceDictionary content in App.xaml
3. Change MainPage to contain a two column (200,*) and two row (auto,*) grid.  Add a Label to row 0 column 0, and Entry to row 0 column 1.
4. Add handlers for Completed, TextChanged, Focused, Unfocused, SizeChanged, and PropertyChanged events in MainPage ctor.  In the handler methods just dump event details to output using Debug.WriteLine.
5. In MainPage ctor try setting focus to Entry control by calling its Focus method.
6. In the TextChanged handler method dump the state of the IsFocused property to Output window using Debug.WriteLine.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

I haven't been able to find a workaround, yet.

**Comment by CDboyOne** [comment]
I am faced with the same issue too.

**Comment by faldeland** [comment]
Same here

**Comment by nmarazov** [comment]
Same behavior with preview 12

**Comment by danielftz** [comment]
Does this issue relate to the fact that the keyboard for Entry will never go away by tapping anywhere outside the entry/keyboard?

**Comment by VincentBu** [comment]
hi @kla50 , Would you like to verify this project? I didn't repro on my machine.
[MauiApp3820.zip](https://github.com/dotnet/maui/files/8369247/MauiApp3820.zip)

**Comment by kla50** [comment]
Hi VincentBu,

I've run some tests using the solution in MauiApp3820.zip and have the following observations.  I have the VS settings "Debugging > XAML Hot Reload" set as follows:
***@***.***


  1.  When the app is run the "myEntry" control does not have focus.  I have to press the tab key three times before focus finally reaches "myEntry".  This seems to indicates that the "myEntry.Focus();" statement in the MainPage constructor is not working as expected.
  2.  I modified AppShell.xaml.cs to:
namespace MauiApp3820;

using System.Diagnostics;

public partial class AppShell : Shell {
public AppShell() {
InitializeComponent();
Focused += AppShell_Focused;
Unfocused += AppShell_Unfocused;
}

private void AppShell_Unfocused(Object sender, FocusEventArgs e) {

Debug.WriteLine($"{nameof(AppShell_Unfocused)}: VisualElement={e.VisualElement}, IsFocused={e.IsFocused}");
}

private void AppShell_Focused(Object sender, FocusEventArgs e) {
Debug.WriteLine($"{nameof(AppShell_Focused)}: VisualElement={e.VisualElement}, IsFocused={e.IsFocused}");
}
}

  1.  I modified MainPage.xaml.cs to:
namespace MauiApp3820;

using System.Diagnostics;

public partial class MainPage : ContentPage {
int count = 0;

public MainPage() {
InitializeComponent();

Focused += MainPage_Focused;
Unfocused += MainPage_Unfocused;

myEntry.TextChanged += MyEntry_TextChanged;
myEntry.Focused += MyEntry_Focused;
myEntry.Unfocused += MyEntry_Unfocused;
myEntry.SizeChanged += MyEntry_SizeChanged;
myEntry.PropertyChanged += MyEntry_PropertyChanged;

myEntry.Focus();

}

private void MainPage_Unfocused(Object sender, FocusEventArgs e) {
Debug.WriteLine($"{nameof(MainPage_Unfocused)}: VisualElement={e.VisualElement}, IsFocused={e.IsFocused}");
}

private void MainPage_Focused(Object sender, FocusEventArgs e) {
Debug.WriteLine($"{nameof(MainPage_Focused)}: VisualElement={e.VisualElement}, IsFocused={e.IsFocused}");
}

private void MyEntry_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e) {
System.Diagnostics.Debug.WriteLine($"MyEntry_PropertyChanged: {e.PropertyName}");
}

private void MyEntry_SizeChanged(object sender, EventArgs e) {
System.Diagnostics.Debug.WriteLine("MyEntry_SizeChanged");
}

private void MyEntry_Unfocused(object sender, FocusEventArgs e) {
System.Diagnostics.Debug.WriteLine("MyEntry_Unfocused");
}

private void MyEntry_Focused(object sender, FocusEventArgs e) {
System.Diagnostics.Debug.WriteLine("MyEntry_Focused");
}

private void MyEntry_TextChanged(object sender, TextChangedEventArgs e) {
System.Diagnostics.Debug.WriteLine("MyEntry_TextChanged");
var f = myEntry.IsFocused ? "focused -> true" : "focused -> false";
System.Diagnostics.Debug.WriteLine($"MyEntry_TextChanged: {f}");

}

private void OnCounterClicked(object sender, EventArgs e) {
count++;
CounterLabel.Text = $"Current count: {count}";

SemanticScreenReader.Announce(CounterLabel.Text);
}
}

  1.  The above two changes just added handlers for the Focused and Unfocused events higher in the visual tree.   All events in MAUI appear to bubble up the visual tree with no way to short circuit the bubble.  In WPF you can set the value of the Handled property of the EventArgs subclass to stop the bubble.  Also, this subclass in WPF has an OriginalSource property which contains the actual control that generated the event.  MAUI has neither of these properties.  So all that can be gleaned from the handlers I added to the AppShell and MainPage is a rough idea where in the visual tree the event originated.  That is, you'll only see debug messages in the handlers above whatever element actually generated the event.
  2.  Debug the app with the above changes.  Once it is loaded do not interact with it.  The Output > Debug view shows no Focused or Unfocused event messages. Go directly to the "Live Visual Tree" and traverse down the [DesktopWindowXamlSource] node to [WindowRootView] and select it.  Expand the "Computed Values" node in "Live Property Explorer" and the FocusState is either Keyboard or Pointer (I've seen both during testing).  I'm not sure why this object is getting focus.  I would expect focus to be placed on the first focusable element in the UI created by the developer.

     *   Now make sure the app is selected and then press the tab key.  The FocusState of WindowRootView changes to Unfocused, and debug messages are generated for the Focused and Unfocused events at AppShell.  So we know that the elements the generated these events are somewhere between the AppShell and MainPage with WindowRootView generating the Unfocused event.  However, I was unable to determine what element received focus.  I traversed the all the nodes in the Live Visual Tree looking for an element with focus, but all had a FocusState of Unfocused.
     *   Note that every time you click away from the app (e.g. activate VS) there is an Unfocused event at AppShell.  And whenever you navigate back to the app you'll see a Focused event at AppShell.  So it seems that these events match application activated and deactivated events.
     *   Activate the app again and press the tab key a second time.  You get a Focused and Unfocused event at the AppShell.  I could not determine what element actually got focus.
     *   Press tab a third time and you get.

        *   AppShell unfocused
        *   MyEntry focused bubbling to MainPage focused bubbling to AppShell focused.
        *   If you traverse down the visual tree you'll eventually find a TextBox with focus.
  1.  Anyway, now regarding the original issue for this ticket, events not firing.  We can safely say that this is resolved in the current release of MAUI.  But now that they're working I feel there are issues with the functionality as currently implemented.

     *   Setting focus to a specific element in the UI at app startup doesn't work with just a call to the Focus method on the control in the constructor.  You have to either click on the element or press tab until it gets focus - three times when using Shell.

        *   Note that the Focus method does work after you start interacting with the app.  It just doesn't work to set focus to a specific element at startup.
     *   There is at least one non-user created element present in the focus cycle (i.e. WindowRootView) that you can't seem to remove.
     *   There doesn't seem to be any way to control tab order.  For example, TabIndex and IsTabStop properties.  Some mechanism needs to be added to control tab order.
     *   The EventArgs subclass passed to Focused and Unfocused event handlers need a way to short circuit bubbling of the event (e.g. Boolean Handled property), and a way to identify the source element that actually generated the event (e.g. OriginalSource property).
  1.  So can these be addressed in this ticket or do I need to create another one for these?  I suspect these are functionality requests and not bugs (except maybe the Focus method not working at startup).

Thanks,
Ken

**Comment by davidortinau** [comment]
@kla50 we will close this issue. Please do open a new issue for your additional feedback and we'll continue there.
