### ISSUE TITLE
Occasional endless maui project creation in VS 2022 Version 17.1.0 Preview 1.1

### ISSUE THREAD

**Issue by KirillPom** [dotnet/maui#3821]
### Description

Occasional endless maui project creation in VS 2022 Version 17.1.0 Preview 1.1

### Steps to Reproduce

Run VS.
Create new maui project.
Endless spinner (10 min) "Creating project".

![image](https://user-images.githubusercontent.com/65759581/146938358-c8488602-3c20-497f-803d-a1c86cf74075.png)

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

 VS 2022 Version 17.1.0 Preview 1.1

### Did you find any workaround?

yes.restart VS.

**Comment by d066hie** [comment]
thanks

**Comment by PureWeen** [comment]
@KirillPom can you click "Continue without code" and then use the feedback tool inside visual studio to see if you can capture the crash and log the issue that way? Even if you can't can you log an issue using that feedback tool? The feedback tool will capture logs that will be helpful for figuring out your issue
