### ISSUE TITLE
FlexLayout > Frame > FlexLayout > Any Content throws error.

### ISSUE THREAD

**Issue by chris-ux** [dotnet/maui#3826]
### Description

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="LayoutTests.FlexLayoutTest">

    <FlexLayout>
        <Frame>
            <FlexLayout>
                <Label>Hi</Label>
            </FlexLayout>
        </Frame>
    </FlexLayout>

</ContentPage>

```
![image](https://user-images.githubusercontent.com/1118231/147015270-8680d181-f337-474d-8ca6-9ab2a0b74319.png)

### Steps to Reproduce

Create new Maui App
Use Code Above in a content page.
Run

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

**Comment by mattscheffer** [comment]
I can repro on 17.2.0 Preview 1 using Windows sim. Repro project can be found here:

https://microsoft.sharepoint.com/:u:/r/teams/Mauitriage/Shared%20Documents/General/ReproProjects/3826.zip?csf=1&web=1&e=sJU4wd

**Comment by shimingsg** [comment]
repro proj could be found here:
[3826.zip](https://github.com/dotnet/maui/files/8130147/3826.zip)

**Comment by jsuarezruiz** [comment]
Investigating this, there is a loop in the `ArrangeChildren` method in the `FlexLayoutManager` class.

**Comment by jsuarezruiz** [comment]
Is the same or related with https://github.com/dotnet/maui/issues/4081 and https://github.com/dotnet/maui/issues/4168

**Comment by davidortinau** [comment]
I'm unable to repro this on main (rc2) on iOS. I did have to provide explicit sizing to get the content to appear tho.

<img width="401" alt="Screen Shot 2022-04-21 at 8 12 48 PM" src="https://user-images.githubusercontent.com/41873/164577291-8708b0c7-05ad-4484-b6c8-1b120e749b2b.png">
