### ISSUE TITLE
[Bug]iOS,Android: Grid not measured size by it's content

### ISSUE THREAD

**Issue by AlexeyZhukoff** [dotnet/maui#3832]
### Description

Grid fill all available page space but has VerticalOptions="Center"

```xml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="gridexampl.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">
             <Grid BackgroundColor="Gray" VerticalOptions="Center" HorizontalOptions="Center" >
                <Label Text="Text" BackgroundColor="Red" VerticalOptions="Center" HorizontalOptions="Center"/>
             </Grid>
</ContentPage>
```

### Expected Behavior
Grid must be mesuared size by their content
![Simulator Screen Shot - iPhone 13 Pro Max - 2021-12-22 at 15 10 21](https://user-images.githubusercontent.com/14820834/147090856-8b04bbf1-850a-4254-9774-8d37f557db07.png)

### Actual Behavior
Grid fill all empty space on page
![Simulator Screen Shot - iPhone 13 Pro Max - 2021-12-22 at 15 11 57](https://user-images.githubusercontent.com/14820834/147091010-ab67cf00-4955-4ee8-96d7-f6412723c832.png)

I Attached Example
[gridexampl.zip](https://github.com/dotnet/maui/files/7762533/gridexampl.zip)

### Steps to Reproduce

1. Open example .NET MAUI App
2. Run App

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android 11

### Did you find any workaround?

No

**Comment by mattscheffer** [comment]
Verified Repro with 17.2.0 Preview 1 using Android 11. 

![image](https://user-images.githubusercontent.com/10537189/154585181-5c6d47b6-1983-4b7e-8f71-5c8dd4672796.png)

**Comment by wenwen60** [comment]
Reproduce on Android 11 with above project.

**Comment by KonyukhovSergey** [comment]
Hello, we are developing [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/) and experienced the same issue in the scenario with layout our controls. This issue has a high priority for us and we do not have a workaround. Thank you for your help.

**Comment by hartez** [comment]
I _think_ #7116 fixes this - noting it here so I can verify.

**Comment by AntonKosenkoDX** [comment]
Hello! Any update on this issue?

**Comment by hartez** [comment]
Verified - this is fixed on the net6.0 branch and the fix should be in SR2.
