### ISSUE TITLE
Delete the Visual Property or Make it work

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#3833]
### Description

For .NET MAUI we are currently not planning on bringing over the Material Renderers. Google says it’s dropping Material Design components on iOS in favor of Apple’s UIKit. 

The possibly useful bodies of work that still exist here are
- The android material renderers all work with AndroidX libraries we are already importing so it'd be fairly easy to make these still work. For example, the MaterialEntry is the standard recommended control to use for accessibility on android. 
- We could still use visual as a way for people to pivot between handlers. 3rd party libraries have developed material libraries via visual themselves so it's probably useful

### (Public) API Changes

Nothing or Deleting Visual

### Usage Scenarios

Continue to allow users to pivot handlers based on a property 

### Backward Compatibility

Yes? or no?

### Difficulty

Medium

**Comment by Redth** [comment]
Fixed by #4428
