### ISSUE TITLE
Sometimes Password Entry Throw 'Specified argument was out of the range of valid values'

### ISSUE THREAD

**Issue by chaoyebugao** [dotnet/maui#3834]
### Description

I am using Entry as password under Windows machine. When I tried type in password with password selected, an exception would throw, so cause app crashed.

Video:
https://user-images.githubusercontent.com/3005574/147116536-6f0daa63-3abc-4107-8834-af335d23f9b4.mp4

### Steps to Reproduce

1. Use an Entry as password one:
Xaml:
``` xml
<Entry Text="{Binding LoginPassword}" Placeholder="Login Password" IsPassword="True" ReturnType="Next"/>
```

View Model:
``` C#
private string loginPassword;
/// <summary>
///login password
/// </summary>
public string LoginPassword { get => loginPassword; set => SetProperty(ref loginPassword, value); }
```

2. Type something.

3. Select What you just typed.

4. Type again,  an Exception should occur.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

Nope~

### Relevant log output

```shell
Index and count must refer to a location within the string. (Parameter 'count')
{"Specified argument was out of the range of valid values."}
    ActualValue: null
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233086
    HelpLink: null
    InnerException: null
    Message: "Specified argument was out of the range of valid values."
    ParamName: null
    Source: null
    StackTrace: null
    TargetSite: null
```

**Comment by jsuarezruiz** [comment]
@chaoyebugao Could you try again with the latest Preview?. Cannot reproduce the issue.
![issue-3834](https://user-images.githubusercontent.com/6755973/149906617-258103e0-115a-4db5-80d5-e8518d71df96.gif)

In case you still have the issue, could you attach a small sample where reproduce it?. Thanks!.
