### ISSUE TITLE
[Bug] iOS: Image isn't shown on the screen if it is added into project as EmbeddedResource

### ISSUE THREAD

**Issue by MariyaGordeeva** [dotnet/maui#3845]
### Description

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp.MainPage" BackgroundColor="White">

     <Image Source="{Binding Image}"/>

</ContentPage>
```

```c#
namespace MauiApp {
  public class ViewModel {
          public ImageSource Image { get; set; }
  
          public ViewModel() {
              Image = ImageSource.FromResource("MauiApp.Images.Andrew_Fuller.jpg");
          }
  }
}
```
### Expected Behavior

Image should be shown on the screen

### Actual Behavior

Image is not shown on iOS simulator (on Android emulator image is visible)

<img width="868" alt="Screenshot 2021-12-23 at 16 00 57" src="https://user-images.githubusercontent.com/41049348/147244184-1ce94db2-91e1-4fbf-9a63-cc265a7073f7.png">

### Stacktrace

<img width="596" alt="Screenshot 2021-12-23 at 16 02 31" src="https://user-images.githubusercontent.com/41049348/147244433-af298cd2-7988-4334-b391-b036b7210efb.png">

### Steps to Reproduce

1. Create a MAUI app
2. Add Image to the project as EmbeddedResource
2. Put Image on the MainPage.xaml
4. Deploy to iOS simulator

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by XamlTest** [comment]
Verified Repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32219.17.main]. Repro Project: [3845.zip](https://github.com/dotnet/maui/files/8197149/3845.zip)

**Comment by davidortinau** [comment]
Android:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/41873/165653585-9dc8cd71-4630-4343-96ba-f4580fe64c46.png">

iOS:

![Simulator Screen Shot - iPhone 13 Pro - 2022-04-28 at 09 10 11](https://user-images.githubusercontent.com/41873/165771995-772a3672-7efb-40b6-99fe-030da0b7c406.png)

Closing as fixed.
