### ISSUE TITLE
FlexLayout doesn't measure out to full height when placed inside ScrollView

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#3848]
### Description

If you have a FlexLayout inside a ScrollView the FlexLayout will only ever measure to the height of the ScrollView

```XAML
        <ScrollView Grid.Row="1" HeightRequest="300">
            <FlexLayout
                Direction="Row"
                Wrap="Wrap"
                AlignItems="Center"
                AlignContent="Center"
                BindableLayout.ItemsSource="{Binding Items}"
                BindableLayout.ItemTemplate="{StaticResource ColorItemTemplate}" />
        </ScrollView>
```

If you replace the `FlexLayout` with a `StackLayout` then you're able to Scroll.

### Steps to Reproduce

[ScrollViewFlex.zip](https://github.com/dotnet/maui/files/7770024/ScrollViewFlex.zip)

1) run project
2) you should be able to scroll up and down and see more squares
3) if you switch to a StackLayout then it's scrollable

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All of them

### Did you find any workaround?

If you set an explicit height on the FlexLayout then you can scroll the FlexLayout

**Comment by chris-ux** [comment]
Alternatively, when not in stack layout, the height of the FlexLayout grows "infinitely", seemingly unaware of the height of its content.

https://github.com/dotnet/maui/discussions/3828

**Comment by v-xiaofchen** [comment]
Verified repro with windows and the above project.
