### ISSUE TITLE
HideKeyboard

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3850]
### Description

Currently we don’t have an option to hide the keyboard and we have to use platform specific code

it will be great if you include this in MAUI

### Public API Changes

`Device.HideKeyboard`

### Intended Use-Case

This is required to hide the keyboard and start another function such as show a busy indicator or a message once the user has completed typing especially with the fix number entries, eg. PIN

**Comment by SarthakGz** [comment]
@jrahma isn't entryxname.UnFocus(); would do trick ?

**Comment by v-longmin** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by hartez** [comment]
@jrahma sorry for the confusion, we now realize this was a feature proposal and not a bug report. You can ignore the comments from the msftbot account - this won't be closed.

**Comment by PureWeen** [comment]
> @jrahma isn't entryxname.UnFocus(); would do the trick ?

AFAICR the platforms don't default to showing the keyboard when something is focused programmatically. We should give the option to the user to influence the keyboard but not make a guess at it for them.

**Comment by PureWeen** [comment]
[Duplicate](https://github.com/dotnet/maui/issues/3739)

**Comment by jrahma** [comment]
> @jrahma isn't entryxname.UnFocus(); would do the trick ?

Yes that works for Hide but not for ShowKeyboard when TapGesture
