### ISSUE TITLE
Additional KeyboardFlags

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3851]
### Description

Hi,

Please add the following to the KeyboardFlags Enum:

ForceCapital / ForceUpper : to force all letters in CAPS.
ForceSmall / ForceLower : to force all letters in Small.

Thanks,

### Public API Changes

`KeyboardFlag.ForceUpper`

`KeyboardFlag.ForceLower`

### Intended Use-Case

To force or upper in many cases such as password, email, etc..

**Comment by v-longmin** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by hartez** [comment]
@jrahma sorry for the confusion, we now realize this was a feature proposal and not a bug report. You can ignore the comments from the msftbot account - this won't be closed.

**Comment by mattleibow** [comment]
Are you thinking that you want the keyboard UI to only allow uppercase/lowercase? Like the "shift" key is disabled?

Or are you thinking that the output of the keyboard? So just the contents in the text box? If this is the case, what about the `TextTransform` property?
