### ISSUE TITLE
FlexLayout doesn't size correctly.

### ISSUE THREAD

**Issue by chris-ux** [dotnet/maui#3852]
### Description

When not wrapped within ScrollView or StackLayout (which have their own bugs with Flex: https://github.com/dotnet/maui/issues/2091 https://github.com/dotnet/maui/issues/3848), the FlexLayout expands infinitely or at least to the visible widow height.  Using the code below, I expected to see a DarkGray background, but the OrangeRed FlexLayout took up the entire screen. 

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="LayoutTests.MainPage"
             BackgroundColor="DarkGray">

    <FlexLayout BackgroundColor="OrangeRed" 
                VerticalOptions="Start"
                FlexLayout.AlignSelf="Start"
                AlignItems="Start" 
                Wrap="Wrap"
                AlignContent="Start"
                >
        <Label BackgroundColor="AliceBlue" FlexLayout.Grow="1" FlexLayout.Basis="20%">Flex 1</Label>
        <Label BackgroundColor="BlanchedAlmond" FlexLayout.Grow="1" FlexLayout.Basis="20%">Flex 2</Label>
        <Label BackgroundColor="CornflowerBlue" FlexLayout.Grow="1" FlexLayout.Basis="20%">Flex 3</Label>
        <Label BackgroundColor="DeepSkyBlue" FlexLayout.Grow="1" FlexLayout.Basis="20%">Flex 4</Label>
        <Label BackgroundColor="ForestGreen" FlexLayout.Grow="1" FlexLayout.Basis="20%">Flex 5</Label>
        <Label BackgroundColor="Gold" FlexLayout.Grow="1" FlexLayout.Basis="20%">Flex 6</Label>
        <Label BackgroundColor="HotPink" FlexLayout.Grow="1" FlexLayout.Basis="20%">Flex 7</Label>
        <Label BackgroundColor="Ivory" FlexLayout.Grow="1" FlexLayout.Basis="20%">Flex 8</Label>
        <Label BackgroundColor="Khaki" FlexLayout.Grow="1" FlexLayout.Basis="20%">Flex 9</Label>
    </FlexLayout>
</ContentPage>
```

![image](https://user-images.githubusercontent.com/1118231/147016621-631a67ef-eafe-42eb-b18f-56006f10757e.png)

---

Further, I tried to contain the flexlayout in a grid, and it actually continued to have the same behavior.

Even when contained inside a grid with row set to auto, FlexLayout takes up entire screen. (Screenshot with black background)

When I use a HorizontalStackLayout the height is correct. (Screenshot with Almond Background)

It feels like the FlexLayout container doesn't seem to measure itself based on children and always expands to full height of the device's window.

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="LayoutTests.MainPage">
    
    <Grid RowDefinitions="Auto, *, Auto">
        <Grid RowDefinitions="Auto" ColumnDefinitions="Auto, *, Auto" ColumnSpacing="8" BackgroundColor="Black" GridLayout.Row="0">
            <HorizontalStackLayout GridLayout.Row="0" GridLayout.Column="0">
                <Label >TopBar</Label>
            </HorizontalStackLayout>

            <FlexLayout GridLayout.Row="0" GridLayout.Column="1" Wrap="Wrap" AlignContent="Start" AlignItems="Start">
                <BoxView BackgroundColor="AliceBlue" HeightRequest="40" WidthRequest="24" />
                <BoxView BackgroundColor="BlanchedAlmond" HeightRequest="24" WidthRequest="24" />
                <BoxView BackgroundColor="Chartreuse" HeightRequest="32" WidthRequest="24" />
                <BoxView BackgroundColor="DeepPink" HeightRequest="16" WidthRequest="24" />
                <BoxView BackgroundColor="Firebrick" HeightRequest="24" WidthRequest="24" />
                <BoxView BackgroundColor="Gold" HeightRequest="40" WidthRequest="24" />
                <BoxView BackgroundColor="HotPink" HeightRequest="16" WidthRequest="24" />
                <BoxView BackgroundColor="AliceBlue" HeightRequest="40" WidthRequest="24" />
                <BoxView BackgroundColor="BlanchedAlmond" HeightRequest="24" WidthRequest="24" />
                <BoxView BackgroundColor="Chartreuse" HeightRequest="32" WidthRequest="24" />
                <BoxView BackgroundColor="DeepPink" HeightRequest="16" WidthRequest="24" />
                <BoxView BackgroundColor="Firebrick" HeightRequest="24" WidthRequest="24" />
                <BoxView BackgroundColor="Gold" HeightRequest="40" WidthRequest="24" />
                <BoxView BackgroundColor="HotPink" HeightRequest="16" WidthRequest="24" />
            </FlexLayout>

            <HorizontalStackLayout GridLayout.Row="0" GridLayout.Column="2">
                <Label>TopBar</Label>
            </HorizontalStackLayout>
        </Grid>

        <Grid RowDefinitions="Auto" BackgroundColor="DarkGray" GridLayout.Row="2">
            <Label GridLayout.Row="0">BottomBar</Label>
        </Grid>
    </Grid>
</ContentPage>

```
Unexpected Flexbox Taking Entire Screen
![image](https://user-images.githubusercontent.com/1118231/147266353-e6daf87b-e45f-4db3-b70b-594e29850635.png)

Expected something closer to this, however it is horizontally broken due to this being a HorizontalStackLayout to simulate vertical expected behavior.
![image](https://user-images.githubusercontent.com/1118231/147266549-e05bff99-6539-47f2-ac36-526c52817fc4.png)

### Steps to Reproduce

Copy layout code above into a page in a new maui project.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows

**Comment by JaneySprings** [comment]
Hello, we are developing [DevExpress .NET MAUI](https://www.devexpress.com/maui/) controls and experienced the same issue in the scenario of two or more FlexLayouts in the same container such as StackLayout. In this case the Element's lay out is incorrect. This issue has a normal priority for us and we do not have a workaround. Thank you for your help.
I've replicated this issue and created a repository: https://github.com/JaneySprings/MauiFlexLayoutBug/tree/main
