### ISSUE TITLE
WebView Navigation events are not firing on Window and Android

### ISSUE THREAD

**Issue by msadeh** [dotnet/maui#3857]
### Description

Both Navigated and Navigating events are not being fire on both Windows and Android

### Steps to Reproduce

Use the sample code that working on Xamarin but not on Maui

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">

    <ScrollView>
        <StackLayout>
            
            <Label x:Name="labelLoading" Text="Loading..." IsVisible="false" />
            <WebView HeightRequest="1000" WidthRequest="1000" Source="https://dotnet.microsoft.com/apps/xamarin" Navigated="webviewNavigated" Navigating="webviewNavigating" />
        </StackLayout>
    </ScrollView>
</ContentPage>

		void webviewNavigating(object sender, WebNavigatingEventArgs e)
		{
			labelLoading.IsVisible = true;
		}

		void webviewNavigated(object sender, WebNavigatedEventArgs e)
		{
			labelLoading.IsVisible = false;
		}

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11, Windows

### Did you find any workaround?

no

**Comment by pkar70** [comment]
Why this issue is closed? This event really doesn't fire.
