### ISSUE TITLE
Installing MAUI using the instructions results in errors about missing workloads.

### ISSUE THREAD

**Issue by sander1095** [dotnet/maui#3859]
### Description

If I follow the official instructions: https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation  I end up with errors about the workloads not being installed correctly. When I then run `maui-check`, it also reports that the workloads are missing. The VS installer definitely shows them as installed.

I let maui-check repair the missing workloads, even though it suggests that you do this with the vs2022 installer. After that, everything works

### Steps to Reproduce

1. Perform the instructions from https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation
2. You will see errors about missing workloads in vs2022

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Doesnt matter

### Did you find any workaround?

Use `maui-check` which will install the workloads manually for you

**Comment by marcpopMSFT** [comment]
@sander1095 Can you list out which version of 17.1 you installed (and which branch 17.1 or main) and do you have the exact error you got complaining about workloads?

**Comment by v-xiaofchen** [comment]
Not reproducible with 17.2.0 Preview 2.0 [32209.335.main] using Windows.
