### ISSUE TITLE
Focus() seems unimplemented on Handlers

### ISSUE THREAD

**Issue by bwoebi** [dotnet/maui#3860]
### Description

Calling `Focus()` immediately returns thanks to `FocusChangeRequested` being null on VisualElements ported to use Handlers (e.g. `Editor`).

Realted to #3820 - focus handling seems to still be completely missing.

### Steps to Reproduce

Implement a simple Editor and Button.

Make the button call Focus() on the Editor on Clicked. Nothing happens.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows (at least, didn't check others)

**Comment by v-longmin** [comment]
@bwoebi Could you provide your repro project, thanks?

**Comment by bwoebi** [comment]
I have no isolated repro project for this issue. The feature was lacking, now it's been partially implemented via #4562. Let's leave this issue open until the feature is also implemented on other targets.

**Comment by shimingsg** [comment]
verified with VS 17.2.0 Preview 3.0 [32315.370.main] on Windows and Android 11, click the button and call focus method, the entry gets focused
![3860](https://user-images.githubusercontent.com/20982341/158562355-cf8f53bd-f154-4ba9-aa60-383e846d9e61.gif)

**Comment by davidortinau** [comment]
Closed based on latest comments. Please open a new issue if this is reproducible in RC3 coming soon.

**Comment by KarlSearl** [comment]
I know this is closed,  however, I can set focus on entry, but it doesn't bring up the device keyboard (when using a phone)
