### ISSUE TITLE
net6.0-android generated sources compile error(don't support covariant for return value )

### ISSUE THREAD

**Issue by zhangzifang1** [dotnet/maui#3867]
### Description

I found some compile error when I reference the package "Microsoft.ML.OnnxRuntime" and compile the net6.0-android project, the compiler come from the generated sources in path ".\obj\Debug\net6.0-android\generated\src";

it is caused by that CSharp don't support covariant for return value:
for example, below java sources:
	
	interface IName {
		public Object getName();
	}

	public class Maui implements IName {
		@Override
		public String getName() {
			return "Maui";
		}
	}

and maui will convert above java sources to below CSharp sources
	
	interface IName
	{
		public object Name { get; }
	}

	public class Maui : IName
	{
		public string Name => "Maui";
	}
you can see the return value type "string" of the property "Name" is just copied from java sources in class "Maui", it will lead to a compile error(reference Relevant log output section).

### Steps to Reproduce

1.create a maui project;
2.add the package "Microsoft.ML.OnnxRuntime" from NuGet Package Manager;
3.compile the project;
4.you will receive some compile error message, reference log section;

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

all version

### Relevant log output

```shell
---------------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0738	'OnnxMap' does not implement interface member 'IOnnxValue.Info'. 'OnnxMap.Info' cannot implement 'IOnnxValue.Info' because it does not have the matching return type of 'IValueInfo'.	MauiApp1 (net6.0-android)	C:\Work\Solutions\MauiApp1\obj\Debug\net6.0-android\generated\src\AI.Onnxruntime.OnnxMap.cs	10	Active
Error	CS0738	'OnnxMap' does not implement interface member 'IOnnxValue.Value'. 'OnnxMap.Value' cannot implement 'IOnnxValue.Value' because it does not have the matching return type of 'Object'.	MauiApp1 (net6.0-android)	C:\Work\Solutions\MauiApp1\obj\Debug\net6.0-android\generated\src\AI.Onnxruntime.OnnxMap.cs	10	Active
Error	CS0738	'OnnxSequence' does not implement interface member 'IOnnxValue.Info'. 'OnnxSequence.Info' cannot implement 'IOnnxValue.Info' because it does not have the matching return type of 'IValueInfo'.	MauiApp1 (net6.0-android)	C:\Work\Solutions\MauiApp1\obj\Debug\net6.0-android\generated\src\AI.Onnxruntime.OnnxSequence.cs	10	Active
Error	CS0738	'OnnxSequence' does not implement interface member 'IOnnxValue.Value'. 'OnnxSequence.Value' cannot implement 'IOnnxValue.Value' because it does not have the matching return type of 'Object'.	MauiApp1 (net6.0-android)	C:\Work\Solutions\MauiApp1\obj\Debug\net6.0-android\generated\src\AI.Onnxruntime.OnnxSequence.cs	10	Active
Error	CS0738	'OnnxTensor' does not implement interface member 'IOnnxValue.Info'. 'OnnxTensor.Info' cannot implement 'IOnnxValue.Info' because it does not have the matching return type of 'IValueInfo'.	MauiApp1 (net6.0-android)	C:\Work\Solutions\MauiApp1\obj\Debug\net6.0-android\generated\src\AI.Onnxruntime.OnnxTensor.cs	10	Active
```

**Comment by mattscheffer** [comment]
Bug is repro still in 32208.182.main. Repro project has been created at the following location: https://microsoft.sharepoint.com/:u:/r/teams/Mauitriage/Shared%20Documents/General/ReproProjects/3867.zip?csf=1&web=1&e=GoJpsh

**Comment by jdluzen** [comment]
I am facing this issue as well, it's a complete blocker for me.

**Comment by jdluzen** [comment]
This currently allows it to compile, have not tested it at runtime.
```
namespace AI.Onnxruntime
{
    public partial class OnnxMap : Java.Lang.Object, IOnnxValue
    {
        IValueInfo IOnnxValue.Info
        {
            get => Info;
        }

        Java.Lang.Object IOnnxValue.Value
        {
            get => (Java.Lang.Object)Value;
        }
    }

    public partial class OnnxSequence : Java.Lang.Object, IOnnxValue
    {
        IValueInfo IOnnxValue.Info
        {
            get => Info;
        }

        Java.Lang.Object IOnnxValue.Value
        {
            get => (Java.Lang.Object)Value;
        }
    }

    public partial class OnnxTensor : Java.Lang.Object, IOnnxValue
    {
        IValueInfo IOnnxValue.Info
        {
            get => Info;
        }
    }
}
```

**Comment by XamlTest** [comment]
Verified this issue on Visual Studio Enterprise 17.6.0 Preview 2.0. This issue does not repro on Android emulator (13.0-API 33) with below Project:
[3867.zip](https://github.com/dotnet/maui/files/11198742/3867.zip)
