### ISSUE TITLE
No splash screen on Windows

### ISSUE THREAD

**Issue by irongut** [dotnet/maui#3870]
### Description

Using .NET MAUI Preview 10 I created a new demo app using Shell: [irongut/MauiBeach](https://github.com/irongut/MauiBeach)

My app contains a custom splash screen:

```xml
<MauiSplashScreen Include="Resources\wave_splash.svg" Color="#BF616A" />
```

This looks great on Android & iOS but did not appear when debugging on Windows 10. At the time I assumed MAUI does not display a splash screen on Windows beause the app runs so quickly.

While updating to .NET MAUI Preview 11 I started seeing this error:

DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(33,27): error 0x80070002: Cannot install or update package 742DEB53-31C9-44E1-9020-6A7B01205723_9zz4h110yvjzm because the splash screen image [appiconfgSplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found.

(I'm not exactly sure when that started happening so it might not be Preview 11 related.)

Digging into `Platforms\Windows\Package.appxmanifest` I found this line which sets the splash screen to the default image but with a slightly different name:

```xml
<uap:SplashScreen Image="Assets\appiconfgSplashScreen.png" />
```

This was not updated automatically from the `MauiSplashScreen` property in my project file. I was able to get my app running by manually changing it to:

```xml
<uap:SplashScreen Image="Assets\wave_splashSplashScreen.png" />
```

But I still don't see my splash screen when I run my app on Windows 10. I also don't see the default splash screen when I run a new MAUI app on Windows 10.

Should I see a splash screen on Windows? Also something seems to be broken when setting the splash screen image for the Windows platform.

### Steps to Reproduce

1. Create a new app using dotnet new maui
2. Build & run on Windows 10
3. No splash screen appears

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 Pro 21H1

**Comment by IndianaGary** [comment]
I recently started encountering this error on a Maui Windows Desktop app. I went so far as completely rebuilding the app from the ground up and still have the error. I will try the workaround described above.

**Comment by mattleibow** [comment]
So there are a few things that are happening here.

Firstly, Windows with WinUI 3 for Desktop does not have a splash screen. The OS controls this part as of today. So, no matter what you have in the manifest, no splash is actually shown. That was only used from WinUI 3 for UWP.

Next, with preview 13, the generated paths of splash screens moved from `Assets\MyImageSplashScreen.png` to a root `MyImageSplashScreen.png`: https://github.com/dotnet/maui/pull/4367 All that this requires is to remove the various `Assets\*` prefix from your manifest URIs.

Finally, we have another PR coming that will generate 90% of the manifest and be consistent with all theother platforms: https://github.com/dotnet/maui/pull/2704

**Comment by igalfsg** [comment]
Is there a fix for this?

**Comment by mattleibow** [comment]
I am going to close this issue in favour or the more accurate issue on the WinUI side: https://github.com/microsoft/microsoft-ui-xaml/issues/4055

If you have any questions, please ask there as this is a feayure missing from the core SDK upon which we rely.
