### ISSUE TITLE
Unable to run wpf blazor apps via command line in c#

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#3874]
### Description

If I create the most simple app and use the blazor webview control, then if I use the process class in c# to run, then it never actually runs.

### Steps to Reproduce

1.  Create the most simple wpf blazor app
2.  Build in release mode
3. In another C# project, specify the path to the exe to actually run
4. It fails everytime.

Same thing happens if I use dotnet and the path of the file as well (probably shows what the problems are.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

The workaround for now is to use dotnet run and specify the actual project not exe.
That will work.
However, it means if somebody ever released that file to somebody, most likely would have the same issues.

**Comment by isaacrlevin** [comment]
I was just able to create a wpf app with blazor web view and run

```
dotnet publish -c Release -o Output
cd Output
.\MyApp.exe
```

and it ran. Do you have a repo with the issue somewhere?

**Comment by musictopia2** [comment]
the strange thing i found is when i was doing via visual studio project, it would fail.  However, when I created the exe and ran it, the problem did not happen.
