### ISSUE TITLE
MaUI blazor desktop application can not publish on windows 11 preview 22523

### ISSUE THREAD

**Issue by hy999** [dotnet/maui#3876]
### Description

when I cheked win-x64  with .net6.0-windows-19041 to publish the Maui project with blazor,it is responsed erro-message.

### Steps to Reproduce

1,create a maui blazor project
2,publish the project to dirctory
3,checked .net6.0-windows19041 and win-x64

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows-19041 or windows 11 dev preview.22523

### Did you find any workaround?

none

### Relevant log output

```shell
2021/12/29 18:15:57
System.AggregateException: 发生一个或多个错误。 ---> Microsoft.WebTools.Shared.Exceptions.WebToolsException: 发布时遇到错误。我们无法确定错误的原因。有关详细信息，请查看输出日志。
   --- 内部异常堆栈跟踪的结尾 ---
---> (内部异常 #0) Microsoft.WebTools.Shared.Exceptions.WebToolsException: 发布时遇到错误。我们无法确定错误的原因。有关详细信息，请查看输出日志。<---

Microsoft.WebTools.Shared.Exceptions.WebToolsException: 发布时遇到错误。我们无法确定错误的原因。有关详细信息，请查看输出日志。

===================
```

**Comment by jfversluis** [comment]
Hey everyone! I've been trying to look into this and wrote up all my findings in #4329. In an attempt to not be all over the place with this I'm closing this one, let's centralise the discussion in the aforementioned issue, thanks!
