### ISSUE TITLE
Shell FlyoutHeader at the wrong position in WinUI

### ISSUE THREAD

**Issue by chrfin** [dotnet/maui#3879]
### Description

If you set the `FlyoutBehavior` to `FlyoutBehavior.Locked` the header starts at the wrong position in my opinion:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/1186179/147693643-582e0e1c-f116-49be-bf7a-812adf915755.png">
I think the header should be next to the darker red title bar.

### Steps to Reproduce

Add a Shell, set the `FlyoutBehavior` to `FlyoutBehavior.Locked` and use the following header:
```
<Shell.FlyoutHeader>
	<BoxView BackgroundColor="Red" />
</Shell.FlyoutHeader>
```

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041

**Comment by chrfin** [comment]
@PureWeen I just upgraded to P13 and this issue is still present in my app. Do I need to change anything except upgrading to P13/VS17.2P1? Or is this not part of P13 and will be in P14/RC1?

**Comment by PureWeen** [comment]
The PR with this fix will be in P14 @chrfin
