### ISSUE TITLE
UI-Bug and warning when using Picker with ItemDisplayBinding in WinUI

### ISSUE THREAD

**Issue by chrfin** [dotnet/maui#3884]
### Description

When I use a `Picker` and set the items to some objects and use the `ItemDisplayBinding` to use e.g. the `Name` property of each item to display the items the UI does not show any labels anymore as soon as you open the selection.
I also get some warnings in the debug output (see below).

### Steps to Reproduce

1. Add a Picker in XAML like the following:
`<Picker` x:Name="PickerTest" ItemDisplayBinding="{Binding Name}" />`

2. Then add some objects as items, where the object has a `Name` property.
3. Run the app and open the picker selection -> no more labels in the picker

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041

### Relevant log output

```shell
Microsoft.Maui.Controls.Element: Warning: Microsoft.Maui.Controls.Label is already a child of Microsoft.Maui.Controls.StackLayout. Remove Microsoft.Maui.Controls.Label from Microsoft.Maui.Controls.StackLayout before adding to Microsoft.Maui.Controls.GridLayout.
Microsoft.Maui.Controls.Element: Warning: Microsoft.Maui.Controls.Picker is already a child of Microsoft.Maui.Controls.StackLayout. Remove Microsoft.Maui.Controls.Picker from Microsoft.Maui.Controls.StackLayout before adding to Microsoft.Maui.Controls.GridLayout.
```

**Comment by v-xiaofchen** [comment]
Not reproducible with 17.2.0 Preview 2.0 [32209.335.main] using Windows. Here are the results. 
![Picture4](https://user-images.githubusercontent.com/99376012/155286696-74e443ae-bb78-4c7c-9531-0cf4fdbd1bb6.png)
![Picture5](https://user-images.githubusercontent.com/99376012/155286702-16ff5743-9fdf-442f-8907-70f739dc6004.png)
Can see the labels 
attached the repro sample
[MauiApp13.zip](https://github.com/dotnet/maui/files/8122938/MauiApp13.zip)

**Comment by chrfin** [comment]
@v-xiaofchen Yes, seems to be fixed with P13...
