### ISSUE TITLE
Error : Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools'

### ISSUE THREAD

**Issue by jchomarat** [dotnet/maui#3888]
### Description

I am on a fresh Macos installation and I cannot lunch a dotnet maui app.

* Monterey 12.1

* XCode 13.2.1

* Visual Studio code (NOT Visual Studio for Mac)

```bash
/> xcode-select -p
/Library/Developer/CommandLineTools
```

* dotnet sdk 6.0.101

### Steps to Reproduce

I ran

```bash
/> sudo dotnet workload install maui
/> dotnet new maui -n HelloWorldMaui
/> cd HelloWorldMaui
/> dotnet build -t:Run -f net6.0-maccatalyst
```

I got:

```bash
/> HelloWorldMaui dotnet build -t:Run -f net6.0-maccatalyst
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.0.101-preview.11.551/tools/msbuild/iOS/Xamarin.Shared.targets(1581,3): error : Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools'. Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK). [/Users/ju/HelloWorldMaui/HelloWorldMaui.csproj]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.0.101-preview.11.551/tools/msbuild/iOS/Xamarin.Shared.targets(1581,3): error :          [/Users/ju/HelloWorldMaui/HelloWorldMaui.csproj]

Build FAILED.

/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.0.101-preview.11.551/tools/msbuild/iOS/Xamarin.Shared.targets(1581,3): error : Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools'. Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK). [/Users/ju/HelloWorldMaui/HelloWorldMaui.csproj]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.0.101-preview.11.551/tools/msbuild/iOS/Xamarin.Shared.targets(1581,3): error :          [/Users/ju/HelloWorldMaui/HelloWorldMaui.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.31
```

I pretty sure I dot not need Visual Studio for Mac - but I cannot figure out which setting I need to add/alter.

Thanks

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Monterey 12.1

### Did you find any workaround?

Nope

**Comment by AnthonySlay** [comment]
@jchomarat follow the instructions from anthony@HarrisonOfTheNorth.com at the link below.  This solved my problem concerning the issue you are having.

https://developer.apple.com/forums/thread/660649?login=true

For future reference (in case the link no longer works) open Xcode. Go to Xcode > Preferences > Locations > Command Line Tools and set the blank drop down to something other than blank.  Restart your Visual Studio (or VSCode).

**Comment by jchomarat** [comment]
Woaa thanks a bunch @AnthonySlay, it did the trick - I would have never guessed :)
