### ISSUE TITLE
ProgressBar, add three fields

### ISSUE THREAD

**Issue by pkar70** [dotnet/maui#3890]
### Description

Could you add three fields to ProgressBar, to make migration from UWP do MAUI somewhat easier?
I mean: Minimum, Maximum and Value.

It can be as easy as something like that:
```  
public double Maximum = 1;
public double Minimum = 0;
private double _value = 0;
public double Value
    {
        get => _value;
        set
        {
            value = Math.Min(Math.Max(Minimum, value), Maximum);
            _ProgressBar.Progress = (value - Minimum) / (Maximum - Minimum);
        }
    }
```

### Public API Changes

public double ProgressBar.Maximum = 1;
public double ProgressBar.Minimum = 0;
public double ProgressBar.Value = 0;

### Intended Use-Case

to make migration from UWP do MAUI somewhat easier

**Comment by jfversluis** [comment]
As per the comment here: https://github.com/dotnet/maui/pull/4653#issuecomment-1165662137

I think we don't want to add this. Thank you!
