### ISSUE TITLE
Add full LocalSettings implementation from UWP

### ISSUE THREAD

**Issue by pkar70** [dotnet/maui#3892]
### Description

Similar to #3446, but extended to full implementation of UWP Windows.Storage.ApplicationData.Current.LocalSettings.

### Public API Changes

Same as Windows.Storage.ApplicationData.Current.LocalSettings

### Intended Use-Case

To make porting apps from UWP to MAUI somewhat easier.

**Comment by jfversluis** [comment]
I'm not really sure what this is about to be honest. I think it would be good to first implement the appsettings functionality and then see if we can expand on that is needed. Closing this for now since it's not really actionable at the time being.

**Comment by pkar70** [comment]
UWP settings is something more than .Net appsettings.
UWP settings storage is object, so it can be anything.
UWP settings storage persistent between app runs.
And can be persistent also between install/uninstall/reinstall app, as it is included in system Backup.
