### ISSUE TITLE
Please add FontIcon

### ISSUE THREAD

**Issue by pkar70** [dotnet/maui#3894]
### Description

Please add FontIcon (that can be placed within Button control as source of Icon).

### Public API Changes

Same as UWP

### Intended Use-Case

To make migration from UWP to MAUI easier.

**Comment by chrfin** [comment]
Can't you use `FontImageSource` for this?

**Comment by pkar70** [comment]
Yes, I can :)
It is hard to port app from UWP to MAI, as there is no table "instead of X use Y" :(
Of course, next would be <SymbolIcon> :)

**Comment by Redth** [comment]
As mentioned, FontImageSource will do this already.
