### ISSUE TITLE
Error APT0003	Invalid file name: It must contain only [^a-zA-Z0-9_.]+ for file OpenSans-Regular.ttf

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/maui#3896]
### Description

I have installed the last version of Visual Studio 2022 preview, 17.1.0 Preview 1.1, and I just created a MAUI project with the template of visual studio and then I try to compile it. I get the following error:

Error APT0003	Invalid file name: It must contain only [^a-zA-Z0-9_.]+ for file OpenSans-Regular.ttf

The project is in a folder which path has not blank spaces, neither another not allowed caracters. This is the complete path of the folder:

C:\proyectos\GestorOrdenadores\GestorOrdenadores.Cliente.XamarinMaui\Resources\Fonts

Thanks.

### Steps to Reproduce

1.- Create a MAUI project witth Visual  Studio 2022 template
2.- Compile MAUI project

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Andriod

### Relevant log output

```shell
Operación Recompilar iniciada...
Se ha restaurado C:\proyectos\GestorOrdenadores\GestorOrdenadores.Service.Grpc.DotNet\GestorOrdenadores.Service.Grpc.DotNet.csproj (en 4,09 sec).
Se ha restaurado C:\proyectos\GestorOrdenadores\GestorOrdenadores.Cliente.Wpf\GestorOrdenadores.Cliente.Wpf.csproj (en 4,1 sec).
Se ha restaurado C:\proyectos\GestorOrdenadores\GestorOrdenadores.Cliente\GestorOrdenadores.Cliente.csproj (en 4,09 sec).
Se ha restaurado C:\proyectos\GestorOrdenadores\GestorOrdenadores.Service.Comun\GestorOrdenadores.Service.Comun.csproj (en 4,12 sec).
1>------ Operación Recompilar todo iniciada: proyecto: GestorOrdenadores.Cliente.XamarinMaui, configuración: Debug Any CPU ------
Se ha restaurado C:\proyectos\GestorOrdenadores\GestorOrdenadores.Cliente.XamarinMaui\GestorOrdenadores.Cliente.XamarinMaui.csproj (en 4,77 sec).
1>Resources\Fonts\OpenSans-Regular.ttf : error APT0003: Invalid file name: It must contain only [^a-zA-Z0-9_.]+.
1>Compilación del proyecto "GestorOrdenadores.Cliente.XamarinMaui.csproj" terminada -- ERROR.
========== Recompilar todo: 0 correctos, 1 incorrectos, 0 omitidos ==========
```

**Comment by jfversluis** [comment]
Hey @ComptonAlvaro thanks for the report!

The error is not about the path where your app is but the _filename_ and if you look at that: `OpenSans-Regular.ttf` it has a hyphen (`-`) in there which is not allowed. Android in particular isn't great at handling "special" characters in filenames, that's why this safe guard is in place.

Rename that file to, for instance: `OpenSansRegular.ttf` and it should be fine.

If that doesn't resolve it, please let me know!

**Comment by yunusefendi52** [comment]
Isn't the template include `OpenSans-Regular.dll` (with hypens) by default?

**Comment by jfversluis** [comment]
Ha you are totally right! OK, looking into this a bit deeper it seems this restriction has been here for a while but most specifically for drawables. So maybe the font was in a wrong folder or had the wrong build action or something?

**Comment by MagicAndre1981** [comment]
I get the same with VS2022 17.1 Preview 3 when I create a new MAUI app. So this is a template issue @jfversluis

**Comment by nextfool** [comment]
@MagicAndre1981 I have exactly the same issue with vs 2022 17.1 preview3. If I remove the '-' from the file name (also removed from the code)
```
 builder
                .RegisterBlazorMauiWebView()
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSansRegular.ttf", "OpenSansRegular");
                });
```
I have a whole bunch of new errors like:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2144	invalid file path 'D:\projects\playground\IHostLearning\MauiApp2Blazor\obj\Debug\net6.0-android\res\resources\images\dotnet_bot.svg'.	MauiApp2Blazor	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.12.2\tools\Xamarin.Android.Aapt2.targets	123	
Error	APT2144	invalid file path 'D:\projects\playground\IHostLearning\MauiApp2Blazor\obj\Debug\net6.0-android\res\resources\appiconfg.svg'.	MauiApp2Blazor	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.12.2\tools\Xamarin.Android.Aapt2.targets	123	
Error	APT2144	invalid file path 'D:\projects\playground\IHostLearning\MauiApp2Blazor\obj\Debug\net6.0-android\res\resources\fonts\opensansregular.ttf'.	MauiApp2Blazor	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.12.2\tools\Xamarin.Android.Aapt2.targets	123	
Error	APT2144	invalid file path 'D:\projects\playground\IHostLearning\MauiApp2Blazor\obj\Debug\net6.0-android\res\resources\appicon.svg'.	MauiApp2Blazor	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.12.2\tools\Xamarin.Android.Aapt2.targets	123	
```
So something is definitely wrong here, please have a look @jfversluis . Thank you.

**Comment by nextfool** [comment]
> @MagicAndre1981 I have exactly the same issue with vs 2022 17.1 preview3. If I remove the '-' from the file name (also removed from the code)
> 
> ```
>  builder
>                 .RegisterBlazorMauiWebView()
>                 .UseMauiApp<App>()
>                 .ConfigureFonts(fonts =>
>                 {
>                     fonts.AddFont("OpenSansRegular.ttf", "OpenSansRegular");
>                 });
> ```
> 
> I have a whole bunch of new errors like:
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	APT2144	invalid file path 'D:\projects\playground\IHostLearning\MauiApp2Blazor\obj\Debug\net6.0-android\res\resources\images\dotnet_bot.svg'.	MauiApp2Blazor	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.12.2\tools\Xamarin.Android.Aapt2.targets	123	
> Error	APT2144	invalid file path 'D:\projects\playground\IHostLearning\MauiApp2Blazor\obj\Debug\net6.0-android\res\resources\appiconfg.svg'.	MauiApp2Blazor	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.12.2\tools\Xamarin.Android.Aapt2.targets	123	
> Error	APT2144	invalid file path 'D:\projects\playground\IHostLearning\MauiApp2Blazor\obj\Debug\net6.0-android\res\resources\fonts\opensansregular.ttf'.	MauiApp2Blazor	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.12.2\tools\Xamarin.Android.Aapt2.targets	123	
> Error	APT2144	invalid file path 'D:\projects\playground\IHostLearning\MauiApp2Blazor\obj\Debug\net6.0-android\res\resources\appicon.svg'.	MauiApp2Blazor	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.12.2\tools\Xamarin.Android.Aapt2.targets	123	
> ```
> 
> So something is definitely wrong here, please have a look @jfversluis . Thank you.

So the errors are fixed by steps in https://github.com/dotnet/maui/issues/3900

**Comment by MagicAndre1981** [comment]
@nextfool yes, this fixed it, but if this needs to be done, the templates are broken and needs to be fixed.

**Comment by TwoSeven99** [comment]
I also just got this issue with preview 12 and creating a new project.  Was able to fix it by renaming the appropriate file and making the above suggested project file changes.

**Comment by MagicAndre1981** [comment]
strange, for me it worked in 17.1. preview 6.0 with MAUI P12 with a new project and without renaming it 🤔
