### ISSUE TITLE
App crashes with `No service for type 'Microsoft.Maui.Controls.Hosting.EffectsFactory' has been registered.`

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/maui#3898]
### Description

I'm porting an app to MAUI, and finally got it to build today. But now it crashes at runtime:

![image](https://user-images.githubusercontent.com/6609929/147882533-1c9f17f7-c810-423c-ae4c-9fb19c2931df.png)

Could you please hint at what could be causing the issue?

### Steps to Reproduce

1. Install MAUI workload with preview 10 version
2. Run this app https://github.com/maxkoshevoi/NureTimetable/tree/a18fc1670d753417565a7700eb0151c59ba59d6d

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by pictos** [comment]
Did you register your effects on builder inside `MauiProgram‘ class?

**Comment by maxkoshevoi** [comment]
@pictos none that I'm aware of: https://github.com/maxkoshevoi/NureTimetable/blob/a18fc1670d753417565a7700eb0151c59ba59d6d/NureTimetable/MauiProgram.cs#L15

I tried removing that line, but app still crashes

**Comment by pictos** [comment]
@maxkoshevoi I'm inferring that your app has `Effects` and the app crashes when you try to use one.
If that is true, if you register your effects using the `builder` does your app work?

```csharp
builder.ConfigureEffects(x =>
{
	x.Add()
});
```

**Comment by maxkoshevoi** [comment]
@pictos I do use `StatusBarEffect` from CommunityToolkit.MauiCompat, didn't know I need to register it, thank you!

```cs
.ConfigureEffects(effects =>
{
    effects.Add<StatusBarEffect, PlatformStatusBarEffect>();
});
```

Error message is super unclear though. It should say something like `"StatusBarEffect" haven't been registered` or something.
