### ISSUE TITLE
Android in-app purchases: port Xamarin.Android.Google.BillingClient to Maui

### ISSUE THREAD

**Issue by chrisgull** [dotnet/maui#3899]
### Description

I use the Xamarin.Android.Google.BillingClient package for in-app purchases in my Android app.
It would be really great to see that package ported to Maui.

### Public API Changes

Addition of the API publised in Xamarin.Android.Google.BillingClient.

### Intended Use-Case

In-app purchases in an Android app.

**Comment by Eilon** [comment]
I'm not certain, but I would think that it's still usable in MAUI as well. .NET MAUI is a successor to Xamarin.Forms, but they still both build on Xamarin Android, Xamarin iOS, etc.

**Comment by jfversluis** [comment]
Looking at the dependencies I only see AndroidX and if I dig deeper it seems they have been updated to use .NET 6. I would think that this library is supported for .NET MAUI. If not, please open an issue on their repo. Thanks!
