### ISSUE TITLE
button text does not display content！

### ISSUE THREAD

**Issue by JusterZhu** [dotnet/maui#3902]
### Description

System : WIN10 Professional 19042.1415
Visual studio Version :  17.1.0 Preview 1.1
SDK:  net6.0-windows10.0.19041
![1641217927(1)](https://user-images.githubusercontent.com/11714536/147939338-5fc0ad14-b3fc-4ab9-a3bc-73dce6c45c4d.jpg)

### Steps to Reproduce

1.run the 'windows machine'
2.Run the following code ↓

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2022.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">

    <ScrollView>
        <Grid RowSpacing="1" ColumnDefinitions="2.5*,2.5*,2.5*,2.5*" ColumnSpacing="5" Margin="{OnPlatform Android='10,10,10,10' ,Default='1,1,1,1'}">
            
            <StackLayout Orientation="Horizontal">
                <Label FontSize="16" Text="StackLayout" WidthRequest="100" HeightRequest="25"></Label>
            </StackLayout>
            <FlexLayout GridLayout.Column="1" Direction="Column"
                AlignItems="Center" JustifyContent="SpaceEvenly">
                <Button WidthRequest="100" HeightRequest="100"></Button>
                <Label FontSize="16" Text="FlexLayout" WidthRequest="100" HeightRequest="25"></Label>
            </FlexLayout>
            <AbsoluteLayout GridLayout.Column="2">
                <Label Text="AbsoluteLayout1" AbsoluteLayout.LayoutFlags="PositionProportional" AbsoluteLayout.LayoutBounds="0,0,0,0" HeightRequest="25" WidthRequest="200"></Label>
                <Label Text="AbsoluteLayout2" AbsoluteLayout.LayoutFlags="PositionProportional" AbsoluteLayout.LayoutBounds="0,10,0,0" HeightRequest="25" WidthRequest="200"></Label>
            </AbsoluteLayout>
            <StackLayout GridLayout.Column="3" Orientation="Vertical">
                <Button x:Name="BtnMessageShow" WidthRequest="100" HeightRequest="25" Text="Messagebox"></Button>
                <Button WidthRequest="100" HeightRequest="25" Text="Change data." SemanticProperties.Hint="clik me." Command="{Binding RefreshDataCommand}"></Button>
                <ListView WidthRequest="300" IsRefreshing="True" IsPullToRefreshEnabled="True" RefreshCommand="{Binding RefreshDataCommand}" HeightRequest="600" ItemsSource="{Binding DemoModels}">
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell>
                                <Grid Padding="10">
                                    <StackLayout Spacing="4" VerticalOptions="Center">
                                        <Label Text="{Binding Name}" FontSize="Small" LineBreakMode="WordWrap" />
                                        <Label Text="{Binding Description}" TextColor="#3498DB" FontSize="Small" LineBreakMode="NoWrap" />
                                    </StackLayout>
                                </Grid>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>
            </StackLayout>
        </Grid>
    </ScrollView>
</ContentPage>

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 10 (current)

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041

### Did you find any workaround?

None

### Relevant log output

```shell
None
```

**Comment by hartez** [comment]
@JusterZhu  If you remove the HeightRequests from those Buttons, does the text display? Or does it remain blank?

**Comment by JusterZhu** [comment]
> 

![image](https://user-images.githubusercontent.com/11714536/148074574-cc339521-9fe2-400d-8217-b94f4d9a3cfd.png)

Did not make any changes.

**Comment by JusterZhu** [comment]
![image](https://user-images.githubusercontent.com/11714536/148094774-cc216525-fdd3-4e30-a0e4-c69e69e46887.png)

Did not make any changes.
