### ISSUE TITLE
Application crash while requesting the events from Microsoft outlook

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#3903]
### Description

We have created an application to access the outlook event and show it on list view. We are authenticating the account by using the client id and we faced the **System.TypeLoadException** but it is working fine in windows. 

We configure the sample by the steps below:

- Register the new project on https://portal.azure.com/
- Enable calendar read write permission for the project
- Create the IPublicClientApplication on App.cs by client id.
- Configure the Android project and authenticate the user by AcquireTokenInteractive and GraphServiceClient

The exception was raised while get events after the authentication.

`Client.Me.Events.Request().GetAsync();`

**Note:** The issue did not raised on Windows

### Steps to Reproduce

1. Prepare the sample with below code
2. Run the sample
3. Exception raised on `Client.Me.Events.Request().GetAsync();`

In App.cs

```
public static IPublicClientApplication IdentityClientApp;
		//You need to replace your Application ID 
		public static string ClientID = "CliendID";
		public static string[] Scopes = { "User.Read", "Calendars.Read", "Calendars.ReadWrite" };

		public static object ParentWindow { get; set; }

		public App()
		{
			InitializeComponent();
			IdentityClientApp = PublicClientApplicationBuilder.Create(ClientID)
			.WithRedirectUri($"msal{ClientID}://auth")
			.Build();
			MainPage = new MainPage();
		}
```

In MainActivity

```
protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            App.ParentWindow = this;
        }
```

In MainPage,

```
private Microsoft.Graph.GraphServiceClient Client = null;
		private AuthenticationResult tokenRequest;
		public MainPage()
		{
			InitializeComponent();
		}

		private void Authenticate()
		{
			Client = new Microsoft.Graph.GraphServiceClient("https://graph.microsoft.com/v1.0",
				new Microsoft.Graph.DelegateAuthenticationProvider(async (requestMessage) =>
				{
					List<IAccount> users = (List<IAccount>)await App.IdentityClientApp.GetAccountsAsync();

					if (users == null || users.Count == 0)
						tokenRequest = await App.IdentityClientApp.AcquireTokenInteractive(App.Scopes)
							.WithParentActivityOrWindow(App.ParentWindow)
							.WithUseEmbeddedWebView(true).ExecuteAsync();
					else
						tokenRequest = await App.IdentityClientApp.AcquireTokenSilent(App.Scopes, users.FirstOrDefault()).ExecuteAsync();

					requestMessage.Headers.Authorization = new AuthenticationHeaderValue("bearer", tokenRequest.AccessToken);
				}));
		}

		private async void OnClicked(object sender, EventArgs e)
		{
			this.Authenticate();
			var events = Client.Me.Events.Request().GetAsync();
			var list = events.ToList();
		}
```

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android API 31

### Did you find any workaround?

No

### Relevant log output

```shell
System.TypeLoadException
  Message=Could not resolve type with token 01000023 from typeref (expected class 'System.Threading.Tasks.ValueTask`1' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e')
```

**Comment by Eilon** [comment]
@Sasikumar3595 can you share more info about this method call that looks like it's async, but isn't awaited?

```
			var events = Client.Me.Events.Request().GetAsync();
			var list = events.ToList();
```

Is `GetAsync()` an async method? If so, it must be called using the `await` keyword.

**Comment by Sasikumar3595** [comment]
@Eilon,

I have tried that code also.

The exception was raised when I comment the `var list = events.ToList();` code and the exception raised from `var events = Client.Me.Events.Request().GetAsync();`

**Comment by ahoefling** [comment]
Hey friends! Jumping into this thread as I have the exact same problem and a **workaround** 🎉

I am using Microsoft.Graph v4.20.0 with an android application running .NET 6 via Uno Platform. I am wondering if this problem should be documented in the core xamarin-android repository instead of .NET MAUI. Since I am running into an identical issue on Uno Platform I am suspect that this also impacts native android running .NET 6.

**Workaround**
The Microsoft Graph API suggests using the API `GetAsync()` which handles the response object and returns a model that is easy to use in your downstream code. I was able to resolve this issue by using the API `GetResponseAsync()` which returns the response object that allows us to read the raw json data and then I was about to deserialize that into the Microsoft.Graph object. See my code snippet below

```c#
var response = await graphClient.Me
  .Request()
  .Select(user => new
  {
    Id = user.Id,
    DisplayName = user.DisplayName,
    UserPrincipalName = user.UserPrincipalName
  })
  .GetResponseAsync();

var data = await response.Content.ReadAsStringAsync();
var me = JsonConvert.DeserializeObject<User>(data);
```

Original Code Snippet
```c#
var graphClient = new GraphServiceClient(httpClient);
graphClient.AuthenticationProvider = this;

var me = await graphClient.Me
  .Request()
  .Select(user => new
  {
    Id = user.Id,
    DisplayName = user.DisplayName,
    UserPrincipalName = user.UserPrincipalName
  })
  .GetAsync();
```

Original Error Message
```
System.TypeLoadException: Could not resolve type with token 01000023 from typeref (expected class 'System.Threading.Tasks.ValueTask`1' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e')
   at Microsoft.Graph.ResponseHandler.<HandleResponse>d__2`1[[Microsoft.Graph.DriveItem, Microsoft.Graph, Version=4.20.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1[[Microsoft.Graph.DriveItem, Microsoft.Graph, Version=4.20.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at Microsoft.Graph.DriveItemRequest.GetAsync(CancellationToken cancellationToken)
  at __my code__
```

**Comment by pekspro** [comment]
I also have this issue, running in preview 14.

I could confirm that the workaround @ahoefling has done is working.
