### ISSUE TITLE
Not found Microsoft.Maui.Essentials

### ISSUE THREAD

**Issue by LeonSweden** [dotnet/maui#3909]
### Description

Created MAUI app by template.
In MainPage.xaml.cs both  packages:
- Microsoft.Maui.Controls
- Microsoft.Maui.Essentials
are missing

Can't find them in nuget PM (e or w/o prerelase flag).

Having VS Studio Version:

Microsoft Visual Studio Community 2022
Version 17.1.0 Preview 1.1
VisualStudio.17.Preview/17.1.0-pre.1.1+31911.260
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

ASP.NET and Web Tools 2019   17.1.126.26097
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.1.126.26097
Azure App Service Tools v3.0.0

C# Tools   4.1.0-1.21551.6+e4419d6f6792da7011c8589ba118f59d830ca72f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   17.1.4 (dc2a48c)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2152601+724154d925d7d9d26ebf8a73a66d5219aa320400
Provides languages services for ASP.NET Core Razor.

TypeScript Tools   17.0.1029.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-1.21551.6+e4419d6f6792da7011c8589ba118f59d830ca72f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21525.2+46af4a248255f4af2284883f48983fe7dd07a760
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.1.0.163 (d17-1-p1@42933de)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.1.0.43 (remotes/origin/main@931878527)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.1.8 (590388a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.99.56 (main/43243b4)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@79744f61
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@a5194e9

Xamarin.iOS and Xamarin.Mac SDK   15.3.0.41 (7b786db64)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Steps to Reproduce

1. Create new project
2. open MainWindow.xaml.cs

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

### Did you find any workaround?

no

**Comment by PureWeen** [comment]
@LeonSweden  can you attach a screen shot? I'm not sure I follow your issue here

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
