### ISSUE TITLE
Unable to run Maui app in release mode

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3910]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-run-Maui-app-in-release-mode/1614563)._

---
[severity:I'm unable to use this version]
My Maui app works in debug mode but crashes in release mode.   

BTW - Saw comment in a similar post to set 
 
<AndroidLinkMode>None</AndroidLinkMode>
<AndroidDexTool>r8</AndroidDexTool>

but these settings causes errors in my build.

---
#### Feedback Bot on 12/15/2021, 10:15 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mattscheffer** [comment]
No repro 32208.182.main. Tested with Pixel 5 (Android 11) simulator. Creating a new MAUI app and building/deploying both debug and release works correctly.
