### ISSUE TITLE
Error creating windows app with MAUI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3911]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-creating-windows-app-with-MAUI/1610623)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:2022 Preview]
I just created a new MAUI app and successfully deployed to Android and IOS.  However, when I select Windows as the target and build, I get the following error:

CS2012	Cannot open 'E:\VS2022\OurData\OurData\obj\Debug\net6.0-windows10.0.19041\win-x64\intermediatexaml\OurData.dll' for writing -- 'Access to the path 'E:\VS2022\OurData\OurData\obj\Debug\net6.0-windows10.0.19041\win-x64\intermediatexaml\OurData.dll' is denied.'

---
#### Feedback Bot on 12/13/2021, 00:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by farlop** [comment]
Bitdefender Endpoint detected as malware:

> El Análisis on-access ha detectado una amenaza. Se ha eliminado el archivo.C:\Users\avalor\source\repos\MauiApp4\MauiApp4\obj\Debug\net6.0-windows10.0.19041\win10-x64\intermediatexaml\MauiApp4.dll es malware de tipo **Gen:Variant.Tedy.62158**

**Comment by jfversluis** [comment]
Older issue and seems indeed like you might need to disable some anti-virus or exclude some paths if that happens. Let us know if you think there is still an issue here.
