### ISSUE TITLE
Creating first maui app floods the error list, only to remove most of them later

### ISSUE THREAD

**Issue by AArnott** [dotnet/maui#3922]
### Description

The roslyn language service should not be initialized with 'last design time build successful' before nuget restore has completed for the project. Otherwise roslyn will flood the error list with hundreds of errors due to missing ref assemblies. This presents a new maui developer with the impression that VS created a badly broken project.

### Steps to Reproduce

**With a local nuget cache that isn't yet populated with Maui packages**, create a new Maui app project.
Notice how the error list floods with hundreds of errors. Most or all of these may disappear after nuget restore has completed.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

VS 17.1.0 Preview 3 (32102.18.main)

### Did you find any workaround?

Just wait for nuget restore to complete.

**Comment by PureWeen** [comment]
@AArnott now that your local setup is working do you still see this?

I tested this by running `dotnet nuget locals all --clear` before creating a new maui app inside VS and I don't see my error list flood with any reference errors.

The only errors that show for me are related to this issue https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1459138

**Comment by AArnott** [comment]
Yes, this still happens on a clean machine. Do you want me to provide an animated gif so you can see it happen?

**Comment by wenwen60** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
