### ISSUE TITLE
The SDK demands installation of android workloads even when project doesn't target android

### ISSUE THREAD

**Issue by AArnott** [dotnet/maui#3924]
### Description

I was forced to install the `android` and `maui-android` workloads to build a project that only targeted `net6.0-maccatalyst;net6.0-windows10.0.19041`.

This makes no sense to me. Why should I have to install Android SDK assets when I'm not targeting Android?

I wonder if the same problem would happen after removing `maccatalyst` as a target. Would the SDK require that I install that workload even when I'm not targeting that?

### Steps to Reproduce

A clean install of VS with no dotnet workloads installed yet. Install the "Mobile development for .NET" workload with the Maui optional component selected.
Create a new maui app project.
Remove the android elements from the project file.
Try to build. It fails because the android workload isn't installed.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

VS 17.1.0 Preview 3 (32102.18.main)

### Did you find any workaround?

Install the android and maui-android workloads even though the project shouldn't require it.

**Comment by AArnott** [comment]
Possibly related: #1392

**Comment by shimingsg** [comment]
Not reproducible with Android 11.
