### ISSUE TITLE
No Valid iOS code signing keys found in keychain. Please enable Automatic Provisioning from the iOS Bundle Signing page

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#3927]
### Description

I am getting the following error

"No Valid iOS code signing keys found in keychain. Please enable Automatic Provisioning from the iOS Bundle Signing page".

I am not sure on how to get around this error, any links on setting this up properly wil help

Also Even Android emulator is not working 

### Steps to Reproduce

Attached the video of error
["No Valid iOS code signing keys found in keychain. Please enable Automatic Provisioning from the iOS Bundle Signing page"](https://1drv.ms/v/s!AtHk7h6Srnk_h99dbKTDMjsCpu3V7A?e=I5bYBh.)

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

### Relevant log output

```shell
"No Valid iOS code signing keys found in keychain. Please enable Automatic Provisioning from the iOS Bundle Signing page"
```

**Comment by nssidhu** [comment]
Also wondering if there is way to run the Development on Local Android Device as well similar to iPhone Local Device?

**Comment by nssidhu** [comment]
I have tried following this link,
https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=windows#enable-automatic-provisioning

but in the latest template I could not find "Automatic Provisioning" section.

**Comment by Redth** [comment]
@dalexsoto @rolfbjarne should the iOS default for provisioning be considered to be automatic, instead of requiring it explicitly set in the .csproj for these cases?

**Comment by chrfin** [comment]
Had the same problem - the UI does not exist yet for MAUI. I found two "solutions": 

1) Use the "Hot Restart"-wizard (just start it once, it will add the needed entries to the project)   
2) Add the entries manually:   
`<CodesignKey>Apple Development: YOUR NAME</CodesignKey>`   
`<CodesignProvision>VS: com.COMPANY.APPID Development</CodesignProvision>`   
(See also my comment here: [https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-preview-11//#comment-14544](https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-preview-11//#comment-14544))

**Comment by rolfbjarne** [comment]
@Redth I believe that we don't require anything set in the csproj if we detect that signing is required, we'll look at the certificates/provisioning profiles the user has and try to find something that can be used (which may fail). OTOH this looks like it's a hot restart scenario, which means that the entire signing logic is done on Windows, so this might be an issue for XVS  (CC @emaf / @mauroa)

**Comment by emaf** [comment]
@Redth Automatic Provisioning will be enable by default on Visual Studio 2022 17.1 Preview 3. That said, you'll still need to set it up (add an account and select a team), and the only way to do so right now is through the Hot Restart wizard.

@nssidhu After creating the project, please try adding `<ProvisioningType>automatic</ProvisioningType>` inside a PropertyGroup in your csproj file. That should enable the Hot Restart wizard to also show the steps to setup Automatic Provisioning.

**Comment by kristinx0211** [comment]
repro on vs 17.2.0 Preview 2.0 [32301.586.main].

**Comment by Redth** [comment]
Fixed in upcoming service release.
