### ISSUE TITLE
Move Maps to handler architecture

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#3933]
API changes:

- Remove `Microsoft.Maui.Controls.Maps.Position` and use `Microsoft.Maui.Devices.Sensors.Location`
- Remove `Microsoft.Maui.Controls.Maps.Geocoder` and use `Microsoft.Maui.Devices.Sensors.Geocoding`
- Change `Microsoft.Maui.Controls.Maps.Position`  on `Pin` to `Microsoft.Maui.Devices.Sensors.Location`
- Change `Microsoft.Maui.Controls.Maps.Position`  on `MapClickedEventArgs` to `Microsoft.Maui.Devices.Sensors.Location`
- Change `Microsoft.Maui.Controls.Maps.Position`  Center on `MapSpan` to `Microsoft.Maui.Devices.Sensors.Location`
- Change `Microsoft.Maui.Controls.Maps.Position`  Geopath on `Polyline` to `Microsoft.Maui.Devices.Sensors.Location`
- Change `Microsoft.Maui.Controls.Maps.Position`  Geopath on `Polygon` to `Microsoft.Maui.Devices.Sensors.Location`
- Remove or make internal `Microsoft.Maui.Controls.Maps.GeographyUtils`

**Comment by jsuarezruiz** [comment]
Should it remain a separate library or be part of Core?

**Comment by Redth** [comment]
Separate library.

**Comment by DavidBerschauer** [comment]
How high are the chances to see this coming in 2022?

**Comment by bricelam** [comment]
Note that a Windows handler implementation will probably want to wait for https://github.com/microsoft/microsoft-ui-xaml/issues/3024

**Comment by hartez** [comment]
I think @rachelkang has some plans for this.

**Comment by TFreudi1** [comment]
I'm also very intrested in the MAP Control or a way to use the native Control  like Xamarin do.

**Comment by davidortinau** [comment]
@TFreudi1 see https://www.cayas.de/blog/dotnet-maui-custom-map-handler

**Comment by TFreudi1** [comment]
@davidortinau 
@hartez 
I got the sample from the cayas page to work now. It is missing _mapView.OnResume(); in the Android platform code. See
[https://stackoverflow.com/questions/70976168/how-to-display-google-maps-on-net-maui/72379499?noredirect=1#comment128848674_72379499](url)

**Comment by ryanaw83** [comment]
When is this planned to be released?

**Comment by rmarinho** [comment]
@ryanaw83  on .net7

**Comment by Rabosa616** [comment]
@rmarinho will be available for Android, iOS, Mac & Windows or only for mobile devices?

**Comment by danbridgellc** [comment]
All these Handler solutions do not address Windows - it just works for Android/iOS/Mac.  Does anyone have a solution that includes Windows?

**Comment by bricelam** [comment]
For Windows support, please upvote https://github.com/microsoft/microsoft-ui-xaml/issues/3024 so they can prioritize appropriately.

**Comment by BillyMartin1964** [comment]
Current build displays and shows Location correctly, but has two major bugs:

When adding Map Pins, I get

System.MissingMethodException: 'Method not found: bool Microsoft.Maui.Devices.Sensors.Location.op_Inequality(Microsoft.Maui.Devices.Sensors.Location,Microsoft.Maui.Devices.Sensors.Location)'

When tracking user with polyline, I get this

![image](https://user-images.githubusercontent.com/29313458/190866989-32b4db53-4623-42df-b9f1-86305f47cdf6.png)
