### ISSUE TITLE
IBorder was implemented incorrectly

### ISSUE THREAD

**Issue by Clancey** [dotnet/maui#3951]
### Description

IBorder is implemented as IBorder: IContentView.

This is very inconsistent with the rest of the styling apis. Shadow, and ClipShape both exists as properties on IView, not as a container view.

Each platform has a [ContainerView](https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/View/ViewHandler.cs#L49), that is automatic. This allows us to do Border the same way as ClipShape and Shadow.

### Steps to Reproduce

IBorder is implemented as IBorder: IContentView.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All Platforms

**Comment by danielftz** [comment]
Would the current implementation also be the cause of a bug where anything wrapped with Border not respecting Margin/Padding sometimes?

**Comment by Clancey** [comment]
Nope, they shouldn't matter

**Comment by AmrAlSayed0** [comment]
@Clancey @hartez explained here https://github.com/dotnet/maui/pull/2445 why IBorder is implemented as a control and not a property. Basically, it's a temporary solution.

**Comment by Clancey** [comment]
This was fixed with https://github.com/dotnet/maui/pull/4035

**Comment by danielftz** [comment]
> This was fixed with #4035
So if I code a control entirely in c#, does that mean I can just implement IBorder and have the border show up?

**Comment by Clancey** [comment]
> > This was fixed with #4035
> > So if I code a control entirely in c#, does that mean I can just implement IBorder and have the border show up?

Correct, starting with preview 13
