### ISSUE TITLE
Can we integrate a DataTemplate with Drawable view?

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#3956]
### Description

We have a custom draw view that will be drawn as default, we require to integrate it with DataTemplate. So if DataTemplate is available we need to show that template instead of drawing canvas.

We can achieve this in Flutter using the builder concept, but in MAUI it seems we can't achieve both drawableview and template using a single view.

### (Public) API Changes

NA

### Usage Scenarios

NA

### Backward Compatibility

No

### Difficulty

Low

**Comment by v-longmin** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by hartez** [comment]
@karthikraja-arumugam sorry for the confusion, we now realize this was a feature proposal and not a bug report. You can ignore the comments from the msftbot account - this won't be closed.

**Comment by mattleibow** [comment]
Looking at this now and not sure exactly what you mean. Could you add some pseudo code of what you are thinking? How would you use this new feature?
