### ISSUE TITLE
Navigation.PopModalAsync not working on iOS

### ISSUE THREAD

**Issue by PedroCigaw** [dotnet/maui#3959]
### Description

Calling Navigation.PopModalAsync throws NullReferenceException.  

I created a [sample project](https://github.com/PedroCigaw/MauiModalTest.git).  The sample has a start page, click the Open Modal button which will push a modal test page that has a button that will pop test page.  

Its working on android and windows, not tested MacCatalyst.

I am running windows 10 using local device Iphone 12 os version 15..1.1

### Steps to Reproduce

1. New Maui Project.
2. Create a ContentPage with a button that calls Navigation.PopModalAysnc on the button click.
3. Modify the MainPage to include a button that calls Navigation.PushModalAsync on the content pages created on step two.
4. Run the solution on iPhone local device.

Alternatively clone the sample repository  [https://github.com/PedroCigaw/MauiModalTest.git](https://github.com/PedroCigaw/MauiModalTest.git) and run the sample on iOS.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by vniehues** [comment]
I'm currently running into the same issue on pre12.

**Comment by vniehues** [comment]
The issue still exists in pre13.

**Comment by J-Swift** [comment]
Same on p13. This is a big issue, can't use modal views on iOS otherwise. I haven't found a workaround yet.

**Comment by kristinx0211** [comment]
verified repro on iPhone 13 IOS 15.2 and above project.

**Comment by Redth** [comment]
This should be fixed in Preview 14.  Please open a new bug if there are still issues with it there.
