### ISSUE TITLE
CurrentCulture on iOS not available at startup

### ISSUE THREAD

**Issue by PedroCigaw** [dotnet/maui#3962]
### Description

On iOS at startup all culture info is null.
`
     var c = Thread.CurrentThread.CurrentUICulture;

     var c1 = Thread.CurrentThread.CurrentCulture;

     var c3 = CultureInfo.CurrentUICulture;

     var c4 = CultureInfo.DefaultThreadCurrentUICulture;

     var c5 = CultureInfo.DefaultThreadCurrentCulture;

     var c6 = CultureInfo.InstalledUICulture;

     var c7 = CultureInfo.InvariantCulture;

     var c8 = CultureInfo.CreateSpecificCulture("en-GB");
`
All of the above are null when called in MauiProgram

On android and windows targets getting the culture works as expected.

On iOS the culture info is only accessible after the first Page is displayed.

### Steps to Reproduce

1. Create new maui project.
2. Add the code in description to the MauiProgram
3. Run on iOS device.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by nmarazov** [comment]
We're unable to set the current culture on iOS, except "en". The following code works on Android but not on iOS:
`CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.DefaultThreadCurrentCulture = CultureInfo.CurrentUICulture = CultureInfo.CurrentCulture = new CultureInfo("bg");`
We even tried setting it on the main thread
`MainThread.BeginInvokeOnMainThread(() => CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.DefaultThreadCurrentCulture = CultureInfo.CurrentUICulture = CultureInfo.CurrentCulture = new CultureInfo("bg"));`
All results in the default resources being used. Funny thing is setting culture to "en" does work - uses the en.resx on iOS
Currently using .net maui preview 12
Has anyone been successful in changing the culture on Maui?

**Comment by AmrAlSayed0** [comment]
A don't think this is a MAUI issue, I am facing this issue on normal XF application on iOS. I think this is a Xamarin.iOS issue.

**Comment by nmarazov** [comment]
> A don't think this is a MAUI issue, I am facing this issue on normal XF application on iOS. I think this is a Xamarin.iOS issue.

The exact same line is used in a production app with XF 5,0 and there is no problem. I am able to change cultures without a problem both iOS and Android

**Comment by mattscheffer** [comment]
Bug repro with 17.2 Preview 1 on Iphone 13 iOS 15.2. Repro project link at https://microsoft.sharepoint.com/:u:/r/teams/Mauitriage/Shared%20Documents/General/ReproProjects/3962.zip?csf=1&web=1&e=pGSRlv

**Comment by dais-set** [comment]
So are there any updates on when this might be fixed?

**Comment by Redth** [comment]
@steveisok is this something your team can look at?

**Comment by steveisok** [comment]
I cannot reproduce the issue as described.  The only values that are null are `CultureInfo.DefaultThreadCurrentCulture` and `CultureInfo.DefaultThreadCurrentUICulture`, which is expected.

As for the comment about switching cultures and not displaying the right resx, @Redth, has your team tested that out?

**Comment by steveisok** [comment]
> Bug repro with 17.2 Preview 1 on Iphone 13 iOS 15.2. Repro project link at [3962.zip](https://github.com/dotnet/maui/files/8145224/3962.zip)

When I inspected the contents of the project, MainPage.xaml.cs contains the culture variables in the issue description, but it does not validate anything.

**Comment by dais-set** [comment]
@jsuarezruiz so what additional info is required? On iOS resources always use the default culture resx and there's no way to set any other culture or display resources from any other culture.
