### ISSUE TITLE
Build fails with `Xamarin.Android.D8.targets(79,5): MSB6006 "java.exe" exited with code 1`

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/maui#3965]
### Description

After update to preview11 app fails to build with: https://github.com/maxkoshevoi/NureTimetable/runs/4721371318?check_suite_focus=true#step:6:25
```cs
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.11.117\tools\Xamarin.Android.D8.targets(79,5): error MSB6006: "java.exe" exited with code 1.
```

It has been building fine in preview 10. 

### Steps to Reproduce

1. Build this app https://github.com/maxkoshevoi/NureTimetable/tree/0f02e8f8ac5a927e97fb5e0ceee2a0dde78764d2 using preview 11

### Version with bug

Preview 11

### Last version that worked well

Preview 10 (current)

### Affected platforms

Android

### Affected platform versions

All

### Did you find any workaround?

Works, but not always:
```xml
<Target Name="Remove1B1B3F705C33DF84" AfterTargets="_CheckDuplicateJavaLibraries">
  <ItemGroup>
    <ExtractedJarImportsToRemove Include="@(ExtractedJarImports)" Condition="'%(Filename)' == '1B1B3F705C33DF84'" />
    <ExtractedJarImports Remove="@(ExtractedJarImportsToRemove)" />
  </ItemGroup>
</Target>
```

### Relevant log output

```
Type com.google.common.util.concurrent.ListenableFuture is defined multiple times
```

```shell
Error in C:\Users\Mi\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.4\buildTransitive
et6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class:
Type com.google.common.util.concurrent.ListenableFuture is defined multiple times: C:\Users\Mi\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.4\buildTransitive
et6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class, obj\Debug
et6.0-android31\lp\133\jl\libs\009E21B983A37ED6.jar:com/google/common/util/concurrent/ListenableFuture.class
Compilation failed
MSB6006: "java.exe" exited with code 1.
Done executing task "D8" -- FAILED.
Done building target "_CompileToDalvik" in project "NureTimetable.csproj" -- FAILED.
Done building project "NureTimetable.csproj" -- FAILED.
Build FAILED.
```

**Comment by mobilewares** [comment]
Ok updating to latest everything didn't help... It still seems to be using the 31.0.101-preview.11.117 version for compiling. 

`1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.11.117\tools\Xamarin.Android.D8.targets(79,5): error MSB6006: "java.exe" exited with code 1.
1>Done building project "HassDashMAUI.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========`

**Comment by mobilewares** [comment]
Ok - brand new PR11 MAUI project (via VS22P2 wizard) seems to be working/launching.. Going to hunt through the .csproj + AndroidManifest.xaml files and see if I can spot anything that might need to be changed.

**Comment by mobilewares** [comment]
Ok - seem to have got around the javac error with following steps : 

- Installed latest Android SDK/Tools - no idea if this helped as Xamarin Android tools still same version.
- Removed Nuget Package for Maui Community Toolkit as I wasn't using it - no idea if cause of the issue however.
- Deleted the obj and bin folders in existing solution & rebooted VS/recompiled < probably fix.

My previously working PR10 app still isn't launching properly (Object reference not found when loading main page) - but I think this is something new now as it's actually running/crashing on the Android emulator now.

**Comment by sharpwood** [comment]
It seems to be caused by syncfusion's Nuget package

**Comment by mobilewares** [comment]
I'm not using Syncfusion on my project - so that wasn't the cause for me..  I notice OP was using MAUI Community Toolkit (same as me) so I removed that just in case.

**Comment by sharpwood** [comment]
Installing syncfusion or Maui community toolkit in the newly created Maui program will both cause this problem.

**Comment by maxkoshevoi** [comment]
> Installing syncfusion or Maui community toolkit in the newly created Maui program will both cause this problem.

Maybe that's because they were built for preview 10?

**Comment by mobilewares** [comment]
The Nuget dependencies are showing preview.10 still for the MAUI Community Toolkit so that explains that one - not sure about SyncFusion..

**Comment by maxkoshevoi** [comment]
> not sure about SyncFusion

Looks like Scheduler was also built using Preview 10 (or earlier): https://www.nuget.org/packages/Syncfusion.Maui.Scheduler

I've rebuilt `CommunityToolkit.MauiCompat` and `Rg.Popup.Plugin` with Preview 11, but cannot do this with `Scheduler` since it's closed source. Need to wait for Syncfusion to update their dependencies.
- https://github.com/maxkoshevoi/XamarinCommunityToolkit/tree/mk/preview11
- https://github.com/maxkoshevoi/Rg.Plugins.Popup/tree/mk/preview11

**Comment by maxkoshevoi** [comment]
Yes, it's the dependency issue.

When adding `CommunityToolkit.MauiCompat` built using preview 11 to a new MAUI project, everything works great:
![image](https://user-images.githubusercontent.com/6609929/148385293-01767a45-ac31-4bfa-b52b-5c9292b04f21.png)

But when adding one built using preview 10, project fails to build:
![image](https://user-images.githubusercontent.com/6609929/148385707-abcf93f1-4ec9-4486-a0eb-fc3290064d22.png)

**Comment by mobilewares** [comment]
@maxkoshevoi OT: Hey just wondering - do you have a Nuget for a working PR11/Maui rg.popup component (mostly interested in Android support)? I have been hoping to use this since migrating project to MAUI (as my Xamarin project used it everywhere) - I'm currently using a super hacky hidden overlayed grid (with injected child view) to simulate a popup window right now.  
I did try migrating the Xamarin version a while back but was getting all sorts of issues with Renderers/Handlers not being initialized or implemented in PR10.

**Comment by maxkoshevoi** [comment]
Syncfusion will update their NuGets in a week:
<details>

![image](https://user-images.githubusercontent.com/6609929/148596811-3aa7aa40-553b-4e09-b2df-b44ed992c6e3.png)

</details>

> Do you have a Nuget for a working PR11/Maui rg.popup component

You can build it yourself from https://github.com/rotorgames/Rg.Plugins.Popup/tree/Maui-Compatibility/Rg.Popup.Plugin.Maui (or take it from [here](https://github.com/maxkoshevoi/NureTimetable/blob/maui/.nuget/Rg.Plugins.Popup.3.0.0-alpha11.1.nupkg))
It currently only has Android support. If something doesn't work, feel free to open a PR into that branch.
You can include local NuGet in your project like this: https://github.com/maxkoshevoi/NureTimetable/blob/maui/nuget.config

**Comment by maxkoshevoi** [comment]
I guess, this can be closed, since updating NuGets to Preview 11+ fixes the issue, and it's expected for previews to have breaking changes.

**Comment by marthinch** [comment]
I also get the similar issue but I can fix it by changing dex compiler from d8 (default) to dx then build the project and i change dex compiler to d8 as default

**Comment by maxkoshevoi** [comment]
@marthinch check maui preview version that referenced NuGets are using. They need to be updated to preview 11

**Comment by hazwan223** [comment]
> I also get the similar issue in VS 2022 community but I can fix it by changing dex compiler from d8 (default) to dx then build the project and i change dex compiler back to d8 as the default setting.

how do I do this exactly? thank you.

**Comment by marthinch** [comment]
> > I also get the similar issue in VS 2022 community but I can fix it by changing dex compiler from d8 (default) to dx then build the project and i change dex compiler back to d8 as the default setting.
> 
> how do I do this exactly? thank you.

You can try it from your android project properties > android options > dex compiler

**Comment by hazwan223** [comment]
> > > I also get the similar issue in VS 2022 community but I can fix it by changing dex compiler from d8 (default) to dx then build the project and i change dex compiler back to d8 as the default setting.
> > 
> > 
> > how do I do this exactly? thank you.
> 
> You can try it from your android project properties > android options > dex compiler

Are you on MAUI?
