### ISSUE TITLE
Adding a new class to Platforms/Android/* in a MAUI single project adds noise to .csproj

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#3967]
### Description
Adding a new class to Platforms/Android/* in a MAUI single project adds noise to .csproj

### Steps to Reproduce

1. Create a new MAUI Application project
2. Add a new class file to the Platforms/Android folder from the solution explorer tree
3.  Open the .csproj file and notice the following is added to it:

```
    <ItemGroup>
      <_MauiCompileToAdd Remove="Platforms\Android\AnotherAndroid.cs" />
    </ItemGroup>
    <ItemGroup>
      <None Include="Platforms\Android\AnotherAndroid.cs" />
    </ItemGroup>
```

This does not appear to happen for iOS, MacCatalyst, or Windows folders in the Platforms folder, only android.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Additional Info

```shell
CPS logging shows this:

Add explicit item <None Include='Platforms\Android\Class2.cs'/> due to expected globs not picking up files after evaluation.

This means that CPS is not seeing the class. The targets file that Steve is pointing to (see below) is removing platform-specific items during evaluation and causing the CPS behavior to add the item.
The suggestion is to switch the way platform items are handled in Microsoft.Maui.Controls.SingleProject.targets to using targets that perform the same action during build so that the evaluated project is unchanged.
```

**Comment by jonathanpeppers** [comment]
Svet was looking into this one, existing work item here: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1413769

I think he was trying to figure out if this is a problem in the project system or what... We are not sure.

Maybe we can get rid of `@(_MauiCompileToAdd )` to work around it?

https://github.com/dotnet/maui/blob/779879a5a085a5f4e51385466112c7727b7d1f36/.nuspec/Microsoft.Maui.Controls.SingleProject.targets#L53-L68

Like if we didn't create that item group at all, maybe the problem disappears.
