### ISSUE TITLE
Remove Behaviors when the Control is destroyed

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#3968]
#### Overview
On `Xamarin.Forms` we, as mobile developers and library creators, have to remove by ourselves in order to trigger the `OnDetachingFrom ` method and clean up the `Behavior` (unsubscribing events, for example) as you can see [here on docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/creating#removing-a-behavior-from-a-control)

> In addition, note that behaviors are not implicitly removed from controls when pages are popped from the navigation stack. Instead, they must be explicitly removed prior to pages going out of scope.

#### The problem

With this implementation we need to remove the behavior manually, as a mobile developer that is not hard just annoying, but for library creators that is hard, because we need to know the lifecycle of the control and remove it when it will be destroyed this also can cause a `System.ObjectDisposedException` when we try to remove the `Behavior`.

#### Solution

I would like to suggest changing this implementation and removing the `Behavior` when the control is destroyed, this will trigger the `OnDetachingFrom` automagically and we will be sure that `Behavior` isn't holding any strong reference that could cause memory leaks or other bugs.

### Public API Changes

None.

### Intended Use-Case

On CommunityToolkit.Maui, we changed all our `Effects` to be implemented as `Behaviors`, as you can see here
- https://github.com/CommunityToolkit/Maui/issues/124
- https://github.com/CommunityToolkit/Maui/pull/231
No need to remove the Behavior manually.

### Blockers

- #3604

**Comment by jfversluis** [comment]
Actually @pictos @PureWeen is this done already? Or do we still need work on this?

**Comment by pictos** [comment]
@jfversluis so the Behaviors (from XF) didn't change, because that will be a breaking change. So, not sure if there's a plan to change that for .NET 7, if don't I believe we can close this issue, and if any one needs the Behavior to be cleaned up automatically just use the PlatformBehavior.
