### ISSUE TITLE
Blazor Hot Reload is not fully working

### ISSUE THREAD

**Issue by stefannikolei** [dotnet/maui#3973]
### Description

The Hot Reload Feature is not fully working.

I tried to change `<h1> Hello world </h1>.` This only worked after i switched away from this view and came back.

What worked instant is, when i changed the method on the Counter.page. Changing from `currentCount++` to `currentCound = currentCount +2` worked as expected.

### Steps to Reproduce

1. Create a new Project MAUI Blazor

2. Start the project (Android or Windows, does not matter)

3. Try to change some text.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Visual Studio 2022 17.1.0 Preview 2

**Comment by sps014** [comment]
Same Issue , hot reload not working at all with Blazor MAUI App with preview 11.

**Comment by danardelean** [comment]
Have you uninstalled the VS 2022 Preview and install it from scratch?

**Comment by sps014** [comment]
I tried, 
reinstalled Windows and still it does not work.

**Comment by davidaxtelius** [comment]
Same issue

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/ETvPNO9L4TJMhgk32apjTu4Baiehqn1pPrDxpENgi5fF8g?e=nx2bFR

**Comment by MaTToX3** [comment]
Still an issue in preview 14 and VS Version 17.2.0 Preview 2.0.

**Comment by sps014** [comment]
No hope was planning to early adopt my in my organization but with these basic unstable features will have to use flutter for now.

**Comment by Redth** [comment]
Closing as a duplicate of #4989 - you can track progress there.  Thanks :)
