### ISSUE TITLE
AbsoluteLayout LayoutBounds with two args throws a XamlParseException

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#3979]
### Description

Using two args when setting `AbsoluteLayout.LayoutBounds` throws a `XamlParseException`:

```
<Label Text="blah" AbsoluteLayout.LayoutBounds="30,25" />
```

XamlParseException - Type converter failed: Cannot convert "30,25" into Microsoft.Maui.Graphics.Rectangle.

Two args worked fine in Forms.

Using four args works fine:

```
<Label Text="blah" AbsoluteLayout.LayoutBounds="0, 20, 200, 5" />
```

### Steps to Reproduce

1. Create a new Maui app.
2. Add a `Label` inside an `AbsoluteLayout`, and set `AbsoluteLayout.LayoutBounds` on the `Label` using width/height args only.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Affects Core.

### Did you find any workaround?

Use four args.

**Comment by hartez** [comment]
This is probably fixed by #3930 - need to verify that.
