### ISSUE TITLE
Add/document MAUI support outside VS

### ISSUE THREAD

**Issue by mycroes** [dotnet/maui#3981]
### Description

Currently all documentation refers to installing VS 2022 for MAUI support. I assume Visual Studio isn't required in the long term, but I also don't see any reason why one would need more than the .NET 6 preview release to actually build MAUI applications. I did a few searches but couldn't find any mention of development support outside of VS.

### Public API Changes

Not applicable

### Intended Use-Case

Development of MAUI applications using VS Code / Rider / &lt;insert your favorite editor here&gt;.

**Comment by jfversluis** [comment]
The best experience right now will be Visual Studio (for Mac). While VS Code will get support automagically, we won't be putting in extra effort at the time being to make the experience better there. I think it's unlikely that our docs will include third-party IDEs.

As support is coming in on more of our products the docs will be extended on those parts as well.
