### ISSUE TITLE
VS 2022 Preview 17.1 on PC. Created Maui app. Ran on Android fine. Updated Nuget Pkgs to latest version. Then project wouldn't load.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3983]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-Preview-171-on-PC-Created-Maui/1604188)._

---
I installed Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.1.0 Preview 1.1. I created a new Maui app using the Maui template. I ran the Android version on an (Android 12.0 - API 31) emulator and it ran fine. I updated the Nuget packages listed with updated versions : Microsoft.Graphics.Win2D ver 1.0.0.29-preview3 to Ver 1.0.030 Microsoft.WindowsAppSDK ver 1.0.0.29-preview3 to Ver 1.0.0 These packages successfully install but I get the following error: Collection was modified; enumeration operation may not execute. And 4 errors are listed in the Output window. When I examine the csproj file, the following lines were added:: However the preceding lines in the csproj file remain unchanged: When I exit VS and start VS with the same project, the project won't load. If I then edit the csproj file, removing the newly added ItemGroup and simply change the 2 PacageReference lines from preview version numbers with the latest version numbers the app will run again.

---
#### David Foley on 12/5/2021, 03:01 PM: 

<p>I dont know where the severity code comes from. VS 2022 preview 17.1 is ver 1.1 is fine with the workaround.</p>

#### Feedback Bot on 12/6/2021, 00:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by wenwen60** [comment]
Not repro in VS2022 17.2.0 Preview 2.0 [32215.517.main], the Nuget packages are latest.
