### ISSUE TITLE
RadioButton with content crashes app

### ISSUE THREAD

**Issue by PedroCigaw** [dotnet/maui#3985]
### Description

The application crashes when adding a RadioButton with content on a xaml page.  I tested on Windows and Android crashes with a TypeInitialization exception.

Funnily enough if no content is added it runs fine.

I tried more complex content as well e.g. StackLayout with Label inside still fails.

I'm either doing something very wrong, but can't see how given it fails even the simplest of tests which begs the question....

### Steps to Reproduce

1.  Create Maui App.
2.  Add  <RadioButton Content="Test" />
3. Run the app.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12, Windows 10

### Did you find any workaround?

Only work round I could think of is to create a radio button with no content and have a separate label, not ideal given the effort required.  The option I will probably take is create a custom class that has both the radio and label which should make it easier to undo when the bug is fixed.

**Comment by de1081** [comment]
My app crashes if I add any RadioButton. Content or not

**Comment by shimingsg** [comment]
Not reproducible with windows and Android 11 from using 32214.398.mian.
