### ISSUE TITLE
Tap gestures on iOS no longer work

### ISSUE THREAD

**Issue by JohnHSE** [dotnet/maui#4001]
### Description

As of Preview 11, tap gestures no longer trigger on any view (tried Frame, Label, and Button) in iOS. Works on Windows though, haven't tried Android.

Worked in Preview 10.

### Steps to Reproduce

Add label to a page, and add a tap gesture recogniser that triggers a Console.WriteLine("fg");
Run on iOS
Tap the label
Nada

### Version with bug

Preview 11

### Last version that worked well

Preview 10 (current)

### Affected platforms

iOS

### Affected platform versions

iOS 15, but I resume all

### Did you find any workaround?

No

**Comment by dotMorten** [comment]
I'm hitting this too after moving to Preview 11. My control responds to pinch/stretch, but the tap recognizer never fires.

**Comment by PureWeen** [comment]
This should be fixed with P12

https://github.com/dotnet/maui/pull/3623

If you're still having issues we can re-open
