### ISSUE TITLE
ListView not displayed on Android since updating on prev. 11

### ISSUE THREAD

**Issue by Phil4121** [dotnet/maui#4007]
### Description

Since I have updated on Visual Studio Prev. 2.0 and .Net Maui Prev. 11 (11.2349) I have got problems displaying ListViews and CollectionViews in my Maui Apps.

I created a new Solution form VS and modified the XAML Code like this:

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Playground.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">

    <ScrollView>
		<StackLayout Orientation="Vertical">
			<Label Text="Start ListView" />
			<ListView HeightRequest="400" BackgroundColor="Red">
				<ListView.ItemsSource>
					<x:Array Type="{x:Type x:String}">
						<x:String>mono</x:String>
						<x:String>monodroid</x:String>
						<x:String>monotouch</x:String>
						<x:String>monorail</x:String>
						<x:String>monodevelop</x:String>
						<x:String>monotone</x:String>
						<x:String>monopoly</x:String>
						<x:String>monomodal</x:String>
						<x:String>mononucleosis</x:String>
					</x:Array>
				</ListView.ItemsSource>
			</ListView>
			<Label Text="End ListView" />
		</StackLayout>
    </ScrollView>
</ContentPage>

After starting my Android Emulator, the result is looking like this:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/11144048/148648105-9acb7865-3655-46d2-98c8-eac29b5bb951.png">

If I try to run the App in in Windows the ListView is displayed. I attached my solution.

[Playground.zip](https://github.com/dotnet/maui/files/7833384/Playground.zip)

An implementation like this:
```
		<StackLayout Orientation="Vertical" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
			<Label Text="Start ListView" />
			<ListView BackgroundColor="Red" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
```
does not solve the problem.

But if I modify this line of code: 
`    <StackLayout Orientation="Vertical"> `

like this: 
`    <StackLayout Orientation="Vertical" HeightRequest="500">`
 the ScrollView is displayed again!

### Steps to Reproduce

1. Create a new .Net Maui Solution
2. Mod the MainPage.xaml like I posted it
3. run on Android Emulator

### Version with bug

Preview 11

### Last version that worked well

Preview 10 (current)

### Affected platforms

Android

### Affected platform versions

Android 11.0 API 30

**Comment by dotMorten** [comment]
I'm seeing the listview populate on some pages, but on other pages while the rows are there, each row is empty. I can still click them and go to the next page.

**Comment by danielftz** [comment]
I have similar issue with listview-stacklayout interaction. , however wrapping ListView with StackLayout works fine on Android. Instead, when VerticalStackLayout is used, Listview disappears entirely.

**Comment by kristinx0211** [comment]
not repro on Android 11 using vs 32301.586.main. ListView is displayed:
![image](https://user-images.githubusercontent.com/99457000/156525702-e677f74c-7a19-4e94-b6c7-b31d383b4859.png)
