### ISSUE TITLE
Native controls are not rendered in some cases when BlazorWebView is present on Android

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#4009]
### Description

This is a very strange issue, which was very hard to reproduce.
When the page has both native controls and BlazorWebView, and blazor tag has no inner text in index.html (e.g. `<div id="app"></div>`), then native content is not rendered straight away. It only happens after the first click on BlazorWebView.

Probably the underlying issue is not that specific, but hopefully that would allow to track it.

It did not reproduce on Preview 10.

Repro project: https://github.com/Dreamescaper/maui-4009-repro/

![qemu-system-x86_64_mmW4atViGT](https://user-images.githubusercontent.com/17177729/148659913-721c8f1d-3708-4499-9899-dce7ee6f2754.gif)

### Steps to Reproduce

1.  Run attached repro project.

ER:
Native label and button are visible straight away.

AR:
Native label and button are not visible straight away. They only become visible when you interact with BlazorWebView.

### Version with bug

Preview 11

### Last version that worked well

Preview 10 (current)

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Add inner text, e.g. `<div id="app">Loading...</div>`

**Comment by Eilon** [comment]
Marking as area/controls because ultimately, it's the Button that isn't rendering, yet the BlazorWebView is.

**Comment by kristinx0211** [comment]
Repro on Version 17.2.0 Preview 2.0 [32214.398.main] with above project.

**Comment by Dreamescaper** [comment]
Cannot reproduce this one anymore.
