### ISSUE TITLE
The default MAUI and MAUI-Blazor projects do not work when published for Windows.

### ISSUE THREAD

**Issue by aokocax** [dotnet/maui#4010]
### Description

Hello, I published the projects by trying almost all the options, but all of them crash without any screen after the program is run.
I see attached error when I look from Eventviewer. I also tried it on both windows 10 and windows 11, no difference.

Tried options
Target runtime: Win10-x64,Win10-x86, Win-x64,Win-x86
Deployment mode: Self-contained, Framework dependent (it gives .net framework error but already installed)
Configuration: Debug-release
File publish options: Produce single file, Enable-disable ready to run, trim unused code.

![ssdefault](https://user-images.githubusercontent.com/1059475/148670647-45782658-bbed-4eec-a935-1c274cf0e22c.jpg)
![ssop](https://user-images.githubusercontent.com/1059475/148670649-890d0084-b35a-46b2-b5be-cbdcc0acbabb.jpg)

### Steps to Reproduce

1. Create Maui or Maui-Blazor Projects
2. Remove other platforms
3. Publish for windows
4. Click and run the exe file

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Relevant log output

```shell
Application: MauiApp22.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Dll was not found.
   at MauiApp22.WinUI.Program.Main(String[] args)
```

**Comment by mkArtakMSFT** [comment]
Removing the `Blazor` label, as the issue happens also for non-Blazor project.

**Comment by jfversluis** [comment]
Hey everyone! I've been trying to look into this and wrote up all my findings in #4329. In an attempt to not be all over the place with this I'm closing this one, let's centralise the discussion in the aforementioned issue, thanks!
