### ISSUE TITLE
[Android] FontImageSource not applied Color or Size properties

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4013]
### Description

The Color or Size properties are not working on FontImageSource on Android.

```
<Image>
     <Image.Source>
          <FontImageSource FontFamily="Material Icons" Glyph="&#xe5e0" Size="12" Color="White" />
     </Image.Source>
</Image>
```

### Steps to Reproduce

1. Download this project: https://github.com/jsuarezruiz/netmaui-travel-app-challenge
2. Launch the App in an Android emulator or Device.
3. The alarm icon at the top is huge and gray. Have the wrong size and color.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 10 and 11

### Did you find any workaround?

Use an image as Icon

**Comment by PineYi** [comment]
Reproduce in Android with above project.
