### ISSUE TITLE
[Android] Wrong position clipping layouts or image 

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4014]
### Description

After clip an image to have a circle effect, the image size and position are not correct.

### Steps to Reproduce

1. Download this project https://github.com/jsuarezruiz/netmaui-travel-app-challenge
2. See the top left circular image. Have a wrong size. (Also can compare it with the result from the Xamarin.Forms project)

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 10 and 11

**Comment by PineYi** [comment]
Reproduce in Android with above project.

**Comment by jsuarezruiz** [comment]
The issue should be fixed with latest Preview 14. I am going to close this issue but open a new one if can reproduce the issue again or find a another one.
