### ISSUE TITLE
[Android] Horizontal CollectionView not rendering

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4015]
### Description

Nothing is rendered trying to use a CollectionView with an horizontal Layout (but, occupies the expected space).

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-travel-app-challenge
2. Launch the App on an Android emulator or Device.
3. Below the "Recommended" text nothing is rendered.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 10 and 11

### Did you find any workaround?

Not at all. Bindable Layout is crashing.

**Comment by PineYi** [comment]
Reproduce in Android with above project.

**Comment by Redth** [comment]
Fixed in main.
