### ISSUE TITLE
[Android] Crash using Bindable HorizontalStackLayout

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4016]
### Description

Crash using an Horizontal Bindable StackLayout.

`"Java.Lang.RuntimeException: 'Canvas: trying to draw too large(181500000bytes) bitmap.'".`

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-travel-app-challenge
2. Update the code to replace a CollectionView (not rendering) by a Bindable StackLayout.
3. Launch the App in an Android emulator or device.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 10 and 11

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/Ec48Q4Le7YhIsRnKrC8dVPsBeZjOJeJPEZ96c0nPfeac4A?e=eQcfWV

**Comment by hartez** [comment]
Does not crash on 17.4.
