### ISSUE TITLE
[Android] Setting the BackgroundColor property in a ContentPage have not effect

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4017]
### Description

Setting the BackgroundColor property in a ContentPage have not effect.

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-travel-app-challenge or create a new .NET MAUI App.
2. Set the BackgroundColor at ContentPage level. Is not working.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Set the BackgroundColor at Layout level.

**Comment by mattscheffer** [comment]
No Repro with 32208.182.Main on Pixel 5 simulator (Android 11). I tested by removing most of code from a new MAUI app and adjusting the Background Color.

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="_4017.MainPage"
             BackgroundColor="Green">

    <ScrollView>
        <Grid RowSpacing="25" RowDefinitions="Auto,Auto,Auto,Auto,*"
              Padding="{OnPlatform iOS='30,60,30,30', Default='30'}">
        </Grid>
    </ScrollView>
</ContentPage>
```
