### ISSUE TITLE
Slow Speed of Visual Studio 2022 Preview Maui File New app and Deployment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4027]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Slow-Speed-of-Visual-Studio-2022-Preview/1577298)._

---
Uppon creating a new Maui app after installing visual studio 2022 and Going file new Maui app. The speed for build is not as quick as noticed in build. I have done a short video demo for you of the situation below.

https://screenrec.com/share/DS94fte3q5

---
#### Feedback Bot on 11/9/2021, 10:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Older issue and "slow speed" is a bit hard to diagnose. I'm going to assume that performance is better by now. Additionally, this is something of continuing interest to us so we will be iterating on this. THanks for the report!
