### ISSUE TITLE
Assinging SingleProject tag the value of false  in csproj file does not have any effect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4029]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Assinging-SingleProject-tag-the-value-of/1588203)._

---
I changed the value of  SingleProject tag in csproj file of maui project from true to false. This should have the effect on solution folder structure. I was expecting to see different folders for all platforms. But the change does not have any effect.

---
#### Feedback Bot on 11/17/2021, 11:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I don't think this tag does what you expect it to do. If I understand you correctly, just might expect that by setting this value to false, the whole solution will be transformed to how it worked with Xamarin.Forms. This is not the case. This setting is only there to accomodate for the new single-project approach and to let the build system know that we are in fact working with a single-project so it will make some different choices in how to build your application.

I hope this clears it up, if I got it wrong, please let me know what you think isn't right with this. Thanks!
