### ISSUE TITLE
unable to restore the packages in visual studio

### ISSUE THREAD

**Issue by Shahid119** [dotnet/maui#4038]
### Description

Unable to restore the packages in Visual Studio 2021 preview **v17.1.0**
 I have uninstalled the VS but still getting error how to fix please help me
![Screenshot (47)](https://user-images.githubusercontent.com/97408470/148897139-152cc4d1-8f72-4bde-9cfb-b9750faffa7a.png)

### Steps to Reproduce

After Creating New Project 
Files Are not restoring

### Version with bug

Preview 11

### Last version that worked well

Preview 11

### Affected platforms

Windows

### Affected platform versions

Windows10.0.19041

### Did you find any workaround?

when I check with **Maui-Check **
`      _   _   _____   _____     __  __      _      _   _   ___
     | \ | | | ____| |_   _|   |  \/  |    / \    | | | | |_ _|
     |  \| | |  _|     | |     | |\/| |   / _ \   | | | |  | |
  _  | |\  | | |___    | |     | |  | |  / ___ \  | |_| |  | |
 (_) |_| \_| |_____|   |_|     |_|  |_| /_/   \_\  \___/  |___|

 .NET MAUI Check v0.10.0.0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────This tool will attempt to evaluate your .NET MAUI development environment.
If problems are detected, this tool may offer the option to try and fix them for you, or suggest a way to fix them
yourself.

Thanks for choosing .NET MAUI!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────» Synchronizing configuration... ok
» Scheduling appointments... ok

> OpenJDK 11.0 Checkup...
  - 11.0.12 (C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\..)

> Visual Studio 17.1.0-pre.1.0 Checkup...
  - 16.11.8-pre.1.0
  - 15.9.42
  - 17.1.0-pre.2.0 - C:\Program Files\Microsoft Visual Studio\2022\Preview

> Android SDK Checkup...
  - emulator (31.1.4)
  - build-tools;31.0.0 (31.0.0)
  - platforms;android-31 (1)
  - system-images;android-31;google_apis;x86_64 (8)
  - platform-tools (31.0.3)
  - cmdline-tools;5.0 (5.0)

> Android Emulator Checkup...
  - Emulator: pixel_5_-_api_30 found.

> .NET SDK Checkup...
  - 2.1.201 - C:\Program Files\dotnet\sdk\2.1.201
  - 2.1.202 - C:\Program Files\dotnet\sdk\2.1.202
  - 2.1.526 - C:\Program Files\dotnet\sdk\2.1.526
  - 2.1.602 - C:\Program Files\dotnet\sdk\2.1.602
  - 2.1.604 - C:\Program Files\dotnet\sdk\2.1.604
  - 2.1.700-preview-009597 - C:\Program Files\dotnet\sdk\2.1.700-preview-009597
  - 2.1.700-preview-009618 - C:\Program Files\dotnet\sdk\2.1.700-preview-009618
  - 2.1.800-preview-009677 - C:\Program Files\dotnet\sdk\2.1.800-preview-009677
  - 2.1.800-preview-009696 - C:\Program Files\dotnet\sdk\2.1.800-preview-009696
  - 2.1.800 - C:\Program Files\dotnet\sdk\2.1.800
  - 2.2.107 - C:\Program Files\dotnet\sdk\2.2.107
  - 2.2.202 - C:\Program Files\dotnet\sdk\2.2.202
  - 2.2.204 - C:\Program Files\dotnet\sdk\2.2.204
  - 2.2.300-preview-010046 - C:\Program Files\dotnet\sdk\2.2.300-preview-010046
  - 2.2.300-preview-010067 - C:\Program Files\dotnet\sdk\2.2.300-preview-010067
  - 2.2.400-preview-010195 - C:\Program Files\dotnet\sdk\2.2.400-preview-010195
  - 2.2.400-preview-010219 - C:\Program Files\dotnet\sdk\2.2.400-preview-010219
  - 2.2.400 - C:\Program Files\dotnet\sdk\2.2.400
  - 3.0.100-preview5-011568 - C:\Program Files\dotnet\sdk\3.0.100-preview5-011568
  - 3.1.415 - C:\Program Files\dotnet\sdk\3.1.415
  - 3.1.416 - C:\Program Files\dotnet\sdk\3.1.416
  - 5.0.100-rc.2.20479.15 - C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15
  - 5.0.100 - C:\Program Files\dotnet\sdk\5.0.100
  - 5.0.101 - C:\Program Files\dotnet\sdk\5.0.101
  - 5.0.209 - C:\Program Files\dotnet\sdk\5.0.209
  - 5.0.210 - C:\Program Files\dotnet\sdk\5.0.210
  - 5.0.403 - C:\Program Files\dotnet\sdk\5.0.403
  - 5.0.404 - C:\Program Files\dotnet\sdk\5.0.404
  - 6.0.100-preview.3.21202.5 - C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5
  - 6.0.101 - C:\Program Files\dotnet\sdk\6.0.101
  - 6.0.200-preview.21617.4 - C:\Program Files\dotnet\sdk\6.0.200-preview.21617.4

> .NET SDK - Workload Deduplication Checkup...

> Edge WebView2 Checkup...
  - Found Edge WebView2 version 97.0.1072.55

> .NET SDK - Workloads (6.0.100) Checkup...
  x android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 31.0.101-preview.10.59) not installed.
  x ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  x maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  x tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  x macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.101-preview.10.251) not installed.
  x maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.101-preview.10.2068) not installed.
  x wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0) not installed.
  - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0) installed.
! Managing Workload installation from the CLI is NOT recommended.  Instead you should install the latest Visual Studio
preview to automatically get the newest release of .NET MAUI workloads installed.
Are you sure you would like to continue the CLI workload installation? [y/n] (n): y

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Recommendation: Install or Update SDK Workloads
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
! Attempt to fix? [y/n] (y): y
» Attempting to fix: .NET SDK - Workloads (6.0.100)
SHELL: C:\Program Files\dotnet\dotnet.exe workload install --from-rollback-file "C:\Users\DEEP_SECRET\AppData\Local\Temp\maui-check-f1322f71\workload.json" android-aot ios maccatalyst tvos macos maui wasm-tools --source "https://api.nuget.org/v3/index.json"

Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: microsoft.net.workload.mono.toolchain.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.android: microsoft.net.sdk.android.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.macos: microsoft.net.sdk.macos.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: microsoft.net.sdk.maccatalyst.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.tvos: microsoft.net.sdk.tvos.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.maui: microsoft.net.sdk.maui.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.workload.emscripten: microsoft.net.workload.emscripten.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Failed to update the advertising manifest microsoft.net.sdk.ios: microsoft.net.sdk.ios.manifest-6.0.200 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Downloading microsoft.net.sdk.android.manifest-6.0.200.msi.x64 (31.0.101-preview.10.59)
Workload installation failed. Rolling back installed packs...
Downloading microsoft.net.workload.mono.toolchain.manifest-6.0.200.msi.x64 (6.0.1)
Installation rollback failed: One or more errors occurred. (microsoft.net.workload.mono.toolchain.manifest-6.0.200.msi.x64::6.0.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json".)
Workload installation failed: One or more errors occurred. (microsoft.net.sdk.android.manifest-6.0.200.msi.x64::31.0.101-preview.10.59 is not found in NuGet feeds https://api.nuget.org/v3/index.json".)
Description:
  Install one or more workloads.

Usage:
  dotnet workload install [<WORKLOAD_ID>...] [options]

Arguments:
  <WORKLOAD_ID>  The NuGet package ID of the workload to install.

Options:
  --configfile <FILE>      The NuGet configuration file to use.
  -s, --source <SOURCE>    The NuGet package source to use during the restore. To specify multiple sources, repeat the option.
  --skip-manifest-update   Skip updating the workload manifests.
  --include-previews       Allow prerelease workload manifests.
  --temp-dir <temp-dir>    Specify a temporary directory for this command to download and extract NuGet packages (must be secure).
  --disable-parallel       Prevent restoring multiple projects in parallel.
  --ignore-failed-sources  Treat package source failures as warnings.
  --no-cache               Do not cache packages and http requests.
  --interactive            Allows the command to stop and wait for user input or action (for example to complete authentication).
  -v, --verbosity <LEVEL>  Set the MSBuild verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
  -?, -h, --help           Show command line help.

Fix failed - Workload Install failed: `dotnet workload install --from-rollback-file "C:\Users\DEEP_SECRET\AppData\Local\Temp\maui-check-f1322f71\workload.json"
android-aot ios maccatalyst tvos macos maui wasm-tools --source "https://api.nuget.org/v3/index.json"`
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

! There were one or more problems detected.
Please review the errors and correct them and run maui-check again.

Press enter to exit...
`

**Comment by Shahid119** [comment]
I am now totally Confused
When I Check For Maui 
with `maui-check`
it shows error 
`> .NET SDK - Workloads (6.0.100) Checkup...
  x android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 31.0.101-preview.10.59) not installed.
  x ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  x maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  x tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.101-preview.10.251) not installed.
  x macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.101-preview.10.251) not installed.
  x maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.101-preview.10.2068) not installed.
  x wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0) not installed.
  - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0) installed.
! Managing Workload installation from the CLI is NOT recommended.  Instead you should install the latest Visual Studio preview to automatically get the newest release of
.NET MAUI workloads installed.`

But when i Check For Maui workload it show this 

`C:\WINDOWS\system32>dotnet workload search

Workload ID           Description
-------------------------------------------------------------------------------------------
android               .NET SDK Workload for building Android applications.
android-32            Preview support for Android API-32.
android-aot           .NET SDK Workload for building Android applications with AOT support.
ios                   .NET SDK Workload for building iOS applications.
maccatalyst           .NET SDK Workload for building macOS applications with MacCatalyst.
macos                 .NET SDK Workload for building macOS applications.
maui                  .NET MAUI SDK for all platforms
maui-android          .NET MAUI SDK for Android
maui-desktop          .NET MAUI SDK for Desktop
maui-ios              .NET MAUI SDK for iOS
maui-maccatalyst      .NET MAUI SDK for Mac Catalyst
maui-mobile           .NET MAUI SDK for Mobile
maui-windows          .NET MAUI SDK for Windows
tvos                  .NET SDK Workload for building tvOS applications.
wasm-tools            .NET WebAssembly build tools`


please help me to fix the issue so that i can use MAUI

**Comment by Shahid119** [comment]
Issue Solved thanks

**Comment by paaltuv** [comment]
Updated to VS2022 Preview 6 today. I can confirm identical issue.

**Comment by Amir-Care** [comment]
Not Repro on VS 17.2.0 Preview 2.0 [32208.484.main]
