### ISSUE TITLE
[Windows] Frames do not size correctly

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4042]
### Description

Wrong sizes using StackLayout inside ScrollView. Can reproduce the issue with different controls but in the screenshot we are using Frames.
![image](https://user-images.githubusercontent.com/6755973/148914131-e332997d-9f72-46f0-8076-cad57d7319ab.png)

### Steps to Reproduce

1. Download [BrushesDemos.zip](https://github.com/dotnet/maui/files/7845186/BrushesDemos.zip)
2. Navigate to the first section, SolidColorBrush sample.
 

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by YuqinSong** [comment]
Verified repro on Windows. Repro project is available:
[#4042.zip](https://github.com/dotnet/maui/files/8159908/4042.zip)

**Comment by Redth** [comment]
@jsuarezruiz this sample won't run anymore and I'm not sure why.  I fixed the Assets\ folder prefix but it still throws at runtime with no good output/stacktrace

**Comment by hartez** [comment]
This is a problem with Frames. The presence of a ScrollView has no effect, and replacing the Frames with Buttons shows the expected layout.
