### ISSUE TITLE
CollectionView using Static property as ItemsSource is not working

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4043]
### Description

CollectionView using Static property as ItemsSource is not working
![image](https://user-images.githubusercontent.com/6755973/148917019-1ba5e208-d27a-4d1d-ba2e-f721b321d6d9.png)

Can reproduce the issue in all the platforms.

NOTE: Is working on Xamarin.Forms.

### Steps to Reproduce

1. Download [BrushesDemos.zip](https://github.com/dotnet/maui/files/7845302/BrushesDemos.zip)
2. Navigate to the sample "All SolidColorBrush fields"
 

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Windows 10 1909, Android 11, etc

**Comment by v-xiaofchen** [comment]
Verified repro with Android 11 and the above project.

**Comment by Redth** [comment]
I repro'd this but this isn't the bug it seems to be, in fact not a bug.

The main issue is that the reflection used to find these brushes and construct the list returns no items in the list that's assigned as a static property.  Once I fixed that I got items showing up again.  Calling this not an issue in main.
