### ISSUE TITLE
[Windows] Incorrect rendering Path and RenderTransform property not working

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4047]
### Description

Incorrect rendering Path and RenderTransform property not working
![image](https://user-images.githubusercontent.com/6755973/148921431-1afa2c58-88e6-4784-9118-7bd3d8421628.png)

### Steps to Reproduce

1. Download [ShapesDemos.zip](https://github.com/dotnet/maui/files/7845488/ShapesDemos.zip)
2. Launch the App on Windows and navigate to the "Path render transform examples"
 

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by jsuarezruiz** [comment]
Also, not working on Android.

**Comment by Amir-Care** [comment]
Repro on VS 17.2.0 Preview 2.0 [32208.484.main]

**Comment by jsuarezruiz** [comment]
This issue have been fixed by https://github.com/dotnet/maui/pull/5190
