### ISSUE TITLE
[iOS] Crash trying to launch an App using a NavigationPage

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4048]
### Description

Crash trying to launch an App using a NavigationPage

`**ObjCRuntime.RuntimeException:** 'Failed to marshal the Objective-C object 0x7fe533b1c0e0 (type: Microsoft_Maui_Controls_Compatibility_Platform_iOS_NavigationRenderer_FormsNavigationBar). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Microsoft.Maui.Controls.Compatibility.Platform.iOS.NavigationRenderer+FormsNavigationBar' does not have a constructor that takes one NativeHandle argument).'`

### Steps to Reproduce

1. Download [BrushesDemos.zip](https://github.com/dotnet/maui/files/7845549/BrushesDemos.zip)
2. Try to launch the sample on iOS device or simulator using iOS 15. 

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Relevant log output

```shell
**ObjCRuntime.RuntimeException:** 'Failed to marshal the Objective-C object 0x7fe533b1c0e0 (type: Microsoft_Maui_Controls_Compatibility_Platform_iOS_NavigationRenderer_FormsNavigationBar). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Microsoft.Maui.Controls.Compatibility.Platform.iOS.NavigationRenderer+FormsNavigationBar' does not have a constructor that takes one NativeHandle argument).'
```

**Comment by mattscheffer** [comment]
Not reproducible with 32208.182.main using iOS 15. Project deploys correctly.
