### ISSUE TITLE
[Windows] Not correctly rendering complex Paths (using multiple Paths)

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4049]
### Description

Not correctly rendering complex Paths (using multiple Paths).

![image](https://user-images.githubusercontent.com/6755973/148923063-9586d6c1-a1fa-4f46-9759-8dd7c2a9d008.png)
_Poor baby elephant!_

### Steps to Reproduce

1. Download [ShapesDemos.zip](https://github.com/dotnet/maui/files/7845586/ShapesDemos.zip)
2. Launch the App on Windows and navigate to the "Baby elephant demo"

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by jsuarezruiz** [comment]
The same happens with similar samples like the Flower, Monkey Face and others.

**Comment by shimingsg** [comment]
Verified repro with windows and the above project.

**Comment by Redth** [comment]
Looks better now :)
