### ISSUE TITLE
Port RadioButton.GroupName to Handler

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#405]
Please read the [Handler Property PR Guidelines](https://github.com/dotnet/maui/wiki/Handler-Property-PR-Guidelines) for instructions on how to create and submit a PR for this issue.

Thanks for your help!

**Comment by davidbuckleyni** [comment]
How easy would this be to do? Can I pick this up if their an example of something similar being done @hartez

**Comment by RemcoDEV** [comment]
I might want to pick this up, but it seems that it is not yet ready to pick it up?
https://github.com/dotnet/maui/pull/482
