### ISSUE TITLE
[Windows] Animating a Shape using Device.Timer not correctly working

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4050]
### Description

Animating a Shape using Device.Timer not correctly working.

### Steps to Reproduce

1. Download [ShapesDemos.zip](https://github.com/dotnet/maui/files/7845621/ShapesDemos.zip)
2. Launch the App on Windows and navigate to the "Spiral demo". 

Should see a spiral animation but, is not working. 

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by shimingsg** [comment]
Verified repro with Windows and the above project.
