### ISSUE TITLE
[Android] Clipping not working

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4053]
### Description

Clipping images is not working on Android.
![image](https://user-images.githubusercontent.com/6755973/148926738-dba8e18f-0d82-416b-ada7-10272d24e10b.png)

### Steps to Reproduce

1. Download [ShapesDemos.zip](https://github.com/dotnet/maui/files/7845747/ShapesDemos.zip)
2. Navigate to Clipping sample.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by jsuarezruiz** [comment]
The issue should be fixed with latest Preview 14. I am going to close this issue but open a new one if can reproduce the issue again or find a another one.
