### ISSUE TITLE
FillRule property not working in Polygon and Polyline

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4054]
### Description

FillRule property not working in Polygon and Polyline. Happens in all the platforms.

### Steps to Reproduce

1. Download [ShapesDemos.zip](https://github.com/dotnet/maui/files/7846531/ShapesDemos.zip)
2. Launch the App and navigate to the Polygon sample.  There are polygons with different FillRule value but is rendering the same.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Windows 10 1909, Android 11, etc

**Comment by mattscheffer** [comment]
Verified repro with Android 11 and the above project. Additionally, project failed draw the polygons with iOS 15.2 simulators.

**Comment by v-xiaofchen** [comment]
Verified repro with windows and the above project.

**Comment by jsuarezruiz** [comment]
Fixed by #5166
