### ISSUE TITLE
Supplying FileProvider in BlazorWebView has design flaw since it throws exception if the path doesn't exist

### ISSUE THREAD

**Issue by budcribar** [dotnet/maui#4058]
### Description

If you want to provide your own FileProvider to either the WinForms or Wpf Blazor controls you need to override public virtual IFileProvider CreateFileProvider(string contentRootDir). However, this will not work  because an exception will be thrown at the following line 173 in BlazorWebView.cs (var assetFileProvider = new PhysicalFileProvider(contentRootDirFullPath) since the directory does not exist. The directory doesn't exist because you are providing the files from another source which is why you are overriding the CreateFileProvider ;)

### Steps to Reproduce

Override  virtual IFileProvider CreateFileProvider(string contentRootDir) in either the Wpf or WinForms BlazorWebView with a file provider which returns the file contents from something other than the file system such as embedded resources, database, embedded constants, etc.

Notice that when you run your app it will fail on line 173 since you no longer need to have a wwwroot directory

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

All

### Did you find any workaround?

Workaround is to have a wwwroot directory with nothing in it. However, it would be more appropriate to either catch the exception or not try and combine the users file provider with the default PhysicalFileProvider

**Comment by Eilon** [comment]
Good find. Some ideas on ways to fix:

1. Check if the directory exists and if not, don't create the physical file provider
2. Pass the system-created file provider into `CreateFileProvider(string contentRootDir)` and have the user create the composite file provider themselves, wrapping the original, if they want. The new signature would be `CreateFileProvider(string contentRootDir, IFileProvider defaultFileProvider)`. So in your case you could ignore `defaultFileProvider` and then there would be no errors.

**Comment by budcribar** [comment]
I would prefer the control not create the physical file provider when the user supplies the file provider. One use case is where an embedded file provider is supplied for the express purpose of preventing users of the app from modifying the wwwroot directory. 

If the developer wants a composite file provider they can easily create it. 

so I would prefer line 167 look like:
IFileProvider fileProvider = customFileProvider == null	? assetFileProvider : customFileProvider;

**Comment by budcribar** [comment]
@Eilon 

> Good find. Some ideas on ways to fix:
> 
> 1. Check if the directory exists and if not, don't create the physical file provider
> 2. Pass the system-created file provider into `CreateFileProvider(string contentRootDir)` and have the user create the composite file provider themselves, wrapping the original, if they want. The new signature would be `CreateFileProvider(string contentRootDir, IFileProvider defaultFileProvider)`. So in your case you could ignore `defaultFileProvider` and then there would be no errors.

You could also return the default file provider instead of null (ie.) 
public virtual IFileProvider CreateFileProvider(string contentRootDir)
		{
                        var defaultFileProvider = new PhysicalFileProvider(contentRootDir)
			return defaultFileProvider;
		}


and then in the override...
public overrideIFileProvider CreateFileProvider(string contentRootDir)
{
      var customProvider = new CustomProvider();
      return new CompositeFileProvider(customProvider, base.CreateFileProvider)
}

**Comment by Eilon** [comment]
@budcribar I think I like your last post the most. Have `BlazorWebView.CreateFileProvider(...)` have an actual implementation that creates the default `PhysicalFileProvider`, as opposed to being empty, like it is now. And an overriding class can choose whether to even call `base.CreateFileProvider(...)` and what to do with that result. I think that's the best of all worlds.

**Comment by Eilon** [comment]
@budcribar I think I understand what you're saying about the contentRootDir parameter, but calling base.Create().Root seems hacky, and computing it manally is not trivial. I agree that many cases won't need it, but at the same time, I don't think many people will override this method to begin with. But for the cases that do need it, I think having it is better than not. And cases that don't need it can just ignore it (obviously).

Here's the Work In Progress: https://github.com/dotnet/maui/commit/1438539057d30a7fccb5edaf8e267e0b58cc6ef7 (WPF/WinForms implemented, MAUI is next)

**Comment by budcribar** [comment]
@Eilon Works for me !
