### ISSUE TITLE
Missing error message if the required properties are not set on the WinForms and Wpf BlazorWebView controls

### ISSUE THREAD

**Issue by budcribar** [dotnet/maui#4059]
### Description

If a developer forgets to set a property (such as the HostPage or Services) on a BlazorWebView control, they will not get any error message and be left wondering why the WebView control did not render.  This more of a usability issue than a bug.

### Steps to Reproduce

Take a BlazorWebView sample program and remove one of the required properties. The developer will not receive any feedback except for noticing the control does not render.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

All

### Did you find any workaround?

Make sure to supply all the required parameters to the WebView control.

**Comment by Eilon** [comment]
We're open to suggestion on what would be a good behavior in this case. Throwing an exception wouldn't work because it's perfectly valid to have a no-op BlazorWebView because maybe the properties will get set "later."

What might be a reasonable way to inform someone that their BlazorWebView isn't fully set up, without annoying someone who intentionally plans to set things up "later" in the app?

**Comment by budcribar** [comment]
Maybe throw an error if the Visibility is set to Visible but otherwise ignore?

**Comment by Eilon** [comment]
@budcribar the thing is, that's not actually invalid. It's unusual, for sure, but if an app is delay-loading some components, it's reasonable for the control to be visible, but not yet fully configured (maybe they put a visual overlay on it saying "loading..." until the Blazor stuff is fully configured and loaded, say, after logging in.

**Comment by budcribar** [comment]
@Eilon Not sure I follow. If the BlazorWebView control has not been fully configured and is set to visible it will be doing and showing nothing (since StartWebViewCoreIfPossible() will effectively be a noop) . If you wanted to delay-load some components you could 



Start with Hidden Visibility
Show Overlay
delay...
Set HostPage
Set Visibility to Visible

and the normal use case would be
Visibility set to Visible
HostPage and services are set
-> works fine

and in the case you forgot to set HostPage
Visibility set to Visible
HostPage NOT set
StartWebViewCoreIfPossible throws Exception because user expects to see something but they forgot to set HostPage

Not a showstopper either way, but I ran into this while testing where HostPage was not set and I had to spend time trying to figure out why the control was not rendering

**Comment by Eilon** [comment]
@budcribar I agree that my example was contrived, but it's still not really _invalid_. In my mind it's similar to a DataGrid that has no columns or no data source set. It's a perfectly nice control that displays exactly what you told it to display: nothing! It doesn't throw, it just does everything you told it to do.
