### ISSUE TITLE
Port RadioButton.Value to Handler

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#406]
Please read the [Handler Property PR Guidelines](https://github.com/dotnet/maui/wiki/Handler-Property-PR-Guidelines) for instructions on how to create and submit a PR for this issue.

Thanks for your help!

**Comment by bkaankose** [comment]
I can take this one if possible.

**Comment by hartez** [comment]
This will probably need #482 (which creates the handlers and adds IsChecked) to get merged first.
