### ISSUE TITLE
System.Console does not flush to chromium debugger console in Blazor MAUI

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/maui#4066]
### Description

`Console.Write(...)` or `Console.WriteLine(...)` does not write to the chromium debugger tools console like it does in Blazor WASM.

### Steps to Reproduce

`Console.Write("Hello World");`
Press F12 when in the Windows GUI to open the debug tools -> Navigate to console -> Execute Code above -> Nothing.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This behavior is by design as you're not running on WebAssembly.

**Comment by KieranDevvs** [comment]
@mkArtakMSFT So where is `System.Console` intended to flush to under Blazor MAUI?
