### ISSUE TITLE
Add children of custom content control after all the public API's are set

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#4071]
### Description

I have a custom content control, for which need to create the content after all the public APIs are initialized. But don't how know to do the same. In other platforms, we are following the below approaches but we couldn't find any here,

WPF, WinUI => OnApplyTemplate and IsLoading event
Xamarin.Forms => on native view rendering.

If we add the content inside the constructor then need to update on each property that is being set on XAML or code behind which makes performance issue on initial loading.

Can anyone please help me to add children of custom control on view loading instead constructor and measure?

### (Public) API Changes

NA

### Usage Scenarios

Improves the loading performance of custom control.

### Backward Compatibility

NA

### Difficulty

Medium

**Comment by mattleibow** [comment]
I think we now have enough events that this can be done. Some "events" are:

Before properties set:

 - **Constructor**

After properties set:

 - **HandlerChanging event** - before the view is assigned a handler (but also if a new handler comes in)
 - **HandlerChanged event** - after the view is assigned a handler (but also if there is a new handler)
 - **Loaded event** - the view is attached to the UI (and again if it is detached and re-attached)
 - **Unloaded event** - the view is detached from the UI (and again if it is re-attached and then detached again)

I also created an issue to track the new docs that would be great to get up: https://github.com/dotnet/docs-maui/issues/1260

**Comment by mattleibow** [comment]
Closing this issue as completed as we now have various hooks to do this. Please open a new issue if there is an issue while using these events.
