### ISSUE TITLE
Visual Studio Preview 2022 Crashing When Opening Create App Packages Wizard

### ISSUE THREAD

**Issue by almas-f** [dotnet/maui#4073]
### Description

I am using Visual Studio 2022 version 17.1.0 Preview 2.0
Project : MAUI Winows Application
When opening the Create App Packages, the visual studio is crashing.

### Steps to Reproduce

1.Create a MAUI Project.
2.Go to Project->Publish->Create App Package
or
Right Click on Project in Solution Explorer -> Package and Publish -> Create App Packages

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

**Comment by jfversluis** [comment]
Hey @almas-f I don't even see that option in the menu. Could you maybe add some screenshots of what you're seeing?

**Comment by v-longmin** [comment]
Verified not repro on windows, repro project: 
[4073.zip](https://github.com/dotnet/maui/files/8139650/4073.zip)
