### ISSUE TITLE
[Android] Wrong positions using AbsoluteLayout

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4074]
### Description

Wrong positions using AbsoluteLayout. The result using .NET MAUI:
![image](https://user-images.githubusercontent.com/6755973/149096867-3b26c171-56eb-455f-9122-a776d90010b6.png)

In Xamarin.Forms:
![image](https://user-images.githubusercontent.com/6755973/149096601-21bb6860-024a-49f2-9e9d-be7d5c1dfaf6.png)

### Steps to Reproduce

1. Download [AbsoluteLayoutDemos.zip](https://github.com/dotnet/maui/files/7853140/AbsoluteLayoutDemos.zip)
2. Launch the App on Android and navigate to the first sample.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jsuarezruiz** [comment]
There are more samples failing. For example, the Chess board sample.

.NET MAUI
![image](https://user-images.githubusercontent.com/6755973/149097747-bdb80057-2644-4019-962b-47555300b899.png)

Xamarin.Forms
![image](https://user-images.githubusercontent.com/6755973/149097609-65fab33e-a976-4c5a-aac8-89b790c673f2.png)

**Comment by davidbritch** [comment]
I tried this sample against VS main (effectively P12) on Mon and it was fine, aside from the chessboard.

**Comment by shimingsg** [comment]
Not reproducible with Android 11.
