### ISSUE TITLE
[Windows] Wrong positions using AbsoluteLayout

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4075]
### Description

Wrong positions using AbsoluteLayout. Probably the issue is the same as https://github.com/dotnet/maui/issues/4074
![image](https://user-images.githubusercontent.com/6755973/149098267-14db107d-cf87-4e0a-9de6-a70572421e51.png)

### Steps to Reproduce

1. Download [AbsoluteLayoutDemos.zip](https://github.com/dotnet/maui/files/7853200/AbsoluteLayoutDemos.zip)
2. Launch the App on Android and navigate to the first sample.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by davidbritch** [comment]
I tried this sample against VS main last Fri (effectively P12) and it all worked as it should do.

**Comment by hartez** [comment]
@jsuarezruiz Can you verify that this is working against main, and close the issue if it is?

**Comment by shimingsg** [comment]
Not reproducible with windows.
