### ISSUE TITLE
[Android] Frame content have a wrong size 

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4076]
### Description

Frame content have a wrong size:
![image](https://user-images.githubusercontent.com/6755973/149110875-e23dccba-2da3-4b66-9639-47d890514b83.png)

This is the expected behavior (in Xamarin.Forms):
![image](https://user-images.githubusercontent.com/6755973/149108465-0030bdd5-332d-4239-8bce-902d3b774196.png)

### Steps to Reproduce

1. Download: [AbsoluteLayoutDemos.zip](https://github.com/dotnet/maui/files/7853421/AbsoluteLayoutDemos.zip)
2. Navigate to the first sample.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by wenwen60** [comment]
Duplicate with #4078.
