### ISSUE TITLE
[Android] Frame using IsClippedToBounds not rendering

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4077]
### Description

Frame using IsClippedToBounds not rendering:
![image](https://user-images.githubusercontent.com/6755973/149110875-e23dccba-2da3-4b66-9639-47d890514b83.png)

This is the expected behavior (in Xamarin.Forms):
![image](https://user-images.githubusercontent.com/6755973/149108465-0030bdd5-332d-4239-8bce-902d3b774196.png)

### Steps to Reproduce

1. Download: [AbsoluteLayoutDemos.zip](https://github.com/dotnet/maui/files/7853421/AbsoluteLayoutDemos.zip)
2. Navigate to the first sample.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by zhouwangyang** [comment]
could you try on the latest build to repro this issue, the first sample you provide is no response after click.

**Comment by zhouwangyang** [comment]
@jsuarezruiz could not find CardView XML demo in the repro code, could you confirm with it. 
![image](https://user-images.githubusercontent.com/39871640/153372361-d129f1de-4200-4461-98c3-190f9c66cdbf.png)

**Comment by davidortinau** [comment]
No long able to repro. Closing as fixed.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/41873/165780638-1e3c74c7-a850-404c-9b3e-cfe9bbc4def5.png">
