### ISSUE TITLE
[Windows] Wrong Frame content sizes 

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4078]
### Description

Wrong Frame content sizes:
![image](https://user-images.githubusercontent.com/6755973/149114509-5ec2180c-0837-46a4-b3f7-366a93860712.png)

### Steps to Reproduce

1. Download: [AbsoluteLayoutDemos.zip](https://github.com/dotnet/maui/files/7853421/AbsoluteLayoutDemos.zip)
2. Navigate to the first sample.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by wenwen60** [comment]
No repro on windows with VS2022 17.2.0 Preview 2.0 [32215.517.main], using above project.
