### ISSUE TITLE
[Android] Wrong size using a FlexLayout inside a ScrollView

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4079]
### Description

Wrong size using a FlexLayout inside a ScrollView:
![image](https://user-images.githubusercontent.com/6755973/149120955-74351223-1915-45eb-901d-ab6d96f5d417.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/6755973/149121148-2e87eccf-81ee-4a61-8e42-0a5a93a482ff.png)

### Steps to Reproduce

1. Download [FlexLayoutDemos.zip](https://github.com/dotnet/maui/files/7853774/FlexLayoutDemos.zip)
2. Launch the App on Android and navigate to the sample "Catalog Items"

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by Redth** [comment]
Still repros on main as of now.

**Comment by VincentBu** [comment]
still occurs on vs main build(32507.29.main)

**Comment by samhouts** [comment]
No longer repros on 6.0.300-rc.4.5742.
