### ISSUE TITLE
[Windows] Crash with FlexLayout inside ScrollView

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4081]
### Description

Crash with FlexLayout inside ScrollView:

`A cycle occurred while laying out the GUI.`

### Steps to Reproduce

1. Download [FlexLayoutDemos.zip](https://github.com/dotnet/maui/files/7853774/FlexLayoutDemos.zip)
2. Launch the App on Android and navigate to the sample "Catalog Items"

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by shimingsg** [comment]
Verified repro with windows and the above project.

**Comment by jsuarezruiz** [comment]
Investigating this, there is a loop in the `ArrangeChildren` method in the `FlexLayoutManager` class.

**Comment by VincentBu** [comment]
still repro on Windows with vs main build(32507.29.main)
