### ISSUE TITLE
[Android] FlyoutPage not rendering 

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4083]
### Description

FlyoutPage not rendering 
![image](https://user-images.githubusercontent.com/6755973/149129673-ac42b8ee-a7ab-42fb-9af3-609d962698b9.png)

### Steps to Reproduce

1. Download [ControlGallery.zip](https://github.com/dotnet/maui/files/7854034/ControlGallery.zip)
2. Try to navigate to the "FlyoutPage sample".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment]
Verified Repro with Android 11 pixel_5 API 30. 
repro sample:
[4083.zip](https://github.com/dotnet/maui/files/8130200/4083.zip)

**Comment by PureWeen** [comment]
This seems fine now
