### ISSUE TITLE
[Android] CarouselPage not working correctly

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4086]
### Description

CarouselPage not working correctly, is not rendering. Have a big amount of binding errors:

```
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'G' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'B' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Hue' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Saturation' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Luminosity' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
```

The same code works correctly on Xamarin.Forms.

### Steps to Reproduce

1. Download [ControlGallery.zip](https://github.com/dotnet/maui/files/7854034/ControlGallery.zip)
2. Try to navigate to the "CarouselPage sample".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/pull/4204

**Comment by YiannisBourkelis** [comment]
@PureWeen Can you please keep this issue open? We need a working CarouselPage control so that we can migrate our Xamarin.Forms projects using a CarouselPage to MAUI. If there is no such control in MAUI how can we migrate? I am sure that other fellow developers will run into the same issue in their projects. I have posted the related issue about this matter here: https://github.com/dotnet/maui/issues/4606
