### ISSUE TITLE
[Windows] Wrong CarouselPage behavior scrolling items

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4087]
### Description

Wrong CarouselPage behavior scrolling items. Everything works as expected:

![image](https://user-images.githubusercontent.com/6755973/149132173-39c1806d-d243-4714-b5b5-154c98868580.png)

Until regret to a visited item.

![image](https://user-images.githubusercontent.com/6755973/149132240-48f6fc8b-a2a1-40d9-ae17-d3ef5c4bdda0.png)

Start getting binding errors:

```
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Hue' property not found on '[Color: Red=0, Green=0, Blue=1, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Saturation' property not found on '[Color: Red=0, Green=0, Blue=1, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Luminosity' property not found on '[Color: Red=0, Green=0, Blue=1, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'R' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'G' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'B' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Hue' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Saturation' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Luminosity' property not found on '[Color: Red=0.5019608, Green=0, Blue=0.5019608, Alpha=1]', target property: 'Microsoft.Maui.Controls.Label.Text'
```

### Steps to Reproduce

1. Download [ControlGallery.zip](https://github.com/dotnet/maui/files/7854034/ControlGallery.zip)
2. Try to navigate to the "CarouselPage sample".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by wenwen60** [comment]
The error list can show, but CarouselPage not rendering. Related #4086.

**Comment by YiannisBourkelis** [comment]
@PureWeen Can you please keep this issue open? We need a working CarouselPage control so that we can migrate our Xamarin.Forms projects using a CarouselPage to MAUI. If there is no such control in MAUI how can we migrate? I am sure that other fellow developers will run into the same issue in their projects. I have posted the related issue about this matter here: https://github.com/dotnet/maui/issues/4606
