### ISSUE TITLE
[Windows] Wrong initial cursor position in Editor

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4089]
### Description

Start in the middle of the Editor's height:
![image](https://user-images.githubusercontent.com/6755973/149133007-ee2a79a8-4154-4690-b1ca-e93d6779cd2b.png)

### Steps to Reproduce

1. Download [ControlGallery.zip](https://github.com/dotnet/maui/files/7854034/ControlGallery.zip)
2. Try to navigate to the "Editor sample".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EbtLj_gI0OlNnMYf5g-d-aUBICSfAGKjNMv67revyvli0g?e=cZrvDZ

**Comment by bricelam** [comment]
Is this by design? The cross-platform default is currently `Center`:

https://github.com/dotnet/maui/blob/f3fbfe06bd57e60d35612e6417678d79c5baa6cf/src/Controls/src/Core/TextAlignmentElement.cs#L9-L10

You can change it to `Start` if you wan it top-aligned.

```xml
<Editor 
    VerticalTextAlignment="Start"
    Text="This should be on the top"
    HeightRequest="100"/>
```

**Comment by bricelam** [comment]
Hmm, looks like Android does indeed default to the top. Maybe the line above should be changed to Start?
