### ISSUE TITLE
[Windows] Weird ListView behavior scrolling

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4091]
### Description

Weird ListView behavior scrolling and recycling cells.

![listview-win-issue](https://user-images.githubusercontent.com/6755973/149134882-d567fb67-a446-4c25-a2ee-5ce7b3a9edf3.gif)

### Steps to Reproduce

1. Download [ControlGallery.zip](https://github.com/dotnet/maui/files/7854034/ControlGallery.zip)
2. Try to navigate to the "ListView sample".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by PureWeen** [comment]
This should be fixed by this PR
https://github.com/dotnet/maui/issues/4091
