### ISSUE TITLE
[Windows] Wrong Slider default track color

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4093]
### Description

Wrong Slider default track color
![image](https://user-images.githubusercontent.com/6755973/149135406-de168e3d-31b0-4e80-aba6-fa4518b9ecaa.png)

### Steps to Reproduce

1. Download [ControlGallery.zip](https://github.com/dotnet/maui/files/7854034/ControlGallery.zip)
2. Try to navigate to the "Slider sample".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by shimingsg** [comment]
Verified Repro with Windows,  Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EfSIkUEY7hJBmZv2uF2cbrEB3PZbIoArIRy00eafaF_HCQ?e=nlcNOP
