### ISSUE TITLE
[Android] Crash using a CollectionView with a RefreshView

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4109]
### Description

Crash using a CollectionView with a RefreshView

`[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.`

### Steps to Reproduce

1. Download [CollectionViewDemos.zip](https://github.com/dotnet/maui/files/7861241/CollectionViewDemos.zip)
2. Launch the App and navigate to the sample "Pull to Refresh using RefreshView".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by davidortinau** [comment]
Closing the crash issues. Images were addressed elsewhere.
