### ISSUE TITLE
[Android] CollectionView ScrollTo methods not working

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4110]
### Description

CollectionView ScrollTo methods not working. Could be related with https://github.com/dotnet/maui/issues/4107

### Steps to Reproduce

1. Download [CollectionViewDemos.zip](https://github.com/dotnet/maui/files/7861241/CollectionViewDemos.zip)
2. Launch the App and navigate to the sample "Scroll by index".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by rmarinho** [comment]
duplicate of #2891
