### ISSUE TITLE
[Windows] Horizontal CollectionView using a GridLayout not rendering

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4111]
### Description

Horizontal CollectionView using a GridLayout not rendering. If resize the Window get a crash:

`A cycle occurred while laying out the GUI.`

### Steps to Reproduce

1. Download [CollectionViewDemos.zip](https://github.com/dotnet/maui/files/7861241/CollectionViewDemos.zip)
2. Launch the App and navigate to the sample "Horizontal list Text".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by shimingsg** [comment]
Not reproducible with windows.
