### ISSUE TITLE
[Windows] Wrong CollectionView item size using MeasureFirstItem

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4113]
### Description

Wrong CollectionView item size using MeasureFirstItem
![image](https://user-images.githubusercontent.com/6755973/149300253-e1891015-662a-44e0-a9a2-f77fb0a19d3e.png)

### Steps to Reproduce

1. Download [CollectionViewDemos.zip](https://github.com/dotnet/maui/files/7861241/CollectionViewDemos.zip)
2. Launch the App and navigate to the sample "Vertical list (variable size items)".

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by shimingsg** [comment]
Verified repro with windows and the above project.

**Comment by Redth** [comment]
This seems ok in main:
![image](https://user-images.githubusercontent.com/271950/165994657-019c61de-f42f-47b7-a3eb-4f5004a98ded.png)
