### ISSUE TITLE
[Windows] Crash using a CollectionView inside a RefreshView

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4114]
### Description

Crash using a CollectionView inside a RefreshView
`Source object type is not a projected type and does not inherit from a projected type. (Parameter 'value')`

### Steps to Reproduce

1. Download [CollectionViewDemos.zip](https://github.com/dotnet/maui/files/7861241/CollectionViewDemos.zip)
2. Launch the App and navigate to any RefreshView sample.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by shimingsg** [comment]
Verified repro with windows and the above project.

**Comment by mattleibow** [comment]
No longer crashes on RC 3. Not sure who fixed the underlying issue, but whoever it is... 🤗
