### ISSUE TITLE
[Windows] CollectionView ItemsUpdatingScrollMode property not working

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4116]
### Description

CollectionView ItemsUpdatingScrollMode property not working
![cv-win-issue01](https://user-images.githubusercontent.com/6755973/149303673-81419107-9fdf-4e0e-9e84-8a4743916b6a.gif)

### Steps to Reproduce

1. Download [CollectionViewDemos.zip](https://github.com/dotnet/maui/files/7861241/CollectionViewDemos.zip)
2. Launch the App and navigate to the sample "Scroll mode when adding items".

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by shimingsg** [comment]
Verified repro with windows and the above project.

**Comment by rmarinho** [comment]
Seems this wasn't implemented in Xamarin.Forms either

**Comment by samuelradford** [comment]
This is still not working in the most recent release.

**Comment by andersonvieiragomeslopes** [comment]
For those who are dragging this problem from xamarin and now dotnetmaui, I made a platform control to solve the problem.

**MauiProgram.cs**

```
.ConfigureMauiHandlers(handlers =>
                {
#if WINDOWS
                    handlers.AddHandler<CollectionView, Handlers.CollectionViewHandler>();        
#endif                 
                })
```

**And now:**

```
public class CollectionViewHandler : Microsoft.Maui.Controls.Handlers.Items.CollectionViewHandler
    {
        private ListViewBase listViewBase;
        protected override void ConnectHandler(ListViewBase platformView)
        {
            listViewBase = platformView;
            listViewBase.Items.VectorChanged += Items_VectorChanged;
            base.ConnectHandler(listViewBase);
        }

        private void Items_VectorChanged(Windows.Foundation.Collections.IObservableVector<object> sender, Windows.Foundation.Collections.IVectorChangedEventArgs @event)
        {
            if(sender is Microsoft.UI.Xaml.Controls.ItemCollection item)
            {
                if(item!= null && item.Count > 5)
                    listViewBase.ScrollIntoView(item.LastOrDefault());

            }
        }
    }
```

Hey @jerry08 I think this makes sense your workaround collection for maui.

**Comment by jerry08** [comment]
@andersonvieiragomeslopes  Thanks! I haven't tested that on windows platform but I guess I'll just add that workaround to my project.

**Comment by davepruitt** [comment]
This is also not working for me on Android. I am using Android 13 on a Samsung Galaxy Tab A7 Lite.

**Comment by jinxinjuan** [comment]
Repro on version 17.6.0 Preview 4.0 on Android API 33 with the project [CollectionViewDemos.zip](https://github.com/dotnet/maui/files/7861241/CollectionViewDemos.zip)

**Comment by Raffro** [comment]
also not working for me on android

**Comment by alexsmi-noveo** [comment]
Also not working for me on Android emulator and Samsung S22. Total ignorance

**Comment by xx7Ahmed7xx** [comment]
Can anyone tell me what is the fix or how to use it? because I don't get it
