### ISSUE TITLE
[Android] SwipeItemView using a Frame is not rendering correctly

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4118]
### Description

SwipeItemView using a Frame is not rendering correctly. 
![image](https://user-images.githubusercontent.com/6755973/149321116-7b4fc9e4-bdcf-448e-9d73-96ad67de8bbd.png)

### Steps to Reproduce

Can use Core Gallery to test it. Navigate to the SwipeView Gallery and select any SwipeItemView sample.

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by shimingsg** [comment]
Not reproducible with Android 11.
