### ISSUE TITLE
Port Picker.VerticalTextAlignment to Handler

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#412]
Please read the [Handler Property PR Guidelines](https://github.com/dotnet/maui/wiki/Handler-Property-PR-Guidelines) for instructions on how to create and submit a PR for this issue.

Thanks for your help!

**Comment by AlexanderGipp** [comment]
I would love to start helping you guys, i am just not too sure if i am good enough to actually contribute to a project like this.
How hard is this issue and is this doable for someone who never contributed to maui?

Thanks

**Comment by AmrAlSayed0** [comment]
@AlexanderGipp It is good that you want to contribute but this issue already has a PR https://github.com/dotnet/maui/pull/1194 submitted for it.
