### ISSUE TITLE
[Android] SwipeItem with gesture recognizer is not working correctly

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4122]
### Description

SwipeItem with gesture recognizer is not working correctly. 

### Steps to Reproduce

Launch .NET MAUI Gallery and navigate to the SwipeView Gallery. Select the SwipeItem with gesture recognizer  sample. Notice that cannot swipe correctly to open it.

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by zhouwangyang** [comment]
could you provide detailed reproduced steps or some reproduced video is helpful.

**Comment by kristinx0211** [comment]
@jsuarezruiz Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
