### ISSUE TITLE
[iOS] MyRecipes and RecipeSearch collections have fixed dimensions 

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#4124]
### Description

MyRecipes and RecipeSearch collections have fixed dimensions. They don't fit the full screen size of iPhones and iPads equally well.

Currently, the dimensions of the views are based on fixed pixel values that render better on iPhone devices.
These views will later be swiped our for more stable controls (CollectionView, CarouselView), at which point this issue will also be addressed.

### Steps to Reproduce

1. Run recipes app on iPad (emulator or device)
2. Navigate to search results page (click on a button OR search something)
3. Note the UI
4. Switch to MyRecipes tab
5. Note the UI
6. Run on iPhone
7. Notice the difference between how it looks on iPad vs. iPhone

| SearchResults page | MyRecipes page |
|---------------------|------------------|
| ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-01-13 at 10 06 18](https://user-images.githubusercontent.com/21988533/149358077-4cc6e62f-8c0d-415e-941e-1873e0cd37a7.png) | ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-01-13 at 10 06 47](https://user-images.githubusercontent.com/21988533/149358075-6e180dbd-7698-4c9b-9024-adb833046008.png) |

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All

**Comment by shimingsg** [comment]
@rachelkang could you share your repro projects.
