### ISSUE TITLE
[Windows] Device.Display.MainDissplayInfo throws COMException

### ISSUE THREAD

**Issue by PedroCigaw** [dotnet/maui#4126]
### Description

Trying to get the DeviceDisplay.MainDisplayInfo throws a ComException

`
System.Runtime.InteropServices.COMException
  HResult=0x80070490
  Message=Element not found. (0x80070490)
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.Graphics.Display.IDisplayInformationStaticsMethods.GetForCurrentView(IObjectReference _obj)
   at Windows.Graphics.Display.DisplayInformation.GetForCurrentView()
   at Microsoft.Maui.Essentials.DeviceDisplayImplementation.GetMainDisplayInfo(DisplayInformation di)
   at Microsoft.Maui.Essentials.DeviceDisplayImplementation.GetMainDisplayInfo()
   at Microsoft.Maui.Essentials.DeviceDisplay.get_MainDisplayInfo()
`

### Steps to Reproduce

1. Create Maui Project
2. In Windows Platform call DeviceDisplay.MainDisplayInfo

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Window SDK 10.0.19041.0

**Comment by PureWeen** [comment]
This should be fixed in p12

**Comment by PedroCigaw** [comment]
Tried in P12 now I get 

`
'DeviceDisplay.MainDisplayInfo' threw an exception of type 'System.ArgumentException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2147024809
    HelpLink: null
    InnerException: null
    Message: "Source object type is not a projected type and does not inherit from a projected type. (Parameter 'value')"
    ParamName: "value"
    Source: "WinRT.Runtime"
    StackTrace: "   at WinRT.CastExtensions.GetRefForObject(Object value)\r\n   at WinRT.CastExtensions.As[TInterface](Object value)\r\n   at WinRT.Interop.WindowNative.GetWindowHandle(Object target)\r\n   at Microsoft.Maui.Essentials.Platform.get_CurrentWindowHandle()\r\n   at Microsoft.Maui.Essentials.Platform.get_CurrentWindowId()\r\n   at Microsoft.Maui.Essentials.Platform.get_CurrentAppWindow()\r\n   at Microsoft.Maui.Essentials.DeviceDisplayImplementation.GetMainDisplayInfo()\r\n   at Microsoft.Maui.Essentials.DeviceDisplay.get_MainDisplayInfo()"
    TargetSite: {WinRT.IObjectReference GetRefForObject(System.Object)}
`
