### ISSUE TITLE
Port Picker.HorizontalTextAlignment to Handler

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#413]
Please read the [Handler Property PR Guidelines](https://github.com/dotnet/maui/wiki/Handler-Property-PR-Guidelines) for instructions on how to create and submit a PR for this issue.

Thanks for your help!

**Comment by pictos** [comment]
Can I work on this one?

**Comment by jsuarezruiz** [comment]
Merged, thanks for the help Pedro Jesus!
