### ISSUE TITLE
Add a gitignore file to the Maui template in VS 2022

### ISSUE THREAD

**Issue by MisterJimson** [dotnet/maui#4131]
### Description

When users create projects, they often want to use git to version control them. Manually setting up a gitignore is an extra step, and folks working on maui know what should and shouldn't be ignored. This is something every developer new to maui will have to do unless a pre made gitignore is added to the template.

### Public API Changes

None

### Intended Use-Case

Saving my project in git

**Comment by Eilon** [comment]
As of right now, none of the default project templates in VS do this. Perhaps this could be a nice general VS feature, but not something we would do specifically in .NET MAUI.
