### ISSUE TITLE
ContentView: Setting the ControlTemplate dynamically causes the control to disappear

### ISSUE THREAD

**Issue by vanka78bg** [dotnet/maui#4135]
### Description

I have noticed that `ContentView` does not support setting the `ControlTemplate` dynamically at runtime. When the `ControlTemplate` is set initially in XAML or in the `Page`'s constructor, everything works as expected. When the `ControlTemplate` is set at a later stage, the `ContentView` just disappears. Some preliminary investigation leads me to conclude this has something to do with the `ContentView`s `Handler`. If the `Handler` is not created yet, setting the `ControlTemplate` would work as expected. If the `Handler` is already created, setting the `ControlTemplate` would make the control disappear.

While debugging, I have also noticed the `ContentView` inherits from the legacy `Layout` class. Setting the `ControlTemplate` at runtime would invalidate the measure, but calling `IView.Measure` after that on the `ContentView` would always return a zero `Size`. This might be some incompatibility between the old and the new layout systems, but I have not investigated that further.

### Steps to Reproduce

1. Run the attached sample project
    - The first `ContentView` has a `ControlTemplate` set in XAML
    - The second `ContentView` has a custom `Style` specifying a `ControlTemplate` in XAML
    - The third and fourth `ContentView`s do not have a `ControlTemplate` specified initially
2. Click the `Set Custom Template` button
    - This sets a `ControlTemplate` to the third `ContentView`. Notice the `ContentView` disappearing.
3. Click the `Set Custom Style` button
    - This sets a `Style` specifying a `ControlTemplate` to the fourth `ContentView`. Notice the `ContentView` disappearing.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

I have not tested on various versions of the different platforms.

### Did you find any workaround?

The only workaround I have found so far is to replace the `ContentView` with a new instance, that has the desired `ControlTemplate` set initially. This is rather inconvenient, as changing the `Style` of a `ContentView` to a new one, which might potentially update the `ControlTemplate`, would require re-creating the entire `ContentView` every time, to avoid the bug.

### Relevant log output

No log output available at this time.

### Sample project

[TestApp.zip](https://github.com/dotnet/maui/files/7869236/TestApp.zip)

**Comment by Amir-Care** [comment]
Repro on VS 17.2.0 Preview 2.0 [32208.484.main]

**Comment by mfe-** [comment]
I'm having the same issue on the Windows Platform. Can't change the ControlTemplate during runtime.

                    

Setting it from Codebehind also doesn't change the appearance of the control. 
I'm using Visual Studio 17.3.0 Preview 1.0
