### ISSUE TITLE
Wrong results searching .NET MAUI project templates

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4136]
### Description

Wrong results searching .NET MAUI project templates. 
![template-filter-issue](https://user-images.githubusercontent.com/6755973/149504713-83817ca6-cf2b-4836-b420-45058b9d1dff.gif)

### Steps to Reproduce

1. Use VS 2022 17.1 P3 with latest .NET MAUI Preview.
2. Filter by "MAUI" project templates.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

VS 2022 17.1 P3

**Comment by Amir-Care** [comment]
Not repro on  VS 17.2.0 Preview 2.0 [32208.484.main]
