### ISSUE TITLE
XAML Intellisense cannot resolve working stuff like in Xamarin.Forms

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4137]
### Description

XAML Intellisense cannot resolve working stuff in Xamarin.Forms

The behavior with .NET MAUI:
![xaml-intellisense-maui-issue](https://user-images.githubusercontent.com/6755973/149505783-f6927088-98f6-4466-b6f6-807b2930fafe.gif)

The behavior with Xamarin.Forms:
![xaml-intellisense-forms](https://user-images.githubusercontent.com/6755973/149505788-67f374f9-5c4b-4dbf-8f4e-4398f97bd8f2.gif)

### Steps to Reproduce

1. Use VS 2022 17.1 P3 with latest .NET MAUI Preview.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

VS 2022 17.1 P3

**Comment by Jon2G** [comment]
![image](https://user-images.githubusercontent.com/24820069/150667116-26aa0d07-a01e-4f9f-8601-8523e6fa5b9d.png)
Intellisense is not working at all in xaml files for me.
VS 17.1.0 Preview 3.0

**Comment by YuqinSong** [comment]
Verified Repro. But my VS2022 XAML Intellisense cannot resolve working stuff in Xamarin.Forms either. Repro project is available:
[#4137.zip](https://github.com/dotnet/maui/files/8150855/4137.zip)

**Comment by Redth** [comment]
I believe this is fixed in recent preview.
