### ISSUE TITLE
VisualStateManager: Changing the Style dynamically messes up the styling of the visual states

### ISSUE THREAD

**Issue by vanka78bg** [dotnet/maui#4139]
### Description

When changing a `Style` dynamically at runtime and the new `Style` defines some visual states this causes some problems:
1. When the control is in a non-default visual state, the styling options for that visual state are not applied.
2. When the control changes its visual state to another one, the styling options from a previous `Style` might get applied.

### Steps to Reproduce

1. Run the attached sample project
    - The sample contains some `Label`s with `TapGestureRecognizer`s. Tapping on a `Label` toggles between `Normal` and `Selected` visual states.
    - The sample defines two custom `Style`s with different `TextColor`s for the `Normal` and `Selected` visual states. The first `Style` alters between `Black` and `Red` `TextColor`s, the second style alters between `Black` and `Cyan` `TextColor`s for the visual states.
2. Tap on a `Label` to toggle between the `Normal` and `Selected` visual states
    - The `Label` toggles its `TextColor` between `Black` and `Red` as expected.
3. Tap the `Set Custom Style 2` button to set the second `Style`
    - The selected `Label`s do not change their `TextColor`s and remain `Red`.
4. Tap on a `Label` to toggle between the `Normal` and `Selected` visual states
    - If the initial state of the `Label` is `Normal`, then it toggles between `Black` and `Cyan` `TextColor`s as expected.
    - If the initial state of the `Label` is `Selected`, then it toggles between `Red` and `Cyan` `TextColor`s, which is unexpected.
5. Tap the `Set Custom Style 1` button to restore the first `Style`
6. Continue playing around with the `Label`s to get even more messed up states

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

I have not tested on various versions of the different platforms.

### Did you find any workaround?

The only workaround I have found is to reset the visual state of the control before changing the `Style` and then re-apply the visual state manually. Please, keep in mind that currently we do not have an API to get the visual state of the control programmatically and the `ChangeVisualState` method is declared as `protected`, so it is not accessible from external code. The only option is to inherit from the original control and override the `OnPropertyChanging` and `OnPropertyChanged` methods:

```csharp
protected override void OnPropertyChanging([CallerMemberName] string propertyName = null)
{
    base.OnPropertyChanging(propertyName);

    if (propertyName == nameof(Style))
    {
        VisualStateManager.GoToState(this, VisualStateManager.CommonStates.Normal);
    }
}

protected override void OnPropertyChanged([CallerMemberName] string propertyName = null)
{
    base.OnPropertyChanged(propertyName);

    if (propertyName == nameof(Style))
    {
        this.ChangeVisualState();
    }
}
```

### Relevant log output

```shell
No log output available at this time.
```

### Sample project

[TestApp.zip](https://github.com/dotnet/maui/files/7870054/TestApp.zip)

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by StephaneDelcroix** [comment]
replacing the VSGL (https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/VisualStateManager.cs#L38) triggers `ChangeVisualState` (https://github.com/dotnet/maui/blob/b5bf49ff7b0759dd6dc3759ff69dda6d932bbb3e/src/Controls/src/Core/VisualElement.cs#L1074-L1082) who resets the State to Disabled, Focused, or Normal

**Comment by StephaneDelcroix** [comment]
I don't see a clean way of carrying over a state when a VSGL is replaced, as a VSGL can have multiple VSG, and each group could have a different state, and knowing which one to reapply to which could only be done by guessing, and guessing wrong 50% of the time.

What would make sense, when changing a style unapply a VSGL, is to get rid of the value set by the VSM, as the current state is gone, which is actually what you're forcing in your workaround

**Comment by StephaneDelcroix** [comment]
@vanka78bg you can workaround, cleanly, this issue by adding a setter for the Normal State. This would be the go-to solution if you wanted to have different. The state wouldn't be maintained (see earlier comment), but you'd get back to a consistent Normal State.

The default setter in the Style has actually a lower priority than the one from the VSM (see #6856) and thus isn't applied.

Oh, and the VSGL isn't unapplied on remove, because we clone it, and it looks it has changed since it was set, so it's not unapplied (#6857)
