### ISSUE TITLE
Custom theme ResourceDictionary not working

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/maui#4143]
I've copied code that largly the same as i have in a xamarin.forms app. But it isn't working.

When the app loads, in the `app.xaml.cs` `OnStart` method it triggers and app theme initialiser method. That method checks what theme the app should be set as _(light/ dark or OS)_. Once it knows what it needs to be set to it then set the `Application.Current.Resources` with the right themes ResourceDictionary. But nothing happens - 
![image](https://user-images.githubusercontent.com/6544051/149569108-2f9ea7a0-2e87-4e3e-9538-cde4c7bec06d.png)

It should be changing the background colour - 
![image](https://user-images.githubusercontent.com/6544051/149569285-1070b53d-5b40-4c2e-b310-c6a2c9e77e16.png)

Both light and dark theme has different colours - 
![image](https://user-images.githubusercontent.com/6544051/149569397-fd37c02a-4c4b-445a-a801-9b6f345ba908.png)

### Steps to Reproduce

repo -
[repo.zip](https://github.com/dotnet/maui/files/7872565/repo.zip)
 

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

android 11

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by Redth** [comment]
Could you please update the repro to be compatible with the latest RC1 release of MAUI?

**Comment by mattleibow** [comment]
I was looking at this already and fixed up the sample when testing #6372.

The repo is actually not working because many of the types do not call `InitializeComponent()` in the ctor, however, after fixing that, the real issue is that the pages are using the obsolete (and broken until now) BackgroundColor instead of Background.
