### ISSUE TITLE
Application with BlazorWebView doesn't work when installed in Program Files folder

### ISSUE THREAD

**Issue by emiliosanchis** [dotnet/maui#4151]
### Description

I have tried the sample app from the repository https://github.com/dotnet/maui/tree/main/src/BlazorWebView/samples/BlazorWinFormsApp
It works correctly in debug and when I install it in a normal directory, for example, c:\test, but when I install it in programfiles it gives an access denied error. 

Following the thread at https://github.com/MicrosoftEdge/WebView2Feedback/issues/297
I have tried to configure the UserDataFolder but then it gives the following error both in debug and installed

_"WebView2 was already initialized with a different CoreWebView2Environment. Check to see if the Source property was already set or EnsureCoreWebView2Async was previously called with different values"_

### Steps to Reproduce

1. Clone https://github.com/dotnet/maui/tree/main/src/BlazorWebView/samples/BlazorWinFormsApp
2. Install in Program Files folder
3. Access Denied error when running application
4. Add

 			CoreWebView2Environment env;
			CoreWebView2CreationProperties wv = new();
			wv.UserDataFolder = Path.GetTempPath() + "BlazorWebViewUserData";
			env = CoreWebView2Environment.CreateAsync(userDataFolder: wv.UserDataFolder).Result;	
			blazorWebView1.WebView.EnsureCoreWebView2Async(env);
before:

			blazorWebView1.HostPage = @"wwwroot\index.html";
			blazorWebView1.Services = services1.BuildServiceProvider();
			blazorWebView1.RootComponents.Add<Main>("#app");
			blazorWebView1.RootComponents.RegisterForJavaScript<MyDynamicComponent>("my-dynamic-root-component");

5. Error: WebView2 was already initialized with a different CoreWebView2Environment. Check to see if the Source property was already set or EnsureCoreWebView2Async was previously called with different values

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10

**Comment by Eilon** [comment]
From Mobile Blazor Bindings here was the bug we had: https://github.com/dotnet/MobileBlazorBindings/issues/196

And here's the fix: https://github.com/dotnet/MobileBlazorBindings/pull/246

I suggest we do something similar in Blazor Hybrid.

**Comment by VincentBu** [comment]
Well, I failed in publish step since access denied. Here is the error message:
```
MSB3021	Unable to copy file "C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.web\6.0.1\lib\net6.0\Microsoft.AspNetCore.Components.Web.dll" to "C:\Program Files\TestApp\Release\net6.0-windows\Microsoft.AspNetCore.Components.Web.dll". Access to the path 'C:\Program Files\TestApp\Release\net6.0-windows' is denied.
```

**Comment by Eilon** [comment]
@VincentBu that seems like a different issue.
