### ISSUE TITLE
SwipeView isn't working

### ISSUE THREAD

**Issue by RobertoGFilho** [dotnet/maui#4154]
### Description

    <CollectionView ItemsSource="{Binding Items}"
                    SelectionMode="Single"
                    SelectedItem="{Binding SelectedItem, Mode=TwoWay}"
                    SelectionChangedCommand="{Binding SelectCommand}"
                    Margin="0,12">
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <SwipeView x:DataType="business:ContactGroupBusiness">
                    <SwipeView.RightItems>
                        <SwipeItem IconImageSource="{StaticResource Remove}"
                                       Invoked="OnRemove"/>
                    </SwipeView.RightItems>

                    
                    <Frame Margin="9,3">
                        <Label Text="{Binding Model.Name, Mode=OneWay}"
                                       Style="{StaticResource TitleStyle}"/>
                    </Frame>
                </SwipeView>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>

### Steps to Reproduce

1. Create a new Content Page;
2. Add Collection View with Swipe View

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by PureWeen** [comment]
should be fixed in P12
https://github.com/dotnet/maui/issues/4154
