### ISSUE TITLE
[Android] HeightRequest, WidthRequest, MinimumWidthRequest and MinimumHeightRequest are not respected by Contentview

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#4164]
### Description

When HeightRequest, WidthRequest, MinimumWidthRequest or MinimumHeightRequest are directly set to a ContentView the control does not respect them. Please, check the attached images that demonstrate how the control looks in iOS and how in Android when the above properties are set:

### iOS
![Simulator Screen Shot - iPhone 8 - 2022-01-17 at 15 33 16](https://user-images.githubusercontent.com/9336157/149790977-257aab7e-25ef-4d72-aae4-d670a9297619.png)

### **Android**
<img width="416" alt="Screenshot 2022-01-17 at 15 35 23" src="https://user-images.githubusercontent.com/9336157/149790928-ac9f9d64-cf86-4085-a14b-4f0c85f2654a.png">

[HelloMaui.zip](https://github.com/dotnet/maui/files/7882637/HelloMaui.zip)
 

### Steps to Reproduce

1. Open the attached project and run it.
2. Notice how the ContentView look on Android when HeightRequest, WidthRequest, MinimumWidthRequest and MinimumHeightRequest are set.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8

**Comment by ScottArbeit** [comment]
I'm seeing the same behavior creating a Windows app using MAUI. Just wanted to +1.

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.
