### ISSUE TITLE
[Windows] Wrong default DatePicker and TimePicker TextColor

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4165]
### Description

Wrong default DatePicker and TimePicker TextColor
![timepicker-textcolor-issue](https://user-images.githubusercontent.com/6755973/149820511-6d902609-8fd4-468c-9e36-a467ad27333c.gif)

### Steps to Reproduce

1. Download [DataBindingDemos.zip](https://github.com/dotnet/maui/files/7883977/DataBindingDemos.zip)
2. Navigate to the "string format" sample

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by v-xiaofchen** [comment]
Verified repro with windows and the above project.
