### ISSUE TITLE
[Windows] Wrong Grid columns and rows Auto sizing

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4167]
### Description

Wrong Grid columns and rows Auto sizing

![image](https://user-images.githubusercontent.com/6755973/149822323-a63e262a-28a4-4e34-a9de-6a11b342006f.png)

### Steps to Reproduce

1. Download [XamlSamples.zip](https://github.com/dotnet/maui/files/7884066/XamlSamples.zip)
2. Launch the App on Windows and navigate to the "Keypad sample"
 

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by davidbritch** [comment]
Just an FYI that I've re-written the sample so this demo works. The problem seemed to be the internal Grid for the top row. I get that it renders as is in Xamarin.Forms. After a quick re-write it now renders in MAUI.

**Comment by YuqinSong** [comment]
Verified repro with Windows and the above project.

**Comment by davidortinau** [comment]
Provided sample renders now, and as Dave mentioned he rewrote the sample as well. Closing

<img width="729" alt="image" src="https://user-images.githubusercontent.com/41873/165837046-3b36ae0a-3534-44f1-9517-d2b29635c885.png">
