### ISSUE TITLE
[Windows] Crash loading dynamic XAML content

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4168]
### Description

Loading dynamic XAML content using the LoadFromXaml method and navigating:

A cycle occurred while laying out the GUI.

### Steps to Reproduce

1. Download [LoadRuntimeXAML.zip](https://github.com/dotnet/maui/files/7884139/LoadRuntimeXAML.zip)
2. Launch the sample on Windows and tap the Button to load dynamic content.
3. Tap the new Button. Crash.
 

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

**Comment by Amir-Care** [comment]
Repro on VS 17.2.0 Preview 2.0 [32208.484.main]

**Comment by VSadov** [comment]
I was able to reproduce it. 
- click [Load XAML] button   ->   [Navigate] button appears
- click [Navigate] button       ->   unhandled exception crash

**Comment by VSadov** [comment]
Nesting like `FlexLayout/Frame/FlexLayout/Stuff` causes a problem

```
		<FlexLayout>
			<Frame WidthRequest=""300"" HeightRequest=""480"">
				<FlexLayout Direction=""Column"">
                                        labels. . . buttons . . . images
```

Nestings like   `FlexLayout/Frame/Stuff`  or `FlexLayout/FlexLayout/Stuff`   are ok

**Comment by jsuarezruiz** [comment]
Investigating this, there is a loop in the `ArrangeChildren` method in the `FlexLayoutManager` class.

**Comment by jsuarezruiz** [comment]
I am going to close this issue because is the same has https://github.com/dotnet/maui/issues/3826
