### ISSUE TITLE
Blazor Maui .Net 6 /Request Again Permission (Deny Mode) In Blazor Page 

### ISSUE THREAD

**Issue by masoodafar-web** [dotnet/maui#4170]
Hi, I have the same problem, but my problem is different.
I want to get my request Permissin from the user in **Blazor pages** (For example. `FetchData.razor`), for example with a **snackbar** or some other Message way, But when the user rejects my permission request => **Deny**, I can not request again, please help !!
@Eilon 
```
if (ActivityCompat.ShouldShowRequestPermissionRationale(this, Manifest.Permission.AccessFineLocation))
        {
            // Provide an additional rationale to the user if the permission was not granted
            // and the user would benefit from additional context for the use of the permission.
            // For example if the user has previously denied the permission.

            var requiredPermissions = new String[] { Manifest.Permission.AccessFineLocation };
            Snackbar.Make(Test,
                           "plz",
                           Snackbar.LengthIndefinite)
                    .SetAction("ok",
                               new Action<View>(delegate (View obj) {
                                   ActivityCompat.RequestPermissions(this, requiredPermissions, 1);
                               }
                    )
            ).Show();
        }
        else
        {
            ActivityCompat.RequestPermissions(this, new String[] { Manifest.Permission.Camera }, REQUEST_LOCATION);
        }
```

_Originally posted by @masoodafar-web in https://github.com/dotnet/maui/issues/3694#issuecomment-1014880727_

**Comment by Eilon** [comment]
@masoodafar-web said:

>  I can not request again

Can you explain what you mean? Is your permission request code called again, but it does nothing? Or it isn't called? Or there is an error?

**Comment by masoodafar** [comment]
@Eilon said:
> Can you explain what you mean? Is your permission request code called again, but it does nothing? Or it isn't called? Or there is an error?

Thanks for your good support
If I want to explain in full ...
1. The first time the app asked me for permission to access the location, I deliberately did not allow it.
2. The second time I run the application, it does not ask for any permission from me. In this case, I manually ask the user for permission, which again asks me for permission, and I deliberately did not give permission again.
3. The third time I can not access the user even manually, I have to guide him to the application settings and ask the user to allow me to access manually. Because the second time (2) the location option is in the DENIED list of the application and so on There is a reason why (2) does not ask my permission.

**In FetchData.razor page**
```
     try
        {
            location = await Geolocation.GetLocationAsync();////////////// //(1)///////////

        }
        catch (FeatureNotSupportedException fnsEx)
        {
            // Handle not supported on device exception
        }
        catch (FeatureNotEnabledException fneEx)
        {
             // Handle not enabled on device exception
            var intent = new Intent(Android.Provider.Settings.ActionLocationSourceSettings);
            intent.AddFlags(ActivityFlags.NewTask);
            Android.App.Application.Context.StartActivity(intent);
           
        }
        catch (PermissionException pEx)
        {
            // Handle permission exception

            var status=await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>();    ///////////////// //(2)/////////////
            if (status!=PermissionStatus.Granted)
            {
               var permissinstatus= await Permissions.RequestAsync<Permissions.LocationWhenInUse>(); ///////////////(2)///////////
               if (permissinstatus!=PermissionStatus.Granted)
               {
                   AppInfo.ShowSettingsUI();  /////////////////(3)//////////////////
               }
            }
        }
        catch (Exception ex)
        {
            // Unable to get location
        }
```

**Comment by masoodafar** [comment]
I have another question that may not be the right place here, but I would love to ask you to help me because you have a better view of Blazor Maui.
**How bright do you see the future of Blazor maui?**
- I know that Blazor maui is different from Xaml Maui.
- For example, I know that when we work with Xaml we have a Native UI.
- I almost know the advantages and disadvantages of both.
- But I do not want to feel that when I use Balzor Maui I am "writing my application on ice" or "building my house on water".
- In fact, I do not want to think that I am working artificially.
- And if I worked with Xaml, the Performance of my application would be multiplied.
- I want you to tell me that the future of Blazor Maui will be even better than Xaml ,or at least they will be Equal. (In general)
- Because I see that in Github you are almost the only one working on Blazor Maui, this scares me because Blazor himself started very strong and now he is successful.
- But if something like this happens, all WASM blazor developers can easily switch and write mobile applications, and this is a bomb.

**Comment by jfversluis** [comment]
@masoodafar I would suggest opening a discussion for this and not clutter this issue so we can focus on fixing the potential issue here rather than going off-topic with this :)

**Comment by masoodafar** [comment]
> @masoodafar I would suggest opening a discussion for this and not clutter this issue so we can focus on fixing the potential issue here rather than going off-topic with this :)

I'm sorry, however, I moved this topic to a new issue

**Comment by SteveSandersonMS** [comment]
@jsuarezruiz This appears to be about standard MAUI APIs, not Blazor. Would you be able to re-triage? Thanks!

**Comment by domagojmedo** [comment]
Isn't that normal Android behavior? If you deny X times then it's only available through settings

**Comment by Eagle3386** [comment]
> Isn't that normal Android behavior? If you deny X times then it's only available through settings

Nope, but yes.
If denied on 1st attempt, most (modern) apps react to that by showing an (extended) explanation for the permission's requirement & provide a button for immediate permission re-request - which then results in either working without it (with probably reduced features) or refusing to allow any usage until permission is granted.
Some apps then go the aforementioned "button prompt" way while others auto-trigger the permission prompt again & again & again & ...

**Comment by nisargagingo** [comment]
after update [6.0.300-rc.2.5513+sha.8a017cf73-azdo.6048189 ](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.WebView.Maui/6.0.300-rc.2.5513)
not able to access camera from html javascript.
previously it was working by inherit class  BlazorWebViewHandler and override WebChromeClient GetWebChromeClient()

public class MauiWebChromeClient : WebChromeClient
{
    public override void OnPermissionRequest(PermissionRequest request)
    {
        request.Grant(request.GetResources());
    }
}

public class MauiBlazorWebViewHandler : BlazorWebViewHandler
{

    protected override WebChromeClient GetWebChromeClient()
    {
        return new MauiWebChromeClient();
    }
}

But after  update GetWebChromeClient gets compile  error.

**Comment by Rahaaaa** [comment]
> for android after update [6.0.300-rc.2.5513+sha.8a017cf73-azdo.6048189 ](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.WebView.Maui/6.0.300-rc.2.5513) not able to access camera from html javascript. previously it was working by inherit class BlazorWebViewHandler and override WebChromeClient GetWebChromeClient()
> 
> ```cs
> public class MauiWebChromeClient : WebChromeClient
> {
>     public override void OnPermissionRequest(PermissionRequest request)
>     {
>         request.Grant(request.GetResources());
>     }
> }
> 
> public class MauiBlazorWebViewHandler : BlazorWebViewHandler
> {
> 
>     protected override WebChromeClient GetWebChromeClient()
>     {
>         return new MauiWebChromeClient();
>     }
> }
> ```
> 
> But after update GetWebChromeClient gets compile error.

Same here

**Comment by TanayParikh** [comment]
Thanks @nisargagingo for reporting, we'll be discussing this particular issue in https://github.com/dotnet/maui/issues/6565.

Regarding your particular implementation, you're extending the base Android `WebChromeClient`. This poses a concern given you'll lose the [`BlazorWebChromeClient`](https://github.com/dotnet/maui/blob/9175dd04afae9e51854faae7f161f4000d6180ad/src/BlazorWebView/src/Maui/Android/BlazorWebChromeClient.cs#L15) functionality entirely.

**Comment by javiercn** [comment]
@nisargagingo you might be able to access the same functionality by attaching yourself to the `BlazorWebView.BlazorWebViewInitialized` event.

On Android the WebView is available through the args, and from there you can get to the client to configure it.

**Comment by TanayParikh** [comment]
Also note, `request.Grant(request.GetResources());` may be a security concern, as all requested permissions are automatically being granted. You may wish to update that to selectively grant the permissions you care about (ex. [camera access](https://docs.microsoft.com/en-us/dotnet/api/android.webkit.permissionrequest.resourcevideocapture?view=xamarin-android-sdk-12)).

**Comment by janseris** [comment]
@TanayParikh could you then please post or post a link to a solution for this for the current MAUI version, please?

**Comment by Rahaaaa** [comment]
Using the following code solved my problem

```
public class MauiWebChromeClient : WebChromeClient
{
        public override void OnPermissionRequest(PermissionRequest request)
        {
            request.Grant(request.GetResources());
        }
}

public class MauiBlazorWebViewHandler : BlazorWebViewHandler
    {
        protected override void ConnectHandler(Android.Webkit.WebView platformView)
        {
            platformView.SetWebChromeClient(new MauiWebChromeClient());
            base.ConnectHandler(platformView);
}
       }
```

**Comment by nisargagingo** [comment]
Thank you for your quick reply @javiercn and  @Rahaaaa. I tried both ways, and it worked for me,  overriding the ConnectHandler and BlazorWebViewInitialized event.


   private void Bv_BlazorWebViewInitialized(object sender, Microsoft.AspNetCore.Components.WebView.BlazorWebViewInitializedEventArgs e)
    {
#if ANDROID
		e.WebView.SetWebChromeClient(new MauiWebChromeClient());
#endif

	}

**Comment by janseris** [comment]
@Rahaaaa How are you using it?
This is on RC 2:
![image](https://user-images.githubusercontent.com/64279914/165755146-ba577b98-a53b-4e3f-8c80-396771813bf8.png)

**Comment by janseris** [comment]
> 

I am still getting
`The type or namespace name 'Webkit' does not exist in the namespace 'MauiApp4.Platforms.Android' (are you missing an assembly reference?)	
`

**Comment by nisargagingo** [comment]
@janseris
 changing namespace in "MauiBlazorWebViewHandler" to  "MauiApp4" worked for me

![image](https://user-images.githubusercontent.com/104501633/165760583-b1d4d252-6366-42e6-acc8-6b57bcf930f0.png)

**Comment by Rahaaaa** [comment]
Are you intending to run the app on Android?
When my target framework is Android, it works

![Untitled](https://user-images.githubusercontent.com/42100435/165759636-d95174fe-ed33-457e-b97e-6bfae2ff7768.png)

I face the same problem when I switch to other frameworks, such as Windows
![Untitled1](https://user-images.githubusercontent.com/42100435/165759761-d4a2cbb5-a0bc-4777-b7fc-9eee4b578b67.png)

**Comment by javiercn** [comment]
@janseris you need to wrap it with
```
#if ANDROID
#endif
```
to conditionally compile those instructions only when targeting android
