### ISSUE TITLE
[Android] Push notification in MAUI

### ISSUE THREAD

**Issue by Hantse** [dotnet/maui#4173]
### Description

I've try to implemente Push notification with differents way in MAUI app, in each way i've a different issue,
with some, i can use basic of push notification, but not a custom listener for service in android for example.

Different providers try :
- Firebase with https://github.com/CrossGeeks/FirebasePushNotificationPlugin, cannot compile, java issue on compilation
- OneSignal, following tutorial for Xamarin, basic work, but custom listener service failed "Unable to create service ...."
- Azure, unable to compile (same than Firebase) 

### Steps to Reproduce

1. Create new Project (Blazor or normal)
2. Follow Xamarin tutorial for all provider listed below

3. For Onesignal
4. https://documentation.onesignal.com/docs/xamarin-sdk-setup
5. https://documentation.onesignal.com/v7.0/docs/service-extensions#android-notification-service-extension
6. For Firebase
7. https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/GettingStarted.md
8. For Azure
9. https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Android 11 And Up 

### Relevant log output

```shell
Error details for Azure & Firebase :
Severity	Code	Description	Project	File	Line	Suppression State
Error	JAVAC0000	 error: cannot find symbol
		com.google.android.gms.common.api.internal.ConnectionCallbacks
  symbol:   class ConnectionCallbacks
  location: package com.google.android.gms.common.api.internal
	FinkleLFG	C:\Repositories\finklelfgmaui\src\FinkleLFG\obj\Debug\net6.0-android\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java	9	

Severity	Code	Description	Project	File	Line	Suppression State
Error	JAVAC0000	 error: cannot find symbol
		com.google.android.gms.common.api.internal.OnConnectionFailedListener
  symbol:   class OnConnectionFailedListener
  location: package com.google.android.gms.common.api.internal
	FinkleLFG	C:\Repositories\finklelfgmaui\src\FinkleLFG\obj\Debug\net6.0-android\android\src\crc6434af9c19aa01b597\GoogleApiClientOnConnectionFailedListenerImpl.java	9	

Severity	Code	Description	Project	File	Line	Suppression State
Error	JAVAC0000	 error: cannot find symbol
		com.google.android.gms.common.api.internal.OnConnectionFailedListener
  symbol:   class OnConnectionFailedListener
  location: package com.google.android.gms.common.api.internal
	FinkleLFG	C:\Repositories\finklelfgmaui\src\FinkleLFG\obj\Debug\net6.0-android\android\src\mono\com\google\android\gms\common\api\internal\OnConnectionFailedListenerImplementor.java	8	


Error for OneSignal :
Java.Lang.RuntimeException: 'Unable to create service my.package.NotificationExtensionService: java.lang.ClassNotFoundException: Didn't find class "my.package.NotificationExtensionService" on path: DexPathList[[zip file "/data/app/~~Fn_Pvo_5G0R7f1TBwoc0Kw==/my.package-dHrnt7TGv7beFNmkNM1MqA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Fn_Pvo_5G0R7f1TBwoc0Kw==/my.package-dHrnt7TGv7beFNmkNM1MqA==/lib/arm, /data/app/~~Fn_Pvo_5G0R7f1TBwoc0Kw==/my.package-dHrnt7TGv7beFNmkNM1MqA==/base.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib]]'
```

**Comment by jfversluis** [comment]
I don't think any of the plugins/guides you mentioned is made compatible with .NET MAUI (yet). You should be able to make it work on the platform level by implementing the right bits in the Platforms\iOS folder or Platforms\Android folder, but for now that would be manual work.

If you would like to see the plugins/guides being updated, please provide feedback on the sources of those.

I'm not sure there is much we can do about that from our side at the time being.
