### ISSUE TITLE
Inside Stacklayout ScrollView not working 

### ISSUE THREAD

**Issue by vplife1** [dotnet/maui#4176]
### Description

I have used Visual studio 2022 preview 2.0 MAUI.I want to used a ScrollView " But ScrollView is not working  How can i resolve this issue please Guide me 
<StackLayout>
<ScrollView>
Large content enter heare and check

</ScrollView>
</StackLayout>

### Steps to Reproduce

1)create a xaml file 
2)Add ScrollView 
3)add stacklayout
4)Add large Content inside a stack layout

**Expected Behaviour:**      Content (stackLayout) is Scrollable 

**Actual Behaviour**        Content is not scrollable 
 VIEW:--

 <ScrollView GridLayout.Row="1">
                        <VerticalStackLayout> 
                            <HorizontalStackLayout x:Name="timeData" Margin="33,-10,22,10">
                                <Label x:Name="DayName" FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Monday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton x:Name="time" Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding  AddTimeCommand}" CommandParameter="{x:Reference DayName}"></ImageButton>
                                <RadioButton  BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <StackLayout BindableLayout.ItemsSource="{Binding TimeSlotList}" Margin="33,10,22,10" IsVisible="{Binding MondayContentIsVisible}">
                                <BindableLayout.ItemTemplate>
                                    <DataTemplate>
                                        <StackLayout >
                                            <StackLayout Orientation="Horizontal" HorizontalOptions="Center">
                                                <StackLayout Orientation="Vertical" WidthRequest="100">
                                                    <Label Text="From" HorizontalOptions="Center" FontSize="{DynamicResource AppFontSize_Default}" FontAttributes="Bold" TextColor="{DynamicResource Black}"></Label>
                                                    <dxe:TimeEdit HeightRequest="32" Time="{Binding StartTime}" TimeFormatMode="HourFormat12" IsStartIconVisible="False" ClearIconVisibility="Never" IsTimeIconVisible="False" BorderColor="Transparent" BoxMinWidth="87" BackgroundColor="{DynamicResource DefaultColor}"></dxe:TimeEdit>
                                                </StackLayout>
                                                <Image Source="big_line.png" VerticalOptions="End" Margin="10,0,10,0" HorizontalOptions="Center"></Image>
                                                <StackLayout Orientation="Vertical" WidthRequest="100">
                                                    <Label Text="To" HorizontalOptions="Center" FontSize="{DynamicResource AppFontSize_Default}" FontAttributes="Bold" TextColor="{DynamicResource Black}"></Label>
                                                    <dxe:TimeEdit HeightRequest="32" Time="{Binding EndTime}" TimeFormatMode="HourFormat12" IsStartIconVisible="False" ClearIconVisibility="Never" IsTimeIconVisible="False" BorderColor="Transparent" BoxMinWidth="87" BackgroundColor="{DynamicResource DefaultColor}"></dxe:TimeEdit>
                                                </StackLayout>
                                                <StackLayout Padding="30,0,0,0" VerticalOptions="End">
                                                    <Image Source="cross.png" HeightRequest="35" WidthRequest="25">
                                                        <Image.GestureRecognizers>
                                                            <TapGestureRecognizer Command="{Binding CloseTimeTableCommand}" NumberOfTapsRequired="1"></TapGestureRecognizer>
                                                        </Image.GestureRecognizers>
                                                    </Image>
                                                </StackLayout>

                                            </StackLayout>
                                            <BoxView HeightRequest="1" Margin="0,10,0,0" BackgroundColor="LightGray"/>
                                        </StackLayout>
                                    </DataTemplate>
                                </BindableLayout.ItemTemplate>
                            </StackLayout>
</ScrollView>

### Version with bug

Preview 11

### Last version that worked well

Preview 11

### Affected platforms

iOS, Android

### Affected platform versions

Android 11

### Did you find any workaround?

No.

### Relevant log output

```shell
Not Find Any solution
```

**Comment by hartez** [comment]
Please update your report with the full XAML you are using, and we will take a look.
Thanks.

**Comment by vplife1** [comment]
[<Grid RowDefinitions="9*,1*">
           
                <StackLayout GridLayout.Row="0">
                    <Grid RowDefinitions="0.5*,9*">
                    <StackLayout Margin="0,0,0,10" GridLayout.Row="0">
                        <HorizontalStackLayout Margin="0,20,0,0">
                            <Image Source="cross.png" Margin="26,0,0,0"  HeightRequest="25" WidthRequest="25">
                                <Image.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding CloseTimeTableCommand}" NumberOfTapsRequired="1"></TapGestureRecognizer>
                                </Image.GestureRecognizers>
                            </Image>
                            <Label Text="Timetable" Margin="95,0,0,0" Style="{DynamicResource SignUpPageHeaderLbl}" ></Label>
                        </HorizontalStackLayout>
                        <Label Text="Duration" Margin="33,33,0,0" TextColor="{DynamicResource Black}" FontAttributes="Bold" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                        <StackLayout Orientation="Horizontal" Margin="44,19,44,0">
                            <Grid ColumnDefinitions="1.5*,0.7*,1.5*">
                                <StackLayout GridLayout.Column="0" Orientation="Horizontal">
                                    <Image Source="leftarrow.png"></Image>
                                    <Control:BorderlessDatePicker Date="{Binding StartDate}" TextColor="{DynamicResource DefaultColor}"/>
                                    <Image Source="right_arrow.png"></Image>
                                </StackLayout>
                                <Image Source="line.png" HorizontalOptions="StartAndExpand" GridLayout.Column="1"></Image>
                                <StackLayout GridLayout.Column="2" Orientation="Horizontal">
                                    <Image Source="leftarrow.png"></Image>
                                    <Control:BorderlessDatePicker Date="{Binding EndDate}" TextColor="{DynamicResource DefaultColor}"/>
                                    <Image Source="right_arrow.png"></Image>
                                </StackLayout>
                            </Grid>

                        </StackLayout>
                        <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                    </StackLayout>
                    <ScrollView GridLayout.Row="1">
                        <StackLayout>
                            <HorizontalStackLayout x:Name="timeData" Margin="33,-10,22,10">
                                <Label x:Name="DayName" FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Monday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton x:Name="time" Command="{Binding AddTimeCommand}" Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" CommandParameter="{x:Reference DayName}"></ImageButton>
                                <dxe:CheckEdit x:Name="MondayCheck"  CheckedChanged="Monday_CheckedChanged" UncheckedCheckBoxImage="uncheckimage.png" />
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <StackLayout x:Name="MondayContent"  BindableLayout.ItemsSource="{Binding TimeSlotList}" Margin="33,10,22,10" IsVisible="false">
                                <BindableLayout.ItemTemplate>
                                    <DataTemplate>
                                        <StackLayout x:Name="MondayTimeSlotList">
                                            <StackLayout Orientation="Horizontal" HorizontalOptions="Center">
                                                <StackLayout Orientation="Vertical" WidthRequest="100">
                                                    <Label Text="From" HorizontalOptions="Center" FontSize="{DynamicResource AppFontSize_Default}" FontAttributes="Bold" TextColor="{DynamicResource Black}"></Label>
                                                    <dxe:TimeEdit HeightRequest="32" Time="{Binding StartTime}" TimeFormatMode="HourFormat12" IsStartIconVisible="False" ClearIconVisibility="Never" IsTimeIconVisible="False" BorderColor="Transparent" BoxMinWidth="87" BackgroundColor="{DynamicResource DefaultColor}"></dxe:TimeEdit>
                                                </StackLayout>
                                                <Image Source="big_line.png" VerticalOptions="End" Margin="10,0,10,0" HorizontalOptions="Center"></Image>
                                                <StackLayout Orientation="Vertical" WidthRequest="100">
                                                    <Label Text="To" HorizontalOptions="Center" FontSize="{DynamicResource AppFontSize_Default}" FontAttributes="Bold" TextColor="{DynamicResource Black}"></Label>
                                                    <dxe:TimeEdit HeightRequest="32" Time="{Binding EndTime}" TimeFormatMode="HourFormat12" IsStartIconVisible="False" ClearIconVisibility="Never" IsTimeIconVisible="False" BorderColor="Transparent" BoxMinWidth="87" BackgroundColor="{DynamicResource DefaultColor}"></dxe:TimeEdit>
                                                </StackLayout>
                                                <ImageButton BackgroundColor="Transparent" VerticalOptions="End" Source="cross.png" Command="{Binding Path=BindingContext.DeleteTimeSlotCommand,Source={x:Reference Name=TimetableList}}" CommandParameter="{x:Reference MondayTimeSlotList}" 
                                                                                        BindingContext="{Binding Source={x:Reference Name=MondayTimeSlotList}}" ></ImageButton>
                                            </StackLayout>

                                            <BoxView HeightRequest="1" Margin="0,10,0,0" BackgroundColor="LightGray"/>
                                        </StackLayout>
                                    </DataTemplate>
                                </BindableLayout.ItemTemplate>
                            </StackLayout>

                            <HorizontalStackLayout  Margin="33,0,22,10">
                                <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Tuesday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <HorizontalStackLayout Margin="33,0,22,10">
                                <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Wednesday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <HorizontalStackLayout Margin="33,0,22,10">
                                <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Thursday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <HorizontalStackLayout Margin="33,0,22,0">
                                <Label FontAttributes="Bold" WidthRequest="230"  VerticalOptions="Center" Text="Friday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton  BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <HorizontalStackLayout Margin="33,0,22,10">
                                <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Saturday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton  Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton  BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <HorizontalStackLayout  Margin="33,0,22,10">
                                <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Sunday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton  BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                        </StackLayout>
                    </ScrollView>
                    </Grid>
                </StackLayout>
           
            <dxe:SimpleButton GridLayout.Row="2" Margin="24,10,24,0"  Style="{DynamicResource DefaultSimpleButtonStyle}" Command="{Binding CompleteProfileCommand}" Text="{x:Static resources:AppResources.Continue_Btn}"></dxe:SimpleButton>
        </Grid>](url)

**Comment by vplife1** [comment]
@hartez  I have attach my xaml page code Please check .And I'm wating for your positive responce 

[<Grid RowDefinitions="9*,1*">
           
                <StackLayout GridLayout.Row="0">
                    <Grid RowDefinitions="0.5*,9*">
                    <StackLayout Margin="0,0,0,10" GridLayout.Row="0">
                        <HorizontalStackLayout Margin="0,20,0,0">
                            <Image Source="cross.png" Margin="26,0,0,0"  HeightRequest="25" WidthRequest="25">
                                <Image.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding CloseTimeTableCommand}" NumberOfTapsRequired="1"></TapGestureRecognizer>
                                </Image.GestureRecognizers>
                            </Image>
                            <Label Text="Timetable" Margin="95,0,0,0" Style="{DynamicResource SignUpPageHeaderLbl}" ></Label>
                        </HorizontalStackLayout>
                        <Label Text="Duration" Margin="33,33,0,0" TextColor="{DynamicResource Black}" FontAttributes="Bold" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                        <StackLayout Orientation="Horizontal" Margin="44,19,44,0">
                            <Grid ColumnDefinitions="1.5*,0.7*,1.5*">
                                <StackLayout GridLayout.Column="0" Orientation="Horizontal">
                                    <Image Source="leftarrow.png"></Image>
                                    <Control:BorderlessDatePicker Date="{Binding StartDate}" TextColor="{DynamicResource DefaultColor}"/>
                                    <Image Source="right_arrow.png"></Image>
                                </StackLayout>
                                <Image Source="line.png" HorizontalOptions="StartAndExpand" GridLayout.Column="1"></Image>
                                <StackLayout GridLayout.Column="2" Orientation="Horizontal">
                                    <Image Source="leftarrow.png"></Image>
                                    <Control:BorderlessDatePicker Date="{Binding EndDate}" TextColor="{DynamicResource DefaultColor}"/>
                                    <Image Source="right_arrow.png"></Image>
                                </StackLayout>
                            </Grid>

                        </StackLayout>
                        <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                    </StackLayout>
                    <ScrollView GridLayout.Row="1">
                        <StackLayout>
                            <HorizontalStackLayout x:Name="timeData" Margin="33,-10,22,10">
                                <Label x:Name="DayName" FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Monday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton x:Name="time" Command="{Binding AddTimeCommand}" Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" CommandParameter="{x:Reference DayName}"></ImageButton>
                                <dxe:CheckEdit x:Name="MondayCheck"  CheckedChanged="Monday_CheckedChanged" UncheckedCheckBoxImage="uncheckimage.png" />
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <StackLayout x:Name="MondayContent"  BindableLayout.ItemsSource="{Binding TimeSlotList}" Margin="33,10,22,10" IsVisible="false">
                                <BindableLayout.ItemTemplate>
                                    <DataTemplate>
                                        <StackLayout x:Name="MondayTimeSlotList">
                                            <StackLayout Orientation="Horizontal" HorizontalOptions="Center">
                                                <StackLayout Orientation="Vertical" WidthRequest="100">
                                                    <Label Text="From" HorizontalOptions="Center" FontSize="{DynamicResource AppFontSize_Default}" FontAttributes="Bold" TextColor="{DynamicResource Black}"></Label>
                                                    <dxe:TimeEdit HeightRequest="32" Time="{Binding StartTime}" TimeFormatMode="HourFormat12" IsStartIconVisible="False" ClearIconVisibility="Never" IsTimeIconVisible="False" BorderColor="Transparent" BoxMinWidth="87" BackgroundColor="{DynamicResource DefaultColor}"></dxe:TimeEdit>
                                                </StackLayout>
                                                <Image Source="big_line.png" VerticalOptions="End" Margin="10,0,10,0" HorizontalOptions="Center"></Image>
                                                <StackLayout Orientation="Vertical" WidthRequest="100">
                                                    <Label Text="To" HorizontalOptions="Center" FontSize="{DynamicResource AppFontSize_Default}" FontAttributes="Bold" TextColor="{DynamicResource Black}"></Label>
                                                    <dxe:TimeEdit HeightRequest="32" Time="{Binding EndTime}" TimeFormatMode="HourFormat12" IsStartIconVisible="False" ClearIconVisibility="Never" IsTimeIconVisible="False" BorderColor="Transparent" BoxMinWidth="87" BackgroundColor="{DynamicResource DefaultColor}"></dxe:TimeEdit>
                                                </StackLayout>
                                                <ImageButton BackgroundColor="Transparent" VerticalOptions="End" Source="cross.png" Command="{Binding Path=BindingContext.DeleteTimeSlotCommand,Source={x:Reference Name=TimetableList}}" CommandParameter="{x:Reference MondayTimeSlotList}" 
                                                                                        BindingContext="{Binding Source={x:Reference Name=MondayTimeSlotList}}" ></ImageButton>
                                            </StackLayout>

                                            <BoxView HeightRequest="1" Margin="0,10,0,0" BackgroundColor="LightGray"/>
                                        </StackLayout>
                                    </DataTemplate>
                                </BindableLayout.ItemTemplate>
                            </StackLayout>

                            <HorizontalStackLayout  Margin="33,0,22,10">
                                <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Tuesday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <HorizontalStackLayout Margin="33,0,22,10">
                                <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Wednesday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <HorizontalStackLayout Margin="33,0,22,10">
                                <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Thursday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <HorizontalStackLayout Margin="33,0,22,0">
                                <Label FontAttributes="Bold" WidthRequest="230"  VerticalOptions="Center" Text="Friday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton  BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <HorizontalStackLayout Margin="33,0,22,10">
                                <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Saturday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton  Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton  BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                            <HorizontalStackLayout  Margin="33,0,22,10">
                                <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Sunday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                <ImageButton Margin="0,0,30,0" Source="plus.png" BackgroundColor="Transparent" Command="{Binding AddTimeCommand}"></ImageButton>
                                <RadioButton  BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                            </HorizontalStackLayout>
                            <BoxView HeightRequest="1" Margin="17,0,17,0" BackgroundColor="LightGray"/>
                        </StackLayout>
                    </ScrollView>
                    </Grid>
                </StackLayout>
           
            <dxe:SimpleButton GridLayout.Row="2" Margin="24,10,24,0"  Style="{DynamicResource DefaultSimpleButtonStyle}" Command="{Binding CompleteProfileCommand}" Text="{x:Static resources:AppResources.Continue_Btn}"></dxe:SimpleButton>
        </Grid>](url)

**Comment by Eilon** [comment]
Dup of https://github.com/dotnet/maui/issues/3655
