### ISSUE TITLE
MauiAsset is transferred to wrong position or path is incorrect

### ISSUE THREAD

**Issue by whann0205** [dotnet/maui#4184]
### Description

I have created a new folder under Resources named Database and put
a sqllite db in it.
In my case Assetquery.db.
In order to let the build process know about it i have
put the following line into the .csproj file:
<MauiAsset Include="Resources\Database\*" />
This works as expected with android
and the statement
var templateFileName = "Resources\\Database\\AssetQuery.db";
using (var stream_source = await FileSystem.OpenAppPackageFileAsync(templateFileName))
and so on.....
works as expected. 
after building IOS however the file is not in a folder Resources it is directly under
MauiAsset.app !

/Users/whann/Library/Developer/CoreSimulator/Devices/BA95FA38-9718-4C7D-804C-A3F5EF5A6DFD/data/Containers/Bundle/Application/0EC1D196-BB36-4872-9E26-B448A55B5149/MauiAsset.app

not in 
/Resources/Database/AssetQuery.db'
but in
Database/AssetQuery.db'

### Steps to Reproduce

1. Create a new project net maui blazor
2. Add a new folder under Resources for example Database
3. Access it via FileSystem.OpenAppPackageFileAsync(yourfilepath)

### Version with bug

Preview 11

### Last version that worked well

Preview 10

### Affected platforms

iOS

### Affected platform versions

does not matter which ios version

### Did you find any workaround?

Not yet.

**Comment by whann0205** [comment]
I found a Workaround simply by using a compiler directive such as:

string templateFileName;

#if IOS
templateFileName = "Database\\AssetQuery.db";
#else
templateFileName = "Resources\\Database\\AssetQuery.db";
#endif

**Comment by Eilon** [comment]
@whann0205 - was the DB file in your project marked as a MauiAsset, or something else?

We're planning on making some changes to MauiAssets to have a better experience, which is tracked here: https://github.com/dotnet/maui/issues/3270#issuecomment-1023724641

**Comment by whann0205** [comment]
It was and is set to MauiAsset by the setting below in the .csprog file

<MauiAsset Include="Resources\Database\*" />
I am glad that you will simplify that one...

**Comment by Eilon** [comment]
@whann0205 do you know if you also had a `LocalName` set on the `MauiAsset`? Can you show what that part of the CSPROJ looked like? I think the issue you have/had is one thing that we plan to fix, but I want to make sure it's the same issue.

**Comment by whann0205** [comment]
[AssetQueryAppCsproj.zip](https://github.com/dotnet/maui/files/7961719/AssetQueryAppCsproj.zip)
Please find attached the applica
![MauiAsset](https://user-images.githubusercontent.com/71807453/151618627-2988488b-32c1-4325-a36a-dcf58f9a5aa9.PNG)
tions csproj for you to review. 
Dont know how to set a LocalName, but i have attached a screenshot.
Let me know if u need something else....

**Comment by Eilon** [comment]
Hi @whann0205 , I took a quick look at this and I think the recent fix for #3270 will address this!
