### ISSUE TITLE
Essentials references Xamarin in areas (docs/android file providers)

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#4192]
### Description

There are a lot of places where xamarin is still referenced in some places and can have reference issues where Xamarin.Essentials run into conflicts.

https://github.com/dotnet/maui/tree/main/src/Essentials

### Steps to Reproduce

1.) Search for xamarin in the Essentials directory

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

**Comment by profix898** [comment]
_Preferences_ and _SecureStorage_ in Essentials still use `{AppInfo.PackageName}.xamarinessentials.{feature}` and `{AppInfo.PackageName}.xamarinessentials` as name for their storage. Would be good to rename before people start using it in production apps. (Note: `Preferences.GetPrivatePreferencesSharedName` is also used in _VersionTracking_.)

**Comment by Redth** [comment]
Thanks, nice catch, fixed in: https://github.com/dotnet/maui/pull/4211/commits/45adf179d15e79750ce5b87b4e04fa7423ae9852
