### ISSUE TITLE
File Picker always returns cached copy of selected file on Android.

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/maui#4195]
### Description

`await FilePicker.PickAsync()` always copies the selected file to a cached app directory and returns that path rather than the original absolute file path.

https://github.com/dotnet/maui/blob/23b80100ab945061ea9f95a4186bd8672c933e68/src/Essentials/src/FileSystem/FileSystem.android.cs#L75
After checking the source code, if the URI scheme is a file then the absolute path should be returned, this is not the behaviour I am getting. 

### Steps to Reproduce

1) Create a new MAUI Blazor project
2) Add `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` to the android manifest.
3) Add a file onto the android device, i.e Downloads
4) Call `await FilePicker.PickAsync()` and inspect the result.
5) .FullPath of the result will be a cached location and not the original location you selected. 

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 - API 30

**Comment by shimingsg** [comment]
verified repro with vs 17.2.0 Preview 3.0 [32309.500.main] on android
![image](https://user-images.githubusercontent.com/20982341/157842427-3758ef2b-b884-4aad-8721-c83ceebb0fd4.png)
repro demo:
[MauiApp4195.zip](https://github.com/dotnet/maui/files/8230809/MauiApp4195.zip)

**Comment by mattleibow** [comment]
In the later versions of Android, apps are no longer allowed to access files on disk, even if you asked for the permissino to do so. 
In most cases on Android, you are just provided a content URI (such as content://downloads/123456789) and then you use a content resolver to get the actual data.

**Comment by KieranDevvs** [comment]
> In the later versions of Android, apps are no longer allowed to access files on disk, even if you asked for the permissino to do so. In most cases on Android, you are just provided a content URI (such as content://downloads/123456789) and then you use a content resolver to get the actual data.

So how do apps like text editors do it? That's essentially what i'm trying to build.
