### ISSUE TITLE
VS 2022 Pre 17.1.3

### ISSUE THREAD

**Issue by snlyazilim** [dotnet/maui#4214]
### Description

I wanted to open MAUI Project and experiment, but after getting the vs 2022 17.1.3 update, MAUI doesn't appear and I can't open it.

### Steps to Reproduce

I wanted to open MAUI Project and experiment, but after getting the vs 2022 17.1.3 update, MAUI doesn't appear and I can't open it.

### Version with bug

Preview 12 (current)

### Last version that worked well

Preview 12 (current)

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

VS 17.1.0 Preview 3.0

**Comment by hartez** [comment]
Have you tried doing a full Repair on VS (from the installer)? That _might_ fix it.

**Comment by RaspeR87** [comment]
@snlyazilim same for me, but you have to start from clean slate as David mentioned here: https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-12/

Then all works great.

**Comment by snlyazilim** [comment]
yes, thank you I read the article. I will try by reinstalling.
