### ISSUE TITLE
WebView needs ExecuteJavascript support

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#4215]
### Description

From Forms: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#invoking-javascript

### Steps to Reproduce

N/A

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

*

**Comment by lwyj123** [comment]
We need that feature.

**Comment by Redth** [comment]
Fixed in https://github.com/dotnet/maui/pull/4507
