### ISSUE TITLE
IElement ambiguous reference

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#4225]
### Description

When we use the `IElement` there's an ambiguous reference compiler error, see the image below.

![image](https://user-images.githubusercontent.com/20712372/150250750-f49149ed-9445-43b4-ae77-16b8e1393757.png)

I believe that's caused by the `Global namespace` feature.

### Steps to Reproduce

1. Create a Maui project
2. Create an interface or class that inherit from `IElement`
3. See the compiler angry

### Version with bug

Preview 12 (current)

### Last version that worked well

Preview 11

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

Using the namespace alias or the complete name `Microsoft.Maui.IElement`

**Comment by mattscheffer** [comment]
Not Repro in 17.2.0 Preview 1. IElement appears to only use Microsoft.Maul now even when both it and Microsoft.Maui.Controls are added included

![image](https://user-images.githubusercontent.com/10537189/154374233-f2632900-15a2-4132-ad26-081195f98af5.png)

**Comment by pictos** [comment]
@mattscheffer it's still reproducible 
![image](https://user-images.githubusercontent.com/20712372/154375430-9de2e960-e71c-424e-9e26-242b39fff29d.png)

If you want to try on your end, here's [the repo and branch](https://github.com/CommunityToolkit/Maui/tree/pj/popup-to-handler) 

and the [file](https://github.com/CommunityToolkit/Maui/blob/pj/popup-to-handler/src/CommunityToolkit.Maui.Core/Interfaces/IPopup.shared.cs)

**Comment by YuqinSong** [comment]
Not reproducible on 17.2.0 Preview 2.0 [32210.339.main], after create an interface inherit from IElement, there is no ambiguous reference compiler error
