### ISSUE TITLE
Warning throws for tabid syntax with stylecop analyzers

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#4226]
### Description

In our project, we have enabled style cop analyzers. If we use tab syntax inside XML comment's example section, it throws below warning.

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	SA1629	Documentation text should end with a period	MAUIDemo (net6.0-android)
```

### Steps to Reproduce

1. Run the attached sample. We have enabled style cop analyzers in our sample.
2. Check the property "ActualWidth" on the main page. It has XML comments with the tab sections for XAML and c# codes.
3. If we place a period at the end of tabid the warning resolves, but with actual tab id behavior it doesn't require.

[MAUIDemo.zip](https://github.com/dotnet/maui/files/7902522/MAUIDemo.zip)

![image](https://user-images.githubusercontent.com/92788387/150278356-35e3eb52-d20c-4fc5-ab71-e4d906509485.png)

![image](https://user-images.githubusercontent.com/92788387/150278385-03f61474-fcba-4a9e-86a3-e40fc0598c9c.png)

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 9.0, Windows SDK 10.0.19041 

### Did you find any workaround?

We have used a period at the end of tab section syntax.a 

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Warning	SA1629	Documentation text should end with a period	MAUIDemo (net6.0-android)
```

**Comment by YuqinSong** [comment]
Verified Repro on 17.2.0 Preview 2.0 [32210.339.main].

**Comment by Redth** [comment]
I'm not sure what the ask is here? Can you provide some more information?

**Comment by karthikraja-arumugam** [comment]
In Public API XML comments, we have used **tabid** which is used to show the code examples in different tabs while publishing API's. In other platforms like Xamarin, WPF and WinUI it's working fine. But in MAUI the tabid requires a period in the end otherwise it throws warning. Please refer the images attached to the issue report.

**Comment by Redth** [comment]
I still do not understand what’s responsible for this and what the fix is. Are you asking for a specific change in MAUI? If so, what is the change?
