### ISSUE TITLE
[IOS] TimePicker crashes when clicking "Done"

### ISSUE THREAD

**Issue by gdv1982** [dotnet/maui#4228]
### Description

TimePicker crashes with
System.ArgumentException: 'Value is an invalid value for Time (Parameter 'value')'
after the Time has been selected

### Steps to Reproduce

1. Add a TimePicker to the default Maui project
2. Click the TimePicker Label to open the Dialog Card where you select the Time
3. Select any Time in the Dialog Card
4. Click "Done" to close the Dialog Card and transfer the selected value back to the TimePicker Label

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 15.2 Simulator

### Did you find any workaround?

No workarounds found

### Relevant log output

```shell
{System.ArgumentException: Value is an invalid value for Time (Parameter 'value')   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)   at Microsoft.Maui.Controls.TimePicker.set_Time(TimeSpan value)   at Microsoft.Maui.Handlers.TimePickerHandler.SetVirtualViewTime()   at Microsoft.Maui.Handlers.TimePickerHandler.<CreateNativeView>b__4_0()   at Microsoft.Maui.Platform.MauiTimePicker.<.ctor>b__2_0(Object o, EventArgs a)   at UIKit.UIBarButtonItem.Callback.Call(NSObject sender)--- End of stack trace from previous location ---   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)   at testprj.Program.Main(String[] args) in C:\Users\nigmoff\Documents\testprj\Platforms\iOS\Program.cs:line 13}
```

**Comment by shimingsg** [comment]
Verified Repro with iPhone 13 IOs 15.2. Repro project available in Maui Triage Teams channel: 
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EXB-s7WX5uFGmx60q9AV-M0Bto2kiWnm18DdUj9MaDpidg?e=Dm9Rhj
