### ISSUE TITLE
Map Control

### ISSUE THREAD

**Issue by owaits** [dotnet/maui#4233]
### Description

I use Maps in a number of my Apps that I  created with Xamarin. Originally using native implementations and then using the Xamarin maps control. I had spotted on the roadmap that the maps control was scheduled for RC1 so have been patiently waiting. However this appears now to have been removed with the release of Preview 12. 

Is the intention to add the Xamarin Maps controls into Maui? What release might we expect it in?

If its not intended to be part of the framework then it would be good to get some documentation on how to implement it natively.

### Public API Changes

Maps

### Intended Use-Case

Embed maps within and app and display locations and overlays on top of the maps.

**Comment by TFreudi1** [comment]
This is interesting for me too, I also almost use a map in my Xamarin Apps, and also waiting patiently for it, but when I look in to src I did'nt see any progress in that.

**Comment by davefxy** [comment]
Majority of my Xamarin apps also use the map control. I have managed to get most of my 3rd party controls working with Maui. Dont know how to get the map control working. Where should I look to figure this out or when will a map control be implemented for Maui?

**Comment by jfversluis** [comment]
Unfortunately Maps will not be ported before GA. It's on the top of our list for the next release, sorry about that. You can track the progress here #3933
