### ISSUE TITLE
WinUI Fluent/Windows 11 eval

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#4236]
Just as in #3444 we need to remove the old control templates we have overridden previously and revert to the defaults implicitly.  We are switching to use resource dictionary to set styles for the colors as needed.

These styles currently exist in: `src\Core\src\Platform\Windows\Styles`.

The remaining Controls are:

 - [x] #5143
 - [x] #5144
 - [x] #5145
 - [x] #5146
 - [x] #5147
 - [x] #5148
 - [x] #5149
 - [x] #5150
 - [x] #5502

**Comment by mattleibow** [comment]
An example is here: https://github.com/dotnet/maui/pull/3444

**Comment by PureWeen** [comment]
NavigationRoot should be using default templates 

I'm not using any generated style templates anywhere for WinUI navigation parts

**Comment by mattleibow** [comment]
Look at that, progress already!

**Comment by antonfirsov** [comment]
I discovered that `RadioButton` is missing from the list, so opened #5502. Hope I applied the right labels.

/cc @Redth @buyaa-n @mattleibow

**Comment by antonfirsov** [comment]
Closing, since all sub-issues are fixed.
