### ISSUE TITLE
Issue with debugging Windows app

### ISSUE THREAD

**Issue by pvhd** [dotnet/maui#4239]
### Description

There is no dependency for net6.0-windows when creating a new project using VS 2022 version 17.1 Preview 3.0. Therefore, debugging on windows side is not possible.

### Steps to Reproduce

1. Create new project and select template .NET MAUI App
2. When checking Dependencies, there is no dependencies for Windows

### Version with bug

Preview 12 (current)

### Last version that worked well

Preview 11

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041

**Comment by YuqinSong** [comment]
Not reproducible on 17.2.0 Preview 2.0 [32210.339.main], there are dependencies for Windows.
