### ISSUE TITLE
Different Tray Size Showing in MAUI Blazor after update

### ISSUE THREAD

**Issue by igalfsg** [dotnet/maui#4240]
### Description

After Updating to preview 12 the windows tray bar of the application changed to add a back button. Is there a way to go back to the old tray? 
![image](https://user-images.githubusercontent.com/8607853/150405125-2e9170d8-54ff-4b22-9b8f-4a206d9626a0.png)

### Steps to Reproduce

1. Update to preview 12
2. Create a new Blazor Maui app from the template.

### Version with bug

Preview 12 (current)

### Last version that worked well

Preview 11

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

**Comment by Eilon** [comment]
@igalfsg are you seeing the same thing on a non-Blazor MAUI app?

**Comment by igalfsg** [comment]
@Eilon  yes 
![image](https://user-images.githubusercontent.com/8607853/151238009-9856b799-35dd-42a6-b367-010537cd5756.png)

**Comment by Eilon** [comment]
@igalfsg great, thank you for confirming this isn't specific to Blazor.

**Comment by igalfsg** [comment]
@davidortinau  This is not an issue in the [WeatherTwentyOne](https://github.com/davidortinau/WeatherTwentyOne) is there a step that I am missing?

**Comment by Amir-Care** [comment]
Not repro on 17.2.0 Preview 2.0 [32208.484.main] 
![image](https://user-images.githubusercontent.com/99456025/155493331-62c4af46-1fb1-46ec-b850-d69ca757a65c.png)
