### ISSUE TITLE
Android: ControlTemplate within a CollectionView ItemTemplate fails to update templated UI when a TemplateBinding changes value

### ISSUE THREAD

**Issue by Keflon** [dotnet/maui#4242]
### Description

Sample project: https://github.com/Keflon/TestPreview12.git

The sample animates the `Padding` of a `StackLayout` within a `ControlTemplate` on a `ContentView` that is in turn within a `CollectionView`.

See the README.md for details.

On Windows desktop, updating the `Padding` correctly updates the UI.
**On Android, updating the `Padding` (after initially rendering the control) does nothing.**

The sample is contrived; the real use-case is for a `ControlTemplate` to draw the indent of a `TreeView` item.  
When the **_Android_** `CollectionView` recycles containers, the recycled container does not respect the `TemplateBinding` for the `Padding`, causing the `TreeView` items to inherit whatever indent was applied to the container when it was first created.

I can give the `TreeView` source code if that will help track down the bug.

### Steps to Reproduce

1. Create a specialization of ContentView - **MyView**
2. Give it a `ControlTemplate`
3. Use a `TemplateBinding` within the `ControlTemplate` to bind some `View` property (e.g., `Padding`) to a property in the template parent's `BindingContext` (e.g. `double Offset` in your `ViewModel`)
4. Create a `CollectionView` and set the `ItemTemplate` to a `DataTemplate` that contains **MyView**
5. Bind the `CollectionView` to an `ItemsSource` where each item has a property that the `TemplateBinding` is bound to (e.g. `double Offset`)
6. Either
7. Modify the `TemplateBinding` source (the 'Offset' property in the `ViewModel`)
OR
8. Add and remove items from the source collection, _where each item has a different_ `Offset` value.

Notice on Android that
7. The `TemplateBinding` does not update the View
OR
8. Items that are added using a recycled container have the wrong `Offset`.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 emulator. Nokia G10 running Android 11. 

### Did you find any workaround?

Not yet.

**Comment by Keflon** [comment]
I said I was not able to test other platforms. That's probably misleading as I've tested on Windows Desktop and the bug is not present.
I'm adding this comment because I can't edit the 'Affected platform versions'.

Also tested on a LGE Nexus 5X running Android 8.1. The problem is the same.

**Comment by VincentBu** [comment]
I verified on Windows, Mac and Android. On Windows & Mac, the View is updated. However, on Android, as Keflon said, View isn't updated. I will try it on IOS emulator once the build error issue is fixed.

**Comment by rmarinho** [comment]
I tested this and seems to be working with current 6.0.300

<img width="413" alt="image" src="https://user-images.githubusercontent.com/1235097/168837904-55774692-76fc-428d-90c3-ba9c2bd93a4e.png">

**Comment by rmarinho** [comment]
Closing this one as it seem fixed. Please reopen if it's still a issue. 

Thanks
