### ISSUE TITLE
Views Don't Support RightToLeft Layout

### ISSUE THREAD

**Issue by hamiddd1980** [dotnet/maui#4245]
### Description

Hello. many Views and Functionalities don't appear correctly when **FlowDirection** property is set to **RightToLeft** (many of these bugs were also present in Xamarin.Forms and Unfortunately haven't been solved so far):
1-Stacklayout
2-Gradient (Reported Bug Number On Xamarin.Forms Github: #11536)
3-Shapes (Reported Bug Number On Xamarin.Forms Github: #11536)
4-Relativelayout  (Reported Bug Number On Xamarin.Forms Github: #11637)
It seems that MAUI ,like Xamarin.Forms, will not support RightToLeft completely (Contrary to other Microsoft perfect products like WPF, Winform which fully support RightToLeft ).
Thank You.

### Steps to Reproduce

1.Create a MAUI Project 
2.Evaluate Views appearance and Functionality when FlowDirection is RightToLeft

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Android 10

**Comment by wenwen60** [comment]
Reproduce on Android 11, attach repro sample
[MauiApp2.zip](https://github.com/dotnet/maui/files/8131223/MauiApp2.zip)

**Comment by jfversluis** [comment]
Duplicate of #2255
