### ISSUE TITLE
Border background color is not updated in Windows machine

### ISSUE THREAD

**Issue by naveenkumar-sanjeevirayan** [dotnet/maui#4248]
### Description

In our project, We have added a label as content in the border. The Border.Background color is not updated when Label.Text is updated dynamically.

Demo sample:
[MauiBorderDemo.zip](https://github.com/dotnet/maui/files/7912087/MauiBorderDemo.zip)

Video:

https://user-images.githubusercontent.com/61832185/150504204-47dae10c-aa0f-44c2-961a-9e40ae63f73d.mp4

### Steps to Reproduce

1. Run the attached sample.
2. Click on the button dynamically.

Expected:
The label text only changed and the border background shouldn't change.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

We have used .Measure() method for layout while updating border content.

### Relevant log output

No response

**Comment by NogginBox** [comment]
Is this related to issue #3791?

**Comment by YuqinSong** [comment]
Verified Repro on 17.2.0 Preview 2.0 [32210.339.main]

**Comment by VSadov** [comment]
Fixed in #5324
