### ISSUE TITLE
[Windows]Clip property is not working properly in preview 12

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#4250]
### Description

When applying a clip with RoundRectangleGeometry to the content view, exception occur as like below  in windows 

![image](https://user-images.githubusercontent.com/92785406/150504025-67a716a3-aec8-4b2f-80a4-3cdb04573561.png)

**After calling CanvasDrawingSession.CreateLayer, you must close the resulting CanvasActiveLayer before ending the CanvasDrawingSession.**

### Steps to Reproduce

1.Run the attached sample in windows platform 
[ClipSample.zip](https://github.com/dotnet/maui/files/7912599/ClipSample.zip)
2.Click Apply effects button to change the round rectangle
3.Application get crash.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 15,Android 11,Windows

**Comment by jeya-kasipandi** [comment]
Can anyone please check and provide the solution?

**Comment by jeya-kasipandi** [comment]
Any update on this?

**Comment by shimingsg** [comment]
Not reproducible with Windows.

**Comment by jeya-kasipandi** [comment]
@shimingsg The reported issue still reproduce in windows. Can you click the apply effects button to change into a round rectangle? Now the reported issue will reproduce in windows. The application gets crash when clicking the apply effects button.

**Comment by Redth** [comment]
Can confirm, this repro's for me on windows.
