### ISSUE TITLE
Warning NU1703 only for net6.0-maccatalyst when adding package Microsoft.EntityFrameworkCore.SqlServer

### ISSUE THREAD

**Issue by Bronzato1** [dotnet/maui#4252]
### Description

On a brand new .NET MAUI Blazor app, adding the nuget package Microsoft.EntityFrameworkCore.SqlServer (latest version) throw hundreds of NU1703 warnings only for net6.0-maccatalyst 

This does not prevent the application from running as expected.

One of them: Warning	NU1703	'Microsoft.EntityFrameworkCore 6.0.1' was resolved as a dependency of 'BlazorMauiApp1', but the dependency is using 'Xamarin.iOS' while 'BlazorMauiApp1' is using 'net6.0-maccatalyst15.0' as its TargetFramework. There might be compatibility issues when MacCatalyst projects depend on Xamarin.iOS projects.	

Note 1: this problem existed yet in previous preview versions of MAUI.
Note 2: same problem with other packages like System.IdentityModel.Tokens.Jwt

### Steps to Reproduce

- Create a brand new .NET MAUI Blazor app
- Add the nuget package Microsoft.EntityFrameworkCore.SqlServer (latest version) 
- Throwing hundreds of NU1703 warnings only for net6.0-maccatalyst
- Removing this package from the project resolve all warnings

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

OS: Windows 11 - Visual Studio Professional 2022 - Preview Version 17.1.0 Preview 2.0

**Comment by VincentBu** [comment]
Hi @Bronzato1 , I create a brand new .NET MAUI Blazor app on my windows and install Microsoft.EntityFrameworkCore.SqlServer 6.0.3 for it.
Then I build project with command `dotnet build -f:net6.0-maccatalyst`:
![image](https://user-images.githubusercontent.com/44959937/157631791-1ea44b71-1aa9-4a89-90ed-e7343e3fd767.png)

I don't see any warning in output. There is also no NU1703 warning in `Error List` tag:
![image](https://user-images.githubusercontent.com/44959937/157632281-9328f2a8-95aa-48cc-8bff-42cd2175fb1f.png)

**Comment by VincentBu** [comment]
Feel free to open a new issue if you get this warning message again.
