### ISSUE TITLE
DisplayAlert bug

### ISSUE THREAD

**Issue by yiszza** [dotnet/maui#4253]
### Description

When I use DisplayAlert, the changes to ui don't take effect, android's AlertDialog doesn't have this problem

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/42995476/150513009-c0eb0989-970b-4e84-98a7-a992d2308e03.png)

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 11

### Did you find any workaround?

use android's AlertDialog

**Comment by jfversluis** [comment]
Hey @yiszza thanks for the report. I'm unsure what you mean by "the UI changes don't take effect". What are you expecting to see and what doesn't happen?

**Comment by yiszza** [comment]
> Hey @yiszza thanks for the report. I'm unsure what you mean by "the UI changes don't take effect". What are you expecting to see and what doesn't happen?

`this.LogLayout.Clear();` Did not happen

**Comment by jfversluis** [comment]
What is `LogLayout` in this case? I think it would help speed this up if you would add some more relevant code or possibly even a reproduction project :)

**Comment by yiszza** [comment]
> What is `LogLayout` in this case? I think it would help speed this up if you would add some more relevant code or possibly even a reproduction project :)

https://user-images.githubusercontent.com/42995476/150984162-8ddd6187-7469-4b6d-b40a-eb5ad59cad0d.mp4

[MauiApp1.zip](https://github.com/dotnet/maui/files/7933825/MauiApp1.zip)

**Comment by mterhorst** [comment]
@yiszza I can confirm the same problem. Happens with `DisplayPromptAsync` as well.

**Comment by kristinx0211** [comment]
confirm the same problem, Debug logs:
`> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.MauiApp1/crc64e632a077a20c694c.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.MauiApp1/crc64e632a077a20c694c.MainActivity }
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/MauiApp1.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Mono.Android.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Runtime.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Java.Interop.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Collections.dll [External]
Resolved pending breakpoint for 'Android.Runtime.JNIEnv.RegisterJniNatives(System.IntPtr, System.Int32, System.IntPtr, System.IntPtr, System.Int32)' to /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:124 [0x00000].
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Threading.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Runtime.InteropServices.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Threading.Thread.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Diagnostics.StackTrace.dll [External]
Loaded assembly: data-0x79ec63446030 [External]
Loaded assembly: data-0x79ec63476060 [External]
Loaded assembly: data-0x79ecf7165040 [External]
[nyname.MauiApp] Late-enabling -Xcheck:jni
[nyname.MauiApp] Unquickening 12 vdex files!
[nyname.MauiApp] Unexpected CPU variant for X86 using defaults: x86_64
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[debug-app-helper] Checking if libmonodroid was unpacked to /data/app/~~9f6J9ISUFE4dC3pk7DnVqQ==/com.companyname.MauiApp1-DkeKsZ49q1xUKVmzNTsrjA==/lib/x86_64/libmonodroid.so
[debug-app-helper] Native libs extracted to /data/app/~~9f6J9ISUFE4dC3pk7DnVqQ==/com.companyname.MauiApp1-DkeKsZ49q1xUKVmzNTsrjA==/lib/x86_64, assuming application/android:extractNativeLibs == true
[debug-app-helper] Setting up for DSO lookup in app data directories
[debug-app-helper] Added filesystem DSO lookup location: /data/app/~~9f6J9ISUFE4dC3pk7DnVqQ==/com.companyname.MauiApp1-DkeKsZ49q1xUKVmzNTsrjA==/lib/x86_64
[debug-app-helper] Using runtime path: /data/app/~~9f6J9ISUFE4dC3pk7DnVqQ==/com.companyname.MauiApp1-DkeKsZ49q1xUKVmzNTsrjA==/lib/x86_64
[debug-app-helper] checking directory: `/data/user/0/com.companyname.MauiApp1/files/.__override__/lib`
[debug-app-helper] directory does not exist: `/data/user/0/com.companyname.MauiApp1/files/.__override__/lib`
[debug-app-helper] Checking whether Mono runtime exists at: /data/user/0/com.companyname.MauiApp1/files/.__override__/libmonosgen-2.0.so
[debug-app-helper] Checking whether Mono runtime exists at: /data/app/~~9f6J9ISUFE4dC3pk7DnVqQ==/com.companyname.MauiApp1-DkeKsZ49q1xUKVmzNTsrjA==/lib/x86_64/libmonosgen-2.0.so
[debug-app-helper] Mono runtime found at: /data/app/~~9f6J9ISUFE4dC3pk7DnVqQ==/com.companyname.MauiApp1-DkeKsZ49q1xUKVmzNTsrjA==/lib/x86_64/libmonosgen-2.0.so
[nyname.MauiApp] Attempt to remove non-JNI local reference, dumping thread
[DOTNET] JNI_OnLoad: JNI_OnLoad in pal_jni.c
[monodroid] Creating public update directory: `/data/user/0/com.companyname.MauiApp1/files/.__override__`
[nyname.MauiApp] Attempt to remove non-JNI local reference, dumping thread
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=10.0.2.2:64311,embedding=1
[monodroid-assembly] open_from_bundles: failed to load assembly MauiApp1.dll
[monodroid-gc] GREF GC Threshold: 46080
[monodroid-assembly] open_from_bundles: failed to load assembly Mono.Android.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Java.Interop.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.InteropServices.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.Thread.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.StackTrace.dll
[nyname.MauiApp] Attempt to remove non-JNI local reference, dumping thread
Loaded assembly: data-0x79ec63426010 [External]
[monodroid-assembly] open_from_bundles: failed to load assembly netstandard.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/netstandard.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Linq.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.Concurrent.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Collections.Concurrent.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:415 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Json.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Text.Json.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encodings.Web.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Text.Encodings.Web.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.ComponentModel.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Maui.Controls.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.ObjectModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Graphics.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Abstractions.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.ObjectModel.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Maui.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Logging.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Loader.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Runtime.Loader.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:410 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.Lightweight.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.ILGeneration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Primitives.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Reflection.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Essentials.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Core.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Core.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Hosting.Abstractions.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Hosting.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.Abstractions.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Compatibility.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Hosting.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Abstractions.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Maui.Controls.Compatibility.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Hosting.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Configuration.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.FileProviders.Physical.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.FileProviders.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Primitives.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.FileProviders.Physical.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.FileProviders.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.DependencyInjection.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.FileExtensions.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Configuration.FileExtensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Options.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Options.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.EventLog.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Configuration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Debug.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Console.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.EventSource.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Logging.EventLog.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Logging.Configuration.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Logging.Debug.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Logging.Console.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Logging.EventSource.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Options.ConfigurationExtensions.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Options.ConfigurationExtensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Xaml.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Maui.Controls.Xaml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.AppCompat.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.Google.Android.Material.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.AppCompat.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.Google.Android.Material.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.TypeConverter.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.ComponentModel.TypeConverter.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Uri.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Private.Uri.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.DrawerLayout.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CustomView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.Runtime.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.DrawerLayout.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.CustomView.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Navigation.Runtime.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.DiagnosticSource.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Diagnostics.DiagnosticSource.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.Tracing.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Diagnostics.Tracing.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Binder.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Extensions.Configuration.Binder.dll [External]
[0:] Microsoft.Maui.Dispatching.Dispatcher: Warning: Replaced an existing DispatcherProvider with one from the service provider.
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.Expressions.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Linq.Expressions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Xml.ReaderWriter.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Xml.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Private.Xml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encoding.Extensions.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Text.Encoding.Extensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Memory.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Memory.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.RegularExpressions.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Text.RegularExpressions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.CompilerServices.Unsafe.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Runtime.CompilerServices.Unsafe.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Numerics.Vectors.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Numerics.Vectors.dll [External]
Thread started:  #2
Thread started:  #3
Thread started:  #4
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Json.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.DataContractSerialization.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Xml.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Runtime.Serialization.Json.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Private.DataContractSerialization.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Runtime.Serialization.Xml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Primitives.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Runtime.Serialization.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SwipeRefreshLayout.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CardView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Compatibility.Android.FormsViewGroup.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.RecyclerView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.ViewPager.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Fragment.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Activity.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.ViewModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.Common.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SavedState.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.SwipeRefreshLayout.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.CardView.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Microsoft.Maui.Controls.Compatibility.Android.FormsViewGroup.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.RecyclerView.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.ViewPager.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Fragment.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Activity.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Lifecycle.ViewModel.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Lifecycle.Common.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.SavedState.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.ViewPager2.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.ViewPager2.dll [External]
[libEGL] loaded /vendor/lib64/egl/libEGL_emulation.so
[libEGL] loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Loader.dll
[libEGL] loaded /vendor/lib64/egl/libGLESv2_emulation.so
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Loader.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CoordinatorLayout.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.CoordinatorLayout.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.Fragment.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.Common.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Navigation.Fragment.dll [External]
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Navigation.Common.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.LiveData.Core.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Lifecycle.LiveData.Core.dll [External]
[nyname.MauiApp] Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
[nyname.MauiApp] Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.UI.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/Xamarin.AndroidX.Navigation.UI.dll [External]
Thread started: <Thread Pool> #5
Thread started: .NET ThreadPool Gate #6
Thread started: <Thread Pool> #7
Thread started: .NET Timers #8
[HostConnection] HostConnection::get() New Host Connection established 0x79eaf3432b50, tid 30688
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
[OpenGLRenderer] Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
[EGL_emulation] eglCreateContext: 0x79eae3484be0: maj 3 min 0 rcv 3
[EGL_emulation] eglMakeCurrent: 0x79eae3484be0: ver 3 0 (tinfo 0x79ea83ab9780) (first time)
[Gralloc4] mapper 4.x is not supported
[HostConnection] createUnique: call
[HostConnection] HostConnection::get() New Host Connection established 0x79eaf34332d0, tid 30688
[goldfish-address-space] allocate: Ask for block of size 0x100
[goldfish-address-space] allocate: ioctl allocate returned offset 0x3f3ffe000 size 0x2000
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
[nyname.MauiApp] Waiting for a blocking GC ProfileSaver
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Intrinsics.dll
Loaded assembly: /data/data/com.companyname.MauiApp1/files/.__override__/System.Runtime.Intrinsics.dll [External]
Thread started: <Thread Pool> #9
Thread started: <Thread Pool> #10
Thread started: <Thread Pool> #11
[OpenGLRenderer] endAllActiveAnimators on 0x79eb63477e40 (RippleDrawable) with handle 0x79ea83c64a10
[OpenGLRenderer] endAllActiveAnimators on 0x79eb6348c1b0 (RippleDrawable) with handle 0x79ea83c68d90
The thread 0xb has exited with code 0 (0x0).
The thread 0x5 has exited with code 0 (0x0).
Thread finished: <Thread Pool> #11
Thread finished: <Thread Pool> #5
Thread finished: <Thread Pool> #9
The thread 0x9 has exited with code 0 (0x0).
Thread started: <Thread Pool> #12
The thread 0x7 has exited with code 0 (0x0).
Thread finished: <Thread Pool> #7
[OpenGLRenderer] endAllActiveAnimators on 0x79eb634917f0 (RippleDrawable) with handle 0x79ea83c6c060
Thread started: <Thread Pool> #13
`

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by mterhorst** [comment]
> Verified repro with Android 11 and the above project.

Yes, reproducible with preview 13.

**Comment by jsuarezruiz** [comment]
After opening the Maui AlerDialog and tapping the clear button, nothing happens, right?
![issue-4253](https://user-images.githubusercontent.com/6755973/161519780-c3fb9bfc-c82b-4f06-bdf4-a8e201e05238.gif)
Cannot reproduce the issue using the main branch.

**Comment by Muehli-dev** [comment]
I had a similar issue,  after Displaying an Alert, changes to Bound ViewModel Properties won't change the corresponding labels.

**Comment by PureWeen** [comment]
> > What is `LogLayout` in this case? I think it would help speed this up if you would add some more relevant code or possibly even a reproduction project :)
> 
>  20220125211745.mp4 
> [MauiApp1.zip](https://github.com/dotnet/maui/files/7933825/MauiApp1.zip)

I tested this project with the latest RC and this looks fixed
