### ISSUE TITLE
[Android] Measure infinite loop

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4261]
### Description

Using https://github.com/jsuarezruiz/netmaui-chat-app-challenge detected a layout measure loop having a big impact in the performance.

![loop](https://user-images.githubusercontent.com/6755973/150518845-c9d77377-dd4b-4ce8-ac6c-0990f75b5f0c.gif)

Debugging the code seems to happens in ScrollView.

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-chat-app-challenge
2. Launch the App on Android and inspect GPU rendering https://developer.android.com/topic/performance/rendering/inspect-gpu-rendering

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by shimingsg** [comment]
Not reproducible with Android 11.
