### ISSUE TITLE
XAML Editor control issue on .NET MAUI Preview 10 for Android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4264]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/XAML-Enter-control-issue-on-NET-MAUI-Pr/1638306)._

---
Visual Studio 2022 17.1 Preview 2.0 / .NET MAUI Preview 10.

On the Android emulator, entering text in the Editor control always adds it to the end. It works fine in Xamarin projects.

! [Screenshot_1642342240.png] (https://aka.ms/dc/image?name=Ba6b7758329d14fab8848b3b3597f4396637779393774152016_Screenshot_1642342240.png&tid=a6b7758329d14fab8848b3b3597f4396637779393774152016)

! [Screenshot_1642342244.png] (https://aka.ms/dc/image?name=B7363f4f5766848d48b1b7beb306e9b0a637779393880939555_Screenshot_1642342244.png&tid=7363f4f5766848d48b1b7beb306e9b0a637779393880939555)

To do this, simply create a MAUI project and change MainPage.xaml as follows.

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ScrollTestMaui.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">
      <Editor x:Name="editor"/>
</ContentPage>
```

This is the sample project.
[ScrollTestMaui.zip] (https://aka.ms/dc/file?name=B1004264d5e424662847b6e0de8cadf57637779398126142272_ScrollTestMaui.zip&tid=1004264d5e424662847b6e0de8cadf57637779398126142272)

---
#### Feedback Bot on 1/17/2022, 01:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/18/2022, 03:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Looks like this is an older issue by now. If this still impacts you, please open a new issue with all the details. Thanks!
