### ISSUE TITLE
FlyoutBackgroundColor and FlyoutBackground on Windows are not working

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#4266]
### Description

#3165 says this is fixed, but I'm not seeing that on Windows. The flyout below should be light grey, the same color as the nav bar.

![image](https://user-images.githubusercontent.com/41873/150602904-7ff96922-ff37-4675-871e-37c3ebfce497.png)

It is taking the Page background color always in this case.

This is the only thing that works:

```xaml
<Shell FlyoutBackground="Red">
```

<img width="209" alt="image" src="https://user-images.githubusercontent.com/41873/150603536-3243c14c-53cd-41e6-8a39-533f2bbef293.png">

I cannot use a StaticResource of Color or Brush. I cannot use `FlyoutBackgroundColor`. I cannot use `AppThemeBinding`. I cannot set it in a style:

```xaml
<Style x:Key="BaseStyle"
           TargetType="Element">
            <Setter Property="Shell.FlyoutBackground"
                        Value="{AppThemeBinding 
                                Light={StaticResource LightGrayBrush}, 
                                Dark={StaticResource BackgroundMidBrush}}"/>
            <Setter Property="Shell.BackgroundColor"
                    Value="{AppThemeBinding 
                        Light={StaticResource LightGray}, 
                        Dark={StaticResource Background_Mid}}" />
```

### Steps to Reproduce

https://github.com/davidortinau/WeatherTwentyOne

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Win11

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/Ee-ajAktn6tLqk42C9iIvfIBkWy7YPy_C-DyO7FMzAagiA?e=J9Ev7m
