### ISSUE TITLE
Compatibility: (Revised) Ported Xamarin Forms Effect registration never resolves

### ISSUE THREAD

**Issue by IndianaGary** [dotnet/maui#4269]
### Description

While testing a newly ported custom ColorPicker, I ported the control's touch handling in ColorPickerTouchEffect, which consists of the platform-independent ColorPickerTouchRoutingEffect and the platform-specific ColorPickerTouchEffectXXXX, where XXXX is platform specific (WinUI, Droid, etc) currently being implemented. 

During my testing I set breakpoints in each of the Configure... builder calls in MauiProgram and discovered that  ConfigureEffects fails to register the PlatformEffect.  Both ConfigureFonts and ConfigureMauiHandlers are called as expected. I confirmed that ConfigureEffects IS called because the EffectsFactory and EffectsRegistration are in the builder. 

AddCompatibilityEffects, which performs assembly scanning, never resolves the PlatformEffect.

Here is the initialization code:

```

    public static MauiApp CreateMauiApp()
    { 
        var builder = MauiApp.CreateBuilder();

        builder.UseMauiApp<App>();
        builder.UseSkiaSharp( true );

        builder.ConfigureMauiHandlers( handlers =>
        {
            handlers.TryAddCompatibilityRenderer( typeof( ColorCircle ), typeof( ColorCircle ) );
            handlers.TryAddCompatibilityRenderer( typeof( ColorWheel ), typeof( ColorWheel ) );
            handlers.TryAddCompatibilityRenderer( typeof( ColorTriangle ), typeof( ColorTriangle ) );
            handlers.TryAddCompatibilityRenderer( typeof( AlphaSlider ), typeof( AlphaSlider ) );
            handlers.TryAddCompatibilityRenderer( typeof( LuminositySlider ), typeof( LuminositySlider ) );
            handlers.TryAddCompatibilityRenderer( typeof( RGBSliders ), typeof( RGBSliders ) );
            handlers.TryAddCompatibilityRenderer( typeof( HSLSliders ), typeof( HSLSliders ) );
        } );

        builder.ConfigureFonts( fonts =>
        {
            fonts.AddFont( "OpenSans-Regular.ttf", "OpenSansRegular" );
        } );

        builder.ConfigureEffects( effects =>
        {
            var assemblies = Device.GetAssemblies();
            effects.AddCompatibilityEffects( assemblies );
        } );

        return builder.Build();
```

### Steps to Reproduce

1. Port an XF application that includes an Effect
2. Add builder.ConfigureEffects to MauiProgram to register Effects
3. Launch the application
4. Observe a NRE because the PlatformEffect was not atttached to the RoutingEffect
    which should occur during Effect resolution.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12 and up, Windows SDK 10.0.19041

### Did you find any workaround?

Not yet, although I'm still working on it. I filed this because Shane recommended that I do so.

Subsequent debugging revealed that ConfigureEffects is working correctly.  Still tracking down why the registration function, AddCompatibilityEffects, doesn't resolve the Effect.

### Relevant log output
None

**Comment by IndianaGary** [comment]
Further research:  I've determined that when the RoutingEffect is instantiated, its constructor calls Effect.Resolve using the "ResolutionGroupName.UniqueName" string to set Inner to the PlatformEffect which fails resulting in Inner being set to NullEffect.

My code is as follows:

```
    public ColorPickerTouchRoutingEffect() : base( "ColorPickerTouchEffect.TouchEffect" ) 
    {
    }
```
for the routing effect constructor in Platform\ Windows included:

```
[assembly: ResolutionGroupName( "ColorPickerTouchEffect" )]
[assembly: ExportEffect( typeof( ColorPickerTouchEffectWinUI ), "TouchEffect" )]
namespace ColorPicker.Effects;
```

which appears correct.

**Comment by IndianaGary** [comment]
I've continued debugging and determined that the real problem is that Effect resolution never occurs. If a RoutingEffect's resolution string is not found in the internal dictionary, the Inner reference is set to a NullEffect instead of the PlatformEffect. As shown in the previous comment the resolution string follows the rules, yet is not found. I proved this by adding the following line of code after the Effect was created and added to the control:

```
        var testEffect = Effect.Resolve( "ColorPickerTouchEffect.TouchEffect" );
```

The result was a NullEffect, confirming that the dictionary lookup for the PlatformEffect failed. Following the registration of the PlatformEffect is difficult in the extreem without the ability to debug into the code.

**Comment by IndianaGary** [comment]
Note... edited the PR to reflect some code corrections and additional debugging.

**Comment by Coloryr** [comment]
if your `MauiApp` configuration as
```C#
public static MauiApp CreateMauiApp()
{
var assemblies = Device.GetAssemblies();
var builder = MauiApp.CreateBuilder();
builder
	.UseMauiApp<App>()
	.ConfigureFonts(fonts =>
	{
		fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
	})
	.ConfigureMauiHandlers(handlers =>
	{
		handlers.AddCompatibilityRenderers(assemblies);
	})
	.ConfigureEffects(effects =>
	{
		effects.AddCompatibilityEffects(assemblies);
		OpenGLPage.page.bind();
	});

return builder.Build();
}
```
when use `view.Effects.Add(touchEffect);` that will call `ConfigureEffects`,but Add once will call once.

**Comment by Coloryr** [comment]
ok that work.
Program code
```
public static class MauiProgram
{
	static bool isLoad;
	public static MauiApp CreateMauiApp()
	{
		var assemblies = Device.GetAssemblies();
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
			})
			.ConfigureMauiHandlers(handlers =>
			{
				handlers.AddCompatibilityRenderers(assemblies);
			})
			.ConfigureEffects(effects =>
			{
				if (isLoad)
					return;
				effects.AddCompatibilityEffects(assemblies);
				isLoad = true;
				OpenGLPage.page.bind();
			});

		return builder.Build();
	}
}
```
page code
```
public OpenGLPage()
{
    ....
    TouchEffect touchEffect = new TouchEffect();
    touchEffect.TouchAction += OnTouchEffectAction;
    glview.Effects.Add(touchEffect);
    .....
}

bool isBind = false;

	public void bind() 
	{
		Dispatcher.Dispatch(() =>
		{
			var testEffect = Effect.Resolve("XamarinDocs.TouchEffect");

			if (isBind || testEffect is NullEffect)
				return;

			glview.Effects.Clear();

			TouchEffect touchEffect = new TouchEffect();
			touchEffect.TouchAction += OnTouchEffectAction;
			glview.Effects.Add(touchEffect);

			isBind = true;
		});
	}
```

**Comment by IndianaGary** [comment]
Thanks for following up. With no movement on the issue I choose to abandon Effects and converted the code to a Behavior which uses a different (and simpler) mechanism. As the Behavior performs the requisite services perfectly, I am abandoning Effects for now.

**Comment by samhouts** [comment]
@IndianaGary Sorry for the delay getting back to you! I'll close this for now, but please let us know if you come across further issues. Thank you!!
