### ISSUE TITLE
MAUI App iOS publishing problem

### ISSUE THREAD

**Issue by aokocax** [dotnet/maui#4271]
### Description

I want to submit my MAUI app to the AppStore for testing, but the IPA file is not generated. I tried all the options in the publish section but failed. 

![s1](https://user-images.githubusercontent.com/1059475/150639410-3caa2b7d-1b7f-49a4-9079-0e3ed3be215b.jpg)

It says publish succeeded but there is no file in the associated directory.

If I choose platform-dependent it gives this error. (tmp file contains the same error)
![s4](https://user-images.githubusercontent.com/1059475/150639506-e4017888-aa07-4851-895e-bc7533018721.jpg)

![s2](https://user-images.githubusercontent.com/1059475/150639244-e2ac375d-a3e0-46c7-ae8e-06b9c6dade59.jpg)
Unfortunately, there is no documentation on this subject. I saw that it was done via the command line in another issue, but it still did not create an IPA. @Redth  https://github.com/dotnet/maui/issues/3283

Could you help?

### Steps to Reproduce

1. Create MAUI project
2. Try to publish for iOS platform

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details.
```

**Comment by RaspeR87** [comment]
Yes, same question from me

**Comment by owaits** [comment]
Also spent the last two days trying to work out why the build output states that it has generated an IPA file but when you go to copy the build artefacts it can not find any file with the extension ipa. I had pretty much reached the same conclusion that it is not working and the ipa file is not being created even though it states it has. Also keen the get a MAUI app into the app store so I can start testing. 

Its been a little frustrating that all the blogs and videos only mention either using the IOS simulator or building Android. Most of what I have achieved has been pieced together or guess work. I am using the build command bellow.

`dotnet publish $(PathTocsproj) -f net6.0-ios -c Release -p:BuildIpa=True -p:Platform="iPhone" -p:IpaPackagePath=$(build.artifactstagingdirectory)/wa2022.ipa `

**Comment by aokocax** [comment]
Finally I was able to create the IPA file with this command and upload the file with altool without any errors.

`dotnet publish -f net6.0-ios -c Release -o art -p:BuildIpa=True -p:IpaPackagePath=art/ipa/app.ipa -r ios-arm64 --self-contained`

`xcrun altool --upload-app -f app.ipa -u aog*****@gmail.com -p pass*** -type iOS`
//No errors uploading 'app.ipa'

Now I got an email from Apple, I will try to solve it.

`We identified one or more issues with a recent delivery for your app, "MauiTest" 1 (1). Please correct the following issues, then upload again.

ITMS-90338: Non-public API usage - The app references non-public symbols in mauipub: _proc_pidinfo. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/`

**Comment by aokocax** [comment]
Finally I was able to send it without any problem. For the solution of the above error, it is necessary to switch to the daily sdk (SDK 6.0.2-servicing.1.22063.8) and update the workload (maui-ios).

**Comment by jfversluis** [comment]
I've created a complete overview in #4397. Closing this one for now, let's centralize in the other issue. Thanks!
