### ISSUE TITLE
When adding Xamarin.GooglePlayServices.Base nuget package can't build the MAUI project

### ISSUE THREAD

**Issue by davidnalbandyan1** [dotnet/maui#4276]
### Description

When adding Xamarin.GooglePlayServices.Base nuget package can't build the MAUI project

### Steps to Reproduce

Add Xamarin.GooglePlayServices.Base nuget package.
![image](https://user-images.githubusercontent.com/87818513/150655484-f085e069-a8aa-4b80-ac7e-9b100db515a4.png)
![image](https://user-images.githubusercontent.com/87818513/150655501-d4fcd8f5-5775-4efe-9f35-4df63fa6365f.png)
![image](https://user-images.githubusercontent.com/87818513/150655445-87ff1ad9-cac1-4cb3-ac91-6156c2d8ea9f.png)

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EYq8iHpxdiRAjhIFyuTKOocBKSWqnBhcSTCUcGchteIMtQ?e=vnMitq

**Comment by davidnalbandyan1** [comment]
> Verified Repro with Android 11. Repro project available in Maui Triage Teams channel: https://microsoft.sharepoint.com/:u:/t/Mauitriage/EYq8iHpxdiRAjhIFyuTKOocBKSWqnBhcSTCUcGchteIMtQ?e=vnMitq

Hi @shimingsg. I can't access this link. Here is the screenshot attached.
![image](https://user-images.githubusercontent.com/87818513/154216021-855bc221-7a23-49e9-994f-b8bfafdab0e2.png)

**Comment by Redth** [comment]
@jonpryor can your team take a look at this please?

**Comment by jonathanpeppers** [comment]
The attached sample builds for me if I update the package to:

https://www.nuget.org/packages/Xamarin.GooglePlayServices.Base/117.6.0.5

I can also do:

1. `dotnet new maui`
2. Manually edit the `.csproj` for a single `TargetFramework=net6.0-android`
3. `dotnet add package Xamarin.GooglePlayServices.Base --version 117.6.0.5`

@jpobst  or @moljac was there a fix in this area? The above sample as-is fails to build with errors like:

```
obj\Debug\net6.0-android\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(8,52): javac.exe error JAVAC0000:  error: package com
.google.android.gms.common.api.GoogleApiClient does not exist
```

I think we can close and say the solution is to upgrade GPS. Let us know if that doesn't work!

**Comment by moljac** [comment]
> @jpobst or @moljac was there a fix in this area? 

Not directly. No updates, no fixes for weeks.
