### ISSUE TITLE
Is VS 2022 Preview and MAUI in a functional condition?

### ISSUE THREAD

**Issue by tedekeroth** [dotnet/maui#4277]
### Description

As I love the idea of MAUI, I have tried to get started with it. In my attempts, I have found some issues and created issues on github regarding the problems I find ([here](https://github.com/dotnet/maui/issues/4244) and [here](https://github.com/dotnet/maui/issues/4244)), and I seem so keep running into issues that are basically stopping me from doing anything useful at all. This time, I am testing out the [WeatherTwentyOne](https://github.com/davidortinau/WeatherTwentyOne) demo project (for which I also create issues, [here](https://github.com/davidortinau/WeatherTwentyOne/issues/54) and [here](https://github.com/davidortinau/WeatherTwentyOne/issues/55)), and now, I run into another issue that makes it impossible to move on from.

* The demo project has a FlyoutItem defined in App.xaml as well as a TabBar. I wanted to replace the pages that the tab and flyout navigate to, so I added two new ContentPages, LoginPage and DashboardPage.
* * Note: when I create a ContentPage from the context menu (right-clicking on the Pages folder), the Page is created and the `x:Class` is set to `x:Class="WeatherTwentyOne.LoginPage"`, so no `Pages` in there. If I compare to the existing pages in the demo project, the x:Class looks different: `x:Class="WeatherTwentyOne.Pages.HomePage"`
* I then changed the App.xaml slightly, replacing the `page:HomePage` with `page:LoginPage` and the `page:FavoritesPage` with `page:DashboardPage`, thinking that would make me able to see the new pages on device, and use that to design the new page (using HotReload). But instead, this is what happened

> Error	XFC0000	Cannot resolve type "clr-namespace:WeatherTwentyOne.Pages:LoginPage".	
> WeatherTwentyOne	C:\Git\Maui\WeatherTwentyOne\src\WeatherTwentyOne\App.xaml	44	
> 
![image](https://user-images.githubusercontent.com/10088477/150674748-5f759ae3-061e-45c5-9802-0f98562538b7.png)

I also note that the IntelliSense does not detect the new pages:
![image](https://user-images.githubusercontent.com/10088477/150674761-1da10e9d-2f16-4c7e-8cb9-d8c2c3a7e839.png)

The pages are there, even though LoginPage looks a bit off in Solution Explorer:
![image](https://user-images.githubusercontent.com/10088477/150675006-8b9978ac-7ce0-4f9a-8496-637a4e260eb8.png)

Here is the XAML for Dashboard:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:v="clr-namespace:WeatherTwentyOne.Views"
             xmlns:m="clr-namespace:WeatherTwentyOne.Models"
             xmlns:c="clr-namespace:WeatherClient2021"
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="True"
             Title="DashboardPage"
             x:Class="WeatherTwentyOne.Pages.DashboardPage">
    <StackLayout>
        <Label Text="Welcome to .NET MAUI!"
                VerticalOptions="CenterAndExpand" 
                HorizontalOptions="CenterAndExpand" />
    </StackLayout>
</ContentPage>
```

LoginPage XAML
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:v="clr-namespace:WeatherTwentyOne.Views"
             xmlns:m="clr-namespace:WeatherTwentyOne.Models"
             xmlns:c="clr-namespace:WeatherClient2021"
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="True"
             Title="LoginPage"
             x:Class="WeatherTwentyOne.Pages.LoginPage">
    <StackLayout>
        <Label Text="LoginPage"
                VerticalOptions="CenterAndExpand" 
                HorizontalOptions="CenterAndExpand" />
    </StackLayout>
</ContentPage>
```

Also, randomly after I try clean/rebuild, I get a bunch of other errors:
![image](https://user-images.githubusercontent.com/10088477/150676804-49f667c6-c678-4669-9b5b-21a7d7e64fdf.png)

### Steps to Reproduce

See above

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10, Win 10 10.0.19042 Build 19042

### Did you find any workaround?

No.

### Relevant log output

```shell
Build started...
1>------ Build started: Project: WeatherTwentyOne, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>Platforms\Windows\trayicon.ico : warning XA0101: @(Content) build action is not supported
1>C:\Git\Maui\WeatherTwentyOne\src\WeatherTwentyOne\Pages\FavoritesPage.xaml.cs(14,35,14,46): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>C:\Git\Maui\WeatherTwentyOne\src\WeatherTwentyOne\Pages\FavoritesPage.xaml.cs(26,13,26,32): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
1>C:\Git\Maui\WeatherTwentyOne\src\WeatherTwentyOne\Pages\FavoritesPage.xaml.cs(33,16,33,32): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>App.xaml(44,31): XamlC error XFC0000: Cannot resolve type "clr-namespace:WeatherTwentyOne.Pages:LoginPage".
1>Done building project "WeatherTwentyOne.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by yoshiask** [comment]
When you changed the value of `x:Class` in `LoginPage.xaml`, did you also change the namespace in `LoginPage.xaml.cs`?

**Comment by tedekeroth** [comment]
I didnt change the namespace, the namespace is `WeatherTwentyOne`. So, in `LoginPage.aml` I have `x:Class="WeatherTwentyOne.LoginPage"` and in LoginPage.xaml.cs I have `namespace WeatherTwentyOne;`.

**Comment by tedekeroth** [comment]
Ah, I see what you mean, but yes, the namespaces are the same in xaml and cs file. Right now, the values are `x:Class="WeatherTwentyOne.LoginPage"` and `namespace WeatherTwentyOne;`, but I still have the `Cannot resolve type "clr-namespace:WeatherTwentyOne.Pages:LoginPage"`

**Comment by tedekeroth** [comment]
Solved!
Thanks to the pointing from @yoshiask, I now learned something new. I havent really used XAML much at all before (Im backend and WinForms), but the solution was that there was some local variable, `page`, defined in the Application tag in App.xaml, that defined a namespace where the Pages were located, and that variable was then used as a short-hand when the ContentTemplate were defined, like `<ShellContent ContentTemplate="{DataTemplate page:LoginPage}"/>`. Since a few pages were in the `WeatherTwentyOne.Pages` namespace, and others in `WeatherTwentyOne`, that was the confusion.

After moving them all to `WeatherTwentyOne.Pages` and setting the xmlns:page correctly those errors went away (mostly, sometimes they appear, and then after a rebuild, the disappear again)

**Comment by tedekeroth** [comment]
I guess whats left here is to look into why the namespace wasnt automatically set to `WeatherTwentyOne.Pages` when I used the context menu, right-clicking on the `/Pages` folder and creating a new ContentPage there; it should be in namespace `WeatherTwentyOne.Pages.ThePage` instead of `WeatherTwentyOne.ThePage`.

Thanks =)

**Comment by jfversluis** [comment]
Guess this one is solved, thanks for the community power here <3
