### ISSUE TITLE
[Android]Clip property is not working properly in preview 12

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#4285]
### Description

When applying round rectangle geometry clip to the content view , the shape is not rendered properly in Android
![image](https://user-images.githubusercontent.com/92785406/150756281-c65220e3-c564-4102-9665-06f51eae143b.png)

### Steps to Reproduce

1. Run the attached sample
[ClipSample.zip](https://github.com/dotnet/maui/files/7924262/ClipSample.zip)
2. Click the apply effects button,
2. See the output. Triangle with dots occurs instead of the rounded rectangle.
![image](https://user-images.githubusercontent.com/92785406/150756240-586342f4-cadd-4157-a91e-1c845518e30f.png)

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jsuarezruiz** [comment]
Related with  https://github.com/dotnet/maui/issues/4286 and https://github.com/dotnet/maui/issues/4250

**Comment by PaulAnderson02** [comment]
https://github.com/dotnet/maui/issues/3081

**Comment by shimingsg** [comment]
Not reproducible using Android 11 with above project. rounded rectangle deploys.

**Comment by jeya-kasipandi** [comment]
@shimingsg  . It is reproduced and does not display the round rectangle. Can you click the apply effects button to change the round rectangle in the above project? The reported issue will reproduce.
 See the below output
![Screenshot_1645077186](https://user-images.githubusercontent.com/92785406/154414111-c760e877-b0d8-4f78-bf38-26109151ce4e.png)

**Comment by shimingsg** [comment]
@jeya-kasipandi yes, Verified repro with Android 11 and the above project.
