### ISSUE TITLE
[iOS]Clip property is not working properly in preview 12

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#4286]
### Description

When applying round rectangle geometry clip to the content view, the shape is not rendered properly in iOS
![image](https://user-images.githubusercontent.com/92785406/150757902-46605efb-0871-4266-9c14-fec145120816.png)

### Steps to Reproduce

1. Run the attached sample
[ClipSample.zip](https://github.com/dotnet/maui/files/7924262/ClipSample.zip)

2. Click Apply effects button to change the rounded rectangle.

3. See the output. Triangle with dots occurs instead of the rounded rectangle.
![image](https://user-images.githubusercontent.com/92785406/150757919-2a746296-bfcf-4a71-9599-2102287c209e.png)

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by mattscheffer** [comment]
Repro. Used sample shown here with 17.2.0 Preview 1. Simulated iPhone 13 iOS 15.2. 

Doesn't show up as a Triangle with dots anymore. Now just shows up as a normal rectangle as opposed to one with rounded corners.

![image](https://user-images.githubusercontent.com/10537189/154379032-62944e49-099f-4d1f-ba68-80dbafe04e50.png)

**Comment by jeya-kasipandi** [comment]
@mattscheffer Can you click the ApplyEffects button to apply the round rectangle? Triangle with dots will occur instead of the round rectangle? Can you check this?
