### ISSUE TITLE
RefreshView causes NullReferenceException with Shell template

### ISSUE THREAD

**Issue by jfversluis** [dotnet/maui#4287]
### Description

Today I ported the Xamarin.Forms Shell template to .NET MAUI, but as I ran it, it would give me a NullReferenceException. Find my converted template here: https://github.com/jfversluis/MauiShellAppTemplate.

When I comment out the `RefreshView` [here](https://github.com/jfversluis/MauiShellAppTemplate/blob/main/MauiShellApp/Views/ItemsPage.xaml#L17) and trigger the `LoadItemsCommand` manually, it all works.

So, it seems triggering the refresh command through setting `IsBusy` on the `RefreshView` is causing this behavior somehow.

I don't think this is specific to Shell, I just happened to notice it while trying to use this template.

### Steps to Reproduce

1. Clone the repo
2. Run the app
3. Go to the Browse page
4. Observe a NRE without any details

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Tested various platforms and versions, all showed this behavior

### Did you find any workaround?

Don't use the `RefreshView` and trigger the data load manually.

### Relevant log output

Unfortunately no real details are in the logs. Only thing is this:

```
[Choreographer] Frame time is 0.2229 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
[EGL_emulation] app_time_stats: avg=282.10ms min=4.76ms max=1094.18ms count=4
[Choreographer] Frame time is 0.161 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
[Choreographer] Frame time is 0.1261 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
[Choreographer] Frame time is 0.0482 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
Thread started: <Thread Pool> #6
Thread started: .NET ThreadPool Gate #7
Thread started: <Thread Pool> #8
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Intrinsics.dll
Loaded assembly: /data/data/com.companyname.mauishellapp/files/.__override__/System.Runtime.Intrinsics.dll [External]
[EGL_emulation] app_time_stats: avg=75.70ms min=23.77ms max=976.33ms count=24
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt] 
[HostConnection] createUnique: call
[librcm] SocketClient connected to host port 22469
[HostConnection] HostConnection::get() New Host Connection established 0x72b4c3a665d0, tid 9458
[HostConnection] HostComposition ext ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_virtio_gpu_next ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr GL_EXT_texture_compression_bptc GL_EXT_texture_compression_s3tc ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
```

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by plettb** [comment]
Is this fixed?  I was having the same problem, but now, running with VS2022 v 17.2.0 Preview 2.0 the problem seems to be gone.  Did someone miss closing it, or am I deluded? :)
