### ISSUE TITLE
[Windows] Templated IndicatorView not rendering

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4290]
### Description

Templated IndicatorView not rendering.
![indicatorview-template-win-issue](https://user-images.githubusercontent.com/6755973/150788805-8db6ba92-c494-4efb-82b1-88a70a11477f.gif)

### Steps to Reproduce

1. Download [IndicatorViewDemos.zip](https://github.com/dotnet/maui/files/7925760/IndicatorViewDemos.zip)
2. Launch the sample on Windows and navigate to the "Templated IndicatorView" sample. 

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17134.0

**Comment by shimingsg** [comment]
Verified repro with windows and the above project.

**Comment by VSadov** [comment]
The repro project seems to be missing Assets folder. I am getting errors about `Assets\appiconfgSplashScreen.png`. 
Is that available separately?

**Comment by VSadov** [comment]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(33,27): error 0x80070003: Cannot install or update package FF06B2CE-A41F-4DD9-951B-4AC1741CD068_9zz4h110yvjzm because the splash screen image [appiconfgSplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found.	IndicatorViewDemos			
```

Is this caused by something in my setup?
I see `appiconfgSplashScreen.png` referenced in the appxmanifest, but cannot see the file in the project.

**Comment by VSadov** [comment]
All views, including Templated render now.

![image](https://user-images.githubusercontent.com/8218165/157522856-c916767b-8a60-47ca-bebb-9b503e16f97c.png)
