### ISSUE TITLE
[Windows] Crash on SwipeView setting the SwipeMode

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4292]
### Description

Crash on SwipeView setting the SwipeMode
![image](https://user-images.githubusercontent.com/6755973/150789845-849642af-4821-4eb6-873a-9ae886fa9bf1.png)

### Steps to Reproduce

1. Download [SwipeViewDemos.zip](https://github.com/dotnet/maui/files/7925798/SwipeViewDemos.zip)
2. Launch the sample in Windows and navigate to the sample where dynamically change the SwipeMode.

### Version with bug

Preview 12 (current)

### Last version that worked well

Preview 10

### Affected platforms

Windows

### Affected platform versions

Windows App SDK 17134

**Comment by shimingsg** [comment]
Verified repro with windows and the above project.

**Comment by jsuarezruiz** [comment]
Related with https://github.com/microsoft/microsoft-ui-xaml/issues/6571
