### ISSUE TITLE
[Perf] compile most-used type converters

### ISSUE THREAD

**Issue by StephaneDelcroix** [dotnet/maui#4293]
### Description

With compiled XAML, we already have a bunch of type converters bypassed, and replaced by some IL generated at build time.

In the past 2 years, we've added new capabilities, and new type converters, but not all of them have a compiledconverter implementation. We should review the most used ones (Brush, Shapes, ...) and provide an implementation, in order to reduce page loading, mostly on android

### (Public) API Changes

/

### Usage Scenarios

/

### Backward Compatibility

/

### Difficulty

Medium

**Comment by jonathanpeppers** [comment]
I wanted to comment on a couple places we showing up in a `dotnet new maui` template.

Speedscope files: [dotnet-new-maui-7.zip](https://github.com/dotnet/maui/files/9021220/dotnet-new-maui-7.zip)

I posted this in order from most time taken to least.

## Brush

![image](https://user-images.githubusercontent.com/840039/176716579-aba95372-ab98-4280-b1c4-f9a59c670262.png)

Shows up in ILSpy like:
```csharp
val208.set_Property(VisualElement.BackgroundProperty);
val208.set_Value((object)"Transparent");
val208.set_Value(((TypeConverter)new BrushTypeConverter()).ConvertFromInvariantString("Transparent"));
```

https://github.com/dotnet/maui/blob/7c46d43125abb509e5ac2e66ed4eac5a28ac588e/src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml#L66

## Stroke

![image](https://user-images.githubusercontent.com/840039/176717389-f77e5132-0370-4a03-9865-7192323fdae7.png)

ILSpy:

```csharp
val19.set_Property(Border.StrokeShapeProperty);
val19.set_Value((object)"Rectangle");
val19.set_Value(((TypeConverter)new StrokeShapeTypeConverter()).ConvertFromInvariantString("Rectangle"));
```

https://github.com/dotnet/maui/blob/7c46d43125abb509e5ac2e66ed4eac5a28ac588e/src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml#L18

## Point

![image](https://user-images.githubusercontent.com/840039/176717550-e93b3236-bd15-426d-85c5-7f4644dff538.png)

ILSpy:

```csharp
val284.set_Property(Shadow.OffsetProperty);
val284.set_Value((object)"10,10");
val284.set_Value(((TypeConverter)new PointTypeConverter()).ConvertFromInvariantString("10,10"));
```

https://github.com/dotnet/maui/blob/7c46d43125abb509e5ac2e66ed4eac5a28ac588e/src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml#L278

## ImageSource

This one is only 1 call.

![image](https://user-images.githubusercontent.com/840039/176718360-0f37689c-88a2-4a58-b27c-f04a794f29a1.png)

ILSpy:
```csharp
((BindableObject)val).SetValue(Image.SourceProperty, ((TypeConverter)new ImageSourceConverter()).ConvertFromInvariantString("dotnet_bot.png"));
```

https://github.com/dotnet/maui/blob/7c46d43125abb509e5ac2e66ed4eac5a28ac588e/src/Templates/src/templates/maui-mobile/MainPage.xaml#L12-L16
