### ISSUE TITLE
Unable to build any maui apps

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#4294]
### Description

When I used old preview 7, it worked perfectly.  However, when .net 6 came out, everything broke.  Now, I try to build a basic template and it won't even build.

### Steps to Reproduce

1.  Create New Maui Project
2.  Build.

Everytime, it fails to compile (even if i target windows alone).
This means its impossible to create any maui apps.

### Version with bug

Preview 11

### Last version that worked well

Preview 7

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

All platform versions

**Comment by jfversluis** [comment]
Hey @musictopia2 sorry to hear that. However without any error message or logs or any description of what you're seeing and what doesn't work according to you, it is near to impossible to diagnose what is going on here.

Make sure that you uninstall any previous preview that you might have, and freshly install everything through VS2022 v17.1 preview 3 which is the latest at the time of writing this.

Closing this one for now, feel free to add more details and ping me to reopen if you think you have enough to diagnose a potential issue here. 

Thanks!
