### ISSUE TITLE
AmbigousMatchException throwing when a control that inherent from Element is instantiated

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#4300]
### Description

During runtime when the code executes the `new SimplePopup();` call, it throws the `System.Reflection.AmbigousMatchException` in the `InitializeComponent` method, I wasn't unable to go footer but looks like that happened during the `SetBinding` phase.

![image](https://user-images.githubusercontent.com/20712372/150905562-387c708d-7b6d-49a4-bc98-1976cef60004.png)

Here's a better image from the stack trace:
![image](https://user-images.githubusercontent.com/20712372/150905766-79fb59fd-80af-4869-b7f3-cc1f8824e37e.png)

### Steps to Reproduce

Repo: https://github.com/CommunityToolkit/Maui/tree/pj/popup-to-handler

1. Run the MCT sample app
2. On the home page, tap in the last item (Popup)
3. Tap on the first item, (PopupAnchorPage)
4. Tap on the Show button

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.3

### Did you find any workaround?

Create a Csharp page instead.

**Comment by kristinx0211** [comment]
@pictos thanks for your report, but could you check your repro link. it seems missing. if you can provide a sample project/screenshots or more details that we can reproduce your issue, That should greatly speed up the process, thanks!

**Comment by pictos** [comment]
@kristinx0211 there's a link to the repo on my first issue. Let me know if you need anything else

**Comment by kristinx0211** [comment]
@pictos thanks for your update, could you share the link of  your first issue? thanks.

**Comment by pictos** [comment]
@kristinx0211 is here: https://github.com/CommunityToolkit/Maui/tree/pj/popup-to-handler

**Comment by kristinx0211** [comment]
@pictos thanks, but the link is missing, could you confirmed this.

**Comment by kristinx0211** [comment]
Hi @pictos , thanks for your update. Could you give more details about repro steps for `https://github.com/CommunityToolkit/Maui/tree/pj/IElement-bug-repro`

**Comment by pictos** [comment]
@kristinx0211

1. Clone the project
2. Open it
3. Go to [this file](https://github.com/CommunityToolkit/Maui/blob/pj%2FIElement-bug-repro/src/CommunityToolkit.Maui.Core/Interfaces/IPopup.shared.cs)
4. Comment the `using alias`
