### ISSUE TITLE
Define a default namespace for .NET MAUI Blazor controls similar to that of Community Toolkit

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#4303]
### Description

Request to consider defining a default HTTP alias for .NET MAUI Blazor controls similar to that of Community Toolkit so that it becomes easier to manage them while using in XAML code

### Public API Changes

Instead of the complex xmlns definition with clr-namespace and assembly names as shown in the below example, when defined with appropriate HTTP alias this will become easy to manage.

such as `xmlns:b="http://..."`

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:b="clr-namespace:Microsoft.AspNetCore.Components.WebView.Maui;assembly=Microsoft.AspNetCore.Components.WebView.Maui"
             xmlns:local="clr-namespace:MauiBlazorApp"
             x:Class="MauiBlazorApp.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">
    <b:BlazorWebView HostPage="wwwroot/index.html">
        <b:BlazorWebView.RootComponents>
            <b:RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
        </b:BlazorWebView.RootComponents>
    </b:BlazorWebView>
</ContentPage>
```

### Intended Use-Case

Allows for quick definition and better source management.

This will result in quite like the community toolkit definition:

xct="http://xamarin.com/schemas/2020/toolkit"

**Comment by Eilon** [comment]
Sorry I have no idea how these get registered and with who. @Redth - do you know (or know someone who knows) how "default" XAML namespaces show up in VS? Right now for Blazor controls we register the namespace in each XAML file by using its .NET assembly + namespace. But everything else in .NET MAUI is registered by some URI. How do we do that for BlazorWebView?

**Comment by jfversluis** [comment]
Here is how to do it: https://docs.microsoft.com/xamarin/xamarin-forms/xaml/custom-namespace-schemas#defining-a-custom-namespace-schema

**Comment by Eilon** [comment]
@mkArtakMSFT I'm removing the milestone so we can reconsider. It looks like it's 1 line of code in the project, removing some XML from the templates, and then a bit of testing. I think this would be really nice to have and clean up the templates a bit too.

**Comment by jfversluis** [comment]
I'm guessing @StephaneDelcroix might have some ideas on this as well on how to do it best?

What do we actually want to do with this? Could we make it appear like the `BlazorWebView` is just another control in .NET MAUI with this? So just adding `xmlns="http://schemas.microsoft.com/dotnet/2021/maui"` would be enough?

Does a concept like this exist in WPF?

**Comment by StephaneDelcroix** [comment]
@Eilon XmlnsDefinitionAttribute is your friend

**Comment by Eilon** [comment]
> What do we actually want to do with this? Could we make it appear like the `BlazorWebView` is just another control in .NET MAUI with this? So just adding `xmlns="http://schemas.microsoft.com/dotnet/2021/maui"` would be enough?

Yeah I think putting it in the same xmlns as the rest of MAUI would be great. No reason to have another one for 1 control plus a few related types (e.g. `RootComponent`).

> Does a concept like this exist in WPF?

Not sure, but if it does, we should do the same thing (though maybe not in the default xmlns of WPF?).

**Comment by egvijayanand** [comment]
Adding the `BlazorWebView` into the same namespace as other .NET MAUI controls certainly helps in managing a common namespace (added OOB in the template itself). 👍
