### ISSUE TITLE
Crash during navigation with Navigation page

### ISSUE THREAD

**Issue by tmijieux** [dotnet/maui#4306]
### Description

https://github.com/tmijieux/MauiNavigationBug/blob/6b8cd9283ecdcd2bc6e2b0718fd8cccb3f35f98f/App.xaml.cs#L5-L32
I try to do the following navigation pattern in my application (very common in my application)
- add a new page at the bottom of the navigation stack 
- pop to root

The aim is to go to a new page while popping everything that was currently on the stack.
The following code throws 2 exceptions :
- the first one is catched by the catch block
- there is another one that is not catched (like if it was on another thread) and crash the application,
 (there is no absolutely no information about the stack trace on that second exception ... and I do not know why ...)
(EDIT i found out about that second exception see my next answers)

```csharp
namespace MauiApp1;

public partial class App : Application
{
    private NavigationPage _nav;
    public App()
    {
        InitializeComponent();
        _nav = new NavigationPage(new MainPage());
        MainPage = _nav;
    }

    public async void Navigate()
    {
        try
        {
            await NavigateImpl();
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"ex={ex}");
        }
    }

    private async Task NavigateImpl()
    {
        var page = new OtherPage();
        _nav.Navigation.InsertPageBefore(page, _nav.RootPage);
        await _nav.PopToRootAsync(false);
    }
}
```

### Steps to Reproduce

1. clone https://github.com/tmijieux/MauiNavigationBug/commit/6b8cd9283ecdcd2bc6e2b0718fd8cccb3f35f98f
2. launch on android
3. tap the "navigate" button

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (pixel 5 emulator)

### Did you find any workaround?

not yet

### Relevant log output
First exception:
```shell
[0:] ex=System.InvalidOperationException: Previous Navigation Request is still Processing
   at Microsoft.Maui.Platform.StackNavigationManager.ApplyNavigationRequest(NavigationRequest args) in D:\a\1\s\src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs:line 87
   at Microsoft.Maui.Platform.StackNavigationManager.RequestNavigation(NavigationRequest e) in D:\a\1\s\src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs:line 321
   at Microsoft.Maui.Handlers.NavigationViewHandler.RequestNavigation(NavigationViewHandler arg1, INavigationView arg2, Object arg3) in D:\a\1\s\src\Core\src\Handlers\NavigationPage\NavigationViewHandler.Android.cs:line 46
   at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0[[Microsoft.Maui.INavigationView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.NavigationViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v, Object o) in D:\a\1\s\src\Core\src\CommandMapper.cs:line 89
   at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args) in D:\a\1\s\src\Core\src\CommandMapper.cs:line 30
   at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args) in D:\a\1\s\src\Core\src\CommandMapper.cs:line 48
   at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args) in D:\a\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 90
   at Microsoft.Maui.Controls.NavigationPage.Microsoft.Maui.INavigationView.RequestNavigation(NavigationRequest eventArgs) in D:\a\1\s\src\Controls\src\Core\HandlerImpl\NavigationPage\NavigationPage.Impl.cs:line 59
   at Microsoft.Maui.Controls.NavigationPage.SendHandlerUpdateAsync(Boolean animated, Action processStackChanges, Action firePostNavigatingEvents, Action fireNavigatedEvents) in D:\a\1\s\src\Controls\src\Core\HandlerImpl\NavigationPage\NavigationPage.Impl.cs:line 264
   at Microsoft.Maui.Controls.NavigationPage.PopToRootAsync(Boolean animated) in D:\a\1\s\src\Controls\src\Core\NavigationPage.cs:line 238
   at MauiApp1.App.NavigateImpl() in C:\src\MauiApp1\App.xaml.cs:line 31
   at MauiApp1.App.Navigate() in C:\src\MauiApp1\App.xaml.cs:line 19


```
2nd exception (uncatchable somehow...)
```shell
**System.ArgumentOutOfRangeException:** 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'
```

**Comment by J-Swift** [comment]
Same. This crashes with `ArgumentOutOfRangeException`:

```
Navigation.InsertPageBefore(myPage, Navigation.NavigationStack[0]);
Navigation.PopToRootAsync();
 ```
 
 Only tested on Android.

**Comment by J-Swift** [comment]
OK, 2nd update. Its an issue with `Navigation.InsertPageBefore`. I poked through the source a bit and saw one possible cause where we fire off an async operation in the background https://github.com/dotnet/maui/blob/9e46f20af9f2302b15c0baaa0f998a3dd3c10c39/src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs#L358 and that operation is an `async void` https://github.com/dotnet/maui/blob/9e46f20af9f2302b15c0baaa0f998a3dd3c10c39/src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs#L202

Or that might not be the issue, I'm not very familiar with how the code is structured 😄

**Comment by tmijieux** [comment]
@J-Swift, indeed ,  the fact that there is a second uncatchable exception that occurs is very probably due to an async method that is not awaited and that throws. (+ the fact that I do not a get stack trace).
I will also look it up , but if the code is really requiring an async operation in InsertPageBefore then the obvious fix would be to transform that method into an awaitable, (that would be an API inconsistency with xamarin.forms but still a very acceptable solution since maui is an upgrade)

**Comment by J-Swift** [comment]
You could also expose the “busy” status that is checked under the covers to
raise the exception in the first place. But yeah i would prefer the Insert
api to be awaitable if its an async operation

**Comment by tmijieux** [comment]
I think i undestand the problem 
https://github.com/dotnet/maui/blob/2c5ada839f4818272d3ae47f9d3b7547c94a347c/src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs#L357-L359

https://github.com/dotnet/maui/blob/2c5ada839f4818272d3ae47f9d3b7547c94a347c/src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs#L199-L202

The call to SendHandlerUpdate here, is a "fire and forget" of the async void method because it assumes (as said
in the comment) that the InsertPageBefore and RemovePage methods will not update the current view and that the implementation will actually not transmit navigation information to native stack. 

But actually if you are on RootPage and insert a page just below root page you need to make the backbutton appear and the reverse is also true, if there is two page in the stack and remove the one below to top , you will need to make the backbutton disappear, so the assumption that this methods needs not update the view is false.

By example, I think this was assumed the handler would use some kind of "fast exit" path like this one.
https://github.com/dotnet/maui/blob/2c5ada839f4818272d3ae47f9d3b7547c94a347c/src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs#L115-L126

I just setup my sample alongside existing samples in the maui repository to be able to have breakpoints in the maui code, and it actually get past this condition (it is false, so the code does not return here) so I think past this point the "native" stack will be updated.

I was also able to catch the exception in the debug session when building mauicode because of VS breaking when throwing exception and it is happening here:
https://github.com/dotnet/maui/blob/2c5ada839f4818272d3ae47f9d3b7547c94a347c/src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs#L83-L109

line 92:
-  newStack is of length 2
-  InternalChildren is only of length 1 
- i=1 (second item)

![image](https://user-images.githubusercontent.com/518039/151707958-acd91ab9-129f-4924-871f-c4aeb249ad35.png)

**Comment by tmijieux** [comment]
https://github.com/dotnet/maui/blob/2c5ada839f4818272d3ae47f9d3b7547c94a347c/src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs#L85-L95

I think there also may be a bug a line 89-91 because if `InternalChildren.Count == i`  then the condition line 89 is false and the condition in `else if` line 91 still throws because you can only index up to `Count-1`

this would maybe fix that ArgumentOutOfRangeException but I am not sure this address the root problem, because here newStack have 2 while maui stack have 1 and the end result the stack is supposed to have one so it still looks like that navigation event from the InsertPageBefore is ticking after the PopToRootAsync.

**Comment by tmijieux** [comment]
that : https://github.com/tmijieux/maui/commit/navigationAwait (changing InsertBeforePage and RemovePage apis to return Task)  seems to prevent the crash but at the cost of modifying the apis the alternatives being either  
- changing the implementation in order that they are fully synchronous, 
- proposing another apis or viable workaround  to achieve the same logic ...
- some other idea that i did not think of ?

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by J-Swift** [comment]
@tmijieux did you submit a PR for your changes? I really think the API needs to be updated to be await-able. Honestly, the more I think about it, the weirder it is to me that they aren't already.
