### ISSUE TITLE
[Android] AppShell navigation - Table View - Java.Lang.IllegalStateException

### ISSUE THREAD

**Issue by Phil4121** [dotnet/maui#4307]
### Description

I'm currently playing around with .Net Maui. I've created my demo App with .Net Maui Prev. 10. Since the beginning I'm using AppShell navigation. 
After upgrade to Prev. 12 I encountered the following problem:

This is a snippet from my AppShell where I call my UserSettingsPage:

    <FlyoutItem
        Title="Settings"
        Icon="menu_icon.png"
        IsEnabled="{Binding IsBusy, Converter={mctConvert:InvertedBoolConverter}}">
        <ShellContent ContentTemplate="{DataTemplate settings:UserSettingsPage}" Route="UserSettingsPage" />
    </FlyoutItem>

If I'm navigating to my UserSettingsPage everything is working fine as long as I put my TableView into a ScrollView like this:

    <ContentPage
        x:Class="DeepBlue.Pages.Settings.UserSettingsPage"
        xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:viewmodels="clr-namespace:DeepBlue.ViewModels.Settings"
        Title="{Binding Title}"
         x:DataType="viewmodels:UserSettingsViewModel">
        <ScrollView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
            <TableView Intent="Settings">
                <TableRoot>
                    <TableSection Title="Settings">
                        <ViewCell>

But if I remove the ScrollView I immediate get the following exception: 
**Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'**

So I leave the TableView inside the ScrollView and tried a few other things. If I try to call DisplayPrompt on my UserSettingsPage after the user clicked a ViewCell the same exception is thrown again.

    var answer = await Application.Current.MainPage.DisplayPromptAsync("Delete Account",
                            "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                            "Delete",
                            "Cancel",
                            keyboard: Keyboard.Text);

I'm sure in .Net Maui Prev. 10 this call didn't cause any problems.

### Steps to Reproduce

1. Create a .Net Maui App
2. Add AppShell navigation
3. Link to a ContentPage with Table View

### Version with bug

Preview 12 (current)

### Last version that worked well

Preview 10

### Affected platforms

Android

### Affected platform versions

Android 11

### Relevant log output

```shell
[nyname.DeepBlu] JIT allocated 76KB for compiled code of void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
[AssistStructure] Flattened final assist data: 4048 bytes, containing 2 windows, 34 views
**Java.Lang.IllegalStateException:** 'The specified child already has a parent. You must call removeView() on the child's parent first.'
```

**Comment by warpedgeoid** [comment]
I am also seeing this when testing an app built using Shell. As @Phil4121 suggested, I wrapped my TableView in a ScrollView and as a workaround.

**Comment by VincentBu** [comment]
Hi @Phil4121 & @warpedgeoid , would you like to give a sample project for us to repro?
