### ISSUE TITLE
The App using Shell always have App Name as default title.

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#4310]
### Description

The App using Shell always have App Name as default title. Although I set the title on AppShell as well as on MainPage in the reproduction but still the Title always remain the AppName. 

### Steps to Reproduce

Navigate to a page through Shell. The title of the navigated page will be the name of the App. 
[BugSample.zip](https://github.com/dotnet/maui/files/8031158/BugSample.zip)

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11.0- API 30

### Did you find any workaround?

Even TitleView does not resolve the issue. Hide NavigationBar with Shell.SetNavBarIsVisible(this, false); and Create your own view.

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.
