### ISSUE TITLE
Preview 12 and VS 2022 for Mac

### ISSUE THREAD

**Issue by dmccolloughOneGas** [dotnet/maui#4313]
### Description

Preview 12 with VS 2022 for Mac produces error "application launch did not return a valid pid or a launch error"

### Steps to Reproduce

I'm trying to run a file new project for .Net Maui using Preview 12 on my Mac with Visual Studio for Mac 2022 Preview 17.0 build 5186.

App was created with the cli using this command:
dotnet new maui -n SampleAppName

I can select a iOS simulator, iPhone 13 Pro Max iOS 15.2, click the play button, it compiles the app. Launches the simulator, installs the app, then I get a message in the application output saying that the "Application launch did not return a valid pid nor a launch error".

I can successfully launch the app into the simulator and have it run if I use the cli command
dotnet build <ProjectName>.csproj -t:Run -f net6.0-ios

Any suggestions on why I'm getting the not a valid pid nor a launch error when I try and launch using VS 2022 for Mac Preview?

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15

### Did you find any workaround?

I have not found a workaround.

**Comment by lhughey** [comment]
This is similar to the error posted here https://github.com/dotnet/maui/issues/3961
In both cases, the app can be run via command line, but not with VS Mac 2022

**Comment by jfversluis** [comment]
Visual Studio for Mac does not have support for .NET MAUI at this time. Keep your eye on their releases for when it's there! For now you can run the apps through the command-line or use the Comet VS Code extension to make your life a bit easier :)
