### ISSUE TITLE
Update arcade dependency for Preview 11 release branch and rebuild / release 6.0.1xx workloads / packs

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#4319]
Update arcade dependency for Preview 11 release branch and rebuild / release 6.0.1xx workloads / packs.

**Comment by jonathanpeppers** [comment]
I think we could put an empty commit on the preview 11 release branches, and the latest yaml-templates would get picked up?

https://github.com/xamarin/yaml-templates/commit/187da5eb2d64319573021ab424d6c2d9a585e2e3

@pjcollins does that sound right?

**Comment by pjcollins** [comment]
That shoulds correct to me, assuming all the branches are referencing yaml-templates/main (which I believe they are). I don't have all of the context for this, is there a reason this is only needed for preview 11 and not other branches? Do we only need this fix https://github.com/dotnet/arcade/pull/8330, or do we need something newer as well?

**Comment by jonathanpeppers** [comment]
Preview 11 shipped alongside .NET 6 GA, so I think that is the reason they need this.

Preview 12 only shipped with a preview 6.0.200 SDK, so 6.0.200 will be fixed by the next Preview 13 release.

**Comment by rolfbjarne** [comment]
So just to confirm: I put an empty commit here: https://github.com/xamarin/xamarin-macios/commits/release/6.0.1xx-preview11, and that's it?

**Comment by pjcollins** [comment]
Yeah that should be all that is needed on the build side, though I'm not sure what distribution needs to happen after that. I assume we'll need to push the new packages to NuGet.org, but will we also need to put them into VS?

**Comment by rolfbjarne** [comment]
Done: https://github.com/xamarin/xamarin-macios/commit/a000c8f3a699eed304585fde6266bf430f75a12e

**Comment by jfversluis** [comment]
This is a couple of previews old now, is this still needed?

**Comment by jonathanpeppers** [comment]
I think the .NET SDK team basically just removed optional workloads from 6.0.102? to solve this problem. Since MAUI Preview 14 requires 6.0.200, that seemed like the easiest fix.

I think we can close this.
