### ISSUE TITLE
Native iOS Application Build broken when referencing iOs libraries

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#4334]
### Description

iOS build is not able to find the dll's produced by the referenced library projects.

When building the iOS application project it outputs the following 

> CSC : error CS0006: Metadata file 'C:\XXXXXX\obj\Debug\net6.0-ios\iossimulator-x64\ref\C1.iOS.Core.dll' could not be found.

But the library produced the dll in the folder "bin\Debug\net6.0-ios"

There are a couple extra folders "iossimulator-x64\ref" in the path

### Steps to Reproduce

I couldn't reproduce this in a separate project

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
