### ISSUE TITLE
DisplayAlert crashes an app if executed in a page constructor

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/maui#4336]
### Description

DisplayAlert crashes an app if executed in a page constructor

```
public partial class MainPage: ContentPage
{
        public MainPage()
        {
            InitializeComponent();
            DisplayAlert("Hello", "There", "OK");
        }
}
```

### Steps to Reproduce

1. Create a new MAUI app
2. Add DisplayAlert call to the MainPage constructor
3. Start the app and observe the app to crash on startup

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041

### Did you find any workaround?

Yes, if you execute the same method with a delay, it works just fine

```
public partial class MainPage: ContentPage
{
        public MainPage()
        {
            InitializeComponent();
            RenderDialog();
        }

        private async Task RenderDialog()
        {
            await Task.Delay(5000);
            await DisplayAlert("Hello", "There", "OK");
        }
}
```

### Relevant log output

```shell
Faulting application name: xxx.exe, version: 1.0.0.0, time stamp: 0x61954b73
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650
Exception code: 0xc000027b
Fault offset: 0x000000000010b362
Faulting process id: 0x6390
Faulting application start time: 0x01d812fb09610291
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: cc7145cf-2475-4e26-bdf6-e57bb709e481
Faulting package full name: 0A8834C6-F23D-4CEB-86B5-B57FD5D15D23_1.0.0.0_neutral__9zz4h110yvjzm
Faulting package-relative application ID: App
```

**Comment by jamesmontemagno** [comment]
Any reason you don't put it in the OnAppearing? This seems like a bad user experience as you can create a page at any time and it may not be visible at all.

I actually don't think this should be supported IMHO.

**Comment by Eilon** [comment]
Dup of https://github.com/dotnet/maui/issues/1514
