### ISSUE TITLE
Support configurability in opening external URLs

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#4338]
### Description

Based on discussion in https://github.com/dotnet/maui/pull/4268#discussion_r790667344.

> Later on I think our goal from security review was to ensure that you can't navigate to external content in the app's webview by default, and that developers would explicitly have to configure or override something to allow that.

We may want to add an explicit option which permits opening external webpages in the browser. 

### Intended Use-Case

Open a link to a parcel courier service in the browser for a package being tracked.

**Comment by codemonkey85** [comment]
I've been seeing an issue where attempting to open external URLs in a Blazor hybrid app for iOS causes crashes. Is this related by any chance? https://github.com/dotnet/maui/issues/3980#issuecomment-1030198360
