### ISSUE TITLE
OnPlatform markup extension defines properties for platforms no longer supported

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#4350]
### Description

The `OnPlatform` markup extension defines properties for platforms that aren't supported in MAUI: GTK, UWP, WPF. At the moment the markup extension reports WinUI as being UWP.

I suppose it's connected to a wider issue that some cleanup is required in multiple places so that MAUI reports a sensible value for WinUI apps.

### Steps to Reproduce

Run this sample: https://github.com/davidbritch/dotnet-maui-samples/tree/main/XAML/MarkupExtensions

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041

**Comment by shimingsg** [comment]
Verified repro with Windows  and the above project.

**Comment by PureWeen** [comment]
This should be fixed by

https://github.com/dotnet/maui/pull/4548
