### ISSUE TITLE
OnIdiom markup extension gets the Windows form factor wrong

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#4351]
### Description

The OnIdiom markup extension thinks my WinUI app is running on a tablet, rather than desktop:

```
<BoxView Color="{OnIdiom Phone=Red, Tablet=Green, Desktop=Blue" ... />
```

### Steps to Reproduce

Run this sample: https://github.com/davidbritch/dotnet-maui-samples/tree/main/XAML/MarkupExtensions

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041

**Comment by kristinx0211** [comment]
verify repro on windows. repro sample:
[#4351.zip](https://github.com/dotnet/maui/files/8168500/4351.zip)

**Comment by PureWeen** [comment]
This should be fixed by the following PR
https://github.com/dotnet/maui/pull/4548

If not we can re-open
