### ISSUE TITLE
Error `Workload ID android-aot isn't supported on this platform.` on Windows

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#4363]
### Description

`dotnet build src\DotNet\DotNet.csproj` && `dotnet cake --target=VS-NET6` yield error:

```
C:\Users\taparik\dev\maui\src\DotNet\DotNet.csproj(158,5): error MSB3073: The command ""C:\Users\taparik\dev\maui\bin/dotnet/dotnet" workload install android-aot --skip-manifest-update --verbosity diag --temp-dir "C:\Users\taparik\dev\maui\bin/temp/" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json"" exited with code 1.
```

Running the command itself yields `Workload ID android-aot isn't supported on this platform.`

### Steps to Reproduce

`dotnet build src\DotNet\DotNet.csproj` && `dotnet cake --target=VS-NET6` yield error:

Following steps in https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md#net-6 on Windows 11

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

11

**Comment by TanayParikh** [comment]
Note; using global `dotnet` instead doesn't result in this error:

```
dotnet workload install android-aot --skip-manifest-update --verbosity diag --temp-dir "C:\Users\taparik\dev\maui\bin/temp/" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json
>> "


Successfully installed workload(s) android-aot.
```

However this doesn't resolve the issue as using global dotnet with the `dotnet build src\DotNet\DotNet.csproj` && `dotnet cake --target=VS-NET6` commands still yields this error.

**Comment by TanayParikh** [comment]
Using the local dotnet (within the maui repo), even `android` isn't supported. Something odd is going on:

```
./bin/dotnet/dotnet workload install android ios maccatalyst tvos macos maui wasm-tools `
>>    --from-rollback-file https://aka.ms/dotnet/maui/main.json `
>>    --source https://aka.ms/dotnet6/nuget/index.json `
>>    --source https://api.nuget.org/v3/index.json
Workload ID android isn't supported on this platform.
```

**Comment by rmarinho** [comment]
can you list the sdk's installed ?

**Comment by Redth** [comment]
Please try installing MAUI with the latest Visual Studio 17.2 preview.

Also I believe android-aot is no longer a separate workload.
