### ISSUE TITLE
Fix how our ViewHandler exposes out INativeViewHandler.NativeView and cleanup GetWrappedNativeView

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#4366]
### Description

Currently on our platform specific `ViewHandler` classes, the implementation of `INativeViewHandler` is returning the `ContainerView` for the `NativeView`

https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/View/ViewHandlerOfT.Windows.cs#L11-L12

This feels like it defeats the purpose of having the two properties. This also makes it so our code can "safely" retrieve the `WrapperView` via the `NativeView` property and then add that to something like a layout but this will cause a different implementation of  INativeViewHandler` to fail.

For example, if you were to take one of our handlers that has a `ContainerView` the following code would run fine

```C#
layout.Add((viewHandler as INativeViewHandler).NativeView)
```

But now if someone else implements `INativeViewHandler` and doesn't return the `ContainerView` for `NativeView` then that code will crash or act in an unexpected way.

### (Public) API Changes

# Proposals

- Change `INativeViewHandler` to return the actual `ContainerView` for the `ContainerView` and the "Wrapped" View for the `NativeView` 
- Or just remove `ContainerView` from `INativeViewHandler` and just make the `Container` concept an implementation detail of the Handler itself. With this implementation we'd just keep `NativeView` as returning the `ContainerView`
- We also currently have two extension methods, `ToNative()` and `GetWrappedView`, that both do the same thing. We should just stick to one.

### Usage Scenarios

N/A

### Backward Compatibility

N/A

### Difficulty

Low

**Comment by Clancey** [comment]
We should not be returning the container view for the NativeView. You are correct, that defeats the purpose.  We should just use GetWrappedNativeView() when adding something to the native view stacks

**Comment by Redth** [comment]
I think we need:

- `ContainerView` - returns container or milk if it is not wrapped 
- `NativeView` - the actual typed view expected, never the container
- `GetWrappedNativeView() => ContainerView ?? NativeView;`
