### ISSUE TITLE
Maui preview 4.0 when try to realease application show error 

### ISSUE THREAD

**Issue by vplife1** [dotnet/maui#4369]
### Description

I have used Visual studio 2022 preview 4.0 MAUI.I want to realse my application .When my application go on realse mode its show following error
[ "Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'D:\Projects\obj\project.assets.json' doesn't have a target for 'net6.0-android'. Ensure that restore has run and that you have included 'net6.0-android' in the TargetFrameworks for your project.	TorpeduMobile	C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	
"](url) 

How can i resolve this issue please Guide me .

### Steps to Reproduce

1)update MAUI preview 2.0 to 4.0
2)Try to realse a app show error message 
3)Im not able to realse a app

### Version with bug

Preview 12 (current)

### Last version that worked well

Preview 12 (current)

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

no

### Relevant log output

```shell
no
```

**Comment by shimingsg** [comment]
Not reproducible with Android 11. you should check your file .csproj to make sure there has include 'net6.0-android' in frameworks from your error log.
