### ISSUE TITLE
The MAUI app project template does not target windows out-of-the-box

### ISSUE THREAD

**Issue by Dbquity** [dotnet/maui#4374]
### Description

Following the [steps](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app) to create a MAUI app, I get a project that does not target windows:
![image](https://user-images.githubusercontent.com/25459675/151542690-db9e1180-9016-4402-a7a1-127e48092c52.png)

### Steps to Reproduce

1. Create a new project using the ".NET MAUI App (Preview)" template
2. open dependencies in the solution explorer

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

I don't know how to see the version of the project templates - or how to update those other than when updating VS itself

### Did you find any workaround?

I can fix this in the project file by removing the xml comments around this line
```
<!-- <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks> -->
``` 
and changing this section
```xml
<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
    <!-- Required - WinUI does not yet have buildTransitive for everything -->
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0-experimental1" />
    <PackageReference Include="Microsoft.WindowsAppSDK.Foundation" Version="1.0.0-experimental1" />
    <PackageReference Include="Microsoft.WindowsAppSDK.WinUI" Version="1.0.0-experimental1" />
    <PackageReference Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="1.0.0-experimental1" NoWarn="NU1701" />
    <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.0.26-experimental1" />
</ItemGroup>

```
to 
```xml
<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
    <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.0.30" />
</ItemGroup>
```

**Comment by Dbquity** [comment]
This issue was prompted by the comments in #3625

**Comment by jfversluis** [comment]
I think you need to update your templates, this has not been the default for a while now. To clarify: the recent versions of templates have Windows enabled by default for a couple of previews already.

For some reason the templates aren't updated nicely with Visual Studio, you can update them manually at this time by running the following command in a terminal window: `dotnet new -i Microsoft.Maui.Templates`

Also check this portion of a video by James for more info: https://www.youtube.com/watch?v=ugem4UbAtC0&t=672s

**Comment by Dbquity** [comment]
Thanks @jfversluis !

Seems the comment in the second line below is no longer needed...
```xml
<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
    <!-- Required - WinUI does not yet have buildTransitive for everything -->
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
    <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.0.30" />
</ItemGroup>
```

**Comment by jfversluis** [comment]
I think so. I think ultimately we can do without these explicit references and it will be implied by adding .NET MAUI to your project, but it seems WinUI hasn't implemented something like that yet... But I might be mistaken.

Why you ask?

**Comment by Dbquity** [comment]
I was merely curious - half expecting an explanation along the lines you just gave :-)
Thanks again for a very quick answer!
(my next step is to try publishing to windows - and I will be following your bullet 4 from #4329)

**Comment by jfversluis** [comment]
Let me know how that one goes!
