### ISSUE TITLE
Button Background on WinUI only updates after you move the cursor off the Button

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#4386]
### Description

If you change the background of a button while the mouse is over it the color won't update until you move the cursor off the Button

### Steps to Reproduce

Paste the following code into the Sandbox project.
Click the button
Color should change to Green right when you click on it but it only changes to Green once you move your mouse off the button

```C#
protected override Window CreateWindow(IActivationState activationState)
{
	Button button = null;
	button = new Button()
	{
		Background = SolidColorBrush.Purple,
		Command = new Command(() =>
		{
			if ((button.Background as SolidColorBrush).Color == SolidColorBrush.Purple.Color)
			{
				button.Background = SolidColorBrush.Green;
			}
			else
			{
				button.Background = SolidColorBrush.Purple;
			}
		}),
		Text = "Button that does call Mapper"
	};

	return new Window(
		new ContentPage
		{
			Content = new VerticalStackLayout()
			{
				button
			}
		});
}
```

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WinUI

**Comment by kristinx0211** [comment]
verified repro on window 10.0.19041. repro demo:
[#4386.zip](https://github.com/dotnet/maui/files/8160683/4386.zip)

**Comment by TJClifton90** [comment]
I am also seeing this behaviour with the same repro steps.

**Comment by hartez** [comment]
Just tried this with 17.4 stable, and the button changes color immediately. Seems to have been fixed.
