### ISSUE TITLE
Proposal: Disable Microsoft.Extensions.Logging by default in Release builds

### ISSUE THREAD

**Issue by eerhardt** [dotnet/maui#4394]
### Description

In profiling a default .NET Maui application, I noticed a decent amount of time is spent initializing Microsoft.Extensions.Logging. We configure some default logging providers here:

https://github.com/dotnet/maui/blob/27380ddcde911c4ca4729986a7581981dd8b9c04/src/Core/src/Hosting/MauiAppBuilder.cs#L231-L268

This code was copied and modified from `HostingHostBuilderExtensions.ConfigureDefaults`, which was intended for service applications, like web servers or Windows Services.

In a non-Windows application, we are configuring logging filters and the "Debug" logger, which doesn't do anything unless a Debugger is attached. This is unnecessary logic and code in deployed / Release-built client applications. We should remove this by default. And instead, developers can opt-in to enabling logging in their applications, if they need it.

### Public API Changes

No public API changes.

But I think we should adjust the default templates to add something like:

```C#
#if DEBUG
        builder.Logging.AddDebug();
#endif
```

### Intended Use-Case

I would like my Maui apps to start faster by default.

I prototyped removing the logging and along with https://github.com/dotnet/maui/issues/4393, this resulted in a 13% faster starting `dotnet new maui` app on my Android emulator.

**Comment by eerhardt** [comment]
cc @Redth @mattleibow @PureWeen - thoughts?

**Comment by Redth** [comment]
Agreed.  The default is faster, and it's still obvious in the template how to enable it if you really want to pay the fee.
