### ISSUE TITLE
WinUI AutoSizeInitializesCorrectly test is failing

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#4399]
### Description

Run WinUI tests and you will see that the Editor (TextChanges) test is failing.

It looks like if you add the layout to the actual window then everything starts measuring out correctly and the test passes

### Steps to Reproduce

Run WinUI tests and you will see that the Editor (TextChanges) test is failing.

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WinUI

**Comment by kristinx0211** [comment]
Editor (TextChanges) for me here just fine. 
https://user-images.githubusercontent.com/99457000/156107535-97ad9158-a963-4e23-a1a9-f5b7f52e7579.mp4
**code snippet:**
`    <Grid>
        <Editor  Text="hi" BackgroundColor="Green" AutoSize="TextChanges" ></Editor>
    </Grid>`

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/pull/4970
