### ISSUE TITLE
Cannot change Android SDK version from 31 to a lower one.

### ISSUE THREAD

**Issue by vladimirmazarakis** [dotnet/maui#4404]
### Description

I've tried everything, and except for that there are literally zero information on this topic. (Understandable)

### Steps to Reproduce

Create a new project, and try to set the compile sdk (TargetFrameworkVersion) to 21 for example.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android - 31

### Did you find any workaround?

Didnt find any information.  In the logs you can see that even when I deleted the API I could not get the required result.

### Relevant log output

```shell
error XA5207: Could not find android.jar for API level 31. This means the Android SDK platform for API level 31 is not installed. Either install it in the Android SDK Manager (Tools > Android > Android SDK Manager...), or change the Xamarin.Android project to target an API version that is installed. (D:\Android\android-sdk\platforms\android-31\android.jar missing.)
```

**Comment by Redth** [comment]
Can I ask why you are trying to change the compile version lower?  I don't believe we support compiling against < 30, but in general you should compile against the highest API level available (so 31 now).

Compiling against 31 does not mean you can only run on 31+ devices, it's just the available build/compile time API surface used.  You'll need to watch that if you do want to run against older API's you use runtime checks in your code around API's unavailable on the lower API levels.

For example, you can ensure your app will install and run on API 21 devices and newer with:
```
<SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net6.0-android'">21.0</SupportedOSPlatformVersion>
```

If you are using API's unavailable before API 28 for example, you'd guard your code with a runtime check like this: `OperatingSystem.IsAndroidVersionAtLeast(28)`.

**Comment by vladimirmazarakis** [comment]
Hmm... for some reason the MAUI build does not run on Android. (Tried on 2 phones on none of those it did install properly). The absolutely same setup worked for Xamarin.Forms.

**Comment by vladimirmazarakis** [comment]
Anyways, I got your point, and I am closing the issue. Thanks for help!
