### ISSUE TITLE
NavigationPage.HasBackButton property not working in Windows 11

### ISSUE THREAD

**Issue by JongHoon023** [dotnet/maui#4407]
### Description

Hello Maui Team!
I found a bug while trying to use Maui for the first time.
If you run the build after setting the `NavigationPage.HasBackButton` property to `False`, there is a problem that the BackButton exists.

(I am not good at English, so please understand that I am writing this with a translator)
<img width="351" alt="image" src="https://user-images.githubusercontent.com/38038052/151699278-bb16e2d2-84a3-46b5-ba07-06e8de6e4d9b.png">

### Steps to Reproduce

1. Create MainPage.xaml
2. Use to ContentPage
3. NavigationPage.HasBackButton="False" in ContenPage
4. Run to Build

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 Pro 21H2 22000.469

**Comment by PureWeen** [comment]
This should be fix on P13
