### ISSUE TITLE
MAUI Projects do not show platform specific .cs C# code files except for the first TFM in the TargetFrameworks list

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#4410]
### Description

(From: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1468324)

We previously added all the `Platforms/[platform]/**/.*.cs` files to `None` item group for the non-current TFM's so they would still show up in the Solution Tree in Visual Studio.

This apparently caused issues with the project system and caused weird entries to show up in the .csproj when files were added/moved/removed. (https://github.com/dotnet/maui/commit/94b145fe42c98560da9bf967a5a51414ae4703e1)

We removed this, but now the files no longer show up for the non-current TFM inside the solution tree.

The suggestion is to add back our `<None Include..` logic but to do so in a target that will run after CPS does the initial evaluation and it should no longer confuse things.

 - Does this target need any Before/After/DependsOn targets? If so, which?

### Steps to Reproduce

N/A

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

*

**Comment by jonathanpeppers** [comment]
I think this is fixed by: https://github.com/dotnet/maui/pull/4411
