### ISSUE TITLE
Label control's text attribute does not handle non-english alphabet characters, and it throws XamlCTask error

### ISSUE THREAD

**Issue by atlasy97** [dotnet/maui#4412]
### Description

This is successfully compiled
![image](https://user-images.githubusercontent.com/67227671/151719402-87ac7398-5bfc-41a4-9e17-d543d728bfd7.png)

But when using accented letters it no longer compiles, and throws "XamlCTask task failed" error message (nothin else has been cahnged)
![image](https://user-images.githubusercontent.com/67227671/151719426-c13dbdf3-62ca-4355-a7f0-560ee18e00d2.png)

### Steps to Reproduce

1. Create a new MAUI app
2. add label control or edit existing
3. add accented letters to the "Text" attribute e.g. űáéíúóüö
4. it will not compile with such letters, but do so with English letters

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

WinSDK: 10.0.17763.0  AndroidSDK: 21.0

**Comment by StephaneDelcroix** [comment]
I'm looking at this. as a workaround, escaping the special characters should work

**Comment by StephaneDelcroix** [comment]
I'm not able to reproduce this. it might be a file encoding issue (btw, your file is missing the `<?xml version="1.0" encoding="UTF-8"?>` processing instruction)

could you please creates the smallest possible reproduction project that triggers this issue ? thx

**Comment by atlasy97** [comment]
Yes saving it with UTF-8 encoding solves it. In other c# frameworks I have not experienced this. Is it possible that in the future the startup project is UTF-8 as default?

**Comment by Redth** [comment]
#4495 only added these for one of the templates.

@StephaneDelcroix  can you please open another PR that fixes the other templates as well?

**Comment by sou1maker** [comment]
In the case where <?xml version="1.0" encoding="UTF-8" ?> is added to the Shell template, using non-English comments will also cause this error to occur.

![image](https://user-images.githubusercontent.com/58240137/152725339-fc852176-821f-4612-8b5d-f5984cb00405.png)

ContentPage no problem.

![image](https://user-images.githubusercontent.com/58240137/152725578-2fb1129f-add3-4346-9d97-fe368f8f300f.png)

**Comment by StephaneDelcroix** [comment]
@sou1maker could you check if the file encoding is different on those files ? (using `file`, or even NotePad)

**Comment by sou1maker** [comment]
> @sou1maker could you check if the file encoding is different on those files ? (using `file`, or even NotePad)

Sorry, it is my fault. It should be caused by the encoding format you said. I restarted the build and found that the error could not be reproduced, it must be that I got the encoding format wrong when using another editor

**Comment by StephaneDelcroix** [comment]
not especially your fault. we ned to make sure iles are created, and saved with the right encoding, using vs
