### ISSUE TITLE
Linear gradient brushes throws an exception in XAML Editor.

### ISSUE THREAD

**Issue by nicksilverstein** [dotnet/maui#4414]
### Description

I tried the sample from your docs:
https://docs.microsoft.com/en-us/dotnet/maui/user-interface/brushes/lineargradient

It throws an error in the XAML Editor

### Steps to Reproduce

I just did a dotnet new maui from macOS Terminal.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15

**Comment by StephaneDelcroix** [comment]
what error does this throws ? is it happening in the IDE (which IDE, version, ...), at compile time from both the IDE and the CLI, or at runtime ?

**Comment by nicksilverstein** [comment]
How do you compile on macOS with cli?

**Comment by nicksilverstein** [comment]
This is the error I'm getting:
Error: XLS0503: A value of type 'GradientStop' cannot be added to a collection or dictionary of type 'GradientStopCollection'. (TestPI) IntelliSense

and it's VS2022 for Mac.

**Comment by shimingsg** [comment]
@nicksilverstein what error does this throws ?

**Comment by kristinx0211** [comment]
Verified Repro with iPhone 13 pro max IOs 15.2 and above docs.

**Comment by mgoertz-msft** [comment]
Odd, no issues here with a blank project for the latest MAUI:

![image](https://user-images.githubusercontent.com/14282894/155816097-f0c540d9-ac2d-41e5-a035-391532c63658.png)

**Comment by kristinx0211** [comment]
@mgoertz-msft close the project and reopen, the errors is showing.
![image](https://user-images.githubusercontent.com/99457000/157163110-bb910848-3fb8-420b-aa3c-822020c2a277.png)

**Comment by mgoertz-msft** [comment]
@kristinx0211 Thank you! I did get it to repro easily on my latest internal VS installation.

@Redth This is another case of duplicate types with the same name in different CLR namespaces but the same MAUI xmlns:
* https://github.com/dotnet/Microsoft.Maui.Graphics/blob/main/src/Microsoft.Maui.Graphics/GradientStop.cs
* https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/GradientStop.cs

Why do we need/have two GradientStops?

**Comment by Redth** [comment]
Fixed in https://github.com/dotnet/Microsoft.Maui.Graphics/pull/347 and will be included in an upcoming release.
