### ISSUE TITLE
Slider size not displaying properly inside a Frame

### ISSUE THREAD

**Issue by Avalyah** [dotnet/maui#4415]
### Description

The slider size is not as expected when placed inside a frame. With the following code:

`<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">

    <StackLayout Background="#111111" >
        <Frame HasShadow="True" Margin="10" CornerRadius="10" BackgroundColor="#222222">
            <StackLayout Spacing="30">
                <Grid ColumnDefinitions="30,*">
                    <Label Text="R" FontSize="Medium"  TextColor="White" />
                    <Slider GridLayout.Column="1" MinimumTrackColor="Red" ThumbColor="Red" MaximumTrackColor="#AAAAAA" />
                </Grid>
                <Grid ColumnDefinitions="30,*">
                    <Label Text="G" FontSize="Medium" TextColor="White" />
                    <Slider GridLayout.Column="1" MinimumTrackColor="#7FFF00" ThumbColor="#7FFF00" MaximumTrackColor="#AAAAAA" />
                </Grid>
            </StackLayout>
        </Frame>
    </StackLayout>
</ContentPage>`

The resulting app looks like this:
![result](https://user-images.githubusercontent.com/10262935/151759684-d0fa1ee5-9186-41ae-8901-7db75671aa2a.PNG)
Changing a property in the xaml while the app is running fixes the issue temporarily, here I set the grid background to green and both sliders resized automatically:
![result2](https://user-images.githubusercontent.com/10262935/151759782-a40d8bf0-bd39-4c5d-a113-66f62571c59e.PNG)
However, when the app is restarted, it looks again like this:
![result3](https://user-images.githubusercontent.com/10262935/151759825-97a79c0c-e902-40fe-887c-7a939b2137ed.PNG)

### Steps to Reproduce

1. Create a fresh MAUI multiplatform app in VS2022 Preview.
2. Input the following code to the body of main page:

`<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">

    <StackLayout Background="#111111" >
        <Frame HasShadow="True" Margin="10" CornerRadius="10" BackgroundColor="#222222">
            <StackLayout Spacing="30">
                <Grid ColumnDefinitions="30,*">
                    <Label Text="R" FontSize="Medium"  TextColor="White" />
                    <Slider GridLayout.Column="1" MinimumTrackColor="Red" ThumbColor="Red" MaximumTrackColor="#AAAAAA" />
                </Grid>
                <Grid ColumnDefinitions="30,*">
                    <Label Text="G" FontSize="Medium" TextColor="White" />
                    <Slider GridLayout.Column="1" MinimumTrackColor="#7FFF00" ThumbColor="#7FFF00" MaximumTrackColor="#AAAAAA" />
                </Grid>
            </StackLayout>
        </Frame>
    </StackLayout>
</ContentPage>`

3. Run the app.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by shimingsg** [comment]
Not reproducible with Android 11.
