### ISSUE TITLE
.NET MAUI Class Library project not generating Windows targeted library when built from the command line using dotnet build

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#4418]
### Description

.NET MAUI Class Library project not generating `Windows` targeted library when built from the command line using dotnet build command.

### Steps to Reproduce

1. The below steps are applicable only on a Windows machine as the issue is wrt to Windows target library
2. Open the terminal and navigate to the folder where you've read/write access
3. Create a new .NET MAUI Class Library using the command `dotnet new mauilib`
4. The project created from the default template is multi-targeting by default, hence don't need to change anything
5. Build the project using the command-line option `dotnet build`
6. Navigate to the project's output folder `bin\Debug` folder, you won't find the target folder for Windows
7. And that's the issue, now open the same project in VS2022 and build it, now the Windows target would get generated

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All Windows versions

### Did you find any workaround?

The condition mentioned in the project file needs to be tweaked for the multi-targeting scenario to work as expected in Windows.

**Comment by Redth** [comment]
Thanks, this is currently not supported: https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj#L5

We conditionally do not include the windows TFM when using dotnet build as WindowsAppSDK currently requires building with full framework MSBuild.  This will eventually be implemented in WindowsAppSDK.

**Comment by egvijayanand** [comment]
Hi Jonathan,

Have raised this issue for .NET MAUI Class Library project, but you’ve provided reference from .NET MAUI App template‘s project file.

Actually speaking, there’s no WindowsAppSDK reference in the class library project default template.

In this scenario, this issue definitely makes sense.

Regards,
Vijay Anand E G

Regards,
Vijay Anand E G
________________________________

**Comment by jeromelaban** [comment]
Related to https://github.com/microsoft/WindowsAppSDK/issues/1652

**Comment by egvijayanand** [comment]
Hi Jonathan,

I’m running the latest templates that correspond to Preview 12. And have even an issue open regarding templates not getting updated as part of VS install, but that’s a different story.

I understand the issue with building Windows AppSDK using dotnet build command but that’s not the scenario I’m referring to.

My point is that the default class library project template is not referencing Windows AppSDK. Can be included if necessary.

And the library that I built doesn’t need either, and my build is automated using dotnet build command. In this scenario, Windows targeted library is not getting generated.

This should have been the case for all your internal projects if the same template is being used.

Say a project that’s on top of MAUI and some P/Invoke for Windows all put together as one library using this template will not generate the expected output.

Regards,
Vijay Anand E G
________________________________
