### ISSUE TITLE
MSB4018	The "XamlCTask" task failed unexpectedly.

### ISSUE THREAD

**Issue by JusterZhu** [dotnet/maui#4420]
### Description

System : WIN10 Professional 19042.1415
Visual studio Version : 17.1.0 Preview 4.0
SDK: net6.0-windows10.0.19041

![image](https://user-images.githubusercontent.com/11714536/151791446-b8713456-a804-4650-8572-b4e8351e27ff.png)

If the above code is removed, the bug will disappear.

![image](https://user-images.githubusercontent.com/11714536/151791692-621c5080-1cda-4dd2-964f-37b05f176353.png)

### Steps to Reproduce

1.run the 'windows machine'
2.Run the following code ↓

`<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">

    <ScrollView>
        <StackLayout Orientation="Vertical">
            <ListView ItemsSource="{Binding MyLst}">
                
            </ListView>
            <Button Text="我是Btn" WidthRequest="200" HeightRequest="50" Command="{Binding}"></Button>
            <Label Text="我是Label" TextColor="Red" FontSize="Title" ></Label>
            <CheckBox IsChecked="True"></CheckBox>
            <Image Source="dotnet_bot.svg"></Image>
            <ImageButton Source="dotnet_bot.svg" HeightRequest="30" WidthRequest="100" CommandParameter="{Binding}" Command="{Binding}"></ImageButton>
            <Entry Text="我是输入框" WidthRequest="100" HeightRequest="30"></Entry>
            <TableView HasUnevenRows="true">
                <TableView.Root>
                    <TableSection TextColor="Red" Title="TextCell Disable">
                        <TextCell TextColor="Red" Text="txtCellDisable1" Detail="test" IsEnabled="false" />
                        <TextCell TextColor="Red" Text="txtCellDisable2" Height="25" IsEnabled="false" />
                    </TableSection>
                    <TableSection TextColor="Red" Title="TextCell Enable">
                        <TextCell TextColor="Red" Text="txtCellEnable1" Detail="test" IsEnabled="true" />
                        <TextCell TextColor="Red" Text="txtCellEnable2" Height="25" IsEnabled="true" />
                    </TableSection>
                    <TableSection TextColor="Red" Title="TextCell ContextActions Disable">
                        <TextCell TextColor="Red" Text="txtCellDisableContextActions1" Detail="test" IsEnabled="false">
                            <TextCell.ContextActions>
                                <MenuItem  Text="More" />
                                <MenuItem  Text="Delete" />
                            </TextCell.ContextActions>
                        </TextCell>
                    </TableSection>
                    <TableSection TextColor="Red" Title="TextCell ContextActions Enable">
                        <TextCell TextColor="Red" Text="txtCellEnabledContextActions1" Detail="test" IsEnabled="true">
                            <TextCell.ContextActions>
                                <MenuItem  Text="More" />
                                <MenuItem Text="Delete" IsDestructive="true" />
                            </TextCell.ContextActions>
                        </TextCell>
                    </TableSection>
                </TableView.Root>
            </TableView>
        </StackLayout>
    </ScrollView>
</ContentPage>
`

### Version with bug

Preview 12 (current)

### Last version that worked well

Preview 12 (current)

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041

**Comment by JusterZhu** [comment]
If only put two buttons in StackLayout no problem.

![image](https://user-images.githubusercontent.com/11714536/151793098-23c9da71-2eec-4cf1-a760-1c8acbcc01c3.png)

**Comment by shimingsg** [comment]
Verified repro with windows10.0.19041 and the above project.

**Comment by JusterZhu** [comment]
> 

got it.

**Comment by rmarinho** [comment]
fixed by #4851

**Comment by ewendeng** [comment]
哥们，我也碰到了一样的问题，我还用的是中文版本的。我试出来的了，一个新模板，只要有个中文字它就无法识别，会出现这个Bug。
Hi,guys. 
I has same problem that writing chinese charater in xaml .
