### ISSUE TITLE
Getting issue when trying to open a new window

### ISSUE THREAD

**Issue by slnsvr** [dotnet/maui#4426]
### Description

var secondWindow = new Window {
    Page = new MySecondPage {
        // ...
    }
};

Application.Current.OpenWindow(secondWindow);

This is throwing unhandled exception at run time. In the eventvwr I can see the below exception.. 
Faulting application name: MauiSampleAppPreview4_3.exe, version: 1.0.0.0, time stamp: 0x61954b73 Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650. Kindly suggest.

### Steps to Reproduce

1. VS  preview 2022 17.1 preview 4 -> File -> New MAUI App
2. In the default OnCounterClicked method, at last, added below line of code.
Application.Current.OpenWindow(new Window { Page = new NewPage1() });
3. On clicking on "Click me" button, at run time, its throwing unhandled exception at the above line.

In the eventvwr I can see the below exception.. 
Faulting application name: MauiSampleAppPreview4_3.exe, version: 1.0.0.0, time stamp: 0x61954b73 Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650. Kindly suggest.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows10 Pro

### Did you find any workaround?

No

**Comment by Luminisc** [comment]
+1, got same issue

**Comment by jarig** [comment]
+1 the same here
Version 17.1.0 Preview 6.0
Microsoft.AspNetCore.Components.WebView.Maui 6.0.200-preview.12.852

> Microsoft Visual Studio Professional 2022
Version 17.1.0 Preview 6.0
VisualStudio.17.Preview/17.1.0-pre.6.0+32203.90
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Professional
Visual C++ 2022   00476-80000-00000-AA928
Microsoft Visual C++ 2022
.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL
ASP.NET and Web Tools 2019   17.1.357.57307
ASP.NET and Web Tools 2019
ASP.NET Web Frameworks and Tools 2019   17.1.357.57307
For additional information, visit https://www.asp.net/
Azure App Service Tools v3.0.0   17.1.357.57307
Azure App Service Tools v3.0.0
Azure Functions and Web Jobs Tools   17.1.357.57307
Azure Functions and Web Jobs Tools
C# Tools   4.1.0-3.22075.3+592501cbb9c9394072a245c15b3458ff88155d85
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.
Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
Microsoft Library Manager   2.1.161+abc97ecc7d.RR
Install client-side libraries easily to any web project
Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers
Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards
Microsoft Visual Studio Tools for Containers   1.2
Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package
Mono Debugging for Visual Studio   17.1.10 (65f98f5)
NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
Razor (ASP.NET Core)   17.0.0.2206201+62a2c1d6162f828801565a7ca26d9d48b810a05b
Provides languages services for ASP.NET Core Razor.
SQL Server Data Tools   17.0.62201.12090
Microsoft SQL Server Data Tools
TypeScript Tools   17.0.1229.2001
TypeScript Tools for Microsoft Visual Studio
Visual Basic Tools   4.1.0-3.22075.3+592501cbb9c9394072a245c15b3458ff88155d85
Visual F# Tools   17.1.0-beta.21610.4+07b5673e4f2fa7630e78abe37f16b372353a7242
Microsoft Visual F# Tools
Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
Visual Studio Container Tools Extensions   1.0
Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
VisualStudio.DeviceLog   1.0
Information about my package
VisualStudio.Foo   1.0
Information about my package
VisualStudio.Mac   1.0
Mac Extension for Visual Studio
Xamarin   17.1.0.309 (d17-1@3f96c58)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin Designer   17.1.0.87 (remotes/origin/main@d50fb5635)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
Xamarin Templates   17.1.8 (590388a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
Xamarin.Android SDK   12.2.0.4 (d17-1/19b97b7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a5d1934
    Java.Interop: xamarin/java.interop/d17-1@7ac33610
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.37.1@0893b3b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7
Xamarin.iOS and Xamarin.Mac SDK   15.6.0.3 (caa899d24)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by VSadov** [comment]
This works with the current main branch.
