### ISSUE TITLE
Showstopper for those that use MongoDB Realm nuget package (and maybe others)

### ISSUE THREAD

**Issue by ShaneBridges** [dotnet/maui#4427]
### Description

Hello, 
I'm converting a fully working Xamarin Forms app which uses Mongo Db Realm (https://www.nuget.org/packages/Realm/).  For some reason, everything works with MAUI on Windows.  However, on Android (using a real device or the emulator), I get a DllNotFoundException when trying to initialize Realm.  I haven't tried it on iOS yet.  Anyway, it's as if the required libraries are not being copied to the device.  I'm using Visual Studio 2022 Community Preview 4, .Net Maui Preview 12 and Windows 11.

At this point, I can't move forward with converting this app to .NET MAUI until this problem is fixed.  I assume it's not a package issue since it works on XF just fine on all devices.  Thanks for any tips on how to resolve this.

-Shane 
![Untitled](https://user-images.githubusercontent.com/7467558/151852926-7a792bd0-aff9-4a7e-9cb8-83e71741983c.png)

### Steps to Reproduce

Create a new .NET Maui App via the VS template, add the Realm nuget package, and add the following 4 lines of code in MainPage.xaml.cs or App.cs.  The exception occurs on the last line of the constructor:

`
using Realms.Sync;

...
		AppConfiguration config = new("carom_app-vyzkd"); // you can use this value for testing...it's a sample Mongo app id.
		Realms.Sync.App.Create(config);  // DllNotFoundException "realm.wrappers"
`

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android (API 30+), possible iOS.

### Did you find any workaround?

Not yet.

**Comment by Redth** [comment]
I think you're going to need to work with Realm on this one, as the exception throws inside their constructor.

Though it may work on Xamarin.Forms, that doesn't unfortunately mean it will work smoothly on .NET 6.  The library authors will need to investigate.

**Comment by ShaneBridges** [comment]
Thank you for the quick response!  I originally thought it may be a Realm issue but when I change my (.Net 6 MAUI) target to "Windows Machine" it runs just fine on my desktop.  It seems like a build issue where the realm-wrappers library is not being bundled with the APK so it can't find it at run time.  I also noted the following warning when building under Android:

Warning		XA4301: APK already contains the item lib/x86_64/librealm-wrappers.so; ignoring.

To me, it seems like a build/package issue with VS 2022 Preview 4.  Thoughts?

Thanks!
Shane

**Comment by Redth** [comment]
Again, it’s hard to say since we aren’t the package authors. Its possible that something has changed in packaging which they need to account for, but nothing immediately comes to mind. 

@jonathanpeppers any ideas?

Ultimately this is really something Realm needs to debug, and isn’t really within our scope to be looking at without more context or bug reports from them.

**Comment by jonathanpeppers** [comment]
I don't think there is enough information here to know what's wrong. What is the full stack trace of the exception? What `.dll` file is missing?

Setting `adb shell setprop debug.mono.log all` and getting [adb logcat](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log) output would tell us more.

I agree someone from Realm needs to look into this, and we can help if needed.

**Comment by ShaneBridges** [comment]
Thanks for the responses so far.  It appears that it cannot find "realm-wrappers.dll".  I've attached the stacktrace and logcat output.  I guess I'm stuck on the fact that it works when I switch the target to Windows but for Android it can't seem to find and load the Realm library file(s).  I compared the output APKs  (Xamarin vs MAUI) and as far as Realm goes, the same librealm-wrappers.so is there in both APKs.  I assume that file should contain everything Realm would need but I've never had to dig into the output APK to figure out an issue.

At any rate, I will reach out to the Realm team.  Thanks!

[stacktrace.txt](https://github.com/dotnet/maui/files/7982609/stacktrace.txt)
[logcat.txt](https://github.com/dotnet/maui/files/7982610/logcat.txt)

**Comment by nirinchev** [comment]
Hey folks, Nick from Realm here. Looks like it's a matter of reshuffling the nuget package and putting the native binaries in the correct place for the .net6 tooling. Definitely an issue on our end and we'll sort it out soon-ish as we're planning to work toward adding MAUI support this quarter.

**Comment by Redth** [comment]
Thanks @nirinchev for updating this thread.  Do you have an issue on your repo we can link this one to for anyone who sees this as well?

**Comment by nirinchev** [comment]
Hm, I thought GitHub will automatically generate a reverse link when an issue is mentioned in another repo, but I guess not this time. In any case, here's the issue on our end: https://github.com/realm/realm-dotnet/issues/2802

**Comment by Redth** [comment]
Thanks! Closing here.

**Comment by ShaneBridges** [comment]
Thanks - I anxiously await the fix :)
