### ISSUE TITLE
Validate correct target for XAML/CSS injection and platform folder adjustments

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#4431]
### Description

We have used the `GenerateMSBuildEditorConfigFileShouldRun` target as a base for both the `_MauiInjectXamlCssAdditionalFiles` and the `_MauiRemovePlatformCompileItems` targets. 

Is this the correct one going forward, or is `CoreCompile` a better option? How does this impact XAML steps?

**Comment by StephaneDelcroix** [comment]
iirc, CoreCompile was too late, as MauiXaml items eventually have to be added to EmbeddedResources. @jonathanpeppers might know better
