### ISSUE TITLE
Attached debugger doesn't stop on startup exceptions

### ISSUE THREAD

**Issue by javiercn** [dotnet/maui#4440]
### Description

When trying to debug an app that throws a startup exception, the debugger doesn't pause on the exception and instead it prompts visual studio to open a new instance.

![image](https://user-images.githubusercontent.com/6995051/151962951-0a0f9a5f-9ddf-461e-bb29-152026f7a5f7.png)

### Steps to Reproduce

```csharp
public static MauiApp CreateMauiApp()
{
    ...
    throw new InvalidOperationException("Startup exception");
}
```

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

No

### Relevant log output

```shell
Exception thrown: 'System.InvalidOperationException' in BlazorMauiAppSample.dll
The program '[13100] BlazorMauiAppSample.exe: Program Trace' has exited with code 0 (0x0).
The program '[13100] BlazorMauiAppSample.exe' has exited with code 3221226107 (0xc000027b).
```
```

**Comment by drasticactions** [comment]
What happens if you try that on a WinUI app that doesn't use MAUI? Or if you throw that exception inside of the WinUI Project when it starts up?

**Comment by shimingsg** [comment]
Not reproducible with windows.
