### ISSUE TITLE
[Blazor webview] Exception handling for blazor webview

### ISSUE THREAD

**Issue by javiercn** [dotnet/maui#4441]
We have several issues that touch different aspects of the same area:

https://github.com/dotnet/maui/issues/3695
https://github.com/dotnet/maui/issues/2057
https://github.com/dotnet/maui/issues/2598

Since these aspects are deeply related, this issue supersedes the other mentioned issues and provides some details on the expected behaviors:
* Unhandled exceptions on a Blazor Webview should be treated in the same way as unhandled exceptions in other platforms.
  * Raising up to the "AppDomain" "UnhandledException" event in Winforms and WPF before terminating the application.
  * Using the same mechanism Maui offers for dealing unhandled exceptions.
* We should consider a "standard" way to display errors across platforms to aid in development scenarios. One option here is to use the `Details` and `Summary` html elements to provide additional details during development. This would follow the same pattern we use in other platforms via the `DETAILEDERRORS` config value.

General expectations around exception types:
* Un-awaited task throws: 
  * These should unwind the stack and be handled at the platform level. Blazor doesn't have any insight into these exceptions and can't react to them.
* Render exception:
  * These flow up to `Renderer.HandleException` where they need to get rethrown for the general exception handling mechanism from the platform to kick in.
* Event handler exception: These are handled by Blazor in the same way across different platforms and already flow to `Renderer.HandleException`
* JSInterop exceptions: These should unwind the stack and be handled at the platform level.
* Exceptions while bootstrapping the Blazor Webview: These should unwind the stack and be handled at the platform level, for example, DI exceptions when failing to resolve a service.
* Caught exceptions within component code:
  * These are only visible through capturing first-chance exceptions in the debugger as Blazor doesn't get visibility into them (they are caught).
  * Our own components shouldn't contain any of these types of exceptions, however in general, these exceptions are not "flavor" specific and also affect Webassembly and desktop.

**Comment by TanayParikh** [comment]
[Support has been added](https://github.com/dotnet/aspnetcore/pull/40765) for WPF/WinForms and needs to be consumed by dotnet/maui, by consuming aspnetcore 6.0.4 packages.

For dotnet/MAUI there isn't a global exception management capability. I've created https://github.com/dotnet/maui/issues/5535 to track adding support for this.

**Comment by TanayParikh** [comment]
Pushing to RC3 as we're awaiting release of the 6.0.4 SDK which has the https://github.com/dotnet/aspnetcore/pull/40765 fix.

**Comment by TanayParikh** [comment]
This is now working in maui main for WPF/WinForms. Closing this issue out, further efforts for first class MAUI support will be tracked via https://github.com/dotnet/maui/issues/5535.
