### ISSUE TITLE
[WinUI, Shell] Convert bottom tabs on WinUI Shell to using HierarchicalNavigationItems

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#4448]
### Description

When shell was first constructed by @dotMorten it didn't have the concept of [hierarchical navigation](https://docs.microsoft.com/en-us/windows/apps/design/controls/navigationview#hierarchical-navigation)

So the implementation currently just uses a custom WinUI grid with buttons as a set of bottom tabs

![MicrosoftTeams-image](https://user-images.githubusercontent.com/5375137/151990881-74efd06f-29ae-4bfb-bd69-08a73ea0a6ac.png)

This implementation made sense at the time and does cause it to match mobile platforms but now that the `NavigationView` supports hierarchical navigation we should express the bottom tabs using that feature.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/5375137/151991266-9a3add9b-d590-4368-ae6a-7c61c4165705.png)

That would mean that the `Xaminals` example above would instead express the menu as all top level tabs
- Domestic
  - Cat
  - Dogs
- Monkeys

### (Public) API Changes

None

### Usage Scenarios

N/A

### Backward Compatibility

Shell is currently experimental in Xamarin.Forms so none of the API/structure was really finalized. This change will break anyone that likes or prefers the bottom tabs. At a later point we are planning on adding additional API so users could customize the TabBar and place it where they'd like to

### Difficulty

Medium

**Comment by jamesmontemagno** [comment]
I believe this makes a lot of sense. In the .NET Podcasts app we actually specify a different Shell layout for Mobile and Desktop so I think this makes sense and would even streamline that.

How about for macOS? can we align there as well?
