### ISSUE TITLE
 Visual Studio 2022 Preview Version 17.1.0 Preview 4.0 Create new project does not scaffold all of the dependencies correctly

### ISSUE THREAD

**Issue by mobycorp** [dotnet/maui#4449]
### Description

I have Visual Studio 2022 Preview Version 17.1.0 Preview 4.0 installed and when I try to use VS to scaffold a new MAUI project from the Create a new project/.NET MAUI (Preview) option, the project does not get created with all of the necessary components. Namely, the net6.0-windows10.0.19041 is missing. Also, when I run maui-check, it tells me that the .NET SDK (6.0.200) is not installed.  I answer the prompt to install it and I get this weird message saying it cannot install this on my system (Windows 11 Pro with the latest updates - I know as my system rebooted after the update last night...).

![image](https://user-images.githubusercontent.com/60759137/152007305-ba3afe2a-be90-4242-a8bb-3a8fc295c405.png)

The odd thing is it says it is trying to install a 16-bit version. Went to the appdata\temp\... folder and ran the executable manually and confirmed the issue...

With all that said, when I scaffold a new project using dotnet new maui from the command line it installs with all of the dependencies properly.  There is something broken in the current version of VS Preview.

### Steps to Reproduce

1. Open Visual Studio Preview v10.1.0 Preview 4.0
2. Create new project .NET MAUI (Preview)
3. The net6.0-windows10.0.19041 will be missing
4. Run maui-check - when it fails to find the .NET SDK 6.0.200 it will fail with the error shown in the screenshot above

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Dependency net6.0-windows10.0.19041

### Did you find any workaround?

Workaround: run **dotnet new maui** from the command line.  The project created this way has all of the necessary dependencies.

**Comment by Rabosa616** [comment]
I´ve succeed to update to latest maui version and run a maui project for windows and android, here you have my steps:

dotnet nuget locals all --clear
Uninstall all workloads one by one
dotnet workload list <-- that returned me all the workloads (if you see any android-aot, remove it the first one and then proceed with the rest)
dotnet workload uninstall <Name of the Workload>
Install the workloads again:
dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --from-rollback-file https://aka.ms/dotnet/maui/preview.12.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json --no-cache
Open Visual Studio and create a brand new Maui project
Run! worked
Note: I experienced issues with the old examples on windows, I´ve fix them by opening the Package.appxmanifest and remove all the "Assets" before any image
I have Visual Studio 2022 Preview Version 17.1.0 Preview 5.0 installed

**Comment by mobycorp** [comment]
When I did a dotnet new -i Microsoft.Maui.Templates Visual Studio 2022 Preview created the correct Maui template.

I consider this issue to be closed.
