### ISSUE TITLE
Renaming all things Native --> Platform

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#4451]
### Description

'Native' has long been a term used across various technologies. In Xamarin, the term has been used to refer to to describe platform-specific features that pertain to the individual platforms supported (i.e. Android, iOS, Mac, Windows).

We now understand that 'native' is not an appropriate term to use, and it is one of the various widely used terms that are not inclusive. Therefore, we will be replacing all instances of 'Native' to 'Platform'.

While we are leaning towards "Platform", a fuller list of replacement words to consider include:
- platform
- platform-specific
- framework
- built-in
- unmanaged
- core
- feature

This change is inspired by learnings from https://github.com/jonathanpeppers/inclusive-code-comments/pull/33. This change has also already been made in Graphics

### Public API Changes

Replace all instances of "Native" to "Platform" in this repo.

A quick search of the maui repo reflects 11353 instances of "Native" across 1495 files.

### Intended Use-Case

To use more inclusive language in our codebase.

**Comment by rachelkang** [comment]
This is not necessarily a quick find and replace!

We must be mindful of nuanced scenarios - for example, we don't want "alternative" to become "alterplatform" :p

**Comment by mattleibow** [comment]
I think this is done now.
