### ISSUE TITLE
Localization via satellite assemblies doesn't work for android when the app built in debug mode.

### ISSUE THREAD

**Issue by nevse** [dotnet/maui#4470]
### Description

If I run app in debug mode `dotnet build -t:Run -f:net6.0-android` it doesn't show translated message. For `dotnet build -t:Run -f:net6.0-android -c:Release` it does.
Project to reproduce - https://github.com/nevse/Maui-Tests-Localization1
![debugVsRelease](https://user-images.githubusercontent.com/1169410/152153995-2c4d55e6-f1b8-4f0a-ab33-86e8705cfd25.png)

### Steps to Reproduce

1. create app `dotnet new maui -n HumanaizerTests`
2. add references 
```
<ItemGroup>
        <PackageReference Include="Humanizer.Core" Version="2.14.1" />
        <PackageReference Include="Humanizer.Core.de" Version="2.14.1" /> 
</ItemGroup>
```
3. change culture to `de` and use Humanizer to read data localization resources
```
CultureInfo.CurrentCulture = CultureInfo.CurrentUICulture = new CultureInfo("de");

CounterLabel.Text = DateTime.UtcNow.AddHours(-2).Humanize();
```
4. run the app in debug `dotnet build -t:Run -f net6.0-android` and release mode `dotnet build -t:Run -f:net6.0-android -c:Release`

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by AntonKosenkoDX** [comment]
Hello, we are developing [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/) and experienced the same issue. This issue has a Normal priority for us but we don't have a workaround. Thank you for your help.

**Comment by AntonKosenkoDX** [comment]
@jsuarezruiz Hello! Any update on this issue?

**Comment by tranb3r** [comment]
Hello,
Any update ?
In https://github.com/xamarin/xamarin-android/issues/2012, @jonathanpeppers said it should "just work" in .net6.
However, it still does not look like it works on maui, neither with .net6 nor .net7, right ?

**Comment by tranb3r** [comment]
Any update on this issue ? Thanks

**Comment by jonathanpeppers** [comment]
I think @dellis1972 is going to look into this one.
