### ISSUE TITLE
[Bug] Shadow effect not showing in WinUI

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#4471]
### Description

Used ICanvas.SetShadow for draw shape shadow effect. But in android, given shadow showing correctly, in WinUI given shadow effect not showing. Please check and update possible solution. 

```
<ContentPage.Resources>
        <ResourceDictionary>
            <local:GraphicsDrawable x:Key="GraphicsDrawable" />
        </ResourceDictionary>
    </ContentPage.Resources>

    <VerticalStackLayout VerticalOptions="End">
        <GraphicsView
                x:Name="GraphicsView"
                HeightRequest="500"
                WidthRequest="500"
                Drawable="{StaticResource GraphicsDrawable}"/>
    </VerticalStackLayout>
```

```
public class GraphicsDrawable : IDrawable
{
	public void Draw(ICanvas canvas, RectangleF dirtyRect)
	{
		canvas.SaveState();


		canvas.FillColor = Colors.CornflowerBlue;
		canvas.SetShadow(new SizeF(50, 50), 5, Colors.Grey);
		canvas.FillRectangle(50, 100, 50, 50);

		canvas.RestoreState();
	}
}
```

**Outputs**
Android:

![image](https://user-images.githubusercontent.com/32541057/152165006-716c6cdb-524a-4bdb-8cc0-830ef04f2ff9.png)

WinUI:

![image](https://user-images.githubusercontent.com/32541057/152165324-82f45629-f664-4437-a4f5-7e5b0e22cc63.png)

### Steps to Reproduce

1. Run the sample
2. See the shadow effect showing in android but not showing in WinUI. 

Sample: 
[ShadowIssue.zip](https://github.com/dotnet/maui/files/7986931/ShadowIssue.zip)

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

**Comment by MuneeshKumarG** [comment]
Any update in this?

**Comment by shimingsg** [comment]
Verified repro with windows and the above project.

**Comment by VSadov** [comment]
Looks fixed in recent main. Works fine for me.

**Comment by VSadov** [comment]
![image](https://user-images.githubusercontent.com/8218165/160189326-32855606-e254-41d0-bc84-33a12422fc50.png)
