### ISSUE TITLE
Shadows disappear after navigating to different page

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/maui#4480]
### Description

Shadow added to grid, when I navigate to another page then go back, the shadow is gone.
_(only tested android)_

https://user-images.githubusercontent.com/6544051/152245747-2854379e-4c71-4f4b-a8a2-e2a669fca3b2.mp4

### Steps to Reproduce

Repo -
[ShadowRepo.zip](https://github.com/dotnet/maui/files/7990382/ShadowRepo.zip)
 

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
@IeuanWalker Thank you so much for your bug report! But we cannot reproduce your issues with the provided project, there are some errors. Can you help double check, and re-upload a repro project.
![image](https://user-images.githubusercontent.com/97647558/156120155-85138ae2-b771-4441-ab1f-eb0f078204ba.png)

**Comment by kristinx0211** [comment]
verified repro on Android 11 and above project.
