### ISSUE TITLE
Project Template to use existing Blazor wasm hosted project as input for BlazorWebview

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#4486]
### Description

Currently we have Blazor MAUI Template where we can build/compose new project using Blazor skills.
There are instance where we just need to deploy existing Blazor wasm hosted app on Appstore or Playstore without any modification.
Can we have a project template, wherein if we add the reference to existing Blazor wasm hosted project it runs that on mobile platforms ?

### Public API Changes

none

### Intended Use-Case

Ability to Publish the existing Blazor Wasm hosted project to run from Mobile Platform. In this case we don't need to change any functionality of the existing Blazor Wasm App, but provide the ability for that app to also run from android, iOS Platforms.

Looks like this should be an easy win, as i was able to have it point to existing Blazor wasm app, but looks like it is not executing the from Blazor wasm program.cs

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Due to the simplicity of the process for hosting a Blazor Web app in a Blazor MAUI project it doesn't make sense to roll out a new project template due to its maintenance cost.
