### ISSUE TITLE
Android Labels don't overflow

### ISSUE THREAD

**Issue by Clancey** [dotnet/maui#4487]
### Description

If you set a labels font too large, or a strings length is too long, the text disappears.  Along this line, Multi line labels do not work properly.

### Steps to Reproduce

File new app, set labels font too large.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All Platforms

**Comment by mattscheffer** [comment]
Not repro anymore in 17.2.0 Preview 1. Emulator used is Pixel 5 (Android 11)

At a slightly large font, you can see text size overflow to additional lines:
![image](https://user-images.githubusercontent.com/10537189/154371170-f0f975a7-3c93-49a3-99c5-6a8900480fd3.png)


Text still appears at unreasonable sizes. I set the font size to 2000 here and the text shows up. Although it takes forever to scroll.
![image](https://user-images.githubusercontent.com/10537189/154370962-a95540f1-0390-4eab-b645-d99078a6b50f.png)

Increasing the string length at mor normal font lines has it overflow to appropriate lines as well:

![image](https://user-images.githubusercontent.com/10537189/154371466-ee6e17f3-6995-4493-ba2d-94cdc96def3b.png)

**Comment by shimingsg** [comment]
Verified Repro with Android11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EbuPpLFPS5BApkZdSXndy7IBvCAk0pGTr-dxNEnK1JpL8g?e=IaI7GD
