### ISSUE TITLE
SQLite in MAUI App not working on iOS

### ISSUE THREAD

**Issue by RaspeR87** [dotnet/maui#4490]
### Description

I firstly use **SQLite-net-plc** package to connect my MAUI app to SQLite database.
Everything works OK on Android phone, but I got error on iOS. I got error which is mentioned and still not resolved here: https://github.com/dotnet/maui/issues/3211

Then I want to make this works by official Microsoft package EFCore SQLite: **Microsoft.EntityFrameworkCore.Sqlite**
Everything works OK again only on Android and not on iOS. What's wrong? I think this is critical issue, because feature to connect to database is necessary on MAUI platform.
I started with this official Xamarin EFCore tutorial (https://docs.microsoft.com/en-us/ef/core/get-started/xamarin) and rewrite it to my view how this could work in MAUI.

### Steps to Reproduce

1. Create new .NET MAUI App or .NET MAUI Blazor App
2. Create Model named Blog.cs:
```
    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
    }
```
3. Create DBContext class named BloggingContext:
```
    public class BloggingContext : DbContext
    {
        public BloggingContext(DbContextOptions<BloggingContext> options) : base(options)
        {
            try
            {
                SQLitePCL.Batteries_V2.Init();

                this.Database.EnsureCreated();
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }

        public DbSet<Blog> Blogs { get; set; }
    }
```
4. Inside MauiProgram class you have to register DBContext:
a) Example for .NET MAUI Blazor App:
```
        public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.RegisterBlazorMauiWebView()
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
			});

		string dbPath = Path.Combine(FileSystem.AppDataDirectory, "blogs.db3");
		builder.Services.AddDbContext<BloggingContext>(options => options.UseSqlite($"Filename={dbPath}"));

		builder.Services.AddBlazorWebView();
		builder.Services.AddSingleton<WeatherForecastService>();

		return builder.Build();
	}
```
b) Example for .NET MAUI App:
```
        public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
			});

		builder.Services.AddSingleton<MainPage>();

		string dbPath = Path.Combine(FileSystem.AppDataDirectory, "blogs.db3");
		builder.Services.AddDbContext<BloggingContext>(options => options.UseSqlite($"Filename={dbPath}"));

		return builder.Build();
	}
```
5. You have to work with something in your database:
a) Example for .NET MAUI Blazor App - add this lines into index.razor:
```
@code {
    protected override async Task OnInitializedAsync()
    {
        try
        {
            Blog blog = new Blog()
                {
                    BlogId = 1,
                    Url = "http://www.google.si"
                };

            await dbContext.AddAsync(blog);
            await dbContext.SaveChangesAsync();

            var stZapisovVBazi = dbContext.Blogs.Count();
            Debug.WriteLine(stZapisovVBazi);
        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex.Message);
        }
    }
}
```
b) Example for .NET MAUI App - add this lines into MainPage.xaml.cs file:
```
        public MainPage(BloggingContext dbContext)
	{
		InitializeComponent();

                try
                {
                    Blog blog = new Blog()
                    {
                        BlogId = 1,
                        Url = "http://www.google.si"
                    };

                    dbContext.Add(blog);
                    dbContext.SaveChanges();

                    var stZapisovVBazi = dbContext.Blogs.Count();
                    Debug.WriteLine(stZapisovVBazi);
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.Message);
                }
	}
```
You have to take mainPage instance with DI in **App** class:
```
        public App(MainPage mainPage)
	{
		InitializeComponent();

		MainPage = mainPage;
	}
```
6. Run app on Android Emulator. Everything works OK.
7. Run app on iPhone 12 iOS 15.2 remote iOS simulator (via connected Mac). App crashes at line:
`SQLitePCL.Batteries_V2.Init();`

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPhone 12 iOS 15.2, Xcode 13.2.1, VS 17.1.0 Preview 5.0 on Windows 10 (connected to remote Mac)

### Relevant log output

```shell
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: e_sqlite3
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[ValueTuple`2,Int32](ValueTuple`2 state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

**Comment by RaspeR87** [comment]
Some additional info:

If I create .NET MAUI App with these NuGet packages:
`
          <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
	  <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.0.8-pre20220111224339" />
	  <PackageReference Include="SQLitePCLRaw.core" Version="2.0.8-pre20220111224339" />
	  <PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.0.8-pre20220111224339" />
	  <PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.0.8-pre20220111224339" />
`

I got pretty same exception:
`{System.DllNotFoundException: e_sqlite3 at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number() at SQLitePCL.raw.SetProvider(ISQLite3Provider imp) at SQLitePCL.Batteries_V2.Init() at MauiApp3.Data.BloggingContext..ctor() in D:\Temp\MauiApp3\MauiApp3\Data\BloggingContext.cs:line 18 at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions) at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`

![2022-02-04_08-41-52](https://user-images.githubusercontent.com/14901702/152491197-ad2d71c5-9205-4b99-a8a1-77da59316068.png)

**Comment by ericsink** [comment]
Just FYI:

I've been investigating this problem at:

ericsink/SQLitePCL.raw#468

and @RaspeR87 has posted a repro there,

and I thought perhaps the following might be of interest here:

Building inside VS 17.1 (preview 5) produces different build output than building from the command line.  From a nuget package, a different assembly is copied into the build output directory.

More details are present in the comments on that issue, and there might be good reasons for this behavior, but it certainly *seems* kinda wrong to see these two build operations doing different things.

**Comment by VincentBu** [comment]
I can run MauiApp2 and MauiApp3 from https://github.com/ericsink/SQLitePCL.raw/issues/468#issuecomment-1030302553 on Android. But I fail to build both project for IOS.
```
1>Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
1>Tool xcrun execution finished (exit code = 1).
1>ld: file too small (length=0) file 'obj/Debug/net6.0-ios/iossimulator-x64/nativelibraries/libSystem.Native.dylib' for architecture x86_64
1>clang: error: linker command failed with exit code 1 (use -v to see invocation)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.91\targets\Xamarin.Shared.Sdk.targets(1197,3): error : clang++ exited with code 1
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.91\targets\Xamarin.Shared.Sdk.targets(1197,3): error :
1>Done building project "MauiApp2.csproj" -- FAILED.
```

**Comment by VladislavAntonyuk** [comment]
Working example: https://github.com/VladislavAntonyuk/MauiSamples/tree/main/Sqlite

**Comment by jfversluis** [comment]
@RaspeR87 can you confirm this is still an issue? I think I have seen multiple examples where this works now?

Thanks!

**Comment by Redth** [comment]
@ericsink I'd expect you'll need to rebuild against a newer net6.0-ios as there's been breaking, incompatible binary changes.  I believe Preview 14 is the last of them though, so you should be able to build against that and be compatible going forward.

**Comment by Redth** [comment]
Please open a new issue if there's still problems around this and they are related to MAUI :)

**Comment by ltemimi** [comment]
@[VladislavAntonyuk](https://github.com/VladislavAntonyuk)

I looked at the MAUI samples for the kanban board. It does not work for IOS I get connection exception when Database EnsureCreated is called.

Have you tested it with IOS?
Thanks

**Comment by VladislavAntonyuk** [comment]
@ltemimi yes, it works:
iOS
![image](https://user-images.githubusercontent.com/33021114/163771264-b154c7c8-e2b9-4529-a3a2-0849abfd62cb.png)

**Comment by ltemimi** [comment]
Hi

Are all the nuger packages for the Kanbanboard app required?

Thanks
Laz

**Comment by VladislavAntonyuk** [comment]
You can experiment, but that is the list that I use to make it work

**Comment by ltemimi** [comment]
Thanks Take care
