### ISSUE TITLE
Handler and MauiContext is null when View isn't

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#4496]
### Description

When the `View` (Entry in the sample) is created its `Handler` and `MauiContext` are null causing issues (NRE) when we need to access those properties.

### Steps to Reproduce

1. Open the bug repro in the branch [`behavior-bug`](https://github.com/pictos/MauiBugRepro/tree/behavior-bug)
2. Start the application
3. See the app crash (`RemoveBorder.Android.OnPlatformAttached` method)

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

All

### Did you find any workaround?

Adding a `Task.Delay` before access the `MauiContext` and `Handler`.

**Comment by IndianaGary** [comment]
This may be related to my issue where I'm using the SkiaSharp Renderer in Compatibility mode. I get NREs for "Handler not found" when opening a Skia-based Control even though I'm depending upon a Renderer, not a Handler.

**Comment by PureWeen** [comment]
@pictos in XF is `Behavior.OnAttachedTo` called after the renderer is attached? 

I might be remembering incorrectly but I feel like `OnAttachedTo` on a behavior is called when the behavior is attached to the xaml tree.

So if you want to access the platform from a behavior you'd need to use the HandlerChanged/HandlerChanging events?

**Comment by pictos** [comment]
@PureWeen 

> @pictos in XF is Behavior.OnAttachedTo called after the renderer is attached?

yes, I did the test here, and the `OnAttched` methods are called before the `Renderer`.

> So if you want to access the platform from a behavior you'd need to use the HandlerChanged/HandlerChanging events?

I would say, yes. Because I'll need to know when the Handler is created and attached to the View. IMHO this _bug_ (if it's a bug) can affect other areas of the application. Because when the Application is created and `MainPage` is created, we have the `View` for all controls in the `Page`, but we don't have `MauiContext` and/or `Handler`, as a mobile dev I would expect to always be able to access the `View.Handler` and `View.Handler.MauiContext` when the `View` is not `null`. Does it make sense?

**Comment by PureWeen** [comment]
@pictos even if we did consider this a bug we couldn't change the behavior from Controls. 

Behaviors are meant to be more xplat focused modifiers. They offer a way to modify a xaml control without having to extend the control.  Users might not want the behavior to take effect after the control has been realized on the platform. 

Honestly what we should probably do is add an `OnPlatformAttached` override to behaviors and deprecate effects.

**Comment by pictos** [comment]
@PureWeen should I create a feature request then? I thought that was an agreement on the Maui team that we should use `Behaviors` instead of `Effects`, if that's true we should change how the Behaviors work or create a new API.

**Comment by PureWeen** [comment]
@pictos yea if you could add a feature request that'd be great!

We probably won't change the state of things currently but we can look at this again for the next release

**Comment by pictos** [comment]
Thanks @PureWeen
