### ISSUE TITLE
Refactor Essentials statics into interfaces/singletons

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#4497]
Historically Xamarin.Essentials API's were all static classes with static methods in them.  This made mocking out their behaviour for testing much more difficult, and many ended up creating yet another abstraction on top of these API's.

We need to refactor these into interfaces and create implementations which can be set as the singleton at runtime.  We can map the existing static methods to the singleton to preserve backwards source code compatibility.

See these examples: https://github.com/dotnet/maui/pull/4464 https://github.com/dotnet/maui/pull/4465 and https://github.com/dotnet/maui/pull/4466

## API's to complete:
- [x] [Accelerometer](https://github.com/dotnet/maui/pull/4630)
- [x] [AppActions](https://github.com/dotnet/maui/pull/4596)
- [x] [AppInfo](https://github.com/dotnet/maui/pull/4464)
- [x] [Barometer](https://github.com/dotnet/maui/pull/4604)
- [x] [Battery](https://github.com/dotnet/maui/pull/4629)
- [x] [Browser](https://github.com/dotnet/maui/pull/4605)
- [x] [Clipboard](https://github.com/dotnet/maui/pull/4612)
- [x] [Compass](https://github.com/dotnet/maui/pull/4615)
- [x] [Connectivity](https://github.com/dotnet/maui/pull/4622)
- [x] [Contacts](https://github.com/dotnet/maui/pull/4539)
- [x] [DeviceDisplay](https://github.com/dotnet/maui/pull/3213)
- [x] [DeviceInfo](https://github.com/dotnet/maui/pull/4465)
- [x] [Email](https://github.com/dotnet/maui/pull/4623)
- [x] [FilePicker](https://github.com/dotnet/maui/pull/4632)
- [x] [FileSystem](https://github.com/dotnet/maui/pull/4633)
- [x] [Flashlight](https://github.com/dotnet/maui/pull/4525)
- [x] [Geocoding](https://github.com/dotnet/maui/pull/4527)
- [x] [Geolocation](https://github.com/dotnet/maui/pull/4634)
- [x] [Gyroscope](https://github.com/dotnet/maui/pull/4649)
- [x] [HapticFeedback](https://github.com/dotnet/maui/pull/4651)
- [x] [Launcher](https://github.com/dotnet/maui/pull/4886)
- [x] [Magnetometer](https://github.com/dotnet/maui/pull/4652)
- [x] [Map](https://github.com/dotnet/maui/pull/4557)
- [x] [MediaPicker](https://github.com/dotnet/maui/pull/4663)
- [x] [OrientationSensor](https://github.com/dotnet/maui/pull/4662)
- [x] ~Permissions~ Not necessary, API is already based on class implementations, the static methods just instantiate and call the method on the specified generic type parameter.
- [x] [PhoneDialer](https://github.com/dotnet/maui/pull/4466)
- [x] [Preferences](https://github.com/dotnet/maui/pull/4582)
- [x] [Screenshot](https://github.com/dotnet/maui/pull/4699)
- [x] [SecureStorage](https://github.com/dotnet/maui/pull/4668)
- [x] [SemanticScreenReader](https://github.com/dotnet/maui/pull/4673)
- [x] [Share](https://github.com/dotnet/maui/pull/4674)
- [x] Sms
- [x] [TextToSpeech](https://github.com/dotnet/maui/pull/4747)
- [x] [VersionTracking](https://github.com/dotnet/maui/pull/4891)
- [x] [Vibration](https://github.com/dotnet/maui/pull/4727)
- [x] [WebAuthenticator](https://github.com/dotnet/maui/pull/4757)

**Comment by mattleibow** [comment]
So looking at the various implementations so far, I think we actually need to do more than just what we have. If I was to register a service and _not_ use the statics, I would lose a fair bit of functionality.

For example, if there is any validation or permissions checks. Right now that just lives in the static class. This should all move to the instance. But to be clean and consistent now, we can continue the way we are.

**Comment by antonfirsov** [comment]
@sps014 giving a heads up if you plan to go on working on this, to avoid duplicate work :) I plan to go top-down in alphabetic order, started with `Accelerometer`.

**Comment by sps014** [comment]
Great will create a trackable issue from now on, not working on `Accelerometer`.

**Comment by mattleibow** [comment]
I also know that @moljac is working on some too. Maybe he starts in the middle :)

**Comment by moljac** [comment]
Nope 'A'

now working on 'G'

**Comment by moljac** [comment]
@antonfirsov @sps014 I started with 'A' and am on 'G' right now. I didn't raise PRs because few of those are a bit tougher.

**Comment by antonfirsov** [comment]
@moljac then we just did duplicate work :) I opened a PR for `Accelerometer` in #4630 and also finished `AppActions` 😄

How to divide the work then? I can also grab something else.

**Comment by moljac** [comment]
This is my list WIP

```
essentials-interfaces-accelerometer
essentials-interfaces-appactions
essentials-interfaces-barometer
essentials-interfaces-battery
essentials-interfaces-browser
essentials-interfaces-clipboard
essentials-interfaces-compass
essentials-interfaces-connectivity
essentials-interfaces-email
essentials-interfaces-filepicker
essentials-interfaces-filesystem
m
```

currently preparing G

**Comment by antonfirsov** [comment]
Today I don't plan to start anything new. Won't PR ApActions, since it's duplicate work.

**Comment by antonfirsov** [comment]
@moljac I will pick some of the remaining items on Sunday or Monday. Let's say the stuff between `Preferences - Share`. Is it fine with you?

**Comment by antonfirsov** [comment]
I will work on `Screenshot-Share` today (& possibly more).

**Comment by moljac** [comment]
@Redth @mattleibow @rmarinho @jsuarezruiz

Hi

Here:

https://github.com/dotnet/maui/pull/4464/files#diff-2c429fd1e9c28a636e0af7b0d118980207e1412bbd0c75a08ea43a4b313ff4e8L31

and here:

https://github.com/dotnet/maui/pull/4466/files#diff-575ea05d8aa0835c4f48ef27c57b2cc678bd3608446df45597e5be8393da7c06L14

I saw removing `Platform` prefix, so I removed it in my PRs.

Now I have cyclic references Launcher is used by Browser, Email and PhoneDialer, so it will not build until those are merged OR I can make 1 PR with all 4 refactorings in that PR. Ideas? Wishes?

**Comment by moljac** [comment]
@antonfirsov Dobre rano!

Planning to start work on last 4 features:

```
essentials-interfaces-texttospeech
essentials-interfaces-versiontracking
essentials-interfaces-vibration
essentials-interfaces-webauthenticator
```

Is this OK with you?

How come you can edit this issue?

**Comment by antonfirsov** [comment]
> Is this OK with you?

Yeah, I don't plan to push further PR-s for this one.

> ow come you can edit this issue?

@Redth added me to `maui-internal-contributors` yesterday.

**Comment by moljac** [comment]
> @Redth added me to `maui-internal-contributors` yesterday.

Say hello to him for me. MAUI is non-inclusive project 😄 At least now I have contact point, communication officer.

**Comment by antonfirsov** [comment]
@moljac pinged you on Teams.

**Comment by moljac** [comment]
Sorry for delays. Trying to answer questions about Maps v.18 and impact on Xamarin.Forms.

**Comment by antonfirsov** [comment]
@moljac do you plan to continue working on this or should I take the remaining ones? If you can take it, I can deal with other important tasks, but it is very important to finish this refactor by EOW.

**Comment by moljac** [comment]
> @moljac do you plan to continue working on this or should I take the remaining ones? If you can take it, I can deal with other important tasks, but it is very important to finish this refactor by EOW.

Which are remaining ones?
I was busy trying to jumpstart CI builds for AndroidX, GooglePlayServices-Firebase-MLKit and XamarinComponents repo.
Sorry.
I see MAUI team was busy.
Let me check what is left
