### ISSUE TITLE
Blazor Hybrid WinForms apps give error if there's an ErrorBoundary

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#4502]
### Description

Ironically it's the `ErrorBoundary` that *causes* the error.

![image](https://user-images.githubusercontent.com/1101362/152402345-c053c4ee-7586-4c2f-98bf-874469e704bd.png)

This may also affect WPF/MAUI but I haven't tried those yet.

### Steps to Reproduce

Put `<ErrorBoundary>` inside a Blazor Hybrid WinForms app.

Fix: We need to add a default `IErrorBoundaryLogger` to the DI container. Presumably it should just log to console.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

**Comment by javiercn** [comment]
@SteveSandersonMS do we have one in Blazor Server? Does the one in WASM use ILogger? I'm a bit worried about adding something that logs to the console. The console is not necessarily visible on Windows Forms / WPF applications and in case it is, we would also be potentially interfering with legitimate output produced by the app, so I think we should have something that does "nothing" and let users plug in their own implementation.

What do you think?

**Comment by SteveSandersonMS** [comment]
We do have default implementations for other platforms:

 * https://github.com/dotnet/aspnetcore/blob/main/src/Components/Server/src/Circuits/RemoteErrorBoundaryLogger.cs
 * https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ViewFeatures/src/RazorComponents/PrerenderingErrorBoundaryLogger.cs
 * https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/Services/WebAssemblyErrorBoundaryLogger.cs

They all log to console by default.

> The console is not necessarily visible on Windows Forms / WPF applications

Indeed. I suppose that if MAUI has any conventions about logging warning-type info we should aim to follow them. I don't know if such conventions exist. @Eilon  ?

**Comment by javiercn** [comment]
@SteveSandersonMS As long as we use ILogger I think it's fine. 

Then people can choose whether to log to the console or a different ILogger implementation, my point was about doing something like `Console.WriteLine` by default; Although we should ask/figure the Maui/WF/WPF story for logging to make sure we have a proper E2E.

**Comment by Eilon** [comment]
I think MAUI has an ILogger registered by default. There are some discussions right now around the exact defaults in default apps, but either way, ILogger is the way to go.

**Comment by pranavkm** [comment]
A fix for this involves updating `AddBlazorWebView` to do what `AddBlazorWebAssembly` / `AddServerSideBlazor` does, but that also means patching 6.0. Are we open to that? /cc  @mkArtakMSFT

**Comment by Eilon** [comment]
@pranavkm hmm could this be fixed in this repo instead? Or would it be possible to fix in both and have the best one win? (Which, with TryAddScoped, would presumably happen anyway?)

**Comment by javiercn** [comment]
@Eilon we should patch this.

**Comment by TanayParikh** [comment]
Updating milestone and re-opening as this was fixed via https://github.com/dotnet/aspnetcore/pull/40508, which will ship via SDK 6.0.4. We'll need to confirm this issue is in fact resolved thereafter.
