### ISSUE TITLE
[Windows] Crash using RadioButtonGroup with a StackLayout

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4508]
### Description

Unable to cast object of type 'Microsoft.Maui.Controls.StackLayout' to type 'Microsoft.Maui.Controls.Compatibility.Layout`1[Microsoft.Maui.Controls.View]'.
![image](https://user-images.githubusercontent.com/6755973/152516257-7c1c92d6-4eee-42b1-816b-b5c5a984cbcd.png)

### Steps to Reproduce

1. Download https://github.com/davidbritch/dotnet-maui-samples/tree/main/UserInterface/Views/RadioButtonDemos
2. Navigate to the sample "Grouped RadioButtons ViewModel demo"

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17134.0

**Comment by the8thC** [comment]
i get the same crash on Android and iOS

**Comment by YuqinSong** [comment]
Not reproducible. when navigate to the sample "Grouped RadioButtons ViewModel demo", project will not crash.
