### ISSUE TITLE
Exception using OnPlatform with View type

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4509]
### Description

Using this piece of code:

```
<OnPlatform x:TypeArguments="View">
    <On Platform="iOS,UWP">
        <!-- iOS and UWP can assign a View to RadioButton.Content. -->
        <RadioButton>
            <RadioButton.Content>
                <StackLayout Orientation="Horizontal">
                    <Image Source="monkey.png" />
                    <Label Text="Monkey"
                            VerticalTextAlignment="Center" />
                </StackLayout>
            </RadioButton.Content>
        </RadioButton>
    </On>
    <On Platform="Android">
        <RadioButton Content="Android can't assign a View to RadioButton.Content." />
    </On>
</OnPlatform>
```

![image](https://user-images.githubusercontent.com/6755973/152517248-aafbb8fb-22af-4c86-8b28-d40896b60351.png)

### Steps to Reproduce

1. Download https://github.com/davidbritch/dotnet-maui-samples/tree/main/UserInterface/Views/RadioButtonDemos
2. Navigate to the sample "RadioButton containing a string"

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Windows SDK 10.0.17134.0, Android 11

### Relevant log output

```shell
System.ArgumentException: 'Object of type 'Microsoft.Maui.Controls.OnPlatform`1[Microsoft.Maui.Controls.View]' cannot be converted to type 'Microsoft.Maui.IView'.'
```

**Comment by shimingsg** [comment]
Verified repro with Windows and the above project.

**Comment by StephaneDelcroix** [comment]
is this expected to work? does the equivalent c# code using OnPlatform works ? or is the sample broken ?
