### ISSUE TITLE
[Android 11] Behavior does not modify properties of attached object when modification occurs in an EventHandler

### ISSUE THREAD

**Issue by danielftz** [dotnet/maui#4516]
### Description

I have implemented a behavior which automatically subscribes the attached VisualElement to AppThemeChanged event, and modify its property (BackgroundColor in this case) accordingly. However when the device theme is changed, the BackgroundColor property is not set. The reason why I use such a roundabout way to do AppThemeBinding is because our app is entirely written in C#, and we need to use SetDynamicResource inside Behaviors. 
```cs
public class TestBehavior : Behavior<VisualElement>
{
  private VisualElement? _attachedView;
  
  protected override void OnAttachedTo(VisualElement bindable)
  {
	  base.OnAttachedTo(bindable);
	  if (Application.Current is not null)
	  {
                                _attachedView = bindable;
		  switch (Application.Current.RequestedTheme)
		  {
			  case OSAppTheme.Dark:
				  _attachedView.BackgroundColor = Colors.White;
				  break;
			  default:
				  _attachedView.BackgroundColor = Colors.Black;
				  break;
		  }
  
		  
		  Application.Current.RequestedThemeChanged += OnAppThemeChanged;
  
	  }
  
  }
  
  protected override void OnDetachingFrom(VisualElement bindable)
  {
	  base.OnDetachingFrom(bindable);
	  if (Application.Current is not null)
	  {
		  Application.Current.RequestedThemeChanged -= OnAppThemeChanged;
  
	  }
  }
  
  
  private void OnAppThemeChanged(object? s, AppThemeChangedEventArgs e)
  {
	  Device.BeginInvokeOnMainThread(() =>
	  {
		  if (_attachedView is not null)
		  {
			  switch (e.RequestedTheme)
			  {
				  case OSAppTheme.Dark:
					  _attachedView.BackgroundColor = Colors.White;
					  break;
				  default:
					  _attachedView.BackgroundColor = Colors.Black;
					  break;
			  }
		  }
  
	  });
  }
}
```

### Steps to Reproduce
I have Attached a sample of a Behavior object which would change the BackgroundColor of the attached element based on the current app theme. You can reproduce this bug by creating any visual element, add the Behavior to its list of Behaviors. The visual will not be modified when app theme is changed. 

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

I can use trigger to do something like this, however that has its own issues/bugs, and is more convoluted overall.

**Comment by danielftz** [comment]
Something related to this issue, 
`public static void SetOnAppTheme<T>(this BindableObject self, BindableProperty targetProperty, T light, T dark)`
does not instantly change the binding on Android either. The binding will only be correctly set when the page is re-rendered by navigating by and then enter again.

**Comment by J-Swift** [comment]
Another data point: It seems that this only affects BackgroundColor property? My dynamic resource bindings for other properties (e.g. Label.TextColor) work fine when referencing the same DynamicResource value.

**Comment by mattleibow** [comment]
Does the page background change when you set it via a button click for example?

**Comment by danielftz** [comment]
> Does the page background change when you set it via a button click for example?

Probably related issue: 
https://github.com/dotnet/maui/issues/4335
