### ISSUE TITLE
Referencing Blazor wasm hosted project in Blazor MAUI project

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#4521]
### Description

First I want to confirm if the following is officially supported or I just happen to stumble upon something that is not fully supported ?

I have existing Blazor WebAssembly hosted PWA Project that I want to publish to iOS & Android platform, without any changes.

I added reference to Blazor wasm hosted (client Project) from Blazor MAUI Project.
I can launch Blazor Maui and display the pages from Blazor wasm hosted project.
But when I access weather forecast page which makes an http call, the mobile app entirely crashes.
What am I missing here for that page ?

Here is the project that i gave a try.
https://1drv.ms/v/s!AtHk7h6Srnk_h-B--nkQMyenoWtz1w?e=HuIcQb

### Steps to Reproduce

1) Create Blazor MAUI Project
2) Compile and run the MAUI Project
3) Add Blazor wasm hosted PWA project to the solution.
   change the Startup Project
4) Run the Blazor Hosted wasm server project.

Next Change the startup project to Blazor MAUI and run it
Add Project Reference to the Blazor wasm Client Project.

Try to run the Blazor MAUI Project , you will get lots of compile error.
To resolve the errors
Delete Pages folder
Delete Everything for wwwroot project

Run Blazor MAUI project, it should launch successfully and display pages from Blazor wasm hosted project.

When you navigate to weather page it will crash the mobile app

### Version with bug

Preview 7

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Version 17.1.0 Preview 5.0

### Did you find any workaround?

No

### Relevant log output

```shell
https://1drv.ms/v/s!AtHk7h6Srnk_h-B--nkQMyenoWtz1w?e=HuIcQb
```

**Comment by nssidhu** [comment]
Android debug output

Time	Device Name	Type	PID	Tag	Message
02-04 21:38:52.622	pixel_5_-_api_30	Debug	548	WifiNative	Scan result ready event
02-04 21:38:52.622	pixel_5_-_api_30	Debug	548	WifiNl80211Manager	Scan result ready event
02-04 21:38:51.885	pixel_5_-_api_30	Warning	1821	gle.android.gm	Reducing the number of considered missed Gc histogram windows from 177 to 100
02-04 21:38:51.825	pixel_5_-_api_30	Info	1672	TngMinusOneSync	Syncing TNG:-1
02-04 21:38:51.820	pixel_5_-_api_30	Error	1672	MDD	DownloadProgressMonitor: Can't find file group for uri: android://com.google.android.googlequicksearchbox/files/sharedminusonemodule/shared/SharedMinusOneData.pb.tmp
02-04 21:38:51.812	pixel_5_-_api_30	Info	1672	BgTaskExecutorImpl	Starting EXCLUSIVE background task TNG_MINUS_ONE_SYNC.
02-04 21:38:51.799	pixel_5_-_api_30	Warning	1225	GCoreFlp	No location to return for getLastLocation()
02-04 21:38:51.782	pixel_5_-_api_30	Warning	1672	LocationOracle	No location history returned by ContextManager
02-04 21:38:51.773	pixel_5_-_api_30	Warning	1672	ThreadPoolDumper	Queue length for executor EventBus is now 11. Perhaps some tasks are too long, or the pool is too small.
02-04 21:38:51.768	pixel_5_-_api_30	Error	1672	sb.v.u.LiteSuggestSourc	On-device lite suggest model loading error.
02-04 21:38:51.755	pixel_5_-_api_30	Debug	311	goldfish-address-space	claimShared: Ask to claim region [0x3f8000000 0x3f89a4000]
02-04 21:38:51.752	pixel_5_-_api_30	Debug	311	goldfish-address-space	claimShared: Ask to claim region [0x3f5cec000 0x3f6690000]
02-04 21:38:51.743	pixel_5_-_api_30	Debug	311	goldfish-address-space	claimShared: Ask to claim region [0x3f5348000 0x3f5cec000]
02-04 21:38:51.742	pixel_5_-_api_30	Debug	311	goldfish-address-space	claimShared: Ask to claim region [0x3f49a4000 0x3f5348000]
02-04 21:38:51.740	pixel_5_-_api_30	Debug	311	goldfish-address-space	claimShared: Ask to claim region [0x3f4000000 0x3f49a4000]
02-04 21:38:51.730	pixel_5_-_api_30	Debug	311	goldfish-address-space	claimShared: Ask to claim region [0x3f6cbc000 0x3f7660000]
02-04 21:38:51.729	pixel_5_-_api_30	Warning	548	RemoteAppPredictionService	could not bind to Intent { act=android.service.appprediction.AppPredictionService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiPredictionService } using flags 67108865
02-04 21:38:51.728	pixel_5_-_api_30	Warning	548	ActivityManager	Unable to start service Intent { act=android.service.appprediction.AppPredictionService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiPredictionService } U=0: not found
02-04 21:38:51.712	pixel_5_-_api_30	Warning	207	Binder:207_2	type=1400 audit(0.0:247): avc: denied { read } for name="wakeup35" dev="sysfs" ino=18996 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
02-04 21:38:51.714	pixel_5_-_api_30	Error	207	android.system.suspend@1.0-service	Error opening kernel wakelock stats for: wakeup35: Permission denied
02-04 21:38:51.713	pixel_5_-_api_30	Debug	548	EGL_emulation	eglMakeCurrent: 0x79409cf3f630: ver 2 0 (tinfo 0x79403cf23b30) (first time)
02-04 21:38:51.704	pixel_5_-_api_30	Warning	207	Binder:207_2	type=1400 audit(0.0:246): avc: denied { read } for name="wakeup34" dev="sysfs" ino=18933 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
02-04 21:38:51.710	pixel_5_-_api_30	Error	207	android.system.suspend@1.0-service	Error opening kernel wakelock stats for: wakeup34: Permission denied
02-04 21:38:51.703	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got cluster times for an isolated uid with no mapping: 99002
02-04 21:38:51.703	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got cluster times for an isolated uid with no mapping: 99001
02-04 21:38:51.703	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got cluster times for an isolated uid with no mapping: 99000
02-04 21:38:51.703	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got cluster times for an isolated uid with no mapping: 90003
02-04 21:38:51.703	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got cluster times for an isolated uid with no mapping: 90002
02-04 21:38:51.703	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got cluster times for an isolated uid with no mapping: 90001
02-04 21:38:51.703	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got cluster times for an isolated uid with no mapping: 90000
02-04 21:38:51.702	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got active times for an isolated uid with no mapping: 99002
02-04 21:38:51.702	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got active times for an isolated uid with no mapping: 99001
02-04 21:38:51.702	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got active times for an isolated uid with no mapping: 99000
02-04 21:38:51.699	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got active times for an isolated uid with no mapping: 90003
02-04 21:38:51.699	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got active times for an isolated uid with no mapping: 90002
02-04 21:38:51.699	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got active times for an isolated uid with no mapping: 90001
02-04 21:38:51.699	pixel_5_-_api_30	Warning	548	BatteryStatsImpl	Got active times for an isolated uid with no mapping: 90000
02-04 21:38:51.698	pixel_5_-_api_30	Debug	548	BatteryStatsImpl	Got freq readings for an isolated uid with no mapping: 99002
02-04 21:38:51.698	pixel_5_-_api_30	Debug	548	BatteryStatsImpl	Got freq readings for an isolated uid with no mapping: 99001
02-04 21:38:51.698	pixel_5_-_api_30	Debug	548	BatteryStatsImpl	Got freq readings for an isolated uid with no mapping: 99000
02-04 21:38:51.698	pixel_5_-_api_30	Debug	548	BatteryStatsImpl	Got freq readings for an isolated uid with no mapping: 90003
02-04 21:38:51.698	pixel_5_-_api_30	Debug	548	BatteryStatsImpl	Got freq readings for an isolated uid with no mapping: 90002
02-04 21:38:51.698	pixel_5_-_api_30	Debug	548	BatteryStatsImpl	Got freq readings for an isolated uid with no mapping: 90001
02-04 21:38:51.697	pixel_5_-_api_30	Debug	548	BatteryStatsImpl	Got freq readings for an isolated uid with no mapping: 90000
02-04 21:38:51.691	pixel_5_-_api_30	Info	869	Zygote	Process 9508 exited cleanly (0)
02-04 21:38:51.847	pixel_5_-_api_30	Info	0	binder	undelivered transaction 333040, process died.
02-04 21:38:51.845	pixel_5_-_api_30	Info	0	binder	undelivered transaction 333042, process died.
02-04 21:38:51.844	pixel_5_-_api_30	Info	0	binder	undelivered transaction 333041, process died.
02-04 21:38:51.688	pixel_5_-_api_30	Debug	974	Telephony	isEmergencyPreferredAccount: Device does not require preference.
02-04 21:38:51.688	pixel_5_-_api_30	Debug	974	Telephony	isEmergencyPreferredAccount: subId=1, activeData=1
02-04 21:38:51.686	pixel_5_-_api_30	Verbose	722	KeyguardUpdateMonitor	SubInfo:{id=1 iccId=89014103211118510720 simSlotIndex=0 carrierId=1 displayName=T-Mobile carrierName=T-Mobile nameSource=3 iconTint=-16746133 number=+15555215554 dataRoaming=0 iconBitmap=android.graphics.Bitmap@515714d mcc=310 mnc=260 countryIso=us isEmbedded=false nativeAccessRules=null cardString=89014103211118510720 cardId=-1 isOpportunistic=false groupUUID=null isGroupDisabled=false profileClass=-1 ehplmns=null hplmns=null subscriptionType=0 groupOwner=null carrierConfigAccessRules=null areUiccApplicationsEnabled=true}
02-04 21:38:51.683	pixel_5_-_api_30	Verbose	722	KeyguardUpdateMonitor	onSubscriptionInfoChanged()
02-04 21:38:51.679	pixel_5_-_api_30	Debug	548	EGL_emulation	eglCreateContext: 0x79409cf3f630: maj 2 min 0 rcv 2
02-04 21:38:51.669	pixel_5_-_api_30	Warning	548	OpenGLRenderer	Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
02-04 21:38:51.668	pixel_5_-_api_30	Info	548	libprocessgroup	Successfully killed process cgroup uid 99003 pid 9508 in 0ms
02-04 21:38:51.665	pixel_5_-_api_30	Warning	722	ndroid.systemu	Reducing the number of considered missed Gc histogram windows from 182 to 100
02-04 21:38:51.657	pixel_5_-_api_30	Warning	548	ActivityManager	setHasOverlayUi called on unknown pid: 9473
02-04 21:38:51.652	pixel_5_-_api_30	Warning	548	BroadcastQueue	Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-04 21:38:51.652	pixel_5_-_api_30	Warning	548	BroadcastQueue	Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
02-04 21:38:51.646	pixel_5_-_api_30	Info	548	ActivityManager	Killing 9508:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0a161i3 (adj 0): isolated not needed
02-04 21:38:51.637	pixel_5_-_api_30	Warning	548	InputDispatcher	Attempted to unregister already unregistered input channel 'be4c31e com.companyname.blazorhybridmauiapp/crc64e90d97f6dc9e141d.MainActivity (server)'
02-04 21:38:51.636	pixel_5_-_api_30	Info	548	WindowManager	WIN DEATH: Window{be4c31e u0 com.companyname.blazorhybridmauiapp/crc64e90d97f6dc9e141d.MainActivity}
02-04 21:38:51.636	pixel_5_-_api_30	Debug	548	HostConnection	HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
02-04 21:38:51.635	pixel_5_-_api_30	Debug	548	ConnectivityService	releasing NetworkRequest [ TRACK_DEFAULT id=60, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10161 AdministratorUids: [] RequestorUid: 10161 RequestorPackageName: com.companyname.blazorhybridmauiapp] ] (release request)
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.634	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.633	pixel_5_-_api_30	Warning	548	InputReader	Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
02-04 21:38:51.633	pixel_5_-_api_30	Debug	548	HostConnection	HostConnection::get() New Host Connection established 0x7940ace21b50, tid 6998
02-04 21:38:51.632	pixel_5_-_api_30	Warning	1125	System	A resource failed to call release. 
02-04 21:38:51.632	pixel_5_-_api_30	Warning	1125	System	A resource failed to call release. 
02-04 21:38:51.629	pixel_5_-_api_30	Warning	1125	s.nexuslaunche	Reducing the number of considered missed Gc histogram windows from 265 to 100
02-04 21:38:51.781	pixel_5_-_api_30	Info	0	binder	undelivered transaction 332999, process died.
02-04 21:38:51.627	pixel_5_-_api_30	Debug	548	ConnectivityService	ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=60, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10161 AdministratorUids: [] RequestorUid: 10161 RequestorPackageName: com.companyname.blazorhybridmauiapp] ], android.os.BinderProxy@87a2ac7)
02-04 21:38:51.627	pixel_5_-_api_30	Debug	548	ConnectivityService	ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=61, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND Uid: 10161 AdministratorUids: [] RequestorUid: 10161 RequestorPackageName: com.companyname.blazorhybridmauiapp] ], android.os.BinderProxy@5be3406)
02-04 21:38:51.624	pixel_5_-_api_30	Info	548	ActivityManager	Process com.companyname.blazorhybridmauiapp (pid 9473) has died: prcp TOP 
02-04 21:38:51.624	pixel_5_-_api_30	Info	548	libprocessgroup	Successfully killed process cgroup uid 10161 pid 9473 in 1ms
02-04 21:38:51.778	pixel_5_-_api_30	Info	0	binder	undelivered transaction 333006, process died.
02-04 21:38:51.777	pixel_5_-_api_30	Info	0	binder	undelivered TRANSACTION_COMPLETE
02-04 21:38:51.618	pixel_5_-_api_30	Info	290	Zygote	Process 9473 exited due to signal 11 (Segmentation fault)
02-04 21:38:51.617	pixel_5_-_api_30	Error	548	InputDispatcher	channel 'be4c31e com.companyname.blazorhybridmauiapp/crc64e90d97f6dc9e141d.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-04 21:38:51.617	pixel_5_-_api_30	Warning	548	InputDispatcher	channel 'be4c31e com.companyname.blazorhybridmauiapp/crc64e90d97f6dc9e141d.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-04 21:38:51.611	pixel_5_-_api_30	Warning	548	BroadcastQueue	Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-04 21:38:51.610	pixel_5_-_api_30	Warning	548	BroadcastQueue	Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
02-04 21:38:51.763	pixel_5_-_api_30	Info	0	init	Untracked pid 9575 exited with status 0
02-04 21:38:51.760	pixel_5_-_api_30	Info	0	init	Untracked pid 9573 exited with status 0
02-04 21:38:51.591	pixel_5_-_api_30	Debug	311	goldfish-address-space	claimShared: Ask to claim region [0x3f6690000 0x3f6cbc000]
02-04 21:38:51.586	pixel_5_-_api_30	Info	548	DropBoxManagerService	add tag=data_app_native_crash isTagEnabled=true flags=0x2
02-04 21:38:51.584	pixel_5_-_api_30	Info	548	DropBoxManagerService	add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x2
02-04 21:38:51.583	pixel_5_-_api_30	Info	548	BootReceiver	Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
02-04 21:38:51.736	pixel_5_-_api_30	Debug	0	logd	logdr: UID=10161 GID=10161 PID=9573 n tail=0 logMask=1 pid=9473 start=0ns timeout=0ns
  Force finishing activity com.companyname.blazorhybridmauiapp/crc64e90d97f6dc9e141d.MainActivity
02-04 21:38:51.580	pixel_5_-_api_30	Error	283	tombstoned	Tombstone written to: /data/tombstones/tombstone_02
02-04 21:38:51.735	pixel_5_-_api_30	Debug	0	logd	logdr: UID=10161 GID=10161 PID=9573 n tail=0 logMask=8 pid=9473 start=0ns timeout=0ns
02-04 21:38:51.641	pixel_5_-_api_30	Debug	0	logd	logdr: UID=10161 GID=10161 PID=9573 n tail=50 logMask=1 pid=9473 start=0ns timeout=0ns
02-04 21:38:51.639	pixel_5_-_api_30	Debug	0	logd	logdr: UID=10161 GID=10161 PID=9573 n tail=50 logMask=8 pid=9473 start=0ns timeout=0ns
02-04 21:38:51.390	pixel_5_-_api_30	Error	9573	DEBUG	backtrace:
      #00 pc 000000000065d8fc  /apex/com.android.art/lib64/libart.so (void art::StackVisitor::WalkStack<(art::StackVisitor::CountTransitions)0>(bool)+156) (BuildId: 7fbaf2a1a3317bd634b00eb90e32291e)
      #01 pc 000000000069b25d  /apex/com.android.art/lib64/libart.so (art::Thread::GetCurrentMethod(unsigned int*, bool, bool) const+157) (BuildId: 7fbaf2a1a3317bd634b00eb90e32291e)
      #02 pc 0000000000430fed  /apex/com.android.art/lib64/libart.so (art::JNI<false>::FindClass(_JNIEnv*, char const*)+765) (BuildId: 7fbaf2a1a3317bd634b00eb90e32291e)
      #03 pc 0000000000047e5a  /data/app/~~OgKogqwnhCNOuoKvgA0Daw==/com.companyname.blazorhybridmauiapp--J1tzY0ZK8FpBZjptD_noA==/split_config.x86_64.apk!libmono-android.release.so (offset 0x11e000) (java_interop_jnienv_find_class+26) (BuildId: 965ab7928a2ac6dddc1f9458687280f5e81f01ba)
      #04 pc 00000000000128ac  <anonymous:40d08000>
02-04 21:38:51.362	pixel_5_-_api_30	Error	9573	DEBUG	Cause: null pointer dereference
    rax 0000793fbf4dc820  rbx 0000793fbf4dcdc0  rcx 0000000000000000  rdx 0000793fbf4dc820
    r8  fffffffffffffdd0  r9  0000793fbf4dce40  r10 0000000000000000  r11 0000793fc4410b30
    r12 0000793fbf4dcbe0  r13 000079401c79d550  r14 000079418ce617c8  r15 0000000000000000
    rdi 0000793fbf4dcdc0  rsi 0000000000000000
    rbp 0000000000000000  rsp 0000793fbf4dcba0  rip 000079401cc768fc
02-04 21:38:51.362	pixel_5_-_api_30	Error	9573	DEBUG	signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
02-04 21:38:51.361	pixel_5_-_api_30	Error	9573	DEBUG	uid: 10161
02-04 21:38:51.361	pixel_5_-_api_30	Error	9573	DEBUG	pid: 9473, tid: 9533, name: ThreadPoolForeg  >>> com.companyname.blazorhybridmauiapp <<<
02-04 21:38:51.361	pixel_5_-_api_30	Error	9573	DEBUG	Timestamp: 2022-02-04 21:38:51-0600
02-04 21:38:51.361	pixel_5_-_api_30	Error	9573	DEBUG	ABI: 'x86_64'
02-04 21:38:51.361	pixel_5_-_api_30	Error	9573	DEBUG	Revision: '0'
02-04 21:38:51.361	pixel_5_-_api_30	Error	9573	DEBUG	Build fingerprint: 'google/sdk_gphone_x86_64_arm64/generic_x86_64_arm64:11/RSR1.201211.001.A1/7054069:userdebug/dev-keys'
02-04 21:38:51.361	pixel_5_-_api_30	Error	9573	DEBUG	*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-04 21:38:51.357	pixel_5_-_api_30	Info	9573	crash_dump64	performing dump of process 9473 (target tid = 9533)
02-04 21:38:51.356	pixel_5_-_api_30	Info	283	tombstoned	received crash request for pid 9533
02-04 21:38:51.355	pixel_5_-_api_30	Info	9573	crash_dump64	obtaining output fd from tombstoned, type: kDebuggerdTombstone
02-04 21:38:51.318	pixel_5_-_api_30	Error	9473	libc	Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 9533 (ThreadPoolForeg), pid 9473 (orhybridmauiapp)
02-04 21:38:51.317	pixel_5_-_api_30	Error	9570	crashpad	dlopen: dlopen failed: library "libandroidicu.so" not found: needed by /system/lib64/libharfbuzz_ng.so in namespace (default)
02-04 21:38:51.267	pixel_5_-_api_30	Warning	9473	orhybridmauiap	JNI WARNING: DeleteLocalRef(0x99) failed to find entry
02-04 21:38:51.267	pixel_5_-_api_30	Warning	9473	orhybridmauiap	Attempt to remove index outside index area (9 vs 10-10)
02-04 21:38:47.606	pixel_5_-_api_30	Info	1312	PeriodicStatsRunner	PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
02-04 21:38:47.606	pixel_5_-_api_30	Info	1312	PeriodicStatsRunner	PeriodicStatsRunner.call():180 call()

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Blazor WebAssembly apps are not meant to be used as libraries. If you intent to use some pieces from it, you have to move those components in a Razor Class Libraries and reference those libraries instead.

When hosted in MAUI app there is no server exposing endpoints to call into. Hence, this won't work nor we plan to make it magically work.
