### ISSUE TITLE
SwipeView throws Java.Lang.IllegalStateException:'Layout state should be one of 100 but it is 10' when in RefreshView

### ISSUE THREAD

**Issue by walkerXx1** [dotnet/maui#4529]
### Description

When SwipeView is put to CollectionView that is in RefreshView, exception is thrown: **Java.Lang.IllegalStateException:** 'Layout state should be one of 100 but it is 10'

` 
<RefreshView RefreshColor="Azure">
            <CollectionView>
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <SwipeView>
                            <StackLayout>
                                <Label Text="a"></Label>
                            </StackLayout>
                        </SwipeView>
                    </DataTempalte>
            </CollectionView> 
       </RefreshView>`

### Steps to Reproduce

1. Use the code from the description on Content Page
2. Run the app on Android Emulator

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11.0 - API 30

### Did you find any workaround?

No

### Relevant log output

```shell
**Java.Lang.IllegalStateException:** 'Layout state should be one of 100 but it is 10'
```

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EXuLAKFMfS9HnkWtqCOoQf8BQ0f7Ra9R2eWHcRH3nt2iew?e=qltqqE

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue using the main  branch ![issue-4529](https://user-images.githubusercontent.com/6755973/158178213-19e1c513-63ff-4c86-9237-61fc36b38ae3.gif)

@walkerXx1 Could you try again using the latest Preview?
