### ISSUE TITLE
AppThemeBinding interferes with VisualStateManager

### ISSUE THREAD

**Issue by vanka78bg** [dotnet/maui#4540]
### Description

There is a bug when using `AppThemeBinding` with `VisualStateManager`, which leads to incorrect styling. When both features are used separately, everything works as expected. When using `VisualStateManager` to declare different styling for the different `VisualState`s, and the `Setter`s for the `VisualState`s use `AppThemeBinding` to specify different values based on the current app theme, the styling can get messed up. This bug seems somewhat related to another bug: https://github.com/dotnet/maui/issues/4139.

### Steps to Reproduce

1. Run the attached sample application:
The application has two `Label`s with two `CheckBox`es. The first `Label` uses a regular `Style` without `AppThemeBinding`. The second `Label` uses a themed `Style` with `AppThemeBinding`. Toggling a `CheckBox` toggles the `IsEnabled` state of the corresponding `Label`.

2. Toggle the first `CheckBox` several times:
The first `Label` switches between normal `TextColor` and grayed out `TextColor` based on the `IsEnabled` property as expected.

3. Toggle the second `CheckBox` several times:
The second `Label` switches to a grayed out `TextColor` and stays in that state regardless of the `IsEnabled` property.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

I have not tested on various versions of the same platform

### Did you find any workaround?

Do not use `AppThemeBinding` at all. Provide separate `Style`s for the `Dark` and `Light` themes and implement your own mechanism to toggle between these `Style`s accordingly.

### Sample project

[TestApp.zip](https://github.com/dotnet/maui/files/8014897/TestApp.zip)

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/ESvCen96KkpGvAtjpOgJ98oBtYCJN1FEjD0KXMvS_0uBvQ?e=VrI3vv

**Comment by StephaneDelcroix** [comment]
should be fixed by #6362

**Comment by davidortinau** [comment]
Retested and unable to repro in rc3. Closing as fixed.
