### ISSUE TITLE
iOS Publishing ignores bundle identifier and uses project name instead

### ISSUE THREAD

**Issue by gdv1982** [dotnet/maui#4559]
### Description

Following the instructions on https://stackoverflow.com/questions/61119754/cannot-create-ios-archive-path-directory-name-must-be-less-than-248-characters/61120063#61120063 to publish an iOS app for the APP Store, the specified bundle identifier is ignored and the project name is used instead (this is visible in the first step under the "APPNAME" section). This will cause "provisioning profiles not found" errors. Renaming the project to the same as the Bundle Identifier creates the app's IPA in the correct way.

### Steps to Reproduce

- Create a new project with any name (for example "com.sample.project")
- Set the bundle identifier to a different string (for example "com.example.project")
- Running "dotnet publish ..." as per the instructions tries to generate the app with identifier "com.sample.project" instead of "com.example.project"

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 14.2

### Did you find any workaround?

Renaming the Project to the same as the Bundle Identifier creates the IPA file with the correct identifier

**Comment by Redth** [comment]
@jonathanpeppers or @mattleibow is this in our targets where we use the application identifier property? Or is something happening with iOS targets @rolfbjarne ?

**Comment by rolfbjarne** [comment]
I wonder if it works by setting/adding a `ApplicationId` property to the csproj?

Something like this

```xml
<PropertyGroup>
    <ApplicationId>com.example.project</ApplicationId>
</PropertyGroup>
```

**Comment by gdv1982** [comment]
> I wonder if it works by setting/adding a `ApplicationId` property to the csproj?
> 
> Something like this
> 
> ```
> <PropertyGroup>
>     <ApplicationId>com.example.project</ApplicationId>
> </PropertyGroup>
> ```

Not in my case, I tried adding the "ApplicationId" property with the correct package identified in the csproj file but it was ignored

**Comment by rolfbjarne** [comment]
Just to make sure I understand correctly: you expect the ipa file to be named `com.example.project.ipa` (and not `com.sample.project.ipa`)?

**Comment by gdv1982** [comment]
> Just to make sure I understand correctly: you expect the ipa file to be named `com.example.project.ipa` (and not `com.sample.project.ipa`)?

Yes, this is the behaviour that I would expect, not just for the file name but also (and more importantly) for the app identifier that is then used to identify the created app (since provisioning profiles only work with the correct identifier)

**Comment by rolfbjarne** [comment]
> > Just to make sure I understand correctly: you expect the ipa file to be named `com.example.project.ipa` (and not `com.sample.project.ipa`)?
> 
> Yes, this is the behaviour that I would expect, not just for the file name but also (and more importantly) for the app identifier that is then used to identify the created app (since provisioning profiles only work with the correct identifier)

The bundle identifier in the `Payload/com.sample.project.app/Info.plist` file seems correct to me:

```
$ unzip -p ./bin/Debug/net6.0-ios/ios-arm64/publish/com.sample.project.ipa Payload/com.sample.project.app/Info.plist | plutil -convert xml1 -o - - | grep BundleIdentifier -A 1
	<key>CFBundleIdentifier</key>
	<string>com.example.project</string>
```

is there anywhere else it's showing the wrong value?

**Comment by gdv1982** [comment]
> > > Just to make sure I understand correctly: you expect the ipa file to be named `com.example.project.ipa` (and not `com.sample.project.ipa`)?
> > 
> > 
> > Yes, this is the behaviour that I would expect, not just for the file name but also (and more importantly) for the app identifier that is then used to identify the created app (since provisioning profiles only work with the correct identifier)
> 
> The bundle identifier in the `Payload/com.sample.project.app/Info.plist` file seems correct to me:
> 
> ```
> $ unzip -p ./bin/Debug/net6.0-ios/ios-arm64/publish/com.sample.project.ipa Payload/com.sample.project.app/Info.plist | plutil -convert xml1 -o - - | grep BundleIdentifier -A 1
> 	<key>CFBundleIdentifier</key>
> 	<string>com.example.project</string>
> ```
> 
> is there anywhere else it's showing the wrong value?

I couldn't produce the IPA file because I was using a provisioning profile specificallly created for "com.example.project", and since the publishing process was trying to publish "com.sample.project", I got provisioning errors during the process...

Coudl it be that you are using a provisioning profile that doesn't specify any id (maybe your provisionig profile specified "*" as the id), and so you don't get any provisioning error during the publishing process?

**Comment by rolfbjarne** [comment]
> I got provisioning errors during the process...

> P.S.: Just noticed I pasted the wrong url in the first message, it should have been https://github.com/dotnet/maui/issues/4397

Can you explain exactly which steps in the process showed errors?

**Comment by mattleibow** [comment]
So is it that just the ipa filename is not matching the bundle id?

**Comment by rolfbjarne** [comment]
> So is it that just the ipa filename is not matching the bundle id?

That's expected, but the filename shouldn't matter anyways, so I'm not sure what's happening for the publishing to go wrong.

**Comment by mattleibow** [comment]
Maybe we should just use the bundle identifier for the filename. I think this is what android does?

**Comment by gdv1982** [comment]
> > I got provisioning errors during the process...
> 
> > P.S.: Just noticed I pasted the wrong url in the first message, it should have been #4397
> 
> Can you explain exactly which steps in the process showed errors?

The step 3.3 (Build and sign your app) failed because my provisioning certificate was specifically created for "com.example.project", while the building and signing process was trying to sign the app with the bundle identifier "com.sample.project" (because that was the name I had given to the csproj inside the sln; as I said, renaming the csproj file to "com.example.project" solved the issue, but I think the correct "place" where the bundle identifier should be taken from during the building and signing process is not the csproj file name)

The filename is not an issue at all.

**Comment by rolfbjarne** [comment]
> The step 3.3 (Build and sign your app) failed because my provisioning certificate was specifically created for "com.example.project", while the building and signing process was trying to sign the app with the bundle identifier "com.sample.project" (because that was the name I had given to the csproj inside the sln; as I said, renaming the csproj file to "com.example.project" solved the issue, but I think the correct "place" where the bundle identifier should be taken from during the building and signing process is not the csproj file name)

I tried this, and I still can't reproduce it, the bundle identifier that's being used is the correct one.

Can you add `/bl:msbuild.binlog` to the end of the `dotnet publish` command, and attach the resulting msbuild.binlog file from a failed publishing attempt? This file will hopefully contain all the info necessary to figure out what's going on.
