### ISSUE TITLE
The StrokeDashArray property in Ellipse cannot be animated

### ISSUE THREAD

**Issue by qian-o** [dotnet/maui#4566]
### Description

When you change the StrokeDashArray value in the Animation callback, the view is not refreshed, but if you change the StrokeThickness property at the same time, the view is updated.
![image](https://user-images.githubusercontent.com/84434846/153023991-7d73ab0b-0f52-47e5-9a34-90e2aa004829.png)
![image](https://user-images.githubusercontent.com/84434846/153024065-5edf1a80-fc3d-40e5-89be-c61fc19336c3.png)
When you run the code like this, nothing happens.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a `Ellipse` like so: `<Ellipse x:Name="ellTest" BackgroundColor="red" HeightRequest="60" WidthRequest="60" HorizontalOptions="Center" VerticalOptions="Center" Stroke="#409EFF" StrokeThickness="6" HandlerChanged="EllTest_HandlerChanged"/>`
3. Write the following code in the EllTest_HandlerChanged event
private void EllTest_HandlerChanged(object sender, EventArgs e)
    {
        Animation animation = new((d) =>
        {
            ellTest.StrokeDashArray = new DoubleCollection(new double[] { d, 28.26 - d });
        }, start: 0, end: 28.26);
        ellTest.Animate("test", animation, length: 1500, easing: Easing.SinInOut, repeat: () => true);
    }
4. Run the program, no effect.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android11 win11

### Did you find any workaround?

1. Create a File > New .NET MAUI App
2. Add a `Ellipse` like so: `<Ellipse x:Name="ellTest" BackgroundColor="red" HeightRequest="60" WidthRequest="60" HorizontalOptions="Center" VerticalOptions="Center" Stroke="#409EFF" StrokeThickness="6" HandlerChanged="EllTest_HandlerChanged"/>`
3. Write the following code in the EllTest_HandlerChanged event
private void EllTest_HandlerChanged(object sender, EventArgs e)
    {
        Animation animation = new((d) =>
        {
            ellTest.StrokeDashArray = new DoubleCollection(new double[] { d, 28.26 - d });
            ellTest.StrokeThickness = ellTest.StrokeThickness == 6 ? 6.1 : 6;
        }, start: 0, end: 28.26);
        ellTest.Animate("test", animation, length: 1500, easing: Easing.SinInOut, repeat: () => true);
    }
4. Run the program, display animation effect.

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EaNcyCuMHA1IqHWPqnbohTkB7TNpOTIH4OV2jNOk6zs82g?e=W6UsDK
