### ISSUE TITLE
.Net MAUI does not accept multi-language .resx files for iOS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4568]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-MAUI-does-not-accept-multi-language/1647024)._

---
In the Properties folder, if I have the default language .resx file (Resources.resx) and just one .resx file for another language (say Resources.af.resx), I can build for iOS in .Net MAUI.
If I add a still another language .resx file (say Resources.cs.resx) the build fails with error SDKNET1152 "Found multiple publish output files with the same relative path..."
This does not happen for Android or Windows, just iOS (and presumably MasCatalyst).

---
#### Feedback Bot on 1/25/2022, 11:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by v-longmin** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
