### ISSUE TITLE
Toolbox is empty in Visual Studio

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#4571]
### Description

<img width="150" alt="image" src="https://user-images.githubusercontent.com/41873/153060176-28a678c8-f6d0-4c5e-84ad-293f0c552627.png">

This is populated from the NuGet in Xamarin.Forms, so I expect it is part of the package here as well. It seems to be missing. I reproduced this based on a report from the open survey.

### Steps to Reproduce

Open MAUI solution and open the toolbox in VS22.

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

all

**Comment by Redth** [comment]
Azdo# 1463875

**Comment by HKLM** [comment]
Having the same issue on new clean install of VS2022 Preview (17.3.0 Preview 2.0) with the 6.0.4 maui

**Comment by Redth** [comment]
Tracked in azdo, closing.
