### ISSUE TITLE
Click  Package.appxmanifest  error

### ISSUE THREAD

**Issue by weiwei11245** [dotnet/maui#4585]
### Description

![image](https://user-images.githubusercontent.com/41153370/153171744-2eddaff9-3063-44ef-84b7-832a134bb108.png)

### Steps to Reproduce

Click  Package.appxmanifest  error

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

window sdk 10.0.19041

**Comment by v-xiaofchen** [comment]
Verified repro with windows and the above project.
![Picture27](https://user-images.githubusercontent.com/99376012/155929564-aa50fcbb-a283-4cd0-8f74-ad0675dedaee.png)

**Comment by Redth** [comment]
AzDo# 1462516

**Comment by jfversluis** [comment]
I think this one is resolved.
