### ISSUE TITLE
BlazorWebView AdditionalBrowserArguments

### ISSUE THREAD

**Issue by Flaflo** [dotnet/maui#4586]
### Description

I have a use-case where I need to configure the environment with additional browser argument for core webview. At the moment this is impossible to do and I would really appreciate a solution to this.

### Public API Changes

```csharp
private void InitializeComponents()
{
    var blazorWebView = new BlazorWebView
    {
        Dock = DockStyle.Fill,
        HostPage = "wwwroot/index.html"
    };

    blazorWebView.RootComponents.Add<App>("#app");
    blazorWebView.CoreWebView2EnvironmentConfiguration += WebViewOnCoreWebView2EnvironmentConfiguration;

    Controls.Add(blazorWebView);
}

private void WebViewOnCoreWebView2EnvironmentConfiguration(object? sender, CoreWebView2EnvironmentConfigurationEventArgs args)
{
    args.AdditionalBrowserArguments = "--disable-features=msWebOOUI,msPdfOOUI";
}
```

### Intended Use-Case

In my app I want to disable the mini menu for text selections on websites and PDFs. At the moment this is only achievable through specific arguments to the browser. In the future there could be more similiar use-cases to the one I have.

**Comment by Eilon** [comment]
I think this should now be available as of .NET MAUI RC1, which was released a few days ago.

This was fixed as part of https://github.com/dotnet/maui/pull/5802.
