### ISSUE TITLE
SearchHandler.ItemTemplate can not be fill

### ISSUE THREAD

**Issue by sou1maker** [dotnet/maui#4589]
### Description

When I use SearchHandler, I find that the item cannot be populated, which is normal in xamarin. Is there something wrong with my settings? 

![image](https://user-images.githubusercontent.com/58240137/153245759-89d3bfaf-d667-4bb3-8a2d-43f6bb916ef6.png)

### Steps to Reproduce

The problem can be reproduced using SearchHandler 

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
@sou1maker Could you provide your repro project, thanks?
