### ISSUE TITLE
Provide an event on all Controls Views that will indicate when they have become attached/detached from platform window

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#4590]
### Description

With .NET MAUI we added `HandlerChanged/HandleringChanging` which gives people a good perspective when the platform component has been created for a control but it would be useful to surface events that map down to the platform concepts of `Attached`

These event choices are up for discussion
- WinUI: Loaded/Unloaded
- Android: IsAttachedToWindow/IsDetachedFromWindow
- iOS: willMoveToWindow (Ideally there is a way to hook into this without having to sublass)

### Public API Changes

- event View.Loaded
- event View.Unloaded

### Intended Use-Case

This will let users and 3rd party libraries attached/detach from events or start making visual changes once a view has been added to or removed from the visual tree

**Comment by mattleibow** [comment]
One thing I did was to create a binding from that property to track it:

 - https://github.com/mono/SkiaSharp/blob/v2.88.0-preview.179/source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKXamlCanvas.cs#L31-L36
 - https://github.com/mono/SkiaSharp/blob/v2.88.0-preview.179/source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKXamlCanvas.cs#L62-L67

**Comment by PureWeen** [comment]
How would `IsVisibleChanged` be more useful than watching `PropertyChanged` ?  We typically won't wire up events that are just associated with `BindableProperty` changes.  Unless I'm not fully understanding the reach of the suggestion

**Comment by DoubleDBE** [comment]
You certainly got a point there.

I just feel like it's a basic event that is currently lacking in XF, and at this stage it doesn't seem to be a lot of trouble to implement directly in Maui.

Of course, one can listen to `PropertyChanged`, that's all fine and dandy for new apps. But not so fine and dandy when porting a large WPF application to XF, or Maui for that matter.

But still, from a productivity point of view it's just a lot (not too much, but you get the point)
of hastle to implement this in **_every_** code behind file where one needs it. 

With an event, one just types a few characters in the XAML editor and lets intellisense take care of things.
And it makes sure one has something to work with that **_just works_**. 

Just my 2 cents ✌
