### ISSUE TITLE
VS 17.1 prv2:  default maui builds and deploys Windows but fails to build Android with error shown

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4593]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-171-prv2:--default-maui-builds-and-d/1632174)._

---
1- create default Maui proj
2- wait for load to complete entirely before doing anything
3-switch Windows build deploy
4- update nuget packages (image shown)
5- build & deploy OK
6- switch to Android
7- build fails with the error shown

**error:** Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1130	Microsoft.Graphics.Canvas.winmd cannot be referenced. Referencing a Windows Metadata component directly when targeting .NET 5 or higher is not supported. For more information, see https://aka.ms/netsdk1130	MauiApp_prv2	c:\program files\dotnet\sdk\6.0.200-preview.21617.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	1003	

---
#### Feedback Bot on 1/10/2022, 01:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by BittProduction** [comment]
Hi i ran into the same issue.

what helped me was to open the yourproject.csproj file
You will find something like this
```
<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
<!-- Required - WinUI does not yet have buildTransitive for everything -->
	<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.0.30" />
	<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
</ItemGroup>
```

this was added twice in my csproj file first time with the extension preview after each PackageReference.

remove the PackageReferences with preview. It should final file should only contain the shown Itemgroup in teh codeblock from above.

hope this helps

**Comment by Amir-Care** [comment]
Not repro on VS Version 17.2.0 Preview 2.0 [32219.17.main]
