### ISSUE TITLE
Collect list of changed default padding/margin/spacing values

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#4594]
In MAUI we opted to make the default for padding/margin/spacing (and maybe other things?) 0 instead of a magic number.

We need a list of the old defaults, to create a style for 'compat' migrated projects.

**Comment by hartez** [comment]
| Property | Default |
| --- | --- |
| Grid.RowSpacing | 6 |
| Grid.ColumnSpacing | 6 |

**Comment by rachelkang** [comment]
^ @hartez's list is actually pretty comprehensive. A deeper dive didn't reveal too much: https://gist.github.com/rachelkang/1297094190441a8ae5bb505343856bbe

**Comment by J-Swift** [comment]
Related: is there a reason Frame still maintains its default padding of 20 (as well as `HasShadow=true`)? I see it alluded to in https://github.com/dotnet/maui/issues/341 and https://github.com/dotnet/maui/discussions/39 but never saw anyone say "hey keep Frame as is".
