### ISSUE TITLE
[Android emulator] MAUI Blazor essentials camera exception

### ISSUE THREAD

**Issue by domagojmedo** [dotnet/maui#4597]
### Description

When calling `await MediaPicker.CapturePhotoAsync();` camera will open on android 11 emulator but an exception will be thrown from the app. It works fine on my Android 8 device and Android 8 emulator.

`Android.Content.Res.Resources+NotFoundException
  Message=Drawable com.companyname.mauiapp2:mipmap/appicon_round with resource ID #0x7f0c0001
`

### Steps to Reproduce

You can check out https://github.com/domagojmedo/MauiApp2 or just call await MediaPicker.CapturePhotoAsync();

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by Eilon** [comment]
@domagojmedo do you see the same behavior happening in a .NET MAUI app without Blazor?

**Comment by domagojmedo** [comment]
Just tested, seems like issue is with normal MAUI also

https://github.com/domagojmedo/MauiApp3.App

**Comment by v-xiaofchen** [comment]
Not reproducible with 17.2.0 Preview 2.0 [32209.335.main] using Android 11 and above project(MauiApp2).
It works fine and I can not see the exception.
![Picture24](https://user-images.githubusercontent.com/99376012/155917149-121428ca-8b2a-45a8-88b0-701157758616.png)
![Picture25](https://user-images.githubusercontent.com/99376012/155917162-15a83c0f-5775-4389-9573-077709f0c386.png)
![Picture26](https://user-images.githubusercontent.com/99376012/155917168-13e7ed24-aaea-4471-bebd-e00e45e6a061.png)
