### ISSUE TITLE
[Android] MAUI app breaks Android 8 launcher

### ISSUE THREAD

**Issue by domagojmedo** [dotnet/maui#4598]
### Description

If you deploy MAUI Blazor app to Android 8 emulator or device, Launcher will stop working. Happened on my OnePlus 3T device and on Pixel 5 Android 8 emulator. "Launcher keeps stopping" pops out indefinitely. I was able to fix my real device by removing the package through adb command (couldn't uninstall normally because launcher crashed every second). 
I thought I bricked my phone for a minute there, it was not the best experience 

![image](https://user-images.githubusercontent.com/12157224/153297028-d20d5c90-c22a-419d-b935-bb7e24e89542.png)

### Steps to Reproduce

Not sure if there's anything special to reproduce it, but I used this almost default app https://github.com/domagojmedo/MauiApp2
Only thing added was call to open camera

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8

**Comment by Eilon** [comment]
@domagojmedo do you see the same behavior happening in a .NET MAUI app without Blazor?

**Comment by domagojmedo** [comment]
Just tested, seems like issue is with normal MAUI also

https://github.com/domagojmedo/MauiApp3.App

**Comment by Redth** [comment]
@mattleibow this sounds like the at other launcher icon bug we couldn't repro.

**Comment by mattleibow** [comment]
This is very strange because it is the default maui app icon which is literally a purple path and 4 white paths. And I think for p12 we make bitmaps. And this is the pixel 5 emu... 

@domagojmedo are you able to attach the logcat for the crashing emulator?

**Comment by domagojmedo** [comment]
@mattleibow I can get logs with Device log window in VS, but not sure how to export it

**Comment by mattleibow** [comment]
Wowzers... Can't seem to repro this at all!

Can you attach the config files for your emulator so I can try repro this. 
They are found in: `C:\Users\<user>\.android\avd\<avd-name>.avd`

 - hardware-qemu.ini
 - config.ini

Also, is this with Hyper V or HAXM?

**Comment by domagojmedo** [comment]
Should be x86 emulator with Hyper-V (had to change to .txt file, Github wouldn't allow .ini)
[hardware-qemu.txt](https://github.com/dotnet/maui/files/8050250/hardware-qemu.txt)
[config.txt](https://github.com/dotnet/maui/files/8050253/config.txt)

**Comment by mattleibow** [comment]
OK, so we have the exact same config files - except for username.

Maybe it is the OS. What version are you on? Also, what is your graphics card/manufacturer? Maybe it is something in the OpenGL drivers...

**Comment by domagojmedo** [comment]
Same thing happened on my phone OnePlus 3T, so it's not emulator exclusive. Also I just tested on x86 emulator and same thing happened
[device log x86.txt](https://github.com/dotnet/maui/files/8050306/device.log.x86.txt)

Windows 10 Pro Version	10.0.19044 Build 19044
AMD Ryzen 7 PRO 5850U with Radeon Graphics, 1901 Mhz, 8 Core(s), 16 Logical Processor(s)

**Comment by mattleibow** [comment]
There has been a whole bunch of comments on the previous issue, all seeming to be related to Android 8. Both Jon and I have not been able to repro this at all.

But, Android 8 seems to be a common thing.

At least we are no longer using Android vectors. In Preview 13 we convert the vectors to raster bitmaps and then use that.

If anyone is feeling extra lucky, they could install the upcoming Preview 13 using the CLI:

```
dotnet workload install maui `
   --from-rollback-file https://aka.ms/dotnet/maui/preview.13.json `
   --source https://aka.ms/dotnet6/nuget/index.json `
   --source https://api.nuget.org/v3/index.json
```

I just want to clarify that this should not cause any major issues and you can roll back to preview 12. However, things that require IDE work - like hot reload and live previews may crash the app. So you may need to run and see.

**Comment by domagojmedo** [comment]
Just tested with new project with preview 13 and the issue seems resolved
