### ISSUE TITLE
[Enhancement] Visual studio code supported development environment 

### ISSUE THREAD

**Issue by levelfivecoder** [dotnet/maui#46]
## Summary
We require a light weight development environment for mobile app development and should support in Linux.

**Comment by dhindrik** [comment]
Scott Hunter showed how he used Visual Studio Code in his session. And this is not an MAUI thing, it is a tooling thing so this issue will probably be somewhere else. Also, it is not only related to MAUI, but it is also about .NET for iOS/Android/macOS.

**Comment by GiampaoloGabba** [comment]
VS Code will be supported as stated in the readme of this repo :)
Moreover MAUI will get full support for the dotnet CLI, which is awesome

**Comment by jsuarezruiz** [comment]
Yes, MAUI will have Visual Studio Code and dotnet CLI support.

**Comment by GeraudFabien** [comment]
The question is wether or not it will work with codespace. And if it does could the emulator be : 
- On the codespace container
- On other container
- On my machine
- And support real device
