### ISSUE TITLE
In shell App, PresentationMode.Modal does not hide NavigationBar for Top level  Page

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#4603]
### Description

The reproduction project is using `Shell TabBar` with only one Content Page. I set the page's presentation mode to `Modal`. But  the `main page` still shows `NavigationBar`. 
The second page is not part of the top level shell navigation also have PresentationMode property set to `Modal`. It is registered in the `AppShell.xaml.cs`. When I navigate to `second page` it does not show the NavigationBar. 

[BugSample.zip](https://github.com/dotnet/maui/files/8038284/BugSample.zip)

### Steps to Reproduce

Run the repro project. Notice that the MainPage have NavigationBar although the PresentationMode is set to Modal.  Navigate to SecondPage by clicking the button at the bottom. Notice that SecondPage don't have NavigationBar. Second page also have PresentationMode as Modal. 

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11- API 30

### Did you find any workaround?

 Shell.SetNavBarIsVisible(this, false);  will hide the NavigationBar.

**Comment by PureWeen** [comment]
This will be fixed with P14
