### ISSUE TITLE
Grid RowDefinition Height Binding not working

### ISSUE THREAD

**Issue by rctec-at** [dotnet/maui#4609]
### Description

I Bound the Height of a Grid to a Value, but as it seems this Binding is not evaluated (Getter not called) and just interpreted as GridLenght.Star.

### Steps to Reproduce

1. Create a new Maui App
2. Create a ViewModel with a GridLength/double Property with a value (i used 100.0)
3. Create a Grid in your Main Page that uses 2 or more Rows. 
4. Create Contentviews with different background colors for your rows
4. Bind 1 Row Height to your ViewModel Property

The problem should be visible

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 9/12 Windows 10

**Comment by PineYi** [comment]
Not reproducible with 32215.517.main using Android 11. Project deploys correctly

**Comment by samhouts** [comment]
RowDefinitions are not inheriting the BindingContext. You can work around this by explicitly setting the BindingContexts for the RowDefinitions.

**Comment by rctec-at** [comment]
Thank you @samhouts  for this workaround i am going to check this out later.
Sad that its getting pushed back and back tho..

could be a possibility this not inheriting the BindingContext hits multible control elements?
