### ISSUE TITLE
[Android] Crash updating FontSize using HotReload

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4610]
### Description

Crash updating Label FontSize using HotReload
![crash-hr](https://user-images.githubusercontent.com/6755973/153442214-5ccadc26-8f5e-40a2-9777-b6b5c418b5d9.gif)

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-chat-app-challenge
2. Launch the App on Android device or emulator and try to update an Entry FontSize.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.

**Comment by drasticactions** [comment]
I can't get this to repro in RC1, but I'm also 99% sure it's not Hot Reload itself causing the issue, but rather, it's updating the font size in general that caused it to blow up.

If you can repro this, I would try and set changing the font programmatically and seeing what that does, if it doesn't blow up there but it does in XAML Hot Reload, then we need to look at the tooling side of it. But right now, it seems like it would be a platform specific issue.
