### ISSUE TITLE
VisualTreeElementExtensions.GetVisualTreeElements does not work for transformed elements

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#4613]
### Description

Hit testing [VisualTreeElementExtensions.GetVisualTreeElements](https://github.com/dotnet/maui/blob/cd3a8193fefb2d1e18993e0f15446989fa74a6cc/src/Core/src/Core/Extensions/VisualTreeElementExtensions.cs#L64) does not work well for transformed elements.
![MauiHitTestIssue](https://user-images.githubusercontent.com/48451158/153458404-0a020676-c74a-49ab-9217-949531d2891c.gif)

### Steps to Reproduce

1. Create new WinUI/MAUI app.
2. Open MainPage.xaml
3. Add Scale="2" to <Button> element.
4. Build and run.
5. Use  [VisualTreeElementExtensions.GetVisualTreeElements](https://github.com/dotnet/maui/blob/cd3a8193fefb2d1e18993e0f15446989fa74a6cc/src/Core/src/Core/Extensions/VisualTreeElementExtensions.cs#L64)  to hit test Button
 [VisualTreeElementExtensions.GetVisualTreeElements](https://github.com/dotnet/maui/blob/cd3a8193fefb2d1e18993e0f15446989fa74a6cc/src/Core/src/Core/Extensions/VisualTreeElementExtensions.cs#L64) : can hit test button at any corner
**Actual**: hit testing near bottom or right edges does not find button
**Note**: similar issue with Rotate transform and possibly others

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows

### Did you find any workaround?

no

**Comment by v-longmin** [comment]
It's not repro on Windows, repro project as attachment:  [4613.zip](\\mlangfs1\Public\dotnet maui\Repro Project)

**Comment by etvorun** [comment]
> It's not repro on Windows, repro project as attachment: [4613.zip](\mlangfs1\Public\dotnet maui\Repro Project)

What MAUI version did you use to verify? Preview 13 or something else?

**Comment by drasticactions** [comment]
@v-longmin This is an internal bug with APIs that are not directly exposed to endusers. This is an issue we've identified with the MAUI team and is known to them, and it's still an issue.

**Comment by antonfirsov** [comment]
I think I can repro this even with `Scale=1`. The hit testing fetches quite random results for me.

Also note that the hit testing code works against the bounding box (`IView.Frame`) of the view, and might not work well with views having sophisticated geometry.

I'm happy to look into this but I wonder if @drasticactions has any comments, seems like this feature has been added with #3351.

I wonder if we can delegate hit-testing to platform implementations, it is likely more optimized.

**Comment by antonfirsov** [comment]
@etvorun is there a reason the XAML Live Preview tool is using the rectangle overload `GetVisualTreeElements(element, x1, y1, x2, y2)`? It seems to me that `x1==x2` and `y1==y2`. Or is there a way to select an actual rectangle?

**Comment by etvorun** [comment]
@antonfirsov in near future we'll need to support multi element selection; similar to selecting multiple objects in Power Point slide  with mouse (a.k.a. click and drag to specify hit test rectangle)
