### ISSUE TITLE
IVisualTreeElement.GetVisualParent returns null for elements in Border

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#4614]
### Description

IVisualTreeElement.GetVisualParent returns null for elements in Border

### Steps to Reproduce

1. Open, build and run attached project.
2. Click on each button and observe changed message.
**Expected**: message should always mention non-null parent
**Actual**: message for Button in Border says "parent is null"
**Note**: there might be other MAUI types which don't have parent and/or don't implement IVisualTreeElement
 
[MauiApp11.zip](https://github.com/dotnet/maui/files/8042991/MauiApp11.zip)

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows

**Comment by YuqinSong** [comment]
Verified repro on 17.2.0 Preview 2.0 [32214.334.main] according the above project.
