### ISSUE TITLE
Clearing BindableProperty causes styles properties to disappear

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#4617]
### Description

Clearing BindableProperty causes styles properties to disappear

### Steps to Reproduce

1. Open build and run attached app.
2. Click on Clear Background button
**Actual**: buttons background color changes to white
**Expected**: no change in background color as they come from style
**Note**: this  breaks XAML Hot Reload. If you first add Background="Red" and then undo we end up with white background color rather than reverring to styles color.

[MauiApp11.zip](https://github.com/dotnet/maui/files/8043401/MauiApp11.zip)

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows

**Comment by wenwen60** [comment]
Reproduce on windows using VS2022(17.2.0 Preview 2.0) with above project, the styles properties disappear but the background color can change to white when I click on Clear Background button.

**Comment by StephaneDelcroix** [comment]
this shouldn't happen, we have code around that's supposed to restore the Style value. investigating...

**Comment by StephaneDelcroix** [comment]
this test succeed

```csharp
[Test]
		//https://github.com/dotnet/maui/issues/4617
		public void ClearValueShouldntUnapplyStyles()
		{
			var button = new Button();
			var layout = new StackLayout
			{
				Resources = new ResourceDictionary {
					new Style (typeof(Button)){ Setters = {
						new Setter{ Property=Button.BackgroundColorProperty, Value=Colors.HotPink}
						}
					}
				},
				Children = { button },
			};

			Assert.That(button.BackgroundColor, Is.EqualTo(Colors.HotPink));
			button.ClearValue(Button.BackgroundColorProperty);
			Assert.That(button.BackgroundColor, Is.EqualTo(Colors.HotPink));
			button.BackgroundColor = Colors.Red;
			Assert.That(button.BackgroundColor, Is.EqualTo(Colors.Red));
			button.ClearValue(Button.BackgroundColorProperty);
			Assert.That(button.BackgroundColor, Is.EqualTo(Colors.HotPink));


		}
```

**Comment by StephaneDelcroix** [comment]
indeed, it's a DynamicResource issue
