### ISSUE TITLE
Can not bind Orientation in LinearItemsLayout

### ISSUE THREAD

**Issue by lauglam** [dotnet/maui#4628]
### When I bind a value of type ItemsLayoutOrientation to the Orientation on LinearItemsLayout, I get an error : 

> 'Object of type 'Microsoft.Maui.Controls.Xaml.BindingExtension' cannot be converted to type 'Microsoft.Maui.Controls.ItemsLayoutOrientation'.'

![image](https://user-images.githubusercontent.com/58240137/153605268-3da34fd8-78c7-4659-a101-966e7cd46001.png)

![image](https://user-images.githubusercontent.com/58240137/153606445-731eb133-8dd8-47ba-8bdc-b1109fb2137f.png)

### Steps to Reproduce

Coding like this

```c#
<CollectionView HorizontalOptions="Center"
                ItemsSource="{Binding Collection}"
                VerticalOptions="Start">

    <CollectionView.ItemsLayout>
        <LinearItemsLayout ItemSpacing="0" Orientation="{Binding Orientation}" />
    </CollectionView.ItemsLayout>

    <CollectionView.ItemTemplate>
        <DataTemplate>
            <Label Text="show something ..." />
        </DataTemplate>
    </CollectionView.ItemTemplate>

</CollectionView>
```
```c#

private ItemsLayoutOrientation _orientation = ItemsLayoutOrientation.Horizontal;

public ItemsLayoutOrientation Orientation
{
    get => _orientation;
    set => SetProperty(ref _orientation, value);
}
```

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
Verified on Vs 17.2.0 Preview 2.0 [32223.438.main].
Windows(OS: 19044.1526): Show error 'Object of type 'Microsoft.Maui.Controls.Xaml.BindingExtension' cannot be converted to type 'Microsoft.Maui.Controls.ItemsLayoutOrientation'.'
Android(OS: Android 12.0-API31): Show error 'Object of type 'Microsoft.Maui.Controls.Xaml.BindingExtension' cannot be converted to type 'Microsoft.Maui.Controls.ItemsLayoutOrientation'.'
IOS(iPhone 12 mini iOS 15.2) : Show error 'Object of type 'Microsoft.Maui.Controls.Xaml.BindingExtension' cannot be converted to type 'Microsoft.Maui.Controls.ItemsLayoutOrientation'.'
![image](https://user-images.githubusercontent.com/97647558/155690652-2044fe5b-6ae8-488e-b33a-6412ab8d39c1.png)
Repro Project: [4628.zip](https://github.com/dotnet/maui/files/8140077/4628.zip)

**Comment by rmarinho** [comment]
@hartez  this was never a bindable property, i think this is not for servicing milestone. Not sure even if we want to make it bindable.

**Comment by jsuarezruiz** [comment]
> @hartez this was never a bindable property, i think this is not for servicing milestone. Not sure even if we want to make it bindable.

Yeah, I think have sense to move it to .NET 7 milestone.

**Comment by XamlTest** [comment]
Verified this issue on Visual Studio Enterprise 17.6.0 Preview 2.0. Repro on Windows, Android emulator (13.0-API 33) with below Project:
[4628.zip](https://github.com/dotnet/maui/files/11208390/4628.zip)
