### ISSUE TITLE
MAUI csproj properties altered after project creation

### ISSUE THREAD

**Issue by mikegoatly** [dotnet/maui#4631]
### Description

I'm copying most of this information over from #3542 as requested by @Eilon 

After creating a new MAUI project in an existing solution I found that I couldn't publish the Windows app (the 0700 error as described in #3542). I was using the Visual Studio 2022 (17.1.0 Preview 6.0) add project dialog, adding to an existing solution that contained an existing Xamarin project.

None of the workarounds in #3542 worked for me, so I did a bit more digging. I noticed that if I opened the csproj file straight after creation, the ItemGroup containing the resources looked correct, but after a few seconds, something was rewriting the content without any interaction from me. Specifically I observed the this:

	<ItemGroup>
		
		<MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" Color="#512BD4" />

		
		<MauiSplashScreen Include="Resources\appiconfg.svg" Color="#512BD4" />

		
		<MauiImage Include="Resources\Images\*" />

		
		<MauiFont Include="Resources\Fonts\*" />
	</ItemGroup>
rewritten to:

	<ItemGroup>
		
		<AndroidResource Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" Color="#512BD4" />

		
		<AndroidResource Include="Resources\appiconfg.svg" Color="#512BD4" />

		
		<MauiImage Include="Resources\Images\*" />

		
		<MauiFont Include="Resources\Fonts\*" />

	</ItemGroup>
My gut feeling was that some extension was misbehaving, so I disabled the obvious ones I could see in the list: Xamarin.Android SDK, Xamarin.Apple SDK and Uno Platform Solution Templates. After disabling these, the csproj no longer got rewritten and everything published fine after creating a new project.

Unfortunately (for testing purposes), everything still worked fine after I re-enabled the extensions, so I can't troubleshoot further, but perhaps this might help someone else.

### Steps to Reproduce

As mentioned above, unfortunately I don't have a consistent repo any more, but before I messed with the extensions it was a simple as:

* Create a new MAUI project in a solution (mine contained a Xamarin project as well, I don't know if that was significant)
* Open the csproj file immediately
* Watch as the msbuild properties are rewritten

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Whatever the default target version is; I don't think this is relevant because the project can't even be published.

### Did you find any workaround?

I still suspect there is something going on with the extensions I mentioned above, but I'm unable to verify exactly which was causing the problem now.

**Comment by v-longmin** [comment]
It's  not repro on windows, the project attachment
[4631.zip](https://github.com/dotnet/maui/files/8139017/4631.zip)
