### ISSUE TITLE
InitializeComponent should cache the same Uris

### ISSUE THREAD

**Issue by eerhardt** [dotnet/maui#4642]
### Description

In profiling the startup of an Android Maui app, I see InitializeComponent taking up a decent amount of time. Drilling in, I see that System.Uri's constructor is taking up a good chunk of time in the App's InitializeComponent:

![image](https://user-images.githubusercontent.com/8291187/153686205-168f4e71-02b2-450c-bf71-e952f8e5e24e.png)

Looking at the generated code, it is pretty clear what the issue is:

```C#
	[GeneratedCode("Microsoft.Maui.Controls.SourceGen", "1.0.0.0")]
	private void InitializeComponent()
	{
		Color value;
		VisualDiagnostics.RegisterSourceInfo(value = (Color)new ColorTypeConverter().ConvertFromInvariantString("#512bdf"), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 9, 14);
		Color value2;
		VisualDiagnostics.RegisterSourceInfo(value2 = (Color)new ColorTypeConverter().ConvertFromInvariantString("White"), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 10, 14);
		DynamicResourceExtension dynamicResourceExtension;
		VisualDiagnostics.RegisterSourceInfo(dynamicResourceExtension = new DynamicResourceExtension(), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 13, 46);
		Setter setter;
		VisualDiagnostics.RegisterSourceInfo(setter = new Setter(), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 13, 18);
		Setter setter2;
		VisualDiagnostics.RegisterSourceInfo(setter2 = new Setter(), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 14, 18);
		Style style;
		VisualDiagnostics.RegisterSourceInfo(style = new Style(typeof(Label)), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 12, 14);
		DynamicResourceExtension dynamicResourceExtension2;
		VisualDiagnostics.RegisterSourceInfo(dynamicResourceExtension2 = new DynamicResourceExtension(), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 18, 46);
		Setter setter3;
		VisualDiagnostics.RegisterSourceInfo(setter3 = new Setter(), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 18, 18);
		Setter setter4;
		VisualDiagnostics.RegisterSourceInfo(setter4 = new Setter(), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 19, 18);
		DynamicResourceExtension dynamicResourceExtension3;
		VisualDiagnostics.RegisterSourceInfo(dynamicResourceExtension3 = new DynamicResourceExtension(), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 20, 52);
		Setter setter5;
		VisualDiagnostics.RegisterSourceInfo(setter5 = new Setter(), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 20, 18);
		Setter setter6;
		VisualDiagnostics.RegisterSourceInfo(setter6 = new Setter(), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 21, 18);
		Style style2;
		VisualDiagnostics.RegisterSourceInfo(style2 = new Style(typeof(Button)), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 17, 14);
		ResourceDictionary resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary = new ResourceDictionary(), new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 7, 10);
		App app;
		VisualDiagnostics.RegisterSourceInfo(app = this, new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute), 2, 2);
```

Calling `new Uri("App.xaml" + ";assembly=" + "MauiTest", UriKind.RelativeOrAbsolute)` 15 times in unnecessary. We should just call it once, and then store it in a local variable.

### Steps to Reproduce

1. `dotnet new maui`
2. `dotnet build -f net6.0-android -t:Run -c Release`
3. Profile the app using https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

No

**Comment by eerhardt** [comment]
Looking into the XamlCTask code, it appears the reason this code is even in the Release build in the first place is because we are defaulting `DebugType` to be `portable` in the [core SDK](https://github.com/dotnet/sdk/blob/356f28cc6abeea084bab1cfef4b1fe7b07db803c/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L85):

![image](https://user-images.githubusercontent.com/8291187/154171753-59b99279-4e8a-4e90-841b-73710057f441.png)

And the code is checking for `none`:

https://github.com/dotnet/maui/blob/8737ee0219e021cce93a26449e7e373e0bb9a20b/src/Controls/src/Build.Tasks/XamlCTask.cs#L289-L293

If I explicitly set `<DebugType>none</DebugType>` in my .csproj, I no longer see these calls to `RegisterSourceInfo` or `new Uri` showing up in the resulting IL.

**Comment by StephaneDelcroix** [comment]
@eerhardt thanks for investigating. Actually, we no longer run XamlC for Release builds at all, and we can remove those calls

**Comment by eerhardt** [comment]
> Actually, we no longer run XamlC for Release builds at all

This doesn't appear to be true according to my binlog for `dotnet build -f net6.0-android -r android-arm64 -t:Run -c Release`. Did you mean we don't run it for **Debug** builds?

**Comment by StephaneDelcroix** [comment]
Yep, that was I meant
