### ISSUE TITLE
Android app crashes when using ItemsSource property in Release mode

### ISSUE THREAD

**Issue by minmer** [dotnet/maui#4650]
### Description

App crashes after setting the ItemsSource property of an CollectionView. On debug mode everything works fine. The crash appears only in the release mode.

### Steps to Reproduce

1. Create a File > New .Net MAUI App
2. Add a CollectionView
3. Set the ItemsSource property of the CollectionView in the code-behind
4. Set release mode

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 9.0

**Comment by minmer** [comment]
A workaround for CollectionViews is to use ObservableCollections istead of other enumerable objects. This workaround seems not to work for ListViews.

**Comment by wenwen60** [comment]
Not repro on Android 11 using VS2022(17.2.0 Preview 2).
