### ISSUE TITLE
[Bug] Frame CornerRadius Not working properly when Margin is setup to minus value (push to top)

### ISSUE THREAD

**Issue by shinnthant-lab** [dotnet/maui#4656]
### Description

Basically, frame corner radius lost on bottom when push to top by margin set to minus value. please see the screen shot for more detail.

![image](https://user-images.githubusercontent.com/54578974/153811055-b88703ef-8293-47ec-b4ee-1bf4e023b8e9.png)

### Steps to Reproduce

1. add a content page to .net maui preview 12 project.
2. add a stacklayout at top, a grid at bottom.
3. add a frame with corner radius  to bottom grid and play the margin value to minus to push the frame to top.

![image](https://user-images.githubusercontent.com/54578974/153811215-be1da348-2eeb-4b19-af2c-3cc43e6c81a0.png)

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

not yet

**Comment by shinnthant-lab** [comment]
For Android, I just tested and the issue is not same.
The frame corner radius working fine, but when I push to top, it's elongate instead of pushing top.

![image](https://user-images.githubusercontent.com/54578974/153817359-e9cfd129-8cfa-442a-899d-c71a650802dd.png)

**Comment by JohnHDev** [comment]
@shinnthant-lab as a work around, TranslateY might work better for you. Or, it might have the same issue! But it might help.

**Comment by shinnthant-lab** [comment]
> , it might have the same issue! But it might help.

Thanks John, I'll give it a try.

**Comment by shinnthant-lab** [comment]
TranslateY did the trick John, thanks again bro @JohnHDev

**Comment by YuqinSong** [comment]
Not reproducible on Windows. Frame CornerRadius works fine when play the margin value to minus to push the frame to top
![image](https://user-images.githubusercontent.com/99384766/155940866-a486ba79-3e8a-4f64-b266-a77b0bd51e8f.png)
