### ISSUE TITLE
Cannot generate valid Android apk

### ISSUE THREAD

**Issue by Xiphereal** [dotnet/maui#4660]
### Description

I've tried to change the package bundle from aab to apk, for generating the apk through `Archive...`, but I couldn't find the related option on the project properties, as I can on the Android project on a Xamarin Forms app (Android Options > Android Package Format). I've tried to force the `Archive Manager` to generate a apk by manually editing the .csproj file, with the following lines:
```XML
<PropertyGroup>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidPackageFormat>pkg</AndroidPackageFormat>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidCreatePackagePerAbi>false</AndroidCreatePackagePerAbi>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidDexTool>dx</AndroidDexTool>
</PropertyGroup>
```

but it fails stating that `Failed to create App archive 'AppName'. Invalid Android Archive (no .apk files)`.

Is there something I'm doing wrong here? 

P.D: I don't know if generating an apk is a expected current feature, or if it isn't and this should be a feature request. Just tell :D

### Steps to Reproduce

1. Create a blank MAUI app project.
2. Manually edit the `.csproj` to add the former lines.
3. Ensure the build is configured for `Release`.
4. Try to archive the app. 

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No.

**Comment by jfversluis** [comment]
Hey @Xiphereal creating archives trough the UI is not supported yet. For now you will have to do that by the command-line. For more info see also #4377. Of course, support will come for this in Visual Studio as well.

Is there any reason you want to create a pkg? I think aab is the only supported format for the Google Play Store now?

In any case, I think if you use this: https://github.com/dotnet/maui/issues/4377#issuecomment-1025964010 a pkg file is also still created. Does that one work for you?

Additionally I see an error as you described in this ticket here: https://developercommunity.visualstudio.com/t/xamarin-forms-android-apk-failure/669333

Maybe @jonathanpeppers has the definitive answer here as well.

**Comment by jonathanpeppers** [comment]
I'm a little confused, `.pkg` is a macOS installer file? What does that have to do with Android?

Can you build the app for Android-only such as:

```
> dotnet build -c Release -f net6.0-android -bl
```

This will create a `msbuild.binlog` file in the current directory. Share it here, and we can take a look. Thanks!

**Comment by Xiphereal** [comment]
> Is there any reason you want to create a pkg? I think aab is the only supported format for the Google Play Store now?

In this case, Appium, our UI testing framework, requires an `apk` for testing Android apps. Even thought generating an `apk` from an `aab` is possible (https://appium.io/docs/en/writing-running-appium/android/android-appbundle/), we'd like the convenience of generating it directly.

> In any case, I think if you use this: https://github.com/dotnet/maui/issues/4377#issuecomment-1025964010 a pkg file is also still created. Does that one work for you?

I'm afraid not, the installed app crashes on launch, both on Debug and Release.

> I'm a little confused, `.pkg` is a macOS installer file? What does that have to do with Android?

Oh, I'm so sorry, I wanted to say `apk` instead. Apologies to both of you for the confusion :( 

> Can you build the app for Android-only such as:
> 
> ```
> > dotnet build -c Release -f net6.0-android -bl
> ```
> 
> This will create a `msbuild.binlog` file in the current directory. Share it here, and we can take a look. Thanks!

Sure, here you have it: https://mega.nz/file/9c9m3IKC#KkWfvrm3jzb4LU2xjq36ojjzawz_ZpBUYKjhPu2gtjE

**Comment by jonathanpeppers** [comment]
@Xiphereal when you do `dotnet build -c Release -f net6.0-android` it should produce both `.aab` and `.apk` files by default.

I see your `.binlog` doing that, do you see the file?
```
Extracting universal.apk to com.companyname.acceptancetestingmauiapp-Signed.apk
```

`.aab` are suitable for submission to Google Play, but we made it also produce an `.apk` for things like beta testing, or other test tools, etc.

**Comment by jonathanpeppers** [comment]
Ok, what _is_ the crash?

You should check `adb logcat` output, some instructions here:

https://docs.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log#accessing-from-the-command-line

**Comment by Xiphereal** [comment]
This is the excerpt related to the app, from `adb logcat`: [log.txt](https://github.com/dotnet/maui/files/8067945/log.txt)
Hope it's of any help :)

**Comment by jonathanpeppers** [comment]
Does the `ListView` have an item template? I don't see where `TextCell` would be used in the above `.xaml`?

Is it just setting a `string[]` to the `ListView`? Maybe the default item template would inflate `TextCell`'s?

**Comment by Xiphereal** [comment]
> @Xiphereal there was an issue with both ViewCell/TextCell and the linker (Release builds). This should address it: #4769

When is this hotfix going to be available? I think this issue has been closed by mistake :)

> Is there another problem here, though? The issue title doesn't match the problem. Are you hitting any problems in debug builds?

I've changed the title to "Cannot generate valid Android apk", hope that is more clarifying. Using the apk generated in Debug, the app also crashes, here is the full logcat for that:
[logcatOutput.txt](https://github.com/dotnet/maui/files/8107356/logcatOutput.txt)

**Comment by jonathanpeppers** [comment]
To solve workaround the release build issue, you can probably put `new TextCellRenderer()` somewhere in your app to preserve it. You wouldn't have to actually call it.

The debug build issue is:
```
02-21 08:56:06.493 11762 11762 F monodroid: No assemblies found in '/data/user/0/com.companyname.acceptancetestingmauiapp/files/.__override__' or '<unavailable>'. Assuming this is part of Fast Deployment. Exiting...
```

This means that no .NET assemblies were sideloaded during deploy.

Can you get the `msbuild.binlog` file from this command and share it?

```
> dotnet build -t:Clean,Run YourApp.csproj -f net6.0-android -bl
```

Thanks!

**Comment by Xiphereal** [comment]
> To workaround the release build issue, you can probably put `new TextCellRenderer()` somewhere in your app to preserve it. You wouldn't have to actually call it.
> 

I've added a `new TextCellRenderer()` on the Android `MainActivity.cs`, but the apk installed app still crashes. Here is the log: [logcatOutput2](https://github.com/dotnet/maui/files/8123598/logcatOutput2.txt)


> The debug build issue is:
> 
> ```
> 02-21 08:56:06.493 11762 11762 F monodroid: No assemblies found in '/data/user/0/com.companyname.acceptancetestingmauiapp/files/.__override__' or '<unavailable>'. Assuming this is part of Fast Deployment. Exiting...
> ```
> 
> This means that no .NET assemblies were sideloaded during deploy.
> 
> Can you get the `msbuild.binlog` file from this command and share it?
> 
> ```
> > dotnet build -t:Clean,Run YourApp.csproj -f net6.0-android -bl
> ```
> 
> Thanks!

Here is the output: [dotnetBuildLog.txt](https://github.com/dotnet/maui/files/8123607/dotnetBuildLog.txt) 
Building through VS (F5 or ctrl+F5) works fine, though.

Thanks in advance :)

**Comment by Xiphereal** [comment]
> Here is the output: [dotnetBuildLog](https://github.com/dotnet/maui/files/8123607/dotnetBuildLog.txt) 
> Building through VS (F5 or ctrl+F5) works fine, though.

If migrated to preview 13, and now the output is this: [dotnetBuildLogPreview13](https://github.com/dotnet/maui/files/8131516/dotnetBuildLogPreview13.txt)

**Comment by Xiphereal** [comment]
Any updates? Thanks in advance :)

**Comment by VincentBu** [comment]
> creating archives trough the UI is not supported yet
Hi @jfversluis , feel free to remove `s/verified` tag if it isn't proper here.

**Comment by jonathanpeppers** [comment]
@Xiphereal sorry for the delay, catching up on this...

For this error now:
```
Mono.AndroidTools.InstallFailedException: Unexpected install output:  pkg: /data/local/tmp/com.companyname.acceptancetestingmauiapp-Signed.apk
```
What device are you using that is hitting this issue?

Can you put this in your `.csproj` and get a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)? Thanks!

```xml
<_FastDeploymentDiagnosticLogging>true</_FastDeploymentDiagnosticLogging>
```

**Comment by Xiphereal** [comment]
> What device are you using that is hitting this issue?

An emulator.

> Can you put this in your `.csproj` and get a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)? Thanks!
> 
> ```
> <_FastDeploymentDiagnosticLogging>true</_FastDeploymentDiagnosticLogging>
> ```

I'm afraid that the log is quite big and I cannot share it as it is (cannot updload the file to any file exchange platforms due to company security policies and URL restrictions, and our email service doesn't allow files or body contents that big). Anything I should be looking for? Any specific part you want to see?

**Comment by jonathanpeppers** [comment]
Can you share the section of log from the `<FastDeploy/>` MSBuild task? You could also email me at the address on my Github profile if you want to share privately.

**Comment by Xiphereal** [comment]
I've search for `FastDeploy` on the log, but the only things I could find was 
```
_FastDeploymentDiagnosticLogging = True
...
AndroidFastDeploymentToolVersion = 31.3.200-preview.13.41
AndroidFastDeploymentType = Assemblies
```

I'd like to remark that this is a successful build via VS, not the one from:
```
> dotnet build -t:Clean,Run YourApp.csproj -f net6.0-android -bl
```

**Comment by jonathanpeppers** [comment]
@Xiphereal you should see a message like `Task "FastDeploy"` and a block of text for everything it did -- including each `adb` command. I was hoping we could see exactly what went wrong.

Do you not see that? Maybe the logging isn't diagnostic?

**Comment by Xiphereal** [comment]
Email sent with the `Task "FastDeploy"` diagnostic log :)

**Comment by jonathanpeppers** [comment]
I believe there was discussion of three separate problems here.

For the FastDeploy issue, closing this and moving to: https://github.com/xamarin/xamarin-android/issues/6945

If you have other Android-related issues, file them for us there, thanks!
