### ISSUE TITLE
Partial methods not compiling in MAUI Class Libraries

### ISSUE THREAD

**Issue by rctec-at** [dotnet/maui#4666]
### Description

If i create a Control with a renderer(using the partial method approach to not require compiler directives the normal approach works fine. 
But if i port that code 1:1 in a Maui class library, the code reports "CS8795 Partial method 'TintableImageHandler.InitHandler(IViewHandler, TintableImage)' must have an implementation part because it has accessibility modifiers." for the non platform .net6 project
 

### Steps to Reproduce

Create a Maui App and Class Library. Use the following code and structure:

Control:
`public class TintableImage : Image
{
    #region properties

    public static readonly BindableProperty TintColorProperty =
        BindableProperty.Create(
            nameof(TintColor),
            typeof(Color),
            typeof(TintableImage));
    public Color TintColor
    {
        get => (Color)GetValue(TintColorProperty);
        set => SetValue(TintColorProperty, value);
    }

    #endregion

    public static void InitHandler()
    {
        ImageHandler.ViewMapper.AppendToMapping("TintColor", (handler, view) =>
        {
            if (view is TintableImage ti)
            {
                TintableImageHandler.InitHandler(handler, ti);
            }
        });
    }

}`

Handler "Definition":
`internal static partial class TintableImageHandler
{
    public static partial void InitHandler(IViewHandler handler, TintableImage ti);
}`

Handler "Android Implementation"
`internal static partial class TintableImageHandler
{
    public static partial void InitHandler(IViewHandler handler, TintableImage ti)
    {
        if (handler.NativeView is AppCompatImageView iv
                    && PorterDuff.Mode.SrcIn is not null)
        {
            var filter = new PorterDuffColorFilter(ti.TintColor.ToNative(), PorterDuff.Mode.SrcIn);
            iv.SetColorFilter(filter);
        }
    }
}`

The Project Structure for the Class library looks like this:
[https://prnt.sc/26vm533](https://prnt.sc/26vm533)

Now just try to call "TintableImage.InitHandler()" from your app.

The code does not compile

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Irrelevant, since it is compile time

### Did you find any workaround?

-

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8795	Partial method 'TintableImageHandler.InitHandler(IViewHandler, TintableImage)' must have an implementation part because it has accessibility modifiers.	MauiCore.Controls (net6.0)	C:\GITHUB\MauiCore\Source\MauiCore.Controls\TintableImage.cs	51	Active
```

**Comment by rctec-at** [comment]
@jfversluis as stated, if i put the exact code in a maui app, it works as expected. Partial classes are nothing new or special. Also i know about the rules how to use them in normal context.

the problem only arrises if it is put into a maui class library. but for completness i will provide a repo later.

**Comment by rctec-at** [comment]
@jfversluis i have to crawl away ashamed.... 
i had my partial methods public. i just removed the modifier (as the error was telling me) and called my method from a proxy method. then it all worked fine. i really dont know what i was confirming working in the app then...

the proxy method is kind of not pretty, but it works totally fine. 
https://prnt.sc/26w0lro

i am sure there is some internal limitation, that needs partial methods to be without access modifiers. but i will read into this later on.

sorry @jfversluis @jsuarezruiz  for wasting your time here. my apollogies

**Comment by jfversluis** [comment]
No need to be ashamed @rctec-at ! We all make mistakes :) glad you figured this one out!
