### ISSUE TITLE
Grid only renders and lays out first child

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#4671]
### Description

I have a Grid layout set as a Content to a ScrollView. Inside the Grid I have two children - the first one is not visible (IsVisible is set to false) and the second one is visible:
```xaml
<ScrollView>   
    <Grid>
        <!-- If we switch the places of the two Labels the Text of the visible one will be visualized -->
        <Label Text="I am not visible" IsVisible="False"/>
        <Label Text="I am visible"/>
    </Grid>
</ScrollView>
```
When I run my application nothing is visialized. If I switch the places of the Children the visible child is visualized as expected.

### Steps to Reproduce

1. Run the attached project.
2. Navigate to the second page.
3. Notice that nothing is visualized.

[HelloMaui.zip](https://github.com/dotnet/maui/files/8062310/HelloMaui.zip)

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8 (at least) and up

**Comment by v-xiaofchen** [comment]
Verified repro with Android 11 and the above project.When I navigate to the second page,notice that nothing is visualized.
![Picture22](https://user-images.githubusercontent.com/99376012/155911508-3690d121-cc46-4d9e-854b-1bc9585743d1.png)
![Picture23](https://user-images.githubusercontent.com/99376012/155911515-fcaddfc7-c4aa-478f-a1cc-aca0f81c89cf.png)

**Comment by ivan-todorov-progress** [comment]
I have tested the following code snippet on all platforms - Android, iOS, MacCatalyst and Windows:

```
<Grid>
    <Label Text="John" IsVisible="False" />
    <Label Text="Doe" />
</Grid>
```

The problem is reproducible on all platforms, i.e. the second `Label` is not visible, but if I comment out the first `Label`, the second label becomes visible.

I am just letting you know, to test this bug on all platforms, when providing a potential fix. Please, keep in mind that the bug is a blocker for us, preventing us from using the `Grid` layout in many scenarios, without any viable alternative.

**Comment by mattleibow** [comment]
This reminds me of the issue that I saw somewhere that Grid only properly measured or layouts the first element or something... Does the visibility matter?

What happens if the grid has both labels visible:

```xaml
<Grid>
    <Label Text="First and very long label" />
    <Label Text="Second" />
</Grid>
```

Do you see both labels or just the 1?

**Comment by ivan-todorov-progress** [comment]
@mattleibow Yes, this is exactly the case - the visibility is what messes up the Grid. If this is a known issue, which we are duplicating, could you associate it here, so we can track the other one instead.

**Comment by mattleibow** [comment]
@hartez @PureWeen I thought someone opened this issue before - and I feel like that is why I know about it. But, I can't seem to find it.

If anyone knows of the issue, feel free to link to it.

Right now I am going to assume I can't find the issue because it does not exist and will update the title to be more accurate.

**Comment by davidortinau** [comment]
This renders nothing:

```
<ContentPage>
            <ScrollView>
                <Grid>
                    <Label Text="Not visible" IsVisible="false"/>
                    <Label Text="Is visible"/>
                </Grid> 
            </ScrollView>
        </ContentPage>
```

Even providing height or vertical options to the Grid will not result in showing the labels, but if I remove the ScrollView:

```
<ContentPage>
            <Grid>
                <Label Text="Not visible" IsVisible="false"/>
                <Label Text="Is visible"/>
            </Grid>
        </ContentPage>
```

<img width="397" alt="image" src="https://user-images.githubusercontent.com/41873/165865174-347d6ca6-abfe-4c07-aa57-0014ffafb0da.png">

**Comment by mattleibow** [comment]
OMG. The scrollview affects the second child of the grid??? 😱

**Comment by ivan-todorov-progress** [comment]
@mattleibow Perhaps the bug is somehow related to how the Grid is measured by its parent. I assume the ScrollView measures the Grid with double.PositiveInfinity, while the ContentView - with some fixed value. This is just a wild guess though.
