### ISSUE TITLE
RadioButton.Content renders type on Android

### ISSUE THREAD

**Issue by vincoss** [dotnet/maui#4683]
### Description

Android Content is truncated, Label control is display as a string
Windows label alignment issues, huge content space, width FillAndExpand not working

![maui-radiobutton-issues](https://user-images.githubusercontent.com/765328/153996637-ee515caa-b94f-4423-9101-3c058a530bba.PNG)

### Steps to Reproduce

` 
 <VerticalStackLayout HorizontalOptions="FillAndExpand" BackgroundColor="AliceBlue" Padding="10">
        <RadioButton Content="Default" />
        <RadioButton IsChecked="True" Content="Alignment Issue - Font Title" FontSize="Title" BackgroundColor="Pink" />
        <RadioButton>
            <RadioButton.Content>
                <Label Text="Label Default Size"/>
            </RadioButton.Content>
        </RadioButton>
        <HorizontalStackLayout>
            <RadioButton IsChecked="True" Margin="0" Padding="0" BorderColor="Red" BorderWidth="1"/>
            <Label Text="Radio and Label" FontSize="Title" HorizontalOptions="Start" VerticalOptions="CenterAndExpand"/>
        </HorizontalStackLayout>
        <RadioButton FontSize="Title" VerticalOptions="CenterAndExpand">
            <RadioButton.Content>
                Text Content
            </RadioButton.Content>
        </RadioButton>
    </VerticalStackLayout>
`

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows10.0.19041

**Comment by Amir-Care** [comment]
Not repro on Windows, Repro on Android, VS  Version 17.2.0 Preview 2.0 [32219.17.main]
- Windows:
  Label alignment has not  issue.

![image](https://user-images.githubusercontent.com/99456025/155641108-96626906-2e18-480e-a5a3-67e3fa55d616.png)

- Android:

1. Content is not truncated
2. Label control is display as a string

![image](https://user-images.githubusercontent.com/99456025/155642892-bcb6fe83-264f-4c0e-a6c8-f6b86e7f0863.png)

 Attached sample project 
[RadioButton Samples.zip](https://github.com/dotnet/maui/files/8138042/RadioButton.Samples.zip)

**Comment by davidortinau** [comment]
I'm not seeing any truncation issue. 

I can confirm the 3rd example is rendering the content children's type instead of rendering the actual content.

![image](https://user-images.githubusercontent.com/41873/165866344-5877667d-b907-450a-a67c-2bebad277283.png)

The secondary issue of vertical label alignment on Windows is bc of `FontSize="Title"`. Without that it aligns correctly, but with it the text seems to bottom align.

**Comment by jsuarezruiz** [comment]
This is a behavior inherited from Xamarin.Forms.
https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Core/RadioButton.cs#L533

We could use drawableLeft to add custom content (creating a drawable) although it would be a BitmapDrawable losing interaction if we add any interactive control in the Content.
