### ISSUE TITLE
Excessive space on the right side of a checkbox

### ISSUE THREAD

**Issue by srqdev** [dotnet/maui#4693]
### Description

I am in the process of converting an Xamarin Forms app over to Maui (basic testing to see what issues exist) and noticed that Checkboxes have an inconsistent spacing on the left and right side. Specifically the right side is excessively large. The spacing on either side should be equal.  Note that I only tried this on the Android platform, it could certainly exist on others.

### Steps to Reproduce

1. Create a new .NET Maui app.
2. Add a stacklayout control to constrain a checkbox and label as per
`<StackLayout HorizontalOptions="Center" Grid.Row="1" Orientation="Horizontal">
      <CheckBox BackgroundColor="Pink" />
      <Label BackgroundColor="Aqua" Text="Checkbox text" VerticalTextAlignment="Center" />
   </StackLayout>`

3. Run the app, note that there is a match wider space on the right side of the checkbox

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Emulator running API 30

### Did you find any workaround?

Add Margin="-10,0,0,0'. Crude but it works.

**Comment by Amir-Care** [comment]
Repro on Android and Windows , VS Version 17.2.0 Preview 2.0 [32219.17.main]

- Android

![Checkboxs_Android](https://user-images.githubusercontent.com/99456025/155664255-5c37dded-abdd-4ff0-b480-fad0c16f88e0.PNG)

- Windows

![image](https://user-images.githubusercontent.com/99456025/155664301-4add4d06-7f1c-48d1-bdae-3f8e19f994b3.png)

Repro  project: 
[MauiApp18.zip](https://github.com/dotnet/maui/files/8138971/MauiApp18.zip)

**Comment by viralrathod7** [comment]
Its strange that in Windows version of MAUI this checkbox is working fine without any excessive space on right side in Version 17.2.0 Preview 2.1 whereas its giving excessive space on right side in latest Version 17.2.0 Preview 3.0.

**Comment by davidortinau** [comment]
I see the issue on Windows:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/41873/165866990-f3bf999d-b398-4241-81c3-b186d898f56b.png">

and Android

<img width="331" alt="image" src="https://user-images.githubusercontent.com/41873/165867120-4c89520f-93ef-4ef3-baec-eadb8c44e2c4.png">

with main (rc3)

**Comment by XamlTest** [comment]
Verified this issue on Visual Studio Enterprise 17.6.0 Preview 3.0. This issue does not repro on Windows and Android emulator (13.0-API 33) with below Project: [4693.zip](https://github.com/dotnet/maui/files/11209013/4693.zip)

![image](https://user-images.githubusercontent.com/97647558/231400373-6ef0b36b-4427-4a1f-b995-c36aaacf8840.png)

![image](https://user-images.githubusercontent.com/97647558/231401071-46e55810-0f52-4d16-b882-375da124ef04.png)
