### ISSUE TITLE
Include Signing Key to MAUI project

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#4700]
### Description

Hi,

Currently, the Android Signing Key is saved under

/Users/jassim/Library/Developer/Xamarin/Keystore/[Solution Name]/..

and similarly, in Microsoft WIndows, I guess

This makes it difficult and risky when moving from. device to another device or when open the same from a cloud folder because the .keystore files are stored locally

It is also a problem when backing up the solutions and the developer might forget to include the .keystore files

I suggest adding a **Keys** folder in MAUI's Android project and make the files automatically stored there

### Public API Changes

N/A

### Intended Use-Case

N/A

**Comment by Eilon** [comment]
Are these files secret? If so, they can't go into source control or else you risk leaking secrets.

**Comment by Redth** [comment]
/cc @jonpryor 

I'm not sure there's any action here.  As @Eilon noted, this shouldn't generally be included in source control.  The debug keystore isn't really required to be the same everywhere since you should not publish to the app store with it.

**Comment by jrahma** [comment]
This can be solved by having the Keys folder exceluded from the source control. So the folder is only for VS use but when backing up my project I can just take the whole folder and everything is done
