### ISSUE TITLE
Element measurement related API should use platforms units for all platforms 

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#4704]
### Description

Hot Reload related API should use platforms units for all platforms 

### Steps to Reproduce

1. Open attached app.
2. Configure to build and run on Android Emulator. Select phone with high density, e.g. Pixel 5.
3. Build and run.
4. Click on Button.

**Actual**: text related to VisualTreeElementExtensions and ViewExtensions contains sizes and points in pixels
**Expected**: text related to VisualTreeElementExtensions and ViewExtensions contains sizes and points in platform units

[MauiApp9.zip](https://github.com/dotnet/maui/files/8075046/MauiApp9.zip)

![image](https://user-images.githubusercontent.com/48451158/154158440-73da0b83-f022-45f0-b199-649a53b3d745.png)

 

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android

**Comment by drasticactions** [comment]
Updated the title: The "Hot Reload" APIs (Like GetBoundingBox) all use platform specific APIs for getting the core platform element and making measurements off of that. VisualElement.Bounds does not (so it happens to match on, say, Windows, but not Android)

So, I believe, we need to talk about how and where these numbers are generated from and what is the "truth", as we were.

**Comment by Amir-Care** [comment]
Repro on Android, VS Version 17.2.0 Preview 2.0 [32219.17.main]

**Comment by hartez** [comment]
Closed by #7904.

**Comment by etvorun** [comment]
Verified. Everything seems to be okay on all platforms.
