### ISSUE TITLE
Grid within a Grid is not size constrained correctly

### ISSUE THREAD

**Issue by srqdev** [dotnet/maui#4724]
### Description

If I create a grid with two rows, one auto auto and one *. For the first row I create another grid and within that grid add a label. For the second row I just add a label. When run the only row that is shown is the first, it takes up the whole screen and as such is not constrained by the Auto setting.

### Steps to Reproduce

1. Create a new MAUI app.
2. Remove the contents of the mainpage and replace with 

```
<Grid RowDefinitions="Auto,*" >
        <Grid Grid.Row="0" Grid.Column="0" BackgroundColor="LightGreen" >
            <Label Margin="10,0" Text="This text will be seen" />
        </Grid>

	<Label Grid.Row="1" Margin="10,0" Text="This text will not be seen" />
</Grid>
```

3. Run the code, you will only see the first text label and not the second. 

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 31

### Did you find any workaround?

Add a heightrequest to the second grid.

**Comment by nickrandolph** [comment]
@srqdev can you check the description of this issue as I suspect some of the XAML has been cropped. If you encase it as code it should display correctly

**Comment by srqdev** [comment]
@nickrandolph Corrected my description. Sorry about that.

**Comment by Amir-Care** [comment]
Repro on Android, VS Version 17.2.0 Preview 2.0 [32219.17.main].
Sample project 
[MauiApp19.zip](https://github.com/dotnet/maui/files/8139200/MauiApp19.zip)

**Comment by dirivero** [comment]
This will be probably fixed by [this](https://github.com/dotnet/maui/pull/6217).

**Comment by hartez** [comment]
Confirmed, #6217 fixed this.
