### ISSUE TITLE
New Maui solution, AppDelegate intellisense issues

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#4726]
### Description

New or existing solution on a brand new VS2022 preview install with preview 13, the iOS AppDelegate doesn't resolve its dependencies at design time, e.g. full of red lines and unknown references. For example:

Error | CS0246 | The type or namespace name 'Foundation' could not be found (are you missing a using directive or an assembly reference?

MauiUIApplicationDelegate could not be found

Various other errors.

I can however build for iOS, but intellisense is broken in iOS projects.

### Steps to Reproduce

1. Create a new Maui project
2. Open the Platforms/iOS/AppDelegate.cs class
3. See broken intellisense/references

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 12

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

App still builds, but intellisense is broken if I need to do anything in native. Hot reload appears to also be affected.

**Comment by VladislavAntonyuk** [comment]
Change the target framework in the code editor from net6.0-Android to net6.0-iOS

but I agree, it’s annoying that Visual Studio doesn’t recognize the current context and doesn’t automatically switch the editor target framework

**Comment by VladislavAntonyuk** [comment]
By default

![image](https://user-images.githubusercontent.com/33021114/154492287-a098a138-b1cc-4e07-a55b-ce74f1386772.png)

issue fixed

![image](https://user-images.githubusercontent.com/33021114/154492351-eac27a62-dbe7-4af0-807c-a264260281f6.png)

**Comment by JohnHDev** [comment]
Ahhh FFS.....
Thank you @VladislavAntonyuk !

**Comment by JohnHDev** [comment]
Hmpf, still can't hot reload iOS as the other platforms all report errors even though Im not building for Android.

**Comment by shimingsg** [comment]
verified reproducible with VS 17.2.0 Preview 2.0 [32223.271.main]
![image](https://user-images.githubusercontent.com/20982341/155665215-e0dafca0-90dd-4114-8c8c-8d4d552e2c8a.png)

**Comment by alaatm** [comment]
This is broken for me (VS 2022 17.2.0 Preview 2.0) regardless of which target framework is selected in the editor. All of them have broken intellisense errors which is extremely annoying trying to figure out the real errors from the fake ones.

**Comment by Mephisztoe** [comment]
I am on current RC1 branch and can confirm this issue. Also, these errors prevent the build from succeed when targetting a local iOS Device using HotReload. Since I am also not able to get the current RC1 branch to pair with my MAC anymore, HotReload was the only alternative to further test my app on iOS. Guess I will have to wait then for the official RC1 release. :)

**Comment by cbaer-extron** [comment]
@Redth , not sure that #6198  should have been closed.  It's a separate issue from this one, even though @alaatm  mentions it above.  Is this a Visual Studio issue or a Maui issue.  Maybe it should be reported somewhere else.

**Comment by czirok** [comment]
> 

I confirm that it has been completely unusable for the last two months. When I open Platforms/*/MainActivity.cs and AppDelegate.cs and App.xaml.cs, I get 35 errors. That's the problem with the .NET MAUI Class Library.

Not just an AppDelegate problem. Complete Platforms/* problem.

**Comment by Redth** [comment]
If you turn off displaying intellisense errors these should go away.

The problem has to do with the source files being included 'behind the scenes' in the project system for TFM's when they shouldn't be.  This is now understood and being worked on and tracked internally with the VS / project system teams.

Unfortunately it's the root cause of a number of issues and while it doesn't seem obvious, it manifests into what you're seeing.

**Comment by czirok** [comment]
@Redth 

Unfortunately, it's not just an error list problem. Editing problem too.

Really looking forward to. Thanks for the reply.

![MAUIEditorErrors](https://user-images.githubusercontent.com/1266377/164466432-f16a431f-c521-43f2-abb1-64cd9b2077b3.png)

**Comment by VladislavAntonyuk** [comment]
For now, you need to manually switch the TargetFramework to remove the errors. It's annoying but doesn't block the build

**Comment by czirok** [comment]
> For now, you need to manually switch the TargetFramework to remove the errors. It's annoying but doesn't block the build

@VladislavAntonyuk Thanks. Where should I send the beer? :-)

**Comment by cbaer-extron** [comment]
This is how I get around the problem, temporarily.  But it means there will only be one Platform folder at a time. (not ideal)

<ItemGroup>
		<Compile Remove="Platforms\Android\*.cs" />
		<Compile Remove="Platforms\iOS\*.cs" />
		<Compile Remove="Platforms\MacCatalyst\*.cs" />
		<Compile Remove="Platforms\Windows\*.cs" />
	</ItemGroup>
	
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'">
		<Compile Include="Platforms\Android\*.cs" />
		<Compile Remove="Platforms\iOS\*.cs" />
		<Compile Remove="Platforms\MacCatalyst\*.cs" />
		<Compile Remove="Platforms\Windows\*.cs" />
	</ItemGroup>
	
	<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
		<Compile Remove="Platforms\Android\*.cs" />
		<Compile Remove="Platforms\iOS\*.cs" />
		<Compile Remove="Platforms\MacCatalyst\*.cs" />
		<Compile Include="Platforms\Windows\*.cs" />
	</ItemGroup>
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-ios'">
		<Compile Remove="Platforms\Android\*.cs" />
		<Compile Include="Platforms\iOS\*.cs" />
		<Compile Remove="Platforms\MacCatalyst\*.cs" />
		<Compile Remove="Platforms\Windows\*.cs" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-maccatalyst'">
		<Compile Remove="Platforms\Android\*.cs" />
		<Compile Remove="Platforms\iOS\*.cs" />
		<Compile Include="Platforms\MacCatalyst\*.cs" />
		<Compile Remove="Platforms\Windows\*.cs" />
	</ItemGroup>

**Comment by Redth** [comment]
Yes these problems are all symptoms of the same root cause.  Like I said, it's not exactly obvious but the summary is that the project system is not processing the include/exclude rules for compile items when/where they are getting set by the MAUI SDK for multitargeting and basically adds all of the TFM .cs files to every TFM causing a bunch of different symptoms to be exhibited in the IDE.

**Comment by thinkOfaNumber** [comment]
I couldn't get rid of this problem (on a previously working project, without changing anything). Even after updating to the latest VS preview, and running maui-check, and updating Android studio packages...

I created a new MAUI project which worked, so I compared the two csproj files and there are some differences which might be related. Hopefully this helps someone fix their existing project:

	diff --git a/MAUI.Test/MAUI.Test.csproj b/MAUI.Test/MAUI.Test.csproj
	index b81ff23..269ee39 100644
	--- a/MAUI.Test/MAUI.Test.csproj
	+++ b/MAUI.Test/MAUI.Test.csproj
	@@ -2,7 +2,9 @@

			<PropertyGroup>
					<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
	-               <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>
	+               <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net6.0-windows10.0.19041.0</TargetFrameworks>^M
	+               ^M
	+               ^M
					<OutputType>Exe</OutputType>
					<RootNamespace>MAUI.Test</RootNamespace>
					<UseMaui>true</UseMaui>
	@@ -14,21 +16,20 @@

					
					<ApplicationId>com.companyname.MAUI.Test</ApplicationId>
	-               <ApplicationId Condition="$(TargetFramework.Contains('-windows'))">9AB06029-2A5B-454E-81EB-F7B9C1C1D664</ApplicationId>
	+               <ApplicationIdGuid>0D05A13A-A63F-44EC-B25D-301C0AA621D1</ApplicationIdGuid>^M

					
					<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
					<ApplicationVersion>1</ApplicationVersion>

	-               <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net6.0-ios'">14.2</SupportedOSPlatformVersion>
	-               <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net6.0-maccatalyst'">14.0</SupportedOSPlatformVersion>
	-               <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net6.0-android'">21.0</SupportedOSPlatformVersion>
	-               <SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.17763.0</SupportedOSPlatformVersion>
	-               <TargetPlatformMinVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.17763.0</TargetPlatformMinVersion>
	-       </PropertyGroup>
	+               <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>^M
	+               <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>^M
	+               <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>^M
	+               <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>^M
	+               <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>^M
	+               <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>^M

	-       <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0-android|AnyCPU'">
	-         <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	+               <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>^M
			</PropertyGroup>

			<ItemGroup>
