### ISSUE TITLE
Maui Blazor Hybrid and authentication

### ISSUE THREAD

**Issue by curelom** [dotnet/maui#4731]
### Description

Trying to use Blazor authentication.  Whenever add either of the following packages

Microsoft.AspNetCore.Components.Authorization and/or
Microsoft.AspNetCore.Authorization

get the following error when compiling.
>C:\Program Files\dotnet\sdk\6.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'android-x64'.

### Steps to Reproduce

1. Create new Maui Blazor app.  Any of the latest betas have this issue
2. Add following to csproj file
```
<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="6.0.2" />
<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="6.0.2" />
```
3. Compile

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Any Android

### Did you find any workaround?

no

### Relevant log output

```shell
1>BigFlippingDeal.Maui -> C:\Users\david\Source\Repos\RealEstateLeads3\BigFlippingDeal.Maui\bin\Debug\net6.0-android\BigFlippingDeal.Maui.dll
1>C:\Program Files\dotnet\sdk\6.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'android-x64'.
1>Done building project "BigFlippingDeal.Maui.csproj" -- FAILED.
1>Done building project "BigFlippingDeal.Maui.csproj" -- FAILED.
```

**Comment by curelom** [comment]
Looks like it missed step 2.  Add the following to .csproj

<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="6.0.2" />
<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="6.0.2" />

**Comment by curelom** [comment]
PackageReference Include="Microsoft.AspNetCore.Authorization" Version="6.0.2" 
PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="6.0.2"

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by javiercn** [comment]
I can't reproduce this issue running on the Android emulator.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/6995051/155351406-9a9305e6-9dfa-4cb0-b76f-c4d5a12b7223.png">
