### ISSUE TITLE
MAUI WebView is not displaying body background-image

### ISSUE THREAD

**Issue by TonyHenrique** [dotnet/maui#4733]
### Description

I have a HTML wich has a background image but on Android it is not appearing, only a white background.

    <WebView Source="https://maui20220216.azurewebsites.net/test.html" />

I tried this same code on Xamarin and it correctly displays the background image.

The HTML page on the Source is like this:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<base href="~/" />
	<link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
	<link href="css/site.css" rel="stylesheet" />
	<link href="CartaoDescontoBlazorApp.styles.css" rel="stylesheet" />
	<component type="typeof(HeadOutlet)" render-mode="ServerPrerendered" />

	<!-- Chrome, Firefox OS and Opera -->
	<meta name="theme-color" content="#185177">
	<!-- Windows Phone -->
	<meta name="msapplication-navbutton-color" content="#185177">
	<!-- iOS Safari -->
	<meta name="apple-mobile-web-app-status-bar-style" content="#185177">
</head>
<body style="min-width:100vw; min-height:100vh;background-image:url('https://way2tutorial.com/images/img_nat.png') !important; background-attachment:fixed; background-position:center bottom; background-size: cover;">

</body>
</html>
```

### Steps to Reproduce

Create a page with this
```
 <html><body style="min-width:100vw; min-height:100vh;background-image:url('https://way2tutorial.com/images/img_nat.png') !important; background-attachment:fixed; background-position:center bottom; background-size: cover;"></body></html>
```
Publish this page

Create a new .NET MAUI
Insert this code in MainPage.xaml

`<WebView Source="https://maui20220216.azurewebsites.net/test.html" />`

Then notice that the background image is not being displayed on the Mobile App on Android.

If you visit the URL on a Desktop, you can see the background image:
 https://maui20220216.azurewebsites.net/test.html

Examples:

MAUI:
<img title="MAUI" src="https://user-images.githubusercontent.com/6307623/154459588-4f87c294-ce8a-4015-b230-4eb59107f459.jpg" width="25%" height="25%">

Xamarin Forms:
<img title="MAUI" src="https://user-images.githubusercontent.com/6307623/154459593-5f83357f-7fc6-47f7-b9ef-97e64af3344d.jpg" width="25%" height="25%">

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by pipearias2** [comment]
I have the same bug in my Maui App

**Comment by v-longmin** [comment]
Verified reproes. Repro project:    [4733.zip](\\\mlangfs1\Public\dotnet maui\Repro Project)

**Comment by TonyHenrique** [comment]
OK, I created a simple repro and also attached a screenshot from my mobile phone (HMD Global Nokia 5.3 (Android 11.0 - API 30)  to GitHub:
https://github.com/TonyHenrique/MAUI-WebView-BackgroundImage


```
Microsoft Visual Studio Community 2022
Version 17.2.0 Preview 2.0
VisualStudio.17.Preview/17.2.0-pre.2.0+32314.265
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA734
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.2.240.24236
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.2.240.24236
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.2.240.24236
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.2.0-2.22159.10+f3a5bad242b7a7b8149ae644de0a61c2f1bffc8d
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   17.1.10 (65f98f5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.0.32314.00
Microsoft Office Developer Tools for Visual Studio

Razor (ASP.NET Core)   17.0.0.2215202+658e2db05d0daa9326356ee1edc85cd3d1b970c4
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62203.01080
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.8
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10302.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.2.0-2.22159.10+f3a5bad242b7a7b8149ae644de0a61c2f1bffc8d
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22108.1+63bcc94efda4fe19b612b167a25fdbcee796040b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   17.2.0.67 (main@19e0f04)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.2.0.64 (remotes/origin/main@3d19e6caf)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.1.13 (bb31b34)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.2.99.130 (main/e89ae42)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: f34bd77
    Java.Interop: xamarin/java.interop/main@aae23c97
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.0@ccd83d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@f0b3abd


Xamarin.iOS and Xamarin.Mac SDK   15.7.0.410 (478c1d2c8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by Zelif** [comment]
This seems to be an issue with the viewport and viewport units. No viewport units seem to work. (Fixed units work fine)
Current Version: Preview 14

Is there a way to set the viewport correctly or wrap the WebView so it forces the viewport to be filled out?
Will this be something the base WebView does not support and must be an override in a custom renderer per device?

**Comment by PureWeen** [comment]
@v-longmin can you try again with the latest and attach your repro project? It doesn't seem like it linked correctly

**Comment by kristinx0211** [comment]
not repro on android 11 and 12 with 17.4.0 Preview 1.0 [32704.40.main].
![image](https://user-images.githubusercontent.com/99457000/177258437-82652c76-ca58-4d24-b461-69d6e236907c.png)
![image](https://user-images.githubusercontent.com/99457000/177258601-de73b344-168e-429f-b983-e0cf35cedb53.png)

**Comment by TonyHenrique** [comment]
This issue was a show stopper for a project I was doing, because the customer had his Web App and the design included a background image that is not displayed on the client MAUI WebView on Android.

On the Desktop WebBrowser:
![image](https://user-images.githubusercontent.com/6307623/190304805-35d46ce7-8a01-4252-b635-608e7e2ed539.png)

But on MAUI / Android it looks similar to this:

![image](https://user-images.githubusercontent.com/6307623/190304895-f746bba8-5c73-44e2-9d3d-e23806f6e326.png)

the background image is not displayed.

**Comment by jsuarezruiz** [comment]
Testing with .NET MAUI 6.0.486 cannot reproduce the issue. Could you share more details like (the Android version, the manifiest properties etc)?
![image](https://user-images.githubusercontent.com/6755973/190428052-5604cffe-562a-47a7-974d-4c96ce1a3e31.png)

**Comment by TonyHenrique** [comment]
Right now, I created a new MAUI app using Visual Studio 2022 Preview Version 17.4.0 Preview 2.0
Here it is:  maui-android                             6.0.486/6.0.400          VS 17.4.32912.340
The device is a HMD Global Nokia 5.3 (Android 11.0 - API 30)

![image](https://user-images.githubusercontent.com/6307623/190438870-e2a12c5e-d305-4fc9-9cf6-99aedbeb27b7.png)

![image](https://user-images.githubusercontent.com/6307623/190439498-0ea6cc7c-713e-4e28-95b5-ea219e023b4e.png)

the background imager does not appear.
![WhatsApp Image 2022-09-15 at 12 10 15](https://user-images.githubusercontent.com/6307623/190440643-f4f6f4e9-b080-4a03-9df2-996bb2ec2434.jpeg)

**Comment by TonyHenrique** [comment]
Attached that repro .sln that I created, displayed on the picture above:
[MauiApp-4733.zip](https://github.com/dotnet/maui/files/9576715/MauiApp-4733.zip)

**Comment by vhugogarcia** [comment]
Hello @TonyHenrique , I'm unable to reproduce the issue on the emulators at Android.

Could you try adding a WidthRequest and HeightRequest to the Webview? please.
` <WebView Source="https://maui20220216.azurewebsites.net/test.html" HeightRequest="500" WidthRequest="800" />`

<img width="407" alt="image" src="https://user-images.githubusercontent.com/1047398/190454377-942dca58-6f1a-469d-b12e-7a2392b9ae14.png">

**Comment by TonyHenrique** [comment]
@vhugogarcia , 
Now I tried this on the real device, a HMD Global Nokia 5.3 (Android 11.0 - API 30):

`<WebView Source="https://maui20220216.azurewebsites.net/test.html" HeightRequest="800" WidthRequest="350"   />`

And this is the result, no background image:
![IMG_1779](https://user-images.githubusercontent.com/6307623/190461380-8c29857b-6687-4f52-95cf-20bc80284e48.jpg)

**Comment by TonyHenrique** [comment]
Hey, I checked now with maui-android version 7.0.0-rc.1.6683/7.0.100-rc.1

and the background image is being displayed!

![image](https://user-images.githubusercontent.com/6307623/191362516-fd4a6317-ca11-40cc-b697-42717396225a.png)

**Comment by TomCJones** [comment]
i can get it on android, but not on iphone

**Comment by TonyHenrique** [comment]
@TomCJones can you add what is displayed when running:

`dotnet workload list`

**Comment by TomCJones** [comment]
The displays on android and iPhone are identical, except that the background image is mission on iPhone, Here is the XAML for that
    <ContentPage.BindingContext>
        <local:IdentityViewModel x:Name="viewModel" />
    </ContentPage.BindingContext>
    <ContentPage.Content>
        <Grid>
            <Image Source="{Binding BackgroundImage}"
                   Aspect="AspectFill" />
            <StackLayout VerticalOptions="StartAndExpand" Background="transparent">

**Comment by TomCJones** [comment]
i have the simplest possible repro - install fresh VS 17.3.5 - create maui app for android & ios - change color on appicon (in both the svg and the csproj) the color changes on android and not on ios.
