### ISSUE TITLE
The splash screen icon (Assets\appiconfgSplashScreen.png) listed in the manifest is not found

### ISSUE THREAD

**Issue by mobycorp** [dotnet/maui#4736]
### Description

Creating a simple out-of-the-box .NET MAUI application in VS 2022 v17.2.0 Preview 1.0 with MAUI preview 13 has an error that will not allow an unchanged new application to compile.  This is the error displayed in the output window:

`DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(33,27): error 0x80070003: Cannot install or update package C2825F9A-1C95-43C1-96C9-3ABE72D02D1D_9zz4h110yvjzm because the splash screen image [appiconfgSplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found.`

The manifest file also lists the logo icon as `<Logo>Assets\appiconStoreLogo.png</Logo>` but that does not prevent the app from building.  The files `appiconStoreLogo.png` and `appiconfgSplashScreen.png` are not installed when the project is scaffolded.

### Steps to Reproduce

1. Create new .NET Maui app
2. Run the app (with no changes)
3. It complains about the splash screen icon not being found

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 12

### Affected platforms

Windows

### Affected platform versions

Dependency net6.0-windows10.0.19041

### Did you find any workaround?

I simply commented it out in the Platforms\Windows\Package.appxmanifest file and it ran correctly albeit without the dotnet_bot image being displayed (reported in an another bug report

### Relevant log output

```shell
DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(33,27): error 0x80070003: Cannot install or update package C2825F9A-1C95-43C1-96C9-3ABE72D02D1D_9zz4h110yvjzm because the splash screen image [appiconfgSplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found.
```

**Comment by Gogzs** [comment]
For me, trying to build a project created with Preveiw 12, after updating to Preview 13, failed to build. 
Fix was, edit Package.appxmanifest and remove "Assets\" from the logo/splashcreen paths. 

Creating a new project on preview 13 had the correct paths in Package.appxmanifest and would build normally after being freshly created.

**Comment by egvijayanand** [comment]
Faced the same issue and after following the migration step, link below, it got resolved. Give it a try.

https://github.com/dotnet/maui/wiki/Migrating-to-Preview-13

**Package.appxmanifest file needs to be updated, remove the `Assets` folder**.

**Comment by jfversluis** [comment]
It looks like you have preview 13 but not the preview 13 templates. Would you be able to run `dotnet new -i Microsoft.Maui.Templates`, does that indicate an update?

And could you then try again? I'm fairly confident that this and the dotnet bot issue should go away

**Comment by egvijayanand** [comment]
Seems like template issue #3312 is still open.

Couldn't able to check this time as I updated to Pre13 a bit early with CLI install.

**Comment by mobycorp** [comment]
@jfversluis - I completely uninstalled all versions of  ,NET 6 SDKs and runtimes, all versions of Visual Studio, rebooted, and reinstalled everything. I would have to imaging that such drastic actions would've corrected any missing or out-of-date templates.

@egvijayanand  - I looked for a migration document and didn't see this. Thanks for the pointer!

In any event, we should not have to modify the manifests in any way, shape, or form. The project creation should just work. I only reported this issue as the manifest calls out for image files that do not exist so I would expect the development team to fix this minor oversight...

**Comment by jfversluis** [comment]
@mobycorp please bear in mind that you are working with preview bits, bugs are to be expected. If everything plays along well and you installed preview 13 with the corresponding preview 13 templates you don't have to open a manifest file nor edit it and it should work with image files that do exist.

The only reason this is happening is because the functionality changed between versions and since they are preview versions we are not concerned with keeping it backwards compatible at this time.

What I don't read in your comment, maybe I missed it sorry about that, is... Is it working right now for you? :)

**Comment by mobycorp** [comment]
@jfversluis - Yes, I am fully aware of the fluidity of working with a preview release. It is only my intention to log issues as I encounter them in the hopes to make this a superior framework!! I am trying to work through the issues, find work arounds, and log them. I am actually enjoying the process extremely! ;-)

As far as getting any of these issues to work, no, I am not finding a way to overcome some of these issues, but my app does run and allows me to explore other capabilities. I am just trying to contribute, and I hope I have not come across as though I was complaining about anything, nor was I expecting the preview releases to stay backward compatible or bug free. Hopefully, I am contributing in a positive way. ;)

**Comment by mobycorp** [comment]
This has been a fun day of learning!

As @jfversluis recommended, I did do a dotnet new -i microsoft.maui.templates and when I created a new project, guess what... The odd image behavior was solved! But, in one of my test projects, I had the line `windows:Application.ImageDirectory="Assets"` in the App.xaml which then caused the images to not appear in my first test app. When I removed that element, images started to appear! Yea!!

So, I don't want to close this issue...  I will let @jsuarezruiz close it so that he is aware of what I did to resolve the issue.

**Comment by jfversluis** [comment]
No worries @mobycorp ! We're (well... I am!) very happy that you're such an early adopter and even providing feedback, so thank you for that! I was worried that you might not be because you mentioned "I don't want to be bothered manually editing manifest files". I guess that's the problem with written text ;)

Again, thanks so much and please keep going and more importantly keep enjoying it! Feel free to ping me on anything if you need something.

I'm going to steal Javiers thunder and close this one for now. Have a great weekend ahead!
