### ISSUE TITLE
Do not run sIn file in  Visual Studio 2022 for Mac version 17.0 Preview 6 

### ISSUE THREAD

**Issue by xing123456789** [dotnet/maui#4741]
### Description

I have some problems when I use Visual Studio 2022 for Mac version 17.0 Preview 6 .
1、"Debug" Layout miss some file when I open sIn file
![1645067631140](https://user-images.githubusercontent.com/95727133/154419876-7a730e19-5b0a-4f2a-827c-12a4ebee31d3.jpg)

2、it shows "The application has not been built" when I click run button
![1645067572585](https://user-images.githubusercontent.com/95727133/154419907-dcca5fcd-b4c9-44e5-8930-5336f08f7a58.jpg)
how can I solve these problems
Thanks

### Steps to Reproduce

1. create a app -> open sIn -> missing file content
2. open csproj -> click "run" -> The application has not been built

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS15

**Comment by jfversluis** [comment]
Thanks for the report @xing123456789! This is unfortunately outside our control. I think .NET MAUI support isn't there for Visual Studio for Mac yet.

If you want to report anything to the Visual Studio team, please do so through the Help > Report a Problem menu. Thanks!

**Comment by xing123456789** [comment]
May I ask which version will it support And What time will it be released?
Thanks

**Comment by jfversluis** [comment]
I think both of these things are unknown at this time, sorry!

**Comment by xing123456789** [comment]
https://user-images.githubusercontent.com/95727133/155442431-99c66363-0d88-4f04-bc0e-438cbad21e7a.mp4

This is my screen recording to create a maui program
