### ISSUE TITLE
[Android]RTL flow direction not working for image

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#4743]
### Description

When setting Flow direction to RightToLeft to the image added parent and the image not aligned based on flow direction in Android.

### Steps to Reproduce

1. Run the below-attached sample
[RTLSample.zip](https://github.com/dotnet/maui/files/8086249/RTLSample.zip)

2. See the below output. Image not aligned based on the RTL flow direction. Labels are aligned based on the RTL flow direction.
![Screenshot_1645081937](https://user-images.githubusercontent.com/92785406/154424846-8516d052-ef34-42a8-a54d-9b99c51c8e79.png)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by Amir-Care** [comment]
Repro on Android, VS Version 17.2.0 Preview 2.0 [32219.17.main]

**Comment by hartez** [comment]
This was fixed by #5495
