### ISSUE TITLE
[Bug] In a Shell enabled App, after traversing to a page defined with the attached property `Shell.PresentationMode="ModalAnimated"` Flyout menu becomes inaccessible

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#4744]
### Description

In a Shell enabled App, after traversing to a page defined with the attached property `Shell.PresentationMode="ModalAnimated"` Flyout menu becomes inaccessible. This issue is observed when running in Windows as the target platform. Basically, the entire app becomes modal as inferred from the title bar change.

Refer to the attached before and after screenshots.

Before:
<img width="960" alt="dotnetmaui-shell-app-before-modal-navigation" src="https://user-images.githubusercontent.com/81947404/154431855-3c24c021-1c67-4e34-bf98-9cb9ff9f757c.png">

After:
<img width="960" alt="dotnetmaui-shell-app-after-modal-navigation" src="https://user-images.githubusercontent.com/81947404/154431928-d417f586-3a5d-4333-9390-f8c9cc36a780.png">

### Steps to Reproduce

1. Create a new .NET MAUI App, enable Shell navigation by adding a Shell Page and other Content pages
2. Have attached my definition in the zip format for simulating the issue
3. Switch Windows as the target platform, build and run the app
4. Traverse to the page enabled with the attached property `Shell.PresentationMode="ModalAnimated"` and come back to the original page
5. Now the Flyout menu becomes inaccessible and the entire app becomes modal

[ShellApp.zip](https://github.com/dotnet/maui/files/8086733/ShellApp.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All Windows versions

### Did you find any workaround?

Nope

### Relevant log output

```shell
Build succeeded, issue during runtime.

Have attached the source of the app (ShellApp.zip) for simulation.
```

**Comment by XamlTest** [comment]
Reproduced on Windows(OS: 19044.1526). 
Repro Project: [4744-FlyoutMenu.zip](https://github.com/dotnet/maui/files/8140643/4744-FlyoutMenu.zip)

**Comment by PureWeen** [comment]
This is most likely fixed on P14

I tested this on RC1 and it's definitely fixed there
