### ISSUE TITLE
Add npm support into .NET MAUI Blazor template

### ISSUE THREAD

**Issue by RaspeR87** [dotnet/maui#4745]
### Description

I would love to have NPM support inside .NET MAUI Blazor template, because with Blazor you could have MAUI app written on web development stack. And in that stack sometimes you want to have NPM, which could be managed by package.json file.

In package.json you want to have for example gulp task runner and you want to make some tasks like css minification, sass compiler, js uglifier, concatenation of js or css files etc etc.

What I miss in .NET MAUI Blazor template is support for restoring NPM packages directly with right mouse click on package.json file like in web templates inside Visual Studio. Now it is possible only with Package Manager Console with npm install command.

### Public API Changes

/

### Intended Use-Case

/

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Maybe this can help: https://devblogs.microsoft.com/dotnet/build-client-web-assets-for-your-razor-class-library/ ?

We don't have any immediate plans to do more here so closing for now.
