### ISSUE TITLE
Vertical Text of a Label?

### ISSUE THREAD

**Issue by mcguu** [dotnet/maui#4746]
### Description

Is there a Label that can make the text vertically?

This is my text to be

        T
        h
        i
        s
        
        i
        s
        
        m
        y

        t
        e
        x
        t

### Public API Changes

Label.TextFlowDirection?

### Intended Use-Case

To change the text from horizontal to vertical.

In chinese the text may be vertically.

**Comment by Amir-Care** [comment]
You can create a function to render the Label text verticaly.
Sample project : [MauiApp25.zip](https://github.com/dotnet/maui/files/8159368/MauiApp25.zip)
 
![image](https://user-images.githubusercontent.com/99456025/156119417-5464171a-0f2b-46c6-9cad-69188bf8c8ce.png)

**Comment by mcguu** [comment]
@Amir-Care  ok and I have create it using graphics drawString.

**Comment by mcguu** [comment]
And I am a newer to maui can you tell me how to create a control? I do not know the Platforms/Android how to write in it and there is no doc.

Should I create a file in android and ios and windows with same View?
