### ISSUE TITLE
[Windows]Flow direction RTL not working in HorizontalStackLayout

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#4748]
### Description

Flow direction RTL not working in HorizontalStackLayout

### Steps to Reproduce

1. Run the below-attached sample.
[RTL horizontalSample.zip](https://github.com/dotnet/maui/files/8088337/RTL.horizontalSample.zip)

2.HorizontalStackLayout content not changed based on the flow direction RTL in windows

3. See the below output
![image](https://user-images.githubusercontent.com/92785406/154472861-83b5c70e-1fbe-4e1d-9cd8-bec4a328ce05.png)

Content added inside HorizontalStackLayout (Label) not aligned based on the RTL.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041

**Comment by v-xiaofchen** [comment]
Not reproducible with 17.2.0 Preview 2.0 [32209.335.main] using Windows and above project. 
Content added inside HorizontalStackLayout (Label) can aligned based on the RTL.
![Picture20](https://user-images.githubusercontent.com/99376012/155687182-b0a78398-fe93-4c97-84db-aed20c53d480.png)

**Comment by jeya-kasipandi** [comment]
@v-xiaofchen  Can you check the above project on the Android platform? Both have different behavior.
In Android, content aligned as like below  screenshot when setting flow direction to  RTL
![Screenshot_1645780614](https://user-images.githubusercontent.com/92785406/155688843-9cd9717e-5152-4ced-8b4a-545734295c5a.png)

**Comment by v-xiaofchen** [comment]
Oh,yes, I have check the above project on the Android platform just now.Both have different behavior. 
I show the same with you on .Android
![Picture21](https://user-images.githubusercontent.com/99376012/155691977-968d212c-d1b9-45fd-82eb-44dbbde62a67.png)
