### ISSUE TITLE
Child view size exceeds the parent view size

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#4749]
### Description

When adding content view inside grid , content view height and width  exceeds the parent grid height and width in all platform.

### Steps to Reproduce

1. Run the below-attached sample.
[SizeSample.zip](https://github.com/dotnet/maui/files/8088548/SizeSample.zip)

2. See the output. In this project, Parent grid height(200) is set lesser than child view(content view) height(600) , child view bounds exceed the parent grid bounds.
![image](https://user-images.githubusercontent.com/92785406/154480679-e131e417-6351-4932-b0f3-a882c24619aa.png)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Windows 10.0.19041,Android 11

**Comment by v-xiaofchen** [comment]
Verified repro with windows/Android and the above project.
![Picture19](https://user-images.githubusercontent.com/99376012/155683287-86575311-a7a7-489c-905f-e6cbd0f1af44.png)

**Comment by Redth** [comment]
I think this is not a bug? you are requesting the size to be bigger.

@hartez I feel like we decided to respect these cases in MAUI, but perhaps you have more clarity on the intent here.

**Comment by davidortinau** [comment]
```
<Grid BackgroundColor="Red" HeightRequest="200">
        <ContentView BackgroundColor="Blue" HeightRequest="600">
            <Grid>
            <Label TextColor="White" Text="Content"></Label>
            </Grid>
        </ContentView>
    </Grid>
```

The expectation is that the child should be clipped by the parent unless `IsClippedToBounds` is set to false, right?

**Comment by hartez** [comment]
> ```
> <Grid BackgroundColor="Red" HeightRequest="200">
>         <ContentView BackgroundColor="Blue" HeightRequest="600">
>             <Grid>
>             <Label TextColor="White" Text="Content"></Label>
>             </Grid>
>         </ContentView>
>     </Grid>
> ```
> 
> The expectation is that the child should be clipped by the parent unless `IsClippedToBounds` is set to false, right?

The child should be clipped by the bounds of the parent if `IsClippedToBounds` is set to `true`. `IsClippedToBounds` defaults to 'false'. 

So this is behaving as expected.
