### ISSUE TITLE
[Android] Maui Blazor, static files from Razor Class Library not included in wwwroot 

### ISSUE THREAD

**Issue by Ghevi** [dotnet/maui#4758]
### Description

When deploying a Maui Blazor app on the android emulator or another android device, the files from a razor class library aren't included and in the console the get request fails. They are not included in the _content folder.
Works fine on Windows.
In the Razor class library, UseMaui is false. Trying with true didn't solve the issue.

By browsing to https://0.0.0.0/rclStyles.css instead of https://0.0.0.0/_content/{packageName}/rclStyles.css, the file is returned.
These files seems to be built into wwwroot instead of wwwroot/_content

### Steps to Reproduce

- Create new Maui Blazor project 
- Add an RCL 
- Run the app on android emulator or android device

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Yes, by adding
```
 <link href="rclStyles.css" rel="stylesheet" />
```
instead of
```
<link href="_content/{packageName}/rclStyles.css  rel="stylesheet" />
```
The former now works both on Windows and Android platforms.
The latter works on Windows and, just for throwing that in too, on Blazor Server projects.

### Relevant log output

```shell
In the network tab:

Request URL: https://0.0.0.0/_content/{packageName}/rclStyles.css
Request Method: GET
Status Code: 404 Not found

When fetching from wwwroot:

Request URL: https://0.0.0.0/rclStyles.css
Request Method: GET
Status Code: 200 OK
Referrer Policy: strict-origin-when-cross-origin

```

**Comment by v-longmin** [comment]
@Ghevi Could you share your repro project/solution, thanks?

**Comment by Ghevi** [comment]
> @Ghevi Could you share your repro project/solution, thanks?

Hi sorry for the delayed response. I'm not able to share a repo right now.
We only had images and file .css in the razor library, no .razor or .cs.
The solution we found was to add a file an empty class in a .cs file with the correct package's namespace.

**Comment by mkArtakMSFT** [comment]
@javiercn bringing this back to review for GA release. If you can't repro this - then great. Otherwise we need to get this addressed, if this is a mainline scenario.

**Comment by javiercn** [comment]
This works just fine with the latest version as per 
![image](https://user-images.githubusercontent.com/6995051/161784630-23bdd1fb-f247-4c75-95e1-39aae7dbc3e4.png)

Both CSS as well as scoped CSS load without issue.
