### ISSUE TITLE
Flyout margins and settings do not display correctly

### ISSUE THREAD

**Issue by mobycorp** [dotnet/maui#4762]
### Description

I have a simple flyout with a header and several pages defined in a shell xaml file. One of these issues has been present in both preview 12 and preview 13 and the other issue broke in preview 13. For reference, here is the top bit of the shell xaml file...

![image](https://user-images.githubusercontent.com/60759137/154544722-78705843-fc09-4f28-afc4-0d451ce982e3.png)

I am setting Flyout width to 210 pixels.  When the app is first fired up, the width setting is not honored as shown in the next screenshot. Also notice the placement of the flyout header and tab headers. They are evenly spaced from the top of the window. This broke in preview 13.

![Flyout width incorrect - flyout header margin correct - preview 12](https://user-images.githubusercontent.com/60759137/154543304-20abfe05-5b6c-440e-a090-a99119f37873.png)

You can see the width of the flyout is set to the default width and the 210 pixel setting is not being calculated.  If you simply change the page, the width is then properly calculated as shown in the next screenshot.

![Flyout width correct after page change](https://user-images.githubusercontent.com/60759137/154543560-8a7ea9dc-9e5e-4407-b830-aec02572b83d.png)

The flyout margin issue started in preview 13.  In preview 12 it was fine.

### Steps to Reproduce

1. Create a new .NET Maui project
2. Create a <Shell> layout with the code from above.  Include at least two pages of shell content.
3. Fire the app up. The flyout width will be incorrect.
4. Change the page tab. The flyout width will then be recalculated and display correctly.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Dependency net6.0-windows10.0.19041

### Did you find any workaround?

No

### Relevant log output

```shell
N/A
```

**Comment by PureWeen** [comment]
This is most likely related to this issue 
https://github.com/dotnet/maui/issues/4719

it seems like the new layouts don't take into account the margin when setting the frame or the code being used in `ListView` / `Shell` to measure is incorrect

**Comment by Redth** [comment]
This appears to be fixed in main:
![image](https://user-images.githubusercontent.com/271950/165992291-ddea4777-7c1f-4e61-8cfe-6992f75a1d99.png)
