### ISSUE TITLE
Span Text cannot be changed

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#4765]
### Description

If you update Span Text, it's not reflected in rendered UI.

### Steps to Reproduce

xaml:
```xaml
    <VerticalStackLayout>
        <HorizontalStackLayout>
            <Label Text="Label with Span: "/>
            <Label>
                <Label.FormattedText>
                    <FormattedString>
                        <Span Text="initial" x:Name="span"/>
                    </FormattedString>
                </Label.FormattedText>
            </Label>
        </HorizontalStackLayout>

        <HorizontalStackLayout>
            <Label Text="Simple label: "/>
            <Label Text="initial" x:Name="label"/>
        </HorizontalStackLayout>

        <Button Text="Set new text" x:Name="button"/>
    </VerticalStackLayout>
```

codebehind:
```csharp
            int i = 0;
            button.Clicked += (_, _) =>
            {
                i++;
                label.Text = i.ToString();
                span.Text = i.ToString();
            };
```

Expected: text is updated for both labels on button click.
Actual: text is updated only for label without Span.

![qemu-system-x86_64_e6vRJcM4UW](https://user-images.githubusercontent.com/17177729/154569400-0be63582-5408-40c7-a29a-f912d0021dd3.gif)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by Dbquity** [comment]
I found the same and came up with this extension-based workaround:
```csharp
label.FormattedText.Spans... // some logic that manipulate the spans of the formatted text of a label
label.UpdateSpansToWorkAroundMauiIssue();

public static class MauiIssuesWorkAroundExtensions {
    public static void UpdateSpansToWorkAroundMauiIssue(this Label label) {
        if (label.FormattedText is FormattedString ft) {
            label.Text = ".";
            label.FormattedText = ft;
        }
    }
}
```

**Comment by NogginBox** [comment]
I'm having the same issue with a span with databinding.

**Comment by Dbquity** [comment]
> I'm having the same issue with a span with databinding.

@NogginBox perhaps it is possible to work around the problem by (temporarily) binding thru a custom value converter that holds a reference to the Label and does the .Text and .FormattedText assignment "trick"...

**Comment by NogginBox** [comment]
@Dbquity I couldn't think of a way to do this with a value converter, as they return a value rather than setting it, so this happens before the span's text has been changed. I tried adding the logic in a PropertyChanged event handler on the span, but it got me stuck in an infinite loop.

**Comment by Dbquity** [comment]
@NogginBox how about the value converter also has a reference to a list of Labels and it adds the label to that list? Then in "some central place" every Label in that list plays the "trick" and the list is cleared. Maybe the list could be an ObservableCollection member on the page...
(I do realize it may turn into a bit of a sizable workaround, and I haven't tried it out myself)

**Comment by NogginBox** [comment]
@Dbquity I've switched to using a horizontal StackLayout of Labels for now. Works for me at the moment as my text is only on one line (most of the time). Hoping this bug will be fixed before I need it. I don't want to spend too much time on workaround code.

**Comment by YuqinSong** [comment]
Verified Repro. Repro project is available:
[#4765.zip](https://github.com/dotnet/maui/files/8139165/4765.zip)
