### ISSUE TITLE
Blazor Hybrid WebView not able to Obtain GPS Location

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#4768]
### Description

I have created RCL Project which uses GoogleMap. This is purely done in Javascript/HTM/css using google maps Javascript SDK.
I am trying to use this RCL in Blazor Hybrid Project.
It does load the Map, but Location is denied.

![image](https://user-images.githubusercontent.com/3267605/154603178-d52b707f-b5eb-490f-b542-a9f02930e149.png)

Not sure if this was needed but i also entered the permission for android platform in AndroidManifest.xml, that did not help either.

```
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

	<uses-feature android:name="android.hardware.location" android:required="false" />
	<uses-feature android:name="android.hardware.location.gps" android:required="false" />
	<uses-feature android:name="android.hardware.location.network" android:required="false" />
```

Is there anything else that i need to do?

My location obtaining scripts are in JavaScript file (googleMaps.js) which is my custom JavaScript code that obtains location
and plots the marker for current location. 
Additionally, it will also plot multiple marker for nearby business location.

In addition, I Manually gave location permission in the Android emulator, even that did not help

### Steps to Reproduce

The steps to create are long.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android

### Did you find any workaround?

No

### Relevant log output

```shell
In the picture
```

**Comment by Eilon** [comment]
Note to whoever investigates: There might be some WebView-specific settings to enable code inside the WebView (JavaScript world) to use certain browser APIs. Or maybe there are specific Android _app_ permissions to enable it (not just the regular "does this APP use location", but perhaps a more specific "does this app's WEBVIEW use location".

I know we've seen similar things before to do with mic/camera or something like that.

**Comment by nssidhu** [comment]
I do see that it does require some additional code, but no sure how to write for the current platform.
https://docs.microsoft.com/en-us/answers/questions/291239/geolocation-in-webview-droid.html
https://www.youtube.com/watch?v=L0BjhcP1uDA
https://turbomanage.wordpress.com/2012/04/23/how-to-enable-geolocation-in-a-webview-android/

**Comment by jfversluis** [comment]
To add to @Eilon's comment, this was the issue he's talking about: #3694

**Comment by nssidhu** [comment]
@jfversluis I tried options mentioned in #3694, but it did not help me in this latest release of MAUI that i am using.

**Comment by nssidhu** [comment]
So i updated the repo to check if native GP would work and it does.  so now in the repo i have native code that is working, but at the same time JavaScript which is not working.

I would have ended up using native code and forget about obtaining location from JavaScript for Location, but native code does not have live tracking, i would have to get it via timer. I also noticed that getting location via native code is extremely slow as well.

As suggested by @Eilon there might be permission that need to be enabled for WebView/BlazorWebView since that is browser-based permission.

Now when I use the same code in Blazor wasm project, i don't need to specify the permission upfront, when JavaScript Code (that will get gps coordinate) is about to execute it prompts user for permission. So, wondering if it is allowed to provide those permission upfront in the code, like we do in native code.

**Comment by nssidhu** [comment]
Hoping this might be helpful to someone who is looking into fixing it within BlazorWebView
https://www.youtube.com/watch?v=L0BjhcP1uDA

**Comment by jfversluis** [comment]
With [the link](https://docs.microsoft.com/answers/questions/291239/geolocation-in-webview-droid.html) you added earlier, I added this code to my `MauiProgram.cs`

```csharp
BlazorWebViewHandler.BlazorWebViewMapper.AppendToMapping("EnableGeoLocation", (handler, webview) =>
{
	handler.NativeView.Settings.SetGeolocationEnabled(true);
	handler.NativeView.Settings.JavaScriptEnabled = true;
	handler.NativeView.Settings.AllowFileAccess = true;
	handler.NativeView.Settings.SetGeolocationEnabled(true);
	handler.NativeView.Settings.SetGeolocationDatabasePath(handler.NativeView.Context.FilesDir.Path);
});
```

Not 100% sure if these are all needed, but at least this makes it work :)

![image](https://user-images.githubusercontent.com/939291/154927146-87186b75-2e8f-4124-9602-76c48dfa08e4.png)

**Comment by SteveSandersonMS** [comment]
@jfversluis Is it your opinion that this is a bug in BlazorWebView, or is a bug in the underlying MAUI WebView, or is not a bug at all and is something we should have covered in docs somewhere?

**Comment by nssidhu** [comment]
@jfversluis, regarding key, yes I will invalidate in few days (that one was created a specially for this testing), Thanks for your pointing that out though.
I just tried out that code now and I am still getting error "user denied the request for geolocation". 
I see you are using exact same emulator as well.

**Comment by jfversluis** [comment]
@SteveSandersonMS I would say either something we need to cover in docs (probably more general: this is how to handle the web permissions in .NET MAUI Blazor world) or something we need to make easier for our users.

From a user standpoint I would be in favor of basically just enabling and allowing all permissions on the web level since it will be handled on the platform level. On the other hand, we are dealing with sensitive sensors and APIs here, I can also see that people wouldn't appreciate us just opening up everything.

**Comment by jfversluis** [comment]
@nssidhu did you try to reinstall the application? Maybe you wrongfully accidentally denied the platform permission at some point? Could you double-check that? As you can see it works for me :)

**Comment by nssidhu** [comment]
> @SteveSandersonMS I would say either something we need to cover in docs (probably more general: this is how to handle the web permissions in .NET MAUI Blazor world) or something we need to make easier for our users.
> 
> From a user standpoint I would be in favor of basically just enabling and allowing all permissions on the web level since it will be handled on the platform level. On the other hand, we are dealing with sensitive sensors and APIs here, I can also see that people wouldn't appreciate us just opening up everything.

My thoughts on this, 
1. I think seasoned programmers will appreciate if they can precisely control what permission to enable. Providing document on 
    how to do it should be sufficient.
2. Enabling all permissions by default will also prompt users to accept all permissions. The better alternative, I think would be to translate platform level specified permission from maifest.xml to equivalent WebView level permission. This will allow things to remain consistent on how to enable permission between WebView and Platform level.

**Comment by nssidhu** [comment]
> @nssidhu did you try to reinstall the application? Maybe you wrongfully accidentally denied the platform permission at some point? Could you double-check that? As you can see it works for me :)

I tried uninstalling and re-installing and also checked in the emulator's setting/location that app does have location permission enabled. But still got the error.
I have made some changes to the code after creating the Git repo, so will try again by taking the code from Git repo and will check if i still run into issue.

**Comment by nssidhu** [comment]
So i have tried it again, still getting permission denied error.
I have pushed my commits to Git as well.

One thing i noticed is that during first run, i already got the "permission denied error", even before i got the chance to enable permission in the prompt as you can see in the screen shot below.

![BlazorWebViewGPSIssue1](https://user-images.githubusercontent.com/3267605/155159408-47bde6a2-734d-4e43-a8e3-35f59afa4644.jpg)

After providing permission and re-running it , as you can see the app now does have the permission.
My question here is are those permission applicable to BlazorWebView/WebView or just to native code (Which is working anyway) ?

![BlazorWebViewGPSIssue2](https://user-images.githubusercontent.com/3267605/155159930-2b765a8e-7853-41ba-b668-94180bb89ed1.jpg)

@jfversluis i am clueless here as to why it worked for you. I even tried moving builder.Services.AddBlazorWebView(); before and after the handler to see if that would make any difference, but it did not

**Comment by jfversluis** [comment]
I think I see the same happening... Here's how I make it work: first deploy, I see the dialog for permission and accept. The error shows.

Now, make sure that you do have a location set in the emulator settings and run the app again either through debugging or not. It will now load and show the location although it still says "User denied the request for Geolocation". I didn't inspect the code too much, but I expect there to be something in your code that doesn't handle this properly as it does work on the second try.

**Comment by nssidhu** [comment]
@jfversluis My bad, I should have removed the native code before publishing. 
There is a code that get the Location using native code which is working, that is why you see the location plotted on the Map.
 // await GetLocation();
 that call is made out at line #67 in GoogleMpa.razor.cs
 i did that to check if i am able to get the Location using Native Code and if can use that as alternative in case things don't work.
 
 I removed it and checked back my code.

**Comment by nssidhu** [comment]
Any updates on how to get this working ?

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck can you please include a note in our docs on how to enable location access for WebView? Thanks!

**Comment by MackinnonBuck** [comment]
Please refer to [this project](https://github.com/MackinnonBuck/MauiBlazorPermissionsExample) as an example for implementing permission management in MAUI Blazor apps for Windows, Android, and iOS. It shows how to access the device's location, camera, and microphone from JavaScript web APIs.

We've decided to refer developers to this sample rather than add a docs page since implementing this is rather involved. In the future, we hope to provide a framework-integrated solution that doesn't require individual apps to worry about configuring WebView options and handling permission requests.
