### ISSUE TITLE
Font Icons in Shell Tabs not showing

### ISSUE THREAD

**Issue by RichardMarsh** [dotnet/maui#4774]
### Description

When using Font Icons in the ShellContent/Tab of a TabBar in the Shell, it doesn't display in iOS but works fine in Android.

I beleive it's setup correctly and I've tested various iterations of the XAML but nothing has worked so far. 

![image](https://user-images.githubusercontent.com/54434905/154679984-6f6d56a9-2191-4f80-83ce-048d8799631c.png)

![image](https://user-images.githubusercontent.com/54434905/154679956-49ea6b52-430a-4edb-8be5-bbe3a6996828.png)

Android: 
![image](https://user-images.githubusercontent.com/54434905/154680022-385f94e4-7d86-4035-a91d-18814b9b6b4c.png)

iOS
![image](https://user-images.githubusercontent.com/54434905/154680239-f81aaf7f-09b9-4346-9603-60d60bb39e10.png)

Reproduction repo: https://github.com/RichardMarsh/MAUICompare

### Steps to Reproduce

1. Create MAUI app
2. Add relevant icon ttf file to app
3. Create shell, add icons to tabs via tabbar
4. Run on iOS local device
5. Post on GitHub

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by dev-thinks** [comment]
am also confirming the same issue in winui and ios. works fine in android.

**Comment by Mephisztoe** [comment]
I can also confirm this issue. Android works, WinUI and iOS does not.

**Comment by jindal1979** [comment]
I am also facing the same issue, the icons are not showing with WINUI Desktop application.

**Comment by PureWeen** [comment]
As a workaround for WinUI if you set the Color on the `FontImageSource` that should make it display

**Comment by PureWeen** [comment]
This might be fixed on P14 for iOS but appears to definitely be fixed on RC1
