### ISSUE TITLE
App.OnTerminate

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#4786]
### Description

All the time we need to understand what happened before the app was terminated.

OnTerminate allows the developer to log any event or send messages to the admin or set a Preference in order to show a message once the user restart the app after termination.

### Public API Changes

protected override void OnTerminate()
{

}

### Intended Use-Case

To log events upon termination

**Comment by jfversluis** [comment]
Actually we have this in place already. Check out the Docs page here: https://docs.microsoft.com/dotnet/maui/fundamentals/app-lifecycle#cross-platform-lifecycle-events

You can hook into the events for each platform to achieve what you want and many more events.

**Comment by jrahma** [comment]
That is what I was talking about 

Excellent. Thanks @jfversluis
