### ISSUE TITLE
FormattedText: Span BackgroundColor does not work

### ISSUE THREAD

**Issue by IndianaGary** [dotnet/maui#4788]
### Description

My application supports color syntax highlighting and I expected to be able to use Span to implement it. Unfortunately, setting BackgroundColor does nothing that I could see. Setting TextColor works as expected. I tried setting it directly on a Span, and setting it using a Setter in a Style. Neither one worked. I also expect a Span's BackgroundColor to *override* any background color set on the containing Label.

### Steps to Reproduce

1. Create a new Maui Project. I named it DebugHelper
2. Replace MainPage's content with the attached XAML file (zipped); modify the project name it to match yours.
3. Observe that Span BackgroundColor is inoperative.

Note the following: The encompassing Label is Magenta text on a Green background because of the default Style. The Span's default Style should override this to be Navy text on an Orange background, except for the first Span, which explicitly sets it to be Yellow text on a Red background:

1. Navy text works but Orange background does not.
2. Yellow text works but Red background does not.

The attached zip file contains MainPage.xaml and MainPage.xaml.cs.

[SpanProblem.zip](https://github.com/dotnet/maui/files/8100902/SpanProblem.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.18362 and later

### Did you find any workaround?

No workaround was apparent.

### Relevant log output

None

**Comment by PineYi** [comment]
Verified Repro with Windows. Repro Project is available:
[#4788.zip](https://github.com/dotnet/maui/files/8130993/4788.zip)
