### ISSUE TITLE
Location Allow Once vs Always

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#4790]
### Description

Please add an option to determine which permission the user has selected for the app, Allow Once or Always

### Public API Changes

```
if (status == PermissionStatus.Granted)
{
     await DisplayAlert("Permission", "The app has (Always) Location permission", "Ok");
}
else if (status == PermissionStatus.Once)
{
     await DisplayAlert("Permission", "The app has (Once) Location permission", "Ok");
}
else
{
     await DisplayAlert("Permission", "The app does not have Location permission", "Ok");
}

```

### Intended Use-Case

In an app that requires Always permission because of background services you want to know if the user has selected Once to show him a message that some features might not work until you choose (Always) permission.

**Comment by jfversluis** [comment]
This is available through .NET MAUI Essentials, linking Xamarin.Essentials here, but the API is the exact same for .NET MAUI: https://docs.microsoft.com/xamarin/essentials/permissions?tabs=android#checking-permissions
