### ISSUE TITLE
The project doesn't know how to run the profile Windows Machine.

### ISSUE THREAD

**Issue by sealkeen** [dotnet/maui#4797]
### Description

I've just downloaded and installed all of the latest updates for Visual Studio Community  (up to 20 february, 2022).
also used these 4 powershell commands: 
`dotnet workload install maui-ios; dotnet workload install maui-windows; dotnet workload install maui-maccatalyst; dotnet workload install maui-android`

I have installed all of the latest:

1. Universal Windows Platform development, 
2. Modile development with .NET, 
3. ASP.Net and web development, 
4. Node.js development, 
5. .NET desktop development, 

		
The compilation for all of the project frameworks completed successfully. 
_**When running the application on an Android device, it runs fine.**_

Visual Studio still compiled all of the required files, but the "Windows Machine" application didn't start,
Trying to load the ".exe" file from debug directory on Windows didn't succeed.

The Windows Version is **21H2 (build 19044.1526)**
Visual Studio version is **Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.1.0**

MAUI version is **6.0.200-preview.13.2865**

### Steps to Reproduce

The new maui application that was created has these lines in the project target frameworks:
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>
		...
		<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>
	...
</Project>
```

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows 10 (19044) affected by the issue. Android platform doesn't.

### Affected platform versions

net6.0-windows10.0.19041 (both release and debug builds).

### Did you find any workaround?

No workaround was found. **_Although a new plain UWP project for the same platform runs fine (only MAUI application doesn't load)._**

### Relevant log output

```shell
Build started...
1>------ Build started: Project: MauiApp2, Configuration: Debug Any CPU ------
1>MauiApp2 -> O:\VCSharp\Testing\MauiApp2\MauiApp2\bin\Debug\net6.0-windows10.0.19041\win10-x64\MauiApp2.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by Ghevi** [comment]
Do you have this extension installed? I'm not quite sure it solve the issue, but messing with it caused me to have your same error.
https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17

**Comment by ajdiv** [comment]
> Do you have this extension installed? I'm not quite sure it solve the issue, but messing with it caused me to have your same error. https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17

After installing this, and trying to rerun the program, the Settings app opened. I turned Developer Mode on from the Settings app, and also turned "Device discovery" on. After that I was able to run. 

Thank you

**Comment by sealkeen** [comment]
Installing the above extension fixed the issue.
