### ISSUE TITLE
Not rendering FlyoutContentTemplate

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#4801]
### Description

Windows isn't rendering the template. I still get only the FlyoutItems defined.

![image](https://user-images.githubusercontent.com/41873/154870950-c1af2aa6-52bd-4583-9f19-2413a5742fdc.png)

Android does render content:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/41873/154870937-90ee6eca-ec6e-4ec7-978e-ca5b3291ff07.png">

The XAML:

```xaml
<Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:FoodPOS"
             x:Class="FoodPOS.App">
    <Application.Resources>
        <ResourceDictionary Source="Resources\Styles\Styles.xaml"/>
    </Application.Resources>

    <Application.MainPage>
        <Shell FlyoutWidth="104" FlyoutBehavior="Locked">
            <Shell.FlyoutContentTemplate>
                <DataTemplate>
                    <FlexLayout Direction="Column" WidthRequest="104" Background="{StaticResource DarkBg2Brush}">
                        <Image Source="logo.svg"/>
                        <Image Source="home.svg"/>
                        <Image Source="discount.svg"/>
                        <Image Source="graph.svg"/>
                        <Image Source="message.svg"/>
                        <Image Source="notification.svg"/>
                        <Image Source="setting.svg"/>
                        <Image Source="logout.svg"/>
                    </FlexLayout>
                </DataTemplate>
            </Shell.FlyoutContentTemplate>

            <FlyoutItem>
                <ShellContent ContentTemplate="{DataTemplate local:MainPage}"/>
            </FlyoutItem>
        </Shell>
    </Application.MainPage>
</Application>

```

### Steps to Reproduce

Run the code on Windows

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

current windows

**Comment by shimingsg** [comment]
verified reproducible on windows with VS 17.2.0 Preview 2.0 [32223.271.main]
![image](https://user-images.githubusercontent.com/20982341/155683509-43d58486-0dec-4244-95a4-4b62a0c72fa1.png)
repro demo: 
[4801.zip](https://github.com/dotnet/maui/files/8139740/4801.zip)

**Comment by PureWeen** [comment]
Fixed in RC1
