### ISSUE TITLE
Label MaxLines doesn't work

### ISSUE THREAD

**Issue by ram16g** [dotnet/maui#4805]
### Description

When set LineBreakMode，MaxLines doesn't work, it always show one line.

<Label 
                Text="Welcome to .NET Multi-platform App UI!Welcome to .NET Multi-platform App UI!Welcome to .NET Multi-platform App UI!Welcome to .NET Multi-platform App UI!"
                Grid.Row="1"
                LineBreakMode="TailTruncation"
                MaxLines="3"
                SemanticProperties.HeadingLevel="Level1"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11  iOS 15

### Did you find any workaround?

no

### Relevant log output

```shell
no
```

**Comment by ram16g** [comment]
<Label 
                Text="Welcome to .NET Multi-platform App UI!Welcome to .NET Multi-platform App UI!Welcome to .NET Multi-platform App UI!Welcome to .NET Multi-platform App UI!"
                Grid.Row="1"
                MaxLines="2"
                LineBreakMode="TailTruncation"
                SemanticProperties.HeadingLevel="Level1"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />

**Comment by ram16g** [comment]
`
<Label 
                Text="Welcome to .NET Multi-platform App UI!Welcome to .NET Multi-platform App UI!Welcome to .NET Multi-platform App UI!Welcome to .NET Multi-platform App UI!"
                Grid.Row="1"
                MaxLines="2"
                LineBreakMode="TailTruncation"
                SemanticProperties.HeadingLevel="Level1"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />
`

**Comment by PineYi** [comment]
Verified Repro with Android 11. Repro Project is available:
[#4805.zip](https://github.com/dotnet/maui/files/8130329/4805.zip)

**Comment by J-Swift** [comment]
It seems this is _both_ `LineBreakMode` and `MaxLines`. Setting either (or both) doesn't do anything for me on Android (p13).
