### ISSUE TITLE
which version will support .NET MAUI for Visual Studio for Mac

### ISSUE THREAD

**Issue by xing123456789** [dotnet/maui#4806]
### Description

I want to develop project with maui for Visual Studio for Mac. But current version is not supported, May I ask which version will it support And What time will it be released?
Thanks

### Public API Changes

none

### Intended Use-Case

none

**Comment by jfversluis** [comment]
Keep your eye on the announcements, there is nothing made public about that yet. The latest blog post at the time of writing [can be found here](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-for-mac-preview-6/#xamarin-and-net-maui-development-in-the-months-ahead) and states:

> We will provide more updates on .NET MAUI support in Visual Studio for Mac as we get closer to [.NET MAUI’s GA](https://github.com/dotnet/maui/wiki/Roadmap) in late Q2 2022.
