### ISSUE TITLE
[Webview/Android] blank screen when website have invalid certificate

### ISSUE THREAD

**Issue by julienGrd** [dotnet/maui#4811]
### Description

hello guys, when i try to load a website with invalid certificate (self signed) into my webview, this last one stay blank (no exception, just nothing loaded).

Many people had to deal with this error in xamarin so i imagine the resolution would be mostly the same

i begin to take a look at this code https://gist.github.com/MansiShah04/2638427748d11f69aee85d22010e1f91 but for now im unable to compile it,

Is it the good direction for .net maui to deal with that ? 

### Steps to Reproduce

- create an .net maui project with a webview, put an website with invalid certificate in the source
- launch the app, you will havve blank screen

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11, api 30

### Did you find any workaround?

no workaround for now

**Comment by drasticactions** [comment]
If the error is how Android deals with invalid certificates inside of a webview, I'm not sure what MAUI should be doing differently here. If anything, it would be something [xamarin-android](https://github.com/xamarin/xamarin-android) would need to look at. 

What's the default behavior for a non-Xamarin Android app with a bad certificate in the webview? If that's the same as what a MAUI app does, then that's not something, IMO, we should handle differently, that's something you need to take up with the platform holder. If it _does_ do something different and show some kind of error, and xamarin-android and/or MAUI don't do that, then there's an issue.

**Comment by julienGrd** [comment]
@drasticactions i know its the defaut behavior of android but it should have a way to handle it (like xamarin did).

actually my principal problems with .NET MAUI is the lack of documentation, so i base my development with xamarin example but it slightly different

anyway i found a way to do it, this is the complete code :
````
//in Platforms/Android
[assembly: ExportRenderer(typeof(CustomWebView), typeof(CustomWebViewRenderer))]
namespace Geckos.Platforms.Android
{
    public class CustomWebViewRenderer : WebViewRenderer
    {
        public CustomWebViewRenderer(Context context) : base(context)
        {
          
        }
        protected override void OnElementChanged(ElementChangedEventArgs<Microsoft.Maui.Controls.WebView> e)
        {
            base.OnElementChanged(e);
            Control.SetWebViewClient(new CustomWebViewClient());
            global::Android.Webkit.WebView.SetWebContentsDebuggingEnabled(true);
        }
    }

    public class CustomWebViewClient : global::Android.Webkit.WebViewClient
    {
        public CustomWebViewClient()
        {
        }

        public override void OnReceivedSslError(global::Android.Webkit.WebView view, SslErrorHandler handler, SslError error)
        {
            handler.Proceed();//this line make ssl error handle so the webview show the page even with certificate errors
        }
    }
}

//At root
public class CustomWebView : WebView
    {
        public CustomWebView()
        {
        }
    }

//on the view
<controls:CustomWebView x:Name="webView" Grid.Row="0">

</controls:CustomWebView>
````
