### ISSUE TITLE
The "Value cannot be null" errors are shown on an attempt to build a project with MauiVersion set to a previous value

### ISSUE THREAD

**Issue by AndreyMarten** [dotnet/maui#4812]
### Description

When I explicitly specify a previous preview version in the csproj file using the `MauiVersion` tag, an attempt to build the project leads to the "Value cannot be null" errors. 

**Microsoft Visual Studio Community 2022 (64-bit) - Preview**
**Version 17.2.0 Preview 1.0**

### Steps to Reproduce

1. Create a new MAUI project using the Visual Studio's default template;
2. Open the csproj file;
3. Add the `<MauiVersion>6.0.200-preview.12.2441</MauiVersion>` tag;
4. Build the project

All attempts to resolve the issue (clean/rebuild, delete bin/obj, etc.) were unsuccessful. 

The project and sreencast below illustrate the problematic behavior: 

[dxSample.zip](https://github.com/dotnet/maui/files/8109672/dxSample.zip)
https://user-images.githubusercontent.com/31204429/154968622-f3c7c2a8-cd33-4eb4-8405-bd7cdbbf5e31.mp4

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 12

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

-

**Comment by PineYi** [comment]
Verified Repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32215.517.main] . Repro Project is available:
[#4812.zip](https://github.com/dotnet/maui/files/8139952/4812.zip)

**Comment by dais-set** [comment]
Is this fixed in the preview.14 ?

**Comment by Redth** [comment]
Please do not use MauiVersion property going forward, it is no longer supported.
