### ISSUE TITLE
[ios] Cant set TabbedPage BarBackgroundColor in iOS 15

### ISSUE THREAD

**Issue by J-Swift** [dotnet/maui#4814]
### Description

On iOS 15, the TabbedPage BarBackroundColor is always either white or black depending on the device theme (light or dark). I see there was a seemingly related issue addressed in https://github.com/dotnet/maui/issues/1654 but that appears to be only for Shell apps.

Repro project here: https://github.com/J-Swift/maui-tabbar-repro

Examples:

Android:
<img width="320" alt="android_sim" src="https://user-images.githubusercontent.com/734158/154986425-bbe2e2a7-94de-4df0-bc97-e74e956f353c.png">

iOS 14:
<img width="320" alt="ios_sim_14_5" src="https://user-images.githubusercontent.com/734158/154986430-afb11bb4-2ca3-4c33-b076-79e8fed0d975.png">

iOS 15:
<img width="320" alt="ios_sim_15_2" src="https://user-images.githubusercontent.com/734158/154986436-8e6652a9-7ca6-43c7-9a58-b4893647abea.png">

### Steps to Reproduce

1. Create a TabbedPage
2. Set BarBackgroundColor to something other than white or black
3. Observe that it isn't respected

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified Repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main] . Repro Project is available: [4814.zip](https://github.com/dotnet/maui/files/8152311/4814.zip)
