### ISSUE TITLE
Binding a App, SecureStorage and Preference value

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#4825]
### Description

Hi,

It will be great if you provide a way to set the value of App, SecureStorage, and Preference to a Label, Text, or other controls using Binding.

### Public API Changes

`<Label Text="{Binding SecureStorage.StudentID" />
`

`<Label Text="{Binding Preference.StudentID" />
`

and for App:

```
public partial class App : Application
{
       .........
       .........
       public static string StudentID { get; set; }
}

```

then:

`<Label Text="{Binding App.StudentID" />
`

### Intended Use-Case

Setting values to controls.

**Comment by jfversluis** [comment]
We have secure storage and preferences with .NET MAUI Essentials. You should be able to use that to achieve what you want with this. I don't see any direct need to make that easier tbh. Or I am not clear on what you're asking. In that case, please add more detail. Thanks
