### ISSUE TITLE
Use "Razor component" and avoid "Blazor component"

### ISSUE THREAD

**Issue by guardrex** [dotnet/maui#4830]
### Description

I'm going to move this over from a GH discussion because I'm having good luck 🍀 thus far getting MS pubs updated on the point, and I hope we'll be able to address the lingering instances of "Blazor component" in frameworks. Separately, I've opened this for the ASP.NET Core team (`dotnet/aspnetcore`) at https://github.com/dotnet/aspnetcore/issues/40344, and they've agreed to my sending a PR to update it there.

Mirroring the discussion remarks that I posted at https://github.com/dotnet/maui/discussions/4799 ...

The term "Blazor component" is valid *informal naming* for **_Razor components_**, which is the official, formal name. See my remarks here ...

https://github.com/dotnet/docs-maui/issues/295

I recommend that in the few spots in framework code where the term "Blazor component" appears that it be changed to either "Razor component" or just "component" to resolve the dual-naming problem and completely align the framework code/API docs with the Blazor docs.

### Public API Changes

"Blazor component" only appears in three files here, usually in comments that will resolve to API docs ...

* https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/WindowsForms/BlazorWebView.cs
  * Line 18
  * Line 72
  * Line 100
  * Line 127
* https://github.com/dotnet/maui/blob/main/src/BlazorWebView/tests/MauiDeviceTests/Elements/BlazorWebViewTests.cs
  * Line 15
* https://github.com/dotnet/maui/blob/main/src/BlazorWebView/samples/MauiRazorClassLibrarySample/Component1.razor
  * Line 2

If you'd entertain a PR from me to update these spots, I'll create a PR to knock it out 🥊. *Let me know* 📣👂. 

### Intended Use-Case

"Blazor component" has slipped out a little bit into the community, but I think we can head off further wide adoption by stomping it out **_NOW_** 🏃 ... quickly 🏃🏃. *Future generations will thank us!* 😄

**Comment by Eilon** [comment]
@guardrex I think a PR would be great if you have time!

**Comment by mkArtakMSFT** [comment]
Thanks @guardrex . Should this be closed now ?

**Comment by guardrex** [comment]
btw ... Your guidance for PR submissions says not to use "fixes" but to use "implements" instead. Not sure if that guidance was by-design or not. Just letting you know why this stayed open.

**Comment by Eilon** [comment]
@guardrex oh that's a bit weird. I'll contact some other MAUI folks to see if that was deliberate.
