### ISSUE TITLE
Add an overloaded constructor for the requested types to simplify things

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#4831]
### Description

While working with C# / Fluent style, it requires a lot of keystrokes to create a Setter and set its Property and Value in the initializer.

Whereas if there is an overloaded constructor that takes the `BindableProperty` and `Value` as its parameters, this would save too many keystrokes especially when there're too many Styles / Triggers / Visual States to define.

And similarly, for types `Label`, `Button`, and `Span`, add an overloaded constructor that takes a `string` parameter and assigns it to the `Text` property.

Though it is possible to extend those types and add an overloaded constructor, this will have an impact while sharing the style definitions.

Whereas having one will improve productivity, especially for those who have less or no XAML knowledge and come from different backgrounds.

### Public API Changes

```cs
public sealed class Setter : IValueProvider
{
    public Setter() { // Default ctor }
    public Setter(BindableProperty property, object value) { // Overloaded ctor }
}
```
```cs
public partial class Button : View //, other interfaces
{
    public Button() { // Default ctor }
    public Button(string text) { // Overloaded ctor }
}
```

Similarly for `Label` and `Span`, kindly consider adding such an overloaded constructor wherever it is meaningful.

### Intended Use-Case

Present scenario:
```new Setter() { Property = Button.TextColorProperty, Value = Colors.White }```

With the Proposed API:
```new Setter(Button.TextColorProperty, Colors.White)```

With C# 9 syntax, this would even get simplified when used inside the Setters collection:

```CSharp
Setters =
{
    new(Button.TextColorProperty, Colors.White)
}
```

**Comment by jfversluis** [comment]
One year later I don't see a lot of traction on this idea. Personally my problem with this change would be: what are the most used properties? How are we going to determine those? The properties you use most might not be the properties that others are using most.

We have a couple of different plugins that help you write UIs in .NET MAUI more fluently. I don't think we'll be adding anything to the direct codebase in the near future.

Thanks for your suggestion!
