### ISSUE TITLE
[Xaml]Assign to nullable properties

### ISSUE THREAD

**Issue by StephaneDelcroix** [dotnet/maui#4832]
### Description

```xml
<Application AccentColor="HotPink" />
```

fails (at least at compilation) cause AccentColor is `Color?`. I guess the TypeConverter isn't even invoked...

### Steps to Reproduce

/

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

All

### Affected platform versions

/

**Comment by shimingsg** [comment]
Verified repro with Version 17.2.0 Preview 2.0 [32222.430.main]
![image](https://user-images.githubusercontent.com/20982341/155294136-bd3a6bf2-3251-479d-ab19-fb82badd6020.png)

**Comment by StephaneDelcroix** [comment]
my wrong, not a bug, moving on
