### ISSUE TITLE
[Enhancement] Add Mocks Project

### ISSUE THREAD

**Issue by dansiegel** [dotnet/maui#484]
## Summary

For Xamarin.Forms it has always been necessary to initialize the platform, and unit tests are no exception to this. For some not knowing how to initialize Xamarin.Forms from a Unit Test project has kept them from being able to write tests for their apps. For others this has meant a burden of writing mocks to initialize Xamarin.Forms... and for many others it has been a dependency on the Xamarin.Forms.Mocks nuget package. 

As such a requirement is likely to continue in some fashion in Maui, it would be good to make this experience a first class citizen and provide a Mocks package that can provide the necessary test environment initialization that developers require in an official package that ships along side of the primary Maui package.

**NOTE**: I'm sure this will look a bit different from Xamarin.Forms.Mocks due to the Host Builder work going on as well.

## API Changes

No actual API changes... 

## Intended Use Case

This would be useful for everyone from Control Vendors, OSS Libraries, and developers writing apps to be able to properly initialize a test environment for their code and write unit tests.

**Comment by Redth** [comment]
Given this issue was created well before more recent previews, I'm going to close it as I think it's instead worth opening new issues for specific changes to better help enable testing with MAUI.
