### ISSUE TITLE
[iOS] [MacCatalyst]: Layout is not invalidated when Visibility is changed for controls using ViewRenderer as Handler

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#4849]
### Description

I have a custom control that inherits from View. The Handler of the control is a [ViewRenderer](https://github.com/dotnet/maui/blob/main/src/Compatibility/Core/src/Handlers/iOS/ViewRenderer.cs). When I toggle the Visibility of the control from False to True the Layout is not invalidated - thus the control is not visualized accurately. When I rotate/change the screen of the device   the layout is invalidated and the control is visualized.
![bug_maui_visibility](https://user-images.githubusercontent.com/9336157/155291331-50e614a6-3bb5-4217-86c7-3b0684f886f4.gif)

### Steps to Reproduce

1. Run the attached project.
2. Toggle the visibility.
3. Notice that the control that was previously not visible is not visualized.
[HelloMaui.zip](https://github.com/dotnet/maui/files/8123133/HelloMaui.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15, MacOS Monteray

**Comment by xing123456789** [comment]
how to create demo when you use Visual Studio 2022 for Mac version 17.0 Preview 6
I have some problems when I use Visual Studio 2022 for Mac version 17.0 Preview 6 .
1、"Debug" Layout miss some file when I open sIn file
![154419876-7a730e19-5b0a-4f2a-827c-12a4ebee31d3](https://user-images.githubusercontent.com/95727133/155312540-72e71c03-45a0-4a68-946d-7e7d41a775e2.jpeg)
Thanks

**Comment by jsuarezruiz** [comment]
cc @hartez

**Comment by xing123456789** [comment]
https://user-images.githubusercontent.com/95727133/155443417-a42b6abe-aa10-4aa2-ba94-33afd70ab8a9.mp4

May I ask how you created the project?  The project I created can't run
Thanks

**Comment by v-longmin** [comment]
verified repro. repro project:

**Comment by davidortinau** [comment]
Verified on main (rc3) with Catalyst
