### ISSUE TITLE
Wear OS/WatchOS support

### ISSUE THREAD

**Issue by Laftek** [dotnet/maui#4852]
### Description

Do you plan to support Wear OS and WatchOS with MAUI?

### Public API Changes

N/A

### Intended Use-Case

To be able to create apps with MAUI for smartwatch.

**Comment by jfversluis** [comment]
Duplicate of https://github.com/dotnet/maui/discussions/1144

We have no immediately plans to support that any more than we do today. Upvote the discussion to show your interest in this!
