### ISSUE TITLE
The XyzMapper fields on each Handler type should be 'readonly'

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#4870]
### Description

The various Mapper fields on the various control handlers should be made 'readonly' so they don't get overwritten.

Examples:
https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/Button/ButtonHandler.cs#L19-L41
https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/Editor/EditorHandler.cs#L16-L37

We noticed this in the BlazorWebView handler (probably because I copied the code from some other handler to begin with) and it seems to make sense to mark them `readonly`.

Tagging @PureWeen .

### Steps to Reproduce

N/A

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

N/A

**Comment by antonfirsov** [comment]
@Elion @PureWeen shouldn't they be get-only properties instead? It feels like more appropriate C# practice.

```C#
public static IPropertyMapper<IImage, IButtonHandler> ImageButtonMapper { get; } = new PropertyMapper<IImage, IButtonHandler>()
{
	[nameof(IImage.Source)] = MapImageSource
};
```

**Comment by PureWeen** [comment]
Currently we're using the settable nature of these to create custom mappers inside `Controls`

https://github.com/dotnet/maui/blob/5941e0d31fc4bf73ce1ef07b35aa3b3f6a96a025/src/Controls/src/Core/HandlerImpl/Entry/Entry.cs#L15

If we make them readonly then we'll need to modify how we're doing this.

**Comment by Eilon** [comment]
Closing because this is by design. We are fixing the Blazor stuff where we pre-emptively changed it.
