### ISSUE TITLE
I Need SerialPort on Android Device.

### ISSUE THREAD

**Issue by mzy666888** [dotnet/maui#4874]
### Description

I need to use the serial port of Android device to communicate with other modules. Can MAUI provide native serial port access？
I hope it.

### Public API Changes

The "System.IO.Port" can't run other platforms without windows.

### Intended Use-Case

I have a medical device that uses serial port  on Android Platform to control the operation of the device

**Comment by Redth** [comment]
This is not on our roadmap.  You can find approaches to this with platform specific API's like here: https://github.com/Jignesh-Darji/xamarin-usb-serial-for-android-2019
