### ISSUE TITLE
fail to create .NET MAUI app

### ISSUE THREAD

**Issue by xing123456789** [dotnet/maui#4876]
### Description

when I create a new app run. when I carry out "dotnet build -t:Run -f net6.0-ios -p:_DeviceName=:v2:udid=02C556DA-64B8-440B-8F06-F8C56BB7CC22"  It happen some errors

用于 .NET 的 Microsoft (R) 生成引擎版本 17.1.0+ae57d105c
版权所有(C) Microsoft Corporation。保留所有权利。

  正在确定要还原的项目…
  所有项目均是最新的，无法还原。
  Detected signing identity:
          
    Bundle Id: com.companyname.mymauiapp
    App Id: com.companyname.mymauiapp
  MyMauiApp -> /Users/mac/Desktop/haha/MyMauiApp/bin/Debug/net6.0-ios/iossimulator-x64/MyMauiApp.dll
  正在优化程序集的大小，这可能更改应用的行为。请务必在发布后进行测试。请参阅: https://aka.ms/dotnet-illink
EXEC : error MT0057: Cannot determine the path to Xcode.app from the sdk root '/Library/Developer/CommandLineTools'. Please specify the full path to the Xcode.app bundle. [/Users/mac/Desktop/haha/MyMauiApp/MyMauiApp.csproj]
          
/usr/local/share/dotnet/sdk/6.0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(897,5): error MSB3073: 命令“/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.2.301-preview.13.7/tools/bin/mlaunch --launchsim bin/Debug/net6.0-ios/iossimulator-x64/MyMauiApp.app/ --device :v2:udid=86E2D614-DC95-4F0C-8DD3-ACB1088BDCE0 --stdout /dev/ttys001 --stderr /dev/ttys001 --wait-for-exit”已退出，代码为 1。 [/Users/mac/Desktop/haha/MyMauiApp/MyMauiApp.csproj]

生成失败。

EXEC : error MT0057: Cannot determine the path to Xcode.app from the sdk root '/Library/Developer/CommandLineTools'. Please specify the full path to the Xcode.app bundle. [/Users/mac/Desktop/haha/MyMauiApp/MyMauiApp.csproj]
/usr/local/share/dotnet/sdk/6.0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(897,5): error MSB3073: 命令“/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.2.301-preview.13.7/tools/bin/mlaunch --launchsim bin/Debug/net6.0-ios/iossimulator-x64/MyMauiApp.app/ --device :v2:udid=86E2D614-DC95-4F0C-8DD3-ACB1088BDCE0 --stdout /dev/ttys001 --stderr /dev/ttys001 --wait-for-exit”已退出，代码为 1。 [/Users/mac/Desktop/haha/MyMauiApp/MyMauiApp.csproj]
    0 个警告
    2 个错误

how I solve it
Thanks

### Steps to Reproduce

1.  dotnet new maui -n "MyMauiApp"
2. dotnet build -t:Run -f net6.0-maccatalyst
3. dotnet build -t:Run -f net6.0-ios -p:_DeviceName=:v2:udid=02C556DA-64B8-440B-8F06-F8C56BB7CC22.  This uuid is my xcode simulator uuid

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

iOS, macOS

### Affected platform versions

iOS15

**Comment by jfversluis** [comment]
Did you install Xcode? And also did you start it? It will probably ask you to install the command-line tools and this should be resolved

**Comment by xing123456789** [comment]
yes, I installed Xcode,  When I run dotnet build -t:Run -f net6.0-ios -p:_DeviceName=:v2:udid=1D20034D-F4A2-424E-9B1D-47065953C2C9 in terminal。It also report the same error.  But It Runs no problem on Mac
![image](https://user-images.githubusercontent.com/95727133/155503716-cec91c33-fb5f-48c5-8a71-12d0ec093d56.png)

I'm guessing it might be a problem with the path
How do I need to modify the path?
Thanks

**Comment by jfversluis** [comment]
What does it say when you execute `xcode-select -p`?
