### ISSUE TITLE
[Windows] Button changes TextColor on hover and never restores it back

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#4887]
### Description

When the `TextColor` property of the `Button` is set to some non-default value, that value is respected initially, When the user hovers with the mouse, the color is changed to black and stays that when the mouse leaves the `Button`.

### Steps to Reproduce

1. Run the attached sample application
    - The first button is with its default text color
    - The second button is with a custom text color
2. Hover with the mouse over the buttons
    - Both buttons are colored in black text color

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

I have not tested on various versions of the different platforms.

### Sample Project
[TestApp.zip](https://github.com/dotnet/maui/files/8133949/TestApp.zip)

**Comment by v-longmin** [comment]
The repro project as attachment: [TestApp.zip](https://github.com/dotnet/maui/files/8133949/TestApp.zip)
