### ISSUE TITLE
Visual Studio 2022 preview dot net maui preview 13

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4894]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-preview-dot-net-maui-/1670590)._

---
[severity:I'm unable to use this version] [regression] [worked-in:preview 12]
I have a dotnet maui project and with this preview It does not build due to CSS isolation when using mac ios iphone 5:
--------------------------------------------------------------------------------------------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error		The path '.. \.. \.. \.. \.. \.. \.. \Dev\Tests\Tests\MauiApp1.Blazor\Shared\MainLayout.razor.css' would result in a file outside of the app bundle and cannot be used.
        	MauiApp1.Blazor	C:\Dev\Tests\Tests\MauiApp1.Blazor\Shared\MainLayout.razor.css	1	
----------------------------------------------------------------------------------------------------

When I disable the Css isolation it works (but with out css of course)

Please fix it ASAP as I am unable to carry on with testing

Regards

Laz

---
#### Feedback Bot on 2/20/2022, 09:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
And the linked issue is marked as fixed recently, so hopefully this should work in the next preview
