### ISSUE TITLE
New MAUI project with la fair number of packages build for windows, but exits with "java.exe exited with code 1"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4895]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/New-MAUI-project-with-la-fair-number-of-/1673349)._

---
[severity:I'm unable to use this version]
I ported over a XF project to a new new MAUI project and added a bunch of packages and sub projects.  project built and ran fine until i added a project reference into the main MAUI project.  Now, the android project will not build and return `java.exe exited with code 1`.  I tried building with diagnostic info on, but there's about 900K lines.  I've attached the project that generates the error.  
[MyCompany.MyApp.zip] (https://aka.ms/dc/file?name=B28f5344a562f4da38eee6679e649ee7a637811742299878775_MyCompany.MyApp.zip&tid=28f5344a562f4da38eee6679e649ee7a637811742299878775)

---
#### Feedback Bot on 2/22/2022, 11:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pierrebrito** [comment]
I reported the same issue in the ticket #4853

**Comment by Redth** [comment]
Can you post the last few hundred lines of your log file? the java error itself is in there and will tell more about what part is failing.

**Comment by pierrebrito** [comment]
This is the error that appears to me.

![image](https://user-images.githubusercontent.com/6466875/159599373-ac107a33-a77a-4037-b331-bc17e5c6256a.png)

**Comment by powerdude** [comment]
My log file from a month ago.  sorry for the delay but I thought someone would open the project file and just build it. 

[MyCompany.MyApp.build.zip](https://github.com/dotnet/maui/files/8526298/MyCompany.MyApp.build.zip)

**Comment by pierrebrito** [comment]
In my case it was a problem with the libraries.
I put tools:replace="android:label" in manifest.application and it solved.

**Comment by jfversluis** [comment]
The actual error in the aforementioned log is

> 8>        D:\code\MyApp - Copy\MyCompany.MyApp\obj\Debug\net6.0-android\AndroidManifest.xml:24:18-86 Error:
8>        	Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from AndroidManifest.xml:24:18-86
8>        	is also present at AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
8>        	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:13:3-38:17 to override.

"java.exe exited with code 1" always means there is an underlaying cause so inspect the logs closely to see what it is. Assuming this will give you enough information to continue on your own.

**Comment by powerdude** [comment]
not sure why this is closed.  I didn't add the anything in the xml files and the template/file was generated by VS.  Has VS/Maui looked to make sure this doesn't happen again?

**Comment by powerdude** [comment]
Not sure why this was closed.  I didn't manually add anything to the `AndroidManifest.xml` file.  Has there been work to ensure this issue is addressed in the tooling/templates?
