### ISSUE TITLE
MauiApp cannot deploy on Windows

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4896]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MauiApp-cannot-run-on-Windows/1670999)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.1.0 latest preview]
Having upgraded to VS 2022 v 17.2.0 Preview 1.0 including MAUI preview 13, a freshly created Maui App cannot deploy on Windows because of a missing splash screen png:

Error DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(33,27): error 0x80070003: Cannot install or update package 36925A76-3BD2-44B7-AD6D-BD80D3D7BBF2_9zz4h110yvjzm because the splash screen image [appiconfgSplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found.	MauiApp4			

---
#### Feedback Bot on 2/20/2022, 10:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/20/2022, 11:45 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
#### Lars Hammer solved on 2/20/2022, 07:53 AM, 1 votes: 

<p>Upgrading the maui templates using<br>
<code>dotnet new --install Microsoft.Maui.Templates::6.0.200-preview.13.2865</code><br>
solves this issue when creating a new MAUI App.</p>
<p>It would be nice, if the process of upgrading VS could include updating the MAUI templates or maybe warn about the need to manually update 😃</p>
<p>In case of an existing MAUI App project - these changes worked for me:</p>
<ul>
<li>remove all references to the ‘Assets\’ subfolder from the Platforms\Windows\Package.appxmanifest file</li>
<li>add a line about raw assets to the .csproj file in the ItemGroup that contains the MauiIcon, MauiSplashScreen, MauiImage, MauiFont tags:<pre><code class="language-xml"><span class="hljs-tag">&lt;<span class="hljs-name">ItemGroup</span>&gt;</span>
  ...
  <span class="hljs-comment">&lt;!-- Raw Assets (also remove the "Resources\Raw" prefix) --&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">MauiAsset</span> <span class="hljs-attr">Include</span>=<span class="hljs-string">"Resources\Raw\**"</span> <span class="hljs-attr">LogicalName</span>=<span class="hljs-string">"%(RecursiveDir)%(Filename)%(Extension)"</span> /&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">ItemGroup</span>&gt;</span>
</code></pre>
</li>
</ul>

**Comment by Redth** [comment]
Thanks for posting a follow-up.

The issue is that you are manually installing the templates from the CLI which will always override and take precedence over the templates which are installed with visual studio.

If you run `dotnet new -u Microsoft.Maui.Templates` you should find that the correct version is used in Visual Studio which is installed with Visual Studio.
