### ISSUE TITLE
Determine non-HTTP(S) link handling behavior

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#4897]
https://github.com/dotnet/maui/pull/4645 was focused on HTTP(S) link handling. We may want to consider how we're handling non-HTTP(S) links (ex. to open a PDF, app store, etc.).

![image](https://user-images.githubusercontent.com/14852843/155600088-ac87f5bb-fc38-4c13-865e-98f9fb6df5b2.png)

**Comment by v-longmin** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots that we can reproduce this issue? That should greatly speed up the process, thanks!

**Comment by TanayParikh** [comment]
Validated with:

Works:

```html
<a href="https://maps.google.com/?q=Houston,+TX">https</a>

<a href="geo:124.028582,-29.201930" target="_blank">Click here for map</a>
```

Crashes app:

```html
<!-- From https://stackoverflow.com/a/65034190/17995448 -->
<a href="intent://Htfw2s2oCvw/#Intent;scheme=vnd.youtube;package=com.google.android.youtube;S.browser_fallback_url=market://details?id=com.google.android.youtube;end;">youtube or market</a>


<!-- From https://stackoverflow.com/a/31876044/17995448 -->
<a href="intent://apphostname#Intent;scheme=appname;package=your.package.name;S.browser_fallback_url=http%3A%2F%2Fwww.example.com;end">with alternative</a>

```


I believe at the very least we should support the `browser_fallback_url` and definitely prevent the crash. Removed from the .NET7 milestone for us to re-evlauate.
