### ISSUE TITLE
Not possible to include a RazorClassLibrary  in a .NET Maui App targetting Android

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4898]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Not-possible-to-include-a-RazorClassLibr/1658756)._

---
[severity:I'm unable to use this version]
Steps to reproduce:

Create a brand new .NET MAUI app and a RazorClassLibrary. Reference the lib and point to the Razor library in the router 

`<Router AppAssembly="@GetType().Assembly" AdditionalAssemblies="new[] { typeof(WebviewAppSharedMaui.Shared.MainLayout).Assembly}">...`

Now use Android as the target for the .NET MAUI app. It fails building with the following error:

`NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'android-x64'.	BlazorMauiApp	C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	427`

---
#### Feedback Bot on 2/9/2022, 06:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Daniel Roth [MSFT] on 2/16/2022, 09:02 AM: 

<p>I’m unable to reproduce this issue with the latest .NET MAUI Preview 13 release. Could you please try your scenario again with .NET MAUI Preview 13 (available with VS2022 17.2 Preview 1) and confirm whether you are still experiencing this problem? Thanks!</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This error happens when you reference a library that has a framework reference for ASP.NET Core. In the case of RCL, this can happen, if you have checked the `Pages and Views` checkbox. For .NET MAUI Blazor projects that checkbox should be unchecked.
