### ISSUE TITLE
Impossible publish to folder

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4899]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Impossible-publish-to-folder/1652505)._

---
No matter what settings I use, I can't successfully publish to folder a .Net MAUI app. It systematically fails.
Please find the log with the reason for the failure.
[Screenshot (137).png] (https://aka.ms/dc/file?name=B8856a80d3dd148f7a05111d6b3c56db6637793834428866845_Screenshot_(137).png&tid=8856a80d3dd148f7a05111d6b3c56db6637793834428866845).
Since the first preview versions of ".Net Maui" I've never been able to publish to
net6.0-windows (folder)
This is the error as reported in the log:
02/02/2022 08:27:14
System.AggregateException: One or more errors occurred. ---> Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 

===================

---
#### Feedback Bot on 2/2/2022, 08:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/14/2022, 02:50 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### James Parsons [MSFT] on 2/16/2022, 11:59 PM: 

<p>After some investigating, it appears that Visual Studio currently does not support publishing Maui apps for Windows. See more info here: <a target='_blank' href="https://github.com/dotnet/maui/issues/4329">https://github.com/dotnet/maui/issues/4329</a></p>
<p>The current method for publishing Maui apps is via the CLI.</p>

---
### Original Solutions
(no solutions)

**Comment by Redth** [comment]
Closing as indicated in the ticket, https://github.com/dotnet/maui/issues/4329 will help publish via CLI
