### ISSUE TITLE
Label FontSize is ignored when using FormattedText

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#4902]
### Description

In XF you could set the font size on the label and the spans would use that unless explicitly set on the span. Now we need to set the font size on every span, which is much more cumbersome.

### Steps to Reproduce

Add a label, set a font size, add a formatted text.
Run it, the font size is ignored and the spans uses an unknown default

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

iOS 15, windows

### Did you find any workaround?

Add font size to every span.

FYI: Finding the span font size doesn't work when the font size changes, I raised a separate issue for that.

**Comment by YuqinSong** [comment]
Verified Repro. Repro project is available:
[#4902.zip](https://github.com/dotnet/maui/files/8150168/4902.zip)

**Comment by Redth** [comment]
Fixed in #5029

Please open a new issue if there is still a problem in the upcoming RC1 release.
