### ISSUE TITLE
ImageButton Image not scaling down by Width- and HeightRequest

### ISSUE THREAD

**Issue by Tardigrade42** [dotnet/maui#4913]
### Description

When an ImageButton is sized by using the Width- and HeighRequest, the image inside is not sized down as well, but instead cropped. This means, that only a part of the image is visible inside the button.

P. S.: I don't know which MAUI version I am using. I have the VS2022 version *17.2.0 Preview* installed.

### Steps to Reproduce

Add the following line of code to the example Maui-App:
```C#
 <ImageButton
                Source="dotnet_bot.png"
                WidthRequest="40"
                HeightRequest="40" />
```

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 (OS build 19044.1526)

**Comment by Amir-Care** [comment]
Repro on Windows, VS Version 17.2.0 Preview 2.0 [32219.17.main]. Sample project [MauiApp21.zip](https://github.com/dotnet/maui/files/8150034/MauiApp21.zip)
