### ISSUE TITLE
Width and Height value of ContentPage not filled

### ISSUE THREAD

**Issue by Tardigrade42** [dotnet/maui#4915]
### Description

The Width and Height property of the ContentPage do not update. They remain -1 and -1.

P. S.: I don't know which MAUI version I am using. I have the VS2022 version *17.2.0 Preview* installed.

### Steps to Reproduce

1. Add the following code to the MainPage.xaml:
```XML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}"
             x:Name="cp">

    <Grid x:Name="grid">
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="100"/>
        </Grid.RowDefinitions>
        <Label Grid.Row="1" x:Name="label1"></Label>
        <Label Grid.Row="2" x:Name="label2"></Label>
        <Button Grid.Row="3" Text="Refresh" Clicked="RefreshNumbers"></Button>
    </Grid>
</ContentPage>
```

2. Add the following code to the Mainpage.xaml.cs
```C#
namespace MauiApp2;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}

	public void RefreshNumbers(object sender, EventArgs args)
    {
		label1.Text = "The size of the ContentPage is:\nWidth:" + cp.Width + " Height: " + cp.Height;
		label2.Text = "The size of the Grid is:\nWidth:" + grid.Width + " Height: " + grid.Height;
	}
}
```
3. Compile and press the button. The values of the Grid layout will update, but the ContentPage will show -1 and -1.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 10 (OS build 19044.1526), Android 11

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
This should be fixed in the next preview release

<img width="652" alt="image" src="https://user-images.githubusercontent.com/5375137/155893830-6cca9baf-e18c-4cb5-9409-83c81a26ef17.png">

**Comment by v-longmin** [comment]
Verified repro. Repro projects: [MauiApp4.zip]("\\mlangfs1\Public\dotnet maui\Repro Project\MauiApp4.zip")

**Comment by emorell96** [comment]
> 

Does this fix work for obtaining the height using App.Current.MainPage when I am using a Shell as MainPage?

Thanks!

**Comment by shimingsg** [comment]
@emorell96 , verified it works to get the height using  App.Current.MainPage with vs 17.3.0 Preview 1.0 [32426.537.main]
is this your expected?
![image](https://user-images.githubusercontent.com/20982341/165686503-4d3bb642-7146-47a4-82d3-df52a9dd686a.png)

**Comment by samhouts** [comment]
No longer reproducible

**Comment by Tardigrade42** [comment]
This looks just as I expected! Thank you :)
