### ISSUE TITLE
[Windows] Button in BindableLayout Don't Get Unhighlighted When Mouse Leaves

### ISSUE THREAD

**Issue by DeanFaizal** [dotnet/maui#4918]
### Description

On Windows, hovering over buttons in a bindable layout highlights the buttons, but moving the mouse away does not un-highlight the button reliably.

https://user-images.githubusercontent.com/2334530/155745831-a0b5d0e3-e15b-403e-b634-f328dd333ec3.mp4

Sample ContentView XAML (simplified) from my project:
`            
<ContentView>
        <ContentView.Resources>
            <DataTemplate x:Key="NotSelectedDataSetTemplate">
                <Button Text="{Binding Name}" 
                    TextColor="{StaticResource SecondaryTextColor}"
                    VerticalOptions="Center"
                    HorizontalOptions="Center"
                    BorderColor="White"
                    BorderWidth="1"
                    BackgroundColor="Transparent"
                    HeightRequest="25"
                    Padding="0"
                    Margin="0"
                    FontSize="12">
                </Button>
            </DataTemplate>
        </ContentView.Resources>
        <ContentView.Content>
            <StackLayout 
                Spacing="5"
                Orientation="Horizontal"
                BindableLayout.ItemsSource="{Binding DataSets}"
                BindableLayout.ItemTemplate="{StaticResource NotSelectedDataSetTemplate}">
            </StackLayout>
        </ContentView.Content>
    </ContentView>
`

### Steps to Reproduce

1. Create a StackLayout that uses BindableLayout.ItemsSource and has a Button in the DataTemplate.
2. Populate the items
3. Hover over the Buttons

Expected Result:
Buttons un-highlight when mouse moves off them

Actual Result:
Buttons stay highlighted

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

**Comment by shimingsg** [comment]
verified reproducible with VS 17.2.0 Preview 2.0 [32224.339.main]
demo:
[4918.zip](https://github.com/dotnet/maui/files/8152060/4918.zip)

**Comment by Redth** [comment]
Fixed in #5122
