### ISSUE TITLE
CTI scenario: Blazor Hybrid targeting Android from VS (Windows)

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#4919]
### Description

This is one of the items required for https://github.com/dotnet/aspnetcore/issues/39933

### Instructions

Create a new guide in https://github.com/aspnet/AspNetCore-ManualTests/tree/release/6.0/AspNetCore60/BlazorHybrid called `60_BlazorHybrid_Android_FromWindows.md`. It can follow the same pattern as [the WinForms one](https://github.com/aspnet/AspNetCore-ManualTests/blob/release/6.0/AspNetCore60/BlazorHybrid/60_BlazorHybrid_WinForms.md) (in fact you could start by copy-pasting that), but can be slightly more shorter because there's a proper project template for this case so you don't need so many "getting started" steps.

It needs to cover the following workflows:

* Creating a project using the template
* Running it in the Android emulator (and/or on a local physical device)
* Adding the "Sample Content" RCL and verifying that the built-in functionality all works
* Debugging
* Hot Reload
* Accessing browser dev tools
* Publishing, which for GA will need to be done through CLI

To reduce the workload, you can use the same "Sample Content" RCL from the WinForms guide, and in many cases you can even reuse the same screenshots, since they are cropped where possible to be independent of the target platform.

For anything that can't be made to work just yet, please write up the expected steps anyway, and file a bug describing the incomplete product area (and link to that bug from the CTI guide so people know to skip that step).

**Comment by TanayParikh** [comment]
@SteveSandersonMS I started looking into the Android scenario using MacOS as I wasn't having much luck with the iOS / MacOS scenarios. The initial setup (Android studio, SDK, AVD) is likely similar between Windows & MacOS. I've pushed the changes here in case you want to re-use any of the bits: https://github.com/aspnet/AspNetCore-ManualTests/compare/release/6.0...taparik/macosBlazorHybridTests?expand=1

**Comment by SteveSandersonMS** [comment]
https://github.com/aspnet/AspNetCore-ManualTests/pull/1225
