### ISSUE TITLE
CTI scenario: Blazor Hybrid targeting iOS from Windows

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#4921]
### Description

This is one of the items required for https://github.com/dotnet/aspnetcore/issues/39933

### Instructions

Create a new guide in https://github.com/aspnet/AspNetCore-ManualTests/tree/release/6.0/AspNetCore60/BlazorHybrid called `60_BlazorHybrid_iOS_FromWindows.md`. It can follow the same pattern as [the WinForms one](https://github.com/aspnet/AspNetCore-ManualTests/blob/release/6.0/AspNetCore60/BlazorHybrid/60_BlazorHybrid_WinForms.md) (in fact you could start by copy-pasting that), but can be slightly more shorter because there's a proper project template for this case so you don't need so many "getting started" steps.

It needs to cover the following workflows. This should be using Visual Studio on Windows with a connection to a Mac build host.

* Creating a project using the template
* Running it in the iOS simulator (and/or on a local physical device)
* Adding the "Sample Content" RCL and verifying that the built-in functionality all works
* Debugging
* Hot Reload
* Accessing browser dev tools
* Publishing, which for GA will need to be done through CLI. This doesn't need to include app store submission, but up to generating the build archive.

To reduce the workload, you can use the same "Sample Content" RCL from the WinForms guide, and in many cases you can even reuse the same screenshots, since they are cropped where possible to be independent of the target platform.

For anything that can't be made to work just yet, please write up the expected steps anyway, and file a bug describing the incomplete product area (and link to that bug from the CTI guide so people know to skip that step).

**Comment by captainsafia** [comment]
This is completed now. No issue found in iOS from Windows scenario.
