### ISSUE TITLE
Unable to install main Maui following Dev instructions

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/maui#4934]
### Description

Following the directions for installing the maui workload (main branch) from https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md fails with the following error:
```
Workload installation failed: Failed to install manifest microsoft.net.workload.mono.toolchain version 6.0.3: microsoft.net.workload.mono.toolchain.manifest-6.0.200::6.0.3 is not found in NuGet feeds [https://aka.ms/dotnet6/nuget/index.json;https://api.nuget.org/v3/index.json"..](https://aka.ms/dotnet6/nuget/index.json;https://api.nuget.org/v3/index.json%22..)
```

The reproduction steps last worked at the beginning of the week before a xamarin-macos update that was fixed with (https://github.com/xamarin/xamarin-macios/pull/14225). 

### Steps to Reproduce

Specific script that should be runnable to replicate:
```
curl -o dotnet-install.ps1 https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1
./dotnet-install.ps1 -Channel 6.0.2xx -Quality daily 
dotnet workload install maui `
   --from-rollback-file https://aka.ms/dotnet/maui/main.json `
   --source https://aka.ms/dotnet6/nuget/index.json `
   --source https://api.nuget.org/v3/index.json
```

The minimum step number is to Install the latest 6.0.2 sdk version matching the sdk band specified in eng/Versions.props file, then run the workload install command for main specified in the https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md Doc

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

All

### Did you find any workaround?

Current work around found with @jonathanpeppers is to use the NuGet config file (https://raw.githubusercontent.com/dotnet/maui/main/NuGet.config) in place of the sources and adding `"microsoft.net.workload.emscripten": "6.0.2"` to the rollback file for the rollback.

**Comment by jonathanpeppers** [comment]
@mattleibow so I guess:
1. Should we put emscripten back in the rollback file?
2. I guess we have to put instructions to use a `NuGet.config` from dotnet/maui/main?

I don't know how we make this break less often...

**Comment by mattleibow** [comment]
If we put Emscripten back, does it actually fix the issue? If so, then we can.

**Comment by mattleibow** [comment]
About the config, that is always going to be annoying. People will have to download anyways. Or use the paths directly via a copy paste.
