### ISSUE TITLE
[Bug] Windows button rollover doesn't update on rollout

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#4935]
### Description

When I hover a button on Windows the text color changes to white, and doesn't return to the color I set when I mouse out.

a/ I expect to be able to style the hover state
b/ I expect on mouse out to return to the Normal (default) state

https://user-images.githubusercontent.com/41873/155808347-9827b927-e279-42c1-bddb-51d649ae23a8.mp4

[MauiApp25.zip](https://github.com/dotnet/maui/files/8145066/MauiApp25.zip)

### Steps to Reproduce

Run the code targeting windows and mouse over a button

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

latest

**Comment by YuqinSong** [comment]
Verified repro according to the above project.

**Comment by mobycorp** [comment]
@davidortinau David, how are you coding this? I just reported a similar issue, but I am stumped at even ho to get the PointerOver visual state to work when the controls I look at (like buttons or tabs) don't seem to have any event to watch or trigger from...

**Comment by hartez** [comment]
This is pretty much a non-issue now, because we have cross-platform support for PointerOver and that's what folks should be using (rather than relying on the WinUI platform stuff). 

For example, in this project, you'd do something like this in DefaultStyles:

```XAML
<VisualStateGroup x:Name="CommonStates">
    <VisualState x:Name="Normal" />
    <VisualState x:Name="Pressed">
        <VisualState.Setters>
            <Setter Property="Scale" Value="0.8" />
        </VisualState.Setters>
    </VisualState>
    <VisualState x:Name="PointerOver">
        <VisualState.Setters>
            <Setter Property="Scale" Value="1.1" />
        </VisualState.Setters>
    </VisualState>
    <VisualState x:Name="Focused" />
</VisualStateGroup>
</VisualStateGroupList>
```

So closing this; feel free to re-open it if you disagree.
