### ISSUE TITLE
VisualTypeConverter loops over all assemblies looking for IVisual types

### ISSUE THREAD

**Issue by eerhardt** [dotnet/maui#4937]
### Description

We are getting trimmer warnings here:

```
C:\git\maui\src\Controls\src\Core\Visuals\VisualTypeConverter.cs(75,26): Trim analysis warning IL2026: Microsoft.Maui.Controls.VisualTypeConverter.Register(Assembly,Dictionary<String,IVisual>): Using member 'System.Reflection.Assembly.GetExportedTypes()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed. [C:\DotNetTest\MauiTest\MauiTest.csproj]
C:\git\maui\src\Controls\src\Core\Visuals\VisualTypeConverter.cs(77,7): Trim analysis warning IL2062: Microsoft.Maui.Controls.VisualTypeConverter.Register(Assembly,Dictionary<String,IVisual>): Value passed to parameter 'visual' of method 'Microsoft.Maui.Controls.VisualTypeConverter.Register(Type,Dictionary<String,IVisual>)' can not be statically determined and may not meet 'DynamicallyAccessedMembersAttribute' requirements. [C:\DotNetTest\MauiTest\MauiTest.csproj]
```

The issue is that the `VisualTypeConverter` looks at all the assemblies in the process looking for types that implement `IVisual`:

https://github.com/dotnet/maui/blob/5d8b7988e47a9f5a3a25d2613b0b961670bae10a/src/Controls/src/Core/Visuals/VisualTypeConverter.cs#L27-L38

https://github.com/dotnet/maui/blob/5d8b7988e47a9f5a3a25d2613b0b961670bae10a/src/Controls/src/Core/Visuals/VisualTypeConverter.cs#L68-L77

This is not trim-safe, since Types that are not referenced by IL can be trimmed by the trimmer. But in the converter code, it takes a `string` object and then tries looking up in the "registered mapping" for the `IVisual` by the string name. This can break trimmed apps because the Type being referenced by that string may have been trimmed.

In talking with @Redth and @PureWeen this approach is out-of-date, and we should remove the assembly scanning. Instead, we should add a "trim-compatible" method for doing this registration. For example:

1. Using an assembly-level attribute (which we already have: lower in that InitMapping method).
2. Adding a new `builder.RegisterVisual<TVisual>()` method that people can add to their `CreateMauiApp()` method. This will register the Visual type statically, and the Types that aren't referenced can be safely trimmed.

### Steps to Reproduce

1. `dotnet new maui`
2. `dotnet restore`
3. `dotnet build -f net6.0-android -r android-arm64 -t:Run -c Release --no-restore -p:SuppressTrimAnalysisWarnings=false -p:TrimmerSingleWarn=false /bl`
4. Inspect the trimmer warnings for mentions of `VisualTypeConverter`.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro with provided repro steps in terminal.

**Comment by rmarinho** [comment]
Fixed by https://github.com/dotnet/maui/pull/20417
