### ISSUE TITLE
Security in MAUI we need the basic tampering checks

### ISSUE THREAD

**Issue by developer9969** [dotnet/maui#4943]
### Description

First of all
I just cannot wait for MAUI to be released. Is going to be great, now some moaning though 

In the real world

-  We need to make the app secure
-  We need to pass penetration tests
-  We need to answer questions from our clients  "How secure is your app?"

Now  I totally get it that this is a cat and mouse game and probably you dont want to get involved, but  I think as a Microsoft product you should offer the basics functionalities. Please dont say "oh they are third parties" well as a company those 3 parties cost $8-10000 a year.

This is something that MAUI/essentials should really offer

1. Basic tampering checks to detect if the device is compromised  IsDeviceRooted /JailBroken  
2. iOS Certificate Pinning using native handlers, how do you do it in iOS without using very dated code. I.E ServicePointManager

As soon as you search the web on the above you are hit with hundreds of articles on how to bypass those with Frida etc..., however it does offer a little layer of protection, and to pass penetration testing those are requirements.

Realistically I know that you will never enter this "game" but what you could do

- Publish more articles on how todo tampering checks 
- How todo certificate pinning in iOS using native handlers
- How to make your api secure if the mobile device has been compromised.

In my personal view  in the Mobile Microsoft ecosystyem we have 3 holes:

1. Mobile Security (we are left on our own)
2. UI Testing (sorry this is just not working as it stands) Appcenter is not good at all on this one
3. Android start up ( which is flagged as a warning in google play console)   Can you launch an app in less than 3 seconds without AOT?

Now lets see if someone cares to reply with some constructive comments on how to approach the above.

Many thanks

### Public API Changes

I suggest the following

DeviceInfo.IsRooted ( Check for cloakingApp,SuspiciousApps  - check for malicious binay IE Magisk)
DeviceInfo.IsRunningOnVirtualDevice
DeviceInfo.AmIBeingDebugged
DeviceInfo.IsValidInstaller (I.E installed from playstore)
How to do Cert pinning in iOS and prevent bypassing!  Man in the middle rejection
The list goes on ... 

### Intended Use-Case

Without the basic tampering checks in place an app that handles sensitive data will not pass Pen testing!

**Comment by erfan132** [comment]
Hi i have the same question about this framework
In winform and wpf we have security problem in protecting our source but in Uwp we have some extra protection
now my questions is 
In MAUI is it possible to have some extra protection?

**Comment by Fabi** [comment]
That is not the job of  maui or the net framework

**Comment by developer9969** [comment]
@Fabi whos job it is then? Can u explain a bit more with some constructive and more elaborated answer?

How do you do your security in the xamarin world then?

**Comment by Fabi** [comment]
> @Fabi whos job it is then? Can u explain a bit more with some constructive and more elaborated answer?
> 
> How do you do your security in the xamarin world then?

It's the developers job to do the things you listed not the frameworks.

**Comment by developer9969** [comment]
Disagree.

**Comment by developer9969** [comment]
waste of time to raise this issue ,security is definetely not important to MS and I dont buy the BS that is a developer job..
