### ISSUE TITLE
[iOS] [Android] Grid measuring auto size row incorrectly when using RowSpan

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#4947]
### Description

Auto sized row is using full height of grid when adding a BoxView with RowSpan that covers all rows.

### Steps to Reproduce

Add a grid with several rows, first auto, the others star.
Add a BoxView at row 0 col 0 RowSpan to cover all the rows.
Add a label at row 0 with the text 'bla'.
Run it

Expect to see row zero to be the height required by the label (works on Windows)
On iOS and Android, row zero becomes the full height of the grid

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS & Android

### Affected platform versions

iOS 15

### Did you find any workaround?

No

**Comment by hartez** [comment]
No longer happening with the latest in main. Should be fixed as of RC3 at least, possibly RC2.
