### ISSUE TITLE
QR and Barcode Scanning

### ISSUE THREAD

**Issue by alberk8** [dotnet/maui#4960]
### Description

I would be very useful to have QR and Barcode scanning.

### Public API Changes

 [API](https://github.com/Redth/BigIslandBarcoding)

### Intended Use-Case

QR code is pervasive so a build in capability will allow apps to be quickly implemented.

**Comment by jfversluis** [comment]
As you've already linked, we're working on creating a library for that which is basically the ZXing library but compatible for .NET MAUI. We hope to have it ready at or around GA.

**Comment by alberk8** [comment]
Wow.  How soon can this be tested in Beta?

**Comment by jfversluis** [comment]
Unfortunately I don't have any info in that regard at this time.
