### ISSUE TITLE
VS 2022 17.2.0 preview 1 - Cant compile project because of MAUI:GridLayout 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4966]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-1720-preview-1---Cant-compile-/1674645)._

---
[severity:I'm unable to use this version] [regression] [worked-in:'17.1.0 Preview 4']
Hi!
After update to VS 2022 17.2 preview 1, my MAUI project cant compile, because of the following error:
XFC0000	Cannot resolve type "http://schemas.microsoft.com/dotnet/2021/maui:GridLayout".

My page have <Grid> element, compilation was successful with VS 2022 17.1 Preview 4, but know I'm getting this issue.
If I remove Grid (or replace with StackLayout for example) everything compiles successfully.

---
#### Feedback Bot on 2/23/2022, 11:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I'm assuming this was caused by a project that was created with an earlier version of the templates and can now not be built anymore because of a breaking change in this area.

If you create a new app that should work for existing projects, change references from `GridLayout` to `Grid`

**Comment by Luminisc** [comment]
How can I do this? As I'm using <Grid> element, but for some reason project treats it as GridLayout instead of Grid
