### ISSUE TITLE
ResourceDictionary does not allow removing or modifying styles with classes, i.e. not hot reload friendly

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#4969]
### Description

There is no API to update styles in ResourceDictionary when modifying styles with classes. Consider following:
```
<StackLayout>
  <StackLayout.Resources>
    <Style TargetType="Button" Class="BlueButton">
      <Setter Property="Background" Value="DarkBlue"/>
    </Style>
    <Style TargetType="CheckBox" />
    <Style TargetType="Button" Class="BlueButton">
      <Setter Property="Margin" Value="10"/>
    </Style>
  </StackLayout.Resources>
</StackLayout>
```
Now consider XAML Hot Reload scenarios where user changes Margin value from 10 to 20. Currently there is no public API to find style within RD. Because [RD.Add(Style style)](https://github.com/dotnet/maui/blob/d182da81ee7c1581925f03da168b62adf7953c5d/src/Controls/src/Core/ResourceDictionary.cs#L300) adds style to a magic entry. That entry is actually a list of styles. This is neither documented nor properly exposed. Even if VS makes assumptions current implementation details, we still have an issue of calculating correct index into that magical list. Index calculation gets even more complicated when user changes or value of Style.Class or pastes multiple styles with classes.

### Steps to Reproduce

See description

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

all

**Comment by etvorun** [comment]
This is a dupe of https://github.com/dotnet/maui/issues/620 and https://github.com/dotnet/maui/issues/621

**Comment by shimingsg** [comment]
close it due to dup issue , please track to https://github.com/dotnet/maui/issues/620 and https://github.com/dotnet/maui/issues/621
