### ISSUE TITLE
Shadow markup extension error

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#4974]
### Description

<img width="848" alt="image" src="https://user-images.githubusercontent.com/41873/156070332-9411ac06-f663-40c5-af50-33539cf450b0.png">

I can do this, and it works as you can see:

```xaml
<Style TargetType="Button">
                <Setter Property="BackgroundColor" Value="{StaticResource SecondaryColor}"/>
                <Setter Property="TextColor" Value="{StaticResource PrimaryColor}"/>
                <Setter Property="FontSize" Value="36"/>
                <Setter Property="FontFamily" Value="DigitalDismay"/>
                <Setter Property="Margin" Value="8"/>
                <Setter Property="HorizontalOptions" Value="Center"/>
                <Setter Property="WidthRequest" Value="80"/>
                <Setter Property="HeightRequest" Value="80"/>
                <Setter Property="Shadow" Value="{Shadow Brush=Black, Offset='8,8', Opacity=0.4, Radius=16}"/>
            </Style>
```

But I get the squiggle which subsequently breaks Hot Reload in some cases.

Please don't squiggle at me. 

### Steps to Reproduce

1. Add this style to a project and observe

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

all

**Comment by XamlTest** [comment]
Verified Repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32227.94.main]. Repro Project is available: [4974.zip](https://github.com/dotnet/maui/files/8158279/4974.zip)

**Comment by StephaneDelcroix** [comment]
that's the 2nd one popping up today. @mgoertz-msft let's talk

3 options here:
- make sure there are no XLS error for non-markup used as markup
- inherit Shadow from IMarkupExtension, so ProvideValue returns `this`. If so:
  - we have to make sure all BP are actually Bindable (which is usually not the case with a markup extension)
  - what about everything else ? Should all our non-control types implements IMarkupExtension then ?
- no longer support this syntax, and have verbose XAML instead

**Comment by mgoertz-msft** [comment]
Same question as on the other thread: So what's the rule here? How does the user know what can be treated like a markup extension?

**Comment by mgoertz-msft** [comment]
Or are you saying that any type can be used with MarkupExtension syntax?

**Comment by StephaneDelcroix** [comment]
@mgoertz-msft sorry, I thought I replied to this weeks ago.

yes, we support markupextension syntax for types that do not implement IMarkupExtension. it has always been this way in XF too. It makes a nice json-y shortcut for some constructs, and has advantages over markup extensions that those can be BindableObject and have a binding context, so you can set properties using {Binding} in there. IMarkupExtension, even if they were inheriting BO wouldn't get the context passed...

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix Thanks for confirming. I guess this is not very widely known/used though since we have always shown that as an error. I will add a backlog item to add support for this. Not sure when we will be able to get to this though.

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix @davidortinau @Redth Not sure why the bot hasn't picked this up but the related "[User Story 1528073](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1528073): Support for using markup extension syntax with any type" was completed for VS 2022 17.4.

I don't have permission to close this either.
