### ISSUE TITLE
The version of “msbuild” is too low to support the functions of visual studio(priview)

### ISSUE THREAD

**Issue by xing123456789** [dotnet/maui#4978]
### Description

Current msbuild version is 16.10.1, It does not support some functions of visual studio and will report an error when running。When printing the msbuild log, the information is as follows
![Uploading 1646101759622.jpg…]()
Thanks

### Steps to Reproduce

1、msbuild --version. ->. 16.10.1
2、msbuild -ds -> error logs
![Uploading 1646101759622.jpg…]()

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

macOS

### Affected platform versions

iOS15

**Comment by jfversluis** [comment]
Your screenshots are not working. And I'm not really sure what you're trying to do. On macOS you shouldn't use MSBuild, you should use `dotnet build`. MSBuild version 16 indeed does not have all the features required to build .NET MAUI apps.

Closing this for now with too little info. Let us know if this doesn't clarify things for you.
