### ISSUE TITLE
[Android] Gesture issue in Tab pages

### ISSUE THREAD

**Issue by FarFlyer** [dotnet/maui#4979]
### Description

Adding Tabbed pages within android, the "bottom" placement has an issue with swiping.

The tabs are not updated according to the current page (i.e. scrolling to the right page leaves the previous tab page selected.

The code is:
android:TabbedPage.ToolbarPlacement="Bottom"

Setting to "Top" works as expected.

### Steps to Reproduce

use the tab with bottom placement:

android:TabbedPage.ToolbarPlacement="Bottom"

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11.0 API 30

### Did you find any workaround?

android:TabbedPage.ToolbarPlacement="Top" is working fine

**Comment by FarFlyer** [comment]
To reproduce the issue please copy the content of the attached txt file to MainPage.xaml in a new project.

With ToolbarPlacement="Bottom" on android, the swipe gesture shaffles the pages, but the tabs are not updated.
With ToolbarPlacement="Top", the swipe gesture shaffles the pages, and the tabs are updated as expected.


[MainPage.txt](https://github.com/dotnet/maui/files/8168387/MainPage.txt)

**Comment by v-longmin** [comment]
Verified the issue on Android 31,the issue also reproes:
[4979.zip](https://github.com/dotnet/maui/files/8242661/4979.zip)
