### ISSUE TITLE
Using device styles throws an InvalidOperationException

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#4987]
### Description

Xamarin.Forms defines a small number of styles in the `Device` class:

```
        <Label Text="Title style" 
               Style="{DynamicResource TitleStyle}" />
        <Label Text="Subtitle style" 
               Style="{DynamicResource SubtitleStyle}" />
        <Label Text="Body style" 
               Style="{DynamicResource BodyStyle}" />
        <Label Text="Caption style" 
               Style="{DynamicResource CaptionStyle}" />
        <Label Text="List item detail text style" 
               Style="{DynamicResource ListItemDetailTextStyle}" />
        <Label Text="List item text style" 
               Style="{DynamicResource ListItemTextStyle}" />
```

The (truly awful) doc: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/xaml/device

Trying to use them in .NET MAUI results in an `InvalidOperationException`: Cannot convert Accent into Microsoft.Maui.Graphics.Color.

I realise that the `Device` class will be marked obsolete. Just wondering whether an obsolete piece of functionality that throws an exception is considered acceptable or not?  ¯\_(ツ)_/¯

My 2 cents: I think that any styles that we provide would be better defined in a file in the project template, rather than in the framework itself.

Repo: [Styles.zip](https://github.com/dotnet/maui/files/8162405/Styles.zip)

### Steps to Reproduce

1. Run the attached sample (Windows) and attempt to browse to the device styles page. An `InvalidOperationException` is thrown.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

**Comment by v-longmin** [comment]
Verified reproes. Repro project:
[Styles.zip](https://github.com/dotnet/maui/files/8165897/Styles.zip)

**Comment by davidbritch** [comment]
Closing because I was wrong - I've only just found a stray Style in my code that was setting Color.Accent. The Device styles actually work ok, and can be safely obsoleted.
