### ISSUE TITLE
C# Hot Reload Broken in VS 2022 17.2.0 Preview 3

### ISSUE THREAD

**Issue by florianwachs** [dotnet/maui#4989]
### Description

Hot Reload does not work with Windows / Android or IOS.
Doesn´t matter if emulator or native device.

I have a clean Windows 11 install (no insider) and VS 2022 17.2.0 Preview 1 installed.
If I try to change this

```csharp
private void OnCounterClicked(object sender, EventArgs e)
{
	count++;
	CounterLabel.Text = $"Current count: {count}";

	SemanticScreenReader.Announce(CounterLabel.Text);
}
```

to this
```csharp
private void OnCounterClicked(object sender, EventArgs e)
{
count+=3;
CounterLabel.Text = $"Current count: {count}";

SemanticScreenReader.Announce(CounterLabel.Text);
}
```

i get this while debugging:
![image](https://user-images.githubusercontent.com/2216547/156209466-130b2ee0-e12d-4a04-b5d4-ac12f47ea8ab.png)

Hot Reload works fine in Console Apps or ASPNET.

I deinstalled and reinstalled VS 2022 Preview but no effect

### Steps to Reproduce

- dotnet new maui -o mnew3
- open with 2022 Preview
- Start debugging (doesn´t matter if Windows / Android / IOS
- While debugging, change `counter++` to `counter+=3`
- The strange hot reload error happens

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 12

### Affected platforms

iOS, Android, Windows

### Affected platform versions

IOS 15

### Did you find any workaround?

no

### Relevant log output

```shell
no error in logs
```

**Comment by mattscheffer** [comment]
Bug reproduces with a new project in VS 17.2.0 Preview 1. Tested with windows simulator. Any changes to the code trigger this issue. As you can see in the picture below, there are a large number of errors in error list. Roughly 40 of those appear explicitly pressing Hot Reload.

![image](https://user-images.githubusercontent.com/10537189/156256242-c0a7d7dc-6189-4caa-934b-7f50ebf202a2.png)

**Comment by florianwachs** [comment]
Thanks @mattscheffer , I was searching for others with the same problem since it's quite servere.
Out of curiosity, are you all using an internal VS build where this is not a problem?

**Comment by JohnHDev** [comment]
Im seeing the same issue with VS 2022 17.2.0 Preview 1. I have heard there is a Preview 2, but its not available for me to update to as yet. Most annoying.

**Comment by dackjaniels2001** [comment]
Seeing the same issue with a new Maui Blazor app created using VS 17.2.0 preview 1. However, in a new Maui Xaml app  hot reload seemed to work fine (Windows app).

**Comment by drasticactions** [comment]
> Seeing the same issue with a new Maui Blazor app created using VS 17.2.0 preview 1. However, in a new Maui Xaml app hot reload seemed to work fine (Windows app).

XAML Hot Reload and C# Hot Reload are not the same pipelines and (with minimal exceptions) don't directly overlap. One can work without the other.

Can you try the same thing with _just_ iOS, Android, and Windows without MAUI? You should still be able to do C# hot reload with the core platforms without MAUI, and if that fails, there's a _much_ higher chance it's a generic dotnet/xamarin issue and not MAUI specific, in which case we need to transfer this bug over to VSFeedback.

**Comment by florianwachs** [comment]
ok, waited for Preview 2 in hope it would fix anything.... It´s just exaclty the same. Not exacly because I´m now even unable to start debugging in a brand new project with an error that the app can not be deployed. This is so sad.
![image](https://user-images.githubusercontent.com/2216547/158767896-ea527bb5-26b0-483c-b0ca-fded8dd98f7e.png)

**Comment by JohnHDev** [comment]
Confirmed, hot code reload is still broken in preview 14 for Maui projects on iOS, Android and Windows.

@florianwachs what error are you seeing on deploy? I had to make minor changes to upgrade, but all my test projects still compile and deploy, (although having trouble deploying to iOS right now, Windows is fine).

**Comment by RichardMarsh** [comment]
Not sure if related, but I'm having problems with Hot Reload and iOS specifically. Apologies if not related, but didn't want to create a new bug if it is somehow related to this issue. 

See below for error

![image](https://user-images.githubusercontent.com/54434905/158777090-1e658bb6-efdc-479e-8055-8ee31d4c0344.png)

**Comment by florianwachs** [comment]
@JohnHDev , sorry for the missing details. VS outputs 
![image](https://user-images.githubusercontent.com/2216547/158815963-8fcc53c0-95ae-42ed-905b-2d91a15ab94e.png)
 when I start debugging with the emulator. If I start the emulator by hand and then start debugging it it works. But Hot Reload broken in IOS, Android and Windows for me.

**Comment by syedqutub** [comment]
having the same issue

**Comment by dannymoller** [comment]
This is an issue that I also have, however I use a workaround which is to Exclude the folders in 'Platforms' from the project, that you're not going to develop on (for now, until .NET Hot Reload works again). And then remove the target framework inside .csproj for those excluded platforms. Once a fix to this is done, you can easily return the other platforms and continue.
![workaround](https://user-images.githubusercontent.com/10290906/162286155-7a07f9ff-58b5-49ee-b5d9-8b8e7c80511b.png)

**Comment by florianwachs** [comment]
thanks @dannymoller , will try it

**Comment by dannymoller** [comment]
You're welcome. The problem seems to be the lack of automatically finding the right TargetFramework-reference to the right file that it belongs to. Which means for example in AppDelegate.cs inside iOS, you find that it sees net6.0-android. And that's why it gives the errors).
![ios](https://user-images.githubusercontent.com/10290906/162287962-e3996ee6-aa82-4337-8efd-1f74addd61ff.png)

**Comment by florianwachs** [comment]
Tested in VS 2022 17.2.0 Preview 3, now the on top mentioned dialog doesn't pop up, but a dialog telling me it can not perform hotreload and needs to rebuild and restart. I now can check a checkbox that automates this for me, which is indeed better than the situation before. Since MAUI is now considered RC, may I ask if Hot Reload will work on Release next month? I tried it with Blazor MAUI, Maui with Windows / Android target. IOS doesn't work for me because of Apple API Changes which are tracked by a other bug in the VS Community.

**Comment by drasticactions** [comment]
@florianwachs The bug here isn't a MAUI bug, it's a Rosyln bug. If you have a multi-targeted project, Rosyln is generating source builds for _every_ hot reload change, which is causing Visual Studio to go "Hey, I can't apply this change, it's a rude edit, throw an error!"

You can replicate similar behavior if you have a multi-targeted class library with a similar targets file that MAUI uses. 

It is, currently, on track to be fixed for VS 17.3 Preview 1, and it might land in an earlier release in 17.2? But again, to be clear, this is _not_ a MAUI bug.

**Comment by florianwachs** [comment]
@drasticactions thanks a lot for the clarification. I hope it gets fixed soon, since people will definitely hit that when maui is GA.

**Comment by Redth** [comment]
There's a fix landing in VS 17.3 Preview 1 that will address this.

**Comment by florianwachs** [comment]
Thanks a lot @Redth , will try that when available.

**Comment by dannymoller** [comment]
VS 17.3 Preview 1 is out now, and the .NET Hot Reload works now.

**Comment by miao17game** [comment]
I try maui-blazor demo with 17.3 preview 1, but hot-reload still not working with razor components :( .

**Comment by JohnHDev** [comment]
@Redth Hot code reload isn't working for me in RC3/VS 17.3 P1 on Windows. Can you reopen this issue?

**Comment by peter-bozovic** [comment]
Also not working on newly created Blazor Hybrid project with 17.3 P1.1
Only css hot reload works, but if I change html text, or the increment of the counter in the component, nothing updates ...

Maybe not related to this issue as there are other issues specifically related to Blazor Hybrid (#2527, #3973, #4474, #6403), but they are all locked now :(

I'm using the physical device to start and debug the app.
