### ISSUE TITLE
Entity framework working at Debug but not at Release

### ISSUE THREAD

**Issue by achilleaskar** [dotnet/maui#4990]
### Description

I am trying to build a wpf app I have on MAUI where I use EF6. While it works like a charm when debuging, it throws exception at Release. Exception is: "An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the UseMySql call. I use Pomelo .Mysql but also tried with Mysql.EntityFrameworcCore library and didn't work either. The thing is it works loke a charm at debug so it might be some security stuff? 

My connection string is "Server=server;;Database=database;pooling=true;Uid=user;Pwd=password;Convert Zero Datetime=True; default command timeout=3600;SslMode=none;TreatTinyAsBoolean=true;"

This only happens on android. Works both at Debug and Release when testing on windows.

### Steps to Reproduce

Haven't tried yet a new app

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by achilleaskar** [comment]
![image](https://user-images.githubusercontent.com/16504165/156341333-90d7d66d-8152-419c-8224-4995e23438e3.png)

**Comment by achilleaskar** [comment]
Hi I created a new project very basic and the error still occurs. 

https://github.com/achilleaskar/TestEFApp

And the basic database: 
```
CREATE DATABASE  IF NOT EXISTS `testbd` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `testbd`;
-- MySQL dump 10.13  Distrib 8.0.26, for Win64 (x86_64)
--
-- Host: 127.0.0.1    Database: testbd
-- ------------------------------------------------------
-- Server version	8.0.26

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `customers`
--

DROP TABLE IF EXISTS `customers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `customers` (
  `id` int NOT NULL,
  `name` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `customers`
--

LOCK TABLES `customers` WRITE;
/*!40000 ALTER TABLE `customers` DISABLE KEYS */;
INSERT INTO `customers` VALUES (1,'test'),(2,'afsdfasdf'),(3,'awesrar');
/*!40000 ALTER TABLE `customers` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping routines for database 'testbd'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2022-03-10 16:08:02


```

**Comment by bstrother1** [comment]
I should add I am currently experiencing something similar with the Mac catalyst build. Receiving 'Object Reference not set to An instance of an object' when trying to interact with:

protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlServer("Server=localhost,1433; Database=GardenDb2;User=sa; Password=MyPass@word");

Have a regular project (non-maui) w/net 6 that I copied and pasted the code from that works but when added to MAUI (Preview 13) conks out. Has MAUI ever been tested with EF and Mac, is there a recommended db that's recommended, is there a guide?

**Comment by Redth** [comment]
"localhost" will not work from android, as the localhost in that case is the android device, and the database server is not running on your android device.  The same would be true for iOS.

If it's MacCatalyst, you may be running into the issue that TLS connections are required by default and you would need to creat\e exceptions in your Info.plist to allow for non-secure connections.

Android has similar TLS requirements as well.

You can read more on them here: https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/transport-layer-security

**Comment by achilleaskar** [comment]
In my app I use online database but cannot share the connection string. But why even my code sample works perfectly when debugging?
