### ISSUE TITLE
Running dotnet new mauilib produces a warning 'The post action 84c0da21-51c8-4541-9940-6ca19af04ee6 is not supported'

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#4994]
### Description

Run `dotnet new mauilib` and you get this warning:

```
The template ".NET MAUI Class Library (Preview)" was created successfully.

Processing post-creation actions...
The post action 84c0da21-51c8-4541-9940-6ca19af04ee6 is not supported.
Description: Opens Class1.cs in the editor.
```

It's fully functional, and it's supposed to not run that postAction, but there should be no warning about it, either.

The odd thing is that all the project templates (`maui`, `maui-blazor`, and `mauilib`) have the same postAction to open the file in the editor, and all have the same condition to do it only in VS, but yet only the `mauilib` template seems to produce this warning. The template sources _seem_ to be identical for this!

### Steps to Reproduce

1. Run `dotnet new mauilib`
2. That's it.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

N/A

### Did you find any workaround?

No workaround needed; it's a spurious warning.

**Comment by Eilon** [comment]
I found this while working on this fix: https://github.com/dotnet/maui/pull/4991

But this issue repros before and after the fix. So it seems unrelated.

This is the identical post action that all the project templates have (they differ by which files/descriptions they use, but the technical metadata is the same):

```json
    "postActions": [
        {
            "id": "openInEditor",
            "condition": "(HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
            "description": "Opens Class1.cs in the editor.",
            "manualInstructions": [],
            "actionId": "84C0DA21-51C8-4541-9940-6CA19AF04EE6",
            "args": {
                "files": "1"
            },
            "continueOnError": true
        }
    ],
```

**Comment by Eilon** [comment]
Ooooh maybe the bug is this:

```
                "files": "1"
```

And maybe it should be:

```
                "files": "0"
```

Because there's only 1 file listed, so it's probably index 0 and not 1.

**Comment by Eilon** [comment]
My hypothesis above is likely wrong. There are indeed 2 files and we want the 2nd one to open.

**Comment by Amir-Care** [comment]
Reproduce this issue
