### ISSUE TITLE
Make BindableProperty trim-compatible

### ISSUE THREAD

**Issue by eerhardt** [dotnet/maui#4997]
### Description

We have the follow pattern of code in a few places that interact with `BindableProperty`:

https://github.com/dotnet/maui/blob/eec992bc6594312442e1f217716c709e07ee535f/src/Controls/src/Core/Setter.cs#L32-L55

https://github.com/dotnet/maui/blob/eec992bc6594312442e1f217716c709e07ee535f/src/Controls/src/Xaml/ApplyPropertiesVisitor.cs#L558-L583

https://github.com/dotnet/maui/blob/eec992bc6594312442e1f217716c709e07ee535f/src/Controls/src/Xaml/MarkupExtensions/OnPlatformExtension.cs#L74-L100

This code is finding the corresponding `MemberInfo` on the `DeclaringType` of the `BindableProperty` using Reflection. However, the trimmer is raising warnings about this code:

```
C:\git\maui\src\Controls\src\Core\Setter.cs(37,6): Trim analysis warning IL2072: Microsoft.Maui.Controls.Setter.<>c__DisplayClass13_0.<Microsoft.Maui.Controls.Xaml.IValueProvider.ProvideValue>g__minforetriever|0(): '#0' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperty(Type,String)'. The return value of method 'Microsoft.Maui.Controls.BindableProperty.DeclaringType.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
C:\git\maui\src\Controls\src\Core\Setter.cs(47,6): Trim analysis warning IL2072: Microsoft.Maui.Controls.Setter.<>c__DisplayClass13_0.<Microsoft.Maui.Controls.Xaml.IValueProvider.ProvideValue>g__minforetriever|0(): '#0' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Reflection.RuntimeReflectionExtensions.GetRuntimeMethod(Type,String,Type[])'. The return value of method 'Microsoft.Maui.Controls.BindableProperty.DeclaringType.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]

C:\git\maui\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs(564,7): Trim analysis warning IL2072: Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.<>c__DisplayClass37_0.<TrySetValue>b__0(): '#0' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Reflection.RuntimeReflectionExtensions.GetRuntimeMethod(Type,String,Type[])'. The return value of method 'Microsoft.Maui.Controls.BindableProperty.DeclaringType.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
C:\git\maui\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs(576,7): Trim analysis warning IL2072: Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.<>c__DisplayClass37_0.<TrySetValue>b__1(): '#0' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperty(Type,String)'. The return value of method 'Microsoft.Maui.Controls.BindableProperty.DeclaringType.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]

C:\git\maui\src\Controls\src\Xaml\MarkupExtensions\OnPlatformExtension.cs(82,7): Trim analysis warning IL2072: Microsoft.Maui.Controls.Xaml.OnPlatformExtension.<>c__DisplayClass45_0.<ProvideValue>g__minforetriever|0(): '#0' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperty(Type,String)'. The return value of method 'Microsoft.Maui.Controls.BindableProperty.DeclaringType.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
C:\git\maui\src\Controls\src\Xaml\MarkupExtensions\OnPlatformExtension.cs(92,7): Trim analysis warning IL2072: Microsoft.Maui.Controls.Xaml.OnPlatformExtension.<>c__DisplayClass45_0.<ProvideValue>g__minforetriever|0(): '#0' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Reflection.RuntimeReflectionExtensions.GetRuntimeMethod(Type,String,Type[])'. The return value of method 'Microsoft.Maui.Controls.BindableProperty.DeclaringType.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
```

The trimmer is warning because nothing is guaranteeing these properties and methods are going to be preserved in a trimmed app.

As far as I can tell, the reason the `MemberInfo` is being retrieved is so the following code can look up to see if there is a `TypeConverterAttribute` on the member, and use the corresponding `TypeConverter` when converting the property value.

https://github.com/dotnet/maui/blob/eec992bc6594312442e1f217716c709e07ee535f/src/Controls/src/Core/Xaml/TypeConversionExtensions.cs#L71-L80

So if these members are trimmed, the `TypeConverterAttribute` will be trimmed as well, and this conversion code won't work the same after the app is trimmed.

### Options

I can think of the following options to solve this:

1. Add `DynamicallyAccessedMembers.PublicProperties | PublicMethods` to the `DeclaringType` of `BindableProperty`. This will instruct the trimmer to preserve **all** public properties and methods on the `DeclaringType`. This will make the warnings go away and make this code trim-safe. However, it will preserve all the public methods on these types, even if they aren't used. This will result in more unnecessary code to be kept.
2. Add new overloads to `BindableProperty.Create*` methods that take the corresponding `MemberInfo` instance. ex. `BindableProperty.Create("Text", typeof(string), typeof(MyControl), typeof(MyControl).GetProperty("Text"))` This way, the trimmer will preserve the `MyControl.Text` property. At runtime, the above code will check if the `MemberInfo` was supplied to the `BindableProperty`, and if it was it will be used. If the `MemberInfo` wasn't supplied, the above Reflection code will be used to find the member. The existing overloads (that don't take a `MemberInfo`), will be marked as `RequiresUnreferencedCode`, so anyone using them will get a trim warning. Then for all built-in controls, we use the new overloads and point directly to the members so they aren't trimmed.
3. If a `TypeConverter` is all that is needed, we could do the same as (2) above, but just pass in the `typeof(TypeConverter)` to the `BindableProperty.Create*` methods. And then remove the reflection code. If a TypeConverter isn't supplied to the BindableProperty, one isn't used. This would be a change that anyone declaring BindableProperty would need to react to.

The easiest option to take is (1) above. It can be done centrally, without touching all the declarations of `BindableProperty`. However, it comes at a cost of a larger app size. To give an example of the size increase, here are the sum of all the `.dll` in a `dotnet new maui` Android app:

**main**: `10.0 MB`
**Trimming Core, Controls, and Controls.Xaml**: `8.57MB`
**Trimming Core, Controls, and Controls.Xaml + option (1)**: `8.77MB`

So roughly 200 KB of extra IL code is preserved by following this approach. This adds up in iOS apps because that is more code that needs to be AOT'd as well.

### Public API Changes

N/A (for now). See Options above.

### Intended Use-Case

I want my Maui applications to be as small as possible. However, I don't want the application behavior to change after trimming.

cc @StephaneDelcroix @mattleibow @PureWeen

**Comment by simonrozsival** [comment]
This has been resolved in #19310. XAML parsing at runtime is not trim compatible and developers need to make sure that they don't disable XAML compilation in their release builds (they should get a warning if they do #19647).
