### ISSUE TITLE
Events for headset connection status.

### ISSUE THREAD

**Issue by JiuLing-zhang** [dotnet/maui#5000]
### Description

Could it be add an event to see how the headset is connected and disconnected(include bluetooth headset)?

### Public API Changes

```C#
Headset.Connected += () =>
{
    audio.Play();
};
Headset.Disconnected += () =>
{
    audio.Stop();
};
```

### Intended Use-Case

In my app I want play music when headphones are connected and stop when disconnected.

**Comment by Redth** [comment]
Thanks for the suggestion, unfortunately we have no plans to implement this feature.

This sounds like a good opportunity for a community plugin if the underlying platforms support the API's enough to create an abstraction.
