### ISSUE TITLE
Implicit styles not applied to underlying items depending on where they are set.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#5016]
### Description

Styles can have TargetTypes that are applied to the underlying types. If you set a style up explicitly on the element, the "Style" property within that element is populated. However, if you set one up implicitly (Ex. Setting a style on a Grid so all labels have a style) that Style property is `null` and the values are instead set locally on the object.

<img width="455" alt="image" src="https://user-images.githubusercontent.com/898335/156401828-ea24e798-d510-4b85-ab73-afce859dc99b.png">

<img width="481" alt="image" src="https://user-images.githubusercontent.com/898335/156401592-b17d19a1-c5c2-46c9-aca9-10a310522826.png">

While the style is set (so what the user has produced is "true" and is shown) it makes it impossible to see where this value is _actually_ set, making diagnostic tooling impossible for styles like these.

### Steps to Reproduce

Set an implicit style on a few and check the underlying objects.  

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

(It's a MAUI issue, platform doesn't matter)

**Comment by Amir-Care** [comment]
Repro on VS Version 17.2.0 Preview 2.0 [32219.17.main].
Sample project: [MauiApp28.zip](https://github.com/dotnet/maui/files/8174128/MauiApp28.zip)

**Comment by StephaneDelcroix** [comment]
this is working as expected, the Style property should only reflect the value being set to that property. The actual style being applied is computed based on Parent styles, implicit styles, CSS, and the Style Property.

If you want to access the actual set currently applied, it's `internal readonly NavigableElement.MergedStyle _mergedStyle;`
