### ISSUE TITLE
Mac Catalyst Blazor WebView CMD+SHIFT+I doesn't open dev tools

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#5022]
### Description

Expected to open dev tools like on Windows.

### Steps to Reproduce

Open blazor webview -> <key>CMD</key> + <key>SHIFT</key> + <key>I</key>.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac Catalyst

**Comment by mkArtakMSFT** [comment]
We don't think this is supported.
