### ISSUE TITLE
Maui's usage of Reflection to find op_Implicit operators is not trim-compatible

### ISSUE THREAD

**Issue by eerhardt** [dotnet/maui#5023]
### Description

We are getting ILLink trim warnings in the following code:

https://github.com/dotnet/maui/blob/cf6896e276aa02023db22c59a25f1d3b20024e6d/src/Controls/src/Core/Xaml/TypeConversionExtensions.cs#L254-L271

Here are the warnings:

```
C:\git\maui\src\Controls\src\Core\Xaml\TypeConversionExtensions.cs(270,5): Trim analysis warning IL2070: Microsoft.Maui.Controls.Xaml.TypeConversionExtensions.GetImplicitConversionOperator(Type,Type,Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethod(String,BindingFlags,Binder,Type[],ParameterModifier[])'. The parameter 'onType' of method 'Microsoft.Maui.Controls.Xaml.TypeConversionExtensions.GetImplicitConversionOperator(Type,Type,Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
C:\git\maui\src\Controls\src\Core\Xaml\TypeConversionExtensions.cs(275,24): Trim analysis warning IL2070: Microsoft.Maui.Controls.Xaml.TypeConversionExtensions.GetImplicitConversionOperator(Type,Type,Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethods(BindingFlags)'. The parameter 'onType' of method 'Microsoft.Maui.Controls.Xaml.TypeConversionExtensions.GetImplicitConversionOperator(Type,Type,Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\git\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj]
```

This issue is that if the trimmer doesn't see these `op_Implicit` operators being used in IL, it will trim them. This will cause the above code to behave differently in a trimmed application, since the operator is removed. This code won't find it, and it won't be used to do the conversions that it is supposed to do.

### Options

I can only think of 2 high-level options to fix this:

1. Remove this logic from Maui and only allow `TypeConverters` to be used to convert values. This means anything that relies on these `op_Implicit` operators from working would need to be fixed. But at least the behavior would be consistent with or without trimming.
2. Teach the trimmer (somehow, either intrinsically or a custom step) to preserve these `op_Implicit` operators. We did something similar for System.Linq.Expressions in https://github.com/dotnet/linker/issues/1821.

cc @mattleibow @PureWeen @StephaneDelcroix @vitek-karas 

### Steps to Reproduce

(These steps are fuzzy, let me know if you need more detailed steps)

1. Implement a BindableProperty that uses an `op_Implicit` operator to do a conversion from a `string`.
2. Use that BindableProperty in an app.
3. Trim the app

Notice that the conversion through the `op_Implicit` operator doesn't happen in the trimmed app because it was trimmed away.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

**Comment by vitek-karas** [comment]
Ideally we would pursue 1. if possible - remove this code from Maui.

If that doesn't work, we could extend the fix we did for `Linq.Expression` to also handle MAUI. It's kind of a hack, but I don't really see any other option. I think it would be good to measure the impact of this - what it would mean to include all operators everywhere in MAUI. Technically we could do a targeted fix and only include implicit operators, but that would mean slightly different (and yet another) hacky behavior compared to `Linq.Expressions` in the linker - would love to avoid that.

**Comment by mattleibow** [comment]
Is this an improvement? https://github.com/dotnet/maui/pull/5073

Should we do the whole thing differently? What happens if we have a non - generic base or something? We cast anyways, so we can maybe get the value and then cast. It will throw us out was wrong.

**Comment by StephaneDelcroix** [comment]
the reason op_implicit is there isn't to convert from string (we have TypeConverters for that), but for the other cases, like when you provide a Color to a Brush. Iirc it was added for Shell support, so participants in the Shell can be promoted to their parent (you declare a ShellContent when it expects a ShellSection).

As with everything else XAML and Binding, we don't know what we'll be used til runtime unless we enforce XamlC everywhere. That's something I'd want, but won't happen right away
