### ISSUE TITLE
Running installed .NET MAUI Blazor app fails on Windows

### ISSUE THREAD

**Issue by danroth27** [dotnet/maui#5024]
### Description

Running an installed .NET MAUI Blazor app on Windows fails with the following error:

Unhandled exception at 0x00000251D0338198 (Microsoft.ui.xaml.dll) in MauiApp7.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x00000251E04ECF80, 0x0000000000000002).

With some help from some folks on the WDX team I confirmed that the error is coming from a E_PATHNOTFOUND in Application.OnLaunched, presumably related to the HostPage of the BlazorWebView.

The installed app under *\Program Files\WindowsApps* does appear to have the correct wwwroot folder and static files.

The app also runs fine in development from VS. It's only after publishing and installing the app that it fails.

### Steps to Reproduce

1. Create a .NET MAUI Blazor project
2. Publish the project for Windows: `msbuild /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="<Cert Thumbprint>" /p:PackageCertificatePassword="<Cert Password>"`. See [steps for creating a signing cert](https://docs.microsoft.com/windows/msix/package/create-certificate-package-signing)
3. Run the generated .msix installer to install the app and run it (to install the msix you may need to install the App Installer app from the Microsoft Store).

Expected result: App runs fine
Actual result: App fails to start. Error in the Application event log.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

Workarounds: Removing the `HostPage` property from the `BlazorWebView`. The app will then run, but of course the Blazor content won't show up.

**Comment by danroth27** [comment]
@Eilon @mkArtakMSFT @jfversluis

**Comment by SteveSandersonMS** [comment]
@danroth27 Might this be the same issue as https://github.com/dotnet/maui/issues/4151 ?

**Comment by danroth27** [comment]
> @danroth27 Might this be the same issue as #4151 ?

Don't know, but the specific error code (`E_PATHNOTFOUND`) seems to indicate that a specified file path is wrong.

**Comment by SteveSandersonMS** [comment]
One indication would be what happens if you copy the application out of Program Files and into your user directory. If it can run from your user directory but not from Program Files, then it's probably the same as #4151 (i.e., a permissions issue whereby webview2 can't create its own temporary files in the application directory).

**Comment by danroth27** [comment]
I did also try using a vanilla WebView control that pointed to https://microsoft.com and that worked fine. Does that usage not cause WebView2 to try to create temp files in the app directory?

I'm not sure I can just copy an installed msix based app to another location, but I'll give it a shot.

**Comment by SteveSandersonMS** [comment]
Great, thanks for checking. Sounds like there is something BlazorWebView-specific to resolve there then.

**Comment by danroth27** [comment]
If I copy the app out of *\Program Files\WindowsApp* to somewhere else and try to run it, it fails to start earlier in the process due to this error:

```
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at MauiApp7.WinUI.Program.XamlCheckProcessRequirements()
   at MauiApp7.WinUI.Program.Main(String[] args)
```

**Comment by MTCMarkFranco** [comment]
Question, what is the guidance/pattern for a Maui app that incorporates a SQLite DB for offline capability? I.E, being able to write to files within program files\windows Apps? Do we suggest moving the SQLite DB and any other writable files outside of this folder structure, and if so , what is the recommended practice?

**Comment by SteveSandersonMS** [comment]
I tried going through this flow (using MAUI preview 13), and the application works correctly for me.

@danroth27 I wonder if the issue is to do with how you installed the application. You hint that you might have installed it using the *App Installer* app, but I wasn't able to do that because for some reason the Windows Store doesn't let me install that application. Instead I installed it by just double-clicking the `.msix`, after going through a process to trust the publishing cert manually (see below).

Were you able to install it by double-clicking the `.msix` directly, or did you use the *App Installer* app? Could you try installing directly if you didn't already?

### Trusting the publishing cert

   * Right-click on the `.msix` file and choose *Properties*
   * Switch to the *Digital Signatures* tab
   * Select the certificate then click *Details*
   * Click *View Certificate*
   * Click *Install Certificate*
   * Choose *Local Machine* then click *Next*
   * Select *Place all certificates in the following store* then click *Browse* and select the *Trusted People* store. Click *OK*.
   * Click *Next* then *Finish*. Verify that the result is *The import was successful.*.
   * Click *OK* several times until the windows have gone away.
   * Retry double-clicking the `.msix` file and follow the prompts to install it.

**Comment by javiercn** [comment]
I've managed to attach the debugger and this is what I'm observing the moment I try to add the Blazor Webview component.
```
Unhandled exception at 0x00007FF9B1666328 (Microsoft.ui.xaml.dll) in MauiDeployOnWin.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001497FF02DB0, 0x0000000000000006).
```

I'm doing this in the Windows 10 Dev environment setup in hyper-v (a VM)

**Comment by javiercn** [comment]
The issue seems to be on how we use the Win UI storage file

**Comment by javiercn** [comment]
Got this to work, the issue is with how we use some of the Win UI APIs

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/6995051/158799867-8feee9e2-222c-4ded-891d-b138c0da18ff.png">

This is the app deployed on a separate machine

**Comment by SteveSandersonMS** [comment]
Excellent - that's great! Looking forward to finding out what we should be doing differently with the WinUI APIs.

**Comment by javiercn** [comment]
This is a quick workaround that can be placed in the project file

```xml
	<Target Name="_RemoveStaticWebAssetsDevelopmentManifest" BeforeTargets="GetCopyToOutputDirectoryItems">
		<!-- Remove the development manifest from the output since its not used and it will otherwise get incorrectly loaded in production. -->
		<ItemGroup>
			<ContentWithTargetPath Remove="$(StaticWebAssetDevelopmentManifestPath)" />
		</ItemGroup>
	</Target>
```

**Comment by PerryZh** [comment]
@javiercn Thanks for sharing. This quick workaround does work on developer's computers. But it doesn't seem to work on non-dev computers. 

Faulting application name: MauiClient.exe, version: 1.0.0.0, time stamp: 0x6216d2c0
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650
Exception code: 0xc000027b
Fault offset: 0x000000000010b362
Faulting process id: 0x38f4
Faulting application start time: 0x01d8445ddd96ae2b
Faulting application path: C:\Program Files\WindowsApps\6772ECE0-9A8C-4587-AC4A-20F9A1984BE9_1.0.0.0_x64__9zz4h110yvjzm\MauiClient.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: fd8d0619-8bd8-409e-9e91-109db3982a90
Faulting package full name: 6772ECE0-9A8C-4587-AC4A-20F9A1984BE9_1.0.0.0_x64__9zz4h110yvjzm
Faulting package-relative application ID: App

**Comment by lvendramini** [comment]
> @javiercn Thanks for sharing. This quick workaround does work on developer's computers. But it doesn't seem to work on non-dev computers.
> 
> Faulting application name: MauiClient.exe, version: 1.0.0.0, time stamp: 0x6216d2c0 Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650 Exception code: 0xc000027b Fault offset: 0x000000000010b362 Faulting process id: 0x38f4 Faulting application start time: 0x01d8445ddd96ae2b Faulting application path: C:\Program Files\WindowsApps\6772ECE0-9A8C-4587-AC4A-20F9A1984BE9_1.0.0.0_x64__9zz4h110yvjzm\MauiClient.exe Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll Report Id: fd8d0619-8bd8-409e-9e91-109db3982a90 Faulting package full name: 6772ECE0-9A8C-4587-AC4A-20F9A1984BE9_1.0.0.0_x64__9zz4h110yvjzm Faulting package-relative application ID: App

Seems like maybe VS 2022 preview to be installed on the computer for the installer to work (which obviously it shouldn't)?

**Comment by lvendramini** [comment]
We still have issues and  cannot install on some computers as well.

**Comment by danroth27** [comment]
> We still have issues and cannot install on some computers as well.

@rborosak @lvendramini This may be due to a missing dependency on the C runtime. Can you try installing the [Microsoft Visual C++ Redistributable](https://docs.microsoft.com/cpp/windows/latest-supported-vc-redist) on the target machine and see if that helps?

**Comment by rborosak** [comment]
@danroth27 Thank you for the suggestion but I have tried installing C++ Redistributable, .NET Framework, Edge WebView and even WinApp SDK. 
Nothing helped.

**Comment by javiercn** [comment]
@rborosak I would suggest you try the following with WinDBG to see if you can get more information about what's going on.

* Find the app install location with Get-AppxPackage <<PackageId>> (You can grab the package ID from your csproj file)
* Once you've located the install directory, open Win DBG, select Launch executable and point to the exe file on the
packaged app install location.
* Run `sxe clr` on Win DBG to break on managed exceptions
* You might need to load the SoS debugger extension to get commands to debug managed code. Running something like
`!CLRStack` should be enough to trigger windbg to automatically load the sos extension provided there is already
managed code running on the process.
* You can use `g` to continue debugging (equivalent to F5)
* The next time the debugger breaks, you can take a look at the call stack with `kpL`
* When you do that, you'll see something like `mscorwks!RaiseTheExceptionInternalOnly(class Object * throwable = 0x...`
* That throwable = 0x... is your exception object. You can copy that address and run !DumpObj 0x...
* That will print the exception being thrown as well as its fields addresses.
* You can use that (or click on it if you are using WinDbg preview) to see things like the error message or the callstack.

That should give you a really good idea of where the app is failing causing it to crash.

**Comment by rborosak** [comment]
@javiercn ok, but maybe there is a misunderstanding.. my app is never installed... The installer (msix) just hangs at some point and the app never gets installed. 

If I install the app using .ps script, the app itself works without any problems.

**Comment by mattleibow** [comment]
Could this also be the other issue? #6318

Maybe try adding the bits in that PR to your project.
