### ISSUE TITLE
NavigationPage.ToolbarItems not shown on Android and Windows

### ISSUE THREAD

**Issue by vinodshinde** [dotnet/maui#5031]
### Description

Toolbar is not shown on Android. It is shown on iOS.

[ToolBar-Bug.zip](https://github.com/dotnet/maui/files/8174603/ToolBar-Bug.zip)

![iOS-Toolbar_LI](https://user-images.githubusercontent.com/1417468/156488244-adcd3799-ff43-4d2c-bf8e-d7c0a075036a.jpg)
![Android-Toolbar_LI](https://user-images.githubusercontent.com/1417468/156488474-a13f6754-65ec-4f6b-ad24-30c626f88453.jpg)

### Steps to Reproduce

Run attached sample project

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Tested on Pixel XL

### Did you find any workaround?

NO

**Comment by PineYi** [comment]
Reproduce in Android 11 with above project.

**Comment by buyaa-n** [comment]
I might be missing something but i could not find where the missing part (toolbar) is added to the view from the repro

**Comment by vinodshinde** [comment]
it is in App.xaml.cs

```
public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		var nav = new NavigationPage(new MainPage());
		nav.ToolbarItems.Add(new ToolbarItem { Text = "Tb1" });
		nav.ToolbarItems.Add(new ToolbarItem("Act", "appicon.svg", () => { }));
		MainPage = nav;
	}
}
```
