### ISSUE TITLE
NavigationPage.SetTitleView does not work in Android and Windows

### ISSUE THREAD

**Issue by vinodshinde** [dotnet/maui#5032]
### Description

NavigationPage.SetTitleView does not work in Android.

As shown below TitleView is shown in iOS but not in Android

![2022-03-02_10-33-56-PM_LI](https://user-images.githubusercontent.com/1417468/156491838-0259d776-9851-4815-ae1f-1d949af6fcde.jpg)

### On Android `Page Title` is shown instead of `TitleView`

![image](https://user-images.githubusercontent.com/1417468/156491980-35a18222-9ca7-4bd0-a0e7-249959b2e4b1.png)

### Steps to Reproduce

Run attached sample
[TitleView-Bug.zip](https://github.com/dotnet/maui/files/8174808/TitleView-Bug.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Tested on Pixel XL

### Did you find any workaround?

NO

**Comment by PineYi** [comment]
Reproduce in Android 11 with above project.

**Comment by PureWeen** [comment]
duplicate https://github.com/dotnet/maui/issues/3877
