### ISSUE TITLE
[Bug] Gif image not working in MAUI

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#5034]
### Description

I have tried to load Gif image in MAUI platforms (WinUI, iOS, Android)

Instead of animating, loaded gif display a single frame.

I have tried the same in Xamarin, it works fine. Please find the code snippet below. 

MAUI:

```
<VerticalStackLayout Padding="20">

            <Label Text="Gif" Padding="10"/>
            <Image Source="person_walking.gif" HeightRequest="30" WidthRequest="30"
                   IsAnimationPlaying="True"/>

            <Label Text="PNG" Padding="10"/>
            <Image Source="person_walking.png" HeightRequest="30" WidthRequest="30"/>

        </VerticalStackLayout>
```

Xamarin:

```
<StackLayout>

            <Label Text="Gif" Padding="10"/>
            <Image Source="person_walking.gif" HeightRequest="30" WidthRequest="30"
                   IsAnimationPlaying="True"/>

            <Label Text="PNG" Padding="10"/>
            <Image Source="person_walking.png" HeightRequest="30" WidthRequest="30"/>

    </StackLayout>
```

### Steps to Reproduce

[MAUI_Gif.zip](https://github.com/dotnet/maui/files/8178446/MAUI_Gif.zip)

1. Run above maui sample in any platform
2. See the output, gif image not animating. 

[Xamarin_Gif.zip](https://github.com/dotnet/maui/files/8178449/Xamarin_Gif.zip)

1. Run above Xamarin sample in Windows platform
2. See the output, gif animation working. 

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

net6.0-windows10.0.19041

**Comment by Amir-Care** [comment]
Verified repro with VS Version 17.2.0 Preview 2.0 [32219.17.main]

**Comment by jfversluis** [comment]
The original issue only talked about iOS, updated it to also include other platforms. Just making sure we don't duplicate our issues. Thanks for reporting this!

**Comment by mattleibow** [comment]
I believe this is an unrelated issue where resizetizer is grabbing the gifs and doing things to it.

**Comment by mattleibow** [comment]
It appears to be because resizetizer (image generator) is making copies of the gif and saving as png files.

To work around this for now, you can add this next to the MauiImage items to disable the resizing of gifs:

```xml
<MauiImage Update="Resources\Images\*.gif" Resize="False" />
```
