### ISSUE TITLE
Dependency issue when building / running the base template on MacOs ARM (ios, android and MacCatalyst workloads)

### ISSUE THREAD

**Issue by OliDow** [dotnet/maui#5054]
### Description

I am having issues when running the base Maui project (dotnet new maui).

**Error I am experiencing**
```
dotnet build -t:Run -f net6.0-maccatalyst                                    
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103: Unable to find a stable package Microsoft.Extensions.Configuration with version (>= 6.0.1) [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 2071 version(s) in dotnet6 [ Nearest version: 6.0.2-mauipre.1.21622.4 ] [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 87 version(s) in nuget.org [ Nearest version: 6.0.2-mauipre.1.22054.8 ] [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103: Unable to find a stable package Microsoft.Extensions.Logging.Abstractions with version (>= 6.0.1) [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 2071 version(s) in dotnet6 [ Nearest version: 6.0.2-mauipre.1.21622.4 ] [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 87 version(s) in nuget.org [ Nearest version: 6.0.2-mauipre.1.22054.8 ] [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1101: Unable to find package System.Runtime.InteropServices.NFloat.Internal. No packages exist with this id in source(s): /usr/local/share/dotnet/library-packs, dotnet6, nuget.org [/Users/olidowler/code/pocs/maui/pocs.sln]
```

**Steps completed**
I have DotNet version 6.0.200 installed (But I have tried with 6.0.201 and the latest 6.0.300 build)
I have successfully installed  without error.
dotnet workload install maui
dotnet workload install maui-ios
dotnet workload install maui-android
dotnet workload install maui-maccatalyst

I have installed latest Android Studio and created a simulator
I have installed latest xcode and created a simulator

dotnet new maui
dotnet build -t:Run -f net6.0-maccatalyst    

Nuget feed - I have attempted adding the maui and the dotnet 6 feed from (https://github.com/dotnet/maui/wiki/macOS-Install) but this has not helped in resolving the packages.

**Fix so far**
I can't see any of the dependencies versions on the Nuget feed (I am not too sure where to browse the dotnet6 or maui repositories), I am able to set an explicit version for Extensions.Configuration and Logging.Abstractions in csproj which hushes these errors. 

However System.Runtime.InteropServices.NFloat.Internal cannot be found anywhere, given the name I assume this is part of dotnet or maui internals so I am not sure what to do about this, I am assuming I shouldn't have to do anything.

Attached a copy of my dotnet folder tree
[dotnet-tree.txt](https://github.com/dotnet/maui/files/8185152/dotnet-tree.txt)
 

### Steps to Reproduce

Install dotnet-sdk-6.0.200-osx-arm64.pkg
dotnet workload install maui
dotnet new maui -n "MauiTest"
cd MauiTest
dotnet build -t:Run -f net6.0-maccatalyst    

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS

### Affected platform versions

dotnet 6.0.200 / 6.0.201 / 6.0.300, v3 and maui NugetFeed

### Relevant log output

```shell
Determining projects to restore...
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103: Unable to find a stable package Microsoft.Extensions.Configuration with version (>= 6.0.1) [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 2071 version(s) in dotnet6 [ Nearest version: 6.0.2-mauipre.1.21622.4 ] [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 87 version(s) in nuget.org [ Nearest version: 6.0.2-mauipre.1.22054.8 ] [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103: Unable to find a stable package Microsoft.Extensions.Logging.Abstractions with version (>= 6.0.1) [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 2071 version(s) in dotnet6 [ Nearest version: 6.0.2-mauipre.1.21622.4 ] [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 87 version(s) in nuget.org [ Nearest version: 6.0.2-mauipre.1.22054.8 ] [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1103:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs [/Users/olidowler/code/pocs/maui/pocs.sln]
/Users/olidowler/code/pocs/maui/pocs.csproj : error NU1101: Unable to find package System.Runtime.InteropServices.NFloat.Internal. No packages exist with this id in source(s): /usr/local/share/dotnet/library-packs, dotnet6, nuget.org [/Users/olidowler/code/pocs/maui/pocs.sln]
```

**Comment by jfversluis** [comment]
Could you try the ones that have `dev.azure.com` from [here](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md#net-maui-workload)?

How did you install the workload and do you know which version you have installed? If you use the preview 13 command that should work without any issues at this time. Seems you somehow got a newer version and not everything has been published to public feeds yet

**Comment by OliDow** [comment]
Great thanks @jfversluis, that seems to have sorted it. 
I wasn't aware of that page, nice and  bookmarked now!

I was following https://github.com/dotnet/maui/wiki/macOS-Install to encounter this issue.  If only I had swapped preview.12.json for preview.13.json

Thanks again.
