### ISSUE TITLE
Application.UserAppTheme is no longer consulted when applying AppThemeBindings

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#5066]
The following PR changed it so the `UserAppTheme` is no longer consulted when retrieving the `RequestedAppTheme` 

https://github.com/dotnet/maui/pull/4964/files#diff-e95ac81676df57c3de0226dc120b0e527fbd52bc7fc506ddfde7cccf34a8f489R184 

Modifying the `RequestedAppTheme` based on the `UserAppTheme` feels a bit off. When we fix this issue, it feels like `RequestedAppTheme` should just remain set to whatever the `OS` Theme is and then if the user sets `UserAppTheme` the internals will consult that vs the `RequestedAppTheme`

Maybe we can add an internal `CalculatedAppTheme` that everything is based on?

**Comment by mattleibow** [comment]
Thanks for creating this issue. I did some bad code and there were no tests to help me. 😭 Now there are some shiny new tests to catch a few more combinations!
