### ISSUE TITLE
Remove hard tabs from templates

### ISSUE THREAD

**Issue by adegeo** [dotnet/maui#5068]
### Description

I created a new .NET MAUI project with Version 17.2.0 Preview 1. I noticed that the _MainPage.cs.xaml_ file uses hard tabs instead of spaces. The default should be just like all other templates, spaces.

I checked all the other code files in the template, it seems that this affects all of them.

This may be a problem with other templates; I didn't create a project based on any other template.

### Steps to Reproduce

1. Create a project.
2. Open  _MainPage.cs.xaml_ in a text editor that displays hard tabs.

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Not platform specific

### Did you find any workaround?

Find/replace the hard tab with four spaces in every file.

**Comment by PureWeen** [comment]
@adegeo why? what's the motivation to switch to spaces?

https://dev.to/alexandersandberg/why-we-should-default-to-tabs-instead-of-spaces-for-an-accessible-first-environment-101f

**Comment by adegeo** [comment]
@PureWeen Everything else in Visual Studio uses spaces and not tabs, as soon as you add a new file via any other template you now have some files in one format and some in another.

**Comment by hartez** [comment]
> Everything else in Visual Studio uses spaces and not tabs

Oh, so this should have been filed as a bug against VS, then :)

**Comment by Redth** [comment]
No plans to switch to spaces.

**Comment by adegeo** [comment]
@Redth Question, do the Xamarin/Forms templates use tabs or spaces? I added some to my MAUI project by accident (didn't realize there aren't any VS file templates for MAUI yet) and saw they're using spaces.

What will be the migration story for anyone migrating an app? Do a find replace four spaces `    ` with a tab character? I'm not sure what we would suggest they do since they could have four spaces in text somewhere.
