### ISSUE TITLE
Unable to use ONNX: Reference to type 'ReadOnlySpan<>' claims it is defined in 'mscorlib', but it could not be found

### ISSUE THREAD

**Issue by jdluzen** [dotnet/maui#5078]
### Description

I am unable to use `Microsoft.ML.OnnxRuntime.Managed` with MAUI, it works on a regular `net6.0` library, and latest Xamarin Forms.
Error: `Reference to type 'ReadOnlySpan<>' claims it is defined in 'mscorlib', but it could not be found`

### Steps to Reproduce

1. Create a new MAUI project, Android is what I tested on
2. Add Nuget reference to `Microsoft.ML.OnnxRuntime.Managed` and `Microsoft.ML.OnnxRuntime`
3. Add workaround for a different ONNX bug: https://github.com/dotnet/maui/issues/3867#issuecomment-1052879415
4. Add this code somewhere: `new DenseTensor<float>(4);`

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
@jdluzen Could you share your project?

**Comment by jdluzen** [comment]
[MauiAppOnnxTest.zip](https://github.com/dotnet/maui/files/8275778/MauiAppOnnxTest.zip)

**Comment by XamlTest** [comment]
Verified on Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main]. Repro with above project(MauiAppOnnxxTest).

**Comment by Redth** [comment]
Seems as though something might not be compiled properly against net6.0-android, although in theory MonoAndroid should still be compatible.  It would be worth making this issue on the ONNX project.

**Comment by mycall** [comment]
Will this be resolved before VS 17.3.0 is released?

**Comment by akoeplinger** [comment]
Can you please try with the latest Microsoft.ML.OnnxRuntime.Managed package, it looks like it was updated to support .NET 6.

**Comment by jfversluis** [comment]
No response from the author and seems that this is on the plugin side. Please let us know if something still isn't right in this area. Thanks!
