### ISSUE TITLE
[WinUI] Default ZIndex issue in a multi column grid

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#5083]
### Description

Given a multi column grid with views added in a specific order, columns on the left obey the default ZIndex (that being as new views are added, they are on top of views already added). 
However, columns to the right don't appear to obey this, views added first appear on top of views added last.

### Steps to Reproduce

New Maui app, add a grid with 7 columns.
Add a BoxView in the first column, then add a label to the same column.
Add a BoxView in the last column, then add a label to the same column.
Run it
Label is visible in the first column, not in the last.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows, don't know which

### Did you find any workaround?

Set ZIndex of the label in the last column to 100 forces it to display correctly.

**Comment by Amir-Care** [comment]
Verified not  repro with VS Version 17.2.0 Preview 2.0 [32219.17.main] on Windows .

- Sample project: 
       [#5083.zip](https://github.com/dotnet/maui/files/8194244/5083.zip)

- Screenshots:

     ![image](https://user-images.githubusercontent.com/99456025/156956030-4daca659-cd8e-4518-a584-436dd5b99dac.png)

**Comment by JohnHDev** [comment]
confirmed resolved in VS Version 17.2.0 Preview 2.0.
