### ISSUE TITLE
InputTransparent doesn't work

### ISSUE THREAD

**Issue by SuryaChinnadurai** [dotnet/maui#5089]
### Description

The button click event was triggered When I set the InputTransparent as true in the button control. 

### Steps to Reproduce

1. Create a new Maui Application
2. Add Button control and set InputTransparent  as true 
3. Add click event for button.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 9 and up, iOS 14.2 and up, Windows SDK 10.0.19041.0 and up. 

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by PineYi** [comment]
Verified Repro with Android 11. Repro Project is available:
[#5089.zip](https://github.com/dotnet/maui/files/8196201/5089.zip)
