### ISSUE TITLE
The views overlap and ScrollView Scroll does not work when FlexLayout is child

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5091]
### Description

When Setting FlexLayout as the Child of ScrollView the Content Does not scroll and the child views of the FlexLayout overlaps. On iOS the content of the page does not expand beyond the bounds of the device.
[MauiBugSample.zip](https://github.com/dotnet/maui/files/8197048/MauiBugSample.zip)
 

### Steps to Reproduce

Run the repro project and see the child views of the FlexLayout ovelapping. Try to scroll

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

### Did you find any workaround?

Use HorizontalStackLayout, VerticalStackLayout or StackLayout.

**Comment by PineYi** [comment]
Reproduce in Android 11 with above project.

**Comment by samhouts** [comment]
The ScrollView issue is no longer reproducible on 6.0.300-rc.4.5704. The views do not overlap on iOS, and the content page is scrollable, so iOS doesn't seem to be an issue. However, on Android, the views are not laid out properly, and they are definitely overlapping on the second Grid.

**Comment by VincentBu** [comment]
repro with vs main build(32507.29.main) on Android emulator.
![image](https://user-images.githubusercontent.com/44959937/167358908-608f5b45-21a0-4288-b573-3dce4d2c35b4.png)

**Comment by hartez** [comment]
The overlap is a weird interaction between the Grid's last Row (with height "*") and the FlexLayout measurement. If you change the last row in each Grid to "Auto", things lay out as expected. 

So if you need a workaround until we get this fixed, that might help.

**Comment by hartez** [comment]
Fixed by #13216
