### ISSUE TITLE
Entry and Editor TextTransformation is not working

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5095]
### Description

The TextTransformation of both LowerCase and UpperCase is not working on Entry and Editor.
[BugSample.zip](https://github.com/dotnet/maui/files/8197422/BugSample.zip)
 

### Steps to Reproduce

In the above repro sample try TextTransformation on Entry and Editor with UpperCase and LowerCase.  

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11 and iOS 15

**Comment by shimingsg** [comment]
verified not repro with VS 17.2.0 Preview 3.0 [32307.380.main] on Android
![image](https://user-images.githubusercontent.com/20982341/157169135-65f7cd46-0266-4647-b3b2-474c1fe9bb7c.png)

**Comment by Redth** [comment]
Fixed in an upcoming release in #4554
