### ISSUE TITLE
[Bug] Stop Stealing KDE MAUI's name

### ISSUE THREAD

**Issue by Joshua-Ashton** [dotnet/maui#51]
Title.

**Comment by rmarinho** [comment]
duplicated issue, is the same as #35

**Comment by Joshua-Ashton** [comment]
Which is closed. The issue is still not fixed.

If you guys ❤ Linux so much, fix it.

**Comment by liketechnik** [comment]
From your code of conduct:

> * Giving and gracefully accepting constructive feedback
> * Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience
> * Focusing on what is best not just for us as individuals, but for the overall community

I couldn't observe any of this so far.

**Comment by adojck** [comment]
Why is this closed if there is no solution to the problem?

**Comment by legistek** [comment]
A better issue would be `[Bug] Stop Whining About KDE's MAUI Name`

**Comment by liketechnik** [comment]
Just to have this clear: Can the actions regarding this issue (in #34, #35, #51, #58) be taken as the official position of Microsoft? If not, what is the official position of Microsoft?

**Comment by Happypig375** [comment]
Congratulations, this has become news: https://www.phoronix.com/scan.php?page=news_item&px=Microsoft-KDE-MAUI

**Comment by ChaseFlorell** [comment]
If you want a constructive conversation, please review https://github.com/dotnet/maui/issues/41

Above all else, be kind.

**Comment by andrewBezerra** [comment]
In 
     https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/ 
is written:

    "that: .NET Multi-platform App UI, affectionately call .NET MAUI."

**Note:**
    affectionatelly call...
and not:
    also call

For me, MAUI is not the real name of "product".
