### ISSUE TITLE
Opacity has no effect on Frame

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#5100]
### Description

Opacity does not affect Frame element, it's still not transparent.

### Steps to Reproduce

1. Run the app with the following page:
```xaml
    <ContentPage>
        <Grid>
            <StackLayout x:Name="stack">
                <Label Text="Hello world!"/>
                <Label Text="Hello world!"/>
                <Label Text="Hello world!"/>
                <Label Text="Hello world!"/>
                <Label Text="Hello world!"/>
                <Label Text="Hello world!"/>
                <Label Text="Hello world!"/>
                <Label Text="Hello world!"/>
            </StackLayout>

            <Frame BackgroundColor="Black" 
                   Opacity="30"
                   WidthRequest="100" 
                   HeightRequest="100" 
                   CornerRadius="10"/>
        </Grid>
    </ContentPage>
```

ER:
Frame should be transparent.

AR: 
Frame is not transparent.
![image](https://user-images.githubusercontent.com/17177729/157092423-df08025b-03ad-4e11-a8e9-89bc7c3d59cb.png)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by shimingsg** [comment]
verified it works if set the value of Opacity to "0.5" with VS 17.2.0 Preview 3.0 [32307.380.main] on Android
![image](https://user-images.githubusercontent.com/20982341/157170125-8af05edc-b20d-45f4-b905-a47ce890c5e0.png)

**Comment by Dreamescaper** [comment]
@shimingsg 
Great to know! Waiting for the release then!

**Comment by SarthakGz** [comment]
@Dreamescaper opacity value range is 0 to 1 you were giving 30 so there was no issue in the first place

**Comment by Dreamescaper** [comment]
@SarthakGz 
I have provided a bad example, but Opacity has still no effect to me even with valid values. I've tried 0.5 and 0.3 values. It works perfectly fine on other controls, e.g. BoxView.
