### ISSUE TITLE
Build not working in MAUI Version 17.2.0 Preview 3.0 [32307.209.main]

### ISSUE THREAD

**Issue by tanpuresiddhant** [dotnet/maui#5108]
### Description
After build getting these errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1103	Unable to find a stable package Microsoft.Extensions.Configuration with version (>= 6.0.1)
  - Found 87 version(s) in nuget.org [ Nearest version: 6.0.2-mauipre.1.22054.8 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Program Files\dotnet\library-packs	MauiApp10	C:\Users\sitanpur\source\repos\MauiApp10\MauiApp10\MauiApp10.csproj	1	
Error	NU1103	Unable to find a stable package Microsoft.Extensions.Logging.Abstractions with version (>= 6.0.1)
  - Found 87 version(s) in nuget.org [ Nearest version: 6.0.2-mauipre.1.22054.8 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Program Files\dotnet\library-packs	MauiApp10	C:\Users\sitanpur\source\repos\MauiApp10\MauiApp10\MauiApp10.csproj	1	
Error	NU1101	Unable to find package System.Runtime.InteropServices.NFloat.Internal. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, nuget.org	MauiApp10	C:\Users\sitanpur\source\repos\MauiApp10\MauiApp10\MauiApp10.csproj	1	

### Steps to Reproduce

Steps to reproduce:
1. Create a new .net Maui project Version 17.2.0 Preview 3.0 [32307.209.main]
2. Try to build the project 
3. You will start getting errors

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

Windows

### Affected platform versions

17.2.0 Preview 3.0 [32307.209.main]

**Comment by drasticactions** [comment]
We're having issues building against MAUI Main and P14 because of missing `Microsoft.Extensions.Configuration` and ` Microsoft.Extensions.Logging.Abstractions`. We know we can add the missing nuget feeds for it, but this is for CI testing against what's in the workload.

Since those packages are missing, we can't run the tests against MAUI without hacking our CI, which we don't want to do.

**Comment by Amir-Care** [comment]
Verified repro with Version 17.2.0 Preview 3.0 [32307.380.main]

**Comment by jfversluis** [comment]
I think this should be fixed now that we have versions released in the open. If there is still something that is not working for you, please let us know in a new issue with all the updated details. Thanks!
