### ISSUE TITLE
[iOS]HorizontalLayoutOptions=Center but the editor still is displayed on start

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5116]
### Description

- Setting HorizontalOptions=Center,  it still remains on the start. 

### Steps to Reproduce

Test the above scenarios on the repro Project.
 
[EditorBugSample.zip](https://github.com/dotnet/maui/files/8204647/EditorBugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS,

### Affected platform versions

iOS 15 

### Did you find any workaround?

No.

**Comment by HobDev** [comment]
There are multiple bugs in the Editor. Is it ok to report all the bugs related to editor on single issue. If each bug should needs to be in  it's own issue than i will split report to multiple issues.

**Comment by XamlTest** [comment]
@HobDev Please split the bug, one issue report one bug. For the same bug reproduce on multi platform, you can report in the same issue.

**Comment by HobDev** [comment]
@XamlTest  Splitting done

**Comment by kristinx0211** [comment]
verified repro on IOS 15.2. repro sample:
[MauiApp5.zip](https://github.com/dotnet/maui/files/8241932/MauiApp5.zip)

**Comment by davidortinau** [comment]
Repro'ing I see a different issue now. The centering works, however the size needed by the children of the VerticalStackLayout is not respected. 

Without the layout options the layout and editor will fill horizontally.

```
<VerticalStackLayout BackgroundColor="Green"
        HorizontalOptions="Center"
        VerticalOptions="Center">
        <Editor Placeholder="Text here" />
   </VerticalStackLayout>
```

This results in what appears to be a blank view, but if you look closely it's centered and just super tiny.
![Simulator Screen Shot - iPhone 13 Pro - 2022-04-29 at 09 11 33](https://user-images.githubusercontent.com/41873/165961851-50721d09-b4de-4eac-862b-2b718d7ef562.png)

Just horizontal (verified same on catalyst):
![Simulator Screen Shot - iPhone 13 Pro - 2022-04-29 at 09 09 56](https://user-images.githubusercontent.com/41873/165961894-628530d5-415c-473b-8096-307df667587b.png)

Providing a width request of 300 to the Editor results in:
![Simulator Screen Shot - iPhone 13 Pro - 2022-04-29 at 09 15 30](https://user-images.githubusercontent.com/41873/165962261-44a98e85-0153-4bd9-bfbc-605c72e48440.png)
