### ISSUE TITLE
CollectionView SelectedItem not highlighted on Android until scroll

### ISSUE THREAD

**Issue by matt-goldman** [dotnet/maui#5117]
### Description

When selecting an item in a CollectionView, the item is not highlighted and there is no visual indication that an item has been selected. If the collection is long enough and you scroll the selected item off screen, when you scroll back it is in fact highlighted.

Issue occurs on Android but not Windows. macOS and iOS not yet tested (I will updated with a comment once I've tested on them).

A repository with a sample reproducing this error is available here: https://github.com/matt-goldman/CollectionViewIssue

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Add a CollectionView
3. Bind the CollectionView ItemsSource property to an ObservableCollection
4. Populate the ObservableCollection
5. Run the app and select an item
6. Observe that the item does not become highlighted
7. Scroll through the collection to move the selected item off-screen
8. Scroll in the other direction to bring the item back
9. Note that the item is highlighted

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested with Android API 28

**Comment by XamlTest** [comment]
Verified Repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32219.17.main]. Repro Project: https://github.com/matt-goldman/CollectionViewIssue

**Comment by VincentBu** [comment]
It works on Android emulator with vs main build(32507.29.main).
![image](https://user-images.githubusercontent.com/44959937/167362690-7e84f949-7408-44b0-8292-125e41d925cd.png)
