### ISSUE TITLE
[Android]VerticalStackLayout HorizontalOptions= Center is not working on Android

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5119]
### Description

When the HorizontalOptions=Center is set on VerticalStackLayout the child views also get centered on iOS but not on Android. On Android they still fill the space Horizontally. 

### Steps to Reproduce

Run the repro project on both iOS and Android. 
[MauiBugSample.zip](https://github.com/dotnet/maui/files/8203417/MauiBugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

**Comment by Redth** [comment]
Seems related to `BoxView` ... if I swap it with a `Border` instead it works as expected.

@PureWeen  FYI another one of these BoxView/Frame isn't quite doing the right thing... 

As such, I'm moving this out since there's a plausible workaround.

**Comment by rachelkang** [comment]
@Redth it's related to `ShapeView` more generally - @hartez's draft PR linked to this issue fixes it, but is a work-in-progress

**Comment by Redth** [comment]
In #6206 there's a link to #5817 that was already merged and perhaps is what 'fixed' this when using a Border, though the problem does persist with BoxView, but I think that's of lesser concern for GA right now.

**Comment by rachelkang** [comment]
Unfortunately, #5817 did not fix this issue :( but yes that makes sense
