### ISSUE TITLE
[iOS]Keyboard covers the editor

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5121]
### Description

 Keyboard covers the editor. The editor does not scroll above the keyboard when in focus.

### Steps to Reproduce

Run the sample project on iOS
[EditorBugSample.zip](https://github.com/dotnet/maui/files/8204770/EditorBugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by jsuarezruiz** [comment]
Similar to https://github.com/dotnet/maui/issues/5121

**Comment by HobDev** [comment]
The link is referring the same issue.

**Comment by Redth** [comment]
This is fixed in Preview 14, please file a new issue if you are finding problems with it in the latest preview.
