### ISSUE TITLE
  UnFocus Event of Editor does not fire when changing the focus to another view

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5124]
### Description

  UnFocus Event of Editor does not fire when changing the focus to another view. 

### Steps to Reproduce

Run the repro project. Unfocus editors by clicking on both editor's one by one. Both editors has subscribed to the Unfocused event. But still the unfocused event does not fire.

[EditorBugSample.zip](https://github.com/dotnet/maui/files/8205504/EditorBugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

**Comment by HobDev** [comment]
@jsuarezruiz The issue is with editor. But `control-entry` label is added

**Comment by jsuarezruiz** [comment]
Yeah, sorry for the confusion. I know, the label is used for different controls: Editor, Entry and SearchBar.

**Comment by PineYi** [comment]
Reproduce in Android 11 with above project.
