### ISSUE TITLE
The focus event does not fire on Editor

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5126]
### Description

The focus event does not fire on Editor. 

### Steps to Reproduce

Run the repro project. Focus editors by clicking on both editor's one by one. Both editors has subscribed to the Focused event. But still the Focused event does not fire.
[EditorBugSample.zip](https://github.com/dotnet/maui/files/8205587/EditorBugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

### Did you find any workaround?

No.

**Comment by HobDev** [comment]
@jsuarezruiz The issue is with editor. But control-entry label is added

**Comment by jsuarezruiz** [comment]
Yeah, sorry for the confusion. I know, the label is used for different controls: Editor, Entry and SearchBar.

**Comment by PineYi** [comment]
Reproduce in Android 11 with above project.
