### ISSUE TITLE
Completed event does not fire on Return key on Editor

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5130]
### Description

The return key Changes line on editor but does not complete the the text input.  The completed event is fired when the editor loose focus. 

### Steps to Reproduce

Debug the repro project and put breakPoint on the completed event of both the editors
[EditorBugSample.zip](https://github.com/dotnet/maui/files/8205688/EditorBugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

**Comment by HobDev** [comment]
@jsuarezruiz The issue is with editor. But control-entry label is added

**Comment by jsuarezruiz** [comment]
Yeah, sorry for the confusion. I know, the label is used for different controls: Editor, Entry and SearchBar.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 2.0. Repro on Android and iOS platform with sample project.

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/9796
