### ISSUE TITLE
[iOS]The location is null when  Geolocation.GetLocationAsync(); is called

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5132]
### Description

The location is returned null when  Geolocation.GetLocationAsync(); is called on iOS. 

### Steps to Reproduce

Debug the repro project. 
[EditorBugSample.zip](https://github.com/dotnet/maui/files/8206333/EditorBugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No workaround for the issue. But the Location coordinates for any city can be found online if required .

**Comment by jfversluis** [comment]
This is expected, from the [Docs page](https://docs.microsoft.com/xamarin/essentials/geolocation#using-geolocation):

> You can get the last known [location](https://docs.microsoft.com/dotnet/api/xamarin.essentials.location) of the device by calling the GetLastKnownLocationAsync method. This is often faster then doing a full query, but can be less accurate and may return null if no cached location exists.

**Comment by HobDev** [comment]
@jfversluis  Sorry for the mistake. The below code is returning null:
`var position = await Geolocation.GetLastKnownLocationAsync();

                if (position == null)
                {
                    // get full location if not cached.
                    position = await Geolocation.GetLocationAsync(new GeolocationRequest
                    {
                        DesiredAccuracy = GeolocationAccuracy.Medium,
                        Timeout = TimeSpan.FromSeconds(30),
                    });
                }`

The error is reproductible from the repro project uploaded above with the issue

**Comment by HobDev** [comment]
Changed the title accordingly

**Comment by jfversluis** [comment]
Are you running this on the Simulator? I copied your code snippet to a project and at first I did see the null because it timed out. Then I set a mock location through Features > Location and it works as it should. I think this works as expected at this point. This also because not much code actually changed for Essentials at all.
