### ISSUE TITLE
BlazorWebView inside Android can't be reloaded

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#5136]
### Description

On other platforms, it's perfectly valid for the Blazor Hybrid application to reload, e.g. because of:

 * The developer explicitly triggering a reload
 * Or, some auth flow causing a reload
 * Or, the yellow error bar's "Reload" link being clicked

... and the application should come back to life and continue working. However, on Android, the page fails to reload.

### Steps to Reproduce

1. Create a Blazor Hybrid application
2. In one of your pages, add `<a href="javascript:location.reload()">Reload</a>`
   * This needs to be a non-root page. For example, the page at `/counter`, and *not* the homepage at `/`.
4. Run it in the Android Emulator
5. Click the reload link you just added

Expected: page should reload
Actual:

![image](https://user-images.githubusercontent.com/1101362/157283622-e23e3828-e90f-4574-ac8b-6340d4e59666.png)

(In place of "navigation", you will see the URL of your page, e.g., "counter")

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30, probably others too

**Comment by javiercn** [comment]
According to Steve, it's likely missing the "fallback" routing behavior

**Comment by Amir-Care** [comment]
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main] on Android.
Sample project: [#5136.zip](https://github.com/dotnet/maui/files/8212164/5136.zip)
![image](https://user-images.githubusercontent.com/99456025/157383394-6e58ed15-bc10-4464-b4f2-ceb1b9f6ec3d.png)

**Comment by danroth27** [comment]
@mkArtakMSFT Milestone?

**Comment by TanayParikh** [comment]
Re-opening as CTI confirms the issue is still present, however, it seems like this may just be blocked on https://github.com/dotnet/maui/issues/4502 getting consumed in MAUI. This should happen on this coming Tuesday.

**Comment by MackinnonBuck** [comment]
CTI reported this as fixed
