### ISSUE TITLE
Linked label clearing on update

### ISSUE THREAD

**Issue by Bruno-Marian** [dotnet/maui#5140]
### Description

Using the Mvvm project when placing the link in the label and performing the page update, the information is blank. Bug for happening on windows.

### Steps to Reproduce

Add a 'Label' like so:'<Label Text="{Binding CounterLabel}'/>
Add a button with command to add

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by shimingsg** [comment]
@Bruno-Marian , thank for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots that we can reproduce your issue? That should greatly speed up the process, thanks!
