### ISSUE TITLE
Enable indicator view to be usable with collectionView, and bindableLayout(scrollView)

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5156]
### Description

Indicator view is generally used in UI design  with Horizontal Scrolled Collections . It works well with CarouselView. But CarouselView have a limitation of displaying single item on screen. This is not always how the Apps are designed. Sometimes the App is required to show two or more items at a time.  In such scenario the CollectionView and BindableLayout(within in scrollView) are used. But currently the indicator view is not usable with these Layouts. 

### Public API Changes

Access to Position Property of Indicator view thus enabling the developer to change position according to the scroll on CollectionView & ScrollView and vice versa. 

```
IndicatorView indicatorView=new IndicatorView;
IndicatorView.PositionChanged+=OnIndicatorViewPositionChanged();

ScrollView scrollView = new ScrollView();
scrollView.Scrolled += OnScrollViewScrolled;

void OnScrollViewScrolled(object sender, ScrolledEventArgs e)
{
  indicatorView.Position=e.ScrollX;
}

void OnIndicatorViewPositionChanged(object sender, IndicatorEventArgs e)
{
//Scroll to the item index of Position on ScrollView 
  scrollView.ScrollToAsync(indicatorView.Position);
}
```

### Intended Use-Case

Indicator view is generally used in UI design  with Horizontal Scrolled Collections . It works well with CarouselView. But CarouselView have a limitation of displaying single item on screen. Sometimes the App is required to show two or more items at a time.

**Comment by rmarinho** [comment]
Hi @HobDev we don't have `PositionChanged` event but you can subscribe for PropertyChange and check if it's the Position property changing.
