### ISSUE TITLE
FontImageSource displays small box instead of requested  font icon

### ISSUE THREAD

**Issue by IndianaGary** [dotnet/maui#5157]
### Description

![ShellPage](https://user-images.githubusercontent.com/13239292/157382245-3d7b1719-9f85-4909-b528-8c9bddba3cb1.png)

Note the small boxes in the tab bar inst4ead of font images.  Note : this is a Windows-Only Desktop app.

### Steps to Reproduce

1. Create a new Maui Shell application.
2. Register Font Icons in MauiProgram.
![RegisterFonts](https://user-images.githubusercontent.com/13239292/157382833-5c3e133d-eb3f-4c36-b31f-b95e84bc29a6.png)
3. Add FontImageSource items in App.XAML.
![AppXAML](https://user-images.githubusercontent.com/13239292/157382894-19529306-3b16-4324-b589-778f0f58ce10.png)
4. Add a TabBar to the Shell Page.
5. Add Tabs with Icons to the Shell Page.
![ShellPageXAML](https://user-images.githubusercontent.com/13239292/157382958-31e02a99-ca75-49e8-ad4b-48c07e59ec40.png)

Run the application and note that the icons are replaced by small rectangles. Note: I have used Font Images in other places in Maui and this problem does not arise. I've also used then on Android and this issue does not arise.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041

### Did you find any workaround?

No...

**Comment by jfversluis** [comment]
Possibly related in Xamarin.Forms: https://github.com/xamarin/Xamarin.Forms/issues/14959

**Comment by jfversluis** [comment]
If you can, it would be super helpful if you could add the project, or at least the relevant bits in a GitHub repo and link that here, thanks!

**Comment by PureWeen** [comment]
@Redth Font fixes will come along for the ride on this PR
https://github.com/dotnet/maui/pull/5667

If you set the `Color` on the FontImageSource to anything then the icons should start showing up. So, in my PR I just set them to `White` by default unless specified otherwise

**Comment by Redth** [comment]
![image](https://user-images.githubusercontent.com/271950/161588804-9bd46583-388a-4859-909c-9a092783b0be.png)

LGTM in main (so fix will be available in RC1).

**Comment by Nk54** [comment]
Hello,

It doesn't work yet on RC1.

![image](https://user-images.githubusercontent.com/13755220/163678664-965b337f-96aa-4aed-9416-0eeb3710cd9d.png)
