### ISSUE TITLE
[iOS] Slider's MaximumValue does not change after initial assignment

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5160]
### Description

Once the initial MaximumValue of Slider is set it does not change on iOS. 

### Steps to Reproduce

Run the repro project and wait for 5 seconds. Now the Slider will completely slide in one go because the MaximumValue  is still 1 even when the new Value of 100 is assigned.
[MauiBugSample.zip](https://github.com/dotnet/maui/files/8212452/MauiBugSample.zip)
 

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by kristinx0211** [comment]
verified repro on iPhone13 IOS 15.2 with vs 17.2.0 Preview 2.0 [32301.586.main].
sample: [MauiApp4.zip](https://github.com/dotnet/maui/files/8241544/MauiApp4.zip)

**Comment by samhouts** [comment]
Still an issue on main
