### ISSUE TITLE
Shell Tab Icon color is always gray

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5164]
### Description

No matter what is the color of the icon the tab bar always display it in gray

### Steps to Reproduce

Run the repro project and see the tab_icon display in gray color.  The color of tab_icon is Blue
[MauiBugSample.zip](https://github.com/dotnet/maui/files/8214256/MauiBugSample.zip)
.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jfversluis** [comment]
Looking at your code it seems like you're expecting it to pick up on the styles in the `App.xaml`? If so, they are not complete.

If I add 

```xml
Shell.TitleColor="Blue"
Shell.TabBarTitleColor="Red"
Shell.TabBarUnselectedColor="Yellow"
```

Either in a style in the `App.xaml` or directly on the `Shell` node in the `AppShell.xaml` it works correctly

![image](https://user-images.githubusercontent.com/939291/157443990-493bb872-e2a3-4e58-96e9-407b8d36c466.png)

**Comment by HobDev** [comment]
@jfversluis  Thank you for the correction.
