### ISSUE TITLE
Grid Rows overlap

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5165]
### Description

Grid Rows overlap if the Image height is larger than the row height. Whereas the Image should squeeze in the given row height. 

### Steps to Reproduce

Run the repro project
[MauiBugSample.zip](https://github.com/dotnet/maui/files/8214678/MauiBugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Andoid 11

### Did you find any workaround?

Set Row height to the Image height or Auto.

**Comment by Amir-Care** [comment]
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main] on Android
