### ISSUE TITLE
Default MAUI App takes 14 seconds to open on iOS.

### ISSUE THREAD

**Issue by aokocax** [dotnet/maui#5183]
### Description

This is not a bug, but there is such a big problem, what can I do to speed up the application startup?
Regardless of debug and release mode, the app takes 14 seconds to open on my iPhone 7 Plus. Android time is much faster but iOS unfortunately is pretty bad. Is there anything that can be done to speed it up? 

https://user-images.githubusercontent.com/1059475/157531982-eeb8eacb-3645-4218-823d-43895f7b17b3.MP4

### Steps to Reproduce

1. Create Maui APP
2. Deploy for iOS
3. Open the app on the iPhone

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by jfversluis** [comment]
Performance is one of the big focus points of .NET MAUI. There can be many things influencing this ranging from your build configuration to the iPhone 7 being a 6 year old device by now and maybe not the fastest anymore. We're working to making it better nonetheless, so stay tuned!

**Comment by aokocax** [comment]
There seems to be something weird. No special build configuration it is default maui app. On the same phone, the old Xamarin Forms application opens only in 2 seconds.  On a 7 year old android phone, the same app opens in half the time.

https://user-images.githubusercontent.com/1059475/157651117-a80a4fe0-153b-4e81-aa28-e3d9c2b05213.MP4

**Comment by aokocax** [comment]
For those who will have similar problems and find this issue, I did what Gerald told here https://github.com/dotnet/maui/issues/4397 and sent it to testflight on mac. The app opened in under 1 second.
