### ISSUE TITLE
The Shell.TitleView is not visible on Android and does not fill Navigation Bar on iOS

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5194]
### Description

The Shell.TitleView is not visible on Android. On iOS it is visible but does not fill the entire NavigationBar. 

### Steps to Reproduce

Run the repro project. Navigate to second Page where the TitleView is set. 
[BugSample.zip](https://github.com/dotnet/maui/files/8223926/BugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

### Did you find any workaround?

SetNavBarIsVisible="False" and create your own View.

**Comment by PureWeen** [comment]
Duplicate
https://github.com/dotnet/maui/issues/5063
https://github.com/dotnet/maui/issues/3877
