### ISSUE TITLE
[iOS]BackButtonBehavior IsEnabled="False" does not Disable the back button on iOS 

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5195]
### Description

BackButtonBehavior IsEnabled="False" does not Disable the back button on iOS 

### Steps to Reproduce

Run the repro project. Navigate to second page. Now click on Back Button. It is set to IsEnabled="False". But it still is enabled on iOS. 

[BugSample.zip](https://github.com/dotnet/maui/files/8224008/BugSample.zip)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

```shell
set  Shell.NavBarIsVisible="False"and replace Navigationbar with custom View.
```

**Comment by kristinx0211** [comment]
repro on iPhone 13 IOS 15.2 with the above project.

**Comment by samhouts** [comment]
Still reproduces on int preview.

**Comment by XamlTest** [comment]
Verified this issue on Visual Studio Enterprise 17.6.0 Preview 3.0. Repro on iOS 16.4 emulator with below Project:
[5196.zip](https://github.com/dotnet/maui/files/11229321/5196.zip)

**Comment by acaliaro** [comment]
@samhouts any news on this?
