### ISSUE TITLE
Blazor Hybrid | Mac Catalyst Publish Failure

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#5197]
### Description

I'm unable to publish mac catalyst apps. I get:

```
dotnet publish -f:net6.0-maccatalyst -c:Release
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Detected signing identity:

    Bundle Id: com.companyname.maui_blazor2
    App Id: com.companyname.maui_blazor2
  maui-blazor2 -> /Users/tanay/dev/maui-blazor2/bin/Release/net6.0-maccatalyst/maccatalyst-x64/maui-blazor2.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
productbuild : error : directory "bin/Release/net6.0-maccatalyst/maccatalyst-x64/publish" does not exist for writing "maui-blazor2-1.0.pkg". [/Users/tanay/dev/maui-blazor2/maui-blazor2.csproj]
```

I've verified the directory does in fact exist on disk. I've also tried deleting the `bin/Release/net6.0-maccatalyst` directory to let the publish command create the requisite structure without luck.

### Steps to Reproduce

dotnet new maui-blazor

dotnet publish -f:net6.0-maccatalyst -c:Release

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac Catalyst

**Comment by TanayParikh** [comment]
cc/ @jfversluis. I see instructions for [iOS](https://github.com/dotnet/maui/issues/4397), [Android](https://github.com/dotnet/maui/issues/4377) & [Windows](https://github.com/dotnet/maui/issues/4329). Is publishing Mac Catalyst supported yet?

**Comment by kristinx0211** [comment]
verified repro with the same errors appear on mac.

**Comment by jfversluis** [comment]
> cc/ @jfversluis. I see instructions for [iOS](https://github.com/dotnet/maui/issues/4397), [Android](https://github.com/dotnet/maui/issues/4377) & [Windows](https://github.com/dotnet/maui/issues/4329). Is publishing Mac Catalyst supported yet?

I think it should be, but I didn't get around to verifying/writing it up yet. Let me see if I can prioritize that. I know @praeclarum has attempted it, maybe you have some new insights?

**Comment by jfversluis** [comment]
I have made some progress with this. The command should look more like: `dotnet publish -c Release -f net6.0-maccatalyst "/p:CreatePackage=true" "/p:EnablePackageSigning=true" "/p:EnableCodeSigning=true" "/p:CodeSignEntitlements=" "/p:CodesignKey=Apple Development: Your Account Name (YOURTEAMID)" "/p:CodesignProvision=Your Provisioning Profile Name" "/p:PackageSigningKey=3rd Party Mac Developer Installer: Your Account Name (YOURTEAMID)"

And that's assuming that you have all the right certs and provisioning profiles :) This gets me a pkg that installs, but it doesn't seem to run...

Let me know if this gets you any further :)

**Comment by TanayParikh** [comment]
Thanks @jfversluis! I was adding this for the blazor maui e2e testing scenarios. Do you know if there's any way for us to publish without signing? We want to focus our testing on confirming the published maui assets are working as expected, and I don't believe signing should change the outcome there. Hoping to reduce complexity of the testing scenarios by avoiding signing.

**Comment by jfversluis** [comment]
Interesting. Try `dotnet build -c Release -f net6.0-maccatalyst "/p:CreatePackage=true"` that gives me a .app that works and a .pkg that works. Notice how I do `dotnet build` and not `publish`.

I'll have to write this up and see if we can make it work through publish as well. Can you confirm this works for you?

**Comment by TanayParikh** [comment]
> Can you confirm this works for you?

(for others who may be watching this issue) discussed offline. It works if you delete the `.app` produced and run the installation wizard. There is a _potential_ issue with the installer not working a second time due to an errant installation lock. Waiting on more data points.

**Comment by Redth** [comment]
Let's track this in #5399

**Comment by TanayParikh** [comment]
Going to keep this open specifically to track the Blazor Hybrid Mac Catalyst Publishing story.

**Comment by TanayParikh** [comment]
Current status (with latest MacOS 12.3) is publishing works, but installation can be tricky. We believe deleting bin/obj folders and then running the installer _should_ do the trick. Waiting on confirmation from those facing this issue (should have feedback soon).

**Comment by TanayParikh** [comment]
Okay it's working now 🎉 

- Make sure you're using the latest MacOS (12.3.*)
- Move the `.pkg` to the Desktop and then delete the `bin`/`obj` folders.
