### ISSUE TITLE
MAUI missing net6.0-ios

### ISSUE THREAD

**Issue by WillAutioItrax** [dotnet/maui#5199]
### Description

On opening a new MAUI app I see this error 4 times:
NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios	MauiApp3	C:\Users\wauti\source\repos\MauiApp3\MauiApp3\MauiApp3.csproj	1	

and because it is there, I'll include this error as well:
XLS0413	The property 'BackgroundColor' was not found in type 'ContentPage'.	MauiApp3	C:\Users\wauti\source\repos\MauiApp3\MauiApp3\MainPage.xaml	4	

### Steps to Reproduce

1) Create a new Maui app.
2) wait until it has created every thing
3) see the errors (see above) in the Error List
4) in solution explorer, see that Dependencies has a yellow tag. Click it. Now all 4 entries below have yellow tags as do their Packages. And finally, their contents do too:
a) Microsoft.Maui.Dependencies(6.0.200-prevview.13.2865)
b) Microsoft.Maui.Extensions(6.0.200-prevview.13.2865)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, I was *not* able test on other platforms

### Affected platform versions

VS Version 17.2.0 Preview 1.0

**Comment by v-longmin** [comment]
Verified the issue on Main\32310.304, it's not repro. You can update vs to main latest build to resolve the issue.

**Comment by kzu** [comment]
Exact same issue here, same VS version. First time creating a Maui project.

What does "update vs to main" mean? I can only access whatever is publicly released, so 17.2 Preview 1.0

**Comment by gyretech** [comment]
try `dotnet workload install ios `

**Comment by kzu** [comment]
Nope @gyretech , that's not it. 

The `net6.0-maccatalyst` TF failed too initially, but it did suggest to run `dotnet workload install maccatalyst` to fix it. The ios one is not offering that as a fix, so I'm kinda not surprised that running that command didn't fix it.

**Comment by gyretech** [comment]
I had to run:
`dotnet workload install maccatalyst`
`dotnet workload install ios`
`dotnet workload install android`

**Comment by WillAutioItrax** [comment]
@gyretech 
I ran those three commands in a DOS window, created a new  default app in Maui (the click a button one). It built and ran in Droid.. That works for me - thanks!

**Comment by kzu** [comment]
Yeah, for whatever reason, I didn't have to run `dotnet workload install android`, that part Just Worked™️
