### ISSUE TITLE
[Enhancement] Better support for C# 8.0 nullable reference feature

### ISSUE THREAD

**Issue by h82258652** [dotnet/maui#52]
## Summary
Hello, I'm a WPF and UWP developer. While developing apps, I always don't know if the return value is null and got a ```NullPointerException``` after I run the app. I hope the maui API can use the C# 8.0 nullable reference feature to tell the developers if the return or input value can be null.

## API Changes
It is a compiler feature, I think there are no API changes.

## Intended Use Case
Like this:
```C#
DependencyObject? parent = MyButton.Parent; // The parent maybe null.
ItemCollection? items = MyItemsControl.Items; // Sometimes, the items will be null.
```

**Comment by charlesroddie** [comment]
This depends on https://github.com/xamarin/Xamarin.Forms/pull/9481 and should be done before the .Net 5 release. I.e. in before Nov 2020 and in the XF repo instead of for the late 2021 MAUI release.

> https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/
> propose that there’s a “nullable rollout phase” until .NET 5 ships (November 2020), wherein popular libraries should strive to embrace NRTs.

This will help users avoid bugs and help to fix NRE bugs within the XF repo.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/232
