### ISSUE TITLE
Blur event get invoked when focusing the input element

### ISSUE THREAD

**Issue by Deepak-Ramakrisnan** [dotnet/maui#5201]
### Description

We have rendered the html input element in razor page and binded the 'blur' event at script end . But when focusing the input element the blur event get triggered unnecessarily. 

### Steps to Reproduce

Sample link : [https://drive.google.com/file/d/1RQBGbu8_UhZ3RoCgHIAu_QNquVhbPM8r/view?usp=sharing](Click here to download the sample)

1.Run the attached sample 
2.Just focus the  input element

**Expected** : Blur event should not be triggered
**Actual** : Blur event get triggered (The body color will get changed as we have done it inside blur event of the input)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Blazor-MAUI , Windows machine ,c# 

### Did you find any workaround?

No

**Comment by PineYi** [comment]
Reproduce in Windows with above project.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Does this happen when you have a pure HTML / JavaScript page which doesn't include any Blazor?
If the answer is `yes`, does it happen only on WebView or not?

**Comment by mkArtakMSFT** [comment]
If it is not the default HTML / JS behavior, please share a repro project as a public repo hosted on GitHub for us to investigate.

**Comment by Deepak-Ramakrisnan** [comment]
> Thanks for contacting us. Does this happen when you have a pure HTML / JavaScript page which doesn't include any Blazor? If the answer is `yes`, does it happen only on WebView or not?

Hi @mkArtakMSFT , Thanks for viewing this . Yes I have used a html input tag in razor page and binded the blur event at script end . The same thing working as expected in default blazor server and WASM. I will share the required sample soon .

**Comment by Deepak-Ramakrisnan** [comment]
Hi @mkArtakMSFT ,

Please find the repo link containing sample below for your reference.

https://github.com/Deepak-Ramakrisnan/MAUI-Blazor/tree/master/MauiApp2

Thanks,
Deepak R.

**Comment by Deepak-Ramakrisnan** [comment]
> > Thanks for contacting us. Does this happen when you have a pure HTML / JavaScript page which doesn't include any Blazor? If the answer is `yes`, does it happen only on WebView or not?
> 
> Hi @mkArtakMSFT , Thanks for viewing this . Yes I have used a html input tag in razor page and binded the blur event at script end . The same thing working as expected in default blazor server and WASM. I will share the required sample soon .

Now I'm facing the same issue even for native Blazor InputText component with @onblur event , (It get triggered when focusing the component in MAUI blazor app )

**Comment by MackinnonBuck** [comment]
I was able to reproduce this using static HTML an a new WinUI project, so it seems to be a bug with the WinUI implementation of WebView2. This issue seems to describe a similar problem: https://github.com/microsoft/microsoft-ui-xaml/issues/5615

**Comment by MackinnonBuck** [comment]
Possibly related:
#5188 
https://github.com/microsoft/microsoft-ui-xaml/issues/5570
