### ISSUE TITLE
Android: IWindow.VisualDiagnosticsOverlay gets cleared when changing element properties

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#5202]
### Description

Android: overlay layer gets cleared when changing element properties

### Steps to Reproduce

1. New MAUI app.
2. Set Android Emulator as active config.
3. Replace MainPage.xaml and cs files with the attached ones.
4. Build and run. Notice how yellow rectangle changes its width every second.
5. In VS open Debug > Windows > XAML Live Preview (XLP).
6. Open Debug > Windows > Live Visual Tree (LVT) and expand all elements.
7. Hover mouse over elements in LVT, pausing 2-3 seconds over each element.
**Actual**: element highlighting appears as mouse gets over an element in LVT and then disappears as yellow rect changes its size.
**Expected**: elements highlighting should stay in place as long as mouse is over an element in LVT.
 
[MainPage.xaml.zip](https://github.com/dotnet/maui/files/8226065/MainPage.xaml.zip)
![MauiAndroidAdorners](https://user-images.githubusercontent.com/48451158/157731685-df139044-06df-4312-ae36-dad826c36d0c.gif)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android and probably iOS and Mac

**Comment by drasticactions** [comment]
Need to check for iOS, but on Android, we do clear out the existing Adorners when the Android view changes, which is probably not right. I can change that.

**Comment by drasticactions** [comment]
Fixed with https://github.com/dotnet/maui/pull/5203
