### ISSUE TITLE
[Bug] Menus doesn't render in Shell if not part of Shell

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5210]
### Description

If I put menus on a ContentPage that is a FlyoutItem, then the menu renders.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/41873/157760031-4857c94f-6ae6-43a3-a651-3d81084aadd8.png">

However, if I navigate to a page in Shell via a route, and that page was not an original part of the shell structure, the menu will not be displayed. In this case I navigate to AppThemes

<img width="454" alt="image" src="https://user-images.githubusercontent.com/41873/157760295-92e2e3cf-e092-45e3-85cd-1498442188a4.png">

```csharp
void InitMenu()
		{
			var fileMenu = new MenuBarItem { Text = "File" };
			var exitItem = new MenuFlyoutItem
			{
				Text = "Exit",
				Command = new Command((obj) =>
				{
					Application.Current.Quit();
				})
			};
			MenuItem.SetAccelerator(exitItem, Accelerator.FromString("cmd+q"));
			fileMenu.Add(exitItem);

			var locationMenu = new MenuBarItem { Text = "Location" };
			var changeItem = new MenuFlyoutItem
			{
				Text = "Change",
				Command = new Command((obj) =>
				{
					Navigation.PushAsync(new ButtonPage());
				})
			};
			locationMenu.Add(changeItem);

			var refreshItem = new MenuFlyoutItem
			{
				Text = "Refresh"
			};
			MenuItem.SetAccelerator(refreshItem, Accelerator.FromString("cmd+r"));
			locationMenu.Add(refreshItem);

			this.MenuBarItems.Add(fileMenu);
			this.MenuBarItems.Add(locationMenu);
		}
```

### Steps to Reproduce

Add the above code to a page in a Shell app and run it.

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

win11

**Comment by v-longmin** [comment]
@davidortinau Could you share your repro project/solution, thanks?

**Comment by PureWeen** [comment]
@davidortinau This should be fixed with the latest RC1 builds
