### ISSUE TITLE
[Bug] Menu missing accelerators

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5211]
### Description

I can create a menu and use the accelerator api, however it doesn't do anything. I should be able to use this or similar to add keyboard shortcuts to menu items.

```chsarp
void InitMenu()
		{
			var fileMenu = new MenuBarItem { Text = "File" };
			var exitItem = new MenuFlyoutItem
			{
				Text = "Exit",
				Command = new Command((obj) =>
				{
					Application.Current.Quit();
				})
			};
			MenuItem.SetAccelerator(exitItem, Accelerator.FromString("cmd+q"));
			fileMenu.Add(exitItem);

			var locationMenu = new MenuBarItem { Text = "Location" };
			var changeItem = new MenuFlyoutItem
			{
				Text = "Change",
				Command = new Command((obj) =>
				{
					Navigation.PushAsync(new ButtonPage());
				})
			};
			locationMenu.Add(changeItem);

			var refreshItem = new MenuFlyoutItem
			{
				Text = "Refresh"
			};
			MenuItem.SetAccelerator(refreshItem, Accelerator.FromString("cmd+r"));
			locationMenu.Add(refreshItem);

			this.MenuBarItems.Add(fileMenu);
			this.MenuBarItems.Add(locationMenu);
		}
```

### Steps to Reproduce

Add the code above to a ContentPage, run it. Note no compiler error, and no keyboard support.

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS

### Affected platform versions

win11

**Comment by shimingsg** [comment]
verified repro with vs 17.2.0 Preview 3.0 [32313.56.main] on windows

**Comment by egvijayanand** [comment]
Pressing the `Alt` key or its equivalent in macOS should visually indicate the `Accelerator Key` mapped to that menu item, like `Alt+F` for the File menu.

Generally, we would achieve this like &File (Placing an ampersand sign in front of the char that would be the menu item accelerator key).

**Comment by egvijayanand** [comment]
Hello Team,

Without accelerators for the menu items, how can the keyboard interaction happen? It's a must-have feature for desktops, both Windows and macOS. It's already a supported feature on Xamarin.Forms.

Regards,
Vijay Anand E G

**Comment by molesmoke** [comment]
@Redth Could you explain why this is only considered p2? As @egvijayanand pointed out, this is pretty much a blocker for writing a desktop app with MAUI. It seems surprising that this would get moved to the backlog.

**Comment by Redth** [comment]
We have a lot of different features and bugs that are different levels of importance to many different customers. 

We are doing our best to prioritize the time and resources.

One of the ways we try and gauge the level of impact an issue has is activity within it (eg: comments and reactions). 

We will continue to reassess which issues should be prioritized as we plan out our work.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 3.0. Repro on windows machine with sample project.
[MauiApp19.zip](https://github.com/dotnet/maui/files/11270314/MauiApp19.zip)

**Comment by jeremy-visionaid** [comment]
Hoping to see some progress on this one! Or at least a very least workaround...
It's a blocked for accessibility, since blind/visually impaired users are going to want to access menus with keyboard accelerators.
