### ISSUE TITLE
Controls aligned to right are cropped on Android

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/maui#5214]
### Description
Related to https://github.com/dotnet/maui/pull/5205
On Android right aligned controls getting cropped, this is noticeable when `HorizontalOptions` of the control set to "End" position for default or `LeftToRight` flow direction. And when `FlowDirection` is `RightToLeft` you can see it when  `HorizontalOptions` set to "Start" or "Fill".
<img width="310" alt="image" src="https://user-images.githubusercontent.com/45579687/157762816-bcfa30bc-f0cc-450f-9b79-d117a74390b4.png">
It seems each container cropping at least one character, in the above image with two nested container i see last 2-3 characters cropped. Previously with only one container i saw only one character cropped
<img width="610" alt="button_start_fixed" src="https://user-images.githubusercontent.com/45579687/157763572-119f5211-d8b6-4e18-9cd1-888432d5f52f.png">

### Steps to Reproduce

```xml
    <Label Text="Horizontal alignment FlowDirection = LeftToRight (default)"/>
    <StackLayout WidthRequest="400" BackgroundColor="AliceBlue">
        <Button HeightRequest="50" Text="Button end" HorizontalOptions="End" />
        <Label HeightRequest="50" Text="Label end" HorizontalOptions="End" />
        <Button HeightRequest="50" Text="Button Fill" HorizontalOptions="Fill" />
        <Label HeightRequest="50"  Text="Label Fill" HorizontalOptions="Fill" />
        <Button HeightRequest="50" WidthRequest="100" Text="Button fill" HorizontalOptions="Fill" />
        <Label HeightRequest="50"  WidthRequest="100" Text="Label fill" HorizontalOptions="Fill" />
    </StackLayout>
    <Label Text="Horizontal alignment FlowDirection = RightToLeft"/>
    <StackLayout WidthRequest="400" FlowDirection="RightToLeft" BackgroundColor="AliceBlue">
        <Button HeightRequest="50" Text="Button start" HorizontalOptions="Start" />
        <Label HeightRequest="50" Text="Label start" HorizontalOptions="Start" />
        <Button HeightRequest="50" Text="Button Fill" HorizontalOptions="Fill" />
        <Label HeightRequest="50"  Text="Label Fill" HorizontalOptions="Fill" />
        <Button HeightRequest="50" WidthRequest="100" Text="Button fill" HorizontalOptions="Fill" />
        <Label HeightRequest="50"  WidthRequest="100" Text="Label fill" HorizontalOptions="Fill" />
    </StackLayout>
1. Copy the xaml code example above into your app
2. run it on Android

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

### Relevant log output

_No response_

**Comment by Amir-Care** [comment]
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main]  on Android 11
Sample project: [#5214.zip](https://github.com/dotnet/maui/files/8228515/5214.zip)

**Comment by hartez** [comment]
@buyaa-n Can you test this again with the latest in main? I believe the changes in #5495 have fixed this.

**Comment by buyaa-n** [comment]
Looks the main issue is fixed, but a wider `WidthRequest` than the available width is still cropping, though i guess that is by design, so closing
