### ISSUE TITLE
Review code in Shell that's there to prevent overdraw on the navbar/statusbar

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#5217]
The following code adds about 11 ms to startup

https://github.com/dotnet/maui/blob/b1bdc55fb7a6fa4457f67ec288f13077583acb93/src/Compatibility/Core/src/Handlers/Shell/Android/ShellRenderer.cs#L319-L322

Is that 11 ms hit on startup worth what this code is achieving? Can it be achieved more efficiently? 

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/5375137/157789449-440d9798-81f2-48c7-a08f-ce46a927eab4.png">

**Comment by angelru** [comment]
any progress on this?
