### ISSUE TITLE
Erroneous warning about SurveyPrompt being unexpected name

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#5241]
### Description

After creating a MAUI Blazor project and looking at Index.razor I see a green squiggly line and the Warning:

Severity	Code	Description	Project	File	Line	Suppression State
Warning (active)	RZ10012	Found markup element with unexpected name 'SurveyPrompt'. If this is intended to be a component, add a @using directive for its namespace.		c:\Dev\PlatteStore\MAUI\PFMainApplication\MauiApp1\Pages\Index.razor	7	

### Steps to Reproduce

Create a new MAUI Blazor app
Open Index.razor

_Imports.razor has the required entries

@using MauiApp1
@using MauiApp1.Shared

### Version with bug

Preview 10

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11, Windows 10

### Did you find any workaround?

No

### Relevant log output

```shell
Visual Studio Version 17.2.0 Preview 1.0
```

**Comment by VladislavAntonyuk** [comment]
Try it with Preview 13, which is the latest preview version of .NET MAUI

**Comment by genifycom** [comment]
How do we get Preview 13? It is not offered via the Visual Studio Installer and going to https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-3-now-available/ and doing a download just launched the same Visual Studio Installer.

**Comment by v-longmin** [comment]
Verified the issue on vs 17.2 preview3 main\32310.304, the issue also repro, but wait a moment,  the green squiggly line and the Warning are disappear.
