### ISSUE TITLE
BlazorWebView inside iOS can't be reloaded

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/maui#5247]
### Description

On iOS, non-root Blazor pages fail to reload. This issue was previously identified on Android (#5136) and WinUI and was fixed for both platforms, but it persists on iOS.

### Steps to Reproduce

1. Create a Blazor Hybrid application
2. In one of your pages, add `<a href="javascript:location.reload()">Reload</a>`
    * This needs to be a non-root page. For example, the page at `/counter`, and not the homepage at `/`.
3. Run it on an iOS device
4. Click the reload link you just added

Expected: page should reload
Actual:
![image](https://user-images.githubusercontent.com/10456961/157986752-af244e43-e2cd-4e1e-b543-31f4f87b4a20.png)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15, but most likely others as well

**Comment by kristinx0211** [comment]
IOS 15.2 is also can be reproduced.

**Comment by TanayParikh** [comment]
@shimingsg can you please confirm if you're still seeing this in latest main / rc2?
