### ISSUE TITLE
Items do not render in CollectionView after scrolling when wrapped in ContentView

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#5248]
### Description

So a couple of things are needed to reproduce this issue:
- Some Element visibility changes depending on the item.
- This element is contained in ContentView (I cannot repro this issue if I wrap it in VerticalStackLayout)

<details>
<summary>xaml</summary>

```xaml
    <CollectionView ItemsSource="{Binding Items}">
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <ContentView>
                    <VerticalStackLayout>
                        <ContentView IsVisible="{Binding OneEnabled}" BackgroundColor="Cyan"  HeightRequest="120">
                            <Label Text="1" FontSize="30"/>
                        </ContentView>
                        
                        <ContentView IsVisible="{Binding TwoEnabled}" BackgroundColor="LightPink"  HeightRequest="120">
                            <Label Text="2" FontSize="30"/>
                        </ContentView>
                        
                        <ContentView IsVisible="{Binding ThreeEnabled}" BackgroundColor="LightGreen"  HeightRequest="120">
                            <Label Text="3" FontSize="30"/>
                        </ContentView>
                    </VerticalStackLayout>
                </ContentView>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
```
</details>

When you scroll the collection view, items start to disappear. 
If you update visibility for an existing item, it disappears as well.

Repro project: https://github.com/Dreamescaper/maui-5248-repro

Screen recording:
![qemu-system-x86_64_BpmzRborBP](https://user-images.githubusercontent.com/17177729/157988241-4db0e6f0-6bf7-4b30-a4bb-20a07f89895d.gif)

### Steps to Reproduce

1. Run repro project.
2. Scroll the CollectionView.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

### Did you find any workaround?

Wrap it in VerticalStackLayout (with single element) instead of CollectionView.

**Comment by Amir-Care** [comment]
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main]
