### ISSUE TITLE
Only MotionEventActions.Down in PlatformGraphisView?

### ISSUE THREAD

**Issue by mcguu** [dotnet/maui#5259]
### Description

in android of platform   I can get the Up and move of MotionEventActions 

only a Down

### Steps to Reproduce

1.Create a Maui Project
2. create a CustomFile in Platform/android
3. inherit from PlatformGraphicsView
4. override OnTouchEvent
5. call this View(register the handler of a view).
6. tap and drag the view
7. you will find that it only a down no up or move

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

Android

### Affected platform versions

Android10.0

### Did you find any workaround?

No I do not know why it come.

**Comment by XamlTest** [comment]
@mcguu could you share you project?

**Comment by mcguu** [comment]
[repo.zip](https://github.com/dotnet/maui/files/8250631/repo.zip)

in platform/android/poPlatformView.cs if you tap the view there is only down no up or move.

**Comment by Amir-Care** [comment]
Hi @mcguu , according to your describe , but  i run your project successfully,  when i tap or drag the view  there is no responese , Is there something wrong with my understanding？

![Android_316](https://user-images.githubusercontent.com/99456025/158529619-fb93cc19-3743-42d5-ad06-2431d077b3a4.gif)

**Comment by mcguu** [comment]
you can drag it and please check platform/android/poplatformview.cs and ovverride the OnTouchEvent

but there is only Down in MotionEventArgs no up and Move.

**Comment by mcguu** [comment]
@Amir-Care

**Comment by Amir-Care** [comment]
Hi @mcguu , i have check  platform/android/poplatformview.cs and the project you provide has override the OnTouchEvent method.  theis is Down, Up and Move in MotionEventArgs, and  only avaliable for android
![Android_MotionEventArgs ](https://user-images.githubusercontent.com/99456025/158549045-f86195a9-946b-4ec6-95fc-66756cf1f373.gif)

**Comment by mcguu** [comment]
@Amir-Care  Hi, add a breakpoint or Debug.WriteLine to see if really get a Up action?

**Comment by mcguu** [comment]
when you drag the view

**Comment by Amir-Care** [comment]
Hi @mcguu , i add a breakpoint and add a code "Console.WriteLine() " to  verify Up, Move and Down action if really work.
I find only Down work fine, another is not really work.

- Down:

   
   ![Android_Down](https://user-images.githubusercontent.com/99456025/158553432-cb21972c-84de-4d41-9941-ba8839eae37d.gif)

- Up:

   ![Android_Up](https://user-images.githubusercontent.com/99456025/158553457-75fc6903-39a5-4c40-b848-0b9263d00da4.gif)

- Move:

  
  ![Android_Move](https://user-images.githubusercontent.com/99456025/158553500-492a88cb-0ee5-4b3b-88c5-940cb026662c.gif)

**Comment by Amir-Care** [comment]
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main]

**Comment by mcguu** [comment]
@Amir-Care where do you think is the bug? how to solve it I can try to solve it myself?

**Comment by Redth** [comment]
This is related to #3261 which should bring in a full set of graphics touch events.

**Comment by mcguu** [comment]
@Redth that means it will done in rc2?

I have to wait?

where is the code of PlatformGraphicsView? I can not find it

I want to fix it by myself and I will know the maui better I think.

**Comment by Redth** [comment]
This is available in RC1. 

There's two issues here...

1. There were some missing api's from PlatformGraphicsView now available in the upcoming RC1
2. If you don't change the TFM in the drop down menu in the code editor in the top left to the platform you are wanting to view the code for, it will show you the api is unavailable though it really isn't (#5294)
