### ISSUE TITLE
MAUI Sqlite doesn't work on Mac M1 Monterey

### ISSUE THREAD

**Issue by bstrother1** [dotnet/maui#5269]
### Description

Attempting to interact with Sqlite on an Apple M1 Monterey throws an exception: The type initializer for 'Microsoft.Data.SQlite.SqliteConnection' threw an exception. Same setup works on regular projects without MAUI.

[MyMauiApp.zip](https://github.com/dotnet/maui/files/8240941/MyMauiApp.zip)
 

### Steps to Reproduce

1.Be on an M1 Mac with Monterey
2. Set up EFCore project w/ latest packages
3. Attempt to connect or create sqlite db
4. Experience error

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey 12.2.1

### Did you find any workaround?

n/a

### Relevant log output

```shell
The type initializer for 'Microsoft.Data.SQlite.SqliteConnection' threw an exception
```

**Comment by bstrother1** [comment]
should note this is on the net6.0-maccatalyst build.

**Comment by jfversluis** [comment]
I see you mention preview 10 as the .NET MAUI version. Are you sure about that? If so, why are you not on the latest version?

**Comment by bstrother1** [comment]
Sorry, I am actually on preview 13.2865. Must have miss clicked when drafting this ticket.

**Comment by drasticactions** [comment]
Are you _sure_ this only happens when you're running in MAUI? I think this is the same bug as https://github.com/dotnet/efcore/issues/24198 and I was able to run your code by directly calling for the built in sqlite from the Mac. Granted, I don't think you should have to do that.

```
#if IOS || MACCATALYST
        SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_sqlite3());
#endif
```

**Comment by bstrother1** [comment]
I am 100% sure. Here is the example project. I used this project to run migrations to create the table, and ran it to insert a singular record into the azure db. Same connection string, same efcore setup, different result. 

[EFCoreBasic.zip](https://github.com/dotnet/maui/files/8258662/EFCoreBasic.zip)

**Comment by bstrother1** [comment]
Oh, your asking if the example project I ran used  MACCATALYST? No it's an net6 project. Does that mean that efcore is bugged making MAUI bugged in return because of the usage of MACCATALYST.

**Comment by bstrother1** [comment]
Where did you place that if condition at? Model? Could this Maccatalyst problem w/ efcore and sqlite extend to other db types as well? I have a ticket out for Azure db doing something similar.

**Comment by bstrother1** [comment]
Hmm... after updating to:
using Foundation;
using SQLitePCL;

namespace MyMauiApp;

[Register(nameof(AppDelegate))]
public class AppDelegate : MauiUIApplicationDelegate
{
    protected override MauiApp CreateMauiApp()
    {
        raw.SetProvider(new SQLite3Provider_sqlite3());
        return MauiProgram.CreateMauiApp();
    }
}

it still doesn't work correctly. Throws the same error.

**Comment by Redth** [comment]
Sqlite needs to be rebuilt against the latest net6.0-ios as there are ABI breaks between Xamarin.iOS and net6.0-ios. Unfortunately until that happens there is not much we can do.
