### ISSUE TITLE
Label bound to a slider fails to update after a button is clicked

### ISSUE THREAD

**Issue by PrimeTempered** [dotnet/maui#5270]
### Description

After navigating to a new page with three controls (a label bound to a slider and a button), the label reports the value of the sliders normally when manipulating the slider. After the button is clicked, the value of the slider is no longer update by the label.

### Steps to Reproduce

1. Create a MAUI project named XamlSamples.
2. Copy/Past the following code into a new MAUI page named XamlPlusCodePage.xaml

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="XamlSamples.XamlPlusCodePage"
             Title="XAML + Code Page">
    <StackLayout>
        <Slider VerticalOptions="CenterAndExpand"
                ValueChanged="OnSliderValueChanged" />

        <Label Text="A simple Label"
               FontSize="Large"
               HorizontalOptions="Center"
               VerticalOptions="CenterAndExpand" />

        <Button Text="Click Me!"
                HorizontalOptions="Center"
                VerticalOptions="CenterAndExpand"
                Clicked="OnButtonClicked" />
    </StackLayout>
</ContentPage>

3. Copy/Paste the code below into the code-behind page, XamlPlusCodePage.xaml.cs

namespace XamlSamples
{
    public partial class XamlPlusCodePage
    {
        public XamlPlusCodePage()
        {
            InitializeComponent();
        }

        void OnSliderValueChanged(object sender, ValueChangedEventArgs args)
        {
              valueLabel.Text = args.NewValue.ToString("F3");
        }

        void OnButtonClicked(object sender, EventArgs args)
        {
               Button button = (Button)sender;
               await DisplayAlert("Clicked!",
                     "The button labeled '" + button.Text + "' has been clicked",
                     "OK");

        }
    }
}

4. Create a button on the application's MainPage.xaml to navigate to the XamlPlusCodePage when clicked.
5. Run the app, manipluate the slider to see the label update the slider's value.
6. Click the button below the slider and then OK to clear the DisplayAlert message.
7. Manipulate the slider again. The label will not update its value.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 21 and up

### Did you find any workaround?

No. I tried incorporating Markup Extensions but was not successful. I am just starting with Markup Extensions and saw this as a chance to apply some ideas, but the label seems to get disconnected from the slider (perhaps losing its binding is a beter way to put it) after the button is clicked. I tried this on another sample XAML page with a rotating label controlled by a slider (SliderBindingsPage.xaml). It too failed to update after clicking the button. 

This behavior was only exhibited on Android. The Windows version worked correctly after the button click.

I do not have the ability to develop for iOS/Mac so could not test those platforms. 

### Relevant log output

```shell
The following comes from the Output Window after hitting a breakpoint after clicking the button:

[Choreographer] Skipped 507 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=8455ms; Flags=0, IntendedVsync=47619941329706, Vsync=47628391329368, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=47628393610120, AnimationStart=47628393627020, PerformTraversalsStart=47628393650520, DrawStart=47628393819120, SyncQueued=47628394006320, SyncStart=47628395616220, IssueDrawCommandsStart=47628395687320, SwapBuffers=47628396476620, FrameCompleted=47628398640520, DequeueBufferDuration=903300, QueueBufferDuration=778600, GpuCompleted=-4294967296, 
[libc] Requested dump for tid 25807 (nyname.mauiapp1)
Thread finished: <Thread Pool> #7
The thread 0x7 has exited with code 0 (0x0).

The last line appeared a few seconds after the others.

Clicking the slider again resulted in the following from the Output Window:

Thread started: <Thread Pool> #12
Thread finished: <Thread Pool> #11
The thread 0xb has exited with code 0 (0x0).
Thread started: <Thread Pool> #13
Thread finished: <Thread Pool> #12
The thread 0xc has exited with code 0 (0x0).
Thread started: <Thread Pool> #14
Thread finished: <Thread Pool> #5
The thread 0x5 has exited with code 0 (0x0).
Thread started: <Thread Pool> #15
Thread finished: <Thread Pool> #14
The thread 0xe has exited with code 0 (0x0).
Thread started: <Thread Pool> #16
[Choreographer] Skipped 644 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=10738ms; Flags=0, IntendedVsync=47864324606764, Vsync=47875057939668, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=47875060710320, AnimationStart=47875060971120, PerformTraversalsStart=47875061035120, DrawStart=47875061380020, SyncQueued=47875061891220, SyncStart=47875062133720, IssueDrawCommandsStart=47875062222720, SwapBuffers=47875062917720, FrameCompleted=47875063643920, DequeueBufferDuration=32200, QueueBufferDuration=262600, GpuCompleted=8589934597, 
[libc] Requested dump for tid 25807 (nyname.mauiapp1)
Thread finished: <Thread Pool> #15
The thread 0xf has exited with code 0 (0x0).
Thread started: <Thread Pool> #17
Thread finished: <Thread Pool> #13
The thread 0xd has exited with code 0 (0x0).
Thread started: <Thread Pool> #18
Thread finished: <Thread Pool> #16
The thread 0x10 has exited with code 0 (0x0).
Thread started: <Thread Pool> #19
Thread finished: <Thread Pool> #17
The thread 0x11 has exited with code 0 (0x0).
Thread started: <Thread Pool> #20

I hope this is helpful.
```

**Comment by XamlTest** [comment]
Verified on Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main]. Not repro on Android 22 and 31. Project: [5270.zip](https://github.com/dotnet/maui/files/8242463/5270.zip)

If you have any doubt, you can reopen the issue and share your project, thank you.
