### ISSUE TITLE
On screen keyboard

### ISSUE THREAD

**Issue by mcjekm** [dotnet/maui#5272]
### Description

I am having issue with keyboard (on screen).
In my page, I have an entry control and a button.
The keyboard will be displayed when the focus is on entry control.
While the focus is on the entry control, I clicks the button. 
The button click command will be executed if I click the button, but the focus still remains on the entry, and the keyboard stays on… 
The button actually redirects to a new page. The new page is not having any controls on it. 
The keyboard display stays on even on the new page. 
Not sure is this a bug, or something I am missing in my code. 

### Steps to Reproduce

1. Create a page with one entry and a button.
2. run the app
3. click on the entry, then the keyboard will be displayed
4. click on the button. (I expect as the focus will be moved from entry to button, and I expect it will hide the keyboard automatically as the focus moved out from the entry)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 and up

**Comment by PineYi** [comment]
Verified Repro with Android 11. Repro Project is available:
[#5272.zip](https://github.com/dotnet/maui/files/8243190/5272.zip)

**Comment by Mephisztoe** [comment]
I am experiencing the same issue.

In my case, I have an AppShell enabled .NET MAUI App (Prev13) that has a CollectionView on the MainView (mvvm). When tapping on an item, AppShell navigates to an ItemView that contains a couple of Entry controls. When I focus an Entry control, the soft keyboard appears and I can type in text. When I hit the back button while the soft keyboard is still open (ToolBar, not a physical/virtual device button), AppShell navigates back to the MainView and the keyboard remains open.

I did a lot of research. 

It seems as if the best solution seems to be implementing platform agnostic RoutingEffects; however, although I tried to implement a "NoKeyboardEffect", it just does not work. :)

**Comment by jsuarezruiz** [comment]
We included pending functionality related with focus in P14. Have done some tests with main branch and the behavior seems to be the expected one now.
![issue-5272](https://user-images.githubusercontent.com/6755973/161566301-3085e610-4758-482f-81c2-011137153477.gif)
