### ISSUE TITLE
WebView Navigated and Navigating events do not occur

### ISSUE THREAD

**Issue by LanceMcCarthy** [dotnet/maui#5280]
### Description

WebView's Navigated and Navigating events are not executing when website navigation occurs. This is easy to reproduce, see steps below for specific guidance.

Note: This has been previously reported, but was closed without a defined solution https://github.com/dotnet/maui/issues/3857

### Steps to Reproduce

1. Create a new .NET MAUI preview13 project, add a ContentPage and use a WebView as the only page element 
3. Subscribe to the `Navigating` and `Navigated events`, use any website for the `Source`
4. Use breakpoints or Debug.WriteLine in both event handlers to observe if the event handler is being executed
6. Start debugging the project (any platform, I repro on Android and WinUI)

Observe => The Navigating and Navigated event handlers are never executed. 

> Also important, although my steps show to use Android, this issue seems exists on every platform.

Here is code you can use:

```xml
<ContentPage ...>
    <WebView x:Name="WebView1"
                      Source="https://www.bing.com"
                      Navigating="WebView1_Navigating"
                      Navigated="WebView1_Navigated"/>
</ContentPage>
```

```csharp
private async void WebView1_Navigating(object sender, WebNavigatingEventArgs e)
{
    Debug.WriteLine("Navigating Fired");
}

public async void WebView1_Navigated(object sender, WebNavigatedEventArgs e)
{
    Debug.WriteLine("Navigated Fired");
}
```

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12 / API 31

### Did you find any workaround?

I need anything that can give me the navigated to URL. Specifically, I need the query string, but nothing I tried works.

### Relevant log output

```shell
I don't see any relevant output.
```

**Comment by wenwen60** [comment]
Reproduce on widows with VS2022 17.2.0 Preview 2.0 [32215.517.main], attach repro sample
[MauiApp4.zip](https://github.com/dotnet/maui/files/8249544/MauiApp4.zip).

**Comment by LanceMcCarthy** [comment]
Hi team,

I wanted to provide a status update after bumping my project to use to `preview14`.

## Android ✔

I am now seeing the Navigated event successfully fire and am getting the expected Url values!

![image](https://user-images.githubusercontent.com/3520532/158897041-1602a05a-1e75-4917-b67c-a6e34d491bff.png)

## iOS/MacCatalyst ❓

WIP - will report back with results when VS 2022 Preview -> Mac deployments are working.

## Windows ❌

I am having issues with WinUI builds deployment, when the page with the WebView loads, there's an IndexOutOfRangeException on the same page that works in Android. I'm still investigating if this has to do with Shell on WinUI not working as expected.
