### ISSUE TITLE
Entry TextColor and BackgroundColor set through attached behaviour not updating on Windows

### ISSUE THREAD

**Issue by Naryorill** [dotnet/maui#5281]
### Description

I created a new MAUI project with VS 17.2 Preview 1, added an extra row to the grid with an Entry and copied the code from the [attached behavior documentation](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/behaviors#attached-behaviors).

It works as expected on my local Android device (Samsung SM-T813 (Android 7.0 - API 24), but doesn't work when I run it on the Windows Machine. Same issue when I set the background color. The debugger stops in the method though, and shows that the TextColor is red, it just doesn't appear that way in the running app.
Setting the text (with a safeguard that the text is only set once) works as expected.

### Steps to Reproduce

1. Create .NET MAUI App (Preview) project
2. Add a new class with the code from [the documentation](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/behaviors#attached-behaviors)
3. Add an entry as described in the documentation to MainPage.xaml
4. Run on Windows Machine
5. Enter a letter in the new entry, the color doesn't turn red as it should (and does on Android)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 10.0.19044

**Comment by Amir-Care** [comment]
- Windows:  TextColor doesn't change
  ![image](https://user-images.githubusercontent.com/99456025/158295706-bf920796-f328-4cfa-9ca4-cd19d56a642f.png)

  ![image](https://user-images.githubusercontent.com/99456025/158295759-edce6dca-4178-422f-89c4-c5278720a1bb.png)


- Android: TextColor change according to the behavior
  
   ![image](https://user-images.githubusercontent.com/99456025/158297862-5d63dfa5-3fff-4ef9-9f9a-efb52e653961.png)

   ![image](https://user-images.githubusercontent.com/99456025/158297884-1987f1e0-deed-417b-9512-ad666ce53e18.png)

Sample project:  [#5281.zip](https://github.com/dotnet/maui/files/8249835/5281.zip)

**Comment by Naryorill** [comment]
To reiterate: BackgroundColor has the same issue as TextColor, and maybe there are other things affected too. I have no clue about the .NET MAUI code, but it looks like the pull request only addresses the text color.

**Comment by Amir-Care** [comment]
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main] on Windows and not repro on Android.

- Windows: TextColor and BackgroundColor doesn't change

   
     ![Windows](https://user-images.githubusercontent.com/99456025/158334411-9eebe294-72a1-4ec1-b052-3075f7b738e5.gif)

- Android: TextColor and BackgroundColor changed  according to the behavior

  
     ![Android](https://user-images.githubusercontent.com/99456025/158334446-f6ad4a13-8058-49c5-be10-88325c93cf66.gif)

- Sample project:  [MauiApp50.zip](https://github.com/dotnet/maui/files/8251343/MauiApp50.zip)
