### ISSUE TITLE
[Mac Catalyst] MAUI unable to connect with db EFCore

### ISSUE THREAD

**Issue by bstrother1** [dotnet/maui#5284]
### Description

Attempting to use existing database throws an 'object is not an object' error with connection to Azure DB in a Docker instance using connection string: 

protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlServer("Server=localhost,1433; Database=GardenDb2;User=sa; Password=MyPass@word");

[MyMauiApp.zip](https://github.com/dotnet/maui/files/8247273/MyMauiApp.zip)

### Steps to Reproduce

1. Install Docker
2. Pull latest Azure SQL Edge image
3. Generate Container 
4. Either use a Dummy Project or a Separate Project to generate db (only net6 or core can natively do this)
5. Try to interact with DB w/ Entity Framework, Get 'Object is not an instance of an object' error

I have only been able to test this on Mac catalyst. 

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS Monterey 12.2.1

### Did you find any workaround?

n/a

### Relevant log output

```shell
The type initializer for 'Microsoft.Data.SqlClient.AzureManagedIdentityAuthenticationProvider' threw an exception.
Object reference not set to an instance of an object
```

**Comment by jfversluis** [comment]
If you're connecting to something on another "machine" even Docker container or whatever, is connecting to localhost then correct?

**Comment by bstrother1** [comment]
Yes, that is correct. I am able to connect on a separate non-maui project.

**Comment by Redth** [comment]
I'm guessing either localhost is not correct and needs an actual IP to resolve correctly and/or the connection is not secure (TLS) and requires to be or an exception for the app/URL.  iOS/MacCatalyst has network rules enforced like this.

You can read more here: https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/
