### ISSUE TITLE
RadioButtonGroup.SelectedValue not triggered (windows app)

### ISSUE THREAD

**Issue by softlion** [dotnet/maui#5298]
### Description

RadioButton does not trigger any change (on a maui windows app).

### Steps to Reproduce

Convert() is called on start (ConvertBack is also called ?????? This is another issue as no user interaction has been involved).

```
        <StackLayout Orientation="Horizontal" RadioButtonGroup.GroupName="Filter" RadioButtonGroup.SelectedValue="{Binding DisplayFilter,Converter={StaticResource FilterConverter}}"  Spacing="5">
            <RadioButton Value="All" Content="{Binding CountOfTotal, StringFormat='Display All ({0})'}" />
            <RadioButton Value="Invalids" Content="{Binding CountOfInvalids, StringFormat='Display Invalids ({0})'}" />
            <RadioButton Value="Valids" Content="{Binding CountOfValids, StringFormat='Display Valids ({0})'}"/>
            <RadioButton Value="Unknowns" Content="{Binding CountOfUnknown, StringFormat='Display Unknowns ({0})'}"/>
        </StackLayout>
```

```
    public sealed class FilterConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return value.ToString();
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return Enum.Parse<Filter>((string)value);
        }
    }

    public enum Filter
    {
        All,
        Invalids,
        Valids,
        Unknowns,
    }
```

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

no

**Comment by softlion** [comment]
@jfversluis not tested on other platforms.
The same code is working properly on Xamarin Forms and even WPF.

**Comment by Amir-Care** [comment]
@softlion Thank you so much for your bug report! Unfortunately, I cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that I can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by softlion** [comment]
@Amir-Care can i see your repro project ?

**Comment by Amir-Care** [comment]
@softlion this is my repro project, could you give me some suggestions or you can modify it according to your issue ? thanks !
[#5298.zip](https://github.com/dotnet/maui/files/8259367/5298.zip)

**Comment by softlion** [comment]
My repro

[ReproMauiBug.zip](https://github.com/dotnet/maui/files/8262190/ReproMauiBug.zip)

**Comment by Amir-Care** [comment]
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main] on Windows.


 ![windows_radiobtn](https://user-images.githubusercontent.com/99456025/158722460-6ed0198a-c2a4-496c-a353-c0a75be22778.gif)

**Comment by cshung** [comment]
@Amir-Care 
The repro you attached works as expected on the main branch, it is no longer reproducible

**Comment by softlion** [comment]
> @Amir-Care The repro you attached works as expected on the main branch, it is no longer reproducible

Thereis still the issue where the "default" button is still not selected on startup.

**Comment by cshung** [comment]
>  i can still reproduce it.

@softlion, Are you sure? I just tested it on the **main** branch yesterday. Note that we haven't released any binary for the main branch yet, you must check out the code and compile yourself to verify.
