### ISSUE TITLE
Add Imaging Tools or make MS Lumia Imaging working with Maui

### ISSUE THREAD

**Issue by sb34000** [dotnet/maui#531]
Working with images is so sad and poor on windows with .net tooling!
Of course there are a few nugets that don't do much, and a few dead-born projects? like Windows Imaging Component (WIC) ...
But there was an absolutely fantastic solution, very complete and allowing to do a lot of things with images (pixel transformations, like light, contrast, colors, blur, effects, lights, images combinations ....).
One of the most complete solutions on the market! It is MS Lumia Imaging SDK which comes from the acquisition of Lumia.

It was available for UWP development but does not appear to be available for future Microsoft dev platforms. And yet I think about nearly 80% of the applications in the store that manipulate images were probably created with this solution.

Why does Microsoft always give up the things that work well and give great functionality, simplicity and fun, power and satisfaction?

So PLEASE (!!!!!!!!) consider adding or porting this awesome Imaging SDK or equivalent on MAUI!
Or build a new one as powerful and complete if it's a better option.
But for now there is nothing at all on Microsoft side for working with images!

**Comment by Redth** [comment]
Out of scope, but thanks for the suggestion, maybe it would be good to check out something like https://github.com/SixLabors/ImageSharp

**Comment by sb34000** [comment]
Thanks for the answer. So I understand that Imaging is out of scope for MAUI ? Anything else is out of scope ? (I'm joking :))
I was dreaming for real imaging features in MAUI... Bad start for building imaging apps.
I know ImageSharp but it's really poor. Nice only for some basic image transformations, but does not allow to do the minimum of features that we find in hundreds of mobile apps on Android, IOS or even UWP. 
It's not a real competitor in the scope of imaging library (such
as Nokia Imaging, Adobe imaging library...).
I'll be happy, to hear of any suggestion for building imaging apps in MAUI
