### ISSUE TITLE
IWindow.DisplayDensityChanged not firing on Mac Catalyst / iOS 

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#5315]
### Description

Original code that should work:

```cs


				UIScreen.Notifications.ObserveModeDidChange(window.Screen, new System.EventHandler<NSNotificationEventArgs>((sender, args) =>
				{
					if (args.Notification.Object is UIScreen screen)
					{
						window.GetWindow()?.DisplayDensityUpdated((float)screen.Scale.Value);
					}
				}));
```

### Steps to Reproduce

Not implemented

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

All

**Comment by taublast** [comment]
Backlog milestone? How are we supposed to create maui apps for Mac if this doesn't work.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Not repro this issue.
