### ISSUE TITLE
RefreshView pull to refresh executes refresh command in Android but not iOS

### ISSUE THREAD

**Issue by mpkagel** [dotnet/maui#5316]
### Description

Pull to refresh in Android works for me fine. However, in iOS, pull to refresh shows the refresh icon but doesn't execute the command that is bound to the RefreshView.

### Steps to Reproduce

1. Add a RefreshView to the Xaml file with a CollectionView in it.
2. Give the RefreshView a binding to a command and a datatype viewmodel and a binding to the IsRefreshing property. Also, make sure the RefreshView has a RefreshColor set or it will throw a NullReferenceException in this version of Maui.
3. Put a break point somewhere in the command that was bound to the RefreshView.
4. Go to the page with the RefreshView in Android and try to pull to refresh. This should work and hit the breakpoint in the command that is bound.
5. Go to the page with the RefreshView in iOS and try to pull to refresh. This should not work, and won't hit the breakpoint in the command that is bound.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

**Comment by XamlTest** [comment]
@mpkagel Could you share a sample project for us? Thanks

**Comment by mpkagel** [comment]
I've attached a sample project that has a page with a RefreshView that demonstrates the issue. This project is on Maui 14, and it looks like this bug is still there.
[MauiFlyout.zip](https://github.com/dotnet/maui/files/8352843/MauiFlyout.zip)

**Comment by kristinx0211** [comment]
repro this issue on IOS 15.4 using above project, pull to refresh does not hit the breakpoint in the command that is bound.

**Comment by richp582** [comment]
Still seeing this as well...

**Comment by ArchangelWTF** [comment]
Still seeing this on .NET 7, I'm surprised it hasn't been triaged yet.

**Comment by glihm** [comment]
Still seeing this on .NET7, on a fresh project with only a refresh view deployed on iOS local device and simulator.

**Comment by japarson** [comment]
@glihm I'm having trouble reproducing this issue. Could you provide your repro project? Also, which version of MAUI are you using and which simulator are you testing on?

**Comment by glihm** [comment]
@japarson thank you for the follow up.

I have tried on a fresh project but pasted some code from my project and the reason was a layout mistake, making the `RefreshView` not accessible and it looked completely unresponsive. But doing tests now on several iPhone simulators in `iOS 16.2` and `iOS 16.0` everything works fine with a good layout.

(also updated VS to latest preview version since my last try the last week, so I don't know if it can matter)

I posted my comment too early before enough testing on my side, as it was due to layout issues (I suppose).

**Comment by japarson** [comment]
@glihm Thank you for the confirmation. That helps my investigation a lot.

@samhouts I'm not able to reproduce this issue with latest MAUI on iOS simulator 16.2. I wanted to test it out on iOS 15.4, but I'm having trouble getting that version running on my Mac (not compatible with my OS). It seems that @glihm can't repro it either so I'm thinking this issue has been fixed or is specific to 15.4.
