### ISSUE TITLE
HttpClient warning in Microsoft.MacCatalyst

### ISSUE THREAD

**Issue by iNoles** [dotnet/maui#5325]
### Description

ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetAllowAutoRedirect(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetAutomaticDecompression(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetCheckCertificateRevocationList(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetClientCertificateOptions(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetClientCertificates(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetCookieContainer(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetCredentials(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetDefaultProxyCredentials(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetMaxAutomaticRedirections(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetMaxConnectionsPerServer(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetMaxResponseHeadersLength(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetPreAuthenticate(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetProperties(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetProxy(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetServerCertificateCustomValidationCallback(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetSslProtocols(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetSupportsAutomaticDecompression(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetSupportsProxy(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetSupportsRedirectConfiguration(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetUseCookies(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.GetUseProxy(): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetAllowAutoRedirect(Boolean): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetAutomaticDecompression(DecompressionMethods): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetCheckCertificateRevocationList(Boolean): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetClientCertificateOptions(ClientCertificateOption): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetCookieContainer(CookieContainer): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetCredentials(ICredentials): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetDefaultProxyCredentials(ICredentials): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetMaxAutomaticRedirections(Int32): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetMaxConnectionsPerServer(Int32): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetMaxResponseHeadersLength(Int32): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetPreAuthenticate(Boolean): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetProxy(IWebProxy): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetServerCertificateCustomValidationCallback(Func<HttpRequestMessage,X509Certificate2,X509Chain,SslPolicyErrors,Boolean>): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetSslProtocols(SslProtocols): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetUseCookies(Boolean): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetUseProxy(Boolean): Unresolved assembly 'Microsoft.MacCatalyst' in 'DynamicDependencyAttribute'. [/Users/jonathansteele/Projects/SpaceXLaunch/SpaceXLaunch.csproj]

### Steps to Reproduce

1. Create A new MAUI Project
2.  Run it by net6.0-maccatalyst
3. Look at the output

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS 12.3

### Did you find any workaround?

None

**Comment by jfversluis** [comment]
I've seen this as well. Just for completeness @iNoles besides this output, does everything seem to work correctly at runtime?

**Comment by iNoles** [comment]
> I've seen this as well. Just for completeness @iNoles besides this output, does everything seem to work correctly at runtime?

No, it does crashed at runtime

**Comment by LanceMcCarthy** [comment]
This also crashes any app using an external library that needs those handlers resolved. Replicated with Cosmos DB

`<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.25.0" />`

Note: This works when used in a plain .NET6 console app on the same device.

**Comment by samidip** [comment]
Glad others are seeing this too .. lots of crashes around anything HTTPClient on iOS/Mac. I pinged David Ortinau as well.

**Comment by LanceMcCarthy** [comment]
Preview 14 is live right now (via `dotnet workload install maui`), I will test is again with v14's bits now and report back.

**Comment by LanceMcCarthy** [comment]
I'm happy to report that this is no longer an issue in preview14!

@samidip You'll need to comment out our custom controls until we do a recompile with preview14, but everything else works as expected (on MacCatalyst)

**Comment by jfversluis** [comment]
Thanks for letting us know!
