### ISSUE TITLE
SearchBar Text changed Event is not triggered in iOS and MacCatalyst Platform

### ISSUE THREAD

**Issue by SuthiYuvaraj** [dotnet/maui#5326]
### Description

In SearchBar , Text changed property is not triggered when the text is entered in the placeholder in iOS and MacOS platform , Also propertyChanged, PropertyChanging , SearchButtonPressed Event is not triggered. 

### Steps to Reproduce

1. Create a new blank .NET Maui app (Xaml/C#)
2. In Xaml, add SearchBar in the content Page.
3. Hook the TextChanged event in the xaml/c# page
4. Run the program on iOS and MacCatalyst platform
5. Note that the Textchanged event is not triggered when the text changing in placeholder

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15.2

### Did you find any workaround?

Used Handler for searchbar , SearchText property is triggered from the SearchBar handler

### Relevant log output

```shell
No response
```

**Comment by XamlTest** [comment]
Verified on Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main]. This issue repro on iOS, not repro on Android. Repro Project: [5326.zip](https://github.com/dotnet/maui/files/8260623/5326.zip)
