### ISSUE TITLE
Project with SkiaSharp nugets is not built for iOS (error MSB6006: "ditto" exited with code 1)

### ISSUE THREAD

**Issue by SailDev** [dotnet/maui#5329]
### Description

When adding SkiaSharp nuget packages to my project the build for iOS (via paired Mac) exits with the following error message:
"error MSB6006: "ditto" exited with code 1"

Building for Android and Windows works as expexted.

### Steps to Reproduce

1. Add the following SkiaSharp packages (Version 2.88.0-preview.187) to the project	
  * SkiaSharp.Views.Maui.Controls
  * SkiaSharp.Views.Maui.Controls.Compatibility
  * SkiaSharp.Views.Maui.Core
 2. Connect a physical Iphone to the build host Mac.
 3. Pair to Mac.
 4. Build "Debug" version.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.3.1

### Did you find any workaround?

No

### Relevant log output

```shell
43>/usr/bin/ditto C:/Users/Mike/.nuget/packages/skiasharp.nativeassets.ios/2.88.0-preview.209/runtimes/ios/native/libSkiaSharp.framework/ bin/Debug/net6.0-ios/ios-arm64/publish/../YO.app//Frameworks//libSkiaSharp.framework
43>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.301-preview.13.2\targets\Xamarin.Shared.Sdk.targets(652,3): error MSB6006: "ditto" exited with code 1.
```

**Comment by LanceMcCarthy** [comment]
I've been seeing this as well, but didn't realize it was due to SkiaSharp packages.

Can be replicated with this project https://github.com/LanceMcCarthy/MvpApi/tree/add-maui/src/MvpCompanion.Maui (open `MvpApi_Maui.sln` in the parent folder)

**Comment by Redth** [comment]
@mattleibow this should be good now right with the latest packages?

**Comment by SailDev** [comment]
Later today, i will upgrade to Visual Studio Preview 17.2.0 Preview 2.1 and test it with the latest preview of SkiaSharp.

**Comment by SailDev** [comment]
Fixed with:
- SkiaSharp version 2.88.0-preview.232
- Visual Studio Preview 17.2.0 Preview 2.1
