### ISSUE TITLE
CollectionView with Header or Footer throws: The specified child already has a parent. You must call removeView() on the child's parent first

### ISSUE THREAD

**Issue by SailDev** [dotnet/maui#5332]
### Description

The initial situation is a simple page with a CollectionView and a Button. 

I press the button and inside a ViewModel i add a new item to the ObservableCollection, which is bound to the ItemsSource of the CollectionView.

If i have no CollectionView.Header or CollectionView.Footer defined, everything works as expected.

If i add a Header or Footer to the CollectionView the same scenario throws the following exception:
Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'

### Steps to Reproduce

1. Create a page with a CollectionView and a Button.
2. Create a ViewModel with an ObservableCollection as ItemsSource for the CollectionView and an IAsyncCommand handler for the button and bind them to the UI.
3. Add a new item to the ObservableCollection, when the button is pressed.
4. Test different scenarios:
   * CollectionView without Header and Footer (o.k.)
   * CollectionView with Header (error)
   * CollectionView with Footer (error)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Physical device with Android 11

### Relevant log output

```shell
Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'
```

**Comment by SailDev** [comment]
Observed a similar behaviour with <CollectionView.EmptyView>.

Scenario:
A Shell Tab page with 3 bottom tabs.
The root of each tab is a page with a CollectionView inside.

If the EmptyView is declared like this

`
      <CollectionView.EmptyView>
      <Label Text="Empty here."/>  
       </CollectionView.EmptyView>
`

after switching between all 3 tabs back and forth, i get an Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.' 

Declaring EmptyView as string 

` <CollectionView ... EmptyView="Empty here">
`

works without error.

**Comment by shimingsg** [comment]
verified repro with VS 17.2.0 Preview 3.0 [32323.346.main] on Android 11 emulator, 
demo: [MauiApp5332.zip](https://github.com/dotnet/maui/files/8339066/MauiApp5332.zip)

here are the test different scenarios:
Test different scenarios:
CollectionView without Header and Footer (error) - 
![5332-h-f](https://user-images.githubusercontent.com/20982341/159858335-21d53460-b72b-4f98-9012-0008e40bab1c.gif)

CollectionView with Header (ok)
![5332-h](https://user-images.githubusercontent.com/20982341/159858441-cc0e7668-2e8a-4bfc-ace7-3ea547c7124a.gif)

CollectionView with Footer (error) 
![5332-f](https://user-images.githubusercontent.com/20982341/159858616-adcfb373-6a4c-409a-a6c9-950f6e851745.gif)

but if press clear all items button which call the items.clear() has the same error
```
Java.Lang.IllegalStateException
  Message=The specified child already has a parent. You must call removeView() on the child's parent first.
```

**Comment by yunusefendi52** [comment]
I tried using `FooterTemplate` everything is ok except if I use `Footer`

**Comment by PureWeen** [comment]
Duplicate

https://github.com/dotnet/maui/issues/5616

**Comment by limefrogyank** [comment]
I haven't narrowed  it down to the specific cause, but I'm seeing similar errors when using a `TableView`.  Mine has the following structure:
```
    <TableView Intent="Form" HasUnevenRows="True">
        <TableRoot>
            
            <TableSection Title="Grading">
                <TextCell IsEnabled="False" Text="{Binding EntityDisplayName}" />
                <SwitchCell Text="Published" On="{Binding IsGraded, Mode=TwoWay}"/>
                <EntryCell Label="{Binding CombinedScoreLabel}" Keyboard="Numeric" HorizontalTextAlignment="End" Text="{Binding Score,Mode=TwoWay}"/>
                <!--<TextCell  Text="{Binding MaxScore}" Detail="Max Score" />-->
                <EntryCell Label="Feedback"  Keyboard="Text" Text="{Binding FeedbackText,Mode=TwoWay}" VerticalTextAlignment="Center"/>
            </TableSection>
            
            <TableSection Title="Submissions">
                <ViewCell>
                    <ListView ItemsSource="{Binding Submissions}"
                                  IsGroupingEnabled="True"
                                  GroupDisplayBinding="{Binding Key.SubmissionDate}"
                                  SelectedItem="{Binding SelectedFile2, Mode=TwoWay}"
                                  >
                        <ListView.ItemTemplate>
                            <DataTemplate>
                                <TextCell Text="{Binding File.FileName}" Detail="no comments"/>
                            </DataTemplate>
                        </ListView.ItemTemplate>
                    </ListView>
                </ViewCell>
            </TableSection>
        </TableRoot>

    </TableView>

```
When I remove the TableView and just have the inner ListView, everything works fine.
