### ISSUE TITLE
IWindow.VisualDiagnosticsOverlay.Density is always 1

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#5334]
### Description

IWindow.VisualDiagnosticsOverlay.Density is always 1

### Steps to Reproduce

1. Make sure your Windows display settings are set to something different than 100%.
2. Create new MAUI app targeting Windows.
3. Replace MainPage.xaml and *.cs with the attached ones.
4. Build and run app. Click on a button
Actual: test appears which states that density is 1
Expected: density should match your OS settings, i.e. should be the same as reported by WinUI.
Note: View.Bounds are reported in MAUI units. With wrong density we cannot convert it to pixels which is needed for XAML Live Preview
[MainPage.xaml.zip](https://github.com/dotnet/maui/files/8262629/MainPage.xaml.zip)

![image](https://user-images.githubusercontent.com/48451158/158603218-17c56315-4ee2-4f03-a615-deedd2d88dae.png)

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows

**Comment by PineYi** [comment]
Verified Repro with Windows. Repro Project is available:
[#5334.zip](https://github.com/dotnet/maui/files/8280163/5334.zip)
![image](https://user-images.githubusercontent.com/99375367/158721187-35660a49-f0f6-436e-ae92-f729720d2eeb.png)
