### ISSUE TITLE
Microsoft.Maui.Dispatching.IDispatcherTimer frequently fires too early

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#5335]
### Description

Microsoft.Maui.Dispatching.IDispatcherTimer frequently fires too early

### Steps to Reproduce

1. New MAUI app targeting windows.
2. Replace MainPage.xaml and *.cs with attached ones.
3. Build and run. Click on a button.
4. Pay attention to text starting timer interval and actual tick time
Actual: tick time on non-first ticks drops to less than 1ms
Expected: tick time on non-first ticks stays around 500ms
[MainPage.zip](https://github.com/dotnet/maui/files/8262801/MainPage.zip)
![image](https://user-images.githubusercontent.com/48451158/158607516-635b5864-81d5-43a5-9b3d-2dc0c82fc77a.png)

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows

**Comment by v-longmin** [comment]
Verified the issue on windows, it's repro. Repro project: [\\\mlangfs1\Public\dotnet maui\Repro Project\5335.zip
]("")
