### ISSUE TITLE
NullReferenceException in CreateNativeHandler for HttpClient on IOS

### ISSUE THREAD

**Issue by owaits** [dotnet/maui#5337]
### Description

I am seeing a NullReferenceException when trying to instantiate an instance of HttpClient on IOS devices after a release build published through the AppStore. The following device log indicates that a NullReferenceException occurs in System.Net.Http.HttpClientHandler.CreateNativeHandler().

Time	Device Name	Type	PID	Tag	Message
Mar 16 08:43:49	Olivers-iPad	Notice	1215	WordAlive	Query Error youthandchildren: Arg_NullReferenceException Stack=    at System.Net.Http.HttpClientHandler.CreateNativeHandler()

### Steps to Reproduce

Create a new MAUI app
Add the code `var http = new HttpClient()` on startup.
Publish the app using the command line "dotnet publish Trunk/WordAlive/WordAlive.csproj -f net6.0-ios -c Release -o wa2022 -p:BuildIpa=True -p:ArchiveOnBuild=true -p:IpaPackagePath=/Users/runner/work/1/s/builds/wa2022.ipa -p:EnableAssemblyILStripping=false -r ios-arm64 --self-contained"

The following linker errors which I think are related are generated:

ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetCredentials(ICredentials): Unresolved assembly 'Microsoft.iOS' in 'DynamicDependencyAttribute'. [/Users/runner/work/1/s/Trunk/WordAlive/WordAlive.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetProxy(IWebProxy): Unresolved assembly 'Microsoft.iOS' in 'DynamicDependencyAttribute'. [/Users/runner/work/1/s/Trunk/WordAlive/WordAlive.csproj]

Upload the ipa to the app store through testflight
Install the app and run it with device log open
It will crash and in the device log you see Arg_NullReferenceException

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 12

### Affected platforms

iOS

### Affected platform versions

iPadIOS 15

### Did you find any workaround?

Not yet

### Relevant log output

```shell
Time	Device Name	Type	PID	Tag	Message
Mar 16 08:43:49	Olivers-iPad	Notice	1215	WordAlive	Query Error youthandchildren: Arg_NullReferenceException Stack=    at System.Net.Http.HttpClientHandler.CreateNativeHandler()

Starting: Build Word Alive App for IOS
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.200.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
dotnet publish Trunk/WordAlive/WordAlive.csproj -f net6.0-ios -c Release -o wa2022 -p:BuildIpa=True -p:ArchiveOnBuild=true -p:IpaPackagePath=/Users/runner/work/1/s/builds/wa2022.ipa -p:EnableAssemblyILStripping=false -r ios-arm64 --self-contained
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/a745a9ea-3187-40e4-a60b-98c8dba99889.sh
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/runner/work/1/s/Trunk/NWA.Core/WordAlive.Core.csproj (in 470 ms).
  Restored /Users/runner/work/1/s/Trunk/WordAlive/WordAlive.csproj (in 531 ms).
  Detected signing identity:
          
    Code Signing Key:
    Provisioning Profile:
    Bundle Id: org.wordaliveevent.wa2022
    App Id: 
  WordAlive.Core -> /Users/runner/work/1/s/Trunk/NWA.Core/bin/Release/net6.0/MWC.Core.MD.dll
  WordAlive -> /Users/runner/work/1/s/Trunk/WordAlive/bin/Release/net6.0-ios/ios-arm64/WordAlive.dll
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetCredentials(ICredentials): Unresolved assembly 'Microsoft.iOS' in 'DynamicDependencyAttribute'. [/Users/runner/work/1/s/Trunk/WordAlive/WordAlive.csproj]
ILLink : warning IL2035: System.Net.Http.HttpClientHandler.SetProxy(IWebProxy): Unresolved assembly 'Microsoft.iOS' in 'DynamicDependencyAttribute'. [/Users/runner/work/1/s/Trunk/WordAlive/WordAlive.csproj]
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Created the package: /Users/runner/work/1/s/builds/wa2022.ipa
Finishing: Build Word Alive App for IOS
```

**Comment by jfversluis** [comment]
Look a lot like what was happening here: #5325

Could you verify with preview 14 that this problem goes away?
