### ISSUE TITLE
[Android] Application crashed while load more images on scroll view

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#5339]
### Description

We have created an application to load images on the scroll view. but the sample crashed on loading
```

<Grid.Resources>
<local:CustomImageConverter x:Key="CustomImageConverter"/>
<DataTemplate x:Key="HeaderTemplate">
<Grid>
<!--<Image Aspect="Fill" Source="{Binding Converter={StaticResource CustomImageConverter}}"/>-->
<Label x:Name="label" HorizontalOptions="Start" VerticalOptions="Start" TextColor="Black" FontSize="16" Padding="55, 20, 0, 0" Text="{Binding StringFormat='{0:MMMM yyyy}'}"/>
</Grid>
</DataTemplate>
</Grid.Resources>
```

![Screen Shot 2022-03-16 at 8 55 45 PM](https://user-images.githubusercontent.com/44917578/158626357-7e83003f-ce34-48ad-b850-43e5a8ac62f9.png)

**Device details:**
![Device detail 2](https://user-images.githubusercontent.com/44917578/158626441-62f0738a-2cfd-4563-8dd0-142dee4cc3c3.png)
![Device detail-1](https://user-images.githubusercontent.com/44917578/158626468-8f822765-e9db-4016-b49e-acaab31e42d1.png)

### Steps to Reproduce

1. Create the sample with scroll view
2. Load the template inside the scroll view content
3. It makes crash

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8 and below sometimes latest version also makes crash

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
According to this error you're trying to load an image that is 140MB. Try to use smaller images as this is not something Android (or other platforms for that matter) can handle.

If you think this is in error, place provide us with a reproduction sample that shows this issue that we can look at.
