### ISSUE TITLE
Add new VisualDiagnostic APIs for rendering elements and views as images.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#5340]
### Description

- [x] RenderAsBMP
- [x] RenderAsRaw
- [x] Render Visual Diagnostic Layer as Image
- [x] Render IWindow
- [x] Render both Visual Diagnostic Layer and IWindow together?

**Comment by etvorun** [comment]
Proposed RenderAsXxx API should return 100% self-describing image data. For example, it should include image width, height, format details (e.g. 24-bit bitmap vs 32-bit bitmap; stride, etc.).
