### ISSUE TITLE
Docs don't show up in Intellisense for .NET MAUI types

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#5341]
### Description

Intellisense doc comments don't show up for any .NET MAUI types. Here's hovering over the `ContentPage` type in a new project:

![image](https://user-images.githubusercontent.com/202643/158635533-71435282-8258-411d-a9b5-813d3f406d78.png)

Yet, we have correct docs defined in the source code:

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/ContentPage.cs#L3

This is presumably because the XML files that contain the docs are not generated or included in the NUPKGs even though we have docs defined.

Note that for the BlazorWebView types we do have doc XML files generated and those work in Intellisense:

![image](https://user-images.githubusercontent.com/202643/158636664-d7dcb7fd-a7a0-419f-bfcd-9157987996c7.png)

For these Blazor types it is achieved by setting `<GenerateDocumentationFile>true</GenerateDocumentationFile>` in each `.csproj` file:

https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Wpf/Microsoft.AspNetCore.Components.WebView.Wpf.csproj#L13

So perhaps we should do the same for .NET MAUI so that the doc XML files are included in the NUPKGs. This seems similar to what was done in Xamarin.Forms, where the doc XML files were also in the NUPKGs:

![image](https://user-images.githubusercontent.com/202643/158637123-24df6a5b-fa27-4427-a3fa-bd07c8cca022.png)

### Steps to Reproduce

1. Create any new .NET MAUI project (app, Blazor app, lib, etc.)
2. Hover the mouse over any .NET MAUI type, such as `ContentPage`, or anything else

The type info is shown, but doc comments don't show up, even though they are defined in the source code.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

No.

**Comment by v-longmin** [comment]
Verified the issue on 17.2.0 preview3.0 main\32315391. It's still repro. repro project: ["\\\mlangfs1\Public\dotnet maui\Repro Project\5341.zip"](url)

**Comment by Eilon** [comment]
This is now partially fixed in https://github.com/dotnet/maui/pull/6874.

Anyone wishing to continue this for other assemblies can follow the same pattern as seen in that PR.

**Comment by Eilon** [comment]
Confirmed this works in MAUI GA 6.0 that shipped this morning:

![image](https://user-images.githubusercontent.com/202643/169878763-154c90c3-a2df-48e9-8a73-2b3dac53b9d3.png)

**Comment by jfversluis** [comment]
Thanks Eilon! I'll be taking this up as part of #3960 for the rest. Let me know if you identify some more types where you don't see anything.
