### ISSUE TITLE
bad grid layout in a stack

### ISSUE THREAD

**Issue by ialbert-AUT** [dotnet/maui#5344]
### Description

I have a simple StackLayout and a Grid:
```csharp
Content = new StackLayout
{
	Children = {
		new Grid()
		{
			ColumnDefinitions = Columns.Define(GridLength.Star, GridLength.Auto),
			RowDefinitions = Rows.Define(30),
				Children =
				{
					new Label() {Text = "hello" }.Column(0),
					new Image() {Source="drink.png"}.Column(1)
				}
		}
	}
};
```
On startup the image is not seen just the text.
![image](https://user-images.githubusercontent.com/61751571/158646218-95fbea5b-2517-458e-bf76-fb1551d82b42.png)

When I resize the window the text disappears and I can see only the image.
![image](https://user-images.githubusercontent.com/61751571/158646350-0f7eda9d-4d95-456e-9c3f-bf4ab5fb366e.png)

 

### Steps to Reproduce
```csharp
Content = new StackLayout
{
	Children = {
		new Grid()
		{
			ColumnDefinitions = Columns.Define(GridLength.Star, GridLength.Auto),
			RowDefinitions = Rows.Define(30),
				Children =
				{
					new Label() {Text = "hello" }.Column(0),
					new Image() {Source="drink.png"}.Column(1)
				}
		}
	}
};
```
add an image, 128x128

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by v-longmin** [comment]
@ialbert-AUT Could you share your repro project/solution, thanks?

**Comment by shimingsg** [comment]
verified repro with vs 17.2.0 Preview 3.0 [32317.292.main] on windows:
![5344](https://user-images.githubusercontent.com/20982341/158949705-08adb606-4283-460a-b1bc-8b2504316cdc.gif)
repro code snippet:
```
<StackLayout>
            <Grid ColumnDefinitions="*,auto"
                  RowDefinitions="30">
                <Label Grid.Row="0" Grid.Column="0" Text="Hello"></Label>
                <Image Grid.Column="1" Grid.Row="0" Source="dotnet_bot.png"></Image>
            </Grid>
        </StackLayout>
```
