### ISSUE TITLE
Run MAUI project on Physical Device (iPhone-Mac) 

### ISSUE THREAD

**Issue by aokocax** [dotnet/maui#5349]
### Description

I'm trying to build the MAUI project on my own iphone but I'm getting this error on my Mac.

`dotnet build -t:Run -f net6.0-ios -p:_DeviceName=daf03e99***myiphonedeviceid`

XEC : error MT1212: Failed to create a simulator where type = iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s) and runtime = iOS 15.4 (15.4 - 19E240) - com.apple.CoreSimulator.SimRuntime.iOS-15-4. [/Users/**/Desktop/prev/fizikt/fizikt.csproj]

I tried with 13.3 and earlier xcode version but it gives the same error. My iOS version is 15.4. I tried with 15.3 but it didn't change.

### Steps to Reproduce

1. Create MAUI project
2. Run on the Physical device

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

15.3, 15.4

### Relevant log output

```shell
EXEC : error MT1212: Failed to create a simulator where type = iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s) and runtime = iOS 15.4 (15.4 - 19E240) - com.apple.CoreSimulator.SimRuntime.iOS-15-4. [/Users/***/Desktop/prev/fizikt/fizikt.csproj]
/usr/local/share/dotnet/sdk/6.0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(897,5): error MSB3073: The command "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.2.301-preview.13.7/tools/bin/mlaunch --launchsim bin/Debug/net6.0-ios/iossimulator-x64/fizikt.app/ --device daf03e*** --stdout /dev/ttys000 --stderr /dev/ttys000 --wait-for-exit" exited with code 1. [/Users/**/Desktop/prev/fizikt/fizikt.csproj]
```

**Comment by aokocax** [comment]
Fixed
I added "-c Release" and worked.
`dotnet build -t:Run -f net6.0-ios -p:_DeviceName=daf03e99***myiphonedeviceid -c Release`

**Comment by RajuGadda** [comment]
Above command with -c release did not work for my physical device iPhone 6 Plus with software version 12.5.5 kindly help with workaround 
template used is .net maui Blazor in IDE VS 2022 17.1.0 PREVIEW for MAC 

error MT1212: Failed to create a simulator where type = iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s) and runtime = iOS 15.4 (15.4 - 19E240) - com.apple.CoreSimulator.SimRuntime.iOS-15-4.
