### ISSUE TITLE
VS2022 Version 17.2.0 Preview 2.0 Unable to pair to Mac

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#5354]
### Description

I know this isn't a Maui bug, but VS2022 Version 17.2.0 Preview 2.0 Unable to pair to Mac has just been released and we can no longer pair to a Mac. The error shown in the pairing dialog:

Disconnected
The Xcode license status couldn't be verified because Xcode has not been found on the default location of the connected Mac. Having Xcode installed and functional is necessary in order to build and run iOS apps, so please check that Xcode is correctly installed and that the path specified under iOS Settings is correct.

### Steps to Reproduce

Install 17.2.0 Preview 2.0 Unable to pair to Mac
Attempt to pair to Mac

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 13 (current)

### Affected platforms

Windows

### Affected platform versions

Windows, don't know which

### Did you find any workaround?

Reverting back to preview 13/VS2022 preview 1 works.

**Comment by v-longmin** [comment]
Verified the issue on vs 2022 17.2.0 preview3.0 Main\32315.391, it's not repro, thanks.

**Comment by JohnHDev** [comment]
> Verified the issue on VS 2022 17.2 preview3 Main\32315.391, it is not repro, thanks.

Just to clarify, you are saying you cannot replicate in preview 3?
If so, when replying to people can I suggest you write the following instead:

> Attempted to verify the issue on VS 2022 17.2 preview3 Main\32315.391, it is not reproducible, thanks.

preview2 is only just out, are we able to access preview3?

Lastly I see you closed the issue, and then reopened? Have you now been able to replicate?

**Comment by jfversluis** [comment]
@JohnHDev reproduction happens on the latest (internal) version. It might already been fixed between previews that haven't been released yet, that's why there is a "mismatch" between these version numbers. Just to be complete: no, preview 3 is not publicly accessible yet.

Could you verify that Xcode is indeed installed and updated to the latest version and the license agreement has been accepted? The latter can be checked by starting Xcode and if no license agreement comes up, all is fine. 

Lastly, what does it say when you execute `xcode-select -p`? (on your Mac)

If it shows something unexpected, you should be able to change it with `sudo xcode-select -s /Applications/Xcode.app`

**Comment by JohnHDev** [comment]
@jfversluis I reverted to a clean VM and installed VS2022 preview 2 from scratch, and it can pair to the Mac successfully.
I am unable to build for iOS simulators however, getting the following error:


Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | /usr/bin/codesign exited with code 1 | MauiApp1 | C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\tools\msbuild\iOS\Xamarin.Shared.targets | 2095 |  


<br class="Apple-interchange-newline">

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | /usr/bin/codesign exited with code 1 | MauiApp1 | C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\tools\msbuild\iOS\Xamarin.Shared.targets | 2095 |  


<br class="Apple-interchange-newline">


Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | Failed to codesign '/Users/johnhair/Library/Caches/Xamarin/mtbs/builds/MauiApp1/7b47a969790e97ad50a73b33131aad68aa1934c455487e095bc22a556c079b60/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp1.app/libSystem.Security.Cryptography.Native.Apple.dylib': /Users/johnhair/Library/Caches/Xamarin/mtbs/builds/MauiApp1/7b47a969790e97ad50a73b33131aad68aa1934c455487e095bc22a556c079b60/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp1.app/libSystem.Security.Cryptography.Native.Apple.dylib: replacing existing signature/Users/johnhair/Library/Caches/Xamarin/mtbs/builds/MauiApp1/7b47a969790e97ad50a73b33131aad68aa1934c455487e095bc22a556c079b60/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp1.app/libSystem.Security.Cryptography.Native.Apple.dylib: cannot find code object on disk | MauiApp1 | C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\tools\msbuild\iOS\Xamarin.Shared.targets | 2095 |  


<br class="Apple-interchange-newline">

On the Mac host I can and am running XF apps on the iOS simulators without requiring code sign.

**Comment by nextfool** [comment]
Hi, I am facing a similar issue, when I try to pair a new mac,  there is an error:
![image](https://user-images.githubusercontent.com/2167369/158917776-0e8a79df-4af0-42ef-bf4d-9f7486ad8f18.png)

**Comment by xtuzy** [comment]
Last friday i update VisualStudio to **Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.2.0 Preview 2.0**, today i open net6.0-ios project, all can't build. 

**Error:**
`error : /usr/bin/codesign exited with code 1`
`error : Failed to codesign `

**Build Output:**
[Output-Build.txt](https://github.com/dotnet/maui/files/8311368/Output-Build.txt)

**Comment by xtuzy** [comment]
Another, my Xamarin.iOS project all can build success. so i feel it is a bug of 17.2.0 Preview 2.0

**Comment by xtuzy** [comment]
I try to update Certification according to 
https://stackoverflow.com/a/69067547/13254773 and https://developercommunity.visualstudio.com/t/Cant-upload-archive-to-apple-app-store/1359685
No luck.

**Comment by Redth** [comment]
This will be fixed in an upcoming servicing release of 17.2 Preview 2.0.
