### ISSUE TITLE
[Windows/Android] Preview 14 Editor does not resize automatically

### ISSUE THREAD

**Issue by emceelovin** [dotnet/maui#5363]
### Description

Editor inside of an Auto Grid row/column will not auto resize once text is overflowed horizontally. To get an Editor to resize, you have to manually trigger a layout resize by resizing the main window, navigating to and from current page, etc. Also, removing the AutoSize attribute from Editor causes all hell to break loose inside the page.

On Android, Editor will resize, but it takes a second. to resize. Literally.

### Steps to Reproduce

Place an editor inside of a grid like so(feel free to criticize the code. It could be my fault.):

```xaml
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="*"/>
        <RowDefinition Height="Auto"/>
    </Grid.RowDefinitions>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="05*"/>
        <ColumnDefinition Width="90*"/>
        <ColumnDefinition Width="05*"/>
    </Grid.ColumnDefinitions>
    <ScrollView
        Grid.Row="0"
        Orientation="Vertical">
        <ListView
            x:Name="_chatListView"
            Background="#1d1e1f">
        </ListView>
    </ScrollView>
    <Editor
        Grid.Row="1"
        AutoSize="TextChanges"
        Grid.Column="1"
        Keyboard="Chat"
        x:Name="_chatInput"
        Margin="12, 12, 12, 12"
        Placeholder="Type a message..."
        Text="{Binding Message}"
        Background="#303135"/>
</Grid>
```

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Preview 14 Windows/Android

**Comment by XamlTest** [comment]
Verified repro on Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main]. Repro Project: [5363.zip](https://github.com/dotnet/maui/files/8282561/5363.zip)
