### ISSUE TITLE
Wrapping Layout in a `Frame` breaks controls 

### ISSUE THREAD

**Issue by nor0x** [dotnet/maui#5365]
### Description

I have started with a `dotnet new maui` and wrapped the whole content of the `ContentPage` in a `Frame` layout (to achieve corner radius). If i start increasing the counter the label becomes invisible. Only if i resize the window (which updates the bounds of the frame) the label appears back on the screen.

This of course doesn't happen if there is no `Frame` around the `Grid` 

https://user-images.githubusercontent.com/3210391/158775278-35f8f55f-02a8-4f36-bed5-2c3864eb6cef.mp4

### Steps to Reproduce

1. Create new MAUI app (Preview 14)
2. Replace the `ScrollView` with `Frame`
3. Click the Click Me button

Repro Project:
[repro.zip](https://github.com/dotnet/maui/files/8283213/repro.zip)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

**Comment by XamlTest** [comment]
Verified on Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main]. Repro on Windows, not repro on Android and iOS. Repro Project: [5365.zip](https://github.com/dotnet/maui/files/8283465/5365.zip)

**Comment by jsuarezruiz** [comment]
The Frame is not adjusting its size as the window size changes.

**Comment by nor0x** [comment]
thanks for the reply @jsuarezruiz! is the frame size causing the `Label` to be rendered invisible?

**Comment by VSadov** [comment]
tried with recent main - the border renders after button is clicked.
Possibly fixed by https://github.com/dotnet/maui/pull/5324
