### ISSUE TITLE
ItemDisplayBinding Property not working in Window

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#5370]
### Description

<Picker Title="Select a monkey"
        ItemsSource="{Binding Monkeys}"
        ItemDisplayBinding="{Binding Name}" />

### Steps to Reproduce

<Picker Title="Select a monkey"
        ItemsSource="{Binding Monkeys}"
        ItemDisplayBinding="{Binding Name}" />

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

Windows

### Affected platform versions

vvv

### Did you find any workaround?

..

### Relevant log output

```shell
..
```

**Comment by jfversluis** [comment]
Without any relevant in the template we can't accept this bug report. Please add relevant info or open a new issue with the requested information.

**Comment by danies8** [comment]
Look on this sample code from link:
https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/picker
section:Populate a Picker with data using data binding
ItemDisplayBinding Property not working in Window
