### ISSUE TITLE
Compile errors when adding UseMaui to WinUI desktop project

### ISSUE THREAD

**Issue by sparkie108** [dotnet/maui#5372]
### Description

I was trying to see if I could get native embedding to work with WinUI based on [#5218](https://github.com/dotnet/maui/pull/5218) but ran into problems at the first step of adding UseMaui to the project file. On compiling there was an error indicating that InitializeComponent is already defined, seemingly by both WinUI and MAUI.

Having to put any MAUI XML into a separate class library to any WInUI XML would be fine.

Also relevant to [#1718](https://github.com/dotnet/maui/issues/1718).

### Steps to Reproduce

1. Create a new "Blank App. Packaged (WinUI 3 in Desktop)" project  in VS
2. Add the following to the project file:
``` xml
<PropertyGroup>
    <UseMaui>true</UseMaui>
</PropertyGroup>
```
3. Compile the project

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

VisualStudio.17.Preview/17.2.0-pre.2.0+32314.265; Microsoft.WindowsAppSDK 1.0.0; Microsoft.Windows.SDK.BuildTools 10.0.22000.194;

### Did you find any workaround?

No

### Relevant log output

```shell
..\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\App.xaml.sg.cs(20,16,20,35): error CS0111: Type 'App' already defines a member called 'InitializeComponent' with the same parameter types
..\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\MainWindow.xaml.sg.cs(24,16,24,35): error CS0111: Type 'MainWindow' already defines a member called 'InitializeComponent' with the same parameter types
```

**Comment by jfversluis** [comment]
Would you be able to add a reproduction project for this? That would probably help speed up to see what is happening here. Thanks!

**Comment by sparkie108** [comment]
I have created:
https://github.com/sparkie108/WinUIMauiEmbeddingIssue

**Comment by PineYi** [comment]
Reproduce in Windows with above project.
![image](https://user-images.githubusercontent.com/99375367/158920382-d4e6c715-6c73-493b-9927-c93bd9411837.png)

**Comment by matteo-prosperi** [comment]
I am experiencing the same when adding `<UseMaui>true</UseMaui>` to a WPF app (the empty app created by the VS project template).

**Comment by rmarinho** [comment]
Can you try setting..

```
<EnableDefaultXamlItems>false</EnableDefaultXamlItems>
```

**Comment by sparkie108** [comment]
Thanks that worked!

I have created an example here:
https://github.com/sparkie108/MauiWinUIEmbedding

If the docs are updated I think this issue can be closed.

**Comment by davidbritch** [comment]
Native embedding is doc'd at https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/native-embedding?view=net-maui-7.0 so I think this can be closed (@jfversluis).

**Comment by sparkie108** [comment]
The bit that needs documenting is having to add to your Windows project:
``
<EnableDefaultXamlItems>false</EnableDefaultXamlItems>
``
which is still not mentioned in the embedding doc.

**Comment by davidbritch** [comment]
Hi @sparkie108 

Agreed. I've created an issue in the docs repo to track this: https://github.com/dotnet/docs-maui/issues/1259
