### ISSUE TITLE
BackgroundColor not changed

### ISSUE THREAD

**Issue by MartyIX** [dotnet/maui#5380]
### Description

I have created a new MAUI project (preview 14) and I have modified (created) the following three files:

`MainPage.xaml`:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiAppRelativeSource.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">

    <ScrollView>
        <Grid RowSpacing="25" RowDefinitions="Auto,Auto,Auto,Auto,*"
              Padding="{OnPlatform iOS='30,60,30,30', Default='30'}">

            <Label 
                Text="{Binding IsGreen}"
                Grid.Row="0"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />

            <Entry Text="" Grid.Row="1">
                <Entry.Triggers>
                    <DataTrigger TargetType="Entry"
                                 Binding="{Binding Path=IsGreen}"
                                 Value="False">
                        <Setter Property="BackgroundColor" Value="Red" />
                    </DataTrigger>
                    <DataTrigger TargetType="Entry"
                                 Binding="{Binding Path=IsGreen}"
                                 Value="True">
                        <Setter Property="BackgroundColor" Value="Green" />
                    </DataTrigger>
                </Entry.Triggers>
            </Entry>

            <Button 
                Text="Click me"
                FontAttributes="Bold"
                Grid.Row="3"
                Command="{Binding ChangeColorCommand}"
                HorizontalOptions="Center" />
        </Grid>
    </ScrollView>
</ContentPage>
```

`MainPageViewModel.cs` (added to the project)

```cs
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MauiAppRelativeSource.ViewModels;

internal class MainPageViewModel : INotifyPropertyChanged
{
    public bool isGreen { get; set; }

    public bool IsGreen
    {
        get
        {
            return isGreen;
        }
        set
        {
            isGreen = value;
            OnPropertyChanged();
        }
    }

    public Command ChangeColorCommand { get; }

    public MainPageViewModel()
    {
        ChangeColorCommand = new Command(() => {
            IsGreen = !IsGreen;
        });
    }

    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        PropertyChangedEventHandler handler = PropertyChanged;
        if (handler != null)
            handler(this, new PropertyChangedEventArgs(propertyName));
    }
}
```

`MainPage.xaml.cs`:

```cs
using MauiAppRelativeSource.ViewModels;

namespace MauiAppRelativeSource;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();

		// Intentionally assigned here. In my app, the view model is obtained using DI.
		this.BindingContext = new MainPageViewModel();
	}
}
```

### Steps to Reproduce

1. Run the attached app: [MauiAppRelativeSource.zip](https://github.com/dotnet/maui/files/8284797/MauiAppRelativeSource.zip)
1. Click the `Click me` button
1. `<Entry>` should be green, it's red

    ![image](https://user-images.githubusercontent.com/203266/158805975-b65e9d36-d4e6-4456-ac89-0b517f60d282.png)

Some sort of https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/relative-bindings has to be added but I tried many options and I failed every single time.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No.

**Comment by Amir-Care** [comment]
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main] on Windows.
Sample project:  [#5380.zip](https://github.com/dotnet/maui/files/8298109/5380.zip)

**Comment by MartyIX** [comment]
Is there possibly any workaround for this issue please?

**Comment by shimingsg** [comment]
@MartyIX , try below, Entry in <Frame> works, set Entry's backgroundcoler = Transparent
```
<Frame Grid.Row="1">
    <Frame.Style>
        <Style TargetType="Frame">
            <Setter Property="BackgroundColor" Value="Green" />
            <Style.Triggers>
                <DataTrigger
                    Binding="{Binding IsGreen}"
                    Value="false"
                    TargetType="Frame">
                    <Setter Property="BackgroundColor" Value="Red" />
                </DataTrigger>
            </Style.Triggers>
        </Style>
    </Frame.Style>
    <Entry BackgroundColor="Transparent" Text="yyyyy" />
</Frame>
```

**Comment by MartyIX** [comment]
@shimingsg Interesting idea. Thank you for sharing it!

It would still be great if the original issue were fixed (unless I'm doing something wrong). @Redth Is there anything I can do to help move this forward?

**Comment by StephaneDelcroix** [comment]
I don't see how this is related to {RelativeBinding}... but it could be linked to some other issues related to Color/Brush

**Comment by StephaneDelcroix** [comment]
the `BackgroundColor` property Is correctly set, but the background isn't updated. @mattleibow does this ring a bell ?

**Comment by StephaneDelcroix** [comment]
see #6372

**Comment by Redth** [comment]
On main the background color indeed does not work correctly for an Entry on Windows.

**Comment by SteveJML** [comment]
Same for Android, Entry background colors are ignored.

**Comment by NeerajRai111** [comment]
It was working in earlier version but now it is not working. Please fix it.

**Comment by jamesmontemagno** [comment]
I am seeing that on iOS/MacOS App theme bindings are not takign effect on the active page @Redth  the workshop is an example here and even file -> new template. It seems like it works on Android fine and I saw it was fixed on Windows in GA build

**Comment by dawiseguy55** [comment]
Thanks guys for fixing this! Just updated my RC3 using the Visual Installer and BackgroundColor seems to work as normal. 

BTW I noticed I can call this now in the initializer of a ContentPage:

var iView = this as IView;
iView.Background.BackgroundColor = Colors.Red;

It doesn't actually update the view however, I thought maybe it would work since @mattleibow mentioned that it is now an IView. I'm just curious about IView. 

Is there any insight on what the proper attribute will be to set the BackgroundColor of a ContentPage upon release?

**Comment by mattleibow** [comment]
@dawiseguy55 the more modern way is the `Background` property on the `View`.

**Comment by ShiiikK** [comment]
Does anyone know when this will be fixed?
