### ISSUE TITLE
Command bound with MenuFlyoutItem is not getting executed, whereas Clicked event is working fine

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#5382]
### Description

Defined a Menu structure in a Content page and added Command to the MenuFlyoutItem, but the Command is not getting executed when invoked. Whereas Clicked event is working fine.

Note: BindingContext is set to the instance of the ViewModel type.

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Add the menu structure to the ContentPage as shown below
3. Define a ViewModel with a Command in it
4. Bound the MenuFlyoutItem to the Command in the ViewModel
5. Set the BindingContext of the ContentPage to the instance of the ViewModel
6. Update the Application MainPage to a NavigationPage containing this ContentPage
7. Build and run the project on any of the supported target platforms (have tried with Android and Windows)
8. Invoke the  menu to trigger the Command, but it's not getting executed

```xml
<ContentPage.MenuBarItems>
    <MenuBarItem Text="File">
        <MenuFlyoutItem Command="{Binding TestCommand}" Text="Test" />
    </MenuBarItem>
</ContentPage.MenuBarItems>
```
App.xaml.cs
```cs
MainPage = new NavigationPage(new MainPage());
```

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 31.0, Windows SDK 10.0.19041

### Did you find any workaround?

Nope (For now Clicked event works fine, executing the command method from there).

### Relevant log output

```shell
NA
```

**Comment by jfversluis** [comment]
Yeah this probably has to do with the BindingContext not being passed on to the menuitems. As a workaround you can set the binding context on that manually for now, then it should work.

**Comment by shimingsg** [comment]
verified repro with VS 17.2.0 Preview 3.0 [32321.361.main] on Windows, Invoke the menu to trigger the Command, it's not getting executed, but if button trigger the command it is getting executed.
attached demo: 
[MauiApp5382.zip](https://github.com/dotnet/maui/files/8320504/MauiApp5382.zip)

**Comment by banditoth** [comment]
Workaround until this issue is fixed:

```
<ContentPage
.....
    x:Name="this">
    <ContentPage.MenuBarItems>
        <MenuBarItem Text="File" BindingContext="{Binding Path=BindingContext, Source={x:Reference this}}">
.....

```


Menu flyoutitems are getting the bindingcontext of menubaritems, so its enough to set the Binding context for MenuBarItem :)

**Comment by kristinx0211** [comment]
still can be reproduced on windows with vs 17.3.0 Preview 2.0 [32506.368.main], Invoke the menu to trigger the Command, it's not getting executed, but if button trigger the command it is getting executed.

**Comment by banditoth** [comment]
> I tried the method above by @banditoth and it give me an error stating:
> 
> Microsoft.Maui.Controls.Xaml.XamlParseException: 'Position 26:34. Can not find the object referenced by `this`'
> 
> 
> 
> So I tried the method below but it still doesn't call my command. This is my attempt at what @jfversluis mentioned above
> 
> 
> 
> `<MenuBarItem Text="File" BindingContext="{Binding Source={RelativeSource AncestorType={x:Type Shell}}, Path=BindingContext}">
> 
>             <MenuFlyoutItem Text="Exit" Command="{Binding ExitCMD}"/>
> 
>         </MenuBarItem>`
> 
> 
> 
> Anyone have other ideas on how I can hook up the BindingContext?

Hey,

Did you named your ContentPage instance with x:Name attribute?

**Comment by cfoster7023** [comment]
Aha, I missed that in your code.  I put the below code in and it worked! (the x:Name="TopShell" is what I added to the "Shell" tag)

`<Shell x:Name="TopShell"
 .....
>`

The binding now looks like:
`        <MenuBarItem Text="Help" BindingContext="{Binding Path=BindingContext, Source={x:Reference TopShell}}">
            <MenuFlyoutItem Text="About" Command="{Binding AboutCMD}"/>
        </MenuBarItem>`

Thanks so much!!

I still wonder why my RelativeSource binding didn't work....?

**Comment by jeff922** [comment]
I see this issue has been closed, but I am still seeing the issue with .NET 7.0.100-rc.2.22477.23 and Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.4.0 Preview 3.0.  The workaround above works, but if this is closed, should the example work without the workaround?

For example, I would expect the DoSomethingCommand to run below, but it only works if I modify the code below to use the workaround.

NON WORKING EXAMPLE
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:viewmodels="clr-namespace:MauiApp1.ViewModel"
             x:Class="MauiApp1.MainPage"
             x:DataType="viewmodels:MainPageViewModel"
             x:Name="thisMenuBarWorkaround">
    
    <ContentPage.BindingContext>
        <viewmodels:MainPageViewModel/>
    </ContentPage.BindingContext>

    <ContentPage.MenuBarItems>
        <MenuBarItem Text="File">
            <MenuFlyoutSubItem Text="Open">
                <MenuFlyoutItem Text="Open Do Something..."
                                Command="{Binding DoSomethingCommand}"/>
                
            </MenuFlyoutSubItem>
        </MenuBarItem>
    </ContentPage.MenuBarItems>
</ContentPage>`

WORKING EXAMPLE USING WORKAROUND
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:viewmodels="clr-namespace:MauiApp1.ViewModel"
             x:Class="MauiApp1.MainPage"
             x:DataType="viewmodels:MainPageViewModel"
             x:Name="thisMenuBarWorkaround">
    
    <ContentPage.BindingContext>
        <viewmodels:MainPageViewModel/>
    </ContentPage.BindingContext>

    <ContentPage.MenuBarItems>
        
        <MenuBarItem Text="File"
                     BindingContext="{Binding Path=BindingContext,
                                              Source={x:Reference thisMenuBarWorkaround}}">
            <MenuFlyoutSubItem Text="Open">
                <MenuFlyoutItem Text="Open Do Something..."
                                Command="{Binding DoSomethingCommand}"/>
                
            </MenuFlyoutSubItem>
        </MenuBarItem>
    </ContentPage.MenuBarItems>
</ContentPage>`

VIEWMODEL
```
using CommunityToolkit.Mvvm.Input;

namespace MauiApp1.ViewModel;

public partial class MainPageViewModel
{
    [RelayCommand]
    public static void DoSomething()
    {
        // This point is never hit without workaround
        return;
    }

```

**Comment by cdavidyoung** [comment]
This workaround fixed my problem as well.  I am Binding the MenuFlyoutItem Text and although the menu items Clicked were working they were blank.  The workaround allowed the text to show up.

<ContentPage ...
             x:Name="this">
    <ContentPage.BindingContext>
        <local:ViewModels.RecordsViewModel />
    </ContentPage.BindingContext>

    <ContentPage.MenuBarItems>
        <MenuBarItem Text="📁File" BindingContext=" {Binding Path=BindingContext, Source={x:Reference this}}">
          <MenuFlyoutItem Text="{Binding msgSave}"
                          Clicked="MenuBarItem_Clicked_Save" />
          <MenuFlyoutItem Text="{Binding msgLoad}"
                          Clicked="MenuBarItem_Clicked_Load" />
          <MenuFlyoutItem Text="{Binding msgImages}"
                          Clicked="MenuBarItem_Clicked_Images" />
          <MenuFlyoutItem Text="{Binding msgHelp}"
                          Clicked="MenuBarItem_Clicked_Help" />
        </MenuBarItem>
    </ContentPage.MenuBarItems>

**Comment by michaelrinderle** [comment]
The current solution does not work for people using a view model with dependency injection. Xaml complains about not having a parameter-less constructor.
