### ISSUE TITLE
RCL Hybrid App _component dosnt load on windows/android platform 

### ISSUE THREAD

**Issue by DidgetMidget** [dotnet/maui#5392]
### Description

Tried building a web and maui app with the same razor class libaray as code base. 

wwwroot from the RCL was not accessible inside the index.html so no css loaded: 
used for the css:"_content/RazorLib/wwwroot/css/bootstrap/bootstrap.min.css"

And the RCL dosnt got the "UseMaui" tag 

[Testproject](https://github.com/DidgetMidget/MauiBlazorTest)

### Steps to Reproduce

1. Create new project
2. Add a Maui Blazor Project
3. Add a RCL
4. Add a Blazor App 
5. Add the nessessary AspNetCore package references to the RCL 
6. Move Folder: Data & Pages & Shared & wwwroot and _import.razor & App.razor to the RCL from the Blazor App 
7. Add any missing assemblys to the RCL 
8. Add reference to the RCL from both Blazor and Maui app
9. Delete Data & Pages & Shared from the Maui Project and Blazor App if you didnt at step 6
10. Modify the Main.razor inside the Maui Project and direkt the MainLayout to the RCL
11. the wwwroot folder inside the maui project contains a html file try to change out the css links and direct them to the RCL wwwroot onces

Instead of doing all that use my provided Projectfile instead :P 

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 14 (current)

### Affected platforms

Android, Windows

### Affected platform versions

Android11 , Windows

### Did you find any workaround?

Just dont use a RCL for the CSS and keep the CSS inside the MAUI Project and use that css file for the Blazor App 
but that would defeat the whole point of hybrid app that is separated into different project files for readability

**Comment by DidgetMidget** [comment]
Okay did some more testing and it seems like it dosnt like beeing nested that deeply 

Works:
"_content/RazorLib/site.css"
"_content/RazorLib/css/bootstrap/bootstrap.min.cs"

Dosnt Work:
"_content/RazorLib/testfiles/site.css"
"_content/RazorLib/testfiles/css/bootstrap/bootstrap.min.cs"

Adding a single folder breaks it and yeah i tried all different kinds of "include" inside the project file with updates and stuff
tried:
<Content include=""/>
<None Include=""/>
<None Update=""/>
^  With just the files itself the whole folder structure parts of the folder structure just every variation there is

**Comment by DidgetMidget** [comment]
![image](https://user-images.githubusercontent.com/54773103/158899616-181aabe2-fc0e-4bf0-8ae5-99e8478164ad.png)
Yeah even more testing the "_content" path is broken af really needs to be look into

**Comment by javiercn** [comment]
@DidgetMidget thanks for contacting us.

Referencing a Razor Class Library with MVC views and Razor Pages (cshtml) from a Maui application is not a supported scenario. Your Razor Class Library must only contain component files and have a framework reference to ASP.NET Core

**Comment by DidgetMidget** [comment]
Sad that you cant just having them laying around inside of the RCL because i am not using them inside of that MAUI Project just left from a hasty copy and paste from the normal Blazor Web APP so if i understood it corectly that MVC support thingy inside my RCL breaks the MAUI end is that right?
