### ISSUE TITLE
Radio button group attacahed property not working in complex layout

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#5393]
### Description

See :https://github.com/dotnet/maui/issues/new?assignees=&labels=t%2Fbug%2Cs%2Fneeds-verification&template=bug-report.yml

### Steps to Reproduce

https://github.com/dotnet/maui/issues/new?assignees=&labels=t%2Fbug%2Cs%2Fneeds-verification&template=bug-report.yml

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 14 (current)

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

no

### Relevant log output

```shell
no
```

**Comment by jfversluis** [comment]
Hey @danies8 this is the third issue today that doesn't have any detail on the issue and therefore I have to close it.

In the future please try to do better, this isn't great for anyone involved.

Thanks
