### ISSUE TITLE
Shell No longer displays correctly in Preview 14 on IPad

### ISSUE THREAD

**Issue by owaits** [dotnet/maui#5396]
### Description

In preview 13 the shell worked as I expected with the side menu and main content on an iPad but in Preview 14 its completely broken and displays the side menu full screen. 

It appears to be fine on Android both for phones and tablets, I don't have a way to test it on an iPhone but am trying to get someone else with and iPhone to look at it.

See screenshot of how it now looks on an iPad.

![IMG_0005](https://user-images.githubusercontent.com/13810266/158870433-082400a8-a802-4a08-8979-8d1cf756bdcc.PNG)

This is a screenshot from Preview 13 where the shell displayed correctly.

![IMG_0003](https://user-images.githubusercontent.com/13810266/158870474-bb761466-327c-4124-9d79-c4ac0e80a2db.PNG)

### Steps to Reproduce

Here is my menu xaml:

`<Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:windows="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.WindowsSpecific;assembly=Microsoft.Maui.Controls"
             xmlns:local="clr-namespace:WordAlive"
             xmlns:page="clr-namespace:WordAlive.Pages"
             x:Class="WordAlive.App"
             windows:Application.ImageDirectory="Assets">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary Source="Resources/Styles/DefaultTheme.xaml"/>
        </ResourceDictionary>
    </Application.Resources>

    <Application.MainPage>

        <Shell 
            FlyoutBehavior="{OnIdiom Phone=Flyout, Default=Locked}"
            FlyoutBackgroundColor="{StaticResource BackgroundDarkColor}"
            >

            <Shell.FlyoutHeader>
                <Grid BackgroundColor="{StaticResource BackgroundColor}" Padding="8">
                    <Label Text="Word Alive 2022" Style="{StaticResource TitleText}}"/>
                </Grid>                
            </Shell.FlyoutHeader>

            
            
            
            <FlyoutItem Title="Schedule" Icon="schedule_light.png">
                <Tab Title="Schedule" Icon="schedule_light.png">
                    <ShellContent  x:Name="GoHome" Title="By Day" ContentTemplate="{DataTemplate page:Sessions.DaysPage}"/>
                    <ShellContent Title="By Track" ContentTemplate="{DataTemplate page:Sessions.TracksPage}"/>
                    <ShellContent Title="By Speaker" ContentTemplate="{DataTemplate page:Speakers.SpeakerPage}"/>
                    <ShellContent Title="All" ContentTemplate="{DataTemplate page:Sessions.SessionsPage}"/>
                </Tab>
                
                <Tab Title="Favorites" Icon="favourite_light.png">
                    <ShellContent ContentTemplate="{DataTemplate page:Favorites.FavoritesPage}"/>
                </Tab>
            </FlyoutItem>
            <FlyoutItem Title="Event Guide" Icon="eventinfo_light.png" >
                <ShellContent Title="Info" Icon="timeout_light.png" ContentTemplate="{DataTemplate page:Event.InformationPage}"/>
                <ShellContent Title="Time Out" Icon="eventinfo_light.png" ContentTemplate="{DataTemplate page:Event.TimeOutPage}"/>
            </FlyoutItem>
            
            <FlyoutItem Title="Word Alive TV" Icon="tv_light.png">
                <ShellContent ContentTemplate="{DataTemplate page:TV.TVListingPage}"/>
            </FlyoutItem>
            <FlyoutItem Title="Kids and Youth" Icon="kids_light.png">
                <ShellContent ContentTemplate="{DataTemplate page:Kids.YouthAndChildrenPage}"/>
            </FlyoutItem>
            <FlyoutItem Title="Exhibitors" Icon="exhibitors_light.png" >
                <ShellContent ContentTemplate="{DataTemplate page:Exhibitors.ExhibitorPage}"/>
            </FlyoutItem>
            <MenuItem Text="Arrival Date" IconImageSource="settings_light.png" Command="{Binding SelectArrivalDate}"/>
            

            
            

            
        </Shell>
    </Application.MainPage>
</Application>
`

### Version with bug

Preview 14

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

iPadIOS 15

### Did you find any workaround?

NO

**Comment by jfversluis** [comment]
I see you mention preview 13 and preview 14 just was released as part of Visual Studio 2022 17.2 Preview 2. Did you actually mean preview 14? If not, could you try if preview 14 fixes it?

**Comment by pietie** [comment]
> Did you actually mean preview 14? If not, could you try if preview 14 fixes it?

Yeah I think he means preview 14. I have exactly the same issue after moving from 13 to 14. Works fine on Android but does the fullscreen thing on iOS.

**Comment by owaits** [comment]
Sorry for the confusion, yes I meant Preview 14. I have amended the bug for clarity.

**Comment by davidortinau** [comment]
This is also a problem on main (rc1) with MacCatalyst.

<img width="1059" alt="Screen Shot 2022-03-19 at 8 26 28 PM" src="https://user-images.githubusercontent.com/41873/159144149-27bb0ed7-65b1-4a6f-aed0-b3bd35068448.png">
