### ISSUE TITLE
Preview 14: Dependency Injection not working anymore

### ISSUE THREAD

**Issue by Phil4121** [dotnet/maui#5398]
### Description

Since I've updated my project from Maui Preview 13 to 14 it seems that Dependency Injection is not working any more when using it in combination with Shell Navigation.

With Preview 13 everything was working fine but since the update I got an error that there is no parameterless constructor for my startup page.
I also updated the Microsoft.Maui.Dependencies to 6.0.200-preview.14.5099

Anybody else suffer from this problem?

### Steps to Reproduce

Take a .Net Maui Project which implements Shell Navigation and uses Dependency Injection.
Update it to Prev. 14
Run it

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Please check the [Migration Guide to Preview 14](https://github.com/dotnet/maui/wiki/Migrating-to-Preview-14) in regards to Shell.

> In order to use constructor injection with ContentPages in the context of Shell, you'll need to register them with DI just like you have your view models.

Does that help?

**Comment by Phil4121** [comment]
works fine for me! Thank you!

**Comment by jfversluis** [comment]
Perfect! Thanks for letting us know!
