### ISSUE TITLE
[Bug] Fix fundamental measuring and layout issues

### ISSUE THREAD

**Issue by JohnH-FF** [dotnet/maui#54]
### Description
A Label in a grid that is contained in a StackLayout isn't measured correctly, with contents below the grid in the StackLayout overlapping the grid and label.

The original issue is here: https://github.com/xamarin/Xamarin.Forms/issues/8797

Create a new template XF solution.
Replace the MainPage xml with a new MainPage.cs
Replace the code with the following and fix the namespace accordingly:
`
using System;
using Xamarin.Forms;
using Xamarin.Forms.PlatformConfiguration;
using Xamarin.Forms.PlatformConfiguration.iOSSpecific;

namespace LabelSizeTest
{
public class MainPage : ContentPage
{
public MainPage()
{
On().SetUseSafeArea(true);

        var grid = new Grid();
        grid.ColumnDefinitions.Add(new ColumnDefinition() { Width = GridLength.Star });
        grid.ColumnDefinitions.Add(new ColumnDefinition() { Width = GridLength.Star });
        grid.ColumnDefinitions.Add(new ColumnDefinition() { Width = GridLength.Star });
        grid.ColumnDefinitions.Add(new ColumnDefinition() { Width = GridLength.Star });
        grid.ColumnDefinitions.Add(new ColumnDefinition() { Width = GridLength.Star });
        grid.ColumnDefinitions.Add(new ColumnDefinition() { Width = GridLength.Star });
        grid.ColumnDefinitions.Add(new ColumnDefinition() { Width = GridLength.Star });
        grid.RowDefinitions.Add(new RowDefinition() { Height = GridLength.Auto });

        var label = new Label();
        label.LineBreakMode = LineBreakMode.WordWrap;
        label.Text = "This is a test teest test 2nd 3rd last";

        grid.Children.Add(label, 1, 0);

        var stack = new StackLayout()
        {
            VerticalOptions = LayoutOptions.FillAndExpand,
            HorizontalOptions = LayoutOptions.FillAndExpand,
        };

        stack.Children.Add(new BoxView()
        {
            BackgroundColor = Color.Blue,
            HeightRequest = 50
        });

        stack.Children.Add(grid);

        stack.Children.Add(new BoxView()
        {
            BackgroundColor = Color.Blue,
            HeightRequest = 50
        });

        Content = stack;
    }
}
}
`
4. Run on the iPhone 11 Simulator.

Expected Behavior
Label should display correctly, with all the text visible.

Actual Behavior
Label is being partially obscured by the 2nd BoxView, the words 3rd and Last are replaced with the BoxView.

Basic Information
Version with issue:

Last known good version:

IDE: VS4Mac

Platform Target Frameworks:

iOS:
Nuget Packages: XF 4.2.0

Affected Devices: iOS and Android, as per the conversation in the original thread.

**Comment by charlesroddie** [comment]
@JohnH-FF I would suggest formatting the code here and in the issue this is copied from, and making the example minimal.

**Comment by dhindrik** [comment]
I think it is to early to start to move bugs from the Xamarin.Forms repository. Or what do you say @davidortinau?

**Comment by davidortinau** [comment]
Correct, let’s focus bugs on Xamarin.Forms please. 

AND I would love to see this topic turned into a proposal! We have discussed updating the layouts and this would be an ideal time to take on that effort.

**Comment by JohnH-FF** [comment]
It's in your hands @davidortinau :)
You have a massive opportunity here to do things properly, I hope you are aiming high and are not just going to fork and limp along with the existing design flaws.

**Comment by JohnH-FF** [comment]
@davidortinau actually were you asking me to create the proposal? Or has this been done already? Happy to help, but I was expecting issues like this would have already been on a list. ;)
