### ISSUE TITLE
[Question] Plans for "desktop-first" controls?

### ISSUE THREAD

**Issue by trympet** [dotnet/maui#542]
I attempted to rewrite my production WPF application to MAUI to get a taste of whats to come, since I have plans publish the application to macOS. Sadly, the takeaway from my experience was that MAUI is not the correct framework for me; the lack of desktop-class controls, such as DataGrid, GridView, context menus, etc. was a deal-breaker.

From what I can tell, MAUI will not bring any such desktop-like controls. Therefore, it seems that MAUI is a mobile UI framework, which happens to run on desktop :/

My question is: are there plans to add desktop-esc controls, such as DataGrid? Is writing desktop-only or desktop-first applications even a supported use case?

Is Blazor Desktop the project which I should focus my attention to instead? I know HTML5 has all the controls I need. If so, this is confusing, since, from what I recall, Microsoft itself said that Blazor Desktop is a mobile-first framework. Maybe Avalonia instead?

**Comment by yavor87** [comment]
From what I can see, there is a lot of effort to bring what has been done on Xamarin and Blazor on the desktop ([link](https://github.com/dotnet/core/issues/5423)). However, what dotnet desktop really needs is a great framework that is trully cross platform (macos, win, linux | x86, arm).

We shall see where MAUI goes, but for now, from what it seems, Avalonia is on the right track. If I am starting a new cross platform desktop app or migrating my WPF | UWP app to be cross platform, I go Avalonia.
