### ISSUE TITLE
DisplayAlert only fires once on TapGesture in ShellItem Page

### ISSUE THREAD

**Issue by ioiooi** [dotnet/maui#5425]
### Description

Hi,
  
when tapping the Label the Alert is only shown the very first time. On every subsequent tap the Alert does not pop up. Clicking on the button opens the DisplayAlert every single time. 

https://github.com/ioiooi/MAUITapGestureDisplayAlert
  
It worked in Preview 13. Every single time the label was tapped the Alert popped up.

### Steps to Reproduce

1. Run on Android - it doesn't matter whether it's a emulator or real device
2. Tap on the Label
3. Click away the alert
4. Tap on the Label again
5. No Alert

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

/

### Relevant log output

```shell
/
```

**Comment by jfversluis** [comment]
Does this _only_ show on Android? Or you didn't try other platforms?

**Comment by ioiooi** [comment]
Didn't try other platforms. Sry.

**Comment by kristinx0211** [comment]
@ioiooi  see the video if it is your expected result? not repro on Android 11 with above project. vs version: 17.2.0 Preview 2.0 [32301.586.main]
https://user-images.githubusercontent.com/99457000/159198677-537a2e33-fa06-4a7c-83c7-c2499c0d3130.mp4

**Comment by ioiooi** [comment]
@kristinx0211 That is not the behaviour I'm getting with that repository/solution.
  
Visual Studio Version 17.2.0 Preview 2.0
Android Emulator Pixel 5 API 30
  
The Alert is only shown once when tapping the label. It is shown every single time when tapping the button though. When starting the App and using the button first, the label does not show the Alert even once.
  
When I set a breakpoint here https://github.com/ioiooi/MAUITapGestureDisplayAlert/blob/main/TapGestureDisplayAlert/Pages/MainPage.xaml.cs#L20 it is never reached or called after the first time.
  
When I replace the DisplayAlert with a `Task.Delay(xxx)` it is however reached or called with every single tap and not only the first one.

**Comment by ioiooi** [comment]
Screen recording of the behaviour. You should be able to see the taps.

![untitled](https://user-images.githubusercontent.com/11210607/159241172-c76ca355-cc17-4255-9aad-d134910836ce.gif)

**Comment by jfversluis** [comment]
I've reproduced the behavior with the attached project. On Windows it does work as expected, so seems to be Android only
