### ISSUE TITLE
MAUI Blazor app how to disable scale and F12 dev tools?

### ISSUE THREAD

**Issue by ft9788501** [dotnet/maui#5431]
### Description

Is there any way to disable MAUI Blazor app F12 and scale? I can't find the option in 'BlazorWebView'.

### Public API Changes

BlazorWebView blazorWebView=new BlazorWebView();
blazorWebView.DisableScale=true;
blazorWebView.DisableDevTools=true;

Can provide the setting properties like this?

### Intended Use-Case

none

**Comment by jfversluis** [comment]
I think as part of #5059 developer tools are disabled by default and you can easily enable them by adding a service to your app.

Not sure what you mean by scaling, but I assume that is that you can zoom the web interface? We have fixed that in the newest default templates to be disabled. If that's not what you mean, please open a new issue with a bit more detailed information. Thank you!

**Comment by ft9788501** [comment]
> 

Yes, that is what I means, thanks.

**Comment by ft9788501** [comment]
> I think as part of #5059 developer tools are disabled by default and you can easily enable them by adding a service to your app.
> 
> Not sure what you mean by scaling, but I assume that is that you can zoom the web interface? We have fixed that in the newest default templates to be disabled. If that's not what you mean, please open a new issue with a bit more detailed information. Thank you!

![Animation](https://user-images.githubusercontent.com/29189410/160219670-fd7c98c7-81d2-4e1c-a489-55398539b75f.gif)

I already upgraded my vs2022 pre to 17.2.0 Preview 2.1. But also can reproduce this issue. Should I do any other step?

**Comment by jfversluis** [comment]
They will be released with the next version which is probably together with VS 17.2 Preview 3.

**Comment by ft9788501** [comment]
I already upgraded my vs2022 pre to 17.3, And now can hide the DevTools, But also can zoom the view through my mouse.
