### ISSUE TITLE
workload install maui failing when installing microsoft.maui.resizetizer.sdk

### ISSUE THREAD

**Issue by afucher** [dotnet/maui#5435]
### Description

When executing `sudo dotnet workload install maui --source https://api.nuget.org/v3/index.json` it is failing with `Downloading microsoft.maui.resizetizer.sdk version 6.0.200-preview.14.5099 failed`

```
> dotnet --version
6.0.201
```

### Steps to Reproduce

1. Run `sudo dotnet workload install maui --source https://api.nuget.org/v3/index.json`

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS 11.3.1 (20E241)

**Comment by kristinx0211** [comment]
repro meet the same error when installing from the command.

**Comment by jfversluis** [comment]
What happens if you use this command `sudo dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.14.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json`?

**Comment by Redth** [comment]
Please install with the latest Visual Studio 17.2 Preview

**Comment by afucher** [comment]
@jfversluis it worked, thanks. Maybe need to update instructions on https://github.com/dotnet/maui/wiki/macOS-Install ?

**Comment by afucher** [comment]
> Please install with the latest Visual Studio 17.2 Preview

How can I do this on my Mac?

**Comment by jfversluis** [comment]
> > Please install with the latest Visual Studio 17.2 Preview
> 
> How can I do this on my Mac?

You can't. I think he didn't notice this was about macOS :) VS for Mac is still in the works that should make this easier. Sorry for the confusion!
