### ISSUE TITLE
Data entry field tracking list has wrong BindingContext value

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5437]
### Description

When a CollectionView is bound to a list of items and an entry field is bound to a property of the selected item the correct information is shown in the entry field and it changes as the selection changes, all as expected. However if there's a method attached to the Unfocused event on the Entry it is called with the wrong BindingContext value (it looks like it may be the one inherited from the page rather than the selected item used to display the value)

### Steps to Reproduce

1. Unzip the attached project
2. Run it on Windows or Android
3. Select an item in the list to get the entry field prefilled
4. select the entry field and change it
5. select a different item, the value you entered should appear in the item previously selected, it won't
6. put a breakpoint at the end of Entry_Unfocused and repeat the test and you'll see the BindingContext value is not as expected (it will be a LineItemView not a LineItem)

Sample project:
[MAUIListEntry-Binding.zip](https://github.com/dotnet/maui/files/8308725/MAUIListEntry-Binding.zip)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows 10

**Comment by v-longmin** [comment]
Verified the issue on windows, it's repro.

**Comment by Redth** [comment]
The entry's bindingcontext in this sample project is never changed, so it is correctly set to that of its parent, which is in this case, `LineItemView`.  While you are setting the Entry's `Text` property to that of the `SelectedItem.ItemName` via the reference to `LineItemsListView`, this does not influence the binding context of the actual `Entry` itself.

**Comment by david-maw** [comment]
@Redth thanks, you're correct, that example is just not right, sorry. I must have screwed something up when I stripped down the original (a chunk of code embedded in a large Xamarin Forms application I'm experimentally migrating to MAUI). I'll go back to the original code and see if I can come up with a better test case - if I'm lucky the original problem I noticed on preview 14 has been fixed in the meantime.

**Comment by david-maw** [comment]
@Redth  well, that test turned out easier than I expected, it was a bug in the original code. It didn't work in Xamarin forms either, it's just that nobody had ever noticed. Thanks for your help debugging my code! Now, if someone will just implement #5596 I won't need to fix it 😉
