### ISSUE TITLE
Image takes more space than needed if RequiredWidth is not set

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#5438]
### Description

If RequiredHeight is set, and RequieredWidth is not set, image takes more space than needed.

It reproduces on Android, but works fine on Windows, and I wasn't able to test it on iOS/MacOS.

### Steps to Reproduce

Use the following page content:
```xaml
    <HorizontalStackLayout>
        <Label Text="Icon: "/>

        <Image HeightRequest="20" 
                     Source="https://cdn4.iconfinder.com/data/icons/web-ui-color/128/Compose-512.png" 
                     BackgroundColor="LightBlue"/>

        <Label Text=" edit"/>
    </HorizontalStackLayout>
```

Expected:
![image](https://user-images.githubusercontent.com/17177729/159121526-e8312f28-a530-4e85-98df-8c6060ee88ec.png)

Actual:
![image](https://user-images.githubusercontent.com/17177729/159121545-bce1cc1d-33b7-4b47-be44-83bee8cfe077.png)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

Set RequiredWidth.

**Comment by XamlTest** [comment]
Verified repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main] on Android 12. Repro Project: [5438.zip](https://github.com/dotnet/maui/files/8312627/5438.zip)

**Comment by hartez** [comment]
Actually, #7389 fixes this.
