### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component when Windows.Storage.Pickers is using

### ISSUE THREAD

**Issue by ty08husker** [dotnet/maui#5443]
### Description

When trying to implement a windows specific folder picker within Maui, following this stackoverflow answer ([link](https://stackoverflow.com/questions/70999773/folder-picker-net-maui). Running this code gives me this error:

Message:
Error HRESULT E_FAIL has been returned from a call to a COM component.

Stacktrace: 
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.Storage.Pickers.IFolderPickerMethods.PickSingleFolderAsync(IObjectReference _obj)
   at Windows.Storage.Pickers.FolderPicker.PickSingleFolderAsync()

### Steps to Reproduce

1. Create new Maui App
2. Following linked stackoverflow in description, add platform specific folder picker
3. ![image](https://user-images.githubusercontent.com/101937716/159126333-3eed90fc-7638-4013-a4b9-0fa82e47b1cb.png)
4. Execute
5. ![image](https://user-images.githubusercontent.com/101937716/159126537-fa772b9d-4d11-4cd5-87e1-d3ad4cd275bd.png)

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 14 (current)

### Affected platforms

Windows

### Affected platform versions

Windows 10 Pro 10.0.19044 Build 19044

### Did you find any workaround?

Seems to be working on Windows 11.

**Comment by drasticactions** [comment]
My first thought straight away is that this is a WinUI limitation, considering those are the APIs your calling. You're getting the WindowHandle off of the MAUI IWindow (which is based on the WinUI one), and calling everything through the WinUI Interop.

I would verify that it fails on a straight WinUI 3 app (without MAUI being loaded), I'm willing to bet it'll fail in the same way.

**Comment by jfversluis** [comment]
Would you be able to confirm if the solution in this comment maybe fixes it? 

https://github.com/microsoft/WindowsAppSDK/issues/1188#issuecomment-1066261574
