### ISSUE TITLE
Slow MacCatalyst builds

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5447]
### Description

MacCatalyst builds are taking 44-60s cold. This is 2x what I was experiencing on builds back in Nov/Dec.

```
dotnet clean
dotnet build -t:Run -f net6.0-maccatalyst

Time Elapsed 00:00:59.31
````

Incremental was around 11s.

Machine is a 2.6 ghz 6-core i7 with 16GB ram

Via VS Mac 2022 it seems even slower, though it doesn't report a time to me.

### Steps to Reproduce

Run a build on a mac

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

any

**Comment by kristinx0211** [comment]
Machine is a 3 ghz 6-core i5 with 8GB ram.
![image](https://user-images.githubusercontent.com/99457000/159196775-15523875-272b-41c5-995d-9d7e2cf45abf.png)
