### ISSUE TITLE
Essentials - Permission.RequestAsync skipped on Windows

### ISSUE THREAD

**Issue by matt-goldman** [dotnet/maui#5450]
### Description

Calling `Permissions.RequestAsync<T>();` on Windows is skipped and a result of 'Denied' is returned without the user being prompted.

The user should be prompted to grant or deny the permission.

Issue does not occur on Andoird, iOS or macOS in my testing.

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Add a call to `Permissions.RequestAsync<T>()`
3. Run on Windows

Adding breakpoints shows that the call is skipped and the result is returned as denied.

Small repo demonstrating here: https://github.com/matt-goldman/LocationPermissionsTest

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 11

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

No, I tried wrapping it in `MainThread.InvokeOnMainThreadAsync` to no avail. I've also tried wrapping it in a try/catch to see if there are any errors I've been missing, also to no avail.

**Comment by JohnHDev** [comment]
This might be relevant to the behaviour you are seeing: https://github.com/xamarin/Essentials/issues/819

**Comment by matt-goldman** [comment]
> This might be relevant to the behaviour you are seeing: [xamarin/Essentials#819](https://github.com/xamarin/Essentials/issues/819)

Yep that's it. Thanks!
