### ISSUE TITLE
Toolbar Icons missing on Windows

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5452]
### Description

Opening up a NavigationPage with a child having ToolBarItems specified only shows icons if they are used elsewhere on the page (for example in an IconButton). For example if you use the XAML below on Windows the X and Z icons show up, but Y does not (all 3 show up on Android).
```
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Letter X" IconImageSource="{StaticResource GlyphX}"/>
        <ToolbarItem Text="Letter Y" IconImageSource="{StaticResource GlyphY}"/>
        <ToolbarItem Text="Letter Z" IconImageSource="{StaticResource GlyphZ}"/>
    </ContentPage.ToolbarItems>

    <VerticalStackLayout>
        <ImageButton Source="{StaticResource GlyphX}" HorizontalOptions="Center"/>
        <!--<ImageButton Source="{StaticResource GlyphY}" HorizontalOptions="Center"/>-->
        <ImageButton Source="{StaticResource GlyphZ}" HorizontalOptions="Center"/>
    </VerticalStackLayout>

```
If you uncomment the 'Y' Imagebutton, the 'Y' icon will show up in the toolbar.

### Steps to Reproduce

1. Unzip the project from [MAUIToolBar.zip](https://github.com/dotnet/maui/files/8311920/MAUIToolBar.zip)
2. Compile and run it on Android and Windows, you should get the result illustrated below.
3. Note the missing 'Y' icon in the tool bar on the Windows version.

![MAUIToolBar](https://user-images.githubusercontent.com/12423046/159176734-8b820838-a916-42df-b8d9-2d87e8638ce7.jpg)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10 

### Did you find any workaround?

Yes, it turns out the icon shows up if it is declared on the page - it does not need to actually be shown, so you can set IsVisible false on the item that uses the Icon on the page and the icon will still show in the tool bar.

**Comment by Amir-Care** [comment]
Hi @david-maw, when i compile and run with your project, throw a error about "Resource"(ps: see screenshoots ), Could you check your project if run well or give me some suggestions about this error?  thanks! 
  ![image](https://user-images.githubusercontent.com/99456025/159213221-d3966ff7-3730-4665-ae5e-55556b180169.png)

**Comment by v-longmin** [comment]
Verified the issue on Windows and Android, it's repro on windows Main 17.2.0 preview 2.0 32222.408.main, not repro on android 12 - API31. Repro Project:
[MAUIToolBar.zip](https://github.com/dotnet/maui/files/8313698/MAUIToolBar.zip)

**Comment by david-maw** [comment]
Looks like it is fixed on RC1.
