### ISSUE TITLE
Title Bar Oddities on Windows

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5453]
### Description

A MAUI program running on Windows shows up a strange Title Bar compared to, say, a UWP app.

Specifically, 

1. The title Bar is wider than I expect and its background color is grey (the UWP default seems to be white other Windows apps often use blue).
2. The in-app toolbar (pictured below) put there by the debugger seems to be inaccessible, clicking on it is just like clicking on the toolbar background.
![InAppToolbar](https://user-images.githubusercontent.com/12423046/159178393-1ea4aa28-619d-40ba-9b4f-bfbb2db363d5.jpg)
 

### Steps to Reproduce

1. Unzip the project in [MAUIMinimal.zip](https://github.com/dotnet/maui/files/8311976/MAUIMinimal.zip) (it's called MAUIToolBar because I reused another project).
2. Compile and run it, expect to see what's below, note the size and color of the title bar and the fact that clicking on the debugger generated in-app toolbar.

Here's a picture of what a minimal MAUI app looks like, with a minimal UWP app for comparison.
![MAUIMinimal](https://user-images.githubusercontent.com/12423046/159178750-79648149-f99a-45ed-b037-283fbbe7025b.jpg)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
1. The gray title bar is an extended content control and an intentional design choice, https://github.com/dotnet/maui/issues/5067
2. The in-app toolbar being inaccessible is a WinUI bug that affects any in-app WinUI app that _uses_ the extended title bar. We only found out that was a bug when MAUI switched to using said control. That should be fixed, I believe, in WinUI 1.0.1, or the next WinUI release.

**Comment by Amir-Care** [comment]
Verified repro with Version 17.2.0 Preview 2.0 [32208.484.main]

**Comment by david-maw** [comment]
Thanks, it would be better if it were the same width as the standard title bar but just knowing that it's intentional is fine for now (and as @PureWeen commented on #5067 "We do need to make it shorter. The plan is to make it the same height as the close/min/max buttons").

The in-app toolbar thing seems like it's a known bug so I won't pursue that any further.

**Comment by david-maw** [comment]
Yep, I tested it in RC1 and it's fixed

**Comment by PureWeen** [comment]
Thank you for verifying @david-maw !!

**Comment by david-maw** [comment]
You're welcome @PureWeen, for a while I worked in a development team whose policy required the submitter to verify a fix before we could close the incident report. Eventually we had to change that to just not closing until the fix was in a generally available release because too many submitters couldn't or wouldn't verify fixes in a timely way - with that in mind I generally guilt myself into verifying fixes for anything I submit.

**Comment by BurkusCat** [comment]
@PureWeen On WinUI, the titlebar doesn't display the application name either. I noticed this in OP's screenshot too.

![image](https://user-images.githubusercontent.com/7528322/163628071-2ee51c9c-da03-4591-bf2c-2bb9cb72502d.png)
