### ISSUE TITLE
Preprocessors don't seem to work the same 

### ISSUE THREAD

**Issue by BinaryAssault** [dotnet/maui#5455]
### Description

This doesn't work in .NET MAUI (worked in Xamarin)

``````
public static ISomeInterface CreateSomeInstance()
{
    // NOTE: for MAUI, change NETSTANDARD2_1 to NET6_0
    #if NETSTANDARD2_1
        return null;
    #else
        return new InteraceObject.CreateSomeInterfaceInstance();
    #endif
}
``````
In Xamarin, the above code would go into the else when running the app in the android emulator. In MAUI, using the NET6_0 tag, it always goes to the first if. 

### Steps to Reproduce

1. Create a new MAUI app
2.  In the code behind, add the following to the bottom of the OnCounterClicked function:

``````
#if NET6_0
		CounterLabel.Text = $"NET6";
#elif ANDROID
		CounterLabel.Text = $"ANDROID";
#endif
``````

3. Run an android emulator
4. Notice the label in the app is NET6
![preprocessors](https://user-images.githubusercontent.com/19739224/159190132-39938811-eab6-42ad-bb76-166cdaff8e58.gif)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10, Android 11

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main] on windows, Android and iOS. Repro Project: [5455.zip](https://github.com/dotnet/maui/files/8312670/5455.zip)

**Comment by drasticactions** [comment]
I think this is running exactly right based on what you wrote. The logic is "If .NET 6, go here, else if Android, go here". You're running this on .NET 6, so it's going to go to that first option every time.

"NET6_0" is not the same kind of preprocessor as "NET_STANDARD" is, I think that's expected behavior. Moreover, I don't think this is MAUI related, since it doesn't control the preprocessor definitions I believe, the runtime/SDKs do. @jonathanpeppers  Does that sound right?

**Comment by BinaryAssault** [comment]
@drasticactions, I kind of felt like that was the case. I am trying to figure out how this would translate to MAUI. How do we run platform specific code in the non-platform specific areas of code using MAUI?

**Comment by drasticactions** [comment]
In your class library, you declare each platform that library can be run on as a target framework. `net6.0` is generic, `net6.0-android`, `net6.0-ios`, `net6.0-maccatalyst`, `net6.0-windows`

So if you have a target framework set of 

`<TargetFrameworks>net6.0;net6.0-android;net6.0-ios</TargetFrameworks>`

And have the following

```
string test = "";
#if IOS
		test = "IOS";
#elif ANDROID
		test = "ANDROID";
#endif

```

Then the string will be set for the platform it's running on. However, if you have 

```
string test = "";
#if NET6_0
		test = "NET6";
#eif IOS
		test = "IOS";
#elif ANDROID
		test = "ANDROID";
#endif

```

Then it's saying "This code has to run on _any_ platform that runs .NET 6. So it'll always hit that first. So, IMO, I would have your platform-specific cases first, and your end case be the platform-agnostic one.

**Comment by BinaryAssault** [comment]
Closing based on @drasticactions comments as this seems correct
