### ISSUE TITLE
[Android] AddEmbeddedResourceFont is no longer working with Preview 14

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#5456]
### Description

After updating to the latest official version (preview 14) AddEmbeddedResourceFont is no longer working. When I try to register an embedded font and use it in Label for example the font is not applied.

After a brief research I believe this is the commit that has introduced the issue: https://github.com/dotnet/maui/pull/4933

One potential fix will be [here](https://github.com/dotnet/maui/blob/066a91125b0050b4615d51473a53125224f34bab/src/Core/src/Fonts/FontManager.Android.cs#L130) to check for the fontfamily (fontFamily = _fontRegistrar.GetFont(fontName) ?? fontFamily;) of the registrar in order to have an accurate check for File.Exists.

### Steps to Reproduce

Run the attached project and notice that the embedded font is not applied to the Label.

### Preview 13:
<img width="557" alt="Screenshot 2022-03-21 at 11 20 56" src="https://user-images.githubusercontent.com/9336157/159233619-cec55de6-6736-4879-9bc0-6df98727b893.png">

### Preview 14:
<img width="557" alt="Screenshot 2022-03-21 at 11 18 15" src="https://user-images.githubusercontent.com/9336157/159233659-0f8a477a-26df-480d-818f-cd7866821f3e.png">

[EmbeddedFontIssue.zip](https://github.com/dotnet/maui/files/8314291/EmbeddedFontIssue.zip)

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

Android

### Affected platform versions

Android 8 and up

**Comment by XamlTest** [comment]
Verified on Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main](Windows machine). Not repro on Android 9 and 31 with above project.
![image](https://user-images.githubusercontent.com/97647558/159246066-214ae32e-7ddc-4d56-8ee9-6534fb158069.png)
