### ISSUE TITLE
Button release outside button area.

### ISSUE THREAD

**Issue by ITWT73** [dotnet/maui#5457]
### Description

Hi,
Released Button outside his area always stays isPressed=True and Released event never trig.

### Steps to Reproduce

1. Create a button on Forms
2. Press on the button
3. Release outside the button area.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

At least Android 10

### Did you find any workaround?

Not found yet...

**Comment by jfversluis** [comment]
Would you be able to provide a little sample project that shows this behavior? Are you using tap or a attached mouse? Did you try only Android or also iOS or Windows?

**Comment by PineYi** [comment]
Verified Repro with Android 11. Repro Project is available:
[#5457.zip](https://github.com/dotnet/maui/files/8320553/5457.zip)

**Comment by shimingsg** [comment]
> Verified Repro with Android 11. Repro Project is available: [#5457.zip](https://github.com/dotnet/maui/files/8320553/5457.zip)

repro gif: 
![5457](https://user-images.githubusercontent.com/20982341/159396788-7a897991-06fd-43e8-876a-faccf6374485.gif)

**Comment by ITWT73** [comment]
> Bugs on Android 10, works perfectly on windows 11.
[BugButton.zip](https://github.com/dotnet/maui/files/8322752/BugButton.zip)
