### ISSUE TITLE
Border control is not updated, while it's width and height changed.

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#5464]
### Description

We have created the application with border control and the border control was not updated size (width/height) while changing the border size (width/height)

```

        StackLayout customControlStack = new StackLayout();
        for (int i = 0; i < 10; i++)
        {
            Border border = new Border();
            border.Stroke = Colors.Red;
            border.StrokeThickness = 2;
            border.Margin = new Thickness(1);
            border.Padding = new Thickness(2);
            border.StrokeShape = new Microsoft.Maui.Controls.Shapes.RoundRectangle()
            {
                CornerRadius = 5
            };
            Label label = new Label();
            label.Text = i.ToString();
            label.HeightRequest = 50;
            border.Content = label;
            customControlStack.Add(border);
        }
        customControlStack.WidthRequest = 300;
        TapGestureRecognizer customTap = new TapGestureRecognizer();
        customTap.Tapped += (s, e) =>
        {
            customControlStack.WidthRequest = customControlStack.WidthRequest - 10;
        };
        customControlStack.GestureRecognizers.Add(customTap);
        this.Content = customControlStack;

```

**Initial UI:**

![InitialUI](https://user-images.githubusercontent.com/44917578/159282009-89b9d1e3-3f33-4f21-9be4-9aeb369b42e4.png)

**After resized UI:**

![Issue](https://user-images.githubusercontent.com/44917578/159282061-528be55e-7b09-4844-a859-39150734cec8.png)

**Replication video:**

https://user-images.githubusercontent.com/44917578/159282121-374c98c7-ab13-4317-81a2-e5a8a6d40110.mp4

### Steps to Reproduce

1. Create a sample with the above code
2. Tap the stack layout to reduce its width value
3. Border was not resized with it updated size

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

No

### Relevant log output

```shell
Not Applicable
```

**Comment by shimingsg** [comment]
verified repro with VS 17.2.0 Preview 3.0 [32317.342.main] on Android 10 with above code snippet

**Comment by XamlTest** [comment]
This issue not repro on Windows and iOS. Sample Project: [5464.zip](https://github.com/dotnet/maui/files/8320774/5464.zip)
