### ISSUE TITLE
After update VS 2022 android maui project not build XamlCompiler error WMC1007

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#5469]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/After-update-VS-2022-android-maui-projec/1697798)._

---
[severity:I'm unable to use this version] [regression]
After update Visual Studio 2022 Pre, Android Maui project stopps compiling.
Error below:
XamlCompiler error WMC1007: Cannot resolve metadata for WinUI types. Please ensure that Nuget Restore was successful.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by ialbert-AUT** [comment]
I also experience the problem.
VS version: 17.2.0 preview 2.0

Repo steps:
1. new maui app
**2. update nuget package WindowsAppSDK from 1.0.0 to 1.0.1**
3. build for Android -> xaml build error

After that even if I revert to WindowsAppSDK 1.0.0 the error still remains with Rebuild.

**Comment by Mephisztoe** [comment]
> After that even if I revert to WindowsAppSDK 1.0.0 the error still remains with Rebuild.

@ialbert-AUT you need to clean your .csproj project file, because the reference to that package is still there even after downgrading. So I guess you only need to remove the respective line from the package list.

**Comment by jfversluis** [comment]
@Mephisztoe can I conclude from this that you have seen this error but it's working now?

**Comment by Mephisztoe** [comment]
> @Mephisztoe can I conclude from this that you have seen this error but it's working now?

@jfversluis it did for me. However, it turns out that this might have been a coincidance. People are talking about that particular issue at the microsoft-ui-xaml repo as well and stated that my workaround didn't work (for them): https://github.com/microsoft/microsoft-ui-xaml/issues/6782#issuecomment-1076529012

**Comment by ialbert-AUT** [comment]
> o clean your .csproj project file, because the reference to that packag

yes, I deleted the code below and it is working after rebuilding the project _twice_ :)
thx!

	<ItemGroup>
	  <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
	</ItemGroup>

**Comment by jfversluis** [comment]
Yeah I think that package is brought in now automatically. I have been able to delete it as well and that makes things work much better. I'm going to assume this is just some migration pain here. Let me know if removing that entry and some aggressive rebuilding doesn't work. Closing it for now.

**Comment by pvanroos** [comment]
@ialbert-AUT Thanks for you post above.  Removing the 'Microsoft.WindowsAppSDK' from the csproj worked for me.  All of these issues are pushing me to wait for RC rather than play in the previews.  😊

**Comment by MartinRothschink** [comment]
I moved the WindowsAppSdk into the windows section here:

`	<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
		
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.1" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.3" />
	</ItemGroup>
`

and removed it from the global section. That worked for me.
