### ISSUE TITLE
Shell Toolbar does not always show

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5470]
### Description

My application stows a startup screen (after the splash screen) which hangs around for a few seconds then switches to a Shell page once it's ready for user input. Under these circumstances the toolbar does not show up,

### Steps to Reproduce

1. Unzip the project in [MAUIToolBar-Shell.zip](https://github.com/dotnet/maui/files/8318190/MAUIToolBar-Shell.zip)
2. Compile and run it on Windows, note the absence of the toolbar
3. Repeat on Android, this time there will be some sort of bar but with no icons in it

Here's what you should expect to see:

![MAUIToolBar-Shell](https://user-images.githubusercontent.com/12423046/159336586-14921ec2-dd9c-4f9c-be69-b1aff333e8c0.jpg)
 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows 10 

### Did you find any workaround?

Only making my own "fake" toolbar using a set of IconButton objects.

**Comment by v-longmin** [comment]
Verified the issue on windows and android, it's repro. Repro project:
[MAUIToolBar-Shell.zip](https://github.com/dotnet/maui/files/8320266/MAUIToolBar-Shell.zip)

**Comment by david-maw** [comment]
Interesting idea, thanks, it seems to detour the problem.

Wouldn't using this technique mean the end user could navigate away from StartupPage before it was completed (which, in my application is required before the other pages are usable)?

Perhaps I could fix that by cancelling any navigation attempt until StartupPage had completed its work but I hate to offer UI (the hamburger menu) and then say "Nice try, doesn't work yet" if the user selects it. Any ideas?

Lastly, a question, why doesn't a TabBar show up anywhere on the screen even though one is defined in XAML?

**Comment by david-maw** [comment]
Interesting idea, thanks, but wouldn't it mean the end user could navigate away from StartupPage before it was completed (which, in my application is required before the other pages are usable)?

Perhaps I could fix that by cancelling any navigation attempt until StartupPage had completed its work but I hate to offer UI (the hamburger menu) and then say "Nice try, doesn't work yet" if the user selects it.

Lastly, a question, why doesn't a TabBar es not show up anywhere on the screen even though one id defined in XAML.

**Comment by PureWeen** [comment]
@david-maw No, if you use TabBar those other `ShellContent` parts aren't reachable. Each shell part also has an "IsVisible" property so you could even do this

```XAML
        <ShellContent Title="Starting Page" ContentTemplate="{DataTemplate local:StartupPage}"/>
    <ShellContent IsVisible="False" Route="FirstPage" Title="A Page instance" ContentTemplate="{DataTemplate local:MainPage}"/>
    <ShellContent IsVisible="False" Title="Another instance" ContentTemplate="{DataTemplate local:MainPage}"/>
```

And then once you want to switch just toggle them all

```XAML
        <ShellContent IsVisible="False" Title="Starting Page" ContentTemplate="{DataTemplate local:StartupPage}"/>
    <ShellContent IsVisible="True" Route="FirstPage" Title="A Page instance" ContentTemplate="{DataTemplate local:MainPage}"/>
    <ShellContent IsVisible="True" Title="Another instance" ContentTemplate="{DataTemplate local:MainPage}"/>
```

**Comment by david-maw** [comment]
Thanks @PureWeen, that's interesting. By "No" do you mean navigation should not be available or that I must explicitly set the m to be invisible? I ask because in my testing I thought I tried your proposed XAML and navigation (to "FirstPage" or "Another Instance") from "Startup Page" seemed to be allowed before it was completed..
