### ISSUE TITLE
No XAML Hot Reload errors or status logged

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#5472]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-XAML-Hot-Reload-errors-or-status-logg/1590580)._

---
[severity:I'm unable to use this version]
I'm running .NET MAUI main and VS22 targeting Windows App SDK. The LVT loads WinUI elements, and Live Preview displays the app, but I get no indication as to the status of XAML Hot Reload. 

When I make an edit and save it, I get no indication if it succeeded or failed. 

Please log the status of XAML Hot Reload and provide actionable, informative log messages and errors, and/or a status indicator that is always present like the Mac Build Host connection or C# Hot Reload with the icon. 

As it is, developers don't know if it's the sdk/tooling that is failing, or their own code and knowledge. 

---
#### Feedback Bot on 11/21/2021, 06:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/1/2022, 11:50 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
@drasticactions this is something up your alley?

**Comment by drasticactions** [comment]
@jfversluis This is an issue from @davidortinau from a few months ago. Considering the context of what he wrote, it could have been various things at the time.

Closing this, it's unrelated to MAUI.
