### ISSUE TITLE
Mobile workload in VS missing MSVC build tools component needed to publish .NET MAUI apps on Windows

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#5474]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Mobile-workload-in-VS-missing-MSVC-build/1681990)._

---
The "Mobile development with .NET" workload for .NET MAUI apps doesn't include the MSVC build tools, which apparently are needed to publish .NET MAUI apps on Windows.

Repro steps:

- Install VS2022 17.2 Preview 1 with just the "Mobile development with .NET" workload
- Create a new .NET MAUI app
- Create a test certificate for package signing: https://docs.microsoft.com/windows/msix/package/create-certificate-package-signing
- Publish the app: `msbuild /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="<certificate thumbrint>" /p:PackageCertificatePassword="<certificate password>"`

Expected result: App publishes cleanly
Actual result: An error stating that FastLink symbols couldn't be converted to PDBs because the mspdbcmf.exe tool wasn't found.

```
Build FAILED.

"C:\Users\WDAGUtilityAccount\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj" (Publish target) (1:19) ->
(_GenerateAppxSymbolPackage target) ->
  C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets(341,5): warning : Failed to convert FastLink symbols to full PDBs for 'C:\Users\WDAGUtilityAccount\source\rep
os\MauiApp1\MauiApp1\obj\release\net6.0-windows10.0.19041\win10-x64\MauiApp1.pdb' due to failure to find the tool 'C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.32.31114\bin\HostX64\x64\mspdbcmf.exe'. [C:\
Users\WDAGUtilityAccount\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj]

"C:\Users\WDAGUtilityAccount\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj" (Publish target) (1:19) ->
(_GenerateAppxSymbolPackage target) ->
  C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets(341,5): error MSB6011: Invalid parameters passed to the Microsoft.Build.Msix.Symbols.WinAppSdkCheckFastlinkPd
b task. [C:\Users\WDAGUtilityAccount\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj]
```

Workaround: Install the MSVC build tools component using the VS installer

---
#### Feedback Bot on 3/3/2022, 02:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Thanks for the report! As mentioned in #4329 we're aware and a fix should be close. Closing this one to not duplicate efforts here, thank you!
