### ISSUE TITLE
ActivityIndicator ignores HorizontalOptions on Windows

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5480]
### Description

Tried to center an `ActivityIndicator `horizontally by setting `HorizontalOptions="Center"` but it looks as if it always behaves as if "Start" was set. Android looks a bit different but seems to be correct.

### Steps to Reproduce

1. Unzip the project in [MauiActivityIndicator.zip](https://github.com/dotnet/maui/files/8319580/MauiActivityIndicator.zip)
2. Compile and run it on Windows
3. Note the position of the `ActivityIndicator` on the left (start) of the page vertically centered (the default).

It should look like this:

![MauiActivityIndicator](https://user-images.githubusercontent.com/12423046/159374880-efc1f4d0-976d-49d2-95ad-040660335023.jpg)
 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

No, but I didn't look for one since it's such a minor problem.

**Comment by XamlTest** [comment]
Verified repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main] on Windows. Repro Project: [5480.zip](https://github.com/dotnet/maui/files/8320139/5480.zip)

**Comment by jsuarezruiz** [comment]
Using the .NET MAUI Gallery and the main branch cannot reproduce the issue.
![issue-5480](https://user-images.githubusercontent.com/6755973/159486489-dfc462d5-2197-4818-93a6-f75409e83cf7.gif)

**Comment by Redth** [comment]
Once RC1 ships, please give that a try, if there's still an issue, please open a new issue.

**Comment by david-maw** [comment]
@jsuarezruiz thanks, that looks remarkably like the Android indicator I'm used to (a rotating broken circle) but in what's obviously a Windows App, so I'm guessing it's different on Windows in rc1. Presuming that's true, I'll happily give it a shot in rc1 once it's available to me as @Redth requested.

**Comment by david-maw** [comment]
Yep, it's fixed on RC1
