### ISSUE TITLE
[Enhancement] Make more controls to inherit a ContentControl

### ISSUE THREAD

**Issue by TanukiSharp** [dotnet/maui#55]
Currently in XF the `Button` (for example) only has a `Text` property and it is a pain in butt to make buttons with something else than text in it.

In WPF, the `Button` inherits from the `ContentControl` at some point in the inheritance chain, which makes it much more flexible.

**Comment by BurkusCat** [comment]
Slightly related:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/checkbox Xamarin.Forms checkbox has no Text property, so you have to go to a bit of effort to make a full checkbox control with a clickable label.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/radiobutton Xamarin.Forms radio button has a Text property, so you can easily use it with no effort. At the same time, you could also put a bit of effort in to use it with images and other content.

It would be nice if Xamarin.Forms made the default use cases for these things easier but left things open that it is easy to override and do something more unusual with the control.

**Comment by TanukiSharp** [comment]
Agreed, and it would also be good for the sake of consistency.

What's good with the `ContentControl` is that it is not opinionated, and if you want text, fine, just put a `TextBlock` in it and you are good to go.

The XAML parser is smart enough to instantiate a `TextBlock` for you when it gets a string, to make things less verbose. With a bit of implicit cast, I believe the same could be done to keep MVU not too verbose for the vast majority of times you just need text.

**Comment by legistek** [comment]
Remember Xamarin Forms doesn't have a `ContentControl` and its `ContentPresenter` is not like WPFs in that it does not accept `object` content and a `DataTemplate` but just presents another visual.
So these would need to be added (though both are very easy).

**Comment by dersia** [comment]
> Remember Xamarin Forms doesn't have a `ContentControl` and its `ContentPresenter` is not like WPFs in that it does not accept `object` content and a `DataTemplate` but just presents another visual.
> So these would need to be added (though both are very easy).

And this is exactly what needs to be changed!
