### ISSUE TITLE
Toolbar with Tabbed Pages in shell

### ISSUE THREAD

**Issue by eramrit78** [dotnet/maui#5504]
### Description

I would to have a toolbar items in tabbed page in shell. Currently in xamarin form toolbar items not work on tabbed page in shell.

### Public API Changes

-

### Intended Use-Case

-

**Comment by eramrit78** [comment]
for more detail  see #7351

**Comment by PureWeen** [comment]
Currently `TabbedPAge` isn't fully compatible with `Shell` and we are tracking that work here https://github.com/dotnet/maui/issues/6389
