### ISSUE TITLE
Shell.GotoAsync not working

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5506]
### Description

A couple of issues, first, it seems that Shell.Current.GoToAsync doesn't do anything. 

Second there's a difference between the behavior of Windows and Android when a shell child page uses navigation to open another page, on Windows you get a left arrow (to navigate back to the calling page) and the shell hamburger menu but on Android you get only the left arrow not both. Given it wasn't modal navigation I suppose showing both icons is the correct answer but I can see an argument for either choice. Here's how it looks in practice:
![MauiShell-Navigation](https://user-images.githubusercontent.com/12423046/159627885-0a23d6a1-592e-4447-a270-d7ba4b47d581.jpg)

### Steps to Reproduce

1. Unzip the project in [MauiShell-Navigation.zip](https://github.com/dotnet/maui/files/8329859/MauiShell-Navigation.zip)
2. Compile and run the project on Windows or Android
3. use the hamburger menu to select the child page
4. click on the button to switch back to the main page, nothing happens

To see the navigation difference above just click on the main page to navigate to the child 
 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows 10

**Comment by v-longmin** [comment]
Verified the issue on Windows and android, it's repro. Repro project:
[MauiShell-Navigation.zip](https://github.com/dotnet/maui/files/8330139/MauiShell-Navigation.zip)

**Comment by PureWeen** [comment]
Make sure to always await `GotoAsync`.  If you await the `GotoAsync` call then you'll see the following exception message

![image](https://user-images.githubusercontent.com/5375137/160854561-4fa444a4-125f-4086-ae21-a95f9e634a25.png)

Currently you can't push shell routes onto the navigation stack so you have to do an absolute route to get back to main
`await Shell.Current.GoToAsync("//Main");`

>  Given it wasn't modal navigation I suppose showing both icons is the correct answer but I can see an argument for either choice. 

We're defaulting to platform behavior here. The Shell implementation on android uses a `DrawerLayout` which uses the same icon space for the backbutton and the hamburger.

I've created a tracking issue [here](https://github.com/dotnet/maui/issues/5666)

**Comment by david-maw** [comment]
Thanks, the original problem was in a chunk of code migrated from Xamarin Forms so while the workaround is simple it's going to be a migration issue until it's supported. Thanks also for the 'await' hint since I didn't care about the result there seemed no point, but I now understand there is because it exposes the exception.
