### ISSUE TITLE
Injecting ViewModel to View (ContentPage) in .Net MAUI MVVM

### ISSUE THREAD

**Issue by mcjekm** [dotnet/maui#5507]
### Description

This is my code, and I am getting error after updating to the latest version.

[XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class HomePage : ContentPage
    {
        public HomePage(IHomePageVM homePageVM)
        {
            InitializeComponent();
            BindingContext = homePageVM;
        }
    }

### Steps to Reproduce

Was working on Version 17.1.0 Preview 6.0

Displaying error  
No parameterless constructor defined for type <>

after updating to Version 17.2.0 Preview 2.1

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by shimingsg** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project that we can reproduce your issue? 
That should greatly speed up the process, thanks!

**Comment by shimingsg** [comment]
verified not repro with vs 17.2.0 Preview 3.0 [32322.459.main] on android 11,  add below code snippet:
in MauiProgram:
```
builder.Services.AddScoped<MainPage>();
builder.Services.AddScoped<IHomePageVM,HomePageVM>();
```
in MainPage.xaml.cs
```
[XamlCompilation(XamlCompilationOptions.Compile)]
public partial class MainPage : ContentPage
{
	public MainPage(IHomePageVM homePageVM)
	{
		InitializeComponent();
		BindingContext=homePageVM;
	}
}

public class HomePageVM:IHomePageVM {}

public interface IHomePageVM {}

```
in App.lxaml.cs
```
public App(MainPage mainPage)
	{
		InitializeComponent();

		MainPage = mainPage;
	}
```

is this your expected? feel free to provide more information/sample

**Comment by Mephisztoe** [comment]
I know this problem. However, I didn't experience it by migrating from any .NET MAUI version to any other, but instead by switching from a NavigationPage style navigation to AppShell. However, using the .NET 6 integrated Dependency Injection, everything works as expected.

Basically what I did was the following:

1. Implement an extension to MauiAppBuilder like so:

```
public static MauiAppBuilder RegisterServices(this MauiAppBuilder builder)
{
    var currentAssembly = Assembly.GetExecutingAssembly();

    // Transient objects lifetime services are created each time they are requested.
    // This lifetime works best for lightweight, stateless services.
    foreach (var type in currentAssembly.DefinedTypes.Where(e => e.IsSubclassOf(typeof(Page)) || e.IsSubclassOf(typeof(BaseViewModel))))
    {
        builder.Services.AddTransient(type.AsType());
    }
    return builder;
}
```

Note: BaseViewModel is a base class, I inherit all my ViewModels from (in this case, it is part of the Refractored.MvvmHelpers package, but you can use whatever you like. It's about identifying your ViewModels by looking for every Class that share a specific base and then adding them to your Services collection.

2. Call into the Extension from your Builder setup like so:

```
public static MauiApp CreateMauiApp()
{   
    var builder = MauiApp.CreateBuilder();
    builder
      .UseMauiApp<App>()
      .ConfigureEssentials()
      .UseMauiCommunityToolkit()
      .RegisterFonts()
      .RegisterServices()
      .RegisterEffects()
      .RegisterAppCenter();
      
    return builder.Build();
}
```

Never mind the other calls; the important one here is of course .RegisterServices()

Then, in my AppShell based .NET MAUI app, I can simply initialize my Views from their corresponding code behind like so:

```
public partial class AboutView : ContentPage
{
    AboutViewModel viewModel => BindingContext as AboutViewModel;

    public AboutView(AboutViewModel viewModel)
    {
        InitializeComponent();
        BindingContext = viewModel;
    }
}
```  

Does this help?

**Comment by Mephisztoe** [comment]
> verified not repro with vs 17.2.0 Preview 3.0 [32322.459.main] on android 11, add below code snippet: in MauiProgram:
> 
> ```
> builder.Services.AddScoped<MainPage>();
> builder.Services.AddScoped<IHomePageVM,HomePageVM>();
> ```

Ah great, this is the short version of my post and I guess the magic happens within Dependecy Injection.
I think @mcjekm might be missing this step.

**Comment by mcjekm** [comment]
If this helps... 

**MauiProgram.cs**
`public static class MauiProgram
	{
		public static MauiApp CreateMauiApp()
		{
			var builder = MauiApp.CreateBuilder();
			builder
				.UseMauiApp<App>()
				.ConfigureFonts(fonts =>
				{
					fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				});

			builder.Services.AddSingleton<AppShell>();
			builder.Services.AddSingleton<IAppShellVM, AppShellVM>();
			builder.Services.AddSingleton<IHomePageVM, HomePageVM>();
			builder.Services.AddSingleton<IEntryPageVM, EntryPageVM>();
			builder.Services.AddSingleton(typeof(RestAPIService<>));

			builder.Services.AddSingleton<IAPIResultVM, APIResultVM>();
			builder.Services.AddSingleton<IHistoryPageVM>(HistoryPageVM.CreateInstance()); 
			return builder.Build();
		}
	}`

**App.xaml**
`<Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:windows="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.WindowsSpecific;assembly=Microsoft.Maui.Controls"
             xmlns:local="clr-namespace:MAUITestProj"
             x:Class="MAUITestProj.App"
             windows:Application.ImageDirectory="Assets">
    <Application.Resources>
        <ResourceDictionary>

            <Color x:Key="PrimaryColor">#512bdf</Color>
            <Color x:Key="SecondaryColor">White</Color>

            <Style TargetType="Label">
                <Setter Property="TextColor" Value="{DynamicResource PrimaryColor}" />
                <Setter Property="FontFamily" Value="OpenSansRegular" />
            </Style>

            <Style TargetType="Button">
                <Setter Property="TextColor" Value="{DynamicResource SecondaryColor}" />
                <Setter Property="FontFamily" Value="OpenSansRegular" />
                <Setter Property="BackgroundColor" Value="{DynamicResource PrimaryColor}" />
                <Setter Property="Padding" Value="14,10" />
            </Style>

        </ResourceDictionary>
    </Application.Resources>
</Application>`

**App.xaml.cs**
`public partial class App : Application
	{
		public App(AppShell mainPage)
		{
			InitializeComponent();

			MainPage = mainPage;
		}
	}`

**AppShell.xaml**
`<Shell xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       x:Class="MAUITestProj.MVVM.Views.AppShell"
       xmlns:views="clr-namespace:MAUITestProj.MVVM.Views"
       Title="Menu">

    <FlyoutItem Title="Home" Icon="home_black_24dp">
        <ShellContent ContentTemplate="{DataTemplate views:HomePage}"/>
    </FlyoutItem>
    <FlyoutItem Title="Search" Icon="search_black_24dp">
        <ShellContent ContentTemplate="{DataTemplate views:SearchPage}"/>
    </FlyoutItem>
    <FlyoutItem Title="Search History" Icon="saved_search_black_24dp">
        <ShellContent ContentTemplate="{DataTemplate views:APIResultListPage}"/>
    </FlyoutItem>
    <FlyoutItem Title="Favourites" Icon="favorite_black_24dp">
        <ShellContent ContentTemplate="{DataTemplate views:SearchPage}"/>
    </FlyoutItem>
</Shell>`

**AppShell.xaml.cs**
`public partial class AppShell : Shell
    {

        public AppShell(IAppShellVM appShellVM)
        {
            InitializeComponent();

            Routing.RegisterRoute(nameof(HomePage), typeof(HomePage));
            Routing.RegisterRoute(nameof(SearchPage), typeof(SearchPage));
            Routing.RegisterRoute(nameof(EntryPage), typeof(EntryPage));
            Routing.RegisterRoute(nameof(APIResultListPage), typeof(APIResultListPage));
        }
    }`

**HomePage.xaml**
`<ContentPage x:Class="MAUITestProj.MVVM.Views.HomePage"
             xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             BackgroundColor="White"
             Title="Home">

    <ScrollView>
        <Grid RowSpacing="25" RowDefinitions="Auto,Auto,Auto,Auto,*"
              Padding="{OnPlatform iOS='30,60,30,30', Default='30'}">

            <Label 
                Text="Enter your vehicle registration"
                Grid.Row="0"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="CenterAndExpand"
                VerticalOptions="CenterAndExpand"/>

            <Button 
                Text="Rego Check"
                FontAttributes="Bold"
                Grid.Row="3"
                SemanticProperties.Hint="Free information about a registered vehicle"
                HorizontalOptions="Center" 
                Command="{Binding RegoCheckCommand}"/>

        </Grid>
    </ScrollView>
</ContentPage>`

**HomePage.xaml.cs**
`[XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class HomePage : ContentPage
    {
        public HomePage(IHomePageVM homePageVM)
        {
            InitializeComponent();
            BindingContext = homePageVM;
        }
    }`

**HomePageVM**
`    public class HomePageVM : IHomePageVM
    {
        private ICommand _regoCheckCommand;
        public ICommand RegoCheckCommand
        {
            get
            {
                return _regoCheckCommand ?? (_regoCheckCommand = new RelayCommand(RegoCheckCommandClickAction, p => true));
            }
        }

        private async void RegoCheckCommandClickAction(object obj)
        {
            Console.WriteLine("Test");
            var route = $"{nameof(EntryPage)}";
            await Shell.Current.GoToAsync(route);
        }

    }`

**IHomePageVM**
`public interface IHomePageVM
    {
        ICommand RegoCheckCommand { get; }
    }`
    
I am not an advanced level dev. So, I don't know right/best ways to do it...  But it was working... I upgraded to latest version, and now it is displaying the below given error...

_System.MissingMethodException
  Message=No parameterless constructor defined for type 'MAUITestProj.MVVM.Views.HomePage'._

I am using Routing (https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-12/).

I tried 'AddScoped' instead 'AddSingleton' (As seen in the previous comments). Same error...

I am not re-opening the ticket if you are unable to reproduce.

**Comment by mcjekm** [comment]
> Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project that we can reproduce your issue? That should greatly speed up the process, thanks!

Hope you have seen the asked/additional info I provided in my previous comment.
