### ISSUE TITLE
How to set app launch window size

### ISSUE THREAD

**Issue by jiangk576** [dotnet/maui#5509]
### Description

I wonder how to set launch window size in maui。
When I search for Issues and DIscussion，I found there is no universal way to set  launch window size in maui, https://github.com/dotnet/maui/discussions/2370 ,someone says in windows we can get the window handler first and change window size,  but in macOS there is no workaround way.
And I also find https://github.com/dotnet/maui/pull/4942 , this work will allow us to set window size to a fixed value while targeting Windows, What about MacOS? I think it's not an uniform solution for maui framework。

### Public API Changes

setWindowSize()
setWindowLocation()

### Intended Use-Case

I want to show different window size when using multi-window,  so I need to set app launch window size。

**Comment by SmRiley** [comment]
Even setting the window size requires reflection or handle, which is very frustrating, and convenience cannot be abandoned just because it is cross-platform
