### ISSUE TITLE
BlazorWebView's AllowSingleSignOnUsingOSPrimaryAccount defaults to false

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#5512]
### Description

This is to follow up on https://github.com/dotnet/maui/pull/5086#issuecomment-1073140745

WebView2 has this setting that controls whether AAD single-sign-on can be used within the webview. It's hard to think of a reason why developers would *not* want this to be possible, and in fact, the WebView2 team says [see here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2240#issuecomment-1061017391):

> I believe this is "False" by default because it was "False" when we created the API and we didn't want to create app compatibility problems with a feature suddenly turning on. It can also be surprising to devs and users to be using a control and already be signed in without user action. There shouldn't be downsides to using this API. Thanks!

Given that this only defaults to false for back-compat, and we don't have a back-compat requirement since we haven't shipped the first stable version yet, shouldn't we have it default to true in `BlazorWebView`? This would streamline the SSO dev experience. Moreover, if we don't do this, then we probably do have to add some API for it since there's no known way to set it to true manually currently.

**UPDATE: My guess is what we really should do is ensure that, for all platforms, there's a way to configure the `CoreWebView2Environment` arbitrarily at the right point during initialization. We're not going to be able to keep up with all the different possible options there are, or might arise in the future.**

### Steps to Reproduce

.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

**Comment by mstancombe** [comment]
@javiercn 👍👍 thank you!  Just stumbled into a scenario requiring exactly this on Android.
