### ISSUE TITLE
OnIdiom don't work correct on Shell - FlyoutBehavior 

### ISSUE THREAD

**Issue by osnipezzini** [dotnet/maui#5524]
### Description

When creating a Shell and adding the Shell.FlyoutBehavior="{OnIdiom Desktop=Locked, Default=Flyout}" don't have effect

![image](https://user-images.githubusercontent.com/4562546/159771119-d13bb22c-ce05-4f09-adc8-66e0359cff5a.png)

Repository with project tested: https://github.com/osnipezzini/BugFlyoutBehavior

### Steps to Reproduce

 - Create a new MAUI App
 - Add a AppShell
 - Edit AppShell and property: Shell.FlyoutBehavior="{OnIdiom Desktop=Locked, Default=Flyout}"
 - Run on Windows

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by XamlTest** [comment]
Verified repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main] on windows. Repro with above project.

**Comment by Redth** [comment]
Related to #5653 ?

**Comment by osnipezzini** [comment]
Not related with this issue

Em qua., 30 de mar. de 2022 22:22, Jonathan Dick ***@***.***>
escreveu:
