### ISSUE TITLE
CarouselPage Migration

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5526]
### Description

Migrating a CarouselPage from Xamarin to MAUI seems quite challenging, am I missing something? The benchmark I'm aiming at is the one described in [Migrate your app from Xamarin.Forms](https://docs.microsoft.com/en-us/dotnet/maui/get-started/migrate) which begins:

_You don't need to rewrite your Xamarin.Forms apps to move them to .NET Multi-platform App UI (.NET MAUI). However, you need to make a small amount of code changes to each app._ 

Which seems reasonable, however #4204 "Remove CarouselPage" says "Now that we have CarouselView there is no longer a need for a CarouselPage".

That's not immediately obvious (to me at least, and perhaps is why Xamarin Forms had both).

To summarize CarouselView is a control mostly focused on displaying a list of items all with the same layout, whereas a CarouselPage contains several content pages each of which may have quite different layouts.

An abbreviated CarouselView XAML might look like this:
```
<CarouselView ItemsSource...>
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <StackLayout>
                <bunch o' labels or other controls>
            </StackLayout>
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>
```
It will display each item in the list using the same DataTemplate.

In contrast, a CarouselPage looks like this in XAML:
```
<CarouselPage ...>
    <ContentPage/>
    <ContentPage/>
    ...
</CarouselPage>     
```
Where each `ContentPage` object may have a vastly different layout.
 
It seems like it would be possible to code around this by converting the pages to some sort of list of views, with attached lists of ToolBaritems (and whatever else a page has that a view doesn't) and dynamically changing the CarouselView DataTemplate as the selected item in the list changes but that does not seem to meet the "don't need to rewrite"' requirement.

Again, I might be missing the point entirely, if so, I'd appreciate some guidance.

### Steps to Reproduce

1. Unzip the Xamarin project in [Carousel.zip](https://github.com/dotnet/maui/files/8335614/Carousel.zip)
2. Compile and run it in Windows or Android, whichever is more convenient
3. Convert it to MAUI
 

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 14 (current)

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

All

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
While we never officially deprecated it, in the [docs for Xamarin.Forms](https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/navigation/carousel-page) there has been a note for a very long that already points out that `CarouselPage` has been superseded by `CarouselView`.

I will see that we add it to a doc that lists the breaking changes and make it more obvious. Thanks for pointing this out!

**Comment by david-maw** [comment]
Thanks, I had never noticed that note, I can see I'm going to regret my design choices (which unsurprisingly predate the note). If you could document a few hints on migration strategies along with the breaking change note, that would help, 

in the meantime I'll experiment with using other methods (maybe a `CarouselView` or `SwipeView`) to achieve the same effect of letting the end user swipe to change pages, are you interested in seeing it if I come up with something fairly generally applicable? Do you have any ideas for dealing with `ToolBarItems` in this case? So far the best idea I've got is some code responding to `CurrentIemChanged`and some sort of collection of `ToolBarItems` collections (one per page of content).

**Comment by david-maw** [comment]
It occurred to me it might be worth some effort to warn Xamarin users about this, so I submitted the following against Visual Studio (which I think is how Xamarin issues get reported).

The [docs for Xamarin.Forms](https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/navigation/carousel-page) contains a note that points out that `CarouselPage` has been superseded by `CarouselView`. For that reason `CarouselPage` is not implemeted in MAUI. 
 
With that in mind it might be worth marking `CarouselPage` as obsolete in Xamarin forms so that people with old code at least get a warning when they compile it (presumably anyone using `CarouselPage` for the first time will see the documentation note, so they are not a problem). That would let them start on a migration plan (if they need one) sooner rather than later.

**Comment by jfversluis** [comment]
I'll admit the messaging could've been better and personally I think we should've added the deprecated flag on the `CarouselPage` for Forms earlier. This will probably be part of the migration guide when we reach GA :)

**Comment by david-maw** [comment]
Yep, I agree it could have been handled better, but as far as I'm concerned that's water under the bridge now. If I'd noticed when the note on `CarouselPage` being superseded by `CarouselView` came out I'd have made the same complaint about migration difficulty against Xamarin Forms, too bad, that ship's sailed.

As I wrote above, if I produce some useful techniques for migrating from `CarouselPage` to `CarouselView` I can pass them back if that'd be useful.
