### ISSUE TITLE
Can't build for iOS simulators in p14, codesign exited with code 1

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#5530]
### Description

Pair to the Mac, running an existing solution and targeting an iOS simulator. The build fails with multiple codesign exited with code 1 errors.
Codesigning is not required when targeting a simulator, and this only started happening with preview 14. Updating VS to Version 17.2.0 Preview 2.1 doesn't help either.

### Steps to Reproduce

Run VS Version 17.2.0 Preview 2.1 with a new solution
Pair to a Mac
Select an iOS simulator and run
Build fails with 1 or more codesign exited with code 1 errors

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

iOS 15, but I resume all

### Did you find any workaround?

No

**Comment by v-longmin** [comment]
Verified the issue on iPhone 11 OS:15.4 platform, VS 17.2.0 preview 2.0 [32223.408 main], the issue does not repro.

**Comment by jfversluis** [comment]
Would you be able to dig anything more out from the logs? Because I haven't been able to reproduce this myself as well.

**Comment by JohnHDev** [comment]
@jfversluis after upgrading the Mac to Monterey 12.3 and installing Xcode 13.3 the problem is no longer repeatable, might be a compatibility issue with older versions of Xcode?

**Comment by jfversluis** [comment]
Might be, not sure. It seems I have 12.3 and 13.3 so that might explain... Going to assume (hope?) that this was incidental. Let's see if more people will report this. Thanks!

**Comment by ElementalLogic** [comment]
I'm seeing this error on BigSur with xcode 13.2.1 - I can't upgrade (without buying a new mac!!).

Using the default Maui Project, results in the following:

`Target "_CodesignAppBundle" in file "C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets":
1>      Using "Codesign" task from assembly "C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\..\iOS\Xamarin.iOS.Tasks.dll".
1>      Task "Codesign"
1>        Task Parameter:SessionId=0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de
1>        Task Parameter:
1>            Resources=
1>                bin\Release\net6.0-ios\ios-arm64\MauiApp4.app
1>                        CodesignAdditionalFilesToTouch=bin\Release\net6.0-ios\ios-arm64\MauiApp4.app.dSYM\Contents\Info.plist
1>                        CodesignAllocate=\Applications\Xcode.app\Contents\Developer\Toolchains\XcodeDefault.xctoolchain\usr\bin\codesign_allocate
1>                        CodesignDeep=false
1>                        CodesignDisableTimestamp=False
1>                        CodesignEntitlements=obj\Release\net6.0-ios\ios-arm64\Entitlements.xcent
1>                        CodesignExtraArgs=
1>                        CodesignKeychain=
1>                        CodesignRelativeAppBundlePath=Release\net6.0-ios\ios-arm64\MauiApp4.app
1>                        CodesignResourceRules=
1>                        CodesignSigningKey=B929A108AF682F32F11CE92B284A74FD86743382
1>                        CodesignStampFile=bin\Release\net6.0-ios\ios-arm64\MauiApp4.app\_CodeSignature\CodeResources
1>                        CodesignStampPath=obj\Release\net6.0-ios\ios-arm64\codesign\
1>                        CodesignUseHardenedRuntime=
1>                        CodesignUseSecureTimestamp=
1>                        IsInputDirectory=true
1>        Codesign: 2022-04-07T16:05:07.7790229+01:00 - Started
1>        Codesign: 2022-04-07T16:05:07.7790229+01:00 - Initializing
1>        [xma]: Trying to get a Build Connection for Session '0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de': Xamarin.Messaging.Build.Client.BuildConnection.0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de, Lifetime: AppDomain
1>        Codesign: 2022-04-07T16:05:07.7790229+01:00 - Initialized
1>        Codesign: 2022-04-07T16:05:07.7800233+01:00 - There's no available inputs to copy to the Mac
1>        Codesign: 2022-04-07T16:05:07.7800233+01:00 - Serializing intputs
1>        Codesign: 2022-04-07T16:05:07.7880226+01:00 - Executing
1>        [xma]: Starting remote task execution for 'MauiApp4': Xamarin.MacDev.Tasks.Codesign
1>        [xma]: Sending Request Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic xvs/build/execute-task/MauiApp4/0f1e4cd002fCodesign
1>        [xma]: Received Response of Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic build0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de23364jamie/+/xvs/build/execute-task/MauiApp4/0f1e4cd002fCodesign
1>        Codesign: 2022-04-07T16:05:08.4528915+01:00 - Logging messages
1>        The stamp file 'bin/Release/net6.0-ios/ios-arm64/MauiApp4.app/_CodeSignature/CodeResources' does not exist, so the item '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Release/net6.0-ios/ios-arm64/MauiApp4.app' needs to be codesigned.
1>        Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign B929A108AF682F32F11CE92B284A74FD86743382 --entitlements /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/obj/Release/net6.0-ios/ios-arm64/Entitlements.xcent /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Release/net6.0-ios/ios-arm64/MauiApp4.app
1>        Tool /usr/bin/codesign execution finished (exit code = 1).
1>        /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Release/net6.0-ios/ios-arm64/MauiApp4.app: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /usr/bin/codesign exited with code 1
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : Failed to codesign '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Release/net6.0-ios/ios-arm64/MauiApp4.app': /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Release/net6.0-ios/ios-arm64/MauiApp4.app: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : 
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        Codesign: 2022-04-07T16:05:08.4528915+01:00 - Finished
1>      Done executing task "Codesign" -- FAILED.
1>    Done building target "_CodesignAppBundle" in project "MauiApp4.csproj" -- FAILED.
1>
1>    Done building project "MauiApp4.csproj" -- FAILED.
1>  Done executing task "MSBuild" -- FAILED.
1>Done building target "DispatchToInnerBuilds" in project "MauiApp4.csproj" -- FAILED.`
