### ISSUE TITLE
Changing Detail of a FlyoutPage leads to an empty page on Android

### ISSUE THREAD

**Issue by Naryorill** [dotnet/maui#5541]
### Description

In a flyout page, setting the Detail with `Detail = new NavigationPage((Page)Activator.CreateInstance(entry.TargetType));` like it's written in the [documentation](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/pages/flyoutpage#create-a-flyoutpage) leads to an empty detail page on Android, the Title in the Navigation Bar is set however. 

On Windows it works as expected.

### Steps to Reproduce

Simple sample project (slightly altered from the documentation, but the not-yet-officially-released sample project from the documentation shows this issue too):
[NavigationTest.zip](https://github.com/dotnet/maui/files/8340596/NavigationTest.zip)

Simply open the flyout and select something.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7 (API 24), Android 12 (API 31)

**Comment by XamlTest** [comment]
Verified repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main] on Android. Repro with above project.
