### ISSUE TITLE
template for maui blazor preview 

### ISSUE THREAD

**Issue by dkboon01** [dotnet/maui#5543]
### Description

I'm getting an error on the package.appxmanifest when using the blazor maui template.  I didn't right any code because I'm just trying to get the template to run on a windows machine.  Error:  Manifest file 'Platform\\Windows\Package.appxmanifest' does not contain attribute Name on Identity element.   I keep trying to fix this file by adding what is needed from the error messages being received.  Is there an example of this file without the "assets folder" problem?  I'm not a windows developer that is why I'm trying blazor in windows.  Dotnet version 6.0.300 -preview 22154.4 and vs 2022 17.2.0 preview2.1

### Steps to Reproduce

1. Updated the maui templates
2. create a new project vs 2022 preview
3. build 
4. windows machine and debug
5. failed to launch 

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 11

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by jfversluis** [comment]
Thanks for the report! Unfortunately I'm not able to reproduce this. Would you be able to perform the steps that you listed to create a new project and upload that to a GitHub repository so we can take a look? Thanks!

**Comment by dkboon01** [comment]
https://github.com/dkboon01/MauiApp2

**Comment by VincentBu** [comment]
Hi @dkboon01 , I'm also using 17.2.0 Preview 2.1 and I can successfully run [MauiApp2](https://github.com/dkboon01/MauiApp2) on Windows. 
![image](https://user-images.githubusercontent.com/44959937/160036251-6020976c-d49b-44b3-8878-01fbf4b3adca.png)

Could you provide the full error message? I mean content in output and error list window:
![image](https://user-images.githubusercontent.com/44959937/160037299-7d2ee13a-f965-4fa7-8007-15252826191a.png)

**Comment by dkboon01** [comment]
![Screenshot 2022-03-24 215835](https://user-images.githubusercontent.com/11353230/160039677-82ddc556-747f-4141-ae57-c1d5fbc773ac.png)

**Comment by jfversluis** [comment]
Looks like you somehow got the newest templates that you shouldn't have yet and now you're running into changes that are made here #2704

How did you install the templates if I may ask?

Could you maybe try to run this in a CLI `dotnet new -i Microsoft.Maui.Templates::6.0.200-preview.14.5099` that should fix it

**Comment by dkboon01** [comment]
I tried the command dotnet new -i Microsoft.Maui.Templates::6.0.200-preview.14.5099  and it says they are already installed.  Created another new project same error with the blazor template.   So decided to uninstall the visual studio 2022 preview version and start from scratch.   from visual studio installer loadded vs 2022 professional preview version  then ran this command again and still same issue the template will not run as a windows machine .  
![Screenshot 2022-03-25 075033](https://user-images.githubusercontent.com/11353230/160116161-af37ad56-a673-4cef-9d5f-65f821c34ee8.png)
 What version of the Microsoft.WindowsAppSDK should I be running?

**Comment by jfversluis** [comment]
Hm that's strange. Did you try my other suggestion and add those contents to your Package.appxmanifest file? Does that fix it?

**Comment by Redth** [comment]
Let's do the opposite, `dotnet new -u Microsoft.Maui.Templates`  since installing templates manually overrides what's installed in the workload or by VS and is not the desired behaviour generally.
