### ISSUE TITLE
[iOS] Preview 14 Shell Tabbar Renders as Blank White Screen on iOS

### ISSUE THREAD

**Issue by kbarnett7** [dotnet/maui#5549]
### Description

After migrating from Preview 13 to 14, MAUI Shell apps that use a Tabbar renders as a blank white screen on iOS simulators. The Tabbar renders as expected on Android emulators. Debugging through the code, the page gets constructed and initialized as expected without issue or exception. But nothing gets rendered on the screen.

iOS Simulator
![Prev14ShellTabBarBug](https://user-images.githubusercontent.com/68033841/159938346-08affaf6-1c81-4e5f-b6c4-07ceaa13e24a.png)

Android Emulator
![Prev14ShellTabBarBug_Android](https://user-images.githubusercontent.com/68033841/159940374-93043658-bad0-45c1-92fd-46de5c144ca5.png)

### Steps to Reproduce

1. Unzip the solution in [MauiShell.zip](https://github.com/dotnet/maui/files/8342319/MauiShell.zip).
2. Build the solution.
3. Run the app on an iOS Simulator.
4. You should see a blank white page rendered to the screen (if the bug doesn't occur, you'll see a "Welcome to Main Page" label).

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

Using a flyout menu instead (though this also has issues in Preview 14, but with an actual workaround. See issue: https://github.com/dotnet/maui/issues/5550)

**Comment by Mephisztoe** [comment]
I am experiencing the same problem and would like to add: In DarkMode, the screen is pitch black. No content rendered.

**Comment by jfversluis** [comment]
@PureWeen was this part of the bugs we fixed for Shell?

**Comment by PureWeen** [comment]
> @PureWeen was this part of the bugs we fixed for Shell?

Yea, tested and this is fixed on RC1
