### ISSUE TITLE
[iOS] Preview 14 Shell Flyout Menu Renders Fullscreen when App Initially Opens

### ISSUE THREAD

**Issue by kbarnett7** [dotnet/maui#5550]
### Description

After migrating from Preview 13 to 14, MAUI Shell apps that use a Flyout menu renders across the entire page, taking up the entire screen, and swiping it to try to close the menu has no effect. Because the flyout takes up the entire screen it makes it seem like clicking the buttons does nothing. The flyout menu renders as expected on Android emulators.

iOS Simulator
![Prev14ShellFlyoutBug_iOS](https://user-images.githubusercontent.com/68033841/159942983-d5139b2c-b2fa-43e9-8a25-af4bc7a6dc15.png)

Android Emulator
![Prev14ShellFlyoutBug_Android](https://user-images.githubusercontent.com/68033841/159943016-3e8663fd-ceba-480f-aebc-b0a0ccd835b7.png)

### Steps to Reproduce

1. Unzip the solution in [MauiShell.zip](https://github.com/dotnet/maui/files/8342548/MauiShell.zip).
2. Build the solution.
3. Run the app on an iOS Simulator.
4. You should see the flyout menu rendered across the entire screen.

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

Swipe the edge of the screen LEFT to RIGHT, as if you are opening the flyout menu like normal using the swipe action. The full-screened flyout disappears and the regular flyout menu opens as expected. It can then be closed and clicked as expected and the app can be used as expected.

**Comment by XamlTest** [comment]
Verified repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main] on iOS. Repro with above project.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/pull/5468 this will be fixed on RC1
