### ISSUE TITLE
Missing TextColor in MenuBar

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#5554]
### Description

Setting the NavigationBar colors is not changing the colors of the MenuBar but the worst thing is that it can make using the menu very complex, because you can't see it!

![bug-menu](https://user-images.githubusercontent.com/6755973/159977717-ee547913-4a55-48da-89e4-483e0c13015b.gif)

### Steps to Reproduce

1. Download the sample [MenuPlayground.zip](https://github.com/dotnet/maui/files/8344090/MenuPlayground.zip)
2. Launch the sample in any platform, for example, Windows.
3. Try to tap in any menu item. 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS

### Affected platform versions

Windows SDK 10.0.17134.0

**Comment by v-longmin** [comment]
Verified the issue on windows, it's repro. thanks. repro project:
[MenuPlayground.zip](https://github.com/dotnet/maui/files/8346739/MenuPlayground.zip)

**Comment by eerhardt** [comment]
Unfortunately, WinUI's MenuBarItem doesn't allow the foreground color to be set. See https://github.com/microsoft/microsoft-ui-xaml/issues/7070.

We will need to workaround this issue ourselves in order to get the text color of the Menu to be set correctly.

**Comment by kristinx0211** [comment]
repro on windows and android with vs 17.3.0 Preview 2.0 [32506.368.main].
