### ISSUE TITLE
After upgrade to 2022 17.2 Preview 2 margin and padding require XAML format on compile, CSS format works after hot swapping when app is running

### ISSUE THREAD

**Issue by paaltuv** [dotnet/maui#5556]
### Description

Upgraded to 2022 17.2 Preview 2 with recommended path (uninstall sdk, uninstall vs, install both with latest version).

Before upgrade this (CSS format) compiled without issue, after upgrade it does not
```
<StackLayout Margin="50 50">
```
Warning:
_1>Pages\LoginPage.xaml(35,25): XamlC error XFC0040: Cannot convert value "0 50" to "Microsoft.Maui.Thickness"._

If I change the code to use commas instead of spaces (XAML format) it compiles.
```
<StackLayout Margin="50,50">
```

Annoying as the XAML format has the definitions in other order than CSS, so I have to rewrite all the definitions.

### Steps to Reproduce

1. Create a .NET MAUI app.
2. Add a margin with spaces to an element.
3. Compile (crashes with above warning from XcamlC)
4. Replace space in margin definition with comma
5. Compile (should work)
6. Observe margin works.
7. Replace comma in margin definition with space.
8. Observe margin works.
9. Stop application
10. Compile (crashes with above warning from XcamlC)

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12 Emulator, API 31

### Did you find any workaround?

Nope

**Comment by kristinx0211** [comment]
verified repro with vs 17.2.0 Preview 3.0 [32323.622.main], using margin with spaces to an element. 
![image](https://user-images.githubusercontent.com/99457000/160046321-af178b77-cb26-4b3b-a510-9221f9dafce6.png)

**Comment by paaltuv** [comment]
@kristinx0211 Thanks for confirming it.

I've been trying to figure out what the issue is. Looks like the error message is thrown by [src/Core/src/Converters/ThicknessTypeConverter.cs](https://github.com/dotnet/maui/commit/c40c6e773c48c995fcea28b71ee1dcf3a4bd1a1b#diff-fc7a47b35ccaf4006851cca738c7455d6f2de611123f19b623a4410e68a7309c), and the only change recently was this one https://github.com/dotnet/maui/commit/c40c6e773c48c995fcea28b71ee1dcf3a4bd1a1b# made by @jonathanpeppers . LGTM tho, so I don't really know why this would happen

**Comment by paaltuv** [comment]
https://github.com/dotnet/maui/blob/18e0f4ebbcca7c904ccdb67e6439cb72382e2a40/src/Controls/src/Build.Tasks/CompiledConverters/ThicknessTypeConverter.cs does not support CSS format. Could this be it?

**Comment by v-longmin** [comment]
@paaltuv Could you share your repro project for us, thanks?

**Comment by jfversluis** [comment]
@StephaneDelcroix this seems like your area. Any recent changes might've caused this?

**Comment by StephaneDelcroix** [comment]
this is intended.

runtime ThicknessTypeConverter accepts both syntax, even if it's undocumented. For perf purposes, we pre-compile value of Thickness during XamlC, and enforce the correct syntax.

relevant commits: https://github.com/dotnet/maui/commit/0a0407ac3def5c74ddda5eadf47d6afdd60f94ec and https://github.com/dotnet/maui/commit/231b9c6dfd913062595704ea1acf8f91f9b2f75d
