### ISSUE TITLE
Blazor Hybrid Mac Catalyst Dev Tools not Supported

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#5561]
It's not possible to open the dev tools menu for mac catalyst applications running Blazor Hybrid (WKWebView).

Others are reporting this issue too: https://apple.stackexchange.com/questions/416277/how-to-inspect-safari-web-inspector-aka-devtools-on-devtools

Dev Resources:
- https://developer.apple.com/forums/thread/657413
- https://webkit.org/web-inspector/enabling-web-inspector/

Tried adding entitlements:

```xml
	<key>com.apple.security.network.client</key>
	<true/>
	<key>com.apple.webinspector.allow</key>
	<true/>
```

Trying to open dev tools (Web Inspector) via:
- OPTION+CMD+I
- Safari -> Develop menu
- Right click -> inspect

I've confirmed the AddBlazorDevTools is appropriately configured

**Comment by TanayParikh** [comment]
Reported to Apple: https://feedbackassistant.apple.com/feedback/9972022

**Comment by TanayParikh** [comment]
Issue has been acknowledged by Apple, however the workaround proposed requires debugging with XCode, which isn't feasible with MAUI (as far as I know).

**Comment by zengxs** [comment]
Add entitlement `com.apple.security.get-task-allow = YES`, see https://github.com/dotnet/maui/issues/7706#issuecomment-1210106684

**Comment by TanayParikh** [comment]
> Add entitlement `com.apple.security.get-task-allow = YES`, see [#7706 (comment)](https://github.com/dotnet/maui/issues/7706#issuecomment-1210106684)

Thanks @zengxs, fix has been confirmed. We'll discuss how we want to surface this for users.
