### ISSUE TITLE
border bug

### ISSUE THREAD

**Issue by ialbert-AUT** [dotnet/maui#5567]
### Description

The red border is not drawn on Windows at all, lower and right edges are missing on Android.

	<Border Stroke="Red" StrokeShape="Rectangle" StrokeThickness="10" Padding="20" Margin="20">
		<Image Source="dotnet_bot.png" BackgroundColor="Black"
		   VerticalOptions="Start" />
	</Border>

If you set Margin to 10 the border is okay on Android but not shown on Windows.

Windows:
![image](https://user-images.githubusercontent.com/61751571/160091280-57300180-e3b0-4dc5-93e5-0cb65e5d8be8.png)

Android:
![Screenshot_1648199473](https://user-images.githubusercontent.com/61751571/160091059-ae27d7ba-d7e1-453e-8a9d-dbf474869bc8.png)

### Steps to Reproduce

<Border Stroke="Red" StrokeThickness="10" Padding="20" Margin="20">
	<Image Source="dotnet_bot.png" BackgroundColor="Black"
	   VerticalOptions="Start" />
</Border>

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 31

**Comment by VincentBu** [comment]
Verified with 17.2.0 preview 2.1. The red border doesn't show on Windows(but show on Android).

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue on current main branch:
![image](https://user-images.githubusercontent.com/6755973/160370539-61748223-2ecc-43ad-b663-fd8632c06d44.png)
