### ISSUE TITLE
bad grid layout

### ISSUE THREAD

**Issue by ialbert-AUT** [dotnet/maui#5571]
### Description

The width of the first column should not change when I change the height of the window.

```csharp
Content = new Grid
		{
			ColumnDefinitions = Columns.Define(Auto, Star, Auto),
			RowDefinitions = Rows.Define(Auto, Star, Auto),
			Padding = new Thickness(10),

			Children = {
				new Label { Text = "Pick image: ", Margin=20, VerticalOptions=Center, BackgroundColor=Colors.Red },
				new Entry { IsReadOnly = true, Margin=20 }.Column(1),
				new Button { Text = "Pick...", Margin=20 }.Column(2),

				new Image { Source="dotnet_bot.png" }.Row(1).ColumnSpan(3),

				new HorizontalStackLayout
				{
					HorizontalOptions = Center,
					Children = { new Button { Text = "OK", Margin = 20 }, new Button { Text="Cancel", Margin = 20 } }
				}.Row(2).ColumnSpan(3)
			}
		};
```

### Steps to Reproduce

```csharp
Content = new Grid
		{
			ColumnDefinitions = Columns.Define(Auto, Star, Auto),
			RowDefinitions = Rows.Define(Auto, Star, Auto),
			Padding = new Thickness(10),

			Children = {
				new Label { Text = "Pick image: ", Margin=20, VerticalOptions=Center, BackgroundColor=Colors.Red },
				new Entry { IsReadOnly = true, Margin=20 }.Column(1),
				new Button { Text = "Pick...", Margin=20 }.Column(2),

				new Image { Source="dotnet_bot.png" }.Row(1).ColumnSpan(3),

				new HorizontalStackLayout
				{
					HorizontalOptions = Center,
					Children = { new Button { Text = "OK", Margin = 20 }, new Button { Text="Cancel", Margin = 20 } }
				}.Row(2).ColumnSpan(3)
			}
		};
```

short:
![image](https://user-images.githubusercontent.com/61751571/160112844-ee425735-9723-4101-b50a-fd2895a1ad5f.png)

tall:
![image](https://user-images.githubusercontent.com/61751571/160112871-c7fe4278-6cd2-4b88-993f-6cf5126fe110.png)

I expect the first column to be the width of the label in the first row.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows sdk 10.0.19041

**Comment by v-longmin** [comment]
Could you share your repro project for us so that we can reproduce this issue? thanks.

**Comment by ialbert-AUT** [comment]
here you go: https://github.com/ialbert-AUT/Bug_GridLayout.App

**Comment by v-longmin** [comment]
Verified the issue on Windows, it's repro. Repro project:
[Bug_GridLayout.App-master.zip](https://github.com/dotnet/maui/files/8361730/Bug_GridLayout.App-master.zip)

**Comment by davidortinau** [comment]
Not reproducible using main (rc3). Closing as fixed.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/41873/165997550-7027808d-9c08-4773-bfaf-ce3b17e1a882.png">
