### ISSUE TITLE
Boxview corner radius not working in Mac OS and iOS

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#5572]
### Description

We have created the application with box view and box view corner radius not working on Mac OS and iOS

```

            Grid customGrid = new Grid();
            BoxView boxView = new BoxView();
            boxView.HeightRequest = 100;
            boxView.WidthRequest = 100;
            boxView.BackgroundColor = Colors.Red;
            boxView.CornerRadius = new Microsoft.Maui.CornerRadius(5);
            customGrid.HorizontalOptions = LayoutOptions.Center;
            customGrid.VerticalOptions = LayoutOptions.Center;
            customGrid.Add(boxView);
            this.Content = customGrid;

```

**Expected output:**

![Image](https://user-images.githubusercontent.com/44917578/160119299-4fc679bf-0ce3-44a5-982e-83da5610f101.png)

**Actual output:**

![Screen Shot 2022-03-25 at 5 42 08 PM](https://user-images.githubusercontent.com/44917578/160119233-f50a81e4-4660-47f7-9e54-1d5d6430ba9f.png)

### Steps to Reproduce

1. Create the sample with the above code
2. Run the sample on Mac OS and iOS
3. Box view corner radius not working

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No

### Relevant log output

```shell
Not Applicable
```

**Comment by Redth** [comment]
Can you try using the Border control instead?

**Comment by Sasikumar3595** [comment]
@Redth ,

We are tried with border control, but the border control does not work correctly on resizing (width or height).
Reference: https://github.com/dotnet/maui/issues/5464

**Comment by samhouts** [comment]
The CornerRadius now applies properly, but now BackGroundColor does not. See #6592 for that issue. Closing this one, since the original issue is resolved.

**Comment by SteveJML** [comment]
Setting the background color sets the whole control to the chosen color ignoring the CornerRadius, setting Color=Red instead of BackGroundColor=Red respects the CornerRadius.
