### ISSUE TITLE
UILabel VerticalTextAlignment not working on iOS when there's a background

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#5575]
https://github.com/dotnet/maui/pull/3714#issuecomment-1078414056

**Comment by davidortinau** [comment]
What should the default be, start or center? Here's what I'm seeing on mac and ios:

- the first label has no bg and renders the text vertical start 
- the second label has a bg and renders text vertical center
- in neither case is vertical text alignment specified

<img width="804" alt="Screen Shot 2022-04-29 at 1 03 29 PM" src="https://user-images.githubusercontent.com/41873/165998944-e24a47e4-bf51-4047-9475-e5117477b37c.png">

```
<ScrollView>
   <VerticalStackLayout Margin="12" BackgroundColor="Grey">
        <Label Text="please center vertically" HeightRequest="100"/>
        <Label Text="please center vertically" HeightRequest="100" BackgroundColor="Yellow"/>
   </VerticalStackLayout>
</ScrollView>
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 3.0. The issue does not repro on iOS 16.4 emulator with below Project:
[5575.zip](https://github.com/dotnet/maui/files/11245794/5575.zip)
![image](https://user-images.githubusercontent.com/97647558/232368045-8a4a30f1-dd98-4082-bef1-564806194a80.png)

**Comment by NonameMissingNo** [comment]
> Verified this on Visual Studio Enterprise 17.6.0 Preview 3.0. The issue does not repro on iOS 16.4 emulator with below Project: [5575.zip](https://github.com/dotnet/maui/files/11245794/5575.zip) ![image](https://user-images.githubusercontent.com/97647558/232368045-8a4a30f1-dd98-4082-bef1-564806194a80.png)

What about if you don't have VerticalTextAlignment set?

**Comment by XamlTest** [comment]
If delete VerticalTextAlignment set, the default is at the top.
![image](https://user-images.githubusercontent.com/97647558/232953561-9218476a-8f0a-4e2f-89c4-d1b0b1750235.png)
