### ISSUE TITLE
Shift Handler?.UpdateValue to happen after all PropertyChanged events have fired

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#5587]
Currently our `Handler?.UpdateValue` call fires during the top call here from `BindableObject`

![image](https://user-images.githubusercontent.com/5375137/160203792-d329afbb-9bbf-4b8e-96c5-e5d37a67fc60.png)

This means that sometimes the `Handler` will have a premature vision of the world. The Handler update should fire after as many of the `PropertyChanged` events have settled as possible.

For example it leads to issues like this

https://github.com/dotnet/maui/pull/5586

The `Parent` on the `FormattedText` is set inside the `BP.OnPropertyChanged` which fires after the `Handler?.UpdateValue` fires. So anything the `BP.OnPropertyChanged` changes will now have to re-propagate.

**Comment by antonfirsov** [comment]
@PureWeen should we consider bringing other events which fire in `OnPropertyChanged` after `property.PropertyChanged` or are we fine with a minimal solution that pushes `Handler?.UpdateValue` after all the other events?

Is this issue mostly about validation whether such a minimal change breaks something?

**Comment by PureWeen** [comment]
Related 
https://github.com/dotnet/maui/pull/22347

I think we could clean up 22347 once we conceive of how we want this to work. 

We should probably move the handler update code to fire about here
https://github.com/dotnet/maui/blob/28e9cbb6d8e932fa04302d2e42bb8003dfe80d4d/src/Controls/src/Core/BindableObject.cs#L645

The difficulty comes with maintaining behavior when users manually call OnPropertyChanged
