### ISSUE TITLE
BarBackgroundColor and BarTextColor don't change color on Android

### ISSUE THREAD

**Issue by coen22** [dotnet/maui#5590]
### Description

When the BarTextColor and BarBackgroundColor are set, Colors of the tab bar aren't affected.

Colors are defined as follows (default from template):

```
<drawing:Color x:Key="PrimaryColor">#512bdf</drawing:Color>
<drawing:Color x:Key="SecondaryColor">White</drawing:Color>
```

Colors are applied. The expected behaviour is a blue/indigo background with white text.
The result however is not affected by whatever colors are chosen, but falls back to default (white background with indigo text).

```
<Style TargetType="TabbedPage">
    <Setter Property="BarTextColor" Value="{DynamicResource SecondaryColor}" />
    <Setter Property="BarBackgroundColor" Value="{DynamicResource PrimaryColor}" />
</Style>
```

The same behaviour occurs when the colors are defined as properties of the tabbed page.

```
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Two2Tango.MainPage"
             BarBackground="{DynamicResource PrimaryColor}">
             ...
```

It's probably something that still has to be implemented.
So anyway, keep up the nice work. I'm looking forward to the next preview :)

### Steps to Reproduce

1. Create a new project from template

2. Add the styling for TabbedPage

3. Change the ContentPage to a TabbedPage 

```
<TabbedPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Two2Tango.MainPage"
             BarBackground="{DynamicResource PrimaryColor}">

    <TabbedPage.Children>
        <ContentPage Title="People">
            <ScrollView>
                <Grid RowSpacing="25" RowDefinitions="Auto,Auto,Auto,Auto,*"
                        Padding="{OnPlatform iOS='30,60,30,30', Default='30'}">

                    <Label 
                        Text="Hello, World!"
                        Grid.Row="0"
                        SemanticProperties.HeadingLevel="Level1"
                        FontSize="32"
                        HorizontalOptions="Center" />

                    <Label 
                        Text="Welcome to .NET Multi-platform App UI"
                        Grid.Row="1"
                        SemanticProperties.HeadingLevel="Level1"
                        SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                        FontSize="18"
                        HorizontalOptions="Center" />

                    <Label 
                        Text="Current count: 0"
                        Grid.Row="2"
                        FontSize="18"
                        FontAttributes="Bold"
                        x:Name="CounterLabel"
                        HorizontalOptions="Center" />

                    <Button 
                        Text="Click me"
                        FontAttributes="Bold"
                        Grid.Row="3"
                        SemanticProperties.Hint="Counts the number of times you click"
                        Clicked="OnCounterClicked"
                        HorizontalOptions="Center" />

                    <Image Grid.Row="4"
                        Source="dotnet_bot.png"
                        SemanticProperties.Description="Cute dot net bot waving hi to you!"
                        WidthRequest="250"
                        HeightRequest="310"
                        HorizontalOptions="Center" />

                </Grid>
            </ScrollView>
        </ContentPage>
        <ContentPage Title="People">
            <ScrollView>
                <Label 
                    Text="Hello, World!"
                    Grid.Row="0"
                    SemanticProperties.HeadingLevel="Level1"
                    FontSize="32"
                    HorizontalOptions="Center" />
            </ScrollView>
        </ContentPage>
    </TabbedPage.Children>
</TabbedPage>
```

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 10, but it's likely most versions

### Did you find any workaround?

Partially, by changing the colors in the android colors.xml, but this only affected the text color.

As soon as I added a styles.xml, the project would no longer compile, but this might be because of the Visual Studio Mac 17.1 preview. Something went wrong with the build configuration. But that's a different issue.

### Relevant log output

```shell
This is the error message I got after adding a styles.xml


/usr/local/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(897,5): error MSB3072: The "Exec" task needs a command to execute. [/Users/coenhacking/Projects/Two2Tango/Two2Tango.csproj]
/usr/local/share/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(897,5): error MSB6011: Invalid parameters passed to the Microsoft.Build.Tasks.Exec task. [/Users/coenhacking/Projects/Two2Tango/Two2Tango.csproj]
    0 Warning(s)
    2 Error(s)
```
```

**Comment by VincentBu** [comment]
repro on Android emulator with 17.2.0 preview 2.1
![image](https://user-images.githubusercontent.com/44959937/160312431-1ed563a7-6850-4248-bd5f-bd4b43160681.png)

**Comment by coen22** [comment]
> repro on Android emulator with 17.2.0 preview 2.1
> ![image](https://user-images.githubusercontent.com/44959937/160312431-1ed563a7-6850-4248-bd5f-bd4b43160681.png)

Ah yeah, that’s different behaviour. But it’s not the colours of the tab bar (or action bar) that are affected. Which is what I was expecting.

**Comment by antonfirsov** [comment]
I think I can reproduce some points from this issue, but not others. @coen22 can you please upload a self-contained repro project to avoid ambiguity?

**Comment by coen22** [comment]
I can confirm that all issues mentioned here were fixed in RC

> I think I can reproduce some complaints from this issue, but not others. @coen22 can you please upload a self-contained repro project to avoid ambiguity?

@antonfirsov thanks for looking into it, but I've tried to reproduce the issues in RC and they seem to be fixed.
