### ISSUE TITLE
Info.plist editor mixes line endings

### ISSUE THREAD

**Issue by toddlucas** [dotnet/maui#5597]
### Description

When using the Info.plist editor in VS 2022 (17.2.0) Preview 2.0, the editor saves part of the file with LF endings while leaving the remainder with CR/LF endings.

This part of the file retains CR/LF:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
```

The remainder now has LF endings, causing a large diff and mixed line endings.

### Steps to Reproduce

1. Start a MAUI project with iOS platform
2. Open the Info.plist using the form-based editor
3. Add a bundle identifier, for example
4. Save

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by dais-set** [comment]
It was the same in the preview 13 (and Visual Studio 17.1 preview), no change with the new service release (line endings are still mixed)

**Comment by VincentBu** [comment]
not repro with vs main build(32621.322)

**Comment by jfversluis** [comment]
Seems this is not reproduced and not a lot of traction here. Also, if this is still affecting you, please report this through Visual Studio as this is a tooling issue. You can do so by going to Help > Provide Feedback > Report a Problem. That will make it show up for the right team.

Thanks!
