### ISSUE TITLE
Frame does not resize

### ISSUE THREAD

**Issue by mfe-** [dotnet/maui#5600]
### Description

When resizing the main window with root content `Frame` it doesn't get resized.
The provided xaml code works in **Xamarin Forms**
![xamarinforms_frame_resize](https://user-images.githubusercontent.com/3492683/160276452-6bc9d382-e829-45fd-a551-85d2fbeae82f.gif)

Behavior on **dotnet maui** 
![maui_frame_doesnot_resize](https://user-images.githubusercontent.com/3492683/160276446-cdfc8d0c-9080-4c7a-8987-62eafde72bd5.gif)

### Steps to Reproduce

1. Create an ew Maui Project. 
2. Add as content in `MainPage.xaml`
3. 
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp3.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">

    <Frame CornerRadius="30" 
           HasShadow="True"
           IsClippedToBounds="True"
           Padding="0">
        <Grid RowSpacing="25" RowDefinitions="Auto,Auto,Auto,Auto,*" Margin="0"
              Padding="{OnPlatform iOS='30,60,30,30', Default='30'}" Background="Red">

            <Label 
                Text="Hello, World!"
                Grid.Row="0"
    
                FontSize="32"
                HorizontalOptions="Center" />

            <Label 
                Text="Welcome to .NET Multi-platform App UI"
                Grid.Row="1"

                FontSize="18"
                HorizontalOptions="Center" />

            <Label 
                Text="Current count: 0"
                Grid.Row="2"
                FontSize="18"
                FontAttributes="Bold"
                x:Name="CounterLabel"
                HorizontalOptions="Center" />

            <Button 
                Text="Click me"
                FontAttributes="Bold"
                Grid.Row="3"
   

                HorizontalOptions="Center" />

            <Image Grid.Row="4"
                Source="dotnet_bot.png"
    
                WidthRequest="250"
                HeightRequest="310"
                HorizontalOptions="Center" />

        </Grid>
    </Frame>
</ContentPage>
```

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041, 10.0.17763.0

### Did you find any workaround?

Switch to XF

**Comment by JohnHDev** [comment]
@mfe- I am seeing the same issue, although mine is a more complex layout involving a grid with a frame within it. Thank you for reporting, it saves me having knock up a simple example!

**Comment by XamlTest** [comment]
Verified repro with Visual Studio Enterprise 2022 17.2.32317.152 on Windows. Repro Project: [5600.zip](https://github.com/dotnet/maui/files/8358885/5600.zip)

**Comment by davidortinau** [comment]
Still reproducible on main (rc3)
