### ISSUE TITLE
Button with image sized incorrectly on Windows

### ISSUE THREAD

**Issue by kla50** [dotnet/maui#5601]
### Description

![image](https://user-images.githubusercontent.com/66872908/160282656-9ad33870-a9c3-49c4-b241-86bd51e74674.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/66872908/160283226-338301f2-eaa1-4cca-a8b7-d4258e6b659c.png)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 22H2 22581.100, WindowsAppSDK 1.0.1, MAUI 6.0.200-preview.14.5099, .NET SDK 6.0.300-preview.22154.4

**Comment by XamlTest** [comment]
Verified repro with Visual Studio Enterprise 2022 17.2.32317.152 on Windows. Repro Project: [5601.zip](https://github.com/dotnet/maui/files/8358953/5601.zip)
