### ISSUE TITLE
Shell view is not working properly.

### ISSUE THREAD

**Issue by MahmudX** [dotnet/maui#5603]
### Description

In Xamarin we had very rich ShellView support but here in  .NET MAUI ShellView is not working as it was supposed to do. Let's take a look at the following screenshot -
![Screenshot_1648432376](https://user-images.githubusercontent.com/16564582/160313633-600d49f8-d409-462a-aef6-e1eb83f9496e.png)

1. You can see that only `Shell.FlyoutHeaderTemplate` seems to be working properly but it's not, the `VerticalOptions="Center"` is not working.
2. The background of the entire shell view is black. From where is this color coming from and how to change this? If I set `<Shell BackgroundColor="White" ...>`, It changes the `ActionBar`'s bg color.
3. The `FlyoutItem` is not aligned and positioned well too! 
4. Same goes for the `Shell.FlyoutFooter` too! Why is this at the end of the view! 

The same view in Xamarin.Forms -

![Screenshot_1648435265](https://user-images.githubusercontent.com/16564582/160317434-2e4d40e1-e355-40e3-86c2-d165e6f7dc3d.png)

The MAUI shell view should look like this too!

### Steps to Reproduce

1. Create a New .NET MAUI App with AppShell view.
2. Paste the following code in the **AppShell.xaml** file: 
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<Shell xmlns="http://schemas.microsoft.com/dotnet/2021/maui" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="MyAwesomeApp.AppShell" xmlns:Pages="clr-namespace:MyAwesomeApp" Title="My Awesome App">
    <Shell.FlyoutHeaderTemplate>
        <DataTemplate>
            <Grid BackgroundColor="#1a1a1a" HeightRequest="100">
                <Label Text="MyApp" TextColor="White" FontAttributes="Bold" FontSize="Title" VerticalOptions="Center" HorizontalOptions="Center"/>
            </Grid>
        </DataTemplate>
    </Shell.FlyoutHeaderTemplate>
    <FlyoutItem Title="Home">
        <FlyoutItem.FlyoutIcon>
            <FontImageSource Glyph="&#xE946;" Color="Black" FontFamily="SegoeFluentIcons"></FontImageSource>
        </FlyoutItem.FlyoutIcon>
        <Tab>
            <ShellContent ContentTemplate="{DataTemplate Pages:MainPage}" />
        </Tab>
    </FlyoutItem>
    <FlyoutItem Title="Home">
        <FlyoutItem.FlyoutIcon>
            <FontImageSource Glyph="&#xE946;" Color="Black" FontFamily="SegoeFluentIcons"></FontImageSource>
        </FlyoutItem.FlyoutIcon>
        <Tab>
            <ShellContent ContentTemplate="{DataTemplate Pages:MainPage}" />
        </Tab>
    </FlyoutItem>
    <Shell.FlyoutFooter>
        <StackLayout HorizontalOptions="StartAndExpand">
            <Label Text="My Awesome App" HorizontalOptions="Start" TextColor="GhostWhite" FontAttributes="Bold"/>
        </StackLayout>
    </Shell.FlyoutFooter>
</Shell>
```
3. Run the app.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11, API 30

**Comment by v-longmin** [comment]
@MahmudX Can you share us with the corresponding .cs code so that we can reproduce the bug? Thanks.

**Comment by MahmudX** [comment]
@v-longmin, Here is the corresponding .cs file's content.

```cs
public partial class AppShell : Shell
{
  public AppShell()
  {
    InitializeComponent();
  }
}
```

Nothing fancy.

**Comment by v-longmin** [comment]
@MahmudX Could you share your repro project for us as we cannot reproduce this issue by the code as you mentioned the step reproduce? thanks.

**Comment by shimingsg** [comment]
@MahmudX , is this your expected except VerticalOptions="Center"? seems the VerticalOptions doesn't work.
verified with 17.2.0 Preview 3.0 [32329.440.main]
![image](https://user-images.githubusercontent.com/20982341/160743834-0ec7567a-6dfe-4b75-b3ff-1a948ee4c254.png)

demo: 
[MauiApp5603.zip](https://github.com/dotnet/maui/files/8376718/MauiApp5603.zip)

**Comment by MahmudX** [comment]
@v-longmin here you go https://github.com/MahmudX/AwesomeMaui-5603

**Comment by nacompllo** [comment]
I confirm that this is still happening in the RC1 version:

In Android the FlyoutFooter is shown misaligned with respect to the FlyoutHeader:

<img width="443" alt="Issue05" src="https://user-images.githubusercontent.com/20904914/164447009-93abb4ac-3dbb-48aa-9155-d89a8760aba7.png">

On Windows it works fine:

<img width="1439" alt="Issue04" src="https://user-images.githubusercontent.com/20904914/164447006-4f2fb910-bce5-477d-859f-2be39590c50c.png">

This is my AppShell code:

```
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiCollectionView.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiCollectionView">

    <Shell.FlyoutHeader>
        <StackLayout BackgroundColor="Green"
            Padding="0,20,0,20"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="End">
            <Label
                Text="FlyoutHeader"
                FontSize="18"
                TextColor="White"
                HorizontalOptions="Center"
                VerticalTextAlignment="Start" />
        </StackLayout>
    </Shell.FlyoutHeader>

    <Shell.FlyoutFooter>
        <StackLayout BackgroundColor="Red"
            Padding="0,20,0,20"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="End">
            <Label
                Text="FlyoutFooter"
                FontSize="18"
                TextColor="White"
                HorizontalOptions="Center"
                VerticalTextAlignment="Start" />
        </StackLayout>
    </Shell.FlyoutFooter>

    <FlyoutItem Route="menu"
                FlyoutDisplayOptions="AsMultipleItems">
        <ShellContent Route="cats"
                      Title="Cats"
                      ContentTemplate="{DataTemplate local:MainPage}" />
        <ShellContent Route="dogs"
                      Title="Dogs"
                      ContentTemplate="{DataTemplate local:MainPage}" />
    </FlyoutItem>

    <TabBar>
        <Tab Title="Cats"
            Icon="dotnet_bot.svg">
            <ShellContent
                ContentTemplate="{DataTemplate local:MainPage}">
            </ShellContent>        
        </Tab>
        <Tab Title="Dogs"
            Icon="dotnet_bot.svg">
            <ShellContent
                ContentTemplate="{DataTemplate local:MainPage}">
            </ShellContent>        
        </Tab>
    </TabBar>
</Shell>
```
