### ISSUE TITLE
TLS 1.2 in android option (it does not exists in VS Preview 17.1)

### ISSUE THREAD

**Issue by thevirtualdj** [dotnet/maui#5604]
### Description

Where to set TLS 1.2 in android options (it does not exists in VS Preview 17.1)
Can find it in Xamarin but no option to set it on .NET MAUI. project properties.
https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/transport-layer-security?tabs=windows
Is there an option in VS somewhere (really got into it but cannot find it)?

And not only one for now.. Please advise.

https://docs.microsoft.com/en-us/answers/questions/658469/use-httpclient-in-maui.html

### Public API Changes

TLS 1.2 in android option (it does not exists in VS Preview 17.1)

### Intended Use-Case

TLS 1.2 in android option (it does not exists in VS Preview 17.1)

**Comment by jonathanpeppers** [comment]
@thevirtualdj these settings don't exist in .NET 6, so some of these settings actually need to be removed from the Project Options pages. We're tracking this internally [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1530132).

What are you looking to do exactly? Do the default values work for your case? Thanks!

**Comment by ShiiikK** [comment]
I need this setting too. Cant get data with my RestApi (RestSharp) while running Android. it works on Windows machine, but on Android not.

**Comment by jonathanpeppers** [comment]
@ShiiikK can you file a new issue?

The issue here is about the setting -- which is actually not needed. .NET 6 supports TLS 1.2, and you don't need a dropdown box to enable it.

**Comment by logikonline** [comment]
@jonathanpeppers please reopen the issue.

**Comment by jonathanpeppers** [comment]
@logikonline can you file a new issue here: https://github.com/xamarin/xamarin-android/issues

Link to it here, thanks!

*This* issue is about these dropdowns:

![image](https://user-images.githubusercontent.com/840039/186438295-19ac16ac-5a4a-463f-a780-72276c4ef98e.png)

And we don't have these settings anymore in .NET 6+.

**Comment by logikonline** [comment]
@jonathanpeppers I am sorry, I see the issue.  android:usesCleartextTraffic="true" needed to be specified for Android to allow the HHTP traffic. 

Sorry, too much coffee this morning

**Comment by thevirtualdj** [comment]
I set it in AndroidManifest in MAUI App like: ![image](https://user-images.githubusercontent.com/102127/191748427-8d0160c4-431d-45e5-8ef2-63a0114a683c.png)
And still the same error.

**Comment by logikonline** [comment]
@thevirtualdj - if give me a url of the image, I may be able to assist.  It works for me.

My client initializes for the HTTP is as follows:

`httpClient = new System.Net.Http.HttpClient(new HttpClientHandler() { AutomaticDecompression = System.Net.DecompressionMethods.GZip });`

I also set a few default headers

**Comment by thevirtualdj** [comment]
Trouble is that this is Microsoft.Data.SqlClient 5.0 not HTTPClient. 

It will fail in Connection Open on MAUI app.. you can try it. 

"using System.Collections.ObjectModel;
using System.Data;
using System.Data.Common;
using Microsoft.Data.SqlClient;
//using Microsoft.Data.SqlClient;

namespace MySQLTest
{
    public static class TringSQL
    {
        public static String GetStringFromExternClass()
        {
            return "Test string!";      
        }
        public static String GetStringFromDB()
        {
           
            string connectionString = "Server =192.168.0.253,1433; Database=INSERTYOURDBHERE; User Id =sa; Password=INSERTYOURPASSHERE;Encrypt=false;TrustServerCertificate=true;";
            //string connectionString = @"Server=192.168.0.15,1433;Database=INSERTYOURDBHERE;User Id=sa;Password=INSERTYOURPASSHERE;integrated security=True;Encrypt=True;TrustServerCertificate=True;MultiSubnetFailover=true";
            //string connectionString = @"Data Source =192.168.0.15,1433;Database=INSERTYOURDBHERE; UID=sa; PWD=INSERTYOURPASSHERE; Integrated Security=true;Encrypt=false; Connection Timeout = 30;TrustServerCertificate=true;";
            string sql = "select UserName from [dbo].[OPERATORS] where OperatorId = 13";
            string ret = "";
            SqlConnection Connection = new SqlConnection(connectionString);
            
            ConnectionState ps = Connection.State;
            var tbl = new DataTable();
            var cmd = new SqlDataAdapter(sql, Connection);
            cmd.SelectCommand.CommandTimeout = 0;
            try
            {
                if (ps != ConnectionState.Open)
                    //Here it will fail to open TLS connection!
                    Connection.Open();
                cmd.Fill(tbl);
            }
            catch (DbException ex)
            {
                //error message is:
                //A connection was successfully established with the server, but then an error
                //occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
                ret = ex.Message;
            }
            finally
            {
                cmd = default;
                if (ps == ConnectionState.Closed)
                    Connection.Close();
            }
            if (tbl.Rows.Count > 0)
            {
                ret = tbl.Rows[0][0].ToString();
            }
            return ret;
        }
    }
}"

**Comment by logikonline** [comment]
@thevirtualdj sorry man.  I would never approach direct SQL connection with apps anymore. I would expose a RESTful interface.  I suppose it is also why they always ask for a github sample app to be attached to tickets.  I hope you find a workaround although you may want to undertake my approach

**Comment by jovanmhn** [comment]
These threads always end the same way, don't use direct SQL connections... Maybe we should tell MS that none of these classes should be allowed to exist at all inside MAUI projects? Isn't the whole point of .NET that everything works everywhere?
If I wanted to go the traditional way, I might as well use languages/technologies that are proven and tested, and go back to some good ol Java on Android Studio...
Anyway...
The same issue described by [thevirtualdj](https://github.com/thevirtualdj) makes EFCore non usable in MAUI android, which is why I'm here

**Comment by logikonline** [comment]
@jovanmhn I use SQLite in my XF/Maui apps exclusively because it works cross-platform, but I do not leave the device for those calls.  So the connections are to a file and not cross the wire.  I have used this tech since before Microsoft acquired it, and it is solid, but there are design patterns that I exclusively use to achieve that.

**Comment by jovanmhn** [comment]
@logikonline The main attraction of using .NET to create mobile apps for me is the ability to use powerful tools (such as Entity Framwork) that make it possible to manipluate complex (several hundred tables) SQL databases, have the ability to track changes, commit batches in the correct order without too much pain, use stored procedures, fucntions and all the good stuff, without too much hassle
How I aquire my credentials, how my SQL server is set up, and where, if at all, I keep my credentials is a completely different issue which should not be brought up in these discussions.

Doing this by through REST APIs as a "middle-man", while of course possible, makes the project considerably more complex

But that is all besides the point, we have code that works on one enviroment (possibly 2, havent tested iOS), but breaks on Android, and, in my opinion, is clearly an issue to be dealt with if we want to call MAUI true multi platform tech

**Comment by thevirtualdj** [comment]
I agree with @jovanmhn . We think that this issue for some small side apps (warehouse mgm, local apps that connect to on-premise SQL servers are still a big piece of cake. So this issue with clear text traffic on android should be solved for these apps. 
TLS 1.2 is not a problem for us to implement but we are facing so much issues to get it working on android right now. 

Currently we are trying to implement clear text traffic but no success. 

In some threads they say you should use: android:usesCleartextTraffic="true". 
Tried it, no success.  
Some of them says implement: network_security_config.xml  in Resources\xml folder or \Platform\Android\xml folder and add it to AndroidManifest.xml like:  android:networkSecurityConfig="@xml/network_security_config"
Tried it, have an issue that VS linker does not see the file at all:  resource xml/network_security_config (aka com.companyname.mysqltest:xml/network_security_config) not found. 


With TLS 1.2 no success to:

https://github.com/dotnet/SqlClient/issues/1662 

Tried everything in this thread but main issue is that it is tied to DOMAIN that is not so useful at all: 
**"set the commonName to the ServerName like this: [PCName].[Domain].local"**

So if anyone has any idea pls advise. 

We would really like to use MAUI and start developing our apps on it with SQL Server support. 
 
Thank you in advance.

**Comment by logikonline** [comment]
@thevirtualdj If you shared a repo, I would give you some time to help resolve it.  I presently use this on very large projects (north of 200+ tables @jovanmhn) with much success, but we will have to disagree around approaches.  I do see value in EF, but I chose to use a different ORM and the approach does require some middle work, although the payoff is better IMO.

If you saw above, my error posted in the stacktrace reported clearText issue.  I haven't seen your stacktrace so it likely isn't applicable to the same outcome.  I can tell you, Maui is finicky around getting everything just right to compile.  I personally preferred the different projects in XF but I can see their direction and once it is flushed out, it hopefully will grow on me.  The ability to edit the project file is better IMO and the new handlers are nicer.

If I were you, I would post a repo where it can be reproduced.  Then I can give you some constructive feedback and possibly a workaround.

**Comment by thevirtualdj** [comment]
Greetings, 

I do not agree with you. Direct access to SQL server is a great feature. Sure it needs to be encrypted on public networks. But for small usage and private nets it is indeed a great feature. 
For generic purposes we HAVE to use direct access. 
But never mind. 
Here is the repo: https://github.com/thevirtualdj/MAUISqlTestApp 

Thank in advance for your help. It is not a problem to encrypt the connection but now I am having a trouble to export SQL Server certificate and use it in this app. 
But in some cases for other users it would be good to have plain text. 
But for my case I really need a direct access (never mind even encrypted is fine, we will use certificates)

**Comment by jovanmhn** [comment]
I would follow these 2 threads, as I can see it got narrowed down to the sql client

https://github.com/dotnet/SqlClient/issues/1656
https://github.com/dotnet/SqlClient/issues/1662

although it could be a wider android certificate issue

**Comment by jovanmhn** [comment]
I found no adequate solution either, but I would assume that when it happens, it will be anounced in these threads.

**Comment by thevirtualdj** [comment]
> I found no adequate solution either, but I would assume that when it happens, it will be anounced in these threads.

Trouble is that they just closed my issues in .NET MAUI and like that is not our problem. 
It is all fine but we are running outta time and might just go native if this gets postponed any more.

**Comment by thevirtualdj** [comment]
> I found no adequate solution either, but I would assume that when it happens, it will be anounced in these threads.

I hit the subscribe button but all of these issues are just closed and moved around. I opened one here on MAUI for this and they just closed it like that is not MAUI problem. So.. will check those issues.

**Comment by janseris** [comment]
> I would follow these 2 threads, as I can see it got narrowed down to the sql client
> 
> [dotnet/SqlClient#1656](https://github.com/dotnet/SqlClient/issues/1656) [dotnet/SqlClient#1662](https://github.com/dotnet/SqlClient/issues/1662)
> 
> although it could be a wider android certificate issue

Yes this is a much wider tls android issue (I am author of these SQL Client MAUI issues)

**Comment by thevirtualdj** [comment]
Greetings, 

**Managed to solve it with cert and IP address.**
How? 

1. Create a cert with powershell for your IP address: New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname '192.168.0.15','localhost' -KeySpec KeyExchange -FriendlyName '192.168.0.15' -NotAfter (Get-Date).AddMonths(240)
(Will work with any IP address of your sql server later).

2. Set your cert in SQL Server Configuration manager. 

3. Export that certificate as Base-64 encoded X.509 (.CER) file.

4. Import that cer in Platforms\Android\Resources\raw folder (if it does not exist create it. 

5. In Platforms\Android\xml folder create nsc.xml (for me was not working if I name it network_security_config.xml)
with content: (change the data ofc IP and domain names and @raw/certname mine was called razvoj1.cer in \Platforms\Android\Resources\raw folder and my SQL server IP was 192.168.0.15 )

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
	<base-config cleartextTrafficPermitted="true">
		<trust-anchors>
			<certificates src="system" />
			<certificates src="user" />
			<certificates src="@raw/razvoj1"/>
		</trust-anchors>
	</base-config>
    <domain-config cleartextTrafficPermitted="true">
		<domain includeSubdomains="true">localhost</domain>
		<domain includeSubdomains="true">192.168.0.15,1433</domain>
		<domain includeSubdomains="true">192.168.0.15</domain>
        <domain includeSubdomains="true">RAZVOJ1</domain>
		<domain includeSubdomains="true">RAZVOJ1.localhost</domain>
		<trust-anchors>
			<certificates src="system" />
			<certificates src="user" />
			<certificates src="@raw/razvoj1"/>
		</trust-anchors>
    </domain-config>
</network-security-config>

6. In AndroidManifest add android:usesCleartextTraffic="true" and android:networkSecurityConfig = "@xml/nsc" to application tag :

<?xml version="1.0" encoding="utf-8"?>
<manifest android:targetSandboxVersion="1" xmlns:android="http://schemas.android.com/apk/res/android">
	<application android:allowBackup="true" 
				 android:icon="@mipmap/appicon" 
				 android:roundIcon="@mipmap/appicon_round"
				 **android:usesCleartextTraffic="true"** 
			         **android:networkSecurityConfig = "@xml/nsc"**
				 android:supportsRtl="true"></application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
</manifest>

7. Use this connection string: 
string connectionString = **@"Server=192.168.0.15,1433;Database=YOURDB;User Id=sa;Password=YOURPASS;Persist Security Info=True;Encrypt=True;TrustServerCertificate=True";**

8. You should be able to open SQLConnection with Microsoft.Data.SQLClient 5.0.0 and .net 7 MAUI

**Comment by jovanmhn** [comment]
its looks more or less like the solution [lcheunglci](https://github.com/lcheunglci) posted in one of the mentioned threads

its ok for testing and development, obviously cant expect random people to install random certs on their phones

**Comment by thevirtualdj** [comment]
> 



> its looks more or less like the solution [lcheunglci](https://github.com/lcheunglci) posted in one of the mentioned threads
> 
> its ok for testing and development, obviously cant expect random people to install random certs on their phones

This is actually not bad because cert is embedded in your app. For now at least we have some solution (was afraid that this will not work without domain, but it does).

**Comment by lcheunglci** [comment]
> > 
> 
> > its looks more or less like the solution [lcheunglci](https://github.com/lcheunglci) posted in one of the mentioned threads
> > its ok for testing and development, obviously cant expect random people to install random certs on their phones
> 
> This is actually not bad because cert is embedded in your app. For now at least we have some solution (was afraid that this will not work without domain, but it does). And yes [lcheunglci](https://github.com/lcheunglci) was a great help. Thank you [lcheunglci](https://github.com/lcheunglci).

I'm glad it helped, you're welcome 👍

**Comment by logikonline** [comment]
> > 
> 
> > its looks more or less like the solution [lcheunglci](https://github.com/lcheunglci) posted in one of the mentioned threads
> > its ok for testing and development, obviously cant expect random people to install random certs on their phones
> 

Sorry for the delayed reply, I was impacted by Hurricane Ian & had to evacuate.  It did work on my Azure server with .NET 6.0 but it appears you are solid now.

I didn't have to create a cert for my device, being that Azure provides one.  As a general development environment, which allows you to not worry about certs when debugging on Android (Android is very picky) - I always use NGROK since that can be set up to serve any IP with their SSL to any server.  I have used this for 3 years and can vouch it works.
