### ISSUE TITLE
Hot Restart for iOS not working in Preview 17.2.1

### ISSUE THREAD

**Issue by RichardMarsh** [dotnet/maui#5605]
### Description

Hot Restart for iOS was working before the 17.2 update.  I updated when Preview 14 of MAUI was released and since then I've not been able to get it to work again. 

Today I updated to preview 17.2.1 and still same issue occurs. See below
![image](https://user-images.githubusercontent.com/54434905/160345210-f8448123-5464-4bbd-a053-acb6eddf660c.png)

### Steps to Reproduce

1. Upgrade VS to 17.2.1
2. Enable Hot Restart for iOS
3. Try to deploy or build to local device

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

NA

### Relevant log output

```shell
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018: The "HotRestart.Tasks.DetectSigningIdentity" task failed unexpectedly.
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'Xamarin.iOS.Windows.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018: File name: 'Xamarin.iOS.Windows.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018:    at Xamarin.iOS.HotRestart.Tasks.DetectSigningIdentity.Execute()
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018: 
4>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018:
```

**Comment by jfversluis** [comment]
I guess from the context you are talking about Hot Restart as opposed to Hot Reload :)

Also mentioned [here](https://github.com/dotnet/maui/issues/3980#issuecomment-1070353521) a fix should be out soon, thanks!

**Comment by RichardMarsh** [comment]
> I guess from the context you are talking about Hot Restart as opposed to Hot Reload :)
> 
> Also mentioned [here](https://github.com/dotnet/maui/issues/3980#issuecomment-1070353521) a fix should be out soon, thanks!

Thank you for the feedback. Wasn't sure if was related or not. That said isn't 17.2.1 the servicing release?

**Comment by enricoe73** [comment]
Same thing here -   Version 17.2.0 Preview 2.1
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/62182350/160504118-f02fbf1f-79e6-492e-b253-b649b77cebaf.png">

**Comment by MichelLaplane** [comment]
Same here trying to debug or execute an app build with template .NET MAUI App (Preview) with VS 2022 Version 17.2.0 Preview 2.1 (no mosidifcation have been made, just try to execute afater generation from template :

Build started...
1>------ Build started: Project: MauiApp3, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018: The "HotRestart.Tasks.DetectSigningIdentity" task failed unexpectedly.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'Xamarin.iOS.Windows.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018: File name: 'Xamarin.iOS.Windows.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018:    at Xamarin.iOS.HotRestart.Tasks.DetectSigningIdentity.Execute()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018: 
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(20,3): error MSB4018:
1>Done building project "MauiApp3.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Is there a way to retrun to preview 13 ?

**Comment by BlueRaja** [comment]
@jfversluis Will that fix also fix iOS Hot Restart in Xamarin Forms, which is suffering from the same issue?

**Comment by MichelLaplane** [comment]
@BlueRaja Yes you're right I got the same problem with Xamarin.
