### ISSUE TITLE
Wrong targets are be compiled inside platform folders

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#5624]
### Description

As you can see the `CameraView` class is inside my `Android` folder, but VS wants to build that code for all target platforms, as you can see in the image below.

![image](https://user-images.githubusercontent.com/20712372/160510466-94571924-516a-4943-a469-ed2b91c1bc03.png)

### Steps to Reproduce

1. Create a new MAUI project;
2. Open `Platforms > Android > MainActivity`
3. Open this dropdown box (I don't know how its name)
![image](https://user-images.githubusercontent.com/20712372/160510631-a584652a-15d9-4241-b4b6-39e6cbfa14e1.png)
4. See that you can select other TFM

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

**Comment by VincentBu** [comment]
Hi @pictos, I am using vs 17.2.0 preview 2.1. I select net6.0-android and successfully run it on Android emulator.

**Comment by pictos** [comment]
Hey @VincentBu, thanks for the quick reply. You will run, but if you add more files there that may fail. And also other targets shouldn't appear inside the android folder. 

I'll push a sample code when I get home again (:

**Comment by nextfool** [comment]
I ran into this issue long time ago, my workaround for now is to remove any other targets from .csproj file when I compile/debug/publish for one specific target. Hopefully this will be fixed soon.

**Comment by jfversluis** [comment]
I think this is more of a VS/tooling issue than anything we can really do something about... Besides giving the errors it does run, right?

**Comment by pictos** [comment]
@jfversluis not sure if it's just a VS issue if I add [the rules that ](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj#L45-L74) we use on CommunityToolkit.Maui this doesn't happen, as you can see in the image below
![image](https://user-images.githubusercontent.com/20712372/160661958-c08ba1d7-fcc5-4abd-978c-42ff393e8a84.png)

That should build, but on my case it fails, as you can see in the image on the original issue. The workaround was:
remove other targets 
`<TargetFrameworks>net6.0-android</TargetFrameworks>`
then building and return the original with other targets
`<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>`

**Comment by pictos** [comment]
BTW, here's the project that I reproduce this issue
- https://github.com/pictos/CameraViewPOC

**Comment by IndianaGary** [comment]
I can add here, that I'm having a similar issue with bleed-over of Windows source code when building an Android target for one of my mobile apps. Windows builds just fine. I also get references to .NET 5.0 and .net core 3.1 libraries and I do not have either platform installed. None of the 5 projects refer to anything but .net 6.0 and/or Maui.

**Comment by PureWeen** [comment]
Closing this issue for now. This is an IDE tooling issue that should be fixed in 17.3

@IndianaGary if you can create a repro of your issue please create a new issue
