### ISSUE TITLE
Shell modal page triggers TapGestureRecognizer which lies on the page under it.

### ISSUE THREAD

**Issue by nevse** [dotnet/maui#5627]
### Description

I have a shell page that contains a tab layout with one page on which I use a TapGestureRecognizer that throws an exception on tap. I placed a button that shows the modal window. If you click on the modal window on a green rectangle (this area has TapGestureRecognizer on the previous page) then the application will crash because it triggers a tap event for the previous page.

### Steps to Reproduce

I created a project to replicate an issue and placed it [here](https://github.com/nevse/Maui-Tests-ShellExampleGestureR-).

Click on the button "Open Modal" then click the green rectangle on the opened modal page. App will crash because the TapGestureRecognizer was triggered from the previous page (it throw an exception).

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

I didn't find any workaround.

**Comment by jfversluis** [comment]
Could you please add more details about the exception? What kind of exception, what message, does it show you the stack trace?

**Comment by nevse** [comment]
Sorry for misleading you with my words about exceptions. 
The exception was raised by the tap event handler to show that it triggers event when I tap on the modal page.
So I have a page markup
```xaml
<Grid RowDefinitions="100,*">
            <Button Text="Open modal" Clicked="OnButtonClicked" />
            <Grid Grid.Row="2" BackgroundColor="Red">
                <Grid.GestureRecognizers>
                    <TapGestureRecognizer
                        NumberOfTapsRequired="1"
                        Tapped="OnTapGestureRecognizerTapped">
                    </TapGestureRecognizer>
                </Grid.GestureRecognizers>
            </Grid>
        </Grid>
```
I navigate from this page to some modal page with such markup
```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             Title="{Binding Title}"
             IconImageSource="info"
             Shell.PresentationMode="Modal"
             x:Class="ShellExampleGestureR.AboutPage2">

    <ContentPage.Content>
        <Grid RowDefinitions="300,*">
            <Label Text="Page2" />
            <Grid Grid.Row="2" BackgroundColor="Green">
            </Grid>
        </Grid>
    </ContentPage.Content>
</ContentPage>
```
And I tap on the green rectangle and OnTapGestureRecognizerTapped triggered from another page.

**Comment by RichardMarsh** [comment]
To maybe add more context, I’ve noticed that modal pages loaded via Shell Navigation does not block users from activating controls that are “underneath” the modal page (aka the previous page).

So if you have Page A with a button and you load a modal Page B, you can still click on the button from Page A even though Page A is under Page B

**Comment by kristinx0211** [comment]
run the above project on Android 12. Click on the button "Open Modal" then click the green rectangle on the opened modal page. exception throw out on method `OnTapGestureRecognizerTapped`. 
System.NotImplementedException: 'The method or operation is not implemented.
@nevse is this the same exceptions with you meet?
![image](https://user-images.githubusercontent.com/99457000/160732963-62c8f30e-28c7-44f7-8959-30a81b6b430a.png)
![image](https://user-images.githubusercontent.com/99457000/160733185-f914f18b-d953-4450-8394-6a6df7bbf785.png)

**Comment by nevse** [comment]
Yes, it is. It only shows that the tap handler is invoked from the underneath page when you tap on the modal page.
