### ISSUE TITLE
Application cannot be deployed on Android (APT error APT2000)

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#5642]
### Description

Hi, I cannot run a simple project on Android.
The basic VS 2022 MAUI application template works on Android.

What I was trying to do:
https://github.com/jsuarezruiz/netmaui-chat-app-challenge <- run this project. Because I could not build that version directly, I created a new MAUI Preview 14 project in the latest VS 2022 Preview and copied all the files manually there and linked the namespaces etc.

It works well on Windows.
It cannot be deployed on Android -> 50+ build errors with one significant - **_Xamarin error APT2000_**
I am enclosing the project in a .zip file.
[MAUITest.zip](https://github.com/dotnet/maui/files/8373607/MAUITest.zip)

I tried reinstalling all the Android and all Visual Studio. The result is the same.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2000	System cannot find file (I don't know the exact English text). (2).	MauiApp1	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.14.106\tools\Xamarin.Android.Aapt2.targets	217	

```
```

1>MauiApp1 -> C:\Users\username\Desktop\work\MAUITest\MauiApp1\bin\Debug\net6.0-android\MauiApp1.dll
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.14.106\tools\Xamarin.Android.Aapt2.targets(217,3): error APT2000: System cannot find file (I don't know the exact English text). (2).
1>Done building project "MauiApp1.csproj" -- FAILED.
```

Double-clicking the error opens this file at this location:
![image](https://user-images.githubusercontent.com/64279914/160668033-67eb9b91-8d47-4b6c-821b-d30d0427afee.png)

### Steps to Reproduce

Install VS 2022 for MAUI workload according to the tutorial on Microsoft docs.
Enable Hyper-V
Create a basic Android device (default device, default settings) in the Android Device Manager.
Try run the application on the Android device. (creating a new default device with version changed to Android 5 doesn't work either)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (API 30), Android 5 (API 21)

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified on Visual Studio Enterprise 17.2 Preview 2.1. Not repro with above project on Android.

![image](https://user-images.githubusercontent.com/97647558/160734678-d88164d8-6d0c-4785-ad19-cbad9ad8af07.png)

**Comment by janseris** [comment]
@XamlTest 
Thank you. 
What resolution do you suggest? 
Do you know any info about the error and/or how to solve it and what might be the cause? 
I am not experienced with Xamarin. 
I was using Microsoft Visual Studio Professional (now) 2022 (64-bit) - Preview
Version 17.2.0 Preview 2.1 and Community (before)

**Comment by janseris** [comment]
@Redth Hi I am seeing that the issue has tag  "s/needs-info". What info do you need me to provide to you?
Thank you.

**Comment by janseris** [comment]
Works in VS 2022 **_Professional_** latest preview

**Comment by Redth** [comment]
@janseris this works in Professional but not Enterprise? is that what you are saying?

**Comment by Redth** [comment]
@jonpryor is there any reason this should not work on Community?

**Comment by janseris** [comment]
@Redth I found the cause and created a clean minimal repro here:
https://github.com/dotnet/maui/issues/5957
