### ISSUE TITLE
App Icon not found error in Android app

### ISSUE THREAD

**Issue by bgraham1962** [dotnet/maui#5652]
### Description

I'm trying to replace the App Icon for the Android platform.

I'm using preview 14 on VS 17.2 but the project was created on preview 13.

I have converted a png to svg file and placed it in resources with the same name as the existing one, set it to a MauiIcon build action. Then rebuilt the project to generate the files which appear correctly in the obj folder but when debug the app on the android emulator I see an error saying 'cannot find mipmap/appicon_round'.

I removed the entry for appicon_round in the manifest and then I got a 'cannot find mipmap/appicon' error.

All the files seem to have been generated correctly in the project obj folder but are not found by Android

Regards
Brian

### Steps to Reproduce

1. Create new project from Maui Blazor Hybrid template. 
2. Remove MauiIcon from existing appicon.svg
3. rename to appiconold.svg
4. copy in new appicon.svg (Company logo)
5. Set build actions to MauiIcon
6. Rebuild project (check obj directory for generated files)
7. Run Android on emulator in debug mode (Nexus 10 Api 31 x86_64 2560 x 1600 Xh-DPI)
8. See error 'cannot find mipmap/appicon_round'
9. Remove entry for appicon_round in Manifest
10. Re-run and see error for mipmap/appicon (See log below)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

### Did you find any workaround?

No

### Relevant log output

```shell
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.intouch.elevate.concierge.client, PID: 19764
[AndroidRuntime] android.content.res.Resources$NotFoundException: Drawable com.intouch.elevate.concierge.client:mipmap/appicon with resource ID #0x7f0c0000
[AndroidRuntime] Caused by: android.content.res.Resources$NotFoundException: File res/mipmap-anydpi-v26/appicon.xml from drawable resource ID #0x7f0c0000
[AndroidRuntime] 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:874)
[AndroidRuntime] 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:668)
[AndroidRuntime] 	at android.content.res.Resources.loadDrawable(Resources.java:993)
[AndroidRuntime] 	at android.content.res.Resources.getDrawableForDensity(Resources.java:983)
[AndroidRuntime] 	at android.content.res.Resources.getDrawable(Resources.java:922)
[AndroidRuntime] 	at android.content.Context.getDrawable(Context.java:753)
[AndroidRuntime] 	at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:322)
[AndroidRuntime] 	at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:755)
[AndroidRuntime] 	at com.android.internal.policy.PhoneWindow.setDefaultIcon(PhoneWindow.java:1812)
[AndroidRuntime] 	at android.app.Activity.initWindowDecorActionBar(Activity.java:3506)
[AndroidRuntime] 	at android.app.Activity.getMenuInflater(Activity.java:5141)
[AndroidRuntime] 	at android.app.Activity.onCreatePanelMenu(Activity.java:4278)
[AndroidRuntime] 	at com.android.internal.policy.PhoneWindow.preparePanel(PhoneWindow.java:673)
[AndroidRuntime] 	at com.android.internal.policy.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:1066)
[AndroidRuntime] 	at com.android.internal.policy.PhoneWindow$1.run(PhoneWindow.java:310)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:938)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:201)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:288)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7839)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[AndroidRuntime] Caused by: android.content.res.Resources$NotFoundException: Drawable com.intouch.elevate.concierge.client:drawable/appicon_foreground with resource ID #0x7f070055
[AndroidRuntime] Caused by: android.content.res.Resources$NotFoundException: File res/drawable/appicon_foreground.xml from drawable resource ID #0x7f070055
[AndroidRuntime] 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:874)
[AndroidRuntime] 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:668)
[AndroidRuntime] 	at android.content.res.Resources.loadDrawable(Resources.java:993)
[AndroidRuntime] 	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1007)
[AndroidRuntime] 	at android.graphics.drawable.AdaptiveIconDrawable.updateLayerFromTypedArray(AdaptiveIconDrawable.java:530)
[AndroidRuntime] 	at android.graphics.drawable.AdaptiveIconDrawable.inflateLayers(AdaptiveIconDrawable.java:494)
[AndroidRuntime] 	at android.graphics.drawable.AdaptiveIconDrawable.inflate(AdaptiveIconDrawable.java:235)
[AndroidRuntime] 	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:145)
[AndroidRuntime] 	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1399)
[AndroidRuntime] 	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1358)
[AndroidRuntime] 	at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:906)
[AndroidRuntime] 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:860)
[AndroidRuntime] 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:668)
[AndroidRuntime] 	at android.content.res.Resources.loadDrawable(Resources.java:993)
[AndroidRuntime] 	at android.content.res.Resources.getDrawableForDensity(Resources.java:983)
[AndroidRuntime] 	at android.content.res.Resources.getDrawable(Resources.java:922)
[AndroidRuntime] 	at android.content.Context.getDrawable(Context.java:753)
[AndroidRuntime] 	at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:322)
[AndroidRuntime] 	at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:755)
[AndroidRuntime] 	at com.android.internal.policy.PhoneWindow.setDefaultIcon(PhoneWindow.java:1812)
[AndroidRuntime] 	at android.app.Activity.initWindowDecorActionBar(Activity.java:3506)
[AndroidRuntime] 	at android.app.Activity.getMenuInflater(Activity.java:5141)
[AndroidRuntime] 	at android.app.Activity.onCreatePanelMenu(Activity.java:4278)
[AndroidRuntime] 	at com.android.internal.policy.PhoneWindow.preparePanel(PhoneWindow.java:673)
[AndroidRuntime] 	at com.android.internal.policy.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:1066)
[AndroidRuntime] 	at com.android.internal.policy.PhoneWindow$1.run(PhoneWindow.java:310)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:938)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:201)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:288)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7839)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[AndroidRuntime] Caused by: org.xmlpull.v1.XmlPullParserException: no path defined
[AndroidRuntime] 	at android.graphics.drawable.VectorDrawable.inflateChildElements(VectorDrawable.java:883)
[AndroidRuntime] 	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:738)
[AndroidRuntime] 	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:145)
[AndroidRuntime] 	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1399)
[AndroidRuntime] 	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1358)
[AndroidRuntime] 	at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:906)
[AndroidRuntime] 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:860)
[AndroidRuntime] 	... 33 more
```

![appicon](https://user-images.githubusercontent.com/5826111/160723822-a1c4af57-ea23-475c-ba5f-188334f84a2b.svg)

**Comment by shimingsg** [comment]
verified not repro with vs 17.2.0 Preview 3.0 [32329.652.main], no error but the company icon didn't work
here is my demo created on 17.2.0 Preview 3.0 [32329.652.main]
[MauiApp6.zip](https://github.com/dotnet/maui/files/8378468/MauiApp6.zip)

@bgraham1962 ,  would you like to upload your project which created on preview 13?

**Comment by bgraham1962** [comment]
Hi @shimingsg,

Sorry, I should have said I was using 17.2 Preview 2.1.  When you say the company icon didnt work could you see what was wrong with it?  Wrong size? 

Thanks for your help.  IK will try and upload a project that shows the problem later.

Brian

**Comment by bgraham1962** [comment]
Hi @shimingsg,

I cannot reproduce the error on a new project with preview 2.1 now but I also cannot get an icon to work. I have tried svg and png files but all I get is an android logo.

Unfortunately, the preview 13 project where I see the error is in a suite of 22 projects which have quite complex dependencies so I cannot uopload a working stand alone version.

As I cannot reproduce the error please feel free to close this bug report.  I may start another one specifically around Icons not being used even theough they have been created in the OBJ folder.

Thanks for yor help
Brian

**Comment by jfversluis** [comment]
I can repro this! Project is here: https://github.com/jfversluis/MauiApp35

Just a File > New project, added a [random SVG](https://www.svgrepo.com/svg/112899/monkey) and did a rebuild. Find full build log here: https://gist.github.com/jfversluis/c2e3736f0494f49b2cf82334a58636fa

**Comment by manuelelucchi** [comment]
any news on this?

**Comment by tcerdaj** [comment]
This issue is 100% reproducible when the icon is removed it and re-add it and set the build action to mauiicon.
![image](https://user-images.githubusercontent.com/3307875/172413016-aff9f4dd-6278-4e1b-86cd-15e41863b609.png)

**Comment by tcerdaj** [comment]
The issue was here, for some reason the line is removed when you remove or add a new file to Image folder.
![image](https://user-images.githubusercontent.com/3307875/172426678-d47b4721-be4e-4044-8f8f-8ae56ef58788.png)

**Comment by tcerdaj** [comment]
To make it works, you have to add every single file: 
Like this:
 <MauiImage Include="Resources\Images\file1.svg" /> 
 <MauiImage Include="Resources\Images\file2.svg" /> 
 <MauiImage Include="Resources\Images\file3.svg" /> 

<MauiImage Include="Resources\Images\*" /> is not working

**Comment by mattleibow** [comment]
In the screenshot above, I see a bunch of removes on line 58+ and I think that might also be the issue. You are adding via a glob (*) but then removing right after.

**Comment by mattleibow** [comment]
@jfversluis  the reason yours fails is that as of GA, the MauiIcon does not update the manifest files in the Platforms/Android/AndroidManifest.xml.

In the manifest, there is an explicit value of `appicon` but you have only generated an app icon for `monkey`

See also: https://github.com/dotnet/maui/issues/4340#issuecomment-1153207618

Improvements are happening here: https://github.com/dotnet/maui/pull/7968
