### ISSUE TITLE
[Windows] Shell FlyoutIsPresented not working on Windows

### ISSUE THREAD

**Issue by emceelovin** [dotnet/maui#5653]
### Description

Setting Shell.FlyoutIsPresented = false isn't having any effect on  Windows. It's closing on android though.

### Steps to Reproduce

I have this Label inside my Shell footer template with a few other Labels, and I - try to - close the flyout when the command is fired, and it is. My application logs out, Shell.GoToAsync(...) goes back to the login page, viewmodels are reset, everything else goes as planned, but on Windows, the flyout stays open. Kind of a bummer. On android it closes. Is it me?

```xaml
<Label BackgroundColor="White" FontSize="16" x:Name="_logoutMenuItem" Grid.Column="0" Grid.Row="3" HorizontalTextAlignment="Start" Padding="14,10" TextColor="#11172F" Text="Logout">
    <Label.GestureRecognizers>
        <TapGestureRecognizer Command="{Binding LogoutCommand}"/>
    </Label.GestureRecognizers>
</Label>
```

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Preview 14 Windows/Android

### Did you find any workaround?

Unfortunately, no.

**Comment by v-longmin** [comment]
@emceelovin Could you share your repro project for us so that we can reproduce this issue? Thanks.

**Comment by emceelovin** [comment]
Copy. When I get the time, I will strip just the code out that's not working properly, put it into a new project, and see if it still happens. That way I can see if it was me or the framework, but I will get to this ASAP.

**Comment by emceelovin** [comment]
> @emceelovin Could you share your repro project for us so that we can reproduce this issue? Thanks.

For some reason github isn't allowing me to drag and drop the project .zip file. This is odd. Is there a filesize limit?

**Comment by emceelovin** [comment]
@v-longmin For some reason github isn't allowing me to drag and drop the project .zip file. This is odd. Is there a filesize limit?

**Comment by VincentBu** [comment]
@emceelovin make sure you have removed `.vs`, `bin`, `obj` folder.

**Comment by emceelovin** [comment]
@VincentBu Thanks. I was going to remove those, but wasn't sure what was safe to remove with the project structure.

**Comment by emceelovin** [comment]
[MAUIRepro.zip](https://github.com/dotnet/maui/files/8377624/MAUIRepro.zip)

**Comment by emceelovin** [comment]
When running that new project on the Android emulator, tapping Logout causes the flyout to close. On Windows it doesn't close.

**Comment by v-longmin** [comment]
Verified on VS 17.2.0 Preview 2.1 [32317.152.main], the issue also reproes. Repro project:
[MAUIRepro.zip](https://github.com/dotnet/maui/files/8378812/MAUIRepro.zip)
