### ISSUE TITLE
Grid Column Layout Is Incorrect

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5657]
### Description

Grid Auto column widths are sometimes calculated incorrectly. In this example an Entry used a ColumnSpan of 2 but it seems to have been treated as if it were 1 and the width of the entry used to set the width of the starting column. 

### Steps to Reproduce

1. Unzip the project from [Simple-GridColumns.zip](https://github.com/dotnet/maui/files/8376788/Simple-GridColumns.zip)
2. Compile and run it on Windows, note the missing control (see below)
3. Change the column for the missing control from 1 to 0 and it will magically appear.
4. Repeat on Android, observe the same problem

Here's how it would look if working along with a note of the missing control:
![Simple-GridColumns](https://user-images.githubusercontent.com/12423046/160746079-ff00c7f3-57bb-4b59-a6de-c82d13abe216.png)
 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows 10 

### Did you find any workaround?

No.

**Comment by XamlTest** [comment]
Verified repro with Visual Studio Enterprise 17.2 Preview 2.1 on Windows and Android. Repro with above project.
