### ISSUE TITLE
CheckBox not visible in Windows 11 OS dark theme

### ISSUE THREAD

**Issue by kla50** [dotnet/maui#5665]
### Description

The default style of the CheckBox is not visible when Windows OS theme is dark.  It's visible with light theme.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/66872908/160842804-c69a4bd8-6408-485a-98d6-06f76734dfc7.png)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 22H2 22581.100, WindowsAppSDK 1.1.0-preview1, MAUI 6.0.200-preview.14.5099, .NET SDK 6.0.300-preview.22154.4

**Comment by jfversluis** [comment]
Hey @kla50 thanks for the report. Could you (next time) please include the reproduction steps and mostly the code that you've used in text form so we can easily copy and paste instead of an image? Thanks!

**Comment by Redth** [comment]
This is fixed in the upcoming RC1 release via https://github.com/dotnet/maui/pull/5260
