### ISSUE TITLE
Generated splash screen does not retain aspect ratio

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#5676]
### Description

Splash screens on Android do not respect aspect ratio.

 - [x] Android 21: there is just a total fill of the screen because the width/height concepts are only supported in Android 23+.
 - [x] Android 33: (at least) the new splash system is designed for square images and as a result just does a fill. I did make the size shrink in #9797, however, all the logic was just made to fix the way android just clips things.
 - [ ] Should we make sure the generated image is not huge

### Workarounds

To fix Android 21, add a custom `maui_splash_image.xml` to `drawable`:

`Platforms\Android\Resources\drawable\maui_splash.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--This file was auto-generated by .NET MAUI.-->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <bitmap android:gravity="center" android:src="@drawable/name_of_your_splash_image" android:mipMap="true" />
</layer-list>
```

To fix Android 23+, add a custom `maui_splash_image.xml` to `drawable-v23`:

`Platforms\Android\Resources\drawable-v23\maui_splash.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--This file was auto-generated by .NET MAUI.-->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:width="108dp" android:height="108dp" android:gravity="center">
    <bitmap android:gravity="fill" android:src="@drawable/name_of_your_splash_image" android:mipMap="true" />
  </item>
</layer-list>
```

> Make sure to use the name of your splash screen image in the place of `name_of_your_splash_image`.  
> Replace the width/height values if your image is not square.

| Android 21 | Android 33 |
| :-: | :-: |
| <img src="https://user-images.githubusercontent.com/538025/160889524-6b8b0a8b-d144-4457-897e-8861fd2e23eb.png" width="300" /> | <img src="https://user-images.githubusercontent.com/1096616/187585610-48f0ffb0-e3d8-4979-ad80-de9ba96c4787.png" width="300" /> |

**Comment by shimingsg** [comment]
verified repro with vs 17.2.0 Preview 3.0 [32330.529.main] on android 21 emulator

**Comment by mattleibow** [comment]
This is because on pre-23 Android, the width/height properties are not respected, so the final fill takes control. We need to update the tasks/targets to actually generate a drawable and then a drawable-v23.

**Comment by mattleibow** [comment]
Related to #9794
