### ISSUE TITLE
Problem with English spelling of GREY in .NET MAUI TableView

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#5677]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problem-with-English-spelling-of-GREY-in/1698809)._

---
In .NET MAUI TableView, TextCell, TextColor, the selector offers both the English (GREY) and the American (GRAY) but GREY cause a Compile Error.

---
#### Feedback Bot on 3/22/2022, 07:16 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Hey there! I tried to reproduce this by simply doing

```xml
<TableView>
    <TableRoot>
        <TableSection>
            <EntryCell LabelColor="Grey" />
        </TableSection>
    </TableRoot>
</TableView>
```

But this runs fine, do you have some more information to reproduce this particular issue? Thanks!
