### ISSUE TITLE
System.TypeLoadException - Third Party Controls

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#5678]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemTypeLoadException---Third-Party-C/1701005)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.2 Preview 2]
I am currently experiencing an error when I use any third party controls in the latest version of Visual studio Preview 2.1 .Net MAUI.  I know that technically third party controls are not Microsoft controls, however many developers do use third party controls and I thought it would be worth mentioning.  So far I have tested, DevExpress, Telerik and Syncfusion controls, specifically the TabPage/TabView controls.  This error pops up with all 3 vendors using the latest Visual Studio 2022 Preview version, 17.2 Preview 2.1.  Please note that this error was not being thrown in the previous preview release version, 17.2 Preview 2.  If a possible workaround can be provided until there is a fix, that would be greatly appreciated. The error is as follows:

System.TypeLoadException: 'Type DevExpress.Maui.Navigation.TabPageHandler has invalid vtable method slot 39 with method none'

---
#### Feedback Bot on 3/24/2022, 02:48 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Redth** [comment]
Unfortunately you'll have to wait for those control vendors to update their libraries to work with the newer releases of .NET MAUI.  This should stabilize after the .NET MAUI RC release once libraries are upgraded to support it.  I'd encourage you to reach out to those vendors and show your interest and ask them for some more information and timelines on their support of .NET MAUI releases.
