### ISSUE TITLE
FontManager tests using method unavailable in Android API 21

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#5684]
The FontManager device tests fail on API 21 because they're using an overload of TypeFace.Create that isn't found in 21:

https://github.com/dotnet/maui/blob/f11e437e94726abb7999c7da4e5aed4b8d8541c5/src/Core/tests/DeviceTests/Services/FontManagerTests.Android.cs#L41

**Comment by v-longmin** [comment]
@hartez Could you share your repro project for us? thanks.

**Comment by hartez** [comment]
@v-longmin The repro project is the MAUI solution Device Tests project.

**Comment by jonathanpeppers** [comment]
@hartez  is this fixed now in e171d1fe74ba2afcc47072b70ba2036d180dc39a? Maybe we can close this?

The test checks against API 28 now:

https://github.com/dotnet/maui/blob/2bbd65010b6f3012dd36746a686392caf66439f1/src/Core/tests/DeviceTests/Services/FontManagerTests.Android.cs#L34-L37
