### ISSUE TITLE
File nesting with razor components and CSS files does not work in MAUI solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#5685]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/File-nesting-with-razor-components-and-C/1703575)._

---
The css files should be under a razor file if they have the same name. But this doesn't work at least in my MAUI solution

---
#### Feedback Bot on 3/28/2022, 03:17 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment]
From @jonathanpeppers:

> I wonder if it's something about the way .razor files are removed and added in this file:
>
> https://github.com/dotnet/maui/blob/f11e437e94726abb7999c7da4e5aed4b8d8541c5/src/BlazorWebView/src/Maui/build/Microsoft.AspNetCore.Components.WebView.Maui.targets#L10-L13
>
> It looks like they would lose any %(DependentUpon) item metadata in some cases, and would break the solution tree nesting?

**Comment by Eilon** [comment]
Hmm yes I think this way of removing/adding is likely incorrect one way or another, and may indeed cause the nesting problem.

It should presumably preserve metadata like we do elsewhere in the same targets file:

https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/build/Microsoft.AspNetCore.Components.WebView.Maui.targets#L63-L71

Tagging @javiercn .

**Comment by rogihee** [comment]
@eilon: it's my issue and I think it is broader and not MAUI related. Nesting also doesn't work in a Razor class library or in ASP Core site, like the appsettings:

![image](https://user-images.githubusercontent.com/4984486/161004171-68b265d0-c232-4aa4-bcab-44b225e42f31.png)

![image](https://user-images.githubusercontent.com/4984486/161004284-fdb83663-ffea-44b2-86ff-6bc926b1a6dc.png)

I just noticed it in MAUI because I was experimenting with MAUI Blazor.

**Comment by javiercn** [comment]
@rogihee I believe this is an ongoing issue in VS that is being addressed.

/cc: @vijayrkn FYI

**Comment by Eilon** [comment]
@javiercn - do you suspect that the other issue of item metadata is still problematic for any other reason? Like whatever other random metadata might be on `*.razor` files, even if it isn't causing this particular nesting issue?

**Comment by mkArtakMSFT** [comment]
Looks like this is fixed internally already and will be shipped as part of VS 17.3-preview3
