### ISSUE TITLE
Look at wiring ShellContent Pages into the life cycle of container registration

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#5686]
Currently for `ShellContent` the code will only instantiate the ContentTemplate the first time the route is navigated to. The code currently only checks to see if it was ever instantiated and then calls `GetServices ?? ActivatorCreate`. If a page is registered into the IoC container then we should look at requesting it every time the user navigates to that route.

Currently if you register a global route and then push to it it will request the page everytime.

### Issues

- What do we do if you navigate between `FlyoutItems` that have navigation stacks? Should we destroy the entire navigation stack because you've registered the root route as transient?

**Comment by JkPersson** [comment]
If this could be a way to ensure that flyout navigation always go to root (clears) the navigation stack, it would be much appreciated.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/pull/23863
