### ISSUE TITLE
[iOS] Calling VisualDiagnostics.RenderAs for Window causes Exception

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#5693]
### Description

![imgpsh_mobile_save](https://user-images.githubusercontent.com/898335/160955522-fa68ab23-2fe2-4d4a-8155-ef74a7a533ab.jpg)

### Steps to Reproduce

Call `Task<byte[]?> task = VisualDiagnostics.CaptureAsJpegAsync(this.Window);` on a given IWindow. On Android and Windows, it works, on iOS, it throws the above exception.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS.

**Comment by Redth** [comment]
Workaround found, deferred to .NET 7 via #6203
