### ISSUE TITLE
BlazorWebView MAUI targets don't copy item metadata for *.razor files

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#5713]
As part of investigating https://github.com/dotnet/maui/issues/5685, it was found that the BlazorWebView MAUI targets don't copy MSBuild item metadata when it re-maps `*.razor` files to `<RazorComponent>` items.

There are no known issues that this causes, but it's probably a good idea to copy over custom metadata so that it flows with the items. This is similar to how the .NET/Razor SDK also retains all item metadata here:

https://github.com/dotnet/sdk/blob/aac033b9324f687eda51d9d7291537bb46cf3a55/src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets#L548

And the bug in BlazorWebView MAUI targets is here:

https://github.com/dotnet/maui/blob/f11e437e94726abb7999c7da4e5aed4b8d8541c5/src/BlazorWebView/src/Maui/build/Microsoft.AspNetCore.Components.WebView.Maui.targets#L10-L13

**Comment by Eilon** [comment]
cc @javiercn FYI

**Comment by SteveSandersonMS** [comment]
Closing for now as we don't know this will lead to an issue.
