### ISSUE TITLE
[Bug][Shell][Windows] BackButton is not available/shown

### ISSUE THREAD

**Issue by DiagProf** [dotnet/maui#5714]
### Description

I have a ShellApp with 3 ContentPage’s
MainPage, AnotherPage and ChildPage1

MainPage and AnotherPage have a Button Click event to start navigation to ChildPage1

`    private async void Button_Clicked(object sender, EventArgs e)
    {
		await Shell.Current.GoToAsync(nameof(ChildPage1));
    }`

When the ChildPage1 appears. 
I always **have** a “back button” when I start the navigation from the **1st FlyoutItem**. 
 I **don’t have** “back button”  when I start the navigation from the **2st FlyoutItem**.

`<ShellContent Title="AnotherPage" ContentTemplate="{DataTemplate local:AnotherPage}" Route="AnotherPage"/>
    <ShellContent Title="Main" ContentTemplate="{DataTemplate local:MainPage}" Route="Main"/>`
`
`
![image](https://user-images.githubusercontent.com/56319388/161121961-ffc51c2a-9865-4753-8100-a9932863dd97.png)
![image](https://user-images.githubusercontent.com/56319388/161122014-0337bbc9-14d7-446a-abff-a3524db86035.png)
![image](https://user-images.githubusercontent.com/56319388/161122054-5189cef3-64ca-4359-8568-d77f7a329d0c.png)

Only on windows is the bug on android it works.

### Steps to Reproduce

example code

[MauiShell-Navigation.zip](https://github.com/dotnet/maui/files/8392075/MauiShell-Navigation.zip)

By the way, if there is no back button then there is no title of the ChildPage1 either.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

with 1st FlyoutItem it work so roughly

**Comment by kristinx0211** [comment]
repro on window using 17.2.0 Preview 2.1.

**Comment by pierre01** [comment]
I have the same issue
