### ISSUE TITLE
[Android] Label width doesn't get updated with text

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#5717]
### Description

On Android, the width of a label doesn't get updated with the text. 

For example, if a label is updated to have longer text, the text is only visible up to the previous text length.
The label width should always update according to the text length or even take up the full width of the parent.

### Steps to Reproduce

1. Create a File > New .NET MAUI app
2. Deploy the app on Android
3. Click on the "Click me" button multiple times.
4. Notice the "Current count: #" text gets cut off after a while (especially once hitting double digit count)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by mattleibow** [comment]
On Windows, changing the text triggers a new layout so the text is visible, however changing layout properties, such as Horizontal options does not affect anything until a new layout occurs.

**Comment by hartez** [comment]
> On Windows, changing the text triggers a new layout so the text is visible, however changing layout properties, such as Horizontal options does not affect anything until a new layout occurs (but this may be for all controls in the layout).

Can you open a separate bug for Windows, then?

**Comment by mattleibow** [comment]
https://github.com/dotnet/maui/issues/5734

**Comment by rachelkang** [comment]
related to ScrollView shenanigans
