### ISSUE TITLE
[Android] Alert Dialog With Onscreen Keyboard Open Causes ScrollView Area to Cut Off

### ISSUE THREAD

**Issue by mpkagel** [dotnet/maui#5721]
### Description

Opening an alert dialog with the onscreen keyboard open causes the scrollview to not occupy the entire screen after the onscreen keyboard has been minimized.
I've attached a sample project to try and demonstrate the issue.
[MauiFlyout.zip](https://github.com/dotnet/maui/files/8393075/MauiFlyout.zip)

### Steps to Reproduce

Steps to reproduce:
1. Run sample project in Android.
2. Open the flyout menu.
3. Click Browse to go to the Browse page.
4. Click the Add button.
5. Click on the Text entry to bring up the soft keyboard and focus on that entry.
6. Click the "OpenAlert" button in the nav bar at the top of the screen.
7. Click OK to dismiss the alert dialog.
8. Minimize the soft keyboard using the lower-left arrow button on the Android emulator.
9. At this state of the screen the scroll view still works but it isn't taking up the area where the soft keyboard was like it probably should be, and that's the issue that I'm trying to point out.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Snackbar messages from Maui Community Toolkit don't seem to have this problem. Snackbar messages aren't always a good substitute for alert dialogs, but I thought I'd mention it here.

**Comment by XamlTest** [comment]
Verified issue repro with Visual Studio Enterprise 2022 17.2.32317.152 on Android. Repro with above project.

![image](https://user-images.githubusercontent.com/97647558/161174003-83ad0de2-942f-4109-b193-cccc3ed96f46.png)

**Comment by PureWeen** [comment]
I tested the attached sample with the latest net7.0 and it no longer seems to reproduce. 

I'm guessing that this was fixed or if you're still seeing the issue, it should be resolved by https://github.com/dotnet/maui/issues/11274
