### ISSUE TITLE
Blazor Maui error to publish in MAC Host

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#5727]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Maui-error-to-publish-in-MAC-Host/1705392)._

---
[severity:I'm unable to use this version]
Visualt studio 2022 17.2.0 Preview 2.0
I have a maui blazor app (CalculadoraMAUI ) that works ok in windows and simulators. But when i tried to publish in a mac host (a want generate de ipa file to install in a ipad), there is a no sense error:
1>CalculadoraMAUI -> C:\Users\ajgar\Source\Repos\Calculadora3\bin\Release\net6.0-ios\ios-arm64\CalculadoraMAUI.dll
1>Se está optimizando el tamaño de los ensamblados, lo que puede cambiar el comportamiento de la aplicación. Asegúrese de probarlo después de publicar. Consulte https://aka.ms/dotnet-illink
1>La ejecución de la herramienta xcrun ha finalizado (código de salida: 1).
1>ld: warning: '/Users/antonio/Library/Caches/Xamarin/mtbs/builds/CalculadoraMAUI/5799804e2bee971ff7aa2c98a022d9cae0d88d139c078bb70c02e8aea9f4b462/obj/Release/net6.0-ios/ios-arm64/nativelibraries/main.arm64.o' was not built with class_ro_t pointer signing enabled, but previous .o files were
1>Undefined symbols for architecture arm64:
1>  "_mono_fconv_u8_2", referenced from:
1>      wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u8_double in System.Private.CoreLib.dll.o
1>  "_mono_fconv_u4_2", referenced from:
1>      wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u4_double in System.Private.CoreLib.dll.o
1>ld: symbol(s) not found for architecture arm64
1>clang: error: linker command failed with exit code 1 (use -v to see invocation)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\targets\Xamarin.Shared.Sdk.targets(1197,3): error : clang++ finalizó con el código 1.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.117\targets\Xamarin.Shared.Sdk.targets(1197,3): error :
1>Compilación del proyecto "CalculadoraMAUI.csproj" terminada -- ERROR.
========== Compilación: 0 correctos, 1 dieron error, 0 actualizados, 0 omitidos ==========

---
#### Feedback Bot on 3/30/2022, 03:13 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Please have a look at #4397 for instructions on how to build/archive and let us know there if things still aren't working. Thanks!
