### ISSUE TITLE
Default template has a double heading/title

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#5732]
### Description

<img src="https://user-images.githubusercontent.com/1096616/161176671-3e4f0677-93f7-446f-a089-3c8a3a8e1f9c.png" width="300" />

### Steps to Reproduce

1. File | New | Maui
2. Run
3. Observe a double title bar

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

One workaround (maybe the correct correct thing?) is to use a `Shell.NavigationBarIsVisible="False"` to hid the OS one.

**Comment by mattleibow** [comment]
Not sure if this is a bug, or just a bad page design because decisions were made to get to this. Maybe it really is a cool layout, I have no idea.

**Comment by jsuarezruiz** [comment]
Is the title in Shell and also a Label in the MainPage, should we remove the title or the Label?

**Comment by rachelkang** [comment]
What do you mean by double heading/title? Is the concern just that we have the "Hello World!" navbar?

**Comment by mattleibow** [comment]
Yeah. I suppose I was confused when I saw it and thought there was an issue. However, maybe it is more because it is the exact same text so my brains says that was redundant and a bug.

Maybe we just need to change the text to be more title-y?

**Comment by rachelkang** [comment]
@mattleibow Makes sense, we can definitely make that adjustment! Any thoughts on what we might make it?

Some potential options...
- .NET MAUI App
- .NET MAUI Template
- .NET MAUI Template App
- .NET MAUI Shell App
- Your First .NET MAUI App

@davidortinau thoughts?
