### ISSUE TITLE
Updating layout options at runtime does not trigger a layout

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#5734]
### Description

If you change a horizontal layout option from Center to Start, it does not actually update. It works if you restart the app.

### Steps to Reproduce

1. File | New | Maui
2. Run the app and hot reload a Horizontal layout option of a label from Center to Start
3. Observe nothing changes
4. Change padding on the container
5. Observe the layout option appy

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

**Comment by hartez** [comment]
This was fixed by 5897.
