### ISSUE TITLE
Add Marker/Annotation clustering for the Maps package that .NET MAUI will have

### ISSUE THREAD

**Issue by SachaPerson** [dotnet/maui#5735]
### Description

If we could get Marker/Annotation clustering for the Xamarin.Forms.Maps of .NET MAUI that would be awesome.

### Public API Changes

    // Nothing I know of.

### Intended Use-Case

I use Xamarin.Forms.Maps and I wanted to use marker clustering but it hasn't been implemented yet so I thought that you could do it in .NET MAUI since using maps is becoming vital to a lot of apps and it'd be great to see C# do all of the current Google Maps and iOS maps things like React and Flutter.

**Comment by jfversluis** [comment]
If you could I do like to ask you to give it a bit more thought. Are you using this today with another control? What properties would you like to see to influence the clustering behavior? How do you like annotations to work? 

We want to make sure that we're building the thing you want, please imagine that the feature is already implemented and you're working with it. What does the code that you're writing look like in the ideal case?
