### ISSUE TITLE
Grid within Border doesn't obey HorizontalOptions 

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5752]
### Description

With just Border and Label, I can get the sizing I expect using HorizontalOptions=Start.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/41873/161310001-46f45c26-8d89-47ad-86df-4c93dd82c4f3.png">

When I then do Border > Grid > Label, the Grid always expands to consume as much width as the parent allows.

![image](https://user-images.githubusercontent.com/41873/161309944-021c2ced-750e-4d0b-986f-69634c861e82.png)

```xaml
<ScrollView>
    <VerticalStackLayout Margin="15" Spacing="8">
        <Label Text="Rectangle"
                StyleClass="Headline" />
        <BoxView StyleClass="HRule"/>

            <Border Stroke="{StaticResource PrimaryBrush}"
                Background="Green"
                HorizontalOptions="Start"
                StrokeThickness="4">
                <Border.StrokeShape>
                    <Rectangle />
                </Border.StrokeShape>
                <Grid Background="Purple" 
                    HorizontalOptions="Start" 
                    VerticalOptions="Start">
                    <Label Text="Basic Rectangle" Margin="8" Background="Red" 
                        VerticalOptions="Center" 
                        HorizontalOptions="Center"/>
                </Grid>
            </Border>
```

### Steps to Reproduce

Run that on Windows

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

11

**Comment by kristinx0211** [comment]
verified repro on windows with vs 17.2.0 Preview 2.1.

**Comment by VincentBu** [comment]
repro with vs main build:
![image](https://user-images.githubusercontent.com/44959937/167549844-d8332b9d-215e-499f-8a5d-a17a1c6a9b3d.png)

**Comment by samhouts** [comment]
Still an issue on 6.0.300-rc.4.5772

**Comment by hartez** [comment]
The Border is a red herring - the problem is with Grid (and happens if you remove the Border entirely). 

Grid is still treating a `*` column (the default single column if you don't specify one) as taking up all available space, even when the Grid's alignment isn't set to `Fill`. It should be treating those columns as `Auto` in that situation. 

If you need a temporary workaround, add `ColumnDefinitions="Auto"` to your Grid.
