### ISSUE TITLE
Border doesn't update with Hot Reload

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5753]
### Description

I think I logged this via VS also. Border doesn't update when using XAML Hot Reload on Windows UNTIL I resize the window or do something else to trigger a new layout pass.

### Steps to Reproduce

with code like this do some XAML Hot Reloading on the Border and observe no updates. Then resize the window and viola.

```xaml
<ScrollView>
    <VerticalStackLayout Margin="15" Spacing="8">
        <Label Text="Rectangle"
                StyleClass="Headline" />
        <BoxView StyleClass="HRule"/>

            <Border Stroke="{StaticResource PrimaryBrush}"
                Background="Green"
                HorizontalOptions="Start"
                StrokeThickness="4">
                <Border.StrokeShape>
                    <Rectangle />
                </Border.StrokeShape>
                <Grid Background="Purple" 
                    HorizontalOptions="Start" 
                    VerticalOptions="Start">
                    <Label Text="Basic Rectangle" Margin="8" Background="Red" 
                        VerticalOptions="Center" 
                        HorizontalOptions="Center"/>
                </Grid>
            </Border>
```

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

11

**Comment by drasticactions** [comment]
You can replicate the same behavior by changing the border directly in code, and only when you resize or cause a redraw event will the change take effect. So, most likely, changing a value on the border should cause it to redraw.

**Comment by kristinx0211** [comment]
relate to the issue [#4611](https://github.com/dotnet/maui/issues/4611).

**Comment by jsuarezruiz** [comment]
I have been testing on main branch and with latest RC1 release. I can't get Hot Reload to work properly (vs main):
![image](https://user-images.githubusercontent.com/6755973/164215372-9f6d4251-b88c-4793-8437-5f04964ce00f.png)

But using buttons to update the Border does seem to work correctly without resizing the window.
![issue-5753](https://user-images.githubusercontent.com/6755973/164215295-06011261-ff17-4ec0-a12e-067fc612c245.gif)

Could you try again with latest version?

**Comment by davidortinau** [comment]
Testing on iOS and it seems to be working now. That plus your test seems to indicate it's resolved.
