### ISSUE TITLE
Is tabbedPages bugged in Windows for .NET MAUI ?

### ISSUE THREAD

**Issue by victorsigga** [dotnet/maui#5754]
### Description

Hello guys, I'm trying to build an application, that in certain moment, I have to navigate to a TabbedPage view.
I'm trying to add icons to my navigation tabs, and set the placement to bottom, but even with the commands that i found im microsoft documentation, that doesn't work, and in android, the icons arw showing whithout any command.

Here is how my code to the icons are:
![image](https://user-images.githubusercontent.com/102825073/161314939-fa089b97-8934-4ad2-bab9-ea19ac54be5d.png)
I'm trying to set this commands:
![image](https://user-images.githubusercontent.com/102825073/161314983-27fa134b-7eec-4235-831e-ea0ffa7a3175.png)
I already tried with just "Windows", but in this way it doesn't build, and give this message:
![image](https://user-images.githubusercontent.com/102825073/161315017-a8bb86a4-6766-4066-969b-6507e2781064.png)
Thanks for your attention and holpe you guys can help me.

### Steps to Reproduce

Create tabbed page and add tabs with icons

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 19044.1586

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
It should work if you add `using Microsoft.Maui.Controls.PlatformConfiguration.WindowsSpecific;` at the top of your file where it's not working. Please let us know if that's not the case. Ideally add a little bit more code (as text) so we can have a better look

**Comment by victorsigga** [comment]
A already added using, but still doesn't working @jfversluis

**Comment by jfversluis** [comment]
Please add some more relevant code or ideally a reproduction in a project on GitHub so we can take a better look

**Comment by victorsigga** [comment]
using Microsoft.Maui.Controls.PlatformConfiguration.WindowsSpecific;

public abstract class TabbedViewBase : Microsoft.Maui.Controls.TabbedPage
{
public TabbedViewBase()
        {
            NavigationPage.SetHasBackButton(this, false);
            
            On<Microsoft.Maui.Controls.PlatformConfiguration.Windows>().SetHeaderIconsEnabled(true);
            On<Microsoft.Maui.Controls.PlatformConfiguration.Windows>().SetHeaderIconsSize(new Size(24, 24));
            On<Microsoft.Maui.Controls.PlatformConfiguration.Windows>().SetToolbarPlacement(ToolbarPlacement.Bottom);

InitializeMainContainer();
        }
public void InitializeMainContainer()
        {
            NavigationPage tab1 = new NavigationPage(HomeView)
            {
                Title = "tab1",
                IconImageSource = "tab1.png"
            };

            NavigationPage tab2 = new NavigationPage(FlowsView)
            {
                Title = "tab2",
                IconImageSource = "tab2.png"
            };

            NavigationPage tab3 = new NavigationPage(NotificationView)
            {
                Title = "tab3",
                IconImageSource = "tab3.png"
            };

            NavigationPage tab4 = new NavigationPage(MoreView)
            {
                Title = "tab4",
                IconImageSource = "tab4.png"
            };

            Children.Add(tab1);
            Children.Add(tab2);
            Children.Add(tab3);
            Children.Add(tab3);
        }
}
@jfversluis  this is my code, and still doesn't work

**Comment by jfversluis** [comment]
Don't really know what to tell you, it seems to build fine here :)

**Comment by victorsigga** [comment]
@jfversluis here build fine too, my problems is that the icons aren't appearing, and the bar doesn't set in bottom

**Comment by jfversluis** [comment]
Coincidentally found out what is going on here. These platform-specifics aren't implemented yet: #5856

**Comment by jfversluis** [comment]
Yep! Keep your eye on that issue to see how the progress goes :)
