### ISSUE TITLE
Flyout labels aren't vertically centered

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5764]
### Description

<img width="401" alt="image" src="https://user-images.githubusercontent.com/41873/161334586-5e18f853-4cca-4481-8eea-214c5c4dc9a7.png">

This is the default Shell template, no styling on the flyoutitem label or layout. The label is vertical start, but should be vertical centered.

When no icons are present, we should allow the default layout to collapse horizontally so we don't have this big gap of space.

### Steps to Reproduce

Create a new MAUI project with Shell (now the default) and duplicate a few pages. Enable the Flyout menu. Run it.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30

**Comment by XamlTest** [comment]
Verified repro with Visual Studio Enterprise 17.2.0 Preview 2.1 [32317.152] on Android. Repro Project: [MauiApp27.zip](https://github.com/dotnet/maui/files/8401561/MauiApp27.zip)

**Comment by Redth** [comment]
Validated this is fixed in #6759 

![image](https://user-images.githubusercontent.com/271950/166608444-8bd758bb-c540-41bd-99ee-6c205f7c2abb.png)
