### ISSUE TITLE
Shell Flyout labels aren't visible

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5766]
### Description

This is basically a default template app showing the differences SxS Windows and Android. The Shell.BackgroundColor is not correct on Windows, but that seems covered on another issue.

The label color isn't contrasting here with the Flyout background color on Windows. It's correct on Android.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/41873/161337338-1f7a9255-4f0b-4b06-9adb-c4e30d9c2e77.png">

<img width="688" alt="image" src="https://user-images.githubusercontent.com/41873/161337368-3b9df6f2-2525-474c-b629-2866c581817f.png">

<img width="689" alt="image" src="https://user-images.githubusercontent.com/41873/161337502-ca6a5f12-faf3-4196-8620-65c49a8f6163.png">

[MauiApp27.zip](https://github.com/dotnet/maui/files/8400787/MauiApp27.zip)

### Steps to Reproduce

Run the app

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.2.0 Preview 2.1 [32317.152]. Not repro on Windows. Sample Project: [5766.zip](https://github.com/dotnet/maui/files/8401975/5766.zip)
 
![image](https://user-images.githubusercontent.com/97647558/161370787-4fa4199e-ba6a-475d-b004-8b94ad2f110e.png)
![image](https://user-images.githubusercontent.com/97647558/161370804-45fe7c89-67f5-431d-91e9-1d4363d73d36.png)

**Comment by XamlTest** [comment]
@davidortinau I cannot use your project directly, there are some errors, I created a new project with your code, and change my machine's Color(Default Windows mode and App mode to Light and Dark), VS Color Theme(Dark and Blue), but cannot repro the issue. Could you try with my project and provide more details if you still can repro?

**Comment by davidortinau** [comment]
I'm no longer repro'ing this.
