### ISSUE TITLE
Dropdown From razor Class Library does not work in Blazor MAUI Windows, but works fine in Blazor Wasm Client

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#5767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created Razor Class Library Project for DropDown List of Countries.
When in add Reference to this RCL in Blazor Wasm  it works as expected.

The same Project when referenced in Blazor MAUI, load the list fine but on click of drop down arrow does not show the list of countries. it just flickers for a moment but collapses back immidiately.

### Expected Behavior

Should display List of countries when clicked

### Steps To Reproduce

https://youtu.be/r51cC6te6ww

### Exceptions (if any)

None

### .NET Version

6.0.300-preview.22154.4

### Anything else?

using Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.2.0 Preview 2.0

**Comment by TanayParikh** [comment]
Root cause: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1693

However based on https://github.com/dotnet/maui/issues/4325#issuecomment-1049641587, this shouldn't be in 17.2 Preview 2. I wonder if you're running into a caching issue resulting in using MAUI preview 13 or earlier still.

Have you tried:

> If you are upgrading from .NET MAUI preview 10 or earlier, or have been using maui-check we recommend starting from a clean slate by [uninstalling all .NET 6](https://docs.microsoft.com/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-windows#uninstall-net) previews and [Visual Studio 2022 previews](https://docs.microsoft.com/visualstudio/install/uninstall-visual-studio?view=vs-2022).
