### ISSUE TITLE
IsVisible OnIdiom binding is not working.

### ISSUE THREAD

**Issue by JiuLing-zhang** [dotnet/maui#5769]
### Description

I used a OnIdiom binding,but the page does not display properly.
![MauiError](https://user-images.githubusercontent.com/78294929/161372461-0d796d45-6243-4c3d-8234-6664451594d5.png)

source code:
[MauiIsVisibleError.zip](https://github.com/dotnet/maui/files/8402046/MauiIsVisibleError.zip)

### Steps to Reproduce

1.Create MAUI App.
2.Add a Label control.
3.Use OnIdiom for IsVisible property.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows Server 2019 17763

**Comment by v-longmin** [comment]
Verified repro on VS 17.2.0 preview 2.1 main\32317.152. Repro project:
[MauiIsVisibleError.zip](https://github.com/dotnet/maui/files/8402071/MauiIsVisibleError.zip)

**Comment by jsuarezruiz** [comment]
Tested on main branch.

On Windows.
![image](https://user-images.githubusercontent.com/6755973/164211995-8dc9b40b-348f-40a1-9505-5b2c2af1ee51.png)

On Android.
![image](https://user-images.githubusercontent.com/6755973/164212048-8914b734-00d4-4b38-9b50-828de66208c0.png)

Seems to work as expected.

**Comment by JiuLing-zhang** [comment]
@jsuarezruiz How should I upgrade to the latest version?I updated vs but it still doesn't work.

**Comment by JiuLing-zhang** [comment]
@PureWeen It's seems to work in the current version.
