### ISSUE TITLE
Build failed on current RC1 branch with java.lan-RuntimeException: com.android.tools.r8.CompilationFailedException (xamarin.google.guava.listenablefuture) 

### ISSUE THREAD

**Issue by Mephisztoe** [dotnet/maui#5776]
### Description

I recently migrated from Preview 14 to RC1 as explained [here](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md).

So that the solution can be built at all, I made several adjustments in the project file (regarding the Windows target) and then still failed building with the following error message:

java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\****\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.5\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar : com/google/common/util/concurrent/ListenableFuture.class	SIT	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.300-rc.1.4\tools\Xamarin.Android.D8.targets	79	

Researching for this message, I found this (closed) issue: https://github.com/dotnet/maui/issues/3965

My project references both CommunityToolkit.Maui (1.0.0-pre8) as well as CommunityToolkit.Mvvm (8.0.0-preview2). Is it possible that one of these is the root cause for this build error and if so, how can I find out and what can I do to fix this?

UPDATE: I configured a base MAUI app and was able to successfully build it. The moment I reference the CommunityToolkit.Maui package, the build fails with the above error message.

### Steps to Reproduce

1. Create new .NET MAUI app using current RC1 branch
2. Add CommunityToolkit.Maui 1.0.0-pre8 package
3. Build for Android

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 14 (current)

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android

**Comment by Mephisztoe** [comment]
After further research I believe this issue is caused by the MCT not being built against RC1 (which introduced a lot of breaking changes).

**Comment by jfversluis** [comment]
You mention "installed RC1 as described here" but I can't see what "here" is.

Also RC1 isn't released publicly yet so there seems to indeed be a mismatch between .NET MAUI, the Toolkit and potentially Visual Studio here.

**Comment by Mephisztoe** [comment]
@jfversluis sorry, forgot to add the link. I was refering to the instructions on this page: https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md

**Comment by AndreasReitberger** [comment]
Same here since I updated VS 2022 Preview to the latest version yesterday (RC1 MAUI).
However, only when I add the nugets for Syncfusion.MAUI (they worked with the maui version before)
https://www.syncfusion.com/maui-controls

Reported this also to Syncfusion, because I'm not sure what the problem is causing.
Default project with just adding the nugets can be used to reproduce the issue.

[TestApp.zip](https://github.com/dotnet/maui/files/8489567/TestApp.zip)

**Comment by ziomek64** [comment]
I'm also getting this. I started blank MAUI app and installed maui compat toolkit and I already have this error.

**Comment by mterhorst** [comment]
It is reasonable to think that MAUI libraries need a recompile, because of the big Essentials namespace change. Hopefully library authers will make the switch soon...

**Comment by v-longmin** [comment]
Verified the issue on 17.3.0 Preview 1.0 [32414.199.main]. Not repro on Android 12.0 with installing CommunityToolkit.Maui 1.0.0-pre8 package.

**Comment by samhouts** [comment]
This should be resolved now that the CommunityToolkit.Maui has been updated. Please install the latest version. Thanks!

**Comment by EliseJoffreIUT** [comment]
Which nuget and wich version solves this error please ?

**Comment by jfversluis** [comment]
@EliseJoffreIUT This version should work: [1.0.0-rc2](https://www.nuget.org/packages/CommunityToolkit.Maui/1.0.0-rc2)

**Comment by jfversluis** [comment]
@ziomek64 I think that still needs to be released, yes
