### ISSUE TITLE
App crashes when installed from apk, works from debugger

### ISSUE THREAD

**Issue by ygoe** [dotnet/maui#5781]
### Description

I've created a MAUI app and tested it on my physical phone. It was installed through the debugger and I can debug it properly and also run it later on the phone without the debugger attached.

Now I need to transfer the app on another phone that isn't configured for debugging. So I created an archive (I leart that from when I tried out Xamarin) but that would only give me an aab file that Android doesn't know what to do with. In this process I also went though creating a signing certificate. After a bit of searching I created the apk file with the command

    dotnet build -c Release -f net6.0-android

and collected the apk file in the project's bin\Release directory. It's named -signed.apk but I'm not sure if it actually used my certificate because this time it didn't ask for its password. The apk can be installed just fine on the same phone. But when I open the app, after the blueish startup screen from the default app, it immediately closes again.

Same if I create the apk for debug configuration. I'm just wondering why debug is 7 MB and optimised release is 21 MB? Usually it's the opposite.

I consider this an app crash, but I see no error message. There's nothing I can do from here because there's no debugger for this. Are there log files somewhere hidden on the device?

I deleted the app that was installed through the debugger and installed it from the apk, to be sure it was a fresh installation.

### Steps to Reproduce

1. Create a default MAUI app
2. Create an archive (useless but stay with what I did)
3. Create the apk with dotnet CLI
4. Install the apk on a phone
5. Open the app after installation

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, Samsung Galaxy S10e

### Did you find any workaround?

No, it doesn't work at all.

I'll have to configure the other phone for debugging as well to pass on my app. This was a weekend hacked project, my first MAUI app ever, my first real Android app, too, and I need to install it on the target device in 2 hours. Anything after this is for future only and doesn't help me soon.

### Relevant log output

```shell
Nothing
```

**Comment by pascalm2002** [comment]
I had a similar problem but i managed to fix it with a lot of information provied via the DeviceLog. In my case, i had a IsNotNullOrEmptyConverter where ConvertBack was not implemented (throw new NotImplementedException) and that Exception was only thrown when i Released my app, but not in Debug.

Maybe try to provide your Device-Log and a sample Project so there's a chance to figure out what's happening.

**Comment by jfversluis** [comment]
As indeed mentioned it would be very helpful if you could inspect the device log or logcat as without it it's kind of impossible to say what might be going on here. Would you be able to get some more info?

**Comment by ygoe** [comment]
> There's nothing I can do from here because there's no debugger for this. Are there log files somewhere hidden on the device?

I can only repeat my question.

**Comment by Muehli-dev** [comment]
https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows

**Comment by ygoe** [comment]
OMG, this is the worst log viewer I've seen in a while. Let me see if I can find something interesting in these masses of entries. Hm, my cell signal strength has changed. The light sensor detected a change, too. Some files were not found and something is ready to run. Does CscParser have something to do with the C# compiler csc? Stuff, loads of stuff. Even a CocktailBarManagerService! Views, windows and layers.

Here's something that looks related: My app stopped with signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr. There's also an abort message: "No assemblies found in '/data/user/0/com.companyname.mauiapp1/files/...'" A backtrace with 89 lines in libart. And a tombstone was written to.

Does that help?

**Comment by Muehli-dev** [comment]
You can filter your apps current PID in the log view to just show app-related entries.
Or you could use the console to write the log to a file and provide the file here:
![grafik](https://user-images.githubusercontent.com/10485531/161623372-65166e74-049d-4370-95ed-3777ec727eff.png)
Clear the logcat cache with
adb logcat -c        
Reproduce your crash
Dump your log to a file:
adb logcat –d > filename.txt

**Comment by ygoe** [comment]
I have no PID (process ID, I assume), I'm starting the app from the app list like a user does. Installing and starting it from the debugger works just fine. It's the installed package that fails to start.

**Comment by ygoe** [comment]
Meanwhile I found out how to avoid the problem. Instead of `dotnet build` I have to call `dotnet publish`. The apk file that's created in the bin\Release\...\publish directory works now. That log hasn't helped me at all. The wording is really weird here. When publishing from the CLI it works, but publishing from the VS GUI only lets me put the thing to Azure and other web environments. Probably completely unsuitable for a mobile app. And then there's the archive command which used to create the apk file but now only makes an aab file which can't be installed. And to archive something usually means to put it away and never look at it again. Or is it a translation bug again and that command has a different name in English?

**Comment by Redth** [comment]
@dellis1972 any ideas on this one? are the defaults for dotnet build assuming something in the APK (I'd imagine fast deploy) and so the apk generated isn't really usable without deploying from the right build target?

**Comment by ygoe** [comment]
I made a Release package, not Debug.

**Comment by ygoe** [comment]
It's based on the default app. I've removed anything that isn't Android and added two references.

Only later I've added the keystore stuff. I had already created a keystore through the VS GUI archiving process and I could even create a "-Signed.apk" with the CLI command but wasn't asked for the password. Later I found instructions to add these properties and use `publish` instead of `build`. So these keystore properties should probably be removed for analysis. (I'm aware of the included secrets, but, they're not productive and not at all secret, so...)

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0-android</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>MauiApp1</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>

    <!-- Display name -->
    <ApplicationTitle>MauiApp1</ApplicationTitle>

    <!-- App Identifier -->
    <ApplicationId>com.companyname.mauiapp1</ApplicationId>

    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>

    <!-- Required for C# Hot Reload -->
    <UseInterpreter Condition="'$(Configuration)' == 'Debug'">True</UseInterpreter>

    <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net6.0-android'">21.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore>myapp.keystore</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias>key</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>password</AndroidSigningKeyPass>
    <AndroidSigningStorePass>password</AndroidSigningStorePass>
  </PropertyGroup>

  <ItemGroup>
    <!-- App Icon -->
    <MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" Color="#512BD4" />

    <!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\appiconfg.svg" Color="#512BD4" BaseSize="128,128" />

    <!-- Images -->
    <MauiImage Include="Resources\Images\*" />
    <MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\*" />

    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SML" Version="0.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UsbSerialAndroidLib\UsbSerialAndroidLib.csproj" />
  </ItemGroup>

</Project>
```

**Comment by dellis1972** [comment]
Hmm odd that looks typical for a default app. We could use a list of all the files in the final apk you are trying to use. 
Are you able to post such a list? 

I am able to run a release apk locally, so I'm not sure what is going on here.

**Comment by ygoe** [comment]
How would I get that list? Is it the contents of the bin/.../publish directory?

**Comment by dellis1972** [comment]
The apk is just a zip file. So you can rename the file to be a `.zip` and use any zip tool to view the contents.

**Comment by ygoe** [comment]
I cannot reproduce the error anymore. `dotnet build -c Release -f net6.0-android` will now create a signed, installable and runnable apk file of some 29 MB, with or without the signing properties in the csproj file. I have no idea why this works or why it didn't, and what happened the first time that has now apparently affected all future builds on the same machine.

What I noticed is that I cannot upgrade the installed app from building *with* signing properties in csproj to a build *without* the signing properties. Android says the structure is incompatible. I have to uninstall the old build first. (I uninstalled the version installed by the debugger before these tests.)

And, boy, does it take long. 6 minutes build time for a simple app on a Surface Pro 4 i5.

**Comment by dellis1972** [comment]
> What I noticed is that I cannot upgrade the installed app from building _with_ signing properties in csproj to a build _without_ the signing properties. Android says the structure is incompatible. I have to uninstall the old build first. (I uninstalled the version installed by the debugger before these tests.)

This is expected, it it how android works. In order to install over and existing app you need the same signing keys . For debug  builds we use Debug keys. Its a good way of making sure you don't accidently upload a debug app to the play store (its one of the things it checks).

**Comment by VincentBu** [comment]
just play around on Android emulator:
1. set build mode to release and deploy the app via debugger
    ![image](https://user-images.githubusercontent.com/44959937/174958178-71bdfd38-1510-4532-9da3-1ed585eca2af.png)
2. close and uninstall the app
3. go to bin/release folder, you can see a xxx-signed.apk file
    ![image](https://user-images.githubusercontent.com/44959937/174958505-030a365e-9f73-459c-aeed-a8ebce599b40.png)
4. drag that apk file to emulator and it will install 
    ![image](https://user-images.githubusercontent.com/44959937/174959147-505e2f47-07de-4a7f-a28d-61e114723f5f.png)
5. click the icon and it runs properly for me
![image](https://user-images.githubusercontent.com/44959937/174959406-c8df20cd-cac3-407a-8c8f-0756443b1656.png)
