### ISSUE TITLE
Listview Viewcell Context Actions aren't bound to the datatemplates viewmodel

### ISSUE THREAD

**Issue by JanLoehr** [dotnet/maui#5783]
### Description

When building a Listview and filling it via an Observable Collection, the ViewCells ContextActions aren't wired through to the viewmodels command. Actually I don't know where they end up. As I set it up in the repro project I'd expect the same action to be called as with the button press. But that doesn't happen. No Binding Errors are showen as well.

See:
https://github.com/JanLoehr/CommandListviewRepro

### Steps to Reproduce

1. Create a new Maui App
2. Add a listview to the mainpage
3. fill the listview via a viewmodel with an observable collection
4. add a datatemplate with a viewcell and a context action to the listview
5. bind the context actions command to the viewmodel you fill the observable collection with
6. command isn't called

Or: check the repro project linked in the description

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.685

**Comment by XamlTest** [comment]
Verified Repro with Visual Studio Enterprise 17.2.0 Preview 2.1 [32317.152] on Windows. Sample Project: [CommandListviewRepro-master.zip](https://github.com/dotnet/maui/files/8439249/CommandListviewRepro-master.zip)

**Comment by Redth** [comment]
Fixed in upcoming RC1 release:

https://user-images.githubusercontent.com/271950/162251592-60ccf5cd-f6f9-41bb-b034-5c00105f7552.mp4

**Comment by JanLoehr** [comment]
Sorry, but I cannot confirm that this is fixed. Also the video isn't showing the issue. The issue is with the context action of the viewcell. The buttons always worked and were only placed to proof the binding is working. If you rightclick the viewcell and press the button the same command is bound to that action, but it isn't triggered :(
