### ISSUE TITLE
iFrame Automatically Opens Source in New Window at Initialization (iOS Blazor WebView)

### ISSUE THREAD

**Issue by ElliottBrand** [dotnet/maui#5784]
### Description

When an iFrame loads in an iOS MAUI Blazor project, it immediately opens the source url in a new window. I'm sort of wondering if it's related to #4268 in any way.

### Steps to Reproduce

- Create a new MAUI Blazor App (Visual Studio 17.2.0 Preview 2.1)
- Change index page to the following and launch in iPhone emulator (I'm using iPhone 13 Pro iOS 15.4).

```csharp
@page "/"

<h1>Testing iFrame</h1>

@((MarkupString)_iFrameCode)

@code {
    private string _iFrameCode;

    protected override void OnInitialized()
    {
        _iFrameCode = "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/W3NTAImpNBQ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"autoplay;\" allowfullscreen></iframe>";
    }
}
```

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4 (haven't tried others)

**Comment by SteveSandersonMS** [comment]
If I'm understanding correctly, I think this is by design.

Opening a 3rd-party page within your app's webview, whether in an iframe or at the top level, is a potential security issue as it could contain malicious content (or could change to become malicious in the future).

The intention is that developers should handle the `BlazorWebView`'s `UrlLoading` event and explicitly implement a policy for which external URLs are allowed to be loaded inline. The default policy is that all external URLs will be opened externally (in the default browser) but you can choose to allow loading specific URLs internally based on any logic of your own choice.

**Comment by ElliottBrand** [comment]
If the source Url is malicious, wouldn't the user still be exposed when it opens in a new browser?

I'll look into the UrlLoading event. I'm not familiar with it, but it sounds like it might work for me, since I'll only generate iFrames for a select few domains (i.e. YouTube).

In my case, if a user entered iFrame code (or any html code) it wouldn't render, as it all gets encoded. If I detect it contains a YouTube url, I optionally generate the iFrame and display the video with their text.

**Comment by SteveSandersonMS** [comment]
> If the source Url is malicious, wouldn't the user still be exposed when it opens in a new browser?

Maybe, but at least it's not inside your application any more. If it is inside your application it might be able to trick the user to do something that's especially problematic for you and more directly implicates you in the consequences. For example, imagine if Microsoft shipped an app containing a webview, and then it displayed some content from an arbitrary 3rd party, and that content was changed to look like a login prompt that actually posted the credentials to a bad actor. The fact that it appears inside an official Microsoft-shipped app would likely be enough to convince a lot of users to actually enter their credentials. Whereas the same content in the phone's default browser, coming from a random 3rd-party domain, is likely to be a lot less convincing.

**Comment by ElliottBrand** [comment]
Very good point, @SteveSandersonMS. Would it possibly be better to display some sort of message in place of the iFrame by default (and not automatically open in a new window), such as "iFrame source url is not listed as a supported url of this application"?

**Comment by SteveSandersonMS** [comment]
Those are certainly reasonable suggestions! We might do something along those lines in the future if there's developer demand. For the first release our priority is to ensure safety by default and developer control. We have limited capacity to add other features at this point.
