### ISSUE TITLE
Why the namespace can not be found in maui Playforms but still compile success?

### ISSUE THREAD

**Issue by ft9788501** [dotnet/maui#5785]
### Description

![image](https://user-images.githubusercontent.com/29189410/161461514-2c123b6f-84a0-4c35-9a97-36b1ab607168.png)

Why the namespace can not be found in maui Playforms but still compile success?
And the IntelliSense in code is invalid.

### Steps to Reproduce

1.Create a project by default template

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

win11

**Comment by jfversluis** [comment]
I've seen this a couple of times and I think that is something that needs to be improved in Visual Studio. Notice in the top-right corner there is a dropdown that now says `VisualLogger (net6.0-android)` that means your editor now shows the code as it would be compiled on Android. Hence, it won't find the Windows specific stuff.

Switch that dropdown to Windows and it should show fine.
