### ISSUE TITLE
'System.PlatformNotSupportedException', reason: 'Operation is not supported on this platform. (System.PlatformNotSupportedException) 

### ISSUE THREAD

**Issue by anpin** [dotnet/maui#5788]
### Description

`net6.0-ios` and `net6.0-maccatalyst` throws exception when accessing `HttpClientHandler.SupportsAutomaticDecompression`
![image](https://user-images.githubusercontent.com/6060545/161519085-f6457923-27a4-40df-b25c-4dcdc77909a2.png)
![image](https://user-images.githubusercontent.com/6060545/161523156-02841ef7-3782-4d2c-b543-b514640f8cef.png)
![image](https://user-images.githubusercontent.com/6060545/161523224-43a75899-ab85-4f22-a599-c7c3695e2ad2.png)

originally found here https://github.com/getsentry/sentry-dotnet/issues/1561

### Steps to Reproduce

1. clone repro [here ](https://github.com/anpin/MauiHttphandlerRepro)
2. run on `net6.0-ios` and `net6.0-maccatalyst` 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

ios 14.2+ / catalyst 14.0+

### Did you find any workaround?

nope

### Relevant log output

```shell
'Operation is not supported on this platform. (System.PlatformNotSupportedException)
   at System.Net.Http.NSUrlSessionHandler.get_SupportsAutomaticDecompression()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpClientHandler.InvokeNativeHandlerMethod(String name, Object[] parameters)
   at System.Net.Http.HttpClientHandler.GetSupportsAutomaticDecompression()
   at System.Net.Http.HttpClientHandler.get_SupportsAutomaticDecompression()
```
```

**Comment by anpin** [comment]
@SimonCropp also opened issue here https://github.com/dotnet/runtime/issues/67529

**Comment by jfversluis** [comment]
I would think Simons issue is in the right place. If it turns out that's not the case let's reopen it here. Closing for now.
