### ISSUE TITLE
Editor WidthRequest does not work on iOS 

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5792]
### Description

The Width Request of the Editor is 150. It is being implemented on Android. But on iOS the Editor is taking full Horizontal space.

### Steps to Reproduce

Run the repro project and write on the editor. On iOS the editor will fill whole horizontal space before starting new line.
[Issueproject.zip](https://github.com/dotnet/maui/files/8409646/Issueproject.zip)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by kristinx0211** [comment]
verified repro on IOS 15.4.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 3.0. This issue does not repro on iOS 16.4 emulator with below Project:
[5792.zip](https://github.com/dotnet/maui/files/11258756/5792.zip)

WidthRequest works on iOS
![image](https://user-images.githubusercontent.com/97647558/232694073-c17b47ea-1880-4df5-a2b8-132ec9ba7657.png)
