### ISSUE TITLE
Can not File.ReadAllText a json file

### ISSUE THREAD

**Issue by MaherJendoubi** [dotnet/maui#5796]
### Description

File not found while parsing a json file in MAUI.

### Steps to Reproduce

1. I created a new project using CLI: dotnet new maui -n MauiApp1
2. I opened the sln file using Visual Studion 2022 for Mac Preview 8
3.  I created my json file in the same folder as MauiApp1.csproj file
4.  I wrote: var json = File.ReadAllText("file.json");
5. I set a breakpoint to the instruction in step 4.
6. I run the app where on iOS or Android Simulators 
7. I get an error message can not open "/file.json" file.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

iOS 14.2

**Comment by jfversluis** [comment]
You can't just add the json file in the same folder and it will be picked up. You probably want to check the [Raw Assets part in the Docs](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/single-project#raw-assets). Hope that will help you further!

**Comment by MaherJendoubi** [comment]
@jfversluis I used it as Raw asset but it remains the same error.

**Comment by MaherJendoubi** [comment]
@jfversluis Did you tried to reproduce my error?

**Comment by MaherJendoubi** [comment]
`public partial class MainPage : ContentPage
{
	int count = 0;

	public MainPage()
	{
		InitializeComponent();
		var json = LoadMauiAsset();
	}

	async Task LoadMauiAsset()
	{
        try
        {
			using var stream = await FileSystem.OpenAppPackageFileAsync("drugs.json");
			using var reader = new StreamReader(stream);

			var contents = reader.ReadToEnd();
		}
        catch (Exception ex)
        {

        }
		
	}
}`
