### ISSUE TITLE
Editor CursorPosition goes to start after adding any character to text

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5803]
### Description

I need to add a "-" in the Editor after every 8 characters. I am doing so using `TextChanged` Event. The issue on Android is that the Cursor goes back to start after each insertion of "-". 

### Steps to Reproduce

Run the app and insert any characters in the editor. 
[Issueproject.zip](https://github.com/dotnet/maui/files/8411083/Issueproject.zip)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment]
repro on Android 12.

**Comment by samhouts** [comment]
This has the same root cause as #5401, so I am closing as a duplicate. Thanks!!!!

**Comment by samhouts** [comment]
Duplicate of #5401

**Comment by HobDev** [comment]
@samhouts  the difference between the two issues is #5401 is about the user input. while this one #5803 is about programmatic  input.  Still if the cause is same than it's fine to close this one.

**Comment by samhouts** [comment]
When the Entry is in password mode on Android, we programmatically replace the characters with asterisks (*) to hide the user's input. So while it looks like the bug is with user input, it's actually the programmatic input. 😄
