### ISSUE TITLE
LinearGradientBrush crashes app on launch on iOS

### ISSUE THREAD

**Issue by Sweekriti91** [dotnet/maui#5812]
### Description

This is a Xamarin.Forms app migrated to .NET MAUI while maintaining project heads for iOS and Android. Specifically on iOS project, there is a runtime crash caused by LinearGradientBrush which is the Background of the Frame. Code snippet here : https://github.com/maddymontaquila/PlantLady/blob/maui-migrate/PlantLady/PlantLady/Views/HomePage.xaml#L7-L23

Versions :
.net version : ` 6.0.300-preview.22154.4 `
maui workload : ` 6.0.300-rc.1.5372 `
xcode : `Version 13.3`
macOS : `macOS Monteray 12.3.1`
[stacktrace.txt](https://github.com/dotnet/maui/files/8413605/stacktrace.txt)

### Steps to Reproduce

1. Clone this repo : https://github.com/maddymontaquila/PlantLady/tree/maui-migrate and use branch `maui-migrate` 
2. Build and run on mac CLI ` dotnet build PlantLady/PlantLady.iOS/PlantLady.iOS.csproj -f net6.0-ios -c Debug -t:Run` 
3. Watch iOS simulator launch and then app crash on launch

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

Comment out code L7-23 https://github.com/maddymontaquila/PlantLady/blob/maui-migrate/PlantLady/PlantLady/Views/HomePage.xaml#L7-L23

**Comment by Sweekriti91** [comment]
@PureWeen 's diagnosis : 

this code here seems to be causing an index out of range exception [PlantLady/HomePage.xaml at maui-migrate · maddymontaquila/PlantLady (github.com)](https://github.com/maddymontaquila/PlantLady/blob/maui-migrate/PlantLady/PlantLady/Views/HomePage.xaml#L7-L23) => right here

[maui/Brush.Impl.cs at f2cdd2dd28769bb709190d674bfdbd65c3035dcc · dotnet/maui (github.com)](https://github.com/dotnet/maui/blob/f2cdd2dd28769bb709190d674bfdbd65c3035dcc/src/Controls/src/Core/HandlerImpl/Brush.Impl.cs#L23)

**Comment by paulvarache** [comment]
I can confirm this happens on 6.0.200-preview.14.5099

Removing the only gradient brush from my app allowed it run run on iOS:
```xaml
<Frame.Background>
    <LinearGradientBrush StartPoint=".5,0" EndPoint="0.5,1">
        <GradientStop Color="#FFC23E"
                        Offset="0.0" />
        <GradientStop Color="#F9AA00"
                        Offset="1.0" />
    </LinearGradientBrush>
</Frame.Background>
```

I get the mentioned index out of range exception otherwise.
