### ISSUE TITLE
Voiceover focus is going to some hidden content after "Keto" in search by diet section.

### ISSUE THREAD

**Issue by Karan4495** [dotnet/maui#5815]
GitHubTags:
#.NET MAUI; #A11ySev2; #A11yMAS; #A11yTCS; #NonBenchmark; #iOS; #iPad; #WCAG2.4.3; #GH_.NETMAUI_IOS_Mar2022; #Focus Order​; #AINotInScope;

### Description

Voiceover focus is going to some hidden content after "Keto" in search by diet section.

**Note:**
This issue observed throughout application focus is going to some hidden content after last control of page.

### Steps to Reproduce

1.Install and open ".NET MAUI" app.
2.Swipe till "Search by diet section".
4.Verify Voiceover focus is going to some hidden content after "Keto" in search by diet section or Not.

https://user-images.githubusercontent.com/100186395/161683441-1750bed2-cfee-43f9-9f9a-97e1530dbd2b.mp4

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4(iPad)

### Relevant log output

```shell
Voiceover focus should not move to hidden content after "Keto" in search by diet section focus should move to next control.
```

**Comment by rachelkang** [comment]
fixed by https://github.com/dotnet/maui/pull/7512

**Comment by Karan4495** [comment]
Verified issue in ".NET MAUI" app. issue is fixed so closing the bug
IOS Version: iPad(15.5)
added attachment for references

https://user-images.githubusercontent.com/100186395/177949223-ee019239-b2f2-4e8a-8848-d6cb1321510c.mp4
