### ISSUE TITLE
Voiceover is unnecessarily announcing as a heading at "Click here to View full recipe" link and "Add to My Recipes" button.

### ISSUE THREAD

**Issue by Karan4495** [dotnet/maui#5821]
GitHubTags:
#.NET MAUI; #A11ySev2; #A11yMAS; #A11yTCS; #Benchmark; #iOS; #iPad; #WCAG1.3.1; #GH_.NETMAUI_IOS_Mar2022; #Info and Relationships​; #AINotInScope;

### Description

Voiceover is unnecessarily announcing as a heading at "Click here to View full recipe" link and "Add to My Recipes" button.

**Note:**
This issue observed throughout application for button and links.

### Steps to Reproduce

1.Install and open ".NET MAUI" app.
2.Swipe till "search box".
3.Enter Recipe name in search box and search.
4.Swipe till any recipe and double tap.
5."Recipe" Screen will open.
6.Verify Voiceover is unnecessarily announcing as a heading at "Click here to View full recipe" link and "Add to My Recipes" button or not.

https://user-images.githubusercontent.com/100186395/161698587-11df5be2-13af-4678-83a2-1e4bf87ad422.mp4

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4(iPad)

### Relevant log output

```shell
Voiceover should not unnecessarily announce as a heading at "Click here to View full recipe" link and "Add to My Recipes" button.
```

**Comment by rachelkang** [comment]
Hi, @Karan4495 - thanks for opening this issue. What is the guidance for when something can/should vs. should not be marked as a heading?

**Comment by Karan4495** [comment]
Verified issue in ".NET MAUI" app. issue is fixed so closing the bug
IOS Version: iPad(15.5)
added attachment for references

https://user-images.githubusercontent.com/100186395/177948710-0c3fa98b-9549-4531-b4a5-e5bd4b1c1af0.mp4
