### ISSUE TITLE
Button visual state not resetting to normal on Windows

### ISSUE THREAD

**Issue by Naryorill** [dotnet/maui#5824]
### Description

If you add a visual state manager to a button for pressed and normal, after pressing the button, the visual state doesn't go back to normal when releasing it. You need to click somewhere else for the button to go back to the normal state. Works perfectly fine on Android.

### Steps to Reproduce

1. Add a button with visual states for pressed and normal exactly according to the [documentation](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/button#button-visual-states)
```
<Button Text="Click me!">
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroup x:Name="CommonStates">
            <VisualState x:Name="Normal">
                <VisualState.Setters>
                    <Setter Property="Scale"
                            Value="1" />
                </VisualState.Setters>
            </VisualState>
            <VisualState x:Name="Pressed">
                <VisualState.Setters>
                    <Setter Property="Scale"
                            Value="0.8" />
                </VisualState.Setters>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>
</Button>
```
2. Press the button on Windows, it gets smaller, but doesn't go back to the original size unless you click somewhere else.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041

**Comment by kristinx0211** [comment]
repro on windows, vs 17.2.0 Preview 2.1. demo:
[MauiApp9.zip](https://github.com/dotnet/maui/files/8417112/MauiApp9.zip)

**Comment by Redth** [comment]
This is fixed in the upcoming RC1 release.
