### ISSUE TITLE
Multi-targeting frameworks in Maui does not work

### ISSUE THREAD

**Issue by adydecki** [dotnet/maui#5833]
### Description

When multiple target frameworks are specified e.g. `net6.0-android` and `net6.0-ios`, it seems it is impossible to conditionally reference assemblies for each target framework.

Different errors shows up depending on the order of the target frameworks. For instance when `net6.0-android` is listed first in the `TargetFrameworks` then following err msg shows up:
`error NU1201: Project LibNet6 is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0). Project LibNet6 supports: net6.0-ios15.2 (.NETCoreApp,Version=v6.0)`. And when `net6.0-ios` is listed before `net6.0-android` then the err msg says:
`error NU1201: Project LibNet6 is not compatible with net6.0-ios15.2 (.NETCoreApp,Version=v6.0). Project LibNet6 supports: net6.0-android31.0 (.NETCoreApp,Version=v6.0)`

### Steps to Reproduce

1. Create Android and iOS folders 
2. Under Android folder create Android class library by invoking `dotnet new androidlib -n LibNet6`
3. Under iOS folder create iOS class library by invoking `dotnet new ioslib -n LibNet6` 
4. Under root folder create MAUI class library by `dotnet new mauilib -n MauiLib`
5. Update `MauiLib\MauiLib.csproj` file to conditionally reference assemblies for `net6.0-ios` and `net6.0-android` in such a way the csproj file looks as follows

> 
    <PropertyGroup>
      <TargetFrameworks>net6.0-android;net6.0-ios</TargetFrameworks>
      <UseMaui>true</UseMaui>
      <SingleProject>true</SingleProject>
    </PropertyGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'">
      <ProjectReference Include="..\Android\LibNet6\LibNet6.csproj" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net6.0-ios'">
      <ProjectReference Include="..\iOS\LibNet6\LibNet6.csproj" />
    </ItemGroup>

6. Execute `dotnet build MauiLib\MauiLib.csproj` and observe the error.

Reproduction steps can be found at GitHub repo at [https://github.com/adydecki/net6-maui-test](https://github.com/adydecki/net6-maui-test)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS15, Android31

### Did you find any workaround?

Changing the `AssemblyName` in dependent projects to be different e.g. for LibNet6.csproj under Android changing to `<AssemblyName>LibNet6Android</AssemblyName>` solves the issue.

**Comment by adydecki** [comment]
Hello, I have created a GitHub repo for reproduction steps at [https://github.com/adydecki/net6-maui-test](https://github.com/adydecki/net6-maui-test). The issue can be observed by invoking `dotnet build MauiLib/MauiLib.csproj`.

**Comment by kristinx0211** [comment]
can be reproduced with the above project.
```
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
D:\git\net6-maui-test\MauiLib\MauiLib.csproj : error NU1201: Project LibNet6 is not compatible with net6.0-android31.0
(.NETCoreApp,Version=v6.0). Project LibNet6 supports: net6.0-ios15.4 (.NETCoreApp,Version=v6.0)
  Failed to restore D:\git\net6-maui-test\MauiLib\MauiLib.csproj (in 511 ms).
  2 of 3 projects are up-to-date for restore.

Build FAILED.

D:\git\net6-maui-test\MauiLib\MauiLib.csproj : error NU1201: Project LibNet6 is not compatible with net6.0-android31.0
(.NETCoreApp,Version=v6.0). Project LibNet6 supports: net6.0-ios15.4 (.NETCoreApp,Version=v6.0)
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.05
```

**Comment by cbaer-extron** [comment]
I have observed similar issues where the code in Platform folders for each supported platform is visible no matter what platform is being targeted.  So if I have a partial class called Class1 in each of the platform folders, VS will see all of them and cause "ambiguity" errors.

**Comment by mattleibow** [comment]
Moving this project to [25224](https://github.com/dotnet/sdk/issues/25224) as this happens with all library projects.
