### ISSUE TITLE
ControlTemplate ignored on ContentPage

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#5836]
### Discussed in https://github.com/dotnet/maui/discussions/5687

<div type='discussions-op-text'>

<sup>Originally posted by **mpanzica** March 30, 2022</sup>
Hello,
I do not seem to be able to use a resource ControlTemplate on a ContentPage.
Give the attached project a try on MAUI.
The same XAML works just fine on Xamarin.Forms.
Any help would be pretty much appreciated.
Thanks in advance
M.

[ControlTemplateTest.zip](https://github.com/dotnet/maui/files/8384481/ControlTemplateTest.zip)
</div>

**Comment by Slm0nB** [comment]
I am experiencing the same issue on RC2 - Preview6

**Comment by hartez** [comment]
I believe this is fixed by #6428. Noting this here so I can verify.

**Comment by cat0363** [comment]
Hi, @hartez 
The status of this issue is still open, but will it be closed now that the code for #6428 has been merged?
Or are there still related issues?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 5.0. Not repro on android platform with sample project.
[ControlTemplateTest.zip](https://github.com/dotnet/maui/files/12273662/ControlTemplateTest.zip)
![Screenshot 2023-08-07 160057](https://github.com/dotnet/maui/assets/77434865/001dc412-9c20-434c-a97b-9c236ed9773e)
