### ISSUE TITLE
[Enhancement][P0] XAML Hot Reload need VisualTreeHelper.GetChildren and VisualTreeHelper.GetChild

### ISSUE THREAD

**Issue by chabiss** [dotnet/maui#584]
# Summary
XAML Hot Reload needs a very reliable way to get the Live Visual Tree of a running application at any given point. WPF and UWP provides those API as part of https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.visualtreehelper.getchild?view=netcore-3.1

# API Changes
XAML Hot Reload need at the minimum

https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.visualtreehelper.getchild?view=netcore-3.1	https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.visualtreehelper.getchildrencount?view=netcore-3.1
Below is an example how those API are consumed.

```
// Enumerate all the descendants of the visual object.
static public void EnumVisual(Visual myVisual)
{
    for (int i = 0; i < VisualTreeHelper.GetChildrenCount(myVisual); i++)
    {
        // Retrieve child visual at specified index value.
        Visual childVisual = (Visual)VisualTreeHelper.GetChild(myVisual, i);

        // Do processing of the child visual object.

        // Enumerate children of the child visual object.
        EnumVisual(childVisual);
    }
}
```
# Intended Use Case
This is critical for XAML Hot Reload with incremental changes to work properly.

**Comment by PureWeen** [comment]
The main issue here is that XF doesn't have a consistent way of exposing the Children of a control

We have this concept of "LogicalChildren" but in cases like Page the LogicalChildren aren't really Logical

On ListView we are using a different structure "AllChildren" to report back to the XET team
This results in an unsustainable model for the XET team where they just have to figure it out themselves and we end up breaking stuff

Ping @PureWeen if you need additional details on this one

**Comment by akamud** [comment]
I'm working on a [library](https://github.com/akamud/Xamarin.Forms.TestingLibrary/blob/main/src/Xamarin.Forms.TestingLibrary/Extensions/ViewExtensions.cs#L24) that needs this functionality and I can confirm the pain points @PureWeen brought. Would love to have a unified model for this in MAUI.

**Comment by PureWeen** [comment]
FYI
https://github.com/dotnet/maui/issues/1445
