### ISSUE TITLE
Hooking to macOS Application Lifecycle events

### ISSUE THREAD

**Issue by BalajiSubramaniam** [dotnet/maui#5840]
### Description

There is a need in MAUI application to do clean-up on application close event and hook to other lifecycle events, we found Microsoft.Maui.LifecycleEvents does support these events : https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle, but we do not have anything specific for macOS, **we tried using iOS  events in macOS it crashes the application**
Lifecycle events for windows which works well:
#if WINDOWS
events.AddWindows(windows => windows
.OnActivated((window, args) => LogEvent("OnActivated"))
.OnClosed((window, args) => LogEvent("OnClosed"))
.OnLaunched((window, args) => LogEvent("OnLaunched"))
.OnLaunching((window, args) => LogEvent("OnLaunching"))
.OnVisibilityChanged((window, args) => LogEvent("OnVisibilityChanged"))
.OnNativeMessage((window, args) =>
{
if (args.MessageId == Convert.ToUInt32("0x02E0"))
{
// DPI has changed
}
}));
#endif

Tried using iOS events in macOS it crashes the application:
events.AddiOS(ios => ios
.OnActivated((app) => LogEvent("OnActivated"))
.OnResignActivation((app) => LogEvent("OnResignActivation"))
.DidEnterBackground((app) => LogEvent("DidEnterBackground"))
.WillTerminate((app) => LogEvent("WillTerminate")));

### Steps to Reproduce

1. Hook Lifecycle events for macOS code
events.AddiOS(ios => ios
.OnActivated((app) => LogEvent("OnActivated"))
.OnResignActivation((app) => LogEvent("OnResignActivation"))
.DidEnterBackground((app) => LogEvent("DidEnterBackground"))
.WillTerminate((app) => LogEvent("WillTerminate")));
2. It crashes the application 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS-Monterey

### Did you find any workaround?

No

### Relevant log output

```shell
N/A
```

**Comment by Redth** [comment]
I'm unable to reproduce this on the upcoming RC1 build.  Please open a new issue once you're able to test this on RC1 when it's released if you are still having an issue with it.
