### ISSUE TITLE
Repeatedly going to "/" in MAUI app on Android shows an info/error in the logs

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#5850]
1. Create new MAUI Blazor app in VS Windows
2. Launch in Android emulator
3. Keep clicking the title of the app (e.g. `MauiApp123`) (or go to the hamburger menu and click Home)

In the VS Debug Output window you'll see tons of these messages:

```
[chromium] [INFO:CONSOLE(1)] "Uncaught SyntaxError: Identifier 'channel' has already been declared", source: https://0.0.0.0/ (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) Error: Blazor has already started.", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught SyntaxError: Identifier 'channel' has already been declared", source: https://0.0.0.0/ (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) Error: Blazor has already started.", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught SyntaxError: Identifier 'channel' has already been declared", source: https://0.0.0.0/ (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) Error: Blazor has already started.", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught SyntaxError: Identifier 'channel' has already been declared", source: https://0.0.0.0/ (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) Error: Blazor has already started.", source: https://0.0.0.0/_framework/blazor.webview.js (1)
```

So it looks like it's trying to start Blazor every time you navigate to `/` even though we never "left" Blazor. It's important that we re-start Blazor if the BlazorWebView wasn't already running it (e.g. you navigated away, despite our warnings to tell you not to). But perhaps we need to guard against trying to restart it if it's already running.

Note: This does seem harmless, but it also seems wrong. I don't want to pollute the output windows with things that _look_ bad, even if perhaps they are innocuous.

**Comment by jfversluis** [comment]
+1 I have seen this as well. Doesn't matter if you do `href=""` or `href="/"` or you use a `<a>` or `<NavLink>` or a combination of these. It seems as long as you navigate to the root this will come up.

**Comment by javiercn** [comment]
This seems like a bug in the navigation interception, as I would expect `/` to be handled as a client navigation.
