### ISSUE TITLE
MAUI Blazor installer hangs

### ISSUE THREAD

**Issue by rborosak** [dotnet/maui#5857]
### Description

I have written an Blazor MAUI app and have created a MSIX package to distribute to the Windows users using 

`msbuild {myproject}.csproj /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:Platform=x64 /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="{thumb}" /p:PackageCertificatePassword="{pass}"`

I am able to distribute that MSIX package and some users can run the package and install the application (the installer downloads .net framework and Microsoft.WindowsAppSDK if needed). Some are admins on their PC, some are not.

But then there are some users that are unable to install the app. (All of them are not admins).
The installer runs fine and get to about 16% and then it just stops (the installer is responsive and I can cancel the installation).
I don't get any notification or dialog to grant administrator privileges. The installer just sits there at 16%. I have tried manually installing VC redistributable, .NET Runtime, WindowsAppSDK but nothing helped. 

Then I altered the Install.PS1 script that the Visual Studio generates when creating MSIX package in a way that the it does not install a developer license. After running the script the app was successfully installed and it works without any problems.

Is there some kind of a bug in MSIX installer? 
The app installs on 100% of Android devices without any problems.

### Steps to Reproduce

I have written everything in a description

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041

### Did you find any workaround?

Yes. Install the app using powershell script generated by the Visual Studio

**Comment by XamlTest** [comment]
@rborosak Could you share your project and the required script?

**Comment by rborosak** [comment]
You can find the sample project [here](https://github.com/rborosak/MAUI_Blazor_Sample)
The script is the same as generated by the Visual Studio except `CheckIfNeedDeveloperLicense` function alwasys returns false.

I have tried to install in about 20 PC before deploying to cutomer and it worked on all of then. 
If a PC had sideloading disabled, the installer would start and then just close (which was strange) but on the customers machines the installer just sits at 16% and does nothing.

**Comment by TanayParikh** [comment]
@rborosak to help us better diagnose this issue, could you please confirm if you're experiencing the same issue with the base `dotnet new maui` app as well? Or is this an issue specific to MAUI Blazor?

**Comment by rborosak** [comment]
@TanayParikh sorry, I cannot confirm because my client is not willing to try and install the base app and I don't have a PC where I could reproduce the issue

**Comment by samhouts** [comment]
I believe this was due to a dependency on Visual C++ Redistributable libraries. This dependency should no longer exist as of GA. Thank you!
