### ISSUE TITLE
Creating android archive from VS 2022 17.2.0 preview 2.1 gives Error "Cannot create an android archive 'xxx' because the project does not have a package name".

### ISSUE THREAD

**Issue by ElementalLogic** [dotnet/maui#5862]
### Description

I'm building a .net Maui blazor app - this is reproducable with the default Blazor Maui project.

If you go to "Archive" in visual studio it fails with 

"Cannot create an android archive 'xxx' because the project does not have a package name".

This worked on the previous preview (it pulled the package name from the ApplicationId in the csproj)

### Steps to Reproduce

Create new Blazor Maui Project
Set build to release
Right click on project and select "Archive"

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

Android

### Affected platform versions

Android, all versions

### Did you find any workaround?

No workaround I can find.

**Comment by ElementalLogic** [comment]
It seems like the project was silently failing to build. If I removed all references in the project to Windows workload and removed the reference to nuget package for WindowsSDK then it all works. I'm guessing the build was silently failing somewhere.

**Comment by kristinx0211** [comment]
not repro on Android 12 with vs 17.2.0 Preview 2.1. 
![image](https://user-images.githubusercontent.com/99457000/162092551-cea4b67c-71fc-40e0-a7dd-8f9cc56f7282.png)

**Comment by ElementalLogic** [comment]
It seems like a reboot (and removing references to the windows platform from the project file) have resolved the issue, it's working today :-)
