### ISSUE TITLE
OnAppearing firing twice when using Shell.Current.GoToAsync()

### ISSUE THREAD

**Issue by ioiooi** [dotnet/maui#5877]
### Description

Hi,

OnAppearing fires twice when trying to navigate to a different Page using `Shell.Current.GoToAsync()`.
Furthermore when navigating to the Page once again OnAppearing does not fire at all.
So during the App Lifetime it only (wrongly) fires twice and then never again.

https://github.com/ioiooi/MAUIOnAppearingTwice

In the linked repository you will find a App with three Pages. Page1, Page2 and Page3. Page2 should never be seen because it navigates to Page3 in its OnAppearing. But after the first "run-through" it will be displayed because OnAppearing won't fire anymore.

### Steps to Reproduce

1. Clone repo https://github.com/ioiooi/MAUIOnAppearingTwice
2. Run on physical Android Device or Emulator with Android Version 11
3. Use the Button on Page1 and navigate to Page2
4. Page2 OnAppearing fires twice and navigates to Page3
5. Use the Button on Page3 to navigate to Page2
6. Page2 OnAppearing does not fire at all and now you're stuck :( 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

I have no Idea why but replacing
`await Shell.Current.GoToAsync($"//{nameof(Page3)}");`
with
`Task.Run(async () => await Shell.Current.GoToAsync($"//{nameof(Page3)}"));`
fixes the issue.

After replacing the line the `async` keyword can be removed from OnAppearing().

**Comment by kristinx0211** [comment]
verified repro on Android 11 with vs 17.3.0 Preview 1.0 [32406.489.main].
