### ISSUE TITLE
Generate the manifest/plist entries for reseizetizer

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#5883]
### Description

This is done for Windows, but not for iOS/Android yet.

### Public API Changes

None.

### Intended Use-Case

Generation.

**Comment by Redth** [comment]
This should be specifically for the generated icons/assets which I think is really just the splash screen and app icon at this point, correct?

**Comment by Redth** [comment]
#5882 is related to this for reference.

**Comment by mattleibow** [comment]
Duplicate of #7971
