### ISSUE TITLE
Unable to build Windows class libraries with dotnet build

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#5886]
### Description

We added support for dotnet build, but it seems that libraries still have some issues.

Partial PR: https://github.com/dotnet/maui/pull/5875
Maui devops issue: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1520610
OS devops issue: https://microsoft.visualstudio.com/OS/_workitems/edit/38897015

### Steps to Reproduce

1. Create a new winui class library
2. dotnet build
3. Observe the error saying it can't load the Pri tasks

```
D:\a\_work\_temp\templatesTest\packages\microsoft.windowsappsdk\1.0.2\buildTransitive\MrtCore.PriGen.targets(891,5):
    error MSB4062: The "Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent" task could not be loaded from the 
    assembly D:\a\_work\1\s\bin\dotnet\sdk\6.0.300-preview.22204.3\\Microsoft\VisualStudio\v17.0\AppxPackage\\Microsoft.Build.Packaging.Pri.Tasks.dll. 
    Could not load file or assembly 'D:\a\_work\1\s\bin\dotnet\sdk\6.0.300-preview.22204.3\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.Build.Packaging.Pri.Tasks.dll'. 
    The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are
    available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
    [D:\a\_work\_temp\templatesTestmauilibTrue\templatesTestmauilibTrue.csproj]
 ```

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

### Did you find any workaround?

Use msbuild :(

**Comment by mattleibow** [comment]
My PR fixes the issue as seen by human eyes, but there are some hidden issues in some areas. Reopening this and will PR more fixes from the WinUI team.

**Comment by Juriyx** [comment]
Same stuff on GitHub Actions
`C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.0.3\buildTransitive\MrtCore.PriGen.targets(891,5): error MSB[40](https://github.com/xperiandri/Elmish.Uno/runs/6379204478?check_suite_focus=true#step:4:40)62: The "Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent" task could not be loaded from the assembly C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\6.0.300\\Microsoft\VisualStudio\v17.0\AppxPackage\\Microsoft.Build.Packaging.Pri.Tasks.dll. Could not load file or assembly 'C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\6.0.300\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.Build.Packaging.Pri.Tasks.dll'. The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\a\Elmish.Uno\Elmish.Uno\src\Elmish.Uno\Elmish.Uno.fsproj]
  Elmish.Uno.Tests -> D:\a\Elmish.Uno\Elmish.Uno\src\Elmish.Uno.Tests\bin\Release\net6.0\Elmish.Uno.Tests.dll`

`Build FAILED.`

`C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.0.3\buildTransitive\MrtCore.PriGen.targets(891,5): error MSB4062: The "Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent" task could not be loaded from the assembly C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\6.0.300\\Microsoft\VisualStudio\v17.0\AppxPackage\\Microsoft.Build.Packaging.Pri.Tasks.dll. Could not load file or assembly 'C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\6.0.300\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.Build.Packaging.Pri.Tasks.dll'. The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\a\Elmish.Uno\Elmish.Uno\src\Elmish.Uno\Elmish.Uno.fsproj]`
`    0 Warning(s)`
`    1 Error(s)`

**Comment by Juriyx** [comment]
Any work arounds?

**Comment by mattleibow** [comment]
You need to set the following properties (we set them in maui):

Library:

```xml
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
    <GenerateLibraryLayout>true</GenerateLibraryLayout>
```

Apps:

```xml
    <WinUISDKReferences>false</WinUISDKReferences>
```

**Comment by codymullins** [comment]
@mattleibow to confirm, when this is fixed in the future we can remove these properties?

**Comment by mattleibow** [comment]
Depends. The official fix right now with a non-Maui library is to set it. I cannot speak to whether the WinUI team actually wants these since EnablePreviewMsixTooling is a feature that you are enabling and it has different behaviour. 

However, I would expect that some of these should at least be set to valid values after setting EnablePreviewMsixTooling=True since you are basically opting into new things, so why keep the legacy, VS-only features?

But, if you open an issue on the WindowsAppSDK repo I am sure they can provide more details as to the reasons h=behind the current defaults and the plans for any changes.
