### ISSUE TITLE
MAUI Border doesn't expand

### ISSUE THREAD

**Issue by DamienDoumer** [dotnet/maui#5895]
### Description

The Border control in MAUI doesn't expand properly. It keeps its initial width even when the page in which it is found stretches. 

### Steps to Reproduce

Inside a page, paste the following code.
Run the app and display the page
the border in the page will display normally, but as soon as you rotate the screen to landscape, 
The views in the border stretch, and overflow in the border which remains at the same size. 
See the screenshots. 

![Screenshot1](https://user-images.githubusercontent.com/16731017/162325252-387e49c1-7248-4723-92d4-8b8afcea7411.jpg)
![Screenshot2](https://user-images.githubusercontent.com/16731017/162325254-64e6587b-93eb-49f7-9c10-b2e69916dc5e.jpg)

### Reproduction

I reproduced [this bug in this page](https://github.com/DamienDoumer/MAUIBugs/blob/master/MAUIBugs/Pages/BorderBugPage.xaml) inside a sample application.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

**Comment by v-longmin** [comment]
@DamienDoumer Could you share your repro project? Thanks.

**Comment by DamienDoumer** [comment]
Hi @v-longmin I updated the issue with a link to a project in which I reproduced this bug.

**Comment by v-longmin** [comment]
@DamienDoumer Error occurred when I running the project on Android(OS: Android 12.0-API31) as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/162656469-81597bfb-ea48-4aaa-9c63-28dbb7290244.png)

**Comment by DamienDoumer** [comment]
@v-longmin I reproduced the bug in a different page. 
`MainPage = new BorderBugPage();`
Please could you pull and re-run?

**Comment by kristinx0211** [comment]
verified repro on Android 11. repro project:
[MAUIBugs.zip](https://github.com/dotnet/maui/files/8472146/MAUIBugs.zip)

**Comment by samhouts** [comment]
No longer reproduces on MAUI main (6.0.400-preview.1.5782)
