### ISSUE TITLE
Deploy to IOS from 17.2 preview 2.1 results in /usr.bin.codesign exited with code 1

### ISSUE THREAD

**Issue by ElementalLogic** [dotnet/maui#5901]
### Description

When using the default Maui Blazor project, and building either to IOS simulator, or release build results in error:

/usr/bin/codesign exited with code 1

I've seen other bug tickets with this error but they are marked as closed, and it states that it was resolved with Microsoft.IOS 15.2.302-preview.14.122, but that's the version I'm using.  I've commented on the other tickets but as they are closed, they will go unnoticed.

For reference I'm using Bigsur on the Mac with Xcode 13.2.1 (I can't upgrade without buying a new Macbook!) which I believe may be part of the issue.

Weirdly I don't think it should be codesigning when going to the emulator - but it's the same result with a release build as a debug simulator build.

In debug/simulator build the logs all ok, up to codesigning part:

`  
1>        The stamp file 'obj/Debug/net6.0-ios/iossimulator-x64/codesign//Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-debugger.dylib' does not exist, so the item '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-debugger.dylib' needs to be codesigned.
1>        The stamp file 'obj/Debug/net6.0-ios/iossimulator-x64/codesign//Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libxamarin-dotnet-debug.dylib' does not exist, so the item '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libxamarin-dotnet-debug.dylib' needs to be codesigned.
1>        The stamp file 'obj/Debug/net6.0-ios/iossimulator-x64/codesign//Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.Native.dylib' does not exist, so the item '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.Native.dylib' needs to be codesigned.
1>        The stamp file 'obj/Debug/net6.0-ios/iossimulator-x64/codesign//Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmonosgen-2.0.dylib' does not exist, so the item '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmonosgen-2.0.dylib' needs to be codesigned.
1>        Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign - /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-hot_reload.dylib
1>        Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign - /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.Security.Cryptography.Native.Apple.dylib
1>        Tool /usr/bin/codesign execution finished (exit code = 1).
1>        /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-hot_reload.dylib: cannot find code object on disk
1>        Tool /usr/bin/codesign execution finished (exit code = 1).
1>        /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.Security.Cryptography.Native.Apple.dylib: replacing existing signature
1>        /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.Security.Cryptography.Native.Apple.dylib: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /usr/bin/codesign exited with code 1
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /usr/bin/codesign exited with code 1
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : Failed to codesign '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-hot_reload.dylib': /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-hot_reload.dylib: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : 
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : Failed to codesign '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.Security.Cryptography.Native.Apple.dylib': /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.Security.Cryptography.Native.Apple.dylib: replacing existing signature
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.Security.Cryptography.Native.Apple.dylib: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : 
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign - /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-debugger.dylib
1>        Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign - /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-diagnostics_tracing.dylib
1>        Tool /usr/bin/codesign execution finished (exit code = 1).
1>        Tool /usr/bin/codesign execution finished (exit code = 1).
1>        /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-diagnostics_tracing.dylib: cannot find code object on disk
1>        /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-debugger.dylib: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /usr/bin/codesign exited with code 1
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /usr/bin/codesign exited with code 1
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : Failed to codesign '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-debugger.dylib': /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-debugger.dylib: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : 
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign - /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libxamarin-dotnet-debug.dylib
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : Failed to codesign '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-diagnostics_tracing.dylib': /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libmono-component-diagnostics_tracing.dylib: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : 
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign - /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.IO.Compression.Native.dylib
1>        Tool /usr/bin/codesign execution finished (exit code = 1).
1>        Tool /usr/bin/codesign execution finished (exit code = 1).
1>        /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libxamarin-dotnet-debug.dylib: cannot find code object on disk
1>        /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.IO.Compression.Native.dylib: replacing existing signature
1>        /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Debug/net6.0-ios/iossimulator-x64/MauiApp4.app/libSystem.IO.Compression.Native.dylib: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /usr/bin/codesign exited with code 1
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /usr/bin/codesign exited with code 1
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-`

In Release, the error is slightly different:

`  Target "_CodesignAppBundle" in file "C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets":
1>      Using "Codesign" task from assembly "C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\..\iOS\Xamarin.iOS.Tasks.dll".
1>      Task "Codesign"
1>        Task Parameter:SessionId=0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de
1>        Task Parameter:
1>            Resources=
1>                bin\Release\net6.0-ios\ios-arm64\MauiApp4.app
1>                        CodesignAdditionalFilesToTouch=bin\Release\net6.0-ios\ios-arm64\MauiApp4.app.dSYM\Contents\Info.plist
1>                        CodesignAllocate=\Applications\Xcode.app\Contents\Developer\Toolchains\XcodeDefault.xctoolchain\usr\bin\codesign_allocate
1>                        CodesignDeep=false
1>                        CodesignDisableTimestamp=False
1>                        CodesignEntitlements=obj\Release\net6.0-ios\ios-arm64\Entitlements.xcent
1>                        CodesignExtraArgs=
1>                        CodesignKeychain=
1>                        CodesignRelativeAppBundlePath=Release\net6.0-ios\ios-arm64\MauiApp4.app
1>                        CodesignResourceRules=
1>                        CodesignSigningKey=B929A108AF682F32F11CE92B284A74FD86743382
1>                        CodesignStampFile=bin\Release\net6.0-ios\ios-arm64\MauiApp4.app\_CodeSignature\CodeResources
1>                        CodesignStampPath=obj\Release\net6.0-ios\ios-arm64\codesign\
1>                        CodesignUseHardenedRuntime=
1>                        CodesignUseSecureTimestamp=
1>                        IsInputDirectory=true
1>        Codesign: 2022-04-08T10:02:27.6635802+01:00 - Started
1>        Codesign: 2022-04-08T10:02:27.6645793+01:00 - Initializing
1>        [xma]: Trying to get a Build Connection for Session '0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de': Xamarin.Messaging.Build.Client.BuildConnection.0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de, Lifetime: AppDomain
1>        Codesign: 2022-04-08T10:02:27.6645793+01:00 - Initialized
1>        Codesign: 2022-04-08T10:02:27.6655793+01:00 - There's no available inputs to copy to the Mac
1>        Codesign: 2022-04-08T10:02:27.6655793+01:00 - Serializing intputs
1>        Codesign: 2022-04-08T10:02:27.6765785+01:00 - Executing
1>        [xma]: Starting remote task execution for 'MauiApp4': Xamarin.MacDev.Tasks.Codesign
1>        [xma]: Sending Request Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic xvs/build/execute-task/MauiApp4/0f1e4cd002fCodesign
1>        [xma]: Received Response of Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic build0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de40900jamie/+/xvs/build/execute-task/MauiApp4/0f1e4cd002fCodesign
1>        Codesign: 2022-04-08T10:02:28.5097327+01:00 - Logging messages
1>        The stamp file 'bin/Release/net6.0-ios/ios-arm64/MauiApp4.app/_CodeSignature/CodeResources' does not exist, so the item '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Release/net6.0-ios/ios-arm64/MauiApp4.app' needs to be codesigned.
1>        Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign B929A108AF682F32F11CE92B284A74FD86743382 --entitlements /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/obj/Release/net6.0-ios/ios-arm64/Entitlements.xcent /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Release/net6.0-ios/ios-arm64/MauiApp4.app
1>        Tool /usr/bin/codesign execution finished (exit code = 1).
1>        /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Release/net6.0-ios/ios-arm64/MauiApp4.app: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-review.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : /usr/bin/codesign exited with code 1
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : Failed to codesign '/Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Release/net6.0-ios/ios-arm64/MauiApp4.app': /Users/jamiemoore/Library/Caches/Xamarin/mtbs/builds/MauiApp4/0f1e4cdf14fa622132609c9ce8057ee583cdfb360497bc97f4c41ba596d325de/bin/Release/net6.0-ios/ios-arm64/MauiApp4.app: cannot find code object on disk
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error : 
1>        C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.2.302-preview.14.122\tools\msbuild\iOS\Xamarin.Shared.targets(2095,3): error :
1>        Codesign: 2022-04-08T10:02:28.5097327+01:00 - Finished
1>      Done executing task "Codesign" -- FAILED.
1>    Done building target "_CodesignAppBundle" in project "MauiApp4.csproj" -- FAILED.`

### Steps to Reproduce

Create default .net Maui Blazor Project
Deploy to IOS

OR 

Add provisioning information 
Build project

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Xcode 13.2.1 Microsoft.IOS 15.2.302.122

### Did you find any workaround?

No, workaround, tried everything I can think of.

**Comment by ElementalLogic** [comment]
[buildlog.txt](https://github.com/dotnet/maui/files/8450473/buildlog.txt)

**Comment by Redth** [comment]
@rolfbjarne  ?

**Comment by rolfbjarne** [comment]
Does this happen with every project, or just one project in particular? In other words: do you get the same failures if you create a new project from a template and build for device?

**Comment by ElementalLogic** [comment]
Indeed it did... Even the blank template project.

However, I've upgraded my MacBook (using opencore to trick it into upgrading), and now have xcode 13.3 installed. I'm no longer getting that error, but different errors altogether.

J

⁣Get BlueMail for Android ​

**Comment by v-longmin** [comment]
Verified not repro on iOS 15.4 with VS 17.3.0 Preview 1.0 [32414.199.main]. Not repro with Maui Blazor Project.

**Comment by rolfbjarne** [comment]
@ElementalLogic ok, I'll close this then since it seems this problem isn't occurring for you anymore. But please file a new issue about the other errors if you need our help, and we'll look at it.
