### ISSUE TITLE
BlazorWebView API review: Open questions

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#5904]
We did an API review. Here are the things we didn't yet reach a decision about:

- `BlazorWebView.cs`
  - [ ] `public virtual IFileProvider CreateFileProvider(string contentRootDir)`
     - Need to confirm if we really want this to be a virtual method, or whether we'd take a different approach (e.g., an event, or a settable `IFileProvider` property so that developers don't have to subclass just to customize this)
     - A publicly settable property (e.g., `public IFileProvider FileProvider { get; set; }`), having a default value representing the default behavior for the current platform, seems to represent the scenario accurately as well as avoiding the weirdness that external code can call `CreateFileProvider` as many times as it likes and you don't know whether you're getting the same instance each time or what other semantics this might have.
       - Depends whether we're concerned that some unrelated code might get a reference to a `BlazorWebView` instance and then mess with it by assigning a `FileProvider`. Unclear to me that there should be a concern about this.
- `BlazorWebView\src\Directory.Build.props`
  - [ ] Can we remove the `<NoWarn>$(NoWarn);RS0041</NoWarn>`? We should be able to if we finish doing nullability annotations for WPF and WinForms.

That's actually all.

**Comment by SteveSandersonMS** [comment]
@Eilon I think you had the strongest preferences in this area, as well as probably being the person who added the existing API. Would you be able to make a recommendation and point out any pros/cons?

**Comment by TanayParikh** [comment]
Adding this to the RC3 milestone so it's reflected on our boards, feel free to change if that's not appropriate.

**Comment by fairking** [comment]
Can I use `BlazorWebView` to host vuejs applixation in Xamarin/Mui (Android/IOS) and have an ability to communicate with host?
The communication mostly is to the local database. Lets say in my vuejs app I have the following js service:
``` js
var customers = CustomerService.GetCustomers({ page: 1 });
```

where the method `GetCustomers` communicate to host, gets data from the sqlite database and returns those data back to the `BlazorWebView` to my vuejs app?

Thanks for any help.

**Comment by SteveSandersonMS** [comment]
@fairking That seems unrelated to this issue (which is about API design). The short answer is you don't need BlazorWebView - you can use a basic MAUI WebView for that. If you have any follow-up questions could you file something separately rather than posting on this one? Thanks!

**Comment by Eilon** [comment]
@fairking said:

> Can I use `BlazorWebView` to host vuejs application in Xamarin/Maui (Android/IOS) and have an ability to communicate with host?

We have a suggestion to track generic WebView App hosting support here: https://github.com/dotnet/maui/issues/1148

**Comment by SteveSandersonMS** [comment]
Outcome from discussion:

 * We'll keep `CreateFileProvider` as-is because, although it probably *could* be replaced by something less abusable, we don't think many developers are even going to see it there and nothing hugely bad happens if they do. Also it's late to change the rules about who decides what the content root is.
 * Regarding `IBlazorWebView`, @Eilon is going to consult and verify if we're following the MAUI pattern correctly here, and we're going to favour following the ordained pattern above our own opinions about whether this interface should necessarily be required. 
   * Assuming the interface is what MAUI wants, then @Eilon is going to try to ensure it's actually respected throughout our code, and we're not downcasting `IBlazorWebView` to `BlazorWebView` anywhere.
