### ISSUE TITLE
BlazorWebView API review: Shared sources

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#5905]
We did an API review. Here are the things we want to change in the shared sources:

- `BlazorWebViewHandler.cs`
  - [ ] `public static readonly PropertyMapper<IBlazorWebView, BlazorWebViewHandler> BlazorWebViewMapper;` - make *not* readonly to follow MAUI conventions
  - [ ] `public virtual IFileProvider CreateFileProvider(string contentRootDir);` - follow whatever decision we make about `BlazorWebView.cs`'s version of this (https://github.com/dotnet/maui/issues/5904).
- `IBlazorWebView.cs`
  - [ ] ~Confirm how mandatory it is to have this interface instead of deleting it and declaring the handler in terms of the concrete `BlazorWebView` type. Remove the interface if it's not really needed in our case.~
  - [ ] ~If we do need to keep it, remove as many members from it as we can.~
- `RootComponent.cs`
  - [ ] Change `Parameters` to be `IReadOnlyDictionary<string, object?>?` as long as this doesn't break setting parameters from XAML
- `RootComponentsCollection.cs`
  - [ ] Since the collection is typed as observable, check we do in fact react if the collection is modified. If not we should make it not observable.
- `BlazorWebViewServiceCollectionExtensions.cs`
  - [ ] Change `AddBlazorWebViewDeveloperTools` and `AddMauiBlazorWebView` to return some new `IMauiBlazorWebViewBuilder` type. This new interface doesn't have to contain or do anything yet - it's for future extensibility.

**Comment by Eilon** [comment]
Regarding IBlazorWebView, I opened PR https://github.com/dotnet/maui/pull/5984 that makes sure we follow MAUI guidelines for interfaces/controls.
