### ISSUE TITLE
BlazorWebView API review: Android

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#5907]
We did an API review. Here are the things we want to change in the Android-specific sources:

- `AndroidWebKitWebViewManager.cs`, `BlazorWebViewHandler.Android.cs`, `BlazorAndroidWebView.cs`
  - [x] Make all these types `internal` unless that breaks things at runtime. If we can't make any of them internal, discuss with the team since we would want to do something about making other members internal.
- `BlazorWebViewHandler.Android.cs`
  - [x] Remove both `GetWebChromeClient` and `GetWebViewClient`, inlining the logic where we use it

**Comment by agingo** [comment]
> We did an API review. Here are the things we want to change in the Android-specific sources:
> 
> * `AndroidWebKitWebViewManager.cs`, `BlazorWebViewHandler.Android.cs`, `BlazorAndroidWebView.cs`
>   
>   * [x]  Make all these types `internal` unless that breaks things at runtime. If we can't make any of them internal, discuss with the team since we would want to do something about making other members internal.
> * `BlazorWebViewHandler.Android.cs`
>   
>   * [x]  Remove both `GetWebChromeClient` and `GetWebViewClient`, inlining the logic where we use it

The latest change that removed 'GetWebChromeClient' disables the ability for the camera to function from JavaScript in the Maui Webview. 

**Our Scenario on Android**
We are using a JavaScript program in the Maui WebView to prompt the user for permission to the camera. Once approved the JavaScript uses the camera to look for barcodes and once found triggers an event to show the data on the screen. After the most recent change after the user approves access to the camera the javascript can no longer access the camera.

Will you please look into this and provide us with a fix? As of now our application is unable to use the camera.

Thanks,

**Comment by TanayParikh** [comment]
@agingo can you please confirm how you were accessing the camera using the `GetWebChromeClient`. A snippet would be great!
