### ISSUE TITLE
Icon on Alt-Tab not showing on Windows

### ISSUE THREAD

**Issue by emorell96** [dotnet/maui#5915]
### Description

When setting an icon using `<MauiIcon>`, the Icon shows on the task bar, but it doesn't when you are alt tabbing or on the Windows Timeline:

![image](https://user-images.githubusercontent.com/20151415/162463049-93d03aaa-4423-4232-9157-a303347cbbec.png)

### Steps to Reproduce

1. Create a new Maui project on Preview 14 (using the default template)
2. Hold Alt Tab.
3. No Icon appears next to the app on the Alt-Tab window.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19043

**Comment by emorell96** [comment]
Probably related, I just realized the page title doesn't appear either. Compare Edge to the App next to it that I am building with MAUI:
![image](https://user-images.githubusercontent.com/20151415/162545760-9da5cfc0-c130-4565-a26a-e340bb4519e0.png)

**Comment by kristinx0211** [comment]
verified repro on windows 10.0.19041.

**Comment by kristinx0211** [comment]
repro with 17.3.0 Preview 2.0 [32506.368.main].
