### ISSUE TITLE
[Android]: Prevent Entry from losing focus when touch to another child of the ViewGroup is performed

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#5916]
### Description

The [current implementation ](https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Android/LayoutViewGroup.cs#L61)of the the LayoutViewGroup contains a specific logic for the EditText widgets when DispatchTouchEvent is executed. The logic makes the EditText lose focus when touch is performed in the ViewGroup. That is altering and changing the default behavior of Android where focus is not lost in that case.

I believe an extensibility point should be introduced in the LayoutViewGroup that makes it possible to break the logic that makes the EditText lose focus.

### Public API Changes

One possible dummy solution could be a public bool property that tells whether the focus should be moved out of the EditText or that tells whether the logic in the LayoutViewGroup's should be overriden.

### Intended Use-Case

I am building a custom control that consists of Entry and two Buttons. I want to prevent the Entry from losing its focus when the buttons are pressed.

**Comment by jsuarezruiz** [comment]
This have been removed https://github.com/dotnet/maui/commit/a3d8d2034377fb169a13ff7e196a482ccfbd4686
