### ISSUE TITLE
Change BatteryPowerSource.Usb to BatteryPowerSource.Cable

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#5925]
### Description

The BatteryPowerSource.Usb is not applicable for Mac because it uses Type C. Although Type C is a USB type it's not called USB at all.

Also if there is a new type of cable comes in future then it won't be good idea to keep the name as Usb

### Public API Changes

`BatteryPowerSource.Cable:
`

### Intended Use-Case

`BatteryPowerSource.Cable:
`

**Comment by jfversluis** [comment]
I think this is irrelevant for now as a Mac/iDevice doesn't even report USB as seen in the Docs [here](https://docs.microsoft.com/xamarin/essentials/battery?context=xamarin%2Fxamarin-forms&tabs=ios#platform-differences)

For Android the literal platform API also reports it as USB and I think it's not uncommon to refer to "Type C" as USB-C.

I don't see any need to change this for the time being. Thanks for the suggestion!
