### ISSUE TITLE
[mauipalooza] Border doesn't contain or wrap image

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5928]
### Description

```xaml
<Border 
        Stroke="Red"
        StrokeThickness="1" HorizontalOptions="Fill">
        <Border.StrokeShape>
            <RoundRectangle CornerRadius="7"/>
        </Border.StrokeShape>
    <Image Source="plane.png" Aspect="AspectFill" HeightRequest="145"/>
</Border>
```

I expect this to put a border all the way around the image and clip it. It doesn't. As you can see in the image, the border is behind the image which is larger.
<img width="731" alt="Screen Shot 2022-04-08 at 5 38 23 PM" src="https://user-images.githubusercontent.com/41873/162543075-b2fffcf8-a6f6-4750-bb67-60e4504fa31c.png">

![Simulator Screen Shot - iPhone 13 Pro - 2022-04-08 at 17 45 46](https://user-images.githubusercontent.com/41873/162543477-e86ae47e-fd92-4f83-81dd-4da71389c6a6.png)

Source: https://github.com/davidortinau/dotnet-airlines

### Steps to Reproduce

Use the code provided and run it on Mac Catalyst or iOS.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

15.4

**Comment by kristinx0211** [comment]
verified repro on IOS 15.4.
