### ISSUE TITLE
[mauipalooza] ImageButton doesn't render gradient brush background

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5929]
### Description

The background doesn't render on Mac or iOS (and Android). It does work on Windows. Notice the gradient does render on the `Button` tho for Mac and iOS.

```xaml
<ImageButton WidthRequest="64" HeightRequest="64"
                        Background="{StaticResource BlueGradient}"
                        Source="arrow_swap.png"
                             Grid.RowSpan="2"
                             VerticalOptions="Center"
                             HorizontalOptions="Center"
                        >
                    <ImageButton.Clip>
                        <EllipseGeometry RadiusX="32" RadiusY="32"
                                         Center="32,32"/>
                    </ImageButton.Clip>
                </ImageButton>
```
<img width="731" alt="Screen Shot 2022-04-08 at 5 38 23 PM" src="https://user-images.githubusercontent.com/41873/162543789-b9c635c5-727f-4f0b-9187-4c688b609c59.png">

![Simulator Screen Shot - iPhone 13 Pro - 2022-04-08 at 17 45 46](https://user-images.githubusercontent.com/41873/162543939-2347a845-420d-40d5-a15b-4d6b77d0e391.png)

Android:
![Screenshot_1649517397](https://user-images.githubusercontent.com/41873/162580213-cd7bb958-2ed8-4d2c-863d-18b3e53d2e3d.png)

### Steps to Reproduce

Run this on iOS or Mac. Also now verified Android issue.

https://github.com/davidortinau/dotnet-airlines

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android, iOS, macOS

### Affected platform versions

15.4, API 30

**Comment by kristinx0211** [comment]
verified repro on Android 12 and the above project.
![image](https://user-images.githubusercontent.com/99457000/162615895-22db482b-669f-4cc4-b14c-7bdb2eb67fff.png)
