### ISSUE TITLE
[mauipalooza] CornerRadius not working on Button

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5930]
### Description

iOS:
<img width="368" alt="Screen Shot 2022-04-08 at 5 55 52 PM" src="https://user-images.githubusercontent.com/41873/162544251-8e8b99da-a871-416b-a2ca-8b703a312def.png">

Android:
<img width="365" alt="Screen Shot 2022-04-09 at 10 14 29 AM" src="https://user-images.githubusercontent.com/41873/162580133-197b5f07-e165-4355-90a4-226611df552a.png">

```xaml
<Button Text="Get Started"
                HeightRequest="70"
                Margin="40"
                FontSize="21"
                FontFamily="OpenSansSemiBold"
                Clicked="Button_Clicked"
                CornerRadius="7"
                Background="{StaticResource BlueGradient}"
                >
        </Button>
```

https://github.com/davidortinau/dotnet-airlines

### Steps to Reproduce

Run this on iOS or Mac.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android, iOS, macOS

### Affected platform versions

15.4, API 30

**Comment by kristinx0211** [comment]
verified repro on Android 12.
