### ISSUE TITLE
RadioButton has a weird dark background

### ISSUE THREAD

**Issue by cshung** [dotnet/maui#5931]
### Description

![image](https://user-images.githubusercontent.com/3410332/162545693-f9111157-2886-440b-ad01-14c4d4523829.png)

This happens **ONLY** on macOS, it is fine on Windows, Android or iOS.

### Steps to Reproduce

Running the repro for issue #5298 [here](https://github.com/dotnet/maui/files/8259367/5298.zip) on macOS will reproduce the issue.

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey

### Did you find any workaround?

I assume setting the background explicitly would be a valid workaround.

**Comment by jfversluis** [comment]
Hm it seems you are running macOS on Dark Theme? Does it show OK when you run it on Light Theme? I think the issue might almost be backwards. The background for the `RadioButton` is actually showing correct, but the background of the page isn't :D

**Comment by jindal1979** [comment]
The same issue is coming on Android in Dark theme mode with RC2.

**Comment by jfversluis** [comment]
Removing the macOS specific label. Additional info shows there is something not right with RadioButton in multiple scenarios on multiple platforms.

* On Android when you run the app in Dark Theme, the background does not match the background color of the default app template. In Light theme it seems OK
* A new report shows that the weird background is now also happening on iOS (see #7248, repro: https://github.com/emorell96/RadioButtonsIosStyle)
* Windows seems fine in both Light and Dark appearance.

Verified on current main that this is still an issue.

**Comment by dustin-wojciechowski** [comment]
It looks like the background color of RadioButton was fixed in this issue: https://github.com/dotnet/maui/issues/6006 which sets a default background color of transparent, and I can confirm I was not able to reproduce that part of the issue. 

With regard to the actual ellipse not appearing in dark mode using the default control template, I should  have a PR out for that soon.
