### ISSUE TITLE
Cannot hide tab bar or change flyout display options

### ISSUE THREAD

**Issue by spence-ss** [dotnet/maui#5932]
### Description

I'm only about 3 weeks in the whole Xamarin/Maui world, so I apologize in advance if these are previously handled or otherwise dismissive issues.  Also, I've really enjoyed learning and experimenting and look forward to future developments. 

[GitHub repo](https://github.com/spence-ss/MauiApp3) of a VS2022 Preview 2.1 > File > New app with everything spelled out as well.

### Dynamic Flyout Display Options

Setting the FlyoutDisplayOptions to a bindable property has no effect on Windows or Android.  Could be related to the [Issue#5653](https://github.com/dotnet/maui/issues/5653) and [Issue #5524](https://github.com/dotnet/maui/issues/5524).
```
<FlyoutItem
     FlyoutDisplayOptions="{Binding FlyoutDisplay}">

~ ViewModel
public FlyoutDisplayOptions FlyoutDisplay { get; set;} = FlyoutDisplayOptions.AsMultipleItems;
// also tried string property
public string FlyoutDisplay {get; set;} = "AsMultipleItems";
```
Setting the value in the code behind works on Android, but throws an Exception on Windows
```
<FlyoutItem
   x:Name = "FlyoutToggle">

~Shell.xaml.cs
  OnPropertyChanged(){
   FlyoutToggle.FlyoutDisplayOptions = Model.FlyoutDisplay; 
  }
```
![image](https://user-images.githubusercontent.com/24481989/162545898-47e059ba-d2e0-4f08-b354-19f55faa67d0.png)

### Tab Bar Visibility

Could be related to the title bar issues with WinUI as discussed in [Issue #5453](https://github.com/dotnet/maui/issues/5453), but setting the the TabBarIsVisible property has no effect on Windows.
```
<Shell
   TabBarIsVisible = "False">
```
However, the background color applies ok
```
<Shell
  TabBarBackgroundColor="HotPink">
```
The only code behind method I found was setting it to a bindable property, which I admit I haven't fully explored in C#.

### Dynamic Flyout Display
1. Create a maui app targeting Windows or Android
2. Add multiple shell content items inside a flyout item
3. Bind the FlyoutDisplayOptions to the view model in either platform OR attempt to set it directly in the code behind on Windows
4. Toggle the option between single/multiple 

### Tab Bar Visibility
1. Create a maui app targeting Windows
2. Add multiple shell content items inside a flyout item
3. Set the TabBarIsVisibleProperty to false anywhere inside the xaml

Sample App Repository [MauiApp3](https://github.com/spence-ss/MauiApp3)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 11 - framework 10.0.19041, Android Emulator 11.0 API 30

### Did you find any workaround?

Code behind manipulation works in some instances but not all.

**Comment by spence-ss** [comment]
To confirm setting tab bar visible does not work in the code behind either
```
~AppShell.xaml.cs

        Shell.SetNavBarIsVisible(this, false);  // Works
        Shell.SetTabBarIsVisible(this, false);  // No effect
```

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.2.0 Preview 2.1 [32317.152]. Repro on Windows and Android. Sample project: [MauiApp3](https://github.com/spence-ss/MauiApp3)

**Comment by kristinx0211** [comment]
verified on windows with 17.3.0 Preview 2.0 [32506.368.main], not repro. close it. feel free to open new issue if you still hit this failure with same/newer environment.
