### ISSUE TITLE
Large Images Not Shown Correctly

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5938]
### Description

When an application shows a large image it is shown in landscape mode, not portrait.

### Steps to Reproduce

1. Unzip the project from [Simple-image.zip](https://github.com/dotnet/maui/files/8456231/Simple-image.zip)
2. Compile and run it on Windows, it will show the image in landscape orientation, not portrait.
3. Compile and run it on Android. It will crash rendering the image reporting `Java.Lang.RuntimeException: 'Canvas: trying to draw too large(485897280bytes) bitmap.`
4. Here's a Xamarin version for comparison (it works as expected in Windows and Android).
[Xamarin-Simple-image.zip](https://github.com/dotnet/maui/files/8456260/Xamarin-Simple-image.zip)

The Windows version should look like this:
![simple-image](https://user-images.githubusercontent.com/12423046/162556036-8c1b0602-b6d6-44c2-8ea4-d88db2c7dd81.jpg)
 
The image jpg itself (in folder Simple\Simple\Resources\Images\large.jpg) shows up in portrait orientation if viewed in Windows, but interesting also displays (incorrectly) in landscape format in Visual Studio too. the image itself should look like this:
![large](https://user-images.githubusercontent.com/12423046/162556107-b3eeb31f-f51a-4585-b132-dcac195e10bb.jpg)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows 10 

### Did you find any workaround?

It does not happen with low resolution images (in this example try small.jpg)

**Comment by kristinx0211** [comment]
verified repro on windows, the image in landscape orientation, not portrait. vs 17.3.0 Preview 1.0 [32408.253.main].

**Comment by david-maw** [comment]
Yep. still broken in RC1, it's also a bug in Visual Studio itself, which exhibits the same rendering problem on large PG files, both for previews and full images being edited, see [Image orientation Wrong for large JPG images](https://developercommunity.visualstudio.com/t/Image-orientation-Wrong-for-large-JPG-im/10015503). It seems likely they are related.

**Comment by jonathanpeppers** [comment]
@david-maw on Android, it appears like this image is simply too big:

1. The image starts at 3008x5340
2. MAUI's build upscales this to 21360x12032, check in `obj\Debug\net6.0-android\resizetizer\r\drawable-xxxhdpi`

To workaround, specify `BaseSize` with the numbers divided by 8:

```xml
<MauiImage Update="Resources\Images\large.jpg" BaseSize="376,678" />
```

We should evaluate what MAUI does when `%(BaseSize)` is blank for non-`.svg` image formats.

The Windows issue looks like a completely different problem.

**Comment by david-maw** [comment]
Thanks @jonathanpeppers that workaround should do nicely for static images. On the face of it there seems no point upscaling a high resolution image, especially if the upscaled version will be too large for the target platform but that's perhaps what you had in mind with your "blank BaseSize" comment.

Actually, there's a related issue with images at run time too, basically if you hand one that's too large for the platform to an Image control it tries to render it in its native size and falls on its face, this is probably the sort of platform dependent decision that the Image control could handle and as a lazy consumer of it, I'd rather it handled it than I write code...

**Comment by jonathanpeppers** [comment]
@david-maw yes, until we get a release with the fix: https://github.com/dotnet/maui/pull/6419

I'd actually recommend doing:
```
<MauiImage Update="Resources\Images\*.jpg" Resize="false" />
<MauiImage Update="Resources\Images\*.png" Resize="false" />
```

**Comment by jonathanpeppers** [comment]
@david-maw does the workaround also solve the Windows issue???

![image](https://user-images.githubusercontent.com/840039/164773441-59ea707a-fb6c-4a4b-93cf-c223f1094150.png)

I'm confused on why... But it seems to fix it for me?

**Comment by jonathanpeppers** [comment]
Ok I believe #6419 solves Windows as well, because the build is rotating the Windows images when they are very large:

![image](https://user-images.githubusercontent.com/840039/164785203-c14660e7-bb32-4007-86e9-d68b424c91c5.png)

This may be a bug in Skia, when resizing very large images?

**Comment by jonathanpeppers** [comment]
I filed https://github.com/dotnet/maui/issues/6426 to look into why large images would be rotated.

I think this solved the problem, though -- as we don't even want this particular image to be that large.

**Comment by david-maw** [comment]
Thanks @jonathanpeppers I think you solved it too, at least for the static case. I'll file a separate bug for the dynamic-load-of-a-too-large-image if there seems to be a problem there.

Sorry for the slow response, I was busy this afternoon.

**Comment by jonathanpeppers** [comment]
I think #6426 should cover the second bug. Thanks!

**Comment by david-maw** [comment]
Thanks @jonathanpeppers, hopefully it will, as long as nobody gets wrapped around the axle and focuses on the fact that the example happens to be a generated (by resizetizer) file.

The App I was originally working with in Xamarin Forms simply crashed in Java code with what seemed to be an uncatchable error when presented with a very large jpg, I was able to code around that particular problem so it stopped being urgent, but I need to get back to it and reproduce the failure in a simpler environment so I can see how (and if) it fails in MAUI. The annoying thing was the large (12000x9000) image came from the inbuilt camera on a Samsung S21 so the device sort of shot itself in the foot by then faulting while trying to render an image it had generated. That said, an image like that does make a 400 MB+ uncompressed bitmap, so it is non-trivial. Anyway, it's on me to investigate all that when I get time, thanks again for resolving the more pressing problem.
