### ISSUE TITLE
Installing MAUI with dotnet installed with brew fails

### ISSUE THREAD

**Issue by XavierGeerinck** [dotnet/maui#5939]
### Description

When I wanted to run `dotnet workload install maui` it kept failing with the error: 

```
Workload installation failed: microsoft.maui.core.ref.android::6.0.101-preview.9.1805 is not found in NuGet feeds https://api.nuget.org/v3/index.json".
```

After researching a bit, I found an article recommending to run `dotnet --list-sdk` to see where it was installed. Since I installed dotnet through brew (`brew install dotnet`) this was the issue. When uninstalling it with `brew uninstall dotnet` and installed it from the dotnet site (https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.201-macos-arm64-installer) it started working.

### Steps to Reproduce

1. Install with brew (`brew install dotnet`)
2. Run `dotnet workload install maui`

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac Latest

### Did you find any workaround?

Uninstall with brew (`brew uninstall dotnet`) and install dotnet from (https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.201-macos-arm64-installer) then run `dotnet workload install maui`

**Comment by VincentBu** [comment]
Hi @jfversluis , I see your comment under [Error NETSDK1147 workloads must be installed: maui-android](https://github.com/dotnet/maui/issues/6077#issuecomment-1098876996). Is that also the solution for this issue?

**Comment by jfversluis** [comment]
There has been a lot of changes in this area. Please try this with all the latest releases and changes and let us know if this is still an issue for you. Thanks!
