### ISSUE TITLE
Publish window MAUI app - create executable

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#5940]
### Description

I used Visual Studio Community 2022 17.2 Preview 2.1 .NET MAUI Preview 14
My question is it possible to create executable in Window platform ?
In this link: https://www.youtube.com/watch?v=jfSVb_RR7X0
:Create a Signed and Publishable .NET MAUI Android App in VS2022
I this link:
https://www.youtube.com/watch?v=kpZi5xAvpZA
Release Your .NET MAUI iOS App to the Apple App Store
No info how to do it in window.

Thanks in advance ,

### Steps to Reproduce

1.Create Maui project.
2. Go to project/publish
3. See picture:
![image](https://user-images.githubusercontent.com/1079689/162566753-900804c6-3b29-4da0-ae9c-41cdfe2c4a57.png)
I got this exception:
03/04/2022 10:45:16
System.AggregateException: One or more errors occurred. ---> Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 14 (current)

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

No, want to know how to create executable file in window>

### Relevant log output

```shell
03/04/2022 10:45:16
System.AggregateException: One or more errors occurred. ---> Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details.
```

**Comment by danies8** [comment]
From event viewer:
Application: AutomationClient.MAUI.exe
CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at AutomationClient.MAUI.WinUI.Program.XamlCheckProcessRequirements()
   at AutomationClient.MAUI.WinUI.Program.Main(String[] args)

**Comment by kristinx0211** [comment]
verified repro on vs 17.3.0 Preview 1.0 [32408.253.main].

**Comment by jfversluis** [comment]
You can't create a published version through Visual Studio right now. The window you are referring to will not produce the right output. At this time it's only possible to create publishable versions through the command-line

**Comment by danies8** [comment]
So how is done ,with command line without certificate ?

**Comment by danies8** [comment]
In this video :https://www.youtube.com/watch?v=FNwv_W3TtSU
 it used signing key tp create executable,
 I need way to create executable file without signing key.
Can you please provide info how to do it ?

**Comment by danies8** [comment]
Can you please provide info how to do it , without  signing key.
