### ISSUE TITLE
Can't load types from xmlns http://schemas.microsoft.com/dotnet/2021/maui after a successful migration from Xamarin Forms to MAUI

### ISSUE THREAD

**Issue by meg-1** [dotnet/maui#5942]
### Description

hello! i have been having an issue while migrating my Xamarin Forms project to MAUI.

here is my current setup:
1. Microsoft Visual Studio Community 2019 Version 16.11.11
2.   .NET SDK - Workloads (6.0.200):
                 - android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.200 : 31.0.200-preview.12.2) installed.
                 - maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.200 : 6.0.200-preview.12.2441) installed.
3. .NET SDKs used:   6.0.200 [C:\Program Files\dotnet\sdk]

the migration was done by following the official instructions:
https://docs.microsoft.com/en-us/dotnet/maui/get-started/migrate
https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview

also here is the output of 'maui-check' run in the console:
![image](https://user-images.githubusercontent.com/62753112/162569698-a4dee0c5-4940-4acd-8a9c-6f9e8f1cf9a9.png)
![image](https://user-images.githubusercontent.com/62753112/162569715-a2fcc62f-3f69-4012-9bf4-f3ec57ee2c28.png)

here is the zip folder of my project:
[TaskApp1.zip](https://github.com/dotnet/maui/files/8456806/TaskApp1.zip)

### Steps to Reproduce

1. during the first build of the project i get these errors:
![image](https://user-images.githubusercontent.com/62753112/162569189-36f07f16-32f8-4026-ba5f-dfd2c1864960.png)

2. after that i delete the 'bin' and 'obj' folders inside from the project folders

3. following that, i rebuild by project again, and get only one error that goes as this:
![image](https://user-images.githubusercontent.com/62753112/162569292-04d5c92a-efaf-4718-838f-ad42a6961f24.png)

### Version with bug

Preview 12

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 31

### Relevant log output

```shell
1>------ Rebuild All started: Project: TaskApp1, Configuration: Debug Any CPU ------
Restored C:\Users\Legion\Desktop\New folder\TaskApp1\TaskApp1.csproj (in 555 ms).
1>C:\Program Files\dotnet\sdk\6.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(134,5): warning NETSDK1182: Targeting .NET 6.0 in Visual Studio 2019 is not supported.
1>Done building project "TaskApp1.csproj".
1>App.xaml : error : Can't load types from xmlns http://schemas.microsoft.com/dotnet/2021/maui
1>Done building project "TaskApp1.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by kcrg** [comment]
I think nuget OxyPlot.Xamarin.Forms is a problem here, in dependencies it have Xamarin.Forms (>= 2.3.3.180). It is super old so also it want to pull some old Xamarin.Android.Support.* packages. If I understand migration correctly, you can't mix MAUI with Xamarin.Forms.

**Comment by MagicAndre1981** [comment]
also, to use MAUI you need VS 2022 17.2 (preview)

**Comment by jfversluis** [comment]
Yeah I see a couple of strange things in here. You can't use .NET MAUI with Visual Studio 2019. Update to the 2022 preview version. Additionally, I see you mention preview 12 of .NET MAUI while we're at preview 14 and almost RC1. 

Make sure to use all the latest and support bits and try again please. Another hint might definitely be that NuGet. You can't just put Xamarin.Forms plugins in a .NET MAUI app unless the plugin has been updated to support .NET MAUI.

If you still see an issue after doing all this, please open a new one. Thanks!

**Comment by meg-1** [comment]
> Yeah I see a couple of strange things in here. You can't use .NET MAUI with Visual Studio 2019. Update to the 2022 preview version. Additionally, I see you mention preview 12 of .NET MAUI while we're at preview 14 and almost RC1.
> 
> Make sure to use all the latest and support bits and try again please. Another hint might definitely be that NuGet. You can't just put Xamarin.Forms plugins in a .NET MAUI app unless the plugin has been updated to support .NET MAUI.
> 
> If you still see an issue after doing all this, please open a new one. Thanks!

@jfversluis @kcrg @MagicAndre1981 , thank you very much for your suggestions, time, and answers! i will try to implement them!
