### ISSUE TITLE
FontImageSource: "Java.Lang.IllegalArgumentException: width and height must be > 0" on some devices

### ISSUE THREAD

**Issue by chrfin** [dotnet/maui#5943]
### Description

I'm using a `FontImageSource` (font is the current fontawesome) as `TabBar`-icons in a shell and on some devices (Galaxy S9 running Android 10) the app crashes on startup and I get the following error logged:

> Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
> Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String , IJavaPeerable , JniArgumentValue* )
> Bumptech.Glide.Load.Engine.BitmapRecycle.BitmapPoolAdapter.Get(Int32 , Int32 , Config )
> Microsoft.Maui.BumptechGlide.FontImageSourceDecoder.<Decode>b__2_0(Int32 w, Int32 h, Config c)
> Microsoft.Maui.FontImageSourceService.RenderBitmap(IModel model, Func`4 newBitmap)
> Microsoft.Maui.BumptechGlide.FontImageSourceDecoder.Decode(Object model, Int32 width, Int32 height, Options options)
> Bumptech.Glide.Load.IResourceDecoderInvoker.n_Decode_Ljava_lang_Object_IILcom_bumptech_glide_load_Options_(IntPtr , IntPtr , IntPtr , Int32 , Int32 , IntPtr )
> java.lang.IllegalArgumentException: width and height must be > 0
> android.graphics.Bitmap.createBitmap Bitmap.java:1148
> android.graphics.Bitmap.createBitmap Bitmap.java:1115
> android.graphics.Bitmap.createBitmap Bitmap.java:1065
> android.graphics.Bitmap.createBitmap Bitmap.java:1026
> com.bumptech.glide.load.engine.bitmap_recycle.BitmapPoolAdapter.get BitmapPoolAdapter.java:30
> crc649aa6eff787b332dd.FontImageSourceDecoder.n_decode(Native Method)
> crc649aa6eff787b332dd.FontImageSourceDecoder.decode FontImageSourceDecoder.java:31
> com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList DecodePath.java:92
> com.bumptech.glide.load.engine.DecodePath.decodeResource DecodePath.java:70
> com.bumptech.glide.load.engine.DecodePath.decode DecodePath.java:59
> com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList LoadPath.java:76
> com.bumptech.glide.load.engine.LoadPath.load LoadPath.java:57
> com.bumptech.glide.load.engine.DecodeJob.runLoadPath DecodeJob.java:529
> com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher DecodeJob.java:493
> com.bumptech.glide.load.engine.DecodeJob.decodeFromData DecodeJob.java:479
> com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData DecodeJob.java:430
> com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady DecodeJob.java:394
> com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal SourceGenerator.java:148
> com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady SourceGenerator.java:76
> crc649aa6eff787b332dd.PassThroughModelLoader_1_DataFetcher.n_loadData(Native Method)
> crc649aa6eff787b332dd.PassThroughModelLoader_1_DataFetcher.loadData PassThroughModelLoader_1_DataFetcher.java:73
> com.bumptech.glide.load.engine.SourceGenerator.startNextLoad SourceGenerator.java:70
> com.bumptech.glide.load.engine.SourceGenerator.startNext SourceGenerator.java:63
> com.bumptech.glide.load.engine.DecodeJob.runGenerators DecodeJob.java:311
> com.bumptech.glide.load.engine.DecodeJob.runWrapped DecodeJob.java:280
> com.bumptech.glide.load.engine.DecodeJob.run DecodeJob.java:235
> java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1167
> java.util.concurrent.ThreadPoolExecutor$Worker.run ThreadPoolExecutor.java:641
> java.lang.Thread.run Thread.java:919
> com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run GlideExecutor.java:393

### Steps to Reproduce

I can't, but it is reproducible on the beta-testers device...

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

No

**Comment by v-longmin** [comment]
@chrfin Could you share your repro project? Thanls.

**Comment by chrfin** [comment]
According to the user the problem does not occur anymore...

I'll reopen if I get another report.
