### ISSUE TITLE
[mauipalooza] ImageButton isn't clipping on Android

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5948]
### Description

```xaml
<ImageButton WidthRequest="64" HeightRequest="64"
                        Background="{StaticResource BlueGradient}"
                        Source="arrow_swap.png"
                             Grid.RowSpan="2"
                             VerticalOptions="Center"
                             HorizontalOptions="Center">
                    <ImageButton.Clip>
                        <EllipseGeometry RadiusX="32"
                                         RadiusY="32"
                                         Center="32,32"/>
                    </ImageButton.Clip>
                </ImageButton>
```

![Screenshot_1649517397](https://user-images.githubusercontent.com/41873/162580364-0d046620-0201-430e-960e-6325d417de49.png)

https://github.com/davidortinau/dotnet-airlines

### Steps to Reproduce

Run the sample on Android

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30

**Comment by kristinx0211** [comment]
verified repro on Android and the above project.
