### ISSUE TITLE
[mauipalooza] Button background doesn't render gradient

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5950]
### Description

This is only happening on Android. The button background is a gradient, but doesn't render.

![Screenshot_1649517645](https://user-images.githubusercontent.com/41873/162580703-be9d3bf1-9d59-4020-a7c8-ad4206ff06f3.png)

```xaml
<Button Text="Find Flights"
                HeightRequest="70"
                FontSize="21"
                FontFamily="OpenSansSemiBold" CornerRadius="7"
                Background="{StaticResource BlueGradient}"/>
```

From styles:
```xaml
<LinearGradientBrush x:Key="BlueGradient" EndPoint="1,0">
        <GradientStop Color="#3784DE"
                          Offset="1.0" />
        <GradientStop Color="#7BD2FD"
                          Offset="0.1" />
    </LinearGradientBrush>
```

iOS for comparison:
![Simulator Screen Shot - iPhone 13 Pro - 2022-04-08 at 18 00 53](https://user-images.githubusercontent.com/41873/162580734-3b9fcca6-7b94-4f09-b536-d6130586130f.png)

### Steps to Reproduce

Run https://github.com/davidortinau/dotnet-airlines

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30

**Comment by kristinx0211** [comment]
verified repro on Android 12.
