### ISSUE TITLE
Application cannot be started on Windows - WINAPPSDKGENERATEPROJECTPRIFILE

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#5953]
### Description

I was attending a conference about MAUI and this project was showed as a sample.
Two weeks ago, it was updated to Preview 14 and some features like FilePicker and Share button were added.
The project cannot be started for Windows (both Debug and Release builds don't work) with the following error - `"Duplicate Entry"`:

![image](https://user-images.githubusercontent.com/64279914/162592956-2503cf6e-131e-4d1a-8eb3-4611cf1b6be8.png)
```

Severity	Code	Description	Project	File	Line	Suppression State
Error		

PRI175: 0x80073b0f - Processing Resources failed with error: Zadání je duplicitní.	CookBook.Mobile	C:\Users\janse\source\repos\cookbook-maui-main\src\CookBook\CookBook.Mobile\WINAPPSDKGENERATEPROJECTPRIFILE	1	
Error		
PRI222: 0x80073b0f - Unspecified error occurred.	CookBook.Mobile	C:\Users\janse\source\repos\cookbook-maui-main\src\CookBook\CookBook.Mobile\WINAPPSDKGENERATEPROJECTPRIFILE	1	

```

### Steps to Reproduce

Download https://github.com/jasho/cookbook-maui
Open in VS 2022 Preview Version 17.2.0 Preview 2.1 Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Default MAUI installed etc.

I also uninstalled VS Professional and installed VS Community clean install and the problem persists.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

My OS is:
```
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19043 N/A Build 19043

```
### Affected platform versions

I don't know but I can see this:
![image](https://user-images.githubusercontent.com/64279914/162593045-c4a76f42-2a1d-4540-a94e-9c7871dd7cce.png)

### Did you find any workaround?

No

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error		

PRI175: 0x80073b0f - Processing Resources failed with error: Zadání je duplicitní.	CookBook.Mobile	C:\Users\janse\source\repos\cookbook-maui-main\src\CookBook\CookBook.Mobile\WINAPPSDKGENERATEPROJECTPRIFILE	1	
Error		
PRI222: 0x80073b0f - Unspecified error occurred.	CookBook.Mobile	C:\Users\janse\source\repos\cookbook-maui-main\src\CookBook\CookBook.Mobile\WINAPPSDKGENERATEPROJECTPRIFILE	1
```

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.2.0 Preview 2.1 [32317.152]. Repro on Windows with above project.

**Comment by emorell96** [comment]
Updating to MAUI community toolkit RC2 solved this for me.

**Comment by miguelangelcv** [comment]
> Updating to MAUI community toolkit RC2 solved this for me.

The same thing happened to me. Updating the community toolkit also fixed the problem for me.

**Comment by samhouts** [comment]
Closing since this is now resolved with MCT RC2. Thanks!

**Comment by mattleibow** [comment]
Just adding a note, I have a workaround: https://github.com/mattleibow/DuplicateEntryMauiTest/blob/main/Directory.Build.targets
