### ISSUE TITLE
Build for Android outputs Windows error

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#5954]
### Description

This issue is related to [this issue](https://github.com/dotnet/maui/issues/5953) - it uses the same source code project.

The issue speaks about that the following project fails to build for Windows:
https://github.com/jasho/cookbook-maui

Sometimes, when attempting to build Android after unsuccessful Windows build, Android build receives the Windows build error and can after than, Android can no more be built as well.

It took me some attempts to reproduce, so the video is a bit long- the important part is 7:00 and later:
https://www.veed.io/view/89e8f6d0-5149-438e-8896-761195c04f22

7:00 Android builds and runs successfully
7:35 Windows is selected to build -> ends with expected error
7:55 Android build is attempted - fails with Windows error and every subsequent attempted Android build fails with this unrelated error

This is not fixed even after:
- `Clean Solution` is executed while Android device is selected
- `Clean Solution` is executed while "Windows Machine" is selected
- `bin `and `obj `folders are deleted manually

The issue is fixed after:
- **Visual Studio is restarted**

VS 2022 Preview Version 17.2.0 Preview 2.1 Microsoft Visual Studio Professional 2022 (64-bit) - Preview
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19043 N/A Build 19043

### Steps to Reproduce

Download https://github.com/jasho/cookbook-maui
Follow the steps in Video.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11

### Did you find any workaround?

Restart Visual Studio

**Comment by kristinx0211** [comment]
@janseris Thank you so much for your bug report! Unfortunately, The reproduce video is not available to watch. could you confirm it.

**Comment by janseris** [comment]
@kristinx0211
Thank you for letting me know. I have compressed it to be able to upload here so now it should stay.
https://user-images.githubusercontent.com/64279914/163371898-242b490c-f420-470e-9404-2d5644daeb74.mp4

**Comment by v-longmin** [comment]
Verified repro on VS 17.2.0 preview 2.1 [32317.152]. Repro project:
[cookbook-maui-main.zip](https://github.com/dotnet/maui/files/8493486/cookbook-maui-main.zip)
