### ISSUE TITLE
NavigationPage.BarTextColor Error

### ISSUE THREAD

**Issue by XiangLiAn627** [dotnet/maui#5955]
### Description

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="EPN.Core.DevOps.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}"
             **NavigationPage.BarTextColor="{DynamicResource SecondaryColor}"**
             Title="test"
             >

</ContentPage>

### Steps to Reproduce

![EBDF3C8A-EB91-420a-9BAB-D632F62D80A9](https://user-images.githubusercontent.com/52099127/162600224-cd5f5a25-ac06-490e-845c-a2b2d1edf17e.png)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

windows10.0.19041

**Comment by StephaneDelcroix** [comment]
I can only guess what you're trying to report here. It looks like you're trying to set the `BarTextColor` property has an attached property of the NavigationPage. But it isn't. It's a property of `NavigationPage`, and has to be set on the NavigationPage itself.
