### ISSUE TITLE
Android - APT2000 build error when project path contains non-ASCII symbols

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#5957]
### Description

Putting project in a folder/directory containing some non-ASCII chars, like Czech alphabet (tested with **_á_**) breaks Android build.
This does not affect any other C# projects. I have beeing using WinForms, Blazor, WPF on this path and all has been working fine for years. 
Even VS Solution, folder names and class and property names can contain these special symbols fine.
It seems like the problem is in Android tools.
I have experienced these issues with C++ compilers and other UNIX tools which live in the ASCII-only world.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2000	System cannot find file. (2).	Tempus.Mobile.GUI	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.14.106\tools\Xamarin.Android.Aapt2.targets	217	
```

![image](https://user-images.githubusercontent.com/64279914/162613888-72e047a4-0d0e-423d-a522-ee8347a6c173.png)

### Steps to Reproduce

Put project in any path containing "á" symbol.
I created a minimal repro with `C:/á/ProjectFolder`

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

**Comment by kristinx0211** [comment]
verified repro on vs 17.3.0 Preview 1.0 [32408.253.main].
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2000	The system cannot find the file specified. (2).	MauiApp1	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.300-rc.1.4\tools\Xamarin.Android.Aapt2.targets	217	
```

**Comment by Eilon** [comment]
@jonathanpeppers - does this look like it should go to the Xamarin Android repo?

**Comment by jonathanpeppers** [comment]
/cc @dellis1972

I thought we had some tests for this, but looks like `aapt2.exe` is failing.

**Comment by jonathanpeppers** [comment]
@Eilon are you using a tool to move these? If so, move this one, too.

**Comment by Eilon** [comment]
Moved to https://github.com/xamarin/xamarin-android/issues/6925.

@jonathanpeppers yeah copy & paste 😁 I have a tool that can do this but for some reason it's not working with the Xamarin Android repo. Maybe because of Single Sign-On?
