### ISSUE TITLE
Button stays enabled even if set as disabled if it is bound to a command

### ISSUE THREAD

**Issue by emorell96** [dotnet/maui#5959]
### Description

The button stays functional even if IsEnabled is set to False when there's a command bound to it.

Reproduction repo: https://github.com/emorell96/ButtonCommandEnabledBug

![Recording 2022-04-10 at 13 25 56](https://user-images.githubusercontent.com/20151415/162615862-93d41e4e-6210-4b3b-8a96-f506fb53e4cd.gif)

### Steps to Reproduce

1. Create a new MAUI app in preview14
2. Add a command and bind it to the button
3. Set the button as disabled
4. Run and click on the button.
5. See how the command still runs.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19043

### Did you find any workaround?

None

**Comment by kristinx0211** [comment]
repro on vs 17.3.0 Preview 1.0 [32408.253.main].

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue with main branch (RC2).

![image](https://user-images.githubusercontent.com/6755973/162784408-ee4ac0e1-2efb-4cd1-9ba2-0919aea50b3c.png)
