### ISSUE TITLE
Windows Desktop apps on Mac

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#5960]
### Description

Hi,

if you can develop Mac OS apps and iOS apps on Windows then why can't you develop Windows desktop apps on Mac?

I hope this will be included when MAUI is launched because it will be a big help to the developers

Windows Desktop Simulator should be available so we can test the Windows App on Mac

Thanks,
Jassim

### Public API Changes

[No Code]

### Intended Use-Case

[No Code]

**Comment by jfversluis** [comment]
Thanks for the suggestion, if we could we would. Unfortunately, this is not possible.
