### ISSUE TITLE
Shell allows navigation when it should not

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#5964]
### Description

When using Shell XAML to define a program flow with a startup page then flyout navigation it should not be possible to navigate away from the startup page. For example with XAML like this:

```
<Shell ...>
    <TabBar>
        <ShellContent Title="Startup Page" ContentTemplate="{DataTemplate local:StartupPage}"/>
    </TabBar>
    <ShellContent Title="Main Page" ContentTemplate="{DataTemplate local:MainPage}" Route="FirstPage"/>
</Shell>

```
Initially local:StartupPage ought to show and until it navigates somewhere else, that's it. Instead the user can make use of flyout navigation to leave the page prematurely.

### Steps to Reproduce

1. Unzip the project from [MultiPage-startuppage.zip](https://github.com/dotnet/maui/files/8460173/MultiPage-startuppage.zip)
2.  Compile and run it on Windows, you should see this
![multipage-startuppage](https://user-images.githubusercontent.com/12423046/162645231-ceff1d56-baee-4ec6-97bf-d9036be676a7.jpg)
3. Until the countdown completes you should be unable to navigate to another page but clicking on the hamburger icon will open up the flyout and allow you to navigate.

I tried it on Android and it seems to work correctly there. 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.2.0 Preview 2.1 [32317.152]. Repro on Windows with above project.

**Comment by BinaryAssault** [comment]
I handle this type of situation by adding this to the XAML of the page I don't want to have a flyout. Then in the code, I navigate to the 'main' page, which will show the flyout.

I looked at your StartupPage.xaml and don't see these. 

``````
Shell.FlyoutBehavior="Disabled"
Shell.NavBarIsVisible="False"
``````

**Comment by david-maw** [comment]
Thanks, `Shell.FlyoutBehavior="Disabled"` would do the trick if it worked in MAUI, but for me at least, it does not seem to.

`Shell.NavBarIsVisible="False"` also seems not to work in MAUI. Even if it did it would prevent tollbar icons from appearing (if the page had any, my example startup page didn't), but it does not seem to be needed in this case, so no problem there.

All in all this would be an excellent workaround but does not work in MAUI and even if it did would:

1. not be the same as Xamarin Forms and 
2. seem to contradict what @pureween wrote in the comments on issue #5470.

Still, it's a simple enough XAML update that if it worked it would solve my problem. Either changing it to work like Xamarin forms or fixing it and documenting the new behavior as a breaking change seems fine to me.

**Comment by david-maw** [comment]
Seems to be fixed in RC1, the behavior of the page heading and back button on  PushAsync seems problematic still, but the basic problem this issue was reporting seems to be corrected.

**Comment by Redth** [comment]
There were some more fixes that will go into RC2 around this, please open a new issue after RC2 with any specifics you still see as an issue.
