### ISSUE TITLE
Minimize button and maximize button of Window work only after double click

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#5966]
### Description

Minimize button and maximize button of Window work only after double click

### Steps to Reproduce

1.Create Maui App.
2.Try to minimize or maximize the window, it happened only after double click.
3.There is gap(margin) redundant in the height of this buttons(see picture).

![image](https://user-images.githubusercontent.com/1079689/162675693-c3677ffb-7f4a-4194-8cdb-198492d7b7cb.png)

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 14 (current)

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

double clicks

**Comment by kristinx0211** [comment]
not repro on window with vs 17.3.0 Preview 1.0 [32408.253.main]. click on the minimize button and maximize button can works.

**Comment by danies8** [comment]
What about the gap/margin ?  the bar is too height ?

**Comment by jfversluis** [comment]
The too big title bar is a bug and that will be fixed with the next release (RC2, so not the immediate next release) by #5811

**Comment by danies8** [comment]
In vs 2017 preview 5 big title bar fixed but still minimize button and maximize button are not working.
