### ISSUE TITLE
Add Folder Dialog

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#5969]
### Description

Hi,
I used this link: https://blog.verslu.is/maui/folder-picker-with-dotnet-maui/?utm_campaign=Weekly%2BXamarin&utm_medium=web&utm_source=Weekly_Xamarin_339
but is not working ?

### Steps to Reproduce

1.Create MAUI app.
2.Define IFolderPicker Interface
`public interface IFolderPicker
{
    Task<string> PickFolder();
}`
3.Create a new file under Platforms\Windows. The logical name would be FolderPicker.cs but of course it can be anything you like. You can see the code for this below.

`using WindowsFolderPicker = Windows.Storage.Pickers.FolderPicker;

namespace MauiFolderPickerSample.Platforms.Windows
{
    public class FolderPicker : IFolderPicker
    {
        public async Task<string> PickFolder()
        {
            var folderPicker = new WindowsFolderPicker();

            // Get the current window's HWND by passing in the Window object
            var hwnd = ((MauiWinUIWindow)App.Current.Windows[0].Handler.PlatformView).WindowHandle; // not complied

            // Associate the HWND with the file picker
            WinRT.Interop.InitializeWithWindow.Initialize(folderPicker, hwnd); // not complied

            var result = await folderPicker.PickSingleFolderAsync();

            return result.Path;
        }
    }
}`

4.Register Folder Picker Implementation
`public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
            });

// Note: this part was added

#if WINDOWS
        builder.Services.AddTransient<IFolderPicker, Platforms.Windows.FolderPicker>();
#elif MACCATALYST
		builder.Services.AddTransient<IFolderPicker, Platforms.MacCatalyst.FolderPicker>();
#endif
        builder.Services.AddTransient<MainPage>();
        builder.Services.AddTransient<App>();
// Note: end added part

        return builder.Build();
    }
}`

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 14 (current)

### Affected platforms

Windows

### Affected platform versions

...

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Please define "but is not working ?" this is not really something that helps us diagnose any issues

**Comment by danies8** [comment]
Its not complied .look on the code I stated the lines that is not complied.
If you need something more I will supply any code.

**Comment by jfversluis** [comment]
Updated the code so that it works with the latest .NET MAUI release. Update your repo and it should work now :)

**Comment by danies8** [comment]
jfversluis-:)
P.S
I build a big application in MAUI preview 14 and we test it and all bugs we reports.

**Comment by danies8** [comment]
Now, I used the latest release (rc1) and I got this error, how us can be fixed ?
![image](https://user-images.githubusercontent.com/1079689/165717421-fb17247c-5759-4ffe-bb77-cea590250d24.png)

**Comment by danies8** [comment]
Error HRESULT E_FAIL has been returned from a call to a COM component.

**Comment by danies8** [comment]
After further testing we eventually figured out that the issue on windows 10 can be resolved from adding the following to the windows platform code: folderPicker.FileTypeFilter.Add("*");

**Comment by danies8** [comment]
When I run the app and click first time is open the pickup folder on second click it crashed. why?
[MauiApp19.zip](https://github.com/dotnet/maui/files/8582144/MauiApp19.zip)
y
