### ISSUE TITLE
No option to add resource dictionary file

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#5970]
### Description

No possible to add resource dictionary file to Maui spp

### Steps to Reproduce

1.create Maui app.
2.try to add resource dictionary file.
3. No option.

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 14 (current)

### Affected platforms

Windows

### Affected platform versions

..

### Did you find any workaround?

..

### Relevant log output

```shell
..
```

**Comment by jfversluis** [comment]
Fixed by #5052 available as of RC1
