### ISSUE TITLE
Changing Button.BackgroundColor does not take effect immediately on Windows

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/maui#5972]
### Description

It seems to only take effect when the cursor is moved outside of the Button's boundary.

![BackgroundColor-WindowsButton](https://user-images.githubusercontent.com/6835152/162769188-bc9c2516-1e09-45b6-80b9-54a47763d47f.gif)

### Steps to Reproduce

Use the hit testing tool from #5892 (Samples app).

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/4386
