### ISSUE TITLE
Setting View.BackgroundColor = null doesn't reset the color on Android

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/maui#5973]
### Description

When setting some BackgroundColor arbitrary color, then resetting it to `null` later, the controls keep the color.

![BackgroundColor-Android](https://user-images.githubusercontent.com/6835152/162769963-cea112c9-5801-4fb4-b63d-3f9199c29836.gif)

### Steps to Reproduce

Use the hit testing tool from #5892. (Samples app).

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by PureWeen** [comment]
That's by design

https://github.com/dotnet/maui/pull/1485

Which is why we also are now including default styles with the templates
https://github.com/dotnet/maui/pull/5111

**Comment by jsuarezruiz** [comment]
Seems to work correctly now
![issue-5973](https://user-images.githubusercontent.com/6755973/186125474-8ad48faf-80be-4afe-a1a1-1890bdd45d3f.gif)
