### ISSUE TITLE
Setting BackgroundColor from code doesn't do anything for Shapes

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/maui#5974]
### Description

As the title says. It doesn't work from Xaml either:

```xml
<Ellipse  WidthRequest="150" HeightRequest="50" StrokeThickness="10" Stroke="Green"  BackgroundColor="Blue"/>
```

### Steps to Reproduce

Use the hit testing tool from #5892 (Samples app) and click on the Ellipse or the RoundedRectangle.

### Affected platforms

Android, Windows

**Comment by v-longmin** [comment]
@antonfirsov Could you share your repro project for us so that we can reproduce this issue? Thanks.

**Comment by kristinx0211** [comment]
verified setting BackgroundColor does not work on android 11.
