### ISSUE TITLE
ControlTemplate not rendered if applied to a ContentPage

### ISSUE THREAD

**Issue by MaurizioPanzica** [dotnet/maui#5976]
### Description

ControlTemplate applied to a ContentPage is not rendered at all.

Same issue as reported on #2302 but in their sample kristinx0211 applied the ControlTemplate to a ContentView and not to the ContentPage as stated.
Hence issue #2302 has been closed without addressing the bug.
This issue is still present on Preview 14.

### Steps to Reproduce

Create a new maui app
Crate a ControlTemplate inside your App.xaml
Use this control in a ContentPage and navigate to it

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11+, iOS 15+

**Comment by v-longmin** [comment]
verified repro on Android 12.0-API31 with VS 17.2.0 Preview 2.1 [32317.152.main].
