### ISSUE TITLE
Debugger wrongly assigns SDK Version to device 

### ISSUE THREAD

**Issue by PontiacGTX** [dotnet/maui#5977]
### Description

I have just installed Visual studio 2022 and It has net 6.0.201 installed and I have created a new project using Maui Preview and I have noticed that the debugging device shows that my phone has an older Android version and an older Android SDK, and I have installed latest Android SDK(as my phone uses Android 12) so I wonder if this issue is related to the debugger or the Maui Project Target framework

### Steps to Reproduce

1.Creata a new Maui App
2.Use a phone with Filesharing/transfer mode (like in this case a Xioami Redmi note 8 )

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 SDK 31

### Relevant log output

```shell
Project's csproj file Property group that contains the target framework but it says 21? and I dont see an option to set it on Visual studio 2022 as 
`<PropertyGroup>
		<TargetFrameworks>net6.0-android;</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>MauiApp1</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>

		<!-- Display name -->
		<ApplicationTitle>MauiApp1</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.mauiapp1</ApplicationId>
		<ApplicationId Condition="$(TargetFramework.Contains('-windows'))">875E21B1-8D24-4E1D-BF9C-9A746422EC52</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- Required for C# Hot Reload -->
		<UseInterpreter Condition="'$(Configuration)' == 'Debug'">True</UseInterpreter>

		
		<SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net6.0-android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>
`
```

Microsoft Visual Studio Community 2022 (64 bits) - Current
Versión 17.1.3

**Comment by jfversluis** [comment]
I'm not quite sure what you mean with this issue, sorry. Are you saying that the emulator (and SDK) Visual Studio detects isn't the right one? What happens if you review the Android Device Manager? Does the Android SDK Path in Visual Studio look OK? Could you provide a bit more information about the problem you think you see and the background?
