### ISSUE TITLE
[Spec] release branching strategy for maui, xamarin-macios, and xamarin-android

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/maui#598]
Other .NET repos have branch names such as:

* https://github.com/dotnet/installer/tree/release/6.0.1xx-preview1
* https://github.com/dotnet/installer/tree/release/6.0.1xx-preview2

Starting with Preview 4, I think we should create a new `6.0.1xx-preview4` branch on:

* [dotnet/maui](https://github.com/dotnet/maui)
* [xamarin/xamarin-macios](https://github.com/xamarin/xamarin-macios)
* [xamarin/xamarin-android](https://github.com/xamarin/xamarin-android)

Looking at the [.NET 6 Schedule (private link)](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/12561/NET-6-Schedule), we would do this during the `Release branch snap and build` timeframe. We would do this after bumping to an appropriate Preview 4 build of the dotnet/sdk.

I think branching will be done manually by each team for now.

## Versions

Right now we have versions such as:

* Android: 11.0.200-ci.main.148
* MacCatalyst: 14.3.100-ci.main.337
* iOS: 14.4.100-ci.main.1192

After branching, we can manually make a commit that changes these versions so they come out to:

* Android: 11.0.200-preview.4.148
* MacCatalyst: 14.3.100-preview.4.337
* iOS: 14.4.100-preview.4.1192

Maui appears to have appropriate versioning already. I would recommend bumping the version to `preview.5` on `main`, once `6.0.1xx-preview4` is branched.

See our [doc for details on versioning](https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNet.md#package-versioning-scheme).

/cc @dalexsoto @jonpryor @Redth

**Comment by dalexsoto** [comment]
@jonathanpeppers looks good to me, please coordinate with either @rolfbjarne or @mandel-macaque for branching.

**Comment by jonathanpeppers** [comment]
@rmarinho I think you could do either one:

1. Use `ci.main` on `main`. Release branches have the number of the preview.
2. Use the next preview on `main`, and increment it each time you branch.

xamarin-android and xamarin-macios are doing option 1, but it's up to you.

**Comment by rmarinho** [comment]
I think we are going to keep the option 2

**Comment by jonathanpeppers** [comment]
FYI for when we branch for Preview 4, we should use the branch name:

    release/6.0.1xx-preview4

When we branched for Preview 3, I messed up and forgot to put `release/` in the front:

https://github.com/xamarin/xamarin-android/tree/6.0.1xx-preview3

/cc @rmarinho @pjcollins @jonpryor @dalexsoto @mandel-macaque

**Comment by rmarinho** [comment]
Just heads up we are going to make main do ci.main, and after we branch we will update GitInfo that commands the version numbers to be -preview4
