### ISSUE TITLE
Soft Keyboard does not Pop Up when Entry View's Focus is set to True Programmatically

### ISSUE THREAD

**Issue by cbaer-extron** [dotnet/maui#5983]
### Description

When Focus is set to an Entry view programmatically (entryTest.Focus()), the cursor blinks in the edit field of the Entry view, but the soft keyboard does not pop up as it should until you physically touch the Entry view.  In comparison to Xamarin Forms where the keyboard pops up when executing entryTest.Focus().

Also, entryTest.Focus() is ignored when placed in the OnAppearing Event.

Video demo of Maui App:

https://user-images.githubusercontent.com/101732760/162827580-c62e0530-9fa1-4f90-b744-90c37caeec57.mp4

Video demo of Xamarin Forms version:

https://user-images.githubusercontent.com/101732760/162827635-9904fcb9-7276-4eba-8d90-ac4c2c7019d9.mp4

XAML:
![image](https://user-images.githubusercontent.com/101732760/162827039-06a7d605-2791-4931-962d-96b733f961d8.png)

Code Behind:
![image](https://user-images.githubusercontent.com/101732760/162827199-b1557e27-aac7-4c69-a059-d9a470a521dd.png)

### Steps to Reproduce

1.  Create a new blank Maui app
2.  Add and Entry View and name it entryTest
3.  Add 2 Buttons and set Text to "Set Focus" and "Set Unfocus"
4.  In the Code behind for the 1st button add code entryTest.Focus()
5. In the Code behind for the 2nd button add code enryTest.Unfocus()
6.  Run the App
7.  Click the Set Focus button.
8.  Notice the Entry field cursor blinks
9.  Notice the keyboard does not pop up
10.  Tap the Entry field.
11.  Notice the keyboard pops up.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Workaround

I added a mapper [here](https://github.com/PureWeen/ShanedlerSamples/blob/main/ShanedlerSamples/Library/Workarounds/EntryWorkarounds.Android.cs) that you can copy to add this behavior for android. 

One thing to note is that if your intention is to open the keyboard you should use
KeyboardManager.ShowKeyboard not `Focus`

Using `Focus` to influence the `Keyboard` has always felt like a hack to me in general.

**Comment by SailDev** [comment]
Still not working in GA.
Is there a method, to show/hide the ENTRY keyboard manually?

**Comment by tataelm** [comment]
I've encountered the same problem. But when I use "Entry" inside Grid instead of StackLayout, it works just fine. Entry and StackLayout don't get along yet.

**Comment by marcoablanco** [comment]
> Still not working in GA. Is there a method, to show/hide the ENTRY keyboard manually?


I've encountered a different problem. Keyboard is not hiding when unfocus entry. I made a wordaround in handler:

```C#
protected override void ConnectHandler(AppCompatEditText platformView)
{
	base.ConnectHandler(platformView);

	if (VirtualView is Entry entryControl)
		entryControl.ObserveUnfocused().Subscribe(UnfocusedSubscription);
}

private void UnfocusedSubscription(FocusEventArgs args)
{
	if (!args.IsFocused)
	{
		InputMethodManager inputMethodManager = (InputMethodManager)global::Android.App.Application.Context.GetSystemService(global::Android.Content.Context.InputMethodService);
		inputMethodManager.HideSoftInputFromWindow(PlatformView.WindowToken, HideSoftInputFlags.None);
	}
}
```
I use own observable method, but you can use events.

**Comment by SailDev** [comment]
Many thanks marcoablanco.
That looks interesting and a real benefit, compared to XF Forms. It seems, that i should investigate some time, understanding the handler architecture in Maui.

**Comment by SokoFromNZ** [comment]
> > Still not working in GA. Is there a method, to show/hide the ENTRY keyboard manually?
> 
> I've encountered a different problem. Keyboard is not hiding when unfocus entry. I made a wordaround in handler:
> 
> ```cs
> protected override void ConnectHandler(AppCompatEditText platformView)
> {
> 	base.ConnectHandler(platformView);
> 
> 	if (VirtualView is Entry entryControl)
> 		entryControl.ObserveUnfocused().Subscribe(UnfocusedSubscription);
> }
> 
> private void UnfocusedSubscription(FocusEventArgs args)
> {
> 	if (!args.IsFocused)
> 	{
> 		InputMethodManager inputMethodManager = (InputMethodManager)global::Android.App.Application.Context.GetSystemService(global::Android.Content.Context.InputMethodService);
> 		inputMethodManager.HideSoftInputFromWindow(PlatformView.WindowToken, HideSoftInputFlags.None);
> 	}
> }
> ```
> 
> I use own observable method, but you can use events.

Can you give me more context how to use this in a sample app. I cannot figure out where I put these code of yours...
thanks

**Comment by marcoablanco** [comment]
> > > Still not working in GA. Is there a method, to show/hide the ENTRY keyboard manually?
> > 
> > 
> > I've encountered a different problem. Keyboard is not hiding when unfocus entry. I made a wordaround in handler:
> > ```cs
> > protected override void ConnectHandler(AppCompatEditText platformView)
> > {
> > 	base.ConnectHandler(platformView);
> > 
> > 	if (VirtualView is Entry entryControl)
> > 		entryControl.ObserveUnfocused().Subscribe(UnfocusedSubscription);
> > }
> > 
> > private void UnfocusedSubscription(FocusEventArgs args)
> > {
> > 	if (!args.IsFocused)
> > 	{
> > 		InputMethodManager inputMethodManager = (InputMethodManager)global::Android.App.Application.Context.GetSystemService(global::Android.Content.Context.InputMethodService);
> > 		inputMethodManager.HideSoftInputFromWindow(PlatformView.WindowToken, HideSoftInputFlags.None);
> > 	}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I use own observable method, but you can use events.
> 
> Can you give me more context how to use this in a sample app. I cannot figure out where I put these code of yours... I've found https://github.com/davidortinau/CustomRendererSample example. But this does not work with the current MAUI version (I get a cast exception when I start the example as is). thanks

I created a EntryHandler for Maui Entry control in Android folder. You can see more about Handler in https://docs.microsoft.com/dotnet/maui/user-interface/handlers/customize

**Comment by RonnyRos** [comment]
Adding      <Entry Text="HELLO" Focused="Entry_Focused" Unfocused="Entry_Unfocused" /> and running it on a Android OS never triggers Entry Unfocused, with a standard maui template when tapping outside the entrybox.
Also the custom handlers does not fire tapping outside the entry box as it should (Atleast in Xamarin Forms it did).

**Comment by RonnyRos** [comment]
[Defocus_issue.zip](https://github.com/dotnet/maui/files/9364048/Defocus_issue.zip)
Added a sample

**Comment by marcoablanco** [comment]
> [Defocus_issue.zip](https://github.com/dotnet/maui/files/9364048/Defocus_issue.zip) Added a sample
Your handler is not registered. I added to MauiProgram and works.
```C
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
#if ANDROID
			.ConfigureMauiHandlers(handlers => handlers.AddHandler<Microsoft.Maui.Controls.Entry, Survey.Handlers.EntryHandler>())
#endif
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

		return builder.Build();
```

I changed a little bit your handler
```C#
public partial class EntryHandler : Microsoft.Maui.Handlers.EntryHandler
{
	protected override void ConnectHandler(AppCompatEditText platformView)
	{
		base.ConnectHandler(platformView);
		platformView.FocusChange += PlatformView_FocusChange;
	}

	protected override void DisconnectHandler(AppCompatEditText platformView)
	{
		base.DisconnectHandler(platformView);
		platformView.FocusChange -= PlatformView_FocusChange;
	}

	private void PlatformView_FocusChange(object sender, Android.Views.View.FocusChangeEventArgs args)
	{
		if (args.HasFocus)
		{
			InputMethodManager inputMethodManager = (InputMethodManager)global::Android.App.Application.Context.GetSystemService(global::Android.Content.Context.InputMethodService);
			inputMethodManager.ShowSoftInput(PlatformView, ShowFlags.Forced);
		}
		else
		{
			InputMethodManager inputMethodManager = (InputMethodManager)global::Android.App.Application.Context.GetSystemService(global::Android.Content.Context.InputMethodService);
			inputMethodManager.HideSoftInputFromWindow(PlatformView.WindowToken, HideSoftInputFlags.None);
		}
	}
}

```

**Comment by RonnyRos** [comment]
Thank you for tweaking the sample, looks much better!

Im still struggling to make the sample work, it does not lose focus and i think i have misunderstood a platform behavior about textboxes/entries.
Meaning, when you have a entry and you click outside the entry or click a button, shouldnt the entry lose focus and stop blinking?

**Comment by RonnyRos** [comment]
Use this to have the old XF tap outside of the entry.
    
    public override bool DispatchTouchEvent(MotionEvent ev)
    {
        if (ev.Action == MotionEventActions.Up)
        {
            var v = Window.CurrentFocus;

            if (v is EditText)
            {
                Rect outRect = new Rect();
                v.GetGlobalVisibleRect(outRect);

                if (!outRect.Contains(new Rect(ev.RawX, ev.RawY, 1, 1)))
                {
                    v.ClearFocus();
                    InputMethodManager imm = (InputMethodManager)GetSystemService(Context.InputMethodService);
                    imm.HideSoftInputFromWindow(v.WindowToken, 0);
                }
            }
        }
        return base.DispatchTouchEvent(ev);
    }

**Comment by Samirgc** [comment]
Surprised to see it's still not working till today.

**Comment by FreakyAli** [comment]
This definitely needs a fix

**Comment by patrickklaeren** [comment]
> I've encountered the same problem. But when I use "Entry" inside Grid instead of StackLayout, it works just fine. Entry and StackLayout don't get along yet.

Changing my stack layout for a grid doesn't work, when invoking `Focus()` the software keyboard does not show. This is still a bug.

**Comment by Samirgc** [comment]
Quick Solution : Make Entry , Editor or Any thirdparty controls  IsEnabled = false then Entry.UnFocus() to hide the key board and Again forget to make IsEnabled property to true as soon as the task is completed. :)

**Comment by philipag** [comment]
This same bug report appears to apply to the Editor control as well.

**Comment by nesho84** [comment]
> Quick Solution : Make Entry , Editor or Any thirdparty controls IsEnabled = false then Entry.UnFocus() to hide the key board and Again don't forget to make IsEnabled property to true as soon as the task is completed. :)

The only optiion that works for me. Thank you ;)

**Comment by maexsp** [comment]
The problem that the Sofkeyboard does not close automatically once touched somewhere outside of the keyboard, is caused by the fact that the Android ViewGroup does not clear the focus anymore in MAUI. In XF the ViewGroup always cleared the focus correctly on touch events. In MAUI it seem it was forgotten to be implemented? XF: https://github.com/xamarin/Xamarin.Forms/blob/a31ddcfe18a0490f7e0fccccfc6e879c2f309485/Xamarin.Forms.Platform.Android/PlatformRenderer.cs#L68

**Comment by PureWeen** [comment]
Here's some code you can use to interact with the keyboard for the time being

https://github.com/PureWeen/ShanedlerSamples/tree/main/ShanedlerSamples/Keyboard

If you call "ShowKeyboard" there's no need to call "Focus" when using this code.

**Comment by iberosmen** [comment]
to this day it still doesn't work

**Comment by RonnyRos** [comment]
Does not seem to fire        public bool OnSingleTapUp(MotionEvent e) if you remove the scrollview from the sample.

**Comment by relecon** [comment]
Try adding this code to the Focused event of the Entry. Resolved the issue of the keyboard not showing up in my MAUI app when running on Surface Pro 9.
`CoreInputView.GetForCurrentView().TryShow(CoreInputViewKind.Keyboard);`

Found from [https://stackoverflow.com/questions/39618127/programmatically-open-on-screen-keyboard-in-uwp](https://stackoverflow.com/questions/39618127/programmatically-open-on-screen-keyboard-in-uwp)

**Comment by nickidentivue** [comment]
> Try adding this code to the Focused event of the Entry. Resolved the issue of the keyboard not showing up in my MAUI app when running on Surface Pro 9. `CoreInputView.GetForCurrentView().TryShow(CoreInputViewKind.Keyboard);`
> 
> Found from https://stackoverflow.com/questions/39618127/programmatically-open-on-screen-keyboard-in-uwp

I can confirm this works when called from Windows platform code, I came across the same link as @relecon and chanced my arm. Added a more detailed explanation here:

(https://github.com/microsoft/microsoft-ui-xaml/issues/6291?fbclid=IwAR0qlccdWand42VzTFhUhleJuv_t-jaTkO1igI3B1rrvUh0k6cgXIpHDW9g#issuecomment-1378649391)

**Comment by PureWeen** [comment]
I added a mapper [here](https://github.com/PureWeen/ShanedlerSamples/blob/main/ShanedlerSamples/Library/Workarounds/EntryWorkarounds.Android.cs) that you can copy to add this behavior for android.

**Comment by Symbai** [comment]
> Here's some code you can use to interact with the keyboard for the

The link no longer works. Also is there a workaround for iOS?

> One thing to note is that if your intention is to open the keyboard you should use
> KeyboardManager.ShowKeyboard not `Focus`

There is no `KeyboardManager` class for me. Where does it come from?

**Comment by Sourcephy** [comment]
Try this solution

`private async void OnShowKeyboardTapped(object sender, EventArgs e)
{
       EntryInput.Focus();
       await Task.Delay(100); // Important to add delay here
       Helpers.KeyboardVisibility(true);
}

private async void OnHideKeyboardTapped(object sender, EventArgs e)
{
       Helpers.KeyboardVisibility(false);
}

private void KeyboardVisibility(bool StateFocus)
{
#if ANDROID
        if (Platform.CurrentActivity.CurrentFocus != null)
        {
            if (StateFocus)
            {
                Platform.CurrentActivity.ShowKeyboard(Platform.CurrentActivity.CurrentFocus);
            }
            else
            {
                Platform.CurrentActivity.HideKeyboard(Platform.CurrentActivity.CurrentFocus);
                Platform.CurrentActivity.CurrentFocus.ClearFocus();
            }
        }
#endif
}
`
