### ISSUE TITLE
Editor Size does not change on iOS

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5990]
### Description

The ` AutoSize = EditorAutoSizeOption.TextChanges` does not work on iOS. The size remain the same although the text move to the new line. 

### Steps to Reproduce

Run the repro project and continue to write the text in the editor until the line changes. The line change but the editor size remain the same. 
[BorderSample.zip](https://github.com/dotnet/maui/files/8469729/BorderSample.zip)

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/3425 duplicate
