### ISSUE TITLE
Editor AutoSize on Text Change Surpass the border around it

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#5991]
### Description

Set the `AutoSize = EditorAutoSizeOption.TextChanges` on Editor . Put the Editor inside the border. Now When Editor grows with text change the border around it does not grow with it. Tested on Android. Unable to test on iOS due to this [bug](https://github.com/dotnet/maui/issues/5990)

### Steps to Reproduce

Run the repro project and continue to write in the editor.
[BorderSample.zip](https://github.com/dotnet/maui/files/8469807/BorderSample.zip)
 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by samhouts** [comment]
No longer reproducible on main (6.0.300-rc.4.5681)
