### ISSUE TITLE
Include an option to add a menu item separator. Sometimes menu items need to be logically grouped.

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#5999]
### Description

Include an option to add a menu item separator. Sometimes menu items need to be logically grouped according to their function.

### Public API Changes

Similar to `MenuFlyoutItem` and `MenuFlyoutSubItem`, this can be defined as `MenuFlyoutSeparatorItem` and it can be defined to denote where exactly this needs to be logically grouped.

```xaml
<MenuFlyoutItem Text="New" />
<MenuFlyoutItem Text="Open" />
<MenuFlyoutSeparatorItem />
<MenuFlyoutItem Text="Print" />
<MenuFlyoutSeparatorItem />
<MenuFlyoutItem Text="Exit" />
```

### Intended Use-Case

This adds a horizontal separator line to denote the logical grouping.

**Comment by Eilon** [comment]
And my prototype works on Windows. Need to do MacCatalyst now.

**Comment by Eilon** [comment]
Here's what it looks like on Windows:

<img width="555" alt="screenshot of a Windows menu with a separator between two of the items" src="https://user-images.githubusercontent.com/202643/177619345-00aa2c7b-5a7c-460d-bfcc-b597a52b1cc0.png">

(It's a bit hard to see, but there's definitely a little separator between the _cool_ menu items.

**Comment by Eilon** [comment]
MacCatalyst looking alright now:

![image](https://user-images.githubusercontent.com/202643/177833997-a625c139-c2aa-488e-ab3c-009aaa907792.png)

**Comment by Eilon** [comment]
PR is here: https://github.com/dotnet/maui/pull/8565
