### ISSUE TITLE
Documentation - add advanced sample for every control and also screenshots for this sample

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6011]
### Description

This platform is awesome and it needs much more visual samples in the documentation not only for the main controls but for all controls.
Also, some official videos - like 5 minutes about every of the 40 controls would be awesome.
DevExpress does this very well with their documentation, you should learn from them. For Windows Forms controls, especially.
Not just basic sample but also some advanced using all features of the control and put into context of a real-world app with some tips and tricks and all visible from a screenshot and code on the docs page for quick learning. This might increase the spread of MAUI significantly.
Images are very fast showoff for people browsing the docs. And GIFs and videos and all!

What is great about the docs is that there is always C# equivalent code. That is very welcome to see! It helps understanding XAML constructs how they work behind the scenes.

### Public API Changes

none

### Intended Use-Case

new MAUI learners quick learn

**Comment by jfversluis** [comment]
This issue was moved to dotnet/docs-maui#1238
