### ISSUE TITLE
SwipeView custom items are not rendering

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6018]
### Description

_Visual Studio Version 17.2.0 Preview 3.0_

https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/swipeview#custom-swipe-items
This documentation samples shows custom content in the swipable side-menu. 
Normal item is` <SwipeItem>`
Custom item is `<SwipeItemView>`

Anything that I put into `<SwipeItemView>` is not rendered.

Expected behavior: `<SwipeItemView>` content is rendered

_**Please fix the problem as soon as possible. I thought I could finally ship test apps to our clients when the RC 1 blog post says cross-platform development ready but this whole feature is missing.**_

### Steps to Reproduce

New MAUI app from template with some quick SwipeView tests in MainPage.
[MauiApp1.zip](https://github.com/dotnet/maui/files/8476860/MauiApp1.zip)

Run on Sony Xperia 5 Android 11 API 30

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (API 30)

### Did you find any workaround?

no

**Comment by kristinx0211** [comment]
verified repro on Android 11 and the above project.

**Comment by kristinx0211** [comment]
repro on android with vs 17.3.0 Preview 2.0 [32506.368.main].

**Comment by janseris** [comment]
@jsuarezruiz Hi, any updates, please?

**Comment by danielftz** [comment]
Issue persists in Service Release 3

**Comment by janseris** [comment]
@samhouts @jsuarezruiz Hi please when is this expected to be fixed? Without SwipeView functioning properly and without context menu (not present in MAUI) how am I supposed to show options on a record in a collectionview or on anything else?

**Comment by chrisparkeronline** [comment]
Having this same issue. Glad I found this is a known issue. I hope it is fixed soon.

**Comment by decv86** [comment]
basic things do not work - why such a Maui?

**Comment by decv86** [comment]
strongly ... how about stopping work on MAUI and returning to supporting xamarin forms? lots of bugs and obscure updates - elementary projects just don't work...

**Comment by jsuarezruiz** [comment]
Reviewing the issue, the size (width) of the SwipeViewItem is zero.
After applying the changes https://github.com/dotnet/maui/commit/fd18215db17bee3fb60a0fa3efb4f8ddbb9bf24d

The situation improves slightly but the width is still zero.

![image](https://user-images.githubusercontent.com/6755973/185587327-5e4362a8-a772-4f7a-a8df-2605e2134c88.png)
![image](https://user-images.githubusercontent.com/6755973/185587364-01eac901-3aca-4f97-8e18-b6384b4914b5.png)

Debugging the code, noticed that:
![image](https://user-images.githubusercontent.com/6755973/185587443-26973f2a-24fe-4ab4-8db5-dcf213fd298c.png)
In the ComputeFrame method, DesiredSize is null but the bounds Rect is {0,0,100,80} so the width is 100.
