### ISSUE TITLE
Visual State Manager Ignored in CollectionView

### ISSUE THREAD

**Issue by cbaer-extron** [dotnet/maui#6019]
### Description

When using Visual State Manager to change the background color, the state change is ignored inside of a Collection View.  As compared to Xamarin.Forms where the state change is handled.  (See both videos to compare)

In Maui:

https://user-images.githubusercontent.com/101732760/163045385-415e9971-2027-49c9-a97a-596ec1347cde.mp4

In Xamarin.Forms:

https://user-images.githubusercontent.com/101732760/163045446-9efeb701-5fd2-4bd6-8381-65a84ac70ad7.mp4

Xaml:
https://github.com/cbradbaer/BugReports/blob/main/StackLayoutIsEnabled/DisableTestPage.xaml

Code Behind:

https://github.com/cbradbaer/BugReports/blob/main/StackLayoutIsEnabled/DisableTestPage.xaml.cs

NOTE:  This code was used for another bug report.  Code-behind is not meaningful for this bug report.

### Steps to Reproduce

1.  Create new Maui app
2.  Use the attached files to add the test page to the app
3.  Run the program
4.  Click on the edit fields and note the color change
5.  Click on the rows of the Collection View and note the color does not change

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32409.46.main]. Repro on Android. Sample Project: [MauiApp13.zip](https://github.com/dotnet/maui/files/8477953/MauiApp13.zip)

**Comment by cbaer-extron** [comment]
Tested with RC2 and Visual State Manager is working in CollectionView now.  😁
