### ISSUE TITLE
Maui should default PublishReadyToRun true on Windows Release

### ISSUE THREAD

**Issue by eerhardt** [dotnet/maui#6025]
### Description

When I create a WinUI app, the WinUI template defaults:

```
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
```

In the `PublishProfiles\*.pubxml` files. This means when I build/publish for Release, I get an app that contains pre-compiled native code. This results in a larger app, but one that loads faster. Even in a `dotnet new maui` app, I can visually tell that when I set `PublishReadyToRun=true`, the app loads faster.

### Public API Changes

None

### Intended Use-Case

Users want their installed Maui apps to load faster.

cc @mattleibow

**Comment by mattleibow** [comment]
Is this something that we can just enable by default in the Maui targets and it just works?

**Comment by eerhardt** [comment]
Correct. PublishReadyToRun has been supported in .NET for a few releases now. The only downside that I know of is that it makes your apps larger.

**Comment by mattleibow** [comment]
This was implemented as the default in .NET 7!
