### ISSUE TITLE
[RC1] Label MaxLines doesn't work

### ISSUE THREAD

**Issue by ram16g** [dotnet/maui#6030]
### Description

When set LineBreakMode，MaxLines doesn't work, it always show one line

### Steps to Reproduce

`<Label 
                Text="Welcome to .NET Multi-platform App UI Welcome to .NET Multi-platform App UI ET Multi-platform App UI ET Multi-platform App UI ET Multi-platform App UI ET Multi-platform App UI Welcome to .NET Multi-platform App UI Welcome to .NET Multi-platform App UI Welcome to .NET Multi-platform App UI Welcome to .NET Multi-platform App UI"
                SemanticProperties.HeadingLevel="Level1"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                MaxLines="3"
                LineBreakMode="TailTruncation"
                FontSize="18"
                HorizontalOptions="Center" />`

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

ANDROID 10

### Did you find any workaround?

no

### Relevant log output

```shell
NO
```

**Comment by hartez** [comment]
@ram16g Are you seeing this on Android, or on a different platform? On Android, TailTruncation (and the other truncation options) does not support multiple lines. 

To be clear - the Android platform _does_ support TailTruncation (TextUtils.TruncateAt.END) with multiple lines; for backward compatibility reasons, MAUI.Controls _does not_ support combining multiple lines with TailTruncation. However, it's possible to customize the mapping behavior to support that combination. I'll try to post a demo of how to do that tomorrow.

**Comment by kristinx0211** [comment]
verified exist on Android 11. show one line.
![image](https://user-images.githubusercontent.com/99457000/163178617-8554e586-8889-47e0-91bd-1c34d8a9b8f5.png)

**Comment by hartez** [comment]
Example of how to customize your app to support multiple line Labels with TailTruncation: https://github.com/hartez/MultilineTruncate

**Comment by kasimier-vireq** [comment]
@hartez : In the example we read "This is a backward-compatibility carryover from Xamarin.Forms" and "However, Android does support some truncation modes ("Ellipsize", on Android) for multiple lines, and TailTruncation (TextUtils.TruncateAt.End on Android) is one of them".

Wouldn't it be better to provide an opt-in for backwards Xamarin.Forms compatibility instead?
If MAUI wants to be a fresh start, then why carry over bugs from Xamarin.Forms?

**Comment by hartez** [comment]
> Wouldn't it be better to provide an opt-in for backwards Xamarin.Forms compatibility instead?
> If MAUI wants to be a fresh start, then why carry over bugs from Xamarin.Forms?

Because we don't want to prevent current Forms users from easily moving to MAUI.Controls.

Long term, we intend to update how MAUI.Core handles text wrapping, truncation, and multiple lines - see #5835. And once that happens, users will have an option to get the new behavior or keep the old one.
