### ISSUE TITLE
[Bug] LayoutOptions Expand not work in HorizontalStackLayout and VerticalStackLayout

### ISSUE THREAD

**Issue by pierrebrito** [dotnet/maui#6031]
### Description

Code:
![image](https://user-images.githubusercontent.com/6466875/163095936-8c620c2e-eb64-4b68-9ad6-39595a8f0fe5.png)

App Android:
![Screenshot_1649821425](https://user-images.githubusercontent.com/6466875/163095967-b730adc9-c46f-41e6-9519-83fee3909ecc.png)

### Steps to Reproduce

    <StackLayout Spacing="16"
                 BackgroundColor="Aqua">
        <StackLayout Orientation="Horizontal">
            <Label Text="Label 1" BackgroundColor="Red" />

            <Label Text="Label 2" BackgroundColor="Blue" HorizontalOptions="FillAndExpand" />

            <Label Text="Label 3" BackgroundColor="Green" />
        </StackLayout>

        <HorizontalStackLayout>
            <Label Text="Label 1" BackgroundColor="Red" />

            <Label Text="Label 2" BackgroundColor="Blue" HorizontalOptions="FillAndExpand" />

            <Label Text="Label 3" BackgroundColor="Green" />
        </HorizontalStackLayout>

        <StackLayout Orientation="Vertical"
                     HeightRequest="100">
            <Label Text="Label 1" BackgroundColor="Red" />

            <Label Text="Label 2" BackgroundColor="Blue" VerticalOptions="FillAndExpand" />

            <Label Text="Label 3" BackgroundColor="Green" />
        </StackLayout>

        <VerticalStackLayout HeightRequest="100">
            <Label Text="Label 1" BackgroundColor="Red" />

            <Label Text="Label 2" BackgroundColor="Blue" VerticalOptions="FillAndExpand" />

            <Label Text="Label 3" BackgroundColor="Green" />
        </VerticalStackLayout>
    </StackLayout>

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by hartez** [comment]
The "AndExpand" options are deprecated, and are not supported in the new HorizontalStackLayout and VerticalStackLayout. They are only supported in StackLayout (to provide an easy upgrade path from Xamarin.Forms).

**Comment by pierrebrito** [comment]
@hartez Is there any alternative to this feature?

**Comment by kristinx0211** [comment]
repro on Android 11 with 17.3.0 Preview 1.0 [32411.352.main].

**Comment by hartez** [comment]
> @hartez Is there any alternative to this feature?

You can achieve the same layout with a Grid. Or continue to use StackLayout; it still supports the "AndExpand" options. 

Or if this is a layout structure you commonly use in your applications, you might consider creating a custom layout you can reuse - examples [here](https://github.com/hartez/CustomLayoutExamples#single-column-layout) and [here](https://github.com/hartez/CustomLayoutExamples#custom-single-column-pre-made-layouts).
