### ISSUE TITLE
View is overflowing when view parent has padding.

### ISSUE THREAD

**Issue by pierrebrito** [dotnet/maui#6032]
### Description

Code:
![image](https://user-images.githubusercontent.com/6466875/163099534-365391ed-9c83-4d4b-88fd-aa99531fd847.png)

App Android:
![image](https://user-images.githubusercontent.com/6466875/163100343-47dc285c-3af0-42b7-aeed-90ef32f1ce9c.png)

### Steps to Reproduce

    <StackLayout Spacing="16"
                 Padding="24"
                 BackgroundColor="Aqua">
        <Grid ColumnDefinitions="Auto,*,Auto">

            <Label x:Name="icon"
                   Text="Label 1"
                   VerticalTextAlignment="Center"
                   Grid.Column="0"
                   BackgroundColor="Red" />

            <Label Text="Label 2"
                   VerticalTextAlignment="Center"
                   BackgroundColor="Blue"
                   Grid.Column="1" />

            <Label Text="Label 2"
                   VerticalTextAlignment="Center"
                   Grid.Column="2"
                   BackgroundColor="Green" />
        </Grid>

        <StackLayout Orientation="Horizontal">
            <Label Text="Label 1"
                   BackgroundColor="Red" />

            <Label Text="Label 2"
                   BackgroundColor="Blue"
                   HorizontalOptions="FillAndExpand" />

            <Label Text="Label 3"
                   BackgroundColor="Green" />
        </StackLayout>
    </StackLayout>

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32409.46.main]. Repro on Android. Sample Project: [6032.zip](https://github.com/dotnet/maui/files/8478194/6032.zip)
