### ISSUE TITLE
Debugging is harder than it need be

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#6034]
### Description

Some failures produce hard to diagnose errors popping up a Warning dialog that says:
`A debugger is attached to <app name> but not configured to debug this unhandled exception. To debug this exception, detach the current debugger.
`
The answer to this might be as simple as a configuration change in my Visual Studio instance, if so, just tell me, if not, read on...

### Steps to Reproduce

1. Unzip the project from [MAUIToolBar-crash.zip](https://github.com/dotnet/maui/files/8478362/MAUIToolBar-crash.zip)
2. Compile and run it on Windows, you should see this:
![MAUIToolBar-crash](https://user-images.githubusercontent.com/12423046/163105872-70e2835a-2893-4c48-a457-507458573598.jpg)
 
The actual underlying bug is simple, a call on `Shell.Current.GoToAsync("//FirstPage")` but AppShell.xaml contains this:
```
    <TabBar>
        <ShellContent Title="Starting Page" ContentTemplate="{DataTemplate local:StartupPage}"/>
    </TabBar>
    <!--<ShellContent Route="FirstPage" Title="A Page instance" ContentTemplate="{DataTemplate local:MainPage}"/>-->
    <ShellContent Title="Another instance" ContentTemplate="{DataTemplate local:MainPage}"/>
```
So the ShellContent item with a route of "FirstPage" isn't included, thus GoToAsync fails. In this case I'd have expected a .NET exception to be thrown.

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

1. Unzip the project from [MAUIToolBar-crash.zip](https://github.com/dotnet/maui/files/8478362/MAUIToolBar-crash.zip)
2. Compile and run it on Windows, you should see this:
![MAUIToolBar-crash](https://user-images.githubusercontent.com/12423046/163105872-70e2835a-2893-4c48-a457-507458573598.jpg)
 
The actual underlying bug is simple, a call on `Shell.Current.GoToAsync("//FirstPage")` but AppShell.xaml contains this:
```
    <TabBar>
        <ShellContent Title="Starting Page" ContentTemplate="{DataTemplate local:StartupPage}"/>
    </TabBar>
    <!--<ShellContent Route="FirstPage" Title="A Page instance" ContentTemplate="{DataTemplate local:MainPage}"/>-->
    <ShellContent Title="Another instance" ContentTemplate="{DataTemplate local:MainPage}"/>
```
So the ShellContent item with a route of "//FirstPage" isn't included, thus GoToAsync fails. In this case I'd have expected a .NET exception to be thrown. This has the same symptom as #5951 but I have no idea if it's the same underlying problem.

### Relevant log output

```shell
No
```

**Comment by jfversluis** [comment]
Hi there, thanks for the report!

It seems that this might be a local configuration thing for you, running the exact same project on the latest public version of VS2022 gives me the exact error message as you would expect

![image](https://user-images.githubusercontent.com/939291/163345521-d9a4c847-dc62-42d2-ab38-9bfaa0fb9bb6.png)

Go to Debug > Windows > Exception Settings and see if you might need to tweak something there.

**Comment by david-maw** [comment]
Yep, that was it, thanks @jfversluis. The exception had been turned off in the exception settings, I re-enabled it and now the program fails with the exception message I expected. Hopefully now I can go back to my real bug and find out what the $%#@#$ I did to trigger it!
