### ISSUE TITLE
Windows content page(C#) cannot be hot reloaded

### ISSUE THREAD

**Issue by git-xiaocao** [dotnet/maui#6035]
### Description

hotreload is invalid.
![image](https://user-images.githubusercontent.com/76673990/163110424-a15f6d82-08fa-4a8f-9888-4c46eb831303.png)

### Steps to Reproduce

1. Create a content page(C#)
![image](https://user-images.githubusercontent.com/76673990/163110221-333b44af-a30f-4e56-b1fa-e669f918107f.png)
2. Run MAUI APP
3. Change source code
4. Hot reload

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

**Comment by kristinx0211** [comment]
verified repro on windows using vs 17.3.0 Preview 1.0 [32411.352.main].

**Comment by xiao-cao-x** [comment]
Please deal with this problem as soon as possible, otherwise it will affect the development.

**Comment by xiao-cao-x** [comment]
This problem also exists on the latest version (RC1).
![image](https://user-images.githubusercontent.com/76673990/163300924-8cbd31b9-a6a2-41e3-9638-554611009c4f.png)

**Comment by freever** [comment]
@git-xiaocao @kristinx0211 There is a way to get it working:
https://dev.to/davidortinau/c-ui-and-net-hot-reload-a-match-made-in-net-maui-243f
