### ISSUE TITLE
ApplicationDisplayVersion problem ITMS-90062 error

### ISSUE THREAD

**Issue by RaspeR87** [dotnet/maui#6037]
### Description

If you want to change default value for "ApplicationDisplayVersion" in our MAUI csproj file from "1.0" to something else, you are getting error like: 

`Unable to read project information for project XYZ: Sequence contains more than one element`

So you cannot change it to something else. And then you have a problem if you want to update existing MAUI app in Apple App Store via Transporter app. You get error:

`ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [1.0] in the Info.plist file must contain a higher version than that of the previously approved version [10].`

### Steps to Reproduce

1. Create new .NET MAUI App
2. Open csproj file
3. Update `<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>` to for example `<ApplicationDisplayVersion>1.5</ApplicationDisplayVersion>`
4. Build solution

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by tbolon** [comment]
Seems to be related to #3690 and #6040

**Comment by kristinx0211** [comment]
Error NETSDK1005 after changes in .csproj file. 
![image](https://user-images.githubusercontent.com/99457000/163132861-60378435-71b7-4279-b02b-bef53ac5419d.png)

**Comment by RaspeR87** [comment]
@kristinx0211 Same for me

**Comment by Eilon** [comment]
Seems related:
* https://github.com/dotnet/maui/issues/3690
* https://github.com/dotnet/maui/issues/6040

**Comment by RaspeR87** [comment]
Now with latest Visual Studio 2022 17.2.0 Preview 4 this works well.

Great works and tnx for all team! (y)
