### ISSUE TITLE
Install MAUI RC1 workloads fails on Mac

### ISSUE THREAD

**Issue by MaherJendoubi** [dotnet/maui#6038]
### Description

I would like to install the .NET MAUI RC1 workloads on M1 Mac.

I use the following version of dotnet :

dotnet --version
6.0.202

I got the following error :

La ou les charges de travail 'maui' sont déjà installées.
Échec de la mise à jour du manifeste de publicité microsoft.net.workload.emscripten : microsoft.net.workload.emscripten.manifest-6.0.200 est introuvable dans les flux NuGet https://aka.ms/dotnet6/nuget/index.json..
Ignorer la validation de signature de package NuGet. La validation de signature NuGet n’est pas disponible sur Linux ou macOS https://aka.ms/workloadskippackagevalidation.
microsoft.net.sdk.android manifeste de publicité mis à jour.
microsoft.net.sdk.maui manifeste de publicité mis à jour.
microsoft.net.sdk.maccatalyst manifeste de publicité mis à jour.
microsoft.net.sdk.ios manifeste de publicité mis à jour.
microsoft.net.sdk.macos manifeste de publicité mis à jour.
microsoft.net.sdk.tvos manifeste de publicité mis à jour.
microsoft.net.workload.mono.toolchain manifeste de publicité mis à jour.
Installation du microsoft.net.sdk.android de la charge de travail du manifeste 32.0.300-rc.1.4...
Échec de l’installation de la charge de travail, restauration des packs installés...
Installation du microsoft.net.sdk.android de la charge de travail du manifeste 31.0.200-preview.14.106...
Échec de la restauration de l'installation : Impossible d'installer la microsoft.net.sdk.android version de manifeste 31.0.200-preview.14.106: The transaction has aborted.
Échec de l’installation de la charge de travail : Impossible d'installer la microsoft.net.sdk.android version de manifeste 32.0.300-rc.1.4: microsoft.net.sdk.android.manifest-6.0.200::32.0.300-rc.1.4 est introuvable dans les flux NuGet https://aka.ms/dotnet6/nuget/index.json.

### Steps to Reproduce

1. Open a Terminal
2. sudo dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/rc.1.json --source https://aka.ms/dotnet6/nuget/index.json

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 14

### Affected platforms

macOS

### Affected platform versions

N/A

**Comment by cfierro-glb** [comment]
I'm also not able to install maui workloads following the wiki page install instructions. Upon further investigation, I found out:
1. The first install option does not install rc1, but preview-14
2. The alternate nuget feed in the second option seems to have many broken resources, after inspecting the index.json. This is why, although the rollback file is fine, packages are not found on the alternate source.

My question is, shouldn't the rc1 be available on the public (standard) nuget feed? I think `sudo dotnet workload install maui` should install rc1 instead of preview14

**Comment by cfierro-glb** [comment]
I just solved the issue. The key is that you need to install both the latest dotnet 6.0.4 (sdk 6.0.202), and sdk 6.0.3xx (second requirement from [the dev guide](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md)). Then, the second install option from the [wiki](https://github.com/dotnet/maui/wiki/macOS-Install) will be successful.

The mac sample runs OK on my m1 mac, but now gotta figure out how to be able to build using omnisharp and vscode

**Comment by MaherJendoubi** [comment]
Thank you @cfierro-glb, I have 2 questions: what was your message error? and where I could find the SDK 6.0.3xx?

**Comment by MaherJendoubi** [comment]
@cfierro-glb Thanks. I am testing.

**Comment by MaherJendoubi** [comment]
I got a new error : 

Échec de la mise à jour du manifeste de publicité microsoft.net.workload.emscripten : microsoft.net.workload.emscripten.manifest-6.0.300 est introuvable dans les flux NuGet https://aka.ms/dotnet6/nuget/index.json..
Échec de la mise à jour du manifeste de publicité microsoft.net.workload.mono.toolchain : microsoft.net.workload.mono.toolchain.manifest-6.0.300 est introuvable dans les flux NuGet https://aka.ms/dotnet6/nuget/index.json..
Skipping NuGet package signature verification.
Installation du microsoft.net.sdk.android de la charge de travail du manifeste 32.0.300-rc.1.4...
Installation du microsoft.net.sdk.ios de la charge de travail du manifeste 15.4.100-rc.1.125...
Installation du microsoft.net.sdk.maccatalyst de la charge de travail du manifeste 15.4.100-rc.1.125...
Installation du microsoft.net.sdk.macos de la charge de travail du manifeste 12.3.100-rc.1.125...
Installation du microsoft.net.sdk.maui de la charge de travail du manifeste 6.0.300-rc.1.5355...
Installation du microsoft.net.sdk.tvos de la charge de travail du manifeste 15.4.100-rc.1.125...
Installation du microsoft.net.workload.mono.toolchain de la charge de travail du manifeste 6.0.4...
Échec de l’installation de la charge de travail, restauration des packs installés...
Échec de l’installation de la charge de travail : Impossible d'installer la microsoft.net.workload.mono.toolchain version de manifeste 6.0.4: microsoft.net.workload.mono.toolchain.manifest-6.0.300::6.0.4 est introuvable dans les flux NuGet https://aka.ms/dotnet6/nuget/index.json.

**Comment by MaherJendoubi** [comment]
My bad, it works now. Thanks @cfierro-glb for your great help.
