### ISSUE TITLE
[RC1] - iOS FontImageSource in AppShell TabBar Pixelation

### ISSUE THREAD

**Issue by RichardMarsh** [dotnet/maui#6043]
### Description

When using FontImageSource as the Icon source in the TabBar, the resulting icons in the TabBar are heavilly pixelated. So much so that it's fairly pointless to use font icons in iOS. 

This works great in Android and allows for great flexiblity when using the AppShell.

See below screenshots for reference

| iOS | Android |
| :-: | :-: |
| <img src="https://user-images.githubusercontent.com/54434905/163130506-39ae576c-ef31-4d2d-ad1a-1c9db84c7ec2.jpg" width="500" /> | <img src="https://user-images.githubusercontent.com/54434905/163130273-a4ddb67c-bf6b-46c2-8260-9d691ae4e7b2.jpg" width="500" /> |

[Reproduction Repo ](https://github.com/RichardMarsh/Maui.Test)

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Add a icon font to the resource folder and include in app start up
3. Setup app shell to use a TabBar and add several ShellContent entries
4. Set the ShellConent Icon property to FontImageSource and use glyphs from the font icons added earlier

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by kristinx0211** [comment]
verified works on Android and the above project, but fail in IOS 15.4. the Icon in the TabBar does not show at all.
![image](https://user-images.githubusercontent.com/99457000/163340344-4792df8d-7bb0-48d5-b40d-1506f386bda2.png)

**Comment by v-longmin** [comment]
Verifed repro on ios15.4 with VS 17.3.0 Preview 1.0 [32418.321.main]. Repro project;
[Maui.Test-master (1).zip](https://github.com/dotnet/maui/files/8520267/Maui.Test-master.1.zip)

**Comment by davidortinau** [comment]
iOS seems to need/want color in order to display. 

![Simulator Screen Shot - iPhone 13 Pro - 2022-04-21 at 19 39 42](https://user-images.githubusercontent.com/41873/164574073-1c1a94de-d311-4eb7-a211-046b7a0531a0.png)


```
<TabBar>
		<ShellContent Icon="{FontImage FontFamily='FontIcon', Glyph='&#xe900;', Color=Black, Size=22}"
        Title="Hello, World!"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" >

		</ShellContent>

		<ShellContent
        Title="Hello, World!"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" >
			<ShellContent.Icon>
				<FontImageSource FontFamily="FontIcon" Glyph="&#xe908;" Size="22" Color="Black" />
			</ShellContent.Icon>

		</ShellContent>

		<ShellContent
        Title="Hello, World!"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" >
			<ShellContent.Icon>
				<FontImageSource FontFamily="FontIcon" Glyph="&#xe958;" Color="Black"/>
			</ShellContent.Icon>

		</ShellContent>
	</TabBar>
```

**Comment by RichardMarsh** [comment]
> iOS seems to need/want color in order to display.

@davidortinau is this a bug or a feature?

**Comment by MGohil** [comment]
I have tested this via Font icons as well as png icons. First two tabs uses FontAwesome icons while other two are using png icons from resources.
As you can see, Android behaves pretty good here but iOS icon shows as white icons.
Even if you select, only text color changes but font icon color remains unchanged.
However, if we use png images, the selection color works good in both platforms. The selection applies to icon and text together.
![image](https://user-images.githubusercontent.com/16605284/192242087-681a2542-309e-4e1e-8155-7d24bb1cdfc2.png)

To overcome above white icon issue for FontAwesome in iOS, as @davidortinau mentioned, we have to explicitly provide the Color to the icon, which solves this problem but again as you can see in below, the selected tab icon still remains unchanged. Only text color changes.
![image](https://user-images.githubusercontent.com/16605284/192243662-c15f20e9-c36d-4e8b-9e76-c8a4eb2a055f.png)

No matter whether we use FontIcon or png both should behave same.

**Comment by RobTF** [comment]
Same problem here. Xamarin was fine.

**Comment by MV10** [comment]
They look pretty chunky on Windows, too (this is a high-DPI 4K screen).

![image](https://github.com/dotnet/maui/assets/794270/5df17f8b-4b94-44c4-90a0-6414f1085127)
