### ISSUE TITLE
ERROR ITMS-90165: Invalid Provisioning Profile Signature

### ISSUE THREAD

**Issue by RaspeR87** [dotnet/maui#6044]
### Description

I have problem with latest MAUI RC1 version if I want to create IPA file for Apple App Store.

I run this command:

dotnet publish -f:net6.0-ios -c:Release /p:ServerAddress=xx.xx.xx.xx /p:ServerUser=username /p:ServerPassword=password /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory=/Users/ezslovenia/Library/Caches/Xamarin/XMA/SDKs/dotnet/ /p:EnableAssemblyILStripping=false

Now everything works ok, ipa file is generated. But If I want to upload that file with Transporter App I get this error: 
![2022-04-13_10-10-02](https://user-images.githubusercontent.com/14901702/163130979-907700ce-e4df-4c2c-97e7-4d4c259e26dd.png)

I have valid publishing profile:
![2022-04-13_10-12-30](https://user-images.githubusercontent.com/14901702/163131183-2cb54699-1a19-43fc-8676-c2b6467ae31d.png)

And I have added this command in csproj:
```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<!-- Only needed when you have a need for entitlements -->
		<!-- <CodesignEntitlement>Entitlements.plist</CodesignEntitlement> -->
		<CodesignKey>Apple Distribution: Kompas Xnet d.o.o. (xxxxxxxxxx)</CodesignKey>
		<CodesignProvision>TrimoLibraryApp</CodesignProvision>
	</PropertyGroup>
```

I think something must be with dotnet publish command, because I have exactly same Windows and OsX environment as before. With Preview 13 this step works well.

### Steps to Reproduce

1. Create new .NET MAUI project
2. Run command dotnet publish 
3. Upload ipa with Transporter App

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by tsjdev-apps** [comment]
I think that this issue is not related to .NET MAUI itself.
Looks like that some Apple certificates are expired yesterday. 

Looks like the easiest way is to create a new provisioning profile, see the following tweet:
https://twitter.com/JI/status/1514043544897425408

**Comment by RaspeR87** [comment]
@tsjdev-apps Ok, great. I will check that ASAP.

**Comment by tsjdev-apps** [comment]
@RaspeR87 I can confirm that creating a new provisioning profile helps, at least for a Xamarin.Forms app.

**Comment by jfversluis** [comment]
I'm fairly sure this is not a bug on our side. Make super sure that the profiles etc. are still valid and that you also have the valid ones on your local machine. If it turns out you can't make it work, please let us know.

**Comment by RaspeR87** [comment]
@tsjdev-apps @jfversluis  tnx for all effort, all works great now (y)

**Comment by jfversluis** [comment]
Great @RaspeR87 thanks for letting us know!
