### ISSUE TITLE
Create ContentPage VS template not using proper namespace when adding new ContentPage inside a folder

### ISSUE THREAD

**Issue by jBijsterboschNL** [dotnet/maui#6049]
### Description

When creating a .NET MAUI ContentPage or ContentView (both for C# as the Xaml option) inside a folder, no proper namespace is set to this new ContentPage. The new ContentPage will have the default project namespace instead, where it should have the namespace *.<foldername>

### Steps to Reproduce

1. Create new MAUI app project
2. Create a folder called 'Pages'
3. Create new MAUI ContentPage inside the Pages folder
4. The ContentPage is created, but it doesn't have the proper namespace *.Pages (it has the projects default namespace instead)

### Version with bug

Preview 14 (current)
(Also checked with RC-1)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

N/A

### Did you find any workaround?

Refactoring the namespace afterwards 🙈

**Comment by XamlTest** [comment]
Verified Repro with Visual Studio Enterprise 17.3.0 Preview 1.0 [32412.377.main]. Sample Project: [6049.zip](https://github.com/dotnet/maui/files/8480021/6049.zip)

**Comment by jfversluis** [comment]
@phenning looked at it and opened a [bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1523468) (internal link) on the tooling side for this. Closing this for now, should hopefully be resolved with an upcoming VS release 🤞
