### ISSUE TITLE
MauiAppBuilder' does not contain a definition for 'RegisterBlazorMauiWebView'

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#6056]
### Description

I have ugraded to visual studio 2022 preview (RC) and now my MAUI Blazor hybrid no longer works

I get the following error making it totally unusable

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MauiAppBuilder' does not contain a definition for 'RegisterBlazorMauiWebView' and no accessible extension method 'RegisterBlazorMauiWebView' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?)	PlcBrowser.Maui.Blazor (net6.0-android), PlcBrowser.Maui.Blazor (net6.0-ios), PlcBrowser.Maui.Blazor (net6.0-maccatalyst), PlcBrowser.Maui.Blazor (net6.0-windows10.0.19041)	C:\repos\products-source\src\Products\Apps\PlcBrowser\PlcBrowser.Maui.Blazor\MauiProgram.cs	12	Active

Please help

### Steps to Reproduce

1 - Add a MAUI Blazor project
2 - Once the project is created try and rebuild solution
3 - The error appears

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MauiAppBuilder' does not contain a definition for 'RegisterBlazorMauiWebView' and no accessible extension method 'RegisterBlazorMauiWebView' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?)	PlcBrowser.Maui.Blazor (net6.0-android), PlcBrowser.Maui.Blazor (net6.0-ios), PlcBrowser.Maui.Blazor (net6.0-maccatalyst), PlcBrowser.Maui.Blazor (net6.0-windows10.0.19041)	C:\repos\products-source\src\Products\Apps\PlcBrowser\PlcBrowser.Maui.Blazor\MauiProgram.cs	12	Active

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 12

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

latest windows

### Did you find any workaround?

no

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MauiAppBuilder' does not contain a definition for 'RegisterBlazorMauiWebView' and no accessible extension method 'RegisterBlazorMauiWebView' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?)	PlcBrowser.Maui.Blazor (net6.0-android), PlcBrowser.Maui.Blazor (net6.0-ios), PlcBrowser.Maui.Blazor (net6.0-maccatalyst), PlcBrowser.Maui.Blazor (net6.0-windows10.0.19041)	C:\repos\products-source\src\Products\Apps\PlcBrowser\PlcBrowser.Maui.Blazor\MauiProgram.cs	12	Active
```

**Comment by RaspeR87** [comment]
@ltemimi Yes. In new MAUI RC1 you don't have to register Blazor MAUI Web View with RegisterBlazorMauiWebView.
So you simply delete this command and build project.

You could take a look into new fresh .NET MAUI Blazor App from template and you could see that there is no RegisterBlazorMauiWebView anymore.

**Comment by egvijayanand** [comment]
Have a look at the migration guide for more details:

https://github.com/dotnet/maui/wiki/Migrating-to-RC1#blazorwebview

**Comment by ltemimi** [comment]
Hi
Thanks for the help, the project I created was from a fresh install of visual studio 2022 preview for RC and it had the register which I have now deleted. So the template needs to be updated.
--------------------------------------------------------------------------

**Comment by egvijayanand** [comment]
Use the below command to update the templates from .NET CLI.

```shell
dotnet new --install Microsoft.Maui.Templates
```

**Comment by egvijayanand** [comment]
Yes, am also facing this issue. Engineers from the Maui team have to provide their responses on this.

**Comment by Eilon** [comment]
The original issue with out-of-date templates has been resolved. If there are other issues, please log new issues for each separate problem so that the right set of people can investigate.
