### ISSUE TITLE
Custom style not getting applied to Button

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#6064]
### Description

Have defined a custom style for Button identified by a name with x:Key attribute.

Then applied that custom style to the Button control by setting the Style attribute to the name of the Style.

It defaults to the Style distributed with that of the project template always.

### Steps to Reproduce

1. Create a new .NET MAUI App project from the default template
2. Open the App.xaml and Add the below style snippet within the ResourceDictionary tag
3. Open the MainPage.xaml and Set the Button style attribute to the value of the Style name
4. Build and run the project

Only relevant details provided to simulate the issue:

App.xaml
```xaml
<Style x:Key="PrimaryAction" TargetType="Button">
    <Setter Property="BackgroundColor" Value="Black" />
    <Setter Property="TextColor" Value="Yellow" />
</Style>
```

MainPage.xaml (Leave the other properties of Button untouched)
```xaml
<Button Style="{StaticResource PrimaryAction" />
```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android, Windows, I was *not* able to test on other platforms

### Affected platform versions

Android 31.0, Windows SDK 10.0.19041

### Did you find any workaround?

Nope

### Relevant log output

```shell
NA
```

**Comment by v-longmin** [comment]
Verified repro on windows & Android 12.0 with VS 17.2.0 Preview 2.1 [32317.152]. Repro project:
[MauiApp11.zip](https://github.com/dotnet/maui/files/8486010/MauiApp11.zip)

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue in main branch
![image](https://user-images.githubusercontent.com/6755973/163786321-ae692225-a72e-4e30-819f-d5789f08ab77.png)

**Comment by egvijayanand** [comment]
Hi @jsuarezruiz,

This issue is consistently simulating with **RC1** and am not sure what the Main branch is up to.

Attached is the project used to simulate the issue. Have tried adding the style definition as _App- and Page-level resource_, but there is NO change in the outcome.

[Issue6064.zip](https://github.com/dotnet/maui/files/8504977/Issue6064.zip)

Regards,
Vijay Anand E G

**Comment by PureWeen** [comment]
So this isn't really a bug :-/ it's just confusing behavior

The default styles use "Background" to set the color which will take priority over "BackgroundColor" 

If you change the style to use "Background" then it applies the style

**Comment by PureWeen** [comment]
The issue here is that the styles that now ship with MAUI are setting the button via the VSM. If you set the styles via the VSM then the properties on the control itself are no longer useable :-/ This is definitely an oversight we'll need to think about.

**Comment by PureWeen** [comment]
We fixed this on the templates by removing the styles from the "Normal" state. If you update your code with the latest styles from a new template that should fix
