### ISSUE TITLE
Error NETSDK1147 workloads must be installed: maui-android

### ISSUE THREAD

**Issue by agustinbishel** [dotnet/maui#6077]
### Description

I'm trying to compile and test on visual studio for mac 2022 but I am not successful. Last night update my visual studio for mac (Version 17.0 Preview build 8567) later i just create a new maui project with dotnet new maui -n "MyMauiApp" (following the official wiki https://github.com/dotnet/maui/wiki/macOS-Install) but i get this error in visual studio:

Getting restore information for project /Users/agustinbishel/Projects/MauiMundial/MauiMundial.csproj
/usr/local/share/dotnet/sdk/6.0.202/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5) : error NETSDK1147: To build this project, the following workloads must be installed: maui-android
To install these workloads, run the following command: dotnet workload install maui-android
Unable to create package spec for project. '/Users/agustinbishel/Projects/MauiMundial/MauiMundial.csproj'

I check this by running: dotnet workload list

agustinbishel@Agustins-MacBook-Air ~  dotnet workload list

Installed Workload Ids
----------------------
maui-ios
maui-android
maui
android

----------------------

Is there but not working

So I run:
 ✘ agustinbishel@Agustins-MacBook-Air ~ sudo dotnet workload install maui-android

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.202

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------

Workload(s) 'maui-android' are already installed.
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Garbage collecting for SDK feature band(s) 6.0.200...

Successfully installed workload(s) maui-android maui-ios maui android.

However, I can compile with vscode without any problem.

### Steps to Reproduce

1 - Create a new maui project with dotnet new maui -n "MyMauiApp" 
2- Open the project with visual studio for mac 2022 (preview)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Not apply to any

### Did you find any workaround?

I check mi VPN, change my network. Reinstall...

### Relevant log output

```shell
Getting restore information for project /Users/agustinbishel/Projects/MauiMundial/MauiMundial.csproj
/usr/local/share/dotnet/sdk/6.0.202/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5) : error NETSDK1147: To build this project, the following workloads must be installed: maui-android
To install these workloads, run the following command: dotnet workload install maui-android
Unable to create package spec for project. '/Users/agustinbishel/Projects/MauiMundial/MauiMundial.csproj'
```

**Comment by toddlucas** [comment]
Not sure if my situation is related, but I have the same error after upgrading to VS 2022 17.2.0 Preview 3.0 Enterprise from the previous Preview 14 release. I then uninstalled Preview and then did a reinstall with only Mobile checked, as before. Same NETSDK1147 errors for all four workloads.

**Comment by jfversluis** [comment]
Also I see that you're using .NET 6.0.202, while that should be .NET 6.0.300. Also see the instructions in [this issue](https://github.com/dotnet/maui/issues/6082#issuecomment-1098567372)

**Comment by VincentBu** [comment]
Feel free to remove `verified` tag if it's not proper here.

**Comment by agustinbishel** [comment]
HI everyone, sorry for the delay! I'm still trying, I don't give up.

I add information about what Gerald said: 

> Also I see that you're using .NET 6.0.202, while that should be .NET 6.0.300. Also see the instructions in [this issue](https://github.com/dotnet/maui/issues/6082#issuecomment-1098567372)

following the instructions in the comment I find the following:

running this command: 
`sudo dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.300/rc.1.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-323bf2dd/nuget/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-572aeedc/nuget/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
`

Result
```
Workload(s) 'maui' are already installed.
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.android.
Installing workload manifest microsoft.net.sdk.android version 32.0.300-rc.1.4…
Workload installation failed. Rolling back installed packs...
Installing workload manifest microsoft.net.sdk.android version 31.0.200-preview.14.106…
Installation rollback failed: Failed to install manifest microsoft.net.sdk.android version 31.0.200-preview.14.106: The transaction has aborted..
Workload installation failed: Failed to install manifest microsoft.net.sdk.android version 32.0.300-rc.1.4: microsoft.net.sdk.android.manifest-6.0.200::32.0.300-rc.1.4 is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-323bf2dd/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-572aeedc/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://api.nuget.org/v3/index.json"..
```

In the meantime, I'm going to reinstall everything. 

Thanks!
