### ISSUE TITLE
Release event is fired twice when hit a button 

### ISSUE THREAD

**Issue by AllenMiaoFil** [dotnet/maui#6095]
### Description

I tried to create a Release event on a button, Release event execute twice When clicked it.
You can see my case in zip file.

### Steps to Reproduce

1. Created new MAUI Project.
2. create a button with Release event
3. do some action, you can write a line in output
4. run application on window.
5. I've tested on windows and IOS, only Window has issue
[ButtonClick.zip](https://github.com/dotnet/maui/files/8488086/ButtonClick.zip)
.

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Window 10 + SDK6.0.200

**Comment by kristinx0211** [comment]
verified repro with vs 17.3.0 Preview 1.0 [32411.352.main].

**Comment by AllenMiaoFil** [comment]
hey Team, I still have this issus on 6.0.300-rc1.5355, May I know which version will be added?

**Comment by DeanFaizal** [comment]
It's in rc2

**Comment by AllenMiaoFil** [comment]
Thanks for your confirmed, it is there.
