### ISSUE TITLE
Edge Developer Tools not showing after upgrading to MAUI RC1

### ISSUE THREAD

**Issue by efonsecab** [dotnet/maui#6098]
### Description

We have a couple of application using MAUI Blazor, and usually when we press F12 in the app running set to "Windows Machine", we would see the Edge Developers tools to inspect the html and css.
After upgrading to MAUI RC1, the F12 is not working anymore to show the Developer tools, so we cannot inspect the html nor the css.

### Steps to Reproduce

1. Create a New MAUI Blazor App
2. Run the app set to "Windows Machine"
3. Press F12 in the running app

The Developer Tools are not loading.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

No, haven't found a workaround.

**Comment by egvijayanand** [comment]
The Developer Tools need to be enabled explicitly from RC1.

More details on this blog post:

https://egvijayanand.in/2022/04/13/net-maui-rc1-blazorwebview-streamlined/

**Comment by Eilon** [comment]
Indeed, check out how the updated project templates enable the browser dev tools conditionally:

https://github.com/dotnet/maui/blob/79f620dc247fc80864bbf6e2a958d14ef99401ba/src/Templates/src/templates/maui-blazor/MauiProgram.cs#L18-L23

(Ignore the weird comments in that code, they are used by the template engine and not part of the project itself.)
