### ISSUE TITLE
The  image is not displayed on Android when image source is a web resource

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#6099]
### Description

Set the Source of an Image to a web address. The Image will show on iOS but not on Android. I used the default maui template to reproduce the bug. Just change the Source of image to a web address. 

### Steps to Reproduce

Run the repro project on Android
[MauiApp1.zip](https://github.com/dotnet/maui/files/8490307/MauiApp1.zip)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by codeaphex** [comment]
Duplicate #6067
