### ISSUE TITLE
Changing Label Value at Runtime makes the label invisible 

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#6100]
### Description

On default maui template just continue to click the button. The count label will be invisible after two clicks.

### Steps to Reproduce

Run the repro project. Click on the button multiple times. 
[MauiApp1.zip](https://github.com/dotnet/maui/files/8490362/MauiApp1.zip)
 

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32412.377.main]. Repro on Android with above project.

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue on main branch:
![issue-6100](https://user-images.githubusercontent.com/6755973/163981040-6d66b718-d458-4fbd-b1a6-7bd701635c8a.gif)

**Comment by karthikraja-arumugam** [comment]
@jsuarezruiz , I'm facing this issue in windows

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz , I'm facing this issue in windows

Could you attach a small sample?. Thanks!.

**Comment by davidortinau** [comment]
I'm unable to reproduce this on Windows or Android from Windows using main branch (rc2).

**Comment by rachelkang** [comment]
This was fixed recently by https://github.com/dotnet/maui/pull/5897!
