### ISSUE TITLE
Change UseMauiEssentials to UsePlatformEssentials (or something similar)

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#6102]
### Description

If you add:
```xml
<UseMauiEssentials>true</UseMauiEssentials>
```

to a non-maui andriod/ios/mac/windows project it will give the developer access all of the platform abstractions. This is nice for other frameworks as well such as Uno & Avalonia. 

However since there technically isn't a dependency on .NET MAUI maybe we should consider a name change.

If someone uses these APIs without .NET MAUI they would need to do additional setup code, but beyond that nothing else is needed. Worked with @mattleibow on some ideas and our only good one was **UsePlatformEssentials**... I know Essentials isn't in the name anymore, but makes sense?

### Public API Changes

Change UseMauiEssentials to UsePlatformEssentials

### Intended Use-Case

See description

**Comment by mattleibow** [comment]
Is it `UseMauiEssentials` or `UseEssentials` right now?

**Comment by jamesmontemagno** [comment]
I think it is "UseMauiEssentials" currently from my testing.
