### ISSUE TITLE
Application.Current.Windows maintains incorrect count

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#6103]
### Description

`Application.Current.Windows` doesn't maintain a correct count of `Window` objects after calling `CloseWindow`.

If you create a Window, `Application.Current.Windows` = 2. Then close the newly created Window and examine `Application.Current.Windows` from your root window. `Application.Current.Windows` still = 2.

Repro: [MultiWindowDemo.zip](https://github.com/dotnet/maui/files/8490686/MultiWindowDemo.zip)

### Steps to Reproduce

1. Run the attached sample on Windows.
2. Click the button to create a Window.
3. With the new window active, examine `Application.Current.Windows` to see its 2.
4. Close the button (on the second Window) to close it.
5. With the root window active, examine `Application.Current.Windows`. It's still 2.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by kristinx0211** [comment]
repro on windows, vs 17.3.0 Preview 1.0 [32413.517.main].

**Comment by almostjulian** [comment]
I also see this on MacCatalyst.

**Comment by nextfool** [comment]
I also encountered this issue today. Seems it caused by a tiny bug when create a Virtual window. I have made a [pull request ](https://github.com/dotnet/maui/pull/6122), sees the fix works just fine.

**Comment by nextfool** [comment]
Sorry I have to close my PR as it brings new problems. I found this issue some how related to https://github.com/dotnet/maui/pull/4860 when I checked the file history. Maybe someone can find some clue there, or if I have time I will dig it deeper. :)
