### ISSUE TITLE
[Enhancement] Consider Dwayne Johnson as a VIP in promoting MAUI.

### ISSUE THREAD

**Issue by Miksier** [dotnet/maui#611]
## Summary

We all know that a framework needs to be promoted to developer community so it is known and well received.
XF has a lot of backstory of being a completly crippling experience in both setting up and working with. Now things are a lot better but the old smell is lingering still.
MAUI is a chance to create a strong brang anew, but it has to become known.
Also all know that Dwayne Johnson portreyed Maui in Disney's Moana. 
This coincidence SHOULD NOT be wasted even if Maui would not be used for Disney reasons.
As I remember MS already worked with Dwayne Johnson in promoting Xbox. Wouldnt this be an ultimate flex to do this again?

This is, of course, not a serious case, yet Im sure that a lot of people wish for this silly thing to become true. 
So out of thoughts of hundreds of IT and marketing dep. people this ticket became a reality.

## API Changes
Well. I think the API does not need to be changed with this.

## Intended Use Case
Promoting the heck out of MAUI and making a massive flex to other frameworks. 
Because we could and we should.

**Comment by Happypig375** [comment]
And then people will start comparing it with Flutter. Please, the team must fix the Xamarin.Forms roots before going confident and brag everywhere.

**Comment by Redth** [comment]
Love the idea, but unfortunately out of scope ;)  What can I say except, you're wel.... nope :D
