### ISSUE TITLE
Counter is disappearing in the default MAUI project on Android

### ISSUE THREAD

**Issue by holecekp** [dotnet/maui#6112]
### Description

I have created a new MAUI application using the default template. It runs on Android well. When I tap the button, the counter is increased. However, when the counter reaches 9, it disappears on the next click.

![count 9](https://user-images.githubusercontent.com/24872113/163454611-4d08d758-c680-4f2e-9fb8-9e0c111920d1.png)

![no current count](https://user-images.githubusercontent.com/24872113/163453872-be612767-7495-4f2c-90d1-03b186f0bc7b.png)

PS. Launching the app on Android is extremely slow (much slower compared to Xamarin.Forms).

### Steps to Reproduce

1. Create a new MAUI app using the default template in VS and launch it.
2. Tap on the button until there is 9 on the counter.
3. Tap on the button again, the counter disappears.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10

**Comment by Eilon** [comment]
Theory: I'm guessing when the label goes to double-digits it isn't being re-sized, so the text ends up not rendering.

**Comment by ncarandini** [comment]
I do confirm the bug, same to me. It reminds me a similar error on early previews, maybe a regression?

**Comment by enricoe73** [comment]
Same bug, on Android Emulator Pixel 5 API 30 the counter disappear at 2.

**Comment by kristinx0211** [comment]
verified repro on Android 12 using 17.3.0 Preview 1.0 [32413.517.main].

**Comment by HobDev** [comment]
Same as #6100

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/5717
