### ISSUE TITLE
Use ServiceCollection.MakeReadOnly in .NET 7

### ISSUE THREAD

**Issue by eerhardt** [dotnet/maui#6115]
### Description

When we take a 7.0 version of Microsoft.Extensions.DependencyInjection, we can take advantage of a new API: https://github.com/dotnet/runtime/issues/66126

This will allow us to delete all this code and just use a built-in ServiceCollection directly:

https://github.com/dotnet/maui/blob/2d765b7ae08c68f975205239c7ff366be493fd7f/src/Core/src/Hosting/Internal/MauiApplicationServiceCollection.cs#L8-L101

### Steps to Reproduce

1. See above. Inspect the code and ensure we no longer have that class internally.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

**Comment by rmarinho** [comment]
fixed by #10097
