### ISSUE TITLE
Windows Blue Screen when connecting to simulator

### ISSUE THREAD

**Issue by philipwolfe** [dotnet/maui#6117]
### Description

I get a windows blue screen when trying to connect to the simulator.

### Steps to Reproduce

1. Create the default MAUI project.
2. Run the app in the Android Emulator. (works fine)
3. Switch to MAC simulator.
4. Click play.
5. It asks me to connect to a MAC.
6. I click, I don't own a MAC.
7. Blue Screen.
8. Looks like the fault is caused by the android emulator

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 21H1

### Relevant log output

```shell
Faulting application name: qemu-system-x86_64.exe, version: 0.0.0.0, time stamp: 0x62339f9e
Faulting module name: MSVCP140.dll, version: 14.30.30704.0, time stamp: 0x615a9215
Exception code: 0xc0000005
Fault offset: 0x00000000000131f8
Faulting process id: 0x2384
Faulting application start time: 0x01d850622cdf7962
Faulting application path: C:\Program Files (x86)\Android\android-sdk\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe
Faulting module path: C:\WINDOWS\SYSTEM32\MSVCP140.dll
Report Id: 1153b81d-865d-42da-b83e-9ed2ecb15d30
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by philipwolfe** [comment]
![IMG_20220414_195342.jpg](https://user-images.githubusercontent.com/61720289/163502776-deab5e7c-25a9-48b6-8876-a997202607a3.jpg)

**Comment by VincentBu** [comment]
Hi @philipwolfe , I can't repro this issue. Could you provide the version of visual studio?  As I know, visual studio only has `pair to mac` rather than `MAC simulator` in MAUI workload. Click `pair to Mac` you will see:
![image](https://user-images.githubusercontent.com/44959937/163507739-c051f66d-2787-445d-99a1-2dffd9a710be.png)

Additionally, if you run into blue screen, there should be an error code. Could you provide it?

**Comment by MagicAndre1981** [comment]
post your hardware specs and also run Android SDK Manager and look for emulator updates. Also try to [analyze the minidumps with Windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/analyzing-a-kernel-mode-dump-file-with-windbg)

**Comment by jfversluis** [comment]
I'd love to help you out with this @philipwolfe but this isn't an issue on the .NET MAUI side of things unfortunately. I would say something is causing this in your setup. Check the Windows Event Logs to see if anything is there. You might get additional support from the Visual Studio team. You can reach them through Visual Studio and go to your Help menu and then Provide Feedback > Report a Problem. That will also include all the relevant logging etc. but they might say something along the same lines.

I hope you will figure it out!
