### ISSUE TITLE
Selection Highlight offset by 5 pixels

### ISSUE THREAD

**Issue by mike3sullivan** [dotnet/maui#6118]
### Description

In a simple ListView or CollectionView, the selection highlight seems to be offset to the right by about 5 pixels [Windows].

### Steps to Reproduce

Add a simple ListView like:
`
<ListView >
                <ListView.ItemsSource>
                    <x:Array Type="{x:Type x:String}">
                        <x:String>One</x:String>
                        <x:String>Two</x:String>
                        <x:String>Three</x:String>
                        <x:String>Four</x:String>
                    </x:Array>
                </ListView.ItemsSource>
            </ListView>
`
What I see is:
![Selection Highlight](https://user-images.githubusercontent.com/26934129/163504005-265f079e-25fc-4bab-8d65-48e4a68f5702.png)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

Adding a padding to the content seems to be required

**Comment by v-longmin** [comment]
Verified repro on VS 17.2.0 Preview 2.1 [32317.152]. Repro project:
[MauiApp15.zip](https://github.com/dotnet/maui/files/8493326/MauiApp15.zip)
