### ISSUE TITLE
CollectionView items not rendered when using EmptyView

### ISSUE THREAD

**Issue by level120** [dotnet/maui#6119]
### Description

`CollectionView` items not rendered.

# When including `EmptyView` attribute.

### XAML
```xml
                <CollectionView ItemsSource="{Binding PresentModelList}"
                                SelectionMode="Single"
                                EmptyView="Empty">
               ...
                </CollectionView>
```

### Result

![image](https://user-images.githubusercontent.com/10791961/163532915-ce74dad5-478b-4753-b692-ff7e8029cad3.png)

---

#  When removing `EmptyView` attribute.

### XAML
```xml
                <CollectionView ItemsSource="{Binding PresentModelList}"
                                SelectionMode="Single">
               ...
                </CollectionView>
```

### Result

![image](https://user-images.githubusercontent.com/10791961/163533015-9c0e1030-f5f2-49ab-90e2-599d96df5a62.png)

### Steps to Reproduce

1. Create `CollectionView`
2. Add `EmptyView` attribute or tag in xaml.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11, Pixel 5 Simulator

### Did you find any workaround?

Remove `EmptyView` attribute or tag in `CollectionView` xaml

[CollectionViewPresentBug.zip](https://github.com/dotnet/maui/files/8494340/CollectionViewPresentBug.zip)

### Relevant log output

```shell
No any output.
```

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android with above project.

**Comment by jamesmontemagno** [comment]
Repo in Final folder as well -> https://github.com/dotnet-presentations/dotnet-maui-workshop

**Comment by jamesmontemagno** [comment]
@Redth I don't think this was fixed. At least in RC 3 from what I see in my custom view
