### ISSUE TITLE
[Bug] Fix WinUI Life cycle events

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#612]
Reunion 0.5.0 stable removed Resuming/Suspending
https://github.com/dotnet/maui/pull/610

Search source code for

```
// TODO WINUI
//Microsoft.UI.Xaml.Application.Current.Resuming += OnResumingAsync;
```

https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#preview-features
`Application.Suspending is not called in desktop apps. See API reference documentation on the Application.Suspending Event for more details.`

**Comment by Harrybombe** [comment]
<solution>
    <add key="disableSourceControlIntegration" value="true" />
</solution>
