### ISSUE TITLE
SkiaSharp OnPaintSurface not called on iOS device connected to Windows dev computer

### ISSUE THREAD

**Issue by SailDev** [dotnet/maui#6120]
### Description

InvalidateSurface does not trigger OnPaintSurface, when the app is deployed to an iOS device, directly connected to the Windows dev computer.

The problem does not occur, when the app is deployed to a remotely connected device via Mac build-host.

Maybe this info saves some time for someone.

### Steps to Reproduce

1. Create a blank Maui app
2. Add Package references
`		<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.0-preview.232" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls.Compatibility" Version="2.88.0-preview.232" />
		<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="2.88.0-preview.232" />`
3. Add .UseSkiaSharp() to builder 

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.3.1

### Did you find any workaround?

Use a remote build host.

**Comment by jfversluis** [comment]
Thanks for the issue SailDev, please report this one on the [SkiaSkharp repo](https://github.com/mono/SkiaSharp), thanks!
