### ISSUE TITLE
The dotnet_bot image in default mobile template is blurry 

### ISSUE THREAD

**Issue by wieslawsoltes** [dotnet/maui#6121]
### Description

The dotnet_bot image in default mobile template is blurry 

https://github.com/dotnet/maui/blob/2d765b7ae08c68f975205239c7ff366be493fd7f/src/Templates/src/templates/maui-mobile/MainPage.xaml#L36-L41

https://github.com/dotnet/maui/blob/2d765b7ae08c68f975205239c7ff366be493fd7f/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj#L39

### Steps to Reproduce

1. Create new app from template
2. Run on windows

![vm7Rn68qoN](https://user-images.githubusercontent.com/2297442/163547604-e58bc694-1c20-42e1-86a6-046bc146ebe5.png)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

Change BaseSize in csrpoj
```xaml
<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="250,310" />
```
![fG6gcBGQbj](https://user-images.githubusercontent.com/2297442/163547810-8cbeee2b-0d79-446b-acdb-343feb05c3ad.png)

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows. Sample Project: [MauiApp5.zip](https://github.com/dotnet/maui/files/8494979/MauiApp5.zip)

**Comment by mattleibow** [comment]
Thanks! Seems that in #6319 the image view size was reduce to below that of the image file, so now it is crisp again.

This is probably something that we need to track and make sure we are not asking for a small file to be generated and then trying to make it fill the screen.
