### ISSUE TITLE
Hot Restart No longer works

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#6123]
### Description

Hi
I try to use my iphone to test a dotnet MAUI Blazor app using restart I get an error as follows.
Hot restart worked in preview 13 and stopped working in preview 14 and RC

![image](https://user-images.githubusercontent.com/5493492/163551270-949e9b48-712e-4616-adfc-2c0969a09d3e.png)

Please help as I am stuck .

### Steps to Reproduce

1. Create a dotnet MAUI Blazor app from the template.
2. Check build works
3. Use IOS local device (IPhone)
4. The error appears
5. 
![image](https://user-images.githubusercontent.com/5493492/163551442-8e9dfb09-6d76-482d-947b-4203e99a21fd.png)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 13

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Windows server 2022

### Did you find any workaround?

No 

### Relevant log output

```shell
See error picture
```

**Comment by espenrl** [comment]
This is probably related to https://developercommunity.visualstudio.com/t/Cannot-load-Apple-certificates/1692185

**Comment by jfversluis** [comment]
Thanks for the assistance @espenrl! As pointed out, there are ongoing issues with the certificates in Visual Studio and therefore also with Hot Restart. Please keep an eye on the linked Visual Studio ticket for the status. We hope to resolve it ASAP!

**Comment by ltemimi** [comment]
OK Thanks I am completely blocked tried the answers above to no avail.
Thanks for the help

**Comment by ltemimi** [comment]
This issue should not be closed it is crucial
