### ISSUE TITLE
IOS Simulators no longer work

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#6127]
### Description

When I try and use an IOS simulator , the simulator seems to be unable to connect to the paired Mac (they worked OK on preview 13) all the issues started from preview 14 and now RC for ios

![image](https://user-images.githubusercontent.com/5493492/163574525-ead76532-281b-435d-bae7-25cc8517f342.png)

### Steps to Reproduce

1 Create a new MAUI Blazor project from template
2 Build to makes ure buitl is OK
3 Pair to A Mac
4 Use a simulator
5 Observe the following
![image](https://user-images.githubusercontent.com/5493492/163574667-9177e2d4-f074-4d89-a64f-8af713b3e509.png)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

Windows server 2022

### Did you find any workaround?

No

### Relevant log output

```shell
see picture above
```

**Comment by kbarnett7** [comment]
I ran into this yesterday as well once we migrated to RC1. When attempting to run the app in the iOS Simulator on Windows, the process would hang at the "Connecting to Mac..." window. Our workaround is to deploy the app to the simulator on the actual Mac machine Visual Studio is paired to. You do this by unchecking the "Remote Simulator to Windows" checkbox (Tools --> Xamarin --> iOS Settings --> Simulator).

**Comment by ltemimi** [comment]
Thanks , I agree it just my Mac is not close to my desk , it used to work  with preview 13.
I hope the RC issues would be resolved quickly as I am completely blocked.

**Comment by kbarnett7** [comment]
Have you tried remoting into the Mac using something like VNC Viewer? That is how the members of my dev team access our company development Mac.

**Comment by ltemimi** [comment]
Thanks Agreed it is something I can do. I also have big issues with hot restart all worked OK in preview 13 since preview 14 I have backwards. 
Hope all will be fixed soon.

**Comment by drasticactions** [comment]
This is due to breaking changes in Xcode 13.3 impacting the remote iOS simulator. It is unrelated to MAUI. You can read about it here, https://developercommunity.visualstudio.com/t/Visual-Studio-2022-1711-iOS-simulator/1695537

In short, it's being working on... but it's not trivial to fix and will take time. As a workaround, use VNC or some form of remote desktop to log into your mac, or use Visual Studio for Mac instead.

**Comment by ltemimi** [comment]
Great, thanks for the help I will use remote desktop.
