### ISSUE TITLE
ArcSegments are rendered as straight lines

### ISSUE THREAD

**Issue by dirivero** [dotnet/maui#6128]
### Description

`ArcSegment` is rendered as straight line inside path geometries:

Here's a simple example:
```       
<Path
    Data="M 0,0 A 50,50 0 0 0 100,0"
    Stroke="Red"
    StrokeThickness="3"
    Aspect="Uniform"
    WidthRequest="100"
    HeightRequest="100"
/>
```
It should look like this:

<img width="102" alt="image" src="https://user-images.githubusercontent.com/7670773/163574180-400dc73b-0cf6-48fe-942d-3ae065b76801.png">

But it looks like this:
<img width="101" alt="image" src="https://user-images.githubusercontent.com/7670773/163574620-d08e794a-85d0-4471-b6e9-45d9c138d8f7.png">

Here is the same path with with the extended XAML notation:

```
<Path
    Stroke="Red"
    StrokeThickness="3"
    Aspect="Uniform"
    WidthRequest="100"
    HeightRequest="100">
    <Path.Data>
        <PathGeometry>
            <PathGeometry.Figures>
                <PathFigure IsClosed="False"
                    StartPoint="0,0">
                    <PathFigure.Segments>
                        <PathSegmentCollection>
                            <ArcSegment Point="100,0" Size="50,50" />
                        </PathSegmentCollection>
                    </PathFigure.Segments>
                </PathFigure>
            </PathGeometry.Figures>
        </PathGeometry>
    </Path.Data>
</Path>
```

### Steps to Reproduce

You can reproduce it with any of the 2 code snippets above.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

**Comment by kristinx0211** [comment]
verified repro on Android 11. demo:[MauiApp1.zip](https://github.com/dotnet/maui/files/8503714/MauiApp1.zip)
