### ISSUE TITLE
Label Formattedtext setting textcolor sets backgroundcolor too

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#6129]
### Description

When I use Formattedtext in a label and set the TextColor the BackgroundColor gets set too 

### Steps to Reproduce

1. Unzip the project from [Simple-formatted.zip](https://github.com/dotnet/maui/files/8496786/Simple-formatted.zip)
2. Compile and run it on Windows, you should see this:
![simple-formatted](https://user-images.githubusercontent.com/12423046/163591791-11cd001e-ae41-40f6-995c-8b17878bbdb5.jpg)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

Yes, explicitly set the BackgroundColor to the one you want

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows with above project.
