### ISSUE TITLE
Crash while resizing window with grouped ListView

### ISSUE THREAD

**Issue by greatoceansoftware** [dotnet/maui#6132]
### Description

Following the steps below results in an unhandled exception "A cycle occurred while laying out the GUI."

Reproduction project is [here](https://github.com/greatoceansoftware/Layout-Cycle-Exception).

![image](https://user-images.githubusercontent.com/78753788/163599289-8085d96a-dca9-44f1-b5fe-00935c7cf6bc.png)

### Steps to Reproduce

1. Build and run the project as Windows Machine.
2. Click the Do Something button. The activities in the list will be filtered (hidden).
3. Try to resize the window.
4. Exception = {"A cycle occurred while laying out the GUI."} Layout cycle detected. The layout cycle could not complete.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.19044 Build 19044

### Did you find any workaround?

No

**Comment by iot-crazy** [comment]
I have the same problem with similar very simple projects. The only pattern I've found so far is when items in a list need to render outside the bounds of the current window. Or, if items do fit in the window and i make the window smaller then I get the exception too. 
My example can be seen here:  https://github.com/dotnet/maui/discussions/6135

**Comment by iot-crazy** [comment]
I think I've found a workaround, at least for my example. If I replace the top level ```<ScrollView>``` with a ```<Frame>```, then it seems to work fine and doesn't produce this exception. As soon as I change the ```<Frame>``` to a ```<ScrollView>```, the exception appears. 
Note that, for me at least, this only happens if there are enough items in the collection to cause the need for scrolling.

For example
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="using:MauiApp2"
             x:Class="MauiApp2.MainPage"
             x:Name="this">

    <Frame BindingContext="{x:Reference this}">
        <CollectionView ItemsSource="{Binding Products}">
            <CollectionView.ItemTemplate>
                <DataTemplate>

                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="Auto"/>
                            <ColumnDefinition/>
                        </Grid.ColumnDefinitions>
                        <Label Text="{Binding ID}" Grid.Column="0" Margin="0,0,5,0"/>
                        <Label Text="{Binding Name}" Grid.Column="1"/>
                    </Grid>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </Frame>
</ContentPage>
```

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows. Sample Project: [6132.zip](https://github.com/dotnet/maui/files/8503110/6132.zip)

**Comment by emorell96** [comment]
> I think I've found a workaround, at least for my example. If I replace the top level `<ScrollView>` with a `<Frame>`, then it seems to work fine and doesn't produce this exception. As soon as I change the `<Frame>` to a `<ScrollView>`, the exception appears. Note that, for me at least, this only happens if there are enough items in the collection to cause the need for scrolling.
> 
> For example
> 
> ```
> <?xml version="1.0" encoding="utf-8" ?>
> <ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
>              xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
>              xmlns:local="using:MauiApp2"
>              x:Class="MauiApp2.MainPage"
>              x:Name="this">
> 
>     <Frame BindingContext="{x:Reference this}">
>         <CollectionView ItemsSource="{Binding Products}">
>             <CollectionView.ItemTemplate>
>                 <DataTemplate>
> 
>                     <Grid>
>                         <Grid.ColumnDefinitions>
>                             <ColumnDefinition Width="Auto"/>
>                             <ColumnDefinition/>
>                         </Grid.ColumnDefinitions>
>                         <Label Text="{Binding ID}" Grid.Column="0" Margin="0,0,5,0"/>
>                         <Label Text="{Binding Name}" Grid.Column="1"/>
>                     </Grid>
>                 </DataTemplate>
>             </CollectionView.ItemTemplate>
>         </CollectionView>
>     </Frame>
> </ContentPage>
> ```

I am also getting this exception on RC1 with a CollectionView as well when I resize the window after loading the items of the CollectionView.
![image](https://user-images.githubusercontent.com/20151415/164787822-c832c2e3-7445-4c82-8ee7-ebcf37d7ca1f.png)

**Comment by emorell96** [comment]
So far with limited testing this won't happen if I use Span=1 in my ``GridItemsLayout``.

**Comment by mike3sullivan** [comment]
In case it helps...this problem seems to have been around in UWP and Xamarin since 2014 at least and it seems to be caused by a scrollviewer inside a scrollviewer (or a combination of components with embedded scrollviewers like listview).  
https://social.msdn.microsoft.com/Forums/windows/en-US/79d27deb-30c2-4270-a27f-3f805e623580/layout-cycle-detected-layout-could-not-complete?forum=wpdevelop

It has also been logged as an issue with microsoft-winui-xaml 
https://github.com/microsoft/microsoft-ui-xaml/issues/3989

**Comment by mike3sullivan** [comment]
Further debugging on my part -- my problem resolved when I made the content (grid in my case) inside the scrollview NOT verticaloptions="center"...

**Comment by PureWeen** [comment]
I tested the sample on the latest main bits and it no longer crashes. 
I'm assuming this was fix by https://github.com/dotnet/maui/pull/6431
