### ISSUE TITLE
iOS Crash on populating CollectionView with data

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#6134]
### Description

When I load data into collectionview i get a crash .. working fin on Android/Windows.

See Final Folder in https://github.com/dotnet-presentations/dotnet-maui-workshop

### Steps to Reproduce

Load Final Folder in https://github.com/dotnet-presentations/dotnet-maui-workshop

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All

### Did you find any workaround?

No

**Comment by v-longmin** [comment]
Verified repro on iOS 15.4 with vs 17.3.0 Preview 1.0 [32418.321.main]. Repro project:
[dotnet-maui-workshop-main.zip](https://github.com/dotnet/maui/files/8519920/dotnet-maui-workshop-main.zip)

**Comment by jfversluis** [comment]
Still happening on current main

**Comment by rmarinho** [comment]
yeah i m looking at it, if you remove the Clear of the collection it works

**Comment by jamesmontemagno** [comment]
@rmarinho  interesting... like i guess i coudl only clear if there are objects...?
let me try that out

**Comment by jamesmontemagno** [comment]
So, put in a workaround where i don't clear it on the first time, however if you hit the button again after you load the data it will crash
