### ISSUE TITLE
Crash while trying to to register sync root with the OS in Windows

### ISSUE THREAD

**Issue by shv07** [dotnet/maui#6136]
### Description

I am trying to register sync root with the Windows using the ```Windows.Storage.Provider.StorageProviderSyncRootManager.Register()``` method and getting the exception:- 
```error
The operation attempted to access data outside the valid range (0x8000000B)
```

### Steps to Reproduce

Add the following code in a new class in Platform->Windows folder.
```csharp
StorageProviderSyncRootInfo info = new StorageProviderSyncRootInfo()
				{
					Id = GetSyncRootId(),
					Path = await StorageFolder.GetFolderFromPathAsync(ProviderFolderLocations.ClientFolder),
					DisplayNameResource = "AchnetCloudDrive",
					IconResource = "<path/to/icon>",
					HydrationPolicy = StorageProviderHydrationPolicy.Full,
					HydrationPolicyModifier = StorageProviderHydrationPolicyModifier.None,
					PopulationPolicy = StorageProviderPopulationPolicy.AlwaysFull,
					InSyncPolicy = StorageProviderInSyncPolicy.FileCreationTime | StorageProviderInSyncPolicy.DirectoryCreationTime,
					Version = "1.0.0",
					ShowSiblingsAsGroup = false,
					HardlinkPolicy = StorageProviderHardlinkPolicy.None,
					RecycleBinUri = new Uri("http://cloudmirror.example.com/recyclebin"),
					Context = CryptographicBuffer.ConvertStringToBinary($"{ProviderFolderLocations.ServerFolder}->{ProviderFolderLocations.ClientFolder}", BinaryStringEncoding.Utf8),
					AllowPinning = true,
				};

IList<StorageProviderItemPropertyDefinition> customStates = info.StorageProviderItemPropertyDefinitions;
customStates.Add(new StorageProviderItemPropertyDefinition() { DisplayNameResource = "CustomStateName1", Id = 1 });
customStates.Add(new StorageProviderItemPropertyDefinition() { DisplayNameResource = "CustomStateName2", Id = 2 });
customStates.Add(new StorageProviderItemPropertyDefinition() { DisplayNameResource = "CustomStateName3", Id = 3 });

if (!StorageProviderSyncRootManager.IsSupported())
	throw new NotSupportedException();
StorageProviderSyncRootManager.Register(info); // throws exception
```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK Version 10.0.19043

**Comment by drasticactions** [comment]
You should verify this works in a straight WinUI app without MAUI. This doesn't seem like it's MAUI specific.

**Comment by shv07** [comment]
> You should verify this works in a straight WinUI app without MAUI. This doesn't seem like it's MAUI specific.

Yeah, throws the same exception in a simple non-MAUI WinUI 3 application as well.

**Comment by drasticactions** [comment]
> > You should verify this works in a straight WinUI app without MAUI. This doesn't seem like it's MAUI specific.
> 
> Yeah, throws the same exception in a simple non-MAUI WinUI 3 application as well. Is there any alternative/ workaround available for using the methods in MAUI, though?

The methods you're calling are from the WinRT Runtime, and those would be the same ones MAUI would also call if it did, since that's the platform you're running on. 

I would file an issue with WinUI at https://github.com/microsoft/microsoft-ui-xaml and see what they say.

**Comment by shv07** [comment]
Update: Was finally able to make it work in MAUI by adding the extensions to package manifest similar to this [repo](https://github.com/shv07/WinClassicSamplesCS/blob/master/CloudMirrorPackage/Package.appxmanifest)
