### ISSUE TITLE
[Android] Grid columns not correctly calculated when control spans columns and auto column definition is used

### ISSUE THREAD

**Issue by anotherlab** [dotnet/maui#6138]
### Description

I had a `CollectionView` that was ported from a Xamarin.Forms 5 project.  The `DataTemplate` for the `CollectionView` used a 2 column `Grid` and the last row of the grid used a `BoxView` as a row separator. The `BoxView` spanned both columns.  When the `ColumnDefinition` is set to "Auto, *", the second column does not render on Android. It was rendered on Windows and I was not able to test on iOS.  The issue is not specific to the `CollectionView` and I have a demo project that illustrates the problem with just the `Grid` control. If the `ColumnDefinition` is changed to "Auto, Auto" or "Auto, 300", the second column appears, but the formatting does not align itself correctly to the device.

Link to demo project: https://github.com/anotherlab/MauiGridColumnBug

### Steps to Reproduce

Use demo project at https://github.com/anotherlab/MauiGridColumnBug 
or
1. Create a new MAUI app
2. Replace the controls inside the stacklayout in MainPage.xaml with the following

```xaml
<Label Text="Wrong column widths"/>
<Grid ColumnDefinitions="Auto, *"
        RowDefinitions="Auto, auto"
        BackgroundColor="BlanchedAlmond">
    <BoxView HeightRequest="64" WidthRequest="64" BackgroundColor="AliceBlue"/>
    <Grid Grid.Column="1" Padding="0" RowDefinitions="Auto, auto">
        <Label HorizontalOptions="CenterAndExpand"
                Text="Line 1"
                FontSize="18"/>
        <Label Grid.Row="1"
                HorizontalOptions="CenterAndExpand"
                FontSize="24"
                Text="Line 2" />
    </Grid>
    <BoxView HeightRequest="1"
                BackgroundColor="{StaticResource Primary}"
                Grid.ColumnSpan="2"
                Grid.Row="1"
                Margin="40,10,40,6"
                VerticalOptions="End"/>
</Grid>
<Label Text="Correct column widths" Margin="0,20"/>
<Grid ColumnDefinitions="Auto, *"
        RowDefinitions="Auto, auto"
        BackgroundColor="BlanchedAlmond">
    <BoxView HeightRequest="64" WidthRequest="64" BackgroundColor="AliceBlue"/>
    <Grid Grid.Column="1" Padding="0" RowDefinitions="Auto, auto">
        <Label HorizontalOptions="CenterAndExpand"
                Text="Line 1"
                FontSize="18"/>
        <Label Grid.Row="1"
                HorizontalOptions="CenterAndExpand"
                FontSize="24"
                Text="Line 2" />
    </Grid>
</Grid>
```
| Expected output (from WinUI) | Actual output (from Android) |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1191188/163622474-b3716d70-59c6-45cc-bf3e-cca857066e1c.png"  width="200"> | <img src="https://user-images.githubusercontent.com/1191188/163622490-11b53a35-3347-4b5e-bf8d-cef54121458a.png" width="200"> |

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Any Android and Windows Subsystem for Android

### Did you find any workaround?

Instead of using a `BoxView` that spans columns as the row of the `Grid`, the following steps will work for that layout.

1. Place the `Grid` inside a `StackLayout`
2. Remove the `BoxView` from the `'Grid` and place it after the `Grid` in the `StackLayout`
3. Remove the `Grid.*` properties from the `BoxView`

**Comment by kristinx0211** [comment]
verified repro on Android 11.

**Comment by Nk54** [comment]
Hello, I'm having nightmares to fix every UI with ColumnSpan / RowSpan : it doesn't work on Windows, Android (havn't tested on iOS).

I have an app with 20 pages created in Xamarin Forms. Not a single page is rendered well on MAUI. I expected more from a RC.

**Comment by hartez** [comment]
This is fixed with the latest in main - should be available in RC2 at the earliest, RC3 at the latest.
