### ISSUE TITLE
[ANDROID] Label with FormattedText does not render properly

### ISSUE THREAD

**Issue by jgold6** [dotnet/maui#6141]
### Description

Label with FormattedText does not render properly on Android only

Other platforms tested: Windows and iOS
Not tested: macOS

A couple of observations:
1. If FontAttributes are set for the 2nd Span, the text for the 2nd Span will not show, but if you delete and re-add the 2nd Span with Hot Reload enabled, it will show. 

2. If the entire Label has its HorizontalTextAlignment="Center", the first Span starts off screen to the left, and 2nd Span is somewhat centered in the remaining space, if it shows at all. (Centering work fine when not using FormattedText)

Repro project:
[FormattedText.zip](https://github.com/dotnet/maui/files/8498232/FormattedText.zip)
 

### Steps to Reproduce

1. Open attached test project and run on Android emulator (I tested on Pixel 5 API29 and 30 emulators)

Expected behavior:
Should see on screen, centered: "You should see bold text following this **bold text**"

Actual behavior:
Screen shows: "You should see bold text following this" 
and it is not centered and the start is cut off.

Further, if you remove and re-add the 2nd span in the XAML, with Hot Reload enabled, it will show, but centering will still be off and start of first Span text is still cut off. 

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 and 11 (API 29 and 30)

**Comment by kristinx0211** [comment]
verified repro on Android 11.
