### ISSUE TITLE
Android is not just Phones Feature requests

### ISSUE THREAD

**Issue by DavidH102** [dotnet/maui#6144]
### Description

If at all possible I would really appreciate the ability to make MAUI apps that can also not just only run on Android phones, but also on Android Auto, Android TV(Inc Amazon Fire), WearOS, Apple CarPlay, Apple Watch.

these endpoints are really where cutting edge development is happerning in terms of streaching out the reach of software devs.

### Public API Changes

NA

### Intended Use-Case

To convince people to allow use .NET in there company for there next project.

**Comment by jfversluis** [comment]
I think a few of these will already work although maybe the templates aren't there right now. I think we've got our hands full making .NET MAUI work for the platforms that we are supporting today. Also, I'd love to see more detail in a feature request to learn more about the why and how you see this happening.

Closing this for now to not keep lingering, not actionable issues in the repo, let's revisit some time in the future.
