### ISSUE TITLE
Microsoft.Maui.Essentials unavailable in VS 2022 Preview 3.0

### ISSUE THREAD

**Issue by tbrabec** [dotnet/maui#6146]
### Description

Microsoft.Maui.Essentials unavailable in Visual Studio 2022 Preview 3.0.

### Steps to Reproduce

1. Install Visual Studio 2022 Version 17.2.0 Preview 3.0 with MAUI support
2. Create a new project .NET MAUI App (Preview)
3. Add a reference to the top of MainPage.xaml..cs file: **using Microsoft.Maui.Essentials;**
4. Build the solution

**Result:**
Error CS0234 **The type or namespace name 'Essentials' does not exist in the namespace 'Microsoft.Maui'** (are you missing an assembly reference?)
MauiApp1 (net6.0-android), MauiApp1 (net6.0-ios), MauiApp1 (net6.0-maccatalyst), MauiApp1 (net6.0-windows10.0.19041)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

net6.0-android, net6.0-ios, net6.0-maccatalyst, net6.0-windows10.0.19041

### Did you find any workaround?

No known workaround.

### Relevant log output

```shell
MainPage.xaml.cs(1,22,1,32): error CS0234: The type or namespace name 'Essentials' does not exist in the namespace 'Microsoft.Maui' (are you missing an assembly reference?)
```

**Comment by drasticactions** [comment]
The namespaces changed for Essentials, it's listed here, https://github.com/dotnet/maui/wiki/Migrating-to-RC1#microsoftmauiessentials-updates

**Comment by tbrabec** [comment]
I should have been prepared for another breaking change. Thank you.
