### ISSUE TITLE
Label Shadow not working correctly on Windows

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#6150]
### Description

The label shadow does not render at the location of the label neither does it render in the right size

![image](https://user-images.githubusercontent.com/2603287/163659236-f930ab5f-5482-4c9e-a289-011e86145f99.png)

### Steps to Reproduce

Create a label : the example in the image above is in a template for a collectionView

```
<Label 
                        Style="{StaticResource FoodCategoriesLabel}"
                        Text="{Binding Name}" >
                            <Label.Shadow >
                                <Shadow Offset="0,0"
                                Opacity="1" 
                                Radius="2" Brush="Black" >
                                </Shadow>
                            </Label.Shadow>
                        </Label>
```

Expected :The Shadow should appear underneath the label with the same character size

Result: see image above

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Works on Android not windows.

### Affected platforms

Windows

### Affected platform versions

Windows 11 Pro 22000.408

### Did you find any workaround?

No

**Comment by shimingsg** [comment]
@pierre01 , could you share the style of FoodCategoriesLabel which can help us to reproduce this issue?

**Comment by pierre01** [comment]
` <Style x:Key="FoodCategoriesLabel" TargetType="Label">
     <Setter Property="TextColor" Value="#FFFFFF" />
     <Setter Property="FontFamily" Value="DancingScriptRegular" />
     <Setter Property="FontSize" Value="48"  />
     <Setter Property="FontAttributes" Value="Bold"  />
     <Setter Property="HorizontalTextAlignment" Value="Center" />
     <Setter Property="VerticalTextAlignment" Value="Center" />
 </Style>
`

**Comment by shimingsg** [comment]
@pierre01 , sorry I don't have windows 11.
please see my demo that seems the shadow works fine, my environment is 
**VS: 17.3.0 Preview 1.0 [32417.43.main]**
Windows: Windows 10 10.0.19044 N/A Build 19044
![image](https://user-images.githubusercontent.com/20982341/164177374-4632596b-ded5-44fa-987b-a5c15bf9c25c.png)

here is my demo project for your reference, I'd like to suggest to verify if the latest VS has the same issue on your environment.
[MauiApp13.zip](https://github.com/dotnet/maui/files/8519588/MauiApp13.zip)

**Comment by pierre01** [comment]
Compiling your code I get an error: 1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.300-rc.1.5355\targets\Microsoft.Maui.Resizetizer.targets(571,9): error : ApplicationId 'com.companyname.mauiapp99875' was not a valid GUID. Windows apps use a GUID for an application ID instead of the reverse domain used by Android and/or iOS apps.

**Comment by pierre01** [comment]
![image](https://user-images.githubusercontent.com/2603287/164200115-5e0e982c-3c02-46de-a79d-27b257ff0e95.png)
 Yes it is...
[MauiApp13.zip](https://github.com/dotnet/maui/files/8520354/MauiApp13.zip)
.
