### ISSUE TITLE
Cannot swipe on Windows (with mouse)

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#6152]
### Description

If I add an SwipeView on a page, I cannot use this on Windows. If I try to swipe it with a mouse nothing happens. Is only touch supported?

[Demo code](https://github.com/pekspro/MauiIssues/tree/NoWindowsSwipe)

### Steps to Reproduce

1. Create a new MAUI project.
2. Add the following code on the main page:

            <SwipeView>
                <SwipeView.LeftItems>
                    <SwipeItems>
                        <SwipeItem Text="Favorite" BackgroundColor="LightGreen" />
                        <SwipeItem Text="Delete" BackgroundColor="LightPink"
                       />
                    </SwipeItems>
                </SwipeView.LeftItems>
                <Grid HeightRequest="60" BackgroundColor="LightGray">
                    <Label Text="Swipe right" HorizontalOptions="Center" VerticalOptions="Center" />
                </Grid>
            </SwipeView>

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.17763.0

### Did you find any workaround?

No workaround found.

> VS bug [#1779663](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1779663)

**Comment by DoubleDBE** [comment]
Can confirm, having the same issue when using `CarouselView`.

Weirdly enough using a scroll wheel (kind of) works.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows with above project.

**Comment by rogerbriggen** [comment]
I can confirm it is also not working for me on Windows 10 and Windows 11.
But it does work if you run the Android APK on Windows Subsystem for Android on Windows 11.... (just if it is still not supported by WinUI...)

**Comment by liplum** [comment]
I can repoduce this issue. Visual Studio 17.3.0 Preview 1.1. It can work on Andriod but not Windows side.
```
<CollectionView> // Vertical Orientation
  <DataTemplate>
        <SwipeView>
            ...
        </SwipeView>
   </DataTemplate>
</CollectionView>
```

**Comment by deaa-aldeen** [comment]
SwipeView doesn't work on windows with mouse /VS2022 Version 17.3.0 Preview 4.0

**Comment by TPullen21** [comment]
I'm also having the same issue with SwipeView not working on Windows 10 with Mouse. VS 2022 Professional Version 17.3.0 Preview 4.0

**Comment by deaa-aldeen** [comment]
update::
SwipeView doesn't work on windows10 with mouse / VS2022 Version 17.3.0 Preview 5.0

**Comment by donbing** [comment]
same on win 11 with 17.3.0 Preview 4.0

**Comment by damonpkuml** [comment]
same on win 10 with 17.3.0

**Comment by jsuarezruiz** [comment]
SwipeView in MAUI (Windows) makes use of the SwipeControl control available in WinUI https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swipecontrol
The behavior you describe is the expected and there are requests to make it compatible with mouse: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/1828

We need to sync with WinUI team to allow this kind of interacction, or, replace the SwipeControl by a custom MauiSwipeView WinUI UserControl.

**Comment by jsuarezruiz** [comment]
@Redth Can we organize a meeting with WinUI Team to review this topic?. Thanks.

**Comment by pekspro** [comment]
I just want to remind on this issue too: https://github.com/dotnet/maui/issues/7757

While I would love to see mouse support for swipe, it is not very useful if it causes crashes :-)

**Comment by sinsedrix** [comment]
I tried this workaround, but SwipeItems don't show:
```
<SwipeView.GestureRecognizers>
      <DragGestureRecognizer DropCompleted="DragGestureRecognizer_DropCompleted" />
</SwipeView.GestureRecognizers>
```

```
    private void DragGestureRecognizer_DropCompleted(object sender, DropCompletedEventArgs e)
    {
        ((sender as DragGestureRecognizer).Parent as SwipeView).Open(OpenSwipeItem.RightItems);
    }
```

@jsuarezruiz  Any idea to have it work until the mouse get compatible?

**Comment by TamerIrdais** [comment]
Any update on this issue? swipe gesture is not working on Windows.
This is critical issue and we at least need workaround.

**Comment by TamerIrdais** [comment]
> SwipeView in MAUI (Windows) makes use of the SwipeControl control available in WinUI https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swipecontrol The behavior you describe is the expected and there are requests to make it compatible with mouse: [CommunityToolkit/WindowsCommunityToolkit#1828](https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/1828)
> 
> We need to sync with WinUI team to allow this kind of interacction, or, replace the SwipeControl by a custom MauiSwipeView WinUI UserControl.

@jsuarezruiz Any update or time estimate from the WInUI team on when this is going to be fixed? we need that fix ASAP.

**Comment by IndianaGary** [comment]
I can confirm that this problem still exists on 17.4.0 Preview 5 for Maui 7.0 Preview.

**Comment by davepruitt** [comment]
I can confirm this problem still exists on Windows 10, VS 2022 version 17.4.2, .Net MAUI 7.0

**Comment by fscopel** [comment]
Using the latest Microsoft.Maui.Controls (7.0.52), VS 2022 17.4.3, .NET 7.0.101 still broken.

**Comment by rctec-at** [comment]
@jsuarezruiz you may have some information about a estimated timeframe when this problem will be solved? 

unfortunally there at the moment are a lot of tickets where no information is provided to the community what so ever..
we depend on such features to go live. This not talking with us about brings problems with our clients, since we cant give them timeframes.

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz you may have some information about a estimated timeframe when this problem will be solved?
> 
> unfortunally there at the moment are a lot of tickets where no information is provided to the community what so ever.. we depend on such features to go live. This not talking with us about brings problems with our clients, since we cant give them timeframes.

Sure thing. SwipeView in MAUI (Windows) makes use of the SwipeControl control available in WinUI https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swipecontrol
The actual behavior is the expected and there are requests to make it compatible with mouse: https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/1828

We have some conversations with the WinUI team. If SwipeControl does have mouse support we will keep SwipeControl. In case of not being able to have it before the .NET 8 timeframe we will use this PR creating our own implementation. https://github.com/dotnet/maui/pull/11229 (We need to complete this implementation if finally we choose this approach)

It's a decision that depends on multiple teams etc, but I hope to be able to share more specific details soon.

**Comment by rctec-at** [comment]
Thank you @jsuarezruiz. 
I am looking forward to the details here. (would be great if you would tag me then).

**Comment by Esperadoce** [comment]
any update about this ?

**Comment by HobDev** [comment]
facing the issue on windows 11 and visual studio 17.6.2

**Comment by DevFrogora** [comment]
I hope Bill gate will implement swipe features for windows in maui

**Comment by dimustriz** [comment]
Still doesn't work. Just commented to subscribe to the issue.

**Comment by hartez** [comment]
The native [Swipe controls on Windows](https://learn.microsoft.com/en-us/windows/apps/design/controls/swipe) only support touch interactions. For contextual actions in a desktop application using a pointer (e.g., a mouse), a [Context Menu should be used](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/context-menu). 

This is by design on Windows, and at the moment we do not have plans to make SwipeViews pointer-enabled on the desktop. (On macOS, they _do_ function with the mouse, because the mouse is a proxy for touch interactions and macOS does not provide any native touch interface. However, context menus are still the better option for desktop applications.)

We're [updating the documentation](https://github.com/dotnet/docs-maui/pull/1594) to make it more clear that SwipeView does not work with the mouse on Windows.

**Comment by IndianaGary** [comment]
It may be "by design" on Windows, but given the legacy behavior from WPF and Win32, it's by poor design...
Just sayin'

**Comment by davepruitt** [comment]
I agree. If this is "by design", it is very poor design. This is something a summer intern could implement in a couple of weeks.
