### ISSUE TITLE
System.AccessViolationException when using SwipeView in a CollectionView on Windows

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#6153]
### Description

If a SwipeView is used in a CollectionView, an `System.AccessViolationException` is thrown on Windows this message.

    Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

[Demo project](https://github.com/pekspro/MauiIssues/tree/SwipeOnWindowsCrash)

### Steps to Reproduce

1. Create a new MAUI app.
2. Add this on the main page:

```
    <CollectionView 
                x:Name="ItemsList"
                ItemSizingStrategy="MeasureFirstItem"
                >
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <SwipeView>
                    <SwipeView.LeftItems>
                        <SwipeItems>
                            <SwipeItem Text="Favorite" BackgroundColor="LightGreen" />
                            <SwipeItem Text="Delete" BackgroundColor="LightPink"
                                />
                        </SwipeItems>
                    </SwipeView.LeftItems>
                    <StackLayout HeightRequest="80">
                        <Label Text="Swipe me!" />
                    </StackLayout>
                </SwipeView>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
```

3. Initialize the view in the constructor:

``` C#
	public MainPage()
	{
		InitializeComponent();

		ItemsList.ItemsSource = new string[] { "Hello", "World" }; 
	}
```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Windows 10.0.17763.0

### Did you find any workaround?

No workaround.

**Comment by FrozDark** [comment]
I have also the same problem using SwipeView

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows with above project. 
![image](https://user-images.githubusercontent.com/97647558/163741088-0a9a8172-31f2-418a-bad4-c11eb6e357f0.png)
