### ISSUE TITLE
Swipe not working when SwipeView is used as base element

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#6154]
### Description

If `SwipeView` is used as base element in a view, and this view is used in a ```DataTemplate``` source in a `CollectionView` swipe doesn't work, at least on Android (it triggers a [crash on Windows](https://github.com/dotnet/maui/issues/6153)).

[Demo project](https://github.com/pekspro/MauiIssues/tree/SwipeNotSupportedAsBaseInView)

### Steps to Reproduce

1. Create a new Maui application.
2. Add ItemView.xaml:

``` XAML
    <SwipeView 
                 xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 x:Class="MauiIssues.ItemView"
                 HeightRequest="80"        
        >

        <SwipeView.LeftItems>
            <SwipeItems>
                <SwipeItem Text="Favorite" BackgroundColor="LightGreen" />
                <SwipeItem Text="Delete" BackgroundColor="LightPink" />
            </SwipeItems>
        </SwipeView.LeftItems>

        <Label Text="Swipe me!" />
    </SwipeView>
```
3. Add ItemView.cs:
``` C#
    namespace MauiIssues
    {
        public partial class ItemView 
        {
            public ItemView()
            {
                InitializeComponent();
            }
        }
    }
```
4: Add `CollectionView` on MainPage:
``` XAML
    <CollectionView 
                x:Name="ItemsList"
                ItemSizingStrategy="MeasureFirstItem"
                >
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <r:ItemView />
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
```
5: Initialize the list in the constructor:
``` C#
	namespace MauiIssues;

	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();

			ItemsList.ItemsSource = new string[] { "Hello", "World" }; 
		}
	}
```

Run the application on Android and try to swipe.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10, I was *not* able test on other platforms

### Did you find any workaround?

Use `SwipeView` directly in the `DataTemplate` instead, like in this issue https://github.com/dotnet/maui/issues/6153.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android. Sample Project: [6154.zip](https://github.com/dotnet/maui/files/8503012/6154.zip)

**Comment by RobertoGFilho** [comment]
On windows plataform this crash below happen : 

![image](https://user-images.githubusercontent.com/68563526/164550175-fa68e1fa-e3d4-49d3-95cb-b8ad7628e9b4.png)

**Comment by davidortinau** [comment]
Perhaps related to #6018 where SwipeView is used as root element

**Comment by jsuarezruiz** [comment]
Tested in main branch and Windows in no longer crashing after merge https://github.com/dotnet/maui/issues/6018

**Comment by pekspro** [comment]
I've updated sample application to .NET 7. The same issue remains.

**Comment by Enbi-Zhang** [comment]
Verified repro on Windows 11 with 17.6.0 Preview 7.0. Repro project 
[MauiIssues-SwipeNotSupportedAsBaseInView.zip](https://github.com/dotnet/maui/files/11460052/MauiIssues-SwipeNotSupportedAsBaseInView.zip)
