### ISSUE TITLE
FlyoutPage Navigation Pane

### ISSUE THREAD

**Issue by ctubig** [dotnet/maui#6157]
### Description

FlyoutPage Navigation Page cannot be resized and change its background color. I noticed some ugly gaps.
![image](https://user-images.githubusercontent.com/24967122/163670696-0605acf1-1fc2-4c87-b65c-ffa8fd54a43b.png)

### Steps to Reproduce

1. Create FlyoutPage

### Version with bug

Preview 14

### Last version that worked well

Preview 14

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows

### Did you find any workaround?

No

### Relevant log output

```shell
None
```

**Comment by Fabi** [comment]
Broken since 3 previews now

**Comment by kristinx0211** [comment]
@ctubig Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!
