### ISSUE TITLE
Nested FlexLayout presentation error

### ISSUE THREAD

**Issue by SchreinerK** [dotnet/maui#6161]
### Description

I don't see the nested FlexLayout with its content. 

![image](https://user-images.githubusercontent.com/4082338/163682325-b2b5cfec-8b67-48d7-931f-e5cc8134dde4.png)

I use Visual Studio 2022 Version 17.2.0 Preview 3.0 

### Steps to Reproduce

- Create new .NET MAUI app.
-  in MainPage VerticalStackLayout add a FlexLayout with some Buttons
- Start debugging with Android Emulator or Windows

 The FlexLayout with its buttons is not visible!
 
 I would expect  a FlexLayout  with a height of the buttons or if wrapped a height of number of rows * height of buttons.
So its seems the height is not calculated.
(BTW the width is also not calculated because HorizontalOptions Start,Center,End works also not as expected)

If I set the HeightRequested to a specific value, I see the content with the specified height.
If I set the MinimimHeightRequested to a specific value, I see the content with te specified height but it does not grow on wrap. Height is always MinimimHeightRequested 
If I set the MaximumHeightRequest to a specific value I see the content with te specified height but not with the minimum required height of the buttons. Height is always MaximumHeightRequest.
 
[MauiApp6.zip](https://github.com/dotnet/maui/files/8500276/MauiApp6.zip)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Microsoft Windows [Version 10.0.19044.1586], Android Emulator  Pixel 5 API 30.

**Comment by kristinx0211** [comment]
verified on Android 11 and windows. The FlexLayout with its buttons is not visible.

**Comment by davidortinau** [comment]
#3852 related

**Comment by kristinx0211** [comment]
verified still repro on Android 11 and windows with 17.3.0 Preview 2.0 [32507.29.main].

**Comment by Redth** [comment]
Seems to be ok now:

![image](https://user-images.githubusercontent.com/271950/169059184-59420ff5-0000-4441-872c-009edf0516fb.png)

![image](https://user-images.githubusercontent.com/271950/169059699-99064792-8377-472d-92ed-7b92efb09147.png)

![image](https://user-images.githubusercontent.com/271950/169060553-27159f6c-d333-4c1a-8d26-8d478ff476ab.png)

**Comment by SchreinerK** [comment]
Nice. :-) 
In which VS Preview version will this fix be included?
