### ISSUE TITLE
ToolbarItem with FontImageSource has different colors on Android and Windows

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#6162]
### Description

If you add a toolbar item with and FontImageSource without specifiying color, the image is drawn with white on Windows (same as the background!) and blue on Android.

Windows (with mouse pointer hovering):
![image](https://user-images.githubusercontent.com/3163293/163685680-7ded356f-c63d-493f-a736-b259e7b7ecca.png)

Android:
![image](https://user-images.githubusercontent.com/3163293/163685685-ecb41f6f-9768-43fb-be55-3f1961042fc0.png)

[Demo project](https://github.com/pekspro/MauiIssues/tree/ToolbarIconColorIssue)

### Steps to Reproduce

1. Create a new MAUI app.
2. Add this in the main page:

``` XAML
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="You won a million!">
            <ToolbarItem.IconImageSource>
                <FontImageSource Glyph="$" Size="32" />
            </ToolbarItem.IconImageSource>
        </ToolbarItem>
    </ContentPage.ToolbarItems>
```

Run this on Windows and Android.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.17763.0, Android 10

### Did you find any workaround?

Using the Color property could be used to force a specific color.

**Comment by kristinx0211** [comment]
verified repro on android 11 and windows with vs 17.3.0 Preview 1.0 [32413.517.main].

**Comment by pekspro** [comment]
This is no longer an issue. Same color is used both in Windows and Android. Tested both in .NET 6 and 7.
