### ISSUE TITLE
Search handler display inconsistent on android

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#6170]
### Description

The search handler does not display correctly on android

### Steps to Reproduce

Create a search handler with an icon 
Set the handler property
**SearchBoxVisibility = SearchBoxVisibility.Collapsible;**
When running the header displays 2 icons
![image](https://user-images.githubusercontent.com/2603287/163705067-5c245ffc-c8a4-4764-84f3-d5fb3056889f.png)

After clicking on any of the 2 icons, the search opens

![image](https://user-images.githubusercontent.com/2603287/163705090-f33b8e7e-55df-4b45-8169-f1d9b4768912.png)

Expected result:

Only one icon displays when collapsed

Also

 if you set
**SearchBoxVisibility = SearchBoxVisibility.Expanded;**

When running the header does not display any icon

![image](https://user-images.githubusercontent.com/2603287/163705138-549f7b82-ec44-483f-ac47-f96bbffd8c2c.png)

Expected the search icon should be displayed next to the input box.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 API 30 and over

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
@pierre01 Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by pierre01** [comment]
https://github.com/pierre01/SearchHandlerAndroidBug/tree/development/SearchHandlerAndroidBug
![image](https://user-images.githubusercontent.com/2603287/163975285-43757915-e77d-4ea6-9a1f-0e09dd3f1c6b.png)

**Comment by pierre01** [comment]
Please note that I can't reproduce the issue on Windows because Windows does not display any search handler.

**Comment by VincentBu** [comment]
not repro on Android 11 emulator. (I'm using vs 17.3.0 Preview 1.0 [32418.120.main])
![image](https://user-images.githubusercontent.com/44959937/164180666-1309cc2a-8a67-4996-b650-2a2ff72ecdbd.png)

**Comment by pierre01** [comment]
I am using VS Version 17.2.0 Preview 4.0 and MAUI RC 1.5355
