### ISSUE TITLE
GraphicsView's PanGestureRecognizer not working on Windows

### ISSUE THREAD

**Issue by GabrieleMessina** [dotnet/maui#6173]
### Description

I think PR #5548 broke GraphicsView's PanGestureRecognizer on Windows, i also tried it on Android and it seems to work fine.

### Steps to Reproduce

To reproduce just use GraphicView with a PanGestureRegognizer:
``` XAML 
<GraphicsView
  HeightRequest="500"
  WidthRequest="500" >
    <GraphicsView.GestureRecognizers>
        <PanGestureRecognizer PanUpdated="OnPanUpdated" />
    </GraphicsView.GestureRecognizers>
</GraphicsView>
```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 13

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.19041

**Comment by VincentBu** [comment]
repro on Windows. `OnPanUpdated` isn't called when doing pan gesture.
