### ISSUE TITLE
The managed-implementation of HttpClientHandler doesn't work on Android

### ISSUE THREAD

**Issue by miao17game** [dotnet/maui#6174]
### Description

I want to build a app witch works as a webdav client, but the native implementation of HttpClienthandler on Android (AndroidClientHandler) doesn't work because 'PROPFIND' is an invalid method of HttpURLConnection ( because AndroidClienthandler use it inside ), so I have no choice but  the managed implementation (HttpClientHandler).
However, when I use HttpClientHandler in my Maui App with option in project config file, an error (Object reference not set to an instance of an object) is thrown from HttpClientHandler.StartSync(...).

### Steps to Reproduce

1. Init a new Maui repo
2. Build WebDavService with HttpClient and HttpClientHandler
3. Open project setting and select 
![image](https://user-images.githubusercontent.com/17511048/163718171-6b95958a-0e8c-474a-bc9a-b1d006ddf892.png)
4. Add button to invoke WebDavService.Propfind
5. Click and crashed.

Demo: maybe you can take a look at my [file on this branch](https://github.com/miao17game/BigmogicianDriveControl/blob/debug/webdav-client/BigmogicianDriveControl/Services/WebDAVService.cs).

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, maybe lower

### Did you find any workaround?

No... I can use WebRequest to build another HttpClienthandler,but the WebRequest is deprecated alreay 0.0 

### Relevant log output

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Object reference not set to an instance of an object.
[mono-rt]    at BigmogicianDriveControl.Services.WebDavService.SetClientAfterTested(String domain, Int32 port, String path, String account, String password) in C:\Development\MAUI\BigmogicianDriveControl\BigmogicianDriveControl\Services\WebDAVService.cs:line 35
[mono-rt]    at BigmogicianDriveControl.Pages.ServerSettingsPage.Button_Clicked(Object sender, EventArgs e) in C:\Development\MAUI\BigmogicianDriveControl\BigmogicianDriveControl\Pages\Settings\ServerSettingsPage.xaml.cs:line 152
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
[HostConnection] createUnique: call
[HostConnection] HostConnection::get() New Host Connection established 0x723a4c29f010, tid 1490
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
[EGL_emulation] tid 1523: eglQuerySurface(1434): error 0x3001 (EGL_NOT_INITIALIZED)
```

**Comment by miao17game** [comment]
Anyway, I try fork the AndroidHttpClientHandler in my repo, and set the options to default, the problem is disappeared.

**Comment by steveisok** [comment]
@simonrozsival Can you please look into why this isn't working with SocketsHttpHandler?  

It's important to note that our underlying crypto API's integrate with Android native API's.  The integration wasn't 1-1 and mileage may vary based upon API level.

**Comment by simonrozsival** [comment]
I've been able to reproduce the issue with a new MAUI project. When the `HttpClient implementation` setting for `net6.0-android` is set to `Managed` in VS, the value of `RuntimeSettingParser.QueryRuntimeSettingSwitch("System.Net.Http.UseNativeHttpHandler", false);` used in the constructor of `HttpClientHandler` to determine whether to use the native or managed handler is `true` even though it should be `false`. When the `Mono.Android` `Android.Runtime.AndroidEnvironment.GetHttpMessageHandler()` function is called, it tries to create an instance of the handler through reflection and it uses the value of the `XA_HTTP_CLIENT_HANDLER_TYPE` env variable. The value of the env variable is `System.Net.Http.HttpClientHandler` and when `Type.GetType("System.Net.Http.HttpClientHandler", false)` is called from within `Mono.Android` it cannot find the class in the current assembly and it returns `null`. The `HttpClientHandler` is in a state where both `_socketsHandler` and `_nativeHandler` are both `null`.

The root of the problem appears to be that `System.Net.Http.UseNativeHttpHandler` is `true` when it should be `false` because it doesn't reflect the VS setting.

**Comment by simonrozsival** [comment]
I think what we need to do is to modify https://github.com/xamarin/xamarin-android/blob/main/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L94 and set the default value based on the value of `AndroidHttpClientHandlerType`.

**Comment by jonathanpeppers** [comment]
After some discussion on this issue, we think the above setting needs to be removed from the Project Options page. We're tracking this internally [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1530132).

@miao17game to understand your issue further, are you trying to use a custom class for `AndroidHttpClientHandlerType`? Or trying to workaround a problem?

Using your own class for `AndroidHttpClientHandlerType` you would need to edit the `.csproj` to set the assembly name such as: `MyNamespace.MyType, MyAssembly`. You might also need to prevent the linker from removing this type.

Let me know if you're still hitting this with MAUI RC 2 (shipped today), and more info on what you're trying to do. Thanks!

**Comment by miao17game** [comment]
> After some discussion on this issue, we think the above setting needs to be removed from the Project Options page. We're tracking this internally [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1530132).
> 
> @miao17game to understand your issue further, are you trying to use a custom class for `AndroidHttpClientHandlerType`? Or trying to workaround a problem?
> 
> Using your own class for `AndroidHttpClientHandlerType` you would need to edit the `.csproj` to set the assembly name such as: `MyNamespace.MyType, MyAssembly`. You might also need to prevent the linker from removing this type.
> 
> Let me know if you're still hitting this with MAUI RC 2 (shipped today), and more info on what you're trying to do. Thanks!

**Comment by miao17game** [comment]
ok, i will try these solutions with rc2.

**Comment by miao17game** [comment]
I wrote a custom HttpClientHandler using HttpWebRequest, which can temporarily solve my needs.

**Comment by jonathanpeppers** [comment]
@miao17game do you still have a problem if you:
1. Don't use `AndroidHttpClientHandlerType` at all
2. Use the default settings

The exception you're getting above would be caused by the use of `AndroidHttpClientHandlerType`.

**Comment by miao17game** [comment]
> @miao17game do you still have a problem if you:
> 
> 1. Don't use `AndroidHttpClientHandlerType` at all
> 2. Use the default settings
> 
> The exception you're getting above would be caused by the use of `AndroidHttpClientHandlerType`.

No, there is no problem if i do this, the app will not crash again with NullReferenceException.

But in my case, I can't use the platform implementation of HttpClientHandler (AndroidCLientHandler) on Android to achieve my needs, because I need to set HttpMethod as 'Propfind', which is not supported by Android's HttpURLConnection. 
So if I can use the .NET platform implementation of HttpClienthandler as before( old version of .NET), I can replace the Android implementation to do my work. Anyway, I've wrote my custom HttpClientHandler using HttpWebRequest, which can temporarily solve my needs. 

So, is there a follow-up plan on how to access the original HttpClientHandler of the .NET platform on the Android platform?

**Comment by jonathanpeppers** [comment]
You could try putting `<UseNativeHttpHandler>false</UseNativeHttpHandler>` in your project.

To override the default:

https://github.com/xamarin/xamarin-android/blob/e50b457fa236e6fc127eadc0cfa527934a03e7de/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L94

The two options in .NET 6 are really `$(UseNativeHttpHandler)` true or false.

**Comment by miao17game** [comment]
> You could try putting `<UseNativeHttpHandler>false</UseNativeHttpHandler>` in your project.
> 
> To override the default:
> 
> https://github.com/xamarin/xamarin-android/blob/e50b457fa236e6fc127eadc0cfa527934a03e7de/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L94
> 
> The two options in .NET 6 are really `$(UseNativeHttpHandler)` true or false.

wow, i think my issue is solved by this solution, thanks !!

**Comment by jonathanpeppers** [comment]
Thanks, let us know if you run into anything else!
