### ISSUE TITLE
Microsoft.EntityFrameworkCore.Tools

### ISSUE THREAD

**Issue by RobertoGFilho** [dotnet/maui#6175]
### Description

When i try to add Microsoft.EntityFrameworkCore.Tools from Manage Nuget Package an error happen on Windows version. See video:

https://user-images.githubusercontent.com/68563526/163718797-1e604ebe-8328-4ae2-968b-32ba2218b5e1.mp4

### Steps to Reproduce

1. Create a new MAUI project
2. Add Microsoft.EntityFrameworkCore.Tools on Solution

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17763.0

**Comment by drasticactions** [comment]
This is a WinUI bug

![image](https://user-images.githubusercontent.com/898335/163730349-21c1e2a8-df96-4eec-838c-e830d6b4ec16.png)

If you make a WinUI Project without MAUI and add that Nuget, you get the same error. I would redirect this issue to https://github.com/Microsoft/microsoft-ui-xaml or https://github.com/dotnet/efcore.
