### ISSUE TITLE
IJSRuntime throw error in MAUI Blazor Hybrid App

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#6176]
### Description

Here is my program file

```
 public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .RegisterBlazorMauiWebView()
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                });

            builder.Services.AddBlazoredLocalStorage(config =>
                config.JsonSerializerOptions.WriteIndented = true
            );

            builder.Services.AddTransient<ClientTokenHttpHandler>();

            builder.Services.AddBlazorWebView();
            builder.Services.AddSingleton<WeatherForecastService>();
         
           

            var options = new JsonSerializerOptions()
            {
                // PropertyNamingPolicy = JsonNamingPolicy.,
                WriteIndented = true,
                PropertyNameCaseInsensitive = true,
            };

            var url = "https://getinline.net/";
            var setting = new RefitSettings
            {
                ContentSerializer = new SystemTextJsonContentSerializer(options)
            };

            builder.Services.AddRefitClient<IApplicationApi>(setting)
            .ConfigureHttpClient(c =>
            {
                c.BaseAddress = new System.Uri(url);
            })
            .AddHttpMessageHandler<ClientTokenHttpHandler>();


            builder.Services.AddScoped<ICountryDropDownDataService, CountryDropDownService>();
            builder.Services.AddScoped<ILoginService, LoginService>();

            builder.Services.AddOptions(); //ToDo find out why this one is needed
            builder.Services.AddAuthorizationCore();

            builder.Services.AddScoped<CustomAuthenticationStateProvider>();
            builder.Services.AddScoped<AuthenticationStateProvider>(provider => provider.GetRequiredService<CustomAuthenticationStateProvider>());

            return builder.Build();
        }
```

Here is the clienthandler.cs

```
      public class ClientTokenHttpHandler : DelegatingHandler
	{
		private readonly ILogger<ClientTokenHttpHandler> logger;
		private readonly IJSRuntime _JsRuntime;

		public ClientTokenHttpHandler(ILogger<ClientTokenHttpHandler> logger, IJSRuntime JsRuntime)
		{
		    this.logger = logger;
			_JsRuntime = JsRuntime;
		}

		protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
		{

			var token = await _JsRuntime.InvokeAsync<string>("localStorage.getItem", "AuthToken");
			if(token == null)
            {
				token = "Token is Null";

            }

			//await _JsRuntime.InvokeAsync<string>("localStorage.setItem", "AuthToken","Value was set by program");

			//request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

			request.Headers.Add("Authorization", "Bearer " + token);
			return await base.SendAsync(request, cancellationToken);
		}

	}
```

![2022-04-17_10-59-14](https://user-images.githubusercontent.com/3267605/163722772-f477beb5-69c1-49f2-8f4d-437129405c19.jpg)
![2022-04-17_11-00-51](https://user-images.githubusercontent.com/3267605/163722773-057a87af-029d-4e81-83e2-f43a62c11fc8.jpg)

### Steps to Reproduce

Screen shots attached

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

how do i get this info ?

### Did you find any workaround?

No

**Comment by nssidhu** [comment]
This is a blocker for me unless i re-write the API calls in a different way.
The same code when used in Blazor wasm works perfectly fine.

**Comment by v-longmin** [comment]
Verified repro on windows & Android 12.0 -API31 with VS 17.2.0 Preview 2.1 [32317.152].  Repro project:
[MAUI-RefItIssue-master.zip](https://github.com/dotnet/maui/files/8503921/MAUI-RefItIssue-master.zip)

**Comment by TanayParikh** [comment]
@nssidhu, can you please confirm if you're still seeing this issue on the latest RC1 release? If so, can you please provide a **minimal** repro so we may investigate further? A minimal repro should only contain code which is absolutely required to reproduce the issue, I recommend starting with a `dotnet new maui-blazor` application and seeing if the issue can be reproduced.

**Comment by TanayParikh** [comment]
I did some basic validation on my end, and it's not just a matter of `localStorage.getItem` returning null, the framework is able to successfully handle that scenario.

**Comment by javiercn** [comment]
The issue here is the same as https://github.com/dotnet/aspnetcore/issues/25758, with the only difference that here it is using IJSRuntime and on the tracking issue is using NavigationManager.

The solution will be the same in both cases, which will be to provide a way to access these scoped services through an abstraction similar to IHttpContextAccessor
