### ISSUE TITLE
Switch control differences

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#6177]
### Description

The switch control in Windows is sufficiently different from the Android (and, I'd guess ios) one that it's difficult to use in a cross-platform project.

It's also different enough from the Xamarin implementation that it's difficult to migrate.

### Steps to Reproduce

1. Unzip the project in [Simple-Toggle.zip](https://github.com/dotnet/maui/files/8502013/Simple-Toggle.zip)
 2. Compile and run it in Android, you should see this (which is also what the Xamarin version looks like): 
 3. ![Simple-Toggle-Android](https://user-images.githubusercontent.com/12423046/163723695-4005854b-8cae-416f-a1d1-44948ac3ba70.jpg)
4. Compile and run it in Windows and you should see this (which seems more like the UWP default behavior)
![Simple-Toggle-Windows](https://user-images.githubusercontent.com/12423046/163723904-a3d8a66e-08d1-48e8-b046-2752f07f4afd.jpg)

The main differences look like the presence of the "On" and "Off" text by default with no seeming option to turn them off and the default HorizontalOptions which looks like it might be "start" on Windows and "end" on Android.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

No, on UWP I might be able to use OffContent and OnContent to disable the labels (incidentally these seem like they would be very useful, they just do not seem to be available on Android, Xamarin, or MAUI)

**Comment by david-maw** [comment]
I just checked generating a UWP app on Xamarin and it uses the same OnContent/OffContent text so it ISNT different from the Xamarin-on-UWP implementation, just different from Android and (I assume) ios.

**Comment by kristinx0211** [comment]
verified repro on  Android 11 and windows with 17.3.0 preview 1.0[32413.517.main].

**Comment by ImproveForInnovation** [comment]
That's a bizarre choice for default behavior. Maui should suppress the text or allow to set it dinamically.

**Comment by vishaljadhav09** [comment]
Hello guys,

I have also faced this displaying On Off text issue in Windows as it is not displaying on other platform.So tried lots of practices to disable this On/Off  text of switch.

And found one solution to this problem.I think we can try this solution. So I have used Absolute Layout. As **[Absolute Layout](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/absolutelayout?view=net-maui-7.0)** gives you option to specify child's width . I have given 60 as width for the Switch controll. And it show only the Switch not On/Off text next to it.

And also checked by resizing the window , all is working fine. The On/Off Text doesn't Appear. So I think we can thought about this solution.Also the Best Thing is it is working fine for Android till not checked for iOS.


Happy to receive observations and suggestions....

Note- For entire source code, Please visit [here](https://github.com/vishaljadhav09/MauiApp2/)

`              

                <AbsoluteLayout Margin="{OnPlatform iOS='0,20,0,0'}" >

                    <Label Text="Switch Demo" 
                           Margin="16,14,0,0"
                           Style="{StaticResource ProfileSettingLabel}"/>
                    <Switch Style="{StaticResource ProfileSettingSwitch}" 
                            ThumbColor="{OnPlatform Android='#0969D9', iOS='#FFFFFF',                           WinUI='#FFFFFF'}"     
                            OnColor="#0969D9"
                            AbsoluteLayout.LayoutBounds="0.7,0,60,35"
                            AbsoluteLayout.LayoutFlags="XProportional,YProportional" 
                            Toggled="OnLocationSwitchToggled"
                            IsVisible="{OnPlatform Android='True',iOS='True',WinUI='True'}"/>

                </AbsoluteLayout>
`

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/117821320/218378343-b452e76f-41e3-410f-97d3-ae9eb2492435.gif)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 2.0. Repro on Android and Windows platform with sample project. 
[Simple-Toggle.zip](https://github.com/dotnet/maui/files/11279532/Simple-Toggle.zip)
![image](https://user-images.githubusercontent.com/77434865/233251064-9cb81f67-28b4-4b00-87bc-6aa1e919b8e2.png)
![image](https://user-images.githubusercontent.com/77434865/233251069-cd8da49c-d92b-4ea9-9f20-dc839b1e0d5d.png)

**Comment by vishaljadhav09** [comment]
Hello Winnie Zhang ,

      As I have mentioned there, have you tried absolute layout as layout ?
Please check On/Off text still showing in windows or not?

**Comment by david-maw** [comment]
@vishaljadhav09 Surely what you describe is a workaround, not a fix, certainly it masks the symptom, but the underlying problem is unchanged. Certainly AbsoluteLayout has its place, but it can be very unforgiving and somewhat tricky to use, especially in an adaptive interface.

**Comment by vishaljadhav09** [comment]
Yes @david-maw you are right this is some kind of workaround to the issue.So until MAUI resolve this issue from their side we can think about this workaround.

**Comment by nicop85** [comment]
+1 to this problem currently showing the "on/off" label besides the switch in WinUI (v. 7.0.86)

**Comment by Felicity-R** [comment]
An alternative to restricting the width is to use a handler mapping to get rid of that label. Like:

```
   SwitchHandler.Mapper.AppendToMapping("Custom", (h, v) =>
        {
            // Get rid of On/Off label beside switch, to match other platforms
            h.PlatformView.OffContentTemplate = null;
            h.PlatformView.OnContentTemplate = null;

            h.PlatformView.MinWidth = 0;
        });
```

Setting the MinWidth to 0 is necessary to let it size better, otherwise there's a bunch of empty space left on the right due to https://github.com/microsoft/microsoft-ui-xaml/issues/3652

**Comment by nicop85** [comment]
@Felicity-R  thanks for sharing! 

I had to add

```
h.PlatformView.OffContent = null;
h.PlatformView.OnContent = null;
```
 but other than that, it worked for me

**Comment by nicop85** [comment]
@Felicity-R thanks for sharing! It worked for me

**Comment by allen-628** [comment]
Nearly a year has passed and this very simple issue (little fish) still is unresolved, for windows.
Is there any timeline for getting this fixed?
Or has the Maui Team moved on to the next latest and greatest, catching the big fish while the little fishes keep getting away
?

**Comment by david-maw** [comment]
My preferred action is to maximize the chance of a single form layout working on all platforms. I use MAUI so as to have a single application run across multiple platforms and having this default the same way on all platforms would best meet that goal. 

Certainly a mapper is easy (well, speaking personally, it is if someone shows me how to do it as in this case) but I'd prefer simply adding OffContent and OnContent properties to the MAUI Switch class. Alas, that would mean implementing them in Android and IOS, which seems like a lot of work for a handy, but niche feature.  IMHO a reasonable compromise would be to, as you put it, 'turn this behavior around', hide the default content in Windows and document a solution for anyone who wants the labels on Windows (which I presume are localized, making the solution a bit trickier).

**Comment by david-maw** [comment]
Sorry @jfversluis I forgot to explicitly name you in the previous reply to your post.

**Comment by jfversluis** [comment]
> My preferred action is to maximize the chance of a single form layout working on all platforms. I use MAUI so as to have a single application run across multiple platforms and having this default the same way on all platforms would best meet that goal.

I definitely understand your sentiment, but I'd think if you want it to really look the same, there are other frameworks that will make it easier to achieve that. Don't get me wrong, I want to keep you here with .NET MAUI, but our paradigm has always been that we translate our abstract layer controls into whatever it should look like on the platform.

For Windows in this case that means having "On/Off" next to this control. If you go through Windows apps, that is what you will see, so if your user is using your apps on Windows, that is what they would expect to see.

What I definitely don't see us doing is implement this as a property and thus also implementing extra functionality for this on iOS and Android. As you already say: it's localized and all that, so we're opening up a whole new set of extra work there which we don't want to do.

What we could do is introduce a [platform-specific](https://learn.microsoft.com/dotnet/maui/windows/platform-specifics/) for this so that we can influence this only for Windows. I think I'd still keep the default to on because it's the default behavior on Windows _and_ it would be a breaking change if we would suddenly change that now.

That will make it easier to set this without writing your own handler, would that be an option?

**Comment by david-maw** [comment]
Thanks @jfversluis, a platform specific would be fine, but unless it's got some downside that I don't understand documenting the handler workaround would do as far as I'm concerned. Since I'm almost completely unfamiliar with handlers I'm probably not qualified to comment on the relative merits of the two solutions) though a plaform specific _seems_ like it would be a bit better integrated.

As for cross-platform compatibility, I want my app to have a native look and feel on whatever platform it's on even though the difference for some things like entry fields is considerable. This difference was bothersome mostly because it changed the overall geometry of the control and duplicated the function of a Label which did essentially the same thing (generate a message for on vs. off). In the more general case differences like an entry box vs. an underline are less significant to the overall page layout.

**Comment by david-maw** [comment]
Thanks @jfversluis, a platform specific would be fine, but unless it's got some downside I don't understand documenting the handler workaround would do as far as I'm concerned.

As for cross-platform compatibility, I definitely want my app to have a native look and feel on whatever platform it's on. The difference for some things like entry fields is considerable, this one was bothersome because it changed the overall geometry of a control in a surprising way whereas differences like an entry box vs. an underline are less significant to the overall page layout.

**Comment by jsuarezruiz** [comment]
There is a quick workaround and we are evaluating options (add new property and implement on all platforms, platform specific etc).

```
#if WINDOWS
 SwitchHandler.Mapper.AppendToMapping("Custom", (h, v) =>
        {
            // Get rid of On/Off label beside switch, to match other platforms
            h.PlatformView.OffContent = string.Empty;
            h.PlatformView.OnContent = string.Empty;

            h.PlatformView.MinWidth = 0;
        });
#endif
```

However, it will not happen for .NET 8 timing. We will open a new Spec once we have it defined and we are going to close this issue. Feel free to let me know if we are not covering all the request in the upcoming spec or to open a new issue. Thanks for all your feedback and time.

**Comment by david-maw** [comment]
Sorry @jsuarezruiz, forgot to tag you in the previous comment.
