### ISSUE TITLE
System.MissingMethodException: 'No parameterless constructor defined for type' calling MVVM from Shell in C#

### ISSUE THREAD

**Issue by devonuto** [dotnet/maui#6180]
### Description

When following the method shown in https://github.com/brminnick/HackerNews, when calling the page from Shell, results in a "System.MissingMethodException: 'No parameterless constructor defined for type DashboardPage" error under Android or just an unhandled Win32 error on Windows.

### Steps to Reproduce

1. Follow Hackernews example for creating .NET Maui app, page & viewmodel etc
2. Create AppShell : Shell page
3. Set MainPage = AppShell
4. Add new FlyoutItem to Shell:

`public AppShell()
{
    Items.Add(
        new FlyoutItem
        {
            Title = "News",
            Route = nameof(NewsPage),
            Items.Add(
                new Tab
                {
                    Title = "News",
                    Items = {
                        new ShellContent
                        {
                            Title = "News",
                            Route = nameof(NewsPage),
                            ContentTemplate = new DataTemplate(typeof(NewsPage)),
                        }
                    }
                }
            )
        }        
    );
}`

5. Build and launch in Android Emulator, get above error.
6. Launch in windows, get Win32 error
[mauicheck.txt](https://github.com/dotnet/maui/files/8502766/mauicheck.txt)
.

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

net6.0-android 21.0, Windows 10.0.17763.0

### Did you find any workaround?

Not use this MVVM method

**Comment by VladislavAntonyuk** [comment]
You have to register your pages in DI. 
`
builder.Services.AddSingleton<DashboardPage>();
`

**Comment by devonuto** [comment]
It is registered in the shell itself.  
Routing.RegisterRoute(nameof(DashboardPage), typeof(DashboardPage));

Didn't think it needed to be in the DI as well, as it works without MVVM. It's complaining that there is no parameterless path, because it's not parameterless in the MVVM model.

**Comment by VladislavAntonyuk** [comment]
That is not enough to register it in shell route. See example from HackerNews: https://github.com/brminnick/HackerNews/blob/main/src/HackerNews/MauiProgram.cs#32

**Comment by VladislavAntonyuk** [comment]
By the way, what features from Xamarin Community Toolkit do you use?
Can you migrate to CommunityToolkit.Maui?

**Comment by devonuto** [comment]
I am using the Maui toolkit, but I'm getting that same bug, so I assume it's the same issue.

 <PackageReference Include="CommunityToolkit.Maui" Version="1.0.0-pre9" />
<PackageReference Include="CommunityToolkit.Maui.Markup" Version="1.0.0-pre9" />
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0-preview3" />

**Comment by devonuto** [comment]
Hmm.  I noticed I still had my old Xamarin app still sitting unused in the sln , but it wasn't part of the build. I removed it from the sln and it's not happening anymore.  Will try the above again.
