### ISSUE TITLE
MAUI templates don't show in VS 2022 Preview

### ISSUE THREAD

**Issue by Mr-Anonymous75** [dotnet/maui#6181]
### Description

I'm using Visual Studio 2022 **17.2 Preview 3**, and I've installed the Mobile Development workload with the MAUI box checked - but I still can't see any MAUI templates in the app.

### Steps to Reproduce

Well, nobody else seems to have the problem I do, but here's what I did.

1. I installed the _Mobile Development with .NET_ workload to Visual Studio 2022 17.2 Preview 3, making sure that _.NET MAUI (Preview)_ was checked in the installation details.
2. I launched Visual Studio, searched for the MAUI templates, and found nothing.
3. I restarted my PC.
4. I launched Visual Studio and searched for MAUI stuff again - still nothing.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11 with both Windows 10 SDK 10.20348 and Windows 11 SDK 10.22000 installed

**Comment by Mr-Anonymous75** [comment]
I tried WinUI 3, and the same thing happened. Should I be posting this issue somewhere else?

**Comment by JasonWues** [comment]
If you have .NET7 installed,Template will not show

**Comment by Mr-Anonymous75** [comment]
> If you have .NET7 installed,Template will not show

Oh. Why though? That makes absolutely no sense.

**Comment by JasonWues** [comment]
I don't know, but uninstalled .Net7 works fine.
Maybe .Net7 did not support Maui.

**Comment by drasticactions** [comment]
> I don't know, but uninstalled .Net7 works fine.
> Maybe .Net7 did not support Maui.

It currently doesn't. If you want to use MAUI you need to target .NET 6 (Specifically 6.0.300 in the case of RC1). There are no workloads being deployed for .NET 7 right now.

IMO this isn't strictly a MAUI issue that could be fixed within this repo, but something needs to be addressed within Visual Studio. It is weird if it won't show templates for other .NET Bands other than the newest (preview!) version you have installed. I would file an issue with VS at https://developercommunity.visualstudio.com.

**Comment by VincentBu** [comment]
Hi @Mr-Anonymous75, does **drasticactions**'s solution solve this issue?

**Comment by Mr-Anonymous75** [comment]
> Hi @Mr-Anonymous75, does **drasticactions**'s solution solve this issue?

I haven't tried that yet - I uninstalled .NET 7 already, though I'll probably try it later when I need .NET 7.
