### ISSUE TITLE
Negative Padding values fail on Windows work on Android

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#6182]
### Description

I was using a label as part of a DataTemplate for a CollectionView and the label happened to have a padding with a negative value. That CollectionView showed nothing in Windows but worked as expected in Android.

### Steps to Reproduce

1. Unzip the project from [Simple-padding.zip](https://github.com/dotnet/maui/files/8503833/Simple-padding.zip)
2. Compile and run on Android, you should see this, the expected result:
![simple-padding-android](https://user-images.githubusercontent.com/12423046/163762516-8a26710e-e756-4530-9935-231936161e30.jpg)
3. Run on Windows and you should see this:, a blank page because no items are rendered:
![simple-padding-windows](https://user-images.githubusercontent.com/12423046/163762611-1914cadd-0c93-4c6f-aef5-af24db6ed0b6.jpg)
 

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Only avoiding negative values

**Comment by v-longmin** [comment]
Verified repro on Windows, not repro on Android 12.0 - API31 with VS 17.2.0 Preview 2.1 [32317.152]. Repro project:
[Simple-padding.zip](https://github.com/dotnet/maui/files/8504098/Simple-padding.zip)

**Comment by kristinx0211** [comment]
@david-maw Thank you for your report. We have determined that this issue is the same as or very similar to issue #5621, so we are closing this one as a duplicate. Please follow that issue for updates. We would want to keep the oldest issue open UNLESS the newer issue has more information that makes it easier for the engineers to work with. Please get started at your convenience! Let us know if there are any other situations that need guidance.

**Comment by david-maw** [comment]
@kristinx0211 Really? The symptom does not look at all similar to me #5621 seems to be about applying margins to CollectionView items and results in incorrect margins, but this one is about padding and results in the item not being shown at all. I'm certainly willing to believe the underlying cause is the same, if you say so, but the symptoms seem quite different.. Am I missing something?
