### ISSUE TITLE
Ping in iOS

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#6187]
### Description

Hi,

I am referring to this link:

[https://docs.microsoft.com/en-us/answers/questions/806688/operation-is-not-valid-due-to-the-current-state-of-1.html?childToView=815311#comment-815311](https://docs.microsoft.com/en-us/answers/questions/806688/operation-is-not-valid-due-to-the-current-state-of-1.html?childToView=815311#comment-815311
)

<img width="673" alt="Screen Shot 2022-04-18 at 3 24 22 PM" src="https://user-images.githubusercontent.com/6236241/163801594-6003c42c-9038-434d-b723-1f286317b10b.png">

This can be included in the same [Ping](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ping.sendpingasync?view=net-6.0)

I hope this will be fixed in MAUI so we only use the .NET MAUI in pining, tracert , etc without having to use external components.

### Public API Changes

Please see above

### Intended Use-Case

Please see above

**Comment by jfversluis** [comment]
I feel this is far from something a UI framework should do. Additionally, there doesn't seem to be much traction/interest here. I will close this one for now, let's revisit in the future.
