### ISSUE TITLE
EF Core migration does not work for IOS

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#6189]
### Description

I have a dot net maui app that uses entity framework 6 with sql lite. All works OK for windows and android platforms but not fo IOS I get a SQLite connrection exception when appContext.Database.Migrate(); is called.

![image](https://user-images.githubusercontent.com/5493492/163806628-f22019a5-bd53-4d78-8121-a435e1cf9282.png)

### Steps to Reproduce

1.Create A Blazor MAUI project
2. Use Entity framework DBContext with SqLite
3. Use appContext.Database.Migrate(); in code to create and populate database
4. Obeserve all works OK for windows and Android platforms
5. Observe Exception when IOS Platform is used
6. 
![Uploading image.png…]()

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Windows server 2022

### Did you find any workaround?

No 

### Relevant log output

```shell
See picture above
```

**Comment by drasticactions** [comment]
I'm 99% sure this issue is not MAUI specific. You should try making an iOS app without MAUI and seeing if you can reproduce it. Also, could you attach the full logs for the exception? Just having the message isn't enough.

@bricelam do you have any ideas where this goes?

**Comment by ltemimi** [comment]
This a MAUI Blazor app that uses Entity framework. I am not sure how I can have this hybrid app without using MAUI? 
The exact same code works under MAUI Windows, MAUI Android and even Blazor Sever. 
I suspect C# code is running differently under MAUI IOS can IOS handle nullable (c#8) for instance.

**Comment by drasticactions** [comment]
The code you're running specifically for EFCore can be run in an iOS app that does not reference MAUI. What I'm suggesting is you try running those calls within a new iOS app that doesn't use MAUI and see if you get the same results. My guess that is you will, which means referencing MAUI isn't doing anything here.

**Comment by VladislavAntonyuk** [comment]
for iOS you need additional settings for the connection. see example: https://vladislavantonyuk.azurewebsites.net/articles/Adding-SQLite-to-the-.NET-MAUI-application

**Comment by hartez** [comment]
Is this related to #6145 ?

**Comment by VladislavAntonyuk** [comment]
@hartez I think yes. mostly all issues related to iOS and additional steps which are required to make it work.
