### ISSUE TITLE
How to use Razor Component Library with .Net MAUI

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#6194]
### Description

I am using VS 17.2.0 Preview 3.0 and have a newly created MAUI project.

I want to separate out my Razor Components into its own library. .NET MAUI Class Library does not appear to be correct for this.

There is no option to add a Razor Component Library in this VS preview.

Since we are in RC1 now, how are we supposed to do this?

Thanks

### Steps to Reproduce

Create a new .NET MAUI Blazor App.
Try to create a Razor Component Library for use with this app.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 Pro Version 21H2

### Did you find any workaround?

No

**Comment by VincentBu** [comment]
Hi @genifycom, the `Razor Component Library` template requires `ASP.NET and web development` workload installed.

**Comment by janseris** [comment]
try ﻿<Project Sdk="Microsoft.NET.Sdk.Razor">

**Comment by TanayParikh** [comment]
As @janseris mentioned, your RCL's `.csproj` should start with `<Project Sdk="Microsoft.NET.Sdk.Razor">`.

Then, in Visual Studio, use File > Add > Existing Project, and choose the `*.csproj` for your RCL.

![image](https://user-images.githubusercontent.com/14852843/164332558-7c512adf-f49b-4e09-af2d-481ec884cf0f.png)

In Solution Explorer, right-click on your application project name and choose Add > Project Reference. In the dialog, check your RCL and click OK.

![image](https://user-images.githubusercontent.com/14852843/164332535-65d85767-a269-4460-9b97-d78bacd47137.png)

You should now be able to use your RCL. Please let us know if this works out for you 😄

**Comment by janseris** [comment]
See this project of mine [Prejimky.Reports.UI-master.zip](https://github.com/dotnet/maui/files/8529512/Prejimky.Reports.UI-master.zip)
which is a 1 month old extension of this project https://github.com/edandersen/blazor-desktop-crossplatform-sample
It contains a separate class library for Blazor controls and uses them in WinForms which are the most important bits and pieces for multi-project Blazor WebView. Same would probably be for MAUI.

**Comment by javiercn** [comment]
@genifycom thanks for contacting us.

What we currently recommend is that you put your Razor views, etc inside a Razor Class Library. And consume that from either a Maui Class Library or a Maui Application.

If you need per-platform functionality, we recommend you define an interface for that functionality to use in Blazor and provide the implementations in a consuming Maui Class Library.

**Comment by jfversluis** [comment]
I don't really see any work that we need to be doing still here? I will close this one, if I'm overlooking something, please let me know or open a new issue with the thing that is still impacting you.
