### ISSUE TITLE
Toolbar moves when overflow button is pressed

### ISSUE THREAD

**Issue by mobycorp** [dotnet/maui#6199]
### Description

I have added a toolbar to see what it does.  I notice that when the ... button is pressed, the contents of the menubar slide up.

The before looks as follows:

![Before](https://user-images.githubusercontent.com/60759137/163863723-8cb59045-dc0b-4120-b1e0-ab62d29f327f.png)

(I also have a question about the yellow box below.)  When the ... button is clicked the menubar looks as follows:

![After](https://user-images.githubusercontent.com/60759137/163863884-c36a1458-6823-41d9-a749-801730617dc6.png)

The question I have also about the first screenshot: How do you change the color of the menu bar?  I was able to do it in previous releases, but I can't find the setting to change the background color to save my life.  You can see in the next screenshot, I was able to do it somehow...

![image](https://user-images.githubusercontent.com/60759137/163864228-cd4c44d2-e7a6-4569-a00b-255cdef55369.png)

While I am at it, I want to change the font and color of the Title element while I'm at it...  How?

### Steps to Reproduce

1) Create new .NET MAUI application
2) Add a shell:

![image](https://user-images.githubusercontent.com/60759137/163865682-6c100e07-cb48-4424-9e8b-f0accc5434a8.png)

3) Run the app and observe...

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 12

### Affected platforms

Windows

### Affected platform versions

I haven't tried this out on any other platform other than windows.

### Did you find any workaround?

NO

**Comment by mobycorp** [comment]
@msftbot Here is the link to the repo you requested:

https://github.com/mobycorp/MobyClient


Thanks!

**Comment by mobycorp** [comment]
To observe the behavior I have reported, run the app and click on the ... toolbar overflow button.

**Comment by kristinx0211** [comment]
can be reproduced on windows with above project.

**Comment by PureWeen** [comment]
Duplicate https://github.com/dotnet/maui/issues/7156
