### ISSUE TITLE
`ListView` uses the wrong style in WinUI 3

### ISSUE THREAD

**Issue by StarlkYT** [dotnet/maui#6209]
### Description

https://imgur.com/LIVgiYg

### Steps to Reproduce

1. Create a `ListView` in `MainPage.xaml` and give it an `x:Name`
2. Go to `MainPage.xaml.cs` and give it an `ItemsSource` (I created a `List<string>`)
3. Run the app 

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

**Comment by shimingsg** [comment]
I found the selection doesn't contain the first letter fully, with VS 17.3.0 Preview 1.0 [32417.43.main]
![image](https://user-images.githubusercontent.com/20982341/163943736-614f2723-6d6c-4412-9671-4b978ca5d0d3.png)

**Comment by VincentBu** [comment]
Hi @StarlkYT, could you provide more details about the issue?

**Comment by VincentBu** [comment]
Does [shimingsg](https://github.com/shimingsg)'s comment give the expected result? (I think that is default style)
Otherwise, would you like to provide a sample project?

**Comment by StarlkYT** [comment]
> Does [shimingsg](https://github.com/shimingsg)'s comment give the expected result? (I think that is default style) Otherwise, would you like to provide a sample project?

No it does not, I provided how it looked with me and how it is supposed to look like:
https://imgur.com/LIVgiYg
 https://imgur.com/a/OYy6pn7
