### ISSUE TITLE
Voiceover is not reading the Role of "click me" button.

### ISSUE THREAD

**Issue by Karan4495** [dotnet/maui#6215]
GitHubTags:
#.NET MAUI; #A11ySev2; #A11yMAS; #A11yTCS; #Benchmark; #iOS; #iPad; #WCAG4.1.2; #GH_.NETMAUI_IOS_Mar2022; #Name Role Value​; #AINotInScope;

### Description

Voiceover is not reading the button for "click me" button and voiceover is not reading "double tap to activate" when focus move to "click me" button.

### Steps to Reproduce

1.Install and open ".NET MAUI Template" app.
2..Net MAUI template screen will open.
3.Swipe till "Click me" button.
4.Verify Voiceover is reading the role of click me button or not.

https://user-images.githubusercontent.com/100186395/163924002-97b80b43-a926-4e05-a86e-6ef39a82f9ac.mp4

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4.1(iPad)

### Relevant log output

```shell
Voiceover should read the button for "click me" button i.e. voiceover should read click me button and also read the "double tap to activate".
```

**Comment by v-longmin** [comment]
Verified repro on VS 17.3.0 Preview 1.0 [32418.321.main]. Repro with maui sample template project.

**Comment by PureWeen** [comment]
Related https://github.com/dotnet/maui/issues/5823

**Comment by rachelkang** [comment]
Resolved - "button" role is now announced.

As for the "Double tap to activate" text, that is Android-specific behavior that does not get emulated on iOS
