### ISSUE TITLE
add documentation for taking VS-generated default Maui project nad debugging with local Maui build

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#6218]
### Description
Need easy way to debug/modify Maui framework with existing app.

I would like to debug our app against a local Maui build (in order to track down what appear to be Maui bugs and perhaps create a pull request).  I have a single project Maui solution which I can run using the default settings <UseMaui>true</UseMaui>.  However it is not well documented how to modify this app to link against a local Maui build.  DEVELOPMENT.md has instructions for building Maui locally, but after spending some hours I am unable to use that local build in may app. 

### Public API Changes

Step-by-step documentation for how to use the VS wizard to create a single project file Maui app and then modify it in order to run with a local Maui development build.

### Intended Use-Case

Debugging bugs which could lie within the Maui framework, or understand code better by debugging against a local Maui build. This will allow people to more easily contribute to Maui instead of just working around Maui bugs and not reporting them.

**Comment by PureWeen** [comment]
@philipag we have a documented process here https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md#testing-branch-against-your-project

It's not quite as straight forward as just downloading nugets. 

The process with .NET8 should be much simpler. Once that process is in place then we will update the documentation for .NET8 scenarios.
