### ISSUE TITLE
Http Client Maui Blazor

### ISSUE THREAD

**Issue by Tiku96** [dotnet/maui#6219]
### Description

I have a problem with maui blazor when I create an httpclient client the application goes into error and does not give me any error debugging, as to make the app work on a physical iPhone I have to launch it in a release mode.

On android the application works correctly.

### Steps to Reproduce

1.   public static Client Api = new($"{url}", httpClient: new HttpClient());
2.  Run app
3.  Crash

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 15.4, windows 11 Visual Studio 2022 version 17.2 Preview

**Comment by VincentBu** [comment]
Hi @Tiku96, I can't repro on IOS emulator. Here is my project, I add `httpclient` related code in `MainPage.xaml.cs`. Would you like to verify it on your IOS device?
[MauiApp4.zip](https://github.com/dotnet/maui/files/8560544/MauiApp4.zip)

**Comment by romanov** [comment]
Unable to use any httpClient in MAUI BLAZOR RC1.

Just declare `new HttpClient()` and the app will fail

**Comment by VincentBu** [comment]
Hi @Tiku96 and @romanov, would you like to share a sample project?

**Comment by romanov** [comment]
[MauiBlazorHttpClient.zip](https://github.com/dotnet/maui/files/8570333/MauiBlazorHttpClient.zip)

You can move httpClient to other class and call it. Any declaration will crash the app.

**Comment by kristinx0211** [comment]
@romanov Thank you for your report. We have determined that this issue is the same as or very similar to issue #6460, and this is not repro on the latest main branch, so we close it now.
