### ISSUE TITLE
[Enhancement] Hot Reload: improve x:Name API

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#622]
Consider following XAML
```xaml
<Shell>
  <FlyoutItem x:Name="ItemsPageItem" Title='Browse'>
  <!-- <FlyoutItem x:Name="ItemsPageDetails" Title='Details'> -->
</Shell>
```
If user uncomments ItemsPageDetails item we need to create new FlyoutItem, add it to Shell and register ItemsPageDetails with appropriate namescope. VS Hot Reload attemps to find namescope by traversing ItemsPageDetails ancestors. However we currently fail to find namescope. The net result is new FlyoutItem appears in Live Visual Tree without a name. For more details see VS bug [1267625](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1267625).
One thing to note about names is that users will name elements not for the sake of referencing them via bindings and alike but just to be able to easily find right items in Live Visual Tree. Thus we would like to see following improvements:

1. There should be public read-write VisualElement.Name property. Like it is in WPF and UWP.
2. Better API for updating namescope registration. Which will deal with any MAUI internal optimizations and/or visual tree modificartions. Something like

```cs
namespace Xamarin.Forms.HotReload
{
  class HotReloadHelper
  {
      public void UpdateElementName(VisualElement element, string oldName, string newName) {};
  }
}
```

**Comment by StephaneDelcroix** [comment]
can't you use RegisterName()

**Comment by etvorun** [comment]
> can't you use RegisterName()

We use, but it does not always work, e.g. see XET bug [1267625](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1267625).

**Comment by spadapet** [comment]
I just debugged this, and it seems like we (UITools MAUI TAP) aren't sending the TAP message UpdateNameRegistration when the x:Name is added or changed. When I forced a call to UpdateNameRegistration, then the new x:Name did show up in the Live Visual Tree.

So this could end up being a fix in MAUI TAP (UITools repo). I'll take this to debug more.

**Comment by spadapet** [comment]
@etvorun the fix went into UITools Xamarin hot reload code, not MAUI repo:
* https://github.com/xamarin/UITools/pull/1714
