### ISSUE TITLE
MAUI RC1 is not compatible with Xamarin.iOS NuGet packages

### ISSUE THREAD

**Issue by rricarrdo** [dotnet/maui#6221]
### Description

There is an issue with MAUI not being compatible with Xamarin.iOS packages the same way as it is compatible with Xamarin.Android packages. For example:

If you reference a Xamarin iOS package like [Xamarin.Google.iOS.Maps](https://www.nuget.org/packages/Xamarin.Google.iOS.Maps/), the package will be installed in all of the platforms (android, ios, maccatalyst, windows), and the classes will **not** be available to be referenced inside the “Platforms.iOS” project.

The same does not happen with Xamarin.Android packages such as [Xamarin.GooglePlayServices.Maps](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Maps/117.0.1.3). When installing the package, it is installed only inside the Android platform, and the package can be normally referenced inside the “Platforms.Android” project.

The same behavior can be observed on other Xamarin packages as well. 

### Steps to Reproduce

1. Create a new MAUI project on Visual Studio for Windows
2. Add the NuGet package [Xamarin.Google.iOS.Maps](https://www.nuget.org/packages/Xamarin.Google.iOS.Maps/)
3. Check that the package is referenced into all of the platforms (android, ios, maccatalyst, windows)
4. Try to reference the package inside the "Platforms > iOS > AppDelegate.cs" file by adding the following line of code (or any other call to the package)
`Google.Maps.Loader loader = new Google.Maps.Loader();`
6. Check that the package is not found
7. Add the NuGet package [Xamarin.GooglePlayServices.Maps](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Maps/117.0.1.3)
8. Confirm that the package is referenced only in the Android platform
9. Try to reference the package inside the "Platforms > Android > MainActivity.cs" file by adding the following line of code:
`Android.Gms.Maps.MapFragment map = new Android.Gms.Maps.MapFragment();`
10. Check that the package is found correctly

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Visual Studio 17.2.0 Preview 3.0 (Windows); MAUI RC1; Xamarin.iOS 15.9.0.100; Xamarin.Android 12.3.0.3

### Did you find any workaround?

No workaround found so far.

**Comment by GalaxiaGuy** [comment]
https://github.com/xamarin/xamarin-macios/issues/13087
