### ISSUE TITLE
ListView context menu is not working.

### ISSUE THREAD

**Issue by JiuLing-zhang** [dotnet/maui#6225]
### Description

Click is not working on any row.  

Test source code:
[ContextMenuNotWorking.zip](https://github.com/dotnet/maui/files/8511927/ContextMenuNotWorking.zip)

### Steps to Reproduce

1.Create MAUI App.
2.Create ListView.
3.Create context menu.
4.Click the menu.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32418.321.main]. Repro on Windows with above project.
