### ISSUE TITLE
[Bug] .NET MAUI RC1 - Shell - OnDisappearing not executing and OnAppearing is only executed the first time

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#6226]
### Description

I have a Shell page with a ShellContent which has a ContentPage linked to its ContentTemplate, the ContentPage's OnAppearing method is only launched the first time the page appears, if you put the application in the background and open it again this method will not be launched never again, the OnDisappearing method never fires. I have tried the same case in an app developed with Xamarin.Forms and it works perfectly, so it is a unique problem of .NET Maui.

<img width="611" alt="image1" src="https://user-images.githubusercontent.com/20904914/163977936-1e8dad9b-c54b-42a6-86f0-36d74d58bebe.png">
<img width="550" alt="image2" src="https://user-images.githubusercontent.com/20904914/163977937-595b5d7b-90cb-444c-9dac-2cba77b6ac87.png">

I attach the 2 repositories, the one for Xamarin.Forms works perfectly and the one for .NET Maui with the mentioned problems:

-Xamarin.Forms:
https://github.com/nacompllo/XamarinFormsLifeCycleIssue

-.NET Maui:
https://github.com/nacompllo/MauiLifeCycleIssue

### Steps to Reproduce

Try the repository attached in the problem description and debug the OnAppearing and OnDisappearing methods of the MainPage page, the OnAppearing method will only be executed the first time the page is displayed if you try to put the page in the background and return to the application is not will fire and the OnDisappearing method never executes. I have also attached the same case in Xamarin.Forms where you can check that it works perfectly.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10

**Comment by VincentBu** [comment]
repro on Android and we run into the same issue on Windows.

**Comment by nacompllo** [comment]
I just tried MAUI version 7.0.92 and this problem no longer occurs, I close the issue.
