### ISSUE TITLE
Embedded images not render in Android Maui

### ISSUE THREAD

**Issue by Choza-rajan** [dotnet/maui#6228]
### Description

The Embedded image is shown properly in WinUI and not working in Android. Below are the screen shots,

WinUI: 
<img width="715" alt="EmbeddedWinUI" src="https://user-images.githubusercontent.com/92723643/163987732-42a38ff0-9e08-453b-b34d-b9dd467f3be5.png">

Android:
<img width="204" alt="EmbeddedAndroid" src="https://user-images.githubusercontent.com/92723643/163987789-207904c8-349a-4d3d-9093-0ee3cc072ba1.png">screenshots

### Steps to Reproduce

1. Run the attached sample in WinUI the image will be shown properly
2. Run the same sample in Android the image has not shown in the UI

[EmbeddedImageAndroid.zip](https://github.com/dotnet/maui/files/8512290/EmbeddedImageAndroid.zip)

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android with above project.

**Comment by janseris** [comment]
Doesn't work for RC 1 also on Sony Xperia 5

**Comment by jonathanpeppers** [comment]
I can confirm that #6394 seems to solve this issue.

Building the attached app with MAUI RC 1 == no image.

Building with dotnet/maui/main I get:

![image](https://user-images.githubusercontent.com/840039/164776543-176b04ff-6549-42b0-be36-ed46e5e64341.png)

**Comment by janseris** [comment]
@jonathanpeppers Hi, that is awesome. Is there, please, any easy way to use this fixed version of MAUI for development? Thank you.

**Comment by jonathanpeppers** [comment]
There are instructions for installing main builds of MAUI here:

https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md#main-branch

You might also have luck copying `maui.aar` over top of:

    C:\Program Files\dotnet\packs\Microsoft.Maui.Core.Ref.android\[your version]\ref\net6.0-android30.0\maui.aar

https://github.com/dotnet/maui/blob/main/src/Core/src/maui.aar

(backup your existing `maui.aar` if you try this)
