### ISSUE TITLE
Frame/Border/Shadow should have Elevation property

### ISSUE THREAD

**Issue by SarthakGz** [dotnet/maui#6233]
### Description

Frame/Border/Shadow should have Elevation property.Using combination of these three control after adding elevation property we can match Flutter Container widget which seem highly customisable and one of the most used widget in any UI.

I think PancakeView used to have all three properties i.e Elevation,Shadow,Border but unfortunately it is no longer maintained
Also MAUI framework should provide this out of the box rather then need for custom control to achieve good looking UI

Not sure if it can be added to IView

I think Shadow Radius property does the same thing that Elevation property would do under the hood but isn't Shadow Radius property is confusing. Elevation sounds right to me

### Public API Changes

```
var frame= new Frame();
frame.Elevation = 10;
```
Same can be for Border/Shadow

### Intended Use-Case

To control the elevation of frame having shadow and border

**Comment by jfversluis** [comment]
Seeing there is not much traction here after 2+ years of opening the issue I don't think we'll get to this anytime soon. Thanks for the suggestion!
