### ISSUE TITLE
VerticalStackLayout doesn't update childs width

### ISSUE THREAD

**Issue by michalkania** [dotnet/maui#6235]
### Description

Hey,
I think it's the same or related to this issue [VerticalStackLayout doesn't size](https://github.com/dotnet/maui/issues/1405)
Default MAUI project (6.0.300-rc.1.5355) - it will create a counter and a button as a template.
When counter exceeds number 9 it "disappears". If you set VerticalStackLayout's HorizontalOptions to "StartAndExpand" (which is not recommended according to [docs](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/layouts/verticalstacklayout#position-and-size-child-views)) then displaying the number works fine.

I can reproduce it regularly on Android simulator (API 28, 30, 31)

### Steps to Reproduce

1. Create New MAUI App
2. Count above 9
3. Label will not update properly

Before 9
![image](https://user-images.githubusercontent.com/8491194/164029496-4dc20e95-3f1a-4295-816f-49e49f0d369d.png)

After 9
![image](https://user-images.githubusercontent.com/8491194/164029533-520b9886-146b-481b-8275-ec8879a767f7.png)

On different screen sizes it can display eg. one (first) digit so 11 = 1, 24 = 2 etc.

**Label width on Android**
![Screenshot 2022-04-19 162502](https://user-images.githubusercontent.com/8491194/164030818-76edd410-35c1-4c85-a355-ce345d53e210.png)

![Screenshot 2022-04-19 162531](https://user-images.githubusercontent.com/8491194/164030879-f9a6efe9-a6f4-42d5-ae71-ad5e6d408875.png)

Counter goes up, but the width stays.

**Label width on Windows**
![Screenshot 2022-04-19 162637](https://user-images.githubusercontent.com/8491194/164030994-a21dcb32-f34d-4de2-b290-8a020bda75f2.png)

It updates the width and is displayed correctly
![Screenshot 2022-04-19 162656](https://user-images.githubusercontent.com/8491194/164031060-7812420b-7c3d-4aee-acdb-77fbf0cc9897.png)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 9, 11, 12, Windows 10 19044

### Did you find any workaround?

Set HorizontalOptions to StartAndExpand (but not recommended according to documentation)

**Comment by hartez** [comment]
I'm betting this was fixed by #5897.

**Comment by Redth** [comment]
Does not repro for me on maui main branch, I agree, fixed by #5897
