### ISSUE TITLE
Shell AppThemeBinding is incorrect and not consistent

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#6244]
### Description

OS is Light, App is set to Dark. This is the result:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/41873/164063907-77a04c7b-bfc8-41c5-82f3-53b392aff9e9.png">

I expect the flyout and navbar to be dark as styled.

When I toggle in-app to Light, most of the UI updates but the page background doesn't. Sep issue. #5706 maybe

<img width="834" alt="image" src="https://user-images.githubusercontent.com/41873/164064351-b840e9ea-9975-45c6-82ee-aed80b5ad613.png">

When I toggle back to Dark, the flyout updates, but the navbar doesn't.

<img width="823" alt="image" src="https://user-images.githubusercontent.com/41873/164064594-b962bd01-c82c-4a5d-8ff0-f9185cf11186.png">

### Steps to Reproduce

https://github.com/davidortinau/WeatherTwentyOne

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Win11

**Comment by rachelkang** [comment]
NavBar theming appears to work as expected now in main

Still investigating the flyout background aspect - what I've uncovered so far is that interestingly, it's only an issue when flyoutBehavior=locked to start. So if you remove the flyoutBehavior or set it ot FlyOut, it works as expected.

**Comment by rachelkang** [comment]
Fixed by #6901!
