### ISSUE TITLE
Blazor Hybrid index.html script and css files are case sensitive

### ISSUE THREAD

**Issue by rogihee** [dotnet/maui#6248]
### Description

Not sure if this was a deliberate design choice but in Blazor Hybrid files loaded in the `index.html` are case sensitive. E.g. given a Razor Class Library in my solution called `MyComponentLibrary` with a bundled js file in it, this will not work and create a runtime error:

`<script src="_content/mycomponentlibrary/js/myjsfile.min.js"></script>`

Only this will work:

`<script src="_content/MyComponentLibrary/js/myjsfile.min.js"></script>`

Browsers are case insensitive but as in hybrid mode they are loaded via a file provider suddenly all files loaded via index.html are case sensitive. This might trip up a lot of people because it is different from current Blazor and browser standards. 

I only tested Android but I suspect the other platforms are the same. 

### Steps to Reproduce

1. Create a component library with a js file
2. Include the js file from index.html with the wrong case
3. Start the app and observe a runtime error

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All

**Comment by jfversluis** [comment]
Maybe this is due to the platform it's running on? I would suspect on Windows this wouldn't be an issue. Unix based systems have case-sensitive filesystems, might just be that?

**Comment by rogihee** [comment]
@jfversluis yes indeed, it seems to depend on the deployment platform. Not really an issue per se then. Closing.
