### ISSUE TITLE
Span.GestureRecognizers - TapGestureRecognizer not working on windows and Android in Visual Studio 2022 .NET Maui

### ISSUE THREAD

**Issue by AndreduToit** [dotnet/maui#6257]
### Description

The Span.GestureRecognizers does not fire the relevant event on click

### Steps to Reproduce

1. In VS add a new new .NET Maui App

2. In the MainPage.xaml, after <Button Text="Click me" add two labels as follows:
            <Label>
                <Label.GestureRecognizers>
                    <TapGestureRecognizer 
                        Tapped="OnCounterClicked"/>
                </Label.GestureRecognizers>
                <Label.FormattedText>
                    <FormattedString>
                        <FormattedString.Spans>
                            <Span Text="Label.GestureRecognizers - TapGestureRecognizer test : " />
                            <Span Text="tap this" TextDecorations="Underline">
                            </Span>
                            <Span Text="." />
                        </FormattedString.Spans>
                    </FormattedString>
                </Label.FormattedText>
            </Label>
            <Label>
                <Label.FormattedText>
                    <FormattedString>
                        <FormattedString.Spans>
                            <Span Text="Span.GestureRecognizers - TapGestureRecognizer test : " />
                            <Span Text="tap this" TextDecorations="Underline">
                                <Span.GestureRecognizers>
                                    <TapGestureRecognizer Tapped="OnCounterClicked"/>
                                </Span.GestureRecognizers>
                            </Span>
                            <Span Text="." />
                        </FormattedString.Spans>
                    </FormattedString>
                </Label.FormattedText>
            </Label>

3. The Label.GestureRecognizers fires the OnCounterClicked event on click.
    The Span.GestureRecognizers does not fire the OnCounterClicked event on click.
    Same behavior encountered on Windows Machine and Android Emulator - iOS not tested.
    Span.GestureRecognizers worked on Xamarin Forms

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11.0 and Windows Machine

### Did you find any workaround?

TEMPORARY workaround = use Label. GestureRecognizers instead of Span.GestureRecognizers
Problem is that migrating from Xamarin Forms to .NET Maui requires developers to spend time debugging issues that previously worked.

### Relevant log output

```shell
None
```

**Comment by tom-b-iodigital** [comment]
I can confirm this bug, there is no workaround for us as we need different spans in the label react differently to gestures (for example part of a label acting as a link while another part checks/unchecks a checkbox)

**Comment by davidortinau** [comment]
#4734 closing as duplicate
