### ISSUE TITLE
iOS Background (Remote) Notification Functionality Absent (Since Preview 12)

### ISSUE THREAD

**Issue by Thomr77** [dotnet/maui#6259]
### Description

Hi,

The iOS background (remote) notification functionality has been missing since Preview 12 from AppDelegate (UIApplicationDelegate) - we are working on a product that relies on iOS notification and so are stuck at Maui Preview 12.

There are several functions missing but the core ones are:

`[Export("application:didRegisterForRemoteNotificationsWithDeviceToken:")]`
`public void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken) {  }`

`[Export("application:didFailToRegisterForRemoteNotificationsWithError:")]`
`public void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error) {  }`

`[Export("application:didReceiveRemoteNotification:fetchCompletionHandler:")]`
`public void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, [BlockProxy(typeof(Trampolines.NIDActionArity1V21))] Action<UIBackgroundFetchResult> completionHandler) {  }`

### Steps to Reproduce

1. Create a new Maui project.
2. Functions would be defined (override) in PROJECT/Platforms/iOS/AppDelegate.cs (from UIApplicationDelegate).

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 12

### Affected platforms

iOS

### Affected platform versions

Any

### Did you find any workaround?

No - we tried to define these functions ourselves but 'application:didReceiveRemoteNotification:fetchCompletionHandler:' is impossible due to the complexity involved (Trampolines are internal etc).

**Comment by cfierro-glb** [comment]
I believe this was introduced with #4391, as I experienced the same issue. My question now is, if we inherit from `UIApplicationDelegate` on our project's `AppDelegate`, will this be a valid workaround? I haven't had the chance to try it

**Comment by Redth** [comment]
You mentioned an issue with trampolines, can you add more context? 

You should be able to basically just add these method definitions with the right export attributes to your AppDelegate:

```
[Export("application:didReceiveRemoteNotification:fetchCompletionHandler:")]
public void DidReceiveRemoteNotification(UIKit.UIApplication application, NSDictionary userInfo, Action<UIKit.UIBackgroundFetchResult> completionHandler)
{
}

[Export("application:didRegisterForRemoteNotificationsWithDeviceToken:")]
public void RegisteredForRemoteNotifications(UIKit.UIApplication application, NSData deviceToken)
{
}

[Export("application:didFailToRegisterForRemoteNotificationsWithError:")]
public void FailedToRegisterForRemoteNotifications(UIKit.UIApplication application, NSError error)
{    
}
```

**Comment by Thomr77** [comment]
Hi @Redth - no worries,

If we go with the code as you posted it then there is a warning for DidReceiveRemoteNotification() parameter 3 during build:

```
...
1>--custom-step "Xamarin.Linker.DoneStep,/Users/NAME/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft.iOS.Sdk/15.4.100-rc.1.125/tools/dotnet-linker/dotnet-linker.dll"
1>--skip-unresolved true  --custom-data "LinkerOptionsFile=obj/Debug/net6.0-ios/ios-arm64/custom-linker-options.txt" --verbose -b --disable-opt unusedtypechecks --feature ObjCRuntime.Runtime.Arch.IsSimulator false
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(327,3): warning MT4174: Unable to locate the block to delegate conversion method for the method MauiBlazorAppiOSBackgroundNotification.AppDelegate.DidReceiveRemoteNotification's parameter #3.
```

Which then subsequently crashes the application when the function is invoked (receiving a background (remote) notification).

This is why we tried to define the conversion ourselves by copy-pasting the function definition found in an earlier version of Maui (that utilizes Trampolines).

I hope this clarifies it - I can upload a sample project as well - please let me know,
Thanks!

**Comment by Redth** [comment]
@rolfbjarne could you have a look?

**Comment by rolfbjarne** [comment]
I just tried compiling this, and it compiled just fine:

```cs
public partial class AppDelegate : UIApplicationDelegate
{
	public override void DidReceiveRemoteNotification (UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
	{
		Console.WriteLine ("DidReceiveRemoteNotification");
	}
}
```

so I'm not quite sure I understand what you mean when you say this functionality is absent.

Could you attach a sample project that you'd expect to work?

**Comment by rolfbjarne** [comment]
Ah ok, I see the problem now.

I'll have a look.

**Comment by rolfbjarne** [comment]
@Thomr77 can you try adding this to your csproj and see if it makes things work?

```cs
<PropertyGroup>
    <MtouchExtraArgs>--registrar:dynamic</MtouchExtraArgs>
</PropertyGroup>
```

this is not a very good workaround (it'll make the app slower), but it would be great if you could try it out and see if it works, to confirm my theory about what's going on.

**Comment by cfierro-glb** [comment]
@rolfbjarne I'm also experiencing this issue. While @Thomr77 responds, I tried your workaround and it compiles correctly. I'll have to write a bit more code to make sure the methods get called properly on my AppDelegate. I also checked your PR and it seems like we won't be overriding these methods anymore?

**Comment by rolfbjarne** [comment]
> I also checked your PR and it seems like we won't be overriding these methods anymore?

Correct, code like this will work:

```cs
[Export("application:didFailToRegisterForRemoteNotificationsWithError:")]
public void FailedToRegisterForRemoteNotifications(UIKit.UIApplication application, NSError error)
{    
}
```

we'll look up the required information we need by finding a matching method on the `IUIApplicationDelegate` interface (which `MauiUIApplicationDelegate` implements). The bug was that we weren't looking for such interfaces on base classes in certain cases.

**Comment by Thomr77** [comment]
@rolfbjarne - I tried the csproj workaround also and it builds without warning now - brilliant - Tusen Takk!

I have just tested this in isolation as we are a bit worried about moving the app this is for to RC1 from preview 12 - do you think the workaround has quite a noticeable impact on performance?

Also do you know - will the fix be in RC2 already (fingers crossed)?

@cfierro-glb - thanks a lot too btw! 😄

**Comment by rolfbjarne** [comment]
@Thomr77 that's good news!

I have another workaround, with a _much_ smaller perf hit (remove the previous one):

```xml
<PropertyGroup>
    <MtouchExtraArgs>--optimize:-static-block-to-delegate-lookup</MtouchExtraArgs>
</PropertyGroup>
```

> Also do you know - will the fix be in RC2 already (fingers crossed)?

No, but I should be able to get it in RC 3.

**Comment by Thomr77** [comment]
@rolfbjarne - Thanks a lot for the improved workaround and the info.

I quickly tried it and it builds also without warning - excellent!

We will give it a proper go and move the app over to RC1 next.

Thanks again!

**Comment by ElliottBrand** [comment]
Has anyone got this working to receive push notifications? I too was receiving push notifications in past releases (without needing to add DidReceiveRemoteNotification), but I'm a little confused by this thread. Do I now need to write all the logic to build and display a notification when the app is running in the background? I tried adding DidReceiveRemoteNotification and the breakpoint is never hit.

**Comment by Thomr77** [comment]
@ElliottBrand - You should only need to define DidReceiveRemoteNotification if your app requires Background (Remote) notification functionally. This functionality revolves around iOS starting or running your app (if in the background) for a moment when the notification arrives so that the app can update itself with new content.

It sounds very much like your app does not use this - but if it does make sure that the notification you send is configured with 'content-available' : '1' (for more details see <a href="https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html">Apple's Reference</a>) so that an arriving notification will trigger the app/function.

Actually we did to have enough time to  do a 360 test with rolfbjarne's workaround yet...anyway I hope this helps!

**Comment by ElliottBrand** [comment]
Thanks for the response, I'll check to see how I'm sending the notification, but it was working before. I might be misunderstanding things here, but my main point was I didn't need to add the method before and when the push notification came in from apns, and the app wasn't open, it displayed the push notification on the iPhone. Nothing happens now.

**Comment by ElliottBrand** [comment]
Ok, sooooo...I'm going to mention this, in case it becomes helpful to anyone else who reads this later. After trying cleans, rebuilds, certificate updates, and various other things, it turned out my issue was simply that my APNS Settings in Azure Notification Hub was set to Production and needed set back to Sandbox in order to test locally! 😄
