### ISSUE TITLE
Clipping is still not working

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#6260]
### Description

https://github.com/dotnet/maui/pull/5224

Still the above discussed issue is present in RC 1.

I have updated the RC 1 update with the ClipRadiusGallery sample of .NET MAUI sample gallery. Still the corner radius is not set correctly. Only the top left works.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/42271912/164148196-d9588993-e130-45ca-a17e-bfd17cf10924.png)

### Steps to Reproduce

Run the .NET MAUI Sample gallery.
Choose the ClipRadiusGallery sample

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 19041

**Comment by jsuarezruiz** [comment]
Thanks for the feedback @PaulAnderson02. The issue will be fixed by https://github.com/dotnet/maui/pull/5708

**Comment by PaulAnderson02** [comment]
> Hi @PaulAnderson02, just curious where could I get the ClipRadiusGallery project?

https://github.com/dotnet/maui/tree/main/src/Controls/samples/Controls.Sample
