### ISSUE TITLE
Entry and Switch in a Grid

### ISSUE THREAD

**Issue by xxjnaxx** [dotnet/maui#6292]
### Description

Can't use Switches or Entrys inside a Grid. Since Preview 15

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add an Entry and Switch in a Grid
3. Try to click on it. It doesn't work

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Preview 14

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11.0. Windows 10

**Comment by kristinx0211** [comment]
@xxjnaxx Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by xxjnaxx** [comment]
[example.pdf](https://github.com/dotnet/maui/files/8521422/example.pdf)

**Comment by Redth** [comment]
Could you please attach a solution/project which reproduces the issue?  Please see https://github.com/dotnet/maui/blob/main/.github/repro.md for more info.

**Comment by kristinx0211** [comment]
repro this issue on android 11 using this project: [MauiApp10.zip](https://github.com/dotnet/maui/files/8526625/MauiApp10.zip)

**Comment by Mephisztoe** [comment]
I am using a Switch control from within a Grid as well. However, I created a LabeledSwitch custom ContentView containing a Grid that in turn has a StackLayout with two vertical aligned Labels and the Switch horizontally put right of the Labels.

Here is the thing:
Until Preview 14 this worked more or less flawlessly on both Android and iOS.
On RC1 this only works on Android and not at all on iOS. 

On iOS the switch does not seem to get the touch input.

**Comment by jfversluis** [comment]
This is an older issue and seems like a very common scenario that we may have fixed already. Can someone confirm that this is still an issue in the current releases?

**Comment by Laim** [comment]
> This is an older issue and seems like a very common scenario that we may have fixed already. Can someone confirm that this is still an issue in the current releases?

Hey Gerald,

I'm still having this issue on .NET 7.  If I'm running on .NET 6 it works perfectly fine, but on .NET 7 the below appears to prevent the boxes within the grid boxes from being clickable - I can tab into them though. (Android Simulator, Windows)

```csharp
<ScrollView>
        <VerticalStackLayout>
            <Grid RowDefinitions="*,*,*" ColumnDefinitions="*,*,*" Padding="10" RowSpacing="10" ColumnSpacing="10">
                <StackLayout Grid.Row="0" Grid.ColumnSpan="3">
                    <Label Text="Name" FontSize="Subtitle" FontAttributes="Bold"/>
                    <Entry Text="{Binding SubscriptionData.Name}" Keyboard="Text"/>

                    <Label Text="Notes" FontSize="Subtitle" FontAttributes="Bold"/>
                    <Editor Text="{Binding SubscriptionData.Notes}" AutoSize="TextChanges" MaxLength="200"/>

                    <Label Text="Order Number" FontSize="Subtitle" FontAttributes="Bold"/>
                    <Entry Text="{Binding SubscriptionData.OrderNumber}" Keyboard="Text"/>

                    <Grid RowDefinitions="*,*" ColumnDefinitions="*,*" Margin="0,0,0,10">
                        <Label Text="Purchase Price" FontSize="Subtitle" FontAttributes="Bold" Grid.Row="0" Grid.Column="0"/>
                        <Entry Text="{Binding SubscriptionData.PurchasePrice}" Keyboard="Numeric" Grid.Row="1" Grid.Column="0" Margin="0,0,0,0"/>

                        <Label Text="Billing Type" FontSize="Subtitle" FontAttributes="Bold" Grid.Row="0" Grid.Column="1"/>
                        <Picker ItemsSource="{Binding BillingType}" SelectedItem="{Binding SubscriptionData.BillingType}" Grid.Row="1" Grid.Column="1"/>
                    </Grid>
              </Grid>
        </VerticalStackLayout>
</ScrollView>
```

Video: https://app.screencast.com/jHGKY2QJCgr9N?conversation=mtzkIMk08kJrwICbomVffX

**Comment by hartez** [comment]
Just tried this with VS 17.5.2 on all three platforms and it's working as expected.
