### ISSUE TITLE
SearchHandler does not display more than one suggestion

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#6293]
### Description

When entering text in the search box, the suggestion dropdown should offer choices matching the search keywords
But it only shows one choice...

### Steps to Reproduce

Create a SearchHandler to search a list of items

Enter a letter that matches more than one item
The Search Handler drop down shows only the first item
Expected: Should show Paul and Peter

![image](https://user-images.githubusercontent.com/2603287/164189478-4f99efd1-c13a-4ffb-a3f3-7fb40c6959a5.png)

I put a project that reproduces the issue here:

https://github.com/pierre01/SearchHandlerAndroidBug

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 API 30 - Windows 11 Pro 22000.348

### Did you find any workaround?

No - Used to work with XAMARIN

**Comment by kristinx0211** [comment]
verified repro on Android 11 with the repro project.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 4.0. This issue does not repro on Windows 11 and Android emulator (13.0-API 33) with below Project:

SearchHandler shows the correct items.
On Android:
![image](https://user-images.githubusercontent.com/97647558/233576350-5e5d1168-2671-4117-b318-f2072ee730ac.png)
On Windows:
![image](https://user-images.githubusercontent.com/97647558/233576413-284e84e3-395e-4be2-84ee-1f01a8485ad8.png)
