### ISSUE TITLE
Button Command CanExecute does not update the button visual on Windows

### ISSUE THREAD

**Issue by danardelean** [dotnet/maui#6297]
### Description

On Windows on a Button with the Command connected to the viewmodel once the CanExecute method returns false and the button disables even if the value of the method changes to true and the command still evaluate the method the visual of the button on Windows remains disabled.

### Steps to Reproduce

[Project sample](https://1drv.ms/u/s!AuJWJQUKZPJosLwuy4-r7jEcenVXhQ?e=aPsvDL)

Press Reset button which changes the value to false of CanExecute and the button gets disabled
Write a value in both of the Entries and the button will not pass to enabled state on Windows (on Android it works correctly)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows, not repro on Android. Sample Project: [6297.zip](https://github.com/dotnet/maui/files/8520546/6297.zip)

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue with current main branch. We'll do a follow-up.
![issue-6297](https://user-images.githubusercontent.com/6755973/164224941-0f79f0d5-9317-4d46-9bfa-7b32e556a26f.gif)
