### ISSUE TITLE
MenuBarItems are not rendered if Title is not set

### ISSUE THREAD

**Issue by VladislavAntonyuk** [dotnet/maui#6303]
### Description

MenuBarItems are not rendered if Title is not set. (Verified on Windows)

Probably related to https://github.com/dotnet/maui/issues/5210

### Steps to Reproduce

1. Create default .NET MAUI application
2. On MainPage set MenuBarItems:
```
<ContentPage.MenuBarItems>
		<MenuBarItem Text="File">
			<MenuFlyoutItem Text="New" Command="{Binding NewCommand}"/>			
		</MenuBarItem>
	</ContentPage.MenuBarItems>
```
3. Remove Title from the MainPage in AppShell

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 19041

### Did you find any workaround?

Set Title to " "

**Comment by VladislavAntonyuk** [comment]
By the way, BindingCommand of MenuFlyoutItem doesn't work as well

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows. Sample Project: [6303.zip](https://github.com/dotnet/maui/files/8526768/6303.zip)
