### ISSUE TITLE
FlexLayout property values don't have intellisense

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#6325]
### Description

I get properties:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/41873/164296987-6282f948-e08d-4615-aa8e-07191e99cb3d.png">

But not values for those properties:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/41873/164297066-98559ebf-187e-4d2b-82f4-9b6b8f519ea1.png">

This is the same for all FlexLayout properties.

### Steps to Reproduce

Try to get completion suggestions for any FlexLayout property.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

all

### Did you find any workaround?

Memorization

**Comment by drasticactions** [comment]
@mgoertz-msft could this be an Authoring tools issue?

**Comment by mgoertz-msft** [comment]
It's generally a missing designtools TypeConverter issue that would need to be fixed on the MAUI side. Similar to [Bug 1439101](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1439101): [Maui] There should be parse error when setting invalid value to FlowDirection property, which also needs to be fixed on the MAUI side.

**Comment by mgoertz-msft** [comment]
FYI, I created an issue for FlowDirection to track it separately: #6343: There should be parse error when setting invalid value to FlowDirection property

**Comment by v-longmin** [comment]
Verified repro on windows with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro with maui sample template project.

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix As long as the attribute table is loaded it shouldn't matter. However, if Maui.Core is ever used without Maui.Controls then this would not work.
