### ISSUE TITLE
CarouselView Position property not updating after changing ItemsSource

### ISSUE THREAD

**Issue by DoubleDBE** [dotnet/maui#6328]
### Description

When you set `Loop="False"` and change the ItemsSource through binding (directly in code not tested), the `Position` property is not updated when swiping through items.

When you set `Loop="True"`, it works as expected.

There is something weird; when you re-apply the binding of the original collection that was bound at first startup, it magically works again 🤷‍♂️

On windows the `Position` property doesn't work _at all_, iOS seems fine.

### Steps to Reproduce

1. Download this repro project
[CarouselViewPositionBug.zip](https://github.com/dotnet/maui/files/8524501/CarouselViewPositionBug.zip)

2. Start debugging in an emulator and start swiping, you'll see it'll work as expected.

3. Click on `Category 1` and start swiping again, you'll see the position remains 0.

4. Click on `Category 0` and you'll see it magically works again

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 5.0 and up, Windows latest

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android with above project.
