### ISSUE TITLE
Shell on Windows: Navigation not working

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#6329]
### Description

Adding a subpage to a shell entry, the navigation for going back works but is not visible

### Steps to Reproduce

- Get https://github.com/rogerbriggen/Maui_sHell/tree/ShellErrors
- Compile for Windows and run
- Click on events
- Click on detail page
- On top menu nothing is shown to navigate back but clicking left of main you can go back to the event page (Check Android or iOS there it works)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows, not repro on Android with above project.

**Comment by davidortinau** [comment]
I see the back arrow and it works. Closing as fixed.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/41873/166125467-5773f6a5-8158-4ea9-95a8-3c09c6fa259f.png">
