### ISSUE TITLE
Shell on Windows: Icons not shown

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#6330]
### Description

The shell on windows just shows text if you set text and an icon. iOS and Android show both.

### Steps to Reproduce

- download https://github.com/rogerbriggen/Maui_sHell/tree/ShellErrors
- compile and run for windows
- see the tabs

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 21H1

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
@rogerbriggen not repro your issue on windows. text and icon both show on windows.
![image](https://user-images.githubusercontent.com/99457000/164352640-1ec176cb-f855-4e51-8988-5f17ada3106b.png)

**Comment by rogerbriggen** [comment]
Hi @kristinx0211 
This is how it looks on my machine:
![image](https://user-images.githubusercontent.com/46163208/164381927-8c84c325-71cb-4b8e-acb6-ce825b55f444.png)
Windows 10 Pro 21H1 (Build 19043.1645) German, Maui RC1, Visual Studio Pro 17.2 Pre 4
Unfortunately, I can run the windows packaged apps only out of Visual Studio and unpackaged apps still don't work so I cannot easily run it on another computer.

**Comment by rogerbriggen** [comment]
I checked on a other computer with Windows 10 Pro German, 21H2, Build 19044.1645, Maui Rc1 and Visual Studio Community 17.2 Pre 3 and it looks the same, no Icons.
Also, in Visual Studio XAML Live Preview, there are no icons visible.

**Comment by rogerbriggen** [comment]
On the computer of my mate it is also the same and it seems other user have the same problem https://github.com/dotnet/maui/issues/6369

**Comment by davidortinau** [comment]
Confirmed icons appear on main (rc3)

<img width="477" alt="image" src="https://user-images.githubusercontent.com/41873/166125498-6dde5c32-5a7e-4821-a6c8-87907846f083.png">
