### ISSUE TITLE
Shell on iOS: icons are not scaled

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#6331]
### Description

Icons used in the shell are not scaled as on android.
This is very frustrating since it kills the advantage of svg files in the project.

### Steps to Reproduce

- download https://github.com/rogerbriggen/Maui_sHell/tree/ShellErrors
- compile and run on iOS
- see the icons and compare with android

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4.1

### Did you find any workaround?

Scaling down the original svg file which is not a good solution at all

**Comment by v-longmin** [comment]
Verified repro on iOS 15.4, not repro on Android with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro project:
[Maui_sHell-ShellErrors.zip](https://github.com/dotnet/maui/files/8526943/Maui_sHell-ShellErrors.zip)

**Comment by Redth** [comment]
You can adjust the scaling by specifying a BaseSize on your MauiImage and then use the generated PNG's.

See the resizetizer info for more details: https://github.com/Redth/ResizetizerNT#basesize (the base size logic works the same in MAUI).

**Comment by rogerbriggen** [comment]
OK, this is sad. It works fine on Android (and there you can even use the svg and is resized properly automatically). This would also speed up the build a lot since the resizetizer needs a lot of time.

**Comment by Redth** [comment]
iOS doesn't support SVG in the platform controls, not much we can do about that.  Resizetizer doesn't need a lot of time really, and the images are generated and cached for incremental builds so that is a no-op when appropriate.

**Comment by J-Swift** [comment]
iOS supports both svg and pdf vectors natively. I outline the process here https://github.com/dotnet/maui/discussions/3016#discussioncomment-2586401

**Comment by Redth** [comment]
Sorry, what I meant is that there's extra processing work on iOS to support it that is not work in scope for right now.  The other part of this is that Android vector drawables are a very limited subset of SVG and there is no great library/code out there to do the conversion that is reliable enough based on my experience.  The one you linked to looks like it basically uses an old version of Google's code from Android Studio (which I at one point ported to C# and it proved VERY limited in what .svg's it could successfully process).   Given the inconsistency of Android, the value of supporting .svg's directly without rasterizing them in MAUI is currently diminished and at best confusing to users who don't understand the nuance here.

It's something I'd love to support more cleanly in the future, but that's not a .NET 6 timeframe thing for MAUI.

**Comment by rogerbriggen** [comment]
First: Thanks for the comments.
On CI we are not doing incremental builds because there are a lot of problems with maui if you change branches and are using incremental builds.
It seems it is supported with XCode 12 and iOS 13 and newer (https://www.avanderlee.com/xcode/svg-image-assets/).

**Comment by J-Swift** [comment]
@Redth  I believe the android is current. Its the exact code that powrers android studios conversion i believe. At least based on my research it was (i wrote the conversion library). So its as close to “native” experience as you will find

**Comment by Redth** [comment]
> @Redth I believe the android is current. Its the exact code that powrers android studios conversion i believe. At least based on my research it was (i wrote the conversion library). So its as close to “native” experience as you will find

Yep unfortunately the converter in android studio is woefully lacking and it’s pretty easy to throw images at it which fail. It’s not reliable enough for general use here in my opinion.
