### ISSUE TITLE
Shell on iOS: completly black screen with .svg files in xaml

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#6332]
### Description

Add an .svg file for your icons in the shell in your xaml file. You only see a completly black screen because of an exception.

### Steps to Reproduce

- download https://github.com/rogerbriggen/Maui_sHell/tree/svgOnIos
- compile and run for iOS
- all is black
- to fix: rename .svg to .png in AppShell.xaml -> but then you have problem https://github.com/dotnet/maui/issues/6331

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4.1

### Did you find any workaround?

do not use .svg but this is not funny if you need to scale

**Comment by v-longmin** [comment]
Verified repro on iOS 15.4 with vs 17.3.0 Preview 1.0 [32414.199.main]. Repro project:
[Maui_sHell-svgOnIos.zip](https://github.com/dotnet/maui/files/8526904/Maui_sHell-svgOnIos.zip)

**Comment by Redth** [comment]
SVG files are not directly supported.  You can adjust the scaling by specifying a BaseSize on your MauiImage and then use the generated PNG's.

See the resizetizer info for more details: https://github.com/Redth/ResizetizerNT#basesize (the base size logic works the same in MAUI).

**Comment by J-Swift** [comment]
You can use svg's natively with some slight configuration. I outline the process a bit here: https://github.com/dotnet/maui/discussions/3016#discussioncomment-2586401
