### ISSUE TITLE
Shell on Windows: It is really ugly

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#6334]
### Description

On top you have a big grey bar from the window. 
Then you have again a big area for the shell items which look nice on Android and iOS where they are at the bottom. On Windows they are on top, huge, and really ugly.

### Steps to Reproduce

- download https://github.com/rogerbriggen/Maui_sHell/tree/ShellErrors
- compile and run on Windows
- see the looks of the shell items and the window

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 21H1

### Did you find any workaround?

-

**Comment by PureWeen** [comment]
Try again on RC2

If you still don't it please include screen shots

Shell/NavigationPage/TabbedPage all just use

https://docs.microsoft.com/en-us/windows/apps/design/controls/navigationview

If there's something we're doing that deviates from how NavigationView looks then we can fix.
If it's the same as NavigationView then we can look at adding APIs for you to adjust
