### ISSUE TITLE
Latest update broke build on all working maui/ blazor solutions

### ISSUE THREAD

**Issue by irinaAtBias** [dotnet/maui#6336]
### Description

I have several maui/blazor  VS2022 preview solutions. In fact, I was running one this morning and even debugged on (deployed to )  my phone.  I updated VS2022 to the newest **Version 17.2.0 Preview 4.0.**  I have not been able to build any of my projects after that.  I tried to update the packages, but it brought even more issues along with installing packages that are not even supposed to be there. Here is what one of the solutions gives before i updated packages 
![before](https://user-images.githubusercontent.com/58484921/164318501-75eca112-f401-4c6c-961a-d253e63d9d53.PNG)
and it actually installed them where they should not even been, here is screen shot(different solution) where packages in question were updated. It also brought new issues.  This last solution was created in previous version of VS preview
![after](https://user-images.githubusercontent.com/58484921/164319674-2b11f196-1330-48cc-acd2-b5a39d82ef1b.PNG)
![image](https://user-images.githubusercontent.com/58484921/164319894-c655ad4c-2d4c-4630-ad9c-e4074fa0da5b.png)
I did not proceed to update my other packages since it seems to be useless, but created a new project  in updated VS where I  am installing things  and plan to move code there. However, my concern is that the next update will ruin it .

### Steps to Reproduce

1Open any maui/blazor solution that was created under previous versions of VS2022 preview. The default "hello World!" would do. 2 Build it using VS2022 Version 17.2.0 Preview 4.0

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Android 11 and up, Windows 10

### Did you find any workaround?

created a  new solution in updated version of VS2022 Preview 17.2.0 Preview 4.0

### Relevant log output

```shell
from default Hello world app created under one of previous versions: Rebuild started...
1>------ Rebuild All started: Project: MauiAppTestEmu, Configuration: Debug Any CPU ------
Failed to restore C:\Users\klepa\source\repos\MauiAppTestEmu\MauiAppTestEmu\MauiAppTestEmu.csproj (in 803 ms).
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>C:\Users\klepa\source\repos\MauiAppTestEmu\MauiAppTestEmu\MauiProgram.cs(12,5,12,30): error CS1061: 'MauiAppBuilder' does not contain a definition for 'RegisterBlazorMauiWebView' and no accessible extension method 'RegisterBlazorMauiWebView' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?)
1>Done building project "MauiAppTestEmu.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by drasticactions** [comment]
Did you follow this? https://github.com/dotnet/maui/wiki/Migrating-to-RC1

And specifically this? https://github.com/dotnet/maui/wiki/Migrating-to-RC1#windows-package-references

**Comment by irinaAtBias** [comment]
@drasticactions no, I did not, I check it out, thank you!

**Comment by irinaAtBias** [comment]
@drasticactions I followed recommendations and was able to fix issues in the default app, also removed some of them in another app. Unfortunately some of the problems persist.  I have to look  further. Thank you for your help!

**Comment by v-longmin** [comment]
Verified repro on Android 12.0, iOS15.4 & windows 10 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro project:
[MauiFlyout.zip](https://github.com/dotnet/maui/files/8526869/MauiFlyout.zip)

**Comment by drasticactions** [comment]
Cool, glad to see it works now!

For anyone else who hits this with an existing project, be sure to upgrade your dependencies and run through this: https://github.com/dotnet/maui/wiki/Migrating-to-RC1
