### ISSUE TITLE
[Enhancement] "net5.0" cross-platform main assembly loads MAUI assembly that targets Windows and macOS

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/maui#634]
## Summary
Make an assembly of a main project with target framework "net5.0" able to load MAUI assembly that targets Windows and macOS. Loading is done using the "Assembly" class.

## API Changes
none.

## Intended Use Case
A project that is cross-platform and has one main assembly and dynamically loads Windows or macOS assembly.

**Comment by PureWeen** [comment]
@aaabbbcccddd00001111 .NET MAUI will only be able to compile on net6.0
