### ISSUE TITLE
There should be parse error when setting invalid value to FlowDirection property

### ISSUE THREAD

**Issue by mgoertz-msft** [dotnet/maui#6343]
### Description

FlowDirection is an enum and normally we would get IntelliSense values and validation. Unfortunately, there is this that breaks it all:

https://github.com/dotnet/maui/blob/cdf43dafaf2dd30ec8732adcb4df855465e9623f/src/Controls/src/Core/FlowDirectionConverter.cs

Its only purpose seems to be to allow additional values for ltr, rtl, and inherit as short forms for existing enum values. Possible ways to improve this would be (in order of complexity):

1. Remove the converter and lose ltr, rtl, and inherit

2. Remove the converter and add ltr, rtl, and inherit to the FlowDirection enum mapping to the same values

3. Add GetStandardValues to the converter, to at least get the enum values back in IntelliSense (still no validation for invalid values though)

4. Create a designtools.dll converter that does it all

### Steps to Reproduce

1. New Maui app
2. Open MainPage.xaml
3. Add `<FlexLayout FlowDirection='leftToRight'/>`

**Expected:**
Parse error as leftToRight is not valid for FlowDirection

**Actual:**
No error

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly), I was *not* able test on other platforms

### Affected platform versions

Not a platform-specific issue

**Comment by v-longmin** [comment]
Verified repro on Android 12.0-API31 & iOS 15.4, not repro on windows. Repro project:
[MauiApp19.zip](https://github.com/dotnet/maui/files/8526821/MauiApp19.zip)

**Comment by shimingsg** [comment]
that would be exception thrown like below according to https://github.com/dotnet/maui/blob/cdf43dafaf2dd30ec8732adcb4df855465e9623f/src/Controls/src/Core/FlowDirectionConverter.cs
![image](https://user-images.githubusercontent.com/20982341/164408680-a50be275-ad32-421f-b0f9-a025b0dc9a7d.png)
@v-longmin , I can repro on windows, the value of FlowDirection is case sensitivity.
Enhancement suggestion that making it case insensitivity since no intelligence when inputting enum value here.

**Comment by mgoertz-msft** [comment]
Either one of my proposals above would add IntelliSense for FlowDirection values. I had already talked about this with @Redth who favored option 4.

**Comment by StephaneDelcroix** [comment]
`rtl` `ltr` and `inherit` are only there to support CSS conversions. it's fine if we get an error when used in Xaml

**Comment by Redth** [comment]
Ok, so we only care about the enum values in XAML.

@mgoertz-msft  It's not clear to me the actions required now.  If we want the XAML editor to only accept values from the enum of  `LeftToRight`, `RightToLeft` or `MatchParent`, what do we need to do?

**Comment by mgoertz-msft** [comment]
@Redth I left this comment in your PR:
> @Redth You just need to remove inherit, ltr, and rtl from this DT converter and the XAML editor complain about anything that isn't one of the first three values.

**Comment by StephaneDelcroix** [comment]
@mgoertz-msft so I understand correctly... the simple fact that the type is attributed with a [TypeConverter] disengage intelliSense validation for enums ? or does IntelliSense actually try to instantiate Maui's FlowDirectionTypeConverter ? Thx for the clarification

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix Correct, the fact that there is a runtime type converter, which we cannot instantiate, tells us that there's special handling that we don't understand, so anything is considered valid - unless you also have a design time type converter, which we do instantiate.
