### ISSUE TITLE
Changing ApplicationDisplayVersion in csproj causes problems

### ISSUE THREAD

**Issue by trevortirrell** [dotnet/maui#6351]
### Description

If I change the ApplicationDisplayVersion in csproj, or on the projects property page causes problems. The NuGet manager shows "No packages found" on Installed tab. Also the project won't build and gives the following error:

Error	NU1105	Unable to read project information for 'ProjectName': Sequence contains more than one element...

### Steps to Reproduce

Right click and edit csproj file or
Open project properties
Change ApplicationDisplayVersion to anything other than 1.0

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

Change ApplicationDisplayVersion back to 1.0

**Comment by trevortirrell** [comment]
This is a duplicate
https://github.com/dotnet/maui/issues/3690 
https://github.com/dotnet/maui/issues/6040

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows and Android. Sample Project:
[MauiApp1.zip](https://github.com/dotnet/maui/files/8527671/MauiApp1.zip)

**Comment by drasticactions** [comment]
This is a duplicate, as mentioned above.
