### ISSUE TITLE
ClearButtonVisibility is not working

### ISSUE THREAD

**Issue by xxjnaxx** [dotnet/maui#6360]
### Description

Its not possible to delete the text in an entry with ClearButtonVisibility="WhileEditing". The button is shown but don't delete the text.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Create a LoginView like so:

<StackLayout Margin="0,50,0,0" >
                    <Label FontFamily="OpenSansRegular" TextColor="{StaticResource SecondaryColor}" FontSize="16" Text="E-Mail"/>
                    <Grid Margin="0,5">
                        <Frame Opacity="0.3" BackgroundColor="Transparent" CornerRadius="5"/>
                        <Entry x:Name="Entry_Email"  Keyboard="Email" IsTextPredictionEnabled="False" FontFamily="OpenSansRegular"  ClearButtonVisibility="WhileEditing" BackgroundColor="Transparent" Placeholder="Enter E-Mail"  Margin="5,0" TextColor="{StaticResource SecondaryColor}" PlaceholderColor="LightGray"/>
                    </Grid>

                    <Label FontFamily="OpenSansRegular" TextColor="{StaticResource SecondaryColor}" FontSize="16" Text="Passwort"/>
                    <Grid Margin="0,5" >
                        <Frame Opacity="0.3" BackgroundColor="Transparent" CornerRadius="5"/>
                        <Entry x:Name="Entry_Password" FontFamily="OpenSansRegular" IsTextPredictionEnabled="False" IsPassword="True" ClearButtonVisibility="WhileEditing" BackgroundColor="Transparent" Placeholder="Enter Password"  Margin="5,0" TextColor="Black" PlaceholderColor="LightGray"/>

                    </Grid>

                </StackLayout>

3.  enter some text and try to delete it. It isn't working

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 13

### Affected platforms

Android, Windows

### Affected platform versions

Android 11 and up, Windows 10

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Sample Project: 
Not Repro on Windows, text can be deleted.
![ClearText](https://user-images.githubusercontent.com/97647558/164411882-649f6733-e89f-4bc9-9f38-d17faca1829a.gif)

Clear button is invisible for Android.
![image](https://user-images.githubusercontent.com/97647558/164411241-b2b8881c-b89f-419f-ba64-4f31e8cac1d4.png)

**Comment by xxjnaxx** [comment]
It is visible on Android with 2 Entrys:

1.  input entry 1
2. switch to entry 2
3. input entry 2
4. switch to entry 1
  now the button is visible. But its not possible to delete the input

**Comment by jsuarezruiz** [comment]
This issue have been fixed. Could you try again with the latest version?.
![fix-6360](https://user-images.githubusercontent.com/6755973/186699807-459177b0-9b86-4b5d-9b6d-39a2d5ca2165.gif)
