### ISSUE TITLE
Shell on Android: Icons not Shown (RC1)

### ISSUE THREAD

**Issue by xxjnaxx** [dotnet/maui#6361]
### Description

Similar to case #6294 which was closed. 

Since 17.2.0 Preview 3.0 (RC1) 

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a AppShell with some FlyoutItems like so:

<FlyoutItem.Icon>
        <FontImageSource FontFamily="FS900" Glyph="{x:Static fontAwesome:FontAwesomeIcons.Mobile}" Color="{StaticResource PrimaryColor}" >
        </FontImageSource>
    </FlyoutItem.Icon>
    <ShellContent ContentTemplate="{DataTemplate local:DevicesPage}"
                  Route="geraete"  />
</FlyoutItem>

3. Debug -> the place will be empty. ( see screenshot in description)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android

### Affected platform versions

Android 11 and up

**Comment by kristinx0211** [comment]
@xxjnaxx Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by devonuto** [comment]
I've also got this issue

**Comment by xxjnaxx** [comment]
[example.pdf](https://github.com/dotnet/maui/files/8537500/example.pdf)

**Comment by kristinx0211** [comment]
@xxjnaxx Could you please attach a solution/project which reproduces the issue? Please see https://github.com/dotnet/maui/blob/main/.github/repro.md for more info.

**Comment by xxjnaxx** [comment]
https://github.com/xxjnaxx/Test1

Now there are also problems with Windows

**Comment by VincentBu** [comment]
still repro with vs main build
![image](https://user-images.githubusercontent.com/44959937/167547599-e464ade2-5f60-432b-bfee-bd885bc5f7b0.png)

**Comment by devonuto** [comment]
@xxjnaxx This looks to be working for me as of Version 17.3.0 Preview 1.0

**Comment by samhouts** [comment]
This is working on 6.0.300-rc.4.5760
![image](https://user-images.githubusercontent.com/7827070/167954844-6b30fbf1-24f6-43ca-9649-9d233d02053c.png)
