### ISSUE TITLE
RC1 - EllipseGeometry does not work

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#6363]
### Description

I have noticed that EllipseGeometry is not working in .NET Maui, I have tried the same case in Xamarin.Forms and it does work. I have tried to circle an image using EllipseGeometry but it doesn't work. As additional data if you have the application running and you replace the Image control with an ImageButton and reload with Hot Reload if it shows circular, however if you run the application directly with an ImageButton it does not work.

### Steps to Reproduce

Run the following code and you will notice that EllipseGeometry is not working, however the same code in Xamarin.Forms does:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             BackgroundColor="White"
             x:Class="MauiCollectionView.MainPage">
    <StackLayout>
        <Image 
               Source="dotnet_bot.svg"
               BackgroundColor="Red"
               HorizontalOptions="Center"
               VerticalOptions="Start"
               Aspect="AspectFit"
               HeightRequest="60"
               WidthRequest="60">
            <Image.Clip>
                <EllipseGeometry
                        Center="30,30"
                        RadiusX="30"
                        RadiusY="30" />
            </Image.Clip>
        </Image>
    </StackLayout>
</ContentPage>
```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows and Android. Sample Project: [6363.zip](https://github.com/dotnet/maui/files/8529478/6363.zip)

**Comment by jsuarezruiz** [comment]
Taking a quick review the clipping is aplied but the image Frame (position and size) is wrong. 

For example, here:
![clipping-issue-01](https://user-images.githubusercontent.com/6755973/164460649-78b9704c-999b-4243-a8cc-3ca95a1c8bc1.gif)

The initial image size is wrong, and clipping we cannot see anything.

In the gallery to measure the performance clipping:
![image](https://user-images.githubusercontent.com/6755973/164460759-847a15c6-dd0d-4524-9ee9-70dc23d64159.png)

Everything is wrong also in the sample without apply the clip:

![image](https://user-images.githubusercontent.com/6755973/164460846-c52846f1-55e5-4fd6-9117-118122aec413.png)

Seems to be related with changes in Glide. We need to investigate this deeply.

**Comment by jsuarezruiz** [comment]
Cannot longer reproduce the issue in main branch:
![Screenshot_1653385702](https://user-images.githubusercontent.com/6755973/170003732-1de757ba-4c6c-4a69-8ae5-8581e9815d77.png)
