### ISSUE TITLE
RC1 - Image with AspectFill does not appear inside some Layouts

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#6365]
### Description

When an image is configured with AspectFill, it is not displayed if it is inside most Layouts, it will only be displayed if it is inside an AbsoluteLayout or a FlexLayout, the rest of the Aspect property values work correctly, it only happens with AspectFill. In Xamarin.Forms it shows up perfectly in any scenario.

### Steps to Reproduce

Try the following code in .NET Maui and you should see that the image doesn't display unless the parent layout is AbsoluteLayout or FlexLayout, it only happens if the Aspect is set to AspectFill.

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             BackgroundColor="White"
             x:Class="MauiCollectionView.MainPage">
    <VerticalStackLayout 
        HorizontalOptions="FillAndExpand"
        VerticalOptions="FillAndExpand">
        <Image
              HorizontalOptions="Center"
              VerticalOptions="Center"
              Source="dotnet_bot.svg"
              Aspect="AspectFill"
              HeightRequest="100"
              WidthRequest="100"/>
    </VerticalStackLayout>
</ContentPage>
```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android and Windows. Sample Project: [6365.zip](https://github.com/dotnet/maui/files/8535883/6365.zip)
