### ISSUE TITLE
RC1 - DeviceStateTrigger Device not work

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#6366]
### Description

I have tried to detect the running platform through a VisualState in the XAML and it seems that the "DeviceStateTrigger Device" is either not implemented or not working. In Xamarin.Forms it works perfectly.

IntelliSense also doesn't work and doesn't show help with available platforms as you type. In Xamarin.Forms this in particular was not implemented but it might be convenient to add it in .NET Maui:

<img width="635" alt="Issue01" src="https://user-images.githubusercontent.com/20904914/164438012-4f58af96-0850-4e7b-8391-b0ae2672ddbf.png">

### Steps to Reproduce

The following code snippet should set the Frame BackgroundColor to red if it's running on an Android device:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             BackgroundColor="White"
             x:Class="MauiCollectionView.MainPage">
    <VerticalStackLayout 
        HorizontalOptions="FillAndExpand"
        VerticalOptions="FillAndExpand">
        <Frame
              HorizontalOptions="Center"
              VerticalOptions="Center"
              HeightRequest="100"
              WidthRequest="100">
            <VisualStateManager.VisualStateGroups>
                <VisualStateGroup>
                    <VisualState
                        x:Name="Android">
                        <VisualState.StateTriggers>
                            <DeviceStateTrigger Device="Android" />
                        </VisualState.StateTriggers>
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor" Value="Red" />
                        </VisualState.Setters>
                    </VisualState>                    
                </VisualStateGroup>
            </VisualStateManager.VisualStateGroups>
        </Frame>
    </VerticalStackLayout>
</ContentPage>
```

This is the StackTrace of the InnerException of the exception that occurs:

```
   at Microsoft.Maui.Devices.DevicePlatform..ctor(String devicePlatform) in D:\a\_work\1\s\src\Essentials\src\Types\DevicePlatform.shared.cs:line 45
   at Microsoft.Maui.Devices.DevicePlatform.Create(String devicePlatform) in D:\a\_work\1\s\src\Essentials\src\Types\DevicePlatform.shared.cs:line 52
   at Microsoft.Maui.Controls.DeviceStateTrigger.UpdateState() in D:\a\_work\1\s\src\Controls\src\Core\DeviceStateTrigger.cs:line 33
   at Microsoft.Maui.Controls.DeviceStateTrigger..ctor() in D:\a\_work\1\s\src\Controls\src\Core\DeviceStateTrigger.cs:line 11
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
```

In Xamarin.Forms this works perfectly.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Release Candidate 1 (current)

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 -API 31 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro with above code.
