### ISSUE TITLE
Expected Style but found Microsoft.Maui.Controls.DataTrigger.

### ISSUE THREAD

**Issue by AllenMiaoFil** [dotnet/maui#6367]
### Description

When I tried to start application in windows platform, I met "Expected Style but found Microsoft.Maui.Controls.DataTrigger." exception. You can see my screenshot below. And I also attached project zip file.
![image](https://user-images.githubusercontent.com/100921408/164442551-e184067e-701d-40dc-8a12-bd4937657d0b.png)

[MauiApp5.zip](https://github.com/dotnet/maui/files/8530283/MauiApp5.zip)

### Steps to Reproduce

1. I created a MAUI project base on 6.0.300-rc.1.5355.
2. Created a ButtonType enum file for identifying different button type.
3. Created a custom control file named MyButton derived from ContentView. and added a maui button.
4. Added style and data trigger in custom control.
5. Added custom control into MainPage xaml file.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Window 10

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows. Sample Project: [6367.zip](https://github.com/dotnet/maui/files/8536023/6367.zip)

**Comment by AllenMiaoFil** [comment]
I met same issue when i tried to use MultiTrigger. 

![image](https://user-images.githubusercontent.com/100921408/164661854-43720485-234e-4dc6-833c-1ff8e6dcb7b5.png)

with below code: 
<MultiTrigger TargetType="local:MyButton" BindingContext="{x:Reference this}">
                    <MultiTrigger.Conditions>
                        <BindingCondition Binding="{Binding ButtonType}" Value="{x:Static local:ButtonTypes.Icon}"/>
                        <BindingCondition Binding="{Binding ButtonType2}" Value="{x:Static local:ButtonTypes2.Primary}"/>
                    </MultiTrigger.Conditions>
                    <Setter Property="VisualStateManager.VisualStateGroups">
                        <VisualStateGroupList>
                            <VisualStateGroup Name="ButtonStates">
                                <VisualState Name="Normal">
                                </VisualState>
                                <VisualState Name="Pressed">
                                    <VisualState.Setters>
                                        <Setter Property="TextColor" Value="Green"/>
                                        <Setter Property="BackgroundColor" Value="Yellow"/>
                                    </VisualState.Setters>
                                </VisualState>
                                <VisualState Name="Focused">
                                    <VisualState.Setters>
                                        <Setter Property="TextColor" Value="Yellow"/>
                                        <Setter Property="BackgroundColor" Value="Red"/>
                                    </VisualState.Setters>
                                </VisualState>
                                <VisualState Name="Disabled">
                                    <VisualState.Setters>
                                        <Setter Property="TextColor" Value="Gray"/>
                                        <Setter Property="BackgroundColor" Value="Black"/>
                                    </VisualState.Setters>
                                </VisualState>
                            </VisualStateGroup>
                        </VisualStateGroupList>
                    </Setter>
                </MultiTrigger>

**Comment by StephaneDelcroix** [comment]
In both the OP and @AllenMiaoFil the xaml parser as some trouble finding the TargetType on the hierarchy. As we're working on this, you can help it by fully qualifying your properties

```xaml
<Setter Property="Button.TextColor" Value="Blue"/>
```
