### ISSUE TITLE
BorderColor does not work on visualStateManager

### ISSUE THREAD

**Issue by AllenMiaoFil** [dotnet/maui#6370]
### Description

When I tried to modify BorderColor with VisualStateManager, I found it doesn't work. 

### Steps to Reproduce

1. Created a new MAUI project.
2. Add Button and Set BorderWidth. 
3. Add Styles for button(TextColor, BorderColor,BackgroundColor).
[MauiApp6.zip](https://github.com/dotnet/maui/files/8530535/MauiApp6.zip)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Window 10

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows with above project.
Button styles not worked for Pressed, Focused event.
![ButtonStyle](https://user-images.githubusercontent.com/97647558/164589946-6adfc5a3-c618-4f17-9a83-77be65719682.gif)

**Comment by StephaneDelcroix** [comment]
I think the Color/Brush issue has been fixed. @mattleibow ?

**Comment by davidortinau** [comment]
Able to repro on main (rc3)

**Comment by kajzik** [comment]
Also does not change in Style.Triggers.

**Comment by mattleibow** [comment]
The Color/Brush was just for Background. I just tested the issue and the colors change if you click and hold and stuff. I think the states are just wrong. So if I click and hold, then it is "focused" and when I release it switched to pressed.

**Comment by StephaneDelcroix** [comment]
I confirm what @mattleibow said, the VSM is fine, the states are not correctly set

**Comment by AllenMiaoFil** [comment]
Hey @jsuarezruiz, I've just tested on Windows with RC2, and it does not work with pervious zip project right now. May I know what you want from my side?

**Comment by jsuarezruiz** [comment]
> Hey @jsuarezruiz, I've just tested on Windows with RC2, and it does not work with pervious zip project right now. May I know what you want from my side?

Have done some tests with main branch and the latest version. The border color updates. This is the behavior:

![issue-6370](https://user-images.githubusercontent.com/6755973/170458104-79b5e9dc-2ed3-42b1-9193-460ddf28ca46.gif)

Are you expecting a different behavior?, could you try the latest version again?

**Comment by AllenMiaoFil** [comment]
@jsuarezruiz Thanks for your update!  May I know what's the latest version? I've tested with RC3, there are still have some issues, like when I set "Pressed" state with BorderColor; There is no update when I was holding pressed button.

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz Thanks for your update! May I know what's the latest version? I've tested with RC3, there were still some issues, like when I set "Pressed" state with BorderColor; There was no BorderColor update when I was holding pressed button.

Testing and comparing with Android, there are some differences. The current behavior on Windows is:

1. By default the Button have the Normal state.
2. Tapping the Button, after pressing it the state is Pressed.
3. Then, with the mouse up event the Button receive the Focused state.
4. The Focused state changes if for example tap outside or another control. The state is back to Normal.

Let me review this more, but I think we can try to align the behavior here.

**Comment by AllenMiaoFil** [comment]
Yes, would you mind to try below steps on windows?
1. Create VSM for button with Normal, Pressed, Focused and Disabled states
2. Set different BorderColor for different state.
3. Keep pressing button to check BorderColor.(Pressed)
4. Move up to check BorderColor and don't move mouse out of button.(this step looks like Hover state but we've never set it, and as I know it is unavailable for now)
5. based on step 4, move out from button.  then check button state.(Focused)

Note: If I fire Pressed state with right click. It was more like Pressed state.  

Let me know if I misunderstand anything.

**Comment by AllenMiaoFil** [comment]
Hey Team, I also find ImageButton borderColor does not work when we change state

**Comment by PureWeen** [comment]
duplicate https://github.com/dotnet/maui/issues/7570

**Comment by samhouts** [comment]
Duplicate of #7570
