### ISSUE TITLE
CollectionView on Android does not show new objects if it starts with 0 objects

### ISSUE THREAD

**Issue by DavidCarKc** [dotnet/maui#6386]
### Description

If there are objects in list which is ItemsSorce for CollectionView, and I load the list into view in public MainPage() and the use a Button to add new objects and add them to the list and list to the view they will be shown on Windows and Android 
BUT if the page loads with empty CollectionView and I add new object with button then in windows it will be shown but on Android it will stay empty, add second object, windows shows both android none, etc

Another interesting thing is if there is a Button bellow CollectionView in Xaml and the CollectionView is empty then when you click on ClickMe button not even the LabelClicked would get updated it will stay as NUMBER OF OBJECTS:  without the number. 

Both cases are problem in Android app and work as they sould in Windows app.

### Steps to Reproduce

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 4.0

Create new Maui project  MauiCollectionViewTestV172P4
Replace mainpage.xaml and mainpage.xaml.cs with attached files
in .cs file uncomment after //UNCOMMENT THIS CODE BELLOW TO ADD 2 objects to the list

[MauiCollectionViewTestV172P4.zip](https://github.com/dotnet/maui/files/8534601/MauiCollectionViewTestV172P4.zip)
[MauiCollectionViewTestV172P4WithButton.zip](https://github.com/dotnet/maui/files/8534831/MauiCollectionViewTestV172P4WithButton.zip)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 5 and 9 phones

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 -API 31 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro project：
[MauiApp1.zip](https://github.com/dotnet/maui/files/8536285/MauiApp1.zip)

**Comment by shimingsg** [comment]
verified not repro on Windows and Android 5/12 with VS 17.3.0 Preview 2.0 [32506.315.main].
if hit again with similar/newer environment please open new issue.
