### ISSUE TITLE
Run on iOS Physical Device - error MT1216: Could not find the simulator UDID 

### ISSUE THREAD

**Issue by dylanberry** [dotnet/maui#6395]
### Description

When attempting to build/run on a physical iOS device, the build fails stating `error MT1216: Could not find the simulator UDID`.

### Steps to Reproduce

1. Create a new maui app: `dotnet new maui -n "MyMauiApp"`
2. Lookup device UUID in xcode
3. Build/run: `dotnet build -t:Run -f net6.0-ios -p:_DeviceName=:v2:udid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

macOS 12.2 21D49 (x86), xcode 13.3.1 (13E500a), iOS 15.4.1, .NET SDK 6.0.300-preview.22179.2

### Relevant log output

```shell
Microsoft (R) Build Engine version 17.2.0-preview-22178-03+1160f4e0e for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/dylanberry/Projects/MyMauiApp/MyMauiApp.csproj (in 735 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Detected signing identity:
          
    Bundle Id: com.companyname.mymauiapp
    App Id: com.companyname.mymauiapp
  MyMauiApp -> /Users/dylanberry/Projects/MyMauiApp/bin/Debug/net6.0-ios/iossimulator-x64/MyMauiApp.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
EXEC : error MT1216: Could not find the simulator UDID 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'. [/Users/dylanberry/Projects/MyMauiApp/MyMauiApp.csproj]
          
/usr/local/share/dotnet/sdk/6.0.300-preview.22179.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(901,5): error MSB3073: The command "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.100-rc.1.125/tools/bin/mlaunch --launchsim bin/Debug/net6.0-ios/iossimulator-x64/MyMauiApp.app/ --device :v2:udid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --stdout /dev/ttys007 --stderr /dev/ttys007 --wait-for-exit" exited with code 1. [/Users/dylanberry/Projects/MyMauiApp/MyMauiApp.csproj]

Build FAILED.

EXEC : error MT1216: Could not find the simulator UDID 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'. [/Users/dylanberry/Projects/MyMauiApp/MyMauiApp.csproj]
/usr/local/share/dotnet/sdk/6.0.300-preview.22179.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(901,5): error MSB3073: The command "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.100-rc.1.125/tools/bin/mlaunch --launchsim bin/Debug/net6.0-ios/iossimulator-x64/MyMauiApp.app/ --device :v2:udid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --stdout /dev/ttys007 --stderr /dev/ttys007 --wait-for-exit" exited with code 1. [/Users/dylanberry/Projects/MyMauiApp/MyMauiApp.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:10.93
```

**Comment by aokocax** [comment]
You should not write the udid line when running on the physical device. 

Your terminal command sholud be
dotnet build -t:Run -f net6.0-ios -p:_DeviceName=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -c Debug

aslo add these to your project file with your identities

<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
	<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<CodesignKey>Apple Development: Xxxx Xxxx (Xxxxxxx)</CodesignKey>
		<CodesignProvision>VS: WildCard Development</CodesignProvision>
	
</PropertyGroup>
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
	<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<CodesignKey>Apple Development: Xxxx Xxxxx (Xxxxx)</CodesignKey>
		<CodesignProvision>VS: WildCard Development</CodesignProvision>

</PropertyGroup>

**Comment by dylanberry** [comment]
Thanks for the suggestions, @aokocax. 

### Fix

Tne fix is to add the `RuntimeIdentifier` in the csproj:

```xml
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
	</PropertyGroup>
```

### Additional Information

The codesign configuration in the project file does not have an impact.

The command without `:v2:uuid` fails with a different error:

```log
EXEC : error MT1212: Failed to create a simulator where type = iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s) and runtime = iOS 15.4 (15.4 - 19E240) - com.apple.CoreSimulator.SimRuntime.iOS-15-4. [/Users/dylanberry/Projects/MyMauiApp/MyMauiApp.csproj]
          
/usr/local/share/dotnet/sdk/6.0.300-preview.22179.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(901,5): error MSB3073: The command "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.100-rc.1.125/tools/bin/mlaunch --launchsim bin/Debug/net6.0-ios/iossimulator-x64/MyMauiApp.app/ --device XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --stdout /dev/ttys007 --stderr /dev/ttys007 --wait-for-exit" exited with code 1. [/Users/dylanberry/Projects/MyMauiApp/MyMauiApp.csproj]
```

**Comment by aokocax** [comment]
I get the same error if I don't add -c Debug or Release and add codesign statements. This only happens when trying on physical device. In addition, it is necessary to define a vildcard identifier for the applicationid from here.
https://developer.apple.com/account/resources/identifiers/list
com.companyname.* etc
`<ApplicationId>com.companyname.blabla</ApplicationId>`

**Comment by rolfbjarne** [comment]
The way to state that you're building for / running on a physical device, is by setting `RuntimeIdentifier=ios-arm64`. This can be done either in the project file:

```xml
<PropertyGroup>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
</PropertyGroup>
```

or on the command line:

```
$ dotnet build /p:RuntimeIdentifier=ios-arm64 ...
```

Then if you want to run the app, you execute the `Run` target by adding `/t:Run` to the command line.

Finally you select the device to run on (if you have more than one connected device), by setting the `_DeviceName` variable to the UDID or name of the device: `/p:_DeviceName=UDID` (this syntax is only when running on a physical device, not when running in a simulator).

The whole command to build & run on device becomes:

```
$ dotnet build /t:Run /p:RuntimeIdentifier=ios-arm64 -f net6.0-ios myProject.csproj
```

If that doesn't work, please post the entire command + the full output of the command.
