### ISSUE TITLE
[Enhancement] Drop UIWebView WebRenderer

### ISSUE THREAD

**Issue by jcmanke** [dotnet/maui#64]
## Summary

As we should all know by now, Apple has deprecated UIWebView for new apps effective April 2020 and existing apps effective December 2020. There is really no reason to keep deprecated references around in the code for a new framework that won't be released until late 2021. 

## API Changes

- Remove class `System.Maui.Platform.iOS.WebViewRenderer`
- Consider renaming `WkWebViewRenderer` to `WebViewRenderer` as the distinction is no longer necessary.

## Intended Use Case

Remove any risk of Apple rejecting submission of apps using MAUI due to UIWebView references.

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/12095
