### ISSUE TITLE
(Windows) RC1 - LayoutCycleException when maximizing window

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#6400]
### Description

Doing some tests in a repository I have detected that in Windows a LayoutCycleException is occurring when trying to maximize the window. This is the only information I get from the exception: 
`A cycle occurred while laying out the GUI.`

<img width="1195" alt="Issue06" src="https://user-images.githubusercontent.com/20904914/164622841-837b6596-3a9b-4b77-8673-a81754fb88ba.png">

Repository:
https://github.com/nacompllo/MauiCollectionView/tree/fix/WindowsCrash

### Steps to Reproduce

Clone the attached repository and try to maximize the window on Windows then the LayoutCycleException will occur.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows with above project.

**Comment by kristinx0211** [comment]
verified still repro on windows with 17.3.0 Preview 2.0 [32507.29.main].

**Comment by hartez** [comment]
This only happens if the layout has nested layouts with HorizontalOptions="Fill". So until we can address it, one possible workaround is to eliminate that pattern from the DataTemplate.

**Comment by samhouts** [comment]
No longer repros on 6.0.300-rc.4.5772
