### ISSUE TITLE
(Windows) RC1 - SwipeView - Attempted to read or write protected memory. This is often an indication that other memory is corrupt

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#6401]
### Description

The SwipeView I've noticed causes an exception on Windows when trying to run the app: 
`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

On Android, however, SwipeView works perfectly.

Repository:
https://github.com/nacompllo/MauiCollectionView/tree/test/WindowsSwipeView

### Steps to Reproduce

Clone the attached repository and start the Windows application, the detailed exception will be thrown. If you remove SwipeView from the XAML, the app will run normally.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows with above project.
