### ISSUE TITLE
[iOS] DatePicker does not display initial value

### ISSUE THREAD

**Issue by SailDev** [dotnet/maui#6402]
### Description

Initial value (i.e. Date="06/21/2022") is not displayed.

### Steps to Reproduce

1. Create a new Maui app.
2. Add to MainPage.xaml:

```
<DatePicker MinimumDate="01/01/2022"
            MaximumDate="12/31/2022"
            Date="06/21/2022" />
```
4. Deploy to local iOS device.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.3.1

### Did you find any workaround?

Don't use dates.

**Comment by v-longmin** [comment]
Verified repro on iOS 15.4 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro with above code.
