### ISSUE TITLE
ViewModel in Page .NET MAUI RC1 - Signed apk installed in device.

### ISSUE THREAD

**Issue by bautistavirchar** [dotnet/maui#6405]
### Description

**adb logcat**

04-22 15:47:16.804  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:17.866 15315 15315 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.866 15315 15315 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:17.876 15315 15315 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.876 15315 15315 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:17.876 15315 15315 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.876 15315 15315 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:25.706  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:26.601 16338 16338 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.601 16338 16338 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:26.609 16338 16338 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.609 16338 16338 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:26.609 16338 16338 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.609 16338 16338 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:29.530  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:30.419 16438 16438 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.419 16438 16438 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:30.427 16438 16438 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.427 16438 16438 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:30.427 16438 16438 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.427 16438 16438 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:31.366  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:32.239 16533 16533 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.239 16533 16533 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:32.248 16533 16533 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.248 16533 16533 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:32.248 16533 16533 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.248 16533 16533 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)

### Steps to Reproduce

04-22 15:47:16.804  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:17.866 15315 15315 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.866 15315 15315 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:17.876 15315 15315 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.876 15315 15315 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:17.876 15315 15315 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.876 15315 15315 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:25.706  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:26.601 16338 16338 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.601 16338 16338 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:26.609 16338 16338 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.609 16338 16338 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:26.609 16338 16338 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.609 16338 16338 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:29.530  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:30.419 16438 16438 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.419 16438 16438 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:30.427 16438 16438 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.427 16438 16438 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:30.427 16438 16438 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.427 16438 16438 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:31.366  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:32.239 16533 16533 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.239 16533 16533 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:32.248 16533 16533 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.248 16533 16533 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:32.248 16533 16533 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.248 16533 16533 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

04-22 15:47:16.804  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:17.866 15315 15315 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.866 15315 15315 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:17.876 15315 15315 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.876 15315 15315 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:17.876 15315 15315 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.876 15315 15315 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:25.706  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:26.601 16338 16338 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.601 16338 16338 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:26.609 16338 16338 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.609 16338 16338 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:26.609 16338 16338 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.609 16338 16338 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:29.530  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:30.419 16438 16438 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.419 16438 16438 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:30.427 16438 16438 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.427 16438 16438 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:30.427 16438 16438 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.427 16438 16438 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:31.366  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:32.239 16533 16533 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.239 16533 16533 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:32.248 16533 16533 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.248 16533 16533 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:32.248 16533 16533 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.248 16533 16533 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)

### Relevant log output

```shell
04-22 15:47:16.804  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:17.866 15315 15315 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.866 15315 15315 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:17.876 15315 15315 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.876 15315 15315 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:17.876 15315 15315 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:17.876 15315 15315 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:25.706  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:26.601 16338 16338 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.601 16338 16338 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:26.609 16338 16338 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.609 16338 16338 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:26.609 16338 16338 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:26.609 16338 16338 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:29.530  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:30.419 16438 16438 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.419 16438 16438 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:30.427 16438 16438 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.427 16438 16438 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:30.427 16438 16438 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:30.427 16438 16438 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:31.366  2206  2206 W AppStartUtils: sendActiveLaunchBroadcast() v.hasOnClickListeners() : true, iconInfo : AppInfo(id=515 type=APP hidden=0 container=all_apps screen=2 rank=11 user=UserHandle{0} title=Hoppa componentName=ComponentInfo{com.aquip_io.hoppa/crc64e7dbbf81b11d1134.MainActivity} screenType=0)
04-22 15:47:32.239 16533 16533 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.239 16533 16533 E AndroidRuntime:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:32.248 16533 16533 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.248 16533 16533 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
04-22 15:47:32.248 16533 16533 I MonoDroid: android.runtime.JavaProxyThrowable: System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `Hoppa_MauiApp.LoginPage:InitializeComponent ()'
04-22 15:47:32.248 16533 16533 I MonoDroid:    at Hoppa_MauiApp.LoginPage..ctor(LoginViewModel loginViewModel)
```

**Comment by bautistavirchar** [comment]
ZIndex="-1" not working actually.

**Comment by danch15** [comment]
In debug mode, everything works well, but in release mode, the application will crash.
This has been the case since the ZIndexProperty appeared...

**Comment by geertgeerits** [comment]
Same problem here.  I did put a try-catch around the InitializeComponent.
See the attached file:
![Screenshot_20220519-095357](https://user-images.githubusercontent.com/101981581/169254016-109f2b39-b0b1-4157-bc8a-420eab9deebb.jpg)

**Comment by bautistavirchar** [comment]
> 

Remove ZIndex in xaml page.

**Comment by aschuhardt** [comment]
This is still a bug right?
