### ISSUE TITLE
FlyoutPage issues on macOS

### ISSUE THREAD

**Issue by WisJamison** [dotnet/maui#6408]
### Description

I use a FlyoutPage to contains a ContentPage(gray area, named MainWindow), have 2 issues when run on macOS:

**1. The Bottom edge of App is higher than ContentPage's about 40 pixels (see fig. below)**

<img width="828" alt="image" src="https://user-images.githubusercontent.com/100921425/164661177-a1507831-06b3-4d6b-a59f-a988d2359818.png">
  So I have to expand the bottom edge by dragging to show ContentPage completely, see fig below:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/100921425/164668221-e87192cc-b7e8-4007-a00f-ea4211b81ac6.png">

**2. ContentPage, inside of LayoutPage, cant't resizing automatically by resizing App border.**
   see fig. below and the gray area is ContentPage:
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/100921425/164674577-e0fa3921-e0c7-4725-90c9-61946e07a9a3.png">

note: I attached project zip file and hope can help you.

[MyFlyoutApp.zip](https://github.com/dotnet/maui/files/8539124/MyFlyoutApp.zip)

### Steps to Reproduce

1. Create a MAUI project base on 6.0.202;
2. Create a NavigationPage and then assign it to MainPage in App.xaml.cs;
3. Change MainPage's parent Class from ContentPage to FlyoutPage;
4. Create a ContentPage named 'MainWindow' and add it into MainPage( type of FlyoutPage) as DetailPage;
5. Build and run the app;

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Version 12.0.1

**Comment by kristinx0211** [comment]
verified repro on macOS Monterey using the above project.
