### ISSUE TITLE
Inconsistent behavior with RTL flow direction for custom layout

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#6413]
### Description

I'm using a custom layout in my project, while setting RightToLeft flow direction for this layout, the children of the layout are arranged in a different manner across different platforms. 

**Windows => The children are arranged from the right as expected.**
<img width="711" alt="image" src="https://user-images.githubusercontent.com/92788387/164734658-8dec8df4-f77a-484f-a25a-02c12eba6d6d.png">

**Android, iOS and macOS => The children renders as normal, flow direction has no effect.**
<img width="241" alt="image" src="https://user-images.githubusercontent.com/92788387/164734458-726847a4-5976-4a38-9d77-ba8fdaaeef85.png">

### Steps to Reproduce

1. Run the attached sample in windows, you can see that the labels are arranged from right to left.
2. Run the same sample in Android, the labels will be arranged from the left to right.

Due to this inconsistency, we need to include platform conditions to arrange child views in RTL mode.

[MAUITestSample.zip](https://github.com/dotnet/maui/files/8541806/MAUITestSample.zip)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

Android 9.0, Windows SDK 10.0.19041 

### Did you find any workaround?

No

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 & iOS 15.4 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro project:
[MAUITestSample.zip](https://github.com/dotnet/maui/files/8548904/MAUITestSample.zip)

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 4.0. This issue does not repro on Android emulator (13.0-API 33) and iOS 16.4 emulator with below Project:

![image](https://user-images.githubusercontent.com/97647558/233827204-bf238153-c67d-4eb1-9874-a8c581bcab64.png)

![image](https://user-images.githubusercontent.com/97647558/233827290-3fb21a08-f396-4988-8f83-b22263f19dee.png)
