### ISSUE TITLE
[iOS] Width or height of Editor control can't be set

### ISSUE THREAD

**Issue by SailDev** [dotnet/maui#6414]
### Description

Width or height of Editor control can't be set.

After changing device orientation (portrait > landscape > portrait) width seems to be o.k.

### Steps to Reproduce

1. Create new Maui app.
2. Add to MainPage.xaml:
```
            <Editor x:Name="editor"
                    TextColor="Red"
                    BackgroundColor="Yellow"
                    Keyboard="Text"
                    HeightRequest="100"
                    WidthRequest="200"
                    Placeholder="Enter text"
            />
```
3. Deploy to local iOS device.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Release Candidate 1 (current)

### Affected platforms

iOS

### Affected platform versions

iOS 15.3.1

**Comment by kristinx0211** [comment]
verified not repro on IOS 15.4, width and height of Editor can be set.

**Comment by SailDev** [comment]
Tested again to verify, but still the same issue.
Editor dimensions are 200w x 300h.
After changing the orientation, the width is recalculated somehow, but the height is totally wrong.
Deployed via VS2022 to local IPhone, connected to Windows PC.

Please see attached demo project.

**Start the app**
![IMG_1060](https://user-images.githubusercontent.com/94922306/165058205-48820170-6df9-4604-a437-55ee42971c63.PNG)

**Enter 2 lines of text**
![IMG_1061](https://user-images.githubusercontent.com/94922306/165058399-e4707c57-aba8-407c-818d-d155b46abe9f.PNG)

**Switch to landscape**
![IMG_1062](https://user-images.githubusercontent.com/94922306/165058414-bbb77c37-8ead-41a8-9624-da5e976c9726.PNG)

**Switch back to portrait**
![IMG_1063](https://user-images.githubusercontent.com/94922306/165058432-ba31d59b-5d59-4b16-b324-08092370f6c7.PNG)

---

O.K. ON WINDOWS PLATFORM

![Screenshot 2022-04-25 112021](https://user-images.githubusercontent.com/94922306/165060141-d1509545-6a59-4ea3-ac35-973846d1fa05.png)


[MauiAppEditorTest.zip](https://github.com/dotnet/maui/files/8553154/MauiAppEditorTest.zip)

**Comment by davidortinau** [comment]
This is working fine with main (rc3) on iOS. Note I did put it inside of a Grid and set v/h options to Center.

![Simulator Screen Shot - iPhone 13 Pro - 2022-04-30 at 20 33 54](https://user-images.githubusercontent.com/41873/166128454-4a9e0595-fd58-4e60-b98b-dbbc315f49da.png)
![Simulator Screen Shot - iPhone 13 Pro - 2022-04-30 at 20 33 49](https://user-images.githubusercontent.com/41873/166128455-6f993ad1-d140-4fe0-a8be-177c807ca3e9.png)
