### ISSUE TITLE
Adding an image file to Resources/Images folder gets incorrectly set as AndroidResource Build Action

### ISSUE THREAD

**Issue by LanceMcCarthy** [dotnet/maui#6418]
### Description

Using Visual Studio 2022 Preview 17.2.0 Preview 4, adding an existing image file get incorrectly set as `AndroidResource` instead of `MauiIcon` or `MauiImage`.

I remember this working in a previous release because I was happy about seeing that working for me. Maybe it was preview14 or preview13. 

### Steps to Reproduce

1. Create a new MAUI project
2. Right click on the Resources/Images folder and select "Add > Existing item
3. Select any .svg or .png file

Observe the newly added file's **Build Action** and **Custom Tool Namespace** property value.

Here's a screenshot to help clarify what happens:

![image](https://user-images.githubusercontent.com/3520532/164762445-83cb5cd9-f0d2-4194-8f9d-a612246766fe.png)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

This is not a runtime issue, so I have no relevant TFM

### Did you find any workaround?

Manually change the **BuildAction** to `MauiIcon` or `MauiImage`

**Comment by XamlTest** [comment]
Verified not repro with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Sample Project: [MauiApp2.zip](https://github.com/dotnet/maui/files/8548837/MauiApp2.zip)
