### ISSUE TITLE
Grid doesn't dynamically size when content size changes

### ISSUE THREAD

**Issue by agendamatic** [dotnet/maui#6420]
### Description

I've often used the Xamarin Grid control to display/hide content. Consider the following:

    <StackLayout>
        <Label Text="Header" FontSize="24" BackgroundColor="Orange"/>

        <Grid RowDefinitions="Auto,*">
            <Button Text="Toggle me" Clicked="Button_Clicked"/>
            <StackLayout x:Name="ContentLayout" Grid.Row="1" IsVisible="False" HeightRequest="240" BackgroundColor="Yellow"/>
        </Grid>

        <Label Text="Footer" FontSize="24" BackgroundColor="Orange"/>
    </StackLayout>

Code-behind as follows:

        void Button_Clicked(object sender, EventArgs e) {
		ContentLayout.IsVisible = !ContentLayout.IsVisible;
	}

In Xamarin Forms, toggling visibility of ContentLayout will expand and contract the Grid and the content below it.

### Steps to Reproduce

Create a .NET MAUI project, add the above XAML to a ContentPage, and add the code-behind as well.

Run the project on iOS. Toggle the button. The footer label does not move down or up the page as the content of the grid's *-height column changes.

Now run the project on MacCatalyst. Toggle the button. The same behavior exists. With the content visible, <Cmd-Tab> away from the app, then return to the app. Note that the page appears as expected, meaning the content is visible AND the footer label is below the content.

On Windows, this example behaves as expected, the same as it did in Xamarin Forms.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

Current iOS and MacCatalyst versions are impacted

### Did you find any workaround?

In this small reproduction sample, replacing the Grid with a StackLayout (or removing the Grid entirely) works, but this technique is being used in several large controls, and I would not want to retrofit each if not necessary.

**Comment by limefrogyank** [comment]
This may be related:

If you run the default template on Android and click on the counter button until it gets to 10, the content of the label disappears.  The underlying code is still counting up on each button press, but after 9, the label refuses to show that number.

**Comment by v-longmin** [comment]
Verified repro on iOS 15.4 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro with above code.

**Comment by VincentBu** [comment]
still repros on IOS and Mac with vs main build[32510.390.main]

**Comment by RonakPatelDotNet** [comment]
Same issue also can be replicated on windows.

**Comment by viralrathod7** [comment]
getting this issue while using Dot Net MAUI for Windows
