### ISSUE TITLE
MAUI Blazor template (WinUI 3) does not display WebView2 Runtime download link

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/maui#6421]
### Description

The WinUI 3 WebView2 element displays a download link for the WebView2 Runtime when it is not installed. However, the MAUI Blazor template displays a blank purple screen under the same conditions.

**WinUI 3 WebView2 element**:
![WinUI WebView2 screenshot](https://user-images.githubusercontent.com/10456961/164772981-9ca2fde2-214d-4e4e-9607-6879b766f5d4.png)

**Blazor MAUI template**:
![MAUI Blazor screenshot](https://user-images.githubusercontent.com/10456961/164773210-7a2a555f-6680-4a85-9403-451093570aeb.png)

### Steps to Reproduce

1. Create a new project from the ".NET MAUI Blazor App" template (`maui-blazor`)
2. Follow [these steps](https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview) to publish the app
3. Install the app on a machine without the WebView2 Runtime installed.
4. Launch the app

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Tested on Windows 10, version 1809 (without WebView2 runtime installed)

**Comment by shimingsg** [comment]
verified repro on Windows 10, version 10.0.19044 with webview2 runtime uninstalled
