### ISSUE TITLE
Resizetizer rotates large images

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/maui#6426]
### Description

As seen in https://github.com/dotnet/maui/issues/5938#issuecomment-1106816185

Building a large `.jpg` as a `MauiImage` rotates the image:

![image](https://user-images.githubusercontent.com/840039/164785203-c14660e7-bb32-4007-86e9-d68b424c91c5.png)

The receipt is actually supposed to be:

![image](https://user-images.githubusercontent.com/840039/164773441-59ea707a-fb6c-4a4b-93cf-c223f1094150.png)

### Steps to Reproduce

1. Build this project for Windows:

[Simple-image.zip](https://github.com/dotnet/maui/files/8456231/Simple-image.zip)

2. Look in `obj\Debug\net6.0-windows10.0.19041.0\win10-x64\resizetizer\r`.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

Use `Resize="false"` on the large image.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 4.0. This issue does not repro on Windows 11 with below Project:
[6426.zip](https://github.com/dotnet/maui/files/11305960/6426.zip)

![image](https://user-images.githubusercontent.com/97647558/233889870-8dfd29f4-2879-460a-a061-732a2bae77f0.png)
