### ISSUE TITLE
Secure storage calling twice/thrice bug

### ISSUE THREAD

**Issue by justasxz** [dotnet/maui#6437]
### Description

Basically if I try to call SecureStorage twice/thrice the app crashes, without any try catch error, it just doesn't go any further, it doesn't work at least on windows machine. It's not my values, because if I get only Username or Password without the other or without the if it works as intended.

### Steps to Reproduce

Not sure about all the steps, all I did was create a function inside App.xaml.cs to log in, when the app starts. 

the part that makes it crash is below:
`        public async void SignIn()
        {

            try
            {
                if (!string.IsNullOrEmpty(SecureStorage.GetAsync("Username").Result))
                {

                    Username = SecureStorage.GetAsync("Username").Result;
                    Password = SecureStorage.GetAsync("Password").Result;
                    IsLoggedIn = true;
                    await Shell.Current.GoToAsync($"//{nameof(MainPage)}");
                }
                else
                {
                    Username = string.Empty;
                    Password = string.Empty;
                    IsLoggedIn = false;
                }
            }
            catch (Exception ex)
            {
                Username = string.Empty;
                Password = string.Empty;
                IsLoggedIn=false;
                // Possible that device doesn't support secure storage on device.
            }
        }`

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

Get username once before an if, and use it twice. Like this: 
`
                Username = SecureStorage.GetAsync("Username").Result;
                if (!string.IsNullOrEmpty(Username))
                {
                    Password = SecureStorage.GetAsync("Password").Result;
                    IsLoggedIn = true;
                    await Shell.Current.GoToAsync($"//{nameof(MainPage)}");
                }`

**Comment by shimingsg** [comment]
@justasxz , 
could you have a try for below, it works for me if change to await. 
```
 public async void SignIn()
    {
        try
        {


            if (!string.IsNullOrEmpty(**await** SecureStorage.GetAsync("Username")))
            {

                Username =**await** SecureStorage.GetAsync("Username");
                Password = **await** SecureStorage.GetAsync("Password");
                IsLoggedIn = true;
                await Shell.Current.GoToAsync($"//{nameof(MainPage)}");
            }
            else
            {
                Username = string.Empty;
                Password = string.Empty;
                IsLoggedIn = false;
            }
        }
        catch (Exception ex)
        {
            Username = string.Empty;
            Password = string.Empty;
            IsLoggedIn = false;
            // Possible that device doesn't support secure storage on device.
        }
    }
```
