### ISSUE TITLE
How to remove loading ... when maui blazor app is starting

### ISSUE THREAD

**Issue by MarshalOfficial** [dotnet/maui#6438]
### Description

I'm developing a dotnet MAUI Blazor hybrid app, I have an issue with the Loading... page when the app is starting, it shows after the splash screen.

![image](https://user-images.githubusercontent.com/8558078/164893556-c603415e-b4cb-4087-8e7a-270c265b0ffd.png)

### Public API Changes

It has nothing from code.

### Intended Use-Case

In visual studio 2022 preview, create a new project, choose dotnet MAUI Blazor hybrid app, then starts on your device.

**Comment by hez2010** [comment]
It's defined in wwwroot/index.html.

**Comment by MarshalOfficial** [comment]
> It's defined in wwwroot/index.html.

@hez2010 thanks for the reply, Is there any way to not have this step?? because when I remove loading... text from there, still an empty screen shows after splash screen

**Comment by drasticactions** [comment]
That's how a WASM Blazor app works on the web; it's no different here. I would probably bring it up with https://github.com/dotnet/aspnetcore if you feel is should be different.

**Comment by MarshalOfficial** [comment]
> That's how a WASM Blazor app works on the web; it's no different here. I would probably bring it up with https://github.com/dotnet/aspnetcore if you feel it should be different.

Maybe it is a good approach to remove the MAUI splash screen and relocate it to the index.html
