### ISSUE TITLE
RC1 - The BackgroundColor of the BoxView does not work

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#6443]
### Description

The BoxView BackgroundColor doesn't work, it always stays gray even if you add a different color to it, It happens on Android as it does on Windows.:

<img width="1430" alt="Issue08" src="https://user-images.githubusercontent.com/20904914/164898751-2b3ccfad-8835-45f2-98e8-7767fe5808fe.png">

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             BackgroundColor="White"
             x:Class="MauiCollectionView.MainPage">

    <VerticalStackLayout>
        <BoxView 
            WidthRequest="200"
            HeightRequest="200"
            BackgroundColor="Blue"/>
    </VerticalStackLayout>
</ContentPage>
```

Repository:
https://github.com/nacompllo/MauiCollectionView/tree/test_BoxViewBackgroundColorIssue

### Steps to Reproduce

Cloning the attached repository and running the application on both Windows and Android, the BoxView will not change the BackgroundColor and will always remain gray.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 10, Windows 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows and Android. Sample Project: [MauiApp4.zip](https://github.com/dotnet/maui/files/8548848/MauiApp4.zip)

**Comment by jsuarezruiz** [comment]
Tested on main branch and is working:
![image](https://user-images.githubusercontent.com/6755973/165048353-cbfe3cf7-4089-4b76-a032-462b81966e2d.png)

Should be fixed in the next release.
