### ISSUE TITLE
RC1 - SearchBar does not detect assigned Style

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#6444]
### Description

The SearchBar control does not detect the styles when one is assigned to it, I have tried with other controls and the rest work fine, it seems that it only happens with the SearchBar.

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiCollectionView.MainPage">

    <VerticalStackLayout>
        <SearchBar 
            Style="{StaticResource DefaultSearchBarStyle}"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="FillAndExpand"
            Placeholder="Placeholder Test..."/>
    </VerticalStackLayout>
</ContentPage>
```
    

```
<?xml version = "1.0" encoding = "UTF-8" ?>
<Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiCollectionView"
             x:Class="MauiCollectionView.App">
    <Application.Resources>
        <ResourceDictionary Source="Resources/Styles.xaml" />

        <Style x:Key="DefaultSearchBarStyle"
               TargetType="SearchBar">
            <Setter Property="PlaceholderColor" Value="Red" />
            <Setter Property="TextColor" Value="Blue" />
        </Style>
    </Application.Resources>
</Application>
```

Repository:
https://github.com/nacompllo/MauiCollectionView/tree/test_SearchBarStyleIssue

### Steps to Reproduce

Clone the attached repository and run the app on Windows and Android, SearchBar does not implement the values configured in the style assigned to it and it is defined in the App.xaml class, the PlaceholderColor should appear red and the TextColor blue but it ignores the style that has been assigned.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Release Candidate 1 (current)

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 10, Windows 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows and Android with above project.

**Comment by jsuarezruiz** [comment]
Tested and seems to work correctly on GA and the main branch:
![image](https://user-images.githubusercontent.com/6755973/170484511-d399ac00-ed67-4012-8d30-a3f14448f457.png)

Could you try it again with GA version?

**Comment by nacompllo** [comment]
Confirmed with the GA version it works perfect, the thread can be closed. Thank you.
