### ISSUE TITLE
Creating "bottom sheet dialog" doesn't render correctly

### ISSUE THREAD

**Issue by yunusefendi52** [dotnet/maui#6445]
### Description

I've created "bottom sheet dialog" component, everything is working in Xamarin.Forms, but when I try to port to MAUI it doesn't render correclty

MAUI:

https://user-images.githubusercontent.com/19399214/164910749-3d3801d4-4a20-4d36-928e-83d227497545.mp4

Xamarin.Forms:

https://user-images.githubusercontent.com/19399214/164910791-e6bbba42-b226-463a-92a4-967e8b745314.mp4

### Steps to Reproduce

Since It's a little bit complext because of the custom component, I am just gonna give u the repro

MAUI:
[maui.zip](https://github.com/dotnet/maui/files/8547425/maui.zip)

Xamarin.Forms:
[xf.zip](https://github.com/dotnet/maui/files/8547430/xf.zip)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10 (maybe others too)

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android with above project.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 4.0. This issue does not repro on Android emulator (13.0-API 33) with below Project:
[6445.zip](https://github.com/dotnet/maui/files/11306010/6445.zip)

![BottomDialog](https://user-images.githubusercontent.com/97647558/233891295-a304833b-d406-42dd-86f2-2031ca66da7f.gif)
