### ISSUE TITLE
[Bug] Checkbox with excess margin on the right side.

### ISSUE THREAD

**Issue by pierrebrito** [dotnet/maui#6449]
### Description

![image](https://user-images.githubusercontent.com/6466875/164934655-ad61e552-6615-4f37-a11b-78d63f47c8a3.png)

### Steps to Reproduce

    CheckBox Color="Red"
              BackgroundColor="Blue"
              HorizontalOptions="Start"/>

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro with above project.

**Comment by christophbrunner** [comment]
#https://github.com/dotnet/maui/issues/4693

**Comment by davidortinau** [comment]
Closed as duplicate
