### ISSUE TITLE
[Windows] Can't include MAUI and WinForms in the same project

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#6450]
### Description

If you include WinForms and MAUI in the same project, you'll get a RuntimePack error saying it can't find win10-arm, causing the project not to build. In separate projects, they both load and work correctly.

### Steps to Reproduce

Create a class library project and use the following csproj

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041.0</TargetFrameworks>
		<UseMaui>true</UseMaui>
		<UseWindowsForms Condition="$(TargetFramework.Contains('-windows'))">true</UseWindowsForms>
		<WarningsAsErrors>nullable</WarningsAsErrors>
	</PropertyGroup>

</Project>
```

You'll see the errors when it compiles. It doesn't need to be referenced to any other project, it just needs to exist.

[MauiWinFormsClassLibrary.zip](https://github.com/dotnet/maui/files/8548502/MauiWinFormsClassLibrary.zip)

You can also use this project.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows in general

### Relevant log output

```shell
1>C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm'.
1>C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm-aot'.
1>Done building project "MauiWinFormsClassLibrary.csproj" -- FAILED.
```

**Comment by drasticactions** [comment]
And in case anyone is wondering, "Why would you want to include WinForms and MAUI in the same library!?!"

You can build Tray Icons in WinForms relatively easily, so I'm trying to make an interface for building taskbar and dock icons.

**Comment by drasticactions** [comment]
And you know what, I just checked and it happens with UseWinUI by itself too.

Closing my own bug, 10 minutes after I made it.

**Comment by drasticactions** [comment]
Okay, I lied, I think it is only with MAUI.

So what tripped me was that if you had `UseMaui` and then replace it with `UseWinUI` it will fail with the same error. But if you reload the project and build, it would work fine. But if you replace it with `UseMaui` it will fail every single time.

So to reproduce this from a new project, if you take an existing MAUI library and add `UseWindowsForms`, it should produce the runtime pack error. If you have a WinForms project and add `UseMaui` you should get the runtime pack error.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/pull/14595#issuecomment-1511565265
