### ISSUE TITLE
[Bug] Grid inside a StackLayout with Padding, exceeds view limit.

### ISSUE THREAD

**Issue by pierrebrito** [dotnet/maui#6451]
### Description

App:
![image](https://user-images.githubusercontent.com/6466875/164944553-04c31138-8aee-448a-81d4-323c3f31a870.png)

Code:
![image](https://user-images.githubusercontent.com/6466875/164944560-5a4a5189-02d3-4f30-bdc9-411e61c53abd.png)

Setting the InputTransparent attribute seems to work correctly.

![image](https://user-images.githubusercontent.com/6466875/164944597-ecccc281-6fe2-43a9-a9bb-1b5f0af252f1.png)
![image](https://user-images.githubusercontent.com/6466875/164944579-d9cb8723-1e3d-4b57-a8a7-d1cfa9c60e00.png)

### Steps to Reproduce

    <StackLayout Spacing="16"
                 Padding="16">
        <Grid ColumnDefinitions="*,*"
              ColumnSpacing="16"
              BackgroundColor="Red"
              Padding="8" >

            <Button Text="Button 1"
                    Grid.Column="0" />

            <Button Text="Button 2"
                    Grid.Column="1" />
        </Grid>
    </StackLayout>

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 - API31 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro with above project.

**Comment by kristinx0211** [comment]
verified on android with 17.3.0 Preview 2.0 [32507.29.main], not repro. close it. feel free to open new issue if you still hit this failure with same/newer environment.
