### ISSUE TITLE
App crashes when changing CarouselView Loop property at runtime

### ISSUE THREAD

**Issue by DoubleDBE** [dotnet/maui#6457]
### Description

When you have `Loop="True"` defined on a `CarouselView` in XAML, and you change it while debugging to `Loop="False"` and do one swipe, the app crashes.

Not sure if this really is a bug, or this has something to do with Hot Reload.

But due to #6328, I find it worthy to mention it anyway.

Sometimes it gives this exception:

`Java.Lang.IndexOutOfBoundsException
  Message=Inconsistency detected. Invalid view holder adapter positionTemplatedItemViewHolder{2931e3f position=15 id=-1, oldPos=-1, pLpos:-1 no parent} crc645d80431ce5f73f11.MauiCarouselRecyclerView{7e3cfb5 VFED..... ........ 0,0-480,534}, adapter:crc645d80431ce5f73f11.CarouselViewAdapter_2@213f7ab, layout:androidx.recyclerview.widget.LinearLayoutManager@8d6a697, context:crc64e40959fc36668bf1.MainActivity@91f982b`

And sometimes it gives this exception:

`Java.Lang.IndexOutOfBoundsException
  Message=Inconsistency detected. Invalid item position 6(offset:6).state:16384 crc645d80431ce5f73f11.MauiCarouselRecyclerView{36293e1 VFED..... ........ 0,201-480,830}, adapter:crc645d80431ce5f73f11.CarouselViewAdapter_2@1ac7153, layout:androidx.recyclerview.widget.LinearLayoutManager@59e6963, context:crc64b52dfc50fa3ba884.MainActivity@963ea9c`

### Steps to Reproduce

1. Download this repro project
[CarouselViewPositionBug.zip](https://github.com/dotnet/maui/files/8524501/CarouselViewPositionBug.zip)

2. Open `MainPage.xaml` and CTRL+F for `ItemSwiper`.

3. Change `Loop="False"` to `Loop="True"`.

4. Start debugging.

5. Change `Loop="True"` to `Loop="False"`.

6. Swipe and observe the crash.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 5.0 and up

**Comment by drasticactions** [comment]
This is not a XAML Hot Reload bug; it's a bug when you dynamically change properties on the CarouselView (In this case, specifically for Android).

If you try changing those properties from code-behind (either adding or removing new items in that view, or changing those properties), it will crash the same way.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.2.0 Preview 5.0 [32422.2.d17.2]. Repro on Android with above project.
