### ISSUE TITLE
Current Count text in Hello World solution does not display in UI after clicking button

### ISSUE THREAD

**Issue by wyldebill** [dotnet/maui#6458]
### Description

Just downloaded and installed VS 2022 Preview, 17.2.0 Preview 4, rebooted, and created a new MAUI solution from the wizard.  Ran the provided sample code for Hello World on Android Emulator, Api 31. Clicking the button does not update the UI with the incremented count from 0 to 1 to 2...  In the debugger, I can see the value of CounterLabel.Text changing it's value but the ui has nothing for the bound value of {count}.

### Steps to Reproduce

Create a new sample MAUI solution.
Build the solution.
Press debug and use Android Emulator, api 31, Pixel 5 virtual device.
Press the "Click me" button.
The UI for the bound value of {counter} disappears and does not update after this.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Api 31, Windows 11

### Did you find any workaround?

I left the debugger on a break point and did some research on this for a long time (15mins?)  and when I came back to the debugger and continued it seemed to be updating the UI correctly.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android. Sample Project: [6458.zip](https://github.com/dotnet/maui/files/8550806/6458.zip)

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/5717
