### ISSUE TITLE
Images don't load correctly on Android

### ISSUE THREAD

**Issue by dharber** [dotnet/maui#6464]
### Description

Android images weren't loading at all. Bug #6394 sort of fixed the problem but not really. Now, when I set the Image source to a UriImageSource, every other image is displayed and the alternates are blank, i.e., no image is displayed.

I'm using the main workload to test this as RC1 doesn't work at all and the bug fix for that is has not been released yet.

### Steps to Reproduce

1. Create a new MAUI App
2. Add a name to the Image element in the default app
3. Create a list of image URI's and a timer to periodically create a new ImageSource and set the Image source to the next URI.
4. I also output the image index to the counter label to demonstrate that alternating images were blank

I can add actual code to this post but it's tied to specific images on a local server and I'm not sure it would help all that much.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Preview 14

### Affected platforms

Android

### Affected platform versions

Seeing it on Android 11

### Did you find any workaround?

I have been unable to find a workaround. I was hoping that setting the source twice might fool it into working, albeit with possible annoying flickering, but that didn't work.

**Comment by VincentBu** [comment]
Repro on Android emulator. Here is a sample project:
[MauiApp6464.zip](https://github.com/dotnet/maui/files/8552484/MauiApp6464.zip)

**Comment by jamesmontemagno** [comment]
Still running into Android images loading via URL databinding in RC2 https://github.com/dotnet-presentations/dotnet-maui-workshop/ in the final folder

**Comment by mattleibow** [comment]
Yeah. I managed to locate where the issue really starts happening, and I think it may be a bug in Glide.

It is a small fix so I am working on a PR now. But still is both surprising as it is all code following the docs and I can't believe we are the only people in the world cleaning up our images.

It appears that when we start loading a new image and ask glide to clean up the old one, glide breaks itself and never fires the image load complete events and so we can't actually know when to set the image.

And if we just never clean up and let the framework auto-cleanup when setting new images it works.

Just need to verify that it is actually doing a cleanup...

**Comment by dharber** [comment]
So this definitely works better but the image still flickers when changing the image Source. It did not do this in Preview 14 so there is still something amiss.

**Comment by mattleibow** [comment]
Flickers? Like it disappears for a millisecond between images? Could you open an issue on that with a repro? 

Does it flicker when loading from a local source? Like a file in the cache? The reason I ask is that I don't recall any flicker, but maybe I got something different in my sample app.

I was just setting `image.Source = new Uri("...")` so maybe you have some logic to do something else?
