### ISSUE TITLE
Control Frame used in a ControlTemplate doesn't work on Windows

### ISSUE THREAD

**Issue by nk54** [dotnet/maui#6467]
### Description

Visual Studio 2022 17.2.0 Preview 3.0

ContentPage of MainPage.xaml
` <VerticalStackLayout>
        <c:GroupBox
            Title="Some text as title"
            Padding="20"
            BackgroundColor="LightBlue"
            Pastille="20">
            <VerticalStackLayout>
                <Label Text="Some text" />
                <Label Text="inside a group box" />
                <Label Text="with a pastille" />
            </VerticalStackLayout>
        </c:GroupBox>
    </VerticalStackLayout>`

Control template (either in a resource dictionary or in the page resource)
` <ControlTemplate x:Key="GroupBoxControlTemplate" x:DataType="c:GroupBox">
        
    <Grid ColumnDefinitions="*,Auto" RowDefinitions="Auto,*">
        <Label
            Padding="18,8,4,8"
            BackgroundColor="{TemplateBinding HeaderBackgroundColor}"
            Text="{TemplateBinding Title}" />
        <Label
            Grid.Column="1"
            BackgroundColor="{TemplateBinding PastilleBackgroundColorProperty}"
            HorizontalTextAlignment="Center"
            Text="{TemplateBinding Pastille}"
             VerticalTextAlignment="Center" />
        <ContentPresenter
            Grid.Row="1"
            Grid.ColumnSpan="2"
            BackgroundColor="DeepPink" />
    </Grid>
    
</ControlTemplate>`

`<Style TargetType="c:GroupBox">
     <Setter Property="ControlTemplate" Value="{StaticResource GroupBoxControlTemplate}" />
</Style>`

If you uncomment the Frame code, it crashes on Windows. It works on Android.

Here is the result
![image](https://user-images.githubusercontent.com/13755220/165052615-2b32b301-bf74-45a1-b8fc-72e13ed1d881.png)

### Steps to Reproduce

Past the given code in main page on a new maui project

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

Not yet

**Comment by Redth** [comment]
Can you try another control? Grid? Just at least to validate if it's the Frame specifically or a control template problem.

**Comment by Nk54** [comment]
@Redth yes it works if I replace the Frame by a Grid.

That's what I did.

I created a Grid as a wrapper, added a Rectangle with corner radius and added my content over the rectangle inside the Grid.
That's not the look I wanted, but at least it doesn't crashes.

**Comment by Redth** [comment]
You could try Border instead as well.

**Comment by Nk54** [comment]
Yea I know. But I'd like to be able to use the Frame control as I'd like to have shadow :)

**Comment by hartez** [comment]
@Nk54 Does your main page have a ScrollView?

**Comment by Nk54** [comment]
@hartez I tried with ScrollView at first but from my experiences, i knew it could be this component.
I think the problem happens without it too.
I'll try and tell you later.

**Comment by samhouts** [comment]
@nk54 Can you please attach a small project to help us reproduce the issue? Thanks!

**Comment by nk54** [comment]
I will provide a Repro project tomorrow

**Comment by PureWeen** [comment]
@nk54 do you have an update?

**Comment by nk54** [comment]
Hello the bug has been fixed since Release Candidate 1.

I don't repro the bug on latest.
