### ISSUE TITLE
Host web api

### ISSUE THREAD

**Issue by selvam920** [dotnet/maui#647]
How to host web api in android using .net.android

**Comment by Eilon** [comment]
Same question here: https://github.com/dotnet/MobileBlazorBindings/issues/356

**Comment by Harrybombe** [comment]
<solution>
    <add key="disableSourceControlIntegration" value="true" />
</solution>

**Comment by mattleibow** [comment]
I don't believe this is a thing that MAUI "does" but rather some library or API - maybe an embeddable ASP.NET server or something. MAUI is just for the app model and UI. You technically can set up a basic server for things using TCP listeners _I think_.

I'm closing this for now as this is not a MAUI "feature" but rather an independent feature.
