### ISSUE TITLE
cannot install maui main - Workload.Mono.ToolChain.Manifest missing signature

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6470]
### Description

Cannot install according to this guide:
https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md

which was suggested here: https://github.com/dotnet/maui/issues/6228#issuecomment-1106813924

![image](https://user-images.githubusercontent.com/64279914/165068237-8ad757ac-09b7-46d2-ab1c-984c42d2e628.png)

`
Failed to verify authenticode signature for C:\ProgramData\dotnet\workloads\microsoft.net.workload.mono.toolchain.manifest-6.0.300.msi.x64\6.0.5\Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.300.6.0.5-x64.msi. Error: 0x800b0100. `

Also, this probably uninstalled my current workloads which shouldn't have happened. Opening any MAUI solution now shows this:
![image](https://user-images.githubusercontent.com/64279914/165069291-22a574aa-2d91-45a8-a082-9143242b93e7.png)

**_Also, this doesn't fix even after uninstalling MAUI and reinstalling via Visual Studio installer_**

when trying to install RC1 back from the guide, the following line shows up which probably wasn't present when I was trying to install main workload:
![image](https://user-images.githubusercontent.com/64279914/165071882-c22a8a72-dc8a-4adb-aa34-bed34911615b.png)

Why is signature check skipped for RC1? I cannot see any command in the batch in the guide that causes it.

### Steps to Reproduce

Try install main maui workload from https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

I don't know

### Did you find any workaround?

no

**Comment by drasticactions** [comment]
If you want to work around it, install a 6.0.300 CI dotnet SDK build from https://github.com/dotnet/installer#table. That allows for unsigned workloads to install.

**Comment by v-longmin** [comment]
Verified repro on windows with VS  17.3.0 Preview 1.0 [32424.51.main].

**Comment by Axemasta** [comment]
I've never had the code snippet in the development guide work, what I do find works is simply:
```
dotnet workload install maui
```
Can't confirm whether that caused other issues, but at least the cli command succeeds 😁

**Comment by drasticactions** [comment]
@Axemasta When you run the workload command without the sources and rollback file, you will pull in whatever versions you happen to have from your nuget sources, and those could be misaligned and cause other issues. So that might have worked for you _right now_ but who knows if it will in the future.

The rollback files are intended to get you to the specific versions that are known to work together.

**Comment by Axemasta** [comment]
The normal .net 6 [download](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)  sdk left me with the same error as OP, despite using an elevated powershell window.
```
Workload installation failed:
Failed to verify authenticode signature for C:\ProgramData\dotnet\workloads\microsoft.net.workload.mono.toolchain.manifest-6.0.300.msi.x64\6.0.5\Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.300.6.0.5-x64.msi.
Error: 0x800b0100.
No signature was present in the subject.
```

The advice from @drasticactions worked for me
> If you want to work around it, install a 6.0.300 CI dotnet SDK build from https://github.com/dotnet/installer#table. That allows for unsigned workloads to install.

I installed it alongside 6.0.300-preview.22204.3 (visual studio) and the commands on the developer guide then seemed to work for me 😀

**Comment by jfversluis** [comment]
I think this should be better now that everything is released publicly. If you still experience issues with this, please open a new issue with all the latest details. Thanks!
