### ISSUE TITLE
[Exception] InsertPageBefore cause "Previous Navigation Request is still Processing"

### ISSUE THREAD

**Issue by pierrebrito** [dotnet/maui#6478]
### Description

Use InsertPageBefore cause "Previous Navigation Request is still Processing"

### Steps to Reproduce

try
{
    Navigation.InsertPageBefore(new MainPage(), Navigation.NavigationStack[0]);
    await Navigation.PopToRootAsync();
}
catch (Exception e)
{
    //Previous Navigation Request is still Processing
}

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by PureWeen** [comment]
Duplicate https://github.com/dotnet/maui/issues/4306

Fixed on RC2
