### ISSUE TITLE
Issues with collection view displaying only first item and scrolling crashes app

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#6484]
### Description

Open and run Final folder in https://github.com/dotnet-presentations/dotnet-maui-workshop
Run on macOS catalyst and then load data and try to scroll and app will crash

### Steps to Reproduce

Open and run Final folder in https://github.com/dotnet-presentations/dotnet-maui-workshop
Run on macOS catalyst and then load data and try to scroll and app will crash

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS

### Did you find any workaround?

None

**Comment by jfversluis** [comment]
On current main it doesn't crash anymore, but still only shows 1 item and seems to be able to scroll down infinitely but showing nothing.

**Comment by jamesmontemagno** [comment]
@jfversluis I think related to https://github.com/dotnet/maui/issues/6484. i put in a fix where i don't clear it the first time and then it shows them all, but if you actually hit the button again it will clear them load them but only show 1 again.
