### ISSUE TITLE
Grid ColumnDefinitions aren't supporting data binding on Width property

### ISSUE THREAD

**Issue by agendamatic** [dotnet/maui#6485]
### Description

In Xamarin Forms, Grid [Column|Row]Definitions supported data binding statements in XAML for the [Width|Height] properties.

In the current version of MAUI, Binding statements seem to be ignored.

### Steps to Reproduce

Create a new MAUI ContentPage, and add the following to the XAML page:

    `<ScrollView>
        <StackLayout Spacing="20">
            <StackLayout>
                <Label Text="Without Binding"/>
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="120"/>
                        <ColumnDefinition Width="*"/>
                    </Grid.ColumnDefinitions>

                    <Label Grid.Column="0" Text="Column 0" BackgroundColor="Yellow"/>
                    <Label Grid.Column="1" Text="Column 1" BackgroundColor="YellowGreen"/>
                </Grid>
            </StackLayout>

            <StackLayout>
                <Label Text="{Binding LabelText}"/>
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="{Binding Column0Width}"/>
                        <ColumnDefinition Width="{Binding Column1Width}"/>
                    </Grid.ColumnDefinitions>

                    <Label Grid.Column="0" Text="Column 0" BackgroundColor="Yellow"/>
                    <Label Grid.Column="1" Text="Column 1" BackgroundColor="YellowGreen"/>
                </Grid>
            </StackLayout>
        </StackLayout>
    </ScrollView>
`

Add the following to the code behind:

    `public class GridBindingDemoViewModel : INotifyPropertyChanged
    {
    public event PropertyChangedEventHandler PropertyChanged;

    protected bool SetProperty<T>(ref T field, T newValue, [CallerMemberName] string propertyName = null) {
        if ( !Equals(field, newValue) ) {
            field = newValue;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
            return true;
        }

        return false;
    }

    string labelText;
    GridLength column0Width;
    GridLength column1Width;

    public string LabelText { get => labelText; set => SetProperty(ref labelText, value); }
    public GridLength Column0Width { get => column0Width; set => SetProperty(ref column0Width, value); }
    public GridLength Column1Width { get => column1Width; set => SetProperty(ref column1Width, value); }
    }`

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows, macOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15.4, macOS 12.3.1, windows 19044.1645

### Did you find any workaround?

I've subclassed Grid and added bindable properties to set the column widths dynamically. I also found some luck with binding to WidthRequest on the labels, but that required more code change than subclassing Grid.

**Comment by StephaneDelcroix** [comment]
Not a bug. DefinitionCollection isn't a BindableObject, and Width isn't a BindableProperty, so you can't bind to it

**Comment by StephaneDelcroix** [comment]
I don't think we changed it from XF to Maui...

**Comment by agendamatic** [comment]
Per GitHub, Width was indeed bindable. (https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Core/ColumnDefinition.cs)

Rather than close the issue, perhaps mark it for v.Next?
