### ISSUE TITLE
Cannot find Could not load signature of Xamarin.HotReload.Loader:CurrentDomain_AssemblyResolve

### ISSUE THREAD

**Issue by emorell96** [dotnet/maui#6488]
### Description

Cannot debug app that was is using Entitlements.plist and thus manual provisioning.

I am using a remote device hooked up to the mac from Windows. And when I try to deploy and run, I get this error when the app loads up:

Could not load signature of Xamarin.HotReload.Loader:CurrentDomain_AssemblyResolve due to: Could not resolve type with token 01000033 from typeref (expected class 'System.ResolveEventArgs' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.ResolveEventArgs member:(null)

I tried disabling Hot Reload but that isn't doing it.

### Steps to Reproduce

1. Create an app.
2. Add manual provisioning to the app.
3. Add an Entitlements.plist file.
4. Deploy to a remote device through Pair to Mac.

You get:

warning: Could not load signature of Xamarin.HotReload.Loader:CurrentDomain_AssemblyResolve due to: Could not resolve type with token 01000033 from typeref (expected class 'System.ResolveEventArgs' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.ResolveEventArgs member:(null)

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 

used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================

	0x10114da44 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x101138de8 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10111e09c - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1ccc98d9c - /usr/lib/system/libsystem_platform.dylib : <redacted>

	0x10114df60 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x101171364 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x101176d4c - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1011767ec - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10115be9c - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/Open
StockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1011511bc - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10114ee94 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1011210e0 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10106e288 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10
0fcf994 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x100fd9530 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x100fced18 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x100fce4c4 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x100fe27b0 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStock
App : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x100fd7e58 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x100e4c304 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : 
	0x10115ac2c - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x101158fdc - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10114ee94 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.a
pp/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1011210e0 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10106c9a8 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1010723c0 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x101125e88 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCod
e
	0x100e7d2a4 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : xamarin_log
	0x10118fc60 - /private/var/containers/Bundle/Application/E295D348-3F35-4DE4-B0B2-626B1CF28B55/OpenStockApp.app/OpenStockApp : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1843c3140 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x10114df68):0x10114df58  01 15 80 52 95 47 fd 97 f6 03 00 aa 13 00 00 f9  ...R.G..........
0x10114df68  a8 12 40 79 08 90 00 b9 a8 0e 40 b9 08 59 16 53  ..@y......@..Y.S
0x10114df78  08 94 00 b9 a8 0e 40 b9 08 15 10 12 1f 41 41 71  ......@......AAq
0x10114df88  e8 17 9f 1a 09 80 42 39 29 79 1e 12 28 05 08 2a  ......B9)y..(..*

==============================================================
===
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at <unknown> <0xffffffff>
	  at <Module>:runtime_invoke_direct_void__this___string_string <0x00058>
	  at <unknown> <0x00000>
	  at <unknown> <0xffffffff>
	  at OpenStockApp.Program:Main <0x00004>
	  at <Module>:runtime_invoke_direct_void_string[] <0x0004a>
	  at <unknown> <0x00000>
=================================================================

and the app freezes while loading.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 15

### Did you find any workaround?

Disable XAML hot reload.

**Comment by drasticactions** [comment]
Are you _sure_ you didn't turn off XAML Hot Reload?

The namespace is from XAML Hot Reload, from an Agent we inject into the application. It should only be present if XAML Hot Reload is turned on. If you're hitting that and it's turned off... that's an interesting problem.

Do you have a repro project for this? My guess right now is that the iOS linker is removing System.Reflection assemblies, which means Hot Reload can't work, so it's blowing up.

Can you also try running a new template MAUI app and try running it on iOS as well?

**Comment by drasticactions** [comment]
Also, can you try adding

`<MtouchLink Condition="$(TargetFramework.Contains('-ios'))">None</MtouchLink>`
