### ISSUE TITLE
NavigationPage.SetTitleView not rendering properly on Android

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#6495]
### Description

The instruction [NavigationPage.SetTitleView] renders incorrectly under Android.
For example, when it should display like this (on iOS):
![image](https://user-images.githubusercontent.com/7484186/165185770-3e81edb7-6c9b-40a3-90a4-ea862aa29112.png)

It display like this (on Android):
![image](https://user-images.githubusercontent.com/7484186/165186891-9464eeb8-31f3-4401-9759-357302ee8957.png)

A very simple reproduction is included to demonstrate this.

This never worked on previous MAUI releases. I decided its time to report the bug.

### Steps to Reproduce

1. Open reproduction from Github repository [https://github.com/hbraasch/SetTitleViewTester.git] inside Visual Studio
2. Run for both Android and iOS
3. See the difference

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11, Android 12 and others

### Did you find any workaround?

None

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 & iOS 15.4 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro project:
[SetTitleViewTester-master.zip](https://github.com/dotnet/maui/files/8558955/SetTitleViewTester-master.zip)

**Comment by Redth** [comment]
No longer reproduces in maui main.  Fixed for next release.
