### ISSUE TITLE
the following workloads must be installed: maccatalyst

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#6496]
### Description

First MAUI experience: I installed the "Mobile development with .NET" workload in VS installer. Created a MAUI project, tried debugging the default app without any changes on Android Emulator (Pixel 5) and it fails to build because of:

`Error	NETSDK1147	To build this project, the following workloads must be installed: maccatalyst`

Then I removed the maccatalyst target in  the `csproj` file, because I dont care about macOS. Tried debuging again but same issue. I removed the catalyst folder in "platforms" folder, tried again but same issue. I did a text search for "maccatalyst" on the whole project folder but no results. I deleted the `.vs` folder and `obj` folder but same issue.

So my question is:

1. Why does it wants something about macOS when I actually try to debug on Android
2. Where does it take the maccatalyst workload from, there is nothing inside the project about maccatalyst anymore.

![image](https://user-images.githubusercontent.com/14368203/165203909-6825a065-93e9-4a76-95b7-fbdc38d6f238.png)
![image](https://user-images.githubusercontent.com/14368203/165203930-83dcaffe-12b4-4bb2-83b3-725cbfee29bc.png)
![image](https://user-images.githubusercontent.com/14368203/165203942-5d08356f-23de-4c88-a7b6-cd59b4a8fab2.png)

### Steps to Reproduce

See above

Host system: Windows 11
VS 2022 Preview 4.0
I dont know which MAUI version gets installed by the VS installer...

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11

**Comment by v-longmin** [comment]
Verified not repro on 17.3.0 Preview 1.0 [32424.51.main] with  sample Maui project.

**Comment by drasticactions** [comment]
Could you open up a terminal, go to the directory with the csproj, and see what version of dotnet is being used to compile your app?

My guess is that it isn't using 6.0.300, which can cause weird errors like that to appear because the tooling is confused about what's available.

**Comment by Symbai** [comment]
What kind of terminal do you mean? I'm using Windows 11 like I said above. How do I see what version of dotnet is being used?

The csproj file contains this:

```XML
		<TargetFrameworks>net6.0-android;net6.0-ios</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>
```

Also like I said this is created by VS, I didn't changed anything.

**Comment by Symbai** [comment]
Ugh, why isn't that setup by MAUI VS template itself? And how to I setup such a file?

**Comment by drasticactions** [comment]
```
{
  "sdk": {
    "version": "6.0.300",
    "rollForward": "latestFeature"
  }
}
```

Put that in the root directory of your MAUI project, and name it `global.json`

**Comment by Symbai** [comment]
`Error	NETSDK1141	Unable to resolve the .NET SDK version as specified in the global.json located at `

But I have `SDK 6.0.300-preview.22204.3` installed and also runtime  `Microsoft.NETCore.App 6.0.3` and `Microsoft.WindowsDesktop.App 6.0.3`

**Comment by drasticactions** [comment]
Yeah, set version to `"version": "6.0.x"`

**Comment by Symbai** [comment]
Thanks, that made the error `Unable to resolve the .NET SDK version as specified in the global.json` go away but I still get the 
`Error	NETSDK1147	To build this project, the following workloads must be installed: maccatalyst` error in VS when trying to debug.

**Comment by drasticactions** [comment]
What happens if you build from CLI? Run `dotnet build` in that directory.

**Comment by Symbai** [comment]
I get the same error in `cmd`, by the way after posting this issue I did created a Xamarin project yesterday and I could immediately debug that in Android Emulator. Its just MAUI that fails.

**Comment by drasticactions** [comment]
Run `dotnet --list-sdk` in that directory, what does it say?

**Comment by Symbai** [comment]
```
6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]
6.0.300-preview.22204.3 [C:\Program Files\dotnet\sdk]
7.0.100-preview.2.22076.7 [C:\Program Files\dotnet\sdk]
```

```
Build started...
1>------ Build started: Project: TestMobile, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\7.0.100-preview.2.22076.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maccatalyst
1>C:\Program Files\dotnet\sdk\7.0.100-preview.2.22076.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload install maccatalyst
1>Done building project "TestMobile.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

```

**Comment by drasticactions** [comment]
That's from VS, and it's still building with the 7.0 SDK, so it's going to get the same error. Did you reload the solution? Quit VS and reopen it. And can you post your build log from CLI?

**Comment by Symbai** [comment]
CLI also says 7.0 SDK. I've restarted VS and now get a different error:

`Error	MSB4067	The element <#text> beneath element <Project> is unrecognized. The project file is invalid on disk and was not reloaded.`

I dont know what that means, I haven't changed the csproj file since yesterday.

**Comment by Symbai** [comment]
Ok I deleted the project. Created a new MAUI project using VS. Closed VS, copied the `global.json` file into the same folder as the `MobileTest.sln` file. Opened the project in VS and tried to build:

```
Build started...
1>------ Build started: Project: TestMobile, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\7.0.100-preview.2.22076.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maccatalyst
1>C:\Program Files\dotnet\sdk\7.0.100-preview.2.22076.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload install maccatalyst
1>Done building project "TestMobile.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

**Comment by Symbai** [comment]
Ok I did was the error message suggested and ran this command in cmd

`dotnet workload install maccatalyst`

Output:
```
Downloading Microsoft.MacCatalyst.Sdk.Msi.x64 (15.4.100-rc.1.125)
Downloading Microsoft.MacCatalyst.Ref.Msi.x64 (15.4.100-rc.1.125)
Downloading Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.Msi.x64 (15.4.100-rc.1.125)
Downloading Microsoft.MacCatalyst.Runtime.maccatalyst-x64.Msi.x64 (15.4.100-rc.1.125)
Downloading Microsoft.MacCatalyst.Templates.Msi.x64 (15.4.100-rc.1.125)
Downloading Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64.Msi.x64 (7.0.0-preview.2.22074.8)
Microsoft.Mono.maccatalyst-arm64.7.0.0-preview.2.22074.8-x64.msi is installing ....... Done
Downloading Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64.Msi.x64 (7.0.0-preview.2.22074.8)
Microsoft.Mono.maccatalyst-x64.7.0.0-preview.2.22074.8.msi is installing ...... Done
Downloading Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 (7.0.0-preview.2.22074.8)
Microsoft.MonoAOTCompiler.Task.7.0.0-preview.2.22074.8-x64.msi is installing .... Done
Downloading Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 (7.0.0-preview.2.22074.8)
Microsoft.MonoTargets.Sdk.7.0.0-preview.2.22074.8-x64.msi is installing .... Done
```

Restarted VS and now I was finally able to debug MAUI on Android. But that didn't really explain why the global.json file seems to be ignored. Or why maccatalyst is even necessary when debugging Android only. Or why installing everything through VS installer misses that one. Or why .NET 7 is still used.

**Comment by jfversluis** [comment]
Seems like this got untangled. If not, please let us know what is still impacting you. Thanks!

**Comment by christiannagel** [comment]
I have a similar (or the same) issue with this error: *the following workloads must be installed: maccatalyst*.
The error only happens with Visual Studio. Using the .NET CLI, the build compiles without error.

I'm using Visual Studio version 17.3.0 Preview 3.0.

CLI:

`dotnet --version`

returns

```
6.0.302
```

`dotnet --list-sdks`

returns

```
3.1.421 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]
6.0.107 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.302 [C:\Program Files\dotnet\sdk]
6.0.400-preview.22330.6 [C:\Program Files\dotnet\sdk]
7.0.100-preview.6.22352.1 [C:\Program Files\dotnet\sdk]
```

`dotnet workload list`

shows

```
android                     SDK 6.0.300
maccatalyst                 SDK 6.0.300
maui                        SDK 6.0.300
wasm-tools                  VS 17.2.32630.192
```

I have a global.json file in place. Command-line compiles successfully, just Visual Studio fails with the missing maccatalyst workload.

**Comment by christiannagel** [comment]
I installed the maccatalyst using .NET 7.0.100-preview.6.22352.1 which finally allowed to compile the .NET MAUI application using Visual Studio. 

It looks like somewhere during the build process the content of global.json is not used anymore. After using the .NET SDK 6 first, later .NET 7 is used. Having this workload with both SDKs installed seems to fix this issue.

**Comment by ali50m** [comment]
I am also going through a similar problem like this. When building a MAUI project (only target Android) in VS 2022 Version 17.3.0 Preview 6.0, it tells me need to install **maccatalyst** workload.

Here is the SDKs in my laptop:
```
6.0.302 [C:\Program Files\dotnet\sdk]
6.0.400-preview.22330.6 [C:\Program Files\dotnet\sdk]
7.0.100-preview.6.22352.1 [C:\Program Files\dotnet\sdk]
```

The global.json trick does not fix it. After installing maccatalyst workload, it works now. 
But it is weird as I only build targetting for Android.
```
dotnet workload install maccatalyst
```
