### ISSUE TITLE
[iOS] ScrollView's ContentSize and ScrollX changes when the device is rotated multiple times

### ISSUE THREAD

**Issue by NavaneethS** [dotnet/maui#6499]
### Description

When the iOS device is rotated clockwise 2 times with a ScrollView which has content large enough to be scrolled, its ContentSize is not the same as its initial value (width has reduced) and the ScrollX value also changes to 0. 

### Steps to Reproduce

1. Run the attached solution targeting iOS. 
2. Scroll the `ScrollView` to its right-bottom extreme. 
3. Rotate the device clockwise, notice the `ContentSize`, `ScrollX`, `ScrollY` values at the top. 
4. Rotate the device clockwise again and notice the values at the top
[InteractiveScrollView.zip](https://github.com/dotnet/maui/files/8560163/InteractiveScrollView.zip)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by v-longmin** [comment]
Verified repro on iOS 15.4. Repro project:
[InteractiveScrollView.zip](https://github.com/dotnet/maui/files/8560344/InteractiveScrollView.zip)

**Comment by VincentBu** [comment]
still repros on IOS with vs main build[32510.390.main]

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 5.0. Not Repro with sample project [InteractiveScrollView.zip](https://github.com/dotnet/maui/files/8560163/InteractiveScrollView.zip).
