### ISSUE TITLE
AbsoluteLayout not always setting child position and size as requested.

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#6500]
### Description

In the attached sample, the entire screen is red because AbsoluteLayout is not setting the size of 'settingscontrol1' as specified.  Instead it is wrongly setting the size and position of 'settingscontrol1' to span the entire AbsoluteLayout.

### Steps to Reproduce

1. Build and run attached sample in an Android emulator.
2. The entire AbsoluteLayout will be red because 'settingscontrol1' spans the entire AbsoluteLayout size instead of being sized+positioned as specified.

The red 'settingscontrol1' should only be as large as needed for the label and should be centered on the screen.
Also the log output shows "settingscontrol1: 392.7,722.9" which means that the  'settingscontrol1' is simply being sized to fill the entire AbsoluteLayout.

[layoutbug2.zip](https://github.com/dotnet/maui/files/8560302/layoutbug2.zip)

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

no

**Comment by kristinx0211** [comment]
verified repro on android 11 with above project.

**Comment by kristinx0211** [comment]
still an issue on android with 17.3.0 Preview 2.0 [32507.29.main].

**Comment by hartez** [comment]
This is fixed by #7116.

**Comment by hartez** [comment]
Spoke too soon.
