### ISSUE TITLE
The UmAlQura calendar is getting crashed.

### ISSUE THREAD

**Issue by MuniappanSubramanian** [dotnet/maui#6505]
### Description

We have to get culture info based on calendar types and set a calendar for culture. While setting a calendar for culture, the application getting crashed by using the **UmAlQura**  calendar. The Hebrew, Hijri, Persian, Thai Buddhist, Taiwan, and Korean calendars are working fine.

### Steps to Reproduce

1. Run the sample
2. Application crashed

Sample: 
[UmAlQuaraCalendar.zip](https://github.com/dotnet/maui/files/8562826/UmAlQuaraCalendar.zip)

Crash:
![Screen Shot 2022-04-26 at 4 46 58 PM](https://user-images.githubusercontent.com/46158936/165293151-57bfeced-23ec-4848-a177-b7f012149421.png)

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

iOS 15.2, Android 11 and Windows

### Did you find any workaround?

NO

**Comment by drasticactions** [comment]
It threw for me in a dotnet 6 console app

<img width="804" alt="image" src="https://user-images.githubusercontent.com/898335/165328613-b58479c4-79d1-4204-82cd-5631547363f2.png">

I doubt this is MAUI related.

**Comment by steveisok** [comment]
We apply a few filters on the ICU data file in order to get it to be as small as possible.  My guess is the UmAlQura is being filtered out.

**Comment by steveisok** [comment]
Then again, if it's throwing in a console app, maybe not.

**Comment by Eilon** [comment]
@steveisok / @tarekgh - any idea where we should move this bug? Presumably it's not something we can fix within MAUI itself?

**Comment by Eilon** [comment]
Alright so it sounds like there is no known issue here as long as calendars are used per those documents. Closing this out. If someone feels that they followed the calendar guidance (that is, only using calendars compatible with the specified culture) but there is still an issue, please let us know.
