### ISSUE TITLE
[MacCatalyst] Lifecycle events don't trigger for minimizing and locking device

### ISSUE THREAD

**Issue by DeanFaizal** [dotnet/maui#6507]
### Description

Lifecycle events aren't firing for MacCatalyst on minimize/restore, and on lock/unlock device. 

### Steps to Reproduce

[MauiLifecycle.zip](https://github.com/dotnet/maui/files/8564007/MauiLifecycle.zip)

Attached repro project. 
STR:
1. Launch app
2. Minimize app
3. Restore app
4. Lock mac
5. Unlock mac

Expected result:
DidEnterBackground and WillEnterForeground events triggered for the above steps.

Actual result:
Only OnActivated event has been triggered.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacCatalyst 14.0

**Comment by Redth** [comment]
These are firing now for me in maui main.

```csharp
.ConfigureLifecycleEvents(lifecycle =>
{
#if IOS || MACCATALYST
		lifecycle.AddiOS(ios =>
		{
			ios.OnActivated(app =>
			{
				Console.WriteLine("ACTIVATE");
			});

			ios.OnResignActivation(app =>
			{
				Console.WriteLine("RESIGN");
			});

			ios.DidEnterBackground(app =>
			{
				Console.WriteLine("BACKGROUND");
			});

			ios.WillEnterForeground(app =>
			{
				Console.WriteLine("FOREGROUND");
			});
		});
#endif
```

**Comment by DeanFaizal** [comment]
Sounds like the fix is in RC2
