### ISSUE TITLE
CollectionView Crash on Android... RequestBuilder Error

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#6518]
### Description

Pull down https://github.com/dotnet-presentations/dotnet-maui-workshop and run Final on Android. Load data and then scroll up and down. Images don't load, but you will get a crash of: 

"System.InvalidOperationException
Message=An attempt was made to transition a task to a final state when it had already completed."

If you continue at this point, it is followed by

"Java.Lang.IllegalStateException
Message=You can't start or clear loads in RequestListener or Target callbacks. If you're trying to start a fallback request when a load fails, use RequestBuilder#error(RequestBuilder). Otherwise consider posting your into() or clear() calls to the main thread using a Handler instead."

### Steps to Reproduce

Pull down https://github.com/dotnet-presentations/dotnet-maui-workshop and run Final on Android. Load data and then scroll up and down. 

### Version with bug

Release Candidate 2

### Last version that worked well

Preview 14

### Affected platforms

Android

### Affected platform versions

All Android

### Did you find any workaround?

None

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android with above project.

**Comment by mattleibow** [comment]
This was fixed in #6739 however the next issue is that sometimes the images don't load again #6783
