### ISSUE TITLE
The Shell FlyoutItems didn't appear when the app is in dark theme

### ISSUE THREAD

**Issue by pictos** [dotnet/maui#6519]
### Description

When I set my Motorola One with Android 10 to the `Light Theme` I can see the Flyout and its items as shown in the image below:
![image](https://user-images.githubusercontent.com/20712372/165408097-871a2a2c-d139-483a-8e0b-c0683b2344b4.png)

Now if I `terminate` the application and change my theme to `Dark Theme` I can't see the items anymore, as shown by the image below:
![image](https://user-images.githubusercontent.com/20712372/165408185-ecd40717-782e-40c3-a563-3d40bb960e2f.png)

Now If I: 
1. Open the application and switch to the `Light Theme` 
2. and open the app 
3. and switch to `Dark Theme` (without terminating the app)
4. and open the app again I can see the items (image below)

![image](https://user-images.githubusercontent.com/20712372/165408416-b259b5f2-c6bb-4a20-9c35-1be6e698f3de.png)

### Steps to Reproduce

1. Set your mobile device theme to be Dark;
2. [Open the CommunityToolkit.MAUI sample application](https://github.com/CommunityToolkit/Maui);
3. Open the Flyout

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
@pictos are you by any chance able to run this against the latest version of .NET MAUI to see if this still reproduces? So not the latest released one, but like the actual code on main? You know how to do that?

**Comment by pictos** [comment]
@jfversluis I don't know how to grab the code at `main`. Do you have any tutorials? And also how can I fallback to the public release?

**Comment by jfversluis** [comment]
Ah no worries, I thought you might know how to do it, but don't sweat it, it's a bit of a hassle and I don't want you to break your dev environment. I'll look into it!

**Comment by jfversluis** [comment]
Can't reproduce on latest main 🎉

![image](https://user-images.githubusercontent.com/939291/167575531-a6029316-5bc8-4ed3-aa09-acdc8722d62e.png)
