### ISSUE TITLE
CarouselView crashes with Loop="True"

### ISSUE THREAD

**Issue by SkeletonJohn** [dotnet/maui#6521]
### Description

Creating a CarouselView and setting Loop="True" causes a Java.Lang.IllegalStateException exception:

Java.Lang.IllegalStateException
  Message=The specified child already has a parent. You must call removeView() on the child's parent first.

Setting Loop="False" it works as expected

Please see attached example.

[CarouselViewIssue.zip](https://github.com/dotnet/maui/files/8567573/CarouselViewIssue.zip)
.

### Steps to Reproduce

1. Create new .Net Maui App (Preview)
2. Update MainPage.xaml to include a CarouselView with Loop="True" parameter.
3. Add Content to the CarouselView
`
   <CarouselView.ItemsSource>
                <x:Array Type="{x:Type ContentView}">
                    <ContentView>
                        <StackLayout BackgroundColor="Blue" />
                    </ContentView>
                    <ContentView>
                        <StackLayout BackgroundColor="Red" />
                    </ContentView>
                </x:Array>
            </CarouselView.ItemsSource>
`
5. Run the app
6. Crashes
7. Set the Loop parameter to Loop="False"
8. Run the app
9. Works as expected.

      

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Only tested on Android 11 - API 30

### Did you find any workaround?

Only to use Loop=False, but I would like it to loop.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android with above project.

**Comment by rmarinho** [comment]
Can you use data for the ItemsSource our do you need to really use COntentView ? 

Your example should be written like this 

```
 <CarouselView 
            Loop="True"
            VerticalOptions="FillAndExpand" 
            HorizontalOptions="FillAndExpand">
        <CarouselView.ItemsSource>
            <x:Array Type="{x:Type Color}">
                <Color>Red</Color>
                <Color>Blue</Color>
            </x:Array>
        </CarouselView.ItemsSource>
        <CarouselView.ItemTemplate>
            <DataTemplate>
                <ContentView>
                    <StackLayout BackgroundColor="{Binding .}"/>
                </ContentView>
            </DataTemplate>
        </CarouselView.ItemTemplate>
    </CarouselView>
    ```
