### ISSUE TITLE
BarTextColour remains [white] for ToolBarItem on Android

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#6523]
### Description

A simple supplied reproduction demonstrates the issue.
On Android, when setting the colour of text on the toolbar, the ToolBarItem's text color remains white:
See below for rendering on Android (fail):

![image](https://user-images.githubusercontent.com/7484186/165416545-05fe552a-3866-4579-95e2-e6341224ca52.png)

See below for rendering on iOS (pass):

![image](https://user-images.githubusercontent.com/7484186/165416608-cde53807-5a86-4e84-b914-8891d35f9933.png)

### Steps to Reproduce

1. Open the reproduction from github [https://github.com/hbraasch/ToolBarTextColorTester.App.git] in Visual Studio
2. Run the app for Android and iOS
3. Observe the differences

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.0-Api 31 (only one tested)

### Did you find any workaround?

No

**Comment by v-longmin** [comment]
Verified repro on Android 12.0, not repro on iOS15.4. Repro project:
[ToolBarTextColorTester.App-master.zip](https://github.com/dotnet/maui/files/8567869/ToolBarTextColorTester.App-master.zip)

**Comment by hbraasch** [comment]
Yes, it works fine on iOS. Only a Android problem.

**Comment by ddavid-son** [comment]
Can confirm this as well, running android 11 - pixel 5 - api 30 
on VS22 Version 17.2.0 Preview 5.0 

due note that this happens although the Shell.foregroundColor = "#Black"

This problem does not occur in VS22 Version 17.2.0 Preview 4.0 and 1.0

**Comment by pictos** [comment]
I tried on Windows and I can reproduce the same behavior as Android.
