### ISSUE TITLE
[bug][android]When I add controls using code, the ScrollView doesn't scroll

### ISSUE THREAD

**Issue by yiszza** [dotnet/maui#6530]
### Description

When I add controls using code, the ScrollView doesn't scroll

### Steps to Reproduce

https://user-images.githubusercontent.com/42995476/165513963-75e8d74b-16bf-45d0-b00c-7e706c452e47.mp4

Code source:
[MauiApp2.zip](https://github.com/dotnet/maui/files/8569716/MauiApp2.zip)

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android12

### 

Relevant log output

_No response_

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android with above project.

**Comment by VincentBu** [comment]
still repro with vs main build

**Comment by yiszza** [comment]
Any update and/or workaround for this? @Redth  @davidortinau @samhouts
