### ISSUE TITLE
LocalApplicationData folder isolation is inconsistent between Android and Windows

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6533]
### Description

Output:

Windows:
`C:\Users\username\AppData\Local\file.txt`

Android
`/data/user/0/com.companyname.mauiapp2/files/file.txt`

This means that on Windows, the _**data will collide with other applications**_ whereas on Android files from different applications are isolated if application `ApplicationId` is unique per application.

### Steps to Reproduce

Create a new MAUI app and use the following code:

```
private void TestWriteReadFile()
{
	string filePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "file.txt");
	var savedContent = $"text saved to {filePath}";
	File.WriteAllText(filePath, savedContent);
	var loadedContent = File.ReadAllText(filePath);
	Trace.WriteLine(loadedContent);
}
```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

probably all

**Comment by kristinx0211** [comment]
can be reproduced using the above code on 17.3.0 Preview 1.0 [32425.291.main].
