### ISSUE TITLE
RTL is not working in AbsoluteLayout

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#6540]
### Description

Setting FlowDirection as RightToLeft has no effect when using AbsoluteLayout in Android platform. Works fine with WinUI.
[MauiApp6.zip](https://github.com/dotnet/maui/files/8572199/MauiApp6.zip)

MAUI:
![Screenshot_1651064557](https://user-images.githubusercontent.com/42271912/165524289-fbb49e9c-4013-4839-902a-dcfe665d72b0.png)

XAMARIN:
![Screenshot_1651064683](https://user-images.githubusercontent.com/42271912/165524423-1f3c70d4-dfa0-4c1f-9715-2525672ec921.png)

### Steps to Reproduce

Run the attached sample

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

ANDROID 12

**Comment by kristinx0211** [comment]
verified repro on android 12 with above project.
