### ISSUE TITLE
Add new view in MAUI add dictionary template instead

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#6544]
### Description

Add new view in MAUI add dictionary template instead

### Steps to Reproduce

1.Create a Maui app.
2.Add new view.
3,Create dictionary file instead.

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 14

### Affected platforms

Windows

### Affected platform versions

..

### Did you find any workaround?

Add Page and replace the tags with view.

### Relevant log output

```shell
No
```

**Comment by DoubleDBE** [comment]
Already fixed in RC2: #6125

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Not repro on Windows. Sample Project: [6544.zip](https://github.com/dotnet/maui/files/8578655/6544.zip)

**Comment by danies8** [comment]
I used vs community.
![image](https://user-images.githubusercontent.com/1079689/165684897-93a7746f-0342-4858-b005-87595af4fcdd.png)
