### ISSUE TITLE
[iOS & MacOS] Preview 14 Shell Renders as Blank White/Black Screen on iOS & MacCatalyst

### ISSUE THREAD

**Issue by alecfilios** [dotnet/maui#6545]
### Description

Using Preview 14, MAUI Shell shows a blank white screen on iOS simulators and a black screen on Mac Catalyst (maybe dark theme enabled makes it black). Debugging through the code, the page gets constructed and initialized as expected without issue or exception. But nothing gets rendered on the screen.

### Steps to Reproduce

1. Create a MAUI app
2. Follow this tutorial: https://www.youtube.com/watch?v=eVgLPYQ_ih8&ab_channel=LearnIT

### Version with bug

Preview 14

### Last version that worked well

Preview 13

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15, MacOs Monterey 12.3.1(Catalyst)

**Comment by jfversluis** [comment]
This was indeed an issue on preview 14 that is fixed with RC1 & 2. Please update to the latest version and it should be fixed!

**Comment by alecfilios** [comment]
> 

Oh alright thank you! One question, how do Update Directly from my 17.0 to 17.2?

**Comment by alecfilios** [comment]
> This was indeed an issue on preview 14 that is fixed with RC1 & 2. Please update to the latest version and it should be fixed!

Based on the instructions I followed here: https://devblogs.microsoft.com/dotnet/dotnet-maui-rc-2/ 
Quote:
"To use .NET MAUI RC2 on Mac, follow the [command-line instructions](https://github.com/dotnet/maui/wiki/macOS-Install) on the wiki. Support for .NET MAUI in Visual Studio 2022 for Mac will ship formally in a future preview."

And then in the instructions: 
> dotnet --version 
returns: 6.0.202
and 
> sudo dotnet workload install maui --source https://api.nuget.org/v3/index.json
Retuns:
Workload(s) 'maui' are already installed.
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Updated advertising manifest microsoft.net.sdk.macos.
Garbage collecting for SDK feature band(s) 6.0.200...

Successfully installed workload(s) maui.

Even tho I think that everything run smoothly I'm pretty sure that there is a newer dotnet and a newer .Net MAUI for me to install in order to get everything to work.
Any suggestions?

**Comment by robsoft** [comment]
Hi - I'm encountering this on Visual Studio for Mac 2022 Preview, build 8754. I've updated the Maui workloads etc - is there anything else I can do to resolve this problem on the Mac right now, or do I need to wait for a newer VS for Mac update? Thanks!
