### ISSUE TITLE
RC2 Solution can't build if CommunityToolkit.Maui is installed

### ISSUE THREAD

**Issue by obenyaala** [dotnet/maui#6550]
### Description

Hi,
I have updated my VS22 to preview 5 and it broke my app. 
When CommunityToolkit.Maui is removed everything works again just fine. 
I am using CommunityToolkit.Maui 1.0.0-rc1
When building the solution i get: 
![error](https://user-images.githubusercontent.com/6730924/165548867-37727fcf-0129-4056-94a7-87c754be0bb4.PNG)

Is there a way I can to revert to Preview4 (Tried searching could not find an exe)

### Steps to Reproduce

1.  Create Maui Solution
2. Install CommunityToolkit.Maui 1.0.0-rc1

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

Windows

### Affected platform versions

10.0.17763.0

**Comment by janseris** [comment]
Does using VS Preview 5 imply using MAUI RC 2?

**Comment by obenyaala** [comment]
yes that is what I have implied. Sorry I did not make it clear. 

I have tried to downgrad to RC1, to see if the problem will be fixed. I could not find a thread on how to downgrade.

**Comment by pictos** [comment]
@obenyaala we just released a new version of the communityToolkit that was built on top of .NET MAUI RC2, can you try with that and tell me if that works?

**Comment by obenyaala** [comment]
@pictos  yes, updating CommunityToolkit.Maui to RC2 fixed the problem. Thanks for the fast answer.
