### ISSUE TITLE
Android: AppShell prevents gestures on native control

### ISSUE THREAD

**Issue by dotMorten** [dotnet/maui#6553]
### Description

When using our native Android map control that uses motion events to detect and act on drag and pinch to navigate the control, the `AppShell` view intercepts these events and prevents dragging and pinching beyond the first few pixels (if appears that if you drag or pinch very slowly you can get a little further before this event gets intercepted and stops responding).
The control works fine outside an `AppShell`.

The native control is relying on `GestureDetector`, `ScaleGestureDector` and `MotionEvents`/`Touch` to react to user input. It returns true on these event handlers to mark them as handled when reacting to user input.

It was suggested by @PureWeen that locking the flyout behavior could address it [based on]( https://github.com/dotnet/maui/blob/5e8e41a691d0c8b8ca759c182e6ae89ea3d5c3a3/src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFlyoutRenderer.cs#L162-L163), but that didn't help. ie in AppShell constructor:
```cs
        this.FlyoutBehavior = FlyoutBehavior.Locked;
```
When doing this though, I do notice that the touch events does go through the flyout and down into the map control (but still with the limited interaction).
Setting `InputTransparent=true` or `IsEnabled=false` on the appshell also doesn't have any effect.

The same control wrapped in Xamarin.Forms AppShell does not exhibit this behavior.

### Steps to Reproduce

1. Open the following project: [MauiApp21.zip](https://github.com/dotnet/maui/files/8568744/MauiApp21.zip)
2. Run the project.
3. On the presented world map, attempt to pan an zoom
4. Notice that the map will stop responding to pan and zoom interactions after a few pixels of finger movement.
5. In `App.xaml.cs`, change the app to launch `MainPage` instead of `AppShell`, and observe interactions now work fine.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Don't use AppShell, but that's hardly a workaround.

### Update 
As [noted below](https://github.com/dotnet/maui/issues/6553#issuecomment-1113919719) looks like only horizontal gestures are getting blocked. Vertical pan and zoom/pinch works (but as soon as a horizontal threshold is performed all interaction stops)

**Comment by Sasikumar3595** [comment]
@jfversluis,

We are also facing the same issue after the VS update.

**Comment by beto-rodriguez** [comment]
Same issue [here](https://github.com/beto-rodriguez/LiveCharts2/blob/dev/src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/CartesianChart.xaml.cs#L832).

In my case, the zoom gesture fires the zoom feature in a chart, notice how it is only working when the pinch is vertical, and ignored when horizontal (3 MB gif):

![maui-gesture-bug](https://user-images.githubusercontent.com/10853349/166092210-1b342be7-2a36-4473-a0a6-b9fa912397a9.gif)

**Comment by dotMorten** [comment]
@beto-rodriguez aaaah good call! That explains why I see a little bit of interaction and then stops. If I very carefully pan or pinch vertically I can go pretty far, but as soon as I exceed a small horizontal threshold it stops the interaction.

**Comment by dotMorten** [comment]
I'm curious if this is caused by this behavior in `ViewPager2`?
https://developer.android.com/training/animation/vp2-migration#nested-scrollables

**Comment by dotMorten** [comment]
Built a Xamarin.Android .net6 app and using the `ViewPager2` then putting my control inside it, and I observe the exact same behavior, so pretty confident this is caused by that

**Comment by shimingsg** [comment]
verified repro on android 11 with VS 17.3.0 Preview 2.0 [32506.315.main]
change the app to launch MainPage instead of AppShell, and observe interactions now work fine

**Comment by beto-rodriguez** [comment]
This now seems to be working properly for me on net 7

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 5.0. Not repro on android device platform with sample project.
[MauiApp21.zip](https://github.com/dotnet/maui/files/12248877/MauiApp21.zip)

**Comment by dotMorten** [comment]
Confirmed
