### ISSUE TITLE
Hot Restart gives instant error

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#6554]
### Description

When trying to use hot restart as soon as I select the team I get an error instantly
"There was an error whilte trying to automatically provision the project please check the logs"

![image](https://user-images.githubusercontent.com/5493492/165580886-b512b5ab-80b3-44e5-94eb-d4ebc33d6181.png)

### Steps to Reproduce

1 create new blazor maui project
2 - Slect ios local device
3 - A wizard appears and prompts for team selection
4 - Select a team (apple developer Id)
5 - Observe the following error appears
![image](https://user-images.githubusercontent.com/5493492/165581201-a962f5ce-2833-42fb-822d-2ac2f65ac137.png)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Preview 13

### Affected platforms

iOS

### Affected platform versions

Windows server 2022

### Did you find any workaround?

No, tryed to import certificates to no avail

### Relevant log output

```shell
see picture above
```

**Comment by drasticactions** [comment]
This is a Visual Studio issue, not a MAUI one. This screen also applies to Xamarin.Forms as well.

I would go to https://developercommunity.visualstudio.com and file the issue there.
