### ISSUE TITLE
In RC2, FontImageSource does not work on Image.Source

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#6559]
### Description

I can use for instance FontAwesome to have MAUI render FontIcons on Labels.

`<Image x:Name="HouseImage" >
    <Image.Source>
        <FontImageSource
            FontFamily="FA-S"
            Glyph="{x:Static fontAwesome:FontAwesomeIcons.House}"
            Size="20"
            Color="White" />
    </Image.Source>
</Image> `

**Repro**
[MauiIssueFontImageSource](https://github.com/dotnet/maui/files/8427583/MauiIssueFontImageSource.zip) 

Same issues
[5859](https://github.com/dotnet/maui/issues/5859#issue-1194658481) 

### Steps to Reproduce

1. Create a .NET MAUI App
2. Add an IconFont such as FontAwesome to the Resources\Fonts folder
3. Register the Font with MauiAppBuilder
4. Add an Image to the Home View referencing any glyph from the IconFont via FontImageSource

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12 API 31

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
verified repro  on android 11. Icon green is shown, Icon red not.

**Comment by Redth** [comment]
Fixed in upcoming RC3
