### ISSUE TITLE
VerticalOptions.Center ignored on iOS, Droid and Windows

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#6561]
### Description

Label with VerticalOptions set to .Center isn't appearing entered vertically.

### Steps to Reproduce

Given the following code:
```
            Content = new VerticalStackLayout()
            {
                VerticalOptions = LayoutOptions.Fill,
                HorizontalOptions = LayoutOptions.Fill,
                Children =
                {
                    new Label()
                    {
                        Text = "Nothing to see here, move along",
                        VerticalOptions = LayoutOptions.Center,
                        HorizontalOptions = LayoutOptions.Center,
                    }
                }
            };
```
Shouldn't the label be in the centre of the have vertically?

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Preview 14

### Affected platforms

iOS, Android, Windows, I was *not* able test on other platforms

### Affected platform versions

iOS 15

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
setting `VerticalOptions = LayoutOptions.Center,` does not work at all. but it can work  on android. repro project:
[MauiApp12.zip](https://github.com/dotnet/maui/files/8580192/MauiApp12.zip)

**Comment by hartez** [comment]
> Shouldn't the label be in the centre of the have vertically?

It _is_ centered in the space allocated for it by the VerticalStackLayout, but the VerticalStackLayout is only giving it the height it's asking for (which is just enough to contain the text).

This will give you the layout you are aiming for:

```
Content = new Grid()
{
	Children =
		{
			new Label()
			{
				Text = "Nothing to see here, move along",
				VerticalOptions = LayoutOptions.Center,
				HorizontalOptions = LayoutOptions.Center,
			}
		}
};
```

**Comment by JohnHDev** [comment]
@hartez surely this can't be the correct behaviour? Center does nothing inside vertical stack layouts?

If the Content of the page is the label itself it still has the same issue.
