### ISSUE TITLE
TranslationY is ignored

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#6562]
### Description

Setting TranslationY values no longer have an effect

### Steps to Reproduce

Given the following code:
            Content = new VerticalStackLayout()
            {
                VerticalOptions = LayoutOptions.Fill,
                HorizontalOptions = LayoutOptions.Fill,
                Children =
                {
                    new Label()
                    {
                        Text = "Nothing to see here, move along",
                        VerticalOptions = LayoutOptions.Start,
                        HorizontalOptions = LayoutOptions.Center,
                        TranslationY = 1000
                    }
                }
            };

I would expect the label to be off the bottom of the page. You can try with other TranslationY values, but it has no effect.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Preview 14

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15

### Did you find any workaround?

Margin can work with negative values

**Comment by v-longmin** [comment]
@JohnHDev Could you share your repro project for us so that wo can reproduce this issue? Thanks.

**Comment by shimingsg** [comment]
verified repro on iOS, not repro on Android and windows

**Comment by JohnHDev** [comment]
@shimingsg already verified this with the example above.
