### ISSUE TITLE
Camera access after Blazor Hybrid Android removal of the `GetWebChromeClient` API

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#6565]
The latest change that removed 'GetWebChromeClient' disables the ability for the camera to function from JavaScript in the Maui Webview. 

**Our Scenario on Android**
We are using a JavaScript program at Runtime in the Maui WebView to prompt the user for permission to the camera. Once approved the JavaScript uses the camera to look for barcodes and once found triggers an event to show the data on the screen. After the most recent change after the user approves access to the camera the javascript can no longer access the camera.

Will you please look into this and provide us with a fix? As of now our application is unable to use the camera.

If you know of a work around that would be great for now.

Thanks,

_Originally posted by @agingo in https://github.com/dotnet/maui/issues/5907#issuecomment-1111305195_

**Comment by javiercn** [comment]
@TanayParikh I think we are good here.

The customer reports that [the solution](https://github.com/dotnet/maui/issues/4170#issuecomment-1111813903) we provided works for them and it is easier to implement than the previous one they had, so I think we can close this issue.

If there is any concrete reason for us to reconsider this, please feel free to reopen the issue.

**Comment by TanayParikh** [comment]
> If there is any concrete reason for us to reconsider this, please feel free to reopen the issue.

I have serious concerns about that approach, primarily as they're creating a new `WebChromeHandler`:

```csharp
public class MauiWebChromeClient : WebChromeClient
{
        public override void OnPermissionRequest(PermissionRequest request)
        {
            request.Grant(request.GetResources());
        }
}
```

(from https://github.com/dotnet/maui/issues/4170#issuecomment-1110883706)

This means the [`BlazorWebChromeClient`](https://github.com/dotnet/maui/blob/9175dd04afae9e51854faae7f161f4000d6180ad/src/BlazorWebView/src/Maui/Android/BlazorWebChromeClient.cs#L15) isn't used, which could result in missing functionality and future issues. I feel like we should **strongly** discourage that pattern as it'll likely lead to long term pains. Re-opening the issue on that note, please let me know if I'm blowing things out of proportion here 😄

**Comment by javiercn** [comment]
@TanayParikh I didn't mean their approach, I meant **the one I provided** which they also said they tested and worked for them.

**Comment by TanayParikh** [comment]
I believe you're referring to [this](https://github.com/dotnet/maui/issues/4170#issuecomment-1111813903)? If so, that approach still uses the newly created `MauiWebChromeClient`.

**Comment by TanayParikh** [comment]
That'd resolve the issues currently being faced. However, that could likely pose long-term maintainability overhang. Given `BlazorWebChromeClient`, we likely wouldn't think twice about adding additional functionality ([via additional `WebChromeClient` overrides](https://docs.microsoft.com/dotnet/api/android.webkit.webchromeclient?view=xamarin-android-sdk-12#methods)), and that functionality would not automatically light up in user code due to the proxy they'd be using. This could prove to be quite challenging to debug as well, without the appropriate context.

Given the alternative, I think it may be worthwhile to reconsider making `BlazorWebChromeClient` public. There aren't any _new_ APIs we'd be introducing, just exposing the existing `WebChromeClient` APIs.

https://github.com/dotnet/maui/blob/9175dd04afae9e51854faae7f161f4000d6180ad/src/BlazorWebView/src/Maui/Android/BlazorWebChromeClient.cs#L17-L41

**Comment by TanayParikh** [comment]
Discussed with @javiercn offline. Our current position is going to be to recommend the proxy approach Javier had above, with additional proxied overrides for [_**ALL**_ virtual methods in the base `WebChromeClient`](https://docs.microsoft.com/en-us/dotnet/api/android.webkit.webchromeclient?view=xamarin-android-sdk-12#methods).

**Comment by Eagle3386** [comment]
> `csharp blazorWebview.BlazorWebViewInitialized += (s, a) =>`

From what I can see that syntax is wrong as `BlazorWebViewInitialized` isn't an event we can subscribe to like that - at least according to its defining interface:
https://github.com/dotnet/maui/blob/b50ed5695ff814aa83d8849daf35e5a83e84ceeb/src/BlazorWebView/src/Maui/IBlazorWebView.cs#L50-L54
... and even current usage:
https://github.com/dotnet/maui/blob/b50ed5695ff814aa83d8849daf35e5a83e84ceeb/src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs#L107-L110

Furthermore, it seems to me that doing an additional `BlazorWebViewInitialized()` call would overwrite any previously set `BlazorWebViewInitializedEventArgs`, i. e. above's `WebView = PlatformView` wouldn't execute any longer.

Or am I missing something?

**Comment by TanayParikh** [comment]
Event is here:

https://github.com/dotnet/maui/blob/b50ed5695ff814aa83d8849daf35e5a83e84ceeb/src/BlazorWebView/src/Maui/BlazorWebView.cs#L47-L50

and it's called here:

https://github.com/dotnet/maui/blob/b50ed5695ff814aa83d8849daf35e5a83e84ceeb/src/BlazorWebView/src/Maui/BlazorWebView.cs#L70-L71

**Comment by Eagle3386** [comment]
@mkArtakMSFT are you serious about the milestone change? Because for #5804 you reverted that & this issue right here is of way more importance since camera access in a MAUI Blazor Hybrid app is obviously more common than JS interop outside a Razor component..

**Comment by javiercn** [comment]
@Eagle3386 You don't need to extend anything.

You can use this snippet to achieve this:

```csharp
blazorWebview.BlazorWebViewInitialized += (s, a) =>
{
#if ANDROID
    a.WebView.SetWebChromeClient(new MyChromeClient(a.WebView.WebChromeClient));
#endif
};

#if ANDROID
    private class MyChromeClient : WebChromeClient
    {
        private WebChromeClient webChromeClient;

        public MyChromeClient(WebChromeClient webChromeClient) => this.webChromeClient = webChromeClient;

        public override bool OnCreateWindow(Android.Webkit.WebView view, bool isDialog, bool isUserGesture, Message resultMsg) => webChromeClient.OnCreateWindow(view, isDialog, isUserGesture, resultMsg);

        public override bool OnShowFileChooser(Android.Webkit.WebView webView, IValueCallback filePathCallback, FileChooserParams fileChooserParams) => webChromeClient.OnShowFileChooser(webView, filePathCallback, fileChooserParams);

        // Any additional override you need to perform.
    }
#endif
```

The only discussion we had left here is whether we wanted to make our custom `BlazorWebChromeClient` public so that people could extend it instead of wrap it.

**Comment by javiercn** [comment]
@Eagle3386 the platform doesn't force you do this

```csharp
    Content = new Platforms.Android.MauiBlazorWebView(blazorWebView.HostPage, blazorWebView.RootComponents);
```

You can literally do 
```
blazorWebView = (Microsoft.AspNetCore.Components.WebView.Maui.IBlazorWebView)Content;
blazorWebView.BlazorWebViewInitialized += (_, args) =>
    {
      // TODO: Check what's obsolete to be set explicitly.
      args.WebView.Settings.AllowFileAccess = true;
      args.WebView.Settings.DatabaseEnabled = true;
      args.WebView.Settings.MediaPlaybackRequiresUserGesture = false;
      args.WebView.Settings.MixedContentMode = MixedContentHandling.AlwaysAllow;
      args.WebView.Settings.SafeBrowsingEnabled = false;
      args.WebView.Settings.SetGeolocationEnabled(true);
      //args.WebView.Settings.SetGeolocationDatabasePath(args.WebView.Context!.FilesDir!.Path);
      args.WebView.SetWebChromeClient(new MauiBlazorWebChromeClient(args.WebView.WebChromeClient!));
    };
```

And tweak what you need.

As for `MauiBlazorWebChromeClient : WebChromeClient` we might make the class public in the future based on demand or come up with a different alternative. We normally strive away on making implementation details public as it limits our ability to update/change the implementation in the future.

**Comment by Eagle3386** [comment]
@javiercn Sorry for the late reply, but trying your suggestion gives me a `CS1656` compiler error:
> Cannot assign to 'BlazorWebViewInitialized' because it is a 'method group'

All I did was create a `[Project root]\Platforms\Android\MainPage.Android.cs`:
```csharp
#if ANDROID
using Android.Graphics;
using Android.OS;
using Android.Webkit;
using Microsoft.AspNetCore.Components.WebView.Maui;
using AView = Android.Views.View;
using AWebView = Android.Webkit.WebView; 

// ReSharper disable once CheckNamespace - Android-specific extensions to common MainPage
namespace My.Project.AssemblyName;

public partial class MainPage : ContentPage
{
  public MainPage()
  {
    InitializeComponent();
    var blazorWebView = (Microsoft.AspNetCore.Components.WebView.Maui.IBlazorWebView)Content;
    blazorWebView.BlazorWebViewInitialized += (_, args) =>
    {
      args.WebView.Settings.AllowFileAccess                  = true;
      [... left out for brevity...]
      args.WebView.SetWebChromeClient(new MauiBlazorWebChromeClient(args.WebView.WebChromeClient!));
    };
  }

  private class MauiBlazorWebChromeClient : WebChromeClient
  {
    [... left out for brevity...]
  }
}
#endif
```

... and modified the existing `[Project root]\MainPage.xaml.cs` like this:
```csharp
namespace My.Project.AssemblyName;

#if !ANDROID
public partial class MainPage : ContentPage
{
  public MainPage() => InitializeComponent();
}
#endif
```

Regarding `MauiBlazorWebChromeClient : WebChromeClient`, I do understand the reasoning & even appreciate your efforts of not making implementation details public.
But still, all that proxy/wrap code within `MauiBlazorWebChromeClient` is a burden I'd like to ask you (personally and/or your team) to try sooner rather than later to lift from developers consuming your API.
Especially since that whole permissions experience on Android is - to be perfectly honest with you - almost a PITA:
Some of it needs to be defined in code instead of within `AndroidManifest` like required for others, yet (re-) requesting & checking for proper grants is even spread across several code parts.

This is not a rant, but honest criticism for how MAUI's onboarding & usage is/was designed/handled.
It just comes up every time I must discover anew that
- API docs are still missing (not over at MS Docs, but with IntelliSense which shows nothing but the raw method signatures)
- hitting `F12` on a method takes you to its signature-only representation rather than its reference source code - even when using ReSharper!

So, for MAUI I'm begging you to at least consider
1. offer a UI - maybe similar to project properties - to tick checkboxes or select from drop-down lists of multiple values (e. g. `ReadExternalStorage` & `ReadAndWriteExternalStorage` which then set the former & `WriteExternalStorage` automatically) to set required permissions
2. allow for setting `BlazorWebView`'s options via UI mentioned in 1.
3. hide Google's awful design decision of `10.0.2.2` instead of `localhost` (like darn anybody on Earth expects) for host OS access from within the emulator

Again, sorry if all that sounds like a rant - it just feels so tedious implementing workaround after workaround just to get a cross-platform WebRTC app running on all 3 platforms, yet still stick with clean code, SOLID & other best practices…

**Comment by javiercn** [comment]
@Eagle3386 You have a sample [here](https://github.com/MackinnonBuck/MauiBlazorPermissionsExample) that demonstrates how to setup permissions.

**Comment by javiercn** [comment]
> 1. offer a UI - maybe similar to project properties - to tick checkboxes or select from drop-down lists of multiple values (e. g. `ReadExternalStorage` & `ReadAndWriteExternalStorage` which then set the former & `WriteExternalStorage` automatically) to set required permissions

I would file a separate request for this so that it can be tracked/considered independently.

**Comment by javiercn** [comment]
> 2\. allow for setting `BlazorWebView`'s options via UI mentioned in 1.

We would not do this because the security boundary for the WebView is different than the one for the application and the permission sets should be independent.

**Comment by javiercn** [comment]
> 3\. hide Google's awful design decision of `10.0.2.2` instead of `localhost` (like darn anybody on Earth expects) for host OS access from within the emulator

I'm not sure there's anything that can be done about this, but I wouldn't think that we would change platform details as that only increases the learning curve for existing Android developers, this is something we would expect Android to change. That said, I would suggest filing a separate issue for this (sorry for repeating myself) so that it can be considered independently (but I suspect is not possible).

**Comment by TanayParikh** [comment]
Thanks all for the comments, I'm closing this issue out as @MackinnonBuck's sample project [here](https://github.com/MackinnonBuck/MauiBlazorPermissionsExample) demonstrates how this (and other native functionality like location) can be accessed across platforms.

**Comment by Eagle3386** [comment]
@javiercn Despite @TanayParikh force-closed this issue already, I absolutely do want to thank you for your - almost - invaluable help, suggestions & especially code snippets as a starting point.
While the latter weren't totally clear from the start (at least for me 😅), your follow-up comments & suggestions either pointed me into the right direction or even solved the issue completely.

So, again, thanks so, so, so much - you've earned some karma, for sure! 😎🥳
