### ISSUE TITLE
VS2022Preview NetMaui - Problem with the application icon in IOS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#6572]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022Preview-NetMaui---Problem-with-the/10017534)._

---
[severity:It bothers me. A fix would be nice]
**I am developing a multiplatform app using the NetMaui feature.
The app compiles and executes perfectly in the Android emulator and phone, but fauls to compile when switching to IOS.
The messahes given by the compile are as follows:**
Rebuild started...
1>------ Rebuild All started: Project: Recipes, Configuration: Debug Any CPU ------
Restored E:\Projects\NetMAUI\Recipes\Recipes\Recipes.csproj (in 512 ms).
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>Executing SayHello Task to establish a connection to a Remote Server. 
1>			Properties: 
1>				SessionId=73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69, 
1>				Addresss=192.168.1.25, 
1>				SshPort=22, 
1>				TcpPort=55738, 
1>				User=pgmariotti, 
1>				AppName=Recipes,
1>				VisualStudioProcessId=16816,
1>				ContinueOnDisconnected=False
1>Detected signing identity:
1>  Bundle Id: com.companyname.recipes
1>  App Id: com.companyname.recipes
1>Tool /usr/bin/xcrun execution finished (exit code = 1).
1>
1>
1>
1>
1>	com.apple.actool.compilation-results
1>	
1>		output-files
1>		
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/partial-info.plist
1>		
1>	
1>	com.apple.actool.document.warnings
1>	
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][ios-marketing][1024x1024][][][1x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appiconItunesArtwork.png is 1024x962 but should be 1024x1024.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][ipad][83.5x83.5][][][2x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon83[Redacted]@[Redacted] is 167x157 but should be 167x167.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][ipad][76x76][][][2x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon76x76@2x.png is 152x143 but should be 152x152.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][iphone][60x60][][][3x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon60x60@3x.png is 180x169 but should be 180x180.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][iphone][60x60][][][2x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon60x60@2x.png is 120x113 but should be 120x120.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][iphone][40x40][][][3x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon40x40@3x.png is 120x113 but should be 120x120.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][ipad][40x40][][][2x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon40x40@2x.png is 80x75 but should be 80x80.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][iphone][40x40][][][2x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon40x40@2x.png is 80x75 but should be 80x80.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][iphone][29x29][][][3x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon29x29@3x.png is 87x82 but should be 87x87.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][ipad][29x29][][][2x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon29x29@2x.png is 58x55 but should be 58x58.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][ipad][20x20][][][2x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon20x20@2x.png is 40x38 but should be 40x40.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][iphone][20x20][][][3x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon20x20@3x.png is 60x56 but should be 60x60.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][iphone][20x20][][][2x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon20x20@2x.png is 40x38 but should be 40x40.
1>			type
1>			Ambiguous Content
1>		
1>		
1>			affected-items
1>			
1>				./appicon.appiconset/[][iphone][29x29][][][2x][][][]
1>			
1>			catalog
1>			/Users/pgmariotti/Library/Caches/Xamarin/mtbs/builds/Recipes/73f9ad659e93928d1de246ea790b2adab77b18c530ae3002e2f1033ecd827e69/obj/Debug/net6.0-ios/iossimulator-x64/actool/cloned-assets/Assets.xcassets
1>			message
1>			appicon.appiconset/appicon29x29@2x.png is 58x55 but should be 58x58.
1>			type
1>			Ambiguous Content
1>		
1>	
1>	com.apple.actool.errors
1>	
1>		
1>			description
1>			The stickers icon set or app icon set named "appicon" did not have any applicable content.
1>		
1>	
1>
1>
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): error : /usr/bin/xcrun exited with code 1
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): error :
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): error : actool exited with code 1
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): error :
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appiconItunesArtwork.png is 1024x962 but should be 1024x1024.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon83[Redacted]@[Redacted] is 167x157 but should be 167x167.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon76x76@2x.png is 152x143 but should be 152x152.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon60x60@3x.png is 180x169 but should be 180x180.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon60x60@2x.png is 120x113 but should be 120x120.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon40x40@3x.png is 120x113 but should be 120x120.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon40x40@2x.png is 80x75 but should be 80x80.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon40x40@2x.png is 80x75 but should be 80x80.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon29x29@3x.png is 87x82 but should be 87x87.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon29x29@2x.png is 58x55 but should be 58x58.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon20x20@2x.png is 40x38 but should be 40x40.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon20x20@3x.png is 60x56 but should be 60x60.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon20x20@2x.png is 40x38 but should be 40x40.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon29x29@2x.png is 58x55 but should be 58x58.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): error : The stickers icon set or app icon set named "appicon" did not have any applicable content.
1>Done building project "Recipes.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

The app icon is defined in the shared project as a .png file, and its build is set to MauiIcon.

Any ideas?

---
#### Feedback Bot on 4/19/2022, 07:30 PM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 4/21/2022, 02:33 AM: 

(private comment, text removed)
#### Paul G Mariotti on 4/21/2022, 03:18 AM: 

(private comment, text removed)
#### Paul G Mariotti on 4/25/2022, 07:32 AM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 4/24/2022, 02:52 AM: 

(private comment, text removed)
#### Feedback Bot on 4/27/2022, 00:19 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CodeBoop** [comment]
I've similar issues when generating publishing from windows to a mac.

```
Microsoft (R) Build Engine version 17.2.0-preview-22178-04+ce7523296 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Executing SayHello Task to establish a connection to a Remote Server.
                        Properties:
                                SessionId=6a8a7f5e707ebe714243de3e367b5214705fc93c3224329fac43ef1b38aeea56,
                                Addresss=,
                                SshPort=22,
                                TcpPort=,
                                User=[user],
                                AppName=ASB.App,
                                VisualStudioProcessId=,
                                ContinueOnDisconnected=true
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  ASB.Api -> C:\Source\CodeBoop\ASB\ASB.Api\bin\Release\net5.0\ASB.Api.dll
  ASB.Components -> C:\Source\CodeBoop\ASB\ASB.Components\bin\Release\net6.0\ASB.Components.dll
  Detected signing identity:

    Code Signing Key: 
    Provisioning Profile: 
    Bundle Id: 
    App Id: 
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : A 60x60@2x app icon is required for iPhone apps targeting iOS 7.0 and later [C:\Source\CodeBoop\ASB\
ASB.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : A 1024x1024 app store icon is required for iOS apps [C:\Source\CodeBoop\ASB\ASB.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon60x60@3x.png is 179x179 but should be 180x180. [C:\Source\CodeBoop\ASB\ASB
.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon40x40@2x.png is 79x79 but should be 80x80. [C:\Source\CodeBoop\ASB\ASB.App
2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon76x76@2x.png is 151x151 but should be 152x152. [C:\Source\CodeBoop\ASB\ASB
.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon40x40@3x.png is 119x119 but should be 120x120. [C:\Source\CodeBoop\ASB\ASB
.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon29x29@3x.png is 86x86 but should be 87x87. [C:\Source\CodeBoop\ASB\ASB.App
2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon83.5x83.5@2x.png is 166x166 but should be 167x167. [C:\Source\CodeBoop\ASB
\ASB.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon60x60@2x.png is 119x119 but should be 120x120. [C:\Source\CodeBoop\ASB\ASB
.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon40x40@2x.png is 79x79 but should be 80x80. [C:\Source\CodeBoop\ASB\ASB.App
2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appiconItunesArtwork.png is 1016x1016 but should be 1024x1024. [C:\Source\CodeBoo
p\ASB\ASB.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon40x40@2x.png is 79x79 but should be 80x80. [C:\Source\CodeBoop\ASB\ASB.App
2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon60x60@2x.png is 119x119 but should be 120x120. [C:\Source\CodeBoop\ASB\ASB
.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon83.5x83.5@2x.png is 166x166 but should be 167x167. [C:\Source\CodeBoop\ASB
\ASB.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon40x40@2x.png is 79x79 but should be 80x80. [C:\Source\CodeBoop\ASB\ASB.App
2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon60x60@3x.png is 179x179 but should be 180x180. [C:\Source\CodeBoop\ASB\ASB
.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appiconItunesArtwork.png is 1016x1016 but should be 1024x1024. [C:\Source\CodeBoo
p\ASB\ASB.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon29x29@3x.png is 86x86 but should be 87x87. [C:\Source\CodeBoop\ASB\ASB.App
2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon40x40@3x.png is 119x119 but should be 120x120. [C:\Source\CodeBoop\ASB\ASB
.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(842,3): warning : appicon.appiconset/appicon76x76@2x.png is 151x151 but should be 152x152. [C:\Source\CodeBoop\ASB\ASB
.App2\ASB.App.csproj]
  ASB.App -> C:\Source\CodeBoop\ASB\ASB.App2\bin\Release\net6.0-ios\ios-arm64\ASB.App.dll
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\targets\Xamarin.Shared.Sdk.targets(1432,3): warning : The file 'C:\Source\CodeBoop\ASB\ASB.Components\.filenesting.json' does not specify a 'PublishFolderType'
 metadata, and a default value could not be calculated. The file will not be copied to the app bundle. [C:\Source\CodeBoop\ASB\ASB.App2\ASB.App.csproj]
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  /usr/bin/mdimport bin/Release/net6.0-ios/ios-arm64/
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(2045,3): warning : Access to the path 'C:\Users\[user]\Library\Caches\Xamarin\mtbs\builds\ASB.App\6a8a7f5e707ebe71
4243de3e367b5214705fc93c3224329fac43ef1b38aeea56\bin\Release\net6.0-ios\ios-arm64\ASB.App.app\_CodeSignature\CodeResources' is denied. [C:\Source\CodeBoop\ASB\ASB.App2\ASB.App.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.100-rc.1.125\tools\msbuild\iOS\Xamarin.Shared.targets(2045,3): warning : Access to the path 'C:\Users\[user]\Library\Caches\Xamarin\mtbs\builds\ASB.App\6a8a7f5e707ebe71
4243de3e367b5214705fc93c3224329fac43ef1b38aeea56\bin\Release\net6.0-ios\ios-arm64\ASB.App.app\ASB.App' is denied. [C:\Source\CodeBoop\ASB\ASB.App2\ASB.App.csproj]
```

**Comment by cdavidyoung** [comment]
I am having a problem with the iOS appicon as well, although I have not gotten to uploading to the app store yet.  My problem is in Debug mode.

The iOS and MacCatalyst icons are generated when I compile the solution on the Mac.  It can be seen that the iOS icons are smaller than they should be and are also missing the color.

I have attached the Android and iOS simulation icons as well that are generated when I compile the solution on Windows.  This seems to be a problem with ResizetizerNT that only affects iOS builds for real hardware.  I am testing on an iPhone 12 Pro.

![Icons iOS MacCatalyst](https://user-images.githubusercontent.com/937899/206521486-809db707-0690-44c0-955a-6cb2d1aec445.jpg)
![Icons Android](https://user-images.githubusercontent.com/937899/206521534-5ed4f336-f72f-404b-899d-e6b7d2f87c75.png)
![Icons iOS Simulator](https://user-images.githubusercontent.com/937899/206521556-db38e126-93e9-4d58-8324-302660c33872.png)
