### ISSUE TITLE
[IOS] InputTransparency always cascaded to Children even when CascadeInputTransparent= false

### ISSUE THREAD

**Issue by danielftz** [dotnet/maui#6574]
### Description

The TapGestureRecognizer attached on Children of Layout will NOT function when Layout is set `InputTransparent = true`, and `CascadeInputTransparent= false`. 

### Steps to Reproduce

```
Content = new AbsoluteLayout
{
    InputTransparent = true,
    CascadeInputTransparent = false,
    Children =
    {
	    new BoxView
	    {
		    Color =Colors.Green,
	    }.LayoutFlags(Microsoft.Maui.Layouts.AbsoluteLayoutFlags.PositionProportional)
	    .LayoutBounds(0.5,0.7,100,100)
	    .TapGesture(t => t.Tapped += (s,e) =>
	    {
		    Debug.WriteLine("This should be clicked but doesn't");
	    }),
    }
},
```

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by hartez** [comment]
@danielftz Have you tried this with any child controls other than a BoxView?

**Comment by danielftz** [comment]
> @danielftz Have you tried this with any child controls other than a BoxView?
Yes I have and the issue persist.
