### ISSUE TITLE
Improve behavior for missing WebView2 Runtime on Blazor Hybrid Windows platforms

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/maui#6575]
### Summary
On WPF, Windows Forms, and MAUI (Windows), the `BlazorWebView` control requires that the WebView2 Runtime is installed on the host machine. While it is becoming increasingly rare for supported Windows versions to _not_ have the WebView2 Runtime installed, it would be nice to have a unified way for developers to detect and handle this case. Following is the current behavior in each supported Windows framework when the WebView2 Runtime is missing:
* MAUI: The `BlazorWebView` displays a label indicating that the WebView2 Runtime is missing along with a link to download it. This behavior is implemented in the `WebView2` WinUI control. Developers can use [this technique](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#detect-if-a-suitable-webview2-runtime-is-already-installed) to see if the WebView2 Runtime is missing if they want to add their own behavior to handle this case.
* WPF/Windows Forms: A `WebView2RuntimeNotFoundException` is thrown, which bubbles up to `Application.Run()`. It can either be caught there or handled using a global exception handler.

The MAUI behavior has the advantage that this scenario is handled gracefully out-of-the-box, but customizing that behavior is more involved than in the WPF/Windows Forms cases. Ideally, all platforms should have pleasant default behavior while providing a simple path to customization.

### Open questions
1. Since the WPF/Windows Forms `WebView2` controls do not display a WebView2 Runtime download link, is this behavior we want to implement in `BlazorWebView`? Or as a possible alternative, should we update the project templates to handle this case in a pleasant way?
2. How should we signal the case when the WebView2 Runtime is missing? Should we catch and re-throw the `WebView2RuntimeNotFoundException` in a more desirable location? Or, should we add some sort of event (maybe `BlazorWebViewInitializationFailed`?).

Related: #1579

### Public API Changes

N/A

### Intended Use-Case

I want my Blazor Hybrid app to provide a positive, customized user experience on Windows when the WebView2 Runtime is not installed.

**Comment by danroth27** [comment]
We should talk to the WebView2 folks about having the same download link for WPF and WinForms that they have for .NET MAUI and WinUI 3.

**Comment by TwitchPlaysBF2** [comment]
Maybe there is an alternative way to detect this within the app maybe? I.e. by checking installed applications or registry entries, from within the WinForms application runtime

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
