### ISSUE TITLE
Android application in Release requires permission whereas Debug does not

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6576]
### Description

Although internet connectivity check is used, resources on the internet cannot be accessed when in Release build on android.
Works fine with the exact same code built and run on Android Debug and Windows Release and Windows Debug configurations.

Example:
- for a DB call, SqlException class 20 is received which normally occurs in EF Core when internet connectivity is not available
- when using a HttpClient to download sample HTML from google.com it outputs:
`System.AggregateException System.Net.WebException One or more errors occurred. (Permission denied (missing INTERNET permission?))`

I cannot see output details because of `Android application is running (debug is disabled in android project properties).`

_**Are permissions bypassed on Android in Debug configuration?**_
P.S. What would, please, be the preferred and clean way to acquire permissions in RC 2 for MAUI in general and also for MAUI Blazor - e.g. access camera from BlazorWebView? Is there any general cross-platform way or do permissions really have to be declared in Android-specific classes and files in the project?

### Steps to Reproduce

- MAUI Blazor app run on Android in Release build configuration
- access the internet

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (API 30)

### Did you find any workaround?

no, I cannot install Debug build on clients' phones

**Comment by drasticactions** [comment]
Are you trying to access a database from your application directly? That seems... quite dangerous. 

Anyway, I feel this is not an MAUI-specific problem but potentially an issue with what you're trying to do on Android itself. Have you tried running your code to connect to this database on a Non-MAUI Android App?

**Comment by janseris** [comment]
@drasticactions I have not tried non-MAUI and will not because our team is just experimenting with MAUI (first time Android apps and first time C# Android apps) as we thought this might be the time.
The issue is not related to accessing the DB but overall accessing the internet. Permission is required for Release build on Android but not for Debug build.

**Comment by drasticactions** [comment]
Then that issue still seems like it's not MAUI specific. If you made a .NET 6 Android application (`dotnet new android`) and tried doing what you're doing, the same thing would probably happen.

@jonathanpeppers Does that sound correct?

**Comment by bautistavirchar** [comment]
add this to your AndroidManifest.xml

`<uses-permission android:name="android.permission.INTERNET" />`

**Comment by jamesmontemagno** [comment]
Yes, this is the same as with xamarin android and .net 6 android... debug auto adds this as it is needed for debugging, however IMHO i think we should add it to the templates. @jonathanpeppers @Redth thoughts here... i really think this is going to bite people

**Comment by jonathanpeppers** [comment]
The Xamarin templates don't have the `INTERNET` permission, but is there any modern app that *wouldn't* use the internet?

I could probably go add this to every Android template: `maui`, `maui-blazor`, and `android` would probably be it.
