### ISSUE TITLE
ANDROID: Problem with on release apk not working.

### ISSUE THREAD

**Issue by bautistavirchar** [dotnet/maui#6578]
### Description

without this in csproj
**```<RunAOTCompilation>false</RunAOTCompilation>```**

one of them is not working is

- SecureStorage - crashed
- HttpClient - crashed (.NET Threadpool logcat)

even though is in the try catch blocked not logs shows in logcat

But by using this
**```<RunAOTCompilation>false</RunAOTCompilation>```**

MVVM binding datas not show up.

### Steps to Reproduce

without this in csproj
**```<RunAOTCompilation>false</RunAOTCompilation>```**

one of them is not working is
SecureStorage - crashed
HttpClient - crashed (.NET Threadpool)

even though is in the try catch blocked not logs shows in logcat

But by using this
**```<RunAOTCompilation>false</RunAOTCompilation>```**

MVVM binding datas not show up.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by janseris** [comment]
try <PublishTrimmed>False</PublishTrimmed>
I have to use it in my MAUI Blazor project for Release on Android else it crashes on startup (does not happen for plain MAUI Blazor project from template)

**Comment by Redth** [comment]
@jonathanpeppers is this a duplicate of #4897  ?

**Comment by jonathanpeppers** [comment]
There isn't enough information here to know what is wrong. There are `HttpClient` fixes coming in the next release.

If the app is crashing can you enable more logging with:
```
adb shell setprop debug.mono.log default,timing,assembly,mono_log_level=debug,mono_log_mask=all
```

Then save the log with `adb logcat -d > log.txt`:

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows#accessing-from-the-command-line

**Comment by bautistavirchar** [comment]
yea I tried but yeah its working but the problem is the data displayed in the list does not show up properly.. seems the UI with one-way binding also.

**Comment by jonathanpeppers** [comment]
@bautistavirchar are you able to get the log? https://github.com/dotnet/maui/issues/6578#issuecomment-1116330830

I think we need that to look into what the problem is.
