### ISSUE TITLE
iOS/macOS Images not cropped inside of a Frame

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#6580]
### Description

<img width="622" alt="Screen Shot 2022-04-27 at 7 03 50 PM" src="https://user-images.githubusercontent.com/1676321/165661774-c119d92d-14e3-496a-8208-c9902676b5a6.png">

Take https://github.com/dotnet-presentations/dotnet-maui-workshop/tree/main/Finish and run on iOS or mac catalyst

```
                <Frame
                    Grid.RowSpan="2"
                    Grid.Column="1"
                    Margin="0,80,0,0"
                    HeightRequest="160"
                    WidthRequest="160"
                    HorizontalOptions="Center" 
                    Padding="0"
                    CornerRadius="80">
                    <Image
                        Aspect="AspectFill"
                        HeightRequest="160"
                        HorizontalOptions="Center"
                        VerticalOptions="Center"
                        Source="{Binding Monkey.Image}"
                        WidthRequest="160"/>
                </Frame>
```

This should crop like it does on Android/Windows. 

### Steps to Reproduce

See above^

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

All

### Did you find any workaround?

Have to set 

           IsClippedToBounds="True"

This should be consistent though between all platforms

**Comment by kristinx0211** [comment]
verified not repro on IOS.

**Comment by jamesmontemagno** [comment]
I just fixed this inside of the repo by adding the work around. You would have to remove the workaround that I put in @kristinx0211

**Comment by kristinx0211** [comment]
@jamesmontemagno thanks for the update. I can repro this issue on IOS.

**Comment by jamesmontemagno** [comment]
Thanks for verifying the repo @kristinx0211. Sorry for the confusion.

**Comment by Redth** [comment]
@jamesmontemagno what about using Border or some other control?  Frame and BoxView have some compat issues that seem to often be resolved by avoiding those controls.  @PureWeen is looking into those but for now I'd suggest avoiding them.

**Comment by jamesmontemagno** [comment]
Gotcha, yeah let me try to move to border and see what happens there. I believe this "bug" is the same experience as on XF.

**Comment by samhouts** [comment]
Still an issue on 6.0.400-preview.1.5782.

**Comment by tj-devel709** [comment]
Can confirm that this is still happening on 7.0.49

**Comment by tj-devel709** [comment]
Similar results with MacCatalyst and iOS

### With ClippingToBounds
![image](https://user-images.githubusercontent.com/50846373/199288465-65d6da7a-907d-45c2-b1fa-9dc388d26dc1.png)


### Without ClippingToBounds
![image](https://user-images.githubusercontent.com/50846373/199288263-898abdb0-7622-42df-8e29-0d7b18747976.png)
