### ISSUE TITLE
If Listview IsEnabled is false, items are still enabled

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#6581]
### Description

Items in a listview are still enabled even if the Listview (or the parent of the listview) is (should be?) disabled

### Steps to Reproduce

```XAML
<ListView IsEnabled="False"
	  ItemsSource="{Binding Source={x:Static local:MyCollection.Instance}, Path=CollectionTest.SubCollection}"
	  SelectionMode="None">
	<ListView.ItemTemplate>
		<DataTemplate>
			<ViewCell>
				<Grid>
					<Label Text="{Binding Name}" />
					<Switch IsToggled="{Binding Enabled}"/>
				</Grid>
			</ViewCell>
		</DataTemplate>
	</ListView.ItemTemplate>
</ListView>
```

In the upper code the `Switch` should be disabled but the user can still toggle the switch. But I've also tested it with `Entry` control and its the same.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (Pixel 5)

**Comment by VincentBu** [comment]
repro on Android emulator
[MauiApp6581.zip](https://github.com/dotnet/maui/files/8580414/MauiApp6581.zip)
