### ISSUE TITLE
Shell Title Changes Randomly (iOS/macOS) after navigation

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#6582]
### Description

When you navigate to a second page in Shell and navigate back the first page title takes on the title of the second page....

Screen 1:
<img width="711" alt="Screen Shot 2022-04-27 at 7 49 27 PM" src="https://user-images.githubusercontent.com/1676321/165666811-12834119-7f9d-49cf-9ef6-bb127b243cca.png">

Screen 2:
<img width="711" alt="Screen Shot 2022-04-27 at 7 50 15 PM" src="https://user-images.githubusercontent.com/1676321/165666873-c85cdaed-f02c-47ca-a77c-713b37ec7b14.png">

Back to Screen 1 (notice it says Baboon):

<img width="711" alt="Screen Shot 2022-04-27 at 7 50 20 PM" src="https://user-images.githubusercontent.com/1676321/165666879-6c77388b-2ce3-460d-a4a4-d762831be5b1.png">

### Steps to Reproduce

pull down https://github.com/dotnet-presentations/dotnet-maui-workshop and run Finished folder app on iOS/Mac and load data then navigate

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

all

### Did you find any workaround?

None

**Comment by v-longmin** [comment]
Verified repro on iOS 15.4. Repro with above project.

**Comment by VincentBu** [comment]
still repros on IOS with vs main build[32510.390.main]
it looks like the content of shell title (after navigation) depends on the first shell page we browse.

**Comment by PureWeen** [comment]
related https://github.com/dotnet/maui/issues/9687

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on iOS platform with sample project. [dotnet-maui-workshop](https://github.com/dotnet-presentations/dotnet-maui-workshop)
