### ISSUE TITLE
Loading image using ImageSource.FromFile not working on Android

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#6583]
### Description

A simple supplied reproduction demonstrates the issue.

On Android, when trying to load an image using the [ImageSource.FromFile] instruction, nothing displays.
When changing the load to an image in the Resource folder (Resizetizer generated), it displays fine. 
The exact same code, running on iOS, works fine for both source types.
Here is the display on iOS (image displays):

![image](https://user-images.githubusercontent.com/7484186/165670811-2d77dfa1-e247-4459-aa21-1e1057e27744.png)

Here is the display on Android (image does not display):

![image](https://user-images.githubusercontent.com/7484186/165670618-13415384-62df-443f-b989-f402c1cd9e84.png)

The app needs to do a few things first before displaying images from the file system. It extracts a zipped file (Embedded Resource) and save the files to the file system. One of these files then gets loaded for display.

### Steps to Reproduce

1. Open the reproduction from github [https://github.com/hbraasch/ImageSourceTester.git] in Visual Studio
2. Run the app for Android then iOS
3. Once running, click on the [Image1] and [Image2] toolbar items. This will display the two images. Image1 displays the image loaded using [ImageSource.FromFile], Image2 displays the image loaded from the Resource folder.
4. Notice that Image1 only displays on iOS.

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 - API 31 (Only one tested)

**Comment by Symbai** [comment]
Looks like a dup of #6525

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android with above project.

**Comment by hbraasch** [comment]
Yes, it does look similar.

**Comment by hbraasch** [comment]
This unfortunately is a major setback, I cannot carry on converting my Xamarin Forms app to Maui because its an offline app, very image intensive , depending on its data to be extracted from a large zip file during first run.
I really hope this will be addressed soon.
Thanks

**Comment by WebGoose** [comment]
Yes, as @mkdave said, we're having the same issue with FromStream. No image displays since the release of RC1. It seemed to work fine before.

**Comment by Redth** [comment]
This is fixed in the upcoming RC3 release.
