### ISSUE TITLE
[Android] The ItemTapped event of ListView has no response for a while after Shell's tab changed

### ISSUE THREAD

**Issue by miao17game** [dotnet/maui#6584]
### Description

The ItemTapped event of ListView has no response for a while after Shell's tab changed, found on Android platform with MAUI rc.2, but work well at rc.1

https://user-images.githubusercontent.com/17511048/165676535-587ca19b-a119-46ce-94be-0f99499d068a.mp4

### Steps to Reproduce

1. Create a now repo with MAUI template in VisualStudio 2022 Preview 5 and maui rc2
2. Add two tabs and two pages in shell page
3. Add ListView with datatemplate in page 1, SelectionMode is false
4. Run the app with debug mode in android emulator, Android version is 12 or 11
5. View the page 1, click the item of ListView,it works well
7. Click the tab of page 2, navigation completed well
8. Click the tab of page 1, navigation completed well
9. Try click the item of ListView, and you will find that this action does not generate any feedback, no android click animation
10. After about a few seconds or tens of seconds, the click action suddenly recovered. The ListView will back to normal after refresh action completed as well.

or view my repo file [on this branch](https://github.com/miao17game/BigmogicianDriveControl/blob/debug/listview-tapped/BigmogicianDriveControl/Controls/WebDavFolderView.xaml)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

Android

### Affected platform versions

Android 12, 11, maybe lower

### Did you find any workaround?

Use CollectionView.

### Relevant log output

```shell
No useful message found.
```

**Comment by VincentBu** [comment]
Repro on Android emulator with vs main build[32510.390.main]. However, if we replace `ListView` with `CollectionView`, it works fine.

**Comment by samhouts** [comment]
I'll bet this is related to #4809
