### ISSUE TITLE
IServiceCollection Not Being Initialized Using builder.Services.AddTransient<SomeCLRClass>()

### ISSUE THREAD

**Issue by AnthonySlay** [dotnet/maui#6587]
### Description

Somehow I think it just me since I can't find an existing bug report for this.

In MauiProgram.cs, the `builder.Services.AddTransient<SomeCLRClass>()` is supposed to return a `IServiceCollection` object but it returns null.

As a result, no dependency injection is working in any part of the application.  Any call using `Ioc.Default.GetService<SomeCLRClass>();` will throw the error "The service provider has not been configured yet."

### Steps to Reproduce

1. On a Mac, create a new maui app using the command `dotnet new maui`
2. Open the project using Visual Studio 2022 Preview for Mac
3. Open and edit the MauiProgram.cs file.
4. On the line just above `return builder.Build();` add the line `var service = builder.Services.AddTransient<SomeCLRClass>();`
5. Allow the quick refactoring to create a `SomeCLRClass` for you.
6. Set a breakpoint on that same line .
7. Debug the app and observe that the service variable remains null after builder.Services.AddTransient (or AddSingleton) is called. 🐞

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

IOS all versions, Android all versions, MacCatalyst all versions

### Did you find any workaround?

I haven't found a workaround yet (developing on a mac using maui has been rough going but the monthly updates of maui and VS 2022 preview have been very encouraging).  I was only able to just start trying to develop using maui on a Mac using VS 2022 preview 9 for Mac and Maui RC1.  I did not test dependency injection before moving to VS 2022 for Mac RC.

**Comment by jfversluis** [comment]
Hm it does seem kind of weird like you say: if this is really broken we would've heard much more about it probably. Are you by any chance able to test this on Visual Studio for Windows? It seems like a bit of a stretch, but that seems the main difference here with the majority of other people at this time I guess.

Also it might help if you add the project that you're testing with, even though it just seems to be a File > New Project. Maybe we can spot something funny in there. Thanks!

**Comment by AnthonySlay** [comment]
Hi @jfversluis,
Thanks for you reply.  This really wasn't a problem.  I needed to used the code below to configure the Ioc container in MauiProgram.cs file.

```
var mauiApp = builder.Build();
Ioc.Default.ConfigureServices(mauiApp.Services);
```
I thought the CommunityToolkit.Mvvm Ioc container would automatically register the same classes the builder.Services was registered with.  Apparently not!  It's all good now.

**Comment by jfversluis** [comment]
Perfect! Thanks for letting us know!
