### ISSUE TITLE
[RC2] Android - The Navigation.PushModalAsync view cannot be full screen when the NavigationBar and StatusBar was hidden.

### ISSUE THREAD

**Issue by danch15** [dotnet/maui#6589]
### Description

I just updated the RC1 version a few days ago. Today, I updated the RC2 version. I found that there was a problem with the method. When I called the pushmodalasync method, the pop-up page was not full screen. My Android application is carried out in a full screen way. There was no such problem before the RC2 version, but this problem suddenly appeared in the RC2 version, which made me speechless.

You can see the demo here: 
**https://github.com/danch15/MauiToolbarAlignmentFullScreenTester.git**

(See in the "samsung_n9100" folder, and you can find the code to hidden the navigation bar in here: Platforms\Android\MainActivity.cs
protected override void OnCreate(Bundle savedInstanceState) ...
I use this code to hidden the bar starting with maui preview 7 to rc1, all works

### Steps to Reproduce

See https://github.com/danch15/MauiToolbarAlignmentFullScreenTester.git

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

Android

### Affected platform versions

Samsung NOTE9 Android 10.0 - API 29 and Android 7.1.2 Tablet API 25

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32414.199.main]. Repro project:
[MauiToolbarAlignmentFullScreenTester-main.zip](https://github.com/dotnet/maui/files/8580493/MauiToolbarAlignmentFullScreenTester-main.zip)

**Comment by kristinx0211** [comment]
still an issue on android with 17.3.0 Preview 2.0 [32507.29.main].

**Comment by kristinx0211** [comment]
@PureWeen repro on android 12 with vs 17.3.0 Preview 2.0 [32525.541.main]. the pop-up page was not full screen.

**Comment by PureWeen** [comment]
@kristinx0211 can you attach a screen shot? Modals aren't always supposed to be full screen so just want to make sure our expectations are aligned

**Comment by kristinx0211** [comment]
@PureWeen 
pop-up page screen shot:
![image](https://user-images.githubusercontent.com/99457000/170449806-ff48385f-7e11-40ea-b899-12c5fc93015a.png)

**Comment by kristinx0211** [comment]
hi @PureWeen I attach the repro video that you can see the full process. 
https://user-images.githubusercontent.com/99457000/170454229-1d40a5d9-a6f0-477b-b8a7-0392387c348e.mp4
pop-up page screen shot:
![image](https://user-images.githubusercontent.com/99457000/170455058-a0e005e5-2df6-4734-9a8f-d5e928d15561.png)


.

**Comment by PureWeen** [comment]
@kristinx0211 why are you thinking that's not full screen?

The modal page is a Navigation page

```C#
var nextPage = new NavigationPage(new NextPage()) { BarBackgroundColor = Colors.OrangeRed, BarTextColor = Colors.LightSkyBlue }; 
```

So it's going to have that OrangeRed NavBar at the top and then the rest of the page which has a BGColor set to LimeGreen

**Comment by kristinx0211** [comment]
@PureWeen ah, I might have confused Modal Page with HTML. I thought the page would cover the navigation bar or the toolbar.

**Comment by PureWeen** [comment]
@kristinx0211 yea it covers the navbar with a second navbar :-) The modalpage itself also has a navbar so that's what that top bar is

**Comment by danch15** [comment]
I checked it in MAUI 1.0 GA, now it's no problem.
