### ISSUE TITLE
views overlap on image in Grid and Vertical StackLayout

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#6590]
### Description

The views overlap on image when the image have `Aspect="AspectFill`.

### Steps to Reproduce

Run the repro and comment and uncomment both VerticalStackLayout and Grid in turns. In both layouts the label is overlapping on the image.
[ImageBug.zip](https://github.com/dotnet/maui/files/8580642/ImageBug.zip)
 

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

**Comment by HobDev** [comment]
This is same as #5165. The pull request #5589 didn't resolve it. The issue is both on Android and iOS.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android with above project.

**Comment by hartez** [comment]
Ah, my mistake. 5589 only addressed Android, not iOS.
