### ISSUE TITLE
[Android] When adding child in ScrollView, the vertical layout options of the child (of child) is not working

### ISSUE THREAD

**Issue by Deepak1799** [dotnet/maui#6599]
### Description

When adding child in ScrollView, the vertical layout options of the child (of child) is not working.

### Steps to Reproduce

1. Create File -> New MaUI app.
2. Add a scroll view to the Main Page.
3. Add a Grid as the child of the scroll view.
4. Add an Image as the child of Grid.

**Code snippet:** [Complete MainPage.xaml]

```
    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 x:Class="ZoomableView.MainPage">
        <ScrollView BackgroundColor="Green">
            <Grid BackgroundColor="Red">
                <Image
                    Source="dotnet_bot.png"
                    SemanticProperties.Description="Cute dot net bot waving hi to you!"
                    WidthRequest="250"
                    HeightRequest="310"
                    HorizontalOptions="Center" 
                VerticalOptions="Center"
            BackgroundColor="Yellow"/>
            </Grid>
        </ScrollView>
    </ContentPage>
```
Where you can see the Vertical options of the Image is "Center". However if you run the sample, the image will be aligned vertically at the "top" of the Grid. 

**Screenshot**
![Image with ScrollView_resized](https://user-images.githubusercontent.com/65169077/165723681-01f26c22-053a-4bd3-9f8d-5d732f8600c8.jpg)

Note: For showing difference, I have used background colors for the controls.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9.0

### Did you find any workaround?

NOTE: The below information is not a workaround. But may be useful for the analysis.

**This issue occurs due to the Foremost parent is a Scroll View**. If we removed the Scroll View and just placing a grid, the vertical option was proper. Please try the below code snippet.

Code: [Complete MainPage.Xaml]

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ZoomableView.MainPage">
    <Grid BackgroundColor="Red">
        <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                WidthRequest="250"
                HeightRequest="310"
                HorizontalOptions="Center" 

        BackgroundColor="Yellow"/>
    </Grid>
</ContentPage>
```

**Screenshot**
![Image without ScrollView_resized](https://user-images.githubusercontent.com/65169077/165723781-4a888311-b510-4484-9978-4f4d5bc4f3b3.jpg)

### Relevant log output

```shell
NA
```

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android. Sample Project: [MauiApp5.zip](https://github.com/dotnet/maui/files/8581586/MauiApp5.zip)

**Comment by kristinx0211** [comment]
still an issue on android with 17.3.0 Preview 2.0 [32507.29.main].
