### ISSUE TITLE
Changing BaseSize attribute of MauiSplashScreen element within a project does not get picked up

### ISSUE THREAD

**Issue by kphillpotts** [dotnet/maui#6600]
### Description

Changing the `BaseSize` attribute of `MauiSplashScreen` element in the project file does not update the size of the image on the splash screen with the next run. 

NOTE: If you do a clean the solution or nuke the `bin` or `obj` files it does pick this up.

### Steps to Reproduce

1. Create new MAUI project
2. Run the project
3. In the project change this BaseSize value, for example:
```
		<MauiSplashScreen Include="Resources\appiconfg.svg" Color="#512BD4" BaseSize="128,128" />
```
to 
```
		<MauiSplashScreen Include="Resources\appiconfg.svg" Color="#512BD4" BaseSize="256,256" />
```
4. Run the project again
5. Image on splash screen stays same size

Workaround:
1. Clean Project -or- Delete obj dir
2. Run Project -- will now show new size

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android (tested on 11) but I suspect all versions

### Did you find any workaround?

Workaround:
1. Clean Project -or- Delete obj dir
2. Run Project -- will now show new size

### Relevant log output

```shell
Target ProcessMauiSplashScreens:
1>      Skipping target "ProcessMauiSplashScreens" because all output files are up-to-date with respect to the input files.
1>      Input files: 
1>          Resources\appiconfg.svg
1>          C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.300-rc.2.5513\targets\Microsoft.Maui.Resizetizer.targets
1>          C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.300-rc.2.5513\targets\\Microsoft.Maui.Resizetizer.dll
1>          obj\Debug\net6.0-android\mauisplash.inputs
1>      Output files: obj\Debug\net6.0-android\mauisplash.stamp
```

**Comment by kphillpotts** [comment]
Seems to pick up changes fine for the `Color` attribute if that helps.

**Comment by mattleibow** [comment]
This was fixed in https://github.com/dotnet/maui/pull/8020/files#diff-2c7ae7efc1ef8b77ae7f105b49a14a0716701cb9550370e5a012d58967c4bd9aR309
