### ISSUE TITLE
Run  Worker service from MAUI throw exception

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#6604]
### Description

Access is denied, service not run

### Steps to Reproduce

1. Create Maui app.
2. Create  worker service.
3.  Add button to run the service use this code:
4`ServiceController service = new ServiceController("AutoamtionService.WorkerService");
            service.Start();
            service.WaitForStatus(ServiceControllerStatus.Running);`
5.Acceess is denied.
![image](https://user-images.githubusercontent.com/1079689/165746778-77050144-664c-42a2-8a05-1704f45efcd7.png)

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

..

### Did you find any workaround?

No

### Relevant log output

```shell
See above
```

**Comment by janseris** [comment]
> "AutoamtionService.WorkerService"

"Auto_**ma**_tionService.WorkerService"?

**Comment by danies8** [comment]
Yes, it not working.
I will supply sample code on Sunday morning.
It work from using same code.

**Comment by MagicAndre1981** [comment]
[WindowsApp SDK will only support elevated apps since Version 1.1](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/37-elevated-admin-support), [Maui uses 1.0.x](https://github.com/dotnet/maui/blob/3aab9c553f674fa5e14d4f19ddf5265db48815f6/eng/Versions.props#L23), so you can't run the Windows app as admin to start/stop services.

**Comment by danies8** [comment]
1. I added sample code.
2. Publish service as single file application.
3. Install service WorkerService3 using "sc create command".
4. Run the maui app and press on start button,
5. You will get this results
![image](https://user-images.githubusercontent.com/1079689/166135321-1148c453-e5dc-4c60-9d0f-e8c9e6dd397b.png)
6. Added sample code
[RunWorkerSeviceApp.zip](https://github.com/dotnet/maui/files/8598416/RunWorkerSeviceApp.zip)
 7. How can be solved? and there is another class that is class platform  instead of ServiceController ?

**Comment by MagicAndre1981** [comment]
> 7. How can be solved? and there is another class that is class platform  instead of ServiceController ?

read my comment above, it is currently **not possible** to run WinUI apps (the Windows app of your MAUI project) **as admin** which is required to start/stop services), until WindowsApp SDK supports it in Version 1.1.

**Comment by danies8** [comment]
When WindowsApp SDK will supports it in Version 1.1?

**Comment by MagicAndre1981** [comment]
[WindowsApp SDK 1.1 will be released later this year](https://github.com/microsoft/WindowsAppSDK#roadmap). MAUI may use it for .net 7 release.

**Comment by danies8** [comment]
Thanks,
1.I used worker service that is should be cross platform ? Is it
2. If yes how I will run it in in macOS and Linux(start/stop the service) ?

**Comment by MagicAndre1981** [comment]
[System.ServiceProcess.ServiceController is Windows only](https://apisof.net/catalog/92ca053e-c68f-f9fa-c50b-ff7a178b94ed?fx=net6.0). 

![image](https://user-images.githubusercontent.com/8274816/166200448-0d695336-cc24-4635-972f-f03063f58c02.png)

And you need the elevation support which comes later this year.

I have no idea how to start/stop demons in *nix systems.

**Comment by danies8** [comment]
Thanks [MagicAndre1981](https://github.com/MagicAndre1981) :)

**Comment by Eilon** [comment]
@danies8 - do you think there is still an issue remaining here? Or is this resolved for you?

**Comment by danies8** [comment]
I will be happy if you support all others platforms:
Linux, && Mac(Catalyst)

**Comment by Eilon** [comment]
For feature requests regarding ServiceController and related types, please go to https://github.com/dotnet/runtime and see if there is an existing issue to upvote, or you can log a new issue with details. Thanks!
