### ISSUE TITLE
RadioButton with an inline content definition doesn't display it properly on Android

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#6614]
### Description

Defined a RadioButton with an inline content definition.

Instead of displaying the Content, this shows the type name.

Refer to the screenshot for more details.

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Add a new Content Page and the below code snippet to simulate the issue
3. Set this newly added page as the Main page
4. Set Android as the target platform, build and then run the project
5. And it works fine in Windows without any issue and unable to check on the other platforms

```xaml
<?xml version="1.0" encoding="UTF-8" ?>
<ContentPage
    x:Class="Issue6614.TestPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:m="clr-namespace:Microsoft.Maui;assembly=Microsoft.Maui"
    Title="TestPage">
    <ContentPage.Resources>
        <ResourceDictionary>
            <m:Thickness x:Key="OptionPadding">3,0,0,0</m:Thickness>
        </ResourceDictionary>
    </ContentPage.Resources>
    <StackLayout
        HorizontalOptions="Center"
        RadioButtonGroup.GroupName="AppTheme"
        VerticalOptions="Center">
        <RadioButton IsChecked="{Binding UseSystem}" Value="system">
            <RadioButton.Content>
                <Label Padding="{StaticResource OptionPadding}" Text="Use System" />
            </RadioButton.Content>
        </RadioButton>
        <RadioButton IsChecked="{Binding LightTheme}" Value="light">
            <RadioButton.Content>
                <Label Padding="{StaticResource OptionPadding}" Text="Light" />
            </RadioButton.Content>
        </RadioButton>
        <RadioButton IsChecked="{Binding DarkTheme}" Value="dark">
            <RadioButton.Content>
                <Label Padding="{StaticResource OptionPadding}" Text="Dark" />
            </RadioButton.Content>
        </RadioButton>
    </StackLayout>
</ContentPage>
```

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 31.0

### Did you find any workaround?

Have to set the value to the Content directly instead of using the extended Content definition.

### Relevant log output

```shell
NA
```

**Comment by egvijayanand** [comment]
Attached is the project to simulate the issue.

[Issue6614.zip](https://github.com/dotnet/maui/files/8583501/Issue6614.zip)

Windows Screenshot:

<img width="264" alt="dotnetmaui-issue6614-windows-output" src="https://user-images.githubusercontent.com/81947404/165772425-8784e20b-eeb1-4a19-bad6-e8ec11aab81d.png">

Android Screenshot:

<img width="421" alt="dotnetmaui-issue6614-android-screenshot" src="https://user-images.githubusercontent.com/81947404/165773379-eed715f6-288b-49ca-a7d9-350a0a124994.png">

**Comment by jfversluis** [comment]
I'm wondering if this is the cause: https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/RadioButton.cs#L563

Do you see anything like that in the logging @egvijayanand?

Not adding the needs-info tag as it seems an obvious bug we can work on. Just trying to get more information without actually debugging it (yet)

**Comment by egvijayanand** [comment]
@jfversluis Here's the Debug log.

Hope it helps. Since I don't see any phrase that is mentioned in the link shared. Let me know if it's getting logged somewhere else.

[Debug-Log.txt](https://github.com/dotnet/maui/files/8584139/Debug-Log.txt)

**Comment by Core121** [comment]
Any update on this? I'm also having this issue.

**Comment by jsuarezruiz** [comment]
> I'm wondering if this is the cause: https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/RadioButton.cs#L563
> 
> Do you see anything like that in the logging @egvijayanand?
> 
> Not adding the needs-info tag as it seems an obvious bug we can work on. Just trying to get more information without actually debugging it (yet)

Right.

```
[DOTNET] [40m[1m[33mwarn[39m[22m[49m: Microsoft.Maui.Controls.RadioButton[0]
[DOTNET]       Warning - Android does not support View as the Content property of RadioButton; the return value of the ToString() method will be displayed instead.
[DOTNET] [40m[1m[33mwarn[39m[22m[49m: Microsoft.Maui.Controls.RadioButton[0]
[DOTNET]       Warning - Android does not support View as the Content property of RadioButton; the return value of the ToString() method will be displayed instead.
[DOTNET] [40m[1m[33mwarn[39m[22m[49m: Microsoft.Maui.Controls.RadioButton[0]
[DOTNET]       Warning - Android does not support View as the Content property of RadioButton; the return value of the ToString() method will be displayed instead.
[DOTNET] OnCreated
```

**Comment by egvijayanand** [comment]
> Do you see anything like that in the logging @egvijayanand?

Will check and update.

**Comment by hartez** [comment]
This is the expected behavior for a RadioButton on Android; the Android platform doesn't support arbitrary in-line content: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton?view=net-maui-7.0#display-arbitrary-content

To display arbitrary content on Android, you'll need to set a ControlTemplate for the RadioButton: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton?view=net-maui-7.0#redefine-radiobutton-appearance
