### ISSUE TITLE
Layout position not updated correctly while dynamically updated in windows platform

### ISSUE THREAD

**Issue by Sasikumar3595** [dotnet/maui#6618]
### Description

We are creating an application with a custom layout and pan gesture. Pan gesture is used to update the layout position based on pan position. but the layout is not updated while updated with the latest position.

**Sample:** 
[MauiApp1 2.zip](https://github.com/dotnet/maui/files/8584171/MauiApp1.2.zip)
 

### Steps to Reproduce

1. Run the below-attached sample 
2. Swipe the layout but the layout was not updated with the latest pan position

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Preview 14

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

No

### Relevant log output

```shell
Not Applicable
```

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Windows with above project.

**Comment by Redth** [comment]
I believe this is working correctly now on maui's main branch.  It's not clear to me exactly the expected behavior, but I'm able to click and drag (pan) and see views moving...

Can you make a more concise sample if you're still having problems once RC3 is released and open a new issue please?
