### ISSUE TITLE
[IOS] Building and debugging related issues

### ISSUE THREAD

**Issue by danielftz** [dotnet/maui#6624]
### Description

I've been trying to build an app for on an IOS 15 physical device. And I have encountered the following problems: 

- After I make any changes to the code, project has to be  Rebuilt, and then Run. If Run directly, changes made in the code will not be applied to the app. 
- When execution hits any breakpoints, I get "The application is in break mode; Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code)." message, and I am unable to step through as normal. 

### Steps to Reproduce

Create a new app, set up breakpoint then build

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by Redth** [comment]
Is this VSMac? VSWindows? what version of everything?

**Comment by danielftz** [comment]
> Is this VSMac? VSWindows? what version of everything?

I am using VSWindows using all the latest version of VS, Maui and iOS, and debugging with a physical iOS device (Hot Restart)

**Comment by PureWeen** [comment]
This issue should be fixed with the latest VS preview. There is a bug with the remote simulator where it fails to debug after the first launch which won't be fixed until P4
