### ISSUE TITLE
VisualStateManager Works Differently on Windows and Android

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#6629]
### Description

I use a VisualStateManager to highlight selected items in a CollectionView. Prior to RC2 it did not work at all on Android so I reported issue #5449. That was fixed so now it works on Android, but differently than Windows. 

### Steps to Reproduce

1. Unzip the project from
[MAUIListEntry-VisualState-RC2.zip](https://github.com/dotnet/maui/files/8585454/MAUIListEntry-VisualState-RC2.zip)
2. Compile and run it on Windows, click each item line in succession, you should see this (the correct behaviour):
![MAUIListEntry-VisualState-RC2-Windows](https://user-images.githubusercontent.com/12423046/165822702-91ecf69a-0c44-44b4-a89f-beffa1056aab.gif)
3. Compile and run it on Android, again click the three item lines in succession, you should see this:
![MAUIListEntry-VisualState-RC2-Android](https://user-images.githubusercontent.com/12423046/165823028-1347feac-2fdb-4f09-90b1-3fc3c858572e.gif)
 

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Yes, as part of the fix for Issue #5449 @antonfirsov wrote "...note that you have to define a default BackgroundColor for your grid, otherwise VisualStateManager won't be able to determine what color to switch back to after deselection" this is evidently only true for Android and can be painful to do in existing code. So if you can come up with a color to use this is a workaround on Android (it's evidently not required on Windows).

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android 12, not repro on Windows with above project.

**Comment by Redth** [comment]
@PureWeen ^

I think for now the expectation is an opinionated 'default' value.

**Comment by david-maw** [comment]
Not my preferred fix but I can certainly live with it since I probably have less than a dozen instances to fix. Should I raise some sort of documentation issue to ensure it gets documented as a Xamarin migration note?

**Comment by david-maw** [comment]
@PureWeen, incidentally, I found the easiest migration in the "background for highlight" case is just to use "transparent" for non-highlighted items since I normally use plain backgrounds anyway.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 4.0. This issue does not repro with below Project: [6629.zip](https://github.com/dotnet/maui/files/11319792/6629.zip)

Windows and Android have the same behavior when clicking on each item line.

**Android emulator (13.0-API 33):**
![SelectItem](https://user-images.githubusercontent.com/97647558/234203630-6c5448f8-f905-4248-8d50-6efd32bf32e3.gif)

**Windows 11:**
![SelectItem1](https://user-images.githubusercontent.com/97647558/234203644-d589ec5d-43e7-409c-a262-0eef8317e6d5.gif)
