### ISSUE TITLE
Tried to get a simple expander view to work. Works fine on Android but not on Windows

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#6632]
### Description

Created the app using RC 2. The app works great on Android. When I try Windows version, I dont see the drop down list. I have not tried the app on iOS.

### Steps to Reproduce

Run the uploaded GitHub app on windows.  I started with : https://github.com/arvindvishwkarma/ExpanderViewInXamarinForms

Here is the path for my uploaded Maui version : https://github.com/davefxy/CustomExpanderView

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
using above project. verified repro on windows, works on android.

**Comment by Redth** [comment]
Can you try replacing Frame and BoxView with Border controls instead?

**Comment by davefxy** [comment]
Replaced the Frame and BoxView with Border controls. On Windows, the expanded view now appears with blank items. However I need to determine why each item contents are not displayed on Windows.  Still works fine on the Android. Sent from Mail for Windows From: Jonathan DickSent: Tuesday, May 3, 2022 7:29 AMTo: dotnet/mauiCc: Davefxy; AuthorSubject: Re: [dotnet/maui] Tried to get a simple expander view to work. Works fine on Android but not on Windows (Issue #6632) Can you try replacing Frame and BoxView with Border controls instead?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by davefxy** [comment]
Replaced the Frame and BoxView with Border controls. On Windows, the expanded view now appears with blank items. However I need to determine why each item contents (ContentView) are not displayed on Windows.  Still works fine on the Android. Sent from Mail for Windows From: Jonathan DickSent: Tuesday, May 3, 2022 7:29 AMTo: dotnet/mauiCc: Davefxy; AuthorSubject: Re: [dotnet/maui] Tried to get a simple expander view to work. Works fine on Android but not on Windows (Issue #6632) Can you try replacing Frame and BoxView with Border controls instead?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by davefxy** [comment]
Replaced the Frame and BoxView with Border controls. On Windows, the expanded view now appears with blank items. However I need to determine why each item contents (ContentView) are not displayed on Windows.  Still works fine on the Android.
Appears I need to be a bit more sophisticated to get this to work with windows. Thanks
