### ISSUE TITLE
CollectionView on iOS won't respect SelectionMode

### ISSUE THREAD

**Issue by emorell96** [dotnet/maui#6635]
### Description

Setting SelectionMode = 'None' will not disable selection on the collection view.

![image](https://user-images.githubusercontent.com/20151415/165840507-320ee2ca-3466-4cf0-93bc-aead7fcfd9d2.png)

Reproduction repo: https://github.com/emorell96/CollectionViewBug

### Steps to Reproduce

1. Create a MAUI app.
2. Add a collectionview
3. Set SelectionMode to none 
4. The collectionview items can still be selected

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 15

### Did you find any workaround?

None

**Comment by kristinx0211** [comment]
verified SelectionMode on CollectionView does not work on IOS. works on android.

**Comment by Redth** [comment]
While not ideal, perhaps the workaround for now is to clear the selection when the selection happens.
