### ISSUE TITLE
DisplayActionSheet Inside a Shell Does Not Work on Windows

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#6639]
### Description

Calling DisplayActionSheet from a ContentPage contained in a Shell does not display anything on Windows; it seems to work fine on Android. It also seems to work fine if no Shell is used.

The symptom seems like the same one as #3726 but that was resolved by #5047 and that looks like it was released in early March so I'd assume it was in the RC2 I tested.

### Steps to Reproduce

1. Unzip the project from 
[MauiShell-actionsheet.zip](https://github.com/dotnet/maui/files/8587180/MauiShell-actionsheet.zip)
2. Compile and run on Android, then click anywhere on the page, you should see this:
![MauiShell-actionsheet-android](https://user-images.githubusercontent.com/12423046/165862020-048ee898-b528-48c9-8a32-198b3d4bd08d.gif)
3. Repeat on Windows, this time clicking the button does nothing.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Windows with above project.

**Comment by Redth** [comment]
Working on maui main:
![image](https://user-images.githubusercontent.com/271950/166464528-d89d96d2-dcb3-4247-9ec5-f6e33ddce62e.png)
