### ISSUE TITLE
MAUI clearing storage of app

### ISSUE THREAD

**Issue by jayveedee** [dotnet/maui#6641]
### Description

After clearing the storage of the app (from within the phone's Android settings) and opening the app, the app instantly crashes before moving past the splash screen.

When trying to run the debugger after clearing the storage, Visual Studio freezes and is unable to completely start the debugger. Happens with Emulator as well as debugging wirelessly to my personal phone.

Haven't tested with IOS as I'm not so familiar with that OS and do not have a IPhone.

### Steps to Reproduce

1. Create a fresh MAUI project
2. Start the fresh application on a emulator or local Android device
3. Open it, verify that it works
4. Go out, navigate to the phone's app settings and clear the storage of the app
5. Open the app again, verify that it crashes instantly

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11, Android 12

### Did you find any workaround?

None so far

### Relevant log output

```shell
This is all the log that appears before it crashes with minimal output:

Forwarding debugger port 8866
Detecting existing process
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.fresh_maui_project/crc64d29721613a91a4e2.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.fresh_maui_project/crc64d29721613a91a4e2.MainActivity }
```

**Comment by shimingsg** [comment]
verified repro on Android 11 and Android 12 Emulator

**Comment by jfversluis** [comment]
This has been reported before. This only happens for debug builds, probably because we store some extra info we need in there for debugging. This has also been the case for Xamarin apps. Don't clear it while developing, running a release build does not have this problem.
