### ISSUE TITLE
Maui build system ignores VS BuildAction=None and builds anyway

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#6642]
### Description

In the attached repro, the build fails on test.cs even though in VS I set "BuildAction=None".  It seems the MAUI build targets don't deal with this properly.

### Steps to Reproduce

1. download repro sample and try to build.
2. build fails on test.cs even though that file should be excluded from the build.
3. using VS file properties and setting BuildAction=None for other files also will have no effect and include the file in the build.

[layoutbug5.zip](https://github.com/dotnet/maui/files/8587881/layoutbug5.zip)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

delete the file.  not really w workaround.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android 12 with above project.
![image](https://user-images.githubusercontent.com/97647558/165881672-0a3f27df-20ab-47d6-b607-2b4d55a8f87c.png)

**Comment by Eilon** [comment]
Presumably some issue with globs looking for all `*.cs` even though they are the wrong MSBuild item type?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 4.0. This issue does not repro on Windows 11 and Android emulator (13.0-API 33) with below Project: [6642.zip](https://github.com/dotnet/maui/files/11320039/6642.zip)
