### ISSUE TITLE
How to change CornerRadius dynamically?

### ISSUE THREAD

**Issue by VincentBu** [dotnet/maui#6646]
### Description

In `CornerRadius` class, `TopLeft`, `TopRight`, `BottomLeft` and `BottomRight` are read only.  What should I do if I want to set `CornerRadius` during the runtime? 
Does it make sense to create a `CornerRadius` instance once there is update on `TopLeft`, `TopRight`, `BottomLeft` or `BottomRight`?

### Steps to Reproduce

Run `DataBindingTest` on Windows.
[DataBindingTest.zip](https://github.com/dotnet/maui/files/8588449/DataBindingTest.zip)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 19041

### Did you find any workaround?

no

### Relevant log output

```shell
no
```

**Comment by v-longmin** [comment]
Verified repro on Windows with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[DataBindingTest.zip](https://github.com/dotnet/maui/files/8630154/DataBindingTest.zip)

**Comment by StephaneDelcroix** [comment]
CornerRadius is a struct, and is immutable as it should. Don't try to modify it's properties, but replace the entire cornerRadius by the new one. and you still can DataBind to it
