### ISSUE TITLE
Navigation bar vanishes when recreating Shell on Windows

### ISSUE THREAD

**Issue by Naryorill** [dotnet/maui#6652]
### Description

When you "restart" the app by creating a new Shell object and set it to the Main page the navigation bar vanishes on Windows. If you have a flyout menu, the content even starts on the same height as the hamburger icon.

Btw: I do this to restart the app after a culture change, I want the user to have the option to select a language other than the device language and without doing this the UI doesn't change to the new culture

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Replace the implementation of `OnCounterClicked ` with `App.Current.MainPage = new AppShell();`
3. Start the app on Windows and click the button

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041

**Comment by kristinx0211** [comment]
can be reproduced on windows, click the button, navigation bar vanishes when recreating Shell on Windows. repro project:
[MauiApp2.zip](https://github.com/dotnet/maui/files/8589791/MauiApp2.zip)

**Comment by davidortinau** [comment]
Should resetting MainPage be necessary when changing culture? That seems like a workaround to the root problem of the app needing to updating content.

**Comment by MissedSte4k** [comment]
Android seems to be also affected by the same problem
