### ISSUE TITLE
 [Windows] No Tabs 

### ISSUE THREAD

**Issue by xxjnaxx** [dotnet/maui#6654]
### Description

Tabs are not displayed with windows

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a Flyoutitem with Tabs like so:

<FlyoutItem Title="Favoriten" FlyoutDisplayOptions="AsSingleItem">
        <Tab >
            <ShellContent Title="Test1"   ContentTemplate="{DataTemplate local:MainPage}" Route="main1"  />
            <ShellContent Title="Test2" ContentTemplate="{DataTemplate local:MainPage}" Route="main2"  />
        </Tab>
</FlyoutItem>

3. Debug 

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by PureWeen** [comment]
Should be fixed by https://github.com/dotnet/maui/pull/6564
