### ISSUE TITLE
ContentView does not respect IsClippedToBounds (does not clip children)

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#6656]
### Description

As shown in the repro sample, the translated pink box is not clipped by the ContentView.

### Steps to Reproduce

1. Build the repro sample and run under Android 11
2. The ContentView left edge is bown and the pink content should be clipped by it, but it extends to the left of the ContentView.

Replacing the ContentView with something like Grid causes things to work normally.

[layoutbug7.zip](https://github.com/dotnet/maui/files/8590005/layoutbug7.zip)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

not for ContentView

**Comment by Redth** [comment]
Using a `Border` instead of `BoxView` fixes this.

This is an incompatibility with the old BoxView control which is deprecated.  Please use Border instead.

![image](https://user-images.githubusercontent.com/271950/166289624-3984cc09-6622-49ae-8726-260b472290c3.png)

**Comment by philipag** [comment]
I'm afraid this has nothing to do with BoxView and needs to be reopened.  If I replace BoxView with Grid as follows then the problem persists:

`		<ContentView Background="#330000ff" IsClippedToBounds="True">
		<Grid>
			<Grid Background="#66ff0000" TranslationX="-50"/>
		</Grid>
	</ContentView>`

![image](https://user-images.githubusercontent.com/6193288/166401195-d21fdcb1-d804-49f7-8e37-4d3bd451af9f.png)
