### ISSUE TITLE
MAUI Essentials MediaPicker CapturePhotoAsync on Windows distinguish between no camera and cancelled

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6660]
### Description

`FileResult file = await MediaPicker.CapturePhotoAsync();`

returns null on Windows (on a laptop/desktop).
Actually it alwasy returns null on Windows and it has been a known issue for 1 year and nothing has happened:
https://github.com/microsoft/WindowsAppSDK/issues/1034

Returning `null `on Android means, that user cancelled the photo capture. 
(logic taken from [this MAUI Essentials sample ](https://github.com/dotnet/maui/blob/main/src/Essentials/samples/Samples/ViewModel/MediaPickerViewModel.cs) btw. that is the only sample with any documentation available for MAUI afaik) 

How to distinguish between that the capture was cancelled and that there is no camera?
When` <action android:name="android.media.action.IMAGE_CAPTURE" />`
is missing in Android manifest, the application throws this error:

[0:] **_Either there was no camera on the device_** or 'android.media.action.IMAGE_CAPTURE' was not added to the <queries> element in the app's manifest file. ...

Microsoft.Maui.ApplicationModel.FeatureNotSupportedException _**Either there was no camera on the device**_ or 'android.media.action.IMAGE_CAPTURE' was not added to the <queries> element in the app's manifest file. ...

But the detection of no camera on device does not work on Windows and it simply returns null for the file instead.

### Public API Changes

any way of distinguishing between photo capture cancelled and no camera available on Windows when running `MediaPicker.CapturePhotoAsync()`

### Intended Use-Case
shared cross-platform code to take a photo

**Comment by jfversluis** [comment]
From what I understand this is a bug on the WinUI side, as you mentioned, and looking at our code, whenever they fix it, it will be resolved on our side automatically. Unfortunately there is nothing much we can do right now on our side for this.
