### ISSUE TITLE
PathFigureCollectionConverter.ParseStringToPathFigureCollection not working correctly

### ISSUE THREAD

**Issue by TitusRie** [dotnet/maui#6670]
### Description

In Xamarin.Forms Paths can be generated from parsing XAML path strings.
Unfortunately, PathFigureCollectionConverter.ParseStringToPathFigureCollection in MAUI not correctly parses or displays the paths defined in the XAML path string.

![image](https://user-images.githubusercontent.com/69340144/165950272-d0e308eb-9de7-4943-8a2a-772bc6549b65.png)

This is the same issue as https://github.com/dotnet/maui/issues/4450

### Steps to Reproduce

Create new MAUI App.

Replace contents of App.xaml.cs with this code:

`using Microsoft.Maui.Controls.Shapes;
using Path = Microsoft.Maui.Controls.Shapes.Path;

namespace MauiApp4;

public partial class App : Application
{
	public App()
	{
		InitializeComponent();
        var pathGeometryRectangle = new Microsoft.Maui.Controls.Shapes.PathGeometry();
        PathFigureCollectionConverter.ParseStringToPathFigureCollection(pathGeometryRectangle.Figures, "M 5 5 H 45 V 45 H 5 Z");

        var pathGeometryCircle = new PathGeometry();
        PathFigureCollectionConverter.ParseStringToPathFigureCollection(pathGeometryCircle.Figures, "M 35 20 A 15 15 0 0 1 20 35 15 15 0 0 1 5 20 15 15 0 0 1 20 5 15 15 0 0 1 35 20 Z");
        MainPage = new ContentPage()
        {
            Content =
                new StackLayout()
                {
                    Children =
                    {
                        new Path
                        {
                            Fill = Brush.Red,
                            Stroke = Brush.Blue,
                            StrokeThickness = 3,
                            Data = pathGeometryRectangle,
                            HeightRequest = 80,
                        },

                        new Path
                        {
                            Fill = Brush.Orange,
                            Stroke = Brush.HotPink,
                            StrokeThickness = 3,
                            Data = pathGeometryCircle,
                            HeightRequest = 80,
                        },
                    }
                }
        };
    }
}`

Run on Windows or Android

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

All

### Did you find any workaround?

No

**Comment by TitusRie** [comment]
Repro project:

[MauiShapePaths.zip](https://github.com/dotnet/maui/files/8591019/MauiShapePaths.zip)

**Comment by TitusRie** [comment]
Expected result as on UWP would be:
![image](https://user-images.githubusercontent.com/69340144/165951767-6050b781-0ef5-4142-b974-def3879deaa3.png)

**Comment by jsuarezruiz** [comment]
Thanks for the repro sample. It seems that the result is correct (tested with main branch).
![image](https://user-images.githubusercontent.com/6755973/166428010-f1eae7fc-0e13-42ce-a015-795ba8ea290a.png)

Could you confirm if this is the expected result?
