### ISSUE TITLE
[Android] <CollectionView.EmptyView> in connection with <SearchBar>

### ISSUE THREAD

**Issue by xxjnaxx** [dotnet/maui#6671]
### Description

<CollectionView.EmptyView> in connection with <SearchBar> will crash the app while a textinput.

### Steps to Reproduce

1. https://github.com/xxjnaxx/Test2
2. Open Project
3. Open MainPage.xaml
4. debug
5. <SearchBar> is working
6. stop debug
7. remove  from <CollectionView.EmptyView>
8. Debug
9. Input in Searchbar
10. Crash

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11.0 API 30

**Comment by Redth** [comment]
Duplicate of #3012
