### ISSUE TITLE
ImageButton visual state does not reset

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#6676]
### Description

Adding a visual pressed state by following the sample in the [docs](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/imagebutton#imagebutton-visual-states) is not getting reset. The image scales down but not up again, according to the docs it should.

Demonstrating the issue on Android Emulator running Android 11 Pixel 5 device:

https://user-images.githubusercontent.com/14368203/165982329-7de78153-455b-4088-aa01-a88b643bd9c1.mp4

### Steps to Reproduce

1. Create a new MAUI project
2. Change the MAUI logo image according to the docs:

```XAML
<ImageButton  Source="dotnet_bot.png"
	WidthRequest="250"
	HeightRequest="310">
<VisualStateManager.VisualStateGroups>
	<VisualStateGroup x:Name="CommonStates">
		<VisualState x:Name="Normal">
			<VisualState.Setters>
				<Setter Property="Scale" Value="1" />
			</VisualState.Setters>
		</VisualState>
		<VisualState x:Name="Pressed">
			<VisualState.Setters>
				<Setter Property="Scale" Value="0.8" />
			</VisualState.Setters>
		</VisualState>
	</VisualStateGroup>
</VisualStateManager.VisualStateGroups>
</ImageButton>
```

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (Pixel 5)

**Comment by Redth** [comment]
What's happening here is the state is not returning to Normal, it's moving to Focused, so you'll need to add that state for the behaviour you expect:

```
 <VisualState x:Name="Focused">
    <VisualState.Setters>
        <Setter Property="Scale" Value="1" />
    </VisualState.Setters>
</VisualState>
```

**Comment by Symbai** [comment]
Thanks, it should be fixed in documentation then
