### ISSUE TITLE
[Enhancement] Provide Shell.TitleBarIsVisible

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#6679]
### Description

Occasionally I don't want to show the title bar but it does not seem to be possible to hide it.

### Steps to Reproduce

Create an app using shell navigation and try to hide the shell on one of the pages.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows 10 

### Did you find any workaround?

Sort of, by setting the title bar background to the same color as the enclosing page you can make the title look almost (see Issue #6680) like part of the page. For example I've used this XAML snippet:

```
<Shell.TitleView>
    <Label FontSize="Title" HorizontalTextAlignment="Center"
           Text="{Binding Title, Source={RelativeSource Mode=FindAncestor, AncestorType={x:Type ContentPage}}}" 
           BackgroundColor="{Binding BackgroundColor, Source={RelativeSource Mode=FindAncestor, AncestorType={x:Type ContentPage}}}"/>
</Shell.TitleView>
```

**Comment by Redth** [comment]
`Shell.NavBarIsVisible="true"` should do it, but as in #6703 it seems to not work on windows (closing to track there instead).

**Comment by david-maw** [comment]
Thanks, I'll follow #6703, and since I was prompted to look in this area I also added #6760 and #6761.
