### ISSUE TITLE
FontImageSource is not displayed on Android, works in Windows.

### ISSUE THREAD

**Issue by IndianaGary** [dotnet/maui#6693]
### Description

I built a default RC2 project that displays the MauiBot and shows a Button that bumps a counter.

I modified the Button to be an ImageButton and set Source to a FontImageSource defined in the page's resource dictionary. For contrast, I put the ImageButton in a yellow Frame and gave the Font Image a hot pink background color.

On Windows, I saw a yellow frame around a hot pink trashcan. Clicking it bumps the count.

On Android, I saw the yellow frame but no trashcan. Clicking where it *should* be, bumps the count.

I have attached the test project.
[MauiAppRC2.zip](https://github.com/dotnet/maui/files/8595468/MauiAppRC2.zip)

### Steps to Reproduce

1. Create a default RC2 project, modify it as described (project attached)
2. Build for Windows and test
3. Build for Android and test

Note the described behavior.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12 - API 31

### Did you find any workaround?

No workaround appeared possible.

### Relevant log output

```shell
N/A
```

**Comment by JimLaird** [comment]
issue verified. fontimagesource not rendering

**Comment by Redth** [comment]
This is fixed in the next release...
![image](https://user-images.githubusercontent.com/271950/166258368-7b9fa3b8-fdeb-470f-9d7d-83d9fcbd5882.png)
