### ISSUE TITLE
[iOS] Editor.IsEnabled doesn't do anything

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#6700]
The Editor on iOS inherits from UITextView which doesn't inherit from UIControl

so the following code doesn't do anything
https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/iOS/ViewExtensions.cs#L22-L23

**Comment by Iangame4** [comment]
Can I have this assigned to me?

**Comment by PureWeen** [comment]
@Iangame4 done

**Comment by Rinzii** [comment]
Gonna have to unassign myself due to personal reasons
