### ISSUE TITLE
Shell.FlyoutBehavior="Locked" shows empy menu on Andriod

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#6701]
### Description

Having a shell with `Shell.FlyoutBehavior="Locked"` shows an empy menu on Android:

![image](https://user-images.githubusercontent.com/3163293/166098281-e27e2bc4-317b-4d08-8dd2-ff679cb334a4.png)

But works fine on Windows:

![image](https://user-images.githubusercontent.com/3163293/166098167-17b6e642-7865-48b0-bc25-3651ce9d6297.png)

### Steps to Reproduce

1. Create a new MAUI app
2. Update shell:
``` XAML
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiIssues.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiIssues"
    FlyoutWidth="140"
    Shell.FlyoutBehavior="Locked">

    <FlyoutItem Title="Main">
        <ShellContent ContentTemplate="{DataTemplate local:MainPage}"/>
    </FlyoutItem>

    <FlyoutItem Title="Settings">
        <ShellContent ContentTemplate="{DataTemplate local:SettingsPage}"/>
    </FlyoutItem>

    <Shell.ItemTemplate>
        <DataTemplate>
            <Grid RowDefinitions="50" HeightRequest="50">
                <Label Text="{Binding Title}"
                       TextColor="Black"
                               />
            </Grid>
        </DataTemplate>
    </Shell.ItemTemplate>
</Shell>
```

Or use this sample: 

https://github.com/pekspro/MauiIssues/tree/FlyoutBehaviorLocked

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Release Candidate 1, or maybelast preview.

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.17763.0, Android 10

**Comment by pictos** [comment]
@pekspro if you:
1. background of the app;
2.  change the switch the theme;
3. Foreground the app, do the items show?

**Comment by Redth** [comment]
Rotating the device fixes this as well, so there's some initialization thing happening here...

**Comment by PureWeen** [comment]
@pekspro fix incoming :-)

**Comment by kristinx0211** [comment]
verified repro on android 11.
