### ISSUE TITLE
Glide tries to set TCS a second time if you background app and then return to it

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#6702]
- run the attached sample
- background the app
- return to the app

[MauiApp28.zip](https://github.com/dotnet/maui/files/8596493/MauiApp28.zip)

<img width="834" alt="image" src="https://user-images.githubusercontent.com/5375137/166099228-3b9e8d19-2218-4604-9496-4fc5600ef453.png">

**Comment by mattleibow** [comment]
This appears to be a big/feature of Glide: https://github.com/bumptech/glide/issues/4795

I will work around it for now until I know what is the correct way to fix or they do a fix.
