### ISSUE TITLE
Pages with no title hides shell menu

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#6703]
### Description

If a page doesn't have a title, the shell menu will be hidden on Android. Sample:

![image](https://user-images.githubusercontent.com/3163293/166099091-8a3bf48f-23de-4ada-a858-acd11b24d662.png)

![image](https://user-images.githubusercontent.com/3163293/166099134-8027f0d7-a451-4d12-8de8-2e6f2094022c.png)

![image](https://user-images.githubusercontent.com/3163293/166099144-f7ff6ec1-7354-4252-bcf4-65ffb2f521b7.png)

Works fine on Windows:

![image](https://user-images.githubusercontent.com/3163293/166099201-7d9e192e-2e90-4f90-9023-9485669fa3d2.png)

![image](https://user-images.githubusercontent.com/3163293/166099209-0a6e83d1-b115-4ed5-b503-583d0b1db516.png)

![image](https://user-images.githubusercontent.com/3163293/166099220-efbba7c6-276e-4e51-9fc4-471887266d0e.png)

I notice that the title area are hidden also on Windows, so maybe this is an expected behaviour. But then the menu also should be hidden on Windows I think. It's not consistent right now. I would prefer an [explicit propery](https://github.com/dotnet/maui/issues/6679) to hide the title.

### Steps to Reproduce

1. Create a new Maui app
2. Add a new page - make sure it doesn't have a title.
3. Update the appshell.xaml:
``` C#
<Shell
    x:Class="MauiIssues.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiIssues"
    FlyoutWidth="140"
    Shell.FlyoutBehavior="Flyout">

    <FlyoutItem Title="Main">
        <ShellContent ContentTemplate="{DataTemplate local:MainPage}"/>
    </FlyoutItem>

    <FlyoutItem Title="Untitled">
        <ShellContent ContentTemplate="{DataTemplate local:UntitledPage}"/>
    </FlyoutItem>

    <Shell.ItemTemplate>
        <DataTemplate>
            <Grid RowDefinitions="50" HeightRequest="50">
                <Label Text="{Binding Title}"
                       TextColor="Black"
                               />
            </Grid>
        </DataTemplate>
    </Shell.ItemTemplate>
</Shell>
```

Or use this sample:
https://github.com/pekspro/MauiIssues/tree/UntitledHidesMenu

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 10.0.17763.0, Android 10

### Did you find any workaround?

Just add a title :-)

Or add a toolbar item.

**Comment by PureWeen** [comment]
@pekspro did you try setting

Shell.NavBarIsVisible="true" on the `ContentPage` ?

**Comment by pekspro** [comment]
Thanks @PureWeen, I wasn't aware of that :-). Setting that forces the menu to be visible: 

![image](https://user-images.githubusercontent.com/3163293/166100465-8746deea-ae85-48b0-8218-899762b96fe1.png)

Setting it to `false` doesn't have an effect on Windows:

![image](https://user-images.githubusercontent.com/3163293/166100585-b9f059cd-f2ea-409f-a2b0-1a2dcc9898a7.png)

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android, not repro on Windows. Sample Project: [6703.zip](https://github.com/dotnet/maui/files/8628375/6703.zip)

**Comment by pekspro** [comment]
This is no longer an issue. Works fine both in .NET 6 and 7. Closing this.
