### ISSUE TITLE
¤ Target current Blazor web app to windows and android

### ISSUE THREAD

**Issue by mike7ang1rdz** [dotnet/maui#6704]
### Description

I currently have a blazor web application that I would like to target to windows and android, is there any documentation of it?

thanks

### Public API Changes

current web blazor target to android and windows

### Intended Use-Case

target a current project in blazor

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is something we're going to cover as part of https://github.com/dotnet/AspNetCore.Docs/issues/25675
