### ISSUE TITLE
Title isn't vertically centered in FlyoutItem

### ISSUE THREAD

**Issue by hamiddd1980** [dotnet/maui#6706]
### Description

Hello.
The **title** (and the Icon) inside **FlyoutItem** isn't Vertically Centered. The title is aligned to Top Row(please see the Below)

### Steps to Reproduce

1-Create a New MAUI Project
2-Add new Shell Page
3-Code:
```
<Shell
    x:Class="MauiApp29.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp29"
    FlowDirection="LeftToRight"
    Shell.FlyoutBehavior="Flyout">
    <FlyoutItem Title="First Item">
        <Tab>
            <ShellContent ContentTemplate="{DataTemplate local:Page1}" />
        </Tab>
    </FlyoutItem>
    <FlyoutItem Title="Second Item">
        <Tab>
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
    </FlyoutItem>
</Shell>
```

![screen1](https://user-images.githubusercontent.com/57061231/166113735-1541e240-7779-45ef-9de9-407b34f3c017.png)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Release Candidate 2 (current)

### Affected platforms

Android

### Affected platform versions

Android 8

**Comment by drasticactions** [comment]
Why would you expect it to be in the center? As far as I know it was never the case in Xamarin.Forms; It always loaded items to the top. So I think what're your asking for is more a feature request, unless I'm missing something. @PureWeen do you have any ideas?

**Comment by hamiddd1980** [comment]
according to images and default template definition for FlyoutItem in [Link](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout), it seems that FlyoutItem **title** and **icon** should be at center position vertically .

**Comment by drasticactions** [comment]
Okay, I confused "Horizontally" and "Vertically", which is "my bad"

**Comment by Redth** [comment]
@PureWeen this does still happen in main.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android. Sample Project: [MauiApp3.zip](https://github.com/dotnet/maui/files/8629517/MauiApp3.zip)

**Comment by Redth** [comment]
This is fixed in main now.  Will release with GA.
