### ISSUE TITLE
Vertical CollectionView should not attempt to scroll horizontally

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/maui#6707]
### Description

Even though CollectionView has vertical orientation, it still attempts to scroll horizontally. It makes CollectionView very user-unfriendly, as you need to move your finger exactly vertical, otherwise you cannot scroll it.

Repro project: https://github.com/Dreamescaper/maui-6707-repro

### Steps to Reproduce

1. Run repro project.
2. Try to scroll the list, moving the finger at some angle (e.g. ~45°).

ER:
CollectionView is scrolled down.

AR:
CollectionView is not scrolled down, horizontal scroll animation is present instead.

![qemu-system-x86_64_A0K3Am0rzJ](https://user-images.githubusercontent.com/17177729/166115208-ec23baeb-3271-4069-aced-f216ffcae7f1.gif)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by Dreamescaper** [comment]
This issue is similar to https://github.com/dotnet/maui/issues/6412, but for the case with root CollectionView.
Issue https://github.com/dotnet/maui/issues/6412 is present on Xamarin.Forms as well, this one - only on MAUI.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Not repro on Android with above project.
![Scroll](https://user-images.githubusercontent.com/97647558/166855811-10402f5e-317c-477d-ac12-f92af6337e2d.gif)
.

**Comment by kristinx0211** [comment]
still an issue on android 12 with 17.3.0 Preview 2.0 [32509.345.main].
https://user-images.githubusercontent.com/99457000/167562589-85418a6a-c7db-433f-909f-10e93797a55e.mp4

**Comment by rmarinho** [comment]
Hello, i just tested this in a device and it doesn't happen, are you still seeing this issue  @Dreamescaper  ? 

Did you test on device or emulator?

**Comment by Dreamescaper** [comment]
@rmarinho 
You're right, I can't reproduce it with GA release, thanks!
