### ISSUE TITLE
xaml grid content on windows not fit (stretch) after window maximize (or after window size increase with mouse borders drag)

### ISSUE THREAD

**Issue by kryszek** [dotnet/maui#6714]
### Description

xaml grid content on windows not fit (stretch) after window maximize (or after window size increase with mouse borders drag).

Also, when you reduce the size of a window by dragging one of its horizontal edges the grid content properly fits, However, when next maximizing the window, the grid content does not match.

### Steps to Reproduce

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestProj1.MainPage">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <Editor Grid.Row="0" Grid.Column="0"/>
        <Editor Grid.Row="1" Grid.Column="0"/>
    </Grid>
</ContentPage>

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

<TargetFrameworks>net6.0-windows10.0.19041</TargetFrameworks>

### Did you find any workaround?

Temporary solution: Dragging vertical edges of the window to reduce its width finally ensures a fit.

**Comment by kryszek** [comment]
The same with simpler XAML:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestProj1.MainPage">

    <Grid>
        <Editor />
    </Grid>
</ContentPage>

what sticks to documentation for Grid
https://docs.microsoft.com/en-us/dotnet/maui/user-interface/layouts/grid
The default value of the RowDefinition.Height property is *. Similarly, the default value of the ColumnDefinition.Width property is *.

**Comment by v-longmin** [comment]
Verified repro on Windows 10 with above code.

**Comment by hartez** [comment]
This is working correctly now with the latest from the main branch.
