### ISSUE TITLE
[Bug] Picker on iOS does not have the title placeholder when nothing is selected

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#672]
### Steps to Reproduce

1. Open the sample
2. Scroll to the picker and observe the empty field
3. Tab and select an item and observe th text populate.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Harrybombe** [comment]
ISO

**Comment by kristinx0211** [comment]
@mattleibow where is the Reproduction Link?

**Comment by samhouts** [comment]
Still an issue on main

**Comment by samhouts** [comment]
I suspect this line needs to be changed to set the title? https://github.com/dotnet/maui/blob/8b56c0b1e703804631f280370fd34789ffa21b16/src/Core/src/Platform/iOS/PickerExtensions.cs#L46
