### ISSUE TITLE
Failed to build "xcrun exited with code 69" and "Class AppleTypeCRetimerRestoreInfoHelper is implemented in both"

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#6721]
### Description

I created a MAUI project on Windows machine. Now I've installed Visual Studio for Mac on a Macbook Pro M1 with all options enabled to install. After the installer was done it told me to install Xcode which I did. Then I tried to simple run my project it said:

please run:
```
dotnet workload install mac-ios
dotnet workload install mac-android
dotnet workload install mac-catalyst
```

Which is very weird because I installed all of them through the official VS 2022 Preview for Mac installer. There were NO .NET sdks installed on this machine before, its brand new. Anyway after I ran the three commands the issues were gone but when I tried to do a simple debug rebuild and it fails with:

`xcrun exited with code 69`
and
`Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib and /Library/Apple/System/Library/PrivateFrameworks/Versions/A/MobileDevice. One of the two will be used. Which one is undefined.`

Like I said this is/was a brand new machine so its frustrating that running the official installer and debugging a simple project is impossible, like this has not been tested by someone. Any help is appreciated because all I want is to debug/build the iOS version on MacOS. For the rest I can fallback to a Windows machine.

//edit: I've now tried Visual studio Code instead of VS 2022 but this gives me the same error message when I run `dotnet build -t:Run -f net6.0-ios`

### Steps to Reproduce

See above

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

Visual Studio 2022 Preview for Mac (Macbook Pro m1)

**Comment by Redth** [comment]
@rolfbjarne  ideas on this one?

**Comment by rolfbjarne** [comment]
> Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib and /Library/Apple/System/Library/PrivateFrameworks/Versions/A/MobileDevice. One of the two will be used. Which one is undefined.

This is likely just a red herring (it comes from Apple's tooling, but I've never seen this particular message cause something bad).

> xcrun exited with code 69

This typically means some problem with the underlying build tools we use from Apple.

Could you get a binlog, by adding `/bl:msbuild.binlog` to the command line like this:

> dotnet build -t:Run -f net6.0-ios /bl:msbuild.binlog

and then upload the resulting msbuild.binlog file here? That should allow us to figure out a bit more. Thanks!

**Comment by Symbai** [comment]
After watching plenty of youtube tutorials and reading guides on how to set it up I've figured out:

1. Despise I'm using an ARM64 Mac, installing the ARM64 .NET SDK was a problem. I also had to install the x64 SDK
2. Installing Xcode is not enough, it also needs to get started once and I needed to agree to the EULA

These two points are missing in the MAUI documentation and should definitely get added. After that these non-helpful error messages finally disappeared. Unfortunately now I'm stuck that as soon as I debug my app, it opens the iOS Simulator but VS 2022 says it cannot connect and the app in the iOS simulator crashes to home screen. If I open it in the iOS Simulator again it shows the splashscreen of the app but then all I got is a blank white screen on the simulated iphone. I don't know why and I cannot debug either, on Android no problems.

For a beginner with MAUI like me this is just a complex and frustrating experience. There isn't much info about MAUI in the internet, mostly Xamarin. But most guides or docs expect you to be either a mac expert or a xamarin expert because they are missing many steps in both directions. Please put more work into getting started with MAUI documentation and consider not everyone is coming from Xamarin or has developed on a Mac before.

Anyway this issue can possibly get closed.

**Comment by Redth** [comment]
VSMac should better support these scenarios now and install the correct dotnet sdk architectures.  VSMac should also prompt to install command line tools if necessary.

**Comment by vipinraturi3112** [comment]
In my case, I just needed to open XCode and accept the terms and conditions on my MAC. I have recently upgraded my MAC OS And this issue disappeared on next build.
May be, it could be helpful for someone. thanks
