### ISSUE TITLE
Content Page- Disappearing event not fire

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#6722]
### Description

Content Page- Disappearing event not fire

### Steps to Reproduce

1. I attached sample code
2. Click on" click me button on main page, it move to New Page.
3. Click on back button the  Disappearing event not fire.
4. See screenshot:
5. 
![image](https://user-images.githubusercontent.com/1079689/166145052-14d54991-06fa-4d87-8b24-bbc0326943a0.png)
[MauiApp21.zip](https://github.com/dotnet/maui/files/8598837/MauiApp21.zip)

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 14

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by danies8** [comment]
Also on Version 17.2.0 Preview 5.0

**Comment by jsuarezruiz** [comment]
Cannot longer reproduce the issue on main branch:
![issue-6722](https://user-images.githubusercontent.com/6755973/166439964-90bdf3f6-2a57-45c7-982e-4a894c94608e.gif)

**Comment by danies8** [comment]
I used Also on Version 17.2.0 Preview 5.0 and it **reproduced**, on which **version** you check ?

**Comment by danies8** [comment]
I checked on version 17.2.0 Preview 5.0 and it reproduced, on which version you check ?
