### ISSUE TITLE
Improve the Migration guide

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#6724]
### Description

The migration guide for RC1 and RC2 (https://github.com/dotnet/maui/wiki/Migrating-to-RC1 ) is missing some features:

In .csproj
- Add ApplicationIdGuid
- Remove the Fullframework for Windows Target in TargetFrameworks to support build with dotnet.exe also for windows

And maybe also explain what MauiImage Update is doing.
And last but not least mention, that we can now use dotnet build and dotnet publish also on Windows.

### Steps to Reproduce

Check https://github.com/dotnet/maui/wiki/Migrating-to-RC1 

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

-

### Did you find any workaround?

-

### Relevant log output

```shell
-
```

**Comment by jfversluis** [comment]
Not sure what you mean with the MauiImage update, but seems like explaining something like that might not be something for a migration guide anyway. Fixed the rest, thanks!

**Comment by rogerbriggen** [comment]
In the latest template there is 
`
<MauiImage Include="Resources\Images\*" />
<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />`
And true, maybe it should be more in the docs what MauiImage Update does and what other params there are.
