### ISSUE TITLE
Recyclerview support

### ISSUE THREAD

**Issue by PontiacGTX** [dotnet/maui#6725]
### Description

I would like to have a xaml component which could be used to list items like a recyclerview does, it is a control that could be added through a nuget package on Xamarin (https://docs.microsoft.com/en-us/xamarin/android/user-interface/layouts/recycler-view/) but the package doesn't work on maui due to the target framework difference

### Public API Changes

?

### Intended Use-Case

It can be used to display a list of images, custom cardview or a list of kind of items which can be selected and explored through

**Comment by emceelovin** [comment]
A regular ListView with recycled Views/custom DataTemplate's isn't enough?

**Comment by xtuzy** [comment]
recycleview support net6.0-android https://www.nuget.org/packages/Xamarin.AndroidX.RecyclerView/, but you can't use it at ios and windows, at maui you can use collectionview, it's android platform view may be recycleview.

**Comment by PontiacGTX** [comment]
> A regular ListView/CollectionView with a recycled Views/custom DataTemplate's CachingStrategy isn't enough?

Yeah I looked after creating this thread if there was an equivalent to Android's RecyclerView and I foud out there was a ListView Control, I will try to use it, or if it doesnt fulfill the needs I have I will report back. thank you also will consider the nuget from xtuzy

**Comment by PureWeen** [comment]
Can we close this issue now @PontiacGTX  ?
