### ISSUE TITLE
Enabling CheckBox does not change visual state

### ISSUE THREAD

**Issue by MartinRothschink** [dotnet/maui#6727]
### Description

If a checkbox is enabled, you can toggle the checkbox, but the visual state is still grayed out (like disabled).
![Screenshot_20220502-084913 (002)](https://user-images.githubusercontent.com/12236753/166195889-04f694c1-3579-4e07-b5bc-96134a380ef7.png)

### Steps to Reproduce

1. Create new Maui App
2. Replace MainPage.xaml with

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:telerikDataControls="clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.Maui.Controls.Compatibility"
             xmlns:telerikChart="clr-namespace:Telerik.XamarinForms.Chart;assembly=Telerik.Maui.Controls.Compatibility"
             xmlns:telerikListView="clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.Maui.Controls.Compatibility"
             x:Class="MauiApp1.MainPage">

    <VerticalStackLayout>
        <CheckBox CheckedChanged="CheckBox_CheckedChanged"/>
        <CheckBox x:Name="Cb2" IsEnabled="False" />
    </VerticalStackLayout>
</ContentPage>

```

and MainPage.xaml.cs with

```
namespace MauiApp1;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}

    private void CheckBox_CheckedChanged(object sender, CheckedChangedEventArgs e)
    {
		Cb2.IsEnabled = true;
    }
}
```

4. Deploy App
5. Toggle first checkbox, second checkbox is now enabled (and working) but still grayed out

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 7 and later, Windows 10/11

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
verified repro on android 11.

**Comment by jsuarezruiz** [comment]
The behavior seems to be the expected one on Windows with the latest version (GA).

![fix-6727-win](https://user-images.githubusercontent.com/6755973/172370826-ddbbe701-12e5-4d03-89c6-671a10ef1c7f.gif)

In Android, the Color property is used in all the states currently. With this PR https://github.com/dotnet/maui/pull/7527 we introduce changes to use the Color property but with opacity.

![fix-6727-droid](https://user-images.githubusercontent.com/6755973/172371095-1c433775-bf16-492a-9cb6-0c3f8f50c4fa.gif)
