### ISSUE TITLE
RC2 - The Grid keeps a height and width at 0 ignoring FillAndExpand

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#6731]
### Description

In .NET MAUI I have added a Grid with 3 columns, one of them occupies 20% of the screen height, the other 50% and the last 30% and has HorizontalOptions in FillAndExpand and VerticalOptions in FillAndExpand, so the Grid should expand all over the screen and show the 3 columns with the configured percentages, in .NET MAUI it is not doing it, the Grid is only shown if you add a WidthRequest and a HeightRequest manually, so it is omitting the FillAndExpand. However the same layout in Xamarin.Forms works perfectly.

Xamarin.Forms works perfectly:
<img width="412" alt="xamarinGood" src="https://user-images.githubusercontent.com/20904914/166215060-b941a69a-d9c6-4a9f-813a-d69898e6ffc9.png">

In .NET Maui the Grid is not displayed unless you set the WidthRequest and HeightRequest manually:
<img width="416" alt="mauiIssue" src="https://user-images.githubusercontent.com/20904914/166215057-be9f7d02-7d11-41c9-8ac7-014754f7154f.png">

.NET MAUI repository with the issue:
https://github.com/nacompllo/MauiCollectionView/tree/test/GridIssue

Xamarin.Forms repository working perfectly:
https://github.com/nacompllo/XamarinCollectionView/tree/test/GridIssue

### Steps to Reproduce

Clone the attached repository and run the application on Android or Windows, the Grid does not fit the screen despite having configured: HorizontalOptions in FillAndExpand and VerticalOptions in FillAndExpand, however if you add a value to the WidthRequest and HeightRequest properties it will will display the Grid on the screen. The same layout in Xamarin.Forms works perfectly, I've attached a repository in case you need to check it out too.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 10, Windows 11

**Comment by kristinx0211** [comment]
verified repro on android with writing a small program to reproduce this issue. demo:
[MauiApp8.zip](https://github.com/dotnet/maui/files/8629452/MauiApp8.zip)

**Comment by samhouts** [comment]
Still reproduces on 6.0.300-rc.4.5760

**Comment by samhouts** [comment]
possibly related to #6714

**Comment by hartez** [comment]
Changing your outermost `VerticalStackLayout` to a `StackLayout` will fix your issue:

```
<ScrollView>
        <StackLayout
            HorizontalOptions="FillAndExpand" 
            VerticalOptions="FillAndExpand">
            <Grid
                ...
            </Grid>
        </StackLayout>
    </ScrollView>
```

The `AndExpand` options are not supported on `VerticalStackLayout` and `HorizontalStackLayout`; `StackLayout` supports them for backward compatibility.

**Comment by nacompllo** [comment]
> 

I have tried to use StackLayout but they still don't work, the StackLayouts don't occupy the space that they have assigned in their respective RowDefinitions of the Grid:
```
    <ScrollView>
        <StackLayout
            HorizontalOptions="FillAndExpand" 
            VerticalOptions="FillAndExpand">
            <Grid
                HorizontalOptions="FillAndExpand" 
                VerticalOptions="FillAndExpand"
                ColumnSpacing="0"
                RowSpacing="0"
                ColumnDefinitions="10*" 
                RowDefinitions="2*,5*,3*">
                <StackLayout
                    Grid.Row="0"
                    Grid.Column="0"
                    BackgroundColor="Gray"
                    HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand">
                </StackLayout>
                <StackLayout
                    Grid.Row="1"
                    Grid.Column="0"
                    BackgroundColor="Brown"
                    HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand">
                </StackLayout>
                <StackLayout
                    Grid.Row="2"
                    Grid.Column="0"
                    BackgroundColor="Green"
                    HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand">
                </StackLayout>
            </Grid>
        </StackLayout>
    </ScrollView>
```

If the grid is the main layout of everything, it works fine:

   ```
     <Grid
            HorizontalOptions="FillAndExpand" 
            VerticalOptions="FillAndExpand"
            ColumnSpacing="0"
            RowSpacing="0"
            ColumnDefinitions="10*" 
            RowDefinitions="2*,5*,3*">
            <VerticalStackLayout
                Grid.Row="0"
                Grid.Column="0"
                BackgroundColor="Gray"
                HorizontalOptions="FillAndExpand"
                <Grid
            HorizontalOptions="FillAndExpand" 
            VerticalOptions="FillAndExpand"
            ColumnSpacing="0"
            RowSpacing="0"
            ColumnDefinitions="10*" 
            RowDefinitions="2*,5*,3*">
            <VerticalStackLayout
                Grid.Row="0"
                Grid.Column="0"
                BackgroundColor="Gray"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">
            </VerticalStackLayout>
        <VerticalStackLayout
                Grid.Row="1"
                Grid.Column="0"
                BackgroundColor="Brown"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">
            </VerticalStackLayout>
        <VerticalStackLayout 
                Grid.Row="2"
                Grid.Column="0"
                BackgroundColor="Green"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">
            </VerticalStackLayout>
        </Grid>        VerticalOptions="FillAndExpand">
            </VerticalStackLayout>
        <VerticalStackLayout
                Grid.Row="1"
                Grid.Column="0"
                BackgroundColor="Brown"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">
            </VerticalStackLayout>
        <VerticalStackLayout 
                Grid.Row="2"
                Grid.Column="0"
                BackgroundColor="Green"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">
            </VerticalStackLayout>
        </Grid>
```

I imagine that the StackLayout compatibility with previous versions (Xamarin) is not working correctly since the same code is working in Xamarin Forms. In any case, as I have commented, if the Grid is the main layout in .NET MAUI, it will work correctly.

A question regarding the AndExpand options, in future versions will they be removed from the VerticalStackLayout and HorizontalStackLayout IntelliSense to prevent them from being used?

**Comment by nacompllo** [comment]
@hartez According to what I explained in the previous comment, should the topic be reopened? Above all I say this because the compatibility of .NET MAUI with StackLayout with previous versions (Xamarin) is not working correctly as can be seen in the previous example in Xamarin.Forms correctly occupies the size assigned in each row of the Grid but the same code in .NET MAUI doesn't.
