### ISSUE TITLE
Switching language on Android results in a crash while navigating if resource manager used (i18n)

### ISSUE THREAD

**Issue by nk54** [dotnet/maui#6732]
### Description

Hello,

I have a MAUI app with 2 resources (ResourceManager), one FR, one EN.

It works really well with the package Microsoft.Extensions.Localization : I'm able to load the correct translation based on the user culture. I can navigate between pages, everything works great.

But if I switch the main language in Android's settings, I go back to the app (was in background while I changed the settings), I try to navigate to a new page to see if the translations are fine, it crashes. (I don't expect live changes when changing my language but at least, while navigating to a new page, I expect the correct translations to be found)

Here is the error 
Java.Lang.IllegalArgumentException: 'No view found for id 0x1 (unknown) for fragment ShellItemRenderer{dd448d5} (e47cc305-1d52-4c02-9754-e65f4ffa09df id=0x1)'

No callstack, only external code

### Steps to Reproduce

Create an app (I use AppShell) with 2 pages.

Add 2 resources to the project and a dependence Microsoft.Extensions.Localization package.
Don't forget to register the dependencie: builder.Services.AddLocalization();
Create a couple of key/values.

Launch the app on Android. See it works.

Go to Android settings, switch from english to the language you added in your 2nd resx.

Go back to the app, try to navigate.

Boom

Couldn't test on Windows as you have to log off to change the language.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Not yet

### Relevant log output

```shell
[enpharma.mobil] Invalid ID 0x00000001.
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.MY_APP_BUNDLEID_WAS_SET_HERE, PID: 29817
[AndroidRuntime] java.lang.IllegalArgumentException: No view found for id 0x1 (unknown) for fragment ShellItemRenderer{dd448d5} (e47cc305-1d52-4c02-9754-e65f4ffa09df id=0x1)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:873)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:193)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6669)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
**Java.Lang.IllegalArgumentException:** 'No view found for id 0x1 (unknown) for fragment ShellItemRenderer{dd448d5} (e47cc305-1d52-4c02-9754-e65f4ffa09df id=0x1)'
```

**Comment by rjygraham** [comment]
I have encountered same fatal crash but it seems to be more general than what's mentioned above.

Steps to repro:

[Repro Repo](https://github.com/rjygraham/MauiShellNav)
1. Create multi-page Android Shell Application with button to navigate from MainPage to SecondPage
2. Start app and then exit using hardware back button (or gesture)
3. Start app again and then attempt to navigate from MainPage to SecondPage
4. App crashes

If debugging you will observe the stacktrace:

````
[me.mauishellna] Invalid ID 0x00000001.
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.companyname.mauishellnav, PID: 7648
[AndroidRuntime] java.lang.IllegalArgumentException: No view found for id 0x1 (unknown) for fragment ShellItemRenderer{f54f2cc} (a7ee66a4-c80c-4f6d-8953-b98bd115c636 id=0x1)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:938)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:223)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7664)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
**Java.Lang.IllegalArgumentException:** 'No view found for id 0x1 (unknown) for fragment ShellItemRenderer{f54f2cc} (a7ee66a4-c80c-4f6d-8953-b98bd115c636 id=0x1)'
````
Video showing crash:
[https://raw.githubusercontent.com/rjygraham/MauiShellNav/main/videos/ShellItemRenderer.mp4](https://raw.githubusercontent.com/rjygraham/MauiShellNav/main/videos/ShellItemRenderer.mp4)

**Comment by VincentBu** [comment]
I can repro with [rjygraham](https://github.com/rjygraham)'s repo on Android. vs version: 32516.383.main

**Comment by PureWeen** [comment]
@rjygraham 's issue should be fixed by this PR https://github.com/dotnet/maui/pull/8455. I'm assuming it's the same issue as the original posters as well because this is generally just a problem when the activity on android is recreated
