### ISSUE TITLE
MAUI Blazor Windows Executables Broken ('Microsoft.ui.xaml.dll')

### ISSUE THREAD

**Issue by clamchoda** [dotnet/maui#6744]
### Description

I just tried the latest preview to give MAUI Blazor a shot. Running the Windows application from within Visual Studio works fine but any of the built executables fail to load. In the event viewer you'll find the exception;

```
Application: FMaps.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at FMaps.WinUI.Program.XamlCheckProcessRequirements()
   at FMaps.WinUI.Program.Main(String[] args) in C:\Users\username\Documents\Visual Studio 2022 Preview\FMaps\FMaps\obj\Release\net6.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.g.i.cs:line 28
```

OS Name	Microsoft Windows 10 Home
Version	10.0.19044 Build 19044

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 5.0

I should mention I didn't change any of the code. I just tested the counter template that loads up by default.

### Steps to Reproduce

1. Create a .NET Maui Blazor application in the latest preview.
2. Build the application.
3. Run any of the Windows executables in the bin folder.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Microsoft Windows 10 Home Version 10.0.19044 Build 19044

### Relevant log output

```shell
Application: FMaps.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at FMaps.WinUI.Program.XamlCheckProcessRequirements()
   at FMaps.WinUI.Program.Main(String[] args) in C:\Users\username\Documents\Visual Studio 2022 Preview\FMaps\FMaps\obj\Release\net6.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.g.i.cs:line 28
```

**Comment by drasticactions** [comment]
This is an issue with WinUI. The same thing would happen if you built a fresh WinUI template (without MAUI included) and tried running it from the build output.

If you install the Windows App SDK runtime downloads (https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-10) it should work. I would bring it up with https://github.com/microsoft/microsoft-ui-xaml/issues.

**Comment by jfversluis** [comment]
Same error also reported here: https://github.com/microsoft/WindowsAppSDK/issues/2443

I think we're working on making this unpackaged scenario work as well. You can track that one on our side here: https://github.com/dotnet/maui/issues/3166

Closing this for now as it's sort of a duplicate :) Keep your eye on those issues!
