### ISSUE TITLE
[Android][WSA] PresentationMode=Modal in Shell with rendering problem of statusbar

### ISSUE THREAD

**Issue by miao17game** [dotnet/maui#6745]
### Description

Shell page with [PresentationMode=Modal] does not render properly on WSA, maybe other situations if device has no statusbar.

Android device:
https://user-images.githubusercontent.com/17511048/166248727-6f70e1e0-9098-41c0-bb19-4403d46041fd.mp4

WSA:
https://user-images.githubusercontent.com/17511048/166248776-a0132afa-0f35-437f-899e-cc7acc62ee32.mp4

### Steps to Reproduce

1. Create new repo with shell and add a page with PresentationMode=Modal
2. dev the project on WSA

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, 11, maybe lower

### Did you find any workaround?

No.

### Relevant log output

```shell
No
```

**Comment by PureWeen** [comment]
[duplicate](https://github.com/dotnet/maui/issues/6532) 
I realize they are slightly different but I'm assuming same root causes
