### ISSUE TITLE
Error In  reading and writing file in Android Emulator and windows from Maui project.

### ISSUE THREAD

**Issue by sanjanapatel2409Unthinkable** [dotnet/maui#6754]
### Description

ANDROID

I am trying to read and write files from the location 
```

Context context = Android.App.Application.Context;
Constant.FileLocation = context.GetExternalFilesDir("").Path;
```

I am getting an Error 

{System.UnauthorizedAccessException: Access to the path '/storage/emulated/0/Android/data/com.companyname.POS/files/ReadData.txt' is denied.
 ---> System.IO.IOException: Permission denied
   

I had given the Permission in Android Manifest

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.INTERNET" />

I don't how to give any other permission so can you please help me with this.

WINDOWS

For the same, I am trying to read files from windows as well as getting Access Denied in that as well
`
Constant.FileLocation = Path.GetPathRoot(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal));
       `

How to Give Permissions..

### Steps to Reproduce

Create a Maui Application -> trying to read files from a specific folder getting access denied

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Release Candidate 3

### Affected platforms

Android, Windows

### Affected platform versions

windows 10.0.19041

**Comment by jfversluis** [comment]
From the code and information you have given it's not really possible to determine if this is a bug on our side or maybe something in your code that doesn't add up. Please provide a small reproduction sample on a GitHub repository that we can look at. Thanks!
