### ISSUE TITLE
"requestLayout() improperly called" warnings spamming output

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#6755]
### Discussed in https://github.com/dotnet/maui/discussions/6512

<div type='discussions-op-text'>

<sup>Originally posted by **russnash** April 26, 2022</sup>
Just wondering if anyone else is seeing floods of this while their app is running?  Just updated to RC2 and my app has slowed to a crawl while endlessly spitting out these messages:

`[View] requestLayout() improperly called by crc64e1fb321c08285b90.FrameRenderer{818c397 V.E...... ......ID 14,14-1067,667 #6} during layout: running second layout pass
[View] requestLayout() improperly called by crc6452ffdc5b34af3a0f.LayoutViewGroup{e455a2 V.E...... ........ 53,53-1002,601} during second layout pass: posting in next frame
[View] requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{771ab69 V.ED..... ........ 0,0-949,103} during second layout pass: posting in next frame
[View] requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{47d43dd V.ED..... ........ 0,103-949,522} during second layout pass: posting in next frame
[View] requestLayout() improperly called by crc64e1fb321c08285b90.FrameRenderer{818c397 V.E...... ......I. 14,14-1067,667 #6} during second layout pass: posting in next frame
[View] requestLayout() improperly called by crc64e1fb321c08285b90.FrameRenderer{818c397 V.E...... ......ID 14,14-1067,667 #6} during layout: running second layout pass
[View] requestLayout() improperly called by crc6452ffdc5b34af3a0f.LayoutViewGroup{e455a2 V.E...... ........ 53,53-1002,601} during second layout pass: posting in next frame
[View] requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{771ab69 V.ED..... ........ 0,0-949,103} during second layout pass: posting in next frame
[View] requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{47d43dd V.ED..... ........ 0,103-949,522} during second layout pass: posting in next frame
[View] requestLayout() improperly called by crc64e1fb321c08285b90.FrameRenderer{818c397 V.E...... ......I. 14,14-1067,667 #6} during second layout pass: posting in next frame
[View] requestLayout() improperly called by crc64e1fb321c08285b90.FrameRenderer{818c397 V.E...... ......ID 14,14-1067,667 #6} during layout: running second layout pass
[View] requestLayout() improperly called by crc6452ffdc5b34af3a0f.LayoutViewGroup{e455a2 V.E...... ........ 53,53-1002,601} during second layout pass: posting in next frame
[View] requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{771ab69 V.ED..... ........ 0,0-949,103} during second layout pass: posting in next frame
[View] requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{47d43dd V.ED..... ........ 0,103-949,522} during second layout pass: posting in next frame
[View] requestLayout() improperly called by crc64e1fb321c08285b90.FrameRenderer{818c397 V.E...... ......I. 14,14-1067,667 #6} during second layout pass: posting in next frame
[View] requestLayout() improperly called by crc64e1fb321c08285b90.FrameRenderer{818c397 V.E...... ......ID 14,14-1067,667 #6} during layout: running second layout pass
[View] requestLayout() improperly called by crc6452ffdc5b34af3a0f.LayoutViewGroup{e455a2 V.E...... ........ 53,53-1002,601} during second layout pass: posting in next frame
[View] requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{771ab69 V.ED..... ........ 0,0-949,103} during second layout pass: posting in next frame
[View] requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{47d43dd V.ED..... ........ 0,103-949,522} during second layout pass: posting in next frame
[View] requestLayout() improperly called by crc64e1fb321c08285b90.FrameRenderer{818c397 V.E...... ......I. 14,14-1067,667 #6} during second layout pass: posting in next frame
[View] requestLayout() improperly called by crc64e1fb321c08285b90.FrameRenderer{818c397 V.E...... ......ID 14,14-1067,667 #6} during layout: running second layout pass
[View] requestLayout() improperly called by crc6452ffdc5b34af3a0f.LayoutViewGroup{e455a2 V.E...... ......ID 53,53-1002,601} during second layout pass: posting in next frame
`</div>

**Comment by PureWeen** [comment]
@hartez  related

https://github.com/dotnet/maui/issues/6606

**Comment by jsuarezruiz** [comment]
With https://github.com/dotnet/maui/issues/6606 or https://github.com/dotnet/maui/issues/5600, maybe have sense to expose the Frame using the Border (with a RoundRectangle and using a Handler)?
