### ISSUE TITLE
MediaPlayer or VLC Player

### ISSUE THREAD

**Issue by apovetkin** [dotnet/maui#6764]
### Description

First of all THANKS for MAUI.

Looks like I did a huge research and cannot find any Video Stream Player for MAUI

Would be nice to have media player which can play video stream.

### Public API Changes

var media = new MediaPlyer();
media.Play("http://192.168.1.1:8080/live.ts");

### Intended Use-Case

My MAUI application will connect to dashboard camera and provide video stream on Android tablet, phone or Ios phone.

**Comment by Xyncgas** [comment]
I thought Xamarin had video support.
Since Maui came from Xamarin perhaps it already supports video?
There is work around by using BlazorWebView to play videos (local or internet)

**Comment by AndreasReitberger** [comment]
If you are using LibVlcSharp in your Xamarin.Forms project, there are plans to migrate this to MAUI as well. 
https://code.videolan.org/videolan/LibVLCSharp/-/issues/346

**Comment by nacompllo** [comment]
The MediaElement control will be integrated into the .NET MAUI Community Toolkit when the time comes, there is currently an [open discussion](https://github.com/CommunityToolkit/Maui/discussions/31) on how to include it in the future. If you have urgency to implement the MediaElement you can use the [Xamarin.CommunityToolkit.MauiCompat](https://www.nuget.org/packages/Xamarin.CommunityToolkit.MauiCompat/2.0.1-preview1007) compatibility nuget which is basically a clone of the Xamarin Community Toolkit but minimally adapted to work with .NET MAUI. There is also a [thread in the VideoLAN forum](https://code.videolan.org/videolan/LibVLCSharp/-/issues/346) in which the migration of LibVLCSharp to .NET MAUI is being considered in the future in case you want to follow it. Finally there is a nuget that is the XamarinMediaManager created by Baseflow that does not seem to have plans to migrate to .NET MAUI or at least they have not announced it, [here is a thread in its repository where a user suggests making the nuget compatible with .NET MAUI.](https://github.com/Baseflow/XamarinMediaManager/issues/835) In any case, this thread does not correspond to this repository directly, you can go to the official discussion about it at this link:
https://github.com/CommunityToolkit/Maui/discussions/31

**Comment by jfversluis** [comment]
Hey @apovetkin thanks for the proposal and everyone else for their input! A couple of things: right now I don't think there is anything available. A lot of library creators have been waiting for the API to stabilize and the breaking changes to stop for .NET MAUI. That happened now, so I expect library maintainers to start looking into converting their libraries.

I can't speak for other libraries, but I can speak a little bit about the Xamarin/.NET MAUI Community Toolkit. The Xamarin Toolkit that is .NET MAUI compatible has the `MediaElement`, I'm not 100% sure it will work but let us know if you find out 😉  for the .NET MAUI Community Toolkit we have the plan to port it, but we just didn't get to it yet. If you, or anyone else here, really needs it and has the time and ability to help us out, that would be much appreciated.

Then for this proposal, I think it's clear that we want to have an element that can play video in .NET MAUI. However, the road to get there is what this is about. I think this proposal will need some more information and discussion before this is actually actionable.

As outlined in the proposal issue template, please put some thought in what are the features you expect to see here? What are properties and functionalities you would like to work with and how do they behave?

I see you already have a concrete scenario in mind which is great! But imagine, with that scenario in mind, what do you expect from a media player?

If we don't have that and some people who will discuss together with us, we will now go build a thing that does what you want, but it might not be exactly what you expected. To prevent that we waste a lot of time and effort on building things our users don't really like, that is why we ask to have a more detailed proposal. 

I'd like to ask you to give this a bit more thought, have a look at existing plugins and note what you like (or don't like) about them and add those details to this issue.

Thanks!

**Comment by jfversluis** [comment]
Actually, I had a feeling this might have already been asked and it has: #2292

So please add any additional details there, closing this one as duplicate

**Comment by apovetkin** [comment]
Many thanks to all. Very useful info.
