### ISSUE TITLE
HorizontalOptions FillAndExpand and Fill does not have any effect on the HorizontalStackLayout

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#6768]
### Description

The The HorizontalOptions FillAndExpand and Fill should stretch the UI to the whole width of the screen. But this is not the case with HorizontalStackLayout. It remains on the start of the screen.

### Steps to Reproduce

Run the repro project where all the ui elements are displayed on the start of the screen whereas the HorizontalOptions of the parent HorizontalStackLayot is set to FillAndExpand. 
[HorizontalStackLayoutBug.zip](https://github.com/dotnet/maui/files/8608465/HorizontalStackLayoutBug.zip)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, I was *not* able test on other platforms

### Affected platform versions

iOS 15 , Android 11 and Windows 

### Did you find any workaround?

Use FlexLayout,  Grid or StackLayout(Horizontally only) as they can stretch on the whole screen .

**Comment by hartez** [comment]
The "AndExpand" layout options have been deprecated, and are only supported by the StackLayout (for legacy/migration reasons). The newer stack layouts (VerticalStackLayout and HorizontalStackLayout) do not support "AndExpand".

For situations where you want to subdivide a screen area, you should use a Grid or FlexLayout.

**Comment by HobDev** [comment]
@hartez Thank you for the information. But the issue is with Fill too. The Fill should expand the HorizontalStackLayout to the whole width of the screen. But it does not and can be reproduce on the attached project.
