### ISSUE TITLE
The UI elements of the screen overlap with StatusBar on iOS on Modal Page

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#6769]
### Description

The UI elements of the screen overlap with StatusBar on iOS when the NavBar is invisible. 

### Steps to Reproduce

Run the repro project and scroll the Screen. The ui elements will overlap with status Bar. 
[ModalPageBug.zip](https://github.com/dotnet/maui/files/8608547/ModalPageBug.zip)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by jfversluis** [comment]
Could you please add a screenshot and a bit more info? I'm pretty sure this is just the way iOS works, iOS allows you to draw under the statusbar. If you don't want that, you'll have to figure something out for that.
