### ISSUE TITLE
[Bug] The Entry.MaxLength value is inconsistent 

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#678]
### Description

Previously in Forms, it seems that a MaxLength of < 0 would just crash. And 0 meant no text at all.

In MAUI, especially for Comet, we can make this consistent and also not crash. One way would be to make < 0 mean all text, 0 mean no text (debatable) and > 0 mean clip text.

### Steps to Reproduce

Windows:
1. Set MaxLength to -1 and run Windows

iOS / Android:
1. Set MaxLength to -1, 0, and 1
2. Observe different things on different OS

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment]
I see there is a MaxLength property on the native WinUI control, but yet we also trim... 

I do know that maybe we are setting the trimmed text because we want that TextChanged event to fire and update the property. At least that is the current functionality. AN dthe MaxLength property is to avoid outside values getting longer - like a keyboard or paste.

**Comment by hartez** [comment]
Seems like the simplest possible rule is that if the text length is longer than the MaxLength, we truncate the text as close to the MaxLength value as possible. The default value for MaxLength is int.MaxValue. If folks want an Entry/Editor with more than 2147483647 characters, they'll need to do some customization work.

So if the MaxLength is 20 and the text is 24 characters long, we truncate to 20.
If MaxLength == 0 and the text is 24, we truncate to zero.
If MaxLength == -5 and the text is 24, we truncate to zero.

**Comment by Redth** [comment]
This no longer crashes on windows, and <= 0 acts as 'no limit', however there's no handling of truncation logic at this point.

**Comment by shimingsg** [comment]
verified with VS 17.2.0 Preview 2.0 [32224.339.main] in Android 12, IOS 15.2 and windows:
if MaxLength =0 , no limited in Android and windows, no length in IOS.
if MaxLength < 0, no limited in Android and windows and IOS.
