### ISSUE TITLE
CollectionView is positioned incorrectly and the scrolling is broken

### ISSUE THREAD

**Issue by holecekp** [dotnet/maui#6784]
### Description

CollectionView behaves differently than ListView in MAUI - it is positioned incorrectly and the scrolling does not work.

I have made a sample repro project with a page that has a label on the top, followed by a CollectionView and there is another label on the bottom. This page is not rendered correctly. The label on the bottom is not visible. Moreover, only first items are shown in the CollectionView, which cannot be scrolled down to show the rest of the items.

There is another page in the repro project that uses a ListView instead of CollectionView. This page is displayed correctly.

**ListView (displayed correctly, the red label on the bottom is visible):**
![mauilistviewwindows](https://user-images.githubusercontent.com/24872113/166485114-d03c0118-ae45-43bc-9b9e-d69e98803fef.png)

**CollectionView (displayed incorrectly, it covers the red label and it cannot be scrolled)**
![mauicollectionviewwindows](https://user-images.githubusercontent.com/24872113/166485297-2d5a6df9-cd8c-4281-88b6-05eacf684a86.png)

Moreover, the CollectionView page rendering is extremely slow (and the CollectionView has only 100 items). This is especially striking when you are on the ListView page in the repro project and then you select the CollectionView page from the flyout menu.

### Steps to Reproduce

1. Download the repro project: https://github.com/holecekp/MauiCollectionView
2. Run it on Windows (but the bug is also on Android)
3. The page with the CollectionView is displayed. There should be 100 items. Only first items are displayed instead and it is impossible to scroll down to view the rest of the items. There should be a red label on the bottom of the screen, but it is not visible and the CollectionView covers it.
4. Open the flyoutmenu and select the second item. It leads to the similar page but it uses a ListView instead. Everything is displayed correctly there. The ListView can be scrolled down to the last of the items. The red label on the bottom of the page is visible.
5. Switch back to the first page with the CollectionView. It takes a long time to load (the same on Android). Switching between these two pages very quickly (it is easier when you set the Shell.FlyoutBehavior="Locked") can crash the app with a COMException, but this is a different bug.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 10 emulator, Windows 10

### Did you find any workaround?

Use a ListView instead of CollectionView if you do not need functions specific to CollectionView. Otherwise, there is no workaround.

**Comment by Redth** [comment]
The simple workaround here is to use a grid with 3 rows...

@hartez thoughts?

**Comment by rmarinho** [comment]
This is by design using the Stacklayout will stretch it's content, you should use Grid, this is a change from Xamarin.Forms
