### ISSUE TITLE
What is the difference between HapticFeedback.Current and .Default?

### ISSUE THREAD

**Issue by adegeo** [dotnet/maui#6799]
### Description

Unsure why both properties exist on the `HapticFeedback` class; what's the difference between the two? Is this an oversight of adding both properties? Some other classes use the term `Default` and some use the term `Current`.

### Steps to Reproduce

Inspect the `HapticFeedback` class.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Release Candidate 2 (current)

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Not platform specific

**Comment by jfversluis** [comment]
Hm yeah that seems a bit weird in this case. I don't think the other Essentials APIs have this, right?
