### ISSUE TITLE
[Bug] Button on Samples Controls app is not rendering with correct height on WinUI

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#680]
### Description

Button text cut off on WinUI

### Steps to Reproduce

1. Open WinUI.sln
2. Run samples app

### Expected Behavior

The Hello from Forms button text should not be cut off

### Actual Behavior
The Hello from Forms button text should is cut off

### Screenshots

![image](https://user-images.githubusercontent.com/5375137/113927364-009a8980-97b3-11eb-87cb-b02c9c935559.png)

**Comment by jsuarezruiz** [comment]
Tested in Preview 11 and seems to be fixed 
![image](https://user-images.githubusercontent.com/6755973/140487698-83dfafb2-e7de-4a4e-aa78-679d76995b8e.png)
