### ISSUE TITLE
Label sometimes displays hugely wrong font size and spacing

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#6801]
### Description

As shown in the attached repro sample, "theLabel.FormattedText" is set twice; once after init and then again after 2 seconds.

Even though the Label font size settings is not changed and even though the same FormattedText is used, after 2 seconds the label text changes significantly when it should not.  This is a regression (XF did not have this issue) and manifests in many different ways.  The repro just shows one such example.

[layoutbug8.zip](https://github.com/dotnet/maui/files/8618486/layoutbug8.zip)

### Steps to Reproduce

1. Compile and run the sample under Android 11
2. notice the label layout/size change completely after 2 seconds - even though nothing should change.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

no, and similar strange things happen using different layouts.

**Comment by kristinx0211** [comment]
verified repro on android 11 with above project.

**Comment by mattleibow** [comment]
I fixed a bug like this a while back, could we check again with RC 3?

**Comment by jfversluis** [comment]
@kristinx0211 could you check again please?

**Comment by kristinx0211** [comment]
@jfversluis sure, I can repro it on android 11 and 12 with vs 17.3.0 Preview 2.0 [32511.531.main].

**Comment by mattleibow** [comment]
OK, so I am looking at this and I see the issue. The initial text is wrong as it is small font, but the FontSize was 35. When the text changes, then it gets the correct size.
