### ISSUE TITLE
Border Rendered Incorrectly While giving Corner Radius in some cases

### ISSUE THREAD

**Issue by Ahamed-Ali** [dotnet/maui#6805]
### Description

Borders are not correctly rendered on Android while giving the corner radius ..But it works on WinUI perfectly

In Android
<img width="158" alt="Android" src="https://user-images.githubusercontent.com/102580874/166669317-d3cdf134-4d28-4fd0-977e-73df79d06aa1.png">

In Windows

<img width="195" alt="windows" src="https://user-images.githubusercontent.com/102580874/166669356-ac86e328-1f52-4dd5-8b0d-f50f305ea01f.png">

### Steps to Reproduce

1.Unzip the sample file and use it

[SampleLevelBorder.zip](https://github.com/dotnet/maui/files/8619760/SampleLevelBorder.zip)

2.See the differences when deploy

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9.0

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by kristinx0211** [comment]
verified repro on android 11 with the above project.
