### ISSUE TITLE
[Windows] ContentView with ContentPresenter measured and arranged incorrectly

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#6808]
### Description

When using a `ContentView` with `ControlTemplate` and `ContentPresenter`, the content is measured and arranged incorrectly on Windows.

Here is an example XAML code snippet:

```xml
<ContentView>
    <ContentView.ControlTemplate>
        <ControlTemplate>
            <VerticalStackLayout>
                <Label Text="Header" BackgroundColor="LightGray" />
                <ContentPresenter />
                <Label Text="Footer" BackgroundColor="LightGray" />
            </VerticalStackLayout>
        </ControlTemplate>
    </ContentView.ControlTemplate>
    <VerticalStackLayout>
        <Label Text="Content 1" />
        <Label Text="Content 2" />
        <Label Text="Content 3" />
    </VerticalStackLayout>
</ContentView>
```

The following screenshot shows how this looks on Android (correct):

![ContentView - Android](https://user-images.githubusercontent.com/98032058/166677393-25542382-dd73-4668-a7e3-7c1c08837669.png)

The next screenshot shows how this looks in Windows (incorrect):

![ContentView - Windows](https://user-images.githubusercontent.com/98032058/166674619-b4c72a3f-5ba7-4512-b307-d05d4b0182eb.png)

After debugging the `Measure` and `Arrange` methods of the content, `Measure` is called with zeros for both `widthConstraint` and `heightConstraint` as some point, which causes the above problem. Here is the code snippet I am using to debug the layout issue:

```csharp
public class MyVerticalStackLayout : VerticalStackLayout
{
    protected override Size MeasureOverride(double widthConstraint, double heightConstraint)
    {
        var size = base.MeasureOverride(widthConstraint, heightConstraint);

        return size;
    }

    protected override Size ArrangeOverride(Rect bounds)
    {
        var size = base.ArrangeOverride(bounds);

        return size;
    }
}
```

### Steps to Reproduce

1. Run the attached sample project
2. Observe the layout on Windows

[TestApp.zip](https://github.com/dotnet/maui/files/8620103/TestApp.zip)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

I have not tested on various versions of the different platforms.

### Did you find any workaround?

The workaround I have found so far is to avoid using `ContentPresenter`. The same behavior can be achieved by nesting another `ContentView` inside the `ContentView` with the `ControlTemplate` like this:

```xml
<ContentView>
    <ContentView.ControlTemplate>
        <ControlTemplate>
            <VerticalStackLayout>
                <Label Text="Header" BackgroundColor="LightGray" />
                <ContentView Content="{TemplateBinding Content}" />
                <Label Text="Footer" BackgroundColor="LightGray" />
            </VerticalStackLayout>
        </ControlTemplate>
    </ContentView.ControlTemplate>
    <VerticalStackLayout>
        <Label Text="Content 1" />
        <Label Text="Content 2" />
        <Label Text="Content 3" />
    </VerticalStackLayout>
</ContentView>
```

**Comment by ivan-todorov-progress** [comment]
Another thing to note, I have encountered exceptions on Windows, when `Measure` is called with zeros for both `widthConstraint` and `heightConstraint`. Apparently, some WinUI controls do not like to be measured with zeros and tend to throw COM exceptions in such cases. I have tried to reproduce the COM exceptions in an isolated app without success so far.

**Comment by kristinx0211** [comment]
verified repro on windows.
