### ISSUE TITLE
[Enhancement] Remove usage of XmlnsDefinitionAttribute.AssemblyName

### ISSUE THREAD

**Issue by mgoertz-msft** [dotnet/maui#681]
## Summary
The XmlnsDefinitionAttribute is needed to group an assembly's CLR namespaces in a different XML namespace, such as "http://xamarin.com/schemas/2014/forms" for example. All assemblies that include types that should be visible in XAML need to have this attribute.

The AssemblyName property of XmlnsDefinitionAttribute is more like a hack to define assembly-level attributes in one assembly for an entirely different assembly.

## API Changes

Remove XmlnsDefinitionAttribute.AssemblyName, move the attribute definition to the lowest common dependency of all assemblies that need to expose types through a common xmlns.

## Intended Use Case
Primitives, such as Color and Thickness, which are used in XMAL and expected to be in the default namespace, are currently included in Microsoft.Maui. That assembly (or whichever assembly these types end up in) needs include the XmlnsDefinitionAttribute to add the CLR namespace for these types to the default xmlns.

**Comment by mgoertz-msft** [comment]
Thanks @Redth! I think this also needs the XET Partner Team project added. If someone could grant me permissions, then I could help with the housekeeping of these issues too.

**Comment by Redth** [comment]
Some notes:

- Each assembly which contains typed to be exposed to XAML intellisense needs to define this attribute in it.
- Each declaration can point to a different CLR namespace with the same xmlns.

**Comment by Redth** [comment]
The PR's mentioned in https://github.com/dotnet/maui/issues/675 should take care of this issue too.

**Comment by mgoertz-msft** [comment]
@Redth Actually, I have to take that back. I should have looked at [the attribute in System.Xaml](https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.xmlnsdefinitionattribute.assemblyname?view=net-5.0#System_Windows_Markup_XmlnsDefinitionAttribute_AssemblyName) first. AssemblyName is indeed in there, but in all these years I have never come across anyone actually using it until now with MAUI. We have never supported it in IntelliSense before and never heard of any complaints about it before either.

So while you could actually keep the AssemblyName property in the attribute I would still discourage its usage since we have no IntelliSense support for it.

**Comment by Redth** [comment]
We did end up keeping the AssemblyName usage for our own XamlC and XamlG build task needs, but we have moved/created attributes in the originating assemblies as well to allow for the expected behaviour of hot reload. This is fixed by #745
