### ISSUE TITLE
Onboard to source.dot.net

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/maui#6814]
### Description

See: https://github.com/dotnet/core-eng/issues/15641

There is a .yaml template we could use to get the sources for MAUI up on https://source.dot.net/.

It looks like we would probably also need a variable group setup in devdiv's AzDO instance.

**Comment by rmarinho** [comment]
OK we got our internal release  building with arcade and enabling this. and it works

<img width="1167" alt="Image" src="https://github.com/user-attachments/assets/1d12e7ce-b06d-4e4b-9c4c-18a1d12a4818" />

We are waiting [this PR ](https://github.com/dotnet/source-indexer/pull/178) to be merged seems it works fine. 
One can browse here https://netsourceindex-validation.azurewebsites.net/#q=Maui
