### ISSUE TITLE
Show output for Release applications on Android

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6824]
### Description

Currently when there is an issue with Android application running on Release, we cannot see the output. We cannot see the exceptions or anything else. This is especially crucial for scenarios like Debug runs fine and Release crashes on startup. This is completely unexpected and currently there is little ways to determine what happened for average user. The application just "doesn't work".

There is probably a way of logging using command line with `adb` but that is not user friendly or straightforward especially for people who are new to mobile development.
This tooling is not integrated with Visual Studio and requires additional setup for such a simple feature which is showing application output during runtime.

### Public API Changes

I don't know

### Intended Use-Case

Mainly find out what is causing exceptions/issues with Release application compared to the same code but running on Debug configuration.

All other issues than the difference `Debug` × `Release` can be solved within running `Debug` configuration during casual development.

**Comment by Redth** [comment]
Can you provide some more information about what you mean exactly?  What output are you expecting to see and where in Visual Studio?

You can definitely log to ADB with Console.WriteLine or Android.Util.Log methods, and in general adb is going to show you information about the device, including stack traces or exceptions of crashes from your app.

There's even a logcat viewer built into Visual Studio (in the menu: Tools -> Android -> Device Log).

**Comment by janseris** [comment]
> Can you provide some more information about what you mean exactly? What output are you expecting to see and where in Visual Studio?
> 
> You can definitely log to ADB with Console.WriteLine or Android.Util.Log methods, and in general adb is going to show you information about the device, including stack traces or exceptions of crashes from your app.
> 
> There's even a logcat viewer built into Visual Studio (in the menu: Tools -> Android -> Device Log).

I mean that when you run a WinForms app in Release mode, you can see your own prints from the code in the Output Window in Visual Studio.
This is the feature I expect with MAUI.
The reason is to be able to check if nothing broke when running Release instead of Debug in MAUI (a lot used to break and is reported to this day for this scenario) .

**Comment by janseris** [comment]
I love how you guys scrap every important idea. That makes the framework much more developer friendly every time
