### ISSUE TITLE
Cannot publish freshly created MAUI app as documented

### ISSUE THREAD

**Issue by Dbquity** [dotnet/maui#6831]
### Description

Documented steps to publish a MAUI app for Windows fails.

repro sln here: https://github.com/Dbquity/MauiApp10

### Steps to Reproduce

1. create a fresh MAUI App with the add project UI in Visual Studio 2022 Community - Preview version 17.2 Preview 6
2. Follow the instructions here: [https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview](https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview)  
3. observe this output from executing the described msbuild command:
```  
...
Build FAILED.

"C:\Code\Maui\MauiApp10\MauiApp10.sln" (Publish target) (1:2) ->
"C:\Code\Maui\MauiApp10\MauiApp10.csproj" (Publish target) (2:18) ->
(ResolvePackageAssets target) ->
  C:\Program Files\dotnet\sdk\6.0.300-preview.22204.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolut
ion.targets(267,5): error NETSDK1005: Assets file 'C:\Code\Maui\MauiApp10\obj\project.assets.json' doesn't have a targe
t for 'net6.0-windows10.0.19041'. Ensure that restore has run and that you have included 'net6.0-windows10.0.19041' in
the TargetFrameworks for your project. [C:\Code\Maui\MauiApp10\MauiApp10.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.99
```

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

Yes. Choosing the ```Release``` profile and ```Windows Machine``` as target in the Visual Studio UI and then building the project successfully produces a .msix - notice the extra ```.0``` in the target framework identifier ```net6.0-windows10.0.19041.0```: 
```
Build started...
1>------ Build started: Project: MauiApp10, Configuration: Release Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>MauiApp10 -> C:\Code\Maui\MauiApp10\bin\Release\net6.0-windows10.0.19041.0\win10-x64\MauiApp10.dll
1>MauiApp10 -> C:\Code\Maui\MauiApp10\bin\Release\net6.0-windows10.0.19041.0\win10-64\AppPackages\MauiApp10_1.0.0.1_Test\MauiApp10_1.0.0.1_x64.msix
1>MauiApp10 -> bin\Release\net6.0-windows10.0.19041.0\win10-x64\AppPackages\MauiApp10_1.0.0.1_Test\MauiApp10_1.0.0.1_x64.msixsym
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by Dbquity** [comment]
This issue was first reported here: https://developercommunity.visualstudio.com/t/Cannot-publish-freshly-created-MAUI-app/10029954

**Comment by Dbquity** [comment]
It seems the version of the .NET 6, 6.0.300-preview.22204.3, that installs with VS Preview - version 17.2 Preview 6 is not in sync with MAUI RC2 on how to identify the Windows target framework:
The former uses ```net6.0-windows10.0.19041```, the latter adds a ```.0```: ```net6.0-windows10.0.19041.0```

**Comment by jfversluis** [comment]
This is mostly an issue in the docs at this point. The TFM has been updated in our templates but not in the docs. The TargetFramework in the publish command should match the one in your csproj. I have updated the docs to use `dotnet publish` and also added the new TFM, including a note that you should double-check that the TMF identifiers are the same.
