### ISSUE TITLE
Add required permissions in API documentation

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6833]
### Description

E.g. MediaPicker.CapturePhoto requires permission XY on Android. This should be written somewhere in the method documentation to avoid surprises when switching to Release.
From my experience with desktop C# development, `Debug` vs `Release` should be about execution speed and removed debug symbols and not _**application behavior changed unexpectedly**_
Also, the fact that Debug does not require permissions and Release requires them, should be added to the official MAUI docs, like in deployment scenario etc.

### Public API Changes

update documentation on APIs which require permissions

- this is already partially implemented when exceptions are thrown with nice description when a permission is missing but this is only during runtime and requires testing every scenario in Release (which is currently very costly in time to build - 3 or more minutes)

### Intended Use-Case

clear statement about required permissions for every used API of MAUI Essentials and maybe other MAUI APIs (do any non-Eseentials APIs require permissions, too?)

**Comment by Eilon** [comment]
BTW you can find a lot of this in the Xamarin.Essentials docs: https://docs.microsoft.com/xamarin/essentials/media-picker?context=xamarin%2Fandroid&tabs=android

And with .NET MAUI Essentials it's pretty much always going to be the same requirements, because it's largely a port from Xamarin.Essentials.

**Comment by jfversluis** [comment]
All the necessary permissions have also been added to the .NET MAUI conceptual docs for this: https://learn.microsoft.com/dotnet/maui/platform-integration/?view=net-maui-7.0

We might still consider making that also more clear in the API docs. I will retarget this issue to mention that.

If you have a conceptual docs issue, please open an issue on their repository, you can find how to do that under each Microsoft Learn page.
