### ISSUE TITLE
Reopen issue #4593. VS 17.2 prv6. Error NETSDK1130 Microsoft.Graphics.Canvas.winmd cannot be referenced. Referencing a Windows Metadata component directly when targeting .NET 5 or higher is not supported. For more information, see https://aka.ms/netsdk1130

### ISSUE THREAD

**Issue by laorient** [dotnet/maui#6842]
### Description

What I observed is that the Microsoft.Graphics.Win2D and Microsoft.Windows.AppSDK are wrapped in an itemgroup with a condition. Like below:
<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
However, I was forced to upgrade both to a later version when VS complained about package downgrade and wants me to specify a higher version. After I did that, these two entries were added to a new ItemGroup without the Condition, so they got applied to other targets, hence the error.

### Steps to Reproduce

1. Create an project in older version of MAUI preview.
2. Open in VS 17.2 prv6 and upgrade both Win2D and AppSDK packages.
3. It would complain and would not let you run.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

copy the Condition and paste it to the new ItemGroup. Remove the old ItemGroup.

**Comment by jfversluis** [comment]
It's not entirely clear to me what you want us to do here?

It seems that you already found a solution? For the previews we didn't worry about the backwards compatibility, of course in the future we will. If this is working with a File > New project today then there is no issue as far as I'm concerned at this point.

Also, if you have an older project already there is the [migration guides](https://github.com/dotnet/maui/wiki/Migrating-to-RC1) in the wiki to update you through all the previews and that should get you in the right state.

And lastly, you shouldn't have to upgrade the Win2D and WindowsAppSDK packages manually.

Is there something I am missing here? 😊
