### ISSUE TITLE
Get native Window handle from control

### ISSUE THREAD

**Issue by niksedk** [dotnet/maui#6843]
### Description

I would like to port a Winforms desktop app which uses a native lib to render video - so the app should have different code for different platforms, but I was unable to find a way to get an IntPtr Windows handle from e.g. a BoxView.

### Public API Changes

I do not know where this functionality should be added...

### Intended Use-Case

In Winforms we can do something like this:
```csharp
_libvlc_media_player_set_hwnd(mediaPlayer, panelVideo.Handle); // Render video on Windows in a panel control
```

It would be very useful to have a similar feature in Maui - if it's not already available.

**Comment by jfversluis** [comment]
I think we only have this on a window level now, but you're asking on a control level, right?

**Comment by niksedk** [comment]
> I think we only have this on a window level now, but you're asking on a control level, right?

Yes, that's correct.

**Comment by PureWeen** [comment]
@niksedk we've added the `Window` property to every single control. Once the view has been added to a control you can use `BoxView.Window.Handler.PlatformView` to return the platform window and then get the handle from that. Does that work for you for now?

**Comment by niksedk** [comment]
@PureWeen: thanks for the Window property :)

I've added a BoxView to the default template:
![image](https://user-images.githubusercontent.com/1261331/189027857-e00462ef-b436-4602-9b9f-a5709175aa42.png)

In the `OnCounterClicked` method I've added:
````
#if WINDOWS
  videoPlayer.Initialize((IntPtr)(BoxView1.Window.Handler.PlatformView as MauiWinUIWindow).WindowHandle, "video.mp4");
#endif
````

Which seems to make a video player in the whole app window:
![image](https://user-images.githubusercontent.com/1261331/189028527-7d774271-6801-48c6-aff6-91987c51581f.png)

Any ideas?

**Comment by mattleibow** [comment]
This may be possible once you have the native WinUI control. So if you do `BoxView.Handler.PlatformView as Microsoft.UI.Xaml.Element` there may be a way.

I would actually suggest talking to the WinUI experts over on https://github.com/microsoft/microsoft-ui-xaml as I am not sure myself if I know of a proper (or a bit hacky) way to do this. It may also be the case that there is no HWND by default as these may not be "normal" controls and you have to add some sort of special composition or HWND-supporting panel.

But again, not sure we can be as helpful as we would like and opening a new issue on how to get a HWND from a UI element in WinUI 3 will be the solution. And then you take that and just use the `PlatformView` value from MAUI to merge the two worlds.

**Comment by srikrishnancgvak28** [comment]
WinForms with C#
The C# code below shows how to retrieve the window handle (HWND) for a WinForms form object. This example uses the [NativeWindow.Handle](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.nativewindow.handle) property.

C#

Copy
// Form1.cs
private void button1_Click(object sender, EventArgs e)
{
    var hWnd = this.Handle;
}
Like that how to get the Handle of the Control in MAUI.
