### ISSUE TITLE
MauiIcon ForegroundScale does not work (does not scale icon under Android)

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#6850]
### Description

In the supplied repro app I use the following modification in the csproj file:

<MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" Color="#512BD4" ForegroundScale="0.1" />

However, no matter what value I set ForegroundScale to, the app icon does not change appearance under Android 11.

### Steps to Reproduce

1. build and run repro app under Android 11
2. App icon image is full size even though it should be scaled down.

[layoutbug7.zip](https://github.com/dotnet/maui/files/8629984/layoutbug7.zip)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

no

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[layoutbug7.zip](https://github.com/dotnet/maui/files/8630197/layoutbug7.zip)

**Comment by philipag** [comment]
yes, this is working now and can be closed.
