### ISSUE TITLE
IndicatorView for CarouselView does not work

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#6854]
### Description

IndicatorView for CarouselView does not work reliably. When you start the app, the indicator doesn't work at all, it only reacts when you scroll

Repro
https://github.com/HausBJB/MauiApp3.git

Gif
![Animation](https://user-images.githubusercontent.com/53478848/166916090-7de7f4a5-e5d3-4a73-a1e5-3f25d6311a0f.gif)

### Steps to Reproduce

1. Use Repro
2. Run App
3. use IndicatorView 

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12 API31

**Comment by kristinx0211** [comment]
verified repro on android 11 with 17.3.0 Preview 2.0 [32503.460.main].

**Comment by samhouts** [comment]
If you remove the PeekAreaInsets, it seems to work reliably. There must be a calculation problem there.

**Comment by shimingsg** [comment]
verified repro with 17.3.0 Preview 2.0 [32506.315.main], yes, if remove the PeekAreaInsets, it works reliably. but the layout is different from above:
![image](https://user-images.githubusercontent.com/20982341/167242056-03d4fe5f-e0a2-4463-bf3a-036f18091f71.png)

**Comment by Csaba8472** [comment]
I have the same issue when I bind ItemsSource value.

**Comment by TonyLugg** [comment]
IndicatorView doesn't work at all on Windows.  On Android it is not centered horizontally.  Works on iOS.

**Comment by jinxinjuan** [comment]
Cannot access the repo: https://github.com/HausBJB/MauiApp3.git.

So verified this issue with another repo [IndicatorViewDemos.zip (https://github.com/dotnet/maui/files/11785269/IndicatorViewDemos.zip), it seems to be non-reproducible. Not sure and need to confirm.
