### ISSUE TITLE
MenuBarItems are disappearing when navigating back from an another page

### ISSUE THREAD

**Issue by banditoth** [dotnet/maui#6855]
### Description

When navigating back from a page which is pushed with `Shell.Current.GoToAsync` from the source page, the source page's MenuBarItems does not get re-rendered.

[Youtube repro video](https://www.youtube.com/watch?v=osCUfq5clBo )

Dotnet version: 6.0.400-preview.22255.2

<img width="556" alt="image" src="https://user-images.githubusercontent.com/24568882/166921615-e689d025-8895-4b89-89a5-5358b390ea93.png">

### Steps to Reproduce

[Menubaritemtest.zip](https://github.com/dotnet/maui/files/8631110/Menubaritemtest.zip)

Run the attached project. Click on click me button, then hit the back button.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macCatalyst

**Comment by Redth** [comment]
@PureWeen this appears to work on Windows fine, so it's MacCatalyst specific.
