### ISSUE TITLE
[iOS] Cannot Debug

### ISSUE THREAD

**Issue by PedroCigaw** [dotnet/maui#6869]
### Description

When targetting IOS and setting a break point the break point gets hit but I cannot see any code.

I previously logged this [#4297](https://github.com/dotnet/maui/issues/4297) and it was closed with no information and its clearly not fixed.

I have not been able to debug iOS builds on windows since Preview 11.  I have tried everything I can think of from new Windows installations, multiple iphones and I have nothing but pain and suffering with Maui when it comes to targeting iOS.  Everything from not being able to pair to the mac due sdk install failures, to now also not being able to automatic provision, I have found workrounds for these issues, but not being able to debug I am having no luck at all.  

I am assuming given the lack of documentation with regards to Getting Started iOS  and even the wiki reference to macos maui installs target MacCatalyst as opposed to an iOS suggests that things are not going well.

What I would like is some sort of confirmation that this is indeed a problem, and if it isn't, at least some sort of clue as to what I can do next.

Note: Xamarin debuging works perfectly on all the environments and phones I have tried, but Maui fails with the following.

<img width="635" alt="150876856-25e6f5cc-dd34-4e07-b111-39ea1b7a04ea" src="https://user-images.githubusercontent.com/65864520/166972501-7a9184b5-85da-420e-812e-71302ab2d957.png">

### Steps to Reproduce

1. Create new Maui App
2. Set provisioning info
3. Connect local IPhone and target iOS
4. Set break point anywhere
5. Debug to local connect Iphone

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No workrounds

### Relevant log output

```shell
I would happily provide some if I knew where to look?
```

**Comment by drasticactions** [comment]
So looking at https://github.com/dotnet/maui/issues/4297 again.

Your issue there was with Hot Restart (Where you can deploy a Xamarin.Forms/MAUI app to a iPhone without a Mac). That issue was closed because it was "fixed" but you still have issues. Those issues cannot be solved in this repo, nor by this team. That feature is maintained by those inside Visual Studio.

You would be better served filing this as Visual Studio feedback (https://developercommunity.visualstudio.com/home) because otherwise it won't be looked at.

**Comment by PedroCigaw** [comment]
My issue was never with Hot Restart, the issue has been the same I see no code when trying to debug Maui apps on an IPhone but it works fine on Xamarin applications.  On preview 11 debugging worked fine and as expected, set a break point and see the line of code, after upgrading to preview 12 it has stopped working for me.  Tried multiple machines including fresh windows installs and multiple iphones,  I will also log this with VS Feedback as suggested thanks.

**Comment by PedroCigaw** [comment]
Seems to finally be working again in 17.3.0 Preview 1
