### ISSUE TITLE
Entry.IsPassword several bugs on Windows (value from binding is not set, IsPassword cannot be changed without reseting value if from value came from binding instead of user input 

### ISSUE THREAD

**Issue by nk54** [dotnet/maui#6870]
### Description

[Amazing Github repro project](https://github.com/Nk54/bug-maui-password)

2 bugs

**First one**
If an entry.IsPassword is set to true and text is binded, on page appearing, nothing is displayed inside the entry on windows (works on android)

But if IsPassword = false, then the password value is loaded.

**Second one** 
On Windows only, if an entry (with either IsPassword true or false) has its text binded and then on a button click you switch IsPassword, the text gets reset on Windows. Setting IsPassword to its original value doesn't give the text back.
Edit: as said in the screenshot: if user types something in the entry then switch IsPassword, it works. This is weird it doesn't work with binding.

![image](https://user-images.githubusercontent.com/13755220/166973754-4d9d4181-19be-4163-8db5-6c84c2f0b490.png)

### Steps to Reproduce

Check the amazing repro project ;)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

Remove the feature to show the password on Windows for now (I hope it will be fixed in the future because it's the kind of mandatory feature when working with password)

**Comment by v-longmin** [comment]
Verified repro on windows with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[bug-maui-password-main.zip](https://github.com/dotnet/maui/files/8636998/bug-maui-password-main.zip)

**Comment by Redth** [comment]
@SotoiGhost can you test these cases with your recent PR/changes?

**Comment by SotoiGhost** [comment]
This issue seems to be fixed with #6841

https://user-images.githubusercontent.com/5924210/167196370-e8cf3518-9827-49ed-842f-e41036f9d4d2.mp4
