### ISSUE TITLE
[Enhancement] DesignTools DLLs needed for IntelliSense

### ISSUE THREAD

**Issue by mgoertz-msft** [dotnet/maui#688]
## Summary
MAUI needs to build and ship .designtools.dll assemblies for additional IntelliSense support through metadata attribute tables similar to what Xamarin Forms does.

## API Changes
Xamarin Forms ships .design.dll assemblies for Xamarin.Forms.dll and Xamarin.Forms.Xaml.dll. These are based on old and obsolete designer extensibility APIs. They are being replaced with new and similar APIs for the Surface Isolation architecture. More information and samples can be found here: https://github.com/microsoft/xaml-designer-extensibility

## Intended Use Case
To provide IntelliSense completions for things like the FontSize's NamedSize values.

## Remarks
We should try to minimize if not eliminate the need for these design-time DLLs though. We can already handle various metadata attributes that have been redefined outside .NET Framework, such as XmlnsDefinition for example. This can/should probably be expanded to other common attributes like EditorBrowsable, Obsolete, etc.

Similarly, we have also replicated the functionality of Xamarin.Forms.Design.StructOptionsConverter, which automatically offers a type's public static members of the same type as completion values (for example, Red for Color.Red, etc.). But anything that cannot follow simple conventions like that we would need to support through design DLLs.

**Comment by Redth** [comment]
We should look through the old design dll for special cases to port to this, as well as look specifically at Color API changes (ie: Named colors moved from Color -> Colors)

**Comment by Redth** [comment]
I'm calling this done for now based on #955 

There will most certainly be more tweaks/fixes/improvements to make yet, but we should open new issues for each one specifically.

Thanks for your help!

**Comment by mgoertz-msft** [comment]
Sounds good. Thanks for adding them!
