### ISSUE TITLE
Border StrokeShape RoundRectangle Geometry Issue

### ISSUE THREAD

**Issue by Ahamed-Ali** [dotnet/maui#6880]
### Description

RoundRectangle Geometry Shape is not Viewed as  Expected , Inside the Circle there is like a rectangle rendered

Giving Corner Radius Half of the width  and seems like in both platform below,

In Android,

<img width="184" alt="RoundRectAndroid" src="https://user-images.githubusercontent.com/102580874/167075569-ed397e32-43fb-48a0-a09a-ec358587d24f.png">

In Windows,

<img width="701" alt="RoundRectWindows" src="https://user-images.githubusercontent.com/102580874/167075614-84376ca9-6e0d-420a-a7dc-f64c0d754fff.png">

### Steps to Reproduce

1.Unzip the sample project Below
[RoundRectSample.zip](https://github.com/dotnet/maui/files/8638304/RoundRectSample.zip)

2.Run the sample

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 9.0

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by v-longmin** [comment]
On Android:
![image](https://user-images.githubusercontent.com/40230425/167085867-8b45b473-49c6-44dd-9616-79788aad53b6.png)
On Windows:
![image](https://user-images.githubusercontent.com/40230425/167085952-baf7a1df-82b4-45d4-b089-8d03b472549e.png)

**Comment by Ahamed-Ali** [comment]
> On Android: ![image](https://user-images.githubusercontent.com/40230425/167085867-8b45b473-49c6-44dd-9616-79788aad53b6.png) On Windows: ![image](https://user-images.githubusercontent.com/40230425/167085952-baf7a1df-82b4-45d4-b089-8d03b472549e.png) That's all different with above result.

Now unzip again and check with that

**Comment by v-longmin** [comment]
Verified repro on Windows10 & Android 12.0 with the above project.
