### ISSUE TITLE
ScrollView does not scroll with Flexlayout as a child

### ISSUE THREAD

**Issue by scara1701** [dotnet/maui#6881]
### Description

When placing a flexlayout as a child for a scrollview scroll does not seem to work.
When using another child such as stacklayout there is no issue.

### Steps to Reproduce

![2022-05-06_08-01-20](https://user-images.githubusercontent.com/31825690/167076442-a92645b1-b596-461d-950d-654effa2af5d.gif)

Does not scroll
`
    <ContentPage.Resources>
        <Style x:Key="DashboardButton" TargetType="Button">
            <Setter Property="Margin" Value="5" />
            <Setter Property="HeightRequest" Value="200" />
            <Setter Property="WidthRequest" Value="200" />
        </Style>
    </ContentPage.Resources>
    <ScrollView>
        <FlexLayout AlignItems="Start" JustifyContent="Start" Margin="20,0" Wrap="Wrap" VerticalOptions="Start" >
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
        </FlexLayout>
    </ScrollView>
`

Does scroll

`
    <ContentPage.Resources>
        <Style x:Key="DashboardButton" TargetType="Button">
            <Setter Property="Margin" Value="5" />
            <Setter Property="HeightRequest" Value="200" />
            <Setter Property="WidthRequest" Value="200" />
        </Style>
    </ContentPage.Resources>
    <ScrollView>
        <StackLayout>
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
            <Button Style="{StaticResource DashboardButton}" />
        </StackLayout>
    </ScrollView>
`

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 10.0.17763.0, Android 10

**Comment by v-longmin** [comment]
Verified repro on VS 17.3.0 Preview 1.0 [32427.505.main]. Repro with above code.

**Comment by shimingsg** [comment]
verified on windows and android with 17.3.0 Preview 2.0 [32506.315.main], not repro. close it. feel free to open new issue if you still hit this failure with same/newer environment.

**Comment by pulimento** [comment]
@shimingsg that preview is not yet publicly available, right?
