### ISSUE TITLE
Title in flyoutitem not visible

### ISSUE THREAD

**Issue by scara1701** [dotnet/maui#6882]
### Description

On Windows the Title of ShellContent is not visible in the flyoutmenu.
It does work on Android.

### Steps to Reproduce

![afbeelding](https://user-images.githubusercontent.com/31825690/167078327-9dd01f2b-a292-42a5-8569-1e39b7b5cd8b.png)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.17763.0

**Comment by v-longmin** [comment]
@scara1701 Could you share your repro code or project for us? Thanks.

**Comment by scara1701** [comment]
Hi,
I've uploaded a project to github.

https://github.com/scara1701/Bugged.Materiaalbeheer.ClientApp

I believe it is caused due to me calling a MSAL dialog during the creation of my ViewModel.
If I skip the dialog, the items are visible in the flyout.

ViewModel/LoginViewModel -> comment out the if statement in the create routine.

**Comment by v-longmin** [comment]
Verified repro on VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[Bugged.Materiaalbeheer.ClientApp-master.zip](https://github.com/dotnet/maui/files/8638812/Bugged.Materiaalbeheer.ClientApp-master.zip)

**Comment by jfversluis** [comment]
Might have something to do with #6033?

But if this still reproduces on main we need to have a look.

**Comment by KarlSearl** [comment]
having this issue after adding login page within shell.

![image](https://user-images.githubusercontent.com/64684177/169333079-cf689530-fa1a-43d7-9e83-6adab1ab8d32.png)

forcing a refresh ( added FlyoutWidhtafter the flyout is rendered) and hitting hot reload

![image](https://user-images.githubusercontent.com/64684177/169333271-da1b007b-3d5f-4c8b-8815-e6712bdd3a46.png)

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 2.0. Not repro on windows with above project.
[Bugged.Materiaalbeheer.ClientApp-master.zip](https://github.com/dotnet/maui/files/8638812/Bugged.Materiaalbeheer.ClientApp-master.zip)
 ![image](https://user-images.githubusercontent.com/82450723/234775291-8098a3ff-b070-4997-a071-0497ccf3f085.png)
