### ISSUE TITLE
StreamImageSource doesn't work on Image Control in Windows

### ISSUE THREAD

**Issue by BharanikhumarSR** [dotnet/maui#6888]
### Description

I am using StreamImage Source to save rendered objects into ImageSource by converting from byte[] to Stream. But after updating to RC, I have faced a breaking issue with Image control. When I tried setting StreamImageSource to the source of my Image control, the image is not visible. Setting URI or File image source types works as expected. 

Note :-  I have raised this issue previously for both android and windows and it was mentioned as fix for android alone (https://github.com/dotnet/maui/issues/6231)

**XAML**
```
 <ContentPage.Content>
        <Image  x:Name="imageControl"
                    WidthRequest="400"
                    HeightRequest="400"
                    HorizontalOptions="Center" />
 </ContentPage.Content>

```

**C#**
```
public partial class Sample : ContentPage
{
    public void Sample()
    {
            InitializeComponent();

           //Converting the default dotnet image to stream
            var assembly = this.GetType().GetTypeInfo().Assembly;
            Stream stream = assembly.GetManifestResourceStream("_YOURSAMPLENAME_.Resources.Images.dotnet_bot.svg");

            if (stream != null)
            {
                imageControl.Source = ImageSource.FromStream(() => stream);
            }
    }
}
```

### Steps to Reproduce

1. Create a new Maui Application
2. Add Image control to the content page.
3. Create the default `dotnet_bot.svg ` image loaded in the assembly into Stream source
4. Set the Stream to the source of the Image control added.
5. See that no image is rendered.

_Note: Make sure you set the **Build Action** of the image to **EmbeddedResource** to reproduce this._

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Preview 13

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No

**Comment by Redth** [comment]
There was a bug around this which is fixed in the upcoming RC3 release, however I think your issue is that you are trying to load a .svg into the image source which is not supported.  Only bitmaps are supported directly and you should use `MauiImage` build action on your svg to produce png's automatically at build time if you want to load them as an image source.

**Comment by BharanikhumarSR** [comment]
Hi @Redth ,
I have given this above SVG conversion for sample purpose, the actual issue is when I try to set a Stream Image source to a control, it doesn't load on Image control.

**Comment by Redth** [comment]
I get that the SVG is in the sample, but there's a reason that the SVG is not EmbeddedResource and is MauiImage instead.  At build time we have a build task that converts the vector into a bitmap for all of the appropriate display densities for each platform, to be included in your app as a .png file.

You can certainly embed the svg into the assembly and load the file, but the image control and image source doesn't know how to load and process that data, so no image will be displayed.

**Comment by BharanikhumarSR** [comment]
Hi @Redth ,
Yeah, I get that, but what I'm trying to portray is that I'm rendering a signature on windows native CanvasRenderTarget object. Later to display on Image control, I'm converting rendertarget to StreamImageSource as below. But when setting this stream image source to image control, it doesn't display. 

** Windows native **
```
 byte[] bytes = canvasRenderTarget.GetPixelBytes();
                var stream = new InMemoryRandomAccessStream();
                var encoder = await BitmapEncoder.CreateAsync(BitmapEncoder.PngEncoderId, stream);
                encoder.SetPixelData(BitmapPixelFormat.Rgba8, BitmapAlphaMode.Straight, 400, 400, 96, 96, bytes);
                await encoder.FlushAsync();

                imageSource = ImageSource.FromStream(() => new MemoryStream(bytes));

```
** PCL **
`imageControl.Source = imageSource;` - This doesn't gets displayed.

**Comment by Redth** [comment]
I believe this was the bug fixed for RC3 I was referring to.  Please file a new issue once RC3 is released if you still are able to repro there (with a zip of the repro sln/project too please).

**Comment by BharanikhumarSR** [comment]
Sure, Thanks.
