### ISSUE TITLE
[Enhancement] Track Windows handlers WIP in the repo along with other platforms.

### ISSUE THREAD

**Issue by bkaankose** [dotnet/maui#689]
## Summary
WinUI slowly introducing itself to the MAUI and soon or later Windows handlers must be ported as well like other major platforms. Having a good progress side by side with other platforms as we get closer to .NET 6 launch, Windows platform **must not** stay behind compared to other platforms.

This is not only about WinUI itself, but it's a huge gain in terms of Microsoft reputation. During the times as we are changing '**WPF,Win32,UWP**' apps to '**Windows**' apps and '**mobile development by XF**' to '**multi platform application development by MAUI**', Microsoft needs to present **'We are not behind in our own platform anymore'** **_with strong speech_**.

In order to speed up the development process, we need to keep track of in progress handler work and contributions to WinUI part of MAUI. Sooner we start doing this is better. It will also eliminate conflicting contributions. 

I'd recommend starting by editing existing PR Handler Guidelines and opened issues in PR Handlers Backlog project. Open for suggestions.

**Comment by Redth** [comment]
https://github.com/dotnet/maui/wiki/Status tracks WinUI progress too :)
