### ISSUE TITLE
iOS startup time of application

### ISSUE THREAD

**Issue by NielsKnaap** [dotnet/maui#6894]
### Description

I have migrated my existing Xamarin.forms application to .NET MAUI and noticed a big difference in starting time of the app on a iOS device. The Xamarin application will startup in 4s +/- and the .NET MAUI application takes 14s +/-.

When I create a new Xamarin.forms and .NET MAUI project (with the xamarin.forms flyout template and .NET MAUI Application template) and run them on the iOS device I get the same results.

On the other hand, I do see an accelerated startup when I run the same project on a android device.

iOS device used:
iPhone 7
iOS 15.4.1

### Steps to Reproduce

1. File -> New -> Project -> .NET MAUI APP (Preview)
2. Setup bundle signing
3. Run application (debug/release with debugger or without.. Doesn't really matter)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4.1

**Comment by SarthakGz** [comment]
Still for debugging mode also 14 second is too much I think.

**Comment by jfversluis** [comment]
I agree, as I already mentioned. I just want to verify that this is not a problem in production, that is most important I would say. If that's the case it's not great and we need to look into it, but at least your end-users won't be impacted.

**Comment by NielsKnaap** [comment]
Hi @jfversluis,

Thanks for your reply. I have now published the project and loaded the ipa on the iphone. The boot time is now much faster!

It might be an idea to temporarily highlight this tip somewhere. When I looked for it I couldn't find any information.

Thanks again!

**Comment by jsuarezruiz** [comment]
> Hi @jfversluis,
> 
> Thanks for your reply. I have now published the project and loaded the ipa on the iphone. The boot time is now much faster!
> 
> It might be an idea to temporarily highlight this tip somewhere. When I looked for it I couldn't find any information.
> 
> Thanks again!

What is the current startup time?. If you want can share a small sample where reproduce the issue to investigate more, if the time now is similar or better than Xamarin.Forms, that is fine and we can close the issue.
