### ISSUE TITLE
[Question] Linux Support

### ISSUE THREAD

**Issue by Yaroslav08** [dotnet/maui#69]
Will there be full linux support?

**Comment by dhindrik** [comment]
They have said that the official platforms maintained by Microsoft is iOS, macros, Android and Windows. The we have Samsung that will maintain Tizen. Other platforms will be maintained by the community.

**Comment by Yaroslav08** [comment]
@dhindrik, understood thanks

**Comment by jsuarezruiz** [comment]
Thanks for the answer @dhindrik.  Yes, the official platforms maintained are iOS, macOS, Android and Windows. Then, we have Tizen maintained by Samsung and other platforms (Linux for example) maintained by the community.

<img width="911" alt="maui-platforms" src="https://user-images.githubusercontent.com/6755973/82532355-7d902680-9b41-11ea-8abe-a81d2b04d4b9.png">

**Comment by KrisSiegel** [comment]
If I could tack on a similar question: how well fleshed out will it be to add additional platforms that the community can maintain? Is there a spec already for that?

Basically I'm curious if I wanted to extend support to another platform, will I end up needed to change the code within the main repo or will I be able to provide my platform implementation separately (so I won't need to maintain a MAUI fork)? I was going to dig into the repo but with so many specs still being decided I wasn't sure the current code would be representative of the final architecture for additional platform support.

**Comment by awulkan** [comment]
I also wonder the same as KrisSiegel. Google is working on Fuschia for example, which Flutter will support. I think it's probably a good idea for MAUI to explore support for that OS as well when it's nearing a more usable state.

**Comment by Tembocs** [comment]
Linux support should be officially supported because it has a lot of potential in years to come.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
If MacOS is officially supported, I guess Linux support is not that hard, right? If so, why not take the responsibility and support it officially? Qt has a long history of Linux support and I believe some people will go for Qt if cross platform really matters for them.

**Comment by GeraudFabien** [comment]
Linux is not that easy. It's not one OS and not one UI. Console support is hard for linux GUI is harder. 
As far i know QT support is done by community. So it's not that different than MAUI support.
