### ISSUE TITLE
Is there a prescribed way to include generated content files as static assets?

### ISSUE THREAD

**Issue by jimmylewis** [dotnet/maui#6904]
### Description

This is basically a request for clarification as to how #6709 should be resolved by libman, but the question applies generally for any content files that are generated during the build.  In other publishing build pipelines (WebSdk, and before that the Web Publish Pipeline for .NET Framework-based web projects), we've had well-defined points in the build to create new content files and ensure they are included during publish.  This is often on issue on clean builds (e.g. CI), because on incremental builds, the first build will create the assets, and subsequent builds will include the files from disk when MSBuild items are initially resolved at the start of the build.

The bottom line of what I want answered:
* Before which target do these files need to be added?
* What ItemGroup do they need to be added to?
* Do I need to worry about duplicates (e.g. on incremental builds when the file exists on disk, but might be regenerated again)?

Lastly, this request is not specific to web assets (wwwroot), it could be applied to any other form of static asset.  I just want to make sure we're not biasing a solution based on my example. 😉

### Steps to Reproduce

Repro:
1. git clone https://github.com/jimmylewis/MauiGeneratedContentRepro
2. Build and run the app (from clean build)
3. Navigate to the Fetch data page

Expected:
Weather summary should contain an emoji.

Repro continues:
4. Stop the app, then build and run again and repeat step 3

Expected == Actual:
Weather summary now contains an emoji.

To reset the repro, delete the wwwroot\css\forecast.css file from the project.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

N/A this is a build issue not a runtime issue

### Did you find any workaround?

The workaround specified in #6709 didn't work for me, so I found an alternative.  I changed my target to:
```
<Target Name="GenerateTheMagicalContentFiles"
        BeforeTargets="StaticWebAssetsPrepareForPublish">
  <Copy SourceFiles="..\GeneratedContentFiles\forecast.css" DestinationFolder="wwwroot\css" />
		
  <ItemGroup>
    <Content Include="wwwroot\css\forecast.css" />
  </ItemGroup>
</Target>
```
The changes were: 
* change BeforeTargets to StaticWebAssetsPrepareForPublish.  (Alternatively, I think I could add it to `$(StaticWebAssetsPrepareForPublishDependsOn)`).
* include the generated file as `@(Content)`.

This works, but is it *the right way* to do it?

**Comment by v-longmin** [comment]
Verified repro on Windows 10 with repro project:
[MauiGeneratedContentRepro-main.zip](https://github.com/dotnet/maui/files/8644259/MauiGeneratedContentRepro-main.zip)

**Comment by javiercn** [comment]
@jimmylewis thanks for following up.

Here are some answers in the context of Blazor:
* Before which target do these files need to be added? `ResolveReferences` is a good place since it runs early enough for other components to pick the generated assets.
* What ItemGroup do they need to be added to? `Content` as that's the item group other parts of the pipeline look to discover web assets.
* Do I need to worry about duplicates (e.g. on incremental builds when the file exists on disk, but might be regenerated again)?
  * Depends on how you are doing this, but if you are using a glob, I would say yes.

If you want this to work outside of the context of a Blazor Maui app, then things are trickier and you'll have to run before several platform specific targets and add the items to the `MauiAsset` item group. These are the ones that we run before in the context of Blazor:
```
* GetMauiItems
* ResizetizeCollectItems
* CollectBundleResources
* CollectHotRestartBundleResources
* _CheckForContent
```

**Comment by jimmylewis** [comment]
@javiercn thanks for the list.  With some tweaking and investigating, I found that:
* _CollectBundleResources (with the _ prefix) doesn't run on all platforms, nor does _CheckForContent.  They run on some platforms, and the others report that the target is not defined in the project.  Plus, since they start with an underscore, convention is that these are private and should not be referenced externally.
* CollectHotRestartBundleResources isn't defined at build time (nor with a _ prefix either).  All platforms reported the target was not defined in the project.
* Using `BeforeTargets="GetMauiItems;ResizetizeCollectItems"` seemed to be sufficient.  ResizetizeCollectItems is run by default on each platform currently defined.

Since libman can be used for any asset and any project type, I'm going to move ahead with this solution.
