### ISSUE TITLE
[Entry] Avoid transforming the text when `IsPassword` is set to true

### ISSUE THREAD

**Issue by SotoiGhost** [dotnet/maui#6906]
### Description

If you set `IsPassword="True"` and `TextTransform="Uppercase "`, the input text will be transformed. Is this the desired effect?

On Windows this is avoided; if `IsPassword` is enabled, the `TextTransform` property is ignored.

https://user-images.githubusercontent.com/5924210/167217594-25fb649e-2164-45dd-a98d-319085ab091e.mp4

https://user-images.githubusercontent.com/5924210/167218004-e04cd26e-f840-479e-9551-7fa3eecc34c2.mov

### Steps to Reproduce

* Add the following Control:

``` xml
<Entry 
    IsPassword="True"
    TextTransform="Uppercase" />
```

* Test the control.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15.4, Android 12

**Comment by v-longmin** [comment]
Verified not repro on iOS15.4 & Android 12.0. Not repro with above code.

**Comment by SotoiGhost** [comment]
@v-longmin I'm new on this heh... what are the next steps to follow if something is not repro?
