### ISSUE TITLE
On Windows you still cannot execute an application without running it from Visual Studio

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#6934]
### Description

Publish an application for Windows.
Try to click on the .exe or run it from commandline. -> nothing happens in both cases. This even happens on the developer machine

In Eventviewer you see:
Application: mauirc2delme.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
   at mauirc2delme.WinUI.Program.XamlCheckProcessRequirements()
   at mauirc2delme.WinUI.Program.Main(String[] args) in C:\Users\Roger\source\repos\mauirc2delme\mauirc2delme\obj\Release\net6.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.g.i.cs:line 28
   
   
  Note: Microsoft.ui.xaml.dll is not in the publish folder

### Steps to Reproduce

1. Create a new app from template (dotnet new maui -n myapp)
2. cd myapp
3. dotnet publish -f net6.0-windows10.0.19041.0 -c Release
4. go to the publish directory
5. click on the .exe file
6. Check EventViewer - Windows Protocols - Application

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 21H1

### Did you find any workaround?

No

**Comment by rogerbriggen** [comment]
I found https://github.com/microsoft/WindowsAppSDK/discussions/2391

if adding
<WindowsPackageType>None</WindowsPackageType>
<WinUISDKReferences>false</WinUISDKReferences>
to the project it still don't run but in Eventviewer there is:

Application: mauirc2delme.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Es wurde keine Übereinstimmung für den angegebenen Schlüssel im Index gefunden. (0x80070491)
Stack:
   at System.Environment.FailFast(System.String)
   at Microsoft.Windows.ApplicationModel.DynamicDependency.BootstrapCS.AutoInitialize.AccessWindowsAppSDK()
   at <Module>..cctor()

**Comment by jfversluis** [comment]
This is being tracked in #3166 

Right now we only support publishing to an MSIX and running it that way. This process can be found in the docs: https://docs.microsoft.com/dotnet/maui/windows/deployment/overview
