### ISSUE TITLE
Shell Navigation with Models

### ISSUE THREAD

**Issue by Mariselvam93** [dotnet/maui#6935]
### Description

Use a Model Class instead of using Query Property to pass data to a page.

### Public API Changes

In order to facilitate the new Navigation api, an object is added to the parameters of the GoToAsync call.

var model = new MyModel();
await Shell.Current.GoToAsync("PAGE_URI", model); // call GoToAsync() using a Model Class

### Intended Use-Case

This new feature could be useful for passing many complex data between pages, without having to pass all the data as strings.

**Comment by Mariselvam93** [comment]
@jfversluis

**Comment by jamesmontemagno** [comment]
This was added :) https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation#pass-data check it out

**Comment by jfversluis** [comment]
Going to assume this covers your needs @Mariselvam93 if not, please provide is with more detail on what you would like to see. Thanks!

**Comment by Mariselvam93** [comment]
Yes. It covers my need. Thank you for support. @jfversluis and @jamesmontemagno
