### ISSUE TITLE
NavigationPage - InsertPageBefore forces visibility of the NavigationBar

### ISSUE THREAD

**Issue by pijnappel** [dotnet/maui#6936]
### Description

When trying to put a page in front of another, the navigation bar is forced to be visible. `NavigationPage.HasNavigationBar="False"` will not work to hide it permanently.

Repo: [here](https://github.com/pijnappel/Maui_InsertPageBeforeForcesNavigationBar)

### Steps to Reproduce

1. Create a Maui App
2. Add Navigation Page and pages
3. Put `NavigationPage.HasNavigationBar="False"` in the top pages XAML
4. Put another page before that using `Navigation.InsertPageBefore`
5. See the Navigation bar appearing

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9, 11, 12

### Did you find any workaround?

No workaround yet

**Comment by Tederean** [comment]
Windows 10 is also affected.

**Comment by kristinx0211** [comment]
verified repro on windows android with 17.3.0 Preview 2.0 [32515.5.main].

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 5.0. Not repro on android platform with sample project.
[Maui_InsertPage.zip](https://github.com/dotnet/maui/files/12246533/Maui_InsertPage.zip)
NavigationPage.HasNavigationBar="**False**":
![6936](https://github.com/dotnet/maui/assets/77434865/a81df9a1-cd3f-40b7-96c7-e6d6eb00a24e)
NavigationPage.HasNavigationBar="**True**":
![6936-1](https://github.com/dotnet/maui/assets/77434865/86fe69b8-a181-433f-b4f4-ded153dd186c)
