### ISSUE TITLE
No output from console.Writeline or Logger.LogInformation in MAUI App

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#6941]
### Description

I have a Blazor Hybrid MAUI App using default template.
```
_Logger.LogInformation("ABCDEFG");
Console.WriteLine("jgjhj");
```

I inject Logger in Blazor Page using
```
 [Inject]
 public ILogger<Index> _Logger { get; set; }
```
I can't see any out put anywhere
I checked
1) F12 tools when running for Windows
2) Output of visual Studio
3) Device Log via Visual Studio

### Steps to Reproduce

Create Blazor Hybrid App using default project template.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.2.0 Preview 6.0

### Did you find any workaround?

None

### Relevant log output

```shell
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.2.0 Preview 6.0


C:\Users\admin>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.300-preview.22204.3
 Commit:    4f23310c97

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300-preview.22204.3\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]
  6.0.300-preview.22204.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
```

**Comment by Redth** [comment]
@eerhardt did you find a logger that does the right thing everywhere? I remember we talked about this at one point.

I think the simple answer for now is you need to use the correct call depending on the platform.  System.Diagnostics.Debug.WriteLine I believe on windows, but Console.WriteLine will work on Android/iOS

**Comment by eerhardt** [comment]
> did you find a logger that does the right thing everywhere? 

No, unfortunately I didn't. The `Console` logger isn't appropriate for mobile apps (or technically even for console apps 😕, see https://github.com/dotnet/dotnet-api-docs/issues/7904). And the `System.Diagnostics.Debug.WriteLine` logger doesn't send the logs to `logcat` on Android.

Maybe Maui should create a Logger that is appropriate for all its intended targets? (i.e. it logs to all the right places on Windows, iOS, mac, Android, etc.)

**Comment by mattleibow** [comment]
Didn't we have a fallback logger for this? So if no logger was provided we should attach that - and it only needs to work in DEBUG mode as well.
