### ISSUE TITLE
Blazor-MAUI Nav-Menu funky visuals on resize

### ISSUE THREAD

**Issue by JuggernOtt81-USI** [dotnet/maui#6942]
### Description

weird visuals on bottom of nav-menu

### Steps to Reproduce

1. new .net Maui Blazor app
2. add lots of items (enough to fill window (in windows)) to nav-menu include some sub-menus
3. when the sub menus expand, nav-menu visuals break at the bottom
4. (have sometimes seen same visual behavior on window resize)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

windows 11, latest as of 5/2/2022

### Did you find any workaround?

my only work around was to have fewer nav-menu items that linked to subject heading pages which contained the would-have-been-sub-links to the other content

### Relevant log output

```shell
n/a
```

**Comment by deepx** [comment]
I made a dotnet new Hybridmauiapp start the windows one. When i fill up the Nav-Menu (copyed the Fetchdata-Link multiple times) and scroll down it removes the background of the Menu as you can see on the screenshot. 

![Screenshot_9](https://user-images.githubusercontent.com/3179474/167433134-bfbd7dcc-d7ef-4ec1-a7a5-7c2957ea8aea.png)

**Comment by javiercn** [comment]
@JuggernOtt81-USI thanks for contacting us.

I think that's just some CSS in the template that is not prepared to handle that many items. You might want to check with the browser dev tools the different boxes for the elements rendered on the page and make the necessary adjustments on the CSS.

**Comment by deepx** [comment]
@javiercn 
Yes, i tried the same with the blazorwasm-template and the same happens (screenshot). so i guess its a adjust of css needed.

![Screenshot_1](https://user-images.githubusercontent.com/3179474/167454895-22c56376-6fe7-4b41-b576-1dfbc704ff28.png)

**Comment by mkArtakMSFT** [comment]
Thanks for confirming that, @deepx.
There is an existing issue for fixing this in Blazor project template here: https://github.com/dotnet/aspnetcore/issues/41050
A community member has already proposed a fix for that, which you can take a look and apply to your project and that should resolve this too. We will address this later in the template.

**Comment by JuggernOtt81-USI** [comment]
wow! you guys are ON IT! 🥇
