### ISSUE TITLE
ListView not scrolling, not selecting after update, extremely slow to update

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#6943]
### Description

Please see linked reproduction project and video.
On both Android and iOS, starting with a tabbed page with a listview on each page, the:

1. ListViews do not scroll
2. Initially, the ListViews allow one to select an item (turning orange), but once the list is updated, on Android, the selection does not happen anymore (I'm just adding one item to List1 for this demonstration).
3. There are 400 items per list (which sounds like a lot), but I was expecting the component to handle it better. The display updates are extremely slow, demonstrated by changing between lists by selecting different tags.

The sample project can be found here:

https://github.com/hbraasch/TabbedListViewTester.git

The demonstration video can be found here:

https://github.com/hbraasch/TabbedListViewTester/blob/master/ListViewProblem.mp4

### Steps to Reproduce

1. Load and run the project using Visual Studio
2. Switch between tabs to see how slow it reponds
3. Try to scroll any list, it does not
4. Change to List1 (Tab), select any item and notice it changes to [yellow]
5. Press [Add] button. A new item will appear in the list at the top.
6. Try to select any item in the list. It never changes to [yellow]

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 12 - API 30/31, iOS 15.4

### Did you find any workaround?

None

**Comment by KarlSearl** [comment]
Hi @hbraasch  In the short term, whilst this gets looked in,  I would personally suggest collection view, as it offers a very simple way to add Lazy loading (paging). 

I am not sure what the long term plans are, seems harder to keep both ListView and collectionView (from a maintenance perspective). Good luck, hope it gets fixed.

**Comment by hbraasch** [comment]
Hi @KarlSearl 

Thanks for the suggestion. Much appreciated.

I've replaced one of my ListViews with a CollectionView and did see some improvement. But... it unfortunately still does not scroll on Android. Everthing using the CollectionView works fine on iOS.

So, for the developers please... There is ALSO a problem with CollectionView...
Here is the updated reproduction project:

https://github.com/hbraasch/TabbedListViewTester.git

And here is a short video to demonstrate the issue:

https://github.com/hbraasch/TabbedListViewTester/blob/master/CollectionViewProblem.mp4

Regards

**Comment by hbraasch** [comment]
I now notice its got to do with the layout, having the buttons and the listview inside a VerticalStackLayout.
If the tab page only contains the listview, scrolling starts to work.

**Comment by samhouts** [comment]
Could be related to #6584

**Comment by hbraasch** [comment]
For what its worth, for the ListView issue, I've now noticed that when I replace the [ViewCell] with a [TextCell] in the DataTemplate section (I can do this in this case, because I only need to display a string), scrolling starts working again.
I followed this route as a temp solution because I saw in the logs it complains the [ViewCell] renderer is incompatible 
[Microsoft.Maui.Platform.ToPlatformException: Microsoft.Maui.Controls.Handlers.Compatibility.ViewCellRenderer found for Microsoft.Maui.Controls.ViewCell is incompatible]

**Comment by PureWeen** [comment]
@hbraasch the problem on a few of your tabs is that you are using a Vertical Stack Layout which allows for infinite height. The ListView doesn't know what size to measure to so it can't constrain itself and be scrollable

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/5375137/170461574-0fac37f8-4d66-4571-b56d-9267efaeb608.png">


Your other issues should be resolved by this PR
https://github.com/dotnet/maui/pull/7485

**Comment by hbraasch** [comment]
Thanks

I'm now aware of the problem when having a ListView inside a StackLayout.

I'll wait for the next release to see if the other issues are resolved.
