### ISSUE TITLE
[ContentProperty] ignored on Layouts

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#6944]
### Description

Mapping the ContentPropertyAttribute of the child class to a different property not working if the base class is a layout control. The base class children property is getting set.

[MauiApp8.zip](https://github.com/dotnet/maui/files/8648769/MauiApp8.zip)

Base Class:
```
public class CustomControl : Grid
    {

    }

```
Child class:
```
[ContentProperty("ChildContent")]
    public class ChildCustomControl : CustomControl
    {
        /// <summary>
        /// Identifies the <see cref="ChildContent"/> bindable property.
        /// </summary>
        /// <value>
        /// The identifier for <see cref="ChildContent"/> bindable property.
        /// </value>
        public static readonly BindableProperty ChildContentProperty =
            BindableProperty.Create(nameof(ChildContent), typeof(View), typeof(ChildCustomControl), null, BindingMode.OneWay, null, OnContentPropertyChanged);

        /// <summary>
        /// 
        /// </summary>
        public View ChildContent
        {
            get { return (View)this.GetValue(ChildContentProperty); }
            set { this.SetValue(ChildContentProperty, value); }
        }

        /// <summary>
        /// Invoked whenever the <see cref="ChildContentProperty"/> is set for SfContentView.
        /// </summary>
        /// <param name="bindable">The bindable.</param>
        /// <param name="oldValue">The old value.</param>
        /// <param name="newValue">The new value.</param>
        private static void OnContentPropertyChanged(BindableObject bindable, object oldValue, object newValue)
        {
        }
    }
```

### Steps to Reproduce

Run the attached sample.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Windows 19041

### Did you find any workaround?

No

**Comment by StephaneDelcroix** [comment]
could you share the code/xaml snippet that assign the content ?

**Comment by StephaneDelcroix** [comment]
is this somehow related to #3745 ?

**Comment by PaulAnderson02** [comment]
`<local:ChildCustomControl>
                <Image
                    Source="dotnet_bot.png"
                    SemanticProperties.Description="Cute dot net bot waving hi to you!"
                    WidthRequest="250"
                    HeightRequest="310"
                    HorizontalOptions="Center" />
            </local:ChildCustomControl>`

Just have a breakpoint in ContentChanged method and it wont get hit and the Content property will be null.

**Comment by StephaneDelcroix** [comment]
@hartez Is it possible that layouts (like Grid) in MAUI implements `IEnumerable` and contains a `Add(View)` method, and that it wasn't the case in XF ?
