### ISSUE TITLE
Offering help porting the Xamarin.forms tutorial over to .NET MAUI

### ISSUE THREAD

**Issue by bryancass** [dotnet/maui#6954]
### Description

I just wanted to offer my help if you have a team that is porting the [Xamarin tutorial](https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/intro) to the .NET MAUI product.  I want to develop a commercial mobile app for a commercial web site I created and can help create or test the .NET MAUI tutorial in the process of learning that platform.

Please file this under label 'area/docs'.

### Public API Changes

None.

### Intended Use-Case

It seems the Xamarin tutorial could be converted for use as a MAUI tutorial.  I am interested in learning MAUI and thought maybe someone new to the code could contribute from that perspective.

**Comment by davidbritch** [comment]
Hi @bryancass 

Thanks for your offer. It's already been ported: https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/intro

**Comment by bryancass** [comment]
Oh excellent, thanks David!  I'll go through it and let you know if I find any issues.

**Comment by bryancass** [comment]
I went through it, but it's basically showing how to download VS 2022, how to install .NET MAUI, and then just creating the Hello, World app.  How about we tackle porting over this one next?

https://docs.microsoft.com/en-us/learn/modules/create-a-mobile-app-with-xamarin-forms/1-introduction

**Comment by davidbritch** [comment]
Hi @bryancass 

Again, thanks for your offer - much appreciated! The Xamarin MSLearn modules have been ported to .NET MAUI. They just haven't launched yet, but will hopefully be launching later this month.

**Comment by bryancass** [comment]
David, can you please direct me to the right place to ask questions on new .NET MAUI development?  For example, I am wondering since I have already developed a complete MVC web app in ASP.NET Core using SQL Server for data, and this new mobile app is kind of an extension of that web app, whether I should use .NET MAUI with Blazor?  I want to get started with the right tools so I don't end up 6 months into development and figure out I should have used something else.  :-)  Thanks!

**Comment by davidbritch** [comment]
Hi @bryancass 

[Discussions](https://github.com/dotnet/maui/discussions) and [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/dotnet-maui.html) are the best places to ask questions. Hope this helps!
