### ISSUE TITLE
Slider value property is ignored on initialization

### ISSUE THREAD

**Issue by duydang2311** [dotnet/maui#6957]
### Description

The slider's value is always set to its minimum value no matter what value is specified.

### Steps to Reproduce

1. Create a new `.NET Maui App (Preview)` project.
2. Add a `Slider` control to `MainWindow.xaml`.
```xaml
<Slider
    Maximum="225"
    Minimum="25"
    Value="100" />
```
3. Run the program. Observe the slider's value on initialization is set to minimum, instead of `100`.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.22000

### Did you find any workaround?

Simply put a delay on initialization before setting the value, e.g:
```csharp
<Slider
    Maximum="225"
    Minimum="25"
    Value="{Binding SliderValue}">
    <Slider.BindingContext>
        <vm:TestBindingViewModel />
    </Slider.BindingContext>
</Slider>
```
```csharp
public class TestBindingViewModel : INotifyPropertyChanged
{
    private int sliderValue = 100; // won't work
    public int SliderValue { /*property implement*/ }

    public event PropertyChangedEventHandler PropertyChanged;
    public BindingViewModel()
    {
        Task.Run(() =>
        {
            Thread.Sleep(0);
            App.Current.Dispatcher.Dispatch(() =>
            {
                SliderValue = 100;
            });
        });
    }
}
```

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Windows. Sample Project: [6957.zip](https://github.com/dotnet/maui/files/8656293/6957.zip)
