### ISSUE TITLE
Binding to App's Variables 

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#696]
Hi,

Please add a way to bind to variable inside the App.xaml.cs or whatever it is called in MAUI, something like this:

```
namespace MyApp
{
    public partial class App : Application
    {
        public static string my_name { get; set; }
        public static DateTime my_birthday { get; set; }

        public App()
        {

```

then in XAML:

<Label Text="{Binding App.my_name}" />
<Label Text="{Binding my_birthday, StringFormat='{0:MMMM dd}'}" />

Thanks,
Jassim

**Comment by Miksier** [comment]
Its called x:Static and here is some documentation:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions#the-xstatic-markup-extension
