### ISSUE TITLE
Alerts in Blazor and WebView on Windows do not look nice

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#6961]
### Description

![image](https://user-images.githubusercontent.com/1096616/167470946-a7b6c1f7-315c-4533-8027-db94ddade153.png)

![image](https://user-images.githubusercontent.com/1096616/167471036-b1bf6c56-46e9-43f1-9b7a-dbcfc015d836.png)

### Steps to Reproduce

Add a webview2 element and add some js to pop an alert.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Release Candidate 2 (current)

### Affected platforms

Windows

### Affected platform versions

all

**Comment by SteveSandersonMS** [comment]
Removing the Blazor label as we don't plan to change it there.

The consensus we established on the Blazor team is that this is simply how alert dialogs are rendered by WebView2, and it's not our business to override the default styling. The fact that it can get cropped is something that could be reported as an issue to WebView2.

**Comment by hartez** [comment]
@jfversluis Can you verify whether this is still an issue? And if so, can you report it to the WebView2 folks to we can get it moving along?

**Comment by jfversluis** [comment]
Cropping doesn't seem to be happening anymore so I think we're all good here for now.
