### ISSUE TITLE
[Enhancement] Introduce a new FlyoutDisplayOptions on Shell "DisplayAsChildren"

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/maui#6973]
### Description

When I enable FlyoutDisplayOptions="AsMultipleItems"  the main menu item disappears and the sub menu items do not appear indentent. This is because "AsMultipleItems" is just used to create groups based on different FlyoutItems but doesn't cause nesting of items. To enable the ability to nest FlyoutItems we should look at introducing an option FlyoutDisplayOptions="DisplayAsChildren"  that show the items as nested.

The items should appear under the menu item addons and be idented and not appear on the bottom bar.

   <FlyoutItem Title="Addons"  FlyoutDisplayOptions="AsMultipleItems" x:Name="addonsflayout" Icon="icon_about.png">
        <ShellContent Route="AddonsPage" ContentTemplate="{DataTemplate local:AddonsPage}" />
    </FlyoutItem>

### Public API Changes

I beleive the solution that @PureWeen  came up with was to have an item called DisplayAsChildren in the flyoutoptions.

The original XF Forms bug is here

https://github.com/xamarin/Xamarin.Forms/issues/13274

### Intended Use-Case

Many apps have child items and as such their should be an option in shell to have child items in the menus float under a main shell item for example

If one has 
Sales
    ----> Orders
    -----> Purchase Orders
    -----> More

At present their is no way of adding child menu items under shell this was meant to go in as an Enhancement but shane said he was thinking of other ways to best handle this.

**Comment by PureWeen** [comment]
@davidbuckleyni can we just keep one of these? https://github.com/dotnet/maui/issues/7345

**Comment by davidbuckleyni** [comment]
Closing as per @PureWeen  suggestions of #7345
