### ISSUE TITLE
macOS: Environment.GetFolderPath APIs return null

### ISSUE THREAD

**Issue by paratype-fonts** [dotnet/maui#6984]
### Description

Environment.GetFolderPath not working under macOS

### Steps to Reproduce

1. Under macOS, create a new Maui project: > dotnet new maui -n "MyMauiApp"
2. Open the project in Visual Studio 2022 (17 preview) for Mac
3. Add a few Environment.GetFolderPath calls:
	public MainPage()
	{
		InitializeComponent();
		var homeDir = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
		var appDir  = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
	}
4. Observe both return values are null

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.3 M1, Visual Studio 2022 (17 preview) for Mac

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Hey there, thanks for the report!

Unfortunately, this is something in the runtime, not .NET MAUI. See also here: https://github.com/dotnet/runtime/issues/68323
