### ISSUE TITLE
iOS publishing not picking up project runtime identifier

### ISSUE THREAD

**Issue by CodeBoop** [dotnet/maui#6992]
### Description

When attempting to publish an iOS app msbuild doesn't seem to find the runtime identifier in the project specified. Following error is presented when attempting to use the cl that has previously worked.

`C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.200-rc.2.191\targets\Xamarin.Shared.Sdk.Publish.targets(16,3): error : A runtime identifier must be specified in order to publish this proj
ect. [C:\Users\Chris\source\repos\MauiApp2\MauiApp2\MauiApp2.csproj]`

Here's a repo of one that did work, and now doesn't: https://github.com/CodeBoop/MauiApp2

I've ensured that the following line is in the project. 

```
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
	</PropertyGroup>

```

### Steps to Reproduce

Attempt to publish

### Version with bug

Release Candidate 3

### Last version that worked well

Release Candidate 2 (current)

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by jfversluis** [comment]
In addition please also provide the command that you are using to publish the app. Thanks!

**Comment by rajeshsws** [comment]
Hi 
Facing same issue , Also tried command line and pass in .csproject file as well . nothing working out.
![image](https://user-images.githubusercontent.com/48245007/167835914-9779a2e9-9807-444e-b31e-b3409822bb3a.png)

**Comment by CodeBoop** [comment]
@jfversluis  here's the command I've used

`dotnet publish -f:net6.0-ios -c:Release /p:ServerAddress=[address] /p:ServerUser=[user] /p:ServerPassword=[password] /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory=/Users/[user]/Library/Caches/Xamarin/XMA/SDKs/dotnet/`

I was able to successfully publish an app through the archive function using a xamarin forms app.

**Comment by rajeshsws** [comment]
Same result not working in .Net MAUI rc 3 .

**Comment by mattleibow** [comment]
The error is saying you can use ios for maccatalyst... I am wondering if the colon `:` between the `-f` is causing issues.

Try using `-f net6.0-ios -c Release -r ios-arm64`

Also, not sure why you need the RID as it should do them all in one package...

**Comment by DerPate2010** [comment]
I experienced the same issue with a new created project. I was able to get rid of the message using this command line:

`dotnet publish -f net6.0-ios -r ios-arm64 -c Release -p:TargetFramework=net6.0-ios `

It basically overrides the list of target frameworks in the project file to include iOS only. It is the "net6.0-maccatalyst" target that causes the error. I found the hint to this fix in the issues
https://github.com/xamarin/xamarin-macios/issues/14015
and
https://github.com/dotnet/sdk/issues/21877

**Comment by rajeshsws** [comment]
@DerPate2010 still not working , you might have tried in xamarin, please try in .net maui blazor rc 3 .Problem is IOS target framework is missing from target framework list when u check in publish app list.
Thank you

**Comment by rajeshsws** [comment]
Its working for me after connecting with I phone then its take run time identifier ios-arm64 and i am able to publish

**Comment by PureWeen** [comment]
https://github.com/xamarin/xamarin-macios/issues/15365#issuecomment-1169006363
