### ISSUE TITLE
[Android][iOS] OnDestroying method of the Window extended class is not called [Lifecycle]

### ISSUE THREAD

**Issue by antborari** [dotnet/maui#6993]
### Description

OnDestroying method of the Window extended class is not called.

Tested on Windows, Mac, Android and iOS.
Windows and Mac works fine.
Android and iOS doesnt work.

Class MauiWindow extended from Window. Override methods OnCreated and OnDestroying.
When inits the application, OnCreated is called.
When destroy the application, OnDestroying didn't called.

Edit1: window.Destroying(EventHandler) has the same behaviour as the OnDestroying() method.

[MauiApp1.zip](https://github.com/dotnet/maui/files/8662100/MauiApp1.zip)

### Steps to Reproduce

1. Download the attached VS 2022 solution and open it with VS 2022 preview with MAUI RC 2 workload installed.
2. Debug the application in Android and iOS, put a breakpoint into method OnDestroying from MauiWindow class.
3. Close the application.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15.4, Android 12

**Comment by jfversluis** [comment]
RC3 is just released, would you maybe be able to verify that it's still an issue there? :)

Thanks!

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android, not repro on Windows with above project.

**Comment by antborari** [comment]
window.Destroying(EventHandler) has the same behaviour as the OnDestroying() method, I have extended the issue with the EventHandler.

**Comment by PureWeen** [comment]
@antborari 

> When destroy the application, OnDestroying didn't called.

are you destroying the activity on Android by swiping the application away to close? 

OnDestroy isn't a reliable event on Android. 

https://developer.android.com/reference/android/app/Activity#onDestroy()

**Comment by VincentBu** [comment]
repro on Android simulator. meanwhile, OnDestroying is called on IOS.

**Comment by jitendrajadav** [comment]
Still, I am having issue any work around I needs to show local notification once application is going to close.

**Comment by jonathanpeppers** [comment]
This is working for me on Android after landing: https://github.com/dotnet/maui/pull/16045.

So, if someone wants to retest the other platforms after the next .NET 8 preview ships -- maybe it's fixed?
