### ISSUE TITLE
Is Maui.Graphics dead?

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6998]
### Description

Until now I thought Microsoft.Maui.Graphics is the graphics library for MAUI (the name suggests it I suppose?).
Also in MAUI tutorials on docs.microsoft.com, there is code used exclusively from this library when working with graphics in MAUI applications. https://docs.microsoft.com/en-us/dotnet/maui/user-interface/graphics/
Code for abstracting work with images is incomplete for probably every platform and for Windows, it seems that it's the most incomplete (I am talking about IImage implementation methods). For Android, it is not complete, either, but still, I have received suggestions in this repo to use parts of it - _("use IImageLoadingService")_ - which is not fully working neither for Android or Windows (because IImage implementations are not fully implemented, it is basically just a class which creates IImage for specific platform from Stream or a byte array).

There is probably last commit with any code update 2 months ago. Since then only package reference updates or non-functional fixes/updates.

https://github.com/dotnet/Microsoft.Maui.Graphics/commits/main?after=d3b2c35e902efbffbe40d6266d2344bdf239d59a+104&branch=main&qualified_name=refs%2Fheads%2Fmain

![image](https://user-images.githubusercontent.com/64279914/167660196-8b49f035-f110-4dc1-be0a-1e0fef209415.png)

What is the suggested library for graphics in MAUI if not this? 
Why is it in official MAUI documentation when it is not fully working and unsupported/experimental/abandoned/not-fully-implemented?
I can see that there is last milestone which says Preview 7. Was this library abandoned around this time and are the docs from Preview 7 and they are still presented as current and the suggested way to work with images even if there is already MAUI GA release coming?
https://docs.microsoft.com/cs-cz/dotnet/maui/user-interface/graphics/images (btw the code is old, I think that there is no such code as 

> Image loading functionality is provided by the `GraphicsService` class. Images can be loaded from a stream by the `LoadFromStream` method, or from a byte array using the `LoadImageFromBytes` method.

anymore).

Why is Maui.Graphics presented in official Microsoft documentation while the repository readme mentions that there is no official support and it is an experimental package?

Why when I post an issue about using Maui.Graphics in MAUI repo, I am redirected to the Maui.Graphics repo _**where nothing happens with the issues**_?

Thank you

### Steps to Reproduce

use graphics library in MAUI

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

all

### Did you find any workaround?

use a switch for every platform with implementing everything myself for every platform?? I thought that's what .NET MAUI removes

**Comment by jfversluis** [comment]
It is not dead, in fact, it's going to move in with us so that we can give it the attention it deserves! 

Also see: https://github.com/dotnet/maui/issues/7901
