### ISSUE TITLE
[Windows] Child controls of the grid are automatically resizing, with the size changes of parent Grid

### ISSUE THREAD

**Issue by Deepak1799** [dotnet/maui#6999]
### Description

Child controls of the grid are automatically resizing, with the size changes of parent Grid. Even if we set the Horizontal and Vertical options of the child element to "Start". The child size should not be changed until we explicitly changing it.

### Steps to Reproduce

1. Create a MaUI project.
2. Add a Grid control inside the content page.
3. Now add an Image as the child of Grid. 
4. Now change the size the of the Grid control at runtime (may be using a button clicks).
5. You can see the child also getting resized along with the parent. [If needed you can also test by setting the child's Horizontal and Vertical options as "start"]

I have attached the repro project to reproduce the issue below. 
[PinchToZoomWindows.zip](https://github.com/dotnet/maui/files/8663669/PinchToZoomWindows.zip)

**XAML Code [Complete]:**

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="PinchToZoomWindows.MainPage"
             xmlns:local="clr-namespace:PinchToZoomWindows">
    <VerticalStackLayout>
        <Button Text="Resize Grid" Clicked="Button_Clicked"/>
        <ScrollView HeightRequest="600" WidthRequest="1200">
            <Grid x:Name="MyGrid" 
                BackgroundColor="Gray" HeightRequest="600" WidthRequest="1200">
                <Image VerticalOptions="Start" HorizontalOptions="Start"
            Source="dotnet_bot.png" 
            SemanticProperties.Description="Cute dot net bot waving hi to you!"/>
            </Grid>
        </ScrollView>
    </VerticalStackLayout>
</ContentPage>

```

**xaml.cs [Complete]**
```
namespace PinchToZoomWindows;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}

    private void Button_Clicked(object sender, EventArgs e)
    {
		MyGrid.WidthRequest *= 1.25;
		MyGrid.HeightRequest *= 1.25;
    }
}

```
 

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

**Note:** This is not a workaroud. But this information might be helpful for the analysis

- This works in Android perfectly but not in Windows. 
- In Windows, it works when we explicitly set the "WidthRequest" and "HeightRequest" for the child control. it worked. But in my case I do not want to set the size explicitly. 

### Relevant log output

```shell
NA
```

**Comment by v-longmin** [comment]
Verified repro on windows with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[PinchToZoomWindows.zip](https://github.com/dotnet/maui/files/8665916/PinchToZoomWindows.zip)

**Comment by homeyf** [comment]
Verified this issue with Visual studio Enterprise 17.6.0 Preview 2.0. Not repro on windows with above project.
[PinchToZoomWindows.zip](https://github.com/dotnet/maui/files/8665916/PinchToZoomWindows.zip)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/82450723/235132228-d523f98f-3071-4599-8bdb-6c30e5e76a7f.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/82450723/235132354-2836f6b0-4e13-4c1e-9ecb-ef86f70a4f71.png)
