### ISSUE TITLE
CarouselView with direct ContentView items in XAML shows error

### ISSUE THREAD

**Issue by JosHuybrighs** [dotnet/maui#7000]
### Description

I am trying to setup a CarouselView in my ContentPage whereby the content items are defined as ContentView items (which have there layout and content completely defined in their own XAML file).
Like so:
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:RoutePlusPlus"
             x:Class="RoutePlusPlus.AppTourPage"
             Title="AppTourPage">
    <CarouselView>
      <CarouselView.ItemsSource>
        <x:Array Type="{x:Type ContentView}">
          <local:Intro1View/>
          <local:Intro2View/>
          <local:Intro3View/>
        </x:Array>
      </CarouselView.ItemsSource>
      <CarouselView.ItemTemplate>
        <DataTemplate>
          <ContentView Content="{Binding}"/>
        </DataTemplate>
      </CarouselView.ItemTemplate>
    </CarouselView>
</ContentPage>
```
The 3 views all have their own XAML file with a StackLayout in which there is an image and a couple of labels.

The first item shows correctly when the page is opened but then the app crashes with the following exception in Visual Studio:
`Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'`

I assume this is a bug? 

I am using VS2022, v17.2 Preview 6.
I assume I am using maui RC2 because Microsoft.Maui.Dependencies and Microsoft.Maui.Extensions both are 6.0.300-rc.2.5513.

### Steps to Reproduce

Create a basic maui app project.
Create a couple of ContentView XAML files.
Replace MainPage XAML content by the above listed page content.
Run the app.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11.0 (Pixel 5 emulator)

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
@rmarinho I think you fixed a couple with this error? Does that include this one?

**Comment by rmarinho** [comment]
yes i fixed this issue, that say using Loop feature with ContentViews as ItemSource will not work. because we can't have multiple handlers for 1 view. 

So if  @JosHuybrighs needs this should use  Loop="False" Or use DataTemplateSelector and change the ItemsSource to be some that and not "Maui Views".

**Comment by JosHuybrighs** [comment]
@rmarinho Setting Loop="False" indeed solves this.
I am afraid however that I, and probably other users as well, will not understand why this Loop property actually makes a difference. It seems that the documentation of CarouselView will need some explanation why suddenly in maui the ItemsSource of an items view poses restrictions on what type of items can be added whereas in xamarin forms, UWP, WinUI3 etc there is full freedom of what you can insert in the view.
Would a non-maui ContentView actually work in case of Loop="True"?

Anyhow, I am happy with your suggestion because I don't require a loop.
So, thanks for the prompt reply and help.
Much appreciated!

**Comment by rmarinho** [comment]
Thanks, you make a good point we need to make sure we expecify that on the Documentation. I m also not sure this worked on Xamarin.Forms.
If your ItemsSource is a Array of simple objects it would work fine.

No problem, thanks.

**Comment by JosHuybrighs** [comment]
Thanks, it could very well be that it also doesn't work on Xamarin.Forms since I am using the plugin PanCardView.CardsView there instead of Xamarin.Forms CarouselView.
