### ISSUE TITLE
Cannot publish freshly created MAUI app as documented

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#7003]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-publish-freshly-created-MAUI-app-/10029954)._

---
\[severity:I’m unable to use this version\]  
Following the instructions here: [https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview](https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview)  
after creating a MAUI App with the add project UI, results in this error:

```  
Build FAILED.

"C:\Code\Maui\MauiApp10\MauiApp10.sln" (Publish target) (1:2) ->
"C:\Code\Maui\MauiApp10\MauiApp10.csproj" (Publish target) (2:18) ->
(ResolvePackageAssets target) ->
  C:\Program Files\dotnet\sdk\6.0.300-preview.22204.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolut
ion.targets(267,5): error NETSDK1005: Assets file 'C:\Code\Maui\MauiApp10\obj\project.assets.json' doesn't have a targe
t for 'net6.0-windows10.0.19041'. Ensure that restore has run and that you have included 'net6.0-windows10.0.19041' in
the TargetFrameworks for your project. [C:\Code\Maui\MauiApp10\MauiApp10.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.99
  
```
repro sln here: https://github.com/Dbquity/MauiApp10

---
#### Lars Hammer on 5/4/2022, 01:05 PM: 

(private comment, text removed)
#### Feedback Bot on 5/4/2022, 07:10 PM: 

(private comment, text removed)

---
#### Lars Hammer solved on 5/4/2022, 01:48 PM, 0 votes: 

<p>[Workaround]<br>
Choosing the <code>Release</code> profile and <code>Windows Machine</code> as target in the Visual Studio UI and then building the project successfully produces a .msix - notice the extra <code>.0</code> in the target framework identifier <code>net6.0-windows10.0.19041.0</code>:</p>
<pre><code>Build started...
<span class="hljs-meta">1&gt;</span>------ Build started: Project: MauiApp10, Configuration: Release Any CPU ------
<span class="hljs-meta">1&gt;</span>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
<span class="hljs-meta">1&gt;</span>MauiApp10 -&gt; C:\Code\Maui\MauiApp10\bin\Release\net6.0-windows10.0.19041.0\win10-x64\MauiApp10.dll
<span class="hljs-meta">1&gt;</span>MauiApp10 -&gt; C:\Code\Maui\MauiApp10\bin\Release\net6.0-windows10.0.19041.0\win10-64\AppPackages\MauiApp10_1.0.0.1_Test\MauiApp10_1.0.0.1_x64.msix
<span class="hljs-meta">1&gt;</span>MauiApp10 -&gt; bin\Release\net6.0-windows10.0.19041.0\win10-x64\AppPackages\MauiApp10_1.0.0.1_Test\MauiApp10_1.0.0.1_x64.msixsym
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
</code></pre>

**Comment by mattleibow** [comment]
When publishing (or even just using the `-f` flag) you need to specify the exact TFM in your .csproj. It really may (for some scary reason) have the same TFM twice, but with and without a `.0` as they are unique.

Think of the `-f` flag as selecting from the list of options in a dumb way. In reality, it is probably worth the CLI learning about the best match, but it may not be a great idea in another world as now it could get ambiguous.
