### ISSUE TITLE
Maui project pre-compiler errors using partial classes with multi-targetting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#7005]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-project-pre-compiler-errors-using-p/10033997)._

---
[severity:It's more difficult to complete my work]
In my Maui project I want to have a platform dependent implementation of a cross-platform DeviceServiceExt partial class with a number of partial methods in there.
I use the priciples defined [here](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code) like so:

In a cross-platform folder I have:

```
namespace RoutePlusPlus.Service
{
    public partial class DeviceServiceExt
    {
        public partial string GetIdentifier();
    }
}
```
In the Platform folder for android I have:
```
namespace RoutePlusPlus.Service
{
    public partial class DeviceServiceExt
    {
        public partial string GetIdentifier()
        {
            return "android";
        }
    }
}
```
In the Platform folder for windows I have:
```
namespace RoutePlusPlus.Service
{
    public partial class DeviceServiceExt
    {
        public partial string GetIdentifier()
        {
            return "windows";
        }
    }
}
```

With VS 2022 v17.2.0 Preview 6.0 it is almost impossible to use because of the various pre-compiler errors that show up, such as:
- A partial method may not have multiple implementing declarations
- The call is ambigious between the following methods or properties: 'DeviceServiceExt.GetIdentifier()' and 'DeviceServiceExt.GetIdentifier()'.

I must say that one can successfully create a working build (multi-targetting apparently removes the unused classes from the build) but the fact that the Visual Studio 'Error List' keeps on showing multiple errors for all of these partial class implementations makes it amost useless.

Is this something that will be taking care of in one of the future VS updates or will this stay so for a long a time to come? If so, I might better have to look at alternative ways to execute platform-specific code.

---
#### Feedback Bot on 5/8/2022, 07:40 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drasticactions** [comment]
The reason this was happening was a Rosyln bug where it was showing all of the TFMs in VS, even when it should have only been showing one. It didn't affect builds, but made actually writing the code harder.

That should be taken care of in 17.3 Preview 1, so I would upgrade to that. If it's still an issue, this can be reopened.
