### ISSUE TITLE
[Bug] Height of the view inside the CollectionView and extra padding inside the Grid.

### ISSUE THREAD

**Issue by pierrebrito** [dotnet/maui#7011]
### Description

![image](https://user-images.githubusercontent.com/6466875/167754968-25d69cf0-0cc0-451b-9401-34c776ca27ae.png)

### Steps to Reproduce

<StackLayout>

    <CollectionView ItemsSource="{Binding Items}"
                    VerticalOptions="FillAndExpand">
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <ContentView BackgroundColor="Blue">
                    <Frame Margin="4"
                            Padding="8"
                            BackgroundColor="Red">

                        <Grid ColumnDefinitions="80,*"
                                ColumnSpacing="8"
                                BackgroundColor="Yellow">
                            <Image Source="sem_imagem"
                                    Grid.Column="0" />

                            <StackLayout Spacing="4"
                                            Grid.Column="1"
                                            BackgroundColor="Green">
                                <Label Text="Label 1"
                                        TextColor="Black"
                                        FontAttributes="Bold" />

                                <Label Text="Label 2"
                                        TextColor="Black" />

                                <Label Text="Label 3"
                                        TextColor="Black"
                                        FontAttributes="Bold" />
                            </StackLayout>
                        </Grid>
                    </Frame>
                </ContentView>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</StackLayout>

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by v-longmin** [comment]
@pierrebrito Could you share your project for us? Thanks.

**Comment by pierrebrito** [comment]
@v-longmin 
[Demo7011.zip](https://github.com/dotnet/maui/files/8666249/Demo7011.zip)

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[Demo7011.zip](https://github.com/dotnet/maui/files/8666333/Demo7011.zip)

**Comment by NonameMissingNo** [comment]
@PureWeen Appears to be working fine on the Latest main (net6.0)
![image](https://user-images.githubusercontent.com/40233496/176235597-d372a418-1414-439a-aa5c-f810f603843b.png)

**Comment by PureWeen** [comment]
Thank you @NonameMissingNo !!
