### ISSUE TITLE
Expose ApplicationSignificantTimeChange in the lifecycle events and/or MauiUIApplicationDelegate

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#7012]
### Description

Now that AppDelegate derives from MauiUIApplicationDelegate/UIResponder instead of FormsApplicationDelegate/UIApplicationDelegate, I don't see a way to access events which are not implemented in MauiUIApplicationDelegate.  E.g.  how can an application receive UIApplicationDelegate.ApplicationSignificantTimeChange?

It would be nice if all UIApplicationDelegate events were exposed through MauiUIApplicationDelegate.  Alternatively, is there a way to derive from UIApplicationDelegate and then have the MAUI application use the derived type instead of UIApplicationDelegate?

### Public API Changes

not sure what's best here

### Intended Use-Case

Migrate XF app to MAUI

**Comment by mattleibow** [comment]
You can for now just implement the method like this on the delegate:

```cs
[Export("applicationSignificantTimeChange:")]
public virtual void ApplicationSignificantTimeChange(UIApplication application)
{
}
```
