### ISSUE TITLE
MediaPicker.CapturePhotoAsync()  is not supported on ios ?

### ISSUE THREAD

**Issue by Ihone8** [dotnet/maui#7013]
### Description

I tried to use the camera on the IOS simulator, MediaPicker. CapturePhotoAsync (); But it doesn't seem to support change methods on IOS, right?

### Steps to Reproduce

1. Create New Project -> New .NET MAUI APP
2. Add a Button like this  <Button Text="Click me" Clicked="OnCounterClicked" />
3. await MediaPicker.CapturePhotoAsync();
![image](https://user-images.githubusercontent.com/34541083/167783486-4382937f-08a0-4350-a75b-a994499312f5.png)
4. run project and Click the Button 
5. 
![image](https://user-images.githubusercontent.com/34541083/167784159-3d65ce04-a3ec-4f3a-986c-28d4601e57f7.png)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

iOS

### Affected platform versions

IOS 15.4

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on iOS 15.4. Sample Project: 
[MauiApp1.zip](https://github.com/dotnet/maui/files/8667864/MauiApp1.zip)

![image](https://user-images.githubusercontent.com/97647558/167798294-e09c4be1-9f12-4e21-a021-902e01f50783.png)

**Comment by nacompllo** [comment]
This is a restriction by Apple, iOS simulators do not allow access to the Mac camera.

The following hardware is not supported in iOS Simulator:

- Ambient light sensor
- Audio input, except for using Siri by choosing Hardware > Siri.
- Barometer
- Bluetooth
- Camera
- Motion support (accelerometer and gyroscope)
- Proximity sensor

The [Apple documentation](https://help.apple.com/simulator/mac/current/#/devb0244142d) specifies this.

So this is not a .NET MAUI issue.

**Comment by Ihone8** [comment]
> This is a restriction by Apple, iOS simulators do not allow access to the Mac camera.
> 
> The following hardware is not supported in iOS Simulator:
> 
> * Ambient light sensor
> * Audio input, except for using Siri by choosing Hardware > Siri.
> * Barometer
> * Bluetooth
> * Camera
> * Motion support (accelerometer and gyroscope)
> * Proximity sensor
> 
> The [Apple documentation](https://help.apple.com/simulator/mac/current/#/devb0244142d) specifies this.
> 
> So this is not a .NET MAUI issue.

ok thanks
