### ISSUE TITLE
[iOS] No Background is rendered on Borders with Shadows

### ISSUE THREAD

**Issue by paulvarache** [dotnet/maui#7015]
### Description

No Background is rendered on Borders with Shadows on iOS. Changing the StrokeThickness programmatically makes the background appear.

Rendering works as expected on Android.

Reproduction repo: https://github.com/paulvarache/MauiIssueBorderShadowBackground

iOS.
Left: Initial render.
Right: After StrokeThickness for third border is set in Code-Behind
![bordershadowbackground-ios](https://user-images.githubusercontent.com/5550089/167790879-7f5742d9-cf86-4106-af68-2e34bd4f3fcd.png)

Android:

![bordershadowbackground-android](https://user-images.githubusercontent.com/5550089/167791068-1099ef3a-20fd-461e-9684-bf2edae00c01.png)

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Add a `<Border>`  with a `Background` and `<Shadow>`
3. Run on iOS

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

Updating the StrokeThickness makes the Background render. I suspect other Properties would too.

**Comment by v-longmin** [comment]
Verified repro on iOS 15.4 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[MauiIssueBorderShadowBackground-main.zip](https://github.com/dotnet/maui/files/8667814/MauiIssueBorderShadowBackground-main.zip)

**Comment by HausBJB** [comment]
I can confirm.

as soon as the border gets a shadow, it disappears completely on the first start.

if you change e.g. StrokeThickness during hot reload, the border reappears

```
    <VerticalStackLayout>
        <Border
            Padding="16,8"
            Background="#2B0B98"
            HorizontalOptions="Center"
            StrokeShape="RoundRectangle 40,0,0,40"
            StrokeThickness="1">
            <Label
                FontAttributes="Bold"
                FontSize="18"
                Text=".NET MAUI OK"
                TextColor="White" />
        </Border>

        <Border
            Padding="16,8"
            Background="#2B0B98"
            HorizontalOptions="Center"
            StrokeShape="RoundRectangle 40,0,0,40"
            StrokeThickness="1">
            <Label
                FontAttributes="Bold"
                FontSize="18"
                Text="Error"
                TextColor="White" />
            <Border.Shadow>
                <Shadow
                    Brush="green"
                    Opacity="0.1"
                    Radius="5"
                    Offset="5,5" />
            </Border.Shadow>
        </Border>
    </VerticalStackLayout>
```
![image](https://user-images.githubusercontent.com/53478848/170742074-11216817-3ffd-40a2-b5c1-07c8243b7004.png)

![Border](https://user-images.githubusercontent.com/53478848/170742847-3cb24e0a-83d2-4575-a751-f1c419545c64.gif)

**Comment by HausBJB** [comment]
I think it has priority. otherwise the border is useless

**Comment by paulvarache** [comment]
In the meantime, adding this to your `Platforms/iOS/AppDelegate.cs` constructor seems to force the background to appear:
```cs
BorderHandler.Mapper.AppendToMapping(nameof(Border.Background), (h, v) =>
{
    Task.Delay(0).ContinueWith((_) =>
    {
        MainThread.InvokeOnMainThreadAsync(() =>
        {
            h.PlatformView.UpdateBackground(v);
        });
    });
});
```

**Comment by HausBJB** [comment]
Thank you that helps

**Comment by drasticactions** [comment]
A new issue by @faceoffers28 was created  (https://github.com/dotnet/maui/issues/7015) referencing reopening this issue.
