### ISSUE TITLE
AbsoluteLayout miss align on MacOS and iOS

### ISSUE THREAD

**Issue by arkadym** [dotnet/maui#7018]
### Description

I tried to use AbsoluteLayout to dynamically change visibility of buttons and it work as expected in Windows and Android, but missbehave on Mac OS and iOS (see attached video)

### Steps to Reproduce

1. Create new .NET MAUI App
2. Create new ContentPage or use existing
3. Use below layout
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.AbsolutePage"
             Title="AbsolutePage">
    
    <AbsoluteLayout>
        <StackLayout Orientation="Vertical" AbsoluteLayout.LayoutBounds="0.5, 1, AutoSize, AutoSize" AbsoluteLayout.LayoutFlags="PositionProportional">
            <StackLayout x:Name="PopupLayout" Orientation="Vertical" IsVisible="False" VerticalOptions="End">
                <Button ImageSource="{StaticResource fisUser}" Text="User and Password" BackgroundColor="{StaticResource Primary}"
                        TextColor="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource White}}"
                        CornerRadius="25" BorderWidth="0" HeightRequest="50" Margin="0,10,0,0" Padding="15,0"
                        Command="{Binding TogglePopupLayoutCommand}"
                        />
                <Button ImageSource="{StaticResource fisKey}" Text="Api Key" BackgroundColor="{StaticResource Primary}"
                        TextColor="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource White}}"
                        CornerRadius="25" BorderWidth="0" HeightRequest="50" Margin="0,10,0,0" Padding="15,0"
                        Command="{Binding TogglePopupLayoutCommand}"
                        />
            </StackLayout>
            <Button ImageSource="{StaticResource fisPlus}" Text="Add Account" BackgroundColor="{StaticResource Primary}" 
                    TextColor="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource White}}"
                    CornerRadius="25" BorderWidth="0" HeightRequest="50" HorizontalOptions="Center" Margin="15" Padding="15,0,20,0"
                    Command="{Binding TogglePopupLayoutCommand}" />
        </StackLayout>
    </AbsoluteLayout>
</ContentPage>
```
5. Use below codes 
```
namespace MauiApp1;

public partial class AbsolutePage : ContentPage
{
	public AbsolutePage()
	{
		InitializeComponent();

        BindingContext = this;
	}

    [ICommand]
    internal void TogglePopupLayout()
    {
        if (!PopupLayout.IsVisible)
        {
            PopupLayout.IsVisible = true;
            PopupLayout.MaximumHeightRequest = Height > 0 ? Height : 10000;
            var bounds = PopupLayout.Measure(Width, Height);

            PopupLayout.Opacity = 0;
            PopupLayout.MaximumHeightRequest = 0;

            var animation = new Animation();
            animation.Add(0, 1, new Animation(v => PopupLayout.Opacity = v, 0, 1));
            animation.Add(0, 1, new Animation(v => PopupLayout.MaximumHeightRequest = v, 0, bounds.Request.Height));

            animation.Commit(PopupLayout, nameof(PopupLayout), length: 500, easing: Easing.CubicOut);
        }
        else
        {
            var animation = new Animation();
            animation.Add(0, 1, new Animation(v => PopupLayout.Opacity = v, 1, 0));
            animation.Add(0, 1, new Animation(v => PopupLayout.MaximumHeightRequest = v, PopupLayout.Height, 0));

            animation.Commit(PopupLayout, nameof(PopupLayout), length: 500, easing: Easing.CubicOut,
                finished: (v, f) => PopupLayout.IsVisible = false);
        }
    }
}
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15, Mac OS X 12.3.1

### Did you find any workaround?

No workaround

https://user-images.githubusercontent.com/7422012/167987162-9737b958-232c-4324-80c2-f90843bd7c92.mp4

**Comment by arkadym** [comment]
FYI, animations are there but is not affecting the bug, can comment it out, still same behavior

**Comment by mattleibow** [comment]
Sadly I see no videos. :( I just cancelled my Netflix and chill in excitement for watching 2 videos of a bug and now I can't! :) 

did you forget to attach?

**Comment by arkadym** [comment]
> Sadly I see no videos. :( I just cancelled my Netflix and chill in excitement for watching 2 videos of a bug and now I can't! :)
> 
> did you forget to attach?

Omg! It is little bit problem, video left on my PC on office, can upload tomorrow morning only, sorry man, no movie today(

**Comment by arkadym** [comment]
> Sadly I see no videos. :( I just cancelled my Netflix and chill in excitement for watching 2 videos of a bug and now I can't! :)
> 
> did you forget to attach?

Done, uploaded video.

**Comment by VincentBu** [comment]
verified with vs main (32623.270), but I run into a different bug: clicking `Add Account` doesn't toggle `PopupLayout` on Android emulator. On IOS, it works well for me.

**Comment by arkadym** [comment]
> verified with vs main (32623.270), but I run into a different bug: clicking `Add Account` doesn't toggle `PopupLayout` on Android emulator. On IOS, it works well for me.

With latest MAUI update - Android dynamic layout changes are totally broken. I mean e.g most content dynamic changes friendly i found is StackLayout (Vertical, Horizontal). It works as expected on Windows/Mac/iOS but totally not work on Android. E.g. i'd like to show semitransparent overlay with progress over the whole page while doing something in background, and it works for Windows, Mac and iOS but when i change IsVisible on Android - happens nothing :(

**Comment by hartez** [comment]
@arkadym #8136 should address the problems you're seeing with IsVisible on Android.

**Comment by arkadym** [comment]
Just tested with latest SR4 (486) - it works fine.
