### ISSUE TITLE
Animated gifs do not start initially

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#7019]
### Description

Setting `IsAnimationPlaying=True` in the XAML does not start the animation, but hot reloading makes it work.

```xaml
<Image Source="animated_heart.gif" WidthRequest="200" IsAnimationPlaying="True" />
```

### Steps to Reproduce

1. Add an animated gif to a project
2. Add an `<Image>` to the XAML
3. Set the `IsAnimationPlaying=True`
4. Run app
5. Observe the gif is not animating
6. Hot reload the value to false then true
7. Observe the gif animating

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All

**Comment by jsuarezruiz** [comment]
Cannot longer reproduce it on .NET 7
![issue-7019](https://user-images.githubusercontent.com/6755973/228867149-43cf132c-4d37-418f-9bbe-3c7422907896.gif)
