### ISSUE TITLE
Animated gifs are not working properly

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#7021]
### Description

**All**
- [x] Resizetizer is resizing animated gifs into png files
      Issue: https://github.com/dotnet/maui/issues/5034
      PR: _pending..._

**Android**
- [x] Android does not start when value is set initially
      Issue: https://github.com/dotnet/maui/issues/7019
      PR: #14295

**iOS**

- [x] iOS has no animated gif support  
      Issue: https://github.com/dotnet/maui/issues/866
      PR: https://github.com/dotnet/maui/pull/17207

Windows

- [x] Windows always animates the gif, nothing can stop it  
      Issue: https://github.com/dotnet/maui/issues/7020
      PR: _pending..._

### Steps to Reproduce

See individual issues

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

**Comment by Vpatel541** [comment]
Will this be worked on any time soon?

**Comment by StratisIain** [comment]
Any update on this?

**Comment by HammadMaqbool** [comment]
Any update on the issue?

**Comment by HammadMaqbool** [comment]
<Image Source="sunset.gif"
               Grid.Column="1"
               Grid.Row="0"
               Aspect="AspectFit"
               Margin="18"
               IsAnimationPlaying="True"
               />

By Adding isAnimationPlaying="True" in the image control you can make the gif animation start.

**Comment by syachrodi** [comment]
> ```
> <Image Source="sunset.gif"
>               Grid.Column="1"
>               Grid.Row="0"
>               Aspect="AspectFit"
>               Margin="18"
>               IsAnimationPlaying="True"
>               />
> ```
> 
> By Adding isAnimationPlaying="True" in the image control you can make the gif animation start.

Hi bro, have you tried this in release mode?
In my case, in debug mode the gif animation is running, but in release mode the gif animation is not running

**Comment by HammadMaqbool** [comment]
> 
> 
> > ```
> > <Image Source="sunset.gif"
> >               Grid.Column="1"
> >               Grid.Row="0"
> >               Aspect="AspectFit"
> >               Margin="18"
> >               IsAnimationPlaying="True"
> >               />
> > ```
> > 
> > By Adding isAnimationPlaying="True" in the image control you can make the gif animation start.
> 
> Hi bro @HammadMaqbool, have you tried this in release mode?
> In my case, in debug mode the gif animation is running, but in release mode the gif animation is not running

Same here. . .   It stopped working in release mode. . . .

**Comment by syachrodi** [comment]
> > > ```
> > > <Image Source="sunset.gif"
> > >               Grid.Column="1"
> > >               Grid.Row="0"
> > >               Aspect="AspectFit"
> > >               Margin="18"
> > >               IsAnimationPlaying="True"
> > >               />
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > By Adding isAnimationPlaying="True" in the image control you can make the gif animation start.
> > 
> > 
> > Hi bro @HammadMaqbool, have you tried this in release mode?
> > In my case, in debug mode the gif animation is running, but in release mode the gif animation is not running
> 
> Same here. . . It stopped working in release mode. . . .

Any trick or solution for this problem bro?

**Comment by jfversluis** [comment]
2 linked issues resolved, remaining 2 have open PRs, I think we can close this one.
