### ISSUE TITLE
MenuBarItems Command is not executed. (Verified on Windows)

### ISSUE THREAD

**Issue by VladislavAntonyuk** [dotnet/maui#7024]
### Description

MenuBarItems Command is not executed. (Verified on Windows)

### Steps to Reproduce

1. Create default .NET MAUI application
2. On MainPage set MenuBarItems:
```
<ContentPage.MenuBarItems>
		<MenuBarItem Text="File">
			<MenuFlyoutItem Text="New" Command="{Binding NewCommand}"/>			
		</MenuBarItem>
	</ContentPage.MenuBarItems>
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 19041

### Did you find any workaround?

Set Clicked event and call command

**Comment by VladislavAntonyuk** [comment]
Sample: https://github.com/VladislavAntonyuk/MauiSamples/blob/main/MauiPaint/MainPage.xaml#L12

**Comment by mattleibow** [comment]
Duplicate of #5382

**Comment by IndexOutOfLimit** [comment]
Can anyone please let me know when we can get permanent fix for this as this is violating MVVM pattern.

**Comment by mattleibow** [comment]
You can follow the linked issue for updates.
