### ISSUE TITLE
[Android] NavigationPage throws InvalidProgramException in Release

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#7027]
### Description

When I try to run my application in Release the following exception is thrown:

05-11 15:49:25.658 24489 24489 E AndroidRuntime:  ---> System.InvalidProgramException: Invalid IL code in Microsoft.Maui.Handlers.NavigationViewHandler:CreatePlatformView (): IL_002a: ldnull    
05-11 15:49:25.658 24489 24489 E AndroidRuntime: 
05-11 15:49:25.658 24489 24489 E AndroidRuntime: 
05-11 15:49:25.658 24489 24489 E AndroidRuntime:    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IStackNavigationView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].OnCreatePlatformView()
05-11 15:49:25.658 24489 24489 E AndroidRuntime:    at Microsoft.Maui.Handlers.ViewHandler.OnCreatePlatformElement()
05-11 15:49:25.658 24489 24489 E AndroidRuntime:    at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
05-11 15:49:25.658 24489 24489 E AndroidRuntime:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
05-11 15:49:25.658 24489 24489 E AndroidRuntime:    at Microsoft.Maui.Handlers.ViewHandler.SetVirtualView(IElement element)

### Steps to Reproduce

1. Run the attached project
2. Try to run in in Release: dotnet build -t:Run -c Release -f net6.0-android
3. Notice how the app crash. The above stacktrace is taken using adb logcat.
[HelloMaui.zip](https://github.com/dotnet/maui/files/8670040/HelloMaui.zip)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Android

### Affected platform versions

Android 8 (at least) and up

**Comment by Redth** [comment]
@jonathanpeppers is this a linker issue, could you take a look?

**Comment by jsuarezruiz** [comment]
> @jonathanpeppers is this a linker issue, could you take a look?

Maybe helps to find what is happening. Setting these properties seems to make the Navigation page work in Release:

```
<AndroidUseInterpreter>true</AndroidUseInterpreter>
<AotAssemblies>false</AotAssemblies>
```

**Comment by jonathanpeppers** [comment]
I bet `-p:AndroidLinkResources=false` might solve this actually?

**Comment by APopatanasov** [comment]
I can confirm setting AndroidLinkResources to False resolves the issue.

**Comment by jonathanpeppers** [comment]
Thanks, I believe that https://github.com/dotnet/maui/pull/7038 fixes this.

This will be shipping in the next release, but anyone should be able to workaround by using this in their `.csproj` for now:
```xml
<AndroidLinkResources>false</AndroidLinkResources>
```
