### ISSUE TITLE
Background color cannot be changed on page

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#7036]
### Description

If you set a background color on a page, that setting will be ignored on Windows. Work on find on Android. This issue is maybe related: https://github.com/dotnet/maui/issues/6932

This did work in RC2.

Reproduction: https://github.com/pekspro/MauiIssues/tree/BackgroundColorIssue

### Steps to Reproduce

1. Create a new MAUI app.
2. Update the MainPage.xaml:

``` XAML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiIssues.MainPage"
             BackgroundColor="DarkBlue">
    <VerticalStackLayout Spacing="25" Padding="30">
        <Label 
            Text="This page should have a dark blue background!"
            SemanticProperties.HeadingLevel="Level1"
            FontSize="32"
            HorizontalOptions="Center" />
    </VerticalStackLayout>
</ContentPage>
```
3. Run the application. The background is still white.

![image](https://user-images.githubusercontent.com/3163293/167906059-6545cb31-4728-4459-ac8a-9dba0ab39f80.png)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.17763.0

### Did you find any workaround?

No. However, changing the color while debugging did forced the changes to be made.

**Comment by Redth** [comment]
Working here nicely on main with a file new project:
![image](https://user-images.githubusercontent.com/271950/167915273-8ddafd31-25ac-4032-867d-37124a2549e7.png)

**Comment by pekspro** [comment]
@Redth, that's super strange :-( I created a new app just to verify and got the same result:

![image](https://user-images.githubusercontent.com/3163293/167921633-d6181346-0a0d-4763-9d26-94b31999f4cc.png)

Running on Windows 10, 19043.1645.

**Comment by Redth** [comment]
@pekspro I was verifying against workloads installed from maui's _main_ branch build, locally the version for me is `6.0.300-rc.4.5760` so if you're not at that version or close to it, it probably won't work for you.

**Comment by pekspro** [comment]
@Redth, I see, then I still have some hope :-)

**Comment by mattleibow** [comment]
What happens if you use the `Background` property instead of `BackgroundColor`?
