### ISSUE TITLE
upgrade from dotnet 6 to 7 errors

### ISSUE THREAD

**Issue by MarshalOfficial** [dotnet/maui#7040]
### Description

I have a dotnet maui blazor application that works with dotnet 6.0.300, now I want to upgrade to dotnet 7.0.100-preview.4.22252.9 to have the latest features. I installed dotnet 7 SDK and updated the visual studio 2022 community preview to the latest version, now when I build the project it is ok to have some errors because in the csproj file it is targeted to dotnet 6, now my question is: how to edit and which sections of csproj file must edit to upgrade my project to target dotnet 7 correctly??
below is screenshot from the csproj file and errors:

![image](https://user-images.githubusercontent.com/8558078/167908901-629c1d00-6e23-4430-9f2e-0c6f091a650a.png)

### Steps to Reproduce

1-create a dotnet maui blazor app in visual studio 2022 community preview latest version
2-attempt to upgrade to dotnet 7

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Preview 14

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Android 10, Windows 10

**Comment by Eilon** [comment]
I think that right now .NET MAUI is compatible only with .NET 6. It cannot be used with .NET 7 at all.

**Comment by drasticactions** [comment]
Yeah. The workloads themselves are being ported to net7, but MAUI itself can't until those ship. Until then, you need to use net6.0. If you have net7 installed, you need to setup a global json to target 6.0.300.
