### ISSUE TITLE
[Enhancement] Acrylic blur BRUSH for every layout

### ISSUE THREAD

**Issue by mhrastegary77** [dotnet/maui#705]
## Summary
Is it possible to use acrylic brush like UWP in every layout?

Like [Sharpnado.MaterialFrame](https://github.com/roubachof/Sharpnado.MaterialFrame) uses the native acrylic blur of every OS but just in a frame not every layout or decide whether to use in-app or background acrylic for desktop platforms like macOS and UWP/winui would be nice.

## Api Changes
**just like the UWP's AcrylicMaterial**

Custom acrylic brush
```
<ResourceDictionary.ThemeDictionaries>
    <ResourceDictionary x:Key="Light">
        <AcrylicBrush x:Key="MyAcrylicBrush"
            BackgroundSource="HostBackdrop"
            TintColor="#FFFF0000"
            TintOpacity="0.8"
            TintLuminosityOpacity="0.5"
            FallbackColor="#FFFF7F7F"/>
    </ResourceDictionary>
</ResourceDictionary.ThemeDictionaries>
```

and using the custom brush like this 
`<Grid Background="{ThemeResource MyAcrylicBrush}">
`

## Screenshots
Acrylic Hostbackdrop 
![image](https://user-images.githubusercontent.com/42671084/114492360-b4759c00-9c2d-11eb-9ea0-bfae7b8e8ff6.jpeg)
![image](https://user-images.githubusercontent.com/42671084/114492366-b8092300-9c2d-11eb-813e-e1123d7c7faf.jpeg)

**Comment by sps014** [comment]
Great proposal, worth considering , glass morphism is new meta.

**Comment by Redth** [comment]
Love the idea, this isn't on our roadmap in the near future, especially considering there's the excellent Sharpnado implementation mentioned in the OP :) https://github.com/roubachof/Sharpnado.MaterialFrame
