### ISSUE TITLE
On Android CollectionView selection and scroll not working properly

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#7053]
### Description

Depending on how one encapsulates the CollectionView, scroll and selection fails.
If layed out with a simple [Content = collectionView;] in a ContentPage, the items scroll, but selection stops or offset once the list is scrolled away from the first page.
If layed out with a [new VerticalStackLayout { Children = { collectionView } };], the list does not scroll anymore.
A video provided here shows the issue.

https://github.com/hbraasch/CollectionViewScrollTester/blob/master/AnotherCollectionViewProblem.mp4

A reproduction project here recreates the issue:

https://github.com/hbraasch/CollectionViewScrollTester.git

### Steps to Reproduce

1. Run the application as provided
2. Select an item, then scroll the page, then try to select again. Notice the selection fail.
3. Click on the [Stack] menu item, the page will refresh (the way the [Content] is setup changed).
4. Try to scroll, it does not scroll anymore.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 - API 31, Android 11 - API 31

### Did you find any workaround?

None

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[CollectionViewScrollTester-master.zip](https://github.com/dotnet/maui/files/8674298/CollectionViewScrollTester-master.zip)

**Comment by IeuanWalker** [comment]
Same issue here, but with HorizontalList -
```xaml
<CollectionView FlowDirection="RightToLeft"
                ItemSizingStrategy="MeasureFirstItem"
                ItemsLayout="HorizontalList"
                ItemsSource="{Binding Dates}"
                SelectedItem="{Binding SelectedDiary}"
                SelectionMode="Single">
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <ContentView Padding="10" x:DataType="viewModel:DiaryTestModel">
                <Frame Padding="0"
                        BackgroundColor="#E5F7FF"
                        CornerRadius="20"
                        HasShadow="False"
                        IsEnabled="false">
                    <VerticalStackLayout Padding="10">
                        <Label HorizontalTextAlignment="Center"
                                Text="{Binding DayOfTheWeekLetter}"
                                TextColor="#00A2EE" />
                        <Label HorizontalTextAlignment="Center"
                                Text="{Binding Date, StringFormat='{0:dd}'}"
                                TextColor="Black" />
                    </VerticalStackLayout>
                </Frame>
            </ContentView>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

**Comment by rmarinho** [comment]
The scroll issue with `StackPanel` is by design, it's a change from Xamarin.Forms, StackLayout will extend it's height, so you will need to use a Grid. 
The other issue was address on my PR #7689

**Comment by alexkblount** [comment]
> The scroll issue with `StackPanel` is by design, it's a change from Xamarin.Forms, StackLayout will extend it's height, so you will need to use a Grid.

I understand that this is by design but I think adding some feedback for the developer would be useful. Having to find out through googling isn't a great use of time and effort. Maybe adding a squiggly and message to say this isn't supported?

**Comment by davidortinau** [comment]
@Redth can we please emit a warning and see about squiggles for this? And any other similar cases.

**Comment by leoderja** [comment]
Clicking on one item selects another: this is a serious bug that makes the CollectionView non-usefull at all. 

Just imagine a user, clicking on a patient in a patient list but is selected a another patient ... It's a serious bug.

**Comment by hbraasch** [comment]
Did a test with my repro app after the latest MAUI update. The selection problem appears to be fixed. Thanks
