### ISSUE TITLE
Page BackgroundColor Wrong on Windows

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#7054]
### Description

I have a startup page with a BackgroundColor specified - it works fine in RC2 but in RC3 Windows it shows up white (it's ok in Android)

### Steps to Reproduce

1. Unzip the project from 
[MAUIToolBar-Shell-background.zip](https://github.com/dotnet/maui/files/8674402/MAUIToolBar-Shell-background.zip)

2. Compile and run it on Android, you should see this
![MAUIToolBar-Shell-background-android](https://user-images.githubusercontent.com/12423046/167974749-d297d6a3-0f8d-4288-89ab-e4c9a1e4af71.jpg)

3. Compile and run it on Windows, you should see this
![MAUIToolBar-Shell-background-windows](https://user-images.githubusercontent.com/12423046/167974771-c310ea51-eaea-4b21-b3f4-d82a442dea28.jpg)

Note that on Windows the background color is not red, that's the bug.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by v-longmin** [comment]
![image](https://user-images.githubusercontent.com/40230425/167976442-60f9f0c9-3918-4648-8058-13f852602cc1.png)
Verified not repro on Windows 10 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[MAUIToolBar-Shell-background.zip](https://github.com/dotnet/maui/files/8674456/MAUIToolBar-Shell-background.zip)

**Comment by david-maw** [comment]
Interesting, I'm also running Version 17.3.0 Preview 1.0 on Windows Version 10.0.19043 and obviously I do see the problem. What version of Windows 10 were you running on?

**Comment by singhwong** [comment]
I had the same problem in rc3, "AppThemeBinding" didn't work correctly. If I change the pc system theme, the correct background color is displayed, but after navigating to other pages, the problem still occurs.
windows version: windows11 22000.675
vs version:  17.3.0 Preview 1.0

**Comment by JohnHDev** [comment]
Im seeing the same issue in RC3, at first I thought it was a new bug on Grid (which is my page content), but taking everything out so that its an empty page with a background color replicates this issue. Worked fine in RC2.

**Comment by david-maw** [comment]
I also reproduced it on a clean Azure VM, so it's definitely a problem but apparently has some sort of system dependency, given that @v-longmin couldn't reproduce it.

**Comment by jamesmontemagno** [comment]
I can confirm this as well in https://github.com/dotnet-presentations/dotnet-maui-workshop/

**Comment by PureWeen** [comment]
This is fixed in GA

**Comment by david-maw** [comment]
Thanks, are GA and the 6.0.300 milestone the same thing?
