### ISSUE TITLE
Manual iOS Provisioning

### ISSUE THREAD

**Issue by claybrooks** [dotnet/maui#7056]
### Description

When trying to manually provision, the IDE is unable to retrieve the provisioning profiles I have setup through my apple developer portal.  I downloaded the profile and placed in %APPDATA%\..\Local\Xamarin\iOS\Provisioning\Profiles.  The profile is now displayed int the "Provisioning Profile" dropdown in the Bundle Signing project settings.

When attempting to deploy to my iOS device, I get the following error in the build output:

Build started...
...
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.4.300-rc.3.83\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets(316,3): error : provisioingProfilePath
1>Done building project "GUI.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

Note the misspelled "provisioingProfilePath".

I then edited Xamarin.iOS.HotRestart.targets file with a hardcoded path to the profile I want to use.  

<HotRestart.Tasks.Codesign 
        AppBundlePath="$(HotRestartAppBundlePath)"
        BundleIdentifier="$(_BundleIdentifier)"
	CodeSigningPath="$(_CodeSigningPath)"
        ProvisioningProfilePath="%APPDATA%\..\Local\Xamarin\iOS\Provisioning\Profiles\app.mobileprovision" />

Everything now works as expected.

### Steps to Reproduce

1. Create a MAUI project
2. Setup up to be "Manually Provisioned"
3. Set signing identity appropriately
4. Set the provisioning profile appropriately
5. Try to build to local iOS device

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

Hardcode the path to provisioning profile in the Xamarin.iOS.HotRestart.targets file.

**Comment by jfversluis** [comment]
@maddymontaquila does this mean anything to you?

**Comment by drasticactions** [comment]
This is not an MAUI bug, it's a Hot Restart bug with provisioning iOS certificates. 

There are a few issues with provisioning (both automatic and manual) for Hot Restart, but these are not things that can be fixed within this repo, it needs to go to Visual Studio. This should probably be filed as VS Feedback.

**Comment by rajeshsws** [comment]
I am also facing same issue.

**Comment by jbloink** [comment]
I just ran into this as well.

**Comment by jfversluis** [comment]
As pointed out, this is a tooling matter. Please report through Visual Studio, then the Help menu, Send Feedback, Report a Problem and see if there is already an existing issue. I think there might as there have been some issues in this area. I think new Visual Studio versions are also imminent, so you might want to give it a little bit, test the new versions and if it still doesn't work then, report it through the method above :)

**Comment by rajeshsws** [comment]
Below is the solution i found from on VS team

On your Mac in XCode, ensure your certificates and profiles are downloaded (Xcode->Preferences->Accounts)

1 On your Mac in Keychain Access, export your development certificate and provide a password for the p12 file (KeychainAccess/My Certificates, File->Export Items), copy the p12 to the PC Desktop
2 On your Mac in Finder, Go->Go to Folder->~/Library/MobileDevice/Provisioning Profiles, copy all .mobileprovision files to your PC into %HOME%\AppData\Local\Xamarin\iOS\Provisioning\Profiles

3 On your PC, open Visual Studio and then Tools->Options->Xamarin->Apple Accounts, click the account and also the name in the box below
4 Click “View Details” and wait for the spinners to throw the now-familiar errors
5 Click “Import Certificate”, choose the certificate you copied in step 1, and enter the password you chose
6 More errors will be thrown, but the certificate will have been imported into %HOME%\AppData\Local\Xamarin\iOS\Provisioning\Certificates
7 Close and reopen VS or at least the VS solution (might be unnecessary but hey)
8 In your VS iOS project, click Properties and you should now be able to select the new certificate and the desired profile
9 Build and run on the provisioned device(s).

Its working for me.
Now able to generate .IPA as well and my previous issue ios-arm64 invalid identifier is also gone

**Comment by ReggieSean** [comment]
> Below is the solution i found from on VS team
> 
> On your Mac in XCode, ensure your certificates and profiles are downloaded (Xcode->Preferences->Accounts)
> 
> 1 On your Mac in Keychain Access, export your development certificate and provide a password for the p12 file (KeychainAccess/My Certificates, File->Export Items), copy the p12 to the PC Desktop 2 On your Mac in Finder, Go->Go to Folder->~/Library/MobileDevice/Provisioning Profiles, copy all .mobileprovision files to your PC into %HOME%\AppData\Local\Xamarin\iOS\Provisioning\Profiles
> 
> 3 On your PC, open Visual Studio and then Tools->Options->Xamarin->Apple Accounts, click the account and also the name in the box below 4 Click “View Details” and wait for the spinners to throw the now-familiar errors 5 Click “Import Certificate”, choose the certificate you copied in step 1, and enter the password you chose 6 More errors will be thrown, but the certificate will have been imported into %HOME%\AppData\Local\Xamarin\iOS\Provisioning\Certificates 7 Close and reopen VS or at least the VS solution (might be unnecessary but hey) 8 In your VS iOS project, click Properties and you should now be able to select the new certificate and the desired profile 9 Build and run on the provisioned device(s).
> 
> Its working for me. Now able to generate .IPA as well and my previous issue ios-arm64 invalid identifier is also gone

To be clear, this error happend to me and I believe op after we followed these steps
