### ISSUE TITLE
Web support 

### ISSUE THREAD

**Issue by aliessmael** [dotnet/maui#7058]
### Description
I would like my maui app run on web platform.
I dot want to work with blazor, making nice looking UI in blazor require working on js .

### Public API Changes

var myLovelyUI = new CustomNiceDraggableCarousel()

### Intended Use-Case

In blazor for example I struggled  at making draggable carousel (drag content to scroll)

maui is simple and clear, it would be nice to have maui app running on web

**Comment by Eilon** [comment]
Dup of https://github.com/dotnet/maui/issues/4528
