### ISSUE TITLE
Custom layout base on AbsoluteLayout will  repeated measure many times

### ISSUE THREAD

**Issue by xtuzy** [dotnet/maui#7060]
### Description

I try to custom layout, it name ConstraintLayout. 
First, i let it derive from Layout like AbsoluteLayout, but nothing show, i don't why.
Then, i ask help form Stackoverflow,see [problem](https://stackoverflow.com/questions/72204307/custom-maui-layout-dont-show-any-control-but-control-have-correct-position-and?noredirect=1#comment127573875_72204307), someone say it need derive from AbsoluteLayout, so i change my code, see the changed result [ConstraintLayout.Maui.cs](https://github.com/xtuzy/SharpConstraintLayout/blob/Modify/SharpConstraintLayout.Maui/Widget/ConstraintLayout.Maui.cs), you can see the [change](https://github.com/xtuzy/SharpConstraintLayout/commit/f6e686e5d87b13f650dc914aaf492825c8b63078).

When use AbsoluteLayout as base class, all control can show, but it will measure many times, when no control in ConstraintLayout, it need measure 6 times at start.
![sharex-20220512103600](https://user-images.githubusercontent.com/17793881/167984389-add2cb67-d094-4cdb-8656-781c9d0605a5.png)

when two control in ConstraintLayout, it need measure many times.
![sharex-20220512103833](https://user-images.githubusercontent.com/17793881/167984409-cac77d2d-2329-464d-9c54-7e5711255b67.png)

I have made ConstraintLayout of WinUI, it just need 2 times at start.
![sharex-20220512111916](https://user-images.githubusercontent.com/17793881/167985378-d9e2bbdf-69ff-46e4-a6d0-e33d9a48b4e7.png)

I want know,
1. how to use Layout, ILayout, LayoutManager,ILayoutManager to custom layout, someone say need use handler, but i don't need extra platform code, why also need use it, i search maui source code don't find AbsoluteLayoutHandler. what i miss?

### Steps to Reproduce

1. Run https://github.com/xtuzy/SharpConstraintLayout/tree/Modify

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.22000

**Comment by hartez** [comment]
#7039 and #7049 _may_ have fixed this. Noting it here so I can check.

**Comment by xtuzy** [comment]
I want die. Finally i found i just use incorrect Arrange method, View inherit form VisualElement and IView, they all have a Arrange method, i use it of VisualElement, so all control not show.

**Comment by xtuzy** [comment]
It still need measure multiple times.

**Comment by xtuzy** [comment]
I write a simple customlayout, it also need measure 5 times
```

        static int index = 0;
        public override Size Measure(double widthConstraint, double heightConstraint)
        {
            Debug.WriteLine("Measure Times:" + index++);
            var availableSize = new Size(widthConstraint, heightConstraint);
            foreach (var child in (Layout as Layout).Children)
            {
                var childSize = child.Measure(widthConstraint, heightConstraint);
            }
            return availableSize;
        }

        public override Size ArrangeChildren(Rect bounds)
        {
            foreach (var child in (Layout as Layout).Children)
            {
                child.Arrange(new Rect(bounds.X + bounds.Width / 2, bounds.Y + bounds.Height / 2, child.DesiredSize.Width, child.DesiredSize.Height));
            }
            return bounds.Size;
        }

```

**Comment by xtuzy** [comment]
Today update to rc3, this problem have solved.
