### ISSUE TITLE
VS does not always show compile time errors of MAUI app

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#7061]
### Description

In another WPF app I don't have this problem even on the latest VS preview, so this appears to be related to MAUI builds which is why I am filing this bug here.

Basically, with "Build Only" Error List in VS, the errors often don't seem to show up even though the build output tab shows errors.  I can show these errors by also showing intellisense errors but that causes too much information to be shown.

Note that when building, VS briefly shows the proper errors in the Error List and then they disappear.  So it seems somehow the MAUI build is clearing that list after populating it.

![image](https://user-images.githubusercontent.com/6193288/167991260-a91def21-ceb0-467a-a42b-9bd4e83dcf4c.png)

### Steps to Reproduce

I don't have a repro project for this but just compiling a project with errors causes the error list to not show errors (as shown in screenshot)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

search log for errors instead of using error list.

> VS bug [#1772661](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1772661)

**Comment by janseris** [comment]
Happens to me as well

**Comment by drasticactions** [comment]
If you create a class library project with multiple target frameworks, can you cause the same behavior to occur? Also, are those errors only occurring for a specific target framework?

My guess is that the CLI build is building globally, and the error is on a specific TFM. VS is building a specific target platform, and so it's not showing the error, since it's not there for that TFM.

**Comment by philipag** [comment]
My project targets ios and android.  If <TargetFrameworks>net6.0-ios</TargetFrameworks> then the problem goes away and errors show correctly.  If <TargetFrameworks>net6.0-android</TargetFrameworks>, then the problem happens.  

So perhaps this is specific to Android builds?

**Comment by VincentBu** [comment]
not repro with vs main build(32626.21)

**Comment by janseris** [comment]
Probably fixed

**Comment by philipag** [comment]
No, this still happens in the latest 17.3.0 Preview 2.0.  Attached is a sample that shows this.  Note that you have to set the error console to show "Build Only" errors.  If you also select Intellisense then it can show the error.  This happens on 2 separate computers with this sample, so definitely repeatable.


[NoErrors.zip](https://github.com/dotnet/maui/files/8989332/NoErrors.zip)

**Comment by VincentBu** [comment]
>  If you also select Intellisense then it can show the error.

Yes, `Build + IntelliSense` can show the error while `Build Only` not

**Comment by janseris** [comment]
Visual Studio issue where this is being tracked but not necessarily being solved:
https://github.com/dotnet/roslyn/issues/19693

**Comment by jfversluis** [comment]
Seems it's reported in more correct places. Please track the progress there. Thanks!
