### ISSUE TITLE
Setting images in code (still) doesn't work on Android

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#7074]
### Description

It has been said this would have been fixed but its not. Its broken in RC2 and still broken in RC3. Setting an image from an URL (or from a stream doesn't matter) in code does not show up in Android. Could test it on iOS and its broken there too.

### Steps to Reproduce

```C#
public partial class MyPage : ContentPage
{
    public MyPage()
    {
        InitializeComponent();
        MyImageControl = new Image
        {
        	Source = ImageSource.FromStream(() => new MemoryStream(Convert.FromBase64String("your image base64 string here")))
        // OR:
        //	Source = ImageSource.FromUri(new Uri("your image URL here"))
        };
    }
}
```

```XAML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
		<Image x:Name="MyImageControl" />
</ContentPage>
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, iOS

### Affected platform versions

Android 11, Pixel 5, Android Simulator on Windows, iOS 15

### Did you find any workaround?

See https://github.com/dotnet/maui/issues/7074#issuecomment-1182933173

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro with above code.

**Comment by mgwojciech** [comment]
+1 on this one. I would consider it a critical issue as You cannot render any image that is stored in a container that requires authentication.

**Comment by NonameMissingNo** [comment]
Hey there, as a workaround, you can set them using a binding, something like this:
![image](https://user-images.githubusercontent.com/40233496/178678628-2c759a28-3b1e-4a42-8a4a-8688ebaf89dc.png)
And then set the binding in code with something like:
![image](https://user-images.githubusercontent.com/40233496/178678730-e947f143-3041-444c-8521-7b14e1148bca.png)
Where les is an object that you put the image into, and Image is just a string.

**Comment by mgwojciech** [comment]
Thanks for the reply. I'm not sure if I understand correctly. 
les is an object that represents binding context for the view, is that right?
Path is a string - but what string - should it be url to the image or encoded image, or maybe should I download the image somehow and provide local path?

**Comment by NonameMissingNo** [comment]
Hey there,
Yes, so the object is indeed a binding context for the view.
And the path (in my case anyway) is a direct link to the image (url).
Hope this helps

**Comment by mgwojciech** [comment]
But if the container requires authentication it will return 401 instead of the image, or is there a way to append authorization header to the request for the image?

**Comment by NonameMissingNo** [comment]
If you log in with your application you are already authorized, so you should be fine.

**Comment by NonameMissingNo** [comment]
Otherwise... you can load the images locally as well... give me a second, I think I have some code.

**Comment by NonameMissingNo** [comment]
You can also use something like this to download the image, and then set it.
![image](https://user-images.githubusercontent.com/40233496/178684707-80d277a6-7b77-4ead-85bb-978ea5346051.png)

**Comment by Symbai** [comment]
I can confirm that writing the image to disk first and then load it via `ImageSource.FromFile` works. @NonameMissingNo Thanks for that! (But next time please edit your reply to append more information instead of creating triple posts 🤗).

```XAML
<Image Source="{Binding BindableImage}"/>
```

```C#
public byte[] Image { get; set; }

public ImageSource BindableImage
{
	get
	{
		string cacheDir = FileSystem.Current.CacheDirectory;
		string imageFile = $"{cacheDir}image.jpg";

		File.WriteAllBytes(imageFile, Image);
		return ImageSource.FromFile(imageFile);
	}
}
```

However this workaround also ends up with spamming the user's file system, depending on how many different images you're loading this way. I would still appreciate if this issue is getting addressed soon.

**Comment by mgwojciech** [comment]
Same here. Looks like it works with this work-around, but I would love to see it working from stream. Thanks for the help!

**Comment by joosera** [comment]
This seems to be broken on Windows too, not just Android and iOS.

Saving to filesystem and using ImageSource.FromFile works as a workaround.

**Comment by jsuarezruiz** [comment]
Tested with current net7.0 branch and cannot reproduce the issue:
![image](https://user-images.githubusercontent.com/6755973/193028942-8b4c13c8-ae49-4498-9199-b35ea64f809b.png)

Could you try with the latest version (net7.0 rc1)?

**Comment by joosera** [comment]
Hi @jsuarezruiz.
I just tested this again and I just realised that my earlier comment about this not working on Windows was incorrect.
The reason that it wasn't working for me was because I was disposing the MemoryStream after setting the ImageSource.
After removing the `dispose` (or rather a `using`) this seems to work just fine on Windows on both .net6.0 and .net7.0 versions.

**Comment by Symbai** [comment]
@mattleibow Why did you closed it?

@jsuarezruiz You're setting the source which is not the same as I do. Look at the first post, I create a new image. And it still doesn't work.

```
MyImageControl = new Image
        {
        	Source = ImageSource.FromStream(() => new MemoryStream(Convert.FromBase64String("your image base64 string here")))
        };
```

**Comment by mattleibow** [comment]
@Symbai  sorry about that. I mistook the last comment "this seems to work just fine on Windows on both" to be from the OP, but I was wrong on that.

But, the reason your code does not work is that in the XAML you are creating a view and then the `x:Name` assigns it to the `MyImageControl` field.

However, in your constructor you are replacing the value in the field and not updating the UI at all. To update the UI you will need to rather do `MyImageControl.Source = ImageSource.FromStream(..)`

If I understand your intent, you are wanting to change the image in the UI, not create a totally different control. If you did want to replace the control, you need to both set the `MyImageControl` field AND then also set the page Content to that view. Updating the value in the field does not update the UI.

**Comment by Symbai** [comment]
@mattleibow Ah okay that makes sense. Then I'll try it like @jsuarezruiz did. If it still doesn't work that way (which I assume is not the case) I will create a new issue. Thanks for the explanation.
