### ISSUE TITLE
<CollectionView.EmptyView> is only shown once

### ISSUE THREAD

**Issue by xxjnaxx** [dotnet/maui#7076]
### Description

<CollectionView.EmptyView> is only shown once
![q](https://user-images.githubusercontent.com/104063296/168053535-a9ba3533-96c1-448a-a68b-fed980ec9ee6.PNG)
![qq](https://user-images.githubusercontent.com/104063296/168053543-33ddace4-0c11-4791-acfa-11541850b69e.PNG)

### Steps to Reproduce

1. https://github.com/xxjnaxx/Test2
2. Open Project
3. Open MainPage.xaml
4. remove the comment environment from <CollectionView.EmptyView> 
5. Debug
6. write "xxx" in searchbar
7. string is displayed
8. delete "xxx"
9. write "yyy" in searchbar
10. string is not displayed

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 and up

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main] on Android 11 with above project.

Can search multi times and show string, but after 2 or 3 times, **pop up an Exception: Java.Lang.IllegalStateException**
![ShowString](https://user-images.githubusercontent.com/97647558/168048396-682d4e2c-4e38-42b7-acf2-f3b9bd3ea0ca.gif)
![image](https://user-images.githubusercontent.com/97647558/168048439-de39b0ae-064e-436f-9911-5ed4ab4a59b7.png)


.
