### ISSUE TITLE
Grid & Grid Row Height

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#708]
Hi,

When you set the Row Height to Auto you will still see a bit of the row showing on the screen and the only solution to get rid of it is t set a name for the Row and then set the Height to ZERO

Please make Auto a real Auto so if there is no content then it's ZERO by default unless the user set the height.

Same thing with the Grid itself.

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by Miksier** [comment]
Repro steps, repro project?

**Comment by Redth** [comment]
If this is still an issue in the latest previews, please open a new issue with a sample project which reproduces the issue.  Thanks!
