### ISSUE TITLE
Shell on Windows: No Text

### ISSUE THREAD

**Issue by xxjnaxx** [dotnet/maui#7082]
### Description

![qqq](https://user-images.githubusercontent.com/104063296/168062753-89cdb0ab-83ed-42fb-9607-b8b20f1bd63a.PNG)

For more information see #6361.

### Steps to Reproduce

See #6361

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by PureWeen** [comment]
@xxjnaxx A couple things

1) I don't think this is a shell issue. It seems like a grid issue or a "Grid+Image" issue. If I replace your ItemTempltae with a HorizontalStackLayout it renderers
![image](https://user-images.githubusercontent.com/5375137/168336582-19917f2c-219d-4501-b141-087e41cd24cb.png)

2)  You don't have any of your images specified in your ItemGroup

```XAML

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
```

**Comment by VincentBu** [comment]
not repro with vs main build(32626.21)
