### ISSUE TITLE
missing OnBackButtonPressed function in maui blazor hybrid app

### ISSUE THREAD

**Issue by MarshalOfficial** [dotnet/maui#7096]
### Description

I want to handle the back button pressed in the dotnet Maui blazor hybrid app, in the community I found this thread in StackOverflow:
https://stackoverflow.com/questions/71148792/maui-blazor-hybrid-handle-back-button-pressed-on-android

Now when I attempt to use OnBackButtonPressed, it is missing and I can not find it in ComponentBase.cs class to override it in my components. how is it possible? maybe the SDK version is lower than what should be?

![image](https://user-images.githubusercontent.com/8558078/168086376-2f1b8c15-e143-40e0-a8cb-a10806964029.png)
![image](https://user-images.githubusercontent.com/8558078/168086491-6778da87-9b36-410c-bd8c-0f18e682d480.png)

### Steps to Reproduce

1- create a Maui blazor hybrid app with visual studio 2022 preview community version
2- attempt to create a way to handle back button pressed from StackOverflow thread
https://stackoverflow.com/questions/71148792/maui-blazor-hybrid-handle-back-button-pressed-on-android

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Android 10, Windows 10

**Comment by Eilon** [comment]
Hi, the `OnBackButtonPressed` method is a MAUI method that you can override in a type that derives from MAUI's `Page` class, such as in a code-behind file for a XAML page. It is not a Blazor method.

You can see the virtual method defined here: https://github.com/dotnet/maui/blob/13df56c765a595300d149d8a97011ef800cef73f/src/Controls/src/Core/Page.cs#L318
