### ISSUE TITLE
CollectionView ItemSizingStrategy on Android, causes app to exit on startup

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#7097]
### Description

When the ItemSizingStrategy is used in a CollectionView on the home page of an Android app, the app exits on startup. The same app works on Windows. I dont have a Mac, so I dont know about IOS or Mac Catalyst. I tested it on a Galxay Tab S7.
There is another bug listed as an Empty CollectionView issue, but it may actually be similar to this one if it is an Android app because it looks like it is using ItemSizingStrategy also, bug #7063.

### Steps to Reproduce

Use the app 👍 https://github.com/davidortinau/WeatherTwentyOne. The Android app will exit on startup. It will run fine on the Windows App. If you remove the ItemSizingStrategy parameter from the CollectionView in the WidgetPanel, the Android app will not exit and startup just fine. 

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

Remove ItemSizingStrategy from CollectionView.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Not repro on Windows and Android 12 with above project.
