### ISSUE TITLE
Flyout menu icon and Back button are not visible on the App targeting the Windows platform

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#7099]
### Description

The Flyout menu icon and Back button are not visible on the App targeting the Windows platform.

Refer to the attached screenshot for more details.

![image](https://user-images.githubusercontent.com/81947404/168108869-2c25686c-5782-45e2-8f03-26591d5c5138.png)

### Steps to Reproduce

1. Create a new .NET MAUI Application (RC3)
2. Define a Flyout based Shell visual hierarchy
3. Set Windows as the target platform
4. Build and run the application
5. Flyout menu and after navigating to the child page make the Back button invisible

Make use of the attached project source for reproducing the scenario.

[ShellApp.zip](https://github.com/dotnet/maui/files/8680459/ShellApp.zip)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

Nope

### Relevant log output

```shell
NA
```

**Comment by PureWeen** [comment]
Thank you for reporting this! 

We should have this fixed in GA
https://github.com/dotnet/maui/pull/7031

If you'd like to try the updated styles you can grab them from here
https://github.com/dotnet/maui/tree/main/src/Templates/src/templates/maui-mobile/Resources/Styles
