### ISSUE TITLE
Resizetizer doesn't keep color from SVG

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7101]
### Description

Resizetizer doesn't keep color from SVG. The  difference is how the SVG set the fill color:
- Working - `<path fill="#71559b"`
- Not working - `<defs><style>.cls-1{fill:#71559b;}`

### Steps to Reproduce

1. Download [svg_color_issue.zip](https://github.com/dotnet/maui/files/8680811/svg_color_issue.zip)
2. Is a .NET MAUI App using two SVGs. Notice how is not respecting the fill color in the SVG using a style.
 
![image](https://user-images.githubusercontent.com/6755973/168119615-a4acb807-ce33-4439-8f97-0261c66e0b0e.png)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Windows SDK 10.0.17134.0, Android 11

**Comment by JeffIPV** [comment]
#7115

**Comment by kristinx0211** [comment]
verified repro on android with above project, vs 17.3.0 Preview 2.0 [32511.531.main].

**Comment by JeffIPV** [comment]
Same as #7115 . It wont take the colors done in the <style type="text/css">
Same issues applies to the app icon and splash screen

**Comment by mattleibow** [comment]
Good news! I found the issue: https://github.com/dotnet/maui/pull/7106#issuecomment-1126287817
