### ISSUE TITLE
Can no longer build for iOS, getting error: clang++ exited with code 1

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#7113]
### Description

Building an existing Maui solution for iOS fails with clang++ exited with code 1.
Building for Windows is fine.
Can still build Xamarin iOS apps on the Mac directly.

### Steps to Reproduce

Create a new Maui solution
Pair to Mac
Build for iOS simulator

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

iOS

### Affected platform versions

iOS 15, but I resume all

### Did you find any workaround?

Unfortunately no workaround that Ive found as yet.

**Comment by v-longmin** [comment]
Verified not repro on VS 17.3.0 Preview 1.0 [32427.505.main] with iOS 15.4. repro with default Maui  template project.

**Comment by SteveJML** [comment]
I had the same issue yesterday, i updated the SkiSharp Nuget which resolved for me.

**Comment by JohnHDev** [comment]
Resolved by reinstalling VS2022. Upgrading from RC2 to RC3 may have introduced the issue.
