### ISSUE TITLE
RC3 MauiIcon MauiSplashScreen svg are black when using <style type="text/css">

### ISSUE THREAD

**Issue by JeffIPV** [dotnet/maui#7115]
### Description

svgs for MauiIcon and MauiSplashScreen are black in RC3 release.
It's not getting the colors  in the <style type="text/css">

### Steps to Reproduce

1. See https://github.com/dotnet/maui/issues/7101
2. Edit the csproj file and use this example svg as the MauiIcon or MauiSplashScreen
![appiconfg](https://user-images.githubusercontent.com/57421592/168211389-4a833f02-18d5-4f12-94f2-80c09c9c97ad.svg)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

https://github.com/dotnet/maui/discussions/7014

### Relevant log output

https://github.com/dotnet/maui/discussions/7014

**Comment by JeffIPV** [comment]
#7101

**Comment by VincentBu** [comment]
repro with vs main build (32512.449.main)

**Comment by JeffIPV** [comment]
I ended up going back to RC2 since my project uses a lot of svgs. It would be more work for me to update my svgs to not use <style>
Ran cmd prompt as administrator and ran dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/rc.2.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json --include-previews
