### ISSUE TITLE
[Bug] Unable to find a stable package System.CodeDom with version (>= 4.7.0)

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/maui#712]
### Description

Unable to restore packages after creating a new Maui application. I've followed this [step-by-step guide](https://github.com/dotnet/maui/wiki/Getting-Started), `maui-check` is green, created the `nuget.config` file with the configuration of the additional NuGet sources. I tried restoring the packages from both VS4Mac and VSCode with the same error as a result: `Unable to find a stable package System.CodeDom with version (>= 4.7.0)`

### Steps to Reproduce

1. Download the maui-check and install everything it asks
2. Create a new Maui app with `dotnet new maui` CLI command
3. Add a nuget.config file to the root of your project with the additional sources [described here](https://github.com/dotnet/maui/wiki/Getting-Started#time-to-go) 
4. Restore package from VS4Mac or VSCode (`dotnet restore`)

### Expected Behavior

The packages are restored

### Actual Behavior

Error `Unable to find a stable package System.CodeDom with version (>= 4.7.0)` is returned:

```
/Users/astrakh/Desktop/Sources/AppCatMaui/AppCatMaui.csproj : error NU1103: Unable to find a stable package System.CodeDom with version (>= 4.7.0) [/Users/astrakh/Desktop/Sources/AppCatMaui/AppCatMaui.sln]
/Users/astrakh/Desktop/Sources/AppCatMaui/AppCatMaui.csproj : error NU1103:   - Found 1112 version(s) in dotnet6 [ Nearest version: 6.0.0-alpha.1.20423.5 ] [/Users/astrakh/Desktop/Sources/AppCatMaui/AppCatMaui.sln]
/Users/astrakh/Desktop/Sources/AppCatMaui/AppCatMaui.csproj : error NU1103:   - Found 0 version(s) in xamarin [/Users/astrakh/Desktop/Sources/AppCatMaui/AppCatMaui.sln]
```

### Basic Information

- Version with issue: .NET Maui Preview 3
- Last known good version: N/A
- IDE: VS4Mac (8.9.5 build 4) and VSCode 1.55.0

### Screenshots

<img width="1909" alt="maui-restore-packages" src="https://user-images.githubusercontent.com/3697084/114470390-a67b3900-9ba3-11eb-95c1-db806da04a40.png">

<img width="1861" alt="maui-restore-packages-cli" src="https://user-images.githubusercontent.com/3697084/114470379-a24f1b80-9ba3-11eb-9627-cc5cb254070c.png">

### Workaround

A workaround wasn't found.

**Comment by Chronostasys** [comment]
I went into the same issue yesterday.  
I don't really understand why but removing `<clear/>` from my nuget.config solved my problem.  
My nuget.config:  
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <packageSources>
        <add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
        <add key="xamarin" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" />
    </packageSources>
</configuration>
```

**Comment by alexeystrakh** [comment]
I can confirm that removing `<Clear />` from the nuget.config helps and solves the issue. I was able to restore the packages and run my new .NET MAUI app.

**Comment by MKJ001** [comment]
Instead of removing Clear you can also add `<add key="public"  value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" />` (taken from https://github.com/dotnet/net6-mobile-samples/blob/main/NuGet.config)

**Comment by alexeystrakh** [comment]
> Instead of removing Clear you can also add `<add key="public" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" />` (taken from https://github.com/dotnet/net6-mobile-samples/blob/main/NuGet.config)
> 
> EDIT: Looks like Clear is there for security reasons. Here is more context: [dotnet/net6-mobile-samples#56](https://github.com/dotnet/net6-mobile-samples/pull/56)

This solution works for me as well, thanks!
