### ISSUE TITLE
Wrong rendering of Grid cell content

### ISSUE THREAD

**Issue by Dokug** [dotnet/maui#7122]
### Description

When filling a 24x14 grid with a frame and a label for each cell, the label gets omitted on a semi-random basis as seen in the first picture.
When omitting the frames, all labels are shown, as seen in the second picture.
I have only tested this on Windows, not yet on any other platform.

I don't think this is expected behavior, but if it is, I apologize.

Best regards,
Dokug

![image](https://user-images.githubusercontent.com/63102276/168187623-c52a8cbe-e5e9-42e4-af14-447f93d3329b.png)
![image](https://user-images.githubusercontent.com/63102276/168187668-810753be-63c9-4eaa-86f5-e11085aa6cdf.png)

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Replace the MainPage.xaml ContentPage Content with:

```
<Grid x:Name="ScreenGrid"
              RowDefinitions="*,*,*,*,*,*,*,*,*,*,*,*,*,*"
              ColumnDefinitions="*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*"/>
```

3. In the MainPage.xaml.cs constructor add the following:
```
for (int row = 0; row < ScreenGrid.RowDefinitions.Count; row++)
{
    for (int col = 0; col < ScreenGrid.ColumnDefinitions.Count; col++)
    {
        Label label = new Label
        {
            Text = "A"
        };

        ScreenGrid.Add(new Frame(), col, row);
        ScreenGrid.Add(label, col, row);
    }
}
```
4. Run the app to see the missing labels
5. Comment out the line adding the frames to the ScreenGrid to see the difference

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.17134.0

**Comment by v-longmin** [comment]
Verified repro on Windows10 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro with above project.

**Comment by hartez** [comment]
If you're looking for a workaround until we get this fixed, you can add `label.ZIndex = 10;` to force the Labels to have a higher z-index than the Frames; that will prevent the Labels from being hidden.
