### ISSUE TITLE
Button/ImageButton Opacity property affect full button 

### ISSUE THREAD

**Issue by AllenMiaoFil** [dotnet/maui#7124]
### Description

I created a Icon Button with a 'BackgroundColor' and 'BorderColor', When I tried to use 'Opacity' in VSM on different State to update Icon Color , I found 'BackgroundColor' and 'BorderColor' were affected at same time. Same issue on Button.

### Steps to Reproduce

1. Create a ImageButton or Button with Border, BorderColor and BackgroundColor.
2. Set different Opacity value for different State in VSM.
3. You will see the button color will be affected on full button. 

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS, I was *not* able test on other platforms

### Affected platform versions

Windows 10

**Comment by kristinx0211** [comment]
@AllenMiaoFil  I create a project to repro your issue, could you check if this is the same as you mean. let me know if I miss something. project: [MauiApp1.zip](https://github.com/dotnet/maui/files/8686129/MauiApp1.zip)
https://user-images.githubusercontent.com/99457000/168262823-7d9d95c7-83be-4102-9a03-4489a76bdff7.mp4

**Comment by AllenMiaoFil** [comment]
Hey @kristinx0211 I did some update on your code, Actually we just want to modify Text opacity or just Image Opacity, You can see the full button are affected by Opacity, The BorderColor, The BackgroundColor, all staff were changed on button.      [MauiApp1.zip](https://github.com/dotnet/maui/files/8686429/MauiApp1.zip)

**Comment by davidortinau** [comment]
This is how opacity natively works and isn't a bug. To resolve the issue use the below.

To modify just the text opacity, you'll want to set a color that includes that value. I see in your example on the Button you have 

```
<VisualState.Setters>
     <Setter Property="Opacity" Value="0.79"/>
</VisualState.Setters>
```

To JUST change the Button's text opacity, assuming it was red (#CC0000), then you could assign it the value #C9CC0000

```
<VisualState.Setters>
     <Setter Property="TextColor" Value="#C9CC0000"/>
</VisualState.Setters>
```

Depending on how you use the hex color values, the alpha may be leading or trailing.

https://docs.microsoft.com/en-us/dotnet/maui/user-interface/graphics/colors
