### ISSUE TITLE
Button/ImageButton has space between button and border in its corner 

### ISSUE THREAD

**Issue by AllenMiaoFil** [dotnet/maui#7128]
### Description

When I tried to use Button/ImageButton with Border and set CornerRadius, it has some space in corner between border and button/ImageButton.
And When I do not set CornerRadius, there is a default Radius in Windows, But it is no Radius on MacOS. 

### Steps to Reproduce

1. Create Button or ImageButton with Border and no CornerRadius.
2. Create another button or ImageButton with Border and CornerRadius is Zero. 
 
You will see the First Button/ImageButton has **two issues:**

> There is a default CornerRadius value on Windows but it is zero on MacOS version.  
> It has some some Space between button/ImageButton and border in CornerRadius.(enlarge screenshot)
![Untitled](https://user-images.githubusercontent.com/100921408/168227947-1f239f99-ccbc-4e57-aacc-d88ba039c3cd.png)

Second Button/ImageButton you will see all works well.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Window 10

**Comment by kristinx0211** [comment]
verified on windows with vs 17.3.0 Preview 2.0 [32511.531.main].
1. repro there is a default CornerRadius value on Windows though no CornerRadius value set to button. 
2. not repro for some space in corner between border and button. seems it is ok.
```
<Button  BorderWidth="5" BorderColor="Pink"
                WidthRequest="200"
                Text="Click me"                        
                HeightRequest="200"
                HorizontalOptions="Center" />

<Button  BorderWidth="0" BorderColor="Red" CornerRadius="0" Text="hi" WidthRequest="150"/>
```

![image](https://user-images.githubusercontent.com/99457000/168243429-a535f912-7b8e-478d-a5db-9ad9aee5395e.png)

**Comment by VincentBu** [comment]
Verified with vs main build. Button has a round corner by default on Windows and Mac.

**Comment by AllenMiaoFil** [comment]
@kristinx0211 Your code is correct, and could you please set a same color both on BackgroundColor and BorderColor, if they are same. should look like a button without border, but it same has some blank space there.

**Comment by kristinx0211** [comment]
@AllenMiaoFil thanks for your update, I can the the space between button and border even though it's small. thanks.
![image](https://user-images.githubusercontent.com/99457000/168254390-abc347d9-82c0-4113-8fe8-6ed2937ba587.png)
