### ISSUE TITLE
SVG images with inner styles shows are incorrect

### ISSUE THREAD

**Issue by AlexeyZhukoff** [dotnet/maui#7129]
### Description

SVG images with inner styles shows are incorrect

### Steps to Reproduce

1. download example
2. unpack example 
3. run example

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

iOS, Android, macOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15.4, Android 11

[svgbug.zip](https://github.com/dotnet/maui/files/86851
<img width="779" alt="Screen Shot 2022-05-13 at 11 47 54" src="https://user-images.githubusercontent.com/14820834/168236481-7797ad28-300c-4da3-a932-53a8e60d8d11.png">
02/svgbug.zip)

**Comment by VincentBu** [comment]
looks like dup with #7115

**Comment by JeffIPV** [comment]
dup with #7101  as well
