### ISSUE TITLE
[Android] CornerRadius ignores density

### ISSUE THREAD

**Issue by ChasakisD** [dotnet/maui#7130]
### Description

Applying CornerRadius to a Button is in pixels rather than dp. BorderWidth is in dp tho. As I can see in BorderDrawable  
https://github.com/dotnet/maui/blob/026e3b6ab66fb44f6d2608063d166f42189814e0/src/Core/src/Platform/Android/BorderDrawable.cs#L296
Scale is ignored and CornerRadius is applied in pixels.

### Steps to Reproduce

```xml
<Button
    BorderColor="Red"
    BorderWidth="8"
    CornerRadius="32"
    HeightRequest="64"
    Text="Continue">
    <Button.Background>
        <LinearGradientBrush StartPoint="0,0" EndPoint="1,0">
            <GradientStop Offset="0" Color="Green" />
            <GradientStop Offset="1" Color="DarkGreen" />
        </LinearGradientBrush>
    </Button.Background>
</Button>
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android 12, not repro on Windows. Sample Project: [MauiApp6.zip](https://github.com/dotnet/maui/files/8685592/MauiApp6.zip)
