### ISSUE TITLE
[Tooling] [Scenario Day] XAML Live Preview not update selection

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7132]
### Description

Using XAML Live Preview, we select the option to select a View and view its properties. After doing this, if we use Hot Reload, the control is updated but the selection and related properties are not updated.

![xaml-live-preview-1](https://user-images.githubusercontent.com/6755973/168252158-2ca84486-e115-4c16-a832-cf30c0fc9fdb.gif)

### Steps to Reproduce

1. Create a .NET MAUI App from template.
2. Launch the App and debugging open the XAML Live Preview. Then, select any view (for example a Label).
3. Update the Label Text.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Windows SDK 10.0.17134.0, Android 11

**Comment by drasticactions** [comment]
@jsuarezruiz Can you file this issue in AzDo under either Hot Reload or XAML Live Preview?

While I think we can make changes to MAUI itself to make that work, it's probably going to require tooling changes that we'll need to update too, and it's something we should own.

**Comment by VincentBu** [comment]
verified with vs main build(32626.21). Hot reload updates the element info
before:
![image](https://user-images.githubusercontent.com/44959937/175863586-b2c656a2-091c-4dd0-956a-6ff0bf06415f.png)

after:
![image](https://user-images.githubusercontent.com/44959937/175863424-d7461911-f359-457e-a25b-eb26f78b19ea.png)
