### ISSUE TITLE
[Scenario Day] Hot Reload not working updating styles using AppThemeBinding

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7133]
### Description

Trying to update styles using **AppThemeBinding** with Hot Reload doesn't work.

![update-style-not-working](https://user-images.githubusercontent.com/6755973/168252839-051f8f3c-68bb-4274-b83c-dea43a934942.gif)

### Steps to Reproduce

1. Create a new .NET MAUI App from template.
2. Launch the App and try to modify the Button Background from `Resources/Styles/Styles.xaml`

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Windows SDK 10.0.17134.0, Android 11

**Comment by drasticactions** [comment]
File this to AzDo under the Hot Reload path. This is a tooling issue, it can't be fixed here.

**Comment by kristinx0211** [comment]
verified repro with vs 17.3.0 Preview 3.0 [32618.28.main].
