### ISSUE TITLE
[Android] [ScenarioDay] The default size of SearchBar is wrong, it does not fill the space

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7137]
### Description

The default size of SearchBar is wrong, it does not fill the space.
![image](https://user-images.githubusercontent.com/6755973/168256074-0be66fea-7928-40fc-9c36-3c72ee15635e.png)

### Steps to Reproduce

1. Create a .NET MAUI App from template.
2. Add a SearchBar in MainPage.
3. Launch the App on Android.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android 12. Sample Project: [7137.zip](https://github.com/dotnet/maui/files/8686277/7137.zip)

**Comment by PureWeen** [comment]
related https://github.com/dotnet/maui/issues/2956

**Comment by Christerad** [comment]
Any Update on this one ?

**Comment by jfversluis** [comment]
I'm creating a PR for this now, as a workaround you should be able to use this today: 

#if ANDROID
Microsoft.Maui.Handlers.SearchBarHandler.Mapper.AppendToMapping("FullWidth", (handler, control) =>
{
	handler.PlatformView.MaxWidth = int.MaxValue;
});
#endif

You can put this code somewhere in the startup path of your app, doesn't really matter where.
