### ISSUE TITLE
Content inside a Frame layout is not visible.

### ISSUE THREAD

**Issue by uragonda-rajesh** [dotnet/maui#7139]
### Description

Label inside a frame layout is not visible.

### Steps to Reproduce

Run this.

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:VT.Views"
             xmlns:resources="clr-namespace:VT.Resources"
             x:Class="VT.Views.Demo">
    <ContentPage.Resources>
        <Style x:Key="Demostyle"
           TargetType="Label">
            <Setter Property="FontSize"
                Value="Medium" />
            <Setter Property="HorizontalOptions"
                Value="Center"/>
            <Setter Property="VerticalOptions"
                Value="Center"/>
            <Setter Property="HorizontalTextAlignment"
                Value="Center"/>
        </Style>
    </ContentPage.Resources>

    <ContentPage.Content>
        <ScrollView VerticalOptions="FillAndExpand"
                    VerticalScrollBarVisibility="Always">
            <StackLayout BackgroundColor="Red" Padding="16,16,16,16" Orientation="Vertical" VerticalOptions="FillAndExpand">
                <Label HorizontalOptions="FillAndExpand"
                       Text="Sample label"
                       Margin="10,10,10,10"
                       TextColor="White"
                       VerticalOptions="CenterAndExpand">
                    <!--// remove VerticalOptions="CenterAndExpand" line to resolve-->
                </Label>
                <Frame Margin="10,10,10,10">
                    <Label Text="Sample button" Padding="14,0,14,0" HorizontalOptions="FillAndExpand" Style="{StaticResource Demostyle}"/>

                    <Frame.GestureRecognizers>
                        <TapGestureRecognizer Command="{Binding LoginCommand}"/>
                    </Frame.GestureRecognizers>
                </Frame>
            </StackLayout>
        </ScrollView>
    </ContentPage.Content>
</ContentPage>
```

```
namespace VT.Views
{
    public partial class Demo : ContentPage
    {
        public Demo()
        {
            InitializeComponent();
        }
    }
}

```

![Frame](https://user-images.githubusercontent.com/11378500/168257277-d6adf3bf-74a3-4767-a802-aa8f309feb42.jpeg)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

Need to remove `VerticalOptions="CenterAndExpand" `of the Label above the Frame layout to make the Label inside the Frame visible.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android12. Sample Project: [MauiApp10.zip](https://github.com/dotnet/maui/files/8686040/MauiApp10.zip)

**Comment by mobycorp** [comment]
I apologize for getting snarky, but the Frame element has been a problem child for MONTHS!! The layout inside a frame has NEVER worked!!!  Please fix this ASAP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mobycorp** [comment]
To confirm: I did employ a workaround using a Rectangle in place of the frame with a lower Zindex so that it would be guaranteed to be behind the VerticalStackLayout that contains the other controls I wanted framed...

**Comment by PureWeen** [comment]
> Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android12. Sample Project: [MauiApp10.zip](https://github.com/dotnet/maui/files/8686040/MauiApp10.zip)

This appears to be fixed
<img width="190" alt="image" src="https://user-images.githubusercontent.com/5375137/176244064-4dff6596-eec3-4972-bdf5-562ee910e48f.png">


If you're still seeing this once SR2 comes out let me know
