### ISSUE TITLE
Maui Blazor Hot Reload Not Working With CSS Isolation Files

### ISSUE THREAD

**Issue by cabbytech** [dotnet/maui#7142]
### Description

When using css isolation files such as xxx.razor.css hot reload does not apply the changes.

### Steps to Reproduce

1. Create a new Maui Blazor App.
2. Add a new css isolation file E.G. index.razor.css
3. Run the app.
4. Add some css to the index.razor.css file  `h1{
    color:blue;
}`
5. On save there is no update in the Index page.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Visual Studio Version 17.3.0 Preview 1.0

### Did you find any workaround?

None

**Comment by TanayParikh** [comment]
Related to https://github.com/dotnet/maui/issues/5751; @mkArtakMSFT @SteveSandersonMS this user is on 17.3 Preview 1 (the version of VS which was to have the fix according to https://github.com/dotnet/maui/issues/5751). Did the fix get moved to a different release?

**Comment by drasticactions** [comment]
Static CSS Hot Reload is supported in 17.3 Preview 1, compiled CSS is not. That might land in Preview 2.

IMO I would close this issue and move this conversation to that feedback item. This issue is related to Visual Studio tooling and is unrelated to anything anyone could do in this repo.

**Comment by mkArtakMSFT** [comment]
@mcumming do you have a tracking issue for this we can point customers to and close this instead?

**Comment by mkArtakMSFT** [comment]
Assigning to @mcumming per offline conversation.

**Comment by ForeverFast** [comment]
any updates?
