### ISSUE TITLE
[Windows] [Scenario Day] Crash using ScrollTo with a grouped ListView

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7145]
### Description

Crash using ScrollTo with a grouped ListView.

![image](https://user-images.githubusercontent.com/6755973/168268352-9e8c7acc-0f4f-4b4e-83d6-a9fd0548006c.png)

### Steps to Reproduce

1. Download [ListViewDemos.zip](https://github.com/dotnet/maui/files/8686395/ListViewDemos.zip)
2. Launch the App on Windows and navigate to the Scroll To grouped list.
3. Tap the Scroll Button.
 

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows App SDK 17134

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Windows. Sample Project: [ListViewDemos.zip](https://github.com/dotnet/maui/files/8696489/ListViewDemos.zip)
