### ISSUE TITLE
[Bug] Fix Issue with Compat Renderers not being able to easily locate Fonts

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#715]
### Description

Currently when using a Compat Renderer to locate a font you have to specify something like

```
#if __ANDROID__
			string fontFamily = "ionicons.ttf#";
#elif WINDOWS
			string fontFamily = "Assets/ionicons.ttf#ionicons";
#else
			string fontFamily = "ionicons.ttf#";
#endif
```

On the handlers it works with just "ionicons"

We need to wire this up so it works on the Legacy Renderers

**Comment by Redth** [comment]
@mattleibow is there still outstanding work / action here?

**Comment by jsuarezruiz** [comment]
@mattleibow I think we can close this issue, could you confirm?

**Comment by hartez** [comment]
Nope, not fixed yet.

**Comment by kristinx0211** [comment]
Not reproduced.

**Comment by mattleibow** [comment]
This may no longer be needed with "renderers" actually being "handlers" now.
