### ISSUE TITLE
[Windows] [Scenario Day] CollectionView EmptyView using View not appear

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7151]
### Description

CollectionView EmptyView using View not appear.
![cv-windows-emptyview-issue-2](https://user-images.githubusercontent.com/6755973/168272086-bd8a5933-2646-4466-b864-78ce95a4231f.gif)

### Steps to Reproduce

1. Download [CollectionViewDemos.zip](https://github.com/dotnet/maui/files/8686453/CollectionViewDemos.zip)
2. Launch the App on Windows and navigate to the EmptyView sample using View.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17134.0

**Comment by hartez** [comment]
This is working correctly in the latest version.
