### ISSUE TITLE
[Android] Updating MainPage with a NavigationPage does not display page content

### ISSUE THREAD

**Issue by paulvarache** [dotnet/maui#7153]
### Description

When updating the Application's MainPage using a NavigationPage, the page is updated, but its content is not displayed.

The is displayed on iOS.

When application is loaded (MainPage):
<img src="https://user-images.githubusercontent.com/5550089/168271534-23952b7e-9271-4812-9123-89960e757332.png" width="200px"/>

When button is clicked. Note that the page is updated correctly as the NavigationBar has the correct title, but no content is displayed:
<img src="https://user-images.githubusercontent.com/5550089/168271581-f0337d11-9576-4f40-ae9a-136fde034118.png" width="200px"/>

### Steps to Reproduce

1. Create a new Maui App
2. Add a second ContentPage
3. Update the Application's MainPage on a button click from the MainPage using `Application.Current.MainPage = new NavigationPage(new SecondPage());`

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by paulvarache** [comment]
Somewhat related to https://github.com/dotnet/maui/issues/2517, but behaves slightly differently

**Comment by kristinx0211** [comment]
verified repro on android 12, the second page displays incorrect content though it is not blank, but it is also normal on IOS.
Android 12:
![image](https://user-images.githubusercontent.com/99457000/168714611-018a5b92-c647-4f18-ba4a-d9945bd973b7.png)
IOS 15.4:
![image](https://user-images.githubusercontent.com/99457000/168714811-0a31efb5-7f9a-4f5c-9487-8c78bd85e70b.png)

**Comment by kristinx0211** [comment]
verified repro on android 12, the second page displays incorrect content though it is not blank, but it is also normal on IOS. repro project: [MauiApp14.zip](https://github.com/dotnet/maui/files/8704591/MauiApp14.zip)
Android 12:
![image](https://user-images.githubusercontent.com/99457000/168714611-018a5b92-c647-4f18-ba4a-d9945bd973b7.png)
IOS 15.4:
![image](https://user-images.githubusercontent.com/99457000/168714811-0a31efb5-7f9a-4f5c-9487-8c78bd85e70b.png)
