### ISSUE TITLE
[Windows] [Scenario Day] Frame is cutted at the bottom on Windows

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7154]
### Description

Frame is cutted at the bottom on Windows.
![image](https://user-images.githubusercontent.com/6755973/168272729-2577a68a-0bfa-4268-81e1-a6b6acea0d13.png)

### Steps to Reproduce

1. Download [FrameDemos.zip](https://github.com/dotnet/maui/files/8686593/FrameDemos.zip)
2. Launch the App on Windows. 

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows App SDK 17134

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Not repro on Windows. Sample Project: 
[FrameDemos.zip](https://github.com/dotnet/maui/files/8696591/FrameDemos.zip)
![image](https://user-images.githubusercontent.com/97647558/168506654-87806377-4c08-4848-8961-619040a07513.png)

**Comment by hartez** [comment]
Duplicate of #9099
