### ISSUE TITLE
[Windows] [Scenario Day] Shell SearchBarHandler only show the first item and and not correctly

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7155]
### Description

Shell SearchBarHandler only show the first item and and not correctly.
![shell-search-incorrect](https://user-images.githubusercontent.com/6755973/168275088-af2daf16-7536-4d7d-baa7-63ab91ebb12f.gif)

### Steps to Reproduce

1. Download [Shell.zip](https://github.com/dotnet/maui/files/8686678/Shell.zip)
2. Type something in the search bar.
 

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17134.0

**Comment by VincentBu** [comment]
I try the project on Windows with vs main build[32516.290.main] and there is no SearchBar(SearchBar is displayed on Android):
![image](https://user-images.githubusercontent.com/44959937/168730396-665a7a41-ac2b-4ed8-a080-e6fbee65eeb7.png)

Should we create a new issue for this?

**Comment by kristinx0211** [comment]
verified repro on windows with 17.3.0 Preview 3.0 [32618.28.main].
![image](https://user-images.githubusercontent.com/99457000/174528967-850b408c-9dda-4672-aaaa-38e82dcb8797.png)
