### ISSUE TITLE
[Bug] Fix windows DPI code on FontImages to account for Screen Changes

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#716]
### Description

Currently the FontImageHandler code uses GetForCurrentViewto retrieve the DPI

```
var dpi = Math.Max(_minimumDpi, Windows.Graphics.Display.DisplayInformation.GetForCurrentView().LogicalDpi);
```

But this API isn't being surface with WinUI3

https://github.com/microsoft/microsoft-ui-xaml/issues/4205#issuecomment-780204896

On WinUI3 you can watch the XamlTree

> For DPI changes, I do recommend to listen for changes on the XamlRoot's Changed event. The XamlRoot is the root of the visual tree and you can get it from any UI Element on your UI. For example, mybutton.XamlRoot. Then you can use XamlRoot.RasterizationScale to get the number of raw physical pixels for each view pixel.

for DPI changes 

So the FontImage code on windows will need to look for changes to the XamlRoot and then propagate those to the FontImageSource.  I'm not sure exactly what the earliest point in time is that you can access the XamlRoot but inside the linked issue it references using the Loaded event (which currently fires after we typically load our fonts)

**Comment by hartez** [comment]
See also #3250

**Comment by mattleibow** [comment]
This should be fixed in Preview 14. Please open another issue if there are still problems.
