### ISSUE TITLE
FlyoutItem disappear when Shell.FlyoutFooterTemplate is present

### ISSUE THREAD

**Issue by piferrari** [dotnet/maui#7164]
### Description

I use the default MAUI Template proposed by Visual Studio. I made changes only in the file `AppShell.xaml`.

When i add `<Shell.FlyoutHeaderTemplate>`, `<Shell.ItemTemplate>`, `<Shell.FlyoutBackground>` and some `FlyoutItem` all work fine in the Android Emulator and on real Samsung Device. I can see a correct Flyout menu.

But, when i add an `<Shell.FlyoutFooterTemplate>`, all FlyoutItem disappear. When i use the emulator, i can change some value like an `HeightRequest` and the FlyoutItem reappear. On the Samsung device, i can change the orientation to landscape and the FlyoutItem reappear.

If i remove the `<Shell.FlyoutFooterTemplate>` all work fine again.

Here is my AppShell.xaml code:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="FlyoutApp.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:sys="clr-namespace:System;assembly=netstandard"
    xmlns:local="clr-namespace:FlyoutApp"
    FlyoutWidth="300"
    Shell.FlyoutBehavior="Flyout">

    <Shell.FlyoutHeaderTemplate>
        <DataTemplate>
            <Grid BackgroundColor="White">
                <Image
                    Aspect="Fill"
                    BackgroundColor="Transparent"
                    Source="cpne_t.png" />
            </Grid>
        </DataTemplate>
    </Shell.FlyoutHeaderTemplate>

    <!-- 
        With 6.0.300-rc.3.5667 MAUI version, Shell.FlyoutFooter cause bug:
        FloutItem disapear...
    -->
    <!--<Shell.FlyoutFooterTemplate>
        <DataTemplate>
            <FlexLayout
                Direction="Row"
                AlignItems="Center"
                JustifyContent="SpaceEvenly"
                HeightRequest="30"
                WidthRequest="{Binding Source={RelativeSource AncestorType={x:Type Shell}}, Path=FlyoutWidth}">
                <Label Text="© pif@piferrari.org"/>
                <Label Text="{Binding StringFormat=\{0:yyyy\}, Source={Static Member=sys:DateTime.Now}}" />
            </FlexLayout>
        </DataTemplate>
    </Shell.FlyoutFooterTemplate>-->

    <Shell.FlyoutBackground>
        <!-- StartPoint defaults to (0,0) -->
        <LinearGradientBrush EndPoint="0,1">
            <GradientStop Color="White"
                          Offset="0.6" />
            <GradientStop Color="#0fa590"
                          Offset="0.8" />
            <GradientStop Color="#005a95"
                          Offset="1.0" />
        </LinearGradientBrush>
    </Shell.FlyoutBackground>

    <Shell.ItemTemplate>
        <DataTemplate>
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="80" />
                    <ColumnDefinition Width="150" />
                </Grid.ColumnDefinitions>
                <Image
                    Source="{Binding FlyoutIcon}"
                    Margin="5,10,0,5"
                    HorizontalOptions="Center"
                    VerticalOptions="Center"
                    HeightRequest="30"
                    WidthRequest="30" />
                <Label Grid.Column="1"
                       Text="{Binding Title}"
                       Margin="5,10,0,5"
                       VerticalTextAlignment="Center" />
            </Grid>
        </DataTemplate>
    </Shell.ItemTemplate>

    <FlyoutItem
		Title="Java"
		Icon="java_menu.png">
        <ShellContent
            ContentTemplate="{DataTemplate local:MainPage}"
            Route="MainPage" />
    </FlyoutItem>

    <FlyoutItem
		Title="C#"
		Icon="csharp_menu.png">
        <ShellContent
            ContentTemplate="{DataTemplate local:MainPage}"
            Route="MainPage" />
    </FlyoutItem>

    <FlyoutItem
		Title="Settings"
		Icon="settings_menu.png">
        <ShellContent
            ContentTemplate="{DataTemplate local:MainPage}"
            Route="MainPage" />
    </FlyoutItem>
</Shell>
```

I think it is an issue or I don't know how to fix this problem.

# Visual Studio
Microsoft Visual Studio Enterprise 2022 (64 bits) - Preview
Version 17.3.0 Preview 1.0

# MAUI
6.0.300-rc.3.5667

# Without `Shell.FlyoutFooterTemplate`
<img src="https://user-images.githubusercontent.com/736192/168311423-1ab7af7c-dbfd-40ba-ab30-d8d7980571c2.png"  width=50% height=50%>

# With `Shell.FlyoutFooterTemplate`
<img src="https://user-images.githubusercontent.com/736192/168311892-ee72425f-8c10-40a6-9207-059fc2d3aaf8.png"  width=50% height=50%>

Thank you for your job.

Best Regards

### Steps to Reproduce

1. Create an new MAUI application in Visual Studio
2. Made the changes listed above
3. Build and run on Android Emulator

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Pixel 5 API 30 (Android 11.0 - API 30) default emulator

**Comment by PureWeen** [comment]
This will be fixed in GA

**Comment by piferrari** [comment]
Perfect 👍.

Once again, thank for your work :)

Best Regards.

piferrari

**Comment by epsmae** [comment]
With the GA Version it works fine on windows, on Android not even the hamburger menu is showing:
![image](https://user-images.githubusercontent.com/22543513/169955157-74920ce5-e906-4e47-894c-0a50f496a51d.png)
![image](https://user-images.githubusercontent.com/22543513/169955276-509a225b-a7a8-47d2-b77e-7c64e8543bc5.png)



It is even worse with:
* Microsoft.Maui.Dependencies 6.0.312
* Microsoft.Maui.Extensions 6.0.312


```
Installed Workload Ids      Installation Source
-----------------------------------------------
maui-windows                VS 17.3.32519.111
maui-maccatalyst            VS 17.3.32519.111
maccatalyst                 VS 17.3.32519.111
maui-ios                    VS 17.3.32519.111
ios                         VS 17.3.32519.111
maui-android                VS 17.3.32519.111
android                     VS 17.3.32519.111
```
