### ISSUE TITLE
Publishing a Maui Windows app SelfContained=false doesn't run

### ISSUE THREAD

**Issue by eerhardt** [dotnet/maui#7170]
### Describe the bug
When I try to package, install, and run a Maui Windows app with SelfContained=false, it doesn't run. It pops up a dialog:

![image](https://user-images.githubusercontent.com/8291187/162843615-ba5c88d4-e53d-4c5d-9c86-c97a520cb2de.png)

The reason this happens is because this is generated into the runtimeconfig.json file:

```json
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.0"
      },
      {
        "name": "Microsoft.Maui.Core",
        "version": "**FromWorkload**"
      },
      {
        "name": "Microsoft.Maui.Controls",
        "version": "**FromWorkload**"
      },
      {
        "name": "Microsoft.Maui.Essentials",
        "version": "**FromWorkload**"
      }
    ],
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

Notice the `FromWorkload` things for `Microsoft.Maui.*`. These things shouldn't be in the runtimeconfig.json file. Removing them allows the app to proceed.

### To Reproduce
0. Get Maui installed on your machine
1. `dotnet new maui`
2. Edit the .csproj to have:

```xml
		<WindowsPackageType>None</WindowsPackageType>
		<WinUISDKReferences>false</WinUISDKReferences>

		<SelfContained>false</SelfContained>
```
3. `dotnet build -c Release -f net6.0-windows10.0.19041.0`
4. Try to run the .exe in the `bin\Release\net6.0-windows10.0.19041.0\win10-x64` folder.

### Further technical details
```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.300-preview.22207.16
 Commit:    1827808c3e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\git\maui\bin\dotnet\sdk\6.0.300-preview.22207.16\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.300-preview.22207.16 [C:\git\maui\bin\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [C:\git\maui\bin\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\git\maui\bin\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\git\maui\bin\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

cc @dsplaisted

**Comment by jonathanpeppers** [comment]
@dsplaisted I moved this, thanks.

Should `%(RuntimePackAlwaysCopyLocal)` be based on if `$(SelfContained)` is `true` and `$(TargetPlatformIdentifier)` is `Windows`? Or just set it no matter what?

**Comment by gerhard17** [comment]
I have the same problem. Compiling from Visual Studio 17.3.0 Preview 2.0 (windows)

**Comment by mattleibow** [comment]
@dsplaisted I tried setting this to true but then it fails for class libraries:

> C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(430,5): error NETSDK1082: There was no runtime pack for Microsoft.Maui.Core available for the specified RuntimeIdentifier 'any'. 


It seems this ResolveRuntimePackAssets only runs on windows

[msbuild (8).zip](https://github.com/dotnet/maui/files/8981822/msbuild.8.zip)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 5.0. Not repro on windows platform with cmd.
![Screenshot 2023-08-07 142035](https://github.com/dotnet/maui/assets/77434865/6d9b1d8b-6e3f-4039-b18a-9b00aea74be1)
