### ISSUE TITLE
CarouselView Swiping Disrupted When in Shell

### ISSUE THREAD

**Issue by cbaer-extron** [dotnet/maui#7177]
### Description

When a CarouselView is on a page within the Shell layout, The swipe gesture of the CarouselView is picked up by the Shell instead.  This causes the "pull-to-refresh" style indicator to be revealed.
CarouselView inside Shell
https://user-images.githubusercontent.com/101732760/168378016-6dcb0def-19fe-4494-a98a-ae86918da67b.mp4

CarouselView without Shell
https://user-images.githubusercontent.com/101732760/168378072-ad214327-878d-4a42-9982-f45590a64d2f.mp4

Demo App:
https://github.com/cbaer-extron/BugReports/tree/main/CarouselViewTestApp

### Steps to Reproduce

1.  Create a new Maui App that uses Shell
2.  Add a CarouselView to the MainPage
3.  Create a List of strings to use as the source for the CarouselView and assign it to the CarouselView's ItemsSource.
4.  in Xaml, define an ItemTemplate that defines the size and attributes of the CarouselView item, and that contains a Label bound to the content of the string list.
5.  Run the app on Android.  
6.  Try swiping the CarouselView.  Notice that the "Pull-to-Refresh" indicator for the Shell appears, but that the CarouselView doesn't swipe.
7.  Try holding finger down on the screen for a second or two before swiping and notice that the CarouselView swipes normally.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
This should be fixed in GA by the following PR
https://github.com/dotnet/maui/pull/6955
