### ISSUE TITLE
[Android] Image is clipped during animation

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#7182]
### Description

On Windows I don't see this clipping, but on Android it's super obvious when doing a rotation and a translate together.

https://user-images.githubusercontent.com/41873/168398831-dcde3c9b-7ac5-4f36-ab5a-8eb2cdb368a8.mp4

### Steps to Reproduce

[Animations.zip](https://github.com/dotnet/maui/files/8691658/Animations.zip)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

all

**Comment by VincentBu** [comment]
repro on Android emulator with vs main build[32516.290.main]
