### ISSUE TITLE
Search Handler visual and functional bug in subtabs

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#7184]
### Description

My application has 2 main tabs (bottom tabs) and each main tab has two categories (top Tabs)
Boys/Girls Bottom tabs
Group1/Group2 top tabs

![HandlerSearch1](https://user-images.githubusercontent.com/2603287/168412173-39bc6e13-67cb-41bf-a01e-3fbb13d6c3bd.jpg)

When alternating through the top tabs, search handlers are added of top of each other .....

![HandlerSearch2](https://user-images.githubusercontent.com/2603287/168412285-f895b5ad-4941-4901-aa3a-dc527c800eb4.jpg)

Also the search handler only searches the first tab page view model

![HandlerSearch3](https://user-images.githubusercontent.com/2603287/168412387-891ee7d7-c2e8-4f8a-8261-d1479c5d1c18.jpg)

### Steps to Reproduce

Use the example on Github below:

https://github.com/pierre01/SearchHandlerAndroidBug

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 API 30 - Windows 11 Pro 22000.348

### Did you find any workaround?

no but you can reset the visual state by selecting a different  bottom tab

**Comment by pierre01** [comment]
An example of What I observed on another app...

https://user-images.githubusercontent.com/2603287/168457943-0b126763-6b5e-46c3-8472-d8595bcd96f7.mp4

**Comment by kristinx0211** [comment]
verified repro on android 11 using above project with vs 17.3.0 Preview 2.0 [32511.531.main].

**Comment by pierre01** [comment]
Fixed with newer Versions
