### ISSUE TITLE
Scrollview stops working with a margin set on 1st element

### ISSUE THREAD

**Issue by codeaphex** [dotnet/maui#7186]
### Description

The scrollview stops working if a margin is set on the first element inside the view.
Tested with different elements inside (StackLayout/Grid).
Windows is not affected. Not tested on iOS, Mac.

### Steps to Reproduce

1. Use a scrollview
2. Set a margin on the first element inside the scollview
3. The scrollview stops working -> scrolling is disabled

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

Android

### Affected platform versions

Android 11+

### Did you find any workaround?

Set the margin on an element further down the chain.

**Comment by codeaphex** [comment]
[ScrollView_Repro.zip](https://github.com/dotnet/maui/files/8693090/ScrollView_Repro.zip)
Repro project, basically the default project with some added controls
![image](https://user-images.githubusercontent.com/39407721/168429785-9432c0df-5e4f-4286-b170-a5224e8bf9dd.png)

**Comment by kristinx0211** [comment]
verified repro on android with above project.

**Comment by hartez** [comment]
Works on latest stable (VS 17.5).
