### ISSUE TITLE
MAUI Windows Machine Developer Mode

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#7187]
### Description

With VS 17.3.0 Preview 1 I am regularly getting the following Dialog box

![image](https://user-images.githubusercontent.com/24735929/168439210-f0766ef1-3030-4f58-9909-e54c9239ce86.png)

and deployment fails with

Starting local deployment...
Deploy: START
DeployAsync: START
Reading package recipe file "C:\Dev\iCan\SourceCode\SSIMAUI\SSIMAUI\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\SSIMAUI.build.appxrecipe"...
DEP0100: Please ensure that target device has developer mode enabled. Could not check to see if Developer Mode is enabled on the local machine due to error 00000490. To learn more about Developer Mode, please visit https://go.microsoft.com/fwlink/?linkid=2128411
	DeploymentSucceeded = False
	DeploymentError = Err_DevLicense_Failed
	DeploymentUserError = True
	DeploymentHRESULT = 2147943568
	HasSharedCode = False
	Target.Id = 256
	ProjectGuid = {84a91904-3fd3-41c3-8658-987b99621791}
	Project.TargetPlatformVersion = 31.0
Deleting file "vs.appxrecipe" from layout...
DeployAsync: END (Failure, 0:00:40.773)
Deploy: END (Failure, 0:00:40.806)

If I look at Developer mode I see

![image](https://user-images.githubusercontent.com/24735929/168439258-1e266ea5-4d3b-483a-a650-979e29f6889a.png)

This was turned on and in gpedit.msc I can see

![image](https://user-images.githubusercontent.com/24735929/168439302-f2ff01a8-dcfe-4034-9207-821513dfe56f.png)

If I perform a gpupdate /force then the Settings correctly goes back to

![image](https://user-images.githubusercontent.com/24735929/168439334-d79a6ef1-38ee-4713-86ca-b02d63ac91b7.png)

But what is changing it back? It seems to be a recent change in MAUI.

### Steps to Reproduce

Try to deploy a MAUI Windows Machine project on Windows 10 Pro 21H2

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Windows

### Affected platform versions

Windows 10 Pro 12H2

### Did you find any workaround?

Only the gpupdate /force to force Developer Mode back to On

**Comment by jfversluis** [comment]
I don't think we do anything this with settings and I have never seen or heard this before. Are you sure there is not some company policy or something on your machine that resets this? 

Personally I don't think this is something on our side and as such will close it for now. If you have some strong indication somehow that "we" are causing this, please let me know
