### ISSUE TITLE
net maui for linux desktop

### ISSUE THREAD

**Issue by strawberryfield** [dotnet/maui#7188]
### Description

when will be release net maui for linux desktop?

### Public API Changes

No requirement

### Intended Use-Case

Create UI for linux apps

**Comment by drasticactions** [comment]
I will refer you to this thread https://github.com/dotnet/maui/issues/336

**Comment by strawberryfield** [comment]
I understand that maui will be useless. You are wasting your time.

Cheers, Roberto

Il giorno sab 14 mag 2022 alle ore 23:01 Tim Miller <
***@***.***> ha scritto:

**Comment by migueldeicaza** [comment]
Good news!

On twitter, Sebastien Pouliot (original developer of much of Xamarin and Xamarin.iOS) pointed out that Uno Platform has proper support for Linux:

https://twitter.com/spouliot/status/1525842873467424768?s=21&t=P8nneV8NjyPO_CgPbFo-hg

**Comment by lytico** [comment]
see:

https://github.com/jsuarezruiz/maui-linux/tree/main-linux

https://github.com/lytico/maui/issues/11
