### ISSUE TITLE
Starting the debugger with WiFi and Mobile Data turned off crashes

### ISSUE THREAD

**Issue by jayveedee** [dotnet/maui#7189]
### Description

If you turn off WiFi and Mobile Data on the emulator and try running the application via Visual Studio, it crashes instantly. I haven't tested this on a real phone. This also sometimes freezes Visual Studio.

![image](https://user-images.githubusercontent.com/24821250/168449052-7962e84e-1b0b-4fda-89b3-802cde3d2552.png)

### Steps to Reproduce

1. Create a fresh MAUI project
2. Using the Android emulator, run the project
3. Verify that it works
4. Stop the debugger, turn off WiFi and Mobile Data on the emulator
5. Run the project again
6. Verify that it crashes

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Turn on either WiFi or Mobile Data and it works. If you turn both off, it crashes.

**Comment by drasticactions** [comment]
If you try making an Android app without MAUI (Ex. `dotnet new android` from CLI) and run it on the same emulator, does it crash?

**Comment by jayveedee** [comment]
@drasticactions I just tried it and by using the following commands (inside of a test dir)
```
dotnet new android
dotnet build test.csproj -t:run
```
It works fine and opens up the app without crashing.

**Comment by drasticactions** [comment]
Okay, can you try deploying the MAUI app from CLI? Does that crash?

If it doesn't. Can you try turning off XAML Hot Reload inside of VS?

**Comment by drasticactions** [comment]
Also, that doesn't attach the debugger _running_ it from CLI I believe. You need to run it from VS.

My guess is that the debugger is using TCP-IP and that will throw because it can't connect. @jonathanpeppers does that sound right?

**Comment by jonathanpeppers** [comment]
You can't debug at all if the emulator is set to be in airplane mode.

Is the complaint here that VS "freezes" for a long time? I've seen that myself, it seems like the IDE blocks on a 10-20 second timeout, and you might get a not responding message until it finishes.

**Comment by jayveedee** [comment]
@jonathanpeppers both. Is it intentional that you can't debug while on airplane mode or WiFi and mobile data turned off?

It's just something I noticed after I tried testing my app with no internet. The fact that the application crashed on startup with the debugger and VS freezing, I'm guessing are the same issue.

**Comment by jonathanpeppers** [comment]
The debugger uses tcp, so it can't possibly work in airplane mode. I wouldn't say this is "intentional", but that is how it was implemented since the beginning of Xamarin.

We could ask the IDE team to improve the behavior when the debugger can't connect. Would you be able to use the `Help | Send Feedback` button in Visual Studio, so folks could upvote? (share the link here)

Thanks!
