### ISSUE TITLE
MAUI WebView on Android not loading Cesium static web page.

### ISSUE THREAD

**Issue by johnseed** [dotnet/maui#7191]
### Description

I'm trying load [Cesium static web page](https://yellow-bay-0c1e66b10.1.azurestaticapps.net/) on MAUI Android WebView. Nothing special about this web page, It works everywhere, Windows WebView, Android Borwser, Android WebView, Xaramin WebView, XamarinForms WebView, but not working on MAUI WebView, it shows black screen.

Web page source : https://github.com/johnseed/Cesium-demo.git    
Online demo : https://yellow-bay-0c1e66b10.1.azurestaticapps.net/

MAUI : 
![image](https://user-images.githubusercontent.com/48501700/168462866-9254cb30-bf6a-43bb-935e-d0adfb6f229d.png)
Xamarin.Forms:
![image](https://user-images.githubusercontent.com/48501700/168462927-74b910aa-8287-4151-860b-e662c94c3ae7.png)
Xamarin:
![image](https://user-images.githubusercontent.com/48501700/168462946-0c80b2d5-b315-4a4d-a86b-e5392efea2b0.png)

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a `WebView` like so: `<WebView Source="https://yellow-bay-0c1e66b10.1.azurestaticapps.net/" />`
3. Launch the android app and observe the bug 🐞

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 - API 30

### Did you find any workaround?

Use iframe,  set the height manually.

**Comment by johnseed** [comment]
Finally figured it out, inside WebView, the height is always returns 0,  which is a bug I guess.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android, not repro on Windwos. Sample Project: [7191.zip](https://github.com/dotnet/maui/files/8696756/7191.zip)

![image](https://user-images.githubusercontent.com/97647558/168509848-dc41148e-f18f-4682-be3d-9f07b0b18f42.png)

**Comment by ederbond** [comment]
Hi, I'm having the same issue here. Is there is there any estimation of when someone will start working on this @jsuarezruiz @PureWeen @samhouts ?

**Comment by hartez** [comment]
This works fine for me if I just add a WebView to a ContentPage:

```xaml
<ContentPage ...>
    <WebView Source="https://yellow-bay-0c1e66b10.1.azurestaticapps.net/" />
</ContentPage>
```

It also works if the WebView is added to a Grid:

```xaml
<Grid>
    <WebView Source="https://yellow-bay-0c1e66b10.1.azurestaticapps.net/" />
</Grid>
```

If you're adding the WebView to a VerticalStackLayout, then it won't display because WebView doesn't have an intrinsic height. so it defaults to zero. You can address this by asking for a specific height:

```xaml
<VerticalStackLayout>
    <WebView HeightRequest="400" Source="https://yellow-bay-0c1e66b10.1.azurestaticapps.net/" />
</VerticalStackLayout>
```
