### ISSUE TITLE
(Blazor Hybrid) CSS Min Map files do not load 

### ISSUE THREAD

**Issue by Kylar182** [dotnet/maui#7194]
### Description

With a New Maui Hybrid Blazor App, CSS Mapping files do not load. This currently works in my WPF Blazor Desktop Application without issue.

### Steps to Reproduce

1. Create a new .Net MAUI Blazor Hybrid App
2. Run the application
3. Check the Dev Tools
4. See the following Error

DevTools failed to load source map: Could not load content for https://0.0.0.0/css/bootstrap/bootstrap.min.css.map: Connection error: net::ERR_ADDRESS_INVALID

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows, potentially others

### Did you find any workaround?

No workaround in .Net MAUI Blazor Hybrid other than not using minified CSS

### Relevant log output

```shell
DevTools failed to load source map: Could not load content for https://0.0.0.0/css/bootstrap/bootstrap.min.css.map: Connection error: net::ERR_ADDRESS_INVALID
```

**Comment by janseris** [comment]
My solution is to drop these files.  I read that they are something of a debug info for CSS. Not sure about the precision of the idea but everything has worked well for me since 5/2021 in BlazorWebView without them.
