### ISSUE TITLE
Content Page- Disappearing event not fire again

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#7196]
### Description

I attached sample code
Click on" click me button on main page, it move to New Page.
Click on back button the Disappearing event not fire.
See screenshot:
![image](https://user-images.githubusercontent.com/1079689/168475332-6cbcde4b-a9ea-468d-a74a-7053ac32d1dd.png)
[MauiApp25 (2).zip](https://github.com/dotnet/maui/files/8695037/MauiApp25.2.zip)

### Steps to Reproduce

I attached demo file

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

...

### Did you find any workaround?

Need workaround!!!

### Relevant log output

```shell
No logs.
```

**Comment by v-longmin** [comment]
Verified repro on Windows10 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[MauiApp25.2.zip](https://github.com/dotnet/maui/files/8696549/MauiApp25.2.zip)

**Comment by danies8** [comment]
I'm using window 10 professional **and is not working**
![image](https://user-images.githubusercontent.com/1079689/168788027-051c6059-80dd-4803-bfb5-77fe6dad1355.png)

**Comment by danies8** [comment]
I'm using Visual Studio Version 17.3.0 Preview 1.0

**Comment by danies8** [comment]
> Cannot reproduce the issue with Visual Studio Version 17.3.0 Preview 1.1 and with workload maui-windowsVS 17.3.32516.55 or in main branch. ![issue-7196](https://user-images.githubusercontent.com/6755973/168787261-56dc284e-b385-4f3b-be4e-41a60ca940f9.gif)
> 
> Leave the issue open until we can confirm that it is fixed in GA.

Please check in on the window details that I provided below.
It is not working!!!!!

**Comment by PureWeen** [comment]
@danies8 are you still seeing this with the latest bits and the repro here?

https://github.com/dotnet/maui/issues/7196#issuecomment-1127128980

**Comment by kristinx0211** [comment]
not reproduce the issue with Visual Studio Version 17.4.0 Preview 1.0 [32702.26.main].

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 6.0. This issue does not repro on Windows 10 with below Project:
[7196.zip](https://github.com/dotnet/maui/files/11404594/7196.zip)

![Event](https://user-images.githubusercontent.com/97647558/236414908-58333cf4-b3aa-42e8-be0c-738f22633cde.gif)
