### ISSUE TITLE
When the title set to string empty place for title  is still exist

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#7198]
### Description

When the title set to string empty is still exist
See:
![image](https://user-images.githubusercontent.com/1079689/168477902-4a00caa9-d4c7-4288-803f-3e297f68e746.png)
[MauiApp25.zip](https://github.com/dotnet/maui/files/8695165/MauiApp25.zip)

### Steps to Reproduce

1.I attached a demo.
2.Click on main page and move to NewPage, the title is empty but the place is still
keep for title. On main window when title not set we not see the place for title like screenshot.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

NO

### Did you find any workaround?

NO, How we get rid of this title?

### Relevant log output

```shell
No


```

**Comment by kristinx0211** [comment]
verified repro on windows with 17.3.0 Preview 2.0 [32511.531.main].

**Comment by StephaneDelcroix** [comment]
what if you do `page.ClearValue(TitleProperty)` ?

**Comment by danies8** [comment]
No is not help.
