### ISSUE TITLE
Including Microsoft.Identity.Client in .net Maui project causes it to fail to build when ios is targeted

### ISSUE THREAD

**Issue by billyjacobs2014** [dotnet/maui#7199]
### Description

If you include the nuget package Microsoft.Identity.Client in a .net maui project it will not build when an ios device or simulator is targeted. It works fine with Android.

On ios
You get the error:

Error		clang++ exited with code 1
File	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.300-rc.3.83\targets\Xamarin.Shared.Sdk.targets	1214	
 

### Steps to Reproduce

1. Create a new .Net Maui app
2. Build it against ios simulator. This works and runs as expected with the default project template
3. Add nuget package Microsoft.Identity.Client 4.43.2 (latest version)
4. Select IOS Simulators any device IPhone 13 Pro Max  iOS15.4
5. Build and the error occurs
6. Remove the Microsoft.Identity.Client and it builds just fine. 

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 15.4, .net maui rc3, latest version of xcode 13.3.1 (13E500a)

### Did you find any workaround?

I have not found a workaround.

**Comment by jfversluis** [comment]
Would you be able to check the logs and see if there is more information? The fact that it says `Error clang++ exited with code 1` means that that process ended badly, in the logs it should tell you more about _why_ it ended badly.

**Comment by billyjacobs2014** [comment]
Is this what you are asking for?

Build started...
1>------ Build started: Project: wwda.crm.mobile, Configuration: Debug Any CPU ------
1>Executing SayHello Task to establish a connection to a Remote Server. 
1>			Properties: 
1>				SessionId=680227dbef70e787ed78a530ca377b2f32238e89696d278810f20e8a28afc75a, 
1>				Addresss=192.168.0.201, 
1>				SshPort=22, 
1>				TcpPort=52779, 
1>				User=billyjacobs, 
1>				AppName=wwda.crm.mobile,
1>				VisualStudioProcessId=13200,
1>				ContinueOnDisconnected=False
1>Detected signing identity:
1>  Bundle Id: com.companyname.wwda.crm.mobile
1>  App Id: com.companyname.wwda.crm.mobile
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>wwda.crm.mobile -> C:\development\waterwheel\wwda.crm.mobile\wwda.crm.mobile\bin\Debug\net6.0-ios\iossimulator-x64\wwda.crm.mobile.dll
1>Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
1>Tool xcrun execution finished (exit code = 1).
1>ld: framework not found System
1>clang: error: linker command failed with exit code 1 (use -v to see invocation)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.300-rc.3.83\targets\Xamarin.Shared.Sdk.targets(1214,3): error : clang++ exited with code 1
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.300-rc.3.83\targets\Xamarin.Shared.Sdk.targets(1214,3): error :
1>Done building project "wwda.crm.mobile.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by drasticactions** [comment]
If you create a new dotnet 6 iOS app without MAUI (ex `dotnet new ios`) and try referencing that library, does it also crash like that?

**Comment by billyjacobs2014** [comment]
If I create a new project using (dotnet new ios) and include Microsoft.Identity.Client, I get the same error. There is no error if I remove it.

**Comment by emorell96** [comment]
Check this out: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3127#issuecomment-1104048737

This allowed me to build mine.

**Comment by drasticactions** [comment]
This is an AzureAD issue with their library, it's not MAUI specific then. I would follow up with that issue posted above.
