### ISSUE TITLE
[Android] Icon shows default android image when ForegroundFile in MauiIcon is not set

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7203]
### Description

Application has default android icon image (robot head on light blue background) without any warning or explanation when `ForegroundFile` attribute in `MauiIcon` tag is not set

### Steps to Reproduce

Use an icon without `ForegroundFile` attribute
e.g. from the basic example in [this tutorial](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment]
verified repro on android 11. and setting  `ForegroundFile` does not work at all.

**Comment by janseris** [comment]
> verified repro on android 11. and setting `ForegroundFile` does not work at all.

Thanks, do you mean that ForegroundFile does not work as expected? 
I once made it to "work" (do something) when I used a white SVG which only has edges (not filled) and a colorful svg for background - then some kind of overlay - the white shape without filling - was shown over the background colorful image in the icon.

**Comment by kristinx0211** [comment]
@janseris  setting the value for `ForegroundFile`, but it won't show show my own defined icon style. it can work on windows.
my vs version is 17.3.0 Preview 2.0 [32517.445.main].

**Comment by mattleibow** [comment]
This was fixed in #8020
