### ISSUE TITLE
[Android] my custom svg icon is always black on Android 

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7204]
### Description

[alfa.zip](https://github.com/dotnet/maui/files/8695318/alfa.zip)

`<MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appicon.svg" />`

Using this simple svg as `MauiIcon` on Android displays black shape on black background.
The colors cannot be modified by any MauiIcon property (as far as I have been trying exhaustivly for the last 4 hours)
The shape can be seen during a few frames when the application is started from the Android applications menu/list (there is an animation on Android which quickly shows the shape without backgorund -> black "alpha" shape is visible in these few frames)

Note: the file must be called `appicon` for Android else the project fails to build.

The svg shape is rendered as black when used in `MauiSplashScreen` as well.

https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=android
I read that svg files are converted to bitmaps. Is is an issue in the conversion then? 

> .NET MAUI converts SVG files to PNG files. 

Is that really needed? The `svg` size is 2 kB. PNG size is probably hundreds of kB. We use `svg`s to squeeze application size. MAUI isn't capable of displaying `svg`s?

### Steps to Reproduce

Try use the image as Android icon (maybe the black image occurs on Windows as well?)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by NeerajRai111** [comment]
It was working in earlier version but now it is not working. Please fix it.

**Comment by alexanderdp** [comment]
Confirmed, Same here, this bug (deployed App, App Icon) shows as solid black icon on any previously built/created .net Maui apps for all platforms (Windows, Android and iOS).

"File New" Maui projects/solutions does not present this bug.

(Windows 11, .net Maui project (Windows, Android, iOS), VS 2022 version 17.3.0 Preview 1.0)

**Comment by VincentBu** [comment]
not repro with vs main build on Android emulator. @janseris , is this the expected result?
![image](https://user-images.githubusercontent.com/44959937/169441209-f5f425ee-de34-4e83-9c1e-ab8c068c8575.png)

**Comment by rrmanzano** [comment]
Hi, @janseris looks like the issue is when the SVG file contains CSS styles, I did a small test, and here are my findings:

SVG to reproduce the issue
```xml
<svg id="ed8c3fcb-bb52-46d0-9a9e-bb9fc9e2126f" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 175.2 132.07">
	<defs>
		<style>
			.a177f59e-042c-4483-90f2-4254cea05478 { fill: #fbcc0a; }
			.faa715a9-1b62-464d-a476-8cbd4e83f49b { fill: #ee1c4e; }
		</style>
	</defs>
	<rect class="a177f59e-042c-4483-90f2-4254cea05478" y="22.64" width="149.8" height="109.43"/>
	<rect class="faa715a9-1b62-464d-a476-8cbd4e83f49b" x="72.64" width="102.56" height="77.36"/>
</svg>
```

Same SVG without CSS - Works !!
```xml
<svg id="ed8c3fcb-bb52-46d0-9a9e-bb9fc9e2126f" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 175.2 132.07">
  <rect y="22.64" width="149.8" height="109.43" fill="#fbcc0a"/>
  <rect x="72.64" width="102.56" height="77.36" fill="#ee1c4e"/>
</svg>
```
Tested with VS 2022 version 17.3.0 Preview 1.0

**Comment by mattleibow** [comment]
I believe that bug was fixed here: #7106

**Comment by janseris** [comment]
@mattleibow Thanks,  BTW what is binlog, please?

**Comment by mattleibow** [comment]
A binlog is a binary log or the entire msbuild run with all variables and items. You can just install a vs extension or add /bl to the end of a msbuild or dotnet build command

https://msbuildlog.com/

**Comment by janseris** [comment]
> not repro with vs main build on Android emulator. @janseris , is this the expected result? ![image](https://user-images.githubusercontent.com/44959937/169441209-f5f425ee-de34-4e83-9c1e-ab8c068c8575.png)

Hi this is not expected result because the icon is stretched incorrectly.
