### ISSUE TITLE
[Android] MauiIcon Color and TintColor doesn't work

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7206]
### Description

The MauiIcon TintColor attribute is said to draw the shape/image in a custom color.

https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons

> To add a tint to your app icon, which is useful when you have an icon or simple image you'd like to render in a different color to the source, set the TintColor attribute:

---------------------------------------------------------------

The MauiIcon Color attribute is said to draw the background color for the app icon:

https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons

> A background color for the app icon can also be specified:
> `<MauiIcon Include="Resources\Images\appicon.svg" Color="#512BD4" />`

None of this works on Android 11 (tried with SVG images and with PNG images with transparent background)

Color attribute works on `MauiSplashScreen` even if the svg turns black by the MAUI conversion.
TintColor attribute works on `MauiSplashScreen` even if the svg turns black by the MAUI conversion.

### Steps to Reproduce

use Color and TintColor attribute on MauiIcon tag on Android

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment]
repro on windows and android, using `<MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" Color="#ff66db" />` does not work.

**Comment by Bnjbel97** [comment]
this is also happening on IOS for me as well

**Comment by mattleibow** [comment]
Color and TintColor should now be working. There is an issue on some things where changes don't reflect without a rebuild: #9803
