### ISSUE TITLE
[Windows] MauiIcon Color and TintColor doesn't work in taskbar and is inconsistent elsewhere

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7207]
### Description

[The documentation](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icon) says:

> A background color for the app icon can also be specified:
> `<MauiIcon Include="Resources\Images\appicon.svg" Color="#512BD4" />`

and

https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons

> A background color for the app icon can also be specified:
> `<MauiIcon Include="Resources\Images\appicon.svg" Color="#512BD4" />`

-----------------------------------------------------

Edit: tested with svg and png with transparent background as well.

This single configuration has 5 different looks in the system:

`<MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appicon.svg" TintColor="White" Color="White" />`

Task manager - additional blue line:
![image](https://user-images.githubusercontent.com/64279914/168483773-61f67bdf-df1e-403e-a323-3a1186e8b47e.png)

Task manager - details tab - no icon:
![image](https://user-images.githubusercontent.com/64279914/168483855-5e7718ba-5331-4740-ac30-55affa0249a6.png)

Windows taskbar - TintColor and Color not applied (well, Color (background) actually once worked _randomly_ https://github.com/dotnet/maui/issues/7200)
![image](https://user-images.githubusercontent.com/64279914/168483876-5cf9f71a-3bf6-4de5-88de-9e2c233593fe.png)

Settings - blue rectangle:
![image](https://user-images.githubusercontent.com/64279914/168483902-e031f202-4e8e-4bc6-be9d-72dd0fbf3676.png)

Window title - nothing
![image](https://user-images.githubusercontent.com/64279914/168483971-fec0e906-3b99-43b7-8f3c-49dec74cbf5b.png)

### Steps to Reproduce

use MauiIcon on Windows

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

latest

**Comment by VincentBu** [comment]
Verified with vs main build(32519.297.main)
Task manager - additional blue line:
![image](https://user-images.githubusercontent.com/44959937/169454916-efa33393-7fab-4565-ba67-b7372d3dd10d.png)

Task manager - details, just a white block
![image](https://user-images.githubusercontent.com/44959937/169454611-bc06256b-d911-441e-ab11-785d66cb3cdc.png)

Taskbar:
![image](https://user-images.githubusercontent.com/44959937/169454710-2fc600f9-9828-4677-8219-252d0cb1092b.png)

Settings:
![image](https://user-images.githubusercontent.com/44959937/169454749-d7f74d57-75ca-4616-887e-4c155526b08e.png)

Window title - nothing
![image](https://user-images.githubusercontent.com/44959937/169454971-fa380140-fe9b-4fb1-9b2e-9917637fac31.png)

**Comment by janseris** [comment]
Update in GA:
![image](https://user-images.githubusercontent.com/64279914/169999697-3fdd77e1-ab2d-44a3-b774-6098d3d8704d.png)
This is the current status when a PNG with transparent background is used.
In Taskbar, there is no blue, **in preview in Taskbar there is still blue background**
In switch windows menu, the background is OK
![image](https://user-images.githubusercontent.com/64279914/170000015-b5269c63-948e-44d4-8edb-21f7440498d4.png)
