### ISSUE TITLE
Accent color can't be overwritten like in WinUI 3

### ISSUE THREAD

**Issue by Fabi** [dotnet/maui#7208]
### Description

We should be able to set the accent color on Windows like in WinUI 3. Currently I don't see any way to do it (or I'm just not able to find it..)
The colors I set in Step 2 work fine on WinUI 3.

### Steps to Reproduce

1. Create a new .NET MAUI project.
2. use this snippet in your AppShell.xaml:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="SampleApp.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:SampleApp"
    FlyoutBehavior="Locked"
    >

    <ShellContent Title="Home" Icon="&#xE80F;" Route="MainPage" ContentTemplate="{DataTemplate local:MainPage}" />
    <ShellContent  Title="Store" Icon="&#xE719;" Route="MainPage" ContentTemplate="{DataTemplate local:MainPage}" />
    <ShellContent Title="Library" Icon="&#xE8F1;" Route="MainPage" ContentTemplate="{DataTemplate local:MainPage}" />


</Shell>
```
3. Add the following colors
```xml

            <Color x:Key="SystemAccentColorDark1">#E91E63</Color>
            <Color x:Key="SystemAccentColorDark2">#E91E63</Color>
            <Color x:Key="SystemAccentColorDark3">#E91E63</Color>
            <Color x:Key="SystemAccentColorLight1">#E91E63</Color>
            <Color x:Key="SystemAccentColorLight2">#E91E63</Color>
            <Color x:Key="SystemAccentColorLight3">#E91E63</Color>
```
4. The flyout selected indicator keeps using the system wide set accent color. I tried multiple other brushes or colors too but it won't change at all.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

All Windows platforms

### Did you find any workaround?

No.

**Comment by drasticactions** [comment]
Can't you change it in the WinUI project MAUI provides you? You should be able to put it in the `Platform/Windows/App.xaml` file as a resource.

**Comment by Fabi** [comment]
> Can't you change it in the WinUI project MAUI provides you? You should be able to put it in the `Platform/Windows/App.xaml` file as a resource.

Actually thanks u for that hint. It really works then. I think some more documentation about these things are required here and there since these values are not used when added in your regular style files. I don't think it should work like  that

**Comment by jfversluis** [comment]
I don't think we have a unified API for setting tint colors yet and as such this will be a platform-specific thing for now.

Glad you figured out a way! :)
