### ISSUE TITLE
[BUG] Label with FormattedText ignores FontSize

### ISSUE THREAD

**Issue by tsjdev-apps** [dotnet/maui#7210]
### Description

If you create a `Label` and use the `FormattedText` property to provide multiple `Span` elements the `FontSize` gets ignored on the `Label` element. If you set the `FontSize` on each `Span` element the `FontSize` is working accordingly.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a `Label` using `FormattedText`, like so:
```xaml
<Label FontSize="32"
       TextColor="Red"
       HorizontalOptions="Center">
    <Label.FormattedText>
        <FormattedString>
            <Span Text="Hello" />
            <Span Text=" World" />
            <Span Text="!" />
        </FormattedString>
    </Label.FormattedText>
</Label>
```
3. The `TextColor` is displayed as `Red`, but the `FontSize` gets ignored

So the attached sample project:
[MauiLabelFormattedText.zip](https://github.com/dotnet/maui/files/8695603/MauiLabelFormattedText.zip)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12, Windows SDK 10.0.17134.0

### Did you find any workaround?

You can set the `FontSize` on each `Span` element.

**Comment by v-longmin** [comment]
Verified repro on windows 10 & Android 12.0 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro project:
[MauiLabelFormattedText.zip](https://github.com/dotnet/maui/files/8696483/MauiLabelFormattedText.zip)

**Comment by mattleibow** [comment]
Duplicate of #6801
