### ISSUE TITLE
Graphics engine desktop

### ISSUE THREAD

**Issue by BC89** [dotnet/maui#7212]
### Description

Having worked with Xamrin in the past I had high hopes for the Maui rendering engine upgrades but man am I disappointed, especially desktop solutions. They look blocky and just lousy. Am I missing something but compared to Flutter, out of the box Maui UIs stink, not even close, like early 90s to modern day. What gives? I do love most everything else about Maui/c# and so want to use it but it's a hard sell in the board room where first impressionsake a difference. 

### Steps to Reproduce

Run the weather app in desktop- ugly

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Preview 13

### Affected platforms

Windows

### Affected platform versions

Deaktop

**Comment by jfversluis** [comment]
Hi @BC89 Flutter and .NET MAUI just take very different approaches. Flutter draws all the things, .NET MAUI maps the abstract layer into platform native controls. To the matter of how it looks, I guess that's all a matter of taste and hard to argue about. With .NET MAUI you have loads of options to style and theme your application to your liking. You can make it as good (or bad) looking as you please.

Additionally, we are exploring [Microsoft.Maui.Graphics.Controls](https://github.com/dotnet/Microsoft.Maui.Graphics.Controls) which takes a similar approach to Flutter and draws all the controls to create that pixel-perfect same look across platforms.

Both the approaching of Flutter and .NET MAUI (and others of course) have their own pros and cons. Up to you to decide which are important for you and which product you will want to work with.
