### ISSUE TITLE
Any plan to Support LG webOS ?

### ISSUE THREAD

**Issue by Mariselvam93** [dotnet/maui#7213]
### Description

Would like to develop an app to support LG WebOS along with Tizen, Android TV. 

### Public API Changes

LG WebOS Platform support

### Intended Use-Case

LG WebOS Platform support

**Comment by Mariselvam93** [comment]
@jfversluis @jamesmontemagno

**Comment by Mariselvam93** [comment]
@jfversluis @jamesmontemagno

**Comment by mattleibow** [comment]
Does that even run .NET?

**Comment by jfversluis** [comment]
I don't think we have any plans for the foreseeable future for this. If we were to add additional targets I think the most likely candidates would be Linux (which seems to help for LG WebOS too as it runs on Linux) or web over a very specific OS for a specific set of devices.

As such, closing this for now, sorry!
