### ISSUE TITLE
[iOS] - Frame not resizing.

### ISSUE THREAD

**Issue by bhuvan94** [dotnet/maui#7217]
### Description

Frame not resize while changing IsVisible Property Dynamically.

### Steps to Reproduce

1. Create Maui Sample.
2. Add below code.

>  <StackLayout>
     <StackLayout>
        <Frame Margin="10" BackgroundColor="Red">
            <Grid RowDefinitions="Auto,Auto" VerticalOptions="Center">
                <Frame Grid.Row="0">
                    <Grid ColumnDefinitions="*,Auto">
                        <Label Grid.Column="0" Text="Header" />
                        <Label
                            x:Name="label"
                            Grid.Column="1"
                            HorizontalOptions="End"
                            Text="Hide">
                            <Label.GestureRecognizers>
                                <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" />
                            </Label.GestureRecognizers>
                        </Label>
                    </Grid>
                </Frame>
                <Frame x:Name="frame" Grid.Row="1">
                    <Label Text="Detail" />
                </Frame>
            </Grid>
        </Frame>
    </StackLayout>

3. Run the app.

Sample : [SimpleSample.zip](https://github.com/dotnet/maui/files/8698785/SimpleSample.zip)

Android recorded video

https://user-images.githubusercontent.com/20217737/168558930-bc231ceb-39c7-4e84-a758-c1deb9319901.mp4

iOS recorded video

https://user-images.githubusercontent.com/20217737/168558812-02e009bc-4a56-499f-8250-fb3a946af568.mov

### Version with bug

Release Candidate 2

### Last version that worked well

Release Candidate 2

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

None

**Comment by v-longmin** [comment]
Verified repro on iOS 15.4 with VS 17.3.0 Preview 1.0 [32427.505.main]. repro with  above project.

**Comment by hartez** [comment]
Probably the same problem as #6420

**Comment by ViktorArbuzov** [comment]
tested on 6.0.312, the issue still can be reproduced
