### ISSUE TITLE
The character set provided in ContentType is invalid 'windows-1253'

### ISSUE THREAD

**Issue by kaniosm** [dotnet/maui#7218]
### Description

Getting the error below on API requests.
Tryied checking the "West" internalization package under Android Options, but the error remains.

{System.InvalidOperationException: The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.
System.ArgumentException: 'windows-1253' is not a supported encoding name. 

### Steps to Reproduce

1. Create a new MAUI app
2. Call a Rest API accepting windows-1253 encoding

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jfversluis** [comment]
Hey there @kaniosm thanks for the report! I'll be honest and say that this doesn't sound really like a bug on our side. It seems that the content that you're receiving from the API has a Windows encoding. And it would seem very likely that that is not supported on Android :)

Would you be able to try this with an Android (not .NET MAUI) project and see if you get the same result? If you do, we have ruled out that this is something specific to .NET MAUI at least. But as mentioned, even beyond that I think you would just need to get the data from the API a different way.

It would also greatly help if you would add some sample code or preferably a reproduction project.

Thanks!

**Comment by kaniosm** [comment]
Hi @jfversluis,

I'm actually trying to migrate an existing Xamarin Forms project to .NET MAUI.
In the previous project I was able to overcome this by enabling the "West" encoding from "Additional Encodings" under "Android Options".
The same exists in MAUI apps, but it doens't seem to make any difference.
Xamarin Forms Project, VS 2022
![image](https://user-images.githubusercontent.com/28901791/168583862-42b6ab5b-31f3-4118-9244-28991177cbbc.png)

MAUI Project VS 2022 17.3 Preview 1
![image](https://user-images.githubusercontent.com/28901791/168584081-cb1ef858-06d4-47b9-b75a-9c99d7097d64.png)

**Comment by jonathanpeppers** [comment]
@kaniosm can you provide a sample project, so we could look into this further? I don't think that setting is going to help here.

> Call a Rest API accepting windows-1253 encoding

This actually seems like the Android APIs for HTTP don't accept `windows-1253` as a value for `ContentType`, but it's hard to know what's going wrong without an example. Thanks!

**Comment by jonathanpeppers** [comment]
Yes, I'm not sure the `West` option actually does anything in .NET 6. We may need to replace this setting (or remove it).

**Comment by kaniosm** [comment]
Hi @jonathanpeppers 

It seems that .NET 6.0 relies on the Nuget packages like the previous .Net Core versions.
Basically the West option will not do anything on MAUI.
I resolved my issue by installing System.Text.Encoding and and System.Text.Encoding.CodePages and adding the below line at startup:
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

For the record I'm attaching 2 sample projects (one Xamarin and One Maui) with the first having the West  option checked and being able to handle 1253 encoding without the need to install any additional packages.

I believe thought it's best if this option is removed or disabled for Maui projects.

[SampleMauiApp.zip](https://github.com/dotnet/ma
[SampleXFApp.zip](https://github.com/dotnet/maui/files/8705757/SampleXFApp.zip)
ui/files/8705754/SampleMauiApp.zip)

**Comment by jonathanpeppers** [comment]
Thank you for the examples!

I filed a [bug internally](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1542163) for them to remove the extra checkboxes in Visual Studio.

Unfortunately, that change is closed source, so I think we can close this issue here. Thanks!

**Comment by kaniosm** [comment]
Thank you both for the hints and actions
