### ISSUE TITLE
Android FormattedText and LineHeights are not correct

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#7220]
### Description

The calculation of the line heights are wrong because they capture the initial state of the `TextView.Paint` - often bfore the text is sized. This result in the line height be calculated from the small font size, and then not updated once the font size is updated.

I found this while working on #6801

<img src="https://user-images.githubusercontent.com/1096616/168562059-4d6b3c14-8586-449e-b599-028b90462f9e.png" width="400" />

### Steps to Reproduce

```xaml
<Label x:Name="theLabel" VerticalOptions="Center" HorizontalOptions="FillAndExpand"
        BackgroundColor="Red"
        LineHeight="1" FontSize="35" />
```

```cs
var formattedText = new FormattedString();
formattedText.Spans.Add(new Span { Text = "test1" });
formattedText.Spans.Add(new Span { Text = "\n" });
formattedText.Spans.Add(new Span { Text = "test2" });
theLabel.FormattedText = formattedText;
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All

**Comment by v-longmin** [comment]
![image](https://user-images.githubusercontent.com/40230425/168565576-2477099f-9464-4978-99d1-830cc1749ac0.png)
Verified not repro on Android 12.0 with above code.

**Comment by mattleibow** [comment]
That is the issue. The font size is set to 35 yet that font is very small. Set any font size - like 100, yet it stays the same size.
