### ISSUE TITLE
Android - Excessive space on the right side of Grid

### ISSUE THREAD

**Issue by bhuvan94** [dotnet/maui#7221]
### Description

Grid creates excessive space on the right side. Compare the below screenshot for better understanding.

### Steps to Reproduce

1. Create Maui Sample.
2. Add below code.

>  <StackLayout>
     <StackLayout>
        <Frame Margin="10" BackgroundColor="Red">
            <Grid RowDefinitions="Auto,Auto" VerticalOptions="Center">
                <Frame Grid.Row="0">
                    <Grid ColumnDefinitions="*,Auto">
                        <Label Grid.Column="0" Text="Header" />
                        <Label
                            x:Name="label"
                            Grid.Column="1"
                            HorizontalOptions="End"
                            Text="Hide">
                            <Label.GestureRecognizers>
                                <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" />
                            </Label.GestureRecognizers>
                        </Label>
                    </Grid>
                </Frame>
                <Frame x:Name="frame" Grid.Row="1">
                    <Label Text="Detail" />
                </Frame>
            </Grid>
        </Frame>
    </StackLayout>

3. Run the app.

Xamarin forms Sample :   [xamarin_forms.zip](https://github.com/dotnet/maui/files/8698835/xamarin_forms.zip)

.Net Maui Sample : [SimpleSample.zip](https://github.com/dotnet/maui/files/8698838/SimpleSample.zip)

**Xamarin Forms (Android) Screenshot**

<img src="https://user-images.githubusercontent.com/20217737/168563192-87475e10-2469-4f0b-aff0-3264e0a69c7f.png" width="500">

**Maui (Android) Screenshot**

<img src="https://user-images.githubusercontent.com/20217737/168563209-ef963176-2d82-45f3-9723-b294f1267f77.png" width="500">

iOS Screenshot

<img width="563" alt="ios_grid" src="https://user-images.githubusercontent.com/20217737/168569475-d0d97bfe-5d2c-4cf2-9248-a52ed5aa4ae5.png">

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

None

**Comment by v-longmin** [comment]
Verified repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro with above project.

**Comment by jfversluis** [comment]
Thanks for the help here @NonameMissingNo!

Confirmed, this no longer is an issue in our codebase. This should be released as part of an upcoming service release. Thanks!
