### ISSUE TITLE
Long Project Name breaks layout in new MAUI Blazor App

### ISSUE THREAD

**Issue by jclarkcds** [dotnet/maui#7231]
### Description

When creating a new project with the .Net MAUI Blazor template, the layout page is not rendering.  After much research, Main.Razor and Shared\MainLayout.razor were all correct.  Pages\index.razor renders without the layout.
![MAUI](https://user-images.githubusercontent.com/10396627/168611699-11c9069c-4b02-4166-9175-c1b00f2b6ecf.png)

### Steps to Reproduce

1. Create Project > .NET MAUI Blazor App (Preview)
2. Project Name > Maui Blazor DLPHIN API Testing
3. Location in my DevOps Workspace
4. Clicked Create

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

All Platforms

### Did you find any workaround?

Yes, in looking at the rootnamespace - Maui_Blazor_DLPHIN_API_Testing, I wondered about the length and the spaces in the project name.

I re-created a new project and took the default name MauiApp1 and placed in my local repo instead of my DevOps Workspace and all is well.
![MAUIAPP1](https://user-images.githubusercontent.com/10396627/168613852-2a6264d4-5346-4e1b-b5e1-d2a6676460e1.png)

**Comment by javiercn** [comment]
![image](https://user-images.githubusercontent.com/6995051/168628005-97c9036b-628e-40fb-b2f9-6c624fada0e2.png)

**Comment by jclarkcds** [comment]
That worked.  Thank you.  How did you diagnose the GET?  Was this done in VS or through a utility like PostMan?
![NewMAUI](https://user-images.githubusercontent.com/10396627/168638060-1f07c657-d0f5-4d5a-b8e6-690570a3d517.PNG)

**Comment by janseris** [comment]
> That worked. Thank you. How did you diagnose the GET? Was this done in VS or through a utility like PostMan? ![NewMAUI](https://user-images.githubusercontent.com/10396627/168638060-1f07c657-d0f5-4d5a-b8e6-690570a3d517.PNG)

Probably browser dev tools. F12 when in Debug Mode on Windows. It is configured in startup.

**Comment by v-longmin** [comment]
![image](https://user-images.githubusercontent.com/40230425/168708386-d3765e6a-00e9-44ca-9faf-de8ce6ee5420.png)
verified repro on windows10 with VS 17.3.0 Preview 1.0 [32427.505.main]. Repro with maui blazor sample project.

**Comment by eddyjd** [comment]
I came across this exact issue last week and cam to same conclusion as you.

**Comment by javiercn** [comment]
Closing in favor of https://github.com/dotnet/maui/issues/10780
