### ISSUE TITLE
Cannot edit a RESX file, designer loader failed

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#7232]
### Description

Using VS 17.3.0 Preview 1, I cannot open a resx files.

The error is "The deisgner loader did not provide a root component but has not indicated why".

I created a folder under Resources called Languages and under that TranslateStrings.resx

When I double click on the resx, I get the above error message.

### Steps to Reproduce

Create a resx files and try to open it.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
This is not specific to MAUI nor something that, I believe, can be fixed within this repo. You should file this to Visual Studio Feedbackl (https://developercommunity.visualstudio.com/search?space=8)
