### ISSUE TITLE
Windows Machine keeps saying Type '/' to search from your saved info

### ISSUE THREAD

**Issue by genifycom** [dotnet/maui#7233]
### Description

Why does Windows keep doing this popup. My field does not even accept / (it is a phone number field) so why is this popping up?

### Steps to Reproduce

Run MAUI on Windows machine

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 21H2

### Did you find any workaround?

None

**Comment by drasticactions** [comment]
Could you add a reproduction project where you see this? I'm not sure if you're referring to a specific control from MAUI or something else.
