### ISSUE TITLE
Border does not draw on android

### ISSUE THREAD

**Issue by michaelstonis** [dotnet/maui#7238]
### Description

I have a custom `BadgeView` control which is a simplified port of the Xamarin Community Toolkit BadgeView. On Android, the background for the badge portion does not appear to draw.

The `BadgeView` renders out properly on iOS and macOS.

### Examples

<img width="526" alt="image" src="https://user-images.githubusercontent.com/120685/168683669-38cf29e6-b423-4ba7-b197-75ee6466ad26.png">

This is the Android version of the `BadgeView`

<img width="612" alt="image" src="https://user-images.githubusercontent.com/120685/168683722-ffe4f1c6-33a7-421e-844e-c0fabb003c0a.png">

This is the iOS version of the `BadgeView`

### Steps to Reproduce

1. Clone this code: https://github.com/TheEightBot/eshop-maui-client/tree/feature/issue/border-nodisplay-android
2. Run the application on Android
3. Login using any credentials (username: test, password: test)
4. Notice that the background for the `BadgeView` is not displayed

The code for the `BadgeView` can be found at `shop-maui-client/eShopOnContainers/Views/BadgeView.cs`

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11+

### Did you find any workaround?

It is possible to use a different underlying control instead of the `Border` and achieve a similar effect.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Repro on Android 12 with above project.

**Comment by TRadigk** [comment]
Have you set a StrokeShape? For me, setting this resolved the issue. But I don't know which value would be sufficient for your scenario.
