### ISSUE TITLE
[Windows] [Scenario Day] Adaptive Trigger on StackLayout crashes  Windows.

### ISSUE THREAD

**Issue by chabiss** [dotnet/maui#7242]
### Description

Following https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/triggers, setting up an adaptive triggers on StackLayout crashes the app. 

 <Style TargetType="StackLayout">
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup>
                    <VisualState x:Name="Vertical">
                        <VisualState.StateTriggers>
                            <AdaptiveTrigger MinWindowWidth="0" />
                        </VisualState.StateTriggers>
                        <VisualState.Setters>
                            <Setter Property="Orientation"
                                Value="Vertical" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Horizontal">
                        <VisualState.StateTriggers>
                            <AdaptiveTrigger MinWindowWidth="800" />
                        </VisualState.StateTriggers>
                        <VisualState.Setters>
                            <Setter Property="Orientation"
                                Value="Horizontal" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>

### Steps to Reproduce

[MauiApp1.zip](https://github.com/drasticactions/Archiverse/files/8710339/MauiApp1.zip)

Download \\ddfiles\Team\XAML\User\chabiss\Maui\MauiApp1.zip
open the app
Run on Windows
Result:
{Microsoft.UI.Xaml.UnhandledExceptionEventArgs} | Microsoft.UI.Xaml.UnhandledExceptionEventArgs
  | ▶ Exception | {"Catastrophic failure (0x8000FFFF (E_UNEXPECTED))"} | System.Exception {System.Runtime.InteropServices.COMException}
  | Handled | false | bool
  | Message | "Microsoft.UI.Xaml.Controls.Frame.NavigationFailed was unhandled." | string

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.22000.194

### Did you find any workaround?

No so far

**Comment by VincentBu** [comment]
Hi @chabiss, looks like you didn't give the link of MauiApp1.zip.

**Comment by drasticactions** [comment]
@VincentBu It's a File Share on Corpnet, I've attached the repro project.

[MauiApp1.zip](https://github.com/drasticactions/Archiverse/files/8710339/MauiApp1.zip)

**Comment by drasticactions** [comment]
![image](https://user-images.githubusercontent.com/898335/168876091-34c88ccb-5ba9-4fdb-a5db-c1b5c90a191b.png)

NRE. _visualElement is nullable, and trying to get Window on it will blow it up.

**Comment by VincentBu** [comment]
not repro with vs main build(32517.416.main)

**Comment by mattleibow** [comment]
So I got a slightly smaller repro. I used the sandbox sample, but in effect you can just put this in the App.xaml resources:

```xaml
<Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.App">
    <Application.Resources>
        <ResourceDictionary>
            <Style TargetType="StackLayout">
                <Setter Property="VisualStateManager.VisualStateGroups">
                    <VisualStateGroupList>
                        <VisualStateGroup>
                            <VisualState x:Name="Vertical">
                                <VisualState.StateTriggers>
                                    <AdaptiveTrigger MinWindowWidth="0" />
                                </VisualState.StateTriggers>
                                <VisualState.Setters>
                                    <Setter Property="Orientation" Value="Vertical" />
                                </VisualState.Setters>
                            </VisualState>
                            <VisualState x:Name="Horizontal">
                                <VisualState.StateTriggers>
                                    <AdaptiveTrigger MinWindowWidth="800" />
                                </VisualState.StateTriggers>
                                <VisualState.Setters>
                                    <Setter Property="Orientation" Value="Horizontal" />
                                </VisualState.Setters>
                            </VisualState>
                        </VisualStateGroup>
                    </VisualStateGroupList>
                </Setter>
            </Style>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

and the contents of the page is just a:

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
    <StackLayout />
</ContentPage>
```

The thing I did notice was that if the style was in the app, then it failed. If the style was in the content page resources, then it was fine.

**Comment by davidortinau** [comment]
Testing today on Windows and it no longer crashes (main branch preview.1.5835), but nothing changes. I'm trying to change the background of the page. I did confirm the width of the page is updating. I also moved it into a style to match the sample, but no joy.

```
    <ContentPage.Resources>
        <Style TargetType="StackLayout">
            <Setter Property="VisualStateManager.VisualStateGroups">
                <VisualStateGroupList>
                    <VisualStateGroup>
                        <VisualState x:Name="First">
                            <VisualState.StateTriggers>
                                <AdaptiveTrigger MinWindowWidth="0" />
                            </VisualState.StateTriggers>
                            <VisualState.Setters>
                                <Setter Property="Background"
                                Value="{StaticResource PrimaryBrush}" />
                            </VisualState.Setters>
                        </VisualState>
                        <VisualState x:Name="Second">
                            <VisualState.StateTriggers>
                                <AdaptiveTrigger MinWindowWidth="800" />
                            </VisualState.StateTriggers>
                            <VisualState.Setters>
                                <Setter Property="Background"
                                Value="White" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateGroupList>
            </Setter>
        </Style>
    </ContentPage.Resources>
```

**Comment by drasticactions** [comment]
I think it's to do with the PR that Matt linked to. The VisualElements being tagged are now null when they get to the VisualStateManager, so nothing is applied.

My PR would have stopped the crash Charles was seeing, but the elements would still be null, so they wouldn't have worked. The CI tests still work, but in a real-world app, they are not.
