### ISSUE TITLE
[Android] [Scenario Day] Wrong selection in list inside Shell

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7251]
### Description

When trying to select an item, the one below it is selected. Also, every selected item stays marked.
![shell-list-issue](https://user-images.githubusercontent.com/6755973/168801375-5b36a98f-3df3-4118-a46c-fa48b0cec560.gif)

### Steps to Reproduce

1. Download [Shell.zip](https://github.com/dotnet/maui/files/8707834/Shell.zip)
2. Select some items. 

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Repro on Android 12 with above project.

**Comment by PureWeen** [comment]
@jsuarezruiz can you test again? I tried with latest bits and it seemed alright now

**Comment by NonameMissingNo** [comment]
It is working properly on the main branch
![image](https://user-images.githubusercontent.com/40233496/176244003-3f00a050-2bb8-432d-bf9f-59bfbf01088f.png)
