### ISSUE TITLE
[Android] [Scenario Day] Navigating from SearchHandler get a blank page

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7252]
### Description

Navigating from SearchHandler get a blank page.

![shell-empty-search](https://user-images.githubusercontent.com/6755973/168801874-505eb3a6-958b-41ce-819f-069de89f1cf9.gif)

Selecting an item navigates correctly and render the details.

### Steps to Reproduce

1. Download [Shell.zip](https://github.com/dotnet/maui/files/8707869/Shell.zip)
2. Search anything, for example "b" and tap an item.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment]
repro on android 11 with the above project.

**Comment by PureWeen** [comment]
The demo app used here I think is really old and isn't setting up navigation parameters correctly. I tested the official sample at maui-samples and that works fine
