### ISSUE TITLE
[Android] [Scenario Day] Application.Current.Quit not working

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7255]
### Description

Using:

`Application.Current.Quit();`

Not works on Android.

![quit-droid](https://user-images.githubusercontent.com/6755973/168804891-8b74da3e-9cc4-471e-93e3-a87ed35f51ba.gif)

### Steps to Reproduce

1. Create a new .NET MAUI App from templates.
2. Using a Button clicked event, try to close the App.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Repro on Android 12, not repro on Windows. Sample Project: [MauiApp6.zip](https://github.com/dotnet/maui/files/8713527/MauiApp6.zip)

**Comment by Redth** [comment]
#7255
