### ISSUE TITLE
[MacCatalyst] [Scenario Day] Crash using Shell

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7260]
### Description

Crash using Xaminals Shell sample.
<img width="1231" alt="Captura de Pantalla 2022-05-17 a las 17 37 23" src="https://user-images.githubusercontent.com/6755973/168853312-42b56ff6-dc42-4b66-b755-92ed50b0836a.png">

### Steps to Reproduce

1. Download https://github.com/davidbritch/dotnet-maui-samples/tree/main/Fundamentals/Shell
2. Launch the App in macOS.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.3.1

**Comment by VincentBu** [comment]
repro with vs main build(32522.39.main)
