### ISSUE TITLE
[MacCatalyst] [Scenario Day] Brushes not working in Frame

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7261]
### Description

Brushes not working in Frame.

<img width="780" alt="Captura de Pantalla 2022-05-17 a las 17 33 19" src="https://user-images.githubusercontent.com/6755973/168854018-54443262-cd9b-47c0-9ac1-3cb2882d4445.png">

### Steps to Reproduce

1. Download https://github.com/davidbritch/dotnet-maui-samples/tree/main/UserInterface/BrushesDemos
2. Launch the app on macOS.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.3.1

**Comment by VincentBu** [comment]
clicking `Linear gradient brush demos` doesn't work on Mac(vs main build)

**Comment by hermben** [comment]
As a workaround, you can replace Frame with ContentView to see if it also works for you:
Example code:

```
<ContentView
                HeightRequest="120"
                HorizontalOptions="FillAndExpand"
                Margin="-2"
                Padding="20, 45, 20, 0">
            <ContentView.Background>
                <LinearGradientBrush>
                    <GradientStop Color="#00A7B5" Offset="0.1" />
                    <GradientStop Color="#721474" Offset="1.0" />
                </LinearGradientBrush>
            </ContentView.Background>
</ContentView>
```

If you need border, border radius and shadow, you can combine **ContentView** with **Border** and **Shadow** MAUI elements.
