### ISSUE TITLE
iOS image in displaying as a black blob

### ISSUE THREAD

**Issue by emorell96** [dotnet/maui#7266]
### Description

I have an svg and when I try yo use it it just shows a black blob:
![image](https://user-images.githubusercontent.com/20151415/168866537-367f9e15-ca10-44d1-968d-249b112e5f14.png)

### Steps to Reproduce

1. Clone my repo: https://github.com/emorell96/RadioButtonsIosStyle
2. The "default_user.png" shows black.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

iOS

### Affected platform versions

ios 15

### Did you find any workaround?

None yet.

**Comment by emorell96** [comment]
This is to work fine in other previous afaik, at least in other platforms.

I worked it out that what makes it display is this options when creating the svg on illustrator:
![image](https://user-images.githubusercontent.com/20151415/168871530-5271ed6d-f5fc-40ce-af1e-5504b7baf5b4.png)

If you set the Styling to "Internal CSS" it fails in MAUI on iOS. I need to use "Inline Style" for it to work.

**Comment by emorell96** [comment]
It sounds related. If someone tried the reproduction repo on the current main, you could know if it was fixed by it since it was already merged.

**Comment by mattleibow** [comment]
I can't see the SVG from the OP, but it looks like that is the case. The CSS parser dies in the current RC, but is fixed in GA.
