### ISSUE TITLE
Not able to create Msix file for an application with a custom library referred directly

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#7268]
### Description

Getting the below error if an custom library is referred directly as project reference to an application for which "GenerateAppxPackageOnBuild" is set as true

"error : Improper project configuration: WindowsPackageType is set to None, but GenerateAppxPackageOnBuild is set to true."

### Steps to Reproduce

Create a MAUI Application.
Create a Library project and refer to the application.
Build using MSBuild in command prompt with GenerateAppxPackageOnBuild enabled

### Version with bug

Release Candidate 2

### Last version that worked well

Release Candidate 1

### Affected platforms

Windows

### Affected platform versions

Windows 19041

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Hey @PaulAnderson02 thanks for the report! IF possible, could you please be a bit more precise? Ideally even provide this in a GitHub repo.

What type of library are you adding exactly? What is the exact MSbuild command you're using?

And I see you mention RC2 while RC3 is out, was that in error or are you indeed on an older version?
