### ISSUE TITLE
ScrollView as child layout not working scrolling

### ISSUE THREAD

**Issue by pierrebrito** [dotnet/maui#7271]
### Description

![image](https://user-images.githubusercontent.com/6466875/168903335-dfa95649-6336-4445-9ecb-67dbe7f492b3.png)

### Steps to Reproduce

    <StackLayout Spacing="16"
                 Padding="16"
                 BackgroundColor="Red">
        <ScrollView>
            <StackLayout Spacing="16"
                         Padding="16"
                         BackgroundColor="Blue">
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
                <Label Text="1" />
            </StackLayout>
        </ScrollView>
    </StackLayout>

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment]
verified repro on android 11 with vs 17.3.0 Preview 2.0 [32516.434.main].

**Comment by hartez** [comment]
This is expected behavior. The StackLayout will expand vertically as much as it needs in order to lay out its children. It gives the ScrollView infinite space to expand, so the ScrollView does that. 

If you want to limit the ScrollView's viewport to the height of the screen, you'll need to use a different layout control, like a Grid or AbsoluteLayout.
