### ISSUE TITLE
Warning in MAUI when referencing a project with GenerateDocumentationFile true

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/maui#7272]
### Description

If you create a project reference from a MAUI project to a class library, and that project is generating XML documentation files, you get the following build warnings - two for each reference (one for iOS, one for maccatalyst):

```
Xamarin.Shared.Sdk.targets(1439, 3): The file '/Users/matt/Code/MyMauiApp/ClassLibrary1/bin/Debug/net6.0/ClassLibrary1.xml' does not specify a 'PublishFolderType' metadata, and a default value could not be calculated. The file will not be copied to the app bundle.
Xamarin.Shared.Sdk.targets(1439, 3): The file '/Users/matt/Code/MyMauiApp/ClassLibrary1/bin/Debug/net6.0/ClassLibrary1.xml' does not specify a 'PublishFolderType' metadata, and a default value could not be calculated. The file will not be copied to the app bundle.
```

### Steps to Reproduce

1. Create a new MAUI app (`dotnet new maui`, etc.)
2. Add a class library project to the same solution
3. Put some XML summary comments on the public members in that class library project.
4. Set `<GenerateDocumentationFile>true</GenerateDocumentationFile>` ([per this](https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#generatedocumentationfile)) in the csproj for the class library project
5. Reference the class library project from the MAUI app.
6. Compile and see the warnings

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

any

### Did you find any workaround?

I think this may be related or similar to https://github.com/xamarin/xamarin-macios/issues/14939, but the workaround there did not work for me, and I'm not sure if this is MAUI specific or not.

**Comment by VincentBu** [comment]
repro with vs main build(32522.39.main)
![image](https://user-images.githubusercontent.com/44959937/169731652-ef524d3d-dda0-40e0-b301-2a02deb1b892.png)

**Comment by mattjohnsonpint** [comment]
I've created a workaround.  Add this to the `.csproj` of the app (or place in a custom `.targets` file, etc.):

```xml
  <!-- Workaround for https://github.com/dotnet/maui/issues/7272 -->
  <Target Name="_SetPublishFolderTypeNoneOnDocFileItems" BeforeTargets="_ComputePublishLocation">
    <ItemGroup>
      <ResolvedFileToPublish Update="@(DocFileItem)" PublishFolderType="None" />
    </ItemGroup>
  </Target>
```

That will set the `PublishFolderType` metadata to `None` on all `DocFileItem` items (the generated XML doc files), and prevent the warning.

I believe something like this should be done somewhere in [`Xamarin.Shared.Sdk.targets`](https://github.com/xamarin/xamarin-macios/blob/main/dotnet/targets/Xamarin.Shared.Sdk.targets) for a permanent fix.

**Comment by mattjohnsonpint** [comment]
Just an update, My workaround above did remove the error, but it also broke everything because I was mistaken in thinking `@(DocFileItem)` will still be available.  It's not.  Here's one that actually works.

```xml
  <!-- Workaround for https://github.com/dotnet/maui/issues/7272 -->
  <Target Name="_SetPublishFolderTypeNoneOnDocFileItems" BeforeTargets="_ComputePublishLocation">
    <ItemGroup>
      <ResolvedFileToPublish
        Update="@(ResolvedFileToPublish)"
        Condition="'%(ResolvedFileToPublish.Extension)' == '.xml' And '%(ResolvedFileToPublish.PublishFolderType)' == ''"
        PublishFolderType="None" />
    </ItemGroup>
  </Target>
```

Though, it does presume that any `.xml` file that doesn't have a `PublishFolderType` set already must have it set to `None`.  Is there a better way to know if a file was a generated doc file, at this point in the build process?

**Comment by mattjohnsonpint** [comment]
FYI, this happens not just on MAUI, but also with an app made via `dotnet new ios`.  Should I close this and open a new issue on https://github.com/xamarin/xamarin-macios?

**Comment by jfversluis** [comment]
If it also happens on iOS without .NET MAUI involved then yes please move it there. Thanks!
