### ISSUE TITLE
MAUI Application.Current.MainPage (17.3.0) = new Shell causes title bar to go translucent

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#7274]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-ApplicationCurrentMainPage-173/10044203)._

---
[severity:Other]
If you set Application.Current.MainPage to a new Shell derived class that loads a new ShellContent, the window's title bar turns transluscent as well as the control buttons (minimize, maximize and close) to be invisible on Windows 10 using VS 2022 preview 17.3

If you open a new window with the same shell and shellcontent, the title bar and control buttons are fine.

---
#### Feedback Bot on 5/16/2022, 11:07 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
This should be fixed in 7.0 RC2

**Comment by AathifMahir** [comment]
Facing this issue on Stable Build of Maui, Any Plans to Provide this Fix for Stable?
