### ISSUE TITLE
Resetting Window Page does not update UI

### ISSUE THREAD

**Issue by dansiegel** [dotnet/maui#7275]
### Description

When resetting the navigation stack within the Window by changing the value of the Page on a Window, the UI does not properly reflect the new Page content that should be displayed. 

**NOTE:** This *MAY* be related to #7153. 

For a sample see: https://github.com/dansiegel/Prism.Maui/tree/maui-navigation-bug

### Steps to Reproduce

1. After the app has loaded reset the value of the `Window.Page`
```cs
var currentWindow = _app.Windows.First();
currentWindow.Page = new SomeOtherPage();
```

**NOTE:** This will fail silently as the Window.Page will reflect that Page is now SomeOtherPage, but the UI will not reflect that

```cs
var currentWindow = _app.Windows.First();
var page = new SomeOtherPage();
page.Dispatcher.Dispatch(() => currentWindow.Page = page);
```
**NOTE:** This will generate an exception like `Microsoft.Maui.Handlers.PageHandler found for PrismMauiDemo.Views.RootPage is incompatible`

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android

### Did you find any workaround?

Instead of trying to reset the Page of the currently displayed window, adding a new Window instead does work as a work around.

```cs
var currentWindow = _app.Windows.First();
var newWindow = new Window { Page = new SomeOtherPage() };
_app.OpenWindow(newWindow);
_app.CloseWindow(currentWindow);
```

**Comment by VincentBu** [comment]
not repro with vs main build(32627.385)

**Comment by jBijsterboschNL** [comment]
Any updates on this issue?
