### ISSUE TITLE
.Net Maui Multiple Listview errors and program crash on VS2022 (64-bit) Preview Version 17.3.0 Preview 1.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#7276]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-Maui-Multiple-Listview-errors-and-p/10039156)._

---
[severity:I'm unable to use this version]
All these bugs can be created by the attached solution (MauiAppMultiListViewBug.sln) and targeting Windows.

Bug#1 - Buttons in a proportional grid don't respect grid column actual size.  If the Page is resized to be less than the width of the 3 buttons, the buttons aren't cut as expected (ButtonsNotBeingCutWhenGridColumnIsLessThanButtonWidth.png)

Bug#2 - ListView column items don't respect a column that goes to zero when LineBreakMode="TailTruncation".  If the Page is resized to squeeze the * column to zero, subsequent columns stomp on columns previous to * column. (ListViewColumnsSteppingOnOtherColumnsPriorToStarColumn.png)

Bug#3 - Program Crash on Page resize when multiple ListView controls present on a page AND one ListView has a certain number of elements.  The Exception is sometimes "Element not found. (0x80070490)", sometimes "A cycle occurred while laying out the GUI.".  To create this bug, load the 60 items in the left ListView and resize the page width.  Loading 5 or 10 items doesn't cause this exception. (ElementNotFoundExceptionWhenResizingPageWithMultipleListViews.png and CycleLayoutExceptionWhenResizingPageWithMultipleListViews.png)

---
#### Feedback Bot on 5/11/2022, 11:04 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
This is way old and not much traction here. Please try the latest versions available and open a new issue if this still affects you, thanks!
