### ISSUE TITLE
Use of ContentPresenter in a ControlTemplate will cause app to exit on Windows but not Android

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#7278]
### Description

If I run the app in Android. The app runs as expected. However when I run the app on Windows it exits with the following error : 
Exception = {"A cycle occurred while laying out the GUI."}
"Layout cycle detected.  Layout could not complete."

If I comment out a single line in the ControlTemplate, namely : `<ContentPresenter` Grid.Row="1" `/>`
the app will run on Windows.

### Steps to Reproduce

Run the ControlTemplateDemos at dotnet-maui-samples\Fundamentals\Templates\ControlTemplateDemos\ControlTemplateDemos on a windows PC
select : "Change a ControlTemplate at runtime" or "Add content to the ControlTemplate" (last 2 in list)
the app will immediately exit with the error listed above.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

Comment out line : `<ContentPresenter Grid.Row="1" />` line #41 in HeaderFooterPage.xam
[ControlTemplateDemos.zip](https://github.com/dotnet/maui/files/8711970/ControlTemplateDemos.zip)
l

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Repro on Windows with above project.

**Comment by davefxy** [comment]
I don’t believe I have the most current workload to be able to help with testing. Sent from Mail for Windows From: Javier SuárezSent: Wednesday, May 18, 2022 8:15 AMTo: dotnet/mauiCc: Davefxy; AuthorSubject: Re: [dotnet/maui] Use of ContentPresenter in a ControlTemplate will cause app to exit on Windows but not Android (Issue #7278) Cannot reproduce with:—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
