### ISSUE TITLE
.NET MAUI source view showing errors - lots of them!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#7279]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-source-view-showing-errors---l/10022688)._

---
[severity:I'm unable to use this version]
I have a .NET MAUI application. I've added code to it and am finding that when I'm set on Android, there are errors showing in the Android platform code (missing namespace issues with Android.* names for example). This also applies if I move to iOS or the other platforms (lots of wobbly lines under code). It is also showing that interfaces are available from my project and anything else in the shared code is not available or missing.

Intellisense is also reporting that code is not available for the different platforms (for example, if I'm in the iOS project, I'd expect to only see that Foundation is available in iOS, but not that it's unavailable on the others)

---
#### Feedback Bot on 4/25/2022, 07:48 PM: 

(private comment, text removed)
#### Mandy Yu(CSI Interfusion Inc) [MSFT] on 4/27/2022, 02:00 AM: 

(private comment, text removed)
#### Paul Johnson on 4/27/2022, 03:50 AM: 

(private comment, text removed)
#### Mandy Yu(CSI Interfusion Inc) [MSFT] on 4/28/2022, 07:12 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drasticactions** [comment]
Judging by the dates on this feedback, it was pre-17.3 P1, which should have fixed that issue.

**Comment by bryancass** [comment]
I am experiencing (I think?) a similar issue where there are false errors in the VS2022 v17.5 P1.0 Error List.  If you would like further info of if I can try config changes in the IDE, let me know.  Attached screen shot error list, although project compiles and runs without a problem.
![Untitled](https://user-images.githubusercontent.com/57223041/207201034-c8652f24-ba17-46f8-959d-0721894a235d.png)

**Comment by jfversluis** [comment]
Going to assume this is fixed by now. If not, please let us know by filing a new issue, thanks!
