### ISSUE TITLE
[Enhancement] more color properties for controls!

### ISSUE THREAD

**Issue by mhrastegary77** [dotnet/maui#728]
## Summary
i think some of these are common opinions for most of the Xamarin.Forms users :

- CollectionView/ListView's SelectedItem color
- RadioButton's outline and inline circle color
- Switch's outline and off color
- Hover BackgroundColor for every Clickable control since maui supports macOS and WinUi3 and these are like 2 of 4 main platforms
- StatusBar/Titlebar Color #998
-  Acrylic brushes #705 
- border color #12

**Comment by hartez** [comment]
> CollectionView/ListView's SelectedItem color

CollectionView's SelectedItem can already be styled (including, but not limited to, Color) using the VisualStateManager.

**Comment by Redth** [comment]
Closing this for now, it seems issues are either addressed, or tracked separately.
