### ISSUE TITLE
Running app on Android fine but immediately exits on Windows : "Layout cycle detected. Layout could not complete."

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#7280]
### Description

If I run the app on an Android works as expected. Same app on Windows gets an error when selecting
  "ScrollView as the root layout".
The app is `davidBritch\dotnet-maui-samples\UserInterface\Views\ScrollViewDemos`
The error is 👍 `Error : {"A cycle occurred while laying out the GUI."}
           Message = "Layout cycle detected.  Layout could not complete."`

### Steps to Reproduce

If I run the  app on Windows, get an error when selecting
  "ScrollView as the root layout".

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows 10.0.19041

### Did you find any workaround?

Don't run the app on Windows
[ScrollViewDemos.zip](https://github.com/dotnet/maui/files/8712053/ScrollViewDemos.zip)
.

**Comment by PureWeen** [comment]
this looks to be fixed on GA

<img width="602" alt="image" src="https://user-images.githubusercontent.com/5375137/168939375-d4a97d22-c188-4833-bda4-5853010ecea2.png">
