### ISSUE TITLE
Building untrimmed application on Android on Release ends with Exception 'Unable to find Java.Lang.AbstractMethodError constructor'

### ISSUE THREAD

**Issue by soundaranbu** [dotnet/maui#7284]
#6569 Issue still exists in 
- MAUI Blazor RC3, 
- Visual Studio Version 17.3.0 Preview 1.0. 
- Android 11 (API 30)
![image](https://user-images.githubusercontent.com/29944019/168728183-b03c2dbc-db02-456d-8a98-fbda875da360.png)

Attaching sample project here
[MauiSqliteErrorSample.zip](https://github.com/dotnet/maui/files/8704965/MauiSqliteErrorSample.zip)

Some Background:
- I'm using EfCore Sqlite here. Publishing with default MAUI project settings causes https://github.com/dotnet/efcore/issues/26383
- Hence, tried to disable `PublishTrimmed` & `RunAOTCompilation`. Now, I'm running into this error.
@Redth  @Eilon

_Originally posted by @soundaranbu in https://github.com/dotnet/maui/issues/6569#issuecomment-1128381993_

(Recreating as the original issue was closed)

**Comment by janseris** [comment]
Does this still happen if you clean bin and obj folder? I don't remember how I solved my issue but I am now able to use EF Core with Trimming false in Release fine.
And surprisingly with trimming true on Release (I don't know what fixed it but I only keep adding code, not removing)

(Android)

**Comment by soundaranbu** [comment]
Clean build also thrown error. I'll try again once more. Between, were you able to build the sample project attached above?

**Comment by soundaranbu** [comment]
> If you try building this on a net6 app without maui (ex `dotnet new android`) and try doing it, does it still break?

No, it doesn't

**Comment by wch1618** [comment]
Use the default vs 2022 preview created maui blazor app would exit after the logo hide with publishing command 'dotnet publish -f:net6.0-android -c:Release -p:PublishTrimmed=false' .But publish without '-p:PublishTrimmed=false', the app runs correctly.

**Comment by jovanmhn** [comment]
Can confirm this is still a thing, its a bit disheartening considering how old this issue is...
Has anyone found a workaround?
Entity Framework is not trimming compatible (yet), trimming deletes essential code.
Untrimmed release config won't build, so its a bit of a dead end :(

This is still an issue as of VS 17.3.6, .NET6 (6.0.402) and:
"Microsoft.EntityFrameworkCore" Version="6.0.10"
"Microsoft.EntityFrameworkCore.Abstractions" Version="6.0.10" 
"Microsoft.EntityFrameworkCore.Analyzers" Version="6.0.10" 
"Microsoft.EntityFrameworkCore.Relational" Version="6.0.10" 
"Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.10" 

I would like to add that apps built in debug mode, work flawlessly.

**Comment by scriptBoris** [comment]
NET7.0 has problem too
Any news?

**Comment by Redth** [comment]
@jonathanpeppers any ideas?

**Comment by drasticactions** [comment]
https://github.com/dotnet/maui/issues/14605

This is still happening.

**Comment by jonathanpeppers** [comment]
@rbrettj can you give more information about your issue in #14605?

1. What *is* the crash? You can do this to get a log:

```sh
# enable Mono's logging
adb shell setprop debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all
# clear the log
adb logcat -c
# launch your app/cause the crash
...
# save the log
adb logcat -d > log.txt
```
Share `log.txt` here.

2. Does upgrading to .NET 7 solve the issue?

**Comment by rbrettj** [comment]
@jonathanpeppers no, the issue still exist on .NET 7. Exact same error as listed above.

**Comment by jonathanpeppers** [comment]
@rbrettj can you share some details about the settings you changed? Why are you disabling trimming?

**Comment by rbrettj** [comment]
What info do you need exactly? Why I'm disabling trimming is irrelevant. It is a feature and thus should work correctly regardless. The issue isn't my code since it fails with File -> New MAUI project. This should be something _easily_ reproduceable.

**Comment by jonathanpeppers** [comment]
The info here would be a great start, if you could get it that would great, thanks: https://github.com/dotnet/maui/issues/7284#issuecomment-1511383946

Turning off `$(PublishTrimmed)` is not something you would do by default, and shouldn't have to change in mobile apps. So the easy suggestion is "don't do that?".

**Comment by soundaranbu** [comment]
Hi @jonathanpeppers, sorry I was away for sometime. 

The reason is that not all the libraries are trim compatible. In my case, I had no other option other than to set the `PublishTrimmed` to false to use the libraries in Release mode.

**Comment by janseris** [comment]
For example EF Core isn't trim compatible afaik for MAUI.

**Comment by janseris** [comment]
> The info here would be a great start, if you could get it that would great, thanks: [#7284 (comment)](https://github.com/dotnet/maui/issues/7284#issuecomment-1511383946)
> 
> Turning off `$(PublishTrimmed)` is not something you would do by default, and shouldn't have to change in mobile apps. So the easy suggestion is "don't do that?".

Sounds like a nice suggestion for everything what is bugged in MAUI - don't use it?

**Comment by jonathanpeppers** [comment]
> The reason is that not all the libraries are trim compatible. In my case, I had no other option other than to set the PublishTrimmed to false to use the libraries in Release mode.

I think a better solution here is to exclude a single assembly instead of turning off trimming entirely, something like:

```xml
<ItemGroup>
  <TrimmerRootAssembly Include="MyAssembly" />
</ItemGroup>
```

https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options

Otherwise your app could be 100 MB or so? As it will include all of the BCL.

What we're looking for here is a stack trace/log if anyone is still hitting this issue in .NET 7.

**Comment by soundaranbu** [comment]
@jonathanpeppers The info that you are asking is for a runtime crash? But this is rather a build time error in VS after adding the property `PublishTrimmed` false. Repro steps here #14605 
As many people confirmed, this still seems to an issue in .NET 7. (Please try the repo steps in #14605). An existing project will normally compile fine.

This property need not be added to a new project. One may add it much later(like me) when they try to publish the app in Release mode and find that some of the libraries are not trim compatible.
I guess this is a most common scenario where many people will come across and it gives a bad user experience. That's my humble opinion.

**Comment by jonathanpeppers** [comment]
So the steps works for me, hence the confusion:
```
dotnet new maui
dotnet build -c Release -f net7.0-android -p:RunAOTCompilation=false -p:PublishTrimmed=false -bl
...
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:35.87
```
If it is a build error then a [diagnostic build log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) is what we would need here (or a sample project).

Could a specific NuGet package required to reproduce this issue?

**Comment by Redth** [comment]
Also worth noting in net7 the default is now `<TrimMode>full</TrimMode>` which means regardless of stated trimmer compatibility for a library, it's by default included in trimming.  You can set `<TrimMode>partial</TrimMode>` to trim only assemblies which declare themselves as trimmer safe.  This is a bit more heavy handed than setting individual root assemblies as @jonathanpeppers is suggesting though.

**Comment by soundaranbu** [comment]
Is this an issue with Visual Studio then? Have you tried in VS?

**Comment by Redth** [comment]
You can get a binlog from Visual Studio with the [Project System Tools Extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022).

That would be helpful.

**Comment by jonathanpeppers** [comment]
@Redth in .NET 7 `$(TrimMode)` defaults changed, but for iOS and Android we still default to `TrimMode=partial`:

https://github.com/xamarin/xamarin-android/blob/56875061ca04bd2c18d787d0df79143418a85e82/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L71

I actually think that `TrimMode=full` broke some things, and we couldn't use it for mobile.

**Comment by soundaranbu** [comment]
> You can get a binlog from Visual Studio with the [Project System Tools Extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022).
> 
> That would be helpful.

I'm away and awaiting the logs from my end will only prolong the fix.

The repro steps in #14605 are straight forward and quite simple to try. But it has to be tried **exactly as it is** (No CLI). If it's not reproducible, then I'm more than happy to try & provide the required VS logs. 

If it's not possible from my side, then @rbrettj may also help.

Thanks for all the hard work you people are putting in.

**Comment by soundaranbu** [comment]
Finally, I got a chance to try to reproduce this issue in the latest Visual Studio Preview release v17.7 Preview 2. But I couldn't reproduce it any longer. Hence I'm closing this issue. Thanks, everyone!
