### ISSUE TITLE
EmbeddedResource is not working with SVG image

### ISSUE THREAD

**Issue by PaulAndersonS** [dotnet/maui#7288]
### Description

A svg image is set to build action as EmbeddedResource and assigned to an Image control. It shows blank.

```xaml
<Image
                Source="{local:ImageResource image}"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="200"
                HorizontalOptions="Center" />
```

```cs
[ContentProperty("Source")]
public class ImageResourceExtension : IMarkupExtension<ImageSource>
{
    public string? Source { set; get; }

    public ImageSource ProvideValue(IServiceProvider serviceProvider)
    {
        if (String.IsNullOrEmpty(Source))
        {
            IXmlLineInfoProvider? lineInfoProvider = serviceProvider.GetService(typeof(IXmlLineInfoProvider)) as IXmlLineInfoProvider;
            IXmlLineInfo lineInfo = (lineInfoProvider != null) ? lineInfoProvider.XmlLineInfo : new XmlLineInfo();
            throw new XamlParseException("ImageResourceExtension requires Source property to be set", lineInfo);
        }

        string? assemblyName = typeof(ImageResourceExtension).GetTypeInfo().Assembly.GetName().Name; //GetType().GetTypeInfo().Assembly.GetName().Name;
        return ImageSource.FromResource(assemblyName + ".Resources.Images." + Source, typeof(ImageResourceExtension).GetTypeInfo().Assembly);
    }

    object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
    {
        return (this as IMarkupExtension<ImageSource>).ProvideValue(serviceProvider);
    }
}
```

[MauiApp9.zip](https://github.com/dotnet/maui/files/8715597/MauiApp9.zip)

### Steps to Reproduce

Run the attached sample

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android

### Did you find any workaround?

no

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Repro on Android 12 with above project.

**Comment by mattleibow** [comment]
Android does not support SVG files as images. When we add it to the csproj and use the `<MauiImage>` build action, it actually converts them all to png files.

Is there a reason you need embedded resources as opposed to letting the build add them to the app package and then just using the filename?

**Comment by PaulAnderson02** [comment]
We are using the svg images in a custom library which is referred in a application and the application uses that svg images. So we embedd the image in the custom library.

Also svg images with build action MAUIImage used in a custom library is not working for a Image control that is inside the CustomLibrary
