### ISSUE TITLE
[Android] API 31 (Android 12) svg on splashscreen is not showing 

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7289]
### Description

SVG on splashscreen is showing on all previous versions of Android.
On Android 12, only the background color is rendered and the foreground image is not visible.
Discovered on Sony Xperia 5 II but Android Emulator with Android 12 has the same result.

**_Note: this happens when started directly from Visual Studio_**

Edit: also png splashscreen is not displayed

### Steps to Reproduce

Run MAUI app (app template is sufficient)
- watch splashscreen
- there is no ".NET" on the splashscreen (or any custom svg image when changed)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by kristinx0211** [comment]
verified this issue on android 12 with vs 17.3.0 Preview 2.0 [32517.445.main].

**Comment by AnjanaJois20** [comment]
The current behavior is splash is displayed in a circle in between the screen and not rendered full screen. When can we expect this fix from MAUI for Android version 12.

**Comment by mattleibow** [comment]
The issue with no images is duplicated from here https://github.com/dotnet/maui/issues/7404 and was fixed in this PR https://github.com/dotnet/maui/pull/8394

The issue with broken images is fixed here: #9509

The issue with the clipped round image is part of the new screenshot APIs Google has added. This is tracked here: #9794

**Comment by mattleibow** [comment]
And just and FYI, I found a nice and simple workaround for now until I can fix this in MAUI: https://github.com/dotnet/maui/issues/9794
