### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/maui#7291]
### Description

Ok well i tyr to made a SVG icon..

I made it in size 456 * 456

ok svg..
Hmm i dont get it..

My icon get total black or "fuckt"  up..

Can any body explain me...

How this work..

### Steps to Reproduce

Create new Maui project call it OS.CP.MAUI_RC3

overwrite the svg file...

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

all

### Did you find any workaround?

no

**Comment by Eilon** [comment]
@PirasathLuxchumykanthan can you upload your project to a GitHub repo so that we can see the exact SVG file that you have? Also please show screenshots or other information about what isn't working.

**Comment by Eilon** [comment]
Thank you for the extra info so that we can investigate.

**Comment by PirasathLuxchumykanthan** [comment]
Well i fix the issus i dont know.. why..

But seems like maui dot like "Adobe" i run the svg file by https://svgoptimizer.com/

and then it work...  strange but yes.. now it work

**Comment by VincentBu** [comment]
Feel free to repopen it or open a new issue if you run into this error in the future.
