### ISSUE TITLE
Android MenuItem acts differently on real/virtual device

### ISSUE THREAD

**Issue by AidarNurmukhametov** [dotnet/maui#7292]
### Description

Hello, I am developing [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/), and I experienced a bug described below. It has moderate severity, because it affects very significantly on real devices. As I can see, this bug could be reproduced ONLY on Android real devices, I cannot reproduce it on virtual one.

[Here](https://github.com/AidarNurmukhametov/BugToPing) you can find an example that demonstrates problematic behaviour.

### Steps to Reproduce

1. Choose real device as a deployment target.
2. Build and run [project](https://github.com/AidarNurmukhametov/BugToPing).
3. Notice that menu item named "Command" doesn't exist on screen 
4. Stop the app and make a few changes. Comment lines 26-42 in AppShell.xaml file, uncomment line 43.
5. Run app once again
6. Notice that now menu item is shown properly.
7. (Optional) Repeat steps 2-6 with virtual device and notice that result is different, menu item is always shown

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested with Android API 28 an 30

### Did you find any workaround?

No, replacing VerticalStackLayout with Grid had no impact

**Comment by AntonKosenkoDX** [comment]
@jfversluis Hello! Any update on this issue?

**Comment by jfversluis** [comment]
Nothing to share at the moment unfortunately!
