### ISSUE TITLE
Error		DEP0700

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#7299]
### Description

Having upgraded to the latest version of visuall studio I now get an error and unable to run on the windows platform.
I uninstalled and re-installed visual studio 2022 17.3 preview 1 to no avail.

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80073CF3] Windows cannot install package E948FD91-43C3-4B61-BAE6-69ABFCE890E6_1.0.0.1_x64__9zz4h110yvjzm because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.24217.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {}	PlcBrowser.Maui.Blazor			
 

### Steps to Reproduce

1 - upgrade to the latest vieual studio 2022 preview
2 - select the windows platform
3 - Run and observe the error
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80073CF3] Windows cannot install package E948FD91-43C3-4B61-BAE6-69ABFCE890E6_1.0.0.1_x64__9zz4h110yvjzm because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.24217.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {}	PlcBrowser.Maui.Blazor			

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Windows

### Affected platform versions

Windows server 2022

### Did you find any workaround?

No. I am stuck this worked before

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80073CF3] Windows cannot install package E948FD91-43C3-4B61-BAE6-69ABFCE890E6_1.0.0.1_x64__9zz4h110yvjzm because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.24217.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {}	PlcBrowser.Maui.Blazor
```

**Comment by JiuLing-zhang** [comment]
@ltemimi You can temporarily fix this by editing the platform file(Platforms\Windows\Package.appxmanifest).
![image](https://user-images.githubusercontent.com/78294929/169182251-94d7a145-36ab-40c8-a57f-4812100a6a3e.png)

**Comment by ltemimi** [comment]
Hi 
Great thanks it worked.
