### ISSUE TITLE
[Android] (Android 12 only) When app is started from device, icon is used as splashscreen

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7303]
### Description

This is maybe caused by Android 12 overriding the splashscreen behavior. I read that in Android 12, there is new splashscreen API. It seems like for all apps, the icon is used as splashscreen by default.

This applies to both `Debug` and `Release`. 
_This means that for release apps (production), icon is displayed as splashscreen for users._

The issue:
- when the app is executed from the device app menu, icon with its background is displayed as splashscreen image
- when the app is executed from Visual Studio, the splashscreen image does not render at all (https://github.com/dotnet/maui/issues/7289)

### Steps to Reproduce

Run an app which has different splashscreen and icon image to observe the behavior.

```
<MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" Color="#512BD4" /> <!-- default -->
<MauiSplashScreen Include="Resources\bird.png" Color="Green" BaseSize="128,160"/> <!-- custom image and color -->
```

Started from phone:
![image](https://user-images.githubusercontent.com/64279914/169120972-189b436a-6f64-4ce1-9016-787537812903.png)
Started from Visual Studio:
![image](https://user-images.githubusercontent.com/64279914/169121348-6511ab46-70f8-4937-ab9e-dc2d36190cc2.png)

Android 11:
![image](https://user-images.githubusercontent.com/64279914/169121726-f2583443-25bc-4e08-881f-17c1a5515cf3.png)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by kristinx0211** [comment]
verified repro on android 12. repro project:
[MauiApp3.zip](https://github.com/dotnet/maui/files/8769025/MauiApp3.zip)

**Comment by jzhao8402** [comment]
I have the same problem on android 11 emulator and physical devices. It does not seem like only on android 12.

**Comment by kylewhittington** [comment]
I can confirm this behaviour on Android 12. No matter which splashscreen image I put in, it's still showing the ".NET" from the App Icon. Surely this is a big deal? Any workarounds? 12 is pretty ubiquitous.

**Comment by janseris** [comment]
@Eilon there is noone assigned to solve this issue and it has been confirmed again lately.

**Comment by AlexeyStarkov** [comment]
The issue is still there on a latest available preview

**Comment by supershopping** [comment]
After 3 months, still no plan to fix this issue? A splash screen is the first thing you see in an app.

**Comment by MagicAndre1981** [comment]
> After 3 months, still no plan to fix this issue? 

The issue is tracked now in [new issue - **Add support for Android 12+ Splash Screen APIs**](https://github.com/dotnet/maui/issues/9794):

**Comment by mattleibow** [comment]
Thanks @MagicAndre1981! As you mention, the issue is tracked in #9794 and will link to other issues of interest relating to splash screens.

**Comment by mattleibow** [comment]
And just and FYI, I found a nice and simple workaround for now until I can fix this in MAUI: https://github.com/dotnet/maui/issues/9794
