### ISSUE TITLE
[Android] MauiIcon BaseSize and ForegroundScale doesn't work

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7305]
### Description

There is no way to preserve aspect ratio or to scale the icon inside the icon area.
My app icon looks awful due to the fact that it stretches somehow through the icon area (both stretched and cropped when not a square probably).

Simulation of the MauiIcon behavior:
Image
![appicon](https://user-images.githubusercontent.com/64279914/169139841-d2bb741a-7f9c-4925-aece-090fad458adf.png)
Result:
![image](https://user-images.githubusercontent.com/64279914/169140276-e1e970e7-d4d7-41d3-8f23-a178efbb125a.png)

Setting `BaseSize` and `ForegroundScale` attributes on `MauiIcon` does nothing although the behavior is documented in https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons

### Steps to Reproduce

```
<MauiIcon Include="Resources\appicon.png" ForegroundFile="Resources\appicon.png" >
	<BaseSize>32,32</BaseSize>
	<ForegroundScale>0.65</ForegroundScale>
</MauiIcon>
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by VincentBu** [comment]
repro with vs main build(32522.39.main)
