### ISSUE TITLE
ListView item size differences Windows/Android

### ISSUE THREAD

**Issue by Michal-MK** [dotnet/maui#7312]
### Description

Let's have a simple `ListView` setup
```xaml
<ListView SelectionMode="None">
    <ListView.ItemsSource>
        <x:Array Type="{x:Type x:String}">
            <x:String>First</x:String>
            <x:String>Second</x:String>
            <x:String>Third</x:String>
        </x:Array>
    </ListView.ItemsSource>
    <ListView.ItemTemplate>
        <DataTemplate>
            <ViewCell>
                <Grid ColumnDefinitions="*" Margin="0, 32">
                    <Label Text="{Binding}"/>
                </Grid>
            </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```
This is how it looks on Windows
![image](https://user-images.githubusercontent.com/12874766/169164660-1af43422-9190-4254-a1ed-8b56d058a08b.png)

This is how it looks on Android
![image](https://user-images.githubusercontent.com/12874766/169164782-977de5d5-b574-48e1-8068-590da9e5292d.png)

Windows automatically adjusts the item size to match content, Android does not and instead uses some constant? value.

### Steps to Reproduce

1. Get the project [here](https://github.com/Michal-MK/MAUI-ListViewInconsistency)
2. Run on Windows and Android

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11, Windows latest I assume

### Did you find any workaround?

Setting `HasUnevenRows` to `true` makes it render as expected on Android, but the rows are even in this case so we are sacrificing performace? for something that should work with `HasUnevenRows="False"` as well.

**Comment by Qws** [comment]
I have this issue as well on Android.

Adding padding and/or margin to control doesn't seem to increase the size of the ViewCell.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 6.0, Not repro on Android platform with above project. 
[MAUI-ListViewInconsistency-master.zip](https://github.com/dotnet/maui/files/11428538/MAUI-ListViewInconsistency-master.zip)
![image](https://user-images.githubusercontent.com/77434865/237027431-7c9a4c04-9738-4e69-8903-cd9239aad4f3.png)
