### ISSUE TITLE
[Bug] What Happened to the MediaElement?

### ISSUE THREAD

**Issue by nicksilverstein** [dotnet/maui#7318]
### Description

What Happened to the MediaElement? Is it there? How do I access it? I need it for a project.

### Steps to Reproduce

<MediaElement>

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All OSs

### Did you find any workaround?

No but, if there is one please let me know?

**Comment by Eilon** [comment]
Hi, it looks like the MediaElement control was always part of the Xamarin Community Toolkit and not part of Xamarin.Forms itself: https://docs.microsoft.com/en-us/xamarin/community-toolkit/views/mediaelement.

There is a new .NET MAUI Community Toolkit as well, which has a proposal to add that feature: https://github.com/CommunityToolkit/Maui/issues/113

**Comment by pictos** [comment]
Yeap @Eilon is correct. We'll start to work on that control after MAUI GA. But I don't have a deadline to share right now.
