### ISSUE TITLE
Different order of Appearing Event and NavigatedTo Event when using Shell ?

### ISSUE THREAD

**Issue by yzbai** [dotnet/maui#7320]
### Description

I found when first time start into Shell, NavigatedTo event came first, then Appearing Event.
But at other situations, like go and back, Appearing Event came first.

Using NavigationPage instead of Shell, Appearing Event came first too.

Is there a order of Page.Appearing Event and Page.NavigatedTo events ? Like which occurs first?

### Steps to Reproduce

None

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

**Comment by PureWeen** [comment]
@yzbai `NavigatedTo` should come after `Appearing` 

Can you attach a repro?

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Repro on Android 11 with above project.
![image](https://user-images.githubusercontent.com/97647558/169432430-4b738a60-72dc-4f45-8202-a6e2907a2d15.png)

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 6.0. This issue does not repro on Android emulator (13.0-API 33) with below Project: [7320.zip](https://github.com/dotnet/maui/files/11412183/7320.zip)

I tried 3 times, Appearing event come first then NavigatedTo event.
![image](https://user-images.githubusercontent.com/97647558/236620354-5df8c6b6-be2d-4a7d-be27-de4bd02c6d46.png)
