### ISSUE TITLE
FlyoutBackgroundColor not working when FlyoutBehavior is locked.

### ISSUE THREAD

**Issue by JiuLing-zhang** [dotnet/maui#7321]
### Description

It's can work when FlyoutBehavior is not locked.
It's can work when using hot reload.

![image](https://user-images.githubusercontent.com/78294929/169243838-80701d68-a3bf-4335-a60d-9d9cadbf9dc5.png)

![image](https://user-images.githubusercontent.com/78294929/169245219-29e7a2d8-eb41-4f16-bd5c-c939076191b1.png)

source code:
[FlyoutBackgroundColorError.zip](https://github.com/dotnet/maui/files/8727107/FlyoutBackgroundColorError.zip)

### Steps to Reproduce

1. Create MAUI App.
2. Edit AppShell page.
3. Set FlyoutBehavior="Locked", FlyoutBackgroundColor="Red".
4. Run.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows Server 2019 Datacenter

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Not repro on Windows with above project.
![image](https://user-images.githubusercontent.com/97647558/169245134-d5c9aff4-0c18-497a-9e22-bcf70edca6f8.png)

**Comment by PureWeen** [comment]
This is fixed in GA

**Comment by Fabi** [comment]
> This is fixed in GA

Sadly MAUI is not GA ready at all. It gets pushed through tho which is very bad. But yes it's fixed on main
