### ISSUE TITLE
ScrollView layout not updating when child IsVisible is updated

### ISSUE THREAD

**Issue by paulvarache** [dotnet/maui#7322]
### Description

Using IsVisible on a descendent of a ScrollView doesn't update the ContentSize of the scroll view.

Only tested on Android. Reproduction repo: https://github.com/paulvarache/MauiIssueScrollViewLayout

In this example, the ScrollView still allows to scroll even after its content becomes smaller than its size

https://user-images.githubusercontent.com/5550089/169247056-c26c991a-162f-4fbe-93f1-ad827613b4a7.mp4

### Steps to Reproduce

1. Create a Maui App
2. Size the ScrollView to be smaller than its content
3. Programmatically update an View's IsVisible to make the content smaller than the scrollview

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Calling `Layout()` on the scrollView with its parent bounds after changing the visibility of the child view

**Comment by paulvarache** [comment]
It seems like calling `Layout` does not help. What makes the ScrollView layout properly is:
```csharp
scrollView.SetValue(VisualElement.HeightRequestProperty, 0); // Setting the value to scrollView.Height does not work
await Task.Delay(1); // a delay of 0 does not work
scrollView.ClearValue(VisualElement.HeightRequestProperty);
```
Unfortunately, this causes a flash of the content

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Repro on Android 11 with provided project.

**Comment by jfversluis** [comment]
Verified this is fixed in our current code, this should be part of the next service release!

https://user-images.githubusercontent.com/939291/177534564-0ae38e3e-897a-410c-9e11-065671f3698b.mov
