### ISSUE TITLE
TemplatedView can't find handlers

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7325]
### Description

Cannot find a correct Handler associated with TemplatedView
![image](https://user-images.githubusercontent.com/6755973/169281257-9904afb3-b914-485e-b30b-db462474ffcd.png)

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/TemplateMAUI
2. Launch the App and navigate to the Rate control gallery.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Windows SDK 10.0.17134.0, Android 11

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Repro on Windows. Sample Project: 
Exception message: "Microsoft.UI.Xaml.Controls.Frame.NavigationFailed was unhandled."

**Comment by mattleibow** [comment]
I also get this with my custom control. I was inheriting from `TemplatedView` because all my content is in the template and there is no need for a `Content` property. 

Maybe we do need a #6447

**Comment by mattleibow** [comment]
Fixed in #7771
