### ISSUE TITLE
[Windows] CollectionView cut off

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#7326]
### Description

After navigating to a page using CollectionView, if it has a scroll, nothing that is off screen is rendered.

![issue-layout](https://user-images.githubusercontent.com/6755973/169282890-7abbef14-d2f3-4aa5-a32c-2132c9decbb1.gif)

### Steps to Reproduce

Use the .NET MAUI Gallery.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17134.0

**Comment by jfversluis** [comment]
@jsuarezruiz is this still happening?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 5.0. Not repro on windows platform with my sample project.
[ManualMauiTests (1).zip](https://github.com/dotnet/maui/files/12246317/ManualMauiTests.1.zip)
![7326](https://github.com/dotnet/maui/assets/77434865/e2a651f0-2bf0-4112-94f4-ee8d274f4d91)
