### ISSUE TITLE
Entry.PlaceholderColor

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#733]
Depends on Brushes (#483).

IText.PlaceholderColor -> IText.PlaceholderBrush
Entry.PlaceholderColor implements IText.PlaceholderBrush using a SolidColorBrush of PlaceholderColor

Entry eventually gets a PlaceholdeBrush property, possibly in a future release.

**Comment by davidbuckleyni** [comment]
@PureWeen  he should add this to the date pickers and time pickers would be handler than setting to null?
