### ISSUE TITLE
Label rendered differently when using <Span> and FontAttributes="Bold"

### ISSUE THREAD

**Issue by Michal-MK** [dotnet/maui#7341]
### Description

Let's take this code:

```xaml
<Label Text="Note:" FontAttributes="Bold"/>
<Label>
    <Label.FormattedText>
        <FormattedString>
            <Span Text="Note:" FontAttributes="Bold" />
        </FormattedString>
    </Label.FormattedText>
</Label>
```

I consider these two equivalent. But when rendered on Android I get different results.

Android:
![image](https://user-images.githubusercontent.com/12874766/169363409-2b349c23-1edb-4a1a-8475-b2ed8d7eed75.png)

Windows:
![image](https://user-images.githubusercontent.com/12874766/169364260-0b78b2e9-269f-4738-a9e2-c31a3015c861.png)

Generaly on Windows the text looks blurred but that is for another issue. On Windows they look more simillar but not identical either.

### Steps to Reproduce

1. Paste the code into a VerticalStackLayout (in my case it was in a `ViewCell` but I assume this is irrelevant) and run on Android

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows 10

### Affected platform versions

Android 11, Windows latest I assume

### Did you find any workaround?

It works, but when the app uses `FormattedString` approach to render multiple `<Span>`s then to maintain consistency you have to use the `FormattedString` approach even for single `<Span>` labels. As shown in the example.

**Comment by VincentBu** [comment]
repro with vs main build(32519.297.main)
