### ISSUE TITLE
CollectionView Crash when clearing & adding data second time.

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/maui#7343]
### Description

See: https://github.com/dotnet-presentations/dotnet-maui-workshop/issues/49

### Steps to Reproduce

1.) Open https://github.com/dotnet-presentations/dotnet-maui-workshop "Finish folder"
2.) Launch on iOS
3.) Load monkeys
4.) Load Monkeys again -> crash

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS and possibly Mac (all versions)

### Did you find any workaround?

not yet ;(

**Comment by VincentBu** [comment]
I fail to retrieve data from https://www.montemagno.com/monkeys.json, so I comment your `Online` code and use the offline part.
not repro with vs main build(32519.297.main)

**Comment by michaelstonis** [comment]
I believe this is the same issue I experienced here: https://github.com/dotnet/maui/issues/7237

**Comment by yairp03** [comment]
Happened to me too, but only in a Grouped `CollectionView`

**Comment by yairp03** [comment]
A possible workaround is to use an `ObservableProperty` on a regular `List` and replace the entire object with each update, instead of using an `ObservableCollection`.
For example:
```csharp
[INotifyPropertyChanged]
public partial class MainViewModel
{
    [ObservableProperty]
    List<Monkey> monkeys = new();

    [RelayCommand]
    void ReloadMonkeys()
    {
        List<Monkey> newMonkeys = Monkeys is null ? new() : new(Monkeys);
        newMonkeys.Add(new("A1"));
        newMonkeys.Add(new("A2"));
        newMonkeys.Add(new("A3"));

        Monkeys = newMonkeys;
    }
}
```
instead of:
```csharp
public partial class MainViewModel
{
    public ObservableCollection<Monkey> Monkeys { get; } = new();

    [RelayCommand]
    void ReloadMonkeys()
    {
        Monkeys.Add(new("A1"));
        Monkeys.Add(new("A2"));
        Monkeys.Add(new("A3"));
    }
}
```

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 6.0, Not repro on iOS platform with above project. 
[dotnet-maui-workshop-main.zip](https://github.com/dotnet/maui/files/11430330/dotnet-maui-workshop-main.zip)
![Crash](https://github.com/dotnet/maui/assets/77434865/3554c3d5-fd7b-4c4b-9315-eb1a31bcfec9)
