### ISSUE TITLE
Running the ListViewDemo on win 11 gets Win32 unhandled exception, fatal error

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#7344]
### Description

I run the ListViewDemos app on windows. Select "scroll by item with grouping". Then select "Scroll to Proboscis Monkey". You will see the Win32 error
[ListViewDemos.zip](https://github.com/dotnet/maui/files/8733985/ListViewDemos.zip)
![Maui ListView Issu](https://user-images.githubusercontent.com/2566250/169397304-0a263287-6b1f-4a91-920b-e4b9785a8f94.png)
.

### Steps to Reproduce

run the ListViewDemos app on windows. Select "scroll by item with grouping". Then select "Scroll to Proboscis Monkey". You will see the Win32 error. The app is included above with a screenshot.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows 10.0.19041

### Did you find any workaround?

Dont make the selection listed abov.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Repro on Windows with provided project.

**Comment by jsuarezruiz** [comment]
This issue seems to be fixed by https://github.com/dotnet/maui/pull/7413

Tested with Windows 11 21H2,Visual Studio 2022 Version 17.3.0 Preview 1.1 and main branch.
