### ISSUE TITLE
CheckBox has default (empty) padding on Windows platform (Mac has no padding)

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/maui#7352]
### Description

CheckBox has default (empty) padding on Windows platform (Mac has no padding)

### Steps to Reproduce

1. Create a new MAUI project
2. Add CheckBox as below:

```
<StackLayout Orientation="Horizontal">
    <CheckBox IsChecked="{Binding XXX, Mode=TwoWay}" />
    <Label Text="XXX" VerticalOptions="Center" InputTransparent="True"/>
</StackLayout>
```

Result: Windows renders the CheckBox with about 90 pixels of empty padding on the right while Mac renders the CheckBox without any Padding

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

Yes, apply margin windows only on a control following the CheckBox:

```
<StackLayout Orientation="Horizontal">
    <CheckBox IsChecked="{Binding XXX, Mode=TwoWay}" />
    <Label Text="XXX" Margin="{OnPlatform WinUI='-90,0,0,0'}" VerticalOptions="Center" InputTransparent="True"/>
</StackLayout>
```

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 2.0 [32515.61.main]. Repro on Windows. Sample Project: [MauiApp3.zip](https://github.com/dotnet/maui/files/8735330/MauiApp3.zip)

![image](https://user-images.githubusercontent.com/97647558/169437008-2405eccd-0ebc-4d28-8aaa-e861b6842889.png)
