### ISSUE TITLE
MAUI project requires bin/obj folders removed for any MacOS build following a successful one

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/maui#7353]
### Description

MAUI project requires bin/obj folders removed for any build following a successful one

```
error : Failed to codesign 'xxx.app': xxx/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/xxx.app: replacing existing signature [xxx/xxx.csproj]
```

### Steps to Reproduce

It's not reproduced on a new MAUI project but 100% reproducible on an existing project. Steps:

1. Build a project once with `dotnet build -t:Run -f net6.0-maccatalyst`
2. Build the project one more time with the same command

Result - the error `Failed to codesign 'xxx.app'`

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS 12.3.1

### Did you find any workaround?

Remove bin/obj folders before each build

**Comment by VincentBu** [comment]
I follow the repro steps described above and don't run into this error.

**Comment by alexeystrakh** [comment]
In our particular case, the issue was related to custom build steps, that created extra files and preventing the app from being properly signed.
