### ISSUE TITLE
Border has no Background on Android, iOS is fine

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#7356]
### Description

I'm using a `Border` control for the `WelcomePage`.
On iOS, the `BackgroundColor` set in the `Style` is applied.

However on Android not.

XAML

```xaml
<Border
      Style="{StaticResource CardViewBorderStyle}"
      Margin="20,5"
      Grid.Row="1"
      >
</Border>
```

```xaml
<Style x:Key="CardViewBorderStyle" TargetType="Border">
        <Setter Property="StrokeShape">
            <Setter.Value>
                <RoundRectangle CornerRadius="30" />
            </Setter.Value>
        </Setter>
        <Setter Property="StrokeThickness" Value="1"/>
        <Setter Property="Shadow" Value="{StaticResource CardViewShadowStyle}"/>
        <Setter Property="BackgroundColor" Value="{DynamicResource Gray-100}"/>
    </Style>

    <Color x:Key="Gray-100">#F5F5F5</Color>
```

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-05-20 at 08 38 10](https://user-images.githubusercontent.com/2952443/169468436-7904e91c-b27c-4129-b5c4-c9133529f2e4.png)

![Screenshot_1653027380](https://user-images.githubusercontent.com/2952443/169468489-4befa436-3cb5-40d2-8b23-5f637e33a96c.png)

### Steps to Reproduce

1. Create a Border control and apply the Style
2. Run on iOS and Android

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jsuarezruiz** [comment]
This issue have been fixed by https://github.com/dotnet/maui/pull/7247
![Screenshot_1653042576](https://user-images.githubusercontent.com/6755973/169509643-4cb8ae26-972e-4837-afd9-a8d9837cce5a.png)
Will be available in the next release (GA).

For now, as workaround, just set the Stroke with the same color used in the Background.
