### ISSUE TITLE
WinUI Touch keyboard does not open on Windows 10 (Tablet mode)

### ISSUE THREAD

**Issue by An0d** [dotnet/maui#7361]
### Description

On Windows 10 (tablet mode) The touch keyboard does not open when typing in an Entry or Editor field
On Android, no problem, the keyboard opens properly

On the other hand, in Excel, it works. When entering the formula field, keyboard opens properly

Tested on Panasonic toughbook CF-20 MK2
Windows 10  version 1909 (build 18363.2212)

### Steps to Reproduce

1. Create a new MAUI project with the default template
2.  Add a simple Entry
3. Launch the application on Windows 10 with Tablet mode activated
4. Tap in the Entry field
5. Touch keyboard does not open

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

**Comment by drasticactions** [comment]
Did you try making a WinUI3 app (Without MAUI, create an entry field, and try tapping it?

**Comment by An0d** [comment]
> Did you try making a WinUI3 app (Without MAUI), create an entry field, and try tapping it?

Nope.
I tried with a classic Winform app and it works.

Will follow your advice and try on a simple WinUI app

**Comment by An0d** [comment]
> Did you try making a WinUI3 app (Without MAUI), create an entry field, and try tapping it?

Hello,

Just tried with a WinUI app and got the same problem. Touch Keyboard does not show up when entering a Textbox :(

**Comment by drasticactions** [comment]
I would file this problem under https://github.com/microsoft/microsoft-ui-xaml and let them know if it's not already tracked.

Since MAUI uses WinUI3 under the covers, if it doesn't work there, then it can't work for MAUI.

**Comment by An0d** [comment]
> I would file this problem under https://github.com/microsoft/microsoft-ui-xaml and let them know if it's not already tracked.
> 
> Since MAUI uses WinUI3 under the covers, if it doesn't work there, then it can't work for MAUI.

Found one issue here 
https://github.com/microsoft/microsoft-ui-xaml/issues/6291

Sorry for the inconvenience
