### ISSUE TITLE
Label cut-off inside Grid with multiple *-columns

### ISSUE THREAD

**Issue by PieEatingNinjas** [dotnet/maui#7363]
### Description

I've found two scenarios where there's something wrong with the size of a `Label`.

Scenario 1
1. The `Label` is set inside a `Grid` which has multiple *-columns
2. The `Label` doesn't span the entire width of the `Grid` (`Grid.ColmnSpan` < #Columns)
3. `RowDefinition` of the `Grid` is set to `Auto`

```
<Grid ColumnDefinitions="10,*, *,10" RowDefinitions="Auto">
    <Label Grid.ColumnSpan="2" Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis convallis nunc, vitae ullamcorper enim. Etiam diam tortor,  END" />
</Grid>
```

Scenario 2
1. The `Label` is set inside a `Grid` which has multiple *-columns
2. The `Label` doesn't span the entire width of the `Grid` (`Grid.ColmnSpan` < #Columns)
3. `Grid` sits inside a `ScrollView`

```
<ScrollView>
    <Grid ColumnDefinitions="10,*, *,10">
        <Label Grid.ColumnSpan="2" Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis convallis nunc, vitae ullamcorper enim. Etiam diam tortor,  END" />
    </Grid>
</ScrollView>
```

In both these scenarios, the `Label` doesn't get the right size, it isn't heigh enough. 

![image](https://user-images.githubusercontent.com/13808075/169541738-b0a64715-ce6f-4e7f-8b74-b5aec7ea1d81.png)

The `Label` does render nicely when it can take up all * columns...

I see the exact same behavior when putting something like the above code in the `ItemsTemplate` of a `CollectionView`.

Seen this behavior on Windows and Android. Haven't checked on iOS.

### Steps to Reproduce

1. Create File -> new MAUI app
2. Remove code (except ctor) from MainPage.xaml.cs
3. Paste the XAML of one of the two scenarios
4. Run!

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 10.0.17763.0, Android 21

**Comment by VincentBu** [comment]
repro with vs main build(32522.39.main), additionally, I run into this issue on IOS emulator.
