### ISSUE TITLE
Ship my Xamarin.UITest to work with MAUI framework

### ISSUE THREAD

**Issue by bhuvi4login** [dotnet/maui#7368]
Hi Team,

I am seeing MAUI coming into picture. We have Xamarin.UITests developed for the mobile app developed using Xamarin and running those UITests now in Azure pipelines.

What is the name of Xamarin.UITest in MAUI? Do we have MAUI.Test or any such test frameworks? So I can ship my existing test cases of the project against the new MAUI framework, which could be easy as adding package and it should work, my expectation.

**Comment by bhuvi4login** [comment]
I need replacement for this test framework from Microsfot: https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/

**Comment by rmarinho** [comment]
It should work on Android right now and they working to enable it to work wit iOS as pointed above.
