### ISSUE TITLE
[Android] Soft Input Resize doesn't properly resize

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#7369]
### Description

With android, handling the on screen keyboard (or soft input), there's a couple of options to deal with the change in screen real estate, including Pan and Resize.

At some point, Resize stopped working well in both Xamarin.Forms and .NET MAUI.  
There's a workaround listed here: https://stackoverflow.com/questions/34013548/xamarin-forms-2-0-appcompat-android-keyboard-mode which points at a google issue: https://code.google.com/p/android/issues/detail?id=5497 which basically uses a view tree observer to change things based on the visible part of the window with the keyboard open.

I have a video which shows the Xamarin.Forms code implementing this workaround on the left side, and then the current MAUI code without the workaround on the right side.

https://user-images.githubusercontent.com/271950/169559836-95194b09-db14-4c55-8f20-17b3ed21330e.mp4

### Steps to Reproduce

1. Create an app with a bunch of Entry's inside a scrollview so that the scrolling area extends past the height of the screen
2. Set the soft input mode on the app to Resize

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

N/A

**Comment by stegl83** [comment]
Hi,
I had the same issue and found out something interesting!
My application has a page with one entry and my own commandBar-Control docked on bottom.

        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="12"/>
                <RowDefinition Height="*"/>
                <RowDefinition Height="Auto"/>
            </Grid.RowDefinitions>

            <Entry Grid.Row="0"/>

            
            <mctk:CommandBar Grid.Row="3">
                <mctk:CommandBar.PrimaryCommands>
        ...
                </mctk:CommandBar.PrimaryCommands>
            </mctk:CommandBar>
        </Grid>
 
When setting the focus on the entry the InputPanel comes up and hides the commandbar.

But when I add one senseless ScrollViewControl like this:

        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="12"/>
                <RowDefinition Height="*"/>
                <RowDefinition Height="Auto"/>
            </Grid.RowDefinitions>

            <Entry Grid.Row="0"/>

            
            <ScrollView Grid.Row="2"/>

            
            <mctk:CommandBar Grid.Row="3">
                <mctk:CommandBar.PrimaryCommands>
        ...
                </mctk:CommandBar.PrimaryCommands>
            </mctk:CommandBar>
        </Grid>

Page Resize works fine on setting focus on Entry!

**Comment by Kremed** [comment]
I'm still facing this problem, any updates?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 5.0. Not repro on android platform with template MAUI project.
![7369](https://github.com/dotnet/maui/assets/77434865/4ee23d73-3715-42f5-b06b-6d23af9acdce)
