### ISSUE TITLE
ContentPage > BackgroundColor attribute not working on Windows

### ISSUE THREAD

**Issue by nicolgit** [dotnet/maui#7376]
### Description

the following page
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Blast.View.SettingsPage"
             Title="Settings"
             BackgroundColor="Red"
             >
</ContentPage>
```  

Create a sample app and add the following page.
It results in a dark page on windows (theme color), while appairs Red on Android (correct!)

### Steps to Reproduce

see above.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

if update the XAML using the hot reload, bacground becomes red.

**Comment by pekspro** [comment]
This is duplicate: https://github.com/dotnet/maui/issues/7036

I hope we get a new version next week ;-)

**Comment by kristinx0211** [comment]
verified not repro on window with 17.3.0 Preview 2.0 [32522.62.main].
![image](https://user-images.githubusercontent.com/99457000/169759209-2c4bc333-284f-4cfb-a265-23f74436b959.png)
